# -*- org -*-

# Time-stamp: <2011-08-19 23:00:18 Friday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 风云激荡下的世界局势

[2011-02-13 13:57:40]

一、新闻链接

 

新闻1：酝酿了6年之久的苏丹南部公投结果2月6日出炉，99%以上的投票者赞同南方独立，南方独立几无悬念。据外电报道，连日来，南部苏丹政府军与反叛分子爆发激烈冲突，已造成至少100人丧生。

新闻2：新华网萨那1月27日电  约1．5万名示威者1月27日在也门首都萨那举行集会，抗议也门政府及相关政策。新华网萨那2月12日电约5000名也门民众12日在首都萨那举行针对政府的示威游行。也门人口总数为2300万。据2008年也门政府公布的数据，当时全国失业率达35％。此后也门政府未再公布失业率，但媒体普遍报道说，目前也门失业率已超过40％。

新闻3： 2010年12月19日至20日，突尼斯有大学毕业生自焚抗议失业，引发骚乱，数十人被捕。2011年1月8日至10日，3天暴乱，超过50人在冲突中身亡。1月14日，全国爆发示威，本·阿里解散政府，出走沙特。15日凌晨，位于首都南部的莫纳斯提尔市的马赫迪耶监狱发生囚犯越狱纵火的事件，目前官方称已有至少42人死亡，约1200名犯人全部逃跑。

新闻4：1月，阿尔及利亚数省发生骚乱，一些游行示威者与警方发生冲突。据阿尔及利亚《晨报》报道，“全国民主和变革协调委员会”不顾阿尔及利亚当局的禁令，号召于12日在首都阿尔及尔各全国各省举行要求“改变体制”的示威游行。该组织是今年1月21日成立的反对派联盟，阿尔及利亚主要反对党“争取文化和民主联盟”即该组织成员。据卡塔尔半岛电视台报道，“争取文化和民主联盟”领导人声称，当局正在采取行动阻止抗议活动，大批警察被调往首都阿尔及尔，火车和其它公共交通工具停运。报道援引这位反对党领导人的话说，1月22日举行的上一次抗议活动引发冲突，造成5人死亡，800多人受伤。

新闻5：国际在线专稿：据克罗地亚国家通讯社2月11日报道，现年75岁的意大利总理贝卢斯科尼在2月11日接受意大利《印刷品报》采访时承认，自己“有时也会犯错”。意大利警方已正式向米兰法院申请启动对贝卢斯科尼的审判，目前针对贝卢斯科尼的指控包括与未成年人进行性交易以及滥用职权。米兰法院日前证实，贝卢斯科尼曾与“大量”的女性进行性交易，其中包括17岁的摩洛哥姑娘卡利玛·玛洛。她是一名夜总会的舞娘，艺名“鲁比”。检方同时证实，贝卢斯科尼曾利用职权向警方施压，令其最终释放被怀疑犯有盗窃罪的“鲁比”。

新闻6：法国政府的外交部长和总理相继被爆料说，近期到突尼斯埃及度假都享受了当地政府的特殊安排，这一系列“度假门事件”更是让处在危机中的执政党是面临强烈谴责。据中国之声《新闻纵横》报道，出于对退休改革的不满而引发的罢工浪潮一度扰乱了法国港口秩序。11日，法国国民教育部门也举行抗议退休改革之后的首次全国性大罢工，而第三桩罢工潮是发生在法国的司法界。

新闻7：2010年11月1日，俄国总统梅德韦杰夫视察了南千岛群岛(日本称北方四岛)， 12月13日，俄国第一副总理舒瓦洛夫继续登岛。2011年 2月7日，在东京召开的“要求归还北方领土全国大会”上，菅直人首相指名道姓地说，梅德韦杰夫总统视察南千岛群岛“是个不能容忍的粗暴之举”。梅德韦杰指令国防部长谢尔久科夫，必须在日俄有归属争议的南千岛群岛部署足够的现代化军事装备，确保岛屿安全，又强调南千岛群岛是俄罗斯不可分割的一部分。梅德韦杰夫又呼吁邻国——包括中国及韩国——到南千岛群岛投资。

 

 

二、世界到底怎么了

突然间世界风云突变，从亚非欧无一消停。欧洲在动，非洲在动，亚洲也在动。到底谁在运筹帷幄，谁在故弄玄虚，谁又有苦难言。不是我不明白，是世界变化快啊。

中东和非洲出现的由示威而骚乱而政局变动的事件，其原因是什么，幕后推手又是谁，谁能在这样的变化中获得最大的利益，大国间的博弈将会以何种形式展开？下文将围绕这些问题，做一些分析。

美国在这个局中扮演什么样的角色。众多周知，<<美国在2008年爆发了金融危机，把世界拉入了危机之中，然后，美国通过所谓的“量化宽松”，明里暗里的发行了天量的货币。>>由于美元的世界储备货币的地位，美国的滥发货币导致的通货膨胀迅速的向世界蔓延，各国都出现了不同程度的通货膨胀，有金融而经济的危机向世界蔓延。

尤其是广大发展中国家，本身的抵抗能力就弱，在这种冲击之下，广大发展中国家的物价开始上涨，失业率居高不下，人们的生活出现困难，继而社会问题开始出现，人们将矛头指向政府的无能和贪污腐败。换言之，<<因为民众生活的下降，经济发展停滞不前，政府的无能和官员的贪污腐败问题变的越来越突出，原来可以容忍的贪腐变得不能容忍，政府与民众的矛盾日益尖锐。民众开始走上街头表达不满。>>

可以说，中东和非洲出现的由示威而骚乱而政局变动的事件，祸根远种。<<美国的金融危机引发天量滥发货币的不良影响间接导致了今天的民众运动，>>由此也可以判断只要美国的不能从金融危机中走出，美国的滥发货币的行为得不到制止，这种运动将会越来越多，烈度也会越来越大。[[薪不尽，火不灭]]。

 

三、各国的利害考量

1、可能获得的利益。

先看美国。虽然目前出现乱局，但是对美国来说，却未必不是机会。站在美国的角度看。由于美国的金融危机没有出现根本的好转。<<美国的国势继续在走下坡路，美国需要借助一定的可控的乱局来表现世界老大的风范同时打压其他对手>>。

埃及、突尼斯、也门一乱，黄金水道必然受到影响，苏丹、阿尔及利亚这些产油国的骚乱，必将影响是石油的供应。欧洲会不会紧张，中国会不会紧张，中东富得流油的产油国会不会紧张。肯定会！<<在动乱的驱动下，避险的资本到哪里去呢？>>去美国就会成一个不错的选项。<<世界通货与石油挂钩的美元地位会如何呢，>>自然会得到一定程度的巩固。占据绝对优势的美国海军就有了用武之地，对美国国势的提振，从短期来说，是有一定帮助的。特别是<<把祸水向非洲的深处引导，增加中国在非洲的经营成本，遏制中国的快速崛起，在中美的对话和斗争中取得更多的话语权，>>都是极为有利的。所以，<<可控制的骚乱>>，美国是可以容忍并一定会加以引导的。

再看俄罗斯，从金融危机以来，俄罗斯的日子一直都不好过，原油价格曾经低落至三四十元美元一桶，长期的低油价，让俄罗斯的经济举步维艰。如果中东和非洲出现混乱，黄金水道受到影响，石油肯定出现飞涨。俄罗斯的好日子就到了，面对这敏感地带的混乱，俄罗斯是求之不得的，自然乐观其成，必要时可能还要加以引导和推动。

再说说中国，对与这敏感地带的混乱，中国在表面上会有直接的损失，比如苏丹政局的变化，非洲出现的骚乱和政权更迭，会对中国经营的非洲带来一定的损失，投资收益会变得不稳定，进而经营成本会增加。石油涨价，航路不畅，会增加中国经济发展的困难。但是，石油价格上涨，中国是能挺的住的，经济发展减速，中国也是能忍受的。<<如果在忍受了高油价和通货膨胀之后，巧妙的将乱局引入中东，引起连锁反应，刮起穆斯林旋风，进一步打击美国已经失败的大中东计划，使得美国无力掌控局势的发展，倒逼美国的利益，形成巨大的筹码，完成东北亚和中东的交换平台建设，顺利整合东北亚。在中东拖住美国，再获得一个相对平静的发展时期。中东的混乱，使得高铁计划顺利开展。那目前的损失，中国是可以付出的，只需积极应对即可。>>

 

2、面临的风险

美国的风险：这样的乱局自然可以强化美国的权威，有利于美国经济的复苏和打击中欧以获得更多的谈判筹码。但是如果这种乱局被推动，被传染。引起连锁反应，刮起穆斯林旋风。中东不稳，西亚不宁。美国的战略支点丧失，美国这个巨人在获得短暂的补血后会失血更加严重，其全球战略就会陷入绝境。高油价和通货膨胀，美国也不可能置身事外，经济的下滑和人民生活水平的下降，美国的国内问题会更加的突出，这对美国都是不能不考虑的问题。

中国的风险：在忍受了高油价和通货膨胀之后，如果不能将乱局引入中东，进一步打击美国已经失败的大中东计划，使得美国无力掌控局势的发展，倒逼美国的利益，形成巨大的筹码，完成东北亚和中东的交换平台建设，获得一个相对平静的发展时期，整合东北亚。那中国就丧失了前年布局索马里的战略意义，资源供应会受到严重影响，经济发展减速，进而社会矛盾也会激化。稳定将成为一个格外重视的问题，后面明的发展就会受到极大的制约。

俄罗斯的风险：如果油价不是俄罗斯希望的那样一飞冲天，反而中东西亚一些斯坦国家倒是将这种运动开展的如火如荼，俄罗斯的传统势力范围受到影响，那俄罗斯可能会从甜头里面尝到苦涩的味道。同时中国的高铁在这样的乱局中，绕过俄罗斯的远东，直贯欧洲，那俄罗斯将有苦说不出。

虽然因为中东的混乱会增加欧洲的话语权，但因为实力的不济的原因，欧洲所处的位置和感觉会很尴尬。无论是地缘是政治还是经贸，都会受到不同程度的影响，目前从欧洲不时被刺激的神经和酸溜溜的话已经能感受到这样的意思。

 

四、自信导致谁都想玩下去

美国知道游戏危险，但美国不得不玩一把，因为金融危机对美国的创伤太重了，美国需要一个喘息的时间，这是无奈的现实，所以无论是美国主动玩，还是被动玩，美国都不想一开始就罢手。

中国也知道游戏危险，但是鉴于整合东北亚的需要和拖住美国再获得一个相对平静的发展时期的需要，中国也要鼓足勇气玩一把。否则，中美的对抗常态化，对中国的发展是极为不利的，东北亚整合的僵局怎么打开，其战略转型怎么顺利实现？所以无论是中国主动玩，还是被动玩，中国也不想袖手旁观。

对俄罗斯来说，那就不一样了。局势一乱，石油必涨，眼前的利益能放弃吗？以俄罗斯的民族个性，肯定不能。尽管局势可能失控，中东西亚出现混乱，侵蚀到俄罗斯的长远利益，俄罗斯也不会放弃眼前利益的。所以无论是俄罗斯主动玩，还是被动玩，俄罗斯这个甜头也一定要尝到，这就是俄罗斯的个性。

似乎说到这里，等于什么都没有说。可能局势就是这样盘根错节的复杂。因此在这样的情况下，中美俄都不想主动的去遏制混乱的发展，谁主动遏制，也必然会被其他的势力所利用。同时，似乎谁都有自信认为可以在这样的乱局中，能将自己的利益最大化，因此才出现了这种一触即发的风云激荡。

 

五、谁是始作俑者。

从局势的发展来看，特别是非洲国家的动乱，出于中美俄欧动机与能量的考量，可以得出这样的结论，始作俑者只能是美国。金融危机，祸根远种。害人不浅，量化宽松。这种混乱是美国的政策所激所逼。同时美国一直扶植的非洲和中东一些独裁的政府，又不负责任的输出所谓的民主自由，造成了民众与政府的紧张对立，这是内在的原因；同时因为大国博弈的需要，各种势力推波助澜，遂成星火燎原不可遏制之势。

孔子说“[[始作俑者，其无后乎]]”。可谓至理名言，对于今日之局面，该认真反思的是美国。美国会不会因为自己的不负责任和肆意妄为付出极为惨重的代价，我们拭目以待。

 

 

六、日俄的口水仗利透露出怎样的信息

日俄关于岛屿之争，突然之间强烈起来。这样的岛屿之争，目前来讲是根本是无解的。日俄的目的无外乎是想在东北亚的整合中，占据最有利的位置。日本从来都是鬼精鬼精的，但是没有战略眼光的民族，在大国的博弈中，是没有前途的。我最不好看的，就是日本。在中俄强大，朝韩发展的今天，还有出路吗？无论是在东北亚，还是在亚太，乃至整个地球，日本的战略空间都极为狭窄。如果在东北亚的整合中，日本被忽略其利益诉求，日本将彻底的没有希望。同样，因为俄罗斯经济不强和在远东实力太弱，俄罗斯是非常渴望在东北亚的整合中最大化自己利益的。所以，<<日俄的嘴里谈的是岛屿之争，眼里盯住的是东北亚的整合。>>

东北亚整合问题，牵涉到中美的未来地位的定位。如果东北亚发生了实质性的变化，那对中美乃至整个世界的冲击将是巨大的。如果这种变化没有力量可以阻挡，那么在金融危机没有散去，美国加速衰落，中国快速崛起，欧洲抱团取暖的今天，大国是不是要为将来的变局做点什么呢？世界的风云激荡，我觉得可能也是这种内在结构变化所折射出来的现象。东北亚的问题，中美在东北亚是无法直接解决的，只能放到更广阔的舞台上去角力，分出胜负了，东北亚的整合的问题也就解决了。

如果中国顺利整合东北亚，试想中国的发展会何等的波澜壮阔，如果美国失去东北亚，美国还能坐稳超级大国的位置吗？正因为牵涉极广，这里面自然会有激烈的利益碰撞和交换。我说的是一个大国博弈的思路，在这个思路上如何布局，这才是大国间需要认真对待和较量的地方。

 

七、未来局势发展的预想

综上所述，中东和非洲的风起云涌，谁打的第一枪似乎已经不重要了。重要的是在接下来的发展中，谁能把局势向有利于自己的方向引导并推动，这才是要认真对待的。美国自然是希望混乱的局势是可控的，希望把更强烈的混乱引导到非洲的各个地方，最大程度的打击中国的利益。而不希望这样的混乱在中东等地发酵，在混乱中反美的势力上台，以色列这个中东钢钉被连根拔掉。那样美国的精力会被牵涉到更多的战场上，会出现一个又一个类伊朗的政权，从而彻底的颠覆美国的全球霸权。

中国则希望能够在付出一定代价的基础上，在中东拖住美国，使其无力东顾，逼迫美国出让利益，完成东北亚的整合，获得一个难得的发展机遇。<<在拖住美国这点上，中俄是有共同利益的，但在石油价格方面，中俄是有分歧的。>>

 

#+BEGIN_HTML
 <p>
未来的发展只会越来越复杂，小国的生存环境会进一步恶劣，世界可能会面临巨大的困难，其斗争的烈度会随时间的延长而增加，变局一定会从这样的乱局中产生。因为美国这个始作俑者导致局势不可控，那么各种势力必然会因势利导，保存实力，借力打力。谁都不会在大幕开启之时，用尽全力，留下空当，为对手所乘。谁能笑到最后，谁才是真正的胜利者。
</p>
#+END_HTML

#+BEGIN_LaTeX
 未来的发展只会越来越复杂，小国的生存环境会进一步恶劣，世界可能会面临巨大的困难，其斗争的烈度会随时间的延长而增加，变局一定会从这样的乱局中产生。因为美国这个始作俑者导致局势不可控，那么各种势力必然会因势利导，保存实力，借力打力。谁都不会在大幕开启之时，用尽全力，留下空当，为对手所乘。谁能笑到最后，谁才是真正的胜利者。
#+END_LaTeX
