# -*- org -*-

# Time-stamp: <2011-09-15 13:56:53 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:3

#+STARTUP: indent

#+TITLE:从中国近现代史....

#+AUTHOR:会同天下

#+SETUPFILE:~/dea/templates/level-0.org



来源：西陆东方军事


** 一

    在2007年《破局--大国的博弈》一文中，我论述了一个支点，内练一口气；两条战线，政治经济学；三个层次，抗美，拉欧，援非；四个方面，东逼，西进，南抚，北交。上面的内容经过近一个月的整理推敲，做了较大程度的修订，重新调整了结构，补充了许多内容，又增添了几万字。并在那基础上对中国近现代的政治稳定与经济发展和民主政治的关系进行了思考，我把思考的相关内容概况为五个阶段，如今贴出来，请各位朋友批评指教。

 

五个阶段

 

（1）、近代肇始：从曾国藩到李鸿章看中国的洋务运动

（2）、国民革命：从孙中山到蒋介石看中国的国民革命

（3）、统一中国：从蒋介石到毛泽东看中国的武力统一

（4）、重装经济：从毛泽东到邓小平看中国的经济改革

（5）、民主政治：从胡锦涛到□□□看中国的民主政治

 

    下面的五个阶段，我将从历史的演变与中国近现代进程的角度来展现中华民族重新崛起的历程，探讨民主政治实现的可能与途径。近现代史是中国历史上最为夺目的一段历史，当我们历经苦难，压抑住悲愤，沉淀出理智，终于能平心静气的看这一段历史的时候，才真正的发现这被称之为苦难史、屈辱史、探索史、抗争史、奋斗史的中国近现代史所具有的特殊的珍贵的价值。

    在中国近现代史上，人物辈出，灿若繁星。其间人品道德有高低之分，识见才能有高下之别，历史机遇变幻莫测，追求目标五花八门，苦心经营或成或败，但作为一个有能有力的人，在那个万马齐喑又狂飙突进的时代，都一一留下了自己的痕迹，或正或反，对历史和民族产生了一定的影响。

 

（一）两个不一样的中国

 

   一、走在世界前面的中国

    在世界不同的地方，人类文明几乎同时诞生，在花开几朵的演变中，表现出了各自不同的特色。从东西方文明出现的价值与当时的影响来看，他们是不分伯仲的。秦帝国是否就一定比罗马帝国更厉害，老子、孔子是否一定比苏格拉底或亚里士多德更多才，这都没有办法具体比较。但在后来的文明的发展中东西方的发展不是并驾齐驱的，其前后相继性表现的比较明显，中国古代文明至少在一千年的时间里要领先于古代西方。

    从公元476年西罗马帝国的没落到十五世纪文艺复兴开始，是欧洲历史上著名的中世纪。由于蛮族的入侵引起了西罗马帝国的崩溃，蛮族落后的价值观念和愚昧无知几乎摧毁了当时欧洲的文化，这一时期被称为"黑暗的中世纪"。"中世纪"是一个基督教盛行和罗马天主教会主宰社会的时期，神学成为封建统治的支柱，神学强调神性、否定人性，在宗教神学的黑暗统治下，西方无论是政治制度、经济发展、科技教育相比中国都是逊色的。

    孔子奠定的健康的人格特征与"子不语，怪、力、乱、神""不知生，焉知死"的清醒认识，给中国古代知识分子提供了充沛的底气与定力。正因如此，中国在宗教方面显得早熟，不极端、有理性。在中国，政治与宗教的关系是松散的，中国人尤其是有远见的政治家是不怎么重视宗教力量的，与其拿宗教做幌子，到不如装神弄鬼来的有用。

中国的宗教无论是土生土长的道教，还是自西而来的佛教，进入中国后，都指向了人的修养，强调人的修为；而西方的宗教由于世俗化，指向的则是权力本身。政治借助宗教维持统治，强力扩张，宗教借助政治扩大传播，为非作歹。政治与宗教在互相勾结利用中，成为一体，最终堕落成"黑暗的中世纪"的罪魁祸首。

   当西方笼罩在"黑暗的中世纪"的影响下时，亚洲大陆的东面--中国创造出了极为优秀灿烂的文明。

 

   先看古代中国的四大发明：

   1、造纸术：东汉蔡伦于105年改进造纸术。造纸术于6世纪初传到朝鲜、越南和日本，8世纪传到中亚，并经阿拉伯人传到非洲和欧洲。

   2、印刷术：活字印刷术发明后，向东传入朝鲜、日本，向西传入埃及和欧洲。

   3、指南针：北宋已会使用磁针指南，制成指南针用于航海。南宋时指南针传到印度、阿拉伯、波斯等国，为新航路的开辟和实现环球航行提供了重要条件。

   4、火药：唐末火药开始用于军事，北宋时火药已广泛用于军事领域。13世纪中期，火药传入阿拉伯，后来又从阿拉伯传入欧洲。

   再看经济：

    西汉末期，首都长安有人口约100万，一千年以后，英国的伦敦，法国的巴黎，意大利的威尼斯等城市的人口都不过万人。宋元时，中国的城市规模也是西方难以望其项背的。

罗兹墨菲在《亚洲史》上提到：宋朝十一世纪的钢铁产量，比欧洲直到十七世纪的总和都多；华北的钢铁业以1078一年为例，年产达一百二十五万吨的水平，而英国在1788年，也就是工业革命开始才不过年产七万六千吨。

   中国11世纪开始使用纸币，六、七百年后，欧洲才有最早的纸币。

   科技文化：

   秦汉：编写于公元前1世纪的《周髀算经》比西方早500年提出了勾股定理的特例。张衡的地动仪是世界上最早测定地震方位的仪器，比欧洲早1700多年。

华佗擅长外科手术，被誉为"神医"。他发明的"麻沸散"比西方早1600多年。祖冲之在世界上第一个把圆周率精确到小数点以后七位数字，比欧洲早1100多年。数学家王孝通撰写《辑古算经》，首次提出三次方程式正根的解法，比阿拉伯人早300多年，比欧洲早600多年。

僧一行在世界上第一次测定了子午线的长度。沈括的"十二气历"比英国早800年。郭守敬的《授时历》比现行公历的确立早300年。

    《孙子兵法》在中国流传2000多年后，于18世纪中期传入西方。美国哈佛大学与哥伦比亚大学的商业管理学院要求学生熟读《孙子兵法》。美国西点陆军学院、国防指挥参谋学院等著名军事院校都将《孙子兵法》列为必修课。



古代中国向西方输出技术

现将有些生产技术在中国出现的时间与在欧洲应用于的时间作一比较：

#+CAPTION: 古代中国向西方输出技术

| 发明       | 出现在中国  | 在欧洲（年） |
|------------+-------------+--------------|
| 链斗水车   | 公元2世纪   |         1672 |
| 轮碾磨     | 公元8世纪   |         1607 |
| 冶金鼓风机 | 公元2世纪   |         1200 |
| 旋转风扇   | 公元11世纪  |         1556 |
| 活塞风箱   | 公元14世纪  |         1500 |
| 手拉织机   | 公元1世纪   |          400 |
| 车轮       | 公元7世纪   |         1200 |
| 弩机       | 公元2世纪   |         1100 |
| 陀螺       | 公元4世纪   |         1700 |
| 风筝       | 公元1世纪   |         1589 |
| 钻井技术   | 公元1世纪   |         1126 |
| 铸铁       | 公元7世纪   |         1300 |
| 敞肩石拱桥 | 公元7世纪   |         1883 |
| 铁索桥     | 公元5~8世纪 |         1741 |
| 艉舵桥     | 公元8世纪   |         1180 |
| 火药       | 公元7~8世纪 |         1200 |
| 指南针     | 公元8世纪   |         1190 |
| 造纸术     | 公元2世纪   |         1140 |
| 活字印刷   | 公元11世纪  |         1440 |
| 瓷器       | 公元2世纪   |         1800 |

#+begin_center
（摘自：中华文化知识精选）
#+end_center

面对如此辉煌灿烂的文明，我们要自豪，中华民族是优秀的，先辈是无愧于我们的。这些优秀的成果是中华民族智慧的结晶，让那些一提到中国就不自信的民族虚无主义者闭嘴吧！

 

   二、世界选择了西方

    三十年河东，三十年河西，东方不亮西方亮。当我们越来越沉溺于所谓的道德优势与辉煌成就而始终抱着夷狄之见固步自封丧失了前进的动力时，西方终于冲破了"黑暗的中世纪"，14世纪中叶到17世纪，一场以恢复希腊罗马古典文化为口号，其实质是人文主义的文艺复兴运动开始从意大利以不可阻挡之势向周边国家蔓延。这是一场波澜壮阔影响深远的思想解放运动，在几个世纪里，动摇了传统的宗教的神权、贵族的特权，君主的王权。人终于从中世纪的基督教神学的桎梏下解放出来，西方人的聪明才智不再受到神的压制，他们开始登上历史的舞台，拉开近代文明的大幕。

    1566年尼德兰爆发了资产阶级革命，1609年西班牙国王菲利浦三世承认荷兰独立，建立了第一个资产阶级共和国；1640年英国开始了资产阶级革命，1689年颁布《权利法案》，确立了君主立宪的政体；随后法国也进行了资产阶级革命，美国经过8年的努力，于1783年赢得了独立战争的胜利，西方的资产阶级革命，推翻了落后的制度，解放了生产力。18世纪60年代以蒸汽机的广泛应用为标志的第一次工业革命首先发生在英国，资本主义由工场手工业开始向大机器生产过渡。资产阶级革命与工业革命的相辅相成让西方在生存与发展的天平上占尽先机，而东方的裹足不前固步自封造成了东方附属于西方的必然结局。

    中国自明朝后期就已现出颓势，倭寇开始大规模进犯中国沿海，检验一个国家是否强大，我认为最明显的一条就是是否受到别人的侵犯，在受到侵犯时怎样反应。日本这个一直以中国为师的岛国都可以渡海而来烧杀抢掠，可见明朝后期的问题已经出现了。由于海患严重，明政府开始清剿，戚继光、俞大猷等组织抗倭，基本肃清了其势力，这说明朝还有起码的抵御力量。据考证戚继光、俞大猷等的战法与火器在当时还是世界上领先的。当然，倭寇虽然势大，毕竟还是乌合之众。

   明朝出现了伟大的航海家郑和。郑和和他的船队航行前后达28年，访问了30多个国家和地区。郑和下西洋，比哥伦布早了87年，比达伽马早了92年，比麦哲伦到达菲律宾早了116年。郑和每次下西洋人数达二万多人，当时西方哥伦布的航海人数在90-1500人之间，达伽马的航海人数是170多人，麦哲伦的航海人数是265人；郑和的船队有两百多艘，西方航海家只有三五艘。郑和曾带领过当时世界上最大的船队，拥有当时世界上最先进的技术。但由于中国人忽视海洋，自封自闭，加上道德思想认识上的局限，限制了中国人进取精神和开拓意识。郑和的宝船七次航行于大洋之中时，除了宣扬国威和所谓的文化交流还有传说寻找散落海外的建文帝之外，没有给国家带来其他的利益，没有让中国从陆地走向海洋，相反却耗尽了国力。这不仅是郑和的悲哀，还是那个时代的悲哀。

 

    中国历史进入明朝后期，问题开始出现。从万历皇帝到崇祯皇帝，要么有力无心，要么有心无力，都不能挽救大局，也找不到解决问题的根本方法。到明朝末期，国内民不聊生，战乱四起，关外后金兴起，虎视眈眈。在内忧外患之下，大明的精英们已经没有力量回旋天地，而满清的入侵让中国彻底的失去了思考与实验的可能，中国的命运在这关键的时刻沉沦。

满清1644年入关，确立对中原的统治。清朝对中国的最大贡献是现代中国疆域的形成和文化的整理，其实少有可观。满族入关时人口一百万左右，要确立对全国的统治，是非常不容易的。但历史告诉我们，满清对中国的统治从1644年一直持续到1911年，长达267年之久，奥妙何在？

    客观的讲，清朝的皇帝绝大多数都是勤奋的，无论是学习、治国，还是琢磨汉人，研究治术，都比较用心。但他们的勤奋不能掩盖他们的自私，他们潜意识中还是把自己定位于白山黑水间的少数民族，而不是富有四海占据一千多万平方公里的中国。

    满族人太少了，汉族人太多了，统治起来就难了。清朝皇帝认为最大的威胁始终都是内部，考虑最多的是如何不被占有优势人口与文化的汉族赶跑，还哪有精力去富强国家，他们处心积虑的就是维持统治，消除内部威胁，瓦解人民的抵抗能力。对于北方骠悍的民族，康熙皇帝借沙俄之手打压，两次雅克萨之战，一次胜而不取，一次战而不胜，放纵沙俄势力南下，蒙古人遭到毁灭性的打击，从此人口锐减，一蹶不振。

    这是对付与他们有同样武力优势的民族，而对于有人口与文化优势的汉族，满清贵族一方面大肆杀戮，一方面从思想文化进取精神创新意识上进行破坏打压。

满清入关后，颁布剃发令。"留发不留头，留头不留发""剃发易服，不随本朝制度剃发易衣冠者杀无赦"。鲁迅说："这辫子，是砍了我们古人的许多头，这才种定了的，到得我有知识的时候，大家早忘却了血史，反以为全留乃是长毛，全剃好像和尚，必须剃一点，留一点，才可以算是一个正经人了。"

    大兴文字狱，控制思想。徐骏的"清风不识字，何故乱翻书？"被挑剔说"清风"就是指清朝，徐骏被雍正杀掉。龚自珍《咏史》："避席畏闻文字狱，著书都为稻粱谋。"从顺治到乾隆可统计到的文字狱约160多起。

    分化民间反抗，拉拢知识分子，打着选拔人才整理文化的旗号，培养顺民，摧残文化。乾隆朝编纂《四库全书》，销毁的书籍"将近三千余种，六、七万卷以上，种数几与四库现收书相埒"（章太炎《哀焚书》第五十八）。吴晗说，"清人纂修《四库全书》而古书亡矣！"

当我一听到清朝大臣，向皇帝谄媚说"奴才如何、奴才如何"的时候，我就止不住的反胃。汉唐宋明有哪一朝的大臣自称奴才的？清朝的臣子，首先是君之奴才，然后才是国之大臣。当一个满清大臣张口奴才闭口奴才的时候，其道德底气又能保留多少。大臣与奴才虽只是称呼的差异，但反映了不同时代国之栋梁的生存状态，价值取舍，更反映了文化气脉的衰落。

西方终于冲破了黑暗的中世纪，中国却进入了"黑暗的中世纪"。我们看不到光明，看不到希望。我们看到的是残酷无情的禁海令；我们看到的是名不副实的康乾盛世；我们看到的是实行了一百多年的文字狱；我们看到的是钻到故纸堆里的知识分子；我们看到的是马嘎尔尼要表演欧洲火器操练却被鄙夷"这种军器操法，量也没什么稀奇"的福康安；我们看到的是火轮船行驶而疑心机器发动系借牛力的两江总督牛鉴；我们看到的是同英国战争早已经开始了，还能问出"英吉利至新疆各部，有旱路可通？"的道光皇帝；我们看到的是要"量中华之物力，结与国之欢心"的慈禧太后。

 

（二）五个阶段

 

  一、近代肇始：从曾国藩到李鸿章看中国的洋务运动

    1840年6月，中西较量的一天终于在英国焦急的等待中到来了，由四十八艘舰船和四千余名官兵组成的英军抵达广州珠江口，鸦片战争爆发。清政府虽经过殊死抵抗，仍惨败。我们看几场战役的伤亡比例：

    大角、沙角之战：清军战死277人，重伤而死5人，受伤462人，英军受伤38人，副将陈连升，佐领裕隆战死。

   虎门之战：清军总兵力11000名，清军250人战死，受伤100余人，水师提督关天培战死，英军受伤5人。

    吴淞之战：清军总兵力4700名，提督陈化成以下88人阵亡，英军战死2人，受伤25人。

    这是一系列不对称的战役，从这些血淋淋的伤亡数字和这些阵亡的民族英雄身上，我们能看得出来，在鸦片战争中，官兵是努力了的，但努力的结果，没有改变失败的命运，中西方的差距在血与火中判若天渊。

    为什么会败的这么惨？我们把目光向前迈进四十七年，也许会找到些不完整的答案。1793年英国公使马嘎尔尼访问中国，商量两国贸易通商，乾隆皇帝生硬的拒绝。马嘎尔尼考察中国后，在其《纪事》中写道："中国自满洲鞑靼占领以来，至少在过去一百五十年里没有进步，或者更确切的说反而倒退了。""满洲人打仗爱用弓箭，当我告诉他们，欧洲人已放弃弓箭而只用来复枪打仗时，他们愕然不解，认为在奔驰的马上射箭，比站在地上放枪豪迈。"

    在清朝皇帝看来，鸦片战争对拥有一千多万平方公里土地，有4亿多人口国家伤害并不大，但对于知识分子的震动极大。怀抱天下的知识分子，突然发现原来庞大的帝国竟然这样脆弱不堪，知识分子首先从"天朝上国"的迷梦中清醒过来，林则徐等人开始开眼看世界。一批知识分子受到社会责任感的激发，自动的担起拯救家国的使命。从魏源无限美好却不切实际的"师夷长技以制夷"，到洪仁玕有具体纲领却无操作环境的《资政新篇》，再到曾国藩李鸿章前后相继的洋务运动，我们看到了中国人在那个特殊时代不懈的追求与勇于探索的努力。

    曾国藩是湖南湘乡人，湖南人在中国近现代史上大放异彩，其源头要追溯到曾国藩。曾国藩是作为天平天国的对立面而出现的，没有天平天国运动，就没有后来的曾国藩。肯定曾国藩，就要否定太平天国；肯定太平天国，就要否定曾国藩，这就造成尴尬的二选一的局面。下面，为了更清楚地论述，我们跳出评价时必须二选一的圈子，从当时社会的需求与措施的得当来看待两个有争议的人物。

    太平天国本身是一个光辉的运动，打击了满清的腐朽政权，坚决反对西方列强强加的不平等条约，要求平等交往，维护民族尊严；坚决禁烟（近一百年后，中华人民共和国建立，才彻底禁止），不再留那讨厌的辫子，女子也不再缠足（五十年后，中华民国时才得以去除）；实现男女平等（毛泽东时代才实现）。

    天平天国又是一个不完满的农民运动，引入"拜上帝教"更是一个败笔，相反的角度也可见清政府已经愚民到了何种程度。天平天国前期提出《天朝田亩制度》，后期制定《资政新篇》，可这样闪烁智慧思想的纲领，前者由于本身致命的缺陷，无法操作，后者由于领导者的局限与迫于环境的险恶，无法落实。

    洪秀全本能的意识到清政府的阴毒，封建专制文化的危害，但他找不到它们的死穴，还成了它们的牺牲品。洪秀全用一个无任何理论根基，也没有民众基础的"上帝"来取代"孔教"。其结果就是暂时性的动员了无数农民起来造反，而一棒子把所有知识分子不分好坏的"打死"，与中国古代文化决裂，彻底的抽走了知识分子参政的可能，这是理论构建与可持续发展上致命的缺陷，相反，曾国藩轻易的找到并扛起了捍卫文化的大旗。

    在捍卫文化的大旗下，曾国藩的幕府人才鼎盛，绝大多数人后来都成了地方大吏，社会的中坚；在"上帝"的指引下，洪秀全的大营人才匮乏，天京变乱后，仅有的几个杰出人物要么被逼走，要么被架空，要么被猜忌，要么只能愚忠。

    撇开他们的功业不谈，就从个人修为上看，洪秀全与曾国藩也是不能比的，他们不是在同一层次上。在天地之间，军营之中，曾国藩磨练出了经世济国的才能；在天王府内，床笫之上，洪秀全耗尽了仅有的精锐之气。

    我常常不切实际的想：如果曾国藩处在洪秀全的位置上，而洪秀全处在曾国藩的位置上，结局会怎样？以曾国藩的才华与湖南人的勤恳，也许可以开出一个新的局面，也许是中国历史的一个幸运。但历史不能假设，历史在这两个人的身上开了一个玩笑，可是让所有的人都笑不出来。

    曾国藩的"武功"指向的不是帝权，在天京失陷前，曾国藩已开始散其权力。攻陷天京后，有人拥戴曾国藩自立，被曾国藩装聋作哑的化解，并留下"倚天照海花无数，高山流水心自知"的名句。曾国藩要的是一个稳定的社会，一个可以施展强兵富国的舞台。洋务运动作为当时中国社会最迫切的需要而展开了浓墨重彩的画卷。

 

    经过鸦片战争、第二次鸦片战争，天平天国运动之后，清政府终于认识到，如果还抱着老祖宗的东西不放，清政府连起码的统治都维持不住了。在中央奕忻和地方实力大臣曾国藩、左宗棠、李鸿章、张之洞等人的推动下，从19世纪的60年代到90年代，开始了长达30余年的洋务运动。

    洋务运动概况：

    洋务运动分为两个时期：19世纪60年代至70年代，以"自强"为旗号，采用西方先进生产技术，创办了近代军事工业。19世纪70年代到90年代，为解决军事工业的困难，又打出"求富"的旗号，兴办了航运、煤矿、电讯、纺织等民用工业。我们可以总结为强兵富国。

    洋务派创办的近代军事工业有二十多个，其中比较著名的有：1、安庆内军械所，1861年由曾国藩创设于安徽安庆，1864年迁往江苏南京，后并入金陵机器制造总局。2、江南机器制造总局，1865年由李鸿章在上海建成，主要制造军火和轮船。3、金陵机器制造总局，1865年由李鸿章在南京建成，主要制造枪支弹药。4、福州船政局，1866年左宗棠在福州马尾创办，专造兵、商各轮船。5、天津机器制造局，1866年崇厚创办，主要制造军事装备。效果：江南制造总局仿制的毛瑟枪赶上了德国的水平。福州船政局可以自行设计、制造舰船供军需和民用。

     洋务派创办的民用工业极多，领域很广，包括轮船航运，开采煤矿和采掘、冶炼其他金属矿藏，电报，纺织业。著名的有：1、轮船招商局，1872年李鸿章在上海开办。2、汉阳铁厂，1890年张之洞在湖北兴建。3、开平矿务局，1878年成立，1881年正式投产。效果：在客观上对外国经济势力的扩张起到一定的抵制作用。轮船招商局经营三年，在华外国轮船公司就损失白银1300万两；开平煤矿出产的煤逐渐取代了洋煤在天津市场的地位。

    创设海军：80年代中期，洋务派初步建成北洋、南洋和福建三支海军。三支海军拥有舰只43艘。1885年10月清政府成立了海军衙门。中国出现了近代海军。

贮备智力，培养人才。创办新式学校，到1896年达20余所，选派留学生出国深造，培养翻译、军事和科技人才。

    举步维艰的洋务运动。虽然洋务运动是当时所必需，但开展起来不是一帆风顺的。顽固派竭尽全力的阻扰与破坏。顽固派的代表人物有倭仁、李鸿藻等，他们高倡" 立国之道，尚礼义不尚权谋，根本之图，在人心不在技艺"，主张"以忠信为甲胄，礼义为干橹"，并以"师法西人为耻"，认为"制造乃工匠之事，儒者不屑为之"。

    修筑铁路对国家富强来说是非常重要的，但顽固派极力反对，认为筑路将破坏风水、触犯龙脉，指斥铁路有"三大弊"，或断言铁路有"不可行者八、无利者八、有害者九"。1881年，中国自主修建了第一条铁路，建成后却被顽固派指斥为冲撞神灵，而禁止使用机车，只准以骡马拉拽，人称"马车铁路"。

    顽固派阴魂不散的与洋务派缠斗了30多年。

    在清政府的腐朽统治与外国势力干涉的夹缝中开展的洋务运动从一开始就先天不足，只能靠地方的洋务大臣常规或非常规的操作才能来弥补其随时可能出现的问题，来争取慈禧可以随时放手的支持。在这样险恶的环境中，评判洋务派的标准应该从个人的操守向实际的功用上倾斜，揪住洋务派的小辫子不放，而忽视其当时社会的特殊性及对历史的推动作用，不符合具体问题具体分析的客观精神。

    曾国藩是洋务运动的首领，有开创意义。他不仅第一个提出"师夷智以制船造炮"观点，还建立了第一个近代新式兵工厂（安庆内军械所），派人到国外购买能制造机器的机器，立足自造；确立了敌强我弱，又要开放自强格局下的外交思想。

    在洋务运动中，曾国藩李鸿章前后相继的特性表现的比较明显。曾国藩1870年死后，李鸿章接过洋务大旗，用李鸿章自己的话讲，"师事近三十年，薪尽火传，筑室忝为门生长"。李鸿章的后半生几乎就伴随洋务运动的始终，李鸿章把洋务运动推到了一个更高的层次。

    李鸿章缺少曾国藩的诚笃，却比曾国藩更具灵活性，这种灵活性既是与生俱来的生存能力，也是环境逼迫的产物。当曾国藩被慈禧用天津教案打倒之后，李鸿章就意识到了环境的险恶。清政府既想通过洋务运动达到维护统治的目的，又不想有一天因为洋务运动而失去满清的江山。李鸿章在清政府的矛盾中小心翼翼见缝插针的努力维持，但最终还是由于洋务派自身的局限、清政府的腐败与日本的阴狠而功亏一篑。

    洋务运动后期，制度性的腐败已成为一个割不掉的毒瘤，洋务运动受到腐败的侵蚀越来越严重。1888年北洋舰队正式建成，共有军舰25艘，其中的定远、镇远是从德国订购的比较先进的巨型铁甲舰，排水量7335吨，马力6000匹，舰上武器先进，火力极强。但自此以后北洋舰队再没添一舰一炮，大量军费被慈禧太后挪用修建颐和园。当日本明治天皇为筹钱买军舰每天只吃一顿饭，在他的激发下，全日本疯狂的捐款给政府以购买军舰的时候，大清的慈禧却面对摆了一桌子的一百多个菜，说了一句"没什么好吃的"。相信看到这个对比的每一个人，都会产生这样的感慨：日本真的该兴了，大清真的该亡了！

    日本看到洋务运动改变了中国落后的面貌，感到了自身的危机。对于有野心的日本，日本不能让中国拥有可以恢复的时间，也不能让中国冲破黑暗成为东亚的强国，否则，岛国日本就永远没有出头之日。因为日本知道，相对于中国俄国这样的大块头而言，日本的战略处境是尴尬的，没有任何优势，一旦中俄能真正的摆脱历史的枷锁，顺利发展起来，谁都可以决定日本的命运。于是，日本在中国发展的关键时刻，倾其全国之力，对中国发动了蓄谋已久的中日甲午战争。

    在战争中，掩盖的缺点暴露出来，可耻的行为遭到报应，北洋舰队全军覆没。第二年，也就是1895年，战败的清政府被迫与日本签订了屈辱的《马关条约》。割让台湾岛及所有附属各岛屿、澎湖列岛给日本，赔偿日本军费2亿两白银，后来又勒索"赎辽费"三千万两白银。

 

    史学界对洋务运动的评价是不高的，认为洋务运动没有改变中国，也没有使中国走上富强的道路，是一次失败的运动。我想产生这样的看法是因为脱离了当时中国的实际，忽视了洋务运动的潜在的深层次的影响。

    洋务运动虽因日本的入侵没有走到最后，但其历史作用仍然不可低估。其实在甲午战争之后，洋务运动的精神--强兵富国的理念与行动继续在中华大地上驰骋。甲午战争中，除了北洋舰队遭到毁灭之外，其它洋务派开办的企业并没有受到破坏，相反还有了一定的发展。清政府在惨痛失败面前也有了一定的清醒，一方面放宽对民间开矿设厂的限制，另一方面推行新政，以求强兵富国。新政的内容是对洋务运动的继承与发展。

    洋务运动是中国近代化当之无愧的开始，是中国人学习西方，走向世界的开始。

    洋务运动为强兵富国留下了可贵的基础，一批批军事工业的建立，一座座学堂的开办，一批批人才的培养，陈腐观念受到冲击，民族精神得到振兴。洋务运动也为以后中国向多舛的命运抗争提供了充沛的底气与实力。在抗日战争中，当中国军人用"汉阳造"打日本鬼子时，我们能否想到，这得益于洋务运动中张之洞创办的湖北枪炮厂呢？中国的"汉阳造"比不得日本的"三八大盖"，但要是没有洋务运动，没有湖北枪炮厂，我们连"汉阳造"都没有。

    我们在对待历史的态度上，一定要尊重现实性与继承性，忽视当时的复杂性，用非黑即白的观点，用一步到位的标准去要求当时的人与事，未免强人所难。他们做不到的地方，正是我们可以努力的方向。对比历史与现实，我们要看到那个时代他们做了什么，现在我们该做什么。如果过分苛求那个时代人的努力，会不会在有一天，我们的后代一样的不能客观公正的评价我们。

     对比另一个东方文明古国--印度，我们中华民族在反抗侵略与压迫，争取国家独立，实现民族复兴的表现上是可圈可点，可歌可泣的。印度虽也为西方所奴役，但表现相对要暗淡的多，几乎没有像样的抗争与运动。这固然与国家民族的特点有关系，也和印度没有一个系统的长达30多年强兵富国的运动有关。没有奠定可以抗争的基础，怎么去抗争奋斗，没有留下火种，又怎么可以形成燎原之势。中国不屈服永抗争的精神是汉唐留给我们的风骨与气魄，是中华传统文化"天行健，君子自强不息"的体现，是居庙堂之上草野之中知识分子自愿承担的使命，更是中华民族是优秀民族最好的证明。

     

二、国民革命：从孙中山到蒋介石看中国的国民革命

 

    中日甲午战争，中国战败，《马关条约》的签订，令中国知识分子倍感悲愤。败于西人，中国人感情虽难以接受，但理智还能平衡，可是败于蕞而小国日本，中国人就不能平衡了，而日本的狮子大开口更让中国人难以接受。

    目睹危机，康有为深受触动，和他的学生梁启超开始宣传变法，一时间变法思潮蔚然成风。1895年8月，康有为在北京成立强学会，11月在上海成立了强学分会，但不久都遭封闭。虽然强学会存在的时间不长，由于变法自强是当时的时代潮流，各种势力仍带着不同的动机纷纷加入。其主要势力有四种。1、康梁等维新的骨干创办强学会是抱爱国热情与献身精神的。2、民族资产阶级入会是寻求保护与实现他们的利益，力量还很弱，3、洋务大臣张之洞等入会是想借变法自强的大旗把洋务运动继续进行下去，4、袁世凯等新兴势力入会是想寻找政治上的突破口。在这四种主要的力量中，第三、第四种是不可依靠的，第二种虽有斗争的愿望，可自身的软弱性，决定其妥协性。只有康梁等人是真正的维新派，斗争意志坚决，但自身实力太弱，眼前有路，手中无权。

    通过以上分析，我们可以看出维新派的复杂与尴尬，在口头的宣传上，强学会的每个人都能表现的慷慨激昂，但一落实到具体的操作层面上，则立马出现分化。慈禧太后的一个不高兴，张之洞就退出了强学会，这是最有实力，最有可能支持维新运动开展下去的力量，但他们不能同慈禧对着干，得罪不起。

    其实，我想康梁等研究俄日变法，可能已经看到"权力"在变法中的作用了，没有皇帝或有权威力量的支持，变法是无法冲破固有阻力，顺利进行的。1861年日本的明治维新得以顺利进行，其重要原因是明治天皇通过倒幕运动掌握了国家权力，而康梁时的中国就缺乏这种可以推行变法的强制力量。

    当时在国家权力上存在名实两种力量，一个是有名无实的"帝权"，一个是根深蒂固的"后权"，代表变法力量的光绪皇帝虽贵为天子，却受制于人，无一兵一卒可调。而代表顽固保守势力的慈禧太后通过1861年的辛酉政变，垂帘听政已达40多年。在变法自强的选择上，清醒地光绪帝是想有所作为的。但当时变法要冲破阻力顺利进行，必须先取得权力，而慈禧太后要牢牢抱住的就是权力，于是我们看到了以君主立宪为标榜的变法自强运动，其实质是以光绪向慈禧夺权为前提的来进行的，尽管这并不一定是光绪的初衷，但随变法的开展必然要在权力的归属上摊牌。比如，光绪因礼部堂官阻挠部员上书，便一次罢免了全堂的六名尚书、侍郎。

在权力的较量中，"帝权"与"后权"的差距实在太大，康梁等依靠的是没有实权的皇帝，而光绪帝又只能依靠没有实力的康梁等人，在这样的"空对空"的互相依赖中，就展开了中国历史上著名的"戊戌变法"。

    1898年6月11日，光绪帝颁布《定国是诏》，实行新政。虽然变法的内容有诸多可取之处，但地方实力派并不支持，变法急剧开展，触动了顽固保守派的利益，慈禧决定对光绪下手。

    在危急的时刻，光绪束手无策，只能传出密诏，要康梁等筹商对策。而受命的康有为、梁启超、谭嗣同等人也是一筹莫展，在走投无路的情况下去找袁世凯。通过谭嗣同最终找袁世凯这一投机的力量，我们可以看出康梁等人当时是何等的没有政治斗争经验，何等的软弱无力。袁世凯最终没有站在维新派的这边。

    1898年9月21日，慈禧发动政变，囚禁光绪帝，搜捕维新党。康有为、梁启超逃走，谭嗣同、杨锐、林旭、刘光第、杨深秀、康广仁死难。一场维持了103天的最有可能用最小代价扭转中国发展方向的"百日维新"结束。

    "戊戌变法"的失败，光绪帝、康梁等负有不可推卸的责任。我们不能只怪慈禧，而要反思维新派有没有问题。根基是不是稳固，力量有没有整合，条件是不是具备，时机有没有成熟，措施是不是得当。从当时的情况来看，这一切都要打个问号。维新派的根基不稳，没有一个核心，各种不同的力量也没有经过整合，面对外界压力，只会四分五裂；从时机与条件来看，当时的民族资产阶级的发展很有限，还不能为维新派提供必要的帮助，洋务大臣与新兴势力，都是不稳定的力量；西方列强已掀起瓜分中国的狂潮，当然不希望中国变法自强；光绪饥不择食，一百零三天的"百日维新"，颁发了一百多道上谕，内容庞杂，既无主要次要之分，有无轻重缓急之别。光绪有名无实，慈禧根深势大，康梁等太过心急，对形势认识不明，在时机不成熟条件不具备的情况下，不从最根本的组织与扎实的基础工作入手，就贸然开始变法，只会欲速则不达。维新派的实际操作能力比起洋务派有天壤之别。维新派骨干都是坚定的爱国志士，但没有政治斗争经验，缺乏对时局的预测与把握能力。爱国可以只凭热情，但救国却需要才能。康梁等毕竟是坐而论道的书生，不懂政治经济学，没有组织与操作的能力。他们的失败是令人惋惜的，也是令人深思的。

    "戊戌变法"的失败，使中国丧失了一个像日本那样通过上层权力变动，自上而下变革以富强国家的机会。中国只能由自上而下的改良向自下而上的革命过渡，中国历史进入了风云激荡的国民大革命时代。

 

    康梁维新变法失败后，中国走改良的道路已不可行。革命党人发动了一系列的反清起义：秋瑾、徐锡麟的浙皖起义，刘道一萍浏醴起义，孙中山黄兴广州起义。起义虽失败，但宣传了革命，推动了形势的发展，锻炼了革命党人。与此同时，由于袁世凯在"戊戌变法"中"出色"的表现，加上其本身的能力，袁世凯得到清政府的重用。李鸿章死后，清政府任命袁世凯署理直隶总督兼北洋大臣，接收了李鸿章的势力。袁世凯建立了北洋常备军，到1905年，形成北洋新军六镇，共计六万余人。

    面对民间的起义，清政府坚决镇压；面对袁世凯势力的做大，清政府也强行的让袁世凯回家"养病"，剥夺了其大权。对于清政府的镇压，革命党人不屈不挠继续积蓄力量，准备再次起义，而被贬斥的本没有病的袁世凯并没有闲着，一方面向清政府显示淡泊名利，已不问世事；另一方面，搜集情报，关注时局，以图东山再起。

    当中国的历史走到1911年的时候，拐点终于到了。孙中山等革命党人精心准备的广州起义虽然失败，但是革命意识与要求在革命党的宣传与推动下已成大势所趋，经过太平天国运动的冲击，汉族地主的势力在镇压太平天国运动和洋务运动中，已发展壮大。清政府对地方的控制越来越弱，张之洞、刘坤一的"东南互保"就是明证。此时的清政府就像一个精疲力尽的赶路者，一旦走不动，就立马倒下。在这种情况下，看似偶然的武昌起义，也成了历史的必然。

    1911年10月，武昌起义爆发，尽管起义爆发时，孙中山黄兴都不在现场，就连武汉的革命党的领袖也不在现场，但起义还是成功了。

    武昌起义爆发后，清政府异常恐慌，急命陆军大臣荫昌率北洋军南下进行镇压，哪知道这支军队不听荫昌的调遣，他只听袁世凯的命令，袁世凯这个乱世枭雄终于等到了绝好的机会。

袁世凯，河南项城人。应举不第，从军，得吴长庆重用，扬威于朝鲜，被李鸿章誉为"环顾宇内者，无出袁世凯其右者"。袁世凯的才能是有目共睹的，警察、铁路、练兵、新政、教育、邮电、实业处处都有他的影响，且成绩蜚然。但他心术不正，不能善终。

    袁世凯等这个机会已经很久了，清政府要借用他的力量消灭革命党，羽翼已满的袁世凯岂肯再被利用。1911年10月14日，清廷任命袁世凯为湖广总督，袁世凯对此并不满意，10月27日，任命其为钦差大臣，11月1日，清政府宣布解散皇族内阁，任命袁世凯为内阁总理大臣。袁世凯挟兵自重，将清政府的大权尽揽入怀中。而此时，革命党的势力又有所壮大，这正是袁世凯所需要的。从另外一个意义上说，革命党是袁世凯的护身符，没有革命党，袁世凯对于清政府来说，不仅是多余，简直就是威胁。聪明的袁世凯一方面镇压革命党的起义，另一方面利用革命党要挟清政府。由于革命党势力的不断壮大和袁世凯的私心，清政府日益被动，其统治终于土崩瓦解。

    辛亥革命后，各省的实权落入了地方立宪派和封建官僚投机分子的手中，他们投机革命，口号喊得震天响，行动却保守至极，想的都是争权夺利，哪里考虑到什么民主共和。革命党人虽占领了舆论的优势与道义的高峰，人多，势却不众，力量分散。各地的实力派都打自己的小算盘，孙中山缺少领导突然膨胀了几十倍几百倍"革命力量"的心理准备与实际能力，也不可能把这些力量都集合起来，劲往一处使，拧成一股绳，加上帝国主义的阻挠破坏，这是革命党在与袁世凯的斗争中最终落败的根本原因。

     1912年1月1日，中华民国临时政府成立。孙中山就任中华民国临时大总统，颁布了《中华民国临时约法》，好像革命就成功了，中国可以像其他国家那样完成资产阶级革命，富强国家了。但对于20世纪初的世界与中国来说，中国还有漫长的路要走。内有各地实力派的飞扬跋扈，不把中华民国当成一回事，还有袁世凯会认可这样一种资产阶级的三权分立，并维持其运转吗？外有帝国主义列强疯狂的瓜分中国，各国实力大小不同，在华利益也不均衡，他们势必要在中国寻找代理人，而代表不同国家利益的代理人在中国的争斗，势必造成中国的分裂与割据。孙中山的中华民国政府中央的权力小，无力约束实力强大的地方派系的争斗，而各地的军阀正要借助外国势力取得稳固的统治权，这些正好为帝国主义寻找代理人分割中国的土地提供了条件。所以，孙中山的中华民国既不会让中国统一起来，也不可能让中国变得富强。特殊的历史阶段与中国特殊的国情与孙中山特殊地位，决定孙中山的中华民国只能是一个过渡。

    果然，孙中山就任中华民国临时大总统，袁世凯恼羞成怒，他指使段祺瑞、冯国璋等人发出战争威胁。逼不得已，革命党人被迫同意如果清帝退位，如果袁世凯赞成共和，政权可以让给袁世凯。袁世凯接着让段祺瑞率北洋将领50人联名上奏，进行逼宫。1912年2月12日，清帝溥仪宣布退位。2月14日孙中山辞去中华民国临时大总统职务，3月10日，袁世凯在北京就任中华民国临时大总统。孙中山的中华民国过渡成了袁世凯的中华帝国。

    袁世凯最终能取得权力，这没有丝毫的悬疑。抛开袁世凯的才能与野心不说，袁世凯的资历与军队的背景，稳扎稳打几十年的运作，都是孙中山无法相比的。当孙中山和袁世凯对决的时候，孙中山底气不足就表现了出来，虽然孙中山的革命道德比袁世凯要高得多，但是成败有时候不完全由道德决定，还要看实力。孙中山的革命虽然一直都在国内进行，但是其根基一直都没有扎根在中国大地上。在国外组织力量，然后空投到国内，革命失败后，再到国外组织力量，再回到国内革命，如此反复。这固然和当时的险恶环境有关，同时也和孙中山的革命路线选择有关。从这点上看，他不如袁世凯，不如蒋介石，更不如历经艰辛的毛泽东。在历史关键的时候，孙中山都不在现场，辛亥革命时他在美洲；袁世凯称帝、护国运动时，他又到日本组织力量，当组织好力量准备杀回国内反袁时，蔡锷等在云南组织了护国军，大的战阵没见，袁世凯就立即失败退位，然后一命呜呼了。

    袁世凯在登上中华民国的大位后，开始集权，宋教仁积极筹建国民党，用议会抵制袁世凯日益膨胀的野心。这是很有意义的工作，但是却得不到孙中山的支持，孙中山这时修铁路去了。袁世凯收买宋教仁不成，1913年派人刺杀了宋教仁，二次革命爆发，袁世凯镇压后，开始想做皇帝。1915年12月12日袁世凯当上" 中华帝国"的皇帝。

    孙中山的中华民国在当时的中国走不通，因其力量小，权力分散，抗风险能力弱，但对于袁世凯来说，这些都要比孙中山强很多，为什么也失败呢？袁世凯败在贪心上。当袁世凯适当的集权后，袁世凯拥有了从鸦片战争以来汉族最好的政治优势，这千载难逢的机会无论是对于曾国藩还是李鸿章、康有为、孙中山都是梦寐一求，可望不可及的。这是历史对袁世凯最大的恩赐，袁世凯完全可以凭借其才能与实力改造中国，让中国成功的转型，那袁世凯还将是中国历史上伟大的功臣。可天堂有路他不走，他不珍惜这个机会，可能他也没有看到这个机会。袁世凯还是要当皇帝，在这一念之恶的瞬间，中国历史又再一次的沉沦。

    为当皇帝，为取得日本人的支持，袁世凯同日本签订了卖国的《二十一条》。袁世凯称帝激起全国哗变，在蔡锷等护国运动的声讨中，结束了政治生命，1916年 3月22日宣布撤销帝制，也结束了自然生命，1916年6月6日当了83天皇帝的袁世凯在全国的唾骂声中死去。这个乱世枭雄可能临死都不明白，为什么他也做了一些有益于国家的事，为什么人们还骂他骂得那么狠呢？

    袁世凯死后，北洋军阀分裂，中国进入了"战国"时代，军阀混战不休。孙中山倡导护法运动，借南方军阀打北方军阀。由此可见，孙中山还是没有实力，孙中山最终发现南北军阀都是一丘之貉，这时孙中山可能真正的明白，要想取得革命的胜利，必须依靠真正的实力，理想与口号救不了国。三民主义没有实力作基础，很容易流为形式。孙中山开始着手创建自己的军队，引入苏俄的势力，在苏联的帮助下，建立了自己的基地，建立了人才大本营黄埔陆军军官学校。直到这时，孙中山才把脚踩在了中国坚实的大地之上，才开始进行卓有成效的斗争。可惜，这时候他的生命也快走到尽头。他没能看到成功的那一天，最后几年的努力，为蒋介石的统一提供了基础。

    1925年3月12日，孙中山逝世。孙中山致力于中国革命几十年，理想的色彩慢慢的减少，实际的操作能力逐渐的增加。终于在晚年为中国将来的发展奠定了重要的基础，当年在孙中山的麾下，聚集了以蒋介石为代表的一批黄埔干将，也聚集了毛泽东、周恩来等一批共产党的精英。

    纵观孙中山的一生，实际上他的功业并不大，但历史的意味却不小，他做的更多的都是奠基与探索。他身上也有很多缺陷，不仅有性格的，而且还有能力的，再加上时代的局限，他不可能建立一个富强民主独立的国家，中国动乱的历史与列强瓜分的现实要求中国的是一个有足够力量消除割据，统一内部，并能抵抗外部势力的干涉，保持国家独立的人物。从这个角度说，孙中山离这个要求还很远，蒋介石强势的上台与毛泽东沉默的崛起提供了这种可能。

 

    蒋介石，浙江奉化人，早年留学日本。他是一个有雄心、有能力、有机遇的人。蒋介石得陈其美的引荐，认识了孙中山，其军人的出身与才能恰恰弥补了孙中山文人的形象。曲折的遭遇，孙中山太需要一个有头脑有运作能力的武夫了。蒋介石凭借天时（陈炯明兵变）、地利（任黄埔军校校长）、人和（孙中山的信任），加上其杰出政治才能、灵活机动的手腕快速的崛起。

    1925年蒋介石依靠黄埔军校的学生军为主力进行了两次东征，打垮了陈炯明，为北伐创造了条件。1926年广州国民政府开始北伐。北伐的目标是打倒列强，消灭军阀，统一全国，这是国民革命的最强音，可惜为此奠基的孙中山却看不见了。国民革命军所到之处，攻无不克，战无不胜，打败孙传芳、吴佩孚，北伐的胜利进军，震动全国，随着北伐的胜利进军，国民党开始屠杀共产党员和革命群众。蒋介石首先举起了屠刀，共产党不提防这一手，在被动中死伤惨重。国共关系破裂，第一次国共战争开始。

    1928年4月，蒋介石第二次"北伐"。1928年12月，张学良宣布改旗易帜，服从南京国民政府，蒋介石从形式上统一了全国。

    没有共同的敌人，原来的战友就变成了对手，蒋介石先后进行了蒋桂、蒋冯和中原大战，才确立了自己牢固的地位。然后一次接一次的围剿工农红军。在第五次"围剿"中，红军全面溃败，为保存实力，被迫进行转略转移。1936年可以说是蒋介石生命的巅峰，无论是政治上较量，还是军事上的厮杀，乃至经济上的振兴，蒋介石都取得了一定的成就。但也就在这年的年底，发生了一件改变了他命运的事情，从此蒋介石的好运就越来越少。

    1931年，日本发动了九一八事变，侵占了中国东三省。张学良的军队撤退到关内，蒋介石安排张学良的军队去镇压共产党的军队。因"剿共"不力，蒋介石亲到西安督战。张学良劝蒋联共抗日无效，1936年12月12日，张学良、杨虎城发动西安事变，拿了蒋介石，实行"兵谏"。在蒋介石的心里，张学良不仅糊涂，而且愚蠢，因为当时共产党在陕北的生存很艰难，要是贾一点余勇，也许可以把共产党的军队消灭或赶入大漠，此时怎么能和共产党合作呢？但是他就没有想到，在国仇与家恨面前，张学良是不会那样配合他的。还有日本人已经占领东北5年了。蒋介石的"攘外必先安内"政策推行的过久，必然产生严重的负面影响，特别是背井离乡有家不能回的东北军战死在陕北战场，却不能马革裹尸于东北战场，他们的气是不能平的。蒋介石冒失的跑到西安压迫张学良剿共，却没有更多地考虑到东北军的情绪和张学良的切身感受，他也高估了自己对张学良的了解与控制。

    西安事变发生，蒋介石从此陷入被动，共产党得到了一个喘息的机会，这一刻历史开始发生改变，江山开始易手。随着抗日战争全面爆发，共产党开赴敌后，从此在北方深深地扎下根来。毛泽东的"俱往矣，数风流人物，还看今朝"可不是心血来潮，而是对历史的选择而抒发的真实感受。


    三、统一中国：从蒋介石到毛泽东看中国的武力统一

 

   蒋介石的对手主要有三类，第一类是旧式军阀，第二类是日本人，第三是以毛泽东为代表的共产党人。

    蒋介石要想统一全国，必然要消灭各地的割据势力，把各地的旧式军阀打掉。对付旧军阀，蒋介石是胸有成竹的。在1926年的北伐中，国民革命军就已经打败了孙传芳、吴佩孚。1928年，蒋介石形式上统一了全国，但各地的军阀表面上拥护蒋介石的国民政府，可他们都是为维护自己的利益，一旦自己的利益与蒋介石的利益发生冲突，他们马上翻脸。蒋介石非常希望能消平这些势力，从而真正的掌握国家权力。从蒋桂大战到蒋冯大战，再到中原大战，蒋介石慢慢的消弱了地方的军阀，虽然这些军阀在以后的岁月里不断的扯蒋的后腿，但是他们再也没有把权力从蒋的手里拿走。

    蒋介石的劲敌是毛泽东和日本人，相对于毛泽东，蒋介石除了军事上的优势，其他均不占优势，无论是对孙中山革命遗产的继承，还是组织的严密有效，是对民心的争取，还是斗争策略的使用，蒋介石都比不得毛泽东。相对于日本人，蒋介石缺少军事上的优势，而且差距非常大，可抗日可以为蒋介石获得政治资本，这个政治资本让蒋介石在抗战胜利后成为中国名实的领袖，但他没有看到在这场战争中，毛泽东也积聚了强大的力量，更重要的获得了解放区的民心，蒋介石还把毛泽东当成他击溃的那些军阀，轻率的发动了内战，三年后，蒋介石一败涂地。

    自1931年九一八事变开始，蒋介石应该已经认识到日本灭亡中国已是箭在弦上，一旦日本快速进攻中国，30年代初的蒋介石就可能有灭顶之灾。因为蒋虽然是中国名义上的领袖，但在地方，有的军阀根本就是自立为王，蒋真正能控制的就是长江中下游流域的几个省，当然，这几个省是中国最有实力的省份。只要是内斗，任何人都抢不去，可是一旦日本人进攻，必然也要占领这几个省份，蒋介石势必要丢掉。蒋介石当时是内战很行，外战不行，如果长江中下游流域的地盘丢了，蒋介石能到哪里去呢？最好的地方自然是云贵川一带的大西南，按照中国的地理特点，自然是"打内战，跑台湾，打外战，到四川"，这都体现在蒋介石的身上了。大西南地势险要，易守难攻。而且还可以建立与外面的通道（后来有滇缅公路）。所以蒋介石一方面苦心经营长江中下游流域的省份，打下雄厚的经济基础，取得内战的优势，成为中国名副其实的领袖；另一方面更要苦心经营大西南，把大西南变成大后方，为自己留条后路，为将来的抗日战争时采取"用空间换时间"的战略准备条件。蒋介石借围剿红军之机，把势力伸进了贵州，王家烈被拿下，云南的龙云受到震慑，四川的刘文辉、刘湘被收服，红军所到之处，中央军尾随而进，将当地不听话的武装一一拿下，一路收拾了西南"诸藩"。这既是当时统一的行动，也是为将来的撤退做准备。从当时蒋介石重点经营西南来看，蒋介石还是很有理智与眼光的。同样毛泽东在掌握了党的领导权以后，决定"北上" 长征的战略部署相当高明，因为蒋介石既然苦心经营大西南，一定不会让共产党的力量活动在川赣云贵一带。第五次"反围剿"失败后，根据地已失，留在当地已不可能，南下更不可能，蒋介石的重兵严阵以待，只有"北上"。"北上"既可以避开蒋的重兵和战略的刀锋，又能接近苏联，同时，"北上"抗日，更可以把力量渗透到马上就快不属于南京国民政府的广大北方，从而为以后的崛起奠定基础。正因为蒋介石与毛泽东的正确决策，蒋介石的"西进"，完成了对西南的改造，在抗日战争中，蒋介石的长江中下游地区尽失，仍可以从容的撤退到西南，依靠险要的地势与外交的运作，巧妙安全的接受美国的援助，抗战胜利后的迅速恢复对中国大部分地区的统治。毛泽东的"北上"，保留了火种，保存了实力，在敌后开辟了许多抗日根据地，为解放战争的全面胜利也做了重要的铺垫。

 

    早年的蒋介石可能并不怎么在意毛泽东，但蒋介石考察过苏联后，深知共产党的厉害。在北伐中，共产党组织的工农运动给蒋介石留下了深刻的印象。国共分裂后，蒋的最大敌人是国民党内部的对手，当蒋确立在国民党内地位的时候，共产党的势力已开始壮大，毛泽东的革命根据地建设的有声有色。这时候，蒋介石似乎已经意识到最终能战胜自己的不是那些依靠权术不学无术的军阀，而是能动员群众起来革命的共产党。

    蒋介石对红色根据地进行了一次又一次的围剿，毛泽东巧妙的化解。此时共产党开始了党内的斗争，苏联控制的共产国际派王明等人到中国来接收共产党的领导权，并把在上海存不下去的党中央搬到苏区，彻底的剥夺了毛泽东的领导权。可在险恶的局势下，有苏联撑腰的王明等人，虽熟读马列经典，但却不懂得军事谋略，靠不熟悉中国国情的德国人李德当军事顾问。王明等人只是纸上谈兵的书生，他们习惯于政治斗争，却不适应战场上的惨烈厮杀，这些人当然不是已做充分准备势在必得的蒋介石的对手。

    在蒋的打击下，中央苏区被迫转移，红军到陕北后，蒋介石又步步紧逼，但一个西安事变，打乱了蒋介石的部署，蒋介石被迫联共抗日，国共第二次合作开始。

    "攘外必先安内"的政策是中国面临日本侵略，蒋介石又要打败政敌进行内战的情况下提出的。符合蒋介石的利益的，部分成全了蒋介石，最终也让蒋介石付出了巨大的代价。当中华民族面临灭种的危险，民族救亡运动持续高涨，纷纷要求抵御外侮时，还继续推行这个政策，未免不合时宜。这也是张杨发动西安事变胆大气壮的原因。个人利益党国利益，在民族利益面前，都是微不足道的，不能代表并维护民族的利益的政党必然会被人民抛弃。

    在解放战争中，占据绝对优势的蒋介石却在三年后退出了大陆，刚刚获得空前政治影响力的蒋介石转瞬就成了一个失败者，历史的无情与对人物的选择的苛刻让人可敬可畏。蒋介石在一些事情上的一错再错让他承担不起领导中国走向独立富强的道路。

 

    蒋介石消弱了西南军阀，又赶走了共产党，欲灭亡中国的日本成了蒋介石的致命大敌。蒋介石一边消平内乱，一边准备力量，迎接迟早要来的中日之战。1931年日本占领中国东三省，1935年又搞华北五省自治，一方面蒋介石在国内加紧统一的步伐，另一方面日本人也加紧对中国的侵略。蒋介石在进行军事统一的同时，也进行了比较有成效的经济建设，从1927年到1937年被称为国民政府的黄金十年，交通运输业、工业都得到一定的增长，1936年，南京国民政府全年财政收入19.73亿元，约为1927年的6倍。但是没有政治的稳定，经济建设就不可能进行到底，蓄谋已久的日本人会让中国完成经济建设吗？为打掉中国崛起的可能，1937年7月7日，日本发动了全面侵华战争。日本军队在中国烧杀抢掠，无恶不作，中华民族遭到巨大浩劫，日本的野蛮残暴的行径激起全民族的愤怒，中华民族是一个有尊严有顽强生命力的民族。中国人没有被日本的屠杀与侵略吓倒，一批批爱国志士奔赴前线，用生命与热血谱写了一曲曲壮烈的抗日之歌。

    1937年9月，国民党提交了共产党的国共合作宣言，第二次合作的正式形成，从而拉开了长达八年之久的波澜壮阔的抗日画卷。蒋介石的"攘外必先安内"的政策，在西安事变中遭受重创，现在随全面侵华战争的爆发而彻底破产。虽然当时中国和日本已经处于战争状态，蒋介石政府仍然没有对日宣战，直到1941年12 月9日，国民政府才对日宣战。尽管国民政府开始没有宣战，可日本人并没有放松对中国的侵略。国民政府组织了淞沪会战、徐州会战、太原会战（国共合作）等，抗击日军侵略，打击了日本的嚣张气焰，给日军以重创，蒋介石的"地无分南北，年无分老幼，无论何人，皆有守土抗战之责，皆应抱定牺牲一切之决心"还是极为动人心魄的，"一寸山河一寸血，十万青年十万军"，也曾激励了无数抗战将士。仅淞沪会战就打破了日军三个月灭亡全中国的狂妄计划，1937、1938年的几次会战，蒋介石精锐尽出。讲蒋介石不抗日，这是不对的，蒋介石不仅抗日，而且还反共，还要提防国民党内的对手夺权，所以蒋介石的抗日表现出了一定的复杂性，有时不动声色，有时大张旗鼓，有时坚决反击，有时媾和妥协。总体来说，在抗战的初期，蒋介石的抗日是积极的，也是有成效的。后期，由于自己实力的消弱与国内外局势的变化，蒋介石的抗日变得不那么积极，甚至做出了皖南事变这样让日本人高兴，中国人痛心的事。随着共产党力量的不断壮大，共产党在北方的敌后根据地进行了艰苦卓绝的抗日斗争，牵制并打击了大量的日军。

     无数忠勇志士为民族前途抛头颅洒热血，几百万将士战死疆场。察哈尔民众抗日同盟军第2军军长吉鸿昌"恨不抗日死，留作今日羞。国破尚如此，我何惜此头？"；29军军长宋哲元"宁为战死鬼，不作亡国奴！"；19路军总指挥蒋光鼐在淞沪会战时说"本弹尽卒尽之旨，不与暴日共戴一天!"；23师少将参谋长黄启东在徐州会战中说"何以对国家？何以对民族？宁作战死鬼，不作亡国奴！"；131师师长阚维雍"千万头颅共一心，岂肯苟全惜此身，人死留名豹留皮，断头不做降将军！"；杨靖宇壮烈殉国后，残忍的日本人剖开他的肚子，发现胃里只有棉絮和草根；第七战区司令长官、第23集团军总司令刘湘死前留下遗嘱"抗战到底，始终不渝，即敌军一日不退出国境，川军则一日誓不还乡！"；第57师师长余程万在常德会战时给司令长官孙连仲的电文"弹尽，援绝，人无，城已破。职率师部，扼守一屋，作最后抵抗，誓死为止，并祝胜利。"

    硝烟散尽，斯人已逝，但其爱国之举豪壮之言英雄气概民族精神必将万古长青浩气长存。

 

     抗战胜利后，由于蒋介石发动内战，使国共两党从共同御寇的战友变成兵戎相见的仇敌，正因这个原因，国共两党在内战后相当长的时间里，都不能对对方在抗日战争中做出贡献的人进行公允的评价。现在国民党已彻底的蜕变，也丧失了政权。而共产党在不断的发展中，已逐渐的放下历史的包袱，也有了更宽容的态度对待并不轻松的历史。我们现在可以以弘扬民族精神，复兴民族大业为号召，更为客观公允的评价这些为中华民族做出贡献的将士，至少让那些在抗日战争中浴血杀敌舍生取义的将士在现在或将来得到应有的荣耀。

 

    先致力于一个统一稳定的国家，然后进行经济建设，在增强国家的抵抗力的基础上，提高人民的整体素质，最后开始民主政治。在历史上，袁世凯与蒋介石曾经达到了第一个境界，但最终又被历史所抛弃，于是历史必须再次进行选择。当蒋介石与毛泽东对决之时，也是中国历史发展到必须要为统一稳定的中国选择最佳的人选的时候。蒋介石有太多的缺陷而最终落败，历史选择了毛泽东。

    蒋介石虽名义上拥有全国的统治权，但实际上并不能掌控全国。对西南、西北的控制力相对薄弱，其地方大员对他阳奉阴违，张学良一气之下，也能对他实行兵谏。而毛泽东则不一样，他对党的控制是有效的，这是毛泽东能取得胜利的一个原因，但同时也为建国后毛泽东犯的一些错误也提供了一个原因。

    毛泽东用党的形式统一了力量，党内虽有几次斗争，都没有影响到毛泽东最终掌握党的领导权。而蒋介石一生都在进行党内的斗争，内耗不止，越到艰难的时候，制肘越大。

    为什么历史选择了毛泽东而不选择蒋介石，因为蒋介石心中虽有国家大义，但其中包含了更多的个人私心。他也想振兴国家，复兴民族，由于目的与手段不同，决定效果的差异。他用重金收买对手的部下，瓦解其战斗力，也纵容了其爱财与不忠；他进行金融改革，加强工业建设，富强国家，同时也是为了四大家族的利益；东北已被日军侵占5年，民怨沸腾，张学良率部攻击陕北的红军受挫，一肚子怨气的时，蒋还贸然的到西安督战，被张所擒；抗日战争时美国的巨额援助的一部分被他的亲戚和部下瓜分；国民党已处于生死存亡的关头，蒋氏政权已摇摇欲坠，老百姓已民不聊生，陈布雷劝其能否让他代表的家族们拿出一点钱来拯救党国，蒋却勃然大怒。当这些历史事件一个接一个发生的时候，历史的选择便慢慢的从蒋的身边走开。蒋介石找不到一个来平衡人民利益、国家利益、民族利益、家族利益和代表阶级利益的最佳方法，他缺乏直面现实的勇气与通古贯今的才能。历史的选择曾经光顾到他的，但最终还是选择了离开。他只能终老于孤岛之上，不知他晚年遥望大陆，是否能意识到这个问题。

   而毛泽东则不同，毛泽东首先过了个人利益这一关，无论是个人生死的置之度外，还是其家人的献身精神，蒋介石都无法与之相比，对历史与事理通透的智慧也是蒋所不及。虽然他们早年都学过曾国藩，但蒋一辈子都只停留在曾国藩的境界，蒋介石还经常的给他赏识或要警告的部下送《曾文正公全集》，三民主义成了他的口号，没有内容。他的内容就是曾国藩的休齐治平。毛泽东从白话文与马克思主义中吸取了营养，从国民党的组织形式中学习了经验，顺应时代的特点与要求，又结合中国的具体情况作出了天才般的组合与创造性的发挥，远远超越了曾国藩的境界与功业。曾国藩再厉害毕竟还是一个将，而没升格为帝王，曾国藩更多的是治平之术，而不是帝王之术。所以结果毛泽东得了天下，蒋介石在台湾把曾国藩的治平之术发挥到了极限。

    由于毛泽东的政治素养与历史际遇，加上众多具有强烈爱国心有实践能力的人参与实践、前仆后继，共产党越来越有力量。毛泽东在三十年代末掌握中国共产党的时候，就注定这个党将不是一个平凡的党。

    毛泽东把握住了中国必须要统一稳定的脉搏，创造并借助中国共产党的组织形式，恪守为人民利益的准则，加上个人的优秀素养与高超的政治谋略，终于取得了胜利。

    也许蒋介石终其一生，都未能领悟，为人民利益这个意思的含义。他的心中有家国，没有人民。他看到国破则家亡，家亡则人危，他看不到家就是人组成的，而国又是由家组成的，没有人民，哪来家，没有家，又哪来国？更要命的是蒋介石的"家"不是普普通通的百姓之家。任何一个政党，忽视人民的利益，都不可能取得持久的最终的胜利。

    蒋介石前期还应该算一个革命者，最起码是一个勇敢的军人，但1927年下野后，与宋美龄结婚，"中美合作"（蒋介石字中正）既是他发达的起点，也是他失败的起点，从此他彻底的落入家族的漩涡。他借助了四大家族为代表的力量，也失去了其他选择的可能，这是他的喜剧，也是他的悲剧，也许是他本性使然。如果当时和以后，没有代表人民利益的毛泽东，蒋介石也许可以走出另外一条道路。可历史只选择强者，现实不相信假设。

 

    1949年中华人民共和国成立，毛泽东继续完成中国的统一。特别是对于各地的土匪势力进行了粉碎性的打击，然后对社会恶习进行整治，黄赌毒一扫而空，社会面貌为之一新；恢复国民经济，通过努力，1952年国民经济取得根本的好转；与苏联进行密切合作，引进项目，建立工业基础；对外进行抗美援朝，打出了一个大国的气势，这是中国军队自国民政府远征缅甸之后又一次在国外作战。抗美援朝，打败美国的干涉之心，中国人重新展示了一个大国的尊严与力量，也使新生的国家得以保全，也开创了"御敌于国门之外"的大国战略，从此，让世界不敢小觑中国。

    对于任何一个大国而言，只有统一才能富强，特别是历史上落后于世界的大国，苏联如此，中国也如此。而大国的分裂就会带来衰落与动荡，中国更是如此，稳定的中国才能走向富强。美国能强大，能走向世界，不仅是对外的手段多么的有效，更关键的是美国内功练的扎实，要想不被对手打败，先要强大自己。就像《孙子兵法》说的那样"先为不可胜，以待敌之可胜，不可胜在己，可胜在敌"。

 

    在全文的开篇，我就说道，要从大历史的背景来分析问题，那何谓大历史？那就是承袭历史遗产，立足现实条件，致力民族前途，忽视个人荣辱得失，以其人其事对国家进步，民族复兴的作用作为评判的标准。为什么要用大历史的视角呢？因为中国的近现代史太过于复杂，人物才能的多寡、认识问题的深浅、道德水平的高低，还有时代的局限，造成了知与行的脱节，德与功的反差，成与败的变换，得与失的错位。加上中国人喜欢以成败论英雄的传统，使得我们看中国近现代史就缺乏必要的定力与心胸。要么抓住一点，讴歌不止，不计其余。要么抓住一点，批斗不止，不计其余。我们陷入无休止的讨论中，却忽视了如何继承历史遗产，吸取有益的营养，为现实服务的问题。我提出大历史观不是为了消平争论，抛弃是非标准，而是要尊重事实，放下包袱，承接历史，开创未来，从而展现中国人是如何用鲜红的热血与不屈的精神探索救亡图存的历程，怎样用扎实的行动与高超的智慧实践富国强兵的过程，以及如何借鉴历史经验并结合现实情况推进民主政治的进程。这也是我准备用近三万字来阐述这五个阶段的最深的心思。

    从大历史的角度说，就对外而言，如果说蒋介石领导中国人民经过八年抗战（虽然共产党独立抗日，蒋介石还反共，但蒋介石当时是中国名义上的领袖），其意义在于抗日，赶走侵入中国的日寇。那毛泽东动员全国之力逼退美国，其意义在于抗美，御敌于国门之外。短短的十几年，中国赶走了日本，重创了美国，这就是民族的胜利，这是以前清政府与旧军阀所不能为的，这是以前屈辱的中国人所不敢想的。


    四、重装经济：从毛泽东到邓小平看中国的经济改革

    日本作为一个弹丸小国，在短短的几十年里，从一个受到列强欺凌的国家变成一个与列强争雄的东方强国，其历史经验是值得借鉴的。日本的成长带有一定的幸运，多次战争失败的危险都让日本差点走上失败之路。甲午战争中，日本已经把国内最后一支军队调集上阵，清政府只消有一点抵抗的血性，死不认输，拒不投降，坚持抗战，日本必被拖垮。对俄战争时，要不是俄军轻敌于前，莽撞行动于中，抵抗不力于后，日本也不会取得日俄战争的胜利，那日本还是不能吞并朝鲜，觊觎东三省。但日本的富强，我们不能归于幸运，日本是踏踏实实一步一步走出来的，日本首先通过倒幕运动推翻了幕府的统治，确立了天皇的权威，这样一个强有力的中央是日本明治维新能够持续进行的重要保证，是日本改革能够不断地深入的主要原因，美国富强用了一百多年的时间，日本用了几十年，后起的大国崛起完全可以站在已崛起大国的基础上，而选择更有实际效果最符合基本国情的方式。东方国家不需要也不能照搬西方的模式，否则只能犯画虎不成反类犬的错误。我们要学习其" 神"，而不是其"形"，我们要根据我们的历史经验走出一条符合自己的有中国特色的崛起之路。

    我们对照中国和日本的历史就会发现，东方大国崛起的道路是不同于西方的。日本通过倒幕运动确立了中央的权威，消除各地封建势力，培育市场，走上强国之路。而中国的这一历史过程则相当的长，付出的代价也太大，中国由于康梁维新运动失败，被迫从自上而下的改革滑向自下而上的革命，从孙中山到蒋介石，致力的都是一个统一的有中央权威的中国。可见对于一个落后的大国，政治的稳定是何等的重要，但蒋介石是不能在中国完成真正意义上的统一的，西方列强不会轻易的让中国走上富强的道路，苏联也不想有一个强大的中国在身边崛起，东方的日本更把中国的崛起看成是自己丧失东亚地位，永无出头之日的标志。这一切对蒋介石都是致命的，更要命的是蒋介石的内部一直不能内斗不休，始终不能凝心聚力，加上被蒋纵容的腐败，都是蒋介石越到后来越头疼的事。没有政治的稳定，就不可能有强大的国防，蒋介石在内忧外患中必然要败下阵来。蒋介石是一个生不逢时的人，他碰上那个时代必然要碰上的最为强劲的对手--日本，又逢上一个比他更有智慧更有力量更准确的抓住时代的脉搏更具有历史意味的人--毛泽东。蒋介石的口头禅"娘希匹"，与其说是对部下和对手发牢骚的不满，倒不如说是自己对时代命运看透后的嘲讽。

    毛泽东凭其雄才大略，与草莽中崛起，在江湖中驰骋，用智慧与勇气走到历史风云际会的交点，打造了一个统一的中央权威能一贯到底的中国，把一盘散沙凝聚成一个可以切金断玉的砂轮，这是毛泽东对中国历史最大的贡献。

    前面反复说的抗美援朝，是具有奠基作用的。战争是检验一个国家实力的最好方法，中国顶住了美国的压力，展示了强大的武力，证明中国经过一百多年的奋斗，终于站起来了。

    毛泽东提供了政治稳定，邓小平开始了经济建设，没有政治稳定的前提，中国在列强的虎视眈眈的险恶局势下，进行并能保证改革开放顺利进行是不可想象的。

 

    经一百年混乱，12年大战，1949年的中国，满目疮痍，百废待兴，国家一穷二白。经过三年建设，到1952年，经济取得根本性的好转。1952年全国工农业总产值实现大幅度恢复性的增长，工业生产恢复到了战前水平。从1953年开始执行第一个五年计划，重点发展发展重工业，建立国家工业化和国防现代化的初步基础，在苏联的帮助下，第一个五年计划提前完成。1957年工农业总产值比1952年增长68％，特别是钢增长296％，煤增长96％。此后，一方面依靠苏联的资金技术援助，一方面自力更生，艰苦创业，逐步建立和发展起了比较完整的工业体系；在建国初期，苏联对中国的援助不仅及时，而且有效。156项援助主要为重工业和军事工业，全面提升了中国的工业水平。想想印度研究了几十年，连阿琼坦克都搞不定，就知道工业的差距了。集中精力向高尖端技术迈进，1964年中国第一枚原子弹试验成功，1967年第一枚氢弹爆炸成功。大规模兴修水利，改造农田。扫除文盲，提高识字率，农村尽可能的普及小学教育，城市尽可能的普及中等教育。现在，有10亿人口的印度还有4亿文盲，这就是差别。没有奠定的这些基础，后来的改革开放就不可能高歌猛进，动力十足。

    在发展初期，都面临全面引进和自主研制的问题。在这个问题上，无论是曾国藩，还是毛泽东，都给我们做出了正确的榜样。洋务运动时，有人提出"造船不如买船"甚至"买船不如租船"的谬论，曾国藩则买的同时坚持自造。徐寿和华蘅芳造出并不先进的中国第一艘机动轮船黄鹄号时，曾国藩高兴异常。毛泽东在引进苏联的技术时，力主完全吸收，变成自己的生产力。重工业和军事工业虽受苏联援助，但也要完全为中国所掌握。

    后来被蒋介石暗杀的国民党中将杨杰在1934年写成《欧洲各国军事考察报告》，提到"职预料世界大战战祸一开，必蔓延全世界。是时，各国自顾不暇，致必以海军封锁我国各口岸，断我军火之来源。是时，虽有万万金，不能得一御侮之工具。"

 

    在强国林立，随时准备占点便宜的国际环境下，后起的大国要想发展起来，获得强者同样的地位与尊严，没有政治的稳定是绝对不行的。只有政治稳定了，才能集中力量发展经济，巩固国防，保卫经济的成果。政治稳定，经济就发展，政治不稳定，动乱一起，不要说经济发展，就连人都没有办法自保自存。

    1966年文革开始，国家从狂热转入狂乱，经济遭到冲击，此时亚洲四小龙国民生产总值的年平均增长速度都在10％左右。中国错失了极好的发展机会，当然也和国际局势有关系，当时的国际局势也不像上个世纪八、九十年代那样宽松。

    文革结束后，邓小平复出。在毛泽东的基础上开始进行改革开放。在全面的改革开放之前，有两个奠基：一是1972年，尼克松访华，中美关系开始缓和。这是毛泽东留给后人的一笔宝贵的遗产；二是1979年对越自卫反击战，确定了立场，打消了美国的顾虑，中美开始越走越近。改革开放29年来，中国发生了翻天覆地的变化，虽然还有一些问题，但毋庸置疑，中国确实是富了，确实是强了，人民生活水平确实改善了，人民享有的民主比以前确实多了。尽管牢骚太盛者依然"端起碗来吃肉，放下筷子骂娘"，但却否认不了这29年来的成就。1978年国内生产总值为1473亿美元，2006年我国国内生产总值为209407亿元；1978年进出口贸易总额为206亿美元。2006年进出口总额17607亿美元；1977年中国外汇储备为23.45亿美元，2007年底，外汇储备达1.53万亿美元。通过改革开放，我们有了足够的底气来面对将来的一切困难。我们终于即将度过最为艰难的时段，收获重装经济的胜利。

 

    从近现代史上看，在统一的情况下进行的经济建设，大致有四次。一是洋务派在十九世纪60-90年代进行的洋务运动；二是蒋介石在1927-1937的国民经济建设；三是毛泽东在建国后的经济建设；四就是邓小平以十一届三中全会为标志的改革开放。洋务派与蒋介石的经济建设都因外部势力的强行介入而失败，这两笔账都要算在日本的头上。没有政治的稳定，没有强大的国防，经济建设最终都是空谈。而毛泽东与邓小平的经济建设能取得斐然的成绩，是政治稳定与军事强大的结果。否则，要么成为苏联的政治附庸，要么成为美国的经济殖民地。无论是美国还是苏联能让中国从容的发展经济，富强国家吗？美苏可以让所有的小国都取得相应的国力，但却对大国保存十二万分的戒心。这也是苏联尽管解体了，美国仍苦苦相逼，必须将俄罗斯置于死地的原因。因为从历史来看，拥有广袤的土地，众多的人口，不衰减的政治热情的国家，最终必然摆脱平凡，成为世界上重要的参与者和领导者。

    建国后我们以苏联为标准，再后来又以美国为标准，其实大可不必。诚如当年中国革命不是俄国革命的翻版，那中国的现代化也应该与美国的现代化有异。我们要借鉴外国的经验，却不能迷失自己的方向。

    如何把改革开放进行下去，通过深化改革来解决改革中出现的问题，保住并升华改革开放的成果，则是下一步的重中之重。四次经济建设，有两次受外部势力所累，这告诉我们要有强大的国防和能调动人民的力量。一次受内部的政治影响，这提示我们如何保证航向的正确，保持政治与经济的协调发展。改革开放有了内外两种经验教训，又有了一代又一代人的奠基，这次重装经济一定能踏过荆棘，取得全胜。

 

五、民主政治：从胡锦涛到□□□看中国的民主政治

    历史已经或正在标记，中国的革命与现代化有浓郁的中国特色。我们的民主政治也将有别于世界，因为时代不同，历史相异，文化悬殊，国情有别，如果照抄照搬外国的某一模式，泥古不化，必将犯刻舟求剑的错误。

    民主政治是我们没有尝试过的，但又是大势所趋，现在或将来必须要走，该怎么走，都只有理论，没有实际的经验。理论是否符合特殊国情的中国，还没有检验，无法证实与证伪，但这并不能妨碍前进的脚步。我们可以大胆设想，小心求证，努力实践，及时总结。开创一条符合中国特色的立足现实国情的民主政治的道路。设想可以异想天开，行动必须脚踏实地。实地就是要接到中国的地气，中国的地气就是中国的历史与现状。

    通过以上的论述，我们要重点把握历史的经验教训，找到治乱的规律，寻得强盛的良方。政治稳定是经济发展的保证，没有政治的稳定就不能有经济的发展，这对于近现代的中国是一个颠扑不破的真理。

    政治稳定最起码需要：1、军事力量强大，强大到能保护自己不受外国势力的干扰和破坏。历史教训已很深刻，不再赘述；2、要缓和国内矛盾，要保证政策正确，并落实到行动当中去。不要说的多做的少，更不能动作大，效果小。看似轰轰烈烈，实则劳民伤财，甚至恰恰相反。历史教训一样深刻。

    中国统一后，毛泽东开始向苏联学习，基础工业就在那个时候建立了起来。现在的改革开放取得了瞩目的成绩，西方经济学家分析不出中国经济能保持29年的高增长的原因，在于他们忽视了中国政治的稳定的局面，没有看到毛泽东奠定的雄厚基础。中国经济还能再发展，但是经济发展最终必然要求政治的进步，所以民主政治就是中国按部就班发展的第五个阶段。这也是中国要确立独特的政治稳定经济发展的政治模式，这个模式的建立者就是中国当之无愧的伟人。这个模式最终建立可能要几十乃至上百年的时间，绝不可能一夕而至，任何事情都不可能一蹴而就，任何"毕其功于一役"的想法都是一厢情愿。如果时机与方法不对，只能欲速则不达，对于太需要民主的中国更是如此。

   本阶段能标出开始，后面却只能留白。让圣人登位，让历史填空。

 

政治经济民主

    要战胜竞争者，必须拥有比对手更多优势，并且能知难而进，知错就改。在创业时，阻力大，利益少，义务多，要调动人民的积极性，所以一个政党在政策方面不能出现错误，在权力方面要相对集中，才能组织好人力物力，保证事情完成；创业成功后，守成时，已无竞争对手，思想开始麻痹，利益大，义务少，投机的多，需要更多的监督机制，所以成功后的政党应从权力的集中向民主过渡。在操作上是先民主后集中，在时间上，从历史的角度看，先集中后民主。不集中，不能保证胜利，不民主，难以久长。所谓民主，简单的理解就是对权力有一定的约束力，让权力能为维护大多数人的利益而服务。由谁来约束呢？只能是人民。要保证权力真的能为民所用，不仅要靠制度，还要靠人民的素质，起码得就是人民有一定的政治参与的能力，辨别是非的能力，才能保证不被有些人利用。人民要提高素质，就需要教育，而教育则需要经济的发展。经济的发展不仅为人民提供了受教育的时间与条件，也为人民参与社会活动提供了可能。经济的发展对于一个落后的大国来说，就需要政治的稳定。

   看似被西方宣传的万能的民主，其实它不是空中楼阁，它需要一定的基础。民主是好东西，是将来发展的必然方向，但我们不能为了民主而民主。民主不是口头禅，也不是遮羞布，民主是一种社会的机制准则，需要我们大家共同的努力。不要陷入民主本身好坏的怪圈，只要有利于国家发展的就好。当年罗马实行共和制，也没见其如何的领先世界，中国当时实行君主制，领先世界上千年。中国要积极地探索适合险恶国际局势下后起大国的民主道路。

    没有政治的稳定和经济的发展，很难有民主的到来，可以不夸张地说，政治的稳定和经济的发展是民主政治的前提。二战以后，广大的殖民地开始实现独立，国体与政体的选择在力量、历史与理智中归队。一些国家接受了美国的民主，比如有日本、韩国、联邦德国等；一些国家采纳了苏联的模式，主要是东欧一些国家，这两种不同的选择，在以后的冷战中，进行殊死的较量；还有一些国家对美苏都不感兴趣，既不想受苏联控制，也不想受美国领导，希望能走上独立自主发展的道路，他们都选择了美国的民主，他们是非洲和拉丁美洲几乎所有的国家。

    几十年后，苏联的模式缺乏可持续性，自然退出历史舞台；非洲和拉丁美洲的国家的美式民也大多被历史证明并不成功，特别是非洲民主的溃败就像当年独立运动一样迅猛；只有日本、韩国、联邦德国采取的民主是初步成功的。于是，美国以这几个为样板，开始用民主武器征服其他不听话的国家。日本、韩国这些国家真的能代表所有的国家吗？他们的民主道路可以随意复制吗？其实日本、韩国联邦德国和台湾的民主模式是不可以作为参照的，因为那是在美国的保护下建立起来的，民主中稳定的力量由美国来提供，并且美国是用心的来操作他们的民主，因为要对抗苏联，包围中国。如果不在美国利益的范围内，美国对民主的操作就不仅是用心，而且还别有用心了。这也是美国扶持的民主都胜利了，美国不扶持的民主则命运多舛的原因。菲律宾的民主没有让国家走向富强，卢旺达的民主带来了种族屠杀。在地方豪强势力和外国野蛮势力的操纵下，民主变成了控制一个国家最好的杠杆。

    是民主不好吗，不是的，民主是好东西，但民主也要靠人来操作。民主一定要符合那个国家的历史与现实，当条件不具备时，没有政治经济保障的民主可能不是最好的选择。就像一个已经渴了三天的人，他要喝水，你却偏给他肉吃，他会喜欢吗，你能说肉不好吗？好，但是他最需要的是水。对于落后的国家而言，现阶段最需要的不是民主，而是民生。

    美国的民主与美国输出的民主是两码事。美国的民主确实是好的，要不然美国也不能如此强盛，但美国输出的民主就参杂了美国的利益，因动机不纯，就要有区别对待。

 

民主政治的实现

    其实民主政治并不神秘，从中国目前的情况来看，就是执政党更有理智与理性，更有克制与远见；建立法制国家，国民在"法"的范围内行使权利，履行义务；人民的权力受到保护，享受到国家发展带来的成果，特别是改革开放的成果；加强执政党自身建设，惩治腐败；扩大民生，建立福利型社会；抑制两极分化，照顾社会公平；转化经济模式，走可持续、能竞争的道路。目前科学发展观的提出，产业布局调整，农业税的取消，九年制义务教育的真正落实，探索新的医疗改革，虽然这些离彻底的解决国内许多问题还有一定的距离，但是要清晰的看到本届政府努力的价值。

当务之急的几方面

    1、保证经济持续的发展。没有经济的发展，没有民生的保证，民主政治就很难实现。即便实现，也是一种形式，缺乏内容。保障民生，增加内需，建立福利型社会，既能维护社会稳定，又可拉动经济发展。

    2、精英阶层要担负起一定的使命。精英这个词在中国几乎要变成贬义词了，这是中国精英的悲哀与自作自受。本该是高智商的代表却被人们唾弃，精英们要反省这个问题。精英阶层要从利的获取向社会良心的维护上转变，或者说不以利作为主要的追求，社会责任感要普遍的增强，一部分人要有起码的道德良心，担负起家国、民族赋予他们的使命。有心、有力、有德三者结合在一起，才可谓是真正的精英。

   3、普通民众的素养要提高。民众素质提高了，就能够有自己的立场与判断，能够从理智的角度考量某一政策或某一作法的带来的利弊。提高民众素质，要靠教育。

    "十年树木，百年树人，百年大计，教育为本"。教育是一个民族可持续发展的智力保证，其作用难以估量。现在很多年龄大的中国人能识文断字，不是文盲，这得益于毛泽东时代的普及教育，你能说中国的改革开放以来中国快速发展与教育没有关系吗？

    振兴教育，可努力的方向有三。

   第一、改革教育对利的追求。教育一旦和现实的利挂钩，那前景就堪忧了，必将侵蚀教育的基础，利具有短期性与盲目性，而教育则是有长期性与前瞻性。从目前来看，首先要消除教育产业化的不利影响，教育资源分配要公平，教育资源分配公平了，腐败的环境就会得以改善，逐利的冲动就会大大的减少。

    第二、教育要变成受保护的行业，而不是成为最终负本不该负责任的行业。如今社会部分部门不作为，该其担负的社会责任不愿承担，最终落到学校的头上，学校只好做冤大头。其行政领导无心也无力从事学校的管理与教学。这个现象如果不得到制止，学校承担的责任将越来越大，最终将影响学校正常职能的发挥。社会其他部门要把本该自己承担的责任承担过来，从法律和制度上保证不许向教育转移。

    有一句话很多人都知道"没有教不好的学生，只有教不好的老师"。这句话提出本身就是不妥当的。我们承认教育的功能，但不能极度拔高到万能的地步。教育不是万能的，老师也不是神，学生更不是可以随意揉捏的泥巴。由于教育资源分配不公平的存在，老师学识修养的差异，学校具体情况的不同，更由于社会环境的恶化，怎么可能把每一个学生都教好？就是让老师一天24小时不眠不休，也不可能教好每个学生。特别是在广大的农村，由于父母外出打工，家里只有爷爷奶奶或其他亲戚照看小孩的现象比比皆是，这样的留守儿童，留守少年，缺乏必要的家庭监护、家庭教育，他们所处地区的教育资源又比较缺乏，他们中的一部分意志力控制力薄弱的就很难教好。"没有教不好的学生，只有教不好的老师"，这样武断的评判只会掩盖教育资源分配不公平的现状，忽视仅靠教育无法解决的社会问题，让教师产生深深的挫败感，更可悲的是，一些学校为迎合家长的期许，还大力提倡这样的口号，不自觉地加深了这种谬误。

     第三、教育部门要反思。我们的教育观念是不是先进，创新是不是有基础，教学改革是否合情、合理，是否根据地方的差异教育资源的不公平现象来调整政策，行政领导是否对教育的职能有深刻的理解并落实到行动中去。我们的教育工作者是否从教书与育人的两个角度出发去想问题，去认真地工作，又是否能意识到肩负的是民族的责任，坚守的是未来的希望。社会上对教师的评价在降低，在这传统尊师重道的国度，是不是让我们想到了什么？

不是我苛求教育，实在是教育关乎民族的将来，希望每个从事教育的工作者不要生气。

   4、惩治腐败，加强监督，重案要用重典；增加政府职能部门的透明度，让民众享有更多的知情权；完善问责制，建立长效机制，定时通报。

   5、尝试基层民主，探索党内民主。

 

几个防止

防止冒进

    中国苦难多了，未免就有情绪上的不耐烦，想一夜之间变成富强民主的国家，就容易犯冒进的错误。中国大跃进时，要求钢产量在15年左右赶超英国，后来又提到了5年，最终达到了，又能怎样，对经济发展起到促进作用了吗？其效果往往是相反的。所以国家的发展，民族的较量不可争一时之短长，而要有长远的眼光，有持续的动力。陈澹然说："不谋万事者，不足谋一时；不谋全局者，不足谋一域。"用科学发展观，用长久的战略思想，稳稳的布局来武装中华民族，才能从理智上战胜冒进的错误。任何一个领导者都有责任不贪功，不冒进，完成历史赋予的时代要求的某一阶段的任务，那么他就是中华民族的功臣。反之，可能出力不讨好。

防止乐观

    中国人是很容易乐观的，即便喜忧同在，都是报喜不报忧。尤其在取得成绩之后，被外国人赞美之后，乐观的更加严重。屈辱的近现代史确实需要成绩与喜悦来振奋，但要实事求是，要清晰的看到我们与世界发达国家的距离。比如城乡差距就很大，就像原辽宁省委书记闻世震说的那样"城市建设得像欧洲，农村发展得像非洲"。我们还有几十年艰辛的路要走，在未来的几十年里我们都要保持谨慎的乐观，好大喜功往往不是强盛之兆，可能是败落之源。

防止破坏干涉

    我们越来越强大，必然有人不喜欢，破坏干涉将以各种花样不间断的出现。我们要做好防守反击的准备，只要政治、经济、军事、民生协调发展，以中国人智慧与潜力，可以从容的击溃各种破坏干涉。要防止破坏干涉，重点是练内功。自己不可战胜了，就不会有人来自讨没趣，自取其辱了。

防止内乱

    有人讲现在发展这么好，有什么内乱？没有更好，所有的爱国者都不希望有，但要居安思危。中国最怕的就是内乱，内乱一起，必将生灵涂炭，不知要过多少年的杀伐征戮，才可以重见和平。当年要不是明朝先有内乱，满清怎么可能入主中原，确立对中国的统治。可以肯定，将来中国要是出现危机，一定不是外忧，首先必是内患。但愿此言不中，中国少走点弯路。

防止过度稳定

    何谓过度稳定，就是为了稳定而稳定，采取高压封堵，而不疏导解决。问题积累多了，就难以解决了，小问题就变成大问题了。我们要有这种智慧：为了稳定而稳定，从来就不是真的稳定，只会造成更大的不稳定。

 

     民主政治就写到这里，还有很多问题没有讲透，但实在写不下去了。提出民主政治这个问题，易如反掌，但具体怎么样操作，则难之有难，必须慎之又慎。关于这个问题，我思考的虽多，但得到的结论很少。可参考的理论太多，能让人完全信服的很少。姑且写到这里，让岁月积累，让新的看法成熟，以后的事以后再说吧！

会同天下2008年2月26日

httx.cn@163.com  或 httx.cn@qq.com
