# -*- org -*-

# Time-stamp: <2011-08-30 16:42:24 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 【友人评序】


（2009年1月）

在“大国崛起”的时代主题下，中国面临的最大威胁和挑战是什么？是未雨绸缪，还是仓促上阵，结果会大有不同；各种判断的准确程度不同，相应的准备和应对的质量也必然有不同。兹事体大，不可不察。

在本人看来，我国面临的全局性安全挑战有三个：粮食安全、能源安全和金融安全，三者任何一条出现纰漏都将导致全局性的被动；而自然而然的，与中国存在竞争关系的国家和组织也会在这三个方向上，力争找到中国的漏洞并大作文章。其中，粮食安全因为事关生存，是最基础的，所以中国中央政府的重视在程度上应该说还是到位的，但即使如此，近年来以大豆为代表的农业与食品加工业还是被打开了缺口。所以，在关乎重大安全利益的斗争的领域，斗争的复杂和激烈程度，确实不是常人可以想象的。

同样的的斗争也反映在能源和金融安全领域。因为这两方面跟老百姓的生活联系不够直接和紧密，所以人们往往对他们是忽视的，这种群体性的意识被动会不知不觉造成巨大的损失。如何让我们的国民对这些既关乎全体，又影响个人的根本性的问题具有更深入的认识，在舆论需求和导向上对国家的应对策略提出更高要求，就成为一个非常关键的问题。在这方面，井底望天所著的《花开花落》就是一部非常成功的作品。

在能源安全方面的讨论上，《花开花落》做到了传统能源和新能源并重，这是既符合当前实际又着眼长远结构调整的老成之见。在传统能源和其关联的传统地缘政治中，作者重点讨论了在中亚、高加索一带的各方博弈，2008年诸多重大国际事件围绕该地区酝酿和发生，不是偶然的，也是未完结的，这个地区与中国的利益关系重大，而将来会变得更大，这也是作者不惜笔墨的原因，竭力为国人详细描绘的原因。而在新能源方面，作者敏锐得捕捉到了新能源对传统能源、地缘政治规则的重构作用，以及在整体安全方面的相应影响，关于这方面的讨论，在国内尚十分罕见，十分值得重视。

金融安全又是一个大话题。在2008年下半年最终破绽的以美国为首的发达国家的金融体系，给长期被哄骗、被洗脑的国人是一个绝大提醒，借此契机，彻底搞清既有国际金融体系的运作规律、杀伤机理，就成为《花开花落》的一个重要贡献。

为了在未来的国际竞争中做到既保障安全又有充满活力和竞争力，则需要在经济和政治方面做出相应的主动调整。在这方面，作者着重提出了以区域政区和经济重构为目标的"经济圈"概念，并指出了其与新能源、新交通互为支撑的紧密关系。这对政治经济结构的调整，应该说是一条线索清晰，导向有力的纲领，对解决中国长期积累下来的问题是一个非常有建设性的思路。金融危机效应显现以来，我国政府采取的各项措施，应该说跟之前（《花开花落》成文于2008年8月-9月底，正好在国际金融危机全面恶化前夜）本书提供的思路框架是完全吻合的，这充分显示出作者的远见卓识。
