# -*- org -*-

# Time-stamp: <2011-08-30 20:20:18 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 【编者文代序·制高点】

（2009年10月）

+ I

金融海啸前，若干年

北京大学，中国主流思想界指标
理教117教室，某“主流”经济学选修课，>500学生，爆满。
漆黑中放映的是一部特别安排的电影：《制高点》，the Commanding Heights。[fn:jdwthkhl0011]

[fn:jdwthkhl0011]  “制高点”这一名词系列宁发明，用来描绘经济中的核心、重要部门。在列宁所身处的19世纪末20世纪初，人类正在逐渐进入电力时代，经济中出现了一批核心的，巨型的经济部门，如当时新兴的电力和传统的煤炭、铁路交通等等，“社会主义=苏维埃+电气化”是列宁的名言。在后来的历史时期，电力、航空、电信、能源、公用事业、资源及泛IT科技相继成为相继成为核心的经济“制高点”。

“经典”，主持的教授用一贯的富有磁性的声音推荐，“必看。”

＊＊＊＊＊＊＊＊

《制高点》说，它发现了20世纪的主轴：较量，两派经济思想的较量

一派的人格化身，是凯恩斯，

据说，凯恩斯=罗斯福=经济调控=管制干预=信息收集困难=效率低下；

另一派追认的人格化身，是哈耶克，

据说，哈耶克=撒切尔=市场社会=自由放任=“看不见的手”=药到病除。

结论：人类通过大半个20世纪的“曲折经历”，终于摆脱了种种蛊惑，醍醐灌顶，顿悟真谛。人类走上了导师哈耶克那“自发秩序”之手所指的的光辉道路。

“Privatize your Commanding Heights! and you will be blessed by the invisible hand!” [fn:jdwthkhl0012]

[fn:jdwthkhl0012] 这句意思是：把你的经济制高点私有化吧！你将被“看不见得手”（市场）所保佑和祝福！

墨西哥顿悟了，它拥有了世界第一富翁[fn:jdwthkhl0013]和越来越多的贫困人口。

[fn:jdwthkhl0013] 墨西哥美洲电信（American Movil在拉丁美洲地位地位可比中国移动）老总Carlos Slim Helu，在金融危机爆发前的2007年7月荣登世界首富位置。他在90年代私有化墨西哥国家电信公司时接盘。

玻利维亚顿悟又“迷茫”了，《制高点》明星演员罗札达下台，印第安阿叔莫扎雷斯上台[fn:jdwthkhl0014]。

[fn:jdwthkhl0014] 它为玻利维亚人民留下了未来的“世界经济制高点”：安第斯高原上的盐湖——用于未来新能源汽车电池原料的锂库。

包治百病的制度疗法，在人民的摇晃下，或成政策神油。

＊＊＊＊＊＊＊＊

国际间的竞争和较量，如果不是，或至少不全是“黑白分明”的独门英美祖传制度秘诀，那么，是什么？

《制高点》作者——名牌作家丹尼尔·耶尔金的成名作：《石油博弈》，道出真相：“对资源的掌控”。

但沙特不因为石油而为世界老大，大国游戏所依赖的资源，绝不仅仅是石油，煤块和铁矿石。

＊＊＊＊＊＊＊＊

20世纪上半叶到60年代，苏联依靠人力和资源的粗犷投入，神奇工业化，世谓“苏联工厂”

20世纪50年代到1973年，日本飞驰在高速发展大道上，年均增速超过10%，人称“日本公司”

20世纪70年代-80年代，苏联人口不平衡迹象日益明显，社会日趋冷却；20年，尽管普京不断打气，俄罗斯已经沦为资源出卖国

20世纪90年代起，日本在“高龄少子”怪圈里扑腾，“一亿总中流”瓦解；2005年，日本总人口达到顶峰，人才凋零，举国哀鸣

中国的迅速增长，从某种意义上，是依靠一种“准不可再生”资源：人力

曾经相对年轻的年龄结构，与铺垫好的基础能力相配合，在很多领域，的确搞出了“东风压倒西风”的架势，横扫百国如卷席

前车之鉴，后事之师。

俄国还有油桶气罐，日本还有技术家底

我们靠什么？

*如果，不能在恰当的时间内，将现有人口资源及时转化为新的、扎实的科技资源，低福利、低水平而挣扎无力的高龄社会结构，就可能横挡在未来的路上。*

有人说，靠“比较优势”而“积累资本”，靠“资本自然积累”获取产业升级或转型。

*温州的局面告诉你：世界上从来没有那么想当然的事。*


+ II

自2007年起，世界发生了两件大事，分别瓦解了过去三十年世界经济体系的两大主轴

第一件事，便是人人皆知的世界金融危机海啸，它摧毁的，是过去三十年发育并在21世纪后达到顶峰的金融市场社会结构；

第二件事，以奇梦达[fn:jdwthkhl0015]的倒掉为标志，硅半导体业[fn:jdwthkhl0016]时代逐渐走到尽头。“摩尔定律”神话开始走向收尾。

[fn:jdwthkhl0015]奇梦达，Qimonda，是电脑内存芯片（DRAM）制造企业，为世界前四大DRAM制造商。
[fn:jdwthkhl0016]硅半导体业由美国发端，并由美国把握核心（中央处理器CPU的制造者英特尔，外加其它企业如AMD、一体化企业德州仪器、摩托罗拉-飞斯卡尔、设计企业高通、博通等等），其余非完全核心的部分可以散步到全球，如DRAM制造企业（日、韩、中国台湾、德），芯片代工企业（中国台湾、新加坡等）但形成美国企业为核心的企业网络。硅半导体等硬件和重要的软件配合，以英特尔和微软的搭配为典型（Wintel），构成美国核心生产竞争力。

*历史的先声总是在某些专业领域敲响，为少数人所意识。*

过去30年，美国握Wintel同盟[fn:jdwthkhl0017]为内核，铺个人电脑和互联网为经脉，展通讯设备和应用为辅助，打造出泛IT产业之锚，将自己拉出70年代的泥潭；

[fn:jdwthkhl0017]即电脑核心中央处理器（CPU）生产商英特尔（Intel）和操作系统垄断提供商微软的主打产品Windows操作系统的两个词的合并。这一同盟形成于90年代，其手法是英特尔和微软均推广个人电脑，并提供计算能力远远超过个人需求的CPU，维持高价，来支撑微软并不高明的操作系统。形成一个“高价/提供超过实际需要的功能/赚取垄断利润”的格局。在高科技行业的过去20年里，过得最舒服的就是近乎垄断地位的英特尔和微软。

再以泛信息产业再应用于金融、软传媒，挟“自由贸易、解除管制”为号令，股市游戏，商品赌博，出手安定海湾能源，虽未武功十全，但足已横行于地球。

30年后，泛IT产业之锚在技术的演化下开始自我侵蚀，信息通信产业日益走向公共平台，以此为暴利和权柄，日成幻影：

内核死党Wintel在节能芯片、上网本、开源操作系统的新模式下公开破裂；

泛IT行业里，芯片制造业走向“巨型投入，赌博利润”的困局；

“老”通讯业里，北电倒地，摩托罗拉挣扎，诺基亚苟喘；

*如果说金融海啸是一次上层的爆仓，泛IT产业的大洗牌，就是釜底的抽薪。*

苹果/iPhone，谷歌/Android，亚马逊/云计算，维基/免费-协同，未来的新信息产业的面貌撕去朦胧，日益清晰。

可惜，它不足以完全成为社会新的支点。

＊＊＊＊＊＊＊＊

美国过去30年的信息产业为基底的“单极”霸权，吃的是谁的老底？

时光倒转80年，罗斯福新政

人人都知道罗斯福的经济“凯恩斯”式新政，却很少人知道罗斯福的科学技术“布什”式新政。两者互为表里，为美国长达70年的世界优势，立下汗马功劳。

1940年，范内瓦·布什[fn:jdwthkhl0018]面见罗斯福，组建“全国国防科学研究委员会”

[fn:jdwthkhl0018]Vannevar Bush，是美国科学支持政策转折的重要奠基人。他组织的机构先后支持了曼哈顿计划（原子物理研究）、贝尔实验室系统（大部分美国战后发明），他本人也是计算机方面的一位先驱，写有《我们可能这样思想》（As We May Think）一文，是互联网的雏形。

从此，美国摆脱了单纯依靠私人资本支持科学家的传统路径，国家科学基金、国防部、能源部[fn:jdwthkhl0019]研究计划，以及纳入AT&T系统下属的科研部门贝尔实验室[fn:jdwthkhl0020]，有条不紊，为美国生产、研制、储备核心科技。

[fn:jdwthkhl0019] 美国国家科学基金会（NSF）、国防部研究计划（DARPA）、能源部（DoE）为美国基础科研和开发的主要国家支持者。在近20年科研投入大削减的背景下，军费较为充盈的国防部科研开支成为一些美国大学（如麻省理工学院）单一的支持者。

[fn:jdwthkhl0020] 贝尔实验室为美国电话公司AT&T研究部门，但贝尔实验室的研究范围极其广泛，包括发明半导体（开创电子计算机行业）、激光（发明激光器）、通信卫星、宇宙大爆炸理论、UNIX操作软件（优于微软操作系统的一套操作系统Linux族群的始祖）、量子物理（崔琦、朱棣文等华人诺贝尔奖）、量子代数法……后，AT&T在改革中分拆，无力支持贝尔实验室，贝尔实验室在90年代末转身为“朗讯科技”，集中于通信业，并在竞争中迅速落败，被法国企业阿尔卡特兼并，在华为等竞争下勉强挣扎。贝尔实验室的历史充分体现了在“前人种树，后人乘凉”中前人的尴尬。

＊＊＊＊＊＊＊＊

*美国的问题在哪里？*

意识形态的迷雾，无限制的金融资本贪婪，证券行业的高薪，人才储备的激励扭曲。能源部、美国科学基金投入长期停滞，主持基础研究的私人公司[fn:jdwthkhl0021]纷纷转型。

[fn:jdwthkhl0021]美国著名的支持科研研发的私人公司，包括施乐、IBM、太阳微系统、贝尔实验室（朗讯），这些公司中的一大部分均不能幸免于衰落。

2008年，贝尔实验室落下挽联，奏响实质上的挽歌；

年底，奥巴马上台，朱棣文[fn:jdwthkhl0022]入阁

[fn:jdwthkhl0022]1997年诺贝尔物理学奖获得者，他被任命为能源部长表现了奥巴马对科技、环保的重视。

朱指出：华尔街，经常惩罚认真研发的企业！

＊＊＊＊＊＊＊＊

投资于科学研究，不一定有产出[fn:jdwthkhl0023]；不投资于科学研究，肯定没有产出。

[fn:jdwthkhl0023]因为有运气问题。日本人80年代以来的信息技术领域科研就是倒霉透顶的典型。

硅半导体行业渐渐步入晚期，美国举国丧失70年前的锐气，怎么办？

奥巴马急，朱棣文更急

权宜之计：盾牌，稻草，智能电网[fn:jdwthkhl0024]，对外合作

[fn:jdwthkhl0024] 说“智能电网是救命稻草”的原因是：智能电网的核心主要是一些简单芯片，属于较为轻松的IT应用领域。

2009年的中国股市，噱头不断，“进口货”不断

“啥？智能电网/智慧地球”

“这可是IBM说，通用电气造的！……”

“你要晓得！人家美国奥巴马点头的，好货”

削价甩卖的货，通过包装，希望还可以卖个好价钱。

撑上五年，赢得空间。

IBM“智慧地球”，奥巴马“智能电网”，你晓得了吧？[fn:jdwthkhl0025]

[fn:jdwthkhl0025]笔者的用意是，在科技战略后面，应该多思考，不要在浮躁中过度追捧。中国国家电网原来结合中国西部发电，东部用电的现实情况，发展特高压输电技术，命名为“坚强电网”，奥巴马上台后，智能电网概念流行，遂改名“坚强智能电网”。智能电网当然在提高用电效率上是一个好应用，但比较适应于分布式的较均匀的电力网络，中国可以向美国学习，但该技术实质并不特别高；相反，美国发展新能源发电，势必要将这些电长途输送，因此需要中国的特高压技术输入，这个技术的含金量则相对更大。中美科技交流，要注意价值对比。


+ III

中国有没有自己的范内瓦·布什？！

李国鼎，新竹科技园区创办者、台湾“工研院”电子所支持者，台湾经济、科技之父。

但，那是台湾。

*今天，中国需要的不只是一个人，而是一群人，一个群体，一个集团*

中国有华为，但华为的机遇和模式难以再次刻意复制；

中国有山寨，但山寨热衷逐利，一拥而上，不可贬低，也不可过分赞美。

……

2008年年中，《大国游戏·花开花落》提出全面发展高铁新交通、全面重视新能源的建议；

2008年11月，中国4万亿人民币经济刺激方案出台，高速铁路建设加快提上日程；

2009年初，节能减排和新能源频频亮相，然而，鱼目混珠，一拥而上；

2009年9月，中国国务院商讨新兴战略性产业，定调抢占若干关系长远发展领域的经济科技制高点。

……

如果美国能够在足够短的时间内调整心态，总结教训，重新激发创造的斗志，那么，它就不至于花落；

如果中国只是沉醉在“繁华盛世”的歌舞，虚幻膨胀的“财富”泡沫中，无视挑战，没有及时奠定坚实的创造能力，那么，它也难以轻易花开。

及时拨开迷雾，尽早确立布局。时不待我，局不可贻。

＊＊＊＊＊＊＊＊

谁家花开

谁家花落

还看后头
