# -*- org -*-

# Time-stamp: <2011-08-23 16:51:13 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话1

[2010-09-28 08:55:44]

闲话之一：收音机听来的信息

  

 

今天开车的时候，顺便听了听收音机。

一帮老美在争吵关于移民法案的问题。

*所谓美国的移民法案，就是关于如何把美国的非法移民转正的问题。*

美国有多少非法移民？具体数字没有多少人知道。最高的估计是接近2千万，大部分的估计是超过1200万。

就是说，有可能美国的非法移民超过美国总人口的5%。

最近美国搞了一个人口普查，根据人口普查的结果，就会重新规划美国众议院的位置分配。

虽然结果还没有完全出来，但是大概的方向已经清楚了。就是美国南部和西部各州，德克萨斯、亚利桑那、佛罗里达、乔治亚、内华达、南卡拉那、犹他和华盛顿州，因为人口增加要增加位置。

而美国的东北部和大湖附近的各州，伊利诺、衣阿华、马萨诸塞、密歇根、明尼苏达、新泽西、纽约、宾夕法尼亚和俄亥俄州，因为人口减少而减少位置。

唯一的例外是南部的路易斯安娜州，出现人口减少，大概是卡翠娜台风的后遗症，导致很多人搬家走了。

造成这个人口变化的主要原因，就是美国西语人口的数量大幅增加。这个不用看统计数据，只要看一下幼稚园的新入学的学生就知道了。

*就是白人少了，黑人也说了，亚裔多了，西裔多。。。非常多了。*

这些还说得是合法居住在美国的西裔人口，还不包括非法移民。在非法移民中间，大概60%的是来自于墨西哥，其他的大部分是来自中美洲和南美洲国家。

于是有听众打电话上来质问，大意是说，我们加州在2020年，就是你们说西班牙语人的天下了。你们就这么把人家一个地方的文化给颠覆了，还不征求我们的同意，云云。

于是有专家大声的回答，什么叫做我们颠覆了这个地方？俺的祖先在1750年就定居在这里了，那时候你们这帮说英文的还没听说过这个地方呢！是你们拿着枪过来占领了这个地方，还好意思说，我们颠覆！

另外一个女专家也大声的回答，有人说我们挂西班牙文的招牌，说西班牙语，这个从来就是这样。我们又不是什么移民！是你们这帮人把自己的国界移到南边去了（指的是美国从墨西哥手里抢走了加州），你不乐意见，自己把国界退回去拉到！

看来美国会越来越热闹。想着美国当年死命支持本拉登，今天被老本搞得一地鸡毛。而美国今天又死命支持中国的这个独、那个独，不知道这个因，会在20年之后变成什么果？

*美国这个国家，从历史上来讲，就是一直靠战争来维持的。*

*一部美国历史，可以大致说也是一部战争历史。*

1675年-1676年，还是英国人身份的美国人在东北地区和几个印第安部落开战。

1689年-1697年，和法国人开战。

1702年-1713年，和法国人开战。

1744年-1748年，和法国人的殖民地开战。

1756年-1763年，和法国人的殖民地加上印第安部落开战。

1759年-1761年，和印第安人彻罗基族开战。

1775年-1783年，和自己的兄弟和宗主国英国开战。

1798年-1800年，和法国开战。

1801年-1805年，和北非国家摩洛哥、阿尔及尔、突尼斯和特里波里开战。

1812年-1815年，和英国再干一场。

1815年，和北非国家又开战。

1813年-1814年，和印第安部落克里克族开战。

1836年，为兼并德克萨斯，和墨西哥开战。

1846年-1848年，和墨西哥开战。

*1861年-1865年，美国内战，南北开打。*

1898年，和西班牙开战。

1914年-1918年，参加第一次世界大战。

1939年-1945年，参加第二次世界大战。

1950年-1953年，参加朝鲜战争。

1960年-1975年，参加越南战争。

1961年，猪湾入侵古巴战争。

1983年，入侵格林纳达战争。

1989年，入侵巴拿马战争。

1990年-1991年，海湾战争。

1995年-1996年，干预波斯尼亚内战战争。

2001年，入侵阿富汗战争。

2003年，入侵伊拉克战争。

可以看得出来，1890年，是美国的转折点。就是从这个时候开始，美国的战争，从在内部打，就是说在自己的美洲大陆打仗，转变为到外面打。

*这个是在于靠了一场北方压倒南方的内战，然后30年的快速工业化，走向帝国主义而实现的。*

*而一旦外面打不动了，帝国要萎缩了，就会走回内部来打。所以美国未来20年的走向，会是很有意思的一个国际研究课题。*

*美国在这个阶段，主要面临的就是两大挑战。*

一个是来源于以中国为首，和其他国家为辅，比如说俄罗斯和欧盟等等，挑战美国独霸的国际次序。

一个是来源于美国自身的制度困境，伴随着内部的部落化，就是以西裔为代表的内部殖民趋势这个种族变化，以及以犹太裔为代表的富裕阶层，剥夺其他白人中产阶级财富的社会分化。

这种历史阶段，中国人早就经历过。那就是在中国人的强盛王朝汉朝覆灭之后，大概经历了4百年的文化融合，各种占据中原的胡人，全部被同化。

自从那之后，中国的各种分裂几乎不能持续50年。

而欧洲则是罗马帝国覆灭之后，再也没有达致统一。

现在美国就是处在中国东汉末年的时代，要看的是就是啥时候，董卓会进京。
