# -*- org -*-

# Time-stamp: <2011-08-24 09:42:20 Wednesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话17：失之东隅 收之桑榆

[2010-11-08 10:48:56]


有读者询问， *俺是怎么推论出美国需要5千亿美元热钱来冲击中国金融次序？*

其实俺并没有进行精确的量化分析，主要的思路是这样的：如果一定量的美元热钱进了中国，自然就需要相当量的人民币来吸纳这些美元。如果你进了5千亿美元，那么中国的央行就必须用3万多亿人民币来吸纳。如果考虑到美元在中国人民币发行中的底座作用，那么可以说要是中国的外汇储备，要增加25%，基本上可以判断，会造成央行基础货币投放增加相似的25%。

考虑到中国的经济增长，大概还是以10%为基准的一个增速，那么这样的货币投放，肯定造成的就是通货膨胀的压力。从中国过去的经济数据来看，这样的货币投放速度，造成的通货膨胀，可以从20%的恶性通胀，到8%的较高通胀。

估计其中的差距，在于蓄水池的建立。以前中国没有商品房市场和股票债券市场，因此水就会冲击实体经济，从而导致统计局的通货膨胀数字高踞。而后期因为蓄水池出来了，实体经济受到的刺激小了一点。

在中国目前的形势下，如果这个25%的货币投放量增加，就会刺激中国的通货膨胀率往8%走。如果你要避免这个局面出现，那么就要考虑让房地产市场来蓄水，这个就会刺激中国的房地产市场泡沫。

而现在中国政府考虑到的暗渡陈仓的法子，你要制止部分城市的房地产过快过高增长，你就泄洪， *让全国大部分城市的房地产，平稳和平均的增长，来防止这些大城市涨得过快。*

当然，你还有一个办法，就是挖一个很大很大的坑，然后就让大家往里面加水，然后有一天就可以填坑。

*在美国这个坑，名字叫做夏威夷和拉斯维加斯。*

*在中国，这个万人坑，叫做海南岛，aka （又名）国际旅游岛。*

你在这个岛上，每年来一次世界美女眼球比赛，来几次国际游艇展览，把它搞成一个销金锅，基本上就可以消灭不少资金流动性。

在当年朱内阁大学士的任下，海南大坑就坑了不少游资。俺一个开发商的朋友，就给清过一次钱袋，只剩下了一条裤衩。当时还真有人跳楼的，不是传闻。

其实在中国古代，这样的大坑也有过，那时候叫做 *扬州* 。于是大家就是腰缠十万两，运河去扬州。

除了海南岛可以用来坑钱，也可以开发上海附近的崇明岛。现在看到南黄海，可以开发离岸的大型人工岛屿，也可以开发出来用于坑钱。

*为啥这些离开海岸的岛屿，用来坑钱是上上之选？* 很简单，就是物产不丰富，样样东西要从大陆运送。那么每一种大陆上的便宜东西，比如说苹果和香蕉，都帮你翻几翻价钱，那么就可以把货币回笼了。

当然最后的一个办法，就是将你的汇率提高，那么就可以减轻压力了。比如说，如果人民币上涨50%，那么你消化5千亿美元，就不需要3万亿人民币，而只要1.5万亿了。而这个就是美国希望达到的目的。

*不过各种政策选择，在于一个国家政府对经济的控制程度如何。如果政府控制力越强，那么可以做的选择越有效。而对政府控制力不强，就是说一个经济私有化程度比较高的政府，那么采取汇率变化政策，也许是唯一的选择。*

这也是现在估计，巴西、印度、日本和韩国，在控制海外热钱上面，比中国难度要高一些。

那么为啥俺认为， *中国要帮助美国洗劫日本、韩国和印度？很简单，如果美国这两年走不出困局，那么美国核心利益集团，寻找全球性战争的手段，来解决内部问题，就是一个不可避免的选择。*

认为战争是一个好的选择，是美国左右两派的经济学家们，包括克鲁格曼等人，都赞成的。

但是选择中国来打仗，是一个很头疼的问题。因为中国个头太大，而且最近两次以中国为瞄准目标的朝鲜战争和越南战争，美国都是铩羽而归，没有讨到多少好处。

最要命的是，如果美国和中国直接对抗，就是重复第一次世界大战和第二次世界大战中，德国和英国的对抗。最后两强对抗的结果，是大家都悲剧了，反而让美国和苏联渔翁得利。

所以 *美国的战略家们，想的是中国和印度在印度洋上发生冲突，然后俺们美国人居中调停。*

而希拉里强力推荐的戏码，就是日本和中国在钓鱼岛和东海海域对抗，然后俺们美国人居中调停。

当然还有中国和东南亚几个国家在南海海域对抗，然后俺们美国人居中调停。

然后在阿富汗、中亚几个斯坦、巴基斯坦、缅甸等地方，俺们美国居中调战。

在这个过程中，你中国就必须送点好处过来，是不是？

那么中国既然也没有办法，可以阻止美国在周边搞事情，也不愿意白白地让美国人掠夺，最好的办法，就是给人家指出一个光明大道，让人家有地方去大吃一把。

因为 *在中国没有彻底解决经济转型问题，和内部统一市场问题之前，中国还不能和美国翻脸。*

*而且中国必须和三个国家搞好关系。这三个国家，一个是法国，一个是西班牙，一个是葡萄牙。*

和法国搞好关系，是因为大家在非洲的合作，还是比较重要。毕竟中国和法国在非洲的利益，有冲突的可能，也有合作的可能。如果冲突起来，估计大家都讨不了啥好处。恶性竞争的结果，一个是让非洲的权贵们在中法之争中左右逢源，一方面又让美国有可乘之机。

*所以如何在非洲和法国达成某种程度的势力划分协议，然后好好发展中国在非洲的影子势力和代理人，如何保证非洲普通民众可以得益于中国主导的经济发展，是中国在非洲站稳脚步的重中之重。*

*和西班牙搞好关系，主要是和西班牙合作，解决中国在南美洲的利益问题。*

*和葡萄牙搞好关系，主要是在巴西和安哥拉的阵地必须有得力的帮手。*
