# -*- org -*-

# Time-stamp: <2011-08-24 11:45:19 Wednesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话30：年年难过年年过

+ （上）

[2010-12-16 04:55:04]


前面谈到美国在朝鲜战争和越南战争中不同的境遇，有读者认为其实越南战争的时候，美军在泰国和菲律宾都有补给和后勤基地，似乎可以相当于美国在朝鲜战争中，日本的后勤基地的地位。

其实不然。 *日本之所以重要，不光是因为其工业制造基础，比菲律宾和泰国强，还因为主要是敌人对这个后勤基地，没有打击能力。*

美国在菲律宾的基地，对越南战争的支持相当有限，因为距离太远。而在泰国，则难以躲避地方的攻击。

而且东南亚这些地方，并不是理想的建立美国方式供给线的环境。反而是越南，这种依赖于游击战的军队更善于利用的地方。所以美国战争的一个主要应对，就是把战火烧到了老挝和柬埔寨，希望借此卡断胡志明小道。

从某种程度上来讲，当年日本皇军绕道攻击缅甸和印度，也是为了抄中国的后路，希望切断滇缅公路。

日军在正面战场上，最后一次努力，是希望从广西，打通贵州到重庆的通道，从而解决中国战场问题。但是这一努力，在 *贵州的独山* 被当地中国军民所挫败。

今天看朝鲜半岛形势，和以前很大的不同，就是美国的敌人一方，已经具备打击日本的能力。这个是当年朝鲜战争时候，不具备的军事能力。

*因此吓阻朝鲜战火的主要工具，就是一定要把战火烧到日本，从而击溃日本某些人士想依赖战争火中取栗的念头。*

*在台湾海峡也是一样，只要明确日本作为战争打击对象，就可以令日本人民产生避战的想法。*

*因此需要明确声明，如果美军以日本为基地，作为战争打击的基础，那么日本全国都会成为战区的一部分。*

*如果日本要避免这个情况出现，最好就不要趟这个浑水。而没有了日本的后勤支援，美国在东北亚根本没有战争的本钱。*

 

当然在中国的媒体上，应该有些退役将军啊，军事评论家等等，多搞一些朝鲜战争和台海战争的沙盘推演。在这些推演中间，一个非常突出的观点，就是因为美国驻军琉球群岛，就保证了这个地方，会变成战争废墟。

*那么琉球的人民，怎么才可以避免战火，不被那些和自己相关的大国搞到自己惨遭杀戮？很简单，就是把普天间基地赶出琉球就行了。*

*当然啦，如果琉球人民知道，要是他们可以独立的话，还可以享受和中国分享东海油气资源的好处。那么你就成了东亚的科威特了，然后保持中立，不牵扯到你美国、中国、日本、俄罗斯等等大国的争斗中间，自己关门过日子，岂不是很爽。*

这样好的文宣，中国竟然没有人去做，真是令人诧异啊。

+ (下)

[2010-12-18 15:56:49]

看来日本在折腾了一大轮之后，要加强军备，就是说要花大钱，向美国买武器了。上次有人说，日本和美国的联合军演，比美国和韩国的联合军演要大六倍，那么就看日本出的保护费要不要多六倍吧。

根据美国政府的推算，美韩贸易协定估计可以为美国带来100-110亿美元的收入，那么日本要出血，也要到600亿的水平吧。

*除了向美国买军火之外，如何出钱支付阿富汗战争，也是日本要出血的地方。现在欧洲盟友，个个大幅度削减财政开支，阿富汗的战争费用奇高，加上要收买人心花的建设费，以及训练和武装阿富汗政府军的支出，估计都是日本要出大头。*

而这一切只不过为日本争取到了日美安保条约对钓鱼岛的运用。搞得好像中国马上就要展开跳岛攻势一样，完全不知道 *只要东海不再进行谈判，日本在西南防线的投入就是得不偿失。*

*其实东亚出现今天的局面，对中国未尝不是一件好事。因为毕竟相对于东南亚，中国的经济具有先发优势，区域整合起来，对中国比较有利。*

而在东北亚，日本和南韩在产业技术上比中国仍然领先，是今后几年需要被中国赶超的经济体，现在搞什么整合，要大幅度开放中国市场，其实对中国自己的科技发展并没有好处。

连人家美国人，也知道要靠打压日本和南韩的汽车行业，来为自己的工业维稳，中国还不乘机， *利用东北亚局势的恶化，也对日本和韩国的工业挤兑一把，岂不是让美国人独美？*

*所以说中国也要有两手。军事上的一手，就是继续靠朝鲜来平衡美国的军事压力，忽悠和谈，大家谈拢也好，谈不拢也好，反正慢慢折腾就是了。*

*那么在经济上，就应该继续以政治和经济不能分离为基准，凡是要在军事上，和美国搞亚洲北约，想遏制中国的国家，比如日本和韩国这样的，就要把他们从中国经济发展的火车帮子上给摔出去。*

*当然不知道中国下一届的领导人们有没有这种魄力了。*

看了中国最近的经济数据，很明显食品价格是一个主要问题，如果剔除了食物价格上涨，通货膨胀率只是1.6%。 *因此通过行政手段和市场手段相结合，短期内压住食品上涨，应该还是可以做到。*

但是长期发展上面，如果 *把农业做到可持续发展* ，却是一个大问题。

至于大家最关注的房价问题，短期内应该是基本无解， *中央和地方的财税制度，没有明确之前，土地财政应该还是地方城市中，尤其是沿海城市的首选。*

比如说上海，搞完世界博览会，然后再搞上海迪斯尼乐园，就像香港那样，任何噱头，都是着眼于为房地产大(打)鸡血。

考虑到北京和上海，自住房比例到70%，广州达到90%，因此商品房的泡沫，是要靠一些 *硬需求* 来支撑。所以如果做到能够提供适当的经济适用房，来分流这些硬需，商品房徘徊，甚至小幅下降的机会还是比较大。

*斗而不破，应该是温水煮青蛙的好方法。* 反正一有涨的苗头，就收紧一些银根，就增加一些交易成本，慢慢拖过这两年，再做打算吧。
