# -*- org -*-

# Time-stamp: <2011-08-24 10:38:13 Wednesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话24：又是头大的时候了

[2010-11-29 14:39:26]


今天和美国政府牙齿印越来越深的维基泄密，第三次抛出美国的秘密文件。这一次，曝光的是美国外交系统的内部电报，把很多美国的疼脚，都给兜了出来。

这也算是对瑞典帮美国发逮捕令的回应吧。

在维基的这次泄密中，引人关注的就是朝鲜局势，果然和俺当时的猜测一模一样。

俺对美国朝鲜政策的看法，就是 *美国一直希望朝鲜能够内部崩溃，然后让朝鲜产生的难民冲击中国的东北和华北经济，同时就是由韩国来接管朝鲜，达到朝鲜半岛统一。*

这个之后，美国的军事基地，是不是要推到鸭绿江边，就看你中国开出的好处是什么了。

而考虑到朝鲜这样的体制，领导人的更替是一个关键点。因此在一金到二金的时候，就是1992年-1995年，美国采取了军事高压的动作。因此这次从二金到三金，也是运用同样政策的绝好时机。

当然朝鲜相对于上一次的危机，有了原子弹这个大杀器，是一利。但是三金相比于二金，在交接时期年纪太轻，资历太浅，都是一弊。

因此美国对朝鲜的军事压力，会在随后的一段时间里，继续施行。

至于中国在这个冲突的角色，就是比较清晰。 *美国是企图以东亚地缘紧张的形式，落实美国、日本和韩国的军事同盟关系，然后在亚洲的任何事物之中，都要插一杆子进来。*

而中国的应对，其实也很简单。就是日本和韩国，必须在亚洲事务上采取和中国政治、外交和经济的同一步伐。如果你想来个政经分离，必然要接受经济上的后果。

当然中国能不能够采取这个政策，问题不是在外部，而是在自己的内部。因为路线对了头，能不能落实到实处，主要看你的干部队伍如何。

要是靠中国以前的外交队伍，见了美国老大，腿肚子就开始发软，忍不住想跪下去的一帮人马，确实是有一定难度。

不过向好处想一下，这些人作为出去忽悠别人的疑兵，也不是一点用处都没有。毕竟如果大家关系闹得僵了一点，出去几个前部长等等，和人家套一点近乎回来，未免不是一个权宜之计。

反正俺们现在既没有能力，也没有手段，更没有人才，扮演所谓负责人的国际大国，不如把姿态放低一点，好好经营自己的经济转型为妙。

因此戴老兄这个俺的同乡，跑到汉城去和人家谈什么战略伙伴关系，也就是扯一下而已。上次老哥和希拉里在海南的交流，大概也是各说各话而已，也没有防止人家落实钓鱼岛的日美安保云云。

倒是中国总是有老天帮忙， *维基泄密这一次的出手，基本上会杀得希拉里丢盔卸甲，溃不成军。* 很简单，老美自己看不住家里的两亩三分地，把盟友的私房话，来个全球播放。

中国要是想好好利用这个机会，就把美国在朝鲜问题上的暗盘操作，认认真真地清理一次，好好地在东亚文宣一下，让大家明白， *到底是朝鲜，还是美国，是东亚形势紧张的真正推手。*

考虑到胡锦涛主席明年可能访问美国，那么又是一个好的文宣机会。要好好地迎合美国人民在中期选举中表现出来的意愿，就是希望美国政府能够正视自己的财政赤字问题，做一个对美国人民和全球人民负责任的政府，不要狂印钞票，用通货膨胀的方法来盘剥美国普通民众。

*以前看中国的领袖人物出访，老是处于被动，不断为中国立场辩解，似乎忙于解释人家误会的姿态。俺倒是觉得，中国必须改变姿态，开始玩一下人家西方人，很顺手的指责游戏了。*

人家要是说人民币汇率问题，就可以回答说，根据高盛的经济学家的意见，人民币在2005年是高估，但是在升值20%以后，就比较合乎市场真正价值了。

对人民币汇率，和贸易顺差问题，可以举例说明，从2005年-2007年的人民币升值之后，美国的贸易赤字没有缩小，反而大幅上升。这个说明汇率不是问题嘛，真正的问题，是美国联储局的货币宽松政策。就向现在一样，是你美联储乱来吗。

也可以提议说，俺们中国的财政平衡搞得不错，可以为美国提供学习的榜样嘛。比如说，一个国家的财政平衡是需要有正常的税收的。你政府收入不够，还要为美国最富的富人们减税，这就不太好吧，不和谐嘛。

那么要搞财政平衡，你是不是应该减少支出？比如说，美国军费比全世界其他国家的所有军费加起来还要多，是不是不太正常？学一下俺们中国，军费少一些嘛。还有，就引用一下中国的《司马法》的名言，国虽大，好战必亡。美国人民是热爱和平的，你还是要遵循民意，不要到处打仗是不是？

所以说， *俺们中国可以为美国开方子，来解决经济问题。*

第一，  要搞建设，不要搞破坏。美国的钱要花在搞好自己的基础建设上，不能让那些破烂的大桥、水坝等等，随时出状况。拿着这些钱，去打仗，还不如在自己国家搞建设，是不是？而且刚刚泄露的消息，就是你美国的钱到了阿富汗打仗，转手就被人家阿富汗的贪官给摸到了欧洲，是吧？

第二，  要重视民生，不要重视有钱大佬。俺们中国的经济刺激计划，就是保障民生，为劳工阶层而定做。你美国的刺激计划，发钱给华尔街的败家子发奖金，那哪能搞得好？

第三，  穷人要减税，富人要加税嘛。你有钱人这么多年来，钱越来越多，还要减税，那政府还如何运作呢?

其实，把这几条，好好地在美国开记者招待会宣传一下，算是中国对美国的建议，估计还是比较受美国老百姓欢迎，这才是负责任的大国之道。

*中国的外交，不重视与人家民众的交流，不重视争取民心，只是在一些政界人物，比如基辛格等等，或者是一些华尔街和其他企业界精英圈子里面应酬，简直就是一种白痴的做法 *
