# -*- org -*-

# Time-stamp: <2011-08-24 11:23:35 Wednesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话28： 军人变穷人，穷人变贼人

[2010-12-09 15:51:23]

先说一下现在闹得沸沸腾腾的维基泄密事件。

在阿富汗的美国国防部长盖茨很高兴，因为维基泄密的头头阿桑奇终于在英国落网了。

原来在人家瑞典，男女行房不用套套，是要享受红色通缉令，被国际刑警跨国追杀的。

尤其是和你那个那个的美女，还帮美国中情局的外围组织打工。

这个红色通缉令，叫做EAW，称为欧洲通缉令，是911事件之后，欧洲人为了抓国际恐怖分子而设立的。

不过在这个发生之前，其他的“非政府组织”就开始为美国政府服务了。亚马逊中断了对维基泄密的主机服务，PayPal掐断了付款服务，然后 *瑞士银行，这个为全世界黑帮洗钱和为世界各国贪官提供服务的银行* ，把阿桑奇的账户给封了，MasterCard和Visa也封了人家的信用卡。

更牛的是，美国司法部在考虑如何起诉阿桑奇。美国国土安全部的提议，是把维基泄密定义为恐怖组织，那么按照美国法律，谁和恐怖组织有任何来往，都可以把你给扔进牢里去了。

有人怀疑维基泄密是美国政府在玩双簧，其实不然。这种泄密，不排除是美国内部的各派势力内斗，比如说希拉里要抢人家副总统的位置等等，但是泄密本身，对美国外交政策的影响是相当巨大，会导致美国外交系统在海外的很多间谍关系曝光。

因此美国政府的下一个步骤，肯定就是把大部分牵扯进去的外交官等等，召回国然后重新分配工作，因为这些外交官们已经很难再和人家国家的人员正常工作。

估计现在没有一个国家的官员，敢推心置腹地和美国人谈心里话了。尤其是那些国家的中下层官员，发布的某些言论，就是被自己国家清洗掉都不出奇。

最有意思的是，在抓了阿桑奇的同一天，美国政府宣布明年要在美国召开“国际言论自由日”。美国政府发布声明，说是对有些政府制止信息自由流通、不让人说话表示严重关切。而且说是美国政府坚决支持言论自由。

英国的报纸把这个和阿桑奇被捕的事，放在了一起，评论道：“好久没有见过这么不要脸的事情了。”

看来阿桑奇是找错人了。要是他针对中国和俄罗斯等等，说不定有北欧的大奖金拿了，来个名利双收。结果找上了美国，看来只好被恐怖分子了。

上次俺谈到美国经济的转型，就是美国经济需要从依赖消费的发展模式，转型到加大生产的比重。因此在私人资本替代政府资本的时候，是希望主要是企业投资，就是说扩大再生产，而不是消费者出钱，继续消费这样的局面。

从财政平衡来讲，如果到了美国今天这个地步，其实最好的法子，就是自己咬紧牙关，过几年苦日子，靠自己解决自己的问题。

而不是赖到别人头上，希望可以靠大棒政策，空手套几只白狼回来。

因此解决财政失衡的最佳办法，就是要开源节流。前些年大家日子过得太红火了，有几多风流，就有几多折堕，反正出来混总是要还的。当然很多美国人，会抗议说，前些年只是你华尔街那帮丫风流，俺们一直就折堕，可是事实是普通美国人是全部跟着风了一把。

所以要解决问题，就是大家都要承担。富人要加税，穷人要减福利。

这个估计难度比较大。那么就是退而求其次。

你不要加税，但是要减福利。这个就是共和党人自圆其说的主张。或者你不要减福利，但是要加税。这个就是民主党人自圆其说的主张。

以前大家博弈和妥协的结果，就是同时减税和增加福利，双方皆大欢喜，问题就是财政赤字，最后到了账面平衡不了的地步。

要增加税收，难度不小。因为真正的有钱人，是没有多少收入的。或者说，人家有一大堆办法，可以把钱从你的手指缝里面，漏过去而不被你抓住。

*因此税收的主要来源，就是两个地方。*

一个是工薪阶层，一个是企业。工薪阶层，现在受到的打击最大，带来的税收基数的大面积缩减。毕竟你不见了几百万只生金蛋的鸡。以现在9.8%的U3失业率，和17%的U6失业率，肯定税收会大受影响。

而美国的企业的税务负担，在发达国家之中，排在了日本之后的第二位。导致的结果，就是以前只是美国的大企业和跨国公司往外面跑，现在很多二线的中小企业，都开始向海外流失。

要削减支出，恐怕比增加税收还要难。

*美国政府支出最大的是三大块，一个是国防军费，一个是社会安全保障，一个是公共医疗。*

削减国防军费，就是要把拿枪的军人们变成穷人。看过俺以前博文的读者，大概都知道大萧条期间的美军退伍军人们的大动作。而今天美国的军费中间，不光养着军火商和一般的军人，还包括退伍的军人，比如说黑水公司那样的私人军队。

美国在伊拉克战争的高峰期，大概有10来万军队，而和他们一起作战的黑水军就高达7万人。相比美军平均工资是3万多，这些私人军人的工资就是35万多。

黑水军自己就有大概10万大军，还不包扩其他的私人军队。和美军不同，这些私人军队大部分是美军特种部队退役人员组成，因此战斗力相当强大。断了他们的口粮，后果很严重。

因此你要裁减国防费用，就会把军人变成穷人。然后裁减其他的福利，就把穷人变成了贼人。
