# -*- org -*-

# Time-stamp: <2011-08-24 11:31:56 Wednesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话29：家家有本难念的经

+ (上)

[2010-12-12 02:58:10]


因为最近一段时间特别忙，工作上一大堆事情，还有要把以前写的东西修订一下，所以决定把闲话的一个章节，分成几个段落，这样可以更新频繁一点。

上次说到美国的政治博弈，看一看刚刚通过的减税延长法案，就可以看出问题在哪里。

本来布什政府时期的减税法案到期了，民主党人希望可以保持对中产阶级的建设，但是对年收入25万美元以上的家庭，就不再延期。这个事实上，就是要对这些富人加税。

但是挟持美国中期选举气势的共和党人认为，经济危机的时候，不应该给任何阶层加税，尤其是25万美元以上收入的不少是中小企业。你还指望这些人扩大投资，增加就业机会呢。

共和党的策略，就是你不和俺妥协，俺就让你所有的法案，包括和俄罗斯的导弹协议全部熄火。

这些法案中的其中一条，就是要给用完失业救助金的失业人士们，继续延长已经延长N次贷救济。

结果奥巴马政府只好妥协，那么结果就是要继续延长对富人减税，作为回报，共和党人同意延长穷人救助。

*博弈的结果，就是不给富人加速，和不给穷人减福利。*

当然这个是从现在这一刻的时间点上来看。如果回到这之前出现这些政策的时候，那就是给富人减税，同时给穷人增加福利。

*然后就是同样的问题，钱从何而来？*

大家当然就很清楚，那就是去打仗。因为很简单，如果你把军人变成穷人，然后把穷人变成贼人，让他们在自己国内里面去打去抢，还不如派到外面去打去抢。

因此有读者开始担忧会不会美国找中国的负气，来打一仗。

美国左右两派的经济学家们，在这一点上是有共识，那就是打仗是可以解决经济困境。

但是熟悉世界历史的战略家们，却有不同观点。

那就是上个世纪的历史。

在英国率先实现工业革命，成为世界霸权之后，许多后进的国家，立即跟进。

在欧洲，是俾斯麦促成的德意志统一，以及俄罗斯的彼特大帝改革。

在亚洲，是日本的明治维新和中国的洋务运动。

在美洲，是美国的南北战争，和西部扫荡，通过工业主导的北方资本，摧毁了南部的奴隶农庄经济和西部的印第安部落游牧业，而达到工业革命的目标。

这个时候，就是霸权争霸战，在各个大洲进行。日本通过打败清朝，在亚洲大陆和东南亚扩张，然后开始挑战英国、法国和美国在这里的殖民地利益。

美国因为早已经打垮了墨西哥，因此地区争霸，是靠打败西班牙，把加勒比海变成了自己的内海。

而最激烈的是在欧洲，先是靠普法战争打败法国而崛起的德国，就开始和英国对抗。

这个基调，导致了第一次世界大战和第二次世界大战。结果就是德国和英国同时变成了废墟。得益者是在边缘的美国和苏联，一举崛起为世界超级强国。

因此对美国战略家和历史学家来讲，如果美国找中国开战，那就是重复英国和德国的对抗。即使能胜，也是惨胜。

而因此得益的人，肯定不是美国人，那是铁板钉钉的事情。

而且美国在中国地缘利益进行的两次战争，一次在朝鲜，一次在越南，都没有占便宜。其实很多人在这两次战争中，没有明白一个道理。

为啥美国在越南，被逼得全身而退，但是在朝鲜，却还可以守住半壁河山？

+ (下)
  
[2010-12-13 14:13:31]

前面说到俄罗斯的改革，写错了，不是彼特大帝的改革，而是亚历山大二世的改革。

另外回头看了关于维基泄密那一段，发现写漏了一句话。那就是因为希拉里对美国副总统的位置虎视铮铮，希望在2012年美国总统选举中，一脚把现任副总统拜登给踢掉，然后自己做一个钱尼第二那样的实权副总统，从而把奥巴马当作傀儡。

因此不排除亲拜登的势力，利用这次维基泄密，狠狠打击希拉里。其实大家都看得出来，这次泄密，被打脸最重的就是希拉里。

前些日子泄密的关于希拉里对联合国的各位大员们搞监视，已经让她得罪了不少圈中人士。最近又把她嘲弄印度的话，给披露出来，已经让希拉里在国际外交界里面，很难混下去。

因此这个打击，有可能直接断送掉希拉里问鼎白宫的曲线道路。

现在就回到美国为啥在朝鲜可以守住半壁江山的问题，关键因素是在于日本。

战争打的是补给线，如果你的补给线太长，那么问题就比较大。

因此如果朝鲜战争发生，你从北向南打的话，如果你不是把日本也给同时拿下了的话，你想守住南边，那是相当困难。

当年朝鲜的军队，已经打到了釜山，就是被人抄了后路，在仁川给人打了一个反击。

其实就算当年金日成，可以拿下釜山，人家南韩军队是可以退到日本，随时可以组织反击。

相比较越南，美国是没有这么近的一个后援基地，无法对南越有效的驰援。

*所以朝鲜战争的关键，并不在于南韩和朝鲜，而是在于中国和日本。*

当年清朝没有办法阻止日本在朝鲜的军事冒险，就让人家打进了东北，然后那里变成了俄罗斯和日本的逐鹿之地。

如果上一次的朝鲜战争，中国不出兵的话，或者是出兵失利的话，人家也是一样的会杀进东北，然后就又来一场苏联和美国的争霸战。

中国当时可以打回三八线，但是越往南打，补给线就越困难。打到三六线，就容易被人家抄后路了。

*所以当初守住三八线，是可以实现的战略目标。而正是这个战略目标的成功，导致苏联势力最后不得不从东北彻底退出，从而中国真正的把东北拿了回来。*

*因此如果新的朝鲜战争开打，其实主战场并不在朝鲜半岛，而是在日本。因为很简单，东京不打烂，北京就会被打烂。*

*如果战火不燃到中国和日本的话，那么朝鲜半岛打出来的结果，不会比上次有任何变化，就是大家还是以三八线对抗。*

*这个道理，用在台湾，那就是台湾海峡如果开战，打的关键不是台湾岛，而是冲绳岛。*

*所以结论就是，如果新朝鲜战争开战，不光是汉城和平壤要变成废墟，而且东京也是一样。*
