# -*- org -*-

# Time-stamp: <2011-08-24 08:51:06 Wednesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话12：最危险的时候，就要开打贸易战

[2010-10-26 15:33:43]


当时法国人曾经对美国发动的贸易战争做出了沙盘推演。

首先是美国将对纺织品进口进行限制，然后欧洲就在美国大豆进口上进行报复。然后美国国会对欧洲的“无耻”行为发怒，反报复，开始限制欧洲鞋子和地毯类产品进口。然后欧洲再次反报复，对美国飞机和电器的进口制裁。

最后美国开始攻击欧洲的玻璃和钢铁业，作为贸易战的最后一招，欧洲就限制美国跨国公司，在欧洲的分公司的经济行动。

其实今天看回去，美国在那个时候，实际上一直是贸易顺差。和今天利用贸易逆差为借口，整天想和其他国家开贸易战不同，那个时候美国的主要问题是 *资金账户不平衡* 。

造成这个原因，是两个因素。一个就是美国私人企业，尤其是跨国公司，在海外其他国家，一路攻城拔寨，占领其他国家的主要工业，导致美国资金流出现负数。另一个就是美国在打越南战争，造成很大的财政赤字。

美国的想法，就是压迫其他国家一是开放更大的市场给美国产品，一个是提高货币汇率，来分担美国因为越战而支付的成本。

说白了，美国就是希望转嫁越南战争的成本给其他的欧洲盟友。

*而美国希望做到的就是，靠印钱来解决问题。*

就是说，美国因为越战花了N多亿美元，然后就要印出N多亿美元来填空。而这个N多亿印出来的美元，就要靠美国的盟友们，来消化这些多出来的绿条。

那时候美国的制造业还没有空心化，所以 *需要欧洲人更多地消化美国的产品来回收这些绿条* 。要做到这一点，就必须让欧洲人提高汇率水平，这样就可以负担美国越战的成本。

当然美国自己的国内目标，就是希望这样可以解决美国失业率接近6%的问题（送青年上前线，使实际失业率隐藏起来了），但至于这样会不会导致欧洲盟友国家的失业率上升，那就不是美国大爷需要关心的事情了。

本来在布雷顿森林协定下，美元作为西方国际贸易体系的实际货币，你一直就要解决美元过度投放，而面对的回收问题。按照本来协定，欧洲盟国的中央银行，拿了过量的美元之后，回收的方法，就是可以到美联储，用事先确定的35美元一盎司的价格来兑换。

但是因为美国货币投放，就是印钱太多，引发了 *黄金危机* 。在这种情况下，美国开始主张大家把多余的美元自己清理掉。

怎么清理，就是依靠美元的贬值，来冲销大家的多余美元。这种做法，美其名曰“解决国际经济的不平衡”。其实就是要求大家分摊美国的白吃白喝。美国提出的理由就是，俺是为你们大家守地头的，因此理所当然，你们得出保护费，就是要认购俺美国批发出来的全球安保股票，你们要在里面选购。

这个理由，如果用在美国防范苏联的华沙条约组织国家，对欧洲的威胁，还是可以说得通。但是用在越战，这个在美国国内和欧洲都受到大家杯葛的战争，就有点自说自话了。

因此美国的要求，得不到大家的响应，就只好诉诸于贸易和金融战了。

在这个贸易和金融战兴起之前，美国已经面临黄金不足的困境。开设一个大金池塘，来舒困的方法，也试过而失败了。结果就是美国向德国威胁，你要是学法国人，拿多余美元来换黄金，俺们在西德驻扎的美军，就会撤走，然后通知一下苏联找点事做。

为了帮助美国人度过难关，西德在1969年底卖了5亿美元价值的黄金给美国，来帮助其稳定金融次序，而且法国也在1968年五月停止了每月兑换黄金的行动。

但是现在既然美国人要开打贸易战了， *德国和法国开始暗示，他们会以大幅度兑换黄金来报复美国的行动。*

这个当时的大杀器，大概和今天 *中国暗示会以抛售美国国债来威胁美国* ，不要开打贸易战，是差不多的行为。如果当时这个行动付诸实施，那么国际金融体系就会崩溃，就说不好，会不会最后靠军事力量来解决问题了。

当时和美国的军事力量比较，欧洲大概可以忽略不计，日本就是零蛋。只不过美国在朝鲜战场上遭受重大挫折，然后在越战上，又焦头烂额，还有一个虎视眈眈的苏联在旁边，因此估计美国政府判断，欧洲人只是瞎嚷嚷而已。

而且这种对帝国权威的挑战，是可忍，孰不可忍。于是在德法的威胁下，经过5个星期的听证会，美国国会筹款委员会以17票对7票的结果，于1970年8月13号，通过了限制欧洲和日本等国纺织品输入美国的迈尔斯法案。

然后一个月后的11月19号，美国国会众院以215票对165票的结果，通过法案，向欧洲和日本正式宣战。

比较一下这次对付中国的贸易法案，美国国会众院的投票结果，是348票对79票。

所以说如果美国当年对付欧洲的情况，说是大军压境的话，这一次对中国，算是武装到了牙齿了。

为啥这一次美国的嗓门特别大？是因为有两位主要的吹鼓手，弄出来了两个耸人听闻的大数字。

一个就是经济炸药奖得主克鲁格曼，给了一个数据，说是中国的外汇政策，导致美国每年GDP增长损失1.4%。考虑到大家对美国GDP今年的增长预期，就是2-3%之间，这个让美国人民相信，俺们美国一半的GDP增长，被你该死的中国给吃掉了。

而且大家都知道，经济发展意味着更多的就业机会。于是另一个砖家伯格斯坦说，只有人民币按照美国的要求升值，会为美国创造出50万个就业机会。这个伯格斯坦任职的彼得森研究所，是对人民币劈砖最狠的地方。

中国政府有些人，错误的以为，这一次美国国会的动作，只是为了中期选举做秀，为自己争取选票。

但是如果看一下美国的经济，你就知道，美国已经到了非常非常危险的局面。
