# -*- org -*-

# Time-stamp: <2011-08-24 10:25:24 Wednesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话22：看谁忍不住先眨眼

[2010-11-27 09:21:39]

有读者问，美国联储局这么印钱， *难道美国就没有通货膨胀吗？*

如果你要是问，美国的物价有没有涨，那是有涨。但是你要是问， *通货膨胀，就是CPI数据，那么就是没有。*

美国的通胀，是要看 *Core CPI* ，就是 *核心物价指数* 。这个指数不包括能源和食品。

其实美国的食品中，主要消耗的奶制品是涨价不少。其他的肉类、鸡鸭类、蛋类和鱼类都涨了，只是美国人比较少吃的蔬菜和水果，就跌了，从而拉低了食品指数。

在美国的能源中，主要消耗的汽油涨得挺厉害，但是现在冬天取暖的天然气没有涨，因此也把能源涨幅给拉下去了。

当然大家都知道，天然气是冬天用，但是汽油是全年用。

所以要是看单项的话，燃油涨得最厉害，现在是14.5%，其次是汽油，涨了9.5%。

另外一项关联的就是因为银行的信用紧了，所以大家主要去买旧车，导致了这个类别涨了8.6%。

其他的就是医疗费用涨了，教育费用涨了，但是不少领域是没有涨，比如说旅馆和房租等，都因为房地产萧条而下跌。各种衣物等等进口用品，现在的价钱，还是今天上半年的进价，所以比较低。

但是估计如果产品制造国如中国等国家的通胀压力，不得不将其转移输出到美国，再加上美元的实际贬值，那么美国明年的物价如何，就要拭目以待了。

这个又要取决于美国现在开始的冬季销售，从感恩节到圣诞节这个重要阶段，销售状况如何。

如果这个季节销售情况比较好，那么这些百货公司，完全可以选择明年上半年来一个冬眠，不指望可以赚什么钱，因此尽量内部消化涨上来的进口价。但是这个可以保住物价不上涨，可是销售业裁员，那就是另一个结果了。

因此从大的层面来讲，因为美国自身是农业生产大国，所以食品上面的涨幅，应该不是在新鲜食品上面（虽然储存和运输费用会增加），而更多在加工食品上面，而且美国人消费比例中，食品成分很小，大概7%左右，和中国的45%的比重，当然差别比较大。

其实美国主要的问题，还是能源。从这个角度判断，美国的QE2会对全世界其他国家的影响比较大，但是对美国自身的影响，就不会有太大的变化。

*美国经济的最大问题，就是要靠消费驱动。而因为驱动消费的来源，并不是中产阶级和工薪阶级的工资收入增长，还是来源于信贷，就是借钱。*

因此靠举债推动的全民消费，总是会到一个债务继续往上滚，就很难滚下去的局面。这个时候，面临的就是信贷紧缩，而把这个债务给消化掉。只要这些债务一天不回复到合理的水平，美国的消费驱动能力，就没有带动经济的正常发展。

所以奥巴马政府，提出了要依靠减少消费，但就增加制造业出口的路子，大方向是正确的。

这也是为啥美国政府拼命想美元贬值，就是为了推动这个过程。美元贬了，大家就少买进口货，然后你的出口货，就竞争力增强了。

而中国在这个美国经济转型的过程中，其实不是美国的主要对手。因为中国的产品升级，确实在一些产业上面，对美国造成了一些威胁，但是 *美国的主要对手，还是德国和日本。*

*中国对美国的竞争威胁，一个是在通信设备业。这个主要表现，就是中国的华为，挑战美国的思科。*

你只要看一下最近美国政府对华为的打压行动，在争取商业合同上，和华为并购上，都不断由美国的各个部门，包括国防部出面，以国家安全名义，进行打压，来保住思科的竞争地位。

*另一个领域，就是在新能源产业，中国已经领先于美国，而这个导致了美国商业部对中国企业的调查。*

前一阵子听到了希拉里的一个访谈。其中希拉里对中国政府非常痛恨，主要是中国在哥本哈根会议上，表现出对新能源产业的保守态度，似乎导致了美国政府的误判。

而中国私底下在新能源产业上面的大幅度动作，则引发了美国政府的高度警惕。因为鉴于美国的内部利益集团的阻止，美国政府知道其新能源政策，基本上是没有任何机会，可以推动。这个从美国传统能源集团，停止了派出国会游说集团的行动，可以知道是不会再发生。

而美国风险投资在各行各业的回报率，以新能源企业为最差，大概是负30%。就是说，以现有条件，在美国投资新能源企业，你是亏30%的。如果没有国家力量的支持，大概私人资本，不会再涉足这个行业。

那么要是 *中国在确立了新能源的领先地位之后，转头和欧洲人合作，从而在新兴工业上，对美国逼宫，那么美国的工业领先地位，就被撼动了。*

这次看一下，美国政府大力炒作国营企业通用汽车的上市，也要看明白这次的成功翻盘，是与美国政府痛扁日本的丰田汽车，大获全胜分不开的。但这之后，通用可不可以在与丰田的竞争中占优，还要看美国政府未来对丰田的态度而定。

那么现在 *德国对付美国的“行政”竞争的态度* ，采取的方法，就是自己摆出架势，出来吓唬要引爆南欧小国的架势。只要在这个方面，德国和中国达成默契，欧洲的局势就处于可控的状态。

毕竟中国和德国，是世界上的主要产品制造大国，也是袋子里钱比较多的少有国家。因此大家靠吓唬游资的方法，倒是可以防止欧元对美元增长太快。
