# -*- org -*-

# Time-stamp: <2011-08-24 10:30:49 Wednesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话23：搬起石头砸自己的脚

[2010-11-28 09:35:58]


俺以为自从俺的《黄海和南海》系列写完了之后，大家就彻底明白了朝鲜半岛和黄海会发生的事情。结果还是有一些读者，询问关于现在朝鲜半岛的问题，只好叹息一声。

朝鲜半岛发生了什么事了吗？为啥俺没看见呢？呵呵。

先说一下美国的 *黑色星期五* 。大概大家不知道为啥叫做黑色星期五。因为 *对企业来说，如果你是亏损的话，那么就是你的利润是赤字，是红色的。如果你赚了钱的话，利润是黑字，是黑色的。*

所以黑色星期五，就是说如果这一天干好了，那么你一年下来的赤字经营，是有希望变成黑字，可以转亏为盈。

因此全美国的经济学家，都看着黑色星期五的数字如何。

每个黑色星期五都有不少故事。但是以前的故事，大部分是因为大家排队排了几天，然后一冲进去的时候，就踩死了人。今年的故事，有一点不同。

先是三个佛罗里达的黑人女人，星期三开始排队，排了个第一名，总算开心的买到了心仪的电子用品。然后把东西放到了后车厢，到另一家商店扫货。回来之后，发现车窗挨了砖头，所有的战利品被人一扫而空。

想到前一阵子的万圣节，小孩子们出去挨家挨户要糖吃。结果半途回来，被成人拿着枪打劫，把小孩子们手上的糖果全部抢走了。

另外就是圣路易斯的十来个人，为了抢货，把车子停在了其他商家的门口。结果人家商家不服气，一个电话，拖车公司就把车给拖了。买完东西回来的人，发现车子不见了，给人拖了。要拿回车，需要交335美元。

怎么办？只好回去退货，把退回来的钱，要付罚金。

今年俺也出去扫了一些货。主要就是棉织品，和明年会用到一些衣物。反正明年再涨价，也不关俺的事了。

不过扫完货之后的第二天，俺出去吃午饭，然后就拿了一些旧衣物去循环再造中心捐献，看到了两个事情。

先是在吃饭的饭店的停车场，冒着大雨，有一个中年妇女走过来，说如何如何，有亲人住院，汽车没油了，等等，然后要钱。而在循环再造中心，有一个青年妇女，带着两个小孩，爬到人家丢弃旧衣架的大铁箱里，去捡破烂。

以前也有这样的事情发生。但是这次有些不同。以前见到的要钱妇女，通常是黑人，但是这一次，要钱和捡破烂的妇女，都是白人。

前一阵子，大家大概还记得一件事情，就是中国总理温家宝访问欧洲的时候，突然飞去了德国，在一个很保密的地方，和德国总理梅克尔有一个密谈。现在看来谈的是什么，大概大家都明白了，就是 *如何针对美联储发动的货币战争。*

有读者认为，欧洲以爱尔兰、葡萄牙和西班牙作为赌注，来阻击游资，弄不好会弄假成真，真给搞出一个危机出来。

其实不然，如果欧洲自己的金融界和银行业，与政府沟通好了，完全可以把这个只是作为市场炒作，只是防止美元大贬就行了。因为本来欧洲的资本回报率，就不比美国好多少。

那么往亚洲跑的热钱，就要有些别的办法了。从这个角度来看，朝鲜半岛的危机升级，甚至打一场小规模的有限战争，未尝不是一个好的解决方法。

*而且这正是美国和以色列在中东屡次用的法子。*

而这次美国航空母舰进入黄海，俺觉得中国军队方面不需要太大的反应。上一次大家喊打喊杀，是因为那个时候的外交战略大方向上不对头，因此反应强烈，是需要的。

现在大方向上扭转了过来，那么在应对方面，就可以悠着一点了。

你美国的战略，不是说要美国军力才可以搞定东北亚地区吗？那好吧，就让你美国来搞定吧。不过，如果朝鲜不服气，你又搞不定的话，请不要来烦我，好不好？

而且美军在东亚，又这样又那样，花大笔钱，还不是得靠韩国和日本，向美国下大军火订单来解决？

也许将来中国可以仿效美国在台湾搞的军事均衡一套，说什么中国军力增长，为了保持台湾海峡实力平衡，美国必须卖什么什么给台湾云云。那么中国就可以说，因为韩国军力增长，中国必须保持朝鲜半岛实力平衡，也要卖些歼10过去，等等。

至于中国自己内部的问题，就是一句话， *压住食品的价格* 。解决这一个问题，其他的都不是太大问题。

俺在2006年的时候，因为当时想了解继任的伯南克有什么东东，所以看过了他和几个人合写的一本书，叫做《通胀目标（Inflation Targeting）》，因此对他的思路比较明白。

说到底，伯南克的想法，就是想通过大印钞票，将美国的核心价格指数，推高到2%的水平。

但是他的这一个想法，会受到来自于美国未来国会的重大挑战。

如果不出意外的话，共和党的Ron Paul有望出任美国国会的货币委员会主席。他的主要货币观点，第一条就是取消美国联储局。第二条就是放弃美元的法币地位，回到美元金本位。

虽然这两条都不可能实现，但是可以考虑到在这个阻击下，美国联储局实行QE3的机率将会比较小。甚至连QE2，可不可按计划全部投放，都会成为问题。

而因为市场对QE2的信心不足，导致的结果，就是美国的10年期国债利率反而在QE2出来之后，会向高处走。而这种预期，就会导致QE2不可能成功，从而反证了伯南克的政策失败。
