# -*- org -*-

# Time-stamp: <2011-08-24 21:26:42 Wednesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话37：借船出海和离岸平衡

[2010-12-29 16:29:53]


在前面的一篇闲话里面，俺大致谈到了朝鲜军队面临的转型问题，提到了当年中国的军队经商。因为用了新时代下的南泥湾一词，结果引发了一些读者的不满。

大概觉得军队经商不是一件好事，是无法和伟光正的南泥湾相比的。

其实大家看问题，不必这么极端。只要是改革开放后出现的事情，就往一个方向夸大。而以前发生的事情，就向另一个方向夸大。

*军队是用来打仗的，是不应该搞生产。这个假定没有错，但是你的前提，就是要国家保证军队的供给。*

南泥湾显然是不符合这个前提。但是天下没有完美的事情，如果当年国家有钱，可以支持军队，那么汉朝也不需要搞屯田，汉武帝也不会在轮台该不该军垦一事上伤透脑筋。

屯田的事情，在明朝和清朝也实行过，最后是效果不佳。建国之后，俺们也有建设兵团，今天也留下了不少遗产，需要好好消化。

南泥湾时代进行的大生产运动，是因为当时边区的经济情况不佳。靠取财于民，已经给当地的人民太大的负担。结果发生了一件事，好像是一个县委书记被雷击而死，然后民间传言说，怎么这雷公不长眼，没有打对人呢。

然后毛主席就坐不住了，大家决定，不能在增加人民的负担，于是军队要开展生产自救，王震将军的三五九旅，就开始军垦了。

*1985年，邓小平基于中国安全环境的改善，开始裁军一百万，大幅度削减军费。因此军队如何开展生产自救，也变成了当时的一个无奈的选择。*

其实军队在很多时候是被赶鸭子上架的。比如说文革后期的军宣队，就是在政府系统瘫痪之后，军队实行政府功能。不过后来很多军队干部，也没有在风起云涌的政治斗争中讨得好处。俺记得小时候，俺的城市里，曾经作为市革委会主任的某军长，就被挂了一个反革命和军阀的牌子，在卡车上被押着游街呢。

*当时军队经商的路子，主要是几个。第一个就是开始向外面卖军火，这个还是以总部的装备部为主，挂了几个公司的牌子干的。*

*而在大军区一级，主要的赚钱方式，还是把军队内部使用的招待所和食堂拿出来，开始搞对民众开放的宾馆和餐馆。* 比如说广州军区，那么就是由军区后勤部下面的一个企业管理局，专门经营的是一个少将，来管理下属的一堆实业。

当时整个中国都缺乏经营人才，不少地方搞 *包干制* 。就是几个能人，来包干一个企业，保证你多少盈利上交，剩下的就是经营者所得。

于是一些军队的产业，就包了出去，还有一些是爱国的港商或者台商来包干的。

这样的经营，基本上没有牵涉到战斗部队。不过后来在沿海，尤其是海南狂飙的全民走私汽车大潮，估计南海舰队的运输船，是掺乎了一把。

这样的局面，大概是很多人反对。包括一些老将军，都不以为然。

*不过不知当时军队财政的困窘之状，是没有资格批评军人的。* 而且相当于后来国企的关停并转那样搞裁军，也得有过办法让一些人过渡一下。俺当年因为机缘巧合，也时常为他们帮一下忙，尽一点微薄之力。毕竟军人经商，本来就是劣势，国家困难，没有钱养，转过头来对他们求全责备，未免不太厚道。

当然军队里面的一些有识之士，尤其是总参谋部的一些人，看出这样下去不是办法。这种忧虑到了美国进行海湾战争的时候，对他们触动比较大。因此 *从1993年开始，要求军队进行现代化和专业化，就是从以前那种大而全的军队办社会模式，向小而精的集成化结构转型，成了军队里面的呼声。*

在这个情况下，希望军队和商业切割，重新由国家派皇粮的共识逐渐形成。而当时因为美国战略开始转变，逐渐以中国为敌的姿态慢慢成型，客观上给这种变化带来急迫感。

也是在那个时候，俺当时对国际政治的一些看法也逐渐与总参里面的朋友们产生共鸣， *如何发展中国的海军，打破第一岛链的封锁，大概就是那个时候成型而变成中国军队的一个发展方向。*

*到了今天，以第二岛链为突破点，已经成了下一步的主要目标。* 当然从1993年，花了5年时间，直到1998年底，中国的军队发展才重新走回正轨。而大家都知道，很快就发生了南斯拉夫使馆被炸事件，表明了这个转变确实到位。

*其实说白了，中国海军的大发展，某种程度上，是利用了台湾问题，以这个主要平台，作为一个借船出海的招牌。*

那么刚刚出台的日本新防卫计划，也是有异曲同工之处，就是借助朝鲜半岛紧张这条船，以未来中国军力威胁为招牌，来为日本借船出海。

以前俺说过， *日本作为一个大国，地缘位置比较差。* 东边是美国，西边是中国，北边是俄罗斯，在军事实力上，个个都可以压日本一头。

过去因为俄罗斯占住了北方四岛，对日本威胁比较大，所以日本的防务重点是以北方为主。

在俄罗斯衰落之后，日本的战略主要是东盼西顾，没有太多的腾挪空间。而且受到美国的明防暗压， *日本的自卫队没有独立作战的能力。就是说，自卫队是给美军提鞋的，作为一个辅助力量，可以非常有效地支援美军的作战。*

*但是要是自己出来出头，那就连一个完整的作战方案都无法实行。*

而且美国对日本的防范，就是在亚洲，不是搞北约那种美国领头，多方商量的法子。而是搞美国和其他国家的单边合作的方法，来防止手下的狗腿子们自己拉帮结伙。

可是在现在面对中国的崛起，美国又不愿意自己直接和中国对抗，希望采取 *离岸平衡手* ，靠中国的周边国家与中国对抗，然后美国扮演一个帮打的角色。

那么对日本来讲，就是你要俺担负更多的角色，是不是得松一松俺脖子上的链子？

*因此借中国威胁为招牌，趁机做大自己的实力，才是日本人现在最热衷的东东。*
