# -*- org -*-

# Time-stamp: <2011-08-23 19:56:09 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话9：如果恐吓不再起作用


[2010-10-18 00:39:03]


美国现在希望摆脱危机的一个方法，就是希望 *通过美联储大量印钞，把全世界的通胀给炒上去* 。

在这个脱困方法的指导下，奥巴马政府希望采取加大政府财政赤字的方法，刺激经济，然后（这个就不知道靠谱的程度有多大）在中长期计划中，来裁减赤字。

为这个方法鼓吹的人，包括克鲁格曼等等，都会用小罗斯福时代的国债高负债额，在战后的经济发展中，被成功的稀释为例，为美国政府现在的大量财政刺激计划作为证据。

不过这些所谓专家，大概有意忽略了美国在二次世界大战后的经济高速成长率，在今天是完全不可能。因此美国出现的债务状况，绝不可能复制美国当年的情况，而会更类似于日本那样的国债不断增高，但是经济增长率却上不去的局面。

在这种局面出现的情况下，就会要求美国政府，必须实行非常痛苦的 *财政减缩计划* 。

其实这种裁减财政计划，应该是相当于今天欧洲的国家们再做的事情。

就是说你一方面要 *裁减福利* ，比如说法国那样的把退休年龄延长到做法，又要 *减缩政府现在的福利支出* ，又要 *裁减政府支出* ，比如说英国那样的裁减军费。

你只要看一下欧洲人民上街的抗议行为，就知道这样的裁减计划，会造成社会的一定程度的动荡。

美国政府打的如意算盘，就是今天赶紧靠政府的大规模举债（其实已经是直接印钱了），靠这些财政赤字保住各类政府的工作人员职位，然后希望以后可以由其他地方来的钱，比如说私人投资的钱，或者外面抢来的钱等等，可以让政府从容的退出这个刺激程序，而且还可以让政府开始裁减财政呢。

那么这个计划成功的可能性有多大？那就是天知道了。不过这个是一场豪赌，那倒是不错。想到了当年美国打进伊拉克之前，美国国防部对国会提交的财政报告，就是说用伊拉克石油来支付战争费用，最后还是成了一个大忽悠。

而美国中期计划开始裁减的政府赤字，你只可以从两大块来裁减。一块就是 *国防预算* 。

这个部分裁减应当难度不小。你现在不是还在战争中吗？就是说反恐战争，是一时半会儿完不了。

伊拉克和阿富汗都不可能大规模撤离（伊拉克号称撤军，还是有5万军队驻扎），要是美国的国内安保一次没有防住，让也门来的恐怖分子在美国搞成功一次，那么迫于国内压力，美军只好再开一个新战场了。

而且中国军力的快速增长，也迫使美国在国防预算上，裁减有一定难度。

美国的政治转换，在总统这一领域，通常是4年。如果大家对你不满意，当然可以等4年。但是如何时不我待，你等4年等不及了，那么另一个快速换人的方法，就是弹劾总统。

可是弹劾总统，难度颇大。克林顿拉链门那次，也是不了了之。

*不过美国有一个更快速的换总统的方法，就是一个响声：“呯”。*

就是 *林肯总统* 、 *加尔费尔德总统* 、 *麦肯尼总统* 、 *肯尼迪总统*被换掉的方法。

其实其他更多的总统，都是有人想换掉，但是没有成功的，比如说杰克逊总统、老罗斯福总统、小罗斯福总统、杜鲁门总统、尼克松总统、福特总统、里根总统和克林顿总统。

老布什总统和小布什总统，倒是海外的某些人想换掉没有成功。

美国现任总统奥巴马，在宣誓之前的几个月内，就曾经有4次对他的暗杀计划流产。最后一次还是一个美军陆战队员准备在军营里面刺杀他。

要是你得罪了军队和军队后面的国防工业，那么被这种方法换掉的可能性，就会升高很多。

那么你可以砍的财政支出，不就是 *社会安全计划* 和 *医疗保险计划* ？还有什么支出可以裁减呢？

说实在的， *如果美国政府今后几年，能够做到年度财政赤字不要继续增长，可以让美国现有的国债增长速度减慢，就已经是一大奇迹了。至于减少国债，那基本是不可能的了。*

现在想不给有钱人减税，都做不到，你总得变出些收入进来吧？像以前一样，从日本和欧洲那里去抽血？

而现在美国最想抽血的目标，就是中国。当然美其名曰，要解决全球经济不平衡问题。或者叫做中国做一个负责人的大国的问题。

*总而言之，只要俺不负责，你就要负责任。*

那么美国现在打出来的牌，就是要打 *汇率战争* 和 *贸易战争* 。

*打汇率战争，就是美元是俺的货币，但是是你的问题。*

*只要俺美国不断地拼命地印美元，那么这些美元就会以投资的方式，去你的国家买你的实体企业，从而导致你的流动性泛滥。*

*换一句话，就是俺向你的国家出口通货膨胀。你如果搞紧缩政策，只能紧缩你自己的资金投放，你又紧缩不了俺的资金投放。*

*那么你自己的企业拿不到你自己投放的资金，岂不是要拐弯抹角，跑过来从俺这里借钱？*

因此这个方法，就是把烫手山芋扔给你。你最好就老老实实，让自己的货币升值，不然的话，你没有办法控制通胀，也没有办法控制美元的超额流动性。

其实美国这一招在1970年的时候用过，是主要用来对付欧洲的。

中国的应对手，其实就是 *加强资金账户管制* ，来防备这些热钱涌入。

有人说，中国不是已经在管制海外的热钱吗？

不是。因为美国在1970年的做法，其实是包括大规模到欧洲实体投资的方法的。而中国以前的资金账户管制，并没有包括管制外来的自己投资。

*美国的想法，就是俺用多如洪水的钱，来投资你的实体，然后逼着你的兑换率上升，然后俺的实际资产是增加的。*

因此中国采取的对策，其实是很简单。就是要以针对美元到中国投资的限制。

想一想中国企业要到美国投资，人家美国人说，你拿美元来，不要拿人民币。

那中国企业说，俺哪里去找美元？人家美国人说，关老子屁事。

所以中国政府可以颁布一条投资法， *海外资金要投资中国，可以。拿人民币来。俺不接受美元。*
