# -*- org -*-

# Time-stamp: <2011-08-24 09:34:35 Wednesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话16：最好的蓄水池是邻家大院

[2010-11-06 13:48:26]

当时美国用来冲击德国金融次序的投放资金，大概是接近30亿美元，相当于德国整个外汇储备的5%左右。

今天中国的外汇储备大概是2万5千亿美元左右，因此要是想冲击中国金融市场，至少也要有5千亿美元的热钱拿出来冲击中国才行。

美联储现在的计划是购买美国国债部分是6千亿，以及大概9千亿左右购买银行的坏帐。那么在中国采取资金账户管制的时候，有多少热钱可以流入中国，也要看其他的新兴市场，比如说印度和巴西，能够吸纳的容量有多大。

*中国面临的主要是两个问题。一个是如何对各级地方政府热衷于引进外资，进行调控。另一个是防止中国的各级国有企业，利用美元的超级流动性，从海外借钱。*

美国对海外的资金流入，采取的政策性调控，通常是用行政办法。比如说，对中国资金感兴趣的实体科技企业，就是用国家安全审议的方法，进行阻击。当然以前对中国投资于美国的金融行业，也是要采取阻击手段的，只不过这两年，美国金融业成立烂摊子，开始对中国资金采取宽容态度。

自然美国国债，这个白条，美国是一直忙于向中国推销，而巴不得你去狂买的。

因此俺觉得，*如果中国政府在防水大坝上好好下功夫，尤其是严密关注通过香港和澳门，流入的美国热钱，中国还是有机会阻止大规模的洪水的。*

*通过黑市和地下钱庄，有些热钱肯定进得来，这个时候，如何利用执法力量，对这些集团，进行骚扰和打击，就可以将热钱流入的成本推高，从而减弱这些集团的危害性。*

*然后等大洪水被你的大坝拦得差不多，成为毛毛雨，那么就在上海等等地方，建立一个游泳池，就可以把这些水蓄在那里了。*

而美国小规模的资本，俺认为应该是以向南方流动为主。最近俺观看了一些美国人海外投资买房产的故事，可以看出在墨西哥、加勒比国家一线。

以基金为主的大资本，估计在南美洲，就是以巴西为主打。在亚洲，是以印度为主打方向，因为毕竟东南亚各国，已经是惊弓之鸟，泰国已经要收15%的美元落地费，来阻止美元洪水的流入。

其实俺个人认为， *印度是一个隐忧* 。在金融危机之后，尤其印度的通胀压力比较高，利息率高企，导致了很多美籍印度人已经开始用美元做套利交易，就是借入低息美元，然后兑换成印度卢比，放在股票和地产市场里面，收取高利息回报。

在加上 *印度整个社会蔓延着一股赶超中国之风，琢磨着怎样才可以把GDP增长搞到2位数字，因此印度经济的泡沫化，比中国要严重得多。*

*当美国开始从源头上放出大水，你总得有一个大水池来蓄水吧。印度也许就是这个大水池，那么中国只要把自己的篱笆扎好，争取在回水的时候，可以飘在水面上，倒时候跟着美国的金融大鳄们一起打捞浮财就行了。*

当然中国自己的大坝，建得稳不稳，就要看 *鼹鼠打击行动* 的效果如何。虽然中国政府里面，有不少是忙着挖大坝的，但是如果可以将他们的挖大坝的速度减缓，那么在洪水冲击大坝之前，可以将水引入其他地方，那么未免不是一个好的办法。

*因此中国现在的做法，某种程度上，和美国在1970年的做法，也是颇为类似。*

当时美国是希望分而治之，就是靠利用日本和欧洲的矛盾，在两边上下其手，号称会给欧洲例外而主要针对日本。然后在欧洲，则是利用德国和法国之间的矛盾，以攻击德国为主。

美国这一次的主要目标是中国，然后是亚洲和东南亚各国，再之后才是欧洲。

而中国最近在欧洲频频出击，在法国下大单子，与德国秘密会谈，和英国开展商谈，是因为现在经济政策上面，中国和欧洲这三大经济体，都已经开始走入以控制通胀和削减财政支出的路子。

相比较而言，美国和日本，走的是另一条放水财政的道路。

那么非常明显，当中国和欧洲开始进行某种程度上的政策结盟（不是战略结盟，虽然俺们看到所谓战略伙伴喊得震天响），就是向美国指出一条阳光大道。

那就是 *美国人要想掠夺世界的话，欢迎你大爷到日本、印度和韩国，去横扫千军如卷席。*

*俺们中国不但不会阻止，还要帮美国人一把呢。*

最近看到美国的国有通用汽车公司要上市了，这里美国政府有60%的股份呢。上市成功了之后，自然要更加保证国有企业的优势地位。好像看到日本丰田，又有骄人的利润成绩了，看来还是可以收割一把了。

奥巴马老哥马上就要到这几个国家去视察了。估计两个重点，一个是肥水不留外人田，要把打击美国汽车工业的日本和韩国车系，在美国的市场，收复一些实地回来。毕竟抢夺了俺美国的市场，就是抢夺了俺美国工人的就业。

在现在的美国，这个是属于杀人父母的大罪。当然另一个就是虎口夺食，要求日本、韩国和印度的市场，更大程度地向美国企业开放。

*这个时候，中国应该好好配合一下，压制一下日本和韩国在中国市场的份额。* 对中级产品，以中国为过境而最终入欧美市场的，要好好大力扶持进口替代。对以中国为最终市场的消费产品，那么就要增加些行政措施，帮他们好好提高一些成本。

忘了说一句，俺从来都是大力支持 *日本和韩国在华企业的中国员工们，应该大力争取自己的应得经济权利的。*

最近日本要到越南北部去建造工厂，作为稀土开发和加工。当然越南北部是有一些稀土资源，但更重要的是 *中国南部的边界，是稀土走私的一大去处。*

*俺们应该关注一下，日本在这里的开发，有没有破坏环境，有没有盘剥越南工人？有的话，就要大力批斗，发动当地人民搞罢工，搞群体事件，来保证当地土著居民的权力。*

*如果没有，那么俺们中国应该好好学习日本人的高标准和高质量，用同样的标准来管理中国的稀土工业。而且所有的稀土产品，都必须征收150%的环境保护费，毕竟绿色经济不能建立在污染开采上面，是不是？*
