# -*- org -*-

# Time-stamp: <2011-08-24 10:48:15 Wednesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话25： 运动员和裁判是不能同时出任的

[2010-12-02 05:56:55]

谈起朝鲜半岛，想起来一段往事。

那就是在韩国准备同中国建立外交关系的前哨铺垫的时候，韩国派到中国的第一个代表团，俺是出面接待的主人之一。

也就是在那个时候，听到宇宙大国的人谈到给汉城改名。那时候提议的不是今天的插标卖的首尔，而是叫首乌尔。如果用广东话翻译一下，就是“你黑头啊！”。黑头黑面，大概可以形容今天韩国政府的样子。

上次说了，老戴在韩国谈六方会谈，就是扯淡。看了维基泄露出来的一些中国外交官员对朝鲜半岛局势的谈法，除了脑残这个词汇，你是想不到其他用词的。

要理解朝鲜半岛的现状，就必须明白两个词汇。一个是“ *维持现状* ”，一个是“ *改变现状* ”。

要维持现状，你就必须有势力均衡。因为如果势力不均衡，你就不可能维持现状。当然如果你的意图，是要改变的话，那么自然就要导致势力更加的不均衡。

在冷战期间，朝鲜半岛的势力是均衡的，是靠几年的血战，和几百万条人命而达成的均衡。

当时的整个态势，就是中国和朝鲜，加上苏联的支持，来应对美国，加上韩国和日本的支持。

为啥这么说呢？虽然中国是朝鲜战争的主要参战方，但是中国非常尊重朝鲜的国家主权，因此这个伙伴关系是处于平等的状态。

而美国和韩国的关系，确是一种主仆的关系，就是以美国为主导，而韩国配合行事而已。

这种关系定义，可以从三个事情上面看出来。

第一个中国和朝鲜，是这一方在朝鲜半岛停战协议上签字的国家。而在另一方，只有美国在停战协议上签了字，韩国从来就没有签字，当必须遵循签字的结果。

第二个就是停战之后，中国就没有在朝鲜的领土上驻军，而美国一直在韩国领土上驻军。

第三个就是如果战争再次爆发，朝鲜具有自己的决策权。虽然中国和朝鲜有军事同盟协定，但是军事指挥权，并不在中国这里。而美国完全具有韩国战争时期的军事指挥权。

那么在后冷战时代，情况有了一个大变化。那就是中国和苏联的继承者俄罗斯，同韩国在90年代，建立了外交关系。因此韩国理论上，不再是中国和俄罗斯的敌对国家。

*这种变化，自然要求另一边的美国和日本，也改变冷战思维，同朝鲜建立正常的外交关系，从而保证将朝鲜半岛的冷战对峙的局面消除。*

*但是要这样做，就必须保证以下几点事情发生。* 一个就是朝鲜和美国的关系正常化，朝鲜和美国签订互不侵犯条约。另一个就是美国不再干涉朝鲜内部事务，毕竟朝鲜内部实行什么样的制度，是人家的选择。你对人家集权政府如何如何，好像你自己从来没有在韩国支持过集权政府似的。而且你美国全世界不是君主专制的朋友国家，还是有一大堆？

当然另外一个就是美国和朝鲜关系好转，不以损害中国的经济和地缘利益为代价。

可是美国的想法，不是这样。 *美国的想法，就是要继续以朝鲜为敌，直到朝鲜崩溃，并以这个来冲击中国，同时把美国的势力推到鸭绿江边，以此来遏制中国。*

*在这种不平衡的情况下，朝鲜必须打破美国不肯谈判的姿态，* 那么采取的手法，就是发展核子武器，并将导弹技术和核技术，向美国的核心利益地区，中东的阿拉伯国家扩散。

至于韩国在这个新变化之中，自然是得利的一方。因为韩国希望和中国发展经贸关系之后，可以影响中国的立场，将中国从朝鲜的盟友一方，就是从本来的运动员，变成比赛的裁判员，从而在朝鲜和韩国之间的事务中，进行斡旋。

因此今天的韩国对中国不满，是有正当理由的。那就是你中国，没有扮演一个公平的裁判员的角色，在朝鲜半岛事务上，你偏帮了。

这也就是为啥中国的外交和经济界里面太多脑残了，因为这些人居然认可了韩国的这个理由，居然认为中国应该放弃朝鲜，从而支持一个韩国主导的统一的朝鲜。

要是让不懂历史的人，来主导中国的国家战略，来造成的杯具可是一个八仙桌都摆不下的。

从元朝、明朝到清朝，朝鲜和中国的关系，不光是一个相邻的兄弟关系。朝鲜王国一直是中国的附属国，怎么说呢，相当于今天俺们的香港和澳门这样的特别行政区的地位。

虽然说现代社会，不需要在搞附属国了，但是 *地缘政治的要求，就是在统一的朝鲜半岛上，不能出现外国的军事势力，尤其是以中国为敌的外国军事势力。*

*如果这一点做不到，那么俺就必须维持朝鲜半岛分裂的现状。* 那就是说，在中国现在力量还是弱势的时候，俺一定要当运动员，而不是当根本不可能公平的裁判员。

*你美国的政策，是要朝鲜崩溃，赌的是金家王朝的完结。而中国的政策，就是必须无条件的保持朝鲜内部的稳定。* 这种保证，并不是说一定要支持金家，而是必须有一个替代的执政力量，保证朝鲜在后金时代，仍然可以保持稳定。

而中国外交界，接受朝鲜半岛统一在一个具有外国军事存在，而且这个存在是以中国为敌的前提，真有点怀疑，这些外交官还是中国的外交官吗？

当然如果韩国希望中国扮演朝鲜半岛的裁判员角色，也不是不可以。先决条件，就是外国军事势力必须退出朝鲜半岛。

如果你韩国不再有外国军队的一兵一卒，那么中国就可以保证，在朝鲜和韩国的争执之中，中国可以不把韩国当成后娘养的，一定会一碗水端平。而且中国可以保证，一定会军事干预，任何一方导致的军事冲突。

当年韩国的金大中执行的阳光政策，就是疏远美国，亲近中国，和好朝鲜，就是走的这一条路。

现在的李明博的道路，就是反其道而行之，就是亲近美国，疏远中国，迁怒朝鲜。而在这个时候，你还要怪罪中国不当一个公平的裁判？你不看看你自己，用22个球员，去踢人家朝鲜的11个球员？

*朝鲜半岛要无核化，你中国就必须提供核保护伞和战争保护给朝鲜。而美国势力一日不退出朝鲜半岛和东亚，朝鲜半岛就不可能有真正的和平。*

在这种情况下，中国就不可能做一个公平的裁判，因为你比赛的参赛队员，已经不过公平的。中国唯一的选择，就是做好一个参赛的运动员，而且必须有一整套的比赛计划。

其中的关键之一，就是 *金家可以倒，朝鲜不能倒* 。
