# -*- org -*-

# Time-stamp: <2011-08-23 19:35:47 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话8：高不成低不就，再来一个中间空

[2010-10-17 02:51:18]


谈到为啥美国劳工基层工资收入在降低之前，先谈一件俺说过的往事。

在大萧条时代，小罗斯福干过一件事情，就是发布缴金令，把全美国的金条、金票等等，按照当时规定的价格收缴了上来，然后立即把金价提高，变相把美元贬值了差不多50%。

那时候这些金子都是从有钱人那里收上来的，虽然有些人把罗斯福恨得牙痒痒的，但是大部分富人都采取了合作的姿态。

和今天比较起来，当奥巴马想把大投资基金的老板们的收入税收，从不合理的20%的长期资本收入一栏，提高到工资收入（就是和大部分美国工薪阶层一样的税率），人家这些有钱人，就把奥巴马骂成入侵波兰的希特勒（杀犹太人之前奏）了。

在谈到美国工薪阶层收入实际降低，就必须明白，这个降低是跟 *美国中端技术职位流失* 有关。

在技术职位流失的原因的争论中，当然全球化是一个很大的因素。

在全球化的过程中，包括中国等劳动力资源丰富的国家加入到了世界产业分工体系中来，又由于运输、信息和交通技术，在电脑和互联网兴起之后，导致产业分工整合，而令大部分制造业走到了亚洲。

在这个全球竞争格局中，美国劳工确实因为各种原因，而在竞争中失利，而出现 *美国产业空心化* ，大部分职业机会外流的情况。

也是在这个背景下，以美国制造业工会，比如说钢铁业工会为主导，坚持针对中国的人民币汇率政策，而倡导贸易保护主义，企图扭转美国中端技术职位流失的情况。

但是全球化毕竟还是近10来年才开始盛行起来，其实在1980年代，美国就出现了工作岗位不足的问题。

这个问题，其实是和科技进步有关系。实际上，就是随着科技提高，生产线的自动化，仓库管理的集成化等等，都导致对技术人员的需求大大降低。

大家想一下，以前电话交换机是需要接听员的。你每打一个电话，就有一个接线员帮你转接。后来电话自动交换机出现了，几十万个接线员的工作机会就没有了。

当然在这个过程中，也出现了美国科技和产业向高端提升的情况。这就要求美国被技术进步淘汰的中端技术人才，必须进行再教育，而转移到高端技术工作上去。

而这一点，是美国非常失败的地方。那就是因为美国基础教育中，对数理化的不重视，大部分小学和中学教育水平太差，造成美国自己教育系统和再教育系统里面，无法提供大规模的高科技人才。

如果看一下两大高科技行业，一个就是 *信息产业* ，在美国的硅谷，走在路上的电脑工程师，大部分是来自印度和中国。另一个就是 *生物化学产业* ，也主要由中国人担纲。

虽然可以说美国在吸收海外人才上面，有其独到之处，但是这样大量的靠网络外面的高科技人才，同时把自己国家的中端技术人才，给赶到了一边，而不是靠提高这些人的技术水平，来满足产业升级的要求， *必然在社会中形成仇恨移民的本土保护主义情绪* 。

把这个和德国经历过的产业升级换代，就可以看出美国的失败之处。

所以美国工薪阶层的情形，就是高科技的劳工需要从外面输入，低端的劳工职位，比如说农场里面去收割农作物，收集草莓等等，美国人又养懒了，没有人愿意去干。甚至很多小企业里面的蓝领工作，也找不到美国人干。

因为美国和加拿大、墨西哥签订了北美自由贸易协定，结果政府补贴的美国大农场，狭持转基因等等技术的威势，就在墨西哥人主要的食物玉米上，把墨西哥的很多小农经济给打垮了。

而这些失去了农业维生的农民们，要么就转种一些毒品，或者帮墨西哥毒贩打工，或者就一窝蜂拥入美国。这些来自墨西哥的非法移民就占据了美国的大部分农场劳工、建筑业下工、餐饮业帮工，以及超级市场的低端工作机会。

*因此在美国高端和低端两个职业市场，算是被合法和非法的外国移民给占得差不多，而中端的工作机会渐渐消失，大部分美国人在没有多少技术含量的服务行业谋生。*

*唯一还有比较好的工作机会，除了每天搏命的专职销售行业，就剩下了可以赚大钱的金融和相关行业、法律相关行业、医药和医疗相关行业。*

当然有句话是羊毛出在羊身上，你这些抬高的金融中介费用（虽然美联储在拼命降息，但金融中介吃的部分，仍然颇为可观）、社会医疗费用（昂贵的药价和诊金）、法律诉讼费用（狮子开大口的官司）等等，都全部压在了企业的身上。

这样高昂的运管成本，美国大企业不往外国跑，那才怪了。现在估计下一个趋势，是美国的中小企业，都会向外跑。

因为人家一个中小企业，大概也没有想要开发什么国际市场，要把公司做大等等。看到美国企业的运营环境这么差，不排除一些公司彻底放弃美国市场，带着资金和技术，跑到中国，去中国谋生算了。

*其实如果美国人团结一致，给企业创造一个宽松的经营环境。政府税收减低一些，金融、法律、医疗三座大山抽血抽得少一些，然后企业高管们花红再分得小一些，大家都不会对生活影响太大，毕竟每年你不赚几百万，你会死啊。*

在这种情况下，美国劳工阶层也把工资降低一些，那么还是可以和其他经济体，比如说德国和日本竞争一下的。毕竟德国和日本的医疗和法律费用低于美国，美国一个CEO的工资可以养3个德国CEO，5个日本CEO，也不见得你美国的公司，就比人家好到哪里去，是不是？

*不过美国的问题是，还是先想走到外面打仗，抢人家钱的方法。现在就是看美国可不可以在中国、欧洲和日本身上，通过狂印美元（大概今年是要印1.5万亿出来）来抢钱。如果这个做不到的话，在美国和全球推高通胀，抢劫包括美国自己在内的全世界屁民，就是下一个选择了。*

在这种大背景下，黄巾军队伍的扩大，就是必然会发生的事情。
