# -*- org -*-

# Time-stamp: <2011-08-24 10:10:03 Wednesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话20：大家齐练七伤拳

[2010-11-20 14:13:51]

谈和法国的能源合作，先看一下英国首相卡梅隆的豪华访问团，在中国签订了什么能源合同。

其中一个主要合同，是英国的BP和中海油合作，在南海勘探和开采石油，这个动作基本上改变了中国在南海只说不做的局面。再加上中国阻碍西方各大石油公司，在越南控制的南沙海域合作开采石油的行为，大致可以了解为啥南海争端开始热了起来。

在这个时候，欧洲的法国和英国，全部站在中国一边，再加上美国石油公司雪佛龙的中国分公司，也掺乎一把，大致可以化解希拉里在南海发动的反华攻势。

*你也可以说，因为美国政府，要在南海实现其核心利益，那么你中国在南海开发的时候，最好也要带上几家美国石油公司一起发财，不然的话，人家肯定要过来搅局。*

*而如果你把这些和美国军方的关系，是剪不断理还乱的能源公司，拉下水，那么最大的黑帮成了股东之一，那么其他的黑帮也不敢发话了。*

美国一直对法国没有什么好的办法，主要是 *法国能源不是依赖于石油* 。法国发电的差不多80%是依靠核能，而法国的核原料来源，主要是来自于加拿大和非洲的尼日尔。

法国的用铀量，一年是10500吨，其中4500吨来自加拿大，3200吨来自尼日尔。

考虑到法国在加拿大的特殊地位（法语是官方语言之一，魁北克是法国领地），这个安全性保障是没有问题的。

而在尼日尔，由于中国在非洲开发的步伐相当大，曾经引发了法国队恐慌。只有在这个背景下，才可以真正明白为啥2008年北京奥运会之前，法国搞出了那么多的疯狂动作。

*现在估计是中法在非洲问题上，有了相互谅解和合作的诚意，那么在这个核子协议中，关于尼日尔的铀矿开发问题，大概也谈判妥当。*

大家必须明白一个道理， *对中国的发展而言，能源是一个很大的瓶颈。* 在2008年俺在《花开花落》系列中，明明知道美国的高铁计划估计是没戏，但就用这个计划，鼓励中国在高铁上加快步伐，是因为 *要彻底摆脱对石油能源的依赖，中国必须在交通建设上，走出一条前无古人，后无来者的道路。*

*高铁的电气化，以及电动汽车的出现，达到的目的，就是要把交通工具的动力，从燃油转化为电力。而在电力上面，中国是世界上煤炭资源大国，是排在美国和俄罗斯之后的第三位。*

虽然说现在地球暖化和环境污染，成了大家关注的大问题，但是要知道， *当日子过不下去的时候，你还有这么多煤炭来保证大家可以生存，那才是重要的问题。*

因此 *中国的能源战略中，如何依靠高科技实现更好的利用煤炭，做到高效率和低污染，是未来的一个重大技术课题。在清洁煤、气态煤和液化煤等等技术开发上，中国都必须有所作为才行。*

除了煤炭之后，就是水能和核能。在水能上，中国已经算是做得比较好的了。但是在核能方面，中国在技术上，尤其是核岛关键技术上，还有待提高，这个也是法国技术可以为中国添加一臂之力。

而铀矿的储藏量，主要是在加拿大、澳大利亚、哈萨克斯坦、俄罗斯和尼日尔。中国的新疆北部一直到内蒙，可以看作是和哈萨克斯坦的同一条地质带，因此好好勘探的话，应该有不少铀矿。这样基本可以保证中国的核能发电，可以有足够的原料保障。

至于其他的清洁能源，比如说风能和太阳能等等，还只能作为补充能源，短期内无法担当大任。

*那么当中国的经济和欧洲实现了某种程度上的合作，必然会导致美国投鼠忌器。就是说如果按照希拉里阿姨的想法，在伊朗和叙利亚那里给你来一把，或者在亚丁湾那里“反恐”，这个时候保证这个地区航运安全的，就是中国和法国的联合海上舰队（法国在亚丁湾附近还有军事基地）。*

而且好像人家刚刚有一个协定，那就是英国和法国的军事合作，就是说这个舰队里面还有英国军舰呢。不知美国会不会“误炸”他们呢？

*美国在1970年代，要拿欧洲和日本开刀，主要是越战打得太心疼了，需要你们这帮丫来分摊成本。而今天美国想拿中国开刀，也是因为伊拉克和阿富汗打得辛苦。*

美国在伊拉克偷用了人家伊拉克人不少钱，但是油田没有机会兑现。现在突然决定要向阿富汗运送总装备坦克了，说明前方确实比较吃紧。

在加上这十几年的大吃大喝，当然想要人家别人来付账。

那么美国可以依赖的是什么呢？就是你安全上要依赖于美军。

当年德国不得不屈服，是因为苏联领军的华沙条约国家，就在门口。而日本也是一样。

今天这一条，是没有法子用到欧洲人身上了。俄罗斯威胁？靠着格鲁吉亚、乌克兰、波兰和捷克，在那里添点麻烦，还不足以把欧洲和俄罗斯引到开打的地步上去。

而且人家欧洲在阿富汗还出了3分之一的维稳城管呢。你要是逼急了，人家经济问题严重，就顺便撤军了。

那么在亚洲有点效果，那就是 *朝鲜半岛* 局势紧张了， *东海* 局势紧张了， *南海* 局势紧张了，还有就是 *南亚* 也不安宁了。

这些都要求大家更借重于美军了，所以奥巴马到亚洲走一趟，用俺们的俗话来说，就是去 *收保护费* 去了。

结果除了印度交了一些保护费之外，其他地方奥巴马是空手而归。连韩国人都说，对不起，老大，俺家里也没有余粮了。

而用来对付大家的印美金，来水漫金山的方法，也在中国和欧洲受到了强力抗击。

欧洲人的做法，就是自揭其短。突然奥地利说，俺不管希腊的事了。然后就是爱尔兰似乎挺不住了。

这种做法，就是七伤拳，打你也伤俺自己。这次欧洲的做法，就是用伤南欧保北欧的方法。因为欧元猛涨，伤害北欧的实体制造业，而欧元跌下来，就会伤害南欧的借贷花钱业。

制造点欧洲恐慌消息，就是用来恐吓热钱，让你知难而退。

那么这些钱，当然还是想冲向美联储心目中的金山，那就是中国。而中国也需要拿出自己的七伤拳出来，让美联储的拳力，弹回去打得自己七窍流血。
