# -*- org -*-

# Time-stamp: <2011-08-24 21:45:08 Wednesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话38：国家如做人需要堂堂正正

[2010-12-31 16:00:36]


记得《大国游戏》里面提到当年日本人写《日本可以说不》的时候，就是日本经济帝国如日中天的当口，日本人对未来的看法是两种观点。

一种就是看低西方文明，认为日本要回归亚洲，从而获取从美国的压迫下独立的国家地位。

另一种就是要求更加向西方靠拢，彻底脱亚入欧，让日本可以和其他西方大国一样平起平坐，从而获得成为和美国平等的伙伴的独立国家地位。

而且俺还提到，在那个时候，日本人虽然认为中国最终会崛起，美国最终会衰落，但是这个过程是一个缓慢的过程。因此日本在其中扮演的角色就是一个关键，那就是说，如果日本偏向美国而帮助美国的话，那么美国就可以延缓衰落50年。

当然如果日本偏向中国而帮助中国的话，那么中国就可以提早崛起50年。

对这种观点，俺当时是非常不以为然。因为从当时俺的看法，中国在世界崛起的时间，也就是50年的时间。如果你日本人想过来凑热闹，当然欢迎。但是如果你觉得没了你这个张屠夫，大家就要吃带毛猪。那么也太自怜自爱了吧？

无论如何，日本在广场协定之后，确实在“帮助”美国了。在佛教里面，这个叫做舍身喂鹰。

那么为了阻止中国的崛起，日本你可以继续无私奉献，替美国输血啊。

最近美国政府开始了对丰田公司的第一笔罚款，大概是3200万美元。而号称丰田事故造成的46个事故，美国政府自己承认确有其事的一桩，也由丰田出血1000万美元来平息。

因此在未来因为欧洲不断面临的财政困境，美军在阿富汗的成本，就不得不从日本和韩国这里抽了。

*那么从日本的立场看，现在最主要的，就是要扩大自身的实力，在中美的对弈中自保，并两边下注，希望可以从中获取最大利益。*

在海外扩张方面，就要实行日本的南进战略。

所谓南进战略，就是你向北、向东和向西，都是雷池而不敢逾越一步。

但是向南，就是一串岛屿，最近的是台湾，其次是菲律宾，然后是印尼，最后是澳大利亚。

从这里向西，前面是越南，后面是印度。

日本本来的想法，就是整合这么一大堆国家，然后可以看形势而动作，所谓看菜下筷。

如果日本可以夯实这个一个海岛集团，那么就可以在中美之争中左右逢源。

其实说白了， *日本就是一个大号的韩国，但是心里的小算盘打得是一样的。*

不过日本的问题，在于此一时，彼一时。日本经济面临的困境，已经使得日本在东南亚想整合菲律宾、印度尼西亚和越南，是不可能的事情。

大家不信的话，就等着看中国怎么在印度尼西亚和马来西亚的投资吧。等到这些投资开始出效果的时候，也就是中国海军的军力冲出第二岛链的时候。

当然，不光是海军和空军，大概从昆明的高速铁路，也可以到吉隆坡了吧。

现在可以看出来的，就是澳大利亚的陆克文代表的一些精英人士，倒是对遏制中国比较有热心。不过也要看一下这几年之后的形式发展，才可以对澳大利亚的真实意图，了解清晰。

有读者发过来一个链接，是新加坡的一位所谓中国问题专家叫做郑永年的，对中国外交的一些看法，征询俺的意见。

俺的意见，就是 *一个国家在世界上的外交行为，也要像做人一样，要做得堂堂正正。*

海外的不少华人学者，虽然也会为中国的利益思考，但是源于思考角度的问题，常常有一种俺称为的 *小妾心态。*

怎么会这样说呢？就是缺乏堂堂正正作为一个中国人而应该具有的自身为主体的独立地位。因此一起立论的基础，就是要考虑如何在人家西方制定的一个框框架架之中，如何放软身段，翘首弄姿，以讨西方主子的欢心。

这一点，倒是西方的学者们看得比较清楚一些。他们看到中国实力的增加，担忧中国和西方双方，无法有效地调整大家的立场，尤其是西方，没有办法适应中国的崛起，从而导致冲突，而令现今的国际体制崩溃。

当然由于目前的国际体制，无法适应中国崛起的事实，是需要进行理所当然的调整。

但是在这种调整之中，西方当然希望开出一个高价，让中国多出点血来让步，是理所当然的讨价还价。

而在这个讨价还价的过程中，西方国家总体来讲，还是尊重中国这个对手，有一种平等的讨价还价的地位的。

相比于西方学者，所谓海外中国的学者们，对中国的看法，基本上就是一种小妾的心态。现在觉得自己的底气强了，希望从小妾变成二房了。

在这种立场下，这些学者，有意无意曲解了中国改革开放的本意，把中国改革开放，从而回归世界应有的地位，看成了简单地要混进西方的大国俱乐部。

而邓小平的“发展是硬道理”，就被简单地理解发展对外贸易，而不知道 *发展的目的是中国的四个现代化，就是工业、农业、科学技术和国防的现代化。*

而且把中国睦邻友好的政策，理解为要发展经贸，从而牺牲自己的地缘安全。不知道俺说的那句话， *没有政治指导的经济，是盲目的经济，没有地缘参照的政治，是糊涂的政治。*

所有把周边国家，如日本和韩国的一些遏制中国的举动，说成了是中国的身段不够软。

而美国针对中国的军事压力，更提议要中国选择战场，不和美国军事竞争，而是要以经济竞争来应对，说白了就是对美国的军事讹诈，中国进行经济让步，然后就息事宁人。直到下一次讹诈开始。
