# -*- org -*-

# Time-stamp: <2011-08-24 10:00:49 Wednesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话19：大家齐心揍老大

[2010-11-10 16:53:44]

前面说到美国威胁德国和日本的工具，当时就是 *苏联威胁论* 。

而当苏联崩溃之后，这个威胁一解除，受够了的德国人，马上伙同法国人，开始搞欧盟了。

如果看欧洲的国家形态，大概是3种。

一个是海岛国家，一个是半海半陆国家，一个是内陆国家。

其实这些都是现在细分的结果。如果看海洋的话，欧洲是一个双海洋国家。在西边是浩瀚的大西洋。而大西洋主要是5个国家的独享地方，这5个国家分别是英国、爱尔兰、法国、西班牙和葡萄牙。

然后大西洋在北部的海湾北海，可以让欧洲中部的国家，比如说德国、荷兰、比利时等等进入大西洋。当然挪威可以通过挪威海，俄罗斯可以通过巴伦支海，进大西洋。不过北部的气候状况不是很理想。

那么其他的内陆国家，虽然不是内陆，比如说波兰和俄罗斯等等国家，都只好经过波罗的海，要过两道关卡，一个是在丹麦和德国那里，一个是在英国那里。

所以英国算是一夫当关，万夫莫开。当年荷兰人被英国人打垮，和这个地理形势很有关系。

在南部的海，就是地中海。这里去大西洋，要过直布罗陀海峡。从地中海往里面走，就是里海。

因此俺们可以说，大部分的欧洲国家，基本上都是在“海”边，但是真正拥有海权的国家，只有几个，而这几个就是 *以海盗身份而扬威的葡萄牙、西班牙、荷兰、法国和英国* 。

当航海技术还没有大幅度提高，所谓的海上大发现时代还没有来临的时候，因为苏伊士运河也没有开通，所以向东方的道路基本上是以陆路为主，或者是从陆路过阿拉伯半岛，然后从印度洋入海。

*因此当时的占优国家，不是大西洋的垄断者，而是地中海的垄断者。* 在大西洋边缘的国家，比如英国，那就是属于蛮荒的边远地区了。

因此看整个欧洲的结构，基本上是三大板块。

第一个板块，是西部板块，基本上是以法国为中心，加上葡萄牙、西班牙、英国和爱尔兰。

第二个板块，是中部板块，基本上是以德国为中心，加上奥地利、瑞士、匈牙利等等。

第三个板块，是南部板块，基本上是以从前的拜占庭王国的领地，就是今天土耳其和巴尔干诸国，加上罗马尼亚、保加利亚等等。

而其他的两个边缘板块，一个是东边板块的俄罗斯，一个是北欧板块，都常常游离于欧洲主要事务之外。

以前的北欧，是扮演的南下掠夺的海盗的角色。后来北方的海盗衰落之后，东边的陆盗兴起了，俄罗斯一直就扮演着对欧洲中心地区进行威慑的一个角色。

因为突厥人攻陷了拜占庭，导致了欧洲在南部地区的势力衰落，同时通过地中海的东方贸易道路，渐渐被由西部走向大西洋的方式取代，因此这个变化，导致了南部板块的影响力大幅度衰落，并附带拖垮了意大利。

于是西部板块在地理上占优，和中部板块的对垒，就成了欧洲进百年来的主旋律。

西部和中部的划分，基本上是延续了路易国王的三个儿子，在凡尔登条约里面的分赃结果。在分赃中出现的东法兰克王国和南法兰克王国，基本上是中部板块。这个板块后来以神圣罗马帝国的方式，维系着欧洲的中心地位。

但是在欧洲出现宗教分裂，以马丁路德领军的新教，和罗马天主教对撼，导致了30年摧毁中部板块的战争。在这个战争里面，作为边缘板块的东边和北边，都参与进来。不过起最大作用的还是身为天主教国家的法国，决定参加新教国家，把欧洲中心给肢解了。

*欧洲人玩的游戏，叫做大家齐心打老大。* 这个时候，就是齐心把哈布斯堡王室给悲剧了。然后战争结果，威斯特法利亚条约出现，中部板块给打破了。西部板块中的法国因此而崛起，那么就引发了大家齐心打老大，包括英国、俄罗斯和土耳其都掺乎进来，想把老大法国给灭了。

这个时候法国出了一位极其强悍的拿破仑，顶了一阵子，后来还是又悲剧了。

法国这个西部板块被打残之后，中部板块出现了新的整合，就是北部的德意志的统一和崛起，和南部的奥匈帝国的邦联也成型。

于是打了一百年战争，两败俱伤的法国和英国，又联合起来了。和英国在全世界顶牛的俄罗斯，也占了过来，大家要回到齐心合力打老大的状态，准备对付威廉二世的德国。

这就是著名的结束战争的战争，第一次世界大战。战争的结果，是中部板块的德国和奥匈帝国，加上南部板块来起哄的奥斯曼帝国，统统悲剧。

但是想一想大概50年前，为了防止俄罗斯帝国的崛起，信奉新教的英国，和信奉天主教的法国，拉着异教徒信奉伊斯兰教的奥斯曼帝国，去悲剧信奉东正教，算是同教异支的俄罗斯帝国，可以看出欧洲齐心打老大的劲头。

然后就是二战时候，中部板块出了个强悍的希特勒，又顶了一阵子，然后再次悲剧。

二战之后，英国决定跟着新老大，远方的美国混日子。而法国，这个天生的反骨仔，开始同德国合作。如果说德国当时主要是提防苏联，那么法国就应该老是给美国惹麻烦的角色。

然后一看苏联解体，那么法国和德国马上上欧盟。这样的一个变化，基本上是要改变自从三分天下以后一直延续的欧洲政治现实，要回到 *查理曼大帝* 的统一状态。

但是当中部板块开始变得越来越强，比如说德国在金融危机之后的欧洲，经济恢复强劲，一花独放到情况下，就刺激了法国，开始和西部板块的英国重新整合。

*而德国则有缩回小欧盟，就是甩开法国和意大利，通过德国、奥地利、瑞士、荷兰这个核心区自我整合，使得欧元区有可能出现南北分化的趋势。*

因此中国和法国最近的哥俩好，是可以放在欧洲整合这样一个大背景下面去看的。

*当年美国对德国的王牌，就是苏联威胁。今天美国对日本的假王牌，就是中国的威胁。*

之所以叫做假王牌，是因为 *中国想叫日本玩完，是可以兵不血刃的。*

*而美国想对中国威胁，主要的王牌是能源，所以看一下中国和法国，在能源上面的合作，是颇有一些意思的。*
