# -*- org -*-

# Time-stamp: <2011-08-25 10:53:15 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话53： 土耳其模式

[2011-01-30 10:29:48]



在国际救援船事件，导致了土耳其和以色列关系全面恶化之后，阿拉伯许多国家的民众出现了土耳其热。不少人纷纷订购机票，到土耳其去参观学习。

土耳其的街头上，宗教气氛颇为浓厚，但是宗教势力，没有成为影响世俗生活的一大势力。对比安卡拉和德黑兰，大城市的阿拉伯居民表示首肯。

土耳其的民意中，对美国不感冒（俺在1993年去土耳其的时候，那时候还是很亲美），但没有到和美国要兵戎相见，大城市的阿拉伯居民再次表示首肯。

土耳其的政府，和美国有一定亲密关系，但是也有比较独立的外交政策。相对于阿拉伯国家的，对美国政府的俯首帖耳，尤其是针对美国的中东政策，大城市的阿拉伯居民三次表示首肯。

土耳其的政治制度，是宗教势力和世俗势力权重均衡妥协的民主。而伊朗的政治制度，是宗教势力占主要地位，和世俗势力妥协的民主。考虑到这两个地方，是阿拉伯民众们可以看到的唯一两个选项，大城市的阿拉伯居民四次表示首肯。

谈到大家的社会转型和现代化选项，其实土耳其和伊朗的起点差不多，当年伊朗还搞得比土耳其好一点呢。

可是土耳其有一个优势，伊朗没有，那就是土耳其没有石油。 *楚人无罪，怀璧有罪。* 伊朗因为有石油，所以搞政治民主，走现代化道路，就被美国给和谐掉了。于是伊朗国王复辟，最后引发了宗教革命。

这种情况下，很多德黑兰的大城市居民，就是比较现代化，比较喜欢世俗生活的人群，还觉得有些不爽。

而土耳其，因为没有石油，于是躲过了西方国家的大刀，顺利地进行了转型。

土耳其的经济发展也不错，虽然无法和东亚相比，但是也成为的一方人物。在可以预见的将来，土耳其会和南韩、墨西哥、印度尼西亚一起，被称为新金砖八国。

在未来老地主们开始破落，新地主们开始暴发这样一个历史趋势下，这个地位，不可小觑。于是大城市的阿拉伯居民们，第五次予以首肯。

而对美国来说，如果能够出现这样的局面，也就是说埃及等国，土耳其化，而不是出现要么是美国视为恐怖组织的穆斯林兄弟会上台，也不是美国认为的捣乱分子，前国际原子能总署主任巴拉迪出来整合反对派力量，那么恐怕是最好的选择。

而这种认可，也比较有利于埃及出现这种局面，因为会减少美国的直接干预。

当然你是无法否认穆斯林兄弟会的力量，会得到大幅度加强。因为在被宣布为非法组织之后，穆斯林兄弟会人士，通过独立候选人的身份，仍然拿下了埃及国会的20%的位置。

如果他们的身份被洗白，成为一个有组织的力量，那么做到30-40%，还是颇有机会。而这样就会成为埃及政坛的一个有影响，举足轻重的力量。

当然为了赢取大部分民众的认可，你穆斯林兄弟会自然要在宗教立场上，有所放松。比如说，你的女候选人，肯定要大力提倡保护妇女权利，给予她们公平机会等等。

这种情况的出现，基本上会引发一个中东北非地缘板块的重组。

就是出现一个独立自主，不是简单的美国基石的新中东势力。

这个势力确实可以起到平衡什叶派穆斯林在伊朗、伊拉克和黎巴嫩的坐大，但是不会出现现在的民间同情伊朗，但是官方和美国商议如何对伊朗动武的局面。

这个势力，会比较认同土耳其的做法，就是试图在伊朗和西方势力之间调停，来增加自己的国际影响力。

但是这个势力崛起之后，导致的最主要的输家，就是以色列。

随着巴解组织对以色列秘密谈判中的卖巴行为，哈马斯的人气会继续上升。而埃及政权的变化，会导致对哈马斯的支持公开化加强。

而黎巴嫩真主党在黎巴嫩政局的斩获，都导致了以色列出现的全面外交困境的局面，而颠覆了戴维营之后的有利局势。

而以色列在这个四面楚歌之下，会不会觉得被逼人了墙角，而断然决定先发制人，对伊朗动手，从而开启中东混乱的战火，都很难断定。

而这种局面出现，在美国没有完成布局之前，没有有效处理伊拉克和阿富汗事务之前，是会打击美国的利益。

*中国在中东乱局中的主要考量，还是稳定的能源来源，和欧洲市场的海路安全。*

不过如果真的中东一乱，也许对欧亚运输线，还会起一个刺激作用。毕竟现在的各国铁路，整合一下，还是可以对付一下的。

*但是中国的外交政策，一定要改变以前那种，只是交好权贵集团的纯粹利益优先的活动。*

*因为外交，是讲政治的。所谓讲政治，那么中国最大的政治是什么？*

*那就是要在世界上，反对帝国主义，反对霸权主义。* 中国自己不称霸，不当霸权，不搞帝国主义，就必须反对世界上出现垄断的超级大国，就必须支持世界各地的国家，搞民族独立，搞人民民主，搞外交独立。

只要把握这个尺度，那么任何对埃及人民和国家有好处的事情，中国自然要大力支持。而和埃及的友好关系，是对中国和埃及双方都有利的事情。

中国应该支持埃及政府和人民，通过改革和协商的办法，重新达致埃及的社会稳定，然后在经济发展、改善民生方面，中国愿意发挥投资，增加双边贸易的作用，使得埃及社会出现良性互动的新局面。

看这一次中东的变局，一个最大的影响力量，其实是半岛电视台。看来 *半岛电视经历了快20年的努力，终于成功地解决了西方舆论对中东的控制权。这个经验值得中国借鉴。*
