# -*- org -*-

# Time-stamp: <2011-08-25 20:39:27 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话75：悲剧和悲情

[2011-03-20 02:14:39]


+ (1)

因为最近一段时间，会比较忙，没有时间写大段评论。所以会短短地写一些想法，然后可以更新地频繁一点。

现在全世界注意的大概只有两个话题。一个是日本，一个是利比亚（其实就是法国）。

在日本的问题上，大家估计都看出来了，日本政府的表现是很差的。

当然 *中国人民解放军三炮部队* 例外，人家是有战略忽悠任务的。诗云：中华有三炮，遗世而独立。一炮倾人城，二炮倾人国。

据纽约时报的一个分析，日本的问题，是体制问题。

战后日本的政治体制，就是所谓的政治人物其实没有多大的权力。日本的外交和国防政策，是由美国做决定。而日本的内政，则是由强大的官僚集团话事。而这些官僚，又和各大公司和财团紧密相连。

本来当时日本的宪法，就是由美国的老麦将军制定的。虽然不完全符合日本的文化传统和国情，但是日本人的适应能力极强。因此 *换汤不换药的结果，就是政客们摆出来，对上面应付一下美国领导，对下面糊弄一下日本人民。*

反正选来选去，都是伟光正的自民党，人家里面自己派系斗争一下，也就罢了。

而真正让国家运转的，是你公众们连谁是谁都搞不清楚的官僚们。这些官僚们好好治理国家，无名有实，得到了报酬，就是下来之后，到大公司做官，好好地拿一份高薪，算是对他们的报酬。

但是在这近十来年，因为日本经济的没落，大公司总裁们的自信和影响，也大不如前。同时官僚的权威，也受到了公众的质疑。可是这两大政治势力衰落的同时，却没有强大的政治家阶层产生，来填补政治真空。

就像巴西前总统卢拉说，你和日本首相吃午餐，中间去了一趟厕所，回来人家就换首相了。就是最近大概不到4年的时间，就换掉了4个首相，现在的老五倌“ *兼职人* ”，大概已经被大家给直接忽视了。你以为一个大国的治理，像过家家一样？

结果就是自民党也没落了，就把民主党选上来。而民主党没有执政经验，人家官僚集团也不鸟你。虽然现在官僚集团自己腐败和无能也很严重，但是对民主党的领导，普遍采取消极怠工，让日本本来就问题重重的政府系统，在现在民族存亡的大灾难面前，更加显得无力。

所以面对核扩散的危险，首相说：自卫队，给我上，这是命令！

然后防卫大臣，说：自卫队，首相指示你们，要上啊。

然后自卫队领导，说：自卫队，首相要求你们，考虑上一下哈。

然后自卫队的中层领导，说：下面的，首相建议，是不是上去看看？

然后自卫队的基层领导，说：兄弟们，首相询问一下，上去行不行？

然后自卫队酱油党们，说：回答首相的询问，上去危险，建议坑爹，让美军先上去死。美军之死重于泰山，俺们之死轻于鸿毛。

一个国家和民族，都会出现悲剧。

你有大自然不可抗拒的摧毁人类的力量。比如说日本东海的大地震，中国汶川大地震，东南亚大海啸，美国新奥尔良飓风，等等。你也有人类自己乱来搞出的悲剧。

*但是一个国家和民族，不能有悲情。面对灾难，勇于承担，勇于牺牲，才是一个国家和民族的生存之道。在大灾难之下，被动地守纪律不一定是民族之福，真正需要的是人人为我，我为人人的热血和献身精神。*

如果一个民族的年轻一代，受到的教育和影响，是“要我为国家和民族死，那还不如让这个国家和民族灭亡”，那么这样的民族，估计是要看瘪的。


+ (2)

[2011-03-23 15:36:36]


日本核辐射问题，从国际关注点突然降温，其中的意味耐人寻味。

之前俺说过，在关注焦点上，日本自己比较紧张的是3号堆，就是 *用了钚做MOX燃料* 的那个堆。而美国更关注的是4号堆，就是 *乏燃料* 那个堆。

这两个堆的主要区别是，4号堆如果出事了，那么核辐射是冲上大气层，那么在下风口的美国是会受其害的，所以美国会更紧张。而3号堆当然也有乏燃料问题，但是水池里面的乏燃料只有514根，和4号堆里面的1479根，不是一个数量级。所以安全壳被底部烧穿，造成核辐射泄露到土壤和地下水里面，才是让日本更紧张的事情。

因此当关注下降，自然表明了一个结果，那就是 *日本核辐射的后继发展，对其他国家（美国）影响有限，而最后吃瘪，打掉牙肚里吞的是日本。*

至于核辐射最后的打击程度，是只限制在核电站周边20-30平方公里的范围，还是会渗透到日本最重要的心脏地区关东平原的北部几个县，那就会对日本的经济造成难以弥补的打击。

而这次美国对日本的支持，是很没有做老大的风度。本来日本打的算盘是，美国航空母舰里根号，会停在东北海岸边，然后日本和美国的直升飞机以其作为平台，把救援物资运进去，把伤员和需要疏散的灾民运出来。

可是 *一发现有核辐射的危险，美军离开掉头就跑。现在连东京南部的横须贺基地里的航母华盛顿号，也跑得无影无踪。*

这次在日本发生的灾难，也在美国的国债市场上引发了忧虑。考虑到日本需要大量的重建基金，日本政府手上的外汇储备超过1万亿美元，而且政府的负债是GDP的200%，因此很自然地会想到日本政府会不会抛掉一些美元国债，调资金回国救难。

可是美国财政部长盖特纳已经发话，日本是有钱国家，不需要靠抛售美国国债。 *俺认为你不需要，你就必须保证不需要。*

去年底的数字是，日本的政府和私人机构手上大概有8820亿美元的国债。就算是日本政府，不敢卖，那么也不排除人家私人卖掉。而美国联储局对国债的购买，就是QE2要在六月份到期。这个时候，美国国债的三大买家，就只剩下中国一家主持大局了。

美联储已经买了大概4千亿的美国国债，现在美国政府发行的国债中间，有五分之三的大多数，靠的是美联储印的票子。因此日本和美国的关系，因为核辐射而产生摩擦，在六月份到来的美国国债危机上面，估计会变动更加剧烈。

而日本核辐射产生的全球过度恐慌，会不会对日本出口产品，不是说只是食品和蔬菜，还包括各种电子原配件等其他产品，造成市场滞销的局面，从而引发产能的危机，对正在布局产业升级和经济转型的中国，是一个大的机遇。
