# -*- org -*-

# Time-stamp: <2011-08-26 11:43:49 Friday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话84：再谈利比亚

[2011-04-27 14:28:54]


看了一位新闻界工作的朋友，发给我的邮件，发现大家对利比亚的博弈，还是没有搞清楚。因此本来要谈美国的黄巾军，现在就停一下，把利比亚的事情，讲清楚一点。

要清楚利比亚的事情，先要了解一下， *欧洲的天然气困境* 。

本来欧洲人为了打破被俄罗斯卡住脖子，准备开通叫做纳布科（Nabucco）的天然气管道，把中亚的天然气，通过格鲁吉亚、土耳其给运出来。但是现在这个建设计划受到了很大困难，基本上面临有可能夭折的命运。

这条长3300公里的管道，是计划每年输入310亿立方米的天然气，本来预算成本是111亿美元，不过根据BP的研究，现在估计成本飞涨了一倍，大概到了200亿美元的水平，就是说这个管道，可能没法盈利。

最要命的不光是成本问题，而且一个管道，一直找不到气源供应商。根据欧盟能源主管Holzner的意见，如果今年也搞不起来，那么这个项目就玩完了。

要解决难题，只有两个选择。第一个就是放弃这个计划了10年的项目。但是这样的话，欧盟的能源安全是一个问题，而且还丧失在越来越重要的里海地区的影响力。

另一个选择，就是和其他线路合并，来降低成本，并吸引其他的投资者和供气商。 *所以问题的关键，不在是政治上，为欧盟获取从俄罗斯能源独立，而是要考虑这条线的经济效益。*

欧盟现在的供气商，主要是4个。俄罗斯是最大的，供气41%。第二是挪威，占27%。第三是阿尔及利亚，占17%。第四是尼日利亚，占5%。大家都知道在 2006年，俄罗斯和乌克兰吵架，在2009年，俄罗斯和白俄罗斯吵架，都导致了俄罗斯停止输气。这两次争端使得欧盟的东部地区，严重缺气，迫使欧盟不得不寻找其他天然气来源。

*正是在这样的一个大背景下，利比亚代表的北非地区，才对欧盟非常之重要。* 比如说，利比亚因为缺乏勘探，有很大的天然气潜力。现在知道是1.5万亿立方米，但是勘探的可能，也许会超过20万亿立方米。

而且欧盟，尤其是法国想搞的地中海俱乐部，到处都是一片赞成之声。唯一的障碍，就是利比亚，更准确地说，是卡扎菲。

因此法国在这次西方的干预中，跳得最高、喊声最大，是目标非常明确的。那就是如果趁机干掉卡扎菲，树立起一个亲法国政府，那么地中海俱乐部自然是水到渠成，而利比亚的能源，自然是欧洲人的囊中之物。

那么如果卡扎菲是个不死的小强，如果没有办法把他给搞下来的话，最起码形成的共识，就是你不能去动班加西，最后谈判的结果，最起码也要把利比亚的能源分一半出来吧。

当然再不济的话，欧洲人也有红脸和白脸。法国扮演的是政治、军事和外交的角色，而德国扮演的是经济和贸易的角色。德国在这件事上采取中立（那就是所谓亲卡扎菲），就会让将来法国控制东利比亚，那么德国就可以来和西利比亚和卡扎菲打交道了。

倒是英国人这次也折腾的比较厉害，不知道内部的交易如何。因为英国人用放回泛美航空爆炸案的主谋，为BP争取到了能源利益，那么这次出动，不排除为了保底，甚至可以加码。而如果出现胶着状态，导致卡扎菲必须下台让位给他的儿子赛义夫，那么以小卡和英国人之间的密切关系，也导致了英国人双边通吃。

如果欧盟可以达到目的的话，那么俄罗斯的利益就会相对受损。无他，你俄罗斯就成了欧盟的张屠夫了。没有你，人家也不吃带毛猪了。所以俄罗斯一定会跳出来搅局。

可是对中国来说，有什么利益损失呢？其实没有。因为中国在利比亚的15万桶油，其实很少。而且东部叛军控制的管道，还在继续出油，通过卡塔尔的安排，中国还一直拿着呢。

至于中国的建筑合同，那些苦力活，那(哪)是人家欧洲的好吃懒做的大爷们干的。所以一旦战局平息，又得找中国公司了。而且还得搞战后重建呢。

最主要的就是，如果欧盟在北非找到了替代的能源来源，那么欧洲人在中亚就不比(必)这么玩命了，这个会导致中国的能源输入更加安稳。

*所以欧盟成功，对中国有百益而无一害。* 而且中国和法国，在欧洲的势力范围已经差不多谈妥了，中国好好经营撒哈拉以南，以原材料为主打。法国经营撒哈拉以北，以天然气主打，大家相干无事。你不要冲击我的奥运会，我不去冲击你的家乐福。

*那么美国在这件事情里面瞎起哄，就是犯傻。* 美军的意图相当明确，倒是国会的那帮傻冒，向麦坎因这样的在瞎哄呢。希拉里犯了一阵傻，似乎有收敛的迹象。纽约时报大炒利比亚叛军的一个重要首领，是呆过关塔纳摩监狱的事情，算是为奥巴马政府脱套。不过美国自己咋呼惯了，想彻底脱身不可能，奥巴马又被萨科齐和卡梅隆给套实了，所以采取磨洋工的招数，是一定的了。

倒是看美国在叙利亚的反应如何，因为如果说美国想干预中东，那么叙利亚是首选。不过叙利亚的逊尼反对派闹事，某种程度上，是对什叶派在巴林和沙特闹事的一个回应。 *阿萨德虽然不是什叶派，但是他的盟友黎巴嫩的真主党和伊朗都是* 。

最后的结果，可能是要靠沙特和伊朗的沟通为妥协结果。
