# -*- org -*-

# Time-stamp: <2011-08-25 11:35:48 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话59：圣人不死，大盗不止

[2011-02-20 04:18:43]

看到中东北非一片狼藉，开始有人大批奥巴马政府外交政策好无章法。

因为俺上班下班的时候，在车上会听一些电台节目，所以知道这次的大变局，并非是空穴来风。

其实关于北非和中东的年轻人，尤其是大学毕业生，失业问题严重的报道，前一两年就被美国的新闻界关注。俺自己听到的就是NPR关于突尼斯的一个专题报道，其中采访了大批失业而无所事事的年轻人，那种情形，颇像中国70年代末和80年代初，就是说大批年轻人，在街上晃荡，暗流汹涌。

*只不过美国的情报部门好像是一帮白痴。自从911之后，情报体系得到大幅度扩张，各种信息都收集得非常齐备，但是分析问题的能力居然如此之差。*

大家其实都看得出来，自从911之后，中东和北非的暗流就开始凝聚，美国的应对之策，就是从小布什开始的 *推进民主化* ，也不想想因为美国同以色列的一条裤子关系，再加上美国长期在这些地方支持独裁政权，民主化的结果，美国非死不可。

奥巴马的外交政策，某种程度上是继承了小布什的模式。当然唯一的区别，就是从动武变成了动文，从动手变成了动口。

小布什的动手政策，某种程度上是削弱了埃及、沙特和巴林等等独裁政权的控制力，而增加了伊斯兰世界的宗教极端势力。这个政策最后叫停，是因为巴勒斯坦民主选举之后，美国视作恐怖组织的哈马斯上台，给以色列的政策添加大变数。

而黎巴嫩本来按照欧洲人的安排，是保证基督徒和穆斯林势力平分政治权力，但是民主选举一推行，人口占优，而且在不断上升的穆斯林势力，就会以真主党为代表，获取大部分政治权力。

奥巴马政府接受了动手不是好办法的判断，但是开始了动口的路子。这个路子就是希拉里号召的网权大于主权的路子。代替美国的精确制导导弹和飞机轰炸的，是谷歌、推特和脸书。

这些本来是用来在这个地区对付伊朗和叙利亚（利比亚已经不再是主要目标）的招数，因为不能被人家说是双重标准，因此这些招数也虚晃了一下，同时对准埃及和沙特等美国盟友，装腔作势地做一些姿态，然后就狠狠对准伊朗和叙利亚开火。

其实奥巴马和希拉里不明白，等你的老虎一出笼，哪里管是你盟友和敌人，都会一口气咬下去。

*而且伊朗面临的压力一大，就会导致穆斯林世界中的逊尼派和什叶派的关系紧张。* 这个关系紧张的结果，在伊拉克已经看得明明白白。要是进一步恶化，那你的巴林这个美军第五舰队总部所在地、也门和沙特，都会没有好果子吃。

结果就是美国的燃烧弹一投下来，防备美国想做到刀枪不入的伊朗和叙利亚，抗打击能力反而比较强大。而美国的盟国，因为在美国的压力下，反而开了被搞乱的口子。

比如说埃及的前总理，就是IT方面的专家。而他推动的改革，包括在互联网和通信上的很多建树，就为这次埃及年轻人的造反运动，提供了美国供应的大杀器。

结果就是埃及政府对这些大杀器缺乏足够的控制和监控，因为这也是美国要求的嘛。导致了埃及和巴林这些美国盟友，比伊朗和叙利亚这些美国敌人，更耐不住这些大杀器的打击。最后的结局，可能就是叙利亚这样的国家，可能比埃及对反对人士很暴力，但是反而受到的冲击更小。

那么就是美国的民主武器，在中东和北非，极有可能，想要颠覆的国家一个也没有成功，但是自己想控制的国家，也许会全部变色。

其实就算你把伊朗和叙利亚推倒，就像美国在伊拉克推翻萨达姆一样，你也不能保证这些地方，不会出现一个更宗教极端化，更反美的政府。

所以现在美国的不少老的战略家，包括以色列的不少人，都对奥巴马政府颇为恼火。因为奥巴马这种又不敢得罪年轻示威人士，又不敢支持自己的独裁盟友，得到的结果，就是双方都不鸟你，然后不论哪一方占了上风，都不会对你有好处。

*其实中东和北非的问题，非常非常简单。就是如果美国的以色列政策不改变的话，美国就不会受到阿拉伯和其他穆斯林国家的欢迎。*

看着美国在联合国要否决120个国家支持谴责以色列的法案，就知道什么叫做犯了众怒。只要美国利益不能清晰地和以色列利益做一个切割，你美国就不可能在这些地方，得到民众的好感。

因此在这些地方搞民主，对美国来说，就是找死。真正要搞定的，不是民主，而是民生。

如果美国可以帮助这些国家搞好民生，或者施加压力，让这些政府高官们少拿一点，多向底层分一点，使得人民的生活好过一点，那么也许减轻社会的不满情绪，保持这些地方的稳定，对美国的利益反而有大利。

但是奥巴马这一代人，不知道为啥，对历史和地缘的理解，让人觉得非常的幼稚。

其实从年龄上来讲，奥巴马比俺还大几岁，但是他和这一代美国精英的认识，真是不敢让人恭维。

比如说他对以前的国家安全事务顾问的选择，就是一大败笔。美国海军陆战队的琼斯将军，曾提议过在伊拉克战争期间，美国应该动用土耳其军队，进伊拉克维稳，来帮助美国。

这就是对历史一窍不通的白痴，才可以想出来的臭招。

看美国的外交政策，在看国内的斗争，真是除了摇头，是没有别的可说了。
