# -*- org -*-

# Time-stamp: <2011-08-25 10:35:12 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话50：为啥2016年是一个夺命年

[2011-01-26 17:23:05]



大家知道，俺在2005年开始坚信，全球经济危机即将来临。而当2008年，果真发生的时候，俺的看法就是，2016年，是一个要命的夺命年份。

为啥这样看呢？是因为起源于俺对1929年大萧条的历史的思考。

大家看到的是2012年，可能会是一个坎。

因为2012年有不少不确定的因素。比如说中国的房地产泡沫，会不会在这个时候到达高潮，出现日本1987年的大爆炸。

如果这个局面出现，不光是中国有大动乱，那么整个世界经济也全部玩完。

很简单，因为2008年经济危机之后，美国的经济开始步入日本式的停滞，全世界的一个经济发动机熄火了。如果你中国在2012年，再歇一把火，那么世界的另一个经济发动机，也玩完了，你就像一架飞机，两个发动机都死了，就等着看着飞机坠毁，大家寻找黑盒子吧。

虽然俺对中央政府在房地产市场上的反应迟钝颇为不满（看俺的博客，2009年秋天，已经建议他们动作了，结果是到了2010年春天才开始动作），但也要考虑到目前房地产的前进方向，在一线大城市，最后是小幅下跌，在二线和三线城市，最后是小幅上涨，总之，要保持在一个温和的浮动区域。

*国家在廉租房和经济适用房上面的投入，起到了保障城市的贫民和弱势阶层，而且在农村政策上的增加补贴，都改善了农村里面的农民。*

*所以国家的地盘还是稳固的，毕竟可以造反，而没有多少东西可以损失的人群，主要在这里。*

当然好似老鼠跌进风箱里，补助房又不够格，商品房又买不起，两边都够不着的城市白领，尤其是大城市，比如说北京、上海、广州和深圳这些地方的白领，就是目前被政策遗忘的人。

虽然说这些人是互联网的主要力量，因此可以看到网络上的“民怨”铺天盖地，但是好在大家只是键盘做刀枪，论坛做战场，不是在街头去打砸抢烧，倒是不必担心即时的危险。

只不过毕竟这个人群，是未来国家发展的主要有生力量，如果不能考虑到为他们建立发展的空间，而变成了带路党的发展基地，那对中国的长治久安，也是一个问题。

最近不少的朋友，比如小mang兄，开始忧虑中国会出现滞涨的局面。

*涨是躲不掉的，因为2008年的金融危机，其实已经是信用过于膨胀的经济危机。* 但是世界各国，面临危机之后的信用紧缩，采取的都是两宽—就是财政和货币都放松的政策。这样的政策施放出来，肯定就是全世界游资泛滥，能源、原材料和食品，全部疯涨。

在这种情况下，一个国家采取紧缩的货币政策，就算是你在加上铜墙铁壁，固若金汤的资本流入控制，也很难彻底抵消通胀压力。

要解决这个办法，也是回答前面说过的台湾网友问的第二个问题，就是 *如何获取相对比较廉价的资源，来支持中国发展，就必须在两方面，采取步骤。*

第一个就是替代性能源。比如说中国自己在水电上，有不少建树，现在在核电上也有一些突破。大概俺看到了三个方向，一个是对核废料的处理循环再运用技术。一个是和法国合作，获取核燃料。一个是和日本东芝合作，开发核燃料提炼技术。

大家要知道，从中国的北疆，到哈萨克斯坦，是一个主要的铀矿。

当然中国自己有不少的煤，但是现在用煤来发电，已经政治上不正确了。

*只要中国在电池技术上有突破，那么基本上的交通需求，从高铁、汽车、地铁、公车、摩托等等，都可以电动化。当然飞机，估计要开发液体氢气。*

第二个就是替代性原材料。中国在各类金属矿石上，比如说铁矿、铜矿等等，对外依赖度及其高，必须考虑开发新材料来替代某些金属运用。

说到底， *中国的矿产，要么主要来自于非洲，要么被澳大利亚这样的靠不住的国家垄断，将来会出大问题的。北非和中东，随时都可以乱，那么中国依赖的石油和矿石，都会受到打击。*

因此中国要解决经济可能发生停滞的问题，其实是可以和发生涨的问题，一起解决。那就是 *不光要转换经济发展的模式，还要转换生活的模式。*

*就是说必须在提高能源使用效率，和能源消费方式上做出重大的变革。*

一句话，要把经济的发展，着重于依赖能源消耗带动的粗放型模式，走向依赖高效率能源使用，靠人的智力资源，靠发明创造，靠灵机一动，这样的脑力带动的精工细作型模式。

俺在2008年，就提到过，中国的4万亿经济刺激方案，非常有必要，但是不要寄望过高。而是要考虑到其实效，就是3年而已，那就是2011年底。

这个刺激方案，要打下来的是一个硬件基础。而真正的发展，是要依赖于民间的中小企业，在这上面的软件发展。

*如果把这个方向，结合中国的中部和西部发展，结合送电下乡、送技术下乡，送贷款（不是那些挂羊头卖狗肉的高利贷小额贷款）下乡等等，结合高铁网络建设，结合村村通公路，结合建设小城镇，那么中国是不太会出现滞的局面。*

然后就是俺在《梦幻泡影》里面提到的中国的马歇尔计划（东部帮助开发中西部计划），比如说上海、江苏和浙江，在安徽皖江搞的飞地经济等等，都可以保证中国的经济增长。

总之，就是要保证中国自己不要乱了阵脚。

*同时，希望美国不要乱。* 因为美国一乱，那么出现希特勒那样的，希望靠对外战争，来解决国内危机的人物，就有机会。而这种情况，也对中国的发展有影响。

但是毕竟，美国的局势，中国无法掌握，唯一希望做到，就是独善其身。J20等一系列杀手锏的出现，其实就是为这样一个2016年的可能局面做准备。

*所以说J20的成军，应该是2015年。*
