# -*- org -*-

# Time-stamp: <2011-08-25 20:22:16 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话72：自作自受兼害己害人

+ (上)

[2011-03-15 13:35:30]


今天看到日本的福岛第一电厂，终于接近全面核融化了。

首先要说明的是，这次的核子大灾难，不仅仅是天灾，而是人祸。

日本核工业的信用本来就非常差，之前的二十来年，发生了至少三到四次核事故，但都被利益集团，加上日本的政府和媒体，一起给捂盖子捂住了。

这几天逐渐透露出来的不完全的信息，其实后备的柴油发电机并不是被海啸给灭掉了。而是在设计中，这些反应堆的备用电力交换器，就是当正常电力失常之后，后备电力转换上来的设备，是建在最低点的。

而日本用来保护这些电力设备，靠的是防水墙。结果地震之后，防水墙裂了，海水就灌了进来。

所以后备发电机运作了不到1个钟头，在海啸还没有冲来的时候，就已经挂掉了。

这之后，靠消防车直接往反应堆里面灌水，因为温度很高，而且压力大，这种做法已经被不少核子专家质疑，是否有用。不过大家，都不好意思公开宣称无用，以免引起不必要的恐慌。

在这个时候，海水进去，马上就蒸发，就必须另一头放含有核辐射的蒸汽出来，减低压力，以便于更多的海水打进去。

这个是发生在一号堆和三号堆的事情，就是虽然发生了氢气爆炸，但是还没有迫在眉睫的危险。

可是二号堆，就没有这么幸运了。一个泄漏蒸汽的阀门失灵了，导致海水进不去。另一个可能，就是这个堆的底部已经有了裂口，导致海水泄漏出来，水平面上不去。

总而言之，二号堆恐怕是已经全部溶解了，日本已经开始撤退抢险人员。这么看来，其他两个堆，没有人抢救，也会全部溶解。

最要命的是，日本人采取了燃料，不是大家通用的铀，而是铀和钚混合体。这样做，增加了安全危险。

其实这也是日本一直灭而不宣的“和平核能”政策，就是 *通过所谓和平的利用核能，日本名正言顺地生产和储存了可以制造几千颗原子弹的钚，再加上日本的技术，可以快速地安装原子弹，用来制衡它认为有威胁的国家。*

其实说到底，日本人的这种算盘，和伊朗现在干的事情，是差不了太多的。

当然主要区别，就是人家伊朗人选择的地方，可不是强地震地带，也不是强海啸地带。

而现在这几个反应堆出现彻底融化之后，会对日本东京地区带来什么样的核辐射影响，是一个令人担心的问题。

谈到这个问题，自然不能回避中国的核安全问题。

中国现在运行的核电站有两个，一个是在广东的大亚湾，其实是两个核电站。一个是大亚湾的两个机组，一个是岭澳的4个机组。这些机组采取的是法国的压力堆和英国的常规岛设备，是属于三代核电技术，比日本这次出事情的二代要安全不少，毕竟是经过了美国三里岛和苏联切尔诺贝利的事故之后，大家吸取经验，进行了改进。

另一个是在浙江的秦山核电站，是中国利用的压力堆的技术自己研发的。

现在进行建设的，就有山东位于青岛北部的海阳核电站两个机组，和浙江唯一宁波南部的三水核电站两个机组。这四个机组，是用了美国的西屋的AP1000技术，是属于三代半的技术。

另外就是位于广东台山的两个机组，是用了欧洲的EPR技术，也是最先进的三代半。

中国的核电站，选址和日本非常不同，是绝对不能在地震带上面。

其次就是因为太平洋岛链的屏蔽作用，中国沿海基本上没有太大的海啸威胁。

不过话也不能说得太满。 *俺自己的估计，现在中国已经运行和正在建设的核电站，估计没有考虑到飞机撞击的因素，而这个因素，其实应该好好考虑。*

毕竟自从美国的911事件之后，劫持民航机，来撞你的核电站，是一个非常现实的安全隐忧。如果借助这次日本核辐射的事件，引发中国政府对此的重视，当为好事。

+ (下)

[2011-03-15 14:48:28]



另外在日本的这个核灾难中，大家其实中了调虎离山之计。

因为真正危险的东东，并不是核燃料的彻底溶解。

当然这个也是问题，但是更要命的是， *燃烧过的核废料泄漏，更要命* 。

美国长岛的布鲁克黑文国家实验室，在1997年的时候，做过核废料泄漏的模拟。得出的结论是， *一次严重的单个反应堆泄漏，导致的结果是在500英里的区域内，立即死亡的人数，会达到100人，而最终导致的综合死亡人数，是13万8千人。*

*而整个受到辐射影响的区域，是2170英里，最终的经济损失是5460亿美元。*

这个研究用的反应堆模型，就是日本现在出事的沸水堆。

日本福岛第一电厂的4、6和6号反应堆，因为维修，在地震发生的时候并没有运作。但是因为这些核废料需要放在水池里面，靠冷却水继续冷却。而这一次，因为整个冷却系统失灵，第四号反应堆的水干了，人家自己发热着火了。

因为这个水池，通常是在最高的地方，这一次1、2和3号堆，都发生了爆炸，把建筑物的顶给掀翻了，所以这些核废料都可以直接接触大气。

当然这些核废料多快时间开始发热，也要看数量的多少，和新旧程度。如果比较新的话，那么几天到一个星期，就会变热，然后一个星期后，就危险了。

不过日本人对这些核废料的情况如何，现在是守口如瓶。
