# -*- org -*-

# Time-stamp: <2011-08-25 20:55:35 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话77：苍天已死，黄天当立


[2011-03-28 10:12:53]


在阿拉伯国家里面，有两个国家，是什叶派占大多数，但是逊尼派当权的。一个就是现在动乱的岛国巴林，一个就是以前萨达姆控制的伊拉克。

这两个国家什叶派大概都是占60%的总人口。而其他的国家，比如说也门，是45%，科威特是30-40%，叙利亚是20%，沙特是10%，主要是在产油区的东部省份。约旦本来没有太多什叶派，但是伊拉克战争一打，跑过去不少难民，就增加到10%了。

*伊拉克之所以重要，是因为这里是逊尼派和什叶派势力冲突的关键。* 在萨达姆时代，逊尼派能够压制住什叶派，并通过两伊战争，向伊朗推进。

在1950年代后期的伊拉克，针对英国人支持的君权，就出现了两派反对势力。一派就是什叶派的达瓦党，提议用伊斯兰神权，加上社会主义来解决穆斯林世界的发展问题。另一派就是逊尼派的阿拉伯复兴社会党，企图以统一的泛阿拉伯民族主义和社会主义来解决问题。

后来虽然复兴党在叙利亚和伊拉克都上了台，但是复兴党内部的军人力量逐渐壮大，最后走向了分化，而出现推翻君权之后，并没有实现民权，却演变成了军权的模式。而且这个以反对西方殖民统治和帝国主义压迫的民族独立解放运动，既没有形成统一的阿拉伯，又在和西方对抗的过程中，慢慢演变成西方的傀儡政权。

*而当年没有被军人们推翻的君权政府，在阿拉伯国家里面，由于西方国家的强力支持，国王们屁股下的坐垫，暂时还坐得暖暖的。倒是推翻了君权的国家，个个现在都下场堪忧。除了认贼做父的穆巴拉克被抛弃、萨达姆被吊死、近几年讨好西方的卡扎菲被轰炸，连唯一没有屈服的阿萨德还在叙利亚苦苦支撑。*

在萨达姆被推翻的伊拉克，后来被复兴党残酷打击的达瓦党重振旗鼓，开始掌控伊拉克局势。而他们打出的大旗，就是以神权和社会主义的结合，来带动穆斯林世界的复兴，最起码在伊朗得到了成功的实践。

而当什叶派的势力，和达瓦党的壮大，造成了新一轮的穆斯林革命，那么在这第三轮的穆斯林革命风潮中，就造成对沙特阿拉伯为主的君权统治国家的强大挑战。

因为很简单，对笃信宗教的民族和文化，君权和神权的争斗，谁占优势，是不言而喻的。

阿拉伯国家，一个痛苦的历史经历，就是如何制止西方强权对这些国家的军事干预。

今天的利比亚，面临的是伊拉克同样的问题。当然之前的埃及，即使在纳赛尔的强势时代，也没法避免受到英法以的三国联军的侵略。

因为 *西方人基本上是一个只看实力，迷信暴力的人种。* 中国能够自己站起来，是靠的朝鲜战争上了血战。而今天的阿拉伯国家，还没有一个可以做到这一点。不要说西方国家的联合暴力，就是一个西方支持的以色列，也毫无办法。

而在中东和北非，唯一可以自保，并且和西方叫板的，就是什叶派的伊朗。当然黎巴嫩的什叶派真主党民兵，在和以色列的战争中，也表现可圈可点。

如果伊朗能够在核危机的斗争中，成功发展核能利用技术，达到 *准核武国家* ，就是不拥有核武，但是马上可以制造核武以自保，那么对阿拉伯国家的刺激，将会相当大。

敬拜阿拉、对抗以色列、不受西方干预，如果这个是神权世俗国家伊朗，产生的后果，那么估计，新月带什叶派的兴起，一定会刺激逊尼派阿拉伯国家，产生自己可以竞争的制度，而这个就是要看 *埃及的穆斯林兄弟会* 是否有作为了。

世界上的事情，通常都是好事成双，祸不单行。当年中国的秦朝统一中原，结果北边的匈奴就统一大漠，而达到势力的均衡。

如果什叶派新月带的成型，形成一个新的地缘政治势力，那么在受到这一波革命浪潮冲击的军权和君权国家，要形成新的势力平衡，只有两条路可以选择。

一条就是由穆斯林兄弟会为代表的逊尼派神权道路，其实就是走波斯人伊朗神权和世俗权力结合的方式，或者走土耳其人那种世俗和神权结合的方式。

当然另一条就是走美国和西方提供的假民主道路，或者又名为“没有穆巴拉克的穆巴拉克主义”道路。不过名义上的选举啊，国会啊，就是伊拉克和阿富汗折腾过的那一套东东，总是要搞一搞。

那么对埃及等国家而言，当你的国家混乱，大家希望寻找一种办法来稳定，你觉得会去从自己的文化和传统里面，去寻找方法和安慰，还是会试一试别人给你开的一剂药方？

俺倒是觉得，前一剂药比较靠谱一下。因为很简单， *所谓选举的民主，其实是把大家的争议放大，给一套规则来博弈。* 但是要是大家缺乏维系的共同纽带，那么这种博弈最后的结果，就是巴尔干半岛那样的。

而要保持共同的维系纽带，那么人家传统里面的宗教因素其实最厉害。那是一种教大于国的概念，是一种可以跨越国家、族群和部路的隔阂，解决阿拉伯国家过于分散，老是被外敌各个击破的法宝。

总之， *中东和北非，这次革命的主要诉求，其实是彻底摆脱被西方，尤其是美国控制的地位，寻找自身主体独立的一个延续。* 正如本拉登一直鼓吹的那样，西方控制这个地区，靠的是两股力量，一个是阿拉伯国家自身的独裁军权和君权，一个是外来国家以色列。他相信，只有彻底端掉这两股势力，阿拉伯人的独立和解放才可以真正实现。

*那么在这个大背景下的西方军事干预，会导致亲西方的假民主势力壮大，还是反西方的神权宗教势力壮大，对未来中东和北非的走势，以至于整个世界格局的变化，都有着深远的历史影响。*

而中国的首要应对，还是俺去年的一系列博文中提出的那样， *保证自己在新疆把屁股坐实，避免未来被别人翻盘。然后考虑有限度地西进，以里海作为一个考量，就是瞄准中国唐朝时候的目标。至于更远的中东和北非，争取护住撒哈拉沙漠以南的利益，其他的地方，还是要打酱油为主。*

*不求有功，但求无祸。不求有利，但求无害。*
