# -*- org -*-

# Time-stamp: <2011-08-26 09:12:08 Friday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话87：美国战略转变（二）

[2011-05-05 15:40:00]


之所以上一篇把Y先生的身份写出来，而不立即对他们的建议发表意见，是希望各位读者可以先读一下人家的原文，然后在没有我的影响之下，有些自己独立的思考。

然后大家功课做足了，就可以一起讨论一下不同的意见了。

其实Y先生的文章，是挺生涩的。充满了不少似是而非的大词汇，就是战略界的专家，恐怕也读到乏味。但是基于他们的身份，就是说他们的意见，其实是广泛地征询了美国军方高层的意见，以他们本身是美军最高决策层—参谋会议联席主席的高级幕僚的身份，大致是既代表了将军们的意见，又不想让高级将领们担上军人干政的恶名。

毕竟上一次的军人干政，还要回溯到 *麦克阿瑟将军和杜鲁门总统的对抗* 去了。

不过很多人不知道，为啥要用Y先生？其实是在1947年的时候，出了一位X先生。X先生，其实就是美国外交官乔治-坎南。他曾经出任过美国驻苏联大使的副手，因此和当时的美国政府对苏政策有分歧。

和当时二次世界大战刚刚结束，美苏两个大国好歹还是盟友，因此当时美国外交界不乏希望以外交和接触的关系，来寻找和苏联和平共处之道。而坎南的观点，则是美国永远都不应该把苏联当作一个伙伴（partner），而只能当作一个对手（rival）。

因此美国的对苏政策，必须是强力的围堵。在军事上就是针锋相对的硬碰硬，来防止苏联的步步紧逼。而在经济上，则必须显示出“自由世界”（Free World）的实力，来击败苏联。

可以说X先生的思想成为后来美国冷战的主要指导方针，也成为了美国今后数十年的外交主要路线。

但是Y先生认为，这种围堵的思维应该改变了。

因为Y先生认为，世界已经不是X先生认为的那种封闭的世界。在那个世界里面，美国可以控制和决定整个世界如何运作。然后就根据自己设计的蓝图，来决定哪些是现存的威胁和潜在的挑战，然后就当头一击，把这些威胁和挑战和消灭掉。

Y先生认为，现在的世界是一个开放的世界，美国已经没有能力完全施加影响，因此就无法像过去那样去应对挑战。而这就是美国面临的第一个大问题，就是可持续的问题。

所以美国的第一个变革，就是必须让围堵（Containment）变成持续力（Sustainment），其中的关键，就是要从控制（control）变成影响（influence）。而这种影响必须是有信用的影响（Creditable Influence）。

我的看法，就是你在阅读Y先生的观点的时候，必须脑袋里面有一个中国的形象在那里，才便于理解。

所以关闭的系统，指的是当年冷战的时候，苏联自己的一套和东欧等国家自成体系的经济系统，和美国以及西欧等国家自成体系的经济系统，其实并没有太大的关联。大家的资源、人力和市场的配置，是毫不关联的。

那么美国在围堵苏联的时候，对自身的经济运作其实并没有太大的影响。

但是考虑中国这个敌人的时候，情况大不相同。因为美国领导的所谓自由世界，已经换了一个马甲，叫做“国际社会”（International Community）。而美国资本全球逐利的结果，就是所谓资本自由流动的全球化，已经导致了最起码中国的经济和美国以及其他美国主要的盟友，比如说欧洲、日本、加拿大和澳洲等等，具有很大的关联和依赖。

所谓和则两利、斗则两害，这种情形导致美国战略界的围堵派，或者说硬性围堵派（软性围堵派则仍然有理论空间）的政策建议，完全没有现实可操作性。

这样的一种认定，确实算是对希拉里主导的外交路线的反对。

不过是否这种开放的国际经济体系，会如Y先生认为的那样，成为未来的趋势呢？也不尽然。毕竟Y先生是纯粹军人，不一定对经济有足够的敏感性。

这里就拿一点我自己的私货出来。看过我在2008年美国金融危机发生之前写的《大国游戏》，在结尾的两篇，表明了我对未来世界经济走向的看法：


 
#+LaTeX:{\kai
#+HTML:<a>

“世界经济发展到今天，全球经济的驱动力正从西方衰退，而转移到新兴的经济体。在未来的数年中，美国和西欧有非常大的可能会同时陷入经济衰退，中国和印度会很容易的成为西方政界和媒体的替罪羔羊。而西方民粹政客将以制造业工作的流失，归罪于全球化和发展中国家，而导致西方贸易保护主义的兴起。

在这种背景下，西方国家会一方面施加压力让中国开放市场，另一方面就会用市场和非市场的方法，关闭部分内部市场。比如在美国可以通过媒体夸大中国制造产品的问题来增加成本，或者是通过国会的国家安全听证会，来限制中国的投资机会，迫使中国只能投资有利于美国，但对自己无益的地方。欧洲则会用各种复杂的欧盟标准，限制中国产品和品牌的进入，迫使中国厂家永远只能做欧洲品牌的代工，让欧洲商家拿高附加值利润。

国际贸易组织WTO估计在今后数年，将会变成一个只能接受各方争吵的论坛，而不会对世界贸易的促进起到真正的作用。在过去，WTO的局势和划分很清晰，就是发达富强国家和发展中贫穷国家利益争执，界限分明和逻辑清晰。但是现在情况却大不相同，以中国，印度，巴西，南非为代表的新经济体，成了第三种状况，就是经济总量大，国富，但仍是发展中国家，民穷。发达国家当然不会那么轻易让步，因为他们认为没有理由，要让他们的弱势经济向你强势经济输血，而要求这些发展中的大国让步，也不容易，为什么这些仍然贫穷的人民，要向富有的发达国家人民让利。

其结果就是，国际贸易体系将会破裂，虽然保住个名不符实的虚名，就会象世界银行和国际货币基金会一样，退出历史舞台。而世界经济就会日益趋于地区化和双边化，为中国在世界经济中的新地位，提供一个活动的空间。”

#+HTML:</a>
#+LaTeX:}

那么，今天的美国战略界，是如何考虑我3年前预测的这个问题呢？
