# -*- org -*-

# Time-stamp: <2011-08-25 21:28:44 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话82：美国黄巾军（1）

[2011-04-20 14:39:39]


看到这个题目，大家就知道，这篇文章是还读者债的。其实是应该去年就应该写的。

不过谈这个问题之前，有几个事情先交代一下。

第一个是关于 *中国能源问题* ，天然气是一个中间过渡环节，所谓stop gap。有了这个中间过渡，那么有赖于技术上的突破，也许更安全的核能，比如MSR等等，就有机会填补空档。

第二个是关于 *利比亚局势* 。自从美国把指挥权交给了北约，躲到了大队人马背后，利比亚干预阵营中的法国和英国，颇有骑虎难下的姿态。虽然奥巴马仍然跟着萨科齐和卡梅隆起哄，要卡扎菲下台，但是美军显然不太用命。

在歧视女人很严重的美军，居然任命了一位女将军去指挥对利比亚军事行动，可以看作是美军对总统动武的不满。前几天，美国前国务卿贝克上电视台专访，明确表示反对美国在“与美国国家利益无关的地方”大动干戈。随后，老贝和基辛格合作撰文，在《华盛顿邮报》这个偏右的报纸上发表文章，反对继续介入利比亚事务。

而代表民主党偏左派的《纽约时报》，则派出了其北非驻地主任，上电视台向美国人介绍情况。这位老哥刚刚去了非洲的马里，发现那里不少年轻人，现在忙着筹款，添置武器和作为盘缠，要自愿去利比亚为卡扎菲大叔上战场。

这位老哥问，为啥你们这么支持卡大叔？人家说，你看看俺们的首都，最漂亮的地方，那个政府机构建筑群，就是卡大叔出钱修的。所以名字叫做卡扎菲政府建筑群。

而且当年卡大叔要搞非洲合众国（United States of Africa），因此从利比亚的石油收入中间，拿了一些零头，到这些贫穷的黑非洲扶贫，让大家明白，如果非洲成为一个国家，那么富裕出油的地方，就有责任拿钱去支持贫穷的地方。

看一看其他非洲国家，比如说尼日利亚，就在马里隔壁，也没见他们分点油钱过来。而卡大叔的无偿援助，确实使得不少贫穷的黑人家庭脱了贫，所以你西方人要来对付俺们的卡大叔，当然大家要拿起武器了。

除了卡扎菲的援助，获得了不少黑非洲的人心，另外一个让这些年轻人佩服的地方，就是老卡大概是非洲唯一一个国家领导人，敢不畏强权，和西方叫板，这个也吸引了不少追随者。

在这样一个背景之下，如果美军不出兵，光靠法国和英国的地面部队，想干掉卡扎菲，并不是一件易事。 *就算你可以把第里波里打下来* ，推翻了老卡的政府，那么支持老卡的过百万部落群众，再加上黑非洲跑过来几万志愿军，人人手上持枪，那么占领军的结局，一定会比美国在阿富汗和伊拉克，更要糟糕。

搞得好，成了阿富汗，搞不好，成了索马里。然后各类军阀乱战，再加上基地趁机坐大，然后数百万难民冲击法国和意大利边界，那就真够你喝一壶了。

所以结果，就是一个，和谈。毕竟班加西等东部地区，不服老卡已经不是一年两年了，就算老卡可以打下来，也没法管制，唯一的办法，就是大家谈条件。

不过非盟的斡旋已经失败，因为交战双方的条件和姿态还太高，而且英法美的嘴巴还比较硬。所以最好的结果，是大家再拉锯一阵子，然后英美法的军费再花多一点， *等着自己国内被裁减的教师和其他员工，发现国家没有钱要逼自己失业，但是就不缺钱每天去打仗，那么怒火中烧，就像英国人那样，在伦敦街头放火了。*

最近通过《俄罗斯时报》等俄国媒体发出的信息，就是希望中国可以出手，正式出面主导这个和谈。因为俄罗斯认为，英法美已经在内战双方中选了边，没有资格出任中间的调停者。

而在联合国表决中，取中间姿态，没有在卡扎菲和叛军之间选边的大国，除了中国，还有俄罗斯、巴西、印度、和德国。其实俄罗斯的言下之意，应该是中国和俄罗斯同时出手，必要就拉上其他几个，尤其是德国在利比亚的利益颇大，那么肯定 *在之后的利比亚重建中，哥们就可以分红。石油和建筑红利，自然中国会沾手，而军火方面，尤其是利比亚被北约炸烂的防空系统、坦克和装甲车啊，等等，就应该有俄罗斯的大头了。*

另外两个话题，就和美国有关了。一个是希拉里督促日本，不要因此而消沉下去。 *中国还需要你打鸡血来遏制呢，美国还需要你输血供应羊毛呢。*

另一个就是三亚 *金砖五国* ，继续推动南南合作，尽快向摈弃美元的双边货币结算转换。还有就是加强合作，防止各自经济受到西方放出来的洪水冲击。

而在这个背景下，就是美国的标准普尔号称，要是美国两党内斗不停歇，极有可能导致美国政府信用评级下降。在这个背景下的美国国债刷爆了卡，需要提供上限，就是这几个星期的斗争战场。

在遇到国外的金砖国家的步步紧逼，在国内美元的地位，也开始受到撼动。美国的犹他州率先通过法案，将金银重新列入货币行列，要打破美元的垄断地位。其他大概十几个州会陆续跟进。而这些州会不会出现替代纸币，将是一大里程碑事件。

另一个数据，就是美国去年的 *学生贷款* ，达到8千亿，超过了信用卡贷款总额，据信今年将超过1万亿美元。要是这些学生毕业后，有工作，那么大概可以在他们的子女上大学那年，才有可能还完。可是要是找不到工作，咋办？

说这些，就是让大家了解一下，美国黄巾军现在所处的大背景。
