# -*- org -*-

# Time-stamp: <2011-08-25 11:28:40 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话58：中东局势和发展道路（五）

[2011-02-08 17:25:41]

[新浪被和谐]

前面谈了一下对极左派的看法，主要是说明，如果左边的朋友们，要想为这个国家和社会，争取更多的公平（俺们就假定左派关注公平，右派关注效率，或者说左派关心穷人，右派关心富人），那么靠祭起文革这个大杀器是不行的。

因为大杀器一出，那么俺这样的中左派，都会被吓跑的。

你可以争辩说，后来的“四人帮”受到了不公平待遇，就如右派们争论说，当年的老干部们受到不公平待遇一样，对俺们这些草民，是没有太多干系的。 *本来就是党内特权阶层的路线斗争而已，胜者王侯败者寇* ，人家自己制定斗争或者博弈的规则，又轮不到小民们插嘴。

*神仙打架，谁打赢并不重要，只要不要拿小民们去垫背就行了。*

如果说对小民们生活有什么差别，那么至少是讨饭的人少了，是不是？或者说俺们上街的时候，留一个长头发，穿一个大桶裤，不会被人家当街给剪了，是不是？

有网友回复说，极左思潮在中国没有太多影响，还是极右比较危险。

俺倒不这样认为。因为极右派的一个大杀器，是人家美国如何如何。

而现在的美国，唉，真的不争气，让人家极右派们失望得紧。

记得伊朗反对党闹事的时候，被骂五毛党的人士们，说国家安定重要云云。被骂五分党的人士们，则高喊人民了、自由了、民主了，非常风光。

而现在埃及反对党闹事了，被骂五毛党的人士们，开始喊人民了、自由了、民主了，风光极了。倒是每天喊民主的被骂五分党的人士们，开始谈国家安定了。

*其实大家就是把马甲一换，上次的贴子，这次就可以重复发表，一点问题都没有。*

而大家没有看到的一个变化，就是南方系的悄然转身。

*而政治博弈的最后结果，主要表现在经济领域上具体操作。*

对美国来讲，社会不稳定、高犯罪率、贫富差距过大、宗教狂热等等，都受到了社会的容忍。而这几个方面，对其他国家，比如说欧洲各国和日本来说，都是不可以想象的。

但是美国社会在这些方面的缺失，付出的代价，换来的是更充满活力的财富创造和经济活力。

而日本社会则比较着重社会共识和服从，大概是西方国家觉得和个人自由南辕北辙的东西。但是日本社会因此而得到的是高度的社会稳定、低犯罪率、和经济上的巨大成功。 *正是因为日本社会对个人自律和集体合作的重视，才会产生出世界一流的精密制造工业。*

所以说中国和其他国家一样，也必须找到自己的取舍。

而俺希望中国将来的社会，最好是一个介于日本和美国之间的社会。那就是希望能够有日本那样的社会稳定，低犯罪率，和比较小的贫富差距。但又希望能够有美国一样的活力，和充满创造力。

无论如何欧洲一定不可以是中国未来的模式。

给大家一个机会留下评论。
