# -*- org -*-

# Time-stamp: <2011-08-26 09:29:28 Friday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话90：美国战略转变（五）

[2011-05-11 18:04:24]


在Y先生的提议里，一个重要的可以持续的方法，就是不能依赖于强力（power）来控制（control），而是通过实力（strength）来施加影响（influence）。

很显然，所谓强力，也可以说是人们谈的硬实力，是美国的军事力量，靠的是打仗、恐吓和封锁之类，让人家口服心不服。

而实力，更多的是软实力，就是靠自身的强大，比如说你的经济发展得好，人民生活过得好，失业率低，医疗健保质量高等等，来让人心服口服。

但是要 *靠自己的软实力来影响别人，靠的是自己的信用* 。而美国在全世界的信用扫地，美军大概是知道得最清楚。

前一阵美国保守派爱国者们纷纷扬扬、义愤填膺了一阵子，是因为一件有意思的事情。就是美国著名的卡通人物，超人superman，那个披着件斗篷，到处飞来飞去拯救世界人民的超级大英雄，公开宣布要丢弃美国公民身份。为啥呢？因为超人发现，当他去行善的时候，受到了世界人民怀疑的眼光，认为他是在为美国的利益而行事。所以为了获得人们的信任，而保持他的信用，他必须不能做美国人。

而美国在世界上的名声败坏，其中美军自己的行为也做了主要贡献。 *古巴关塔纳摩基地的审讯* 、 *伊拉克监狱虐囚丑闻* 、 *把阿富汗和伊拉克老百姓当猎物打* 、 *把打死了的无辜平民的身体部件当战利品收藏* 等等，都不言而喻了。更恶劣的是，被美国国会议员们看过，但奥巴马政府决定不公布的第二批照片，其实在网上的所谓黄色网站已经被人泄漏，其中有些是美军士兵轮奸伊拉克少女的照片，极其恶劣，被阿拉伯国家的一些组织广为流传，作为挑动反美情绪的宣传材料。

所以美军想挽回美国声誉的一个招数，就是建立了 *网络水军* ，也称为 *sock puppet* 。

这个就是有美军出钱，让美国的高科技公司发展出虚假马甲软件，然后一个美军工作人员，就可以拥有10个不同的马甲。而这些马甲，就必须“来自”世界不同的国家和地区，然后在各种非英语的论坛和其他社交网站上出没，一看到有对美国不利的言论，马上就出来护盘。

最近看到博客上突然蹦出来的，与文章内容好不相关的评论，高喊美国如何如何伟大光荣正确之类的东东，都不知道是不是这些水军们的自动软件在启动。

但是对Y先生这些美国军队中的有识之士来讲，大家知道靠水军的法子，是救得了一时，救不了一世。

*而真正可以挽回美国声誉和信用的法子，不是靠你军力出去吓人，而是要靠你自己把家里的事情搞好* ，让人家其他国家，不是对你充满愤恨、厌恶、反感和恐惧，而是对你自己的行为表示佩服和尊敬，愿意模仿和效法。

这个也要求美国必须 *言行一致* ，不能口头上说一套，实际上做一套。自己人权纪录糟糕透顶，比如说美国关在牢里的犯人的绝对数，是世界第一，比人口大国中国、印度等等都要多，也比自己嘴里口口声声咒骂的伊朗、朝鲜和古巴相当数字要多。

这种情况下，还到处骂骂咧咧，说别人的人权状况如何如何差，哪能让人服气。

当然Y先生还是摆脱不了美国人传承的 *传教士国家性格* ，大谈特谈美国的价值体系，是美国信用的来源。最有趣的是，列举了一大堆这样自由和那样自由之后，人家也提到了美国人民“免于受到有害的意识形态影响的自由”。这不就是中国的 *反精神污染* 吗。

不过在谈到一个开放体系里，以非零和的方式，和其他国家进行公平的竞争这一点上，Y先生和其他美国各界精英，谈到了美国的优势—创新和企业精神。

这也是其他国家，甚至包括中国的专家们，提到的美国优势。

*那么美国的创新意识，在未来和中国已经欧盟的竞争中，是否一定具有不可超越的优势？很多人的看法是认可，但我个人的观点，则是否定的。*

要理解这个，就要搞清楚，为啥美国面临的主要科技竞争者，日本和德国，无法在科技上完全超越美国？

其实原因很简单，那就是 *真正的科技优势，是来源于军事技术和军事工业* 。而日本和德国，在这个领域被人家给阉割了，所以无法彻底超越美国这方面的优势，以及通过军工技术，转移到民用的科技优势。

因为很简单， *高端的技术没有市场，自然就没有需求* 。以追逐利润为主要目标的民用企业，自然就没有意愿去投巨资开发。

可是一旦这个技术，是因为国防和国家安全的要求，那么算账的方法就不一样，自然资金投入研发就不是问题。这也是中国的两弹一星能够成功的主要原因。

美国最近几十年的民用科技，比如说互联网和GPS等等，都是军事用途而研发成功，最终转移到民用领域。

从这个角度来看，当年的苏联虽然有军事需求而产生的尖端的军事技术，但却没有一个成熟的市场，来带动民用技术的转移。改革开放之前的中国，也有同样的问题。

但是今天的中国，既有了逐渐成熟的市场，又有军事发展的需求，那么通过军事技术上对美国的追赶，比如说先进航空发动机的研发，自然可以带动向民用方面的转移。那么这样的竞争下，如果中国仍然保持成本优势，而逐渐发展的巨大市场，通过人口的规模，又把研发费用给分摊下来，那么未来的创新竞争，美国不一定可以占有大家认为的巨大优势。
