# -*- org -*-

# Time-stamp: <2011-08-25 12:13:57 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话64：埃及革命的背后（五）

[2011-02-25 10:50:35]

[和谐]

又没了。渔民政策，乐出不穷啊。


但是CANVAS训练了50多个国家的反政府组织，并不是每个国家的颜色革命，都可以拿出来炫耀。

据他们自己的分析，最成功的国家，是因为他们训练的学生们，就是这些国家的反对组织领袖人物。比如说格鲁吉亚和乌克兰。

而在伊斯兰国家的训练，最成功的是黎巴嫩。可是在伊朗，绿色革命就没有成功，因为他们训练的组织虽然有用，但是整个运动的领袖并没有采纳他们提供的战法。

波波维奇建议，伊朗的推翻政府运动，不应该以选举舞弊作为诉求。因为除了你的坚强支持者之外，大部分的选民都是打酱油的。你在选举舞弊上面大作文章，和人家这些人的切身利益没有太大关联，反而觉得你政治上不成熟，参与政治游戏，结果符合自己的利益，就接受游戏结果。不合自己的利益，马上就要推翻游戏规则。

毕竟你说人家舞弊，那你自己就干净了？或者说，既然系统可以舞弊，你没有舞过人家，不是说明你没用？

你要是这么没用，俺骑墙派怎么敢跟你混？所以你闹事，也是在为你自己的利益。俺们没有必要出头为你死。

而且你闹得越欢，人家政府担心俺们的态度，还嬉皮笑脸地跑过来送钱给俺们花呢。所以唤醒民众，是痴心妄想，但是民众也不在乎你是否成功，人家就是打酱油。

你们自己和政府，谁最后打赢了，不关俺们的事。只要不要忘记，过来送酱油钱就是了。

因此波波维奇的看法，是伊朗的推翻政府运动，应该像甘地的食盐游行那样，以生活诉求为马甲。比如说用力点，集中在失业、低工资、和腐败。

因为伊朗的人口结构和突尼斯、埃及等国家差不多，有不少年轻、相对教育不错的城市人口。这些诉求比较容易忽悠起来。

在他的眼里，差不多类似的，可以颜色革命掉的国家，大概包括阿尔及利亚、安哥拉、柬埔寨、埃塞俄比亚、哈萨克斯坦、尼加拉瓜和委内瑞拉。甚至俄罗斯也值得一试。

当然缅甸和朝鲜的难度要相对比较大，毕竟反政府行动的自由空间比较小。培训完的缅甸学生们在问道会不会回国后，立即着手他们讨论的方法。不少人的回答，还是找其他人干比较合适，俺们嘛，就出出主意好了。

埃及的学生，受到的训练和缅甸的学生一样。不过人家一回国，就开始干了。大概在2010年的四月，报道埃及抗议活动的图片，在塞尔维亚引起了大家的注意：怎么埃及抗议组织“四月六”的旗帜，上面的那个大拳头，俺们好眼熟呢？

阿德尔带回去了一大堆翻译成阿拉伯文的教材，包括配上了阿拉伯字幕的《如何推翻一个独裁者》的录像带。而之后的所有训练、组织和活动，阿德尔都一直保持和CANVAS的联系，并不断提问，获得课外补习。

在阿德尔的阶级分析图中，埃及军队的地位至关重要。因为针对埃及军队的动作，比如说美女上去献玫瑰花啊，抱个小孩子上去给士兵哥哥，坐一下坦克的炮筒啊，都按照计划实行。

在抗议活动进行的一月二十五号之后，一本26页的手册叫做《如何聪明地抗议》在埃及被广泛派发，而且这个册子现在已经传遍了整个中东和北非。

里面是教大家，如何去占领政府的建筑物，如何和警察、军人接触，如何互相保护等等。其中最重要的一条，就是如何保持统一战线，比如说在解放广场，穆斯林们祈祷的时候，基督徒们就出来围坐，保护他们。而基督徒们要祈祷的时候，穆斯林们就保护他们，等等，都是CANVAS的教材里的重点。

当然要达致的目标，是不是现实，是很重要的。埃及革命的目的，是要干掉穆巴拉克，而不是要改变埃及军人政府执政的现状。

而这个不要穆巴拉克的穆巴拉克体制，或者说美国主张的那样，没有穆巴拉克的穆巴拉克政府，还是可以得到军队的支持。

不然的话，你一张口，就要动人家军队的蛋糕，那么你送过去的是玫瑰，收回来的还是子弹。

当然这之后，埃及的局势，甚至整个中东和北非的局势，会出现什么样的变化，那就不是任何人可以控制的了。

*点火容易，灭火难。CANVAS的本事，是推到一个现存政府，至于如何重整河山，如何建设，那就不是人家的本领了。*

其实看中东和北非，在1950年代的风起云涌的反殖民地、反帝国主义的民族独立和国家自主运动，靠的是新军里面培训的军官们完成的。那时候的纳赛尔，现在的卡扎菲，以及后来派生出来的萨达姆、萨达特和穆巴拉克等等，都是那个浪潮之后产生出来的军事强人。

当然除了这些军事强人政府之外，就是没有被冲垮的国王体制，比如说沙特、约旦、巴林、阿尔及利亚和科威特那样的。

另外就是被推翻的国王，然后在美国支持下复辟的伊朗，然后又被推翻，出现宗教领袖领军的新模式。

*那么这个第二波的社会大变革，会给大家带来什么，现在还只是一个序幕。*

在利比亚内战中的东部反卡扎菲地区，参与过伊拉克战争，和美军战斗洗礼的基地组织战士们，在也门的基地组织们，在索马里的同盟军，会寻求更大的运作空间。

在埃及、沙特和巴勒斯坦等地的穆斯林兄弟会，也不会闲着。

从伊拉克、巴林、也门、黎巴嫩到沙特的什叶派民兵们，也蠢蠢欲动。

*中东失其鹿，天下共逐之。* 俺们这些局外人，还是等到汽油价涨到5美元的时候，再感叹民生之艰难吧。
