# -*- org -*-

# Time-stamp: <2011-08-25 13:14:58 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话46：2011猜想（2）


[2011-01-17 02:57:01]


既然谈起了突尼斯，就多讲几句。

*突尼斯* ，和中东北非区域的许多国家一样，主要是两大问题。一个是政府独裁和腐败，尤其是经济比较差，民生问题困难的情况下。另一个就是政府和民众之间的不合越发激化。

听起来像是美国最喜欢搞掉的政府，但事实上并非这样。

因为突尼斯和其他阿拉伯国家一样，反对政府的民间力量，通常是穆斯林极端宗教势力。所以 *如果突尼斯搞民主化，那么基本上就是搞反美化。*

当年伊朗革命，从政治体制来讲，绝对是推翻了伊朗国王巴列维的独裁统治，是民主化进步。但是上台的宗教力量是反美的，于是民主的伊朗成为了美国的敌人，取代了独裁的伊朗，这个美国的朋友。

在巴勒斯坦也是一样，民主选举一出来，哈马斯就上台了，给以色列造成了很大的威胁。

黎巴嫩的情形也是一样，西方是不敢在那里进行彻底的民主化进程的。因为 *现在的安排是要保证黎巴嫩的基督徒可以和穆斯林分享政治权力* ，如果推进民主化，那么占70%并且增加的穆斯林人口，就会保证真主党在黎巴嫩的绝对统治地位。

在看一下伊拉克的情形，伊拉克基督徒在萨达姆的独裁统治下，还可以活得比较滋润。现在民主化了，基督徒们只好逃亡他乡了。

所以美国是不敢在这些地方推行民主化的，民主的结果，就是反美政府的上台。突尼斯政治动荡的结果，会不会导致穆斯林极端势力上台，不光是对美国的反恐战争，还是欧洲的地中海战略，都是一大忧患。

但是这一次亲美国的本阿里的垮台，和美国自己摆脱不了干系。

那就是 *美国大使关于突尼斯总统本阿里的亲属们如何腐败，如何奢侈的秘密电报，被维基泄密，给通通报出来了。*

其实比较一下这些突尼斯腐败，比起来希拉里嫁女儿的奢侈，并不过分。但是突尼斯的经济状况之差，这个时候的爆料，就是火上加油。

而这些消息，是导致突尼斯变局的一个主要因素之一。因此维基泄密，就很自豪地把这个功劳归结到自己头上了。

美国外交杂志也将突尼斯变局，称为第一场 *维基革命* 。

当然这一次美国导致的变局，不是美国自己的本意。但是大家也可以看到俺前面写的舆论战争的重要性。当年美国在1953的伊朗，用政变推翻了民主伊朗政府，也是采取的舆论造势的先发手段。

当时的造势，就是用谣言散布伊朗的民选总理是同性恋，从而引发了保守的宗教狂热者起来，搞了个农村包围城市。当然这一招用保守宗教的农村，来对付开放现代的大城市德黑兰的招儿，人家 *霍梅尼* 后来照单接收。

这之前的未遂的伊朗颜色革命，想走反向道路，靠德黑兰比较开放的知识分子和青年学生，来撼动现政权，则比较难以成功，毕竟人口基数差别很大，信仰力量的对比也不占优势。

因此当阿拉伯和伊斯兰世界的舆论界，在讨论突尼斯会不会成为阿拉伯世界的头一张多米诺骨牌，大概没有意识到 *要是埃及出现这样的情况，穆斯林兄弟会上台，那么中东就真要大变天了，* 美国人和欧洲人大概就坐不住了。

回头继续谈美国的QE2给金融衍生品带来的结果。除了粮食涨价之外，能源和其他原材料都会涨价。

对中国人来说，因为食品占的比重要大，也因为能源在食品生产中的作用，都会造成比较强的通胀压力。这个靠的是政府主导的菜篮子，和俺前一阵提过， *缩短菜农和市场中间的距离，来维持价格稳定* 。

而美国人来讲，食品价格也不是大问题。这个得利于美国的天然资源，比如说当年罗斯福夫人号召大家自己种菜，结果是美国65%的蔬菜都是自己的后院出的。另外一个也是因为美国人食物结构中，蔬菜比重小于中国人。

那么在其他的用品上面，中国自身的消费价格压力应该不大，毕竟是世界的制造工厂。 *而对外出口的产品，比如说对美国出口的产品，估计涨价会接近40%。* 因为原材料和能源造成的涨价，大概是要占25%左右，因为中国农民工工资水平上升，大概是10%左右，而因为人民币升值和其他因素，大概会是5%。

*这个对美国会产生什么样的影响？*

看这次的美国节日销售，可以看出社会的分裂。那就是高档消费品销售大幅增加，因为华尔街和其他富裕阶层，日子反而更好了，导致购买LV手袋、Tiffany珠宝等等猛涨。

但是低中阶层的消费销售，就不是那样理想。

在这种情况下，如果美国进口商的成本上升40%，但是又无法通过提价转嫁成本给消费者，那么公司的利润就会受到影响。

因此这些公司采取的办法，其实就是一个，继续裁员，节省开支，然后保持价格不变，或者小涨。然后就在冬天节日到来的时候，请些临时工对付一下。

这个情况的出现，倒是比美国出现恶性通胀的结果，更要现实一些。

*另外一个QE2资金的去处，就是大家都熟悉的天量的信用掉期CDS。* 这次的 *CDS* 主要是针对欧洲的国债市场，那么这些资金玩出了大赌局，就必须靠搞倒几个欧洲国家，来获取暴利。

但是世界经济靠的是三条腿来支撑一个桌子，如果欧洲真的崩溃了，对美国经济也不一定是好事。
