# -*- org -*-

# Time-stamp: <2011-08-26 10:58:51 Friday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话96：以退为进和海阔天空

[2011-05-31 14:46:21]


看了一些读者对前一篇的评论，似乎认为如果内贾德下台，并不符合中国的战略利益。可是这些读者没有想到，伊朗人考虑自己的战略对策上，人家已经不是中国的大唐波斯都督府，又不是你的波斯特别行政区，当然考虑的立足点，是人家的本身利益。

而且中国在对伊朗的支持上，也不是百分之百和无条件的。毕竟中国还是同意了美国对伊朗的经济制裁方案。在中国和伊朗签订的不少能源合约，似乎着眼于长期的比较多，能够现在直接帮上忙的，不是太多。

在美国内部，除了亲以色列的强硬派，也有一派非主流智库，提倡美国和伊朗重新合作，恢复以前美国和伊朗关系，使得伊朗能够成为美国在中东依赖的主要力量。

持这一派观点的智囊们认为，伊朗和美国并没有根本的利益冲突。就算是伊朗伊斯兰革命成功之后，或许可以把黎巴嫩美军海军陆战队被人放炸弹炸了一事，扯到伊朗支持的真主党身上，毕竟你美国大力支持伊拉克武器，还把人家伊朗的民航客机给打下来，估计也可以扯平了。

而且伊朗在美国对付伊拉克的萨达姆和对付阿富汗的塔利班上面，是采取了合作态度的。 *那么之所以美国对伊朗采取敌视态度，当然主要问题，是伊朗被定义成为以色列的最大威胁* 。

这个定义，很大程度上是伊朗在伊拉克的势力坐大，影响了美国在中东的战略布局。也包括伊朗在内贾德治下，对以色列的口头刺激。而伊朗的核计划，又可能成为中东核军备竞赛失控的导火索。

目前美国对伊朗的制裁，在欧洲国家的大力支持下，和在中国和俄罗斯的有限配合下，确实导致了伊朗经济上的不少困境。比如说，伊朗航空公司如果飞行欧洲航线的话，到了欧洲机场，人家拒绝给你客机加油，让你没有法子飞回来。

诸如此类的做法，基本上使得伊朗的各种贸易成本大幅度上升，导致核计划的速度受到了影响。

而伊朗一直希望能够加入上海合作组织，借助俄罗斯和中国的力量，保护自己的想法，又没有得到足够的支持，因此 *在中东局势变化莫测的局面下，如何退一步海阔天空，把以色列和逊尼派放到火上去烤，以推迟和以色列和美国摊牌的时间，当然是一个比较优化的选择* 。

最近发生的几件事情，可以看到各派在这方面的操作。

第一件事情，就是伊朗军舰通过苏伊士运河，到达叙利亚，和叙利亚展开军事演习。这个动作基本上，就是刺激以色列和挑动埃及内部的反以色列力量。

第二件事情，就是埃及永久开放了加沙边境的拉法口岸，导致哈马斯的后援力量大增。同时也表明了美国和以色列对哈马斯的封杀计划，彻底失败。

第三件事情，就是埃及内部的一些力量，刚刚玩了一出 *捉放曹* ，说是抓了一个伊朗的外交官，怀疑是间谍。然后马上又说，没事了，你可以走了。看起来，就是发一个信号给伊朗，让你自己稍微收敛一点。

奥巴马在这个关键时候，高调把1967年边界拿出来说事，显然是希望拉拢埃及和其他地方出现的逊尼派新生力量。也希望无论如何以色列做一些让步，最起码可以在逐渐被人加柴火越烤越热的以巴冲突上，浇下一点冷水。

奥巴马另外一个手法，就是希望通过G8平台，以大幅度对埃及等国家的所谓新马歇尔计划，来拉拢这些国家的新实力派人物。虽然说上次希拉里在埃及吃了瘪， *毕竟那些反美的年轻人，只不过是陈胜吴广，而美国希望拉住的是刘邦项羽。*

看埃及的下一步发展，如果国会选举不被推迟的话，最大的赢家，基本上可以肯定是穆斯林兄弟会。一旦这个局面出现，以色列和巴勒斯坦的矛盾，将会出现大幅度升温。

这个时候，觉得自己被人逼到死角的以色列，会如何行动？是向伊朗动手，来化解自己的困局，还是继续死守，对付哈马斯?

奥巴马的第三个行动，就是通过“民间”的非政府组织黑水公司的原班人马，入驻波斯湾的几个小国，以此为自己的海湾势力范围护盘。

这个民间组织的动作，基本上可以卸掉美军的负担。毕竟如果美军出来保护独裁政权，无论如何面子上难以自圆其说。但是更重要的是，美军的关注点，还必须考虑到也门，这个应该是美军目前最大的担忧。

至于叙利亚，显然伊朗已经全力帮助阿萨德维稳。但是叙利亚和埃及不同，在埃及你还可以把军队从穆巴拉克的政府给分离出来。而在叙利亚，这种分离完全不可能。如果外部势力介入，强力推翻叙利亚政府，那么整个叙利亚会陷入无序状态，这样会导致的乱战局面，可以影响到以色列、黎巴嫩、约旦、伊拉克和土耳其。

而且因为俄罗斯在叙利亚的利益，这个地方的操作，受到的外部力量牵制，会远远复杂于利比亚，可以说是牵一发而动全身，应该是 *各位列强，在通气之前，都不会轻举妄动* 。

而法国在利比亚的干涉，力量会加大。但是法国碰到的抵抗，不光是来自于卡扎菲，而且还有非洲国家组织的取舍。因为如果法国希望以利比亚战争，而重新整合其在北非和几内亚湾的势力范围（法国刚刚干预了象牙海岸的局势）。

这个时候，同样也是美国需要固盘，保证自己从埃及到整个阿拉伯半岛的势力范围，不受到影响。

在这种各家都出现火烧眉头的情况下，中国在非洲的攻略，不排除开始经营索马里一线的东非海岸，通过和南部非洲国家组织和南非的合作，在这里建立自己的势力范围。

*从这个角度来讲，刚刚访问美国的陈炳德将军提议，可以上索马里陆地上剿匪，可以看作中国和美国在世界上合作的一个起步。*

*那么这样的话，中国和法国的势力范围分界线，基本上就是在乍得和尼日利亚交界。*

而在陈炳德将军访美之后，和美军大量交换了意见。估计达成的一个共识，就是中国在南海的利益，和美国在亚洲的利益，并不是必然冲突。

因为很简单， *南海的能源，如果没有中国的首肯，那么就算是你美国的埃克森和雪佛龙亲自出手，也别想开采出来。*

*除非美军军舰亲自护航，不过这样美军又要考虑在南亚和朝鲜半岛的压力了。*
