# -*- org -*-

# Time-stamp: <2011-08-25 21:13:51 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话80：九天揽月和五洋捉鳖

[2011-04-12 14:06:29]



今天是对中国非常重要的一个日子。因为在4月11号，中国北斗第八课卫星发射成功，使得北斗导航系统在中国和周边地区基本成网。当然要全面成网，还要等到2012年底。在2020年左右，中国的北斗就会全球成网。

北斗的出现，是中国在重大科技基础建设的一个里程碑事件。北斗，和美国的GPS，欧洲的伽利略，和俄罗斯的格洛纳斯一样，都是 *一个大国安身立命的必备工具* 。因为在军用上，这个系统可以为中国提供国防安全，在民用上可以带动几千亿的产业发展，使得中国在关键的导航、定位、报时上面，不再被人掐住脖子。

记得过去有朋友感叹我做过很多完全风马牛不相及的工作，当时我是开玩笑的说，这叫做可上九天揽月，可下五洋捉鳖，还要做到谈笑凯歌还。而 *中国要成为一个世界性大国，就必须在科技能力上，可以上天入地，登山下海，无所不能。*

北斗和其他的卫星导航系统不同，不光是无源系统，还具备有源功能。就是说可以从事双向的通信短信作用。

我在以前写的关于中国东风21D的反航母导弹文章的时候，曾经提到过北斗的功能。当时被读者错误地认为是要靠北斗来导航。其实不是这个意思。 *在谈到如何早期发现航母的时候，其实北斗的功能，就可以表现在这个短信上面。*

看过美国电影《黑鹰坠落》的读者，大概不会忘记这样一个场面。那就是当美军的直升机从基地出发的时候，就会有索马里的放羊的孩子，马上用手提电话，通知自己人。其实这个在抗日战争的时候，我们叫做消息树。就是放羊孩子王二小，看到鬼子朝村子这边偷偷来了，就把山顶上的一个消息树给放到了。

阿富汗的塔利班其实也干过这样的事情。那就是派人坐从巴基斯坦到中东的民航飞机，每次飞过印度洋的时候，看到美国的航空母舰战斗群，就打电话汇报，让大家知道美军的空袭可能要开始了。

*而将来小渔船上，都有这样的手提电话，里面有一颗北斗芯片，那么就可以做到全渔民皆兵了。*

这两天美国的事情挺多的。一件事当然就是国会两党在国债和财政赤字上面的争斗，已经到了白热化。联邦政府差一点关门，标志着恶斗刚刚拉开帷幕。

*其实美国的赤字不难解决，只要税收增加50%，支出去掉35%，就可以慢慢逐年降下来了。* 可是要做到这个，那就是刀光剑影，每一块肥肉都会打个不停，不知道打完了之后，还有没有美国这个国家了。

在以前的一个闲话中，我提到最主要的问题，是 *砍谁* 。美国各州政府，认为教师和教育可以不要。而现在的联邦政府，已经决定大富翁们要继续退税，华尔街大鳄们继续高歌猛进发红包，收入这边落空了，只好堤外损失堤内补，从支出这边多斩杀几刀了。

但是如果支出的三大块，国防、社安和医疗动不了的话，其他地方全部斩了，都没有大用。而这三大块，砍起来是动美国国本的大事，不是那么太好玩的。

美国的外交上面，也发生了三件大事。

第一件是美国政府大清扫，三位中国通出局。这三位是总统顾问Bader、副国务卿Steinberg，当然还有自己要走的大使洪教主。换上来的除了新任大使，会是商务部长骆家辉，其在华盛顿州长的任上，对中美贸易建树颇大，自己又是华裔，算是中国通。另外的两位Russel和Campbell是会说“巴嘎”的脚盆（也称为泥轰）专家。

这个算是延续了希拉里路线的拉紧日本遏制中国政策，只不过地震、海啸、核辐射不见消停的日本，将来是不是有气力来遏制中国，倒是值得怀疑。

第二件事情，是美国国防部长盖茨，继发表了著名的“历史垃圾桶”理论，和“美国高官通通脑残”论之后，又在伊拉克发表了“美国会把伊拉克驻军撤进伊拉克“理论。

这个撤军言论一出来，伊拉克最具有民意基础的反美领先萨德尔就趁机把队伍拉上街了。本来以为他会卧薪尝胆一阵子，等着美军撤走，就开始高调动作，现在看来伊拉克的冲突会死灰复燃。

第三件事情，就是美国的埃及政策，所谓没有穆巴拉克的穆巴拉克主义破产了。前一阵子希拉里访问埃及，主动地要和抗议活动的主要反对派领袖见面，却遭到了人家的严厉拒绝。

而现在埃及的年轻人们再次走向广场，开始挑战军方和执政党。埃及局势的转趋紧张，导致了美国和埃及的不少达人，开始不满奥巴马抛弃穆巴拉克这个美国的老朋友的政策。

看到沙特、巴林和也门，动手砍人，美国连一个屁都不敢放。而卡扎菲在北约的一轮轰炸下，又开始占据了上风，让穆巴拉克把肠子都后悔青了。因为他当时认为，如果按照他自己的计划，在9月份的时候，实现平稳下台，估计会避免埃及现在动荡的局面。

现在连动手砍人的叙利亚的阿萨德，要是前几个星期，估计会被美国上窜下跳，搞联合国决议，直接出手。可是经历了利比亚的劳而无功，并看到和沙特实际上的关系交恶，然后还无法控制埃及的局势，导致穆斯林兄弟会开始坐大，现在是叙利亚的事情，也懒得再理了。
