# -*- org -*-

# Time-stamp: <2011-08-25 11:50:25 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话61：埃及革命的背后（二）

[2011-02-22 02:20:41]


就是说，搞革命，要像人家可口可乐的广告推销那样，喝可口可乐的，让人觉得都是性感的俊男美女，那么俺们的这个革命分子，也要走这一着，才可以吸引今天的年轻人。

而且这个组织，决定不搞游行啊，集会啊这些传统的抗议手法。部分原因是他们的组织还搞不出那么大的阵仗。因为这些年轻人们从小看街上的恶作剧电视比较多，大家就出了一个怪招。

那就是不是大家都对政府有些怕怕吗？俺们就整些东西出来，专门让政府显得又没屁用，又让人鄙视。那么就把大家对政府暴力的恐惧，慢慢给消除掉。

其中一个有名的法子，就是在一个汽油桶上面画了米洛舍维奇的头像，然后一帮子年轻人，推着这个汽油桶，到比较繁忙的大街上，向行人们兜售。如果你投一个硬币，俺就让你提一根棒子，狠狠打米洛舍维奇这丫挺的。

这个法子的本意，就是如果政府你不禁止，就让人们看到你政府的软弱。当然如果你政府出来干预，那么大家就做鸟雀散，然后第二天反对党控制的电视台里面，就把你政府没有容忍力的丑态，向全世界大大传播。

其实就像现在网上号召大家去散步推翻政府一样。你不出动警力，严正以待，俺就表现出你政府胆小，大家就趁机上啊。但是如果你戒备森严，然后俺就在旁边安排外国记者们大力曝光，让人家看看你政府，多心虚啊，俺们都不出人，只是网上虚张一下声势，就让你出这么大的洋相。

而且这样的事情，将来不断地搞，让你精疲力竭，防不胜防。

不过俺觉得塞尔维亚的这帮年轻人，还是挺幼稚的。这一招对付米洛舍维奇有用，用在俺们美国政府身上，没用。很简单，你马丁路德金够牛了吧？一个字， *呯* 。查无结果。马尔科姆X，也是一个字。多少当年反政府的老黑们，这样那样的理由，就进去了。没有一个是政治犯，没有一个是因为言论自由之类。

连美国总统肯尼迪，都是一个字呢。倒今天不还是一个无头案。

结果这些以搞臭政府名声为主要目的闹剧一出，报名参加的年轻人大幅增长。这个时候，人多了，队伍壮大了，就不能再躲避被警察抓。而是要改变战术，搞事情，让你抓。就是说，俺被抓俺英雄，你不敢抓你狗熊。

结果是警察抓了一个，大家就搞群体事件，大规模人群包围警察局，要求放人。而塞尔维亚警察叔叔们，可能抓的时候，手法会重一点，但是进了警察局，从来不敢用人家美国对付恐怖分子的法子来和谐你，而且大部分是过夜都不会，就放了出来。

于是进局子呆几个钟头，就是很性感的事情了。走出来之后，反对派和外国媒体的镁光灯咔嚓咔嚓，好像好莱坞明星走红地毯。说不定，还有美女冲上来献花呢，晚上搞不定啥好事呢，嘿嘿。

结果就是年轻男人们大家争先恐后，唯恐不被抓进局子里去。

你得到的第一个奖励，就是有机会穿俺们组织发了的黑衬衫，上面一个大拳头。这个是成为革命战士的荣誉。要是进了局子里再出来，你就是摇滚歌星了。

这种精神上的变化，就是你本来会认为自己是受害者，现在是英雄了。反政府越来越起劲了。

两年之后，这个组织就增长到了7万人。结果就是在米洛舍维奇准备在2000年9月再竞选的时候，大家就开始发力了。通过这个组织的有组织抗争，和米洛舍维奇的压制，最后就导致了他控制的军警力量，觉得他成了一个负担。

于是米洛舍维奇辞职，塞尔维亚的颜色革命成功了。

不过，有一个问题，一直困扰着大家。俗话说，兵马未动，粮草先行。那么这个组织，哪里来的钱，可以支持搞这么长时间的专业运动。

这个一直是该组织的秘密，但是后来还是被揭开了。 *这个组织的资金，一直是来源于美国政府。*

得知了这个真相，该组织的7万名会员中，绝大多数人觉得自己给人出卖了。于是大部分会员退出了该组织。不过不要紧，米洛舍维奇已经倒了，南斯拉夫反正已经分裂了，塞尔维亚的大局已定。

没有退出去的领导人物，下一步做的就是出口。第一个目标，就是俄罗斯的主要外围，白俄罗斯。但是这个计划，没有成功。因为白俄罗斯的学生组织，被政府给渗透，然后就中了政府的反间计，大伙儿给搞散了。

而在格鲁吉亚就获得了2003年11月的玫瑰革命的成功，然后就是乌克兰橙色革命，都有这个组织的训练功劳。接着就是在南非训练津巴布韦的反对派人士。

这个时候，该组织的领导人波波维奇成了塞维尔亚的国会议员，开始创建第一家无线互联网供应商（当然无人知道人家资金的来源）。今天他是塞尔维亚的大亨，最大的互联网供应商和电话公司的老板。然后他的公司，就专门出资为CANVAS在全世界训练颜色革命组织。

当然 *美国政府* 的影子组织 *自由之家（Freedom House）* 和 *欧州安全理事会* 都出资，专门请他们帮助培训人才。

只不过，这个组织的训练，只是在一些比较弱的国家，取得了成功。如果比较一下格鲁吉亚，毕竟还是和朝鲜，不具备可比性。而且美国比较感兴趣的，就是你可不可以搞一次对付朝鲜这样的？

于是一个非常有趣的案例，就是 *如何培训缅甸的反对派，去推翻军政府，来实验这个组织的颜色革命药方管不管用。*
