# -*- org -*-

# Time-stamp: <2011-08-25 13:08:04 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话68：乱枪杀黑胭脂色

[2011-03-03 16:24:52]


想起了自己以前在2008年写的一句诗，用在今天的世界，倒是很贴切。

那首诗里的最后两句是“ *闲时洒水剑兰侧，但求顽鹿不吃边* ”。虽然J20和DF21D也招摇了一阵子，但是人家的航母老是想在边上吃一口呢。

上面一个闲话，有读者抱怨没有读懂，不要紧。读懂就看，不懂就算。不用那么执着。

说到这次中国从利比亚撤侨，这之前有朋友问我对利比亚的局势的看法。但是俺的大致意见是 *利比亚非常大的可能会陷入内战。短了是几个星期，长了是两三年。*

为啥中间的差距这么大？是因为参与其中的各派系的情况非常复杂，再加上外部势力虎视眈眈，导致局面很容易变化。

首先是说为啥可能内战，是因为这一次卡扎菲的支持者和反对者，在地缘和文化上，都比较旗帜鲜明。

先说一下反对卡扎菲的主要力量，就是以第二大城市班加里为中心的东部地区，叫做Cyrenaica。

而卡扎菲的主要支持一方，是以利比亚首都为中心的Tripolitania，还有就是西南部撒哈拉沙漠里的Fezzan。

其实利比亚作为一个国家，是很近期的事情。早在罗马帝国时代，这些地方，就是不同的省份。然后经过阿拉伯人、突厥人，最后到意大利人，城头大王旗换了好几轮，都是各行其是。

最后在二次世界大战中，盟军于1947年从意大利手里拿下了这个地方，就在1952年决定，把它搞成一个国家。

n当时树立的国王，就是来自东部Cyrenaica的Senussi部落的酋长Idris，出来做利比亚王国的国王。

可是人家Idris说，什么屁利比亚国王，俺真不乐意干呢，就让俺做Cyrenaica的酋长，就好了嘛。

不过当时主持的英国人，说啥也不干。帝国利益需要你，你就凑合着干吧。

在Senussia部落当道的时候，其他部落自然就只好歇菜了，被人家压在头上猛捶呢。

这个时候的利比亚，是英国和美国的优秀狗腿子。不光是美国和英国，在这里有基地，而且南部的沙漠，还是英军和美军在意大利的战机，过来练习的投弹靶子。

然后就是 *1959年* ，美国的埃克森公司在利比亚发现大油田，于是在分蛋糕上面，就引发了其他部落的不满。

当然，当时阿拉伯世界，正形成了 *纳赛尔* 刮起的革命风潮，导致了利比亚这个部落联邦，充满了其他部落对统治部落的不满，也洋溢着青年一代的人们，反帝国主义、反殖民主义，和反西方国家的激情。

于是在1969年，终于在卡扎菲上校和一帮年轻军官的策动下，主要来源于Tripolitania和Fezzan的三大部落， Qadhadhfa（卡扎菲的部落）、Maghraha和Warfalla的部落人士，搞了一次武装政变，就把国王给废了。

先知先觉的英国，早就看出情况不妙，已经在1966年，关闭基地走人了。而后知后觉的美国，就在卡扎菲上台之后，于1970年，被人家一脚给踢走了。

今天看利比亚的内乱，你可以看到Cyrenaica的人们，举起的旗帜，是当初的王国旗，举出的画像，也是老国王的画像。

而这次卡扎菲的支持力量，有所减弱，是因为当初支持他的三大部落，其中的Warfalla开始动摇。其中一个原因，就是来自这个部落的军官们，在1993年想搞一次兵变，干掉卡扎菲。

结果这次兵变失败，带头的主儿们被五花大绑，送回去给部落长老处理。那人家只好自我了断，用家法给砍了。

因此这次东部造反之后，该部落的上层，已经表示和卡扎菲正式翻脸。但是中下层各级干部的思想并不统一，大家还有不少分歧。

而卡扎菲的其他两大部落的支持比较稳定，算是和对手相比，稍微站优势。至于其他的将近一百个中小部落，基本上都是在骑在墙上观风景， *目前表示鸭梨不大，继续打酱油。*

因此在这种局面下，如果你不是每天看老美的新闻，搞舆论战争的话，利比亚的局势，如果在几个星期中间，大家不能靠谈判解决问题的话，就要看双方，大挖战壕，准备搞持久战了。

这次反对势力似乎突然成了气候，就和1969年那次一样，受到了埃及的东风吹。

另外一个因素，就是 *利比亚的部落联盟，靠的是石油分赃协议来维持。*

而2008年开始的全球经济危机，导致了利比亚石油收入减少了40%，导致了缩小的蛋糕，在承担损失方面，各部落之间关系趋于紧张。

不过讽刺意味的是，这么一折腾，油价就搞上去了，蛋糕规模又回来了，不知道大家是不是分起来有容易一些了。

当然，到底利比亚的乱局会持续多久，外部大国势力，也起相当作用。这个时候，不光要注意高调抢进的美国和英国，也要注意在利比亚利益最大的意大利和法国。
