# -*- org -*-

# Time-stamp: <2011-08-26 09:18:38 Friday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话88：美国战略转变（三）

[2011-05-08 10:44:42]


结果最近在美国战略界把持的《外交》杂志上，看到了一篇叫做“人人恐惧中国（Everyone’s Afraid of China）”的文章，算是对这个问题，给出了某种回应。

这篇文章的作者叫做Clyde Prestowitz。这位老兄曾经出任过里根政府的商务部长的顾问，参与过美国政府，对亚洲国家，包括中国、日本和南韩，以及拉丁美洲等国家的贸易协定签署。他后来创建了“经济战略研究所（Economic  Strategy Institute）”，为后来的北美贸易协定，也做出了一定的影响。

所以当4月底，这位普老兄和一小撮圈中人吃晚餐的时候，就是大概这么20-30个思想库智囊、前政府高官、新闻界大牛、少数商界总裁和一个现任政府高官，大家一起乱侃的时候，似乎出现了一个共识，就是全球化已经无法推进下去了。

而所谓主要的原因，就是“人人都怕中国佬”。

就是说，至少从美国人的角度来讲，人家觉得这个全球化的框架下，美国人开始恐惧中国的竞争能力。

要知道，出席这个晚宴的人，不是美国工会那些反对国际贸易的人士。这些人是支持美国给予中国贸易最惠国待遇，支持中国加入WTO的人士。本来大家认为，只要把中国接受进入WTO，然后就可以把中国颜色革命到西方的市场和民主体系。也许在政治上，不是完全的西化，但至少是新加坡西化，虽然还有些威权体制的影子，但最起码是西方要求下的自由市场、自由贸易和资本控制国家的形式。

说白了，就是 *人家希望中国是喂养肥了又可以割肉的一头猪* 。现在的问题是猪是长大了，可是却不听话，不愿意被割肉了。

本来WTO框架下的全球贸易体系，本来就是为了帮助美国获取经济利益。但是现在处于这个规则之下的竞争，却出现了面临中国的竞争，美国感觉自己处于了劣势。当然是不是真的处于劣势，是值得商榷的。只不过相对于以前那种绝对的欲取欲求的优势，确实是遇到了挑战，有点力不从心。

比如说以前美国在WTO框架下，碰到了日本和德国的竞争，人家可以从政治、外交和军事的考量下，要求日本和德国给自己“公平竞争”下去，解决所谓国际贸易的不平衡问题。

这个也是我曾经提到过的所谓 *美国的盟友们要购买全球安全防卫股份，就是说美国老大的保护费的意思* 。

*这个也是为啥本拉登和盖达组织，被定义为反西方，或者是反全人类的意思。因为只有共同的敌人，你才可以交你那份被保护的份额。*

可是塑造中国成为全球敌人，当然行不通。不要说是亚非拉，连欧洲都行不通。或者东亚还可以找到几个国家，比如说新加坡那样的应和一下，其他国家，就趁机以中国威胁论，成为军队高官们的发财机会，但是要是以中国为敌，来创造出一个共同敌人，从而让美国可以堂而皇之的收保护费，何其难也。

所以这些美国高层人士们的结论，就是在不远的将来，新的贸易协定，将出现双边化、行业化和地区化的趋势，而不是全球化和全面化趋势。而他们认为代替全球化的趋势，将会出现自由贸易协定FTA泛滥。其实 *所谓的自由贸易协定，更准确地说，是优惠贸易协定PTA，就是签约的国家们享受别人没有的贸易优惠条件* 。

而对美国来说，其实这是一个比较令人担忧的趋势。因为很简单，未来世界的经济热点，会是远离美国的东亚，那么要是人家搞起什么地区组织，不说那个鸠山提出的吓得老美心脏病出来的东亚共同体，就是你东亚三国论坛、10+1、10+3等搞下去，把美国参与的APEC给晾到了一边，那人家美国人就悲剧了。

所以这些美国曾经吹捧全球化的人士们，坚决反对这个趋势。他们说，当年大萧条之后，就是这种东东搞出了二次世界大战。

言下之意，就是你要搞这套双边和地区协定，那就会导致世界大战。你们自己看着办吧。

其实看一下希拉里高调宣布的返回亚洲，就带有这种思维在里面。就是我美军绝不会从亚洲后撤。没有一个稳定的环境，你亚洲各国就别想得到地区经济整合的好处。而我美军就是来搞乱亚洲局势的， *你要是不想乱，那就交保护费* 。

于是像新加坡李光耀这样的人，一方面催促美军快点回来驻扎对付中国，一方面又厚着脸皮，要求中国把新加坡做成为人民币离岸中心。他倒是想美国人花钱来驻军，然后用美国作为虎皮，从中国割点好处。

可是人家美军想的是，用你新加坡提供的费用来驻军，作为打击人民币国际化的工具。不知道这样的利益冲突，最后靠如何安排来解决。

可以看到这个思维的背后，就是美军的负担，必须很大。因为你必须在世界的主要地方都维持存在，而且还要随时压制住各种挑战的力量。

那么Y先生提出的看法，虽然对未来国际经济发展的趋势，并不是特别清晰，但确表明了非常明确的观点，那就是 *美军不愿意独自担当帝国的重担* 。

尤其是当帝国的其他部门，比如说 *掌握财权的华尔街* ，不光没有配合美军做到稳定帝国局势，反而监守自盗，把美国面临的危机进一步深化。这种 *枪杆子* 对 *钱袋子* 的不满情绪，最有力的表现，就是现在以《外交》杂志为代表的战略派，开始声讨华尔街，认为高盛为代表的金融界，是当前世界粮食和石油价格飞涨，引发中东和北非乱局，导致全球陷入混乱的罪魁祸首。
