# -*- org -*-

# Time-stamp: <2011-08-26 09:36:24 Friday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话91：美国战略转变（六）


[2011-05-14 14:41:01]


在Y先生的文章里面，他们提出了一个有趣的问题，就是你要想向全世界输出你的“ *聪明实力（smart power）* ”，你就必须先有国内的“ *聪明发展（smart growth）* ”。所以我就非常小心的寻找，看他们对美国军方应该在美国国内事务中，扮演什么样的角色，如何定位。

结果他们先是谈到，美国要想在全世界重建其信用，就必须解决言行不一致的差距。其中一个就是要停止 *乱贴标签* 。

*所谓乱贴标签，其实是美国一直的对外战略。每当美国将一个国家、一个政府、或者一个组织，界定为自己的敌人之后，采取的法子，就是先把人家给妖魔化。搞到人家仿佛不是人似的。*

然后就在妖魔化之后，开始在国际上孤立这个对手，靠威逼利诱、偷偷给好处的法子，就拉了一帮喽罗，然后就出去动手杀人了。所以美国政府，不管是行政部门，还是国会，再加上煽风点火的媒体，都是帽子工厂，长于生产希特勒牌子的大帽子，到处出去给人戴。

连中国这样的韬光养晦，夹着尾巴过日子，人畜无害的小白兔，2008年的奥运会，也给戴上希特勒的大帽子了。

不过这种乱戴帽子的法子，也有毛病。虽然可以团结和鼓舞自己人的士气，但是也同时鼓舞和团结的敌人的士气。

奥运会一战，虽然造成了西方同仇敌忾的气势，可是中国人的团结和士气，尤其是很多出生海外，从来没有去过大陆的华人，也被刺激得走出来了。

在对付本拉登的问题上，美国也吃了乱贴标签的恶果。反恐战争，反出来的恐怖分子越来越多，结果就是自己陷入了战争泥坑，导致了这10年的国力快速衰落。看来阿富汗这个帝国坟墓的绰号，真不是浪得虚名。

但是Y先生，把这种乱贴标签的行为，笔锋一转，用了一个英文词，叫做binning，即 *装箱* 的意思。这个说法，一方面指是把不是敌人的穆斯林，通过发明Islamofacist这样的无聊词汇，都给装到了敌人的箱子里去了，而这种装箱的方法，也把自己内部给分裂了。

就是说美国政府的各个部门之间，国家的内政和外交之间，都出现了分道扬镳的现象。而要保证美国的安全，就必须解决美国可不可以保持富强的问题。这就要求美国的国内和外交政策必须协调，那么军队扮演什么角色？

我个人觉得，在这个问题上，Y先生一直闪烁其辞，遮遮掩掩，无法明确地表达出来。

Y先生的建议，就是美国安全的基础，是订立于冷战时期的NSC68文件。其中主要是将国防和外交，作为国家安全的基石。

而现在要将美国外交政策非军事化，Y先生认为，必须将以前的National Security，改写为National Prosperity And Security，就是说把发展经济，放到首要位置上。所谓发展才是硬道理。

那么在内政和经济作为外交首要任务的时候，控制着美国内政事务的国会，和控制美国经济的华尔街和其代理美联储，如何保证其施政方针，可以和军方和外交战略界的目标一致？

比如说现在美国国会强烈支持的利比亚干预，和军方的态度，截然不同。而 *军方认为，美国最重要的投资，是对教育下一代的人力资源的投资* 。可是美国各级政府，现在都忙于解雇教师，关闭学校，减少教育投入。

美国的经济恢复，有赖于实体经济的发展，而在美国缩减财政支出，却放松货币投放的局面下，华尔街仍然陶醉于金融衍生品和炒卖大宗商品。国家基础设施残破不堪，结果现在的密西西比河涨水，给河边的人民带来了灾难。而美国真正的危险，是在各州维修不良的水坝和桥梁，一旦出现问题，真是不堪设想。

*这个时候，美国的军方会在内政里面扮演什么样的角色？或者说，大家要求他们扮演什么角色？* 这个都是在美国战略转变中，必须面临的问题。

另外就是当美国外交开始出现非军事化的倾向，那么对外交人员的要求就大幅提高。美国外交队伍，受到维基泄密的影响，导致了在其他国家的各种线人面临危险（因为人家各国的情报部门，自然不会帮你改掉名字之类的）。

而美国外交界的两员大将中，阿富汗巴基斯坦特使，霍尔布鲁克因为工作辛苦，压力过大，死在了任上。另一位大将，中东特使米歇尔，现在也撂了担子。

再加上现在巴勒斯坦的哈马斯和法赫特开始和解，以色列依赖的埃及合作，不再存在，加沙局势的下一步走向，非常诡异。对美国外交政策，是一个大的挑战。

最近美国不少人，开始翻开历史，寻找答案。

记得奥巴马刚刚上台的时候，正是经济危机的热闹时候。那时候，美国出现最多和最风行的历史书，是关于小罗斯福的新政的。

而奥巴马短短的一年，基本上就把大家对新政的期待，给消磨掉了。那个时候，大家开始热林肯了。

而今年最热门的美国书，就是关于美国南北战争的书。

而更多的学者，则是关心民主体制陷入内斗僵局，有如罗马共和国的元老院，出现瘫痪局面。这个时候，是不是会出现对强人的呼唤？

美国在历史上曾经有过两次大的危机，一次是1860年南部各州联盟独立而导致南北战争，一次是1929年经济大萧条。

两次危机，靠出了 *两位独裁的强人林肯和小罗斯福* 度过了难关。而现在的美国，是否会出现另一位强人，或者说美国人的心态中，可不可以接受这样的人出现，都要看美国经济在中期内失业率无法好转之下，如何应对。

而这次军人开始出来发话，可以说是一个新的时代的开始。
