# -*- org -*-

# Time-stamp: <2011-08-14 12:28:08 Sunday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+STYLE: <link rel="stylesheet" type="text/css" href="css/org.css">

** 九月


*** 从JH7到JH7A看“飞豹”的革命性变化

[2008-09-24 15:35:42]

从JH7到JH7A“飞豹”究竟有那些革命性的变化,笔者根据仅有资料从战术指标、动力、气动外形、航电、武器系统五个方面进行了概括和总结,现提供出来,供大家讨论。

一.战术指标

JH7 的战术指标从来没有详细公开,根据出口型FBC-1展览会上散发的资料,这种飞机<<长22.325米,翼展12.705米,停机高度6.575米,最大起飞重量28475千克,最大外挂重量6500千克,作战半径大约为800千米,能够进行1.7马赫数的超音速飞行,最大升限达到15200米,能够在 0.7～0.9马赫数下进行投弹,导弹投放最小高度为300米>>;JH7A由于采用国内新研制的全复合材料平尾,减轻了重量,强度和寿命都提高一倍,再加上 2003年通过国家鉴定的“秦岭”发动机,在国产化进程中性能已有明显提高,所以国内媒体对JH7A作战半径的报道是1600千米,已足以涵盖中国大陆近海至第一岛链。

二.动力

JH7使用的是<<英国斯贝MK202发动机>>,JH7A用的是<<国产涡扇-9“秦岭”发动机>>。涡扇-9是英国斯贝(SPEY)MK202发动机的国产衍生型, “斯贝”MK202型是英国在 60年代中期研制的一种性能较为先进的涡扇发动机,它是皇家空军F-4“鬼怪”式战斗机的标准发动机,长5025毫米,直径1039毫米,重1850千克,最大推力54.5千牛,加力推力91.1千牛,推重比5.05,最大军用耗油率0.684千克/牛•小时,最大加力耗油率2.0千克/牛•小时,涵道比0.62。当时中国希望将MK202作为JH7标准发动机装备,同时出资5亿英镑,于1975年12月13日与英国签约引进该发动机生产专利,1976年3月,603所的中国红旗机械厂负责开始试制该发动机。从此, 涡扇-9开始了漫长而又艰辛的国产化进程,终于在2003年7月17日,国产化的涡扇-9通过国家工程技术鉴定,获准投入批量生产。实现全国产的涡扇-9 被命名为“秦岭”,性能已有所提高,是目前JH7A用发动机。
三.气动外形
JH7采用中等展弦比后掠式上单翼,外翼带气动扭转,翼根带填角。斜定轴全动中下平尾,大后掠单垂尾,单腹鳍。两侧进气,蜂腰形机身,两台发动机并排于后机身内,三点式机身起落架,前起落架为后撑杆形式,主起落架为小轮距“外八字”摇臂式。JH7A则采用了新的整体圆弧座舱风挡,取代了原机上的三片式座舱风挡,使飞行员的视野得到改善,新设计了机头雷达整流罩,两翼新增一对武器外挂点,并取消了JH7上的翼刀设置,改JH7上的单腹鳍为双腹鳍。JH7A的加工工艺较原型机也有明显改观,整体上显得十分光顺整洁,显示了生产厂家加工制造水平的提高。
四.航电
JH7的航电主要由飞控系统、火控系统、导航系统、通讯系统、电子对抗系统组成。具体设备包括:
飞控系统:
1套KF-1型三余度三轴增稳数模混合自动飞行控制系统;
1台8415型数字式大气数据计算机;
1套HZX-1B型航向姿态指示系统;
1套安全高度预警系统;
火控系统:
1部232H型多用途火控雷达;
1套HK-13-03G型平视显示器(含火控计算机);
1套舰空导弹火控系统;
2套多功能单色液晶显示器;
1套多功能彩色下视显示器;
1套头盔瞄准器;
1套1553B综合数据总线系统;
导航系统:
1套HG-563GB型惯性/GPS组合式导航系统;
1套210型多普勒导航系统;
1部WL-7型无线电罗盘;
1部265A型雷达高度表;
1部XS-6A型信标接收机;
1套HGY-10B型IFF/ATC应答机;
1套微波着陆系统;
1套仪表着陆引导系统;
通讯系统:
1部170型HF短波单边带电台;
1部651型VHF/UHF超短波电台;
1套483D数据传输/塔康系统;
1套JT型机内通话器;
电子对抗系统:
1部605B型敌我识别器;
1套RKL-800A型综合电子对抗系统;
1台KJ-8602/RW-1045型雷达告警接收机;
1套综合电子自卫智能计算机;
1台960-2型噪音式电子干扰机;
1台KG-8601型应答式电子干扰机;
1台KZ-8608型电子侦察机;
2套941-4G型红外/无源电子对抗系统(红外诱饵/干扰箔条发生器);
这些简单的机载电子设备决定了JH7战斗力的特点,可总结如下:
(1)        JH7的机载电子设备主要执行针对海上目标的攻击,而对地攻
击则使用座舱的瞄准具。这种技术整合状况使得JH7战机只能对海上舰船使用远程精确制导弹药,而对地面目标则仍然使用常规航空弹药。
(2) 飞行控制系统只综合高度表参数,雷达不能测量飞行航向前方的地形高度,只能保持在复杂地形平均高度上飞行,这很容易被目标舰艇在远距离上截获,监视全部攻击和投弹过程。这样,目标舰可以启动舰上武器系统,对准来袭航向和预跟踪,一旦JH7战斗机接近射程就开火,这对于空袭的JH7战斗机非常不利。
(3)机载雷达缺乏地形跟随能力,地形回避性能也不完善,主要依靠事先规划的航路结合仪表导航完成复杂地形的超低空飞行,这种简陋系统下的复杂地形飞行适用于简单的气象条件,遭遇复杂气象条件时很难完成这种任务飞行。
(4) 机载设备简陋,导航技术水平低,且缺乏通信保障。造成的最大困难是:复杂气象条件下的远程作战需要长时间超低空飞行,这会遭遇很复杂的气流影响,扰动造成的偏差更大,此时缺乏通信保障,将会使得空袭的JH7编队无法了解不断变化的目标位置,及时纠正导航偏差,最终可能导致跃起后找不到目标,甚至闯入目标舰的瞄准扇区内而遭到杀伤。
总之, JH7只是解决了航程远和载弹量大的问题,而携带精确制导武器和全天侯复杂气象条件的飞行能力并没有解决。这也是JH7A要改进的地方。
JH7A航电的改进主要包括以下几点:
(1) 机载雷达由早期功能单一的对海搜索雷达换装为具有对地和对空搜索功能、能进行地形回避和地形跟踪的综合火控雷达。据加拿大<<汉和防务评论>>报道,JH7A的综合火控雷达为JL10A,607所研制,X波段,雷达上视搜索距离达到80公里,下视搜索距离54公里,具有11种工作模式,可同时跟踪4个空中目标,上视跟踪距离40公里,下视跟踪距离32公里。607所还为JH7A研制了Blue-Sky低空导航吊舱, Blue-Sky地形追踪间隙高度60-400米,地形追踪雷达探测距离15公里,前视红外探测距离10公里,重量200公斤,可以使JH7A以时速 900公里,进行60米的低空地形跟踪飞行。JL10A大大提高了作战能力,使JH7A能够对地面和海上目标进行远距离精确测量,将目标运动要素提供给火控系统,这是作战飞机使用防区外发射的精确制导武器的基础。
(2)JH7A的座舱系统据称也得到了改进,早期只有简单的仪表和雷达显示装置,而 JH7A安装了综合座舱显示系统,与常规显示仪表不同的是,这些系统能够将导航、通信和火控信息进行综合,直观地显示在座舱垂直状态显示器上,飞行员可以通过显示图标方式了解前方地形、空情和目标相对位置,而以前的仪表则需要靠飞行员不断核对仪表读数和导航图。
(3)综合雷达装置提供的地形回避和地形跟随功能能够交联自动驾驶系统,配以前面提到的Blue-Sky低空导航吊舱,使JH7A能在超低空复杂的航路上也不需要太多的人工干预,能够按照规划的作战航路飞行。
综上所述,“飞豹”的这些革命性变化,标明中国海空军的突防能力已与世界先进国家相当。
五.武器系统
JH7 的武器比较单一,鉴于只担当对海攻击任务,它的武器主要还是C-801/C803/鹰击系列反舰导弹,最多可携带4枚。JH7A的武器装备推断如下:保留双管机炮,除了能使用C801/C803/鹰击系列反舰导弹外,还可使用引进生产的Kh-31A超音速反舰导弹, Kh-31P超音速反辐射导弹,且可挂载先进的空空导弹。据据加拿大<<汉和防务评论>>报道,JH7A携带了由俄式27N激光制导炸弹寻的器组合而成的激光制导炸弹,由此可以推断JH7A具有精确攻击能力。其他的对地攻击武器,还包括现役和研制中的国产与进口航空弹药、火箭弹等。

可以肯定的说,无论从什么角度看, “飞豹”都可以说是中国开发最为成功的飞机,它的装备使中国具备了与先进国家作战水平相当的能力,它是中国21世纪的主力机种之一。

*** “大海军”离我们还有多远？

[2008-09-24 15:57:06]


以往我们谈中国海军时，总离不开“蓝水海军”、“防御型海军”的范畴，对这两个字眼大家已经相当的熟悉，笔者在此也不想浪费笔墨。给人耳目一新的是在2008年初，西方权威防务期刊《简示防务周刊》在报道中国海军时提出了一个全新的概念－“<<大海军>>”。这表明西方已经在一定程度上超越了过去着眼于解放军武器装备的更新换代，而是从国家力量、国家战略角度全方位重新认识中国的海上力量。这也从另一个侧面对我海军近几年的巨大进步的肯定，然而<<我们的海军真的从武器装备更新换代的量变达到“大海军”的质变了吗？>>让我们细品一下《简示防务周刊》给“大海军”下的定义再来进行评判。<<《简防》认为，“大海军”包含至少三个方面的内涵，首先，这应当是一只技术现代化程度较高的海军（而不仅仅体现在规模和数量庞大上），具备远洋作战能力；其次，具备有效的海上控制能力，在战争中可以打赢相对弱小的对手；第三，拥有“海域禁入”能力，可完成区域性的海洋控制任务，有效威慑强大对手。>>笔者的评判如下：

第一条：在技术现代化与具备远洋作战能力问题上，我们的海军由于技术含量较高的170、171入役，再加上购买的“现代级”，以及093、094以及AIP潜艇，还有071船坞登陆舰等相继服役，可以说中国海军已经达到第一条的标准，这一点我们够了。

第二条：在相对有效的海上控制能力与打赢相对弱小对手的问题上，我们的海军经过整整半个多世纪发展,从无到有,从引进仿制到自行研制再到开拓创新,一步一个脚印,踏踏实实地创出了一条富有中国特色的发展之路.<<如今中国海军编有三大舰队、海军航空兵团和规模不大的两栖战力部队>>,这三大舰队为:北海舰队、东海舰队、南海舰队,每只舰队都拥有潜艇分队、驱逐舰分队、护卫舰分队、海岸导弹快艇分队。发展到这样一个规模，我们可以自豪的说海军还是有相当的战斗力的，对象越南这样的相对弱小的国家还是能够打赢的。因此，《简防》提出的第二点标准，我们也够了。

 第三条：在拥有“海域禁入”能力与有效威慑强大对手问题上，笔者认为，我们海军的能力还达不到。因为，<<对海域有禁入能力的装备那就是航母编队了>>（笔者观点：海军中航母编队的攻防体系最完备，能控制作战半径内的海域。），在此我们以美国的小鹰号航母编队为例进行介绍和对比（小鹰号编队由1艘航母，3艘防空型驱逐舰，2艘反潜型护卫舰，2艘攻击型核潜艇，1艘后勤支援舰，共计9艘舰艇组成。）。对于防空型驱逐舰、反潜型护卫舰、攻击型核潜艇、后勤支援舰这几个方面，我想我们现在有这个能力生产与装备。航母目前我们还没有，但已有进展，随着动力、弹射器、舰载机问题的不断解决（现在已有媒体报道我舰船动力曲轴的国产化，舰载机购买俄罗斯Su- 33。），相信不远的将来我们会有自己的航母编队的。到那时才可以称得上拥有“海域禁入”能力。要是达到《简防》提出的能有效威慑强大对手水平，笔者认为那还必须拥有三个或三个以上的航母编队。所以笔者观点：<<“大海军”离我们还有很长的路，还需要我们不断探索。>>那种认为：中国海军已处于“大海军”时代的观点，是中国威胁论的一种表现。我们应该给予驳斥。

老军001以上陋见，随笔而发。欢迎大家进行评论、拍砖与补充。。。











