# -*- org -*-

# Time-stamp: <2011-08-18 16:43:38 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+title:如何从书本知识读懂世界

老军001是一个读了很多书的人，到底读多少书呢？我也不记得有多少本，反正是自己买书的钱有5万3000多元了，但是我读的书都不是小说娱乐一级的书籍，都是关于国家战略和国家安全的书，涵盖<<军事>>、<<经济>>、<<哲学>>、<<科技>>、<<文化>>、<<历史>>、<<法律>>等很多大的方面，现在老军001可以自豪的说经过8年的苦读苦写基本读懂中国读懂世界了，就是说知道中国制定的国策走向和世界大趋势发展方向了，更进一步的说，这世界上的事在老军001的脑子里形成了一个“度”、一个根、一个<<潜意识模型>>，诸位要是不信的话可以看老军001最近几年写的博文，里面有很多我对世界大事的判断和军事经济解读，基本符合世界趋势。算了不吹了，下面老军001谈谈我是如何通过看书读懂世界的。

先说<<军事>>上的潜意识模型是如何形成的，必须看军事上的专业书籍和科技文献，而且涵盖面要广，譬如<<航天>>、<<航空>>、<<舰船>>，<<潜艇>>、<<装甲车辆>>、<<枪械知识>>、<<防空技术>>，<<电子和雷达技术>>，<<战机技术>>，<<材料技术>>，<<新概念武器技术>>，<<电子器件技术>>等，还有军事理论中专业书籍更是要看，这样能丰富你的头脑，形成属于自己的作战潜意识模型，这样的书籍有<<孙子兵法>>，<<战争论>>，<<大纵深战役理论>>，马汉的<<制海权>>，杜黑的<<制空权>>，以及中国军事专家编著的<<从古至今的军事作战理论汇编>>，还有军事科学院公开出版的<<军事理论博士论文集>>等等。不但要看专业书籍，而且要看<<科技文献>>，因为科技文献往往是新出现的概念和装备技术，这样你再看海外军事新闻的时候，才能够找到有价值的新闻，并能根据自己的潜意识模型进行新闻分析，说道这里，一些人或许会说，你不接触军事装备的实际东西，咋能形成自己的潜意识模型呢？老军001要说的是<<潜意识模型有理论模型，有实际模型，一般理论模型形成的东西能涵盖实际装备模型的内涵>>，就是你像老军001这样通过看书形成的潜意识军事模型<<能外罩住实际的东西，更进一步说实际的东西逃脱不出理论知识形成的潜意识模型>>，这样用潜意识模型进行分析就能具有指导实际模型的东西了，此所谓理论指导实践的真理，这也是老军001用自己的潜意识模型能进行军事问题分析的原因吧。

当然分析世界大事，离不开<<经济>>，那么<<如何通过看书分析经济大势呢？>>老军001要说的是这就需要你掌握经济学的根，啥叫经济学的根呢？这个还需要你从经济学的专业书籍中进行挖潜，找属于自己那个根。这个根就像老军001前面说的潜意识军事模型一样，都属于每个人自己的心里想。老军001就是通过这样的方式形成属于自己的根的，先看<<《经济学史》>>，了解经济学不同发展阶段的各个大家们观点，譬如重农主义学说，重商主义学说，马克思经济学，凯恩斯经济学，以及他们之中的种种改良和变种都要看，就是要所有名家的观点在脑子里形成概念，这样你才能进行下一步。然后你在看经典的西方经济学和中国经济学，先说经典主流西方经济学吧，必须看<<《国富论》>>、<<《凯恩斯著作》>>，<<《博弈论与经济行为》>>，<<《资本积累与经济活动》>>，<<《投资策略》>>，<<《停滞膨胀》>>，<<《增长的极限》>>，<<《国际生产与跨国企业》>>等；尤其是<<前两本必看>>，因为西方经济理论他们是主流，然后看一个国内经济学专家对西方经济学理论的分析文章，这个感兴趣的读者可以上万方数据网去找<<经济学文献>>看，这样久而久之，在头脑中就有了西方经济学的根，当然要看经济博弈光看这个还不够，还要看宋鸿兵的<<《货币战争》1，2>>；这两本书不错，能使你知道西方货币资本血淋淋的博弈史，和各种出招数，是难得的科普教材，这样你在看西方经济新闻的时候，就能看出一点门道来了，并能进行恰如其分的分析。当然你还必须看中国出版的<<《年度世界经济概论》>>，这也是很初级的读本，能使你在头脑中的根与潜意识更清晰，更通俗，更实际。再说中国经济吧，你必须读<<《宏观经济理论》>>、<<《微观经济理论》>>、<<《城市经济学》>>、<<《区域经济学》>>、<<《农村经济学》>>、<<《国家经济学》>>>以及<<货币理论>>和<<货币衍生品>>；总之一句话就是全面的了解中国经济的各个方面，每一大面都不错过，然后你在看看<<国务院经济发展研究中心和中国银行专家出版的书>>，譬如<<巴曙松>>的书<<李若谷>>的书，看一下中国经济大战略走向，和中国金融走向分析的书，这样你就基本成一个国内专家了，脑子里的根形成了，分析新闻就一点问题没有了。老军001经济学领域的那点根就是这样形成的。

再说<<哲学>>，所谓看哲学就看思维，我们通过看别人的哲学能够预知别人的原始动机，别人思维问题的方式，形成的习惯，和政治套路，当然看西方哲学家写的著作是很累人的活，也不是一般人能理解的深度，但是作为能读懂世界的知识要求，老军001认为看一下<<《哲学史》>>、<<《西方哲学史》>>、<<《西方现代哲学》>>、<<《西方政治哲学史》>>，等普及的知识，把西方从古至今的心里所想和思维习惯以及政治套路都有个大概的了解，知道人家的中心是什么，是一个什么样的思维国度，总之西方哲学家的各个流派在你心目中要有一个能仗量的“度”，这个“度”与军事上的潜意识模型和经济上的根对等。能“度”完别人还要能“度”自己，所以你要看<<《中国哲学史》>>、<<《中国文化思想史》>>、<<《中国现代哲学》>>等，了解自己，把自己心中的那个几寸几两的“度”与别人的“度”放在不同的大脑储存空间，遇到与西方人打交道时就想一想这哲学领域里面“度”的差距，（常常通过关注国际冲突想象）这样能更好的把握分寸办理国际事务，有了这个初级的水准，你再看看国家政府首脑的出访，官方所说的话语，就是那么有分寸，有“度”，掌握了火候。久而久之，你的哲学修养与思维就跟上了国际大事的发展。

再说说<<科技>>、<<文化>>、<<历史>>、<<法律>>等几个大面，简单说说吧，科技要看每年一度的中国科学院编写的<<《年度科学发展报告》>>，文化要看<<《世界各国文化战略概述》>>、<<《中国文化战略》>>等，历史看<<世界史>>和<<中国通史>>就行了，法律看<<《世界法律史》>>、<<《中国法律》>>、<<《新中国法律60年》>>等，同时密切关注这几个方面发生的<<新闻大事>>，记在脑子里作为知识点，还要<<把这些知识作为充实和完善上面提到的军事潜意识和经济上的根以及哲学上的“度”的外延>>，这样就使你成一个能读懂世界的多面手了，你可以说就是一个复合型人才了。

#+begin_center
老军001写于2010年11月23日
#+end_center




