# -*- org -*-

# Time-stamp: <2011-08-04 00:09:04 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 2005年6月17日 星期五

** 赖斯：中国军事崛起令美感到威胁

【华盛顿消息】在周四的记者会上，美国国务卿赖斯再次表示中国军事的崛起让美国感到威胁，她表示这是美国阻止以色列向中国出售军事科技和武器的主要原因。

周五启程出访之前，美国国务卿赖斯在记者会上被问到美国阻止以色列向中国出售武器的问题时说，中国的军力增长让美国担心自己在东亚及太平洋地区的利益，包括以色列在内，有意向中国军售的国家应当对这个问题持续关注。

美国国务卿赖斯：“我们认为完全有必要象以往一样关注中国军事能力的增强，因此以色列应该对这个问题非常敏感。”

记者会上赖斯也再次提及朝核问题，她明确指出朝鲜是否重回六方会谈虽然是目前关注的焦点，但是更应当关注的是如果朝鲜回到谈判桌，是否愿意就消除核设施等实质问题作正面的对话。

赖斯：“仅仅回到六方会谈是不够的，朝鲜应该愿意复谈并且关注要谈的内容，那就是销毁朝鲜的核计划。”

赖斯将于周五出访，首站将是以色列。加沙撤军协议和未来的执行情况，将是她分别会见以巴领导人的重点议题。其后赖斯会分别到约旦，埃及和沙特阿拉伯停留，短暂访问之后将会转往布鲁赛尔出席伊拉克援助大会，最后在伦敦参加8国集团的总理会晤。


【时事点评】这几天，美国和以色列之间、正为以色列向中国出售有关军事科技的事情而闹得不可开交，有意思的是，就在美国国务聊赖斯以“中国军事的崛起让美国感到威胁”为由，阐述美国为何要阻止以色列向中国出售军事科技和武器的时候，向来对中国强硬，前几天还在兜售“中国军事威胁论”的美防部长拉姆斯菲尔德却在另一个场合说了一番立场相反的讲话，声称“中国现在或未来一段时间内不会对美国构成威胁”。

东方军事评论员认为，赖斯在临去以色列访问之前，“突然感受到”“中国威胁了美国”，绝非什么是几架“哈比”无人攻击机的因素，期间，有军事专家就指出，真正让华盛顿感到不自在的是来自中国海军方面的一些进展。

在我们进一步展开我们的观点前，先来看一段相关报道，看看在美国人眼里，中国的海军再过几年之后，大概将拥有一个什么样的实力。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 美日制定联合作战计划、一旦需要封锁中国海上通道

【东京消息】据报道近日，“美日联合作战计划”被日本媒体曝光，其中许多“大胆假设”和极力渲染，显示了日美两国为了打造东亚军事联体而无所不用其极的“良苦”用心。

许多军事专家表示，这一计划明显针对中国。根据这一计划，当所谓“台海有事”时，美日就可以采取针对中国的联合行动。

封锁中国太平洋通道

据日本《产经新闻》近日披露，根据“美日联合作战计划”，美军将在太平洋地区部署新的航母战斗群。

《产经新闻》报道称：“美日军官认为，假设台海发生战事，中国‘侵略’了日本的西南群岛，日本的陆上自卫队可以紧急出动中央应急集团，迅速投入约9000兵力，夺回这些群岛。但这并非‘万全之策’。强化日美责任分担这个任务，比想像中更紧迫。”

据美日分析，“2015年，中国将拥有台湾海峡的制海权和利用潜水艇获得海上封锁的能力”。

因此，在美日联合行动计划中，美国打算提高陆海空的综合协调作战能力，建设夏威夷和关岛的核潜艇基地，增强战略轰炸机的战斗力。最重要的是，美国海军还将在日本附近的西太平洋海域部署一个新的航母战斗群。

报道称，中国被美日划在了“不稳定弧线”内，美国要阻止中国自由进出太平洋，为此，必须把日本建设成最前线的战略基地。日本媒体指出，美国的对华基本政策可谓是缓和的“包围战略”。一旦中美转为敌对状态，美国就马上对中国实施“封锁”。

共建导弹防御系统

除了部署新的航母战斗群之外，美日两国政府还计划以部署导弹防御系统为契机，在驻日美军横田基地内，由驻日美军和日本防卫厅共同组建“联合作战指挥中心”，构建美日两军的联合作战指挥系统。

据日本共同社报道，美日联合作战指挥系统形成之后，通过美国的预警卫星，美日双方就可以同时掌握他国发射弹道导弹的确切情报，并立即指令具有拦截弹道导弹能力的海上自卫队、“宙斯盾”驱逐舰或者防空部队，就地实施拦截。



【时事点评】事实上，就如我们在军事点评中多次指出的那样，华盛顿在对中国军力“说东道西”的时候，似乎总喜欢关注中国的常规军力的提高。然而，谁都明白，中国在常规军力方面，特别是海军常规军力，与美国独霸世界海洋的海军相比，不仅没有办法相比、在可见的将来，也不可能在远离中国海域的地方、给美国的海军制造致命的威胁。

这不，按美日的分析，“2015年，中国将拥有台湾海峡的制海权和利用潜水艇获得海上封锁的能力”，不难看出，如果中国海军到了2015年也不过如此的话，那么，日本大可放心地跟着美国介入台海战争、也可以大胆地配合美国对中国实施海上“封锁”。


*** 唯一可以对美国造成致命威胁的中国海军核力量的进展情况，美方反倒是总是喜欢“闪烁其辞”

有意思的是，对唯一可以对美国造成致命威胁的中国海军核力量的进展情况，美国官方反倒是总是喜欢“闪烁其辞”、其中的原由恐怕只有华盛顿心里最清楚。

就在刚才，我们得到一则经日本官方证实的消息称，中国海军一艘新型核潜艇于16日晚、在中国青岛港的外海、成功发射一枚“巨浪2”型潜射弹道导弹，在飞行几千公里之后，导弹击中了新疆内陆沙漠中的目标。

此外，军事评论员也注意到，“消息”还认为，发射这枚射程至少为8600公里的“巨浪2”的载体，就是中国自行研制的“094”战略导弹核潜艇。显然，在我们看来，真正能让赖斯突然感受到来自“中国的军事威胁”，恐怕只有中国在战略核打击力量方面的进展了。


*** 要想准确掌握导弹弹头情况、和发射的准确参数，必须“抵近侦察和监控”

我们知道，在研制弹道导弹的过程中，研制者为了准确把握导弹技术性能和相关参数，通常要进行数次导弹试射。在这一过程中，一个常识是，为了安全起见，导弹发射国通常将导弹试射地点选在浩瀚的大洋或是偏僻的沙漠戈壁之中。

东方军事评论员认为，由于中远程弹道导弹采取的均是“返回大气层式”发射技术，因此，不论是中国、还是俄罗斯、美国、都有能力通过空间预警卫星、地基探测雷达等设备对导弹发射情况进行“监视和跟踪”。

然而，就目前的各国的技术水平来看，谁都没有把握通过远程预警雷达就“很精确地跟踪目标和分辨弹头、诱饵或是其它假目标”，因而也就不能准确提供导弹“弹着点信息和相关参数”。

一般的做法是，如果要想准确掌握导弹发射的准确参数，必须派出导弹观察机、海洋测量船等专门力量实施“抵近侦察和监控”。


*** 日本人根本就没有这种全程侦察、精确定位的实力


在我们的记忆中、最近的一个例子是在1998年末，中国在筹备一次发射“东风―31”导弹的时候、美国情报部门发现了一丝“蛛丝马迹”，为了获取“弹着点的精确参数”，美军迅速向西太平洋地区派出“观察岛”号导弹跟踪观测船和RC―135S型导弹观测机来监视此次发射活动，但令美国人感到非常失望的是，出于“保密参数”的因素，中国当时并没有将导弹射向太平洋方向、而是射向了中国内陆。

东方军事评论员认为，尽管这一次“最先捅出”消息的是日本人，但是，日本根本就没有这种全程侦察、精确定位的实力。不难想像，如果日本官方的消息属实，必然是从“别的什么渠道”获取的，如果不是，那就是在那里“闭门造车”了。


*** 这则“消息”的可信度仍然“有待鉴定”

在我们看来，由于我们至今仍然没有从中国官方渠道获得证实，也没有否认的报道，因此，这则“消息”的可信度仍然“有待鉴定”。然而，如果此消息属实，那么，可以肯定的是，除了中国之外，最先“探测到全过程”的、恐怕是美国人和俄罗斯人。奇怪的是，“美俄”方面与中国一样，仍然没有正式的消息出来。

因此，在我们继续等待“中俄美官方”消息的时候，简单谈谈“如果消息属实”的重大意义。


*** 英国前国防大臣的一句“大白话”点破了“等效核均势”的核心意思

英国前国防大臣皮姆曾经在冷战期间、冲着拥有足以毁灭地球100次核弹的苏联、就说过这么一句非常形象的“大白话”，他说，即使英国只有一艘“北极星”战略导弹核潜艇可供使用，也足以给苏联造成不能承受的破坏。

在东方军事评论员看来，这句“大白话”有两层意思：第一，它点破了“等效核均势”的核心意思，即：不管你的核武库是否达到了万枚、或者更多，你的核攻击力量多么强大和先进，但在承受真实的战略核打击方面，你同别人一样脆弱，事实上都不能承受十几、二十枚核导弹的打击。


*** 战略导弹核潜艇是"三位一体"核力量中最具威力的一部份

第二，这句“大白话”也“点明”了战略导弹核潜艇在一个国家战略打击力量上、可以充当最核心角色，即，战略导弹核潜艇是"三位一体"核力量中最具威力的一部份。

在我们看来，核战略潜艇之所以最具威力，是因为它是“潜伏流动的导弹基地”。其最大的特点在于一旦需要，它可以在长达几个月的时间内隐蔽在“四大洋”的深处，并将足以让任何一个国家都承受不了的核打击力量“背在身上”、是走到哪里带到哪里，甚至可以前出到敌国海域，在“敌国的家门口”建立发射阵地。

这样，哪怕国土上的军事设施已被敌国第一波核打击悉数摧毁，或者是陆基核导弹被有效拦截，我方就是仅剩下最后一艘战略核潜艇，那么，其拥有的核报复能力、也足以让对手彻底瘫痪，从而给对手造成不能承受的损失，这也就“实现了”所谓的“等效核均势”。


事实上，现在拥有战略导弹核潜艇的国家只有美，中，俄，英，法五个联合国安理会常任理事国。从这一点上看，就知道联合国“五常”之所以可以“共同主持着”世界，绝不是仅仅是“经济上够强”就可以胜任的、任何一个国家要想成为一个政治大国，首先就得是个军事大国、核大国。

“五常”之中，地域广阔的美俄，在冷战期间都已经发展出了庞大的“陆地、空中、水下”“三位一体”的核打击力量，而国土狭小的英国和法国、则主要依靠水下核打击力量、而只有中国，尽管也算得上拥有“三位一体”的核投射能力，但是，严格来讲，能形成威慑的全球战略核打击力量、主要是陆基的。

中国目前唯一在役的一艘战略核潜艇，是“夏”级核动力弹道导弹潜艇，严格上讲、“夏”级技术上是落后的、即使已经经过改装、携带了“巨浪二”，但因为整艇噪声大，很容易遭受敌方反潜力量制约，事实上也没有自由进出世界各大洋，无法对欧美实现真正的二次核打击力量。


*** “如果消息属实”，这将是中国战略核打击力量的又一个里程碑

众所周知，长期以来，关于中国战略核打击力量，西方有太多“自相矛盾”的说法，我们注意到，众多说法中、一个最流行是版本是认为中国有“20-25”枚洲际运载导弹，不超过400个核弹头，其中，有四分之一，也就是约有100个弹头可以打击美国本土。显然，在东方评论员看来，这种最流行的版本，显然没有将中国的战略核潜艇的核打击力量计算在内。

因此，在东方军事评论员看来，如果此次发射成功的导弹是“巨浪二”、载体也的确是传说中的“094”战略核潜艇的话，那么，由于“巨浪二”潜射战略导弹，可携带六至八枚分导式重返大气层弹头，体积也大幅缩小，使载体“094”战略核潜艇可搭载16至20枚导弹，一艘“094”将有能力一次发射一百个以上的核弹头，按上述“流行版本”的计算结果，那么，这就相当于将“中国陆基核导弹可以打到美国的弹头数”、搬到了隐蔽性极强的大洋深处，显然，这将是中国战略核打击力量的又一个里程碑。


*** 对中国的核规模，美国不过是在那里“捕风捉影”地“猜猜猜”而已

事实上，由于中国官方对中国核战略力量的具体规模，从来就是“绝口不提”，因此，在包括美国在内的许多西方国家、本质上都不过是在那里“捕风捉影”地“猜猜猜”而已，在东方评论员看来，上述这个“最流行版本”也是这样产生的。

在我们看来，由于中国“夏”级战略核潜艇上的“巨浪一”、或者“巨浪二”从不入国外情报机构的“法眼”，因此，那么版本繁多的猜测中、主要的“猜测对象”就是中国的洲际弹道导弹ＣＳＳ－４，也就是“东风５号”。

据西方情报机构公布的资料，东风５号最早于１９８１年部署，射程１２０００千米，投掷重量４4００磅，弹头当量４００万～５００万吨，部署在加固的地下井内，数量10～2０枚。


*** 美国防部情报局的一份报告、最能体现出“猜测的色彩”

东方军事评论员注意到，在众多的“猜测版本”中，特别以美国国防部情报局的一份报告最能体现出“猜测的色彩”，该报告说：“也许中国已制造了另外５０枚导弹（亦可能生产１００～１５０枚），但尚未决定作为实战部署的导弹还是作为空间发射飞行器使用。”

直到不久前，美国情报部门仍然在“一再声称”：“中国有约２０枚可达美国不少地区的洲际导弹，到２０１５年还可增加数十枚，包括二三十枚机动导弹。”

显然，传说中的“094”，是绝不会拖到2015年才会服役的，因此，美国情报部门所说的、中国可攻击美国的洲际导弹“到２０１５年还可增加数十枚”的说法显然“太低估”中国军事工业的产研能力、尤其是这种估算中“还包括有二三十枚机动导弹”。

非常清楚，那“二三十枚机动导弹”指的是“早闻声且已见面”的“东风31型”、或者是“已闻声却未见面”的“东风41型”。



*** 从历年中国官方一系列“正式、非正式”的表态上、看看中国核打击力量“到底如何”？

然而，事实上，对上述的“各种消息”我们也“无从求证”，因此，就本质而言，我们也是在和美国情报机构“做着同一件事情”，即：也是在这里“猜猜猜”。

但是，军事评论员也认为，虽然中国核武器和战略导弹的种类、数量、性能等方面始终是谜，但是，经过我们的长期观察，从历年中国官方一系列“正式、非正式”的表态上、我们也可以“猜出个大概”来。


我们知道，核打击力量是最具威慑力量的政治和军事手段。因此，中国的核力量，总是在“最需要体现其威慑价值的时候”、被中国官方有意无意地掀开一个角，并以此同时实现政治、军事上的双重目的。

在我们的《备忘录》中，1999年，面对美国的一份《考克斯报告》的“谎言连篇”、指责中国偷窃美国的中子弹和核武器小型化技术，中国国务院新闻办主任赵启正就曾经不屑地驳斥说：20年前中国就已掌握了中子弹和核武器小型化技术。


在我们看来，直到2001年，布什上台的时候，中国还非常喜欢说“中国只保留最低限度的核威慑力量”。然而，“这种偏好”，随着华盛顿将美国新保守主义全球战略加以实施、北京也不再有兴趣去“不断声明”了。

东方评论员注意到，近几年来，“中国只保留最低限度的核威慑力量”的“说法”、已经从中国官方的“宣传语言”中给正式删除了、增加的正是一些“非常露骨”“中国有决心准备使用自己的核战略打击力量的语言”：

其中，在2002年，熊光楷上将就曾经说过“我们可以把核弹打到洛杉矶”。而在东方评论员看来，中国有史以来最为直白的一次披露，则是在2004年，在台海局势最为紧张的时刻，中国军方的一位中将针对美国国防部发布的《中国军力评估》中所说的“考虑攻击三峡大坝”，也直接以威胁的口气公开地加以反击、并指出“中国是个拥有全套核手段、令任何敌人生畏的核对手”，“美国能炸中国的三峡水库，中国也可以炸美国的胡佛大坝”。

显然，在东方军事评论员看来，从中国官方这些“公开的、不再遮遮掩掩的”讲话中可以捕捉的信息是，中国不仅已经是个“拥有全套核手段、令任何敌人生畏的核对手”，而且也有“敢于用核”的决心。

谁都知道，华盛顿之所以敢对中国说出“考虑攻击三峡大坝”这类威胁的话，根本原因在于华盛顿根本“不相信”、或者出于自己的战略目的、“根本不愿意相信”中国也有摧毁美国的“核规模”。


*** 西方国家猜测中国“到底有多大的核规模的”“标准”

对此，东方军事评论员认为，这也难怪，因为长期以来，尽管中国早就有了全套的战略核打击力量，但是，基于“不首行使用核武器”、和“不称霸”的原则，中国官方非常喜欢“不断声明”“中国只保留最低限度的核威慑力量”。

事实上，也正是根据“中国只保留最低限度的核威慑力量”的说法，美国也一直在以“中国保留最低限度的核威慑力量”为“标准“、去猜测中国到底有多大的核规模的。

在中国制造出东风31型车载洲际核导弹之前，美国的情报是根据卫星反复观测的结果，其理论根据竟然是“中国洲际导弹无法机动发射，通过观测可能的发射阵地，也就可以得出“相当精确的结论”了”。当然啦！美国人也毕竟是猜测出来了，这就是“最流行”的“20枚导弹”。


*** 中国开发出东风31型车载洲际导弹之后，美国又提出了新的“估算理论”

我们还注意到，据西方军事专家分析，中国的“东风31”洲际导弹、其整体技术已接近美国“民兵”Ⅲ、俄罗斯“白杨”―M等同类导弹水平，是中国目前生产的威力最强的导弹、配套的生产技术非常复杂。

因此，非常有意思的是，在中国开发出东风31型车载洲际导弹之后，由于“只数可能阵地”的理论“没有了根据”，美国又提出了新的“估算理论”，即根据所谓的“中国最大生产能力”来为中国可以打到美国本土的核弹头“号脉”。当然了，美国人也“号”出来了，这就是所谓的“100枚弹头”。

然而，在东方军事评论员看来，如果“上述的那些理论果真值得信赖的话”，那么，美国五角大楼手中的那份、“最新”、却又“难产”的《中国军力报告》又何来的那么多的“诧异”、与“失察”呢？


*** 华盛顿喜欢“如此低估”中国的核战略打击力量的一个重要原因

对东风31型，媒体上的报道甚多。但有一点可以肯定的是，陆基东风31型已经形成战斗力。可问题是，其数量与打击覆盖面“似乎仍然不能让美国相信”它将会遭到彻底毁灭、并由此带来某种恐惧感。

我们认为，只要中美核力量还存在着较大差距、中国未对美形成真正的、有把握的全面摧毁，而仅有最低限度核反击的前提下，美国在对华战略上，始终会将核力量作为威胁中国的最后手段。事实上，“这一理论”正是美国防部向国会提交的一份绝密《核态势评估报告》中、敢于将中国明确列入核打击目标的根据。

在东方评论员看来，华盛顿之所以喜欢“如此低估”中国的核战略打击力量、其中一个重要企图就在于：只要中国不能证明自己拥有“有把握摧毁美国”的终极核威慑能力，美国就始终会强调并让“台独”和支持“台独”的其它国际势力（主要是日本）相信：美国在未来可能的台海冲突中“将会全面军事介入”，并以此来操纵“台独势力”和“台湾民意”。


*** 值得注意的美国《核态势评估报告》

我们注意到，在《核态势评估报告》中，明确表明，美国军方可能会使用核武器的三种紧急情况可以概括为：第一，对付那些一切非核武器无法摧毁的目标；第二，在美国受到核生化武器攻击时进行报复；第三，对付出人意料的军事态势发展。

此外、报告还进一步列举了美国可能动用核武器的情势和潜在的地区，例如阿拉伯国家与以色列爆发全面冲突；东亚地区爆发战争等。这其中东亚地区的冲突、明眼人是一看就知，这是明确地指向台海与朝鲜半岛这两个、均涉及到中国军事力量的区域。

显然，根据美国现行的核战备，东方军事评论员认为，该报告明显是在“警告”中国，即：如果中国在台海与美国对抗时取得初步的胜利，比如说出现了“击沉美国一艘或数艘航空母舰、美国面临无法用非核力量取胜”，以及“美国遭遇了出人意料的军事态势发展”这两种军事形势，都足以使美国启动核武器系统开始对中国进行核打击。


*** 这份“绝密报告”被华盛顿有意识地曝光

不难看出，这份“绝密报告”被华盛顿有意识地曝光，就是说给中国、“台独”、及支持“台独”的其它国际势力（主要是日本）听的。

在东方评论员看来，不论美国曝光这份报告的用意何在，都说明了一个关键问题，那就是，只要中国始终“不能向方方面面证明”、已经拥有“有把握摧毁美国”的终极核威慑能力，那么，出于美国的战略目的，华盛顿就始终敢、也有空间玩这种“为了台湾它敢与中国打核战争”的把戏、非常明显，华盛顿玩这种把戏的根据、就是面对“只有20枚洲际核导弹的中国”，美国非常自信、并且在拼命让台独和日本相信，它能凭借在“核威慑和核保障上”的优势、即使是核战争下、确保美国也能是最后的胜利者。


*** 北京必须客观地看待美国的导弹防御系统

显然，东方军事评论员认为，美国的“这种自信”不仅来自中国现有的核威慑能力“只能部分威慑美国”，也来自美国正在发展中的导弹防御系统。在我们看来，美日正在联手打造的导弹防御系统、是“有可能削弱”中国相应的对美核威慑能力的。

就如我们之前多次所说的那样，北京必须客观地看待美国的导弹防御系统，东方评论员认为，在目前状况下，它既不是完全有效，同样也不是完全无效的武器系统。因此，在我们看来，如果北京“完全轻视”、或者“盲目夸大”美国导弹防御系统的作用，都将是极不明智的。


*** 中国决策层是务实的，眼光也是长远的

值得欣慰的是，近年来中国全力发展东风31、41型战略核导弹、和太空技术的事实说明，中国决策层不仅“没有完全轻视”美国正在发展中的导弹防御系统、更没有“盲目夸大”这套系统的作用。

在首席评论员看来，中国全力发展东风31、41型战略核导弹、和094战略核潜艇，说明中国决策层“注意到了”导弹防御系统对中国“现有的”、主要是陆基战略核打击力量的威胁，就这一点而言，中国的决策层是务实的；

而我们也注意到，中国在注重水下核打击力量的同时，仍然非常注重发展太空技术，这本身说明中国决策层的眼光也是长远的。显然，全力发展东风31、41型机动部署战略核导弹、和094战略核潜艇，这意在“提前突破”美国导弹防御系统的基础上，同时建立一套对美国的全面核威慑力量。



*** “导弹防御系统”在没有完全开发出来、其“技术指标”就已经部分过时了

根据一些公开的报道，东风31型洲际导弹具有很强的“限程”打击能力，即指挥员可在导弹的最小射程(1000公里以上)和最大射程之间任意选择目标，并采用调整燃料剂量、修正弹道参数等方式来“限制”导弹射程，从而使对手在导弹发射后难以确定打击目标，并继而采取有效的反制措施。

另外，国外军事分析人士还认为，中国的“东风31型”导弹已经采取了各项先进技术：如改进的移动导弹发射系统、高强度弹体和高载荷技术、诱饵及假弹头渗透技术以及高能量的固体推动燃料等。

显然，如果“这些分析是事实”的话，那么，“这些美国人自己都没有的先进技术”是否又被列为“偷窃于”美国的军事技术，我们还不得而知，东方评论员也只能“等着瞧”了，只是有一点是清楚的，那就是，东风31型身上的这些“现有技术特征”，本身就已经令美国日本正在拼命发展的“导弹防御系统”在没有开发出来的时候、其“技术指标”就已经部分过时了。


*** 美国的“宣传套路”离谢幕的时间也不远了

东方军事评论员认为，东风31型的许多用以突破导弹防御系统的新技术，以及东风31型衍生出来的“巨浪二”潜射战略导弹、及其水下载体“094”战略核潜艇的进展顺利，都说明离中国“用事实证明”中国将向俄罗斯那样、确保拥有彻底摧毁美国的核打击力量的时间已经不远了。这就是说，美国在向方方面面证明“它将依靠核优势、一定会介入台海战争”的“宣传套路”离谢幕的时间也不远了。


另外，有西方媒体报道说，中国在加快提升核威慑能力的策略上，是两条路同时走。就在中国建造“094”战略核潜艇，并将“东风31”“拉下海水”、用“射程8600至12000公里”的“巨浪二”武装“094”的同时，中国军方还在将““东风31”“拉上铁路”、开发成用铁路机动的“东风41”。

在东方军事评论员看来，由于铁路机动发射弹道导弹技术要求极高，核战争条件下生存力极强，目前得到证实的只有俄罗斯拥有此技术。因此，我们认为，如果中国开发成功的话，那么，中国战略导弹部队的机动性和隐蔽能力都将大大增强，也使美国跟踪监视导弹发射的难度大为增加，中国的战略核打击能力在继核潜艇发射弹道导弹成功后、也将再次实现一次质的飞跃。


*** 为有朝一日破解、或干扰“美日”导弹防御系统在“做技术准备”

而北京注意太空技术的发展，其战略意义是“全面而重大的”，抛开其他方面意义不讲，在东方军事评论员看来，就中国核战略力量的建设这一层面而言，这本身就是为有朝一日破解、或干扰“美日”导弹防御系统在做技术准备。不要忘记了，美国导弹防御系统、其信息采集、协同指挥，都依赖美国的太空通讯。

不可否认的是，攻击太空系统、远比维持太空系统的正常运转、要便宜得多、也方便得多。显然，针对美国太空信息系统的攻击或者干扰，将是针对导弹防御系统“最具效率的”攻击手段。

另外，太空武器将是今后世界军事发展的一个关键方向，谁在这一领域占有一席之地，才能在今后的全球军事角力中占据主动地位，不难看出，在加大太空投入、开发太空武器的方向上，北京显然有非常超前的认识，也已经取得了一个“高起点”。

*** 当中国建立起一套完整的“二次战略核打击力量”之后

在东方军事评论员看来，当中国建立起一套完整的“二次战略核打击力量”之后，特别是当中国战略核潜艇可以前出到太平洋、“向前”、其核导弹可以威胁美国本土，“向后”，可以避开美日沿第一岛链、面向中国、俄罗斯方向布置的导弹防御系统、用核导弹直接威胁日本本土的时候，令美国人非常自信的核威慑优势、以及美国凭借自己的核优势为日本撑开的核保护伞，到底有多大作用，恐怕就得全部重新估算了。

然而，还有消息说，“美日”两国将于明年3月在夏威夷共同进行“标准-3”型海基拦截导弹的首次拦截试验。东方军事评论员注意到，对此，就有日本媒体认为，这一“实验”意义非同寻常，根据是“它意味着美国将允许日本直接和自己一起，使用最先进的导弹防御系统”。

然而，事情果真如此吗？起码在军事评论员看来，由于“等效核均势”的理论“是现实的”，因此，一心想让别人相信一定会介入与中国的军事冲突的华盛顿，在获知中国军力有一连串的“出人意外”突破之后，于几天前宣布进行的这一实验、似乎更能表明华盛顿有意借助导弹防御计划的“某种突破”、来确保自己的核优势。在我们进一步给出自己的观点前，再来看一则来自美国国防部的消息。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
