# -*- org -*-

# Time-stamp: <2011-08-02 20:46:40 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

#+STARTUP: indent

*  2005年4月26日 星期二

** 连战抵达南京终于迈出历史性的一步

【南京4月26日消息】中国国民党主席连战率领中国国民党大陆访问团26日16时40分许抵达南京，开始其60年来首次大陆之行。中共中央台湾事务办公室主任陈云林、副主任李炳才、中共江苏省委副书记任彦申、江苏省台办主任陈尧等官员以及台商代表三百多人到机场迎接。

连战一行26日上午从台湾抵达香港后，换乘上海东方航空公司班机直接至南京。中国国民党副主席江丙坤、吴伯雄、林澄枝、秘书长林丰正、政策会执行长曾永权、文传会“主委”张荣恭等同机到达。


飞机抵达后，禄口国际机场两辆客梯车分别在飞机的前、后舱门接参访团成员走出机舱。连战和夫人方瑀自前舱门走出机舱，并挥手向欢迎的人群致意。两名少年儿童迎上前去，向他们敬献鲜花。

连战：终于迈出历史性的一步

连战在南京禄口机场停机坪发表演讲。他说，这是一次间隔了整整60年的访问，有一种相见恨晚的感觉，但终于迈出了历史性的一步。

连战表示，中国国民党非常的想念大家，也非常的思念大家。

他说，就历史来讲，南京曾经是国民政府的所在地，是中山先生陵寝的所在地。今天本人能够率同中国国民党工作的同仁大家一起来到南京，向中山先生致以最高的敬意，这是我们全党共同的心声，也是众多人民共同的一个期盼，我深深的感到此行真是难能可贵。

连战说，这次到大陆来访问，对于两岸如何能够营造一个互惠互利和平双赢的未来，是大家所关心的一个问题。中国国民党访问团愿意为和平稳定的两岸关系尽绵薄之力，也希望各界人士、所有团体，能够同心协力，一起奋斗，一起努力。

据报道，26日晚江苏省领导将会见并宴请连战一行。27日上午，访问团将赴中山陵拜谒伟大的民主革命先行者孙中山先生的陵寝。随后，访问团还将游览世界文化遗产“明孝陵”，以及“总统府”、夫子庙等景点。4月28日访问团离开南京。

期盼两岸向双赢道路迈进

26日上午10时30分左右，连战一行乘坐专车抵达台北桃园机场。随后连战发表了简短的谈话，对冒雨前来送行的民众表示感谢。连战强调，希望通过这次的访问，了解大陆最近以来各方面的发展实际情况；另一方面，也希望利用这次机会和大陆领导人针对两岸大家所关心的和平和经贸交流进行意见交换。他期盼两岸同胞掌握这一历史契机，向“互惠、互动、共存、共荣”的双赢道路迈进。

亲民党主席宋楚瑜26日上午前往机场送机。连战等人走向登机舱前，先趋前和宋楚瑜握手。宋楚瑜和连战互相勉励为台湾乡亲一起打拼。宋楚瑜一声“祝福”，连战也回以“感谢，感谢”，并且互道“加油，加油”。


【时事点评】今天，东方评论员也一直在等待连战抵达南京的画面，在我们看来，这的确可称得上是个历史性的事件，就连战从台湾桃园机场“起飞”开始，可以说两岸关系就是一个新玩法了。

*** 大陆就处处体现出“给连战以体面”

还在台湾桃园机场时，当我们发现宋楚瑜竟然“也夹在”冒雨欢送连战的人群中、“干望着”连战“先行一步”时，我们不竟摇头：早知如此、是何必当初！在我们看来，在整个过程中，从连战在香港“转机”开始，到南京飞机降落为止，大陆就处处体现出“给连战以体面”。

就如我们昨天所讲的，这种体面本来是宋楚瑜最有机会“抢先体味”的。在我们看来，自华盛顿被迫高调“反台独”、而北京仍然不为所动启动“反分裂国家法”、两岸间的某种形式的“和谈”就成了必然。

*** 宋楚瑜并没有看到东亚局势竟会是这样的一种局面

事实上，在政坛上浸淫了几十年的宋楚瑜是看到了这一点的，也正是如此，他才最敢呆在华盛顿时就有目的的放风说、要“登陆”中国大陆。然而，宋楚瑜并没有看到东亚局势竟会是这样的一种局面，即：中国在通过“中印和解”抓到了一大把筹码之后，就立刻在日本入常的问题上开始反击“美日同盟”，并首次将矛头直指日本、在日本“做最后的尝试”、宣布将向日本企业发放东海资源勘察许可证这一极端挑畔动作，想以“中日关系决裂”的危险来威胁北京、压迫中国让步时、北京果断地利用日本外相访华、名义上是要求中国道歉、实际则是迫使中国在历史问题上让步的机会，拉高姿态、放出中日关系“何去何从”的“胜负手”、将球彻底扔给日本，从而迫使“小泉纯一郎道歉”、暂时在中日的这一轮角力中“低下了头”。


*** 错判东亚“中美日”角力的形势，宋楚瑜过早地将自己卖给了华盛顿

东方评论员认为，以此为标志、华盛顿想利用印度从南亚、利用日本从东亚两个方向给北京施加压力、从而让中美间“更多地按有利于华盛顿”的方向、“去制定包括台湾、朝核、日本问题的一揽子东亚政策”的努力彻底“落了空”。显然，对宋楚瑜而言，不幸的是，他没有看出“中美日”间，在这几个月来的“拳脚相向”，打出的却是这样的一番结果。

首席评论员指出，如果不是宋楚瑜错判了东亚“中美日”角力的形势，导致过早地将自己卖给了华盛顿，从而在华盛顿的安排下去与陈水扁和解、从而“在事实上答应”以陈水扁的“代言人”的身份访问大陆的话，那么今天从飞机中走出来的应该是“最先想到”要借“大陆行”打开局面的宋楚瑜。

东方评论员注意到，连战在南京禄口机场停机坪发表演讲。他说，这是一次间隔了整整60年的访问，有一种相见恨晚的感觉，但终于迈出了历史性的一步。

的确、根据时事评论员对连战“统独立场”的了解，这是他的心里话，可以说一点都没有虚假的成分。事实上，根据资料，在李登辉“最恨”连战的理由中，早年连战就有“想回大陆看看”的这一条、正是李登辉对他最为“耿耿于怀”的。

然而，心情归心情，相法归想法，连战直到宋楚瑜“倒戈”、去与陈水扁搞了个“十点共识”、从而为陈水扁所利用，欲以所谓的“中间路线”去瓦解国民党、终结连战的政治生命之前，连战和他的国民党、终究都是“不敢回大陆看看”。


*** 走投无路的国民党、“要活下去”的唯一的出路、就是访问大陆

东方评论员认为，对还没有从“立法选举泛蓝用出”的虚假胜利中醒过来的连战和国民党而言，扁宋会”的后果是危险的。在我们看来，这种危险性来自两个方面，第一感觉就是“没有了朋友、从而国民党和连战都太孤独”、第二感觉就是“没有前程、从而国民党就没有了凝聚力、内部就是产生离心力而加速分裂”。

由于王金平、马英九“正在争”党主席，可以说国民党是“内外交困”。因此，连战和国民党“要活下去”的唯一的出路、就是访问大陆，象宋楚瑜投靠华盛顿、陈水扁前、当初所设想那样，借两岸关系的突破“再造生机”。

然而，华盛顿、陈水扁又怎么可能让连战和国民党如此轻松就“突破重围”呢？华盛顿在这方面有许多手段、且用起来非常娴熟。


*** 华盛顿操纵台湾民意“功底之深厚”，是大陆暂时远不能与之相比的

事实上，就在华盛顿于去年底突然开始“高调反台独”的时候，其“两面手段”也是一刻也没有停止。在美国做出一系列“反台独”的动作之后，事实上、对台湾的民意产生了巨大的影响，从而在台湾的立法委员选举结果中，造成了“两大失败者”，一个是“立场向来摇摆的”亲民党和宋楚瑜，该党派“立法委员”是大减，而另一个就是“亲日的”急独势力--台联党和李登辉、李登辉甚至可以说可以用惨败两字来形容。

而“向来听华盛顿的”台独势力--陈水扁和他的民进党仍然是台湾的第一大党，且所得“立法委员”也并未减少什么，由此可见，华盛顿在操纵台湾民意方面的“功底之深厚”,应该承认，这是大陆暂时还远不能与之相比的。

*** “两岸和谈”还未开始，华盛顿和台独就已经在为日后“收紧政策”做准备了

东方评论员认为，在华盛顿的安排下，华盛顿对陈水扁、宋楚瑜对已经达成的“中间路线”仍觉得不保险，还要将国民党要么也纳入其中、要么就彻底瓦解它，总之，让一支有别于“中间路线”的政治力量在台湾，就有可能给华盛顿今后继续让两岸绝缘于“两岸三通”的政策带来变数。

显然，在东方评论员看来，“两岸和谈”还未开始，华盛顿和陈水扁就已经在为日后“收紧政策”做准备工作了。我们认为，在华盛顿、陈水扁日后“收紧政策”的过程中，将扮演一个重要角色的，恐怕就是那个马英九了。

为了说明这个问题，我们再来看一段有关马英九评论这次连战历史性访问的新闻报道。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 欲促成两岸共识马英九：连战为扁投石探路

【台湾消息】据台湾媒体报道，国民党主席连战明日将赴大陆展开历史性访问，国民党副主席马英九昨日表示，连战出访大陆是在为台湾的陈水扁「投石探路」，促成两岸共识。连战今日将以「陈先生」称呼致电陈水扁，以口头方式向陈水扁讲述此行赴大陆的意义。

宋访大陆不代表政府

马英九表示，连战这次前往大陆是「历史性的一刻」，连（战）宋（楚瑜）先后到大陆，可视为帮陈水扁「投石探路」，在取得共识后，将来「连宋扁胡（胡锦涛）」，都可争取到诺贝尔和平奖。前日陈水扁曾表示，连宋访大陆如果一切依法，可当作两颗石头「投石问路」，可以给他们祝福。

国民党党务高层昨日表示，连战今日与陈水扁通电话时，会强调两岸和平是朝野要合作努力的共同责任。该名党务高层强调，二人的谈话不是「报备」，且已建议连战称陈水扁为「陈先生」，必要时会公布电话录音。

亲民党秘书长秦金生昨日搭乘航机经香港前往北京，与大陆有关单位落实五月初将到访大陆的亲民党主席宋楚瑜行程安排。秦金生表示，宋楚瑜此行是以亲民党主席身份前往大陆，不代表任何个人或政府。



【时事点评】在东方评论员看来，从宋楚瑜与陈水扁会面的那一刻起，由于已经失去泛蓝民众和北京的信任，事实上宋楚瑜已经被华盛顿和陈水扁挰在手中、而且被挰得死死的，摆在他前面的只有一条路，那就是帮着陈水扁、在以那条根本就是华盛顿“旨意”的“十点声明”和“中间路线”的幌子下，先利用所谓的“中间路线”去“诱骗”马英九这种动摇分子、从而去分裂国民党、继而全面铲除国民党在台湾的存在。

*** 马英九狂拍“中间路线”的马屁

事实上，就在陈水扁“转身”、以一句“连宋访大陆如果一切依法，可当作两颗石头'投石问路'，可以给他们祝福“、是由反对到支持连战“登陆”的那一瞬间，国民党的这位马英九、马副主席，就立刻以“连（战）宋（楚瑜）先后到大陆，可视为帮陈水扁'投石探路'”来拍“中间路线”的马屁。在东方评论员看来，国民党因内部有以此人为代表的一帮子隐性台独的存在、可以说是前途未卜。

当然了，马英九当然也不是傻瓜，在东方评论员看来，连战和国民党落到今天这种四处遭人暗算的田地，有多种原因，其中非常重要的一条，就是被华盛顿所抛弃。因此，马英九心里认定，在台湾这种政治环境中、连战为代表的“反独”没有前途，因为台湾的民意有两个特点，一个是“避战”、二是“反统”、而不是“反独”。

*** 拍“中间路线”马屁、实际上也是拍华盛顿的马屁

东方评论员认为，华盛顿的“中间路线”，实际上正是针对台湾民意这两大特点量身定做的，也是根据美国的全球战略而量身定做的。显然，马英九狂拍“中间路线”马屁、实际上也是拍华盛顿的马屁。

但是，与此同时，国民党内部也有人显然是对“中间路线”不满，在连战被迫和陈水扁通电话之后，国民党另一部分的人、中以必要时“会公布电话录音”的方式来拉开国民党此行与“中间路线”的距离，并以此将连战与陈水扁划清界线的。

*** 少了日本挑畔中国的帮衬、华盛顿在台湾问题上也就承受了北京更大的压力

显然，在北京和华盛顿之间、事实上再次将日本排除在东亚安全决策之外后、少了日本挑畔中国的帮衬、在朝核问题上被北京挰了一头的华盛顿、在台湾问题上也就承受了北京更大的压力，从而，连战也就捡到了因“聪明反为聪明误”、宋楚瑜所“漏掉”的“一鸣惊人”的机会，他也吸取了宋楚瑜与陈水扁“不清不楚”签下了“中间路线”，从而最后被北京“剥去了体面”的教训，从而始终在拒绝陈水扁约他见面的安排。

最后，不得已答应通通电话，结果，还要“严肃地要求”“必要时会公布电话录音”，非常清楚，连战是想与陈水扁和他的那个、让宋楚瑜“还没有出门、就栽了个大跟斗”的“中间路线”划清界线，互不搭界。

*** 马英九“难担振兴国民党的大任”

要知道，就中间路线而言，它根本就是华盛顿的“台独路线”，而陈水扁和他的民进党，事实上已经被华盛顿“钦定”为这一路线的执行者和代言人，你马英九再怎么表现、再怎么套近乎，都不可能取而代之。

可叹的是，那个自视甚高的马英九却偏偏看不清这一点，不仅不远离那个所谓的“中间路线”，反而主动将连战的大陆行拼命“往陈水扁的“中间路线”上面拽”、就凭这一点，马英九就“难担振兴国民党的大任”，而只会成为华盛顿、陈水扁分化、瓦解国民党的帮凶。


*** “另选登陆对象”，就成了北京同意缓和台湾局势、朝核局势的“先决条件”

针对这一点，北京自然也得有相应的策略才行。显然，已经被华盛顿和陈水扁“捕获”的、并失去相当“泛蓝”民心的宋楚瑜，当然不可能让北京相信他有能力摆脱华盛顿的控制，在被华盛顿所迫去帮助陈水扁瓦解国民党时、还有力量去完成他“登陆大陆、以左右逢源、借助催动两岸和平、图东山再起”的计划。

宋楚瑜已经不是先前的宋楚瑜了，事实上经过“扁宋会”，他已经是“中间路线”的正式代言人，也就是说，北京若和宋楚瑜谈，首先在“九二共识”的问题上都难有突破，那后面的问题还怎么谈？

显然，这只能如华盛顿的愿，即“两岸空谈”，“并在空谈中”轻易地让华盛顿得到“其想造成的”“两岸缓和”的事实，反过来又要求北京兑现帮助缓解朝核问题的条件。

这样一来，“另选和谈对象”，就成了北京同意缓和台湾局势、继而缓解朝核局势的“先决条件”。显然，愿意承认“一个中国”的、且正被华盛顿、陈水扁、宋楚瑜合伙边缘化的连战和他国民党中的反对“中间路线”的势力、就成了替代已经不被北京信任的宋楚瑜之“当然人选”


*** 美国人对连战“虽然不喜欢、但还是放心的”

我们注意到，在江丙坤访大陆后，第三次“国共合作”的提法就非常醒目，显然，连战的大陆之行，是否会成为“国共第三次合作”的开始、那就要看连战在大陆“愿意、和敢于签下”什么样的“共识”来。

坦率地讲，东方评论员对第三次“国共合作”这种提法很感兴趣，然而，是否能成达成实质性的、对台湾政治格局产生巨大冲击的内容，还得观察，因为连战的政治魄力不足，在我们看来，这恐怕也是华盛顿“三思这后”之后、“也愿意”满足大陆“另换人选”之要求的关键之所在。

据东方评论员掌握的消息说，在北京拒绝为“中间路线”“捕获”的宋楚瑜“先行登陆”之后，实际上也就是拒绝华盛顿急需的“两岸缓和”之后，华盛顿特意派人去套连战的口气，“想确认”连战是否仍然“旗帜鲜明”地“反对一边一国；反对一国两制；坚定捍卫台海安全”的立场，显然，美国人对连战取代宋楚瑜首先登陆，“虽然不喜欢、但还是放心的”。

*** 北京和华盛顿这一“幕后的角力”，正好发生在气势汹汹的日本外相“在北京败北”之后

在这里，有必要强调的是，北京和华盛顿这一“幕后的角力”，正好发生在气势汹汹的日本外相“在北京败北”、中国取得“这一轮对日斗争上风”之时的4月19日、20日期间，而也正好在小泉纯一郎22日“正式道歉”之前的两天里、在日本皇民李登辉“提前24小时”跳出来“形容自己几天睡不着着”的21日之前的一天里。

在东方评论员看来，日本不敢选择与中国决裂的、其实本身是建立在华盛顿不敢与北京决裂的之基础上的，而中日关系“通过小泉的道歉”而得以的“暂时维持”，又反过来促使华盛顿在台湾问题上、在“是否登陆、谁行登陆”的问题上、必须“再做考虑”。

显然，李登辉在21日的忍不住“跳将出来”，正是一种意味到阻止连战、国民党登陆、阻止“国共第三次握手”的“衷鸣”。

*** 华盛顿是在担心“两岸会不会越走越近、而局面不可收拾”？

首席评论员指出，急于让“两岸谈起来”的华盛顿、其实是非常熟悉连战的，然而就是哪此，也还要专程考察一番，足见其谨慎。在我们看来，华盛顿对自己表示“欢迎”的这一“历史性突破”如此“放不下”，其根本原因，是在担心“两岸会不会越走越近、而局面不可收拾”？

然而，只要连战心里念着“反对一边一国；反对一国两制；坚定捍卫台海安全”这个信条赴北京，那么，“反对一边一国”是大陆的立场，而“反对一国两制”则是台湾朝野共识，而两边加在一起，正好是美国嘴里一直念叨的“不独不统”的现状。也正是如此，连战才得以成行，不然，陈水扁这一关，连战根本就绕不过去，而一经绕到陈水扁那里，那么，在北京的眼里、连战和宋楚瑜又有什么两样？如此一来、北京仍然可能是“懒得理他”。

这样，华盛顿急于得到的“两岸缓和”去换取“朝核问题缓和”、从而稳住东亚、集中精力于中东的想法、就又得“继续拖着”，在东方评论员看来，朝核问题拖下去，不仅台海不能让华盛顿放心，韩国也不能让美国放心，从现在的情况看，韩国已被“拖离”华盛顿和日本够远的了，再拖下去，谁知道韩美、韩日、中韩间会出现什么事？这都是让白宫决策层焦急之所在。


*** 我们认为还是不要太乐观的好

很清楚，华盛顿愿意中途换人、是北京在暂时逼日本道歉之后、华盛顿在台湾问题上承受了更大的压力所致；而走投无路的国民党、愿意到大陆来，主要目的还是在借大陆搭建舞台、拉抬身价、解除自己在岛内即将被“中间路线”彻底瓦解、边缘化的困局。我们认为，基于华盛顿在台湾一手遮天的现实，如果国民党主席连战在“生死关头”、有足够的政治勇气排除内部的“隐性台独”、对华盛顿仍然抱有幻想者的摇摆性，与大陆达成“足以冲击”华盛顿对台政策中的“绝不容两岸三通成为现实”的底线的“民间共识”的话，那么，在朝核问题上有求于北京的华盛顿，就会处境尴尬、而难以转身，进退两难，大陆也就将真正的可以主导“两岸和谈”，然而，这种局面会出现吗？说实在的，我们认为还是不要太乐观的好。

首席评论员就认为，连战之所以能替代宋楚瑜先行登陆，是华盛顿在北京的压力下默许、放行的，因此，我们看到的连战、仍然是个“乡情有余、胆量不足”政治人物。


*** 华盛顿“放”连战登陆的条件.......

显然，在华盛顿为连战准备的、并由他带到北京的礼物中，可能有“九二共识”，但不太可能有“两岸三通的谈判”这个东西，请大家注意一点，是“两岸三通的谈判”，而不是“两岸三通”，这是两回事。

东方评论员认为，华盛顿、陈水扁会将这两者间区分得非常清楚的。因为“两岸三通的谈判”这要与执政的陈水扁当局才能谈清楚，显然，如果不出意料的话，这是华盛顿专为陈水扁准备的、在需要的时候送给北京的礼物。

另外，在东方评论员看来，华盛顿“放”连战登陆的条件、恐怕就是让连战借着“第三次国共合作”作“飞机票”、用“九二共识”当“敲门砖”，去敲开两岸“中程协议”这道门。

*** “中程协议”，成为华盛顿退而求其次、最合其胃口的一道菜

不难看出，这份所谓可以保障“两岸和平”几十年的“中程协议”，实际上是北京用“反分裂法”截杀了“和平台独、法理台独”的“可能性”之后，成为华盛顿退而求其次、最合其胃口的一道菜的。

然而，从博弈的角度讲，“最合”华盛顿胃口的，当然不会“最合”北京的胃口，在东方评论员看来，没有“两岸三通”、而仅有“九二共识”的中程协议，是根本就没有保障的，何况华盛顿在对台军售、准备走支持台独“军事抗统”路线这一关键问题上始终不肯松口。

首席评论员指出，在连战和国民党在“先行登陆”被华盛顿放行的情况下，已经转过身来、暂时摆脱被边缘化命运、从而准备在台湾政治、两岸事务上发挥更大作用时，他们如何平衡北京和华盛顿在对台军售上针锋相对的立场，将是东方评论员重点观察的一个问题。

显然，两岸关系是“一定会有反复的”，而这种“反复”在很大程度上就在于华盛顿根本就没有放弃准备有朝一日、以“打台独牌”威胁中国、以换取重要利益，或者以此主动打断中国建设的战略企图。事实在东方评论员看来，北京对此也是心中有数的。

*** 是北京的“反对”有效、还是华盛顿的“坚持”有效？

因此，如何防止将“两岸三通”与中程协议“捆绑起来”，从而“军事抗统”被化解、是华盛顿、陈水扁“必然会坚持”的、而北京也必然会想办法将“两岸三通”进程纳入到两岸和谈的进程中、纳入朝核问题缓和的过程中，从而“反对”将台军售问题单独放在台海缓和、朝核问题缓和的“东亚安全安排”之外。

只是在东方评论员看来，是“反对”有效、还是“坚持”有效，那就不仅仅是“隔着台湾海峡”就能谈得通、谈出结论的。我们的观点是：这不仅要看中东、朝核问题的进程如何，也得看日本政府是否在这一轮的“中美日”角力受到北京和华盛顿的“双重重击”中回过味来，从而主动调整中日、韩日关系。

巧的是，就是我们将注意力集中在连战登机、开始历史性的和平之旅的时候，可以说从美国方面在朝核问题上、日本方面在东海争议上立刻就传来了“非常符合逻辑”的消息。下面，我们就先来看看我们从资料员收集的信息中，挑选的两则报道，之后，东方评论员将就此而谈、谈谈它们是如何“非常符合逻辑”的、从而结束今天的台湾问题的讨论，进入朝鲜半岛的点评部分。


《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
