# -*- org -*-

# Time-stamp: <2011-08-04 12:12:30 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent


* 2005年8月03日 星期三






** 台湾宣布两重大政策开放飞机飞大陆领空



【台湾8月3日消息】据报道台湾“行政院长”谢长廷今天上午在“行政院”院会宣布两项重大两岸政策，为了因应国际油价高涨造成台湾航空业者在成本上的负担，开放台湾航空器可飞越中国大陆领空。

预计此举将可以大幅减轻，台湾航空业者在国际航线方面的成本与旅客搭乘时间。

另外，为了因应中秋节的到来，台湾官方也希望尽早针对两岸客运便捷化，与北京当局展开协商。

陆委会：客货运同步谈但货运包机先行

台湾媒体报道说，“行政院”大陆委员会高层官员指出，相关政策是为实现货运包机尽速协商的可行方案，即“货运、客运包机可以同步谈，但若协商完成，货运包机先行”，盼藉释出善意，照顾两岸人民权益，增进了解，改善两岸关系。



【时事点评】这则消息算是“两岸三通”的一个重大突破吗？在东方评论员看来，在判断是否“重要突破”的时候，恐怕还得看这则新闻出来的背景是什么。

在之前的点评中，我们曾经多次强调过，随着北京将自己的“台海政策”调整为“硬的更硬、软的更软”，即通过带有“非和平手段”的“反分裂国家法”成功狙击了“急独”、从而体现了“硬的更硬”的一手之后，又通过打破华盛顿、陈水扁的事先计划、安排连战、宋楚瑜以“先连后宋”这一“先后顺序”依次登陆、来成功地展示了自己“软的更软”的这一手。

*** 连宋登陆之后，大陆在台湾问题上表现得更多的是“等待时机”

事实上，北京在做完了这一切的时间，就是在五月份。之后，除了不时地将台湾农产品“登陆”、大陆旅游团体“登台”这些“细节问题”经常拿出来刺激“台独”的神经、分化台湾政治势力之外，大陆在台湾问题上表现得更多的是“等待”、等待国民党、亲民党领导层的“换代”。

东方评论员认为，直到目前为止，在马英九、宋楚瑜分别“当选”为新的国民党、亲民党党主席之后、由于马英九还没有“继位”，因此，我们认为，在马英九正式继位之前，从策略上看，大陆在台湾问题上“仍然不太可能有什么大动作”出台，但是，由于马英九“就位”的时间已经临近，因此，大陆在台湾问题经过近两个月的“沉寂”之后，却已经在开始“渐渐热身”。


*** 一个非常合乎逻辑的思路

在我们看来，就如我们之前强调的那样，在中国决策层的眼里，如何借助朝核问题“确定一个解决模式”的过程、来启动新一轮的“对台统战（台独语）”，显然是一个非常合乎逻辑的思路。


*** 这一轮“六方会谈”是成功还是失败，中国都有理由“期待着不菲的收获”

因此，东方评论员认为，对这第四轮六方会谈，身为“主持人”的北京，有足够的理由表现得“超然”一些，在我们看来，这种“超然”的意思就是不论这一轮“六方会谈”是成功还是失败，中国都有理由“期待着不菲的收获”。

在之前的点评中，我们也曾经说过，对这轮六方会谈，各方达成一致：事先不设时间的限制，在东方评论员看来，这种“不设限”的本身、就是在为最终取得某种突破奠定基础、创造可能。

然而，我们也认为，有基础、有可能是一回事、若要将“可能”转化成“事实”、恐怕就要看“在世界各地都有核心利益、需要自己精心照看”的华盛顿、如何权衡利益、分辨轻重，从而决定是否对朝鲜让步？如果让步，又要做什么样的让步，在什么时候让步了。


*** 在朝核问题上，这次对美国直接施加压力的是美国的亚洲盟友--韩国

首席评论员就指出，事实上，北京对第四轮朝核六方会谈的那种“成亦可喜”、“败也欣然”的“超然态度”、“反衬”得华盛顿在韩国的逼迫下“赴会”“六方会谈”的同时，面临着“放下身段”的巨大压力。

显然，在朝核问题上，这次对美国直接施加压力的是美国的亚洲盟友--韩国。然而，谁都清楚，正是韩国“有意识地”、“不停地”朝着北京方向的“张望”、才使得这种来自韩国的压力不仅真实、而且力道巨大。


*** 但是，其“关注的重心”、评估的“主要参数”绝对是北京

尽管华盛顿在做“需要做什么让步、什么时候做让步”的“全套评估工作”时，其“直接动力”是来自韩国那份“急于稳定半岛局势、启动半岛经济整合”一揽子计划，但是，其“关注的重心”、评估的“主要参数”绝对是北京。

在东方评论员看来，华盛顿的“全套评估工作”、其工程量不可谓之为不大、涵盖的范围不可谓之为不广，根据我们的观察，华盛顿的“这番论证”可以说是全方位、多层次、且计划非常周密：


*** 华盛顿“反手”借“连宋”登陆的后续效应、直接刺激日本右翼的神经

首先，在东亚方向，由于“反分裂国家法”是“如期上岗”、并进行“战略执班”，这一方面迫使在公开操纵“台独和平台独”的问题上不得不收敛一二，但是，却也给了华盛顿决策层另外一条、也就是推动”非和平台独”的机会，这表现在同意连战、宋楚瑜“按连宋这一大陆安排的顺序”实现了“连宋登陆”之后、“反手”借“连宋”登陆的后续效应、直接刺激日本右翼的神经、“激起”中日东海争端、翻“东京审判”的铁案，从而达到其将中日关系“往绝路上赶”的战略意图。


*** 美国极可能在“两岸关系”上再让一步、以图制造中日关系破裂的局面

还有，为了强化日本社会继续右倾、强化日本对两岸极可能走向“两岸三通”的担心，华盛顿定向地、向亚洲、主要是东亚方向“抛出”中国军事威胁论，事实上，从五角大楼7月19日一公布《中国军力报告》就立刻引得台湾用有史以来第一份“国安报告”、以及日本的05年度《防卫报告》、来分别“策应”“中国军事威胁论”的情况来看，华盛顿针对东亚方向的一套“评估、准备”工作、其意图是“清清楚楚”：既华盛顿极可能在“两岸关系”上再让一步，让两岸往两岸三通的方向再靠近一步，一来寻机以此换取北京在朝核问题上的松动一下；但更主要的恐怕想刺激日本保守势力下决心走极端、制造中日关系破裂的局面、引发中日全面对抗、彻底实现美国亚洲人打亚洲人的大国制衡战略。

但是，关键问题是、就算华盛顿让两岸在”两岸三通“的问题上再往前走一点、在中国和日本的眼里、能算是美国在做“实质性”的让步吗？


*** 在台湾问题上，北京现在正在做的有两件事

东方评论员认为，在台湾问题上，北京现在正在做的有两件事，一是等待国民党新领导人“就位”、之后，北京就将择机启动新一轮“统战”、继续拿着“连宋登陆”时、在大陆“签了字画了押”的两份“新闻公报”、从上面逐条地取下那些有利于台湾经济的“条条款宽”、当作标枪一一地扔向台湾岛，由于再过几个月就是台湾地方县市政权选举，可以期望的是，台湾岛各个县市政权的“在野势力”，是一定会接过这些标枪，用“两岸三通”、“开放大陆对台投资”等诸多“钱途”、去收购台湾民众的选票。


*** 北京手中的“统战资源”本质上是华盛顿为了台湾、朝核问题眼下不至于失控而“付出的代价”

显然，这些“统战资源”本质上是在“反分裂国家法”“正式上岗”的情况下、华盛顿为了达到“稳住台湾、朝核问题不至于失控、并反手用这些去强烈刺激、并启动日本更加激烈地挑衅中国”之目的、而不得不付出的“代价”。

东方评论员认为，大陆在手握这种美国为达上述目的而“送给”自己“统战资源”时，在盯着美国正准备全力地整合“美日台”军事同盟的时候，又怎么可能去对华盛顿可能的、让“两岸三通”再往前走一点的“好意”动心、并视为“实质性”的让步呢？


*** 美国“屡试不爽”的、刺激日本右翼的手段

在我们看来，美国在台湾问题上所做的让步，要想“能够吸引住”北京的注意力，就得在“对台军售”的问题上做出实质性的让步，从而解除美国想通过构筑“美日台”军事同盟、怂恿”台独“武力拒统”、有朝一日搞“非和平台独”的“非份之想”。

然而，就目前来看，要让华盛顿做此让步，似乎很难，这样一来，在我们看来，在台湾问题上，中美之间不太可能达成什么突破，多半是继续目前这种局势，即“台湾不独、大陆不武”的局面。

不过，就这种局势，善于耍两面手段的华盛顿，仍然要加以利用、也能利用的，众所周知，美国人现在为了中东、的确还不敢一下子就将“台独牌”打出来，但是，日本右翼这张牌，华盛顿是仍然会继续打下去的。

显然，要刺激日本保守势力、只要用让“两岸气氛”再好一点、让日本的台湾代言人李登辉的日子再难过一点当作“刺激手段”，对美国人而言是“屡试不爽”、而且效果奇佳。如果我们从这种背景去透视陈水扁“同意”开放台湾航空器飞越中国大陆领空的所谓“大新闻”的时候、在我们“欢迎”陈水扁向“两岸三通”再近一步的同时，心中一定要明白华盛顿让陈水扁这样干的“真实意图”是什么。


为了更好地说明这个问题，我们再来看两则相关消息、一来看看泛蓝的观点，二来，也看看在谢长庭放出这则消息前，陈水扁已经做了些什么准备工作。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com


** 开放飞机经大陆上空？国亲：等扁点头才算



【台湾8月3日消息】据台湾媒体报道，对于谢长廷宣布开放台湾航空公司飞越大陆上空以及货运和客运包机将一起协商，对此，台湾“立法院”在野党团都表示，这是早该做的事，并呼吁民进党政府不要只是随便说说，到时候根本做不到。

亲民党立委孙大千对说，他对民进党政府这项新政策能否实施抱有怀疑态度。他指出，在最近一段时间以来，在两岸议题上，谢长廷作出很多决定，最后都被陈水扁所否决。这次航空器飞越大陆上空的政策能否达成，谢长廷说了不算，而是要看陈水扁会不会同意。

而国民党团副书记长潘维刚对此表示欢迎，但他就希望不只争得形式上的表现，而是实质上的内涵，让台湾航空公司都可以因此获利，潘维刚并希望民进党政府要说到做到，不要又变成雷声大雨点小。




扁「中华民国四阶段论」国民党批借壳搞台独

【台湾8月3日消息】据报道，陈水扁二日提出「中华民国四阶段论」，国民党发言人张荣恭批此是「违宪搞台独」。

陈水扁上午会见「美国福尔摩沙基金会」青年亲善大使时提出该论，指一九一二年「中华民国」在大陆成立；一九四九年「中华民国到台湾」；前「总统」李登辉时代，「中华民国在台湾」；二○○○年政党轮替后，「中华民国是台湾」。为厘清确认「国家认同、国家定位、台湾主权」，所以「总统府」应称为「中华民国（台湾）总统府」。

对于陈水扁的论调，国民党发言人张荣恭二日中午痛批是「躲在中华民国安全伞下搞台独的危险动作」，借「中华民国」的壳为日后「破壳而出搞台独」作准备；他并指出，「在宪法中，中华民国不只有台湾，陈水扁的说法也明显违反宪法」。

张荣恭表示，美国务卿去年表示「台湾不是主权国家」，就是要吓阻陈水扁的「台独」动作。陈水扁曾说在他任内做不到「台独」，想用中华台北名称参加亚太经合会领袖高峰会，但面对「台独」团体又不禁真情流露，真是「人前说人话，鬼前说鬼话」，值得全民警惕及注意，避免陈水扁把大家带到危险的路上去。




【时事点评】事实上，让台湾航空公司飞越大陆上空的事、早在美国攻打伊拉克时、大陆方面就已经做过，那是出于安全因素、在台湾的请求下、特别允许台湾航空公司飞中东的飞机经大陆空域、绕过战区。

所以，在东方评论员看来，新闻中的这么一段似乎说得非常中肯：原文是，对于谢长廷宣布开放台湾航空公司飞越大陆上空以及货运和客运包机将一起协商，对此，台湾“立法院”在野党团都表示，这是早该做的事，并呼吁民进党政府不要只是随便说说，到时候根本做不到。

*** 这显然不能算是一个“两岸三通”的“重大突破”

的确，在“连宋登陆”已经过去了几个月，台湾当局才做了一件“早该做的事”，何况还是有了上述的“复杂背景”，再加上就如新闻中所说的那样：最近一段时间以来，在两岸议题上，谢长廷作出很多决定，最后都被陈水扁所否决,因此，整个事情有没有后续进展，还是个没有影儿的事情。

另外，大陆所要的“两岸三通”，在航空这一块，其核心是两岸间的客运直航，可见，谢长廷的拿出的这个“飞越中国大陆领空”，离真正的核心问题还远着呢！

因此，在东方评论员看来，这显然不能算是一个“两岸三通”的“重大突破”、更算不得实质性突破。但是有一点却可以肯定，这个消息可不是谢长廷“独家创造”、而是华盛顿让陈水扁刻意安排的。


*** 陈水扁也就象一句老话那说的那样：“安能辨我是雌雄（蓝绿）”！

我们注意到，就在谢长廷抛出这个决定之前，陈水扁就已经提前一天抛出了“绿色”的“中华民国四阶段论”，不难看出，有了这个“绿色”的“中华民国四阶段论”垫底之后，再抛出一个“蓝色”的意向，如此一来，陈水扁也就象一句老话那说的那样：“安能辨我是雌雄（蓝绿）”！


*** 陈水扁是正在支起耳朵“听风向”

另外，东方评论员注意到，在谢长廷抛出了这个被台湾媒体形容为“爆炸性的决定”之后，我们还没有听到陈水扁公开说些什么，由此看来，陈水扁是正在支起耳朵“听风向”。

然而，在两岸关系上，陈水扁就是听出了风向，也决定不了什么。在东方评论员看来，一年多来的台海风云、尽管风云变幻、扑朔迷离、但最后，都以铁一般的事实、不可辨别地证明了这个“不听话的陈水扁”、其“真实身份”不过是华盛顿的“提线木偶”而已。在这一点上，陈水扁与“只愿意效忠日本”的、在台湾有一大批日本人后裔死心拥护的李登辉相比较而言，还是有着本质区别的。

*** 不过是华盛顿与陈水扁一起在演戏

在我们看来，什么布什狂骂陈水扁、什么陈水扁不听招呼，什么华盛顿近来在绕开陈水扁、而直接与民进党的其他实权人物打交道，事实上都不过是华盛顿与陈水扁一起在演戏。

当然，这种戏不是演给北京看的，而是演给“泛蓝”看的、也是演给与李登辉有渊源的日本人看的。之前，就凭着这些“假戏”，在去年“320”之后、华盛顿、陈水扁就靠这一套骗了国民党的连战、让国民党相信美国人将主持公道，因为美国人“不喜欢不听话的陈水扁”，从而将上街的支持者劝回家去，结果是在那时能左右台湾局面的华盛顿、在经过调查程序、拿到了“319”枪击案的证据之后，却偏偏让自己“最讨厌的人”当上了“台湾的总统”；

之后，另一个上当的是亲民党的宋楚瑜，相信美国人、为了率先登陆、当两岸和平的奠基人而拉抬身价、从而与陈水扁搞了一个“蓝不亲”“绿不爱”的“扁宋十点共识”、为换取陈水扁放行他率先登陆的“通行证”、不惜来为陈水扁当说客。


*** 几个月前的情形，与现在似乎有太多的相似

在东方评论员看来，当时的情形与现在似乎有太多的相似，即华盛顿就是通过“这些事情”、也就是在美日联手阻止“反分裂国家法”不果的情况下，在华盛顿的确需要台湾稳定、也需要日本出来牵制中国的背景下、也在美国有意“促使台海长期和平稳定”、以策应美国中东战略的政策调整的“思维定式”“掩护”下、美国通过去年底台湾立法委员选举前、突然高调“反台独”、引导台湾民意、让亲日的、李登辉的“台联”遭受重创、从而在2月份成功地刺激日本在钓鱼岛问题上突然对中国发难，并被美国如意地拖进了“协防台湾”的阵营。


*** 在“美日新安保指针”问题上、小泉政府曾被布什政府“出卖”

然而，在“美日新安保指针”问题上、小泉政府被布什政府“出卖”了是公认的事实：由于朝核问题在朝鲜宣布“已经有核武器”后、一度陷入东亚核竞赛的边缘，因此，感受到北京压力的华盛顿，在日本同意将台湾纳入美日安保目标之后，却没有将日本已经在国防文件中正式确立的中国威胁论写入安保条约。因此，事后小泉纯一郎还一度公开地对华盛顿“出卖”日本感到不满、并否认日本是调整美日安保指针的主谋、从而将美国也供了出来。


*** 美国“策划宋楚瑜”登陆、小泉就立刻如美国所愿的再次跳了出来

之后、面对对自己不满的日本，美国又“策划宋楚瑜”登陆、“放风”调整台海政策、准备促进两岸签定和平协议，结果，在日本的台湾代理人--李登辉无法阻止连宋登陆的情况下、刚刚抱怨美国人出卖日本不久的小泉纯一郎、就再一次如美国所愿的跳了出来、在东海问题上、以向企业发放许可证为题、来强烈地挑衅中国、企图压中国不要对日本插手台湾、支持李登辉做出激烈的反应、并顺势对中国正式开打台湾牌。


*** 华盛顿和陈水扁的把戏、将宋楚瑜“剥得一丝不挂”

结果，也就在4月份，在北京用反日游行、公开反对日本入常等一系列手段“力压”小泉纯一郎公开在国际场合道谦、并利用“朝核问题”有可能进一步恶化、暗中对美国用来与欧盟交换中东利益的“巴以和平进程”施加影响，而压华盛顿“强行调包”、让连战首先登陆、打破了是华盛顿和陈水扁的事先策划、其结果是宋楚瑜临到正式登陆时似乎才明白，他对华盛顿已经不再有利用价值、不仅如此，反而为大陆所利用的宋楚瑜、终被华盛顿和他不喜欢的陈水扁一起、给“剥得一丝不挂”。


*** 他们这一次想骗谁呢？

现在，华盛顿、陈水扁将这一套又给搬了出来，那么，他们这一次想骗的是谁呢？在东方评论员看来，由于美国刚刚在中亚的美军军事基地问题上、中东的“巴以和平”问题上、伊朗核问题上都与北京刚刚过过招，知道北京手上的确抓有不少“非常实用的筹码”，特别是眼下在朝核问题上、北京更是摆出一副超然的姿态，因此，中国是不会对这点“小玩意儿”动心的。

所以，我们认为，美国人、陈水扁这一次想骗的恐怕还是国民党、亲民党、骗什么？第一，是骗钱，想骗“国亲”手中搼着的“军售案”，这是美国人想骗到手的东西；

第二，就是骗年底台湾县市长选举的选票，之后、再骗出一位可以保障陈水扁个人利益的“接班人”来，就象叶利钦与普京那种关系。这是陈水扁想骗到手的“玩意儿”；


*** 美国还想骗日本人，将一推就倒的中日关系往悬崖上赶

第三，美国还想骗日本人，想以这种老招术去刺激日本、让日本在华盛顿设定的反华路线上“再勇敢地走几步”。到目前为止，让华盛顿失望的是，尽管小泉纯一郎够强硬，但是，在最具爆炸性的、北京态度极其强硬的“东海油气开发问题”上，在中国军方以公开警告“准备核打击美国”这种方式、“指着主人准备打狗”的威慑下，在东海、钓鱼岛主权问题上狂言不已的日本保守势力、终究不过是在那“只听楼梯想、不见人下来”地让布什“郁闷不已”。

显然，现在的华盛顿、就是想让“两岸三通”这种“不是不可能”的前景、再次去刺激日本人、刺激害怕“两岸三通”的日本右翼继续跳出来插手台湾、从而将一推就倒的中日关系继续往悬崖上赶。


*** “务实”特点鲜明的中国决策层、是不会对马英九寄予厚望的

东方评论员注意到，国民党发言人张荣恭翼在痛斥陈水扁、说他是“人前说人话，鬼前说鬼话”，然而，以国民党今天这种格局，即使是看得清楚骗局，却不一定能避免再次受骗，总之，针对美国和陈水扁的骗术、即将接任国民党主席的马英九要想今后有所作为、首先要做的就是“捂紧钱包”，其次就是将连战访问大陆时与中共达成的共识加以落实、努力地将其转化为成果，从而赢取台湾的民意支持。

不过，根据我们对马英九本人的多年观察，此人的表演才能较之陈水扁是“有过之而无不及”，在东方评论员看来，一个有着“不粘锅”之称的、的单纯“演员”、仅靠其“政治洁僻”这一优点，似乎很难做到这一点。


*** 大陆要利用华盛顿、陈水扁“先前骗过”的宋楚瑜搅局

我们认为，“务实”特点鲜明的中国决策层、是不会对这样一种人寄予厚望的，因此，东方评论员认为，最大的可能是，在继续尽力地利用连宋登陆的成果、充分利用被华盛顿、陈水扁“先前骗过”、现在遭弃、处境尴尬的宋楚瑜和亲民党、尽力搅乱台湾政局的同时，北京将“更加努力地”进行军事斗争的准备工作，将“台海和平”的希望寄予在自己的、让任何人生畏的、强大的军事打击力量上。

下面，在一起熟悉一则有关六方会谈的最新消息后，东方评论员将开始讨论朝核问题的最新进展，并针对六方会谈是否会因分岐难以弥合、而“暂时体会几天”、给出我们的观点。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com




