# -*- org -*-

# Time-stamp: <2011-08-04 13:01:05 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 2005年8月22日 星期一

  

** 中俄联合军事演习达成联合战役决心侧记

 

【解放军报报道】8月21日，参加中俄联合军事演习的两军参谋人员正在导演部里紧张作业。

2005年8月21日15时50分，对“和平使命—2005”中俄联合军事演习来说，是一个重要的时刻。中俄联合军事演习中方总导演葛振峰上将和俄方总导演莫尔坚斯科伊上将，共同批复了此次军演的联合战役决心书和决心图。

中俄两军导演部、联合指挥部和各作战集团指挥员，都对这份联合战役决心给予高度评价。在联合指挥部召开的作战会议上，参演两国的将军们认为该决心对情况的判断准确、清晰，形成的决心和任务部署详细、具体、周密，抓住了联合战役行动的战略枢纽，展现了中俄双方战略指挥机关丰富的战略思维和良好的战略素养。

签署仪式上，出现了动人的一幕：联合战役决心签署完毕，中俄联合军事演习导演部、联合指挥部的葛振峰、章沁生、范长龙、刘冬冬和莫尔坚斯科伊、费奥多罗夫、阿格耶夫等将军们，情不自禁地走到演习沙盘前，亲切握手，互相祝贺。

这份凝聚着中俄两军指挥员心血的联合战役决心，既坚决贯彻了中俄两军统帅部的战略意图，又符合“敌情”、我情。联合战役决心对此次联合军事演习中俄双方的战役编成、任务及实施方法等都作出了明确规定，是双方实施联合作战的基本依据。按照该决心，中俄双方的陆海空军部队，将在山东半岛及其附近海域进行海上联合封锁、两栖登陆作战和强制隔离作战的实兵课目演练。

演习正式开始以来，记者多次走访导演部大厅和两军指挥中心，实地观看了各分中心和各指挥组的工作展开情况，所到之处都是一派紧张的磋商、谋划场面。尽管这期间青岛天气异常闷热，但官兵们都自觉以大局为重，不言苦、不叫累，始终保持着高昂的斗志。

今天下午，俄方总导演莫尔坚斯科伊上将向演习中表现突出的中俄两国将军和校尉军官，颁发了俄国防部长奖章、总参谋长奖章和总后勤部长奖章。

13时50分，记者走进导演部大厅，只见巨幅电子沙盘上灯光闪烁，不断显示着最新的战场态势；两侧各悬挂着3幅分别用中俄文标注的作战地图；两军作战协调室、两军指挥中心和信息作战中心、政治工作中心、海军指挥组、空军指挥组、空降兵指挥组、后勤保障中心、装备保障中心等筹划战役演习的情况，也实时显示……

14时，导演部俄方总导演莫尔坚斯科伊上将指示联合指挥部双方司令员报告战役决心。

14时01分，联合指挥部俄方司令员费奥多罗夫海军上将首先报告战役决心，他重点报告对情况的判断和战役企图。

14时35分，联合指挥部中方司令员范长龙中将报告战役决心，重点报告联合部队任务、指挥、协同原则、保障等。

随后，导演部双方的7位导演助理，分别就各自分管的工作提出了建议，导演部俄方

参谋长阿格耶夫少将、中方参谋长章沁生少将也分别提出了建议。

中方总导演葛振峰上将做出了结论性意见，最终达成并批准了联合指挥部的战役决心。

数十小时后，一场着眼应对共同威胁，旨在维护世界和平的高技术、高水准实兵实弹演习，将在山东半岛及其附近海域展开……


 【时事点评】东方军事评论员注意到，中俄联合军演中方总导演葛振峰上将和俄方总导演莫尔坚斯科伊上将，已经“共同批复”了此次军演的联合战役决心书和决心图。在我们看来，这标志着在这场举世瞩目的、由中俄两个大国联手演出的“和平使命2005”中、确定双方各自“扮演何种角色、承担何种责任”的问题上、“所有的程序”都已经落实。接下来，整个演习也就将正式进入高潮部分--第三阶段的“实施交战”。


*** 值得强调的“敌情”、“我情”

在我们看来，如果我们仅从军事术语的角度去认识上述“确认”这一幕、那么，其军事意义在新闻中可以说是阐述得一一清二楚，即：这份凝聚着中俄两军指挥员心血的联合战役决心，既坚决贯彻了中俄两军统帅部的战略意图，又符合“敌情”、我情。联合战役决心对此次联合军事演习中俄双方的战役编成、任务及实施方法等都作出了明确规定，是双方实施联合作战的基本依据。按照该决心，中俄双方的陆海空军部队，将在山东半岛及其附近海域进行海上联合封锁、两栖登陆作战和强制隔离作战的实兵课目演练。

显然，东方评论员认为，这中间值得强调的有这么几个名词，第一，“坚决贯彻了中俄两军统帅部的战略意图，又符合“敌情”、我情。


*** 这是场融合国际政治、经济、军事意函的大规模联合军演

首席评论员就指出，我们不能用纯军事的眼光去观察这场融合重大国际政治、经济、军事意函的大规模联合军演，在我们看来，这场军演的看点不在军演本身，而在于中俄想通过这场联合军演散发出何种战略目的。

事实上，在之前的《东方时事解读》中、东方评论员已经就中俄正式邀请南亚的大国印度观摹所散发出来的信号、给出过我们的观点，即，印度正在准备在印度洋地区通过建立一种新的多边安全框架来打破其以往的孤立，而中俄在一个月前正式将印度列为“上海合作组织”的一个观察员、现在又正式邀请印度“参与”“和平使命2005”最精彩部分，这本身就意味着“中俄”愿意在印度洋建立“新的多边安全框架”中、扮演某种“重要角色”。


*** 中俄印之间矛盾能调和到什么程度、美在印度洋、西太平洋上遇到的麻烦就能到达什么程度

东方评论员认为，中俄进行的这次联合军演、事实上“在东亚方向”与印度主动提出与中国在印度洋举行海军军演的战略意图、是遥相呼应的。在我们看来，“中俄印”联手在印度洋、西太平洋两上方向、在政治、经济、军事各个层面共同制衡美国的目的是一目了然。当然，今后，中俄印之间的战略矛盾能够调和到什么程度、那么、美国在印度洋、西太平洋上遇到的麻烦就能到达什么程度。不过、这已经是另一方面的问题了。


*** 实在是找不出比“国际舞台剧”这个词更能准确地来形容它的了

东方评论员认为，就这次联合军演的“形式与功用”而言，我们实在是找不出比“国际舞台剧”这个词更能准确地来形容它的了。

在我们看来，从“国际舞台剧”的“几个要素”而言，首先、不论是编剧（联合战役决心书和决心图）、导演（中方总导演葛振峰上将和俄方总导演莫尔坚斯科伊上将、还是演员（中俄参演精锐部队）、可以说是均已到位。唯一“似隐似现”的就是所谓的“观众”了。

在之前的点评中，我们对美国和日本、以及“台独”面对这次军演的种种心态给出过描绘、在东方评论员看来，“这三位”、尤其是“美日”、是当然的观众、而且还是一批“不请自到”的看客。然而，还有一批“贵宾”似乎就不那么引人注意了。


*** 回忆一下这场“联合军演”是在什么背景下最终敲定的

首席评论员认为，只要我们稍微回忆一下这场“联合军演”是在什么背景下最终敲定的、就不难看出这批“贵宾”是些什么人了。

众所周知，就“和平使命2005”联合军演本身而言，“本质”上是在胡锦涛主席7月初的莫斯科之行“前后”、才最终敲定的。在那次访问中、胡锦涛与普京在莫斯科签署了直接针对华盛顿的《中俄关于21世纪国际秩序的联合声明》。

我们知道、“联合声明”一共有十二条之多、是中俄之间“专门就国际秩序”发表的第一份联合声明，而“声明的12点内容”可以说是“全部关系到国际事务”。

*** “最关键的”还得要让人相信你、在关键的时刻“你敢于使用你自己的实力”。

东方评论员认为，“中俄联合声明”在“字里行间”里早已经“暗示”中俄将联手、以致力于建立一个涵盖“政治、军事、经济”方面的国际新秩序、并以此挑战美国在国际事务中“一家独大”的“强烈愿望”。

显然，在我们看来，中俄仅有“美好的远景”和“强烈的愿意”是不够的，因为“豪言壮语”谁都能说、如果你的“豪言壮语”要让人相信，“前提”就是要有相应的实力，然而，仅有实力也是不够的，“最关键的”还得要让人相信你、在关键的时刻“你敢于使用你自己的实力”。


*** “和平使命2005”就是中俄证明自己敢于在关键时刻使用实力的“关键一步”

首席评论员指出，“和平使命2005”就是中俄在说了“豪言壮语”之后、展示自己“拥有的相应实力”、并证明自己敢于在关键时刻使用实力的“关键一步”。

为了更好地说明问题，我们不妨回忆一下《中俄联合声明》的核心内容、即“联合声明”的“第十条”和“第十一条”。

请看原文：

十、区域一体化是当前国际形势发展的重要特征。双方指出，建立在地区开放、平等合作和不针对其他国家基础上的多边区域组织在国际新秩序形成过程中发挥着积极作用。在经济领域，地区倡议应促进贸易共同体更加开放和富有成效。在地区安全领域，建立兼顾各参与方利益的、开放的、不针对其他国家的安全合作机制具有根本性意义。双方支持各地区一体化组织建立横向联系，营造互信、合作氛围。

十一、中俄新型国家关系正为建立国际新秩序作出重大贡献。中俄关系的实践印证了本声明所述原则的生命力，同时表明，在此基础上可以有效发展睦邻友好合作关系，解决各种问题。两国决心与其他有关国家共同不懈努力，建设发展与和谐的世界，成为安全的世界体系中重要的建设性力量。


*** 通过上面“两条”，我们可以清楚地看到中俄“准备建立何种”“新型国家关系”、以及“如何”建立这种关系

显然，通过上面的“两条”，我们可以清楚地看到中俄准备建立一种什么样的“中俄新型国家关系”、以及如何建立这种国家关系。其中，东方评论员注意到，“双方”在描述这种“新型国家关系”时、不仅用到了“区域一体化”这几个字，而且在第十条中还特别“强调了”这种“区域一体化”、将在建立“美好的”“国际新秩序”过程中“应该发挥的积极作用”、因此，在我们看来，如何确定“区域一体化”的“性质与作用”、实际就可以弄清楚中俄“是否在建立”一种“同盟关系”。



*** “这两条”中还暗藏有另外的“两层意思”

不难看出，“这两条”不仅“点出了”中俄有意“以区域一体化”的方式来“为建立国际新秩序作出重大贡献”，而且还在“反复暗示”这种“区域一体化”不仅是“安全方面”的、而且还涉及“经济领域”。

对此，首席评论员就指出，就这种“反复暗示”而言，其意图就是在“反复强调”“这两条”中还暗藏有另外的“两层意思”：第一，胡锦涛与普京当时所谈妥的“区域一体化”起码有两个方向；第二，明确了中俄致力建设的“区域一体化”的“具体特性”，即将是个“开放性”的、属于“地区安全性”的，且“兼顾各参与方利益的”“区域一体化”，另外，中俄还说得非常清楚、那就是它还具有“不针对其它国家的性质”。


*** “上海合作组织”毫无疑问具有“中俄”“事先约定”中的“所有特点”

对此，首席评论员认为，就第二层意思而言，北京和莫斯科显得非常灵活、有了这些“事先约定”之后，中俄今后建设的任何“区域一体化”、实际上“将成为相关地区”的稳定核心，这就是说，任何相关国家、只要符合中俄的战略利益、都可以被纳入这种“区域一体化”中。

显然，到目前为止，我们能看到的、中俄联手打造的、已经成形的“区域一体化”中、“上海合作组织”毫无疑问具有“中俄”事先约定中的“所有特性”。


*** 中俄何以“事先约定”“区域一体化”的“诸多特性”、并公诸于世？

首席评论员指出，中俄“事先约定”“区域一体化”的“诸多特性”、并以《中俄联合声明》的形式公诸于世，显然是在“着眼于未来”。在我们看来，在北京和莫斯科决策层的眼里，双方急须“从两个方向”开拓自己的未来。

同样，也是为了更好的说明这个问题，我们再看看胡锦涛在访问俄罗斯之初与普京签署了《中俄关于21世纪国际秩序的联合声明》之后，于结束俄罗斯行程之际，中俄共同发表的另一份重要文件--《中俄联合公报》的“核心内容”，非常巧合的是，东方评论员所认为的核心部分，也列在《中俄联合公报》的第十条和第十一条，原文如下：

十：双方愿共同努力，本着战略协作伙伴的精神加强合作，维护亚太地区的安全和稳定。双方愿进一步加强两国在东盟地区论坛等区域合作机制下的对话、协调与合作。
　　中国欢迎俄罗斯加入“亚洲合作对话”，愿继续努力促进俄加入“亚欧会议”。中国欢迎俄罗斯与东亚已建立或正在形成的区域一体化体制建立联系。

　　十一：双方重申，坚持朝鲜半岛无核化目标，坚持对话和平解决方向，坚持维护半岛和地区的和平与稳定，支持朝韩继续改善关系，支持朝鲜与有关国家实现关系正常化。双方一致认为，六方会谈是寻求解决朝鲜半岛核问题的最好最有效的方式。双方对有关各方近来为推动复谈所做的积极努力表示欢迎。双方呼吁会谈各方保持耐心，显示灵活，以建设性态度积极推动早日重开六方会谈，并使会谈取得进展。双方愿进一步共同采取协调一致的步骤，和平解决朝鲜半岛核问题。

　　双方坚决反对核武器扩散，主张通过外交手段在国际原子能机构框架内尽早解决伊朗核问题。双方支持国际社会为推动政治解决伊朗核问题所做的外交努力，愿在这一进程中继续发挥建设性作用。


*** 通过《中俄联合声明》和《中俄联合公报》，中俄“大体上确认”在东北亚和中亚“各自扮演的角色”

非常清楚，在东方评论员看来，从“稍后发表”的《中俄联合公报》的第十、十一条的字里行间中，我们可以非常清楚地看出几层“核心要义”：第一，包括朝鲜半岛的东北亚、和包括“上海合作组织”的中亚、正是“稍前发表”的《中俄联合声明》中的第十条、十一条中所明确之“区域一体化”的“具体区域”。

第二，通过《中俄联合声明》和《中俄联合公报》这两份文件，北京和莫斯科“大体上确认”了中俄双方在东北亚和中亚“各自扮演的角色”、在东方评论员看来，这种“角色”可以说是“利益”与“责任”的结合体。

*** 中俄“两份文件”的签定，实际上已经明确了中俄双方在战略合作上的分工

也正是在这种大背景下，我们也就观察到如下一幕：北京在与莫斯科一起强化“上海合作组织”的时候、显然知道自己的重心在东亚方向、因此、也“非常顾及”俄罗斯在中亚的政治、军事、甚至是经济上的影响、“尊重”俄罗斯在中亚的传统主导地位、因此、在中亚这一块，中国“更多地是在主张自己的经济利益”、而刻意避免去与俄罗斯争夺政治、军事主导权、并有意配合俄罗斯维护中亚的政治稳定。

因此，中俄“两份文件”的签定，事实上是北京“承认”俄罗斯在中亚的政治、军事主导权、而莫斯科同意中国更深地参与乌兹别克政府提出的、“中亚经济整合”的战略分工、从而意在达到从政治、经济、军事上全面稳定中亚、增强上海合作组织的影响力进行的全面战略合作。


*** 在“中俄联合军演”对中亚所具的战略意义上、一个值得重视观点

就“中俄联合军演”对中亚所意味的战略意义，事实上，许多“局外人”已经在猜测：中俄联合军演将直接导致上海合作组织演变成一个“防御性联盟”。在东方评论员看来，这种观点是可以说点破了《中俄联合声明》和《中俄联合公报》的真正意涵，显然，这种“防御性联盟”要起到“防御”的作用、那么、其前提就是中俄确保彼此间的“战略互信”，既北京“支持”莫斯科在中亚的政治、军事上起主导作用、并与莫斯科一道、在关键时刻用包括军事力量在内的各种手段、去共同维护中亚国家的政治稳定。


*** 所谓“防御性联盟”的内涵之所在

而莫斯科则同意北京在中亚的经济整合中起到比现在“重要得多的作用”，其中典型的就是让中国通过中国和俄罗斯铺设在中亚国家的石油管道、抽走美国“巴杰”石油管道“准备从里海抽走”的原油、从而“从根本上防止”美国通过“巴杰油管”将美国“远在万里之外”的经济影响渗透到中亚、从而在经济“这个根本上”去瓦解上海合作组织的政治、军事凝聚力。

首席评论员指出，这大概就是所谓“防御性联盟”的内涵之所在吧。


*** 北京与莫斯科之间的“战略合作”与“战略互换”

而作为战略交换，北京在与莫斯科协同将华盛顿挤出中亚的同时，稳定住自己的后方的同时，还将在东北亚得到俄罗斯的政治、军事策应、既协助中国去帮助韩国启动朝鲜半岛的经济整合。


事实上，莫斯科在东北亚力助北京也有着巨大的战略利益。这表现在以此为契机，俄罗斯将在“将自己的远东”“介绍给亚太经济圈”的问题上、得到北京的帮助，既，中国将“有义务”帮助俄罗斯远东地区在共同参与东北亚经济一体化的基础上、以东北亚经济一体化为突破口、切入到东亚经济一体化进程、并突入亚太经济圈。

事实上、在“东亚的”东北亚区域，我们看到的是北京的“高姿态”，比如：“中国欢迎俄罗斯与东亚已建立或正在形成的区域一体化体制建立联系”、在东方评论员看来，更让俄罗斯心动的是，北京“愿进一步加强两国在东盟地区论坛等区域合作机制下的对话、协调与合作”、此外、“中国还欢迎俄罗斯加入“亚洲合作对话”，愿继续努力促进俄加入“亚欧会议”。


由此可见，“两份文件”已经凸现出莫斯科不仅“尊重”北京在东北亚的核心地位、还“指望着”借助北京的帮助、让自己能够融入东亚、融入亚太经济圈，此外、俄罗斯还指望着从侧面、借助“亚欧会议”这个欧亚大舞台、全面切入“欧亚对话过程”。


*** 这种局面，对北京而言，将彻底动摇华盛顿主导的东亚安全格局

显然，这种“突入”就是借助北京在东亚经济一体化进程中的关键角色、打通与韩国、东盟、甚至是日本之间的经济联系。在东方评论员看来，这种局面，对北京而言，将彻底撬动美国在东亚、特别是东北亚的地盘、动摇华盛顿主导的东亚安全格局，从而为自己极大地扩展了战略空间；

东方评论员认为，可以肯定的是，俄罗斯如能做到这一步，就意味着全面突破了美国欲将其封堵在俄罗斯国境线内的包围圈、从而将吸引到中国、日本、韩国、甚至是欧洲的大量外资、并将自己的资源“运到了太平洋”上，从而全面地将俄罗斯远东的经济“融进”亚太经济圈。


*** 我们理解的所谓“敌情”与“我情”

首席评论员就认为，上面所讨论的的这些内容，事实上、这就是所谓的“中俄统帅部”的、在“中亚方向”、“东亚方向”上的战略意图，在中亚、东亚的政治、经济、军事形势、也就是我们理解的所谓“敌情”与“我情”。（在南亚、中东方向的战略意图、之前已经有过分析，这里不做展开。详细内容请参阅上周《东方时事解读》）。

军事评论员表示，对这种所谓的“敌情与我情”，我们不难从中俄双方签定的“联合战役决心”中、去找寻到它的“应对方案”。请大家再次注意一下这一段，原文是：按照该决心，中俄双方的陆海空军部队，将在山东半岛及其附近海域进行海上联合封锁、两栖登陆作战和强制隔离作战的实兵课目演练。


*** 所谓的“强制隔离作战”显然有着“鲜明的中亚色彩”、“鲜明的实用色彩”

在东方军事评论员看来，不难看出，“海上联合封锁、两栖登陆作战”这两种实兵课目是针对台海、东海、朝鲜半岛方向“可能的意外”、而所谓的“强制隔离作战”显然有着“鲜明的中亚色彩”、有着“鲜明的实用色彩”，我们认为、这是针对“有些人”热衷推动的“颜色革命”、而“量身定制”的反击方案。

东方评论员认为，可以肯定的是，一旦中俄将“两份文件”的政治、经济、军事合作方案、以及这次联合军演所展示的“军事实力”、与“使用这些军事实力的决心”付诸行动、那么、华盛顿要想再在中亚搞什么颜色革命、在东北亚继续不理睬韩国、以及周围国家的国家利益、继续在朝核问题上“老调重谈”、恐怕不那么容易。

事实上，这也正是中俄请上海合作组织的另外“四个成员国”及“四个准成员国”、一起观摩这次联合军事演习的意义之所在，显然，其意义在于“教育”、是让这些国家感受一下中俄战略合作下的实力、与中俄在关键时刻使用这些实力、维护共同利益的决心。

下面，是新华社的一则有关本次军事演习中俄参演军力配置情况的报道，在一起了解详细内容之后，东方军事评论员将结合中俄参演部队的情况、以及中俄双方签定的“联合战役决心”，单纯地从军事层面去解读“军演的第三阶段”。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
