# -*- org -*-

# Time-stamp: <2011-08-04 12:53:58 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 2005年8月16日  星期二



** 以色列总理沙龙发表电视讲话解释单边行动计划




【国际在线8月16日报道】以色列总理沙龙15日晚发表电视讲话，解释实施单边行动计划的原因，并号召维护国家的统一。

沙龙说，他也希望能继续留在加沙地带，但在目前的形势下，以色列不得不撤离。他再次警告巴勒斯坦，如以在撤离期间遭到巴武装分子袭击，以色列将用“最激烈的措施”予以还击。沙龙还呼吁以色列民众保持团结。

15日是以色列实施单边行动计划的第一天。由于定居者的强力阻碍，执行撤离任务的警察和以军士兵未能按计划进入加沙地带大部分的犹太人定居点。

迈出和平新一步以色列开启单边撤离行动

8月15日零时，以色列军警在其占领的巴勒斯坦加沙地带的基素菲姆检查站，将挂着用英文和希伯来文书写的“禁止入内”的红色牌子的栏杆徐徐放下，至此，以色列正式开始执行从加沙地带撤出全部21个犹太人定居点和从约旦河西岸北部撤出4个定居点的单边行动计划。从此，以色列将结束对加沙长达38年的占领，撤离约9000名犹太移民，将土地归还给巴勒斯坦人。巴以和平进程迈出重要一步。

为顺利地实施这一撤离计划，以色列和巴勒斯坦政府及双方军警做了认真、全面、具体的协调和部署。以色列出动了约6万军队和警察，执行政府的撤出行动，并将这一行动命名为“兄弟援手”行动，因为这次行动的对象是“犹太兄弟”。以军方发言人说，从关闭上述检查站起，加沙地带和约旦河西岸北部的定居点已变成了军事禁区，只许出不许进。以色列军警已分成若干小组进入加沙的犹太人定居点，向那些尚未撤出的居民散发传单，要求他们在48小时内主动撤离，如有需要，以军警将提供援助，而超过时限拒绝撤离者，以军警将伸出“兄弟援手”，强行让他们撤出，整个撤离过程将历时三至四周。以军总参谋长哈卢茨要求参加此次行动的数万军警尽最大努力、“心平气和”地完成任务，避免冲突和暴力。

许多定居点的居民响应政府的号召，驾着装满物品的大小车辆在检查站前排队，有序撤离，但还有相当一部分犹太定居者坚决反对撤离计划，并在15日上午与向他们散发传单的军警小组发生冲突，致使军方不得不停止传单的发放工作。在尼菲赫·迪卡沙姆定居点，愤怒的居民砸碎汽车玻璃，焚烧汽车轮胎。更有甚者，一些拒绝撤离的居民竟然在加沙南部由12个定居点组成的古什·卡提夫定居点召开记者会，宣布成立加沙南部“独立犹太政权”，期望有朝一日把这个政权变成一个“独立的犹太国家”，并宣称已致信联合国秘书长安南，要求其承认这个“政权”。此外，在耶路撒冷和加沙定居点禁区外围，聚集了大批反对撤离计划的犹太激进分子，他们企图阻止和干扰撤离行动。由此可见，以色列政府的单边撤出计划不会一帆风顺，三至四周时间能否完成计划，尚难预料。

巴勒斯坦政府、巴各武装派别和埃及方面对此计划给予了全力支持与配合。在以方正式开始执行撤离行动前，巴政府将7500多名训练有素的安全部队和警察部署在犹太定居点附近，其使命主要有三个：一是阻止和挫败激进巴人的任何攻击，保障犹太移民在撤出过程中的安全；二是防止巴人在犹太定居者撤出后，冲进定居点抢劫；三是在犹太定居者完成撤出后，全面接管加沙的安全工作。为协调巴勒斯坦内部立场，巴政府还与巴9个派别的爱国力量及伊斯兰组织组成了一个“跟踪撤离行动全国委员会”，以协调意见，监督以方撤离情况，共同参与国家大事。此外，巴政府还制定了接管加沙的行政工作方案，避免出现任何安全、政治和行政管理真空。

埃及为了保证此次撤军的顺利进行，消除以色列的安全之忧，与以、巴双方达成向距离埃及与加沙边界14公里的地区部署750名埃及边防军的协议，帮助控制巴、埃边境的安全与稳定。

此间分析人士认为，以色列的撤离行动，是美国在伊拉克战争之后，为挽回自身信誉而向以方施压的结果。而巴勒斯坦人则强调，这是巴人武装斗争和不屈不挠的抵抗的结果，希望此次行动能成为“路线图”计划中所允诺的建立独立巴勒斯坦国的第一步。



【时事点评】在东方评论员看来，以色列实施单边行动计划、对大多安适以色列人而言，终归是个好事，因此，我们也注意到，以色列几乎是高达60%民众支持沙龙政府的这一决策。

对此，我们的观点是，以色列民众拥护沙龙的单边行动计划、是认为这能带来“巴以和平”、是认为这种行动将会让以色列社会远离巴以之间持续了几十年的暴力冲突、从而过上和平的生活。因此，在我们看来，以色列实施的单边行动计划、事实上得到了包括巴勒斯坦、以色列大多数民众的支持。


*** “单边行动计划”背后闪烁着众多“大国的影子”

然而，尽管这一行动计划“颇得巴以人心”、但要是有谁就此认为“巴以和平”是指日可待、那也就太过于乐观了。事实上，直到目前为止，我们也没有发现有哪家媒体如此乐观，有的恰恰是“不胜担忧”。

在东方评论员看来，众多媒体“担忧”的背后，显然是透过以色列和巴勒斯坦这两个主角的“无奈”、看到了“单边行动计划”背后闪烁着众多“大国的影子”。


首先，是以色列的“无奈”。在东方评论员看来，此次以色列将归还巴勒斯坦的土地只占整个巴勒斯坦被占领土的１．７％，撤离的定居者也只有以色列定居者总人数的４％。


*** 一句“不得不撤离”点破了沙龙内心的无奈


我们注意到，以色列总理沙龙、对让出这块土地的解释是“此举可以减少双方的摩擦、增加以色列的安全系数”。在东方评论员看来，让素有“推土机”之称的强硬的政治人物沙龙亲口吐出此言、其中的意味恐怕只有这位崇尚“以暴易暴”的“推土机”心中最为清楚。

东方评论员注意到，沙龙在15日晚发表电视讲话，在解释实施单边行动计划的原因时，沙龙说了这么一句话，他说，“他也希望能继续留在加沙地带，但在目前的形势下，以色列不得不撤离”。

在东方评论员看来，一句“不得不撤离”点破了沙龙内心的无奈。


*** 绝对军事优势“不再起作用”的奇怪现象

事实上，沙龙内心的无奈、可以说主要表现在两个层面：

第一，在过去近５年的冲突中，尽管以色列方面对巴民族权力机构和各武装派别实施了沉重的军事打击，再加上国际大环境的改变，就军事力量而言，可以说巴以双方完全是不对称的、以色列拥有各方面的绝对优势。

然而，不难看出，在没有巴勒斯坦（阿拉伯世界）军事方面的威胁之后，以色列的另一个麻烦却来了。我们认为，与美国在伊拉克拥有绝对军事优势、却始终无力重建军伊拉克一样，在巴勒斯坦方面已被打得毫无还手之力、且已经无路可退的情况下，以色列的军事优势也就立刻失去了意义。

显然，这种绝对军事优势“不再起作用”的奇怪现象，通过十几万美军驻在伊拉克、却对几无武装的伊拉克国内局势表现出“始终被动”的事实、“给体现得”淋漓尽致。


*** 更加棘手的“另一面”：那就是人口问题

另外，美军在伊拉克的情景，似乎终于让只相信军事力量、想用“以暴易暴”的手段解决巴以冲突的沙龙、看到了事情还有更加棘手的“另一面”：那就是人口问题。

我们知道，以色列在加沙共有8000名定居居民、而为保护这些定居者的安全，以政府却动用的１万多名士兵。不难看出，以色列这“两万军民”与140万巴勒斯坦居民共同挤在加沙这块小地方、实际上已经使加沙成了世界上人口最稠密的地方之一。

东方评论员认为，“两万军民”与140万巴勒斯坦居民共同挤在加沙的前景，就有如十几万美军与一千多万伊拉克人“住”在一起的前景一样、稍有风吹草动，必然会陷入暴力冲突之中，因此、在我们看来，美军在伊拉克的遭遇让以色列决策者越来越意识到，使犹太人同巴勒斯坦人脱离接触，才符合以色列的长远利益。事实上，沙龙在电视讲话中对让出这块土地的解释成“此举可以减少双方的摩擦、增加以色列的安全系数”、正是针对的“以上两点”。


*** “巴以和平进程”从来都是大国们“逐鹿中东”的牺牲品

另外，沙龙内心的无奈、还表现在另一个层面：“巴以和平进程”一开始是、现在仍然是大国们在“逐鹿中东”过程中“激烈博弈”的牺牲品。随着华盛顿在中东战略再一次到了关键时刻，随着中国、欧盟、俄罗斯都在“各有打算”地在中东与美国周旋，在美国渴望伊拉克政治重建“不至于完全脱轨”的同时、在美国渴望伊朗核问题的这期内不至于完全失控制的同时，欧盟非常在意的“巴以和平进程”、也终于到了必须走出关键性一步的时刻。


*** 沙龙在强硬的同时、也是个手段非常灵活的政治人物

根据我们对沙龙长期的观察，在我们看来，沙龙的强硬是众所周知的，但是它同时也是个手段非常灵活的政治人物。东方评论员认为，之前，沙龙实际上已经尝试着施展各种灵活手段、去极力避免以色列的国家利益牺牲在大国们的“中东倾轧”之中。

在我们看来，沙龙经过一系列手段、硬是将华盛顿的“中东和平路线图”转化成他自己的单边行动计划、在整个过程中、其“灵活手段”可谓是表现得淋漓尽致。


*** 沙龙曾经利用以色列的特殊角色、实实地“拿了华盛顿一把”

我们知道，华盛顿最早提出中东和平计划是在2002年6月、当时，据我们了解，提出这项计划是美国副总统切尼的主意。有非常多的证据显示，切尼是担心“难以解决的中东冲突”可能在政治上对美国的中东利益产生不利影响、因此，这位最为显名的美国鹰派政治人物建议布什主动去打破巴以冲突的僵局。

显然，切尼所关心的中东利益、实际上就是包括已经在华盛顿计划中的攻打伊拉克、颠覆伊朗、建立大中东民主计划的“一整套”中东战略计划。

在华盛顿的主导下、中东“路线图”计划是在当年7月（2002年）开始酝酿的，并在当年年底由联合国、欧盟、俄罗斯和美国“四方代表”在华盛顿举行了一个高层会议，探讨结束巴以争端的途径。

根据我们的观察，沙龙的“手段”在这个过程中显露出来了。当时，会议原打算最后通过、并立刻公布酝酿已久的“路线图”计划。但是，强硬的沙龙硬是要求布什“拖延公布方案的具体内容”，在白宫决策者看来，在没有拿下伊拉克之前、以色列的全力配合、对确保美国的中东战略是极其重要的，显然，沙龙在那个时候利用以色列的特殊角色、实实地“拿了华盛顿一把”。


*** 沙龙的用心显然在于“以拖待变”

事实证明，沙龙强硬地要求布什“拖延公布方案的具体内容”、其用心显然在于“以拖待变”。显然，美国在攻打伊拉克之前、沙龙就已经看到了华盛顿新保守主义者是一定会攻打伊拉克的，沙龙对美国先打伊拉克、再打伊朗、最后控制中东、继而支配世界的战略意图就非常清楚，因此，以色列不仅公开支持华盛顿攻打伊拉克、甚至还用各种方法鼓励美国不要太顾及“老欧洲”的反对、显然，坚信“以暴易暴”且已经将这一政策在巴勒斯坦“身体力行”的沙龙，那个时候和布什一样，对美国在短时间内易将结束伊拉克战争“充满了信心”。

在东方评论员看来，对美国赢得伊拉克战争充满期望的沙龙、终于达到了自己的目的、即将一个早在2002年12月、在伊拉克战争之前就要公布的中东和平路线图、硬是给拖到了伊拉克战争之后。


*** 中东“路线图”的正式推出、与布什单边主义“漂亮的第一步”是紧密相关的

也就是在以色列期待中的“美国已经赢了”的气氛下，在2003年4月到6月间，我们也才正式知道了“正式的”“中东路线图”是个什么东西。即，2003年4月30日联合国、美国、欧盟和俄罗斯中东问题四方正式公布了实现巴以和平的中东“路线图”计划。最后，在6月4日，巴以美三方在约旦红海港口城市亚喀巴举行峰会，宣布正式启动“路线图”计划。

在这里，我们想补充一点的是：大家不要忘记了，在2003年5月1日，美国总统布什特意跑到美国航空母舰上“神气地”宣布“伊拉克战争已经胜利了”，显然，中东“路线图”的正式推出、与布什单边主义“漂亮的第一步”是紧密相关的。

说白了，华盛顿主导搞出来的中东和平路线图、是美国在伊拉克情“迅速取得军事胜利”的情况下、为了继续惯策华盛顿原先提出“中东和平计划”的“原来战略意图”、将攻打伊拉克、颠覆伊朗、建立大中东民主计划的“一整套”中东战略计划的顺利展开，华盛顿有意趁着“宣布伊战胜利”的气势、摆出向反对伊战的“老欧洲”示好的“高姿态”，将“中东和平路线图”当成了第一根抛向“法德”为首的老欧洲、和在中东、特别是在伊朗仍然有相当影响力的俄罗斯。


*** 沙龙利用大国角力的可趁之机，顺势地提出了所谓的““单方面行动”

之后，也仅仅在中东路线图启动后几个月、随着布什所宣布的“伊拉克战争胜利了”在伊拉克被形形色色的反美武装给“搅得”面目全非，美国陷在伊拉克开始“由传说慢慢变成了现实”，再加上华盛顿死抱伊拉克主导权不放手，作为“四方”中的另一方欧盟，对美国抛过来的这根修补关系的胡萝卜，根本就不屑一顾。

在这种情况下，沙龙也就瞄准机会，为了策应华盛顿、以色列先是突然加大对巴勒斯坦的军事打击力度，激起支持巴勒斯坦的欧盟对以色列的强烈抨击，这中间、尤其是支持阿拉法特的法国更是爆发了一场被称之为反犹太人的运动。

之后，沙龙就顺势将主要矛头对准欧盟、并否决了联合国安理会支持中东和平“路线图”计划的决议、公开声称以色列准备提出了一套解决巴以冲突的方案，以备在中东和平“路线图”计划失败后实施。

事实上，这个方案的主要内容就是，如果巴以无法就实施中东和平“路线图”计划达成和解，以方将采取“单方面行动”，拆除在约旦河西岸和加沙地带的部分犹太人定居点，加快修建“隔离墙”工程，并以此为基础，划分以色列和未来巴勒斯坦国的边界，到止为止、沙龙利用大国角力的可趁之机，顺势地提出了所谓的““单方面行动”，并最终得到了布什的“首肯”。


然而，尽管沙龙的“这一套”事后看来“有一气呵成之妙”，但是，在东方评论员看来，自意在帮助美国控制中东的中东战略打好基础的“中东和平计划”、被美国副总统切尼“首倡”开始，不论以色列总理沙龙的手段如何了得，实际上都已经注定要成为大国间角力的棋子。


*** “欧盟政治一体化进程”遭遇了巨大麻烦，为华盛顿分化“中欧俄”战略协调提供了难得的机遇

对此，就如我们之前一再所说的那样，华盛顿抛出“中国威胁论”是其分化中国与欧盟、俄罗斯、印度、制造中日关系破裂的一个“重大战略阴谋”、在东方评论员看来，华盛顿近来全力推动“巴以和平”、与华盛顿近来抛出“中国威胁论”并加以“论证”的意图是相辅相成的。

对此，首席评论员就认为，华盛顿加快“巴以和平进程”的“理论基础”就是“法德”全力推进的“欧盟政治一体化进程”遭遇了巨大麻烦，从而为华盛顿分化“中欧俄”战略协调提供了难得的机遇。


*** 在巴以和平进程的问题上，华盛顿的手段显得非常圆滑与老到

在我们看来，“巴以和平”一旦在美国主导下、按以色列设想的模式得以实现，那么，首先会分裂的是阿拉伯世界，其次将再次分裂的是欧盟；

另外，首先受到“沉重打击”的将是“反美、反以”的阿拉伯国家，其次，依靠这些阿拉伯国家、与依靠以色列的美国争夺中东利益的“中欧俄”、也将因此而失去大量的“筹码”、与展示力量的“支点”。

根据我们的观察，在巴以和平进程的问题上，华盛顿的手段显得非常圆滑与老到，在东方评论员看来，其“最具杀伤力”的手段就是“愿意顺从”欧盟有些国家（比如说英国）的意思、让以色列加快欧盟国家“非常在意”的“巴以问题”之“和平进程”、企图“以此换取”欧盟的分裂、与在伊拉克问题上的让步，从而走出分拆“中欧俄”因两伊问题形成的“抗美集团”之关键一步。之后、一旦“中欧俄”因伊拉克问题落入相互不信任的陷阱，华盛顿就会拿着“巴以和平”做“胡萝卜”、视时机迫使欧盟在伊朗核问题上的立场向华盛顿方向滑动。

然而，中东问题的关键在于伊朗问题。在东方评论员看来，以色列的“单边计划”是否能换得巴以和平、华盛顿最终是否一定有机会拿着“巴以和平”做“胡萝卜”、迫使欧盟在伊朗核问题上的立场向华盛顿方向滑动、仍然言之过早，显然，在巴以和平走出了关键一步之后，伊朗核问题也走出了关键一步。

下面，是一则来自伊朗国家电视台的一则新闻报道，在一起了解内容之后，东方评论将继续今天的中东话题。




《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
