# -*- org -*-

# Time-stamp: <2011-08-04 00:24:53 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 2005年6月08日 星期三



** 美《国际先驱论坛报》：渲染中国军力威胁美难赢得亚太支持

【华盛顿消息】据《国际先驱论坛报》报道，美国国防部近日将公布中国军力年度报告书，将中国军力威胁提升至“最高警戒”级。美国防部长拉姆斯菲尔德也称，中国实际军费开支已居亚洲第一、世界第三，将对“地区安全构成严重威胁”。对于这些指责，美国在亚太地区将很难找到真正有力的支持者。

美国渲染中国威胁，夸大中国军事实力，显然是美国在亚太地区的盟国不愿看到的。就在几天前，新加坡总理李显龙就曾发出警告称，美国对中国采取遏制政策，在亚太地区不会有太多的支持者。

中国也许早就预见到美国会采取围堵政策。拉姆斯菲尔德在新加坡的言论，只是在重复美国的外交政策，至少是布什政府的外交政策。9.11恐怖袭击前，拉姆斯菲尔德及其他新保守主义鹰派就已经在积极造势，称中国正在成为美国的“竞争者”。现在，反恐战争已经接近尾声，华盛顿重新将中国威胁、自由贸易及地区安全等问题提上日程。

过去四年里，美国一直忙于在阿富汗及伊拉克进行反恐作战，中国则利用这一时期在亚太地区打下了牢固的战略基础。过去几个月里，中国与巴基斯坦签定了安全条约，与菲律宾也签下了国防合作协议，而这两个国家都是美国的盟友。中国还与印度、澳大利亚等加强友好合作，如果美国对中国进行遏制，将会遇到这些国家，甚至包括来自日本的阻力。

美国对中国的遏制，是分步进行的，先是要求中国人民币升值，接着对中国纺织品贸易实行制裁，最后再由美国国防部出台中国军力报告书，抛出中国军力威胁论。下阶段，中国很可能会继续实行积极的外交政策，加强在联合国及其它领域的影响力。通过石油投资，中国与非洲、中东及中亚等国建立了非常紧密的友好合作关系。

让亚洲国家感到担心的是，美国夸大中国军力威胁，将会阻断该地区所有的互信建立机制，导致部分热点问题失控，如朝核问题及中国东海油气田问题等。当战争真的爆发时，又有多少亚洲国家会指望美国真能提供有效的安全防卫呢？



【时事点评】对拉姆斯菲尔德抛出“中国军事威胁论”一事，我们已经连续跟踪分析了多天了，在我们看来，华盛顿使出的这一招，就如我们昨天所说的那样，不论是“原汁原味”的“中国威胁论”、还是经过“单项处理”过的“中国军事威胁论”，从亚洲国家的初步反映来看，它在亚洲、特别是东亚、东南亚都是不得人心的。

*** 这篇报道一针见血地“刺中”了华盛顿的“精心算计”

事实上，华盛顿决策层“用心炮制”的这一套、用“单项处理”“精心包装”的战略手段，不仅我们能够看得出来，就是美国媒体也是清清楚楚。在东方评论员看来，美国《国际先驱论坛报》的这篇报道，可以说就一针见血地“刺中”了华盛顿的“精心算计”：

请大家注意这么一段，原文是：美国对中国的遏制，是分步进行的，先是要求中国人民币升值，接着对中国纺织品贸易实行制裁，最后再由美国国防部出台中国军力报告书，抛出中国军力威胁论。

*** 美国的这套“组合拳”、正是这样一路施展过来的

事实上，如果您这几天一直在关注我们的“讨论纪要”的话，那么，相信您也一定《国际先驱论坛报》所描述的“这一程序”印象深刻。在东方评论员看来，美国的这套“组合拳”、正是这样一路施展过来的。

显然，按照《国际先驱论坛报》的“描述”、以及我们之前的分析，在布什点出“单项处理”“新观点”、紧接着、是拉姆斯菲尔德“照方抓药”、在亚洲方向抛出“中国军事威胁论”之后，接下来的一幕、应该是“正式确立”“中国军事威胁论”的《中国军力报告》粉墨登场了。

*** 五角大楼不断“出意外”、“根子”就在白宫

然而，最新的消息说，五角大楼以“没有准备好”为由、推迟了“按计划应该在几周前”就公布的《中国军力报告》。当然了，既然五角大楼说“没有准备好”、那自然就是“没有准备好”，只是这样接二连三的“出意外”，人们也不难免去嘀咕“到底什么时候才能准备好？”

在东方评论员看来，五角大楼之所以不断“出意外”、其实“根子”就在白宫那里：布什不是说中美关系太复杂吗？而且是“错综复杂”吗？既然如此，一个“各种利益犬牙交错”、“错综复杂”的中美关系、又怎么可能去“人为地、简单地”分解成这个面那个面呢？还要美其名为“单项处理”。


*** 华盛顿的“中国军事威胁论”何以在亚洲推销不出去？

我们认为，华盛顿的“中国军事威胁论”之所以在亚洲推销不出去，其中最大的原因恐怕就在于只从美国自己的角度去考虑问题、只强调中国所谓的扩军威胁，却没有看到中国对这一区域的的经济贡献已经“不可抺杀”，更没有看到美国的力量“已经有限”，“不再能单方面地”去主宰亚洲事务、更不能“随心所欲地”去决定东亚的局面了。

与此相反，和中国在一起发展的大部分亚洲国家、感同身受的却是中国对这一区域的的经济贡献，同时，也看到了美国力量的“有限”。在东方评论员看来，这些“现实的对比”、足以让亚洲国家感到担心，这种担心就如《国际先驱论坛报》所说的那样，担心美国如此这般地“夸大中国军力威胁，将会阻断该地区所有的互信建立机制，导致部分热点问题失控，如朝核问题及中国东海油气田问题等。当战争真的爆发时，又有多少亚洲国家会指望美国真能提供有效的安全防卫呢？


*** 上面的那一句“疑问”、其实点破了亚洲国家为什么反对“中国军事威胁论”的“实质”

在东方评论员看来，上面的那一句“疑问”、其实点破了亚洲国家为什么反对“中国军事威胁论”的“实质”，就如我们在昨天点评中所说的那样：在这些国家的眼里，让中国和美国“在某种程度上竞争”、对他们是有好处的，然而，这些国家的领导人也明白，一旦这种竞争延伸到“政治、军事上的恶斗”、以至于最后发展到“中美圈地、各国选边”，那么，最终倒楣的还是这些区域内的“小国家”。这个道理非常简单，就有如“兵慌马乱的时候，老百姓才是最遭殃的”道理一个样。不是吗？“当战争真的爆发时，又有多少亚洲国家会指望美国真能提供有效的安全防卫呢？”

*** 美国的商务部门“精心炮制”了“中国威胁论”的另个一个版本

东方评论员认为，拉姆斯菲尔德没有想到“他主管的五角大楼”所炮制的“中国军事威胁论”、在亚洲这个主要宣传方向上、遭遇的“反对的声音”竟然如此之大，事实上、有消息说，拉姆斯菲尔德也受到了来自美国其他部门的质疑，也正是在离开新加坡的飞机上、拉氏下令“再次修改”准备于今天发表的《中国军力报告》。

根据我们的观察，就在华盛顿决策层让军事部门在“西太平洋”方向、用中国的导弹“可以射向任何国家”来“突显”中国的“军事威胁”、去“化解”东南亚“小国家”、着眼于与中国经济关系的“经济小道理”的时候，华盛顿决策层早就下令让其商务部门、好好琢磨如何在“大西洋上”、也精心炮制“中国威胁论”的另个一个版本、去“化解”欧盟着眼于与中国战略关系的“政治大道理”。

*** 华盛顿朝向“大西洋对岸”宣传“中国威胁论”时“另换曲调”

中国有句老话，叫做“到什么山上唱什么歌”，显然，华盛顿朝向“大西洋对岸”宣传“中国威胁论”的高音嗽叭、在进行广播时自然就得“另换曲调”了，在东方评论员看来，与美国隔着大西洋的欧洲，可不担心什么“中国军事威胁论”，不仅不担心，在法、德的一再努力下、欧盟反而一直在考虑“何时解除”对华军售禁令、如果不是华盛顿拼命地从中作梗，这事情说不定已经成了。

在东方评论员看来，不论是人民币升值与否问题、还是纺织品将是否会引起贸易战的问题、实际上都是在布什“单项处理论”这一“最新中美关系理论”指导下的“杰作”。


*** 面向欧洲的“中国经济威胁论”何以比面向亚洲的“中国军事威胁论”高效得多？

也就是说，由于欧盟“还不是一个统一号令的整体”，再加上欧洲成员国的经济表现不一，因此，美国拿着将“中国威胁论”“单项处理过的”“中国经济威胁论”、去冲着欧盟进行宣传的时候、其在欧洲国内产生的效果、显然比经济高速增长的亚洲国家要高出了得多。

东方评论员认为，之所以出现这一原因，恐怕就在于欧洲各国的经济各有特点，从而对中欧关系、和中欧经贸的认识是不平衡的、这一点，我们在“解禁对华军售”这样深具重大战略意义的事情上、欧盟都很难取得一致意见、就可想而知。

再加上欧盟一体化进程又遭遇重大挫折，如此一来，欧盟就不可能以一个声音代表一个统一的欧盟、去关注欧盟最重要的利益，这些，都为美国向欧洲各国有针对性地散布“中国经济威胁论”提供了机会。


*** 法国人在历史上就曾经玩过这么一回

对法、德这两个有政治报负心的欧洲核心国家而言，“解除对华军售”可不是“仅仅为了赚钱”这么简单，在东方评论员看来，这两个有政治报负的“欧洲核心”、之所以“如此卖力”、就在于这根本就是想着如何去增强“中国的军事威胁”，至于中国的军事到底能威胁谁，中、美、欧可以说心里都有一本账。

特别是法国、在历史上就曾经玩过这么一回，通过增强美国的军事力量、从而、美国不仅将英国赶出了美洲大陆、还成了英国心中的一块心病，由于强大了的美国、开始对英国的海外利益“虎视耽耽”，曾经一直压制、并欺负着法国的英国、终于不敢对法国“再用强”了、这才给了法国后来崛起的机会。


*** “两件事”本来就对欧美的经济“意义不大”、但对中国的影响却大得不得了

因此，华盛顿经过一番“单项处理”之后，面向欧洲发行的“中国威胁论”，在军事方面也就“不去着重”，而是加进了“汇率”、“纺织口”这两味成份，如此也就炮制出了这一份“中国经济威胁论”。

欧洲和美国一样清楚，不论是人民币升值与否、对自己的贸易的“盈余”影响不大，而中国纺织品出口虽然突然增加、冲击了自己的纺织业，但这些对欧美经济的影响也不大，特别是欧洲、比如法国、意大利、德国、它的许多高价值消费品的一个重要出口地就是中国。

也正因有上面这一层，事实上、欧美在这一轮“中欧美”“汇率”、“贸易”争端中的的心情复杂，因为，上面“两件事”本来就对欧美的经济“意义不大”、只是“这两样事情”对中国的影响大得不得了。显然，从任何角度上看，中国都不会全盘接受欧美的标准、去放开人民币、接受纺织品出口限制的。

为了更好地说明这个问题，我们再来看一段新闻。之后，东方时事评论员、经济评论员将继续在一起展开讨论。
《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 诺贝尔奖得主指美中贸易争端不会升为贸易战

【北京消息】诺贝尔经济学奖得主盖瑞·贝克尔日前在接受新华社记者专访时说，近日恶化的美中纺织品贸易纠纷不会上升为贸易战。

在被问及美中间的磨擦是否会升级为贸易战时，贝克尔态度非常肯定。他说：“不会，不会，绝对不会！我认为只会以更多贸易的方式收场。”

贝克尔的看法与一些中国分析家的观点相似。他们认为，双方可以通过谈判解决问题，并排除发生贸易战的可能性。

中国商务部长薄熙来日前表示，在过去２６年中，中美两国经济贸易合作取得了巨大进步，两国有能力解决纺织品和其他商品贸易中发生的问题。

美国商务部长古铁雷斯也表示，美国政府希望双方通过谈判解决纺织品贸易问题，并希望进一步加强与中国的经贸关系。

不久前，美国以中国服装和其他纺织品的进口较去年水平上升了５４％为由，在根据世贸规则取消相关配额４个月之后，于５月份对７种中国纺织和服装产品重新施加配额。而数字显示，去年中国对美纺织品出口达到９０．６亿美元，仅占双方贸易总额的５％。

根据中国纺织工业协会统计，美方的设限措施将在一年内导致约１０万中国人失业，并将破坏中国纺织业的投资环境。

对于中美间目前的纺织品贸易磨擦，担任美国芝加哥大学教授的贝克尔认为，这与明年的美国国会大选有关系。

贝克尔说：“纺织行业在美国经济中的地位并不重要，但它有不少公司和雇员分布在一些对国会选举来讲具有政治意义的州。”

“问题就是这样。我赞成自由贸易，不赞成任何国家对贸易施加限制。”

“我希望磨擦会朝着自由贸易的方向得到解决，”他说。

同时他认为，“美中两国在国际市场上是互补的，并不仅仅是竞争对手。”

“美中两国间的经贸关系主要是互补关系，都会从更多的自由贸易中受益，我更愿意问题以达成更多纺织品自由贸易的方式解决。”



【时事点评】我们注意到，在被问及美中间的磨擦是否会升级为贸易战时，贝克尔态度非常肯定地表示：“不会，不会，绝对不会！我认为只会以更多贸易的方式收场。”

然而，在东方评论员看来，要出现以“更多的贸易方式收场”这种喜剧性画面、恐怕得有一个前提条件，那就是北京“是否敢于打贸易战”。


*** “中欧美”一旦开打“贸易战”，后果不堪设想！

东方评论员认为，如果“中欧美”一旦开打“贸易战”，那么，由于中国、欧洲、美国相互间本来就是“彼此排名前几位”的贸易伙伴，再加上彼此“都有过万亿美元”的外贸总量，显见，一旦这“一、二、三”名一旦开打贸易战，其影响将是全球性的、后果不堪设想！

在东方经济评论员看来，“中欧美”贸易战对中国这种以“实体经济”为主的经济结构之打击、都将是非常沉重的，更何况对欧美这种服务业为主体的经济结构，在我们看来，特别是对美国这种虚似经济体，对其金融服务业，由于有着大量衍生交易、其打击将是更加沉重。

因此，只要北京最后拉开架式，准备不惜“以贸易战的方式”做为解决问题的“主要方案”时、在东方评论员看来，这场“人民币”“纺织品”争端、才会最终转化成“只打雷不下雨”。



*** 北京在处理过程中、也有值得反思的地方

首席评论员指出，从某种意义上讲，欧盟同中国一样，也是正处在“和平崛起”的路上，与美国不同的是，中国和欧洲要成为世界强大的一极，似乎都在走“亚洲、欧洲经济一体化”的道路。

如果我们从这个角度去看问题、就不难看到，在挑起这一轮“中欧美”经贸争端的背后，华盛顿决策层显然是非常狡猾的。根据我们的观察，美国成功地利用了法、德这两个欧盟核心国家新近遇到的挫折、以及急于从这种挫折中走出来的心理，还利用了欧盟的另一个核心国家--英国、在欧盟中怕失去自己影响力的自私心理，以及欧盟其他成员国在与中国的经济往来中、有着各种各样的、“追逐私利”的动机，将欧盟也拉进了这场旨在瓦解中欧战略合作的“中欧美经济角力”中。

在东方评论员看来，综合“中国军事威胁论”和“中国经济威胁论”在亚洲和欧洲引起的不同反映来看，对美国这套将“中国威胁论”“单项处理”的策略，北京有很必要保持警惕、认真应对，从“欧美”可以抛开政治利益的分岐、而共同在“人民币”、“纺织品”问题上对中国展开攻击的事实来看，北京在处理过程中、有值得反思的地方。

对此，首席评论员就指出，北京一开始似乎单纯地将其视为经济问题了，而没有从政治层面过多考虑，这就导致想单方面通过经济让步解决问题，这才有“自己主动加税”这一幕。


*** 针对欧美各自所打的算盘，北京实际上没有“单方面让步”的“本钱”。

东方评论员认为，美国人在与中国为“纺织品”和“民币”问题争吵不休的同时，心里也明白，这争的不是“纺织品”和“民币”，而是在争政治、争军事、是在与“中欧俄”争未来的霸权；而欧洲内部的各个国家、在与中国人争这些经济问题的时候，恐怕心里也有一本各自的“小九九”，那就是“能捞多少就捞多少”。

显然，针对欧美各自所打的算盘，北京实际上没有“单方面让步”的“本钱”。在东方评论员看来，如果北京不在这一轮“经贸角力”中、顽强抗击的话，那么，今后什么“打火机争端”、“箱包争端”、“玩具争端”等等、只要是中国企业占据优势的待业和产品，都将被扣上种种理由、“一而再、再而三”地遭遇麻烦。


*** 北京扬言，在“开放农产品市场”方面也准备不妨“说话不算数”

有意思的是，中国已经扬言，如果“欧美”拿中国的“纺织品”说事、说话不算话的话，那么，中国也准备在“开放农产品市场”方面“重新考虑”，也不排除“说过的话不算数”的可能性。

众所周知，美国是世界农产口的主要出口大国，而中国又是主要的进口大国，因此，在东方评论员看来，这次北京表示在“开放农产品市场”方面也准备不妨“说话不算数”，其矛头所指，是显而易见的。


*** 北京这种“不将欧美看做一个整体”的做法是明智的

东方经济评论员认为，在这一轮经贸角力中、北京这种“不将欧美看做一个整体”的做法是明智的，华盛顿不是在对“中欧”搞“分而化之”的策略吗？，那么，北京最好的反击方式当然也是“擒贼先擒王”，将对美国影响面最大的“农产品”拿来说事，从而在“欧美”的“共同施压”中、也针对美国的“分而化之”策略、找出一条“各个击破”的方案来。

在我们看来，相对于“中欧美”各个国家而言，经济问题都将给自己带来国内的政治压力，中国也不例外。因此，东方评论员认为，“中欧美”这一轮“经贸争端”、持续到现在，就要到最关键的时刻了，也就是说，经过这么长时间的媒体报道，不仅相关国家内部对此高度关注、就是世界其他国家也在密切注视之中。

*** 这一轮“中欧美经贸争端”的“实质”之所在

在东方评论员看来，这一轮“中欧美经贸争端”如果完全撇去其他因素的话，那么，它实际上反映了这么一个“实质”，即经济一体化、自由贸易都是发达国家出于自己的利益搞出来的玩意儿，按他们的想法，这种游戏规则最适合发挥他们的技术、资本优势，因此、按道理、也只有他们去威胁别人、兼并别人、轮不到别人去威胁他们、兼并他们。

然而，当发展中国家、比如中国纺织品行业的所体现出来的竞争优势、威胁到他们的产业时，这些游戏规则的制定者们就不干了，就想找由头、寻理由不遵守自己制定的游戏规则、从而“说话不算数”。

显然，“中欧美”贸易争端，表面上是三方的事情，事实上，却代表了全球经济一体化、自由贸易“公平与秩序”。在东方评论员看来，中国做为一个最大的、也是最具实力发展中国家，在这个问题上，也有必要在这个关键时刻“体现出责任感”来，即是为自己、也是为发展中国家、同时也是为WTO尽可能地争得一份“公平与秩序”。我们认为，这也正是这场举世关注的“贸易争端”的重要意义之所在。

下面，我们一起来看一段“军事新闻”，之后，东方军事评论员将结合传说中的《中国军力报告》所描述的“科幻小说”，谈谈中国的太空军事力量。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
