# -*- org -*-

# Time-stamp: <2011-08-23 14:49:48 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

#+STARTUP: indent

#+TITLE: 2005年01月04日 星期二



** 鲍威尔预测:什叶派会赢得本月伊大选的胜利

   【华盛顿消息】据法新社报道，美国国务卿鲍威尔昨日预测说，伊拉克什叶教派将赢得本月30日举行的伊拉克大选的胜利。

   “即将在巴格达选出的新政府以及带有过渡性质的国民议会，将属于人口占多数的什叶教派，”鲍威尔在接受美国国家广播电视公司/NBC采访时说，“他们是伊拉克人口的多数派。”

   #+LaTeX:\red{
   #+HTML:<a>
   目前，什叶教派占伊拉克全国总人口的60%，绝大多数居住在伊拉克的南部与中部地区。伊拉克另一教派——占全国人口20%的逊尼教派主要居住在西部与中部地区。
   #+HTML:</a>
   #+LaTeX:}
   
   鲍威尔同时重申，本月30日的伊拉克大选将如期举行，并坚称由什叶派主宰的国民议会不应成为人们担忧的理由。

   另据报道，此前，属于逊尼教派的伊拉克独立民主党呼吁推迟选举，称在目前的情况下进行选举“将剥夺一大批人的公民权，并且许多地区不能被充分代表。”
 
 

   【时事点评】这些天来，东方评论员一直在关注着中东的情况、说起来，有一个现象非常值得一提，那就是，就在东方评论员们一致认为北京和欧洲有意将伊拉克选举与巴勒斯坦选举捆绑在一起的时候，我们注意到，华盛顿在公开场合、却一直没有表示出任何、哪怕是一点儿这方面的意思。相反，直到不久前，我们听到、看到的，却是布什、鲍威尔等人、都还在信誓旦旦地表示：“伊拉克选举一定会如期举行”。


*** 鲍威尔有“处乱不惊”的本事，到了这个节骨眼，仍然还能沉得住气！

然而，就如我们之前一直强调的那样，由于布什下令重兵攻击费卢杰，结果终于造成了目前这种、让自己哭笑不得的结果：即，华盛顿原本想压制的伊拉克什叶派，由于有望成为最大的赢家，反成了推动、并维护美国原定于这个月底举行的大选“最为积极的力量”。

面对这一现状，东方评论员倒是“非常欣赏”美国国务聊鲍威尔“处乱不惊”的本事，到了这个节骨眼，仍然还能沉得住气！

然而，就在我们注视着美国决策层仍然不停地、也“非常坚定地”、向外散布着“一定会按时选举”的信息的同时，伊拉克临时政府却传出了与华盛顿决策层不一致的观点，在东方评论员进一步给出我们的观点之前，我们先来看看相关新闻。
 
 《东方时代环球时事解读》http://www.dongfangtime.com
 
 
** 伊拉克国防部长：本月三十日选举可能延后

【巴格达消息】伊拉克国防部长沙兰今天说，如果逊尼派选民同意参与，那么该国预定在本月三十日举行的划时代选举就可能会延后。

沙兰接受记者访问时说：「我们已请求阿拉伯各兄弟国家、特别是埃及和波斯湾各国，劝使伊拉克逊尼派教徒参与选举，而若他们的参与须要以延后选举作为配合，那么选举就可能延后。」他在被询及、美国是否会同意延期时说，他相信，「美国将乐于见到因为所有选民都参与而使选举作业完整」。

他说：「我们希望再给我们的逊尼派兄弟们一次机会，即使要延后选举，也在所不惜。」到目前为止，美国总统布什对于延后选举的想法均嗤之以鼻，而伊拉克官员们也坚称，选举必须依计划在元月三十日举行。
 

【时事点评】请大家注意这一段：伊拉克国防部长沙兰说：“我们希望再给我们的逊尼派兄弟们一次机会，即使要延后选举，也在所不惜。”


*** “傀儡”表示“即使要延后选举，也在所不惜”的背后究竟发生了些什么

在东方评论员看来，这位伊拉克国防部长的所说的“如果逊尼派选民同意参与，那么该国预定在本月三十日举行的划时代选举就可能会延后。”显然与布什的“对于延后选举的想法均嗤之以鼻”的报道极其矛盾。

我们都知道，伊拉克临时政府是一个、从人员到机制，都是地地道道的傀儡政府，这一点没有人怀疑，因此，东方评论员认为，在“傀儡”开出条件表示“即使要延后选举，也在所不惜”的背后究竟发生了些什么，那就要去问“操纵傀儡”的华盛顿了。
 
*** 美国很早前与逊尼派的萨达姆能够紧密合作的基础


在之前的《环球时事解读》中，东方评论员已经多次说过，
#+HTML:<a>美国伊拉克战略的核心，就是建立一个由亲美的世俗派人士主导的政权，从而在权力移交后能够确保美国在伊的地位和利益，并引导未来政权走上“民主”的亲美路线。</a>
#+LaTeX:\red{美国伊拉克战略的核心，就是建立一个由亲美的世俗派人士主导的政权，从而在权力移交后能够确保美国在伊的地位和利益，并引导未来政权走上“民主”的亲美路线。}
这一点，正是美国很早前与
#+HTML:<a>逊尼派的萨达姆</a>
#+LaTeX:\red{逊尼派的萨达姆}
能够紧密合作、反对什叶派的伊朗之基础。

然而，在华盛顿军事攻占逊尼派三角地带的核心区域-费卢杰之后，美国新保守主义眼中原来最可依赖来建立世俗政权的势力-伊拉克逊尼派却公开表示退出选举。

目前，伊拉克国内的形势对伊拉克什叶派最为有利，如果布什果真对“任何延后选举的想法均嗤之以鼻”的话，那么，可以肯定的是，美国务卿鲍威尔所预测的“伊拉克什叶教派将赢得本月30日举行的伊拉克大选的胜利”将成为事实。
 
*** 半年前，美国人做得最露骨的“两件事”

然而，如果伊拉克什叶派控制了伊拉克的“国会”，那么，可以预料的是伊拉克的政治局面将对华盛顿更加不利，甚至可能造成华盛顿一手扶植起来阿拉维临时政府的提前终结，这绝不是华盛顿所愿意看到的结局。

也许大家还记得，在今年6月底美国占领当局向伊拉克临时政府移交政权的前后，所有的迹象都在证明一件事情，那就是：华盛顿占领当局可以说采取了各种手段限制伊拉克新政府的权力，并加紧安插亲信，以确保在政权移交之后，美国仍能“垂帘听政”，从而在幕后牢牢控制这个具有重要战略地位和丰富石油资源的国家。

其中，东方评论员认为美国人做得最露骨的“有两件事”，第一，就是当时就要向伊拉克“全面移交”政权的美国驻伊拉克最高文职行政长官布雷默、赶在临上回国的飞面前，签署了一大堆的“政令”，又是“修订伊拉克法典”，又是“任命了至少二十多位伊拉克人出任政府要职”。
 
*** 一个反美的“国会”怎么可能容忍一个亲美的政府？

对于“那一大堆的赶忙之中签署的法令”，美国占领军当局是这样形容的：这些法令“是为了确保伊拉克人民提供约束及指导”，而且在现在仍然生效。我们注意到，伊拉克临时宪法的附件规定，要推翻布雷默签下的任何政令，需先得到阿拉维为首的大多数部长批准，包括临时政府总统及两位副总统，显然，指望阿拉维自己推翻自己几乎是不可能的。在东方评论员看来，华盛顿半年前导演的这一幕，就是要确保目的是要保在“如期移交政权”之后，伊拉克仍能继续按他的理念接受管治。

美国人做的另一件露骨的事，就是布雷默卸任前下令，他挑选的总理阿拉维所任命的国家安全顾问及国家情报机关首长任期长达五年，从而使阿拉维的抉择将凌驾于可能今年晚些时候、也由选举产生的伊拉克政府。

显然，面对着一个由什叶派控制的“伊拉克国会”将会导致伊拉克政局向什么方向发展，可以说是明眼人一看便知的，因此，东方评论员认为，鲍威尔在这个时候重申，“本月30日的伊拉克大选将如期举行，并坚称由什叶派主宰的国民议会不应成为人们担忧的理由”、实在是让人“怀疑是在言不由衷”，起码在我们看来，华盛顿的担心是根本就是“不言而喻”的：一个反美的“国会”怎么可能容忍一个亲美的政府？
 
*** 布什及其强硬的新保守主义参谋班子显然是“别无选择”

东方评论员认为，如果我们站在华盛顿的角度来看问题，那么，一个最有争议、但也最简单的解决办法就是让月底的选举延期，虽然这样做会被其它强权视为”美国伊拉克战略的又一次重大失败”，也可能被嘲笑为“无异于向企图破坏选举的伊反美武装屈服”、还可能在需要同其它强权进行新的一轮“讨价还价”处于更加不利的地位，从而还要付出更多的政治、经济代价，但是，比起让伊拉克出现一个反美的“国会”、继而继续衍生出一个“反美”、至少是“不亲美”的伊拉克政府之结果而言，我们认为，布什及其强硬的新保守主义参谋班子显然是“别无选择”。
  
*** 伊拉克傀儡政府冲着其美国老板做最后一次“呐喊”！

因此，搞清楚了华盛顿真正想要的是什么，那么我们也就不难看出，伊拉克国防部长沙兰所说的“我们希望再给我们的逊尼派兄弟们一次机会，即使要延后选举，也在所不惜。”这一类的话，明显是替华盛顿说出了自己“不好意思”、或者“还不到时候”承认的“心里话”而已。在东方评论员看来，与其说伊拉克傀儡政府是在给逊尼派兄弟最后一次机会、还不如是在冲着其美国老板做最后一次“呐喊”！

事实上，为了让伊拉克选举“推迟”，华盛顿和伊拉克临时政府似乎已经开始做“公开的准备工作”了。我们注意到，就在布什、鲍威尔在不同场合仍然在态度坚定、异口同声地保证要“选举必须依计划在元月三十日举行”的时候，伊拉克临时政府又传来一则新闻，我们还是先来熟悉一下具体内容，之后，东方评论员将继续这个话题。
 
 
 
《东方时代环球时事解读》http://www.dongfangtime.com
