# -*- org -*-

# Time-stamp: <2011-08-02 22:46:41 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

#+STARTUP: indent

* 2005年5月24日 星期二

** 5月24日外交部发言人孔泉在例行记者会上答记者问

【外交部网站消息】5月24日下午，外交部发言人孔泉主持例行记者会。下面是有关中日关系内容节选

　　问：吴仪副总理取消了和小泉首相的会晤。根据中国外交部的消息，此次访问取消的理由是国内有紧急公务。请问这个紧急公务是什么？如果这次取消会晤和小泉关于靖国神社的言论没有关系，为什么中方在今天上午新华社的表态中如此强烈地谴责小泉首相参拜靖国神社？

　　答：昨天晚上，我在回答媒体提问时做了完整的表态，新华社已于当晚11点发表了这条消息。看样子，你对这条消息的全文不是十分了解，我在这里向你重新介绍一下。

　　昨晚我阐述了以下看法：中国政府高度重视中日关系，我们一直在为改善和发展中日关系做出不懈的努力。吴仪副总理对日本的访问也充分体现了这一点。但是令人遗憾的是，就在吴仪副总理访问期间，日本领导人接连就参拜靖国神社发表了不利于中日关系改善和发展的言论。中方感到十分不满。我们真诚地希望双方能够共同努力，落实胡锦涛主席在雅加达与小泉首相会见时提到的五点主张，推动中日关系走上健康稳定发展的轨道。

　　问：今天上午，日方一些官员表示，中方的态度缺乏一些外交上的礼仪。中国政府对此有何评价？

　　答：你提到的日本方面一些官员的说法，我也看到了。我的看法是，在今年全世界都在庆祝反法西斯战争胜利60周年的时候，在中国人民庆祝抗日战争胜利60周年的时候，日本领导人不顾中国人民的感受和感情，漠视中国人民作为受害者在那段令人难以忘却的历史中所遭受的日本军国主义的烧杀劫掠，无视自己多次表示的反省历史的承诺，最近接二连三地就参拜靖国神社问题发表错误的言论，难道心中没有丝毫歉疚吗？

　　问：你的意思是否是说吴仪副总理昨天突然回国的原因是靖国神社的参拜问题？昨天中国政府说是因为突然有紧急公务，请澄清。

　　答：我刚才向大家介绍了我昨天晚上的表述，也就是我们的正式态度。在目前情况下，特别是在中方作出了一系列真诚的、希望不断发展改善中日关系努力的情况下，日本领导人还连续发表了不利于中日关系健康发展的言论。显然，两国领导人的会晤缺少必要的合适气氛。

　　问：据报道，今天早上日本外相町村信孝说，日方认为中国政府应该有一个好的解释，甚至可能是道歉。因为昨天取消的和小泉总理的会晤原来都已经约定好了。中国政府会道歉吗？另外有报道说，美方向中方提建议，人民币应该升值10％，以避免美国国会出台一些对中美贸易不利的新法案，请问中方有何反应？

　　答：我在回答刚才日本媒体的提问时已经表明了我们的立场。今年全世界都在纪念反法西斯胜利60周年，中国也在庆祝抗日战争胜利60周年。你知道抗日战争在中国意味着什么？在中国意味着8年抗战，死伤人数3500万，直接损失1000亿美元，间接损失高达5000亿美元，在中国许许多多的家庭留下了巨大的伤痛。日本军国主义当时在中国的种种罪行罄竹难书。

　　日本领导人在这样的背景下，违背自己的承诺，不顾自己向国际社会作出的反省历史的表态，一而再、再而三地就供奉着甲级战犯的靖国神社问题发表错误言论，难道就丝毫没有考虑到广大受害国人民的感情吗？难道说广大受害国人民这种无法弥合的伤痛，在他的眼里就没有丝毫的价值吗？

　　关于你的第二个问题，我们已经多次表明立场。汇率改革是中国主权内部的事情。条件成熟了，没有外界压力，中国也会改革；内部条件不成熟，即使外界再大的压力中国也不会这样做。中国不但对自己的经济发展采取负责任的态度，而且对世界和地区经济的发展也要采取负责任的态度。中美在汇率上问题有些不同看法。最近美国有不少高级官员访问中国，中国的一些高级官员也访问了美国。我们还是希望双方能够通过平等对话，进一步加强相互了解和理解，不断推动中美经贸关系在健康稳定的基础上向前发展。

　　
　　问：既然吴仪副总理有紧急公务处理，为什么她坚持对蒙古进行访问？第二个问题，中日东海问题磋商能否按计划进行？

　　答：吴仪副总理对蒙古的访问是一次很重要的访问，对双边关系具有重要意义。根据我掌握的日程，她将同蒙古副总理乌兰进行议题广泛的会谈，与蒙古现任总统巴嘎班迪及新当选的总统、现任议长恩赫巴亚尔进行会晤，还将会见总理额勒贝格道尔吉。这些会晤将为两国领导人提供一个深入交换意见的机会，使双方能够总结近年来双方关系发展取得的重要成果，并对两国今后一段时间的互利合作做出规划。

　　有关中日东海磋商问题，我没有接到有变化的消息，我相信近期中日双方将就东海开发问题进行磋商。

　　问：刚才你谈到吴仪副总理提前回国是因为靖国神社问题，中方究竟对哪些言论感到不满？沈国放今天上午表示只要日本对靖国神社问题采取正确态度，其它问题都比较容易解决。你对此有何评论？日本一些人士对吴仪副总理取消会见感到不满。中日应通过对话解决两国之间的问题。如果放弃会谈，如何解决两国之间的问题？

　　答：你的第一个问题问及日本领导人发表了哪些谈话。作为日本媒体驻京记者，我深信你对中日关系的经纬是清楚的，对中日三个政治文件的内容是清楚的，对日本领导人一再表示要反省历史、反省侵略，以及中方提出的“以史为鉴、面向未来”的一系列政治原则是清楚的。建议你认真看一看贵国报纸近10天来对贵国领导人的言行所做的报道，对比一下，日本领导人哪些言行不符合这些政治文件和原则的内容，我相信你一定能够找到，而且不是一两件。

　　沈国放部长助理今天上午会见媒体朋友看来是富有成果的，不少问题都是关于他这次采访的。实际上他所说的，至少你刚才引述的那段话，也表明了我们的一贯立场，即中日双方在一些问题上有不同的看法和分歧。中日政治关系当前面临困难最主要的问题就是靖国神社问题，实际上这不仅仅是中国人民关注的问题，也是亚洲人民、国际社会关注的问题。日本是不是真正要走和平发展的道路？人们有理由担心，在世界反法西斯胜利60周年这样富有历史纪念意义的时候，日本领导人可以无视国际社会的呼声，无视受害国家人民的感情，一而再、再而三地在这个问题上发表极端错误的表态，使人们难免对这个问题感到非常担心。

　　关于你的第三个问题，我赞同你的部分看法。中日之间存在的问题，应该通过见面、通过沟通来增进相互了解，这是对的。但是另一方面我希望你能注意到，中方作出了巨大的努力。从去年圣地亚哥胡锦涛主席同小泉首相的会晤开始，直到今年，特别是最近一个月，包括4月23日胡锦涛主席在雅加达再次会见了小泉首相，提出了关于改善和发展中日关系的5点主张。两国领导人会晤时我在场。这5点主张得到了小泉首相的积极回应，他表示愿意同中方共同努力。一个月后，具体地说，是5月22日下午，胡锦涛主席在北京会见了贵国执政两党的干事长，他再次表明了中方在有关问题上的立场，希望日方能够同中方一道以史为鉴、面向未来，使中日关系在健康、稳定的基础上向前发展。

　　除了中国国家主席的两次会晤外，吴仪副总理在公务非常繁忙的情况下赴日本访问。刚才大家都谈到吴仪副总理对日本的访问缩短了。实际上，我认为大家的注意点不应该仅仅集中在缩短访问的问题上，应该看到吴仪副总理对日本的访问是取得了一些积极成果的。她主持和参加了中国馆日的活动。据我了解，中国馆日的活动在爱知世博会期间受到了日本人民的热烈欢迎，增进了中日两国人民之间的相互了解和友谊。除此之外，吴仪副总理还发表了两次演讲。其中一次是在贵国的经济新闻社关于亚洲未来的研讨会上，她非常全面地阐述了中国政府对中日关系的重视和积极态度，并且提出了发展中日互利经贸关系的6点主张。除了这两项之外，第三项就是她落实两国元首达成的共识，同日方各阶层、各部门、各级别的人士广泛接触。所以你应该注意到，吴仪副总理这次在日本的时间虽不长，接触的日方人士之多是前所未有的。通过这些接触，她也深切感受到了日本人民希望进一步同中国人民发展友好关系的愿望，同时她也转达了中国政府和人民在健康、稳定的基础上进一步发展中日世代友好关系的强烈愿望。这些都是她访问的积极成果，无论是日本媒体还是其它国家媒体都应该予以报道。

　　问：作为外国记者，我们认为中方在解释吴仪取消会见小泉原因时产生了混乱。取消会见的决定是谁在何时作出的？

　　答：你在中国的时间较长，我知道你的汉语说得很好。我想告诉你中国有个成语叫“舍本逐末”。我认为，你们对一些细节问题的关心和探讨，恰恰说明你们对大局问题的忽视。我刚才已再三表明，中方重视中日关系。但另一方面，我们也不得不非常遗憾地、非常不满地表达这种心情：日本领导人在吴仪副总理访问期间，接二连三地发表不利于中日关系发展的言论，使领导人间的会晤缺少合适的气氛。我们希望日本领导人能够认真地考虑深受日本军国主义之害的受害国人民的感受，能够真正地反省历史。

　　问：日本有些媒体报道，日本自民党干事长武部5月21日会见中央对外联络部负责人时表示，有人提出，中国关于日本靖国神社的批评是“干涉内政”，你承认报道内容吗？你昨晚说的“不利于改善中日关系的言论”是否包括武部的有关言论？

　　答：我没有看到关于这次会晤的情况，因此对你所引文字的准确性，我现在不发表意见。但我曾经听到过类似说法。我本来以为，在日本战后一再重申要走和平道路的今天，不会重现这种言论。然而，事实确实令人感到十分意外。发表这些言论的人，他们有没有想一想，当年日本军国主义是如何在亚洲邻国特别是在中国进行烧杀劫掠的？！他们有没有想过，在日本军国主义的铁蹄、军刀和子弹下，有多少人死亡、有多少家庭破碎？！我对上述言论感到非常愤慨。

　　问：现在，日本很多领导人对取消会谈表示“强烈”不满，很多人觉得中日关系更趋恶化。你认为这次取消会谈将对中日关系产生什么影响？

　　答：也许有些人对这次事件会感到所谓的“不满”，这些人是否考虑到了中国广大人民作为受害者，在创伤还没有痊愈时的感情？从另一角度说，我也想提醒你注意，现在日本各界有相当多的有识之士对中日关系的现状和造成这种现状的原因深感忧虑。人们问，为什么日本领导人不能真正地正视历史，对历史负责？我认为，在这些问题上，我们还是要遵照两国几代领导人、包括两国人民经过几代人的努力达成的共识。中日交往长达2000多年，其中发生不幸的历史是短暂的。但是，我们没有权利忘掉这段历史。只有正视这段历史，承担历史责任，才能真正地“以史为鉴、面向未来”，使中日两国一衣带水的友好关系在健康发展基础上继续发展下去。

　　问：是否因为今年是抗日战争胜利60周年所以今年中方对小泉首相关于靖国神社的言论提出了比以往更强烈的批评？昨天欧盟决定就停止进口两项中国纺织品进行调查，中方对此有何评论？

　　答：对历史承担责任是永恒的任务，不会因为年份而发生变化。历史上发生的事情，国际社会早有公论。




【时事点评】在东方评论员看来，孔泉的“正式表态”、可以说“清楚地厘定”了吴仪取消与小泉纯一郎见面的原因。

*** 孔泉“重复”这段简短谈话内容，其实包括了“两个看点”

我们注意到，孔泉今天所“重复”的这段简单的谈话内容，其实包括了“两个看点”：第一，北京这是在“强调”吴仪访日本身非常明确地表明、在改善中日关系的问题上，中国的“态度是无可辩驳地端正”；

之后，我们更是注意到，孔泉在讲话的中段，花了大量的篇幅，介绍了吴仪访问的“积极成果”，并特别强调“吴仪副总理这次在日本的时间虽不长，接触的日方人士之多是前所未有的”，通过这些，我们不难体会、在小泉纯一郎大放撅词的干扰下，北京仍然安排吴仪如期访问日本、这本身就达成了两项目的，一来可以利用吴仪主管经贸的副总理身份，近距离地做日本社会和日本经济界的工作，另一方面，也已经为中国“摆高姿态”打下了很好的铺垫，这中间，就包括为孔泉今天在记者会上“义正严词”地抨击日本阻碍中日关系改善、“提供了充足的子弹”。

第二，东方评论员，北京也是在“正式解释”，吴仪副总理之所以“取消最后行程”，主要原因就是因为吴仪访日期间，“日领导人连续就参拜靖国神社问题发表不利于改善中日关系的言论”，这令“中方感到十分不满”。


*** 北京在“第一时间里”“此地无银三佰两”的“意义”何在？


东方评论员认为，看了孔泉的这段话，相信大家对中国为何在第一时间里、就以一种“此地无银三佰两”的手法、去“立刻澄清”的意义“有所感悟”了，即：中国强调“取消会晤和小泉纯一郎参拜靖国神社无关”，这分明是“假话真说”、而日本官员却偏偏想将“原因”往“小泉参拜靖国神社”上面扯、这又分明是在“真话假说”。

在东方评论员看来，中日双方之所在“这种技术问题”如此用心，就在于两者之间“大有文章”。

这就如我们在昨天的点评中所说的那样，北京在第一时间里的澄清，根本就是在“话中套话”，一方面是在以“此地无银三佰两”的手法、以“否定”的方式、“刻意地强调”原因就是“靖国神社”；

*** 小泉为了抓住“国际外交惯例”这根稻草、不惜“不打自招”供出“靖国神社”

而在另一方面，北京这样“拐弯抺角”的意图，就是为了通过模糊手段、调动方方面面的“注意力”，好在稍后将造成中日关系如此不可收拾的责任、“彻底送给小泉政府”，从而去让关心中日关系的国际社会、以及日本国内所谓“知华派”和中日友好人士、特别是日本经济界的人士、能够看得更加清楚些，看看到底是谁在“无视”中日关系！

然而，首席评论员就指出，看来小泉纯一郎不仅是“只有小聪明”，更糟糕的是他身边也“没人”，反而为了抓住“国际外交惯例”这根稻草、不惜“不打自招”地自己供出“靖国神社”，以为这样就可以大事鼓噪，并集中攻击中国“没有外交礼貌”、同中国争取日本国内、特别是日本经济界的“同情”。

要知道、在“靖国神社”是否是中日关系主要障碍的问题上，在日本国内、日本右翼仍然在施展各种手段进行遮掩，直到“这一次”之前，小泉纯一郎只在公开场合、极其含糊地承认过一次，并认为“靖国神社可能是中日高层无法互访的原因”。

值得强调的是，这仅有的一次“含糊承认”，就是在去年11月份，是在“中国核潜艇去日本海域一游”之后。当时的情形大家应该还记得，北京的态度“非常模糊”，一不完全否认，答应继续调查，二则也不承认“那是中国的”；

而事情闹到最后、中国仅仅是对“潜艇的技术失误”表示了自己的“遗憾”，而事实上，小泉纯一郎则为了换得这个“遗憾”、和稍后在亚太峰会上与胡锦涛见一面，而第一次以“靖国神社可能是中日高层无法互访的原因”这句话、“含糊地承认了”“靖国神社”是中日关系的障碍（还没有明说是主要障碍）”。



*** 小泉纯一郎似乎相当自信

明白了“这一段历史”，我们就不难想像，小泉政府这次在第一时间就大方地、面对日本社会公开咬定“参拜靖国神社”是吴仪“提前回国”的主要原因，是“很不容易”的，在东方评论员看来，这也是小泉纯一郎自信能在“谁是中日关系到了72年建交之后最坏时期的责任人”之争论中、“拿到主动权”的一种表现。

显然，这一次既然小泉政府自己“主动跳了出来”、并“一再确认”“靖国神社”问题、就是造成这次“标志中日关系急剧恶化”的“取消”之根本原因，北京也自然就可以“借汤下面”、“正式表态”，从而将国际社会“非常好奇”的原因合盘端出：

结果，孔泉这一次可谓把话说得“非常坦率”，可以说是给足了小泉纯一郎“面子”，不仅正式承认“取消”的原因、“的确”就是小泉政府自己承认的“靖国神社问题”，而且，还“进一步”向方方面面表明、吴仪不见小泉、也“绝不仅仅”是“靖国神社问题”。因此，在东方评论员看来，孔泉今天的讲话中，有一段特别值得注意。


*** 值得重视的一段话

孔泉今天的讲话中，有一段特别值得注意，原文是这样的：

问：今天上午，日方一些官员表示，中方的态度缺乏一些外交上的礼仪。中国政府对此有何评价？

答：你提到的日本方面一些官员的说法，我也看到了。我的看法是，在今年全世界都在庆祝反法西斯战争胜利60周年的时候，在中国人民庆祝抗日战争胜利60周年的时候，日本领导人不顾中国人民的感受和感情，漠视中国人民作为受害者在那段令人难以忘却的历史中所遭受的日本军国主义的烧杀劫掠，无视自己多次表示的反省历史的承诺，最近接二连三地就参拜靖国神社问题发表错误的言论，难道心中没有丝毫歉疚吗？



*** 这种对日本首相“直接描绘”、并给出“定性的说法”、是绝无仅有的

在东方评论员看来，这段话之所以值得注意，就在于代表中国外交部“正式态度”的孔泉、面对日本外相自以为拿着这种“不常见”、但绝不是没有先例的“外交手法”、就可以“要求中国道歉”的“外交无知”，义愤地、直接将小泉纯一郎描述成一个“不顾中国人民的感受和感情，漠视中国人民作为受害者在那段令人难以忘却的历史中所遭受的日本军国主义的烧杀劫掠”的日本领导人，显然，这分明是个“冷血动物”；

同时，孔泉还将其“定性为”“无视自己多次表示的反省历史的承诺”的日本领导人，非常清楚，在孔泉的这一番具体描绘下，小泉纯一郎分明就是个“政治骗子”，在东方评论员看来，这种对日本首相“直接描绘”、并给出“定性的说法”、在中日建交之后的外交史上，是绝无仅有的。


*** 孔泉的这番对小泉纯一郎的“盖棺定论”、更加证实了我们的一个判断

在昨天的点评中，我们已经说过，北京临到最后一刻、取消了吴仪副总理与小泉纯一郎的会面，在“本质”上就已经关上了中国与“这一界日本政府”的“所有高层对话”，今天看来，孔泉的这番对小泉纯一郎的“盖棺定论”、更加证实了我们的一个判断，这就是说，中国已经不再对这个“无视自己多次表示的反省历史的承诺”的日本“变人”（日本媒体语）报任何希望。

东方评论员认为，小泉纯一郎心中“没有丝毫歉疚”是肯定的，他手下的那个外相又何尝不是如此？在我们继续点评孔泉的答记者问之前，我们先来看一段来自日本的消息。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 日外相要求中国为吴仪取消与日首相会晤道歉

【综合消息】据外电报道，日本外相町村信孝要求中国为突然取消国务院副总理吴仪和日本首相小泉纯一郎的会面道歉。

町村信孝表示,即使吴仪有紧急公务要取消会晤，是无法避免，但都应该作出道歉，他也要求中国清楚解释吴仪取消会晤和缩短访日行程回国的原因，他希望中方会遵守基本的国际外交规条和礼仪。

日本总务大臣麻生太郎也批评中方突然取消会晤，缺乏礼仪的常识，也不利中日关系。内阁官房长官细田博之就呼吁冷静处理事件，他说取消会晤是平常事，不需要要求中方详细解释。


日使馆：吴仪很不礼貌

日本驻北京大使馆官员昨天表示，中国副总理吴仪临时取消和日本首相小泉的会面，是“非常不礼貌的外交事件”，必将使陷入低潮的中日关系雪上加霜。日本官员私下认为，吴仪的举动显然是针对小泉无视中国警告坚持参拜靖国神社。

　　日本大使馆官员表示，虽然中国外交部没有说明吴仪取消和小泉会晤回国处理哪些“要紧急公务”，但以中日关系现状，临时取消和日本首相会面，是十分严重的事，定使两国气氛“很不愉快”。




【时事点评】通过这段文字，我们再次看到了日本外相町村信孝“要求中国道歉”的画面。显然，“要求中国道歉”这几个字，也让我们很自然地想起了4月17日他访华时的情境。

*** 町村信孝的“两次要求”之间，本就是个因果关系

在东方评论员看来，町村信孝的“这次要求”与“上次要求”之间，事实上，本来就是个因果关系：我们知道，就在中国摆出“不再单方面”顾及中日关系何去何从的姿态、令日本外相以“要求中国道歉”的“高姿态”访华，最后却什么都没有得到，反遭中国外长的“言行”奚落、并以“低姿态”离京、且小泉纯一郎被迫在国际社会面前公开道歉之后，副总理吴仪才决定赴日本展开访问的。

*** 中国借吴仪访问日以示中国重视、并愿意就改善中日关系的努力“是非常有必要的”

在东方评论员看来，中日关系对地区以至全球的繁荣、稳定都是非常重要的，和台海问题一样，国际社会也极其关注中日关系的走向。因此，我们认为，中国借吴仪访问日本以表示中国重视、并愿意就改善中日关系做出自己的努力“是非常有必要的”。


*** 北京已经成功地让部分日本媒体和国际社会接受了这一事实

首席评论员指出，也正是通过吴仪访日的本身，以及她在“7天”内所做的“大量工作”，北京已经成功地让部分日本媒体和国际社会接受了这一事实，即，中国对改善中日关系已经做了自己“可以做”的事情。

而反观小泉纯一郎，则明显违背了他见胡锦涛时、在雅加达“达成的共识”，也暴露了他在亚非峰会上道歉的“投机性”、也根本就是在“践踏自己已经做出的承诺”，由此可见，由于小泉纯一郎自食其言，并抛出了“靖国神社不容外国干涉”的“内政说”，因此，中国取消“这次见面”的问题上，谁是谁非，可谓说是自有公论。

我们注意到，日本媒体十分关注中国副总理吴仪19日出席日本爱知世界博览会，也认为这体现了日中交流的重要性。其中，《日本经济新闻》在报道就认为，“吴仪是上海世博会的总负责人。从她的世博外交中，可以领会到中国政府寻找修复日中关系突破口的诚意”。

*** 武部勤嘴里说的“有人”，就是在“警告”中国

在我们看来，小泉纯一郎将靖国神社问题内政化，不仅是对中国的严重挑畔、也是对人类正义和良知的严重挑衅。有消息说，就在吴仪在日本访日进入第7天的时候，日本自民党的武部勤干事长日前在北京与中联部部长王家瑞会谈时，针对中方批评日相小泉参拜靖国神社一事表示：“也有人认为这是干涉内政”。

显然，武部勤嘴里说的“有人”，就是在“警告”中国、意思是日本国内“有这么一股立场坚定的势力”认为靖国神社是日本的内政。在东方评论员看来，武部勤是日本自民党的干事长，在他来北京之前，自然与自民党的党魁小泉纯一郎商量过“如何如何、这般这般”，再加上小泉纯一郎之前已经公开抛出了这一观点，显然，武部勤在北京“重复强调”小泉纯一郎的“干涉内政”说，可以说有两层目的：第一，这是在向中国“示强”。

对日本拿着靖国神社问题到北京来示强，中国当然会断然反击。据说，先期与武部勤举行会谈的中联部部长王家瑞，就立刻对这一说法进行了“态度强硬的反驳”，并指出这是在“把（Ａ级战犯合祀）国际上已有定论的事情划入内政干涉范围内”。


*** 警惕日本在尝试将靖国神社问题与台湾问题之间划等号、“全面挂钩”。

然而，在首席评论员看来，日本的第二个目的更为重要，简值就是在“居心叵测”。我们的判断是，日本这种将“靖国神社问题内政化”的做法，显然是在做一种尝试、企图将靖国神社问题与台湾问题之间划等号、将“两种性质全面不同”的问题“全面挂钩”。

显然，小泉纯一郎这是在想利用中美之间在台湾问题上、以及全球战略上的对立，公开为自己牟取私利的“典型心理”


*** 以过种“尝试”和“企图心”，北京必须动用一切手段进行打击

因此，在东方评论员看来，对日本这种将靖国神社问题与台湾问题“全面挂钩”的任何尝试，中国都必须动用一切手段进行打击，不能给它以任何侥幸的心理，否则，极易造成“尾大不掉”的后果。

在东方评论员认为，今天孔泉态度鲜明地对小泉纯一郎进行了一番“盖棺定论”、以及之前吴仪取消与小泉纯一郎的会面，“本质”上就是对这一企图心“系列打击政策”的开始。

*** 北京可以“以其之道还治于其人”

我们认为，既然小泉政府有意尝试将“靖国神社问题”与“台湾问题”挂钩，那么，北京方面自然也会在“靖国神社问题”“挂在”一个更加显著的地方、以达到“以其之道还治于其人”的效果。

请大家注意孔泉讲的这一段文字：原文是，中日政治关系当前面临困难最主要的问题就是靖国神社问题，实际上这不仅仅是中国人民关注的问题，也是亚洲人民、国际社会关注的问题。日本是不是真正要走和平发展的道路？人们有理由担心，在世界反法西斯胜利60周年这样富有历史纪念意义的时候，日本领导人可以无视国际社会的呼声，无视受害国家人民的感情，一而再、再而三地在这个问题上发表极端错误的表态，使人们难免对这个问题感到非常担心。


*** 孔泉的态度显然是在强调：日本不要指望拿“台湾问题”去换“靖国神社”

显然，孔泉这是在对“靖国神社问题”“深挖”、“猛打”。在东方评论员看来，孔泉的这段话可以说突出了三点：第一，再次强调“靖国神社问题”是中日政治关系当前面临困难最主要的问题，不难看出，在什么是“双方关系”首要问题的定义上，这与“台湾问题”在中美关系中的“首要地位”截然不同，这就是说，在北京的眼里，在台湾问题上，日本只是“协从”，不是“主谋”。在东方评论员看来，中国的这一态度显然是在强调：日本不要指望拿“台湾问题”去换“靖国神社”。


*** 小泉的“靖国神社内政说”、已经为中国提供了一个“非常醒目的标靶”

第二，小泉纯一郎不是在那里一而再、再而三地“特意提醒”：“希望亚洲国家不要干涉（参拜靖国神社）问题吗？”在东方评论员看来，孔泉在这里也在“特意提醒”方方面面：“靖国神社”不仅不是不能干涉的内政问题、也不是“亚洲国家不能干涉的问题”。

东方评论员认为，孔泉的意思非常清楚，那就是，“靖国神社”问题的“本质”是“日本是不是真正要走和平发展的道路”的标志，这就是说，中国这是在“放风”，警告日本，北京不排除在“必要”的时候、将其视作“日本是否决定走军国主义老路”的标志，并将这种“担心”继续“世界化”、并大加宣传。

在东方评论员看来，日本这种将“国际上已有定论的'法西斯Ａ级战犯合祀'的事情划入内政、不容干涉”的问题，已经为中国提供了一个“非常醒目的标靶”。


*** “中国人民抗日战争胜利60周年”的纪念活动，已经是中国手中的一张“政治牌”

第三，东方评论员注意到，孔泉在今天的讲话中一再提及“两个历史纪念意义”，一个是“世界反法西斯胜利60周年”、再一个是“中国人民抗日战争胜利60周年”，显然，在我们看来，中国如何进行“中国人民抗日战争胜利60周年”的纪念活动，不论是规模、还是形式、都已经是中国手中的一张“政治牌”。

在我们看来，北京如何运用这张牌，取决于今后几个月小泉纯一郎在“参拜靖国神社”的问题上、其立场是否有根本性的“转变”，不然，北京很可能围绕“中国人民抗日战争胜利60周年”的纪念活动，在形式、规模、内容上做文章之外，还可以“放风”或者“正式出台”一些足以让日本政府“看得见，却摸不着”的、足以影响日本全球经济布局的“经济手段”，并以此去促进日本社会的反思。


*** 对日本保持强大的外部压力是“极其关键”的

东方评论员认为，不论中国如何做都是“外因”，对日本保持强大的外部压力是“极其关键”的。但是，在我们看来，日本是个“问题国家”，因此，只有保持住这种强大的外部压力，才能去“有效地触动”日本整体社会的“内在因素”。当然，我们认为，要想从根本上打击日本右翼的气焰，借助日本内内部不同政见力量也是非常必要的。只是，在我们看来，有必要认识到这第一点，那就是，在对日政策上，在我们重视“内因”的同时，要格外重视“外因”的主导作用。

事实上，在“内外结合”这一点上，我们也能从孔泉的讲话中找到线索，请大家注意这一段，原文是这样的：

问：现在，日本很多领导人对取消会谈表示“强烈”不满，很多人觉得中日关系更趋恶化。你认为这次取消会谈将对中日关系产生什么影响？

答：也许有些人对这次事件会感到所谓的“不满”，这些人是否考虑到了中国广大人民作为受害者，在创伤还没有痊愈时的感情？从另一角度说，我也想提醒你注意，现在日本各界有相当多的有识之士对中日关系的现状和造成这种现状的原因深感忧虑。人们问，为什么日本领导人不能真正地正视历史，对历史负责？


*** 北京的对日政策，有着“内外兼修”的鲜明特性

东方评论员认为，孔泉所说的“日本各界有相当多的有识之士对中日关系的现状和造成这种现状的原因深感忧虑”，是符合事实的，另外，我们还注意到，与日本外相的强硬、要求中国道歉的态度显著不同的是，日本官防长官的说法就非常有弹性，并认为“因国内有急务”而“取消”预定的会面、是可以理解的。

因此，在我们看来，日本政府各层、日本社会在“靖国神社问题”上，在如何处理中日、中美关系的问题上，也非铁板一块，东方评论员认为，如何尽量争取这部分有识之士、并尽最大努力去孤立日本右翼，正是吴仪顶着小泉纯一郎狂抛“靖国神社内政说”也要去日本访问的重要原因。

不难看出，中国对小泉政府的第一波打击、就是建立在吴仪出访日本的基础上的，而且，给小泉纯一郎的第一记耳光，恰恰就出自吴仪之手。由此显见，北京的对日政策，有着“内外兼修”的鲜明特性，在东方评论员看来，到今天为止，在中国决策层的头脑中，一个长远、整体的、结合有东亚、中东安全局势的对日政策、“应该已经悄然成形”。

在我们看来，中美间在台湾问题上的“暂时共识”，只不过是解决了包括朝核问题、日本定位问题等整个东亚问题的一小部分。显然，“日本的定位”问题是北京现在着手解决的另一部分。东方评论员手上，有一则来自华盛顿的消息，我们觉得有点意思，在一起了解了全部内容之后，我们将进入朝核问题的点评，在相关的讨论中，时事评论员将结合着朝核问题，谈谈我们对中日关系的另一个观点。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
