# -*- org -*-

# Time-stamp: <2011-08-02 21:31:51 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

#+STARTUP: indent

*  2005年5月10日 星期二

** 陈水扁炮轰李登辉:别把我当儿子?

【台湾消息】据东森新闻报报导，台湾总统陈水扁5月9日晚上在三立电视台的一个半小时录影专访中，再度抨击李登辉最近对他这个现任总统的批评是「情何以堪」。主持人在问到李登辉批评陈水扁与宋楚瑜的扁宋10点共识是「抓鬼而被鬼抓」，陈水扁说，扁李关系5年多来，「他没变，而是李登辉一直变来变去」。

陈水扁说，「李前总统2000年卸任时曾对我说，国统纲领不能废，中华民国宪法不能废，两支柱子不能动，对他的指点，我只有感谢，美国的三不加李登辉的两不，才有四不一没有」。

他说，「所以是李登辉没有走李登辉总统的路线，是他改变，不是我改变，是他忘了他对我的交代」。「他提议扁宋会是好意，我当时觉得还合理可以接受，他说台联他负责摆平，现在变成这样，我想不懂」。

「我既然要走和解，就一定要走下去，不像他变来变去」。陈水扁说，「他说过，总统只能有一个，我很尊敬他，但我觉得很痛苦，我真的很为难，摧毁总统领导人格，受害的是二千三百万人，前任的总统不断批评现任总统，叫我情何以堪」。

陈水扁说，「虽然说我像他的儿子，不过不是说把我当成他的儿子，就算是父亲批评儿子，也要有分寸，要拿捏一下」。

至于制宪正名的问题，陈水扁亦在专访中进一步说明为何会说「制宪正名在他任期内也做不到」，他强调只是谈一个客观的事实，并非主观的态度。

陈水扁说，「我一直对李前总统很敬重，但是他最近的谈话很奇怪，过去他执政十二年，掌握大半数的力量，如果他真有心要推动宪改，条件那么好，是绝对很简单的，但是为何他不做」？

他说，「我做不到正名制宪，我是有心，但客观我没有过半数，没有力量，还说我骗选票？我从未说我不正名制宪，但是剩下三年任期内，因为去年立委选举没有过半数，更不要说要有四分之三的多数，条件既然还没成熟，我只是老实说，时间上不可能，确实无法完成」。

陈水扁以非常直接而露骨的语气谈他与李登辉所谓的「台湾国父」与「台湾之子」的关系。陈水扁的谈话是在「劝告」李登辉如何扮演好一位卸任总统角色，为未来扁李关系的发展，以及泛绿未来分合的走向投下强烈的震撼弹，扁的谈话也将可能使民进党与台联的关系会出现风暴。

针对外界质疑他近来在两岸的一些作为是想获得诺贝尔和平奖，陈水扁8日晚间表示，他只是一个平凡的总统，他做总统只有三个字，保台湾，不要让台湾成为中华人民共和国的特别行政区或地方政府，他「不可能做一个伟大的总统」，所以不可能拿什么两岸和平奖。

陈水扁说，像这种背景的人，做了总统，还做了两任总统就已经很好了，从没有想到拿这种奖，他是非常平凡，也是平凡总统，不可能拿什么奖。

陈水扁还说，大家不要小看他，不要拿他念书的事来评比这些事，他要念好书，是因为他的手不能拿重物，一定要拿笔，才能替家人还债，才能出人头地。他不会想做台湾之父，只想做台湾之子。

中国时报报导说，关于朝野的对抗与和解，阿扁呼吁大家要有耐心，「解决事情没有那么简单的。」扁宋会的时候，宋楚瑜表示过，许多具有争议的案件，希望等他从中国回来之后再处理。阿扁表示，愿意相信他。因此，希望大家拭目以待，看看宋主席是否信守承诺，在回国之后，协助扁政府通过包括军购案等的重大案件。

关于军购案，阿扁表示，这个案子是美国非常关心的事情，连战出发之前一周，美国特别有找过连主席，表示对军购案、以及访中行程的关切，美国也希望连战主席先向陈水扁报备再去。

关于蓝绿阵营的民调支持，阿扁表示，有些民调做参考就好了。不过，面对选举的时候，主帅如何带领士气，则非常重要。阿扁表示，你不能看民调显示这样，就说民进党就要崩盘，「怎么可以这样？」甚至后来还变成，阿扁不要改革台湾、背弃台湾主流意识，害的民进党支持者改变支持台联党，但是事实上也没有啊！「扁宋会之后，我们民调显示支持度都是第一」阿扁说，等到江丙坤回台后，民进党民调支持度才开始下滑，「就是因为怪来怪去」「选举最忌讳的就是内乱」。




【时事点评】坦率地讲，陈水扁一连几天在电视镜头前“炮轰八方”，可以说让我们看得也是“眼花缭乱”，特别是昨天晚上的这部“电视专访”，陈水扁更是继之前“炮轰”国民党主席连战、亲民党主席宋楚瑜、民进党主席苏贞昌之后的“又一力作”。

*** 我们也有幸看到了如此奇怪的一幕

东方评论员注意到，陈水扁的一句“前任的总统不断批评现任总统，叫我情何以堪”，可以说是让人“不胜唏嘘”，在我们看来，一个惯使流氓手段的政客、今天居然在电视镜头前、借这种“悲嘁不已”的方式为自己“讨个说法”，也足见陈水扁在这一轮台湾政治角力、特别是两岸角力中、已成了“困兽”。

也正是如此，让我们有幸看到了如此奇怪的一幕，那就是，陈水扁可以说是“不分蓝绿”、“不分老少”、“不分敌我”地将台湾政治各派势力、以及相应的头面人物给“轰了个遍”、骂了个够。


*** “四不一没有”的“出处”竟然是“如此这般”！


在我们看来，特别是陈水扁于昨天晚上上演的“儿子骂老子”的这一幕，可以说达到了高潮部分。

请大家注意这一段，陈水扁说，“李前总统2000年卸任时曾对我说，国统纲领不能废，中华民国宪法不能废，两支柱子不能动，对他的指点，我只有感谢，美国的三不加李登辉的两不，才有四不一没有”。

显然，陈水扁这是在自曝“台独”和“支持台独国际势力”的“老底”，说实在的，东方评论员也是第一次听到“还有这么一说”：原来“四不一没有”的“出处”竟然是“如此这般”！。


*** “台独教父”的老底，可以说就被翻了个“底儿朝天”

在我们看来，如果陈水扁所言不假，那么，李登辉这个所谓的“台独教父”的老底，可以说就被翻了个“底儿朝天”

在东方评论员看来，陈水扁所说的“是李登辉没有走李登辉总统的路线，是他改变，不是我改变，是他忘了他对我的交代”显然是“台湾之子”在有意挖苦“台湾之父”，这当然有点“情绪的宣泄”、我们也大可“一笑了之”。

只是对陈水扁所说的、“他（李登辉）提议扁宋会是好意，我当时觉得还合理可以接受，他说台联他负责摆平，现在变成这样，我想不懂”的这句话，我们认为有必要在此说几句。

*** “怨恨”李登辉出了“锼主意”、害了他陈水扁的“台独大业”


东方评论员认为，从“扁宋会”到“十点共识”，再到连宋先后登陆，陈水扁所说的“现在变成这样、我想不懂”、其真实意图、无非是在台湾社会面前“怨恨”李登辉出了“锼主意”、害了他陈水扁的“台独大业”。

然而，在我们看来，“扁宋会”是否是李登辉提议的并不重要，也暂且不谈，我们认为，重要的是“十点共识”是谁导演的、又是谁参与了，显然，陈水扁要想将这个责任也推给“他老子”、也就“太说不过去了”。

大家也许还记得，在之前的点评中，我们已经多次分析过，即“扁宋会”和“十点共识”的源头并不在台湾岛内。我们知道，宋楚瑜在去年年底的立法选举惨败之后，是立刻飞到了华盛顿，而且在那里是一住就是几十天，而这中间又发生了许多事情，这之后才有了“扁宋会”，也才了“十点共识”，为了更好地说明“这一段”，我们不妨再来看看陈水扁抖落出来的另一则消息。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 宋陈年初在美国密会？亲民党斥陈水扁放假料

【台湾消息】据报道，陈水扁八日晚在电视专访中突然爆料称，亲民党主席宋楚瑜与国台办主任陈云林今年初在美国密会，以反「公投入宪」换取赴大陆访问。正在大陆访问的宋楚瑜已否认了这一讲法。亲民党透露，是美方认为「公投入宪」就是「法理台独」，所以才希望台湾的「在野党」阻遏，根本不是大陆授意。

陈水扁八日晚在电视专访中说，宋楚瑜反对「两国论」却提「一中各表」，这是自相矛盾。而且还爆料：宋楚瑜与国台办主任陈云林今年初在美国会面，以反「公投入宪」换取赴大陆访问。身在湖南的宋楚瑜第一时间得知这个消息后非常不悦，驳斥有密会这回事，并打越洋电话给在台的秘书长秦金生，要亲民党立委全力反击。

宋楚瑜也紧急找幕僚密商对策，直到九日凌晨四点才结束，就是希望「胡宋会」之前，双方不要再出现擦枪走火的发言。此外，亲民党透露，是美方认为「公投入宪」就是「法理台独」，所以才希望台湾的「在野党」有所阻遏，根本不是大陆授意。

对于陈水扁在电视专访中对宋楚瑜大陆行的批评，随行到大陆的亲民党政策中心主任张显耀表示，希望陈水扁沉稳下来，以全民利益为念。对亲民党来说，不但「胡宋会」不会受影响，反而为亲民党厘清了「传话、授权」等流言或负担，也许客观情势「反而更有利」。

亲民党立院党团九日上午召开记者会，强烈否认宋楚瑜与陈云林会面，并对陈水扁引用错误信息指控宋楚瑜表示强烈抗议。

党团总召陈志彬表示，陈水扁所获得的情资错误，可见「国安局」与政府系统出了很大问题，一定要追究。党团干事长李永萍指陈云林离开美国后宋楚瑜才到美国，两人行程完全错开，要求彻查「国安系统」。

宋陈访美时间错开

宋楚瑜今年初是否在华府密会陈云林呢？陈水扁说情资掌握确有其事，而且「当时报纸曾报道」。最初独家披露此消息的是《联合报》记者，在二月二十五日一篇分析「扁宋会」政治角力的特稿中，提到宋楚瑜年初在美曾会晤陈云林，消息来源是「国安单位」相关人士。

此一消息，各媒体驻华府记者都不知道，陈云林于一月四日抵华府会见副国务卿阿米蒂奇讨论《反分裂国家法》的两岸议题，在十日之前回到大陆接见台湾两岸包机参访团，而宋楚瑜现身华府的时间是一月十四日，与国务院亚太事务副助卿薛瑞福见面。两人出现华府的时间没有交集，除非宋楚瑜有分身能力，否则不可能在华府见到陈云林。

亲民党文宣部主任谢公秉表示，当时媒体报道时，亲民党就已经否认这件事情，想要求媒体更正，并不是现在才否认。

扁为选情弃宋楚瑜此外，据相关人士指出，从陈水扁的谈话中可以看出，他为了「国代」选举要巩固民进党基本盘，不得不拋弃宋楚瑜，微调向民进党基本教义派「温情」喊话。　

但该人士也认为，陈水扁对两岸的基调应是维持基本教义派立场，对岛内政党采取「和解」态度，但和解的进度，整个情势要等到「国代」选举结束，政党版图位移确定后，情势才会明朗。


【时事点评】这一段新闻，其实是陈水扁八日晚在电视专访中、在大骂宋楚瑜的过程中“突然爆料”的。事实上，如果您一直在关注《东方时事解读》的话，也许会有印象，那就是、在过去的几个月中，我们曾经不下三次谈及“宋楚瑜年初在美曾会晤陈云林”的事情。

*** 最重要的“真相”倒不是“有无会晤”

根据我们掌握的资料，宋楚瑜也正是在华盛顿“闲居”的过程中透露“有意登陆大陆”的，不过，既然正在大陆访问的宋楚瑜已公开否认了“会晤”这一讲法，那么，我们在此也无意继续去探究“会晤”是否真有其事，因为在东方评论员看来，最重要的“真相”倒不是“有无会晤”，而是宋楚瑜“是否”果真是曾以反“公投入宪”为条件、去换取赴大陆访问“门票”。

*** 宋楚瑜根本就用不着“那样做”

首先，当时的宋楚瑜还在“想着法儿”“补救败局”，也就是在这种情况下，“登陆构想”才开始弥漫于媒体的“字里行间”。我们知道，近年来，大陆的对台政策一直就有一种延续性，那就是“只要承认一个中国、承认九二共识，两岸是什么都可以谈、台湾不论是什么人、什么政党都可以到大陆来谈”。

显然，在这种“开放性”的条件下，当时处于绝境之中的宋楚瑜、如果“有决心登陆”，就意味着不再顾忌被“抺红”。而以他向来的“统独立场”而言，那么，他承认“一个中国”这个大陆“最看重的大前提”是没有任何问题的，因此根本就用不着另外去拿“反'公投入宪'”这一条件、去换取赴大陆访问的机会。


*** 宋楚瑜也根本就不可能“那样做”

而另一方面，如果宋楚瑜害怕“被抺红”，而仅想以“反'公投入宪'”这个“不是条件的条件”、做为自己“打大陆牌”的“登陆计划”“敲门砖”，恐怕根本就行不通。

在东方评论员看来，不要忘记了，当时，陈云林是为了什么去的华盛顿？不就是为了“透露”正在草拟中的“反分裂国家法”的、将用“非和平方式”解决“台独”的“立法宗旨”吗？

东方评论员认为，尽管当时“反分裂国家法”还没有正式通过与生效，但却有一个硬得响当当的、且对“台独”和支持台独的国际势力、实际上已经发挥着威慑作用的“517声明”在那里摆着。

何况，事实上华盛顿正是在北京“放风”将启动“反分裂法”进程之后，被迫在台湾立法委员选举前几天，开始为“台独”降温、以避免“台独进程”撞上了“反分裂国家法”枪口的。

*** 大陆没必要“借重”宋楚瑜的反“公投入宪”的承诺

显然，大陆在阻止“公投入宪”这种“法理台独”时、有拟定中的“反分裂国家法”这种“法理手段”，而阻止“台独”势力狗急跳墙，也有“517声明”这种“最后通谍”在发挥效用，在这种“强硬手段充足”的情况下，大陆有必要“因要借重”宋楚瑜的反“公投入宪”的承诺、去阻止“公投入宪”、而食言放弃“一中前提”吗？

要知道，放弃“一中前提”就意味着“反分裂国家法”没有了立法基础，也意味着自我废除“517最后通谍”的“武功”，从而让国际社会和台独势力“接收一种错误信息”，因此，在东方评论员看来，陈水扁所揭露的、宋楚瑜以反“公投入宪”为条件、去换取赴大陆访问的“门票”的说法，恐怕没有多少说服力。


*** 经陈水扁“这么一闹”，华盛顿在“扁宋会”和“十点共识”之中的身影是“更加清晰”


相反，东方评论员注意到，对陈水扁的昨晚“突然袭击”，亲民党在今天也急忙“透露”说，是美方认为“公投入宪”就是“法理台独”，所以才希望台湾的“在野党”有所阻遏，根本不是大陆授意。在我们看来，亲民党的“透露”显然“更加贴近事理”。

时事评论员认为，通过陈水扁与宋楚瑜之间“这么一闹”，虽然许多事情仍然是“公婆互骂”、“扑嗍迷离”、但是，华盛顿在“扁宋会”和“十点共识”之中的身影、却是“更加清晰”。


*** 不妨来仔细清点一下陈水扁“炮轰”下的“受伤者名单”

就如我们之前所多次强调的那样，正是宋楚瑜被华盛顿、陈水扁安排的“扁宋会”、特别是“十点共识”中的“宪法一中”套牢之后，失去了承认“一个中国”、“九二共识”的主动权，才造成他今天不得不踏着“连战的脚印”，跟着连战去承认“九二共识”、也就是在这种基础上，宋楚瑜才得以“重拾机会”实践他率先提出的“登陆计划”的。

东方评论员想强调的是，在我们“观赏”陈水扁连续两天的“全方位扫射”的过程中，第一感受就是“其行为举止”“太不合情理”，然而，如果我们结合眼下的形势，却又不难看到其“内在的逻辑性”。

首先，我们不妨来仔细清点一下陈水扁“炮轰”下的“受伤者名单”：其中有中国国民党的连战、有亲民党的宋楚瑜、还有民进党的苏贞昌、最后就是代表台联党的李登辉，可以说台湾岛内有头有脸的政治人物是一网打尽，另外，我们还能看到华盛顿似乎也被“波及”。

*** 陈水扁何以对布什“哪壶不开提哪壶”？

在东方评论员看来，在陈水扁8、9两日的“炮轰”中，有两个地方涉及到了美国人，第一，是陈水扁在解读“四不一没有”的由来时，提及“美国的三不加李登辉的两不，才有四不一没有”；第二，就是那个让布什朝思暮想的“军购案”了。

事实上，陈水扁将“美国的三不”解读成“四不一没有”的基石中的一部分，实际上是在“为华盛顿脸上贴金”，只是陈水扁为了“通过轰击宋楚瑜”、达到警告宋楚瑜“不要乱说话”的目的，竟然用上了“美国人最上心的军购案”这颗炮弹，这一点有点让我们惊讶；坦率地讲，表面上看，这根本就是在对布什“哪壶不开提哪壶”。

*** “拉着华盛顿这面大旗”做“虎皮”，警告宋楚瑜

然而，在东方评论员看来，事情到了这一步，可以说陈水扁在这一出“儿子骂老子”的政治秀中、是连带“他台湾的老子”、“美国的干爹”是一块给骂了，只是我们认为，陈水扁的这场“连续两晚的叫骂”、以及对布什“哪壶不开提哪壶”的行为，显然是其精心谋划的一着棋。

我们认为，陈水扁象这样“打华盛顿的旗号”、其意图主要在于两上方面：一是在替华盛顿在向北京隔空“叫牌”，意即是“军购案”、也就是“武力抗统”是华盛顿的既定政策，也是两岸关系、中美关系中“绕不过去的坎”，二则是在冲着宋楚瑜这位“向来东风吹来西边倒”的“政客”、“拉着”华盛顿事实上仍然在支持着台独的“这面大旗”做“虎皮”、警告宋楚瑜在北京“要小心不要乱讲话”。

首席评论员指出，如果陈水扁所言不虚，那么，不论是已经回到台湾的连战、还是正在大陆的宋楚瑜，都得面对一个问题，那就是如何对待“华盛顿是心仪已久、而北京则深恶痛绝的军购案”，

我们注意到，在台湾朝野的“对抗与和解”的问题上，陈水扁在电视中多次“呼吁大家要有耐心”，并咬定“解决事情没有那么简单的。”还“盘点”说，“扁宋会”的时候，宋楚瑜表示过，许多具有争议的案件，希望等他从中国回来之后再处理。

而关于“军购案”，陈水扁也表示，“这个案子是美国非常关心的事情”，“连战出发之前一周，美国特别有找过连主席，表示对军购案、以及访中行程的关切，美国也希望连战主席先向陈水扁报备再去”。


*** 华盛顿的“这种希望”可以提炼成“两点”

到此为止，可以说我们在之前《东方时事解读》中的、有关连战“何以首先登陆”的点评都一一找到了“直接证据”，显然，在北京不让当时“完全沦为”陈水扁特使、欲揣着“十点共识”的宋楚瑜“率先登陆”之后，迫于朝核、伊核两大紧迫问题的“紧急性”，急于“营造两岸和平景象”的华盛顿、在被迫点头让连战“率先登陆”的同时，显然也对连战“提出了希望”。

在东方评论员看来，华盛顿的“这种希望”可以提炼成两点：第一，是为了民进党政府与大陆的“和谈”“铺路”，第二，也是为了“军购案”“加油”。

我们认为，可以肯定的是，没有答应“这两条”，华盛顿是不会放连战登陆的、也不可能让宋楚瑜随后而动。

*** 华盛顿安排“扁宋会”和“十点共识”的险恶用心

在我们看来，美国“营造一个两岸和平景象”的真实目的，只是为了让“两岸坐下来谈”，谈出一个“和平协定”、或者一个“两岸三通的谈判进程”，而不是大陆所要的“实质性的两岸三通”。因此，要达此目的，就得靠“仍然不肯放弃台独党纲”的民进党政府、在利用台湾“在野党”登陆、打开“两岸缓和”的局面后、再一面出来“摘两岸缓和”的桃子，一面却去尽可能地阻碍“两岸实质性三通”。

从而在今后的时间里，可以让美国有充足的空间与时间、继续去通过“军售”、整合“美日台”军等方式、大幅提高台湾“军事抗统”的能力、并通过这些“实质性支持台独”的动作、一面享受“两岸和平”的“安全成果”，一面继续为日后打“非和平台独牌”做扎实的准备工作。

*** 早前，“老子教训儿子”、是在那里“唱双簧”

在华盛顿的这种“对台政策”中，我们不难发觉华盛顿安排“扁宋会”和“十点共识”的险恶用心，首席评论员就指出，正是有了“这么一层”，李登辉才会在一开始对陈水扁提议“扁宋会”是“好意”，至于他最后骂陈水扁在“十点共识”上是“捉鬼反被鬼捉了去”，在东方评论员看来，那时候，是李登辉骂陈水扁、是“老子教训儿子”、但根本就是在那里和陈水扁“唱双簧”。

搞清楚了这些，我们也就不难体味到北京在宋楚瑜退步到以“宪法一中”为基础、内容可以任意解读的“十点共识”后、断然拒绝其登陆的真正用心之所在。

*** 大陆将“这局牌”的顺序“给硬性的调整了一番”

对这些，陈水扁不可能不懂，只是事到如今，大陆显然没有按华盛顿的套路出牌，反而一面利用华盛顿急于稳定台海、继而稳定东亚的战略需要，将这局牌的顺序“给硬性的调整了一番”，将在台湾“几乎无牌可打的”连战和国民党先行请到大陆来，并将所有的台湾社会眼前看得到的、最关心的大礼包，一并全部拿了出来，“成功地换取了”陈水扁、宋楚瑜准备用来和大陆在“十点共识”与“胡四点”间讨价还价的最大筹码--“九二共识”，“一中原则”。


*** 今天上演的这出“儿子骂老子”，在我们看来，是在真骂！

东方评论员认为，就事实来看，大陆这次颠倒台湾在野党的“登陆顺序”之举，可以说取得了巨大成功，首先，连战在端出“九二共识”的那一刻起，事实上就彻底打乱了华盛顿、陈水扁的全盘计划。

从而，李登辉所认为的“好主意”也就这样在陈水扁的“不懂”之中、变成了一个“馊主意”，是个“馊得”让陈水扁“情何以堪”的“馊主意”，因此，今天上演的这出“儿子骂老子”，在我们看来，是在真骂！


这表现在华盛顿、陈水扁在同北京“玩这局牌”时、事先设计的、用来打开“两岸僵局”的最关键的一张牌--宋楚瑜，在连战的光芒下、立刻就显得“作用全失”。对华盛顿和陈水扁而言，最糟糕的是，是宋楚瑜的“投机心理”依然，也正是在这种投机心理的驱动下，华盛顿手中的“这张牌”、在失去先机之后、在目睹了连战的大陆之行取得了意想不到的民意支持之后，仍然坚持“要飞到大陆”。


*** 从北京给宋楚瑜“下马威”的手法和时间上来看，显然是有精心准备的


而大陆也瞄紧宋楚瑜的“鱼和熊掌”都欲得的投机心理，待他一到大陆、立刻就抓住他大谈“中华民国”这一点，一分钟都没有耽搁就开始了“大做文章”，在媒体报道的安排上立刻来了个“下马威”，之后，还由国台办副主任孙亚夫亲自出面警告：宋楚瑜在大陆谈“中华民国”不恰当。

在东方评论员看来，从北京给宋楚瑜“下马威”的手法和时间上来看，显然是有精心准备的。


*** 国台办副主任孙亚夫亲自出面“警告”，为“搭桥之旅”“正式地钉上了棺钉”


首席评论员指出，在这后几天的活动中，我们已经清楚地观察到宋楚瑜的“尴尬”、但是，令我们印象深刻的是宋楚瑜的另一种特点、那就是“投机”。显然，国台办副主任孙亚夫亲自出面警告，事实上已经为宋楚瑜事先标榜的、欲在“胡四点”与“十点区识”之间牵线搭桥的“搭桥之旅”给“正式地钉上了棺钉”。


*** 对华盛顿而言，事先安排的“这张牌”已经没有多大的战略意义了

因此，在我们看来，不论是华盛顿、陈水扁、还是这个“善变”、擅长权谋的宋楚瑜，在宋楚瑜相信“就是第二个登陆”、凭借其“十点共识”的“官方色彩”、“美国色彩”“也能确保丰收”的心态驱使下、从其登陆的那一刻起，事实上就已经被北京装进了“口袋”。

东方评论员认为，只要宋楚瑜的“投机心理”不改，那么，他就一定会想尽各种办法、在稍后的“胡宋会”中取得突破、去超越连战已经取得的成就，这样一来，华盛顿事先安排的这张牌、在大陆给”搭桥之旅”“正式钉上棺钉”之后，已经没有多大的战略意义了。


*** 北京逼迫宋楚瑜“更改旗号”、宋楚瑜悄然地已经转手成了北京手上的“一张牌”

在我们看来，在进北京前、在“天上地下”围着北京“转圈”的过程中、被迫扔掉“搭桥之旅”大旗的宋楚瑜、最终是扛着“工作之旅”的旗帜进北京的。

显然，在北京逼迫宋楚瑜更改旗号、将行程换成“工作之旅”之后，它却悄然地已经转手成了北京手上的“一张牌”，只是这张牌威力的“大与小”，则在于宋楚瑜最终将做何选择，是同连战一样、将希望全部寄托在台湾“和平民意”的基础上，还是象“扁宋会”时那样，将宝押在华盛顿身上、押在华盛顿操纵“台独进程”的能力上、押在美国将来可以摆脱战略被动的基础上。


*** 种种迹象表明，他还没有拿定主意

就在我们讨论的时候，宋楚瑜的包机已经到了北京机场。在东方评论员看来，宋楚瑜的神情无疑是沉重的，这与“豁出去了的”连战当时的表情、形成了极大的反差。显然，种种迹象表明，我们的感觉是，他还没有拿定主意，毕竟现在离他见到胡锦涛主席还有点时间。

有消息说，就在到达北京之前，宋楚瑜主动地在飞机上向媒体发表了讲话，表达了对陈水扁昨天晚上的“爆料”的不满。从宋楚瑜讲话的大概内容来看，宋楚瑜仍然在保持低调地、尚未与陈水扁翻脸。

在东方评论员看来，在等待见胡锦涛的这段时间里，宋楚瑜最后将“如何定性”陈水扁的攻击，将在很大程度上预示他在“胡宋会”中能走多远，也将预示“扁宋会”是否破裂，还将预示着陈水扁“还要多长时间”才肯接受“九二共识”。

*** 陈水扁事实上已经给自己的“两岸政策”留了条“后路”

然而，对这个问题我们有种感觉，而这种感觉来源于上面所列出的那份遭陈水扁轰击的名单位。在这里，我们不妨再去看看那份陈水扁“炮轰”之后的“受伤者名单”，其中，有他的政治死敌、中国国民党和连战、有他的“露水政治夫妻”--亲民党和宋楚瑜、还有他的“家人”---民进党和苏贞昌、最后就是“他的老子”---代表台联党的李登辉，然而，却偏偏没有海峡对岸的、这些天来逼得他陈水扁“情何以堪”的中国共产党的总书记胡锦涛。

怎么说呢？不论陈水扁是不敢轰击、还是觉得没有必要轰击，事实上这都让东方评论员有种联想，那就是，不论是“有意还是无心”，陈水扁事实上都给自己的“两岸政策”留了条“后路”，至于陈水扁什么时候才肯走上这条“后路”，恐怕在很大程度上、要视宋楚瑜在“胡宋会”中能走多远而定。

现在，宋楚瑜在北京机场上的讲话稿已经被资料员整理出来了，在我们一起熟悉其中的内容之后，东方评论员将继续讨论宋楚瑜的“工作之旅”。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
