# -*- org -*-

# Time-stamp: <2011-08-03 23:03:14 Wednesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:3

#+STARTUP: indent

#+STYLE: <link rel="stylesheet" type="text/css" href="css/org.css" />

*  2005年6月02日 星期四

** 中国外交部发言人：安理会改革应遵循四原则

【北京消息】中国外交部发言人孔泉今天在此间例行记者会上表示，对于安理会改革是不是应该增加常任理事国的问题，在目前情况下，中方的态度是安理会的改革应该有一些基本的原则。

孔泉说，首先，安理会改革无论采取任何方案，都应该提高安理会的工作效率；其次，安理会改革必须增加发展中国家的代表权；第三，改革应该有助于增加世界上广大中小国家参加安理会决策的机会；第四，改革应顾及地区平衡，应考虑不同文明和不同文化的情况。孔泉表示，对中方来说这些原则同等重要。

孔泉强调，安理会改革中各方都有不同的述求，关键是各方能通过充分的、民主的协商，尽可能达成最广泛的一致，寻求利益汇合点。正是本着这种精神，中国正在同联合国的所有成员国保持密切的联系，进行充分讨论和意见交换；正是从这一角度出发，我们反对强行推动或者表决任何可能破坏会员国团结、不利于改革进程的提案。

另外孔泉也提到，安理会改革只是目前正在酝酿的联合国改革的一个部分，无论是在名人小组递交的联合国改革报告中，还是安南秘书长的报告中都只是把安理会改革作为其中一个部分，而绝不是整体。所以我们对于目前联合国改革因为有关方面过于强调安理会改革，而使其他改革处于无人关注的状况表示担忧。


【时事点评】在东方评论员看来，孔泉的这番“老调重弹”，可以说是再次明确了中国在安理会改革问题上的“既有立场”，既“安理会改革无论采取任何方案，都应该提高安理会的工作效率；其次，安理会改革必须增加发展中国家的代表权；第三，改革应该有助于增加世界上广大中小国家参加安理会决策的机会；第四，改革应顾及地区平衡，应考虑不同文明和不同文化的情况”。

*** 鲍彻的嘴里也吐出了一个“四原则”

我们认为，就在中国外交部发言人孔泉再次亮出自己“四原则”的同时，美国国务院发言人鲍彻嘴里也吐出了一个“四原则”，这就是所谓的“支持日本、反对德国、同情印度，不管巴西”。


*** 北京是“好话、歹话全都有”，相关国家“是只须敬请对号入座”就可

显然，“华盛顿的霸道”、和“啀齿必报”的报复性的心态、再一次从鲍彻吐露的“四原则”中“一览无遗”，要东方评论员看来，相比较而言，北京的姿态就“显得公事公办”得多，不仅表现出一种“替天行道”般地、为广大第三世界国家“谋福祉”的责任感、也透露出了一种“在必要时”、将也不妨来一回“君子动口也动手”的强硬，真可谓是说的“滴水不漏”、好话、歹话全都有，相关国家“是只须敬请对号入座”就可，大凡都能找到自己“在北京心目中的位置”！

在东方评论员看来，比起外交部发言人孔泉在北京款款“宣读”中国政府对此问题的“指导性处理原则”而言，坐在联合国总部的中国常驻联合国代表王光亚、在接到外交部的指令之后，说起话来可是“一点都不客气”。

下面，我们就先听听处于“火线上”的王光亚，是如何去具体贯彻北京高层发出的这番指令的。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 王光亚：中国将对四国“增常”决议草案投反对票

【纽约消息】中国常驻联合国代表王光亚１日（北京时间2日）说，由德国、日本、印度和巴西（“四国联盟）提出的要求增加安理会常任理事国的决议草案危害联合国改革进程，如四国将这一决议草案付诸表决，中国将投票反对。

王光亚当天下午参加由反对“增常”国家组成的“团结谋共识”运动举行的闭门会议后对新闻界说，

“四国联盟”提出的决议草案使联合国成员国分裂成了两个对立阵营，如果“四国联盟”下周将决议草案提交联合国大会表决，中国将投反对票。王光亚希望各方继续磋商，找到一个得到联合国成员国广泛支持的安理会扩大方案。

意大利、西班牙、墨西哥、阿尔及利亚、巴基斯坦、加拿大等十几个“团结谋共识”运动成员国代表参加了当天的会议。巴基斯坦常驻联合国副代表乔杜里会后说，这次会议是“团结谋共识”运动一次协调内部立场的例会。联合国成员国对该阵营上周向联大提交的要求增加１０个安理会非常任理事国的工作文件作出了积极反应，一些国家认为这一方案很有吸引力。

乔杜里说，中国不是“团结谋共识”运动的一员，但中国对该阵营解决安理会扩大问题的方式给予了大力支持。他还说，“团结谋共识”运动主张通过对话就安理会扩大问题达成共识，该阵营不会就此提出有关安理会扩大的决议草案。

“四国联盟”５月中旬公布了一项框架决议草案，要求增加６个安理会常任理事国和４个非常任理事国。巴西常驻联合国代表萨尔登伯格５月３１日对新华社记者说，目前已有约１２０个国家对该决议草案表示支持，其中有２０个国家有意和“四国联盟”一起成为决议草案的共同提案国。“四国联盟”将在和这２０个国家进行协商后，对决议草案进行修改，争取在６月中旬之前敲定决议草案的最终文本。此后，“四国联盟”将视情况将决议草案正式提交联大辩论。

如“四国联盟”强行表决框架决议草案，需要得到联大至少三分之二成员国的支持（即１２８张赞成票），才能确保决议草案获得通过。根据联大有关规定，美、中、俄、英、法５个现任安理会常任理事国在联大表决中没有否决权。


【时事点评】在东方评论员看来，与孔泉在北京大声宣读“四原则”相比，王光亚坐在联合国总部，可以说是“火力四射”。两相比较，孔泉在“君子动口”，而王光亚显然是在“大动其手”。

*** 将“四国联盟”提出的决议草案、定性为“危害联合国改革进程”

我们注意到，王光亚不仅威胁说“如四国将这一决议草案付诸表决，中国将投票反对”，更是将“四国联盟”提出的决议草案、定性为“危害联合国改革进程”，在我们看来，既然北京“已经强硬如此”，那么，“四国联盟”要想如愿恐怕就得“另想办法”。


*** 中国除有个“公事公办”的“四原则”外，还有个“特事特办”的“四原则”

孔泉在北京说，“中国坚持协商原则，反对强行推动或表决任何可能破坏联合国团结以及不利于改革进程的提案”、而王光亚在联合国则强调“希望各方继续磋商，找到一个得到联合国成员国广泛支持的安理会扩大方案”，显然，北京说来说去，就是一句话，即，各方“最好”还是得“继续协商下去”。

在东方评论员看来，中国除了有上面这个“公事公办”的“四原则”之外，其实还有个“特事特办”的“四原则”。众所周知，北京早已经明确表示过，支持德国“入常”、也支持印度“入常”、还支持巴西“入常”，单单没有提“反对”或“支持”日本“入常”的碴。显然，“地球人都知道”，中国是“只反对”日本“入常”。

*** 联合国“五常”也在各自斗着心思、比划着自己的利益


首席评论员指出，在“四国集团”“抱着团”要“强求”入常门票的时候，联合国“五常”显然也在各自斗着心思、比划着自己的利益。

在我们看来，鲍彻在以“美国式的霸道”阐述美国“四原则”的同时，又何尝不是在暗中“得了便宜还卖乖”？

东方评论员认为，“五常”中的任何一个、包括中国在内，说“支持谁、谁、谁入常”，说到底都不过是“违心之言”。

事实上，在我们看来，这五个瓜分有“联合国一票否决权”的“五强”，谁也不乐意与更多的人“分享自己的这份特权”，因此，如果可能的话，“中法英俄美”这“五大常任理事国”恨不得一把就将“安理会改革案”给一把掐死，然而，不行呀，国际社会要求联合国改革的“洪流太大”。

*** “五常”可以说是“配合默契”

然而，中国有句老话说得好，“治洪之道在于疏而不在于堵”，在东方评论员看来，在“如何疏通这股改革安理会的洪流”方面，“五常”可以说是“配合默契”，起码、中美这对在东亚、中东斗得昏一黑地的“老对手”，就在“各司其责”。

在我们看来，中国明言要投票反对“四国联盟”的决议案，谁都知道、北京这是将矛头集中在日本身上，就是要让世界、特别是亚洲国家知道，“我只想将日本踢出来”，而美国则明言“不支持德国”，这显然是在报复德国、因为德国在伊拉克战争与法国一起、带领欧洲、鼓动联合国成员国阻止美英从联合国拿到授权，这种报复，显然也是在明示“我美国只想把德国踢出来”。

*** “五常”的“两强”、要踢“四国”的“两强”

显然，中美这“两常”、也是五常中实力最强的两个大国、在决议案还没有最后定稿的时候，就分别声称“我一定要踢人出来”，而且各自要踢的国家、还都是“四国集团”中两个最具实力的国家，可见，“两强”要“踢两强”、“四国集团”抱团集体闯关、仍然是凶多吉少。

*** 华盛顿对日本的支持显然是有条件的，也是“五常”的共同愿望

另外，华盛顿在“变来变去”、现在“终于又重新”开始支持日本“入常”，然而，比起先前的态度，华盛顿对日本的支持显然是有条件的，即附加了一个前提条件，那就是日本“不得坚持”索要“否决权”；

在东方评论员看来，华盛顿的这一前提条件，可以说是“五常”的共同愿望。


*** 法国、英国有必要“矜持”一把

此外，法国、英国则是一再表示“有意”支持“四国提案”，但在我们看来，这种所谓的“一再表示支持”、不过是碍着德国的面子、与日本也没有过节、也想积极地在南美洲扩大影响需搞好与巴的关系的通盘考虑、而不便公开反对而已。

按照“四国联盟”公布的消息，目前已有约１２０个国家对该决议草案表示支持，而其中又有２０个国家有意和“四国联盟”一起成为决议草案的“共同提案国”。

　　我们注意到、日本外务省官员曾对外界宣称，英、法曾经向日本表示，如果条件成熟，两国有意成为“四国集团”“框架决议案”的共同提案国，而日本官员之所以“这样招摇”、就在于日本人认为“这是来自常任理事国的支持，影响不轻”。

但是，东方评论员认为，至于法、英，是否会在“四国集团”的“决议案”上签字划押、成为“共同提案国”，恐怕还有变数，道理很简单，因为美国的态度是如此地“爱憎分明、别具一格”，其“只支持日本、也只反对德国”的鲜明态度，也足以让支持德国的法国、英国有必要“矜持”一把，从而尽可能地保持“灵活的话语权”、以求在“整个、有可能长达数年的漫长过程中”撅取尽可能多的国家利益。


*** “五常”也可以尽可能地拿着手中的“否决票”、找相关国家“尽可能地套现”

在我们看来，站在五常的角度去看问题，就不难发现，如果让整个决议案“胎死腹中”、表决不通过，是最好不过的了，这将最大限度地保障“五常”今后继续把持联合国朝政大权；东方评论员认为，是否可以做到这一点，很可能取决于英法的“最终态度”。

当然，在“五常”看来，就算是“四国集团”的决议案通过了，也不是什么了不得的事情，这可能会是一个长得以十年计的过程，在这一过程中，“五常”手中的“否决票”的含金量就立刻表现出来了，“五常”也可以尽可能地拿着手中的“否决票”、找相关国家“尽可能地套现”。

事实上，自日本官员“宣称”将获得来自安理会常任理事国的“共同提案的支持”之后、时间已经过去了近半个月，只是直到目前为止，东方评论员仍然没有得到“英法两国对此予以证实”的消息、也就是说，我们仍然不清楚日本人所说的、那个愿意去“共同提案”常任理事国、到底是哪一家？

意外的是，在我们搞不清楚哪家常任理事国会“共同提案”的时候，俄罗斯突然表示，它支持日本“入常”。我们先来看看具体情况，之后，东方评论员将继续这个话题。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 俄罗斯希望以支持日本“入常”换取北方2岛主权

【东京消息】俄罗斯外长拉夫罗夫于5月31日抵达东京开始了对日本为期两天的访问，并就俄总统普京今年年底访日进行磋商。拉夫罗夫在与日本前首相森喜朗举行会谈时，表示支持日本成为联合国安理会常任理事国。据外界分析，俄罗斯此举是希望日本能放弃对北方四岛中两岛的主权要求。

　　但事与愿违，在当天下午与日本外相町村信孝长达3个多小时的会谈中，双方就俄总统普京年内访日达成一致，但北方四岛问题却未曾有丝毫进展。

　　据日本媒体报道，俄日外长会谈后，拉夫罗夫在记者招待会上就北方领土问题回答记者提问时承认，俄日双方并没有改变立场，意见相左，两国仍然存在很大隔阂。拉夫罗夫同时表示，他与日本外相的磋商主要为普京访日做准备，虽然具体日期尚未敲定，但普京将于今年访问日本已基本确定。

　　在结束对日本的访问后，拉夫罗夫前往符拉迪沃斯托克会晤中国外长李肇星、印度外长辛格。




【时事点评】在东方评论员看来，如果就此下结论说俄罗斯希望以支持日本“入常”换取北方2岛主权，恐怕有点“言之过早”，但是，俄罗斯想“借机捞一把”的心态是“非常迫切的”。

*** 俄罗斯可以对日本打的两张牌、分别是“石油管道”和“北方四岛”

我们的判断是，拉夫罗夫此番前去，其实还为了另外一件更具意义的事情，那就是向日本方面“提前通报”一下他今天与中国外长李肇星、印度外长辛格举行“中俄印”三方会谈的事情。

之前，东方评论员注意到，俄罗斯外交部发言人就意味深长地表示，按他的说法，这个“三方会谈”，既俄、印、中三方建设性对话“不针对亚洲和世界其他国家”。

然而，亚洲只有三个大国，一个是中国、再就是印度，还有一个是日本，“前面的两个”都是“三方会谈”的参加者、显然，值得俄罗斯去“此地无银三佰两”一番的亚洲国家，也就只能是剩下的日本了。

事实上，目前，俄罗斯可以对日本打的两张牌、分别是“石油管道”和“北方四岛”。而“石油管道”这张牌、其实已经被俄罗斯塞进了“中、俄、印三方会谈”之中。如此一来，这个“三方会谈”不仅谈安全、还谈能源，只是原来一度赢得与中国管道之争的日本，不仅没有能获得最后的胜利，这次竟然不在邀请之列，其尴尬之情是可想而知。


*** 小泉“斩钉截铁”说出了上面一番“硬话”

对俄罗斯而言，如果能妥善解决好与日本之间的“北方四岛问题”，并促使日本依靠一个互补的“日俄关系”、逐渐地脱离美国、并与中国保持距离，那么，这将对俄罗斯的复兴有莫大的助益。显然，这种战略构想，正是俄罗斯一度“愿意考虑”与日本讨论归还“北方四岛”的理论基础。

我们知道，就在日本在钓鱼岛、东海海域主权问题挑衅中国的同时，日本也在北方四岛的问题上冲着俄罗斯“发镖”。东方评论员注意到，小泉对“北方四岛”曾经有个明确的强硬态度，那就是：俄罗斯应当认识到如果不归还日本的“北方四岛”，那么双边关系就不可能获得正常发展。

事实上，小泉纯一郎的这番“掷地有声”的话，是2004年时说的。我们还记得，那是在2004年2月10日，是日俄战争爆发100周年纪念日，日俄双方都举行了纪念活动，日本更是将2月7日设为北方领土纪念日，意在配合要求俄罗斯交还日俄之间有争议的北方四岛，也就是在所谓的北方领土纪念日的这一天，日本首相小泉“斩钉截铁”说出了上面一番“硬话”的。


*** 短视的日本政府，再次错过了一个与中国争夺亚洲领导者的战略机会

然而，当时我们就曾经指出，短视的日本政府，终于再次错过了一个与中国争夺亚洲领导者的战略机会。

在东方评论员看来，狭窄细长的日本岛、远离欧亚大陆，并居于美、中、俄3个世界大国的势力范围之间，我们认为，日本的地理条件、和身背着二战“法西斯战败国”的历史，命中注定了日本必定要依附其中的一个大国、才能在今天这个全球化的世界上“有所作为”。

事实上，就是在冷战打得最紧张的时期，日本也始终努力地与这“三个大国”中的“两个”同时保持着友好关系，而不是象现在这样，一把就同时得罪了其中的两个。


*** 前苏联占据日本“北方四岛”不放的重要关键、是担心它对俄海上通道的战略封锁作用

众所周知：前苏联占据日本“北方四岛”不放的重要关键、是担心它对俄海上通道的战略封锁作用。在东方评论员看来，可以非常肯定地说，近一年多的事实证明，尽管俄罗斯和日本之间有如此多的战略利益“存在交集”，但是，受制于美国的日本政府、终究无法自主地制定出一套独立的外交政策、在这一点上，日本似乎已经失去了俄罗斯的信任。


*** 俄罗斯恐怕在任何时候也不会将“北方四岛”完整地归还给日本了

因此，在东方评论员看来，对日本是否有追逐自己战略利益的能力、已经抱持怀疑的俄罗斯、恐怕在任何时候也不会将“北方四岛”完整地归还给日本了，显然，俄罗斯的决策层有理由相信，在日本唯美国马首是瞻的情况下，俄罗斯如将“北方四岛”交还给日本，实际上就是交给了欲置俄罗斯于死地的美国人手中，从而让美国拿着俄罗斯交出来的北方四岛、去完全堵死俄罗斯在西太平洋的海上通道。


*** 日本人如果够聪明，至少要做到“二者之中选其一”

所以，东方评论员认为，日本人如果够聪明，就必须在钓鱼岛争端和北方四岛争端中，至少要做到“二者之中选其一”，以同时在“三个大国中”同时与两个、或者两个以上的国家、保持良好的关系。

眼下，在日本周围的“三大国”之中，不可否认的是，美国实力最强，中国次之、俄罗斯最弱，因此，在我们看来，日本只有在俄罗斯虚弱、不仅受到美国的战略挤压、也同时担心中国势力增强的时候，以灵活的方式暂时搁置“北方四岛”问题，并“以此为基础”去寻求与俄罗斯建立友好关系，通过大规模投资俄罗斯远东地区，将俄罗斯的资源与自己的资金与技术结合在一起，将包括俄罗斯远东地区、中国东北地区、朝鲜半岛在内的整个东北亚打造成一个世界经济的“新热点”。

东方评论员认为，只有这样，日本“才有可能”通过“在中美之间的来回摆动”、慢慢将自己的影响扩展到朝鲜半岛、和俄罗斯远东地区，并以此为政治、经济基础、去寻找机会以摆脱目前受到“中美”联手压制的处境。


*** 日本的这一出路，就是中国主张的东北亚“经济一体化”

不难看出，日本的这一出路，与去年7月份到8月份之间，中国在主导朝核问题进程时、用以利诱日本、韩国脱离华盛顿的朝核政策、为东北亚指出的“经济一体化”之出路、是“如出一辙”。

在东方评论员看来，只是那一次，日本政府满以为美国人挑起来的“韩国浓缩铀”事件、加上原有的朝核问题、朝鲜半岛局势最后必然会发展成东亚核竞赛，从而为日本跨入核门槛带来千载难逢之良机，结果，日本被华盛顿突然抛出的“韩国浓缩铀”、从中国主导的朝核问题进程上、给骗了回去，日本的朝核政策、再次成为美国的朝核政策的“一个补充部分”。


*** 小泉在关键时刻，再次表现出其“小聪明有余、大智慧绝无”的特性

然而，让东方评论员“一再惊奇”的是，小泉纯一郎在这一关键时刻，再一次表现出了其“小聪明有余、大智慧绝无”的特性。结果是，小泉政府的“对俄政策”、再次成为华盛顿“对俄政策”的“绝好补充”，单看美国脸色行事小泉纯一郎、不仅没有能抓住这一改善日俄关系的“难得良机”，反而“剑走偏锋”、认为俄罗斯既然是“软弱可欺”、那就干脆将这个“好时机”利用一番，结果是，通过上述的那一番“斩钉截铁”的“硬话”所确立的“对俄政策”、小泉政府逐渐地将“日俄”关系带进了今天这种“死胡同”。


*** 对日本而言，“北方四岛”问题和台湾问题一样，分明都已经是一步死棋

首席评论员指出，“北方四岛”问题和台湾问题一样，对日本而言，分明都已经是一步死棋，硬走下去，不过是美国的“最爱”。然而一年多来，小泉纯一郎自以“傍上”布什、就可以通过无视“中俄”、从而有机会、也有本钱去“左右逢源”、并将这两枚死棋一步步地走活。

因此，在我们眼里，小泉纯一郎也就敢表现得如此地“锋芒毕露”、不惜一把就得罪了“三个大国”中的两个，现如今、“四面楚歌”中的小泉纯一郎、就算是不再做什么，也足以可以让布什感到满意，何况小泉纯一郎还在一意孤行、在钓鱼岛、北方四岛的问题上一再“顽固不化”！如此一来，布什更是满意得“无以复加”的了。

东方评论员认为，一个渐行渐远的中日关系、俄日关系，既对抗又合作的中美关系，既合作又彼此心怀戒心的中俄关系、如影相随的美日关系，也就确定了中、俄、美、日等国，在一系列问题上的“悲欢离合”。

在我们看来，中、俄、美在公开表态“支持、或者不支持”日本“入常”的问题上，就能看到这种“悲欢离合”的印记。


*** 俄罗斯外长“何以赶到日本”去主动地“支持日本入常”呢？


我们认为，由于“北方四岛”问题是俄罗斯与日本间改善关系的“一道死结”，因此，俄日之间的任何进展、都必将与双方“在北方四岛上的立场变化”有关。

在东方评论员看来，对于俄罗斯外长这次公开表态“支持日本入常”，不论俄罗斯拿支持日本“入常”换取北方2岛主权的说法是否属实，我们都认为，可以肯定的是，眼下，遭到北京痛击的小泉纯一郎、在处理“北方四岛”问题上的态度，肯定较之那番“牛皮哄哄”的“硬话”有所软化，不然，在小泉纯一郎于国内、国外的处境“都非常难捱”的情况下，俄罗斯外长“怎么可能赶到日本”去主动地“支持日本入常”呢？


*** 俄罗斯手中的这张“否决权”是如此地好用！

首席评论员指出，不论小泉纯一郎是拿的何种手段、哄得普京愿意“去支持日本入常”的，总之有一点，普京的“这一声支持”，在本质上仍然只不过是“口惠”而已！

由此可见，如果小泉纯一郎“果真呑下了”他曾经就“北方四岛”问题所说的“狠话”、食言而肥的话，那么，一个“没有信用的小泉”，和一个“信用记录也不佳”的普京，两人在一起可能就会让我们看到一出好戏，在东方评论员看来，这出戏好将好在普京会用日本“入常”这件事，用手中握有的“否决权”、狠玩小泉纯一郎一把，尽可能地为俄罗斯赚取国家利益。

东方评论员认为，日本在远东石油管道、和俄罗斯远东地区投资上的“信而无信”，俄罗斯在管道走向上的“信用全无”，恐怕与今后的好戏相比，都不过是“小菜一碟”！

显然，俄罗斯手中的这张“否决权”是如此地好用，这也足以证明“四国集团”选择的这条联手入常的道路、注定“将是多么的艰难”！


*** 北京恐怕早就设计好了，如何拿“否决票”去尽可能地“套现”

东方评论员认为，联合国的“否决票”、除去俄罗斯这一家之外，还有四家，在看到俄罗斯“如此这般地撅取”国家利益的时候，其他四家恐怕也早有算盘。

别的先不说，只说中国，在东方评论员看来，北京恐怕早就设计好了，应该如何拿自己手中的这张“否决票”去尽可能地“套现”、特别是针对日本。

我们注意到，中国常驻联合国代表王光亚曾经说过这么一句，他说：“如果进展到了最后一个阶段，我相信中国的立法机构会考虑到其他人的感情。我不认为中国会在这件事情上会有非常肯定的举动。”

*** 北京第一次“清楚明白地”表示将“考虑”动用否决权

在东方评论员看来，王光亚的这句话，可以说是第一次“清楚明白地”表示出中国将不惜“考虑”动用否决权、在最后关头去敲碎日本的“常任梦”。

我们认为，在中国通过一系列手段：包括严重警告日本向日本企业发放东海勘察许可证、让“日本外相北京败北”、逼迫小泉纯一郎“公开道歉”、安排吴仪如期访日、用了7天的时间见了所有应该见的日本人、又提前召回吴仪，独独不见小泉纯一郎本人等，从而既达到了向日本右翼展示了“在历史问题、国家主权问题上绝不让步的强硬态度”、又实现了向日本社会体现出“愿意改善中日关系的真诚善意”的目的之后，北京在这个时候首次暗示“不排除动用否决权”，可以说在时机的把握上是“恰到好处”。


*** 针对日本“隆重推出”“不排除动用否决权”这一意向，北京可达成多重目的

首席评论员就指出，北京现在针对日本“隆重推出”“不排除动用否决权”这一意向，可以达成多重目的：

第一，由于小泉纯一郎在靖国神社问题上“仍然在强硬”、“仍然在暗示”今年还要去参拜，这就给了中国以小泉政府“仍然没有诚意”改善中日关系为由、为“祭出否决权”找到了100个理由。

对此，已经受到日本社会极大压力的日本右翼、小泉政府，在仍然拒绝从靖国神社问题上让步的情况下，就是想将中国“只是想”阻挠日本入常的帽子扣在北京的头上、恐怕已经失去了相当的说服力。

显然，在中国积极改善中日关系的努力已经为国际社会所“共同欣赏”的情况下、在日本政府竟然“变本加利”地为“东京审判”翻案、挑战国际社会的情况下，北京“以暗示的方式”、威胁要在“最后关头”“否决日本入常”的行为、显然是“威胁得有理”，不仅不应该视为什么报复、而应该视为是对人类良知、对亚洲国家、和国际秩序、《联合国宪章》的负责表现。

*** 北京早早地暗示“不排除动用否决权”这一意向，意在“多重警告”


第二，东方评论员认为，北京早早地暗示“不排除动用否决权”这一意向，实际上是在向日本社会施加压力、也是在有意将日本从“四国集团”中分离出来。在东方评论员看来，既然中国有意最后否决日本入常的梦想，那么，对日本而言，忙着参拜靖国神社的小泉政府、忙着为东京审判翻案的日本右翼，所搞的“这一套申请入常的形式”，充其量是在“做秀”，因此，是中止政府买票大掏银子“做无用功”的行为，还是提早在历史观上“改弦更张”、或者是现在就开始清算日本右翼政权，都是“有心入常”的日本社会现在就要着手做的事情。

另外，在我们看来，北京早早地暗示“不排除动用否决权”这一意向，也是在对“四国集团”的另外几个国家进行警告。不难看出，如果他们不能劝说日本认识法西斯历史、清算过去的罪行，那么，最保险的办法就是将日本请出去。

显然，以德国为例，尽管美国人公开反对，但是，这只是一家反对，如果继续与死不认罪的日本人为伍，起码就有两家反对，什么情况下机会更大一些，恐怕小学生都算得出来。

还有，也不要指望日本人帮德国人到美国人那里通融通融，一则日本人没有这份面子，二则德国人还有英国、法国两家撑腰，在东方评论员看来，到底是谁帮谁通融、真还不一定呢！


*** 需要再次强调的是，中国只能在“程序的最后一步”“进行否决”

在昨天的点评中，东方评论员曾经对照联合国章程、对“四国集团”决议案的通过过程做了详细的解读（详细情况见6月1日《东方时事解读》），在这里不再多说，只是需要再次强调的是，中国只能在最后一步“进行否决”；

而第一步是，如果“四国集团”决议案获得一百九十一个成员国的三分二支持，就有可能通过。

接著是第二步，选新的常任理事国、按规定，这一过程也必须获同样的三分二成员国选举出来。最后一步，是一个旨在改变联合国宪章的最后决议案，这不仅需要三分二的选票，还必须获拥有否决权的安理会五个常任理事国的批准、无一反对才行。而中国就可以在这一环节“否决”整个结果。


*** 日本“入常”，最后还得视中国人大的“心情”如何

现在，表决还没有开始，甚至还没有最后定稿，王光亚就已经态度斩钉截铁地说了：“我们将与其它国家合作，共同阻止这一计划。”

在我们看来，“四国集团”要通过这“中国与其他国家合作、共同阻止这一计划”的一关，并不是十拿九稳，也就是说，仅是整个安理会改革进程的第一步，“四国集团”、或者说是日本，要想通过，就得下血本。

显然，北京在临近投票前、声称要反对、但“又不明确地表示”最后是否一定要行使否决，从而令日本“入常”变得“理论上希望并没有完全破灭”，而要视“中国的立法机构”会如何考虑到其他人的感情、从而取决于中国人大“在最后关头对日本做何的评判”，如此一来，日本夹在“四国集团”之中、在这种要视中国人大的“心情”如何的被动中、日本今后将“如何表现自己”，将直接决定中国人大“是否最终决定动用否决权”。


*** 北京将“最终是否动用否决权”的判断标准“直接与其他人的感情”挂钩

首席评论员指出，从上述分析中不难看出，王光亚在以“暗示”的方式、在确定了中国“有意”动用否决权的同时，又以“不能确定”的方式、将中国“最终是否动用否决权”的判断标准“直接与其他人的感情”挂钩。

在东方评论员看来，这个所谓的“感情”，根本就是在警告日本政府、也是警告日本社会，必须在今后的“申常过程”中、正视历史问题，切切不要伤害中国人民的感情、也不要伤害亚洲、世界人民的感情，不然，中国的立法机构--中国人民代表大会，将会根据中国、亚洲、以至世界人民的感情，从而代表“世界人民”、去确定是否要投下否决票。


*** 王光亚的这一番“绕口令”，实际上也给日本挂上了一颗胡萝卜

不难看出，王光亚的这一番“有意”动用、却又“不确定是否最终动用”否决权的“绕口令”，实际上也给日本这头驴子前面挂上了一颗胡萝卜，当然了，与华盛顿挂出来的胡萝卜相比，北京的胡萝卜“在品种上”还是有区别的，那就是，对日本军国主义而言，美国的胡萝卜是“可闻、可望、而不可即”，而北京的胡萝卜则是“既不可闻、也不可望、更不可即”。

*** 日本还将为每向前走一步、而付出更加惨重的代价

也就是说，除非日本政府、日本社会“经过长时间的反省”、而彻底放弃日本军国主义，否则，按北京今天公布的这一套“阻击计划”，我们可以非常肯定地下结论，披着军国主义外衣的日本、要想从中国手中取得“入常”的门票，根本就是休想！

不仅如此，日本还将为每向前走一步、而付出更加惨重的代价。值得强调的是，这种代价绝非仅是金钱、物资上的、更多将是政治上的、比如说日本的历史清算问题、通过国际社会清除日本的制造核武器的潜力问题、甚至是其他的日本核心国家利益。

在我们看来，可以肯定的是，美国、英国、法国、以及俄罗斯这些也有否决权的常任理事国、也一定会瞄准机会、对日本大搞“雁过拔毛”的。

在东方评论员看来，日本右翼和日本社会终究会发现，如果日本不放弃军国主义而“强行叩关”的话，最终不仅会落得一个“身上的毛会被列强们拔得精光”的下场，恐怕还不得不静候“代表中国民意的中国人大之投票结果”。在东方评论员看来，有朝一日，若果真面对这一情景，日本右翼当作何感想？

当然了，日本右翼到时“会做何感想”，我们今后也许根本就没有机会看到，今天、在这里也就不多说了。下面，我们将把关注的焦点放在中东方向。

在一则来自伊朗国内的消息之后，东方评论员将谈谈伊朗国内政局的最新动向。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
