# -*- org -*-

# Time-stamp: <2011-08-03 23:47:35 Wednesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 2005年6月20日  星期一

** 朝鲜有可能重返核不扩散条约

【平壤消息】综合报道，朝鲜领导人金正日日前表示，如果条件成熟，朝鲜在下个月就可能重返六方会谈。与各方就朝核问题以及朝鲜半岛无核化的其它相关议题进行平等的协商。金正日还表示，如果朝核问题得到解决，将重新加入不扩散核武器条约，接受包括国际原子能机构核查在内的所有的国际核查。不过，美国国务院发言人则对此事的反应相当谨慎。

郑东泳发表朝韩会谈结果

据韩国联合通讯社报道，韩国统一部长官郑东泳17日晚9点40分在首尔三清洞南北会谈事务局举行新闻发布会，发表了会谈结果，并转达了以上内容。

郑东泳说：“双方在会谈中讨论了包括核问题在内的政治、军事、人道主义等问题。我向金正日委员长转达了卢武铉总统关于解决核问题和发展南北关系的口信。”

郑东泳说，金正日对卢武铉总统为朝鲜半岛和平做出的努力表示了感谢，并表示将在适当的时机访问首尔。

关于朝核问题，金正日说：“朝鲜半岛无核化宣言仍然有效，这也是金日成主席的遗训。我们没有拥有核武器的理由。我们从未放弃六方会谈，也没有拒绝参加六方会谈。只是因为美国轻视我们，我们出于自卫的目的才和美国对抗。如果美国认可和尊重我们的态度很坚定，7月份也可参加（六方会谈），但这个问题还需要与美国进一步协商。目前美国的态度好像还不够坚定，好像在拖延时间。”

金正日高度评价6月10日举行的韩美首脑会谈，表示朝鲜在观察美国的态度。

关于朝鲜所担心的体制安全保障问题，郑东泳向金正日说明多边框架内的安全保障比朝美之间的双边安全保障更为安全和有效。对此金正日表示，“有道理，以后会认真研究”。

对于韩国政府提议的“重要方案”，金正日也表示“将认真研究后答复”。

当问及对布什的评价时，金正日回答，“没有理由把布什总统阁下想得很坏”，从克林顿政府时期开始，他就对美国抱有好感。

美国对朝鲜重返核谈表态反应谨慎

据报道，针对金正日的表态，美国国务院周五表示谈的确定日期和朝鲜的诚意才是美国真正希望看到的。

金正日在17日会见韩国统一部长官郑东泳时表示，如果可以和美国达成协议，朝鲜最快可以在7月回到朝核问题6方会谈的谈判桌。美国国务院周五响应说，目前还没有获得有关金正日表态的详细的资料，无法做出进一步的评论。国务院发言人表示，朝鲜光有意愿是不够的，提出复谈的确定日期和以诚意回到谈判桌才是美国真正看重的。

美国国务院发言人埃雷利说：“在没有确切日期之前，其它的表态都没有意义。真正让我们觉得有意义的是，回到谈判桌，而且更重要的是要非常严肃并富有诚意。”

对于金正日可能提出的先决条件，美国明确表示拒绝任何为新一轮会谈的召开所提出的要求。朝鲜应该尊重六方为解决朝核问题所达成的共同框架。

埃雷利说：“我们不接受任何复谈的先决条件，我们已经提出了一个计划，而讨论这个计划的地方就是六方会谈。”

美国总统布什多次表示，尽管对于重开六方会谈，美国没有具体的时间表。但是朝核问题是政府要优先解决的问题。他也期待借助其它各方，特别是中国的外交努力在这个问题上早日取得突破。

朝韩将恢复将星级会谈

据联合通讯社报道，金正日对于民间和政府代表团参加6.15共同宣言5周年活动，使活动圆满结束，给予了高度评价，并表示，朝鲜将组织由政府重要人物组成的代表团，派到韩国参加韩方准备的8.15活动。希望8.15活动继6.15活动之后，成为南北关系的发展的又一个契机。

郑东泳提议，今年8月15日是朝鲜半岛南北分裂60周年，也是半岛光复60周年，有着重要意义，因此必须实现中断1年的离散家属相逢。金正日欣然接受，当场指示劳动党中央委员会第一部部长林东旭（音）在金刚山举行第11次离散家属相逢活动。

此外，双方就恢复将星级会谈，举行水产会谈，开通从平壤到首尔直通航线等达成了协议。

郑东泳回国后前往青瓦台，向卢武铉总统汇报了访问结果。卢武铉总统表示，与金正日委员长举行长时间、有诚意的对话，具有深远的意义，是个好征兆。此次访问取得了很多成果，希望各方共同努力，维护会谈成果。双方通过坦诚的对话，确认相互信任关系是非常重要的成果。

郑东泳与金正日会面达4小时50分钟

在平壤出席纪念6•15共同宣言发表5周年庆典活动的郑东泳17日与朝鲜国防委员长金正日单独会晤举行会谈。

这次韩国现任统一部长官与金正日的单独会晤，是自2000年9月朴在圭时任统一部长官与金正日会面以来，时隔5年的又一次单独会面。

这次单独会晤是朝鲜方面当天通报会面事项，而郑东泳前往会晤金正日的形式进行的。

郑东泳与金正日从11点到13点30分，进行了长达两个半小时的单独会晤。而后到15点50分，在2小时20分钟的时间里与政府及民间代表团的负责人共进午餐。

郑东泳上午10点39分离开百花园招待所，政府代表团则在他离开之后不到1小时就乘轿车出发。下午4点08分许代表团一同回到了百花园招待所。

晚6点30分代表团离开百花园招待所，7点左右从机场出发，并于8点左右回到达仁川国际机场。



【时事点评】在东方评论员看来，朝核问题在这个周未可谓是“风起云涌”。我们注意到，按朝鲜领导人金正日的说法，既“如果条件成熟，朝鲜在下个月就可能重返六方会谈。与各方就朝核问题以及朝鲜半岛无核化的其它相关议题进行平等的协商”。我们认为，显然，如果拿这个态度与三、四月份时朝核局势相比，朝鲜无疑是赢家。

●三、四月份时发生的几件事情

下面，我们不妨简单回顾一下三、四月份时发生的几件事情。

大家知道，一年前、“六方会谈”中断的时候，平壤并没有将“朝鲜问题”与“朝鲜半岛核问题”之间直接划等号。由于时间过去的不久，我们还清楚地记得，朝鲜第一次将两者之间划等号、是在今年4月份期间。

当时，北京对日外交是罕见地强硬，不仅拒绝就日本驻华大使馆受损“道歉”、反而更加猛烈抨击小泉纯一郎参拜靖国神社、并指出造成“这一事件”的真实原因是日本在历史问题上的态度，真正应该道歉的是日本政府。

我们注意到，就在日本外相“北京败北”之后、围绕着是“中国应该道歉”、还是“日本应该道歉”的问题，可以说，中日之间“在台上台下”进行了非常激烈的交锋。

也正是在这一连串激烈交锋的过程中、在小泉纯一郎最后于印尼雅加达亚非峰会上“道歉”之前十几个小时，朝鲜半岛上的“两个国家”-韩国和朝鲜官方，同时就朝核问题表达了各自“最新的立场”。

其中，韩国外交部次官补宋旻淳以媒体专访的形式表达立场的，我们注意到，他不仅提及了解决朝核问题的“六月期限说”，同时、他还公开反对将朝核问题提交联合国处理的解决方案。

而朝鲜方面，则是通过朝鲜劳动党中央机关报《劳动新闻》发表了一篇评论说，平壤的观点则是“要实现朝鲜半岛的无核化，美国就必须撤走其部署在韩国及周边地区的所有核武器，彻底消除核威胁，同时必须根除韩国走核武道路的可能性”。

●金正日就是不拿“六月期限”当回事、这分明是不给日本人“半点面子”

对这个所谓的“六月心理底线”的说法，东方评论员之前已经多次给出过“解读'，大家应该还记得，“六月期限说”的“版权”可是日本“独家”所有的，事实上，早在赖斯3月访问北京的时候，我们就注意到，日本就提前放风说“美国日本在六月设立解决朝核问题的期限的问题上达成了一致”。

之后的事实证明，围绕这个“六月期限”说，“中美日”三方是“各有一套说词”，就在日本单方面捅出这一说法之后，中国外交部发言人稍后就正式表示“没有听美国官员（指正在北京访问的赖斯）说过”，而美国方面开始是迟迟没有反应，或一到有了反应的时候，却是“最为正式”，即是由美国总统布什“亲自出面”、在一次公开讲话中、不仅明确证实“没有为朝核问题设限”这一说，并以“我是有耐心的人”自栩。

总而言之，在朝核问题上，真正玩牌的、起着关键作用的两家，不论是中国、美国，谁都不认那个“六月期限说”。不仅如此，北京方面还从未表现出一点着急的样子，反而是一再劝各家“要拿出诚意、也要有耐心”、而华盛顿方面，自布什亲口说了“美国没有为朝核问题设限”之后，在公开场合，华盛顿官方也都在“刻意地”保持着这一宣传口径。显然，北京和华盛顿的这种“不急不忙”的态度、与日本“上赶着”要将解决朝核问题的期限划在六月份的做法、是显得如此的格格不入！

东方评论员，非常清楚，韩国在那个时候、在韩日关系因独岛争端而处于最紧张的时候，将日本单方面划出的、北京和华盛顿“都不承认”的“六月期限说”给“引述”一遍，并在同时也反对华盛顿欲将朝核问题提交联合国的主张，这分明是在表明自己“有独立的朝核立场”。

显然，到今天为止，金正日已经正式地将“六方会谈”复会的日期强行地推到了下个月、也就是7月份再说，在东方评论员看来，这表明，金正日还就是不拿“六月期限”当回事、这也分明是不给日本人“半点面子”。


*** 朝鲜“左手制造问题、右手解决问题”的一个策略而已

另外，值得强调的是，按金正日的说法，既“如果条件成熟.......与各方就朝核问题以及朝鲜半岛无核化的其它相关议题进行平等的协商”。

对此，东方评论员认为，金正日这一次是亲口将“朝核问题以及朝鲜半岛无核化问题”给区别开了，而没有象四月份朝鲜官方所说的那样、将“朝核问题”和“朝鲜半岛无核化问题”“完全等同”起来，表面上看，平壤“似乎”已经“让了一步”。

在东方评论员看来，我们之所以称其为“似乎”是让了一步，原因在于：就整个过程而言，这不过是朝鲜“左手制造问题、右手解决问题”的一个策略而已，显然，这就如美国在朝核问题上的立场、即可以说朝鲜“暴政前哨”制造紧张、又可以说“朝鲜是一主权国家”缓和气氛，然而，紧张来、缓和去、却始终是“左手打右手”，美国的核心立场是一点儿都没有变化。

东方评论员认为，朝鲜的这一番表演、实际上也是个“左手制造问题、右手解决问题”的一个策略而已：表面上看也似乎是“让了一步”，然而，本质上的立场也没有任何变化，给人的感觉却是朝鲜在中、韩、美各方的劝说下也好、威胁下也罢、总之，朝鲜已经表现出了一定的诚意、从而已经给了各方一个台阶、也着实令朝核问题的气氛“缓和多了”。

当然，这里面似乎独独没有日本人什么功劳。

*** 金正日的这番话其实在与卢武铉唱的一出双簧

然而，朝鲜在这个时候为什么要让一步呢？东方评论员认为，金正日的这番话其实在与卢武铉唱的一出双簧。

请大家注意这一段，原文是，郑东泳说，“金正日对卢武铉总统为朝鲜半岛和平做出的努力表示了感谢，并表示将在适当的时机访问首尔”。

显然，按郑东泳的说法，他给金正日带去了卢武铉的口信，而金正日不仅“对卢武铉总统为朝鲜半岛和平做出的努力表示了感谢”、还表示“将在适当的时机访问首尔”，东方评论员更是注意到，关于朝核问题，金正日的说法更显积极：“朝鲜半岛无核化宣言仍然有效，这也是金日成主席的遗训”。

谁都看得出，金正日番言行，不仅仅是给了卢武铉“极大的面子”、更是让人立刻想起了五年前的一幕：２０００年６月，时任韩国总统的金大中成为朝鲜半岛分裂５０多年来第一位访问朝鲜的韩国总统。而金正日则是亲自到机场迎接金大中，在一起回平壤的途中、为了显示亲热，两人不仅“同乘一辆汽车”，还“手握着手”，共同接受大约６０万平壤人夹道欢迎。

有意思的是，时事评论员至今仍然清楚地记得，金正日当时也是将其过世的父亲搬出来“明志”，称举行朝鲜半岛首脑会议是他父亲金日成的“去世前的最大心愿”。

事实上，也就是在那一次，金正日当着金大中的面、也是以“在适当的时候会去的”这句话、作出了“回访汉城的承诺”。

现在看来，自那之后，可以说是弹指一挥间，就过去了五个年头，期间，由于布什上台，美国开始执行一套新保守主义者周密策划的“全球战略”，而在这一全球战略的规划中，出于在集中力量攻击中东的同时、华盛顿必须让包括中国、日本在内的整个东亚不得安宁的需要，就必须让朝鲜半岛不得安宁。

也正是在这一大背景下，不仅金大钟与金正日商定、并发起的“先整合”南北经济、“后图谋”半岛统一的“阳光计划”、立刻被布什给掐死了，甚至克林顿与金正日之间达成的“以援助换核武”的“核框架协议”、也立刻被布什掐死了。


*** 卢武铉眼下想做的，都是对华盛顿“大大不利”的事情

在之前的点评中，我们已经说过，与布什谈得“并不融洽的”卢武铉、从华盛顿回来后，不仅有意继续强化“朝韩”双方的经济联系、更是与朝鲜一道提出了“朝鲜半岛统一”的构想。

在东方评论员看来，卢武铉之所以奋力扯起“民族统一”这面大旗，就是想借这面大旗、寻找机会、让其前任发起的、却被布什亲手掐死的“阳光计划”“起死回生”。

显然，在目前卢武铉不论是想借“民族统一”大旗让“阳光计划”还魂、将朝鲜经济纳入自己的产业链也好，还是只想维持朝鲜半岛和平也罢，起码有一点美国人是看得一清二楚的，即：“这些可都是”对亚洲经济一体化“大大有利”的事情，也就是说，这些都是对中国全球战略大大有利的事情，自然也就都是对华盛顿大大不利的事情。


*** 对朝鲜而言，其面对的国家生存威胁“有两个”

东方评论员认为，“以独霸全球为自己最核心利益”的华盛顿、几年来“一直不愿意认真解决”的有两个问题，一个是台湾问题，显然，台湾问题是美国用来凝聚日本、台独势力、共同遏制中国的最好的“凝结剂”；另一个就是“朝核问题”。

首席评论员指出，对朝鲜而言，其面对的国家生存威胁有两个：一是它所认为的美国“迫在眉睫的入侵”，一是长期存在的经济困难。显然，朝鲜发展核武器只能解决前者，而不发展核武器只能解决后者。最为麻烦的是，只要朝鲜的经济问题解决不了，那么，朝鲜就是有了核武器，也不可能维持政权的长时间稳定。


*** 对中国而言，“朝核问题”其实是由朝鲜的经济困难引起的

因此，在我们看来，对中国而言，“朝核问题”其实是由朝鲜的经济困难引起的。显然，一个没有进行经济改革的朝鲜、最后必将是一个“北京不能丢弃、也丢弃不起的沉重包袱”。

因此，东方评论员认为，朝鲜核危机的深层原因是金正日政权面临深重的经济危机，因此只有从根本上促使平壤实行经济改革，在经济方面进行类似于中国的模式进行改革，并完全融入中国、韩国（有可能还会加上日本）的经济生活中、再带动俄罗斯远东地区的经济发展，只有这样，朝鲜才有可能因是区域经济稳定的一部分、而享受到由中国、俄罗斯、韩国、甚至还有可能包括日本来共同提供的、对朝鲜国家安全的“多边保障”，从而才能切实地保持朝鲜政权的稳定，才能最终解决核问题。


*** 对“多边模式”金正日表示“有道理”

东方评论员注意到，上面那段新闻中似乎“点到了”这一“多边模式”。请大家注意这一段，原文是：关于朝鲜所担心的体制安全保障问题，郑东泳向金正日说明多边框架内的安全保障比朝美之间的双边安全保障更为安全和有效。对此金正日的态度则是：“有道理，以后会认真研究”。

可以肯定的是，就目前而言，金正日认为“有道理”、并愿意“以后会认真研究”的“这一版本的朝核问题解决方案”，华盛顿自然是“欲除之而后快”。

然而，从卢武铉顶着“美国威胁全部撤军”、也要扛起“民族统一”大旗的举动来看，在北京的策应下，华盛顿似乎很难阻止韩国重启“阳光计划”这一类的、意在整合朝鲜经济、推动东北亚经济一体化的决心了。


*** 朝核问题似乎已经演化到了关键的一步

东方评论员认为，朝核问题似乎已经演化到了关键的一步，在我们看来，卢武铉不顾及布什阴森的脸色、也要派他的特使--郑东泳到平壤“再请”金正日访问汉城这一事实表明，布什政府几年来奉行的朝核问题强硬政策、“似乎已经到了”难以为继的地步。

只是根据我们的长期观察，就如美国的战略策划者对“东亚经济一体化”早就有、并一直在执行的一套“全力破坏的对策”一样，华盛顿对“朝韩”经济整合、“东北亚经济一体化”“也有一套对策”。


*** 北京有必要警惕华盛顿朝核政策“可能的改变”

在我们看来，如果美国在中东方面没有实质性进展的话，那么，急于稳定朝核问题、阻止其继续恶化的华盛顿，不排除会在一定程度上改变其朝核政策。东方评论员认为，其改变的“核心”可能是：愿意逐渐解除对朝鲜的制裁，甚至有可能同意与朝鲜签订互不侵犯条约，但条件是朝鲜必须同时销毁其核设施，并允许核查人员在朝鲜境内自由活动。


东方评论员的观点是，如果将来有一天布什果真这么干的话，那也并非意味华盛顿是在原有的立场底线上有所后退。恰恰相反，我们认为，一旦到了这一步，将更加说明朝核问题到了最为实质的阶段，即涉及朝鲜一些“深层次的问题”，朝核问题将进入到一个华盛顿以退为进，以守为攻的阶段：它意味着华盛顿将出台一套从政治、经济到军事的对朝鲜新策略；而就外交谈判层面而言，也意味着华盛顿将逼迫平壤将核危机谈判、从核计划“表层”转入“整个”朝鲜半岛常规武器和军力部署的深层。

这种可能性虽然是种推测，但是，东方评论员认为，如果事情进展到了这一步，那么，“朝韩”内部、特别是韩国国内的亲美政治势力、就有可能成为韩国半岛政策的不稳定因素、就可能为华盛顿大加利用。


*** 牢牢把持住朝核问题的主导权，对北京不仅现实、也极为重要

在东方评论员看来，稍为处理不好，就极可能影响朝鲜的经济改革进程和政权稳定，并动摇韩国的半岛经济整合计划，那样一来，平壤就将面临一个两难和被动的局面，其局势、进程很可能非金正日、卢武铉所能掌控。

首席评论员因此也指出，对北京而言，由于有个华盛顿一手控制的“台独进程”、因此，牢牢把持住朝核问题的主导权不仅现实、也极为重要。

在我们看来，中国在“两岸三通问题”上有实质性突破之前，美国在朝核问题上的任何承诺、都不能视为朝鲜“彻底弃核”的理由，而只能作为朝鲜一步步销毁核计划的条件。在我们看来，只有这样，在最近几年的时间里，只要台湾问题一天得不到实质性进展，北京就始终可以借“朝核问题”、找机会在“美日韩”、“美日”军事同盟间“插针”“泼水”！

前面说了，布什政府几年来奉行的朝核问题强硬政策、“似乎已经到了”难以为继的地步。然而，在我们看来，“似乎已经到了”和“已经到了”还是有“很大的区别”的。对此，首席评论员就指出，这个“很大的区别”就是华盛顿手中仍然还抓着一张牌，这就是日本。

在我们正在讨论的过程中、汉城方面传来了一则最新消息。我们先来看看卢武铉和小泉纯一郎会谈的结果，之后，东方评论员将继续今天的朝鲜部分。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 韩日首脑会谈就历史遗留问题达成初步协议

【汉城消息】据联合通讯社报道，韩国总统卢武铉２０日在此间说，韩日首脑会谈决定启动第２届历史共同研究委员会研究工作，同时下设教科书分科委员会开展共同研究工作，并公开所有研究结果。

当天下午，卢武铉总统结束长达２小时韩日首脑会谈后，在联合记者招待会做出上述表示后继续说，在按照各自国家的教科书编写制度编写教科书的过程中，有关历史遗留问题的共同研究结果将作为参考资料。

此外卢武铉透露，小泉纯一郎表示将考虑日本国民舆论等全方面因素后，研究建立新的追悼及纪念和平的设施。

卢武铉还说，在韩日首脑会谈上，就参拜靖国神社问题提出了２００１年韩日首脑会谈上讨论过的建立其他追悼设施的问题。



【时事点评】事实上，这则消息传来时，已经接近我们今天的截稿时间了。之前的消息是，卢武铉不会和小泉纯一郎一起参加记者会，而这则消息显示，卢武铉并没有强硬到最后。


*** 太多的因素、决定了韩国其实对日本暂时还硬不起来

与北京的强硬不同，韩国相比日本，是处于“以弱敌强”的位置，因此，在东方评论员看来，有太多的因素、决定了韩国其实对日本暂时还硬不起来。

我们认为，韩国的“弱”、是在于多方面：第一，其综合国力不及日本；第二，在美国东亚战略中、韩国的重要性不及日本；还有，就是在国家安全上、受“朝核问题”最终解决方式影响最为巨大的是韩国、而不是日本；

东方评论员，仅列举以上三点、就足以决定韩国“不能对日本一味强硬”。


*** 韩国对日本“不能一味强硬”最主要的原因，不是别的，还是中国因素

然而，首席评论员指出，韩国对日本“不能一味强硬”最主要的原因，不是别的，还是中国因素。在我们看来，由于地理和民族的原因，韩国是一心想一劳永逸解决朝核问题的，然而，与北京和华盛顿相比，韩国知道、自己单独是决定不了任何问题的，它只要将符合自身利益的朝核政策、“依附在”中国或者美国中的一方、才能发挥起“关键作用”。


*** 目前华盛顿的“态度”，仍然是尽一切可能将朝核问题“稳定下来”之后、再继续地“拖下去”

显然，华盛顿的全球战略下的朝核政策、本质上是通过一个紧张的朝核问题、维持一个紧张的朝鲜半岛的。只是现在，由于北京已经将朝核问题“做成了”一副“东亚核竞赛牌”抓在手中、而美国的最大利益又和“东亚核竞赛”相抵触，因此，必然顾忌韩国、特别是日本长久之后、必然会产生“离心力”，这才不得不将“朝核问题”“不当回事儿”的态度、调整为谋求“尽快地稳定朝核问题”。

请大家注意，是“尽快地稳定”朝鲜问题、而“不是尽快地解决”朝核问题。由此可见，在朝核问题上，目前华盛顿的“态度”尽管积极了许多，但是，其政策核心仍然是“不愿意解决朝核问题”、仍然是尽一切可能将朝核问题“稳定下来”之后、再继续地“拖下去”。


*** 韩国是可以将自己的朝核政策“依附到”北京身上的

不难看出，华盛顿“不愿意解决朝核问题”的战略价值取向，显然不符合韩国的“最大利益”，也正因如此，韩国就无法将自己的国家战略取向依附到华盛顿的全球战略上。

而在韩国眼里，北京尽管想解决的是“朝鲜半岛核问题”、而非仅仅是个“朝核问题”，但是，由于朝鲜对中国具有巨大的地缘政治和经济战略价值，北京是愿意“尽可能地维持朝鲜半岛稳定与和平的”、如此一来，韩国是可以将自己的朝核政策“依附到”北京的全球战略上的。


*** 韩国、朝鲜其实和日本一样，对一个强大的中国从来都是“心怀戒心”的

朝鲜对中国的地缘价值自然是无须多论，而朝鲜对中国的经济价值、就体现在北京有意利用韩国整合朝鲜半岛经济的过程、启动“东北亚经济一体化”进程，并以此去催动“东亚经济一体化”进程，从而主导亚洲经济、政治一体化进程。

然而，韩国、朝鲜对中国的这一战略，自然也是“心知肚明”，此外，他们其实和日本一样，对一个强大的中国从来都是心怀戒心的。因此，就如东盟为了防范中国所做的那样：一方面想借中国的经济的发展而发展、因此就与中国搞了个“10+1（中国）”，一方面又惧怕中国的太强大、从而始终都在处心积虑地想“拉日本入伙”，以尽可能地平衡中国的影响，这就有了个“10+3”。

*** 这种结果实在是“太正常了”

事实上，这一心思在韩国决策层的头脑中又何尝没有？在韩国人看来，韩国想搞的是韩国主导的朝鲜半岛经济整合，是“以朝鲜半岛为核心”的、辐射中国东北、俄罗斯远东、朝鲜、日本在内的东北亚经济一体化。

因此，为了尽可能地平衡中国的影响力，如果能将日本拉进这一进程，自然就成了关键。在这种背景下，卢武铉尽管“非常生气”、却仍然和在参拜靖国神社问题上没有任何改变的小泉纯一郎同时出席记者招待会。

在东方评论员看来，站在韩国的立场去看，出现这种结果实在是“太正常了”，我们认为，这就是国际政治的现实性与残酷性，是由不得以个人感情为依归的。

下面，我们关注的目光，将跟随一则中国外长访问中东的消息转移到中东方向，并以此作为今天中东部分讨论的开始。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
