# -*- org -*-

# Time-stamp: <2011-08-02 13:53:03 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

* 2005年02月28日 星期一

** 日本媒体称：朝鲜拟6月重返六方会谈 10月与美签署条约

  【东京消息】据日本产经新闻报道，朝鲜将会在6月重返朝核六方会谈的谈判桌，并会在10月与美国签署一项条约。消息是透过非官方渠道传达给韩国政府，然后再传达给日本政府。不过消息还未得到日本官员的证实。

  据日本产经新闻28日引用日本政府有关人士的话报道，朝鲜通过非正式渠道向韩国政府转达了这一信息。据推测，由于重启六方会谈之前需要进行工作组会议，朝鲜很有可能3月份正式表明重返六方会谈的意向。

  据日本政府有关人士透露，朝鲜向韩国政府转达了第四次六方会谈中谈论朝鲜半岛实现无核化以及确定经济支援日程后，10月份为止与美国签定具体协定的意向。

  【时事点评】我们知道，早在2000年，北京在公布《一个中国原则与台湾问题》白皮书中，就已非常明确指出三种可能导致大陆采用断然措施的情况，包括使用武力。白皮书明确指出：“如果出现台湾被以任何名义从中国分割出去的重大事变，如果出现外国侵占台湾，如果台湾当局无限期地拒绝通过谈判和平解决两岸统一问题，中国政府只能被迫采取一切可能的断然措施、包括使用武力，来维护中国的主权和领土完整，完成中国的统一大业。”外界随后将此视为大陆的 “动武三前提”。

  在东方评论员看来，也就是这么个“动武三前提”，尽管全是原则性的东西，操作性不佳，但是，不论是“台独”、还是支持台独的势力就是一直把它“当回事”。

*** 美国国内有一批人也一直在谋求着做这么一件事

    事实上，我们认为，长久以来，围绕朝核问题，美国国内有一批人也一直在谋求着做这么一件事，即，为朝核问题“划定一条坚守的红线”、其性质就如中国在台独问题上清楚地划出的“那条不可逾越的红线一样”。

    在我们看来，美国的新保守主义者不仅一直计划这样做，并前后相继做了多次努力，尝试着让北京相信一旦朝鲜不让步，美国将毫不犹豫对用军事手段单方面地去解决问题。
 
 

*** “六方会谈”实际上已经从“对话的性质”转变成了“对抗的性质”

    但是，就如我们在早前的《东方环球时事》中所说的那样，在布什先后于去年4月和7月份，派“极其强硬”的切尼、与切尼相比相对温和的赖斯相继访华，欲以一个毫无保障的“维持台海现状去换取北京放弃朝鲜”。

    事实证明，在北京“不再相信”台海有和平解决的可能性之后，确信美国霸权一天不除，台海就必有一战之后，自然也就一口拒绝切尼和赖斯的带去的 “以美国承诺维护台海现状的承诺、去换取北京放弃对朝鲜的军事保护”的建议。从根本上讲，切尼和赖斯这两位重量级人物的访华“相继失败”，实际上就是中国正式拒绝放弃朝鲜的必然结果。

    从而从那开始，从赖斯离开北京的那天开始，也就是从去年7月份之后，朝核问题的和平解决进程、实际上就彻底停顿下来。在东方评论员看来，“六方会谈”实际上也就从“对话的性质”转变成了“对抗的性质”，这就是为什么布什连任前朝鲜半岛局势“一转直下”的原因之所在。

*** 朝鲜何以敢与华盛顿叫板？

    在我们看来，朝鲜之所以敢与华盛顿叫板，不仅是因为它是挟在中、俄、美和日本、韩国间的战略要地，更重要的是、它同时在地理和政治上“紧紧地背靠”着中国和俄罗斯这两个美国“不能拿对手怎么样”的大国，这与美国“敢说打就打”的伊拉克“没有保护人的情况”截然不同。

    东方评论员认为，尽管朝鲜远远没有伊拉克、伊朗那样的石油资源，然而
    #+HTML:<b class="mark-text-1">朝鲜政权的“稳定与否”直接关系到诸大国们的“全球战略的主动与否”。</b>
    #+LaTeX:\red{朝鲜政权的“稳定与否”直接关系到诸大国们的“全球战略的主动与否”。h}

    特别是对中美两国，由于本来就有个台海问题没有解决，“中美”国家利益更是在全球范围内的战略要地[fn:1]“频繁交手”、比如说中东，因此，在“中美两国”看来，营造出一个“对自己有利的”东亚形势至关重要，如此一来，在台湾问题上彼此都不敢轻易有大动作的情况下，各自在朝鲜半岛上所具有的地缘利益也就日显突出。

    首席评论员指出，从春节初一以来，我们从这段喧闹的日子里，可以清楚地看到，尽管中美两国都在东亚“努力营造一个对自己有利的东亚形势”。然而，不论是从地理位置，还是从国家战略、甚至是从日本侵略亚洲的历史来看，日本对朝鲜半岛战略价值的重要性更是“颇有心得”。

    也正因如此，在东方评论员看来，“朝核问题”或者说“朝鲜半岛紧张与缓和”已经成了大国们手中一张牵一发而可以动全身的“大牌”，在我们看来，“这张牌”不仅北京在打、华盛顿也想打、有意思的是，日本人也想挤进玩一把。

    在一段有关日本与韩国争夺独岛最新进展的相关报道之后，我们将继续这个话题，看看日本人是怎么玩这张牌的。


** 韩议员反日情绪高涨呼吁立刻驱逐日驻韩大使

   汉城消息】据韩国联合通讯社报道，韩国政党进一步加大了对日本驻韩大使高野纪元就韩国独岛发表的有争议的言论的批评力度。一些议员甚至要求立刻驱逐高野纪元。

   日本驻韩国大使高野纪元23日称独岛(日本称竹岛)是日本领土。这在韩国国内引发了强烈反响。国会文化和旅游业委员会今天举行了全体会议，委员会成员纷纷发表了反日言论。委员会主席强调指出，韩国还没有从日本殖民主义的“阴影”中走出来。

   独岛位于韩国郁陵岛东面约70公里处，是由被称为“东岛”和“西岛”的两块岩石组成的岛屿。韩日两国都宣称对此岛拥有主权，目前韩国实际控制这一岛屿。

** 朝核困境无妨援助韩开运六千多吨援朝玉米

   中新网2月28日电 据法新社报道，韩国官员27日宣布，尽管目前朝核问题陷入困境，但韩国仍将履行去年的承诺，为朝鲜提供最后“一船”食品援助货物。

   这批货物包括大约6500吨玉米，这是韩国去年承诺向朝鲜提供的“10万吨玉米援助”的最后一部分，它们将在3月2日或3日运抵朝鲜西部港口。

   “韩国仍然保证将会继续向朝鲜提供人道援助，以便促进它与朝鲜之间的合作。”一位未透露姓名的韩国官员说。

   联合国粮农组织上月呼吁，国际社会应向朝鲜提供更多援助，称目前朝鲜的粮食缺口达到了50万吨(价值2亿2千万美元)。

   【时事点评】就日本这次主动挑起“独岛争端”，东方评论员也通过几天的跟踪分析给出了大量的分析，总而言之，我们的观点是清楚的，那就是，这是大年初一日本挑起钓鱼岛争端、“美日”以“擦边球”的方式抛出涉及台湾问题的“安全共同声明”、中国暂时在东亚核军备竞赛的问题上“引而未发”的继续。

   我们注意到，连日来，这次由日本岛根县议会表示将强行制定“竹岛之日（韩国称独岛）”条例案引起的领土争端，在韩国国内爆发了一连串的抗议活动。由于今年是韩国从日本殖民统治下光复60周年，又是韩日建交40周年，同时还是“韩日友谊年”。
 
*** 充分地“展露”了小泉纯一郎的“狐狸尾巴”

    在东方评论员看来，日本中央政府在整个过程中的态度“耐人寻味”，开始，它借口很难干涉地方议会事务，声称不介入此事。然而，就在日本政府做此声明、且在韩国方面提出正式抗议之后，日本驻韩大使居然在汉城特意举行的外国记者招待会上、公然强硬地声称“竹岛是日本领土”。

    与此同时，日本另一位外交官员也坚定地表示：“维护对竹岛的拥有权远比韩日关系重要，具有重要的价值。”我们注意到，这名日本官员还强调：“政府解决竹岛问题的原则，是在不影响韩日关系的基础上，维护领土主权。”

    显然，如果日本政府不想看到事情不可收拾的话，那么，就算是日本中央政府真的“很难干涉地方议会事务”，那么，日本政府总可以让它的驻韩国大使不要火上浇油”吧。

    在东方评论员看来，日本驻韩国大使在这个时候的“火上浇油”，可以说充分地“展露”了小泉纯一郎的“狐狸尾巴”。
 
*** 小泉政府似乎是在有意在给东北亚局势制造混乱

    与此同时，我们注意到，对此，法国一家国际战略周刊就发表文章认为：从日本多个外交官的“强硬态度”来看，小泉政府似乎是在有意在给东北亚局势制造混乱。

    东方评论员认为，这种观点可以说是“一语中的”。东亚的形势是：一方面，日本在挑起钓鱼岛主权之争后，在答应华盛顿愿意将台湾问题纳入“美日安全共同声明”的同时，却没有将自己已经明确的“中国威胁论”推销出去，更孬提要华盛顿在钓鱼岛主权问题给出个让日本高兴的态度来。
 
 
*** 在中国以“半岛无核化”替代“朝核宣布有核”的“斡旋”下、朝鲜宣布“有条件地”返回“六方会谈”

    而另一方面，则是朝鲜在宣布有核武器之后，由于有中国的强硬支持，再加上欧洲和俄罗斯都在那里“不痛不痒”地、“象是履行手续一般”批评朝鲜“做了一件错事”之后，就没了下文。

    结果，在华盛顿后退一步、打了一记“擦边球”之后，朝鲜方面并没有象传说中的那样，进行打击范围涵盖日本的中程导弹试射，也没有做什么进一步刺激日本的事情，反观北京，北京一方面继续“拒绝指责”朝鲜“宣布有核”、并有意“转移概念”、以敦促“各方都要表现出足够的诚意、通过谈判实现半岛无核化”的方式来“重新给朝核问题定性”，结果，在中国的这番以“半岛无核化”替代“朝核问题”的“斡旋”下、朝鲜立刻宣布“有条件地”返回“六方会谈”。
 
 
*** 这种安排表明北京“暂时还不打算”将“东亚核竞赛[fn:2]”这张“牌”立刻就给抛出来

    显然，这种安排表明北京“暂时还不打算”将“东亚核竞赛”这张、日本人非常渴望见到的“牌”立刻就给抛出来。

    请大家注意这么一点，即，直到现在为止，在中国外交部的正式发言、或者中国领导人的谈话中，我们始终没有听到“朝核问题”这个词。

    有意思的是，一说到朝鲜半岛局势，北京方面的口径非常统一，那就是，要么用“半岛无核化”这个复杂的名词、要么干脆简化到“核问题”，总之，是在刻意地以这两种说法替代“朝核问题”这个词，东方评论员认为，北京“这样坚持”是有着深层的战略考虑的。
 
*** 恐怕不会再有人天真地相信：“美国”和“中国”是“清白无辜”的了

    在我们看来，大年初一，日本将钓鱼岛上的灯塔“收归国有”，大年初二，朝鲜“宣布有核武器”，这两件事间的“关联性”到了今天，恐怕不会再有人天真地相信：“美国”和“中国”是清白无辜的了，东方评论员认为，不论日本和朝鲜是否愿意当华盛顿和北京的棋子，然而，就事情的过程和结果来看，日本和朝鲜在追求自己国家利益的同时，的确起到了“棋子”的作用。
 
*** 北京通过朝鲜“宣布有核武器”地继续给美国和日本的战略协调制造障碍

    就华盛顿而言，日本在台湾问题上采取两面讨好的骑墙策略，实际上也是美日同盟背后的一大隐忧。如何化解这种隐忧，是华盛顿“一直在努力着的事业”。因此，这场较量下来，美国得到的不少，最大的战果就是那份谋划了多年、意在破坏“中日关系”基石的、涉及台湾的“美日安保指针”，初步达成了其着眼于中东、调整东亚安全格局的战略目的；

    对北京而言，由于日本帮着美国破坏了“中、日两国”牵制美国势力的“中日关系”，显然，北京的亚洲战略的确受损不轻，在台湾问题上也受损不轻。尽管日本在台海出现战火时，是否真会和美国一道协防还是个疑问，但是，
    #+HTML: <b class="mark-text-1">就目前的局势而言，台湾问题事实上已经由“中美对峙”变成了中国和“美日”对峙的局面。</b>
    #+LaTeX:\red{就目前的局势而言，台湾问题事实上已经由“中美对峙”变成了中国和“美日”对峙的局面。}

    然而，北京在台湾问题上面对更大压力的同时，显然也在朝鲜半岛上、通过朝鲜“宣布有核武器”这一点、在继续给美国和日本施加压力、继续给美国和日本的战略协调制造障碍。
 
*** 北京现在的策略似乎是在继续以“朝鲜半岛有核”这一事实为出发点，继续要求华盛顿做出选择

    中国外交部发言人的态度非常清楚，第一，中国不认为“朝鲜半岛无核化”仅仅是特指的“朝核问题”，第二，由于“有核”是朝鲜官方的正式声明，因此“朝鲜半岛的确有核”已经是事实，但是，中国显然已经将其定性为“现有基础”，这就是说，“朝鲜半岛无核化”必须在“现有基础”上、以谈判的方式和平解决，显然，“无核化的范围”不仅包括朝鲜、也应该包括韩国、甚至直指“驻韩美军”有无核武器的问题。

    由于“美日安全共同声明”将台湾纳入其中已经是事实，华盛顿通过一记“擦边球”避免了直接选择“东亚核竞赛”这一结果，因此，在东方评论员看来，北京现在的策略似乎是在继续以“朝鲜半岛有核”这一事实为出发点，要求华盛顿在朝鲜准备正式、公开进行核武装、继而有可能引发东亚核竞赛、和“全面缓和”朝鲜半岛局势这两种结果中做出选择。

    在我们看来，朝鲜公开、正式进行核武装显然是华盛顿“绝不容忍”的，那样一来，日本和韩国也必将尝试发动国内社会，强烈要求跨入核门槛，从而出现核军备竞赛，从而对美国的“亚洲军事存在”产生极大的冲击。
 
*** 美国的战略家们也准备了一套替代“东亚核竞赛”的应付方案

    同时，东方评论员也注意到，在朝鲜宣布有核之后，美国的战略家们也准备了一套替代“东亚核竞赛”的应付方案，那就是，美国也可能将在东亚可能实行更加强硬的军事存在，美国加强南韩和日本的军事力量。可问题是，在朝鲜正式跨入核门槛、拥有战略核打击力量之后，而美国仍然拒绝日本和韩国进入核门槛进行自卫的同时，日本和韩国的政治人物一定会扇动社会、对华盛顿施加压力，在这种情况下，日本和韩国社会、还会愿意缯加美国增强军事力量、继续接受美国的控制吗？

    当然，我们也注意到，美国的战略家还推测出了一种“可怕的结果”：认为，如果中国不和美国一道扭转局势，那么东北亚地区、包括日本，台湾，可能会感到更不安全，因而日本和台湾也可能想追求发展自己的核武器项目。
 
*** 以台湾可能发展核武威胁中国，根本就是在“拿台湾宣布独立”威胁中国

    显然，这份名单里面没有韩国， 只有让中国头痛的日本，另外还加了个让大陆“无从着力”的台湾，东方评论员认为，其威胁北京的意图是一目了然，因为在一般的不具国际经验的人看来，韩国有核武器对美国不是好事，而只要一提日本和台湾核武装似乎就可以让北京头痛。

    东方评论员认为，我们无意去指责抛出这种观点的美国专家专业水平，因为一种经不起推敲的观点，不一定是因为持有者的“专业水平不高”，在我们看来，很多时候，在“别有用心”的情况下，似乎更容易产生这样低级错误。

    然而，东方评论员认为，如果台湾也敢发展自己的核武器项目的话，那事情反而变得简单了，因为在大陆订下的动武条件、除了前面所说的原则性的 “动武三前提”之外，还有一条中美心照不宣的硬条件，那就是“如果台湾追求发展自己的核武器项目等大规模杀伤性武器的话，大陆必然会武力解决台湾问题”。

    因此，只要美国还不想同中国摊牌，由于台湾问题和朝鲜问题不一样，是中国没有任何弹性的主权问题，因此，“台湾发展核武器的事”本身就赞同于 “台独”，在东方评论员看来，以台湾可能想发展核武器来威胁中国的主意，根本就是在“拿台湾宣布独立”来威胁中国，当然，如果美国有这个能力摊牌，自然可以用这一套来威胁，问题是，美国还没有这个能力。

    事实上，就在美国战略学家献计献策的时候，从朝鲜宣布“有自卫用的核武器”那一刻起，就一直保持克制的华盛顿，今天终于愿意开出条件来、“请”朝鲜回到谈判桌上。最新的消息是，朝鲜将会在6月重返“六方会谈”的谈判桌，并会在10月与美国签署一项条约。

    到此为止，东方评论员认为，朝鲜在中国的庇护下，不仅成功地迫使华盛顿做出让步，而且谈判的基础，也被北京修改成了“朝鲜有核”的“现有基础”。
 
 
*** 朝鲜局势有缓和的信号，这不能不让“欲乱中牟利”的日本焦急

    反观日本：日本在主动于钓鱼岛主权问题上挑畔中国、并满足美国的要求、将自己放到了与中国公开对立的处境下之后，
    #+HTML: <b class="mark-text-1">日本在自己最关心的几个问题上</b>
    #+LaTeX:\red{日本在自己最关心的几个问题上}
    ，如，在确立“中国”为“美日同盟”的军事威胁的问题上、在“美日军事同盟”是否涵盖钓鱼岛的问题上，在引发“东亚核竞赛”的问题上，可以说是一无所得、这种结果似乎让小泉纯一郎冲着华盛顿、说了些日本领导人不应该说的一些话，比如，“将台湾纳入美日安保声明是华盛顿的意思”这一类的“外交忌语”，不论是出于何种原因，小泉的这种口不择言，让国际社会产生了“小泉被布什出卖了”的感觉。

    我们认为，在日本方面挑起中日钓鱼岛争端之后，在国际社会认为“小泉被布什出卖了”之后，不仅在日本所有可以用来实现“正常国家”的手段中、属于“最简便、高效的”---“东亚核竞赛”没有一丝迹象，反而朝鲜局势有缓和的信号，这不能不让“欲乱中牟利”的日本焦急。

    这一点，同韩国声称：尽管目前朝核问题陷入困境，但韩国仍将履行去年的承诺，为朝鲜提供最后“一船”食品援助货物、所表现出的有意为缓和半岛局势、营造气氛所做的努力、形成了“鲜明的对比”。
 
 
*** 日本对东亚核竞赛仍然没有死心

    东方评论员认为，自上世纪初至今，韩日两国在独岛（竹岛）问题上的较量就一直没有停歇过，而这次日本再次以这种不具弹性的领土主权问题、去主动挑畔另一个亚洲大国--韩国，其目的恐怕就在于挑斗各自国家的民族情绪。

    首席评论员指出，在日本挑衅中国、于钓鱼岛方向“搞事”、却在“三大问题上”暂时“都没有如愿”的情况下，这次又挑衅韩国、于“独岛”方向再次“搞事”，其主要目的恐怕就是想尝试催动“东亚核竞赛”这一步了，换而言之，日本对东亚核竞赛仍然没有死心。
 
*** 在之后的事态发展中，我们认为有一个地方非常值得注意

    首席评论员认为，在之后的事态发展中，我们认为有一个地方非常值得注意，那就是，朝鲜是否会主动介入这场“独岛（竹岛）争端”，显然，在我们看来，如果“六方会谈”仍然没有进展、换句话说，如果华盛顿仍然拒绝对朝鲜做出实质性的让步，从而让朝鲜半岛局势彻底缓和下来的话，那么，就算是朝鲜不朝日本方向试射导弹去刺激日本社会，而只需象上次那样，也声称对独岛拥有主权，那么，剩下的事情就是日本保守政府[fn:3]的事了。

    可以想像的是，一旦如此，日本政府一定会不遗余力地大做文章，象在钓鱼岛争端上所做过的那样，尽全力去催动国内民族意识。与中国争钓鱼岛主权，日本不占上风，因为中国是大国，是政治大国、经济大国、更是军事大国、是核国家，这已经让日本政治人物“悲情过一把了”。

    可以想像的是，如果与朝鲜或者韩国争独岛主权也不占上风的话，由于朝鲜不如日本大，韩国不如日本强、假如将高丽民族与日本争锋、渲染成“就是靠的核武器”的话，日本政治人物的“悲情”无疑也就将更上一层楼。

    在我们看来，不论日本人如何做这篇文章，起码有一点是少不了的，那就是，“中心思想”肯定是这样的：“一个没有核武器的日本，是无法保障自己的主权的”。事实上，从我们得到的最新资料中可以清楚地看到，在日本，已经有人开始这样做文章了。

    下面，是一篇译自日本一家主流媒体的评论，其立场显然是右倾的。在一起浏览该文之后，东方评论员将继续讨论美日在“朝鲜半岛无核化”问题上的战略矛盾。

[fn:1] 全球战略梛有哪些？中东
[fn:2] 东亚核竞赛?
[fn:3] 日本保守政府
