# -*- org -*-

# Time-stamp: <2011-08-02 22:56:03 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

#+STARTUP: indent

* 2005年5月27日  星期五

** 日官称侵略不须道歉小泉急为右翼言论降温

【综合消息】据报道，中日关系再陷低潮之际，有日本高官大放厥词，意图淡化日本的战争侵略罪行。日本厚生劳动省政务官森冈正宏昨声称，战争是国际公约规范下的政治形式，日方毋须为战时罪行道歉。他并指，首相小泉纯一郎参拜靖国神社并无不对，神社内供奉的所谓甲级战犯不是罪人，只是战胜国单方面施加的卷标。
时事通讯社报道，身兼众议员的森冈正宏，昨天在所属的执政自民党会议上，否定日要为战时侵略行为道歉，他说：「战争是政治形态，（日本）是依据国际法规定参战，而士兵是根据个别规条杀人，并不是需要道歉的事情。」

他也为小泉参拜供奉十四名甲级战犯的靖国神社辩护，他指出，所谓「甲级、乙级和丙级战犯」，是远东国际军事法庭所订，该法庭是由美国等战胜国单方面主持，他们自称是维护和平，反对违反人道的罪行，但其实是违法审判。他强调：「不应视战胜者是伸张正义，战败国则是邪恶。」

小泉急为右翼言论降温

他认为参拜神社被视为罪恶的存在是一件遗憾的事，自民党应该将这项事实向全球公布。他说，若自民党在外交上把拜祭甲级战犯视为坏事，「将在未来留下麻烦的根源」。

对于森冈的挑衅言论，内阁官房长官细田博之赶紧澄清，他形容森冈的评论「是对事实的错误诠释，与政府立场不同」，他并强调这是「一位众议员表达自己的想法」。

小泉也为森冈言论降温，他说，他参拜靖国神社，并非向战犯致意，又说日本接受远东国际军事法庭作出的裁决。

森冈是日本右翼政客，去年起出任厚生劳动省政务官，官阶仅次于厚生劳动省副大臣，并两度当众议院议员，前年出任众议院法务委员会理事。上月二十二日，一百六十八名国会议员和代表参拜靖国神社，当中包括三名政务官，森冈是其中一人。此外，就日本政府最快七月将批准日本石油公司勘探东海油气田，中国外交部发言人孔泉昨天表示已向日方提出抗议。

前外相田中真纪子要小泉下台

据香港文汇报报道，此外，有一定支持者的日本前女外相田中真纪子在广播节目中指出：小泉在被问到几时参拜时，总是没有给予确定答复，然后又突然去突然不去，这一做法是缺乏信用，作为日本国民，应该好好考虑，小泉还是否适合继续当首相。还有媒体预测：如此下去，小泉纯一郎官位将难保。不过，如果他下台，可能会让更强硬派的安倍晋三上台。



【时事点评】在东方评论员看来，就在中日关系陷入72年来最低潮时，这个森冈正宏跳出来公开为“甲级战犯”“平反昭雪”，为日本的战争侵略罪行“鸣冤叫曲”、可以说是日本右翼“好走极端”的最新表现。

*** 日本国内到处弥漫的军国主义“死魂灵”的一次大暴露

我们注意到，森冈是日本右翼政客，更是日本政府的高官，从这位高官的嘴里吐出的“远东国际军事法庭.....其实是违法审判.....”的言论，事实是日本国内到处弥漫的军国主义“死魂灵”的一次大暴露。

还有，这位日本右翼政客不是说“他认为参拜神社被视为罪恶的存在是一件遗憾的事，自民党应该将这项事实向全球公布”吗？很好，在我们看来，如果小泉政府还是“一意孤行”，北京倒可以在这方面“配合”这种说法，大可想想办法“协助日本”将“这项所谓事实向全球公布”，那就是，在世界反法西斯战争暨中国人民抗战胜利60周年之际，日本政要竟然公开为法西斯“甲级战犯”翻案，这不能不让人产生疑问，日本究竟要在国际社会扮演一个什么角色？

*** 借助日本炒起来的“入常”问题，北京应该首先将其转化成帮日本“走和平道路”的问题

东方评论员认为，如果是走“和平主义”，那为何急着为“甲级战犯”翻案？如果日本是想走军国主义，那么，日本就不要在那里贼喊捉贼了，因为日本军国主义本身就是东亚、以至世界和平的重大威胁！事实是，“这种认识”本身就是现有国际法的一个重要组成部分。

显然，在日本“是选择和平主义、还是选择军国主义老路”尚不明确的情况下，怎么可能去做一个“负责任的国家”？不是一个负责任的国家，又哪有资格在国际社会“去扮演更重要的角色”呢？显然，日本“入常”问题，北京有责任、也有必要在世界范围内，将其转化成为一个帮助日本“走和平道路”的问题。


*** 不失为一个可以考虑的办法

据说，有国际组织早就有一项动议，建议由相关国家级成一个国际组织、以对日本法西斯在二战争中的所做所为进行“全面、公正的调查”，完成后将“真相和结论”都公诸于世，并以此来解决日本和亚洲国家间始终“认识不一”的日本历史问题。

东方评论员认为，尽管日本的“战争罪行”已经在一系列“国际法”中“定义”得一清二楚，但是，在我们看来，本着帮助日本社会“尽快认清”历史的“良好愿望”，这倒不失为一个可以考虑的办法。然而，据我们所知，中国和其他亚洲国家对“这种建议”倒是颇感兴趣，只是不知这位“口口声声”要将“所谓事实向全球公布”的日本右翼政客和小泉政府，内心里会感兴趣吗？有胆量接受吗？


*** 小泉纯一郎这次倒还显示出了“一点点历史知识”

我们知道，东条英机是第二次世界大战中，与希特勒、墨索里尼齐名的三大法西斯头目之一，是日本军国主义侵略亚洲、侵略中国的头号战争罪犯。

显然，相比森冈这位“说话不经大脑”的日本高官，小泉纯一郎这次倒还显示出了“一点历史知识”，赶快地跑出来为森冈言论降温，并公开地表示“他参拜靖国神社，并非向战犯致意，又说日本接受远东国际军事法庭作出的裁决，东条英机是甲级战犯”。

*** 就在小泉纯一郎“聪明”地做出补救的同时，却一不小心将自己“给卖了”

然而，在我们看来，就在小泉纯一郎“聪明”地做出补救的同时，却一不小心将自己给卖了。众所周知，小泉纯一郎几天前、还在那故弄玄虚地表示“别国不应干涉追悼阵亡者、搞不懂不能参拜靖国神社的原因”。

在东方评论员看来，这位森冈公开所宣称的、“战争是国际公约规范下的政治形式，日方毋须为战时罪行道歉。首相小泉纯一郎参拜靖国神社并无不对，神社内供奉的所谓甲级战犯不是罪人，只是战胜国单方面施加的卷标”等一系列“辩解”的话，事实上却是小泉“故弄玄虚”的最好理由。

可是，“搞不懂不能参拜靖国神社的原因”的小泉纯一郎、为何在第一时间里、就急着与这一套“慷慨激昂的辩解”撇清关系呢？显然，小泉纯一郎这是在自己打自己的耳刮子：这种迫不及待的撇清正好说明、他对“靖国神社里供奉的'鬼'、都是些什么玩意儿，有罪无罪”心里是非常有数的、之前之所以在那里“故弄玄虚”，不过是在“揣着明白装糊涂”而已！

*** “翻案”行径、显然“深藏着不可告人的企图心”

首席评论员指出，我们不清楚这个森冈今天散布的“这套谬论”是否果真如日本内阁官房长官细田博之所澄清的那样，“是对事实的错误诠释，与政府立场不同”，是“一位众议员表达自己的想法”。

但是，在我们看来，就“事实和后果”而言，这套否定“远东国际军事法庭”、这一将东条英机等日本十四名战犯判决为甲级战犯的历史性审判是“违法审判”的“翻案”行径、显然“深藏着不可告人的企图心”。

东方评论员认为，几年来，日本政府之所以一再地、在供有甲级战犯的“靖国神社”里“打转转”、最终目的就是要为侵略战争翻案，而翻案的真实目的、就在于彻底推翻当年远东国际军事法庭审判--东京审判的结果，从而为其推脱战争罪责寻找借口，为创造当年“大日本帝国”之辉煌的日本军国主义“正名”。


*** 森冈今天散布的“这套谬论”其实是一种“极其危险的信号”

因此，在我们看来，森冈今天散布的“这套谬论”其实是一种“极其危险的信号”，也就是说，日本右翼再次展现了其“争功近利、好走极端”的本性，在“靖国神社”这个突破中国压力的“突破口”、久攻不破的情况下，已经迫不及待地将“最终目标”直接抬了出来。

对此，首席评论员就指出，日本右翼这次“政治冒险”，不仅是对亚洲国家感情的挑畔，更是对整个的现行“国际法”的挑战。在我们看来，日本右翼把“东京审判”说成是“违法的审判”，这并不是什么新闻，很早之前，就有“黑暗的审判”这一说。


*** “翻案”本身，就是想推翻“现行的、日本必须严格遵守的国际法”

显然，不论是今天的“违法审判”、还是以前的“黑暗的审判”，其主要目的都是推翻“东京审判”对日本军国主义、和发动侵略战争的甲级战犯罪行之“历史定论”。因此，东方评论员认为，“翻案”本身，就是想推翻“现行的、日本必须严格遵守的国际法”对日本国家性质的定位，这也就直接涉及到日本是否继续遵守它所接受的《开罗宣言》和《波茨坦公告》的有关条款规定，直接关系到“日本今后是走和平发展道路、还是重走军国主义”的大问题。


*** “翻案”本身，也是给“台独”“炮制理论依据”

1943年、美、苏、英在《开罗宣言》中宣布：“三国之宗旨在剥夺日本自1914年第一次世界大战开始以后在太平洋所夺得的或占领之一切岛屿，在使日本所窃取于中国之领土，例如满洲、台湾、澎湖群岛等，归还中华民国(即中国)。

1945年，纳粹德国无条件投降。其后，同盟国开始集中力量对日作战，并就结束对日作战的条件和对日战后处理方针达成一致，并征得中国同意，共同发布敦促日本无条件投降的《波茨坦公告》，就是在这一年里，苏联于对日宣战、苏联红军以绝对优势兵力从中国东北向日本关东军发起总攻，也是在这一年里，美国向日本本土扔了两颗原子弹，最后日本天皇不得不在接受《波茨坦公告》的诏书上签字，宣布日本无条件投降。

东方评论员认为，《开罗宣言》、《波茨坦公告》构成战后日本必须严格遵守的国际法基准。其中，《开罗宣言》以国际法文件的形式谴责了日本对中国领土的窃取，承认了台湾等被占土地是中国的固有领土，并规定日本必须将其归还中国。

首席评论员指出，《波茨坦公告》对日本战后处理问题和战后的中日关系具有极其重要的意义。而72年中日两国签署中日邦交正常化联合声明、日方在联合声明中就明确表示：“坚持遵循波茨坦公告第八条的立场”，这等于重申日本已将台湾归还中国。而在78年中日和平友好条约又确认了中日双方都要遵守《中日联合声明》，这等于以双边条约的国际法形式再度确认了日本从中国窃取的台湾等归还中国的立场。

此外，《波茨坦公告》第六条规定：“欺骗及错误领导日本人民使其妄图征服世界之威权及势力，必须永久剔除。”第十条规定：“对于战争人犯，包括虐待吾人俘虏者在内，将处以法律之严厉制裁。”它强调必须铲除日本军国主义、穷兵黩武主义，追究战犯的罪责。

事实上，正是根据这一规定，1946年到1948年间，远东军事法庭对东条英机等甲级战犯进行了具有历史意义的审判，即东京审判。

显然，东方评论员认为，日本右翼这种“东京审判”是“违法审判”的言论，从世界的角度上看，这是“企图颠覆”直到今天为止、都在限制日本走军国主义老路的“国际法”，如果从台湾问题上看，日本右翼的这一叫嚣，从日本在台湾势力的总代表--李登辉身上就能找到“对应点”，这就是“台独”分子李登辉一再鼓噪的所谓战后“台湾归属未定论”。不难看出，“翻案”本身，也是给“台独”“炮制理论依据”。


*** 小泉“否定”森冈，根本就是周瑜打黄盖

在我们看来，值得警惕的是，尽管小泉纯一郎立刻跑出来表示“日本接受远东国际军事法庭作出的裁决”，然而，直到现在为止，东方评论员注意到，日本执政的自民党党内，依然有重量级人物为之辩解。

不难看出，森冈作为日本在任高官，突然抛出这种言论、根本就不是什么个人言论，这应被视作小泉政府对吴仪提前结束访问行程的一种“试探性报复”，在东方评论员看来，这根本就是在警告中国、日本手中还有“台湾归属未定论”这张牌可打。显然，森冈和小泉、这是在那里唱双簧，小泉“否定”森冈，根本就是周瑜打黄盖：一个愿打一个愿挨！

在东方评论员看来，日本一些人鼓吹的所谓战后“台湾归属未定论”是根本站不住脚的，根本就是缺乏法律依据的“杜撰”，因此，在东方评论员看来，这一“公开的威胁”，暗含着日本政府又一次严重挑畔中国主权的“极端行为”，以超级，北京当然会表现出强烈地反应。

在对此进行进一步的解读之前，我们先来看看中国政府的明确态度，之后，我们将继续这个话题。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 外交部发言人孔泉就日本政要为日二战战犯开脱罪责答记者问

【外交部网站消息】下面是外交部发言人孔泉就日本政要为日二战战犯开脱罪责答记者问：
　　问：5月26、27日，日本厚生劳动省政务官森冈正宏和自民党总务会长久间章生相继发表谈话，公然否定远东国际军事法庭审判结果，为日本二战甲级战犯开脱罪责。请问中方对此有何评论？

　　答：日本政要发表的荒谬言论，是对国际正义和人类良知的公然挑衅，是对所有遭受日本军国主义野蛮侵略深重灾难的受害国人民感情的严重伤害。中国政府和人民对此表示强烈愤慨，并予以严厉谴责。

　　以东条英机为首的甲级战犯双手沾满亚洲国家人民和世界人民的鲜血，是对世界和平和人道犯下滔天罪行的历史罪人。远东国际军事法庭的审判结果，是构成战后国际政治基础的重要组成部分，任何企图推翻这一审判结果的行径都是不可能得逞的。

　　必须指出的是，日本政要此次发表荒谬言论不是孤立的，也不是偶然的。这不能不让人产生一个疑问，就是日本能否在国际社会扮演一个负责任的角色？我们强烈要求日方以实际行动体现反省侵略历史的承诺，真正取信于国际社会特别是亚洲邻国人民。



【时事点评】我们注意到，孔泉非常清楚地指出，“日本政要此次发表荒谬言论不是孤立的，也不是偶然的”，的确，通过我们前面的讨论，不难看出，孔泉的“这个结论”是有根有据，容不得“翻案”。

*** 孔泉一把就戳到了日本右翼“心痛”之所在

另外，孔泉也强调，“远东国际军事法庭的审判结果，是构成战后国际政治基础的重要组成部分”，显然，通过上面的解读，我们应该也能领会发言人“点出”的这个“国际政治基础工、任何企图推翻这一审判结果的行径都是不可能得逞的”、其实就是一把就戳到了日本右翼“心痛”之所在。

在东方评论员看来，中日关系之所以出现目前的“复杂局面”，有各种原因，其中一个“主导性因素”是中日力量对比的“根本变化”：即，中日力量对比正在不断朝对中国有利的方向发展，这是客观事实。可以说，只要中国“继续强大”，日本对华政策的这一消极面就不能完全消失。

事实上，我们认为，日本右翼不仅恐惧这一客观事实，并正在夸大、企图利用这一客观事实，操纵日本民族情绪、从而“瞄着”中美战略对峙的战略时机、在中国还没有正式成为亚洲领导者之前、客观需要一个良好的“中日关系”、去形成东亚经济一体化的“愿望”，以“这种愿望”“做人质”，赌中国“不能承担中日关系全面破裂带来的损失”，从而“幻想”中国在最后一刻从历史问题上后退，从而给日本从上述一系列“国际法”的限制中“逃”出来打开突破口。

在东方评论员看来，孔泉所表现出来的强硬立场，再次宣示了“中国在原则立场上是不会让步的”。因此，我们认为，只要日本不去碰这些原则立场、不在中国的核心利益上挑起争端，那么，中国是可以让其“长期化”的，然而，问题是日本右翼势力却想“一夜间”就突破这些原则，从而立刻达到自己的战略目的。

事实上，在中日之间经过上一次日本外相访华失败的“摊牌”之后，对日本的政界和商界的冲击都是非常大的，东方评论员认为，北京通过上一次“摊牌”式较量，除了成功地“迫使小泉暂时道歉”之外，其实还成功地拿到了小泉政府和日本社会的底牌，那就是：小泉政府和经济界都认为“不能承受一个破裂的中日关系”。

*** “几近破裂”的中日关系、好比是逆水行舟、终将“不进则退”

因此，首席评论员就认为，北京这次让吴仪提前回国，将小泉纯一郎的“老窝”里、当着日本社会的面将他“晾”了一回，这本身又是一次“摊牌”，就如我们之前所说的那样，由于日本在欧美眼里“没有能力”成为世界一极、也没有能力在经济之外去挑战他们自己，而在亚洲国家眼里、日本也没有能力成为亚洲的领导者，因此，在东方评论员看来，这种“几近破裂”的中日关系、好比是逆水行舟、终将“不进则退”。

显然，北京这是在迫使日本在“维持一个可以正常交往的中日关系、以保持其独立的经济政策”和“接受一个不正常的、在各个方面完全受控于美国的美日关系”之间“做出明确的选择”。


*** 美国的企图心

在我们看来，就在北京让日本做出选择的同时，华盛顿又何尝不是？

首席评论员指出，美国对日本的政策历来是“控制加利用”，是控制多点，还是利用多点，则视美国战略需要而定。现在，美国的全球战略以欧亚大陆地缘战略为基点，其特点就是“中东、中亚是重点”，因此，东线只能靠日本，让华盛顿决策层难受的是，它另两个盟友澳大利亚和韩国、现在都在与美国独霸全球的战略“保持距离”，不仅如此，还先后明确地表示“不会插手台湾问题”，如此一来，在华盛顿的手中，只有这个日本可以利用。

在我们看来，华盛顿是“控制”的一面开始松手，想用日本来制约北京，以策应其中东、中亚战略，而日本又想借美国的势，搭顺风车，在美国的羽翼下进一步壮大自己，两者一拍即合。东方评论员认为，美国松手“控制”的结果、就是美国的“新帝国政策”与日本的“新军国主义”倾向“正在合流”。

*** 破裂中日关系、是美国进这一步控制、并最大限度利用日本政治、军事、经济资源的“前提”

然而，对美国人而言，现成“松手”“控制”是迫不得已，因为中日双方经济结合得太紧密了，所以、直到今天，美国“对日本的利用效果”也非常有限、其中，甚至于还“一度在”朝核问题、东亚核竞赛问题上“遭日本的要挟”。

显然，在华盛顿决策层看来，在日本经济正依托中国大陆与美国经济竞争的情况下，在关键时刻、日本又怎么可能对自己唯命是从？

在东方评论员看来，破裂中日关系、动摇中日间的“经济配合”、是美国进这一步控制、并最大限度利用日本政治、军事、经济资源的前提。东方评论员，为了将来“更紧”地“控制”。因此，一直以来，华盛顿在挑唆日本挑畔中国的问题上，非常有企图心，在东方评论员看来，美国的企图心就是在竭尽全力、想千方百计地将目前的中日关系“给彻底破裂掉”。

*** 盛顿决策层为了破裂“中日关系”、显然也选择了一个突破口

根据我们的观察，华盛顿决策层在实现这一企图心的时候，显然也选择了一个突破口，这就是中日的东海主权之争。

比起钓鱼岛之争，华盛顿的战略家们显然知道东海主权之争更加有利用价值。早在去年，也就是在赖斯还是国家安全顾问时、在她7月访华前后，美国就开始挑唆日本了。为了“配合”赖斯访华，我们注意到，美国传统基金会专家当时发表了一份报告，报告公开称、中国的行动（开发春晓油气田、中国的海洋调查船和海军舰艇最近多次在该海域维护我主权的行动）是对日本领海和资源的侵犯，是挑战日美同盟的冒险活动。

值得注意的是，报告最后还提醒美国政府说，为遏制中国在海洋上的野心，为坚持美日同盟，应该支持日本对尖阁群岛（即钓鱼岛及其附属岛屿）的领有权，并让美军参加海上自卫队在东海的巡逻行动。

*** 美国不敢让整个东亚安全体系的“立刻崩塌”


在东方评论员看来，美国民间专家可以这样“叫”，只是在目前、华盛顿决策层是不敢这样做的，为什么，很简单，一旦美国的军舰出现在中国东海海域，或者宣布支持日本对钓鱼岛的主权，就意味着整个东亚安全体系的将不可避免地立刻崩塌。

显然，中国的一个最可能的反应、就是选择时机、提前解决台湾这个“国内问题”、之后，再来处理东海争端这个国际问题。这样一来，也就意味着美国立刻就得面对两种选择，要么是放弃台湾、要么就是军事干预台海，不难看出，一个破裂的中美关系，带给美国的两种选择“都是最糟糕的结果”。


*** 华盛顿是不会让中美关系“先于”中日关系前破裂的。

在东方评论员看来，非常清楚“破裂的中美关系”会给自己“带来多么大麻烦”的华盛顿，自然也非常明白将中日关系“搞破”能给自己“带来多么大的好处”。

可以肯定的是，没有一个良好的中日关系借以腾挪的日本，将会在政治、军事、这些本来就受到美国严密控制的方向上、进一步失去自主决策权。

还有，进一步失去政治、军事自主决策权的日本，在失去了一个良好的中日关系、失去中国经济政策上的配合之后，是很难单纯地、用其所谓“世界第二的经济实力”、去保护它现在仍有相当独立性的经济政策、和有非常强竞争力的产业结构的。

*** 日本的许多大企业经营有一个明显特点

东方经济评论员就认为，现在，日本的许多大企业经营有一个明显特点，那就是，一方面，在通过中国这个大市场的进行技术或产品的“出口中转”、既可以与欧美企业争夺中国市场份额、又可以立足于中国、以“中国制造”的名义、将中低端产品出口到欧美，赚取利润。

而另一方面，这些日本企业又将技术层次高的核心技术和高端产品全部放在日本国内生产、由日本直接出口到欧美去与欧美企业竞争。也就是说，日本企业就与欧美的许多跨国企业一样，从中国市场赚取的利润、占了其全球利润中“最重的一块”。也正是这最重的一块，促使“欧美日”企业都在将中国将为其全球战略布局最重要的一部分来加以经营的。


*** 早先叫嚷着“人民币升值”最凶的日本、这次没有“随声附和”

另外，我们注意到，就在欧美这次异口同声要求人民币升值的时候，早先叫嚷着“人民币升值”最凶的日本、这次不仅没有随声附和，反而由其央行行长亲自出面，罕见地表示“人民币升值无助于改变世界贸易格局”。

东方经济评论员认为，这可不是日本人“良心的发现”，在我们看来，从昨天韩国央行宣布与中国、日本央行签暑了金额庞大的（分别是40亿、30亿美元）货币互换协议的动作来看，不论是日本、还是韩国、表面上看，似乎都意识到了人民币“必然升值”、从而将给自己的货币和经济带来的巨大打击，也都在“未雨”“筹谋”。

*** “懂行的美国经济管理层”一再强调这么一层意思

在这里，我们强调这些的目的，不外乎是想说明一点，那就是，在今天、中国的经济政策、货币政策是如此地重要，重要到了美联储主席格林斯潘和美国财长、这些“懂行的美国经济管理层”一再强调这么一层意思，既“人民币升值对美国不利”。

事实上，就如我们在昨天的《东方时代国际投资》之国际金融部分所分析的那样，既然中国决策层不愿意让人民币升值，而“管理美国的人”也不愿意让人民币升值，而欧盟和美国一样，自己的经济与中国的经济（尽管其中包含有日本的产品）更多的是互补、并没有什么激烈竞争，那么问题也许就简单了，即、让日元先于人民币之前升值、从而进一步挤压日本正在赶超欧美的企业、如IT行业的竞争力、或者是否会再次让美国强硬敲打日本的传统优势产业、如美国国内正在抱怨的日本汽车产业，也就未为可知了！

显然，时事评论员们认为，不论是欧洲人、还是美国人，心里都清楚，在经济方面，在目前日本是最需要打击的对象。由此可见，特别是对美国人而言，一个“破裂的中日关系”首先给日本带来的麻烦、恰恰就是日本现在凭借中国市场、而得以“最为自由的”经济政策。

*** 日本是否会再次遭遇一次“广场协议”呢？

因此，东方评论员认为，在日本右翼进一步挑畔的关键时候，北京的对日政策恐怕是“除了强硬、还是强硬”。在我们看来，中国政府很可能首先就在经济方面给日本一个教训，从而给欧美逼迫日元先行升值提供机会。显然，相比中国维持货币稳定的决心而言，敲打日本要容易得多。何况，欧美心里都清楚，让日元升值，比压人民币升值对欧美本国经济、对世界经济的冲击都要小得多。

这样，东方经济评论员就认为，可以作一个问题提出来的是：那就是，在经济政策上，日本是否会再次遭遇如80年代、欧美联手强压日本改变货币政策的“广场协议”呢？起码在我们看来，一个破裂的中日关系，将使“这种可能性”急剧地增加！

如果我们现在回过头去看“中日韩”的货币互换协议，以及日本央行罕见地为人民币“说好话”、这中间的“味道”也就不太一样了。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
