# -*- org -*-

# Time-stamp: <2011-08-02 22:43:52 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

#+STARTUP: indent

*  2005年5月23日 星期一

** 胡锦涛发出警告称小泉必须停止参拜靖国神社

【凤凰卫视5月23日消息】据共同社报导，中国国家主席胡锦涛廿二日向前往北京访问的日本国会议员发出警告说，日本领导人必须停止参拜靖国神社。

胡锦涛还向日本自民党干事长武部勤等国会议员批评日本处理第二次世界大战历史的态度以及日本对台湾的政策，胡锦涛警告，中日关系很可能一瞬间就毁了。

ＮＨＫ报导，胡锦涛对日本国会议员表示：「日本领导人最近一直前往供奉甲级战犯的靖国神社参拜，这是我们不乐见到的。」

中日关系最近受到一系列事件困扰，包括日本首相小泉纯一郎每年前往靖国神社参拜。

谈到中日关系，胡锦涛说：「我们举个例子，构建我们的双边关系，就如构建一面墙，砖必须一块块叠上去，但一面墙很可能一瞬间就毁了。」

武部勤答复胡锦涛说，他希望中国能够了解，自从第二次世界大战结束后，日本已采取坚定步骤，朝和平国家路线迈进。

共同社报导，胡锦涛表示，中日关系友好符合两国基本利益。

胡锦涛对日本的批判有三方面：日本领导人每年都前往靖国神社参拜，日本对台湾的政策，日本历史教科书粉饰第二次世界大战罪行。

由于日本文部省审核通过粉饰二战罪行的教科书，加上日本争取联合国安全理事会常任理事国席次，上月中国大陆各地爆发反日示威。

此外，今年二月日本和美国将「透过对话和平解决台湾海峡两岸的问题」列为战略优先，北京当局反应也十分激烈。

小泉纯一郎最近一次前往靖国神社参拜是在二○○四年一月。小泉一再辩称，他前往靖国神社主要是祭拜日本在战争期间的死难者，并祈求和平





【时事点评】我们注意到,胡锦涛主席昨天（22日）在接见日本执政两党干事长时，对当前的中日关系打了个比喻，原文是，“我们举个例子，构建我们的双边关系，就如构建一面墙，砖必须一块块叠上去，但一面墙很可能一瞬间就毁了。”

*** 中日关系已经到了“一推就倒”的紧要关头

显然，在东方评论员看来，胡锦涛主席打的这个“砌墙”的比方，首先，是非常形象地描述了中日关系的“来之不易”，其其次，也非常形象地指出了中日关系的“已经到了“最危险的时候”，到了“一推就倒”的紧要关头。

然而，结合前日小泉纯一郎“首次”表示“是以个人身份参拜”所做的“所谓姿态”、中国官方显然没有在第一时间给出激烈的回应，而是继续让吴仪在日本演讲、并举行多次座谈，与尽可能多的、日本方方面面的人沟通、交流。

就在国务院副总理吴仪在日本做日本社会、经济界工作的同时，我们再来看看小泉纯一郎除了要“外国不要干涉”他以“个人身份参拜靖国神社”、让石原慎太郎到“冲之鸟”做秀之外，他还做了些什么。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 日将会向中国提官方发展援助

【东京消息】据日本《产经新闻》报道，如果北京使用日本新干线或子弹火车，作为连接北京及上海的高速火车，日本将会向中国提供官方发展援助。日本于本月初已向中国提出有关计划。

但报道并没有指出贷款金额及有关条款。

日本的政治人士及商界领袖均积极游说其中国相关人士以争取有关合同。

报道引述一名外交部高级官员指称，如果是次交易成功，将会是日本向中国提供的最后一笔大额日圆贷款，因为日本已决定在二○○八年北京举办奥运前，终止中国境内援助贷款。

** 小泉将宣布开放中国免签证

【东京消息】根据日本媒体的报导，日本首相小泉纯一郎明天(23日)与中国大陆副总理吴仪会面时，将宣布全面对中国大陆旅客开放旅游免签证的措施，不再仅限于爱知博览会期间。

据了解，小泉首相将在和吴仪会面时，正式转达这项善意，好改善僵持已久的中日关系。

不过，小泉应也会强调，假如不时发生中国旅客藉观光旅游而留在日本非法打工的话，这项措施也有可能取消。

事实上，日本从2000年9月就开放北京，上海和广东三地旅客旅游免签证，去年又扩大为包括山东等四省也都免签证，如今则可能会全面开放。





【时事点评】在上周五的点评中，东方评论员曾经说过，吴仪提出的“六点建议”、以及同时所做的这一番讲话，实际上可以理解为中国在做日本社会的工作，特别是日本经济界的工作。


*** 小泉政府“放风”将提出两个“将要”的目的

因此，我们从这个角度再来看小泉政府“放风”将提出的这两个“将要”，也不难发现，日本保守势力也是在“针尖对麦芒”，不论是想以贷款换得日本企业眼红的京泸高铁项目、还是所谓的“将宣布全面对中国大陆旅客开放旅游免签证”，事实上、这也是在针对吴仪带着“六点建议”做日本社会、日本经济界工作、在“反向地”做着日本经济界的工作。

东方评论员认为，显然，与吴仪所提及的建立、有利于双方和整个亚洲经济发展的中日自由贸易区、或者类似“欧洲煤钢联盟”的中日“能源联盟”相比，小泉纯一郎旨在为日本企业揽活的两个“将要”，显得“小心眼太多”，也显得格局“小了太多”。

*** 在日本右翼重压之下的小泉、做得“毫无诚意”

另外，还值得注意的是，就在小泉纯一郎准备了这些个“将要”的同时，又不停在在参拜靖国神社等历史问题上大放橛词，并充许东京都知事石原慎太郎在“冲之鸟”做秀，还抛出在钓鱼岛和“冲之鸟岛”登记户籍的消息。

不难看出，这与北京让吴仪出访日本、摆出愿意以小泉纯一郎在亚加达道歉为契机，试探能否以“经热”捂热中日“政冷”的努力相比，小泉纯一郎内心虽然也急着改善中日关系，但在日本右翼重压之下、仍在具体改善中日关系的问题上，做得“毫无诚意”。

我们知道，小泉纯一郎是在上月22日于印尼、就日本在二战时侵略亚洲各国公开表示“深刻反省和由衷道歉”的，之后，他才得以见到胡锦涛主席，胡锦涛在与小泉的见面中，双方都表示“高度重视中日关系”，都“同意暂不争论历史教科书、靖国神社等问题”，特别是胡锦涛当时就提出的“五点改善中日关系的建议”中，就包括要求日方“把对侵略战争的反省落到实处”。

*** 中日交流、暂时失去了政治基础

显然，小泉纯一郎是“好了伤疤忘记了痛”，在参拜供有甲级战犯的靖国神社问题上“再次”态度顽固，在“公开道歉”仅20天之后，又捡起了强硬态度、一如先前，这当然令中日交流、暂时失去了政治基础。

东方评论员认为，从让日本外相访华失败、从而迫使小泉道歉的整个过程来看，充分说明在与日方打交道时，原则立场是绝对不能软弱的。

特别是在历史与台湾这两个“大是大非”问题上，在我们看来，对待日本右翼的挑畔，只有采取强硬措施才能压制他们的气焰，也才能让日本社会和经济界“正视”中方对这些“原则问题”的坚定立场，也只有这样，北京才能更好地去争取日本社会和经济界、更好地去打击日本右翼的政治企图。

*** 我们虽然也有点惊讶，但却“非常欣赏”

因此，在东方评论员看来，在胡锦涛主席强硬批评日本政府之后，我们听到吴仪取消与小泉见面的消息，对此强硬举措，我们虽然也有点惊讶，但却“非常欣赏”。下面，我们先来看看相关报道，之后，时事评论员将继续今天的日本部分。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 吴仪取消今日与日首相小泉的会面提前回国

【东京消息】据报道，日本外务省表示，正在日本访问的中国国务院副总理吴仪原定今日和日本首相小泉纯一郎的会面，但会面已经被取消。

日本内阁官房长官细田博之表示，吴仪以国内有要事为理由，要求取消会晤，并会提前在下午离开日本回国。但中方表明，取消会晤和小泉纯一郎参拜靖国神社无关。

吴仪原定计划访问日本八天，明日才结束行程。

日本主要媒体均认为吴仪不见小泉因参拜问题

据报道，关于中国副总理吴仪与日本首相小泉原定今天（23日）下午的会见突然取消一事，中国宣布的理由是吴仪有“国内紧急公务”。但日本主要媒体均认为，是小泉坚持要参拜靖国神社，导致了如此高级的会谈在即将开始之际极为罕见地被中止。

据朝日新闻、读卖新闻报道，日本官房长官细田博之在今天上午的记者会上说，接中方通知，吴仪副总理因为“国内紧急公务”而取消原定当天下午4点过后与小泉首相会面，与日本民主党冈田代表的会见也将取消，吴仪将于下午回国。

据悉，吴仪5月17日到访日本，参加爱知世博会的中国馆日等活动。她原先预定于24日离日回国。

另外，小泉对记者表示了他的不满，称“不想会面的会面是不必要的”。

媒体认为此次会谈被取消，极有可能与小泉坚持参拜靖国神社并声称“其它国家不应该干涉”的言论有关。但小泉当天对于记者类似的提问，却回答说“不知道”。他还坚持：“我（参拜）至今为止没有造成任何坏影响，为什么（会面）要取消呢？我一直说，无论什么时候都希望会面的”。

细田在记者会上说，“本来（会见）是中日关系改善的一个好机会，十分可惜。”对于会见取消是否因靖国神社问题而受到影响（小泉16日在日本众议院预算委员会会议上，曾表达了将继续参拜靖国神社的意向），他以“不那样考虑”之语加以否定。而据日本外务省有关人员透露，中国提出取消会见的理由时也说明“不是因为靖国神社”。

原定双方在会见时，要讨论有关扩大中国团体游客签证发放地区范围的议题。细田说，“日中双方的负责人已在充分地讨论。国民层级的交流对于互相理解是非常有用的”，（日本）仍将按照既定的方正实施。

吴仪今天上午出席了在东京举行的一个讨论会以及由日本经团联主办的午餐会。在午餐会上，她阐述说：“中日两国一起努力致力于关系发展，是至关重要的。”

另据每日新闻报道，有日本政府有关人员表示，中日高层会见的取消，确是由于参拜靖国神社问题造成的。这位官员说：“如果吴副总理在会谈时提出靖国神社问题，小泉首相会不得不强硬地提出这是‘干涉日本内政’。这个意思已经向中国方面转达，这可能是会谈取消的理由。不过最终还是中方的缘故。”



【时事点评】我们注意到，中国宣布的理由是吴仪有“国内紧急公务”，且中国外交官员立刻表示“取消会晤和小泉纯一郎参拜靖国神社无关”、倒是日本官员偏偏往靖国神社上面扯，这是为何呢？

*** 中国外交官员的说法非常有意思，可以说是“话中套话”

在东方评论员看来，中国外交官员的这种说法非常有意思，可以说是“话中套话”：第一，我们认为，这本来就是在“此地无银三佰两”，众所周知，中日高层没有相互交流，可以说是由来已久，其原因就是靖国神社问题。因此，在我们看来，北京越是说与靖国神社无关，就越是在强调与之“太有关系”了；

这还不算，中国方面的“否认”，除了有意要“此地无银三佰两”之外，恐怕就是要为日后将“中日高层对话中断的原因”强调成“与小泉纯一郎会面没有任何效果”做好了铺垫、从而去“堵”日本所谓“知华派”和中日友好人士、日本经济界人士的嘴。

*** 这番“气话”与其身份“非常地不相称”

我们注意到，尽管小泉在第一时间里，就对记者表示了他的不满，并称“不想会面的会面是不必要的”。然而，在东方评论员看来，如果小泉先生果真如此认为，那么我们就不明白他在4月22日，为何千方百计地找机会与胡锦涛主席见面？

显然，如果他没有患健忘症的话，他就应该清楚地记得，当时可是满世界的人都知道，是胡锦涛主席不想见他，可为何这位日本首相当时就没有“不想会面的会面是不必要的”的骨气呢？

显然，在东方评论员看来，小泉纯一郎在这种时候说这些话，恐怕只能是“气话”，这也说明了一点，那就是作为一个国家的首脑人物，他说的这番“气话”与其身份“非常地不相称”。

*** 小泉纯一郎、恐怕还没有弄明白中国此举的真正意思

另外，我们也注意到，小泉纯一郎在强硬之余，又表示：“我（参拜）至今为止没有造成任何坏影响，为什么（会面）要取消呢？我一直说，无论什么时候都希望会面的、只要中方提出来”。

不难看出，他在说出诸如“不想会面的会面是不必要的”这种强硬的话之后，又摆出了一副“随时恭候”的高姿态来、然而，在东方评论员看来，没有忘记“摆高姿态”的小泉纯一郎、恐怕还没有弄明白中国此举的真正意思.



*** 北京给出了“中日双方的所有高层互动，都将无限期中止”的信号

东方评论员认为，中国以吴仪有“国内紧急公务”为由头将吴仪调回的，在我们看来，吴仪是位主管经济的副总理，也就是说她的上面还有总理等“众多领导”在国内掌握大局。何况，那位非常强硬的日本外相、町村信孝不是在前些天还说过“中日关系比什么都重要”的话吗？的确，在东方评论员看来，中日关系虽然不是比什么都重要，但的确很重要，因此，北京在小泉纯一郎道歉之后、愿意让自己的副总理前去表达改善中日关系的愿望，愿意做出自己的努力。

由此可见，专门为表达愿望、并去日本“做工作”的吴仪副总理，这几天里，在国内是绝不可能有什么比“顺利完成访问行程”更加重要之公务的了。

针对吴仪在临见小泉纯一郎之前才“突然取消行程”，首席评论员就指出，如此高级别的会谈，在即将开始之际被中止，是极为罕见的，因此，在我们看来，这分明是继昨天胡锦涛主席以“砌墙难”、“毁墙易”为比喻、“口头”严厉警告日本、指出中日关系“有可能毁于一旦”之后，中国将“口头”严重警告“立刻付诸行动”的强硬举措。

东方评论员认为，此举如实展现了中国政府的、在历史、台湾、教科书这些原则问题上绝不妥协的强硬态度，而且、更为重要的是，此举分明也正式给出了“中日双方的所有高层互动，都将无限期中止”的信号。

*** 北京已经强硬地关上了与小泉政府“对话”的大门

在我们看来，目前这种“几近破裂”的中日关系、暂时是靠着“经热”维持着的，然而，在中日之间经过一次日本外相访华失败的“摊牌”之后，许多观察人士都相信，北京是不会因为经济利益而牺牲政治原则、国家安全的。

在东方评论员看来，显然，没有忘记在对着日本社会“摆高姿态”的小泉纯一郎、恐怕还没有弄明白中国此举的真正意思，那就是，北京已经强硬地关上了与小泉政府“对话”的大门、而将促进“中日关系”改善的“日本部分”、留给了与日本右翼相比，“更能面对现实”的日本社会、日本经济界。


*** 吴仪这次出访的意义何在？

首席评论员指出，吴仪这次出访，实际上是代替国务院总理温家宝访日，显示这次出访的定位不是两国最高层的会面，也预示这次只是一个尝试，是北京在小泉“道歉”之后、试探中日关系现在“是否有修补的基础”。

期间，东方评论员“非常留意”吴仪在日本曾经针对媒体提问说过这么一句话：即，她与小泉首相的见面，就是为了将胡锦涛主席在4月22日于印尼雅加达会晤时达成的“五点主张”落在实处。

在我们看来，吴仪此次借参加世博会中国馆开馆仪式之机，到日本可以说有三个目的，第一就是摆明中国的“开放态度”，那就是愿意搞好中日关系的；第二个目的，就是我们之前已经详细分析过的、北京此举是在全力“做日本社会、特别是日本经济界的工作“，第三，就是敦促小泉将他见胡锦涛时达成的共识“落在实处”。

*** 吴仪在日本的发言时都发现，吴仪主讲的就是经济问题

因此，东方评论员注意到，期间不论小泉纯一郎和其他日本右翼势力如何搞小动作，我们在处处留意吴仪在日本的发言时都发现，吴仪主讲的就是经济问题、在面对日本社会、经济界“大打经济牌”、大送胡萝卜。

相反在政治导面上着墨不多，除了今天上午的态度有些严厉之外，可以说非常温和，只是一味地在强调胡锦涛的“五点主张”可以说是到一地说一地，每次演讲是必提“五点主张”。



*** 前面两个目的只要“中国认真地做了”，就会起到效果

东方评论员认为，从吴仪多日来在日本所做的演讲、与日本政界、经济界重要人士的多轮座谈来看，北京这次让吴仪访日、对日本社会“做工作”的目的已经达到。在我们看来，在这个时候，针对日本社会、特别是与中国联系紧密的日本经济界多沟通，是非常有战略意义的、着眼于下一步、争取主动权的工作。

显然，前面两个目的只要“中国认真地做了”，就会起到效果。在东方评论员看来，不论是主张中日建立自由贸易区，还是建立类似有效解决欧洲国家相互竞争的“欧洲钢煤联盟”相类似的、旨在解决中日能源竞争的“能源联盟”，至于是包括“中日韩”在内的、东亚经济一体化、事实上都是有很好的经济基础的建议。据我们了解，日本的许多经济界人士对这些建议“都听进去了”。

非常清楚，日本一旦走上融入东亚经济一体化的道路，也就等于挖掉了日本右翼的生存根基，这就有如“两岸三通”也将彻底铲除“台独”势力的生存环境一样。

显然，直到最后一刻，吴仪还在向日本社会、日本经济界做工作，据报道，就在今天上午，吴仪准备离开东京之前、还在举行最后一场演讲。有消息说，也是在这个时候，中国才通知日本方面，说吴仪有“国内紧急公务”、并“突然取消与小泉的会面的”。

在我们看来，中日双方在交换看法时，日本对“五点主张”的态度、肯定是“交换看法”的核心内容。现在、吴仪在行程进行到最后一项时“突然中断”，这本身就是在强调：既然你小泉没有诚意将他自己、在好不容易见到胡锦涛主席时所达成的共识“落在实处”，因此，“类似的见面”又有何意义？

*** 中国也已经为“立刻就会有”的“经济动作”打下了基础

如此一来，中国也已经为立刻就会有的“经济动作”打下了基础。在东方评论员看来，吴仪带去的“六点建议”几乎是“纯经济性的”，这不仅是“共同发财的建议书”，也是一颗颗的胡萝卜，显然，这一纸“共同发财的建议书”、一颗颗的胡萝卜能否“兑现”，就在于日本政府的“政治取向”了，我们相信，吴仪带去的这些“胡萝卜”、在中日政治关系有可能毁于一旦的情况下，是不可能兑现的。

不要忘记了，欧美企业也盯着这些东西，一旦中日之间不能在经济上联系得更紧密一点，反而要因政治关系而更加疏远了一点，那么、在世界范围内与日本企业竞争的欧美企业、就会找到许多机会去抢夺日本企业的市场。这中间，中国政府首先就可以可以在经济政策上、让日本经济界“感受到难受”。

显然，在东方评论员看来，既然日本政府不敢要这些“胡萝卜”，那么，中国只好再次举起“摊牌”式的大棒，结果在日本本土上、演化出“老娘不见你小泉了”的强硬画面、倒也是非常合理的。

*** 如何让日本社会、经济界真正感受到“政冷”导致“经冷”的“剧痛”

在东方评论员看来，事情到了这一步，说明日本右翼的所做所为并没有让日本社会感到“剧痛”。因此，对北京而言，“现成的办法”就有一个，只要在经济政策上去影响日本企业在中国、甚至亚洲的经济布局，从而让日本的一些主导企业在着眼于世界竞争的长远战略布局上、立刻就有“危险感”、日本社会、经济界才会真正感受到“政冷”导致“经冷”的“剧痛”。

*** 必须彻底打碎“政冷”不妨碍“经热”的幻想

东方评论员认为，北京只有彻底打碎幻想着“政冷”不妨碍“经热”的日本社会、日本经济界、特别是与日本右翼有瓜葛的日本企业、在深刻地感受到了“不仅没有得到可以得到的、而且还失去了不应该失去的”之后，才会主动地去反对日本右翼的政治主张、从而为“经热”捂热“政冷”提供了“一种可能”。


我们的观点是，没有“硬”的立场，就不会有“软”的效果。下面的一段“报告的摘要”、已经为我们提供了些许这方面的线索，在一起阅读完这些“经济数据”之后，东方时事评论员、东方经济评论员将一起继续讨论这个话题，

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
