# -*- org -*-

# Time-stamp: <2011-08-04 12:20:16 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

*  2005年8月10日 星期三





** 唐淳风：中日年内或因东海纷争动武



　　【中评社香港8月10日电】中国前驻日外交官唐淳风今天接受中评社专访时表示，日本首相小泉纯一郎面对政局危机，为转移国内视线，必然挑起国际纷争，特别是利用东海油气田问题，中日双方今年内很可能打起来。

　　对於解决中日东海纷争问题，唐淳风说：“我是国内最不乐观的人，很多人都看得很淡说打不起来的，但恰恰相反，我认为特别是今年内就可能打起来。特别是这几天日本政坛巨变，小泉要把国内矛盾转化成国际矛盾，要吸引民族主义的选票，必然要挑起这种纷争。”

　　况且，日本在东海动武也不是没有先例，2001年北韩的所谓间谍渔船，日本就深入中国东海海域145海将其打沉。至今，仍有传闻称，被打沉的并不是所谓的北韩间谍渔船，而是中国渔船。

　　唐淳风认为，日本一直想发动第二次中日战争，就是没有东海问题，日本也是想打中国，因为攻击中国、打败中国才会有最大的战略利益和政治利益。

　　日本目前不但利用东海问题表现对中国政治上的傲慢，更重要的是，日本想要占领钓鱼台群岛海域，东海问题只是个掩护动作。“如果钓鱼岛是日本的，东海就是它的了。”

　　钓鱼台群岛的分围长125公，宽38-50公。其周边200海是专属经济区围，仅距离宁波海岸100多公。因此，如果钓鱼岛是日本的，就等於从中国霸占20万平方公的海疆，日本的海洋资源就会增加三分之一。

　　再说冲之鸟礁，退潮时只有桌面大，但如果是日本的，以它为圆心，周边专属经济区就划到中国大陆东海海域和中国台湾海域了。“那可绝不是电视画面上的礁石岛而已，”唐淳风说。

　　而中国的春晓油气田离宁波海岸100多公，离日本1700多公，不管从地理位置，还是领土管辖看，怎会跟日本挂上钩了？这是毫无道理的。“如果说日本过去还只是有侵华的野心，而今天日本极右势力分子上台，宁愿冒着挑起战争的危险。”
　
　　他认为东海问题有三种可能发展走向。一、中日关恶化。　二、中日双方妥协，在日本基本实现其阴谋下合作开发。三、双方不相让，矛盾长期化。“我认为最危险的是第二种走向。”

　　唐淳风认为，东海问题考验中国大智慧。他说，解决东海的关键在琉球。琉球是被日本非法占领的，中国从来就没有承认所谓将冲绳交给日本的《旧金山和约》（1951年美国英国不顾中国反对签订）。他指出，日本挑战东海、钓鱼台，要争的是琉球。他说，不管从国际法，还是二战後联合国管协议看，琉球是中国的。中国应该据理力争回琉球；争回琉球，就不再有钓鱼台、东海问题了。



【时事点评】在东方评论员看来，唐淳风的观点在于三层意思：第一，唐淳风认为“这几天日本政坛巨变，小泉要把国内矛盾转化成国际矛盾，要吸引民族主义的选票，必然要挑起这种纷争。”

第二，日本想要占领钓鱼台群岛海域，东海问题只是个掩护动作。如果钓鱼岛是日本的，东海就是它的了；

第三，他认为东海问题有三种可能发展走向，最危险的是第二种走向，即：中日双方妥协，在日本基本实现其阴谋下合作开发；

对此，东方评论员觉得“有许多话要说”。

●唐淳风的“第一层意思”与我们的观点基本吻合

首先，唐淳风的第一层意思与我们的观点基本吻合，但是，我们也认为日本是否最终敢在东海问题上挑起事端、还在于北京是否能“继续有效展示”不怕中日关系破裂、以及自己敢于一战、甚至是核战争的决心，特别是通过各种渠道向日本展示包括“一旦需要、不排除对日本进行核打击”的坚强决心，在东方评论员看来，展示这种决心的目的、就是要让日本朝野和国民“彻底明白”日本右翼玩火的“严重后果”。


*** 对这种决心的展示、可以有三种方法

当然，在东方评论员看来，对这种决心的展示、可以有三种方法，其一，在目前、可以“继续拿台湾问题”说事，公开针对为日本提供核保护的华盛顿、就与朱成虎将军不久前“所做所为”的一样、继续激起美国社会对中美可能会核战争的关切、从而让美国社会逼迫美国政府去“厘清”“涵盖台海”的“美日安保条约”的“相关条款”。


显然，就如不久前朱成虎将军声称一旦因台海战争受到美国的攻击，“中国准备核攻击美国”之类的“公开威胁”一样，明眼人是一看就知、朱成虎将军的这番“醉翁之意”、是“即在酒、又不在酒”：非常清楚，“真正的听众”除了有“点了名”的“台独”之外、还有支持台独的国际势力、在我们看来，美国当然是支持台独势力的国际势力、而日本也是支持台独势力的国际势力。


*** 北京应以“准备好进行军事冲突的姿态”、“尽最大可能地”去“事先”压住日本军事冒险的侥幸心理

不难想像，一旦支持“台独”的国际势力插手台海可能的战争，那么，既然中国这位将军“点名”准备核打击武装到了牙齿的美国、又怎么可能放过弱得多的、指望美国核保护伞保护的日本呢？

东方评论员认为，北京完全可以继续尝试着让美国社会和政府之间去“厘清信息”、并以此去警告日本社会和日本右翼势力、“通告”欧盟、特别是亚洲周边国家，一旦中日在东海、钓鱼岛方向发生军事冲突、其真实的原因是什么、其可能引起的“严重后果”又将是什么，从而，一方面可以尝试以“准备好进行军事冲突的姿态”、去最大限度地、尽最大可能地去“事先”压住日本保守势力的嚣张气焰、指望通过军事冒险逼迫北京让步的侥幸心理；而另一方面、也可以为一旦中日发生军事冲突、中国将不惜一切打掉日本右翼的军事冒险争取一个“尽可能好的国际氛围”。


*** 华盛顿“可以想的办法中”、“代价最小、效率最高”的办法

首席评论员认为，日本在东海的战略性试探是其“周边事态”政策的具体推进，也是日本打算改变“中美日”目前这种、“中美”可以绕过日本进行“全球战略对话”、而日本却无法绕开中国与美国进行全球战略对话、而只能与美国进行“区域对话”的“痛苦局面”。

为什么？在我们看来，其原因就在于日本与中国相比、它的政治、军事“本来就在美国人的手中掌握着”、再加上它现在还需要借助华盛顿的力量、“借助美国遏制中国这一战需要的掩护”、以达到从一个经济大国到一个政治、军事大国的“脱胎换骨”。


*** 美国一定会“继续想各种办法”、以让日本“与中国决裂、甚至是自绝于整个亚洲”

因此，在我们看来，尽管日本本质上是“想渔利于中美争斗”，但由于上述的“巨大缺陷”，决定它更多地是在扮演着为华盛顿“牟利”的角色，随着日本“全面倒向美国”外交政策的持续、华盛顿是一定会“继续想各种办法”、以让日本“自绝于整个亚洲”的、从而在更好地控制日本政治、军事之余、也将日本的经济置于自己的控制之下。

为了达成这一战略目的，华盛顿在策略上有着极其鲜明的两面特征，为了更好地说明这个问题，请大家仔细阅读下面这篇文章，东方评论员认为，这篇文章很好地“记录”了近来“中美日”间的互动过程，从中，我们不难看出华盛顿是如何“帮助”中日搞好关系的。



《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com


** 美国：空头支票安抚日本两面下注防备中国


【人民日报8月10日文章】编者按：长期以来，美国在亚太地区一直充当着一个特殊的角色。面对近年来中日两国由于历史问题和东海能源勘探等问题矛盾不断的情况，美国的态度又是如何呢？美国的举动是否意味着它要出面充当中日矛盾的“调停人”，这些举动的背后又有着什么样的动机呢？

中美日双边、多边会谈很频繁

进入5月份以来，中美日三国之间双边或多边的接触频繁，有官方的对话，也有带官方背景的民间智库之间的交流。其中，有美国参加的几次会谈更受到人们的关注。

7月21日—22日，“中美日安全对话”在北京悄悄拉开帷幕。这次会议是由美国传统智库布鲁金斯学会首先倡议的，美方并且派出了美国前国家安全副顾问斯坦伯格，美国前“国安会”官员、布鲁金斯学会中国中心主任杰弗里·贝德，以及该学会外交政策研究中心主任卜睿哲等重量级的人物与会，可见对这次会谈的重视。

在这次会议上，三国专家就中日之间的重大问题进行了探讨，如中日美三国战略利益和战略关系，中日、中美和美日双边关系，以及台湾问题、朝核问题和经济合作等问题。据美方成员表示，会议主要是从战略角度探讨三国关系，没有涉及到东海油气田争端等具体问题。2006年上半年，三国学者还将在日本举行一次研讨会，并最终联合撰写一份研究报告，对解决中日分歧及中日美三国关系发展提出建议和构想。

8月1日，中美举行了首次战略对话。尽管中美双方将这次对话定为“超越议题”，双方在会谈后都未详细说明对话的主要内容，但据日本共同社分析，双方会谈涉及了亚太安全和中日关系问题。日本专家认为，中日之间关系目前处于特殊时期，亚太地区蕴涵着美国巨大利益，因此亚太安全问题很大程度是指中日关系。前不久美国国务卿赖斯访问日本时，曾特意告诉日本首相小泉，美国重视与中国的战略对话。

8月4日至6日，美国众议院议长丹尼斯·哈斯泰德率领的众议院代表团访问了中国。哈斯泰德访华的前一站是日本，他与日本首相小泉纯一郎进行了会谈。日本和美国专家认为，哈斯泰德此行，中日关系可能是他与两国领导人会谈的一个重要内容。

与此同时，在美国参议院外交关系委员会的听证会上，负责亚太事务的前副助理国务卿薛瑞福表示：“（中国）对开采争议性海洋地区石油的兴趣日增，当然可能直接影响到美国的利益。”在中日东海争端方面，薛瑞福还表示：“美国可能被迫选择支持美国的盟邦。”据此，有台湾媒体称：“中日探油冲突，美国将支持日本。”这是否意味着美国真的将直接插手中日争端，并完全倒向日本一方呢？

强化美日同盟，但并非完全支持日本

日本一直是美国在亚太地区非常倚重的盟友，但中国作为“非盟国”也是美国不能忽视的合作伙伴。

今年以来，美国在对日和对华政策上的一系列举动颇为引人注目。对华政策上，美国的反恐战争取得阶段性成果之后，国内保守派要求对华“强硬”的声音有所抬头。布什政府对此反应较为理性，一方面称中美关系“复杂”，很难用准确的词语“界定”，另一方面也强调与中国合作的重要性。美国许多智库将美国的这种对华新战略概括为“两面下注”，即面对中国崛起的不确定性，做好两手准备，鼓励中国朝有利于美国利益的方向发展，也准备好应对中国挑战美国的霸权地位。强化美日同盟就成为美国在亚太应对中国崛起的“第一招”。

美国不少专家认为，美国对日政策其实并未改变多少，有许多是口惠而实不至。多年来，美国对中日之间的领土和海洋争端采取不表示立场的政策。比如，美国一名高官曾经表示：“钓鱼岛在日本的管辖下，日美安保条约适用于钓鱼岛。”对此，日本媒体大加炒作。但实际上，美国只是重申日本对钓鱼岛的“施政权”，并不违背其不对中日主权争端表态的政策。

在日本“争常”问题上，美国一方面表示支持日本，但最近又公开表示将与中国共同反对“四国联盟”的提案。这无疑表明，美国对日本的支持只是一张“空头支票”。怪不得日本媒体大骂美国是日本“入常”的最大障碍。

中日交恶，美国表现谨慎

对于中日两国关系紧张，美国的表现也异常谨慎。显而易见，一方是正在崛起的区域性大国，国际影响力不断扩大，另一方是自己的军事盟友和“全球合作伙伴”，美国不愿在这两者之间“选边站”。在朝核问题和反恐问题上仍有求于中国的时候，美国的表现格外小心。美国当然明白，中日的紧张关系势必影响亚太地区的繁荣与稳定，但是只有在关乎美国国家利益的时候，美国才会“出手”。

美国谨慎而复杂的态度在日本篡改历史教科书问题上表现得很典型。美国官员对此问题的表态，在很多中国人看来是有偏袒的，但美国却觉着是“不偏不倚”，或者是“各打五十大板”。美国国务院官员曾表示，“两国应通过协商解决问题”，“希望日本认真对待历史”，但也“关注中国历史教科书中对美国的不实描述”。美国外交关系理事会研究员艾瑞克认为，美国对日本的侵略历史从来不愿追究，除了因为美国已经从日本找回“伤亡平衡”以外，还与美国用原子弹轰炸日本有关。

美国想静悄悄地私下调解

许多美国专家认为，美国更希望通过“第二管道”来促进中日之间的沟通，避免两国不和危及美国在亚太地区的利益。美国华盛顿大学迈克尔·叶胡达教授表示：“中日是两个自豪的强国，美国只可能安安静静地在幕后帮助中日促和。由于最近中情局和国防部高级官员大谈特谈中国军事力量增长，中国可能很难将美国看作中日关系中有用的调停人。”他认为，美日最近将台湾变成其共同战略目标，这样至少会让中国觉得，美日可能联手来对付中国。

华盛顿战略与国际研究中心日本研究室主任威廉·布里尔曾在美国国务院工作了35年，并在日本居住了18年。他认为，美国可能没有能力去调解中日之间的纷争。美国现在穷于应付中东和反恐，很难顾及中日之间的争端。不过，他称，如果要调解的话，“公开的讨论已经够了，你一句我一句的公开发言够多了，现在是私下搞外交的时候”。

在中美日三方智库北京举行会谈的前后，记者曾多次致电布鲁金斯学会请求他们详细谈谈会谈情况，但均遭婉拒。这可能是美国“静悄悄”外交战略的结果。

中美日三边战略对话有可能实现吗?

未来亚太地区安全格局走向的决定因素在于中美日三边关系的发展，而其中最重要的当属中美关系。许多专家认为，当前中美关系、中日关系的背后多多少少都有意识形态偏见在作祟，而美日同盟的冷战思维架构的色彩不但没有淡化，反而有加深的趋向。无论是中美还是中日之间缺乏战略互信，都是上述原因的直接后果。

因此，未来亚太地区格局如何变化，还要看三方相互间的对话与沟通能否消除意识形态的偏见和冷战思维。此外，作为中日关系“死结”的历史问题，也需要两国静下心来，坐在一起商讨双方都可以接受的、解决问题的方案。

不久前，中日首轮战略对话中，李肇星外长明确向日本外务省事务次官谷内正太郎表示，倡议加强战略对话。虽然李外长并未明确这个对话是否指三方对话，但由于美日战略对话已形成机制，中美、中日战略对话也已经展开，无疑为三国之间的战略协调开启了“机遇之窗”。只要彼此有诚意，能够达成共识，中日关系就会继续发展，亚太安全也能得到保证。



【时事点评】我们知道，美国人“津津乐道”的、美国人主张的“中美日安全对话”、是在7月21日到22日召开的，是日本政府继7月14日向本国企业――日本“帝国石油”公司授予与中国有争议的东海三处天然气田的试开采权后、北京立刻升高调门强烈抨击之后召开的，也是中国军方高级官员意外地声称“准备核打击台独和日本的保护国--美国”的情况下召开的，结果我们也都看到了，那就是，中日之间不仅没有任何缓和的迹象，反而更加紧张了、反倒是中美关系因朝核问题六方会谈的重启、而在中日关系紧绷的时候呈现了一丝的缓和、直到最后中美还意外地启动了“中美战略对话机制”。

*** 美国将中国视为一个无法控制的对手，将日本视为可以控制的“小伙伴”

在东方评论员看来，任何一个有政治敏感度的人、都不难从中日关系的“紧”、和中美关系的“缓”中看出美国在与中国和日本打交道时所施展的“两面手法”、也都不难看出、中美之间到目前为止、在经历了美国中亚军事基地问题、伊朗核问题、争取韩国、印度等一系列较量之后，虽然仍然没有什么“战略互信”可言、但却看到了一种“相互认真对待”的气氛；在东方评论员看来，这是因为美国将中国视为一个无法控制的对手；

另外，我们在美日之间似乎也找不到任何战略互信的影子，除此之外、我们也看不出盟友间那种“应有尊敬”，在我们看来，这却是因为美国将日本视为可以控制的“小伙伴”。

显然，在这一点上，在日本“争常”问题可谓是表现得淋漓尽致：美国一方面表示强烈地支持日本，而且还只支持日本一家，但在日本最需要它支持的时候，华盛顿却公开表示将与中国共同反对“四国联盟”的提案。


不过，华盛顿在支持日本“入常”问题上的出尔反尔、开空头支票的最新记录，似乎一点也不影响它开出另一张空头支票，做出另一种空头人情。在东方评论员看来，近来“美日军事同盟”似乎又向前迈了一大步，东方军事评论员注意到，据报道日本自卫队和驻日美军计划于明年1月举行日美“联合纸上”演习，演练“日本所属岛屿在遭受武力侵犯”的情况下，日美如何“共同采取行动”。


*** 提出“关着房门、只在纸上画地图”这一建议的绝对是华盛顿

在这里，请大家注意这几个字：“联合纸上演习”，在东方评论员看来，如果此消息最后属实，那么，我们不禁要问一句，美日在这个时候安排这种“联合纸上演习”是什么意思？

显然，所谓“联合纸上演习”，就是只在纸上做推演、而非实兵演练。而据报道，这个演习是为了保卫所谓的“日本所属西南岛屿”，就此一条，足见提出“关着房门、只在纸上画地图”这一建议的、绝不是气焰极端嚣张、正千方百计要华盛顿在钓鱼岛、东海主权之争问题上“表态”支持日本的日本人、而是刚与北京启动战略对话、即试图推日本与中国决裂、同时又担心中国与自己进行全面对抗的华盛顿。

要知道、北京与华盛顿之间，在正在已经激化的伊朗核问题上、已经有所进展、再拖下去将对华盛顿绝对不利的朝核问题上、在已经初步稳定的中亚局势上，以及正在演变的“巴以和平”上、在经济政策协调的问题上、有太多的事情“要好好商量”。


*** “中美”双方都在极力避免的事情

可以肯定的是，一旦华盛顿答应日本，用实兵演习的方式、来公开演示美日军事同盟的目标范围，那么，北京与华盛顿之间，不仅在上述一系列问题上、就将立刻走向全面恶化的一面，更为严重的是，中美关系也就真的“向全面对抗”又迈进了一步，从而为俄罗斯、欧盟、甚至是日本的腾挪提供了“额外的空间”，这是“中美”双方都在极力避免的事情。


*** 华盛顿是“绝不愿”现在就在中日之间“选边站”的

在东方评论员看来，华盛顿的“这种用心”非常明白：即，通过这种方式的演习、一来可以向日本“暗中表示”支持日本在钓鱼岛问题上的“用心”，而另一方面，“关着房门画地图”却可以避免让日本有“公开的机会”、有“确实的证据”证明美国在钓鱼岛主权问题上的立场，避免被日本利用说成是美日军事同盟已经将钓鱼岛纳入共同防卫目标，从而对中国造成过度刺激，引起中美关系的进一步紧张。

显然，在华盛顿“可以想的办法中”、可以说“代价最小、效率最高”的办法、就是让中日军事冲突起来、让中日关系破裂、由“可能性变成事实”。在完全做到这一点之前，华盛顿是绝不愿在这中日之间“选边站”的。


*** 吴仪中断访日行程之后，北京却始终没有在经济层面有“大的、配套动作”

对北京而言，由于继吴仪中断访日行程、立刻引发日本国内政治、经济势力对小泉政府的、“近年少见”的“口诛笔伐”，之后，我们注意到，日本反对小泉“对外政策”的政治势力、比如说日本民主党党首、日本前首相桥本龙太郎等人相继展开了北京之行、这时候的北京、似乎又开始顾全大局了、似乎又开始在对日本社会“自动调整”抱有幻想、从而始终没有在经济层面有“大的、配套动作”。


*** 间接地给了小泉政府以喘息的时间

在东方评论员看来，这显然等同于缓和了紧张气氛、间接地给了小泉政府以喘息的时间、客观上讲、小泉之所以不顾自民党利益、而一意孤行地“解散国会、提前大选”、并为赢得大选而放风“打8月15日参拜靖国神社”这张牌、就在于日本社会给他的、搞好与中国、韩国关系的压力“不够”。

我们认为，尽管在这期间、北京加在大了在外交上的压力、但是，在东方评论员看来，没有经济层面的大动作、要让素有经济动物之称的日本人“自动调整”又谈何容易？如此一来，日本社会所具有的那种鲜明的“鱼群效应”、不仅不容易为北京所利用、反而给了日本保守势力以利用的空间。


*** 日本急于通过挑起东海争端的心态、已经到了一种“莫须有”的地步

第二，东方评论员也注意到，唐淳风认为日本想要占领钓鱼台群岛海域，东海问题只是个掩护动作，对此，东方评论员的看法是，唐淳风先生的话可以说是“一针见血”。

事实上，就目前而言，日本之所以拿着东海油气田问题说事，就是想掩护它要占领钓鱼台群岛海域的战略企图。

首席评论员指出，就目前中国开发东海油气田的情况来看，以最靠近日本单方面划出的“中间线”最近的春晓油气为例，由于它位于所谓“中间线”靠近中国沿海的一方，因此根本就不关日本的什么事、可日本就是要拿这个问题说事，显见其急于通过挑起东海争端、伺机掠夺中国海域、最后沉重打击中国在亚洲、甚至在世界上的声望之心态、已经到了一种“莫须有”的地步。

在昨天的点评中，东方评论员详细分析了日本社会在历史问题上、在面对中国日益强大这个现实下的“真实心态”（详见8月9日《东方时代环球时事解读》），显然，在东方评论员看来，北京不应该再对日本社会会从小泉纯一郎为首的、日本保守势力所奉行的这种“对华政策”上“自动调整”抱有太大的希望。


*** 北京已经到了应该将中国“可以打的”“经济牌”“公开示之”的地步了

在经济上，由于在日本对外贸易总额中，对美贸易所占比例已经跌破20%，而对亚贸易所占比例已经达到50%。在东方评论员看来，这个“此消彼涨”的经贸数字之中、还暗藏着另一个数字、这就是日本对中国的贸易额已经超过了它对美的贸易额，显然，这是一个“重大的变化”。

我们认为，有了这个重大变化之后，北京有必要将对日施展经济压力提上日程。东方评论员认为，在立足于“准备军事斗争”的前提下、北京已经到了应该将中国“可以打的”“经济牌”公开示之的地步了。在我们看来，日本在经济上已经非常依赖中国市场了，有统计认为，中国市场对日本的“经济增长”拉动了一个百分点，这是非常大的影响。北京在经济政策上有许多可以发挥的地方。


*** 有必要在人民币所参考的货币蓝子中、“灵活掌握”日元的权重

东方评论员认为，在“中美欧日”的经济政策协调方面，北京就可以尝试一下，比如，在欧美的压力下、在中国“被迫”调整人民币汇率形成机制之后，有必要变坏事为好事、有必要在人民币所参考的货币蓝子中、“灵活掌握”日元的权重（货币蓝子已经公布，但各币种的权重却仍然没有公布），在下一波人民币升值的压力中、想办法将升值压力转移到日元身上，想办法让日元“早一点”成为美元、欧元的攻击对象、从而削弱日本经济的竞争力、毕竟日本与欧美经济更多地是处于竞争关系、而中国与欧美更多是处于互补关系。

下面是一则译自路透社的经济报道，在一起了解报道内容之后，东方时事评论员、东方经济评论员将一起就中国对日本“可以打的”“经济牌”继续进行讨论、并对北京应如何防范日本在东海可能的冒险、继续进行展开。


《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
