# -*- org -*-

# Time-stamp: <2011-08-03 23:44:19 Wednesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 2005年6月21日 星期二

** 李光耀：台海模糊空间没了

【综合报道】据岛内中国时报报导，与中国大陆关系良好的新加坡内阁资政李光耀表示，由于「反分裂国家法」与美日安保条约把台海问题列为共同战略目标，模糊的空间没有了，反而让美、日尽力确保台湾不会妄动，避免自己卷入与中共的战争。

「联合早报」二十日刊登了李光耀接受中国央视的专访。李光耀在专访中指出，中国制定「反分裂法」，等于在台海问题上画下自己的底线。现在，美国与日本又把台海问题列为美日安保条约下的「共同战略目标」，也等于宣布一旦中国向台湾动武，美国若有所反应，日本也有义务协助美国对抗中国。

李光耀表示，正因为有这样的底线，模糊空间没有了，美、日反而会尽力确保台湾不要妄动，以避免自己卷入与中国的战争。他同时相信，日本将避免自身卷入和中国发生战争的困境，以免百年后也无法和中国握手。

不过，李光耀也呼吁中国不要卷入战争，否则将会再次倒退相当长的时间。他说，上次中国倒退，就倒退了一百五十到二百年。虽然李光耀没有说明中国可能卷入什么战争，但他提到了中国和日本最近因为能源资源发生的争端及台海问题。

李光耀在专访时再度解释总理李显龙去年访台的原因。他强调，李显龙去年在任职总理前访台，确实是为了解台湾的发展，并期待在适当地情况下，把正确的讯息和评估传递给恰当的人，为避免台海爆发危机出一份力，但是中国政府却以为新加坡向台湾当局伸出援手，误解新加坡的用意。

李光耀指出，确保台海不出现军事冲突，是新加坡的利益所在。因为一旦发生冲突，对台湾、中国、美国以至于整个东亚，包括新加坡在内，都是一场灾难。

他还说，当日本同意把台湾问题列为美日共同战略目标后，等于使台海问题加入日本因素，因此也将到东京访问，设法了解日本领导人在两岸问题上的真实想法。

李光耀并呼吁，中国现在最重要的就是不要卷入战争，耐心追求成长，因为中国还需要五十到一百年去赶上全球，包括科技能力、尖端科技。



【时事点评】我们注意到，李光耀指出，确保台海不出现军事冲突，是新加坡的利益所在。因为一旦发生冲突，对台湾、中国、美国以至于整个东亚，包括新加坡在内，都是一场灾难。

*** 李光耀的一个观点，我们还是深以为然的

显然，在东方评论员看来，李光耀的这席话“说得不错”，符合事实。我们同时也认为，也正是基于这种判断，新加坡在努力避免这场可能的灾难时、可以说用过了各种手段，其中、就包括有些“不那么光明正大的东西”。

东方评论员认为，李光耀的一个观点，我们还是深以为然的，他说：由于“反分裂国家法”与美日安保条约把台海问题列为共同战略目标，模糊的空间没有了，反而让美、日尽力确保台湾不会妄动，避免自己卷入与中共的战争。

显然，从这段话中，我们不难看出“反分裂国家法”的战略意义之所在，对东亚格局、世界格局的影响之所在。


*** “告戒”中国、才是李光耀真正想说的“心里话”

然而，李光耀先生在以“反分裂国家法”划下红线的效果“有意无意地”夸奖一番之后，却又以“中国不要卷入战争，否则将会再次倒退相当长的时间”的言词来“告戒”中国、在东方评论员看来，恐怕后者才是李光耀真正想说的“心里话”。

首先，我们对李光耀先生这一“似是而非”的“告戒”、有两个疑问，第一，中国现在想进行战争吗？第二，如果中国想启动战争，又会在什么方向投入战争？


*** 李光耀先生在“提建议”之前，搞清楚了没有？

不难看出，李光耀事实上已经承认，中国制定“反分裂法”、在台海问题上画下自己的底线的做法，在让台海的模糊空间“没有了”的同时，“反而让美、日尽力确保台湾不会妄动，避免自己卷入与中共的战争”。

由此可见，正是因为中国不想进行战争，才果断制定“反分裂国家法”的，也正是因为有了这部“反分裂国家法”、才确保台海仍然没有爆发战争的。而美日明知“反分裂国家法”是一部旨在“止独”的法律，却偏偏要针锋相对地抛出“美日新安保指针”，将台湾纳入共同目标，到底是谁在想有朝一日催动“台独”、引发战争，对这一切，李光耀先生在“提建议”之前，搞清楚了没有？


*** 到底是“良苦用心”、还是“别有用心”？

在我们看来，这位素有“中国老朋友”之称的新加坡前领导人这一番用心，到底是“良苦用心”还是“别有用心”、恐怕从他为李显龙新加坡之行准备的“辩解词”中、就可以看得清清楚楚。

请大家注意，原文是这样的：李光耀在专访时再度解释总理李显龙去年访台的原因。他强调，李显龙去年在任职总理前访台，确实是为了解台湾的发展，并期待在适当地情况下，把正确的讯息和评估传递给恰当的人，为避免台海爆发危机出一份力，但是中国政府却以为新加坡向台湾当局伸出援手，误解新加坡的用意。


*** 世界上哪有“如此这般”地去“为避免台海爆发危机出一份力”的?

然而，在东方评论员看来，李光耀“如此袒护”李显龙、并“怪责”北京是“误会了”新加坡的真实用意、恐怕是说不过去的。要知道，当时中国外交部是严词警告新加坡政府、而时任新加坡副总理的李显龙却终究“执意台湾一行”，不仅行程“保持高调”，并与台湾军方公开举行军事会谈，世界上哪有“如此这般”地去“为避免台海爆发危机出一份力”的?新加坡当局当时不是在向“台独”伸出援手又是什么？


*** 李显龙访台是一次极其敏感、严重的外交事件

对李显龙的那次访台、东方评论员当时就曾经给出过大量的分析与点评。在我们看来，李显龙访台是中新之间、在去年7月份、赖斯“访华失败”之后的一次极其敏感、严重的外交事件。

东方评论员认为，新加坡对中国核心利益的这一挑衅行为，显然是受到华盛顿两岸政策的“启发”、并在美国人授意下进行的。我们知道，长期以来，华盛顿在两岸政策上一贯玩弄的就是“两手策略”，一方面口头上承诺坚持“一中”原则，另一方面、则是在暗地里扎扎实实地做着推动“台独进程”的苟且之事。

在华盛顿的对华政策上，在执行“一中”政策时、不仅从来就没有认真过、现在更是被美国逐惭空洞化，这一点恐怕全世界都看得出，而在整个政治、分寸、眼光上的确有那么点“独到之处”的李光耀难道会看不出？


*** 在整个过程中，美国和新加坡真可谓是一唱一和

事实上，比那时稍早点的时候，在去年4月份美国副总统切尼访华“不成功”、气哼哼地回去之后仅仅只有三天的功夫，美国学术界就立刻抛出了“一中政策”是个神话的说法。

在东方评论员看来，这分明是在给北京以颜色看，意思就是说，如果北京不按美国的要求对朝鲜施加压力，让北京的朝核政策“顺着”美国的朝核政策，那么，华盛顿就会将“一中政策”当牌来打。显然，华盛顿这是在制造舆论，意在用“台湾问题国际化”来要挟中国。

根据我们的观察，而北京也是做得非常绝，不仅没有屈服，反而直接请计划访问北京的朝鲜领导人金正日、“提前访问北京”、并在访问期间敲定了明确的“对朝政策”，即公开表示“支持朝鲜改革”、支持朝鲜现有政治体制的稳定。这分明是暗示中国已经将朝鲜纳入了自己的军事保护之下。

于是乎，美国国内就有人配合着提出了“一中政策”是个神话的说法，露骨地以“要重新审视“一中”政策”来威胁北京。

当时，李显龙就是在这种背景下、在赖斯从北京“不高兴地”回到华盛顿之后，立刻跑到台湾去的，在整个过程中，美国和新加坡真可谓是一唱一和，李显龙的那次访台、根本就是在替美国政府试探大陆，为重新介定一中政策“提前探路”。


*** 新加坡领导人在国际事务“大有作为的愿望”一直“十分强烈”

东方评论员认为，从李光耀时代起，新加坡就非常热衷于将自己塑造成世界大国关系的“中间人”，使各方有求于己，从而提高其国际地位。在东方评论员看来，自李光耀创造了新加坡的经济奇迹之后，由于小国的危机感、李光耀在国际事务“大有作为的愿望”一直“十分强烈”、想通过所谓的“大国外交”来为新加坡谋取最大的政治、经济利益。

显然，“台独”问题毫无疑问是亚太地区“最重大的安全问题”，也是中美日等大国全力角力的战略问题。如何在台湾问题上游走于大国之间、并借机渔利，一直是李光耀、吴作栋最喜欢做的事情之一。


*** 李显龙访台有着多重的政治目标

在东方评论员看来，李显龙访台有着多重的政治目标。第一，我们知道，李显龙是新加坡前总理、现内阁资政李光耀的长子，而李光耀为了让自己的儿子接手政权，可以说，李光耀很早就开始对他进行了长期、系统地培养，从多个方面为其接班创造各种有利的条件。

然而，在新加坡，随着民主化进程的推进，李显龙世袭国家权力所面临的困难越来越大。为此，李光耀采取自己担当内阁资政、吴作栋当总理的“垂帘听政”过渡方式，来缓解了李显龙“直接世袭”总理的国内压力。

但是，李显龙自1997年兼任财政部长后，国际局势是一点都没有给他面子：东南亚金融危机连带着新加坡的经济是“全面下滑”，李光耀主政新加坡、在20世纪70至80年代创造的“经济辉煌”，可以就是“一去不返”。

只是按李光耀的计划，李显龙是必然接替吴作栋出任总理的，一来其在国内的政治威信不高，二来特别是吴作栋线上的人对李显龙“仍然不服”。因此，为了尽可能地提高李显龙的政治威信，台湾问题就成了一个非常合适的舞台：李家想通过李显龙访台来显示他的政治魄力与胆识。

而深得李光耀“真传”的李显龙、执意访台就是企图在这一重大问题上“有所作为”、从而“提高新加坡的国际地位”、并拉抬自己的政治威信。

根据我们的观察，李显龙与吴作栋虽然在权力争夺上有矛盾，但在通过李显龙访台来提高新加坡的国际地位这一问题上的、两人的看法还是一致的。因此，李显龙访台并不只是李氏父子的决定，也是新加坡政府的决定、出于新加坡所谓的国家利益。

可见，在这中间，李光耀先生所说的、李显龙是“为避免台海爆发危机出一份力”的解释，在东方评论员看来，根本就是一种“狡辩”。


*** 美国和新加坡之间的算盘、打得的确“非常精巧”！

第二，东方评论员也注意到，李显龙访台后，国际舆论对此事的报道、普遍是以一种“相对客观的态度”进行报道的。在东方评论员看来，这一态度本身就说明两个问题，首先，这说明国际舆论认为此事的责任在于故意挑战中国主权的新加坡政府，其次，这还表明关注台海局势的国家还在密切注视着这一事件的发展动向。

显然，国际社会、特别是周围国家都在注视着北京、都想看看北京将如何摆平这件事情。在东方评论员看来，从上面的分析不难看出，李显龙访台的“国际后果”实际上有两个，第一，或“全面加强”国际社会支持“台独”的力量，使中国遏制“台独”的国际困难越来越大，这是华盛顿想要的；或进一步削弱国际社会支持“台独”的势力，使中国遏制“台独”的政策收到成效，这是北京想争取的。显而易见，产生何种影响、北京和华盛顿谁得谁失，完全取决于中国的反应。


东方评论员认为，如果中国让新加坡为李显龙访台付出巨大代价，那么，周边国家、国际舆论“将会判定”新加坡是“聪明反被聪明误”、从而谨慎从事；在东方评论员看来，新加坡之所以敢挑战争中国的核心利益，就是凭借自己在东盟中的特殊地位，而北京出于经济方面的因素，一直“非常看重”与东盟的关系。

不难看出，如果北京顾忌经济因素、或者错判此事的影响，那么，不仅新加坡会利用“台独”与中国进一步“讨价还价”、而且国际舆论也将立刻视新加坡的“台海政策”为“指针”，并会立刻效法而与华盛顿的台海政策进行互动、和美国一道、利用“台独”来勒索甚至是遏制中国。

在我们看来，这就是华盛顿最想看到的一幕：即彻底动摇国际社会中普遍承认的“一中政策”，从而将台湾问题进行“国际化”。这种图谋一旦得逞，那么，“台独”势力也将因此而更加大胆地实现“法理独立”。

在看清楚了“台独”、支持“台独”的国际势力之间的这一连串的“复杂联动”、“倾情表演”之后，我们不得不说、美国和新加坡之间的算盘、打得的确“非常精巧”！



*** 最后的结果”也许没有出乎华盛顿的意料，但却绝对地出乎了新加坡、李氏父子的预料

然而，“最后的结果”也许没有出乎华盛顿的意料，但却绝对地出乎了新加坡、李氏父子的预料：即，尽管新加坡政府一度发动舆论攻击中国是“大国期负小国”，将中方的严正抗议斥之为“反应过激”、“有损形象”；尽管访后，面对北京的痛击、李显龙当时仍然心存幻想地威胁北京说：“如果我们的关系经不起这次事件的考验，那只能说明这样的关系是很浅薄和脆弱的”，然而，北京不仅没有因“这些攻击”而放过新加坡，而且更是痛下杀手，从经济层面逐一封杀新加坡的“在华利益”。直到已经“转正”、成为新加坡总理的李显龙、公开的反对“台独”为止。

显然，在台湾这个核心问题受损的情况下，在新加坡甘愿为华盛顿出头打探“台湾问题国际化”之可能性的情况下，中国还就以大国的身份去“期负”新加坡这个小国了，在东方评论员看来，如果这种“因果昭然”的“以牙还牙”也能算是一种“欺负”的话。


*** 李光耀为儿子做的一番“辩解”，，根本就站不住脚

事实证明，遭到北京所谓“欺负”的新加坡、在整个过程中，从来就没有得到过国际社会的“同情”，甚至是在幕后操纵的美国人、由于顾忌自己的身份，也没有为新加坡说一句新加坡“想听的同情话”。

在东方评论员看来，国际社会也看得清清楚，是新加坡不自量力、挑畔中国核心利益在前，北京的报复在后。东方评论员认为，华盛顿搬动新加坡这枚棋子、挑起的这一轮“试探”之举，不仅没有能为重新审视“一中政策”、为“台湾问题国际化”探出一条路来，反而因菲律宾、澳大利亚等美国盟国“看清形势”之后、纷纷宣布与中国加强关系、反对“台独”、而大大压缩了华盛顿欲将“台湾问题国际化”的操作空间。

可见，在这整个过程中，李光耀先生所说的、“中国政府以为新加坡向台湾当局伸出援手，误解新加坡的用意”的辩解，在东方评论员看来，根本就站不住脚。


*** 在配合华盛顿遏制中国的问题上，新加坡总是显得那么地“别具一格”

现在，当时的新加坡副总理已经“转正”、成了新加坡的总理，一心“想搞大国外交”、再创新加坡辉煌的李氏父子、也就更加有了一片“广阔的政治舞台”、从而更有机会在国际社会面前、去表演一番。

然而，在对待“台独”的问题上，因执意访问台湾而遭北京痛击的新加坡、后来是一再地公开表示“反对台独”、并不厌其烦地“警告”“台独”是危及亚洲安全的最大危险，并以此“部分修补了”与中国的关系。

但是，如果我们看得再仔细一点，如果我们观察得再深入一点，就不难发现，在如何配合“台独”的总后台--美国的问题上、在如何配合华盛顿全力围堵中国的政策时，东方评论员的感觉是：在亚洲这块地方，新加坡总是显得那么地“别具一格”。


*** 新加坡的“何去何从”、竟然当成了是新加坡对中国的一种“恩赐”

事实上，新加坡的李显龙为何要访问台湾，其真实目的新加坡人自己就曾经有一番“精彩的表白”，当时新加坡最有影响的《联合早报》，就曾经发了一篇文章，猛烈抨击北京，文章中的一段威胁意味十足，原文是：“站在一个小国的立场看，新加坡在国际舞台上最好就是能在各个主要国家之间取得平衡，但现在似乎存在这样一个趋势，各种主客观的因素都在促使新加坡向欧美这一边靠拢。这符合新加坡的国家利益吗？恐怕不，至少不会是我们最佳的选择。这符合中国的利益吗？恐怕也不。个别具官方背景的中国学者嘲笑新加坡是“口袋有一点钱就想玩大国外交”，但新加坡的另一个选择，难道是中国更乐于看到的吗？”

在东方评论员看来，文章作者有无新加坡官方“背景”，我们无从考证，然而有一点是非常清楚的，那就是这段话可谓是“牛气十足”，显然，文章将新加坡的“何去何从”、是否在中美之间保持平衡、竟然当成了是新加坡对中国的一种“恩赐”。

我们认为，这种观点非常“耐人寻味”，首席评论员曾经就此指出：这就是新加坡政府敢于在当时那种敏感局势下、不顾中国的强烈反对也要去台湾的“真实心态”。


*** 北京有必要放弃原则、去看新加坡的脸色吗？真是笑话！


在我们看来，新加坡是选择向欧美靠拢、还是向中国靠拢，这是新加坡自己的事，他人无权干涉，也无意干涉。东方评论员认为，在“上述原文”中，起码有一点说得不错，那就是：“站在一个小国的立场看，新加坡在国际舞台上最好就是能在各个主要国家之间取得平衡”。

显然，这的确是“小国的生存之道”，只是如此一来，问题也就来了：东方评论员认为，如果新加坡“果真认为”这也是新加坡的“生存之道”的话，那么，什么可以选择欧美、或者可以选择中国，根本就是“胡说”；

在我们看来，如果新加坡政府“不真心”认为必须遵循这一生存之道的话，那么，新加坡迟早会做出自己的选择，东方评论员的立场是：新加坡最终将做出的选择、是更符合欧美的利益、还是更符合中国的利益？我们“并不愿意多想”。

在东方评论员看来，“不愿意多想”的道理其实很简单，即，我们“有一点是知道的”、也是非常肯定的，那就是，新加坡的最佳选择是“一定会符合”新加坡的利益的。因此，手里拿着大把筹码、甚至可以打打马来西亚牌的北京、有必要放弃原则、去看新加坡的脸色吗？真是笑话！



*** 新加坡人“写出来”的这段“笑话”、曾经达到了“高潮”


事实上，新加坡人“写出来”的这段“笑话”、在北京痛击新加坡、李显龙最后被迫公开“反对台独”、将“台独”归之为区域内安全最大威胁、从而被台湾“外交部长”形容为“鼻屎大点的国家”之后，终于达到了“高潮”。

东方评论员认为，起码到目前为止，新加坡虽然没有正式宣布“选择美国”（恐怕也不会）、但是，种种迹象表明，新加坡人为了“玩大国外交”、刻意“所保持的平衡”、其实已经在向美国方向移动。


*** 就“亚洲金融中心”这一点而言，新加坡的“没落”似乎是不可避免的

在我们看来，在亚洲金融危机后，新加坡经济一蹶不振，过去依赖美国市场的新加坡经济饱受打击之余只有转向中国市场。由于新加坡的亚洲金融中心的地位受到中国香港、上海的强大挑战，不论是香港还是上海、所依附的都是经济容量庞大的中国，其前程都是“不可限量”，因此，就“亚洲金融中心”这一点而言，新加坡的“没落”似乎是不可避免的。

因此，东方评论员认为，“新加坡的出路”在于借助中国经济堀起之机，在参与亚洲经济一体化进程的过程，逐渐调整自己的经济结构，从而将自己融入东亚、亚洲经济一体化的格局中来。

然而，新加坡目前在政坛、商界当权的一群受英文教育的精英分子心中，存在着一种“殖民地子民”的微妙心结。在东方评论员看来，这种“殖民地子民”情结使得新加坡的统治层非但看不起其国内受中文教育的人，还看不起其他地区的华人、也看不起其它亚洲人。

因此，东方评论员也就注意到这么一种现象：即，新加坡不仅与其邻国马来西亚搞不好关系，就是与印尼、菲律宾、泰国也是“全都处不好”，再加上惧怕中国的强大，如此一来，新加坡自然就得全力投靠美国“以求自保”了。


*** 在新加坡统治层的眼里、其“最佳选择”似乎就是“与美国、日本一起遏制中国”

然而，论道理，从来都是“远亲不如近邻”的道理。对此，许多国际问题专家早已经非常清楚地指出，如果新加坡面临中国堀起的趋势、却最终选择与中国对立的关系，那么，今后一段时间里，新加坡的“全面没落”是“指日可待”。

在我们看来，也正因新加坡有那种“可以选择美国、也可以选择平衡”的“小国心态”、又有“想玩大国外交”以为新加坡找出路的李氏父子，还有一大帮子受英文教育、心存“殖民地子民”微妙心结的精英分子，还加上新加坡在香港、上海的挤兑下、“没落”的危险日甚一日，因此，在新加坡统治层的眼里、其“最佳选择”似乎就是“与美国、日本一起遏制中国”。


*** 新加坡如此卖力地“反台独”、恐怕是为了更好地配合美日围堵中国

只是在有了李显龙访台遭中国痛击的教训之后，在对台政策上，新加坡似乎不敢再嚣张了。东方评论员注意到，在表面上，新加坡甚至还不时地喊喊“反对台独”的口号，以免冒犯北京，然而，在东方评论员看来，新加坡如此卖力地“反台独”、恐怕是为了更好地配合美国、日本围堵中国的战略。

东方评论员看到的真实情况是：新加坡一边着“反台独”、一边却与日本一样，在亚洲是“仅有的两个”、为美国航空母舰提供军事基地的国家之一；新加坡一边着“反台独”、一边却为拉姆斯菲尔德在亚洲推销“中国军事威胁论”提供平台与场地；新加坡一边喊着“反台独”、其“国父”李光耀却在其他场合对中国国策“指指点点”，“切拿问闻”：先是建议“中国不要军事崛起”、而要“文化崛起”、现在又建议“中国不要卷入战争”，而要“耐心追求成长”；


*** 对中国的事务“指手划脚”，李光耀的真实目的到底是什么？

对此，东方评论员就不禁要问：这位李光耀先生在短短的几个月之内，连续多次对中国的事务“指手划脚”，先是建议中国不要以军事崛起、现在又建议中国不要卷入战争，其真实目的到底是什么呢？


不难看出，在拉姆斯菲尔德强硬的提出“中国军事威胁论”之后，在赖斯不再掩饰“中国威胁了美国”的念头之后，在日本公开以中国为主要假想敌之后，李光耀的这一番“别有用心”的建议，不过是在以亚洲国家的身份，在向中国喊话，要求中国“继续滔光养晦”、不要给美国制造“中国威胁论”的口实、从而让美国有理由在亚洲制造紧张气氛、不利于亚洲的安全与稳定。

在东方评论员看来，李光耀的这一套，可以说是美国强硬“对华政策”的另一面，是软的一面，其真实意图，是在尝试“借助”美日的军事压力，“配合”美国“劝说”中国以“东亚经济一体化进程”换取中国的对台军事准备，换取中国的军事现代化进程，继而换取中国的国家安全，否则、按李光耀的警告：战争一旦爆发，（可能是两岸间，也可能是中日间），中国将会“再次倒退”相当长的时间。

东方评论员认为，粗看起来，李光耀先生真可谓是“中国人的好朋友”，为中国“想得太周到了”、竟然想出这样一种办法、来解“中美日”间的“死结”。

然而，只要我们看看今天的形势，看看美日是如何将中国列为主要威胁的、看看美日是如何着手安排围堵中国的军事部署的，再看看美国是如何操纵“台独进程”、直逼中国底线的，再看目的地美日是如何联手、阻止中国获取原油的，我们也就不难发现，李光耀先生为中国提出的这一连串建议、本质上不过是在奉劝中国不要与美国有丝毫的战略对抗、而要尽可能配合华盛顿的战略安排、并以此来最终避免台湾可能的战争，从而在“谋求文化崛起、耐心追求成长”的过程中、满足于逐渐成长为一只“肥得流油的待宰羔羊”、直到有朝一日被人“大卸八块”、永除心头之患。

我们认为，新加坡“国父”的这一番建议，简值是“不堪入耳”：如果新加坡的决策层不是傻子，那么就是把中国决策层当成了傻子。不过值得警惕的是，与此类似的建议，在中国国内，也时有耳闻。

*** 新加坡的利益又在什么地方呢？

然而，在东方评论员看来，就算最终的结果是中国被人“大卸八块”、那么、新加坡的利益又在什么地方呢？新加坡人能成为美国人、或者西方人吗？显然，新加坡的利益不是在围堵中国的结果中收获、而在围堵的过程中汲取。

就如现在新加坡正在做的事情一样，在帮助美日遏制中国的过程中、捞取那么一点点好处，不论怎么样，李氏父子起码可以在这一过程中、继续自欺欺人地、“大玩大国外交的游戏”；还有一点，那就是新加坡似乎也因此就找到了“尽可能地减弱、减慢”香港、或者上海挑战自己亚洲金融中心地位的“潜力和速度”的好办法，当然，这仅仅是从新加坡想保住其国际金融中心这一层面来说的。

下面，是一则有关台军“护渔”的后续报道，在一起阅读之后，东方评论员将继续今天的台湾部分。
《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
