# -*- org -*-

# Time-stamp: <2011-08-02 20:58:06 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

#+STARTUP: indent

* 2005年4月29日 星期五

** 中共中央总书记胡锦涛会见连战时致辞（根据录音整理）

【北京消息】中共中央总书记胡锦涛会见连战时致辞：

尊敬的连战主席和夫人、尊敬的吴伯雄副主席、林澄枝副主席、江丙坤副主席，尊敬的国民党大陆访问团的全体成员，大家好！

四月的北京春意盎然，在这美好的季节里，我们迎来了中国国民党主席连战先生率领的国民党大陆访问团，今天的会见是我们两党主要领导人历史性的会见，我为此感到非常高兴。

首先我代表中共中央向连主席和夫人、向各位副主席、向访问团的全体成员表示热烈地欢迎并致以良好的祝愿。

“有朋自远方来，不亦乐乎”你们的来访是中国共产党和中国国民党关系史上的一件大事，也是当前两岸关系中的一件大事，从你们踏上大陆的那一刻起，我们两党就共同迈出了历史性的一步。这一步既标志着两党的交往进入了新的发展阶段，也体现了我们两党愿共同促进两岸关系发展的决心和诚意，我们共同迈出的这一步，必将记载着两岸关系发展的史册上。


当前，两岸同胞都希望两岸关系走向和平、稳定、发展的光明前景。我们多次表示，欢迎认同“九二共识”、反对“台独”、主张发展两岸关系的台湾各政党、团体和代表性人士同我们开展交流和对话，共同推动两岸关系的改善和发展。


昨天全国政协贾庆林主席和连战主席以及访问团的成员进行了很好的会见，陈云林主任和林丰正秘书长也进行了工作会谈，等一会儿我还要和连主席交换意见。我想，我们一定能够在促进两岸关系发展和两党交往等问题上达成重要共识。

虽然我们两党目前还存在一些分歧，但只要我们双方都能够以中华民族的根本利益为重，以两岸同胞的福祉为重，就一定能够求同存异，共同开创美好的未来。

今年是孙中山先生逝世八十周年，连主席和访问团的全体成员在南京敬谒了中山陵。中山先生是伟大的爱国主义者和民族英雄，是中国民主革命的伟大先行者，他为民族独立、民主自由、民生幸福，为国家的统一和富强贡献了毕生精力。他在全国各族人民和一切爱国人士当中有着崇高的威望，中国共产党人始终对他怀着崇高的敬意，从来就是中山先生革命事业的坚定支持者、合作者、继承者。

中山先生也把中国共产党人当作自己的好朋友。在当年，中国内忧外患的情况下，中山先生第一个喊出了“振兴中华”的口号，这理应继续成为我们两岸的中国人共同的追求和责任。中山先生为中华民族和中国人民留下了许多珍贵的精神遗产，值得我们永远继承和发扬。

在当前两岸形势复杂变化的形势下，我们两党都要深入地体察两岸同胞的所愿所想，深刻地把握两岸关系和世界大势的发展趋向，要以我们积极的作为向两岸同胞展示两岸关系和平稳定发展的前景，要向世界表明两岸的中国人有能力、有智慧解决彼此的矛盾和问题，共同争取两岸关系和平、稳定、发展的前景，共同开创中华民族的伟大振兴。

我相信，国民党大陆访问团的这次访问，以及我们两党的交流对话，已经给两岸关系的改善注入了春天的气息，希望我们双方共同努力，争取两岸关系和平、稳定、发展的方向前进。让我们两岸同胞一道在和平、发展的道路上不断开拓前进。


非常感谢连主席和各位听完我的欢迎辞，谢谢大家。




【时事点评】我们注意到，在两党达成这一会谈新闻公报之前，胡锦涛主席在欢迎致辞时、所说到的一句话，既：“要向世界表明两岸的中国人有能力、有智慧解决彼此的矛盾和问题”，可以说很好地为这一历史性握手进行了“画龙点睛”。

在东方评论员看来，这一历史性握手的现实和历史意义之所在，本身就是在告诉世人：台湾政治固然是岛内之事，牵扯到方方面面，但归根结底，它更是“中国人自己的事情”。

在我们具体点评胡锦涛和连战“正式会谈”的意义和成果之前、先来全篇通读一下两党领导人历史性握手之后、在“正式会谈”中形成的新闻公报。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 中国共产党总书记胡锦涛与中国国民党主席连战会谈新闻公报

【北京消息】中国共产党总书记胡锦涛与中国国民党主席连战会谈新闻公报，全文如下：


中国共产党总书记胡锦涛与中国国民党主席连战会谈新闻公报


二00五年四月二十九日


应中国共产党中央委员会总书记胡锦涛邀请，中国国民党主席连战率国民党大陆访问团，于二00五年四月二十六日至五月三日访问大陆。这是国共两党一次重要的交流与对话。在两党“正视现实，开创未来”的共同体认下，四月二十九日，胡总书记与连主席在北京举行会谈。双方就促进两岸关系改善和发展的重大问题及两党交往事宜，广泛而深入地交换了意见。这是六十年来国共两党主要领导人首次会谈，具有重大的历史和现实意义。四月二十八日，中共中央政治局常委贾庆林会见了国民党访问团全体成员。两党工作机构负责人进行了工作会谈。基于两党对促进两岸关系和平稳定发展的承诺和对人民利益的关切，胡总书记与连主席决定共同发布“两岸和平发展共同愿景”。全文如下：


五十六年来，两岸在不同的道路上，发展出不同的社会制度与生活方式。十多年前，双方本着善意，在求同存异的基础上，开启协商、对话与民间交流，让两岸关系充满和平的希望与合作的生机。但近年来，两岸互信基础迭遭破坏，两岸关系形势持续恶化。目前两岸关系正处在历史发展的关键点上，两岸不应陷入对抗的恶性循环，而应步入合作的良性循环，共同谋求两岸关系和平稳定发展的机会，互信互助，再造和平双赢的新局面，为中华民族实现光明灿烂的愿景。


两党共同体认到：


━━坚持“九二共识”，反对“台独”，谋求台海和平稳定，促进两岸关系发展，维护两岸同胞利益，是两党的共同主张。


━━促进两岸同胞的交流与往来，共同发扬中华文化，有助于消弭隔阂，增进互信，累积共识。


━━和平与发展是二十一世纪的潮流，两岸关系和平发展符合两岸同胞的共同利益，也符合亚太地区和世界的利益。


两党基于上述体认，共同促进以下工作：


一、促进尽速恢复两岸谈判，共谋两岸人民福祉促进两岸在“九二共识”的基础上尽速恢复平等协商，就双方共同关心和各自关心的问题进行讨论，推进两岸关系良性健康发展。


二、促进终止敌对状态，达成和平协议


促进正式结束两岸敌对状态，达成和平协议，建构两岸关系和平稳定发展的架构，包括建立军事互信机制，避免两岸军事冲突。


三、促进两岸经济全面交流，建立两岸经济合作机制促进两岸展开全面的经济合作，建立密切的经贸合作关系，包括全面、直接、双向“三通”，开放海空直航，加强投资与贸易的往来与保障，进行农渔业合作，解决台湾农产品在大陆的销售问题，改善交流秩序，共同打击犯罪，进而建立稳定的经济合作机制，并促进恢复两岸协商后优先讨论两岸共同市场问题。


四、促进协商台湾民众关心的参与国际活动的问题促进恢复两岸协商后，讨论台湾民众关心的参与国际活动的问题，包括优先讨论参与世界卫生组织活动的问题。双方共同努力，创造条件，逐步寻求最终解决办法。

五、建立党对党定期沟通平台


建立两党定期沟通平台，包括开展不同层级的党务人员互访，进行有关改善两岸关系议题的研讨，举行有关两岸同胞切身利益议题的磋商，邀请各界人士参加，组织商讨密切两岸交流的措施等。


两党希望，这次访问及会谈的成果，有助于增进两岸同胞的福祉，开辟两岸关系新的前景，开创中华民族的未来。(完)





【时事点评】在东方评论员看来，“胡连会”达成的“共同体认”，最有份量的具体成果就是两党再次将“九二共识”置于“头条头款”的地位、从而为“两党”共同反对“台独”奠定了坚实的基础。

*** “堵嘴的小动作”还是没能堵住“见证人”连战的嘴

在昨天的点评中，我们还以台湾“总统府”秘书长抛出的一个“歪理”（参阅4月28日《东方时事解读》）、对陈水扁欲堵台湾“前行政院长”的嘴的意图进行过分析，然而，今天我们特别地留意到，连战在致答谢辞时，还当着媒体的面、不仅提及93年达成“九二共识”的“汪辜会谈”、有意思的是，他还特意点出“我那时是在做行政工作”。

在东方评论员看来，连战是“有心还是无意”我们不得而知，然而，就结果而言，尽管“有点不放心的”陈水扁匆忙间抛出的那一套“歪理”、尽管他的秘书长游锡堃是一口就表明：“没有九二共识”，但是，这些“封堵的小动作”还是没能堵住“见证”“九二共识”全过程、当时正在台湾“行政院长”任上的连战的嘴。

*** 端出“九二共识”的连战、可以说已经取得了此行的“完胜”

我们认为，由于连战这次是不顾陈水扁隔着海峡的一再“警告”、以及国民党内一直就没有停过的“杂音”、勇敢地一把就将他在任台湾“行政院长”时、台湾“海基会”与大陆“海协会”共同达成的“九二共识”给端了出来，可以说已经取得了此行的“完胜”。


*** 在历史上，“九二共识”就来得不容易

东方评论员认为，在连战顶住来自党内派系的压力、顶住“台独”当局的压力、而抢先将“九二共识”和盘端出之后，事实也就没有什么可顾虑的了。因此，我们也就可以在“新闻公报”中清楚地看到“共同体认”之后的“五条具体意见”。

首先，我们先来看第一条和第二条。显然，这两条的核心就是“和平谈判”，和“和平协议”、而根据公报，显然，“和平谈判”的基础就是两党“共同体认”的“九二共识”。

东方评论员认为，在历史上，“九二共识”就来得不容易，今天，这个“九二共识”来的更不容易。

*** 李登辉不得已采取的“以退为进”的做法

上世纪80年代末、90年代初期，由于前苏联的瓦解，美国加紧了对中国以“和平演变”为手段、以分裂、瓦解中国这个“大一统”的国家为目的的战略颠覆进程。然而，中国当时遭遇的内乱，以及前苏联的瓦解、都没有让美国为首的西方看到中国有分裂、瓦解的迹象。

只是目睹这一切的国际反华势力，以美国、日本为代表，在感觉到瓦解前苏联的那么一套、既通过“和平演变”这一手段来瓦解中国的战略“出了问题”之后，开始调整战略，并执行另一套以“遏制中国”为主的战略，其中的一个重要部分，就是借“台独”来干扰、消耗中国的经济和国力、从而达到延阻、甚至再次打断中国现代化进程的目的。

这些当然引起了北京的警惕，从而内部产生了“是否要”解决台湾问题的想法，在我们看来，当时的李登辉是刚上台不久，根基不牢，而台湾岛内“反独”力量仍然十分强大，对台独仍然是一片“喊打声”，李登辉不得已采取了“以退为进”的做法，既，在93年与大陆达成了这个“一个中国、各自表述”的“九二共识”。


*** 以“九二共识”为转折，台湾的政治生态开始加快“量变”

自93年起，就是由于有这个“九二共识”，两岸可以说算是暂时建立了一种“政治互信”，所以，海峡两岸才有了那么一段“时间不短的稳定时期”，而大陆的经济改革也经过调整、从那之后、开始又一轮的“快速增长”，而另一方面，台湾的政治生态却也从那之后开始加快“量变”。

也就是在这一大背景下，经过一段时间后，一直受外力操控的台湾内部政治生态、终于由量变到了质变、这表现在，台湾岛内的统派势力、国民党元老、均遭到美国、日本、台独势力的联合打击，台独势力用各种手段一边分裂国民党、一边扶植民进党，与此同时，“九二共识”也开始被“台独”和支持“台独”的国际势力有计划、蓄意抹杀、否认，直到李登辉拋出了“两国论”、公开挑畔“一个中国”原则，并以此为高潮。

*** 支持“台独”的国际势力否认“九二共识”的目的

而台湾政治格局真正产生“剧变”，则是2000年台湾实现了第一轮“政党轮替”，已经被李登辉严重分化的国民党下台，而有“台独党纲”的民进党一上台，就立刻开始全面、忠实地执行着李登辉拟定的台独计划，通过“去中国化”等一系列手段、从而让“台独”势力是“急剧坐大”，直到在岛内实行“绿色恐怖”。


在东方评论员看来，不论是李登辉抛出的“两国论”，还是陈水扁炮制的“一边一国论”，本质上都是美国、日本这些支持台独的国际势力、想以否认“九二共识”为手段，达到挑战“一中原则”，从而利用“台独”、“藏独”、“疆独”这些大大小小的分裂势力，以“没完没了”的方式、去干扰、甚至打断中国的现代化进程、直到最后实现分裂中国、彻底瓦解中国的战略目的。

而“台独”势力，也想借“美国、日本一心想遏制中国”的战略企图之机会、以“配合国际反华势力”为手段，最终实现其“台独”的目的。

在这里，东方评论员想强调一点的是，只要看看美国、欧洲如何利用一个小小的车臣闹分裂、去削弱俄罗斯的过程，以及这个过程对俄罗斯产生的巨大战略杀伤力，我们就不难明白反华势力为何如此看重“台独”等分裂势力的战略价值的了。


*** 从这份“新闻公报”开始，“九二共识”已经不是什么“有没有的问题”了


显然，北京“如此看重”这个“九二共识”的理由也就非常清楚了，那就是，借连战“以当事人的身份”、去证明“九二共识”不仅存在，而且这个“九二共识”、还是直到李登辉抛出“两国论”为止、“两岸几年和平”最大的保障。

现在，从这份“新闻公报”开始，“九二共识”已经不是什么“有没有的问题”了，而是陈水扁当局“承认不承认”的问题了，也就是说，是陈水扁“要不要”、以及什么时候要“台海和平”的问题了。


*** 剩下来的事情就是“需要有专门的人”去将“五大条”逐一落实

现在，就通过这个“新闻公报”的“五大条”，“地球人都知道”连战已经“全部搞定了”“两岸关系”的重大原则问题，剩下来的事情就是“需要有专门的人”去将“五大条”逐一落实、显然，连战和国民党通过一再强调自己是在野党这一事实，已经将这个皮球给一脚开至陈水扁、民进党、这种“专门的人”的脚下。

在东方评论员看来，如果陈水扁、民进党按“国共两党”谈妥的那样去做的话，那么，这不仅是两岸的双赢，也是东亚国家、以到整个亚太、全球社会的、所有“真正希望和平”的人们之福音。


*** 大陆在如何“下好连战、宋楚瑜这两枚棋子”的手法上，显得非常灵活


东方评论员认为，胡锦涛和连战在“历史性握手”之后、谈妥的这份“新闻公报”，事实上已经正式地将球踢到了陈水扁的脚下，也就是说，只要陈水扁承认“九二共识”，只要回到“一个中国”，那么，接下来当然是“什么都好说，什么都好办”。

事实上，从这份“新闻公报”中，东方评论员再次看到大陆在如何“下好连战、宋楚瑜这两枚棋子'、并以此去促进连战、宋楚瑜、陈水扁、以及国民党、亲民党、民进党相互竞争的手法显得非常灵活。

在我们看来，这种灵活性表现在大陆以“先声夺人”的手法，可以说是一把就将宋楚瑜、陈水扁可以拿到台面上“公开砍价”、或者准备拿来在桌子底下“私下要价”的“所有要点”“都一次批发”给承认“九二共识”的连战和国民党了。


*** 两岸关系“所有要点”，北京“一次批发”给承认“九二共识”的连战和国民党了

东方评论员认为，在连战顶住党内、以及陈水扁的压力，表现出足够的勇气将“九二共识”一口气承认到底之后，可以说，大陆对连战和国民党也是“异常的慷慨”，可以说凡是台湾社会高度关心民生问题、凡是可以帮助连战、国民党提高民望的政治利益、凡是陈水扁准备用来在今后去与大陆“讨价还价”筹码、准备拿来做文章的“题材”、风是华盛顿急于从这一轮“两岸缓和”中捞到的战略利益，可以说，北京是一把全部划到了连战、国民党的“功劳簿”下。


就象“两党峰会”达成的“联合新闻公报”中所列举的那样，连战此行是成果丰硕：什么华盛顿想要的“和平协议”问题，国际社会、特别是周边国家想要的“正式结束两岸敌对状态，建构两岸关系和平稳定发展的架构，建立军事互信机制”问题、台湾经济界想要的“两岸共同市场问题”，还有台湾社会非常关心、向来被用来大做文章的的加入世卫组织等问题，特别是真正可以让两岸双赢的“两岸三通”“经济全面交流”的问题、可以说都是些包括华盛顿在内的方方面面“牵挂不已”的事情，全部被连战给“一网打尽”了。


*** “新闻公报”，是北京对连战“真正”的“实质性最高礼遇”

连战访问中所受到的礼遇、无疑是中央可以给他的“最高规格”。事实上，在东方评论员看来，通过这份“新闻公报”，大陆对勇敢“见证”“九二共识”的“当事人”连战和他的国民党，“真正”给出了“实质性最高礼遇”，那就是让连战和国民党在这一轮台湾岛内政治的角力中、事实上“已经处于了不败之地”。（当然了，在这里需要提一句的是，连战回台后，可能受到的最大冲击是来自国民党内部的，这是后话，东方评论员将在今后的《东方时事解读》中进行展开）。

首席评论员指出，在大陆给了连战“实质性最高礼遇”的同时，又何尝不是在对稍后就将登陆的宋楚瑜“紧紧进逼”？何尝不是在对陈水扁“招招致命”？

*** “豁出去了”的连战、这次对宋楚瑜和陈水扁也“忒狠心了”，

事实上，在看到这份“新闻公报”后，东方评论员有一个共同的感受，那就是，“豁出去了”的连战、这次对宋楚瑜和陈水扁也“忒狠心了”，可以说是将宋楚瑜、陈水扁能拿上台面、与大陆讨价还价的东西是“一网打尽”，其中，最狠的一招就是没有将“九二共识”再模糊几天、从而给宋楚瑜、甚至是陈水扁留一点儿“嚼头”。

东方评论员认为，“豁出去了”的连战可谓是一不做二不休，还在“新闻公报”中“大谈特谈”“两岸三通”问题，显然，连战连“两岸三通谈判”的“题材”也没有给、宋楚瑜陈水扁留下，在东方评论员看来，在拿走了“九二共识”“两岸三通谈判”这两个北京最感兴趣的“题材”之后，我们真不知道宋楚瑜过几天的“搭桥之旅”还有什么好“建材”、去在北京的“胡四点”和华盛顿安排下的“十点共识”中“铺路搭桥”。

*** 可能是连战准备承认“九二共识”的消息提前泄了

不过，倒也的确有一则轰动性的消息传来。之前，就在陈水扁抛出“那番歪理”的当天，也有消息说，宋楚瑜在会晤胡锦涛时，将代表亲民党面邀胡锦涛访问台湾，进行了解之旅，此议并已获得对岸高层的若干默契。

显然，东方评论员认为，就“创新”的角度来看，“邀请胡锦涛到台湾”当然是个“创意”无限的点子，可问题有两个，第一，如果宋楚瑜亲自邀请，那么，宋楚瑜是以什么份邀请？是陈水扁的特使吗？如果是，那么，宋楚瑜恐怕这次根本就到不了北京、也就根本没有亲自邀请的机会了。

第二，可以肯定的是，胡锦涛不会在陈水扁不承认“九二共识”的情况下去，而陈水扁如果愿意承认“九二共识”“也不会愿意”胡锦涛到台湾去“贬低他”，因此，这根本就是一个“没有解”的问题。

当然也有一种可能，那就是，可能是连战准备承认“九二共识”的消息提前泄了，所以，在胡锦涛见连战前，陈水扁的“歪理”和这则“没有解”的问题，几乎是同时登场，而最有意思的是。

东方评论员注意到，对宋可能亲自邀请胡锦涛来台访问的消息，亲民党秘书长秦金生受访时表示，他是第一次听到这种说法，强调目前无此计划，但这是“很有创意的思考”，亲民党将会再行研究。

*** 亲民党为了搞点“新东西”想坏了脑子

有意思，在东方评论员看来，亲民党秘书长秦金生就这则消息还要称是“很有创意的思考”，并还表示“将会再行研究”，如果不是“有头无脑”，那就是亲民党为了搞点“新东西”想坏了脑子。

我们注意到，亲民党希望在扁宋“十点共识”下，建构两岸复谈的基础与架构，显然，在连战已经将“九二共识”全盘端出的“最新形势”下，宋楚瑜的这种认识显然“不太合拍”，在东方评论员看来，连战勇敢地“证明”“九二共识”的存在，看来，已经打乱了宋楚瑜、陈水扁先在“九二共识”的问题上顶一阵子、接着再在“两岸三通谈判”的问题上蘑菇一番的全盘计划。

有分析人士就指出，如果散布消息者的确是橘营，那么，宋楚瑜放“亲自邀请胡锦涛来台”的这种“风”，恐怕是在试探陈水扁的口气，既，“九二共识”已经不是个筹码，而是个包袱了，显然，他宋楚瑜要实现“搭桥之旅”有所突破，就也得承认“九二共识”，并在这种基础上有所“创新”。


*** 连战逼得宋楚瑜为了想出“创意”、不得不再派他的核心幕僚张显耀周日“再赴”北京

看来，“豁出去了”的连战的确“忒狠心了”，逼得宋楚瑜为了想出“创意”、不得不再派他的核心幕僚张显耀周日“再赴”北京，与中共中央台办进行“磋商”。

这就是说，如果宋楚瑜的核心幕僚张显耀、这次不能在北京谈出个新鲜玩意出来，那么，不论是宋楚瑜的“搭桥之旅”，还是陈水扁今后可能会承认“九二共识”，并以此启动“两岸和谈”，事实上都不过将是“突而不破”，显然，他们今后如何拿不出什么“新东西”出来的话，那么，本质上都不过是在那里“炒连战的剩饭”。

显然，这是在逼稍后就要以“搭桥之旅”登陆的宋楚瑜、亲民党“再动动脑筋”、要“学习连战好榜样”，起码一条就是，“十点共识”中的“宪法一中”就不必再说。


*** 大陆提前取得这份“承认九二共识”的“证据”之意义

在东方评论员看来，已经被华盛顿、陈水扁套牢的宋楚瑜、不是说“不排除”还会在临行前去见陈水扁一面的吗？那好，道理很简单，中共与国民党已经达成了“九二共识”的共识，也就是说，大陆已经获得“九二共识”的“关键人证”（连战，当时的台湾“行政院长”）、与“确切物证”（这份新鲜出炉的“新闻公报”）。

我们认为，大陆提前取得这份“承认九二共识”的“证据”之意义，就在于“麻烦你宋楚瑜”、在正式动身前就与陈水扁商量好，将准备用来讨价还价的“九二共识”给提前划掉，首先拿去，不然，你宋楚瑜的“搭桥之旅”的“关键建材”就用错了型号，还凭什么“搭桥”？

*** 或者宋楚瑜就在这种逆境中“也勇敢一回”、做出意外的动作也不一定

显然，如果宋楚瑜还想借“十点共识”继续“打两岸关系牌”的话，那就得在台湾就与陈水扁商量，达成将“宪法一中”给换成“九二共识”的意向，不然，宋楚瑜的“搭桥之旅”恐怕是“拆桥之旅”、是自己拆自己的桥。

当然了，如果陈水扁还在那里“装模作样”、硬充好汉，不给宋楚瑜以承认“九二共识”的灵活性的话，宋楚瑜还有一个选择，那就是，继前天声明“不是陈水扁的特使”之后，再发一个声明，将他好不容量得来的“十点共识”干脆就“留在台湾”，“轻装”进行登陆，只是就算是宋楚瑜这样做，我们也看不出他如何才能“将风头盖过连战”。

不过，在东方评论员看来，或者宋楚瑜就在这种逆境中“也勇敢一回”、做出什么让我们意外的动作也不一定。


*** 陈水扁的“两岸关系牌”、在经连战、宋楚瑜这两个人的“两次拔毛”后、也许就越加清晰了


显然，有句老话，叫做“雁过拔毛”。在东方评论员看来，只要中东、中亚的形势没有大的变化，那么陈水扁的“两岸关系牌”、在经连战、宋楚瑜这两个人的“两次拔毛”后，也许就越加清晰了，即：除了承认“九二共识”、一方面“自解”面对的方方面面“要求和平的压力”，摆出一副“愿意和平”的样子、再按华盛顿的意图、以谈“和平协议”为手段，与大陆在“实质性两岸三通”的问题上“蘑菇”、去帮助华盛顿“消磨时间”、以达到其“以和待变”的战略目的之外、似乎已经无路可走。

我们认为，华盛顿、陈水扁在这个时候求“台海和平”，不过是权宜之计，除了上述“以和待变”的算盘外，还有一个重要目的，就是借“台海和平气氛”越来越浓，“台独”可能性越来越低，去刺激对台湾的战略作用更加看重日本，让日本再次跳出来、代替自己在一线支持台独、以挑畔中国。


*** 华盛顿空前热心于“台海和平气氛”背后

在昨天的《东方时事解读》中、在包括台湾、朝鲜、日本问题的整个东亚部分的点评中，一个主题始终贯穿前后，那就是：在华盛顿空前热心于“台海和平气氛”的背后、是中美在台海、朝鲜半岛、日本角色定位、中东问题、中亚问题等方方面面的角力、“正在白热化”。

就如在不久以前，许多人还不敢相信“中印大和解”、更不相信短短的时间内、台海竟然能发生“两党峰会”这样一件“历史性事件”一样，在东方评论员看来，在朝鲜半岛、在中东几大问题上，对今后局势起重大影响的、北京旨在化解美国压力的、类似于“中印和解”这样的历史性事件、其实也都在酝酿之中。



*** 美国助理国务卿希尔，带着“强烈不满”离开了北京


在我们看来，最值得关注的地方就是朝鲜半岛。就如首席评论员所指出的那样，由于北京一面坦然地接受华盛顿默许连战在宋楚瑜之前抢先登陆，而一边也始终坚守坚决维护自己在朝鲜半岛的利益、并坚决保护朝鲜的合理要求，从而让美国专程在连战前脚登陆、后脚就跑到北京来，催促朝核问题“六方会谈”开谈时间的美国助理国务卿希尔，不得不又带着“不去猜测是什么时间”的“强烈不满”离开了北京。


*** 在希尔嘟噜着“不去猜测是什么时间”的背后

东方评论员认为，在希尔嘟噜着“不去猜测是什么时间”的背后，其实是北京“不去猜测'两岸和谈'会是什么时间的、不急不忙的态度”。

东方评论员认为，显然，北京心里非常清楚，那就是，别的不说，就在东亚这个区域内，不论是今天的连战“登陆”也好，还是早一点的华盛顿“高调反华”也好，或者是小泉纯一郎“被迫道歉”也罢、“牌理”就在于：和几个月前相比，倒不是中国本身的实力这么短时间里就提高了许多，而是美国在全球战略上、实在是“太被动”了。


*** 中国在这轮“中美日”的角力中、所体现的实力表现在几个方面

当然，在我们看来，中国在这轮“中美日”的角力中、所体现的实力表现在几个方面：

首先，迫不得已时，北京有能力用一个“恶化的朝核问题”去“彻底颠覆”美国受益最大的东亚安全框架，从而迫使华盛顿在无力处理好中东问题的时候，就得面对提前调整东亚安全政策的巨大困难；因此，在背后唆使日本挑畔北京的华盛顿、到了关键时刻就会为了自己的战略利益、“自觉地”去配合北京，敲打一下日本。

其次，是中国和印度和印度尼西亚这两个亚洲大国达成了战略和解，在东方评论员看来，我们必须强调的是，“这种性质的和解”的基础显得“非常牢固”，因为，它是建立在中印、以及中印（尼）两国都在强调经济发展、且彼此经济高度互补的基础上的，也是建立在都意识到美国霸权威胁到各自国家安全的基础上的。


*** 华盛顿的决策层“太现实了”

我们知道，华盛顿对待印度的态度非常清楚，那就是：印度只不过是美国战略棋盘上的一个棋子，双方绝非平等的“战略伙伴”。

根据我们的观察，印度的决策层也明白，华盛顿之所以如此看重印度，主要是想拉拢印度、象日本那样“进入美国全球战略轨道”，与日本一起，一东、一南，成为保持亚洲军事平衡的两支重要力量，从而利用中日对立，截断中国往东走海路，获取南海资源、和中东能源的生命线，往南，则利用中印对立、截断中国经南亚到中东的陆上能源线，以及经印度洋到中东的海上能源线。

显然，华盛顿的决策层“太现实了”。不过东方评论员也不奇怪，因为保守主义者天生就有两个特点，一个是“现实性”，第二个，就是“急功近利性”。

东方评论员认为，在华盛顿的保守主义战略决策者的眼里，根本就没有想过印度现在最想的是在如何保障安全的同时，去如何更好的发展经济，而不是去为美国的利益去各中国搞对抗。在我们看来，几十年的事实证明，印度人不难总结出这么个结论，那就是，在历史上，印度和美国、前苏联都联过手，但从来就没有与中国的对抗中，获得过什么明显的利益。


*** 北京“可以继续暂不理会”华盛顿“要求”的原因


不难看出，华盛顿在印美关系上的充满冷战思维的“过分现实”，完全无视印度的国家利益的“自私思维”，都是印度决心重新定位与中国战略关系的重要原因，谁都明白一个道理，那就是“和则两利，斗则俱伤”，何况中印之间的在能源、经济、国家安全战略上、也有许多重大的共同点。

显然，在印度与中国决定建立战略合作关系时，双方的理由也是“太现实了”，那就是“经济发展才是硬道理”。

我们认为，这些都是北京在台海和平“没有根本得到保障”之前，决定“可以继续不理会”华盛顿要求中国在朝核问题上立刻“拿出行动”的重要因素。

*** 台海和平的“根本保障”主要有两点

首席评论员就指出，就算是陈水扁承认“九二共识”，两岸开启和平谈判，达成了“和平协议”，但是，我们认为，这种“台海和平”是“没有根本得到保障”的。

在东方评论员看来，台海和平的“根本保障”主要有两点，一是中国有让任何人不敢轻举妄动的军事能力，二就是“两岸实质性的三通”，就是让两岸全方位，深层次的交流起来、整合起来，彻底断绝“台独”和国际势力“打台独牌”的战略空间。

在东方评论员看来，这两方面是缺一不可，不然，只要不改变其独霸世界的全球战略、华盛顿对利用“非和平台独”来为自己渔利、是永远也不会死心的，也永远不会主动放弃“台独牌”的。因此，我们认为，北京在做到上面两点之前，任何在其它方向上的战略交换，都应该“小心再小心”。

*** 北京在与华盛顿的一系列战略合作问题上，更多的只能是“虚以委蛇”

再就是，一个缓和、经济融合的朝鲜半岛，事实上也是对台海问题的一种重要保障。在东方评论员看来，北京在朝核问题上的任何让步，都不应该影响到确保朝鲜能顺利进行经济改革、都不应该影响到韩国能顺利与朝鲜进行经济合作的进程，在短期内，这是确保韩国与美国、日本保持足够距离的前提。

我们的观点是，不论是连战今天成果丰硕的“和平之旅”，还是宋楚瑜即将展开的“搭桥之旅”、更或是陈水扁有朝一日被迫承认“九二共识”、“两岸启动和平谈判”、达成“和平协议”，在东方评论员看来，类似的这些“已经取得的”、或者可能会取得的成果，都是“没有根本保障”的。

因此，东方评论员认为，在“两岸三通”没有到达“不可逆转”的程度之前，北京在与华盛顿的一系列战略合作问题上，特别是伊朗核问题、朝核问题上、更多的只能是“虚以委蛇”。令人欣慰的是，根据我们的观察、那位兴冲冲与连战同天到达大陆的美国助理国务卿希尔，最后又在“气呼呼”中离开北京，似乎已经说明北京好像就是这样做的。

在一段来自汉城的消息之后，东方时事评论员、东方军事评论员将继续就美国助理国务卿希尔，带着“强烈不满”离开了北京之后中的朝核问题，进行进一步的点评。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
