# -*- org -*-

# Time-stamp: <2011-08-02 20:54:32 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

#+STARTUP: indent

* 05年4月28日 星期四

** 胡连会共识适当表达北京仍盼多接触民进党

【综合消息】据报道，国民党主席连战抵京前夕，中共中央台湾办公室副主任孙亚夫27日晚在北京大学演讲时表示，此次连战来访，属于国共两党间的问题，双方若达成共识或者文件，也会考虑台湾的有关法律，采取非常适当的方式来体现。

胡连会共识将适当表达

孙亚夫说，国民党副主席江丙坤访问大陆后，台湾当局竟然要「法办」他，大陆方面已注意到，并在事后也对台湾相关的法律进行了解。他透露，此次连战的大陆之行，双方若再次达成共识，会考虑到台湾的有关法律，采用非常适当的方式来体现。因为国民党毕竟是在野党，大陆若与其达成共识或者文件，属于两党之间的问题。


宋楚瑜不代表陈水扁

对于连宋两人登陆的异同，孙亚夫表示，两者的相同点都是认同「九二共识」反对「台独」。不同点则是，宋楚瑜有「扁宋会」的基础。目前亲民党方面希望在「胡四点」与「扁宋十点」中扮演桥梁的角色，用两岸的新成果来约束陈水扁搞「台独」。由于「扁宋十点共识」非常复杂，而亲民党的构想亦相当复杂，所以宋楚瑜的大陆访问也比连战来访复杂些。孙亚夫还强调，既然邀请宋楚瑜来访，那么双方所交流的问题就是两党间的问题，宋楚瑜并不代表陈水扁。


欢迎民进党学者来访

孙亚夫表示，陈云林主任在近期接受访问时经常提起民进党，意思是说在这种情况下，大陆「还想和民进党多发生一些关系」。

孙亚夫说，近年来，有不少民进党成员以个人身份来大陆，并不代表民进党。一些高校和学术机构举行的活动，欢迎民进党学者来访。大陆也认为大多数民进党成员与「台独」分子不同。他指出，若民进党机构推动台湾农会来大陆谈农产品在大陆销售的问题，大陆也欢迎。

结束敌对即可进新阶段

至于胡锦涛总书记与连战的世纪会谈，能否称为两岸结束内战状态的标志？孙亚夫表示，此事尚在研究中。但他深情地说，「如果有一天，双方能够达成结束敌对状态的协议，那么两岸关系将进入全新阶段」。

孙亚夫坦言，在对台宣传方面，也有人提出批评，认为大陆所使用的语言、方式与岛内的距离较远。大陆在两岸问题上采取主动、重大的动作是非常必要的，如连战来访，台湾媒体自然会探索其来访的意义、影响，这样就可向岛内民众宣传大陆。


不宜提第三次国共合作

孙亚夫还强调，国民党主席连战是次访问大陆，国共两党并未提及第三次国共合作，原因在于现在尚不适宜提这个主张和口号。

孙亚夫解释，正如外界注意到的那样，国共两党目前都没有提到第三次国共合作。但这不意味着这个提法不对。事实上，中共过去有过这个主张。只是现在不适宜提这个主张或口号。

孙亚夫表示，国民党主席连战访问大陆是国共两党、两岸关系中的一件大事。我们提出欢迎认同「九二共识」，主张发展两岸关系的台湾党派、团体访问大陆，交流对话。国民党认同「九二共识」、反对台独就是一个重要的政治基础。



【时事点评】东方评论员注意到，中共台办副主任孙亚夫的这番讲话谈到几个要点。

首先，请大家注意这一段：孙亚夫说，“此次连战来访，属于国共两党间的问题，双方若达成共识或者文件，也会考虑台湾的有关法律，采取非常适当的方式来体现”。

*** 大陆的这种担心纯粹是在为国民党的日后“着想”

显然，大陆的这种担心纯粹是在为国民党的日后“着想”，然而，在东方评论员看来，虽然孙亚夫是在借“国民党副主席江丙坤访问大陆后，台湾当局竟然要'法办'他”的事实，为国民党“叫屈”，但是，事实上在江丙坤与大陆谈妥了“十二点”之后，陈水扁一“没有法办成”江丙坤、二也“没有阻止住”连战正式登陆，原因很简单，美国人“不认为这是个好办法”。

*** 孙亚夫在这里“哪壶不开提哪壶”为哪般？

因此，事实上，在东方评论员看来，我们看不出陈水扁有将连战“真正移交法办”的胆子，而只看出陈水扁有借国民党无权与大陆达成涉及台湾“公权力”协议为名、想压连战在大陆“少说两句”的想法。

不难看出，孙亚夫在这里“哪壶不开提哪壶”、是在有意借防止陈水扁“再次法办”国民党，而开始为连战的北京之行的结果“定调”，可以肯定的是，这种“定调”在“党对党”的“愿望”不会来自大陆方面，而只会是来自国民党方面。

*** 我们已经说过，连战如果“胆子够大”，那么.....

在之前的点评中，我们已经说过，连战如果“胆子够大”，敢抢在陈水扁、宋楚瑜之前、完全承认当年的“汪辜会谈”、就有“九二共识”这么回事，从而就可以将陈水扁准备在“十项共识”基础上、拿着“九二共识”当筹码、去与大陆“讨价还价”的计划全盘破坏。

东方评论员认为，一旦连战这次将陈水扁最看重的“九二共识”这把筹码、“一股脑”毫无保留地“交给”大陆，实际上就意味着将陈水扁、宋楚瑜搞的那个、欲置国民党于死地的“十点共识”、就一把给“扔到垃圾堆里去了”，如此一来，他将取得这次大陆之行的“完胜”。

*** 有理由相信他多半会在与中共达成的共识中“涉及到这一点”

首席评论员就指出，尽管我们对连战有胆量一把就完全承认“九二共识”有疑问，但是，我们仍然有理由相信他多半会在与中共达成的共识中“涉及到这一点”。东方评论员认为，连战既然是“为了活下去”而到大陆来的，那么，他也一定会为了他、以及他的国民党更好的活下去、尽可能地去创造条件。

我们知道，“九二共识”是国民党执政时、在93年“汪辜会谈”中达成的，因此，如果连战在这个时候对“九二共识”没有个态度，那么，如果他日亲民党的宋楚瑜、或者民进党的陈水扁承认了“九二共识”，那又反过来将置连战这个当年的台湾“行政院长”、一个“知情者”、以及国民党这个“版权拥有者”于何地呢？


*** 陈水扁在连战登陆之前苦苦相邀、麻烦安排一个“连扁会”的目的


显然，东方评论员认为，陈水扁在连战登陆之前苦苦相邀、麻烦安排一个“连扁会”，除了想将连战“罩在”自己“创作”的“十点共识”的影子下、将连战塑造成自己的“代言人”外、另一个重要目的，就是约定对“九二共识”的“口径”。

在我们进一步讨论这个话题前，再来看一段新闻报道。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 台当局提两岸和平促进法三原则称无92共识

【台湾消息】台“总统府”秘书长游锡堃昨天对所谓“两岸和平促进法”，提出“三原则”底线，即：“没有九二共识”；“若相关组织设在‘总统府’，府方可同意”；“相关法律不应该侵犯‘总统’职权、须符合宪法原理”。

另据“中央社”报道，游锡堃称，只要符合这三原则，府方都可以接受。他并称，“和促法”目前在“立法院”协商，“总统府”未参加讨论，目前态度是只要符合三原则，其它内容不会多加干预。


【时事点评】在我们继续点评这则消息之前，想说几句闲话。东方评论员记得，就在12年前、也就是93年4月29日，据先前的资料，“两岸”的“海协会”和“海基会”通过“汪辜会谈”、达成了“九二共识”。

*** 那个所谓的“相关组织”、恐怕就是指的“海基会”了

请大家注意这位刚从“行政院”搬到“总统府”的游锡堃所说的这句话，他说：“若相关组织设在‘总统府’，府方可同意”；在东方评论员看来，这位卸任“行政院长”才不过两个月的现任台“总统府”秘书长，可以说是“脸是变得真快”。

如果我们没有估计错的话，他刻意“不想说清楚名讳”的“XXX”，也就是那个所谓的“相关组织”、恐怕就是指的“海基会”了。

*** 一种解决“九二共识”僵局的“好办法”

的确，“海基会”是不设在“总统府”，按游锡堃的这种逻辑、不是“总统府”的“海基会”“所签的字”，“总统府”就“可以不同意”，不认账，在东方评论员看来，这种“歪理”非常有意思，按这种逻辑推理，“海基会”是台湾“行政院”的，那就只好请台湾的“行政院”去认账好了，可问题在于，台湾“行政院”也不在“总统府”内，这就是说台湾“总统府”仍然不可能认账，不过还好，在东方评论员看来，只要民进党的台湾“行政院”出来“认账”，相信大陆“不会不满意”的，这倒也不失为一种解决“九二共识”僵局的“好办法”。

*** 台前“行政院长”游锡堃是一口就代台湾现“行政院”谢长庭表明了态度

只是又轮不到台湾“行政院”说话，这不，这位台“总统府”秘书长、前“行政院长”游锡堃是一口就代台湾现“行政院”谢长庭表明了态度：“没有九二共识”。

在东方评论员看来，台湾就是怪事多，既然“海基会”是“行政院”的，那么按游锡堃的逻辑、既然“总统府”不用负责，有没有“九二共识”、就得由“行政院”说了算，可是台湾的“总统府”偏不让台湾的“行政院”说话，总而言之一句话，在“九二共识”有与没有的问题上，台湾现在的“行政院”已经落得了个、是“说有”也没资格、说“没有”也没有资格“尴尬境地”。

*** 陈水扁“摆这道歪理”的意图何在？

这就不由让人疑问？陈水扁这位台湾“大总统”在这个时候、让他的秘书长出来“摆这道歪理”的意图何在？在东方评论员看来，这恐怕是台湾“总统”、在急着堵台湾“行政院长”的嘴，说准确点，是在忙着堵台湾“前行政院长”的嘴。

*** 看来，陈水扁对连战“还是有点不放心”

显然，在93年4月29日，“海基会”董事长辜老先生在“九二共识”的文件上“签字画押”时，连战正是当时的台湾“行政院长”，不难看出，陈水扁“摆这道歪理”的意图之一，就是为了堵连战这位“前行政院长”的嘴，防止连战在北京“口无遮拦地”说出他任台湾“行政院长”时、所听过、看过、甚至做过的一些事情，显然，按陈水扁让他的秘书长“未雨绸缪”抛出来的“这番歪理”，分明就是在摆一副“你连战就是说了也不算”的蛮横态度。

看来，临近“胡连会”的前夕，陈水扁突然表现出对连战“还是有点不放心”，这在东方评论员看来是个值得重视的信号，在我们看来，陈水扁“不放心”这是好事情，他越不放心就意味着我们“可能会称心一点”。然而，我们是否会因陈水扁的“担心”而“称心”一点，只有是“静等明天'胡连会'的结果了”，但愿意陈水扁的“担心”没有让我们失望。


东方评论员还注意到，孙亚夫在谈完国民党的事情之后，接着谈的就是宋楚瑜和亲民党访问团登陆事宜，在我们具体展开之前，我们也来了解一下宋楚瑜“登陆”的安排情况。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 宋楚瑜行程曝光定位为“搭桥之旅”

【综合消息】综合报道,中共中央台湾工作办公室27日宣布，中共中央台湾工作办公室与亲民党有关方面商定：应中共中央和胡锦涛总书记的邀请，亲民党主席宋楚瑜一行将于5月5日开始访问西安、南京、上海、长沙和北京五个城市，12日离京返台。

据香港大公报报道，在台北，亲民党秘书长秦金生27日举行记者会，宣布了党主席宋楚瑜访大陆的行程，并定位此行为「搭桥之旅」，除5月8日在上海拜会海协会会长汪道涵外，并可能于5月10日或11日会晤胡锦涛，由于胡锦涛目前仍在国外访问，所以宋胡会晤时间将在敲定后再公布。

宋楚瑜一行的详细行程如下：5日启程前往西安，6日祭拜黄帝陵后，搭机转往南京；7日谒中山陵，并拜会江苏省委。下午赴上海，拜会上海市委后，夜宿上海。8日在上海与台商座谈，并拜会汪道涵；傍晚搭机前往长沙，出席湖南省委晚宴。9日上午回湘潭祭祖，并与乡亲会面；当天晚间搭机抵达北京，同时参加中共中央欢迎晚宴。10日、11日在北京行程尚未最后敲定，但确定将会见胡锦涛与相关人士。12日在清华大学演讲，并在北京饭店举行记者会后返台。

秦金生说，亲民党访问团成员约80多人，立委人数相当多，并有60多名记者随团采访。

宋楚瑜此行无意扮演「特使」角色

另据香港文汇报报道，亲民党高层人士透露，宋楚瑜与中共中央总书记胡锦涛的会谈，主要讨论两岸的定位问题，不排除有一些文字性表述。

亲民党政策中心主任张显耀说，「胡宋会」将主要讨论两岸问题：「宋楚瑜主席今次前往大陆，将讨论两岸目前最关键、也是最核心的问题，就是两岸的定位问题，即是如何在九二共识的基础上来定位两岸关系」。张显耀进而说，因为只有两岸定位处理完之后，才能建立和平架构。「建立和平架构非常重要。两岸关系只有在这架构下，才能够展开实质性的交流和对话。」

他透露，胡宋会谈有些议题目前还未定案，双方还会就内容议题继续进行沟通，交换意见，未来一个星期会继续与北京沟通，进行幕僚作业。他强调，胡宋会谈不排除有一些文字性的表述。

党对党交流不做「特使」

对于宋楚瑜充当「特使」传闻，张显耀澄清说，宋楚瑜这次访问经过协调，定位为党对党模式，因此，宋楚瑜主席的访问是代表亲民党，绝不可能代表任何人和任何政党，甚至政府。他重申，宋楚瑜此行无意，也不可能扮演什么「特使」角色。


【时事点评】我们注意到，宋楚瑜的手下、在宣布了宋楚瑜访大陆的行程的同时，也抛出了一个“新名词”，即定位他们的宋主席将以“搭桥之旅”的名义“登陆”。


*** 宋楚瑜要搞的“搭桥之旅”又是个什么“东东”？

经过几天的新闻“轰炸”、和连战的几场演讲，大家对连战的“和平之旅”可以说是“理解得没有问题了”，只是宋楚瑜要搞的“搭桥之旅”又是个什么“东东”？

在东方评论员看来，要搞清楚这是个“什么玩意儿”，就又得从“扁宋会”、从“十点共识”说起。

我们知道的，宋楚瑜之所以“不能抢得头彩”、头一个“登陆”，就在于他急急忙忙的“扁宋会”，并被迫要扮演陈水扁“代言人”的身份、去把“扁宋会”的结果--“十点共识”揣到北京来。

在东方评论员看来，在宋楚瑜表示“只代表亲民党，除此之外，绝不可能代表任何人和任何政党，甚至'政府'、不可能扮演什么'特使'的角色”之后，才被北京作为“第二个邀请对象”。

*** 在扔掉了不承认“一个中国”的陈水扁之“特使”的身份后，自然非常符合“一个标准”

显然，在宋楚瑜被北京“连打带消”、打掉了其陈水扁“代言人”的身份之后，由于是华盛顿的安排，他也就仍然放不下那个“十点共识”。东方评论员认为，胡锦涛在“四点意见”中已经提到，台湾的任何政党、任何个人，只要承认“一个中国”，那么大陆就可以与之坐下来“随便谈”、而且是什么都可以谈。

不难看出，宋楚瑜在扔掉了不承认“一个中国”的陈水扁之“特使”的身份后，自然非常符合上述的这个标准，这也正是大陆仍然邀请承认“一个中国”的宋楚瑜、和他的亲民党“稍后登陆”的基础。

*** 大陆邀请“已经符合登陆标准”的宋楚瑜、做此“搭桥之旅”的本意

对于连宋两人登陆的“相同点”，我们注意到，孙亚夫对此就有非常准确的“提炼”，即：两者的相同点都是认同“九二共识”反对“台独”。而对于两者的“不同点”，东方评论员则认为，这从连战定位为“和平之旅”、而宋楚瑜而定位在“搭桥之旅”这两个名词差异上就可以看得出来。

事实上，宋楚瑜所谡的“搭桥”，就是想在“胡四点”与“扁宋十点共识”之间“穿针引线”、“扮演桥梁”的角色。在之前的点评中，我们已经说过，大陆对陈水扁“白字黑字地”承认“宪法一中”、却又“隐埋大量地雷”的“十点共识”，是一种“反对也不是”，“赞成也不恰当”的心情。

显然，在宋楚瑜“不是陈水扁特使”的“保证”下，在国民党已经先行登陆的情况下、如何利用宋楚瑜、迫使“十点共识”在已经承认“宪法一中”的基础上、如何“再进步一步”，去符合“胡四点”中要求的“一个中国”、“九二共识”，大概就是大陆邀请“已经符合登陆标准”的宋楚瑜、做此“搭桥之旅”的本意了。

*** 对这次所谓的“搭桥之旅”，宋楚瑜和亲民党可以说是“将自己拔得很高很高”

此外，东方评论员也注意到，对这次所谓的“搭桥之旅”，宋楚瑜和亲民党可以说是“将自己拔得很高很高”，一个典型的说法，就是亲民党强调“要用访问成果”去约束陈水扁搞“台独”。

只是在我们看来，宋楚瑜、亲民党“说这话”有点与“反分裂国家法”抢彩头的味道，谁都知道，直到目前为止，真正能约束陈水扁“搞台独”的是美国人，而真正能断掉美国人“搞和平台独”念想的、却是大陆的“反分裂国家法”。

*** 宋楚瑜“要吹”就得在这次访问中“取得吹的本钱”

因此，首席评论员就指出，宋楚瑜事后“怎么吹”是他的事，但是，他“要吹”就得在这次访问中“取得吹的本钱”。在我们看来，这个吹的本钱就是能否在“胡四点”和“十点共识”之间，用“九二共识”当针、用“两岸三通”做线，将两者“完全的缝合起来”。

*** 历史上的经验是比比皆是

在东方评论员看来，我们之所以将“九二共识”当成“针”，就在于没有这根针，那么，被宋楚瑜拔得如此之高的“搭桥之旅”也就无从突破，而我们之所以视“两岸三通”为线，则在于没有“这根线”，两岸就无从交流、融合，结果就是陈水扁承认了“九二共识”，两岸之间也终究是“两张皮”，始终无法缝合在一起，始终会让“台独”和支持“台独”的国际势力有机会随时“撕毁”任何“共识”。

在这点上，历史上的经验是比比皆是。就在60年前的1945年，就在重庆、共产党毛泽东主席和国民党总裁蒋介石举行了“两党峰会”，蒋介石迫于打内战还没有准备好、以及国内、外巨大的舆论压力，不得已签定了“保证和平”的“双十协议”，结果，在蒋介石自认为准备妥当之后，一心要打内战的蒋介石，是毫不犹豫地、就将墨迹未干的“和平协议”一把就给撕毁了。

*** 60年前的背景”却对今天的形势有着很大的借鉴意义

现在恰好是60年后，中国共产党和中国国民党再次举行“两党峰会”，谈的又是“如何保证和平的问题”，尽管有了许多的不同，但是，在东方评论员看来，“60年前的背景”却对今天的形势有着很大的借鉴意义。

当时的情况是，是美国支持下的蒋介石、还没有准备好“打内战”，也面对着方方面面“要求和平的压力”，所以不得不暂时摆出一副“愿意和平”的样子，一旦时机成熟，就立刻置信义如草芥，弃之于无物。

现在的情况是，是“台独”和支持台独的美国，由于在中东、在东亚、在中亚、甚至在欧洲、还有许多战略布薯遇到巨大困难、许多准备工作没有准备好、还有，美国的经济仍然可以维持一定的增长、并还在正常支转，因此，华盛顿在“反分裂法”堵死了“和平台独”去路之后，出于自己的战略利益，还不敢“打台独牌”，直接与北京摊牌。

同时，“台独”也面对着方方面面“要求和平的压力”，所以，也不得不暂时摆出一副“愿意和平”的样子，愿意谈什么“和平协议”。

*** 一个绝不是美国“想与不想”、而是“能与不能”的问题

就如之前我们所一再强调的那样，陈水扁最后承认“九二共识”、回到“一中原则”，也丝毫不会令我们意外，在东方评论员看来，两岸间就是有了一份台海“和平协议”、美国人和美国人支持的台独势力，在华盛顿自认为“准备好了”之后、或者是美国的经济到了无以为继的时候，华盛顿“是否会”断然打出“非和平台独”这张牌、利用各种手段促成“非和平台独”、以此去冲击中国的战略利益，让两岸、或者让日本、台湾与中国大陆全面冲突起来，自己则在一旁坐收渔利，这绝不是美国“想与不想”的问题、而是“能与不能”的问题。

*** “非和平台独”的阴影、伴随着美国独霸全球战略的脚步仍在“如影相行”

东方评论员认为，在“和平台独”被“反分裂国家法”的“非和平方式”给一举截杀之后，“非和平台独”的阴影、伴随着美国独霸全球战略的脚步仍在前行、而并没有远去。


*** 北京绝对“要硬起来的综合安全政策”

在我们看来，在了解了华盛顿他日打“非和平台独牌”不是个“想与不想”、而是个“能与不能”的问题后，北京的国家安全政策的战略取向就非常清晰了，那就是一方面在继续以经济建设为中心的前提下，全力提高中国的军事力量、战争能力，特别是太空、海上、战略核打击、信息战等综合战力，全力提高国家应付包括社会危机、经济危机等突发事变的能力、从而让任何敢挑畔中国核心利益的势力由衷地感受到“有心无力”、以达到在军事上、经济上“不战而屈人之兵”的战略目的，这是至关重要的，也是绝对“要硬起来的综合安全政策”。

*** 在“轰轰烈烈”的“两岸和平”的问题上，北京和华盛顿显然是在“各有侧重”

其次，另一方面，就是“软的方面”，在东方评论员看来，和平是个好东西，谁都想，特别是对中国这个旨在致力于中华民族伟大复兴的国家、更是如此。因此，对和平，哪怕是有一万分之一的希望，也要努力争取，也就是在这种背景下，“两党峰会”才得以实现。

然而，东方评论员认为，真正的和平是需要综合保障的。因此，在在我们看来，北京在争取两岸和平的过程中，不会“不计代价”，东方评论员认为，在如何看待现在“轰轰烈烈”的“两岸和平”的问题上，北京和华盛顿显然是在“各有侧重”：

*** 北京必须解决的问题、也也必须坚持的原则

大陆是在“以和促统”，而华盛顿则是在“以和待变”，如此一来，对中国而言，如何在致力于“以和促统”的同时、时刻警惕华盛顿的“以和待变”就成了个非常现实的问题。

因此，如何在迫使陈水扁承认“九二共识”的同时、迫使华盛顿同意将“实质性的两岸三通”纳入“两岸和平”框架内、以至整个东亚、中东安全框架内，是北京必须解决的问题、也也必须坚持的原则。

在一段来自华盛顿的立场报道之后，东方评论员将谈谈朝核问题的最新进展，这接下来的讨论中，我们将今天的台湾问题北京所应该坚持的原则、延伸到朝鲜部分再行展开，以继续今天的东亚部分。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
