# -*- org -*-

# Time-stamp: <2011-08-02 20:49:23 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

#+STARTUP: indent

* 2005年4月27日 星期三

** 连战拜谒中山陵感言中华民族定会有前途

【南京消息】中国国民党主席连战率领中国国民党大陆访问团27日上午8时50分抵达南京中山陵，举行拜谒仪式。这是两岸分隔56年来，中国国民党主席首次亲临谒陵。谒陵结束后，连战在博爱广场发表了拜祭感言（全文），他勉励两岸一起追随革命先行者的脚步，共同努力，奋发图强，在二十一世纪真正做一个扬眉吐气的中华民族。

中华民族一定会有前途有出息

连战表示，今年是中山先生逝世80周年，也是对日抗战胜利60周年的纪念，在此时刻率团来创党领袖陵地致上最高敬意，是以庄严心情来这里。

连战说，中山先生领导国民革命，推翻满清建造亚洲第一个民主国家，死而后已，这不仅是他个人奋斗史，也是民族生命奋斗史。但遗憾是他无法看到不平等条约废除等历史事件。今天来到此地，尤其联想到中山先生思想，全心全心为民奉献，所谓博爱，所谓天下为公，都在牌楼上写得很清楚。

连战并指出，面对今天两岸的局势，尤其这种可以说是称为严峻的一个僵局，我们免不掉会回忆到中山先生弥留的时候，一再的昭示国人不要忘记和平、奋斗救中国。和平、奋斗，中华民族有前途、有出息，对不对？

所以在这个时刻，我们回想到这种叮嘱、叮咛，我们非常期盼大家无论是在哪里，都能够本着一个和平的、奋斗的心情，来让我们抓住这个时代，让台湾能够持续不断地经济的发展、均富社会的建立；让大陆快速地成长，完成小康社会，这才是我们今天应该认知，全力以赴的总的目标。

56年来中国国民党主席首次亲临谒陵

作为中国国民党主席的连战来到国民党创始人的陵寝地，其意义和感情非同一般。刚刚到达南京的连战主席，已多次在公众场合表达过对中山陵的特殊景仰之情。连战也将成为56年来第一位拜谒中山陵的中国国民党主席。

连战一行8点50分左右到达中山陵，为迎接连战主席的到来，中山陵特为他开启了中间的大门。连战一行进入主陵后向孙中山的石像敬献花圈，宣读祭文，行三鞠躬礼及静立默哀。连战随后又替中山陵题字“中山美陵”作为留念。


中山陵位于南京的紫金山南麓，依山而筑，坐北朝南，前临平川，后拥青峰，西邻明孝陵，东毗灵谷寺，岗峦前列，屏障后峙，气势磅礴，雄伟壮观。墓地全局呈警钟形，面积共八万余平方米。孙中山先生的灵柩于1926年6月1日奉安于此。

民众期盼两岸和平统一

27日，中山陵挤瞒了游客，上午8时30分左右，就已聚集了好几百游客，大家自发来到这里欢迎连战和参访团的到来，现场气氛十分热烈。很多游人还打着横幅，上面写着：“欢迎连战访大陆”，“两岸要和平统一”，表达对祖国和平统一的期盼。


【时事点评】今天，时事评论员们可以说是全程观看了连战拜谒中山陵的整个过程。在我们看来，我们很想通过连战的讲话、去发现点什么新东西，然而，除了那一腔让人心生共鸣的“乡情”之外，连战并没有什么说点让人眼前一亮的话来。

*** 连战三番几次“将自己归纳于中华民族”的态度是非常值得肯定的

尽管如此，从连战那篇充满感情的讲话来看，他三番几次“将自己归纳于中华民族”的态度仍然是非常值得肯定的。

东方评论员注意到，连战强调：此行是本着和平、善意、诚信为基础，大家理性交换意见，相信在对等双赢的理念下可以探讨若干问题，为两岸带来和平、为台海带来安定，为未来缔造有利基础。

*** 显然没有提及“统一”这两个我们非常关注的字眼

不难看出，在连战对于两岸“未来”概念的描绘中，东方评论员注意到，显然没有提及“统一”这两个我们非常关注的字眼，不难看出，展开“和平之旅”的连战和国民党一行，尽管“一而再、再而三”地引用中山先生留下的、比如“国人不要忘记和平、奋斗救中国”等遗言，来间接地昭示“自己的中国心”，然而，连战始终回避“统一”字眼的事实、无时不在验证着我们之前所说的，台湾的主流民意不过是在“惧战”、但却“反统”的结论。

东方评论员认为，在“必须以非和平手段”粉碎“台独重大事变”内涵的“反分裂法”正式生效后，一直“安心”于美国“与台湾关系法”的保护下搞台独的台湾社会，终于意识到美国的“与台湾关系法”无法为“台独”保驾护航，而“大陆更不是纸老虎”之后，台湾民众的第一感受就是对战争的恐惧。


*** 中美之间在台海上的这种玩了几十年的游戏，立马就是另外一种玩法了


因此，在我们看来，台湾社会目前这种“惧战”、“反统”的民意也足以让大陆将“连战登陆”这步棋最大限度地玩下去，事实上，就如我们昨天所说的那样，自连战踏上大陆的土地，“两岸之间”、中美之间在台海上的这种玩了几十年的游戏，立马就是另外一种玩法了。

在我们进一步讨论中美间这场“战略游戏”之前，先看看华盛顿对连战登陆的正式态度。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 美国欢迎并支持两岸扩展对话

【华盛顿消息】美国国务院表示,虽然台湾岛内对国民党主席连战访问大陆,有不同的看法,但美国仍然欢迎并且支持两岸扩展对话。至于连战是否会与大陆达成签署任何协议,美国不愿表示任何意见。

美国过去两周对台湾在野党领导人相继访问大陆,与大陆展开对话,一直给予正面评价,认为有助于降低两岸紧张关系。但连战启程访问大陆前,支持台独的人士在机场游行抗议,并引发流血冲突。周二美国国务院不愿评论台湾岛内因此升高的紧张对立,只表示两岸对话不但应该受到支持,还应该继续扩大。

美国国务院发言人埃雷利表示，能够增加对话,支持对话,并且能够和平解决两岸紧张的步骤,都应该受到支持以及欢迎。连战的访问是这样的例子。而我们也支持扩大此类接触。

台湾陆委会警告连战不可与大陆签署任何涉及两岸的文件。有消息指出,美国在台协会台北办事处处长包道格在连战访问大陆前,与连战会面,也表达美国鼓励对话但不希望改变台海现状的立场。但周二美国国务院拒绝证实。

埃雷利对此表示，对于他们的讨论,我不能提供你任何评论。

周二纽约时报有分析文章指出,大陆邀请台湾在野党人士访问,是孤立台独份子的策略。

国共历史性的会面也使部份华盛顿分析家对两岸前景感到乐观。美国前驻联合国代表霍尔布鲁克就表示,只要美国遵守对台湾的承诺并鼓励两岸对话,那么台海永远不会发生战争。



【华盛顿消息】我们注意到，华盛顿发言人的态度“很大方”，那就是：两岸对话不但应该受到支持,还应该继续扩大。是说真话吗？东方评论员认为，是说的真话！但是不得已吐出来的真话。

在我们看来，只是华盛顿这一番“瑭而瑝之真话”的背后，暗藏着“另外一番道理”

*** 两岸“斗争方式”的一个转折点

首席评论员就指出，抛开连战会与中央领导人“愿意谈的、能谈成的”政治议题不说，仅仅是连战亲自到孙中山墓竭陵、引用中山先生的话来“暗示自己是中国人”、而不再害怕“被泛绿抺红”这一点来看，这可以说是两岸“斗争方式”的一个转折点。

然而，我们也必须看到的是，连战在表达自己是中国人的方式上“仍然有所顾忌”，其不敢直接明示自己是中国人，更不敢谈及“统一”这两个字的事实表明，破除台湾的“绿色恐怖”，大陆还有许多事情要做、显然这中间最重要的一条就是迫使陈水扁也承认“九二共识”。

然而，事实上，在我们看来，从国民党副主席江丙坤“破冰之旅”的全面成功、在北京与大陆达成“12点共识”、连战亲自到孙中山墓竭陵为止，许多媒体一边倒的都在认为“陈水扁当局已被连战登陆逼得相当被动”。


*** 我们有必要再回顾一下“反分裂法”生效之后、台湾发生的几件事情

如果我们只将观察的目光盯在台湾这块地方、将观察的时间只局限在这一段内的话，的确是很容易得出这个结论的。然而，陈水扁的被动只是被“连战登陆”一事所逼“如此简单”吗？

对此，东方评论员认为，为了说明“陈水扁被动”的真实背景，我们有必要再回顾一下“反分裂法”生效之后、台湾发生的几件事情。

在“反分裂法”正式生效后，赖斯访问过北京，之后，就是陈水扁、李登辉搞的“326”反制游行。然而，也就在陈水扁、李登辉还在大街上闹腾的时候，向有“绿色台商”之称，且被大陆点名批判的许文龙，却突然发了个“退休感言”，声称“台湾、大陆同属一个中国”，指出台湾的经济发展离不开大陆，搞“台独”只会把台湾引向战争。　

特别有意思的是，许文龙还表示，胡锦涛主席的谈话和大陆通过“反分裂国家法”，“让他心里踏实许多”。在东方评论员看来，在赖斯访华回国之后，陈水扁在326游行中的“沉闷表演”不令人意外，意外的是，这位绿色台商许文龙却在这个时候出来和“台独”唱起了反调”。显然，这预示了华盛顿台海政策在与北京的朝核政策、中国的中东政策的对峙中、出现了“某种变化”。


显然，在东方评论员看来，许文龙如果向某些媒体说的那样，只是出于商业上的考虑，那么，这个“出身于台独”的“绿色台商”，靠着台独政府而“商运亨通”，他又为何要特意挑在“台独”势力“最需要展示力量”的“326”游行的前一天接受专访呢？

*** 仅从商业角度是很难解读许文龙为何专挑“326”这个“浪尖上”突然“反叛”的

在我们看来，许文龙挑在这个时候接受专访，不为别的、为的就是抢在“326”这天通过媒体发表一份“反独”“号外”，如此一来，他这不是在自决于陈水扁、李登辉、不是在自决于“台独”政府吗？那么他在台湾的“商业前途”和自己的“皇民情节”和“台独信仰”就不需要考虑了吗？

显然，仅从商业角度解读许文龙在“硬了一年”之后、却专挑“326”这个“台独”想挑畔“反分裂国家法”权威的浪尖上突然振臂高呼“搞台独只会把台湾引向战争”，并声情并茂地感叹说“最近胡锦涛主席的谈话和大陆通过《反分裂国家法》，让他心里踏实许多”，是非常牵强的。


*** 在之前的点评中，东方评论员曾经多次说过这么一个观点

也许大家还记得，在之前的点评中，东方评论员曾经多次说过这么一个观点，就是华盛顿如果因为中东战略、全球战略的需要，而压陈水扁承认“九二共识”、回到“一中原则”、甚至是启动“两岸三通”谈判，我们都一点也不会意外。

*** 华盛顿的“近期”对台政策是非常清楚的，那就是两手“都是硬的”

其中特别需要指出的是，如果到了启动“两岸三通”谈判一层、我们也不要对所谓的“和平统一”抱任何幻想。在东方评论员看来，华盛顿的“近期对台政策”是非常清楚的，第一，台海要稳定，第二，“台独牌”要继续准备。而且从其实施的力度上看，它抓的这两手“都是硬的”。

因此，要做到第一条，台独进程就得必须暂停，而要做第二条，那么，真正意义上的“两岸三通”那是绝对要阻止的，所以，在这一点上，只要让“两岸三通”“谈而不通”、或者是“通而不畅”，那么，就威胁不到美国对台湾在政治上的控制、也威胁不到华盛顿操纵“台独进程”的能力。我们认为，对美国人的这一套，不仅中国政府、就是台湾的各政治势力也是“心知肚明”。


*** 顺着这个思路去看许文龙，那么，所有的“迷团”也就全部消解了

如此一来，首席评论员特别指出，如果我们顺着这个思路去看“独骨”“忒硬”的许文龙于“326”的“振臂高呼”，那么，所有的“迷团”也就全部消解了。因此，在我们看来，倒又是那个向以“吕大嘴”著称的、早已经将自己摆到了下一任台湾“总统”位置上的台湾“副总统”---吕秀莲、再一次出来说了句“公道话”，她说许文龙这样说话“是有人指使”，就象她当年在美丽岛事件中的“自白书”一样，其实根本就是“别人写好的、逼她签名的”。

*** 如果是陈水扁政府指使许文龙“叛变”的，那么，又是谁在背后促使陈水扁这样做的呢？

在东方评论员看来，表面上吕秀莲将许文龙和自己类比的意思非常清楚，即与李登辉一样，都是将矛头指向大陆、指向中国中央政府，可问题是，大陆又拿什么去逼一个“台独信念”和李登辉相若、“日本皇民心态”和李登辉也可相提并论的许文龙、在退休一年之后以古稀之龄、在“硬扛”大陆打击“绿色台商”一年之后，却突然转身去“硬顶”“台独”游行造势的狂风、在3月26日这天与“台独”阵营彻底决裂呢？

显然，许文龙的“背叛”不简单，因此，台湾就有政治人物指出，想当台湾“女总统”吕秀莲、在这个时候强调许文龙的“退休感言”是“别人写的”，表面上是指大陆，然而，谁都清楚，对许文龙这么个死硬的台独分子，大陆还没有如此大的“感招力”，因此，吕秀莲其实是暗指民进党内部、台独势力内部、有人默许许文龙“叛变”的。

值得强调的是，如果是陈水扁政府默许许文龙“叛变”的，那么，又是谁在背后促使陈水扁这样做的呢？其结果是不言自明的。

*** 以“台独”为宗旨的民进党、游行中首次使用了我们看了近100年的“青天白日满地红”

在“326”这天，时事评论员们大多通过卫星电视观看了整个游行过程，说实在的，在观看的过程中，时事评论员们显然都注意到了一个细节，那就是在此次游行中，我们看到了一幕幕“别有趣味”的镜头：首先是陈水扁是“只跳舞不唱歌”，而且是“说到做到”，我们听不见这位最爱煸情的“台独”头子“说一句话”，看到了尽是他的“肢体语言”；

其次，以“台独”为宗旨的民进党、游行中首次使用了我们看了近100年的“青天白日满地红”--“中华民国”国旗，并在游行中呼喊着“相对中性”口号，其所做所为，倒象是国民党在搞游行似的，显然与之前的“台独”活动有了“天壤之别”。

*** 在“反独”立场上也一度“追随台湾民意”、而转持暧昧态度的国民党，其政治舞台似乎突然间就坍了一半


再加上事后暴出台联党不满民进党在现场禁止举“制宪正名”的牌子的插曲，不难看出，陈水扁在赖斯在北京同中国领导人充分交流、回到华盛顿之后，“接到的指令”几乎可以肯定是“不能挑畔《反分裂国家法》”这一类的内容。

于是乎，这才有了陈水扁表演的这一套“柔性诉求”以及“克制”的行动，并在行动中降低了“台独”高调，也正是如此，许文龙也恰到好处地在陈水扁、李登辉还在街上为了反“反分裂法”、而游行得“精被力竭”之际，突然与那个“号称100万大军的台独行动”挥手道别的。


然而，我们可以清楚地看出，在以“台独”为宗旨的民进党、先与亲民党签定了准备走中间路线的“联合声明”后、这次更是再次打出了“青天白日满地红”--“中华民国”国旗，先前在“反独”立场上、在以马英九为代表的一批人、也一度“追随台湾民意”、而转持暧昧态度的国民党，其政治舞台似乎突然间就坍了一半。

在东方评论员看来，蓝营的分化，华盛顿在背后操纵的台湾政治格局大洗牌，才是自感会去政治舞台之危机的国民党、在“为了活下去”（国民党副主席王人平的原话）的第一需要下，首次组团访问大陆的内在原因。


*** 这是有意在让台湾商界打头炮，迫使北京“先经济、后政治”地、加快两岸和谈的步调

这就是说，陈水扁、民进党对许文龙的“叛变”所持的态度，可以说是“非常的冷静”。在我们看来，许文龙的“叛变”根本就是“华盛顿编写的剧本”的关键“一节”，东方评论员认为，“这一节”之所以关键，就在于它是是在为启动“两岸和谈”造势。显然，这是有意在让台湾商界打头炮，迫使北京“先经济、后政治”地、加快两岸和谈的步调，而“先经济、后政治”本身就是在为“宋楚瑜拿着与陈水扁敲定的“十项共识”，走“中间路线”，去与北京谈所谓的、“名义上”可以保持几十年和平的“中和协议”。


*** 陈水扁如此这般地从台湾民众关注的经济着手、实际上是在为日后被迫承认“九二共识”做铺垫

可以非常清楚地感受到，陈水扁在美国必须“暂停台独进程”、确保台海稳定的要求之下，让许文龙“公开宣传”“台湾、大陆同属一个中国”，并指出台湾的经济发展离不开大陆，搞“台独”只会把台湾引向战争，主要有两层目的，第一，陈水扁如此这般地从台湾民众关注的经济着手、实际上是在为日后被迫承认“九二共识”做铺垫。

第二，陈水扁的民进党，通过这种几乎赞同默认台商许文龙“反叛”行为的方式，如果能拉拢广大台商、迫使北京提前、在经济层面上启动“两岸和谈”进程，那么，这将彻底将“反独立场”一度模糊的国民党边缘化。


*** 民进党欲将所谓的“中间路线”去“一统江湖”

因此，国民党要想在台湾保留一个舞台，就必须在两岸互动中找准角色，而沦为在野党的国民党，除了这种政治动作之外、又有什么牌可打呢？

所以，东方评论员注意到，就在民进党对许文龙网开一面之后不久，感觉无牌可打的国民党、就让其副主席江丙坤立刻率团前往大陆谒陵，而台立院的民进党团就在“大加挞伐”，质疑，江丙坤为何在326游行后就急着向中国朝贡、投降？陈水扁更是亲自喊话，，一边叫骂国民党已开启第三度国共合作，战略就是“联共制”、“抺红”连战。一边却也在那里一而再、再而三地建议“扁连也应排除万难，尽快坐下来谈”。

*** 一旦连战与陈水扁在“登陆之前”会面，其政治生命就会万劫不复

东方评论员就认为，一旦连战与陈水扁在“登陆之前”会面，那么，连战和国民党就都将彻底落入华盛顿、陈水扁的圈套内，其政治生命就会万劫不复。在我们看来，陈水扁在成功地用达成“十项共识”的“扁宋会”、将宋楚瑜圈在自己的阴影下之后，也想“如法炮制”将连战变成一个“嗟食者”、变成陈水扁的“代表”，从而将自己拉高成北京“唯一可以打交道的对象”。

在我们看来，还好，在北京及时迫使日本这个“美国的台湾问题代言人”让步之后，让华盛顿不得已“再次回到台湾问题的第一线”，再次“单独面对”“台湾问题与朝核问题、日本问题、中东问题等等的综合权衡问题”，经过一连串“巧妙的策应”下、连战在这个时候硬是没有在见胡锦涛之前，去见陈水扁，这就为国民党在两岸关系上、在台湾政治斗争中、在中美的角力中，保住了自己的独立舞台、为日后“有所作为”奠定了一个基础，而北京也成功地保住了台海政策的“一种灵活性”。

*** 连战得拿出“敢逼陈水扁、宋楚瑜”的勇气来才行

我们的观点是，连战不理睬陈水扁就赴大陆、虽然“可圈可点”，但是，“为了活下去”的连战和国民党、如果能“认清国际形势”、认清承认“九二共识”也是陈水扁迟早要走的“唯一出路”、继而在这次与中央领导人达成的共识中，抢在陈水扁、宋楚瑜之前、先与大陆达成承认“九二共识”这一条，那才是连战和国民党的“完胜”。

除此之外，我们并不期望在野的连战能带来其他什么令人感兴趣的东西。然而，也就是“这点东西”，连战也得拿出“敢逼陈水扁、宋楚瑜”的勇气来才行。然而，就如我们之前所说的那样，东方评论员虽然希望看到这一点，我们仍然无法“太乐观”。

*** 国民党“恍然大悟”：之前一再害怕的“抺红”，原来是个“纸老虎”！

东方评论员认为，尽管华盛顿在朝核问题上、日本战略定位问题上都受到北京的压力，而不一定“全力反对”。但是，出于连战和国民党一直“看不懂中东、东亚、南亚政局”，国民党的“马副主席”更是看不懂“反分裂法”对国际格局的重大冲击力，而匆忙“第一个起来反对”、想投机取巧，并以此与大陆划清界线，从而导致国民党内部“有杂音”、从而分化了“泛蓝”的民意，更让亲民党觉得得另找合作伙伴，这才导致最后被陈水扁、宋楚瑜玩到了“面对活下去”的“生死问题”之后，才不得不考虑“大陆行”，并又在其副主席江丙坤率团往大陆谒陵后、似乎才“恍然大悟”：之前一再害怕的“抺红”，原来是个“纸老虎”！

*** 陈水扁也在被迫地赶着时髦、开始“抺红”自己

在东方评论员看来，国民党不仅终于发现“抺红”是“纸老虎”，而且在“抺红”自己之后，还得到了陈水扁的“支持和祝愿”，从而立刻置一度欲置自己于死地的陈水扁、宋楚瑜于全面被动之中，显然，陈水扁也在被迫地赶着时髦、开始“抺红”自己。

因此，东方评论员认为，对无法看清这点，反而默许马英九这批人“去主动迎合中间路线”的“国民党决策集体”而言，我们无法对“这种政治智慧”的“决策集体”“太乐观”。

*** 陈水扁的算盘非常清楚：在“十项共识”的基础上与北京“讨价还价”

东方评论员认为，陈水扁的算盘非常清楚，那就是，准备在“十项共识”的基础上，拿着“九二共识”与北京“讨价还价”、在是包含“两岸三通谈判”、还是包含“九二共识”“中程协议”上再蘑菇一番，从而绝对避免出现一个包含“实质性的两岸三通”的“中程协议”版本的出现，要知道，这是华盛顿极力回避的结果。

*** 北京这一轮意在挑起“国亲民”三党全面竟争的“组合拳”之“目的”

因此，在东方评论员看来，连战如能顶着党内独派的压力，抢着承认“九二共识”，再行“逼宫”陈水扁、从而帮着大陆、在陈水扁的“十项共识”的代表--宋楚瑜到北京之前，就“一把就先行拿掉”陈水扁准备在“十项共识”的基础上、准备拿着“九二共识”与北京“讨价还价”的“计划”的话，那么，减少两岸间就是包含“两岸三通谈判”、还是包含“九二共识”“中程协议”上再蘑菇一番的“过程”，继而促进随后就到的宋楚瑜、也“胆子更大些”与“十项共识”拉开点距离。

东方评论员认为，促使宋楚瑜“胆子更大一点”的好处是明显的，首先就可令欲打“朝野已经达成共识”这张牌的陈水扁，一开始就“失去准星”、也得被迫调整步调，从而最终加速导致一个包含“实质性两岸三通”的“中程协议”版本的出现。

*** 北京还有什么办法让连战、宋楚瑜“大胆一点”？是我们观察的重点

如此一来，北京这一轮意在挑起“国民党、亲民党、民进党”三党全面竟争、彻底孤立李登辉台联党之“组合拳”的“目的”、也就算是达到了。

因此，在“接待”连战的过程中，北京还有什么办法让连战“大胆一点”，或者是敦促已经失去头彩的宋楚瑜“大胆一点”、也是我们观察的重点。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
