# -*- org -*-

# Time-stamp: <2011-08-23 14:52:38 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

#+STARTUP: indent

#+TITLE: 2005年01月05日 星期三


  

*** 伊情报官员认为伊反美抵抗力量高达20万人

【巴格达消息】伊拉克情报部门负责人穆罕默德·阿卜杜拉·沙瓦尼３日在巴格达对伊拉克媒体说，伊境内反美抵抗力量的人数高达２０万。

沙瓦尼说，伊反美抵抗力量的人数已超过２０万，大于美国军队在伊拉克的规模。其中至少有４万人是核心主力，专门从事战斗袭击行动。其余大部分人员则是利用部分时间参加武装行动，或者从事向战斗人员提供情报和后勤支援等活动。

沙瓦尼还认为，巴格达、萨拉赫丁、迪亚拉、尼尼微等地区的反美抵抗力量受到了当地民众的广泛支持。

美国军方和情报部门去年１０月的评估结果认为，伊拉克境内反美武装的人数在５０００至２万人之间。沙瓦尼公布的这一数字远远超过美国军方和情报机构的估计。美国军事专家认为，沙瓦尼将众多伊拉克反美同情支持者也计算在内，是造成和美国军方估算结果差距巨大的原因。
 

【时事点评】显然，在伊拉克国防部长同华盛顿唱起了反调的同时，几乎可以视为美国情报部门在伊拉克“分局”的伊拉克情报部门、也在对美国人表示“不同意见”。

● 华盛顿似乎接受了伊拉克情报部门“新统计”

按沙瓦尼的话来说，伊境内反美抵抗力量的人数按最新统计口径，已经是“高达２０万”。值得一提的是，如果这中间没有“弄虚作假”成分的话，那么，仅从数量上来看，当然就超过了美国军队在伊拉克的“14万”的规模。

然而，我们也注意到，在伊拉克情报部门强调“20 万”这个数字的同时，美国专家并没有提出“反对”，在补充了一些意见之后，比如，沙瓦尼将众多伊拉克反美同情支持者也计算在内，事实上，华盛顿似乎接受了伊拉克情报部门“新统计”。

东方评论员认为，如果没有什么特别的政治因素的话，伊拉克情报部门又有什么必要在就要举行选举前去、“赶着忙去”修正其上级机构--美国情报部门的“统计”？显然，不说别的，起码在鼓舞反美武装的势气方面就非常不划算！
 
● 亲美、反美双方都抢着为“反美力量”做广告


然而，现在伊拉克的局势可以说是乱到了极点，最新消息说，巴格达省省长海德里当天在自己的汽车里被武装人员袭击，海德里和6名保镖当场身亡，而一直被美国追杀的、伊拉克境内头号恐怖分子扎卡维领导的武装组织已宣称对这一事件负责。

东方评论员认为，在伊拉克傀儡政府的情报部门、以及反美武装都在以“实际行动”、抢着为“反美力量”做广告的时候，我们除了认为伊拉克情报部门“别有用心”之外，还能解读出些什么呢？
  
 
● 这一高官的被杀，很可能会成为华盛顿公开承认“推迟选举”的机会


在我们看来，这一高官的被杀，很可能会成为华盛顿公开承认“推迟选举”的机会。然而，东方评论员认为，现在距离选举还有近25天的时间，因此，华盛顿似乎还没有同其它大国谈妥。

因此，布什将在什么时间宣布推迟选举，仍然取决于其它方向的进展。

在我们看来，别的不说，与北京之间的“讨价还价”显然进行得非常艰苦，在一则有关台湾的消息之后，东方评论员将把关注的焦点投向台湾。
 
 
 
《东方时代环球时事解读》http://www.dongfangtime.com

*** 中国台办高官访美沟通反分裂法  


【华盛顿消息】美国国务院周一证实，中国国务院台湾事务办公室主任陈云林周二将展开在华盛顿的正式访问，除了与白宫高层会晤，周四也与美国副国务卿阿米蒂奇见面，特别是对美方关切中国制定 “反分裂国家法”， 与美方进行讨论。美国国务院并以声明表示，美国希望两岸不要企图改变现状或使敏感的议题更复杂。

美国国务院表示，中国国务院台办主任陈云林一行已经抵达华盛顿，但基于中方的要求，美国将等陈云林与美国官员会晤之后，才发布相关消息。陈云林在2003年7月以及2004年2月曾访问华盛顿，并会见美国国家安全顾问赖斯以及国务院主管政治事务的副国务卿格罗斯曼。美国国务院周一指出，由于国务卿鲍威尔正在东南亚访问海啸受灾国，副国务卿阿米蒂奇周一晚间才从中东地区返回华盛顿，因此他与陈云林的会晤安排在周四。

美国国务院官员指出，美国关切中国即将制定反分裂法的内容，并透过驻北京大使馆持续向中方进行了解。对于中国主管台湾事务的最高官员陈云林亲自到华盛顿来，响应美方的关切。 美方表示欣赏与感谢。虽然陈云林未必如美方所愿带来反分裂法的草案全文，但美国官员私下表示，陈云林访问的本身，就有助于中美两国在台湾问题上，建立更好的沟通模式与默契。

美国官员表示， 美国对台海问题的立场很明确，就是不希望两岸任何一方企图单方面改变现状，对于中国即将制定反分裂法，美国目前为止反应温和，但美国期待陈云林能对反分裂法的内容有更多的说明，以作为美国台海政策的参考。

美国国务院周一并以书面声明表示，美国希望中国大陆与台湾都能以对话和平解决问题，任何一方都不要采取单方面改变现状或使敏感问题更复杂的举措。
 

【时事点评】我们注意到，美国方面以“国务卿鲍威尔正在东南亚访问海啸受灾国，副国务卿阿米蒂奇周一晚间才会从中东地区返回华盛顿”为由，因此，将陈云林与阿米蒂奇与会晤的时间安排在周四。
 
● 美国和日本显然是在“海啸”中打政治牌最积极的国家


各国在“海啸救灾”过程中所表现出的“政治热情”，在前几期的点评中，东方评论员也已经连续地给出了我们的观点。就如我们之前所说的那样，在东方评论员看来，美国和日本显然是在“海啸”中打政治牌最积极的国家。

● 美国的“吝啬”面孔换成了一副“投机商人面孔”

特别是华盛顿，在被联合国官员指责为“吝啬”之后，其“吝啬”面孔是立刻为之一变，但是，东方评论员又看到了美国换成了一副“投机商人面孔”，在承诺增大援助金额的同时，不失时机地提出要由美国、日本、澳大利亚和印度为核心的救援联盟，企图以“主导救灾”进程之名，来行“排挤中国”之实。

● 华盛顿花大价钱、“想展示的三种力量”

东方评论员认为，不论华盛顿是头脑里是突然想到了“马六甲”也好，还是想试验一下“亚洲小北约”的科目也罢，或者上述目标最后都不能实现，干脆“收获点人心”，事实上都不过是表面上的东西，在中东问题没有定论之前，不会有什么结论，亚洲国家中的大部分谁也不会轻易下赌注。因此，华盛顿这次从“小脚女人”一夜之间“突然掷地万金”，其实质还是想让国际社会、特别是中国影响日益增强的亚洲、再次看到美国“超强的政治、经济、军事力量”。

然而，美国想展示的这三种力量最好的地方显然应该在中东，在伊拉克，可事实是，美军在伊拉克取得了一塌糊涂的胜利、华盛顿完全陷入孤立之后，国际社会看得清清楚楚，那就是，华盛顿花大价钱、“想展示的三种力量”，除了“很难解决问题的军事力量”之外，根本就没有什么值得一提的必要。
 
● “动机不纯”，必然导致与当事国的利益矛盾激化

首席评论员指出，人道救援的工作，中国当然要尽力做好，但是，一定要有“两个前提”，那就是“力所能及”、以及真心实意、不附带条件。就如我们之前所指出的那样，在我们看来，中国在这次救灾中的表现可以说可以用“非常出色”这一词来加以形容。

在我们看来，由于这场灾后重建将是一个“长期的工程”，因此，开销将是非常之大的。时事评论员们认为、任何“表演性”的、超出自己实力的动作、看似能“先声夺人”，可到了最后，由于中国、美国、日本与受灾国的政治、经济利益关系、很难因这场灾难而轻易改变，因此，在“长期救灾”中的“动机不纯”，非常容易导致与当事国的利益矛盾激化，从而最终尝到“搬起石头砸自己的脚”。
 
 
● 北京只需“脚踏实地”、一心一意地救灾，做自己“力所能及”的事情就可以

东方评论员不认为美国能长时间地靠现在这种方式来“表演”自己的救灾热情，我们也不认为日本还能接二连三地“扔出5亿美元”，所以，在我们看来，北京在这场长期的救灾过程中、只需“脚踏实地”、一心一意地救灾，做自己“力所能及”的事情就可以，用不着去和美国、日本去争着搞政治表演，别一时“谁财大气粗的苗头”。

我们也认为，如果认为美军能以这种方式重返印尼等国，日本也能以这种方式让东南亚对日本的政治、军事大国梦重新评估，那也就太低估东南亚政治领导人的政治智慧了。

好了，“海啸”相关的讨论，将和往常一样，放在稍后进一步展开，现在，还是言归前面的话题。
 
● 华盛顿对陈云林“非常客气”的背后， 东方评论员看到的是中美之间的“紧张”


在之前，东方评论员一再重复着一个观点，那就是，北京制定“反分裂法”很可能是一个“有趣的过程”，之所以这样说，就在于我们认为“反分裂法”的“立法速度“、以及“相关内容”，都将与中美、美欧在中东、在地球其它方面的“讨价还价”的“过程与结果”密切相关。

东方评论员注意到，就在北京和欧洲在中东加紧活动的同时，就在华盛顿一直关注着中欧在中东的动向的同时，美国官员也在私下里透露说，华盛顿一直在关注着中国即将制定反分裂法的内容。显然，在我们看来，华盛顿“将这两种关注相提并论”是合乎情理的，也正是在后一种“关注”下，北京主管台湾事务的最高官员陈云林亲自到华盛顿来，以“响应”美方关切的。

我们也注意到，华盛顿似乎对陈云林的到访“非常客气”， 不仅表示“欣赏与感谢”，还认为“陈云林访问的本身，就有助于中美两国在台湾问题上，建立更好的沟通模式与默契”。

然而，在这一切“客气”的背后，东方评论员看到的是北京与华盛顿之间的“紧张”，可以说有许多问题“没能、或者很难取得共识”。
 
 
● 在台湾问题上，不论北京和华盛顿这一轮谈得多好，都有可能是“人一走茶就凉”


在我们看来，美国方面在安排与陈云林见面的人员上就很成问题，不要忘记了，不论是国务卿鲍威尔还是副国务卿阿米蒂奇，不久都将走人，这就是说，在台湾问题上，不论北京和华盛顿这一轮谈得多好，都有可能是“人一走茶就凉”，因此，东方评论员认为，直到目前为止，布什政府在对台政策上，仍然是在采取一种“走着瞧”的态度，所以，白宫决策层，也不可能指望心知肚明、态度强硬的北京、会让陈云林“如美方所愿带来反分裂法的草案全文”。
 
 
● 没有任何理由认为中美之间在台湾问题上还有什么好谈的。


东方评论员认为，如果我们猜测不错的话，或许北京现在根本就没有什么“全文”，如果有的话，也许是一个“动态的全文”，视“台独进程”，“全球局势”变化而随时调整的全文。

在我们看来，陈云林在这个时候访问华盛顿，本身也并不说明中美双方的焦点在台湾，在我们看来，在现阶段内，由于北京的“反分裂法”已经记动，因此没有任何理由认为中美之间在台湾实质问题上、还有什么好谈的。

 
● 现阶段内，中美之间的任何一次接触，都可以看成是坦率“交换意见”

显然，北京和华盛顿对对方在台湾上的底线都应该非常清楚了，对对方在中东问题上的底线似乎也非常清楚了。因此，在东方评论员的眼里，起码在现阶段内，中美之间的任何一次接触，都可以看成是北京和华盛顿之间在台湾问题上的、以及其它战略问题上的坦率“交换意见”，这种坦率甚至可以理解成“我准备这样做”， “你要这样做、我就要这样做”这一层次。


● 华盛顿目前最需要搞清楚的不是北京想在台海做什么，而是打算在中东做什么

东方评论员认为，显然，现阶段内，北京在台湾方向上除了这个准备制定的、防御性的“反分裂法”之外，不可能有任何大的动作，因此，华盛顿目前最需要搞清楚的不是北京想在台海，而是打算在中东做什么。如果我们从这个角度来看唐家旋出访巴以、美国副国务卿阿米蒂奇周一晚间才将从中东地区返回华盛顿，我们也就更能体会到中美的这次接触，其实不论是在“时间”还是在“人物”上，似乎都已经抺上了一丝“中东色彩”。
 
 
● 将很多精力投入中东方向的北京，已经“不太可能理会”华盛顿的“小动作”了

因此，当我们听说“美国期待陈云林能对反分裂法的内容有更多的说明，以作为美国台海政策的参考”时，东方评论员认为，与其说华盛顿是期待着北京让陈云林带去的东西、能做为美国台海政策的参考、倒不如说是作为美国中东政策、特别是眼下最紧急的、是否可以推迟伊拉克选举的参考来得真实。

当然，东方评论员认为，直到目前为止，中国和欧洲似乎仍然没有足够的理由、在捆绑“伊拉克选举、巴勒斯坦选举”的事情上做实质让步，因此，做为事态的后续发展，在台湾、中东问题上，我们认为有一点可以期待，那就是，如果中美、欧美之间这几天在伊拉克选举时间、巴勒斯坦选举能否顺利进行的问题上还是“谈不好”的话，那么，华盛顿在台湾问题上、在伊朗、叙利亚问题上又会弄出点新闻来，或者是更加“热情”地反独、或者是来点强硬的、不光是在台湾问题上强硬，也可能在伊朗、叙利亚问题上强硬，如果是后者，一来是向中国、欧洲施加点压力，二则也是出一口恶气。

在东方评论员看来，将很多精力投入中东方向的北京，已经“不太可能理会”华盛顿在台海方面的“小动作”了，毕竟“反分裂法”立法进程已经正式启动了，显然，北京的意图非常清楚：在现阶段，只要支持台独的布什和搞台独的陈水扁、不敢“大动作”就行。
 
 
 
《东方时代环球时事解读》http://www.dongfangtime.com
