# -*- org -*-

# Time-stamp: <2011-08-04 12:18:06 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 2005年8月08日  星期一

下面，我们将把关注的目光投向日本国内。众所周知，小泉在内政遇到困难时总要转移矛盾，把人们的视线吸引到国外。在东方评论员看来，直到今天之前为止，可以说小泉的手上、仍然抓着“三张牌”：第一，是邮政民营化；第二，是8月15日参拜靖国神社、第三，就是与中国的东海油气田争端。

今天是他的“第一张牌”的“大日子”、也就是说，日本参议院将表决日本众议院在不久前、以微弱票数通过的邮政改革相关法案。下面，我们就来了解一下事情的最新进展，之后，东方评论员将开始讨论这个话题。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com



** 日本参院否决了小泉政府提出的邮政改革相关法案




【东京8月8日消息】日本参议院8日以125票对108票否决了政府提出的邮政改革相关法案。此前，日本首相小泉表示相关法案不能获得参议院通过，将解散众议院重新举行大选。

日本邮政系统在全国境内有2.5万个分支机构，共吸纳存款1.9万亿美元，相当于日本最大私营银行东京-三菱银行存款的3倍。

根据小泉政府提出的邮政民营化相关法案，日本邮政业在2017年前完成私有化。邮政民营化相关法案包括邮政民营化法案、日本邮政股份有限公司法案等6项法案，主要内容是在2007年4月解散日本邮政公社，成立一个控股公司，下设窗口公司、邮政事业公司、邮政储蓄银行和保险公司。窗口公司负责整个系统雇员开支、管理邮政企业财产等。控股公司起初将统领这4家公司，但到2017年必须售出在银行和保险业的股票。

这个改革方案在日本朝野引起强烈争论。支持者称，邮政业私有化有助于改善服务、提高竞争力，由市场来决定如何有效使用巨额存款。反对者认为，邮政业民营化不仅会导致部分从业人员失业，而且会造成邮局减少，影响服务质量。

日本众议院在7月5日以微弱票数优势通过邮政改革议案。除了在野党投票反对外，自民党众议员中也有51人投反对票、缺席或弃权，内阁4名副大臣、政务官也投了反对票。



** 小泉决定解散日本众议院，提前在9月11日大选




【东京8月8日消息】日本参议院否决了由首相小泉纯一郎提出的邮务改革议案，小泉与执政联盟商讨，决定提早在9月11日大选。

　参议院今日是以125票反对、108票赞成，否决小泉自2001年上台后就积极提出的邮务改革。今次议案被否决，对小泉造成沉重的打击。

　表决完毕后，小泉即时召开紧急内阁会议。日本放送协会及共同社报道，小泉与执政联盟开会后决定解散众议院，提前在9月11日大选。此外，反对派政党已在国会向小泉政府提出不信任动议。

　现时日本邮政当局兼顾存款和保险业务，所收的款项会用来购买政府债券。小泉认为有需要改革制度，将这大笔存款转成股票出售，藉此刺激经济。

　但反对者，包括部分执政自民党员，指邮务私有化会令郊区邮政服务减少，而且40万邮务职员将面临被解雇的命运。



【时事点评】我们知道、在此之前的日本众议院的表决中、当时、小泉纯一郎为了让“法案”过关，就抛出两招“绝杀”，首先，是立下规矩：一旦自民党议员投反对票、将受到严厉地处置，即：如果自民党内部有谁敢胆造反、投反对票、那么、在以后的国会议员选举中、就不要指望受得到自民党的提名，也就是说，谁敢造反、本质上谁就得“被请出”自民党。


*** 小泉纯一郎一早就抛出来的“两招”

其次，小泉纯一郎为了“威慑”有心造反者，当时就扬言：一旦法案“最终被否决”，就将视为对小泉内阁的“不信任”，他一定会解散议会、提前大选。

显然，在东方评论员看来，小泉纯一郎一早就抛出来的这“两招”、其实是“互为条件”的，也就是说，他对“造反”的自民党议员的“惩罚”将依赖于“第二招”的“兑现”来实现。

因此，在日本众议院表决时，许多“有心造反的”自民党议员心中就已经非常清楚，一旦该法案在众议院就被否决、也就是在自己的手上被否决、那么，也就意味着是自己动手将自己踢出了国会。因为，一旦众议院被小泉纯一郎解散，那么，在失去自民党的提名之后、他们就得作为独立竞选人、或者另结新党去参与大选。

而在日本现行的选举体制下、即一个小选区只产生一名议员的情况下、这些“因反叛在而失去政党支持的政治人物”、要想重新当选，困难极大。


*** 自民党的“参议员们”在造反时就少了许多顾忌

事实上，也就是在这种“反对”法案、就意味着丢掉议员位置的巨大压力下，据了解，在日本众议院于7月5日“正式表决”时，慑于小泉纯一郎的这两招“杀招”的威力，许多原本要“投反对票”的人、最后为了自己还能在议员这个位置能够继续干下去、而被迫妥协。

因此，在众议院表决时，这个法案最终还是通过了，尽管是仅仅几票的“极小优势”。

根据我们的观察，7月5日、在小泉抛出两“杀招”之后，众议院表决中却仅仅出现了一个“极小优势”，这似乎让小泉纯一郎感到更加地不安。

东方评论员认为，道理很简单，按日本的宪法，小泉纯一郎“只有”解散众议院的权力、这就是说，在今天的参议院表决中、自民党的“参议员们”在造反时就少了许多顾忌，最起码他们不会象那些在众议院造反的“同志”那样、担心立刻就会丢掉自己在参议院的位置。


*** “邮务私有化”中牵扯了“太多利益”的激烈倾轧

然而，我们知道，在日本的政治党派中、特别是自民党中、是分成许多派系的、而与邮政系统有瓜葛的政治人物为数众多，其中、前首相桥本龙太郎就是靠邮政势力抬上首相宝座的、此外、日本国会议员中、有相当多的议员就是依靠农村地区的邮政局长帮助宣传拉拢当地选票、或者干脆就是靠“邮政”的“庞大资金”给抬上议员、大臣宝座的。

在东方评论员看来，小泉纯一郎的“邮务私有化”这所以受到自民党内的重重阻力，其实就在于“利益”两字，这不仅有个人利益争斗、还有日本党派间、更有自民党派系间利益的激烈倾轧。


*** 日本所谓的“百年之争”

日本邮政储蓄大概有3万亿美元之巨，总体而言，拥有这一巨额资金的日本邮政的功能主要有三点；邮政业务；简易保险；再就是邮政储蓄，这就便利日本邮政不仅仅提供邮政服务，实际上它还是一个庞大的储蓄银行。

就邮政储蓄这一块，其主要特点有两个，一是金额巨大、二是对于小额邮政储蓄、其利息是不用交税的。因此，基本上所有日本国民都把钱存放在日本邮政，尽管利息很低，但是他们知道这实际是个政府部门、所以很安全，仅仅就这两点，就足以让日本政府的“相关部门”“极其不满”

东方经济评论员表示，在这里，我们所说的相关部门就是指“日本的财政部”--大藏省，“不交税”这一块、就一直为其所“眼红”、可以说这一“红眼病”“得”了近一百年：早在100年前日本的大藏省就想把日本邮政省的这一块肥肉吃进嘴里，但在邮政势力的强大反对下、就是没有吃动。“这一争斗过程”在日本国内早就形成了一个专有名词、这就是所谓的“百年之争”。


*** 事实都已经证明是“个人利益”、“党团、派系重点单位”战胜了“国家利益”

小泉纯一郎的邮政改革就是为了终结这个“百年之争”，改革的目标，就是把这么一大笔钱拿出来，让私人银行来管理。对此，支持改革者的理由是：邮政业私有化后，就可以由市场来决定如何有效使用巨额存款，也有助于改善服务、提高其竞争力，在他们看来，他们的观点将有利于“日本国家利益”。

但是，反对的人似乎“更加贴近民众”，他们反对的理由就是：邮政私有化会导致大量从业人员失业，还会损害穷人（小额存款）的利益，不仅如此，它也会造成邮局减少，从而影响许多人烟稀少地方的服务质量，因为私人企业主是不会不顾成本、在一个人烟稀少的地方设“邮政所”的。显然，反对者“走的是群众路线”。

在东方评论员看来，在日本国会参、众两院的表决中、不论是“过程”还是“结果”，事实都已经证明是“群众路线”战胜了“小泉政府”，也就是小泉的“反对派”战胜了其“支持者”，但是、我们认为，这本质上也是日本国会议员眼中的“个人利益”、“党团、派系利益”、最后战胜了日本保守势力眼中的“国家利益”。

对此，小泉纯一郎的“反应”是“兑现”之前亮出的“两招”，特别是对其解散众议院、提前大选而言、日本许多分析人士认为是小泉纯一郎的故技重施、是又一次在“赌博”、因为，小泉纯一郎在2003年10月就曾经通过解散众议院、“赌赢”过一次。

如果是“赌博”，那么小泉纯一郎会赌赢吗？

在我们具体分析这一问题之前，再来看一则“花边”新闻，之后，我们将继续回到这个话题。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com



** 为劝说小泉“大局为重”，前首相森喜朗“饿着肚子”忠言相告




　　【东京8月8日消息】与其他报章和媒体也作出类似预测，原订在明年底举行的大选，将在9月11日举行。

　　据报道，自民党内部在周末两天对邮政部门私营化法案展开激烈拉锯战，前首相森喜朗也拿他没办法，在劝说小泉不果之际，责骂小泉“比怪人还怪”。

　　小泉以“怪人”扬名政界，在上述法案表决的拉锯战中，被自民党干部认为，他将毁灭自民党的大好江山。

　　为劝说小泉必须以“大局为重”，森喜朗在周末晚上饿着肚子，拿着几罐啤酒对他忠言相告。

　　在小泉的官邸内，森喜朗对小泉说：“我们都在努力避免出现解散局面。在众议院表决时，许多原本要投反对票的人都妥协了。你若解散国会，只有让这些人感到痛苦。”

　　小泉说：“那是我的信念，我也不怕就此被杀，已经作了最坏的打算……要知道我是首相，说过要做的事情就得兑现，我本身也不希望国会解散。”

　　森喜郎警告他解散国会后可能发生的局面，说：“要是我们变成反对党，你就不再是总裁，到时没有人会要追随你。”


森喜朗骂小泉“比怪人还怪”


　　小泉说：“那就叫他们（反对的参议院议员）别投反对票。如果还是继续造反，只有大家完蛋。”

　　森喜朗说：“我需要你重新作考虑……”

　　小泉说：“不，我不会改变主意。”

　　森喜朗：“你简直比怪人还怪。”

　　森喜朗最后拿着空啤酒罐子回答记者的问题时说：“小泉的态度实在叫我难过，这或许也是我最后一次见他。”

　　“解散国会”是日本首相的权力，也被认为是用于制衡党内势力的一把“尚方宝剑”。为兑现邮政部门私营化这个“承诺”，小泉将“宝剑”搬出台面，让自民党内出现疑云片片。

　　日本自民党干部也趁这一周末对反对派进行游说。自民党预测到，要是解散（国会）就会出现分裂，是赔了夫人又折兵。

　　政治评论家预测，如果国会解散，自民党一部分议员就会出来组新党。民主党则有胜算，可结合这些新党夺取政权。”

　　白鸥大学教授福冈政行指出，值得叫人关注的是，若解散国会，会促使小泉以“在8月15参拜靖国神社”来哗众取宠。

　　根据一项调查，支持小泉的民众始终有40％，都是老人和妇女。加上“参拜靖国神社”，必然能够给他拉来选票。8月8日解散国会，将焦点转移到8月15日的靖国神社参拜上，或者就是小泉的政治布局。



【时事点评】我们注意到，小泉纯一郎的“前辈”、前首相森喜朗、为劝说小泉必须以“大局为重”，在周末晚上是“饿着肚子”，手里“拿着几罐啤酒”对他“忠言相告”的。

另所了解，森喜朗在劝说未果之后，在接受媒体采访时、是当众将啤酒罐“挰瘪”、绝望地声称“这或许也是我最后一次见他。”


*** 小泉走到了“以死明志”的地步

在东方评论员看来，作为自民党森喜朗派的“派头”、森喜朗都无法说服自己一派的小泉纯一郎回头、并还听到了一席“我也不怕就此被杀，已经作了最坏的打算……要知道我是首相，说过要做的事情就得兑现”的“回答”，似乎小泉纯一郎的确就是“怪人中的怪人”。

然而，首席评论员就指出，既然“说过要做的事情就得兑现”的小泉走到了“以死明志”的地步，足以说明他除了“兑现”“说过要做的事情“之外、已经没有任何路可走了。显然，改革日本邮政是他说过要做的事，结果，他做了；而扬言如法案被废，他将解散国会、结果他也做了；


*** “死都不怕”的小泉、极可能在大选前“赌最后一把”的

那么，身为日本首相的小泉纯一郎还有什么说了没有做的事情呢？这恐怕就是今年他在中国的压力下、至今还没有参拜靖国神社。因此，“死都不怕”的小泉纯一郎泉、

并声称“如果还是继续造反，只有大家完蛋”的“怪人”，是极有可能在9月11日大选前“赌最后一把”、其中、“在8月15参拜靖国神社”将是小泉内阁拉抬人气的一个筹码。

但是，东方评论员也认为，“在8月15参拜靖国神社”、很可能只是小泉纯一郎“赌最后一把”中的筹码中的一个、而不是全部。


*** 警惕小泉将“赌盘”“开到国外”，从国际上抓筹码、“借外压”来扳回败局

对此，首席评论员指出，对“困兽犹斗”的小泉纯一郎而言，如果北京“将眼睛仅仅”盯在“小泉可能在8月15日参拜靖国神社”上、将是非常危险的。我们认为，对于一个即将下台的、并“悲鸣”“不怕被杀”的小泉而言，他既然将解散国会作为他借以渡过难关的“政治豪赌”，那么，我们有必要警惕他将“赌盘”“开到国外”，从国际上抓筹码、“借外压”来扳回败局。

显然，就日本社会仍然有近半数的民众“不支持”小泉参拜靖国神社的现实而言，仅仅是以“8月15日参拜靖国神社”来激起中国、韩国的“外压”，是不足以在9月份的大选中“扳回败局”的。


*** 小泉的“一意孤行”、实际上也是在向北京发出警告

事实上，首席评论员就认为，小泉纯一郎在这个时候不听自民党内“派头”-森喜郎的“苦口良心般劝告”、将邮政改革法案“推迟到明年”、他将做工作确保通过，而偏偏在这个时候、在7、8月份的时候“一意孤行”、实际上就是在借此向北京施加压力，也是在向北京发出警告，即：如果北京不在“一系列问题上”做出妥协，减少他面对的、来自日本内部的压力、否则、一旦他“必将下台”，那么小泉纯一郎就将在东海问题、钓鱼岛问题上、“被迫一搏”、在我们看来，让中国、日本对外关系中都非常重要的“中日关系”和小泉内阁“都完蛋”的事情，走投无路的日本保守势力、如果得不到有效的压制，是有可能做得出来的。


*** 从日本政府的一系列动作中、都能看出这一“脉络”

如果我们在这一背景下、去看日本外相町村信孝日前在纽约长“造谣”、声称“中国最终不会反对“四国集团”的“入常”方案”；以及八月一日自民党发表了修改宪法草案、并在同日右翼势力呼吁发动二十万人参拜靖国神社活动，敦促小泉于八月十五日参拜靖国神社；

还有在8月2日众议院通过了战后决议、将“侵略”的字眼删去、同日日本政府内阁会议通过了白皮书，并通过《读卖新闻》、《产经新闻》等均发表了、配合华盛顿的、鼓吹“中国威胁论”的文章、此外，日本方面甚至还声称中国的春晓油气田将在8月份完成投产的准备工作、等等、从这一系列动作中、都能看出这一“脉络”。


*** 中国对来自“日本和美国”的威胁、所做的准备也是非常认真的

然而，就我们的观察，正如我们之前所说的那样，北京在此之前的一系列动作、特别是宣称严厉警告日本不要在东海问题上轻举妄动、并拿着台湾问题、以中国有核打击美国的决心、“来证实自己”已经做好了应付日本可能“在主权问题上极端挑衅”的准备；

此外，北京还以一系列强硬态度、比如：声称“四国提案”将是“死路一条”、并支持在“六方会谈”的具体议程中将日本坚持的绑架问题“剔出”了“朝核问题”，本质上都是“狠踩”小泉政府的“形象”、强化小泉纯一郎的“内外困境”、从侧面“策应”日本国内反对小泉政府的政治、经济力量。

不难看出，来自“日本和美国”的威胁、是“非常认真”的，而中国对来自“日本和美国”的威胁、所做的准备也是非常认真的。因此，事态的最后发展、如何发展、就要端乎“谁的意志更加坚强”了。



*** 要谈清楚许多重大问题、“三个星期”的时间实在是“太短了”

也正是基于这种判断，东方评论员早在上个星期的《东方时代环球时事解读》中、就已经将“六方会谈”“可能会休会几天”，以及“朝核问题”“可能将伴随”中俄8月18日开始的大规模联合军演的高潮、而出现高潮的问题给出了大量的分析。

首席评论员的观点是，“六方会谈”休会三周、可能也只是个“临时决定”，我们认为，“六方会谈”什么时候复会、将要看中日关系、伊朗核问题、巴以和平问题、中亚美军军事基地问题、中印关系、以及台湾问题的“综合走向”而定。显然，对“中、美、欧、俄、印、日”这几个“强势中心”而言，要谈清楚许多重大问题、“三个星期”的时间、实在是“太短了”。


*** 小泉在邮政改革问题“如此积极”、与人民币“被迫”升值、与美元的走向也有密切关系

另外、小泉纯一郎在邮政改革问题如此积极、除了政治上的因素外、在经济上也是有着企图的。对此，东方经济评论员就认为，日本的这一企图与中国在欧美的压力下、“被迫”突然升值人民币、与美元的走向、也有着密切的关联。

在一段译自日本《读卖新闻》的经济新闻之后，东方时事评论员、经济评论员将一起对此“进行展开”。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

