# -*- org -*-

# Time-stamp: <2011-08-02 19:13:48 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

#+STARTUP: indent

* 2005年01月06日 星期四

** 陈云林继续访问华盛顿晤阿米蒂奇

【华盛顿消息】国务院台湾办公室主任陈云林周三与美国副国务卿阿米蒂奇见面，讨论中美关系以及两岸议题。美国国务院指出，陈云林等中方高层官员访问华盛顿，直接与美方就敏感议题沟通，是重要，有用而且受到美国欢迎的。
 
陈云林周二与美国副国家安全顾问哈德利见面后，周三又在中国驻美大使杨洁篪的陪同下，前往美国国务院，与副国务卿阿米蒂奇，会谈一个小时。美国国务院发言人指出，双方就共同关切议题，广泛交换意见，其中包括中国正在研拟的反分裂法。

会谈中，阿米蒂奇也重申，希望两岸以对话和平解决问题，不要采取会使敏感问题更复杂的举动，会谈之后陈云林虽然没有公开讲话，但美国国务院表示，陈云林这次访问是美中经常性的高阶层对话。

美国国务院发言人埃瑞利表示，中美经常性地交换意见，中美高层官员也经常性地互相访问，这次陈云林访问是我们经常性对话的一部份。

美国目前最关注的是中国制定反分裂法的内容，埃瑞利指出，去年十二月中国副外长戴秉国，以及这次主管台湾事务的最高官员亲自来与美国沟通，美国欢迎并且认为是有帮助的。

这次是陈云林在一年半内第三次访美，一般认为，中美在敏感的台湾问题上，已经有越来越多的共识与默契。
 
 

【时事点评】在昨天的点评中，东方评论员就曾经说过，北京和华盛顿在有关台湾的“实质问题上”、实际上“已经没有什么好谈的了”，在我们看来，北京启动“反分裂法”进程，事实上已经意味着中国决心缩减中美东亚战略的回旋空间，打乱华盛顿的“台独时间表”、从而可以“继续置台湾问题于不顾”，继续在中东方向与欧洲一起、直接拿华盛顿的中东利益与台湾问题之外的东西、进行战略交换。


*** 陈云林这次不会带去华盛顿感兴趣的东西

因此，东方评论员认为，尽管美国国务院的外交官门对陈云林的来访一再表示“欢迎并且认为是有帮助的”，然而，我们并不认为陈云林这次会带去华盛顿感兴趣的东西、

在我们看来，很难想像北京还会因华盛顿在台湾问题上的“小动作”而与欧洲在中东的政策拉开距离。因此，东方评论员认为，华盛顿是期待着北京让陈云林带去的东西、其实是有关交换中东利益、伊拉克利益的内容，所以，东方评论员之前也不指望陈云林访问之后、美国会在台湾问题上能传出什么好的消息。

事实上，不仅没有传出什么好消息，就在陈云林和美国高官在华盛顿还在谈的时候，就已经传出了几则“坏消息”。在一起看完这几则报道之后，东方评论员将继续展开这个话题。


《东方时代环球时事解读》http://www.dongfangtime.com


** 美国向台湾出售近450枚导弹

【华盛顿消息】美国国防部今天证实，美国洛克希德马丁公司在4号与台湾达成协议，将向台湾出售近450枚，总值约五千万美元的“地狱火”空对地导弹。五角大楼官员表示这是在2002年就批准的军售案，美方认为这不会影响台海两岸的军力平衡。

洛克希德马丁公司4号宣布，台湾方面同意购买约450枚“地狱火”式导弹。这笔价值约五千万美元的军售案是美国国防部管理下的对外军售的一部分。

该公司在一份声明中还说，“地狱火”式导弹可以配备在攻击型直升机上，是世界上最好的空对地导弹。其优良性能已经通过伊拉克和阿富汗战争多次检验过，不仅可以精确打击陆地上的目标，还可以有效袭击舰船，轻型装甲车，及城市建筑物等。声明中说，该公司已经开始生产这批导弹。总共大约需要6个月的生产时间。台湾军方在配备这种导弹之后，将大大增加与美军各军种协调作战的能力。

五角大楼下属的国防安全合作局官员5号指出，这笔军售案是美国在2002年批准的。美国不认为出售这批武器会改变台海地区的军力平衡。

美国在02年还同时批准出售290枚陶式导弹和182枚向尾蛇导弹给台湾。中国驻美大使馆5号重申了坚决反对美国向台湾出售武器的立场。但是，有美国国防部官员表示，对台军售符合美国的台湾关系法，五角大楼将切实履行协助台湾自卫的承诺，并希望新的，价值200亿美元的台湾军购预算早日通过。
 
 

【时事点评】在我们看来，华盛顿的手法一如往常，那就是其“相对温和”的美国国务院和强硬的五角大楼，总是在同一个时间段内、你前我后的扮演着“红脸”与“白脸”的角色。
 


*** 我们一度认为，“消息得到证实”也许还有几天的时间

东方评论员认为，事实上此消息在前天的点评中，我们就给出过初步的观点，然而，当天，时事评论员们都不约而同地认为，“消息得到证实”也许还有几天的时间，因为陈云林尚在华盛顿，在我们看来，华盛顿这是在有意放风，因为会谈还没有结束。

然而，我们注意到，在同“唱红脸”的美国国务院谈过之后不久，在陈云林还没有离开华盛顿的时候，向来“唱白脸”的五角大楼就迫不急待地登场了，也还真的在台湾问题上又会弄出了点新闻来，

消息传来，让东方评论员也多少有点意外之感！
 
 
*** 也许会唔的结果比东方评论员想像中的“还要糟糕”

显然，对华盛顿变脸的速度、让我们也多少有点意外。不过，中美之间的这次会晤让华盛顿“大失所望”并没有让东方评论员有意外之感！

只是东方评论员认为，从消息见报不到24小时，美国五角大楼今天就急急忙忙地正式加以了“证实”、“白脸”相向来看，也许会唔的结果比东方评论员想像中的“还要糟糕”。

在我们看来，中美之间，只要五角大楼上场表演、自然总是意味着“来点强硬的”。事实上，这笔“5000万美元的“地狱火”空对地导弹还只是小儿科，美国人使出真正强硬的一手、是让之前被“骂得狗血淋头”的陈水扁、在几乎是同一时间内抛出的“公投修正案”。

在我们进一步讨论这个问题前，再来看看围绕这份“公投修正案”、台湾的“泛蓝”、“泛绿”又在忙些什么。
 

《东方时代环球时事解读》http://www.dongfangtime.com
 

** 马英九对“公投法草案”提六点质疑 “渐进式台独”又渐进了一步

【华盛顿消息】综合报道 台湾「行政院」院会昨日通过了《公民投票法》修正草案。草案大幅降低了公投提案及成案连署人数的门槛，为台独势力日后发动「国旗国号」公投创造了条件。台北市长马英九及亲民党代表在会中表达了反对意见。

未纳入公投「制宪」

台湾「行政院」会通过公投法修正案，原本「行政院」有意纳入「修宪」公民创制权，因为受到美国和大陆的压力喊停。另外这次公投法修正，也将公投提案和连署的门槛降低，只要八千人左右就可以提案，三十多万人连署就可以成案。
 
原本「行政院」打算透过修法纳入公投创制权，也就是可以透过人民连署的方式，进行「国旗」、「国号」变更等创制公投。不过，受到美国和大陆的压力，「行政院」会通过的公投法修正版本，最后公投「制宪」的条文没有纳入。
 
提案人数降10倍
 
据香港商报报道，台湾「行政院」发言人陈其迈说，「行政院」会通过的公投法修正案，大幅降低公投的提案门槛，由原先的选举人总数的千分之五，降为万分之五，大约八千人左右。公投的连署门槛，也由原先的选举人总数的百分之五需要八十万人，降为百分之二，只要三十多万人连署就可以成案。
 
修正草案还删除了投票人数须达有投票权人二分之一以上的「投票率门槛」规定，将通过门槛修正为仅须同意票数多于不同意票数，且同意票数达投票权人总数25%以上者，即为通过。但领土变更案与「宪法」修正案，同意票须达投票权人总数50%以上者，始为通过。另删除3年内不得就同一事项重行提出公投的限制。
 
马英九提六点质疑
 
台北市长马英九昨天在「行政院」会中，针对「行政院」公投法修正草案提出六点质议。马英九说，他赞成降低公投的提案与连署门槛，但反对「总统」或行政机关有公投的发动权。
 
马英九反对公投法修正草案的理由有六：一，要求公投复决领土变更应在「修宪」后为之，否则便是「违宪」；二，坚持公投审议委员会不宜废除，因由中选会审议并不适当；三，「行政院」不应有提案权，因为公投并非政府的统治权；四，防御性公投并无必要，应以紧急命令应付非常状况才合理；五，建议公投通过门槛应采绝对多数制，方可确保民意之权威；六，强调不应采取咨询性公投制度，否则就是「戏弄人民」。
 
马英九指出，高等法院也认为三二○选举中「公投绑大选」是违法的，权力应规定在「宪法」中，这是「宪法」保留的条款；若放到法律中，变成「立法院」就可以创设总统的权力，违背了「宪法」与法律的分工。
 
亲民党：「渐进式台独的一步」

「行政院」院会通过公投法修正草案，「行政院」院长锡堃强调，这是府院达成的修法共识。
 
据台湾媒体报道，刘文雄表示，公投法修正草案绝不会是「行政院」单方面意愿，陈水扁一定也有共识，且草案增列领土变更案、「宪法」修正案由人民复决相关程序，动机并不单纯。
 
刘文雄质疑，修正案是「渐进式台独的一步」，执政党何不干脆举行「台独公投」？
 
他表示，就两岸关系观察，「行政院」会通过修正案，正好在大陆制定「反分裂国家法」期间，将升高两岸紧张情势，破坏两岸和平。
 
 
 
【时事点评】看完这两则消息，可以说台海局势就非常清楚了。在这个时候，如果我们再回过头去看看和鲍威尔一条线上的鸽派人物阿米蒂奇、当着陈云林重申的、所谓的“希望两岸以对话和平解决问题，不要采取会使敏感问题更复杂的举动”显得是多么地“苍白”。
 

*** 在台湾问题上，任何事都没有北京按自己意愿“起草”“反分裂法”来得实在

我们注意到，在同这位刚从中东赶回去的阿米蒂奇会谈之后，陈云林没有公开的讲话。然而，在五角大楼在隔不到24小时，就立刻证实了媒体所报道的、美国洛克希德马丁公司在4号、与台湾达成将向台湾出售近450枚，总值约五千万美元的“地狱火”空对地导弹的协议之后，中国就立刻发出了强烈的反应，并声称要美国立刻取消这一合同。

显然，北京的反应之所以强烈，并不在于这个合同能否取消，而是在向方方面面宣示：在现阶段内，在台湾问题上中美之间没有什么交易可谈、就是谈台湾问题、北京也没有打算要将台湾问题“拿到中东”去谈。

与此同时，东方评论员也注意到，就在陈水扁当局通过了《公民投票法》修正草案后，北京却没有任何针对性的发言，由此可见，由于“反分裂法”进程已经启动，因此，在台湾问题上，大陆方面也显然没有什么可以再多说的了。在我们看来，在这个时候，北京说任何严厉的话、华盛顿使任何强硬的招，都没有北京按自己意愿“起草”“反分裂法”来得实在。
 
 
*** 都不过是华盛顿在前一阶段“高调”“反台独”、却“毫无所获”的“强烈反弹”。

在之前的《环球时事》中，我们一再强调的一个观点是：“反分裂法”的进程将视全球局势的变化、视“美国推动台独的进程”的“变化而变化”，在我们看来，不论是华盛顿批准出售这批总值约五千万美元的“地狱火”空对地导弹、还是陈水扁当局抢在这个时候通过了《公民投票法》修正草案、大幅降低公投提案及成案连署人数的门槛，以为台独势力日后发动“国旗国号”公投创造了条件，事实上都是华盛顿在前一阶段“高调”“反台独”、却几乎“毫无所获”的“强烈反弹”。

事实证明，唐家旋中东照去，反对美国压住中东和平路线图也是一样的反对，支持伊朗核问题立场的声明也仍然在重复，特别是在伊拉克选举问题上，由于中国欧洲仍然没有松口，因此，华盛顿也仍然无法正式提出“推迟”的动议。

眼见着选举的日期就要到了，伊拉克什叶派正准备着“控制国会”，一心想建立一个“合法的”傀儡政权的华盛顿，心里能不急吗？
 
 
*** 布什在这个节骨眼上，再次将陈水扁放出来，其心可以说是“昭然若揭”

因此，东方评论员认为，华盛顿在这个节骨眼上，再次将一度痛骂的陈水扁放了出来，其心可以说是“昭然若揭”。在我们看来，特别是这次“公投法”修正，我们注意到，修正后的草案将公投提案和连署的门槛降低，只要八千人左右就可以提案，三十多万人连署就可以成案。显然，这对于有二千多万人口的台湾而言，如果最后定案，那么，美国日后如果战略上需要的话，陈水扁日后搞“公投提案和连署”几乎就没有什么门槛了，在东方评论员看来，这些“危险”就是华盛顿想让北京“再三思”的地方。


*** 可以说是美国不放弃打“台独牌”的总暴露

首席评论员指出，从台湾“立法委员”大选前后、白宫决策层突然变脸“大骂”台独、北京用启动“反分裂法”这一特有的方式“表示欢迎”开始，到今天中国台办的一把手陈云林访问华盛顿期间、五角大楼抛出一份“军售合同”、默许陈水扁当局尝试“拆去”提案和连署台湾公投的门槛为止，既可以说是美国对台政策的“正常延续”，也可以说是准备其打“台独牌”之本质的总暴露。


*** 陈水扁抛出《公民投票法》修正草案，再向“台独”前跨一步

在我们看来，不论是美国抛出的这份5000万美元的军售合同，还是陈水扁当局抢在这个时候搞出的《公民投票法》修正草案，在华盛顿而言，其目的主要有两个，一是向北京施加压力，让中国的“反分裂法”的具体条款尽可能地有利于华盛顿继续打“台独牌”，二就是在中东问题上立刻答应美国的要求，那就是在华盛顿极可能稍后提出的“推迟伊拉克大选时间”上不要拆美国的台。

对陈水扁当局而言，其目的那就更加明确了：这本来就是“渐进式台独的一步”，这个时候无非是在华盛顿授意之下、借配合美国需要的机会、又向前跨了一大步而已。
 
*** 布什“默不吱声”、这本身就是在替陈水扁“平反昭雪”

显然，在东方评论员看来，一个“只要八千人左右就可以提案，三十多万人连署就可以成案”的公投修正案，可以说是在布什默不吱声的情况下就这么提了出来，这本身就是在替陈水扁辩解、为其“平反”：什么布什让人传话“不喜欢陈水扁”啦！什么华盛顿终于意识到“台独”危害到了布什政府的利益啦！什么中美在联手“反台独”、如此等等的说法，都不过是在“捕风捉影”、或是只看到了事情的表面，没有看清背后的实质。
 
 
*** 华盛顿控制起“台独进程”来，可谓是得心应手！

东方评论员认为，我们还是那一句话，那就是：布什是“非常喜欢”陈水扁的、而且可以说是“喜欢到了骨头里”！在我们看来，也正是在“320”中通过调查“枪击案”、摆平“泛蓝”的抗争的过程“修理”、并最后选择了这么一个“不在乎脸皮”的陈水扁后，华盛顿控制起“台独进程”来，可谓是得心应手！

首席评论员指出，或许台湾的国民党、亲民党、或者马英九、宋楚瑜都对美国的对台政策有更深的认识，因此，在我们看来，不论是国亲两党是否在“认真地”质疑这个“修正案”，事实上都对“台独进程”起不了任何作用。
 
*** 有分析认为，香港这次不让马英九前去，其中就大有文章

东方评论员注意到，有分析就认为，香港这次不让马英九前去，而且没有给出任何解释，其中就大有文章。在东方评论员看来，在是否给出解释的问题上，按香港的惯例，在处理类似的问题上，也一直是这样做的，因此，香港这次不让马英九前去，而且没有给出任何解释本身没有什么异常可言。但是，东方评论员注意到，许多媒体在得不到香港特区政府的解释后，顺势就将背后的因素归到了北京的身上。

其实，东方评论员认为，这些媒体将香港这次不让马英九前去的责任转到北京身上，本身并没有错。显然，没有北京的授意，香港特区政府没有必要这样做。问题是北京为什么要这样做？
 
*** 北京在这个时候不让马英九前往香港，意在传递一个信息

在此，我们注意到，有国际问题专家就认为，北京在这个时候不让批评过“反分裂法”的马英九前往香港，意在传递一个信息：美国大可去玩“泛蓝”、“泛绿”，而在北京的眼里，“泛蓝”和“泛绿”没有太大的区别了。


*** 美国和台湾各政治势力之间的这场政治游戏，是演给北京看的

东方评论员对这种观点“非常以为然”！在前段，亲民党主席宋楚瑜在民进党、国民党之间跳来跳去，表面上是在对国民党夺去了自己的选票表达不满，是为了保障亲民党的影响力，有意不排除考虑与民进党合作、而在给很有可能是马英九出任下一任主席的国民党施加压力，然而，事实上，美国和台湾各政治势力之间的这场政治游戏、其真正观众并不在台湾，而是北京，问题是，北京却表现得“连眼皮都懒得揿一下”似的。

在我们看来，北京在宋楚瑜“跳来跳去”、并频繁飞美国的过程中，一句有关台湾的话都没有讲，而只是按步就班地“打理”着自己的那部“旨在止独”、美国现阶段不便公开反对的“反分裂法”。


*** 北京有意“照单抓药”？

东方评论员认为，北京的这种态度就是要看看美国和台湾的“泛蓝”、“泛绿”到底能安排个什么“台独进程”出来，之后再“照单抓药”，有针对性的往“反分裂法”中“添加内容”。

在我们看来，华盛顿于台湾“立法委员”选举前搞的那一套是非常有欺骗性的，也就是说，一旦北京不够坚决、仍然对华盛顿几年之内维持台海局势现状抱有一线希望、从而“愿意接受”美国“是在做止独的好事”，并也和美国、台湾媒体一样、给布什政府贴上“反独”的标签，那就意味着中国必须在中东问题上，特别是伊拉克选举问题上立刻就“给出回报”。
 

*** 自“517”之后，北京是从来就没有认为华盛顿是在做什么好事！

事实大家都看到了，自“517”之后，北京是从来就没有认为华盛顿是在做什么好事，也没有认为陈水扁、“台独”势力受到了美国的打击，更没有表现出“松了一口气”的样子，反而做出了一副将“泛蓝”、“泛绿”不做本质区别的态度，这就是说，美国你愿意插手台湾政局的安排、那就请便，但不要将这种“泛蓝”、“泛绿”之间力量对比的“人为安排”、作为一种与中国进行全球战略层面上的讨价还价之筹码就行。
 
 
*** “台独”和支持“台独”势力一个月来的表演、前后真可谓是“天壤之别”

东方评论员认为，这几天看到美国的这些不折不扣地“支持台独”行为、以及陈水扁又开始活跃的事实，与稍早美国狂批“台独”、陈水扁“灰土灰脸”的景象真可谓是“天壤之别”，为什么？在我们看来，恐怕就是因为美国的新保守主义者、在费了这么大的周折、准备了大把的“台湾牌”的筹码之后，对陈云林随身携带的公文包中的内容“太失望”了。

华盛顿准备的这一大把筹码，其本质上还是想回头去、再拾起那张“台湾牌”打一打。然而，在我们看来，就如之前所说的那样，半年来，美国的强硬对台政策，实际上已经将“台湾牌”打死了，玩完了，现在再玩就只能玩“台独牌”。


*** 华盛顿现在要真打“台独牌”却似乎很难

在我们看来，围绕着华盛顿困难重重的“中东进程”，白宫的决策者还会想办法调动一切可以调动的资源、以实现其拿下中东、支配全球的既定目标。显然，如何调整“台独进程”就是其为实现这一战略目标、可方便调用的一个重要资源。

东方评论员认为，尽管现在白宫的决策层也意识到控制一下“台独进程”不难，但是在现在要真要打起“台独牌”时机却不成熟，因为中国这次不仅将手也伸到了中东、并抓到了美国的痛处。而且，在东方评论员看来，特别是在中东战略陷入困境的时候，由于北京“正在起草”那部“还没有成文”的“反分裂法”，因此，美国想让“台独牌”配合自己的已经严重滞后中东战略，相对变得困难起来。
 
*** 不排除台湾的政治生态不久之后将可能发生剧变

在东方评论员看来，由于美国在中东迟迟没有进展，因此，不排除台湾的政治生态不久之后将可能发生剧变，因为再过不了多久、台湾的地方选举又要开始了，在我们看来，台独和支持台独的美国、日本，都不会放过这个促进台湾社会进一步“独化”的战略机会的。

据东方评论员观察，北京对此似乎已经有了心理准备，那就是，如果中东方向没有大的变化，华盛顿却敢在这个时候将“台独进程”再往前大步推进，必将面对北京立刻推出的一套、条件将非常严厉的“反分裂法”，在我们看来，其严厉的程度可能会以“立刻触发台海战争”来衡量。

当然，东方评论员也认为，如果中东方向有重大变化，特别是有不利于美国的方向变化，那么，不排除中国的“反分裂法”的通过将会延期，或者某些极其严厉的条款暂不放入也是可能的。

在之前，首席评论员已经指出，只要中国欧洲在中东问题上不做实质性的让步，新的一波“台独”高潮将随之而来。在我们看来，这一波“台独”高潮已经在“隐隐约约”之中了。但是，是否是一定能揿起在浪来，那还得看北京在调控“反分裂法”的立法进程上、还能亮出什么高招了！
  在一段香港媒体的报道之后，东方评论员再来谈谈“反分裂法”的相关问题。
 

  《东方时代环球时事解读》http://www.dongfangtime.com
