# -*- org -*-

# Time-stamp: <2011-08-02 22:58:57 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

#+STARTUP: indent

*  2005年5月30日 星期一

** 中日东海问题磋商难突破可能引发两国摩擦

【北京消息】据报道，中日两国计划于今明两日（30日、31日）在京就东海油气田开发展开局长级磋商，两国期望通过此次对话，找到缩小分歧、解决问题的办法。著名国际关系学者、国际时事评论员庞中英预料，在目前情况下，会谈将更侧重于彼此交换意见，继续保持事务性接触势头，双方在重大原则性问题上取得突破与进展的可能性极小。

解决问题须双方让步

有外电分析指出，此次两国间的务实性磋商将会把联合开发作为议题，但可以预料，具体将开发海域设定在哪里以及如何决定利益分配比率都会成为双方争论的难题。

庞中英表示，中日双方就东海油气田问题进行磋商，说明两国确认了这一问题的存在。他指出，是否通过谈判解决东海问题，实际上仍是一个很大的问号。他表示，目前两国进行的接触与交流只是使这个问题处于可控制的状态之下，但是今后如何解决这一问题目前尚无定论。

庞中英认为，如果要通过谈判解决，双方都要创造条件和气氛。他指出，中日双方都曾表示，要使东海成为友谊之海、合作之海。但在目前分歧比较严重的情况之下，双方应首先确定这一问题必须通过谈判解决，而谈判就需要双方各自作出让步。

可能引发两国摩擦

庞中英说，如果两国间不能确定通过谈判解决东海问题的原则，日本的单方面行动还将可能会进一步升级，东海问题将有可能会引发两国间轻度摩擦，甚至是军事上的摩擦。他说，东海问题是一件很危险的、也是让人非常担心的事情。

庞中英强调，不管中日关系现在是多么困难，我们也不能让中日关系彻底走向失败。但他同时指出，这并不等于说我们要放弃我们的利益、原则和立场。

庞中英表示，在目前的困难面前，我们需要驾驭中日关系，而驾驭中日关系，就要在坚持我们的利益、原则和立场的基础上，尽我们最大的可能性，想尽一切办法去维持中日关系，促进中日关系向好的方面转化。




【时事点评】我们注意到，对这一轮“局长级磋商”，国际时事评论员庞中英的“预料”是：在目前情况下，会谈将更侧重于彼此交换意见，继续保持事务性接触势头，双方在重大原则性问题上取得突破与进展的可能性极小。

*** “都愿意坐下来”的背后，显示双方都在“各有所图”

对庞中英的这个“预料”，东方评论员倒也“深以为然”。但是，在我们看来，在气氛非常紧张的时候，在东海问题上、中日双方还能坐下来，并从今天下午开始的这一轮“局长级磋商”，显然，尽管双方的立场与“出发点”有很大的不同，然而，在这种“都愿意坐下来”的背后，显示双方都在“各有所图”。

我们认为，坦率地讲中日之间可以坐下来谈的事情“有许多”。在东方评论员看来，就目前而言，不论是美日涉及台海的军事同盟、还是钓鱼岛、更或者是根本就是一个日本“自说自话”的冲之鸟问题、以及“以日本政要参拜供奉有十四位甲级战犯靖国神社”为代表的“日本历史问题”、双方都可以坐下来谈，然而，只要稍有点政治常识就不难发现，这些可以坐下来谈的问题“有一个共同特点”，那就是，它们“都不是”一天两天就“谈得透、争得清”的问题。

*** 大概回顾一下近期中日双方的“态度与立场”

因此，首席评论员就指出，如果中日双方、都在以中日关系大局为重、都在诚心诚意地为改善中日关系做不懈地努力，那么“上述的问题”、毫无例外地都能找到“缓解”的办法，然而，事情就出在“诚心诚意”和“缓解”这两个词上面。

在这里，我们不妨大概回顾一下、自“日本外相北京败北、日本首相公开道歉”之后，在改善关系的问题上，近期中日双方的“态度与立场”。

我们知道、小泉纯一郎是4月22日在亚非峰会上“口是心非”表示“道歉”的。而就在第二天，也就是4月23日傍晚，胡锦涛与小泉纯一郎就在雅加达举行了“首脑会谈”，目的虽然都是为了“缓解了中日关系危机的进一步蔓延”，但是，结果我们也都看到了，双方基本上是“各说各话”，胡锦涛提出“五点主张”，而小泉纯一郎则是“表示同意”，除此之外，没有能解决任何问题，国际社会也都在对中日关系“边走边看”。

显然，小泉纯一郎“表示同意”之后不久，町村就在纽约公开宣布“台湾本来就是日美安保条约的对象”。到了5月7日，中国外长李肇星到京都出席中日韩三方委员会第三次会议时与町村外相举行了双边会谈。而就在这次会谈过程中，我们注意到，离开北京之后的町村、这次再次要求中国“对反日游行造成的损失进行道歉赔偿”、及“妥善解决东海开发争议”，显然，日本的立场已经非常清楚地退回到了“日本外相访问北京前、日本所持的强硬立场”。

之后，北京在“坚持不道歉”的前提下，却表明“将负责修葺让受损的日本大使馆”以让其“恢复原状”；此外，也再次表达了“使东海成为友好合作之海”的意思，但是，东方评论员也注意到，北京在表达这些善意的同时，也更加强硬地强调一个原则立场，那就是“希望绝对不要发生参拜靖国神社的事”。

紧接着，从5月13日开始，日中在北京举行了为期两天的首次副部长级“综合政策对话”，日本外务省事务次官谷内正太郎与中国副外长戴秉国经过两天的“唇枪舌剑”、终究是“毫无成果”。

就在5月16日，中日双方，是同时宣布了高层互访计划：中国副总理吴仪于17日对日本进行工作访问；而日本“两执政党”的高官--自民党干事长武部勤和公明党干事长冬柴铁三则于21日至23日出访中国。

最富戏剧化的一幕也就开始了：胡锦涛于5月22日在北京，对敢为小泉纯一郎“传诵”“靖国神社内政干涉论”会见了武部勤和冬柴铁三当面以“砌墙说”强硬地警告日本：“中日关系可能毁于一旦”。

次日，也就是5月23日，吴仪副总理突然因“紧急公务”取消了与小泉的会谈提前回国，到此，在东方评论员看来，在北京提前召回吴仪之后，“最富戏剧化的一幕”也终于让我们看到了。


*** 除非小泉在靖国神社的立场上有实质性的改变，弄不好，“中止对话的层级”有可能扩展到部长一级的官员

东方评论员认为，北京提前召回吴仪所强调的意义非常明明，那就是中国高层决心彻底中止与小泉政府的一切高层接触，这就意味着、除非小泉在靖国神社的立场上有实质性的改变，否则，不仅胡锦涛、温家宝不可能再搭理小泉纯一郎，也很可能意味着吴仪所代表的副总理一层级的领导人，也将不再与小泉政府的相应人士对话。在我们看来，弄不好，这一“中止对话的层级”甚至还有可能扩展到部长一级的官员。


*** “尽可能地稳住”“不进则退”的中日关系，是双方都必须面对的现实问题


因此，在中日高层对话全面中止的情况下，如何将这个重要的、但却已经到了“不进则退”境地的中日关系“尽可能地稳住”，就成了中日双方都必须面对的现实问题。

说到这里，我们再回过头去观察这一轮“在重大原则性问题上取得突破与进展的可能性极小”的“局长级磋商”，那么，我们也就很容易感觉到，举行这一轮“局长级磋商”，可以说双方的“意图”是在“各有侧重”：其中，北京手法显得非常现实，那就是，在一系列问题上、比如、靖国神社问题、台湾问题、还有教科书问题、通过吴仪访问日本这一过程，国际社会、包括日本社会在内，都是看在眼里的，即：在维持“中日关系”的问题上，北京体现出了责任感，中国也已经做到了“仁至义尽”。

*** 对北京而言，提前召回吴仪，意外出牌的目的，还是在于“尽最后努力”去“挽救”中日关系

东方评论员认为，对北京而言，提前召回吴仪，让小泉纯一郎在日本社会和国际社会面前“无法交待”、以及严厉警告中日关系“已经到了一推就倒”、引导日本社会国际社会“必须重视”对国际经济稳定与繁荣有着重大影响作用的中日关系的“危险性”，都不是“手段”而已，在我们看来，北京如此强硬、意外出牌的目的、归根结底还是在于“尽最后努力”去“挽救”中日关系。


*** 中日关系是否“最终彻底走向失败”，不是、也绝不应该是北京“单方面让步就可以解决的”事情

然而，首席评论员指出，中国的做法显示，这种“挽救”是有原则的“挽救”，也就是说，北京在努力做到“尽人事”的基础上，分明抱着一种“天要下雨、娘要嫁人”的超然态度，而不是什么“不管中日关系现在是多么困难，我们也不能让中日关系彻底走向失败”。

因此，在我们看来，中国应该“警告”日本的话、以及可用以“挽救”中日关系的事，北京都已经说了、也都已经做了，因此，明白“严重后果”小泉纯一郎、愿意怎么做，尽管去做好了，是选择推倒中日关系这堵墙，还是留着这面墙，悉呼尊便！

在我们看来，中日关系是否“最终彻底走向失败”，不是、也绝不应该是北京“单方面让步就可以解决的”事情。

*** 北京“根本就没有那种继续大度、继续单方面顾全大局的本钱、更没有这种必要”

在这个问题上，就如我们之前所强调的那样，“破裂”中日关系、动摇中日间的“经济配合”、是美国进这一步控制、并最大限度利用日本政治、军事、经济资源的前提。因此，在华盛顿保守主义决策层“正在竭尽全力”、想千方百计地将目前的中日关系“给彻底破裂掉”的时候，在日本右翼也正在以“不管中日关系现在是多么困难，我们（中国）也不能让中日关系彻底走向失败”这种思维“做人质”，“有心狂赌”“北京最后一定不能让中日关系彻底走向失败的”情况下，东方评论员认为，北京“根本就没有那种继续大度、继续单方面顾全大局的本钱、更没有这种必要”。


在我们继续这个话题之前，一起再来看一则来自日本的消息。


《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 日本首相小泉不拜靖国　改参拜“千鸟渊”

【东京消息】据报道，由于最近参拜靖国神社的话题，引发中日紧张关系，小泉纯一郎没有前往靖国神社，改往距离靖国神社只有十分钟路程的“千鸟渊”参拜。
小泉从2001年上任以来，每年都会前往靖国神社参拜，不过今年元旦小泉参拜时，曾引起中国方面的反弹，再加上不久前副总理吴仪突然取消双边会谈，为了避免中日关系雪上加霜，小泉今天低调前往另外ㄧ个“千鸟渊”神社参拜，这个神社的性质跟靖国神社非常类似，不过相较起来比较不敏感，一般预料，小泉可能担心进一步激怒中国以及韩国，才会临时舍弃参拜靖国神社。事实上，日本最新的民意调查，也有超过半数不希望小泉参拜靖国搞坏邻国关系。



【时事点评】小泉纯一郎当天没有去参拜靖国神社，而前往“千鸟渊”的战殁者墓苑献花、在东方评论员看来，表面上，“这看起来的确像”是在“为了避免中日关系雪上加霜”。

*** “千鸟渊”是个什么东东？

然而，只要仔细看看这个“千鸟渊”是个什么东东，那么，我们也就不难看清小泉纯一郎这样做是“意欲何为”了！

所谓的“千鸟渊战殁者墓苑”实际上与靖国神社相隔600多米，里面埋葬着在日本侵略战争中死去、而无人认领的约35万日本军人和军属。显然，“千鸟渊”和靖国神社的性质一样，都是日本军国主义的“招魂所”，都是一件用以美化日本侵略战争史的“道具”。

东方评论员之所以称之为“道具”，就在于“道具”，都是“因时因需”而用，事实上、对这么一件“道具”、小泉纯一郎也不是第一次使用。我们记得，就在去年的8月15日、在日本第二次世界大战中宣布无条件投降的战败日，小泉纯一郎就曾经搬弄过这件道具、到“千鸟渊”“一游”。

*** 时间“太敏感”，而不得不使用的一个“障眼法”

在我们看来，当时的小泉之所以选择“千鸟渊”去拜祭战殁者、是担心“815”投降日去靖国神社“太敏感”，而不得不使用的一个“障眼法”。显然，就情形而言，由于中日关系已经到了“一推就倒”的地步，当时的情况也和现在非常类似、那就是“同样是太敏感”了，因此，小泉也就需要再来了一次“障眼法”。

如果要搞清楚小泉纯一郎此次“障眼法”的目的，我们再来看一段来自日本的新闻，之后，东方评论员将展开讨论，看看小泉纯一郎到底“意欲何为”？


《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 日本首相助手表示：靖国神社战犯灵位应移走

【综合外电消息】据报道，日本首相小泉纯一郎的助手中川秀直试图平息参拜靖国神社引起的中日纷争，他建议将甲级战犯和其他战死者分开祭祀，以争取中国支持日本成为联合国安理会常任理事国。

据共同社报道，中川秀直昨天出席富士电视台的政论节目时表示，期待靖国神社和遗属们通过协商，自发性地将甲级战犯同其他战争中的死者分开祭祀。

中川秀直是执政自民党国会对策委会委员长。

法新社报道，自民党政调会长与谢野馨也建议，将靖国神社中战犯的名字除掉，将他们的灵位迁移到另一个神社。

与谢野馨说：“我认为将他们分开祭祀是正确的做法，日本和中国应务实地解决纷争，寻求圆满的方案。”

中川秀直说，他希望将甲级战犯同其他战死的士兵分开祭祀后，将能争取中国支持日本成为联合国安理会常任理事国。

他表示应将靖国神社问题和日本“入常”问题一并考虑解决。

他说：“我认为这是可能的做法，我认为首相将会谨慎处理此事并作出适当的决定，包括适当的时间。”

他还强调小泉是以“个人”身份而不是以首相身份到靖国神社参拜，希望得到中方的理解。

靖国神社供奉日本250万名战死士兵的灵位。1978年，靖国神社将14名甲级战犯，包括二战期间的日本首相东条英机的灵位安置在内，引起邻国的不满。

过去也有人提出将甲级战犯的灵位迁出靖国神社，但被靖国神社反对。

据共同社前天公布的民调，在每五个日本人中，将近三个人反对小泉今年到靖国神社参拜。

小泉一再为他参拜靖国神社的做法辩护，他强调参拜是尊敬战争中的死者并保证日本将不会再发动战争。

小泉被询及今年是否会参拜靖国神社时表示，他何时参拜将作适当的判断。自小泉2001年上台后，每年都到靖国神社参拜，引起中韩两国的抗议。


【时事点评】看到这则消息，东方时代的时事评论员们不禁“叹为观止”：看来不仅小泉纯一郎的“小聪明”“天下闻名”，他身边的所谓助手和高参、耍起“小聪明”起来、更是无人可比。

*** 这个时期重提这一设想，显然是“醉翁之意不在'鬼'”

请大家注意这一段：日本首相小泉纯一郎的助手中川秀直试图平息参拜靖国神社引起的中日纷争，他建议将甲级战犯和其他战死者分开祭祀，以争取中国支持日本成为联合国安理会常任理事国。而自民党政调会长与谢野馨也建议说：“我认为将他们分开祭祀是正确的做法，日本和中国应务实地解决纷争，寻求圆满的方案。”

众所周知，“将甲级战犯同其他战死的士兵分开祭祀”的设想，并非什么新玩意儿，许多年来，日本国内一直就有人提起，我们就注意到，到了小泉纯一郎政府、由于他一直公开、强硬地要去靖国神社“拜鬼”、而且主要拜的就是日本右翼最想拜的“那十四个大鬼”，显然，“分开祭祀”的设想就不再吃香，因此，在东方评论员看来，小泉纯一郎“身边的高参”在这个时期重提这一设想，显然是“醉翁之意不在'鬼'”。

*** 日本民众在许多媒体的引导下、对小泉纯一郎的所做所为“也似有感悟”

我们知道，中国对日外交的三大难题依次是：参拜靖国神社、美化侵略历史的教科书和美日联手介入台湾问题。简而言之，就是“历史和台湾”两大问题。除此之外，就是日本目前正在“上下总动员”的联合国“争常”问题，在东方评论员看来，这也是“中日关系”另外一个极可能产生重大影响的“问题”之一。

因此，东方评论员认为，小泉纯一郎让自己的心腹、于此时抛出这一论调，主要出于两层目的：第一，由于吴仪如期访日、却又意外地提前中止访问行程，可以说是在日本本土上、当着日本民众的面，“晾”了小泉纯一郎一回。在经过一番“嘴巴官司”之后，“恼羞成怒”的小泉纯一郎、不仅没有能靠攻击北京“不讲外交仪”而博得半点同情，反而在日本社会和国际社会面前是“越辩越白”，结果是，不仅日本国内的反对党公开喊出了“打倒小泉内阁”的口号，日本民众在许多媒体的引导下、对小泉纯一郎的所做所为“也似有感悟”。

*** 日本“经济首相”规劝小泉

我们注意到，据一家日本媒体调查，前几天，“反对”小泉纯一郎继续参拜靖国神社的日本民众众去年同期的45%一度上升到了近60%，而“支持”的比例则从52%下降到了“37%”，显然，从“支持”与“反对”的升与降之幅度来看，小泉纯一郎不难从中感受到吴仪“如期访日”对日本各层做工作、以及胡锦涛以“一推就倒”强烈警告日本、“一软一硬”、双管齐下“所带来的沉重压力”，据说有日本“经济首相”之称的丰田总裁就劝小泉纯一郎、说“中日关系不能再坏下去了”！从这些已经发生的事情来看，日本社会似乎已经有了“一丝反思”的苗头。

*** 警惕日本将“靖国神社”与“争常”相挂钩

然而，在东方评论员看来，“这种苗头”是非常脆弱的。我们认为，日本右翼正在针对刚出现的这“一丝反思”、而酝酿着“一系列小动作”。

显然，值得警惕的是，日本首相小泉纯一郎的助手中川秀直、这次是打着“试图平息参拜靖国神社引起的中日纷争”的旗号，将“甲级战犯和其他战死者分开祭祀”作为条件，与“争取中国支持日本成为联合国安理会常任理事国”相挂钩，东方评论员认为，这本身就是在瞄着日本社会的这“一丝反思”而在“故做姿态”。

众所周知，靖国神社问题，其本质是日本社会对日本侵略战争历史的认识问题，是日本右翼试图通过为“甲级战犯”平反昭雪、为日本军国主义招魂、企图复走军国主义老路、达到快速成为“政治、军事大国”的一个卑劣手段，并因此而“臭名在外”。

*** 在这一番“高论”中，“参拜甲级战犯”与“入常门票”竟然被设想成了一种“等价交换”

然而，从小泉身边“高参”抛出的这一番“高论”中，我们不难看出，它分明是“摇身一变”、变成了一个与中国“讨价还价”、索取“入常”的筹码，如此一来，旨在为军国主义翻案的靖国神社问题、竟然成了日本“愿意维持中日关系”的一种“报酬”，从而将“参拜甲级战犯”与“入常门票”变成了一种等价交换，即：日本政府“愿意”在靖国神社问题上让步、以“甲级战犯和其他战死者分开祭祀”，去换取中日关系的改善、按照这种逻辑，那么，北京自然也应该“支持日本成为联合国安理会常任理事国”。


*** 中国“不可能同意”将成小泉攻击北京最好的借口

毫无疑问，东方评论员认为，北京肯定不会拿“支持日本成为联合国安理会常任理事国”、去换取日本所谓的、将“甲级战犯和其他战死者分开祭祀”，因此，对小泉政府而言，中国“不可能同意”也就成了他表达了所谓的善意之后，攻击中国“不通情达理、没有诚意改善中日关系的最好借口”。

*** 北京在力争“内外结合”挤压日本右翼煸风点火的空间

我们认为，从吴仪不顾小泉政府的干扰、“如期访日”、与日本社会广泛接触，一面“体现中国改善中日关系的真诚愿望”、一面努力做日本社会的工作；另外、又提前中止了行程，旨在将胡锦涛主席对日本的严厉警“告付诸实践”、再加上之后中国外交部一再重申“只要妥善处理靖国神社问题，中日关系就能得到改善”的立场来看，中国决策层的策略显然是：在以中日关系就要破裂的事实、去促使日本社会、特别是日本经济界认识“小泉路线”的巨大危害性、从而“尽可能地孤立日本右翼势力”、力争“内外结合”去挤压日本右翼煸风点火的空间。

*** 这一番“高论”、可以说就是针对着上述策略的一招“釜底抽薪”

因此，在东方评论员看来，小泉通过身边的“高参”、今天抛出的这一番“高论”、可以说就是针对着上述策略的一招“釜底抽薪”：表面上是在准备“讨价还价”、实际上却是在为日后“将不诚心改善中日关系、并且力图阻止日本“入常”的帽子”全部扣在北京的头上、从而为伺机再次煸动日本民族情绪“做前期准备工作”。

日本近来一系列针对中国的挑衅动作，其目的是要激怒中国，从而为日本迅速武装制造借口。这也是力量陷于中东地区的美国当前希望看到的情形，美国希望日本改变以前在中美之间左右逢源的做法，直接协助其遏制中国。因此，美国甚至不惜鼓励日本修改其和平宪法。

*** 其“用心之险恶”，是想通过刺激中国、迫使北京“提前接招”。

显然，东方评论员认为，日本今天抛出的这一番“高论”的“用心险恶”，中国决策层不可能看不出来，因此，这一番“高论”的本身就具有两面性，一面是面向对日本侵略历史有模糊认识的日本社会和国际社会，意在通过这一套“等价交换”的“理论”、去宣扬日本“有意”化解中日关系的紧张。

而另一方面，却是面对中国决策层，在东方评论员看来，在现在这种紧张的情况下、“这种卑劣的论调”、在明知北京“不可能同意”的情况下，竟然被小泉纯一郎身边的高官“一字一句、态度认真地”正式广播出来，这分明就成了“一种挑畔”。其真正意图是小泉纯一郎在讨好日本社会和国际社会的同时，却在“变本加利”地刺激中国，想通过刺激中国、迫使北京“提前接招”。


*** 小泉纯一郎这次的“千鸟渊”之游，显然是在“探路”

前面说了，去年“815”的当天，小泉之所以选择“千鸟渊”去拜祭战殁者、是担心“815”投降日去靖国神社“太敏感”，而不得不使用的一个“障眼法”。然而，在今天，小泉之所以选择“千鸟渊”去拜祭战殁者，表面上看似是因为中日关系已经到了“一推就倒”的地步、而主动地“后退了一步”、避免去“火上浇油”。

然而，首席评论员指出，小泉纯一郎这次的“千鸟渊”之游、显然有为“甲级战犯和其他战死者分开祭祀”进行探路的意图在内。在我们看来，小泉纯一郎的这次探路，不仅是在试探日本国内民众的反应，更是在试探中国的反应。

对日本右翼而言，只要北京“提前接招”，对这一论调加以驳斥，或者对小泉纯一郎改去“千鸟渊”拜鬼大加鞭打，那么，他们就可以立刻“借力打力”、将“中国的驳斥”立刻“上升为”是中国对日本“有诚意解决靖国神社问题”的“这一建议”的正式拒绝，从而将阻碍中日关系改善的大帽子“直接扣在”北京的头上，继而为自己“里外不是人”的尴尬处境彻底解套。

特别需要指出的是，对小泉纯一郎而言，最妙的地方则在于他在达此目的的同时，甚至不需要去招惹代表着日本极端右翼势力靖国神社的不痛快、去提什么“移除十四个甲级战犯灵位”这一类的棘手话题。

*** 北京“提前化解”的第一步似乎已经走了出去

对此，东方评论员认为，对小泉纯一郎的“这一险恶用心”，北京自然是有必要“认真对待”、并提前加以化解，在我们看来，北京“提前化解”的第一步似乎已经走了出去，这就是“沉默”，在东方评论员看来，现在的“沉默”，就是最好的反击，其意思非清楚，那就是，你小泉纯一郎既然有诚意解开靖国神社这个“死疙瘩”，那好，北京也就“听其言、观其行”，小泉的助手中川秀直不是已经建议将“甲级战犯和其他战死者分开祭祀”，以争取中国支持日本成为联合国安理会常任理事国了吗？这句话中国已经听见了，如果日本政府真心诚意地愿意将甲级战犯的灵位“先拖出来”，谁也不会阻拦，以后的事情以后再说；当然，如果日本政府没有诚心这样做，也不必难为情，因为谁也不会把这种“解决不了任何实际问题的建议”当一回事。


总之一句话，善使小聪明的小泉纯一郎、和他手下那群一样擅长耍小聪明的助手、高参们，如果你们真觉得好玩，你们就自己先玩去吧！在东方评论员看来，中日关系已经到了这一步，也就是说，明白“严重后果”小泉纯一郎、和日本社会，愿意怎么做，尽管去做好了。

*** “推墙”或者是“砌墙”，悉呼尊便！

在我们看来，日本政府当然有可能选择推倒中日关系这堵墙，与中国为敌，丢掉在中美间的战略回旋空间，去接受美国更为牢固的控制，可以预见的是，一旦日本选择与中国正式为敌，那么，美日关系将随着美国对日本的进一步控制、而达到历史上“最紧密、最友好”的程度，美国人也就再不会担心来自日本的任何威胁，不管是军事威胁还是经济威胁。

然而，这种“最紧密、最友好”的美日关系、却无异是日本右翼的恶梦。因此，在我们看来，日本或许会选择”还是留着““这面墙”，以借北京的庞大身躯、为日本遮挡一下来自华盛顿的凄风厉雨，当然了，在胡锦涛主席已经“将一堵一推就倒的墙”摆在日本政府的面前之后，“推墙”或者是“砌墙”，这些都是日本政府和日本社会的事情了，如何选择、悉呼尊便！

*** 一个“具体事务性局级蹉商”，却意外地承担了“暂时维系”中日关系的历史重任

前面已经说了，在气氛非常紧张的时候，在东海问题上、中日双方还能坐下来，并从今天下午开始的这一轮“局长级磋商”，“都愿意坐下来”的背后，显示双方都在“各有所图”，东方评论员认为，北京想的是“毁墙容易砌墙难”，在坚持原则的前提下，有一分希望就尽一份努力；

对日本而言，吴仪不见小泉，事实上已经导致中日高层对话的彻底中断，在这种情况下，备受国内和国际巨大压力的小泉纯一郎（小泉不是承认说，他对美国承诺要为改善中日关系努力吗？）也的确需要保持一个渠道与中国“保持对话的气氛”，显然，东海问题“会谈”本身，就为中日双方同时提供了“这样的一种机会”。

因此，在东方评论员看来，尽管东海问题会谈很难取得突破，但是，就这样的一个“具体事务性局级蹉商”，却意外地承担了“暂时维系”中日关系的历史重任。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
