# -*- org -*-

# Time-stamp: <2011-08-04 12:01:25 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 2005年7月13日 星期三



** 金正日在平壤百花园迎宾馆会见唐家璇




【平壤7月13日消息】朝鲜劳动党总书记、国防委员会委员长金正日１３日下午在平壤百花园迎宾馆会见了正在这里进行正式友好访问的中国国家主席胡锦涛的特别代表、国务委员唐家璇。

唐家璇首先转达了中共中央总书记、国家主席胡锦涛致金正日总书记的口信。胡锦涛在口信中表示，中国党和政府高度重视中朝传统友谊，愿同朝鲜党和政府共同努力，深化各领域的友好合作，推动中朝关系不断取得新的发展。胡锦涛说，第四轮六方会谈将于本月底举行，希望中朝双方继续保持密切的沟通与合作，共同推动六方会谈进程取得实质性进展。

金正日对胡锦涛的口信表示感谢。他说，按照去年他访华时同胡锦涛总书记达成的共识，朝中关系正在顺利向前发展。继承和不断发展朝中传统友谊是朝方坚定不移的方针。朝方将继续同中方共同努力，在高水平上进一步推进朝中友好合作关系。金正日表示，实现半岛无核化是朝方的努力目标，希望六方会谈机制成为实现半岛无核化的重要平台。朝方期待下一轮会谈如期举行并取得积极进展。中方为重启六方会谈作出了不懈努力，朝方给予高度评价。

唐家璇表示，进入新世纪，在两国最高领导人的直接关心和双方共同努力下，中朝传统友好合作关系取得了新的发展。不断巩固和发展中朝传统友好合作，符合中朝双方的战略利益。他重申，中方将继续本着“继承传统、面向未来、睦邻友好、加强合作”的精神，同朝方共同努力，全面深化中朝友好合作关系。唐家璇指出，中方在半岛核问题上的立场很明确，即坚持实现半岛无核化目标、坚持维护半岛的持久和平与稳定、坚持对话和平解决的大方向。中方将同包括朝方在内的各方共同努力，推动新一轮六方会谈取得成果。

朝鲜最高人民会议常任委员会委员长金永南１３日上午在万寿台议事堂会见了唐家璇。

当天上午，唐家璇还到锦绣山纪念宫瞻仰了金日成主席的遗容。今年是中国人民志愿军入朝参战５５周年，唐家璇冒雨前往位于平壤市区的朝中友谊塔敬献了花圈，表达对中国人民志愿军烈士们的深切怀念。



【时事点评】在东方评论员看来，朝鲜最高领导人金正日今天出来见胡锦涛主席的特别代表、国务委员唐家璇、根本就已经是象征性的了，象征着朝鲜在朝核问题上与北京的立场“是完全一致的”，也象征着朝鲜方面是在北京的“费心的劝说下”、“才同意重启六方会谈”的。


*** 唐家璇一口气讲出“三个坚持”显示中国的“最新立场”仍然没有任何变化

而北京的“最新立场”又是什么呢？请大家注意这一段文字：唐家璇指出，中方在半岛核问题上的立场很明确，即坚持实现半岛无核化目标、坚持维护半岛的持久和平与稳定、坚持对话和平解决的大方向。

显然，唐家璇在与金正日见面后、一口气讲出的这番话中、用了“三个坚持”、这显示中国在朝核问题上的“最新立场”仍然没有任何变化。


*** 六方会谈”中的“六方”、各自都在打着什么小算盘呢？

然而，东方评论员也注意到，确切的消息显示“六方会谈”本月底又将举行，而赖斯在北京除了第一次提到了“朝鲜半岛无核化”这个北京、朝鲜的“专用名词”、显示了“与以前有所不同”之外，在随后的日本、韩国之行中、却又多次“老调重谈”、强调美朝核政策的原则立场“也没有任何改变”。

因此，东方评论员不禁就要问一句：若到了最后一刻、也就是第四轮六方会谈开始的时候，到底是谁的立场会改变呢？“六方会谈”中的“六方”、又各自都在打着什么小算盘呢？

在我们进一步讨论这个问题之前，再来看一则消息、看看卢武铉在见到自日本而来的赖斯时、当着这位女士的面、又说了些什么。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com


** 卢武铉称希望美国在六方会谈中发挥重要作用




【汉城7月13日消息】据报道；韩国总统卢武铉今天在总统府青瓦台会见美国国务卿赖斯时说，希望美国在重启的六方会谈会谈中，发挥重要作用，并表现出解决朝核问题的意志。

据青瓦台发言人金晚洙说，卢武铉在会见时认为，朝核局势正朝着积极方向发展，赖斯再次访韩，意义非同寻常。赖斯强调，现在是解决朝核问题的良机，美国已做好为使六方会谈取得成功而付出努力的准。她同时也认为，朝鲜的战略性抉择也很重要。

卢武铉还说，朝鲜半岛乃至东北亚从对峙、对立走向和解与合作的转变的过程中，美国的作用极其重要，并且与朝鲜半岛的局势息息相关。

在随后举行的韩美联合记者招待会上，赖斯表示，朝鲜重返六方会谈“走出了非常好的第一步”。美国支持韩国提出的“如朝鲜完全弃核则直接提供电力”的提案，因为它既解决了朝鲜的能源问题，又可消除核能在朝鲜扩散的担忧。这是一个解决朝鲜能源问题的好办法和富有创造性的提案。

赖斯表示，朝核问题同朝鲜半岛无核化相关，它不仅是美国关心的问题，也是韩国、中国、日本和俄罗斯等各方所共同关注的问题，因此六方会谈是解决朝核问题的最佳途径。

赖斯还说，美国方面在2004年第三轮六方会谈上提出的解决朝核问题的方案仍然有效。




【时事点评】东方评论员注意到，卢武铉今天在总统府青瓦台见赖斯时说，“希望美国在重启的六方会谈会谈中，发挥重要作用，并表现出解决朝核问题的意志”。


*** 韩美”间“龌鹾”与“中朝”间的“协调”“对比度”似乎也过于强烈了

显然，在我们看来，从卢武铉当着赖斯的面、就对华盛顿“寄予一大堆的希望”来看，韩国对美国在即将重启的“六方会谈”中将会“起什么性质的作用”虽然还没有最后确定、但已经知道得”八九不离十“了。

这与朝鲜最高领导人金正日对国务委员唐家璇所说的“中方为重启六方会谈作出了不懈努力，朝方给予高度评价”的态度相比，“韩美”之间“龌鹾”与“中朝”之间的“协调”、其“对比度”似乎也“过于强烈”。

因此，在我们看到卢武铉在会见赖斯时所说的“朝核局势正朝着积极方向发展”的时候，恐怕熟悉“朝核问题”现状的人没有几个人“会真正相信”。


*** 北京和华盛顿在朝核问题的“最新立场”、显然也存在着某种“对比度”

首席评论员就指出，“朝核问题”“是否”正朝着着“积极方向”发展，恐怕要看站在什么立场来看问题，在我们看来，如果站在中国、韩国、俄罗斯的立场来看，相较以前、“朝核问题”的确在向积极方向发展，但是，如果站在美国、日本的立场来看朝核问题的“最新进展”，不仅不是朝向“积极方向”、反而是“倒退得令人难以忍受”。

因此，东方评论员认为，不仅“韩美”关系与“中朝”关系存在着“反差”、就是北京和华盛顿在朝核问题的“最新立场”、显然也存在着某种“对比度”。



*** 唐家璇的“三个坚持”与赖斯的“重弹老调”之间似乎很难找到“交点”

东方评论员注意到，赖斯昨天在东京同日本外长町村信孝谈话后指出，“朝鲜在来临的六方会谈必须承诺放弃核武，否则会谈将以失败收场”。另外，赖斯直到今天还在汉城强调“美国方面在2004年第三轮六方会谈上提出的解决朝核问题的方案仍然有效”，显然，华盛顿这实际上是在弹“朝鲜应该先行弃核”的“老调”。

然而，与此相对应的是，唐家璇在同一时间里、在平壤也是一步不让、即中国“坚持实现半岛无核化目标、坚持维护半岛的持久和平与稳定、坚持对话和平解决的大方向”。

显然，在我们看来，就唐家璇和赖斯在同一时间里的“各自表述”来看，赖斯今天在汉城“重弹之老调”与唐家璇今天在平壤态度鲜明地“三个坚持”之间、似乎很难找到“交点”。


*** 北京“毫不指望”华盛顿在“六方会谈”中能起到建设性的作用


东方评论员认为，赖斯在汉城的这番话，说明华盛顿“承认”“朝核问题”已经由先前“华盛顿认定的朝鲜无核化问题”转化成了“中国认定的朝鲜半岛无核化问题”，因此，在我们看来，唐家璇的“三个坚持”与赖斯的“老调重弹”之间，似乎也就找到了这么个“表面上的交点”。

不过，我们认为，这个所谓的“表面上的交点”、很可能仅仅是为了通过将“朝核问题”纳入到涵盖驻韩美军核武器问题的“朝鲜半岛无核化问题”中、暂时打破目前的僵局、启动第四轮“六方会谈”。

对此，首席评论员就指出，看来北京“毫不指望”华盛顿在“六方会谈”中能起到建设性的作用，但是，北京也“毫不怀疑”华盛顿非常渴望“六方会谈”能够重新启动。


*** 华盛顿似乎看到了一种危险

因此，就在我们觉得很难在“中美”互不相让的“最新立场”之间找到“某个交点”的时候，东方评论员注意到，赖斯在见过卢武铉后的记者会上，再一次提到了她在北京的一个“新说法”，即“朝核问题同朝鲜半岛无核化相关”，显然，这与北京对朝核问题的“一惯立场”相吻合。

不仅如此，赖斯也没有忘记对韩国的立场“表示一点尊重”，她说，美国支持韩国提出的“如朝鲜完全弃核则直接提供电力”的提案，认为“它既解决了朝鲜的能源问题，又可消除核能在朝鲜扩散的担忧。这是一个解决朝鲜能源问题的好办法和富有创造性的提案”。

东方评论员认为，一惯骄横的白宫“能注意到”韩国的提案，这只能说明一个问题、那就是：华盛顿似乎看到了一种危险，即一旦韩国对美国改变其强硬的“朝核政策”“彻底失去了耐心”、那么，“中俄”很可能借助韩国急于“开发朝鲜”的战略需要、抛开“六方会谈”、拉着整个朝鲜半岛“另起炉灶”。


*** 卢武铉在这个时候“来这几下子”，摆明了是在强调这么一个立场

事实上，有消息说，韩朝两国另外在汉城经过彻夜谈判，韩国已经答应朝鲜的要求，立刻向它提供50万吨白米的援助。这还不算，韩国还同意为朝鲜提供生产衣服、鞋子和肥皂的原料，以换取对朝鲜矿业的投资权，挖掘锌、菱镁矿和煤。韩国准备做的另外一件事，就是赖斯这今天“特别提到”的、韩国向朝鲜供电问题。

显然，在东方评论员看来，卢武铉在这个时候“来这几下子”，摆明了是在强调这么一个立场，即：不论“六方会谈”启动与否，韩国都要在“朝鲜半岛经济整合”的道路上继续走下去。


*** 中俄”更愿意看到的“另起一座炉灶”

在我们看来，华盛顿之所以在这个节骨眼上、“愿意”以承认北京所定义的“朝核问题”概念、来换取“六方会谈”的重新启动，就在于华盛顿“不想置身于半岛事务之外”。

东方评论员认为，华盛顿“这样处理”虽说是迫不得已，但是，其企图心也是“毫不含糊”的，在我们看来，华盛顿这样做显然是想将韩国决心启动的“朝鲜半岛经济整合”、纳入到自己参与的“六方会谈”的框架之中、而不是“中俄”更愿意看到的“另起一座炉灶”。


*** “不想置身于半岛事务之外”的美国人、在策略上还是非常狡猾的


非常清楚，华盛顿这样做非常狡猾，如此一来、美国人就可以在明知不能阻止“朝鲜半岛经济整合”进程的情况下，顺势而为、干脆就将其纳入“有自己一份”的“六方会谈”框架中，这样，美国就多少能保持自己对整个进程的影响力、并作为韩国这个小国、在与中俄这两个大国打交道时“非常需要的”“一个平衡力量”、来保持对韩国、对中俄、对东北亚事务的影响力。

另外，必须看到的是，华盛顿在玩这一手的同时，也将日本人“给捎带着一起算计了”。


*** 日本要想继续在朝鲜半岛问题上起作用、只有两条路走

非常清楚，在这中间，我们也就几乎“看不到日本人的位置”了。如此一来、日本要想继续在朝鲜半岛问题上起作用、只有两条路走：一是参与朝鲜半岛经济整合、也就是东北亚经济一体化；当然，这虽然符合日本有“长期利益”、却不符合日本保守势力的“短期利益”。

另一条路，就是更紧地抱紧美国的大腿，更卖力地充当其遏制中国、包围俄罗斯的角色。值得警惕的是，这虽然不符合日本有“长期利益”、却绝对符合日本保守势力的“短期利益”，因此，对小泉政府极可能选择的这一条路、再次对北京进行战略试探，北京有必要做最充分的准备工作、及时对其加以迎头痛击


*** 不论是中国、还是俄罗斯、在朝核问题上“真正希望”的事情是什么？

另外，东方评论员注意到，在唐家璇转达的胡锦涛致金正日总书记的口信中，锦涛说，“第四轮六方会谈将于本月底举行，希望中朝双方继续保持密切的沟通与合作，共同推动六方会谈进程取得实质性进展”。

值得注意的是，赖斯在与小泉纯一郎会面后，“美日”也异口同声地表示“第四轮六方会谈一定要谈出个结果来”。显然，不论是“中俄朝”、还是“美日”都摆出了一幅“必须有实质性突破”的姿态。

但是，在东方评论员看来，“真正指望”实现实质性突破的莫过于朝鲜、韩国、而真正想将朝核问题继续拖下去的莫过于美国、而想继续恶化“朝核问题”只有日本，因此，在这种情况下，不论是中国、还是俄罗斯、真正希望的事情恐怕与“六方会谈”无关，只想韩国早点拿定主意、在中俄的保护下、启动“朝鲜半岛经济整合”，并构建一个与西边的“上海合作组织”遥相呼应的“东北亚多边安全体系”。


*** 对“中俄”两国而言，“六方会谈”存在与否，也就都不重要了

这样，对“中俄”两国而言，不论华盛顿是多么强硬、日本是如何捣乱，以及“六方会谈”存在与否，也就都不重要了。东方评论员认为，在这种情况下，华盛顿除了尽力讨好韩国之外，对朝鲜就是想不让步都不行，只是让步的多少而已。

说起西边的“上海合作组织”，东方评论员也就顺势将我们关注的焦点转投过去。在一则来自路透社的消息之后，时事评论员将结合伊朗的情况，开始今天的中亚部分。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
