# -*- org -*-

# Time-stamp: <2011-08-02 13:52:31 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil


* 2005年03月15日 星期二
  

** 外界高度关切台美间是否重建构水下监听系统

   【台湾消息】台湾媒体报道称，由台“国防部”2年出版1期的国防报告书中，连续两期提及“水下监听系统”等用语，令外界高度关切台美间是否重启建构水下监听系统“龙睛计划[fn:6]”？知情官员说，中科院确自上开计划获得“水中听音器”技术，惟随海军转向建构8艘柴电潜艇，可望获致主动反潜能量，水下监听将仅用以验证电讯情资。

   2002年度“国防”报告书(页284)首度指出，“国军”建立“电子侦测网”目标，在整合强网、大成等电讯信息，并结合无人遥控载具与“水下监侦系统”，藉联合监侦、识别、频谱管理机制，掌握敌我电磁频谱，支持全般作战。

   该年度“国防”报告书强调，为掌握空中、地面、“水下监侦系统”电讯情资，及敌我电磁之频谱，现正执行电磁频谱管理系统的研究。

   2004年度“国防”报告书168页表示，“国军”为反制潜艇威胁，持续进行线导鱼雷、复合感应水雷等水下武器关键性技术研发，包括：声纳浮标、舰装声纳系统、“水下监听验证系统”及反鱼雷诱标系统等，以提升反潜作战能力。

   “水下监侦系统”与“水下监听验证系统”差异何在？知情官员说，当年台、美合作“龙睛计划”失败，但中科院万象馆仍从合作过程中获得计划主要“水中听音器”相关技术。

   官员描述，这是一种能将电能转换成声波水中进行传播，或将声波转换成电子讯号加以分析应用的技术，是当时“SOSUS”的主要侦测器“水中听音器”制成技术，中科院可利用这项成果，执行水下声波、电讯的验证，与布放水下监听系统的“龙睛计划”大不相同。

   官员表示，未来海军若顺利获得8艘柴电潜艇，舰上声纳网结合“博胜案[fn:7]”，自可组成主动式的反潜网，加上引进线导鱼雷、潜射导弹与水雷布放能量，中科院万象馆研发功能降低。

   【时事点评】据东方军事评论员介绍，台湾这个所谓的“水下监侦系统”已经吵吵嚷嚷多年了。事实上，台“国防部”现在接二连三地抛出这个“项目”，其用意却在新闻的最后一行，即，（台湾）官员表示：未来海军若顺利获得8艘柴电潜艇，舰上声纳网结合“博胜案”，自可组成主动式的反潜网。
 
*** 我们又不能将这笔“军购案”仅从商业的角度去看待

    显然，绕来绕去，又绕到了那“8艘柴电潜艇”的问题上，也就是说，台“国防部”这几天将这个一度“忌讳莫深”的“项目”拿出来“翻炒”，起码有一层意思，还是为了那笔“军购案”。然而，这笔能为美国军火商提供巨额商业利润的军售，我们又不能将这笔“军购案”仅从商业的角度去看待。
 
*** 台湾这笔几千亿新台币“军购案”离通过的时间不会太久

    在东方评论员看来，就如我们之前所说的那样，由于华盛顿已经主导了台湾政治势力的整合，目前，陈水扁的民进党和宋楚瑜的亲民党已经被一纸“联合声明”、通过“中间路线”这个“政策名词”被紧紧地挷在了一起，因此，华盛顿一直压台湾通过、却被“国亲”主导的台湾立法会阻拦的“对台军售案”问题，事实上“已经不存在了”，可以肯定的是，台湾这笔几千亿新台币“军购案”离通过的时间不会太久。
 
*** 美日台之间的军事互动，其紧迫性也就立刻凸现出来了

    在之前的点评中，我们已经说过，由于美日台无力阻止“反分裂法”的通过，因此，对台独以及支持台独的势力而言，“台独进程”如何调整现在已经日见清晰，
    #+HTML:<a>在东方评论员看来，这就是由“法理台独”为主、转向“武力拒统”为主的“台独政策”</a>
    #+LaTeX:\red{在东方评论员看来，这就是由“法理台独”为主、转向“武力拒统”为主的“台独政策”}
    。

    我们认为，在台独势力避开“反分裂法”的锋芒、而转走“武力拒统”的时候，如何加速美台、美日台之间的军事互动，其紧迫性也就立刻凸现出来了。

    在一段相关新闻后，东方时事评论员、军事评论员将一起就此问题进行展开。

    [[http://www.dongfangtime.com][《东方时代环球时事解读》]]

** 台军汉光演习本周展开将与美日新联机推演

   【台湾消息】据台媒报道，台军“汉光二十一号演习”兵棋推演将在本周展开，据了解，前来台湾指导“汉光二十一号演习”的美日台计算机兵棋联机的外军顾问已陆续抵达台湾，外军顾问团人数将首度破百。

   权威消息指出，为反制“反分裂国家法”，台军“汉光二十一号演习”兵棋推演将在本周展开，并且台军本周将借由“汉光”演习兵棋推演，进行美军太平洋总部联机兵棋推演，参与国有美、日及新加坡。

   台“国防部”经与相关单位协调后正式核定“汉光二十一号演习”将在中部地区展开，演习区域以彰滨工业区因应反突袭、反破坏、反恐等作为进行演练。

   据透露，台美双方已规划兵棋联机，预计今年美方将正式批准通过，由于美国已与日本联机，因此台、美、日未来都将透过太平洋总部联机兵棋推演。“国防部”目前已引进新的联合作战指挥系统，具备与他国联机的功能。

   军方高层指出，这一次的“汉光二十一号演习”预计将动用到清泉岗基地配合救援机队等进行演练作业，同时将大量运用后备军人体系进行城镇保卫作战，而彰滨地区在演习实兵行动中，将会出现包括海军陆战队登陆的“联兴演习”、陆军空降部队降落的“联云演习”及各种火炮射击等“联勇演习”。

   【时事点评】事实上，早在3月8日，就在《反分裂国家法(草案)》正式提交全国人大审议的当天，东方评论员就注意到，针对刚刚提请审议的《反分裂国家法(草案)》，台湾“国家安全会议”秘书长邱义仁专门主持召开了内部会议，称“反分裂法条文中所指‘非和平’手段，其实比‘动武’更加严厉”。
 
*** “台独”想掌握“反分裂法的翻译权”，想得的确不错

    值得一提的是，台湾当局声称：现在台湾要做的行动主要有两个：一是掌握“反分裂法的翻译权”，以便更好地向美日等国“告状”；二是要夸大大陆的“军事威胁”。

    在东方评论员看来，“台独”想掌握“反分裂法的翻译权”，想得的确不错，然而，这种“翻译权”在大陆的手中，显然，“翻译权”是要靠实力做保障的。至于如何夸大大陆的“军事威胁”，陈水扁当局是“行家”，何况旁边还是“美日”两个高参，当然清楚怎么做。

    于是乎，东方评论员立刻就看到，与此同时，台“国防部”也是配合默契、立刻抛出了2005年度重大演习训练规划表。
 
*** 陈水扁这一路演下来，分明是在向大陆展示其武力对抗《反分裂国家法》的姿态

    根据这份规划表，台军今年仅是军演就安排了50次之多。这还不算，第二天，台军的动作就从备战换成了渲染大陆的“军事威胁”。也就是9日一大早，在与李敖于台“立法院”内争辩台湾是不是美国的“看门狗”的问题之后，台“国防部长”李杰仍然是如期“提交报告”，大肆渲染说大陆的军力是如何如何，怎样怎样。

    在东方评论员看来，陈水扁这一路演下来，分明是在向大陆展示其武力对抗《反分裂国家法》的姿态。

    对华盛顿而言，在“台独进程”被“反分裂法”彻底封堵之后，尽快在政治层面给两岸画出一个“和平缓和”的“和平前景”、以暂时稳住中国，并将对台政策由“法理台独”转向“武力拒统”也就具有了非常现实的意义。
 
*** 看美国是如何“玩转”“与台湾关系法”的

    首席评论员指出，在之前，由于美国手中有一个“与台湾关系法”，一般认为，华盛顿就是凭借这个、有意在“协防台湾的问题上”“模糊其辞”、在它需要的时候，就做出一些相应的动作来，以让国际社会相信美国必然会“依法”介入台海的；

    同时，华盛顿还在它认为需要的时候，也可以任意变脸，做出一些相反的言行举止、好让国际社会相信华盛顿的介入“是有条件的”，也就是说，美国在决定“是否介入”之前，也要对“与台湾关系法”中的有关“协防台湾”的启动条件去加以“解释”。
 
*** 有一点足以让华盛顿的决策层感觉“非常难受”

    然而，这都只是“以前的玩法”。东方评论员认为，在《反分裂国家法》已经生效的情况下，可以这样说，由于
    #+HTML:<a>《反分裂国家法》对中国政府具有法律约束力，并授以中央军委、国务院可以“见机启动战争”的权力，此外，对“台独事实”“台独重大事变”、以及“和平统一的可能性全部丧失”这些关键问题的解释权也操持在中国的立法机构手中。</a>
    #+LaTeX:\red{《反分裂国家法》对中国政府具有法律约束力，并授以中央军委、国务院可以“见机启动战争”的权力，此外，对“台独事实”“台独重大事变”、以及“和平统一的可能性全部丧失”这些关键问题的解释权也操持在中国的立法机构手中。}

    因此，在东方评论员看来，有一点足以让华盛顿的决策层感觉“非常难受”，那就是：《反分裂国家法》的“正式文本”在表面上似乎没有“可操作性”、然而，它通过将启动“非和平方式”的条件放在“主观解释第8条”的基础上，更显出它是一个更具“攻击性”的法律。

    如此一来，华盛顿并没有因《反分裂国家法》的通过、就彻底地拿到北京的“底牌”。在东方评论员看来，
    #+HTML:<a>如果华盛顿能够拿到北京的“底牌”、那么，它就可以在不触踫这些“底牌”之前，大可以根据自己的全球战略需要、特别是中东进程的实际情况，精心地准备它的“台独时间表”。</a>
    #+LaTex:\red{如果华盛顿能够拿到北京的“底牌”、那么，它就可以在不触踫这些“底牌”之前，大可以根据自己的全球战略需要、特别是中东进程的实际情况，精心地准备它的“台独时间表”。}
 
*** 《反分裂法》对“两岸现状”的“定义”、实际上就会被“一连串的法律和协议”“承认”下来

    由于“反分裂国家法”将台海现状以“大陆和台湾同属一个中国”在法律上明确规范下来，并通过对“台独事实、台独重大事变、以及和平统一的可能性是否完全丧失”“三条件”也明确了自己的“界定方式”、从而首次将中国政府的旨在维护国家统一的“战争意志和决心”在法律上加以了“确定”。

    所以，不论是从立法的“时机与动机”、还是执法的“决心与意志”来看，东方评论员认为，《反分裂国家法》的正式文本的通过并立刻生效、显然是北京愿为台湾问题“付出一切代价”的最新例证。

    在东方评论员看来，对“两岸现状”给出清楚定义的第二条是非常重要的，可以说它对北京是重要的，对华盛顿也是重要的。我们认为，一旦华盛顿最终让步，并默认了北京所定义的“两岸现状”，那么，在首席评论员看来，有一点是非常清楚的，那就是，《反分裂法》对“两岸现状”的“定义”、实际上就会被 “一连串的法律和协议”“突然”地“承认”下来。
 
*** 华盛顿“玩转”“与台湾关系法”的“操作手法”、实际上已经“成为了历史”

    我们认为，这“一连串的法律和协议”，不仅有已经生效的、给出“两岸现状”之“定义”的中国国内法--“反分裂国家法”，还有美国国内法-- “与台湾关系法”，最后，可以肯定的是，如果大陆和北京间最后能谈出个“中程协议”来的话，那么，这个“中程协议”将毫无例外地“继承”这一“定义”。

    如此一来，不论华盛顿是否愿意，事实上，它之前动不动就亮出“与台湾关系法”、并根据一时需要、或者刻意去“模糊”、或者有意去“明晰”那些个“介入台海的条件”之“操作手法”、实际上已经“成为了历史”。
 
*** 没有明列出“具体的红线”的负面影响也不容忽视

    说到这里，我们再回过头去看“两岸现状”的“如何界定”的问题，我们应该可以更清楚地看到其重要意义之所在。显然，在东方评论员看来，“两岸现状”的“如何界定”的问题，直接关系到中国“能否合法启动”“反分裂国家法”，美国“能否顺利地”启动“与台湾关系法”的问题。

    就如我们昨天在有关台湾问题的点评中所说的那样，不难看出“修正后”的“正式文本”，不仅没有明列出“具体的红线”，较之“草案”相比，也更加体现出了一种特性，那就是“最大的弹性”。

    可以这样说，这种“将释法第八条”去“主观界定红线”的方式，由于没有明确定义所谓台湾不能跨越的“红线”，虽然留给大陆了更多灵活执法的空间，但其负面作用也不容忽视，那就是，极可能造成台湾方面的误判，并给了“台独”伺机挑畔《反分裂国家法》权威的空间。
 
*** 北京这种时刻准备着在“他日释法”“第八条”的态度，已经让方方面面感觉到了“台海的硝烟”

    我们认为，不论是2000年发表的“白皮书”中所列明的“动武三前提”、还是前不久胡锦涛主席在“四点意见”中所列举的“台湾正名”、“去中国化”等“渐进式台独”形式、或者是人大副委员长王兆国在《反分裂国家法（草案）》的“说明”中、所明列的“几条”应引起高度警惕的“台独”手段，比如，台湾当局妄图利用所谓“宪法”和“法律”形式，通过“公民投票”、“宪政改造”等方式，其实“都有可能”促使人大根据《反分裂法》“第八条”解释出“台独事实”、“台独重大事变”的含义，人大甚至“还可能认为”、一旦出现这些情况之后，“和平统一的可能性也就完全丧失了”、从而、受《反分裂国家法》约束的中国政府、启动“非和平方式”也就是顺理成章的了。

    显然，这种“法律的强制力”是“看得见摸得着”的东西，也就是说，随着《反分裂国家法》的生效，尽管里面没有列明具体的红线，在东方评论员看来，北京似乎有意通过这种方式间接地为“他日释法”“第八条”“预做伏笔”。不难看出，北京这种时刻准备着在“他日释法”“第八条”的态度，已经让方方面面感觉到了 “台海的硝烟”。
 
 
*** 被迫“走回头路的”华盛顿、其“强硬的台湾政策”之“强硬度”，已经没有了足够的信用

    因此，东方评论员认为，华盛顿在中东问题“前不着村后不着店”的无奈之下，为了避免“台独进程”与“反分裂法”迎头撞上，在台湾问题上只得逼迫“台独”“走走回头路”。

    如此一来，东方评论员认为，被迫“走回头路的”华盛顿、其“强硬的台湾政策”之“强硬度”，已经没有了足够的信用，在中国政府面前如此，在“台独”势力的面前也是如此，在日本、韩国、澳大利亚这些军事盟友面前又何尝不是如此呢？
 
*** 如何让人“相信”美国“也有一战的决心”，显然就成了华盛顿急需解决的问题

    但是，值得强调的是，台湾无疑对美国具有重大的战略价值，然而，
    #+HTML:<a>这种战略价值之所以重大，很大程度上是因为遏制中国的战略需要。</a>
    #+LaTeX:\red{这种战略价值之所以重大，很大程度上是因为遏制中国的战略需要。}
    对美国决策层而言，遏制中国只是其全球战略的一个重要方面，华盛顿眼中的威胁还有欧盟、俄罗斯、日本等等，这样，台湾的战略价值再怎么重要，也得着眼于其全球战略，换而言之，就算是中国统一了台湾，美国仍然可以是一个世界强权。

    但是，台湾对中国的意义就不一样了，彻底失去台湾的中国、由于将因之被迫付出极大的战略代价，实际上也就失去了成为世界强权的资格。因此，在台湾主权这个问题上，华盛顿很难向中国制定“反分裂国家法”那样、以一种可以为了台湾“不惜一切代价”的决心、去为其“与台湾关系法”树立起足够的威信。

    所以，在东方评论员看来，在一部刻意强调“台独”就是战争的“反分裂国家法”的面前，美国的“与台湾关系法”已经失去了往日的那种“随意解读”的空间。

    在这种尴尬之下，如何让人“相信”美国“也有一战的决心”，显然就成了华盛顿急需解决的问题。
 
*** 通过“打造”一个强大的“美日台”军事同盟的“实际行动”，去让人们重新相信美国“也有一战的决心”

    有分析就认为，《反分裂国家法》的威信就来源于其立法的宗旨、而立法的宗旨就是以法律的强制力、约束中国政府必须以包括“非和平方式”在内一切手段、确保台湾留在中国。

    而华盛顿在“与台湾关系法”的权威、因自身在“是否介入台海”的问题上刻意“模糊”、被已经生效的、立场鲜明的《反分裂国家法》极大地冲击之后，华盛顿显然有意以打造一个强大的“美日台”军事同盟的“实际行动”，去让人们重新相信美国“也有一战的决心”。

    事实上，在华盛顿的对台政策的调整下，台湾、日本的军方都是积极配合，在东方评论员看来，陈水扁当局在这个时候搞“汉光二十一号演习”，并透露说“美日台”计算机兵棋联机也是已成事实，这只是“台独”和支持“台独”的国际势力、为避开“反分裂法”的锋芒、而准备“武力拒统”一系列动作中的一步而已。
 
*** 现实情况下，华盛顿眼中的“上佳的选择”

    可以想像的是，一旦中国认为已经出现了启动“非和平方式”的条件，那么，台海战争已经成了事实。到时，华盛顿就是想根据“与台湾关系法”去介入台海，那也得考虑清楚：首先，由于中美都是“深具战争潜力”的大国，因此，双方如果直接交手、规模小了解决不了问题，但是规模大了，在中美两国都是核大国的情况下，进行一场大规模的战争、就有升级到核战争的风险，这对中美两国而言都是个灾难，这显然也不是个选择。

    因此，在东方军事评论员看来，在华盛顿决策层的眼中，眼下、在华盛顿准备继续向中东方向增加投放战略资源、而美军力量却出现“捉襟见肘”的情况下、全面提升台军的战力、让一个被美军高度整合，高度武装的“台独”去“武力拒统”、在眼前有助于帮美国维持台海现状，在将来又可大幅提高中国完成统一的战略成本，对华盛顿而言，这样去打算盘，不论是着眼于帮助自己去“遏制中国”、还是为了“消耗中国综合国力”、更或是赚取“现实的”商业利润、无疑都是 “上佳的选择”。

    [[http://www.dongfangtime.com][《东方时代环球时事解读》]]

    



[fn:6] 龙睛计划
[fn:7] 博胜案
