# -*- org -*-

# Time-stamp: <2011-08-02 22:05:42 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

#+STARTUP: indent

*  2005年5月12日 星期四

** 胡锦涛会见宋楚瑜一行致欢迎致词

【北京消息】下面是胡锦涛会见宋楚瑜一行致欢迎致词（根据录音整理）

尊敬的宋楚瑜主席和夫人，尊敬的张昭雄副主席和夫人，尊敬的亲民党大陆访问团的全体成员，大家好！

在这春光明媚的五月，亲民党主席宋楚瑜先生率领亲民党大陆访问团来到北京，两岸的华夏儿女、炎黄子孙相聚在一起，都感到非常的亲切。首先，我代表中共中央向宋主席和夫人，向张副主席和夫人，向亲民党大陆访问团的全体成员表示热烈的欢迎，并致以良好的祝愿。

宋主席率团来大陆访问，同中国共产党进行两党的交流和对话，这是我们两党关系当中的一件大事，也必将对两岸关系的发展产生重要影响。这一重大举措充分表明了我们两党为台海地区谋和平，为两岸同胞谋福祉的决心和意愿。符合当今时代的发展潮流，符合两岸同胞的共同心愿。我相信，历史将铭记我们今天的历史性的握手和历史性的会见。

这几天，宋主席一路走来，反复强调“炎黄子孙不忘本，两岸兄弟一家亲”。我同样认为两岸同胞同根、同族、同脉，中华民族五千多年的悠久历史和灿烂文化把我们紧紧联系在一起，我们都是中华民族的子孙，都应该以我们这个伟大民族为自豪，也都应该以振兴我们这个伟大的民族为己任。

今天，纵观世界发展的大势，中华民族的发展面临着难得的历史机遇，求和平、求稳定、求发展是两岸同胞的共同期盼。我们作为两岸政党的领导人，应该登高望远，紧跟时代、顺应民意、奋发有为，为促进两岸的发展繁荣，实现中华民族的伟大复兴而努力。这是时代对我们的要求，也是两岸人民对我们的要求。

宋主席和亲民党坚持体现“一个中国”原则的“九二共识”，坚持反对“台独”，主张发展两岸关系，我们对此高度肯定和赞赏。坚持体现“一个中国”的原则的“九二共识”，坚持反对“台独”，是两岸进行对话协商的政治基础，也是两岸关系和平稳定发展的政治基础。

不久前，中国国民党主席连战先生率团来访，这次宋主席率团来访都得到了大陆同胞的热烈欢迎，也得到了多数台湾同胞的肯定和支持。这就表明两岸的同胞都认为这些做法符合他们的心愿和意愿。在这里我要再次重申，只要承认“一个中国”原则，承认“九二共识”，不管什么人、什么政党，也不管它过去说过什么、做过什么，我们都愿意和他们谈发展两岸关系，促进和平统一的问题。

当前，两岸关系的发展正处在一个关键时期，我们两党应该以积极的作为，向两岸同胞展现两岸关系和平稳定发展的希望和前景，向世界表明两岸的中国人有能力、有智慧解决我们之间的矛盾和分歧。

宋主席把这次大陆之行称为“搭桥之旅”，我衷心地希望通过亲民党大陆访问团的这次访问，在我们两党之间搭起一座互信之桥，在两岸同胞之间搭起一座沟通之桥。一会儿我还要和宋主席进行政治会谈，我相信在共同的政治基础上，经过我们双方的共同努力，会谈一定能够取得积极的成果。我同样相信通过两岸同胞的携手努力，两岸关系一定能够向着和平稳定的方向发展。谢谢宋主席，谢谢各位。




【时事点评】在观看完直播之后，时事评论员们有个共同的感受，那就是在胡锦涛主席在最后表示提及“搭桥之旅”的时刻，可以说，这已经意味着宋楚瑜在最后一刻“终于抛弃了”以“宪法一中”为基础的“十点共识”。

*** 在最后一刻宋楚瑜终下决心将“宪法一中”从“十点共识”中“抽了出来”

这就是说，在大陆“强压”的“促进”下、在连战已经取得成功的“巨大压力”下，在为陈水扁和他自己的“十点共识”宣传了“台湾意识”之后，在最后一刻宋楚瑜终于下了决心将“宪法一中”从“十点共识”中“早早地就给抽了出来”，而代之以“一中原则”的“九二共识”作为他在两岸间“搭桥铺路”的“建材”。

*** 看起来多少“有点幽默”，却真实地反映了“政治角力”的残酷性

东方时事评论员们认为，在没有了“宪法一中”这个障碍之后，大陆自然可以让宋楚瑜正式开始其“搭桥之旅”。在我们看来，自连战和“和平之旅”成功之后，宋楚瑜就开始宣传其“搭桥之旅”，只是在其计划中的“8天9夜”的行程中，却在经过了“7天8夜”之后的今天下午3：00，才正式开始其“搭桥之旅”。

在东方评论员看来，这看起来多少“有点幽默”，但却真实地反映了“政治角力”的残酷性。

*** 曾庆红昨晚的一句“重话”，彻底“点醒”了宋楚瑜

不过需要指出的是，准确地讲，就在今天早上，我们已经注意到，满面春风的台办主任陈云林的嘴中、就已经开始“闪烁”“搭桥”“两字”了。我们的判断是，看来，在昨天晚上、曾庆红在宴请宋楚瑜一行时，扔出来的“中华民国是49年以前的事，49后，是中华人民共和国”的这句“重话”，彻底打碎了陈水扁、宋楚瑜想以台湾是“中华民国”之“中国”，去混淆“大陆是中华人民共和国”之“中国”的迷梦，从而“点醒”了宋楚瑜，那就是，在“宪法一中”和“一个中国”之间，没有“两全其美”的好事。


下面，我们就来具体了解一下刚刚得到的、在“胡宋会”中产生的“会议公报”，之后，我们将开始“展开”今天的台湾部分。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 胡宋会达成六项共识提“两岸一中”新表述

【北京消息】中共中央总书记胡锦涛5月12日下午3点在人民大会堂会见宋楚瑜一行，随后双方进行了政治会谈。会谈结束后，亲民党政策中心主任张显耀当日下午在北京饭店召开记者会，公布了《会议公报》。

公报包括了在九二共识基础上，尽速恢复平等谈判等六大会谈共识成果。宋楚瑜表示，会议公报特别凸显海协会、海基会九二年会谈的各自表述内容，强调在两岸一中的基础上，相互尊重求同存异，尽速恢复两岸平等谈判。

亲民党宣布胡宋会六项共识

亲民党政策中心主任张显耀强调，亲民党主席宋楚瑜应中共中央总书记胡锦涛之邀，率领亲民党访问团正式访问大陆，也是两党首度进行的交流，别具意义。双方就两岸关系改善等重大问题，进行坦率的意见交流，双方也在会谈后做出会议公报，包括六项共识：

第一，促进在“九二共识”基础上，尽快恢复两岸平等谈判，1992年两岸达成的共识应受到尊重，1992年“两会”口头表述原文，海基会表述在海峡两岸共同谋求利益的同时，双方坚持“九二共识”“一个中国”的原则，但对“一个中国”的含义搁置不同，表示终遵守“一个中国”的原则，但在两岸涉及“国家”当中在前述均坚持“一个中国”的原则，即“九二共识”（两岸一中）的基础上，迅速恢复两岸和平谈判，解决两岸关系的重大议题。

第二，共同反对“台独”。“台独”主张伤害两岸情感，不利于发展两岸和平互利的关系，双方对任何推动“正名”“公投”“制宪”等破坏台海和平活动均坚决反对。希望台湾当局领导人切实履行2月24日重申的“四不一没有”的承诺。只要台湾没有朝向“台独”发展的任何可能性，将能有效避免台海军事冲突。

第三，推动结束两岸敌对状态，促进和平架构。建议建立两岸军事互信机制，共同维护台海和平与安全，确保两岸关系和平稳定发展。

第四，加强两岸经贸交流，促进建立稳定的两岸经贸合作机制。推动两岸实质性的经贸交流，在互惠合作的基础上开展两岸关系良性互动。包括积极推动两岸通航，促进两岸春节包机的成功模式，实行客运包机节日化、常态化，并逐步推动客运的便捷化。并逐步促成2006年开始全面直接双向直航。促进两岸直接贸易和直接通汇，进一步实现两岸关系经贸正常化。促进两岸协商后，建立两岸贸易便利和自由化（两岸自由贸易区）等长期稳定的相关机制问题进行磋商。加强两岸农业合作，扩大台商在农业领域的投资，增加台湾农产品在大陆的销售。

大陆方面提供通关、检验、检疫便利，和部分农产品（水果）零关税的优惠待遇，以协助解决台湾水果丰收及截止的销售问题。促进实现两岸企业的投资，推动两岸银行、保险、运输服务业的合作，建立稳定的经贸合作机制。促进两岸在互惠互利的基础上，协商解决台商投资权益的问题，商谈处理避免对台商双重课税的问题。

扩大两岸民间往来，为两岸交流提供便利，大陆方面进一步简化台湾同胞往来大陆的入处境手续，大陆方面要尽快实施在大陆就读的台湾学生与大陆学生同等收费标准，并争取于年内设立台湾地区的奖学金。

扩大两岸人才交流，大陆方面逐步放宽政策，鼓励和促进台湾同胞在大陆的就业。

第五，促进协商台商民众参与国际活动的问题。促进两岸平等协商后，讨论台湾民众参与的国际组织问题，包括优先讨论参与WHO的相关活动，双方求同存异，逐步找到解决的办法。

第六，推动两岸民间精英论坛，汇集两岸学者专家及各界的智慧经验，筹策两岸民间精英论坛。双方共同推动建立完善为台商服务的机制。

“两岸一中”最受关注

随后，宋楚瑜发表了讲话，宋楚瑜表示，在今天的公报里面特别提到，我们希望能够促进在过去建立的“九二共识”基础之上，希望尽速恢复两岸平等谈判，只有让两岸和平，才能够让亚太地区，所有邻近的国家，特别是两岸的人民享受到和平的果实。

宋楚瑜说，因此，在一开始的时候，我们都确认得到，在1992年，双方曾经就这个问题交换意见，与其不断地再去就所谓“标签”、“标题”这个问题在做这些喊话和相互的要去找一些文件，事实上很多文件只要找到它确实的内涵，明明白白的把它很明确的写出来，那就是在1992年“两会”曾经口头地表述这个原文，我们已经请我们的同事回头把这个公报的原文赠送给诸位。

宋楚瑜说，而海基会表述，在海峡两岸共同努力谋求国家统一的过程中，双方虽均坚持“一个中国”的原则，但对于“一个中国”的含义、认知各有不同，而海协会表述海峡两岸均坚持“一个中国”原则，努力谋求国家统一，但在两岸事务性商谈中不涉及“一个中国”的政治含义。这跟我们亲民党在我们台北所提出来的“和平法”，就是1992年，“国统会”所定的“一个中国”的原则的含义是完全符合的。

宋楚瑜表示，今天要特别向诸位提出的是这一段的文字在公报里面，就是在前述两岸各自表明均坚持“一个中国”的原则，这是第一次我们看到的跟大陆当局所明确的说明。各自表明均坚持“一个中国”的原则，而且还有一个我们特殊所提出来的一个名词，叫“两岸一中”，在这个基础上，尽速恢复两岸平等谈判，也就是强调“九二共识”的内涵，而希望相互尊重，求同存异，务实地来解决两岸共同关心的重大议题。


【时事点评】从“会议公报”的内容来看，在大陆的一系列“加压、促进”之下，宋楚瑜在最后关头、终于跨出了这一步，在我们看来，如果没有这个将“九二共识”文字化的“两岸一中”、宋楚瑜的这趟“大陆之行”不仅没有机会从“工作之旅”变回“搭桥之旅”、而且注定将成为“无为之旅”。

*** 巨大压力之下，走投无路的宋楚瑜，终于提前“兑现了”“行胜于言”的诺言

在之前的点评中，东方评论员曾经说过，如果宋楚瑜仍然心存幻想，“舍不得”那个给他披上“官方色彩”的“十点共识”、又想通过这次”搭桥之旅”、通过“仅仅承认”一个“已经被连战确认”的“九二共识”、就开始在“胡四点”与“十点共识”间“牵线搭桥”、从而取得“比率先承认九二共识的连战还要出色的访问成果”，首先在大陆这里就“过不去”。

在东方评论员看来，在最后关头、这位一度“鱼和熊掌”都欲兼得的宋楚瑜，在“除非取得重大突破”，不然就会来了不如不来”的巨大压力之下，终于在回到台湾之前、在北京就提前“兑现了”他在清华大学演讲中所说的“行胜于言”的诺言。



*** “两岸一中”是个“新东西”，较之“九二共识”，算得上是突破

坦率地讲，在两岸定位上，“两岸一中”是个“新东西”，较之“九二共识”，也算得上是突破，东方评论员认为，也正因有了这块“敲门砖”，胡锦涛主席也才在今天下午3：00鈡，才“正式许可”宋楚瑜做两岸“搭桥工程师”的。


*** “两岸一中”这个词，在汪道涵会见宋楚瑜时，就可以找到“源头”

事实上，“两岸一中”这个词，我们似乎听起来颇有印象。其实，如果我们细心一点，就可以在8日的汪道涵会见宋楚瑜时，就可以找到源头，当时，在陕西一落地，就已经被大陆“拔去”了“搭桥之旅”旗号的宋楚瑜、在“没有头绪”之中一飞到上海，就从汪道涵那里“着重地”听到了这么一句话，即：“大陆和台湾都是中国的领土、两岸同属一个中国”。

在东方评论员看来，尽管类似的表述，在“胡四点”和“反分裂国家法”中是到处都可以看到，但是，两岸之间共同提出这样明明白白的定义，这是头一次，值得注意的是，它还是在汪道涵见宋楚瑜时、当面就提出来的。


众所周知，从宋楚瑜数次强调“中华民国”，大陆官方就开始管制对宋楚瑜的相关报导了。这表现在其谈话不再现场直播，即便直播，也有记者以旁白“盖过”宋楚瑜的声音，让其声音“漠漠糊糊”。这些都意味着宋楚瑜的“大陆之行”的结果也进入了“漠漠糊糊”之中。

*** 宋楚瑜对自己“期望值”很高

事实上，宋楚瑜自五日出发访问大陆前，就对自己“期望值”很高。在东方评论员看来，宋楚瑜在“钻入”华盛顿安排的“扁宋会”之后，就一直有意揣着“夹杂”有“各方观点”的“十点共识”、以其一根“橙色领带”，意图通过“飘忽”于“蓝”、“绿”、北京与华盛顿之间，在台海局势的演变中穿针引线、扮演“要角”，只是想不到北京是“棋路一转”，拒绝他先行“登陆”，反而让国民党主席连战率先进京、从而一把剥去了宋楚瑜的“体面”。

显然，从整个过程来看，大陆的行棋步调非常顺畅，并全然达成了自己的目的。东方评论员认为，这表现在先用可帮助在台湾几近边缘化的国民党“摆脱困境”的一包包大礼，一举换得了陈水扁“发誓没有”的“九二共识”。

*** 让连战“白纸黑字”地承认“九二共识”不是目的，只是手段

其次，我们注意到，对大陆而言，让连战“白纸黑字”地承认“九二共识”、“一中原则”不是目的，只是手段，就阶段性的目标而言，让陈水扁承认“九二共识”、或者“一中原则”、只有这样才能瓦解“台独”政府的政治基础，这才是目的。


*** 借用了华盛顿、陈水扁事先“精心准备”的“道具”

不难看出，要做到这一点，大陆显然可以借用华盛顿、陈水扁事先“精心准备”的、意在让大陆既不好“全盘拒绝”、也不可能“全盘接受”的“道具”，也就是那个以“宪法一中”为前提的、包括有“大陆向来认可的观点、台湾社会一直渴求得到的内容”之“十点共识”。

事实上，在东方评论员看来，只要将“十点共识”的“第一点”、也就是“宪法一中”这根“独筋”给抽出来，并用“九二共识”或者“一中原则”去代替，那么，“胡四点”与“十点共识”之间“在许多点”上、是可以“搭桥画线”、从而用陈水扁提出的、并为台湾民众所认可的“十点共识”中的大部分内容、去堵陈水扁嘴、并抄台独的后路。

*** 关键的是，只要有可能，宋楚瑜显然是“非常愿意”去找机会实现自己的“主角梦”的

显然，“这个工作”仅靠连战和国民党是做不到的，然而，一直对当连战的配角不甘心、反身又掉进陈水扁“十点共识”中的宋楚瑜、却可以很好地起到这样的作用，在东方评论员看来，最关键的是，只要有可能，宋楚瑜显然是“非常愿意”去找机会实现自己的“主角梦”的。


*** 给了大陆有条件让宋楚瑜感受一番“高处不胜寒”的“客观条件”

我们注意到，尽管失去头彩、但是，宋楚瑜对自己重新得到“主角定位”还是极有信心的，他不同于连战出访前的低调、而是以一种“高调”的方式开始大陆之行的。这里有两个事就非常有代表性：

第一，率先登陆的连战、在行前是概不接受媒体采访，而这位“第二位”登陆的宋楚瑜、则是在台北大张旗鼓地“亲自”举行中外记者会，宣传他“搭桥之旅”的目的，并“重申”亲民党的“两岸政策”。

第二，他仍然不断以“扁宋十点共识”拉抬自己的身价，并以此宣传“他的大陆之行、将比连战更具代表性”，这些，这一方面引起大陆的警惕，二方面，也给了大陆有条件让他感受一番“高处不胜寒”的“客观条件”。


*** 掉进了大陆为他准备的、意在烘烤他的“火坑”里

显然，早在汪道涵先生那里，宋楚瑜就应该已经听出来了，在“已经手握”连战承认“九二共识”的情况下，大陆对宋楚瑜的“期望值”也很高，也就是说、在两岸关系的定位上，宋楚瑜如果只是“单纯的重复”“九二共识”、不要说现在的中共领导人，就是当时的这位谈成“九二共识”的这位老人“都觉得没有意思”。

如此一来，宋楚瑜已经明白了自己的处境，那就是他还没有从华盛顿、陈水扁“淹渍”他的“水坑”中爬出来，就又掉进了大陆为他准备的、意在烘烤他的“火坑”里。

可以说，自那之后、宋楚瑜的“大陆之行”就立显“气氛凝结，步步为营”，不难看出，“两岸一中”这个“新名词”，不是宋楚瑜“想出来”的，而是大陆“指出来”。


在我们继续我们的讨论之前，我们先看看我们刚刚收到的、中国国民党方面的“初步反应”。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 国民党:“两岸一中”有待和亲民党“问清楚”

【台湾消息】据中央社台北十二日电，中国国民党发言人张荣恭表示，九二共识在国民党的观点是“一中各表”，亲民党主席宋楚瑜在中国大陆、刚才提出的“两岸一中”并没有否定“一中各表”，宋楚瑜的说法，到底让台湾的空间更大或更小，有待亲民党进一步阐述。

张荣恭在国民党中央召开记者会表示，国民党认为，一中各表是两岸基于各自法律文件对一个中国做出各自表示；中国大陆的说法叫各自表述一个中国原则，也称各表一中，宋楚瑜提的两岸一中，到底“一中”是什么意涵，如果“一中”是各表，就和国民党的主张没有什么不同。

张荣恭说，国民党一贯的主张就是以九二共识做为两岸会谈的基础，今天得到宋胡两人的再次确认。中国国民党与中国共产党共同发布的新闻公报中，两党党名并列，就是具体落实一中各表的作法。

他说，中国国民党当然是中华民国的国民党，而中国共产党是中华人民共和国的共产党，两党党名并列，实际上就是对中国两字有不同意涵，这就是两党以具体行动落实一中各表与九二共识的内涵，希望两岸以此基础推动协商。


【时事点评】显然，“两岸一中”这个“新名词”似乎带来了新问题。在东方评论员看来，这个“新问题”的出现非常“耐人寻味”。请大家注意上面新闻的这么一段：张荣恭说，中国国民党当然是中华民国的国民党，而中国共产党是中华人民共和国的共产党，两党党名并列，实际上就是对中国两字有不同意涵，这就是两党以具体行动落实一中各表与九二共识的内涵，希望两岸以此基础推动协商。

*** 国民党的“疑问”，汪道涵早就回答了

非常清楚，如果按国民党的“疑问”去思考的是话，那么，很显然，在汪道涵先生会见宋楚瑜的时候，早就回答了这个问题，汪道涵的原话是“大陆和台湾都是中国的领土、两岸同属一个中国”。

当然，如果国民党认为北京太远，不好理解，那么，台湾民进党政府的话应该好懂，我们注意到，陈水扁手下的一位官员表示，所谓“两岸一中”，只是“一中原则三段论（世界上只有一个中国，大陆和台湾同属一个中国，中国的主权和领土完整不容分割。）”的另一形式包装，并无新意。这种主张“已逾越扁宋会十点共识”。

*** 国民党在这里“质疑”的本身，是在“得了便宜还卖乖”


对此，首席评论员就指出，国民党在这里“质疑”的本身，是在“得了便宜还卖乖”，这就是说，连战尽管在大陆是“大获成功”，但是，其“九二共识”的成果、在大陆迫使宋楚瑜拿出“两岸一中”这个“更好”的“新名词”之后，“九二共识”已然不能与“两岸一中”这个对“两岸关系”定义得“更加具体的”“新名词”相提并论的了。

如此一来，国民党于第一时间内抓住“两岸一中”做文章，将其与“九二共识”比起来更不为台湾民意“所喜欢”的“两岸一中”、去“硬性地”与自己的“九二共识”相区别，也就不为奇怪了，我们知道，台湾正面临着一连串的选举。


*** 到这一步，大陆“下好连宋这两颗棋子”的计划可以说是大获成功

在东方评论员看来，到这一步，大陆“下好连宋这两颗棋子”的计划可以说是大获成功。我们认为，如果按汪道涵的原话去解读“两岸一中”这个名词，当然是一点问题都没有，这就是“胡四点”中的核心内容，更是“反分裂国家法”对“两岸现状”的“精确界定”。

然而，“巧就巧在”国民党却偏偏“不理解”，这就是说，到底是“九二共识”好、还是“两岸一中”好，还是“九二共识”、“两岸一中”都不好、在大陆方面已经有自己明确的“定义”之后，这个问题已经被大陆“扔到了”台湾，你们自己去商量好了，反正对大陆而言，就两个字：“九二共识”和“两岸一中”“都行”，当然，如果陈水扁都不要也行，那就意味着他是“台海和平”的阻碍者，台湾社会如何选择，华盛顿如何动作，与大陆无关，只是最终的选择的结果、大陆都有必要比照着“反分裂国家法”一条条地“落实”就行。

需要强调一点的是，比起陈水扁、比起华盛顿来，北京对台海、以到朝核问题紧张局势的态度，显得“超然得多”。


*** 大陆这一套组合拳下来，起码已让连战和宋楚瑜之间“别起了苗头”

在我们看来，以“一个中国”为基础的“九二共识”和“两岸一中”的说法，不是个什么哪个“会”“最好”的问题、而是“哪个”“会”“更好”的问题，东方评论员认为，大陆这一套组合拳下来，起码在已经让连战、国民党和宋楚瑜、亲民党之间“别起了苗头”，至于陈水扁什么时候参加进来，那就得走着瞧了。

东方评论员认为，在宋楚瑜从“十点共识”中抽出“客法一中”之后，陈水扁加入进来的速度是只会快，不会慢。


*** 对大陆而言，只要能促进“两岸向实质性三通”方向靠近，任何事情都是值得“鼓掌”的


值得强调的是，这还只是个“虚”的东西，大家还只能在嘴巴上“别苗头”，如果具体到有关“两岸三通”这些实际的层面后，我们相信，两者之间的“任何别苗头、旨在讨好台湾商界、台湾民意的实际动作”，都会让台湾社会“点滴在心”。

对大陆而言，只要能促进“两岸向实质性三通”方向靠近，任何事情都是值得“鼓掌”的。


*** 宋楚瑜哪有半点陈水扁“特使”的味道，反而更像是胡锦涛的“特使”

我们注意到，宋楚瑜在发表“会谈公报”后的答记者问中，有一个有趣的一幕：当时，一个记者问，是否为陈水扁带话？是否会有“胡扁会”时？宋楚瑜先是回答说：他不代表任何人和政府，只代表他个人和亲民党。然而，他又说，就象刚才和胡总书记会谈时，胡总书记所说的：只要承认“九二共识”和“那个”基础，就欢迎台湾任何人、任何政党，不管过去说了什么、做了什么，都可以谈，并以此来做对“是否有'胡扁会'”这个问题的回答。

在我们看来，好个宋楚瑜，在豁出去提出“两岸一中”之后，竟然全然不顾“扁宋会”的存在、尽管他仍然对说出“一中原则”不自在、而心人“那个基础”加以替代，但是，他的口气和言语，哪有半点陈水扁特使的味道，反而更像是胡锦涛的“特使”，坐在北京、一板一眼地向陈水扁“喊起话”来。东方评论员认为，看着宋楚瑜坐在台上、冲着陈水扁“背诵胡锦涛语录”的样子，简值就与宣传“交枪不杀，共军优待俘虏”的画面没有两样。


*** 大陆送给宋楚瑜的“最大的一个礼包”


事实上，宋楚瑜“当上了”胡锦涛的“特使”，其好处也是不小的。请大家看看“会议公报”的第二条：

原文是：共同反对“台独”。“台独”主张伤害两岸情感，不利于发展两岸和平互利的关系，双方对任何推动“正名”“公投”“制宪”等破坏台海和平活动均坚决反对。希望台湾当局领导人切实履行2月24日重申的“四不一没有”的承诺。只要台湾没有朝向“台独”发展的任何可能性，将能有效避免台海军事冲突。

在东方评论员看来，在这一条中，前面是大陆要的，而后面的一句“只要台湾没有朝向“台独”发展的任何可能性，将能有效避免台海军事冲突”，可以说大陆送给宋楚瑜的“最大的一个礼包”。

事实上，站在大陆的角度，东方评论员“不愿意”去详细解读它，就让它尽可能地模糊好了，这从大陆不愿意在“会议公报”明确其意义就可见而之。


*** 宋楚瑜回台湾后“恨不得立刻就装裱起来“的几个字

然而，如果从宋楚瑜的角度去看，这就是“不独不武”。东方评论员认为，如果不出意料的话，这个“不独不武”将是宋楚瑜回台湾后“恨不得立刻就装裱起来、亲自挂在亲民党中央党部大楼”前的“几个字”。

在昨天的《东方时事解读》中，我们的台湾部分点评是以宋楚瑜的那份“演讲稿”为主线进行展开的。在我们看来，宋楚瑜在昨天的演讲中大谈“台湾意识”的本身，就是在为所谓的旨在“维持现状”的、“中间路线”进行张目。

*** 专治“台湾意识”中“惧战”这一“病症”的“特效药”

显然，在东方评论员看来，“台湾意识”的确是台湾的主流民意，其核心就是两点：第一是惧战、第二是反统。不难看出，宋楚瑜在大陆献出了“两岸一中”这个“秘方”之后，当然不对“台湾意识”中“反统”这一症状。然而，值得强调的是，他从大陆带回的“不独不武”的这个“药方”，却是专治“台湾意识”中“惧战”这一“病症”的“特效药”，这比连战回去的“建立两岸军事互信”的提法，要“有效得多”。

*** 如此这般明确了“这种意向”，也有种“权宜之计”的意味在其中

有消息说，连战不是傻瓜，当然也想要这个“不独不武”，只是北京没有给，显然是在吊宋楚瑜的胃口，更是有意留着给这位身带“十点共识”的陈水扁“特使”、好去对台湾民众喊话用的。

事实上，“不独不武”正是“反分裂国家法”的立法宗旨，只是“反分裂国家法”经台独政府控制下的“台湾的媒体”一描写，显得好恐怖、说出来让“台湾民众不爱听”，那么，大陆也就用这种方式，委托宋楚瑜、亲民党回去用“不独不武”这“朗朗上口”的几个字，去“代为宣传好了”。

在东方评论员看来，由于国家现在“对台政策”的主要目的是“止独”、之后才是“促统”，如此这般明确了“这种意向”，虽然是为了更好地下好宋楚瑜这颗棋子，但也有种“权宜之计”的意味在其中。

在一段来自华盛顿的消息之后，东方评论员将继续就台海的“不独不武”与华盛顿、陈水扁在“两岸政策”取向之间的“关联度”、给出一个综合的分析。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
