# -*- org -*-

# Time-stamp: <2011-08-04 00:35:12 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 2005年6月28日 星期二



** 6月28日外交部发言人刘建超在例行记者会上答记者问

【外交部网站消息】6月28日下午，外交部发言人刘建超主持例行记者会，下面是有关中日关系部分的节简内容。

问：日本各大报今天报道说，日外务省高官27日在答记者问时称，关于广州日本遗弃化武伤人事件，日方希望加快处理进程，但中方应对缓慢。中方对此有何评论？

答：我们注意到了日本新闻媒体所作的有关报道。中方已就报道中所提及的日本外务省的官员就处理在华遗弃化武问题的表态向日方提出交涉，并要求日方作出澄清。

我要指出的是，日本遗弃化武是日本军国主义侵华期间犯下的严重罪行之一，至今仍然对中国有关地区人民生命财产和生态环境安全构成重大的、现实的威胁。此次在广州发生的日本遗弃化武伤人事件再次说明了这一事实。日本政府理应严格遵循《禁止化学武器公约》和《中日两国政府关于销毁中国境内日本遗弃化学武器的备忘录》，切实承担起销毁日本遗弃化武的责任，尽早彻底干净地销毁日本遗弃化武。

中国政府始终高度重视处理日本遗弃化武问题，并为加快处理进程作出了切实的积极努力。现在应该是日方采取切实行动，多做有利于推动处理日本遗弃化武进程的事情。

问：前不久，大连海关扣押了大连日本人学校从日本寄来的一部分教材。据了解，扣押的理由是，在这部分教材中，地图上中国大陆的颜色与台湾的颜色不一。这违反了中国什么法律？中方今后将如何处理？一般而言，中方对外国人学校的教材持何态度？是否都必须与中国政府政策和看法一致？

答：你提的问题非常具体，你的其他同事未必了解有关情况的背景。我向大家介绍一下事情的经过。今年4月12日，大连日本人学校从大连机场空运进口了1539册教材，大连海关于4月15日放行了其中1411册，暂时扣留了128册。经海关查验，发现其中15册地理教科书中的地图将中国大陆和台湾标注为两种不同颜色。我们认为，这违反了中国的《出版管理条例》和《中华人民共和国海关对个人携带和邮寄印刷品及音像制品进出境管理规定》。海关将依据《中华人民共和国海关法》和《中华人民共和国海关行政处罚实施条例》的有关规定，对上述15册地理教科书做退运处理。中方今后将会依照法律对此类问题进行处理。

关于外国学校教材是否要与中国持同样的观点，在这个问题上应区分不同层次，不同内容。总之，有关物品入关问题要依法处理。在大连发生的问题涉及中国主权和一个中国原则，也涉及中国人民的感情，是个原则问题。中国的海关依照有关法律进行处理是完全有法律依据的。


问：最近日本明仁天皇祭奠了塞班岛的二战日本阵亡士兵，并且祭奠了那里的韩国阵亡士兵。中国是将此举动看作日方促进关系的积极表态还是仍然专注于日本首相小泉参拜靖国神社的问题？

答：我们注意到了有关的报道。我们认为有关安排应该基于对历史问题的正确认识，应该基于对历史问题负责任的态度，日方应重视包括中国在内的亚洲国家人民的感情，妥善处理好有关问题，恪守在历史问题上所作出的有关反省历史、尊重历史事实的承诺。




【时事点评】在昨天的点评中，我们曾经说过，人民日报27日刊发的《"大东亚共荣圈"的欺骗性》这篇评论，之所以要安排在日本天皇夫妻登上“美国管理着的”塞班岛的当天刊发，一个重要原因应该是北京有意向日本社会展现出的“强硬态度”、是为新一轮“敲打日本”发出的信号。

*** 仅隔了一天，就传出了中国扣留并要“退回”日本学校“有问题”教科书的消息

有意思的是，仅仅隔了一天，也就是今天，就传出了中国大连海关扣留、并要“退回”日本学校“有问题”教科书的消息。下面，我们就先通过一则新闻报道了解一下相关过程，之后，时事评论员将对此进行展开。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 中国大连海关扣留并没收日本学校辅助教材

【综合消息】据韩国联合通讯社报道，中国大连海关认为在华日本学校从日本订购的辅助教材有问题，将其扣留了一段时间，并没收其中的一部分。

据日本媒体２８日报道，日前，大连海关扣留了日本学校从本国订购的共１０种１２８件辅助教材，包括小学生用《社会》、中学生用《历史》、《地理》、《公民》等８种习题集、资料集和两种ＣＤ。

部分辅助教材在地图中将中国和台湾标记为不同颜色，使用“台湾政府”用词等将台湾标记为独立国家，并把中国视为本国领土的钓鱼岛（日本称尖阁列岛）标记为日本领土。

这些辅助教材由于违反“一个中国”原则而抵触中国国内法，因此被没收。

大连海关起初拒绝日本学校方面返还被扣留辅助教材的要求，经校方交罚款人民币１０００元和提交事件经过报告书之后，返还了教科书。但是没收了其中含有把尖阁列岛标记为日本领土的地图的１０多件辅助教材。

日本学校的批准成立是以遵守中国法律为前提条件，因此法律上不能拒绝中国对教材的检查。


目前，还没有迹象表明中国中央政府介入此事。但是，鉴于最近中日两国围绕历史遗留问题等的矛盾，日本方面担心中国当局对教科书也进行海关检查。


【时事点评】我们注意到，被中国大连海关查扣的辅助教材、被称之为“双色教科书”、即在地图中将中国和台湾标记为不同颜色，使用“台湾政府”用词等将台湾标记为独立国家，另外，还把中国视为本国领土的钓鱼岛（日本称尖阁列岛）标记为日本领土。


*** 日本国内的种种反应“非常耐人寻味”

显然，在东方评论员看来，按中国法律规定，“有这些毛病”的地理教科书，当然是“有问题”的，按照中国的相关法律，将15册这样的地理教科书做“退运处理”、自然也是“以事实为依据，以法律为准绳”。

在东方评论员看来，倒是日本国内的种种反应“非常耐人寻味”，可以说是“参差不齐”。东方评论员注意到，日本官房长官细田博之在今天下午刚刚举行的记者招待会上，就显得“非常低调”，记者会上，他不仅低调地称“将进行调查”，还对中国“扣留”的合理性，表现出了某种程度的“理解”，并以例举的方式表示，“即使在日本，有时因有些不恰当的照片或内容判断“不行”，并被海关没收的事例也是有的”


*** 这件事情本身就是日本媒体最先“捅出去的”

我们认为，日本官房长官细田博之对中国“扣留”表示出的“某种程度的理解”，那是日本人自己的事、因为这件事情本身就是日本媒体最先“捅出去的”，我们注意到，根据刘建超的“详细介绍”，事情并非发生在眼前，而是发生在今年4月12日，当时、大连日本人学校从大连机场空运进口了1539册教材，大连海关于4月15日放行了其中1411册，暂时扣留了128册。

大家应该记得，4月12日到15日间，中日正因日本准备向日本企业发放勘测东海资源许可证一事吵得不可开交，中国还以极其严厉的态度警告日本“不得妄动”。显然，在当时的情况下，中国政府突然“拿这几本有问题、且恰恰是在关中日东海、钓鱼岛主权争端的教科书说事”，分明是在“以具体行动”警告日本。


*** 北京在这个时候挑出“15本”来“退回”日本，这根本就是在“没事找事”

然而，按时间上看，事情已经过去两个多月了，期间，日本方面也一直没有说什么。但是，这几天中日之间又发生了一系列的问题：小泉叫嚣将“继续参拜靖国神社”，日本天皇夫妇去海外“招魂”，中国《人民日报》发表评论揭露日本想通过“大东亚共荣圈”称霸世界的野心，再就是中国要“退回”“那15本有问题的地理教科书”。

显然，东方评论员认为，从刘建超的“详细介绍”中不能看出，“这15本书”应该属于两个月前被扣、实际上“没收了”的那一批，总共是128册。明眼人是一眼都看得出，北京在这个时候“又挑出”“15本”来“退回”日本，这根本就是“没事儿找事儿”。


*** “退运处理”的目的、恐怕与当初的行动一样“不简单”


由此可见，今天，在中日关系又处于关键的时刻，特别是日本保守势力这次是存心要钻“虽然日本天皇裕仁是战争罪犯、但却又没有被正式审判定罪”的空子来挑衅中国和亚洲国家：显然，日本让“应该是战争罪犯、却又没有被国际法定罪”的日本天皇裕仁的儿子、在二战结束60年后、以已经没有了任何权力的日本天皇身份去塞班“招魂”，倒真的让北京“不好明确地说什么”。

因此，东方评论员认为，中国政府在这个时候“硬是”要将早已经扣下两个月之久的、“15册”有问题的日本地理教科书做“退运处理”、其目的、恐怕与当初的行动一样“不简单”，除了继续“用同一批教科书对日本进行同一性质的警告”之外，也是存心在让日本政府“也说不出什么来”。


*** 日本“官方的低调”是“虚”，日本“媒体的高调”才是“实”

前面说了，这次日本官方比较低调，倒是日本媒体在一马当先、意图为小泉政府贴上“顾全大局”的标签。在东方评论员看来，小泉因中日关系陷入僵局、而在靖国神社的问题上、受到国内民意的强大的压力，因此，在我们看来，小泉在这个时候来这一手，是在企图通过“自拉自唱”、在那里“以攻为守”。

显然，日本“官方的低调”是“虚”，日本“媒体的高调”才是“实”。而日本媒体又是如何“唱高调”的呢？东方评论员注意到，日本共同社就认为，“日本政府没有向中国政府提出抗议而显出谨慎的姿态，原因可能是为了改善中日关系，尽量避免制造风波”。

非常清楚，一件违反中国法律的事情、中国不过是在“按法律条文进行正常处理”，日本政府本就无权提出什么抗议，倒是经日本媒体这样一渲染，竟然成了日本政府在“尽量避免制造风波”、是日本人“为了改善中日关系”。


*** 日本的另外一个“不可告人的阴谋”

但是，日本政府是在尽量避免制造风波吗？小泉纯一郎是在做有利于改善中日关系的事情吗？在东方评论员看来，小泉纯一郎近来对北京挑衅可谓是“多多”，自从韩国回去之后，他就立刻扬言要继续参拜靖国神社；再就是，将他的天皇夫妻送到了塞斑岛、公然在海外为日本军国主义招魂，这是为了改善中日关系吗？

另外，首席评论员指出，在今天的记者会上，刘建超回答了第一个问题，可以说可以非常清楚地反应了日本的另外一个“不可告人的阴谋”。

请大家注意这么一段，问题是：

问：日本各大报今天报道说，日外务省高官27日在答记者问时称，关于广州日本遗弃化武伤人事件，日方希望加快处理进程，但中方应对缓慢。中方对此有何评论？

在东方评论员看来，对这一段文字，我们想强调的是，非常清楚，日本人谈的这次“广州日本遗弃化武伤人事件”，而不是“其他”，“日方希望加快处理进程”的，是指的这次事件而言的，也不是“其他”。

*** 日本对待销毁在中国境内遗弃化学武器的“真实态度”

因此，我们也就不难看清，日本高官所声称的“日方希望加快处理进程”，只是“广州日本遗弃化武伤人事件”，而日本高官指责“中方应对缓慢”、也只是针对“广州日本遗弃化武伤人事件”。

然而，日本遗弃化武伤人事件、绝不是只有广州这一处。众所周知，在日本侵华期间，日军在中国遗留了大量化学弹药。但日本在战后一直否认研制和遗弃了化学武器，直至1991年日本迫于事实和国际压力、才第一次正式地承认这一问题，并在99年7月30日，中日才签署了《关于销毁中国境内遗弃化学武器的备忘录》，规定日本遗弃在中国的化学武器，必须在2007年4月前彻底销毁完毕。

不难看出，现在已经是2005年6月底了，距离“日本必须在2007年4月前彻底销毁完毕”的时间只有两年不到的时间，然而，据了解，日本除了在吉林省进行了一些勘测和调查活动之外，根本就没有其他的实质性动作，在“应该建设什么样的挖掘”、如何回收毒气弹、建什么样的大规模设施加以处理，等问题上，日本到现在为止，根本就没有提出一个具体计划，这就是日本对待销毁在中国境内遗弃化学武器的“真实态度”。


*** 有了日本“铭记中日联合声明和中日和平友好条约的原则和精神”这一前提，才有了“备忘录”本身

显然，了解了这些事实之后，我们再来看外交部发言人刘建超对该问题的回答，原文是：

答：我们注意到了日本新闻媒体所作的有关报道。中方已就报道中所提及的日本外务省的官员就处理在华遗弃化武问题的表态向日方提出交涉，并要求日方作出澄清。我要指出的是，日本遗弃化武是日本军国主义侵华期间犯下的严重罪行之一，至今仍然对中国有关地区人民生命财产和生态环境安全构成重大的、现实的威胁。此次在广州发生的日本遗弃化武伤人事件再次说明了这一事实。日本政府理应严格遵循《禁止化学武器公约》和《中日两国政府关于销毁中国境内日本遗弃化学武器的备忘录》，切实承担起销毁日本遗弃化武的责任，尽早彻底干净地销毁日本遗弃化武。

在东方评论员看来，北京的态度，已经由刘建超说得非常清楚了，那就是，“日本政府理应严格遵循《禁止化学武器公约》和《中日两国政府关于销毁中国境内日本遗弃化学武器的备忘录》，切实承担起销毁日本遗弃化武的责任，尽早彻底干净地销毁日本遗弃化武”。

在这里，我们有必要强调一点，那就是，中日在正式签署《关于销毁中国境内日本遗弃化学武器的备忘录》的时候，日方就在“备忘录”中明确表示“铭记中日联合声明和中日和平友好条约的原则和精神”，“承认在中国遗弃了化学武器，承诺将根据《禁止化学武器公约》诚实履行作为遗弃缔约国应承担的义务”。

显然，在东方评论员看来，正是有了日本“铭记中日联合声明和中日和平友好条约的原则和精神”这一前提，才有了“备忘录”本身，也才有了一套可以依据的“化学武器处理流程”，然而，不论是“中日联合声明”、还是“中日和平友好条约”，其原则和精神早已经被“小泉参拜靖国神社”、日本高官“否认侵略历史”，日本将台海纳入“美日安保指针”这一系列动作“给践踏了”。


*** 中日双方都“心里有数”的“原则问题”

因此，在“前提条件”已经没有了的情况下，北京当然有理由不让日本按“原来的流程”加以处理，在东方评论员看来，这看起来虽然只是一个细节，但却是个原则问题，在这一点上，中日双方都是“心里有数”。


*** 中日双方在“这种问题上”的最近一次较量

事实上，中日双方在“这种问题上”的最近一次较量，是不久前。我们知道，日本《日本经济新闻》本月6日，在头版报道说：“日中两国政府商定，为了建设对侵华日军遗留在中国境内的化学武器进行挖掘、回收和废弃处理的大规模设施，日本政府决定拨款2,000亿日圆以上作为建设费用”。

此消息一出，东方评论员就注意到，而日本政府并没有在第一时间内“进行肯定”，北京“也不吭气”，而日本在拖了几天的时间后，才加以“否认”的，并声称该报道“完全失实”。

有意思的是，《日本经济新闻》东京总社的负责人，却明确地表示：“这条新闻登在6月6日的头版，目前我们尚未收到任何来自内阁的撤稿通知，可以明确地说，我们的报道是没有任何问题的。至于新闻来源我们不便透露，也许是来自政府的官员。”

在东方评论员看来，在日本国内被称为“踏入社会的人的必读报纸”的《日本经济新闻》，本身是日本五大报之一、是发行量有300多万份的全国发行的综合大报，我们认为，该报负责人明确反驳日本政府官员的说法、并声称“报道没有任何问题”，“有确切的消息来源”，这又说明了什么呢？


*** 小泉“耍手段”，将“备忘录”规定的一个“早就应该做的事情”“做成球”、并抛给北京


对此，当时就有国际问题分析人士指出，小泉政府这不过是在“耍手段”，其目的是通过媒体放风，试探北京的反应：既，在小泉有心突破历史问题的紧要关头，如果北京愿意受日本按“备忘录”去处理日军遗留化学武器的问题，那么，实际上也就会被视为中国接受了“中日关系”的“现状”。

显然，“该消息”的出台，是在北京以中断吴仪访日行程、切断中日高层一切对话、对中日双方都非常重要的中日关系“处于几十年来最糟糕”的情况下，受到内外巨大压力的小泉政府、想通过拿一个日本根据上述“备忘录”规定“早就应该做的事情”、将其“做成球”、并抛给北京，看看中国有何反应。


*** 北京采取了“根本就不接球”的策略、于无形中化解了日本人的这一阴招

对此，首席评论员曾经特别指出，小泉玩的这一套，这就有如陈水扁抛出“一边一国论”、却又渴望与大陆展开有关“两岸三通”的谈判是“如出一辙”，大家都知道，在陈水扁拒不承认“一中原则”、或者“九二共识”的情况下，如果大陆答应了“两岸三通”谈判，那么，其后果不仅仅表现为大陆自毁“一中原则”、更将被“台独”拿去、“发挥为”是在为陈水扁的“一边一国论”“背书”、最后，不仅“两岸三通”将是“竹蓝子打水”、还有可能刺激“台独”挺而走险，继续在“台独”的路上做出更激烈的举动来。

经此一对比，东方评论员认为，在日本《日本经济新闻》本月6日抛出该消息之后，对日本政府的“不置对否”、中国政府在一开始也是“不置一评”，这显然是看清了小泉政府的小算盘：即，想用“处理日军遗留化学武器的问题”换取“中日关系仍然处于可以合作的层次”的事实，从而为他后来所提出的“靖国神社问题不是中日、中韩关系的核心问题”这类似的论调“准备事实根据”。

从而，在我们看来，中国决策层却采取了“根本就不接球”的策略、于无形中就化解了日本人的这一阴招。


*** 中国又怎么可能让日本这一心思得逞！

在我们看来，到了这次“广州日本遗弃化武伤人事件”，我们不难再次看到日本人这一心态的“彰显”，东方评论员认为，日本高官所声称的“日方希望加快处理进程”，这倒虽符合事实，但日本人所指责的“中方应对缓慢”、可能就是在“不问前提”了，在东方评论员看来，日本人这次急急忙忙地承认“伤人的”的确是日本遗弃化武，并想“尽快处理”，显然是小泉政府在已经完全违背了“铭记中日联合声明和中日和平友好条约的原则和精神”这一前提的的情况下，却企图按原来的相对有利日本、照顾到日本利益的“备忘录”做成一个“典型案例”、以供今后“引用”、而中国又怎么可能让日本这一心思得逞！

在东方评论员看来，就如我们在之前的《东方时事解读》中所说的那样，小泉纯一郎这几天的“上窜下跳”，可以说是其“最后一搏”了，因此，在与小泉政府的角力中，北京在继续对小泉施加压力的同时，只要继续将主要精力盯在日本背后的华盛顿身上，通过朝核问题、“继续放大”“美日韩”的战略矛盾，继续削弱“美日韩”军事同盟，并在关键的时候，不惜以强硬的手段、配合“风险已经在积聚”的欧美经济、有目的的打击一下正在复苏的日本经济，给日本一个教训，那么，日本社会还是“有可能”做出积极的反应的。

在一段有关日本生化技术的新闻后，东方时事评论员、军事评论员将一起进行共同讨论，看看日本今天的化学武器的实力如何，并从生化武器的角度、去分析美日间的“相互警惕”。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
