# -*- org -*-

# Time-stamp: <2011-08-02 20:37:25 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

#+STARTUP: indent

* 2005年4月19日  星期二

在昨天的点评中，我们曾经说过，小泉纯一郎让町村信孝带来的“新想法”，即想以“取消21、22日前往靖国神社参拜的春祭活动”、来争取“打开中日首脑互访”的僵局。

东方评论员仍然认为，单纯地就小泉的这个“表态”而言，的确算得上是个“积极的信号”，然而,对于小泉的“表态”“是否最终言而有信”，在昨天我们就不想多谈，今天我们同样不想多谈，因为在东方评论员看来，最大的可能性就是我们在昨天点评中所说的那样：事情是不会就“这么简单就一步到位的”。

也许正是基于这种事实，在日本外相离开北京的前后，中国政府透过各种方式表示出了“将信将疑”的态度，而外交部发言人显然也是在那里“话中有话”，下面，我们就先一起来看看外交部发言人的相关讲话，之后，我们将给出自己的观点。


** 外交部:希望中日“相向而行”不是“背道而驰”

【北京消息】新华社北京４月１９日电（记者李诗佳李萱娜）外交部发言人秦刚１９日在记者会上表示，中方对发展中日关系有诚意，也希望日方表现出同样的诚意，特别是在历史和台湾问题上。双方应该“相向而行”，而不是“背道而驰”。

他说，此次日本外相町村信孝访华期间，不论在与唐家璇国务委员会见时，还是与李肇星外长会谈时，双方都就当前中日关系坦诚交换了意见，中方表明了发展中日关系的看法和立场，也提出了存在的问题。双方有一些共识，都认为应该从长远和战略角度看待中日关系。中方也强调要本着“以史为鉴，面向未来”的原则，町村信孝也做了同样表态。

秦刚说，町村表示日本在近代历史上对中国的侵略给中国人民造成了巨大伤害，对此深感痛心，再次表示深刻反省和道歉。日方愿深刻汲取历史教训，继续走和平发展道路。关于台湾问题，町村重申，日本坚持一个中国原则，不支持“两个中国”、“一中一台”，不支持“台独”。

这位发言人说，中日在经贸等领域的合作是互利互惠的，符合双方的利益，我们不希望合作受到影响。中国政府一贯高度重视发展中日友好合作关系，希望按照中日三个政治文件的原则，与日方和平共处，世代友好，共同发展。




【时事点评】我们注意到，秦刚在记者会上表示：“中方对发展中日关系有诚意，也希望日方表现出同样的诚意，特别是在历史和台湾问题上”。显然，在东方评论员的眼里，秦刚的这么平平常常的一句话，其实点出了两个要点，那就是要对日本政府在“历史问题上、台湾问题上”“听其言、观其行”。

然而，东方评论员注意到、就在中国政府正式拒绝为反日示威中的部分过激事件进行道歉后，日本国内立刻对中国发起了新一波的猛烈抨击，甚至一些国会议员还宣布将会继续参拜靖国神社。

特别值得注意的、就是那个刚刚表态有意暂时不去参拜靖国神社的小泉纯一郎、也立刻在记者会上辩解说，他参拜靖国神社“只是为了保证不再有战争，也是对战争的死难者表示哀悼”。

*** 日本外相町村信孝的北京之行没有实现某种“险恶目的”

显然，日本外相町村信孝“挟带着”驻华使馆遭袭的“天大委曲”、而端着一副气势汹汹架式的北京之行，在北京却没有讨到半点便宜，更没有达到想通过让中国为反对日本篡改历史进行游行示威的过程中的部分“过激行为”进行道歉、而实现某种“险恶目的”，另外，中国政府还对与小泉纯一郎几天后在印尼会面的事情“不置可否”，如此一来，可以说带着小泉纯一郎亲笔信到北京的日本外相，离开北京时，没有取得任何重大成果。

值得强调的是，对于道歉的问题，我们注意到，中国副外长武大伟就说，谁对谁道歉，应该是看谁制造了现在的困难局面，现在的中日关系的困难局面是日方造成的，中方没有任何必要向日方道歉。

*** 日本在这里面又“耍起了小聪明”

在东方评论员看来，日本之所以如此强调中国要道歉，而中国却反而要日本政府道歉，就在于日本在这里面又“耍起了小聪明”。显然，眼眼人是一看就知，日本就是为了达到通过中国政府的道歉、去间接否定中国民众为了反对日本篡改历史、反对日本侵犯中国主权而进行的游行之“正义性质”，从而为日本篡改历史的恶行进行“间接背书”的目的。

在这里，我们先来说说“历史问题”。东方评论员认为，只要我们稍稍注意一下，就不难发现，中国领导人在任何公开场合谈及中日关系时，无不把“历史问题”放在首位，事实上，这个“历史问题”之所以如此重要，就在于它将决定日本政治外交将来的走向，从而确定日本最终是“有助于”亚洲一体化、还是去破坏亚洲一体化的关键之所在。


*** 日本人玩这一套东西的时候，有太多的事情证明这不过是日本的一厢情愿


也正是如此，小泉政府尽管心知“一个良好的中日关系”是自己与美国人“打交道”时“最好的筹码”，但是，因自身经济长期不振、出于对中国快速发展的恐惧、早就丧失其80年代未时那股欲以经济实力领导亚洲、去与美国争天下的“自信心”、而一心想依靠“重走军国主义”这条老路、假借与美国联手遏制中国、图谋一边借美国力量削弱中国、打乱中国的现代化进程，一边也想借中国已经壮大的力量、通过在中美之间制造直接对立、从而寻找机会彻底摆脱美国。

然而，日本人在玩这一套东西的时候，有太多的事情证明这不过是日本的一厢情愿、自说自话。在这里，别的不说，就只挑一件3月底发生的一件不起眼的事情加以论证。


*** 再提“蓝岭”号访华所具有的重要的政治意义


不久前、我们曾经专门点评过美军第七舰队旗舰“蓝岭”号到中国访问的新闻。就如首席评论员当时所指出的那样，此次“蓝岭”号访华具有非常重要的政治意义，其重要性就在于华盛顿急于表明“在现阶段里，在美国愿意在中东一揽子问题上”与“中欧俄”暂时妥协的同时，华盛顿非常希望同北京维持一种稳定的关系、以确保包括台海、朝鲜半岛在内、整个东亚的暂时稳定”。

有意思的是，期间，我们也注意到有的战略分析人士得出的结论“似乎更加积极”，一种典型的观点就认为，军事交流是两个国家之间最高层次的交流。因此，此次“蓝岭”号访华，反映了中美两国政治关系的改善。


*** 如果就此下“反映了中美两国政治关系的改善”这一结论，显得“并不合适”


然而，在我们认同“美国现在非常希望同中国维持一种稳定的关系”的同时，也必须强调，华盛顿的这种“非常希望”，只不过是一种面对现实的“现实态度”和”权宜之计”而已，在东方评论员看来，如果就此下“反映了中美两国政治关系的改善”这一结论，显得“并不合适”。

然而，首席评论员则认为，在今后的几年中，随着中东、中中亚局势的演变、中美间有两个趋势特别值得注意，第一，就是华盛顿一旦看到中东政策彻底破产、且其经济稳定也不能持续时，极有可能借助“美日军事同盟”的声势，去给台独势力足够的信心去重启“台独进程”、在台海、以至东亚制造战争、从而主动打断中国的建设、同时，还可能在中东、中亚制造战乱，破坏中国、欧洲的能源线的稳定、最大限度地冲击中、欧经济、图谋在乱中寻觅重掌战略主动权的战略时机；

显而易见的是，在这种考虑中，日本的重要性是不言而喻，而华盛顿想尽办法也要拿到那份新的、将台海纳入战略目标的“美日安全指针”的动机也是不言而喻的。

第二，就是美国的经济稳定可以基本保证时，美国有可能接受其中东政策彻底破产的现实、从而退而求其次、接受世界多极化或者“欧洲、美洲、亚洲三极化”，这样，中美两国的军事交流和战略合作倒有机会提升、在我们看来，促使中美在“反分裂法”生效之后不久，就立刻开始军事交流的首要因素、就是日本因素。


*** “蓝岭”号访华并没因为中国通过《反分裂国家法》而受到影响，恐怕最主要的原因就是日本因素

在东方评论员看来，“蓝岭”号访华并没因为中国通过《反分裂国家法》而受到影响，恐怕最主要的原因就是日本因素。我们认为，由于美国在国际议题上必须与中国合作，因此，表面上，华盛顿“不能明白地、公开地”与中国站在敌对立场，在与“中欧俄”争夺中东、以及整个欧亚大陆之余，美国为保有在东亚制衡中国的力量，需要日本成为“代理人”，去公开支持台独。

*** 日本人太急，急到“似乎不明白”这么一个道理

而想通过公开支持台湾、换取更大政治、军事利益的日本、从2月份签定“美日安全共同声明”起到现在为止，显然没有从华盛顿得到“足够的回报”。东方评论员认为，华盛顿之所以敢如此行事、玩弄日本，就在于日本人太急，急到“似乎不明白”这么一个道理，那就是，像中国和美国这样的核大国、在全力争夺国家利益的时候，也得考虑“可接受的风险”。

在东方评论员看来，这种“可接受的风险”的一条底线、就是同时身为核大国的中美双方，都在力避双方间直接发生军事冲突的危险。显然，为了做到这一点，一个最有效、最实际的办法就是通过各自的“代理人”去角力。

*** 华盛顿在这方面是占优势的，它手中一度就抓到过“两张牌”

显然，华盛顿在这方面是占优势的，它手中一度就抓到了“两张牌”，一张是“和平台独”、另一张就是日本军国主义。然而，在北京用“反分裂国家法”彻底封死了“和平台独”的通道、并迫使华盛顿为避免与中国提前摊牌，而将陈水扁的“台独进程”压回到他刚上台时的水平之后（承认“四不一没有”、承认中华民国宪法），日本军国主义这张牌就犹显重要。

现在，美国之所以需要放出日本来做“代理人”，就在于两点考虑，第一，由于“反分裂国家法”不仅剥去了华盛顿所谓的“台海现状定义权”，也确立了“台独”不再有“和平台独”的路可走，中国大陆是“纸老虎”的宣传也不攻自破，因此，对台独和支持台独的国际势力而言，他日要想打“台独牌”去重创中国，就只有“武力拒统”这种选择。

因此，“如何让旁人相信”美国有能力在为日本提供核保护伞的情况下，利用日本的常规军力和政治野心、全力去支持美国“协防台湾”，其意义就显得“非常现实”。

东方评论员认为，站在华盛顿的角度来看，以一个虚假地、“让日本在国际上发挥更大政治、军事作用”的“胡萝卜”、去换得一个涵盖台湾的“美日军事同盟”、一来可以分化“中日韩”的东亚经济一体化进程，二来可以达到在军事上牵制中国的目的，显然是绝对地“物有所值”，应该承认，到目前为止，尽管北京一直愿意顾全大局、以免“中日两国”因关系全面恶化、而都落入美国早就挖好的陷井、但由于日本的政治野心过于急切，结果是华盛顿的挑起中日恶斗的战略目的可以说已经初步达成。


*** 美国的这种“胡萝卜”，本质上是在逼日本“拿出足够的反华诚意来”

第二，华盛顿在放出日本的同时，事实上就已经在盘算“如何渔利”，即，通过将台湾纳入“美日安全声明”的这个举动，并利用中日间在历史问题上“不可调和的矛盾”,去催动中日关系走向全面对抗、并进入白热化。

东方评论员认为，美国的这种战略考虑，本质上是在逼日本在与中国为敌方面、“拿出足够反华诚意来”、显然，一旦日本“拿出了足够的城意”，一旦又遭到中国的强烈反击，而在政治和军事上对日本做出激烈的打压动作、那么，中日关系也就如美国所愿、在政治、军事、经济上彻底走上对立，而日本极可能在中国的重压之下、全面投靠美国，成为美国在政治、经济、军事全面控制下的、阻挡中国在西太平洋区域渗透的一道“牢固堡垒”。

*** 日本决策层在愿意接受“美国给的胡萝卜”的同时，心里想着的可不象是“怎么协防台湾”

至于日本、其目的可不是继续呆在美国的核保护伞下，而是想重走军国主义、自己为自己撑起一把“核伞”，因此，日本决策层在愿意接受“美国给的胡萝卜”的同时，心里想着的可不象是“怎么协防台湾”、而根本就是在瞄着如何将“朝核问题”想方设法恶化成“东亚核竞赛”、其手段更是直接，即想通过在东亚“拼命闹事”、去激化“朝核六方会谈”“六个成员国”之间、特别是中美间的战略矛盾、从而迫使一直在压制着自己的“中美”、在东亚军事平衡的问题上“重做安排”：或是中国对日本在政治上让步，从历史问题上后退，从而让中国在亚洲国家中的名声扫地，而摆脱了历史包袱的日本、则可名正言顺地“回归亚洲”，担任亚洲领导人的角色、再去心甘情愿意地推动东亚、乃至亚洲经济一体化，然而，日本的这一算盘却有个不可逾越的巨大风险，那就是，如果从地区政策而言，如果日本与中国闹翻，那么日本也就彻底掉进了华盛顿的陷井，值得强调的是，中国也一样彻底掉进了华盛顿的陷井。

*** 如中日双方关系彻底决裂，那么、日本的外交政策也就彻底完蛋了

在东方评论员看来，对日本而言，如果中日双方关系彻底决裂，中国受损自然很大，但是，对于日本而言，其外交政策恐怕也就彻底完蛋了，不仅整个亚洲政策也就走到头了，更要命的是，日本将彻底沦为台湾第二，从而象台湾问题那样，不再会有什么政治、军事自由，长远看也将失去经济自由，从而彻底成为“中美关系”的一个附属品。

*** 一个与中国彻底闹翻的日本、除了当美国的奴才之外、还能做什么呢？

我们的观点是，这时的日本、在亚洲战略上，它无法依靠中日关系去与美国周旋，而在世界战略上，由于中国在亚洲的存在，它又无法成为欧洲、俄罗斯针对美国的合作对象，那么，一个与中国彻底闹翻的日本、除了当美国的奴才之外、还能做什么呢？明白“没有中日关系、对日本的损害绝对是致命的”这一点的北京、又怎么可能让日本轻易地摆脱历史包袱呢？同时，也又怎么可能让自己与华盛顿周旋的“日本筹码”丧失贻尽呢？

如此一来，东方评论员认为，不论从什么角度去看，北京都绝不可能在历史问题上对日本做原则性让步、但也不会如美国所愿地那样在政治、经济、军事层面上、针对日本进行全方位地打压，东方评论员认为，日本尽管在历史问题上、钓鱼岛、东海主权问题上登鼻子上脸，但只要中国就象这次中日较量这样，就是“不松口”，那么，显而易见的是，不论是历史问题、还是主权问题，日本就是想解决也解决不了。

*** 日本越是从中国这里得不到什么，也就越不敢与中国彻底翻脸

在我们看来，在历史问题这个大是大非的问题上、日本越是从中国这里得不到什么，就越是不能得到其它亚洲国家的“信任和信服”、也就越不敢与中国彻底翻脸，这中间，韩国之所以敢在关键时刻“奋起抗日”，就在于卢武铉看清了北京在朝鲜问题上、决心维护自己的利益、而不会对华盛顿做出原则性让步这一点。

东方评论员认为，在历史问题上、北京似乎决心利用中日在历史问题上的死节和中日在经济关系上的相互依赖、将“中日间的政冷”将慢慢导致中日间的经冷”的风险，通过各种方式去将这种“慢慢的趋势”放风给日本社会，从而掐住日本右翼势力的无法在“民粹政治”和“民生经济”两大问题上“同时在国内加分”之“七寸”、让日本整个社会去“反省”。

*** 日本政府有这个胆子、有这个能力和有这个本钱吗？

对此，东方评论员认为，尽管中间出现了我们也不愿意看到的、也不必要的“过激行为”，但是，这一轮的“反日示威”的确起到了这一重大作用，向日本社会、特别是与日本政治人物一样幻想着“政治不会影响经济”、“最后关头中国会让步”的日本经济界、传送了足够的信息：那就是“中日长期的政冷必然导致经冷”的信息、也包括中国绝不会在历史问题上让步的信息。

另外，值得一提的是，至于日本右翼所叫嚣的“为了钓鱼岛和东海资源、不惜与中国发生军事冲突”，东方评论员认为，华盛顿倒是“极为乐意”看到这一幕，可日本政府有这个胆子、有这个能力和有这个本钱吗？

*** 华盛顿决策层心里还有一本账更是算得清清楚楚的

在我们看来，现在的国际局势正处于巨变的前夕，日本在东亚与中国虽然闹得凶、而且我们有太多的证据去证明日本挑衅中国的背后挑唆者正是美国人，然而，华盛顿目前的战略重点并不在亚洲，而在中东，当务之急不在东北亚，而在中东、再就是中亚。

因此，东方评论员认为，美国在有心利用日本作为牵制和削弱中国在亚洲、或者东亚地区安全和战略影响的主要“棋子”的时候，的一点是清楚的是，那就是，放日本出来、或许可以在相当程度上减轻美国的压力和负担。

但是，在我们看来，华盛顿决策层心里还有一本账更是算得清清楚楚的，即，它之所以不得不放出、且自认为“有条件”放出日本这颗危险的棋子，以更大程度地利用日本去实现美国的战略计划、其最根本原因就在于有中国这个制约日本的关键因素，因此，美国在决定放出日本的同时，就已经在“定制”一条“拴住日本政治、军事、经济能力的皮带”了。

*** 要“定制”这么一条“结实的皮带”，华盛顿就得继续与北京“合计合计”

显然，要“定制”这么一条“结实的皮带”，就得在政治、军事、以至经济上有个全面的安排，华盛顿就得一如既往、继续与北京“合计合计”，也就是在这种背景下，美军第七舰队旗舰“蓝岭”号、不顾中国刚刚通过不久的、令美国决策层咬牙切齿《反分裂国家法》到中国访问、并与中国军方开展军事交流的，由此可见，国家利益至上是何等的现实。

这还不是全部，而也是在这种背景下，我们惊奇地看到，日本政府竟然默许其台湾势力的代理人--李登辉掌控的“台联党”、派出其党主席亲自带队去靖国神社参拜，并亲口称是对在二战中为“日本国”献身的（包括二万八千台湾兵在内）的二百多万日本军人的“敬拜”，显然，日本在这当口让李登辉派他一手提拔的苏进强去日本上演民族败类这一出，是在向北京示强，意在强调日本在台湾的影响力、也意在公示华盛顿在与北京欲继续联手压制日本的同时，华盛顿也在玩两手策略，即美国对日本介入台湾问题政策限制的“松绑和鼓励”。


*** 华盛顿突然间“如此地热爱和平”，这并不奇怪

然而，在华盛顿看来，日本人挑畔中国是好事，就是跳得再高点也没有什么、但条件是得落在一个“圈圈”内，那就是不得损害美国“现时的东亚战略”。不难看出，华盛顿现在正卖力地“促进”着两岸和平，也在对朝鲜“缓言暖色”，然而在东方评论员看来，华盛顿突然间“如此地热爱和平”，这并不奇怪，因为在现在，在眼前，美国的东亚战略就是不得改变中美两国在赖斯访华期间达成的“大致共识”，那就是，北京手里有个朝核问题的“进一步恶化到刺激日本国内进行核竞赛的问题”，而华盛顿手中也有一个迫使北京必须启动“非和平进程”的“台独”的问题，这两个中的任何一个，都足以全面破坏当前中美共同维持、联合控制日本的东亚安全格局，因此，这“一来一往”、其结果是中美在全面权衡利弊之后，必然是得出一个“东亚必须暂时保持相对的稳定”之共识。

*** 近期内，中美关系还能保持大体稳定，因此，中日陷于全面战略对抗的可能性就不大

东方评论员认为，在美国与“中欧俄”都分别将“谋取中东独霸权”、以及“反对美国独霸中东”做为自己的头等大事、且也都对自己有信心实现各自中东战略、并破坏对方战略的时候，在东亚这个包括有日本这一危险因素的战略区域内，北京和华盛顿对此区域必须保持相对的稳定，在利益上有交叉是不奇怪的、能达成共识也是自然的。

首席评论员指出、在我们观察包括台湾、朝鲜、日本等东亚局势的时候，必须眼睛紧盯着中东的局势，在我们看来，在中东局势还不明朗的时候，由于中美双方都有意稳住包括台海、朝鲜半岛、日本在内的东亚、可以肯定的是，日本的政治与安全战略尚处在美国和中国“共同利益”的影响和控制范围之内。

*** 小泉政府将“何去何从”、必然会成为近期的一个重大新闻

因此，近期内，中美关系还能保持大体稳定，因此，中日陷于全面战略对抗的可能性不大，因为那对中国利益的损害极大，对日本而言更是致命的，即使是最极端的日本右翼政治人物，心里也清楚日本挑畔中国的目的绝不是为了现在就与中国陷于全面战略对抗，因为现在就与中国全面对抗，日本极可能在政治、经济上陷入困境、特别是对日本经济上的巨大影响、极可能遭致日本国内民意的反思、从而导致其为军国主义招魂的计划提前终结。

日本外相访华期间，东方评论员注意到，中国外长当着日本外相的面说过“中日关系如果放任不管就会更加恶化”这么一句话，在我们看来，这句看似外交式的语句，其实意味着一个重大转折，东方评论员认为，这就是一个信号，是一个北京暗示“不再愿意单方面去顾及、并维护”对两国都至关重要的中日关系的信号。如此一来，在北京表示出极其强硬、并给那个气势汹汹的日本外相以极其难堪、不留余地的奚落之后，在是“选择美国”、还是“选择自由”的问题上，日本政府的选择余地并不大、选择时间也不多了，因此，东方评论员们的一致看法是，小泉政府将“何去何从”、必然会成为近期的一个重大新闻。

为了更好地讨论“中日关系”，我们再来看看日本国内的“一个动态”，它是日本一家新闻媒体做的一个调查，其结果是否可信，我们不去评论，但是，日本国内的确比以前更加重视中日关系、这却是个不争的事实。
