# -*- org -*-

# Time-stamp: <2011-08-04 11:57:52 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 2005年7月11日 星期一

** 赖斯：中国军力增长美国不认为是威胁



【北京消息】据海外媒体报道，美国国务卿赖斯十日在北京指出，中国是国际政治中的一股力量，美国的目标是希望中国成为一股正面的力量。她也表明，美国会持续作为维护亚太区域和平稳定的力量。

正在亚洲访问的赖斯十日在北京举行记者会，她在答复美国是否视中国为威胁的问题时作此表示，美国国务院今天公布了这项记者会的纪录。她稍后已转抵曼谷访问。

赖斯表示，中国正在经历大规模的国内转型，进而带动整个亚太区域转型，「我们的目标是看到崛起的中国形成国际政治中的一股正面的力量。」

她指出，中国是国际政治中的一股力量，问题在于中国会成为什么样的力量，「我们相信中国完全有机会成为非常正面的力量。」

赖斯表示，她在会晤中国领导阶层时提到军力平衡相关问题。她说，毫无疑问的，美国对中国军事扩张的速度和规模有所关切，她已向中国领导阶层说明，这不只是美国国防部的看法，而是整个美国政府所持的观点。这并不表示美国将中国视为威胁，只是美国注意到中国正在大幅度扩充军备的事实，这是令人关切的事，美国关切的是军力平衡问题。

在北京访问的美国国务卿赖斯昨天说，中国军力增长是美国政府、而不只是五角大楼所关心的事情。中国总理温家宝在会见赖斯时则强调，中国坚持走和平发展道路，现在没有、将来也不会干涉和威胁任何国家。

在前晚抵达北京的赖斯昨天上午会见了中国国家主席胡锦涛、总理温家宝和外长李肇星。她在单独召开记者会后，又于下午会见了负责六方会谈事务的国务委员唐家璇。

感谢中国努力重启六方会谈

她对中国在重启六方会谈上所做的努力表示感谢。

赖斯说：“我们非常感谢中国政府所做的努力，和表现出来的负责任态度。中国做出了很大的努力。”

对于美国是否认为中国是一个威胁，赖斯用“复杂”来形容中美关系。

她说：“毫无疑问的，我们对中国军事力量在规模及速度上的增长有所关切，而且这不只是五角大楼（的看法）。我曾清楚的表示，这是美国政府的看法。但这并不表示我们把中国视为‘威胁’。我们只是提出中国军力显著增长的事实，我们对于军事平衡表示关切；当然，美国也会持续提升本身的军事现代化，以便维持本区域的稳定。”

美国国防部一再推迟公布一份关于中国扩军的报告，一般相信是因为白宫及国务院对于报告过度强调中国的军事威胁有所保留。

赖斯表示，双边经贸关系在过去几年有了长足的进步，虽然存在问题，但是总体的经济关系是健康和有活力的。她说，只要符合国际规范，美国乐见中国经济蓬勃发展。

在台湾问题上，赖斯重申了美国的“一个中国政策”及《台湾关系法》，她形容中国政府与台湾的接触是一件好事，并希望接触对象能扩大到台湾的民选政府。

赖斯也在记者会上主动提到，她就人权与宗教信仰自由问题及达赖喇嘛和西藏问题同中国领袖交换意见。她说：“我们希望中国主动接触达赖喇嘛，他在西藏享有极高的道德权威，而对中国丝毫没有威胁。”

双方并没有讨论中海油收购美国优尼科公司的交易。

中国是赖斯东亚之行的第一站，也是她上任国务卿以来半年内的第二次访华，她接着将访问泰国、韩国和日本。





【时事点评】在东方评论员看来，这是赖斯就任美国务卿的第二次访华，就行程而言，真可谓是“来也匆匆、去也匆匆”，不过还好，这次赖斯没有象上次在《反分裂国家法》通过之后那样、对北京表现出“极大的情绪”。


*** 赖斯的“访问成果”中、“充分反应、并吸收了”这些天来中美角力的“最新成果”

显然，在我们看来，尽管赖斯的自9日晚上（北京时间）开始的这次短暂访问是上个月就已经计划好的，但是，东方评论员认为，就结果而言，赖斯的“访问成果”中、则“充分反应、并吸收了”这些天来中美“盯着东亚”、而在其它方向“大打出手”的“最新成果”。


*** 布什所谓的“中美关系”“非常复杂”是“话中有话”

在之前的点评中，东方评论员已经分析过，自布什用“非常复杂”、以及很难简单的用“单个方面”去评说中美关系的“性质”之后，在我们看来，华盛顿实际上就正式开始了对“中国威胁论”的“公开论证工程”。

非常清楚，布什所谓的“中美关系”“非常复杂”可以说是“话中有话”，其“很难在单个方面去评说中美关系”更是“暗藏玄机”。

东方评论员认为，华盛顿新保守主义团队这次为布什提供的策略、就是要将“中国威胁论”有针对性地分解成不同版本，针对不同的对象进行“推销”，比如，针对中国家门口的、与中国有主权之争的亚洲国家、华盛顿力推的是“军事版本”的“中国军事威胁论”、针对与北京没有重大地缘政治利害冲突的欧洲、美洲、则明显是在兜售着“经济版本”的“中国威胁论”。


*** “中美”近段角力全面升级的一个转折点

显然，在我们看来，就如在之前的《东方时事解读》中所说的那样，布什的这一套“看似顾全大局”的高论，事实上就是在为“中国威胁论”的大规模“推销行动”所致的“开幕词”，也是“中美”近段在东北亚、中亚、中东等国际安全问题上的“较劲”趋于摊牌、在纺织品、汇率、知识产权保护等经济问题上角力趋于“强硬对强硬”的一个转折点。

在东方评论员看来，第一个跳出来“推销”“中国威胁论”的、理所当然地是对美国新保守主义政策“身体力行者”的大本营--五角大楼。

我们注意到，尽管华盛顿决策层策划周密，但是，在拉姆斯菲尔德上个月在新加坡针对亚洲国家、突然放出“中国军事威胁论”的“探风球”之后、与中国经济关系日紧的亚洲国家中、除了日本的防卫厅长官当场公开附和、要求北京透明军事计划、军事开支、配合拉姆斯菲尔德的“推销行动”之外，可以说是“几无反应”。

不仅如此，拉姆斯菲尔德的“中国军事威胁论”还遭到许多亚洲国家的公开质疑，就连和与华盛顿“心有灵犀”的新加坡政府、最后也不得不以“中国的发展不是威胁、而是新加坡的机会”这类的话来“刻意减轻”因向拉姆斯菲尔德“提供了这个反华讲台”所引致的消极影响。


*** 华盛顿配合这一轮“论证”“中国威胁论”“是否可行的”之最显著动作

事实上，在东方评论员看来，华盛顿决策层配合这一轮“论证”“中国威胁论”“是否可行的”最显著动作，就是那份本来在3月份就已经由五角大楼完成、但一直没有公布、也不为人们所重视的的“中国军力报告”，却“突然”“被白宫以“有关中国军力的描绘太过夸张、而要求再做修改”的方式、而一夜间就搞得是“地球人都知道”了。


*** 白宫对如何操纵媒体热点，的确有着“非比寻常”的功底

显然，白宫对如何操纵媒体热点、吸引国际舆论关注、来配合自己的战略计划这一层面上，的确有着“非比寻常”的功底，因此，在东方评论员看来，美国决策团队有意借“白宫不满意原稿、并公开要求退回五角大楼修改”这一罕见的动作、来做成“引线”、非常准确地引出了“中国威胁论”这个焦点话题，从而顺势加以炒作、并在“这个炒作过程”、不时地配以各种小动作、以达到多层次、多方向地对北京和其他国家“可能的反应”进行“综合试探”。

我们认为，这中间，有两个非常典型的案例，一个就是美国防部长拉姆斯菲尔德亲自在新加坡抛出、而美国务聊赖斯也曾经“多次给过肯定”的“中国军事威胁论”，再一个就是所谓的“纺织品争端”。


*** 对华盛顿的“中国军事威胁论”，北京的反击是“实实在在”的

东方评论员认为，对华盛顿面向亚洲推销的“中国军事威胁论”，北京的反击是“实实在在”的，在我们看来，这种实实在在的反击主要有三件事：

第一，华盛顿不是面向亚洲兜售“中国军事威胁论”吗？那么，中国在军事上就配合华盛顿的意思真的“威胁”了一下。众所周知，就在拉姆斯菲尔德先生于新加坡的讲台上、“生气地”冲着北京质问：“为什么要发展那么多、可以射向任何地方的导弹”后，中国还偏偏就“哪壶不开提哪壶打”，立刻安排打一发据说射程8600--12000公里、可以涵盖美国全境的“巨浪二”战略潜射导弹、着实地“证明”中国的确“有能力在军事上向某个方向进行毁灭性的威胁”。


*** 在这里，我们想再说点关于上次发射“巨浪二”的题外话

在这里，既然说到了“巨浪二”，我们想再说点题外话。东方评论员注意到，美国方面的专家在事情过去许久之后，对中国此次发射成功的“巨浪二”用的何种载体、“仍然在那里猜猜猜”，说什么中国绝不会让造价近乎天价的“094”冒此风险、担任“首发”、并由此肯定这次是用的“水下发射装置”、而非中国新下水的“094战略核潜艇”。

但在东方军事评论员看来，“这种推测”作为一种“谈资”还是有其价值的，但是，如果有人想通过“这种推测”来说明什么、那就成了“非常可笑的事情”了：显然，该观点“并不敢否认”中国有能力、或者已经建造出了“094”、这样，人们不禁就要思考：这种观点在做了一大堆推测之后，究竟想“下个什么结论”呢？是认为中国的“094战略核潜艇”没有建成、而不得不用水下装置代替？还是想证明中国的战略核潜艇“没有能力”进行水下发射？或者只是想证明中国新一代的战略核潜艇没有能力进行“巨浪二”的水下发射？

显然，任何一个明眼人都会明白，以中国今天的技术实力，水下发射潜射战略导弹早已经不是个新玩意了，从上个世纪80年代未起、中国的“092战略核潜艇”就已经开始携带“巨浪一”服役了，因此，在东方军事评论员看来，就算这次发射就如美国专家所说的、是用的“水下装置”、那么，这种“水不装置”不过也是模拟“094”的发射条件、去替代“094”进行的一次未携核弹头的“实弹打靶”，换而言之，由于从这次“实弹打靶”的射程来判断，必是“巨浪二”无疑，因此，在“巨浪二”已经否认不了的情况下、只要美国人“不敢否认”“094战略核潜艇”的存在，那么，北京事实上也就有了在隐蔽性极强的大洋深处、一次向美国本土投送一百个以上的核弹头的能力，显然，这将是中国战略核打击力量的又一个里程碑。


*** 一位美国学者的一席话、就说得“非常到位”

好了，现在我们言归正传。在东方评论员看来，中国“巨浪二”的成功发射，对华盛顿五角大楼的震动是巨大的，我们认为，谁都知道，华盛顿之所以敢对中国说出“军事介入台海”、“考虑攻击三峡大坝”这一类威胁的话，其根本原因、就在于华盛顿根本“不相信”、或者出于自己的战略目的、“根本不愿意相信”中国也有摧毁美国的“核毁灭能力”。

在东方评论员看来，华盛顿之所以总是喜欢“非常认真地告诉世界中国有20枚可以打到美国的洲际战略导弹”，其中一个重要企图就在于：只要中国“以事实不能证明”自己拥有“有把握摧毁美国”的终极核威慑能力，那么，美国人就“始终可以证明自己会按《与台湾关系法》的规定、考虑介入台海军事冲突”。

可问题在于、你就是翻遍了整个“与台湾关系法”、你也找不到“美国一定会出兵台海”法律约束条款、甚至是在中国武力解决台湾的情况下、你也不能从那部“台独”、与支持“台独”的国际势力嘴里念念不忘的“与台湾关系法”中、寻找到可以直接推导出“美国一定会介入台海战争”的、相关法律约束条款来。

显然，美国在“是否介入台海”的问题上，始终是在“策略地不说清楚”、“刻意地保持模糊”，对此，一位美国学者的一席话、就说得非常到位，他说：“只要中国人无法说清楚是否有象俄罗斯那样的、让美国社会害怕的、足可以毁灭美国的核打击力量，那么就不要指望华盛顿会在台湾问题上说真话”。


*** 北京展示出的“军事威胁能力”，显然是冲着太平洋对岸的美国

在东方评论员看来，“巨浪二”的成功、以及“094”建成的消息一旦得以证实，那么，随着后续艇的继续建设、以及东风41型机动部署战略核导弹成军，在中国建立起一套完整的“二次战略核打击力量”之后，并以确凿的证据令美国社会、国际社会相信能够毁灭美国的不仅仅是俄罗斯这一个国家的话，那么、令美国人非常自信的核威慑优势、以及美国凭借自己的核优势为“台独”撑腰、为日本挑衅北京而撑开的核保护伞，到底有多大作用？甚至有没有人相信？恐怕就是另外一回事了、我们相信，在那个时候，也就是华盛顿在台湾问题上“说清楚”、美国国会在叫嚣“军事介入台湾”的问题上闭嘴的时候了，

非常清楚，北京这次展示出来的“中国军事威胁的能力”，显然是冲着太平洋对岸的美国，是直接冲着“中国军事威胁论”这个“美国制造商”的、根据我们的观察，“美国制造商”欲兜售、倾销的“亚洲市场”、除了日本与“台独”之外，似乎没有人因中国的“巨浪二”感受到威胁，显然，这东西打得太远，根本就不是用来威胁亚洲的。


*** 北京对台海局势“有了另外一种玩法”


东方评论员认为，也正是因为手中挰着“非和平手段”粉碎台独重大事变的“反分裂国家法”、为台独划下了红线，而华盛顿出于自己战略利益、又不敢打出台独牌，从而北京在台湾问题上“不再对美国有所期待”。

在我们看来，北京也因此而对台海的局势“有了另外一种玩法”，那就是只要华盛顿不敢打“台独牌”，那么，北京就可以一边对“台独”进行“冷处理”、一边与台湾“不搞台独”的各种势力打交道、在继续自己的经济建设、继续强化“军事解决能力”的同时、可以从容地利用经济的吸引力、利用台湾所谓的“民主选举”、通过台湾在野党，将民进党往“两岸三通”的方向“驱赶”。

当然，东方评论员认为，能“驱赶”出一个“两岸三通“来最好！做不到这一点也没有关系，在北京将制止“台独进程”的工作交给华盛顿去做之后，大陆只要确保“在最坏的情况下军事解决台独的能力”得到继续强化就行！

东方评论员认为，就如我们在上周五的台湾部分所说的那样，随着新党大陆团“民族之旅”的结束，本月16日，国民党的党主席的大位就要定了，在我们看来，大陆新一波的统战工作也就要开始了。



*** 北京对美国兜售“中国威胁论”的第二个反击


东方评论员认为，也正是“在这种相对以前轻松得多的心态下”，北京才得以对美国兜售“中国威胁论”进行第二个反击，就是默许朝鲜再次将“暂时稳住、没有进一步恶化”的朝核问题、又给搬了出来，这表现在朝鲜强硬地拒绝华盛顿的“先行废核”的要求，反而重启核反应堆、声称要继续制造更多的核武器、不仅如此，还再次地将“朝核问题”与包括驻韩美军部署核武器的问题给提了出来，明确表示“朝核问题”就是“朝鲜半岛核问题”。

在东方评论员看来，北京默许朝鲜这般强硬，就瞄准了华盛顿的“两个软肋”：一个是日本有核武装企图，对这个问题，中国清楚，决定权不在于自己，而在于华盛顿，只要美国愿意、并认为日本核武装符合美国的国家利益，中国是挡不住的。显然，中国在这个问题上一再“将”华盛顿的“军”、就因为在目前阶段，“全力阻止日本的核梦想”才最符合美国的战略利益。

东方评论员认为，既然美国人在东亚核竞赛问题上在“投鼠忌器”，那么，华盛顿就别指望一边想让中国帮忙稳住朝核问题不再向“东亚核竞赛”方向恶化，一边还指望继续维持强硬的朝核政策、将朝鲜半岛目前这个“不稳定”的局面再继续下去、从而阻止朝鲜的经济改革、达到将经济困难的朝鲜当作一个大包袱、给中国背上，并将一个不稳定的朝鲜半岛、给中国、日本、韩国背上。


显然，从韩国近来积极与中国朝核政策协调、有意与中国、俄罗斯一道、不顾美国的反对、强行启动朝鲜半岛经济整合的情况来看，华盛顿在东北亚、在朝核问题上、如果不改变其强硬的立场、那么就几乎陷入“无牌可打”的窘境。


*** 北京对美国兜售“中国威胁论”的第三个反击

第三，北京对美国兜售“中国威胁论”的第三个反击，就是先与印度建立合作伙伴关系、再与俄罗斯一道，将伊朗、印度、巴基斯坦同时接纳为观察员，并通过上海合作组织的名义、向美军发出了请从“上合”成员国“离开”的逐客令。


东方评论员认为，上述这些、只是简单地列举了中美间这些天来一边“盯着东亚”、一边在其它方向“大打出手”的“最新成果”、特别是“朝核问题”发展成了韩国不顾“美韩分手”也要走自己的路的问题、而“中亚问题”也发展成了美国还能在上海合作组织成员国“待多久”的问题，在我们看来，也正是这些“新成果”、“新情况”下、前不久还在为拉姆斯菲尔德的“中国军事威胁论”“背书”的赖斯，前不久还“坚称”不收回“暴政前哨”之说法的赖斯，终于又分别就这两个问题“琢磨”出了“两个新说法”：
第一，赖斯认为美国没有将中国视为威胁，只是美国注意到中国正在大幅度扩充军备的事实，这是令人关切的事，美国关切的是军力平衡问题。
第二，她还重申，美国承认朝鲜是主权国家，没有攻打和侵略朝鲜的意图，美方希望朝鲜半岛无核化目标能尽早实现。


*** 赖斯的“第一个新说法”，多少有点“早知如此何必当初”意味

显然，首席评论员就指出，对第一个新说法，我们认为，这多少有点“早知如此何必当初”意思，不难看出，对“中国威胁论”这个东西，华盛顿说说可以，千万不要“太认真”、以至于当成政策去执行。

东方评论员认为，这个道理很简单，一认真起来当成国策加以执行，那就意味着中美将彻底地撕破脸皮。这对北京当然不好，但从“中亚”这一局中俄与美国的“攻守易位”的过程来看，华盛顿在与北京公开为敌之后，要凭手上现在掌握的筹码去称霸，其能力“非常有限”。


*** 第一次提到了“朝鲜半岛无核化”这个北京、朝鲜的“专用名词”

另外，在东方评论员看来，值得注意的是赖斯这次除了“炒”“承认朝鲜是主权国家，没有攻打和侵略朝鲜的意图”这两盘剩饭之外，还第一次提到了“朝鲜半岛无核化”这个北京、朝鲜的“专用名词”。显然，这是个重大变化。

在一起了解一则来自韩国汉城的消息之后，东方评论员将继续回到这个话题。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
