# -*- org -*-

# Time-stamp: <2011-08-02 19:48:42 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

#+STARTUP: indent

* 2005年03月22日 星期二

** 美警告六方会谈不能无限拖延 朝正式增核武

【华盛顿消息】 美国白宫发言人麦克莱伦今天（22日）指出，解决朝鲜核危机的六方会谈不能「无限期拖延」，并力促平壤当局重回谈判桌。

据法新社报道，麦克莱伦说：「美国已就最后一回合谈判提出非常实际的建议，我们希望能看到顺着这些建议达成的目标。我们希望看到朝鲜回来谈判。」 美国国务卿赖斯今天稍早在中国访问时表示，朝鲜若不回来谈判，将会遇到「麻烦」，华府会寻找「其它选择」。
 
不过赖斯强调：「我们无意诉诸武力。」 麦克莱伦说：「赖斯国务卿表示，现在是朝鲜重回谈判的时机，这些话我们已说过了。她指出这项谈判不能无限期拖延，我们必须解决这项议题。」朝鲜最后一次参加六方会谈是于2004年6月。
 
今年2月10日，朝鲜宣称拥有核武器，并且无限期中止参与这项谈判。
 
国务院一名匿名资深官员，对六方会谈议题「明显缺乏进展」及难以解读朝鲜意向表示关切。
 
他说：「只要谈判继续拖延，威胁就不会降低，也会对于我们努力想达成的目标构成一定程度的危机感。」 他另表示：「我们至今仍不认为，六方会谈是按照我们想要看到的方向前进。」
 
赖斯：或寻「其它途径」解决朝核问题
 
美国国务卿赖斯周一(3月21日)表示，如果朝鲜持续坚持不回到谈判桌前，那么参与六方会谈的各国必须寻找处理威胁的新途径。
 
赖斯是在北京的新闻发布会上做以上表述的。 赖斯在周一晚上已离开北京，结束亚洲的访问行程。
 
赖斯表示：「会谈是否能重新开始取决于朝鲜，每个人都在等待，都准备好进行一个建设性的讨论。」
 
她说：「每个人都非常清楚国际系统当中的其他选项。」
 
「当然，如果我们通过这个途径（六方会谈）无法找到解决朝鲜问题的办法，那么我们将必须寻找其他途径解决。」
 
赖斯进行亚洲访问公开的目标就是要寻找一个恢复六方会谈（美国、朝鲜、韩国、中国、日本和俄罗斯）的共同战略。
 
朝鲜称「增加核武器以防敌国入侵」
 
朝鲜表示为抵御美国入侵，将增加其核武器。朝鲜没有就此发布详细信息，但是据BBC报道，韩国联合通讯社援引朝鲜官方媒体的话说，朝鲜已经采取措施，动员所有军力来抵御得敌人的挑衅行动。
 
在此之前，美国国务卿赖斯在她亚洲之旅的尾声提出，如果朝鲜拒绝就其核武器问题重返谈判桌的话，美国将考虑通过其它途径来解决问题。
 
朝鲜的声明正是在赖斯发表这一讲话后作出的。
 
上个月朝鲜官方首次承认拥有核武器。
 
美国认为朝鲜拥有一个或者两个核弹，并可能通过对核废料再加工获得足够制造半打多核弹的钚。
 
 
 

【时事点评】东方评论员曾经着重分析了赖斯在公文包里带来的那份“建设性的意见”到底是关于台湾问题的、还是关于朝鲜问题的。
 

*** 中美东亚“角力”，我们已经看到了奇怪的一幕

在东方评论员看来，就如我们昨天所分析的那样，直到目前为止，在中美东亚“角力”的问题上，我们已经看到了奇怪的一幕，即，在“台独进程”上，由于华盛顿操控着台湾政局，并在如何影响台湾民意上很有一套，因此，北京手中除了授权中央军委、国务院可以启动“非和平方式”的“反分裂国家法”可以有效地暂时制止住“台独重大事变”之外，在如何影响台湾政局和影响台湾民意方面，大陆仍然处于“无从着力”的状况之中。

因此，我们认为，从客观上讲，华盛顿仍然是唯一能够决定性地影响台湾岛内政治走向的势力。

而与此相对应的是，北京却通过对朝鲜的军事保护，借朝鲜宣布有核的事实，再加上韩国急于实现朝鲜半岛的稳定，日本梦想借机实现“正常国家”的的美梦，因此，在朝核问题上游刃有余的北京、实际上拿到了“朝核问题”何去何从的主导权。

所以，在东方评论员看来，北京和华盛顿事实上已经在朝核、台湾问题上“各执一边”，几个月来、就这么“在东亚相互对峙着”，然而，就如一位美国资深外交人士所说的那样，中美都是有力量的大国，就这么对峙下去，对谁都是一种伤害。
 

*** 赖斯的“建设性的意见”应该是一份“涵盖东亚两大热点”的“综合性意见”

我们认为，从美国推动“台独进程”挑畔中国核心利益、到北京启动“反分裂国家法”进行阻击；从华盛顿费尽心思地让“美日安全共同声明”“涉及台海”、到北京强硬支持“宣布有核的朝鲜”加以回应，在东方评论员看来，这无一不在说明美国是包括台海、朝鲜问题的东亚局势全面紧张的“始作蛹者”。

俗话说得好，，解铃还须系铃人，因此，我们倾向于这样一种观点，即，与之前想以一个“紧张的东亚”、逼迫区域内的中、日、韩紧跟着美国的利益跳舞的华盛顿，在中东遭遇“中欧俄”阻击、而无法摆平，在东亚面对着中国的“拒绝让步”而面临局势失控的现实下，美国终于愿意提出所谓的“建设性意见”。

首席评论员指出，如果华盛顿果真想如它正在中东所做的那样，“先将局势稳定下来、再徐徐图之”的话，那么，赖斯公文包中的“建设性的意见”就应该是一份“涵盖东亚两大热点”的“综合性的、建设性意见”。

我们注意到，国务委员唐家璇在昨天已经公开表示，对赖斯带来的“中美双边关系”提出的建设性意见感同兴趣，并将“认真加以研究”，可问题是，中国在“感兴趣”之余，并经过“认真研究”之后，最终是否还能保持“足够的兴趣”呢？在我们具体展开这一话题之前，再看一段相关报道，之后，东方评论员将一并给出自己的观点。
 
《东方时代环球时事解读》http://www.dongfangtime.com

** 美国务卿赖斯前脚走朝鲜总理朴凤柱今访华

【综合消息】  在美国国务卿赖斯离开中国之后，朝鲜总理朴凤柱将从二十二日起开始为期六天的中国之行。朝美双方接踵访问北京，朝核问题与六方会谈成为焦点。北京学者预料，朴凤柱此次来访，很可能是就六方会谈的具体内容与中方交换意见。
 
据香港大公报报道，著名亚太问题专家、中国国际问题研究所亚太室主任晋林波对六方会谈的复开表示乐观，他预计下轮会谈的时间很可能以六月份为目标。
 
晋林波说，中国在朝核问题上一直扮演积极的角色，积极劝和促谈，并一直担任六方会谈的东道国，做了很多努力。朝鲜半岛无核化符合全球、地区和中国的利益。
 
中国人民大学美国研究中心主任时殷弘说，能否尽快促使朝鲜重返六方会谈，已成为美国最关心的问题。甚至可以说，如果六方会谈在短期内无法恢复，美国很可能失去耐心，而端出解决问题的新方案。
 
「在这个时候，美国在外交上加大了对中国的压力，包括敦促中国采取过去不愿意对朝鲜采取的经济措施来迫使朝鲜重返六方会谈，」时殷弘说，「就这次赖斯访问北京来说，只有朝核问题才是中美确实需要认真磋商的问题，而《反分裂国家法》的问题，由于中美双方的基本立场已经确定，不可能因为这次访问有什么显著变化。」
 
 
【时事点评】坦率地讲，目睹着美国国务卿赖斯前脚离开北京，朝鲜的总理后脚就到了中国这一幕，让我们想起了去年4月的一次类似外交安排。当时，美国副总统切尼是“手持着强硬的台海政策”访问的北京、在他最终“一无所获地”前脚离开中国之后，仅隔了48小时，朝鲜的一把手金正日就亲自跑到了北京。
 

*** 北京通过金正日的成功访华，立刻促使“朝核问题”有了一种“实质性的变化”

东方评论员认为，带着强硬的台海政策的切尼之访华失败的后果，就是北京通过金正日的成功访华，立刻促使“朝核问题”有了一种“实质性的变化”。在我们看来，这种“实质性的变化”主要表现在“两个支持”：第一，北京公开支持朝鲜的政治体制，第二，北京还公开支持朝鲜进行经济体制改革。
 
 
*** “两个支持”所“带出来的”信号是强烈的

对切尼那次访问北京的失败，以及金正日访问北京的成功，在去年的《东方时事解读》中、我们已经有过非常详细的点评。在我们看来，上面的“两个支持”所带出来的信号是强烈的，即，自朝核问题以来，这是北京第一次公开地将“朝鲜政权”置于自己的保护之下，也是北京第一次将“朝鲜问题”作为一个战略杠杆、用以去主动反击华盛顿通过操纵“台独进程”、一面暗中推动“台独”、一面还要借机向中国“强索强要”之惯用伎俩。
 
 
*** 一年的时间里，中美两国经过一番斗智斗勇，可以说是“各有心得”

从去年4月份到现在的3月，差不多刚刚好是一年的时间，也就是在这一年的时间里，围绕着朝核问题和台湾问题，在东亚这个区域内、中美两国经过一番斗智斗勇，可以说是“各有心得”。

在东方评论员看来，在台湾问题上，北京的华盛顿已经斗出了个“反分裂国家法”，且这个“反分裂法”已经有取代“与台湾关系法”的势头，也就是说“反分裂法”的真正意义，就在于“一次性地”把“和平台独”“没有任何可能得逞”这点、以法律的形式“彻底地讲清楚、说明白”，从而从根本上“打掉了”美国以前可以随意解读“与台湾关系法”、“随意”为美军介入台海“开空头支票”的权力，从而成为中美两国处理台海问题的“新基准”。
 

*** 在“台独若独，大陆必武”的“共同认识”下，北京、华盛顿和台湾之间的游戏，当然就得“换个玩法”

因此，在首席评论员看来，在大陆“动武”已经不是个什么可以“猜测”的话题之后，“台独”一再所称“大陆是纸老虎”的自欺欺人，也就“到此为止”。从而，在“台独若独，大陆必武”的“共同认识”下，北京、华盛顿和台湾之间的游戏，当然就得“换个玩法”。
 

*** 中美间任何双方都可以接受的建议，都必将优先考虑到“反分裂国家法”的权威

东方评论员认为，由于华盛顿急需在台海、朝核问题上“稳住”北京，避免北京在台海局势、朝核问题上、去影响美国最看重的“中东进程”。所以，北京和华盛顿之间的任何双方都可以接受的建议，都必将优先考虑到“反分裂国家法”的权威。

在我们看来，由于“反分裂法”要求“台独若独，大陆必武”，可以肯定的是，“新玩法”的主调将是“缓和”；同时，由于“新鲜出炉”的“反分裂法”划定了“台海现状”和“一中含义”，因此，同样可以肯定的是，“新玩法”必然会包括进“反分裂法”划定的“台海现状”和“一中含义”。
 
在我们看来，在考虑到上述因素之后，两岸之间当然可以坐下来谈，谈和平、谈三通，谈那个华盛顿一直在兜售的“中程协议”，至于是否能“谈通””两岸三通“，恐怕是赖斯所带来的”建议”根本就“不愿意”提及的、在东方评论员看来，对华盛顿不过是在“搞缓兵之计”也“心中有数”的北京、大概也不会“天真地”心存“此种奢想”。
 

*** 华盛顿在打“打着小算盘”同时，北京又何尝不是在“心有旁骛”？

事实上，首席评论员指出，就在华盛顿心中“打着小算盘”搞缓兵之计的同时，北京又何尝不是“心有旁骛”？在我们看来，现在的“朝核问题”也早就不是个单纯的“朝核问题了”：华盛顿是往里添加了“美日台军事同盟”这个筹码、来压中国在包括台湾、朝鲜在内的一系列问题上做出让步，而北京也不示弱、硬是通过向华盛顿“提供”了“制止台独”和“全面缓和朝鲜半岛局势”、以及“东亚核竞赛”这几个“选择项”、从而将“朝核问题”这个单一命题、“一锅烩成了”一个“东亚安全框架”式的综合问题。
 

*** 通过这个“大论坛”，北京所得到的好处是非常明显的

因此，我们现在再来谈“朝核问题”、再来谈“六方会谈”，恐怕再也没有谁认为这是个“朝美”双方就可以单独“谈通说透”的事情了。也就是说，“朝核问题六方会谈”，很有可能演变成一个关于东亚、甚至是整个亚洲、整个亚太区域的整体安全框架的重大战略的“大论坛”（我们暂且这样形容）。

在我们看来，一旦这个“论坛”成形，那么，通过这个“大论坛”，北京所得到的好处是非常明显的，其中最重要的是一点，就是将“台独问题”从大陆"VS"“美日台军事同盟”的模式中抽出来，将“台独”打上“区域的和平与稳定”最主要威胁的标签，再把它放到这个“大论坛”中去、尽可能地利用国际力量去延缓“台独进程”。
 
 
*** 华盛顿将台湾问题纳入“美日军事同盟”的一个显著利益

不知大家是否还记得，我们在评论“美日军事同盟”时，就曾经说过，华盛顿将台湾问题纳入“美日军事同盟”的一个显著利益，就是可以降低台湾问题在中美关系中的“敏感度”。
 
在东方评论员看来，这种“敏感度”的减低，就在于华盛顿将日本这个因素正式地引入了“中美台”这场所游戏、结果是，“中美台”“三角游戏”、给弄成了“中美日台”“四角游戏”、总而言之，不论北京是否愿意，如果单独处理台湾问题，那么，就得面对日本已经成了“四角游戏”之一角的现实，这就是说，华盛顿就通过这么个纳入台湾的“美日军事同盟”，将一部分风险和责任让给了“急欲出头”的日本。
 

*** “美日安保共同声明”、其“战略溢价”已经“打起了折扣”

在东方评论员看来，如果就事论事而言，华盛顿在自己的力量不敷使用、实力有所不逮之际、利用日本急于成为“正常国家”的急切心理、为了防止北京趁机扩大在亚洲的影响、而费尽心机得到的这份新版“美日安保”、的确是一大成功。

然而，当我们结合着朝核问题“越闹越僵”，且日本不甘心只为美国承担了台湾问题的风险和责任、却没有得到任何实质性的好处（比如美国充许日本核武装、支持日本对钓鱼岛、东海划线的立场）、而在东亚借领土争端、到处闹事、且闹得“东亚核竞赛”的风声“越来越紧”的时候，那份费尽心机得到的“美日安保共同声明”、其“战略溢价”已经“打起了折扣”。
 

*** 胡锦涛当时当着布什的面所说的一句重话是“余音犹在”

在东方评论员看来，如果北京能充分利用周围的韩国、澳大利亚、印度、东南亚、俄罗斯、以及南美洲国家，对美国全球霸权的警惕、对日本刻意在东亚制造紧张气氛、图谋政治、军事大国的戒心，对台独可能破坏亚太地区和平与稳定的恐惧，而将朝核问题和六方会谈逐渐发展成一个有关“东亚、或者亚洲、更或是整个亚太地区安全格局”的“大论坛”，并和其它成员一起，共同努力去对亚太安全格局进行“重新定义”，那么，对现在这个旨在为美国称霸全球服务的“美日军事同盟”、或者将来的“美日台军事同盟”而言、其“战略溢价”也将大打扣扣。

事实上，这种战略意图，在胡锦涛主席于去年底参加亚太APEC峰会、会见布什时，就已经于“不经意”之中提出来了，在东方评论员看来，胡锦涛当时当着布什的面所说的一句重话是“余音犹在”，他说：台独将断送台海和平，并将严重破坏亚太地区的稳定和繁荣。中美双方都应站在这个战略高度来认识“台独”的危害，共同遏制“台独”势力的分裂活动。

在我们看来，胡锦涛的这句话虽然是说给布什听的，又何尝不是说给当时参加亚太峰会的其它国家成员听的呢？东方评论员认为，尽管这是个困难的战略目标，但是，这绝对是一个值得、并有条件可以一试的战略目标。
 
*** 这“一去一来”可以说清楚地证实了赖斯此番前来的“焦点所在”

现在，美国国务聊赖斯刚离开中国，朝鲜总理朴凤柱就到了北京，这“一去一来”可以说清楚地证实了赖斯此番前来的“焦点所在”，朴凤柱此次来访，显然是在就“六方会谈”的具体内容与北京“再做商量”，。
 
因此，在东方评论员看来，朝核问题是否会有进展，我们还需观察。就如中国外交部李部长所说的那样，台湾问题谈不好，中美之间的战略合作就无从谈起、如此一来，华盛顿“会不会永无限期等待”，并不是华盛顿一家说了就算的。
 
此间，我们已经注意到，华盛顿在赖斯访华提出了一个“建设性建议”之后，已经对朝鲜放话“我们不会永无限期等待”，但这只不过是种谈判前拉高身价的策略和手段而已，就如朝鲜威胁说要“增加核武器生产以自卫”一样，是“同一性质“的东西。
 
东方评论员认为，如果赖斯的“建议”果真是个涵盖了台湾、朝鲜两大热点的“建设性建议”的话，那么， 我们有理由相信，只要北京认为华盛顿的“建议”在台湾部分的确有“足够的建设性”的话，那么，朝核问题取得一点进展也是可能的。
 
《东方时代环球时事解读》http://www.dongfangtime.com
