# -*- org -*-

# Time-stamp: <2011-08-04 12:13:54 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent


*  2005年8月04日 星期四



** 吴邦国晤美众院议长：中国不是威胁而是机遇




【北京8月4日消息】中国全国人大常委会委员长吴邦国今天表示，中国将长期坚持和平发展道路，作为一支和平、繁荣和建设性的力量，无论是对美国，还是对世界，中国都不是威胁，而是机遇。中国愿同美国和平共处，互利合作，共同促进亚太地区和世界的和平、稳定、发展和繁荣。

吴邦国下午在人民大会堂与美国国会众议院议长哈斯特德举行会谈，双方就中美关系、台湾问题、议会交往以及共同关心的国际和地区问题友好、深入、坦诚地交换了意见，达成了许多重要共识。

吴邦国积极评价当前中美关系的稳定发展势头。他也指出，中美之间存在一些分歧和需要慎重处理的问题，但中美两国拥有重要的共同利益和广泛的合作基础。中方愿与美方一道，从战略高度把握两国关系的大局，通过加强对话，缩小和解决分歧，增进互信，通过发展合作扩大共同利益，努力推动中美关系取得更大发展。

吴邦国介绍了当前台海地区形势和中方为改善和发展两岸关系所采取的一系列积极举措，重申了中方在台湾问题上的原则立场。他表示，中方积极评价布什总统和美国政府多次重申坚持一个中国政策、遵守中美三个联合公报、反对“台独”的立场，反对台湾当局任何旨在单方面改变台湾地位的言行。希望美方以实际行动履行承诺，也希望美国国会多做有利于两岸关系改善和中国和平统一的事，不向“台独”分裂势力发出错误信号。

在谈到议会交往时，吴邦国说，中国全国人大与美国国会众参两院的定期交流机制进展良好，并取得积极成果。中国全国人大愿与美国众参两院一道，巩固和完善定期交流机制，保持高层互访和各层次交往的良好势头，进一步加深了解，不断增进政治互信，继续扩大交流和合作的领域，促进两国关系健康稳定发展。

哈斯特德赞成吴邦国对中美关系的评价。他表示，很高兴再次访华，赞赏中国取得的巨大成就。他说，美中关系有了很大发展，双方应共同努力，不断扩大共同利益和合作基础。哈斯特德充分肯定美众议院与中国人大交流机制取得的积极成果，希望不断加强机制框架下的交流与对话。哈斯特德重申坚持一个中国政策，对海峡两岸关系取得新进展表示欢迎。



【时事点评】在朝核问题、中日关系、中东问题、中美因人民币汇率、中海油竞购问题等等“此起彼伏”、北京和华盛顿在政治、经济上“怒目相视”的同时，我们也注意到双方高层会晤的画面、是频频出现在电视镜头里。

之前，美国副国务卿佐立克跑到北京、启动了中美战略对话机制。当然了，在此，东方评论员觉得有很必要澄清一下，那就是这个“中美战略对话机制”的提法“是北京的口径”，而我们也注意到，按美国官方的口径、佐立克此次北京之行、是与中国举行“高层对话机制”、而没有“战略”两字。

*** “战略对话机制”与“高级对话机制”赋与了意识形态般的感情色彩

众所周知，在美国官方的“字典”里，所谓“战略对话机制”是指与盟友间的对话机制，显然，华盛顿的官僚体系将“战略对话机制”与“高级对话机制”赋与了意识形态般的感情色彩。

那么，北京自称佐立克来是启动“中美战略对话机制”、这是在往自己脸上贴金吗？当然不是，在东方评论员看来，向来注意细节的中国政府是不会这样做的。我们注意到，美国国务院发言人在新闻发布会上虽然“强调”中美是在进行“高层对话”、但并没有明示、或暗示北京的说法有什么不对，看来，就中美是启动“战略对话机制”还是“高层对话机制”的问题上，北京和华盛顿显然有某种默契、那就是“说法不同、意思一样”、对此，有人就认为，华盛顿这样做也许是想避免在联合国改革问题上刚刚被美国人“出卖”的“日本盟友”更没有面子。

中国有句老话，叫做“不打不相识”，在东方评论员看来，用这句话来形容中美的这半年来、特别是的这两个月来的“你来我往”是再合适不过的了。


*** 美国决策层从各个层面给北京做了一次全面的“综合评估”

在我们看来，在过去的几个月中、美国决策层可以说动员了“可以动员的一切资源”、从各个层面给北京做了一次迄今以来最为全面的“综合评估”。在东方评论员看来，这种“综合评估”不仅包括中国的政治、军事、经济力量、甚至也包括中国是否敢于使用这些力量的决心、和如何使用这些力量的灵活度与策略。

东方评论员认为，华盛顿用到的“评估理论”就是“中国威胁论”。而相应的“评估参数”就是一些极具代表性的具体国家、和政治经济实体，比如东盟中的越南、东亚安全框架中的日本、处于亚欧中心战略位置的印度、西方文化体系的欧洲、相应的“评估方式”就是用这些国家、或实体一些核心利益、去极力拉拢它们、利用它们的一已私心、再加上美国的实力、相互交换利益，这些国家、实体“想得到的东西”是“各有侧重”，但是华盛顿想要的似乎就只有一个、那就是“与美国联手”挤压中国。


*** 过去几个月，中美之间上演了一场世界范围的、不见硝烟的攻防战

结果是，针对美国以“中国威胁论”为“总纲”、借用将一份本应该在3月出版的“中国军力报告”、有意识地“一推再推”、直到7月份才正式公布的策略，辅之以华盛顿决策层娴熟操纵、引导媒体的技巧，通过“吹、拉、弹、唱”的手法、先后让“中国军事威胁论”、“中国经济威胁论”等具体理论轮番上场，而期间，中美之间也随之上演了一场世界范围的、不见硝烟的攻防战。


*** 针对美国拉拢的东盟阵营的越南，北京是不动声色

针对东盟这个美国推销“中国军事威胁论”的“主要市场”、拉拢的东盟阵营的越南，北京是不动声色，通过加大对湄公河流域的经济介入，从侧面牵制越南，从而让越南“晓以利害”、在对越南施加压力的同时，北京不仅没有损害中国与东盟之间的关系、也没有让东盟感受到“中国威胁论”事实根据何在。


*** 军事上，北京“连带狗主人一起打”的气势硬是暂压下了小泉冒险的决心

对东亚安全框架内的日本，它与美国一样，不仅是中国威胁论的接受者、更是中国威胁论的鼓吹者，对这样的角色，北京还就要真实地威胁一下：在我们看来，北京针对日本的手法、可以说是相当地强硬，具体而言主要是采用军事高压，手段之一就是让中国军方将领发了一则震惊世界的、“准备核打击美国”公开警告、结果是通过这种“连带狗主人一起打”的气势、硬是暂时压下了小泉纯一郎准备在东海油气问题上冒险一试的决心。


*** 北京一点也不给华盛顿“模糊的空间”

另外，针对华盛顿用一些个不切实际的、“军事打击中国的计划”不停曝光的策略、来作为日本进一步挑衅北京“撑腰打气”的手段，北京的的反击也“非常干净利落”、一点儿也不给美国人“解释的模糊空间”：即，通过中国军方的一个身份特殊的将军、以“个人观点”公开警告华盛顿、不排除中国率先对美国进行核打击的可能性，并明言“美国得准备几百个城市被摧毁”。

事实上，以及指望靠美国撑腰、继续挑衅北京的日本和台独，在看到自己的“后台”、不可一世的美国人、都被中国用毁灭性的打击力量、“真实地威胁着”的时候，其内心是如何想的、恐怕从日本小泉政府的高官狂言“在日本企业东海开发油气资源的安全问题上”、日本“在军事上有许多选择”之后、却“多日按兵不动”的事实中、就可以清楚地显示出来。


*** 让华盛顿意外的是：北京的策略完全变了

至于华盛顿自己、本想是抛出“中国军事威胁论”之后，慢慢地同北京玩“猫捉老鼠”的游戏、即、华盛顿等着北京向过去一样、去耐心、努力地化解“中国军事威胁论”对周边国家的影响，而自己则在北京化解的过程、不停地找机会、去制造新的难题。

然而，让华盛顿意外的是，北京的策略完全变了。在东方评论员看来，“中国准备核打击美国”这个“没有任何解释空间”的公开警告、本身就是在“从源头上”对美国的计划进行反击、是对“中国军事威胁论”炮制者的最强硬的回击。如此一来，谁都明白、五角大楼之所以如此高调地贩卖“中国军事威胁论”也难怪，因为中国现在还真有实力对美国进行“毁灭性的威胁”。


*** 所谓“中国威胁论”的“核心要义”是什么？

我们知道、随着苏联作为一个超级大国解体、而导致冷战的结束、更加上美国在经济上、用汇率武器狠狠地修理了日本，打掉了日本在经济上的咄咄逼人之后，战后第一次没有了政治、军事、经济对手的美国、就立刻抛出了“中国威胁论”。

事实上，“中国威胁论”是以冷战思维为理论基础的、但却绝对是冷战后的产物。在我们的记忆中、“中国威胁论”的第一次见诸报端、就是在1992年,当时、美国的一个名叫芒罗的战略专家、在报纸上发表了篇名为“真正的威胁来自亚洲中国”的文章，从而标志着美国保守势力正式推出“中国威胁论”。

不知是巧合、还是有意安排，另一个充满冷战色彩的著名理论--“文明的冲突”也在此时由哈佛大学教授亨廷顿同时推出。我们注意到，芒罗用“中国威胁论”推导出的结论、是“美国与中国必有一战”，而亨廷顿的“文明的冲突”也断言“西方文明将遭遇儒家文明这个天敌”。



*** 中国主动“帮美国挑明”所谓“中国威胁论”之“核心要义”的意图何在？


显然，既然北京现在以“中国准备核打击美国、毁灭美国”、这种“无以复加的威胁”帮美国人挑明“中国威胁论”的理论、就是建立在“中美对抗”、即中国“准备威胁太平洋对岸的美国”、准备驱逐美国在西太平洋利益之基础上的，那么，美国准备在之后一一展开的、针对中国可以军事威胁东南亚、南亚的“宣传战略”、也就“非常多余”了。


*** 美国人开始承认与中国发生军事冲突，那可是要“拿美国本土做赌注的”

在我们看来，也正是中国军方这种“直言不讳”的“最强烈警告”、让美国官员和新闻媒体在暴跳如雷之余，似乎都开始慢慢习惯去面对现实、开始承认中国对美国的毁灭能力、开始承认美国与中国发生军事冲突，那可是要“拿美国本土做赌注的”。

东方评论员认为，在这一点上，前美国驻北京使馆武官麦利凯的态度就非常说明问题，他说：“以中国的核武战力，中国有可能在遭受攻击时对美国发动（核）攻击的”。


*** 北京还毫不掩饰自己有排除“非亚洲国家”（美国）参与东亚事务的意图

另外，还有一个值得注意的信号，就是中国外长李肇星没有参加今年的、有“非亚洲国家”（特别是美国）参加的“东盟区域论坛部长级”的年度会议，但却非常认真地与“东盟”十个国家的外交部长“捉对”分别举行了“会外会”，我们还注意到，李外长也非常认真地参加了“东盟10+3”会议。

对此，东方评论员认为，这充分显示北京有意与华盛顿“针锋相对”、毫不掩饰自己有排除“非亚洲国家”（可以说是专指美国）参与东盟（东亚）事务的意图。

显然，北京的这种“毫不掩饰”、也是在一点儿也不给美国人“解释的模糊空间”。


*** 再次强调我们的一个观点

到此为止，可以说美国再次抛出“中国威胁论”并身体力行“加以论证”的后果、对中美双方都是严重的。如果您一直在关注《东方时事解读》，相信您对我们针对拉姆斯菲尔德先生在新加坡试探性抛出“中国军事威胁论”时，所下的一个结论“应该有所记忆”，那就是：别的国家、包括日本都可以“认真地说”“中国威胁论”、并将其确立为“国策”、唯独美国不行。

事实上，让美国开口说“中国威胁论”、并确立为国策、正是日本人最想做的一件事。东方评论员认为，但是，美国对日本有极大的警惕，心里非常清楚日本的心里不过审在企盼“中美全面对抗”，先借美国的力量把中国削弱、同时也借中国的力量把美国削弱、只有这样，美国才不得不放松对日本自卫队的限制，日本才有“全面发展”本国军事力量的机会，显然，策动美国将“中国威胁论”确立为国策、并加以身体力行，从而激起北京对华盛顿的全力反击，正是为了这一战略目的。


*** 华盛顿在东亚搞事的原则就是“在中日关系彻底破裂之前、绝不能让中美关系破裂”

其实，当初日本人之所以同意将台湾纳入美日安保战略目标，将“中国威胁论”写入“条约”、就是日本的条件之一，只是最后被华盛顿耍了而已。因为美国对日本人的这一企图也是了如指掌，因此华盛顿决策层拟定其东亚政策、在东亚搞事的原则就是“在中日关系彻底破裂之前、绝不能让中美关系破裂”。

然而，在2月份、“半推半就”的日本被美国“耍进了”“协防台湾”的美日军事同盟之后，中日关系是急剧恶化，日本执政的保守势力的地位在内部开始不稳，而为了保住自己的政治地位，日本保守势力更是力推“民粹牌”、为了取得突破、也抄起了“台湾牌”、意图换取北京在历史问题上、入常问题让步，从而成为日本保守势力的两大政绩、而稳住阵脚。


不过、北京对日本保守势力的反击力度已经是众所周知的了：先是强调靖国神社问题是中日关系的“症结”，绝不让步、并策略地将日本的历史问题“世界化”，引发了一轮对日本历史问题的国际大批判；随后、不仅公开对日本“入常”说不、还在联合国率先狙击“四国提案”、并团结亚洲另一个大国--韩国、一起为反对“四国提案”的“咖啡俱乐部”提供全面的支持。

到了4月份，小泉纯一郎终于决定在东海问题上一搏，抛出核准日本企业开发东海油气资源许可证的问题、结果却引来北京“极其严重的警告”、声称这将引起“事情（中日关系）性质上的变化”。

与此同时，中国国内“恰到好处地”爆发了“反日游行”、许多日本企业在华业务受到严重影响，这反过来引发了日本经济界对小泉政府的不满、在北京打退了日本外相町村信孝“兴师问罪”的北京之行的气势之后，小泉纯一郎终于在几天之后的、在印尼举行的亚非首脑峰会上面对国际社会、就其侵略历史做出了“心不甘情不愿”的“公开道谦”。


*** 华盛顿何以在在4月份之后才加大媒体炒作“中国威胁论”的力度？

东方评论员注意到，事实上也是在这前后，美国五角大楼的、在3月份就已经完成的05年度《中国军力报告》、开始被五角大楼有意曝光、从而被媒体“广为注意”，有关报告中是否有“中国威胁论”的“猜测”开始成为新闻焦点，美国政府在时隔近10年之后，再次开始了“中国威胁论”的“认真论证”，在东方评论员看来，华盛顿借媒体炒作“中国威胁论”有两个目的，第一，是最重要的，是坚强小泉纯一郎的“决心”、策应日本保守势力继续引导日本社会右倾化、从面稳住日本保守势力的执政基础，继续诱导中日关系走向破裂、而这是美国对中国狂打日本牌、“全面破坏”中国力推的、东亚经济一体化、将美国势力逐出东亚的最好保证。

第二，就是想借“中国威胁论”的“论证过程”、对中国的“综合能力”进行全面评估。

然而，就如我们多次强调的那样，别的国家、包括日本都可以“认真地说”“中国威胁论”、并将其确立为“国策”、唯独美国不行。


*** “较量”对双方造成的困难、果真被我们言中了

为什么？其原因也如我们当时所说的那样：因为“美国需要照看的”是全球各处的利益、一旦如此，华盛顿必然遭到北京的全力反击，其结果就是美国的全球利益都将受到来自中国因素的冲击、并付出巨大的代价、尽管中国也将为此付出不菲代价、其中、中日关系几乎到了没有弹性的地步、就是其中之一、还有，为了分解欧美联手、在经济上施加压力、人民币也“被迫”突然升值。不幸的是，中美之间的这场空前激烈的较量、以及“较量”对双方造成的困难、果真被我们言中了。

大家看看美国全力推动的、对以色列有利的“巴以和平”、“已经进行到了”接近与欧盟在伊拉克政治重建问题上“做利益交换”的关键时刻、却突然遇到了麻烦。对此，东方评论员认为，美国人借机私下指责“中俄不再合作”是重要原因之一、是有可能的，在我们看来，“巴以问题”、更多地是欧美利益交换的一个筹码，对“中俄”好处不大，北京和莫斯科又何苦去花气力、做工作、“帮忙维持秩序”呢？但是，以色列竟然也在伦敦“77爆炸案”后，一度将“炸药”的产地说成是“来自中国”、而将矛头指向北京、尽管他们拿不出证据、但这种指责的“意图”却是不言而喻的；

还有，在东方评论员看来，美国国防部长拉姆斯菲尔德在新加坡抛出“中国军事威胁论”时、可能说什么也没有想到不久之后、他自己就得为美军在中亚军事基地的前途、拖着一个上了年纪身体、却还得“万里奔波”、还得揣着“支票簿”去对俄罗斯和中亚各国“说好话”；

当然了，在东方评论员看来，堂堂的“世界老大”今天却在其“不耐烦的盟友”--韩国的逼迫下、在“六方会谈框架下”幌子下、靠着“六方”彼此都将“捉对会谈”这块遮羞布、“自食其言”地与朝鲜举行之前一直不肯屈就的“双边会谈”、可以说更是“不堪入目”。



*** 中美都清楚，双方之间全面对抗，那地球上事情就成了谁也无法预料的了

事实上，直到目前为止，中国还没有摊牌，拿美军的中亚军事基地“说事儿”不过是反击中的一个，而北京在中亚动手后、却又应韩国之意“全力斡旋”、“说服”朝鲜重返“六方会谈”、只要华盛顿愿意对朝鲜让步、保留一个“说不清是民用还是军用”的核设施、“朝核问题”倒也有可能成为中美间、以另一种方式“重新合作”的开始。

显然，如北京在中亚的反击手段还算不得摊牌相类似，美国对“中国威胁论”的“论证”也还算不得摊牌，由于欧盟、俄罗斯、以及日本的存在，美国也不可能现在就同中国摊牌，美国现在也不可能以其全部的力量来压制中国。

然而，东方评论员认为，在北京的反击下，华盛顿应该已经清楚，如果美国逼迫中国成为其对手，中美之间就会全面对抗，那地球上事情就成了谁也无法预料的了。


*** 吴邦国委员长的“语重心长”

在我们看来，显然，北京的多面反击，却也正是美国副国务卿佐立克到北京、启动“中美战略对话机制”、防止中美关系、“在中日关系破裂之前”就走向失控的“大背景”。

对此，首席评论员就指出，在北京以这连串的“非常干净利落”、一点儿也不给美国人“模糊空间”的“反击”下，今天，吴邦国委员长才能当着美国国会众议院议长哈斯特德的面、去“语重心长”说“无论是对美国，还是对世界，中国都不是威胁，而是机遇”。在我们看来，华盛顿对这些向来是“听不懂”的，但是、从华盛顿近来的反应来看，对北京的反击却是“看得懂”的。

下面，我们再来看一则美国媒体对这次中美高层对话的分析、之后，东方评论员还将回到这个问题、对吴邦国委员长的“语重心长”再说几句。


《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
