# -*- org -*-

# Time-stamp: <2011-08-04 12:57:50 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 2005年8月19日 星期五


  

** 日石油公司：因安全问题近期不会钻探东海油气




【中新网8月19日电】据日本共同社报道，日本帝国石油公司经理高井17日表示，由于存在安全问题，该公司不可能很快在东海海域进行油气试钻探。

高井称，在9月之前进行钻探非常困难。

据报道，关于东海天然气田开发一事，日本政府打算与中方尽早恢复协商。

围绕中日两国存在争执的东海油气田的开采问题，日本九州经济产业局局长松井哲夫在9日的记者会上宣布，被授予试开采权的帝国石油公司已经交付了约1000万日元的执照登记税，已全部办妥了试开采权相关的各种手续。

此前，7月14日，日本经济产业省正式宣布授予日本帝国石油公司在东海中国专属经济区的天然气田试开采权，并给这些气田起了日本名称。中国对此表示“严重关切”。


【时事点评】我们注意到，日本帝国石油公司是以“存在安全问题”、而透露“该公司不可能很快在东海海域进行油气试钻探”的，另外，我们也注意到，那位日本帝国石油公司的管理人士还提到一个敏感的时间，即“在9月之前进行钻探非常困难”。

*** 该公司在表明“不可能很快试钻探”原因的问题上、还是“比较老实”的

在我们看来，该公司在表明“不可能很快在东海海域进行油气试钻探”原因的问题上、还是“比较老实”的，我们也认为这的确是个“安全问题”、因为它本来就“不存在任何技术上的问题”。

根据我们的资料，这个被日本政府授予东海勘探权的日本帝国石油公司、在所谓“日中中间线”附近的3个区块上、获得了所谓的“勘探权”，面积共计400平方公里，其位置就位于中国正在加紧建设、且即将投产的春晓和断桥油气田南侧。

*** 日本人在“故意出错”

之前，东方评论员注意到，按日本方面特意制作的、东海有争议区域“日本暂定矿区分布图”来看，我们可以清楚地看到，日本帝国石油与其他公司的开发区块“都紧紧地贴着”所谓的“中间线”，在东方评论员看来、特别值得注意的是，帝国石油的“勘探区块”甚至还向西越过了日本单方面划定的“中间线”，显然，日本人这是在“故意出错”。

*** 日本保守政府的“这一故意举动”主要有两层企图心

对此，东方评论员就认为，日本保守政府的“这一故意举动”主要有两层企图心，第一，这本身就是在故意挑衅北京的“忍耐度”、极具挑衅性；第二，我们认为，日本之所以将帝国石油公司的“勘探区块”紧贴着中国准备投产的春晓油气田、除去别的因素，在技术上这也明显是种“投机取巧”。


*** 日本人认为，只要在春晓油气田附近，不论在哪里打井、准保都能打出油来

非常清楚，由于日本一直拿不出任何有价值的东海海底地质勘探资料、而春晓油气田距离所谓中间线仅仅只有5公里，因此、在日本人看来，只要尽可能地“贴着”中国已经建设、且就要投产的春晓油气田、对没有相关地质勘探资料的日本公司而言，也就省去了勘探的费用。不难想像，只要在春晓油气田附近，不论在哪里打井、准保都能打出油来。

在东方评论员看来，可以肯定的是，在“东海海域进行油气试钻探”的问题上，日本手上没有的、在而向中国索要却又未果的“海底油气资料”、也不是让该公司“在9月之前进行钻探非常困难”的因素。


*** 日企唯一“不可能试钻探”的原因，就是日本政府没有从中国政府这里取得“许可证”


对此，东方评论员认为，在日本帝国石油公司成功地拿到日本政府的“勘探许可证”后、唯一“不可能很快在东海海域进行油气试钻探”的原因、就是日本政府没有从中国政府这里取得“许可证”。

在我们看来，不论日本经济产业大臣中川昭一事先如何强硬、“将话说得如何满”、甚至声称“在保证日本企业安全上、日本有多种选择、甚至军事选择”，然而，事实上，直到目前为目，日本人野心勃勃的东海开发计划“仍然停留在嘴巴上”、终究没敢迈出最关键、也是最具爆炸性的一步。


*** 帝国石油坦承担心“真正开始勘探的时候，中国肯定会找日本的麻烦”

东方评论员认为，日本帝国石油公司的官员就亲口将日本政府的“真实心态”描绘得“非常到位”，我们注意到，他的观点主要有两点，第一，担心“真正开始勘探的时候，中国肯定会找日本的麻烦”、这就是所谓的“安全问题”，显然，这是日本帝国石油公司担心的“外部因素”；

第二，坦承“今后是否真正进行勘探，政府还将和帝国石油进行慎重商议”、显然，在我们看来，这是所谓的“时机问题”、是该公司“在9月之前进行钻探非常困难”的“内部因素”。不难看出，没有“安全”哪来的“时机”。


*** 声称“在目前情况下、绝不会考虑与中国共同开发的”日本经济产业大臣“突然变脸”

另外，就我们得到的消息，先前声称“在目前情况下、绝不会考虑与中国共同开发的”日本经济产业大臣中川昭一、在以“8月15日有内阁会议”、而特意抢在“日本投降日”前一天公开参拜靖国神社之后、又突然“变脸”，对新闻界“改称”：“我并未排除进行共同开发的可能性。”


*** “强迫”中川昭一的突然“变脸”的可能性只有两种

显然，我们认为，“强迫”中川昭一的突然“变脸”的可能性只有两种：首先，是中国做出了实质性让步。但是，东方评论员认为这种可能性不存在，因为在东海问题上，由于日本早已经将其“没有道理的要求”摆明、其要求主要是两条：第一条在我们看来，那根本就是在直接挑战中国的底线、即在有争议区域、日本坚持要由日本自己独家开发、不与中国进行任何形式的合作，明眼人一看就知：这实际上是要求在有争议区域、单方面的强行行使主权；


*** 日本提出种种“无理要求”的“本来目的”

第二条实际上是一条陷井、即要求中国“对等停止”春晓油气田的开发工程、以此作为日本不单独开发有争议海域的前提条件。由于春晓油气田位于没有任何争议的区域内、日本之所以提出这种“无理要求”、就在于其本来目的就是要在东海主权问题上“蓄意挑衅北京”、以中日关系可能破裂作为赌注、赌希望继续保持经济发展势头的北京会继续“顾全大局”、从而迫使北京默认那条所谓的中间线、达到其“策应”现在为日本实际控制之下的钓鱼岛问题。


*** 按照日本“中间线”的划法，中国的钓鱼岛也就“自然而然地成了日本的领土”

东方评论员认为，非常值得警惕的是，这条所谓的“中间线”、本来就是在日本硬性将钓鱼岛主权划日本的基础上、才能够“划拉”出来的。问题的核心在于：按照日本所谓“中间线”的划法，中国在钓鱼岛的海域、就得朝向中国方向“退进”数十海里，如此一来，包括钓鱼岛在内的所有海域，都将在日本的“排他性经济水域”和“大陆架”之内，如此一来，中国的钓鱼岛也就“自然而然地变成了日本的永久领土”。


*** 日本若果真敢“靠实力、拿性命”来拼中国、恐怕占不了上风

由此可见，日本强行开发东海油气资源，其主要意图是一边动手抢夺了东海“现实的经济利益”，一边还用眼睛死死地盯着钓鱼岛的主权归属、在我们看来，日本人的算盘“不可谓之为不精”、只是这“一箭双雕”的策略太过于一厢情愿了，要将“图纸”变成现实、将“如此重大的一坨国家利益”抢到手、那是得“靠实力、拿性命”去拼的。

然而、就现在的中国而言、综合政治、军事、经济三方面的“综合实力”、已经在日本之上，不然，欧盟、俄罗斯、印度在找战略合作对象、以制衡美国时、断不会都千篇一律地“全盯上了中国”。显然，日本若果真敢“靠实力、拿性命”来拼中国、恐怕占不了上风。


*** 在这种原则问题上，北京根本就“无步可让”


不难看出，钓鱼岛主权又直接牵扯到台湾主权问题、因此，在东方评论员的眼里，东海主权争端的本质绝不仅仅是个东海油气资源开发与否的问题、而是一个事关东海、钓鱼岛、台湾一系列主权的核心利益。在这种原则问题上，北京根本就“无步可让”。


*** 一旦日本将上述设想付诸实践，本质就是一场拿日本国家、民族之前途做赌注的豪赌

因此，说白了，一旦日本将上述设想付诸实践，在东海、钓鱼岛问题上“越过”北京的底线，那么、其“实践”的本质就是一场豪赌、一场拿日本国家、民族之前途做赌注的豪赌。

东方评论员认为，正因为东海问题是如此地“牵一发而动全身”、所以、自小泉政府于7月14日正式授予帝国石油公司在东海争议海域的试开采权后，日本保守势力在挑战中国主权利益方面迈出的“极其危险的一步”：可以说中日关系真正进入了的“雷区”、也可以说日本保守势力“再向前哪怕是试一步”、比如让日本公司的探测船开到有争议区域进行开采活动、那都必将造成中日之间的种种“不堪设想”、在我们看来、最后恐怕什么样的恶果都是日本人可能面对的。


*** 日本的“突然变脸”也就只有另外一种可能

我们认为，既然按日本“先前摆明的立场”中国是“无步可让”，那么，日本的突然变脸也就只有另一种可能、即：小泉政府在各种压力下、暂时从先前的强硬立场退了一步，这就如那位向来强硬的中川昭一代表日本政府所说的那样，“我并未排除进行共同开发的可能性。”

然而，种种迹象表明，小泉纯一郎的这种“暂时性退步”更多地是种策略，其中，一个重要考虑就是9月份的大选。

在我们继续讨论这个问题之前，再来看一则光明日报的一篇时评。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com



** 光明日报时评：战后六十周年日本走到十字路口



　　【光明日报8月19日文章】60年前的8月15日，日本天皇裕仁发表“终战诏书”，宣布日本无条件投降，深陷于日本军国主义铁蹄之下的亚洲各国终获解放。60年后的今天，中、韩等亚洲国家的人民却在为日本领导人是否会去参拜供奉着当年那些甲等战犯的靖国神社、为侵略者招魂翻案保持警惕。那场史无前例的残酷战争已经过去了60年，当年挑起战争并最终惨败、无条件投降的日本如今走到了一个新的十字路口。

　　*** 小泉顾及内外而放弃参拜

　　近年来，以首相小泉连年参拜靖国神社为标志，日本政府在历史认识问题上出现持续倒退，日本与中、韩等亚洲邻国的政治关系也进入了所谓的“冰冻期”。因为今年是二战结束60周年，所以日本内外高度关注着小泉是否会再次参拜以及会不会选择8月15日前往靖国神社参拜。由于靖国神社供奉着在战争中罪恶累累的甲级战犯的亡灵，并宣扬着一种美化战争、否定侵略的历史观，因此是否参拜靖国神社也就成了检验日本政治领导人历史认识的一个主要标准。

　　小泉首相最终没有敢接受右翼保守势力的鼓动，在今年8月15日前往靖国神社参拜，而是发表了一份要反省战争走和平之路的战后60周年首相谈话。尽管有评论认为小泉谈话与10年前的村山谈话相比在内容上有局部倒退，但小泉在谈话中明确表示对过去的殖民统治和侵略战争表示反省和道歉，日本今后将坚持走和平之路，同各国发展友好信赖关系，因此对谈话内容本身国际社会还是给予了相应的肯定，国际社会包括日本舆论强调重在小泉的行动，而不是看他说什么，关键在做什么。

　　日本媒体认为，小泉放弃在战后60周年的8·15参拜靖国神社并发表有积极意义的首相谈话，主要是为了赢得即将举行的众议院大选以及打开与中韩两国关系的僵局。小泉为顺利推行自己所主导的邮政改革，于本月8日解散了众议院并引起自民党的局部分裂，在当前有半数日本民众以及共同执政的公明党反对参拜的情况下，小泉最终回避了在8·15前去参拜。而冷却的日中、日韩关系不仅不符合日本的国家利益，还使在野党抓住了小泉在外交上失败的把柄，可以说小泉谈话释放出了改善日中与日韩关系的意愿，但也充满了现实的考量。不少日本政治家也表示希望小泉首相能够切实履行谈话内容，用实际行动表达对历史的真诚反省。

　　*** 靖国神社迎来20万人参拜

　　虽然靖国神社在日本战败60周年纪念日8·15这一天没有等到首相小泉的参拜，但却接待了有史以来最多的参拜客——20.5万人。当然，这20万人里有不少是为了悼念当年被迫走上战场而丧失性命的先人。但小泉内阁的环境大臣小池百合子和厚生劳动大臣尾辻秀久、日本自民党干事长代理安倍晋三和东京都知事石原慎太郎以及另外近50名参议员和前众议员也都在当天前来参拜。他们作为日本的政府高官或政界要人，故意挑选在8月15日战败纪念日这一天高调参拜，不能不让人觉得他们是在替靖国神社及其所代表的历史观撑腰打气。

　　8月15日的靖国神社尽管烈日炎炎，但日本保守势力在这里的激情表演并没有受到丝毫影响。当天有日本青年穿着当年“皇军”的军服列队行进，有社会团体举行集会呼吁天皇及首相前来参拜，甚至还有人在贩卖战前每个日本学生都须背诵的皇国思想材料“教育勅語”。某海外媒体在报道中称当天的靖国神社是人山人海，该媒体记者多次在8·15采访靖国神社，但是还是第一次看到这样的“盛况”，报道还指出在长长的参拜队伍中，竟有不少不到20岁的年轻人。

　　作秀靖国神社仅仅是日本社会趋于保守化的一个表现。现在日本大批的右翼学者在报纸及杂志上鼓吹当年日本发动战争是迫于自卫，中韩等国批评小泉参拜靖国神社是为了用历史问题牵制日本。甚至连日本政府高官都会经常“失言”来替甲级战犯辩护。在书店里，污蔑和诋毁中韩等国的书刊杂志大行其道，而由极端保守人士编撰的新历史教科书更是获得日本政府的审批而逐渐走向课堂。在这样的环境之中，已经有越来越多日本年轻人对当年的侵略战争产生了错误的认识，对中韩等国也开始抱有抵触情绪。

　　*** 和平力量的不屈抗争

　　尽管日本社会整体趋于要通过否认历史建立新的国家观，但仍有不少进步力量和正义人士在为日本坚持走和平道路而奋力抗争。就在8月15日靖国神社内进行着各种表演的同时，多个社会团体也于当天举行各种集会和游行，反对参拜靖国神社以及呼吁保护和平宪法。日本“和平遗族会全国联络会”的代表西川重则在当天集会上表示：“靖国神社曾是军国主义的精神支柱。政教分离的原则能够表明不再重蹈侵略亚洲这一覆辙的决心。我们要求首相中止参拜靖国神社，决不原谅参拜行为。”

　　而在最近一系列有关战后60周年的研讨会中，也有不少富于历史正义感的日本学者认真地对当年日本走上军国主义侵略之路进行了深刻的反思。他们在平常也一直对抗着试图美化战争、否定侵略的保守势力，并积极向日本民众指出那场侵略战争的残酷性以及日本社会目前所抱有错误历史认识的危险性。一位日本作家看到书店里批判中韩等邻国的书之后称“太过分了，只看题目就可发现书中竟堂而皇之地使用诽谤和侮辱对方的措辞，我对这样的情感将演变成何种状况感到恐惧。”为此，他于近期同时出版了两本关于战争的新书，希望能够让日本的年轻人正确认识60年前的那段历史。

　　当前的日本，有人认为首相不应该参拜供奉有二战甲级战犯亡灵的靖国神社，也有人认为侵略有理、战犯无罪，因此包括首相及天皇在内的日本人都应该参拜靖国神社。有人主张日本应该对当年遭受战争伤害的中韩人民表示道歉，实现与亚洲邻国的和解与共同发展，也有人认为只要有牢固的日美同盟就够了，对中韩等国无须总是认错，而应该堂堂地提出自己的主张。日本在经历了战败60年后的今天，走到了国家发展的一个十字路口，今后是坚持走和平发展道路，还是集体向右转重温当年发动“大东亚战争”时的荣光，国际社会将拭目以待。



【时事点评】在东方评论员看来，《光明日报》驻东京记者的这篇文章比较好地描绘了日本政治的真实情况，即日本政治在整体上正在“趋于保守化”、日本社会在整体也正在“要通过否认历史、建立新的国家观”的危险方向上“疾走”。

*** 日本社会最看重的日本的经济问题、而不是什么“对外关系”、更不是什么“道德、良知”问题

我们认为，也正是有这种社会背景，尽管将中日关系、韩日关系搞得一团糟，小泉纯一郎在解散国会后、短短的几天里、原本“里里外外不是人”的小泉、却因“锐意”改革邮政系统而突然人气飙升。

在东方评论员看来，由于邮政系统改革总体上对日本经济是有利的、因此，尽管当前有半数日本民众反对小泉参拜靖国神社、但是小泉纯一郎的支持率却仍然是摆脱了中日、韩日关系、以靖国神社问题的影响、而立刻开始攀升。

在东方评论员看来，日本社会一边反对小泉参拜靖国神社、一边又将“支持率”给了小泉、这一“说怪也不怪”的事实充分证明日本社会“总体上”对小泉纯一郎的错误历史观“并不以为然”，也充分地说明了日本社会更看重日本的经济问题、而不是什么对外关系问题、更不是什么“道德、良知”问题。


*** 真正能触动日本社会神经的只能是经济层面的东西

因此，在东方评论员看来，北京必须充分认识到日本社会这种对历史问题“不加反省”、在“历史认识”上与国际社会所希望的“有根本偏差”的现实。

显然，对日本社会这一现实，任何“外在的”道德劝说、与单纯的外交政治压力、都很难“直接触动”日本社会的内在神经。我们认为，真正给触动日本社会神经的只能是经济层面的东西，也就是说，真正能让促进日本社会反省历史的、也只能是经济问题。

当然、日本社会对经济的重视、也正是小泉政府为配合对华强硬外交、一再警告投资中国有风险、而日本企业仍然不顾警告、义无反顾地继续将市场庞大的中国视为投资“当然选择”的主要原因。


*** 对小泉纯一郎的“功利”心态，文章给出了准确的描述

据我们了解，自解散国会后、在8月15日之前，一个星期的时间里、小泉纯一郎的支持率就已经上升至近50%，这的确让背水一搏的小泉纯一郎欣喜不已，显然，这一支持率如果能够保持到9月11日，那么，小泉纯一郎在继上次解散国会“赌赢”头一把之后、这次极有可能“重温旧梦”。

然而，支持率的上升、反而让小泉纯一郎对日本右翼要求他兑现几年前上台时许下的、“在8月15日参拜靖国神社”的诺言开始犹豫不决：显然，在重大的现实利益面前，他所一再坚称的“个人信念”根本就不足挂齿。

对小泉纯一郎这一“功利”心态，文章给出了准确的描述。请大家注意这一段，原文是：日本媒体认为，小泉放弃在战后60周年的8·15参拜靖国神社并发表有积极意义的首相谈话，主要是为了赢得即将举行的众议院大选以及打开与中韩两国关系的僵局。小泉为顺利推行自己所主导的邮政改革，于本月8日解散了众议院并引起自民党的局部分裂，在当前有半数日本民众以及共同执政的公明党反对参拜的情况下，小泉最终回避了在8·15前去参拜。而冷却的日中、日韩关系不仅不符合日本的国家利益，还使在野党抓住了小泉在外交上失败的把柄，可以说小泉谈话释放出了改善日中与日韩关系的意愿，但也充满了现实的考量。


*** 小泉纯一郎眼下最大的现实利益、就是赢得9月份的大选

显然，在东方评论员看来，小泉纯一郎眼下最大的现实利益、就是赢得9月份的大选、因此、所谓“现实的考量”，就是尽最大可能维持目前正在上升的“支持率”。

之前，在国际社会的眼里，东海事实上已经成了中日关系的“火药桶”、也成了东亚稳定的“火药桶”，因此，方方面面对获得小泉政府“授予”试开采权的帝国石油公司，是否不惧成为中日之间的“导火索”，真的能够进军东海、是“倍加关注”。

就目前来看，还好，直到今天为止，支持率上升的小泉纯一郎、暂时没有敢亲手点燃这根自己埋下的“导火索”，这样、已经到了“临爆点”的中日关系也就还能“暂时维持着”。

不过，东方评论员认为，现在离日本大选还有近20天、这中间会发生什么事“只有天知道”，在我们看来，北京仍然要保持足够的警惕、警惕视赢得大选为眼下最大利益的小泉、一旦感觉没有把握赢得大选、那么，他极有可能再次变脸、将“日本打算与中方尽早恢复协商”的所谓善意再次扔到一边、仍然极有可能在东海问题上挺而走险。

下面，我们将把关注的焦点转向朝鲜半岛。与昨天一样，我们打算继续结合中俄联合军演来展开相关讨论。在一则中俄联合军演的最新消息后，东方时事评论员、军事评论员将一起给出我们的观点。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
