# -*- org -*-

# Time-stamp: <2011-08-04 13:05:22 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

*  2005年8月24日  星期三




** 发生这样不可思议的事情，全拜欧盟错误的对华贸易政策所赐




【国际在线报道】欧盟气势逼人，其实没有本钱对华打纺织品贸易战。它不掌握中欧纺织品贸易的详实数字，结果作茧自缚；而其内部的意见分歧和利益区别，必然使它在关键时刻做出妥协。

夏末秋初，凉风渐起，正是服装换季销售的大好时机。然而，欧盟的服装零售商和进口商却只能面对空空的货架，忧心如焚。原来，8月中旬以来，欧盟对中国部分纺织品人为设置的出口配额已经用完，数以千万计的中国羊毛衫和长裤被阻拦在欧洲各大港口无法清关。

发生这样不可思议的事情，全拜欧盟委员会错误的对华贸易政策所赐。

在1月1日全球纺织品贸易配额取消之后，中国价廉物美的服装按理说可以更方便地销往世界各地，这对消费者来说是一个福音。欧盟各国的进口商因此纷纷增加了对中国的定单，准备大干一场。然而，就在此时，欧盟委员会突然宣布要对中国纺织品和服装进行特保调查，并以进行贸易报复相要挟，要求对中国10类纺织品重新实行配额限制。

这一做法明显违背了世界贸易组织自由贸易的原则，是一种贸易保护主义政策。对此，中国政府一方面据理力争，另一方面出于维护中欧贸易大局的考虑，做出了适当让步。双方于6月达成妥协，规定了10种中国纺织品的限额。

欧委会之所以采取咄咄逼人的姿态，显然是受到了部分成员国的压力。这些国家在取消纺织品贸易配额制度之前的10年过渡期期间，不注意引导本国纺织企业调整产品结构、提高产品档次、增强竞争力，结果在配额取消后，面对中国企业的市场竞争一时慌了手脚。为了保护本国的纺织企业，它们就利用在欧盟内部强大的影响力，推动欧委会启动对中国纺织品的特保程序。

然而，这种做法真是损人又损己。它固然暂时保护了小部分欧盟纺织业的从业者，但却损害了欧盟广大消费者、零售商和进口商的利益；它照顾了法国、西班牙和意大利等国家的利益，但是却以牺牲欧盟其他成员国的利益为代价。这就导致了极具讽刺意义的情形出现：欧盟贸易委员曼德尔森在与中国的纺织品贸易谈判中越是锱铢必较，越是损害着大多数欧洲人的利益，也为自己日后的尴尬处境埋下伏笔。

果然，中欧纺织品贸易协议墨迹未干，曼德尔森就已经是四面楚歌：利益受到损害的成员国向他施加了巨大的压力。德国、荷兰、丹麦、瑞典、芬兰的外贸部长或写信、或公开撰文，抨击欧委会重新设置配额、“阻止进口和业务外包的做法是经济自杀”；欧洲商会也发表声明，要求欧委会对已抵达欧洲港口、但超出配额的中国纺织品清关放行。甚至立场强硬的法国贸易代表也要求曼德尔森灵活行事，网开一面。这就让这位谈判代表多少感到有些“里外不是人”的意思。

说到底，欧盟委员会其实没有太多的本钱发动对中国的贸易战。

在与中国进行的纺织品贸易纠纷中，欧盟的地位相当脆弱。作为谈判者，欧委会并不掌握中欧纺织品贸易的详实数字，否则就不会陷入在谈判中漫天要价、作茧自缚的窘境；同时，欧盟的决策是各成员国及各行业、各利益集团互相讨价还价的结果。内部的意见分歧和利益区别必然导致欧盟在关键时刻做出妥协。因此，尽管欧盟有时看起来气势汹汹，但是它打不起对华贸易战。



【时事点评】事实上，在东方评论员看来，这次“服装危机”可以说充分暴露了欧盟内部在一体化的进程中、到处都充满着“意见分歧”和“利益区别”。


*** 欧盟谈判代表曼德尔森何以“一夜之间”成了“口诛笔伐的对象”

显然，在“中欧纺织品贸易协议墨迹未干”的时候，在北京与中国方面“据理力争”、并最终从中国这里拿到一份让法国、意大利、西班牙厂商“感到非常满意”的“限额协议”的欧盟谈判代表曼德尔森、却在这“秋高气爽”的“换装之季”、突然发现自己一夜之间、就成了英国、德国等国家商界眼里成了“口诛笔伐的对象”，其根本原因，就在于欧盟国家的经济结构的“不均衡”。


*** 引发这场“服装危机”的也有“技术上的因素”

其次，就是技术上的原因，即：由于欧洲服装贸易商或零售商早在协议签署之前就已向中国商家订货、以应对秋冬销售旺季，让欧盟尴尬的是，大量发往欧洲的中国纺织服装产品在运到之后、却因为无法获得配额而积压在欧洲各港口而“不能入关”。从而引发了一场所谓的“服装危机”，并就此激发了欧盟进口商、零售商及相关行业组织、国家政府等“反设限派”的“强烈不满”、与对“设限派”的“愤怒声讨”。


*** 将这份“限额协议”“批得一无是处”的国家都已完成产业调整

我们注意到，将这份“限额协议”“批得一无是处”的主力军、是德国、荷兰和英国等国家、在我们看来为，这些国家有具共同特点，那就是，早前都有意、无意地让按照世贸组织《纺织品与服装协定》、如期完成产业调整，结果，这些国家（在欧盟内有圈套影响的就有德国、英国、荷兰、瑞典、丹麦等）、都已经调整成了“纺织品纯消费国”、而不是“生产国”。


*** “按规矩办事”的国家正经受二战以来欧洲最为严重的“服装危机”

因此，东方经济评论员认为，对这些国家而言、“纺织品”早已与“生产过程”脱钩，在这些国家政府的眼睛里、所谓的“纺织品”问题、更多地是表现在“如何维护”“其国内的纺织品零售业”的利益之上、如何维护国内消费者的利益之上。

显然，眼下这些“按规矩办事”的国家、其需要维护的重点单位、即国内的纺织品零售业正遭遇“大量缺货”和“失去商机”的窘境、而其民众不仅正经受这么一场号称二战以来、欧洲最为严重的“服装危机”、之后，还将“被迫继续为此付出更多钞票”。


*** 在经济利益上的“巨大出入”、怎么不令欧盟国家间的矛盾激化？

与此同时，另一些国家、比如法国、意大利和西班牙、不仅一直拒绝世贸《纺织品与服装协定》进行产业调整，以实现与欧盟其他国家的经济整合、反而准备反其道而行之、准备让其国内的“纺织品生产商”继续享受、这份给德英等国带来损害的“限额协议”所带来的巨大好处。由此可见，这种在经济利益上的“巨大出入”、怎么不令欧盟国家间的矛盾激化？


*** 俗话说得好、“会哭的孩子有奶吃”

事实上，在6月份的中欧纺织品贸易谈判中，东方评论员就注意到，尽管德国等政府出于自己的利益也反对法国、意大利、西班牙要对中国纺织品设限的做法、但是、由于这些国家从政府、到商家、再到媒体、最后到一般的民众，显然没有一种“火烧眉毛”的感觉、即“没有深刻地意识到”自己必将是继中国之后的“第二个受害者”、而且也没有意识到这种损害是如此地现实。

因此、在我们看来、当时欧盟内部种种“反对限额的声音”、总的来说被“支持限额的声音”淹没得“一干二净”。

俗话说得好、“会哭的孩子有奶吃”，“限额协议”达成之前、“会哭的孩子”是法国、意大利、西班牙，欧盟听到的也就是“要求设限的声音”、这些国家也就如愿地“吃到了奶”、吃饱了后自然也就没有了哭声。而现在、“饿”着的可是德、英、荷等，饿急了自然也就要哭两声，如此一来，听到“哭声”的欧盟这才知道事情不那么简单。


*** 欧盟“又准备将解决问题的出路”放在北京这一边了

然而，问题是中欧间的“纺织品限额协议”已经生效了，新出来的问题来自欧盟“内部矛盾”、可以说是“纯属欧盟内政”，绝对与北京“拉不上关系”。但是，在东方评论员看来，关键在于种种迹象显示、欧盟似乎对自己内部矛盾“拿不出个办法来”、或者不愿意在这方面花费精力，因此，欧盟“又准备将解决问题的出路”放在北京这一边了。那么，面对“急火火地”赶到北京的欧盟官员、北京这次又将如何应对呢？


在一则有关欧盟官方“最新立场”的报道之后，我们将再来讨论这个问题。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com



** 纺品设限引爆空货架危机欧盟派员来华谋解




【综合8月24日消息】据报道，欧盟委员会贸易官员今天将动身飞抵北京，与中方就输欧纺织品“超限”问题进行谈判。

据报道，中国纺织品超出进口限额之后，目前大量中国纺织品囤积在欧盟港口，无法通关。订购这些中国纺织品的欧盟零售商希望能让这些货物顺利进入欧盟市场，因为很多欧洲商场面临“空货架”危机。

欧洲陷入服装危机

今年6月，欧盟重新对来自中国的10类纺织品实行配额限制。此举虽然满足了南欧和东欧一些纺织品生产商的要求，却损害了欧盟纺织品进口商、零售商和消费者的利益。目前，中国出口欧盟套头杉、长裤等纺织品早已超出欧盟进口配额，胸罩、女式衬衫和亚麻布服装又将达到配额限量，这使欧盟进口商面临较大压力。

据英国《星期日电讯报》21日披露，当地服装销售商警告说，若欧盟不尽快解决中国纺织品滞留关外的僵局，英国消费者将在两周内面临服装销售短缺的局面。

这场危机并非仅在英国上演。欧盟对中国纺织品设限，实施严格的进口配额后，英国的马克与斯宾塞、瑞典的亨尼斯与莫里茨集团等著名国际时装公司进口的大量服装，包括运动衫、裤子、乳罩大量积压在港口，无法入关。

零售业专家惊呼，这是“自二战以来最大的服装危机”。他们称，消费者也许从下月开始就会感到购物受到限制。英国驻欧盟零售商协会负责人阿利斯代尔·格雷说：“这将带来灾难，这场对华贸易的最大危机影响极大，秋季商品供应在很大程度上将中断。”

欧盟代表抵京为纺织品“放行”

在配额用完后，“超限”的那部分中国输欧产品只能滞留在当地关外，而无货可卖的欧盟进口商和零售商却还得支付仓储费用。看到越来越多中国产品滞港导致自己陷入断货的窘境后，欧盟一些成员国政府、纺织服装进口商和零售商组织近日纷纷要求欧委会放松对中国纺织品的限制。目前，德国、瑞典、荷兰、芬兰、丹麦等国经贸部长已紧急上书欧盟贸易委员曼德尔森，要求增加对中国产品的配额，要求大幅增加对中国产品的配额。

欧盟委员会发言人克里斯蒂娜日前在欧盟委员会举行的新闻发布会上表示，欧盟贸易官员将于24日赴北京与中方进行谈判。另据了解，今年9月，欧盟贸易代表曼德尔森还将再次造访中国，参加中欧峰会，这次峰会可能成为双方就灵活处理纺织品配额管理达成一致的重要契机。

稍早前，欧方一位官员表示，中欧间就“超限”问题的谈判，决不会把6月中欧纺织品备忘录中的配额数量“推倒重来”。欧方预想的方案是预借明年的配额，或是跨类别调剂配额———拿出备忘录下10类设限产品中配额使用较少的产品数量，调配给那些配额已用完的产品。


欧盟或有望提高配额

此外，贸易专家的分析指出，中欧此回合谈判的核心焦点是借用明年配额还是扩大今年欧洲进口配额总量。从目前的综合形势判断，此回合的磋商总体对中国纺织品企业有利，中方在此回合中将占据主动地位。在欧盟与中国签订纺织品协议之前，欧委会主要面对的是成员国纺织品生产企业压力，其要求对中国纺织品设置限制以解决由此带来的就业压力。由于设限制并没能解决就业的问题，现在的情况是纺织品生产企业的声音没有了，而进口商和零售商的反对设限的声音却越来越高涨。

一位接近中国商务部的人士对中欧解决“超限”问题颇有信心，“欧盟受到其内部进口商的压力越来越大，中国产品滞港的费用都是他们承担的，他们一定会要求政府拿出解决办法。”该人士指出，眼下中方关注的是“怎样谈”这个问题，“我不认为预借明年配额是最佳的解决方案，我们应该争取让欧方增加配额。”




【时事点评】就表现上而言，欧盟内对各国政府施加压力的企业、一方面来源于欧盟进口商、比如著名国际时装公司、它们在港口、码头上有着大量积压着、自中国进口的大量的运动衫、裤子等无法“入关”、并为此承受着日益增加的“滞港费用”；而另一方面来源于欧盟零售商、这些零售商中、有的还得为自己进口的货品支付仓储费用、更多的则是面临着无货可卖、“有钱无法赚”的荒唐境地。


*** 欧盟有人还提出了一个“异想天开”的解决方案

显然，面对这种“双重损失”，在欧盟企业和许多不需要保护纺织企业国家的压力下、欧盟委员会贸易官员今天才动身飞抵北京、要与北京“再次商量”输欧纺织品“超限”问题的。

事实上、因“内乱”而被迫重返北京的欧盟、似乎有求于北京、但是，磋商还没有开始、欧盟负责商贸的一位官员就“先声夺人”地强硬表示，中欧间就“超限”问题的谈判，决不会把6月中欧纺织品备忘录中的配额数量“推倒重来”。此外，欧盟有人还提出了一个“异想天开”的解决方案、即让北京向欧盟“预借明年的配额”。


*** 亏得欧洲人“想得出来、并说得出口”

对这一解决方案，我们的观点是：亏得欧洲人“想得出来、并说得出口”。道理其实很简单，第一，这是种不讲基本信用、且没有廉耻的方案，根本就是一种寻求将欧盟的“内部矛盾”“外包给”中国的“不道德行径”、也是一种一厢情愿的、不切实际的幻想，这是想让中国“为欧盟内部的矛盾、处理中欧贸易的错误行为埋单”，我们认为、北京就是再顾及中欧战略关系的大局、也不会替“想出这种点子的欧洲人”“结账”。

第二，这种方案不过是在“头痛医头”，是只顾眼前。在我们看来，提前使用明年的部分配额本质上不过是“拆东墙补西墙”的临时应付手段，无法彻底解决问题，还会因减少了明年可出口总量而可能在明年再次造成中国纺织品压港危机。


*** 欧盟一方面想稳住阵脚、另一方面又抛出一“阴招”

东方评论员认为、在提出这种不切实际的想法后、因“内乱”而处于谈判弱势的欧盟也许是“自觉不太可能”、因此，一方面强调“正争取寻找可以平衡各欧盟国家利益的解决危机办法”，并“呼吁各国保持团结”来稳住阵脚、另一方面还使出了另一“阴招”、即放风可以“跨类别调剂配额”—拿出备忘录下10类设限产品中配额使用较少的产品数量，调配给那些配额已用完的产品。


*** 欧盟想“一箭双雕”、想“好处要沾全、坏处全不沾”

我们之所以称之为“阴招”、就在于“跨类别调剂配额”听起来似乎有理、但细一琢磨其实与“预借明年的配额”是一路货色、都是企图要中国企业独自承担这次”服装危机”的所有后果，显然，所谓的“跨类别调剂配额”、就是要求那些在“备忘录下10类设限产品中”的、且暂时还没有用完今年配额的中国企业、将剩下的配额调剂给
在欧盟港口、码头上“正大量积压着的产品”、这样，欧盟既不需要增加中国纺织品的配额、以免刺激法国、意大利、西班牙这些国家内“力主设限的纺织品生产商”、而且又可以让“大量积压着的”、欧洲人民“正等着换装的”纺织品正常“入关”，从而也缓解了来自德国、英国、荷兰等纺织品消费国、以及整个欧盟的纺织品零售商的巨大压力，总之一句话，“这种阴招”对中国企业而言是“至阴至极”、百害而无一利，而对欧盟而言、则是“一箭双雕”、是“好处要沾全、坏处全不沾”。


*** 本质上不过是“被动的欧盟”意图“以攻为守”的伎俩

东方经济评论员认为，提出这些“自私至极之方案”的欧盟人、大概不会傻到认为北京会“照单全收”，在我们看来，不论是“预借明年的配额”、还是“跨类别调剂配额”，本质上都不过是“被动的欧盟”意图“以攻为守”的伎俩，既将这些“不可能的方案”先手抛出、来当作谈判的基础和起点。


*** 解决这次危机的方式大概有这么三种

事实上，一般认为，解决这次危机的方式大概有这么三种，第一，欧盟所希望的、让北京提前使用明年的部分配额；第二，追加配额；第三，北京所喜欢的、彻底取消对中国纺织品的限制。

显然，欧盟最想以第一种方案解决问题，并以此作为谈判的“公开基础”，而北京自然会认为第三种方式“最为合理”、因此，北京的“公开愿望”将是实现这一目标、尽管北京也知道要做到这一点、起码几年内都是不可能的。


*** 双方“首先要认真谈的”就是在“第二种方案”基础上、如何“想办法、变花样”

然而，谈判不过就是个“站着开价、坐地还钱”的过程，既然“第一种”、“第三种”都不可能，那么，双方“首先要认真谈的”就是在“第二种方案”、即追加配额的基础上如何去“想办法、变花样”：一则能立刻解决欧盟眼下的难题、二则在中国纺织业、欧盟纺织业、欧盟零售业之间寻求一种新的平衡点、从而“在现实的基础上”，尽可能地防止这一危机对欧盟以及中国企业造成更大的损害。


*** 谈判的焦点，很可能集中在“明年、后年的额度”的“计算问题”上

在我们看来，经过一番“真真假假地”“讨价还价”、欧盟很可能不得不单方面地对今年的额度进行追加，条件很可能是北京也要“承诺放缓”欧盟已经订货部分的“付运速度”，从而暂时解决这次服装危机。

不过，这样一来，就又将带来一个问题、即“明年、后年的额度”将根据什么基数计算，因此、东方经济评论员认为，双方“其次要认真谈的”、也是这次双方谈判的焦点，很可能集中在“明年、后年的额度”的“计算问题”上、而不是有些分析所认为的、谈判焦点将集中在“是借用明年配额还是扩大今年欧洲进口配额总量”的问题上。


下面，我们将把关注的焦点转向石油市场，据最新的市场行情、今天的石油期货有可能再创历史新高，事实上，我们对此并不惊讶，之前，在《东方国际投资》的相关报告中、经济评论员及分析师已经给出了明确的判断，即在朝核问题六方会谈复会前、国际石油价格极有可能越过70美元的大关。

因此，在我们看来，今天上升势头猛烈的石油价格、不过是往这个方向“又近了一步”而已。在一段援引自英国《金融时报》的分析片段之后，我们将开始今天的国际市场部分。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
