# -*- org -*-

# Time-stamp: <2011-08-02 22:21:54 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

#+STARTUP: indent

*  2005年5月19日 星期四

** 吴仪出席日本爱知世博会中国馆馆日开幕式

【名古屋消息】５月１９日，２００５年日本爱知世界博览会中国馆馆日开幕式１９日在名古屋市世博园隆重举行。中国国务院副总理吴仪、日本经济产业大臣中川昭一等出席开幕式并发表讲话。

吴仪在致辞中首先向为中国馆建设提供支持的日本各有关方面和国际展览局表示感谢。她指出，世博会是人类文明传承轨迹的体现，是展示世界各国社会、经济、科技进步和发展前景的舞台，也是各国人民交流思想、促进合作、推动文明发展的盛会。中国已经先后１０次组团参与世博会的展出活动，通过世博会了解世界，展示自己，促进了与世界各国的友好交流和合作。

吴仪表示，这次世博会中国馆的主题是“自然、城市、和谐—生活的艺术”，体现了中国人民对人类生存、发展的生活艺术的思考和探索。中国政府致力于构建人与自然和谐共生的社会。中国馆已经并将继续通过丰富多彩的展出和系列活动，向日本及来自世界各地的朋友们展示中国的传统文化与现代文明的交融与发展，让大家充分感受中国人民创造新生活的智慧和热情。

吴仪说，本届世博会紧紧把握时代的脉搏，取名“爱地球”，并以“自然的睿智”为主题，从设计施工到组织运作，都体现了对地球、对大自然的关爱。这再次体现出日本人民的智慧和创造力。她表示相信，日方举办世博会的先进理念和经验对中国办好上海世博会将起到借鉴作用。她还热情邀请各国朋友光临２０１０年上海世博会。

中川昭一代表日本政府热烈欢迎吴仪出席爱知世博会中国馆日开幕式。他表示，爱知世博会中国馆在这里受到广泛关注和欢迎，吸引了大批观众，为世博会增添了光彩。爱知和上海世界博览会主题衔接紧密。日方将与中国合作，将世界博览会接力棒传递好。

日本世界博览协会会长丰田章一郎在开幕式上发表讲话说，对日本而言，中国是最重要的国家。作为一衣带水的邻国，两国友好交往历史悠久。他希望日中双方通过爱知、上海世界博览会，共同描绘城市与自然和谐共存、可持续发展的美好蓝图。

中国驻日本大使王毅、中国国际贸易促进委员会会长万季飞、日中友好议员联盟会长高村正彦以及日本前首相桥本龙太郎、国际展览局局长吴建民等２０００多位中外各界人士出席了开幕式。出席开幕式后，吴仪先后参观了爱知世博会的中国馆、蒙古馆、韩国馆、日本馆和丰田馆。



【时事点评】大家知道，国务院副总理吴仪这次对日本的访问、事实上是源于今年一月份、中日之间的一次高官对话。

*** 恐怕更多的是在设立一种“标志”

我们记得，今年元月份，吴仪是当着来访的日本国土交通相说的，当时，那位官员在北京表示：“首相应该谨慎对待参拜靖国神社”，在这之后，吴仪才表达的这么个“意愿”的，即，“有意于5月的2005日本爱知世博会期间访问日本”。

在我们看来，吴仪副总理当时所表达的、“有意访问日本的心愿”、恐怕更多的是在设立一种“标志”，东方评论员认为，北京之所以设立这个“标志”，就在于“那之后的几个月”正是世界格局何去何从的“关键期”。

*** 北京显然摆出了一个姿态

显然，如果顺着这个思路去看，我们就不难看出，中日之间在经历了上个月的、日本外相访华失败的“摊牌”、日本首相的“公开道歉”之后，北京显然摆出了一个姿态，那就是，既然日本方面以“道歉的行动”、肯定了中日之间的关系“不能断”的现实，而中国又用“一连串的实际行动”“有力地证明”了“政冷经热”式的中日关系是“兔子的尾巴长不了”的，那么，中日双方就都得从“最实际的利益”出发，用积极的行动、通过“经热”去“捂热”“政冷”。

东方评论员认为，从这个角度去看，国务院副总理吴仪“如愿”访问日本、参观爱知世博会，事实上是北京方面率先在这方面走出了第一步。

然而，在中日关系何去何从的问题上，由于日本右翼的得势，再加上夹杂了太多的“中美因素”、以及日本那挥之不去的“大国梦”、这也就注定了双方修补关系过程不会一帆风顺。

事实上，就在吴仪访日的同时，我们就注意到，双方在“台上台下”、可以说“各种配套动作”是一刻都没有停。下面，我们先来熟悉一下两段消息，之后，东方评论员将继续就是“中美日”关系、展开我们的观点。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 日本在野党批评小泉为其参拜靖国神社辩解

【东京消息】日本在野党领导人近日发表讲话，对日本首相小泉纯一郎日前为其参拜靖国神社辩解提出批评。

小泉日前在日本众议院预算委员会上声称，每个国家都有追悼阵亡者的心情，采取什么样的追悼方式“别国不应干涉”。

社民党党首福岛瑞穗１８日在记者招待会上批评说，在中韩两国强烈的批评声中，（小泉）这种不以为意的态度无非是傲慢。这不是加害国领导人该说的话。

日本最大的在野党民主党代表冈田克也于１７日在记者招待会上说，小泉缺乏作为一个首相的认识。

** 中国重申拥钓鱼岛主权反对日采单方面行动

【北京消息】中国外交部发言人孔泉19日指出，中方坚决反对日本方面对钓鱼岛采取的任何单方面行动。日本政府17日称，有18名日本国民的户籍设于钓鱼岛。在19日的外交部例行记者会上，有记者问及中方对此消息的评论。

孔泉重申，中方在钓鱼岛问题上的立场是明确和一贯的，那就是钓鱼岛及其附属岛屿自古以来就是中国的领土，中国对此拥有无可争辩的历史和法律依据。

孔泉进一步指出，日方对钓鱼岛采取任何单方面行动，都是对中国领土主权的严重侵犯，都是非法和无效的，中方对此坚决反对，坚决不能接受。



【时事点评】对小泉为其参拜靖国神社辩解、并叫嚣“别国不应干涉”、以及“日本政府17日称，有18名日本国民的户籍设于钓鱼岛”的消息，我们在周一的《东方时事解读》中、已经给出过我们的观点，而就如我们当时所说的那样，小泉政府在吴仪到访之前、突然来这一手，一来是在故技重施、在实际控制钓鱼岛的问题上又偷跑了一步，二来，也是在有意在“恶心”北京。

*** 得到日本经济界支持的这种“反对声”突然增强

然而，我们也注意到，日本的主要在野党也抢在吴仪到访之前、反驳了小泉纯一郎的辩解。显然，在中日关系何去何从的问题上，日本人内部“也有好多反对声音”，值得强调的是，随着北京一系列“政冷必然导致经冷”、“言与行”的警告、得到日本经济界支持的这种“反对声”突然增强。


*** 国际社会下大迫使华盛顿在两个方向让步

事实上，日本这种反对声的增强，也与目前的国际格局大有关系。东方评论员认为，由于“中欧俄”在中东问题上、正在以伊朗核问题的“和平解决方案”为支点，迫使华盛顿向着同意建立一个“多边的中东安全机制“方向让步，而在东北亚，中国、俄罗斯、朝鲜、韩国、也在有意将朝核问题的”和平解决方案”为支点，迫使美国向着同意一个“多边的东北亚安全机制”方向让步。

值得强调的是，北京显然在考虑用一个“有效的东北亚安全机制”、去从侧面保障“台海和平”。这样，台海海面上的任何风吹草动，都将直接影响到整个东北亚的安全形势，这就如中国目前将“朝核问题”硬性地捆上了“台海问题”一样。

*** 华盛顿在将其军事力量发挥到极致之后，却仍然不得不面对“如下现实”

然而，需要指出的是，华盛顿在中东、东亚的力量仍然非常强壮，这就让我们“在表面上看起来”、要想让这两个“多边机制”成形，好象是几乎不可能。

但是，在东方评论员看来，我们不要忘记了，尽管华盛顿在中东、东亚的力量仍然非常强大，只是这种“仍然非常强壮”的力量，更多地是依赖其军事力量而加以体现的了，这就是说，在华盛顿将其最能体现霸权的军事力量的作用发挥到极致之后，却仍然不得不面对“如下现实”：

*** 十几万大军、上千亿美元仍然不能主导伊拉克政治重建进程

第一，美国的力量不能在中东问题上取得压倒性优势，这在其动用了十几万大军、在耗费了上千亿美元之后，仍然不能主导伊拉克政治重建进程、从而导致出现一个什叶派政权的尴尬中，表现得尤其清楚。

在我们看来，这还不算，华盛顿在压力之下，不得不启动巴以和谈，也不得不接受“中欧俄”“最想得到的”伊朗核问题的“解决原则”：那就是保留伊朗和平使用核能的能力，而由其他国家提供核燃料的方案。

*** 谁都清楚“这一方案”的真正意图

东方评论员想强调的是，谁都清楚，按这一方案，就意味着只要“中欧俄”愿意提供“相应品位”的浓缩铀、那么，伊朗随时就能生产出核武器。显然，这是“中欧俄”在防止伊朗成为一个中东“核武强权”的同时，也在为他日需要伊朗成为“核武强权”、去制衡华盛顿独霸中东野心、而留的一个后手。显然，如果今后伊朗核问题果真如此解决的话，很难判断，华盛顿的十几万大军、在伊拉克忙了两年多之后，究竟得到了什么？


*** 美国也不能在东亚表现出“具有优势的战略力量”


第二，在东方评论员看来，让华盛顿决策层“难受”的是，在“美日军事同盟”的帮助下，美国甚至也不能在东亚表现出“具有优势的战略力量”，这在“反分裂国家法”确定了“台独就是战争”、从而迫使美国不得不调整对台政策、进行“反台独”、并同时在之前一再声称“不排除将以军事手段解决”的朝核问题上、也不敢轻举妄动，从这一事实中、我们也可以清楚地看到、美国人的确在“捉襟见肘”。

唯一让美国人安慰些的是，在其军事力量最为薄弱的中亚地区，华盛顿倒反而促成了几场“颜色革命”，捞回了一点颜面，但是，这扭转不了其在全局的被动。

*** 华盛顿不得不“尽快地”在战争之外去寻求替代解决方案

在东方评论员看来，这样的例子还有，在这里，我们之所以罗列这些，就是想强调一点，即，如果华盛顿不能靠其世界上最强的军事力量、在中东、东亚这两个关键的地方争得主动，并迅速解决问题，摆脱中东被动的话，那么，它就不得不“尽快地”去接受这么一个事实、那就是，在战争之外去寻求问题的替代解决方案。

首席评论员指出，早在今年元月份，布什第二任期的就职演讲时，就打出了“民主”这块招牌，这将之形象地称之为“武器”，由此可见，美国决策层也意识到了“美军”、这一先前美国新保守主义者最为相信的战略利器、根本就不能解决“美国想解决的问题”。

*** 美国的野心、以及与这种野心不相符的实力，促使其他国家在纷纷地“合纵连横”

众所周知，在美国的“战略武器库”中，向来有三大宝：民主人权、美元、美军、显然，由于美国新保守主义者过于相信“美军”的使用，结果是，“美军”不仅重创“美国的民主人权形象”之余，也严重影响了“美元”这一武器的使用。

而反过来，在华盛顿全力使用“美军”、奉行“单边信条”的这两年中，美国的野心、以及与这种野心不相符的实力，促使其他国家在纷纷地“合纵连横”，在东方评论员看来，这种合纵连横绝不仅仅是“政治、军事层面”的，恰恰相反，它更多地是体现在经济层面。


*** 美国独霸世界，首要目标就是为了独霸经济话语权

事实上，在东方评论员看来，我们不能说华盛顿新保守主义者的战略目标不符合美国的利益，因为，它的战略目标就独霸世界，从而获得全球主要问题的决定权，显然，“悠悠万物，经济为先”，华盛顿的战略家们非常清楚，不论是“民主人权”、还是“美军”、从根本上讲，都是建立在“美元”基础上的。因此，美国动用军事手段要独霸世界，首要目标就是为了独霸经济话语权。


*** “美元”所代表的美国经济霸权，事实上已经面对着众多的冲击

然而，也就在在过去的两年中，特别是今年以来，“美元”所代表的美国经济霸权，事实上已经面对着众多的冲击，这中间，最具代表性的是三个方向，一是欧洲经济体（包括俄罗斯）正在整合，二是亚洲经济体（包括俄罗斯远东地区）也在整合之中；最后，就是美国的后院，南美洲、也在以一种“有别于”美国愿望的方式、在试图重新寻找经济出路。


显然，在“美军”不能解决问题之后，事实上，美国的中东战略、与其“最先的计划”相比，事实上已经陷于了停顿状态。东方评论员认为，随着华盛顿的“无力用兵”，美国的霸权、自然也就到了“心有余而力不足”的地步。

*** 美国的“自私性”、事实上“同时侵害了”其“盟友与对手”的核心利益

还有一点，东方评论员觉得必须强调的是，由于美国全球战略目标的“自私性”、事实上、它“同时侵害了”其“盟友与对手”的核心利益，这就给美国的“盟友和对手”以时间和空间，去考虑“各自的出路”。这一点，在“中美日”三者之间的复杂关系中，体现得特别鲜明！

在西太平洋地区，美国认为最大的挑战争来自中国，这不错，事实上，在东方评论员看来，北京现在也正在凭借自己的经济、政治影响力、一点点地通过与周围国家的整合，正在慢慢地排挤美国在这一地区的影响力。东方评论员认为，在这一点上、在韩国的身上、表现得特别明显。


*** 对华盛顿的决策者而言，让日本迅速军国化，代价是现实的，也是十分巨大的

华盛顿决策层非常清楚，让“日本军事主义”去全面承担来自中国的压力不是不可以，但是，由于中国背靠欧亚大陆，而日本却完全是个海水环绕的岛国，因此，对华盛顿的决策者而言，让日本迅速军国化，代价是现实的，也是十分巨大的，这种“现实性”表现在日本一定会“倾一国之力”、重点发展海上军事力量、和核战略力量，以拿回一直在美国海军手里掐着的海上生命线，从而挑战美国的海上霸权。这样一来，也许日本还没有伤着中国、而首先就会伤着美国自己。

*** 日本用“炸弹”和“商品”两次袭击过美国人

可以肯定的是，美国海军离开日本军港的那天起，必然标志着美国海上霸权的结束，自然也就标志着美国全球霸权的结束。在东方评论员看来，日本是世界上唯一两次攻击过美国的国家，一次是二战期间，第二次，是80年代后期，美国经济处于调整期间，日本商品狂攻美国市场，一时间里，日本的生产商在用汽车等日本产品在美国攻城掠地，另一方面，日本庞大的资金、在用日元买进美国资产、这其中甚至有美国人心中的标志物、比如洛克菲勒中心、和夏威胰海滩。

不难看出，曾经遭到日本分别用“炸弹”和“商品”、进行过两次袭击的美国人，是绝不愿意撤出日本、绝不愿意撤出东亚的，众所周知、驻日美军的最主要任务、从来就不是准备同前苏联和中国打仗的，而恰恰就是为了严密控制日本的一举一动。

*** 日本仍然有用炸弹和商品再次袭击美国的潜力

在东方评论员看来，日本仍然有用炸弹和商品再次袭击美国的潜力，也正是日本具有这种潜力，这就决定了华盛顿在严防中国的同时，也绝不会主动地、现在就让日本成为一个足以挑战自己海上军事霸权的“正常国家”；

与此同时，在日本拒彻底清算历史问题、消除重走军国主义“危险老路”的情况下，中国、韩国也不会养虎为患地、去支持日本成为一个“正常国家”的。

*** 在这种双重限制下，日本恐怕只能走与亚洲经济一体化的道路

东方评论员认为，在这种双重限制下，日本在无望通过走上军国主义“这条快车道”、快速成为“正常国家”的情况下、在没有能力保护自己的经济政策，和海上运输线的时候，为了摆脱欧美经济对自己的双重夹击，恐怕只能走与亚洲经济一体化的道路、依托亚洲国家去与欧美经济相周旋。

事实上，在我们看来，由于华盛顿对日本的军国主义也极其警惕，因此，在很大程度上，美国人之所以在中日之间竭尽全力地、钉钉子、插楔子，最主要的目的正是为了破坏这个“亚洲经济一体化”、从而从根本上遏制中国的崛起、并继续控制日本。

*** 北京派吴仪去日本“交换看法”的宏观背景

在我们看来，这恐怕也正是北京派吴仪去日本“交换看法”、发出准备以“中日经济合作”促进“中日政治和解”之信号的宏观背景。我们注意到，尽管小泉纯一郎仍然在钓鱼岛问题上“搞小动作”、在历史问题上“念歪经”，然而，在中国政府“已经用行动”证明了自己“可以承受一个完全破裂的中日关系”之后，从小泉纯一郎“被迫道歉”一事来看，日本政府“也已经用行动”证明了自己“不能承受一个完全破裂的中日关系”。

东方评论员认为，有了这一层“认识”之后，那么，中日间的许多问题也就有了“改善的基础”，如此一来，北京自然也就愿意通过这次定位在“交换看法”层次上的访问，尝试一下，在日本“军国梦”事实上没有出路的情况下，想看看日本政府是否充分地认识了这一点，也想看看到底能不能用“经热”捂热“政冷”的局面。


有消息说，十八日下午召开的二00五年亚洲纺织服装发展福州高峰论坛上，来自日本、韩国及内地、香港、台湾地区的纺织服装界代表签署《亚洲纺织服装发展福州高峰论坛联合宣言》，并探讨亚洲国家加强合作的初步构想。

显然，在东方经济评论员看来，中日韩纺织行业的这次“联合宣言”、将使得三国的“各自优势”得到具体的分工、和充分地发挥。事实上，就结果而言，这次论坛取得的成果，实际上已经为亚洲国家“经济一体”、提供了一个“中日韩可以共赢”的“实例”。

在东方评论员看来，通过这个实例，我们可以看到、中日之间在经济层面的密切关系、是“有可能”促进政治关系改善的。然而，这只是种“可能性”。

下面，我们一起通过报道了解一下相关情况，之后，东方评论员就“中日关系”的走向，还想说几句！

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
