# -*- org -*-

# Time-stamp: <2011-08-03 23:42:23 Wednesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 2005年6月22日 星期三

** 胡锦涛会晤韩国总理谈朝核问题

【北京消息】中国国家主席胡锦涛会见到访的韩国总理李海瓒，双方就国际和地区问题交换看法，在朝核问题上，双方都认为对话和谈判是唯一选择，中国方面希望各方努力，早日促成重启六方会谈

胡锦涛说，这是第二次和李海瓒会面，感到非常高兴，而李海瓒就转达韩国总统卢武铉的问候。

地区和国际问题是两国领导人会谈的一个重点，中国方面就强调，作为本地区的重要国家，中韩两国应该进一步发挥各自的影响，

而双方都认为，对话和谈判是解决朝核问题的唯一正确选择，各方都应该抓住时机，为尽快复谈创造气氛和条件，而中方表示，愿意继续劝和促谈，并且和韩方保持密切的协调和配合。

对于不久前韩国统一部部长对于朝鲜的访问，中方表示极大的关注，并且对于朝鲜方面表示愿意尽快在七月份重开六方会谈的态度表示赞赏。


【时事点评】我们注意到，胡锦涛主席再次强调了“对话和谈判是解决朝核问题的唯一正确选择”，显然，在东方评论员看来，北京之所以喜欢强调这种“唯一性”，就在于华盛顿始终在企图实现“另外一种唯一性”，即“朝鲜是一个必须被推翻的暴政国家”。

*** 中韩两位总理“谈得最认真的”就是经济问题

在昨天的点评中，东方评论员已经说过，韩国总理李海瓒此番前来，其实是韩国旨在启动“六方会谈”一系列外交努力的“继续”。而这个努力的重点，就是尽可能地抛开政治谈经济。

在昨天，温家宝总理已经和韩国总理李海瓒举行了会谈，在两位总理的谈话中，当然少不了朝核问题，然而，从各方的信息来看，就如东方评论员在昨天所说的那样，中韩两位总理“谈得最认真的”就是经济问题。


*** 在华盛顿看来，朝鲜鼓捣出的这些玩意儿，都是北京开打经济牌的“序曲

事实上，在东方评论员看来，直到目前为止，尽管朝鲜已经释放出了“许多善意”，其中有“重返核控”，也有愿意销毁可以打到美国夏威夷的中程导弹，更有华盛顿喋喋不休的“重返六方会谈”，然而，在华盛顿看来，朝鲜近来鼓捣出的这些玩意儿，不论怎么看，都象是北京准备在朝鲜半岛开打经济牌的“序曲”、对此无计可施的华盛顿，似乎只能是“满脸的强硬”来应对，并以此来“尽可能地拉住”“六方会谈”中的唯一一个盟友--日本了。


*** 日本因“拿到朝鲜半岛”享受了多么巨大的便利

可问题是，在朝核问题上，由于韩国已然决定从“美日韩”阵营中“出走”、在中国准备的这局东北亚“经济牌局”中、为自己的经济结构升级换代“构建”新的产业链和市场寻找机会，也为将来朝鲜半岛的统一打好基础，韩国的这些目标，无一不在刺激着曾经殖民统治朝鲜半岛达半个多世纪的日本人的神经，要知道，从中日甲午战争、到二战中间，日本在其一步步图谋大东亚共荣圈的过程中，因“拿到朝鲜半岛”享受了多么巨大的便利。

在我们进一步展开讨论之前，我们再来看看一则来自日本的消息，了解一下小泉纯一郎的“最新动作”，之后东方评论员将继续这一话题。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 小泉称不会屈服中韩压力或继续参拜靖国神社

【东京消息】据法新社报道，日本首相小泉纯一郎今天声称，他觉得在参拜靖国神社的问题上，没有必要屈服于中国与韩国要其停止参拜的压力。

“我认为我们不必照韩国所说，或者照中国所说的那样做，”小泉今天对日本众议院一个委员会说。

他称参拜靖国神社不是日本与中国与韩国关系的核心。“在日本与韩国和中国的关系当中，我参拜靖国神社一事不应该处于核心位置，核心问题应该是如何面向未来重视友好关系。”小泉说。

在今天的众议院会议上，日本反对党对小泉发出质疑，指责其以日本外交关系做赌注，寻求为自己的“政治表现”加分，并说小泉试图通过煽动公众的民族主义情绪来提高自己的支持率。

“记住，作为一名首相，你必须考虑国家的利益；你作为一名首相，有责任提高与韩国与中国的关系，”日本主要反对党——民主党领袖对小泉说。

小泉对民主党的指责加以拒绝。20日，小泉在会晤韩国总统卢武铉时没有就参拜靖国神社一事达成共识。


** 日本政府高官再次否定远东军事法庭审判结果

【东京消息】据日本媒体报道，日本厚生劳动省政务官森冈正宏２２日再次否定远东国际军事法庭的审判结果。

森冈当天上午在超党派“日本会议国会议员恳谈会”会议上说，远东国际军事法庭是什么样的审判（值得疑问），战争是双方都作了坏事。只有战胜国正确，而战败国不好，这种说法是错误的。他说，在被占领下（日本）实行了严厉的言论控制，被贴上了那场战争只有日本不好的标签。他还强烈要求小泉首相继续参拜靖国神社。

“日本会议国会议员恳谈会”当天通过了支持小泉首相继续参拜靖国神社的决议，并表示反对对甲级战犯进行分祭和建设新的追悼设施。

森冈正宏５月２６日在执政的自民党国会议员会议上发表谬论，妄称“甲级战犯在日本国内已经不是罪人”，远东国际军事法庭是“任意以反和平罪和反人道罪进行单方面审判的”。他公然否定远东国际军事法庭的审判结果，为日本二战甲级战犯开脱罪责，遭到了战争受害国人民的严厉谴责。




【时事点评】我们注意到，这是小泉纯一郎与卢武铉在韩国“交锋”之后、第一次就参拜靖国神社一事做出“明确的表态”，显然，在东方评论员看来，卢武铉在是否与小泉纯一郎共同出席记者会问题上的“前倨后恭”，显示韩国在“拉日本参与朝鲜经济改革”的问题上，心情“过于迫切”了。


*** 卢武铉心里有一个“小九九”

东方评论员认为，韩国想拉日本“入伙”的心情“可以理解”，但是，卢武铉在布什那里没有得到好脸色，就急急忙忙给小泉纯一郎“好脸色看”，主要在于卢武铉心里有一个“小九九”，即，一方面想借中国的力量、通过中美这两个大国在全球利益上的“斗争与合作”、来迫使华盛顿尽可能地不去打断朝鲜半岛经济整合的过程；而另一方面，也想将日本引入朝鲜半岛经济整合进程、从而部分削弱北京的影响。


*** 韩国的这种心态、也就让小泉纯一郎抓到了卢武铉的底牌

首席评论员指出，俗话说得好，是“无欲则刚”，显然，韩国的这种心态、就是小泉纯一郎敢以强硬姿态访问韩国的“本钱”，而卢武铉在小泉“拒绝”在历史问题上让步之后，却并没有拒绝共同出席记者会的“表现”，也就让小泉纯一郎彻底抓到了卢武铉的底牌，从而在历史问题上“看轻”韩国的压力、而认为只需全力顶住来自北京的压力就行。


*** 客观上讲，小泉纯一郎今天的一番话倒也并非是“无根无据”

首席评论员就指出，如果从这一层面来看问题的话，那么，小泉纯一郎自韩国回国之后、一改之前的“含糊不清”、立刻称“参拜靖国神社不是日本与中国与韩国关系的核心”，客观上讲，在小泉纯一郎又耍小聪明“将日本与中国和韩国的关系”混为一谈之后，倒也成了“并非是无根无据”。起码在日韩关系上，就是如此。


*** 布什从侧面上达到了“坚定小泉纯一郎拒不向北京低头的决心”的目的

显然，在东方评论员看来，华盛顿在朝核问题上的“持续强硬”，就朝核问题本身而言，不论是多么地不合时宜，但是，如果我们从华盛顿欲稳住小泉政府的角度去看问题的话，那么，非常肯定，“华盛顿在朝核问题上的强硬”、让韩国感受到了很大的压力，这也是促使一心想稳定朝鲜半岛局势的卢武铉、无法在小泉纯一郎面前强硬到底的一个重要因素，如此一来，“华盛顿的强硬”起码迫使卢武铉不再强逼小泉纯一郎在历史问题上低头，布什这也就从侧面上达到了“坚定小泉纯一郎拒不向北京低头的决心”的目的。


*** 不难瞥见华盛顿前些日鼓吹中国威胁论的现实意义何在

这这一轮角力的过程来看，不难瞥见华盛顿前些日鼓吹中国威胁论的现实意义何在：显然，在东方评论员看来，韩国心中的那个“小九九”，虽然不能说是受美国近日鼓吹“中国威胁论”的影响，然而，可以肯定的是，从韩国内心深处，尽管出现了“离美亲中”的倾向，但是，这本质上不过是一种现实利益的“驱使”，其中，即有中韩经贸规模已经突破1000亿美元大关的现实经济利益、也有着眼于稳定朝鲜半岛、整合朝鲜半岛经济的政治、经济利益的“驱使”。

需要强调的是，在这些因素之外，东方评论员认为，我们可以清楚地看到，韩国统治层内心深处、仍然“深藏着”“中国威胁论”的影子、尽管韩国人出于自身利益、仍然会不断地、“全面加强”与中国的关系。韩国日前声称将与中国发展军事关系，并计划将“中国韩国军事关系”提升到“韩国日本军事关系”的层次上，就是一个例证。


*** 不论韩国心里如何想，如何警惕中国，但有一点让北京非常满意

首席评论员指出，不论韩国心里如何想，如何警惕中国，但有一点让北京非常满意，那就是，韩国的确是“一心想”整合半岛经济、稳定半岛局势、而并不强求朝鲜“无条件放弃核武器”、是韩国动手做这些事情之前的、必不可少的“前提条件”。

在我们看来，就凭这一条，这就足以让北京“高兴地”、且“尽可能”地“和韩方保持密切的协调和配合”。

东方评论员注意到，小泉纯一郎这一次是在摸到了卢武铉“在历史问题上的底牌”之后、才强硬地宣布“不惧怕中国、韩国的压力”的，并表达了“将继续参拜靖国神社”的意向的。另外，日本厚生劳动省政务官森冈正宏今天再次否定远东国际军事法庭的审判结果，这都与华盛顿在朝核问题的强硬、导致韩国在历史问题上的让步“紧紧相关”。


*** 小泉的“这一宣布”，还是一个“试探”

然而，在我们眼里，小泉的“这一宣布”不完全是“这次韩国之行的总结”，除此之外，它还是一个“试探”。

我们知道，中国外交部副部长戴秉国就要飞往日本，与日本外务事务次官谷内正太郎进行第二回合的战略对话，显然，小泉纯一郎和森冈正宏两人连续在历史问题上再放撅词，就是瞄着这个“第二回合的战略对话”的。

*** 小泉纯一郎的“小聪明劲儿”又一次得到了发挥

由于这个所谓的“战略对话”，实际上就是吴仪中断访日，中日高层“全面中断往来”的情况下，建立起来的一套“事务性对话渠道”，表面上是解决中日间东海开发石油气这一类的具体事务性问题、但事实上已经提负着维持“中日沟通”的历史重任，因此，在这种情况下，北京很难因小泉的这席话、就单方面切断“这一对话渠道”的。显然，在这一点上，小泉纯一郎的“小聪明劲儿”又一次得到了发挥。显然，小泉纯一郎“会拿这一点”来“侧证”他所说的“靖国神社”不是中日关系的核心问题这一论调。


*** 北京不可“过于照顾”韩国的要求

但是，同样“非常清楚”的是，如果中国“假装听不见”小泉纯一郎“继续参拜靖国神社”的声音、没有通过其他渠道做出强烈反应，那么，小泉纯一郎就真有理由解释说：中国最关心的不过是台湾问题、是东北亚经济一体化、东亚经济一体化的问题、而不是“参拜靖国神社”的问题了。

显然，方方面面都在紧张的观察之中，看看中国稍后将如何对此做出反应。东方评论员认为，就我们的观点来看，我们也认为如何促进朝鲜半岛经济整合、促进东北亚经济一体化、以至东亚经济一体化是中国的“最重要外交课题”之一，但是，如果北京“过于照顾”韩国的要求，而在小泉纯一郎再次发出“继续参拜靖国神社”的声音的时候，不做出激烈的反应、虽然不理睬日本、继续冷冻中日政治关系也是一种反应，但是，这种反应将有可能为小泉纯一郎所利用、并向日本国内“散发”错误的信息，那就是有如小泉纯一郎所说的，“中日核心问题不是靖国神社”问题。


*** 北京有必要全盘加以考虑，不要给小泉“自我背书”的机会

另外，东方评论员认为，日本社会至今不肯对小泉政权“痛下杀手”，这说明日本政治界、经济界仍然在观望，看看小泉纯一郎是否能在靖国神社问题上、“在最后一刻”有所突破。就如东方评论员先前一再强调的那样，靖国神社问题表面上看是个历史问题、但是，实质上却是中日双方国家意志的较量。

因此，在我们看来，就算北京因此拿到了小泉纯一郎“参与朝鲜经济改革”的承诺、推进东北亚经济一体化的承诺、在台湾问题上“有所让步”的承诺，如果不打消小泉纯一郎继续参拜的气焰，其对中日关系的“后遗症”将是明显和深远的。对此，北京应该清楚，韩国愿意进行朝鲜半岛经济整合是出于自己的利益、日本愿意加入也是妯于自己的利益，中国在今后有必要对此“全盘加以考虑”。在东方评论员看来，北京有必要通过其他渠道亮明自己的立场，而不要给小泉纯一郎这种“自我背书”的机会。


*** 中国在稍后的“中国人民抗日战争胜利60周年的纪念活动”的安排上，应该“有所动作”

因此，在我们看来，北京的眼光是全球性的，因此不可能在这方面象韩国那样、仅为了拉日本参与东北亚经济一体化、就在这个大是大非的历史问题上做出让步。如此一来，中国在稍后的“中国人民抗日战争胜利60周年的纪念活动”的安排上，应该“有所动作”。

下面，是一段有关伊拉克问题的消息。从消息上看，华盛顿在伊拉克国际会议上“仍然没有如愿”，在一起了解详细内容之后，东方评论员将把点评的焦点转换到中东方向。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

