# -*- org -*-

# Time-stamp: <2011-08-04 12:09:47 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

*  2005年8月01日 星期一




** 六方会谈进入第七天　共同文件仍是讨论重点




【北京８月１日消息】朝核问题第四轮六方会谈１日进入第七天，各方将继续就共同文件草案的修改进行磋商。截至今日，本轮会谈已成为２００３年六方会谈进程启动以来历时最长的一次。目前尚难确定本轮会谈将在何时结束。

韩国代表团团长、外交通商部次官宋旻淳３１日下午在记者招待会上说，会谈进程“已经沿着国道开到了市中心的入口，”“虽然离目的地已经不远，但很难预测还要过多少时间才能到达。”

在３１日一整天的工作级别磋商中，各方围绕共同文件草案进行了认真讨论。

另据俄塔社报道，各国代表团各自对共同文件草案进行修改后，已于３１日将修改后的文本交还给中方。

宋旻淳说，共同文件草案“并不长，但各方都想将迄今为止会谈所论及的核心内容包含进去。”

俄塔社援引俄罗斯代表团副团长叶尔莫洛夫的话说，共同文件草案的修改即将进入“最后阶段”。



【时事点评】在东方评论员看来，随着六方会谈随着时间而逐步向纵深化推进的进程中，可以说“各方的底牌”在揭开最初的“外交语言”之后，而逐一亮相。


*** “美朝”双方根本就是在“各拿一把号、各自吹老调”

之前，即第四轮六方会谈于27日进入第二天的时候，我们就注意到这么一幕：美代表团团长希尔在强调，“当朝鲜彻底弃核并接受有效验证时，会谈各方将向朝鲜提供安全保障”；而朝鲜代表团则表示：“愿意完全弃核，但前提条件是来自美国的核威胁消除，并实现朝美关系正常化”。

显然，东方评论员认为，“美朝”双方这根本就是在“各拿一把号、各自吹老调”。

对此，首席评论员当时更是进一步地指出：朝美各自吹的老调还都是一年前、甚至是两年前的老调。在我们看来，如果“各自重谈老调”是重启六方会谈的“全部”的话，那么，不论是平壤还是华盛顿、或者是北京、甚至是汉城，恐怕都宁可将“第四轮”的日期往后推推。显然，我们的判断是，


*** 过去的几天，不过各方“相互谈心”、“彼此交底”的过程

在东方评论员的眼里，就如在27日中我们所说的那样：国际社会所看到的、朝美双方“各拿一把号、各自吹老调”的场面，不过是一种“六方会谈”的各方之间开出的讨价还价之“原始价格”而已，也就是说，按计划，“六方”不过是将在这个“原始价位”上“逐一要价”而已。

事实上，对此，在上个周未的《时事解读》中，首席评论员就曾一针见血地指出：“过去的几天中，其实不过是个各方通过“相互谈心”、“彼此交底”的过程”，此外，首席评论员还指出、“在底牌都已经亮出来的情况下，六方会谈就面临着“六方”“如何进入”各自依靠实力、拼抢下一阶段会谈筹码的实质阶段。


东方评论员就注意到，韩国代表团团长、外交通商部次官宋旻淳昨天（３１日）下午在记者招待会上说，会谈进程“已经沿着国道开到了市中心的入口”。在我们看来，宋旻淳说的这句话，与首席评论员所说的、颇有异曲同工之妙。

为了更好地说明这个问题，我们再一起来看一则有关“共同文件草案”的后续消息，之后东方评论员将继续这个话题，谈谈这个所谓的“共同文件”，到底起着什么作用。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com


** 六方会谈有争议也有共识，北京将提出“第二版”草案



【东方早报8月1日报道】朝核问题第四轮六方会谈在一种神秘的气氛中进入第二周，虽然能否达成最终的“共同文件”，以及这份文件将以何种形式出现目前还不得而知，但各方已经开始对文件的内容和措词进行磋商，这本身就是此次会谈取得的一个进展。

据消息灵通人士透露，负责起草文件的中方已经在昨天收到了其他各方的反馈，将在今天提出修改后的“第二版”草案。

俄罗斯代表团副团长叶尔莫洛夫表示，各国代表团已于昨天将修改后的共同文件文本交还给中方，草案即将进入最后修改阶段。

日本代表团发言人伊藤昨晚在接受早报记者采访时称：“当天实际上才是实质性谈判开始的第一天。”据俄罗斯媒体报道，已于昨天抵达北京、将代表美国政府参加定于今天在北京钓鱼台举行的首次中美战略对话的美国副国务卿罗伯特·佐立克也将参加共同文件的磋商工作。

中国草案内容极为敏感

7月的最后一天北京飘起了零星的小雨。各方代表团团长们5天来第一次不用早早赶往钓鱼台国宾馆参加各种会议和磋商，因为从这一天起，本轮会谈进入到了副团长级别的工作小组对“共同文件”草案进行商讨的阶段。从当天上午10时起，工作小组在钓鱼台开了4个多小时的会，直到下午的3时才结束。

一位消息灵通人士告诉记者，各个代表团在昨天的副团长会议上向中方提交了自己的修改建议并向其他与会各方做了说明。中方将充分听取各方的反馈并在今天的会议上拿出一个“共同文件”的第二稿供大家再次讨论。

由于“共同文件”草案的内容极为敏感，因此在保密的同时也引起了不少媒体的猜测。7月30日下午4时左右，当天的团长会议结束仅3个多小时，日本《读卖新闻》就报道称：各方一致同意“共同文件”将不明确阐述朝鲜弃核与其他各方履行相应义务的顺序问题。该报还披露说，文件的主要内容将包括：向朝鲜提供安全保障；美日同朝鲜实现邦交正常化；进行经济合作；确立朝鲜半岛无核化目标以及各方关心的其他事项等。

不过，这份被广泛转载的报道也引起了一些资深记者的怀疑。有消息灵通的记者表示，中午12点30分截稿的《读卖新闻》不可能在团长会议结束半小时之内就拿到草案的内容。况且当天的团长会议只进行了20分钟左右，各方只是听取了中方对草案的说明，不太可能在没有和国内商量的情况下达成任何共识。

为半岛无核化目标建框架

韩国代表团团长、外交通商部次官补宋旻淳则透露，六方在昨天的副团长级会上一致认为，共同文件有必要为实现朝鲜半岛无核化的目标建立框架，并为此展开频繁和有效的协商。据悉，各方就将朝鲜半岛无核化与和平解决作为朝核问题大原则达成了一致。

宋旻淳昨天下午在记者招待会上说，各方就共同文件草案发表了各自的意见，但没有就文件的细节展开字斟句酌的讨论。“每个国家都表达了自己的观点，在某些领域的分歧开始明朗化。”一位日本官员则称各方就草案的一些措辞展开了“热烈的交流”，会议将在今天继续。

宋旻淳说：“今天协商的共同文本（草案）并不长，但各方都想将迄今为止会谈所论及的核心内容包含进去。”会谈中没有谈到人权等问题。他说，韩国提出的解决朝核问题重要提案“将成为解决朝核问题的一个重要支柱”。

据美国代表团团长希尔透露，“共同文件将包含6至7个基本原则”。

不少专家预测：“由于六方会谈出席国比以往任何时候都积极，一定能制定出包含废弃朝核、安全保障、经济援助原则的共同文件。”

不过几乎没人预测会达成包含具体行动的协议。

分歧

1，朝鲜半岛无核化的定义，朝鲜要求“互相确认”，即韩国也没有核武器。朝鲜要求对驻韩美军的军事设施展开国际核查，这一点看来美国不会接受。

2，朝鲜要求保留一些核发电设施，而美韩不同意，两国认为韩国的大规模电力援助已能满足朝鲜需要。

3，是朝鲜先弃核还是美国先采取对朝补偿措施。共同文件预计将不阐明如果朝鲜弃核就采取相应补偿措施的顺序，这一点将在以后讨论。

共识

1，朝鲜半岛必须实现无核化，和平解决朝核问题。

2，共同文件有必要为实现朝鲜半岛无核化的目标建立框架，为未来出台半岛无核化文件建立基础。1992年的朝鲜半岛无核化宣言将作为无核化文件的最好参照物加以灵活运用。

3，9月举行工作小组会议，协商朝鲜弃核程序。

4，朝鲜弃核及其相应的补偿应根据各阶段彼此公平的“行动对行动”原则。



【时事点评】事实上，就如上述报道中所说的那样，由于第一份“共同文件”草案的内容极为敏感，因此在“保密的同时”、也的确引起了不少媒体的猜测。我们注意到，日本《读卖新闻》的“猜测”就是：各方一致同意“共同文件”将不明确阐述朝鲜弃核与其他各方履行相应义务的顺序问题。另外，我们还注意到，该报还披露说，文件的主要内容将包括：向朝鲜提供安全保障；美日同朝鲜实现邦交正常化；进行经济合作；确立朝鲜半岛无核化目标以及各方关心的其他事项等。


*** 如果日本《读卖新闻》的“猜测”的第一条“属实的话”，那么，这将是朝鲜的一个胜利

坦率地讲，在东方评论员看来，如果日本《读卖新闻》的“猜测”的第一条、既各方一致同意“共同文件”将不明确阐述朝鲜弃核与其他各方履行相应义务的顺序问题“属实的话”，那么，这将毫无疑问是朝鲜的一个胜利，是美国的妥协。

如果我们拿这一条“共识”去比照美国和朝鲜在这一轮会谈之初就公开抛出的“老调”的话，那么，有一点是非常清楚的，既事实上华盛顿不再强硬反对朝鲜坚持了一年之久的“行动对行动”立场、而间接放弃了“朝鲜必须先行弃核”的强硬立场。

显然，按照我们上面的“争抢筹码”的说法，朝鲜也就成功地将自己的主张塞入了“共同文件草案”、从而抢到了一张重要筹码。不过，需要指出的是，“这种共识”到现在为止，仍然不过是日本《读卖新闻》的一家之言，并没有得到证实。


*** 报道披露的“主要内容”、事实上包括了“中韩俄朝”“四方”的主要立场

另外一个需要指出的事情是，如果您一直在关注《东方环球时事解读》，那么，有一点应该是清楚的：我们一直在强调，朝鲜在朝核问题上的“所有重大立场”，不仅得到北京的默许、事实上更是得到了北京的全力支持。

因此，我们如果从这一背景去分析日本《读卖新闻》的“大胆猜测”，就不难发现，这份“大胆猜测”在字里行间所“披露”的主要内容，比如说“向朝鲜提供安全保障”；“美日同朝鲜实现邦交正常化”；各方在朝鲜半岛进行经济合作；确立朝鲜半岛无核化目标等等，似乎无一不是在“翻译”中国外交部发言人在记者招待会上“经常谈及”的“公平立场”，显然，这些主要内容包括了“中韩俄朝”这“四方”的主要立场。


*** “共同文件”本质上不过是为“六方会谈”拟定一个进一步讨价还价的基础

不难看出，日本《读卖新闻》的这份针对第一版“共同文件”所谓的“披露”，如果不是日本官方的“有意泄密”，那么，可以肯定的是，该报道的主笔人的政治“视听神经”一定非常发达、在我们看来，其对“四方”的朝核问题立场的了解“的确了得”，特别是对中国、韩国、俄罗斯想从朝核问题进程中得到什么也“非常清楚”。

东方评论员认为，通过在朝核问题上的“积极主动”、而“已经获取”了不菲利益的北京、在提交自己的第一份“共同文件草案”的时候、是绝不可能“谦虚地”地忘记自己立场的，也不可能不为朝鲜着想，何况中国也清楚，这第一份“共同文件草案”、本质上不过是在为“六方会谈”拟定一个“继续讨价还价”的基础。


*** “六方”都在期待着自己的对立面“自我检讨”

有意思的是，“六方”是手拿“第一版”草案，经过星期天一整天的讨价还价，今天又形成了“第二版”“草案”。但是，针对这份在一夜之间修改完成的“第二版本”，各方仍然在“叽叽喳喳”，我们注意到，韩国代表团团长宋旻淳就说：“今天协商的共同文本（草案）并不长，但各方都想将迄今为止会谈所论及的核心内容包含进去。”

显然，对宋旻淳的这句“大实话”，东方评论员不觉得意外，在我们看来，这句“各方都想将迄今为止会谈所论及的核心内容包含进去”、就已经将我们在前面所说的、六方“各自依靠实力、拼抢下一阶段会谈筹码”的“热闹情形”、给清楚地描绘出来了：这就是说，表面上看，“六方”都认为自己的立场“是必不可少”的，“六方”都在期待着自己的对立面“自我检讨”、并放弃自己的立场。


*** 对“中美俄”这三个大国而言，“这种期待”远远超出了朝核问题范围

然而，特别是对“中美俄”而言，“这种期待”远远超出了朝核问题范围，而分别与中亚、中东安全局势，以及台湾问题，日本问题、两伊问题等其它事关自己的核心战略利益紧紧相联。

因此，在我们看来，就以“中俄”而言，只要双方能拉着韩国、迫使华盛顿愿意保证“不阻碍”朝鲜半岛进行经济整合、那么，“中俄”在朝核问题上的最大现实利益--启动东北亚经济一体化的目的、也就算达到了。


*** 北京确保东北亚主导权、俄罗斯突破美国包围圈的关键所在

事实上，能否谈出一个多边安全框架、一来保障朝鲜弃核后的国家安全，二来也能顺利启动“东北亚经济一体化”，将是北京确保东北亚主导权的关键所在，也是俄罗斯能否从东亚突出美国包围俄罗斯之战略包围圈、与亚太地区“经济接轨”的关键所在，除此之外，其他的事情并不重要。

因此，在这个方面，美国是绝不可能轻易做出让步、从而让自己实施多年、困死俄罗斯的战略，面临前功尽弃之局面的。

在我们看来，对“六方会谈”的六个成员国而言，怎样进入下一阶段、如何确保自己的利益，是要依靠各自的实力去说话的：各方能否将自己的主张塞进“下一阶段”的会谈议题之中、从而再通过“自己的议题”去左右会谈进程、并去谋求相应的“朝核利益”，正是这几天“六方”都在全力以赴的事情。


*** “中俄”与“美日”之间、可以说围绕着这轮“会谈议程”，早就展开了激烈的角力

然而，首席评论员也指出，其实早在这一轮六方会谈启动之前，中国俄罗斯和美国日本之间，可以说就围绕着“确立六方会谈议程”、就展开了激烈的角力，根据我们的观察，为了夺取朝核问题的谈判的主动权，在这轮六方会谈启动之前，事实上，北京就拉着莫斯科，华盛顿拉着日本，双方可以说都动用了自己各自“可以动用”的一切战略资源，进行了一局激烈空前的、包括政治、军事、甚至是经济各个层面在内的“综合较量”。

我们认为，这场激烈的角力、表面上看，尽管其主战场在包括台海、东海、朝核问题的东亚、但是，它本质上却可以说是一场在世界范围内的“综合较量”。

在我们看来，对这轮六方会谈影响最大的，就是本月将正式展开的、围绕着朝鲜半岛周围举行的中俄联合大规模军事演习。显然，这场安排在本月18日进行的军演，与7月26日才启动、却又没有确定会期、还仍然在为具体议题而争论不休的六方会谈、有着莫大的关系。


*** 在朝核问题上，强硬了几年的布什政府，最后恐怕“想不让步都不行”

由于能否谈出一个多边安全框架、去保障朝鲜弃核后的朝鲜半岛的和平稳定、保障能够顺利启动“朝鲜半岛经济整合”，对韩国而言似乎成了眼下最优先考虑的“最高国家利益”。

因此，东方评论员认为，在朝核问题上，强硬了几年的布什政府，最后恐怕“想不让步都不行”，要知道，一旦“中俄”因共同利益走向联合，并联手出击、华盛顿面临的就将是“巨大的麻烦”，这一点，相信华盛顿决策层通过“上海合作组织”准备将美国赶出中亚，特别是乌兹别克政府已经明确“限期美军离开”的事实中、已经得到了深刻的教训。

在我们看来，“中俄”与美国在中亚的那场较量、足以让国际社会清楚地看出美国的无奈、清楚地看出华盛顿在同时面对“中俄”这两个大国时的“力所不逮”。


*** “中俄”联合军演将起到一种继续向美国展示强大力量的效果

实际上，明眼人是一看就知，在“中俄”在中亚出了美国的洋相之后，随着“中俄”联合军演在朝鲜半岛附近的正式展开，将起到一种继续向美国、日本、韩国展示强大力量的效果，而令人寻味的是，很可能在那个前后，北京主持的第四轮六方会谈也恰好进行到了“高潮部分”。

所以，东方评论员认为，只要韩国能从中国、俄罗斯这边得到足够的、对朝鲜半岛安全上的支持，那么，一旦华盛顿强硬到底，韩国是极有可能从国家、民族的长远利益出发、依靠中俄、不顾美日的反对、自行启动朝鲜半岛经济整合进程的。


*** 今后华盛顿可能的谈判策略

东方评论员认为，如果局面果真演变到这一地步，这将导致东北亚格局的巨变、导致华盛顿东北亚、甚至有可能是东亚安全政策的重大失败。因此，在东方评论员看来，华盛顿如果够聪明的话，在这轮会谈中，今后很可能会采取一种“表面上仍然强硬、但实际上却相对现实”、从而不至于强硬到让韩国彻底失望、而下决心抛开美国单干的谈判策略。

事实上，也正是存在有这一变数，我们认为，华盛顿在继续默许日本跳出来、以种种理由不停搅局、提条件的同时，恐怕也得着眼于“美朝各自让步”、以达成一个可行的解决方案：通过给朝鲜一定的经济补偿，换取朝鲜无核化目的、并在一个多边框架下、一来确保朝鲜半岛的稳定、二来确保美国在朝鲜半岛问题上仍然能起到的关键作用。


*** 华盛顿是一定会在朝鲜半岛之外、去寻找东亚的战略平衡的

显然，一旦美朝（实际上是中美）各自让步，达成了一个解决朝核问题的可行性协议，那么，这轮朝核会谈不仅对朝鲜半岛、而且还将对东亚战略格局产生巨大的影响：在我们看来，它将不仅可直接导致东北亚形成一套安全机制、而且必然会辐射到台湾问题、以及中日关系。

东方评论员认为，华盛顿是一定会在朝鲜半岛之外、去寻找东亚的战略平衡的。如果我们估计得不错的话，其结果很可能是出现一个比现在“紧张得多”的中日、韩日关系。


在一段来自日本报纸的消息之后，东方评论员将把关注的焦点转向日本国内，并结合日本国内政治动向，深入地谈谈中日关系的一个值得警惕的“新特点”。


《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com



