# -*- org -*-

# Time-stamp: <2011-08-02 20:44:14 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

#+STARTUP: indent

* 2005年4月25日 星期一

** 宋楚瑜访大陆行程初定亲民党先遣团抵北京

【台湾消息】亲民党主席宋楚瑜大陆行的先遣团二十四日高调自台北出发抵京，为宋楚瑜访大陆敲定具体的接待及会谈事宜。中共中央台办主任陈云林专程从海南博鳌赶回北京，与亲民党秘书长秦金生展开磋商。此外，陈云林还将专程从北京赶赴南京，在南京禄口国际机场迎接中国国民党主席连战一行。

综合香港大公报报道，亲民党秘书长秦金生所率的先遣工作团一行八人二十四日下午抵达北京，进行为期三天的行程、议题洽商。工作团涵盖议题组、行政组、党团组、行程组、协调组等，宋楚瑜亲信夏龙、「立院」党团干事长李永萍、政策中心主任张显耀、文宣部副主任吴昆玉、行政部副主任叶家宇等人参与。

亲民党先遣团抵北京

秦金生强调，无论是岛内民调、两岸或国际社会，都对宋楚瑜大陆行给予高度肯定及相当的期待。宋楚瑜确定五月五日登陆，将访问北京，和中共高层领导商讨两岸互动发展和机制外，也会返回老家湖南湘潭，并在上海和台商餐叙。在北京，宋楚瑜将赴清华大学演讲。这次先遣团到北京，是首个到大陆访问的亲民党团，感谢大陆方面给予热情接待。

幕僚强调，宋楚瑜是亲民党主席，是民间代表，不会有第二个身份。

晚七时十五分，陈云林和相关部局的负责人与亲民党先遣团在钓鱼台国宾馆十四号楼进行工作会谈。陈云林说，他在此前接受新华社采访时，已代表中共总书记胡锦涛向亲民党主席宋楚瑜先生发出邀请，很高兴被宋楚瑜欣然接受。他说，亲民党先遣团今次来京与中共就宋楚瑜访问的具体问题展开磋商，以加强两党合作，建立党对党对话的渠道，为推进和改善两岸关系，造福两岸民众做努力。

江苏准备接待宋楚瑜

至记者二十五日凌晨发稿时，双方的会谈还没有结束。据亲民党人士透露，今后两天还会与大陆方面继续讨论具体事宜。宋楚瑜一行在大陆将访问上海、南京、湖南长沙、北京四地。

值得关注的是，他的行程是先到上海，然后到南京中山陵谒陵。据称，宋楚瑜曾多次表示他个人是孙中山先生的崇拜者，所以来大陆必去中山陵敬谒。

中山陵再度成为世人关注的热点。据了解，目前，江苏省台办的官员们正全力以赴接待连战一行，同时，已经着手准备制订接待亲民党主席宋楚瑜的方案。

行程安全保卫级别高

另据最新消息，中共中央台办主任陈云林将专程从北京赶赴南京，在南京禄口国际机场迎接中国国民党主席连战一行。

中共中央对连战一行的来访高度重视，实行高规格接待，目前已经确定中台办主任陈云林近日将专程从北京赶赴南京，亲自去南京禄口国际机场迎接连战一行。据透露，四月二十六日下午，还将有一、二十名江苏台商的代表一同去机场迎接连战一行。

据悉，目前，内地报名参与采访的记者已逾四百人（不含港、台等境外记者），可以预见一场新闻大战在所难免。由于此次连战一行在南京的行程安全保卫级别高，所有的记者在进入任何一个采访地点都要接受极为严格的安全检查。

【时事点评】我们认为，前面说了，宋楚瑜在“立法委员”选举中失败后，其第一个动作就选择了去美国“闲居”。

*** 宋楚瑜分明是呆在美国“钓渔”

然而，在东方评论员看来，他哪里是闲居，分明是去那里“钓渔”。非常清楚，宋楚瑜在华盛顿可以说是与四面八方都在保持着联系。表面上看，他在美国话并不多，然而，在台湾却到处都能听到他的声明：什么不排除与陈水扁合作、清算国民党的党产问题呀，什么继续站在蓝营中反对台独呀，还有、就是放出风声,即：他有意赴大陆展开和平之旅，推到两岸和谈，并表示他与大陆官员有过接触。


*** 他同华盛顿谈的“足够深刻”、“足够透彻”

大家如果细心的话，当然会发现，他好像与美国之间没有什么，然而，对他与华盛顿之间的那段历史，在这里我们不想去翻他的“底案”，在东方评论员看来，仅就当时而言，仅从他直飞华盛顿，并在那里一住就是十几二十天的事实，就足以说明他同华盛顿谈的“足够深刻”、“足够透彻”。


*** 用“有心登陆大陆”做“名片”，宋楚瑜在“玩权谋”上的确有两下子

东方评论员认为，宋楚瑜选择在华盛顿“从蓝色变成橘色”、选择住在华盛顿的时候与岛内的死敌陈水扁“眉来眼去”，并对刚才还是“国亲联盟”这一条战壕内的国民党“大加鞭鞑”，并特别是向北京方向“示好”：“有心登陆”，这一整个过程充分体现了宋楚瑜在“玩权谋”上的确有两下子。

在我们看来，他这一整套动作的展开，显然是在用北京“做渔饵”，用“有心登陆大陆”做“名片”、在北京和华盛顿面前介绍自己的“新身份”，从而“意在”引起中美双方的重视；

*** 宋楚瑜似乎在打算从“台湾外部”找到“着力点”


值得注意的是，失败的宋楚瑜再次表现出“其立场的摇摆性”，为了继续保证“有一方舞台”、以保证他在台湾政坛上“继续保持畅快的舞步”，宋楚瑜选后、可以说立刻就飞到了华盛顿，东方评论员就注意到，宋楚瑜可以说是在一边破口大骂国民党“不仁义”、一边登上那架越洋飞机的。

据东方评论员所知，在华盛顿一呆就是几十天的宋楚瑜，除了与华盛顿方面密谋“如何如何”之外，并还曾经与期间赴美国访问，沟通“反分裂法”方面的国台办官员见过面，显然，宋楚瑜似乎在打算从“台湾外部”找到“着力点”。

实际上，直到宋楚瑜与陈水扁见面，签定“联合声明”“十点共识”之前，最早放风有意访问大陆的并不是连战，而恰是这位“立法选举惨败之余、四处寻路”的宋楚瑜。

*** 向来“精通政治诈术、且有远大抱负”的宋楚瑜，想“多玩几年”

首席评论员指出，今天的台湾政治局面，总体上看，那个“非常听华盛顿话”的陈水扁、民进党相对“极度亲日的”李登辉、台联党而言，“还算是个缓独角色”，其“台独时间表”说白了就是按着华盛顿根据自己的全球战略利益制定的“台独时间表”进行“临摹”的，而在台湾立法院内，第一大党是民进党、其次是国民党、再次才是宋楚瑜的亲民党，最后才是李登辉的台联党。

因此，宋楚瑜知道，如果继续保持“蓝色”，那么，他和他“排名第三”的亲民党不过是“排名第二”的国民党的“小伙伴”，而且，由于亲民党席位严重萎缩，而这种“严重萎缩”却主要是因为其选民大量被同属蓝营的国民党所吸收而导致的，如此一来，就是在泛蓝阵营内，宋楚瑜和亲民党的影响力也是“急剧缩水”。

在东方评论员看来，向来“精通政治诈术、且有远大抱负”的宋楚瑜，他比上了年纪的连战、当然想“多玩几年”、自然不甘就此完结其政治生命。

因此，如何在席位缩水的情况下、去增强影响力，就得另僻溪径，显然，根据我们的观察，此公将突破口选在了“变色”上，这就有了所谓的从“蓝营”中分化出一标“橘色”的人马来！


*** 要发挥“砣小压千斤”的重要作用

继而，又拿他的亲民党、虽然是第三位的小党、却可以在台湾政治全局上“砣小压千斤”的事实，力图去左右整个局面、为自己扳回一方“可以继续跳舞的舞台”。也就是说，他在真真假假、闪烁其辞中，成功地让连战和陈水扁明白：在立法选举中，连战是“赢而未赢”、在，而陈水扁是“输而未输”，宋楚瑜想让“蓝营”过半，或者“绿营”过半，那都不过是他宋楚瑜的“一句话”而已。


*** “变色”一招，虽然算盘得精巧，却又露出宋楚瑜的致命伤

然而，“一向摇摆不定的”的本性，这本来就是宋楚瑜在“立法院选举”中“泛蓝”选民流向国民党，从而丢掉大量席位的关键因素，显然，“变色”一招，虽然算盘得精巧，却又露出了这个致命伤，那就是再次让泛篮民众不再相信他，如此一来，“不蓝不绿”而面泛“橘色”的宋楚瑜、和他的亲民党在今后的一连串的选举中，将面对着泛蓝更大的不信任。


*** 华盛顿“逼迫”陈水扁和宋楚瑜“联合的”目的

也就是在这种情况下，华盛顿和陈水扁显然抓住了他的这一致命弱点，迫使宋楚瑜做出了更多的让步，更多地以华盛顿和陈水扁的意见、形成了一个所谓“主题”为“稳住现状、伺机台独”的“中间路线”。

然而，在东方评论员看来，陈水扁尽可以去挤压宋楚瑜，然而，在华盛顿面前，陈水扁又是被挤压对象。我们认为，华盛顿“逼迫”陈水扁和宋楚瑜联合“稳住现状”的目的主要有两重，第一，在华盛顿无力从中东抽身的时候，避免大陆动用“反分裂法”、启动“非和平方式”；

第二，就是想在这一期间里，全面瓦解泛蓝、继而全面瓦解国民党、瓦解台湾“亲美台独”之外的一切政治势力，这中间，其目标不仅有连战的国民党，也有”亲日的”李登辉的、那个刚刚参拜过靖国神社的“台联党”。

也正因如此，李登辉一怒要向民进党“全面宣战”，下面，我们就先来看看李登辉的最新表演，之后，将继续讨论连战、宋楚瑜先后“登陆”的前因后果。


《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 连宋访大陆绿营内讧李登辉扬言火拼陈水扁

【台湾消息】据报道，因不满扁政府没有以「公权力」限制连宋登陆，泛绿盟主李登辉一怒要向民进党全面宣战。不仅在年底县市长选举中，台联党将大量提名与民进党抗衡，而且更积极招募党员，大挖民进党墙角。

连宋出访大陆引发绿营内部炮口相向。台联党秘书长陈建铭转述，李登辉下令对民进党「全面宣战」，年底县市长选举，台联党将大量提名，即使和民进党玉石俱焚，也在所不惜。他说，对于扁政府不以「公权力」限制连宋访问大陆，李登辉难掩不满情绪，连宋出访大陆期间，李登辉仍会持续开炮，并对扁政府施压。

陈建铭进一步扬言，扁政府坐视连宋出访大陆，正好增加台联党任务型「国代」选举逆势操作的空间，李登辉和一百个本土社团批连宋、轰扁政府，就是代表台湾民众和民进党决裂；他说李登辉将亲自操刀，将「五一四国代选举」切割成「中国」对「台湾」的战争，支持「中国」的选民就投给国、民、亲三党，坚守台湾意识的就请投给台联党。

台联党不仅要在年底县市长选举中与民进党一比高低，而且还要在党员人数上与民进党较劲，于二十四日一口气召集了一千三百多人入党，并在台北县举行千人集体入党誓师大会。

对于台联党大动作「全面宣战」，「立院」民进党团书记长陈景峻则表示，这是台联党面对选举压力下，企图争取泛绿板块所做出的政治动作，民进党可以体会，但台联党若和民进党两败俱伤，只会让泛蓝坐享其成，民进党呼吁台联党切勿做出让「亲痛仇快」的举动。


【时事点评】在东方评论员看来，连宋出访大陆引发绿营内部“炮口相向”，这也怪不得李登辉，客观上讲，做为都戴着一项“绿帽子”的陈水扁和李登辉而言，陈水扁按华盛顿的要求行事，的确毒了点，也的确“伤了李登辉的心”。

只是对于扁政府不以“公权力”限制连宋访问大陆，李登辉如此地“难掩不满情绪”恐怕有点“无的放矢”，在东方评论员看来，李登辉一把将美国人给捅出来，那才是有种。


*** 美国欲“全面扫清外围、全面控制台湾”

东方评论员认为，一旦陈水扁和宋楚瑜在华盛顿的搓合下、“正式联合”，并在“十点共识”的“掩护下”开始实际行动，那么，华盛顿实际上就开始了其“全面扫清外围、全面控制台湾”的进程：即，不仅要让大陆的对台政策“无法染指”台湾岛内事务，也要让日本对台湾的传统影响、因没有台联党这个内部因素的配合、今后也无法直接干预台湾事务。

而不是象今天这样，华盛顿让陈水扁“暂停台独”，却招致秉承日本旨意、欲以“急独”去刺激大陆、并挑起中美提前摊牌的李登辉一派的猛烈攻击和强烈反对。

因此，只有避免这种局面，一旦美国在战略上需要，就可以全面操控“台独”“只为”美国的战略利益服务，从而为其今后一旦中东战略需要配合的时候、伺机打出“台独牌”时打下最为牢固的基础。


*** 已经被华盛顿和陈水扁“捕获”的宋楚瑜，在相当程度上成了“嗟食者”


然而，在这些算计中，可以清楚地看出，宋楚瑜在华盛顿住了那么多天，还是有不少收获的，在东方评论员看来，其最大的收获就在于他的确因此受到华盛顿的“器重”，但是，其必须拿出的见面礼，就是在华盛顿、陈水扁欲瓦解国民党的计划中扮演“关键的角色”。

然而，同样，已经被华盛顿和陈水扁“捕获”的宋楚瑜，事实上已经失去了泛蓝民心的基础，在相当程度上成了“嗟食者”。在东方评论员看来，宋楚瑜也深知他今天的地位，已非当年“宋省长”叱咤风去”之时代可比。我们的看法是，他与陈水扁和解，展现他在两岸议题的高度企图心，是为他“政治生涯再创高峰”的盘算。

事实上，宋楚瑜将他与陈水扁和解，定位为从“泛蓝”的“极右路线”往“中间路线”的修正”，然而，东方评论员则注意到，他手下就有许多认为需要“泛蓝选票”才能延续“个人政治生命”的党内重量级“立委”，公开地将宋与扁“握手”就定位为“背叛”、以此与之划清界线。


*** 华盛顿和陈水扁就是想让宋楚瑜带着个“怪玩意”“登陆大陆”

事实上，就我们的观察而言，宋楚瑜和陈水扁达成的“十项共识”，已经让他落入了华盛顿和陈水扁的圈套，既将一个“自相矛盾”，“空洞无物”、还可按主观愿望去“任意解读”的“十项共识”，交给宋楚瑜，让他带到北京、去与大陆周旋。东方评论员认为，华盛顿和陈水扁的意图非常清楚，那就是，一方面满足了宋楚瑜“登陆大陆”、“赚取民意”的投机愿望、而另一方面，由于这个“空洞”的、自相矛盾的“十项共识”、实际上是一个让大陆“反对也不是”，因为，它里面有“所谓的承认“宪法一中”的“积极内容”，但是“肯定得似乎也很小心”、因为它里面的条款包蔵有莫大的祸心。


*** 陈水扁欲将所谓的“中间路线”去“一统江湖”

因此，国民党要想在台湾保留一个舞台，就必须在两岸互动中找准角色，而沦为在野党的国民党，除了这种政治动作之外、又有什么牌可打呢？

所以，东方评论员注意到，就在国民党副主席江丙坤率团前往大陆谒陵的时候，台立院的民进党团就“大加挞伐”，质疑国民党为何在326游行后就急着向中国朝贡、投降？并质疑国民党已开启第三度国共合作，战略就是“联共制”。还有，值得强调的是，陈水扁还建议举行“二度扁宋会”，声称什么“扁连也应排除万难，尽快坐下来谈”。

对此，首席评论员指出，陈水扁的一句、“建议举行二度扁宋会，扁连也应排除万难，尽快坐下来谈”的话，“真切地道出了”陈水扁、民进党欲将所谓的“中间路线”去“一统江湖”的真正用意，而对这个所谓的中间路线，东方评论员早就下了个定义，即美国控制下的“台独进程”。


*** 北京单纯地同宋楚瑜谈，实际上是在同“不承认一中”的陈水扁在谈

在东方评论员看来，华盛顿和陈水扁开始时就是想让宋楚瑜带着这个“怪玩意”“登陆大陆”，让大陆从这个基础上去与宋楚瑜谈。

我们认为，按华盛顿的想法，是让宋楚瑜登陆，但是北京没有兴趣，一来，陈水扁在和宋楚瑜的“十项共识”中玩文字游戏、归根结底还是没有“承认一中”，二来，就是宋楚瑜在投靠华盛顿和陈水扁之后，已经没有什么可以代表自己的观点的了。这样，北京单纯地同宋楚瑜谈，那就么落入一个陷井，即实际上是在同“不承认一中”的陈水扁在谈，这就造成了大陆在“一中前提”上“自废武功”。大陆怎么可能单纯地、与代表陈水扁的宋楚瑜去谈。

因此，北京对准备挟带这个、即拐弯抺角在“第一条”中、对“宪法一中”点到为止、却又以“更多条文”、去为“将来否认一中”提前埋伏笔的“怪玩意”、准备“登陆”的宋楚瑜、根本就“没有表示出兴趣”来。


*** 美国似乎就面对着另一种选择

因此，对急于想以一个“中程协议”暂时稳住台海、从而稳住朝核问题的华盛顿而言，面对一个台湾将是“台独党一党独大”的结局，北京当然有理由拒绝华盛顿的建议。这样，美国似乎就面对着另一种选择，那就是一改初衷，由那个已经被自己和陈水扁，联同宋楚瑜“整得咽咽一息”的、承认一个中国的连战“登陆”、到北京去谈，

东方评论员认为，连战登陆后，有一点是可以肯定的，那就是，只要北京最关心的台湾问题取得北京认可的进展、那么华盛顿最关心朝核问题“才有可能不继续恶化”。


*** 连战登陆，一个首要问题就是连战要“敢登陆”才行

然而，要让连战登陆，一个首要问题就是连战要“敢登陆”才行，在东方评论员看来，连战如果是个有胆量的政治人物，他在去年“319”、“320”中的表现就不应该是那个模样。

因此，我们认为，陈水扁是不会让连战出此风头的，欲打大陆牌、东山再起的宋楚瑜更不会愿意让连战抢去自己的风头，那个只认日本的李登辉更不用说，显然，在东方评论员看来，只有华盛顿“点头和保驾”，连战才敢在离开大陆60年后第一次“登陆”，并借此为自己的政治生涯写下“难得光辉的一页”。


*** 应了一句老话，那就是是“人算不如天算”

我们认为，有了承认“一个中国”的连战“先来谈”，那么，宋楚瑜的登陆的意义也就“无关紧要”、算不得什么突破了。最多不过是在“锦上添花”而已。由此可见，一个急于在两岸关系投机取巧的宋楚瑜，在自我丧失立场后，最终可以说是落得“两边不待见”，他想靠自己的力量“登陆大陆”打开局面，但是陈水扁不让，于是投靠华盛顿、在美国的安排下，就有了个“十项共识”，结果，这时，他再想登陆，北京又没有兴趣了。

结果，我们也就看到这让宋楚瑜极其尴尬的一幕，既，他“登陆大陆”、以“浴火新生”的构想，反成了被他痛骂的连战“大陆之行”的“新嫁衣”，真是应了一句老话，那就是是“人算不如天算”。

*** 大陆在毫不留情地“剥去了宋楚瑜的体面”之后，却又高明地、高姿态地“赠送了”宋楚瑜一个体面


然而，被连战抢先登陆，宋楚瑜情况可以说是“相当尴尬”。事实上，大陆在“剥去了宋楚瑜的体面”之后，却又高明地、高姿态地“赠送了”宋楚瑜一个体面。

我们认为，北京通过先邀请连战访大陆、事实上就已经毫不留情地“剥去了宋楚瑜的体面”，而在宋楚瑜愿意以个人身份，而非民进党所说的“代表陈水扁”的身份赴大陆之后，北京又通过国台办出面邀请宋楚瑜访问北京，并表示将高规格地礼遇宋楚瑜的方式，从而高姿态地“赠送了”宋楚瑜一个体面。

首席评论员指出，宋楚瑜方面强调，说他此次到大陆，是以亲民党主席的身份，是民间代表，不会有第二个身份。在我们看来，这显然是北京“一剥一送”的妙处之所在。


*** 大陆的思路非常清晰，一不按华盛顿的套路下棋，二还是要“下好连战、宋楚瑜这两颗棋”


显然，大陆的思路非常清晰，既一不按华盛顿的套路下棋，二还要下好连战、宋楚瑜这两颗棋，通过邀请两人一先一后访大陆，既给了鲜明坚持“一个中国”的连战以最高的礼遇，同时，也让“承认宪法一中”的宋楚瑜、在体味到摇摆不定的苦果之后，却又“可怨可言”，最后还让也那个、不管怎么样、也与宋楚瑜一道承认了“宪法一中”的陈水扁“无话可说”。

在东方评论员看来，北京的“如此这般”，一来打开了两岸交流的“关口”，二来，通过同时与台湾“两大在野党”都建立了沟通管道的方式，达到让连宋两人“相互竞争”，从而事实上达到了让台湾岛内连战、宋楚瑜、陈水扁三人，和他们的国民党、亲民党、民进党“三党”相互竞争的局面，从而为在两岸谈“中程协议”的过程中，迫使陈水扁承认”九二共识“，启动“两岸三通”谈判的打下基础。


另外，连战的“和平之旅”将于4月26日、也就是明天就要启程，首站将前往南京、而我们又得到消息，说的是李登辉准备发动一万人在机场“用鸡蛋轰炸”连战一行人，以李登辉这把年纪、还要如此地上窜下跳，东方评论员还得善意地提醒一番“还是注意点自己身体的好”。

还有，在我们看来，素有“台独教父”这称谓的李老先生、亲自上阵却也只能“发动一万人”、是否太少了一点，当然，我们还是先来看看李登辉为“只需集中一万人”所做的注解，之后，东方评论员将继续今天的台湾话题。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
