# -*- org -*-

# Time-stamp: <2011-08-04 00:17:49 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

*  2005年6月13日 星期一



** 中欧纺织品协定：一个敲打美国的工具？


　　【北京消息】北京时间11日凌晨1时，中欧双方就中国部分输欧纺织品问题达成了协议，签署《备忘录》。根据《备忘录》，欧盟承诺对源自中国的棉布、T恤衫、套头衫、裤子、女式衬衫、床单、女连衣裙、胸衣、桌布、亚麻纱等十类纺织品终止调查。

　　《备忘录》的签署，标志着差点升级为“贸易战”的中欧纺织品贸易摩擦问题得以缓解。“谈判就是一种妥协的产物，在纺织品贸易问题上，中欧双方都做出了一定的让步”，国务院发展研究中心对外经济研究部副部长隆国强说，“这一备忘录的最大成果就是中欧双方将中国加入WTO时签署的242段条款更加具体化，今后双方都有了一个可以接受并可以预期的出口增幅。”

　　《备忘录》是“妥协”亦是“双赢”

　　根据《备忘录》内容，中欧双方同意，在2005年6月11日至2007年底期间内，对上述十类纺织品合理确定基数，并按照每年8%至12.5%的增长率确定中方对欧出口数量。

　　事实上，中欧双方在解决这一贸易摩擦问题时都选择了“退一步，海阔天空”。欧盟的让步体现在对停止特保调查，以及未来3年中，10类受调查纺织品对欧出口增幅将高于7.5%（注：242条款中规定的增长幅度）。同时，欧盟也承诺对此次未受调查的其他纺织品将克制使用242条款。而中国的让步，则是接受对欧盟已经发起调查的10类纺织品对欧出口增幅的限制。

　　商务部研究院研究员、国际贸易问题专家梅新育博士对此表示，“欧盟对中国10类纺织品进行调查已是既成事实，而且因为有242条款这一紧箍咒，欧盟随时可以逐一对中国的产品发起调查并设限，从这一点上来看，中国所做的也算不上什么太大的让步。”

　　也正是如此，在长达10个小时的谈判之后，薄熙来在新闻发布会上表示，“今天谈了10个小时，还是值得的。”

　　梅新育分析，尽管8%~12.5%的年度增长率看起来并不算很高，而且今年1~4月，我国纺织原料及纺织制品出口增长率为18.9%，也大大超过该《备忘录》设定的8%~12.5%年度增长率。但也必须看到，今年年初纺织品出口高增长率的原因是纺织企业和美、欧进口商担心美欧政府对中国纺织品设限，因而开足马力生产、加快出口，这种高增长率必定不可持续。

统计数据显示，从3月份开始，我国纺织品出口增速就逐月下降，梅新育认为，即使完全停止与欧盟的特保争端，并且不设定8%~12.5%的年度增长率，今年全年纺织品出口增长率也很难达到18%。因此，8%~12.5%的年度增长率还算是一个比较宽裕的限额。


　　“这项协议对于中方来说是公正的，也为欧洲及它国的纺织业腾出了准备时间。”曼德尔森在新闻发布会上曾表示，这项协议也让欧盟纺织企业获得了一定的喘息空间，毕竟已经发起调查的10类中国纺织品在今后3年有了比较确定的增长率。

　　同时，由于欧盟承诺“克制”使用242条款，即今后对其他种类的纺织品不会像这次挑起争端那样滥用，而是尽可能不使用，即使使用也要事先与中方充分磋商，这样亦可以保证中国企业在今后几年无需过分担心来自欧盟的特保措施，可以借此期间，合理安排受限制产品的生产和对欧盟市场的出口，并提高出口产品的附加值。

　　一个“敲打美国的工具”？

　　薄熙来在评价这次谈判时指出，“在解决纺织品贸易的问题上，欧盟不同于某些国家，不是断然采取单方面行动，而是一直谋求通过双方磋商，友好妥善态度解决双边贸易关系。”

　　在梅新育看来，欧盟方面在此次谈判中表现出了解决问题的诚意，既没有不合理地漫天要价，也没有单方面超越国际规则采取行动。

　　中欧纺织品贸易摩擦问题解决之后，更多关注的目光投向了中美双边经贸关系的走向。今年7月11日，中美商贸联委会将在京举行，中国国务院副总理吴仪与美国商务部部长古铁雷斯、美国贸易代表波特曼将就双边经贸摩擦问题进行磋商。而本月初，后两者来华期间，与中方的磋商未达成任何成果。

　　隆国强指出，这一次中欧双方之间达成谅解，“给了中国人一个工具去敲打美国”，但由于中美之间经贸关系更为复杂，美国在纺织品争端问题上是否会轻易让步仍是一个问号。在隆国强看来，纺织品问题只是中美贸易摩擦中的一个片断而已，中美经贸关系是“一揽子问题”，人民币汇率、知识产权问题、长期以来的贸易不平衡关系，都是中美经贸摩擦的焦点所在。而由于美国国内政治存在压力，部分政客要向选民证明自己，就必然会随时用“纺织品问题”作为“替罪羊”来敲打中国，希望在双边经贸关系中占据主动地位。



【时事点评】在东方评论员看来，从6月10日下午到11日凌晨，中欧可以说在上海西郊宾馆进和地“长达10小时的艰难磋商”，并在“最后一分钟”的时候、双方才在《备忘录》上“签字划押”。

*** “二四二条款”让中国从一开始处于被动地位

中欧经过艰巨的谈判才达成的这项协议，双方是各让一步，这表现在中国和欧洲分别得到了一部分，其中，“欧盟得到的利益”是，给十种纺织品的中国入口年增幅设下百分之八至十二点五的上限，要到2007年十二月三十一日之后，才对中国纺织品“全面开放”市场。

而“北京得到的利益”则是在其它产品上，即：欧盟承诺“在其它纺织产品上”启动特殊保障措施时“采克制态度”。

必须承认的是，这次争端，也是中国当年在入世协议中“作出的一些让步”产生的后遗症，比如说，关于纺织品贸易的“二四二条款”就是其中一例、这个“二四二条款”的确让中国在对抗类似“不公平待遇”中、从一开始就处于被动地位。（详细情况，我们将在下面点评中进行展开）


*** 在“十大纺织品”的问题上，《备忘录》将“二四二条款“具体化”了

如果我们在这种基础上去评判这份《备忘录》的话，显然，这一备忘录的“最大成果”就是中欧双方、在“十大纺织品”的问题上，将中国加入WTO时签署的二四二条款“具体化”了，这也就令今后双方在纺织品问题上、都有了一个可以接受、并可以预期的出口增幅。

首席评论员指出，就结果而言，我们想强调两点：第一，在“十大纺织品”问题上，中欧双方似乎都做出了一定的让步，但是，客观上讲，这以中方让步为主，结果是，欧盟承诺对源自中国的棉布、T恤衫、套头衫、裤子、女式衬衫、床单、女连衣裙、胸衣、桌布、亚麻纱等十类纺织品终止调查。北京则承诺，在２００５年６月１１日至２００７年底期间内，对上述十类纺织品合理确定基数，并按照每年８％至１２．５％的增长率确定中方对欧出口数量，从而给了欧洲纺织业两年多的时间“调整”；


然而，我们必须看到的是，过去几年，在配额制下，中国向欧盟出口纺织品增值年均达24%，因此，在中欧达成协议之后，欧洲企业所受的保护比过去几年时间里“更大”，显然，就这点而言，中国做出的让步很大。只是，中国在让步的同时，也确保了８％至１２．５％的增长率。

第二，在其他纺织品问题上，则以欧盟让步为主，承诺在“其他纺织产品”问题上“采克制态度”：即，欧盟承诺在２００５—２００７年期间，对于上述十类产品之外的２００５年实现一体化的中国纺织品克制使用中国加入世界贸易组织报告书第２４２段条款；２００８年，对所有２００５年实现一体化的中国纺织品克制使用“２４２段”条款。

但是，东方经济评论员认为，我们在看到欧盟所承诺的“克制”的时候，也必须看到，这种“克制”是一种意愿，而非具体指标，也就是说是种“软制约”，而不是中国做出“有数值的让步”那样、是种“硬制约”。



*** 很难用“谁输谁赢”去简单地下结论

不可否认的是，这份《备忘录》却是中国摆出“不惜打贸易战”的姿态后“才签下”的。在东方评论员看来，正是北京敢于打贸易战的“决心与实力”、而避免了一场贸易战和由此引起对中欧战略关系的重大破坏、并谈下了“8%到15%”的增长率，并让欧盟也承诺在援引“242条款”的时候，愿意接受这个“软制约”、从而“部分放弃”通过中国入世时签下“242条款”时、所获得的权利。

只是在我们看来，欧盟与中国之间的“政治关系”是良好的，这就为双方保持经济合作、达成协议创造了“良好的基础”。事实上，因为，中欧双方“都没有人”想通过这个《备忘录》、在政治、经济上弄出个输赢来。因此，不难看出，这份《备忘录》很难用“谁输谁赢”去简单地下结论。


为了更好地说明问题，我们再来看一则消息。之后，东方经济评论员、时事评论员将继续这个话题进行展开。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 欧盟批评美国呼吁对话解决贸易争端

【综合消息】据英国金融时报报道，欧盟贸易专员彼曼德尔森敦促美国采取更趋和解的方式解决贸易争端，此前欧洲和中国达成了一个限制纺织品进口的协议。曼德尔森先生表示，欧盟和中国周五达成的这一协议将有助于遏制欧洲的贸易保护主义压力，并表明贸易争端可以通过建设性对话予以解决。美国已实施进口配额措施，以抑制来自中国纺织品进口的上升。


“美国选择先采取行动后进行会谈，这样可能会使谈判稍困难些，因为中国可能会作出不同的反应。”曼德尔森先生上周末表示。他还以纺织品争端的成功解决为例，批评美国就飞机制造商波音和空中客车补贴问题的长期争议，在世界贸易组织内采取法律行动。世贸组织的争端解决机构今天将开会，首次研究空中客车与波音的申诉。“我的观点是，当你发现贸易摩擦发生时，总是就应该进行对话，与波音和空客有关的争端当初就该尝试对话，”他表示。

欧盟和中国周五达成的协议有可能被欧盟视为曼德尔森先生取得的第一个重要成就。欧盟与美国在有关飞机补贴的谈判破裂后，曼德尔森先生的谈判技巧一度遭到怀疑。

欧盟某国的一名外交官昨天表示：“这正是开展贸易外交应采用的途径。中国在全球经济中的作用明显上升，我们需要同中国进行谈判并开展生意。”这名外交官所在国家曾警告说，不要和中国进行对抗。然而，曼德尔森先生针对美国政府处理贸易争端做法的批评，可能会激怒美国。

欧洲纺织服装协会总干事威廉•拉金昨天表示：“我们仍需仔细研究细节，并评估结果对我们意味着什么。”纺织行业过去对中国是否能够并愿意落实自动限制表示担忧。今年1月份纺织品进口配额被取消后，令中国纺织品在欧盟和美国销量激增，自那以来，纺织品在欧盟和美国已成为一个爆炸性政治问题。

** 吴仪在港表示中国坚决反对将经贸问题政治化

【综合消息】中新社香港六月十三日电中国国务院副总理吴仪在此间表示，在处理各国间的贸易摩擦时，中国坚决反对动辄就设限和制裁，更加反对将经贸问题政治化。

吴仪在今天召开的太平洋地区经济理事会(PBEC)第三十八届国际年会作主题演讲时说，全球纺织品贸易一体化前后，中国政府充分理解有关各方的关注，主动采取加征出口关税、降低出口退税率、实行出口自动许可等自律措施。但最近，美国对中国部分纺织品单方设限，极大地损害了中国企业享受全球纺织品贸易一体化成果的权益。

她表示，中国强烈呼吁有关国家要尊重世贸组织规则，通过平等对话和协商，共同努力，妥善处理纺织品贸易问题。

吴仪指出，随着各国经贸联系日益紧密、规模日益扩大，出现一些贸易摩擦是正常的，关键是如何处理。六月十日，中欧双方签署《备忘录》，就解决纺织品贸易问题达成了一致，再次证明只要本着平等互利、相互尊重的原则，充分考虑和照顾彼此的关切，加强沟通和磋商，即使出现贸易摩擦也是能够妥善解决的。





【时事点评】在东方评论员看来，由于中国和欧洲手头上都有与美国需要处理的“政治、经济问题”。

*** 欧盟在与中国达成协议之后，转头就批评美国丝毫不令人奇怪

我们注意到，欧盟贸易专员曼德尔森强调了这么个观点，即，“美国选择先采取行动后进行会谈，这样可能会使谈判稍困难些，因为中国可能会作出不同的反应。”

东方经济评论员认为，曼德尔森的这个“中国可能会作出不同的反应”的“观点”，其实是一语道破了中欧抢在最后一分钟也要达成协议的“真实意图”，那就是，《备忘录》的签署，在某种意义上讲，是中欧计划自己先行解决问题、然后再集中精力去对付美国的必然。

因此，在经济评论员看来欧盟在与中国达成协议之后，转头就批评美国、并“呼吁对话解决贸易争端”是丝毫不令人奇怪的。

*** 在某种程度上，《备忘录》已经成了解决纺织品争端的一份“标准的”“协议书”

我们认为，在中国与欧盟达成协议之后，在某种程度上，《备忘录》已经成了解决纺织品争端的一份“标准的”“协议书”，也就是说，北京和华盛顿稍后开始的谈判，在纺织品方面、必然将以这个标准为基础来进行。在东方经济评论员看来，北京在与华盛顿之间、如果不想打贸易战的话，那么，将来可能达成的协议，“在内容上”不会与这份“备忘录”有什么大的出入。


*** “给了中国人一个工具去敲打美国”的说法，虽不够准确却有几分道理

否则，欧盟也一定会找北京的麻烦，从这种角度看，《备忘录》可以说等同北京面对华盛顿、将“必须坚守的底牌”、以“无差别对待”的名义给亮了出来，因此，在经济评论员看来，那种认为《备忘录》“给了中国人一个工具去敲打美国”的说法，虽然不够准确，但却有几分道理。

如果我们再回过头去看那个“8%到15%的年增长率”，就不难看出，中国与欧盟的“协议”，是各自在充分考虑到了“美国因素”之后、考虑到欧洲与美国都可能让步的程度、而“一并制定”的。

事实证明，欧盟方面在此次谈判中、的确表现出了“解决问题的诚意”，既没有不合理地漫天要价，也没有单方面超越国际规则采取行动。

因此，在东方经济评论员看来，整个过程就有如早已经安排好的剧本一般，中欧“抢在最后一分钟”达成了“协议”。显然，中国和欧洲之所以都想拿到这个“备忘录”，其中的一个重要目的就是“及时抽身”，以分别对付华盛顿。在这种情况下，经济评论员认为，我们就这份《备忘录》、也就更难用“谁输谁赢”去简单地下结论了。

*** “中欧”在彼此谈好之后，立刻就一致将炮火对准了华盛顿

我们注意到，就在“中欧”在彼此谈好之后，立刻就一致将炮火对准了华盛顿。不难看出，北京和欧盟“都在以刚刚达成的《备忘录》为例子”，猛烈抨击华盛顿那种“先采取行动后进行会谈”的“霸道作风”。

其中，欧盟首先要做的，就是逼迫华盛顿坐下来，再谈“波音与空客”的补贴问题。事实上，曼德尔森已经在以纺织品争端的成功解决为例，开始批评美国就飞机制造商波音和空中客车补贴问题的“长期争议”了。


*** 北京剩下来的也只是与华盛顿“好好谈了”

与此同时，在纺织品上、在先与欧盟解决问题之后，北京剩下来的也只是与华盛顿“好好谈了”。

我们注意到，吴仪的讲话、再次提到了这份“备忘录”，我们也注意到，吴仪公开表示“更加反对将经贸问题政治化”。

总体而言，北京这是在强调这场“中欧美”的纺织品争端中，中欧的协议是从经济角度去解决的，因此显得非常顺利。而中美之间显然加杂了太多的政治因素，这也就应了欧盟贸易专员曼德尔森强调了这么个观点，即，“美国选择先采取行动后进行会谈，这样可能会使谈判稍困难些，因为中国可能会作出不同的反应。”


*** 美国在制定“世贸规则”时，做的准备工作“非常之充分与细致”

经济评论员认为，按照《中国加入世贸组织工作组报告书》二四二条款（f）项，依据此项条款对中国纺织品采取的特保措施不得超过一年。这一规定对中国是非常不利的，这就是说，如果诉诸世贸组织争端解决机制，可能世贸组织调查、初裁、终裁全部程序尚未全部完成，美国、欧盟的特保措施就“已经期满”。

在这种情况下，我们就可以清楚地体会到“世贸组织旷日持久的争端解决机制”，对“欧美”这个“世贸规则”的游戏规则“制定者”而言，其优势是一开始就存在的。

如此一来，“欧美”可以“完全实现”其目的，反倒是中方最后将“一无所得”，尤其值得强调的是，美国发动此次争端所依据的是其“国内法”、是美国《一九七四年贸易法》“241条款”，从内容上看，“241条款”远远超过了“242条款”，其中，明确规定“在没有再次申诉的情况下，该数量限制的期限不应超过一年”。

在这种情况下，我们也不难看出，美国在制定世贸规则时，在参考其“国内法”具体条款方面，所做的准备工作是多么地“充分、细致”。

显然，根据这一条，美国人就可以用“反覆申诉”，“反覆采取特保措施”的方法、使争端始终处于“待解决状态之中”、而美国人始终可以凭借其“国内法”来单方面设限、制裁。

不难看出，由于中国加入世贸时签下的“242条”、以及美国《一九七四年贸易法》的“241条款”，北京在与华盛顿谈判时，会困难得多。


*** 中美间的“这一揽子经济问题”，已经不能简单等同于“经济问题”了

另外，在我们看来，纺织品问题只是中美贸易摩擦中的“小问题”而已，非常清楚，中美经贸关系是“一揽子问题”，人民币汇率、知识产权问题、长期以来的贸易不平衡关系，都是中美经贸摩擦的焦点所在，而这些问题中、特别是人民币汇率问题、更是中国不可能做出让步的核心问题，其牵扯面之广、已经不能简单等同于“经济问题”了，实际上事关中国的“经济安全问题”、甚至“国家安全问题”。

显然，东方评论员认为，北京虽然口头上“反对将经贸问题政治化”，但是，中国领导人心时非常清楚，美国人就是要“借经济问题”“解决”政治问题，解决“中国威胁论”中的、各种各样的“实际问题”。


*** 很可能是打到“贸易战边缘”之后，甚至开始打贸易战之后，中美双方才会收手、妥协

因此，首席评论员指出，我们也必须正视经贸问题已经被华盛顿政治化了的事实，如此一来，中美间要解决“这一揽子问题”的难度就大得多，华盛顿是瞄准了“人民币问题”，是三句不离“汇率”，而北京则总在美国的“农产品问题”打转，有意无意地拿“农产品开放”问题说事，显然，北京和华盛顿、都抓住了对方的一大软肋。

在我们看来，如果我们估计不错的话，中美间的这一轮角力，最后的结果很可能是打到“贸易战边缘”之后，甚至开始打贸易战之后，中美双方才会收手、妥协。

在我们看来，中欧之间达成了这项协议本身，其最大意义在于“避免了中欧贸易战争”，这对与美国都有大把贸易争端在手、且同华盛顿在全球战略上有结构性冲突的“中欧”双方，都是好事情。

此前，欧美关于“波音和空客补贴”问题的谈判已经破裂，而美国商务部长的北京之行，也是空手而归，所以东方评论员认为，中欧抢在最后一刻“签字划押”《备忘录》，给华盛顿的信号也是明确的，那就是，“意在渔利”的美国、在“不要指望中欧互斗”的情况下，如果不想打“美中”、“美欧”贸易战的话，那就只能坐下来“彼此好好谈”。

这样，北京与欧盟先期解决彼此间的矛盾、不仅对欧盟、就是对北京而言，也是非常具现实意义的一步棋。

另外，就如我们在上面所说的那样，“人民币汇率问题”才是中美间在经济上的核心问题，对华盛顿是否希望人民币升值，我们已经说得够多。因此，在下面的国际金融部分，东方经济评论员将着重谈谈，在格林斯潘的眼里，对美国经济而言，人民币到底是升值好、还是不升值好？

下面，我们还是先来看看新闻，之后，结合下面的一段新闻，经济评论员将详细分析一番：如果到了贸易战边缘，中美谈妥了，而人民币最后仍然是不升值，美元又必须“再软一点”，那么，为了实现目的，格林斯潘的眼睛又将盯着什么货币？是日元吗？

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
