# -*- org -*-

# Time-stamp: <2011-08-02 20:36:32 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

#+STARTUP: indent

* 2005年4月20日  星期二

** 小泉表示将根据“村山谈话”致力于改善日中关系

【东京消息】据日本媒体２０日报道，日本首相小泉纯一郎２０日表示，他将根据“村山谈话”致力于改善日中关系。

报道说，小泉当天在自民党与民主党党首讨论中说，他迄今一直开展重视日中关系的外交，（在历史问题上）具有与“村山谈话”相同的认识。

另据报道，日本民主党代表冈田克也当天与到访的澳大利亚总理霍华德举行会谈。他在谈到日中关系时说，在小泉首相领导下，日中关系发展不顺利，令人遗憾。他认为，（日中关系发展不顺利）的责任在于不停止参拜靖国神社的小泉首相。

１９９５年８月１５日，时任日本首相的村山富市发表“村山谈话”，承认日本过去进行的殖民统治和侵略对许多国家、特别是亚洲各国人民造成了巨大的损失和痛苦，表示要深刻反省，并向日本年轻人讲述战争的悲惨，以免再犯过去的错误。

 

【时事点评】我们注意到，在日本外相非常不快地回国之后、日本国内部分媒体对中国政府不仅拒绝道歉、反而严辞要求“日本应该就伤害中国人民感情的一系列言行进行道歉”的不满也是溢于言表。


*** “里外不是人”的小泉先生忽然“又一次”想起了“村山谈话”


然而，在东方评论员看来，在日本右翼操持部分媒体攻击中国的时候，小泉政府也正因“日本外相在北京败北”（日本媒体的原话）、不仅没有得到日本右翼所期望的日本社会舆论的巨大同情、反而承受着在被指责为在改善日本与中国、韩国关系上“不作为”的巨大压力，显然，也就是在这个“里外不是人”的背景下，这位小泉纯一郎先生忽然“又一次”想起了近乎十年前发表的“村山谈话”。

*** 所谓的“村山谈话”

既然小泉“又一次”想起了十年前的这段历史，那么，东方评论员在这里也自然得和大家一起回顾一下这个所谓的“村山谈话”。其实，所谓的“村山谈话”是在1995年，日本纪念战后50周年时，日本前任首相村山富市的一个谈话，村山当时表示“对于过去的殖民地统治和侵略造成的巨大损害和痛苦的历史事实诚恳接受，痛切反省和道歉。”

*** 中日建交后关系的几个转折点

显然，如果我们现在回朔中日建交后关系发展的历史，就不难看出大概有这么几个转折点，在1972年《中日联合声明》中，日本政府表示，“日本方面痛感日本国过去由于战争给中国人民造成的重大损害的责任，表示深刻反省”。1995年，日方发表“村山谈话”，首次承认对亚洲国家施行了“殖民统治和侵略”，表示“深刻反省和由衷道歉”。1998年，签署了《日中联合宣言》和《日韩联合宣言》，日方首次以书面形式承认对中国的侵略并口头道歉。事实上，在这之前、正是日本在对待和处理历史问题的“反省和道歉”态度的基础上，中日关系发展得还是比较顺利的。


*** 对小泉第一次“口是心非地”刻意地引用了“村山谈话”、村山前首相顿时是大怒


然而，这之后又有一个转折点，而且是一个向下的转折点，其标志性的年份就是2001年，标志性的事件就是日本首相小泉纯一郎在当年8月13日正式参拜靖国神社、并在参拜前为了降低他参拜靖国神社给当时尚好的中日关系带来的巨大冲击、在发表讲话中“口是心非地”刻意地引用了“村山谈话”的部分内容，也就是“基于错误的国策而进行了殖民统治和侵略”这一段。


据说，在看到小泉纯一郎一边拿着自己讲话为参拜靖国神社做挡箭牌、一边又在那里“断章取意”、只提“日本已经道歉”的“前半截内容”、而扔掉“深刻反省和由衷道歉”的“后半截”之后，在大分市家中的村山前首相顿时是大怒：“既然引用了我的讲话，又为什么去参拜呢？”，显然，小泉纯一郎拿着尽管在历史责任上“闪烁其辞”、但仍有积极意义的“村山谈话”去参拜供奉着甲级战争犯的靖国神社，这根本就是矛盾的。

何况，据村山自己讲，当时他在发表“村山谈话”时，其中对亚洲各国的人民表示“由衷的歉意”一句是他特意加进自己的讲话中去的，然而，这段特意加进去的内容、在意在为参拜靖国神社减轻影响的“小泉谈话”中却不见了踪影、彻底地消失了。如此一来，也难怪日本前首相村山、会怒斥小泉纯一郎的偷梁换柱，痛惜地表示：以后“‘村山讲话’就变成表面文章了，真是可耻。”

在东方评论员看来，就因为小泉纯一郎在2001年有过这么一段、这也是什么我们在前面一再说小泉纯一郎“又一次”想起了一度被称之为“和平定言”的“村山谈话”原因。显然，用村山的话来形容小泉在2001年“第一次”想起“村山谈话”的“不良目的”、的确可以说是“真是可耻！”


*** “村山谈话”其“含糊的一面”更是经常被日本用来当历史问题“已经解决”的挡箭牌

首席评论员指出，事实上，就是这么个“闪烁其辞、遮遮掩掩”的、虽然在“内容含糊方面”也被中国、韩国批评、但其体现的积极意义同时也被中、韩所肯定。也正是如此，“村山谈话”自十年前的世界反法西斯胜利50周年之际“问世”之后，其“积极的一面”就一直遭到日本右翼势力的强烈攻击，不仅如此，其“含糊的一面”更是经常被日本官员用来当历史问题“已经解决”的挡箭牌。


*** 在日本右翼如何利用“村山谈话”的问题上，有两点值得一提

在这方面，我们认为，在日本右翼如何利用“村山谈话”的问题上，有两点值得一提，一个是在“村山谈话”中，并未提及有关中国东北部地区或“满洲国”的字眼。因此，日本右翼就抓住这点，充分地加以发挥、甚至给出了一个日本对“满洲国”的“荒谬见解”，那就是：既然中国、韩国都不反对“村山谈话”，那么由此可见“日本和满洲政府是一体的。

第二，就是小泉纯一郎为了部分化解他第一次参拜靖国神社必将引起的冲击，也“第一次想起”这个“已经道过歉”的“村山谈话”、小泉纯一郎这样做的意图非常清楚，那就是，既然日本政府在侵略历史问题上“已经正式道过歉”，那么，他去参拜靖国神社仅仅是在“尊重日本人的文化传统”而已、


*** “村山谈话”竟然成了小泉理直气壮去参拜靖国神社的“跳板”

显然，在日本对历史认识问题上“有积极意义”的“村山谈话”、经小泉纯一郎如此这般地在意义上“偷梁换柱”、在文字上“挑挑捡捡”，就立刻“摇身一变”，竟然成了小泉政府“开历史倒车”最好的“挡箭牌”。

东方评论员认为，小泉纯一郎几年前在靖国神社前上演的这一出、充分地让我们看到了日本的右翼政治人物、为了参拜靖国神社、为了重走军国主义、是如何地在那里“挖空心思、殚精竭虑”的。

东方评论员认为，既然小泉纯一郎“第一次想起”“村山谈话”是别有用心，意在将之用来当作理直气壮去参拜靖国神社的“跳板”，那么，小泉的“又一次想起”的动机又是什么呢？在一段相关新闻后，时事评论员将继续回到这个话题，继续展开我们的讨论。


《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

**  小泉首相指日本已以行动面对二次大战争历史

【东京消息】据媒体报道，日本首相小泉纯一郎表示，日本过去六十年无发动或参与战争，已经是以行动面对二次大战的历史，日本和中国必需合作解决现时的外交危机，以免损害友好关系的发展。

小泉在国会发言时说，他一直视亚洲邻国为重要区域伙伴，并承诺会与邻国改善关系，他又不否认作为战争受害者，大部份中国人仍然对日本有不满情绪，但他拒绝就日军侵华战争，再作道歉，并重申日本政府应该就内地反日示威活动，提出抗议。

日本在野党民主党领袖冈田克也，就指责小泉忽视亚洲邻国，未能缓和与中国的紧张关系，批评在小泉领导下，日中关系正面对危机。



【时事点评】看了这段文字，相信大家对小泉纯一郎的“最新表现”不难立刻就获得一种印象，那就是“似曾相似”。


*** 小泉的“又一次想起”，满脑子想的还是如何利用“村山谈话”“已经道过歉”的这一点


请大家注意这段文字，小泉在国会发言时说，“......拒绝就日军侵华战争，再作道歉，并重申日本政府应该就内地反日示威活动，提出抗议。”显然，从他的态度来看、我们不难看出，在小泉“又一次想起”“村山谈话”的同时，他满脑子想的还是如何利用“村山谈话”“已经道过歉”的这一点、去为他“拒绝就日军侵华战争，再作道歉”
做“挡箭牌”。

另外，首席评论员也指出，按中国外长当着日本外相的面、强调日本在中国民众反日示威活动的问题上、要认清是什么原因引发中国民众反日示威的、而不要“本未倒置”的话来说，小泉纯一郎在接受他的外相北京之行的“工作汇报”之后、显然还在那里顽固地“本未倒置”。


*** 其实也是在为即将动身出席亚非峰会“以壮声色”。

事实上，在东方评论员看来，小泉纯一郎既然表态愿意在“村山谈话”的基础上致力于改善中日关系，也表态说在在历史问题上具有与“村山谈话”相同的认识，却也刻意地在登上飞往印尼的飞机之前、在国会上发表了这么一篇“态度仍然强硬”的讲话，其实也是在为即将动身出席亚非峰会“以壮声色”。


*** “后退一小步”后，对胡锦涛是否愿意会见自己，小泉心里似乎仍然没底

在历史问题上“口头回归”“村山谈话”的小泉纯一郎、却又在国会讲话中“拒绝就日军侵华战争，再作道歉”，这显然又是在自我矛盾，首席评论员认为，由此判断，小泉纯一郎在国内、外巨大的压力下“后退一小步”之后，对胡锦涛是否愿意会见自己，心里似乎仍然没有底。


*** 日本其它政治势力初步改变暧昧态度、开始真正动作起来

我们知道，通过这次日本外相的北京之行，北京已经正式向方方面面传送出了“不再单方面顾及中日关系何去何从”的强硬态度，也正是如此，相比中国而言、“更没有本钱”去面对一个完全破裂的中日关系的日本各种政治势力，终于也一改之前的、对小泉政府的政治冒险的“乐观其成”、并寄希望于北京最后会让步的暧昧态度，并开始真正动作起来、对小泉政府的所做所为开始施加压力和影响了。

巧的是，也是在今天，日本参议院宪法调查会通过并向其参议院议长提交了一份事关日本“和平宪法”的“最终报告书”，在一起了解相关内容之后，我们还会继续就中日关系再说几句。


《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

**  日本参议院宪法调查会通过并提交最终报告书

【东京消息】日本参议院宪法调查会２０日下午通过并向参议院议长提交了最终报告书。调查会在坚持宪法第九条第一项规定的“放弃战争”条款、“保持个别自卫权”问题上达成了共识，但在以行使集体自卫权和派遣自卫队为前提的国际合作问题上未能形成一致意见。

当天下午，日本参议院宪法调查会在自民党、民主党和公明党赞成，共产党和社民党反对的情况下通过了最终报告书，然后提交给参议院议长扇千景。根据这份报告书，各政党在坚持现行宪法的“国民主权”、“和平主义”、“尊重基本人权”三项原则，维持“象征天皇制”和“认可女性天皇”，以及“坚持国会两院制”、“文官指挥”自卫队问题上达成了共识。但在是否修改第九条第二项“不保持战争力量”，是否可以行使集体自卫权，以及是否在宪法中写明“自卫队存在”和“国际贡献”等问题上出现了意见分歧。

４月１５日，日本众议院宪法调查会出台了最终报告书。报告书提出坚持宪法第九条第一项规定的“放弃战争”条款，但认为应该修改宪法第九条第二项规定的“不保持军队”条款。报告书在是否可以行使集体自卫权以及在宪法中增加参与国际合作的规定上没有形成统一意见。此间舆论认为，在众参两院宪法调查会最终报告书出台后，今后的焦点将是制定有关修宪程序的“国民投票法案”。

日本众参两院于２０００年１月设置宪法调查会，对现行宪法进行广泛而综合的舆论调查。


【时事点评】东方评论员注意到，前段一直与小泉政府配合默契的日本在野党民主党、其领袖冈田克也，也在公开指责小泉“忽视亚洲邻国，未能缓和与中国的紧张关系，批评在小泉领导下，日中关系正面对危机”。


*** 日本在野党民主党真正担心的是什么


事实上，在我们看来，冈田克也真正担心的是北京的对日态度已经明朗、且不可能有大的调整之后，其结果必然是小泉政府如果继续一意孤行、“中日关系”也就真实地面对着破裂的可能，从而让自己在国际社会上、特别是在亚洲外交政策上再无回旋的余地。


*** 这个结果当然会让日本右翼大失所望

再就是，东方评论员认为，不论如何，日本国会宪法调查会的这份“最终报告书”、我们注意到，报告书提出坚持宪法第九条第一项规定的“放弃战争”条款，并在是否修改第九条第二项“不保持战争力量”，是否可以行使集体自卫权，以及是否在宪法中写明“自卫队存在”和“国际贡献”等问题上“都出现了意见分歧”，显然，这个结果当然会让日本右翼大失所望，然而，我们也必须看到，只要日本政府和社会在历史问题上不诚心诚意地“进行反省”，那么，日本宪法第九条第一项规定的“放弃战争”条款，迟早会被正式终结。

*** 根据我们的观察，日本是个“问题国家”

东方评论员认为，日本人为日本过去的对外侵略战争以及日军在战争中的暴行承担责任的心理意识是很弱的，也是很成问题的。根据我们的观察，日本是个“问题国家”，在日本国内、其占主流的观念是“在19世纪末20世纪初的帝国主义瓜分殖民地的狂潮中分一杯羹算不得犯罪”、在其侵略历史问题上、许多的日本人认为“太平洋战争是因美国对日本实施贸易封锁引起的”、远东国际军事法庭对日本战犯审判是“战胜者对战败者的报复“；

而对日本是世界上第一个、也是唯一一个遭受原子弹轰炸的国家，其辩解又是“要说战争是不义之举的话，我们大家都有罪”。东方评论员认为，正是在这种情况下，加上日本经济仍然没有完全走出困境、而中国又恰好在旁边高速的发展，这些都让近100年来一直自视比中国要强的日本人“心情不爽”，这些，都在被日本右翼所广泛地加以利用，利用去篡改历史教科书、抹杀侵略战争罪行、为军国主义招魂，重走军国主义道路、从而为日后有本钱与中国全面对抗打下基础。

*** 北京做出的一项果断、有远见的战略决策

由此可见，日本在历史上的“认识问题”绝非那些鼓吹“对日新思维”的专家学者所认为的“大可不必”，更不会真正地影响、阻碍中日关系的发展。

从日本外相“北京败北”之后在日本国内并没有出现与日本右翼所期望的一边倒的“同情气氛”、反而激起对小泉政策更多的批评来看，恰恰相反，北京这次强硬地死死地掐住日本历史问题这一症结不放、正是中国充分利用自己综合国力已经强大的条件、充分利用中日、中美、美日间相互掺杂的重大政治、经济、军事战略利益、巧妙地利用美国、日本国内不同的政治、经济利益集团的利益之争、以及国际社会各国间的利益之争，顶住了来自美国、日本保守势力施加在中国身上的各种压力、为了日后更好地维持住一个相对较好的中日关系、从而为最终化解美日军事同盟创造条件、而做出的一项果断、有远见的战略决策。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
