# -*- org -*-

# Time-stamp: <2011-09-15 10:45:16 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 东方时事解读2011年9月2日



+ 伊朗回击萨科齐称：伊朗核能研究仅具和平用途

【德黑兰消息】据媒体报道，继法国总统萨科齐抛出“伊朗若继续研发核武器将遭到先制军事打击”的言论之后，伊朗国营电视台于当地时间9月1日做出回应称，伊朗的核能研究仅限于和平用途。

伊朗国营电视台评论称，萨科齐不应该根据“不实的信息”对伊朗发表任何评论。该电视台还指出：“我们已经重复过多次，伊朗的核能活动是完全和平的，国际核能组织对此已经予以证实。”

此前，法国总统萨科齐曾发表讲话称：“伊朗在军用核能以及远程打击技术方面的野心，已经构成了一种正在成长的威胁。这可能导致其它国家率先对其发起攻击。法国将不惜一切代价阻止这样的局面出现。”不过，他并没有明确指出“其它国家”是哪个或哪些国家。

+ 土耳其因以色列拒绝为袭击加沙救援船道歉驱逐其大使

【卡拉奇消息】据媒体报道，由于以色列拒绝就去年袭击前往加沙的国际援助船队道歉，土耳其于9月2日宣布，将驱逐以色列驻土大使，限其在9月7日前离开土耳其境内，并断绝与以色列签署的所有军事协议。

美联社9月2日报道称，土耳其外交部长达武特奥卢2日称，土耳其将与以色列的外交关系降至二等秘书层次，并要求以色列驻土大使于下周三，即9月7日离开土耳其境内。

达武特奥卢还说，土耳其将暂停与以色列作为盟友签署的所有军事协议，认为“现在是以色列付出代价的时候了。”

对于土耳其的这些举动，据以色列一位高级政府官员透露，以总理内塔尼亚胡的办公室正在举行紧急磋商会谈，以决定如何做出反应。

【时事点评】在东方评论员看来，就这个所谓的“回击”，特别是之前的、由法国总统萨科齐抛出的那份“伊朗若继续研发核武器将遭到预防性军事打击”的言论，不论是“时间”还是“内容”，都非常耐人寻味。

请大家注意这两段文字，原文是分别是：

第一，继法国总统萨科齐抛出“伊朗若继续研发核武器将遭到先制军事打击”的言论之后，伊朗国营电视台于当地时间9月1日做出回应称，伊朗的核能研究仅限于和平用途。

第二，法国总统萨科齐曾发表讲话称：“伊朗在军用核能以及远程打击技术方面的野心，已经构成了一种正在成长的威胁。这可能导致其它国家率先对其发起攻击。法国将不惜一切代价阻止这样的局面出现。”不过，他并没有明确指出“其它国家”是哪个或哪些国家

伊朗核计划当然“不仅仅”是为了“给电灯泡供电”的

对上述两段文字，我们想指出这样几点：

其一，针对“伊朗国营电视台于当地时间9月1日做出回应称，伊朗的核能研究仅限于和平用途”的说法，我们的观点早在N年之前就已经明确：首先，伊朗核计划当然“不仅仅”是为了“给电灯泡供电”的；

其二，在法国总统的警告中，其实包括了两个部分，一是警告伊朗勿发展“军用核能”，也就是所谓“核武能力”，二是警告伊朗勿发展“远程打击技术”，也就是远程投送能力。

显然，“一”是“（核）弹”的问题，“二”是“枪（远程导弹）”的问题，只有两者结合，才能形成所谓的“核战略打击力量”。

但请大家注意，一个国家是否拥有“核战略打击力量”与是否拥有“核威慑能力”还是两码子事儿。

●“西方资本”恐惧的倒不是伊朗拥有“核战略打击力量”、而是恐惧中东由此而进入“失控的核扩散状态”

事实上，对极其恐惧伊朗拥有“核战略打击力量”的“西方资本”而言，它们所恐惧的倒不是伊朗拥有“核战略打击力量”、而是恐惧伊朗所处的中东由此而进入“失控的核扩散状态”，动摇“西方资本”通过控制中东产油国、继而主导世界秩序、特别是金融秩序的根基。

在这个问题上，不久前，沙特阿拉伯的官员在6月访问英国时，就已经说得“非常清楚”了，也就是那句著名的“........中东地区要么都没有核武器，要么就竞赛核武军备.........”。

●再谈沙特阿拉伯抛出“....要么.....要么.....”的背景

而在之前的点评中，针对沙特阿拉伯抛出的这个“....要么.....要么.....”，我们也曾经详细地给出了它的背景，即：它是2011年1月胡锦涛主席“访美失败”之后、“大国”及相关重要国家在全球各个层面展开的“第四轮排列与组合”的一个“逻辑结果”。

在了更好地进行今天的讨论，我们不妨对已经开始、且还在继续的“第四轮排列与组合”，在“回顾”的基础上、再次进行一番总结。

●中国强行介入中东的“军事支撑”、“政治契机”、“介入方式”

在东方评论员看来，在我们正式引入“第四轮排列与组合”的概念，且将其“始点”追溯至“2011年1月胡锦涛主席访美失败”的情况下，所谓“第四轮排列与组合”已经可以提炼出如下特征：

第一，在经历以“中美直接交手”为主线的“第三波排列与组合”之后，中国通过欧盟与俄罗斯的战略策应，并以彻底扒下“美国军事技术绝对优势”的反卫星武器、新一代核潜艇、中段反导、北斗导航、歼20、反舰弹道导弹等战略与战术武器为“军事支撑”，以“促成 ”并借“以色列袭击土耳其国际救援船队”这一事件为“政治契机”，以联合国常任理事国的身份、公开“为以色列核项目立项”、及“在中东戈兰高地高调‘种树’”等“介入手段”为“政治策略”，以强行介入“中东和平进程”的为“介入方式”，不仅对美国策划的、针对中国的“天安号事件”与“南海问题国际化”等展开针锋相对的反击，还借此“有目的地形成”并“事实地”推广了“与美国一切都在中东谈”的“大国间博弈策略”，最终成功地将“大国间战略利益主要交换平台”从中国重中之重的南亚方向、推至“均”远离“中欧俄”各自的“重中之重”、却积聚了美国核心利益的“中东方向”。

●“第四波排列与组合”头一个重大特征

总之，在“回顾”的基础上，针对目前仍在继续展开的“第四波排列与组合”、我们想总结的“头个重大特征”就是：中国已经在欧俄的策应下，成功地构建、且“中欧俄”均已实际运行了“一切重大问题都与美国在中东谈”的“战略博弈模式”。

●“第四波排列与组合”的第二个重大特征

第二，在“第一”的层面上，在“中欧俄”均拿“一切重大问题”都与美国“在中东谈”的情况下，“谈”的结果也恰恰形成了“第四波排列与组合”的第二个重大特征，即：“美国主导的中东安全格局”已经被推至“不可逆转的破局进程”。

●再谈“策动者”策动“埃及之乱”的险恶用心

第三，站在“美国利益”的角度上，针对自己的被动，出于急于扭转“中东安全格局之不可逆转破局进程”的目的，着眼于“以攻为守”的“扭转手段”，“美国利益决策层”基于“美国资本利益的层面”策动了“埃及之乱”。

第四，在东方评论员看来，“策动者”的这种反击具有多重战略意图：既具有的“战略测试”的意图，更具有“在战略测试的同时、伴随进行战略攻击”的险恶用心。

 所谓“战略测试”更多地是指测试“中欧俄”在中东破局问题上的“团结度”。

●对“策动者”而言，基于不同的测试对象，则明显具有不同的“伴随战略攻击”之意图

而所谓的“伴随战略攻击”，对“策动者”而言，总的来说，与其“战略测试”的“测试内容”相伴相随，也就是：意在瓦解已经成功运行了近十年之久的所谓“中欧俄之伊核战略协调”。

但是，在具体操作中，基于不同的测试对象，则明显具有不同的“伴随战略攻击”之意图。

●如果仅站在中国的立场去思考问题，这种“伴随战略攻击”更多地是指.......

第五，如果仅站在中国的立场去思考问题，则更多是指“策动者”竭力将“埃及之乱”导向“欧亚运输线之乱”、或者针对亚洲、东亚经济的“亚洲海上运输线、东亚海上运输线之乱”，尤其是专门针对中国经济的“中国海上运输线之乱”，且将“北非”、甚至整个非洲大陆或“苏丹化”、或“索马里化”，从而全面破坏中国从非洲获取稳定的能源、矿产，并输出商品的能力，继而最大限度地恶化“中国的外在安全环境”。

●我们也再次、或者更加准确地讲、是“第N次”强调一个观点

在我们看来，需要警惕的是，一旦“美国”与“其它私心杂念（主要指欧盟、也需要警惕日本，也包括部分南方国家，主要是印度、也需要留意巴西）”将“埃及之乱”导向为专门针对中国经济的“中国海上运输线之乱”，那么，与“这种测试”相伴而行的“伴随战略攻击”也就相当于“早就处于攻击状态”之中，也就等同于“已经”对中国展开了实质性经济、特别是金融攻击，也就等同于“已经”对中国早就展开了“暗渡陈仓式南亚破局”。而如果中国只是在确认到这一点之后，才组织反击，那么，届时面对的局面也就必然是：对方“早已经”将“攻击计划”执行“过半”、且处于相对主动的位置。

请大家认真体味上述这段描述。

也正因此，我们也再次、或者更加准确地讲、是第N次强调：如果站在中国的角度看问题，绝不能任由美国这种“在战略测试的同时伴随进行战略进攻”的“战略计划”顺利展开，因为一旦对方战略计划最终顺利展开，从而最终导致中国的外在安全环境被全面恶化，那么，真到了那个时刻，中国再想组织反击、恐怕就已经来不及了。

●千万不要低估了“全面恶化中国外在安全环境”这一手段可能带来的巨大威胁

在这个问题上，首席评论员就明确指出，千万不要低估了美国旨在“全面恶化中国外在安全环境”所做“诸多努力”可能带来的巨大威胁。

在我们看来，作为美国参与、并企图主导“第四波排列与组合”的一个重要的“伴随攻击企图”，就是在全面恶化“中国外在安全环境”的同时，用尽一切办法激化、并扩大中国与“非美势力”之间的战略矛盾，从而“威、逼、利、诱”“伊核六方之其它大国”、特别是某些经济、特别是金融上有严重问题的“南方势力（比如、印度、巴西等）”，对一个“外在安全环境”“届时已经全面恶化”的“中国经济”、或“欲取欲夺”、或“落井下石”、更或“让‘中国制造’与‘人民币汇率’成为‘它们所遭遇的一切困难’之‘替罪羔羊’”、从而不仅在“北方”的层面、更在“南方”的层面，将“攻击中国制造、攻击人民币汇率、对中国经济设置贸易壁垒”精心引导为一种“时尚”：一种将“攻击中国”作为它们“为各自本身内在严重问题”开脱责任之“当然手段”的“时尚，甚至“被引导”为“理所当然地”以为“攻击中国”就能解决自身问题的“时尚”，从而出现某些南方经济、特别是“有必要与中国相互配合”才能令“其”有效抗击“北方”对“其”进行经济、特别是金融攻击的“南方经济”，反而“助纣为虐”地帮助“美国利益”、或者“西方资本”攻击中国、甚至成为“反华的急先锋”！

●“美国利益”、或者“西方资本”用来“诱导”某些南方势力的可能手段

值得强调的是，在“美国利益”、或者“西方资本”极可能用来“威、逼、利、诱”“南方势力”最终转向“攻击中国制造、诘难人民币汇率”的层面上，其可能的手段就是：

第一步：将“埃及之乱”的“后续发展”或从埃及经北非的利比亚、再往阿尔及利亚方向，或者经中东叙利亚、向伊朗方向延伸，从而导向“欧亚海上运输线之乱”、甚至是专门针对中国的“中国海上运输线之乱”。

在此基础上，通过破坏中国从海外“正常”获取能源、矿产及输出商品的能力，从而“先”全面恶化“中国经济稳定运行”的诸多必要条件，“为”今后向中国“任意”输入通货膨胀压力制造条件，一旦成功，就可以“任意地”全面拉高中国经济运行的成本，最后，就是用“定向、且持续的高通货膨胀”尽可能地迫使中国连续加息、“尽可能地”逼迫、或诱导中国“自我灭活”“自己的经济活力”。

●警惕“美国利益”或“西方资本”在“尽可能”广泛地范围内掀起一股“攻击中国、特别是攻击中国经济”的狂潮

第二步，根据我们的观察，在“美国利益”特别是“西方资本”的计划中，在“第一步”进行到相当程度之后，就可以充分利用“西方金融霸权”、通过“水淹（天量货币流动性）南方经济”、触发特定范围内（比如南美、南亚、东亚等，与中国制造有冲突的方向）的金融、甚至经济危机、引发其社会动乱，最终“引导”这些或被经济危机、或被社会动乱逼得走投无路的“南方经济（甚至包括部分北方经济体，比如日本、欧盟）”，在尽可能广泛地范围内掀起一股“攻击中国、特别是攻击中国经济”的狂潮。

●如不能“实质性灭活”中国经济的活力，则“第二步”就要走得困难得多、且危险得多

然而，在东方评论员看来，值得强调的是，对“美国利益”或者“西方资本利益”而言，如果不能“实质性地”实现“第一步”，也就是“实质性灭活”中国经济的活力，则“第二步”就要走得困难得多、且危险得多，其原因有二：

 其一，这意味着“仍然有强大活力的中国经济”会被那些可能被“西方资本”用天量流动性“水淹”的“南方经济”、“更多地”视为一支“有效抵御”“北方经济”的经济、特别是金融攻击的“屏障”。

显然，在“谁都知道”西方资本最终目标只有在“控制中国经济、特别是金融命脉”的情况下才能得以实现的情况下，显而易见的是：“任何与中国进行实质性战略合作的可能性”都将成为这些南方国家、或者经济体（比如印度、巴西），甚至北方国家、甚至经济体（比如欧盟、日本）用以“最大限度延缓、甚至规避”遭受经济攻击的“战略筹码”。

●这一“战略筹码”，对“东亚方向的经济体”而言、特别具有现实意义

在东方评论员看来，这一“战略筹码”，对“事实上”承担着向“华尔街金融永动机”的“稳定运行”提供“主要资金流（再次强调：这不仅仅是资金问题）”、从而也注定为“华尔街”“急于抓在自己手中”的“东亚方向的经济体（比如日本、韩国、东盟）”而言、特别具有现实意义。

其二，不论从哪个角度看，不论从哪个统计口径去看，“中国经济”是如此的独特：

首先，中国经济规模巨大，其次，如以GDP计，中国经济已经超过日本经济规模，列为世界第二，而以“购买力计”，在“量级”上，已经上了“10万亿美元”、已经与美国经济（14万亿美元）不相上下，但是，如“以GNP计”，则在规模上至今仍落后日本经济很多，更不能与美国经济相比。

但是，如果我们撇除“日本GNP规模巨大”的“其它意义”，而只从“规模庞大的日本海外资产”在“日本GNP”中所占的“庞大比例”去看，也就不难明白，相对“GDP已较中国为小”、但“GNP”仍远大于中国的日本经济而言，中国经济的抗冲击能力极强，日本经济抗冲击力则弱得多，这个道理很简单：“日本海外资产”的“运营情况”极易受到当地经济、特别是政治局势的左右、甚至冲击。

这一点，对“海外资产”更加庞大的欧洲、特别是美国经济而言，又何尝不是如此？

●这一“战略筹码”，对“东亚经济一体化”而言、也特别具有现实意义

我们之所以要指出这一点，在于强调：即便美国利益、或者西方资本以“水淹南方”的方式、以上面所述的、类似于“迂回包抄”的方式、对中国进行经济、特别是金融攻击，如果届时中国经济仍然有强大的活力，那么，在“庞大的美国海外资产”也必将因“水淹南方”而“率先受损”的情况下，对美国利益、“西方资本”而言，“其一”所带来的风险更大，因为，这可能“反而”为“活力仍然没有受到实质性灭活的中国经济”提供了一个“借机整合某些南方经济、特别是“中国身边”之东亚经济”的“巨大机会”。

而在这个问题上，对旨在“彻底整合”整个东亚经济的中国而言，一旦那个“华尔街”“急于抓在自己手中”的“东亚方向的经济体（比如日本、韩国、东盟）”被“水淹”，那么，上述“可能的巨大机会”也特别具有现实意义。

●这种“可能的巨大机会”又何尝不是中国的一个“战略筹码”？

显然，对比“其一”，这种“可能的巨大机会”，又何尝不是中国用以警告“美国利益”特别是“西方资本”的一个“战略筹码”？不仅如此，它又何尝不是中国用以警告“某些”可能受到“西方资本”攻击的南方经济、特别是“东亚经济”、尤其是“美国东亚盟友”之日本经济与韩国经济的一个“战略筹码”？

讨论进行到这里，我们已经不难明白一个道理了，即：对“美国利益”或者“西方资本利益”而言，如果不能“实质性地”实现“第一步”，也就是“实质性灭活”中国经济的强大活力，则“第二步”就要走得困难得多、且危险得多。

●美国利益”或“西方资本”目前最想做的事情

而通过上面的讨论，东方评论员其实是想强调：在欧美债务危机“急待”进一步深化，但从“利比亚之乱”的“局势突变”、特别是“中俄”在其中所发挥的巨大作用来看，“欧美”之间的“不可调和矛盾（欧美国家利益之间）”仍然没有得到“有效缓和”、而“很难调和的矛盾（欧美资本利益之间）仍然没有得到“有效调和”的情况来看，策动“埃及之乱”的“幕后策动者”为了最大限度地消除“上述危险”，“美国利益”或“西方资本”目前最想做的事情，恐怕就是将“仍在脱稿运行”的“埃及之乱”尽可能地拉回“设想中的轨道”，从而“继续进行”数种伴随有“战略攻击”的“战略尝试（测试）”：

第一，或沿埃及经利比亚至阿尔及利亚方向、运用已经将苏丹（这是中国在非洲重要的能源合作国）分裂的“苏丹模式”，结合已经将索马里无政府化的“索马里模式”（这是亚丁湾大量产生海盗的原因），沿着“欧亚运输线”沿线、制造专门针对中国的“中国海上运输线之乱”。

第二，或运用“维基解密”之类的战略工具，以西方军事力量，特别是金融霸权为支撑，结合先后成功颠覆了突尼斯、与埃及政权的“突阿拉伯之春”模式，迫使非洲大陆、中东地区、南亚等方向、攸关中国核心利益的国家与组织，不得不与“中国利益”保持距离，从而破坏中国从这些国家与地区正常获取能源、矿产、并输出商品的能力。

●不论是“第一”还是“第二”，“美国利益”都需要“欧盟利益”的“实质性配合”

显然，不论对于“第一”还是“第二”，对“埃及之乱的策动者”而言，要推进这一“尝试（测试）”，就必须得到“欧盟利益（欧盟国家利益与资本利益）”的“实质性配合”。请大家注意，是“实质性配合”而非其它。

●“欧美”在“利比亚由乱至稳”的问题存有“欧美国家利益层面”的“不可调和矛盾”

但是，由于利比亚“在地面上”的地理位置非常核心（是欧盟全面掌控非洲大陆的关键），“在地下的”资源又非常重要（是欧盟计划在中东大乱时部分替代中东石油的来源），且“拿下利比亚”还是欧盟将来用以“慢慢理顺”与非盟、阿盟关系的“要点”，因此，在很大程度上，尽快实现“利比亚的由乱至稳、且主权完整”，还是欧盟用来“掩护”自己“加速解决”“科索沃独立后续发展”的一种“战略纵深”，而“科索沃问题”最终是“和平解决”还是“非和平终结”又关乎“欧元与美元的强与弱”，因此，“欧美”在“利比亚由乱至稳”的问题、也存有“不可调和的矛盾”，显然，这种矛盾根本就是“欧美国家利益层面”的。

然而，就如我们多次强调，欧美国家利益之间的矛盾是“不可调和的”，然而，在“不可调和”的另一面，我们也强调，在某种条件下，是可以“有效缓和”的。

因此，如果我们在这个层面去观察“利比亚之乱的局势突变”，也就不难看出，在“中俄”默认北约（欧盟）将“卡扎菲武力赶下台”的行动之后，美国也以“不阻止（至少在公开层面是这样的）”的方式，被迫对“欧盟利比亚政策”进行了让步。

事实上，在之前的点评中，我们曾经强调，以此为转折：

第一，欧盟与美国也就正式地一“先”一“后”地跳进了“大家（中俄欧美）”合力挖下的“坑”中。

第二，随着欧盟“最终走出这一步（不顾“美国利比亚政策”的“核心利益”，武力将卡扎菲势力赶下台）”，其实我们已经将“利比亚”这个“点”的“定性”、由“观察点”调整为“撕裂点”。

●就“欧美”之间不可调和的“国家利益矛盾”而言，其“后续发展”的可能性有三

显然，在东方评论员看来，就“欧美”之间不可调和的“国家利益矛盾”而言，在先后跳进“坑”中之后，其“后续发展”的选择项有三：

第一种选择；是“美国国家利益”在“坑”中按住了对方、从而最终对“科索沃”跨海（地中海）一击、彻底解决欧元问题、并全面巩固“美元本位制”，继而先瓦解欧盟、再按美国全球战略之需、以“收编了欧元之后的美元本位制”的强大金融力量去“重整”北约，直到将之前美国的“的私有战略资产”－－－－“美日、美韩、美澳军事同盟”一一注入“新北约”，为最终封锁、瓦解俄罗斯、中国做最后战略准备。

●“美国利益”要想在中国“不作为”的情况下、顺利地对欧盟“跨海一击”，基本上不可能！

值得强调的是，美国利益要想顺利实现这一意图，就必须“争取”到中国的“配合”，也就是终止目前一直在执行的“扶弱（欧元）锄强（美元）政策”。

在东方评论员看来，绝非巧合的是，这种“争取”恰恰就是“美国对中国竭尽全力兜售”“中美（G2）共管地球模式”的“战略意图”之一。

毫无疑问，从中国多次公开、且正式拒绝“中美共管地球（G2）”的情况来看，只要欧盟不出现战略误判，从而向美国提供“美国南亚政策”所急需的“实质性南亚配合”，中国也绝不会中止直到今天都“行之有效”的“扶弱（欧元）锄强（美元）”。

因此，我们认为，“美国利益”要想在中国“不作为”的情况下、在“坑”中按住欧盟、最终顺利地对欧盟“跨海一击”，基本上不可能！

●“各方面的主动、或者被动反应”无疑让“欧盟利益”看到了“第二种选择”的“成功希望”

第二种选择：是“欧洲国家利益”在俄罗斯、特别是中国的“扶弱锄强”下，经过一番努力，最终踩着“美国利益”的脑袋、从“坑”中“一跃而起”，从而快速解决科索沃问题，完成“统一外交、军事、特别是财政权力”的“欧盟全面整合”，继而令“欧元”正式驶入“取代美元”的快车道，并由此正式启动“全方位接收美国人才、技术、资金外流”的“接收进程”。

在东方评论员看来，从“欧盟主动向朝鲜提供援助”换来中国对“欧盟利比亚政策”的支持（准确地讲，是不反对）、并迫使“不太可能顺利实现第一种选择”、从而指望拉拢欧盟、联手“全面恶化中国外在安全环境”的美国、也不得不对“欧盟利比亚政策”进行让步的情况来看，“各方面的主动、或者被动反应”无疑让“欧盟利益”看到了“第二种选择”的“成功希望”。

值得强调的是，让欧盟“看到希望”，这“即”是“中国拒绝中美G2”的主要意图之一，也是中国奉行“扶弱（欧元）锄强（美元）”的主要意图之一。

第三种选择，则是“不可调和的欧美国家利益矛盾”在“虽很难调和、但最终‘却’‘可能’因种种原因而‘有效调和’的欧美资本利益”之间“共同利益（西方资本利益）”的“牵引”下，先在“坑”中“暂时缓和”彼此之间的“不可调和之矛盾”，从而一面防止因“欧美之间的撕裂”而令“中俄”有机可趁，另一方面，则是试图寻找机会、甚至是制造机会、“共同”从“坑”中爬出来，继而令“中欧俄美”之间的角力局势“重新回到”埃及之乱之“后”、利比亚之乱之“前”的那种，“欧美”虽然被动、但不至于像目前这样“欧美全部跳入坑、中俄却均站在坑外、且随时准备轮番消遣欧美”的这般被动局面。

●所谓“第三种选择”，就是“欧盟国家利益”要避免出现惨遭“中俄”轮番消谴的下场

在之前的点评中，我们曾经说过：对比“俄罗斯最新利比亚政策”的“利益核心”，其实我们不难看到“中国利比亚政策”的“主要元素”，从中国政策在利比亚问题上的“言”、特别是“行”来看，“中俄”的利比亚政策具有“高度的一致”，也就是说，在“方方面面”于“其它战略方向”经过一番“排列与组合”之后，针对利比亚这个“观察点”，“中与俄的利比亚政策”仍然保持着“足够的一致”，这也就意味着在叙利亚这个“止损点”上，“中俄”也在“保持着高度一致”，这还意味着在伊核问题上，“中俄”仍然保持着高度的战略协调。

在东方评论员看来，上述情况又进一步说明：在非盟与阿盟这两个地区组织、及“其它地方王”的策应下，在利比亚这个曾经的“观察点”、今天的”撕裂点“上。在科索沃问题、特别是“两核问题”上，“中俄”又将“轮番消谴”那个“不可调和”的“欧美国家利益之间的矛盾”了。

 显然，就“欧美”之间不可调和的“国家利益矛盾”而言，在“欧盟利比亚政策”在中俄的支持下、终于走出“那一步”之后，在“欧美”终于一先一后地全部跳进“坑”中之后，其“后续发展”的所谓“第三种选择”，就是要避免出现上述这种惨遭“中俄”轮番消谴的下场。

不仅如此，在之前的点评中，我们也强调：事实上，由于“中欧俄”之间的“利比亚利益”即有合作也有冲突，而欧盟与“中俄”之间的最大利益冲突就在于‘欧盟想独自掌控利比亚、并以此为支点，重新掌握地中海之滨北非、甚至整个非洲大陆”，从而将“北非、甚至整个非洲大陆”作为“欧盟经济”最主要的能源与矿产供应基地，及地中海联盟的巨大市场。因此，欧盟这“一已私心”必然成为“基本失败之后”的“美国利比亚政策”之“调整支点”。

●其“调整思路”、在层面上已经非常清晰了

因此，在东方评论员看来，在“美国利比亚政策”已基本失败之后，在“第一种选择”基本没有希望之后，特别是，在“方方面面的主动、或被动反应”已经令欧盟看到了“第二种选择”的希望之后，在中俄的支持下、欧盟终于走出了“全然不顾美国利比亚政策的意图、武力推翻卡扎菲势力”、从而令“欧美国家利益之间”不可调和的矛盾“彻底投射”到“利比亚之乱”的“处理进程”“这一步”之后，无法实现“第一种选择”、但也必然阻止“第二种选择”的“美国利益”，其当然的选择就是“第三种选择”，即：利用欧盟的那“一已私心”作为“调整支点”、对“美国利比亚政策”进行调整。

显然，其“调整思路”、在层面上已经非常清晰了，那就是：

第一层，用“利比亚”这个曾经的“观察点”、今天的“撕裂点”、去置换“中欧俄”等组成的“国际社会”手中的“止损点”--叙利亚；

也就是说，在利比亚问题上基本失败的“美国利益”在“第一种选择无望成功”，又试图避免“第二种选择”的思路下，企图“迎合”欧盟的那“一已私心”、沿着“第三种选择”，以“美国利比亚政策愿意对欧盟做出进一步让步、从而令欧美有机会共同爬出坑”的方式、继而“以退为进”、将“局势”导向以“中俄”计划用来撕裂“欧美”之间的“撕裂点”、“反向”去撕裂“中欧俄”之战略协调、特别是“中欧”之间的战略协调。

●“美国东北亚政策”突然以一种“实际行动”向方方面面宣示：我愿意重新做人！

第二层，显然，尽管在利比亚问题上与美国一起落入“坑”中的欧盟也不想被“中俄”轮番消遣，但是，在欧盟已经于“中俄美等方方面面的或主动、或被动的反应”中看到了“第二种选择”有成功希望之后，一个单纯的“第三种选择”也是很难蒙蔽欧盟的那“一已私心”、继而令欧盟做出战略误判、令其自毁“第二种选择”的前程的。

也正是在这种背景下，“美国东北亚政策”突然以一种“实际行动”向方方面面宣示：我愿意重新做人！即：

其一，美国宣布，向中国出口、并转移部分部件生产核心技术的LM2500燃气轮机。

其二，美国宣布，向朝鲜提供人道援助；

●“弃之可惜、但又食之无味”

众所周知，向中国实质性解禁、并出口中国所需的重要装备产品、特别是相关高技术，在今天的形势与格局下，即是我们判定美国是否愿意构建“中美共管西太平洋（修订版G2）”的核心标准之一（另一核心标准是“实质性接纳”中国参与国际金融决策），也是我们判断“美国东北亚政策”是否支持、至少是不反对“东北亚经济一体化”的核心标准之一，因此，美国在此期间同时宣布“上述两件事情”，显然在向方方面面、特别是欧盟强调：我在“认真地考虑”别的选择。

在东方评论员看来，LM2500燃气轮机中国的确“仍然需要”，但随着中国相关技术的进步，这种东西已“有如鸡肋”，可谓“弃之可惜、但又食之无味”，对此，在技术上，我们的建议是，在“毫不动摇”地继续“自己的相关技术与产品”的前提下，如果美国人“最终（请注意用词）”仍然愿意转让，那就对其技术加以引进、直到彻底吸收。

●正是在“这一变化”前后，中东方向同时来了“数声异响”

而在战略上，那就非常简单了，在此非常时期，既然美国人愿意将“其”作为“警告”欧盟、及其它盟友（比如日本）的“某种战略信号”抛出来，中国自然要做出一种“满意状”加以“接收”，否则，至于如何利用它、并鼓励欧盟继续向“盟国加速整合”的方向“冲刺”，并继续敲打“刚刚上台的日本新政府”，那是中国自己的事情！

事实上，正是在“这一变化”前后，中东方向同时来了“数声异响”：

第一，欧盟9月2日宣布：对叙利亚进行石油禁运；

第二，俄罗斯9月2日宣布，俄驻北约代表将前往德黑兰讨论伊朗导弹计划；

第三，据媒体9月2日报道，伊朗议会新闻部宣布议长拉里贾尼将于9月4日开始对朝鲜进行为期3天的访问。离开平壤后，拉里贾尼还将访问中国。

第四，土耳其表示已与北约达成协议，在土境内部署作为北约导弹防御系统一部分的早期预警雷达；

第五，鉴于以色列拒绝就袭击土耳其国际救援船一事向土耳其道歉，土耳其于9月2日宣布，将驱逐以色列驻土大使，限其在9月7日前离开土耳其境内，并断绝与以色列签署的所有军事协议。

●一旦欧盟对叙利亚进行全面经济制裁，对叙利亚的打击是相当巨大的

首先，针对“欧盟宣布：对叙利亚进行石油禁运”，在东方评论员看来，就如我们之前所说，一旦欧盟对叙利亚进行全面经济制裁，对叙利亚的打击是相当巨大的。

显然，对比这一条件，我们不难看出，尽管叙利亚的石油产出并不多，但95%都输往欧盟，这也足以对叙利亚的经济产生一定影响。

因此，在东方评论员看来，“不要轻视”欧盟这一动作，因为，欧盟此举明显有与“美国利比亚政策”进行“战略交换”、从而双方“共同爬坑”的意图。

●这只是问题的一个方面，远非问题的全部

然而，我们想强调的是，这只是问题的一个方面，远非问题的全部。

如果您最近一直在关注《东方时代环球时事解读》，相信您会对我们近期针对三件事情，即：

其一，“横跨中日俄三国的日本海陆海联运航线通航仪式于8月18日在日本新潟港举行”；

其二，8月18日、继美国率先要求“叙利亚总必须下台”、并宣布制裁叙利亚的石油、金融等核心行业之后，英国、法国、德国政府也开始“附议”“叙利亚总必须下台”的“美国提议”，但在更加重要的“全面制裁问题”上，还是有所保留。

其三，直到8月18日，在印度“绝食反政府示威”的问题上，也就是“南亚破局”的问题上，欧盟总体上仍然保持着低调。

.....所给出的一个观点有所印象。

针对上述三件事情，我们认为：以“这个仪式”放在18日举行为例、就“日期”而言或是个巧合，但“这个仪式”本身却绝非巧合，这说明，根本就不相信（对中俄而言）、或者不敢相信（对日本而言）“美帝国”不会步“前苏联、及大英帝国纷纷在阿富汗折戟沉沙”、从而“是个“例外”的，是大有“人”在！

因此，在东方评论员看来，在“其三”的背后，也就是.......8月18日、继美国率先要求“叙利亚总必须下台”、并宣布制裁叙利亚的石油、金融等核心行业之后，英国、法国、德国政府也开始“附议”“叙利亚总必须下台”的“美国提议”，但在更加重要的“全面制裁问题”上，还是有所保留........的背后，也就引出这样一个问题，那就是：

....................在叙利亚这个“水深难测”的“止损点”上，欧盟公开加入“叙利亚总必须下台”这一步，这到底是美国“已经拉”欧盟“下了水”呢？还是欧盟正琢磨着“如何一脚”将美国给彻底踢下水、且不再有机会爬起来呢？在东方评论员看来，就“结果”而言，恐怕还得走一步看一步！但欧盟琢磨“如何一脚”将美国给彻底踢下水的可能性要大得多！

●欧盟也是在借这一“不轻不重”的动作发出战略信号：它也在考虑另一种选择

显然，我们之所以强调“不要轻视”“欧盟宣布：对叙利亚进行石油禁运”，首先就在于：它毕竟向“欧盟对叙利亚进行全面制裁”更靠近了一步，其次，也是更加重要的，它还在于它毕竟与”欧盟对叙利亚进行全面制裁“还有一段距离，因此，欧盟也是在借这一“不轻不重”的动作向“方方面面”发出一个战略信号、特别是中国与俄罗斯，那就是：它也在考虑另一种选择。

有意思的是，也在这个时候，罗斯9月2日宣布，俄驻北约代表将前往德黑兰讨论伊朗导弹计划，不仅如此，伊朗议会新闻部宣布议长拉里贾尼将于9月4日开始对朝鲜进行为期3天的访问。离开平壤后，拉里贾尼还将访问中国。

还有，俄罗斯突然抱怨称：美国直到今天都不肯保证准备在欧洲部署的北约反导系统“不针对俄罗斯”。

●土耳其这个“中东地方王”的身价就立刻高了一层

这样一来，第四、也就是“土耳其表示已与北约达成协议，在土境内部署作为北约导弹防御系统一部分的早期预警雷达”也就有了另一番风味，那就是，这个将“美国中东安全框架”冲击得“哗哗作响”的“中东地方王”，其身价就立刻高了一层，即：它感觉从此开始，就可以正式在“中欧俄美”及伊朗、叙利亚、“非盟”与“阿盟”之间玩一种“准大国游戏”、以尽可能地“为自己划拉”国家、及区域的长远利益。

值得强调的是，这是“非美势力”所喜闻乐见的。尽管土耳其的坐大，日后也会给非美势力、特别是俄罗斯与中国的利益造成不利影响，但是，在当前最紧要的“中东破局”相比，那些尽管值得警惕，但都是“后话”！

在这种背景下，土耳其冲着“美以”翻那笔旧账、进一步享受“中东地方王”的“红利”，那就成了必然，而这，又给“中俄”提供了”在利比亚轮番消遣欧美”的“筹码”，甚至也给“中欧俄”提供了“一切都与美国在中东谈”的“筹码”。

●这些媒体“警觉得有理，怀疑得正确”

我们注意到，一些媒体马上对伊朗和朝鲜的走近表示警觉，并怀疑双方在军事上展开合作。

在东方评论员看来，基于我们之前的观点，这些媒体“警觉得有理，怀疑得正确”，其实，这也正是法国总统警告伊朗的重要背景。

●如果....，则，是废掉命系着“美元本位制”的“美国中东安全框架”的时候了

显然，“中俄”及伊朗、叙利亚、土耳其、阿盟、非盟等分别接收到“欧美”分别发出的“战略信号”之后，所有“非美势力”显然都感觉到：是时候推动巴勒斯坦单方面建国了，是时候打通国际社会自由进出加沙地带的第二、甚至第三条通道、从而废掉命系着“美元本位制”的“美国中东安全框架”的时候了。如果美国人“仍然不明白”如何才能真正爬出利比亚的那个“坑”的话！

●“国际社会”强行打通第三条通道的“表象”与“本质”

而一如我们之前所说，“国际社会”强行打通第三条通道，其表象是“中俄”支持中东国家进行“武力护航”、因此，面对一个拥核的以色列，其“实质”又是“中东核扩散”为这种“武力护航”作支撑。

如果在这一层面去观察问题，那么，在俄驻北约代表将前往德黑兰讨论伊朗导弹计划，及伊朗议会新闻部宣布议长拉里贾尼将于9月4日开始对朝鲜进行为期3天的访问。离开平壤后，拉里贾尼还将访问中国.....的背后，恐怕就是“两核联动”、“万不得已、中俄将默认伊朗正式跨进核门槛”的“强烈信号”。

●欧盟当然明白这中间的利与害

在之前的点评中，我们曾经强调，如果欧盟在叙利亚问题上自“伊核战略协调”上“红杏出墙”，“欧美”联手有效击穿叙利亚这个止损点，“中俄”所代表的“国际社会”就必然做出强烈反击，其中，强行打通第三条通道、与默认伊朗悍然核试都是选择项，不过，我们也强调，强行打通第三条通道也要以伊朗悍然核试作军事与政治“支撑”，而一旦伊朗悍然核试，且沙特也在“国际社会”的“不反对”下坚决兑现那个“....要么.....要么.....”，则“西方国家与资本”主导全球的格局就立马打碎，而这，恐怕即是法国总统突然警告伊朗的深层原因，也是中国、俄罗斯警告美国、特别是欧盟在叙利亚问题上“小心一点儿，别玩过火”的一个动作，而结合“欧盟”已经看到了“第二种选择”的成功希望，尽管欧盟抛出“对叙利亚进行石油禁运”这一动作，正式摆出了一副愿意与美国利比亚政策进行利益置换，从而“共同爬坑”的姿态，但“中俄”对“伊核悍然核试”、并进一步借朝鲜之名解决“枪”的问题上所表现出来的“不阻止”之态度，事实上已经在暗示：如果欧盟还想从“坑”中爬出来的话，那就与美国利益远一点儿，否则，“中东核竞赛”开始的那一天，就是包括欧盟在内的“西方利益”终结其“主导全球历史”的那一天。显然，在这种情况下，本来有希望在利比亚方向通过“第二种选择”从坑中一跃而起的“欧盟利益”，也就等同自己为自己掘墓、继而“将自己与原本已经很难从坑中爬出来的美国利益”一起，给埋在了“坑”中！

●针对欧盟对叙利亚进行石油禁运，我们再次重复之前的那个观点

在东方评论员看来，欧盟当然明白这中间的利与害，因此，综合各方面的情况，针对欧盟对叙利亚进行石油禁运，我们再次重复之前的那个观点，即：

在叙利亚这个“水深难测”的“止损点”上，欧盟公开加入“叙利亚总必须下台”这一步，这到底是美国“已经拉”欧盟“下了水”呢？还是欧盟正琢磨着“如何一脚”将美国给彻底踢下水、且不再有机会爬起来呢？在东方评论员看来，就“结果”而言，恐怕还得走一步看一步！但欧盟琢磨“如何一脚”将美国给彻底踢下水的可能性要大得多！

事实上，从德国总理默克尔之前访问塞尔维亚，前几天又访问了斯洛文尼亚的情况来看，欧盟有重心仍然在“科索沃问题”的“加速解决”上。

因此，在上述问题上，欧盟琢磨“如何一脚”将美国给彻底踢下水的可能性要大得多！显然，在加沙通道问题上，如果欧盟“重返”国际社会，与中俄一道，那么，永久打开埃及与加沙之间的“第二条通道”也一样可以拆掉“美国中东安全框架”。这也就不必“中俄”通过“伊朗悍然核试”去“最暴力中东破局”了。

●欧盟在“只可意会，不可言传”地对“也跳入坑中”的“美国利益”发出了一份“警告”！

从这种角度去看，我们不难察觉到欧盟“对叙利亚进行石油禁运、但并不进行全面制裁”的“微妙”之处。其“微妙”之意还在于“只可意会，不可言传”地对“也跳入坑中”的“美国利益”发出了一份“不要在利比亚问题、欧盟债务问题、特别是科索沃问题”搞小动作的“警告”！

这份“警告”的“具体内容”，相信不久就会随着“相关新闻”显现出来！大家不妨密切关注之！

●抓住了阿盟与非盟的“心”，也就等于抓住了“利比亚最后解决方案”的关键、未来与主动权

另外，对“中俄”而言，只要叙利亚这个“止损点”不被有效击穿，在欧美已经跳进利比亚那个坑中之后，它们在“坑”中愿意怎么玩都行，不过，“中俄的利比亚”是一分都不能少的，在保护自己利比亚利益的层面上，事实证明，中俄显然有充分的协调，并如我们所评估的那样，保持着一种“纵深”，在俄罗斯承认反对派的同时、中国暂不承认，这即是在“尊重”、也是在“等待”非盟的“最终态度”，也是在轮番消遣“欧美利比亚政策”。

试想，“利比亚的稳定”根本离开不非盟的支持，因此，在东方评论员看来，“中国利比亚政策”目前所要做的，就是在联合国替“非盟”把关、并“为”非盟代言、从而充当“非盟”、并日后充当“阿盟”之利比亚政策的代言人，继而全面展开自己的全球战略。如果期间“美国利益”不敢进行战略冒险、以阻止“这一展开”之“顺利进行”的话。

显然，抓住了阿盟、特别是非盟的“心”，也就等于抓住了“利比亚最后解决方案”、特别是“中东和平进程”的关键、未来与主动权。

这个道理、这份逻辑，从上面讨论的情况去观察，恐怕根本就不需要多说！在这份道理与逻辑下，“欧盟”通过“利比亚反对派”放出“先照顾参与军事打击卡扎菲势力的生意”的“风声”，无疑显得“极其苍白”、我们倒想看看，利比亚还想不想由乱至稳？特别是，利比亚石油结算货币的问题上，“欧元”还想不想要？更不要说中国手中的否决权！因为没有中国的同意，“利比亚反对派”在联合国、在国际法上，就只能当一群“反对派”！
