# -*- org -*-

# Time-stamp: <2011-08-15 23:35:15 Monday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+STYLE: <link rel="stylesheet" type="text/css" href="css/org.css">

** 2011年8月5日
   
*** 巴勒斯坦官员说不放弃成为联合国会员国的努力

 

【拉姆安拉消息】据媒体报道，巴勒斯坦解放组织（巴解组织）执行委员会委员艾哈迈德&马吉达拉尼11日表示，以色列发出的惩罚威胁不会动摇巴寻求联合国会员国资格的决心。

马吉达拉尼告诉新华社记者，就以色列现任政府的一贯做法来看，这次所发出的制裁威胁“不足为怪”，也非首次。巴不会受其影响，放弃寻求成为联合国会员国资格的努力。

巴媒体当天援引巴民族解放运动高官穆罕默德&埃什提的话说，以方威胁对巴民族权力机构进行政治上孤立、经济上封锁仅是一场“政治秀”。他指出，巴方前往联合国的努力已获取国际社会的广泛支持，巴方已经做好了应对任何威胁的准备。

以色列媒体11日报道，以政府当天举行会议探讨如何应对巴“联合国方案”。多名与会官员建议采取包括停止向巴方转交代收的税款等进行惩罚。

根据巴以曾达成的协议，以色列负责对运往巴控区的物品征收关税以及对在以色列工作的巴勒斯坦人征收个人所得税，并将税款定期移交给巴民族权力机构。据媒体估算，以色列每年移交给巴方的税款超过10亿美元，约占巴民族权力机构预算额度三分之二。但以方曾多次借故冻结移交税款，以此向巴方施压。

去年9月初，巴以双方在华盛顿重启直接和谈，但和谈仅过两周就因以色列拒绝延长<<约旦河西岸犹太人定居点限建令>>而搁浅。今年6月，巴解组织正式宣布将于9月前往联合国，要求联合国承认巴勒斯坦国，给予巴勒斯坦联合国会员国身份并根据联合国宪章承认其自治权。对此，美国和以色列强烈反对。

*** 俄颁布总统令禁与卡扎菲政权贸易 支持北约行动

 

【莫斯科消息】据俄新社报道，俄罗斯总统梅德韦杰夫当地时间12日表态称，俄罗斯支持在联合国决议框架内北约对利比亚的军事干预行动。

据报道，[[http://www.kreml.ru/][克里姆林宫官方网站]]上12日公布了梅德韦杰夫颁发的总统令，禁止除人道主义救援用途外的任何利比亚飞机进入俄罗斯领空，并授权当局对来自利比亚的船只进行武装人员及武器方面的搜查。

俄总统的这份命令还禁止俄罗斯企业从事任何涉及利比亚领导人卡扎菲或其家族成员资产的商业交易。

今年3月17日，联合国安全理事会通过第1973号决议，授权在利比亚设立禁飞区，要求相关国家采取“一切必要手段”保护利比亚平民安全，包括对卡扎菲军队发动空袭。当时，俄罗斯对这份决议投了弃权票。

联合国安理会还通过了1970号决议，对卡扎菲政权高官实施制裁、冻结资产并发布旅行禁令；同时对利比亚实施武器禁运。

3月19日，美国、英国和法国以执行联合国1970号和1973号决议为理由，率先对利比亚发动军事打击。同月31日，北约全面接管对利比亚军事行动的指挥权。北约决定，将持续对利比亚军事目标发动空袭以遏制卡扎菲军队的作战能力，至少直到今年9月底。西方连月来要求卡扎菲下台，但卡扎菲没有同意，并态度强硬地表示不会离开利比亚，而是将抗争到底。

今年7月13日，俄罗斯外长拉夫罗夫表态称，俄高层认为卡扎菲应当下台。

拉夫罗夫说，西方认为莫斯科方面支持卡扎菲，这对于俄罗斯在利比亚问题立场的评论是不正确的。他指出，这种情况出现是由于消息不灵通。

拉夫罗夫表示，“我们首先谴责卡扎菲的行动。我们支持联合国安理会关于利比亚的第一份决议。第二份决议，我们对于决议的实施方面存在一些问题”。

7月18日，拉夫罗夫又在新闻发布会上表示，俄承认作为谈判方之一的利比亚反政府派别“全国过渡委员会”，但不认为该委员会是利比亚人民的唯一代表。

拉夫罗夫还重申，俄罗斯在卡扎菲下台后不会接纳他。

 

【时事点评】在之前的点评中，我们曾经着重回顾了2001年阿根廷金融危机，之所以如此，在于：

 

●阿根廷金融危机的“前因”与“后果”，均值得当今世界、特别是“南方经济体”的高度警惕

 

 

 第一，我们认为，就阿根廷金融危机而言，不论是“前因”还是“后果”，也不论是”经验“也好、“教训”也罢，都是值得当今世界、特别是“南方经济体”的高度警惕。

 

 

●“阿根廷金融危机”与“阿根廷式的金融危机”很有可能在全球再次上演

 

第二，也是最重要的，我们还认为，即便“方方面面”的决策层“深刻地认识”到了“第一”，但时至今日，由于“那种土壤（<<北方向南方转嫁危机>>的土壤）”依然，因此，不仅“阿根廷金融危机”仍有可能在阿根廷重演、更加值得警惕的是，“阿根廷式的金融危机”也很有可能在“其它南方经济体”、甚至“许多的北方经济体”上演。

 

●英国此次何以多个城市爆发大规模骚乱？

 

值得强调的是，在所谓的“许多的北方经济”之中，就包括有“美国经济”。更加值得强调的是，既然仍然拥有“美元本位制”可“用”、从而可以借 “QE（量化宽松）”的货币手段来缓解一二的“美国经济”都“可能难以幸免”，那么，已经失去“英镑霸权”近100年、从而“本质”上只能“硬性减赤”的 “英国经济”，必然就是“不可避免”了。

 

在东方评论员看来，此次英国多个城市爆发大规模骚乱（注：这是西方政府与媒体的定性，显然，如果类似的事发生在“它们所不待见的”南方国家或经济体，其宣传上就必然用上诸如‘违反自由价值观、血腥镇压人权’之类宣传词），其实就与英国在“欧美金融危机”之后、“没有能力”像“有美元本位制可用的” 美国那样大搞货币宽松、从而“不得不”玩自我消化的“削减开支”、但却将削减的目标主要对准社会福利、从而进一步激化社会矛盾有“很大的直接关系”。

 

●哪个国家都有一本难念的经，相对“中俄”而言，欧盟、特别是美国内部的矛盾更加尖锐

 

事实上，早在“埃及之乱”之初时，也就是在美国决策层基于“美国资本利益”策动“埃及之乱”后，特别是，在美国国务聊希拉克面对媒体、公开叫嚣“中国不能阻止历史潮流（美国决策层所幻想的、旨在<<通过控制中国政治、继而最高效地控制中国经济的所谓‘民主自由’>>）”、并狂妄地声称“‘埃及之乱’的局面尽早会在中国出现”的时候，我们就曾经给出这样一个观点，即：仅就“中欧俄美”而言，不论是哪个国家，客观地讲，由于情况各异，可谓家家都有一本难念的经，不过，“整体”且“相对”而言，欧盟、特别是美国内部的矛盾显得更加尖锐、且已经处于爆发的边缘！

 

 

●“英国骚乱”恐怕已经在相当程度上预言了这一点

 

在东方评论员看来，“民主与自由”的英国、终因“警察枪杀一名青年”而触发了一场大规模骚乱，这恐怕已经在相当程度上预言了这一点，即：<<在欧盟、或者美国国内，爆发“英国式骚乱”只是时间问题，需要的只是一个机会而已，仅此而已！>>

 

前面已经说了，“英国之乱”的“触媒”是英国大幅滑坡的经济问题，且由于英国经济规模不够大、政治与军事影响力不够强、英镑的“硬通能力”非常弱，这就注定“英镑”不能像欧元、特别是美元那样玩“隐性、或显性的量化宽松”、向外转嫁危机，否则，“大量的英镑”将滞留在“规模不大的英国经济体”内、并令英国经济“内涝成灾”、如果是这样的话，此次恐怕就不是“相对单纯一些”、也“相对好处理一些”的、在司法层面就可以处理的“英国骚乱”，而是类似“埃及之乱”、甚至“利比亚之乱”、特别是”叙利亚之乱”的、给“外部力量提供机会”的、最终必须在“体制层面”、或者“军事层面”进行处理的“英国之乱” 了。

 

在这里，我们想提请大家注意一点，直到今天，通过我们的观察，“外部力量”暂未明显介入“英国骚乱”，但这绝不意味着“外部力量”不会介入可能的“英国之乱”、欧盟之乱、特别是“美国之乱”。

 

 

●这些土壤在欧盟、特别是美国，可谓是一个“没有最多、只有更多”的问题

 

在这个问题上，我们想针对“某些势力”强调三点：

 

第一点，一切都是可能的！基于“英国骚乱”有着强烈的、产生“英国之乱”的土壤，而这些土壤在欧盟、特别是美国，可谓是一个“没有最多、只有更多”的问题，因此，这一点没有什么可争议的！

 

 

第二点，那种“以子之矛、攻子之盾”的道理，地球人都知道！在英国首相不得不拿“<<民主之矛、攻自由之盾>>”的那一瞬间，当时策动“埃及之乱”的“西方资本利益决策层”，恐怕从内心中再一次真切地体味到“矛盾”的滋味、感受到“搬起石头有可能砸了自己脚”的恐惧！

 

●“英国骚乱”表面是个社会问题，却起源于一个经济问题

 

第三点，“英国骚乱”表面是个社会问题，却起源于一个经济问题，是个“<<西方国家与资本利益之间矛盾的不可调和性>>”的问题，具体至英国，则是个“英国资本利益6”不肯向“英国国家利益”让利、以共渡难关、从而只想让英国社会（英国国家利益）为“英国资本利益”一手弄出来的“英国金融危机”去“单方面埋单”的问题。

 

 

而这一处理方式，在欧盟内部也在“广泛存在、并处于激烈地争论”之中，但在美国内部更是“最为严重地存在、并仍在继续发展之中”

 

在“欧盟内部也在‘广泛存在、并处于激烈地争论’之中”的层面上，在“德国国家利益（德国社会）”强烈要求“欧盟内部的私人金融资本”更加深入地参与“旨在缓解、或解决希腊等成员国债务危机”的问题上，已经表现得非常清楚了！

 

而在“美国内部更是‘最为严重地存在、并仍在继续发展之中’”的层面上，从“演戏至最后一刻”的“美国国会”、最终毫无悬念地上调“美国国债上限”、从为“美国资本”日后的QE3（甚至QEn)打开“无限空间”、就可以看出。

 

 

●“中美国（G2)”绝不可行、但“中德国”却可以尝试的原因

 

  显然，“德国利益”之所以敢于如此要求，在于“德国国家利益与德国资本利益”之间的“不可调和的矛盾”，因“德国经济相对稳定”而处于“有效缓和阶段”。

 

而德国经济之所以能相对稳定则在于“德国经济”整体上与“英国、特别是美国经济”有“质”的区别，即：德国经济以“制造业”等“实体经济”为主，这与“中国经济”有更多的相似之处，这也是我们之前一再强调“中美国（G2)”绝不可行、但“中德国”却可以尝试的原因。

 

非常清楚，由于德国是欧盟经济实力最为强大的国家，而中国则是南方经济中实力最为强大的经济体，且彼此间有很强的经济互补性，因此，对“中德国”的尝试、无论其结果如何，至少可以起到干扰、甚至阻止“欧美联手”的作用。

 

●“英国骚乱”与“英国之乱”的“区别”

 

因此，此前曾因滞留在欧元区之外、而在美元与欧元间大收“骑墙”红利的英镑，其对应的“英国经济”只能以“实实在在的紧缩（当然，这也是相对而言的，英镑也曾量化宽松，精通金融奥秘、且一样贪婪的英国资本利益、也一直试图持续量化宽松、但遭到英国国家利益的极大阻力）”为“第一波欧美金融危机”承担后果，且也必须以“持续紧缩”在即将到来的“第二波欧美金融危机（请大家注意我们的用词，事实上，在之前的讨论中，我们的相关用词就是：<<美国次贷危机>>，<<欧美金融危机>>，而不是其它）”、或者“第一波<<全球金融危机>>（请大家注意我们的用词）”之前、试图为英国经济“紧”出一线生机、为英国社会“缩”出一丝安定。

 

值得强调的是，这个所谓的“一丝安定”，大家可以在“英国骚乱”与“英国之乱”之间的、可以说是“非常细微”的、但却是本质的“区别”中、去细细体味！

 

●“英国经济”在模式上像极了“美国经济”，“都”寄生在“美元本位制”的身体上

 

在东方评论员看来，在这个问题上，可以肯定的是，如果“英镑”当初也选择“类似欧元、特别是美元”的那种“或隐式、或显式的量化宽松”作为应对“欧美金融危机”的主要手段的话，那么，今天英国政府面对的恐怕就不是什么、被英国政府用“虚假民主诉求、暴民”等关键词进行“定性”的“英国骚乱”、而是“实实在在的”一场、类似“阿拉伯之春”式、旨在推翻英国政治体制的“英国之乱”了。

 

●更多在依靠“美元本位制”与“美国军事超强”的“美国经济”，今后要仔细了！

 

值得指出的是，“英国经济”在模式上像极了“美国经济”，都是以“金融服务”与“特定领域的高科技”为主，且“都”寄生在“美元本位制”的身体上，其生产、特别是生活资料严重依赖进口，而“欧盟经济”的“内循环能力”远较“英美经济”要强，因此，“美国经济”其实较“欧盟经济”、更别说是中国经济、更容易受到“外部经济波动”的冲击，从“枪杀黑人青年”就立刻导致一场大规模“英国骚乱”的情况来看，“<<种族问题经济化>>”问题更加严重的、更多在依靠“美元本位制”与“美国军事超强”苦苦支撑、且度日如年的“美国经济”，今后，一旦有什么“风吹草动”，那可就要仔细了！

至于这个所谓的“风吹草动”是什么？我们稍后再展开！

 

至于“要仔细”什么？在这里，首席评论员就指出，“内部问题较英国更加尖锐”的“美国政治、经济、军事体”首先要仔细的就是“<<经济问题种族化>>”。

 

因此，一旦“全球经济”因“意外的原因”、或者“计划之中的原因”而触发、并面对一场“第一次全球金融危机”的话，那么，在“谁先乱”的问题上，早已经通过“南海示强”而准备“最低限度内循环”的“中国经济”恐怕比欧洲、特别是“美国经济”要自信得多！

 

●人类社会进入现代文明以来的“最大行政腐败、经济腐败、特别是司法腐败”

 

在我们看来，弄出了美国次贷危机、以至欧美金融危机，给欧美社会、以至世界经济造成重创的“欧洲、特别是美国利益集团”，竟然没有一个“负责人”、或者“负责团体”为之承担相应的法律与经济责任、受到相应的惩罚，显见：人类社会进入现代文明以来的最大行政腐败、经济腐败、特别是司法腐败，也均莫过于此了。那位因“<<庞式骗局>>”而获罪的“金融小虾米”、那位大声责问“倒闭的为什么是雷曼、而不是其它更大的公司”的雷曼总裁，它们都在“如诉如泣”告诉人们：他们不过是两只很小、很小的替罪羔羊而已！

 

●庞氏的“如诉如泣”

 

 

在东方评论员看来，放在更大层面去观察，这种“如诉如泣”有其一定道理，但是，本质而言，它们“诉”的是“自己遭遇了极大的不公”，“泣”的是“为何受伤的偏偏是自己”，显然，它们并没有出一丝一毫的“忏悔”，它们的逻辑就是：为此负责不应是他们、而应“另有其人”，因为“美国金融机构”、特别是 “美国政府”都在玩一种“庞式骗局”，它们只不过是“参与其中”而已！

 

<<显然，这个所谓的“另有其人”的“人”，即是一种政治制度、也是一个利益集团、还是一个游戏规则。>>

 

●“欧美社会”其实也是一清二楚

 

 

<<值得强调的是，如果不是因为“格鲁吉亚回合反击”惨败，令格林斯潘时代就种下的“次贷危机”这只脓胞再也捂不下去、继而“美国利益决策层”不得不选择“定向爆破”的手段，以将其它国家、特别是欧盟也拖入金融危机，可能肯定的是，历史上“历经劫难”、素有“九尾猫”之称的百年老店--雷曼兄弟公司，由于也“足够大”，也断不可能清盘、倒闭！>>

 

事实上，对此，“欧美社会”其实也是一清二楚。

 

不然，“英国骚乱”何以打出“社会不公”的旗帜？更不然，英国首相卡梅伦何以在“强力镇压”之余，弄出“......不为虚假的民主诉求所阻挡”这一近乎“自打耳光”的“解释”？

 

●“欧美社会”何以还在容忍这种“人类现代史上最大腐败”？

 

不过，在东方评论员看来，“欧美社会”之所以还在容忍这种“人类现代史上最大腐败”，一个最主要的原因就是：<<欧元、特别是美元均用“量化宽松”的手法、暂时压住了“欧美经济烂账的账面”，从而令欧美经济仍然在“勉强的稳定运行”，令欧美民众的生活水平还没有受到不可忍受的冲击。>>

 

因此，从某个角度去看，“庞氏”本人入狱之后曾因“骗”而被“受骗入狱”的狱友“痛殴”，不过是他日“欧美民众生活水平受到不可忍受冲击”之后、稍有机会，就会“痛殴”“另有其人”之“人”的预演而已！

 

 

●“必然”之中的一件“偶然”

 

因此，在“欧盟、特别是美国”玩的这场“庞式骗局”还未“彻底破局”之前，从某种意义上讲，“英国骚乱”也算得上是一“偶然事件”，但通过上面的讨论，我们应该不难明白，这却是“必然”之中的“偶然”。

 

 

而前面已经说了，“英国经济”像极了“美国经济”，也就是说，如果“美英经济”找不到维持“庞式骗局”、或者解出“庞式骗局”的方案，那么，今天的“英国式偶然”、就定会成为明天的一种“必然”、一种“欧式、特别是美式必然”。

 

●在这个问题上，不必怀疑！

 

如果将问题放在“欧美”的层面去观察，在东方评论员看来，一旦它们中的任何一家、因“国际格局不可逆转的变化”而实质性失去“目前仍在持续的量化宽松”之能力，那么，可以肯定的是，“目前仍有待深化的”欧美金融危机“届时必然深化”，欧盟、或者美国经济至少有一家“将”不可能“稳定运行”，从而令欧盟、或者美国民众的生活水平受到不可忍受的冲击，这样，稍有机会，就有可能引发类似于“阿拉伯之春”式的欧洲之乱、或者美国之乱！

 

 

在这个问题上，不必怀疑！“民主与自由”的“大英帝国”已经用一件“必然之中的偶然事件”、给出了无可辩驳的实例！

 

●就目前而言，在国际格局中，明显处于“不可逆转状态”的是“中东破局进程”

 

毫无疑问，就目前而言，在国际格局中，明显处于“不可逆转状态”的是“中东破局进程”，而“美国利益决策层”基于“美国资本利益层面”、循着对“中东破局进程”进行“以攻为守”的原理、所策动的“埃及之乱”继续在“脱稿运行”，并已经在向“中东大乱”的方向发展。

 

 

而针对可能的“中东大乱”，我们想强调这样几点：

 

 

其一，“埃及之乱”后续发展当然会是“一大堆的之乱”，这是没有什么悬念的，因为，“策动者”之所以要“不顾一切地”策动“埃及之乱”，已经说明其“幕后策动者”下决心要策动“一大堆的之乱”、以实现其“不可告人的目的”。

 

●再谈“策动者”的所谓“不可告人的目的”

 

至于这个所谓“不可告人的目的”，在之前的点评中，我们已经详细讨论过，相关讨论的重要观点如下：

 

第一点，“策动者”的所谓“不可告人的目的”，在于：

 

尽力激化“南北撕裂”，从而一面尽可能缓和“三边撕裂”，一边尽可能利用“美元本位制”的金融霸权、在世界范围内、寻找时机、甚至“制造”时机、针对“南方经济体”、并“威、逼、利、诱”欧盟（欧元）与日本（日本），用“天量的硬通货流动性”，共同掀起一场史无前例的、由“北方”对“南方”的大兼并、大收购，直至“北方”彻底掌控“南方经济”的经济、特别是金融命脉，从而彻底地将“南方经济”“永固”在“北方经济”的最下游，从而彻底走出“欧美日债务危机”。

 

值得强调的是，如果我们抽去“三边撕裂”与“南北撕裂”两个框架之“中”的、或、两个框架之“间”的“错综复杂枝节”，就可以清楚地看到，由于“南方经济”的代表是中国经济，因此，在“北方经济”彻底掌控“南方经济”的经济、特别是金融命脉，从而彻底地将“南方经济”“永固”在“北方经济”最下游的层面上，其实现的标志，将是“北方”对中国经济、特别是金融命脉的彻底掌控。

 

第二点，显然，“这”即是“西方资本利益”说服“西方国家利益”的“说词”之一，也是从“美国国家利益”手中刚刚“拿到QE3空间”的“美国资本利益”、用以“说服”“欧洲资本利益）”与美国资本利益“一道去努力”的“说词”之一，还是刚刚与美国资本利益做出妥协，从而令“美国资本（西方资本）”可以继续“量化宽松”的“美国国家利益”、试图“先”通过“美国资本”去“说服”欧洲资本、再通过“西方资本（欧美资本）”去说服“欧洲国家利益”的“说词”之一；

第三点，在东方评论员看来，如果在“定量”的层面去观察，那么，这个“不可告人的企图”也可细化为“理论”与“操作”层面。

 

所谓“理论”层面，阿根廷总统已经说得非常清楚了，即：将金融危机的严重后果转嫁给包括拉美地区在内的新兴市场国家。

 

所谓“操作”层面，在东方评论员看来，这恐怕就是我们一再强调的通过“第三种方式的南亚破局”、伺机将中国推入南亚冲突，再对中国进行经济、特别是金融攻击。

 

至于“破局”的具体路线图，我们可以在“阿根廷金融危机”的“前前后后”中去找寻。

 

第四点，站在“西方资本”的角度，在将中国打造成“第二个阿根廷”的问题上，如果能利用“印度之乱”将中国拖入南亚军事冲突，最大限度地消耗中国的战略资源，这种消耗无疑是最大的，效果也是最好的！

 

如果不能，那么，如果能利用“巴基斯坦之乱”、并启用“拉登遗物”这笔遗产、“制造”巴基斯坦支持本拉登的“事实”，并据此联手欧盟、日本等“8北方经济”、并加上印度等“南方经济”、全面制裁巴基斯坦，就可用“一个极其困难的的巴基斯坦”去最大限度地消耗中国的战略资源，显然，由于“巴基斯坦通道”对中国极其重要，中国对巴基斯坦必然会尽力相“救”，而尽力相“救”也就意味着“极大地消耗”，毕竟巴基斯坦有1亿人口、且国内政治极其复杂！

 

此外，还有一个“已经受到制裁”的伊朗、可以消耗中国。

 

第五点，如果还不能，那么，站在“西方资本”的角度，假如“西方资本”能在“向南方国家转嫁危机”的过程中，先通过“定向引暴”某些南方经济体的金融危机，再伺机通过一场“史无前例的大兼并”、率先掌控印度、巴西等5南方经济的命脉，那么，就可以将“印度、巴西等已经掌握在手的南方经济”、或作为 “低成本生产基地”，或通过立法、行政等手段、实质性限制“中国制造”的对这些市场的进入，从而“不计成本地”用来打击“中国制造”，显然，这也是一种消耗方式。

 

而基于“阿根廷金融危机”的经验，一旦中国政府手中“用于支撑”战略资源被“西方”如此这般地大量消耗，那么，即便中国为应付经济波动而施展“非常手段”，也可能像阿根廷的“非常手段”那样、注定成为“无本之木、无源之水”！

 

最后一点，就是“西方资本”适时启动“加息周期”，在中国制造的生产成本、资金成本、运输成本最高的时候，“进一步抽取”中国的流动性，并通过在中国境内制造“社会环境”、或者“自然环境”混乱，从内、外两个方向逼中国像阿根廷政府那样妥协：为了换取所谓外援、而不得不服下“彻底私有化”的“烂药”！直到将电信、铁路、能源、矿产、特别是金融等战略行业“私有化”、“西方控股化”为止。

 

注：上述观点只是简单的罗列，建议大家重新阅读《东方时代环球时事解读.时事节简版》2011年08月05日的相关部分，以便更好地理解下面的讨论。

 

●警惕“第五点”

 

在之前的点评中，我们还说过：

 

在美国债务危机“急待深化”的大背景下，针对“美国利益”的逃生方案，我们给出了两种可能方案：

 

第一种方案，就是“第三种方式南亚破局”；

 

第二种方案，就是以“利比亚”为支点，针对科索沃问题，对欧盟（欧元）进行跨海一击。

 

然而，基于我们之前的大量讨论，大家也已知道，不论是哪一种逃生方案，要想成功，“美国利益”都必须寻求“中欧”中任何一方的“实质性配合”才行： “第三种方式南亚破局”要想成功，得到欧盟（欧元）的实质性配合是前提，不然，不仅很难离间“中欧关系”，且一旦中国在南亚方向强硬反击，美国（美元）就很难摆脱“为人（欧盟、欧元）做嫁衣”的下场！最为不确定的是，一旦中国在中东方向强硬反击，促成“中东最暴力破局（中东核竞赛）”，则西方资本主导世界的根基都将动摇。

 

因此，站在“美国利益”的角度，如果“最终”也不能得到“中欧”中任何一方的“实质性配合”，则以“西方共同利益”为出发点，通过“向”欧盟利益 “展示”上述“不可告人的目的”，以“第五点”的“可行性”、去说服“欧洲利益”，从而“先”选择“一些“相对较弱”的南方经济体（比如、阿根廷、巴西、印度等）转嫁金融危机，并以此为掩护，“定向”制造“区域性金融危机”，之后，再利用“欧美”手中的“发钞权”、伺机兼并、直至彻底掌控这些“较弱的南方经济体”，直到满足条件后就转入“第五点”的后续部分，特别是针对中国经济的部分，即：

 

  伺机通过一场“史无前例的大兼并”、率先掌控印度、巴西等南方经济的命脉，那么，就可以将“印度、巴西等已经掌握在手的南方经济”、或作为“低成本生产基地”，或通过立法、行政等手段、实质性限制“中国制造”的对这些市场的进入，从而“不计成本地”用来打击“中国制造”。

 

●第五点，缓解剂，调和剂

 

显然，讨论进行到这里，我们其实不难看出，站在“西方国家利益与资本利益”的角度看问题，则，如果“中俄”等“较强南方经济体”最终放任“欧美”顺利展开这个“第五点”，则这个“第五点”本质上可以视为“欧美”的一个、可用于“有效缓解”彼此间“不可调和之矛盾”的“缓解剂、“有效调和”彼此间“很难调和之矛盾”的“调和剂”。

 

或者也是正是看到了这一点，“中欧俄美”及“方方面面”间的“排列与组合”再次出现了变化，其中最具代表性的有这样几件事情：

 

第一，阿根廷、巴西等南美国家即将于周未召开一个南美国家会议，商量强化区域合作、以防范并抵御西方国家向南美转嫁金融危机的相关事情；

 

在东方评论员看来，由于我们非常担心会出问题的巴西可能因“又一次的阿根廷金融危机”而受到经济、特别是金融攻击，而如果西方对南美的经济、特别是金融攻击得手，最终就有可能“威、逼、利、诱”“巴西经济”最终转身变为一个“反华先锋”，这对“中国经济”而言非常重要的“南南合作”损害极大，一旦如此，“南美金融危机”就可能成为“三边撕裂”的“缓解剂”、“欧美国家与资本利益之间矛盾”的“调和剂”。

 

第二，据印度《印度时报》报道，印度国家安全顾问梅农11日就中印关系表示，印度媒体和时事评论员在谈及中印关系时要“学会温和的品质”。梅农强调，有必要确保中印两国不会对彼此产生误解。此外，他并反问：我们为什么要同像中国这样强大的邻国制造自我预言式的冲突呢？”

 

不仅如此，梅农还表示，印度将中国看成是合作伙伴之一。他称，中印双边关系既包含合作也存在竞争。尽管两国之间存在边界纠纷，但只要中印在国际领域致力于共同利益的合作，不损害双方的核心利益，两国的关系就能够像现在这样持续下去。他同时指出：“这也需要两国进行更好的交流，不要对彼此之间的行动和动机产生误解。”

 

而在东方评论员看来，由于“印度经济”极易受到经济、特别是金融攻击，而一旦西方攻击得手，那么，在“埃及之乱”的“后续发展”中出现“印度之乱”也就成了必然。

 

而在之前的点评中，我们已经指出，印度最大限度减轻“西方经济、特别是金融攻击之危险性”的可行方案，就是最大限度地强化与中国、伊朗、巴基斯坦等周边国家的关系、并建立起起码的战略互信。

 

显然，印度国家安全顾问梅农的这番讲话，印度在孟买第二次恐怖袭击后、最终宣布“....是境内恐怖分子所为”，以及印度与伊朗之间及时解决了“石油支付”问题，都是符合上述内容的。

 

南美国家与印度的言行说明，这些极易受经济、特别是金融攻击的南方经济、的确在“高度警惕”着什么！

第三，8月8日，由“郑和”号远洋训练舰和“洛阳”号导弹护卫舰组成的中国海军训练舰编队圆满完成对朝鲜的访问，从朝鲜元山起航回国。

 

值得强调的是，该编队在在访问了俄罗斯之后，访问朝鲜的。

 

第四，8月9日，俄罗斯声称，目前正在与朝鲜谈判计划修建一条穿越朝鲜的天然气管道向韩国出口天然气；

 

而除了天然气管道外，俄罗斯还计划修建一条通往朝鲜半岛的高压电力输送线以便向能源短缺的朝鲜和韩国出口电力；

 

不仅如此，俄罗斯外长还同时表示，俄罗斯还计划将西伯利亚铁路延长至朝鲜境内并经由朝鲜与韩国铁路系统相连。如果条件成熟，俄朝韩三方还可能修建一条海底隧道通往日本，这样产自西伯利亚的原油和其他矿产就可以通过铁路出口到日本。

 

●俄罗斯似乎有意承担“欧亚经济”之间的“物流运营商”与“能源、资源供应商”的双重角色。

 

如果您一直在关注东方时代环球时事解读》，那么，相信你一定会有所印像：

 

其一，俄罗斯的计划、特别是“俄朝韩三方还可能修建一条海底隧道通往日本”的计划，就是途经俄罗斯、联贯东北亚（亚洲）与西欧（欧洲）、最后“加挂”上两个孤悬在欧亚大陆之外的日本与英国之“欧亚铁路线（或高铁线）”。

 

其二，“其一”又与“中国南海示强”战略所暗含的、在“中东大乱”或“欧亚海上运输线大乱”、从而“全球经济硬着陆”的极端情况下进行“最低内循环”的“相关条件”息息相关。

 

显然，透过“俄罗斯计划”，我们不难看出俄罗斯似乎有意承担“欧亚经济”之间的“物流运营商”与“能源、资源供应商”的双重角色。

 

显然，这是俄罗斯也可以在“全球经济硬着陆”的极端情况下维持“经济基本稳定运行”的可行性方案的一部分。

 

●一切都是如此地符合逻辑！

 

第五，就是之前非常低调的欧盟与美国，近日纷纷开腔、对乌克兰逮捕那位“亲西方的”美女前总理“不约而同地”表示“非常忧虑”，其中，美国政府甚至公开呼吁乌克兰政府“立刻放人”！

 

显然，在“有人”替俄罗斯在巴基斯坦方向“测试”了一下“美国实质性启用俄罗斯通道”的“真实态度”之后，在美国的“正式反应”是“仍然未决定”、从而“根本没打算”将美国中亚战略、南亚战略、甚至全球战略的咽喉交由俄罗斯掌握之后，这样，什么“承诺俄罗斯入世”、什么“逮捕乌克兰美女前总理”，在俄罗斯眼里、已不仅仅是“只能欣赏的态度”与“不可以安全享用的成果”，而已经是“一文不值”了！

 

在这种情况下，我们再去观察“俄罗斯计划”，也就不难明白，一切都是如此地符合逻辑！

 

更加有意思的是，就在俄罗斯9日表现出“这一逻辑”之后，接着传来的消息就是：俄罗斯常驻北约代表德米特里&#8226;罗戈津周二（8月 10日）在接受俄新社采访时透露，俄罗斯与北约可能将开始就实施过俄境向阿富汗运输物资的新路线进行磋商，担俄罗斯方面不会对北约军用物资过境的问题放松。

 

显然，驻阿美军的“通道问题”，是美国决策者始终挥不去的“痛”：不论是“向中国借道（巴基斯坦通道）”、还是“向俄罗斯借道”，没有一条是“省油”的“道”！

 

●“近段的”东北亚局势明显透露出一丝诡异！

 

第六，同样是8月9日，据报道，欧盟通过红十字会与红新月会国际联合会（IFRC）向朝鲜提供了20万欧元（相当于28万美元）的水灾赈灾援助。欧盟援助的28万美元被包括在IFRC于2日提供的59万美元“赈灾紧急基金”当中，并已支付和使用。

显然，通过“第五”与“第六”，我们不难感觉到“近段的”东北亚局势明显透露出一丝诡异！

 

同样，如果您一直在阅读《东方时代环球时事解读》，那么，相信你一定会想到，早在欧盟“扛着几袋粮食”赶赴平壤“评估朝鲜粮食问题”的时候，我们就说过：欧盟这是在拿“欧盟支持、甚至准备参与东北亚经济一体化”的“态度”与北京淘换“中国的利比亚配合”。

 

毫无疑问，通过上面的内容，我们可以清楚地感觉到，韩国内部有了变化、至少是那种“对美一边倒”的对外政策出现了“政策层面的调整”。

 

●明眼人一看就知：“极端亲美的李明博势力”明显在“遭遇清算”

 

第七，事实上，自韩国国内突然追查“驻韩美军就地秘密倾倒危险化学品”、特别是媒体高调曝光“韩国高级将领向美国出售韩国机密情报”以来，明眼人一看就知：“极端亲美的李明博势力”明显在“遭遇清算”。

 

众所周知，李明博政府不仅在“天安舰事件”、及“朝鲜炮击韩国军事目标”两个问题上始终没有给出一个令韩国社会满意的交代（一，韩国社会相当多的人认为天安舰事件真相与李明博政府公布的有出入，二，如果真相为李明博政府所说，则韩国政府又缺乏相应的惩罚措施，这同样令人不满），更关键的是，种种迹象显示，李明博领导下的韩国经济已经岌岌可危，极可能再次遭受97年亚洲金融风暴式的重大打击，因此，迫使李明博政府主动缓和与朝鲜、特别是与中国的关系，也就成了“韩国经济”的当务之急。

 

有意思的是，就在这个期间，日韩之间的关系因“日本主挑动主权之争”而突然紧张起来，而针对日本议员执意访问日韩间有争议岛屿，李明博政府也表现得非常强硬，而同时为“日韩”最重要盟国的美国、却突然出手“架秧子”。

 

●“架秧子”的警告意味是明显的：没有美国这个盟友，所谓的“大韩民国”什么都不是！

 

8月8日，据媒体报道，美国最近向国际水文组织(IHO)致函，提出应将东海单独标记为日本海的立场。IHO通过官网详细介绍这一提议，证实了该说法。

 

该说法立刻引起韩国的不满与强烈抗议。

 

而到了8月10日。美国政府则再次强调：支持将韩国地图所标称的“东海（注：日本海）”正式采用“日本海”的标注，并称其“符合美国标准，并无更改打算”，从而在引起韩国政府“强烈抗议”之余，也着实让韩国内部“间接领悟”了“李明博政权所奉行之亲美政策”的必要性，美国在这个时候出手“架秧子”的警告意味是明显的：没有美国这个盟友，所谓的“大韩民国”什么都不是！

 

有意思的是，也就在“韩美”之间围绕“标注”问题争吵、且韩国内部“间接领悟”了“美国很生气、后果很严重”的同时，韩国军方突然称：朝鲜10日向存在争议的“北方界线”附近开炮。

 

●没有朝鲜（中国）的配合，美国想像以往那般维护好“美韩军事同盟”、甚至“美日军事同盟”的尊严，那是做梦！

 

显然，在中国编队刚刚离开、欧盟一再向朝鲜（东北亚经济一体化）示好，而“美国东北亚政策”不仅迟迟不肯重新做人、甚至在关键时刻出手阻止“韩国内部”清算李明博、及微调对外政策的情况下，朝鲜用炮声也让美国“直接领悟”了一点，那就是：没有朝鲜（中国）的配合，绝对实力与相对实力均已实质性下降、且在加速下降的美国，想像以往那般维护好“美韩军事同盟”、甚至“美日军事同盟”的尊严，那是做梦！人们永远要问：炮击之下，“美韩同盟”在哪里？

 

而一旦朝鲜半岛不稳，“美日军事同盟”就会吃重，而要压住比韩国更难控制的日本，美国势必消耗更多的战略资源，其中就包括必须缓和“中美关系”、从而强化中国在<<利比亚问题>>、<<中东和平问题>>、特别是<<科索沃问题>>上的发言权，并促进“中欧战略靠近”，而这，又明显与“美国南亚政策”相矛盾。

 

 

不仅如此，随着“中欧”、再加上“中俄”之间的战略靠近（比如，<<俄罗斯计划>>），即便美国促成“欧亚、特别是中国海上运输线之乱”、或者“非洲的苏丹化、索马里化”，但“中国南海示强”所暗含的“最低内循环”也就更加有了保障！

 

 

●朝鲜10日炮击的结果就是

 

因此，朝鲜10日炮击的结果就是，8月11日，美国国务院发言人努兰德在当天举行的例行新闻发布会上表示，据美国政府了解，韩朝之间的炮击已经结束，美国期望韩朝能够改善关系，并期待朝鲜做出符合纽约会谈成果的举措，以便重启六方会谈，美国已就此向朝方表示了顾虑，并会继续敦促朝鲜保持克制。

 

显然，美国人的态度就是：“朝美之间在纽约谈好了的东西”仍然有效，不受炮击影响。毫无疑问，这一顿炮，对韩国而言，又“白挨”了！而让韩国李明博政府更加郁闷的是，如果就这样“重启六方会谈”，那么，也就意味着“天安舰事件”上的那几十条人命也“白死”了，套用上面的话来说，美国的态度也就是： “韩朝之间的‘天安号事件’已经结束”，及“美国期望韩朝能够改善关系”，并“重启六会谈”！

 

●美国决策层眼下最着急做的事情有两件

 

非常清楚，美国的“战略注意力”无法停留在东北亚，因为，美国决策层眼下最着急做的事情有两件：

 

第一，解开“两种逃生方案（见之前的点评）”的“共同死结”，也就是：寻求“中欧”中任何一方的“实质性配合”、以获取“对另一方展开攻击”的“条件”。之后，或就此发动攻击，或以此“条件”要挟“另一方”提供“实质性配合”，从而“不战而屈人之兵”！

 

第二，如果“第一”无法实现，则通过另外几种手段、特别是“第五点”去遂行上述“不可告人的目的”。

 

而对中国而言，除了要以“无误”的策略“确保”美国无法解开“两种逃生方案”的“共同死结”之外，更重要的是，针对美国所谓“不可告人的目的”，特别是其中的“第五点”，要准备“随时出手破解”。

 

●警惕美国资本对中国香港、中国台湾进行的、旨在“声东击西”的金融攻击

 

在之前的点评中，针对“美国资本”可能进行的“第三种方式南亚破局”，我们曾经提醒：警惕美国资本对中国香港、中国台湾进行的、旨在“声东击西”的金融攻击。

 

此外，我们还曾经提醒，中国要做好国内安全层面的保护工作，包括<<金融安全（网络安全）>>层面的工作。

 

而最新消息是，中国香港的证券交易系统连续两个交易日受到黑客的“有组织攻击”，另外，期间，香港市场明显出现异常波动。

 

●要密切注意南美、印度、东亚国家可能出现的经济、特别是金融危机

 

显然，在我们“对此不感意外”的同时，我们想强调的是：除了更加倍地做好国内各个层面的相关安全工作之外，中国决策层还要密切注意南美、印度、东亚国家可能出现的、因“种种原因（比如、恐怖袭击、金融大案、网络瘫痪等）”引发的经济、特别是金融危机。

 

而这些金融危机一旦出现，就要警惕上述“不可告人的目的”中的各种情况，特别是“第五点”的局面。

 

 

因此，“破解”的原理是一目了然的，那就是针对美国遂行上述“不可告人的目的”的最大优势，也就是“美元本位制”、或者在此“具体理解”为“QE-N”的“量化宽松”之手段，从而：

 

 

第一，“或”尽一切可能的手段、以最大限度地“鼓励”欧盟（欧元）下决心快速解决“科索沃独立后续发展”、并下决心向“欧盟彻底整合的目标”进行“冲刺”；

 

在这个问题上，那架一举报销了、”打死拉登”美国海豹第6分队21名美国海豹突击队员的坠机事件，就可以很好地起到这一效果。

 

大家不要忘记了，通过“打死拉登”的秘密军事行动，美国可是向方方面面演示了“两种特殊能力”的，一是，控制巴基斯坦核武库、并斩首巴基斯坦军事指挥机构的军事特殊能力；

 

再一个，就是“美国资本”掌控全球货币与资本市场的金融特殊能力；

 

而随着执行该次任务的“美国海豹第6分队”中的“21名美国海豹突击队员”被阿富汗反美武装一击致命，美国当时所展示的所谓“军事特殊能力”，也就烟消云散了！

 

值得强调的是，“瞄准”并“打”下一架“支努干”直升机相对容易，最难的是，“知道是谁”并“传递”相关信息的能力。

显然，随着“打死拉登”的、美国最精锐的“海豹第6分队”中的“21名美国海豹突击队员”被装备简陋的阿富汗反美武装一举歼灭，从上任美国防长就开始打造的、特别针对南亚（巴基斯坦）的、被美国决策层赋予了关键时刻可夺取巴基斯坦核武器之特殊任务的、在“打死拉登”中大显神威的“美国特种部队作战能力”，也就成了一个笑话。对此，我们的劝告就是：在阿富汗这个地方，两个大国在旁边盯着，因此，很多时候，之所以看不见你，是因为不想看见你！自己可不要自以为披了件隐身斗蓬！这不，闹笑话了吧！

 

至于“美国的特殊金融能力”，由于美国特种部队此次折戟沉沙，因此，本来还有意效仿“美国秘密军事行动”的印度，之后，如再遇到意外，就更有理由保持冷静了，这样，美国顺势演示给印度经济、特别是印度金融看的、旨在逼迫印度提供“南亚破局实质性配合”的“美国特殊金融能力”，其威力也就大打折扣了！

 

●东方评论员想强调一点

 

第二，“或”紧盯叙利亚这个“止损点”，一旦被“有效击穿”，且就要以“中东彻底破局”的方式、以瓦解“石油美元结算制（美元本位制）”为目的的任何手段进行反击，即便是“中东大乱”也在所不惜。

 

在这个问题上，东方评论员想强调一点，在“伊核问题”问题上，任何势力，不论它之前如何，也不论它之前与中国关系是否友好，如果其“所做所为”最终将“实质性伤害”到中国“在伊朗核问题上的核心利益”者，都将是中国的敌人，在这个问题上，毫无疑问，“中东大乱”如果最终也伤害到它，那也将是“令人遗憾”的！

 

我们注意到，最新消息是，利比亚反对派的战斗力近段显著增强，显然，这是得到了军火援助与外交支持，至于前者，这是违反联合国相关决议的。显然，外交支持可以人“俄颁布总统令禁与卡扎菲政权贸易支持北约行动”的新闻中清楚地看到，至于军火援助嘛？

 

不过，只要俄罗斯不反对，中国也不阻止，那么，“违反”也就违反了，因为，真正想阻止的“人（美国）”，“阻止”两个字实在是“既说不出口、也拿不出手”！

 

至于原因嘛，一来，表面上，为了“美国的全球战略”这个大局，美国还不能与欧盟公开翻脸！因为，美国还想着“第一”，如果“第一”不成，也惦记着 “第二”，而实现“第二”的关键，就是欧盟不与中国联手阻止“美国QE3”，并与美国（美元）联手，用欧元与美元这“两大硬通货”、去水淹“南方经济”！

 

二来，如果公开阻止，导致欧美“公开撕裂”，则无疑就给了“中俄”以可乘之机，则不论是欧盟回归“国际社会”、与“中俄”一道强行打通进3出加沙的 “第三条通道”、从而废掉“石油结算制”的基石，还是与“中俄”一道、参照“中国南海示强”所暗含的“最低内循环”，从而放手“中东大乱”，自己则在“利比亚之乱”与“中东之乱”的掩护下，强行整合欧盟，彻底解决科索沃问题，这两种结果都是“美国利益”不能承受之重！且必然引发类似于“阿拉伯之春”式的美国之乱！

 

值得强调的是，在欧盟回归“国际社会”、与“中俄”一道强行打通进出加沙的“第三条通道”、从而废掉“石油结算制”基石的问题上，“巴勒斯坦官员说不放弃成为联合国会员国的努力”就有这样的苗头。

 

显然，这样的事，如果没有欧盟支持，仅靠“中俄”两家的力量，是无法做到令“巴勒斯坦如此坚持”的。

 

 

●中国打造航母平台原本就立足于“打”、时刻准备打击敌人与挑衅!

 

如果在这个层面去观察中国航母平台在这个时间段里进行试航、及美国立刻要求中国解释航母的用途，也就不难明白两点：

 

第一，中国航母试航、既是在为随时掌控中国南海做6准备，也是在为随时前往亚丁湾、地中海、及欧亚海上运输线打海盗、甚至为强行打通“第三条通道”做准备，还是为伺机解放台湾、统一中国做准备，同样是为了必要时予以周边宵小（包括日本）以痛击做准备。

 

第一句话，中国打造航母平台原本就立足于“打”、时刻准备打击敌人与挑衅!

 

●中国打造航母平台也立足于“护”、时刻准备保护自己的朋友与利益！

 

第二，中国航母试航、在“第一”的基础上，我们也不难看出，这也是在为维护“中国经济最低内循环”的“必要条件”做准备。

 

值得强调的是，中国航母问世的“现实意义”除了上述两点之外，还在于以此为“水面支点”，结合太空中的中段反导、空中的隐型战机等层面的相对优势，从此之后，中国军事力量将可以为自己的海外“核心战略节点”提供有效的军事保护，这一点，对中国类似于“在苏丹的核心利益”而言，或或类似于苏丹之类的友好国家而言，特别具有现实意义。

 

第二句话，中国打造航母平台也立足于“护”、时刻准备保护朋友！

 

由于中国至今没有公开调整中国的国防政策与外交原则，在海上没有军事基地，因此，将首艘航母定性为“科研与训练舰”是再灵活不过了，显然，全世界都可以“搞科研”、任何地方都可以“搞训练”。
