# -*- org -*-

# Time-stamp: <2011-08-04 18:04:42 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 【金鸿95】时事综合分析

  [2008-03-21 16:07:46]

  
    李登辉今天在桃园投票，他投完后，有记者问他投“公投”了没有？他说，我忘投了。
    【金鸿评论】早就说公投结束了,可你们都不信,看看,台独爸爸都没投票,谁会有谁投这个票?看笑话吧,到晚上.
    日本防卫大臣石破茂21日宣布，由于最近发生的海上自卫队军舰撞上渔船导致两名渔民死亡等一系列丑闻，海上自卫队参谋长吉川荣治已经被免职，大约
90名官员受到了处罚。
    【金鸿评论】最新消息,哈哈,小日本太有意思了,现在居然没人管海军了，如果明天开了战，日本海军都没法调动了.光撤了一个,新人没得补,哈哈.早就
说过,提前停了美国人还有点面子,现在好了,全赔进去了,看看强悍的世界警察还有没有帮手!有种美国人就自己为了我们的台湾同胞与中国拼命吧.让全世界人
民都来看看美国大兵是如何的舍己救人的。这可是绝无仅有的好机会！现在好了，美国人连最后的那点幻想都没有了——他是希望把小日本拖进战场，让中国揍
一顿。好得很！布什先生，明天还投吗？希望你有种！我们等着！
     一、中东
    伊拉克官员称，伊朗军队13日炮击了伊拉克西北部的数个库尔德村庄。伊朗方面怀疑库尔德叛军的基地隐藏在那些村庄里。
    中华人民共和国国防部和俄罗斯联邦国防部１４日正式建立直通电话。中华人民共和国中央军委副主席、国务委员兼国防部长曹刚川上将与俄罗斯联邦国
防部长谢尔久科夫通过两国国防部直通电话进行了首次通话。
    【金鸿评论】这两条新闻是一组。中俄建立直通电话不是为了台湾。如果中国收台湾都要靠外人帮忙的话，那中国就别混了。台湾是我们的家务事，我们
谁都不靠。建直通电话是为了警告美国，如果台海有战事，伊朗肯定在中东搞大动作，这样做本身也是为了减少俄罗斯在中东面临的压力。由于欧盟非常配合
我们的台海政策，所以尽量不会宣布伊朗有核，其他的选择项就是让伊拉克开锅。
   动作很干脆，那边伊朗开炮，这边中俄宣布直通。
   ——准确的说，伊朗是在侵略伊拉克。没办法，这年头不是什么事都讲道理的。
   德国总理默克尔18日说，国际社会应继续就伊朗核问题向伊朗施压，以阻止伊朗拥有核武器。默克尔是在以色列议会发表演讲时做上述表示的
   3月19日，瑞士外交部长米舍利娜·卡尔米－雷伊因与伊朗总统内贾德会谈时戴头巾而遭到国内媒体和政治家们的炮轰，他们指责她“这副打扮”显得太过“谄
媚”，与她宣称支持女权主义的立场相矛盾。
   据土耳其私营NTV电视台20日报道称，土耳其军战斗机当天对盘踞在伊拉克北部的库尔德工人党武装实施了轰炸。
   【金鸿评论】欧盟在中东也真没少忙活，看看默克尔是如何在巴以和谈问题上抢班夺权的吧。当然了，欧盟也够狡猾的，一方面在以色列面前装好人，一
方面还在讨好伊朗。唉，没有强大的军事实力就是不行！多累！美国也没办法，还是不得不在库尔德武装问题上向欧盟让步，以换取欧盟在伊核问题对自己的
支持和西藏问题上向中国的施压。
    二、藏独
    【金鸿评论】不看别的，光看我们给这些杂种录得象、拍的照片就知道，之前的准备是非常充分的。一切都在掌握中。正所谓“去之者纵之、纵之者乘之”
，中央干的很漂亮。在这里我就不多费话了。有人问我西藏现状，哈哈，我又不是神仙，我离那至少八千里路，我怎么知道呀，呵呵。不过，谢谢朋友们的信
任。不过，那边应该平稳下来了，当然，必要的警戒还应该是有点，以备不虞嘛。
   至于布朗想见达赖的事情，这个很明显，替美国人在欧美之间搭统一战线的，他想装好人，不过，别得罪了不该得罪的人就好。大家不要把藏独和台独挂
钩，这是两码事。因为藏独基本掀不起大浪来，台独却有可能引发世界大战，这里有本质区别。国际斗争就是这样，你中有我，我中有你，既相互帮助，又相
互算计。欧盟也想抓一张可以压中国的牌，所以一直在打达赖的主意，这很正常。我们不也在欧美之间拼命的砸楔子吗？
    美国助理国务卿、朝核问题六方会谈美国代表团团长希尔19日发表谈话，再次敦促朝鲜全面准确地申报其核计划。

     3月20日，朝鲜外务省发言人答朝中社记者问。发言人说，最近，在中国西藏自治区拉萨市发生了包括殴打、抢劫、纵火、杀人等行为的犯罪事件。这一
事件是西藏分裂主义者在邪恶势力的唆使下有组织进行的，引起了全体中国人民的愤怒和谴责。他指出，西藏是中国领土不可分割的一部分。朝鲜政府对邪恶
势力谋求“西藏独立”、破坏北京奥运会的阴谋活动予以强烈谴责，支持中国政府为维护西藏社会稳定和法治、保护西藏人民根本利益所采取的措施。

    据美国海军时报2008年3月20日报道，据美国军方发言人周四告诉共同通信社记者，在台湾大选之前，美国2艘航母及其护卫编队已经部署在了西太平洋。
     【金鸿评论】美国人坐不住了，想交换了。想可惜，北京不给面子，你想拿入投公联换朝鲜弃核吗？那就先把入联公投停下来再说吧。否则，对付台独
分子就象对会藏独一样！北京的态度非常干脆，也非常坚决。对付那些混蛋，就应该这样！
    别看美国一下子过来了两艘航母，没什么大不了的，没发现吗——小鹰号航母只带了柯蒂斯·韦伯号驱逐舰(美国‘阿利·伯克’级导弹驱逐舰)护航。美国人根
本就没有放手一搏的打算！至于两艘航母会停在台海什么地方，如果我猜的不错，连这两艘航母的头儿都不知道，他们正在海上瞎转悠、等上头的命令呢！哈
哈。
    入联公投早在8日时就已经停止了。
    三、入联公投
    【金鸿评论】下面是8日以来台湾政坛发生的一系统的主要事件。哪里还有入联公投的影子？有的只是各色人等猴跳鳖跳的通过各种方式、以各种各样的
脸谱来支持马英九上台而已。至于马英九跳出来攻击我们温总理的事，道理很简单，他得在上台之前向他的美国主子先表表忠心吧？许多朋友很向往“民主”，
看看台湾，这样的民主有什么意义？当然，比动画片好看一点。事实证明，小范围的民主是可取的，大范围的民主是行不通的。老百姓直接选国家元首是不明
智的，因为大家关心的首先是自己碗里的，只不是整个锅里的。为了捞选票，侯选人也只能顺应民意，只顾眼前满足选民的喜好。所以，为国家长远计，还是
间接选举的好。明天台湾大选了，应该出不了什么事了。公投在台湾都没动静了，还在在世界上弄出花来？回头再看看我前段日子写的【金鸿评论】入联公投
局势追踪(连续一 周共六篇) ，应该没分析错，大家有兴趣，可以看看我9日和10日更新的内容
 
    原本立场深绿的“全民计程车队”大转向，将于十日上午集结二千多辆计程车，在二重疏洪道现场宣誓支持马英九，并由台“立法院长”王金平代表一一授旗
。“全民计程车队”2004年台湾“大选”前，曾发动会员力挺陈水扁连任。
 
　　中新网3月8日电据台湾《联合报》报道，台湾地区领导人选举第二场政见发表会昨晚举行，国民党候选人马英九场边频咳嗽，民进党候选人谢长廷认为马
不是故意的；政见结束时，两人握手，谢伸右手握，左手掌举向马，马忙说不会拍背，谢称是要跟马“击掌”。
 
　　中新网3月9日电据台湾《中国时报》报道，多位已退休的国民党“执政”时财经高官林振国、徐立德、邱正雄、韦伯韬等人八日出面，替国民党候选人马英
九的财经政策背书。其中，陈水扁当局任命的首位“财政部长”许嘉栋，也现身挺马，成为全场关注焦点。
 
　　无党团结联盟籍“立委”高金素梅8日说，“公投”造成蓝绿阵营互斗，无盟党立场很清楚，不论是民进党提出的以“台湾”名义加入联合国“公投”案，还是国
民党提出的以“中华民国”名义重返联合国“公投”案，都呼吁民众拒领。

　　中新网3月10日电台湾国、民两党台湾地区领导人候选人马英九和谢长廷9日下午展开第二次电视辩论会。两人围绕台湾定位问题剧烈交锋，但外界认为，
二人的基本论调并没有重大突破，缺乏让人眼前一亮的论点和攻防。特别是谢长廷只是一味地攻击“两岸共同市场”，被外界认为缺乏新意、只会打“恐共”牌，
难以打开新局以获得新的支持。辩论结束后不久，前“绿委”郑运鹏认为，马谢对决结果，如果没有重大的“天灾、人祸”，22日的大选胜败已定。

　　“入联公投”在岛内反应冷淡，陈水扁昨天下午前往台南县新营市太子宫上香参拜，即时向现场民众呼吁，希望台南县民能在3月22日支持台湾“入联公投”
。

　　一直保持沉默不讲明2008年台湾地区领导人选举挺谁的李登辉，昨天终于说话了；下午马谢进行辩论的同时，李登辉没空看电视，跑去打高尔夫球。对于
记者追问挺谁，他回应说，现在不会为谁站台，至于台联党“立委”钱林慧君夫妇表态挺马英九，他就说，不关他的事。

　　据台湾东森新闻报道，知名艺人小S徐熙娣被问到支持谁时，意有所指地表示，会投给“内外兼具”的候选人。不过吴佩慈就大方公开心目中支持的对象，
吴佩慈表示，“我支持马英九，我希望他当选。” 吴佩慈不但言语上表示支持，就连身上一席长礼服，颜色也是经过特别挑选，连珠宝耳环也一样是蓝色的。

    台“立法院交通委员会”今天邀请台当局“交通部”针对“远航财务危机”提出项目报告。会上，国民党“立委”江连福爆料，根据台湾“华航”内部的相关评估报
告，陈水扁有可能在“520”之前利用松山机场离台。他要求台当局“交通部”要“守好机场”。对此，台当局“交通部”及“民航局”相关负责人都表示不知情，并强
调相关的评估都是公开信息。

    另据台湾媒体民调，岛内近五成台湾民众认为“入联公投”没有举办的必要。岛内呼吁拒领“公投票”的呼声也越来越高。国民党本周三中常会将最终确定对
“入联公投”和“返联公投”案的最终态度。据了解，拒领民进党当局推动的“入联公投”票几成定局。

    中新网3月12日电据台湾《中国时报》报道，台湾“大选”进入决战期，国亲展现大团结气势，国民党候选人马英九和亲民党主席宋楚瑜、国民党主席吴伯
雄十一日晚间在花莲首次同台造势，现场涌入二万五千多人，首次为马站台的宋楚瑜，带领台下群众高呼“冻蒜”(当选)口号，呼吁支持者票投马英九。

    中新网3月12日电据台湾媒体报道，陈水扁昨天评估“大选”选情时表示，马英九不是稳赢，谢长廷也不是稳输，最后一周常有机会逆转胜。陈水扁强调，
他曾说三月二十二日前要退居幕后，不是因为“立委”选差，也不是谢叫他退，而是本来就应以候选人当主角。对于近来参加“公投苦行”等活动，他称作是“做
暗的”、“顾内场”，默默帮忙奔走。

　　据台湾“中广新闻”报道，国民党台北市党部准备周六(15日)，在凯达格兰大道举办“扫贪腐、迎接新台湾”集会活动，邀请上万妇女一同走上凯道扫贪腐。

　　中新网3月13日电台当局“国安局长”许惠佑12日称，所有情治单位绝对不会出现政治性操作，同时“如果命令违法，公务员有不遵守的义务”，绝对会维持
行政中立。

　　中新网3月14日电前民进党籍“立法委员”陈道明涉嫌在2004年“立委”选举期间，以每票新台币五百元不等的金额向选民买票。台湾“最高法院”13日驳回上
诉，维持台“高等法院”更一审判决，判处陈道明一年八个月有期徒刑，并科罚金新台币五十万元，褫夺公权四年。全案定谳。

　　中新网3月14日电国民党“大选”候选人马英九今天上午九时在总部召开记者会，对党籍“立委”前往谢长廷竞选总部抽查引发冲突的行为，再度进行公开道
歉。

　　中新网3月14日电据台湾TVBS报道，受谢长廷竞选总部冲突事件影响，国民党原“立法院”党团书记长费鸿泰，继前晚请辞书记长一职后，今天上午又召开
记者会宣布退出国民党，以示负责。

　　费鸿泰宣布，从现在开始自动退出国民党，不希望因为个人关系，影响到马英九的选举及国民党的形象。他哽咽地说，如果马英九因为这一事件导致落选
，无法打垮贪腐政权，“我不排除结束生命。”

　　中新网3月17日电从去年底就积极推动“两岸和平共处法”的台湾联电荣誉董事长曹兴诚，在个人部落格(博客)中首度表态支持马英九，老曹还点名一个挖
鼻孔的“部长”却能不动如山，令人叹为观止。

　　中新网3月17日电台当局“教育部”主任秘书庄国荣16日以不堪入耳的脏话攻击马英九已过世的父亲马鹤凌，引发台下群众骚动，庄国荣后向杜正胜口头请
辞但并不道歉。庄国荣失言风波绿营忧冲击选情："一人抵四傻"

　　中新网3月17日电台联党中执委罗志明今天在国民党主席吴伯雄陪同下，宣示挺国民党二00八“大选”正副参选人马英九及萧万长，说明他的“三个理由、三
个期待”，同时宣示不会加入国民党，以免被某政党抹黑。

　　中新网3月18日电因爆发“粗口风波”而黯然下台的台前“教育部”主秘庄国荣，虽已发表声明向马英九家人致歉，但负面效应仍持续发酵。

　　中新网3月19日电据台湾《中国时报》报道，马英九阵营经营许久的台湾学界支持力量浮上台面。包括多位现任大学校长、前“教育部长”毛高文、郭为藩
、李焕、杨朝祥、前台大校长孙震等近两千位学界人士参与联署，将在选前一天公开呼吁票投马英九。

　　中新网3月19日电据台湾联合报报道，在一场“大选最后选情”座谈会上，前民进党“立委”沈富雄表示，国民党“大选”候选人马英九胜选大势已定。

　　中新网3月19日电今天是台湾“3"19”枪击案四周年。国民党今天(19日)上午召开“毋忘三一九，全民反奥步(阴招)”记者会，列出各种可能的“奥步”，呼吁
选民“不听、不信、不传”谣言，也呼吁媒体在选前最后关头，要谨慎地处理相关讯息。

　　对于此次台湾地区领导人选举“公投绑大选”，过去鲜少对政治发表现意见的台塑集团总裁王文渊18日指出，不论是“返联公投”或“入联公投”“都是没有意
义的”，“只造成内部对立，甚至影响台湾经济发展”。
 
　　中新网3月20日电据台湾TVBS 报道，陈水扁19日表示“卸任不会把‘政权’交给有绿卡的人”，对此，马英九回应并重申绿卡早已失效，也强调520一到，陈
水扁依法必须走人。
 
　　中新网3月20日电 3月12日谢长廷总部蓝绿阵营冲突事件的主角之一、国民党“立委”陈杰，在事件发生一周后，昨天(20日)首度现身说明事件始末。他说
，当天电梯停在维新馆(谢长廷竞选总部)三楼突然停住，并听到谢总部人员打电话动员时，才知道“中计了”，但因电梯电源被切掉而无法脱身。
 
　　中新网3月20日电据台湾中时电子报报道，国、亲两党合并的进程有具体进展。国民党主席吴伯雄昨天(19日)和亲民党主席宋楚瑜通电话。宋楚瑜同意“大
选”后国亲合并，但强调他个人不要任何位子。吴伯雄则说，国民党还是会用最“尊崇”的方式迎接宋楚瑜；至于要给宋楚瑜什么名衔，他将向国民党荣誉主席
连战请示后决定。
 
　　中新网3月20日电陈水扁20日表示，22日“大选”投票后，不管谁当选，他个人任期到5月19日都要离任、都要交棒，接下来的工作，就是把“政权”交接做好
。
 
　　中新网3月20日电据台湾TVBS电视台报道，一直迟不表态的李登辉，今天下午召开记者会，表示自己的一票会投给民进党候选人谢长廷。
 
　　中新网3月21日电民进党籍台南市议员王定宇服务处，昨天上午接获恐吓电话，对方扬言要赏给谢长廷一颗子弹，警方立刻组成专案小组，昨晚逮获一名
蔡姓男子，依法送办。

　　中新网3月21日电台湾中华视听传播基金会董事长许安进20日号召逾百位地下电台业者挺马英九，坚决反对选举前的任何“奥步”(烂招)。谈到艺人江霞最
近的言行，许安进笑着说，大家都有表态的自由，但请不要攻击别人。

　　中新网3月21日电台湾“独派”大老辜宽敏20日为民进党搭档候选人谢长廷与苏贞昌拉票，脱口抱怨吕秀莲“成事不足，败事有余”。
