# -*- org -*-

# Time-stamp: <2011-08-04 18:03:55 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent


* 【金鸿95】汇率的本质（初稿）

  
    在一个国家内部，不同企业之间竞争的核心是价格——这里所说的价格竞争主要是指以性价比为核心进行的价格竞争而不是价格战；而在国与国之间，经济
斗争的核心则是汇率。所以，我们有必要深入的理解一下汇率这个概念。

    一、国际贸易的本质

    汇率是从属与国际贸易的，国际贸易是国家与国家之间财富转移的一种形式。所以，要研究汇率质，就必须先搞清楚国家与国家之间的财富是如何转移的
。

    国家与国家之间的财富转移有三种形式：掠夺、赠送、贸易。下面一一分析：

    1、掠夺。顾名思义就是“抢”，无本买卖。国家与国家之间最大规模的财富转移都是从通过掠夺进行的。而掠夺有两种表现形式，一是发动战争进行暴力
掠夺，二是通过金融工具 “文明”的掠夺。暴力掠夺是大家非常熟悉的，从1840年到1949年我们的共和国建立的100多年，就是中国被帝国列强暴力掠夺的100
多年。这一掠夺的时间之长、财富之多是人类历史上绝无仅有的。通过金融工具掠夺是第二次世界大战以后才开始出现的。欧美发达国家通过制定金融规则，
运用金融工具对其他的国家进行财富掠夺。拉美经济危机、苏联经济崩溃、日本经济大衰退、东南亚金融危机，都是这种形式的掠夺。通过金融工具对他国进
行掠夺的效果从效果的角度看，往往丝毫不逊于发动战争，上面提到的四次金融危机无一不是让受害国经济倒退十年以上。

    2、赠送。顾名思义就是“送”。古代臣服于他国的小国对他的宗主国的纳贡、现在中国对非洲等不发达国家进行的无偿援助、免除某些国家所欠的债务都
属于这种行为。当然，侨民对其祖国的无偿捐助也应该包括在其中，比如抗日战争期间，世界各国的华侨对中国的抗日捐款就是。

    3、国际贸易。上面的两种财富转移形式，无论是“抢”还是“送”，都是不等价交换，那么，国际贸易应该如何理解呢？等价交换？非也。如果用一个字来
给国际贸易定性， “坑”字是比较合适的。当然，许多人可能认为这种说法是比较“疾世愤俗”的，但是，事实的确如此。下面是三个例子：

    第一个例子：清朝末年，英帝国与当时的清王朝通商，英国殖民者以为中国是一个落后的农业国，进行经济贸易可以轻松的实现对中国的出超，可结果让
英国殖民者大失所望——英国屡屡入超。无奈之下，英国殖民者开始对中国输入鸦片才扭转了局面。鸦片是什么？毒品，卖鸦片是标准的犯罪行为，可英国的商
人品乐此不疲。后来因为清王朝禁烟英国殖民者还和我们打了两次鸦片战争——这有什么正义和公理可言？鸦片贸易可比“坑”要严重多了。如果有人要说那是老
帐，这里有几个数字：根据粗略的估计，毒品贸易的销售额从1977年的1750亿美元涨至1989年的5580亿美元（这表明来自毒品贸易的钱在全球金融市场上扮演
着重要角色）。一些美国金融专家甚至在新闻访谈节目中公开宣称：采取措施制止一些大银行参与“洗钱”将危及整个银行体系的稳定——这说明某些重要银行和
金融家族深深地卷入了数十亿美元的毒品贸易资金的“管理”，他们是在延续一条自英中鸦片战争以来延绵不断的黑线。

    第二个例子：据世界银行统计，发展中国家在1980年的外债总额为4300亿美元。从1980年到1986年，世界一百多个债务国向发达国家支付利息高达3260亿
美元，本金偿付支付了3320亿美元，共计6580亿美元。尽管这样，到1987年，109个债务国还欠着13000 亿美元的债务。——这样高的利息率，不是坑人是什么
？说“坑”是好听的，说 “抢”都不为过！ 

    “剪刀差”这个名词大家都知道——发达国家一直在使用高利率和低原材料价格这对“剪刀的双刃”来抢劫发展中国家已经取得的经济成就。 “剪刀差”的存在
，过去如此，现在如此，将来呢？依然如此！有“剪刀差”的存在，能说是公平交易吗？——不是“坑”是什么？

     第三个例子：在国际贸易中，关税是再正常不过的一道卡了。这道卡合理吗？如果用一首大家熟悉的打油诗来形容关税的话，应该是：“此山是我开，此
树是我栽。要从此路过，留下买路财。”不是吗？如果你不交关税就把产品运到对方国家卖，结果会如何？那叫“走私”！被查住了以后，货要没收，人要拘留
，还要再交罚款。严重的走私还要判死刑。但是，在一个国家内有人敢设这种卡吗？北京生产的东西卖到河南去，河南省敢在河南的边界上设卡收“过境费”吗
？那河南的那帮父母官还不得全部下台？为什么在国内不同的地区之间不能设卡？道理大家都明白，同一国家内的不同经济组织都是平等的，都享受同等待遇
，要公平竞争。那么，为什么不同国家之间就有这道卡呢？而且大家还都认为是合理的（所有的国家都在光明正大的使用关税这个贸易壁垒）。道理同样很简
单，本国的企业要保护。其实，除了关税，在国际贸易中的非关税壁垒更是多如牛毛。所以，国际贸易中不平等处处可见。

    由此我们可以看出，那些发达国家定的“贸易规则”和“国际惯例”就是方便他们合法抢劫不发达国家财富的“强盗规则”。不是吗？为什么近年来美国经常和
我们搞贸易磨擦？因为随着我们国家经济的发展，他们制定的那些规矩挡不住我们从他们国家得好处，所以他们对自己定的规矩都不认帐了。这就是强盗的逻
辑：许他抢我们，不许我们抢他。所以，随着中国的强大，我们必须一步步的去改变那些现行的“贸易规则”和“国际惯例”。说白了就是：我们必须拿到国际规
则的制定权——光知道按游戏规则办事不行，我们必须参与游戏规则的制定，否则，在起跑线上我们就吃亏了。

    二、汇率的概念

    下面，再来看一下汇率的实质。

    汇率是什么？如果用通俗的话讲，就是钱的价格。打个比方说，如果1元人民币兑换0.125美元，则我们可以说1元钱的价格是0.125美元。当然，如果某一
年1元人民币可以兑换0.2美元了，则我们可以说人民币“涨钱”（或者说“贵”）了，也就是人民币升值了。同样的道理，人民币对其他货币的汇率也就是用其他
货币来标示的人民币的价格。

    因为所有的货币都有价值度量的功能，所以，不同货币之间的标价是相互的。也就是说，你即可以说1元人民币值0.125美元，也可以说，0.125美元值1元
钱。同样的道理，一种货币相对于其标价的外币升值，就意味着相应的外币贬值。

    三、公平的金本位与不公平的浮动汇率

    在金本位条件下，不同货币之间的兑换是公平的，也就是说，在金本位条件下，汇率是合理的、不被扭曲的，因为所有的货币都与黄金挂钩。这时就不会
出现某种货币的汇率被人为压低或者抬高的情况——如果出现了，通过对黄金的买卖可以让汇率迅速的回归到合理的数值。举个例子，如果100元人民币相当于1
克黄金，40美元相当于1克黄金，此时的汇率应该是10：4，如果这时有人人为的抬高人民币汇率（比如为了打压中国对美国的出口，汇率升高则出口难度增加
），假如抬高到了10：5，此时，就会有人把大量的人民币汇换成美元——比如把1000万人民币兑成500万美元，用500万美元到美国可以购买12.5万克的黄金，
而此时用1000万人民币在中国只能买10万克黄金。所以，为了防止吃亏，美国官方会马上把人民币兑美元的汇率降到10：4以防止黄金外流（即财富丢失）。

    在金本位条件下，不同国家之间的贸易往来是“相对公平”的，因为有同一个价值度量的标准——黄金存在。但是，在没有了黄金这个价值标准之后，进入了
单纯的法币时代，情况就不一样了。这时的汇率，就变成了一个可以用来制造阴谋、施行阴谋的工具了。

    谁会从这个阴谋中得利呢？自然是能够控制的了汇率的一方。而吃亏的一方，必然是驾驭不了汇率的一方。比如，当年美欧联手逼着日本签定了广场协定
迫使日元升值。谁赚谁赔？自然是施压的欧美赚了，被迫升值的日本亏了。

     在法币时代，汇率实际上是一个杠杆——一根撬动对方国家财富的杠杆。为什么这么说呢？还是举例子说明吧：现在人民币兑美元1：7.5，1美元可以买
7.5元的东西。如果人民币贬值到了1：10000（贬值1333倍），则美国人用20亿美元就可以“交换”到中国人民一年创造的财富。

    有没有认为这在做梦呢？

    事实上，在过去的几十年里，这样的情况不止一次的发生过：1982年年初，墨西哥比索对美元比价为12：1，而到1989年，比索对美元已贬到2300：1。比
索的贬值近200倍，比起我上面举的例子中的1333倍稍微小了点而已。在苏联经济崩溃的时候，卢布的最低实际贬值112000倍，美国只用了几亿美金就买下了
价值28万亿美元的原有苏联资产。从这里可以看出，汇率是进行金融战争的最强力武器。

    由此可以看出，在金本位下，不存在人为操纵汇率的基础，任何国家的人民创造的财富都不会轻易的“被偷走”，除非通过大规模的战争进行暴力掠夺。只
有在法币时代，才有可能出现人为操纵汇率的情况——所有让国际金融集团大发利市的金融危机都是发生在法币时代就足以说明这一点。因为在法币时代，没有
了超越国界的、统一的度量财富的工具，这就为通过汇率武器这根撬动他国财富的杠杆“偷走”他国财富创造了必要条件。当然，还有一个前提条件是必不可缺
的，这就是允许汇率自由浮动。

    西方研究汇率形成和变动的理论也有一大堆：国际借贷论、购买力平价论、汇兑心理论、货币主义、资产组合平衡论等等，哪个对呢？都不对。这些理论
都是在法币条件下创造出来的，他们无一例外的在做分析时把黄金扔到了一边，而事实上，任何一个国货币的价值都是以其含金量为基准确定的。没有黄金作
为货币价格的度量标准，货币价值就象断了线的风筝，漫天飞舞。没有了黄金，滥发货币就成了那些私有的中央银行可以为所欲为的事情，通货膨胀也就不可
避免的出现了——既然一国货币的价值都成了无法准确度量的东西，那不同国家的货币之间的价值比较（即汇率）就更无从确认了。所以，失去了金本位之后，
浮动汇率才成为现实；黄金才是钉死汇率的那道镇魔符。

    我承认，在没有人为操纵的情况下，浮动汇率是非常合理的，但是，现实情况是，各国的政府力量和国际金融资本势力都在充分的利用自己的手中的力量
，或是行政力量，或是金钱的力量，人为的操纵汇率，这就让浮动汇率成了最不公平的汇率制度——在完全竞争的市场上，无论是商品的消费者还是供应者都感
觉市场“那只看不见的手”是合理的；可是，如果有人利用掌握在自己手里的条件（比如行政垄断、资源垄断）把“那只看不见的手”变成了“自己的手”，这时，
无论是消费者，还是那些处于被动地位的竞争者，将感觉不到任何公平可言。这时，市场的“价格发现”功能、优化资源配置功能都被大大削弱甚至扭曲了。

    能不能消除这些操纵汇率的人为因素呢？不可能。因为国际贸易本身就是在“坑”，就是一场不见硝烟的战场，所有的参与方（国家或者资本势力）都在为
了实现自身利益的最大化而不择手段的努力着。在一个国家之内，市场是受行政力量控制的，垄断可以被行政力量打破，在国际资本市场上，根本就没有一个
能真正管理得了各种参与方的机构，公平竞争自然无从谈起了。在这样的前提条件下，浮动汇率自然是最不公平的汇率制度。

    如果允许一国货币自然浮动，无疑相当于把一国经济体变成了一艘无锚的航船——在狂风巨粮的冲击之下，极有可能出现倾覆的情况——国际金融势力洗劫他
国财富无一例外都是在浮动汇率下才得手的。所以，人民币汇率绝对不能自由浮动。那些所谓的“人民币汇率应该自由浮动”的建议都是希望置中华民族于万劫
不复之地的——国际金融资本早就在中国境内埋伏好了大批的伏兵（即流入国内的热钱），只要我们打开了大门（即人民币宣布自由浮动），热钱将对中国进行
内外夹攻，中国人民六十年辛苦积累的财富将会在一夜之间被抢走。

    国际金融斗争从来就不是在公平的条件下进行的，更没有雷锋式的国家（除了中国）去对别人进行雪中送炭，有的只是落井下石、不择手段，榨干对手的
最后一滴血。

    四、科技进步在汇率变化中的决定性作用

    那些国际收支理论（弹性论、乘数论、吸收论、货币论等等）在做分析的时候，都忽略了一个最根本、最重要的因素——科学技术。所有的国际收支理论都
强调，一国贸易出现逆差，是因为它出口产品的价格水平（性价比）偏高、没有竞争力，所以应该通过贬值来降低出口产品的价格水平，增强竞争力。其实，
从长远来看，决定物价水平的因素只有一个，那就是科学技术。举个例子：两户农民种地，一户是三口人种了5亩地，手工劳作，；另一户雇工30人使用了大
量先进的机械设备，种了2000亩地。这两户农民谁的粮食更有价格竞争力？傻子都能看出来，手工劳动的那一家肯定会破产。其他的产品也是同样的道理。法
国人心目中的英雄拿破仑称帝后，特地给自己做了一顶铝的王冠——大家不要笑，那时的铝价比金子贵数十倍。可后来呢？电解铝技术一问世，铝价一落千丈。
这时，拿皇帝死都不戴那顶铝冠了——丢不起那个人！

    再来看一下前面提到的“剪刀差”——发达国家用高利率和低原材料价格这对“剪刀的双刃”来剥削不发达国家靠的是什么？金融霸权（这里的表现是包括制定
利率在内的定价权）。此外，发达国家还以超高价格卖给不发达国家高科技产品，赚取远较在国内销售高的利润。比如，OFFICE系统在美国只卖40美元/套，
相当于一个美国蓝领工人2小时的工资，在中国呢，6000元人民币/套，凭的是什么？人家掌握的高科技。

    其实，发达国家只所以能拥有金融霸权，靠的也是科技术领先——200年来先后出现过两个拥有金融霸权的国家，一个是英国（日不落帝国），一个是美国
。英国当年靠的是工业革命带来的技术领先，美国就更不必多说了。所以说，金融霸权的支点是科技领先——如果说金融霸权是王冠上那颗光芒璀璨的宝石，那
么科技领先就是那个王冠。有一个现实大家都能看到，就是美国用自己的强大的军事力量保卫着美元霸权——在任何一个国家，最先进的科学技术永远是首先应
用于军事，之后才是军转民。所以，中国要强大，必须加强军事技术方面的研发投入，全力赶超，只有中国拥有了全世界最领先的军事技术，才能保证中国不
再受制于人，受欺于人。这不仅仅是为了保家卫国，更是为了中国的经济强盛。

    所以，从长远来看，提高一国经济体的综合竞争力，从而确保国际收支平衡政策的实现关键要靠加强研发，提高本国的科技水平，其他的有关国际收支的
政策引导机制，都是临时性的，那些财政政策、货币政策、汇率政策更是头痛医头、脚痛医脚的法子，绝不可能从根本上改变国际收支恶化的状况；只有提高
科技水平才是固本培元、强筋壮骨的正路子。

   五、国际金融势力的赌具——金融衍生工具

    在金本位下，那些形形色色的金融工具中的绝大多数是无法出现的，因为没有他们存在的土壤。金融衍生产品分为四类：远期、期货、期权、互换。其实
，无论哪一类金融衍生产品都是在赌博，因为无论是金融衍生产品的买方还是卖方都不创造新的价值，而只是在进行财富的再分配，这跟在赌桌上赌大小赢钱
没有任何区别。而且，许多金融衍生产品还有高杠杆性，可以以小博大，如此一来更放大了风险。

    相当数量的金融衍生产品是打着“规避风险”的旗号出现的。事实上，它们完全是在投机，它们把个体风险变成了系统风险——它们不是在灭火，而是在点火
。美国的次贷危机就是个明显的例子——不就是一部分信誉比较差的购房贷款人还不起贷款吗？如果这样的事情发生在中国不就是给银行搞出一点呆帐吗？可美
国、欧盟、日本三家联手注资救市多次都解决不了问题。为什么？全拜金融衍生工具所赐放大风险所致。

    其实，“规避风险”只是糊弄人的。风险一直存在，只是通过购买金融衍生产品可以转移风险而已。从本质上讲，转移风险本身就是一种不负责任的行为——
把自己应该承担的风险扔给别人。当然，普通的从事国际贸易的人是被迫的，因为在金本位条件下（固定汇率条件下也可以）是不需要转嫁汇率波动风险的。
由此可以看出，浮动汇率是鼓励不负责任的投机行为的制度。这是一套罪恶的制度，它不倡导人们通过诚实劳动来创造财富。

    金融衍生产品是虚拟的，但是它们是建立在现实基础资产之上的。由于金融衍生产品疯狂发展，其规模早已远远超过了基础资产市场的规模。例如，1997
年初，仅美国商业银行就持有名义价值为25.7万亿美元的衍生合同，这是美国GNP 的三倍以上。许多欧美日银行的衍生合同都5-10倍于它们的资产，100-500
倍于它们的净值——这意味着整个世界金融体系已经事实上破产了。金融衍生产品发展到今天总额就更不得了了——仅仅美国商业银行所申报的 “利率掉期”就有
74万亿美元。由此可以看美国的金融泡沫大到了什么程度！

    从某种意义上说，全球金融体系已经破产了。

    关于国际金融的相关分析暂写到这里，因为刚刚开始学习和思考这方面的东西，深度还非常有限，有许多关键的东西思考的深度还是远远不够的。随着时
间的延续和个人水平的提高，再做总结吧。
