# -*- org -*-

# Time-stamp: <2011-09-16 01:03:14 Friday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:3 LaTeX:dvipng

#+STARTUP: indent

#+TITLE:

#+AUTHOR:

#+SETUPFILE:~/dea/templates/level-0.org


** OpenOffice.org公式编辑器完全教程

*** 简介

#+begin_verse
原创作品，允许转载，转载时请务必以超链接形式标明文章[[http://zhouguidi.blog.51cto.com/1653754/346109][原始出处]] 、作者信息和本声明。否则将追究法律责任。http://zhouguidi.blog.51cto.com/1653754/346109
#+end_verse

经常写公式的人，都用过各种公式编辑器，比如Microsoft的公式编辑器MS公式3.0（Word附带）、MathType等。相比于MS公式3.0，MathType功能强大的多，也是很多人使用的公式编辑器。然而，MathType（以及MS公式3.0）都是采用的都是“所见即所得”的操作方式，所有的输入都要依赖鼠标在公式编辑器中点击选择各种公式元素来完成。如果只输入几个简单的公式，这没什么问题。然而，如果你面临的是一篇充满公式的科技论文，甚至是一本数学书，那么我想不管是谁也会发抖的。虽然可以使用内置的许多快捷键来加速操作，但要快速准确的按下这么多快捷键也不是一件容易的事。而且，还有一个重要的问题——这些软件都是商业的，你需要向软件开发者支付一笔价格不菲的费用。当然，除非你觉得版权问题无所谓，从而心安理得的使用破解软件。

除了微软的Office软件之外，Oracle（以前是Sun）的OpenOffice.org应该是最流行的一种办公软件了。它功能上的强大并不亚于MS Office，而且是开源软件，你可以自由获取使用它，甚至如果可能，你可以修改并重新发布它。OpenOffice.org于MS Office同样属于所见即所得的编辑模式，然而它的组件之一——OpenOffice.org Math公式编辑器却采用“所想即所得”的方式。使用它，你不需要频繁的切换于键盘和鼠标之间，可以不受任何打扰地将存在于你头脑中的公式像流水一样的输入到文档中。这是通过Math使用的公式解释语言来完成的。只要你掌握这种简单高效的语言，你就能将你的公式像说一段自然语言一样“说”出来。Math提供的各种公式元素和公式控制符号能够让你轻松输入极其复杂的公式。事实上，OpenOffice.org Math也提供了类似MS公式3.0和MathType的依靠鼠标点选来输入的操作方式，以提供一个直观的输入感受，使习惯MS公式3.0或MathType的用户能够继续使用其熟悉的输入方式并逐渐过渡。

另外，MS Office和OpenOffice.org之外，LaTex也是使用十分广泛的排版工具。它完全采用所想即所得的理念，一篇文档的任何输入、编辑、格式控制都是通过其命令语言来完成的，当然也包括公式。与MS Office和LaTex相比，OpenOffice.org可以说是一种折衷：其文档编辑（OpenOffice.org Writer）是所见即所得的，而公式编辑是所想即所得的。这使得熟悉MS Office的人可以快速转移到OpenOffice.org，而不需要去学习大量的命令；同时又使公式的编辑变得十分高效。同时，有一个OOoLatex插件可以让你在OOo中输入LaTex风格的公式。

Math既是OpenOffice.org Writer的一部分，也是一个单独的程序。你可以单独运行Math，编辑公式，然后存为odf格式，然后插入到Writer中；也可以在Writer里通过“插入”-“对象”-“公式”菜单来插入一个新公式并编辑它。

这各系列的文章准备来详细介绍一下OpenOffice.org Math的使用，让我们一起来享受输入公式的乐趣吧～因为我也是刚学，所以里面出现什么问题也是很正常的，发现什么问题可以在博客上留言，欢迎讨论。主要参考资料是OpenOffice.org Math帮助文档。


   
*** 基本知识

**** 公式的组成
Math采用一种公式解释语言来描述公式。这种语言由各种运算符、保留字、函数、变量、常量和文本组成。运算符、函数是预定义的，用来表示各种运算；保留字是用于控制公式显示方式的，它们自身是不可见的；变量是出现在公式中的自变量、因变量；常量一般是指数字；文本是区别于前面各种公式组成成分的，它用于在公式中显示一些纯文本。另外，Math允许用户自定义运算符和函数。各种公式成分往往具有不同的外观，如函数、常量和文本一般显示为正体，变量一般显示为斜体。这也是可以自定义的。

在本系列的文章里，我们将用 =<?>= 表示任意一个变量、常量或文本，并将它们称为公式元素。

Math将任何连续的字母（英文字母和希腊字母）、数字视为一个公式元素。公式元素不能包含空格和运算符。比如

:    a，abc，a1，123，12a 

都是合法的公式元素。而

:    a b，a+b，a(b 

等将被视为两个公式元素。
Math中希腊字母用%+字母名称表示，比如%alpha=>\alpha ，%rho=>\rho，%DELTA=>\Delta，%THETA=>\Theta。
现在我们可以输入简单的公式了，比如

:    z=x+y，z=2x+y，z=2(x+y) 

等，都是很简单的。
**** 复合元素
有些时候需要将多个公式元素一起当作一个来使用，比如下面的公式
，
“i=1”是一起作为x的下标出现的。如果输入

:    x_i=1 

（_是下标运算符）将会出现这样的结果：


因为i=1是两个元素，而下标运算符_只能将其后的第一个元素作为下标。此时需要复合运算符。
复合运算符是用花括号{}来定义的。任何放在花括号里的公式成分都将作为一个单独的公式元素来使用，而不管其内部有多复杂。因此上面的公式应该表示为

:    x_{i=1} 

公式元素也可以嵌套，比如

 :   x^{e_1^2} 

代表公式 $x^{e_1^2}$ ， 其中^是上标（或乘幂）运算符。 下面我们提到公式元素时，都是既包括单一元素，也包括复合元素的。

**** 文本、空格、换行和注释

默认情况下，除了常量之外，任何公式元素都是作为变量的。如果想将一个元素设为文本（比如为了使之变成正体，而不是斜体），则可以用一对双引号将其包围。比如微分算子

$\frac{dy}{dx}$

:    {d y} over {d x} 

（over是分式运算符），一般情况下微分中的“d”都是正体的，而Math把“d”也作为变量了，变量的默认字体是斜体的。只要改成

:    {“d” y} over {“d” x} 

就能使“d”成为文本，从而使用文本的字体（一般是正体），即 $\frac{\text{d} y}{\text{d} x}$ 。

这里有个小问题，就是分子和分母都没有居中对齐，而是左对齐的，这样有些不好看。解决的办法我们下面会提到。
前面提过，空格是用来分隔元素的，除了这个作用之外，空格别无其他作用。在其他空格或运算符已经将元素分开了的情况下，多余的空格都会被忽略。那么如果要在公式中加入空格怎么办呢？可以用“`”（键盘上Tab上面那个键）或“~”（shift+`）。`是小空格，~是大空格。它们都属于公式元素的一种，可以理解为特殊的内置变量。另外还可以用空元素{}来插入空格，它相当于`，也是小空格。

另外，Math的公式默认都是在同一行显示的，即便你输入了回车符也是一样。因此一行公式可以分几行输入，这样可以增加代码的可读性。如果输入分几行显示的公式，需要用newline保留字，它把其后的公式放在下一行显示。

为了增加代码的可读性，也可以在代码中加入注释。注释使用%%定义，并一直作用到一行代码的结束，因此如果使用注释，必须分行写代码了。如果要在公式中显示%和%%，可以用双引号将之变为文本。

4. 更改默认字体
默认的字体在那里改呢？点击“格式”菜单下的“字体”子菜单，将弹出“字体”对话框，里面列出了各种公式元素使用的字体。点击右边的“更改”按钮可以改变默认字体。
