# -*- org -*-

# Time-stamp: <2011-08-23 14:58:30 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 井底望天：希拉里的梦想开始成真了


[2011-08-20 12:11]


记得有一段时间，我的博客集中批判了美国国务卿希拉里。当时的批判要点，就是希拉里想 *把美国发展起来的社交媒体高科技，作为颠覆和搞乱美国不喜欢的国家的工具。*

从我的一系列关于谷歌的文章开始，就一直提醒中国政府相关部门不能对这种手法掉以轻心。

不过现在看来希拉里的梦想开始成真了，只不过这些工具对付的目标，成了自己和自己的盟友。

前一阵为北非和中东大乱而幸灾乐祸的西方人士们，现在就要面临他们自己种下的恶果了。而这个大节目的预演，就是最近发生在英国伦敦、伯明翰等大城市的城市骚乱。

在这里，我就把这种现象大致归纳一下。

首先，在社交媒体出现之后，人群的集聚的速度变得更快，成本变得更低。很快的就出现了一个称谓，叫做“ *闪聚族* ”。就是英文 *Flash Mob* 。

这个闪聚族的出现，刚开始是以年轻人无聊，想搞点乐子的方法出现的。比如说，在伦敦火车站候车厅，或者纽约地铁站，等等公共地方，突然在某一个特定时刻，大家开始跳集体舞。这样的玩意，一下子在欧美变得极其流行，在youtube等地方给贴出来，然后其他地方的人又开始仿效，变成了一种风潮。

这个时候，这种现象是受到社会欢迎的。而且主流媒体还给加上了“文明优越”，“西方文化创意”之类的牌坊，来到全世界去敲打其他的不普世国家。

然后，在这些年轻人逐渐积累了召集和行动的经验之后，慢慢闪聚族的行动就开始多样化了。

在美国的一些大城市，比如说纽约、华盛顿、芝加哥、克里夫兰等等，都出现了闪聚族出来抢劫和破坏的情况。而其中最为严重的，是费城。那么这些行动通常是如何进行的呢？

就是发一个帖子，大家什么时候，到哪里。结果就是短短几分钟的时间，上百甚至上千的无所事事的年轻人们出现在预订地点。这个地点，可以是一条街、一个饭店、一个商场之类。然后大家就一鼓作气，在街上把行人给抢了，还有的居然就把人家给打昏过去，顺便把附近商店也抢了，把玻璃给砸了。当然路边的汽车也同样遭殃。

而这样的行动，进行的时间相当的快，通常是在警察准备出手的时候，大家已经化整为零，做鸟雀散了。
最近这样的趋势有从大城市，向中小城市蔓延的趋势。比如说，前几天，马里兰州的一个小城，就有商店被闪聚族们给抢了。大家因为抢来抢去，行动效率有所提高，这次是不到一分钟，就完事了。

当然美国的闪聚族，还没有像英国的同志们那样，放火烧城市。而且英国之前，还出现查尔斯王子夫妇，被人围攻的现象。

对这些变化，美国的治安部门暂时还没有太好的法子。一个原因是代沟，就是很多警察部门，甚至连推特是啥玩意，都不知道。那么费城实行的法子，就是戒严和宵禁，晚上就不许你年轻人出来。出来，就把你抓到监狱里去。

不过这个法子只能是临时措施，专家们认为最好的办法，就是要搞网管，要有眼线。就是说你推特等等上面，不管有什么风吹草动，警察部门都可以全时段监控，然后可以以快制快，敌动我动。

不过要是美国也这么干了，看希拉里还有什么厚脸皮，可以出去敲打其他不普世国家。

美国和欧洲现在的问题，就是长期失业率高企，导致现在的年轻人，没有工作做。然后又在家看到父母也没有工作，想啃老也没机会。那么现在这些国家的大幅度削减政府开支和福利的路数，只会让这样的情景更严重。

在这种情况下，大部分年轻人，充满了愤怒情绪，又觉得前程茫茫，而且人生充满了无聊。而且大家沉迷于电脑游戏，在那里是一天杀掉了半个世界的人口，那么这些因素加在一起，就够大家喝一壶的了。

然后你这帮有钱佬还出来发飙显摆，像希拉里，嫁女的婚礼，都要排场到7百万美元。

现在出现的闪聚族，还是抢点东西而已。将来给你一个微薄，说是大家带齐武器，把某个建筑物给灭了，那就严重了。
