# -*- org -*-

# Time-stamp: <2011-08-06 09:07:02 Saturday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+STYLE:<link rel="stylesheet" type="text/css" href="css/org.css">

* 高铁和事故

最近因为温州出了一桩大事故，有幸看到了广东电视台的报道和新闻评论。

这个事故发生的时间，也有另一件大事情发生，就是挪威发生了枪击和爆炸案，震动了整个欧洲。而美国正好就是白宫和国会，关于国债封顶的斗争，到了拼
刺刀的白热化阶段。

所以中国动车事故，没有成为热炒的头条。大概只有日本的新闻女主播高兴得捂着嘴巴笑，整个日本国民心态幸灾乐祸。咱们当然不能跟这样的人一般见识，
只不过小心核辐射，不要乱买日本货就行了。

广东电视台的新闻评论，说是铁路事故，是体制问题，是政企不分问题，就差没有说，是私有化程度不高问题了。

铁路本身当然是有问题的。就算是没有这次的事故，大家已经对各类动车组过了保修期，而铁路自身的技术维修能力可不可顶上大梁，有保留意见。因此整个体系稍微慢下来一点，好好整顿一下，把各类隐患排除一下，是比较明智的选择。

当然刚刚铁道部高层换将，在整顿过程中，如果不是以技术和管理作为切入点，而变成各派人事斗争，站位选边，内斗加剧而导致军心涣散，引发小事故层出
不穷，那么就走歪了路了。

铁路出车祸，不止一次了。生命的丧失固然可悲，但是要是以人血馒头为武器，把一个新生事物和新技术给彻底消灭，就是要大家防止出现的趋势。以高铁的竞争对手航空业为例，就是现在咱们还是时不时看到飞机跌下来，造成几百条生命的丧失，但是这个没有制止大家继续坐飞机。

对铁路也是一样，好好把事故原因查清楚，不要满足于处罚了什么人，而是要把程序、制度和运作提高上去，把技术安全摆到首位。这样才是真正的事故处理的路子。

因为我们也不是技术内行，所以不能像媒体的记者一样，自己出版技术分析报告。等一等专家的调查意见出来，在作定论。

至于铁道部本身，早就是大家看准的一个靶子。从铁路运营方面来看，因为新线路的建立，旧有的客运线路，里面的商机无穷，自然就会成为各派利益集团眼红的目标。可以预见，关于铁路部门如何糟糕的舆论会越演越热闹，要求瓜分掉铁道部的各条运行线路，尤其是利润丰厚的客运线路的经营权的呼声，会比较高涨。

* 再说几句


现在网上有传言，说是日本或者美国的计算机病毒，侵袭了中国的高铁系统。大家听了笑一笑就行了。

想起以前看个一本书，叫做《动物农场》，说的是动物们反抗人类的压迫，自己组织了自己的动物农庄。大家为了让生活过的更好，就去建设磨坊。结果因为质量有问题，就在大风雨中倒塌了。于是领导说，这个是阶级敌人破坏。

这样的想法和说法，中国以前的历史里，也是常常有的。

但是不信这个传言，并不等于不应该提高警惕。正如美国曾经发生过一次电力系统的大停电事故，算是半个国家都受到了影响。这个事故是设备问题，但是立即引起了人们的关注：如果敌人要来搞破坏，这个岂不是软肋之一？

中国人也应该有这种居安思危的想法。害人之心不可有，防人之心不可为啊。

那么现在一些国家，比如说日本，在中国高铁安全上大做文章，也很正常。只有参照美国为了救亡三大汽车公司，从而使劲抽丰田的故事就行了。当时丰田出了一个故障，造成了几人死亡，于是美国大规模进行炒作，终于把三大汽车公司救出了火海。至于会不会对中国高铁的出口造成影响，大家也不用担忧。自己把自己内部的事情做好，把自己的安全可靠性做到家，你当全世界人是瞎子啊？

这个世界有冥冥的上天。德国人就比较克制，没有乱讲话。毕竟德国自己的高铁也出过重大事故，还死了100多号人呢。日本人上次看到云南地震，还惋惜地说，咋不在北京上海发生大地震呢？话音未落，自己家里就来个地震、海啸，加核辐射了。做人还是要厚道点。

但是对铁道部那帮丫，就不能厚道。看着那个什么发言人出来讲话，那副嘴脸，不用听到胡说什么，就想一巴掌扇过去。

铁道部是应该好好整顿一下，好好反省一下，人命大于天。那怕是不幸遇难的受害者已经仙去，他们的遗体和遗物，都有最大限度的受到尊重。你出事的这条线路，又不是京广线，你晚两天恢复通车，多搜寻两天，会死啊？

该装孙子的时候，还学人打官腔，被愤怒的人们涂抹淹死你，活该。

有人问，为啥高铁和动车跑了几年，一直没有出事，而现在却是事故频频？

很简单，铁道部的这一套运行体制，有不合理的地方。以前刘跨越在的时候，这家伙是一个疯子，每次试车的时候，自己都要占车头，还要拉着手下的一帮高官，以身作则，都站在那里。如果一出事，大家就是一锅端。

于是这些手下人，就比较卖力，怎么也要保证自己的小命安全吧？而且还是老实验超高速，就是说你跑它个400，也可以顶得住，那么跑300，就要放心多了。一种说法是，老刘给干下来之前，京沪线的枣庄到蚌埠是他亲自折腾的，所以现在京沪出毛病的地方，都是这个区域之外。

现在的铁道部是新官上任，老刘那套拼命三郎的法子是不搞了，可是其他的法子似乎还没有出来。所以铁路的问题，似乎有点总爆发的味道。正好也给私有化们，航空业们，波音公司们，振奋一下士气。

本来出点故障是小事，铁路晚点一下，也不是什么大事。大家谁都经过飞机和汽车晚点的。可是晚点的车，居然撞到了另一个晚点的车，还死了人，那就是大事了。

天大地大，不如人命最大。如果不记住这句话，那么你铁道部就没有一天好日子过。

* 再说高铁
[2011-07-29 15:15:14]

大家对动车事故很愤怒，因为死了39人，而且铁道部的救援和公关处理，与大家要求的水准相差太大，骂他是活该。

可是前几天好像还有一桩事，就是有一架客车着火，死了人好像还更多一点。似乎没有太多人关心那件事。

原因有很多方面，不过可以想到的大概有几个：

1.客车的事情，估计最终是和私人有关，所以没有骂的后着在里面。而铁路的事情，是政府，骂起来可以一路延伸下去，直至无穷，骂出一部红楼梦都可以
了。

2.客车上的人，是坐不起高铁和动车的人，是真正的下层。坐高铁和动车的人，是中上阶层。所以自由媒体们，网民们屁股是在中上阶层里面的居多，感同身受，骂起来自然贴切。

3.高铁嘛，已经是太长时间的靶子了，不打那可是白不打。

上次说到日本女主播笑得梨花带雨，有人说是PS出来的。所以这里更正一下。不过日本全社会像是打了兴奋剂似的，那也是事实。看到西方的不少新闻主播，在75之后的眉开眼笑，不会太觉得惊奇就是了。

有读者，尤其是铁路行业的读者，对刘跨越有异议，非常正常。因为刘老兄是一将功成万骨枯，当时对铁路职工鞭子招呼得紧，糖果给得少。对比其他国企，比如说两桶油的脑满肠肥，大家确实是一腔怨气。

我在《苍天黄天》里谈到美国修建跨大陆的铁路，中间充满了丑闻。但是这条铁路，导致了美国西部扩张的成功，并真正意义上奠定了一个统一美国的基础。如果没有这条铁路的出现，今天的美国可能是几个国家，互相打来打去呢。

当时美国的私人铁路，都是想在人群居住集中的地方，比如说从纽约市到水牛城这样的地方修建。跨越大陆的铁路，是先铺路，在求发展，盈利上没有保障，私人鬼才给你干呢。而就算政府出钱，无利不起早，那些国会议员们若不是自己可以从中间捞到大笔油水，鬼才花那个功夫去搞条铁路出来呢。

中国也是这样，如不是好处在那里，你以为刘跨越们会那么起早贪黑，尽心尽力去搞铁路大发展？

有人说，为啥不像我们当年搞两弹一星那样，又可以搞好大工程，又可以无私贡献？因为很简单，中国50年代的献身精神，在今天，或者说大部分的人类历史时间，是不可复制的。那是非常时期才会出现的人类精神升华的时期。比如说美国人在抗击英国佬要独立的时候，苏联人要抗击德国佬入侵的时候，中国人拼死打小日本鬼子的时候，这些都是历史的非常时期。 大部分的时候，人性就是那么丑恶的，大家期望不要太高。所以刘跨越贪污也好，腐败也好，这是中纪委要关心的事情。他只要把铁路给搞出来就行了，至于贪污掉的钱，现在让他吐出来，不就是了？

而今天的铁道部的领导们，如果你拿不出法子来，让铁路的事故发生率一直下去，忙于“组织建设”换人，而不是重点在安全上面，那么高铁这个新生事物，被搞黄也是不出奇的。
现在就回到一下关于高铁赚钱不赚钱的问题。

高铁要赚钱，很容易。那就是提高收入。你收入多了，去掉成本，那么就赚钱多了。这个很容易理解吧？

大家抱怨铁路职工服务态度差，人家辛辛苦苦，收入那么低，你想态度好，做梦吧。所以要解决这个问题，一个办法，加工资。

大家明白了？高铁要赚钱，你的票价就要上去。所以那些骂高铁亏钱，又同时骂高铁票价高的人，要么是白痴，要么就是枪手。

也有人说，高铁可以效率好一点嘛。我来个私有化，把冗员给裁掉。剩下的人，精明强干，效率高了，服务态度好了，而且人少了，工资可以提高嘛。

可是想一想，高层的工资上天了（因为人家管理有方），下面裁掉的工人，去哪？不管是拿救济，还是政府帮助解决转行，这个钱哪里来？还不是全民负责。又是我这边进自己口袋，你那么全民付账的路子。

所以说，凡是搞客运的公共交通，都是不应该赚钱的。因为你提供的是给全民的服务。

而要保证票价低，又要让服务周到，就是说铁路职工们的工资水平合理，就是和你要让市民们吃低价的粮食，又要让农民们有合理的收入一样，这个就需要政府的补贴。

这种补贴有好多种，比如说高铁带动很多地价上来了，那么地产增值税收要搞起来，其中的部分，进高铁成本。比如说高铁通过了一些城市的地方，那么这些地方的生意红火了，那么销售税中的一部分也是去高铁成本。诸如此类的东西。

铁路真正赚钱的地方，是在于货运。那是不需要太多服务的，只要把货物往车厢里堆好就是了。而客运对一个国家的贡献太大，如果只是以高铁自身是否赚钱来考虑，你怎么不考虑一下公安和消防，是不是赚钱？这些都是政府的公共服务，是国民们理所应当享受到公共产品。

