# -*- org -*-

# Time-stamp: <2011-09-14 12:55:18 Wednesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:3

#+STARTUP: indent

#+TITLE: 井底望天的其它

#+AUTHOR: 井底望天

#+SETUPFILE:~/dea/templates/level-0.org



** 还是让人讨厌
(2011-09-13 15:37:00)


记得我曾经说过，认识不少体制内的人物，包括海子里面的人物，常常是自己占尽了体制里的好处，但是成天又是攻击和贬低体制的最强有力的声音。老是鼓噪这也腐败，那也黑暗。可是一旦真正要动体制的方案出来，这些人又是跳得最高的。

比如说一方面说，我们你政府敢裁？你不知维稳任务多重。呵呵，中国基层大部分的稳定问题，不就是你们这帮官吏折腾出来的？而且还恐吓，裁了我们这帮人，就和黑社会合流，看你这么应付。

很简单，问一问薄熙来和王立军怎么应付的。不就是打翻了文强，你黑社会就烟消云散了。当年广西和贵州还有十万大山的土匪呢，不是一样给剿灭了。

国企改革的时候，3千万工人下岗了。有一段时间，农村问题调查出书的时候，农民的日子也够惨的。今天工人和农民的生活都稳定了，就是你这帮贪官污吏还在搞事情。真裁了你，还怕你造反呢！我倒是见过曾经是高官的人，出来混世界，混得一文不名。还以为真忽悠一下老百姓，就跟你跑了。

其实这些官吏，之所以横行霸道，鱼肉乡民，不就是穿着一副国家罗汉的马甲而已。靠的是啥，就是出了乱子，要让人家武警来救命那种。真要是把国家干部的皮给你扒下来了，还想搞黑社会，呵呵。怕的是以前欺压的老百姓就拿你开涮了。

一说基层官吏腐败，就有人马上高喊上梁不正下梁歪，最反动在主席台之内的口号。当年清朝嘉庆搞改革，整理乾隆留下的腐败官僚系统，可是基本上从阁员到总督都是给换掉了。可是一动到地下，马上就有人喊没路可走，要造反的威胁出来了。

*减轻财政负担，压缩官僚体系，是今后全世界的一个趋势。* 你的选择，要么是在经济发展还不错的情况下搞，要么是在经济停滞的情况下搞。如何将财政支出的规模控制下来，从而减少对社会其他阶层的盘剥，让经济发展的好处，真正落到那些干事的人的身上，而不是政府庞大体系里面的寄生虫那里，是保证长治久安的唯一路子。

*把社会管理扁平化、政府行政能力提高、中央适当集权、削弱诸侯经济、建立国内统一市场、地方政府向公共品提供者角色转化，都有赖于行政体制改革的实行。*

而中国现有的中央和地方税收比例对半，显然太低。应该学习美国联邦政府的比重是75%，然后把事权集中，从而建立起全国统一的社会安保体系和全民医疗体系。

在民生方面，只要做到两件事情，一个是五年收入倍增计划，另一个是廉租房。

而在政府体制方面，如何精简机构，把财政这个账做好。然后在基层，如何发展农村乡村一级组织建设，和城市小区一级组织建设，从而在家庭和国家之间，这个小共同体和大共同中间，将来一个中共同体，并好好搞好文化建设，把共同体的价值上面的文化认同，用来做到社区（乡村）自助，邻里守望等等集体公共服务，来平衡货币至上、市场冲击、个人为主、消费盛行，对集体生存价值的冲击。

** 继续令人讨厌

(2011-09-12 12:27:01)

发觉这几天被和谐掉的文章，大概是2010年4月一篇谈打压房价的短评和另一篇四面楚歌里面东亚经济作茧自缚其中的某一篇。打压房价那篇里面，说到如果不好好控制房价，这一届政府在2012年全身而退，下届到时候就没有调控的工具，就只要跳脚的路子了。当然也提到，如果你房子这么容易发财，鬼才给你好好去做实业。

从这个角度来讲，转载本嘉明老弟的外贸文章，其实是可以看到这个现象的。不记得什么时候，曾经和忙总聊天，共识是2011年年尾，可能看到外贸行业的一些惨状。看来这种担忧，不无道理。真正要担心的，当然不是外贸业的老板们如何如何，而是如何实现这些相关行业的农民工的就业转型。如果今天规划的农村水利资金可以到位，也许可以解决一些问题。

而减轻对外贸的依赖，就是开发内贸。所以又转载了忙总的诸侯经济篇。 *要打破诸侯经济，还是要从政府行政改革入手，这个难关攻不破，内贸就无法起来* 。

在2008年，我是支持4万亿经济刺激的。不是说没有考虑到通货膨胀压力，而是因为就业问题，是中国发展的重中之重，其他的问题，都必须在这个问题解决之后的前提之下，才可以考虑。吃药就会有副作用，但是不吃药，你连副作用的机会都没有。看一下奥巴马迟来3年的就业刺激计划，就明白了。

但是在支持刺激计划的同时，我也说过，不要以为那个计划是一老[劳]永逸，以为可以自己下一帖补药，然后等着美国和欧洲缓过来了，自己就容易对付了。当时我的看法是也许人家完全恢复不过了，就迫使中国必须靠自己的内部自我循环。

这样的话，2008年的刺激计划，你只能寄望于解决3年的问题。那些刺激，只不过为中国下一步发展，打下基础，而真正的后继手段，是要解决 *民企和中小企在内贸中的融资成本和营运成本* 。

融资成本解决不了，你要控制通胀预期的时候，收紧了银根，就把人家中小企逼上了民间的高利贷。运营成本，就是你各种市场割据，物流关卡，诸如此类的东东，就把人家中小企给搞得死去活来。

看来这方面问题并没有得到很好的改进，国务院的相关人士，考试吃了零蛋。

继续前面的话题，那就是地区一级政府机构取消。最近的一个实例，就是安徽撤销了巢湖地区市的一个举动。

在安徽，比较重要的城市有三个。第一个当然是合肥，省会吗，各种优势都占了不少。另外两个一个是马鞍山，是以钢铁行业为龙头。一个是芜湖，记得以前卷烟是大头，现在出了一个奇瑞，汽车行业成了龙头。

安徽现在发展沿江一带，有一个思路，那就是芜湖和马鞍山的同城化。当然以前马鞍山比较有兴趣的是和南京的同城化。

那么巢湖地级市，本来下面有4个县，分别是庐江、含山、和县和无为，现在就是原地级市所在地居巢区改为县级市，省直管，暂时合肥代管。然后庐江归合肥，无为和和县的沈港镇（这个镇卡住芜湖长江大桥咽喉）归芜湖，含山和和县的其他部分归马鞍山。

有读者问过为啥不把人家地级市做大，把下面的县城改为区？其实很简单，地级市本身就缺乏足够的经济实力，是无法带动其他县城发展的。而安徽的这个行动，其实就是用合肥、芜湖和马鞍山三强来解决一个地区的问题。肯定比巢湖市的能量要大。

这种办法，你可以说是给大中城市圈地。但是毕竟大中城市的人才，确实比较强，如果能够把这些地方的城市化给解决了，圈也不是问题。你上海不是发展腹地不够吗？去圈人家江苏和浙江的地，人家也不一定卖你账，而且还有藩镇做大的嫌疑。你可以去皖南圈嘛，把宣城、池州、铜陵和安庆搞起来。或者去赣北，把景德镇、上饶和鹰潭搞起来嘛。

其实平心而论，中西部地方，由于不少人才，跑到了大都市里面，导致了这些地方的矮子里面的将军，就在政府体制内混吃等死。裁减政府编制，还可以把这些人才赶进市场，由此来带动当地的经济发展。

一个国家最重要的就是财政收支的可持续性，现在美国和欧洲的大部分国家，都面临着这个财政紧缩的问题。中国现在的经济增长速度还可以，因此财政中挤出来的人，还可以被社会所吸收。你要是到了美国和欧洲的无增长率的时候，财政出现问题，那时候要想挤压出去，你就只有做梦了。

千万不要把问题向下一任推。用英文说，就是 *kick the can down the road* 。这样的话，明清两朝出现的衰亡历史，就要重演。不要等到万不得已，才出张居正。


** 令人讨厌的井底望天

(2011-09-11 16:03:38)


中秋节，本来应该说点应景的话，不过发现我这个井底望天，其实是挺令人讨厌的。

前面有读者，问了一句，关于为啥要撤销地级市的问题，这里就大致回答一下。

中国古代的政治结构，从周朝开始的时候（因为具体夏和商如何，不是确定的），是周王城（镐京，就是大概今天的西安附近）和陪都（今天洛阳附近）算是首都。然后下面的结构是诸侯国和邑。从西周到春秋大致如此。

然后到了战国，就兼并成了7个大国。

从今天的角度来看，战国的7个大国，颇有点像现在的省。春秋和之前的国，颇像现在的地区，就是所谓地级市，而邑大概相当于县城。

秦始皇统一中国之后，政治结构，除了中央政府，下面是两级政府，就是郡和县。其实郡，也就是今天的地区这样规模。后来经过多次变革，要么就是州和县，要么就是郡和县，大部分时间是两级政府。

在金朝的时候，搞了一个临时的“行中书省”机构，在元朝忽必烈那里，就固定成为了行省，后来就发展成现在的省。

这个时候，政府的三级行政结构，就固定下来了。

看以前的戏，大家都记得县官新官上任，就是带着个师爷和几个手下，就上任了。所以当时的县委班子是不大的。

这种模式，不好之处，就是对县城以下的社会，缺乏动用和组织能力。

那么在超级组织能力为特点的共产党的主导下，中国国家政府组织算是头一次下了镇、乡和村。这样的话，加上中央一级，你就有中央、省、地区（市）、县、镇、乡和村这样的七级组织。以前是公社、大队和小队，但是基本经济核算单位，其实是到了大队。

这么多级别下来，你动用能力上去了，但是官员队伍就大了，国家财政负担就重了，那么老百姓养这些官员的压力就大了。所以要走出这个困局，就必须裁减官员和精兵简政。

其实刚解放之后，我们还有一个大区，就是按照自然地理特征，整个中国分成东北、华北、西北、华中、华东和西南6个区。后来搞了一个 *5马进京* ，就把这些大藩镇给削了。
考虑到互联网、高速铁路等等工具的出现，社会管理偏平化是一个大趋势，那么压缩官僚层级，是一个必须走的路子。

一个就是中央必须以身做则，把各种部委，好好的压缩一下。其实中国大部分时候，中央政府主要就是六个大部嘛。考虑到中央每个部门，都是一杆子倒底，有对应的体系在各级政府，这样一削减，那么下面也裁掉不少人。

第二个就是把底下的环节，比如说镇、乡和村都给撤掉。下面搞乡民和村民自治，然后派一个小的镇公所就行了。

第三个就是中间一层，把地区给撤掉。这个就是省管县。当然工业化和城市化，带动了城市的大发展。这样的话，把一些县城取消，变成大城市的一个区，都是一个法子。

那么这样的话，省的责任过重，规模太大，其实就要推恩散省，将来把各个省一级单位，都搞成重庆市那样大的规模，就差不多了。

我之所以令人讨厌，就是在不适当的时候，说人家有些人不愿意听的话。比如1988年，我独排众议，反对激进的价格改革。最近看了当年在位的某人写的回忆录，居然还觉得价改搞得对，呵呵。后来，在沿海贸易开始红火，我就强调要搞西部开发，结果这一个过程，落后了20年，搞得今天的西部局势不稳。

而在朱丞相时代，人家要搞机构改革，削减政府官员，当时我是坚决反对。当年的工人下岗，那么厉害，你给人送李自成？当时是应该稳定公务员队伍。

那么今天，其实是应该对官员队伍开刀了。有人会问，现在你让人家官员下去，人家会不会造反？

答案是不会。很简单，这30年的经济发展，大多数官员都捞得脑满肠肥。这个时候，让人家下去了，大不了揣着银子，落得快活。20年前，人家也是没有多少油水，自然和你拼命。人嘛，不逼上绝路，也不会跟你急。

第二个，就是现在的官民对立，你真以为那个官，可以号召屁民们起来？

刚刚发现以前很久的一些博文，本来人畜无害，被人给和谐了。看来有些话，让有些人刺耳啊，呵呵。



** 经济形势
(2011-09-09 16:49:31)


中国刚出来的CPI数字稍微有回冷趋势，但是压力还是不小，需要这几个月的继续冷却。

但是光靠中国自己还是不行。欧洲看起来会在主权债务危机里面继续挣扎，搞得欧元会不会崩溃，都成了大家关注的问题。

最近德国的最高法院判决，现在德国政府参与的希腊解救运动是没有违反德国宪法。但是将来德国政府要想行动，必须得到国会的同意。

这个就是要绑住德国政府的手脚。那么对欧元区是什么影响？

在现在的欧元区之内，其实有一个小欧洲。就是我提过的7国欧洲--德国、法国、荷兰、比利时、瑞士、卢森堡和意大利。

其实这几个国家的版图加在一起，就差不多是1812年以前，拿破仑时代和之前的法兰西帝国。

瑞士是有自己独立货币瑞士法郎，似乎就像靠着人民币身边的港币一样。

如果欧盟解体，或者是欧元区搞不定，那么退而求其次，就是要进入这个小欧洲。

有英美人士，劝说德国退出欧元区（比如金融时报就大声鼓噪了一下），要搞北欧元和南欧元，其实是想这里面的德国、荷兰和瑞士，与法国、意大利等做一个南北切割。这样下来，只要德国和法国不搞在一起，那就是美国和英国的大利了。

当然人家也没有那么傻，被你忽悠。但是要保住小欧元区，就一定要保住意大利。而现在意大利，就仿佛是当年朝鲜战场上的五圣山，而从希腊、葡萄牙到西班牙，就是寸土必守的上甘岭了。

德国也不是没有好消息的。其中之一，就是俄罗斯从北流来的天然气开通了。大家可以一起问候波兰他妈妈了。

另一招数，就是欧洲内核出问题，大家就往北非招呼。最起码现在利比亚的形势，暂时向对法国利好的方向发展。

当然现在是小法飞刀已经连连飞向了美国、英国、中国和俄罗斯，很难说这些刀子不会长了腿，自己又转悠回来，以其人之道，还治其身。

美国的情况，就是奥巴马向国会喊话，要搞另一波刺激，就是用4470亿美元，来刺激经济。

本来共和党的算盘，就是开始选举经济，通过国债上限的操作，导致政府支出减少，而迫使经济萎缩，从而为2012年白宫换位奠定胜局。

所以这次奥巴马的就业计划，被人不断开刀，最后能剩下多少，鬼才知道。

而另一个可以放水的水龙头，就是美联储局。最近共和党总统候选人，开始威胁联储局主席伯南克。先是派里说，伯南克再印钱，就是犯了叛国罪。然后，罗莫尼也说，他如果选上总统，就会炒伯南克的鱿鱼。

金里奇就更爽，说是老子明天就想炒掉伯南克。

而美元会否泛滥的斗争，仍在继续。而这个对中国通货膨胀的压力，是一大因素。当然另一大因素，是中国自己可不可以把贷款增长看管好。

记得有一次周末晚上开车的时候，看到一个地方工地上灯火通明。原来是一家红火的太阳能公司，赶紧建造新办公楼呢。后来有一次堵车很厉害，是因为奥巴马到这个公司参观，为他们背书。

今天看到这家公司倒闭了，竞争不过中国的太阳能公司。
