# -*- org -*-

# Time-stamp: <2011-08-23 15:20:12 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 时事和时局补充


[2011-08-09 04:56:47]

先说一下不幸丧生的美军海豹队。这次的海豹队员，不是一般的海豹队员，而是属于海豹第六队。这个第六队，通常是选择海豹队员里面最精华的人员，因此算是精英中的精英。

美国在反恐战争中，有三只秘密队伍，除了 *海豹第六队* 之外，就是 *陆军的三角洲* ，和 *中情局的特别行动队* 。而中情局的特别行动队，都是从海豹队员里面招募。而陆军三角洲，则是从陆军特种部队游骑兵里面的精华选取。

因为这支队伍，是属于高级机密，其行动和人员组成都是保密的。所以倒底这次牺牲的战士，有没有本拉登行动里面的人，外界很难知道。而这次损失，会极大地鼓舞塔利班的士气，也会打击美军的士气。

如果死的人，还是同一批人，那么对士气的影响更大，因此不管真相如何，官方一定要否定的了。

另外就是对标普的降级，今天导致了美股的大幅下跌。奥巴马出来喊话，说是不管什么人评级，美国国债都是三个A，永远都是3个A。而且引用巴菲特的话，说俺们美国应该是4个A才对。

也有不少人评论，说标普早已经没啥信用了。而且按照美国新银行法的规定，你不需要根据评级机构的评级来决定资金的储备量，只要自己内部评估就行了。当然最好就是美联储宣布，大家不要用这个标准，可以继续按照持有美国国债依照3个A的法子就行了。

其实这些解释，都没有搞清楚，这个事件的真实含义。

*当一个主权国家发行货币，其货币是代表了一种负债。就是你给我一个货币，我可以兑换回来我需要的商品。如果你没有对应的商品来支撑这个货币，那么货币就会发毛了，就是说不值钱了。*

当年美国在没有独立之前，其中最红火的贸易，就是向印第安人收购毛皮，然后转卖到欧洲。可是当时国际贸易之间用的金子，不被印第安人认可。印第安人认可的货币，是串起来的珍珠。所以大家必须先去买珍珠，才可以去印第安人那里换毛皮。

后来在美国南北内战期间，为了打仗，林肯大幅度发现债券。那时候，如果政府欠了你的钱，就付绿票子给你，但是政府来收你的税，就要收黄金。于是在纽约就出现了美元-黄金炒卖场所。因为 *美元的命运，和联邦军队的战绩有关，所以这个时候大家看到兑换率波动，就知道联邦军队的战况。* 那时候炒家们为了最快的掌握信息，雇用的情报人员，比林肯自己要早知道战场实况。当然，这个不排除有人赌了一个结果，就试图买通战场上的指挥官，有意打败仗。 *这个时候的华尔街，是被林肯骂为李将军的第五纵队。*

*对任何货币来说，你必须有一个锚，就是拿来回笼货币，行使你的负债责任的一个工具。* 在布雷顿协定下，西方国家的货币，全部以国际储蓄货币美元为基础，而美元以黄金为基础。

你拿了美元，跑来结算，我美联储就以黄金来回收发行的美元。这个法子实行了不少年，最后就是美国在越战中发行了太多的票子，而通过二战积累的黄金不够了， *于是美国国债隆重登场* 。

其实曾经想过用纸黄金的概念，就是你拿美元来，我给你一个纸片，上面书写“黄金五万两”。你拿回去，不能兑换。这当然没法行得通了。于是美国又眉头一皱，计上心来。你看看，全世界的安全，都是我保证的嘛！这样吧，你们手上的美元，自己消掉一部分，就算是交了保险费了。

这个就是 *美国国债发行和美元定期贬值制度* 。这样的话，你拿美元来结算，我就给你美国国债。而每次当美元发行过量，导致你手头美元过多，那么就采取美元贬值，同时促进美国货出口给你，来回收你的美元。

*由于美国制造业逐渐萎缩，而不萎缩的部分，比如说高科技和军工这一块，又不对中国开放，而中国手头又掌握了最多的海外美元，那么这个制度现在也面临一个困局。*

那就是说， *整个美元为基础的国际金融体系，以及建立在上面的贸易和金融衍生品市场，都是根基于美国国债。*

*可是美国国债和黄金结算不同在于，黄金你给了就给了，而美元国债确必须支付利息。而这个利息必需来源于经济增长带来的税收增长。而一旦国债数量过大，而经济增长率过低，那么国债利息很可能就会导致税收不足支付，这样的话，体系就没有办法运作下去。*

而标普的动作，其实是大家一直就有共识，总有一天会发生。只不过这一天终于来到的时候，很多人不适应而已。 *现在出现的情况，就是国债的零风险信誉受到挑战，那么以这个为基础建构的整个大厦，就会出现不稳定局面。*

*把国债上升的速度，和财政赤字的削减挂钩，其实是变相为国债封顶。那么美国经济赖以扩张的发动机被人熄火，将面临一个比较麻烦的停滞局面。*

这个时候，世界经济需要的是给全球金融体系增加一根柱子，因为你的大柱子美元，和小柱子欧元，都风雨飘摇。
