# -*- org -*-

# Time-stamp: <2011-08-23 15:46:44 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 最近的一点思考（2）


[2011-08-03 16:29:56]


其实现在看来，北非移民的方向，主要是以法国为主。

因为北非的不少国家，是旧法国殖民地，也是法语流行的国家，这些地方的移民，自然是以法国为主。虽然这次挪威出来砍人的白人右派哥们，认为社会主义对欧洲的危害太大，强调多元文化已经侵蚀了基督教，所以希望欧洲能够恢复天主教传统，重振当年的十字军的斗志，针对穆斯林的侵袭，采取另一场圣战。

*当然当年十字军的圣战，从大的战略意义上来讲，是一场保卫战，应对东罗马帝国，被塞尔柱突厥占领。但是从战术上来讲，是一场进攻战，是以今天的法国和德国等地方为主的基督徒向东边征讨，而且最后是屡战屡败，在技术先进和战力优势的穆斯林军队的打击下，是一败涂地。*

对欧洲的极端右翼来说，今天的对抗，不论是战略和战术上，都是一次背水之战，因为觉得给人家杀到老家来了。这样的情绪，虽然没有出现在欧洲的主流媒体上，但是从瑞士的制止建造尖塔、法国的制止穆斯林女人戴面纱、还有瑞典的行为，都表达了民间的暗流汹涌。

不过今天的天主教徒们，似乎比起新教徒们，要更加软弱和温和。因此在短期内，看到的欧洲反穆斯林潮流，似乎不是针对北非的移民。倒是来自中东、以及巴基斯坦的移民队伍里面，倒是让欧洲人恐惧的情形更甚。

但是随着穆斯林人口在欧洲的比重坐大，比如说 *到了2050年的时候，穆斯林人口在欧洲的比例，估计会达到25%，那么在文化上和宗教上，都可以和欧洲文明不分伯仲抗衡的内部异端文化* ，你自己的文明，因为缺乏宽容的内涵，无法消化别人的文化，那么就很显然地会最终走向文化冲突。

*在美国的情形，就是旧人群的新教文化，和新人群的天主教文化的和谐问题。* 大家都知道 *美国历来出任总统，要求的是WASP男人。WASP，就是White白人，Anglo-Saxon就是盎格鲁-撒克逊、Protestant就是新教徒。*

迄今为止，所有的美国总统，都是来自于欧洲北方白人—英国、德国、荷兰和爱尔兰的血统。唯一不合乎这个标准的，一个是肯尼迪，是爱尔兰后裔的天主教徒，一个是奥巴马，是一半爱尔兰后裔的混血儿。

而今天美国的白人仍然处于增长状态，因为靠了南部的红脖子们死命生孩子。但是这个趋势会在2040年停止， *使得白人占美国总人口的比例，从1960年代的85%（今天是67%），下降到2050年的47%。而拉美裔人口，会从今天的16%增长到29%。非洲裔则保持不变为13%，而亚裔会从5%增加到9%。*

可以想象的是，在这样的一个人口布局下，拉美裔的政治力量会变得相当强大。而作为美国社会同化和维系大家一体的意识形态，就是美国特有的华盛顿共识体系，是建立在作为个人的美国梦，就是说只要你个人奋斗，就一定会出人头地，和整个国家的经济强大地位，来保持各自不同宗教、种族、文化和民族的一致性。

有美国学者，把美国大致分为很多个不同的小社区种类，就是说其实现实上并没有一个一体的美国，而是由不同类型的人群社会自己安身立命，然后 *通过意识形态的体系，而链接在一起。*

那么当美国经济开始失去昔日的光辉，美国梦越来越艰难的大趋势，无法提高自身主流文化的宽容度，又无法有效地同化其他的文化，将成为美国社会的很大的挑战。

因为很简单， *当年的苏联帝国，就经历了中亚的穆斯林人口在生育率上的大幅度赶超，然后在1989年左右，俄罗斯族的人口比例，下降低于50%，然后引发了苏联帝国的分崩离析。*

当年能够把苏联境内的各民族和各宗教团体联系在一起，靠的是共产主义意识形态。而当这个基点，受到了撼动，那么整个国家的链接，就折断了。

这个过程，我在以前的系列里面提到过，并用了一个名词，叫做“ *内部殖民化* ”。这个名词，可以比较明显地描绘目前在美国和欧洲出现的情况，其实包括德国总理梅克尔等人在内，都发表了关于欧洲多元文化的努力算是彻底失败了。

当然，并不是其他的国家，就会比美国和欧洲好多少。对俄罗斯来讲，这个也是同样的问题，那就是 *俄罗斯面临来自于中亚国家的穆斯林人口，向俄罗斯北迁的问题。* 而现在因为美国在中亚的动兵，还难以看出这些人群迁移之后，来自南亚，比如说巴基斯坦的人口，会不会北上，填补这些人口丧失的真空。

至于 *印度次大陆，可以看到的，其实有同样的北移的趋势。* 在西北部，可以看到印度教徒，大规模向印度占领的克什米尔地区移民，在北部，可以看到同样的印度教徒去占据被印度非法吞并的锡金，和非法占领的中国藏南。而在局势不稳定的东北部，则可以看到来自于西孟加拉邦的印度教徒，和孟加拉国的穆斯林，向北部蚕食。

当然印度人口的北迁，会在气候暖化之后，印度次大陆因为水源紧缺，形成更大的压力。但是印度的最大障碍，是因为中国的关系，无法顺利地越过喜马拉雅山。这估计也是印度一直梦想着把西藏从中国分裂出去的一个主要原因。想象的话，一个独立的西藏，估计迟早都会成为印度的盘中餐。

而中国在几个北方大国里面的情形，在比烂中，相对要好一点。一个是中国的民族融合历史上做得比较好，比如说最难以同化的犹太民族，在中国是自己心甘情愿地给同化掉了。作为中华文化核心的 *儒法家* （我自己搞出来的一个新词，来 *描绘道德修为和法规行为的内儒外法的儒法一体化* ），是非常世俗的意识形态体系，在魏晋南北朝时代，成功地融合了佛教和道家，算是达到了三位一体，那么今天要做到的，就是五星红旗，迎风飘扬，就是要 *以儒法家为那颗大星星，然后让佛教（包括大乘的显宗和密宗）、道教（包括各种地方教种）、伊斯兰教和基督教（包括犹太教和天主教）这四颗小星星，大家和谐的团结在一起。*
