# -*- org -*-

# Time-stamp: <2011-08-29 11:30:40 Monday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 龙之声国际观察 第十七期（2011.08.26）

各位朋友们，在第一期国观中，我们曾说过 *国际局势犹如不止的流水，觅不到开始，也寻不到结束* 。从4月25日开始的龙之声国际观察已经走过了近半年的时间，如果大家还记得的话，当时我们是以“世界是怎么样的一个局”来为大家开始分析这个世界的时事新闻的，同步走来的还有北非中东之乱。流水一样的国际局势，却从来不是平静的，有时暗流汹涌，有时巨浪涛天。从3月19日北约对利比亚的轰炸开始到本月的 21日，苦苦支撑了五个月之久的卡扎菲和利比亚局势，突然以让人眼花缭乱的速度在变化着，各方势力以各种方式积极参与了这一年度最大剧目的表演，为让大家更好的了解这个剧本的演绎，我们的目光仍然先从新闻开始。

*【新闻链接】利比亚反对派逼宫城下卡扎菲身困危局*  综合新华社驻外记者报道：持续5个多月的利比亚战事21日进入关键阶段。反对派武装在北约的军事支援下已经攻至首都的黎波里，处境岌岌可危的利比亚领导人卡扎菲则呼吁支持者同仇敌忾，击败北约和反对派的入侵。


*【新闻链接】美欧欲推动联合国制裁22名叙利亚高官* 美国之音网站报道，23日西方国家发布了一份针对叙利亚总统巴沙尔·阿萨德及其家族的制裁草案，意图制止正在叙利亚上演的镇压反对者行为。

  

美国和欧盟代表团提议今早表决这份草案，但拥有否决权的俄罗斯并不支持这份草案，俄罗斯驻联合国大使丘尔金称现在不是惩罚叙利亚政府的时候。


除了巴沙尔之外，草案还要求冻结包括巴沙尔的哥哥马赫以及在镇压抗议活动中起到重要作用的第四装甲师指挥官等在内的22位核心人物的资产。

　　

巴沙尔的表兄拉米·马克鲁夫掌握着叙利亚最大的移动电话集团，以及一些其他暴利行业。这位商业大亨同样被列入制裁名单，他已经成了反对者愤怒的靶子。决议将同时制裁一些在资金上支持政府的公司。

据悉，制裁的具体措施包括加强武器禁运、禁止除了巴沙尔及其弟弟之外的21人出国等。此次制裁草案的提出是对叙利亚政府连续5个月对示威进行镇压的反应。联合国称目前已有约2200名市民死亡。

23日，巴沙尔的反对者组成“全国委员会”并声称要推翻巴沙尔政权。与此同时，美国驻叙利亚大使罗伯特·福特出人意料地访问了叙利亚城镇Jassem，在那里已经有一些抗议者丧生。

美国、欧盟和其他西方国家已经明确表示巴沙尔必须下台。这位叙利亚领导人将反对者称为持械匪帮和恐怖分子，并以此为镇压行为辩护。他同时声称西方国家的批评并不会对自己产生影响。


*【新闻链接】以色列军方连续空袭加沙地区停火协议成空文* 以色列军方表示，他们的战机24日对加沙地区实施了打击，针对目标是两名武装人员。据称，这两名武装人员此前曾向以色列南部地区发射迫击炮。

　　
以色列军方说这两名武装分子在发动炮击后不久即被以方击中。目前还没有来自加沙方面的伤亡报告。

　　
据哈马斯安全官员称，在24日早些时候的另一场空袭中，以色列战机对加沙地带进行轰炸，一名巴勒斯坦伊斯兰圣战组织(杰哈德)军事派别的领导人死亡。

　　
以色列军方表示这名杰哈德组织成员曾向加沙地区走私武器，并参与了在西奈半岛的军事行动。

上周，8名以色列人在埃及边界遭袭击死亡。随后，以军战机对加沙地带实施了多次空袭。巴勒斯坦武装组织也向以色列南部发射了多枚火箭弹。尽管加沙武装组织21日称与以色列达成停火，但是袭击事件仍不断发生。


*【时事解读】* 当下利的局势已经发生了明显的变化，那么顺着时间的节点，我们继续帮大家先把近期有关利比亚的重要新闻汇总一下，以利大家更好的看明白这个局面的演化过程：

8月11日：北约称卡扎菲已“无力进攻”

8月16日：利反对派称“胜利3周内到来”

8月19日：中国援助利反对派5000万

8月20日：利比亚前总理倒戈

8月21日：利比亚首都爆发激战

8月22日：利比亚反对派涌入的黎波里

8月22日：利比亚驻多国使馆宣布改旗易帜

8月23日：利反对派攻占阿齐齐亚兵营

8月24日：利比亚反对派表示，新政权将遵守卡扎菲政府签署的石油协议，这其中也包括中国公司签署的协议。从利比亚近期的局势演化上以及几个月来的经历，不断印证着观察员曾在前期中所做的分析和给出的观点总结，现在我们有必要把它重新让大家再看一下：

1、利比亚问题不是一个单纯的社会动荡或者说是仅仅是内战的问题。利比亚问题是世界性大变局的一个缩影，是涵盖资源产地和黄金水道上所有动乱的一个组成部分。只不过因为其地理原因和历史原因，才成为了斗争的一个节点。

2、利比亚问题，必然是一个长期化的问题，在战事开始的时候，我们就分析过，利比亚问题是不可能短时间就解决的。在龙之声观察第一期，龙之声观察员给出这样的结论： *世界主要势力在中东非洲的角力没有分出胜负之前，中东北非等地的动乱有长期化的趋势，这种趋势时间的长短、烈度的小大，在于各方势力达成妥协的程度。*

3、要想解决利比亚的问题，单纯依靠欧盟的力量根本就做不到，志大才疏的法国，后发制人德国都不可能做到。欧盟是非常希望能够快速的解决利比亚的问题，但是因自身实力的原因，这样的希望注定是不现实的。他们的选择只能是： *要想快速的解决利比亚问题，要么向美国妥协，要么向中俄寻求支持。除此以外，欧盟没有第三条路能够走通。*

4、 *利比亚问题一天不解决，欧元的警报一天就没有解除。在利比亚问题的僵持中，欧元也继续的在受煎熬。*

从前期的观点和近期局势的演化中，无一不说明了各方在对利形势上的相互搏奕和妥协。本期龙之声观察员首先提醒大家的是： *随着利比亚形势的变化，要注意由利比亚战争到叙利亚局势恶化的实际转变，这期间是有必然的关联的，甚至可以认为是欧美实际达成妥协的一种必然表现。* 而在龙之声第九期中，观察员也提到过，在利比亚，中国力量是不会无所作为的，中国是要入局利比亚的。那么随着16日中国对班加西人道主义物品援助的成行，加之俄罗斯转向已久，以及欧美两方就利叙问题上达成妥协的结局，自然就使反对派的力量突然以绝对性的优势，迅速包围并占领了的黎波里的大部分地区。当下的战斗虽仍然激烈，但可以预见的是，如果以色列所引用的军方消息属实的话，那么由 *英国SAS突击队* ， *法国2REP突击队* 和 *DELTA 部队* ， *DINOP突击队* ， *约旦的巷战专业部队* ， *王家特种部队* 等所实际参与的黎波里的攻坚战中，反对派的力量从当初的乌合之众，已经有了实质性的改变，理所当然的使卡扎菲政府力量突然处于绝对的劣势的地位上了。但卡扎菲当下也没有完全的失败，有理由相信，在后卡扎菲时代的利比亚，利比亚的局势是很难在短时间内稳定下来的，各方的势力仍然将在这个地方继续以各种形式进行搏奕，因为利国不论是卡的支持力量还是将走强部落化趋势，都表明了即使是反对派占领了的黎波里或是抓到了卡扎菲，都不代表就可以完全实际控制了利比亚全境。相反，各反对派之间的矛盾也许就会很快的暴发出来，前一时间内其联军司令的离奇死亡，或许可以说明点什么的。那么共同的目标被打倒后，内斗是否会加剧，海外势力会如何插手权利的争夺，都是未知的变数和有待继续关注的事情。


另一个方向上，从进入8月份开始，欧美媒体加大了对叙利亚政府的指责力度，并在利比亚反对派攻入的黎波里的第一时间，适时的做出大家似曾相识的决定，那就是对包括叙利亚总统巴沙尔在内的22名高官的制裁草案，并于联合国人权理事会第17次特别会议23日通过决议，决定向叙利亚派出独立国际调查团。虽然以俄罗斯代表团为主的反对力量明确的表明了反对，而中国外交部也在关键时候表时(示)自己的态度，反对外来势力施压叙利亚，但欧美合力已成，达成这样的一个结果是并不意外的事。早在几期之前龙之声观察员就曾提醒过有关方面： *叙利亚正在被实际推向混乱的境地。在叙利亚还没有乱之前，也门已经早都不稳定了。* 而从北非和红海沿岸国家的动荡的进一步加剧，将是一条必然的路线图。

当下的局势发展，与预测的一样，卡扎菲曾经的罪名和命运，正在越来越近向着巴沙尔的头上罩了过来。只不过前者是被欧洲人的利益主导的，后者却是美国利益者在主持了，从美国大使多次对叙利亚抗议地区的造访中，大家或许可以明确的感受到这一点。逼巴沙尔下台，以使伊朗失去其重要的盟友和战略纵深，并形成对俄罗斯安全威胁，实际控制黄金水道。正是在这种诱惑之下，使得越来越多的北非中东的关联国家逐渐陷入了剧烈的政局动荡中。当下叙利亚在带路之下如期的乱了，做为利益交换，正在按预想剧本如期进行的所谓的调查，调查团想来也会被预期的一样出视报告和提交制裁讨论。可是在这里，龙之声的观察员仍然强调以前观点： *如果到时候混乱的不仅仅是叙利亚怎么办？如果以色列这个中东钢钉被连根拔起，美国的中东政策无力应对广泛的汹涌澎湃的中东乱局从而导致美国的中东政策崩盘，那怎么办？*

在这一点看来以色列方面也是深有感受并万分紧张的，加沙方向射来的火箭弹，引发了以方的报复性抓捕与空中袭击，但当下看，双方尚处可控和理智的状态下。因为，从巴方来讲，即将到来的联合国关于其建国的表决才是至关重要的决定，所以就此时来说，与以方发生剧烈的冲突是不符合其利益的行为。但巴的建国梦是否成真，并不凭是他的力量所能主导的，外交努力之下，还要看各方在利益需要与制约手段的平衡间能否达成一致的交换。从这一点上说虽然当下巴方宣布已经有120个以上的国家同意巴方建国，但做为犹太力量代言人的美国的态度，仍将在巴方这次大考中，起到最关键的作用，而犹太力量又是与美国利益息息相关的，从这一点上说，巴方的诉求，虽然可能得到世界上非美势力的支持，但仍然是个困难重重的局面。而这一关键点上的任何变化都将会为美国的大中东重建计划，带来极其重要和深远的影响。从这一点上看，叙利亚也好，巴以也好，都是美国大中东战略的重要组成部分，独霸中东资源，以对伊形成进一步孤立，拿下对中东最后的一切非控区，进而达到操控世界能源和向非美国家转嫁危机创造最有利的局面。动荡叙利亚，黎巴嫩，也门等非美势力国家，不仅可能先期控制了通道更可以起到弱化中东非美国家的力量。保证美以战略后方的安全，才是达到最后对伊朗一击成功的保证。因而，虽然美国政府很想使巴以的局面得到稳定化，为此奥巴马不惜顶着巨大的压力抛出过支持巴建国的观点。但从后续的反应看，不论是美国国内的资本势力还是以国的政客，都对此进行了坚决的抵制，以至当初我们看到过以色列的领导人在美国对白宫政府的强烈不满和指责，那脸色之难看，让人感觉到了这个世界老大原来在资本面前是如此的虚弱。这样的一种大背景下，白宫指望靠外交努力以达到巴以的稳定，可以说是一厢情愿之举了，更何况这世界上还有非美力量，要在其中起到他们该起的作用。

中东政局的变化，虽然是以美国力量为主导的，但同样不可忽视是其他几方的存在，特别是俄罗斯不论出于安全角度也好，还是传统势力传承也好，都决定了他必然是制裁叙利亚的带头反对方，关于这一点，在以后的龙之声观察中，我们将就俄罗斯的心态做进一步的详尽分析。那么当下还有一个中东的重要非美力量却是不得不提的，那就是伊朗，做为当下最大的伊斯兰反美势力，美国在中东地区最大的障碍，伊朗的一举一动都自然吸引全世界的目光。利比亚的局势变化后，伊方先是公判了两名美国人的罪并宣布其纳坦兹铀浓缩工厂传言“中毒”的离心机开始了正常工作，稍后的23日内贾德公布了一种由潜艇发射的短程导弹和一种鱼雷系统。显然一系列举动都是有针对性的，表明了他对叙利亚局势是相当不安的，相信随着利比亚和叙利亚局势的变化，伊朗及相关的土耳其甚至是埃及方向，都必将针对以色列这一中东的美国软胁有进一步的施压行为，还有早前已经表明会有所作为的中国力量和必然不甘心退出的俄罗斯的制约。正如前面说到的很可能发生的中东乱局中，美国是否有能力来保证在面对这种汹涌澎湃的中东乱局中而不使美国的中东政策崩盘，确实是个问题了。这里龙之声观察员要提醒的是： *中东是否破局的关键，不仅取决于美国政府的战略决策，还与其他非美势力的反抗意志和决心是息息相关的。长远和短视，眼前利益还是长远利益，是被各个击破还是联合对抗，都考验着各势力领导人的智慧和能力。因为美国的战略是全球化的战略，并不是就某一点或某一面的突击行为。*

*在这里，龙之声观察员想强调的是，有充分证据表明，利比亚战争，在欧美特种部队全面参与的情况下，已经接近尾声，但随战争的结束，欧美间还有许多工作要做，最起码的分赃协议如何签订，就是个大难点。如果解决不了这个问题，那么，利比亚战争伊拉克化，阿富汗化，也许就在眼前。而原利比亚反对派别，在战争顺利结束后，政权的能否得到保证，还要照顾各方利益，否则，这个门派复杂且被各个势力严重渗透的“临时”政府想扶正都难！*

*再谈法国总统突然来华的目的所在。* 有消息说，法方邀请中国参与利比亚的“重建”，而中方答应考虑。法国充分注意到这一点。在法国总统来华前，美副总统，这个职位虽在美国仅仅是个象征意义的，但在这个时候来华，说明华盛顿还是非常在乎中国的态度。无论是美将要推行的QE3，还是亚太地区的经济与安全，还是美的中东中亚利益，特别是利比亚问题，得到中国的理解，还是需要给出真金白银的。

利比亚战争，中国其实早就知道这个结果。在战事前夜，中国大规模的撤侨，在一周内将几万人撤出来，已经考虑到今天这个结果。五个月过去了，早就预料是这个结果的中国政府，也就早已经针对目前利比亚出现这个结果作出了相应的安排。因此，在利比亚战事之后，出现在伊拉克已经出现的那一幕，并不奇怪。

为进一步的说明这个问题，下面我们把目光看向全球经济方面，因为政治乱局当下还主要是为经济掠夺和危机转嫁来服务的，这方面可能会为我们带来更多的思考和答案。

*【新闻链接】默克尔拒发欧元债高盛唱衰欧币联盟* 德国总理默克尔近日再次强烈反对欧元区发行共同债券的构想,但财长朔伊布勒暗示对某种形式的财政联盟持开放态度。与此同时,知名投行高盛指出,欧洲现有的经济和货币联盟已经无法运转,欧元区需要有凝聚力以及有决定作用的领导力,德国必须决定它想要一个什么样的货币联盟。

*【新闻链接】德法倡导建立“欧元区经济政府”* 德国总理默克尔和法国总统萨科齐16日在巴黎会晤后表示，德法两国将共同倡导成立“欧元区经济政府”，协调成员国经济和财政政策。两国领导人还提出欧元区成员国实施财政平衡政策、开征金融交易税等几项建议，以加强欧元区经济治理，应对主权债务和经济增长危机。

分析人士认为，德法领导人会晤的提议为欧元区统一财政政策体系做出了铺垫，是欧洲一体化进程向前迈出的新一步。不过，此次会晤否决了扩大欧洲金融稳定机制和发行统一欧元债券的提议，缺乏应对欧债危机的实质性措施。

*【新闻链接】日本主权信用评级遭调降* 国际评级机构穆迪投资者服务公司24日宣布将日本国债评级从Aa2下调一档至Aa3，主要理由是该国财政赤字巨大以及债务负担不断增加。这是穆迪9年来首次下调日本主权信用评级。穆迪同时宣布，将日本国债评级展望定为“稳定”。日本主权信用等级被下调当天并没有引起投资市场波动，但分析人士普遍认为，日本国家债务危机远比美国严重，如果日本政府不能尽快采取财政重建政策，其未来经济发展堪忧。


*【新闻链接】美联储或推6000亿QE3* 8月24日,有媒体报道称,美联储的第三轮资产购买计划(QE3),规模可达5000亿-6000亿美元。


　　8月23日,美国财政部拍卖350亿美元2年期国债,利率为历史最低的0.22%。当天10年期国债收益率为2.15%,30年期国债收益率也在历史最低区间——3.46%-3.49%。尽管标准普尔8 月初调低了美国长期主权信用评级,债务危机扩散,但美债仍被视为动荡市况中的相对安全资产。美国国债收益率近期持续走低。

*【新闻链接】美国仍面临严峻的预算和经济挑战* 美国国会预算局２４日发布的最新报告预测，２０１１财年（２０１０年１０月至２０１１年９月）美国联邦政府财政赤字将逼近１．３万亿美元。在这份长达上百页的报告中，无党派的国会预算局指出，美联邦政府仍面临“严峻的预算和经济挑战”。

报告预测，２０１１财年美联邦政府财政赤字将达到１．２８４万亿美元，年度财政赤字占国内生产总值的比重将达８．５％，尽管略低于上一财年的８．９％，但仍远高于３％的国际警戒线标准，显示财政状况仍不容乐观。

*【时事解读】* 上期龙观察上，我们提出：因为美元与欧元不可能共生而无矛盾的原因，特别是今天流动性泛滥而导致美元与欧元矛盾进一步激化的情况下，如果能吃掉欧元，美国就获得了巨大的战略腾挪的空间，美元危机就得以化解。美国就不可能出现双底的衰退，美国不出现双底的衰退，全球就不会出现双底的衰退，尽管有的国家会“退”的很厉害，但是全球不会。所以美元对欧元的攻击不仅仅不会减弱，相反，还会加强。从现时的状态上看正是如此，不同与(于)政治上欧美之间的相互妥协，经济上的定向攻击却是准确而致命的，从南欧五猪的希腊开始到意大利，法国这样的关键性国家，或降级或维持，都有其不同的作用和目的性。而当下更是已经精确到开始评级欧洲的一些有影响力的银行系统，以穆迪为首的美国评级机构，正在利用其独一无二的话语权，对全球和重点对欧洲金融体进行着定点的轰炸攻击。

在欧洲的应对上，除看到欧洲央行到处贴创可贴以被动式治疗之外，还没有什么实际有效的应对手段。法德峰会本来被外界赋与了极高的希望，但从结果来看，虽然达成了一个乌托邦式的欧洲区经济政府预期，但却就更为实际的发行欧元区共同债券一事产生严重分歧，就更别说有具体到改善欧洲银行风险的举措了。欧洲区各国的不同心态于发展中的不平衡，特别在除德国强劲外的集体经济低迷状况，决定了他们很难就一些实际的问题达成一致的理解和支持。而对发展中国家不断加大的贸易产品进口壁垒，不仅不是疗疾之药，更是作茧自缚之举。正是这种背景下，才有了25日法国总理萨克奇的突访北京之举。挟利反对派攻入首都的有利时机，向中方示好，以求得到中国的实际经济帮助和政治支持，想来才是他此行的目的。但这里要提醒欧洲的是： *如果欧元区国家支持美国在中东的战略肃清行动，或许欧元区国家看来，中东之乱似乎是能将美国的注意力转移到欧洲之外的地方去了，这种思考方式却是无比的短视的。失去了中东影响力的欧洲，当中东的地中海中的核心中的核心国家都被美国所控制，欧洲就是能拿下利比亚，也只能是一个断了链条的欧洲噩梦，等待他的将是更加孤立化，长远的看美国正是想借欧洲之力来为美国最终孤立乃至打倒欧元开辟道路。所以从这一点上看如果理智和正确的对待中东之乱，欧洲是有机会的。而一旦为眼前利益所左右，等待他的将是一场和美国一样再输不起的赌局。*


*同样在上期的龙之声观察中，观察员提到了欧洲区想要解决危机的两条有用途径：* 第一，迅速的解决利比亚的战事，收拢被自己敞开的门户。第二、迅速的认清形势，不要再抱有幻想，要果断的向中国妥协，让利给中国，寻求中国支持。关于这两个方面，上期中有比较详细的论述，现在利比亚的形势虽在向欧洲有利方向转化，萨克奇也适时的突访了中国，但同样并不意味着欧洲的金融危机就可能得到实质的解决，因为就后一个方面来说，还要取决于欧洲的决心态度以及是否会向中国实际让利的结果。中国从长远的战略角度上自然会帮助欧洲，因为对中国而言，如果欧元区不存在了的话，美国就能集中力量对付中国了，这是一个非常浅显的道理。然而双方能否有条件合作的前提，就是互利互惠，而非单方面的付出，从这一点上看，在此次会见中胡总适时的提出希望欧洲能确保中方对欧投资安全是很恰当和重要的表态。

而关于日本的被降级和美国QE3的预测及美国经济体仍深陷危机的新闻，正如龙之声观察第十期中所写道： *全球一体化的结果，就是使世界局势有机地织成一张网，无论是在中东、非洲、欧洲还是亚洲，重要力量聚集的地方，资源聚集的地方，总能让人看到“恰好”的新闻。* 美国的评级机构，就像是这个机制中的裁判员一样的存在，同样是美经济霸权的需要和现实的实际反映，三家机构虽同样是裁判，但最近却是不同的命运，标普因对美国降级而被报复，穆迪却因为是在授意下的吹黑哨而混得风声水起。这件事说明了，裁判还是要听裁判委员会的指挥才行，做出的评判是一定要符合美国利益的。关于美国的债务状况和当下经济增长的停滞状态，几家评级机构自然心知肚明，但可以知道，却是不能乱评的，至于其他国家么，就没必要心慈手软了，在适当的时机适时的点燃他的危机之火就可以了，对欧洲，对日本莫不是如此。

*日本的债务问题* 之所以没有在希腊之前被引爆，是因为美国政府认为他还有利用的价值，那么此次被降级，可以看做是对日本政经界的一次警告性行为，在日本将要再次换相之际，这种警告是耐人寻味的，这里可做多方面的解读，对欧洲方向，敲山再震虎，能对日本降级，下一步就更能对欧洲的如意大利或其他国家进行下再评估，当然前提是欧洲国家还不合作，还不低头的妥协的情况下的再评估；另外，削弱世界上其他可投资的国家债券的影响力，对美国债券肯定是利好的，起码可以达到让中国的大量外储少一些去处；当然还有一个警告日本，实行QEN这样的宽松，只是我可以做的，而且这规模也是我来定的。我这个州官可以放火，但你也想点灯却是不行的，干预汇率和妄想也实行宽松的经济政策，不管你是否地震，都是要受到惩罚的行为。关于日本，近几期的龙之声观察栏目已经分析了很多，本期不做重复，只简单的讲下： *新的首相又要诞生了，五年六相的节目还在继续延续的发展，不论党派还是个人，谁对美国的利益有好处，谁就可能会成为最有份量的候选人，当下看，前原肯定是比较符合这一要求的，而拜登在中国表演后，第一时间登陆日本岛继续表演，一些日本媒体也很快提出让前原代表民主党参选的呼声，想来与此公的表演是不无关系的，这是从政治上的考量；而从经济上来说美国威逼日本的一个手段就是通过下调日本主权信用评级发出美国有可能引爆日本主权债务危机的信号，从而压迫日本朝着美日合作的方向发展。*

*再说日本面临的危险局面。* 因核泄露而获得喘气的日本，在经过半年的短暂“休闲”，偷安之后，以日本在亚洲的地位，美国人是需要日本在亚洲做些什么的。但是，因日本的核泄露，如果美在那个时候压迫太厉害，肯定会取得相反的效果，设想在日本困难之时，美压迫的太厉害，在日本国内酝酿出新一轮的反美情绪是非常现实的事。因此，美国人也“忍”了半年。

在美国副总统来华访问，估计美没有得到最想要的结果，而中国方面却表现的非常强硬，在债务问题，货币宽松问题，人民币国际化问题，中国的表现非常抢眼。这令美国感觉非常不快。

这个不快，首先表现在，在最短时间内出台了《中国军力报告》，看这个军力报告，估计国际上大的玩家，都看看标题，但有关人是理解这个“报告”出台的内涵，因此，有的“人”心神领会。

在这里龙之声观察员想强调的是， *在中国以“钟声”为作者连续多篇关于中国核心利益不容触犯的背景下，在亚洲还有多少国家敢于真的去面临民族灭顶之灾，去为美利益做炮灰！其次，就是美为日本的债权评级降级。这个降级来的太是时候了。这是压迫式的逼近日本，在亚洲，为美国必须要做些什么，否则，债务评级降级，只是第一步，下面还有第二步，第N步。*

而中国方面，早就预计到这个结果，于是，中国渔政船，在钓鱼岛周围，引来了日本的全面抗议！

而中国外交部的回答是：钓鱼岛周围领海，都是中国的。没有问题的余地。

再回头看日本面临的危险。如果日本政府，在面对与日本利益关联最大的两个国家，如果在两个国家达到一个大体的平衡，是日本政客必须要考虑的，必然要面对的。这两个国家，无论哪个国家，都可决定日本的生与死，万一失衡太严重，对日本来说，会出现比失去的二十年更危险的结果！其实，中国是在提醒日本，不要将路走绝，走死，自掘坟墓。于是，日本政府，又出现曾经相似的一幕，日本首相辞职。这个习惯的辞职，对日本来说，是临时的救命稻草。

龙之声想提醒日本将要出现的新政客们，无论你是亲华也好，亲美也罢，一定要把握住大方向，不然，噩梦不远。

关于美国即将推出的QE3政策的影响，我们将结合最近时期中国周边的新闻和外交事件，就大家最关心的中国应对问题，在本期国际观察的最后给大家做下回顾和分析。

*【新闻链接】朝鲜：美韩联合军演是对朝鲜全面宣战* 平壤消息：据朝中社17日报道，朝鲜祖国和平统一委员会发言人当天发表谈话说，美韩联合军事演习把针对朝鲜领导人的特殊战斗训练和对朝鲜核和导弹设施进行先发制人的打击作为主要内容，这是对朝鲜的“全面宣战”。

*【新闻链接】拜登接受《人民日报》专访暗示将放宽出口管制* 华盛顿8月16日消息：据人民日报报道，美国副总统拜登启程对中国进行正式访问前接受本报书面采访时表示，当奥巴马总统和我就职时，我们就知道与中国的关系将是我们最优先考虑的事情之一。我们决心将两国关系确定在可以持续几十年的稳定轨道之上。

*【新闻链接】报道称：越南政府宣布禁止反华游行称其被敌对势力利用* 河内消息：据法新社报道，越南当局表示反华游行示威必须停止，称敌对势力正利用反华活动制造分裂和破坏越中关系。

*【新闻链接】美国声明:支持印度示威者印度国会：怀疑美为幕后黑手* 新德里消息：据《印度快报》网站报道,印度国会开始怀疑此次由安纳·哈扎尔被捕引发的大规模示威是否存在幕后黑手。

*【新闻链接】金正日时隔9年再访俄罗斯或讨论重启六方会谈* 据媒体报道：朝鲜最高领导人金正日20日上午乘专列抵达俄罗斯边境城市哈桑。克里姆林宫和朝鲜媒体证实，金正日开始访俄，将与俄总统梅德韦杰夫会晤。这次访问正值金正日首次访俄10周年之际。外界预计两国领导人将讨论双边经济合作、俄罗斯对朝人道主义援助和重启朝鲜半岛核问题六方会谈等事宜。

*【新闻链接】中国外交部：巴基斯坦外长希娜将于23日至24日访华* 北京消息：据中国外交部网站消息，外交部发言人马朝旭宣布：应外交部长杨洁篪邀请，巴基斯坦伊斯兰共和国外交部长希娜·拉巴尼·哈尔将于8月23日至24日对中国进行正式访问。

*【新闻链接】巴基斯坦在野党称：暴力事件如果继续将要求总理下台* 伊斯兰堡消息：据媒体报道，当地时间8月22日，卡拉奇暴力事件又导致至少8人死亡。针对持续的暴力事件，巴基斯坦“统一民族运动党”表示，若政府无力制止暴力事件，则要求总理优素福·拉扎·吉拉尼下台。
　　
*【新闻链接】美国防部发布2011年中国军力报告新增航母内容* 美国国防部24日发布《中国2011年军事与安全发展报告》，报告尽管强调美国欢迎一个强大、繁荣、成功和巩固国际规范、增进全球安全与和平的中国，承认中国更多地参与国际维和、反海盗、人道主义救助等行动，但对中国的现代化军队“可能被用来增加中国获取外交优势或有利于其解决争端的能力”表示担忧。

*【新闻链接】人民币加快国际化步伐* 国务院副总理李克强在港表示,香港发展离岸人民币业务具有天然优势,中央政府将积极支持香港人民币市场发展,拓展香港与内地人民币资金循环流通渠道,支持香港离岸人民币金融产品创新发展;将把跨境贸易人民币结算范围扩大到全国,开展外资银行以人民币增资试点,支持香港企业使用人民币到境内直接投资,允许以人民币境外合格机构投资者方式(RQFII)投资境内证券市场,起步金额为200亿元,允许境外企业以人民币到境内直接投资(RFDI);将增加在香港发行人民币债券的境内金融机构主体,允许境内企业在香港发行人民币债券,扩大境内机构在香港发行人民币债券的规模。

*【时事解读】* 关于中国周边国家的安全形势，是与中美两国之间的围堵与崛起之间搏奕反映，从这点上讲，中国周边动荡的周边环境，是符合美国的战略要求和安排的，他的全球战略不光是反应在中东问题上，与东亚和南亚局势及世界上的其他关键点的动荡都是有所必然联系的。几期前，我们就曾提出，如果欧美有妥协的意向的话，那么东亚的朝鲜半岛也很可能紧张，另外就印度可能被引发革命及巴基斯坦的安全等方面做出过分析。近期事态的发展看，不论是从朝鲜半岛大规模军事演习还是印度的反腐示威，还是巴基斯坦的爆炸声响，都如期的上演了。因为从美国的利益考虑，它现在需要的是在中国周边环境上有持续时间长且影响力大的动荡，从阿富汗战争，印巴冲突至朝鲜半岛的紧张局势，以及中南半岛的小国政治动荡到现在连印度都开始的革命化浪潮，周边之乱，不仅可以牵扯中国的发展精力，而且会为美国对中国施加压力创造有利条件，而在应对方面，中国也做了很多实际的工作，如周委员的中国周边之行，也当然不是去观景的。

当然哪有压迫，哪里就会有抗争，关于朝鲜的金正日对俄罗斯的访问，韩国媒体给了很多带眼镜的解读，这一点上说明了他的无奈和紧张。正像前几期所分析的一样，这个国家的领导人和媒体总是在耍弄那种商人式的小聪明，结果却经常是搬起石头在砸自己的脚。天安事件如此，向天射击还有前段时间的炮击事件，都是一样，他总想在大国之间找到自己的位子，并企图以最小的代价来绑架大国在地缘上对他的实际支持，结果自以为聪明的自残行为不断发生，可是总是却难以达到他的目的。这次也同样是如此，发动如此大规模的演习，劳民伤财不说，还换得了在三日内，被清算在金刚山的旅游资产作为报复的后果。不仅如此，做为反制，金正日在连续三次中国行得到安全背书之后，又去了俄罗斯，以进一步加强与中俄之间的经济的合作和相互联系，最大限度了消弱了演习所能带来的不利影响。而更有趣的是美联社也闻风而动，去到了平壤对朝鲜进行了关注，不知道当李商人看到朝鲜人在机场欢迎美国媒体的代表团时心里是做何感想的，花费巨大的演习，买单的却得不到实惠，而是被一个小小的美国媒体给淡化了，这种玩笑开得有点大，其间的甘苦滋味让李大总统慢慢咀嚼吧！


印度之乱当下看还基本在控制之内，留待继续观察，另外还有俄罗斯的心态变化，也会在以后的观察中为大家奉上。下边将就美国副总统的来访及中国的应对来结束本期的观察。

美国副总统拜登在中国总共进行了六天的正式访问，这期间他不光跟中国的领导进行了勾通，还去了中国四川的成都，而被媒体所关注的，当然还有其带领手下在中国吃凉拌面消费不多的新闻。龙之声观察员认为： *不要被一些表演性的东西掩盖了其人此时来中国的真正目的，这次来华的主要目的，其实显而易见，那就是一个 “钱”字。*

在前几期中，我们都为大家分析了美国将推行QE3的可能性，拜登此来，主要目的在这一点上，美国希望得到中方的理解和帮助，继续购买美国稀释后的国债，以帮美国渡过难关，至于其他方面的功课他也做很多，像对日债打压和对欧洲的攻击，都可以看做是前戏的准备。最终的演出就是为了QE3靴子落地的那一刻。而对中国的影响当然也是大家所最关注的话题之一。从前两次QE的效果来看，并不是如美国预想那样对他经济复苏的帮助有多大，倒是给世界上各国特别是发展中国家带来的输入性通胀，当美元被稀释后，大宗商品的价格是必然走高的结果，从而自然增大发展中国家对能源需求的成本。另一个目的，自然就是关于人民币汇率了，做为对美最大的出口国，人民币升得越快，对美国的出口和就业就越有帮助，这正是美国人的盘算。至于吃个面什么的，不过是表演罢了，没必要做太多的解读的。当然其他方面，如达成10亿的商品交易，和对台军售等问题，不过是美方自己先制造了，后来加经解决的老手段了，同属于表演性质的事。多年来，在对台问题上一手制造矛盾，一手解决矛盾，都是用烂的手法了。

至于中国的应对，首先是关于美债，买与不买都不该模式化，切忌冲动和盲动，要灵活根据形势的变化进行有选择性操作。要充分了解调查当下美债受追捧的实际原因，还要跟欧洲合作，尽可能的为中国外储的多元化策略增加有利的条件。另外一点，就是升值问题，中国政府这方面做的还是相当到位的，7月份的统计结果，是人民币已经在有所贬值，说明虽然人民币对美元升值较快，但相对于欧元和日元的贬值，淡化了这种单边升值带来的后果，后续上要防范欧美日之间达成联合，以使人民币承爱更大的压力。不论他实际的QE规模达到如何，总之，加强外储的多元化，促进产业转型升级的策略，抓紧扩大内需的策略，加快企业“走出去”的策略，都要有条不紊地扎实推进，持之以恒，以时间换空间，必收大效。另一个重要的消息就是当下的人民币国际化进程，走上了快车道，李副总理于前段时间亲自在香港主持发行人民币离岸债券的消息和最近关于中国将开放资本项目的新闻，都说明了这一点。关于人民币要加速国际化的进程和因此而可能带来的变化，在上期观察中，观察员已经做了分析，那么在这期中，观察员要提醒的是： *人民币国际化的进程中，加快可以，但不能超速，一定要把好关口，在这一点上切忌被金融大跃进的思维所左右，一定要对相关金融制度进行不断的完善和修订，这样才能让人民币国际化的道路走得更扎实更稳。*


从周边环境和经济环境上看，相对中国来说，形势仍然是相当严峻的，反中或遏中战略，会是一个长期必然的存在。最后观察员要强调： *勿以羔羊之心度豺狼之腹，不光要听其言，还要观其行，唱得再好不如做的到位。* 嘴上唱得好听，背地里下绊子的事，做了也不会得到什么好的结果的。从本质上要看到，美国作为拥有全球经济军事霸权的垄断资本主义国家，不会坐视金融泡沫破灭引发危机侵蚀其国际地位，不会容忍给其带来巨大利益的美元霸权走向衰落，为了转嫁危机并维护霸权都有可能采取进一步的疯狂举动，在加大对中东整合的同时，在中国周边地区的关键点上制造战争危险局势很可能是其选择，另外，其更可能加大金融投机力度促使全球食品、能源价格暴涨，加剧全球严重通货膨胀来诱发各国民众的不满情绪，配合非政府组织、互联网宣扬“普世价值”并精心策划突发事件，甚至直接干涉中国内政制造政治动乱和颜色革命。如此的背景和形势下，需要我们的高层领导人保持高度的清醒和警觉性。正如前文提到中东一样，与之相关联的中国周边及中国国家安全和经济安全问题，不仅取决于美国政府的战略决策，还与其他非美势力的联合，特别是中国的反抗意志和决心是息息相关的。


*中国需要做的也很多，除加大威慑外，还必须做好内部工作。* 而只要有个别不知道自己份量的国家愿意做炮灰，那么，在必要的时候给予雷雷霆，就成全它。
