# -*- org -*-

# Time-stamp: <2011-08-04 18:24:56 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent


* 【金鸿95】也谈中国的通货膨胀

  [2008-05-26 17:09:25]

  
    一年来，中国的通货膨胀非常严重。对其原因的分析，也是众说纷纭，莫衷一是。

    其实，出现通货膨胀的原因只有一个，就是相对于商品的增长而言，货币增加的更多；也就是说，货币增发的速度比商品增加的速度快。当然，这个道理
反过来也成立：如果一个经济体遭遇到了重大的破坏，比如战争，即使没有增发货币，由于商品生产能力大幅下降，同样会出现通货膨胀。

    中国出现了严重的通货膨胀，也应该以此为基础进行分析。当然，为了便于理解，从两个角度来看这个问题：

    1、外汇储备暴增。从07年年初到现在，中国的外汇储备增加了6000亿美元，中央银行不得不多印48000亿元的人民币，中国的商品生产能力没有多大的提
高，流通中的货币却暴增了这么多，能不出现通货膨胀？所以，大量美元流入中国外汇储备体系是中国出现通货膨胀的第一个元凶。当然，这些美元是货币滥
发的结果——否则，如此大数量的美元流入中国，美国应该出现严重的通货紧缩才对。

     2、进口原材料价格的大幅增长。比如石油、铁矿石等等。由于这些东西是工业生产和生活中必须要用的基础性资源，所以，它们的涨价导致了商品生产
成本的提高，反映出来就是通胀。其实，进口原材料价格的提高是由于美元滥发造成的，美元多了，原材料的生产没增加，过多的美元追逐有限的产品，它们
能不涨价？所以，中国出现通货膨胀的第二个元凶还是美元。

    综合起来看，造成中国出现通货膨胀的两个元凶是原来是一个——美元。所以，现在需要思考的问题是，这么多美元兴风作浪是为了什么？要搞清这一点，
不得不先弄明白货币数量与经济产出的关系是什么。

    关于货币量与经济产出的关系，这里有一个公式：MV=PY。M表示一定时期流通中货币的平均数量；V表示一定时期单位货币的平均周转次数即货币流通速
度；P表示商品和劳务的价格指数；P表示商品和劳务的交易数量。这个公式的意思就是：商品交换的结果就是经济产出（这里面没有包括自给自足的那一部分
，但是由于那一部分占经济体的比例太小，可以忽略）。

    通过这个公式可以发现：当货币数量M增加以后，物价水平P也会跟着慢慢提高，这就是通货膨胀的传导过程。同样，在P提高了之后，如果货币数量M剧烈
减少（即通货紧缩）了，P则不会跟着立即下降来，仍然需要一段时间才会降下来。在这期间，因为M减少了，V不变，P短期内不变，所以Y会减少，也就是说
，经济产出会大幅下降。这也是资本主义国家暴发经济危机的原因——通货紧缩。

    对于中国而言，这一次通货膨胀是被动的，是由于美元作用的结果。所以，如果将来有一天，大量的中国外汇储备剧减，中国经济也将会出现严重的经济
危机，这是我们必须得提防的。我们要做的，首先就是阻止中国经济的通货膨胀继续下去。要阻止通货膨胀，必须从两个方面下手：1、阻止热钱的继续流入
，2、争夺大宗商品定价权。要争夺大宗商品定价权，需要做两方面的工作：1、介入巴以和谈，把油价压下来；2、参股控股国外大型的原材料生产企业，争
夺世界矿产资源。唯有如此，才能摆脱受制于人的局面。
