# -*- org -*-

# Time-stamp: <2011-08-04 18:09:12 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 【金鸿评论】新一轮的博弈展开了(1日更新)
[2008-03-24 13:01:12]
  
       24日更新:
    伊朗外长穆塔基24日在塔吉克斯坦访问时表示，已正式向上海合作组织（SCO）秘书处提交了加入申请。
    2008年3月24日晚，外交部长杨洁篪同俄罗斯外长拉夫罗夫通电话。
    伊朗军队近几天来连续对伊拉克东北部地区进行炮击，但没有造成重大损失。

    伊朗外长穆塔基周六在群众集会上说：获得用于和平目的的核技术是伊朗的权利，伊朗在这方面不会做出任何让步。他指出：伊朗专家在核技术方面取得
了巨大的成功，今天伊朗已经不需要其他国家的专家。 
    美国副总统切尼3月24日表示，巴勒斯坦伊斯兰抵抗运动(哈马斯)在叙利亚和伊朗的帮助下试图破坏巴以之间的和谈。

    美国国务院发言人麦科马克24日宣布，美国国务卿赖斯将于本月28日至30日访问以色列和巴勒斯坦自治区，以敦促巴以恢复和平谈判。
    黎巴嫩真主党总书记纳斯鲁拉24日在贝鲁特说，真主党要为被以色列暗杀的其高级军事指挥官穆格尼耶复仇。
    萨科奇建议美国和中国批准“完全禁止核试验”条约。法国总统说:“美国曾于1996年签署了“全面禁止核试验条约。现在是该批准的时候了。”
    【金鸿评论】从上面的一系列互动可以看的出来,现在大国斗争的核心已转移到了中东和平进程的主导权上了。其实，8日时入联公投就已进入扫尾阶段（
美国《华盛顿邮报》7日报道说，陈水扁执意推动“入联公投”，美国已经改寄希望于台湾人民），当时我曾给出过个人观点：入联公投结束的钟声终于被美国
人撞响了，台湾各届也开始“拒领公投票”;如果不出现大的意外,入联公投已进入扫尾阶段。接下来我们就可以看到“台湾人民”是如何反入联公投的,小扁又是
如何“被民意所迫”灰溜溜的停止入联公投的了——估计入联公投会在一周内彻底停下来。看来布什还是想表演一番，让我们胡主席看看他是如何玩弄台湾的“民
意”的，又是如何巧妙的把下一个台独头子马英九送上宝座的。
    当时，我也犯了一个错误，那就是领会错了红线，我也以为“公投即是战争”，所以我才会认为17日能停下来，其实，“公投过关才是战争”。这是我犯的一
个错误，当然，其他的地方，就没什么错了。
    不得不说的是，布什团队养了一群猪，如果早一点停下来，损失会小一点，因为他们一直在死撑，所以吓坏了小日本，也吓坏了亲美的萨克奇。为了给自
己找回点面子，才有了洛佩西见达赖的丑事。其实，这样的小动作是没有战略价值的。
    公投一结束，各方马上开始了新一轮的较量——巴以和谈的主导权问题。坦白说，这块硬骨头我们不是啃了一天两天了。现在，到了啃出点东西的时候了：
    伊朗一边找美国的茬子，一边还在那里招摇——俺是有组织的人。杨部长的电话打的也是时候，生怕别人不知道中俄是伊朗的后台。
   美国为保巴以和谈主导权，又想拿哈马斯开刀，这时，真主党又跳出来了——还真有不怕事情闹大的。早就说过，哈马斯-真主党-叙利亚-伊朗是一根线上的
蚂蚱。
   欧盟还是在抱幻想，想在上合与美国之间来个“一碗水端平”。哪有那么容易？这年头，必须得选队站，不站就出局！伊朗又拿核问题敲打欧盟了。这个楔
子是砸定了，看欧盟的选择了。——中美禁止核试验？想当和事佬，你的份量还不够！ 当然了，从土耳其还在炮轰库尔德武装看，欧美之间在巴以和谈问题上
还是有统一战线的——可苦了美国人的盟友库尔德人了，两边挨揍！
   这一轮次的斗争全面展开了，接下来，好戏多多，最大的看点就是——欧盟吃亏多还是美国吃亏多。
   至于台海，谈是为了暂时稳定局面，为了不给对手们机会。我们不对小马抱任何幻想，三通能不能实现，小马说了不算，看美国人的。当然，美国人可以
不干，没问题，金胖子还想再点一炮呢，谁管得了？
   想要朝鲜核申报？三通得有动静才行。当然，胖子不能白干，为什么搞核研究？因为缺能源，这边弃核了，布什大爷不得给点补偿？重油，大米，美元，
一个都不能少。
  
    27日更新:

    法国总统萨科齐25日表示，不排除抵制出席北京奥运的开幕仪式，抗议北京在拉萨的行动。

    德国联邦政府发言人周二表示，达赖提出在他五月访问德国时和联邦总理默克尔再度会谈，被默克尔拒绝。

    美国驻埃及大使馆26日发表声明，承认24日晚在苏伊士运河发生的美国军用货船向埃及小船开火事件造成一名埃及船员死亡。

    【金鸿评论】巴以和谈的主导权事关全局。在当前情况下，中国是势在必得；当然，不争也不行了。

    现在油价持续暴涨，给中国造成了巨大的通货膨胀压力，严重损害了中国经济的健康运行。但是，不能不说的是，油价持续上涨并不是由于产能不足造成
的，而是因为美英金融资本炒作的结果。但是，我们绝对不能任凭油价就这么涨下去，1973年石油价油暴涨造成的发展中国家债泡沫对这些国家造成的严重打
击就是前车之鉴：

    1973年10月，第四次中东战争爆发，阿拉伯国家纷纷要求支持以色列的西方国家改变对以色列的庇护态度，决定利用石油武器教训西方大国。10月16日，
石油输出国组织决定提高石油价格，第二天，中东阿拉伯产油国决定减少石油生产，并对西方发达资本主义国家实行石油禁运。因为当时，包括主要资本主义
国家特别是西欧和日本用的石油大部分来自中东，美国用的石油也有很大一部分来自中东。石油提价和禁运立即使西方国家经济出现一片混乱。提价以前，石
油价格每桶只有3.01美元，两个月后，到1973年底，石油价格达到每桶11.651美元，提价3～4倍。随着油价的暴涨，印度、苏丹、巴基斯坦、菲律宾、泰国、
非洲和拉丁美洲，一个国家接着一个国家面临着贸易赤字。许多正在实施工业化的发展中国家已经陷入对世界银行低息贷款的严重依赖，石油价格猛涨使得这
些国家的大量资金被高油价所吞噬。最后就是这些发展中国家掉进了美英金融势力设下的陷井。

    在事情过去之后，人们才明白，OPAE是中了美国人的招了——先挑动埃及和叙利亚进攻以色列，美国再公开支持以色列来激怒阿拉伯人，导致阿拉伯国家一
怒之下对西方实行石油禁运，最后石油价格一飞冲天。

    今天，我们该怎么面对这种局面呢？如何才能把油价重新拉下来？办法只有一个，进入巴以和谈坐庄。

    只有这样，我们才能把阿拉伯国家的亲华态度做实；只有这样，我们才能为阿拉伯国家争得利益；只有这样，我们才能有和美英金融势力谈判的资本——你
再把油价炒高10美元，我就让一个听我话的中东产油国放弃用美元结算石油价格——想要美元霸权不要太过份。

    现在，伊朗叙利亚都在我们的阵营，沙特也一心投靠，就连最亲美的埃及都逐渐的站在了美国的对立面，在这种情况下，美国为了维持在中东的统治地位
，对埃及人开枪警告就是很自然的事情了。

    巴以和谈的主导权旁落的确是个挖心挖肝的事情，不说美国，就连法国都扛不住，萨克奇居然拿抵制奥运会开幕式说事——你抵制石油吗，萨克奇？

    不过，可以看得出来，欧盟还是非常希望与美国一道联手阻止中国坐庄巴以和谈的。可惜，这样的小手腕没什么价值。伊朗的所谓加入上合就是警告欧盟
的，不要逼中俄做出和欧盟撕破脸的事情来。当然，欧盟也怕这一手，所以让德国人出来消毒，说什么默克尔拒见达赖——见呗，谁怕谁，你都有初一了，还怕
有十五吗？

至于美国的那几手小动作，实在没有多大意思：

    美军与印度官员商谈前往所谓的阿鲁纳恰尔邦搜寻二战期间坠毁的B-24轰炸机残骸和机组人员遗骸的问题。还想在中印领土争端上直接插一脚吗？恐怕三
兄还没傻到那个份子上。这年头，小巴兄弟都想揍老三，还况中国！

    向台湾运送了弹道导弹零部件和弹道导弹零部件并非核武物资的澄清。这样的小动作还是收了吧。去年又不是没玩过，又是台湾搞雄二E，又是小扁下令
造原子弹，闹得不比这个动静还大？结果怎么样？还不是小扁出来保证绝对不搞原子吗？这次还要逼小扁出来写血书不成？荒唐！

    当然了，争夺巴以和谈主导权比入联公投中的较量要激烈得多。看看各国已经开始选边站队了：

    委内瑞拉总统查韦斯25日指控美国鼓动西藏暴力冲突，并说华盛顿的目的就是要削弱中国。

    俄罗斯《独立报》的报道称，格鲁吉亚外交部近日针对俄罗斯杜马建议俄联邦首脑考虑承认阿布哈兹和那奥塞梯独立一事发表了言辞激烈的批评。该言论
是在莫斯科和第比利斯关系出现缓和时发出的。报道认为，格鲁吉亚外交部的个别词汇甚至可以理解为“宣战”。

    巴基斯坦前总理谢里夫25日在会见美国官员时表示，巴新政府将重新审视巴基斯坦在美国发动的反恐战争中的角色。

    一位韩国政府官员27日称，韩国已决定承认科索沃独立。

    首尔27日消息：据当地媒体报道，韩国统一部官员证实：朝鲜已单方面要求韩方人员离开开城联合开发区。

  28日更新：

  朝鲜在28日当地时间上午从西部海岸向黄海试射了多枚近程导弹。
  【金鸿评论】辛辛苦苦写了半天，一断电全丢了，只好再简单重写一下。

  三天前希尔还牛皮哄哄的说布什下台前朝鲜能弃核，这一下子可把他那张牛皮嘴撕烂了。当然，事实没这么简单，我方（中俄朝）这次的要价是非常高的：

   1、给埃及撑腰

   美国为了镇住阿拉伯国家一个个从自己阵营里逃走，拿埃及开刀，在苏伊士运河开枪杀了人连个歉都不道，很显然，蓄意而为。为了拉过阿拉伯国家，中
国必须出面给埃及撑腰。当然，这种事也不是第一回了。上一回是在哈马斯炸墙的时候，美以警告要收拾埃及，当时就传出了中国要在伊朗建海外基地的“假
消息”，之后，美以没敢动手，“假消息”也就成了假消息。这次，中国又出手了。不过，这次是真动静，看来，坐庄巴以和谈的决心不小。

  2、彻底废掉台独牌

   布什明明知道台独牌打不赢了，还要用“误运导弹零件”的方式变相打一打台独牌。可恶！既然美国能打暗着打台独牌，我们当然能明着打朝鲜牌。看谁顶
不住。这次是强烈警告。

  3、警告李明博

   姓李的敢承认科索沃独立，这不是明着往北极熊的熊掌上踩吗？我可忍熊不可忍！不给他一巴掌他不知道自己姓什么！

  接下来的看点有：1、美军在苏伊士运河开枪杀人事件的处理结果；2、两岸关系；3、李明博的外交转向问题；4、美国是否会给朝鲜以物资支援？

  31日更新：

  美国总统布什28日打电话给埃及总统穆巴拉克，对美国海军租用船只上的安全人员击毙一名埃及人事件道歉，这艘船是美国海军根据合约租用的民间船只。

  第20次阿拉伯国家联盟(阿盟)首脑会议30日在此间通过一项决议，重申阿拉伯国家愿加强与中国的合作。

  【金鸿评论】布什也就这两下子了，欺软怕硬。巴以和谈主导权争权有一定进展，下一步估计得打一下伊核牌，刺激美国或者欧盟介绍中国入场。

  台湾警方将“三"一九”枪击案以结案处理，国际知名刑事鉴定专家李昌钰纽约当地时间30日表示，“结案不代表破案”；倘若有新的人证、方向、线索或新东
西出现，全案可随时重新调查；涉及物证部分，他绝对配合。

  马英九28日接受媒体专访时，对国家主席胡锦涛与美国总统布什日前在热线对话中提出的“九二共识”与“一中各表”下恢复两岸协商，表示是对两岸关系来说
会是正面发展，是一个进步。马英九呼吁大陆和台湾能回到“九二共识”“原版”的基础上展开协商，两岸可以“连胡公报”为起点进行协商。

  据朝鲜中央通讯社3月30日报道称，鉴于日前韩方官员对朝方发表的不友好言论，朝鲜威胁可能中止与韩国的一切形式对话。此外，朝鲜军方将全面禁止包
括韩国军方人员在内的所有韩国官方人员通过军事分界线。

   27日，李登辉和马英九会面，双方谈及台湾未来以及两岸互动。而李登辉30日晚上表示，两岸根本没有“九二共识”，马英九拿什么和大陆谈判，他不知道
，他说有提醒马英九务必坚持“台湾主权”。

   【金鸿评论】台湾问题上，美国在两个方向上试探（或者准备），一是开打台独牌，逼中国动武，以扭转中东颓势，二是开始谈三通。估计三通的可能性
大。

   日本也是唯恐天下不乱，希望老金折腾的大一点，好有机会从它的美国主子那里捞点好处出来。有推波助澜的就好，这样美国更架不住老金的折腾。

   李明博非常配合美国，这是个标准的韩奸，为了修复韩日关系居然可以“不要求日本就殖民统治道歉”，看来当年李明博的家人被太君关照的很好，日子很
滋润。  这会把老毛子得罪的不轻，估计以后有它好日子过。

   1日更新：

   俄罗斯驻联合国大使维塔利·丘尔金3月31日呼吁伊朗放弃拒绝同安理会五个常任理事国以及德国举行核问题会谈的反对立场，以使人确信其核能项目是和
平的。他表示解决伊朗核纠纷的唯一途径则是通过和平谈判。

   军方消息灵通人士透露，伊朗在近日已经派团秘密抵达成都，就伊朗购买40架J--10的相关问题进行磋商。

  【金鸿评论】中俄一文一武终于出手了，不同的是这次俄罗斯来文的，中国来武的。中国是希望把台湾的事情压下去，俄罗斯的意思是把伊核问题与巴以和
谈挂钩。好戏开场了，等着看各方面的反应吧。

   现在正在忙着写那篇金融文章，写了三万字，估计还有不到一万字，先忙那边，评论这边少写点，大家见谅。那篇文章的观点绝对是与主流观点完全相反
的。呵呵。

