# -*- org -*-

# Time-stamp: <2011-08-04 18:27:01 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent


* 【金鸿评论】近期国际局势观察之二（14日更新）

  [2008-06-06 21:24:55]


      【金鸿评论】从5月29日开始说。那一天先后传出了与三个国家领导人有关的消息，金正日死亡，阿罗约遇刺，穆沙拉夫辞职；同时，美国也给伊朗扣上
了一个与基地组织“密切接触”的罪名——以前打阿富汗和伊拉克好象就是扣的这个帽子，这些同时出现的险情说明，有人已经拔出匕首准备冒险了。

    美国要对伊朗动手，切断巴铁通道是必须得做的。而日本也以为自己有机可乘，就开始大肆炒作自卫队军机入华的事情。要知道，巴铁是中国的全球支点
，如果这个支点被人抄了，那中国的全球战略就失败了。作为报复手段，中国只能向美国的全球战略支点——日本出手。

    所以，在30日，朝鲜进行了导弹试射。当然，当时李明博还在访华，他的某些表现也不让中国满意，打两发导弹正好警告他一下，半岛局势不是区区一个
韩国能控制得了的。

    朝鲜的导弹一打，日本的态度马上转变，日本再也不提军机入华的事了，转而追加5亿日元的灾区捐款。其实，这笔钱是金正日帮我们打劫来的，要谢就
谢老金，不用谢福田。其他的后果还有就是日本在海上自卫队舰艇访华变得谨慎多了——谁说这小子不长记性？还是抽的他少了。

    在我方果断出手之后，美国反而又强攻了一步，捅出了盖茨想往巴部落派地面部队的消息，这可不得了，惹得内贾德老兄又出惊人之语：“以色列将灭亡”
。其实，这话的意思是说，再玩大了伊朗的原子弹就爆炸了——如果伊朗也有了原子弹，以色列在中东的军事优势就荡然无存了，没有了军事优势的以色列又如
何生存在伊斯兰世界的怒火中？

    巴铁也在这时壁虎掀帘子——露了一小手。巴控克什米尔地区地方政府２日向中国四川地震灾区捐赠１０００万卢比（约合１７万美元）的现金和１５００
顶帐篷。这其实是在挑印度一把。看它敢不敢趁乱浑水摸鱼。印度的回应是是很让人满意的——抓了五个藏独头目向中国示好。当然这是演戏，但戏能演到这份
子上也不容易了，说明阿三还是有长劲的。

    南亚印度收敛的同时，东北亚形势也变得更加理想：4日韩国表示准备向朝鲜援助5万吨玉米。这说明李明博的朝核政策认栽了，五天前老金的导弹起作用
了。同日，町村信孝说日美之间不存在关于朝鲜紧急事态的密约，这说明小日本的朝核政策也全面向中国靠拢了，现在，朝核六方会谈成了五打一了，所以，
台海不三通都不行了。不过还要给大家提个醒，不要认为那个马鹰狗是个好东西，现在两岸一团和气是我们拼出来的，不是他想统一。当然了，处在中美夹缝
中的小日本也不好过，完全倒向中国又会被他的美国爸爸收拾，为了还给他美国爸爸留点想头，福田在派出自己的内阁官房长官町村向中国的朝核政策致意的
同时，还亲自出面说什么尚未考虑是否出席北京奥运会开幕式一事，其实，这是哄他爸爸的空心汤圆。福田爱来不来，不来我们就多卖张门票，有什么大不了
的？

   由于现在东线对美国而言面临失控，所以美国只能用海台三通来换东线的暂时稳定，以求突破西线。对美国而言，中东才是核心，石油才是关键，美元才
是生命。所以，美国在东线有多少忍耐，在西线就会发多少狠。当然在西线美国也非常不顺利，中东那把尖刀现在非常不好用，所以，才有了奥尔默特天天吃
官司的事。其实也不怪以色列，06年没打败真主党不就是因为美国在背后不出力的结果吗？

美国在中东露出了獠牙，一是想收拾哈马斯，二是想切断巴铁通道，三是想吓住伊朗。巧的很，4日基地组织的二号人物扎瓦赫里发表了最新录音讲话，纪念
阿拉伯国家和以色列之间1967年爆发的战争，呼吁在加沙地带发动“圣战”。这是什么意思？

    要知道，加沙现在在哈马斯手里，而哈马斯在美国人的恐怖分子名单里，所以，这是在暗示哈马斯与基地一伙，含有威胁武力清剿哈马斯的意思。但是，
如果哈马斯那么容易就可以整死的话，何至于让他们占领加沙一年多？就算现在以色列有心动手，他还有那个胆子吗？所以，以色列长巴拉克5日说在巴勒斯
坦各派别和以色列达成停火协议之前，以军“可能”会对加沙地带发动大规模军事行动。“可能”是什么意思？也许打，也许不打。如果以色列真有胆量的话，何
必“可能”呢，直接动手就是了。

    同时，阿巴斯也没闲着，想趁火打劫一回哈马斯，说什么自己并未放弃与哈马斯恢复对话的条件，阿巴斯的条件就是哈马斯放弃对加沙地带的控制。这小
算盘打的，啪啪响。要是哈马斯交出了加沙的控制权，布什不就在巴以和谈问题上解套了吗？阿巴斯和以色列显然是在一唱一合。

    当然，如果没有伊核问题，如果没有中俄借着伊核撬巴以和谈，哈马斯又何必挂在心上？所以，真正的核心还是伊核。对付伊朗，美国直接动武是不可能
的，一来他没兵了，二来肯定没人支持他，除了以色列，就连英国都会反对——上一回打伊拉克，英国佬也够卖命的了，可分到了什么战争红利？这回要是再白
帮忙，那英国的资本家不都成雷锋了？

    要想不动手就吓住伊朗，只有切断伊朗的外围通道，让伊朗感觉到威胁，才有可能逼伊朗软化态度，才有可能让中俄在伊核问题上失去主导权。但是，通
往伊朗的通道有三条，土耳其，土库曼，巴铁。其中只有巴铁最坚定，所以，首先必须切断巴铁。所以，美国才一再的要进巴铁反恐，抓拉登。其实，真实的
目的是切断通道。但是，老穆死活不放美国人进去。无奈之下，美国人只好利用巴国家的政派混乱，来搞搞事。比如今天，人民党的布托老公，那是恨老穆的
吧？比如谢里夫，那是穆的死对头吧？美国说：谁给我把老穆搞下去，我就全力支持谁，这样谁也出力呀。当然，把老穆搞下去并不代表上台的就不亲华，谁
敢不亲华，军方肯定会出手收拾他。中国连巡航导弹和原子弹都给巴铁了，他还能对中国有二心？但是，这样搞还有一个影响：老穆的地位不稳，他也得为自
己考虑呀，所以，不得已有可能和美国人做交易，让美国大兵进巴，保住自己的位置，但是，这样就背叛了中国的利益。所以，每次美国要进巴抓拉登，老穆
就对中国示好，意思很简单——姓穆的娘家人在中国。多次试探无果，美国人想把老穆搞下台去。近期一再的传出老穆要辞职的传闻，就是美国人说：“我不耐
烦了”。当然，巴国内老穆的政敌也在充分利用这个来搞老穆下台——自己可以上去嘛。这就是各人打各人的算盘。

    现在穆沙拉夫面临的局面非常严重。在这样的背景下，穆沙拉夫的发言人出来辟谣“有关穆沙拉夫总统将退休的说法完全是谎言”就有明显的针锋相对的意
思了。做为暗示性的报复手段，巴基斯坦核科学家卡迪尔-汗已被允许重返社会就是对美国最大的警告。穆沙拉夫下台之时，就是巴基斯坦核武库失控之日，
也是伊朗核爆之日。美国有必要充分考虑后果之后再对老穆下手。

    不过，今天美国的一个举动让人心惊，由于“误送核弹引信到台湾”等一系列严重事故，美空军参谋长莫斯利和空军部长韦恩今天辞职获准。这显然是美国
在台湾问题上对中国极大的示好，但是，这背后的警告意味实在太强了。也许接下来面临的摊牌才是最激烈的交锋——我们必须谨防对方狗急了跳墙。

    不过，它也实在没有多少牌可打了。近来，它严重的透支了自己的国际信誉。发了那么多狠，谁也没镇住，特别是朝鲜，连踩红线，它还装孙子。接下来
如果一个撑不住了，会在中东有一个大的原则性让步——出让一部分巴以和谈主导权给中国，这将是它不得不做出的决定。

    中国在南美也不停手，现如今马岛争端又起，没人支持阿根廷他敢提？有这马岛争端，英国人以后就得悠着点儿了，当然，整个欧盟都会受这个问题的影
响。这一点可能让欧盟想不到，本来打算在美国人的后院与中俄联手划拉一点对付美国人的筹码，没想到又被中俄抓了根辫子。同时，中巴卫星合作也在加快
步伐，好得很。不把火烧到美国人的后院，他永远感受不到真正的威胁。

11日更新：

   巴基斯坦军方１１日发表声明，对美国领导的驻阿富汗联军越境空袭巴检查站事件表示强烈谴责。
【金鸿评论】真没想到布什被逼到了这个份子上，真的对巴铁下手了，在空袭的同时，还让兰德公司放风，说什么，巴基斯坦情报机构和部落民兵一直在为塔
利班提供援助，给巴铁扣上一顶支持恐怖势力的大帽子，让人以为美国真要动手--弄得跟真的似的。
许多人认为，现在局势急，老穆有麻烦，其实不然，现在，老穆可以沉住气了。美国人主动对巴国的人下手了，巴国的亲美派要是再敢张狂，结果会如何? 巴
国人民会怎么看自己的兵被美国人炸的了事? 老穆前几天最大的压力在国内，现在好了，美国人出手给他解套了，美国人在巴越闹，老穆大位越稳。
当然，美国这是在吓唬，一面动嘴，一面试探性的动手，看各方的反应。别人的反应先不说，巴国的军方出来表态了。这个表态有两个关键点：1、面临外患
的时候，老百姓最必须依赖的，是军队，而军队是支持老穆的，所以，现在对巴国人民来说，无论如何都不是收拾老穆的时候；2、巴军方说：“联军这一暴行
损害了巴基斯坦士兵为支持联军反恐战争所提供的合作和奉献的根基”，也就是说，再闹下去美国大兵可要在阿富汗吃大苦头了。
有了巴军方的强硬表态，我们不用再做任何大的表示了，就看美国人怎么收场就好了。
当然，美国人这样做，也是被中东局势逼的。伊朗越来越强硬，以列色又打怵不敢下手，现在居然沦落到了连黎巴嫩都要开和谈的地步，美国人能不急？无奈
之下，美国人选择了默认现在伊拉克与伊朗亲热，这是美国在逼欧盟和阿盟，再不支持我的伊核政策，我可要和伊朗修好了--如果真到了那一步，欧盟在中东
腾挪的空间也就很小了。这一下子还真把欧盟给吓住了，所以欧美峰会上双方能在在伊朗问题上达成一致，强调欧美将共同采取措施，以确保伊朗无法利用国
际银行系统“支持武器扩散和恐怖主义”。当然，伊朗也毫不客气，马上开始撤回存在欧洲银行的资产，这意思是明摆着的，咱爷们离了你们照样过！当然，从
这里也可以看出，现在伊朗是安全的。
    欧盟的做法让人很不爽，所以，俄罗斯也没给欧盟好脸色看--卡扎菲直接否决了地中海联盟。前段日子普京专门去了趟利比亚，卡扎菲一看有人撑腰了，
马上就和以前不一样了，前几天拿高油价说事，让美国人很没面子，今天又直接否了地中海联盟。看看，欧盟难受不？现在倒向谁更合适呢？让欧盟自己去琢
磨吧，我们就不费那份心了。

14日更新：

    许多朋友都觉的，中国应该有所反应，其实，有点多虑了。中国的反应基本在我的预料之中，就是冷眼旁观。不过，中国不动有人动。谁？伊朗。在巴铁
挨炸的第一时间，伊朗的反应是：由伊朗驻日本大使出来强调，“伊朗任何时候都不会停止浓缩铀活动”。意思很简单，你老美吓唬不住我。

    接着，巴基斯坦军方出来警告美国，美国就说，自己是误炸。其实，这样说也是没办法的事，他能说自己是有意的？那就更没法收场了。但是，他又不甘
心，所以，在承认"误炸"的同时，并没有道歉，只说对“巴基斯坦人的死伤表示遗憾”。看来，还打算继续试探下去。当然，行动上美国也有表现，那就是继续
咬住巴和基地组织有联系不放，这样做的意思不外乎还是想切断巴铁通道。于是，伊朗又有态度了，伊朗总统内贾德声称：“美国及其走狗反伊政策必败” 

    这可真不给人家面子。前几天，有以色列亲美派声称以色列攻打伊朗“无可避免”，结果被以色列国防官员和学者们围攻了一顿。其实，国小人微的以色列
是没有本钱和伊朗抗衡的，如果真对着扔核弹，那么肯定有波斯人能活下来，而以色列人毛都不剩一根。如果打常规战，就伊朗那财力，拿着导弹当炮弹使，
谁把谁炸残还不一定呢。所以，对本国负责人的政治人物是不可能轻易涉险单独对付伊朗的，除非美国也上。正因为以色列自己不往上冲，所以，奥尔默特才
被人公开逼迫下台，这也说明，美国真急了。

    所以，美国对付伊朗的外围恐吓战术没有见到任何效果，倒是哈马斯又跳出来了。哈马斯提出的条件是：以色列与加沙地带之间的任何停火都必须以解除
以方对加沙地带的封锁为条件。这个条件是以色列不可能答应的，因为这样做，意味着阿巴斯事实上出局，中国自动加入巴以和谈。

    这么一个折腾，就出现了一个大笑话。哈马斯是12日表的态，在12日布什两次谈伊核问题，先说伊朗应停止铀浓缩活动，否则将被制裁，后又改成不排除
对伊朗动武的可能。要我猜，前一次时，布什还没得到哈马斯开的条件，后一次放话，则是在得到哈马斯的消息之后——老美真是变色龙呀。

    至于中国为什么自动加入，原因很简单，因为中国也是哈马斯的幕后支持者，所以，如果以色列停止封锁加沙了，就意味意哈马斯与以色列的武装斗争赢
了，以色列是占着大片的阿拉伯世界的土地的，有了哈马斯这个榜样，谁还和谈？跟哈马斯学，打！这样一来，谁还对一直在和以色列和平谈判的阿巴斯有信
心？不就相当于阿巴斯出局吗？阿巴斯一出局，巴勒斯坦这边不就是哈马斯的天下了吗？再搞巴以和谈，不就是哈马斯与以色列之间的事了吗？

    应该说，现在是美国人最着急的时候，所以，美国是四处放火。在巴铁炸那一下子绝对是犯晕。不知道哪个脑子被驴踢了的高手给布什出的好主意，一下
子解了老穆的围——既然炸了，还不能第一时间就对这个战术认输，这样一撑，军方对老百姓的影响更大，所以，老穆更稳了。

    在西线美国没有好办法，只好在东线有所动作，日本人撞台湾渔船的事就是个不好的暗示。这后面肯定是美国人的黑手。所以，台湾当局也跟着号称要保
钓，这可是大麻烦：怎么保？如果台湾的军舰跟日本的军舰在钓鱼岛发生了冲突，北京该怎么办？不管？那是我们的地盘。管？那和谁打？日本？台湾？

    所以，这个套子设的不地道。当然了，中国人玩谋略是一流的，咱不进他的套子。你不是在钓鱼岛完领土争端吗？我就在朝鲜玩核问题。

    朝鲜搞了个“党中央纪念金正日首次访华25周年”的怪活动，让人浮想连篇。如果台湾那边有事，半岛一定更热闹，大家玩就是，谁怕谁？

    还有一件很有意思的事情，12日，“嫦娥之父”、中国绕月探测工程卫星系统总指挥叶培建院士在兰州大学透露，卫星已获得的图像质量很好，层次丰富。
透露这个消息的时候，台湾正在声称为了钓鱼岛“不惜一战”。我不太懂军事技术，不过，这个照相技术在打仗的时候一定很有用，警告意味很浓呀。

    这几天，中国又开始炒日本入常的事了。搞了个与几年前“一边倒”的抗议不同，这回，中国网民开始出现支持的声音，让小日本心里怪痒痒的。顺着中国
不顺着？顺着中国就支持你入常。当然了，中国支持也没有用，最后肯定是被美国人否决掉，如果日本真入了常，美国经济就破产了，这买卖赔不起。

    现在，美国在东边和西边同时出了最损的招——台独牌都敢再用用，炸巴铁更是近乎疯狂的举动，这样的招都挽回不了局面，他下一步肯定得在中东让步了
。

    再简单说一下俄罗斯，老熊玩的很有意思。美国要搞北约东扩，惹急了熊，他居然暗示要兵进阿富汗。

    美国拿抽掉伊核谈判桌为要挟吓唬欧盟，逼着欧盟一起对伊朗搞金融制裁，伊朗没害怕，当天就要从欧盟撤资，俄罗斯更不给面子，一脚就把地中海联盟
踢了个翻个，这还不算，还假性性的对欧盟示好：俄罗斯总统梅德韦杰夫11日警告，单靠北约并不能应付冷战后欧洲面对的挑战，他认为应该全面检讨欧洲的
安全体系。这显然是在拆北约的台。欧盟该怎么办？跟俄罗斯联合？那美国肯定在中东修理他，继续跟俄罗斯作对？地中海联盟就别玩了，另外，如果惹大了
，俄罗斯兵力科索沃也不是没可能，如果真到了那一步，欧元就算完蛋了。

    阿富汗有向上合示好的意思，应该。他是上合的观察员吧？如果中俄真封锁他，他活不了的，有毒品总不能空运吧？走陆地，中俄伊巴土，围得他严实实
的，他和中俄暗地里有一腿，美国也得忍着，否则，反恐大业就交待了，中俄包美军的饺子是很容易的，现在，最被动的，就是美国，中俄要求他的是他在巴
以和谈问题上让步，如果他不让，会拖死他，但是他一让，命根子就抓在别人手里了。当然，他一让步，中俄美可以联手先废了地中海联盟，给美国人个交待
。可以肯定的说，近期中国在巴以和谈问题上必有所收获。（

    意大利前年就想进伊核，中国支持（当时是温总见的普罗迪），不过没成功，可能是美国反对。对中国而言，进来的人越多，美国吃亏越大。中国不可能
让步，因为中国有本钱。伊朗核暴了又如何？中国不怕，怕的是美国。
