# -*- org -*-

# Time-stamp: <2011-08-04 18:28:09 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 【金鸿95】嬗变中的全球局势

  [2008-06-25 23:32:06]

  
　　近期国际局势着实复杂，我足足观察了五天，也没彻底理清楚。应该说，近半月来所有的地区热点问题之间全部联动起来，各国加大了探试的力度、外交
取向也开始大幅摆动，应该说，现在处在国际局势嬗变的前夜，这时的局面是最复杂的。

    还是从大家最关心的“美国是否对伊朗动武”说起吧。

    许多朋友担心美国对伊朗动武，我倒想问问：美国为什么要对伊朗动武？真是为了伊朗那还看不到影子的核武器？就算现在美国或者以色列对伊朗动武了
，把伊朗的核设施全给炸了，能解决问题吗？要知道，自从联合国五常都拥有核武器以来，无论哪个新的核国家拥有核武器都不取决于他自已，而是看大国需
要：印度有核是在美国的默许下实现的，巴基斯坦有核离不开中国的支持，以色列那点儿核家底更离不开美国的赞助，朝鲜那颗响了一半的原子弹恐怕也不是
朝鲜兄弟自己干出来的，同样，只要美国人点头，日本人能在三天内把核武器造出来......既然如此，伊朗有没有核武器与这点核设施有什么关系？伊朗会不
会造原子弹不是关键，会把原子弹给点响了就是本事。所以，美国攻击伊朗，原子弹仅仅是个借口。

    当然，对以色列而言，伊朗是否有核是致命的。但是，以色列能否生存下去，同样不取决于他自身。如果没有人在背后罩着他，试想一样，一个面积比中
国一个县城大不了多少的多少的小国家，面对着数百倍于自己的伊斯兰世界，居然能五战五胜，凭什么？真是他能打吗？只有傻子才会相信以色列士兵是天神
下凡。如果没有大国护着他，早就被平掉了。当然，话又说回来了，以色列作为一枚钢钉钉在中东产油国中间，最所有的大国都是有利的，如果所有的产油国
真的一条心了，那对中俄欧美各方，都不是好事情。所以，大国们也会尽可能的保全以色列，这也是现实的国际斗争的需要。所以，不到万不得已，无论是中
国俄罗斯，还是欧盟，都不会允许伊朗拥有核武器，但是，反过来说，如果伊朗的国家安全真的出现了大麻烦，到了中俄欧三家正面无法保全的地步，那就只
能放手让伊朗拥有核武器了。所以，打伊朗是因为伊朗有核只是个借口。既然这样，那么，美国为什么想要对伊朗动手呢？

    真正的原因，来自两个方面：一是因为美国经济出大问题了，美元弱势；二是在这个关口伊朗出口石油用欧元结算挖美元霸权的墙角。这两个原因是相辅
相成的，只有一个都不会导致美国如此的火烧火燎。下面详细说一下：

    先说一下美国经济：从表面上看，美国人过着让全世界人民都把眼珠子瞪出来的好日子，其实，美国经济从骨子里早就掏空了。几十年来，美国人努力发
展虚拟经济，也就是泡沫经济，所以，美国经济“干净”的很，但是，如果没有干“脏活”的国家（比如中国），美国人这么玩只能喝西北风了——这也是几十年来
美国一直有巨额的贸易逆差的原因，因为他不搞生产了。

    如果把整个全球产业链比作一条食物链的话，美国经济处在这条食物链的顶端，他是肉食动物，他欺负别人，所以，他好象是最高贵的。但是，他对于别
人的依赖性是最强的——如果没有人大量的出口日用品给他，美国人可能连裤子都穿不上。

    美国的这种玩法，实际上就是狂吹经济泡沫，但是，吹到一定程度就吹不动了，如果泡沫全破了，那美国经济就完蛋了。所以，他需要输血，可是，谁会
白白的给他输血呢？没办法，一个字：骗。骗的方式有两种，一种是在美国国内市场上空手套白狼，所谓金融市场上的“钱生钱”，特别是金融衍生品市场上的
“钱生钱”，只是个障眼法，是个“套”，就是说，他们在金融市场上炒作，让别人看着这个“钱生钱”有利可图，跟着进去炒，他就赚钱出局了，原来指望也跟着
“生钱”的人就被套住亏在里面了。比如里根时代，放松金融管制之后房地产泡沫暴涨，之后操纵房市暴跌，有人狠赚一笔，既然有人赚了，肯定有人赔了，谁
赔了？别人我不知道，反正那帮子号称要“买下美国”的日本商人是赔的要死（投资炒房的都亏了50%以上）。再比如克林顿时代，狂炒高科技神话，又套了不
少银子。另一种就是在国外，那就是骗与抢相结合了，比如石油危机引发的全球债务危机，比如东南亚金融危机和拉美金融危机，比如解体苏联。

    通过吸血，美国经济可以良性运转，但是，他国经济可就吃大亏了。所以，美国这个吸血鬼的存在，对这个世界而言，是一个恶梦。应该说，从上世纪70
年代以来，美国的吸血事业一直是进展比较顺利的。直到次贷危机暴发，美国经济需要再一次大吸血的时候，只不到冤大头了。从近几年来的种种迹象看，美
国极有可能指望这次通过解体中国经济来为他输血，方式就是打开中国的金融大门。可惜的是，我们的当家人胡温守门守的死，他未能得逞。当然，如果他得
逞了，中国就全完了，中国就重新变成了一个半殖民地国家了。所以，从这个意义上讲，我们也要绝对支持我们的当家人胡温二公。

　　如果美国经济不出问题，那么美元就可以强势。强势的美元还是不怎么怕拆台的，但是，现在美国经济不振，美元疲软是必然的，在这时，如果有人挖美
元霸权的墙角，是比较容易成功的，而就在这时，伊朗搞起来石油欧元，这不是挖美国资本家们的祖坟吗？所以，这一点才是美国一直想打伊朗的真正原因。

　　另外，打伊朗还需要两个关键的条件：钱，兵。其实，说到家还是钱，因为美国有三亿人，不能征不到兵，可在美国经济被次贷危机拖的大出血的情况下
，军费是大问题。另外一点就是，现在美国在伊拉克和阿富汗根本玩不转，如果再对伊朗下了手，所有的美军基地都将是伊朗的目标，这也是美国非常担心的
一点。

　　站在美国的角度看，如果武力打服了伊朗，整个中东就算拿下来，如此一来，全球石油基本受控了，不管是中俄欧，还是日印巴，还是其他的小国，就全
部得听美国人的了，这是各方无论如何都接受不了的。所以，如果美国真要动手了，会有两件事情发生：一是伊核问题会出现质变，伊朗拥核速度将会大大加
快；二是美国所有的盟友（除了以色列），都会成为敌人，除非是傀儡政府。大家轻则通过各种方式援助伊朗，在伊拉克阿富汗给美国大兵找麻烦，重则对美
元霸权发动致命攻击，比如狂抛美元，让美国人直接下地狱，反正大家的日子都没法过了。这一点才是美国最不能承受的。所以，美国一直举棋不定。

　　近期，一直传出以色列要空袭伊朗的消息，其实，这是美国在试探，因为如果美国直接对伊朗出手，局势极有可能滑向他最不愿意看到的一面，但是，以
色列出手就不一样了，这种一小规模的打击如果能震慑住伊朗，美国在伊核六方会谈中就算是咸鱼翻身了。不过，以色列怕遭报复，以色列很明白，伊朗背后
站着中俄欧三个大块头，一旦动起手来，伊朗的报复极有可能是自己不能承受的。所以，奥尔默特一直就不敢往前冲，这也导致了奥尔默特面临着空前的权利
危机。其实，就算以色列换个新总统上来，对伊朗发动一轮空袭，就一定能改变局面吗？恐怕结果是把以色列放到了火炉上烤。

　　既然打击伊朗不是最佳方案，美元地位岌岌可危，当务之急就是摁倒欧元。要摁倒欧元，就需要先尽可能的弱化欧盟在中东的影响力。当前，欧盟只所以
能在中东指手划脚，靠的是在伊核问题上的中间人角色，通过这张牌换取巴以和谈问题上美国人对自己的支持（当然，换牌的内容还包括用科索沃独立换伊拉
克阿富汗稳定）。现在，美国对欧盟是两面手法：一、与我一起制裁伊朗，美国在巴以和谈上给欧盟以照顾，在这一点上，欧盟没有太多的选择余地，所以，
欧盟加大了对伊朗金融制裁的力度，但是，欧盟通过巴拉迪放风，坚决反对打伊朗，也不矛盾。枪一响，欧盟在伊核问题上同样就出局了。二、威胁与伊朗交
好，抽掉伊核谈判桌，把欧盟逼出局，同时也弱化中俄对自己的威胁。不过，这恐怕是美国人的一厢情愿，伊核这张赌桌，上去了再想下就难了。伊朗清楚的
很，一旦今天自己放了美国人一马，明天美国人就会要自己的命。

　　另外，地中海联盟必定是锁定的打击目标之一。对这个联盟，中国俄罗斯印度甚至日本都看着不顺眼，因为一旦欧盟经济上整合了中东，欧元就是大患，
虽然现在大家拿石油欧元顶美元，但只是为了激化欧美矛盾，做收渔利。要拆地中海联盟，有几个关键点可以借用：一是以色列，这个刺头让几个环地中海的
中东国家很不爽，所以，只要他在里面挑事，地中海联盟就难成气候，这不，萨克奇访以为了拉以色列入伙却意外的遇到了枪声，这其中的文章有人还是做的
很用功的。还有一个点就是利比亚，前几天利比亚直接否了这个联盟，很显然，欧盟的某些表现，特别是没有在联盟问题上让俄罗斯分一杯羹让熊吃醋了，结
果给了欧洲人一掌。从这里也可以看出，在这一场斗争中，欧盟是最被动的一方。他吃亏就吃在军事实力太差。这一场斗争的最终结果，极有可能是欧盟吃亏
最多。

　　国际斗争就是这样，国家穷一点死不了，没有军事实力活不好。与欧盟同病相怜的，就是日本。现在，美国经济失血严重，欧元又借机抢位子，美国从哪
儿补血？应该说，中国是最好的，可惜，他搞不定。那么，下一个比较好的目标是谁？日本。虽然出于遏制中国的需要，他暂时没对日本下手，但是，一旦到
了自己扛不住、又搞不定中国的时候，只能对日本下手了。而且，在以前是有成功经验的。所以，日本是非常危险的。日本要想保证自己的金融安全，唯有靠
上一棵大树——中国。只要他全面倒向了中国，美国是奈何不了他的。

　　１９８５年，美欧通过广场协议逼日元升值，又逼日本降息引发流动性泛滥，之后又堵住两头逼日本吹起巨大的经济泡沫，又刺破它吸血无数。应该说，
日本亏在不得不听美国人的，无论是签广场协议还是降息，但是，他当时为什么不能不听？有一个非常重要的原因就是经济人依附于人，不听不行。今天，情
况不一样了。日本经济可以通过融入东亚经济圈来避免受制于美国。而要融入这个圈子，就必须倒向中国。现在，福田平静的接受美国给朝鲜摘去支恐的帽子
，就是一个表现。

　　说到这里，大家可能感觉奇怪了：既然日本这么有求于中国，为什么中国要在东海向日本让步呢？其实，这并不矛盾。日本需要中国，中国也无法甩开日
本。如果日本真的再被美国人宰一刀，那么，整个东亚经济圈都要受拖累，都要大出血，这个道理很简单，现在，１０＋３经济上融合的已经非常紧密，如果
在日本身上狠插一刀，其他的１２方也会真着吃大亏的。所以，在相当大程度上说，保护日本也是保护人民币经济圈。还有一点就是，想要日本彻底归附，光
有大棒是不够的，必须有颗胡萝卜。事实上，从胡主席访日开始，中国就开始走上从美国人手里接管日本的道路。也许许多人都不相信这一点，不过，时间会
证明一切的——要知道，日本是个极有野心的国家，想要他服气不是件容易事，别的不说，仅仅日本国内的右翼势力，就不好收拾——不是我们收拾，是日本人自
己收拾。所以，适当给点好处也是必须的。另外，中国现在极需的是在西线有所突破，这就需要东线能稳住。

    说到东线的稳定，不能不说金正日。这是我们在东线的定海神针。有了他不时的激化一下朝核问题，在整个东亚，好象没有什么问题不能让美国人坐下来
好好跟我们的谈的。有了朝核牌，我们才能压的住台独势力，才能离间美日韩关系，才能掌握东亚局势的主动。可以这么讲，在台湾回归以前，在日本彻底归
附之前，在把棒子磨成棒子面之前，朝核问题不会有真正的结果。朝核问题解决了，美国的西太平洋安全框架也就散架了。所以，朝鲜在26日申报核计划（不
涉及核武器相关信息）时还没忘记对着美国喊一嗓子：不能对美国所宣称的“对话”、“和平”抱有幻想！就是这样，炸个冷却塔还不忘记敲布什一笔银子，其实
，这点钱不算什么，让中东的弟兄们看看美国现在落魄到了什么地步才是目的。

    再说一下中俄关系，我们就分析西线：中俄关系，从战略层面讲是联合的，无论是对抗美国，还是消遗欧盟。但是，战术层面讲，中俄也是在斗争的。最
近发生了一件事足以说明这一点：俄罗斯石油巨头卢克石油公司要赶走中石油独吞哈萨克斯坦图尔盖石油公司。其实，对俄罗斯而言，让中国进入中亚经营无
疑是引狼入室，之所以从05年起允许中国介入，是被美国逼的没办法——再不让中国进对冲一下美国势力，整个中亚就全部染色了。尽管如此，只要有可能，俄
罗斯还是竭力的排斥中国的“经济入侵”。这一点我们必须心里有数。其实，在中俄欧美四方的斗法中，手里的牌最少的就是俄罗斯。他有强大的核武库，但是
除非在集体自杀时有用外，其他时候用不上；他的军力正在挥复，但比起巅峰时期来差的很多；最重要的是，他的外围战略空间被美国人挤压的太厉害，这导
致他全盘被动。当然，与中国和欧盟相对，他的军事实力还是相当可观的。对于俄罗斯而言，手里最关键的牌就是两张：能源和军力。军力是参与全球斗争的
后盾，能源是手里的长矛。只要俄罗斯打出能源牌，好象没有什么问题不能让欧盟坐下来跟他谈的。现在俄罗斯要扭转被动局面，实现全球战略突围，有两点
战略制高点是要打拿下的：一个是东欧隔离带（含东欧反导问题），有这个隔离带，俄欧关系始终走不近，同时，如果冲破了他，俄罗斯的外围战略空间将会
大大增加。为了突破美国人设置的这道防线，俄罗斯能打的就是格鲁吉亚牌，用格鲁吉亚来离间美欧关系，弱化东欧国家对美国的信息，进而消融东欧隔离带
。二是中东和平问题主导权。到现在为止，在巴以和谈问题上，俄罗斯还是坐在冷板凳上。只要上不了主席台，俄罗斯在中东的影响力就起不来。要想登上主
席台，就离不开中国的配合，离不开对伊核问题的控制权。说到这里，有一点要说明一下：最希望美国打伊朗的国家，就是俄罗斯。因为只要美国一动手，美
国霸权极有可能在短期内土崩瓦解，美国一败，会在地球上出现一个巨大的权利真空，无论是南美，还是中东，还是东欧，甚至东亚，这时俄罗斯就有机可乘
了——因为俄罗斯与美国经济的关联性很小，美国经济崩溃不会对俄罗斯产生太大的副面效应——如果美国面临着崩溃，极可能出现全球超级通货膨胀，这时的能
源价格极有可能一飞冲天，而俄罗斯不缺这个，甚至会因此而获利更多。所以，这也是美国人最担心的一点。

    现在，中东局面出现了许多新情况：叙以和谈、黎以和谈都有动作的迹象，哈马斯在加沙也站稳脚了。很显然，这是美国被动的表现。叙以和谈的背后，
是中俄欧美四方的斗法。黎以和谈更是如此。所以，在这里出现了一个大笑话：18日以色列表示希望与黎巴嫩举行双边直接和谈，促成两国达成和平协议。而
黎巴嫩总理府发表声明，要求以色列从萨巴阿农场地区撤走其军队，黎以之间没有必要举行双边谈判。黎巴黎总理府强硬的很，玩一言堂，如果黎政府真这么
有本事，那萨巴阿农场早收回来了。很显然，里面有道道。问题应该出在欧盟身上。对以色列有控制权的是美国，以色列愿意谈代表美国愿意让步，而黎政府
后面的是美国和欧盟，黎政府不愿意谈说明欧盟不想再开一桌，因为谈判桌越多，他让步就越多。为了搪塞各方，只好嘴硬一回了。不过，这不是办法。一个
靠自抬身价参与大国斗争的主，最后肯定捞不到多少好处，甚至把自己赔进去。中俄美都可以掀了桌子不玩了，只有他不行。要收拾他，还是用伊核问题。

    现在，斗争的核心在伊朗。无论是巴以和谈、伊拉克乱局还是阿富汗反恐，都与伊核问题直接互动，刚刚出现不久的科索沃独立及其派生出的格鲁吉亚问
题、叙核问题和叙以和谈及黎以和谈，甚至远一点的缅甸问题、台独问题、达尔富尔问题都与此问题密切相关。现在，在伊核问题的基础上刮起了一场超级风
暴，风暴波及了全球各国，所有的国家都在对自己进行重新定位，各国都明白，稍有不甚就有可能被撕碎，刚刚越南和印度遇到的金融问题只不过是有人小试
牛刀罢了。正是因为局势危险性，各方都异常谨慎，举个例子：沙特一方面和中国加强合作，一方面却屈服于美国增加了石油产量，但是又宣称油价上涨与产
能无关（事实也是如此），为什么？怕自己成为某几股力量交锋的对象——被撕碎了。所以，最近日本和欧盟在许多问题上表现的中规中矩，他们很清楚，自己
也有可能成为猎物。同样，中国也不是万无一失的，6月24日，温总理再次强调要确保金融安全，避免经济出现大的起落，社科院马上跟着报告入境中国热钱
13.6万亿，已超越外储，可以给大家足够的想象空间。当然，对于金融安全问题，可以这么说：关键时刻大闸一定能关的上，所以中国吃不了大亏，但是，小
的闸门处有人放水，所以我们肯定在吃小亏，这个问题一时半会难以根治。所以，不必过于忧心，保持警惕既可。站在中央的角度看，清除内鬼时不待我。

   既然分析了中国日本面临的空前威胁,也该分析一下欧盟和美国的压力才合适:欧盟现在是借力打力,专门钻空子，把中俄推在抗美的第一线，自己捡柿子。
其实，单凭他自己，因为军力不行，他的全球战略空间是非常有限的——这玩艺是打出来的，不是吓出来的。所以，只有美国腾出手来，玩欧盟很简单，欧盟都
是虚拟经济，虚拟经济的另一个名字叫信心经济——凭什么对你有信心？因为你有实力，没人敢惹你。所以，只要来自中俄的战略压力一小，美国在科索沃弄两
声枪响出来，接着乘势介入轰炸一回，欧元就再趴五年没问题。只要美国摆平了伊朗伊拉克把中东的石油牢牢的掐在自己手里，欧盟肯定得过着仰人鼻息的日
子。这些东西欧盟心里清楚的很，所以他和美国是面和心不和。应该说，欧盟手里的牌也不好：他的经济实力要比美国强，身子骨还没被掏空，就是军力这块
短板补不上；另外还有个大麻烦，就是表面统一实际上各玩各的，这一点是最要命的，举个最近的例子：意大利以支持美国“阿富汗事业”为条件换取“伊核七
方会谈”的门票，希望重走大国路，结果招来的第一个反对居然是德国——德法意三国都不齐心，剩下的小国就更不用说了，欧盟想当老大？做梦！从这里也可
以看出来，所谓的民主自由都糊弄傻瓜蛋的，只有集权才能带来国家强大——如果谁不相信可以去查查历史，从古到今所有“强大过”的国家，他只所以能“强大
起来”，最长身子骨的时候都是最集权的时候，只有集权才能让大家心往一处想，劲往一处使，一旦自由了，民主了，大家就各过各的去了，国力就开始衰败
了。中国如此，美国俄罗斯日本欧洲也都如此。
    下面再说一下美国。美国手里的牌是最多的，实力也是最强的，但是，身子骨也是最虚的。所以，这一次的资贷危机搞的他焦头烂额。现在，无论是中俄
欧，还是印日巴，都希望把美国人从世界霸权的位子上抬下来，只要把这棵大树砍倒，随便上去擗两根树枝子，都够自己烧几年的。所以，各方抗美都是很积
极的。这也注定了美国得向各方掏银子让步。不过，资本家们是会算帐的，怎么才能少掏点，怎么才能扭转局面再抢回来，这才是考虑的最多的问题。如果任
由各方抢，那美国根本撑不住。怎么办好？有重点的拉拢一家或者几家，然后打压其余的。当然了，拉拢的人越多，自己的压力越小，不过付出的代价就越高
，败得可能越快。所以，尽可能的少拉几家才是正理。从美国的许多表现看，特别是抛出G2构想。很显然，美国希望拿中国作挡箭牌为自己找到腾挪的空间。
不过，中国不可能和美国结亲家，只有抗美，才是中国的崛起之道，也是拉队伍的精神力量所在。美国经济面临的压力超大，现在他无法从国外吸血来重新吹
大自己的经济泡沫，只有换另一个极具危险性的办法来勉强维持局面，那就是增发钞票。增发钞票的办法可以是多印票子，也可以是减息。这样一来，流通中
的货币增加了，才有可能重新吹起泡沫。但是，吹起泡沫还需要一个条件——信心。如果人们对美国经济没有信心，那么有钱也不往美国投，反而会投到其他许
多国家去。巨额的货币流到了各国，必然引发各国严重的通货膨胀，当然，这个招用久了也会引发美国国内的通货膨胀加剧。搞不好会搬起石头砸了自己的脚
，让弱势的美元更加弱势。为了维持美元地位，狂炒油价是最好的办法，这样既可以刺激美元需要，又可以制造全球债务泡沫来给美国经济回血。近期，由于
高油价已导致部分国家付不起进口石油的帐单了，其中就有我们的小兄弟巴基斯坦。这个办法配合粮食武器，可以引发某些国家和地区出现动荡，从而为美国
找到借以翻身的机会。不过，这样的招也太黑了点。

    要想把油价和粮价拉下来，不是件容易事，但是，也不是办不到。

    首先要明白一点：粮食武器和石油武器（高油价）是相辅相成的：正是因为高油价的存在，才会出现高粮价。为什么这么说呢？道理很简单，粮食涨价了
是因为粮食缺了，粮食缺了是因为有人拿粮食去造燃料了，但是，如果不是因为石油价格高，粮食造燃料根本就无利可图——如果能把石油价格重新砸回到50美
元一桶，那所有开玉米造乙醇工厂的老板都得跳楼自杀。所以，只要能把石油价格拉下来，粮食价格就会掉下来，因为高油价和高粮价在世界范围内引发的一
系列问题，比如通货膨胀、贸易逆差，比如社会动乱、政权危机，大部分都可以解决，这个世界也能更和谐一点。

    怎么把油价打下来呢？插手中东和平进程。只有我们进去了，说了算了，能给产油的阿拉伯国家带来好处了，能保护他们的国家安全了，他们才敢往我们
这边站，只要他们听话了，我们就可以跟美国人谈了——要么你把油价拉下来，要么我把某国的出口原油改成用欧元计价——有本事你美国人把油价炒到10000美
元一桶，你们美国老百姓只要消费的起就可以。这样一来，可以激化欧美矛盾，让欧盟和美国自己想办法解决问题。只有这样，才可以打下油价。

    这样做还有一个好处，就是把欧盟重新变为美国最大的敌人，让美国把更大的精力投到欧盟身上——八成会让科索沃危机重新激化。这样可以减轻中俄的战
略压力，大家可以腾出手来更好的制造和谐世界。要做到这一点，我们在西线必须强力进攻。近期，叙以和谈、黎以和谈都开始了，加沙封锁也停止了，这都
是我们（中俄）强力进攻的结果。当然，距离我们想要的成果，还有一段距离 。说到这里，再说一个小插曲，25日美以刚刚决定支持在莫斯科举行中东问题
国际会议，马上以杰哈德组织从加沙地带用3枚“卡桑”火箭弹袭击以色列造成1人受轻伤为由，关闭了所有运输货物的加沙地带口岸，随后，以军方威胁说以军
在必要情况下可能对加沙地区采取大规模军事行动。很显然，这一次美国以对俄罗斯在中东让步为代价换取俄罗斯支持对哈马斯的困城。现在，就看俄罗斯的
了，相信普京不是个鼠目寸光的人。他应该非常清楚，这次中东和会能逼得美以同意在莫斯科开，离不开中国的密切配合。应该得到了欧盟的默认，因为无论
是美国，还是欧盟，对巴以和谈的主导权都看的比命还值钱。不过，美国人的做法也太露骨、太功利了。

    当然了，要想介入中东和平进程，还得内贾德老兄出力才行呀。
