# -*- org -*-

# Time-stamp: <2011-09-14 12:43:12 Wednesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:3

#+STARTUP: indent

#+TITLE:【金鸿评论】帝国梦碎“9•11”

#+AUTHOR:

#+SETUPFILE:~/dea/templates/level-0.org

[2011-09-10 11:06:58]




“9·11”事件无论如何都是美国历史上的一件大事。

“9·11”事件发生以前，美国的综合国力如日中天，一超独大；“9·11” 事件发生以后，美国新保守主义者开始推行反恐战略，先后打下了阿富汗和伊拉克。让美国新保守主义者们始料未及的是，这两个战场严重地消耗了美国的国力，世界格局也开始向着多极化的方向发展。全球金融危机发生后，改革全球金融体系、推翻美元霸权的呼声越来越高，美国从傲视天下的王者沦落到墙倒众人推的地步仅仅用了十年的时间。

在这十年里究竟发生了什么？我们有必要去发掘，去深思……

 

+ 美国新保守主义者的帝国梦

美国是一个帝国吗？在美国新保守主义者的眼里，答案是毫无疑问的。

小布什执政以后，切尼、赖斯、拉姆斯菲尔德、沃尔福威茨、约翰·博尔顿等新保守主义者主宰了白宫。切尼是美国外交政策决策班子的核心人物，也因此成为美国历史上最有权利的副总统。2002年，布什在《国情咨文》中把伊拉克、伊朗和朝鲜列为“邪恶轴心国”。布什大言不惭的说，美国将承担起领导世界的责任，对邪恶轴心势力、恐怖主义势力和其他挑衅美国的势力发动全面打击。从此以后，美国官方开始大肆宣扬“新帝国论”。

“新帝国论”主张，美国要利用当前无与伦比的实力优势用美国的价值观来改造世界，建立一种美国统治下的世界新秩序。随后，赖斯在《反恐战争与美国对外政策》在演讲中宣称，“9·11”事件后的世界给美国带来的不只是巨大的威胁，而且有巨大的机遇，作为世界上最强大的国家，美国应该把握机遇，主动出击，建立新的国际秩序。赖斯对美国新出炉的“新帝国论”作了权威的诠释。

“新帝国论”有四大理论支点，它们分别是“单极稳定论”、“先发制人论”、“主权有限论”和“民主和平论”，核心是“单极稳定论”。威廉·C·沃尔弗斯在1999年发表的《稳定的单极世界》一文中最先提出了“单极稳定论”观点。沃尔弗斯认为，苏联解体以后，美国成了仅存的超级大国，世界上再也没有任何一个大国或大国集团能够单独与美国抗衡，为争夺国际体系中的领导地位而导致世界冲突的情况也将一去不复返了，人类国际关系史上出现了未曾有过的“单极时代”。在这样的背景下，美国的实力越突出、越强大，在美国主导下的国际秩序就越稳定、越和平。当然，为了维护这种“单极”局面美国采取的所有手段(包括战争)都是合法的。2002年6月，布什在西点军校演讲时正式提出了“先发制人论”。在随后的《国家安全战略报告》中，布什政府正式将“先发制人”确定为美国的安全战略，美国推行了半个多世纪的“遏制威慑”战略被终结了。至于“主权有限论”和“平民和平论”，则是布什政府“先发制人”的借口罢了。

 

+ “9·11”，机遇还是灾难？

“9·11”事件给了美国新保守主义者实现帝国梦的充分理由。“9·11”事件发生后不久，美国就发动了阿富汗战争，推翻了塔利班政权。随后，美国又准备以萨达姆政府支持“基地”组织和拥有大规模杀伤性武器为由准备推翻萨达姆政权，这时，美国在联合国遇上了强大的阻力，因为欧盟的核心成员国法国和德国是坚决反对的。

法国和德国的反对主要是基于自身利益的考虑。欧盟能源需求的50%以上依靠进口，其中石油的对外依赖度更高，中东则是欧盟能源供应的最重要渠道之一。根据欧盟的估计，到2030年欧盟所需的能源70%要靠进口。如果美国打下了伊拉克，欧盟在石油进口问题上将不得不看美国的脸色，而且，美国武力解决伊拉克问题会引发中东地区的局势动荡，原油价格上涨是必然的，油价上涨会对欧盟国家形成很大的通胀压力，这对欧盟的经济发展是非常不利的。

法德等国家的反对没有能够阻止美国对伊拉克动武。2003年3月20日，美国带领着英国绕开联合国对伊拉克发动了军事打击。法国总统希拉克马上发表声明，对美国绕过联合国发动战争深表遗憾。德国总理施罗德发表电视讲话指出，发动伊拉克战争是一个错误决定，希望这场战争能够尽快结束。法德两国首脑在电话交谈中一致谴责美国在没有得到联合国授权的情况下单独对伊拉克采取军事行动的单边主义行径，双方一致强调联合国安理会的重要作用，认为安理会仍然是解决国际矛盾的惟一渠道，并表示双方在伊拉克问题上的立场是协调一致的。

萨达姆政权被推翻后，伊拉克局势的发展大大出乎了美国政府的意料，伊拉克成了恐怖分子的天堂。到“9·11”三周年纪念日时，美军死亡人数突破了1000人，伤亡人员8000余人。“虐囚事件”的曝光更是摧毁了美国的解放者形象，至于子虚乌有的大规模杀伤性武器更是没有找到。

美国的“先发制人”的单边主义政策导致了国际社会的广泛不满。2004年1月，联合国秘书长科菲·安南在世界经济论坛上指出，全球安全的危险不仅源于恐怖主义，而且源于反恐战争的方式，国际恐怖主义和反恐战争均有推翻行为准则和人权标准的潜在可能，而且还会扩大文化、宗教和种族隔阂。当年9月15日，安南更是直截了当的对记者说，美英两国发动伊拉克战争是非法的。

一场伊拉克战争让美国走到了全世界的对面。在“9·11”事件发生的第二天，法国《世界报》的马里耶·科隆巴尼曾写下过一句名言，今天我们都是美国人。可是，在2004年9/10月号的美国《外交》杂志上有一篇文章却说，现在看起来，我们都是反美的人。

应该说，出现这样的情况，当然是美国霸权思维和单边主义的必然结果。同样是恐怖分子，车臣恐怖分子的头号人物艾伊亚斯·阿克马多夫，就得到了布什政府的支持，在美国“避难”。美国庇护阿克马多夫自然是希望用车臣问题牵制俄罗斯。类似的例子比比皆是。得道多助，失道寡助，为了实现自己的帝国梦就如此的损人利己，怎么可能有朋友？

 

+ 伊拉克泥潭与次贷危机

网络经济泡沫崩溃以后，为了挽救美国经济美联储开始降息，用房地产泡沫替代股市泡沫，减缓美国经济的衰退。“9·11”事件以后，美国的航空、保险和旅游业受到了沉重打击，国外资金的流入也受到了严重影响，这时，格林斯潘为了挽救经济不顾一切地把利率降到了1%——1973年以来，美国的利率从来没有低于过2.58%。超低利率吹起了一个超级大泡泡，这就是次贷泡沫。任何资产泡沫都会引发通货膨胀，这是不可避免的。为了稳定经济控制通货膨胀，美联储从2004年6月开始连续加息，到2006年6月，利率提高到了5.25%，美国的房地产泡沫开始破灭，一年后，次贷危机爆发了。

在这期间，战后的伊拉克也成了美国政府的巨大包袱。2010年9月，奥巴马在电视讲话中承认，战争消耗超过了1万亿美元，这一数字远远超过了越战的6630亿美元。诺贝尔经济学奖得主斯蒂格利茨认为，如果把伊战对美国财政预算和经济的消极影响考虑在内，美国可能打水漂的资金多达3万亿美元。

背上战争包袱以后，美国开始实行弱势美元政策帐，美元指数从2002年2月开始下跌，美国入侵伊拉克时跌破了100点，2008年3月，美元指数跌到了71.15点的历史最低位。随着美元指数的下跌，原油和粮食等大宗商品的价格开始疯涨，涨势最猛、影响最坏的当属原油，其价格是从16元/桶的价格开始上涨的，2006年8月，原油最高价达到了77美元/桶，次贷危机爆发后，原油炒作更加疯狂，2008年7月原油价格居然达到了147美元/桶。油价的高涨给欧盟国家和日本经济带来了大麻烦，2006年第二季度欧元区就出现了逆差，原因就是欧元升值和油价的上涨。欧元区中间投入品的进口以原材料和能源为主，而中间投入品的出口以零部件为主，油价和其他原材料价格的上涨恶化了欧元区的贸易条件。

2007年3月下旬，次贷危机开始露出苗头，美国参议院拨款委员会批准了在2008年3月31日前从伊拉克撤军的计划。

 

+ 全球金融危机撼动了美元霸权的根基

2008年9月，全球金融危机爆发，2009年6月，美国作战部队撤出伊拉克城镇。

全球金融危机发生后，欧盟国家开始要求改革国际金融体系，在2009年4月的伦敦金融峰会上，欧盟力推的IMF成了世界经济的大管家。为了掩盖美国的金融问题，防止因美国经济快速恶化出现更多的美元霸权遭遇攻击的可能，美国财务会计准则委员会修改了会计准则，放宽了按公允价值计价的会计准则，允许金融机构“更加灵活”地进行资产计价。美国官方带头做假帐，暂时止住了美国金融形势恶化的势头。

修改会计准则这种技术性的手段是治标不治本的，它只能延缓美国经济恶化的速度，却无法阻止美国经济恶化的方向。2011年7月下旬，美国股市开始暴跌，维持了28个月的上涨势头止住了，OFHEO单独购房价格指数显示，房价已经跌回了2004年第二季度的水平，密歇根大学消费者信心指数跌回了全球金融危机爆发时的水平，失业率居高不下，通胀加剧，美国经济再次走到了最危险的时候。

随着美国经济形势的恶化，QE3的呼声越来越高，可是，美联储却再也不敢轻举妄为了。美联储推出QE1的时候，世界各国基本没什么反应，美联储推出QE2的时候，世界各国开始对美国进行口诛笔伐，如果美联储再冒天下之大不韪推出QE3，美元的国际储备货币地位将受到严峻挑战。

2008年秋全球金融危机爆发后，欧盟也深陷衰退之中，如今这一幕重演了。在美国经济二次探底的关键时刻，欧盟也遇上了大麻烦——欧洲债务危机升级了。9月7日，希腊1年期国债收益率冲高到了94.4%，10年期国债收益率触及欧元问世以来的纪录高位20%。受希腊债务问题的影响，欧元汇率连续下跌，9月9日跌到了1.363美元/欧元，这是半年以来的最低价。希腊该怎么办？欧盟该怎么办？

2011年8月6日，国际评级机构标准普尔把美国的长期主权信用评级由“AAA”降到了“AA+”。美元信誉遭到了严重质疑，欧元又是“跌跌不休”难当大任，这无形中给了人民币国际化的最好机会。

*2011年9月1日，由中国人民银行主办的首届中国亚欧博览会金融合作论坛在乌鲁木齐召开，人民币吹响了进军中亚和南亚国家的号角。* 9月2日，非洲标准银行发表报告推销人民币，说人民币将成为非洲一些国家的外汇储备货币。他们认为，南非和尼日利亚等国将成为首批接受人民币成为外汇储备的国家。9月5日，在北京访问的世界银行行长佐利克说，支持中国向非洲转移低端产业。佐利克曾担任过前美国副国务卿和高盛集团的常务董事。9月6日尼日利亚央行行长拉米多·萨努西在北京宣布，尼日利亚把人民币纳入外汇储备，尼日利亚也成了第一个把人民币纳入外储的非洲国家。9月8日，中英两国发布联合声明，同意加大中国对英国基础设施的投资，并确认伦敦作为人民币离岸交易中心之一。此前，菲律宾和马来西亚等东盟国家的央行和货币当局已经把人民币列为了官方储备货币，人民币已经在东盟迈出了国际化的第一步，现在，在美元和欧元都不被看好的情况下，人民币有了更大的发展空间。

2011年8月底，有美国新闻工作者透露，一些泄露的录像显示，“9·11”事件发生当天，袭击美国国防部五角大楼的巡航导弹而不是飞机。在2010年9月联大的一般性辩论中，伊朗总统内贾德就说过，美国政府内部为挽救美国经济和以色列策划了“9·11”事件，当时还遭到了奥巴马的强烈谴责，现在，“9·11”阴谋论又被美国的新闻工作者翻了出来，相信美国政府一定会别有一番滋味在心头。

“9·11”事件究竟是不是阴谋，正面反面的资料都有一大堆，有兴趣的人自可以去查找和判断。逝者已矣，生者当如斯。可是，今天美国的实力和地位已经根本无法与10年前相提并论了，甚至可以毫不夸张的说，美国衰败的速度不亚于双子塔倒掉的速度。从这个意义上讲，“9·11”事件无疑是美国的一场国家灾难。造成这样的情况，究竟是谁的错呢？是“单边主义”的美国政府，还是无孔不入、愈剿愈多的恐怖分子？相信每个人都有自己的判断。
