# -*- org -*-

# Time-stamp: <2011-08-18 19:52:12 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+title:【金鸿评论】新一轮的欧债危机开始了（之三）

[2011-08-17 21:22:34]


【金鸿评论】美国的经济形势很麻烦。从7月下旬开始，道琼斯指数疯狂下跌，OFHEO房屋价格指数也跌到了04年秋天的水平，这些都加剧了美国家庭的负财富效应，降低了美国老百姓的消费能力。我们都知道，消费是美国经济发展的主要动力，虽说消费包括个人消费和政府消费，可美国政府的总债务已占到了GDP的100%，远高于欧元区85%的水平，奥巴马需要做的是削减赤字而不是扩大消费，所以，消费这驾马车暂时还靠不上，美国经济想重振真是非常困难。

美国几十年来一直有贸易赤字，必须依赖海外资金流入来平衡，可是在今年5月，美国海外资本净流出675亿美元，这也是11个月来首次出现资本净流出。又一个危险的信号。

<<美国应该如何摆脱经济困局呢？>>

其实说到家，<<美国经济的问题就是一个字，缺钱>>。美国的失业率从第二季度开始一直维持在9%以上，再工业化短期内是靠不上了，靠制造业赚不进钱来，怎么办呢？<<抢>>！格林斯潘也说了，美国可以在任何时候印钞票还债。一旦美联储再度启动量化宽松政策，热钱将再度涌入各发展中国家，大宗商品价格也极有可能再度狂涨，一场新的金融风暴必将出现。

8月4日，阿根廷总统克里斯蒂娜要求拉美国家做好充分准备，防止发达国家向新兴市场国家转嫁金融危机。巴西总统罗塞夫和墨西哥财政和公共信贷部长埃内斯托·科尔德罗齐声回答，我们顶得住！在8月9日的国务院常务会议上，温家宝总理说，光有信心是不够的，大家必须防范金融风险的准备工作才行哪。

【金鸿评论】发展中国家不怕美国抢钱，欧盟国家可就头疼了。先是欧债危机蔓延到了意大利和西班牙，欧洲央行召开紧急电话会议后发表声明，实在不行咱就购意大利和西班牙的国债！接着，伦敦又乱套了，卡梅伦假也休不成了，急匆匆的赶回去摆平那帮野孩子。欧盟一看事要闹大了，不找个靠山不行了，正巧，朝鲜在发水灾呢。欧盟赶紧向朝鲜提供了20万欧元的水灾赈灾援助。

8月10日，美国官员放风，美国政府准备明确要求叙利亚总统巴沙尔下台。让奥巴马失望的是，欧洲人没吱声。于是，法国兴业银行可能破产的传闻又出来了，兴业银行的股票暴跌。这时，<<法债危机>>又被人念叨上了。不过，美元也遇上了一个不小的麻烦，就是金价连续暴涨。黄金是以美元标价的，黄金价格持续上涨意味着美元在不断的缩水，这显然对美元的储备货币身份非常不利。这时，以色列在修建定居点问题上变得更加强硬，在东耶路撒冷批准的新建住宅数量是层层加码，忍无可忍的巴勒斯坦阿拉伯人决定， 9月20日递交申请成为联合国会员国的文件！

<<一旦巴勒斯坦加入了联合国>>，以色列将被迫让出东耶路撒冷，退回到1967年战争前的边界线，美国和以色列的关系也将回到零点，以色列的“美国打手”角色也就当到头了，石油的美元结算制也就没人保护了，这对美元霸权的打击是致命的。唯一让美国人感到庆幸的是，内贾德没有在这个时候伊朗没有添乱，相反，内贾德说了一句让奥巴马心宽的话——研制核武器完全是浪费钱财和资源的行为。看来，站在伊朗背后的国家目前还不想让美元霸权成为历史。如此一来，美国可以放心大胆的攻击欧元了。

现在的局势，对欧元来说是非常微妙的，美国经济撑不住了，极有可能通过搞垮欧盟来转嫁危机，不过，如果欧盟能得到中国和俄罗斯的支持完成内部的政治整合则可极大的强化欧元的影响力，取代美元地位都是有可能的。所以，在这个欧债危机向着欧盟核心国家蔓延的关键时刻，要求发行欧元债券的声音又传了出来。

发行欧元债券，一方面会压低那些债台高筑的欧盟成员国（比如希腊）的利率，另一方面则会推高那些在金融市场拥有较高可信度国家（比如德国）的利率。很显然，这不是奖勤罚懒的好办法，可是，天下没有免费的午餐，在欧元生死存亡的关键时刻，为了共度难关发行欧元债券，各国必须交出部分甚至全部的财政主权，如果这种情况真的出现了，欧元区只有统一的货币政策没有统一的财政政策的状况就结束了。这种情况当然是某些欧洲领导人梦寐以求的，6月2日欧洲央行行长特里谢不就向欧盟各成员国首脑提出建议成立中央财政部来统一监管欧元区各国的公共支出吗？

不过，这件事跟吸收塞尔维亚加入欧盟一样，都是不得了的事情。一旦欧盟决定这么做了，就相当于决定跟美国摊牌了。所以，在8月16日萨科齐和默克尔16日会谈后两个人异口同声的说，目前发行欧元债券的时机还不成熟。不过，成立欧元区经济政府倒是可行的。

成立欧元区经济政府跟设立欧盟中央财政部有什么区别呢？只不过是把动作分解一下罢了。欧洲人真是想下水了，只不过怕水太深会淹死了就只伸出了一只脚
。

【金鸿评论】8月15日，奥巴马离开华盛顿，开始了为期3天的中西部“倾听之旅”据说，倾听完了之后奥巴马准备推出经济刺激政策。我们相信奥巴马是有耐心倾听的，可是，我们无法相信奥巴马能推出真正能提振美国经济的好政策。因为现在奥巴马正被共和党逼着削减赤字呢，减赤之后奥巴马手里可用的资金就少了，再想刺激经济从哪里弄钱呢，只有多向富人征税了，可是，共和党人已经表过态了，拒绝接受任何增税方案——众议员已经被共和党控制了。这可如何是好？美国的国债越发越多，光支付利息就是一笔不小的开支，可是，木有钱呀，巧妇难为无米之炊呀，杯具呀！
