# -*- org -*-

# Time-stamp: <2011-08-04 18:02:13 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+STYLE: <link rel="stylesheet" type="text/css" href="css/org.css" />
#+title: 十年大国斗争纵览



* 十年大国斗争纵览

  还是从中东三大热点问题说起吧。

爆炸连连的伊拉克乱局、持续不断的巴以冲突、越来越危险的伊核问题是相伴而生的。美国打下伊拉克的目的，一是攫取石油利益，二是保卫美元霸权；所以
，在打下了伊拉克之后，布什做的最重要的两件事就是把伊拉克国库里的黄金运到美国、废掉萨达姆时代伊拉克与中俄法德签定的石油合同。在打下伊拉克之
初，俄罗斯的实力还没有完全恢复过来，中国基于军队战斗力、经济结构、科技水平提升、干部队伍改造等核心层面的国家战略调整刚刚展开，都没有太多的
能力和资本在中东与美国抗衡；不过，经过几年调整恢复了元气的（与北约打完南联盟时相比）法德出现在了对抗美国的第一线。法德的做法有二：暗中支持
伊拉克反美武装，让打下了伊拉克的美国人无法获利；引爆伊核危机。通过这两步，法德希望以此迫使美国让步，分享伊拉克石油利益，推动欧元区向中东的
扩张。为了阻止欧元区的扩张，保卫美元霸权，美国回报法德的是持续不断的巴以冲突。中东三大热点问题由此全面展开。

本来，法德所代表的欧盟在中东是抗衡不了美国的，可随着中俄介入程度的增加，局面发生了质的变化。这也是美国在攻打伊拉克之初始料不及的——让我们再
把目光往前移几年，从美国入侵南联盟说起。

美国之所以同意法德的要求攻打南联盟，是冲着欧元去的。所以，在战争结束之后，欧元就垮了。这在战争之前是法德两国始料未及的，他们的打算是借美国
人的手把俄罗斯的影响力从巴尔干半岛挤出，实现欧盟内部经济整合，为做强欧元做准备。之后，美国人环顾世界发现，自己再无对手：昔日的老对手苏联解
体了，继承其衣钵的俄罗斯一厥不振；现在的对手欧盟也瘫软了，无法对自己形成威胁；潜在的新对手中国正在老老实实的韬光养晦，不足为虑。这绝对是美
国人扼住全球经济命脉——石油的最好机会。这时，小布什上台了。巧的是，发动战争的最好借口911来的恰逢其时。布什一鼓作气干掉了阿富汗的塔利班和伊
拉克的萨达姆，接下来摆平伊朗叙利亚，在中东全面推行大民主计划，就可以全面控制中东了。这还不是计划的全部——世界第二大油库中亚也应该在美国人的
手中。事实上，美国人对中亚石油下手是导致中俄轴心全面形成的最主要原因。为了削弱盟欧与中国的经济实力，伦敦-华尔街轴心狂拉油价，希望给中法德
经济带来严重的泡沫，可想不到的是，收效有限；想不到的是，一个本来穷得当当响的老对手——俄罗斯却借着高油价重新强壮了起来。

最让美国人想不到的是，中国换了领导人，胡主席全面调整了中国的核心战略——对外强硬，对内柔和，全面提升军队战斗力，加大研发投入，全方位调整经济
结构……一个二十多年来最好对付的对手重新变成了最难对付的敌人。中美斗争的主战场先后经历了一系列的转移：台海——朝核——伊核——巴以和谈——科索沃。具
体的说就是先用《反分裂国家法》捆住美国的台独牌，反手开打朝核牌——虽然朝鲜宣布有核是05年2月而《反》法通过是05年3月，但《反》法是对“（04年）
517最后通谍”主要精神的法律化，所以说《反》法在前、朝核在后。到06年10月朝鲜核爆后，中国成功主导东亚局势。其间中国又通过与伊朗经济捆绑成功介
入伊核进程。对伊朗国家安全作用同样重要的土库曼斯坦（俄）和土耳奇（欧盟）的态度相对摇摆，中国却能通过确保巴基斯坦通道的安全来保证伊朗的国家
安全，这无形中增加了中国在伊核谈判中的重要性。同时，由于巴基斯坦的坚定，也让土库曼通道变得更加可靠，很快，中俄主导伊核局势。

由于伊核问题主导权的存在，中俄在中东左右逢源：通过伊朗策应叙利亚，通过叙利亚支持真主党，通过真主党保护哈马斯，通过哈马斯这把尖刀破坏美国人
巴持的巴以和谈。哈马斯从一开始就是美国人的眼中钉。所以，哈马斯一上台美国就对其进行全面的经济封锁，后来在欧盟的经济支持下度过危机，美以又打
算用武力打垮哈马斯。在这危急关头，真主党挺身而出，袭击了以色列哨所，以色列立即掉头收拾真主党，黎以战争爆发（06年）。在中俄伊朗叙利亚的全面
策应之下，真主党成功顶住以色列的打击，一战成名。此战也帮助哈马斯度过了生存危机。过了不到一年，哈马斯武装占领加沙，这直接触犯了美以的核心利
益。本来，美国人可以通过控制着法塔赫的首领哈马斯来让巴以达成有利于美以的协议——这些协议将是建立在出卖巴勒斯坦和阿盟利益的基础之上的。在阿巴
斯当叛徒的时候，哈马斯却在通过武装斗争为巴勒斯坦、为阿盟争取利益，巴以和谈想结出果子就变得难上加难——如果有利于美以，阿盟就不满；如果不利于
美以，那怎么得了？在这样的背景下，除掉哈马斯再次成为当务之急；可是，一年前的武装行动失败了，再打能赢吗？没有把握的美以多次火力侦察均未得到
满意的结果，故尔一直未敢下死手。最后，甚至想出了饿死哈马斯的狠招，不过，结果是以哈马斯炸开埃及边境的隔离墙结束。哈马斯的斗争，让阿盟看到了
希望——并不是只有屈于美国的淫威之下才能生存。所以，通过哈马斯，中俄正在一步步得到阿盟成员的依附之心。

现在，巴以和谈成了美国人手里的烫手山芋：没有它，就没有美元的世界霸权（所以说巴以和谈是美国人在中东的最后防线）；有了它，中俄可以巧妙的收拢
中东产油国的人心。所以，巴以和谈的主导权美国丢不起，而又不好保。而对中俄而言，有无巴以和谈上的主导权，都能同样获利。

其实，不用说中俄，就连欧盟都一再的利用巴以和谈从美国人手里捞好处——中俄欧借着巴以和谈从美国人手中捞好处离不开在伊核问题上的主动权，这在伊核
问题刚刚展开时是美国人始料未及的。那时，美国人认为这是个机会——欧盟给了他收拾伊朗的最好借口。美国自认为有这个借口可以轻松的实现对伊朗先经济
封锁拖垮，后军事进攻拿下的战略目标，就象当年收拾萨达姆那样。可是，随着斗争的深入，随着中俄在谈判桌上角色的吃重，伊核问题越来越成了美国人放
血的地方。在苦撑了数年之后，美国人露出了希望进行战略转身的意思——通过情报部门放风，说伊朗已于三年前停止了核研究。

伊核问题不是菜市场，出入自由。来由你，去不由你！要想伊核问题平息，美国首先要做的就是从伊拉克撤军，这也是去年伊朗总统内贾德说“帮助美军体面
的撤军”的原因所在。上次美国人“体面的撤军”发生在越战时期，是尼克松登门求和的结果——历史又要重演了。可是，从伊拉克撤军对美国而言，绝对不是个
容易下的决心，因为以前花的本钱太大了——先在911中吃一把大亏，赚足地球人的眼泪，再扯起反恐大旗开始实施独霸世界两大油桶（中东和中亚）的计划。
美国先打的是阿富汗，之后才打了伊拉克。这样的做法不可谓不精明：如果直接攻打伊拉克，那么上合可以联合土库曼斯坦-阿富汗-巴基斯坦-伊朗，兵力从
东面直抵伊拉克，如果再得到欧盟通过土耳其从西面的配合，可以对伊拉克的美军形成夹击之势。为了避免这种局面的出现，美国先在上合的怀抱里楔入一颗
钉子——阿富汗，阻止中俄对伊拉克方面的渗透，西线的欧盟自然动作就小多了。同时，有了阿富汗这块飞地，下一步拿下中亚就有了前哨，事实上，这也是美
国能在中亚搞颜色革命连连得手的一个重要条件。通过这里的分析可以看出，如果从伊拉克撤军，就意味着美国的全球战略遭到重挫——足以与越战失败相提并
论，这是美国无法接受的。另外，如果撤出伊拉克，意味着伊拉克的石油再无美国人的份，一滴都没有，如果美国人不服气，尽管打回来！如果美国人愿意多
在伊拉克撑几年试试运气，不会有人有意见，反正伊拉克的石油在地下多埋几年也坏不了，只要美国感觉军费还没掏够，大兵死伤的还嫌少，那就悉听尊便。

不过，美军在伊拉克也撑不了几年了，撤军将是美国人不得不做出的一个选择。美国从伊拉克撤军之后，伊拉克国内就会出现一个权力真空——一场伊斯兰叶什
派（伊朗叙利亚）与逊尼派（阿拉伯国家）之间的伊拉克国家权利之争将会展开，甚至会激化成为伊斯兰世界的内部矛盾，这也将是美国乐意看到的。如何避
免呢？“和谐伊拉克”。其实，中国的布局早就做过了。去年夏天伊拉克总统塔拉巴尼访问中国，带来了一个号称中国人非常在意的石油“老合同”。结果，胡主
席眼皮都没抬一下，不要。出人意料的是，胡主席大手笔的免掉了伊拉克在萨达姆时代欠中国所有债务。那个老合同无疑是个李代桃僵，想把中国拉进伊拉克
泥潭，拆掉中俄联盟、甚至让欧盟敌视中国。中国人那是玩谋略的祖宗！这样的小把戏也拿的出手？胡主席免除伊拉克的债务，既是向伊拉克国内势力示好，
也是向阿拉伯世界展示——中国将保护他们应得利益，同时这个动作本身就说明，伊拉克的石油我们吃定了！不然谁会白白扔钱？在美军撤出伊拉克之后，在中
俄的主持下（欧盟也会参与），伊拉克各派达成和解，重建伊拉克，中俄欧分享重建蛋糕。美国从伊拉克撤军之后，美国人手中的阿富汗也将成为鸡肋，愿意
抱着就多抱几年，给塔利班的弟兄们解解闷也不是坏事。

美国从伊拉克撤军之后，还有一个更大的威胁，就是美元霸权的地位问题。其实，从中俄全面主导伊核进程之后，伊朗就开始推动石油欧元的使用，这是美国
人最害怕的——这也是布什出兵伊拉克的导火索。但是，石油欧元在中东遍地开花是欧盟梦寐以求的事情。正是因为欧元犯了美元的忌讳，再加上欧盟做了两个
大动作——政治一体化的加快和地中海联盟的强推，才逼着美国在多处被动的情况下依然强行启动科索沃独立来激化欧美矛盾、打垮欧元救急。当然，欧盟的所
作所为，也是被美国人逼的。

在这里，明确两个概念：欧盟主要指的是法德轴心，美国主要指的是伦敦-华尔街轴心，还有一个轴心是中俄轴心。伦敦-华尔街金融势力、法德为代表的实业
经济势力是欧美两大经济势力。从许多迹象来看，英国的金融势力和唐宁街并不是完全一条心：1990年，英国政府在伦敦金融城的反对声中加入欧洲货币兑换
体系之后，英镑就遭到了索罗斯的狙击，这就是一个明显例子。从本性上说，中俄轴心和法德轴心是同气连枝的。伦敦-华尔街轴心是亲金融的，惯用空手套
白狼的招势。他们牢牢的控制着美国。法德为代表的老欧洲国家则不然，以亲工业为主，他们为了摆脱伦敦-华尔街轴心的金融压迫才自立门户搞欧元的。99
年欧元被打软让法德轴心好不难受，后来因为美国全力“反恐”，法德轴心才重新缓过劲来。到07年，伦敦-华尔街轴心又开始算计法德轴心——这就是次贷危机
的爆发。很显然，次贷危机是伦敦-华尔街轴心几十年来制造的一连串泡沫中的最新一个，它们希望通过这个大泡沫能够狠狠的冲击一下法德轴心，所以大家
看到的是，次贷危机中注资救市最积极的就是欧盟。为了尽量减少所受冲击，欧盟强推政治一体化进程和地中海联盟，加快内部政治整合、稳定和扩张经济势
力范围，（希望）在中俄的配合下能让欧元出人头地。

在这一系列尖锐矛盾的对立中，科索沃独立浮出了水面。这一幕是非常有趣的：美国为了救美元霸权之急，必须先把欧元压制住，而压制美元的最好办法就是
从巴尔干下手，所以，美国力推科索沃独立。巧合的是，为了从经济上实现内部整合并扩张经济势力范围（至整个中东），欧盟也愿意通过让科索沃独立来达
到自己的目的。如此一来，支持科索沃独立是欧美达到各自目的共同手段——这个共同手段的背后，是水火不容的大矛盾。但是，支持科索沃独立是在打俄罗斯
的脸。科索沃是斯拉夫民族的发源地，精神层面的意义太大。如果科索沃在美欧的支持下独立了而自己挡不住，那尊严何存？这就象一个人年轻时就离家出门
打拼，终有一天富贵荣华到手了。在衣锦还乡时却发现自己的老家被人占了，自己的兄弟也被人欺负了，这时该怎么办？除了夺回来之外别无选择。

这个情况有点象“二桃杀三士”： “二桃”一个是“欧元取代石油美元”，一个是“斯拉夫民族的尊严”；“三士”则是美俄欧。这“二桃”成功的挑起了“三士”的全面
火并。但是，一旦拼斗了起来之后，“三士”就发现：谁都不敢、也不能后退一步：

美国不能退缩，因为退了之后就意味着美元霸权地位的消失。经济上早就快变成空壳的美国一旦失去了美元霸权必将很快垮掉，而没有历史积淀、由移民组成
的美国一旦经济崩溃了必将出现优势人才大量流失的局面，之后的美国将一厥不振。这是美国绝对不能接受的。

欧洲不能退缩，因为退了之后就意味着欧元重新回倒陪太子（美元）读书的位置上，受制于人的欧盟只能继续过着被美国人剥削与算计的日子，而在中俄全面
介入中东的背景下这样做意味着自己全面退出中东，沦为世界二流，这是不能接受的。

俄罗斯更不能退缩，且不说损失一块地盘，仅仅面子上的损失就丢不起。连自己的老家都看不住，凭什么重新称霸世界？

对三士而言，除了死撑下去都没有别的选择，他们的希望就是对手耗不住了先倒下，自己成为胜利者。当然，这又不完全是“二桃杀三士”——俄罗斯是中国的盟
友，中国会从侧面配合俄罗斯，确保俄罗斯得益；欧盟如果不与中俄作对，也不在被杀之列，一直以来它都是中俄全力拉拢的对象，但是，如果欧盟不识相就
没办法了；真正要杀的，是美国。

(我们真正需要防范的，是各种各样的阴手：针对主要领导人的暗杀、生化袭击、颜色革命……如果有必要，大可以牙还牙。须知：天生天杀，道之理也。)

围绕科索沃独立展开的斗争，符合俄罗斯的一惯风格（大棒横扫、强攻硬上），也符合中国的风格（四两拨千斤）。不过，由于中国没有陷入战场，胡主席将
会有更多的精力去从容布局，无论是国内还是国际。作为盟友的俄罗斯必将得到中国的全力支持。欧盟最后能得到什么，那就要看它的表现了。

至于美国，“（伊核+朝核）+（伊拉克+阿富汗）+（巴以和谈+科索沃独立）”六座大山压在身上，这个超级大国会落个什么结果呢？就看它是不是铁打的了。



