# -*- org -*-

# Time-stamp: <2011-08-04 19:11:06 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 【金鸿评论】国庆期间时事追踪（完）
  [2010-10-02 21:22:26]

  
     【金鸿评论】前面的大国斗争回顾写完后，有人并不认可我的观点，有些人呢不太相信，这都是很正常的。印象里感觉中国被人欺负惯了，今天一看我
说的中国要当爷了，自然不适应。我前面的分析到底对不对呢？如果跟接下来的时局合起拍了，那就是对的，如果走两岔去了，那就是错的。这两天又发生
了许多事，沿着前面的思路继续分析，看看对不对：

    这两天最热的新闻，除了嫦娥奔月，就是新华社解读中俄的二战声明了，今天，新华社的解读中直接点美国的名，提出了“1971年美日不顾中国的反对，
擅自签订《归还冲绳协定》，将日本从中国窃据的钓鱼岛及附属岛屿的管理权“归还”日本”一事。这时的中国，摆出了一副要解决琉球问题的架式。中国为什
么这么做呢？这么做是想得到什么？下面从四个方向做分析，一一来看：

    1、俄罗斯：在中俄两国高调发表二战结束65周年声明后，俄美国世贸谈判完成。美国为什么要在这个时候对俄罗斯让步？因为梅德韦杰夫访华以后，中
俄关系再次升温。现在正处在中美第三轮决斗的时间里，中国要求美国退出东亚，现在俄罗斯也来凑热闹，要配合中国把美国赶出东亚。

    中国与俄罗斯，对日本的态度是有很大差别的。中国希望美国慢慢退出东亚，退出之前可以吃穷日本，这样有利于中国的收编工作。同时，在美国退出
之前，俄罗斯是被美国挡在东北亚之外的。而俄罗斯希望立即把美国赶出东亚。他希望和日本加大经济上的往来，俄罗斯有资源，日本有技术，一合作不是
挺好吗？省得中国一头独大。同时，借着中国的手，还可以死死压住日本，多爽？

    所以，在中美第三轮斗法的关键时候，俄罗斯进来加了一把火，要把美国赶走，美国无奈，只能在世贸谈判上做让步，希望老梅高抬贵手——你不是希望
跟日本经济合作吗？我给你个补偿，日本这趟浑水你就别淌了。

    按理说，老梅这么趁火打劫一回，得到入世的回报也就可以了。可谁也没想到，他是逮住机会就不撒手，接着伸手要好处。所以，亲俄的乌克兰总统就
发话了，要推进政治改革，把橙色革命时通过宪法修正案给废了。要说这老梅也太黑了，估计奥黑这时肯定想揍他，就是隔的太远够不着。

    2、伊朗：现在，温总理又去欧洲参加中欧峰会了，中欧关系进一步加强。欧盟也在制裁伊朗的问题后撤。

      1日，欧洲数家能源巨头说，它们不会迫于美国的压力终止在伊朗的商业活动，将继续购买伊朗原油，只有在现有合同到期后才会考虑退出伊朗；

      2日，内贾德在会见到访的叙利亚总统巴沙尔，呼吁两国及地区各国加强在经济领域的合作；
      2日，伊朗国家石化公司董事长称，尽管伊朗遭到严厉制裁，但是中国、土耳其和马来西亚宣布准备在伊朗石化领域进行投资。

      现在，土巴伊联盟的内部经济联系在加强，马来西亚也要加强对伊朗能源领域的投资，欧盟也不想放弃伊朗石油，当然中国的投资自然是继续的，现
在，美国制裁伊朗的串联计划有完全失败的可能。

    3、巴基斯坦：在巴铁断了美国的粮道之后，塔利班又及时的烧了几十辆运油车，之后美军以两次空袭回应。在美国宣布航母三进黄海取消之前，巴铁的
要求美国应该不会答应，但是，美国宣布航母三进黄海取消之后，美国没有本钱不答应巴铁的开价。

    4、日本：在希拉里祝贺中国人民国庆节快乐之后，石原慎太郎喊出美国人不可靠、应该发展核武的口号。现在，日本也看到美国对局面没有控制能力了
，所以也想对美国耍耍威风。

     【金鸿评论】总的来看，现在的美国已陷入了全面被动状态。这时的中国，也跟着做了两个动作，一是温总理对希腊经济发展前景投信任票，二是新华
社解读中俄声明，要算琉球旧帐。现在，美国想解套，只有求中国了。中国并不希望马上把美国赶出东亚，允许美国用几年时间吃穷日本，所以，只要美国
对中国让步了，俄罗斯那头的压力美国可以轻松化解，欧盟那边美国想做什么也随便，只要不触犯我们的低线（欧元不能倒）就行了。

    中国的条件是什么呢？第一，航母三进黄海取消，第二，答应巴铁的要求，第三，对华输入先进技术。何去何从，美国人自己选择好了。（2日更新）

 ————————————————————————————————————

    《04年以来大国斗争回顾》一文五部分全发完了。看到回贴不少，选一部分有代表性的问题做集中回答，当然，仅限于与我的文章内容有关的问题。那
些张嘴闭嘴YY之类的贴子，我是不会回的：

    回复lhft21

    1、新能源：美国在核心技术上肯定比中国强，但不代表我们不能赶超，我们甚至可以想办法逼他们把技术卖给我们，就象今年七月让德国卖技术给我们
的那样；至于发电，你想过核能和其他的发电方式了吗？全世界的煤炭也就用个百十年吧？没有煤我们不就用电了吗？至于美国和澳大利亚的煤炭，澳大利
亚是可以收编的。至于美国，这个国家能撑几年都是个未知数，谁敢说十年后他一定不会分裂？
    2、澳大利亚铁矿石谈判的事：这里面肯定有内奸，不然怎么会抓了胡立泰等四个人？还有买两房债券，一开始肯定是不该买的。这里面同样有问题。如
果中国没有内奸，那绝对不是现在这个样子了。为什么说胡温难？手下的人，有贪的，有卖国的，这都是事实。清理这些人，是需要时间的，也是需要耐心
和宽容的，急不得。
    多换思想少换人，尽量统战，这条原则是正确的，也是必须的。现在不是毛主席时代了，有清廉的干部占几成大家都清楚，现在必须先团结他们，哪怕
是犯错的，有问题的，只要愿意悔改的就先团结过来，团结一切可以团结的人一致对外，打击美国，其他的等美国倒了再说。当年毛主席也是这样做的，不
管是流氓土匪黑社会，只要打日本，就是朋友，先团结起来，其他的以后再说。
    3、马英九：此人是个隐性台独分子，完全听命于华盛顿，你以为他会跟北京一条心？他怎么可能和大陆联手打日本呢？真是笑话。他是想用擦枪走火吃
亏来日本人坐实钓鱼岛，以此逼中国出手跟日本人开战。试想一下，如果马英九亏了，中国不吱声，是不是相当于宣布钓鱼岛归日本人了？中国不是不能跟
日本打，是那时还有比这更重要的事要办。你想想，08年5月出了什么事？汶川大地震，缅甸风灾。当时美国人法国人可是死活要进缅甸救灾的，中国也是准
备在缅甸开战的，缅甸方向可比钓鱼岛方向重要多了。中国同时应付这地震救灾和保护缅甸就够麻烦了，如果再在东海开一仗，中国受的了吗？中东方向还
管不管了？
    4、俄罗斯抛售美国债券：是打格鲁吉亚时候的事，中国没参与，这个都知道，不是秘密。如果参与了，或许就能把美国整死了。如果美国真倒了，只得
利最大的是俄罗斯。结果俄罗斯狂抛美国债券之后如何呢？油价砸到了30美元，中国趁机完成了石油的战略储备，如果还是140美元，那中国得多花多少钱？
这里面有没有妥协呢？我没有情报，但我相信华尔街没有傻子。两房之后虽然退市了，应该不会出大问题，美国再三承诺过的，毕竟中国没有落井下石。另
外，美国倒的太快不符合中国利益。为什么过去几年人民币高速扩张美国人基本不管？就是因为中国一方面在对它输血。如果中国象欧盟那样光抢地盘不给
好处，早就翻脸了。

    2008年7月17日证券时报报道：美国财政部数据显示，房利美及房地美共发行了约5万亿美元的债券及房贷担保债券，外资持有的债券总值约1.3万亿美元
，亚洲区占大部分。其中，中国持有最多，达3760亿美元；日本其次，为2282亿美元；俄罗斯753亿美元，排第三。香港及澳门政府或金融机构也持有195亿
美元及7.9亿美元。看这个数字可以看出，75%是美国人自己持有的。如果真让两房倒了，那美国人会亏的更多。所以，美国选择了政府接管。当然有人可能
说，美国会不会赖帐？这个当然可能，不过这也得看中国的本事了。没本事，这头没坑别的地方也可以坑，有本事，他赖也能让他吐出来。从现在的全球局
势看，中国不怕他赖帐了。

    我的分析全靠新闻，没有其他任何情报来源，更没有任何官方背景，我写东西，只是出于一个中国人的良心。

    5、关于美国算计欧盟的计划的问题：各国都有一套斗争计划，都是提前打算提前动手做准备，这个是正常的，自己过日子都提前打算，何况一个国家？
美国不仅仅要算计欧盟，更有算计中国的计划。为什么次贷危机爆发了？因为他在伊拉克的计划失败了，以至于搞乱了全部的计划。另外，他是希望中国放
开资本管制好接管中国金融业的，如果中国真的开放了，那他的问题也就解决了，可是，胡温坚决顶住没有开放，没给他机会。美国人的计划很好，可是计
划不如变化快。

    6、钓鱼岛扣人事件：这件事谁要说中国亏了，那可真是脑子有问题了。因为放了中国船长，日本有人拿着刀找菅直人算帐，国内政界也是群起攻之，日
本也因此出现大规模的反华活动，我们的大使馆两度遭袭，试想一下，如果日本人赚了，会有这么严重的报复情绪吗？真是事不关己，关己则乱。

————————————————————————————

     日本首相菅直人于3日中午乘专机离开东京羽田机场前往比利时首都布鲁塞尔出席亚欧首脑会议。临行前接受记者采访时，菅直人首相表示，没有与中
国总理温家宝进行会谈的预定。首相官邸昨日透露消息说，日本政府正在通过一定的渠道，希望在4日下午于比利时王宫举行的欢迎活动中，实现菅直人首相
与温家宝总理的会谈。政府关系人士说：“哪怕是站着说上几句话也好”。但是，菅直人首相的今日答复，显示温家宝总理拒绝了日本提出的与菅直人首相进
行对话或会谈的要求。

    3日报道称，美日将在美国总统奥巴马11月赴日本出席亚太经济合作会议(APEC)后举行联合军事演习，演练夺回钓鱼岛的作战计划，具有牵制中国的用意
。

    中国总理温家宝在访问雅典期间，宣布购买希腊国债等多项措施，挽救该国经济。

   由43辆卡车组成的声援加沙欧洲车队2日抵达叙利亚与土耳其交界的巴卜哈瓦叙利亚口岸。

    美国国务院3日向在欧洲国家旅游的美国游客发出警告，防范可能发生的恐怖袭击危险。美联社认为，这样一份旅行警告对欧洲经济的影响将极其深远，
因为在欧洲旅行、求学、经商的美国公民相当多，数以十万计。一旦旅行警告发布，不仅影响前往欧洲的美国人，还会潜在影响前往欧洲的其他外国人。

    巴基斯坦警方说，一北约运油车队4日凌晨在巴首都伊斯兰堡附近的拉瓦尔品第遭到武装分子袭击，28辆油罐车中弹起火，造成至少12人死亡、多人受伤
。4日的袭击是10月以来的第3起针对北约运油车的袭击，也是近期最为严重的一起袭击。

    【金鸿评论】眼看着日本人真要跪下了，奥巴马又出来打气，有用吗？

    中国对欧盟的保证是欧元不倒，要求是欧盟要负责策反以色列。欧盟果然开始出手了，这是对美国中东战略的穿心一剑，美国也对欧盟进行了一级警告
。看来，美国又要对欧盟下手了。

    这时的美国连乌克兰都顾不上了，还有闲心来和日本人一起牵制中国？真是笑话。

    巴铁兄弟好样的，就该这样下手，炸服他！以后跟朝鲜学着，东北亚有事美国得找朝鲜，南亚有事找让美国找你，不然怎么张嘴要钱花？至于中国，到
台下看戏就可以了，犯不着正面跟美国人打交道，那么累干嘛？

    此轮欧美交锋之后，东北亚也该变天了。（3日更新）

 ————————————————————————————————————————

巴基斯坦外交部发言人3日说，只有在安全状况得到改善，且该国民众对于北约的愤怒情绪平复后，才会重新开放北约向阿富汗运送军事供给的通道。

北约秘书长拉斯姆森4日对北约空袭炸死巴基斯坦士兵一事表示遗憾，并敦促巴基斯坦“尽快”重新开放驻阿富汗北约物资供给通道。

中国总理温家宝周日(3日)在希腊国会发表演讲时表示，中国支持欧元汇率稳定，不会减持欧元区国债，同时强调将支持希腊，希望通过加强合作帮助希腊走
出危机。

德国内政部表示，目前没有迹象表明德国面临恐怖袭击的直接威胁。

近日，有韩国官员说道，如果朝鲜想要韩国考虑重启朝韩两国边境旅游，朝鲜当局必须就“天安”舰沉没做出解释。

日本首相菅直人3日下午将出发前往布鲁塞尔参加亚欧首脑峰会，在启程前他表示“并没有计划与一同参加会议的中国总理举行会谈”。

【金鸿评论】先说巴铁通道：在断了他们四天的粮并且炸了三回车队之后，北约想起道歉起来。早干嘛去了？你以为道个歉就能解决问题吗？以后再犯怎么
办？做个保证，保证以后不再犯错就饶你。

再解释一下昨天说的一句话：“东亚要变天了”：

前面说过，这次中美决斗，目的是逼美国把日本和韩国交出来。这种说法其实有点笼统，美国交出日本和韩国，其实是一个过程，不是一天可以做到的。这
一次中美决斗，就是逼美国同意，开始一步一步往外交出日本和韩国。那么，交出日本和韩国的标志是什么呢？

这就要在朝核六方会谈上体现了。

去年4月23日，朝鲜退出六方会谈，理由是发射卫星被安理会谴责了。其实，这是朝鲜在找理由，真正的原因是美国当时准备对俄罗斯和欧盟做出让步，准备
逼中国同意制裁伊朗。这个时候对中国来说，最大的危险就是巴基斯坦通道被截断，所以，朝鲜马上退出六方会谈准备二次核爆。结果，在巴铁通道最危险
的时候，朝鲜引爆了第二次原子弹，之后，巴铁通道安全了。

之后，中美两国围绕制裁伊朗又苦斗了差不多一年，到今年的6月10日了通过制裁伊朗的1929号决议。这份1929号决议已经被中国改的不象样子了，奥巴马一
看，再这么折腾下去，100年也达不到目的，于是改变方法，挨个拉人串联制裁伊朗，欧盟、日本、韩国先后加入了制裁伊朗的队伍。

在1929号决议通过的第二天，中国就要求明确以色列的核身份，随后宣布二次汇改，以此逼迫美国退出东亚，美国坚决不退，于是中美之间就连续进行了三
轮决斗。到现在为止，决斗快结束了。

现在美国是败局已经。现在美国已无能力再对中国发起进攻，中国却通过推动欧盟策反以色列来对美国的中东战略进行致命一击。这时，急红了眼的美国开
始对欧盟进行一级警告——欧洲要遭遇恐怖袭击了。结果，人家德国人围着自家院子转了一圈后说，没事，门关的紧紧的，没看到有狼进来。人家不怕！看来
，温总理对欧元的支持还是起了相当大作用的。

接下来就看发了狠的美国人有没有本事把戏演完了。其实就算演完也是一样的结果，美国输定了。如果美国输了，会用什么方式对中国让步呢？

朝核六方会谈开谈，解除对朝鲜的经济制裁，朝美关系正常化。这样，东北亚经济一体化就可以上路了。中国收编日本韩国，离不开朝鲜半岛这个舞台。以
前东北亚经济一体化搞不起来，就是因为美国一直从经济上掐着朝鲜的脖子。现在，到了放手的时候了。当然，这个过程不是一天两天能完成的。就象朝鲜
第一次核爆以后，美国不得不把朝鲜从支恐名单上删除时一样，花了好长时间。

现在，韩国已经开始为重开六方会谈准备功课了。注意，这时韩国在天安舰问题上的态度是，要求朝鲜做出解释，比一开始咬住朝鲜不放的时候蹦的矮多了
。下一次再提天安舰事件的时候，估计态度会更好。态度好了才好做在一起谈合作嘛。这是提前做感情预热工作。与此同时，菅直人到比昨天硬实了。为什
么呢？他是顺着杆子爬，现在离美国在朝核六方会谈上让步还有一段时间，所以改善与中国关系的时间很充足，不必急于一时。现在奥巴马又拉了他一把，
要搞针对中国的演习，他堂堂一个首相，在低三下四之后仍没能得到与中国总理面谈的机会，能不借机硬一把为自己找回颜面？

当然，这一切也只是中国收编日本韩国的第一步，距离全面收编还早呢。收编成功的标志，是美国把冲绳军事基地交给中国。大家都知道，冲绳就是琉球。
只要把冲绳基地给了中国，那琉球问题就解决了。接着，东海划界还是问题吗？不过，这时应该会出问题，就算美国甘心情愿的交出来，日本也不会轻易答
应。这时，应该会以一场战争来解决问题。小日本就是这样，你不把他打趴下，他不认你当爹，打趴下了之后，东海划界的事就OK了（如果不和中国打一仗
，日本政府也没法给日本老百姓一个交待，打输了就什么都交待了，力不如人嘛）。如果中国愿意，那时还可以多接收几个美国驻日本的军事基地。

一战之后，必将崛起一个大国。（4日更新）

————————————————————————————————————

　国务院总理温家宝4日和日本首相菅直人在第八届亚欧首脑会议期间进行了交谈。温家宝重申，钓鱼岛是中国固有领土。温家宝指出，维护和推进中日战略
互惠关系符合两国和两国人民的根本利益。双方同意，加强两国民间交流和政府间沟通，适时实现中日高层会晤。

【金鸿评论】看到这条新闻之后，许多人又要泄气了，不是说好不见的吗？怎么看到人家搞联合军演就害怕了呢？

其实事实并不是这样。先看新闻中的两个短语,“在第八届亚欧首脑会议期间进行了交谈”,“ 适时实现中日高层会晤”，看晕了吧？都“交谈”了怎么还没“会晤”
？“交谈”的二位，可都是总理呀，怎么也算“高层”吧？

魔鬼就在细节中。

这次交谈根本不是正式的，如果是正式的会谈，肯定不会在新闻里光提温总理说了什么，不提菅直人说了什么，也不会只有文字不配照片。那么这次交谈是
什么性质的呢？

按照菅直人的说法，首脑峰会开完后，两人在在走廊里“偶然相遇”，这时走廊里“偶然有两把椅子”，“偶然有一名翻译”在现场，就这样两个人偶尔聊了25分
钟的天。这么一偶然，菅直人“站着说上几句话也好”的强烈要求被满足了。

大家都知道，之前菅直人为了能在布鲁塞尔跟温总理会面，专门派特使揣着秘信跑了一趟北京。结果呢，“哪怕是站着说上几句话”的要求当时温总理也没有
答应！我想，来我这里看文章的人都是成年人，应该能感觉到“哪怕是站着说上几句话也好”其实是在苦苦哀求。日本官方只所以把这句话放出来，就是为了
向美国表明，自己顶不住了，美国再不伸手拉一把，自己只能下跪了。

这时，奥巴马出手了，要和日本举行一场能牵制住中国的夺岛演习。接着，得到了奥巴马援手的菅直人脸上也有光了，开始一扫往日的颓气：中国总理很重
要吗？不见就不见呗，我还没有见他的打算呢！

我真的是太佩服奥巴马了，我想现在全世界99%的人都象我一样的：世界警察真的是天下无敌，真是太牛了，只不过轻轻拉了菅直人一把，他就立刻强硬了起
来。这种功效是伟哥绝对比不了的！

可是，时隔一天，戏剧性的一幕出现了，菅直人和温总理见面了。

现在问题出来了：菅直人不是说没有计划见我们的总理吗？为什么又见了呢？这次见面可不是正式会见，而是之前苦苦哀求而被拒绝的那种见面。既然有美
国人撑腰了，那就没有理由再满足于当时苦求不得的最低要求了吧？加码要求正式会见的要求不算高吧？如果中国不同意他可以不见嘛，反正有美国人撑腰
了。如果这时温总理真的答应跟他正式会见了，那菅直人绝对脸上有光了，菅直人一定会马上要求中国放了那个至今还被关得不明不白的日本人的，可是现
实不是这样。

在这次聊天中，双方也掰了一回手腕：当时温老爷子对菅直人说“钓鱼岛是中国的固有领土”，用“固有”一词直接去揭菅直人的强硬面具：你不是在和美国搞
夺取钓鱼岛的军事演习吗？你不是用行动证明你很强硬吗？那好，我现在说钓鱼岛是我们的，你敢当着我的面说不吗？如果连当面说不的胆量都没有，那在
背后玩这些花还有什么意思？

菅直人是怎么回答的呢？ “尖阁列岛不存在领土问题”。媒体的解读是，双方都没做出让步。如果媒体不是有意曲解，就是水平太差。两个人的话如果按下面
的方式来组合，会得出什么结论？

温家宝说了原则性的话：钓鱼岛是中国的固有领土。

菅直人强调：对，不存在领土问题。

有人可能会说，这是在曲解菅直人的意思。那我只能说，为什么菅直人不敢象温总理那样直接的表明态度：尖阁列岛是日本的固有领土。那时，谁还能曲解
他的话吗？他不敢正面表明态度，本身就是心虚的表现。

在菅直人丢脸的同时，还有个大人物也跟着丢脸了，这人就是奥巴马。这会儿奥巴马肯定要恨死自己了：我伸手拉他干嘛来着？我拉他是为了让他对中国强
硬一下的，可不是为了让他再次对中国低三下四的！我这不是犯贱吗？

对于温总理和菅直人的会谈，可以再做一下猜测：菅直人和温总理在会面之前，中国肯定事先给了日本可以谈一谈的暗示，不然，不会出现那么多的偶然，
此前温总理是明确拒绝和菅直人会面的，菅直人也说过没有见面计划的。至于双方心领神会之后，谈话时会谈到什么问题，双方其实也都心知肚明。普通的
商务谈判还要事先心里有数呢，何况国家领导人见面？菅直人很清楚，自己没有强硬的资本，如果这回强硬了，以后连站着说上几句话的机会也没有了。聊
天的结果就是双方同意加强两国民间交流和政府间沟通，并适时实现中日高层会晤。如果菅直人真的强硬了，温总理会同意“适时实现中日高层会晤”吗？

还有一点要说明，菅直人3日说没有计划与中国总理会见，只是在给自己挽回一点面子。他万万没有想的是，到连这点小动作北京都不允许，还是逼他自己打
了自己的脸——这回北京真把日本修理惨了。这次菅直人忍辱同意与温总理会谈，也充分表明了日本的态度，那就是以后就不敢在钓鱼岛上轻举妄动了。这一
点在接下来由日本外相原诚主持的关于“中国渔船事件”以及日中关系问题的记者恳谈会上充分的表现了出来。恳谈会内容很长，在此只选关键部分列出来：

1、前原大臣表示，外交是与一个国家的国力有重要的关系，两者是不可分离的。日本有一个说法，说是日本失去了20年。确实，这20年中，日本经济发展缓
慢，国民生活水准下降，日本在先进国家中的情况是最糟糕的。

2、日本目前最重要的课题是发展经济，还有申请加入联合国安保理事会问题。日本国力不增强的话，日本外交就不可能有大的进展。所以，经济不发展，外
交就搞不好，发展经济是重要的外交课题。

3、前原大臣说，经济外交是我的外交政策的基本。我们必须做好三件事：第一是与各国实现自由贸易。第二是保证日本的资源和粮食的安全，减少负面因素
。第三，扩大日本的技术出口。

4、前原诚司表示，尖阁列岛是日本固有的领土，在东海不存在领土纷争的问题。他同时指出，日本希望与中国就防止此类事件再次发生的协作体制问题，进
行对话和磋商。前原大臣指出， 1885年之前，尖阁列岛还是一个无主岛，我们经过10年的调查得出了这一个结论，因此在1985年，经过内阁的决议，正式把
尖阁列岛编入到日本的版图中。二次大战后，在旧金山条约的二条中，写到了日本归还台湾的问题。条约的第三条是有关冲绳的，冲绳属于美国的托管，其
中包括钓鱼。在1972年，冲绳归还日本时，尖阁列岛也一并归还给了日本。

【金鸿评论】先看一二两段：前原的态度是很诚肯的，也很无助，他的意思很明显了，日本非常担心将来可能被美国人彻底吃穷吃垮了。为了不被吃穷，日
本人希望有人帮他一把。

第三段是在对中国喊话，希望以扩大对华技术出口来换取中国的照顾。

第四段：日本人在钓鱼岛问题上求饶了，日本愿意以后在钓鱼岛规矩一点。并且摆出了自己的态度，钓鱼岛不是他从中国手里抢到的，而是美国人硬塞过来
的。如果中国真想要回去，那就找美国人。钓鱼岛当时是和琉球捆在一起送给自己的，所以，要解决就一起解决把这两个问题都解决了。这样做也是在将中
国一军，逼美国交琉球并不是现在要做的事，而是在美国退出东北亚以前的最后一件事，现在根本不适合解决。所以，他也希望中国以后在这两个地方不要
逼人太甚。

总得来说，今天的态度是相当不错的。这段时间没白揍他，真懂事了不少。接下来，如果日本人怕马上道歉赔偿被美国人修理的话，那可以当几天缩头乌龟
，等美国宣布航母三进黄海取消之后再道赚赔款也可以。

其实，变老实的不仅仅是日本人，还有更怕事的。今天菅直人和李明博举行了首脑会谈，为了让李明博替自己在钓鱼岛问题上说句话（也许这是菅直人这是
想告诉美国人对中国服软的不止他一个），菅直人说出了国家领导人绝对不该说的话：你们韩国对独岛是实际控制的，我们对钓鱼岛是实际控制的。你说钓
鱼岛是不是该算我们的？（新闻报道的原文不是这样，要含蓄一点）独岛问题是日韩之间的领土争端问题，现在堂堂首相都在假设领土应该归韩国了，可见
是多么的无助。菅直人是希望得到这样的回复：那当然了，现在独岛我们控制，就是我们韩国人的；现在钓鱼岛你们控制，也该属于你们的。如果李明博当
时这样说，可以坐实对独岛的主权。这么好的机会，他却没敢抓，只是打了个哈哈：“我认为，日本和中国之间的纷争是关系到东北亚和平的问题。很高兴看
到两国正在为和平解决这一问题做出努力。”之后李明博生怕被中国误解，又派人出来放话：“这个问题很敏感，（我们）甚至不知道该用‘尖阁列岛’还是‘钓
鱼岛’（称呼这个岛）。韩国政府不好具体谈及这个问题。”这句不知道该用尖阁列岛还是钓鱼岛，绝对是今年韩国人说过的最绝的一句话，至少读到这句话
时，我是笑喷了！害怕也不至于怕成这样呀。中国在东北亚，真成吃人的老虎了。当然，为了给美国人一个交待，日韩双双配合美国人对欧洲人下手了。

4日，韩国称二十国集团首尔峰会应完成IMF份额改革。

5日，继美国、英国和法国之后，日本昨天(4日)也警告旅欧日本人，要提防恐怖分子在欧洲发动袭击。据美国传媒报道，法国和德国的多个地标性建筑物，
都是恐怖分子计划袭击的目标。

美军4日在对巴基斯坦多山边境地区的导弹空袭中，打死5名德国籍武装分子。被空袭地点据认为藏有数名英国与德国籍武装分子。

由52辆卡车组成的声援加沙的约旦和海湾国家车队4日抵达叙利亚与约旦交界的纳西卜叙利亚口岸。

【金鸿评论】美国真被逼急了，要对欧洲人下手了。接下来会发生什么呢？我们拭目以待。

    文章最后说几句题外话，也是回答一部分网友的跟贴疑问的：
    各国都有自己的战略布署，长期的战略提前几十年就布局，比如毛主席的三个世界划分搞统战；中期的是提前几年就下手，比如高盛提前埋下希腊债务
危机的种子；短期的也是提前几个月就布局，就算是临时的反应，也比我们从报纸上看新闻快多了，因为所有国家的媒体都是受管制的，如果国家管不了媒
体了，那说明这个国家出大问题了，要大乱。所有大国都有庞大的特工情报网络和发达的信息处理系统，再加上各国官方之间也肯定会有我们老百姓看不懂
的、不知道的私下递纸条、打手势、换眼神等等行为。所以，等我们看到新闻的时候，事情其实各国都处理过去一段时间了。
    其实想一下就能明白，我们老百姓过日子都有个算计，何况一个国家？怎么可能养一帮蠢蛋？如果谁认为自己很聪明，可以看看自己的位置，再想一下
为什么你那么厉害却上不去呢？能上去的都是高手，至少在某些方面有过人之处，这是绝对不能否认的。
    一部国家机器的复杂，超出了我们常人的想象。所以，不要把任何一个大国的政府当傻子。自然，我写的这点东西，也就不存在泄密或者曝露我方行动
计划之类的问题，我要有那本事，我不进中央了？我只不过是个看客而已，比我水平高的人多着呢，只不过大家不知道罢了。
    还有就是我以前的文章的问题：我最初写文章的时候，水平很不怎么样，大家只要翻翻我最早的评论就知道。我自己也有自知之明。今年九月份以前写
的文章，除了那篇《国际金融战探密》，我一概没有留底保存。反正也没什么太多价值。希望大家辩证看待。
