# -*- org -*-

# Time-stamp: <2011-08-04 18:19:57 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+title: 国际金融战探秘

* 国际金融战探秘

  

** 【金鸿95】国际金融战探密(连载一)
[2008-04-20 18:18:13]

金鸿：喜欢这篇文章的朋友尽管转贴，只要注明作者即可。

****************************************************

    第一章、全球化的阴谋

    1、全球化思想的始作俑者——罗素

    伯特兰罗素是英国著名的哲学家、数学家、社会学家，也是20世纪西方最著名、影响最大的学者和社会活动家。他和西方经济学界的“一代宗师” 凯恩斯
、伦敦金融城的主宰者罗斯柴尔德等人都是英国剑桥大学的秘密组织“使徒会”的成员。

    罗素认为，科学和技术的无限进步造成了对于人类生存的威胁——只要主权国家能自由地发展其科学研究和工业能力，所有的国家都能造出核武器。因此，
罗素认为，要想世界保持安全就必须限制不发达国家获取工业技术，消除科技进步并将其置于严格控制之下，消灭国家主权，建立一个专制的世界政府。

    从某些方面看，罗素思想的出发点有些象道家的老子——“使有什伯之器而不用，使民重死而不远徙。虽有舟舆，无所乘之；虽有甲兵，无所陈之。”但是，
老子希望的是民风淳朴，天下和谐；他认为“损有余而补不足”是对的。可罗素就完全相反了，他信奉的是“损不足而补有余”。当然了，如果用老子的话来评价
罗素之流，就是“圣人不仁，以百姓为刍狗。”

    如何实现罗素所希望的“世界政府”呢？（国际金融资本势力的想法是）通过控制其他国家的经济命脉，进而控制他国的政权。这一点与马克思所推崇的“
经济基础决定上层建筑”观点很有异曲同工的味道。那么，如何控制他国的经济命脉呢？通过金融，让世界经济受控制的解体。以此摧毁第三世界国家的工业
发展，并通过对这些国家的经济实施致命打击，开辟出一条全球化道路，而所有国家的主权将在全球化中被消灭。

    这就是国际金融资本势力发动国际金融战目的。

    现在我们需要搞清楚的就是，国际金融资本势力是如何发动国际金融战的？他们使用的主要工具是什么？

    他们使用的工具，主要有两件：汇率和泡沫。如果把汇率比作强攻城头的军队的话，那么泡沫就是混入敌城的奸细。当然，也不能忘记石油武器的作用，
石油是工业的血液，是重要的战略资源，其作用不亚于粮食的国家稳定的作用，国际金融势力通过操纵油价的任意波动，疯狂的制造经济泡沫，掠夺他国财富
。另外，他们还大力宣扬所谓的经济自由化，特别是金融自由化；他们通过各种方式要求各国政府减少对经济和企业的管制，说什么管理经济要靠“市场那支
看不见的手”，以清除那些阻碍经济自由化的壁垒，以便他们更加容易的解体他国经济。

    近年来随着各种媒体的耳濡目染，大家基本了解了汇率武器的强大杀伤力。但是，汇率武器只是敌人进攻的“明枪”；除了明枪，还有暗箭。明枪易躲，暗
箭难防。“暗箭”是什么？就是泡沫武器。说泡沫是令人防不胜防的暗箭，是因为受害的国家中了暗算往往还懵然不知，甚至不但不以为害，反以为利。这才是
泡沫武器最厉害的地方。下面详细介绍一下经济泡沫。

    2、三种经济泡沫

    泡沫是指某一事物所存在的表面上繁荣、兴旺而实际上虚浮不实的成分。比如股市泡沫、房地产泡沫。通俗的理解，泡沫可以认为是某种财产（或者资产
、资本）价值与价格的背离。比如一支股票它的每股净资产是1元，在股市上被股民们追捧，价格炒到了10元，这就是泡沫——价格与价值已经背离了9元。既然
有泡沫吹大的时候，就有泡沫破灭的时候。比如在2007年1月时每股贝尔斯登的股票价格是170美元，但是今年3月贝尔斯登被大摩收购时每股股价仅为10美元
。从这个小例子就可以看出，泡沫往往意味着大涨大跌。

    当然，一国经济泡沫化后也同样会大涨大跌——这就是经济学中常讲到的所谓的经济周期，随着泡沫的吹起，一国经济进入繁荣期，在泡沫破灭时该国经济
又跌入了低谷。所谓的经济周期根本不是天灾，而是人祸。既然把经济泡沫搅起来时全民亢奋，认为遍地是黄金，在泡沫刺破的时候肯定会有人跳楼，做过山
车的感觉就是这么刺激。

    既然泡沫的危害这么大，那就有必要详细研究一下泡沫的种类：

    （1）投机泡沫

    投机是指利用市场上出现的价差进行买卖并从中获利的行为。买彩票就是投机行为，当然，炒股也是。关于投机泡沫，有一个非常有名的案例，就是南海
泡沫事件：

    所谓南海就是现在的拉丁美洲。事件发生在1711年。当时英国政府为了向南美洲进行贸易扩张专门成立了一家公司——南海公司。南海公司是英国一个特许
贸易公司，它是具有给南海贸易的特许权，垄断经营。不过在公司成立之后的8年里，除了靠向南美洲贩卖黑奴赚钱之外，几乎没干过盈利的事。在1718年时
英国的国债总额害达到了3100万英镑。为了迅速筹集资金还债，英国政府做出了一个决定，把南海公司的股票卖给公众。

    于是，南海公司就开始编故事，说我们在公司发现了金银矿、香料，非常赚钱。南海公司编造的梦幻般的利润前景，唤起了英国人的狂热，南海公司的股
价迅速飙升。据历史记载，从1720年3月到９月，在短短的半年时间里，南海公司的股票价格就从每股330英镑涨到了1050英镑。

    当人们为南海公司的股票而狂热的时候，英国还发生过一件事情。在1720年初，南海公司股价迅速上涨。但是，要想进一步推高股价，就需要更多的资金
涌向南海公司。然而，当时的英国正处在第一次工业革命的前夜，大量的民间企业同样需要筹集资本，它们就开始背着政府偷偷地发行股票，导致股票供应大
量增加，如此一来，南海公司股票上涨的动力就小了，这就损害了南海公司的利益。于是南海公司采用了不正当的手段，买通了国会的议员们，通过了一个法
案——《反金融诈骗和投机法》来阻止别人通过发行股票融资，这是典型的只许州官放火，不许百姓点灯。这个法案颁布之后，南海公司的股价进一步被推高了
，但是，在南海事件中存在着太多的腐败行为，很快就击破了南海泡沫。

    人们争先恐后购买股票，而当时的政府成员在股价高涨时卖掉了所持的股票。这些内幕人士的大举抛售，引发了持股人的疯狂抛售，南海泡沫破灭。当时
的英国财长就在南海公司的内幕交易中就赚取了９０万英镑的巨额利润，不过，丑闻败露之后，他被关进了英国皇家监狱伦敦塔。不过比他更命苦的却是那些
不知情的投资人，这其中还包括鼎鼎大名的科学家牛顿，牛顿赔了两万英镑。事后，牛顿伤感的写道：我可以准确地计算出天体的运动规律，但我却无法计算
出股票市场的变化趋势。——看来，头脑发晕的并不只有凡人。

    今天在股市上的炒股人，有几个是在坚持价值投资的？恐怕不超过百分之一。大家都是在“博傻”——在明知股票（其他投资资产品也一样）价格已被高估的
情况下还要买入，希望的是接下来还会有更“傻”的人以更高的价格接手。结果在泡沫破灭时自己变成了那个傻瓜。

    股市泡沫破裂时的危害是人所共知的，房地产投机泡沫的例子也不少，在这里简单看一下上世纪90年代的中国海南房地产投机泡沫，威力丝毫不小于股市
泡沫：

    当时在海南创造了一个世界纪录，平均80个人就有一家房地产公司。但是，这些公司基本上都不是为了盖房子，而是为了炒地皮的。当时的炒地皮绝对是
热火朝天，看几个数字： 1992年，海南全省房地产投资达87亿元，占固定资产总投资的一半，仅海口一地的房地产开发面积就达800万平方米，地价由1991年
的十几万元/亩狂升至600多万元/亩；同年，海口市经济增长率达到了惊人的83%，另一个热点城市三亚也达到了73.6%，海南全省财政收入的40%来源于房地产
业。

    在泡沫吹起的过程中，在四大商业银行的带领下，银行、国企、乡镇企业和民企的资金通过各种渠道源源不断涌进海南，总数不下千亿。几乎所有的开发
商都是在玩空手套白狼。开发商们把炒地皮赚到的钱装进自己的口袋，把还在图纸上的房子高价抵押给银行，再去炒新的地皮。投机性需求已经占到了市场的
70%以上，一些房子在图纸上就已经被倒了几遍手……炒作达到了疯狂的程度，据《中国房地产市场年鉴（1996）》统计，1988年，海南商品房平均价格为1350
元/平方米，1991年为1400元/平方米，1992年猛涨至5000元/平方米，1993年达到7500元/平方米的顶峰。短短三年，增长超过4倍。

    1993年6月23日，当时的国务院副总理的朱镕基出来宣布，终止房地产公司上市，全面控制银行资金进入房地产业；第二天，国务院发布了《关于当前经
济情况和加强宏观调控意见》，出台了16条强力调控措施，银根全面紧缩，海南房地产泡沫应声破裂，房价掉头砸下。

    这场调控的结果，就是给海南留下了600多栋共1600多万平方米的“烂尾楼”，18834的公顷闲置土地，800亿元的积压资金，仅四大国有商业银行的坏账就
高达300亿元。从1999年到2006年，海南省用了整整七年的时间，才基本处理完积压的房地产。去过海南旅游的人都知道，海南有一大怪，乞丐住别墅，全拜
海南房地产泡沫所赐。

    （2）、债务泡沫：

    债务泡沫有两种，一种是纯恶性的，这种债务是被人捏造出来的，本身就不应该存在，比如 1979年的“利率冲击”造成的全球发展中国家债务泡沫：

    1979-1981年间，英国撒切尔政府和沃克尔领导下的美联储推行极端的货币主义“休克疗法”，将利率提高到美国内战以来最高的水平：美元基本利率更高
达21.5%；英国把基准利率提高到 17%；欧洲美元贷款的利率也升至1980年初的20%。发展中国家的债务则由1973年5月会议时的1300亿美元，暴涨了5倍，到
1982年时更是达到了6120亿美元。

    利率是国际金融资本势力单方面调整的，欠债的发展中国家绝对不愿意接受这么高的利率——如果一开始就知道利率会上调到如此的高度，他们肯定不会借
这些债，但是，他们借的钱已经花出去了，现在还债还不起，赖帐又没实力，因为打不过美国，还没人出头替他们说话，这些发展中国家一下子就成了待宰的
羔羊。

    其实，当利率飚升的时候卡尔松（如果我没记错的话，他就是1982年诺贝尔经济学奖的获得者阿尔维德卡尔松）曾开玩笑说，“科学家们开发了一种强有
力的新式武器，它杀死人但让楼房屹立，它叫做17%的利率”。从卡尔松的这句“玩笑”里可以看出，这次提高利率行为是一个标准的“陷阱”。

    根据古老的英国法律，收取任何数额的利息都是一种罪行；这种高得足以“杀死人”的利率应该定什么罪行才合理呢？这些暴增的债务无疑是不应该出现的
，现实的债务远没有那么多，这就是泡沫——严重的、恶性的债务泡沫！

    这些巨大的债务泡沫直接导致了拉美债务危机，墨西哥总统波蒂略开始带头抵抗。1982年8月初，洛佩兹总统公布了“洛雷斯行动”计划，停止支付外债。
不过，其他欠债的拉美国家太胆小，没有人敢跟进。之后，波蒂略也被国际金融资本势力搞下了台。再后来，墨西哥比索对美元比价从1982年年初为12比1贬
到1989年的2300比1，墨西哥经济被有控制的解体了。与墨西哥一起被解体的，还有大批的拉美国家。

    众多第三世界国家的这一劫难无疑是悲惨的，作为第三世界领袖国家的中国也没有出来主持正义，只顾着韬光养晦。中国得到的回报是什么呢？就是1989
年美国在联合国制裁中国的时候几乎没有国家出来支持中国——除了巴基斯坦和古巴。中国不在关键时候给穷弟兄们搭把手，中国落难的时候自然也没有人管闲
事。

    与“利率冲击”所形成的债务泡沫相比，另一种债务泡沫就显得“善良”多了——个人消费信贷。

    消费信贷的本质是透支未来，透支未来的收入，透支未来的消费需求，透支未来的幸福生活。

可能在许多人眼里，个人消费信贷是件非常美好的事情，有了信贷消费，可以提前买车，可以提前买房……生活将变得无比美好。

    某些专业人氏更是不遗余力的宣传消费信贷：称消费信贷是经济发展到一定时期（从卖方市场走向买方市场）的必然产物，它的出现对西方国家的经济发
展起的了“良好的作用”，是消费信贷使西方国家多次摆脱了经济衰退。在中国，尽管“消费信贷刚刚起步”，却已经让上千万户人圆了住房梦。我们还应该改革
消费制度，促进消费信贷的发展，因为消费信贷是经济稳定增长的重要力量。对比发达国家，我国消费信贷还处在初级阶段，无论是消费规模和信贷品种，都
大有潜力可挖——在法国，1/2的家庭有债务，1/4的家庭靠贷款买房子；在美国，每年有6000万家庭用信用卡消费。我们还差得远呢。多好的主意，国民经济良
性发展，老百姓还得实惠！

    事实果真如此吗？真相总是可怕的。

    下面还是通过中国房地产泡沫的真相看一下消费信贷的给老百姓带来的“真正实惠”是什么吧：

大家都知道，房地产泡沫是形容房价远高于其实际价值这一事实的。今天中国的房地产泡沫已非常严重，我国房价跟居民收入的比例是世界最高的。但是，大
家是否知道，中国的房地产泡沫是如何形成的？中国的房价是如何涨上去的？

    可能有人会列举出许多原因：人多地少、房源稀缺，炒房投机，地方政府经营城市等等，其实，这些都是次要的因素，最主要的因素是消费信贷。如果买
房子不允许贷款，房价是绝对不会涨到今天这一步的，特别是在房价赶英超美的一级城市。可能许多人不相信。其实，如果不允许银行按揭、全部现款买房，
既使在北京，房价也不可能突破8000元/平方。现在北京的房价虽然高，但首付只有二成，剩下的钱是按月还的，所以，想买房子的人只要付的起首付，月收
入在支付了月供之后还能活得下去，他们就会买房。所以北京的房价能涨到16000元/平方，不就是因为购房人能付的起首付款吗？如果必须全款买房，他们还
能买得起16000元/平方的房子吗？绝大多数的买房人能掏得出的购房款，不会比首付款多多少的。

炒房者之所以炒房（无论是国内的炒房者还是热钱），是因为房价有上涨的空间，如果房价涨不动了，他们还会炒吗？地方政府经营城市（即拍地赚钱）就更
有限了，如果房价封了顶，开发商拍地时绝对不敢乱开天价，因为那样会推高建房成本减少利润。所以，如果真想打压房价，中央只要出台一条政策——购买第
一套房首付不得低于六成，中国所有大中城市的房价都会雪崩。其他的房价干预措施都可以去掉。

当然，如果允许买房首付降到一成，贷款年限延长到40年，房价还会疯涨。所以说，消费信贷让多少多少人圆了住房梦的话纯粹是骗人的鬼话！在没有消费信
贷之前，老百姓不是照样有房子住吗？还不用背债？其实，去年央行出台的第二套房首付不得低于四成的政策对房市的冲击就已将这一点表现的淋漓尽致了。
所以，中央对这条政策的操作非常小心。当然，基于经济稳定发展、稳步调整经济结构的考虑，不可能在短期内把首付比较提的很快。中国本已虚弱的经济体
质也实在受不了大的冲击，而且那样会杀伤无辜太多——会有大批的高价贷款买房人因为房价暴跌沦为“负翁”，不利于社会和谐。但是，大家也不用担心中国经
济被房地产开发商们绑架了——第一套房的首付比例可以五个点五个点的慢慢提，既能减少冲击又能稳定房价。当然了，房地产泡沫不仅仅是信贷泡沫，里面还
有投机泡沫的成份。

*******************************************************************************

以上是《【金鸿95】国际金融战探密（连载一）》，其余连载的链接如下：


** 【金鸿95】国际金融战探密（连载二）
   [2008-04-07 11:14:20]

   
    其实，消费信贷对经济发展和人民生活的恶劣影响早已在美国表现出来了。下面回顾一下消费信贷在美国的发展历程：

    消费信贷是从十九世纪初期开始进入美国家庭的，在此之前，美国居民的主流意识仍沿袭着崇尚勤俭、憎恶债务的思维定式（和中国人是一样的）。这种
观念来源于传统文化和宗教信仰。在牧师的心目中，债务是与疾病、恶魔联系在一起的“邪恶三位一体”。新教牧师向信徒推荐圣保罗的缄言：“不要欠任何人
的任何东西”（中国人也认为，寅吃卯粮的是败家子）。

    消费信贷方式起源于十九世纪初商家为促销住房、汽车和冰箱等耐用消费品而采取的分期付款策略。最初，消费者需先支付总价款30%的首付款，其余借
款在半年或一年内还清，以后延长至分年付清。到19世纪20年代，分年付款被按月还款的“轻松付款”方式所替代。在商家的诱惑下，越来越多的美国家庭为实
现住房梦、汽车梦而心甘情愿的自己套上债务的枷锁。从1920年至1929年，每个美国家庭实际债务从平均387美元增加到739美元。到1930年，全美汽车的75%
，家具的90%，洗衣机的80%，收音机的75%是采取分期付款方式进行销售。靠着“轻松付款”，老百姓可以奢侈的消费；但是，“轻松付款”的结果是精打细算、
勤俭度日。

    在1929年美国股市崩盘中，消费信贷对美国经济副影响表面了出来。从1929年到1933年，首饰、建材、汽车、家具电器的销售分别下降了85%、82%、78%
和69%，因为之前的信贷消费透支了太多的市场需求。不过，消费信贷的坏账损失很小，仅占全部贷款的1%。

    从这个例子可以看出，消费信贷对经济发展并没有多大的好处，恰恰相反的是，在危机暴发的时候，它对经济发展的副作用倒是表现的淋漓尽致。更关键
的是，真正在消费信贷中获利的，是贷款银行——你还得起贷款，他赚了；你还不起贷款，他收回你的东西。

    当然，在正爆发的次贷危机中消费信贷也有抢眼的表现：

    今年2月份，德国之声电台网站称，次贷危机引发的美国金融危机已经扩大到了信用卡领域，信用卡违约造成的巨大亏损即将公开化，从而使还未走出次
贷危机的美国经济遭受新一轮打击。

    今天的美国经济70%靠私人消费拉动，而私人消费却是靠借债进行的。现在，美国的信用卡债务已经积累到了9150亿美元，还有15000亿美元的汽车和其它
消费债务，100000亿私人抵押债务。美国消费者大把的花钱，不过花得不是他们自己的钱，而是信用卡上的钱。失业人群的不断增大，将使信用卡支付不了的
情况明显增加。次贷危机愈演愈烈，将会有越来越多的持卡人无力还债，从而必然导致美国经济的低迷。

    但是，美国人已经养成了消费信贷的习惯并深深的堕入其中，这就如同吸食毒品上瘾一样——继续吸毒必将走向死亡，戒毒又是生不如死、难上加难——告别
依靠贷款消费的经济模式，是美国经济无法承受的。我们还要走美国的覆辙之路吗？

其实，在消费信贷后面还隐藏着一个更隐蔽的险恶用心——国际金融势力希望建立一个由极少数人统治的世界政府，把全世界人民变成他们的奴隶，然后是对地
球上的所有人征收“世界税”。当然，套在人民身上的枷锁不再是铁链而是债务——要想把债务的枷锁套在世人身上，只能依靠人们主动的去信贷消费——还不起贷
款的时候，就变成了奴隶。从本质上讲，还是罗素的那个全球化思想。

    一个家庭如果想过宽裕无忧的过日子，就要做到两点，一不能赌，二不要借债。一个国家搞经济也是一样，要想经济发展平稳，一不能鼓励投机，二不能
靠债务拉动经济发展。用大规模信贷扩张刺激经济的方法是凯恩斯主义的观点，凯恩斯、罗素与国际金融势力本身就是穿一条裤子的。凯恩斯的这一观点被各
国政府广泛采用，之后的结果就是造成了浪费性消费品和服务的过度增长，这给各国经济的良性发展留下了严重的隐患，因为一个国家在扩大再生产的过程中
可以动用的资金是有限的，浪费性消费多了，长期性投资自然就少了。而且，这种靠浪费资源拉动经济增长、实现他们目的做法，还将给全人类带来灭顶之灾
，关于这一点，我将在第六章里详细介绍。

   （3）营销泡沫

    对于营销泡沫，可以这样理解，站在企业层面看，是由于行政和销售人员的过度增加造成的每单位实物产出的整体成本的提高；站在整个社会层面看，就
是每年新生产的物质产品总量和劳动生产率没有多大的提高的情况下，GDP却大幅增长了。

随着市场竞争的加剧，企业为了生存和发展，在营销方面的投入力度越来越大，2007年中国传统媒体广告花费总量为3120亿人民币，网络广告总量为70亿元，
同年GDP为220000亿人民币，仅广告一项就占GDP的1.5%。现在，许多行业的产品出厂价格连市场零售价的20%都占不到，也就是说消费者花费的80%都交给了流
通领域。这种情况合理吗？这叫营销泡沫。泡沫最大的好处就是可以把人民手里货币表现的财富缩水，从而达到掠夺人民财富的目的。不管是投机泡沫、债务
泡沫还是营销泡沫，都是如此。

    当然，按照某些精英的说法，投资利润在向消费领域尤流通环节转移——仿佛这是天经地意的事情。事实果真如此吗？这年头，多长个心眼是不吃亏的。

    流通领域指的是商品生产出来后，通过运、存、销到达消费者手中的中间环节。流通领域并不创造价值，只起到商品价值转移的作用。流通领域的确是商
品实现价值和使用价值的不可缺少的环节，但是，商品的价值是由生产过程中创造的。生产是根本，流通是枝叶，枝叶不可能比根本还重要吧？为什么会出现
这种本末倒置的情况？我们自然要深思其中的原因——这既不利于社会公平，也会影响社会生产效率。

    其实，这是由市场经济体制与生俱来的浪费本性决定的。随着从卖方市场进入买方市场，商家面临的竞争压力越来越大，为了生存，商家必须要把生产销
售出去，形成回款才能维持生存。但是，在买方市场上，所有的厂家都想销售产品，产品的差距本身就不大——所谓的产品差异更多的是消费者的主观感觉而已
（也是各厂家努力宣传的目的），实际上，所有合格的产品差别并不大，它们都是符合国家相关生产标准的（假冒伪劣的产品除外）；当然，每个产品都有个
合格率的问题，这对所有产品都一样，尽管许多知名品牌都在宣传自己的产品质量是如何的过硬，其实，差别远没有想象的那么大。

    为了争夺有限的消费者，商家不得不加大的营销环节的投入。这就象追女朋友一样，当只有一个男孩子去追求一个女孩子时，他所付出的代价不会太大；
一旦出现了大批的竞争者，再想追上这一个女孩子就得花大代价了，否则就追不上，但是，如果追女孩子的花销是借来的，等两个人结了婚后女孩子也得跟着
还债。

当然，过度竞争的出现是与投资者的信息不充分有关（都认为是个发财的好机会，进去后才发现竞争者一大堆，实际利润远没有想象的那么多）。这与政府对
市场的撒手不管（“自由竞争”、“依靠市场那支看不见的手”）有直接关系，其实这本身是对社会资源的极大浪费。

    当一个经济体中在流通环节投入过多的资金——这些都要算到商品的成本里——归根到底还是要消费者来买单的，这就形成了严重的浪费，同时也会导致商品
价格与价值的严重背离，这就是营销泡沫。

    在市场经济体制下，政府对商家在流通领域投入的过量增加是无法阻止的——这是在妨碍市场自由竞争，所以，在市场经济条件下，人们对社会资源的浪费
是无法避免的。

    此外，所谓“投资利润在向消费领域尤流通环节转移”里面还有一个阴谋。一起看一下：

    有一位前中国驻美国旧金山商务领事在2004年曾做过一个经济调查，他调查的是一件中国产的日用品的价格出口到美国全过程中价格的变化情况，一起看
一下：中国生产工厂1美元—中国出口商1.05美元—美国进口商1.4美元—美国大批发商1.75美元—美国分销商2.0美元—美国消费者4.0美元（甚至8.0美元）。

    这个价格表让我们看清了一个事实，什么叫血汗工厂！中国出口商只赚0.05美元，利润率只有不到5%，美国人在流通环节的收入是2.95美元，他们居然还
不用生产！这是什么？这是在吸中国人民的血！某些中国精英居然有脸跟着狂叫什么“利润在向流通领域转移”——你还算中国人吗？大家都不生产了，你创造个
利润我看看！你得喝西北风去！

    ——根本没有什么利润转移的问题，有的只是外国人在压榨中国人民的血汗！所以，对于这种血汗工厂，没有二话，坚决关停！行政手段不行就用市场手段
，把汇率提起来，逼他们卖技术，逼它们跟外国人学着卖品牌。

    现在美国从中国直接进口的产品大约是700亿美元，这是中国的厂家和出口贸易公司的总收入，总利润最多不超过30亿，但是，国外的批发商的收入是多
少？ 700亿。就算扣除400亿的管理和销售开支，还有300亿的利润，是我们利润的10倍！人家外国人当然有条件享受高福利，当然可以带薪休假、满世界的旅
游！

    很明显，在这个从生产到消费的链条中，便宜都让外国人占了，人家为了长长久久、光明正大的占便宜，自然要为自己找足理由——“投资利润在向消费领
域尤流通环节转移” 嘛！

   第二章、泡沫解体一国经济的最经典案例

  1、广场协议

    1984年，美国的经常项目赤字达到创纪录的1000亿美元，与各国贸易摩擦加剧。为此， 1985年9月，美国、日本、联邦德国、法国、英国等5个发达国家
的财长及央行行长，在纽约广场饭店举行会议，决定5国政府联合干预外汇市场，使美元对主要货币有序地下跌，以增加美国产品的出口竞争能力，解决美国
巨额的贸易赤字，史称“广场协议”。从此，在美国的压力下，日元一路升值，在几个月内由当初的250日元兑1美元骤增至120日元兑1美元。

    由于担心日元升值会提高日本产品出口价格，降低在海外市场的竞争力，日本政府开始把经济增长政策调整为内需主导型，日本央行连续下调利率，以降
低储蓄率、刺激消费，但是，由此引发的另一个后果就是货币供应不可避免的增长了。由于原有的产业结构下的日本经济增长已饱和，无法正确引导迅速增大
的货币供应流向；再加上货币汇率剧烈的变化（升值一倍）给出口生产商的沉重打击，各企业为弥补出口损失纷纷从银行借贷投机，于是巨额资金流向了股市
和房地产。

    需要指出的是，这种纵容投机行为的政策并不符合日本以往的产业政策。五、六十年代之前，日本政府是严格限制金融投机活动的，日本政策的政策是引
导银行信贷投向工业发展和基础建设领域，1985年以前日本工业的发展是举世瞩目的。这一段时期日本银行的贷款质量也是非常高的。1965年以前，日本150
家最大银行的贷款中，有65%投向了国民经济的生产领域，仅有6%向了非生产领域（指金融、保险、房地产和服务行业）；到1975年，日本最大的150家银行的
贷款中，依然有一半以上的贷款额投向了生产领域。1978年之后，在罗素停止工业化扩散的全球化政策指导下，日本银行的投资重点也从生产和工业领域转移
了出去，投向后工业社会的服务行业的银行贷款暴增。1985年时生产领域的贷款下降为总额的38%，不过，此时仍然高于投向非生产领域的贷款（贷款总额的
26%），日本经济深染沉疴是十年之后的事情。

    1978年，日本曾计划对拉丁美洲、亚洲和非洲发展中国家投资5000亿美元，用于发展铁路、供水和发电等基础建设，但当时的美国国务卿布热津斯基对日
本施加了强大的压力——阻止贫穷国家工业化是罗素全球化思想的精髓。日本的这个全球基础建设发展基金如果成功了，就是第二个马歇尔计划，既使不能帮助
日元成为新的霸权，也可以让日元与美元欧元鼎足而立。但是，日本并不是一个独立的国家，它处在美国的“保护”之下。日本顶不住布热津斯基的压力，被迫
放弃了这一大规模投资计划。

    美国逼日本签下广场协议只是解体日本经济的第一步。日元汇率的飙升严重打击了日本的出口生产业，削弱日本企业的国际竞争力；同时，美国通过限制
日本对第三世界国家投资，逼着日本因降息而涌出的巨额资金无处可去，最后只能吹起一个巨大的经济泡沫。此外，日元的升值让日本工业设备变得更加昂贵
，贫穷的第三世界国家就更买不起了，以便于达到罗素的“限制获取工业技术”的目的。国际金融势力一箭三雕。

    对日本政府在广场协议之后的数次下调利率，美国政府并不满意，还嫌日本利率不够低——里根政府的赤字政策也需要巨额的日元去支撑。1987年10月，纽
约股市崩盘。美国财长贝克向日本施压，要求日本银行继续下调利率，这样可以吸引东京市场的资金流向美国。日本政府低头了，把日元利率下调到了2.5%，
日本银行系统开始出现严重的流动性泛滥。这时，日本银行贷款投向的比重则完全颠倒过来了——投向非生产领域的贷款开始高于投向生产领域的贷款比重。不
过，这个选择对日本政府而言，实属无奈。利率下调之后，出现了的巨额货币供应根本无处投放——国内投资已饱和，投下第三世界国家美国（准确的说是国际
金融势力）又不同意，这些资金能流向哪里？

    2、吹起一个大泡泡

    巨额资金涌向股市和房地产，之后，日本的股市和房市泡沫暴涨。东京的股票年成长率一度高达40% ，房地产甚至超过90% 。1989年12月29日，日本股市
达到了历史巅峰，日经指数冲到了38915 点。房市的表现更是有过之而无不及。在日本的6大城市中，住宅、商业和工业用地的价格，每年以两位数上升，从
1970年的每平方米6千美元，猛涨至1991年的每平方米62000美元，上涨幅度高达10倍之多，创下世界前所未闻的记录。相比之下，纽约市区土地价格仅为每平
方米1200美元。到80年代末，日本的土地财富已经占国家财富总额的70%。那时有日本人狂傲的说：“卖了东京全部的地的钱，可以买下整个美国”。可惜，这
个狂妄的日本人不知道，日本的地价是被美国人逼着涨起来的。

    日本的经济沫泡能膨胀到这一步，与当时日本人的狂妄心态是直接相关的。因为在股市和房市投机炒作的基础都是信心。没有超一流的信心怎么会有超一
流的泡沫？从二战之后，日本一直在美国的管理之下，美国是日本的保护人，所以日本在一切事务上都要听从美国的安排，美国人说什么，日本人只能说“是”
。现在日本已成为美国最大的债主了，所以日本人有理由对美国人说“不”。有一个小故事足以说明当时日本人的狂妄程度：有日本人向美国政府提议，把加利
福利亚卖给日本人，以解决日美之间的巨额债务问题。理由很充分，加州离日本最近，亚裔居民最多，与日本贸易和投资往来也最多……加州已成为日本人的天
下，日本人应该把加州买下来。日本人很聪明，知道拿钱可以买到地，当年阿拉斯加不就是华莱士从沙俄手里买的吗？

    整个日本深深的沉浸在一片可以对美国说“不”的快感之中。


    

** 【金鸿95】国际金融战探密（连载三）
   [2008-04-08 09:13:45]

   
    3、日本经济泡沫的破灭

    日本东京股市崩盘的主要原因有四点：

   （1）由于地价过度上涨，个人买不起房，住宅建筑业前景堪忧；建筑用地价格过高，许多企业投资扩大的成本太高，难以承受；过高的地价还给日本从中
央到地方的城市再开发和道路建设带来了严重障碍。为了压制房价的上涨，日本政府不得不做出加息的决定。自1989年5月始，日本央行3次上调贴现率。1990
年8月，为防止海湾战争带来的油价上涨的冲击，日本银行将贴现率从4.25%一次性上调到6.0%。银行加息是给股市泡沫和房市泡沫带来了巨大的压力。其实，
泡沫吹大后破灭是必然结果，无论是股市还是房市。

    （2）广场协议签署之前，国际金融势力把巨额的热钱推入日本国内套利（关于进入日本的热钱数量，有一种数法是300亿美元）。在揣着热钱大量卖空美
元买进日元的投机者里面就有东南亚国家的老朋友索罗斯。这些热钱进入日本后，通过狂炒股票和房产获得了巨额收益，并在国际金融势力发动对日本泡沫致
命一击的前夜出逃。大笔热钱的出逃时抛售了巨额的资本品，大大增加了日本股市泡沫和房市泡沫的压力。

    （3）老布什出了狠招。1989年秋天，美国要求日本企业改变相互持股的做法，并提出了具体要求：将日本的银行持股标准由5%降低到2%；取消综合商社
不得持有制造业企业股份的限制；强化子公司持有母公司股份的限制。

老布什的这一招绝对是釜底抽薪：各公司相互持股是日本股票市场的主要特点，如果日本改变了这一做法，将使市场流通的股票数量急剧增加，股价肯定会受
挫；日本银行一向大量、长期的持有公司股票，并且不轻易抛出，经过长期的大牛市，银行所持股票（1985年以前就持有这些股票）的盈利非常巨大，一旦银
行抛售股票，日本股市泡沫承受的压力进一步增加了。

    （4）国际金融势力动用了股指期货这一威力巨大的金融工具，大规模做空股市，直接扎破了日本股市泡沫。从此，日本股票市场陷入了长达十多年的熊
市之中。

    在股市狂跌之后，1991年，巨大的地市泡沫也开始破裂，从东京迅速蔓延至日本全境。当年，日本六大城市的房地产价格就下降了15%～20%。房地产价格
的暴跌导致大量不动产企业及关联企业破产。在日本的房地产泡沫崩溃之前，日本的银行业发行了数额巨大的银行贷款用于土地投机，到1992年3月末已达到
150万亿日元，占当时银行总贷款额的1/3以上。在泡沫破灭后，银行也背上了巨额的债务包袱，重创了日本的金融业。

    4、克林顿的二次进攻

    1993年，克林顿政府开始了新一轮的日元升值攻势。

    1993年4月，刚上台的克林顿在日美首脑会议上说：“日元升值有利于日本削减贸易顺差。”日元升值的希望又让套利的热钱开始蠢蠢欲动。很快的，日元
兑美元从1993年初的1美元兑120日元上升到当年8月份的1美元兑100日元。克林顿对日元的穷追猛打招致了许多国家的反对。1994年7月，发达国家首脑在意大
利那不勒斯召开会议，试图改变日元汇率居高不下的状况，但由于美国不支持，会议没有达到预期目的，日元再次飙升，达到1美元兑96日元。1995年，日美
汽车贸易摩擦再次导致日元飞涨，4月份时的汇率涨到了1美元兑80日元。

    一个国家汇率的调整属于支出转换政策，它直接影响一国商品的国际竞争力，也就是说，它直接决定着一个国家出口型企业的生死存亡——连续、快速的升
值会对一个国际的出口型企业造成致命性的打击。举个例子，假定每辆车的出口价格是2万美元，日本的汽车生产商想把每辆汽车的生产成本降低1万日元是一
件非常困难的事，但是只要日元兑美元升值1日元，日本汽车的出口成本就上升2万日元，如果升值10日元，成本将提高20万日元。生产成本降得再快，也比不
了汇率上升带来的出口价格上涨快。所以，从1994年到1995年的日元急剧升值，导致日本的制造企业陷入了一片恐慌之中。由于日元兑美元长期升值，日本多
数传统出口产业，如化学制品、金属及金属制品、纤维及纺织品、机械机器等产品，对美国的出口数量持续大幅度下降；同时为了降低成本，不得不将生产基
地转移到亚洲其他国家和地区（这也对日元区的形成有一定帮助）。日本对美国出口最强势的汽车业，也从1986年的350万辆降低到1992年的180万辆。

    从广场协议前的1美元兑250日元到1995年的1美元兑80日元，日元长达10年的升值之路给日本制造业以近乎毁灭性的打击。用美国国际经济研究所所长巴
古斯登的话来说，美国就是要通过逼日元不断升值 “让日本用自己的锅烹煮自己”。

1995年6月，日本中央银行公布了银行体系的坏帐数字，该年度日本150家最大的商业银行一共拥有400000亿日元的坏债，折合4000亿美元；而据美国索罗门证
券公司的估计，日本银行体系坏债约为1000000日元，折合1万亿美元。而在1980年时，日本银行体系的坏债总额仅为10000亿日元，折合100亿美元。坏债率仅
为0.5%。十五年的时间，坏帐增长了100倍，国际金融势力的泡沫武器的厉害可见一斑！不过，有一点必须承认，连续十年的日元升值都没有让日元的汇率崩
溃（掉头下跌），这足以说明日本经济体之前是多么的健康。

    5、套在日本人脖子上的绳索——巴塞尔协议（资本充足性标准）

    1985年9月的“广场协议”导致日元急速升值，日本企业对外投资暴增，从1986年的220亿美元上升到1989年的680亿美元。1980年到1990年累计对外投资额
2271亿美元，是80年代前半期的5倍。尤其是在1988年到1990年期间，日本对外直接投资额占世界8个主要工业大国对外直接投资的27 .5%，超过英国和美国，
成为全球最大的对外直接投资国。在全球资产规模最大的10家大银行中，有7家属于日本。

随着日元的升值，亚洲各国对日本的出口剧增，对日本的经济依赖性增加；日本企业为了降低生产成本，纷纷向亚洲其他国家和地区转移生产基地；日元的强
势导致亚洲国家在对日贸易中倾向于用日元来作为结算货币，日元也因此在亚洲得以广泛使用。日元区在逐渐的形成，日本也具备了争夺全球话语权的能力。
这让国际金融势力非常的不舒服。

    为了有效地抑制日本资本的全球扩张，也为了打击正在形成的日元区，在1987年底，巴塞尔协议（资本充足性标准）出台了。该协议要求：凡是从事国际
业务的银行，必须将总资产中的自有资本比例维持在8%以上。

    一开始，美联储主席沃尔克把它拿到国际清算银行去寻求国际协调，结果遭到了联邦德国、法国和日本等国的强烈反对。于是，美国改变了策略，首先与
英国达成双边协议，并率先在两国银行的国际业务中实施了他们的标准——这无异于强迫其他国家签署协议，因为不签署协议就无法与把持着世界金融命脉的美
英银行做生意。日本无奈，只好在1989年接受了巴塞尔协议，但是，日本要求把银行账外资产的45%认定为自有资本，国际清算银行同意了日本的要求。

    巴塞尔协议对日本的银行的致命伤害在日本经济泡沫破灭后很快就显露出来。

    为了达到巴塞尔协议的要求，日本各银行在国际融资中变得越来越谨慎，对外贷款规模持续下降。1988年，国际银团的贷款规模为1260亿美元，1989年降
到1210亿美元，1990年降到1080亿美元。国际上的日元融资比例同时下降，1987年为10.8%，1988年为5.6%，1990年仅为1.8%。从这组数字可以看出巴塞尔协
议对限制日本资本规模的效果。

    在日本股市泡沫破灭后，日本各银行的帐外资产逐年快速下降，自有资本比例跟着下降，日本大型银行的平均资本充足率也一度已经降至了8%左右——正好
被巴塞尔协议勒住脖子，“国际著名的企业信用评级机构”就以此为参考不断降低日本金融机构的信用等级，如此一来，日本金融机构在国际金融市场的筹资成
本就提高了。为提高银行的资本充足率，日本的银行只好大规模压缩贷款，日本企业从银行贷款就变得越来越难，这又导致了日本企业经营业绩下降（甚至有
的企业因此而破产），日本公司股票又因此而下跌，股票下跌又使日本银行的账外资产减少（甚至因贷款企业破产而使坏帐增加），资本充足率又跟着下降，
日本银行只得进一步压缩贷款……恶性循环形成了。（有人可能会问了，为什么巴塞尔绳索套不死美英两国的银行呢？答案在第五章）

    日本政府为抵抗泡沫崩溃带来的经济灾难，刺激经济增长，实施了前所未有的大规模扩张的财政政策。如1992年8月投入110000亿日元的财政资金以刺激
经济增长，1993年4月投入了130000亿日元，1994年投入了150000亿日元。财政投入逐年增加，使政府债务急剧增长。但每次的努力都以失败告终——因为在巴
塞尔协议的逼迫下，日本银行出现了严重的惜贷行为冲销了日本政府扩张性的财政政策，阻碍了日本经济的恢复。经济虽然没有刺激起来，政府公债包袱倒是
越来越重，到2006年底，日本政府公债已达到83492亿美元，几乎是日本国民生产总值的1.7倍，这一比例在西方发达工业国中没有先例。以美国为例，美国联
邦政府公债占GDP比例还不到40%。日本经济有彻底崩溃的可能。

    巴塞尔协议在日本金融战败中所取的作用让我们知道了什么是国际游戏规则，它的作用又是什么。在一个公平合理假象之下，是对别国处心积虑的算计。

    6、两个尾巴

    里根主政期间，美国经济面临着两大难题：逐年增加的贸易收支逆差和急剧扩大的财政赤字。要想改变这种状况有两个选择，一是让美元贬值，减少经常
项目赤字，二是借款或吸引国外资本进入，以资本项目的盈余弥补经常项目的赤字。但是，让美元贬值不符合里根政府建立“强大的美国”政策——这是他上台前
的保证，更是当时国际金融势力的需要。这样一来，美国就必须借款或吸引国外资本。里根政府决定大量发行中长期国债。但是这些国债可以卖给谁呢？当时
美国国内的投资者根本没有这么多钱。只能依靠吸引国际资本。在当时，世界上最有钱的地方只有两个地方：欧洲和日本。

　　当时欧洲人正趁着美元地位动荡不稳的关键时刻建立他们欧洲货币体系，根本不可能为里根政府买单。如此一来，里根政府只有靠日本帮忙了。1983年11
月美日成立了货币委员会，加强两国在货币领域里的协作，日本成了美国最亲密的经济伙伴。在1976年时日本购买美国联邦债券总额只有1.97亿美元，但在美
日加强金融协作后，日本就开始海量的吃进美国联邦债券，仅1985年一年日本就购买美国债券535亿美元（那一年日本的对外投资总额为818亿美元）。80年代
中期，美国政府每年借债1000～2000亿美元，大部分资金是由日本提供。如果里根政府没有得到日本在金融上的支持，里根经济政策极有可能导致美元暴跌，
甚至垮掉。在日本的鼎立支持下，美国度过了有可能失去金融霸权的危险期。日本政府把储蓄和大量顺差在投在了美国，支持了美元，促进了美国经济的繁荣
。换来的是泡沫解体的下场。

里根的强势美元政策给美国老百姓带来了实惠，因为美元的强势意味着进口商品的廉价，但是，强势美元政策也带来了严重的经常项目赤字，到1984年时已高
达1000亿美元。正是这1000亿美元的美国赤字，才有了广场协议。美国政府就是这样感谢日本人的。

     在这一部分的最后，还有一个日元吹起的大泡泡需要说明一下：在罗素全球化思想的指导下，巨额的日元一部分流进了日本的股市和房市，剩下的另一
部分无处落脚的巨额日元，则流向了欧洲和美国，特别美国的房地产业。在此期间，里根政府大幅度解除银行管制，美国3000多家储贷银行开始了疯狂的房地
产投机，制造房地产泡沫。日本资金也大量涌入推波助澜。从1985年到1989年五年间，日本累计在美国购买不动产总额达23750亿日元。这是巨额日元吹起的
另一个大泡泡。在80年代末90年代初，美国的房地产泡沫破灭了。美国经济进入了新一轮衰退期，日元豪赌美国房市一败涂地。据统计，90年代初日本在美国
的投资亏损共有 7 000 亿美元，基本上相当于整个80年代日本对美国的贸易顺差。

    在日本“买下美国”的过程中，最有名的就是日本三菱土地公司收购纽约洛克菲勒中心的行动。1989年日本三菱土地公司以13.73亿美元巨资收购了纽约洛
克菲勒中心的14栋办公大楼，成为拥有洛克菲勒中心约80%股份的控股公司。在当时，洛克菲勒中心是美国的标志性建筑，美国媒体将这一收购行为称为日本
人“买走了美国人的灵魂”。泡沫破灭后，日本三菱土地不得不将洛克菲勒广场低价转卖，如果加上汇兑损失，三菱土地公司总计亏损880亿日元。据统计，日
本这一时期在对美国不动产的投资中，损失率在50%以上。如果我们站在美国的角度看这个泡沫，流入美国房地产市场的日元就是热钱，它们进来是来投机的
，国际金融势力是怎么对付这些热钱的呢？先制造泡沫、吹大，在泡沫大到一定程度日本人大量买入的房产还未脱手之前把泡沫挤破，日本人手里的房地产价
格大幅缩水，钱就全赔进去了。当然，这个方法我们不能用来打击进行我们房市炒作的热钱，因为这样做的杀伤面太大，如果房价短期内暴跌，会出现太多的
“负翁”，也会让我们的银行系统背上大笔的坏帐，对我国经济体的损害太大。

    “世界上没有一个国家比美国从前的敌人——日本更加忠实和积极地支持里根时代的财政赤字和巨额花销的政策了。甚至连德国都不曾那样对华盛顿的要求
无条件的满足过。而在日本人看来，东京忠诚和慷慨地购买美国国债、房地产和其它资产，最终换来的报偿竟是世界历史上最具破坏性的金融灾难。” 威廉恩
格在评价日本在金融的溃败时曾这样说过。


** 【金鸿95】国际金融战探密（连载四）
   [2008-04-09 10:54:15]

   
    银监会的那个《银行控股股东监管办法（征求意见稿）》的事是加入WTO的承诺，要给外资银行国民待遇的，早就签过了，现在我们必须信守承诺。当然
，在实际操作当中，我们多准备几双小鞋也就够了。无论如何，我们都要相信胡温，这是我们的希望所在。相信在胡温的正确领导下，我们会打赢这一仗的！

1999年中国和美国、欧盟签定的WTO双边协议中，我国银行业开放的条件是：中国加入WTO两年后，外国银行将可以与中国企业进行人民币业务往来。在准人后
五年，外国银行将可以与中国居民进行人民币业务往来。外国银行可与中国公司开展人民币业务，分支机构不受地域限制；五年后对外资银行实行国民待遇，
外资银行进行人民币业务不受地域限制，可吸纳人民币存款，可从事零售银行业务。加入WTO后外国非银行金融机构可提供汽车消费信贷融资业务。

****************************************************

    第三章、绑架黄金生命的劫匪

    现在人们都很熟悉一个词“美元霸权”，它指的是美元决定着世界经济、金融、货币制度运行规则，美国凭借美元本位制支配世界，美国不但可以通过过量
发行美元剥削贫穷国家，还可以剥削富裕国家。但是，美元霸权的建立是非常艰难的，直到布雷顿森林体系彻底崩溃之后，真正的美元霸权才建立了起来。

    1、美元霸权的建立过程

    美元霸权的建立过程，就是货币与黄金脱钩的过程。从古到今，黄金都是财富的象征，马克思在《资本论》中写道：“货币天然不是金银,但金银天然就是
货币。” 所以，要想把黄金与货币脱钩是一件非常困难的事情，国际金融势力先后做了四步工作，才把黄金与货币脱了钩。

    （1）金币本位制

    也称纯粹的金本位制，这种货币制度有三大特点：自由铸造、自由兑换、黄金自由输出入。在这种制度下，黄金即是货币。虽然此时也发行一定数量的银
行券或者纸币，但能保证按面值及时足额兑换黄金。

    在历史上，自从英国于1816年率先实行金本位制以后，到1914年第一次世界大战以前，主要资本主义国家都实行了金币本位制。1914年第一次世界大战爆
发后，各国为了筹集庞大的军费，纷纷发行不兑现的纸币，禁止黄金自由输出。一战结束以后，一些资本主义国家经济受到通货膨胀的影响很大，再加上黄金
在各国的分布已经失衡，很难恢复金币本位制。1922年世界货币会议在意大利热那亚城召开，会议决定采用“节约黄金”的原则，实行金块本位制和金汇兑本位
制。

    （2）金块本位制

    也称金条本位制。在该制度下，由国家储存金块；流通中的货币是银行券（纸币）；货币单位仍然规定含金量，但不再铸造金币；流通中各种货币与黄金
的兑换关系受到限制，不再实行自由兑换，但在需要时，可按规定的限制数量以纸币向本国中央银行无限制兑换金块。各国中央银行掌管黄金的输出和输入，
禁止私人输出黄金。这时实现了黄金与货币的第一步脱钩，黄金与货币不能自由兑换了。当然，不允许自由兑换不是不能兑换，在金块本位制下，银行券可按
规定的含金量在国内兑换金块，但有数额和用途等方面的限制。比如英国以银行券兑换黄金的最低限额为相等于400盎司黄金的银行券(约合1700英镑)，低于
限额不予兑换。法国规定银行券兑换黄金的最低限额为21500法郎，等于12公斤的黄金。意大利热那亚世界货币会议结束后，英国、法国了实行金块本位制，
而美国继续实行金币本位制，到了1933时，罗斯福以稳定经济为名，废除了金币在美国的自由流通和兑换，开始金块本位制。

    （3）金汇兑本位制

    又称为“虚金本位制”，其特点是：国内只流通银行券，不能流通金币；纸币不能直接兑换黄金，只能兑换外汇（即实行金块或金本位制国家的货币）。实
行这种制度国家的货币同另一个实行金块本位制国家的货币保持固定比价，并在该国存放外汇和黄金作为准备金，体现了小国对大国(“中心国”)的依附关系。
黄金是最后的支付手段。通过无限制买卖外汇维持金块本位国家货币的联系，即“钉住”后者的货币。国家禁止黄金自由输出，黄金的输出输入由中央银行负责
办理。这时实现了黄金与货币的第二步脱钩，在国内不能用货币兑换黄金了。第一次世界大战前的印度、菲律宾、马来西亚、一些拉美国家和地区，以及20世
纪20年代的德国、意大利、丹麦、挪威等国，均实行这种制度。

    （4）布雷顿森林体系

    1944年7月 1日，44国代表参加了在美国新罕布什尔洲的布雷顿森林举行有联合国货币金融会议（简称布雷顿森林会议）。确立了以美元为中心的国际货
币体系，即布雷顿森林体系。

    布雷顿森林体系的实质是建立一种以美元为中心的国际货币体系。其基本内容是美元与黄金挂钩、其他国家的货币与美元挂钩（即“双挂钩”），实行固定
汇率制度。在这时，其实仍然是黄金本位，只是把美元的地位提高了，美元爬到了“等同”黄金的地位，因为在1945年美国工业生产总值占资本主义国家的60%
，出口量占三分之一，黄金储备达200亿美元占三分之二（1948年这个比例进一步上升为四分之三），美国在政治、经济、军事等各方面都取得了绝对优势，
美国成为最大的债权国。这一切都为美元的霸权地位创造了特殊的有利条件。这是黄金与货币的第三步脱钩，黄金不再充当货币，但可以用美元“购买”。

    用假币换真币的日子开始了。

    2、三次主要的美元危机

    在这里，需要说一下英镑霸权的衰落：在1928年之前，国际金本位制实质上是英镑-黄金本位制，当时，英国是世界上最发达的国家，伦敦是全球贸易中
心和金融中心，90%的国际收支是以英镑进行的。有些国家的央行（比如印度），直接持有英镑而不是黄金，这使“英镑等同于黄金几乎成了天经地义的事情”
。

    1931年，英国第一次出现国际收支逆差，英镑地位也受到了猛烈冲击。从1931年初开始，黄金从英国滚滚外流，英国银行的黄金储备急剧下降，英镑与黄
金的挂钩关系面临着严峻的考验。当时正处于世界范围的经济危机之中，英国经济持续的衰退。1931年9月20日，英国宣布废除英镑金本位，并将英镑贬值30%
，以增加其商品在世界市场上的竞争力，改善扭转国际收支恶化的局面，抵制经济危机的冲击。英镑的贬值令许多外国央行损失惨重，有多家央行负责人被解
除职务。其中荷兰央行行长杰拉德威瑟林还为此自杀谢罪。

    在这期间，美国崛起了而英国的衰弱，所以英镑的地位也败落了。不过，尼克松时代的美国经济实力也衰弱了，为什么美元的地位没有跟着败落呢？因为
在20世纪30年代之前，黄金和货币是可以直接兑换的，所以，随着英国经济的衰弱，英国的黄金存量也大幅减少了，而美国随着经济的强大则拥有了世界上最
大存量的黄金，这是引起美元和英镑地位转换的关键。所以，国际金融势力要想保住美元地位的万代江山，就必须把黄金与美国脱钩，因为其他国家的崛起是
美国无法从根本上阻挡的。

    到布雷顿森林体系的建立为止，黄金与货币已先后进行了三步脱钩，只剩下最后一步了，就是1971年8月15日的尼克松 “新经济政策”：停止履行外国政府
或中央银行可用美元向美国兑换黄金，美元与黄金彻底脱钩。但是，完成这一步是非常困难的，此前共发生过七次美元危机。下面介绍一下比较有名的几次：

    （1）第一次美元危机

    1960年10月伦敦黄金市场价格猛涨到41.5美元/盎司，超过官价18.57%，美元大幅贬值，美元出现了第一次信任危机。这次危机的出现是因为随着大量美
元涌入欧洲和美国的国际收支状况恶化使美元贬值的压力增大了，从而动摇了人们对美元与黄金固定兑换比价的信心。这时，美元过量发行已经露出了马脚，
因为在马歇尔计划中美国实行“廉价货币”政策。为了实现在黄金与货币的最后一步脱钩，“廉价货币”还必须继续发行，但是，过量发行廉价货币必然会出现黄
金价格上涨，即美元贬值。如何暂时稳定住局面呢？打压黄金价格成了当务之急。“黄金互助基金”就在1961年11月出台了。这个基金是由美国和7个欧洲主要
国家建立的，它的主旨就是打压伦敦市场的黄金价格，以防美联储过多发行美元的事情露馅。该基金由参与国的中央银行共同出资，总额为27000万美元的等
价黄金，其中美国的出资占一半，德国3000万美元，仅次于美国。英法意都是2500万，瑞士、比利时与荷兰为1000万。该计划由英格兰银行实际负责执行，先
由它自己的金库中垫支黄金，然后月末和其它国家的央行按比例结算。“黄金互助基金”的首要目标就是如果金价超过35.20美元时，则坚决打压，35.20美元的
价格中包括了从纽约调运黄金的运输成本。“黄金互助基金”最初几年的运作非常成功，不仅没有赔钱，还狠赚了一笔，在头21个月中，黄金互助基金”的黄金
总额变成了13亿美元。当然，这里面有苏联的功劳，由于苏联1963年秋农业严重歉收，不得不大量抛售黄金来进口粮食。但是，毕竟纸里是包不住火的。

    （2）第二次美元危机

    20世纪60年代中期，美国扩大了侵越战争，美元过量增加（即廉价货币政策），又导致了人们对美元的信心不足，纷纷用美元兑换黄金。到1967年11月底
，“黄金互助基金”就已损失了10亿美元的黄金（不过他们收回了等面值的绿纸），接近900吨。此时的美元处在世界范围内的信心危机之中。

    1968年3月爆发了严重的第二次经济危机。为了把局面压下去，也为了给看好黄金的人一个惨痛的教训，打压金价，在华尔街高手们的指导下，美国总统
约翰逊拿出全部黄金，在伦敦黄金市场上疯狂抛售，目的是用超大数量的黄金供应，将金价打到35美元以下，引发黄金购买者的恐慌，并击穿他们的止损线，
造成更大规模的抛售黄金。等彻底打垮金价之后，再以低价逐渐买回黄金。该计划从1968年年初开始执行，结果让人大跌眼镜，黄金市场吸收了全部的黄金卖
盘，美联储总共损失9300吨黄金。1968年3月17日，“黄金互助基金”计划破产了。美国宣布，不再按35美元1盎司黄金的官价在自由市场上供应黄金，任凭黄金
价格自由上涨；但是，各国政府和中央银行仍可按黄金官价以美元向美国兑换黄金，这时，自由市场上的金价与黄金官价不发生联系了，这就是所谓的“黄金
双价制”。与此同时，美国与原黄金总库成员国达成了一个非正式的“克制提取黄金协议”，各国同意原则上不再以美元向美国大量兑换黄金，以减轻美国兑现
黄金的压力。

    （3）第七次美元危机

    到1971年，美国的黄金储备仅是它对外流动负债的15.5%。1971年5月，第七次美元危机爆发了。8月15日尼克松政府宣布实行“新经济政策”，“对外停止履
行美元兑换黄金的义务”，实现了美元与黄金的最后脱钩，此举也从根本上动摇了布雷顿森林体系。

    这时出现了一个问题：当初建立以美元为中心的布雷顿森林货币体系是因为美元可以兑换黄金，为什么尼克松宣布美元与黄金脱钩之后各国仍然相信美元
、持有美元，并且允许美元把黄金踢出货币系统、夺取了黄金的生命呢？

    3、欧洲美元

    在这里面，有一个劫匪，绑架了黄金的生命，它就是欧洲美元。正是由于欧洲美元的存在，各国不得不接受美元拥有黄金生命这一既成事实。下面详细说
明：

欧洲美元是指存放在美国境外的各国银行、主要是欧洲和美国银行欧洲分行的美元存款，或是从这些银行借到的美元贷款。“欧洲”是泛指美国境外的意思，并
非指地理上的欧洲；当然，之所以这样冠名是因为大量的境外美元存款诞生于欧洲的缘故。与欧洲美元相伴而生的，就是欧洲美元市场。

    欧洲美元市场的出现，首先得益于马歇尔计划。第二次世界大战后，欧洲经济恢复乏力，社会主义思想影响很大，亲苏的左翼势力发展迅速。为了防止苏
联势力向西扩展，美国就开始帮助欧洲加快经济发展，给欧洲注入启动资金，因为欧洲其他的东西比如人、技术、市场体制都不缺；当然，援助欧洲也对美国
大有好处，因为大部分贷款要买美国的产品，这对美国经济的发展是十分有利的，于是美国国务卿马歇尔让国务院起草了一份“复兴欧洲计划”，史称马歇尔计
划。这个计划于1947年7月正式启动，并整整持续了4年。在这段时期内，西欧各国总共接受了美国包括金融、技术、设备等各种形式的援助合计130亿美元。
结果大部分的援助都被西欧公司用来购买了美国货，仪器和棉花46%，煤16%，钢材和铝材19%，只有14%用于追加企业资本。

    其实，马歇尔计划还有一个更加重要的好处，就是从那时起，西欧国家习惯了使用欧洲美元。当然，欧洲美元市场的形成，还有两个推波助澜的重要因素
，一个是英格兰银行借尸还魂，一个是美国政府瞒天过海。

    （1）英格兰银行借尸还魂

    1954年４月，新成立的埃及政府要求英军撤离苏伊士运河，英国不同意，双方谈判破裂。这时美国站了出来，公开支持埃及，因为美国想把英国挤出中东
。在美国施压后，英国不得不在埃及撤军的问题上让步。7月10日，英国和埃及的再次展开谈判，这次美国代表也列席了会议。7月27日，英埃达成协议，约定
英军于1956年6月25日以前全部撤出埃及。之后，虽然英军撤出了埃及，但苏伊士运河仍属于万国苏伊士运河公司的财产，而万国苏伊士运河公司的两大股东
是英国和法国。

    1956年7月26日，埃及革命胜利４周年时，纳赛尔总统发表讲话，宣布将对苏伊士运河实施国有化，这个消息震惊了全世界。英法两国就把苏伊士运河问
题提交联合国，但没有达成什么结果，于是英法开始秘密策划武力夺取苏伊士运河的计划。为了解决兵源问题，英法又邀请以色列参战。以色列也早已视纳赛
尔政权为发中钉，三国一拍即合，一致对埃。 1956年10月底，第二次中东战争爆发。英法认为自己选择了一个出兵的好时候，因为当时欧洲正好发生了匈牙
利事件，苏军出兵匈牙利，美苏的冷战又达到一个高潮。英法认为美苏忙于冷战，无暇顾及埃及。但英法两国失算了，苏美组成了统一战线，双双强烈要求英
法两国立即撤军。美国还施压，如果英法不撤军，美国就要停止经济援助，甚至通过联合国进行经济制裁，并大举抛售英镑，导致英镑汇率浮动并贬值了15%
，引发了1957年的英镑危机。在美苏两大国的压力下，英法无别选择，于11月6日宣布停火；12月，英法军队全部撤出埃及。英法军队撤退后，以色列也不得
不撤回到1948年停火线以前的位置。第二次中东战争的结果是：埃及获胜，英法的在中东的殖民地消失，中东由美苏控制。

    从这一段历史事实可以看出，美国抛售英镑只是个手段，是为了把英国挤出中东，并不是为了打击英镑。事实上，美联储在许多地方还非常需要英格兰银
行的配合。但是，英格兰银行依然打起防止英镑被抛售的旗号给英镑关了禁闭。为什么？其实，英格兰银行是借着防止英镑被抛售这个“尸”还帮助受自己控制
的美元建立新霸权这个“魂”。英格兰银行加强了英镑管制，提高再贴现利率，并严禁英国商业银行向非英镑区的客户提供英镑贸易融资，禁止银行用英镑放款
。这就逼着英国商业银行去开展美元存贷款业务，促进了欧洲货币市场的形成。有了英镑帮忙腾位子，美元想不称霸都难了。

    （2）美国瞒天过海

    各国之所以信赖美元，信赖欧洲美元，是因为美元可以直接兑换黄金。而欧洲美元的大量出现，意味着美国黄金库存将不敷使用。事实上，到20世纪60年
代，欧洲美元的数量已大大超过了美国黄金存量按35/盎司计算的价值。这也是导致数次美元危机的根本原因所在——所有的人都怕自己手里的美元成了美联储
打的白条（可后来这个结果还是出现了）。

    现在矛盾出现了：把黄金与货币脱钩、用可以任意发行的美元向全世界人民征税是国际金融势力的既定方针，又怎么会改变？但是，这正是各国所害怕并
且全力避免的，这也是1962年法国率先退出“黄金互助基金”，并把手中的美元从美联储换成黄金的原因。如何继续实现自己的既定方针呢？国际金融势力使出
了瞒天过海的招数：

    1963年，美国政府开始对购买外国政券的美国居民征收利息平衡税，此举号称是限制外国人在美国发行证券的，因为征税后外国人在美国发行证券的成本
就抬高了。但是，这个做法又促使美国银行将其大量资金转移到设在欧洲的分行避税，美国工商企业也纷纷将其海外收益留存境外，不再调回国内，大量美元
外逃。

    1965年，美国政府实话了对外信用限制方案，此举号称是限制美国银行对外放款，并要求美国公司自动限制对外投资的。但是，这个做法又迫使许多借款
人到欧洲美元市场寻找贷款来源，这样反而刺激了欧洲美元市场的发展，大量美元被吸往欧洲。

    美联储Q条例对美国银行存款利率上限进行了管制，欧洲美元则无利率上的上限限制，使银行存款对投资者的吸引力急剧下降，促进了美元存款向欧洲银
行转移；美联储对国内存款有存款准备金制度的限度而欧洲美元没有，使欧洲美元的经营者可以降低经营成本、提高利润，大量美元流向欧洲；

    还有一个非常重要的因素，就是长期以来美国银行存款利率低于西欧国家，在20世纪60年代末期时差额居然高达5%，美元不往欧洲跑才怪呢！

    在国际金融势力的精心安排和调度下，终于让欧洲在第七次美元危机爆发时积累了巨额的欧洲美元（678亿美元），此时，美国的黄金储备仅102亿美元，
欧洲美元终于具备了绑架黄金生命的能力——这时如果所有的欧洲国家要求用手中的美元换成黄金，他们将损失84.5%的财富。同时，美国政府也会破产，在这
样的情况下，谁敢保证美国政府会不赖账？事实上，尼克松政府也已经明确的表示，自己赖账了！尼克松不是宣布“对外停止履行美元兑换黄金的义务”了吗？
当初各国接受美元就是因为美元能兑换黄金，现在美国又不认这个帐了，天下还有比美国政府更无赖的吗？这不是给其他的国家打白条吗？但是，论实力，西
欧不是美国的对手，而且，苏联对西欧虎视眈眈，西欧各国也需要美国保护它们，不能和美国撕破脸。

    就是这样，西方各国仍然不愿意接现这个现实。怎么办？谈判！谈判的结果就是1971年12月达成了的史密森协议。其实，不用想谈判的内容，光看谈判时
间就知道各方争吵和激程度了——谈了100多天。史密森协议是美国不得不与其他西方国家达成的一个妥协性方案。主要内容是：美元贬值7.89%，黄金官价升至
每盎司38美元，西方主要通货的汇率也作了相应的调整，并规定汇率的波动幅度为不超过货币平价的上下各2.25%。但是由于此后美国的国际收支状况并未好
转，1973年1月下旬，再次爆发了新的美元危机。美元再次贬值，幅度为10%，黄金官价升至42.22美元。美元第二次贬值后，外汇市场重新开放。抛售美元的
风潮再度发生。从这里也可以看出，没有人适应、也没有人愿意接受美国的白条，国际金融势力最后采用了石油武器，才彻底巩固了美元的位置。

    事实上，如果没有欧洲美元的存在，尼克松宣布美元与黄金脱钩之日，就是美元被踢下神坛之日。如果有谁认为美联储养了一帮傻瓜、他们制定了错误的
政策导致巨额美元出逃才导致布雷顿森林体系崩溃的话，那他才是真正的傻瓜（或者是揣着明白装糊涂）！美联储管不住美元出逃，为什么能管得了黄金出逃
？为什么美国在第七次美元危机时彻底切断了黄金与美元之间的联系？不就是为了保住自己手里的黄金吗？他们清醒的很。他们知道，黄金才是真正财富的化
钱，美元只不过是他们印制出来的一堆绿色的纸片而已，如果需要，想印多少就印多少。

    在黄金与货币彻底脱钩以后，为各国廉价货币政策打开了方便之门，各国央行可以通过任意印刷钞票制造通货膨胀来掠夺本国劳动人民的财富；廉价货币
的泛滥推动了资本过剩的出现，导致了世界范围内商品投机的暴增（炒作油价就是其中一例）；金本位的去除更是为浮动汇率制的通行开辟了道路，从此汇率
可以在人为操纵下任意波动，由此也卸开了国际金融投机的闸门，使国际性的长期投资和国际贸易风险剧增；当然，最重要的是，从此以后，国际金融势力可
以动用汇率杠杆轻松的掠夺别国财富，压垮别国经济了。



** 【金鸿95】国际金融战探密（连载五）
   [2008-04-10 10:05:08]


   
第四章、伦敦-华尔街轴心征战世界的道路

1、控制美国

国际金融势力要想征服世界，首先必须掌握一个强大的政府工具，以此作为征战世界的工具。他们盯上了美国。

美国的历史就是国际金融势力与美国共和势力斗争的历史。华盛顿建立美国之后，这两派的斗争就开始了，共和势力一派的代表人物是杰弗逊，他代表的是人
民大众的利益；国际金融势力一派的代表人物汉密尔顿。在美国建国的最初100年里，共和势力占上风。在1901年时，代表共和势力的麦金利总统被暗杀。此
事标志着国际金融势力彻底控制了美国，之后的肯尼迪属于国际金融势力的窝里反。在共和势力与金融势力的长达一百多年的斗法中，先后有七位美国总统死
于金融势力的手下。

从某个角度看，一个国家就象一个人，不同的党派代表这个人不同的性格，共和势力代表着一个人的朴实面，金融势力代表着这个人的狡诈面，当美国这个人
还小的时候，他的狡诈面就表面了出来——华盛顿本人就对金融势力让步了——标志性事件就是美国第一银行的成立，长大后，这个人肯定是狡诈无比的，三岁看
老就是这个道理。现在的美国政府完全是国际金融势力手里的傀儡。

当然，需要说明的是，“共和”是相对于“世袭”来说的，美国是共和制的国家，中国也是，在这一点上，中国和美国是一样的。不要认为美国是民主制的国家，
事实上，美国的先贤们（共和势力）对所谓的民主从来就不感冒，对此，可能许多人都不相信，所以在此我不惜篇幅对比一下在美国先贤们的眼里，“共和”与
“民主”的区别：

美国的先贤们总是把美国政府称为“共和政府”或 “自由政府”，而不是今天美国政府自我标榜的“民主政府”。无论是华盛顿，还是亚当斯，在其总统就职演说
里都是用“自由政府”、“共和政府模式”，形容当时美国政府，而不是所谓的“民主政府”。在费城制宪会议上，美国的先贤们强烈的抨击了民主和民意副面影响
，下面是几个代表的原话：

代表谢尔曼说，“老百姓眼下对建立政府的事还插不上手。他们缺乏信息，老是被人误导”。

代表格里：“我们所经历过的罪过，都是源于民主过于泛滥。人民并不缺乏德行，但总是受到假装爱国的人蛊惑。马萨诸塞州的经历证明，引动人精心炮制出
各种虚假报告，到处传播，老百姓每天都被误导去做些最作孽的事，说些最作孽的话，这些虚假报告又无人可以当场揭穿。一个主要的罪过，是说要对政府雇
员实施正当程序，仿佛把公仆都饿死才是民主的极致……”

　　美国第四任总统麦迪逊指出，“政府若采取民主的形式，与生俱来的就是麻烦和不方便，人们之所以遣责民主，原因就在这里”

富兰克林也承认，“我们都遭受过民主带来的迫害和不公正……”

　　美国先贤们对民主都不感冒，对议会自然也不可能有什么好感，他们对议会的评价是：“在议会中，议员们有时似乎自以为就是人民的化身，面对来自任
何其他方面最小程度的反对，就暴露出不耐和厌烦的病态；好象不论是行政或司法部门只要行使其权限就是侵犯了人民的利益。立法机构常常表现出企图横蛮
控制其他部门的意图；而且，由于立法机构一般有人民站在他们一边，就总是在行动时势头过猛，致使其他政府部门难于维系宪法规定的平衡”

为了削弱议会的权力，美国的先贤们采取的措施有：分割立法权，用“政府中精选而稳定的组成部分（即参议院）”牵制更容易受民意影响的众议院，立法权一
分为二，便于总统对他们分而治之，各个击破；实行三权分立，彻底地从理论上否定了民主机关在共和政体中的支配地位；赋予行政首脑“帝王般的权力”，使
行政首脑的政治地位高于议会。

代表迪金森认为：“受到限制的君主制，是世界上最好的政府形态之一”，“任何共和制的政府形态，都永远不会得到与此同等的祝福”。美国先贤们承认，美国
总统“与英国国王有类似之处，它也同样类似于上耳其皇帝、鞑靼可汗”。美国总统的权力主要有行政权、军权、联邦法官任命权、大赦权、立法复决权。这样
的权力设置，赋予总统有效压制议会内的反对势力的权力，使总统在美国政体中的地位比议会明显高出一截。

　　美国先贤们把总统是否可以独揽大权上升到了事关美国生死存亡的高度，他们强调：“舍此，不能保卫美国免遭外国的进攻；舍此，亦不能保证稳定地执
行法律；不能保障财产以抵制联合起来破坏正常司法的巧取与豪夺；不能保障自由以抵御野心家、帮派、无政府状态的暗箭与明枪。”当反对派以“美国的新政
体已经带上浓厚的君主制色彩”对此进行了强烈的批评时，美国先贤们的反击是：“我们却不妨承认，优良政体的真正检验标准应视其能否有助于治国安邦”。
也就是说，他们并不承认某种政治制度具有天然的合法性和道德上的优势，他们认为，任何一种政体好与不好，正真的检验标准是“治国安邦”，而不是别的什
么东西。他们还指出，“软弱无力的行政部门必然造成软弱无力的行政管理，而软弱无力无非是管理不善的另一种说法而已；管理不善的政府，不论理论上有
何说辞，在实践上就是个坏政府。”——在美国先贤们的眼里，国家领袖就应该是非世袭的、任期有限的独裁者，这样既可以避免行政部门的软弱无力，又可以
保证领袖（因担心下台后被清算而）对自己严加约束。

　　美国的先贤们对待民意的态度是：“人民普遍地是从自已的公益出发的。但这一点常亦用来说明人民也会犯错误的。人民从常识出发是会蔑视阿谀奉承的
人的，而某些别有用心的人胡说人民在任何时候都是贤明的，都能找到解决问题的途径的。但人民从自己的经验知道自己有时候是会犯错误的；因为人民终日
受那些别有用心的寄生虫和马屁精的欺骗，受到野心家、贪污犯、亡命徒的欺诈和坑害，受那些不值得信任的人的蒙蔽，受到巧取豪夺的人的耍弄。要说人民
在经常受到这样一些干扰的情况下，也不会经常犯错误，勿宁说这是个彻头彻尾的神话。”

他们设计美国的新政体的最重要原则就是要确保“行政部门肯定应该处于敢于有力量、有决心按照自己意见行事的地位”，也就是要确保执政者能够按照自已的
理念施政，而不是按照民意来施政。人民有权自由的表达自已的意见，但不允许民意干扰政府的施政。

他们认为，政府不但要为人民服务，还要能教化人民——“当美国人民的意向同他们本身利益出现差异的情况下，受命维护人民利益者的职责应该是坚决抵制这
种一时的误会，以便给予美国人民时间和机会去进行冷静认真的反省。这种作法能使美国人民免遭其本身错误所造成的严重后果，并使其有勇气和雅量为美国
人民利益服务而不惜引致美国人民一时的不快，但他将得到美国人民长期感激和纪念。”——那些一直对美国体制崇拜有加的人们可能失望了，美国的先贤们是
禁止人民参与治理国家的。

    富兰克林认为，美国新宪法确定的政体是一种“选出来的君主制”；杰弗逊也称美国的新政体是“君主制的新版本”。

美国宪法只赋予人民的权力是：人民选举众议院，参议院由各州的议会选出——在最初的美国大选中，民众只选众议员，没有资格选参议员，这样做的目的是为
了既能让治理国家的人倾听人民的声音，又可以做到在做决策时不对民意惟命是从；在选举总统的方面，人民直选州议会，州议会选出大选举团，大选举团选
出总统；人民没有罢免总统的权力，总统只有在严重违法并且被议会抓住了把柄，并且还要弄到连议会中本党的议员都众叛亲离之后，才有可能被议会赶下台
。说穿了，美国的先贤们希望美国总统就是一个稍受限制的独裁者而已——唯有强势的领袖才能有强势的国家。

随着共和势力在美国的衰败，美国也变得越来越民主了。在1860年南北战争前，大选举团大多改由各州民众普选。到1913年时，美国通过了宪法第17修正案，
在全国确立各州普选参议员。从那个时候开始，民众有了立法机构参众两院的全部选举权，这时，美国的共和势力已经全军覆没了。

熊彼特说过：“一旦涉及的各项利益与理想是人民拒绝与之妥协的利益与理想，民主政治可能根本运行不了。

今天的美国政府，已经是代表国际金融势力利益的傀儡政府了，所以他们不再提共和，不再提自由，只提民主。不要认为民主和自由有相同的意义，它们的区
别非常大：自由是实的，民主是虚的。民主不能当饭吃，自由却可以当饭吃——自由意味着独立，经济上独立是独立的基本条件——经济独立意味着自己有饭吃，
民主可以做到吗？

自由可以给人带来幸福，民主却不能。现在的美国足够民主：布什在台上叫喊着“就算只有自己的狗狗支持自己也不从伊拉克撤军”，反战的人就在白宫面前示
威，形势上民主的很。但是，有用吗？仗不还是打吗？只要华尔街不点头，华盛顿就得撑着打，死多少人背多少债是美国老百姓的事；赚取多少战争红利还是
华尔街考虑的问题。

但是，现在的美国民主有什么用？多少人沦落为债务的奴隶，这一点从次贷危机引发的信用卡危机中已经充分表现了出来，当然，现在许多的中国人也正在沦
为债务的奴隶（比如房奴），民主是有了，可能不能吃上饭自己却说了不算了。——是吃饭重要还是民主重要？美国的共和势力希望的是人民生活自由幸福，而
不是所谓的民主。而这些满口民主的家伙们，整天干得却是喝别人血汗的买卖。真正主宰着美国的那个群体，是财富可以世袭的家族，他们是“共和”的死敌，
他们希望把世人都变成他们的奴隶，用债务的锁链锁住，永远不得翻身。坐在白宫的人是民主选举的，但是，控制着华尔街的人是民选的吗？他们可是世袭的
。

我们的国家也是共和国，人民是国家的主人，我们同样是一个自由的国家，我们同样是共和国，我们的政体是世界上最优秀的。民主和专制是一对矛盾的统一
体，一方不可能把另一方消灭。专制到了极端，就到了民主的时候——造反，那时是人民最能“作主”的时候；民主到了极端，专制就出现了，要想让民主充分的
扬长避短，就必须控制民主的范围。过犹不及。不要不相信——给全世界带来最大祸乱的大独裁者希特勒不就民选的吗？

孟德斯鸠说过：“民主制和贵族制国家的本质并不是自由的。”美国现在是最民主的国家，可是，无论是民主党的侯选人，还是共和党候选人，都是国际金融势
力支持的，谁上台对他们来说都是一样的。所以，最民主的美国其实是最专制的国家——选谁上台都是为华尔街的主宰者们服务，这样的民主选举不就是个形式
吗？

股神沃伦巴菲特的父亲霍华德巴菲特是美国参议员，他在1948年就指出：“我警告你们,两党的政治家都将反对恢复金本位，那些这里和国外靠美国持续货币贬
值而大发其财的人,也会反对恢复诚实货币的制度。你们必须准备智慧和机警的面对他们的反对。”为什么美国的两党都反对恢复金本位？因为他们的金主反对
。谁控制着美国政府还用再问吗？

当然，这也是直选制度的必然结果：侯选人想上台就必须做宣传拉选票，这就需要大把的钱。谁来出？肯定是支持他的阶级来出——任何一个侯选人都是代表着
一个阶级的，这是不容抹煞的事实。广大的普通百姓虽然选举的时候积极，可掏腰包支持候选人的时候有几个积极的？当然，这也是没办法的事情——自己掏钱
了，自己支持的侯选人上台了，但是，他不会只为自己服务，会有大批的人搭便车，这样自己不就亏了吗？再说，普通人大都是一盘散沙，相互之间没有密切
联系，组织力量很差。而资本势力就不一样了，他们人数虽少，但是相互之间联系密切，而且有足够的钱去玩政治。如果一来，出钱支持候选人的基本上都是
资本家，这也是不争的事实。吃人家嘴短，拿人家手短。在人家的支持之下才上的台，能不替人家办事？不要以为你投票选了他他就应该替你做事，只有你出
钱支持他他才会为你做事。这才是选举政治的本质。换句露骨的话说，就是在直选情况下，选民手里的选票是废纸。这个道理也很简单：人做事是要负责任的
。你投谁的票是你的事，自己对自己负责就可以了；他花谁的钱是他的事，他得回报为他掏钱的人，这是他的责任。

看看现在的直选中出的那些笑话吧：小布什当众啃棒子，戈尔专门在媒体面前和自己老婆接吻，(在台湾地方领导人选举中)陈水扁为了当选做了阿扁娃娃（两
颗子弹就更不必说了），希拉里当众落泪……

“天地之大德曰生，圣人之大宝曰位”。本来，选举国家领导人是一件非常神圣的事情，却让人搞成了笑话，这难道不是对国家尊严的污辱？难道不是对民主的
嘲讽？有句不太好听的俗语，是这样说的：“看戏的是疯子，唱戏的是傻子。”这句话用在直选政治里倒也恰当。

相比之下，间接选举就不然。最高领导人是由选举团选出的，选举团成员都是代表自己群体利益的，他关注的是领导的品德和才能、以及能否给本集团带来利
益，而不是那些外在的东西。如果选举团成员不为自己的集团理性投票，他很快就会被自己的集团淘汰。所以，间接选举更理性。

其实，真正为国家和民族做实事的政治家，执政时都不怎么民主，也不会被民意牵着鼻子走，但是他们可以为自己的国家和民族争取到应得的眼前利益和世俗
人眼光看不到的长远利益。这一点，稍有历史常识的人就应该知道——古今中外，最有作为的国家领袖有哪一个不是近乎独裁？

当然，说美国政府是傀儡可能没几个人相信，还是举个例子吧，尼克松可绝对是国际金融势力的功臣，在替金融势力出过大力之后，居然被排除在石油回流计
划之外，后来在明白自己根本不被信任之后，恼火之下的尼克松准备单干，这时水门事件就爆出了，《华盛顿邮报》更是揪住这件事不放，搞得尼克松被动无
比，之后，尼克松对《华盛顿邮报》下了封口令，但是不起任何作用，相反，《华盛顿邮报》甚至还把尼克松对其下封口令的事情捅了出去。后来，《华盛顿
邮报》的这一行为被广泛的宣扬为美国媒体独立性的典范。尼克松也曾打算武装保卫白宫，但是巧得很，此前一周参谋长联席会议发布命令，所有美国武装力
量从即日起停止接受白宫命令。军队不听白宫的命令算怎么回事？这不是造反吗？可人家就是干了，事后既无人提及更无人追究责任，怎么的？尼克松是三军
总司令，关键时刻却只能指挥自己，真正成了孤家寡人，无奈之下，只能选择辞职。

美国的媒体真的那么客观公正吗？ 2003年美国侵略伊拉克的时候，曾因越南战争和海湾战争的战地报道而获得普利策奖彼得阿内特，仅仅由于在接受伊拉克
电视台采访时说了句“美国的第一个作战计划已经失败”，就被炒了鱿鱼。其实，不光是媒体，就连一向与布什唱反调的民主党领袖们也全部闭上了嘴，没有一
个人敢出来对布什政府在作战中所犯的低级错误提出任何质疑。美国媒体的独立性呢？美国的民主呢？全是子虚乌有的，有的只是国际金融势力的利益。当然
，如果还有人怀疑的话，看看今天CNN的表现就知道了——“做人不能太CNN”。

到底谁是美国政府的真正主人？追求民主的美国人最后追求到了什么结果？

相比之下，英国政府倒是在国际金融势力面前更吃得开一点。1990年，英国政府敢在伦敦金融城的反对声中加入欧洲货币兑换体系，国际金融势力只能通过用
索罗斯阻击英镑的方式逼英国退出，就足以说明英国政府在国际金融势力面前有非常独立的一面。因为英国在建立君主立宪制时（英帝国这个“人”在小的时候
）还没有国际金融势力。如果国际金融势力也想彻底控制英国政府的话，只有一个办法，就是武力推翻现政府，这叫连根拔起，也叫回炉再造。


** 【金鸿95】国际金融战探密（连载六）
   [2008-04-11 10:33:25]

   
    2、 美国称霸

    从1823年起，美国开始推行门罗主义，在“美洲是美国人的美洲”的口号下，开始大举扩张殖民地。到19世纪末，美国控制了拉丁美洲。1898年1月美国挑
起美西战争并打败了西班牙。西班牙将波多黎各、关岛和菲律宾割让给美国；美国付给西班牙2000万美元作为“补偿”。1898年，美国又吞并了夏威夷，从此，
美国成了东太平洋上的海权强国，之后的两次世界大战帮助美国称霸了世界。实际上，两次世界大战是美德争霸的两场战争。每次战争都是德国为了称霸而主
动挑起的，每次战争之初美国都是选择了隔岸观火、大发战争财，在德国被战争拖得筋疲力尽的时候美国再半路杀出对德国宣战，每次战争的结果也都是美国
打败德国。

    第二次科技革命以后，美德英法成为了世界上最强大的国家。以1900年世界制造业产量的数据看，德国在世界制造业产量中的相对份额为13.2% ，与英国
相当，美国为23.6%，而法国仅为6.8%。在威廉二世（1888—1918）时德国更是大规模扩军，实行海外扩张的政策。1897年，德国占领中国的胶州湾和青岛，次
年从西班牙手里取得加罗林群岛、马利安纳群岛和帕劳群岛，1899年和英美签订条约并获得萨摩亚群岛的一部分。1902年修建巴格达铁路直逼英俄中东利益，
德国与其他列强开始贴身紧逼。1914年德国利用萨拉热窝事件，挑起第一次世界大战，战争之初，美国宣布中立。利用“中立国”地位同交战各国大做生意，国
际金融势力向协约国提供了约200亿美元的物资和贷款。大战进行到1916年冬，交战各国物资和人力消耗极大，广大人民更是困苦不堪，交战各国都面临严重
的政治危机。在这种情况下，交战各国展开了“和平”攻势，希望用和谈取得用武力所没有得到的东西。1916年12月12日，德、奥、土、保共同向中立国、协约
国和罗马教皇发出照会，建议在中立国荷兰的海牙召开和会，谈判结束战争的问题。12月18日美国总统威尔逊假惺惺的出面调停，但实际上，美国非常害怕俄
国与德国单独媾和，导致协约国失败，那样美国给协约国的贷款就难以收回了。所以，为了保证国际金融势力的利益（也就是美国的国家利益）不受损失，也
为了争夺世界霸权，美国利用德国“无限制”潜艇战攻击了美国商船为理由，于1917年4月6日对德宣战，当然，美国大使给德国人的说法是“我们美国人是为了
道德原则而投入战争的。”

    早已被战争拖得疲惫不堪的德国哪是多年养精蓄锐的美国人的对手？结果是德国在战争中被毁灭，意大利被消弱，英国也大受战争影响，其世界金融中心
的地位让给了美国的纽约，美国成为世界头号强国。

    第一次世界大战后，苏联和日本又崛起了。特别是苏联，仅仅用了两个五年计划（1928 ～1938年）的时间，其制造业的产量就增加了7.5倍多，跃居世界
第二位。而且法国的表现也越来越不让国际金融势力满意，于是国际金融势力扶持希特勒上台，对付苏联和法国。

    希特勒上台之后，大力煽动民族复仇情绪，全面整军备战，国际金融势力在背后给希特勒以全方位支持，德国的军事实力很快强大起来；意大利也不甘心
在一战中的失败，希望重走国家扩张的道路；日本更是随着实力的增强，霸称野心陡增，全面军国主义化，妄图吞并中国，于是，德意日轴心形成。

    希特勒没有让国际金融势力失望，发动闪电战迅速灭亡了法国，直逼莫斯科，二战中最惨烈的战争开始了。这场战争的头两年，美国坐山观虎斗，任凭德
国侵略苏联，消耗这个社会主义国家的实力；美国甚至在日本入侵中国东北、华北时，美国还跟日本做生意。之后，在欧洲战场打得难解难分的时候，美国开
始大幅削减对日本的石油、钢铁等战略物资的供应，封锁日本的海上通道，日本不得已，偷袭了美国的珍珠港，美国以此为借口加入战争，太平洋战争爆发。
这一场战争之初日本占优，它占领了香港、缅甸、马来西亚连同新加坡要塞、菲律宾、印度尼西亚各重要岛屿及其他地区，重创了英、美、荷联合舰队，使美
、英失去了太平洋西部所有海、空军事基地。之后，美国把主要的精力投入到了对付日本上，借着与日本作战的机会夺取了日本太亚太地区的所有殖民地。最
后美国彻底控制了日本。从国际金融势力展现出来的战略规划能力看，日本战败完全在情理之中，大和民族是最缺乏战略规划能力的民族了。当然，日本的战
术执行能力在全世界是首屈一指的，这也是日本商人能够纵横天下的原因。

    如果站在时间和空间的大纵深层面总结一下美日之间的这一场战争，可以发现日本人是完全中了美国的诱敌深入之计：先放纵日本的野心，让它大举出兵
搞什么“大东亚共荣圈”，在日本国力变得空虚的时候扼住日本的海上生命线，造成日本不得不主动对美国宣战的结果。从表面上看，日美开战伊始，日本在太
平洋上节节胜利、攻城掠地，美国却被动无比，其实，整个战争完全在国际金融势力的控制之下，当然，许多人可能不相信这种说法，在此，我就把理由说一
下：首先，在1943年1月，罗斯福和丘吉尔在卡萨布兰卡发表声明，要求德国必须无条件投降。这个声明严重打击了德国内部反战力量，因为此时德国反战派
已经在着手策划军事政变了。正是因为这个无条件投降声明，战争又被延长了两年多。从这一点可以看出，整个战争的进程完全是受控的。其次，当时的希特
勒受制于国际金融资本，因为打仗是要靠钱来支撑的，当时的法西斯德国的战争融资主要通过国际金融资本控制的国际清算银行进行。如果美国真的在太平洋
战场上支撑不住了，只要掐住希特勒的资金供应或者支持一下德国反战势力，就可以结束欧洲战场——意大利的战斗力根本就不堪一击。只要欧洲停火了，英国
可以援助美国，苏联也可以掉头南下对付日本，再加上中国抗日势力的反扑，日本马上就顶不住了。另外，美国的国力远强于日本，速战速绝的话日本或有取
胜的希望，可打起消耗战之后日本是无论如何也支撑不住的。美国就是趁着欧洲战场上各方打得难解难纷、无瑕东顾的时候，打着打击日本的幌子控制了整个
太平洋，极大的扩展了美国在太平洋上的战略外围空间，日本本国最后也被美国控制。

    其实，偷袭珍珠港只是日本人的一厢情愿罢了，之前美国早就掌握了日本的动向。别的不说，在偷袭珍珠港之前，港上运到了大批的医疗卫生用品，就是
为了救护伤员的。只不过日本人一直被蒙在鼓里罢了；日本原定的主要袭击目标是美国的三艘航空母舰，但一艘都不在港内。战列舰倒是全炸了，不过战争的
发展证明，摧毁这些战列舰的作用远比日本人预想的要小得多。对美国而言，珍珠港被袭击还有一个天大的好处，就是以此为借口动员民意，加入二战。因为
当时的美国人非常反感加入这场战争。对日本宣战的理由是日本偷袭自己了自己的珍珠港，可如何引导着民意同意对另一个心腹大患德国宣战呢？地图计。
1941年10月27日，在庆祝美国海军节的午餐会上，罗斯福拿到了一幅“希特勒政府绘制的附有说明的中南美洲地图”。这幅地图将中南美洲的14个国家的疆界进
行了重新划分，其中委内瑞拉、哥伦比亚和巴拿马被合并成为一个受希特勒控制的名叫“新西班牙”的国家，与美国利害攸关的巴拿马运河以及整个拉丁美洲都
被纳入纳粹德国的势力范围。这幅地图一公布，美国舆论哗然：美国后院不保！德国轰炸机要飞到自己头上来了！于是人们纷纷要求政府参战打击法西斯，以
确保美国的安全。其实，这幅地图是假的，当时的希特勒正忙着对付强大的苏联，哪有精力去招惹更强大的美国呢？那幅地图根本就是英国情报部门在邱吉尔
的指示下绘制的，因为那时的英国快顶不住德国的进攻了。而罗斯福装糊涂，以此来煽动美国民意，让国会顺利批准美国参战的计划。从两个操纵民意的事件
中也可以看出，民意确实是盲目的。

    美英两国一开始在欧洲战场上都是以防守为主、出工不出力，目的就是尽最大可能的消耗德国和苏联的实力，直到苏联取得了斯大林格勒保卫战的胜利、
扭转了战局以后，美英两国的战斗行动才积极了起来。从诺曼底登陆战开始，美英法联军开始全力进攻德国，直至美英法苏把德国肢解。至此，日本和德国两
个对手被美国全部收拾掉了。不过，另一个死敌反而更强大了——苏联。

    第二次世界大战严重破坏了苏联经济，但是，战后苏联主要经济指标的增长速度比美国高出1-2倍。1950年，苏联的工业总产值不到美国的30%，1980年已
达到67%，苏美争霸成了二战之后的主旋律。

    在这里还得再说一下法国。本来，在二战一开始，法国就亡国了，为什么法国还能成为战胜国并且成为联合国常任理事国呢？因为美国一直欠法国的人情
，一来当年的美国独立战争就是法国帮着华盛顿打胜的，二来拿破仑在1803年以1500万美元的价格把路易斯安那卖给了美国总统杰弗逊，这片土地从密西西比
河直达洛矶山的广大平原，相当于当时美国版图的一倍。当然，拿破仑这样做是为了给英国制造一个强大的对手，以减轻自己的战略压力。但是，由此美国欠
下了法国两个天大的人情。所以，帮助法国重新建国是美国必须做的，这也是1964年法国敢于率先在美国的反对下承认中国、1966年敢于退出北约军事组织（
只保留政治组织资格）的原因——国家和人是一样的，欠债要还，欠情也要还。

    第二次世界大战一结束，冷战就开始了。苏美两国为了争夺军事上的优势都把大量国家资源投入到了军备竞赛上，以至于被许多人评价为“对经济发展造
成了长远的损害”。其实不然，从第二次世界大战到今天的63年的时间里，只有冷战开始的前20年，世界各国经济体是相对健康的，经济增长是真正的实物性
的经济增长。以美、苏两国为代表，各国的工业和技术取得了真正的进步。苏联和美国两个阵营都以人均实物产出的增长为目标，而达到这个目标的手段也都
是对工业、农业和基础设施等资本密集型项目进行大规模投资。在这期间，各国都不鼓励投机，对金融都实行严格的管制，都在努力的保护和扶持本国生产者
，都强调高科学技术和生产力水平，而这段时期的金融利润主要产生于实物的制造和贸易，各国经济体的泡沫含量都非常小。

    但从赫鲁晓夫和艾森豪威尔达成了“后工业社会政策”的协议之后，一切都变了。

    3、泡沫解体世界的第一个牺牲品——美国

    从上世纪60年代开始，国际金融势力用两面手法全力推动欧洲美元市场的壮大，为最后实现黄金与美国脱钩做准备；同时，他们也开始了泡沫解体世界经
济的道路。

    艾森豪威尔政府用大规模信贷扩张的方法刺激经济发展，由此增加了每单位实物产出的整体成本，造成了美国经济实质效率的下降——也就是说，每年生产
出的实物产品没有增加多少，GDP却有了显著的增长（这本身就是经济泡沫），当然，这种泡沫这债务泡沫和营销泡沫的组合。经过20多年（从1958年开始到
1980年）的泡沫培养——其间美国发生过4次经济危机，每一次经济复苏都是采取的信贷消费拉动，结果给美国制造了一个巨大的经济泡沫（这期间还有高油价
造成的债务泡沫），到1979年“利率冲击”的时候，美国经济体再也支撑不住了，巨大的泡沫在超高利率的猛烈冲击之下（再加上沃克尔严格的信贷控制等手段
），泡沫破灭，美国的经济基础（工农业）遭受到了近乎毁灭性的打击。许多工业部门的实物产出在3年内下降了30%至40%，到今天都没有恢复过来。

    泡沫解体美国经济对国际金融势力有什么好处呢？第一，在泡沫破灭的时候低价收购优质的企业资产，全面控制美国的经济命脉；第二，每次经济复苏都
是在信贷消费拉动下实现的，给各国竖立一个榜样，信贷消费政策是正确的，跟着学样的国家也都自己吹起了一个个的大泡泡；信贷消费成为习惯以后可以让
老百姓背上沉重的债务，奴隶的锁链就这样套上了；第三，改变各国政府及老百姓对经济增长的认识，以前都认为只能实物产出的增加和劳动生产率的提高才
意味着经济增长，现在看来，经济增长和实物增长是可以脱钩的，单纯的“资本财产”也可以增长（即炒作），当然，宣扬和美化GDP也有这个意思。

    4、石油武器与美元霸权保卫战

    尼克松宣布美元和黄金脱钩之下，西方各国不依不饶，无奈之下的美国政府1971年年底的与西方各国达成了一个妥协性的“史密森协议”，勉强蒙混过关，
不过，各国实际上仍然寄希望与美元重新与黄金挂钩，至少各国能用手里的美元赎回属于自己的黄金，可惜的是，此后美国的国际收支状况并未好转，于是在
1973年1月再次爆发美元危机。美元又再次贬值，贬值后外汇市场重新开放。抛售美元的风潮再度发生。美元的地位摇摇欲坠。

    这时，国际金融势力祭出了他们手里的石油武器（其实从1970年开始，他们就已经把油价逐步上升到了3美元一桶，可仍然止不住美元的颓势）。他们挑
唆埃及和叙利亚进攻以色列，之后，美国公袒护持以色列，阿拉伯人被彻底激怒了，他们在1973年12月宣布收汇石油标价权，并将其原油价格从每桶3.011美
元提高到10.651美元，如此一来，世界石油价格就从1970年1.9美元/桶暴涨了4倍。因为世界石油交易普遍使用美元结算石油价格，这时世界各国对美元的需
求激增，美元的地位稳住了。

    同时，油价暴涨引发了第二次世界大战之后最严重的全球经济危机，所有的工业化国家的经济增长都明显放慢，许多正在实施工业化的发展中国家都背上
了巨额的贸易赤字，国内经济发展不得不依赖世界银行的低息贷款。

    之后，他们又借着世界第二大石油出口国伊朗亲美的巴列维政权倒台、第二次石油危机爆发和两伊战争的机会，把油价炒到了1980年的34美元。第三世界
国家背上了沉重的债务。并且，美国“错误的”政策助长了欧洲美元市场的进一步扩大（这里面还有美联储海量发行廉价货币和石油美元回流的功劳），到1979
年，已有超过1/3的美元变成了欧洲美元。西方各国把自己手里的美元换成黄金的奢望再也无法实现了，美元的地位则重新获得有力支撑。

    5、利率冲击与全球债务泡沫

    七十年代石油价格的暴涨造成了发达国家二位数的通货膨胀，这些国家的人民的财富遭到了洗劫。为了让人民一个交待，反通货膨胀的朝代来临了。

沃尔克当上美联储主席后就打起了打击 “世界范围的通货膨胀”的大旗，把美元拆借利息平均值从1979年的11.2%一口气涨到1981年的20%，基本利率更高达
21.5%，国债冲上17.3%。英国的撒切尔夫人也非常配合的把基准利率从12%在12个星期之内提高到 17%，因为她发誓“要把通货膨胀从经济中驱除出去”。

    美元利率的提高，进一步稳固了美元的地位。但是，世界各国的人民却承受了巨大的痛苦。如果把严重的通货膨胀比作放在火上烤的话，那么猛烈的通货
紧缩就是放在冰里冻，快要烧焦的身体怎么受得了冰冻的折磨？　 

    第三世界国家的债务从1973年到1982年间共暴涨了５倍，巨大的债务泡沫直接导致了的全球债务危机。身为债权人的国际金融势力则理直气壮的开始“有
控制的解体”这些欠债国。他们通过IMF 和债权银行推行的“解决方案”，并没有解决问题，反而为日后各国暴发更严重的金融危机埋下了种子——到1987年时第
三世界国家所欠债务又冲到了13000 亿美元，债务泡沫更大了。当然，他们如愿以偿的获得了这些国家大量的核心资产，控制了这些国家的经济命脉。


** 【金鸿95】国际金融战探密（连载七）
   [2008-04-12 11:05:38]

   
    5、解体苏联

    经过多次的石油提价，国际金融势力已经给第三世界国家深深的种下了债务泡沫的种子，并且帮助美元彻底稳住了阵角。更幸运的是，从1978年中美建交
开始，中国开始实行亲近美国、韬光养晦的外交政策。这时，美国具备了解决自己的死敌苏联的条件。

    也是苏联命该当绝，1979年12月27日，苏联出兵阿富汗，推翻了阿明政权，处死了阿明全家，扶植亲苏的卡尔迈勒上台，开始了对阿富汗的军事占领。阿
富汗人则开始奋起抵抗，成立了大大小小数百个各种抵抗组织。从1980年起，七大派抵抗组织建立了“阿富汗圣战者伊斯兰联盟”的统一战线，在战场上协同作
战。中国则与美国联手，通过巴基斯坦为阿富汗抗苏组织提供各种支持。苏联深深的陷入了战争泥潭。当时，在阿富汗的反苏武装都被美国人称为英雄，这其
中就有现在美国人的死对头本拉登，他当年可是美国CIA培训出来的，也是当年美国人心目中的大英雄。

    从大国斗争的角度看，当时的中国犯了战略性的错误，苏联再不济也是社会主义国家，中国却和一个老牌的、一直欲除掉红色中国政权而后快的帝国主义
国家联手对付它，于情不合；当时中美苏三足鼎立，美国最强，中国最弱，帮着美国除掉了苏联，接下来美国就可以精中全部的精力对付中国，于理不通，事
实发展的结果也是如此，在苏联解体之后，美国就开始对中国输出颜色革命，支持李登辉搞台独，再后来就是炸中国的大使馆……

    入侵阿富汗的失败在苏联解体过程中起到了决定性的作用，是苏联解体的最主要原因。因为经济崩溃而灭亡的国家不多，因为军事战败而灭亡的国家则比
比皆是。

    导致苏联解体的第二个原因是苏联经济崩溃，而在这其中美国是居功至伟。当时苏联与美国争霸，在军事方面投入的财力太大，经济发展受影响非常大。

    当时苏联对石油出口的依赖很大，只要国际油价下降，苏联的出口换汇能力就会下降。于是，美国开始从国际油价上入手做文章。美国派出中央情报局局
长凯西到利雅得会见沙特亲王，要求沙特支持美国把油价降下来；美国则保证沙特的国家安全会，并向沙特出售一些尖端武器。之后，美国用尽一切办法来缩
减石油需求，甚至缩减了美国的战略石油储备。除以之外，美国还要求西欧及日本在油价上涨时抛售战略石油储备，稳定油价。1985年，沙特国王法赫德访问
美国，美国又要求沙特多开采一些石油以继续压低油价。为了给沙特一点甜头，美国政府向法赫德透露，美国财政部准备在未来12个月内让美元贬值1/4。这
可是个套利的好机会，沙特狠赚了一笔。当然，对美国投桃报李是肯定的，1985年夏末，沙特正式通知里根政府，它准备增加石油产量。国际石油价格应声暴
跌。当年11月，每桶原油的价格从原来的30美元跌到了12美元。对苏联来说，这绝对是个坏消息，石油价格下跌造成苏联的出口换汇能力严重下降，美元贬值
也让苏联手里的美元的实际价值严重缩水。

    除了压低油价外，美国还针对苏联出台了一系列措施：

    利用巴统委员会来限制西欧对苏联的关键技术出口：包括先进计算机及其电子部件、光纤、半导体和各种冶金方法，限制西欧的公司把工厂迁入苏联境内
，所有与苏联签订的价值超过一亿美元的合同都要自动交委员会审批，扩大该委员会从成立以来制订的禁运清单……

    利用经合组织等国际机构来限制给苏联提供的贷款，1983年的3月，巴克利到欧洲访问，与西欧国家把苏联重新定义为“相对富裕的国家”，而不是原来的“
中间借贷国”，并且停止了对较富裕的国家的贷款提供补贴。如此一来，苏联从西欧借的贷款利息从原来的7%―8%上升为17%（17%利率武器）。

    鼓励西欧国家利用各种替代能源，减少对苏联天然气供应的依赖，1983年春天，美国还将一项协议强加给了国际能源机构，限制欧洲从苏联进口的天然气
比例，规定西欧从苏联进口的天然气不得超过其能源需求量的30%。

    到1985年时，苏联的外汇收入锐减，苏联原来指望从西欧获得的出口贷款、硬通货和技术也全部泡汤，苏联从西伯利亚通往西欧的天然气管道工程也因此
而被推迟，原计划这条天然气管道可以从1985年起给苏联每年带来上百亿美元的收入。当然，如果到1990年第二条管道也完工，每年就可获得150亿至300亿美
元的收入。然而，由于里根政府的搅局，苏联修建第二条天然气管道的计划彻底失败。

    戈尔巴乔夫接手时，苏联已经危机四伏：苏军在阿富汗进退维谷；波兰在美国的支持下公开挑衅苏联社会主义模式；为了对抗美国的星球大战计划，苏联
不得不把仅剩的一点资源都投到了军事上，国力严重透支，几乎吐血；靠着往西欧出口能源来换外汇的路子又被美国堵死了，苏联只好卖黄金换外汇。

    决战的时候到了。在1991年1月和2月，美国的金融战专家万塔在伦敦黄金交易市场上大肆做空黄金高达200吨，金价暴跌，苏联的出口换汇能力再遭重击
。在此之前的1990年10月，万塔以高于黑市一倍的比价（28卢布兑换１美元）以50亿美元的资金买进了1400亿卢布。这时万塔把这1400亿卢布猛抛了出来，卢
布暴贬，之后苏联的内奸们推波助澜、加上苏联政府的无能，导致卢布暴贬万倍以上。是役，苏联损失的财富总额高达275000亿美元。

    当然，如果在那个关键时刻苏联政府对金融进行了国家管制，就不会出现那个悲惨的结果了。可问题是他们没有那样做，他们太相信“市场的力量”了。

    之后，叶利钦又在IFM的指导下开始对俄罗斯经济实施休克疗法：看紧货币、调整结构和债务重组。方法不能说错，可关键的输血（国际金融援助）没有
到位，结果是让俄罗斯的GDP损失了一半，人民生活水平更是一落千丈。一头身强力壮的北极熊就这样被人轻轻的摞倒了。

    6、攻击日本

    国际金融势力用70年代的高油价和80年代初的高利率巩固了美元的地位，把第三世界国家深深的埋进了债务泡沫之中，但是，美国的工业实力也受害无穷
，造成了日本经济的腾飞。日本靠模仿起家，然后迅速降低生产成本，反过来全面冲击欧美市场，日本制造的产品行销全球。

    在站国际金融势力的角度看，富裕的日本是一块诱人的肥肉，吃下它既能增加实力，还有助于泡沫解体世界目标的实现。于是，他们在1985年出手了。

    国际金融势力收拾日本的办法也不复杂：逼长期日元升值，强烈冲击日本的出口制造业，日本经济是标准的出口拉动型，出口制造业受打击的结果就是日
本经济体质的严重下降。为了扭转颓势，日本不得不改为内需主导型，下调利率将成为必然的选择，为了保证日本经济泡沫吹的足够大，国际金融势力又强迫
日本政府取消金融市场管制，进一步下调利率（最低达2.5%），引发日元的流动性泛滥，同时，国际金融势力限制日元投入到第三世界国家的实业当中，无法
落脚的日元洪流只有走疯狂投机的道路。当然，为了保证泡沫的吹大，从日本泡沫的吹起过程中获利，国际金融势力还把巨额的热钱推入日本经济体推波助澜
，并在准备挤破日本经济泡沫之前获利撤出。之后，国际金融势力全方位下手，挤破日本经济泡沫，日本经济元气大伤。

    在制造日本经济泡沫的同时，国际金融势力也没有忘记用“国际金融规则”捆住日本人金融扩张的双脚——巴塞尔协议（资本充足性标准）。这一协议一箭双
雕，在日本经济泡沫破裂之前，它极大程度上阻挡了日本银行海外收购的步伐；在日本经济泡沫破裂之后，它又极大程度的抵消了日本政府重振经济的扩张性
财政政策。从这里也可以看出，所谓的游戏规则是如何的不公平。这就象一个练中国武术的人和一个练拳击的人比武，练拳击的人说：“我练的是拳击，不用
腿踢人，所以你也不能用”。从表面上看，很合理，因为每个人都是两只手两条腿，大家都不用谁也不吃亏。其实呢，中国武术讲究的是“手是两扇门，全靠腿
打人”，不让用腿中国武术的优势就全没了。如果定下“不允许直接攻击头部”的规则，那么那个练拳击的人就死定了。

    日本泡沫经济崩溃之后，不但损失了巨额的财富，还被深深的埋下了投机泡沫的种子。从1992年以后，日本非生产性贷款比例逐渐提高。新增的非生产性
贷款基本上都是在制造经济泡沫的。原本非常健康的日本经济体从此病入膏盲。

    7、狙击英镑

    国际金融势力为了稳住美元的霸权地位，也为了泡沫解体世界经济，在70年代先后制造石油危机和推行极端的货币政策（17%利率），西欧国家也带来了
严重的通货膨胀。为了扭转西欧经济屡遭经济泡沫的冲击，免受跟着美元汇率做过山车的痛苦，70年代末，德法两国决定建立自己的货币体系，并且趁里根与
苏联争霸的机会建立起了欧洲货币体系。

    1992年2月17日，欧共体12国的外长和财长在荷兰的马斯特里赫特签署了《马斯特里赫特条约》，条约规定，欧共体（欧盟）各国分三步完成统一货币的
工作，第一步是强化当时已经存在的欧洲汇率机制，实现资本的自由流通；第二步是建立欧洲货币机构，负责协调欧共体各国的货币政策；第三步是建立统一
的欧元，并把欧洲货币机构升级为欧洲中央银行，为欧盟各国制订统一的货币政策。如果这个计划能够顺利完成，欧元可以与美元平起平坐了。

    但是，当时的欧盟各国经济发展很不平衡。德国处于经济繁荣的巅峰，主宰着整个欧洲的经济发展；英国则陷于衰退的泥潭；意大利甚至还不如英国。

    当时，英国的情况还有一个更特殊的地方：首相梅杰之所以能上台组阁，是因为撒切尔夫人对欧共体的极端敌视政策引发的保守党内乱才混水摸鱼成功的
。虽然梅杰满足了英国亲欧派加入了欧洲汇率机制的要求，能在欧洲一体化进程的分得一杯羹；但梅杰又不敢完全满足亲欧派的要求，因为伦敦金融城是绝对
惹不起的。于是，梅杰政府在签署条约的时候要求欧盟各国允许在欧元建立的时候，英镑可以继续存在下去，英格兰银行依然保持独立。

    尽管梅杰政府非常的小心谨慎，依然招来了伦敦金融城的报复。

    在《马斯特里赫特条约》签署之前，英镑已经严重被高估了，这里面有英国经济不景气的原因，也有英国已经加入了欧洲汇率机制、英镑必须和马克等货
币相互盯住的原因——英镑只允许在一定范围内浮动，一旦超出了规定范围，各成员国的中央银行就有责任通过买卖本国货币进行市场干预，使该国货币汇率稳
定到规定的范围之内。如此一来，英镑的回旋余就更小了，英国政府也不可能通过英镑的主动贬值来刺激经济的发展，摆脱萧条了。　

    在《马斯特里赫特条约》签署之后，英镑与马克的汇率是1：2.95。两德统一之后，受东德地区基础设施建设的影响，德国经济过热，德国央行不得不调
高利率来抑制通货膨胀，这又给英镑带来了更大的压力。英镑只有两个选择，一是提高英镑利率以维持英镑在资本市场的竞争力，二是在外汇市场上大量购买
英镑以维持英镑汇率的稳定。但是这两个选择都非常艰难，加息会让英国的经济低迷雪上加霜；筹资稳定市场的钱，英国政府又拿不出来，只能依靠借贷，不
过如果稳定市场的行动失败了，英国政府将背上沉重的外债包袱。

　　再其他的办法就是说服德国降低马克利率，减轻英镑的升值压力，不过德国人并不想帮忙；说服欧洲其他国家暂时容忍英镑的贬值给英国经济以喘息之机
的主意也被欧洲各国拒绝了。就在这个英镑最脆弱的时候，金融大鳄索罗斯出手了。

    其实，在这个时候，保卫英镑的力量不是英格兰银行，而是欧洲其他国家的央行，特别是德国央行。因为仅凭英国的力量是无法把英镑对马克的汇率维持
在1：2.95的水平上的。所有内行的人都知道英国经济支撑不住英镑的高汇率，但几乎没有人敢轻易出手狙击虚弱的英镑——只要德国愿意出手，英镑就是安全
的。

    这时的德国虽然实力强大，但也有麻烦，因为它要两面作战。德国经济的过热要求德国央行不但不能在此时降息，还要加息，因为东德基础设施投资的进
一步增加将会使通货膨胀压力越来越重。结果，随着马克的加息，英镑越来越吃不消了，英格兰银行也多次装模作样的多次要求德国央行降息以便英国也降息
、刺激英国的出口。德国人又不是不知道英国政府和英格兰银行之间的那点破事——你们内斗我们外人掺合什么？拒绝是德国人的唯一选择。外人是看不出这其
中的门道的，不过，身为英格兰银行马前卒的索罗斯又怎会不知内情？

    因为德国人的袖手旁观，英镑顶不住了，从年初的1：2.95跌到初夏的1：2.85，又跌至8月下旬的1：2.80。欧洲汇率机制规定英镑对马克的汇率不得低于
1比2.778。攻击英镑的时候到了。

    9月，索罗斯带领着一群金融赌徒开始在市场上攻击疲软的英镑（还有意大利里拉）。英国政府采取了各种措施来应付这场危机：它一再请求德国降低利
率，但德国拒绝了；无奈将本国利率提高到15%，希望通过高利率来吸引货币的回流，但仍收效甚微，英镑的汇率还是未能守住2.778的最低限上。在这场英镑
保卫战中，英国政府动用了价值269亿美元的外汇储备，最终还是遭惨，英镑对马克的比价下降了2.7%，跌到了2.703，大大低于汇率机制的最低限额。梅杰宣
布，英国退出欧洲货币汇率机制，意大利也跟着退出了，英国和意大利货币开始自由浮动，两国的央行不再在市场上购人各自的货币以维持其地位。尚未成形
的欧元被打倒在地。

    在这一场豪赌中，索罗斯做空英镑70亿美元，做多马克60亿美元。同时大规模的做空意大利里拉、做多法国法郎；还购入价值5亿美元的英国股票，卖空
自己在德国和法国的股票，因为一个国家货币贬值通常会导致该国股市的上涨。此役索罗斯共收益20亿美元，其中10亿收入来源于做空英镑，另10亿的赢利来
源于意大利里拉和瑞典克朗以及东京股市混乱。

    8、扫荡东南亚

    狙击英镑和里拉是为了阻击欧元区的建立，打击日本也是为了打压日元区的建立。日本这个日元区的建立者被打倒了，接下来就是要斩草除根，清剿日元
区的外围空间，全面压缩日本的经济外围生存空间——东南亚；同时，由于中国也视东南亚为自己的后院，占领了东南亚也就压缩了中国的经济外围空间，可以
把枪口直接顶在中国的大门上，事实上国际金融势力也是这么干的——索罗斯扫平了东南亚不就奔着香港杀过来了吗？

    苍蝇不抱无缝蛋。国际金融势力能找到对东南亚各国下手的机会也是有原因的：

    从表面上看，小虎们都挺壮，其实是表壮里不壮。这些国家经济多年发展并没有形成真正的优势产业群，国际竞争力相对有限。这些国家太相信国际友人
的建议，开放得太快，引入了大量国际资本之后却因为没有优势产业群的正确引导一股脑的扎进了股市和房市，吹起了巨大的泡沫。泡沫的吹起必然导致这些
国家经济体制的虚弱，体制虚弱之后泡沫就出现了要破灭的趋势——经济泡沫就是这样的一个恶性循环。

    东南亚国家一直是盯住美元的。在1994年以前的他们坐的是顺风车，美元一路贬值，他们的货币也跟着贬，这些国家的出口企业日子都很好过，因为出口
商品的价值由于货币贬值变得价格更低廉；但是，之后美元开始强势起来，拖得小虎们非常疲惫；这期间人民币和日元又贬值了，小虎们的出口又受到了严重
的挤压。在这一拖一挤之间，小虎们架不住了，出口换汇能力严重下降，贸易赤字巨增。与此同时，由于放松了金融管制，热钱滚滚而来，进一步推高房价和
股价，并形成了严重的通货膨胀。为对付通货膨胀，央行不得不加息，加息后套利的热钱进得更猛了，导致这些国家外债更多……到1996年时，泰国国际收支经
常项目赤字为230亿美元，韩国则高达237亿美元，货币贬值的趋势出现了。

    当然，这些国家被黑还有别的原因，比如把巨额的短期借债投入到了长期投资上，形成了不合理的债务结构，直接后果就是短期借债到期后如果新债借不
进来就被债务卡了脖子，虽然他们有足够的债权，但这些债权都是长期的，远水解不了近渴。

    瞅准了机会的国际金融势力就下手了，派出金融黑客索大魔头先奔着泰国就杀了过来——因为泰国是东南亚各国中金融市场开放程度最高的，资本进出自由
，泰国的泡沫也最严重，房地产泡沫又已经露出了破灭的迹象。对付泰国这样的小国非常容易，强攻硬上即可。索罗斯带领着大队的投机资金先卖空泰铢远期
合约，然后狂抛泰铢砸汇率，同时在股市上玩命的砸盘做空股市，泰国只有区区300亿美元的外汇储备，哪经得住索罗斯的折腾，几天下来泰国政府就弹尽粮
绝了，无奈之下剜肉补疮，宣布泰铢自由浮动，结果当天泰铢就贬值了20%。泰国政府这一下子就被“那个很有钱的白痴”卷走了40亿美元，在股市的暴跌中许
多泰国人的腰包也被掏空了。初战告捷的索罗斯顺势扫荡了整个东南亚，印尼盾、菲律宾比索、缅元、马来西亚林吉特纷纷大幅贬值，各国股市崩盘，工厂倒
闭，银行破产，物价上涨，惨不忍睹。从1997年7月起的半年时间里，东南亚各国货币贬值30%～50%，印尼盾竟达70%以上。同期这些国家股市跌幅达30%～60%
。这次给东南亚各国造成的经济损失就达1000亿美元以上，这些国家和地区陷入了严重的经济衰退之中。中了国际金融势力暗算的小虎们还是不长眼，一头扎
进了IMF的怀抱， IMF便派出了经验丰富的专家帮助治病——这些专家在墨西哥金融危机中都是显过身手的——那场金融危机是索罗斯干的。结果几刀下去，几乎
把这些小虎们大卸八块。


** 【金鸿95】国际金融战探密（连载八）
   [2008-04-13 11:03:42]

   
    西方经济精英们搞过一个“第一代金融危机模型”，认为在国际资本自由流动的条件下，冲垮固定汇率制度是必然的。对这一点，我深以为然。但是，这并
不能说明固定汇率不合理，恰恰相反，它说明国际资本自由流动是不合理的。固定汇率就象截江大坝，资本自由流动就是把许多的河流之间打通，如此一来，
暴雨来临的时候河水暴涨能不冲毁大坝？大坝被冲垮必然会出现水淹七军的惨剧。但是，这并不是大坝的错误，如果没有大坝的蓄水作用，进入枯水期的用水
问题如何解决？错误的是不该把不同的河流之间连起来，这样的水量增加根本就是无法控制的——如果有人在某些地方故意截流把水引向某一方向的话。

    东亚金融危机还引发了商业银行撤资的狂潮，日本商业银行在这其中是一马当先。1997年年中到1998年年中的资本外逃中有1/3是日本资本外逃，总额230
亿美元。当然，这里面有日本的商业银行早已成了惊弓之鸟的因素——他们被1990年的日本经济泡沫崩溃和1995年日本金融危机吓怕了，只要一有风吹草动，逃
得比兔子还快，生怕被巴塞尔协议的绳索勒死——如果不能按照巴塞尔的要求将资本金充足率提高到8%以上，就不能涉足国际市场业务。当然，这里面更有小日
本不扛事的原因，如果日本真能在关键时刻顶上去了，那一场东南亚金融危机根本就爆发不了，香港不就是在北京的支持下成功的顶住了索罗斯的进攻吗？这
一场危机之后，东南亚国家对日本也绝望了，什么“雁阵”，兔子阵！此役，国际金融势力成功的围剿了日元区，结果吃亏最大的还是日本。

    这一次的金融危机，是东南亚国家上当的结果，正如世界银行首席经济学家斯蒂格利茨（曾任克林顿政府的经济顾问委员会主席）所的说：“IMF和美国财
政部在国际上推行的政策，恰好与其国内政策追求相反。我们在国内反对社会保障体系的私有化，然而我们却在国外提倡它；在国内我们反对平衡预算疗法，
因为这会限制我们在经济下滑时使用扩张性财政政策，但在国外，当其他国家陷入衰退时，我们却强迫它们使用紧缩性财政政策；在国内，我们通过破产法来
保护债务人，并且给予他们一个全新的开始，但在国外，我们把破产视为对贷款合同的肆意挑衅；在国内，我们认识到市场的局限性，并不相信市场原教旨主
义，认为政府应该扮演一个重要的角色，但我们却在世界上其他国家推行市场原教旨主义……”

    9、遭遇滑铁卢

    在香港被攻击之的前几年里，实际长期利率是负数，刺激着房地产泡沫迅速膨胀。从1984到1997年，主要物业的价格上涨12倍，造成了经济过热，并导致
人民工资水平和股市狂升。恒升指数在1997年上半年由12000多点升至16800多点，而在7月，恒指更是在短短一个月内连创11次创历史新高，股市泡沫也吹起
来了。房地产泡沫的恶性膨胀还导致了经济环境恶化，因为高房价和高地价将会是使企业的生产成本和销售成本上升，由此推动通货膨胀加剧，经济泡沫进一
步扩大化，如此一来，港币也有了贬值趋势。

    这也是国际金融资本攻击香港的原因——都是泡沫惹的祸。

    随后，国际金融势力通过大批的炒家（以索罗斯为首，还有摩根斯坦利、高盛、所罗门、美林等等）对港币在十几个月的时间里进行了多次进攻。它们的
手法是：低息借入港币，并在期货市场上抛出港币，同时卖空期指；一旦外围市场出现了有利的机会，就疯狂抛售港元，迫使港府挟高利息，利息抬高之后必
然有大量的股民从股市把资金抽出，造成恒生指数暴跌；他们甚至为了达到砸盘的目的会借货抛空股票；当恒生指数暴跌时，索罗斯们就可以套现离去了。

    从东南亚金融危机开始，炒家们先后四次冲击香港。决定性的战役发生的1998年8月。香港政府这一次积极入市，奋起抗击，双方展开了一场厮杀：

    炒家们先是在二三个月前就开始大量的卖空期指，并且大量发售港元债券和抛售美元换港元以备足弹药。从8月初，开始在外汇市场上造谣。什么“联系汇
率不保”、“港元将贬值”，扰乱视听，以期在砸市时形成羊群效应（操纵民意）。接着，索罗斯带着炒家们狙击港元。

    索罗斯们首先狂抛港元砸汇市，仅5日和6日两天就抛售元460亿，港府动用外汇储备全部吃进，同时把吃进的港元存入香港银行体系，稳定银行同业拆借
利息，防止了因拆息率提高带来的股市下跌。之后在国际金融势力的支持下，西方各国对港府进行广泛的口诛笔伐，希望能逼港府让步、放弃护盘行动。但港
府不为所动，坚决入市干预。

    之后索罗斯们又狂抛股票砸股市，到13日时恒指就跌到了6600点。港府在14日挟巨资杀入股期两市，通过三家券商不问价格的狂扫大蓝筹和期货，把恒指
和期指拉起，迫使炒家们事先高位卖空的合约无法于8月底之前如数套现。与此同时，香港金管局大幅提高银行间隔夜拆借利率，阻止对冲基金短期融资，希
望他们知难而退。

    这期间，索罗斯们眼看8月份的期指难以获利，又开始转仓，准备打持久战。而港府也开始在期指市场上买入8月份合约抛出9月份合约，迫使索罗斯们平8
月的仓，并在股市进一步扫货，推高恒生指数。从14日至28日港府共吃进1200亿港元的股票，最终在28日时把恒指和期指都维持在了7800点以上，死守股市成
功。而且，港府并通过成功推高9月份的期指价格打赢了转仓战。

    索罗斯们没能从“超级提款机”上取到钱，反而被吃掉了取款卡。

    10、巧击欧元

    1999年欧元启动，不少国家就表现出了要调整外汇储备结构、减少美元、增加欧元的欲望。美元霸权感受到了威胁。于是，美国开始带着北约的弟兄们开
始对南联盟进行狂轰滥炸，一战下来，整个欧洲都被闹得鸡飞狗跳，吓得许多投资者看好欧元区的经济发展、不敢往欧洲投资了。之后也就没人不再动加欧元
减美元的主意了，欧元的汇率也就软得象刚出锅的面条。这一情况完全出乎了欧盟的想象，最初的时候他们是打算借着美国的力量把俄罗斯的影响力挤出东欧
、实现内部经济和政治整合，进而与美国争霸天下的。结果不光欧元被打的无人问津，还给了美国在巴尔干火药桶再安一颗定时炸弹（科索沃独立）的机会。

看来，欧盟的领导人还是脑子进了水，天下哪有免费的午餐？

    11、进攻中国

    国际金融资本一心惦记着中国的事情是众人皆知的。在这里，我通过几个指标再简单分析一下：

    （1）美元汇率：现在的美元又开始走低了。这是国际金融资本最拿手的本事——赖帐。这也是老招势了，在1985年到 1986年一年的时间里间美元贬值就让
美国赖掉了1/3的债务。当然，国际金融势力还在逼着人民币升值，害得爱国的同胞们天天喊广场协议。其实大可不必，中国不是日本，政治完全独立，升值
不升值我们自己说了算。中央也不傻，人民币强行大幅升值会导致中国经济崩溃，因为中国经济现在是标准的出口拉动型。不过，从长远看，人民币升值是好
事，这样外国货会变得更便宜。但是，人民币的升值速度必须和中国整体科技创新水平的提升挂起钩来，因为只有技术进步才能降低成本，只有产品科技含量
的提高才能抵消利率升高带来的出口压力增大，才能维持足够的出口换汇能力，才能从根本上提高中国企业的竞争力。虽然现代企业理论高强企业发展战略有
三种（成本领先战略、差异化战略和集中战略），但归根到底都要靠加强研发来实现。科技领先才是经济强盛的唯一真正指标。科技领先也是军力强大的最关
键指标之一。

    （2）石油价格：70年代为了稳住美元的位置和制造全球债务泡沫，国际金融资本疯狂拉高油价，最高时达34美元/桶；之后，为了挤垮苏联，又把石油价
格狠压到12美元/桶。现在，为了消化美元滥发的恶果，为了制造更大的债务泡沫，为了用通货膨胀拖垮中国，石油价格又飞到了100美元以上，并在向着200
美元冲刺。为了压制住国际金融势力狂拉油价的局面，中国全面介入中东和平进程势在必行。

（3）中国的外汇储备：现在，中国的外汇储备已超过16500亿美元，而在2002年年底时只有2864亿美元。中国人不是神仙，最近五年挣到的外汇比前50年还多
。很显然，这是有人送货上门的结果。人家的目的就是制造通货膨胀，推动中国营销泡沫的暴涨，等中国的泡沫涨的差不多的时候再撤走挤破泡坏，让中国经
济大伤元气。当然，能不能在人民币升什中套利成功，能不能从推动中国股市和房市泡沫中再捞一把，就看他们的运气了。

    第五章、金融创新的阴谋

    创新，多么动人的名词，可是它一旦和“金融”这个词结合在了一起，就完全变味了。

    1、从金融衍生品的类型看金融衍生品的非法性

    金融衍生品分为远期、期货、期权和互换四大类。

    （1）远期合约在金本位之下是不可能出现的，因为金本位（包括布雷顿森林体系之下）汇率是稳定的，正是由于当年尼克松关闭了美元与黄金兑换的窗
口，才有了今天洪水般的金融投机（即赌博）。守法经营的企业用远期合约进行套期保值是无奈的选择，因为他们没有其他锁定汇率的办法。

    在金本位条件下，谁也不敢操纵汇率，因为那样只能搬起石头砸自己的脚。举个例子：1美元兑换1克黄金，10日元兑换1克黄金，此时美元兑日元汇率是1
：10。假如有人操纵汇率，把美元兑日元汇率提高到1：5来打击日本出口制造业，那将会引发套利行动的出现——拿10000日元可以换到2000美元进而换到2000
克黄金，用2000克黄金可以再换到20000日元，再用20000日元可以换到4000美元……这样一来，等不到日本制造业被挤垮，美国的财富就全流到日本去了。谁受
得了？

浮动汇率的出现，却给国际金融势力一个通过恶性操纵汇率打击他国经济、掠夺他国财富的绝好机会——其实，浮动汇率本身就是他们制造出来的——如果黄金不
与货币脱钩，能有浮动汇率吗？

    （2）金融期货市场更是一个赌场，在这个赌场上没有人去创造财富，只有赌徒们在赌博，对财富进行重新瓜分。金融期货这个赌具的存在，不利于保护
真正的劳动者合法的享受自己的劳动成果。

    87年纽约股市崩盘不就是股指期货的功劳吗？90年东京股市不就是被股指期货这种金融核弹击垮的吗？

    股指的涨落本身就是信心的表现，而股指期货是信心的倍增器。但是，任何股指的上涨都是有限的，也就是说，人们对经济前景的信心是有限的，在股指
期货的倍增放大作用下，人们对股市的信心可能在极短时间内达到顶峰，之后信心必然会受挫，表现在股市上就是股价不再上涨甚至下跌。所以，大规模做空
股指期货必然致股市崩盘。有了股指期货的存在，股市的涨跌更容易被人控制，通过制造和挤破股市泡沫掠夺大众财富也就变得更加容易。

    （3）期权是买方向卖方支付一定数额的权利金后获得这种选择权。看似公平，实则完全非法。买方交纳的权利金并不是用来违约后给卖方做补偿的，而
是用来保证卖方必须履约的，也就是说，如果卖方没有在应该履约的时候把标的物按约定价格卖给买方，卖方必须承担相应的经济责任和法律后果。由于期权
这种产品是虚拟产品，对实际经济生活的影响不那么明显，其非法性对社会的危害几乎表现不出来，如果实际经济合同也以这种方式履约，那就天下大乱了。

    举个例子：一个生产商（卖方）与一个经销商（买方）签订供销合同，经销商支付了权利金（也就是定金），到了生产商交货时，经销商说：“你的货不
好卖，我不要了，定金赔给你作补偿。”这合法吗？绝对不行。经销商的定金是保证生产商如期按量交货的，如果交不了的话生产商要给经销商赔偿损失。但
是，如果经销商随随便便就不履行合同了，那生产商的货卖给谁去？如果所有的经销商都这样做，那生产商还活不活？在经济合同履约中，一般只有不可抗力
出现才可以不履行合同，否则，不但要支付违约金，还要支付赔偿金。

    同时，期权违背了最基本的法律原则：期权的买方只有权利，卖方只有义务——任何权利的实现总是以义务的履行为条件，权利和义务是相伴而生的，可以
不履行义务的权利是绝对权利，是腐败权利，这完全违背了法律的最基本精神，与正义背道而弛。西方社会号称法制社会，自由公正，三权分立，为什么会允
许一种完全违背法律正义精神的商品在广泛销售？法理何在？公义何存？

以后美国财长保尔森再来和我们谈金融开放的问题时，建议中央跟这位仁兄交流一下期权类产品的非法性问题。我们要学习西方先进的东西，但我们总不能跟
着犯法吧？

    （4）互换。顾名思义，就是你的钱我用我的钱你用。这不是明摆了给犯罪分子钻空子的机会吗？自己的资金自己人使用还有监管不到位出事的时候，自
己的资金放到别人手里，天知道能出什么事。都说“在西方法律钻人人的空子”，法律多么的健全，看看这些金融产品，怎么感觉都是在说谎呢？

    不得不说明的是，大多数的金融衍生品业务如远期、期权、互换等都属于表外业务。表外业务就是不列入资产负债表、不形成现实资产负债但能增加银行
收益的业务。不要以为不形成现实资产负债就能白捡大便宜，恰恰相反，经营者更危险了，因为他们往往死的时候都不知道自己是怎么死的——巴林银行就是死
在表外业务上的，法国兴业银行亏那49亿也全拜表外业务所赐。表外业务发展过程中，巴塞尔协议（资本充足性标准）要居首功。当初，美英两国央行联手推
这个文件的目的，就是为了促使全世界的银行搞投机的，为了推动全球经济泡沫化的。他们自己的银行都是造泡沫的高手，自然不吃亏。可是，那些本来通过
对实业的投资来赚取合法利润的银行怎么受得了这种东西？因为它要求银行的资本充足率太高。银行为了赚钱只能扩展金融衍生品这类表外业务——这叫什么国
际标准？完全是在逼良为娼！

     2、从金融衍生品的特点看金融衍生品的危害性

    （1）高风险性。金融衍生品号称是为了“避险”而出现的，可是，它出现了之后，世界各国经济运行的风险更大了。看看20世纪80年代以后的历次金融危
机，那一次没有金融衍生品的功劳？东南亚金融危机时中国没有卷入其中，不是中国的经济体质多么强健，而是中国经济没有开放，也没有那么多的金融衍生
品存在。事实上，当时的中国经济远不如东南亚各国好——四大银行性术性破产就在那个时候。如果中国经济也象东南亚国家那样开放，如果中国的金融创新也
象美国那样发达，恐怕当时的中国人得有一半上大街要饭去了。

    （2）高杠杆性。以小搏大，给了金融赌徒们获得暴利的机会。结果就是风险多倍放大，个别风险放大成了系统风险，为大范围的金融危机出现创造了良
好的条件。后面分析对冲基金的时候再做详细说明。

    （3）虚拟性。金融衍生品是建立在现实基础资产之上的，但它们的规模已远远超过了基础资产市场规模，这就是所谓的“倒金字塔”。

    经济“倒金字塔”理论是德国经济学家特南鲍姆提出的，他认为，各国全部经济金融化的价值可以构成倒置的金字塔结构：第一层是金字塔的底，是以实物
形态存在的物质产品；上面是商品和真实的服务贸易；第三层是股票、债券、商品期货等；最上层是完全虚拟的金融衍生品。

    现在的金融衍生已经发展到了发疯的地步：1980年时，全世界的金融衍生产品是零，到2006年，这个市场的总规模却达到3700000亿美元！相当于全世界
的GDP总和的8倍多。如果没有金融全球化，倒金字塔是不可能高速发展的，倒金字塔的发展，就是西方国家整天玩“以钱生钱”买卖的结果——这倒有意思，不用
干活，对着开支票就能发财，就能过好日子，这不是天上掉馅饼吗？当然不是，有中国这样的国家在卖苦力，人家自然可以靠画假饼来换真饼。不过，傻子都
知道，头重脚轻是要摔跟头的。倒金字塔能撑多久？轰然倒地的时候，就是全球金融体系崩溃的日子。在下一节有对次贷危机那个小倒金字塔从建立到倒塌全
过程的详细分析，可以帮助大家见识一下西方金融精英的能耐。

    中国如何逃此一劫？避免经济泡沫化，改变单纯依靠出口拉动经济增长的模式。如果中国经济体没有泡沫，这场浩劫将与中国无关，反而可以给中国崛起
的机会。泡沫就是泡沫，再大也冲不动石头，弄不好反被石头刺破把自己栽进去。只要我们的经济体对外信赖性不大，在倒金字塔倒掉引发全球经济危机的时
候，中国经济受到的冲击就会很小；反之就是大麻烦。


** 【金鸿95】国际金融战探密（连载九）
   [2008-04-14 09:46:03]

   
    3、资产证券化看金融衍生品的非法性

    资产证券化是指将缺乏流动性的资产，转换为在金融市场上可以自由买卖的证券的行为。乍一看，很合理，可以增强流动性，大家的投资机会也增加了，
多好。但是反过来想一下：人家为什么把发财的机会让给你？谁傻呀？

    还是用一个事例来说明资产证券化的危害吧，这个例子就是今天备受世人关注的次贷危机：

    在美国，有一个相当数量的低收入人群，他们无法通过贷款买房子，因为按照严格美国房屋贷款审查程序审查，他们是达不到标准的。但从1980年以来，
美国一些投资银行开始降低贷款门槛，这就出现了比以往信用标准低的购房贷款，这就是“次级抵押贷款”，简称“次贷”。

    次贷的出现，好象是一件好事：对买房人来说，零首付可以买房，非常有诱惑力，虽然要付出更高的、随时的浮动利息；对放贷机构来说，可以获得更高
的收益，两边都有好处。20世纪90年代美国经济运转良好，次贷没出什么事。进入21世纪后，次贷风行美国。特别是 911发生后，为保美国经济稳定运行，格
林斯潘不顾一切的放水，4年内连续25次降息，联邦基金利率从6.5%降到1%。这一下可好了，泡沫有了疯狂膨胀的机会。所以，今天的次贷危机里面，绝对有
格老的大功。

    超低的利率、无需担保、无需首付，房价一路高升，不买房子的绝对是白痴。欣欣向荣的美国，天堂一般的美国……

    在次贷发展最快的2003~2006年，投行稳赚超高利润，贷款人房产升值，绝对双赢。但是，所有这一切都是建立在贷款人能得起款的前提下的，如果到时
贷款人还不起债了，那可就砸锅了。到2006年末，次贷已经涉及到了500万个美国家庭，规模达到了1.1万亿至1.2万亿美元。

    泡沫吹到了足够大的时候，就到了挤破的时候了，不然怎么抢钱？从2005年到2006年，美联储先后加息17次，利率逐渐提高到5.25%。房地产泡沫开始破
灭。本来次贷的贷款人就是穷人，这时房价一跌，他们还不起贷款了。投行就开始收贷款人的房子，不过，这时收回的房子现在也没人要了，还在不断贬值，
许多投行的周转也困难起来。从2007年2月开始，问题全暴露出来了，结果，新世纪金融公司第一个趴下了。

    如果只是次级贷款出了问题，也算不得一件大事。因为次贷占美国整个房地产贷款的14.1%，大约在1.1万亿到1.2万亿美元之间，据高盛测算，里面的坏
帐只有4000亿美元。在2006年美国的GDP就有15万亿美元，完全消化的了。可问题是金融创新在里面使劲了——资产证券化：

    美国的投行也知道次贷高回报的背后是高风险，为了防范风险，也为了找到更多的资金来源支撑更大规模的放贷从而获取更多的收益。他们就打起了金融
创新的主意，将一个个单体的次贷整合打包做成次级抵押债券CDO。干这个生意的投行都是欧美的顶级银行，象美林,，花旗，雷曼兄弟，贝尔斯登，美国银行
，德意志银行等等。但是，这个东西的高风险性是大家都知道的，所以销路不畅，怎么办？这难不倒银行家们，他们把债券分档：优先产品、中间产品和股权
产品。优先产品和中间产品的质量好、收益比股权产品低一点。然后找来穆迪、标普这些世界级的信用机构给优先CDO评了个AAA级。然后，银行家们开始大施
拳脚了：

    先在无人监管的“洗钱天堂”开曼群岛注册一个独立承担法律责任的SPV（特殊目的机构），用它把所有的CDO买下来再销售，这样将来有一天CDO捅了篓子
就与投行们没有关系了。有了3A的等级，又有高利润，各种大型投资基金和国外投资机构纷纷吃进优先CDO。

    剩下的高风险的中间CDO和股权CDO可就没人要了。当然，这点小事考验不住顶级银行家的智慧。他们再出钱成立了独立的对冲基金, 然后将中间CDO和股
权CDO高价卖给了对冲基金——以后再出事就全是对冲基金的了。在格林斯潘超低利率的支持下，形势一片大好，房地产市场繁花似锦，次级贷款拖欠的比率也
远低于原来的估计。CDO的购买者们抱着高利润的CDO哪舍得出手？结果，CDO市场一直是门可罗雀。因为没有可靠的价格信息作参考，金融监管部门允许对冲
基金按照内部的数学模型计算结果作为资产评估标准。这样一来就相当于收益率允许随便吹。很快，高利润招来了大量的投资者，他们大把的投钱入伙抱着中
间CDO和股权CDO的对冲基金。既然所有人都看好这些CDO，在对冲基金经理拿着它去找商业银行要求抵押贷款时，商业银行就不能不给面子了。他们大把的借
款给对冲基金。在这期间，对冲基金向银行抵押贷款的杠杆比率最高的能达到15倍。对冲基金拿到商银的钱,再向自家的投行买进更多的CDO。一个完美的良性
循环。

    随着次贷被打包做成了次级抵押债券，单个的贷款风险变成了打包债券的整体风险。一旦部分贷款变成了坏账，整个一包次级抵押债就变成了“垃圾债”。
风险也从投行转到了次级债的购买者手里。目前，这些次级债主要分散在五类金融机构手中，包括银行(31%)、资产管理公司(22%)、对冲基金(10%)、保险公
司(19%)和养老基金(18%)。现在，这些金融机构损失惨重。到今年1月底，花旗、汇丰、UBS、美林、摩根斯坦利等大型银行和证券公司，已经撇账900亿美元
；当然，欧洲的银行也受损不轻，包括法国兴业银行、巴黎银行，英国北岩，瑞士瑞银。

    在各国购买了次级债之后，风险就转移到了美国之外——全世界人民帮助美国穷人购房还贷。谁说资本主义制度下没有雷锋？从这里可以看出，这一次挤破
次贷泡沫打劫的对象主要是欧盟和美国的中产阶级。巴菲特说得好，这些证券可能是金融大规模杀伤性武器，就象一个吃人的怪物。现在，中国也在忙着资产
证券化。看来，许多中国人喜欢怪物，管它吃人不吃人。

    现在，虽然中间CDO和股权CDO卖的很好，但是，如果出现了违约，风险还得由银行家们承担，怎么才能把风险转嫁出去呢？再进行一次金融创新——信用违
约交换CDS。CDS是一种和保险合同类似的金融衍生产品。这个产品也由投保人和承保人两方组成，投保人是发行CDO的投行们。投保人把CDO的违约风险卖给承
保人。承保人就可以按月从投行那里得到一笔收入。在风险出现以前，承担风险的承保人并不需要出任何资金，也不需要与被保险的CDO有任何关系，只需要
顶上一个承担CDO违约风险的人头就可以按月得钱。当然签订合约的两方都可以把CDS合约转售给其它人。这个CDS的确有诱惑力，之前一分钱不用出白赚收益
！这不是天上掉馅吗？许多金融机购纷纷作为承保人买入合约。同时，许多买CDO的投资机构也从投行那边转买CDS成为投保人来避险。CDS想不火都不可能了
。如此一来，投行手中的垃圾CDO的风险又转移了出去。

    在次级债市场开顺车的日子里，信贷违约掉期合同是非常便宜的（就是说每月付给承保人的费用很低），因为大家都认为次级债没有什么风险，低风险的
保险合同自然是低价格的。不过，在次贷危机爆发后，次级贷款违约率上升了，保费就开始上涨，这时购买CDS就非常的不划算了。之前的承保人也就付出了
高昂的代价——他们得替CDO违约风险买单了。

    事情到这里还没有结束。投行又在CDO的基础上进行了再一次的金融创新，这是一种什么好东西呢，就是投行把自己卖股权CDO的每月收益垫底，发行一个
用来购买CDS的基金（做CDO的承保人）。也就是说，购买者现在顶一个承担CDO违约风险的人头，就可以按月从CDO投保人那里得钱，在CDO出事之前不用做任
何事；而且，如果CDO出现了违约风险，投行还有个底子先垫在那里赔，它赔完了别人才会赔——常听人说天塌下来有高个子的人顶着，这回真在华尔街遇上了
，这可是打着灯笼都找不找的好机会，不抢那叫傻子！各种养老基金、教育基金、外国银行又纷纷加入了购买行列……

    其实，股权CDO的违约风险是CDO中最高的，当这些垃圾债券出现大比例违约时，哪里还有什么收益？所以，当天真塌下来的时候，世人才明白，原来自己
是为华尔街顶着的。

    在CDO风行的时候，华尔街的天才们还发明了另一个金融衍生品ABX，它叫次级房屋贷款债券价格综合指数。当次贷风险升高、CDO价格下跌时，ABX指标随
之下滑。这个ABX有点象股指期货，股指期货可以卖空股指获利，ABX则可以看空次级债市场获利。在死伤遍地的次贷危机中，有几个对冲基金就是靠着这个东
西大发利市，其中一个叫保尔森的，就连索罗斯都其“请教”做空楼市的细节（是不是演戏我们就不得而知了）。当然，高盛也通过看空次贷市场收入了达40亿
美元，冲销了在次贷证券上的10多亿美元损失。他们的做法也不复杂：就是买入CDS信贷违约保险产品（承保人身份），做空ABX指数相关衍生产品。在次贷债
券违约不断增多的时候，CDS的价格不断走高，低买高卖赚一笔，ABX指数不断走低，做空又赚一笔。一般说来，做空市场的东西都是资本市场走熊的刽子手，
现在还不知道ABX在次级债市场崩溃的过程中起到了多大作用。

    当全世界都在为次贷危机买单的时候，华尔街居然还能有人大笔的赚钱，这可真是本事。

    美国的国父们有一句名言:“创造价值的不应该贫穷,不创造价值的不应该富贵”，今天控制华尔街的那些富贵人绝对不符合美国国父们的标准。如果今天主
宰美国的还是美国的那些国父们那样的共和势力的话，金融衍生品绝对不可能在美国泛滥到今天这一步。他们也绝对不会看着自己人民的财富任由别人劫掠。
这是路线问题，古今中国，盖莫能外。今天的美国，是民主的美国；但是，今天的美国，已绝对不是那个自由的美国。

    现在总得看一下次贷危机，是一场标准的由金融衍生品引发的金融危机。危机爆发之前形成了一个小型的“倒金字塔”：第一层是金字塔的底，是为次级信
用人建造的房子；上面是建筑商、购买者、银行、广告公司等等；第三层是次级抵压贷款；第四层是次级债CDO；第五层是信用违约交换CDS，上面还有个第六
层。当第三层的次贷人还不起贷款时，整个倒金字塔就崩溃了。如果没有上面的三层金融衍生品，危机是受控的；可有了上面的三层以后，天知道牵扯进来了
多少企业、银行和国家。

    次贷危机爆发只是一个小的倒金字塔倒了，如果那个比世界GDP大多倍的大的倒金字塔倒了，会是怎么的一番场景呢？大家可以展开想象的翅膀，充分的
发挥一下自己的想象力。

    在看完了次贷危机之后，我们就可以发现资产证券化的非法性在哪里了：因为债务可以做成债券，债券的流动性又那么好，所以，一旦债务无法偿付形成
死债，那倒霉的就是购买债券的人，而不是发放债务的人。在债务不能做成债券转移风险之前，贷款机构是非常小心谨慎的，不然损失得由它自己来负担；但
是，一旦允许证券化，贷款机构的风险就可以转嫁，这时，它还关心贷款质量高不高吗？它还去严格审核贷款资质吗？它只会拼命的拉人来贷款，然后把贷款
做成债券卖出去。用债券的方式投资也好，刺激消费也罢，都可以在一定程度上起到刺激经济发展的作用，但前提前贷款质量要有保证，否则贷款就不是在刺
激经济发展，而是在埋地雷了。从这个意义上说，证券化是在鼓励贷款机构不负责任的放贷，是在放纵经济犯罪。如果说放贷是在烤火取暖的话，贷款做成债
券就是点了火之后置之不理。

    其实，金融创新都是为了增加流动性的。没有流动性是不行的，但是，流动性太强同样不行。拿河水来说，完全不流动的河水是死水，要臭的；但河水流
动的最快的时候同样是大麻烦。因为那是洪水肆虐的时候。如果把一国经济体比作一块大陆，那么资金流就是大陆上的河流湖泊，这些河流湖泊里的水都不流
动是不行的，因为那样整个大陆将没有生机；但是，水流的太快同样是不行的，那时，水流会冲垮堤岸，为害无穷。当把所有的河流都用运河连通了起来时（
相当于越来越多的金融限制被取消），表面上是好事，洪水来了可以分流洪水的压力，但是，如果有人在洪水来临的时候恶意堵住了某些河道、把河水集中灌
向某一条河呢？这条河的周围就要遭殃了，河堤被冲毁，村庄田地被淹没……

    事实上，在没有恶性破坏力存在的情况下，流动性是必然的。因为资金流动意味着商品交换的正常进行。在一个存在劳动分工的经济体里，进行交换是每
个个体必然要进行的行为，因为他们要生存；相反的，我们要担心的是，流动性过强的恶果——为制造危机扫清道路。所以，金融管制是必须的，而且是必须严
格的。

    4、金融创新创造出的吃人怪兽——对冲基金

    对冲基金还有好几个别名，其中最好听的一个叫避险基金；其实，许多的金融灾难都是它们制造的，所以，套利基金的名字是最恰当的；因为一般要求入
伙人的出资在100万美元以上，与穷人无缘，所以又叫富人基金。

　　对冲基金往往通过制造市场价格波动，在市场恢复正常状态时获取差价，以获取超额利润。比如在东南亚金融危机中，量子基金通过沽空泰铢远期合约、
抛售泰铢造成泰铢汇率暴跌而获得收入。由此可以看出，对冲基金的赢利往往是建立在他人的痛苦之上的。

　　对冲基金以极高的杠杆从银行借贷，从而达到最大程度地获取回报的目的。通过杠杆效应（数十倍很正常），对冲基金可以获得极高的利润率。这里就出
现了一件怪事：一般说来，银行放货都是非常小心的，他们要考虑对方的还款能力。可为什么他们会给对冲基金如果高的信用额度呢？对冲基金干得本身就是
极为冒险的买卖，大银行们为什么会如此信任他们？要知道，在制造金融危机的时候，他们往往可以借到上千亿美元的资金。谁会有这么大的面子？再就是，
如果银行这么有把握能赢利，他们为什么不知道去投上钱做这些事，而是把钱借给对冲基金去做？这不是给别人做嫁衣裳吗？

    对冲基金的组织结构一般是合伙人制。基金投资者出资金不参与投资活动；基金管理者出一部分资金和技能，负责基金的投资决策。由于对冲基金多是私
募并且门槛极高，所以基金信息非常保密工作做的非常好。为了避税和逃脱监管，在美国市场上进行操作的对冲基金一般都在巴哈马和百慕大等一些税收低，
管制松散的地区注册，募集资金也只找美国境外的投资者——美国政府居然能眼看着有人在自己眼皮底下发大财不交税还能做到不闻不问，这里面能没有蹊跷？
在他们把市场搅得天翻地覆却美国政府不怪他们，这又是为什么？比如这一次的次贷危机，使用高倍杠杆在一线点火导致次贷危机火烧全球的就是对冲基金。

    其实，人家不光不管，还处处护着对冲基金。比如在1998年时索罗斯攻击香港，被港府迎送痛击，这本来是当地政府维护地区经济稳定运行、保护地区居
民财产的好事，却被美国官方和经济学者指责为违背自由市场原则，损害了香港的长远利益，难道香港被索罗斯抢光了才是在保护香港的长远利益？

    2007年八国集团峰会上，默克尔主张对对冲基金实施由政府主导的强制性监管，并为对冲基金的运作制订行为准则。默克尔指出，如果不加强监管，全球
范围内运作资金规模已达1.5万亿美元的对冲基金可能会对各国乃至全球金融市场的稳定构成威胁。但默克尔的建议遭到了布什和布莱尔的强烈反对，日本也
不敢吱声，只有我们胡主席和默克尔站在了同一战壕。从这里也可以看出来，对冲基金的后台不小。

    其实，象量子基金那样的对冲基金，本身就是国际金融势力手下的敢死队。他们通过对冲基金制造金融动荡、掠夺别国财富，转嫁风险和责任。比如，在
制造危机时如果对冲基金赢了，赢利远在100%以上；如果赔了，结果就借款给对冲基金的银行来买单，损失就成了银行的全体股东来负担了，因为对冲基金的
底子本身就少，赔光也都不够，而且还把恶名全兜了去。好不精明的算盘！

    第六章、地狱之门与希望之路

    1、人类的伟大创举：

    从工业革命到现在，不足240年，人类创造了巨大的生产力，也为自己在一百年内走向灭亡做好了充分准备。地球是人类的摇篮，地球给予我们人类的太
多太多，可我们回报地球母亲的是什么呢？是无餍足地索取。看看今天的地球被我们人类改造成了什么样子吧：

   （1）水污染。地球上水所覆盖的面积为3.8亿平方公里，约占地表面积的70%。但是淡水储量仅占2.5%，人类实际能开发利用的淡水又只占淡水总量的0.3%
。与19世纪相比，20世纪世界人口增加了２倍，而人类用水却增加了5倍。在一些发展中国家，约50%的饮用水和60%的灌溉用水因使用不当而浪费；全世界每
年约有4200多亿立方米污水排入江河湖海，使5.5万亿立方米淡水受到污染，这相当于全球淡水径流总量的14%；过度抽取地下水使许多地区水位下降了几十米
；世界面临的水资源短缺已非常严峻：12亿人用水短缺，30亿人缺乏用水卫生设施，每年有300万到400万人死于和水有关的疾病。预计到2025年，水危机将蔓
延到48个国家，约35亿人将为水所困。现在，我们还不能造水，我们只能设法保护水。不要认为这是杞人忧天，正在举行的博鳌亚洲论坛上，理事长拉莫斯不
就说第三次世界大战可能会为争夺水资源而起吗？

    （2）土壤污染荒漠化。化肥和农药过多使用，与空气污染有关的有毒尘埃降落，泥浆到处喷洒，危险废料到处抛弃，对土地构成了不可逆转的污染。110
个国家（共10亿人）可耕地的肥沃程度在降低。在非洲、亚洲、和拉丁美洲，由于森林植被的消失、耕地的过分开发和牧场的过度放牧，土壤剥蚀情况十分严
重。裸露的土地变得脆弱了，无法长期抵御风雨的剥蚀。在有些地方，土壤的年流失量可达每公顷100吨。滥砍滥伐、毁林造田、过度开垦、过度放牧使荒漠
化情势加剧。现在，地球上每分钟就有10多公顷土地被沙漠吞噬，也就是说沙漠正以每年700万公顷的速度扩展。日趋严重的荒漠化正威胁着10多亿人的生存
，成为全球性的重大环境问题之一。（与此相关的粮食危机也逐渐表现了出来）

    （3）全球变暖。联合国有关机构最新报告预测，假若全球温室气体减排计划得不到有效的实施，21世纪全球的平均气温将上升1.8至4摄氏度。如此下去
，人类总有一天会掉进自掘的“热陷阱”里而不能自拔。据2500名有代表性的专家预计，海平面将升高，许多人口稠密的地区（如孟加拉国、中国沿海地带以及
太平洋和印度洋上的多数岛屿）都将被海水淹没。气温的升高也将对农业和生态系统带来严重影响。

    （4）森林减少。最新一份统计报告说，全世界森林面积每年都会减少1300万公顷。森林消失不仅影响生物多样性，还会影响水源和土壤，对温室气体减
排也会产生不利影响。大城市里的生活条件将进一步恶化：拥挤、水被污染、卫生条件差、无安全感……这些大城市的无序扩大也损害到了自然区。无限制的城
市化正在成为人类文明的新弊端。

    （5）工业污染。工业带来的数百万种化合物存在于空气、土壤、水、植物、动物和人体中。即使作为地球上最后的大型天然生态系统的冰盖也受到污染
。那些有机化合物、那些重金属、那些有毒产品，都集中存在于整个食物链中，并最终将威胁到动植物的健康，引起癌症，导致土壤肥力减弱。多数大城市里
的空气含有许多取暖、运输和工厂生产带来的污染物。这些污染物威胁着数千万市民的健康，导致许多人失去了生命。每年春天，在地球的两个极地的上空仍
再次形成臭氧层空洞，北极的臭氧层损失20%到30%，南极的臭氧层损失50%以上。

    （6）物种减少。由于城市化、农业发展、森林减少和环境污染，自然区域变得越来越小了，这就导致了数以千计物种的灭绝。地球上物种消失的速度在
加快，主要生态系统几乎都存在物种数量下降的问题。科学家们估计，每天都有若干个物种消失，再由于生物链的作用，地球上每消失一个物种，往往会引起
与之相关的更多物种的消亡。人类如不尽快采取措施加以遏制，地球上近1/4的物种在未来50年内将遭受灭绝之灾。生物多样性是由生物及其生存环境共同构
成的一个大生物圈系统，倘若它的平衡被严重打破，人类恐怕就难逃与恐龙一样的厄运了。

    看一下人类改造世界的杰作，真是触目惊心。这是征服自然吗？这纯粹是在慢性自杀！现在我们应该好好想一下了：究竟是什么原因让人类走上这不归路
的？


** 【金鸿95】国际金融战探密（连载十）
   [2008-04-14 09:52:42]

   金鸿：喜欢这篇文章的朋友尽管转贴，只要注明作者即可。

   2、中华民族的伟大成绩

    目前，中国的荒漠化土地已达267.4万多平方公里，占国土面积已达27%；全国18个省区的471个县、近4亿人口的耕地和家园正受到不同程度的荒漠化威胁
，而且荒漠化还在以每年1万多平方公里的速度在增长。北方地区因沙漠化诱发的沙尘暴频率加大；中国大部分草地已经退化。其中中度退化程度以上的草地
达1.3亿公顷，约占草地面积的1/3，并且每年以200万公顷的速度增加。

    七大江河水系中，完全没有使用价值的水质已超过40%。全国668座城市，有400多个处于缺水状态。其中有不少是由水质污染引起的。如浙江省宁波市，
地处甬江、姚江、奉化江三江交汇口，却因水质污染，最缺水时需要靠运水车日夜不停地奔跑，将乡村河道里的水运进城里的各个企业。中国平均1万元的工
业增加值，需耗水330立方米，并产生230立方米污水；每创造1亿元GDP就要排放28.8万吨废水。还有大量的生活污水。其中80%以上未经处理，就直接排放进
河道，要不了10年，中国就会出现无水可用的局面。

    全国1/3的城市人口呼吸着严重污染的空气，有1/3的国土被酸雨侵蚀。经济发达的浙江省，酸雨覆盖率已达到100%。酸雨发生的频率，上海达11%，江苏
大概为12%。华中地区以及部分南方城市，如宜宾、怀化、绍兴、遵义、宁波、温州等，酸雨频率超过了90%。在中国，基本消除酸雨污染所允许的最大二氧化
硫排放量为1200万~1400万吨。而2003年，全国二氧化硫排放量就达到2158.7万吨，比2002年增长12%，其中工业排放量增加了14.7%。按照目前的经济发展速
度。以及污染控制方式和力度，到2020年，全国仅火电厂排放的二氧化硫就将达2100万吨以上，全部排放量将超过大气环境容量1倍以上，这对生态环境和民
众健康将是一场严重灾难。

我国农作物平均每年受旱面积达3亿多亩，成灾面积达1.2亿亩，每年因旱减产平均达100亿-150亿公斤，每年由于缺水造成的经济损失达2000亿元。目前，全
国420多个城市存在干旱缺水问题，缺水比较严重的城市有110个。全国每年因城市缺水影响产值达2000亿至3000亿元。

    在《濒危野生动植物物种国际贸易公约》所列的640个物种中，我国占156个。动物资源中，全国列为一级保护动物有97种，二级保护动物238种。在植物
资源中我国珍稀濒危植物共有389种。我国已有15%-20%的动植物物种受到威胁，高于世界10%-15%的平均水平。

    在过去20多年里，国内制造业不是依靠技术进步降低能耗、降低成本，而是朝在另外两个方面挖潜:一是工资，二是环保。举个例子，水泥生产要达到起
码的环保要求，每吨水泥需增加8元成本，占水泥出厂价的5%。在中国，要真正有效地控制环境，环保投入须占到GDP的3%以上。而在过去20年里，中国每年在
环保方面的投入，在90年代上半期是0.5%，环保是一种“奢侈性消费”，投入大，对GDP贡献小，因此，大量的环保方面专项资金被挪作他用。再举个例子：云
南滇池周边的企业在过去20年间，总共创造了几十亿元产值，但要初步恢复滇池水质，至少得花几百亿元。淮河流域的小造纸厂，20年累计产值不过500亿元
，但要治理其带来的污染，即使是干流达到起码的灌溉用水标准也需要投入3000亿元。要恢复到20世纪70年代的三类水质，不说花销，光时间至少需要100年
。

    据中科院测算，目前由环境污染和生态破坏造成的损失已占到GDP总值的15%，这意味着一边是9%的经济增长，一边是15%的损失率。环境问题，已不仅仅
是中国可持续发展的问题，已成为吞噬经济成果的恶魔。 2005年，中国刮起了一场环保风暴，30个总投资达1179亿多元的在建项目被国家环保总局叫停，其
中包括同属正部级单位的三峡总公司的三个项目。原因是这些项目未经环境影响评价，属于未批先建的违法工程。（胡温政府为人民办事呀）

    我们的成绩也不小。这样发展下去，谁敢说我们还在这片古老的土地上再生活一百年？我们想把自己的子孙后代置于何地？究竟是什么原因导致了今天的
局面？

    3、都是市场经济体制惹的祸

    很显然，这一切的一切都是人类放纵自己贪婪欲望的结果。我们这个地球可以满足60亿人的生存需要，却无法满足6个人的贪婪欲望。究竟是什么让我们
人类变得如此贪婪？如此可怕？一步步的把自己逼上了绝路还在欣然自得？

    答案是：是市场经济体制造成的。

    市场经济体制的本质就是纵欲经济，它放纵人们的欲望——所有的个体（无论是个人还是企业或者其他组织）都在追求自身利益的最大化，满足自己的私欲
（以物质需求为核心），却把人类对精神需要的追求扔到了一边。正如赵蕤所说：“匠成舆者，忧人不贵；作箭者，恐人不伤。彼岂有爱憎哉？实技业驱之然
耳。”每一个个体都在为了实现自身利益的最大化而努力时，也就顾不得整体的利益了——只要能使消费者当时感觉满意就好。

    举个例子，现在大家都知道，在美国大多数家庭都有几台彩电。这说明美国富裕。对此，我们也很羡慕，也希望中国的每个家庭也都能摆上两三台。但是
，是否有必要呢？对个人来说，是好事，对整个社会而言呢？制造彩电是需要资源的，向大自然无度索取的结果是什么？不就是上面那些触目惊心的事实吗？
但是，在市场经济条件下政府能管吗？政府能禁止一个家庭买两台彩电？还是政府能够限制哪一家彩电企业的生产规模扩张？所有的企业都要为了生存和竞争
对手拼命，如何平衡这其中的利益关系？再拿家用电脑做例子，现在的电脑更新速度极快，绝大多数电脑用不到报废就换了。的确，随时用最新式的机子很舒
服，但是，淘汰下来的机子怎么办？还有手机，更新换代的速度更快。有谁知道电脑电视手机等电子产品垃圾的危害性有多大？它们当中含有铅、汞、镉等重
金属元素，这些属金属很容易进入土壤和水里，从而给人类和环境带来长期的危害，而处理这些垃圾的代价是极为高昂的，欧美发达国家都为这个东西犯愁。
当然，他们为了转移麻烦往往向中国这样的发展中国家大量出口电子洋垃圾，这样就可以保证他们国家的山清水秀——其实，中国进口的洋垃圾何止电子洋垃圾
一类呢？

    这只是一个电子类消费品行业的例子而已，其他哪个行业不是这样？一边是无度的索取，一边是大量的制造垃圾，结果是什么？

    打个比方，地球是一个参天大树，人类是数上的蛀虫。在一定范围内，蛀虫从树上吸取养分对大树造不成实质性损害，因为它有再生能力。但是，一旦蛀
虫越长越大，数量越来数多时，大树就吃不消了，终有一天，大树会被啃死。之后的蛀虫去哪里生存？再找一棵大树？如果找不到新的大树呢？

    只要“要求自由竞争”的市场经济存在，人类无度的向自然索取的局面就不可能改变，整个自然环境被破坏是必然的，接下来就是自杀。如果人类还希望自
己的子孙后代能够长久的在这个世界上活下去，这种经济发展模式必须进行根本性调整。本来，市场经济对人类的纵欲行动就是放纵性的；从20世纪60年代以
后，国际金融势力搞出了所谓的“后工业时代”政策，人类也从工业社会进入了后工业社会，之后人类更加变本加厉起来。本来，他们这样做的目的是为了放任
人们的消费、甚至信贷消费，进而让人们还不起债，成为债务的奴隶。但是，“后工业时代”的经济政策鼓励的是浪费性消费品的大量消费，从而大大加剧了人
类对大自然供应能力的透支行为。这就更加导致了环境的恶化。我不知道那些顶级富豪们是怎么样想的，也许他们是希望自己的儿孙也能永享荣华富贵，可是
，这样做的结果却是一起下地狱。他们的儿孙要是知道会有这样的结果，会不会恨死他们那些当父母的呢？如果现在知道了这个结果，他们会不会改变主意、
为别人也为自己和自己的后代留一条生路呢？

    当然，在市场经济体制下，从自由竞争走向垄断是不可避免的。资本主义世界也由此经历了从自由竞争到垄断资本进而到今天的国际金融垄断资本三个阶
段，金融资本垄断是垄断的最高形式。在某一个行业中，单纯的企业垄断是可以打破的——将垄断企业解体即可；但是，金融垄断是无法打破的——总不能把一个
银行家的家产给分了吧？今天的美国，由洛克菲勒财团、摩根财团、第一花旗银行财团、杜邦财团、波士顿财团、梅隆财团、克利夫兰财团、芝加哥财团、加
利福尼亚财团、得克萨斯财团控制着美国的经济命脉，每个财团控制着同一个行业的多家企业，这些财团之间又有着千丝万缕的联系并且掌握在少数人手里，
这种垄断如何打破？只有无产阶级革命了。随着金融垄断的形成，专制社会就形成了。原因很简单，既然极少数人控制着国家的经济命脉，政府必然是为金融
资本代言的——经济基础决定上层建筑，如此一来，普罗大众的利益谁来照顾？

    有许多人建议，为了对付国际金融势力对中国银行业的冲击，也为了给国内私人资本以国民待遇，应该允许中国人开银行。这样做的后果是什么？中国金
融资本势力又起来了。就算前面赶走了狼，后面又来了虎，结果还是大麻烦。今天的国际金融势力是我们的死敌，但是，就算我们消灭了他们又如何呢？在市
场经济体制下，还会再出现新的金融资本势力，这是必然的。接下来再消灭第二次的金融资本势力？再出现了第三代的怎么办？

    4、  眼前之计

    当然，在国际金融势力对我们虎视眈眈、欲除之而后快的今天，迎接挑战是必然的。所以，下面几方面的功课是必须做好的：

    首先要做好宏观发展规划，这个规划不仅仅是经济层面的，它包括政治稳定和干部队伍整顿、经济发展、环境保护、计划生育、教育科研投入、社会福利
等等在内的系统的、长期的规划，以保证做到我们是在社会进步而不是断子孙的后路。

    其次解决好经济结构调整和产业升级问题，宏观层面上必须改变经济发展严重依赖出口拉动的局面，完善社会保障体系，扩大内需，减少对外依赖性；中
观层面必须调整产业结构，比如家用汽车制造业，根本不适合做支柱产业，必须把各行业的主导权从外资手里抢过来，我们的经济命脉不能让别人控制，微观
企业层面就是要加大研发投入，加快技术进步步伐，政府政策要配套，以提高企业产品附加值，培养优势产业群，引导资产正确流向，避免经济泡沫过度膨胀
。

    第三，对热钱的流入需要严防死守。在目前情况下，热情流入中国不一定非要制造股市和楼市泡沫，因为在中央政府的调控之下他们可能没有机会了。但
是它们照样可能大批的流入，巨额热钱流入会推动通货膨胀，制造营销泡沫；进来的热钱要控制好，不能任其乱窜，更不能任其随便再流出。一旦这些热钱制
造起了巨大的营销泡沫再猛的全部流出，将造成严重的通货紧缩，引发危机经济，这样对手就可以找到控制我们经济命脉的机会，他们甚至能以此为契机制造
社会动乱和颜色革命，危害我们的国家安全，颠覆我们的人民政权。

    第四，严格控制金融业务自由化，因为它助长了投机的盛行，金融机构也不再以发挥“经济血库”作用、为经济发展增加血液为核心，转而以投机炒作、“
以钱生钱”为核心，如此一来，人们越来越不愿意通过诚实劳动去换得财富，都去跟着投机，社会风气也会跟着堕落。同时，杜绝金融衍生产创新。

    至于国际金融层面，问题太大。要改变就得动大手术。国际金融势力控制着世界金融命脉，他们是不会允许改革的，因为那相当于让他们破产。我们只有
把经济结构调整好，降低对出口拉动的依赖，做好足够的能源、矿产和其他战略资源储备（控制相关公司也可以），提高科技实力，增加军队战斗力和企业竞
争力，就能稳住阵角，在全球金融体系崩溃的时候不但可以独善其身，还能获得逆风起飞的机会。

    2、希望之路

    从长远看，只有计划经济体制，才能控制人类整体的贪婪欲望，在人类总需要与地球供应能力之间达成一个平衡，保证既满足人类的正常需要，又不透支
地球母亲的体力，这样才能做到人与自然的和谐相处（单个的国家同样如此）。而且，计划经济更公平，更有利于社会成员的幸福，更有利益实现整个社会整
体利益的最大化。建立世界政府也是好事，但世界政府要为全世界人民谋福利，而不是替几个人捞好处。

   在这里，先通过一个例子比较一下计划经济体制和市场经济体制：

   一个班有100个学生上课，现在要给学生们排坐位。应该按照什么原则进行呢？有两种选择：第一，抓阄，抓着什么位置坐什么位置，但是这样一来，矮个
子的、视力不好的学生可能就坐在了后排，他们的听课质量就得不到保证。第二，由老师按身高和视力排位子。不过这样在高个子和视力好的人眼里就未必合
理了——长得高是错误吗？视力好是错误吗？

   抓阄有利于“公平竞争”，有利于发挥个人优势（如果嫌抓阄不过瘾还可以让学生自己解决，自由抢坐，包括武力），这样一来，可以充分的实现“个体利益
的最大化”。但是，因为身高和视力不好而又坐在了后面的学生的听课效果又如何保证呢？按照优胜劣汰的原则看，他们是活该自己倒霉。不过，他们听不好
课，他们就有可能就直接不好好听课了，自暴自弃，在班上交头接耳，坐小动作，影响课堂秩序，反过来也会影响别人听课，这个恶果谁来付？这就是在市场
经济条件下颓废主义盛行的原因。因为真正的公平没有了，某些个体的利益得不到保证，整体利益最大化无人管，人人只管个人利益最大化了。

    在计划经济条件下，人们首先关注的是整体利益最优，所以才会有雷锋，才会有助人为乐，人们才会追求精神享受和精神满足。在市场经济条件下，人们
首先关注的是自己得到了多少物质利益，所以，陪陌生人聊天都要收费，还美其名曰“心理医生”；给人指个路都要收费，因为“信息值钱”。回家陪自己的父母
聊天要不要收费？为教育孩子学好打他两巴掌要不要让孩子给自己打欠条？当我们眼里只有钱的时候，这个世界就变成了兽性的社会——甚至连野兽都不如！野
兽不会为了自己的幸福而去杀死同类，它们会为了争夺食物、配偶、权利和地盘而争斗，但谁都不会去杀死失败者。而人类呢？不知道有多少人死于同类的黑
枪之下，这些人中有许多都是死在自己曾经的朋友手中。

    不要认为欧美社会靠“自由竞争”成功的大企业都是多么的规矩守法，更不要那些白手起家的富翁多么的值得我们学习。那个世界第一CEO所效力的世界第
一号的机器制造公司不是在二战中为了赚钱而为希特勒制造专门用于大批量屠杀犹太人的杀人机器吗？这是不是反人类罪？有几个美国的顶级公司没有参与洗
黑钱？如果不是比尔盖茨的美艳情人斯特凡妮捅出了微软支付“反向赏金”(在微软这是贿赂的代名词)的问题，并在法庭上指证盖茨使用非法手段竞争，我们又
如何知道盖茨并不是年轻人的楷模？当然，为此盖茨花了80亿美元泡妞费。再曝一下盖茨的家底：大家认为盖茨是白手起家的，但是，有谁能说明一下为什么
当年的蓝色巨人要和一个名不见经传的小人物签合同？要是换个人可是连IBM董事长的面都见不上的。而这一点可是盖茨的起家之本。答案很简单，因为盖茨
的母亲是IBM的董事。谁如果想学盖茨的话，还是先找到有本事的老妈好了——如果求伯君的母亲也这么有背景的话，那金山就不是今天的局面了。还有一点，
盖茨在微软的股份最多的时候也不超过22%，剩下的78%在谁手里？谁是微软的真正控制者？大家自己想好了。

    马克思说过：“只要有适当的利润，资本就会非常胆壮起来。只要有10%的利润，它就会到处被人使用；有20%，就会活泼起来；有50%，就会引起积极的冒
险；有100%，就会使人不顾一切法律；有300%，就会使人不怕犯罪，甚至不怕绞首的危险。”

    在市场经济条件下，每一个个体，不论是个人，还是企业，都在为了实现自身利益的最大化而努力。为达到这个目的，都不惜损害他人的利益。所谓的法
律只是为了防止过度损害他人利益的行为，既便如此，违犯法律的现象还是层出不穷。为什么？制度使然。让人们首先考虑如何实现个体最优的制度本身就是
在放纵人们的贪欲，而所有的经济犯罪行为都是由贪欲而生。在计划经济条件下则不然，每一个个体都是在为实现整体利益的最大化而努力。要实现整体利益
最大化，自然不能损害他人的利益。这样的制度本身就是在努力让人们去控制自己的贪欲、让别人生活的更好。在这样的制度下，经济犯罪行为自然要少的多
。这就是计划经济的制度优势。举个例子，一家私营企业可以为了自身利益的最大化而去偷排污水，一家以社会利益最大化为核心的集体企业却绝对不可能这
么做。相比之下，哪种企业对社会更有利？

    本来，当人类解决了生存需求之后，更多的应该追求精神层面的满足。可是，在市场经济条件下，所有人都在贪婪的追求物质满足，结果是越富有就感觉
越不满足。正如那句话所说的：财富就象海水，喝得越多就越渴。越富有却感觉越忙碌，越没有时间享受生活。这又是何苦？人生下来难道就是为了受罪吗？
正如老子所说：知足不辱，知止不殆。物质的追求是没有穷尽的，而且，人们会因为对物质的追求而暴发无尽的冲突（极端形式就是战争）。这与人们追求幸
福的目的是背道而驰的。

    金钱只是人类谋生的手段，不是人类生活的目的。有钱和幸福完全是两个不同的概念。有钱代表的是物质满足，而幸福代表的是精神满足。有句话叫“助
人是快乐之本”，这句话有道理吗？有。助人之后可以获得“自我实现需要”的满足——“自我实现需要”本身就是需要别人来承认的。根据马斯洛的需求层次理论
，“自我实现的需要”是最高层次的需要。马斯洛的这一理论是正确的，并且被广泛应用于管理工作当中。但是，站在个人利益最大化的角度看，站在追求物质
满足的角度看，助人为乐无疑是错误的。获得物质满足不代表幸福，幸福产生于工作的过程之中。当所有的人为了追求自己的物质利益而不惜一切代价的时候
，手段就异化成了目的，真正的目的却达不到了。而且，所有的人都放纵自己的需求的时候，就意味着要透支地球的供给能力，结果就是生态环境的严重恶化
。环境恶化的结果是什么？我们追求来追求去究竟是为了幸福呢还是为了自杀呢？

    《礼记》有言：“傲不可长，欲不可纵，志不可满，乐不可极”。做人（即管理自己）和治国是一样的道理。一个国家要想长治久安，同样必须做到这四点
。

    现在，我们面临着的是内忧外患：环境恶化在把我们一步步的逼上绝地，这是内忧；国际金融势力不择手段欲置我们于死地，这是外患。至于国内的道德
沦落、腐败犯罪、内奸卖国等问题的危害都相对小一点，因为在胡主席和温总理的领导下，这些东西很快就可以改变。从大面上看，国际金融势力这个外患也
好对付；只要我们内部整顿好了，打倒他们并不难。当然，为了全人类的福祉，如果有可能，我倒希望大家能讲和。因为两虎相争，必有一伤。特别是在拥有
核武器和生化武器的今天。一旦火并，不知道要让多少无辜的生命遭受劫难，不知道又是怎样的一个生灵涂炭的局面。而且，出现这么一个群体是市场经济发
展的必然结果，不仅仅是某个人的错误。当然，如果真到了刺刀见红的地步，我绝对相信，胜利是属于我们的，因为我们是正义的。真正的麻烦是我们人类的
自杀行为。要想改变这一切只有靠计划经济体制，那是人类的希望所在。不然，再这样下去我们会断子绝孙的。

这个问题是我们所有人都必须面对和认真思考的：不论是你工人农民，还是私营业主、精英学者，甚至是国际金融势力的核心人物们，只要你是希望自己的子
孙后代能够幸福生活的人，你都必须认真的考虑这个问题——是今天继续放纵自己以致于绝了自己子孙后代明天的生路还是今天克制自己的欲望以便为他们的明
天留下一片生存空间？

    后记：一个月来，没有换成理想的工作，却写完了这篇文章，也算是收之桑榆。当然，在我个人看来，这篇文章应该是我对我们这个国家和民族，甚至这
个世界所作的最大贡献了。我希望的是一个海晏河清的世界，愿众生吉祥！    金鸿95  于2008年4月14日

