# -*- org -*-

# Time-stamp: <2011-08-30 15:45:29 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 【卷后录】



【附录之一·阿富汗】

+ 1.1 关于阿富汗塔利班政权和美国政府之间的来往

1995年，当时的美国石油管道公司尤尼科希望开发土库曼斯坦的道勒塔巴德天然气田的潜力（即Dauletabad，在苏联解体前命名为苏维埃塔巴德，是解体前土库曼最大的气田），将其引向国外，主要是通过阿富汗，到达巴基斯坦在阿拉伯海的港口或者进入印度，主要以供应南亚和东南亚市场为目标。

为了达到这个目的，在阿富汗就必须有一个与美国亲近的政府。1996年塔利班夺取首都喀布尔掌握了阿富汗的大部分地区的控制权。尤尼科即试图游说塔利班领袖人物，将他们带到休斯敦度假，享受奢华生活，并在那里开出每过境1000立方英尺天然气给塔利班15美分过境费的条件。在当时美国助理国务卿拉法尔（Robin Raphael）的大力游说下，塔利班当时同意了这个项目。

所以，在塔利班执政的第一年，美国政府从来没找过它的麻烦。到1997年的时候，甚至有美国外交官声称塔利班将变成第二个沙特，会建立类似沙特国家石油公司（Saudi Aramco）的“塔利班-石油天然气公司”，“一个酋长，一条油管，一个公司，没有国会，更多伊斯兰法律，美国仍然可以和这样的国家共同合作”。

后来塔利班开始采取激进的宗教措施，尤尼科仍然竭力保持和它的合作关系，劝说美国不要忽视塔利班的重要性。因为在美国与伊朗交恶的情况下，阿富汗是唯一的由美国可控制下的将中亚油气引向亚洲的通道。

但当塔利班向尤尼科提出支付每年1亿美元以上的过境费，用于修建道路、供水系统和电力电话系统，以及截流一部分天然气给阿富汗自用的新要价的时候，尤尼科拒绝了这个要求。并开始着手协助美国政府颠覆塔利班政权。911无疑提供了一个极好的机会。[fn:jdwtdgyx10102]

[fn:jdwtdgyx10102] 以上资料来源于巴基斯坦裔著名记者拉什德（Ahmed Rashid）的披露。此人担任过《远东经济评论》（Far East Economic Review）和《每日电讯报》（The Daily Telegraph）的记者和《华尔街日报》及《民族》（The Nation）杂志的撰稿人。此人在2000年出版了一本畅销书《塔利班-中亚的伊斯兰民兵、石油和原教旨主义》。


+ 1.2 尤尼科国际业务副总裁1998年2月12日在美国众议院听证会上的证词

主持人：

今天我们将听证有关美国在中亚各国的利益问题。一百多年前，中亚是众多强国，包括沙皇俄国、大英帝国、拿破仑的法国，以及当地的波斯和奥斯曼土耳其帝国角逐的舞台。

……

（关于中亚地理、政治和周边土耳其、伊朗的介绍，《大国游戏》系列将在第二卷作生动描绘。——编者注。）

……

下面我们欢迎尤尼科公司国际事务部副总裁约翰·马雷斯卡先生的证词。好的，您可以开始了。

#+begin_example
马雷斯卡：

　　诸位好，我今天将谈论三个话题。首先是关于中亚石油和天然气资源开发中将油气导出到市场的多条管道建设的必要性。第二点是美国支持国际和地区努力以在该地区实现和平，结束冲突的必要性——比如说在阿富汗。第三点，关于如何为本地经济改革，改变投资环境所需要美国提供的全面的帮助。为了打到上述目标，我们认为希望废除“支持自由法案”（the Freedom Support Act）。

    主席先生，里海周围地区储藏着及其丰富的未开发的油气资源。大到什么程度呢？目前（截至1997年底——编者注）已经探明的天然气储量已经超过236万亿立方英尺（合6.68万亿立方米。到2007年底，里海西岸的土库曼斯坦的预计储量为100万亿立方米，南岸的伊朗为27万亿立方米，俄罗斯全国为48万亿立方米——编者注）。同时本地的石油储量已经超过了600亿桶，有些专家的估计可能储量超过2000亿桶（截至2007年，沙特探明的石油储量还有2640亿桶）。但1995年，该地区每天只生产了87万桶石油，到2010年，在此地投资的西方国家计划将把生产量提高到每天450万桶，也就是15年内就要增长500%。如果达到这个生产规模，那么本地将生产全球石油产量的5%。

    但是，如何将本地的丰富能源资源输送到使用销售的市场，是一大亟待解决的难题。从地理上和政治上来说，中亚是与世隔绝的。他们的自然资源没有出海口。在中亚和高加索地区的每个国家都面临着困难的政治局面。有些还在打仗或者有内部冲突，有的内政不稳，法律甚至司法机关都整天变来变去。而一个最重要的技术难题在于：目前该地已有的管道系统不能胜任输送本地未来石油的任务。

    上述现象的原因在于本地目前的管道是在苏联时代建设的，在莫斯科的主导下，现有管道都是向北、西北输送并入俄罗斯的管道系统。现有管道与南边和东边都没有延展连接。但以现在俄罗斯的情况（当时处于混乱而衰落的叶利钦时代——编者注），它无法吸收那么多的西方石油公司投资生产的大批增产能源——我预计十年之内俄罗斯都不会是有巨大能源需求的新兴市场，而且它又缺乏将这批增产能源转运到其他市场去的能力。

　　目前，有两批目的在于提供该地未来新增生产的能源向外输送能力的工程项目正在计划中。第一条是是里海石油管道财团（包括雪佛龙等美欧石油公司参与出资）打造的一条管道，从里海北部延伸到俄罗斯在黑海的新罗斯托克港。然后再这里用油船的方式将能源经过土耳其的博斯普鲁斯海峡进入地中海，送往欧洲和世界其他地方。
   
    另一个项目则是由国际阿塞拜疆运营公司主导——该公司是一个由11家欧美石油公司参与组建的合资财团企业，其中包括四家美国本土公司：尤尼科（后并入美国雪佛龙公司）、印地安纳标准石油（后并入英国石油公司）、埃克森（今为埃克森-美孚公司）、宾州石油（后并入英荷壳牌石油石油）。这个项目考虑两条可能的管道路径：一条从阿塞拜疆出发，沿里海西岸往北走，进入俄罗斯境内，到达黑海港口新罗西斯克，另一条则走格鲁吉亚的道路，到达格鲁吉亚在黑海沿岸的一个港口从那里装船走，另外这个格鲁吉亚的管道计划还可再向西、向南延伸经过土耳其到达该国南部地中海海岸的港口杰伊汉。

    （尤尼科负责人在这里谈到的几条管道，就是中亚能源激烈博弈的几条竞争性管道。本系列图书将在第二卷中作生动的图文展示。其中欧美最后赌注押在格鲁吉亚路线的延伸版本——即到达杰伊汉的石油管道。这条管道，因为格鲁吉亚政局变化后俄格两国交恶以及2008年的俄格战争而被炸，具体背后原因令人浮想联翩。——编者注。）

    但即使这两条管道都建设完毕，仍然无法完全胜任未来该地区石油产量向外运输的任务，也没有足够的转运能力。所以还需要建设其他的出口管道。

    我们尤尼科认为，决定管道走哪条路线的根本因素，是未来能源市场的地点——未来哪个地方的能源需求增长最有潜力，哪个地方就最可能需要中亚的未来能源，我们就应当把管道向哪里修。根据我们的计算，西欧、中东欧和独联体地区未来十多年内（1995-2010）的能源需求都仅有每年0.5%-1.2%的增长。

    亚洲与这些地区完全不同，它的能源消费将迅速增长，在最近的危机（指1997年东南亚金融危机）之前，尤尼科预计该地石油需求将在2010年翻番。虽然最近几年的增长预测可能因为短期的危机而有所降低，但长期的增长预期我们仍然维持不变。

    我要提醒诸位，满足亚洲地区的石油需求增长符合每个人的利益。如果此地的石油需求没有得到中亚石油的补充满足，那么他们就会到国际市场上四处购买，就会给全世界的能源市场带来压力，从而在各地造成能源价格上涨。

    所以，现在问题的关键就在于如何把中亚能源输送给他们周围的亚洲国家。现在设想的有两条可能的路线，每条路线里面还有各种互有差别的版本。第一条大的方向是向东输送，穿过中国。但这种办法的问题在于它意味着要建设一条3000多公里长的管道——此时还只能送到中国的中部，而如果从中国的中部送到它的沿海各地，还需要共2000公里的支线。所以，如果这样走，那么问题就在于这条漫长管道所产生的过路费会有多少，是不是严重影响我们这些石油生产公司的剩余所得？

    所谓剩余所得，是指生产者在扣除所有支付给管道过境地的过路费及其他所有成本后的能源收入的剩余。

    第二个选项，是选择修建一条从中亚向南，到达印度洋的管道。一条很显而易见的路线是穿过伊朗，但是这条路线因为美国对伊朗的制裁而无法实现。所以这样唯一的选择就是经过阿富汗——当然此地也有不少挑战。该国已经经历了20年残酷的内战，而且现在还在厮杀。所以从一开始，我们就清楚表态：在该国确立一个被国际广泛承认的政府，让该政府获得其他政府、国际金融贷款机构和本公司的信任之前，我们是不会开工建设穿越阿富汗的管道的。

    主席先生，如你所知道的，我们已经和在奥马哈（股神巴菲特公司所在地）的内布拉斯加大学建立非常紧密的合作关系，进行一个培训阿富汗未来人才的培养计划，这些人才将在未来送往阿富汗各地，包括北方和南方（这里指当时仍然在交战的阿富汗北方联盟军阀和主要占领南方60%以上地区的塔利班武装）。

　　尤尼科预计这一阿富汗管道将成为地区系统的一部分。其石油管道将通过现有管道系统从土库曼斯坦、乌兹别克斯坦、哈萨克斯坦和俄罗斯汇集石油。这个1040英里长的石油管道将向南通过阿富汗到达巴基斯坦沿海的一个出口转运港。这个直径42英寸的管道将具有每天输送1000万桶石油的能力。该管道建设工程的成本大约和穿过阿拉斯加的石油管道类似，约25亿美元。

    考虑到中亚地区极其丰富的天然气资源，我们的天然气方面的计划是将此地天然气引入临近市场。这个想法在商业上是可行的，但面临着地缘政治的挑战。尤尼科和土耳其的石油公司Koc集团对于将低成本的天然气引入土耳其很感兴趣。所以和他们所提议的欧亚天然气管道将把土库曼斯坦的天然气直接穿过里海运送到阿塞拜疆，经过格鲁吉亚到达土耳其。当然由于是海底天然气管道，所以里海领海划界问题还需要解决。

    去年十月，中亚天然气管道联合财团，建成中气（CentGas）——尤尼科在其中占有一定的股份，已经组建以建设一条连接土库曼斯坦的资源丰富的道勒塔巴德天然气田与巴基斯坦和印度之间的天然气管道。这条计划长790英里的管道将为土库曼的天然气打开这一市场。建成后天然气能源奖惩土库曼斯坦穿过阿富汗，到达巴基斯坦的木尔坦，然后再延生到新德里，与现有的南亚管道系统相联。和上面所提到的中亚石油管道计划类似，中气也无法在出现一个国际承认的阿富汗政府之前进行工程建设。

    中亚和里海地区有着如此丰富的石油和天然气，为本地人民生活水平的提高和向欧洲及亚洲提供能源满足需求增长提供了可能。这一资源对于美国商业利益和美国外交政策的影响也是非常巨大的。如果不能够解决本地的冲突，实现和平，那么跨境的石油和天然气管道都不可能实现。我们敦促政府和国会对联合国在阿富汗的和平行动（当时只限于少量的人道援助——编者注。）提供强有力的实际支持。美国应当利用其影响力为该地的冲突寻找解决方案。

    美国帮助本地各国经济发展有利于的制度也是对商业的繁荣成功至关重要的。我们因此希望能够在该地普遍实施强有力的技术支持。具体的说来，我们希望废除支持自由法案中的第907条款。该条款限制了美国政府向阿塞拜疆政府提供各类帮助，限制了美国在该地区施展影响。

    为中亚地区的能源寻找低成本的出口路径是艰巨的任务，但并不是不可能的。尤尼科和其他公司已经准备好承担这一工作，将中亚地区再次获得它过去有过的转折性发展机会。谢谢，主席先生，我的讲话完了。
#+end_example


【附录之二·中国新疆】

2008年年中关于关塔那摩中国籍俘虏的美国国会听证会记录（摘要）

本书作者在2008年5月预言就关塔那摩的中国籍犯人在美国针对新疆分裂分子的第二批宣传战中可能被操作允许赋予西方国家居留权乃至护照，2008年6月10日，在美国国会上演了一场大戏。

（2008年）6月10日，美国国会外交事务委员会就人权问题作了个听证会，其中有一段对话是关于关塔纳摩监狱里同美军在阿富汗作战而被俘的维吾尔族恐怖分子的。出来为布什政府作证的是曾为美国国家安全委员会法律顾问，现任职于美国国务院的贝林格。发问的是加州共和党议员罗拉巴赫和宾西法利亚州的共和党议员皮茨，听证会主席是马萨诸塞州民主党议员德拉亨特。听证记录如下：

#+begin_example
贝林格：罗拉巴赫先生，你谈到了维吾尔的案例。但是在该案例上，因为得不到外交上的保障（指其他西方国家承诺接收维吾尔族恐怖分子），我们没有一个好的替代方案。而假如替代的方案是硬让这些人呆在美国，我认为你的选区的选民就会责问你为什么我们让危险人物留在我们的国家。

罗拉巴赫：先生！这是维吾尔问题。不同于你的看法，我和主席先生都有这样的一个结论——他们不是美国的威胁。事实上当初对他们的监禁是一个错误的决定。既然我们做出了错误的决定，就应该承认这个历史错误——我们要考虑共产主义中国的人权纪录，不应该把他们送回那里。我看，替代的解决办法是承认我们的历史错误，允许他们呆在这里。听证会主席和我事实上已经写了一封信送交国务院来表达这个建议。国会议员们也提到了最近披露出来的关于关塔纳摩基地帮助中国人审问维吾尔囚犯而搞各类准备工作的事情。

皮茨：我在这里对维吾尔事件提供一点补充，法务部检察官报告有一个很有意思的脚注，也就是第134号脚注，里面提到，一个联邦调查局特工告诉检察官，中国政府官员去了关塔纳摩并审问了美军拘留的维吾尔人。他报告说，在中国政府的审问官的要求下，这些维吾尔囚犯，先是被强迫不让睡觉，然后再在低温房间里过一个夜晚和白天，然后再交由中国官员审讯——以方便他们问出有价值的信息。
诸位注意！这里的关键，是美国政府官员邀请中国政府的人员来一个在美国也是高度限制的军事基地，来审问这些维吾尔人。而正是这个中国政府恶待维吾尔人而导致他们逃出中国。具有讽刺意味的是，这个军事基地连咱们美国国会议员都不能进去同囚犯对话。
而且根据该指控，美国军队人员被指使去软化这些囚犯，或者可以说，折磨他们，使他们可以较好的被中国官员审问。
到底是谁下命令允许在美国军事基地里由中国政府去审问被他们迫害的少数民族？到底是谁做的决定？！

贝林格：皮茨先生，我可以认定那是国防部，你必须去问他们。就听证会主席提出来的问题，我可以说，我们确实关注维吾尔人的处境。
我们很早就得出结论：如果我们把他们交还给中国，他们肯定会得到不公正待遇。几年前，我们曾经得出过结论，他们的扣留并不是被错误的、无辜的——他们之所以被抓，因为他们是在阿富汗（基地组织）的训练营里和塔利班混在一起。但是我们很快又得出结论，他们不会试图和我们开战，他们只会向中国人开战。
所以我们很早就做出决定，他们如果被遣送，可以遣送到任何地方但就是不能送回中国。但是，关于关塔纳摩的事情，先生，你必须去问国防部，你问我没用。
#+end_example

看来，美国可能会试图给予这些维吾尔东突恐怖分子以美国身份，来支持对中国新疆的颠覆活动。不知中国是不是应该考虑与美国在反恐战争的合作态度？


【附录之三·巴基斯坦】

时任巴基斯坦总统的穆沙拉夫2007年关于红色清真寺事件后实行国家紧急状态的全国电视讲话（摘录）

（本文被普遍解读为巴基斯坦公开表态和中国的亲密关系和与欧美的影响力日渐式微）
（以下为乌尔都语）

#+begin_example
    我亲爱的兄弟姐妹，愿真主保佑你们！

    今天我在这里向你们发表全国讲话，是因为我们的祖国巴基斯坦处于十字路口，之所以走到这一步，是因为我们的内部混乱——哦，所有你想不到的事情都发生了！这都是因为内部的原因。在很多国家的历史上都有领导人被迫做出痛苦决定的时刻，而现在就是要为巴基斯坦做出痛苦但万分重要的决定的时刻——因为我很担心，如果我们不及时做出反应，那么真主就要惩罚，巴基斯坦的国家团结就要处于危险！

    在我说明这项决定之前，我要做一个承诺，那就是我保证所将要做和已经做得所有决定，都是从巴基斯坦的利益出发，这是我的原则——为了巴基斯坦的利益，而不是任何个人利益或个人考虑，巴基斯坦永远被放在第一位。我愿全国人民，都能够感同身受这一点。

    我的兄弟姐妹们！很坦白的说，在过去的几个月里，巴基斯坦的国内环境发生了剧烈变化。其中有一件事情我要在讲话里自始自终强调的，那就是恐怖主义和宗教极端势力已经到了无比嚣张的地步。就在最近，自杀性袭击在巴基斯坦遍地开花——在卡拉奇爆炸，在拉瓦尔品第爆炸，在萨果达爆炸103，在全国到处爆炸。局势在加剧，在燃烧！极端分子光天化日之下招摇过市，简直可以说他们根本不把我国的执法部门放在眼里，真是自以为神灵附体。这一局面开始从与阿富汗临近的西北边境地区起发端倪，随即进入其他省份——兄弟姐妹们你们都明白在西北边境省的斯瓦特区和在南部各区发生了什么事情。我们面临挑战。但是，最大的悲剧是——在我们的首都，巴基斯坦的心脏——伊斯兰堡，居然在这里，极端主义也四处蔓延，人们无所适从。这些极端分子正在取代政府，他们要建立一个国中之国！而最危险的莫过于他们想把他们那套对宗教的死板和极端的理解强行灌给那些热爱和平和公正的巴基斯坦人民。这些行为在我看来，是对巴基斯坦国家团结的公然挑衅。

    让我们更进一步的追问，这个政府是处于一种什么状态，搞到如此岌岌可危？在我看来，就是几乎已经瘫痪！所有的政府里的高级官员都被法庭一一传唤，最高法庭的传唤！鱼贯而入，鱼贯而出，纷纷领刑。在法庭上他们丢尽了脸。因此，这些官老爷们也把该干的工作放在一边，撒手不管了。目前最高法院在审理的此类案件已经至少有100件了，而我还收到报告说还有上千件在后面排队！所有的这些案件都是关于政府日常执行部门的。我国政府的管理功能目前已经瘫痪。

    让我们来看看执法部门（指检察院之类——编者注）。在我看来，这些人简直就不要脸——特别在首都伊斯兰堡的这些人。他们已经没有希望，自暴自弃，为什么？因为他们里的同僚们大批大批的在走向最高法庭被告席的队伍里。有十个官员——包括两个总检察长，被撤职或者指控。所以我们的执法部门道德堕落，懦弱无能，无法履行本职工作，他们除了游手好闲看热闹以外不会干任何事情。

    现在再看看我们的民主体系——民主在我国的实际运行功效好了。在这里困难重重。1999年，当我带领我的政府开始执政的时候，我作了一套三步走的计划——这个计划是为了方便我国最后过渡到民主而设计的。之所以这样做，是因为到1999年的时候，我们的国家已经是一个失败，无法运作下去的国家：民主体系破败不堪，没有一任政府能够干完正常任期；只剩下一个民主的口号空壳。正因为这个背景，所以我们的计划中的第一阶段，即1999年到2002年，是按照我的计划来执行的，即由我（作为政府总理）完全领导政府。接下来的第二阶段是2002年到2007年，通过民主选举的体系来选拔政府官员、国民议会议员和各省地方议会议员，以及地方政府，走的是完全充分的民主选举政府同时我来监督督促的路子。对，我对其进行监督，但国家及其按照自己的路数在运行。在此期间我是总统兼三军总司令。这个第二阶段总体运行还可以。的确，存在很多问题，但至少我们第一次让国会会员和政府官员能基本干满了他们的任期。

    现在，我们已经处于过渡时期的最后步骤，即第三阶段。我曾经希望在2007年11月15日，国会完成他们的完整任期后，我们可以按照原计划进行总统大选。这样选举出来的政府——无论谁获胜——都可以率众进入一个政治和解和完全民主的新时代。我曾经如此希望，我们能够第一次按照原定的精心构思完成这次过渡。

但是，非常非常不幸的，我必须说最近以来，很显然某些势力正在插手我们的民主计划，想妨碍并最后让他中断。就在这最后阶段的最后几个月的关头，第三阶段的计划被粗暴破坏了。我认为这是一种为了个人和政治团体私利而置巴基斯坦国家利益于不顾的有意行径。

……

现在，我们又看到了红色清真寺，这里面的极端分子试图当起执法者来了——就在巴基斯坦的心脏——我们的首都，这让我国在世界各国面前蒙羞。只有我知道这件事情给我们带来了多么大的耻辱。我们，一个拥有强力的国家（指核武器——编者注），居然无法控制我们自己的首都，让某些人在这里建了一个国中之国。我国的形象受到了极大的损害，我们的根基发生了动摇。这些极端分子——他们什么做不出来？！他们把中国人当作人质，折磨他们。因此，我个人感到非常的尴尬。我必须向中国领导人道歉：我为我们伟大的朋友在我国遭遇的这样的不幸感到羞辱。此后，这些极端分子居然来点燃部长大楼，点燃他们的汽车！我们在这种情形下应当采取什么行动？！几个月来，我们一直被公开指责，人们认为我们无所作为。其实我之所以不想做出激烈反应，是因为我尽可能要遵从治病救人的原则。直到最后没有办法，我们只能采取行动，我命令所有武装力量迅速解决这一令我国尴尬的事件。我们中的许多士兵牺牲了，我为他们的升天祈祷。愿安拉保佑他们上天堂，他们为这个国家而不是他们自己的利益而牺牲了自己的生命。

……

在审视完当前局势后，我与军队、政府、政治和民间领袖以及海外巴基斯坦侨民磋商，在与他们共同会晤之后，我决定作出选择。我命令回到过渡时期的第三阶段，重新走完这一步。通往民主道路上的障碍必须被移出。我要以我无论当初还是现在的坚定意愿，最终真正走完这第三步。真主保佑我达到这一目标！

为了做到这一点，我在此宣布全国进入紧急状态。我已经签发了临时宪法令并在刚刚已经由全国电视系统播出，兄弟姐妹们你们应该都已经看到了。我必须重申目前政府内部没有变动。总理、省长和主要部长仍然各就其位。所有议会会议造常进行。这是我的决定，我认为这是最容易将巴基斯坦拉回正规，保护经济发展，完成向民主的最后过渡的途径。

借此之机，我要用英语说几句：

（以下用英语）

我刚刚用乌尔都语向巴基斯坦人民作了讲话。现在我们要向你们（这些外国朋友）讲话，特别是我们在美国、欧盟和英联邦的朋友。我希望你们能够理解巴基斯坦国内和周边形势的严峻性。巴基斯坦正在动荡的边缘——如果不及时行动的话，一切将不可挽回。让我感到非常痛心的是，我亲眼见着巴基斯坦过去7年一点一点取得的成就，但现在却开始走向下坡路。

我个人就我的所见和所思，认为，在这种局面下如果仍然无动于衷，将意味着巴基斯坦走向自我毁灭。我不允许我的祖国走向毁灭。

所以，我必须采取这一行动以保存过去8年取得的民主过渡的成绩。我要重复一遍——刚才我已经用乌尔都语说过了——我进行了三步曲的过渡安排，第一阶段从1999年到2002年，由我亲自领导；第二阶段从2002年延续到2007年，5年的民主制度，所有的议会、地方政府统统是按照民主选举制来组织的——与此同时我作为三军总司令和总统监督辅佐；现在我启动第三阶段，主要是为了在过渡阶段的最后几个月内完成最后过渡，实现完全的民主，回到民选领导人的状态——如果我有幸当选，那么我将只是一个民选总统。今天，正是这个第三阶段被干扰了，而我希望用我的全力去完成这一步骤。如果我们无所作为，我不认为我们能走完这一步，我无法预言会有什么样的大混乱在等待我们。

所以，我希望你们所有人（欧美等国——编者注）能够理解我们。对于反对这一行动的那些批评者、理想主义者，我要说的是请不要把你经过几百年才得以运转成熟的那种程度的民主制度强塞给我们。我们学习过，我们干的很好。也不要强行要求你们的人权、民权、公民自由——所有这些东西你们自己都学了几百年，我们也在参考，也做的很好。

我将特意为美国的听众朗读一份亚伯拉罕·林肯总统的信件摘录。作为一个理想主义者，亚伯拉罕·林肯在联邦国家面临分裂的时候，在最高危机大祸临头的时候，他决定打破当时的法律，决定违反当时的宪法，他为自己的理想获取了必要的绝对权威，他没有为绝对的教条的个人自由所束缚，他的判断是必要的，为了解释他当时不可思议的大规模“违宪”，他在1864年的信件中说道：

“我必须尽全力遵守我对宪法的宣誓，用任何手段保卫宪法——我们的政府、我们的国家的根本大法，但是，是否有可能在国家瓦解的时候宪法仍然能够保存呢？以常识可知，对于一个人来说，生命和肢体都是他要保护的，但是人们在危机情况下常常为了保存生命而舍弃部分肢体，但从来没有能牺牲生命来保留肢体的说法——这种保存毫无意义。我认为这样看来，某些并不符合宪法的做法，能够成为法律，能成为为了捍卫宪法而必须采用的手段——当只有这种做法才能捍卫国家的时候。不管这种看法被认为对还是错，我坚信这一立场，并在此声明”

如林肯所述，我们也在民主的学习过程中，我们将经历艰难的过程阶段。国家至上，对于我，对于每个巴基斯坦人，巴基斯坦至上。无论别人怎么看，我正是坚持这一看法的，所以我所做的，都是为了巴基斯坦，无论别人怎么想，我以至诚之心发誓，我所做的，是为了巴基斯坦之利益。我将以我的全心全意全力去实现它。

（换回乌尔都语）

我的兄弟姐妹们！我希望我们大家都认识到了局势的严峻性。我认为别无他路。如果需要牺牲我的生命来挽救巴基斯坦，我别无他议。我不会向环境屈服，我会与恶局战斗，我从不投降。我会战斗，不断战斗，不是为我自己，而是为民族，为国家，为了我国的人民，为了大家的幸福。如果有你们的支持，毫无疑问，真主保佑，巴基斯坦将回归正轨。毫无疑问，我们的国家需要进步，需要向前进。普通人关心的是物价，关心的是失业和贫困，人民已经厌倦了那种空谈民主而无所作为给他们带来的生活的动荡，人民已经厌倦了那些恐怖分子以宗教的名义滥杀无辜，人民已经厌倦这些了。

我要告诉兄弟姐妹们，让我们团结起来，共同战斗，把巴基斯坦推向前进。愿真主与你常在，与巴基斯坦常在。巴基斯坦 哈米沙 磐答巴答。
#+end_example


【附录之四·沙特阿拉伯】

赖斯2005年6月中东之行的两个演讲摘录，时逢布什政府开始新中东政策，美沙关系陷入低点

+ 4.1 赖斯在开罗大学的演讲（摘录）

#+begin_example
    非常感谢，哈拉·穆斯塔法博士，谢谢你的介绍和关于中东民主的睿智思考。我非常荣幸能够来到这古老的城市开罗。

    美国珍视与埃及的战略关系和不断增强的经济联系。且自里根总统以来，美国历任总统都能够有幸从与穆巴拉克总统的交往中获得智慧和见解，我本人也非常荣幸在今天早些时候和他会面。

    美国和埃及的人民都希望能够互相访问，互相学习。而这里——开罗美国大学（the American University of Cairo104），就是我们相互合作的结晶。美国大学——这个学习知识的殿堂经历了各种坎坷，生生不息而发扬光大——无论是关系有所颠簸的过去，还是关系密切的今天。我非常荣幸能够在这个学习知识的殿堂里发表演讲。

    ……

    在这个伟大抉择的时刻，我来到开罗，不是要谈论过去，而是要展望未来——一个埃及人能领导、控制的未来。女士们先生们，在我们当今世界，有一批越来越多的人，无论男女，在追求他们自由的保障。当这些人们获得选择的权力的时候，他们将创造一个能够保护他们自然权利的民主政府！

    我们需要展望未来，一个所有政府都尊重其公民意愿的未来——因为民主的优点是普世的。60年来，我的国家——美国，以牺牲民主，不要求本地民主化为代价，在中东地区追求局势的稳定——但我们发现，最后既没有收获稳定，也自然没有收获民主。现在，我们要改变方向，我们将支持所有人对于民主的追求！

    ……

    尽管如此（美国历史上对黑奴的压迫），铭刻在我们美利坚合众国宪法的（民主的）原则，使得心怀坚定信仰的人民持续努力，让美国日复一日更加接近于民主的楷模。在这里——中东，与我们相通的对于民主变革的热切渴望和改革进程正在全面展开。数百万的人民在要求自由，要求他们的国家走向民主。

    对于这些勇敢的人们，无论男女，我今天相告：所有的自由国家都将与你们同在，在你追求自由的过程中与你同在！在到达埃及之前我刚刚访问了约旦，我会见了约旦国王和王后——这两位领导人拥抱改革已经很多年。约旦的教育改革就是整个地区的榜样。约旦政府的政治改革正在分散权力，给约旦人民在未来得到更大的幸福。

    在伊拉克，数百万公民拒绝向恐怖投，选择了自由和民主的梦想。当巴格达在一千二百年前建造的时候，它是按照“环形城市”的原则来设计的——在这个环形城市里，所有公民都与中心的最高法庭有同等的距离。今天，经过数十年的谋杀、暴政和不公，伊拉克人民正在再次接近他们祖先的环形城市的民主梦想！

    尽管要冒一些恶势力的可能袭击，普通的伊拉克人仍然显示了巨大的个人勇气，取得了令人瞩目的成就。这每一步——从重新获得他们的国家主权，到举行选举，再到制定新的宪法，伊拉克人民以成就在超越世界对他们的期望！

    巴勒斯坦人民也发出了自己的呐喊。他们自由选举产生的政府正在抓住多年不遇的良机去实现建国的历史梦想。充满勇气的领袖——无论是巴勒斯坦还是以色列方面，都在竭尽全力寻求和平。他们正在构建一个共同的互信。

    巴勒斯坦自治政府将很快接管加沙地带——这是实现两个民主国家毗邻而居的梦想的第一步。随着巴勒斯坦人与恐怖主义作战，以色列人在履行巴勒斯坦人民帮助建立一个生机勃勃的国家的义务和责任，全世界——特别是埃及和美国，将给予全力的支持。

    在黎巴嫩，民主的支持者要求在外交上获得国家独立。在总理哈里里遇刺后，数以千计的黎巴嫩公民呼唤变革。而当记者卡塞尔之死向每个人暴露恐怖主义的残暴的时候，黎巴嫩人民仍然没有任何退缩。

    他们为牺牲的烈士痛苦，但他们用文字战斗，公开团结在一起。并不仅仅只是黎巴嫩人民要求从叙利亚这个警察国家的压制下获得自由，叙利亚人民自己也有同样的要求。

    179个叙利亚学者和人权活动分子呼吁他们的政府“让大马士革之春绽放，让它的花朵盛开”。叙利亚领导人应对此有所回应——他应当学习如何相信他的人民。叙利亚的例子特别突出，因为当他的邻居都在拥抱民主和政治变革的时候，叙利亚继续在窝藏或直接支持暴力组织——在黎巴嫩，在以色列，在伊拉克，在巴勒斯坦地区，是叙利亚作出战略性改变以加入地区的变革洪流的时候了！

    在伊朗，人们已经对这个压制性的政权失去了耐心，这个政权否定他们的自由和权利。空有选举的外表105并不能掩盖这个神权国家有组织的犯罪和残暴。伊朗人民，无论男女，都有自由的天性，他们热爱自由，他们理应自由。让那些未经选举的掌权者交出他们的权力，给伊朗骄傲的人民的时候到了！

    在沙特阿拉伯，勇敢的公民正在要求得到一个负责任的政府。有一些迹象表明在最近的地方选举上有一定的走向公开透明的进步。但是很多人仍然为行使他们的基本权利付出了过高的代价。有三位人士，最近因为和平情愿而被关押，这在任何国家都不该被定性为犯罪。

    现在，在这里，在开罗，穆巴拉克总统决定修改国家宪法并组织多党选举，这令我感到振奋。穆巴拉克总统已经打开了变革之门。现在，埃及政府必须用心来服务于它自己的人民了。我们都非常关心埃及的改革，因为就目前看来，那些民主的和平拥护者，都尚未摆脱暴力的威胁。用法治来代替紧急状态令的那天必须到来，用独立司法来代替专断法官的那一天必定要来到！

    埃及政府必须切实履行它对人民做出的承诺，必须履行它对全世界做出的承诺——给他的人民自由选举的权利！埃及的选举，包括议会选举，必须满足符合自由选举标准的客观标准。

    ……

    女士们先生们，放眼今日中东，数百万公民在呼喊，在呼喊他们对自由和民主的渴望。这些人，男男女女，正在将一年前尚认为不可能的边界不断向外拓展，没有什么不可能！

    ……

    今天，自由在被非民主政府威胁。有些人认为这是历史的常态。但有更多人比这些人认识的更清楚，更明白更好。这些已经失去耐心的勇士，遍布中东，他们在巴格达和贝鲁特，在利雅得和拉马拉，在安曼，在德黑兰，还有在这里，开罗，他们到处都是！

    他们自共同书写着我们这个时代的公正标准——一个曾经被认为不可能的标准，现在已经是不可避免的标准。埃及人民将作为先锋走在中东民主伟大征程的前列，正如过去你们走在中东文明的前列一样。

    一个充满希望的未来就展现在每个埃及公民的眼前，每个中东人民的眼前。这是你们的选择。但你们不是孤独的。所有自由国家都是你们的盟友！所以，让我们一起，为我们的国家，为我们的孩子，为我们的共同未来，选择自由和民主吧！

    谢谢！
#+end_example


+ 4.2 美国国务卿赖斯与沙特外交部长萨乌德·阿·费萨尔的联合记者见面会（摘录）

#+begin_example
沙特外交部长萨乌德：
    女士们，先生们，我们欢迎美国国务卿赖斯女士访问我沙特阿拉伯王国。很高兴能与国务卿一起在这里见面——特别是她在这样一个不那么令人舒服的炎热夏季来到我国，可见她此行不虚。
……
    赖斯女士与尊贵的沙特国王、以及王储阿卜杜拉（时尚未登基——编者注）进行了深入而互有收获的讨论，主要集中在以下几个议题：
1 美沙双边关系及如何深化促进之。
2 以色列和巴勒斯坦之间的和平进程，如何通过公正和广泛的解决办法打到目的。
3 在前总理哈里里不幸遇刺后的黎巴嫩局势及叙利亚从黎巴嫩撤军的问题
4 伊拉克局势，如何给此地带来和平和稳定，统一和领土完整。
……
（介绍了部分关于美国帮助沙特加入WTO，美沙公民互访对方国家的协议等等）
……

赖斯：
    非常感谢外长先生。非常高兴能和你站在一起，当我还是国家安全顾问的时候我就和您共事多年。很高兴本次访问是我首次以国务卿身份访问贵国。
众所周知，美国与沙特阿拉伯之间有着传统和深厚的战略关系。布什总统与阿卜杜拉王储之间在克劳福德的峰会上进一步借机深化了彼此间的关系。正如外长所谈，我们已经决定成立一个委员会，一个战略对话委员会，以便更方便让我们在很多面对的议题上进行合作。
首先，我们将在我们关于地区安全的讨论上加大力度。刚才，我与外长谈及了以巴和平进程问题。……
……
我们也讨论了伊拉克问题，……沙特政府将敦促伊拉克的逊尼派阿拉伯人参与联合政府进程。当然，我将与外长在晚些时候在布鲁塞尔召开的关于支持伊拉克人民营造民主未来的国际会议上再讨论这一议题。
其次，我们讨论了经济议题。沙特阿拉伯已经同意，增加原油产量以缓解世界石油供应。我们知道石油供应是一个长期问题，我们感谢沙特阿拉伯为此结构性的难题愿意贡献自己的一点力量。
同时沙特阿拉伯已经在加入世界贸易组织的谈判上取得了极大进展。加入世贸组织将帮助沙特经济，释放它的人民的创造性活力。
第三，我们继续讨论了有关打击极端主义势力的策略问题。自911时间的几年来，沙特已经成为我们与恐怖主义的战争的终要伙伴，当然这个战斗并不一帆风顺。有一些沙特的警察和士兵为此牺牲了生命，我们对此表示感谢。
第四，我们将强化在双边性议题上的讨论。我和外长讨论了美沙公民、组织之间交流的议题，包括如何为更多沙特商人和学生到美国做生意或读书，以及更多美国人来沙特工作提供便利。我很高兴得看到与我会晤的很多沙特部长都是美国大学毕业的，包括其中一位和我是校友——都在丹佛大学学习过。我认为这说明保持双边政府和其他人员的流动是很重要的。
我们的确谈到了改革的话题。我在此要感谢外长和王储殿下在讨论沙特改革这一话题上保持的开放心态。美国，当然是以一个朋友的身份来敦促这一事情的，沙特的改革也是布什总统一如既往的心愿。布什总统已经表明态度：他坚信民主自由价值是普世标准，当然我们也知道不可能将我们的自己的制度加在别人头上，所以我们会采取帮助他们，让他们去自由选择的办法来推进进程。正如我今天早些时候在开罗大学提到的，成功地改革必须发自本地，而且它必须有利于本国。当然，我们相信更多的自由是治疗对立仇恨意识的最佳长期药方。
我和外长，以朋友的关系，谈论了贵王国的这一改革进程。沙特的全国对话和地方选举是贵王国的重要事件。我也注意到随着事态的发展，我们有必要提议这一民主必须是男女共同参加的——而不是仅限于男性，我们会进一步希望看到妇女政治权利的进步。
美沙双边关系仍然良好，其原因，在于我们都能注重长远的未来，我们都探寻温和的、和平的、共同参与的取得目的的途径。
谢谢。

沙特外交部长：
谢谢女士。……下面开始问答时间
#+end_example  

提问者Q1：

……我们希望了解美国政府对沙特在以下方面取得的成就的评价：包括打击恐怖主义、人权和内政改革。谢谢

赖斯：

非常感谢。我们在反恐、打击恐怖主义议题上合作很好。我们都同意基地组织和类似的恐怖组织都必须被消灭。……

……

我们认为沙特政府在改革上正在取得进展。我们注意到地方政府一级展开了选举，我们还留意到有正在筹划一个全国性的对话。很显然，每个国家都有他们自己的时间安排，但我们鼓励这种改革能越快越好。而且正如我所说的，我认为任何改革都会展示这样一个事实，那就是存在着人类心想往之的普世价值和自由。我给外长说过，我认为这条真理涵盖了中东地区的人民，包括沙特阿拉伯人民，他们在这方面都没有什么不同。

由于美沙之间有如此深厚的关系，在这个深厚关系上我和部长可以无话不谈，所以我们刚才的交换话题覆盖奇广。所以才使得记者招待会在这个半夜来举行。

沙特外交部长：

我补充一点，我实在是很难理解为什么谈论“改革是什么性质的改革啦”、“我国改革要采用多块得速度啦”有什么值得吵闹的。……我看不出来和美国国务院或国务卿谈论这一话题有什么值得奇怪值得书写的地方。所以这种议论吵闹没有什么实际意义。关于政治改革进展的评估在任何国家都是重要的事情，最后取决于我们选择的标准。

提问者Q2：

    国务卿女士，你今天在开罗提到了在沙特这个国家很多人为了行使他们的基本权利而付出了不相称的过高的代价。请问你今天和沙特外长德会晤中是否提到了这一点，你在会晤中是否感受到这一点可能改进的气息？
    
还有，外长先生，为什么贵国会仅仅因为向政府请愿就把人抓到监狱里？还有你能不能给赖斯女士今天在开罗的讲话一点评价？

赖斯：

好吧，我的确在刚才向外长提到了今天上午我在开罗提到的三位不幸被收押者。过去我们给沙特政府提过今后还会提。外长会给出他自己的答案，但我们会保持对这一案件的跟进。我们认为这是一个重要的案件。我对外长如实重复了今天上午在开罗的演讲内容，那就是向政府请愿不应该被定性成犯罪。外长对此类话题非常开放，我期待他自己来回答。

沙特外交部长：

谢谢，我们的确提到了这三个囚犯。我告诉国务卿女士这几个人已经触犯了法律，他们正在被法院审理。我国政府目前无法干涉——直到法庭作出了他们的裁决。

关于赖斯女士今早在开罗的演讲，很抱歉，我忙于欢迎国务卿女士来访的准备工作，所以恐怕我还没有来得及阅读她在开罗的演讲稿，真不好意思。
    
……

（以下为关于关塔那摩沙特籍犯人的处理问题，巴勒斯坦、哈马斯和黎巴嫩真主党武装等等）

……

沙特外交部长：

非常感谢，本次记者招待会到此结束，谢谢你，女士。


【附录之五·朝鲜】

美国传媒机构麦克可拉奇公司（McClatchy Company）对伪钞事件的调查结果（2008年1月10日）

    2年前（2006年），当布什总统在为他的在财政上孤立和搞垮朝鲜政府的运动加温时，他指控这个政权在伪造美钞。

    布什在2006年1月26日说：“当有人在伪造我们的货币时，我们有权要求他们停止这样做。我们正严厉的警告朝鲜政府——不要伪造我们的钞票！”

    可是经过麦克可拉奇历时10个月，跨越三大洲的调查，我们发现支持布什的那些指控证据，最多只能算是模糊的证明。而且新闻报道里提到的所谓北朝鲜叛逃者的声明，都是含糊不清的，更可能是假货（编者注：听起来像当年入侵伊拉克的借口——所谓“伊拉克的大规模杀伤武器”？）。在此事件中的一个关键的机构——瑞士联邦警察局，公开质疑朝鲜是否有制造这种“超级伪钞”的能力。这些美金100元假钞除了一些一般检测器械看不到的附加部分外，几乎是完美无缺的。

    美国政府对朝鲜制造伪钞的公开指控大部分可以追溯自韩国的朝鲜事务“专家”。这些专家安排朝鲜叛逃者接受美国和其他外国媒体的采访。然后这些采访的结果就由美国国会议员、研究学者和布什政府官员直接引用，并以此来寻求对朝鲜施加压力。

    例如，叛逃者们的描述在2006年7月23日出版的纽约时报杂志的指控朝鲜制造精致的超级伪钞的故事里大段直接引用。

    而麦克可拉奇的调查却找到许多理由来质疑这些来源。这几个故事中一个主要证人叫金东植，自称是个化学家。但麦克可拉奇发现他已经人间蒸发。他的一位前同屋叫文国汉，自称他是为钱而说谎话——他对美钞缺乏基本知识，连100美元纸币上印的是谁（正确答案是本杰明·富兰克林）都不知道。

    而美国秘密工作处（Secret Service，该机构专门负责查伪钞）、美联储和财政部都谢绝接受麦克卡拉奇关于此事的调查访问。

    2006年7月，在布什政府的要求下，国际刑警组织进行了关于美国指控的伪钞的第一次国际测试，它召集了各国中央银行、警察部门和印钞企业来研究美国对朝鲜的指控是否属实。这次在法国里昂进行的会议，是在2005年3月国际刑警发出橙色警告后的后续行动。05年的那次警告，是在美国的要求下，国际刑警号召各会员国停止出售印钞机、纸张和油墨给朝鲜。

    但是在这个聚集了60多位世界专家的会议期间，美国秘密工作处——这个美国防止伪钞的牵头单位——从来未能提供任何它宣称的所拥有的任何证据的细节。该机构要求这些聚集的专家们只是凭借对它的信任来接受这些指控。

    “我都不记得在那个会议上我到底是在大笑还是在睡觉了，哈哈”一位出席会议人士在和麦克可拉奇讨论此事时说道。因为和秘密工作处有工作联系，所以他只接受匿名披露。

    国际刑警的秘书长是美国人诺布（Ronald Noble），此人曾在1993到1996年在秘密工作处任职。他谢绝了详细讨论“超级伪钞”问题，因为他宣誓过要对他过去的工作里接触到的保密文件继续保持沉默。诺布说秘密工作处明确的表示，对于他接触过的该局情报，“没有自由和他人分享”。

    最明确的反馈来自瑞士联邦刑事警察局2007年5月的声明。该机构也管理伪钞事务，而且过去和美国财政部门合作密切。该机构号召华盛顿拿出更多的证据出来，瑞士人说他们怀疑那种说朝鲜是超级伪钞来源地的说法。

    瑞士警察局的怀疑，部分的原因来自这样一个事实：自从1989年一位眼睛锐利的菲律宾银行家发现第一张伪钞以来，只有少量的超级伪钞被缴获。该伪钞总量估计大概是5000万，比买印钞机和特殊纸张来印这些伪钞的成本还要低。瑞士机构还怀疑朝鲜是否有伪造这些钞票的技术能力。

    “用过时的七十年代的印钞机，朝鲜今天印的自己朝鲜元钞票的质量是如此之差，令人颇为怀疑它会有本事来印如此高水准的超级美元伪钞。”瑞士警察局的报告说。

    它同时指出，印这些假钞的人，还制造了至少19个不同的版本，而每一版都和美国印钞模板上的细微变化相吻合。

    “如果这确实是假钞，那么这是迄今为止钞票史上最精致的伪造行动”，来自亚利桑那州的共和党众议员科尔比（James Kolbe）说到。他是国会监督秘密工作处经费的人。他认为“我们不确定这种伪造是怎么能做到的，或者说如何发生的。我们不确信如何（北朝鲜）可以得到如此精致（技术）。这活干得实在太精致了。”

    最确切的曝光“证据”来自2004年对伽兰（Sean Garland）的指控。他是一个爱尔兰共和军分裂出来的组织的头目，据称在九十年代末运输了面额100万美元的超级伪钞到欧洲，大部分据说来源于朝鲜驻莫斯科大使馆。伽兰现在在爱尔兰，但是爱尔兰大使馆说，美国并没有对他提出引渡。

   在推动对朝鲜进行伪钞指控的前美国政府官员中，关于美国政府是如何得出这个结论的，几个官员的信息也不尽相同。

    阿舍尔（David Asher）作为国务院工作组的协调人，收集了朝鲜“犯罪行为的细节”。但他说他的小组发现了伪钞的证据，所以并不是依赖于“情报”来拿出结论的。而且阿舍尔——现任职于保守右翼智库传统基金会（Heritage Foundation）的研究人员，拒绝提供任何细节。

而布什总统在8月8号麦克可拉奇询问关于朝鲜造“超级伪钞”有何证据时，声称“我不能自由地讨论情报问题。”

    前布什政府官员，朝鲜事务上的鹰派博尔顿，告诉麦克可拉奇他从来没有见过北朝鲜政府伪造超级伪钞的可信证据。但他说即使朝鲜只是分销伪钞，就足够“证明其坏行为”。

    一位前情报高官说，他从来没有看到足够的证据可以推出结论。“我从来没有真正地亲眼看到情报以能够让我自己做一个独立的有把握的判断，”福特（Carl Ford）说。他在2003年辞去了国务院情报局局长职务，因为他在伊拉克问题上的关键问题上挑战政府，那就是美国政府关于伊拉克拥有大规模杀伤武器的指控。他说，“至于政府在朝鲜问题上对证据细节的讨论，要我来说，凭直觉来说无法信服。”

    另一个证据，是说中国澳门的一个小银行——汇业银行帮助北朝鲜洗假钞。这也显得很模糊。美国财政部把汇业银行列入了黑名单，并在2007年作出裁决，事实上将该银行进行业务封锁，该行事实上只能关闭。

    但据国际会计安永事务所（Ernst & Young）为澳门政府做的审计报告，麦克可拉奇拿到后，发现汇业银行只有一次发现假钞。那次是1994年，而且该假钞并不是来源于北朝鲜。且该银行自己发现了假钞后，通知了执法部门。

    澳门解除了对该银行的惩罚，但是美国财政部，根据“情报”，继续把它留在黑名单上，尽管允许该银行将2500万美元汇回北朝鲜。

    尽管全世界仍然在继续查没“超级伪钞”，布什政府已经不再公开指控北朝鲜伪造钞票。根据国务院官员的消息，在关于北朝鲜核武器计划的谈判中，该议题已经被剔除了。
    所以，现在遗留的问题是，到底是美国政府再一次从自己无法支持的指控中退却呢，还是自己采取主动地下台阶的办法，将硬证据软化下来，以免破坏朝核问题谈判上的努力。
    所以，恐怕超级伪钞的真正来源要变成历史之谜了。行业里的专家，例如美国制版和印刷局前主任弗格森（Thomas Ferguson）说，超级伪钞造得如此之好，似乎是有办法接触美国政府的印刷设备的人才可以弄出来。
    有些专家认为伊朗可能印这些假钞，但其他人认为在俄罗斯或者其他国家的犯罪团伙可能是主谋。
    以该话题出版了《造钱者：钞票印刷的秘密世界（Moneymakers: The Secret World of Banknote Printing）》的本德尔（Klaus Bender）说这些100美元伪钞“不能再归入伪钞了。它只是真钞的‘非法印刷’版本而已。”“它的水平远超于任何通常的伪造钞票可以达到的地步”，本德尔说。他的书首先证明了北朝鲜根本不可能伪造这种超级伪钞。“而且这个伪钞做得如此复杂（和昂贵），以至于也不可能靠它来伪造赚钱。”
    本德尔声称如此高质量的超级伪钞，而且其更新如此频繁，只可能由美国政府的某个部门，比如说中情局制造出来。
    虽然这个指控没有事实根据，但以前有过类似的先例。在他的关于中情局历史的新书里，记者维纳（Tim Weiner）详细的描述了中情局当年如何通过伪造苏联的货币来打击其经济。
    制造少量的精致伪钞也可以帮助情报部门和执法机构跟踪付款或在非法活动。或者用来追踪流氓国家、恐怖组织和其他组织的资金流动。
    “当然，无论这种声称如何荒唐，我们都不会发表评论。”中情局发言人曼斯菲德（Mark Mansfield）答道。

