# -*- org -*-

# Time-stamp: <2011-08-22 14:02:01 Monday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 【第二篇·西域】


人生到处知何似，应似飞鸿踏雪泥。

                                                --【宋】苏轼

十一

布什上台伊始，希望履行他在竞选中对克林顿的对华绥靖政策的批评，实行由“新保守派”12推行的强硬对华政策。

在国防部的鹰派中，如何打造一个“新美国世纪”是其主要的战略重点。为此，七个国家，包括中国、俄罗斯、伊朗、伊拉克、朝鲜、利比亚和叙利亚，被新保守派划定为流氓国家，建议运用先发制人的军事行动予以打击。而在布什政府的要求下，五角大楼准备了对这七个国家的核打击计划13。

当时以美国副总统切尼为首，新保守鹰派人物开始每星期都派人到台湾，暗示美军将支持台湾独立，怂恿新上台的陈水扁政府冒险，害得当时的国务卿鲍威尔也每次都要派特使尾随其后，赶快消毒。14国防部副部长沃尔福威茨15还表演了一场无聊的游戏，将美军订购的价值150万美元共60万顶“中国制造”的绿色贝雷帽堆在野外，当众一把火烧掉，表明与中国誓不两立。

按照切尼的设想，美国应该同日本、澳洲、印尼和印度建立一个亚洲的北约组织，以对付中国的崛起。于是在小布什演说表明要“不惜一切代价保卫台湾”后，中美发生了海南撞机事件，成为中美对抗的一个导火索。虽然最后以美国道歉而暂时解决，但美国在中国边界剑拔弩张的架势已经拉开。此后，小泉在01年五月上台，则开始了他恶化中日关系的靖国神社参拜之旅。

以当时的事态发展，如果没有意外发生的话，我们很可能会在台湾看到一场中国和美日的军事冲突。以当时中国的军力，是无法在常规战争中占优势的，最后可能不得不依赖核武器武器对美国进行威慑。而美国可能对中国打局部核战争的决心表示怀疑，逼使中国不得不在局部动用核武器而避免和美国的全面核战争。


图2.1  2001年的世界局势，美国新保守派上台，瞄准七国，不料拉登横空出世。
从左到右为拉登、沃尔福威茨（时任美国国防部副部长，后出任世界银行总裁）、切尼（时任美国副总统）、拉姆斯菲尔德（时任美国国防部长）

可以想象那会对东亚的和平产生什么样的影响。于是沧海横流，方显枭雄本色。有一个人横空出世，化解了中美在台湾的冲突，使亚洲的亿万人民可以继续和平生活。这个人，就是西方人称为魔鬼的本·拉登。

本·拉登，是个热衷宗教理想的狂热分子，但是却不是一个深谋远虑的战略家。

如果拉登精通权谋之术，他就不应该对美国本土实施如此震撼的911恐怖袭击，引火上身，而是应当继续保持对美国的驻外使馆和军事目标进行规模有限但频繁的小型攻击，建立起一个有效和强力的行动网络，同时静静等待美国的新保守派冒险家们找上中国这块奇硬的骨头去啃，然后再从中浑水摸鱼。

可以想象的是，一旦美国在台湾挑起和中国的战争，本来国际间好不容易达成共识的反核扩散条约就会顿时失效。甚至不排除可能会有国际上的有心人士，通过俄罗斯和巴基斯坦等国，主动让核武器流落到极度反美的伊斯兰武装手里，让他们在世界各地甚至美国本土开辟另一个战场。

但本拉登的恐怖袭击，客观上平息了中美之间的冲突，使中东成为美国迫在眉睫要解决的问题。又因为美国政策决策层在此时对局势的误判，导致了1991年以来的美国独大时代匆忙结束。


十二

美国在911事件后，赢得了全世界大多数国家和人民的支持，国难当头，团结一致，开始向本拉登发动反击，而阿富汗的塔利班就成了美国反击战的第一个牺牲品。

    阿富汗是一个战略地位及其重要的国家，位置处于中亚、东亚、南亚和西亚的交叉点，也是大国地缘政治的必争之地。当年的沙俄帝国为寻找一个暖水军港而南下印度洋，与雄霸南亚的大英帝国展开了一场以间谍和阴谋为主的“大游戏”（The Great Game）。这两个势力在相互“游戏”的时候顺带将手伸入中国的新疆和西藏，这是造成这两个地方独立运动的主要外部因素。两强硬撼而不得，而最后达成妥协的结果，是在中国和阿富汗的边界，以一条狭长的兴都库什山，作为英俄势力的分界线：北边是俄罗斯帝国的中亚，南边是英属印度克什米尔（今属巴基斯坦），中间一道宽度不到50公里的“瓦罕走廊”，归属阿富汗。

本来阿富汗的塔利班在利用伊斯兰原教旨主义的宗教感召力上台后，一扫各地方军阀的鸦片种植业，自己关起门来搞宗教学习，是没有必要踩美国这趟浑水的。但是本拉登在90年代末对美国对外使馆和军舰的攻击行动16，殃及池鱼，害得庇护他的苏丹被美国导弹频频打击。苏丹政府原本想把拉登交给他的祖国沙特阿拉伯去处理。只不过，沙特政府也不想接这个烫手山芋，尤其是其皇室人员和宗教领袖又和本拉登有千丝万缕的关系，不想惹麻烦上身，于是就让经济上完全受沙特支持，宗教上和沙特同声同气，统治地又是这前抗苏战士本·拉登当年起家的老根据地阿富汗的塔利班，作为他的新避难所。



图2.2  上：19世纪后30年英俄在中亚-土耳其一线逐鹿的局面及分界线
中：1879年的一幅画，反映的是新上台的阿富汗王在英（狮）俄（熊）两强中间求存
下：阿富汗东部兴都库什山实地拍摄情景，北边就是雪山林立的帕米尔高原（翁鸿鸣摄）。

其实911之后塔利班是想把本拉登交出去的。他们声称，如果美国能提供确切的证明，他们就可以把本拉登交给一个伊斯兰国家，让他接受公平的审判。但很显然美国没有可能接受这个条件。即使塔利班乖乖的把本拉登交给美国，美国也不会放弃这个出兵阿富汗的绝佳机会。

阿富汗本身虽然有很多稀有矿产，比如说包含金、银、铜、锌、铁等等，并可能有石油和天然气，但最重要的地方，还是在于它的地理位置。占领了这里，就可以以此为基地，控制石油和天然气蕴藏丰富的里海和哈萨克斯坦。而从地缘政治上，在阿富汗建立军事基地，可以北边遏制俄罗斯，配合北约东扩，吞并乌克兰、白俄罗斯和格鲁吉亚，从而几乎兵临莫斯科城下。而如果北约的东扩成功，就可以从乌克兰向南和东南，从格鲁吉亚向北，鼓励俄罗斯外高加索地区的一系列早有异心梦想独立的小自治共和国，如车臣等民族起事。这样，就将彻底打破目前俄罗斯对欧盟能源的垄断“天然气大棒”政策，使从黑海到里海的能源对美国盟友欧洲门户大开，而不需要如同现在这样，欧盟痛苦的经过土耳其、格鲁吉亚及阿塞拜疆，费尽周折来开辟新能源来源，最后在里海能源上还连皮毛都捞不到太多。

	当然，俄罗斯自然不会心甘情愿的让美国和北约在这里为所欲为。可以想象的是，俄国佬当年吃过在阿富汗用兵深陷美国用抵抗战士拨弄泥潭的苦头，自然也知道你做初一，我做十五的故事。对于自己是怎样被人玩死的方法，当然会铭记在心，准备今天以其人之道，还治其人之身。

图2.3 阿富汗对于美国的意义——插在俄罗斯和中国的中间，把握中亚，控制中俄乃至印度


十三

在东边，控制了阿富汗就可以威慑中国，一方面完成对中国西侧的战略性包围，另一方面可以据此为基地，支持新疆的分裂主义势力，在中国西部造成乱局。另外，比邻的中亚对中国能源有重要意义，中国现在需要的石油进口可能已经到2亿吨一年，占总用油量的4成以上，预计到2020年可能增加到5亿吨。现在哈萨克斯坦探明的储油量大约为50亿吨17，如果从哈萨克大规模获得石油，就可以为中国减低其因为对中东和非洲的石油依赖而产生的受制于海上运输必经之马六甲海峡瓶颈而带来的能源风险。

因此，为了应对因为苏联解体而造成的力量转换，在中亚地区，各国政府开始了进行相互之间的合作，以面对军事恐怖主义、宗教极端主义和民族分裂主义的挑战。在2002年，由中国牵头，俄罗斯参与，包括中亚四国——乌兹别克斯坦、哈萨克斯坦、吉尔吉斯斯坦和塔吉克斯坦的上海合作组织成立，以保证中国和俄罗斯的经济和战略利益。而对“四小斯坦”而言，他们并不介意其他大国介入本国，反而是希望以自己的资源和战略位置为砝码，在各大国间玩平衡外交，谋求自己的最大利益。

既然阿富汗有如此重要的位置，美国自然决心挥师阿富汗。由于此事恰好符合中国利益，在获得中国的强烈支持下（中国的利益，一方面是可以借此美国的新战略热点摆脱美国军事压力，另一方面又可以在反恐合作中铲除东突厥斯坦运动恐怖组织），美国得以成功地对巴基斯坦威逼利诱，借其道入侵阿富汗。

美国在阿富汗的军事行动规模并不大，除了天上的狂轰滥炸外，地上的行动全由北方联盟的军阀代理进行。因此在这种不大的攻势下，本拉登能够在托拉博拉（Tora Bora）18脱身，并不令人惊奇。但是美国为了支持阿富汗战争，迅速在乌兹别克斯坦的汗阿巴德和吉尔吉斯斯坦的玛纳斯机场建立空军基地，这就对中国和俄罗斯形成重大战略威胁。

正是因为美军这一布局举动，于是有人认为美国对消灭塔利班和活捉本拉登并非真的有兴趣。项庄舞剑，意在沛公，其真正的战略意图在于控制中亚的石油和天然气资源，以及在中亚建立永久的军事基地，从而对可能的大国挑战者俄罗斯、中国和印度进行战略遏制。

提到印度，这里就不能不提到印度和中国以及巴基斯坦的地缘政治关系。我们只谈到了美国试图对俄中印（至少印度还是一个潜在的目标）的大迂回包围，但是也要看到印度对中国的恐惧。中国同印度北面的国家尼泊尔和不丹交好（这两个国家都担心印度象吃掉锡金一样吞掉他们），使驻扎在喜马拉雅山巅的中国军队对印度具有压顶之势。而中国同缅甸、孟加拉国和斯里兰卡（印度因为支持斯里兰卡的泰米尔反政府游击队而与其交恶）的友好关系，加上印度非法占领藏南的名不正言不顺，还有附近阿萨姆等几个印度东北小邦从未平息的武装独立游击战争，都使新德里的战略家们心惊肉跳。而在印度西面的巴基斯坦，恐怕是中国最亲密的兄弟国家，几乎和上述其它国家对印度形成合围之势。所以当耳闻中国势力进入中亚，尤其是阿富汗时，印度人立即就会心脏病发作。


十四

巴基斯坦在和印度的对抗当中，有一个很大的地缘弱点，就是缺乏战略深度。如果能把阿富汗变成自己的“事实领土”，两国合成“一国”，那么这个纵深空间可以相对得到弥补，这就是为什么巴基斯坦当初希望与其友善的塔利班在阿富汗当权的一大原因。但是在911之后，由于美国威胁巴基斯坦如果胆敢不从帝命，就要把你炸回到石器时代。再加上中国也对自己好言劝告，巴基斯坦只好让美国借道收拾塔利班。

美国对付塔利班还有一个商业的原因。美国的石油公司尤尼科19（中国的中海油购买不成功，后被雪佛龙公司20收购）曾与天然气丰富的土库曼签订铺设油气管道的合约，计划通过阿富汗和巴基斯坦将能源输送入印度。这样不光能使美国在印度经济起飞中得益，而且可以通过建立开关阀门的办法控制印度能源咽喉，令印度受制并服务于美国全球经济和外交战略。（编者注：尤尼科在美国国会的证词及其它资料，请读者参考卷后附录。）

当时尤尼科请了几位顾问。其中一位就是哈利勒扎德，美国新保守派的主要人物，阿富汗裔，美国布什政府的中亚和中东事务的主要智囊21。哈利勒扎德曾游说塔利班支持这条油气管道的建设，但是未来得及达成协议就发生911，因此不得而终。另一位则传言是阿富汗人卡尔扎伊22，此人在美国生活多年。所以当美国推翻了塔利班后，卡尔扎伊就成了阿富汗新政府的总统，而哈利勒扎德就成了他的太上皇——美国驻阿富汗大使。当然，这把自己人变成了总统，阿富汗过境油气管道协议自然很快就出结果。可是让美国头大的问题就是塔利班残余势力无法清除，使这一工程一拖再拖。结果到俄罗斯和中国联合出手，买下了不少土库曼的石油和天然气资源，又将了美国一军，在源头上翻了牌。
 
图2.4 哈利勒扎德和卡尔扎伊

美国要在中亚长期驻军，当然会引起中国和俄罗斯的反对。于是在2005年，以上合组织的名义，中俄要求美国从中亚撤出军事基地，理由是阿富汗战争已经结束，并且美国的主战兵力已经在伊拉克开打了好一阵了，说明阿富汗并非威胁美国的重点地区。美国拒绝了这个要求，声称只有在阿富汗局势彻底稳定后，美国才会考虑这个问题。

当然，所有的明眼人都知道，阿富汗是进军中亚的借口，而中亚的乌兹别克斯坦和吉尔吉斯斯坦的这两个美军基地为的是中亚本身，和阿富汗根本扯不上直接关系。但是如果美国希望能够长期的保持这些基地，就必须在这些国家策动颜色革命。于是就像在乌克兰的橙色革命和格鲁吉亚的玫瑰革命一样，吉尔吉斯斯坦在2005年4月发生了郁金香革命。不过随后5月在乌兹别克斯坦运作的安集延造反却以失败告终，于是美国和欧盟施加压力要求联合国介入进行调查，结果乌兹别克斯坦一怒之下将美军赶出了其领土。

其实，美国在吉尔吉斯斯坦的基地得以保留，不光是颜色革命成功的功劳，还因为该国太穷，要点外汇花。美国一年的租金就是5000万美元（后来因为被中国和俄罗斯抗议，租金已经加到了1亿5000万），在加上其他援助1000万，对这个500万人口的穷山国是不少钱。也正是因为如此，不敢得罪中国和俄罗斯的吉尔吉斯斯坦，一方面参加上合组织对美国撤军的合唱，希望能以此为理由要挟美国涨租，另一方面又在美军基地旁划出地来，请求中国和俄罗斯租为军事基地，这样它可以饭吃三家。23


十五

美国在吉尔吉斯这个军事基地驻扎了大约一千兵马，到底会对中国有多大威胁呢？其实威胁并不大，如果真的中美开战，这点人马连填牙缝都不够，可能在开战的头几个钟头，就会被驻扎在比希坎的中俄快速反应部队清理掉。就算是美国在阿富汗的一万三千军队一起上，都不是什么大数目。

但是，在和平情况下，军队的驻扎不光可以显示军力，而且可以影响和加强当地的亲美势力，使当地政府的政策受美国影响。

不过美国在阿富汗和其他中亚国家的部署，有一个极大的缺陷。就是这些国家全是内陆国家，美国必须从其他国家借道，才能在紧急情况下，对其驻扎在此的有限的兵力进行支援。现在美国是通过巴基斯坦为阿富汗和中亚的美军和北约盟军提供通道和后勤支援，但是有一个致命的问题是：巴基斯坦是中国最重要的兄弟和盟友，一旦美国在阿富汗的军事行为矛头开始针对中国，巴基斯坦就会毫不犹豫限制美军在阿富汗的人数，甚至不惜切断美军的运输线。24

虽然巴基斯坦的主要敌人是印度，希望和美国及中国同时保持良好的关系，但是如果必须在中美冲突中作一个选择的话，巴基斯坦一定会选择中国。加上美国在阿富汗的行动同巴基斯坦的地缘利益相冲突，并将战火引入了其西北部的部落区。根据2008年2月由美国和平研究所在巴基斯坦进行的民意调查表明，巴基斯坦老百姓已经把美军在阿富汗和中亚的行

图2.5  巴基斯坦2007年年底的民意调查表，表明美军已经超过印度成为第一威胁25

动分别看作对巴基斯坦利益的第一和第二负面因素，而巴基斯坦人恨之入骨的印度倒是退居第三位。

美国在巴基斯坦人的心目中是个靠不住的朋友，需要利用你的时候，就热情无比，用不着的时候，就一脚把你踢开。巴基斯坦在历史上已经吃过两脚。一是在80年代末，在利用巴基斯坦来培训和支持阿富汗游击战士去反抗苏联成功后，美国把贡献很大的巴基斯坦晾在一边；二是对巴基斯坦发展核武器进行制裁，却毫不考虑巴基斯坦在印度拥有核武器之后那种没有退路和选择的实际战略处境。加上现在美国在巴基斯坦的政策只是考虑巴基斯坦如何配合美国在阿富汗的政策，而不考虑巴基斯坦自身的战略和地缘利益。所以巴基斯坦在对美国的配合问题上，比如打击部落地区的塔利班同情势力等事情，基本上是半推半就，敷衍了事。26

相比而言，中国却是巴基斯坦的全天候伙伴，对巴基斯坦政府和人民一直都采取支持态度。与中国合作，除了军事和国防上的合作对印度具有平衡作用外，还能使得巴基斯坦在伊斯兰世界中成为拥有核武的最有声音的大国，增加了它在伊斯兰国际组织中的话语权。



图2.6  上：巴基斯坦瓜达尔港的重要战略地理位置示意图
中：瓜达尔地区的地理位置使得是天然良港
下：瓜达尔航拍照片（面向北方大陆的视角）

在中巴合作中，最具有代表意义的就是瓜达尔港（Gwadar Port）的建设项目。瓜达尔港以及接通卡拉奇的沿海高速公路，为巴基斯坦海军提供了可贵的战略深度，防止了印度在海上对巴基斯坦的封锁。而这个在波斯湾口的港口，在军事上可以起到监视波斯湾海上交通的作用，在商贸上，则可以成为中国的海外物资集散地，将中国需要的石油、天然气和原材料送进，把中国的制成品送出来，输出到中亚、中东和非洲。


十六

瓜达港的另一个作用，就是使中国的能源进口可以躲过马六甲这个瓶颈。现在大约超过80%的中国进口的石油必须从马六甲海峡通过。即使不算那些印度洋里流窜的海盗带来的威胁，中国石油航运安全在马六甲海峡入口处基本处在印度海军的虎视监控下（安达曼群岛），而出口处基本上被美国海军控制（新加坡等）。一旦有地区冲突发生，缺乏远洋舰队的中国，就必须忧虑运输线的安全问题。


图2.7 目前依靠于马六甲海峡的被动局面，与未来中国与中东非洲乃至印度经济一体化的主动局面的对比

    美国发动反恐战争后，曾通过新加坡提议由美国海军巡航马六甲海峡。这个提议遭到了中国的反对，中国通过马来西亚和印度尼西亚提议，由新马印尼三方共同负责海峡的安全。在这种老路到处是虎狼的情形下，新开的瓜达尔港对中国开拓新的能源运输路线，保证经济和战略安全就非常重要。开通瓜达尔到新疆的输油和输气管道，可以同来自哈萨克等国的管道汇集，加上新疆自身的石油和天然气开采，将把新疆打造成中国的能源工业基地。同时，除了负责能源的东去，新疆又可以将中国制造业的产品西送，成为中亚和中东的主要消费品集散和生产地。这样的战略才能为中国的西部大开发战略起到真正的助力。

但是现在的西部开发有一个大问题，就是在新疆的“西气东送”（和贵州的“西电东送”一样），还是主要以服务东部为主。由于本身的技术含量太高，要求的专业人员所需要的技能，往往是西部当地居民尤其是少数民族居民所缺乏的。这样就不得不从东部人才市场引进工作人员。这就使得西部开发的成果，似乎没有让包括少数民族在内的西部老百姓充分享受到。即使增加天然资源开发的分红比例，让当地留成的利润分红可以投入少数民族的社会福利、医疗保险和教育，也还是不足以创造出足够的就业机会，给职业水平低的，包括广大少数民族在内的当地贫穷农民群众。如果继续如此，恐怕无法让他们真正感受到经济开发的好处。这可能会给一些别有用心的国外组织和恐怖主义分子的渲染留下操作空间。

其实，我们应该吸取东部的发展经验。过去十几年，在东部沿海形成的大规模的制造业，为中西部的农村剩余人口提供了大量的低中工资的工作机会。目前新疆各级政府针对这种局面尝试了劳务女工输出的方法，送出了一定量的维吾尔农村姑娘到沿海的天津，山东，浙江和广东工作。这些女工一个月的工资有时可能就是贫困家庭一年的收入，为少数民族的脱贫起了一定的好作用。但是考虑到生活方式的不同和地理上的不便，中国应该考虑在新疆如乌鲁木齐、伊犁或喀什等地建立类似东部沿海的加工业，专门面对中亚、俄罗斯、中东、非洲和东欧市场。这样可以节省来自西部和从中亚进口的能源和原材料向东部的输送的成本浪费，又可以节省将东部制成品向以上市场出口的运输成本。最主要的是可以为当地的各族人民，尤其是少数民族，创造出大量的本地就业机会，在保证当地人民就业的情况下，还可以吸收其他西北省份，如甘肃，宁夏，陕西等地的剩余劳动力。

当然要使这个方案成功，道路，通信，电力等基础设施必须先行，才可以重振这个古代被誉为“丝绸之路”的欧亚大陆桥。

考虑到目前几乎所有的中东商人都活跃在浙江，而非洲商人都活跃在广东，两地小商品交易会热闹非凡的情景，可以看出这个方案有很大的潜力。当然任何经济发展都离不开稳定的社会局势，而中国和巴基斯坦的合作，能够对中国新疆的稳定，以及巴基斯坦经济发展和生活水平提高起到非常正面的作用，进而使恐怖主义失去市场，对两国都是得益非浅。


十七

巴基斯坦对中国的重要性，除了牵制印度，提供替代的能源和产品通道，杜绝疆独恐怖主义势力的发展以外，还可以作为中国的伙伴，增加中国和中东以及北非的伊斯兰世界的紧密关系。

可以设想的是，如果中巴的石油气管道可以顺利畅通，通过喀喇昆仑山的铁路和高速公路顺利建成，中国从伊朗和伊拉克进口的石油和天然气都可以从这里进来。那么中国的海上能源运输线，就只需要为巴基斯坦的瓜达尔港和北非的苏丹港之间的航段提供保护。

如果挂着五星红旗的中国海军军舰出现在这些地方，也许北美和欧洲的某些人就会集体心脏病发作。但是，如果中国可以保持低姿态，让具备一定实力的巴基斯坦海军担任这个巡航任务，那么估计来自西方的噪音也许没有这么大，而与巴基斯坦关系极好的沙特阿拉伯和其他的穆斯林国家，也都不会对“伊斯兰自己”的海军有异议。也许，中国与巴基斯坦在海军方面的合作，不光是由中国军舰厂商装备巴基斯坦海军，而且还应该包括人员的互派，甚至在特殊情况下，可以两国商量协定合作，让中国军舰以巴基斯坦的名义，如挂巴基斯坦国旗进行必要的巡航任务。27

图2.8 在本笔记写作8个月后，美国《外交事务》周刊针对中国海军护航亚丁湾发表文章（编者加）

当然聪明的美国人不会看不到这些发展。瓜达尔港和贸易能源通道也有一个潜在的问题，就是其所在的俾路支斯坦省28有少数当地民族分离分子，对巴基斯坦政府不满，进行恐怖活动。而美国在巴基斯坦的主要战略目标，就是阻扰中国在巴基斯坦的影响力增大，制造对这一能源贸易通道的不安全因素。

俾路支斯坦的问题，和当今世界绝大多数的问题一样，都是英国人整出来的。英国为了和俄国对抗，扩大在印度的地盘，于1839-1842年，发动了对阿富汗的第一次侵略战争。英军很快占领阿富汗首都喀布尔，扶持起傀儡政权，但好景不长，两年多后，在阿富汗反英力量的打击下，英军不得不连同所有的当地支持者，向印度撤退。当时的英军为第44步兵团（后来重组参加了侵略中国的第二次鸦片战争）的一个营（大约500人）加上印度兵（大约4000人）共4500人，和随军的家属以及其他平民包括妇孺10000多人，合计总数为14000-16000。这批人马在撤退中，遭到了阿富汗部落的攻击，最后只有不足40人生还印度。英国人中只有一个叫贝登的军医侥幸逃生到加拉巴巴。他其实已经受伤，但阿富汗人决定放他一条生路，让他作为信使告诉英国政府不要再干涉阿富汗。

图2.9 巴基斯坦四大民族：东北旁遮普族、东南信德族、西北普什图族和西南俾路支族的地域分布图
及瓜达尔港口的相对位置

如果就此善罢甘休，那就不是英国人。在这之后的几十年中，英国从来没有放弃杀回阿富汗的努力。终于，在1880年第二次英阿战争后英国占领了阿富汗全境。然后英国拿出自己的拿手好戏，就是迫使阿富汗政府接受边界划分。这个划分既不考虑地形情况，也不考虑民族分布。结果就是把普什图民族划分在今天的阿富汗和巴基斯坦两个国家，又把俾路支民族分到今天的阿富汗、巴基斯坦和伊朗三个国家。

俾路支是个游牧民族，本来习惯于随水草而迁，过无拘无束的游牧生活。被人这么一分，当然不是太满意，所以一直就有分裂运动。巴基斯坦联邦政府除了打击武装分裂分子，推行民族团结政策外，提高俾路支人民的经济生活水平，减弱部落头人的影响力，都是政策考虑过的方法。而瓜达尔港和连接卡拉奇的马卡然沿海高速公路的建设，事实上都起到了一些这种正面效应。

对美国而言，在敌国伊朗境内的俾路支分裂运动，当然是求之不得，毫无顾忌，直接介入29。但是对巴基斯坦，就要慎重一些，避免随意支持最后影响了和巴基斯坦的合作关系。当然，如果美国能在其中找到专门攻击中国利益的代理人，那便是最佳安排。所以计划首选，就是借手印度军情部门在阿富汗帮助支持恐怖组织“俾路支人民解放军”，而美国却装出毫不知情的样子，这样达到了目的又避免直接冲突。


十八

这一轮的俾路支分裂运动的主要动作是在部落头人布格提30的领导下，针对巴基斯坦的瓜达尔港的最后完工进行恐怖攻击。而恐怖分子运用的武器装备颇为先进。在攻击巴基斯坦军警的同时，也针对中国公民，主要是参与建设的中国工程人员。令人寻味的是，所有号称对中国公民的攻击都算到了伊斯兰极端恐怖势力的头上，但却没有任何具体的组织为此宣布负责。

巴基斯坦军队对此作出了很快的反应，在2006年8月，成功的将布格提猎杀，炸死在山洞里，基本上清扫了他的恐怖势力。由于很难寻找到合适的替代人，美国不得不启动B计划。

在美军关塔纳摩监狱的基地组织和塔利班重犯中，有一个人叫马素德31，在同美军作战时被俘。经过了至少两年的监禁生活后，美国确定他不再是对美国有危险的人物，放虎归山。
马素德具体释放的日期并不清楚，所以难以判断是在布格提死之前还是之后。按照美国舆论界的说法是，马素德坐了两年的牢，然后美国政府误认为他不再坚持恐怖主义，所以就人道地放了他。但是按照巴基斯坦的消息，他其实在关塔纳摩呆了五年，是布格提死后释放的。

但有一点可以确信，虽然马素德声称他的组织是反美的，但从来没有对美国目标进行任何攻击，反而很快的绑架了两名中国工程师，其中一人在巴基斯坦军队的救援行动中死亡。巴基斯坦军方同样对其进行了又快又狠的打击，马素德本人在俾路支斯坦的团伙和辅佐他的美印情报人员，在2007年7月，被巴基斯坦情报机构一锅端。

如果用中国的传统权谋术语命名的话，美国这一招应该叫做“敲山震虎”，用小股美国可以控制的影子组织，隐藏在大股分裂势力的乌合之众中，采取极度低姿态的做法，对中巴的合作项目进行骚扰。通常的分裂组织和其他为意识形态而战的恐怖组织，一般是采取高姿态的做法，又发宣言，又上电视，唯恐天下不知道他们的厉害。而所有针对中国人的袭击，完全是悄无声息，显然不是这种普通的乌合之众所为。
 

图2.10 布格提年轻时面见巴基斯坦国父真纳的照片与年老的照片；布格提被炸弹炸死前所住的山洞

接着，美国的下一招就是“借刀杀人”。大约在2007年中，美国、加拿大、英国和澳洲的媒体开始了一场舆论宣传战，在电视上对中国进行抹黑，渲染中国在新疆对维吾尔族进行灭绝政策。这场宣传战的目的是多重的，其中一个目的是为加拿大、英国和澳洲接收计划将释放出来的尚在关塔纳摩关押的20余名维吾尔族圣战分子作好舆论准备。美国曾在全世界推销这些恐怖分子，说他们无害，可以放心接纳，但被多数国家拒绝，只有４名情节较轻的被阿尔巴尼亚接受（主要是看在美国帮助科索沃阿族独立的份上），但被严格限制行动自由，如同坐牢。于是在美国，那个号称政治独立的公共电视台（PBS）32制作了一个专题采访片，由一位华裔年轻女记者方女士（Serene Fang）施展全身解数，尽力误导对新疆一无所知的美国民众。

其中一个场面，是方记者搭上一个没什么文化的汉族男司机的出租车，一路上分秒不拉，不停套词。方女士故意问司机会不会考虑娶个当地的少数民族太太。这个司机正为拉上个外国游客的长途生意高兴的手舞足蹈，随口说不会，其主要原因是生活方式不同，在饮食上有差异，如果结婚不能适应配偶的禁忌。方记者穷追猛打，故意直问原因。这个笨头笨脑的司机毫无戒备之心，犯了禁忌。我们知道，中国的各民族之间，由于信息上相对封闭，存在一些误会，甚至有的人还有歧视本民族以外群体的坏现象，但是这个方女士的导读方法却是万分恶毒。听完这个司机的见解，她马上加进解释说，这种误解当地少数民族的态度，其实是“中国人”持有的“大量（歧视）态度的典型”（要记住，西方媒体的“中国人”只是指汉族中国人，所有非汉族中国人都不是“中国人”，他们的居住地也不是“中国”，而是“中国”非法占领的殖民地）的态度。

看了这个节目，估计西方的观众会很讨厌中国人，并开始同情那些关塔纳摩的“维吾尔自由战士”。而从这位华裔的记者口里说出来，估计公信力会更高。所以，有些美国的穆斯林青年看到这里，就开始签名要抵制北京奥运会了。看来中国的媒体在学习美国同行的本事上，有好长一段路要走。

这个节目的另外一个场景就更有趣，为了显示“中国人”如何打压少数民族的“正义反抗”，这个节目用了一个中国人熟悉的公审大会的镜头。根据笔者的一个新疆的维族好友介绍，其实这是PBS剪切了新疆电视台播出的一个新闻片段，这个新闻讲的是乌鲁木齐法院审判一个贩毒集团，而这个贩毒集团成员是跨民族的，但为了传递这是一个政治犯被审判的信息，所有汉族罪犯的镜头被删除，只留下看起来不像“中国人”的罪犯的镜头。不过可笑的是，在审判台上大声宣判的法官却是个维吾尔族，说明编造水平还有待提高。

当时笔者把这些细节指出来，有人还认为西方媒体不至于这样没有道德。估计在看完西方媒体对西藏暴乱胡编乱造的无耻行径之后，大家都不会再感到不可思议。


十九

这场宣传战的另一个主要目的，就是把伊斯兰极端势力沸腾的热血，用导引的方法，流向东边。

本来，活跃在巴基斯坦部落区的伊斯兰极端恐怖分子，其主要目标是英美势力。如果能够通过宣传中国如何迫害穆斯林，再鼓动起这些中东极端分子在参加其他穆斯林圣战中与那些东突分子建立起的生死战斗情谊（比如说当年在南斯拉夫的波斯尼亚和科索沃、俄罗斯的车臣甚至印控克什米尔的战争），就会激起广大圣战分子们对东突恐怖组织的同情。这个宣传战做得好的话，就可以四两拨千斤，让这些恐怖主义的洪水猛兽扑向中国。

其实，美国在阿富汗战争中已经和东突恐怖分子交过手，并吃过亏。曾有传言，中国新疆的特种部队曾经为救援受困的美军小部队尔同美国协同作战。在美国同意把东突恐怖组织列上美国黑名单上后，美军还在关塔纳摩监狱里提前做好“准备”工作，以方便中国情报部门的审讯人员问出情报。

如果美国和西方的战略目标真的是要彻底清除恐怖势力，就应该始终如一的和中国合作，共同创建出一个和平的世界次序，而不是根据自私的目的，把恐怖分子当作一种损人利己的工具。对自己的利益不利的时候，就是恐怖分子；对他人的利益不利的时候，这同一帮人，就被定性成了“自由战士”。这样做，最后的结果就是迫使其对手以其人之道，还治其人之身。双方互相推手，那么“歼狼术”就变成了“赶狼术”，只要恐怖分子被赶过来，北约军队就停止追击。而中巴军队也是将其再赶回去以对付北约而已。

    可是，美国恰恰要把这场反恐，变成一套把戏。

美国的这些动作，一般由媒体宣传战开始，而后由外围的政治势力国会议员们发难，然后才由美国国务院、国防部和财政部出手。2008年，为了配合美军入侵巴基斯坦的军事行动，美国已经在中国新疆问题上走出了第二步。 

这第二步，首先是在2008年5月22号，由来自美国俄亥俄州的参议员布朗在第110届国会第二次会期上提出第574号法案，要求中国政府释放参与分裂活动的热比娅的孩子和持有加拿大护照的恐怖分子玉山江，并攻击中国在文化、语言和宗教上迫害维吾尔族。

从这个法案上可以看出几个趋势：

1．美国试图在东突分裂势力中将热比娅树立成一个精神领袖。2007年布什在捷克首都布拉格专程接见热比娅，瑞典国会议员提名她为诺贝尔和平奖候选人，都是想模仿达赖喇嘛的先例，为东突分裂运动提供整合的平台。

2．以玉山江为先例，通过由西方国家提供护照，来为东突恐怖分子提供司法保护，利用外交对中国施加压力。当然在这方面，提供护照的加拿大重量级太轻，中国可以不予理睬，但如果美国都这样发护照，那么中国就可能会投鼠忌器。在西藏问题上，就出现了类似的问题，笔者个人认为，中国的表现其实还可以更强硬一些。

    （该事件此后的发展，应证了作者在这里的语言，详见卷后附录。——编者注。）

话说在这个抹黑中国的宣传战渐入佳境时，2007年年初，英国媒体“适当”的披露一条消息，即关于穆沙拉夫将巴基斯坦军队捉拿的东突恐怖分子递解到中国去处理。这一下激怒了巴基斯坦的极端分子，于是引发了轰动全球的红色清真寺事件。

红色清真寺是巴基斯坦首都伊斯兰堡颇有影响的宗教基地，曾因为阿富汗抵抗苏联的圣战和克什米尔的反印斗争提供了大批敢死勇士而立下汗马功劳，也是巴基斯坦达官贵人常去崇拜的场所。但是，近年该寺与极端派越走越近，而且因为巴基斯坦政府和美国的合作，开始与政府有不小的分歧。只不过刚开始的时候，这些分歧，更多的表现在清真寺的少男少女学生们在街上跑来跑去，做些道德警察的无聊事。但这一次，开始有人把中国人作为攻击目标，绑架了几位在伊斯兰堡工作的中国公民，制造出一个国际事件。

在绑架中国人之前，道德学生们骚扰商店，扣押警察，但是都基本上在警方的克制下和劝告下，和平解决。一旦牵连到中国人，巴基斯坦政府开始坐不住了。穆沙拉夫和巴基斯坦总理亲自听取每分钟的汇报，中国驻巴大使向胡锦涛主席多次汇报谈判进展。而巴基斯坦所有具有影响力的政治和宗教领袖都竞相出场，最终说服了清真寺释放了人质。


二十

但是，这个事件给了巴基斯坦政府非常大的难堪，所以在派高官去北京对中国领导人表示道歉之外，巴基斯坦决心在这件事情上划出一条底线：即不允许任何巴基斯坦内部势力，在相互争斗中把中国利益当作目标。与中国的友谊是与巴基斯坦之国家老本相关的外交关系，高于巴基斯坦各派利益，因此列为禁区而不许有人越雷池一步。

据未公开的消息，提议绑架中国人的学生中，不排除有维吾尔族恐怖分子潜藏其中的可能。因此此事是为2008年北京奥运会进行恐怖活动做准备，趁此机会攻击中国目标。因此巴基斯坦政府决定将清真寺包围，直至极端分子放下武器全部投降。可是在这个关头，极端分子在白沙瓦杀死了三名中国商人，让穆沙拉夫怒不可遏。于是他下令对红色清真寺发起强攻，将顽抗的武装分子彻底铲平，一举让数百极端分子送了命。

图2.11 红色清真寺强攻后爆炸的场景

巴基斯坦这一强硬的做法，令西方非常的不快。因为每当美国催促巴基斯坦军方对部落区的塔利班势力动真格的时候，巴基斯坦总是找出种种借口，推三拉四而敷衍了事。看来，巴基斯坦不是没有决心对极端分子大开杀戒，而是要看极端分子对付谁。如果对付的是西方，巴基斯坦政府就会嘴上说说，而没有真正动静。但极端分子如果敢向中国开刀，巴基斯坦政府和军队一定让冒犯者死无葬身之地。

如果你看一下穆沙拉夫宣布戒严令的演讲，就可以了解这个不争的事实。穆沙拉夫的讲话，主要用乌尔都语，只在中间穿插发表了一阵针对西方听众的英语讲话。而在巴基斯坦的乌尔都语讲话中，他对本国听众宣布，极端分子对巴基斯坦最亲密的朋友中国的无耻行为，不光令国家蒙羞，还令他个人感到羞愧，他不得不向中国朋友道歉。

    （有关穆沙拉夫的演讲词，请参考卷后附录。——编者注。）

图2.12 穆沙拉夫就红色清真寺事件发表乌尔都语和英语穿插的全国讲话

这句表态，在从来以美国为中心的美国人心里，非常不是滋味。一个在巴基斯坦进行颜色革命的方案于是开始酝酿。这个方案的主要目的是扶持一个更加亲美的巴基斯坦政权，以平衡和遏制中国在巴基斯坦的影响力。这个政权必须要做到：

1．允许美军在巴基斯坦领土上进行军事行动。目前美国的行动基本上是定点式暗杀轰炸，针对塔利班的领导阶层。如果美国可以随意用兵，不光可以选择时间打击塔利班，还可以以此为幌子，扰乱中巴的交通要道喀喇昆仑山公路。

2．允许美国控制和“看守”巴基斯坦的核武设施。如果美国在部落区进行军事行动，可以预想到塔利班不得不向南部避其锋芒，而试图攻击美国从卡拉奇到白沙瓦的军队补给线，把恐怖战斗带进巴基斯坦的心脏地带。美国可以以局势严峻，巴基斯坦的核武器可能会落入基地组织手中为借口，出兵巴基斯坦，把巴基斯坦的核武器拿到手中。

3．允许美国直接控制巴基斯坦核子弹之父卡迪尔汗。如果美国控制了巴基斯坦的核武器，就可以很快发现汗和朝鲜和伊朗的真正关系，然后弄出证据出来去证明他的核扩散行为不是私人的行为，而是巴基斯坦政府的行为。而经过这一证明，国际社会就会同意，巴基斯坦政府不是一个大家可以相信的政府。为国际安全着想，联合国就可以委托美国来托管巴基斯坦的核武器。而且如果巴基斯坦合作的话，美国还可以作中介，促成巴基斯坦和印度签署一个互不使用核武器条约。那样，巴基斯坦就不再需要核武器，可以被销毁。转由美国为巴基斯坦提供核保护伞，从而实现完全控制巴基斯坦的目的。

4．不过，要让以上三点成为可能，巴基斯坦军队和情报部门必须改组，变成一个愿意和恐怖分子战斗的组织，当然改组后的军方必须亲美而非亲中。

美国找到的代理人是当时流落海外的人民党领袖贝·布托女士。她看到有机可乘，立即在美国发表美国人愿意听的所有承诺，把每张空头支票都开出来，至于倘若她真的上台，这些支票会不会兑现，笔者和许多行家都表示怀疑。可惜的是，布托女士出师未捷身先死，在第二次针对她的暗杀活动中死于非命，把美国的颜色革命计划彻底打乱。








































【写作日期】2008年6月5日——14日            


