# -*- org -*-

# Time-stamp: <2011-08-30 10:25:09 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 【第七篇·亚洲】

#+begin_center
【写作日期】2008年7月6日——7月12日 
#+end_center

坐地日行八万里，巡天遥看一千河。
--【现代】毛泽东

+ 六十一

美国和欧洲对未来有两个担忧，一个是世界经济中心随着中国和印度的崛起而转移到亚洲。在未来的二十年后，这个世界的经济非常有可能出现中国第一，美国第二，日本第三和印度第四的局面。待到了那个局面下，美国还可以继续利用其可观的军事实力，以及一个太平洋国家的身份，参与到亚太区为中心的世界经济活动中，而其他的国家则需要通过重新定义自己与亚洲主要经济体的关系，以求在新体系中分一杯羹。以出产能源和其他农产品来满足中国和印度巨大市场的国家，如澳洲、加拿大、南非、巴西，以及中东、中亚、非洲和美洲的许多国家都会在这个经济变化中受益，而全世界经济地位下降，遭受最大损失的会是欧洲国家，尤其是西欧国家，如英国、德国、法国和意大利等。

第二个担忧是一旦形成以中国为主的经济体系，用非西方的东方文化来勾画国际事务游戏准则，那么经济地位衰退的西方将失去对国际事务的操控权。同美国相比，欧洲的大问题是，不光无法形成一个更紧密的政治体系，连军事实力也已经名存实亡。美国在为达到自己的战略目的进行军事威胁时，经常会威胁把对方炸回石器时代，而欧洲则已经不再具有这种能力。不久前，伊朗把闯入两伊争议海域的英国海军士兵抓获，英国也是毫无脾气。德国人在美国的占领下，已经逐渐失去斗志，搞得军队的教官要不断提醒训练的士兵，想象自己在美国的街头，面对暴动的“黑鬼”，拿出点杀气出来。[fn:jdwtdgyx0776]而有趣的是，法国外交部长要求联合国安理会授权用武力进入缅甸强行救灾，不知如果联合国真的授权给法国，法国军队有没有胆量杀进去？法国人记不记得奠边府是怎么一回事？

[fn:jdwtdgyx0776] 此事出自德国军队的训练录像， 一位德国陆军教官告诉他的士兵：“你在（纽约）布朗区，一辆黑色的客车停到了你的面前，三个黑人从车里跳出来，用最难听的脏话问候你老妈……好，行动！”随即德军士兵扣动机枪扳机，扫出一派子弹，并大声叫骂：“黑鬼，你死吧！”教官大声呵斥：“他妈的给我骂大声点！”这个录像后来被人曝光。

既然有这样两个担忧，那么就必须拿出办法来。而这个办法就是以民主自由为幌子，建立起一个亚洲的北约组织，以美国为领袖，形成一个东从亚洲的日本开始，笼络东盟、澳洲、印度、由美国控制的中东和中亚，再延生到已加入北约的东欧和南欧，直到英国为终结的半圆，对中国和俄罗斯形成一个完整的包围圈。而在这个计划中，由于印度洋是美国军事实力的软肋，所以把印度拉上船是一个关键点。美国最近破坏国际防止核扩散条约的协定，签署《印美核协议》，向印度输送核技术和原材料，变相的鼓励印度发展更大规模的核武器，就是出于这一考虑。但是要真正遏制俄罗斯和中国，光靠各种军事同盟并非有效，必须靠建立起遍布东西盟友刀枪不入的全球导弹防御系统，控制住中俄的核打击能力，只有这样才可能让这些同盟国家感到安全得到真正保障，心甘情愿的充当喽罗。

但是现实有一大软肋在于，欧洲的能源，尤其是天然气，卡在俄罗斯手里。任何面对俄罗斯的举动，自然会受到俄国的报复。俄国的国力还在进一步恢复中，其反应力度基本上会根据国力的大小而决定，但这起码已就造成了欧洲反对美国将乌克兰吸收进北约组织的提议。所以，既然西边包围圈暂时封不上，就在东边先扎圈，所以出现了以美国、日本、澳洲和印度四国形成的准军事同盟。这个同盟打破了以前美国在亚洲只与单独国家建立双边军事同盟的惯例。不过也正是因为这个突破，亚洲的国家自己也可以趁势建立内部的双边关系。

图7.1 印度和乌克兰是大包围圈中的两个缺口，美国要尽力争取拉拢


+ 六十二

本来，美国的意图是争取将东盟数国拉进来，但由于中国在亚洲金融危机之后成功的改善了和东盟国家的关系，所以美国收效不算明显。印尼已经不愿因为参加任何针对中国的行动而影响它的能源在中国的销售以及中国在印尼的投资。马来西亚和菲律宾则不愿意公开和中国作对，但则不排除允许美军在其南海附近的岛屿中，进行持续的军事演习而形成威胁力量。尤其是菲律宾，自从将美国踢出苏比克后，它的宪法不允许外国驻军，美国为了绕过法律，则以反恐合作和军演的名义，不停顿的在菲律宾的南部岛屿中进行各种各样名目的不间断演习，造成美军在菲律宾南部的事实驻军。

在东盟各国中，对美军支持最积极的，反而是与中国人同文同种的新加坡。新加坡不光为美国提供樟宜以建立军事基地，而且也是东南亚地区“依伴美国军力”的最大倡导者。除去“黄皮白心‘假英国人’”的意识形态老底以外，新加坡的想法，其实是既利用美国的军事实力保证自己安全，但同时又利用中国的经济发展带动地区发展来分一杯羹。只不过，他们没有想到，如果美国的军事实力被用来限制中国的经济发展，他们应该做怎样的选择？尤其是如果中国面对这种老路被卡的情况，选择一个替代“新路”，比如说动用巴基斯坦的瓜达尔港，或者缅甸的实兑港（Sittwe），或者开通泰国的克拉运河（Kra Canal），都会对新加坡的经济带来一定打击。而现在新加坡强力支持美军的积极态度，又是中国不得不积极寻找替代路线的一个重要原因。

图7.2  新加坡岛屿东部的樟宜区，未来的美国亚太海军基地所在地

 
图7.3 缅甸实兑港是中国和印度都有意重点开发的港口

而越南就更不愿意踩这趟浑水。虽然中越在1979年打过一仗，且越南至今意图染指中国的西沙群岛和中沙群岛，而又在南沙群岛仍然控制一些与中国存在主权争议的岛屿，但越南直截了当拒绝美国希望租用金兰湾的要求，试图建立一个与中国睦邻友好的关系。其他的印支国家即老挝和柬埔寨则完全站在中国一方，希望中国的经济发展可以把他们带出贫穷落后。泰国的形式比较微妙，既有和美国的传统友好关系，允许美军的存在，又重视和中国及其他邻居如缅甸的关系，不会一味跟随美国的地区政策。目前泰国的民主体制造成其政局的持续动荡不安，军方要不断的以军事政变来推翻民选政府，已经对其经济发展带来很大困扰，因此泰国对美军的态度甚至比新加坡还要温和，但就象大部分东南亚国家一样，虽然不介意美军的出现，但主要目的是盯着经济上的好处，即美军支付的费用和军援带来的经济上的好处，但不会让美国干扰自己的区域政策，尤其是不能允许影响他们和中国的经济贸易关系。

当然，东南亚各国有意通过美军的存在而让自己在南沙群岛的油气资源和渔业资源利用上底气更硬。为了防止中国和东南亚的关系因为美国的介入而恶化，影响中国在该区域的政治、经济和战略利益，中国在南海的策略应当是不排除和东南亚各国就资源问题上实行共同开发的可能，只是在战略利益上寸土不让，保证中国海军在这个地区实行主权，对马六甲海峡进行影响。

中国把握南海地区，同时有利于中国和澳大利亚的原材料运输线的安全，但可能会受到美国的阻拦。南海风云变幻，未来将不会风平浪静。[fn:jdwtdgyx0777]

[fn:jdwtdgyx0777] 2009年3月，南海发生美军舰只与中方船只的对峙，东南亚部分国家如菲律宾和马来西亚集中对南海上一些岛屿进行强硬的动作，印证了作者的判断。——编者注。

如果中国大陆和台湾在资源开发上能够达成协议，两岸在南沙的驻军可以互相配合，将有利于中国建立以海南和广东湛江为基地的前进基地，加上中国在柬埔寨的影响，可以为保障南海和平起重要作用。目前海峡两岸在台湾海峡的能源开发上已经开始协商。在南海事务上的同声同气，应该在不远的将来能够实现。[fn:jdwtdgyx0778]

[fn:jdwtdgyx0778] 在本文写完后3个月，2008年10月，大陆和台湾开始商谈海上能源开发合作项目。——编者注。


+ 六十三

在东南亚的北部，中国最有利的作法是通过大湄公河六国合作，以中国三省区——贵州、云南和广西与东南亚各国在民族、文化和习惯上的一致性，建立起一个互利互惠的统一市场。通过发展中国西南、越南北部、老挝、柬埔寨和缅甸，加上相对富裕的泰国，形成一个繁荣的共同经济区，从而抵消美国在泰国的影响，也使美国通过颠覆缅甸现政府而登陆南亚进而建立印度洋霸权的企图不易施行。通过这一地区交通基础建设的修缮，中国在情势需要的时候，如这些国家遭到侵略或重大自然灾害之时，可以派出军队快速的通过高速公路从昆明直到金边，而为这个经济区域提供保护。

图7.4 中国在东南亚的可行建设规划（虚线表示现在的航路，实线为未来建成的路网）

由于美国在这些区域不可能投放军队，所以对中国战略的牵制主要表现在支持其操控的环保组织对中国的投资行为进行攻击。比如说，在新中国建立之初，由于美国为首的西方国家对中国禁运，中国不得不在云南南部和海南岛种植橡树，以保证自己的橡胶供应。现在可以预料，这个区域的老挝和柬埔寨也将成为中国橡胶的一个重要产地。但这类投资建设行为，必然遭受西方操控的环保组织的攻击。这些组织将通过指责中国摧毁原始森林和灭绝原生态文化来干扰这个地区的经济一体化。

在东南亚的南部，中国应该和当地华人如马来西亚的“传统华人”（与西化华人相对应的那种仍然心怀祖国的华人）合作，积极利用他们的经济影响力，通过与这些国家进行经贸合作而建立利益共同体。中国在这些经济活动中是有利可图的，因此当然要比美国在此地纯粹烧钱的军力炫耀更具有持久性。而一旦美国动用军力来打击中国在此地的经济利益，就会首先损害这些国家自己的经济利益，那么这些国家，也会像以前的菲律宾一样，把美军从国土上踢出去。
 
图7.4 中国可规划的从昆明经湄公河沿线到柬埔寨金边的路线尚待开发 图为老挝-柬埔寨边界

中国一方面可以宣称自己并不挑战美国在亚太区的霸权，不强迫东南亚国家在中国和美国之间必须择一而伴。另一方面要大力提倡以区域合作为优先的双边和多边贸易，绕过由美国和西方操控的国际贸易组织（WTO）。例如建立大湄公河六国合作（中缅泰老柬越）、东盟+1（中国）、 东盟+3（中日韩）、东盟+5（中日韩再加澳洲和新西兰）等等组织，以地区性经贸合作，替代因为美国和欧洲不愿取消农产品补贴而造成的僵持的WTO多哈回合死局。中国同时可以加入和倡导地区性的金融组织，如亚洲发展银行、美洲发展银行和非洲发展银行等等，不需要太多参与美国主控的世界银行和国际货币基金组织。[fn:jdwtdgyx0779]

[fn:jdwtdgyx0779] 在该文写作时，西方仍然把持着世界银行和国际货币基金会，在金融危机下，到2009年初的G20财长峰会，似乎有向发展中国家部分让权的趋势，最后博弈结果如何，仍然要看局势发展。——作者补注。

中国可以用这个方式继续东亚市场的一体化、区域集团化，并在必要情况下，通过地区性的金融合作，防止出现类似于1997年那样由西方金融资本发起的掠夺亚洲国家的金融危机。依靠中国、日本和其他亚洲国家的巨额现金储备，建立统一基金，可以保证本区域内任何国家的经济和货币体系在危急关头不会崩溃并影响整个区域经济。在军事层面上，中国可以倡导双边的军事合作，增加中国和东南亚国家在救灾、反恐和海洋执法上的共同演习。当然，在目前情况下，中国没有必要刺激美国，但在将来，中国应该逐渐增加海军舰艇的出海，与泰国和柬埔寨在泰国湾，与缅甸、孟加拉国甚至印度在印度洋，和伊朗、巴基斯坦在波斯湾举行演习。

只要中国采取以经济拉拢抗衡美国军事炫耀的做法，从长远来看，总有一天，东南亚就会师法非洲（拒绝美国在其土地上建立非洲战区司令部），要求美国不要再在其领土上驻军。


+ 六十四

日本当初自甘美国跟班，鼓吹组建东方北约时，其实有其自己的小算盘。日本的困境在于虽然经济目前在世界上排行第二，又是一个人口大国，但地理条件极差。换了世界任何一个地方，日本都会是当仁不让的世界级大国。但是可叹的是，日本运气太差，被夹在美国和中国两大强权中间，其外交政策不可避免的必须在东西走向上摇摆。当然，现在日本国内的主流意见是，日本应该以日美安保条约为首要依靠，但又要同时加深和中国在政治、经济和军事上的联系，避免在可能的中美冲突中变成炮灰。日本在这个平衡中，目前还是以偏美为主，但必须有未来随时调整位置的弹性。有趣的一个现象是，当日本在亲美的小泉治下，中日政治关系降到冰点时，日本的极右派势力倒是想到要建立一个庞大的基金，专门资助中国的中学生到日本短期学习和日本的中学生到中国短期学习。而且还计划安排让这些中学生住到对方国家的家庭里，以增进对对方的好感。这是因为历来反中的极右势力担忧，如果不这样做的话，任由双方关系恶化，导致下一代互相讨厌，一旦将来出现必须和中国亲善才能维护日本利益的情况，会没有转向所需要的人心基础。

日本的另一个算盘是，如果日本以一个海洋国家的领头羊身份，能够进行南下战略（因为北边是麻烦的俄罗斯），拉上印尼、澳洲和印度，而撮合成自己领导的一个“民主同盟”，就可以同中国抗衡。而由于美国在亚洲从来都不搞群体同盟，只允许和单独国家一对一的建立以美主导的双边军事协定，日本就可以利用这个机会，建立起和澳洲、印度等的军事合作。这样，虽然名义上还是在美国领导下，但日本在实际上已经组织了一个独立集团。如果将来美国势力衰退，就可以集集团数国之力，在日本的领导下，和美国讨价还价。

当然这个想法最后是南柯一梦。一个原因是印度从来都是三心二意，另一个原因是中国成功的看准了澳洲这个东方北约中最弱的一环。因为澳洲在经济上对中国依赖很大，又是一个规模小的经济体，所以比较难以应付中国的经济惩罚。果然，在以“知中派”陆克文上台后，澳洲已经宣布退出针对中国的任何军事同盟，并开始检讨美澳军事条约，防止澳洲被条约拖入未来可能的美国和中国的冲突。

这两个变化基本上把快要建成的亚洲北约又打回日美两国的安保条约的原型。而后福田在日本上台，更是使这个主要由小泉和美国副总统切尼运作的计划失败。福田，被极右派攻击为“中国狗”，应该算是陆克文一类的所谓“知中派”。虽然他们不是亲中派，但至少在考虑其本国利益时，不会陷入无理性的反中怪圈，而会在中美之间做一个中间性的选择。

其实如果了解中国历史的话，每当中原王朝强大的时候，周边政权中的亲中原派就通常会上台。如果看一下从日本、澳洲，到台湾的选举结果，可以看到同一个趋势。这其中唯一的变数就是韩国的选举，新总统李明博试图改变前任卢武铉靠近中国疏远美国，在朝鲜问题上和中国共同进退的政策。李明博上台后，首先是放弃在朝鲜问题上与中国的共识，而采取更接近美国的立场，使朝韩关系异常紧张，然后又积极推动韩国和美国的双边自由贸易协定以显示对美友好，不料因为韩国民众对美国牛肉进口的强烈反弹，导致新政府刚组阁就面临倒阁危机。


+ 六十五

韩国人的问题在于他们的情况比日本人还要惨。经过几代人的艰苦努力，小小的韩国好歹也算是世界上的十来号经济体，换个其他地方也是人中龙凤，可惜身在东北亚，除了可以蔑视一下自己的北方同胞兄弟朝鲜外，在美国、中国、日本和俄罗斯的环视下，只感到一种危在旦夕的惶恐。

本来在历史上，朝鲜人是没有这种感觉的。他们以大中华文化的一员而自豪，身为这个令人自信的文明中的一分子，还可以俯视汉化得还不够彻底的日本人。朝鲜人从来都自豪的把自己算作广义中国的一部分，尤其是在明代，作为一个文化和政治上的附属国，自称为小中华，并对他们眼中的野蛮人满族鄙夷之至。明亡清兴，朝鲜民间则有“三百年来中国土，如何付予老单于”的传说来对抗新兴的清朝。虽然这只是个传言，但朝鲜人民在臣服清朝之后，仍然偷偷的拜祭明朝皇帝数百年，却是个不争的历史事实。即使在前几年，韩国一位驻美外交官曾在接受中文电视访谈时，用流利的普通话说道，能够真正明白唐诗宋词的底蕴的，除了中国人之外，全世界只有朝鲜人。当然不排除他是为了讨好中文观众，同时文化上低视日本才这样说，但他确实谈到了一个事实，即朝鲜人是真正的中国文化的一分子，而且二战后韩国的经济有此长足的进步，也是主要得益于儒家文化的精髓。

在清楚了解这些情况后，中国人不应该对韩国人有一种文化上的沙文主义态度，而应该坦然的承认在历史上他们的祖先对中华和东方文明的贡献。比如说将宋代毕升的泥字活字印刷，改良为铜字印刷，再传回中土，对知识的传播和教育的普及起了很大的作用。

自然，在西方强权打开东方封闭和保守的大门后，朝鲜的儒家老朽和他们同样心态的天朝官员，就不得不经历一次炼狱的苦难挣扎，在传统和现代之间久久找不到出路。反而倒是尚处于儒家文明初中级阶段的日本，通过又一次成功的文化学习，吸收西方知识再次转型，变成了一个侵略邻居的强权。于是在衰老的保守派和急进的东学党的内争与日本在甲午战争中击败清朝的外患中，朝鲜从一个在中国体系内自治的附属国变成了日本直接管理的殖民地。

日本战败后，朝鲜又在东西方意识形态，文化和地缘政治的冲突下，被一分为二。只是在五六十年代日本成功将儒家文化现代化而在战后废墟上重生，造就经济起飞之后，韩国，与其他中华文明的小兄弟台湾、新加坡和香港一起，在七十年代造就了亚洲的另一个经济奇迹，终于可以扬眉吐气的做人一次。应该让所有同情朝鲜这个多灾多难的民族的世人向其祝贺。

但是韩国今天面临的挑战也相当巨大。其中一个最主要问题是如何改善与朝鲜的关系，使朝鲜半岛不再成为世界强权的逐鹿之地。这就要求韩国必须和中国找到共识，寻找如何舒缓东北亚的紧张关系，逐步排除美国这个区域外因素，帮助朝鲜的政治和经济转型，为将来有可能的朝韩合作，甚至更远期的统一打下基础。在当前的形势下，应该避免谈统一问题。以目前的韩国经济能力，根本无力消化朝鲜的人口去实现德国那样的统一。而且朝鲜半岛是否能够统一，又关乎周边中国、日本、俄罗斯和美国的利益，不是简单的可以由朝鲜或韩国自己想决定就可以决定的。


+ 六十六

韩国李明博政府的一大失误在于主动冷却和朝鲜的关系，从独立自主的阳光政策上退步，而将韩国的对朝政策与美国政策挂钩，以朝鲜满足美国的要求作为韩国对朝政策的先决条件。而在这个过程中，又疏远了中国，并放弃在朝鲜问题上和中国达成的共识，影响了中韩关系。

这个政策的结果，首先就是与朝鲜产生了一些无聊的骂战，甚至双方的军事将领都谈到要对对方狂轰滥炸，给一点颜色看看。这就造成和朝鲜之间不必要的紧张。正在韩国为美国对朝鲜的政策做摇旗呐喊的时候，朝鲜炸毁宁边冷却塔，美国对朝政策来了一个180度急转弯，宣称要实现朝美关系正常化并把朝鲜从恐怖国家黑名单上除名。于是这结果就是韩国和他的难兄难弟日本一样，被美国撇在一边，晾起来晒了。韩国政府的尴尬场面可想而知。

本来，美国和朝鲜之间的轻手重脚，在很大程度上由美国和中国的全球利益博弈来决定。李明博的行为，既不能左右情况的发展，又不能施加决定性的影响力，自己主动去踩这趟浑水，绝对是自找苦吃。	

美国在朝鲜的政策上，在新保守派主持大政时期，曾由本书前面屡屡提到的超级鹰派、前美国驻联合国大使博尔顿完全掌控。此人尤其好战，攻击一切对朝和解计划，并攻击现在的国务院务实派副国务卿希尔（Hill）为金正希（Kim Jong Hill）[fn:jdwtdgyx0780]。按照强硬派的设计，反正美国不敢对朝鲜动武，最好的办法是通过经济上的金融战，把朝鲜经济整垮，造成朝鲜崩溃，让几百万甚至千万难民涌入中国东北，使东北因为重工业改造已经存在大量下岗工人的脆弱经济进行冲击，从而将整个中国经济发展拖下水。一旦发生这种情况，美国就有望以联合国维和部队的名义，把大腿伸进朝鲜。

[fn:jdwtdgyx0780] 朝鲜领导人金正日英文拼写为Kim Jong Il，博尔顿取音似臆造讽刺性名字Kim Jong Hill来攻击政敌。

在美国的这个经济金融战谋划中，韩国当然要担当重要的中介角色，即在必要的时候去管理混乱的朝鲜。当然韩国的一些学者也看出了这里面的情况的复杂。曾有一位在韩国大学任教的俄罗斯籍的朝鲜半岛专家提议让中国来全权处理朝鲜事务（估计没有哪个韩国学者敢冒被国人劈砖的危险提这样的建议），韩国应该明哲保身，不要被人上套。[fn:jdwtdgyx0781]

[fn:jdwtdgyx0781] 俄罗斯籍首尔大学副教授、朝鲜史专家兰科夫（Andrei Lankov）在《亚洲时报》2008年2月撰文。这个观点后来被日本人热炒，引发韩国人不满。

美国对朝鲜的经济战，基本上就是由今天对伊朗进行经济战的同一帮人掌控，用的也是差不多的手法。首先是栽赃朝鲜偷印美元，然后以此为借口把朝鲜在世界各地的金融关系斩断，以打击朝鲜经济的生命线——黄金出口（正如打击伊朗生命线石油出口一样）。

具体操作是打击澳门的一家小银行汇业银行（该行一年为朝鲜向香港国际金市出售价值1亿5千万的黄金），冻结朝鲜的2500万美元存款账户，用美国财政部的经济制裁让这家银行破产。其目的正如财政部经济战的负责人阿舍尔（David Asher）在国会作证时所说，是一个杀鸡给猴看，以此来威胁大银行如中国银行切断和朝鲜的经济联系，达到美国经济封锁朝鲜的目的。[fn:jdwtdgyx0782]

[fn:jdwtdgyx0782] 阿舍尔在2007年4月的国会听证会上称：汇业银行是个象征性目标。我们是要杀鸡给猴看，猴子就是那些在和朝鲜做生意的中国几个大银行。对于这种说法，美国国会议员质问，我们搞到最后把鸡还回去了，猴子是否吓到了呢？

在美元伪钞的报道上，基本上美国所有的媒体都参与了造谣。[fn:jdwtdgyx0783]其实美元假钞中最出名的“超级百元票”最先在九十年代现身中东，当时美国财政部根据时局的需要，一会儿指责黎巴嫩真主党，一会儿又说叙利亚，一会儿又“发现”伊朗是伪钞的制造者。而按照美国法律，制造美元伪币就是向美国宣战，美军就可以杀进去。

[fn:jdwtdgyx0783] 如纽约时报2006年关于朝鲜伪钞时间的系列报道，完全引用美国财政部的说辞，缺乏独立的调查态度。


+ 六十七

当时确实是有朝鲜的外交官带着美元伪钞而被抓。专家的估计是，一个可能是朝鲜在向中东国家偷偷出售导弹时，误收了假美元作为付款。另一个可能就是朝鲜政府想用歪路赚钱，用半价买入假美元，希望能够兑换真的回来获得暴利。但是据2006年美国国会一个引用韩国情报部门资料的研究报告，在美国1996年重新设计了美元使得更加难以伪造后，再没有证据表明朝鲜参与伪钞的买卖活动。

根据欧洲专家的意见，超级百元的印刷水平比真正美元还要高超，但是似乎就故意留下的一些记号让美国国内验钞机可以轻易的辨明真假，从而好像要保证美国自己的金融系统不受冲击。而海外流通的美元则占总美元的三分之二，许多国家并不能用美国专用的验钞机。而据西方的印钞专家估计，能够印刷这样高水准的印钞机只有瑞士的专门公司出产，单机成本就超过5000万美元，还不包括墨水、印钞纸等等。而由于朝鲜贫穷，上一次买旧机器的款项还没有付清，瑞士根本连旧机器的零件都没有给。目前朝鲜货币还是请中国帮忙印刷的，似乎没有这种技术能力可以印如此高水准的假钞。

图7.6  指控朝鲜伪造的“超级伪钞”让人怀疑的四个外表特征：1 防伪线用的是真钞相同的防伪线；2 在人像的衣领上有1/42000英寸大的字样“USA 100”或“The United States of America”；3 水印从背面可以看到；4 纸张就是真钞纸——纸张中有彩色微纤

另外就是总的超级百元假钞只有区区5000万，真是连买机器的成本都不够，因为你还要半价批发给黑社会的零售商。所以说，这个对朝鲜的指控在伪钞专家眼里只是个笑话。而最有趣的是，在新的钞票印刷技术上，有一个变色处理方法，比如说美元在变换光线的角度时，就会从绿色变成黄色。这种变色墨水由瑞士的斯克帕（SICPA）公司专门出品，基本上是世界各国的中央银行为本国选择两种变色以供专用。如果朝鲜要印美元假钞的话，就必须购买美国的变色墨（而这是完全不可能），或者自己研发出来仿制方法。但是，最能辨别真假的是斯克帕公司的专家，而且他们不仅能够根据墨水知道是否是真货，还可以知道是那个地方卖出的墨水。可是，这家公司拒绝出席由美国财政部和国务院主持的“朝鲜伪造假钞全球座谈会”（韩国和国际刑警也选择了缺席），并对德国记者的采访表示，因为美国印钞局是该公司的最大客户，所以他们不会对此事发表评论。

另一个数字就是，美国传统基金会的学者们估算出朝鲜在10年内每年伪造了2亿5000万的美元假钞，这一消息并在美国各媒体引起巨大反响，然而专业的美国联储局的数据大概被人遗忘了——联储局的结论是过去十年平均每年发现的伪钞为4千万，而任何美元流通，在第三和第四手时，就会由美国联储局下的一家分行接触到，不可能有每年新造出超过2亿的伪钞在外面流通而不被发觉。

所以说，欧洲的犯罪专家基本断定这些伪钞是美国自己印刷的，而且根据印刷机的记号，应该是由华盛顿特区以北的那家中情局控制的印钞厂出品。他们的推断是中情局在进行秘密活动时，通常为了绕过美国国会的监督，自己印钱解决，把超级伪钞给释放出去。

本来瑞士不想在这个问题上发表意见，但是后来美国财政部拿出布什总统的特别行政命令，要求其银行和美国合作，对付伊朗的金融活动。如果瑞士不合作的话，美国不排除中情局援用美国反恐怖法，利用黑客闯入瑞士银行系统，在其电脑记录里擦掉可疑“恐怖分子“（指所有伊朗账户）账户上的所有金钱。瑞士政府忍无可忍，由其警察部门公布调查结果，指出美国对朝鲜伪造美元的指控是谎言，为欧洲金融界抗拒美国在伊朗的金融战中步步紧逼提供炮弹。

    （编者按：对朝鲜制造伪钞一事，请参考附录。）

六十八

美国对朝鲜的金融战由于中国的不合作，最终失败。虽然当时的美国新保守派想向中国银行等开刀，但是由于中国银行控制了上千亿美元的美国各实体的债券，如果招惹导致抛售行为，肯定会对世界经济和金融产生巨大冲击。所以这个方案一报上去，就被布什否决了。最终的结果就是以朝鲜试验了一个小小原子弹而告终。由于考虑到朝鲜的核技术非常可能流入中东如叙利亚等国84，美国不得不听从中国的劝告，放下身段和朝鲜谈判。

中国则对朝鲜将事态无限扩大而不满，因为一个稳定的朝鲜半岛合乎所有周边国家的利益。在中国给予朝鲜和美国双方压力后，以中国主导的六方会谈终于成型，并在进两步、退一步的艰难过程中，取得了成果。当然这过程之中美国强硬派试图令谈判破裂，但最终并未成功。

其间有一幕颇具有戏剧性。那就是虽然美国答应让朝鲜拿回冻结的2500万美元的存款，但却不肯解除对澳门汇业银行的制裁。因为当时伊朗的资金已经从欧洲移到香港和上海等地，美国希望能继续把这种对银行的恐吓手段用于针对伊朗的金融战。结果就是世界上所有的银行都拒绝接受这列在美国黑名单上的澳门汇业银行的资金转账，而朝鲜一天拿不到钱，就一天坚持指责美国没有诚意，不肯回到谈判桌，这使朝核六方会谈迟迟不能进行。中国因为不满美国以切尼为祸首的搅局派的行为，并质疑美国国务院赖斯是否真正对美国外交政策具有操控权，所以让中国银行对此事完全袖手旁观，就是让六方会谈这样拖下去开不了局。结果是韩国和俄罗斯按耐不住这迟迟不开的和谈，都想用一些办法解套，比如韩国建议通过由其政府控制的韩国进出口银行来转帐，俄罗斯建议由俄罗斯中央银行出面做转账，但前提要求美国财政部必须豁免这种转帐流程带来的与“恐怖犯罪分子”“交易”的“罪行”。可是美国财政部也没有办法发出豁免令，因为美国新保守派可以动用国会，以美国国内的反恐法为依据，把事情扯进美国法院，从而捆绑住美国行政部门如财政部的外交决策权。问题拖到最后，还是由美国财长保尔森直接迫使布什放话，由美国联储局出面，将钱转入美国联储局纽约分行，再通过俄罗斯的银行转入朝鲜，这样一来最起码“犯法”的是美国中央银行，财政部也不会去“执法”制约美国自己的央行。

其实美国对一个国家的经济制裁，本来目的是要使人家经济周转不灵，遭受损失，小日子难过。但以伊朗和委内瑞拉为例，因为担忧美国经济制裁，所以早早的在2005年就把所有的美元换成欧元和人民币，结果在美国开始制裁伊朗之后，他们在兑换率上已经赚了近30%，在加上国际石油价格因为制裁的原因只会向上涨，他们的小日子越过越红火，就算是交易成本因为制裁增加了10%，也已不是什么大事，真不知这样的制裁有什么用。

日本在六方会谈上的大错就是帮美国大声摇旗呐喊。本来日本和朝鲜并没有真正的利益冲突，朝鲜也并不真正对日本造成军事上的威胁。但为了配合美国的步伐，日本通过媒体狂炒朝鲜绑架日本人质的陈年老案，并把这个事情的解决作为停止对朝鲜经济制裁的一个先决条件。可是大伙尤其是美国的最大关注点是朝鲜向中东扩散核技术的问题，对日本这件小事，都不会认真看待。结果就是美国这辆大车一转弯，日本就被甩出去了。但是这个要求已经被摆上了台，没有退路，国内舆论和民意也不好交代，继续维持单方面对朝鲜制裁不光无效，还被其他国家看作不合时宜的搅局。怎么办？如果去找朝鲜交涉，朝鲜得势不饶人，又没有什么痛脚可以被日本捏，估计又会开出些新条件让日本难堪，或者不加理睬还放些难听的话出来，比如“你的主子国美国已经和我谈妥了，你日本州又跑来吵吵嚷嚷干什么？”日本唯一的出路，还是求中国帮忙，让朝鲜做些姿态出来，给日本政府一个台阶下。

估计日本政府在和中国的高峰会中，如胡锦涛访日、G8峰会、以及奥运会，如何帮助日本解套，使日本人在被美国挂起来晒（Hang and Dry）之后，能够全身而退，是个主要考虑。而和美国的会谈中，估计也要向美国抱怨几句，而美国就会以布什总统招牌的傻笑搪塞过去。


六十九

所以在这个所有明眼人都心知肚明但却十分微妙的情形下，刚爬上座位的李明博跑来撞枪口和朝鲜中国对着干，真是找死，而且会死得很难看。本来，韩国的经济能够从亚洲金融危机中走出来，完全依赖于与中国的经济日益密切的交往。本来可选的一个聪明的做法是，复兴韩国自身的中华文化传统，重新普及汉字，利用同文同种的优势，象香港、台湾和新加坡一样，在中国经济中抢占先机，不要挑起无聊的文化、历史和领土争执，比如高句丽古文化归属，吉林延边长白山领土这些已经不是问题的问题，应当善于利用中国社会里仍然遗留的反日情绪，在和日本、美国、欧洲争夺中国市场份额上，抢个头彩。反观日本，从来就不会在文化问题上同中国争吵，而是实实在在的承认日本文化的70%来源于中国文化。其实在明治维新后，日本知识界用汉字为基础，引进的西方新思想造出来的新汉字词汇，如“民主”等，都几乎全部被中国接受，如果日本有韩国那样心态的话，恐怕虚荣心要膨胀到九霄云外了。

韩国本来靠包装华丽但却缺乏内涵的泡沫电视剧为其产品的销售打开了一个不错的局面。这些电视剧在低级趣味的粗俗文化里，创造了成功的商业文化市场，为整个韩国产品系列起到很好的推销作用。为什么韩国的电视剧在内涵上一般，但商业上却很成功呢？因为这些电视剧的故事完全满足了生活无聊的中产阶级家庭主妇的意淫梦，而这些主妇（香港人所谓师奶）又是消费品市场的主要生力军。韩国泡沫剧的故事梗概千篇一律，基本可以概括成一个楚楚可怜的灰姑娘如何把韩国仅有的几位大财阀的继承人之一，收倒在石榴裙下的故事。这些又富有，又长得帅，又聪明，又有同情心的王子们，完全不像真实世界里的此等人类，忙着做潇洒的花花公子，在二流明星、模特和选美小姐之间左拥右抱，反而要对灰姑娘一片真情，不弃不舍，几棒子都打不走。当然一般还要加上一个宝钗之类的表妹情敌出来挖陷阱，下绊马索。再加一个对灰姑娘死心塌地的大傻冒，一旦剧情需要她眼瞎耳聋，身上到处长癌症的时候，这个大傻冒立即变身灰姑娘的人体器官备用库，就可以很煽情的升天，然后把他的眼角膜啊，肝啊，肾啊为她做器官移植。

与韩国泡沫剧相比，中国的俗文化中确实缺乏为女性量身定做的意淫故事，但有不少为男人而编的自慰戏。比如说黄梅戏中的女驸马和天仙配都是此类。“私定终身后花园，落难公子中状元”是当然的老套。但是你个破书生，不光有个美如天仙的富家小姐喜欢，还可以帮你做高考枪手，射个状元冠军回来，也许顺带还帮你娶个公主当二奶，你说爽不爽。天仙配里无德无才兼无能的董永，混到要卖身做三年长工，居然有个真正的天仙妹妹死活要嫁他，小仙术一施，三年变三天，真是令天下没有出息的男人们梦中都要流出口水来。现代金庸笔下的韦小宝也是桃花遍地，不管你是姑姑、姨姨、姐姐、妹妹、小泼皮是老少咸宜，大小通吃，难怪中国男人个个对其着迷，要少学韦小子，老学杨大倌。

可惜的是韩国人搞出一堆泡沫剧，却不知道自己到底在文化上应该怎样定位，成日家弄些让人笑破肚皮的新考古发现。在科技上，韩国更是夹在中国和日本之间。据韩国东亚发展中心的报告，中国的科技能力已经是韩国的95%，在近年内应该会超过韩国，使东亚科技日韩中的格局变成日中韩，届时估计会对韩国的经济在中国的市场份额产生重大影响。


七十

这大概就是韩国对中国恐惧的最大因素，也是韩国人对中国人态度由好转坏的主要原因。对中国经济的绝对依赖，加上对未来缺乏信心，使韩国新政府企图靠疏远中国，亲近美国令其经济多样化。而李明博政府的韩美自由贸易协定，就是这个步骤的一个主攻方向。但可惜的是，美国经济日渐陷入衰退，不一定会为韩国的出口贸易带来短期的效果，而且为达到这个目的，韩国首先要根据协定开放自己的农产品市场，令美国牛肉可以无阻拦的横扫韩国，这就触怒了农业利益，导致为保护农民而兴起的大规模抗议活动。
 
图7.6 左：韩国牛肉抗议；右：日本库存大米并于2008年运出援助菲律宾

相比之下，日本虽然也不得不进口美国稻米，但在保护本国农民的事情上，处理得就比较好。日本基本上是买了美国米后就堆放在仓库里变质，从而防止美国米冲击自己的稻米生产。这些米过几年后，就贱价卖给农民当饲料，算是皆大欢喜。08年上半年美国的对冲基金把米价炒上了天（也不能怪他们，股市和楼市都被炒焦了，只能在石油和商品市场上拼死赌一把），大多数原本出米国又粮食收成不佳，限制大米出口保护本国粮食安全，结果许多像菲律宾等大米进口国85只能干瞪眼，无米可买。最后还是日本征得了美国政府的同意，把准备放烂的米拿些出来为菲律宾救急。日本的唯唯诺诺在这件大米的事情上也可以看出来，它不能将这些米卖回国际粮食市场而影响国际稻米价格，除非美国同意，例如这次就只是直接对菲救急而不经过国际市场买卖，目的是为了保护美国的大米出口商。

本来，李明博的74786和他的效法者马英九的62387都是拿来忽悠老百姓的。如果李明博想把韩国变成世界第七大经济体，就需要将现有GDP从接近1万亿美元翻一番到多于2万亿美元，将现有人均GDP从二万多美元增加到四万，才可以与加拿大、意大利和法国等一争长短。这本来就不是一件容易的事。加拿大得益于世界石油和商品价格的飞涨。意大利和法国有很多高利润的产品如军火等，这是韩国不可能涉足的。另外外部销售市场也对韩国不利，欧洲市场的一体化为意大利和法国的高档消费品保证了市场，北美贸易协定也使加拿大在美国市场上有很大的便利。而韩国没有能保证自己份额的巨大市场，在高科技上又要和日本、中国、台湾和新加坡竞争，在国际经济高涨的时候，也许还可以有些机会，但遇上目前美国和欧洲面临衰退，亚洲经济放缓的情况下，还想要放大卫星，在未来的5年内有所作为，好像有些痴人说梦。

况且在他竞选的时候，美国次贷危机已经爆发，以中国经济过去几年12%的年增长率，都已经要把预测下调到9%。韩国近几年的经济增长尚大致在4-5%之间，想要在世界经济困局中一花独放，往上跳2-3个百分点，似乎有点人有多大胆，地有多大产的味道。当初，韩国陷入亚洲金融危机，还主要是大财团过度负债，尚有集中调整的可能。但之后几年经济改革改出来的反弹，却让韩国出现了全民负债、不动产泡沫等日美泡沫经济中出现过的危险情况。现在的政府不实事求是的面对困境，而是为了民主选举蒙骗人民，乱开支票，怕的是不光那个大跃进的747飞机上不了天，搞不好来个经济崩溃都不出奇。一旦韩国的楼市开爆，情况就会一发而不可收拾。

回过头来看一下日本的例子，自从1990年开始，日本在经济萧条上徘徊近二十年。不过日本在科技上仍然具有领先优势，因此和中国的经济互补性很好。如果能同中国齐心而力，在发展新能源和节能技术上支持中国，它的经济复苏就可以和中国经济的下一步发展挂钩，使日本的经济在5-6年后走出萧条。






































【写作日期】2008年7月16日——23日            























*** 【第八篇·稳定】


梧桐不禁三更雨，起坐寒星一缕烟。
--自题

七十一

谈到中日关系，必须从一个世界性的大局去看问题。日本作为一个经济和技术大国，有利于打破世界的经济和技术由欧美垄断的局面，对中国是一个有益的因素。但日本作为政治和军事上的美国殖民地，则对中国有害。在中国崛起的过程中，日本可以扮演很重要的一个角色，如果日本采取亲华政策，则对中国崛起是一个助力，反之，如果日本采取仇华政策，则对中国崛起是一个阻力。当中国的发展迫使世界政治、经济和文化中心转移到东亚，日本文化，作为中华文明的一个分支，会帮助中华文明，在同西方文明争夺形象力上起良好作用。

站在日本本身的角度看，在这个世界性的大变革中，如何有效的保障自己的国家利益，在中美两大超强中平衡关系，不是一个容易解决的问题。比如说，日本希望加入联合国安理会，成为一个没有否决权的常任理事国，为其国家正常化迈出重要一步。但问题是，如果日本的立场完全亲美，中国就肯定会否决这个提议。而如果日本的立场亲中，美国又不会让其入局。

所以对日本当政者而言，一个最好的选择是，目前尽力发展和中国的经贸关系，在给予中国技术和投资上支持的同时，也享受中国经济发展带来的好处。但是在军事和安全层面上，则继续依靠日美安保条约，对中国军力的增长持提防的心态。等待过一阵时间，在安全得到保障之后，就必须加快和中国的军事交流和合作，使中日和平可以有一个更坚实的基础。而当中日合作深化到日本真正成为中国的合作伙伴，日本对中国增长的军事实力不再恐惧的时候，日本就可以取消日美安保条约，把美军从东北亚赶出去。

所以中国在对日政策上，必须着重三点。一是经济上更紧密的合作，二是军事上加深交流和互信，三是政治上定期的高层互访。至于在民间情绪上，中国人可能还需要一些时日，才可以从历史的阴影中走出来，开始真正的感受到作为大国国民的自豪。对日本的一些右翼分子的行为，不需要有过激的反应。这一点，中国人需要像美国学习，美国人对日本教科书上对珍珠港的处理，完全不予理会。对美国人而言，实力决定一切，如果你日本人觉得可以向美国叫板的话，顶多我再扔几颗原子弹而已。

对日本而言，过去以有限的人口和资源，与大国抗衡，靠得是全民族狂热的团结和牺牲精神，但是在核武器出现之后，这一套就完全无用。在当今的世界上，恐怕只有中国、美国和俄罗斯具有足够辽阔的国土，可以经受住一场核战争。像日本、英国等之类岛国，则根本没有胜算，一次核战争之后整个国家和民族都不再存在，所以没有资格和别人再找架打，只能靠维持足够的阻吓能力来增加敌人的成本。再加上战后日本在美国的统治下，人民享受到了非战的好处，军国主义想在日本复活是难于上青天。

除了在国际上如何伺候两强让人头痛以外，日本面对的另外一个问题是人口老化和人口减少。由于东方人的生活和饮食习惯，日本是一个长寿社会。在加上发达国家养育孩子费用昂贵，人们普遍不愿生孩子。另外在现代社会，如果男女较为平等，如北欧和北美，因为丈夫比较愿意帮忙做家务，妻子会比较愿意生孩子。而如果歧视女性比较严重，如日本和意大利，女人通常不会愿意生孩子来增加自己的负担。在这种人力资源日益稀缺的情况下，一个国家通常不会好战，而希望有一种安宁的生活。


七十二

根据人口学研究，当一个社会平均年龄低，每个家庭的生育率在3-5胎时，因为年轻人多，社会结构不稳定，国家通常比较好战，每个家庭也比较容易接受家里有一两个孩子为国捐躯。相反，对日本和中国而言，其低生育率导致的社会结构都会使得人民越来越希望和平。日本的人口减少使其不能承受大的战争带来的人口损害，而其补充劳动力，输入海外移民的首选，又是来自中国上海等地的留学生。在这种情势下，如果有人还在宣传日本威胁论和日本军国主义复活论，大概没有多少事实基础。

而中国因为计划生育带来的独生子女问题，也不会轻易和别人动刀动枪，本来能够不用战争解决的问题不要用人命去换，从来都是中国历史上的思想家如写孙子兵法的孙武大力提倡的。战争只能作为最后的一种无奈的选择，往往代价巨大所得甚微，正如美国在伊拉克的战争，到现在还是损失惨重，看不出结束的一天。中国在历史上长期占据世界经济第一的位置，不是靠战争得来的，而日本今天的经济强国地位也不是靠战争获得。所以中国和日本之间，完全有能力避免一场对大家都没有好处的战争。中日间的任何冲突，都会损害双方的利益，而推迟世界中心向亚洲区的转移。任何中日摩擦和对抗，直接得益者都会是美国和欧洲，因此每当中日关系有所发展的话，你就会听到不少撩是斗非的声音，攻击中国政府。而这些声音中不少来自海外，你必须知道他们的资金来源于何处，才可以对他们的意图进行分析。通常很多海外的反中国政府势力，在美国和欧洲的财政支持下，会进行针对中国政府的舆论和行动。当这些行动和舆论产生危害时，中国政府不得不对美国和欧洲做出妥协，在关键利益如中东和北非上作出让步，而这些西方的帮手，又会转过头来指责中国政府出卖国家的利益，让中国政府两头不是人。

08年的中日东海协议就是这样一个例子。中国在历史上，处理这个问题的一个最大的失误，就是在二次世界大战结束时没有要求归还琉球的主权。当年琉球被日本强占后，被美国总统威尔逊在一战后重新划定世界边界时仲裁给了日本，而清政府或北洋政府都从来没有承认。二战结束前，罗斯福总统曾两次向蒋介石提出归还琉球主权，都被婉拒。当然，以那时国民政府的施政水平，连台湾人民都要被逼出来个228，所以就算琉球人民对日本军国主义深恶痛绝选择回归中国，国民政府也不一定有能力管好。如果琉球主权没有归属日本，那么日本不光在东海，连在钓鱼台上都没有资格和中国谈判。但将琉球主权收回在今天已经是完全不现实的了，但如果这个争议一天不解决，中国，至少在民间，就应该以某种形式支持琉球独立作为一个反制方式，作为压日本谈判的基础。

中国政府当前的策略是极其有远见的。在坚持中国的主权底线下，对日本进行一点让利的甜头。其实对一个大国而言，不论是有利于大陆架国家的国际关于大陆架的条款，还是有利于海洋国家的关于专属经济区的条款，你都不能让西方控制的所谓国际法庭来决定你的主权。中国完全不能指望西方的法庭能以不对中国怀有偏见的心态来进行仲裁。这样的主权纠纷只能由纠纷国的实力来决定。而中国目前在面临日美军事联盟尚存，直接对抗并不占优势的今天，当然应该选择将主权纠纷留到后代，等中国的实力强大之后，再去解决问题。


七十三

在搁置主权争议后，对该争议地区进行共同开发，是唯一的可行方案。如果中国和日本在这方面不能有个双方都满意的协议，那么就可能会引发一系列的连锁反应。比如，假设中国强行在春晓等油气田进行开采，则由于春晓本身位置并不在争议范围之内，日本除了抗议（以春晓油气田会从争议地区吸收油气为理由）之外只能做些象征性的举动，比如让得到授权的日本石油公司在争议水域里勘探等。虽然中日不会因为相互这些姿态性的挑衅动作，包括可能的舰队或军机的短暂对峙，来一场真正的军事冲突，但是东海局势和中日关系，就必然会呈现紧张关系。

在这种形势下，中国在东南亚的布局就可能受到不良影响。本来，目前控制南沙群岛的几个东南亚小国和中国之间已经达成了共同开发、和平解决的协议，这些小国也根本没有兴趣去挑战中国在南沙群岛的地缘战略利益，甚至视中国军力的存在为他们的保护力量。但一旦中国和日本为东海争议海域上剑拔弩张，这些国家对中国许下的承诺就会有所怀疑，从而为美国军力介入南沙群岛问题提供一个极好的切入点，使美国可以高姿态的重新驻军这些国家。

因此如果不能达成共同开发协议，这串可能的连锁反应基本使中国无法在这些海域进行开发。今天能源对中国的发展如此重要，而国际油气价格又持续高企，中国守着这大量油气储备却无法开发，岂非浪费？换一步说，由于能源价格高企，西方发达国家已经加大对各类可再生能源的研发投资上，不排除在今后的数年内在这个领域有重大突破。如果等到未来去解决争议，可能那时的油气资源已经不再那么值钱。正如西方俗语里一句话，一鸟在手，胜过二鸟在树。

其实对于中国今天的发展，寻找稳定和多元的资源固然很重要，但是如何尽快提高能源使用效率是最迫切的事情。减缓能源需求和供应之间的不平衡压力，改善现在的环境污染，这些问题都急切需要解决。中国在这方面比西方发达国家落后至少有二十年之多，能源利用效率要差于美国2.5倍，欧盟的5倍，和日本的9倍。中国的落后低效率不光存在于对能源如石油天然气的勘探和开采上，还存在于提炼和加工方面甚至终端消费上。当年中海油出高价并购尤尼科，一个主要目的就是获得先进的开发和提炼技术。但由于美国其他石油公司担心中国会打破他们的技术垄断，从而增强在世界上开发油田领域的竞争力，通过其控制的美国政府令收购计划失败。如果中国能够通过东海开发和日本公司合作，就会绕过这个阻碍，有助于中国获得这些先进科技。

日本与中国正好相反，在节能上位于世界前列。日本人创造１美元的GDP只是美国人的37％，是名至实归的世界第一。除了其完整详细的法律和全民族的节能和环保意识，日本在如何有效的综合使用能源上，确实有令人佩服的一套。笔者在数年前就建议中国应该以东海合作上的让步来换取日本在高能效技术上无偿或低价转让。这样不光可以为中日两国人民创造出一个更好的居住环境，而且光是中国节省出的能源，恐怕已经不亚于开采出来分给日本的分额。而从中带来的合作的好处，又是多方面的。


七十四

如果日本无法分享东海的能源，那么在当前的局势下，日本只好在美国控制的伊拉克油田（是否可以顺利增产达到设定目标还是一个未知之数）等着买入经过美国大石油公司和华尔街大投资行拼命吹泡的高价石油，或者就是利用日本庞大的外汇储备，加入非洲的油气资源争夺战。目前欧美仍然占非洲石油出口的57％，为最大市场。中国占非洲石油出口14%的份额，已经引起了来自美国和欧洲的口诛笔伐，试图利用苏丹达尔富尔和抵制奥运会来逼迫中国吐出来。而且目前中国尚无其他亚洲竞争对手——印度是作为合作方跟在中国大佬的背后一起合作，比如在苏丹的大尼罗河石油公司里，印度的股份就有25％，这样的合作就为中国减少了因为竞争而推高的成本。如果日本再加进来抢油，而且也学中国抬出“投资无附加条件”的招牌菜，肯定会推高中国在非洲开发石油的成本。

反之，如果日本能和中国合作，以其自身技术能力，以及方便从西方拿取技术的身份，配合上中国在国际政治和外交上的大佬身份，由中国的石油公司带着日本老弟一起玩，就可以使日本的海外能源来源多样化，还能够参与到美国和欧洲都够不到的地方去开采石油。一旦日本的能源来源不必完全依赖于美国，日本就会比较愿意对美国的全球政策上摆出一幅不太热心的“保留态度”。又由于日本的能源来源更多和中国扯在一起，自然会比较容易赞同中国对全球事务的看法。而当日本不得不服从于美国的诏令而参与对某些国家制裁的时候，就可以在中国成立由日资公司控股的影子公司，或者同中国公司合股组成中国法人公司，绕过美国的制裁限制继续到这些国家做生意。

中国在与日本达成东海合作协议后，除了引来美国和欧盟对东亚经济一体化的疑虑以外，俄罗斯恐怕也会发表一些怨言，因为中日合作使其在西伯利亚油气资源奇货可居从中渔利的谈判姿态必须放软，但俄罗斯也不得不服。而在中日合作基础上，美国在与中国能源技术的合作和转让问题上，也同样要降低价码，以免让日本独占中国市场。如果中国能够有效的利用日本和美国的技术，并在其上进行改进，在清洁煤、液化煤、二氧化碳地下储藏和人工光合作用等方面有所作为的话，就可以大大减低中国对海外能源的依赖，从而降低中国由于争夺资源而和美国和欧洲造成冲突。本来，由于中国是这几年来唯一一个持续进行大规模基础建设的国家，中国对原材料和各种金属的需求量极大，但因为还没有抢进西方列强的饭碗，因此在原材金属领域西方还是比较容忍。但在石油和天然气能源上，由于西方经济极度依赖油气，中国的小小动作，就会造成满堂喊打喊杀。

事实上美国的节能高技术与日本相差不是太远，但由于美国政府，尤其是外交和国防领域，被石油公司操控，任何国内的节能计划通常会被政府反对而胎死腹中。现在美国一天要消耗2000万桶原油，其中1100万需要进口，这个消耗量的69％是用于包括开车之类的运输，只有大约4％用于发电。所以明眼人都看得出来，要改变美国人对海外石油的依赖的首选，在于如何改变当前的交通技术和生活方式，而不是如何利用太阳能发电。其实在七十年代，美国已经有很成熟的电动车技术，可是由于政府的阻扰，这个技术完全没有得到发展，即使在今天油价不断攀高的情况下，也只是电油两用车初成规模。相反，倒是那又斩杀美国纳税人又忽悠环保义士，享有发展中国家“粮价杀手”美称的生物乙醇燃料得到政府的大力支持。


七十五

08年后，国际上一帮“战略家”除了大谈由美国和中国建立共同管理世界的G2新概念之外，又多了一个P3的玩意88，也就是所谓“太平洋三强俱乐部”，由美国、日本和中国参与来解决全球的经济和政治问题。另外，英国的《经济学人》杂志提议把加拿大从G889里赶出来，让中国代替。还有另一种能“容纳”最多国家的提法，就是在现存的G8基础上，扩大到G13，加进中国、印度、巴西、南非和墨西哥。90这各种提法，都是为了应对中国成长为一个世界超级大国而对世界新次序而作的重新安排。但是这些提法都忽略了一个最大的问题，那就是无论哪一种排他的俱乐部，都无法对国际性和地区性的事务做出全面的操控，没有一个俱乐部可以涵盖所有面临的挑战。

　　比如说，如果要谈到石油问题，你不能不包括沙特阿拉伯。可是除了石油问题和中东问题之外，沙特又不能在其他事务上有所作为。那么你的这个排他性俱乐部到底包不包括沙特呢？再比如，地区性的争议，比如在非洲或者拉美的问题，你不可能不首先考虑当地的国家或国家联盟如非洲同盟和未来拉美同盟的意见，但这些地区联盟又不可能对其他地区的事务有太大发言权。所以合适的体系，还是应该变成由最主要的国家形成一个小圈子，然后又在具体事务上临时加入各相关团体。

　　那么这又和现在的G8体制有多大区别呢？俗话说，汤多不入盐，主要的区别是现在的G8俱乐部闲杂人员太多，真正合资格入会的人士太少。从国家分量来看，加拿大固然是个十足的假货，但是其他的国家也好不到哪里去，意大利就是7成水货，连法兰西、德意志和不列颠都是3成加水。俄罗斯和日本如果合并变成一个国家，则倒是名副其实的硬通货。可惜两位仁兄都是一条跛腿，日本跛的是政治腿，俄罗斯跛的是经济腿。只剩下来一个美国，挟政治、经济、军事、科技和外交的超级强权，才堪称当然会员。这也难怪当初新保守派分子们上台时有种投鞭阻流的气派了。

　　另外一个问题是，由于中国的异军独起、别树一格，也给当前的格局造成一个极大的困扰。本来一个俱乐部都是物以类聚、人以群分，来参加的不光是要够资格交得起会费，还要有同好、同趣和同心，才可以同声同气。而中国就是与大家不同，如果你不拉进来玩，那么这个俱乐部就是形同虚设，而且好多事情都是只能以口水漱牙，大家磨一阵子嘴上的粗皮，往外喷上大大的几个吐沫而已。可是如果要拉中国进来，就要大改章程，结果可能让原先说好的足球俱乐部，变成了美式足球（橄榄球）俱乐部，搞到与设计的原始初衷风马牛不相及。

　　大家都知道，这里的差别在于意识形态下的政治制度。以中国当前的政治体制，西方自然不愿放弃其自以为是的个人幸福感觉，照着镜子忸怩作态，自己把自己爱得差不多要昏过去了，哪里愿意为了你一个“丑陋”的面孔而削足适履，改变他们的游戏规则呢？那么要中国人改变，才可以入会，这听起来好像是一个很好的选择。可是，如果中国人变得太慢，等到合乎这个俱乐部的入会资格时，也许俱乐部早就破产了。更何况，中国人小日子越来越红火，可能真的不想改变其经过实践检验的成功方法而去整容加入你家俱乐部呢！

　　当然也有人士认为，为什么中国不快点变成俱乐部要求的标准呢？答案就是，如果中国吃了这张开出来的药方，然后兴冲冲的赶去交俱乐部申请书，可能在还没有走到俱乐部大门口的时候，就已经病发而死在路上了。


七十六

　　其实明白这个道理很简单，近的不说，看看当年俄罗斯的经历，大家就知道这种以西方药方为蓝本的所谓政治改革，其实是饮鸠止渴。说难听点，只不过是西方在新的形势下，为大家开发出来的新型鸦片，让你吸了毒后，毒瘾大发，好比十七年前被俄罗斯那些丘拜斯盖达尔忽悠的不行的俄罗斯老百姓，觉得很high很快乐。然后等毒瘾过后，俄罗斯那些老百姓再回头看，就觉得自己真是好傻好天真。
　　
许多人会说，中国人都没有搞过议会民主和选举，当然不知道里面的好处。错了，中国人早就搞过议会民主和选举，最后搞到国家变成了一个个独立的小王国，只是到了1950年，才又靠着几千万条生命的代价，变成了一个虽然不富裕，但至少不被列强鱼肉的国家。在中国议会民主的一幕很有趣的戏，就是1923年曹锟选总统。当时来自全国各地的议员们已经将自己的选票开出了价，大致是5000个中华民国第一任正式大总统袁世凯的光脑袋银洋。5000个袁大头碰撞在一起，估计比拉斯维加斯的老虎机吐硬币的动听音乐更要接近天籁，够这些人民代表们天马行空，想入非非一阵子。

　　可惜中途杀出个程咬金，据某家大报（如同美国拿手的宣传战）爆料，曹三傻子刚刚用10万块钱娶了一个年轻貌美的妓女做四房姨太。这一下，整个国会炸了锅。群情激愤，这些谦谦君子们怒火万丈，开始讨伐曹锟的恶劣行径。唉，也不是大家真的贪钱，只不过发现堂堂民选的国会议员拿出来卖，居然还卖不过一个小姨子！而且一个小姨子居然值20个国会议员，真是斯文扫地，是可忍，孰不可忍！这一下不得了，曹锟赶紧约见议员，做好思想政治工作，并公布了事件的真相：此系一些别有用心人士所为，其实买妓女只是花了4万大洋而已。接下来就是一轮轮国会议员的讨价还价，唇枪舌剑，结果最终以每位议员1万大洋成交。通过这番实践，民选的国会议员们真实的感受到了民主赋予的权利应该怎样善加运用。最后，曹锟先生赢得了593票中的480票，高票当选了伟大的中华民国总统。
 
图8.1 左：1923年的曹锟撒大洋贿选；右：1996年的叶利钦用国有资源类企业低价转让换总统

　　不过回头来看，曹锟虽然绰号叫三傻子，其实智商要比美国两次由人民选出来的布什总统要高些，至少曹兄是靠自己的本事在社会中出头，不像布什老弟，要靠着前总统老爸和州长弟弟又推又拉抬上总统宝座。也许有人又会说，那些时候的歪脑筋道道，今天大家都已经开化，没人会去玩。笔者看说这话的人，估计是没有去过印度、菲律宾、日本、韩国还有我国台湾等地，看看“真正的民主选举”是怎么玩的。其实标价方法和收钱方式和前中华民国的选举基本相似。也许会有些人说，这些都是在低素质的亚洲人手里弄得民主变形，人家北美和欧洲的就比较像样。其实应当用北美欧洲“更高明、更精细”来描述要更准确一些。不信的话，如果你有钱，想在美国收买官员替你效劳的话，笔者倒可以教你几手。比如说，要办什么样的事要对应买哪几个官，每个什么价，什么方式付款，如何保证回报等等。记住，这些可都是合法的哦。

　　笔者并不是说议会民主一无是处，相反这里有很多方面值得中国学习。但是如果个个明白人都要把自己读成假洋鬼子，张口托克维尔闭口光荣革命91，对美国和西方制度一知半解，对实际操作完全一头雾水，只是满足于读完几本《民主入门傻瓜教材》，就成日高谈阔论，在不了解西方的政治实践又不了解中国传统深入民心的政治理想的情况下，盲目用西方政治理想来批评中国政治实践，硬套制度，那么倘若这些人呆在海外，还只是增加些噪音，倘若呆在中国的学校里，也还只是妖言惑众多骗几个后辈而已，但如果这样的人在中国当政，那可就是大难临头。这时就一定要起来推翻他们，免得这些江湖术士把中华民族再次拖进四分五裂的深渊，害得大家又要辛辛苦苦的再去统一中国一次。


七十七

在孙中山对美国的民权充满向往的时候，超过数百万的美国黑人还在集中营里做奴隶。自从林肯赢得美国南北战争之后，法理上黑人已经成了自由人，不再被当成奴隶，但美国宪法和其他法规并没有认定把黑人当奴隶这种举动是犯法的条文。于是美国南部各州自己颁布了形形色色专门针对黑人的法律，比如说黑人在任何时候必须证明自己有一份合法的工作，否则就立即抓去坐牢。在这种情形下，很多黑人就成了犯人，被南部政府合法的租给美国的大企业如美国钢铁公司（US Steel）等，作为变相的奴隶来用。在这些强迫的集中营里，黑人受到的待遇是非人道的，各种类似于关塔纳摩的酷刑和折磨方式层出不穷，许多在营中的黑人在沉重劳役压迫下，疾病得不到治疗，折磨无休无止而丧生。而美国公司在租用这些罪犯来开采矿山，修建道路时，则赢取暴利，还因此借此获得谈判筹码，击退了白人工会的罢工反抗。到底多少黑人被奴役，仍然没有总的数据，但是光在阿拉巴马一州，至少超过20万黑人被租出去。92


图8.2 在1930年仍然在做事实上的奴隶的美国南方黑人

这个情形一直持续到1941年，才由罗斯福政府出来干预。而当时干预的原因是，日本帝国利用这个事件开展的道德宣传攻势非常成功，让美国政府在国际上名声扫地。另外一个原因就是美国需要大量人力从事二次世界大战的战争军需品的生产工作。于是在珍珠港事件的第四天，美国政府立法限制出租黑奴。可以说是日本军国主义分子们阴错阳差，救了黑人一命，但马上又把无辜的美籍日本人变成了新奴隶。而当时的中国政府也趁此机会，由宋美龄主导，借美国敌视日本，同情被日本侵略的国家的人民的时机，推翻了臭名昭著的《排华法案》。 

而美国和英国放弃所有不平等法案带来的在华特权，其实也得益于日本军政府和汪精卫伪政府签订的日本放弃不平等条约的协定。所以美国和英国被迫不得不作出比日本军国主义“道德更高尚”的行为来。即使是后来的黑人民权运动，如果不是苏联的政治攻势，估计很难预料其结果如何。甚至在半黑人奥巴马出来选总统，已经经历了两任黑人国务卿（鲍威尔和赖斯）的今天，美国年轻黑人男性中仍然每9个人就有一个在蹲大牢，而且这种局面彻底改善的机会基本上还不存在。

所以有人戏谑的解释说，美国宪法上的“人人生而平等”是翻译错误，应该是“所有（白人）男性（被上帝）创而平等”。女人当然不能算人，其他人种的男人（只要不是盎格鲁－撒克逊（即英国）后代或德国北部和北欧的日耳曼后代）自然也不能算是人。如果明白这个道理，就大概能知道美国社会骨子从来倡导的都是精英政治（打着自由的旗号，让这些优越群体名正言顺控权），而非真正广泛的民主政治。美国当年可是只讲自由不讲民主的。

　　任何一个社会，在考虑如何维持其在稳定和变化这两者的平衡时，都必须面对两个方面的考虑：一是如何创造出足够的流动性，让穷人能通过自己合法的努力，在社会中出头；二是如何保障富人的利益而不受非法的社会行为的损害。如果不能保证前者，那么这个社会除非用宗教等手段麻醉底层，否则长期苦干却眼看要一辈子牛马的人，迟早揭竿而起；如果不能保障后者，那么这个社会就没有了目标和公义，因为大家随时都可以用对社会的财富分配“愤慨”不满的旗号来要求重新洗牌，那么任何个人规规矩矩的奋斗和努力，就毫无价值，大家只要知道如何揭竿而起，用枪杆子打土豪分田地就行了。

　　中国的传统社会在这方面做得最好。其中一个重要制度是儿子们的平等继承权，这个制度使中国传统社会富不过三代。有钱人通常会多娶老婆，然后由众多的儿子分家，就难以代代积累形成拉美庄园主那种超级大富豪。当然现在不可能这样多娶媳妇多生儿了，所以只能通过高遗产税和劝人为善多多捐款来解决。另一个保障是教育平等权和科举制度，给予任何有志向的穷苦人以一个奋斗的机制。此外再加上对外战争立军功加赏的办法，也给了人们一个向上提升自己社会地位的体制。所以在在这些机制中，通常被逼着落草为寇的人，都是实在没有能力在体制内过关斩将的挫败者，比如清朝的洪秀全就是一个多次落第的秀才。


七十八

　　而人类社会就是要有这样的制度，既让所有青年洪秀全不会成为中年洪秀全，又让沈万三儿子和孙子不再继续富裕如祖宗沈万三。93

美国人是如何处理这个问题呢？美国一个最根本的基石是法治，只要程序合理，不求结果公平。在美国私人财产神圣不可侵犯，不考虑你到底如何得来的。比如卡耐基是盘剥工人得来的万贯家财，布什家族是靠贩卖黑奴和与德国纳粹做生意得来的亿万家业，这都不是问题，但是如果有人侵犯他们的财产，就是一个大问题。那么你可不可以剥夺别人的财产呢？可以，只要你合法且按照法律程序。比如在美国，如果你看中了某位人士的地产，你可以跑到他的地盘上开派对、请客、进行野餐之类。如果那位主人太好客，不忍心来扫你的兴来阻止你这些行为，在超过一个时间段，比如说20年后，你就可以正二八经的去法院递交申请，要求把这块地正式归于你，应为你已经行使了地主的权益而没有人有异议。

　　如果这件事发生在中国，当法官作出合法但不合情合理的判决的话，估计中国人立马就会把这个法庭放火烧了。中国人重结果多于程序，重公平多于规矩，重人情多于道理，都使法制的推行具有一定的难度。法不责众，刑不上大夫，都在数量上和质量上对法律的普遍性和公正性进行挑战。这说明中国社会中的有高于法律的更高理念，“人民的多数认同”高于法律精神，而且倾向于认为“精英思维”比法律要更有真理价值。

　　粗听起来这似乎让人觉得中国人天生就是民主的料子，因为其对“民意”的重视似乎是一个终极社会关注。而民意又代表了天意，天意决定天命，而天命又决定谁来当皇帝这样重大的政治问题。水能载舟，也能覆舟，似乎得罪老百姓的后果，是不可以想象的，是不能不由当权者来负责的。那么为什么历史上，为什么经常出现真正的民意没有得到应有的重视，最后搞得历朝历代的皇族们一个个被剥夺了天命呢？

　　中国历史上屡玩不爽的一个指责游戏，就是把罪责怪到庞大的官僚系统上，“反贪官不反皇帝”。天子是要与民同乐的，而且芸芸众生也是出自内心爱戴万岁爷的。全国人民上下同心，但是在中间却出了岔子。也就是说国家这大房子的屋顶很棒，基础也很扎实，可惜是中间的柱子被该死的蛀虫挖空了，搞得国家摇摇欲坠。看来天不变，道亦不变，这帮官老爷们，黑了良心，把孔老爷子的教训吐进痰盂桶了。

　　所以看来问题不在皇帝那里，而在贪官那里。只要我们可以清洗贪官，这大宅子还是会高大光猛、富丽堂皇、生机勃勃。所以说，中国的民意重点不在于如何选举中华人民共和国主席，甚至也不在于如何选举三里屯屯长，而是在于究问为什么这个傻冒屯长没有听听“俺”老百姓的说法。中国的民主最大的关注，不是官威（地方政府的威信），而是吏治（地方政府的诚信）。所以西方选举民主从原理上就不能解决中国的问题，因为西方选举政治重点在于决定政府的威信问题，或者是“为什么这个政府具有合法性”的问题（比如这几个蛤蟆官“合法”是因为俺三里屯人选了这几个蛤蟆），但不能解决这个政府的施政合理性问题（为啥这些个选出来的蛤蟆晚上三点呱啦呱啦吵死人？）。亚洲国家普遍存在类似现象，生搬硬套西方选举制后就解决不了本地民生（施政），比如印度贫民窟选地方长官，基本都是选举承诺满天飞，选出官后统统忘，老百姓也奈何不得，只能得过且过。

　　可以想象一下，如果中国科学院可以发明人工智能机器人，每个村子里放一个做村长，每天就把老百姓的想法按支持度排名，输进去，然后让机器人执行，不知中国的政府效率和行政廉洁可以提高多少？


七十九

其实这个假想的机器人村长，它的作为就很像中国传统的技术官僚，这种技术官僚对当地的错综复杂的利益关系和派别采取一种旁观和超然的态度。在中国的传统制度中，这个官员必须是外派，不能在本地当官，并要代表中央政府行使管理地方的责任。但在操作实践中，当地方势力增长，比如中国改革开放三十年后中央集权向地方分权过度，就会出现由层层地方官员形成的强大体系，自然削弱地方官员代表中央政府的意愿，而衍生出一个相对独立的地方政府势力。

　　在过去的体制中，一个来自广东岭南的官员来到山西洪洞县做县太爷，第一个面临的问题就是语言不通。因此他不得不依赖地方上的士绅来协助他的工作。这些士绅们通常是分成两类人士，一是退休后，告老还乡回到本地的老官僚，其中不乏曾出任高级京官如尚书之。二是取得举人资格，就在家等空缺外放，没当官的本地精英。这两类人都是当地的有头有脸人物，在地方上具有影子政府的角色，没有他们的鼎力支持，估计所有的外来县太爷都要一筹莫展。当然发挥余热的老爷子们以动脑张口为主，随时可以传一两手绝活给本地动手跑腿的后生们，进行做官前的实习训练。在某种情况下，中央政府与地方之间的关系是建立在一种灵活而多变的契约关系下的，根据形势而年年调整。中国的历史上中央政府对地方上的事务通常干涉极少，只要钱粮（税收）顺畅，刑名（社会稳定）不乱，地方上的事务通常通过血缘联姻的同宗会、商业上的同业会、还有宗教团体等非政府的社会协调组织来维持。

铁打的江山就需要流水的兵，为了维持社会稳定，一个地方的政治、经济和军事实力，就不能同时被一帮人，或者说同一个利益集团所控制。这就要求管理当地的官员必须经常轮换，避免与当地势力结成利益同盟。就算是退休的老官僚可以通过过去的门生或者同僚关系，来干预现存官僚体系的运行，但毕竟是人一走茶就凉，其影响力还是相对有限，要受到现任官员的限制。而一旦出现现任官员压不住当地的地头蛇，被当地势力控制而失去独立和中立的非地方性色彩的情况，就需要中央政府的干预。然后那位手持尚方宝剑，握有先斩后奏大权的钦差大臣就开始走马上任。而由于当地士绅的过度用权导致的社会不公，就会在击鼓鸣钟，拦轿喊冤的信访制度下，通过王朝马汉这些公正的法律卫士护驾，让黑面老包一出场，问题就得到了暂时的解决。

这套传统社会的治理模式在今天似乎就不再行得通了。一个主要的趋势是在城市化和工业化大潮下，作为农村本地的精英，不再享受原先的社会地位，从而选择“人往高处走”的情形。其结果就是导致了人才在沿海大城市的高度集中，退休的官员也不再返乡过田园生活，而是跟着子女住大城市，甚至飘洋过海一去不复返。而在过去的朝代里，农业税收是国家的主要财政来源。现在，由于农业税基本免除，在农村日常发生的事情也已经不再受到高层的重视，只是在出现大面积的群体对抗事件时，才会引起高层的关注。

　　其实，今天这个局面的形成，和中央政府在过去几十年采取的经济发展侧重不均有关。因为长期的不均衡发展政策，尤其是在九十年代以来过分着重城市发展，使东西部、沿海和内地、大中城市和县镇村之间社会发展极其不平衡，个人机会严重不均，结果导致了各类人才从这些最欠缺的地方流失，造成人才的在全国分布的两极分化严重。而当前实行的政府行政制度，又非常近似于元朝忽必烈的吏员入阁制，结果使底层政府管治水平道德水准低劣。对于这一点，笔者早在80年代末期，就已经做出预言，可惜当时并没有得到重视。


八十

　　当年忽必烈治理中国，对政治制度进行了两大改革。一是成立的新的行省制度，改变了过去郡县的缺乏中间环节的体系，把金朝实行的临时行省制度固定下来。二是鉴于宋朝官僚的重浮夸轻实干的特点，取消了科举取士，改用提拔本地能干的吏员出任官员位置。这个制度的长处在于吏员有长期的实际政府行政管理经验，可以处理各种当地事务，其缺点在于由于在本地工作时间长，又与利益集团有千丝万缕的联系，加上缺乏传统儒家知识分子的教育，贪污腐败就不可避免了。

在现代社会，政府的管理职能日益多样化，从古代简单的税收和治安，推广到现代社会公共卫生、道路交通、乡村企业、教育扶贫等等。在现代社会政府权力必然扩大的同时，却由于上述种种原因导致的人才流失，使得留守当地的人才出现低素质化，显然政府的管治水平降低就不是什么大惊小怪的事了。而这个过程中，矮子里的将军们，又变成了庞大官僚机构里的冗员，本来应该在当地的各种社会、经济和文化活动中起领导作用的地方精英，就被这个安逸的工作养懒了。

而全国经济发展的不平衡的局面下，由于市场经济人要求财，自然会产生一个现象。就是城市里的工业和商业利益集团，就会以手上的资金和技术的优势，以开发落后地区为名，趁已形成的不公平竞争条件，对小城市、县镇村实施原材料、矿产、能源、土地和劳动力的低价剥夺。而当地的政府官员，包括从外地派来的代表中央（其实往往更是省级）政府的主管官员，又因为官员指标的设定，必须以经济发展为工作重点，自然希望做出点成绩，有助于升官，就为地方一级的政治和经济实力一体化，即官商勾结提供了温床。

本来，一个地方的经济发展，自然会牵涉到利益的分配，不论是对矿山的开采，还是水库的修建，还是新的商品房开发，必然会对各方面的利益博弈提供新的舞台。在这个分大饼的过程中，既然没有太多先例可遵循，就必须留有一点冲突的空间。比如说企业主、政府公务员，和平头山民，都会为捍卫自己的利益而斤斤计较，寸土必争。在这种情势下，政府执法部门应该置身于事外，不能轻易的变成任何一方随意动用的私器，更不能成为企业主在同工人谈判过程中，或者是政府人员对待市民中，一旦出现僵局或失去耐心时就随心动用的私人保镖力量。

　　执法公权力被少数团体、帮派渗透，或者是无止境的乱用，就会形成政治、经济和暴力的一体化，这是对中国社会基础的最大破坏。官商警力被这些少数群体操纵，会让地方的政府的管理威信彻底破产。一旦事情闹大，当地政府又无法掩盖的时候，上级指派的治安力量就不得不介入，而地方大员和钦差大臣就匆忙的出来救火，平定局势。如果一旦再上面一层的省级政府权威失效，那么后果就不敢让人想象了。

如何解决这个困局呢？其实并不难。第一点是削减地方的警力，严格限制警察力量被用来解决民事纠纷，把地方纠纷的弹压权交给武警而不是警察。把地方的治安权重新给予地方联防，而非武装的警察管理日常治安事务，薪水问题由地方财政解决。如果武器控制在武警而不是警察手里，地方乡政府不能再粗暴的运用警力来面对刁民，看你还敢不敢不和群众打成一片？

第二点是大幅度削减政府行政工作职位，把大多数冗员赶进社会，发挥他们的一技之长。让地方上的能人们可以自己出头，出现各种能由其人际关系靠其三寸不烂之舌协调各方利益的人士，让他们发挥影响力。

第三点，以经济激励手段鼓励大城市的年轻人向中小城市搬迁，对中国的中西部进行税收优惠，提高基层政府的公务员素质。





























【写作日期】2008年7月24日——30日            
