# -*- org -*-

# Time-stamp: <2011-08-22 14:00:32 Monday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 【第一篇·回顾】





此情可待成追忆，只是当时已惘然。

                                                --【唐】李商隐

一

二零零八年，对未来的历史学家而言，一定是个代表着分水岭的年份。

这一年，一个全新的国际秩序逐渐初现雏形，全球的大国和准大国们都在这一年根据自己的国家利益重新洗牌，省视自己在尔虞我诈的国际丛林中合纵连横的策略，为自己辨清当前的这一刻，谁是盟友，谁是敌人。

也是在这一年，四百年的西方对世界的统治地位开始衰落，世界重心完成了它从东至西的漂移，开始向东亚转移。自哥伦布时代起，从东亚，到西欧，到北美，再回到东亚的历史大循环，开始走向收笔。

这一年，处在这一历史大转变的数个大国和国家集团都发生了潜移默化的重大变更，为未来的国际社会和全球体系铺下另一轮明争暗斗的伏笔。

其实一个具有划时代意义的事件已经在前一年发生：在2007年，世界第一经济强权美国已经不再是全球经济的发动机。这一地位已经被古老而新兴的中国取代。以前只要美国打喷嚏，全世界就要重感冒的情形已成了昨日之黄花。凡是经济上变得相当依赖中国的国家，就不需要喝感冒茶。虽然流传在这一年早些时候关于美国和世界各国经济脱钩（De-coupling）的预言，还有些言过其实，在美国重肺炎的时候，全世界也还会被严重的传染。但由于中国经济的兴起，有能力保持住一定的增长率（8%以上），国际的经济格局其实已经有了里程碑式的变革，只是，这一变革的主角——中国，似乎还尚未自觉。3

其实，相比于经济数字，也许人们会更记得今年的新闻标题。而今年的全球种种事件，却会让未来的历史学家和分析家们记忆犹新。

在这一年的八月，中国举办奥运会，将向全世界展示它三十年的经济成就。对于中国自身来说，如何给自己进行一个总结归纳，提炼经验和教训，及时调整整体的政治、经济思路，为即将来临的世界经济暴风骤雨做好足够准备，打造出真正有内容的“北京共识”，是当务之急。对于广大发展中国家的人民和政府来说，除了对中国城市表现出来的飞速变化极端羡慕之外，如何与中国共同学习、修正、发展真正的经济社会发展理论，并和中国合作，活学活用在他们自己的经济发展上，拒绝西方提出来却被事实证明是发展毒药的“华盛顿共识”，当是观赏奥运会的第一感叹。而对于经济逐渐衰落的西方大国来说，看到中国的欣欣向荣和生机勃勃，却充满了嫉妒和愤慨之心，以至于图谋利用奥运会作为人质，搞烂中国的名声和形象，以此来达到要挟和勒索中国的目的。这其实是其在奥运会前的一系列针对动作的第一要点。西方人打的是普世价值——（美式）民主自由人权的旗号，出的是“负责的利益共享者”的请帖，要的是中国用其日益增长的大国影响力，为西方的全球经济和战略利益服务。

早在2001年国际奥委会授予北京奥运会主办权时，西方就开始对这个事件进行计划。4中国似乎被逼上一个两难选择。要么向西方威胁让步，在许多中国的核心利益上让步，以保证奥运会顺利进行，要么坚持自己的国家利益，承受西方毫无道理的挖苦和攻击。

可以想象的是，世人将看到两个影响深远的文化体系，以自身巨大的政治、经济、外交和文化影响力，开始了一场旷世的较量，而这场较量，将会对今后近百年的世界发展，带来深远和长久的影响。


二

我们可以回过头去看一看上一次国际秩序的大洗牌。

那便是发生在1956年的苏伊士运河危机。在二次世界大战之后，世界强权英帝国和法帝国在与纳粹德国的苦战中，势力衰落，但仍然想保住自己在全世界的殖民地，继续保持在全球的影响力，以图重新崛起。

当时的国际情形，是美国经济独大，苏联军事强悍，世界强权两极化开始显现。世界仅有的几个大国中，德国和日本是战败国，当然没份参与联合国安理会的工作，而美国总统罗斯福和他的接任杜鲁门，将当时的弱国中国当成大国之一的外交政策，也被英国首相丘吉尔和苏联领袖斯大林强烈反对。5但以当时的世界局势，希望中国成为一个对付苏联的辅助性的平衡力量，是美国的主要政策考虑。

当然，美国的用意，是以那个中华民国来制衡苏联，并同时由美国驻军压制日本，来维护美国在东亚的独霸地位。但随着中华人民共和国的成立，瞬息即变的局势超出了它的掌控。直到23年后美国总统尼克松访华，才有些重新达到了原来意图。而日本在这20多年里就钻了这个空子，被美国扶持起来。

而在中东，美国开始取代英国势力，成为该地区的唯一老板。美国在1953年通过中央情报局策划了伊朗政变，推翻了民主独立的伊朗摩萨台政府，扶持美国傀儡的巴列维国王，从而取代了英国在二战前的在伊朗的统治地位。加上对土耳其和以色列的控制，已经在战略重地——世界经济能源仓库中东形成三把钳子的姿势，控制住居于其中的分散不团结而形同散沙的阿拉伯人。



图1.1 苏伊士危机时期的地图及当时埃及人民热烈簇拥纳赛尔总统欢庆胜利的场景

苏联想伸一脚进来，就利用以巴冲突，通过当时的卫星国捷克斯洛伐克向埃及提供可以和以色列先进武器抗衡的苏制武器。于是美国和西欧便以停止向埃及的阿斯旺大坝提供贷款为威胁。这刺激埃及总统纳塞尔将苏伊士运河国有化，用它的过路费收入来保证进口设备建造大坝的外汇资金。

英法两国以此为借口，联络以色列，在1956年对埃及展开军事入侵，并占领了苏伊士运河区。但是，当时英法两国还未从二战的废墟上恢复，经济上无力支持这场战争。于是两国向美国主导的国际货币基金组织申请援助。这一要求立即受到美国的要挟。美国以联合国维和部队进驻运河区和英法军队退出作为经济援助的先决条件。经过痛苦的煎熬，英法不得不退兵，从此将中东的统治权完全交给了美国。

    这一事件标志着英国和法国作为世界霸权的彻底终结。英国本来在1948年结束对巴勒斯坦的管辖权，让以色列独立之后，还控制着埃及。但是在1951年，埃及发生革命，纳塞尔上台，推翻国王体制，建立共和国。本来美国支持英法在埃及的军事行动，但是在最后变卦，转而在联合国安理会鼓吹停火协议，被常任理事国英法否决后，又通过联合国大会运作，最终逼迫英法退兵。在英国势力受此打击之后，伊拉克的一帮军官在纳塞尔的激励下，发动政变，推翻费沙尔国王，也成立了共和国。

英国的埃登政府因此而倒台。之后的英国人明白了：从今往后，谁才是这个世界的真正老板。此后英国外交政策一直以美国马首为瞻，亦趋亦行，直到今天的伊拉克战争，都是如此。而法国就走上与美国分道扬镳之路。先是开始和德国（当时的西德）和好，为最终的欧盟成立建立基础。当然，法国人从来都是比英国人慢几拍，直到后来的越南（印度支那）和阿尔及利亚独立，才真正明白大势已去。


三

在这之后，美国就成了世界的主导力量。也许有人认为一个大国之所以成为超级大国，必须在各方面都是出类拔萃，其实并不尽然。当时的美国在经济上确实是世界超强，通过两次世界大战发了军火财，又没有在战争中受太大损失。除了夏威夷的珍珠港和殖民地菲律宾经受了一点战火洗礼外，美国本土丝毫无损。虽然在战争中人员伤亡巨大，但比起所有的其他国家，还是算是比较小的。但是当时美国在军事上其实并不占优势，在朝鲜战争中还被新兴的中华人民共和国给了个下马威。在欧洲，美国军力同样比苏联要弱，需要通过核威慑来抗衡苏联强大的陆军。在外交上，如果扣除傀儡中华民国和新收编的英国，其影响力和苏联基本是半斤八两。在文化上，美国就更要稍逊一筹。1932年，当多民族的联邦国家苏联产生出一位非俄罗斯族的格鲁吉亚人斯大林成为最高统帅时，美国的民权领袖马丁路德金才3岁，差不多30年后才开始为深受种族迫害的黑人民众争取基本的权利，并且也很快丢掉性命。也许在70余年后的今天，才可能出现第一位黑人总统，而这位奥巴马，还只能算半个黑人。

通常来说，一个大国的影响力在于三个方面：

一是恐吓力。我军事实力强，你不听我的，就打你个鼻青脸肿。或者是我掌握世界金融和经济命脉，对你实施经济制裁，让你有了上顿没了下顿。或者我朋友哥们儿遍天下，把握

图1.2  1956年，美国取代英国霸权地位的苏伊士运河危机时的世界局势图，美国霸权头30年里来自军事和经济的挑战示意图
左为1956年时英国首相艾登，因为苏伊士危机下台，右为当时的埃及总统纳赛尔
世界喉舌，看你不老实，一起骂你个狗血喷头。

二是收买力。和我站一边，你有好处分。如果还能帮我干一件事，就有更好的奖金。总之，人为财死，鸟为食亡。为利益而行，每个国家都是如此。

    三是亲和力。我的行为让你佩服，你心甘情愿的和我套近乎。当然，如果套完近乎后，又可以有利益可分，自然是锦上添花。有的人认为这种亲和力跟文化价值是一回事，其实是大错特错。现在西方的一些人，成日以为自己掌握民主自由的普世价值，就具有国际舆论的话事权和道德仲裁人的身份，可以在世界上有亲和力，这其实是一种意淫的想法。对一些小国家和曾被人殖民和欺负的人民而言，如果一个大国对他们尊重，平起平坐，不会动辄教训他们，其实可能会有更强的亲和力。

    美国的强大，主要在于其收买力。二战以后通过开放国内市场，使很多国家发了财，不仅包括北约圈子里的欧洲国家，还包括了东亚的日本和四小龙。


四

当然，在战后的三四十年里，美国的霸主地位受到了两个方面的强大挑战：

一是苏联的军事挑战，二是日本的经济挑战。

苏联的军事挑战主要是以冷战的方式进行。唯一的一次热战的可能是古巴导弹危机。其实在两强的对抗当中，持续的冷战和军备竞赛对经济实力较弱的苏联肯定不利，因为军力强大的苏联在战场上取胜比在经济竞赛上取胜的机会要大得多。当然，如果能够既让对方陷于战争泥坑，自己又不直接出手而是在旁边四两拨千斤，那就更是上上之策。所以说美国入侵越南和苏联入侵阿富汗，都是各自的大败笔。在新的武器系统装备下，即当双方都具有完全毁灭对方的核武器而同时又没有保障自己不被毁灭的导弹防御系统的对阵下，两大国直接热战的机会比较小，因为凡是有矛盾，一般都可以通过调动、牺牲自己的马前卒——附庸各国的利益而达到平衡。

 
图1.3 苏联从1987年开始的改革开放，此为1988年的邮票，左为开放Glasnost，右为改革Perestroika

这一军事挑战最后以戈尔巴乔夫盲动的经济改革（Perestroika）和政治开放（Glasnost）带来的苏联解体而告结束。当然冷战中途的中苏分裂和中美友好都削弱了苏联的实力，但是只靠军事一条腿，而没有强大的经济，苏联的胜算本来就不大。

苏联的麻烦始于1979年对阿富汗的入侵。其实经过成本昂贵的军备竞赛，苏联和美国双方的经济资源都消耗很大。这之后十年，在苏联在阿富汗浪费军力和经济资源的同时，衰退的美国开始面临来自日本在经济上的强大挑战。美国的汽车工业、电子工业和机械工业，都在日本的竞争下处于劣势。日本人挟高企的楼市和股市，凶猛的出口工业，和变成巨无霸的各家银行，以一个超级暴发户的姿态，在美国展开购物狂潮，将美国地产的标志，如纽约的洛克菲勒大厦、加州的帕博海滩高尔夫球场，以及好莱坞的电影和唱片公司，一扫而空。激的美国民间掀起强烈的反日浪潮。

但是，日本对美国的挑战无法带来真正的威胁，因为日本在现实上还是美国的殖民地。一旦美国在苏联陷于阿富汗泥坑后松出一口气，立即逼迫日本在对其最为关键的外汇兑换率上做出让步。在1985年的广场协议后，西方各大央行对日元实行干预，让日本为美国经济衰退买单，使美国的赤字从GDP的3.5％降了下来。在短短两年之间，美元对日元兑换率降了一半以上。表面上看，日本的经济实力按美元计，几乎接近美国。但由于快速的货币增长，日本和国际游资强进日本的股市和楼市，尤其是后者，造成固定资产的泡沫化。在最高点时，日本东京皇室3.41平方公里的地皮，居然比美国整个加州的土地总和还要贵。最高价的银座，更是卖到一百五十万美金一平方米（13万9千美元1平方英尺）。不明就里的日本人民自尊心高涨，觉得自己可以和美国叫叫劲。于是有日本右翼政客石原慎太郎和索尼公司的创始人盛田昭夫，出书《日本可以说不》，对美国的权威进行挑战。


五

在《日本可以说不》一书中，两位趾高气扬的作者认为日本应该从商业到外交上都要摆脱美国的控制，寻求独立的国际地位。这本书并不是一本深思熟虑的研究成果，而只是两位作者平时作的演讲的讲稿集。

  
图1.4 左：1962年《时代》周刊带有松下幸之助肖像的杂志封面
右：1989年出版的《日本可以说不》的日本国内版封面

石原慎太郎的主要观点是，日本在高科技上，尤其是半导体方面要比美国优越，因此在与美国打交道时，日本要强硬点，不要老是卑躬屈膝。日本应该用高科技作为一个筹码和美国讨价还价，不惜和政治敌国苏联作交易合作来迫使美国让步。他认为日本应该换掉不会同西方人打交道的外交官，改让在商场上打得美国人落花流水的日本企业家参与并主导贸易谈判。他还主张日本结束与美国的安保条约而改由日本自卫队保护自己，这样可以少花钱（因为美国在日本的军事费用由日本政府出）多实效（因为他对美国军队的效率表示怀疑），并且结束日本对美国的依赖。

石原慎太郎还认为美国和基督教传教士实行文化帝国主义，每到一处，就毁灭当地文化，代之以西方文化。并认为美国人充满白人优越感，自以为现在西方统治世界就不可一世，将来会为此付出代价。有趣的是，他用一种日本人的优越感来攻击美国人的优越感，认为日本工人的教育程度高，竞争力强，而美国工人水平低，产品质量所以差。甚至日本以前的殖民地如台湾和韩国经济也高速增长，而美国以前的殖民地如菲律宾则充满问题。

当然石原忘记了一点，台湾和韩国，乃至包括日本都是处于重视教育和提倡勤劳吃苦的中国儒家文化圈内，而菲律宾不是。只不过从他的看法里，可以看出作为一个黄种人和亚洲人对白人世界的欧美人一贯以来趾高气扬的一种反感。

而盛田昭夫就有些不同。因为他是一位成功的企业家，并在纽约住过，所以他对美国企业界的看法还是比较中肯。比如说他觉得：

——80年代后的美国商界太热衷于合并和并购这类金钱游戏，而不重视真正的产品创新和制造能力；

——美国企业太重视于短期利润而牺牲长期的企业整体生存，比如将制造业移到海外；

——美国公司高层收入太高，对公司伤害大；

——日本公司的员工的日常生活中人际关系亲密，所以总的生产效果要比美国好；

——美国公司在基础研究上比日本强，但是在产品发展的市场推广上比日本弱。

他还提出一些提高日本国际形象和地位的建议，也许对今天的中国都有参考意义：

——美国的反日情绪和日本企业在海外没有和本地人交往成为当地社会的一分子有关；

——日本人需要更多的接受西方文化和语言，便于在和美国人打交道时不会被误解；

——美国对日本的轻视对美国和世界经济不利；

——日本需要明白自己世界领袖的角色，做好支持世界经济应尽的责任；

——日本必须帮助亚洲发展，从而确立起日本在亚洲地区经济中的领导地位；

——日本需要提供更多的海外援助以成为一个真正的世界领袖。


六

这两位日本精英其实代表了日本两种不同的民间情绪。一种是对日本自身国际和地区角色的反思，希望回归本身的东方文化，并不惜为此与美国发生对抗，从而达到国家人格独立的目的；另一种则是加强向西方的靠拢融合，希望在西方为主的体系中担当更大的领导角色。

笔者本人在1988年，也听到日本战略界学者认为美国衰退和中国崛起是不可避免的事。但是如果日本帮助美国的话，可以把美国的强权延长50年。如果日本帮助中国的话，可以使中国的崛起提前50年。而当时的笔者，认为中国崛起的时间就是50年内的事。看来日本学界当时对美国和日本实力的估计过高，而对中国实力的估计过低。

当然日本人以登泰山而小天下的口吻，指点江山，论天下大势，是和当时的形势分不开的。那时日本经济如日中天，在世界上光芒四射，无比辉煌。只可惜，当时的日本精英们无法面对的一个历史事实是，每次日本人的风光来得快，但持续力相当差。当年的大日本帝国是如此，80年代的太阳经济帝国也是如此。不知道经历了经济帝国沉没的日本人，是不是长进了些。

最关键的是，石原们忘了一个残酷的事实，那就是，日本就算是一个经济大国，也没有强大的政治，外交和军事实力。正如苏联的军事一条腿不能持久和美国长期二分天下一样，只有经济一条腿也是没有资格和美国叫板的。结果到了1989年底，日本的楼市和股市泡沫爆破，从此日本走进经济萧条中，一直到今天，过了近20年仍然没有从谷底中走出来。也许，本为右翼的石原慎太郎今天却仿佛开始亲中，是看到日本是没有资格对美国说不，而只有中国才可以这样做的缘故吧。

就在日本威胁消除的同年，苏联黯然的从阿富汗撤军，并在短短两年后烟消云散。从1991年开始，美国开始了一个短暂的意气风发，一支独秀，堪当唯一世界超强的时代。那时候，美国军事实力打遍天下无敌手，将不老实而蠢动的伊拉克变成了展示美国高科技武器实战表演的舞台，为美国军火商赢得滚滚商机。俄罗斯在美国不怀好意的哈佛休克专家的折腾下，几乎破产。中国年迈的邓小平在1992年艰难的南巡，为停滞不前的经济改革竭尽全力，又转身交代中国的年青一代领导人要学会韬光养晦、卧薪尝胆。美国的经济也在日本的崩溃下，恢复生机，开始了以互联网商业化带动的创新浪潮。而美国鼓吹的“自由民主资本主义”模式在全球风行，无坚不摧，最终在90年代末以后导致了多国的颜色革命。

　　而正是在这一阶段，中国开始成为美国的潜在对手。于是，有几位中国年轻学者仿照日本写了一本《中国可以说不》的书，对中国八九十年代一代知识分子过分热衷于西方价值的心态提出批评。当然和日本学者不同的是，中国说不的资格并不是简单的由几个学者可以决定的，而是由当年在朝鲜战场上浴血奋战的中国军队的普通士兵用生命赢来的。与日本不同的是，日本想说不，但却没有这个实力。而中国有说不的能力，但没有做这个选择。

　　其实当时中国的经济实力不如日本，军事实力不如俄罗斯，不是和人叫板的时候。于是中国选择了在政治和外交上避免与美国对抗，尽一切可能广交朋友，集中精力发展经济。


七

　　其实那几位年轻学者的强烈反美情绪是针对80年代末中国知识界的强烈崇美情绪的一种非理性的反弹。这种反弹不仅存在于中国，也存在于世界许多国家的知识精英阶层。这些精英，或出身权贵，或有机会去美国大学深造，从而对美式生活和美国价值极其推崇，学成后回到自己的国家，可以当政、实践那套价值观。可是他们很快就会发觉和美国外交官、政府官员、企业大亨们打交道时充满屈辱，被傲慢和无礼的对待。然后，其中一些人明白了一个道理：美国和以前的强权一样，都不是好东西！

　　不要以为在中国骂美国为帝国主义是中国共产党的发明。话说当年亲美的蒋介石，娶了个完全美国化的宋美龄为妻，还被老婆彻底改造成了个基督徒，对美国的民主自由充满仰慕之情，但在史迪威事件后，老蒋也大骂：娘希皮，美国也是个帝国主义。

　　既是一个超级大国，又缺乏文化底蕴，很难不会让自己变成骄横跋扈，趾高气扬的暴发户。虽然美国前总统西奥多·罗斯福6曾引用西非俗语“手持大棒，说话温和”来描绘美国外交政策的目标，但大多数执行美国旨意的小暴发户们，通常就会把主子的意思，弄成“手执大棒，恶语相向”。
  
图1.5 1904年的漫画，手持大棒的老罗斯福总统漫步在加勒比海

　　其实大家可以留意，几乎全世界的反美情绪都源于对美国全球外交政策的反抗，而不是对美国本身生活方式和文化价值本身的鄙视。处于那个时代的中国政府官员和中国知识精英们本来带着一种谦虚的态度，努力向美国为代表的西方体系进行全面的学习，渴望走出从前的闭关自守的孤立状态，成为国际体系的一员。但是冷战的结束，立即为中国和西方的关系添入不明朗因素。

　　以1991年为分水岭，世界开始了美国一霸天下的短暂时代。而这个时代的来临，必须要有人成为美国勇武出场的祭旗。这个倒霉蛋就是伊拉克强人萨达姆·侯赛因。

　　本来二战后美国的中东政策是抓住以色列，土耳其和伊朗，把夹在中间的财多身子弱的阿拉伯人按住，保证美国在这一地区的绝对权威。但是，天有不测之风云，1979年，伊朗革命成功，推翻了美国傀儡巴利维国王，并扣住美国外交官为人质（因为1953年伊朗的反革命政变就由美国大使馆策划，所以美国使馆人员当然是要赶快关押的外鬼），一举打破美国的原有战略布局。于是美国转而支持伊拉克，希望由伊拉克来削弱伊朗的势力。结果萨达姆以领土争端为由，挑起了长达十年的两伊战争，杀人一千自损八百，对自己的经济造成严重的损害。于是伊拉克转而想用武力收回1962年在英国保护下独立的科威特增厚自己的腰包。结果正好给即将踏上超霸舞台的美国提供了一个绝好的机会，一展雄风，忘掉越战失败的梦魇。
  
图1.6  1983年代表里根总统的拉姆斯菲尔德在巴格达游说萨达姆，20年后两人兵戎相见


图1.7 中东石油产区战后四十年地缘政治演变图

其实萨达姆还是挺冤的，当年在和伊朗在出海口争执不下（伊拉克自从让科威特独立后，出海口就是一个大问题），不料伊朗人捏住软肋，以支持库尔德族反叛独立为要挟，被逼着签订对自己不利的领土和水资源协议，后来被美国前国防部长拉姆斯菲尔德7到巴格达怂恿一番，就欣欣然扩大化两伊战争，又是偷鸡不成蚀把米。最后想收复科威特，而且还事先向美国驻伊拉克大使请示过，并得到了主子批准，没想到被主子拿来当祭品了。


八

　　以当时美国的强大军力和广泛的同盟，可以想象战争的结局。

当然，美国军队在高科技的战争理念和武器装备下，其指挥系统、各兵种协作、投放能力、战地信息交换、导弹精度等等，都令世界耳目一新，佩服得五体投地。而其他国家，如俄罗斯和中国，都是手心里捏把汗，认为和美国军事能力比，自己是不得不甘拜下风，也就开始有了“落后就要挨打”的焦虑。

图1.8 高科技美军在海湾战争中无坚不摧

美国在伊拉克的动武，算是打出了军威，把越战失败之后的一股晦气，总算舒舒服服的吐了出来。这次战争美国一改西方传统的军事行动战术，由其战地最高指挥官施瓦兹柯波夫（Schwarzkopf）将当年在越南战场学到的东方战术活学活用，采取了大范围纵深，从侧翼迂回的方法，几日内就把伊拉克军队横扫千军如卷席。8

这次战争也标志着高科技战争的成型，为世界军事思维带来了革命性的变更。美国在战争中体现出来的强大的科技整合能力、信息利用能力，几乎就是好莱坞的未来科幻大片的情景。而这一次战争，也向世界所有的国家发出了警告：不要以为你可以和美国叫板，挑战美国敲定的全球次序——伊拉克就是一个活生生的榜样。虽然当时美国总统老布什在日本的欢迎宴会上昏倒，被人们解读为帝国的老迈，但随后美国在克林顿的管理下经济重振，就证明了那种说法太天真。

    而美国在伊拉克的出手，也改变了其战略行为模式。即从越战后通过军事威慑，由代理人出手的方式，改变为亲自上阵，大打出手。但是，军事打击伊拉克，再加上驻军沙特阿拉伯，刺激了伊斯兰极端势力，这些人开始了以美国为敌的军事恐怖活动，最终导致了911事件，乃至美国在伊拉克深陷泥坑不得自拔的结局，为美国独大时代的终结埋下伏笔。

    就在美国势力如日中天的时候，其在东亚的军事布局却受到一个重创。菲律宾国会拒绝同美国续约，在1992年11月24日把美军赶出了苏比克海军基地，这使美国封锁中国的第一岛链完全中断。这一事件，不光给了中国海军南下南沙群岛，监视马六甲海峡提供了生存空间，也为印度海军在印度洋的扩张减轻了压力。

图1.9 美军航母撤离菲律宾苏比克海军基地，降美国国旗，升菲律宾国旗


图1.10 美国在亚太的岛链布局及90年代后的进展

本来美国的第一岛链，其北段从阿拉斯加，经阿留申群岛，到日本本土和韩国，再到冲绳，把俄罗斯的东面和中国北部海岸线堵得严严实实，但其南段却在70年代末中美建交中因为中国的主权问题，美军不得不撤出台湾，而已经从中间被切断。这次在菲律宾的撤退，简直就使整个南段军事布局形同虚设。

美国对此的对应策略是，一方面与新加坡签订协议，在樟宜建立一个深水港，为美国军舰提供停泊，补给和维修服务。另一方面，美国试图通过不间断的联合军事演习和911后的反恐合作，采取非固定条约的形势，在菲律宾保持事实上的军事存在，并通过在巴拉望岛和马来西亚在婆罗洲岛的北部领土（沙巴和沙捞越）增加对南中国海的围堵。当然，这些行动都是2000年之后的事。


九

有一点可以确定的是，1992年以后，美国的对华政策发生了根本的变化。

在日本经济因为泡沫破裂难以自拔，亚洲实力格局变化的同时，苏联的解体令欧洲国家发现了机会，迫切渴望填补这一新的空间，于是在1992年二月签署了马斯特里赫特条约（Maastricht Treaty），正式宣告欧洲联盟的成立。同时，巴尔干半岛上南斯拉夫分裂，开始了历时数年的民族战争。

图1.11 苏联崩溃后，当时被视为挑战美国的欧盟在1992年成立时的签字仪式

当时的中国正确的确认了国内的经济改革发展是最重要的国策，一个稳定的国际环境对中国的发展非常重要。因此中国无力也无心在世界事务上挑战美国的霸权，相反还采取了与美国合作的态度，于同年三月份签署了防核扩散条约。

对美国来说，中国潜在的巨大市场，廉价的劳动力和投资机会，都是巨大的诱惑，当然不会轻易放弃。但是中国不同的意识形态、社会机构和成长为大国的潜力，又令他们担心。这就不可避免的造成了美国国内对中国政策的争论，而各种不同的利益集团根据他们不同的商业利益，各取所需，形成了对华外交政策的两大阵营。

一个阵营是“交往派”（Engagement）。这一政策派别主张美国通过与中国进行更多的交往，来确保在中国的发展中获得最大的商业利益，并在这一过程中，对中国施加压力，迫使中国按照美国设计的方向转变。在这个政策的设想中，美国的企业界既可从中获利，而中国又会在美国的影响和压力下转变，成为一个美国可以利用的力量，就象经济发达但政治、军事和外交完全以美国马首是瞻的日本和德国。这一政策要求外国对中国的经济具有更大的影响力，例如让外国资金在中国的金融等关键行业里控制相当的比重。但同时又意求逐渐削弱中国的国家能力，甚至不惜鼓励中国内部的分裂力量（包括国土和思想上的分裂）。

另一个阵营是“围堵派”（Containment）。这一派别主张对中国进行围堵，以确保在中国的发展中不会对美国的强权在任何方面形成挑战。这个政策的主要方向是，增加美国的军事预算，使美国的军事力量对中国具有压倒性优势，然后在中国的周边国家建立起军事同盟，完全控制中国的经济生命线。在舆论上妖魔化中国，削弱中国在国际上的影响力。通过对中国的威慑，比如对中国分裂力量的支持，来迫使中国在经济利益上做出让步。

这两个政策本身都有各自不可解决的悖论。主要问题是他们都只是考虑到自己一方的双边关系的欲取欲求，而不考虑到对方的利益和意愿，因而缺乏双边良性互动。中国则以邓小平的“二十四字口诀”9为基点，尽量低姿态，少露面，除了牵涉到中国的关键利益的事务，在其他无足轻重的事情上，都是以和为贵，以让为主，为中国的发展争取难得的外部环境。

这种不对称不平等的互动，其实为未来的双边关系埋下不稳定因素。如果按照第一种“交往派”的思路走下去，当美国在经济上与中国更加密切，获利非浅的时候，其他的意识形态目标就变得无足轻重，而成了口头空话。而与此同时，当中国经济对美国和世界影响越来越大的时候，美国对中国施加压力的能力就越来越小。此时中国在应对压力上也进行了策略上的调整，在人权问题上提出了“生存权”的观念，又让美国企业完全退出意识形态上的争论，并使美国政府不再把人权作为中美关系的首要考虑因素。至于美国国防工业比较支持的“围堵派”政策，同样面临困境，因为美国在国际事务上需要中国的合作，而且中国周边的国家对围堵中国的提议并不是很有兴趣。

其结果就是，交往不能令中国转变成美国傀儡，围堵只会令中国变成美国强敌。而在这个过程中，中国小心翼翼，埋头苦干，国力变得越来越强，美国影响中国的能力越来越弱。


十

几个主要的事件决定了中美关系以及中国和西方关系的复杂性。

1993年，西方国家试图在维也纳联合国人权会议上推行其“人权大于主权”的理念，试图以此彻底颠覆自二次世界大战结束以来，以联合国宪章中尊重会员国领土和主权完整为基础的国际秩序。本来在原有的联合国原则下，任何国家只有在自卫的情况下才可以对其他国家进行军事入侵。当然，这个世界仍然大国横行，但联合国宪章最起码能让大国受到一些限制，对弱小国家具有保护作用。而一旦“人权大于主权”这一“人权帝国主义”成为国际法，所有大国都会以此为借口，对弱小国家随心所欲进行武装侵略，把这个世界重新带回炮舰政策下弱肉强食的丛林时代。而对于大国如美国，小国家却没有能力去干涉其主权。可想而知，推行“人权大于主权”的政治企图遭到了中国和大部分发展中国家的抵制。

同年，为报复中国在维也纳会议上的领导作用，西方挫败了北京申请2000年奥运会的努力，显示了西方的政治实力和对中国的不满。10

1994年，原本扬言要对中国强硬的克林顿，在亚洲各国和美国商界的压力下，宣布将中国最惠国待遇同人权脱钩，开始了美国政府从以意识形态作为外交手段的策略的退却。但同时，克林顿建议美国国会大幅度增加对中央情报局的代理组织——国家民主基金会11的拨款，并创立了不少美国政府操纵的非政府组织，在全世界对美国重要的地缘政治重点地区上，以民间组织的名义，通过支持目标国的反对派力量，以非军事手段的方式，开展有利于美国的颜色革命。

1995年，美国允许李登辉访问美国，使中美关系跌入谷底，增加了台湾问题的不稳定因素。

1996年，美国以台湾选举为契机，开始了中美双方在台湾海域里的军事对抗，并引发了关于中美可能为台湾而战，并引发局部核战争的猜测。

1997年，香港回归中国，中国的整体经济实力大幅度加强。同年，以美国风险投机家索罗斯领头的西方金融资本在国际货币基金会的合谋下，对金融政策失误的东亚和东南亚国家发动了经济掠夺战。而中国以全国之力为后盾，在香港击退西方风险基金，并通过人民币不贬值，稳定了亚洲经济，使受重创各国能够苟延残喘，从此确定了中国在东南亚的大哥地位。

1999年，美军在南斯拉夫“误炸”中国大使馆，给了中国一个下马威。这一事件刺激了中国军队加速现代化进程速度，并让中国看明白了美国（至少在国防工业圈和军界）在战略上已经开始了以中国为假想敌的转变。

然而，这一切在小布什上台之后，却突然变成了一峰三转的局面。

随着小布什入主白宫，美国由那些在对外策略上极端激进的“新保守派”当权，形成了布什上台初期对华强硬的态度。然而突然间，随着本拉登的圣战死士们将劫持的民航客机撞人纽约世界贸易中心大楼和华盛顿的五角大楼，美国的首号敌人变成了中东的伊斯兰原教旨恐怖分子，而中国则从美国的监敌雷达中暂时消失。

接着，美国以其一霸独大的超强实力对中东进行美国式民主改造，遂陷入伊拉克战争。这使中国在世界各地的权力真空中站稳脚跟。等华盛顿的战略家们几年以后再次回望中国时，已经对中国的国际影响力望洋兴叹，不得不调整其全球战略，希望能够在东亚、南亚、中亚和西亚四面出击，抵消中国日渐增长的实力。













【写作日期】2008年5月28日——6月2日            

