# -*- org -*-

# Time-stamp: <2011-08-27 23:30:56 Saturday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 【第六篇·对策】

#+begin_center
【写作日期】2008年6月29日——7月4日            
#+end_center


何当踏破双芒屐，却向昆仑望故乡。

--【近代】王国维

+ 五十一


其实种族问题，在世界任何一个多民族国家都是一个敏感问题。最近在美国的南部各州，就发生了中学里非洲裔学生和拉美裔[fn:jdwtdgxt0670]学生的大规模打斗事件。这两个种族的冲突，主要原因是两族青年人的教育水平都比白人和亚裔要低，所以在低工资、低技能、非专业的职位上进行竞争，而这种工作因为美国工作机会向海外流失，反而机会较少，竞争激烈。再加上作为少数族裔的拉丁裔，也加入了享受政府名额有限的少数族裔优先计划的行列，在本来黑人垄断的福利大饼中，虎口夺食。这样，面对近十几年快速增长的拉丁裔人口，非洲裔黑人不得不忧虑。

[fn:jdwtdgxt0670] 即西班牙语群体，主要来源于墨西哥、波多黎各及中美洲的移民，白种或混血种人但肤色较深

另外一个种族冲突就是发生在黑人社区，曾经有犹太人去黑人区开商店，赚了黑人的钱后，就到富人区买房买地，完全对黑人社区的发展没有反馈促进贡献。而当犹太人赚够钱撤出后，韩国移民又故计重施，从而引发了在洛杉矶的黑人针对韩国裔的冲突事件。

其实中国的各种族间要和谐得多，比如在多民族区的云南，广西和贵州等地，很少听到这类民族冲突事件。而在青海和甘肃发生的藏族和回族等其他少数民族之间的不合，也不是很难解决。这个问题本身出现的原因，在于中国开放改革后，从严格限制的计划经济转为自由发挥的市场经济，在这新环境下，藏族这种传统从事农牧业，社会讲求等级次序的民族，就会不太适应，产生某种失落感。而遗传基因里充满了商业细胞的回族、撒拉族等少数民族等，简直就是如鱼得水。所以很快就会在几个民族群体之间的生活水平上出现差距。再加上一些少数民族和汉族的商业活动，像犹太人和韩国人那样，走进了藏民聚集区，但又社群活动相对封闭，这就使这种冲突性情绪逐渐蔓延。如果地方政府在这方面处理不好，就会有部分与国外配合的“有心”的知识精英或者宗教人士在其中操作，通过对藏民中知识文化水平低的农牧民，散布量身定做，精心编造的谣言，就可能带来很多原本没有预料的后果。

要解决这个问题，中国政府必须明白，靠市场经济的力量和自由竞争来提高人民生活水平的办法，并不完全适合中国所有的56个民族。其中一些少数民族缺乏足够的训练和教育，在职业竞争市场上本来就没有一个公平的起点。而且很多少数民族在基本的现代工商业的工作要求上，比如说定时的工作时间、按照工作成绩而定的奖金制度、从事服务业工作要“顾客至上”的商业道德等等，都不太习惯。比如说，藏族通常待人单纯友善，但当一个顾客七挑八挑，要求商店这样那样服侍自己的时候，有的藏民商人就会觉得自尊受到了影响。所以不能完全把中国东部理所当然的企业制度、商业文化，采取一种高高在上的态度强行安到少数民族地区，似乎要把“落后”的藏族逼进现代化的好日子。如果我们反感西方人那种不可一世高高在上，用人权、自由和民主来教训我们的态度，而对他们竖中指，那么我们就应该将心比心，站在藏族和其他少数民族的角度上，认真的听取他们的意见，和他们一起合作解决面对的问题。比如说，可不可以在藏区新开设的服务业上尽量避免采取汉族或其它少数民族独资的方式，可采取尽可能让多民族以多种模式共同入股（如以劳资关系员工持股，社会关系共同合伙入股等等方式）的合股企业形式。政府可以做的就是为这些多民族企业提供贷款上的优惠，并在就业上以雇佣当地藏民为主。如果当地缺乏足够的合适人选，就应该成立有针对性的职业训练计划，为藏民定做一些有针对性的就业培训，使他们能够享受到经济发展带来的益处，从而和其他民族的致富速度比较接近，这样就不会让他们有经济地位相对降低的感觉。


+ 五十二

多民族合作企业的方式，马来西亚是一个到目前为止相对成功的范例。本来，马来西亚的华裔，人数虽少，但却掌握了马来西亚大部分的经济命脉，因此和马来族裔的关系一向紧张，在社会不安定时，经常成为马来裔贫苦平民暴乱的主要攻击对象。后来马来西亚政府实行了华裔向马来裔让利的计划，即将华裔企业中分出少量股份，比如5%-10%的比例，让给马来裔人。当初，华裔对这个政策很反感，认为自己辛勤工作，却不得不免费去养一些好吃懒做的马来裔。但是他们很快发现那些能够拿到让利的马来人，都不是等闲之辈，而是马来裔社区里宗教和民意的领袖人物。这些人当年在清真寺里的几句话，或者在当地报纸上的几行字，就可以引发马来平民的大规模骚动。但当这些精英人物成了华裔商业的生意伙伴后，不光不再挑动骚乱，而且还经常出来平息可能发生的种族冲突。更重要的是，通过了不同民族的合作，大家开始利用不同方面的能力，齐心合力，进而推动了整个社区的发展。当然，近来，马来西亚因为本身是小国，不得不在国际经济浪潮中沉浮，尽管有强人马哈蒂尔勉力引导航船，但是由于在国际经济竞争中，不再是80年代那样的世界明星，所以过去形成的安定局面，近几年来有所动摇，但马来西亚起码能够在民族关系动荡不安的东南亚保持较为超然的状态，其中的经验，仍然值得中国加以参考。

所以，对走进藏区或长期乃至世代已经定居在当地做生意的少数民族，甚至汉族，应该明白，如果他们能在自己赚钱的同时也让当地的藏族分利，其实对自己生意的长期发展更有利。而享受这些分利，参与合作的藏族，必须是支持国家政策，拥护民族团结并在社区的民众中有影响的宗教和世俗人士。支持国家统一、民族团结和提高人民生活的民族人士，理所当然要享受经济发展的好处，而鼓吹分裂、民族冲突和扰乱社会次序的人士，就必须在各方面受到打击，这个政策决不能因为国外一些敌对势力的大声喧哗而有所改变。笔者认为中国政府没有必要对西方国家的杂音太过关注而投鼠忌器，结果反而鼓舞了国内的一些分裂分子的气焰，得寸进尺，得陇望蜀。

如果解决不好青海、甘肃和西藏本地藏族和其他少数民族之间因为某些商业误会而引发的矛盾，后果会相当严重。一方面，海外藏独势力可以将藏族经济生活提高慢于其他民族的情况，归罪于中国政府，并攻击中国当前的民族自治制度，借机鼓吹说什么如果藏人真正“当家作主”，比如说独立，就能真正的“保护藏人利益”。另一方面，会把主动权送给某些头脑比较冲动的宗教界人士，而他们在群众自发议论中发表“权威意见”的时候，往往用不可调和的宗教情结来代替容易妥协的具体经济诉求，结果使情况容易失控。比如在藏区流行的一些流言，从外地人看来非常荒唐。但是对青海和甘肃的藏族，曾有过当年军阀逼迫自己改变信仰的历史经历，又有信仰中传说的中亚伊斯兰教新兴力量在印度和中亚横扫佛教势力的痛苦记忆，就很容易相信。这样就把众少数民族之间本来容易解决的经济问题变成了你死我活的信仰问题。

随着中东在油价高涨而造成钱包鼓胀，阿拉伯国家，尤其是沙特阿拉伯对中国的投资会越来越多。而与阿拉伯人在文化、宗教和血缘上都有紧密联系的西北不少少数民族，靠娴熟的阿拉伯语，将会成为他们的经济伙伴和雇员。当年被解放军打败的军阀马步芳就是率整个家族流亡沙特阿拉伯，并最后入籍老死在客乡的（当然，沙特也可以说是宗教意义上的“真正家乡”）。可以想象，如果这些少数民族中的知识文化精英，看到海外的藏独势力背后是印度和西方的大力支持，在国外中东冲突局势升级的情况下，他们的一些亲阿拉伯文化精英就会相应号召针对西方和印度来开拓另一场圣战。而藏族对阿富汗的塔利班摧毁巴米扬大佛的行为已经非常气愤，而看到美军打击塔利班则感到很过瘾。这些问题落到了国际颠覆专家的手里，加以运作，又是一个火烧连环船，搞乱中国的契机。


+ 五十三

西藏和其他藏区的问题，有一些是由人口增长带来的。在过去的农奴制下，大部分的藏民必须承担领主和高级僧侣的奢侈生活，导致自身的消费物资非常缺乏，再加上工作条件恶劣，医疗卫生落后，藏族的婴儿出生死亡率高，藏族平均寿命大约35岁。而在共产党执政后，在国内的领主被改造成自食其力的人，许多僧侣还了俗，达赖喇嘛和他的一批领主和活佛们，逃到了印度，吃上了美国政府的供养，这些都使藏族农牧民的经济负担大幅度减少。加上中国政府在公众卫生上的努力，而藏族又不受计划生育的限制，结果导致全国的藏族人口增长了180%，从五十年代初的200余万人增长到今天的550万人，其平均寿命也增长到了72岁。可别小看这个72岁，因为世界最富裕和发达的美国人均寿命也是72岁。

但是，人口的增长同时也对西藏和其他藏区脆弱的天然环境造成巨大的压力。以青海为例，本来藏族牧民依赖天然的草场，可以靠自己放养的牛羊群，而有很好的生活。但随着人口的增加，放牧的人增多，草场在过度的放牧中开始沙化，这就要求限制牧民的放牧活动，把多余的人口转移到其他产业中去。而在这个过程中，对牧民的职业训练和心理辅导尤其重要。从传统的生活中转型，对他们的生活和心理都是一个重大的变革，如果处理不好，就会使其中的一些群体出现像美国的黑人社区和印第安人社区的状况，即很多人住在政府提供的免费房屋内，但由于工作和前途没有着落，演变成为社会不满动乱的根源。

另外一个问题就是藏族人口平均年龄很低，大约在20岁（维吾尔族也是这个情况）。通常这种年龄结构的社会都会有一定程度的动乱。中国内地平均年龄20岁时，大约是在70年代，我们都知道那时中国的社会情况。即使在文革结束后，也存在着大规模的年轻人打群架的社会现象。而美国平均年龄20岁时，正是风起云涌的六十年代，以反越战、吸毒和嬉皮文化为特征的年轻人向整个美国秩序掀起了挑战。如何将年轻人的骚动情绪通过一些正当的渠道，如流行文化中的反叛行为，或体育运动进行适当的引导，是政府需要考虑的问题。

如果中国政府不对这些问题有所防范的话，这两个因素就会很容易被海外藏独势力利用，来配合由部分寺庙喇嘛的分裂主义行为。如果看一下历次西藏和藏区的骚乱，可以发现主要的闹事者都是以前藏尤其是拉萨周边三大寺庙里的部分喇嘛为主。而班禅喇嘛治下的后藏地区则不会参与这些分裂活动。至于藏传佛教的噶举派、宁玛派和萨迦派，则比较关注于自身的宗教实践，对中国政府的宗教政策持支持态度，也不关心世俗政治的权利分配。

中国政府在处理这些闹事的寺庙时，由于过分在意西方国家的舆论和西方政府的态度，显得过于宽松。结果一些西方国家报纸就借机造势，为达赖喇嘛的海外宗教势力通过派出人员的方式来控制这些寺庙上出谋划策。这些势力，已经到了利用来自其他藏区的喇嘛学徒到这些大寺庙学习的机会来传播渗透的地步。而08年春，在其他藏区的寺庙里出现配合拉萨的响应活动，与这种海外的计谋策动，恐怕有密切的联系。


+ 五十四

其实喇嘛学徒在寺庙间串门学习，是藏族社区在历史上很传统的方法，效果是通过宗教上的师徒传承关系而达到宗教上的影响，并在客观上实现组织上的领导控制。中国政府如果在这方面不加足够注意和管理的话，就会使得这些年轻的喇嘛缺乏社会信息，偏听偏信，这就让美国控制的藏独势力留下了空间，通过散布精心编制的谣言，来煽动不明真相的群众冲击当地的社会次序。

中国政府似乎寄这样一种希望，即认为西方的舆论和公众之所以轻信达赖藏独势力的谎言，是因为他们对西藏和其他藏区的情况并不理解，如果中国政府想耐心的向他们介绍事实，以为他们就有一天会用比较客观的态度来看待西藏问题。

笔者认为这种希望是不实际的，残酷的现实是，现在的海外藏独运动完全由西方政府在背后运作，而作为海外藏独精神领袖的达赖喇嘛反倒只是一个傀儡，对这些运动势力并无真正的控制能力。在美国的藏独操作是由两个组织进行的，一个是“国际支持西藏独立”组织，得到美国民主党的左翼自由派势力如国会议长佩洛西等人的支持，而加入了很多好莱坞的过气明星来增加声势。另一个就是自由亚洲电台（具体来说是藏语和汉语部门）。这个电台号称民间组织，但其实是由美国共和党内的右派控制。这次事件，基本上所有西方媒体关于西藏的报道，都是这个电台提供的假消息。

这一左一右两个组织的资金来源都是美国国会下的国家民主基金会（National Endowment for Democracy，NED），而具体操作执行，都是由中情局的退休专家发挥余热。笔者的分析是，之所以在3月14日发动动乱，主要原因是利用这一事件，影响台湾的大选。即使这个主要目的没有达到，美国在今后的操作中肯定会加大砝码，继续向中国政府施压，最终达到中国在世界其他地方，比如苏丹、伊朗等能源地区向美国输送利益。

现在海外的藏独势力基本上可以分成三大部分：一个是达赖喇嘛和他的家族。虽然达赖喇嘛在中情局的宣传攻势中，已经成功的建立了以达赖喇嘛带点童真幼稚的灿烂笑容为形象的西方商业品牌。而他带口音的英文，听起来高深而朴素的佛学哲理，也已经把傻乎乎的西方普通人忽悠的死去活来，在西方如鱼得水。但是他的家族还是要考虑他圆寂后的家族经济问题。如果能够通过和中国政府成功谈判，使达赖喇嘛重建其在中国的尊贵地位，他的家族不光可以继续享受达赖喇嘛在海外的巨大商业利益，还可以在西藏和其他藏区的经济事务中占最大的股份，直到下一个达赖喇嘛家族的产生。当然在下一个达赖喇嘛的转世灵童的选择权上，还是会有一场争夺和政经利益的重新洗牌。所以可以说，达赖喇嘛的家族是海外藏独势力中最想和中国政府谈判和达成妥协的。

第二个势力是以西藏的流亡政府主席桑东活佛为领导的老一辈流亡藏人。这些人完全靠打达赖喇嘛的旗帜生活，当然其中的一些活佛也在西方国家发展自己的势力，以保证有一日三餐。这个势力是当年中情局支持的武装暴动和之后的游击骚扰的主要参与者，因此对最后被美国抛弃的经历有惨痛记忆，因此现在他们在配合美国的行动时，会比较注意是不是只是被人当枪使。

第三个势力即是年轻一辈在海外出生的藏人，以“藏青会”和“自由西藏学生协会”为代表。这些年轻人基本上是在美国、加拿大和欧洲各国长大，完全受西方势力的操纵，为西方国家的利益服务。现在海外藏独势力的内部斗争中，主要是这个势力攻击桑东政府贪污腐化，想抢权取而代之，从而在配合西方政府时能更为其所用，方便行事。


+ 五十五

中国政府在西藏问题上必须有一个现实的看法，就是美国在西藏问题上绝不会善罢甘休，而中国同美国在这个问题上的争斗会是一个长期的过程。因此中国在考虑其政策时，就不能投鼠忌器，必须在需要对分裂势力打击的时候，不能因为顾及美国的舆论捆绑住自己的手脚。更重要的是，当美国总统和国会议员接见达赖喇嘛的行为（包括西方其他国家的类似行为），被藏独各派势力夸张化，向国内有联系的分裂势力转递错误信息的时候，这些分裂势力会错误的认为西方政府将真正的支持他们的分裂和暴力活动而铤而走险，向中国政府叫板。如果中国政府在这方面由于对西方舆论的顾虑，而不能强势打击这些势力，那么就会印证了这些势力对局势的估计，从而变本加厉。其实西方政府支持藏独势力的主要目的是希望中国政府在国际事务中对西方国家让利来作为西藏问题的交换砝码，他们很清楚藏独势力并不能真正动摇中国的根本，因此在操作藏独的力度方面有很好的拿捏。

最近西方国家的政府和媒体在藏独势力的支持上有所收敛，一方面和中国政府做了适当让步，与达赖喇嘛的私人代表重开谈判，给了西方一个台阶下有关系。但其实更重要的原因是，中国民间和海外留学生的反西方情绪由于西方媒体和政客的操作动作过大而强烈反弹，使西方意识到他们可能在将来不得不面对一个对西方充满敌意的强大的中国，而胆颤心惊。同时由于美国军事强权在伊拉克和阿富汗的战局都不够理想，美国和西方经济影响力的衰退，西方希望能通过对中国施压的方式，依靠中国的实力在中东和非洲等地为他们的利益而出力。这就是所谓“ *负责任的共同利益者* ”的真正含义。

在全球层面上，西方当然会拿出他们自己的萝卜和大棒政策。大棒政策就是支持台湾和大陆继续对抗，干扰目前在“九二共识”下“模糊主权争论，创造双赢局面”的两岸良性互动，争取以清晰的“一中各表”而制造显性的“两国论”；然后支持整合疆独分裂势力，干扰中国的中亚和中东能源供应线；最后就是争取进一步掌控西藏局势，在中国和印度之间制造事端。

美国对西藏的操作，就是争取能够在拉萨建立领事馆[fn:jdwtdgxt0671]，直接与西藏内部的各派势力进行接触。现在美国的西藏情报来源和搅局操作，还是主要以依赖海外各派藏独势力作为中间媒介来进行，这对美国有两方面的不利。一是海外各派藏独势力会有意的错误传递美国的意图，误导内部的势力以谋求自己的利益，这样会造成美国的政策失误，使局面失控，损害美国在中国的整体利益。另一方面是海外藏独各派势力，为达到自身的目的，会误导美国政府，而令他们的决策行动与当地的实际情况脱节。只有美国政府能够直接和中国内部的各派藏人中的势力接触，有独立的情报来源时，才可以通过随时调整对不同派别的支持力度，来控制任何行动的规模。正如美国在台湾国民党和民进党的不同派别中进行操作，以到达台湾各党派任何行为都可以让美国利益最优化的目的。

[fn:jdwtdgxt0671] 这一要求在后来果然成为美国政府一个主要动作的方向。——编者注。


+ 五十六

笔者认为，国家在西藏的各种管理特别是宗教管理，需要明确传达两个信息：一是任何西藏内部在民族事务上反中国政府的力量，都是西方和海外藏独势力的无谓的牺牲品。即使中国政府在任何国际事务上向西方妥协，或者在任何条件上向海外藏独势力妥协，这些内部的分裂势力都不会得到任何好处。美国政府在本国和海外执行自己的操作的时候，从来遵从这个原则。中国在处理西藏和藏区的骚动时，如果骚动人员的诉求是和自身合理权益，特别是经济权益相关的，可以和政府讨论。但是，如果诉求是配合海外势力行动制造分裂活动、恐怖活动，就应该严厉打击，连带其支持网络一锅端。对参与闹事的宗教机构要有经济、人员上的重点管理，不要放任增长膨胀，对于海外返回的喇嘛和其他藏区的喇嘛要防止其从事政治性的颠覆活动。这也是为让这些地方获得正常的经济生产能力着想，让当地人们更多的参与生产建设而不是过度供奉寺庙，是光明正大理直气壮的。

二是借近些年来尼泊尔的政局的迅速变化，配合该国新执政的出身贫苦人民的共产党政府，加大在这个国家的投资，较快的提高该国人民的生活水平，以此督促尼泊尔新政府把其境内的藏独势力赶出该国。至于印度方面，虽然西方操作西藏问题的意图中不乏挑起中国和印度的冲突的用心，但只要不会导致大的危机，掌握一些小的和局部的事务，其实是不无好处的。中国可以做的是，给印度施压并力求让印度最后能将藏青会组织赶出其境内。具体的操作方式，可以是对印度吞并锡金的历史事件，表达某种保留或者关切，对锡金和阿萨姆邦的独立运动和当地的农民争取正当经济利益的自发抗争带来的社会动荡，和一些非政府组织一起，表达一种忧虑或关切。

在应对美国和西方在西藏的操作问题上，要充分总结民间这次在抵制法国家乐福和去法国旅游的成功经验，允许一些专门的以抗议西方为主要活动的非政府组织存在。一旦美国和欧洲政府在西藏问题上一有动作，这些组织就可以加以配合，造成一种中国民间的强大的反西方声势，对这些国家的政客进行阻吓。而且这种组合(阻吓)不能让其成为一种空喊，在2008年的火炬事件期间，法国一些奢侈品品牌非常嚣张的逆风公告，什么“抗议者没有购买力，不是他们的主要客户，自己的在华营业一切照常”等等，这其实是一种在民族情感和经济上的双重公然蔑视，造成了相当的负面影响。对于这样的企业，必须有实际的操作产生经济压力，让其经济利益受损，以便实现实质性的收敛。

西方在和中国的游戏中，基本上是以两手来对付中国政府。一手是用其政府在官方名义上与中国推行友好政策以确保自己获得丰厚的经济利益，一手是以个人或非官方组织名义出面的政府官员、国会议员、社会名流，以及政府控制的非政府组织，跳出来搞与中国为敌的动作，包括打击中国的海外利益，支持中国内部的暴力行动等等。如美国政府包括布什在内的高官和国会中佩洛西等领导人物，都公开支持海外的藏独和疆独暴力组织。在欧洲如英国、法国和德国，都有藏独和疆独组织活动。中国也应该向这些老师学习，可以考虑采取恰当形态，对于世界穆斯林世界以反西方为主的组织表达一种关心，保持相当的接触和经济上的往来。这对于增进和穆斯林世界的兄弟感情，削弱新疆的分裂势力，也有很大的好处。

在可以预见的将来，笔者认为中国将越来越难以用置身事外的方法处理国际事务。一厢情愿的希望自己能够安静的发展自己的经济，不被西方骚扰，是行不通的。西方国家是不可能平静地看着中国这个非我族类的国家成为世界上的主要强国的，不可能不试图在路上挖陷阱和拍砖头，更何况目前中国在经济上其实也通过出口外需与西方挂钩，不一定占据主动地位，所以可趁之机还是很多的。当然，西方知道光靠捣乱的方法风险性也很大，所以就会不断的祭出胡萝卜来，忽悠爱面子的中国政府和人民。

在笔者看来，中国政府和人民在奥运会前期宣传活动上已经被西方砸了一板凳，就要认情形势，做好准备（本文写于2008年7月初。——编者注）。由于中国人民非常爱国，非常为自己举办奥运会感到扬眉吐气，所以这样一个在国外看来很大程度上已经蜕化成现代商业运作的体育活动，就被人民给予了“中国人民站起来了，中华民族再次复兴”的大面子。笔者要提醒读者的是，咱们对于北京奥运会，一定要做好充分的估计，你看一个奥林匹克山上取来的火种被冠以圣火地位到处巡游的机会，全球的反华势力都要倾巢出动来砸场子。那么等到奥运会真正上演的时候，可以想象将有多少反华势力嚷嚷要冲进北京，借着你主人想要搞一个历史上最大最棒的盛会的时机，大闹特闹搞个乌烟瘴气了。[fn:jdwtdgxt0672]

[fn:jdwtdgxt0672] 由于较为充分的准备和较为严格的审查，北京奥运会避免了大规模的外国人借会闹事的事件。但是仍然出现了将分裂口号挂到北京奥运主会场外的高大路灯上的案件。——编者注。


+ 五十七

好在中国人民和政府已经有所醒觉，习近平同志在奥运临近前关于对奥运会要有平常心的表示就是一个好的开端。其实这次奥运会，为了应付海外敌对势力的破坏，对奥运会的保安措施，实际上已经造成了对旅游业的打击，使这次奥运会的经济效益大大降低。

在应付西方反华组织希望在北京奥运会上的搅局行为，中国的民众可能会有比较好的应对方式。西方在自己的媒体上搞洗脑可以概括成：“中国人民很善良，中国政府很流氓。西方政府要体谅，西方人民要逞强。”，就是有意区分中国的群众和政府，把中国的人民群众，用好莱坞勾勒弱势国家的人民的一贯手法，渲染成一批其实在民族问题上与政府持不同意见的群体，此所谓“中国人民很善良”。所以西方政府要对这批唯唯诺诺而不敢为的人民多加理解，此所谓“西方政府要体谅”，而所谓争头出气，就要靠我西方无数民间勇士，“勇闯北京”，来一次“仗义执言”，此所谓“西方人民要逞强”。所以所有西方媒体对中国的抹黑，都是以中国政府为对象。而来北京捣乱的西方政治流氓，如拿着西方政府工资的“记者无国界”之流的职业运动混混，在中国捣乱时，如果中国政府出面处理，就会招惹西方媒体的大肆群攻。中国苦于此，所以才会居然过分投鼠忌器，疏忽大意，居然让一些流氓在中国的长城上打出西藏独立的大旗。

中国的应对方式，就应该让西方人明白，在今天的中国，你西方混混不再可以像19世纪末那样，横行东方国家，独享随意耍流氓的特权，更不是今天的中国还要一味的让步，去“以中华之物力，结与国之欢心”。中国人民虽然善良和好客，不过13亿人民中，那也不缺乏头脑容易激动的青年。既然你们这些西方来的流氓要在北京搞事，那也就不能排除北京的一些小年轻因为“义愤填膺的情绪”，在这些白种流氓胡作非为的时候作出一些较为激动的回敬。在中国的警察赶到现场前，这些小年轻又适可而止，提前离场。中国政府会依法将这些触犯了中国法律的外国流氓拘留，同时发表声明，不鼓励群众采用自行激动手段来应对这些外国人违法活动——但是很遗憾，希望这些外国人好自为之，不要滥用中国人民的好客情谊，在中国的街道上乱打让中国人反感的标语旗号，胡作非为。其实，不要以为这帮西方流氓是什么亡命之徒，或者是什么敢于献身的理想主义者，他们只敢按西方“政治正确”的方针起哄，在所谓道德高尚的议题上走走街，如果让他们去纽约街头打出支持本拉登的标语出来，不知道还可不可以活着走出来。

这种灵活的法律运作方式，并不是没有先例，举一个美国的案例如下。在奥运火炬来到美国旧金山之前，曾有几个隶属于自由西藏学生组织的职业混混，违反当地的法律，阻碍交通，爬到金门大桥的吊索上挂标语。而大桥的工作人员不得不冒着生命危险，去把这些标语取下来。事后，旧金山法院对这个犯法行为进行宣判，判罚这些混混必须在社区组织做义务工作，可荒唐的是，他们需要做义工的社区组织，就是他们自己的自由西藏学生组织。从这里可以看到美国“法律至上”的具体运作方法。

而担任旧金山警察保安活动总顾问的戴利警长，对记者谈到了他本身的亲身经历。戴利曾是美国特种部队军官，退役后曾出任过美国前总统克林顿的保镖，后来出任旧金山一个分局的主任。在一次藏独分子在中国领事馆前进行的未经批准的非法静坐抗议活动中，戴利带领他的下属，去规劝抗议者结束非法活动。结果在他试图劝说一个喇嘛时，对方突然从袖口中掏出一个木棍，冲着他的头上就是一棍子。经验丰富的戴利吃了个大亏，因为他以为西藏喇嘛都是热爱和平的善良人士。让他更恼火的是，这个打警察的凶僧被逮捕后，因为美国上层人士的干扰，检察官拒绝起诉，最后无罪释放。戴利对旧金山警察的建议是，必须把藏独的喇嘛当作恐怖分子一样对待，严加防范，不然吃了亏都有苦说不出。[fn:jdwtdgxt0673]

[fn:jdwtdgxt0673] 参考美国《星岛日报》对于戴利警长的访谈。

中国在对待这些政治流氓的时候，也不能按常理出牌。必须改变过于顾及西方的舆论而不能有效的维护自己的利益的情况出现。


+ 五十八

除了要应付西方的上述大棒政策，中国需要提防的是西方拿出最大的一颗大萝卜，来满足中国人的虚荣心，这就是以允许中国加入西方八大工业国这个大亨俱乐部，用西方既定的规则，令中国为西方的利益服务。在当前西方在世界各地的影响力大幅减弱，需要中国的帮忙才可以在世界的很多地方维持其利益的情况下，这个大胡萝卜很可能会适时送上。如果中国人满足于这种虚妄的做世界大国的美梦，就会傻乎乎的牺牲自己的利益，成为西方国家的帮凶。

中国在世界事务上的政策，还是要用明初的九字真言“ *高筑墙，广积粮，缓称王* ”为基石。首先要“高筑墙”，增加国防力量，建立一支“中洋”海军（相对于中国目前的近海海军和美国的远洋海军而言，覆盖能力介乎其中的海军），能够保护中国的海外利益和中国从本国及巴基斯坦沿海到中东和北非的海上新丝绸之路，必须能够做到防止“当代匈奴”来扰乱这条生命线。中国军队除了在潜艇和护卫舰上要加速国产为主的发展，还要充分运用友好国家的支持，通过贸易上的互利共同体，把中东和北非的国家的利益同中国的利益绑在一起。

“广积粮”可以从两个方面来考虑：一个当然就是发展生产经济，这恰恰是中国人做得最好的一点，另一个就是要进行长远的战略物资储备，比如在东南亚和非洲发展以中国市场为主的粮食基地，补偿中国因为大规模城市化带来的耕地损失。在原材料上，中国应该大量动用手上过多的美元储备，在中亚、东南亚、南亚和北非购买矿业资源，在美元进一步大跌前，抢占全球的资源。在石油资源上，长远来说，中国应吸取美国的教训，建立一个以替代能源为主的经济；在目前，就应该充分利用一些产油国家，如伊朗、苏丹、委内瑞拉等国和西方的争执，在油价上取得优惠，支持中国经济的继续发展。

当前高居不下的油价（本篇写作于2008年6月底7月初，时逢国际原油价格达到接近150美元的高点。——编者注。），会对西方国家，尤其是美国的经济造成极大的打击。中国必须让反美的产油国知道，如果中国得不到相对于市场现价大幅削低的石油供应，就会导致经济衰退，则中国就无法为他们提供必要的保护，那么他们就可能成为西方强权下一个军事干涉的目标。楚人无罪，怀璧其罪，这个道理估计这些国家的领导人也听得懂。如果他们的目的是要打击以美国为首的西方经济，他们大可以一方面增加对中国需求的石油输出，另一方面继续减少对西方为主的国际市场的供应，让西方那些投机基金在把美国股市和房市炒死了之后，再在石油期货市场上把油价炒过150美元一桶，令按照国际油价定价能源的西方消费者为此买单。

且中国在这些产油国家，比如说非洲一些国家的贸易，是用中国的基建工程换取当地的能源。某种意义上来说，是一种易货贸易安排。随着能源和原材料价格上涨，建筑工程的价格也相应提高，应该可以保证中国经济不受打击。在国内政策上，不应该实行政府补贴的汽油低价格政策，而是应该放开以消费者为主的汽油价格，扼制耗能交通方式如大排量私家车的发展，但在生产和基本民生的耗油，例如农业、能源、公共交通运输等等，应该根据各自重要性采取对应的退款支持政策。在能源效率方面，则必须通过严格的管制，使汽车等耗能品的能耗效率达到高水平。


+ 五十九

“缓称王”是中国人最需要考虑的问题。这并不是说要坚守邓小平所说的“决不出头”，因为中国已经不可能置身于国际政治之外自己过自己的小日子；而是说中国要把自己定位在一个穷国，一个发展中国家。即使在十年，二十年后成为世界第一的经济体系，人民生活到达小康水平，中国的人均收入仍然属于发展中国家，或自己要坚持自己还是发展中国家的一员。因此中国要拒绝参加西方八国组织，应该出头成为发展中国家的领袖，在与非盟、东盟、拉美的Mercosur[fn:jdwtdgxt0674]，还有阿拉伯联盟之间牵线搭桥，促进南南合作。当然也要与美国为首的西方国家在南北合作和对话中，就全球贸易、环保、能源合作、防治温室效应上寻求合作。

[fn:jdwtdgxt0674] Mercosur，也称南方共同市场，正式会员包括阿根廷、乌拉圭、巴西、巴拉圭、委内瑞拉五个南美国家，联系会员国包括智利、哥伦比亚、厄瓜多尔、秘鲁、玻利维亚五国，另外还有观察员国墨西哥。基本覆盖了所有拉美重要国家。

中国在联合国安理会常任理事国中是唯一一个在近现代没有对世界其他国家进行殖民的大国，因此可以被众多发展中国家看作是安理会中唯一和真正代表自己利益的大国。在联合国改革方面，对增加日本和德国成为常任理事国的提议，中国应该持保留态度和有条件的观望，因为这两个国家即属于西方阵营，又是美国政治傀儡。中国更应该支持发展中国家的代表或者国家联盟，如阿拉伯联盟、非洲联盟以及未来将可能出现的拉美联盟获得安理会常任理事职位，让巴基斯坦、沙特阿拉伯、埃及、南非、苏丹、巴西、墨西哥和委内瑞拉等国，都可以在安理会轮流坐庄，使联合国做到真正多元化。

按照这种思路，所以说中国对于目前与欧洲联盟的关系必须重新审视。前几年，因为美国新保守派一意孤行，而法国在希拉克，德国在施罗德的领导下，强调欧洲与中国的战略伙伴关系，发展多极社会，防止美国独大，这是一个正确的道路选择。但当美国势力衰退，中国势力兴起时，新上台的德国总理默克尔和法国总理萨科齐，出于一些意识形态上的原因，不光重新向美国靠拢，开始向中国叫板，而且还在世界事务中，担当反华马前卒的角色。相比较于新保守派已日益出局，对华日益灵活的美国政府，默克尔和萨科齐这对黑风双煞，反倒是有“比布什更布什”的架势。

在这种情势下，中国政府在拉萨事件后对欧洲主要国家一些举动的政策，却是仍然想以过去的“分而攻之、各个击破”的策略来达到目的。可是中国人需要明白的是，中国和欧洲之间，并不是一些中国的国际问题专家所宣称的那样没有利害冲突，可以做天然的盟友。

中国，与欧洲和美国的冲突，根源在于对当前这套经过西方世界数百年的杀戮和掠夺所建立的国际既有秩序。在这个现存的国际秩序中，只占世界大约四分之一的西方世界，要消费占世界四分之三的资源。现在你中国以占世界五分之一的人口，要想过小康社会，在2020年即使只达到大约人均收入4000到5000美元，也就是算成购买力平价仅相当于西方的三分一的水平，也势必会加入现在的世界资源大饼分配。这简直就是从无论是欧是美的西方人那宽裕的饭碗里虎口夺粮，是不可以忍受的大逆。只要看一下欧洲对中国在非洲投资的态度，就可以知道其中的奥秘。

除非中国人可以发明一种新的经济运行方式，即依赖于可再生的能源，和新型的建筑材料，从而避免在石油、天然气、各种金属矿石上和西方极度浪费的消费文化展开残酷竞争，否则，中国人就不可能和西方人成为真正的盟友。而由于美国开始调整政策，不再如过去那般口出狂言大谈新欧洲优秀啊旧欧洲没落，不再忙于把法国炸薯条改成自由炸薯条[fn:jdwtdgxt0675]，中国和欧洲之几年前在美国新保守派攻击欧洲的背景下确立的伙伴关系，也开始慢慢对欧洲失去其重要性。再加上美国现在开始允许法国等欧洲国家参与伊拉克石油分赃，法国又在阿联酋开设海军基地，这些因素都会使欧洲对中国的态度发生微妙的变化。

[fn:jdwtdgxt0675] 指美国国会在伊拉克战争后，出于对法国在联合国对美国要求联合国发兵的阻挠的愤恨，通过法案决定将“法国炸薯条”改名“自由炸薯条”，此事成了国际笑话。


+ 六十

因此，欧洲在应对中国过去那种“分而治之、以夷制夷”的策略上，采取车轮大战的对付方法。2007年就由德国领军对付中国，默克尔带头接见达赖喇嘛，开启08年春的拉萨暴乱序幕。中国缺乏思维弹性的“专家”们，就得出“德国的影响力在世界范围内不如英法”的谬论，让中国开始在经济上教训德国，却把大块经济馅饼扔给来访的萨科齐和布朗。没想到喂饱了白眼狼回去后，欧洲就转由法国萨科齐来唱去年德国的高音部，英国布朗唱中音部，默克尔唱低音部。只见萨科齐高调见达赖喇嘛，布朗低调见达赖喇嘛，默克尔倒是找个借口避开锋芒。

眼见新的三重唱，中国“专家”们的反应就是突然一百八十度大转弯，宣称什么与德国的关系已经恢复正常，法国的行为不必多虑，据说原因是“法国在欧洲的影响不如德国”，督促中国政府要准备对德国扔经济馅饼。当然，因为法国和英国在中国拿到的超巨型大饼可以吃上好几年，所以这个新三重奏可能还会唱一段时间，此间英法就可以继续在世界上展开打击中国的行动。而等到中国在未来两年喂饱了德国之后，才再次轮到德国出马。

中国人实在该变得聪明一些。既然欧洲在世界事务上已经重新成为美国的马仔，那么中国就应该只把他们当作美国的马仔。在国际事务上不需要在欧洲的身上浪费时间和精力，只需要和他们的主子打交道，谈妥协定，让他们的主子回家自己传达会议精神就行了。

在这方面的谈判策略上，我们倒应该向朝鲜学习。朝鲜人需要同时和美国和日本谈判，它对日本的喋喋不休只回一句：你日本不过是美国的一个州而已，根本不需要来参加什么谈判。我和美国谈什么，由你老爸回去给你打声招呼就行了。

在如何应对中国的态度上，美国也有不同的分歧。意识形态旺火上身的共和党总统候选人麦凯恩宣称要把俄罗斯从西方八国俱乐部踢出局，而且永远不让中国加入，但就要吸取印度这个“世界最大民主样板”入会。这位老朽不知道，如果中国不买你八国俱乐部的账，掉头自己开一家新夜总会的话，你那个俱乐部就会变成和世界银行、国际货币基金组织一样，门可罗雀，名存实亡。最近美国一些学界人士的新提议，倒值得中国学界人士好好研究加工。这个新建亦(议)就似乎所谓建立以美国和中国为主的G2俱乐部，将中美之间定期进行的战略经济对话提升到一个对国际政治各方面有举足轻重作用的主要政策的出产源。当然，美国这套想法，就是由美国和中国共同管理世界经济和安全事务，中国可以作出太极顺手，借力用力，自己发挥出一套新的原则。

具体说来，中国应该就势“支持”美国的这一想法，添加进自己的内容。作为一个代表世界大多数发展中国家利益的大国，中国可以提出增加地区性国家组织在地区性事务的主导作用的建议，并把中美两个大国的作用，定位成“在地区性国家组织之间进行协调、引导”。比如说中东的伊朗问题，中国可以主张应该主要由欧佩克组织和阿拉伯联盟牵头，在“欧-阿”框架内找出一个合理的解决方法，而美国和中国来协调，但都不起决定性的作用。再如非洲的津巴布韦政治危机，中国要坚决反对西方主导的制裁甚至军事干预的政策，而应该主张依靠非洲联盟对这一本地事务的处理意见，来决定政策导向。

总之，中国在世界事务上，应该逐渐排斥欧盟对非欧洲以外的事务的发言权，不需要尊重这帮黑社会的自以为可以得到大佬待遇的小喽罗。他们既然只不过是美国全球事务的一个马前卒，那么就只应当得到马前卒的地位，中国在国际事务上即使要寻求共识，也只需要同美国去寻求共识。


#+begin_center
【写作日期】2008年6月29日——7月4日            
#+end_center
