# -*- org -*-

# Time-stamp: <2011-08-27 23:26:31 Saturday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 摘录


** 大变局

如果考虑到国际大势的变化，世界的经济，文化和政治中心向东亚漂移是一个不争的事实。而在这一大变局中，美国的超强角色自然会衰退，但是瘦死的骆驼比马大，美国的国土、人口和经济实力，还是比较可观， *如果美国能及时将其全球力量收缩，而不是再到处在全球扩张，那么它就不会象历史上所有的帝国一样，轰然倒塌。美国还会在一个多极的世界次序中扮演一个重要角色，而真正受到打击的反而是欧洲。*

在东亚为核心的新次序中，最为重要的是中国、日本和印度的经济、政治和外交关系。当这三个国家实现以中国和印度的独立自主的经济为基本，配合上日本在观念中的脱欧返亚（当然美国重兵驻境，有一定难度）时，欧洲的地位就会大幅降低，最后与崛起的阿拉伯、俄罗斯、巴西和南非处于同一层次。

这对西方在世界资源中享有的垄断是一个噩梦。所以如果能够在亚洲的未来三强中制造事端，以二桃杀三士，引出个火烧连环船，应该是上上之选的对策。


图5.3 具有挑战力的“亚洲三士”与能破坏离间三者的“二桃”

而这个“二桃”，从今天的情况来看，就是石油、天然气代表的能源，以及其他各种原材料。如果美国和北约可以控制住中东，解决伊朗，北上中亚，然后南下中北非，就可以控制住亚洲三强的命脉。至于中南美洲，通过浩瀚的太平洋施加影响恐怕还是一个梦想，只有在二十年后，也许集三强之力，才可以和美国领军的北约对抗。但是三强可不可以熬到那一天，出现那样的完美整合，还是互相之间未及达成共识就已经咬个你死我活，都是未定之数。

当然，从西方的角度来看这个问题，三强中除了中国之外，印度和日本不足为惧。日本在政治和军事上仍然是美国的殖民地，在经济上虽然是世界老二，但是日本人民的卖命工作，经常成为替美国和欧洲人民付账的提款机，比如第一次海湾战争中的大部分军费都由日本人支付，甚至出现了支付期间因为兑换率变化使原来答应的日元金额兑换成美元后缩水造成的前后差额也要补上的事情。日本人非常恼火，但都不得不忍气吞声。而当日本经济一旦过强，就遭到了美国和欧洲的口诛笔伐，责令悔改，一直到日本陷入经济衰退为止。日本作为一个岛国，市场在外，资源在外，能源在外，一切命脉取决于美国人的脸色，从美国的角度来讲，日本颇象英国的地位，以日本来平衡亚洲大陆的中国就是学以英国来平衡欧洲大陆的法德联盟。只不过唯一的区别是，英国是美国的堂弟，日本只是美国的马仔。

在南亚的印度，则是另外一个不同的情况。印度邯郸学步，继承了英国人替他们建立的无法运作的民主体系，过去几十年一直无法有效的解决国家的发展问题和周边的安全环境问题。凭着一批绝顶聪明的印度软件工程师，以及印度人民作为数学发源地的底蕴，印度终于在全球化的今天可以在外包业中异军突起，在电脑和医药等行业上可以有所建树。但是印度的体制造成其官僚体系腐败，效率低下，利益集团在频繁的选举中不断侵蚀公共利益。在周边关系上，还是未能完全处理与巴基斯坦、孟加拉国和斯里兰卡的紧张关系，而且印度的战略界和军界，仍然为1962年的中印战争的失败而耿耿于怀，非常容易陷入美国和西方国家利用印度抗衡中国的挑拨离间。印度有限的海军力量却因为美国在印度洋区域的薄弱而在本地独占鳌头。也许，美国在巴基斯坦的介入还不是太顺手，在缅甸的颜色革命也不成功，在斯里兰卡通过上次南亚海啸的渗透也没有结果，这些超级大国的失手让印度可以暂时心安，但中国的任何举动，哪怕是商业的动作都能让印度精神过敏。67


** 巴基斯坦

南部的俾路支独立运动

** 世界主要问题

*** 非洲
津巴布韦政治危机
*** 中东

欧偑克组织

阿拉伯联盟
**** 伊朗



** 企业

西方的五大石油公司，即美国的埃克森、雪佛龙、英国的BP、英荷的壳牌，加上法国的道达尔（也许这是为什么法国新总统萨科奇让人觉得比布什还布什的原因）

英国石油公司（British Petrol，简称BP）

** 人物


   
*** 伊朗
**** 摩萨台首相

伊朗总理
**** 巴列维国王

**** 霍梅尼教长

1979年：伊朗革命



*** 印度-1947年独立

**** 尼赫鲁
** 制裁

*** 美国-伊朗

战略目的：占领伊朗，如果不能靠自己的地面部队，就得扶持亲美的伊朗政府。

**** 一般贸易
**** 原油出口和汽油进口


** 语

+ 一条铁链的强度就在其最弱的一环上决定。


** 词

中印区（Chindia）

中中区（Chime）
