# -*- org -*-

# Time-stamp: <2011-09-21 13:28:43 Wednesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:3

#+STARTUP: indent

#+TITLE: 数学-科学的女皇

#+AUTHOR:

#+STYLE: <link rel="stylesheet" type="text/css" href="/css/org.css" />



#+HTML:<div class="sidebar">
+ 数论-数学的女皇
+ [[file:stochasticprocess.org][随机过程论]]
+ [[file:combinatorics.org][组合数学]]
+ 数学应用
#+HTML:</div>


   数学家高斯说：“数学是科学的女王。”

    数学家哈尔莫斯说：“数学是创造性的艺术，因为数学家创造了美好的新概念；数学是创造性的艺术，因为数学家的生活、言行如同艺术家一样；数学是创造性的艺术，因为数学家就是这样认为的。”

    哲学家康德说：“数学科学呈现出一个最辉煌的例子，表明不用借助实验，纯粹的推理能成功地扩大人们的认知领域。”

    物理学家爱因斯坦说：“纯粹数学，就其本质而言，是逻辑思想的诗篇。”“数学受到高度尊崇的另一个原因在于：恰恰是数学，给精密的自然科学提供了无可置疑的可靠保证，没有数学，它们无法达到这样的可靠程度。”

    事实上，无论哪种流派的科学史，都不约而同地赋予“数学是一切自然科学之基础”的尊崇地位。一般说来，数学的对象可以包括客观现实中的任何形式和关系，正如伟大的科学家伽里略所说，自然界这部伟大的书是用数学语言写成的。回顾科学技术的发展历史，物理学、力学、天文学、化学、生物学等领域的许多重大发展无不与数学的支撑息息相关，数学为它们提供了描述大自然魅力的语言与探索大自然奥秘的工具，牛顿力学（特别是万有引力定律）依赖于微积分发现，爱因斯坦的相对论则与黎曼几何及其他数学的发展紧密相关。

    身处高科技时代，自然科学的各个研究领域都已进人更深的层次和更广的范畴，这就更加需要数学，许多一度被认为没有应用价值的抽象的数学概念与理论，出人意料地在其他领域中找到了原型与应用，数学与自然科学的关系从来没有像今天这样密切，数学的许多高深理论与方法正在深人广泛地渗透到自然科学研究的各个领域，例如，分子生物学中DNA结构的研究与数学中的纽结理论有关，理论物理中的规范场论与微分几何中的纤维丛理论紧密相关……当代自然科学的研究正在日益呈现出数学化的趋势。

    数学不仅是自然科学的基础，也是重大技术革命的基础。大家都知道20世纪最伟大的技术成就首推电子计算机的发明与应用，它改变了人们的日常生活，使人类进人了信息时代，但是你知道吗，在电子计算机的发明史上，里程碑式的人物——图林、冯诺依曼都是数学家。而且，在当今的计算机的重大应用中也无不包含着数学的贡献。不仅仅是电子计算机，从医学上的CT技术到中文印刷排版的自动化，从飞行器的模拟设计到指纹的识别，从石油地质勘探的数据处理到信息安全技术，在这些形形色色的技术革命的背后，数学都扮演着不可缺少的角色。数学在这些领域内既不是什么增补营养的“钙片”，也不是一种可有可无的参考，而是真正能解决问题的“一把锋利的剑”。因而，美国国家研究委员会把数学与能源、材料等并列为必须优先发展的基础研究领域。

    今天，信息技术己被广泛应用于人类生活的方方面面，使我们无处不感到她的存在。然而，享用这些成果的人们却往往只看到了技术成果，而看不到其背后的英雄 —— 数学。正像前美国总统科学顾问艾德华·大卫所说的，“很少人认识到当今如此被广泛称颂的高技术在本质上是一种数学技术”，尽管这句话可能会引起争论，但是，他并不是要否定各种硬件技术发展的意义，而是在强调只有很少人认识到数学在高技术中的重要性，强调高技术中数学的不可或缺性。从这个意义上讲，他的见解无疑是正确的，并且是富有远见的。

信息技术的发展使得数学在科学技术中的地位发生了重大变化，使得数学不再只是通过其他基础学科间接地应用于技术领域，而是广泛、直接地应用于各种技术之中。如今，大规模科学计算与计算机模拟在科学研究和技术开发中扮演着十分重要的角色，人们把她与理论分析、科学实验相并列，称之为科学探索的三大手段。在某些领域，科学计算已经替代或部分替代一些价值昂贵的实验，大规模科学工程计算正在材料科学、流体力学等研究中，以及航天、军事和大型工程设计中发挥着巨大作用。同时，数学也已广泛深人到社会科学的各个领域，比如，用数学模型研究宏观经济与微观经济，用数学手段进行市场调查与预测，用数学理论进行风险分析和指导金融投资……如此种种在发达国家已被广泛采用，在我国也开始受到重视。在经济、金融理论研究上，数学的地位更加特殊——诺贝尔经济学奖获得者中，数学家或有研究数学经历的经济学家占了相当大的比例；当今在华尔街叱诧风云的许多人物，都曾出身数学专业。

