# -*- org -*-

# Time-stamp: <2011-08-05 18:11:45 Friday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+title: 04年以来的大国斗争回顾

#+STYLE: <link rel="stylesheet" type="text/css" href="css/org.css" />

* 04年以来的大国斗争回顾



** 【金鸿评论】04年以来的大国斗争回顾（上）

[2010-09-05 22:22:59]

#+HTML:<h3><strong>
谨以此文献给*共*和*国*61岁*华*诞。
#+HTML:</strong></h3>

【金鸿评论】先从台湾这个内政问题说起。

04年320台湾大选[fn:jinhong0101]后，陈水扁靠着两颗子弹连任，泛蓝上街，台岛一片混乱。随后切尼访华，以台湾大乱逼北京在伊拉克问题上合作（
#+HTML:<a>台湾大乱和独立一样，都是北京必然出武的条件</a>
#+LaTeX:\red{台湾大乱和独立一样，都是北京必然出武的条件}
），结果北京不为所动；切尼回去之后，马上抛出了一中是神话的观点支持台独。感觉到了被动的北京开始着手准备应对的手段，

这就是朝核牌。北京马上邀请金正日访华，承诺对朝鲜进行全面的军事保护和经济支持；老金心领神会，回国后马上着手准备“核材料”。

之后，陈水扁开始准备台独味十足的520就职演说，向北京施压以配合华盛顿的伊拉克政策，北京则发表了强硬的517声明，准备以武力收拾台独，在中东被缠住了手脚的美国无力当即与北京摊牌，只好暂时压住了台独的冒头。

随后，北京带头在伊拉克问题决议案上出手，狠狠修理了华盛顿一回。7月份赖斯访华，寻求北京在伊拉克问题上对华盛顿的支持，结果北京依然不同意。华盛顿再次举起了台独牌，不过，这次是以台湾问题国际化的面貌出现的，带头试水的是新加坡的二当家李显龙。李公子在北京的再三警告声中以副总理的身 份对台湾进行了一次“私人访问”，得到了陈水扁的高调欢迎。

为了防止是其他东盟国家跟着新加坡学样子，北京决定杀鸡吓猴，给新加坡一个教训。北京一面掐断了大量与新加破合作的经济项目，一面把凯山防空导弹系统连同技术一起卖给了新加坡的老对手马来西亚。在北京的文攻武迫之下，李公子扛不住了，只好出来反台独，承认台独是东亚不稳定的最大根原。此言一出，台湾立即恶语相向，大骂新加坡为鼻屎大的国家。看到了北京强硬态度的澳大利亚马上明确表态，不会与美国一道协访台湾；菲律宾更是与北京签订
了军事合作协议，北京的出手大获成功。

北京与华盛顿在台海激烈交锋的同时，在朝鲜半岛上也都没闲着：在北京明确表态对朝鲜提供军事保护并支持其经济改革后，日本韩国都感觉到，朝鲜问题不可能按美国人希望的方式解决了，如果韩日不参与朝鲜经济改革，中国也有能力做到，自己（韩日）只会失去一片大市场。要知道，对于内需已经饱合的韩国和日本来说，朝鲜这片市场是非常有诱惑力的，如果有机会，韩日两国绝对希望能从朝鲜的经济发展中分一杯羹。这时，韩国执政的是亲朝的卢武铉，态度自不必说；就连亲美的小泉纯一郎也对朝鲜的改革大为动心，一度打着解决绑架问题的旗号想要访朝。

7月份，中日俄三国在海参崴开始商量建立东北亚运输走廊的事情，准备搞东北亚经济一体化[fn:jinhong0102]。这时，如果东北亚的经济整合真的开始了，那美国的东北亚政策就完全破产了，因为按美国的计划，是要把俄罗斯挡在朝鲜半岛以外、也不准日本经济登陆朝鲜半岛的，现在俄罗斯却要和日本在朝鲜半岛上会师了，这还了得？

华盛顿决定扭转局面。在韩国亲美派的配合下，闹出了韩国非法制造浓缩铀的新闻，一下子刺激了小泉。试想，韩国都可以搞浓缩铀，那日本是不是也可以？只要想办法让美国点头同意自己跨进核门槛，以日本的经济实力还不马上就可以成为一个独立的强国？心存幻想的小泉转身投入了布什的怀抱，期望以自己的献身（全力反华）以换取日本的自由之身，当然，最理想的局面是让日本成为美国的全球合作伙伴。

美国用核诱饵诱惑日本自然是在玩火，北京决心反手拆穿，让日本瞧瞧美国是否真的允许他有核。9月9日，朝鲜北部发生了一次剧烈爆炸，出现了一朵巨大的蘑菇云。之后朝鲜解释说。那是为了修水电站在炸山，不是核试验（实际上爆炸的地方根本不具备修水库的条件）；一心想跨过核门槛的日本则一口咬定那就是核爆炸；华盛顿却拼命地否认说那绝不是核爆炸。通过这次试探，北京彻底明白了美国的底牌，那就是
#+HTM:<a>绝对不会因为朝鲜有核、韩国有核就让日本也有核</a>。
#+LaTeX:\red{绝对不会因为朝鲜有核、韩国有核就让日本也有核}。

到了10月份，陈水扁发表了挑畔味十足的双十致词[fn:jinhong0104]，跟着朝鲜半岛局势也急转直下。北京再次放风进行东山岛军演[fn:jinhon0103]，华盛顿则披露了两份军事打击朝鲜的作战计划，一时间从台湾海峡到朝鲜半岛，随时都有爆发战争的可能。为保朝鲜安全，北京用三万解放军调换了中朝鲜边境的武警部队。之后，小布什为保大选平安过关，再次压下了台独的势头。

布什成功连任之后，又继续让陈水扁搞台独。受够了台独折腾的北京开始制定《反分裂国家法》。接着，北京反手一击，在欧伊会谈问题上表态支持伊朗拥有和平利用核能的权利，反对对伊朗进行任何形式的制裁，强力阻击了华盛顿的伊核政策。这时，华盛顿在中东的局面变得更加被动。为了能集中精力实现拿下中东（稳定伊拉克、摆平伊朗）这一最主要战略目标，只能避免眼下就和北京摊牌，于是，华盛顿又开始高调的反对台独。当然，华盛顿是希望自己的反台独能让北京停止制定《反分裂国家法》，可是北京不为所动，坚持做自己该做的事。

05年3月14日，《反分裂国家法》出台。这时，中国有了一部正面碰撞美国《与台湾关系法》的法律。在此之前，每逢台海有事，美国必拿《与台湾关系法》说事，以此为依据，或明或暗表示会协防台湾，替台独分子打气鼓劲。其实，华盛顿原是希望能搞和平台独的，现在北京划出了独则必打的红线，华盛顿再敢耍嘴皮子把台湾搞独立了那可就得真帮忙了。所以，自从《反分裂国家法》出台以后，美国就再也不拿《与台湾关系法》说事了。

和平台独被《反分裂国家法》堵了路之后，伊拉克局势又迟迟搞不定，困境中的华盛顿，开始谋求东亚的稳定。这才有了连宋先后登陆。

【金鸿评论】到了05年的大年初一这一天，日本宣布把钓鱼岛上的灯塔收归国有，开始在钓鱼岛主权问题上挑畔中国。之后，陈水扁、李登辉积极配合，蓄谋建立美日台军事同盟（支持台独）。这时，传说中的朝核牌被人打出了，朝鲜宣布自己已经拥有了核武器，并无限期退出六方会谈。从那一刻起，华盛顿手中的台独牌和北京手里的朝核牌开始了激烈的交锋。

这一次华盛顿在以“支持”日本拥有钓鱼岛主权换取日本的协防台湾。美国不会为了台湾与中国开战的，但美国非常希望中国武力收台时日本能加入战争。其实，华盛顿对日本拥有钓鱼岛主权的支持，仅仅限于地下，在每一次中日之间在钓鱼岛问题上面临摊牌时，华盛顿总时及时的把自己的态度调整为：美国在钓鱼岛归属问题上的立场，就是没有没有立场。

#+HTML:<a>华盛顿打台独牌的目的是用可能的台湾独立去逼迫希望全力搞经济建设的北京在他希望的国际际问题上让步</a>
#+LaTeX:\red{华盛顿打台独牌的目的是用可能的台湾独立去逼迫希望全力搞经济建设的北京在他希望的国际际问题上让步}
。而北京的朝核牌，则是
#+HTML:<a>在日本与美国之间砸楔子</a>
#+LaTeX:\red{在日本与美国之间砸楔子}
。既然朝鲜有了核武器，那朝鲜的敌人日本是不是也该有核武器才能保证自己的安全？而这是美国绝对不允许的事情，日本有核意味着日本将成为一个独立的国家，而不再是美国的殖民地，这对美国而言是绝对无法接受的。要压住日本的核野心只能靠北京帮忙（至少是不再刺激日本）这样，日本一下子从华盛顿对北京施压的工具变成了北京对华盛顿施压的工具，北京顿时反客为主。

《反分裂国家法》出台后，华盛顿在台独牌上失分很大，便想另找一个地方扳回来，这个地方就是中亚。华盛顿迅速在吉尔吉斯斯坦搞成了郁金香革命，接着又在乌兹别克斯坦搞了一场颜色革命，结果在北京的支持下卡里莫夫把革命分子给镇压了。

策划颜色革命不难，只要能找到一帮与自己志合道合的人，再给些活动资金，在他们革命的时候帮着摇旗呐喊即可。真正困难的是革命成功之后的政权稳定问题，——你得把老百姓养活好，让他们过得比革命以前更富足，更快乐；否则，用不了多久反革命就会爆发。给革命分子发钱美国给的起，可养活这些小国的老百姓，那是他能给的起的了，也不是他愿意做的了。那么，美国应该怎么做呢？当然想办法让这些小国家自己养活自己。于是，美国就瞄准中亚的石油资源搞了一条巴杰管道，希望靠卖这些国家的资源把这些国家的老百姓养起来。

巴杰管道是从阿塞拜疆巴库到格鲁吉来的第比利斯再到土耳其杰伊汉的石油管道。有了这条管道，就可以把里海地区的原油输送到地中海国家去消费。这样，中亚小国的石油出口就可以绕开俄罗斯，俄罗斯对这些小国的控制力也将逐渐丧失。有了这条巴杰管道，可以帮助华盛顿以阿富汗为中心做活一片。显然，巴杰管道要抽走的是俄罗斯希望得到的石油，也是中国希望得到的石油。现在，华盛顿一下子动了两个人的奶酪。

需要先说明的是，阿富汗对美国的全球战略具有特别重要的意义：911之后，美国打着反恐的旗号杀进了阿富汗，成功的在亚欧大陆的中心地带砸进了一颗钉子。以阿富汗为中心，往北美国可以在前苏联加盟共和国搞颜色革命，拉过土库曼斯坦、哈萨克斯坦、塔吉克斯坦等一帮“斯坦”们和格鲁吉亚、乌克兰等小国，再往北通过控制波兰、捷克，形成一道封锁线，阻止俄罗斯西进中东，同时阻挡俄欧接近；顺着阿富汗往北，如果控制了巴基斯坦的俾路支或者是克什米尔地区，再拉上印度，就可以切断中国西进的道路；同时，借助对中亚小国的控制，还可以分割中俄，如果再加上堵在中国门口的第一岛链和第二岛链，就可以全面封死中国的发展空间。当然，这一切是北京绝对不能容忍的，面临着同样问题的莫斯科也是绝对不能容忍的。

在巴杰管道开通之前，俄罗斯是非常介意中国对中亚的经济渗透和油气进口的。但是，现在情况完全变了（4月25日巴杰管道正式开通）：既使中国不能从中亚弄走石油，美国也可以；即使中国不能从经济上控制中亚，美国也可以。相比之下，美国是死敌，中国还算可靠。既然东西必须要送人，那至少要送个可靠一点的人。于是，俄罗斯开始允许中国对中亚小国的经济渗露和能源进口了。

从7月份开始，中俄联手展开了封杀美国阿富汗支点的行动。理由嘛，禁毒，人类最高尚的事业。要知道，美军控制下的阿富汗除了出毒品以外别的什么都不出，禁毒相当于切断了阿富汗的经济命脉。

今年8月，美国已完成了作战部队从伊拉克的撤离工作，奥巴马却一再高喊口号要增兵阿富汗。我们都知道，伊拉克有大量的石油而阿富汗没有，为什么美国不从阿富汗撤军却从伊拉克撤军呢？美国难道不想要石油了？从上面的分析中，相信大家可以找到答案。

也许在中亚搞颜色革命搞的太顺手了，美国人开始飘飘然手舞足蹈起来。05年6月，亚太安全会议[fn:jinhong0106]在新加坡召开，拉姆斯菲尔德在会上开始大谈中国军事威胁论，给小泉纯一郎打气，因为小泉刚刚被他吴姨[fn:jinhong0105]放了鸽子并招致国内各届的群起围欧，日子正过的艰难；另外喊一喊中国威胁论还可以离间一下中国与东盟国家的关系。

其实，这时的美国并不真的想和中国正面发生冲突，只是希望用中国军事威胁论这根绳子困住中国，乘着中国慢慢解绳子的机会继续在中东、中亚做自己该做的事情。在胡主席上任之前，这一招是华盛顿屡次不爽的，可是这回遇上麻烦了。这一次北京根本没理华盛顿缠过来的绳子，直接揪住头发对他展开了反击，没给他任何在后台看热闹的机会：

北京先是打了一发射程8000公里的巨浪二导弹，你不是说我能威胁你吗？你说对了。原来心里打鼓的东盟小国这时倒放心了——中国的导弹打得太远了，根本不是冲着自己来的，难怪不得美国喊中国军事很暴力，还真有这事。

接着，朝鲜也拒绝了美先行废核的要求，重启核反应堆，号称要造更多的原子弹，努力的刺激非常渴望原子弹的小泉纯一郎——你不是想造原子弹吗？机会来了。

接着，在7月初的上合峰会上，中俄搞了一份建立多极化国际新秩序的联合声明，以上合的名义吸收伊朗、印度、巴基斯坦为观察员，并要求华盛顿确定在上合成员国临时驻军的最后期限。这次上合峰会是一次标准的反美大会：大家都知道美国是世界一霸，而中俄要“多极化”，摆明要把美国拉下马；吸收伊朗巴基斯坦为上合观察员，就可以完成对阿富汗的战略包围，关键时刻中俄随时可以拔掉美国的这颗钉子；同时，把伊朗这个美国一心想占领的国家纳入了自己的势力范围保护了起来；拉印度入伙则是进一步增强反美阵线的实力；最后就是拔掉了美军在乌兹别克斯坦的一个基地（吉尔吉斯斯坦的没有拔，给俄罗斯留点想头）。

真没想到拉姆斯菲尔德这一句话带来了这么大的麻烦，华盛在中亚花了巨大代价才砸下的几颗钉子，差点被中国联手俄罗斯全给[拔]了，这实在是太不划算了。从此，美国再也不敢轻易喊中国军事威胁论了。

在与中国斗法时，美国倍感吃力，为了给自己减压，美国以允许日本有核为诱饵诱惑反华的小泉政府跟中国彻底绝裂。为了能拥有核武器、成为独立的国家，小泉一度在反华的道路上走的非常远，所以，06年是中日关系最为紧张的一年。不过需要说明的是，小泉的反华行为其实只是手段，是希望借与中国的冲突把美国拉下水，借美国的战略需要（靠日本帮忙一起对付中国）和日本眼前的生存压力（死敌朝鲜已在制造核武器）逼迫美国同意自己拥有核武器，从而快速成为一个独立的国家。

年初，眼看着北京一步步的制定《反分裂国家法》，美国决心制定美日新安保指针、组建日美军事同盟来协防台湾。新指针制定之前，华盛顿通过美国媒体放风，说指针里会写明中国军事威胁论，日本一听，就在自己的防卫政策里写进了中国军事威胁论，结果到了2月底美日新安保指针通过时，日本人惊讶的发现中国军事威胁论不见了！小日本被华盛顿实实在在的玩了一回，事后，小泉一个劲在媒体上抱怨，协防台湾是华盛顿的主意；但是，为了让华盛顿允许自己有核，小泉还是接受了现实，忍了！

面对敢于染指台湾的日本（美日新安保指针涵盖了台湾海峡），北京开始了强有力的回击，首先借着小泉拜鬼的由头，调动各国对日本历史问题展开大批判；然后公开对日本入常说不，原因就是战后日本政府的出身太差且死不悔改。为什么北京把攻击点首先选在历史问题上呢？因为只有军国主义的日本才是危险的，也只有军国主义的日本首脑才会参拜靖国神社。这也是每一任不参拜靖国神社的日本首相的对华政策都相对友好的原因。

4月份，小泉决定踩北京的红线，进入东海采油；结果被北京严重警告的同时，经济层面也受到了打击。中国国内开始出现反日大游行，许多日企在华业务受到了严重影响，这就引得日本企业界对小泉强烈不满，小泉不得不低头，在随后举行的亚非首脑峰会上就日本的侵略历史做了公开道歉、以改善中日关系。

6月份，小泉又编了一个“六月期限”来刺激朝鲜，说美日两国把六月份作为解决朝核问题的最后期限。结果金正日一点面子不给，还六月期限？我偏偏要到七月才有空跟你们谈，你能奈我何？无法控制局面的小布什只好出来辟谣，说根本没六月期限这回事，自己是个非常有耐心的人，六月份谈不出结来就七月，七月不行就八月，这事不着急，当年为了追劳拉我还拿着99朵玫瑰在劳拉的门外跪了三天三夜呢，我有耐心的很。

当然，布什的耐心也是被逼的，他是实在也惹不起金正日，只好打小泉的脸了。打脸归打脸，该鼓的劲还是要鼓的，拉姆斯菲尔德高呼中国军事威胁论，还弄了一份封锁中国海上通道的美日联合作战计划出来，一起给小泉鼓劲。得到了鼓励的小泉毅然拍板，进入中国专属经济区开采油，再踩北京的红线——我爹帮我，你能咋的？

北京马上进行了强硬反击，把中国的专属经济区纳入了海事监管范围，只要日本的船只敢进场，中国就要扣船；接着由少将朱成虎出面警告，如果美国在台海冲突时敢对华动武，中国将进行核还击。在北京主子奴才一起打的强悍气势逼迫下，小泉暂时收手。

8月份，中俄举行了首次大规模联合军演和平使命2005，此次军演主要是照顾中国利益保卫朝鲜半岛和照顾俄罗斯利益稳定中亚局势。中俄的这一场军演不光让金正日有了安全感，也让卢武铉增强了归属感，为了拉住韩国，无计可施的华盛顿只好签下了919共同声明。虽然这个声明没解决什么实际问题，却也避免了会谈的彻底破裂。签完字后，美朝双方把笔一扔，马上拉开架式继续斗。

朱成虎的“核胁美国”震惊了美国朝野，万不得已派出老鹰拉姆斯菲尔德到中国打探消息，中国真要的用核武器先发制人吗？结果，这头被逼上门来的老鹰用支持东北亚经济一体化的口头承诺换来了北京不首先使用核武器的承诺。东北亚经济一体化，其实就是北京通过对东北亚经济的整合来全面主导东北亚局势，一旦完成，美国影响将被全部挤出，日本韩国将变为中国全球经济布局中的一个棋子。

美国不敢与中国摊牌的态度惊醒了刚刚在改选中赌赢的小泉纯一郎。为了不被美国人当枪使，小泉开始在反华问题上跟华盛顿做起表面文章来，除了在参拜靖国神社这类“虚”的事情上继续恶心中国外，在东海采油这类“实”的事情上变得规矩起来。

没按华盛顿的要求继续与中国决裂也就算了，最不能容忍的是，小泉居然利用民意拿冲绳军事基地说事，跟华盛顿讲价钱，这让华盛顿恼火无比。于是，憋了一肚子气的拉姆斯菲尔德开始拿日本出气，声称要取消原定的访日计划。这让一惯拿小布什当亲爹的小泉再也坐不住了，只好自打嘴巴在冲绳军事基地整编问题上做了巨大让步，这才换来了华盛顿的一笑。布什拍了拍小泉的肩膀说了一句：“要西，好狗！”

从小泉那里拿到了好处的华盛顿没有按照之前的承诺在东北亚让步，耍了北京一回。恼怒的北京这才在919共同声明中写进了十个字，“口头对口头，行动对行动”，以此警告华盛顿：你要记住，这样的便宜只有一回，以后你要再耍嘴，我也会，你要来真的，我奉陪！接下来又较量了一年，华盛顿才被迫开始在朝鲜核问题上“行动对行动”。

此后，小泉在反华方面更加的避实就虚，出工不出力。小泉把对中国的攻击点进外移，从东海转移到了东南亚——首届东亚峰会。

先说一下东亚峰会的来龙去脉：东亚峰会的构想最早是由马来西亚总理马哈蒂尔在1990年年底提出的，他提议建立包括一个东盟和中、日、韩在内的东亚经济共同体。这个东亚经济共同体最终能长成什么模样，大家只要看一看昨天的欧共体就能明白个差不多。只不过当时的中国一心韬光养晦，美国对东南亚的控制力量又很强，这个构想自然无法变成现实。到了97年，美欧联手发动了一场掠夺东亚各国财富的金融风暴，一下子把这些小国推进了中国的怀抱。当年年底，东盟与中日韩领导人齐聚吉隆坡，10+3合作机制正式启动；01年建立东亚共同体的报告被提出；05年在吉隆坡召开首届东亚峰会。请注意，无论是10+3启动还是首届东亚峰会，都是在马来西亚举行的，可见马来西亚的积极程度之中。

马哈蒂尔为什么要力推东亚峰会？97年金融危机之后为什么几乎整个东盟（都全力支持新加坡是个异类）？因为小国要想生存的好，必须找个大国做依靠。马来西亚是亲华的，这一点只要看看今天人民币和林吉特的公开上市交易就能明白——林吉特可是首个与人民币进行交易的发展中国家货币，此前，人民币交易的对象只有美元、欧元、日元、英镑（港元是自家生意），现在，中国力推人民币国际化争夺发展空间，首先就是要把人民币的交易范围扩大到整个东南亚，马来西亚是配合中国最积极的国家。

早年，日本曾经提出过一个雁行发展模式，日本当头，亚洲四小龙跟上，中国大陆和东盟其他国家在最后。如果按照这样模式发展，日本可以通过整合东亚经济来主导东亚局势，中国只能处在东亚产业链的最低端，干着给人端茶递水的活。到了85年，日本被欧美联手进行了一次金融打击（广场协议），经济上元气大伤；到了97年，东南亚金融危机暴发，当时日本不扛事的表现让东南亚小国们失望之极，倒是中国帮他们度过了一劫。之后，中国经济越来越强大，整合东南亚的主导权慢慢落入了中国的手中。

中国是如何逐步主导东南亚局势的呢？方法跟在东北亚的做法完全一样。一面打击美国的政治军事影响力，一面进行经济整合。现在东盟小国有心投靠、一起搞东亚共同体，那还不是北京求之不得的好事？既然是共同体，总得有个老大吧？在这13个国家里面，中国无疑是最大的大块头，中国不当老大谁当呢？

眼看着自己碗里的肉变成了别人的盘中餐，日本人心里酸溜溜的。一旦中国把美国逼出东亚、完成了对东南亚、东北亚的经济整合，日本只好给中国打工了，这种局面是日本人所不愿意接受的。所以，对北京力推的东亚峰会，日本一直不热心，他不愿意给中国做嫁衣裳。在日本人眼里，与其帮中国人，不如帮他的美国主子。二战以后东南亚一直就是美国的地盘，现在中国来抢，美国自然不高兴。于是，每次东亚峰会召开时，日本都会配合美国来搅局（还有那个该死的新加坡）。不过，日本的做法让大部分东盟国家非常不满——他们之所以愿意搞东亚共同体，就是怕被美国再抢一次。

日本配合美国的搅局手段是什么呢？掺水，削弱中国的主导能力。从首届东亚峰会开始，日本美联手把10+3撑成10+6，加塞进来的三家分别是印度、澳大利亚、新西兰。很显然，印度是美国为中国量身打造的对头，而澳新日韩都是美国的盟友，这样，10+6里面就有一群阻挡中国主导局面的敌人，再加上一个在后台操盘的美国，局面变得很难控制，首届东亚峰会开得很不成功。如果对比一下今年东亚峰会上冒出来的10+8，有什么感想呢？如果再看看今年美国在未通知日本的情况下就宣布参加东亚峰会，是否有沧海桑田之感？

当然，如果换个角度来看，东亚峰会能召开本身就是一种成功，因为它冲破了重重阻力。

【金鸿评论】面对着越来越麻烦的伊朗核问题，被伊拉克乱局拖得疲惫不堪的美国不得不在巴以和谈问题上开始让步。按华盛顿最初的计划，打下伊拉克以后，用卖伊拉克石油的钱作军费再打下伊朗，就可以完全控制中东石油。美国人的这个计划让欧盟感觉非常不爽。所以，当美国在欧盟（主要是法德）的强烈反对声中攻入伊拉克的时候，欧盟扔给美国人一个伊朗核问题。在美国打下了伊拉克之后，大家又一起再送给美国一个伊拉克乱局。在大家的共同努力下，伊拉克局面完全出乎了美国人的意料，天天爆炸天天死人，美国人根本无法采油赚钱，结果原来计划中的现金奶牛变成了吸金黑洞。在伊拉克捣乱的这个“大家”是谁呢？很难说清楚，但是怀疑欧盟、俄罗斯、中国、伊朗、叙利亚、沙特这些国家中的任何一个都不会冤枉了好人。

06年以前，美国在在伊拉克日子很艰难，但伊朗的核进程并不快，主要原因就是欧盟保护不了伊朗。在那三年的时间里，伊朗只强硬过三次：

04年6月，伊朗恢复铀浓缩离心机的安装；

04年9月，伊朗宣布开始将一部分铀矿料用于铀转化试验；

05年８月，伊朗恢复了在伊斯法罕的铀转化活动。

上面的三个时间段里还发生几件事：

04年6月，朝鲜在北京的支持开始着手搞原子弹；

04年9月，朝鲜又弄出一朵蘑菇云；

05年8月呢，是和平使命2005联合军演的日子。

从这里可以看出，伊核与朝核有着相当大程度的关联性，这一点在以后的局势发展中会表现得更加明显，这也是中国很快就能主导伊核六方会谈的原因所在
。

对欧盟而言，伊朗核问题只是筹码，逼迫美国在巴以和谈上作出让步的筹码，发展到08年就是要求大中东计划给地中海联盟让路。05年11月伊拉克议会选举前，俄罗斯提出了伊核六方会谈模式，希望与中国欧盟联手在中东对抗美国。当时的欧盟心存幻想，希望与美国平分中东，所以就没理俄罗斯，中国自然也
就没好表态。

对于欧盟的私心，只能用事实教育。之后，在中俄的放任之下，伊拉克议会选举顺利完成，不过选举结果对华盛顿很不利，华盛顿就把选举结果压下不公布，还弄了份与事实严重不符但绝对对美国有利的选举抽样报告出来试探各方反应。这时，欧盟才明白，美国根本不想与他平分中东。如果再不请中俄帮忙，等美国搞定了伊拉克之后，中东就全姓美了。这时，墨克尔站了出来支持俄罗斯的伊核六方会谈建议，从那时起，中俄欧三强中东抗美格局形成。

中国能挤进六方会谈，跟北京刚刚与伊签下的总额1000亿美元的油气长期合作协议直接相关。协议签署之后，中国在伊朗就有了巨大的商业利益。美国的目的是颠覆伊朗政权、控制伊朗的石油资源，如果伊朗被美国搞定了，中国的利益将严重受损。所以，一旦美国作出严重危害伊朗国家安全的行动时，中国必然出手干预。中国成了伊核问题上任何一方都绕不过去的国家，这也是欧盟允许中国加入的原因所在。加入伊核六方会谈，是中国人的手第一次伸进中东，这对中国而言，是个历史性的突破。

眼看欧盟拉来了外援，美国只好实事求是了一回，让什叶派主政伊拉克。上台后的伊拉克新政府马上开始反美，把原先政府里的亲美派一个一个往外踢，让美国人很受伤：兔崽子，我让你们上台是让你们来对付我的吗？

这个选举结果却让波斯人喜出望外，伊拉克什叶派是伊朗的自家人。大喜之余的内贾德做的第一件大事就是马上恢复了停止两年多的浓缩铀活动，核进程开始提速。伊朗这么做的原因有二：一是中俄已把伊朗吸收为上合观察员，纳入了自己的保护范围，中俄现在又是六方会谈的成员，伊朗的国家安全有了保证；二是伊朗拥有了左右伊拉克局势的能力，美国投鼠忌器，得提防伊朗在伊拉克搞破坏。

伊朗核进程的加速让美国人开始心慌了，美国开始要求将伊核问题提交联合国安理会了，希望能在安理会通过对伊朗的制裁决议，通过制裁拖垮伊朗现政权
。不过，在中俄欧三家的联合戏耍之下，一点成绩也没有。

这时又发生了一件让小布什更感觉不可思议的事情：哈马斯在巴立法委选举中获胜了，到了三月哈马斯自治政府组建成功。如果说伊拉克选出了什叶派执政是布什的恶梦的话，那么哈马斯上台真的就是白天撞见鬼了。哈马斯是些什么人？那可是上了白宫恐怖组织黑名单上挂着号的，现在居然成了巴勒斯坦的掌权人！而且是在美国全球战略心脏地带（巴以和谈[fn:jinhong0108]对石油美元的存在具有决定性意义）！在哈马斯上台之前，巴以和谈的双方以色列和法塔赫都在华盛顿的控制之下，巴以和谈除了欧盟别人是无法染指的（毕竟都是北约的人，自己吃肉总得给小兄弟点汤喝喝）。现在哈马斯上台了，哈马斯与伊朗关系密切，伊朗又与中俄是一个组织的（上合）。这么一来，中俄又有机会在巴以和谈问题上说话了，这还了得？

所以，哈马斯一上台，立即出现了一连串的新鲜事：

首先，新登基的沙特国王阿卜杜拉首访地选择了北京，中沙关系从此越来越紧密，对于石油，“中国要多少有多少”，特别需要指出的是，汶川大地震的时候
阿卜杜拉捐献钱物共计6000万美元，居国外捐款之首；

其次，阿拉伯世界一致要求美以接受哈马斯掌权，给哈马斯一个“重新做人”机会；

第三，普京邀请哈马斯访俄，美以强烈反对，法国却表示支持；

第四，美国不顾国家体面，张嘴讨回了已经拨付给巴勒斯坦自治政府的5000万美元援助，欧盟却马上掏了1.2亿欧元的经济援助给哈马斯，以防哈马斯活不过
去被逼疯了；

第五点与中国有关，为逼中国在伊核问题上配合自己，华盛顿又一次摔出了台独牌，出人意料的是，这一次北京没动朝核牌，却打起了哈马斯这张牌，声称
准备对哈马斯进行经济援助，气得以色列马上安排了一场达赖见面会。

从这一系列事件中可以看出，哈马斯上台对世界局势的影响有多大。

随着中俄欧三家联合的形成，美国在伊核问题上变得更加被动，虽然先后在乌克兰方向（逼俄罗斯黑海舰队搬家）、格鲁吉亚方向（逼驻格俄军撤走）
、台海方向（陈水扁终止国统）向中俄同时施压，没有得到任何满意的效果，倒是伊朗的铀浓缩进展的更加危险了，到5月份甚至传出了欧洲人在伊朗发现武
器级浓缩铀的小道消息。

这时，华盛顿实在是撑不住了，对伊朗做出了一系列的让步：保证伊朗国家安全，允许伊朗更大范围的融入世界经济体系，保障伊朗和平利用核能的权利，
希望换来伊朗的暂停铀浓缩。但是，因为美国并没有给中俄欧三方半点好处，伊朗也就没有接受美国的好意而停止铀浓缩。

应该说，伊朗的做法是是聪明而不精明：美国给他那么多好处，他却没有伸手拿；他为什么不拿呢？因为他深知这些好处是中俄欧替他捞过来的，如果这三
方没得到好处，既使他把好处拿到手了，只要有一方翻脸，他就会得而复失；

而美国的表现是精明而不聪明，既然伊朗只是台前人物，你单给他好处又有何用？扬汤止沸吗？眼前可以少放一点血，但问题是解决不了的。当然，美国这
么做也有他的难处，如果单单一个欧盟伸手，大不了在中东给他一点好处，可是，现在中俄也一起伸手了，而且伸手要的不是别的，是巴以和谈问题上的发
言权，这对美国而言是极难接受的。（此前俄罗斯虽然是中东四方的一方，可在欧美的联合架空之下说话一直没人听，俄罗斯希望把中国引进来跟美国争夺
发言权）

这时，华盛顿开始翻脸，扬言要武力解决伊核问题，同时让以色列对哈马斯下手。以色列国防军一口气逮捕了87名哈马斯高官，以行动警告中俄，你们不是
以为有了哈马斯就可以介入巴以和谈吗？我先灭了他！很显然，美国想和以色列一齐解决掉这两个问题：美国打伊朗，以色列收拾哈马斯。可就在这时，出
现了两件事，一下子缠住了美国和以色列的手脚，打乱了华盛顿的计划：一件事情是7月5日的朝鲜导弹发射事件；另一件事情是7月12日真主党越境袭击以色
列并抓走了两名以色列士兵。

先说第一件，朝鲜导弹发射事件。7月5日那天，朝鲜先后发射了多枚导弹，其中，射向日本方向的短程导弹全部发射成功，能打到美国本土的大浦洞二
型导弹却空中解体了。在分析这一事件的影响之前，先看一下各方对朝鲜发射导弹的态度：

中国：我非常关心这件事，大家都要冷静啊。

韩国：虽然我感觉没什么，不过我嘴上还得喊一嗓子，朝鲜你想干嘛？

日本：你吓着我了，我可能会找个机会修理你一下；

欧盟：朝鲜在挑事，唯恐天下不乱！

俄罗斯：大家商量一下，怎么把这个事过去呢？

美国：我真的很烦哪！怎么没一个人帮我说话呢？

朝鲜这次导弹试射是在
#+HTML:<a>测试美日关系倒底有多铁</a>
#+LaTeX:\red{测试美日关系倒底有多铁}
。结果呢，打往美国方向的导弹日本不拦，打往日本方向的导弹美国不拦。日美同盟原来是个空架子，谁都不管谁死活。朝鲜这几发导弹，也帮助小布什看清了东亚的形势：一旦陈水扁在台湾玩大了逼北京动了手，日本是绝对不会冲到火线上去的，美国自己也不可能为了台湾跟中国拼命（台湾只是美国遏制中国的一颗棋子），结果就是一旦北京动武相当于把台湾白送给中国。所以，关键时刻华盛顿想从台海方向牵
制北京是不可能成功的。在朝鲜导弹发射一周后（14日），小泉的官房长官安倍晋三会见马英九时更是明确表态，日本是反对台独的。请大家注意，这时以
色列已经和真主党动上手了。

东亚局势的变化，美国人看的清楚，以色列人同样看的清楚。按华盛顿的意思，以色列最好集中火力收拾哈马斯。可是以色列偏偏借着真主党抓人的机会，
把目标对准了真主党。其实，以色列很明白，现在的哈马斯是中俄眼里的一块宝，如果真把他打残了，美国究竟能不能保护的了自己还是个未知数，所以还
是先借打击真主党来探一下华盛顿在中东摊牌[fn:jinhong0107]的决心有多大吧。眼看着自己的小跟班拈轻怕重，心里头也在打鼓的美国只好让以色列先捏个软柿子看看情况
。结果实际一动手以色列才发现，自己不打哈马斯是完全正确的，美国根本没有摊牌的决心。所以黎以冲突到了最后就是把真主党打成了中东的英雄，向来
软弱的阿拉伯国家也开始扯着嗓子跟美国人说话了，连最亲美的埃及都开始反省亲美政策了。

这次帮助伊朗和哈马斯减压行动的背后，无疑都有中国的影子，朝鲜打导弹自不必说，真主党抓人也是在中国的特使在中东转了一圈之后发生的事，真主党
又是伊朗扶植起来的。出于对中国插手的恼火，7月26日凌晨以色列轰炸了联合国的一处观察站，杜兆宇烈士牺牲。

在以色列和真主党的交手时，出欧盟仍然幻想与美国平分中东，所以在中俄希望的改组中东四方会谈问题上拒绝回应。一仗打完，中国仍然被挡在了巴以和谈门外，不过欧盟自身也失分不少，因为交火中欧盟一点忙也帮不上，让阿拉伯人大失所望，倒是中国对真主党的援助行动让以色列变的缩手缩脚。

没有欧盟的引荐，中国无法加入巴以和谈，只好加大了在外围的活动力度，包括进入黎巴嫩维和，为叙利亚和真主党开辟出一片绿色通道。有趣的是，邀请中国到黎巴嫩维和的是新官上任的普罗迪，普罗迪希望以此换取中国对意大利加入伊核会谈的支持。对中国而言，意大利加入伊核会谈可以接受，反正意大利也是想借机
#+HTML:<a>打劫华盛顿</a>
#+LaTeX:\red{打劫华盛顿}
，只要给中国点好处就可以支持他，只怕美国人不同意。在意大利伸手的同时，日本也向美国要求加入核伊会议，气得小布什脑袋
一摇：“这趟车的票都卖完了，你们等下一辆吧！”

从这里也可以看出大国斗争的某些潜规则：
#+HTML:<a>加入关键的国际谈判是需要有人引荐的，新加入方需要有左右谈判人的能力</a>
#+LaTeX:\red{加入关键的国际谈判是需要有人引荐的，新加入方需要有左右谈判人的能力}
。比如年初中国加入伊核会谈，离不开欧盟的引荐，更离不开中国左右伊朗的能力（巨额能源合同）和对付美国的实力；而这次中国挤进巴以和谈失败，就是因为没有欧盟的引荐，一个处在边
缘的俄罗斯根本无法把中国托上去。

之后，为了尽可能的保护伊朗的安全，保住伊核这张牌，中俄欧联手把伊核问题弄回了联合国，给予华盛顿制裁伊朗的机会，这样就可以给华盛顿做梦
的机会（制裁拖垮再武力解决）；那么伊朗可以得到什么好处呢？避免挨打。如果强行把伊核问题留在联合国之外，华盛顿想制裁却没机会，关键时刻万一
狗急跳墙就麻烦了。从那时起，我们常常可以看到这样一幕，这边华盛顿花一年的辛苦才弄到一份制裁伊朗的决议案，那边北京顺手跟伊朗签几份经济合同
把制裁效果全抵消了。

7月份的黎以冲突达到了两个目的：一是解了哈马斯的围，二是减了伊朗的压。当时的朝鲜导弹试射只是策应性质的，真正起到支援作用的事件发生在10月9
日，朝鲜地下核试暴成功。这时，一个所有地球人都搞不懂答案的问题出现了：为什么美国不去打那个已经爆炸了原子弹的朝鲜，却要打这个没造出原子弹
的伊朗？难道仅仅有作案动机比已经作案还可怕？

借着美国被两核问题牢牢缠住了手脚的机会，中俄欧三方也加快了各自的全球布局。所谓布局，就是抢美国地盘。回头看看这半年的交锋，和华盛顿下对手
棋的人是谁？北京。俄罗斯和欧盟都是陪趁。

以朝鲜核试爆为标志，北京拉开了东亚核竞赛的序幕。美国为了压住日本的核野心，不得不连续让步：搞乱台湾的倒扁运动被压了下去，格鲁吉亚与阿布哈兹的冲突也偃旗息鼓，苏丹政府和东部阵线的十年内战也结束了。
#+HTML:<b><a>从此，中美之间的全球争斗美国开始转入防守，中国则借机展开全球布局，</a></b>
#+LaTeX:\red{从此，中美之间的全球争斗美国开始转入防守，中国则借机展开全球布局，}
标志性的动作有四：

一是加大了全球能源布局：西向的是巴基斯坦的能源走廊建设（进口中东和非洲的石油），当时中国在巴基斯坦的瓜达尔砸进了500亿美元，修了一个军民两用的港口。北向的是中俄能源管线及中亚方向的管线，再就是与委内瑞拉的能源合作。要知道，美国全球战略的核心也是控制全球石油，以此保证美元的霸主地位。

二是中非和合论坛北京峰会成功召开。这次峰会规模庞大、规格极高，有48个非洲国家代表团参加，43非洲国家的元首亲自与会。半个月前，苏丹政府刚刚和反政府武装东部阵线在阿斯马拉签署和平协议，结束了持续10多年的武装冲突。协议签署时，苏丹总统巴希尔高兴的说，阿斯马拉和平协议是非洲国家在没有外来干预的情况下解决自身自身问题的典范，并承诺苏丹政府将遵守和平协议。一句“苏丹政府将遵守和平协议”，道出了协议的来之不易，更道出了苏丹政府对协议的满意，个中滋味大家自己体味。不过，要说没有外来势力干预，就是在说假话了。93年苏丹就被华盛顿列到了自己的支恐名单上，这个名单是只有古巴、朝鲜、伊朗这样的国家才能享有的殊荣。如果没有外部势力的干预，一场内战能打10年？如果没有朝鲜的核试爆，苏丹能有机会独立解决自身的问题？协议能签的这么干脆？正是看到了北京对自己小兄弟朝鲜、伊朗、巴基斯坦、苏丹这些国家的保护能力，非洲各国才愿意全身投靠。43个国家元首参会，不用说在万里之外的北京开会，就是在非盟的会议上，也是从来没有的事。这样的成功，足以让殖民过非洲的英法吐血。

三是拆散APCE[fn:jinhong0109]。前面提到过东北亚一体化、东南亚一体化对中国的好处了，对比一下就会明白APCE对美国的好处。APCE是当年克林顿力推的国际工程，通过主导APEC，美国把欧盟和俄罗斯这两个对手隔离在亚太经济圈之外，然后通过台湾问题、东海划界、朝鲜核问题、南海争端等问题在中国和日本韩国东盟等国之间砸钉子，华盛顿居中协调就可以把中国牢牢控制在这个经济体的中低端，中国也将永无出头之日。这对中国而言是绝对不可接受的，胡主席上台以后开始着手破局，力推10+3（05年更是推出了东亚峰会），把美国挤出去，建立一个自己主导的东亚经济体。美国当然不同意，中国又使出了第二招，把APCE扩大，你不是不愿意我搞小的吗（10+3成员都是APCE成员）？那就搞大的，把俄罗斯欧盟一块拉进来搞吧。这当然是华盛顿更不愿意看到的局面。于是，华盛顿只好让步允许中国搞10+3。对比一下，中国把APCE撑大和东亚峰会时美日联手把10+3撑大到10+6有什么区别吗？

四是力推泛亚铁路。泛亚铁路其实是中国把美国排除在外整合亚欧非大陆所推的一项工程。为什么要建铁路不走水路呢？因为海洋在美国航母编队的控制之下，我们不得不避实就虚。泛亚铁路共分北部、南部、南北部和东盟4条线路。北部路线是韩半岛-俄罗斯-中国-蒙古-哈萨克斯坦，贯通亚洲北部地区；南部路线是中国南部-缅甸-印度-伊朗-土耳其，连接南部地区；南北路线为俄罗斯-中亚-波斯湾，连接南部和北部地区；东盟路线则连接东南亚国家和中南半岛地区国家等东南亚地区。另外，如果从土耳其经叙利亚，以色列、巴勒斯坦到埃及，就进入了非洲大陆。这个泛亚铁路真要搞成了，整个亚欧非大陆将从经济上联为一体。在中俄欧美四方中，论综合实力，中国比美国要差，但比欧盟和俄罗斯都强。现在搞的这个把美国排出在外的亚欧非大陆经济整合里面，中国无疑是最大的块头，获利最大的也将是中国，此涨彼消的是美国的必然衰弱。这才是真正的大手笔。从此不难看出，胡主席的确是伟人。

北京的做法让华盛顿感到了强大的威胁，于是华盛顿开始在北约搞转型。怎么转型呢？首先，要求北约跨出传统的欧美防区，走向全球；其次，要搞北
约全球伙伴计划，哪些伙伴呢？日本、韩国、澳大利亚、新西兰。很显然，美国是左手拉住老朋友，右手再交新朋友。目的呢，一方面巩固老朋友防止被孤
立，另一方面用新朋友破坏中国的全球布局。只不过转型的结果让美国很伤心：欧盟不但明确反对全球伙伴计划，还要求美国应该在北约内部多听听他们的
声音。从这时起，北约不但没能更加团结，反而走上了瓦解之路。

12月份底，华盛顿终于拿到了一份圣诞礼物，制裁伊朗的决议案通过了，这时，距离伊朗重启铀浓缩活动已经快一年了。

这份决议案也确实来之不易，它是在美国在让中国主持了一次巴以和会、又用一场警觉之盾07核军演暗示有可能对伊朗进行核打击之后才拿到手的。不过，
就是这么一份用核大棒才唬到手的协议，里面并没有经济制裁的内容，中俄欧三家在伊朗的商业利益都不受任何影响，受到制裁的只是伊朗的核计划和弹道
导弹项目，其实这是一份没用的制裁案。还有一点需要说明，通过这份决议案也是为了照顾一下阿拉伯人的情绪，因为伊朗在伊拉克扩张的太快了，阿拉伯
人不放心。所以，送到华盛顿嘴里的，只是一个空心汤圆。



** 【金鸿评论】04年以来的大国斗争回顾(中)
[2010-09-1122:57:33]



【金鸿评论】美国只所以在中东如此被动，是因为伊拉克局势迟迟不能平定，美国只能大把的往伊拉克扔军费却无法采油获益；可他的对手们却在忙着相互间
搞经济经促发展。此涨彼消，美国危矣，感受到了强大压力的小布什在07年新年伊始就马上开始布局：

第一，以把伊拉克彻底搞乱威胁各国（主要是沙特、约旦、叙利亚、土耳其和伊朗），并在宰牲节那天用萨达姆的人头来激化让逊尼派和什叶派的矛盾，让他
们自相残杀，自己好收渔人之利；

第二，向伊拉克增兵两万，为平定伊拉克局势做最后的努力；

第三以参与伊拉克石油立法的方式，帮助美英石油公司获得在伊拉克30年的石油开采权，露出了攻打伊拉克的真正面目；

第四，不停的用小动作警告伊朗在伊拉克规矩点：到伊朗驻伊拉克办公室抓人，号称美军将对向反美武装提供武器的伊朗网络发动袭击，乱闯入伊朗大使馆，
放风布什已经授权消灭在伊拉克活动的伊朗特工……当然，如果从另一个角度看美国的行动，也可以说明伊朗在伊拉克是多么的能折腾。

面对华盛顿的威胁，各方开始回应：

伊朗在两伊边境击落了一架美军的无人侦察机，之后俄罗斯说击落无人机的导弹是他家以前卖的，而且只要伊朗有需要，俄罗斯会继续卖。

1月11日，中国用一颗陆基中程弹道导弹将一颗飞行在860公里高空的气象卫星撞毁，震动了全世界。中国的反卫星实验是冲着美国上个月刚刚搞的警觉之盾核
军演去的。大家都知道，美国对抗中俄核威慑的导弹防御系统是高度依赖卫星的，现在，这套系统在中国的反卫星武器照顾下，将成为一堆废铁。现在美国还
有决心在中东或者台海摊牌吗？中国把卫星这么一打，被美国威胁着的朝鲜、巴基斯坦、伊朗、叙利亚和众多的阿拉伯国家都放心了，中国有能力保护他们。

24日，又传出了朝鲜在帮助伊朗搞地下核试爆的消息。这是朝鲜第二次在关键时刻替伊朗分担压力（上次是三个月前的核试爆）。不准核扩散是美国去年给朝
鲜划下的红线，现在朝鲜又把这条红线踩在了脚下，美国打还是不打？如果不打，那还有什么理由打伊朗？如果打，能打赢吗？到这时，华盛顿才有了花点本
钱把朝核问题先行彻底解决掉的压力。

29日，法国总统希拉克接受采访时说，伊朗拥有核弹并不是十分危险的事。希拉克的意思很直白，你们美国人不是感觉把伊拉克剁成三截搞乱中东很吓人吗？
我倒感觉与伊朗拥有核武器相比这还不算什么。如果你真有胆量的话，就往前再走两步试试。

这一轮大摊牌的结果是什么？日本人李登辉的表态最能说明问题。29日时李老狗说了，他不是台独教父，也从来没有主张过台独！他认为应该开放中资以及大
陆观光客入台——李登辉居然成了两岸三通的忠实支持者！而他的主子安倍晋三呢，嘴上喊着要加强日美联盟，却就是不去访美！大家一看，安倍果然在搞强势
外交，只不过强势的对象是他的主子华盛顿。的确，比起给小布什下跪的小泉来（真有此事），安倍要强硬多了！

为了集中力量解决两伊问题，防止关键时刻朝鲜再是跳出来搞破坏，华盛顿从07年2月份起开始有诚意解决朝核问题。要知道，此前的919共同声明只不过
是权宜之计，当时的华盛顿，只有“口头对口头”的敷衍，哪有“行动对行动”的诚意？919共同声明签完字的第二天，华盛顿就给朝鲜安了个制造美元假钞的罪
名开始对朝鲜进行金融制裁。不过后来事实证明，那些假钞是美国中央情报局印刷的。

这时，华盛顿解决朝核问题的诚意表现在哪里呢？

首先，2月5日，华盛顿通过阿巴斯的嘴巴告诉中国，希望北京介入中东和平进程；

其次，对朝鲜让步，愿意与朝鲜进行双边谈判（即承认朝鲜问题是自己的麻烦），考虑不再将朝鲜列为支持恐怖主义国家，并终止《敌国贸易法》；

第三，，承诺不会军事解决伊朗问题，满足了俄罗斯人的条件。

这时，华盛顿希望的是一劳永逸的解决朝鲜核问题，不过北京并不想这么轻易的就扔掉一张好牌。虽然华盛顿开出的条件非常优厚（允许中国加入巴以和谈）
，只不过北京介入中东事务时间太短、立足未稳，如果冒然丢掉自己的根据地（朝鲜牌）轻装远袭，只恐出现意外情况时前后两不靠。因为北京不愿意从根本
上解决问题，华盛顿也就拿着萝卜不松手，直到9月份被局势逼的实在没办法了，才同意让步把朝核问题压下好喘口气。

在小布什最迫切需要有人在东亚帮忙的时候，却遇上了一个刺头安倍晋三。在安倍上台之前，小泉那那可是小布什身边的一条好狗，只不过好狗没得到好
回报。之后，新狗上任的安倍改弦更张，再也不象小泉那样在布什面前下跪作揖了，开始玩强势外交：先访华，再访欧，就是不去看他爹。这时的华盛顿也很
难，看着自己的狗在自己困难的时候反咬自己一口，很想教训它一顿却又怕打生了眼，又不怕不打一顿它以后会变本加厉。于是，华盛顿只好玩起了胡萝卜加
大棒，一面拿着慰安妇问题修理日本人，一面又不得不在东京安排了一场巴以和会给安倍一点满足感。就在这一巴掌加一个甜枣才把安倍这尊神请到了华盛顿
。

按小布什的设想，在东北亚的让步仅仅是手段，可有人不那么看——向来被美国人死死抱在怀里的巴以和谈居然在短时间内连续让黄皮肤的中国人和日本人摸了
两回，看来美国人真遇上大麻烦了。于是，狡猾的英国人开始开小差了。

3月23日，15名英国士进入伊朗水域被扣，英国人马上要求伊朗放人，内贾德说只要英国人道个歉并且保证不再犯错就放人。于是两家开始演戏给美国人看。
最后，布莱尔给内贾德写了道歉信，并承诺英国无意和伊朗对抗——究竟是在救人问题上不愿意对抗呢还是在伊核问题上不愿意对抗呢？这恐怕就是个见仁见智
的问题了。不过，按英国国防部的说法，那15名英军在劣势下不抵抗是非常明智的！那布莱尔把这些明智的士兵派到波斯湾是去干什么去了？

要知道，英国一向是美国的死党，现在连英国都在另找出路了，可见美国的全球战略真要执行不下去了。那么，麻烦到底出在哪里呢？伊拉克，美国大兵在伊
拉克的日子实在是太了。到底难到了什么程度呢？驻伊美军二号人物奥迪尔诺亲口承认，美军在和他们的伊拉克敌人讲和。

4月下旬，中东特使孙必干到中东“劝和促谈”，并顺访了欧盟总部——孙特使此行的目的是什么？很简单，要求欧盟引荐中国加入巴以和谈。可惜，失败了。

进入5月份，美国又跟俄罗斯干上了。为了什么事呢？东欧反导。要说07年布什做了点什么成绩出来的话，也就是这张对付俄罗斯的东欧反导牌了。这张牌不
仅能威胁俄罗斯的国家安全，还能起到分割欧俄的作用，同时还可以离间欧盟的内部团结。对于美国这种踹寡妇门挖绝户坟的恶劣行径，欧盟也只能嘴上警告
一下（冒似强大的法德连波兰捷克都管不住），倒是普京不吃这一套。5月15日赖斯访俄时说，东欧反欧不容阻挡。普京则说，我准备重返阿富汗！俄罗斯派
兵到阿富汗能有什么事干呢？至少塔利班再买先进武器时容易了，地球人都知道俄罗斯的家伙好使，另外，俄罗斯指挥官偶然眼花错把小股美军当成塔利班灭
了也很正常。

在一面与老熊摔交的同时，华盛顿又安排他的小跟班在中东闹事了：借着打击哈马斯的机会，以色列把战火引向了黎巴嫩，这时突然冒出了一个叫“伊斯兰法
塔赫”的武装组织跟黎巴嫩政府军干上了。这个半路杀出的程咬金，叙利亚并不认识，可美国一口咬定他是叙利亚支持的，并说是叙利亚搞乱了黎巴嫩局势，
要办他。正在这时，一年前大显神威的真主党站了出来，在划清与程咬金界限的同时警告黎巴嫩政府，不准进入巴勒斯坦难民营抓人[fn:jinhong0110]，否则黎巴嫩会陷入内战
！因为有以前和真主党交战不胜的记录，以色列就没敢再继续打下去，叙利亚度过了一劫。

进入6月份，美国做了一件冒似得分的事情：借着哈马斯与法塔赫武装冲突的机会，让法塔赫不战而退，把加沙送给了哈马斯；接着，由阿巴斯出面对哈
马斯进行严厉谴责，说哈马斯占领加沙是在搞政变，并马上组建的巴勒斯坦紧急政府，巴勒斯坦就出现了加沙和约旦河西岸分治的局面。

其实，阿巴斯完全是在贼喊捉贼，哈马斯明明是执政的一方，有必要搞政变吗？再变又能变出什么来？倒是阿巴斯借机组建临时政府的行为怎么看都象是在搞
政变。此后，美以两国马上承认了阿巴斯的临时政府；美国又取消了对巴勒斯坦的制裁（制裁是从哈马斯上台后开始的），恢复对巴经济援助；以色列则归还
了之前扣留的４亿美元税款，同时取消对西岸人员与货物流通的限制。从美以两国这一连串的动作可以看出，他们的目的只有一个，通过支持阿巴斯来压垮哈
马斯。

谁能想象一下：强大的天下无敌的美国和强大的中东无敌的以色列，居然沦落到了只能依靠耍小手腕来困死弱小的哈马斯的地步，这究竟是谁的悲哀呢？

接着，以色列开始围困加沙，哈马斯的苦日子开始了；不过，小布什在中东的日子就更苦了。以前，在巴以和谈问题上阿盟的脸色美国是不看的，谁不听话可
以让以色列一打了之；现在情况变了，现在中国和俄罗斯联手杀进了中东，有人替阿盟说话了。这一变化也让欧盟感到了压力，欧盟一向是借着替阿盟说话的
机会从美国人那里捞好处的。

现在，在阿盟和欧盟的共同施压下，华盛顿就有了必须做点成绩出来的的压力。：代表阿拉伯民意的哈马斯已经被以色列困起来了，美国是不是要拿出一个说
的过去的方案来让阿拉伯人看到希望呢？要知道正是出于对美国人的无限期望，才没人替哈马斯的加沙被困说话。

6月底，伊朗宣布自己已经生产出一百公斤浓缩铀，伊核问题有了进一步激化的态势，这时，感受到了压力的美国人再次想起需要解决朝鲜问题来了，于
是马上把朝鲜的2500美元“非法资金”从澳门汇业银行转到了美国央行、再转到俄罗斯央行、最后汇到了开有朝鲜账号的俄罗斯远东商业银行，金融制裁也就此
结束。这是朝核六方会谈了十个月才谈出的一点进展。三个月后，华盛顿再次让步，朝鲜也开始去核化。

8月份，和平使命2007中俄联合军演举行。从和平使命2005到2007这段时间，中俄联手做成了一件事，就是修建了一条反毒隔离带，完成了对阿富汗的战略包
围。这条隔离带的修建过程中，穆沙拉夫和内贾德两位老兄是出了大力的。

为了保证毒贩子越不了境，穆沙拉扶特意在巴阿边境大量埋地雷、建隔离带。穆沙拉夫在这边一堵，惹恼了那边的美国人。以后，巴基斯坦国内就开始经常发
生严重的自杀式爆炸袭击了，美军越境轰炸的事情也越来越多。其实，这是巴基斯坦为中国的全球战略、也是为自己的国家命运与中国绑在一起付出的代价。
时间将会证明，巴基斯坦付出的代价是完全值得的。

这期间，内贾德也听说美国大兵在阿富汗天天吃香的喝辣的，心里感觉很不痛快，要知道伊朗在美国的制裁之下小日子过的并不滋润，还得拿出钱来安置上百
万的阿富汗难民。内贾德算盘一打，还是把几十万人赶回阿富汗比较划算，让那些有吃有喝的美国大兵照顾好了。当然，被遣返的难民里有多少人被训练成了
反美战士就不好说了，有没有伊朗革命卫队的人化妆成难民去阿富汗旅游就更不得而知了。反正从这以后驻阿美军的日子就越来越难过了。

由于阿富汗对的美国全球战略有着特殊重要的意义（前面已经分析过了），美国必须把这块死棋做活，于是美国开始了艰难卓绝的合纵连横，先拉欧盟后求俄
罗斯，目的只有一个，做活阿富汗这个眼。欧盟正是瞅准了美国需要自己在阿富汗提供配合的机会，让美国吃下了科索沃独立的苦果。这一点后面会详细展开
。

面对着越来越麻烦的中东局势，华盛顿决意冒险一试：

８月27日，萨科齐说伊朗的核计划是世界所面临的最危险问题。28日内贾德马上回应说，萨克奇说的没错，伊朗已经是一个核国家了。9月2日，美国国防部说
已经拟订了打击伊朗的三天闪电作战计划。接着，驻伊美军也遇上了大规模的袭击。看着美军死伤惨重，萨克奇的同情心上来了，跟布什商量，是不是该制定
从伊拉克撤军的时间表了？英国人一听，要撤军？那我先从巴士拉撤军了。要知道，巴士拉有美国最重要的后勤补给线，英国人却没跟美国人打招呼就把它扔
给了伊拉克反美武装。为什么英国人会这么干呢？英国前陆军参谋长杰克逊道出了原因：拉姆斯菲尔德在伊战中的决策纯属脑子进水！其实，这位杰克逊老兄
也参与了当年英美联军出兵伊拉克的决策过程，要说脑子进水，他也有一份。之后，以色列军机侵犯叙利亚领空，对叙利亚进行战争威胁，叙利亚则果断开火
回击。伊朗也马上表态，准备向叙利亚方面提供任何所需要的援助！伊朗和叙利亚那关系绝对是用电焊焊起来的，铁的很！

看着美国真要动武，各方纷纷表态：9月12日，德国反水，不再支持对伊朗实施新制裁；20日，萨科齐摊出底牌，不能接受伊朗拥有原子弹，也不想跟伊朗开
战。10月16日，普京冒着“被暗杀”的风险访问了伊朗，普京在德黑兰明确表态，绝不允许任何人对伊朗进行军事打击。至于中国的态度，那就是谈判，谈判，
再谈判，几年来反复念叨的就是这两个字。

1：3！华盛顿只好放弃了武力打击伊朗的计划，并于25日宣布对伊朗实施新的大规模制裁。

武力解决问题行不通，以一敌三太吃亏，华盛顿只好全面调整自己的战术：

朝核问题上大踏步后退，要钱给钱，要重油给重油，要粮食给粮食，支恐黑名单可以删，只要金爷别再闹事什么都好说。

接着开始跟欧盟谈判：

美国：你得支持我制裁伊朗；

欧盟：可以，但你必须巴以和谈上表示表示；

美国：我可以让奥尔墨特和阿巴斯弄个框架协议出来，不过你不能再帮哈马斯；

欧盟：可以，我现在要通过《里斯本条约》（欧盟政治统一），你不能添乱；

美国：那你也要保证不在伊拉克给我添乱；

欧盟：可以，你还得允许科索沃独立，独立后不能出现武装冲突；

美国：可以，但你要在阿富汗增兵，帮我从中俄的包围圈里面撕个缺口出来；

欧盟：可以考虑。

于是，美欧媾和。从此，中俄欧抗美小组进行半解体状态（欧盟只允许制裁伊朗，不允许打伊朗）。其实，这时欧盟也感觉到了自己在伊核问题上的力不从心
——仅仅要求伊朗暂停铀浓缩伊朗都不买帐。

同时，美国又以肢解伊拉克威胁沙特、伊朗、叙利亚这些国家，不要把自己逼急了，否则谁也别想过好日子。肢解方案已于9月26日在美国参议院通过。

在稳一头、拉一家、吓一片的基础上，加大了对北京的施压，即以台独为威胁（入联公投[fn:jinhong0111]）逼迫北京在伊核问题上让步，同意全面制裁伊朗。

随着华盛顿战略调整的展开，世界局势开始出现新的变化：

巴基斯坦：为了在上合的包围圈里冲出一个缺口，华盛顿开始对巴基斯坦施加巨大的压力。要知道，穆沙拉夫是北京的铁杆支持者，为了逼穆沙拉夫低头，华
盛顿用尽了一切手段，先是多次严重的自杀式暴炸袭击，接着是逼迫穆沙拉夫脱掉军装再参加大选，最后在无法扒掉穆沙拉夫军装时又让巴最高法院对穆沙拉
夫的参选资格裁决拖迟不办，这下子彻底惹恼了老穆，老穆一怒之下宣布国家进行紧急状态，颁布临时宪法，把亲美的大法官乔杜里赶出了最高法院，又逮捕
了大批的亲美人士。然后把自己己的人安上就把资格合法性裁决的事给办了，老穆不愧为军人，办事就是利索，一点都不拖泥带水。小布什也只能接受现实，
为了让老穆脱下军装，小布什又开始狂拍老穆的马屁，说穆沙拉夫是个守信用的人。之后，布托又及时的被炸死了，制造南亚大乱（印巴冲突）的条件具备了
。为什么说布托之死可以导致印巴冲突呢？因为印巴是死对头，只要把杀害布托的恐怖分子往印度这边一引，即可激发巴基斯坦国内的反印情绪，如果此时在
克什米尔地区再出一点擦枪手火的事情，那战争就可以引发。不过局势没有按美国人的思路发展下去，到了08年11月26日，印度孟买又遭遇连环袭击，27日
印度总理辛格就说袭击案可能是由总部设在邻国的恐怖组织策划的，印巴冲突再一次到了一触即发的时候。

欧洲方向：11月16日，欧洲人用一份伊朗核问题报告（巴拉迪做的）提醒美国，巴以和谈得上路了（这份报告没有给出美国人想要的伊朗正在发展核武器的结
论）。27日，安纳波利斯中东和会举行。和会上提出的目标是在以东耶路撒冷为首都的国土上建立独立的巴勒斯坦国。为达此目的，巴以双方准备一年内搞定
耶路撒冷归属、难民回归、犹太定居点合法性、边界划分、安全和水资源分配等一系列问题。需要说明的是，这些问题是搞了几十年都没搞定的棘手问题。这
样的承诺，唯一的作用就是为华盛顿争取一年的战略翻盘时间。

站在欧盟的角度上看，虽然仅仅是在和会上给阿拉伯人画个饼，也足以让阿拉伯人感恩戴德了。会后马上组织捐款，两个月共筹资70亿美元。其中，欧盟6.5
亿美元，美国5.55亿美元，剩下的钱是阿拉伯人掏了。欧洲人一边从巴以和谈上拿到好处的同时，也在着手自己的政治一体化进程：12月21日，《申根协定》
参与国的范围由15国扩大到了24国；同日意法西3国领导人宣布，准备推动地中海地区合作，成立地中海联盟。

【金鸿评论】按华盛顿的设想：拉过欧盟，用台独问题逼北京让步，只要北京让了步，俄罗斯好对付，什么东欧反导、北约东扩、世贸谈判、颜色革命、
原油价格等，随便抓两张牌就可以交换到俄罗斯的伊核配合。可没想到的是，不管是让小布什宣布协防台湾也好，对台售武也好，甚至放风陈水扁已下令研发
核武，都没能换来北京的让步，到最后就是华盛顿用一场入联公投彻底把台独牌打废了。

其实，在伊朗核问题上，中俄的底牌是：美国不让中国加入巴以和谈，伊朗就不会停止铀浓缩。因为中俄的硬挺，伊朗局势进一步恶化。如果不是当时次贷危
机持续恶化的话，华盛顿肯定直接对伊朗动武了。即使如此，08年1月11日还是出现了波斯湾美伊军舰对峙事件，可见当时局势的凶险。这次对峙也是伊朗离
战争最近的一刻。

接下来，华盛顿拼命的催促欧盟增兵阿富汗，1月底，盖茨给德国人写了一份措词异常严厉的信件，要求德国向阿富汗南部增兵。而德国的回复也非常严厉，
不增！不过回过头来德国又温柔的跟华盛顿商量：兵不能增，我多弄几辆坦克到阿富汗怎么样？听到这话小布什的鼻子差点没被气歪了。

按照欧美之间的秘密协议，在欧盟增兵阿富汗之前，美国是不会支持科索沃独立的。但是，中俄在背后硬挺欧盟，在两伊问题上强压华盛顿，华盛顿无奈，只
好答应先让科索沃独立，欧盟后增兵。为什么中俄乐见科索沃独立呢？这要从地中海计划的作用说起。

地中海计划在欧盟的全球经济布局中处于核心地位。欧盟借地中海计划从经济上整合中东，以实现在中东用欧元取代美元的目标，一旦目标完成，美元霸权就
变成了欧元霸权。而美元霸权的旁落是华盛顿绝对不可能接受的。所以，华盛顿必然奋起反击。所以，让科索沃独立可以激化欧盟与美国的矛盾。借着欧元与
美元争霸的机会，中俄各自完成自己的货币国际化之路。当然，随着欧盟地中海计划的展开，俄罗斯的国家战略也发生了显著变化。

2月17日，科索沃宣布独立，华盛顿马上就向国际原子能机构提供材料检举伊朗，说伊朗在发展核武器。这哪是在报案？这明明是催促欧盟快点帮忙通过去伊
朗的制裁决议。同时，为了能让北京支持制裁伊朗，赖斯在2月底访问了北京，华盛顿的方案不外乎是以停止入联公投换来对伊朗的经济制裁。结果北京没答
应。

赖斯刚刚离开北京，中海油就和伊朗石油部签了160亿美元的合同，共同开发伊朗北部的Pars天然气田。到了3月3日，华盛顿才拿到了制裁伊朗的1803号决议
。这份决议还有什么用？北京已经提前用160亿美元的合同把它的效果抵消了。恼怒之下的华盛顿抡起贸易大棒开始对中国进行双反调查。伊朗最高领袖哈梅
内伊则高兴的对外宣布，伊朗在其核项目议题上赢得了一个胜利。

科索沃独立后，欧盟加快了政治统一和一体化进程，扩张的内在动力就更强了。这时，欧盟开始狂推地中海计划，而美国不得不在中东做出让步的姿态。当然
，欧盟之所以火急火了的推动地中海计划，也与次贷危机有关。欧盟必须在美国倒掉之前完成他的政治整合和全球经济布局，否则，一旦美国倒下了，中俄会
及时填充美国败退留下的权利真空区域，内部不统一又没有强大武力保护自己的欧盟在失去了美国的保护很有可能被俄罗斯给抢了，那时也不排除中国趁火打
劫的可能。这也是科索沃刚刚宣布独立后，布朗和萨科齐就要共建全球性欧洲的原因。

对于中俄美三方来说，唯一比较能接受地中海计划的一方就是俄罗斯，因为俄罗斯与欧盟的互补性实在是太强了：欧盟有足够的经济实力，先进的科学技
术和管理经验，却没有强大的军事实力和经济发展所需要的足够资源；而俄罗斯正好相反，有强大的军事实力和足够的资源，经济上却不怎么强，民用科技也
不发达。如果这两家捏合到一起，那可真是珠联璧合。不过，站在欧盟的角度看，资源没有可以从中东和非洲进口，军事实力也可以随着内部政治整合的完成
而增强，所以俄罗斯伸过来的橄榄枝有点一厢情愿的意思。虽说是一厢情愿，普京还真就不客气，不等地中海计划展开，就反客为主杀了进去：

1月中旬，普京访问保加利亚和希腊，三方签署了建设布尔加斯─亚历山德鲁波利斯石油管道的协议；同时，普京在保加利亚首都索非亚宣布，俄罗斯天然气工
业公司和意大利国家能源控股公司就穿过黑海的南流天然气输气管道成立联合设计机构。另外，俄罗斯还搞了一条北流天然气管道，从列宁格勒，穿过波罗的
海海底一直到达德国格赖夫斯瓦尔德。有了这一南一北两条气管，俄罗斯可以把欧盟牢牢的抱在怀中。同时，由于保加利亚和希腊成了俄罗斯的油气中转站，
可以从中获利，自然有了更多的亲俄倾向，通过这种小手段，普京成功的往欧盟大家庭里砸进了钉子。

接着普京后手不断，4月17日，普京访问利比亚，免掉了利比亚45亿美元债务之后又签署了一揽子协议。普京算盘一向打的精，这次放血自有其道理。因为这
个利比亚这个国家现在对俄罗斯的确很有用。利比亚在环地中海国家里面也算大国了，而且出了一个强人卡扎菲。这位老兄可不简单，反帝反殖民主义，坚持
闹革命，一心要统一阿拉伯世界。当年还找我们周总理买原子弹，因为我们总理不卖给他他就开始自己搞，只是最后没成功。就是这么一个反对殖民主义的强
硬派领导人，自然对老牌帝国主义国家在自己家门口摊派什么联盟没好感。而这一点，也是普京最看重的，当然也同样是中美两国所看重的。俄罗斯与利比亚
加强了联系，就可以在以后欧盟力推地中海联盟时多一张要挟欧盟的筹码。同样，看到了这一点的美国也加强了与利比亚的联系，08年9月，赖斯访问利比亚
，“揭开了两国关系的新篇章”。

眼看着不请自来的客人普京赖在自己餐厅里不走，非要等着一起吃晚饭，欧盟是赶又赶不走，打又打不过，顿时没了主意，。不管怎么说，普京的态度还是有
可用之处的，比如眼前的科索沃，如果有俄罗斯人帮忙稳定局势，就会大大减少发生冲突的可能性；再说普京摆出了一副霸王硬上弓的架式，拒绝太困难。所
以，欧盟新关系谈判到了7月份就开始了，从此，欧洲人有了个平衡北约内部敌人美国的新朋友俄罗斯。

当然，不管什么东西，爹有娘有都不如自己有。为了防止美国在关键时候把科索沃搞乱了（那时请俄罗斯帮忙时普京要价绝对低不了），欧盟开始跑到美国人
的后院里找筹码。3月6日，欧盟委员委员米歇尔（注意，这位仁兄负责发展和人道援助事务）访问古巴，欧古关系正常化出现了一丝曙光，此前，法国已经和
巴西进行军事合作，向巴西输出先进的战斗机和核潜潜艇生产技术。中俄也在南美努力的渗透，拿委内瑞拉来说，中国买石油，俄罗斯卖武器。大家都没闲着
。中俄欧心照不暄的进军南美有两个目的，一是抢地盘，二是捡一点讨价还价的筹码。

随着中俄欧这些处来势力的大举介入，有人感觉抢班夺权的机会来了，3月4日，巴西总统卢拉提议，应该成立南美防卫理事会来增强南美国家的国际影响力，
并且感觉巴西人可以作为代表进入联合国安理会当常委。傻子都知道联合国的常委是干什么的。

经过上面的分析之后，大家可能感觉局势变的非常混乱。其实正是如此。这时，次贷危机已经暴发了，所有的国家都身上有严重的内伤，所以，在相互争
斗的过程中，谁也不敢轻易的把招式用老了，以免别人落井下石要了自己老命，都希望别人互欧自己在一边白捞好处。所以，中俄欧美四方不再是简单的谁和
谁是朋友、谁和谁是敌人的关系，而是变成了在这条战线上是朋友、另一条战线上是敌人的关系。简单概括一下，中俄欧美四方的斗争主线主要有：

为了防止欧盟的地中海计划坐大，中俄美三家联手搅局；

为了建立反华统一战线，欧美联手在藏独问题上密切配合；

为了发展自己的实力，俄罗斯在地中海计划上持有条件支持的态度；

为了跟俄罗斯抢夺前苏联加盟共和国，美国政治上拉拢，中俄经济上诱惑；

为了阻止中俄在中东攻城掠地，欧美联手在巴以和谈问题上死死堵住门不让中俄进；

为了对抗美国，中俄欧三方分别在拉美地区积极寻找合作伙伴，拆门罗主义[fn:jinhong0112]的围墙；

为了对抗美国，中俄欧联手在伊核问题上抗美，拥有共同的不允许对伊朗动武的底线；

……

这些主线里面又有一大堆问题，什么伊核六方会谈，巴以和谈，伊拉克重建，阿富汗反恐，朝核六方会谈，格鲁吉亚问题，乌克兰问题，东欧反导，科索沃问
题，美元与欧元争霸，人民币扩张，全球金融危机，地中海联盟，东亚经济一体化……

因为斗争主线的复杂性，从现在开始，以后的局势就按时间顺序做分析，因为所有这些问题都搅在一块了，已经无法再按一条思路一下子理到底了：

安纳波利斯和会[fn:jinhong0113]之后，伊拉克局势依然混乱，伊朗铀浓缩依旧停不下来，这就导致了奥尔墨特和阿巴斯之间的框架协议没有任何进展，这也让此前心存幻
想的阿拉伯人非常失望。到了1月23日，在埃及的默许下，哈马斯炸毁了加沙与埃及之间的一段隔离墙，大量巴勒斯坦人进入埃及城镇拉法抢购生活用品。这
一事件宣告美以饿死哈马斯的政策失败。之后，华盛顿再次改变中东策略，拿出戈兰高地[fn:jinhong0114]诱惑叙利亚，条件是叙利亚与伊朗保持距离，结果被叙利亚拒绝。

2月25日,韩国的李明博上台。李明博将来肯定是个要被清算的人物，他最大的特点就是不自量力。他在努力的执行亲美路线，可是，得到的只是自取其辱。试
想一下，经济规模10倍于韩国的日本都在东北亚翻不起浪花来，一个小小的韩国又能做的了什么呢？除了挨北京的耳光，它什么也得不到。李明博的亲美政策
使它在关键时候放弃了本该属于自己的发展机会（加强对朝鲜的经济渗透），客观上起到了封杀自己发展空间的作用，从此以后，韩国经济开始走下坡路了。

3月份是中国比较被动的一个月，先是藏独闹事，接着是入联公投。应该说，台独对中国来说是个麻烦，藏独却算不上什么大问题。台湾目前处于独立状态，
北京对它没什么控制力，一旦闹起来，战争的范围可能会扩大到整个东南沿海；而西藏不一样，它在领土范围内的，不管藏独分子怎么闹都好办，大不了派兵
镇压，抓不上三千人，局势就平定了。在07年欧美媾和之前，为了表示诚意，墨克尔曾打出过达赖这张牌，以此彰显欧美两家有着共同的价值观。欧盟在西藏
问题上的挑衅，务虚的成份居多，北京最多是面子上不好看，实质上的伤害是没有的。

至于322入联公投，更是把台独牌彻底打废了。美国打台独牌是希望日本也加入战场与中国动武，但如果日本不参与，台湾是没有多少抵抗能力的。通过这次
的入联公投，华盛顿和北京都彻底看清了日本的态度，那就是绝对不做火中取栗的事。入联公投的前一天，海上自卫队参谋长吉川荣治已经被免职，同时有90
名官员受到了处罚。安倍晋三用事实向小布什证明，如果台海有事，就别指望日本人了，日本海军的指挥系统已经出问题了。至于那个台湾之父李登辉，更是
神领神会的忘了投公投票了！

进入5月份，又一场灾场降临到了中华民族的头上，这就是汶川大地震。这次地震在带给中华民族巨大伤痛的同时，也把中华民族的凝聚力和无私奉献的精神
淋漓尽致的展现了出来。所有人都看明白了，中华民族依然是不可战胜的。

在中国发生大地震的同时，缅甸也遇上了强热带风暴，超过13万人死亡和失踪。借着这个机会，美欧联手打着救灾的旗号要强行进入缅甸，在中国的南大门上
砸个楔子，结果被中国挡了回去。

6月10日，驻阿美军空袭了一个巴基斯坦边境检查站，穆沙拉夫与小布什的矛盾彻底激化。这一事件也埋下了穆沙拉夫下台的种子。年初穆沙拉夫曾警告过小
布什，如果美国敢在巴阿边境开展单边军事行动，美军将一定被视作侵略者。这次美军的空袭就是巴基斯坦对美国的单边军事行动忍无可忍后发动反击引起的
。事后，美国挑动各派势力弹劾穆沙拉夫，失去了军方支持的老穆在选择了主动辞职。个人对老穆的下台深感惋惜，他实在不应该交出军权，老穆是靠这军人
政变上的台，怎么能把军权放了呢？军权是他在台上的基本保证，可惜，他放弃了。

7月13日，地中海峰会在巴黎召开，会上宣布地中海联盟正式启动。不出所料的是，法国和意大利轮流邀请的卡扎菲没有参会，原因嘛，这个计划企图破坏阿
拉伯国家和非洲国家的团结，真有心合作那就和阿盟和非盟地起搞，不是只拉一部分国家。应该说，卡扎菲的这个觉悟还是相当高的。

下面再从经济层面分析几个问题：

进入07年后，为了扭转被动局面。华盛顿也从经济上加大了打击中国的力度：一面要求人民币升值以减少逆差，一面开始对华抡起贸易大棒，一面疯狂拉抬大
宗商品价格，石油涨价，金属涨价，粮食也涨价，不惜一切代价向中国输入通货膨胀。在这些涨价的大宗商品中，原油对世界经济的影响无疑是最大的，它的
价格上涨也是最疯狂的，03年国际原油全年每桶平均价格只有27.4美元，07初已升至50美元，到08年7月更是达到了惊人的147美元。

对于华盛顿提出的人民币升值，不是不可以，人民币长期徘徊在低位对中国的经济结构转型也没有什么好处。这就象一个小孩子整天弯着腰走路上学对他的身
体成长没有任何好处一样。人民币升值可以淘汰那些没有技术含量的出口加工型企业（血汗工厂），也可以起到提高资源价格减少资源出口的作用，这些对于
中国产业结构提升都是大有好处的。只不过，人民币升值的速度要我们自己说了算，升值的节奏更要由我们自己说了算，只有这样才能保证经济结构的稳步转
型。

具体的办法是这样的：经过一轮升值淘汰一批企业的同时扶持一批，被扶持的企业经过几年壮大后再升值一轮再淘汰一批企业，再扶持一批……北京的手法，恰
恰反映了这样的思路，05和06两年人民币小幅升值了4.6%，给众多的出口企业提醒“要变天了”，之后的07和08两年人民币大幅升值了16.4%，两年时间淘汰了
一大批企业（珠三角有大量企业关门），同时扶持了一批有高技术含量的企业，接下来的09年和10年两年，人民币仅升值1%，这是在为新扶持的企业提供了缓
冲期。

对于华盛顿砸过来的贸易大棒，北京则以忍为主。没办法，经济结构严重失调，卖给人家的是些谁都也生产得了的低端产品，在完成经济结构转型之前，大棒
是不得不挨的。不过，华盛顿的大棒也是绊马索性质的——只是为了给中国的经济发展制造麻烦，并不是真要和中国彻底决裂。要是真决裂美国还没那本钱，因
为中美贸易实际上是美国用白条（美元）来换中国生产的生活必需品。一旦决裂，中国没有白条可以活，美国人没了生活必需品想找个国家替代中国临时还真
找不到（没有第二个国家有中国这么大的产能）。

正是由于中美贸易的这种畸形，才造就了中国天量的美元储备。当然，天量美储的出现，还有两个原因，一个是美国为了实现先在中国制造经济泡沫再刺破以
掠夺中国人民财富的目的，把巨量的热钱通过地下走私到了中国国内；另一个就是中国为了整合东亚经济，实现对东亚产业链的控制，通过经济手段把东亚各
国的出口慢慢集成进了中国对美国的出口，东亚各国对美国的直接出口则减少了，这样一来，本来分散打给各国的白条大部分集中打给了中国。这样做无疑会
加大中国的风险，不过也有好处，那就是一旦中国狂抛美国国债，美国经济可以就崩溃了，中国也因此而找到了一座可以牢牢压住华盛顿的五指山。在了这座
五指山，人民币再搞扩张、争夺全球金融主导权（叫霸权也可以），美国只能争一只眼闭一只眼。这就是中国手里有巨额美储的最大好处。

大宗商品的暴涨，的确给中国经济带来了巨大的麻烦，仅猪肉价格翻番一项就给人民生活带来了大麻烦，更不用说原油价格的暴涨造成的全面通胀了。当然，
这一切中国还是可以顶的住的，不过一些小国就难说了。

最先遇上大麻烦的是越南。08年5月份越南的的CPI指数涨幅超过了25%，股市从07年年初的1100多点下降到370多点，跌幅达60%以上（而此前的一年多越南股
市暴涨近5倍，房地产市场价格也大幅上扬），楼市也开始大跳水，贸易逆差陡增；紧接着，美国的三大评级级构标普、穆迪、惠誉把越南长期债务评级展望
由稳定调低至负面。此前过度流度的外资开始大量撤离（之前的股市和楼市泡沫就是大量热钱流入后推动的），汇率大幅贬值，这时的越南出现了要被剪羊毛
的迹象。5月底，越共中央书记农德孟带着15吨的抗震救灾物资来北京求援。在与温家宝会见时，中越双方强调要加强中越经贸合作；访问结束后，中越两国
还建立了领导人热线电话。之后，越南的金融动荡局势就慢慢扭转了。另外，对比一下越南这次的金融动荡与09年年底出现的希腊债务危机，华盛顿的操作手
法有无相似之处？

有句俗话叫做几家欢乐几家愁，这句话用在原油价格暴涨给各国带来的后果上是非常合适的。在大多数的发展中国家为了高油价发愁时，普京却在高兴的大把
数银子。当时的俄罗斯，原油产量已经超过了沙特阿拉伯，成为世界上最大原油出口国。而且，普京正拿着高油价换来的巨量美元满世界的搞投资。

在高兴之余，俄罗斯也非常警惕握在美国人手里的石油定价权。要知道，当年苏联解体就与原价被操纵有相当大的关系。当时，苏联经济对石油出口的依赖很
大，油价一降苏联的出口换汇能力就跟着降。85年11月，在美国和沙特的联合操纵下，原油价格跌到了12美元（半年前是30美元），再配合着美元的贬值（广
场协议），慢慢把苏联经济拖入了绝境。08年俄罗斯人还做过专门测算：如果09年油价跌到每桶25美元，俄罗斯政府收入将锐减9％；那时还会出现占GDP7％
的财政赤字。为了防止灭国悲剧的再次重演，俄罗斯开始争夺石油定价权。6月6日，俄罗斯国际商品原料交易所在圣彼得堡成立。普京将俄罗斯混合原油期货
(REBCO)从纽约商品交易所撤走，重新在俄罗斯国际商品交易所挂牌交易，从此普京开始与华尔街争夺石油定价权。

我们都知道，美元之所以拥有霸权地位，是因为石油交易用美元结算。如果石油定价权被夺走了，美元霸权也就完蛋了。所以，石油定价权是美国人的命根子
。现在普京居然来揪美国人的命根子，这还了得？美国马上展开反击。

美国人的反击手段有两招：一是反手做空油价，油价在7月见顶之后迅速回落，到年底打穿了80美元关口（79.36美元），到09年2月油价最低时跌至34美元。
随着原油价格的暴跌，俄罗斯也被拖入了经济危机。第二招就是唆使格鲁吉亚在8月8日奥运会那天进攻南奥塞梯，这时，俄罗斯不得不动武了。如果任由格鲁
吉亚平定了南奥塞梯，大了胆子的萨卡什维利马上就能加入北约，紧接着就是乌克兰。真到了这一步，美国人的枪可就直接顶在老熊的胸口上了，俄罗斯还有
什么国家安全可言？于是，俄罗斯马上命令北高加索军区第58集团军发动了闪电战进行回击，不到两天就彻底击溃了格鲁吉亚部队，华盛顿没能为格鲁吉亚提
供任何军事支持。接着欧盟迅速介入调停，以格鲁吉亚的不再武力解决南奥塞梯及阿布哈兹问题换来了俄罗斯的停火。15日，默克尔与梅德韦杰夫会谈，共商
缔结了《新欧洲安全条约》倡议。

被晾在了一边的美国人开始给欧盟上眼药：

9月5日，赖斯访问利比亚，进一步在地中海计划中掺起了沙子；

12日，阿巴斯又说，自己对年内能否达成和平协议表示悲观，警告欧盟悠着点儿；

18日，赖斯发表对俄铁幕式演说，暗示欧盟要跟俄罗斯保持距离，不然地中海联盟肯定要黄。

面对着美国的警告，欧盟又是如何回应的呢？25日，德国财长施泰因布吕克在议会发言时说，美国已经丧失了超级大国地位，现在要摆脱困境只能依靠亚欧帮
助；同日，法国总统萨科齐呼吁重建国际金融货币体系。法德两家真是串通好了，说话不光一个调，还是同一天说的。

接着，俄罗斯拉着查韦斯一起搞国际石油银行，又申请加入欧佩克，欧佩克也说，不排除接纳俄罗斯！大家都知道俄罗斯这时想加入欧佩克是为了争夺石油定
价权的，欧佩克接纳俄罗斯就就不怕美国报复？其实他们是在暗示美国，油价压的太低了，日子过的紧哪。

在欧盟和俄罗斯的联合挤压下，华盛顿压力空前，不得不选择对北京示好来为自己减压：10月16日盖茨说，中国是美国的竞争者，但不是冤家对头，如果两国
对抗那将是悲剧性错误（此时已不是三年前拉氏高调中国威胁军事论的时候了）。接着在24日对中国放水，接纳中国成为泛美开发银行第四十八位成员。凭此
资格，中国可以参与该银行在拉美地区资助的项目。这时，从华盛顿那里拿到了好处的北京开始表态了，我也认为有必要进行金融改革，但是……但是什么呢？
但是，欧盟打算拿多少好处出来让北京支持改革。结果呢，欧盟不但没大大方方的表示一下，反而掏出达赖这张牌跟美国哥俩好——霸权归你归我不都一样吗？
肥水不流外人田嘛。欧盟此举招致的后果就是北京立即无限期取消了中欧峰会。在随后举行的华盛顿金融峰会上，欧洲人也什么都没捞到。



** 【金鸿评论】04年以来的大国斗争回顾（下）
[2010-09-2721:56:46]



【金鸿评论】进入09年以后发生的第一件大事，应该是海湾六国计划在2010年发行单一货币海元。如果中东有了海元，那就没有美元什么事了，更没有欧元什么事了。这一消息的警告味道是非常足的。为什么阿拉伯人要发出这样的警告呢？

因为他们等得不耐烦了——安纳波利斯中东和会上许下的一年期限已经过去了，巴勒斯坦建国的事情依然没有任何进展。再不给欧美两国提个醒，真不知道他们还会拖到猴年马月。

这时，被阿拉伯人冷落了很久的哈马斯看到机会来了，以停火协到期为由开始对以色列发射火箭弹，以色列则马上进行狠辣报复。以色列的黑手引起了众多阿拉伯国家的强烈不满，他们就开始拒绝出席有以色列参加的地中海联盟会议。这倒好，哈马斯的火箭弹把地中海计划打残废了。

哈马斯这么着急动手，主要原因就是一个字：饿。再不把以色列的铁桶阵打开个缺口，他们真要活不下去了。应该说，这次交火中以色列出手非常狠，连白磷弹都用上了，不过打到了关键时候又出现了插曲，有从黎巴嫩方向打出的火箭弹问候了以色列一回（深入以色列境内42公里）。接着，真主党和哈马斯都宣布此事与自己无关。

这几枚火箭弹提醒了以色列，也提醒了美国，该接受中国调停了[fn:jinhong0115]。这时的华盛顿已被国内的金融危机搞得焦头烂额，连句硬话都说不出来了，还是让捷克出来替自己表态，“以色列打的对，打的好！”欧盟呢，说话更是没人听，之前在安纳波利斯峰会上他们可是巴勒斯坦建国的保人，还让阿拉伯人掏了50多亿美元的建国费，
#+HTML:<a>现在国也没建成，钱也不知道弄哪去了</a>
#+LaTeX:\red{现在国也没建成，钱也不知道弄哪去了}
，阿拉伯人不找他要帐就不错了。这一次，阿拉伯人的火气是特别的大，个个拍着桌子嗷嗷叫唤，狠不得把以色列一口吞了。这时，北京的特使来到了中东，沟通各方，迅速达成了一份新的停火协议。

欧盟是最希望停火的，北京就卖了个面子给欧盟，签了份比上一份长一年的协议，给欧盟安心搞地中海计划准备了充足的时间；北京也顺手托了埃及一把，以前只有以色列控制的一个口岸可以进出加沙，新协议上又增加了一个加沙与埃及之间的口岸，埃及就多了一个可以与美国和以色列讨价还价的筹码。就这样，皆大欢喜，北京漂漂亮亮的当了一回和事佬。

2月份的大事是新星号事件。在新星号事件以前的三年半多的时间里，中俄一直配合默契；新星号事件后，中俄关系出现了裂痕。这一事件的发生，与北京插手吉尔吉斯斯坦关闭美军基地的事情直接相关：

2月5日，吉尔吉斯斯坦表态，准备关闭美国在该国的马纳斯空军基地；

同日，美国白宫发言人说，马纳斯空军基地对美国至关重要，希望继续与吉方合作。

2月12日，吉尔吉斯斯坦废除了与11个国家的基地使用协议，这11个国家大都是欧盟成员国，但保留了和美国的协议；事后俄罗斯有外交官说，中国不会在关闭吉尔吉斯斯坦基地问题上保持沉默（而是会使小动作）；

2月13日，俄边防军舰把中国货船新星号击沉，并迅速宣布击沉行为合法；

2月23日，朝鲜扣留俄罗斯货船丽季亚杰梅什号，理由是侵犯领海；

6月23日，吉尔吉斯斯坦公开表态，同意美军继续使用马纳斯空军基地。

7月7日，吉尔吉斯斯坦批准俄罗斯在其南部建立第二个军事基地。

7月20日，巴基耶夫辩解说俄在吉南方设立的不是军事基地，而是培训中心。

8月3日，乌兹别克斯坦声明，反对俄罗斯在吉尔吉斯设立新的军事基地并增派驻军数量。理由是这会加速地区军事化进程，严重影响地区局势稳定。

俄罗斯在吉尔吉斯挤兑美军基地并为自己新建基地的做法，很显然是为了增加对中亚国家的控制力（为了更有效的控制中亚国家，俄罗斯还专门把这些中亚国家拉进来建立了一个组织，叫做独联体集体安全条约组织，简称集安组织[fn:jinhon0116]），但是，关键时刻跳出来指责俄罗斯的恰恰是同属集安组织的乌兹别克斯坦。很显然，支持乌兹别克出来搅局的是北京，要知道05年乌兹别克发生颜色革命时卡里莫夫是在北京的支持下才稳定住局面的。之后俄罗斯在吉尔吉斯安插军事基地的计划流产。2010年4月，巴基耶夫被俄罗斯人搞下台，随后马上传出了俄罗斯计划在吉尔吉斯斯坦建立第二个军事基地的消息。

为什么中国会出手阻止吉尔吉斯斯坦把美军赶走呢？这与当时普京的战略调整有关：欧盟力推地中海计划以后，俄罗斯积极加入，俄欧关系日益亲密，华盛顿布置在欧盟与俄罗斯之间的隔离带有被俄欧联手拔掉的可能。这时美国人决定，再向俄罗斯让步，以中亚和东欧的全面让步（任由俄罗斯恢复对中亚国家的影响力和不再搞东欧反导计划），换取俄罗斯阿富汗支持（从俄罗斯运输物资到阿富汗而不再经过巴基斯坦）和对伊朗的经济制裁（此前已得到欧盟对伊朗的经济制裁配合）。美国人这样做，也是无奈之举，既使他不把东欧和中亚送给俄罗斯，随时俄欧关系的密切，两家同样可以联手把美国挤出去。反正是要失去的东西，能换点什么东西回来就换点回来好了。

如果美国与俄罗斯完成了战略交换，美国就可以搞乱巴基斯坦，从克什米尔切断中国的西进通道，再对伊朗进行武力威慑，这时就有可能使伊朗屈服。如果局势真正发展到了那一步，中国只有不惜一切代价反击美国：直接支持阿富汗反美武装，兵进巴基斯坦，其他方向上的动作就要视当时的全球局面而定。一旦中国正面与美国摊了牌，美国只能更加的依赖俄罗斯的配合，俄罗斯则可趁机拽着欧盟在中东攻城掠地，石油定价权也能从美国手里抢过相当一部分。接下来，俄罗斯彻底击倒美国将再无悬念，欧盟也将慢慢成为俄罗斯挟持下的人质。到那时，俄罗斯将成为最大的赢家，中国亏多少，就看中美对决的残酷程度了。

这时，俄美之间已经表现出了利益交换的迹象，巴基斯坦通道上也开始承受强大的压力，为了避免让中国陷入上面提到的被动局面，中国只能好好敲打俄罗斯一下，出手搅黄了吉尔吉斯斯坦军事基地的事，警告俄罗斯不要只顾自己的私利，损害了中俄联合的大局，否则俄罗斯得到的绝对比失去的要多。中国对俄罗斯的警告立即引来了俄罗斯的报复，这就出现了新星号事件，之后中国安排朝鲜出手也扣了一艘俄罗斯货船，暗示不排除取消俄罗斯在朝核六方会谈上的发言权，这时，俄罗斯的态度才慢慢有所转变。

随着中俄矛盾的暴露，美国和欧盟对俄罗斯态度的态度也生了转变：美国并不愿意通过自己对俄罗斯的让步换来一个跟中国拼命的结果，所以中国在吉尔斯吉挡一下的机会，美国重新开始做吉尔吉斯斯坦的工作，吉尔吉斯的巴基耶夫本来就是在美国支持下通过颜色革命上的台，现在中国也支持保留美军基地，自然这个基地就留下了；欧盟也深知没有中国的配合，俄罗斯不可能从美国那里拿到什么好处，于是也借着中俄出现矛盾的机会，加大了对中亚国家的经济渗透，气得普京对欧盟恶语相向。这时，轮到俄罗斯承受压力了。

3月份是各方准备伦敦金融峰会的时间。这次欧盟和美国的表现完全调了个个：上次没能从华盛顿峰会上捞到好处的欧盟这次学乖了，主动把达赖牌收了起来，并让中国的赴欧采购团满载而归（中国采购团采购的主要是航天航空、电子、环保等领域的技术和设备）。借着欧美国家经济危机的机会，大量引起尖端技术，可以加快我国产业结构的提升速度，为下一步的赶超打好基础。

华盛顿一看：上次你从我后院里吃了一顿，这回欧盟又拿先进技术喂你，这样下去，等着不到金融危机结束，两家就被你吃穷了。于是，拉着欧盟的手一起来对付中国。他们安排国际刑事法院给苏丹总统巴希尔判了刑[fn:jinhong0121]（理由是战争罪和反人类罪），警告中国注意自己的海外利益。给在位总统判刑，这对国际刑事法院来说，也是大姑娘上轿头一回。不过，这回的轿子不稳当，国际刑事法院招来了非盟和阿盟的狂批。

接着，美国又在南海挑起了中美船舰对峙事件，想用中国与东南亚国家的领土问题绊住北京，结果北京把渔政执法船派到了南海，稳住了局面。之后，美国再次喊出了协防台湾的大话，并要捆绑钓鱼岛。北京也毫不客气，再次激化伊朗核问题，向美国伸手索要巴以和谈的门票，这时的华盛顿对伊朗毫无办法，只好来了个掩耳盗铃：我知道伊朗能造原子弹，但我也知道伊朗这两年不急着造，他怕别人找到制裁他的理由——既然没有理由，那凭什么在联合国安理会通过了制裁伊朗的1737、1747和1803号决议？说这样的话不是打自己的嘴吗？

随时峰会召开时间的临近，各方的表现也越来越激进：

周小川说，这个美元毛病太多，问题成堆，应该考虑在国际储备中扩大特别提款权的用途[fn:jinhong0117]；奥巴马说，这可不行，美元眼下格外强劲，根本不用新设国际货币[fn:jinhong0118]；萨科齐马上威胁道，不管怎么说，加强金融监管的要求美国人必须得答应，否则这会我就不开了[fn:jinhong0119]；麻生太郎一听，马上掏出1000亿美元借给欧盟说[fn:jinhong0120]，别上火，不就是缺钱嘛，我们大和民族有的是（其实钱是被美国人逼着掏的），回过头来，打肿了脸还要充胖子的麻生大声呼喊：我们日本人将在峰会上扮演领导角色！

前台吵得热火朝天，后台也有人在自己找事干，这人是谁呢？就是那位刚刚被国际刑事法院判了刑的巴希尔。巴希尔是先访厄立特里亚和埃及，再去埃塞俄比亚，最后又到了卡塔尔。要知道，按国际刑事法院的说法，只要巴希尔一离开苏丹领土，就会被人抓起来。结果谁也没想到，巴希尔运气这么好，转了四五个国家愣是没碰上一个警察！害得出席阿盟会议的潘基文还是躲着巴希尔不敢见面——联合国秘书长总不能亲力亲为客串一回警察吧？倒是有33个非洲国家宣布支持巴希尔，准备退出“殖民者”控制国际刑事法庭。

为什么这时没人再提抓巴希尔的事了呢？道理很简单，峰会召开前，为了向北京施压，欧美联手判了巴希尔的刑，现在要开会了，
#+HTML:<a>谁也不愿意把北京推到自己对手的怀里去</a>
#+LaTeX:\red{谁也不愿意把北京推到自己对手的怀里去}
，所以，这时再也没人出头让国际刑事法庭抓人了。

从各方的态度中足以看出，大家是多么在意峰会的结果，那么，峰会到底开出了什么结果呢？

首先，第三世界国家的利益得到了保证，中国、巴西、印度力主的刺激需求保证就业和反对贸易保护主义的要求得到了各方支持。要知道，
#+HTML:<a>以前的经济危机发生时，市场需求锐减，制造型企业会大量破产，这是金融资本家们借机大量收购企业、扩充实力的好时候，等他们吃饱喝足了，再放松银根刺激需求把市场激活，经济危机就结束了。</a>
#+LaTeX:\red{以前的经济危机发生时，市场需求锐减，制造型企业会大量破产，这是金融资本家们借机大量收购企业、扩充实力的好时候，等他们吃饱喝足了，再放松银根刺激需求把市场激活，经济危机就结束了。}
这次金融危机如果再让欧美国家的金融资本家们得逞，那这场经济危机，就不是欧美国家的经济危机而是经济机遇了。

刺激性的经济政策和反对贸易保护主义的措施，恰恰可以减轻发展中国家制造型企业的生存压力，如果手法操作到位，还将成为发展中国家反攻欧美国家高端高场的机会。难怪峰会结束后巴西总结卢拉握着胡哥的手说，感谢中国为这次峰会的成功作出的重大贡献，并拍着胸脯保证坚决支持人民币国际化[fn:jinhong0122]。

其次，欧盟也捞到了一点好处。欧盟力推的、打算用以主导世界金融秩序的IMF[fn:jinhongj0123]得到了加强，可用资金提高到了7500亿美元，并增加了2500亿美元的特别提款权，欧盟非常希望的加强对金融机构、对冲基金和信用评级机构监管得到了一定支持。不过，在欧盟最关心的美元霸权为欧元让路问题上，美国没了态度。

4月5日，朝鲜发射了一枚火箭[fn:jinhong0124]，据说里面装的是光明星2号通讯卫星。朝鲜为什么要在这时发射卫星？这与年初的局势直接相关。当时，华盛顿希望通过对俄罗斯让步来围堵中国。北京就给华盛顿出了这道题：真打算在跟我撕破脸吗？那给你个机会。我让朝鲜打一颗洲际导弹，你敢拦否？

如果华盛顿真的拦截了，那就证明之前对欧盟、对俄罗斯的让步都是实的，否则，就是虚的。而朝鲜发射火箭时华盛顿的表态是：我知道是朝鲜发射的是火箭不是卫星，但我不拦（盖茨语）[fn:jinhong0125]。

在朝鲜挂着发射卫星的头羊卖了发射洲际弹道导弹的狗肉之后，美国感觉面子上有点不好看，就拉着日本韩国一道要在联合国群欧朝鲜。这时，中俄站了出来，声明将否决任何制裁朝鲜的议案，结果，美国只弄到了一份没有任何价值的谴责朝鲜的主席声明。值得注意的是，这时俄罗斯的立场已从新星号事件上大踏步后退了。

按道理说，朝鲜把能威胁美国的洲际导道打出去后，只挨一份不疼不痒的谴责声明已经很不错了——吓唬黑社会老大还不是滔天大罪吗？可是金正日那几天辣椒吃得太多上火了，马上以火箭发射被遣责为由退出六方会谈，恢复了去功能化的核设施[fn:jinhong0126]。伊朗一看，朝鲜这么穷的国家都能发射卫星，我也能。其实，朝鲜之所以退出六方会谈，是因为克什米尔地区又起枪声，美以两国也在举行防止伊朗核武化的军事演习，导致了伊核局势的再度紧张[fn:jinhong0127]。伊朗发射卫星[fn:jinhong0127]，其实是在向美国示威，并展示两核问题的配合默契的——别光顾我这西边，东边也不太平！

华盛顿不得已，用巴以和平两国方案拉住欧盟，来稳固巴以和谈这条防线[fn:jinhong0129]。得到了机会的欧盟顺势重新启动地中海联盟。这时哈马斯站出来搅局，表态永不承认以色列，准备找机会否决两国方案[fn:jinhong0128]。

在稳住防线的同时，华盛顿也对北京展开了反攻，战线有两条：

一是继续续在南海领土问题上消耗中国，由美国撑腰，越南、菲律宾、马来西亚、印尼等国轮翻在领土争端问题上挑衅中国；

二是试图切断巴基斯坦通道，这方面美国的动作实在是太多了，一会儿暗示要强行接管巴国核武库，一会儿轰炸巴阿边境，一会儿又逼着印度在克什米尔搞印巴冲突，最后，快要被逼得发疯的扎尔答里[fn:jinhong0130]只好拼命的向北京求救。

对于华盛顿的进攻，北京也准备了几手：

南海方向：用船舰对峙的方式警告华盛顿，休想躲在后面捡便宜，接在南海颁布了禁渔令[fn:01jinhong0131]镇住了小鬼们。在朝鲜二次核爆之后，美国宣布不会介入南沙群岛的纷争。

巴基斯坦方向：让朝鲜进行了二次核试[fn:jinhong0132]，巴基斯坦局势马上就稳定了；这时还出了一个笑话：奥巴马对朝鲜的核试非常恼火却又无计可施，就开始装糊涂：这好象不是原子弹爆炸吧？结果俄罗斯人一语揭穿：怎么不是核爆炸？跟当年你们扔给日本广岛的那颗当量一样大，我们测量过！

印度方向：应该说印度压力是很大的。在此之前，为了逼印巴互欧，先是说刺杀布托的凶手来自印度克什米尔，再说印度911[fn:jinhong0134]是巴基斯坦军方干的，最后再从孟买搞了一伙人去巴基斯坦袭击斯里兰卡板球队，幕后的人真是心血废尽。为了给蠢蠢欲动的印度一个警告，北京支持斯里兰卡政府把与印度瓜葛极深的斯里兰卡猛虎组织被消灭了[fn:jinhong0133]，之后印度也就规矩多了。

在打退华盛顿攻击的同时，北京也展开了反击。6月底，北京再次力超主权储备货币[fn:jinhong0135]，支持欧元继续闹革命。接着，梅德韦杰夫也表态，支持北京的构想，接跟着印度也加进来一起批判美元………看到如此火红的革命局面，欧盟心里乐开了花，摩拳擦掌，准备在接下来举行的G8峰会上大干一场。

为了减少压力，华盛顿安排热比亚策动了乌鲁木齐七五暴力事件[fn:jinhong0136]，之后胡主席不得不提前回国，奥马巴在G8峰会[fn:jinhong0137]上的压力顿时大减。之后，为了给北京加压，有人又要把15名东突头目弄进台湾[fn:jinhong0138]，接着，驻阿美军就遭遇了血腥一周，4架直升机被毁[fn:jinhong0139]，血淋淋的形势吓坏了东突头目们，也就再没有进台湾的事了。

从这时起，北京减缓了在中东方向（巴以和谈）的进攻速度。因为在过去的三年里，大国斗争盘面上的发生了太大的变化：

#+HTML:<strong><h3>
#+LaTeX:\red{
06年4月，伊核局势第一次激化（伊朗发现武器级浓缩铀），引来了美国企图武力解决伊核问题和哈马斯，后被北京用朝鲜导弹发射和真主党抓人化解，接着美国想要强行切断巴铁通道，引来了朝鲜的第一次核爆，此后局面暂时得到稳定。借着美国在中东被缠住手脚的机会，中国展开了全球布局。

07年7月，伊核局势第二次激化（内贾德说伊朗已是核国家），美国再度武力威胁打击伊朗，被中俄欧三家联手顶住，接着美国选择了对欧盟在巴以和谈问题上让步，从那以后，科索沃独立，《里斯本条约》出炉，地中海计划启航，欧盟得利；

08年6月，俄罗斯发力，争夺石油定价权，美国为自保挑动格鲁吉亚闹事，后被俄罗斯肢解，欧俄开始战略接近，俄罗斯得利；

08年12月，中国与韩国签署了1800亿元货币互换框架协议，人民币迈出了成为全球硬通货的关键一步，中国正式登场争夺全球金融霸权，这又引得美国联合欧盟与中国大打贸易战，同时准备对俄罗斯让步（放弃东欧反导和中亚方向），以联合俄欧对付中国。
#+HTML:</h3></strong>
#+:LaTeX:}

按美国的意图，是通过对欧盟在科索沃和巴以和谈上让步换取欧盟的伊朗制裁案和阿富汗增兵，通过对俄罗斯的中亚让步和撤销东欧反导来换取俄罗斯的伊朗制裁案与阿富汗配合，再与东盟签署《东南亚友好合作条约》、亲自上阵从南海方向对中国的施压，再加上李明博的到处找麻烦和日本的搅局，就可以给中国施加巨大的压力。

在此以前，盘面上是中俄欧三家联合抗美的，现在盘面上有可能出现北京以一对三的情况，这种局面是非常危险的，也是是北京必须避免的，如果实在躲不开
，那也得找到新的化解之道。

美国对俄罗斯的让步是08年年初开始放风的，俄罗斯表现出了浓厚的兴趣，随后中国对俄罗斯进行了警告，接着俄罗斯的立场重新调整了回来。可是，到了9月份，奥巴马还是宣布放弃东欧反导计划，为防意外发生，北京也调整了自己的策略以应对盘面上的变化。

为了拆解美欧媾和，北京的办法是努力推动欧元与美元争霸，逼美国在中东对地中海计划的让步做实。这时，眼看着勾引人家要变成了陪人家上床，奥巴马不干了，马上撕去了伪装，在09年年底引爆迪拜债务危机，接着又引爆了希腊债务危机，欧美反目。

下面，先换个话题，说说北京如何收拾李明博的：

要说这李明博，可真是个人物，只可惜，心比天高，命比纸薄，如果早年把名字改成李心高，可能运气会好一点。这个李明博，一上台就先声夺人，要拿400亿美元买断朝鲜的核政策。其实，朝鲜哪有什么核政策？那是北京手里的一张牌而已。李明博拿着400亿美元找金正日，是装傻还是真傻？接着，李明博又宣布把朝鲜的弃核进程与韩朝经济合作挂钩，并说不排除对朝鲜实施极端措施，还拿着在韩国布置反导系统向北京示威，气得金正日马上打了几发短程导弹对李明博进行了初次警告。再往后，金正日对李明博的媚美政策越来越反感，先后掐断了南北对话和金刚山旅游项目，直至与韩国断交。要是换个人，就借坡下驴以后规矩点算了——韩国经济是能离的开朝鲜还是离的开中国？如果真有本事翻脸你为什么第一个中国搞货币互换？可李明博不是，非要在人前装那大尾巴狼，结果招来了金正日的一顿狠扁。

到了09年3月，李明博又搞了一个比400亿美元买朝鲜原子弹更大的计划——让韩国成为全亚洲的领导者。如何实现呢？通过加强跟澳大利亚和印度尼西亚加强联系来达到目标。

这个计划其实是在给北京找麻烦：中国正在主推10+1、兼推10+3，现在李明博倒好，从这“10”里面抠出一个排华传统悠久的印尼、再拉上一个不在东亚户口本上的澳大利亚搞起来了小团体，这摆明是要拆北京10+3的台！试问，还有比他更欠揍的人物吗？结果，李明博的计划刚刚摆出来一天，朝鲜就宣布，切断朝韩之间最后一条军事热线，准备战斗！

接下来，到了朝鲜发射卫星的时候了。在卫星发射前，韩国的态度是：调整飞机轮船行线，免受卫星威胁，跟华盛顿的不拦截态度完全一致；卫星发射后的态度是：宣布准备加入防扩散安全倡议，配合华盛顿经济上围堵朝鲜。朝鲜则强硬回应：韩国加入防扩散就是宣战！

到了五月份，李明博又跑到中亚搞资源外交，这回李明博出门肯定没看黄历，所以走到半路上行程就被人掐了一截，刚刚回国又遇上了朝鲜的二次核爆，也够倒霉的。按理说，你流年不顺就少说少做，免得不自在。可他还不，非要跳出来逞逞能。这回李明博又出来指责朝鲜，说二次核爆是绝对无法容忍的挑衅行为。这个不长眼睛的东西，也不先看清楚了形势再说话，就连美国都只能对朝鲜的二次核爆“严重关切”一下，哪轮得到你无法容忍？不能容忍你又能怎样？再问候你5颗导弹看你能不能容忍？

受了窝囊气的李明博接着宣布，加入防扩散安全倡议。朝鲜跟着又宣布退出停战协议，并警告不再保证西海岸航行的安全，从此，南北朝鲜完全进入战争状态；韩国又制定了假想军舰受到朝鲜袭击后的海陆空反击计划，美军也宣布，已在朝鲜半岛部署100多架战机，给李明博打气。奥巴马一看，不好，金正日可不是吓大的，万一反应过激了就没法收场了，赶紧安排自己的朝鲜问题特使出来灭火，说美国无意对朝鲜发动军事进攻。

到了7月4日，朝鲜又发射了7枚短程导弹，祝贺美国人民独立日快乐，这次美国老实了，没有做出任何回应。之后的李明博开始大叫：“自己死一百次也无法理解朝鲜。”这话说的好没意思，我倒想问一句：明博贤弟，你不能理解朝鲜，你能理解政治吗？只要死一回，相信你就完全理解了。

在狠狠打击李明博的同时，北京继续夯实10+1。8月6日，泛北部湾经济合作论坛在广西南宁开幕。泛北区域包括中国和越南、马来西亚、新加坡、印尼、菲律宾、文莱、泰国等东盟七国。为什么中国要推泛北合作论坛呢？因为05年搞第一届东亚峰会时遇上了大麻烦，被人从10+3撑大成了10+6，北京只好避其锋芒，把10+3拆成了7+1。即使这样，泛北合作论坛搞的也不顺利，一开始东盟国家都在观望，接下来是派司局长与会，到09年才变成了非常重视，这时，原本不在泛北框架内的泰国也强烈要求参会了。

与泛北合作一起推进的还有大湄公河次区域经济合作，包括的国家有、缅甸、老挝、泰国、柬埔寨和越南。从时间上看，大湄公河这边搞的更早一点（从02年开始）。速度也更快一点，毕竟这些国家离中国更近。

8月15日第八次中国－东盟经贸部长会议在曼谷举行，双方签署了中国－东盟自由贸易区《投资协议》，中国－东盟自贸区将按原计划于2010年建成。就这样，北京通过大处着眼，小处着手，铢积寸累，聚沙成塔，一步步的实现着经济上完全融合东南亚的目标。

回过头来，接着看中美斗法：

随着美国对俄罗斯、欧盟让步行动的逐步落实，北京身上的压力也在逐渐增大。这时，北京也展开了反击：

面对着接踵而来贸易磨擦，北京选择了擒贼先擒王，9月13日，中国商务部对原产于美国的部分进口汽车产品和肉鸡产品启动了反倾销和反补贴立案审查程序
。

随后，北京又转身到美国的后院南美寻找劫材，在北京用80亿美元买断委内瑞拉三年内所产燃料油的消息传出后，查韦斯就开始反美串联了：先访伊朗，内贾德非常热心的接待查韦斯并说，老弟，我家里穷得只剩下石油和原子弹了，石油你家也不缺，我帮你建个核村庄如何？查韦斯说，好主意，不过你得先帮我探探我们家的铀矿储量够不够建一个核村庄的。接着查韦斯又到了俄罗斯，普京说，建核村庄很危险哪，我卖你点又战机和坦克防身用吧？查韦斯说，OK，不过伊朗的核技术好象不如你家的好。普京又说，那我们也合作一把，我给你核技术，不过你得跟我签几个能源合同（签能源合同对普京争夺能源定价权大有帮助）！查韦斯说，没问题！

本来，北京的目的是：美国在东欧反导和中亚方向对俄罗斯做了让步，如果俄罗斯不配合美国中国施压，那美国会收回自己的让步。现在，中国和俄罗斯一起，用一个可能出现的委核问题去牵制美国，逼着美国敢动收回让步的主意。可是没想到，北京的算盘被巴西给搅了。在委内瑞拉准备建核村庄的第二天，巴西就宣布，自己有了制造核弹的能力。

要知道，小国玩核是受控的，可以让他有核，也可以让他弃核；但是大国玩核就不一样了，等他有了核，就控制不了他了。如果让委内瑞拉也搞核弹，那在必要时可以让他弃核；如果巴西有了原子弹，那他立即就能成为南美的巨人，中俄美欧四方都有可能被他赶出南美，这是谁都不愿意看到的局面。对北京来说，得罪巴西同样不划算，因为他是需要团结的抗美力量，是第三世界国家的中坚力量。所以，本想制造的委核问题，只好不了了之了。

到了10月14日，希拉里再次试探俄罗斯是否愿意一起制裁伊朗，并抛出了支持俄罗斯加入世贸组织的红绣球，普京的答复是不要威胁伊朗，接着美国翻脸，马上宣布将在波兰境内部署新型导弹防御系统。

由于无法得到俄罗斯配合，美国只能把更大的希望寄托在了欧盟身上，希望用捷克放行《里斯本条约》来换取欧盟的阿富汗增兵。可令奥巴马失望的是，首任欧盟总统都选出来了，欧盟还是不增兵。恼火之下，华盛顿在11月24日引爆了迪拜债务危机，警告欧盟悠着点儿。之后，欧盟依旧我行我素，美国只好在年底进一步启动希腊债务危机，准备掐死欧元。

在美国引爆迪拜债务危机的时候，误伤了他的英国兄弟。10月中旬的时候，布朗带头宣布将向阿富汗增兵500，把奥巴马高兴得不了。之后因为法德不增兵美国引爆了迪拜债务危机，本来美国人是想警告法德两国的，可奥巴马事先没好好翻翻迪拜世界的帐本就下手了，回头一看才发现麻烦了——在延期的迪拜债务中，英国银行未收回的放款额是最高的，有495亿美元之多，远比法德两国加起来（215亿美元）还要多。这一下子惹恼了布朗，马上下令从阿富汗撤出部分英军，急得奥巴马连连跺脚。

眼看着欧盟和俄罗斯光捞好处不帮忙，奥巴马很无奈，只好再次变招。11月奥巴马访华，开始拉拢中国搞G2，结果被中国拒绝。其实，这么低级的战术往北京身上使，纯粹就是污辱中国人的智商。中国是第三世界国家，美国是第一世界国家，这样两个国家怎么可能绑到一块去呢？如果中国真跟着美国走了，那众多的第三世界国家怎么看中国？过去多少年来辛辛苦苦跟广大的第三世界国家交朋友搞统战不就白忙活了吗？

在中国大丢脸面的奥巴马回去以后，立刻宣布大规模增兵阿富汗，准备和南亚在中国一拼高下，为了保证驻阿美军的后勤补给，美国正式提出向俄罗斯借道。

在09年最后的几个月里，伊朗核问题也出现了很微妙的变化：每当美国摆出向欧盟和俄罗斯做出妥协姿态的时候，伊朗核问题就变得非常缓和，标志性事件就是伊朗同意进行核燃料交换。可每当美国与欧盟俄罗斯再生龃龉的时候，伊核问题跟着就起波澜。应该说，伊朗的表现是非常聪明的，当美国与欧盟俄罗斯卿卿我我的时候，如果伊朗冒头，极有可能招来大麻烦；反过来，当美国与欧盟或者俄罗斯恶语相向的时候，伊朗冒头恰恰是给俄罗斯欧盟与美国讨价还价的筹码。另外，为能拉着欧盟对抗美国，北京开始把欧盟往朝鲜半岛请。

【金鸿评论】刚刚进入2010年，北京就露了一手，在1月11日成功进行了一次中段反导实验。北京这样做也是是有原因的，此前的克什米尔和台海局势不断恶化：

6日，印控克什米尔发生枪战，巴控克什米尔地区遭到自杀炸弹袭击，孟买也接到炸弹恐吓；

7日，美国宣布对台出售爱国者导弹防御系统；

8日卡拉奇市区发生大爆炸；

10日卡拉奇地区又发生系列枪击事件；

当时印巴冲突一触即发，而且华盛顿还在台海方向对北京形成强大的压力，逼迫北京在中东让步。动能弹一打，打掉了美国人对自己先进军事力量的信心，也打掉了印度的冒险之心。到了2月25日，印巴举行了孟买袭击后的首次官方会谈，迈出了关系正常化的第一步。

当然，北京露这一手，也是在大盘面上出现很大变化后不得不做的动作，如果北京不能展示出他有着足以抗衡华盛顿的军事力量，那在接下来的全球斗争中将会处于下风。

露这一手，既可以给准备接受美国红包的欧盟和俄罗斯一个警告，也可以给北京准备联合的势力们吃一颗定心丸。北京需要联合哪些势力？为什么需要联合他们？

这要从去年开始美国对俄罗斯的让步说起：

从伊核六方会谈开始到07年年底欧美媾和之前的这段时间里，中国采取的斗争策略是“联强制超”。“强”是指欧盟和俄罗斯，“超”就是美国。在中国的带队攻击之下，华盛顿节节败退，无奈之下，只好先对欧盟让步把欧盟拉过来，再对俄罗斯让步希望把俄罗斯也拉过来。对欧盟的反水，中国的态度是继续支持欧元挑战美元霸权的野心来激化美欧矛盾；对俄罗斯的转身，中国也通过搅黄吉尔吉斯斯坦美军基地的事给予了警告。但是，这些办法都不足以解决中国面临的问题
。

我们必须看到的一点是，从伊核会谈开始，北京拿到的红利是最多的：三通台湾，整合东南亚，渗透中亚，联合非洲，布子南美，交好中东。不过，中国在得到这些好处的同时，也让美俄欧三方对中国非常不满，因为中国在通吃三方——东南亚和南美有美国的地盘，非洲有欧盟的地盘，中亚是俄罗斯的地盘。现在，美国为了改变被三方通吃的局面，拉拢两家对付中国，而逼迫中国回吐一部分战略利益也符合欧俄两家的利益，所以这种三打一的局面是非常可能出现的。为了避免出现这种情况，北京及时调整了自己的策略，改成了“联弱斗强”。“弱”是指巴西、土耳其、沙特等地区大国，“强”则是指美欧俄三家，注意，全球金融危机之后，美国已不再是个超级大国，他对世界的综合影响力已经在中国之下了。

应该说，联弱斗强是非常高妙的一招，这一招直接让伊朗受益，在接下来的联合国安理会上新通过的制裁案中依然没有被经济制裁。这一点将会在后面详细展
开。在联弱斗强的同时，中国对美俄欧三方不再向以前那样明显的联合两家打击一家，而是变成了对三家既拉又打：

对美国：攻击美元霸权的行动是不折不扣的，对美国企图切断巴铁通道的行动是坚决回击的，对伊朗的保护也是诚心诚意的，对G2是坚决不买帐的。但是只要美国为保美元霸权而对中国做出实实在在的让步时，中国又会策略性的暂时停止攻击美元霸权，帮美国维持一下局面。

总之，对美斗争的原则就是通过对美国施加强大的压力逼迫其一步步的对中国让渡利益。而对俄罗斯和欧盟，则是尽可能的拉拢，用以增加对美国的压力，当他们被美国挤兑的快要挺不住的时候，中国就会出手拉一把防止他们彻底垮掉，比如在俄罗斯肢解格鲁吉亚时中国持支持态度，在希腊债务危机时对欧元也是尽量帮助的。但是，每当俄欧两国做出有损中国利益的行动时，中国会毫不犹豫的坚决反击，比如俄罗斯企图拔掉吉尔吉斯美军基地时，欧盟打达赖牌时。

在接下来的二三月份，发生了几件大事：亲俄的亚努科维奇当选乌克兰总统，韩国天安号警戒艇被击沉；希腊债务危机逐渐演化成欧元危机；伊朗在核燃料交换问题上反复无常。

这几件大事看似各不相干，其实是一个局势的几个侧面：美国战略翻盘的关键，是拿到一份有价值的伊朗制裁案，同时稳定阿富汗局势。为了达到这个目标，美国对俄罗斯让步，亲俄的亚努科维奇得以上台；同时，美国在巴以和谈和沃[科]索沃两个方向对欧盟让步，而欧盟拒不增兵阿富汗。伊朗呢，通过在核燃料交换问题上时软时硬的表态，配合欧俄两方的节拍，打乱华盛顿的步调，再加上受制于中国联弱斗强方针的压力，美国迟迟拿不到经济制裁伊朗的方案。

为了更好的离间美欧两方，中国开始下意识的把欧盟引入朝鲜半岛。要知道，按照华盛顿的规划，欧盟应该被屏蔽在亚太经济圈之外的（APEC）。现在，中国主动当介绍人，欧盟自然是求之不得的。把欧盟引进来，虽然不能全面启动东北亚经济一体化，至少可以减轻一下朝鲜的经济压力，还可以更大程度的把欧盟从美国身边拉开，进而激化欧元与美元的矛盾。但是，美国不愿意看到欧洲人登陆朝鲜半岛。
#+HTML:<a>为了把欧盟档在朝鲜半岛以外，美国制造了天安舰事件。</a>
#+LaTeX:\red{为了把欧盟档在朝鲜半岛以外，美国制造了天安舰事件。}
试想，欧盟怎么能和刚刚制造了天安舰事件的“主谋”朝鲜建立外交关系并加强经济往来呢？这又让韩国和日本怎么看欧盟呢？

为了警告迟迟不增兵阿富汗的欧盟，华盛顿一步步引爆希腊债务危机来打压欧元了。09年10月，当时的希腊新政府宣布09年财政赤字水平将达到国内生产总值的12．7％，远高于欧盟规定的3％的上限，希腊债务危机浮出水面；到了12月10日，美国惠誉落井下石，把希腊主权信用降级，希腊债务危机开始升级；在希腊债务危机的拖累下，欧元也从09年10月份的1欧元兑换1．5美元跌到12月份的1.42美元。

希腊债务危机出现以后，欧盟中最大的经济体德国不愿意救助希腊，因为希腊本来是没有资格加入欧元区的，他是通过作假账才混进去的，对此，德国人非常愤怒，而且德国自己也面临人口老龄化、贫困人口增多、社会不平等诸多社会经济问题，也需要大量资金来解决这些问题，在这时再拿钱出来救助希腊，德国老百姓很难接受。到了5月份，希腊债务危机火烧连营，欧元汇率打穿了1：1.3美元，这时，法国人急了，以退出欧元区要挟德国出手救人，意大利西班牙也加入了反德阵线，再加上希腊人开始病急乱投医要跳出欧盟框架求救，不得已，德国人在5月7日通过了救助希腊的决议。

随着救助希腊方案的通过，全球局势出现了显著的变化：

美国开始一步步的把炸沉天安舰凶手的帽子往朝鲜头上扣，慢慢把欧盟挡在了朝鲜半岛之外；同时也用救助希腊的行动对欧盟进行最后的劝告，再不增兵阿富汗和支持对伊朗进行经济制裁的话，欧元可就真垮了。与此同时，伊朗核问题也随之发生了微妙的变化，下面先从时间上看一下先后发生了哪些事：

北京也开始全面施展联弱斗强策略：这次用到的“弱”国是是土耳其和巴西，他们虽然是地区性强国，把他们放在全球高度，都算弱国，是地球村里的群众。因为美国对欧盟和俄罗斯的让步，让中国可能面临以一敌三的局面，所以中国也改变了自己的斗争策略，从以前的联合俄欧对付美国变成了发动群众闹革命。中国在与这些国家建立良好的关系的基础上支持这些群众在各自地区挤兑美国、发展壮大自己的势力，在伊朗核问题上需要帮手的时候，中国就把他们托起来顶一把。要知道，伊核会谈是中俄欧美四方角逐全球利益的地方，其他国家根本进不了场。现在，在中国的引荐下，两个不怎么强的国家巴西和土耳其却在这个竞技场上露了一回脸，还从中拿到了好处，自然让这两个国家非常高兴，对于把他们托进来的中国，他们也是感恩戴德。下面按时间顺序分析一下这一轮斗争的全过程：

随着欧盟在救助希腊问题上表现出向美国妥协的姿式，拿了美国人好处的俄罗斯开始警告大声伊朗必须让步，之后伊朗示软，重启核燃料交换方案。看到了欧盟和俄罗斯态度的美国则对伊朗表现的异常强硬，号称要对伊朗实施严厉制裁。这时，为了防止美俄欧三家达到一致、形成对伊朗真正有杀伤力的制裁案，北京把巴西托了起来（之前土耳其已经进场了）进场搅局（4月27日，巴西表示愿意让伊朗在巴西领土上进行核燃料交换）。在表示完对美国的配合之后，普京毫不客气的伸手要求美国把乌克兰交给自己，奥巴马只得点头放行。

进入五月后，局势进入高潮：德国刚刚通过了救助希腊的决议，伊土巴核交换就露出了成形的影子。到了5月9日，欧盟对美国妥协，通过了1100亿欧元的救助希腊方案。为什么说这个方案有是美国妥协呢？因为这1100亿美元中有300亿来自IMF，美国在IMF有一票否决权（欧盟也有），此前欧盟一直强调援助方案必须在欧盟框架内制定。当然，这1100亿欧元也不仅仅是为了救一个希腊，还可以从中拿出一部分资金作为欧洲的货币稳定基金，震慑市场的投机力量，必要时再拉一把葡萄牙、西班牙、爱尔兰等挣扎在危机边缘的国家。

之后，美国则进一步示好，支持在两国方案基础上解决巴以争端；可是欧盟依然没有增兵阿富汗。17日，看到了欧盟态度的胡哥也表态坚决支持救援希腊。同日伊土巴三国签署核燃料交换协议，不过这时伊朗又做了一个让欧盟“深感疑虑”的动作，继续生产纯度为20%的浓缩铀——你倒底是要换呀还是要自己造呀？倒是以色列人说出了实话：“他们假装接受这种安排，以缓和局势和降低遭受更严厉国际制裁的风险，然后又拒绝完成交易。”对于伊朗的这种滑头行为，美国忍无可忍，18日开始在联合国散发制裁伊朗决议草案——虽说这份草案已经让北京改的不成样子了，但有总比没有好，通过了之后再想别的办法修理伊朗。

土耳其和巴西的入场，完全打乱了美国的计划，本来美国是打算让欧盟和俄罗斯来分享这份核燃料交换协议的，现在被人抢走了。这时，俄罗斯和欧盟两方又向美国伸手了：老大，你给我们的好处让人抢走了，你打算再给我们点什么好处让我们帮你制裁伊朗呢？当然，我们的面子是不是比小巴小土要大一点？我们是非常希望帮你教训那个不懂事的伊朗的，我们不是不出力，只怪共军太狡猾……

这时的美国能怎么办呢？正面打击土耳其和巴西是绝对行不通的，因为美国求着他们高抬贵手的的地方多着呢，不然怎么叫地头蛇呢？当然，有人可能会说，美国不会不让他们参与核燃料交换吗？的确，美国是非常不希望他们进场，可是，俄罗斯和欧盟是愿意的，就算把核燃料交换的好处全给这两个国家他们也愿意——至少美国无法索要之前对他们的让步了，因为人家俄欧两方都愿意制裁伊朗，只不过被中国领着土耳其和巴西破坏了本来一片大好的局面。再说土耳其和巴西是俄罗斯欧盟都在积极拉拢的国家，谁愿意得罪他们？

常言说的好，吃人家的嘴短，拿人家的手短。土耳其和巴西拿了伊朗的好处，回头自然要表示一下。这时就遇上美国在安理会散发制裁伊朗的草案了。很自然的，土耳其表态了，制裁有用吗？制裁只会破坏气氛嘛！巴西更不给面子，抓起一份制裁伊朗的决议草案就扔进废纸篓了——没兴趣讨论这玩艺儿！

本来，土巴两国的搅局行为就让美国人大为恼火，只是不好表现出来。可法国人不看火候，偏偏这时跳出来拍土巴两国的马屁——法国总统府专门发表公报，说三方达成的协议绝对是“积极的一步”。结果气得美国人回头就给了一棒子，你们欧盟刚刚找我要了钱去救西腊，回头就敢看我的笑话？当天美国参议院通过了一项决议，考虑阻止IMF救助无力偿还贷款的国家（暗指希腊）。小样，真以为我治不了你？老子一向翻脸比翻书还快。

在中国对欧元的坚决支持下，美国没敢立即推翻对希腊的救助协议，19日希腊顺利拿到了200亿欧元的首笔救命钱，安然度过了首个偿债大限，同日，欧元也从1：1.21美元的低谷绝地反弹。当然，作为交换条件，希腊议会不得不咬着牙通过了财政紧缩政策，给欧盟的兄弟们一个交待。

在这一轮制裁伊朗的斗法当中，中国真正掌握了主导权。在这里需要说明的是，在国际斗争中，不要认为一个国家什么都说了算才是掌握了主导权，这几乎是不可能办到的事情。主导权是指这个国家说什么事不行什么事就不能做，也就是否决权。联合国五常的否决票，就是保证这五个国家拥有主导权的，不过，在联合国有五张否决票而不是一张，所以也经常出麻烦。现在，在伊核问题上，中国做到了一票否决——美俄欧都同意制裁伊朗，只有中国不点头，结果就通不过。最后大改了方案之后，中国点头了，这才通过了。伊朗核问题是目前大国斗争中最重要的一个问题，现在中国掌握了主导权，说明什么？

中国已经成为了NO.1。

在花了血本仍一无所获之后，奥巴马终于认识到，想从联合国拿一份有用的伊朗制裁案是不可能的，于是也改变了策略，绕开联合国拉拢人单独对伊朗搞制裁，最好把欧盟、阿盟还有其他盟友们全部拉到制裁伊朗的队伍里。

回过头来奥巴马再一打算盘，发现自己赔大发了，前面做出的让步实在太多了，于是赶紧往回捞：5月24日，爱国者导弹正式布置到了波兰，接着美国又要在捷克建立联合反导防御中心，重新开打东欧反导牌；对付欧盟，则是继续打压欧元，5月28日，惠誉再次把西班牙的主权债信评级下调，欧元跟着继续又开始下跌，到了6月4日，匈牙利也跟着大呼小叫，说自己可能陷入希腊式的债务危机，引得欧元在6月7日跌破了1：1.19美元。随后，中国向希腊大手笔投资数十亿欧元（船运、物流和机场项目），帮助欧元稳住了阵角。

4月份还发生了一件不大不小的事，就是吉尔吉斯斯坦的总统巴基耶夫被俄罗斯搞下了台，之后，在吉尔吉斯有相当影响力的中美两国都没有反对。美国不反对，是希望在此之后俄罗斯能进一步在中亚挤压中国的影响力，形成中俄互斗的局面，好减轻自己的压力；中国不反对，则是希望俄罗斯在赶下台了巴基耶夫之后再把美军基地拔掉，以后美国对俄罗斯的依赖性会更强，从而会更下不了决心搞乱巴铁通道。接着，北京就选择了坐壁上观的态度。

本来，在吉尔吉斯是中俄美三家斗法的，现在中国撒手不管了，任由俄美两国折腾。这时，俄罗斯为了进一步控制吉尔吉斯，就想出手挤掉美军在吉尔吉斯的基地，美国人马上沉不住气了，到了6月初，美国人又开始在吉尔吉斯制造骚乱。这时，中国的态度依然是按兵不动。两个闹事的加上一个不管闲事的，可把吉尔吉斯临时政府急坏了，先是以延长美军基地租约为威胁，逼俄罗斯出兵平乱，结果被俄罗斯拒绝，接着美国想混水摸鱼，提出派兵维和，结果又被俄罗斯挡了回去。两国一看不行，还是先定一下局势再说，结果两家一起出手，骚乱就结束了。之后，俄美两国又开始研究在吉尔吉斯增加军事基地的事了……


** 【金鸿评论】04年以来的大国斗争回顾（续）
[2010-10-0117:12:52]


【金鸿评论】眼看着美国把自己的欧元往死里打，欧洲人也在5月底开始了报复行动，顺着中国竖起的联弱斗强的杆子往上爬，拉着土耳其弄了艘救援船去闯以色列的海上封锁线，结果以色列开火伤了人。事情闹开之后，全世界狂批以色列，不过参与行动的以色列军官说他们是在受到刀棍甚至是实弹攻击之后才以武力反击的，并出示了录像带做为证据。这种说法应该有真实的一面，至少船上的志愿者有本事制服身上揣着“暗杀名单”的以军士兵（这是新闻报道过的）。按理说，船上有几十名欧盟成员国的议员，这些当兵的应该不敢乱来。不过，谁让以色前以前欺负人欺负的这么厉害呢？这次又伤了人，谁会替他说话？欧盟之所以冲上去，主要是为了逼迫美国在中东让步。救援船是去救哈马斯的，强硬的哈马斯是阿拉伯人向美国人讨价还价的重要保证（也正是有了哈马斯，中国才有了要求加入巴以和谈的机会）。现在欧盟去救哈马斯了，阿拉伯人能不感激？所以，得到了人心的欧盟自然有理由要求美国人停止攻击欧元，并放行地中海计划。土耳其愿意派船，与伊拉克局势密切相关，美军大量撤出伊拉克，可伊拉克新政府迟迟选不出来，搞不好真就三分天下了，那时土耳其就必须得面对库尔德斯坦问题了。现在派船冲击一下，也算找到一个可以跟美国讨价还价的筹码（库尔德问题也是导致土耳其、叙利亚、伊朗三国结盟的原因，三家结盟的后果就是叙利亚胆子更大了）。这种局面也是伊朗、叙利亚还和众多的阿拉伯国家非常乐意看到的局面，中国和俄罗斯也有了足够借题发挥的空间。所以，欧盟的配合行动，其实也是在警告美国，如果不能在中东让步，又不允许欧盟登陆朝鲜半岛（天安舰事件），欧盟不排除把中国介绍进巴以和谈。

救援船事件后，埃及马上宣布无限期开放加沙口岸，之后，美以对欧盟让步，放松了对以色列控制的加沙口岸的管制。这时，欧盟与美国一起逼迫埃及取消无限期开放加沙口岸的决定，欧美重新回到了同一条巴以和谈战壕里去了。这时，北京做出了一个令人震惊的举动：6月10日，中国主张以色列应尽快以无核武器国家的身份加入《不扩散核武器条约》，并将其所有核设施置于国际原子能机构的全面保障监督之下。在此前一天，联合国安理会刚刚通过制裁伊朗的1929号决议（表决时的两张反对票来自土耳其和巴西），胡哥真是一点时间都不耽误。

如果说06年年初中国加入伊核六方会谈标志着中国的全球战略反守为攻的话，那么今年6月9日通过的北京大改特改后的伊朗制裁案，则是中国从攻到胜的标志，这时，中国第一次拥有了对全球局势的主导权，这是一个从量变到质变的过程（上世纪70年尼克松登门求和也可以看作为中主导全球局势的一个标志，不过精神层面的意义更大一些，因为中国的实力当时还到不了中东）。局势就是这样，一旦完成了从量变到质变的转换，变化将一日千里。就象当年的三大战役：在三大战役之前，解放军处处被动，整天防着敌人进攻，手里一个大城市也没有；三大战役之后呢，许多城市根本不用打，兵不血刃就传檄而定，既使开战，国民党也是望风而逃，真正有效的抵抗几乎没有。为什么会出现如此大的反差呢？形势变了。“势”是无形的，但它比有形的“力”更有价值。所以，在《孙子兵法》里有这样的话：“故善战者，求之与势，不择于人，故能择人而任势”——形势比人强！

其实，在此之前，美国就已经显出了败势。4月12日，华盛顿举行了核安全峰会，参会国家有40多个；到了4月17日，伊朗发起的核裁军国际会议却有56个国家的代表到会。对比一下就可以看出，堂堂美利坚在事关人类命运的核安全问题上的影响力，居然比不上一个支持恐怖主义的伊朗（伊朗一直在美国的支恐名单上挂着号）。看来，不是这个世界出了大问题，就是美国出了大问题。

这样的局面，对北京来说，那可真是千年的大道走成河，多年的媳妇熬婆婆。现在，扭转乾坤的时候到了。胡哥一分钟也没有耽误，先后打出了三张牌，马上引来了滔天巨浪：

第一张牌，要求明确以色列的核身份；

第二张牌，宣布进行二次汇改；

第三张牌，制定了战略性新兴产业发展规划(9月8日)；

下面首先分析一下明确以色列核身份对全球局势的影响：

在中东，当前有三个热点问题，巴以和谈，伊拉克重建，伊朗核问题。站在美国的角度看：巴以和谈是后防线，保卫着美元霸权；伊拉克是前线，摆平了有助于稳定美元，并可以为攻打伊朗提供资金支持，伊朗则是未来的战场，是未来要占领的国家。站在中俄欧三方的角度看，绝对不能让美国摆平了伊拉克，否则美国就完全控制了中东的石油，三家只好去喝西北风。

为了不喝西北风，三家开始想办法在伊拉克捣乱，同时摆出伊朗核问题让美国去解决。如果美国摆平了伊拉克，自然不管什么核问题心问题的，抒伊朗一打了事，可是美国被伊拉克的烂摊子拖住了腿，实在抽不出兵力来打伊朗，只好跟中俄欧搞六方会谈。美国愿意谈判，是为了争取时间来解决掉伊拉克的问题，中俄欧愿意陪他谈，则是为了逼他在中东（包括伊拉克）和地球上其他的地方让渡利益。结果谈来谈去谈了四五年，美国花费了大把的时间和美元，也没能搞定伊拉克，最后还不得不把战斗部队撤了出来。中俄欧三方则以伊核问题为前线，步步前推，先推到伊拉克（07年7月美国通过从伊拉克撤军时间表），再推就是巴以和谈了。这是美国最后的防线。美国为了保住这条防线，选择了对欧盟让步，从07年年底开始，已先后多次让步，但是，他拒绝让中国加入。进入巴以和谈最大的好处是什么？就是可以争夺巴以和谈掩护着的美元霸权，欧盟也是得到了美国的让步之后才开始推动欧元与美元争霸的。前面的分析中，也提到了中国数次要求加入巴以和谈，均被拒绝。这一次，欧盟做了引荐中国加入态度后得到了美国的让步，之后便不再提引荐的事了，中国再次在巴以和谈问题上被欧盟利用了一把。不过，此一时，彼一时。这时的中国已经不是以前的中国了。中国在中东已经拥有了主导权，自然可以用其他的方式达到自己的目的，而不是离了欧盟就活不了。北京采取了什么手段呢？要求明确以色列的核身份。

如果用一个比方来形容的话，北京的这个动作就相当于抡起一把锤子，对着方方面面示意，我准备砸掉巴以和谈这张谈判桌——你们不是不给我安排把椅子吗？我还不要了呢，我把这张桌子砸了，大家都别坐了。北京这个举动，也是自攻入中东以来做过的仅次于让朝鲜引爆原子弹的凶悍动作。这个动作在华尔街看来，简直就是刨他们的祖坟。

为什么说这个动作是在砸谈判桌呢？这得从以色列的身家性命说起。大家都知道，以色列在中东地区，只有敌人没有朋友。他能在中东活这么多年，离不开美国先进武器的支持，更离不开他有原子弹。众多的阿拉伯国家打不过他，是因为以前的大国都不希望中东真正实现和平。

自从以色列建国以来，美国就是最强大的国家，在中东一直占据主导地位，哪个国家想要争夺中东主导权，都必须通过巴以和谈这张谈判桌来跟美国较量，无论是苏联还是欧盟，都是这样。因为过去的苏联和欧明因实力上都没有超过美国，所以自然不能做出实质性伤害以色列的行动来。很自然的，众多的阿拉伯国家也就得不到可以战胜以色列的好武器，历次的中东战争中阿拉伯国家就也不能取胜了。同时，以色列拥有原子弹，是对阿拉伯国家极大的心理震慑，各国都怕把他逼急了会扔一颗出来，那小日子就别过了。

现在，中东局势发生了重要变化，美国的影响力严重下降，中国在中东取得了主导权。美国保护不了以色列已是事实，已发生的救援船事件和接下来发生的一棵树战争都足以证明这一点。这时，如果中国愿意，可以实质性的损害以色列。如果以色列再没有了最后的杀手锏原子弹，他也许真的就象内贾德说的那样，有一天会被人从地图上抹去。所以，核武器是以色列最后的救命稻草。现在，北京要求以色列以无核国身份加入《不扩散核武器条约》，就是在绝以色列的后路。一旦以色列没了核武器，中国（或者俄罗斯欧盟）再去卖力的武装一下阿拉伯人，以色列还敢在巴以和谈中唱黑脸吗？巴以和谈谈了这么多年不就是靠的以色列这个黑脸吗？没了黑脸中东不就和平了吗？和平了的中东谁还会买美国人的帐？谁还会用美元结算石油？所以说，北京的这个动作着实要命。

写到这里，还必须说明一点，北京的这个动作其实是虚招，是在吓唬美国的。中国也不希望美元（国）倒的太快。如果美元今年就倒掉了，那获利最大的国家是跟美国没有多少经济联系的俄罗斯，中国经济则会受伤。北京摆出这个虚招之后，接着亮出了实招，就是6月19日宣布的二次汇改。在分析北京为什么要先虚后实的出招之前，先看一下这次汇改的真正用意是什么。这次汇改有四个特点：第一，把经济发展模式由出口导向型转内需拉动型，平衡国际收支，彻底改变卖血汗换白条的状况。这次汇改，完全是北京主动选择的，绝对不是也不可能为了满足美国人提出的用人民币升值改善中美贸易失衡现状的要求的，更不会去进行一步到位的（对美元）大幅升值，在这一点上，过去保尔森说了不算，现在盖特纳说了更不算。

第二，这次调整和05年的汇率不同，上次调整的基本原则是锁定美元、逐步提高汇率，这一次则是放弃盯住美元，准备全面脱钩。当时锁定美元，是非常不得已的，因为中国经济畸形太严重了，经常项目对美贸易顺差奇高，为了保证中国经济的正常运行，必须锁定美元。然后逐渐提高汇率，分阶段淘态血汗工厂，提高出口企业的技术水平，优化产业结构。

经过5年的努力，中国的主要贸易伙伴已经明显的多元化。前十大贸易伙伴占中国外贸总额的比重逐年下降，非洲、拉美占中国外贸总额的比重呈上升趋势。我手里有几个数据，可以简单参照一下：从05年到08年，中国前十大贸易伙伴占当年进出口总值的比例分别是：81.5%、79.7%、78.6%、75.9%，估计到今年年底，这个数字可能降到72%左右（哪位有比较全面的宏观经济数据，可以给我一点，分析要用到）。


今年1-5月中国前五位贸易伙伴分别是欧盟、美国、东盟、日本和我国香港地区，他们的占比分别为16.3%、12.9%、10.1%、9.4%和7.5%。从这组数字可以看出，中国经济对美国的依赖性大为减小，美欧日加起来已不足40%，大头落在了广大的第三世界国家，这是一个重大的变化（对日贸易会在后面单独分析）。

这时，中国基本具备了甩开美国的能力。我们都知道，中美贸易的实质，其实就是美国打白条买中国的产品，中国再拿着白条买美国国债，收回了白条的美国人再用白条买中国产品的这么一个循环。以前，这个循环不敢打破，因为中国经济会很受伤；现在，这个循环可以打破了，是因为中国经济调整的差不多了。所以，北京决定放弃盯住美元单一货币（现在说是转向一篮子货币，其实这个篮子也是用来过渡的）。我们都知道，在中国商品换美国白条的过程中，与中国离不开美国相比，美国更离不开中国，毕竟没有白条可以生活，没有产品无法生存，所以，从一开始，中国处在相对主动的位置；现在，中国则彻底掌握了主导权。如果美国人还敢耍横，我们有能力让他去喝西北风！

第三，此次汇改将实行双向浮动。换句话说就是人民币可以升值，同样可以贬值。拿美元来，如果人民币升值一倍，那中国经济可能受不了；但是如果人民币贬值一倍，则可能会要美国的老命。为什么说贬值一倍会要美国的老命呢？大家都知道广场协议，日元兑美元升值一倍，日本经济失去了十年。日元升值一倍，换个角度看，就是美元贬值一倍，当然不光是美元贬，大多数货币都跟着美元在贬。现在，中国经济已经基本成功的绑定了东盟，对广大的第三世界国家的影响性也越来越强。如果这些国家对中国经济的依赖度超过了对美国的依赖度，那么，当人民币猛然贬值一倍的时候，这些国家就必须选择重新站队：要么跟着人民币一块贬，要么跟着美元原地踏步走。每个国家首先要考虑自己的利益，当必须面对损失的时候，他会选择小的损失。在这时，这些国家必须跟着人民币贬值，否则损失太大。一旦出现了这样的情况，美国必须面对进口商品升值一倍的现状。

我们都知道，通过操纵石油价格暴涨，美国多次成功的掠夺各国财富。其实他的手段很简单，打个比方就可以说明白：假如某个小国每年需要进口50亿美元的石油，这个小国每年有50亿美元的贸易顺差。现在石油价格拉高了一倍，这个小国的顺差就没有了；如果油价拉高两倍，这个小国将逆差50亿美元。有人可能会说，他不会提高出口品的价格还弥补吗？不能，因为这类小国的产品往往是低端产品，竞争激烈，盲目提价无异于自杀。这也是不掌握高科技的悲哀。同样的办法也可以用在美国身上：在美国的出口能力没有提高多少的情况下，出口产品贵了一倍，会沉重打击本已衰弱的出口制造业，美国也会因此产生更严重的贸易逆差，经济形势会进一步恶化，市场也将对美元形成强烈的贬值预期，从而引发美国国内资金的大量出逃，结果就是美国经济大失血。为了减少资金的出逃，美国只有提高利率来维持局面。可问题是美国经济还有两个更大的麻烦，一是美国开动印钞机已经把利率压到了零，二是美国经济就已经在债务堆里打不出滚来，这时提高利率就是经济自杀。可是不选择自杀美国经济也会在失血中崩溃，这是一个无解的问题。同样的招数也适用于欧盟。这里还需要指出的是，对美元暴贬是进行货币战争的手段，是杀招，如果美国能接受中国的要求，人民币不会对美元直接贬值，而是继续有节奏的升值，用有节奏的升值来进一步优化产业结构。人民币从05到08四年大幅升值了21%之后，近两年来一直稳住不怎么动，一个波次的调整时间也够了，再进行一轮的升值应该也是可以接受的（具体情况要分析数据，我不掌握，仅是猜测）。

第四，站在中国经济转型的角度看，本次汇改不是孤立的行动，它是一套组合拳中的一招。配套的还有发展战略性新兴产业、调整国民收入分配格局（扩大内需），完善社会保障体系等。关于这几点，我会放在文章的最后系统分析，在此先作一个结论，这套组合拳打好之后，中国经济将成为世界经济的火车头，中国将成为这个世界真正的主宰者。

【金鸿评论】现在，回头过来看，北京为什么要先虚后实的打出两招呢？其实这是北京在对美元霸权形成前后夹击之势。明确以色列核身份，是正面强攻，这线战线上还有欧盟和俄罗斯在强攻，如果从这条战线上猛攻，美元霸权会以极快的速度倒掉，但是好处要三家分；二次汇改的杀招，是侧翼包抄，同样可以击倒美元，但这条战线只有中国自己，美国倒掉的速度会慢很多，而好处会让中国独享。所以，北京先虚后实的出招，是给华盛顿出题：你愿意快速的倒掉吗？如果不愿意，我这有让你慢慢倒掉的办法，你选择好了。当然，选择慢慢倒掉，也是要让度利益给北京的。这一次，北京想要得到什么呢？美国退出东北亚，把日本和韩国让给中国。要说这一次，也的确是狮子大开口。所以二次汇改的第二天，朝鲜就宣布自己要实施核聚变试验（暗指东亚局势要嬗变）。这时美国的态度是什么呢？北京要求明确以色列核身份之后，华盛顿马上宣布对朝鲜的制裁延长一年；

北京宣布二次汇改后，华盛顿宣布美国已经开始调查并冻结朝鲜海外资产。

很显然，华盛顿用行动证明，自己反对东北亚一体化，决不退出东北亚。当然，所谓的东北亚一体化，也就是让日本、韩国和朝鲜接受中国的整编（不仅仅是经济层面）。此前，美国一直在东北亚，所以东北亚一体化也就一直停留在口头上。现在，北京正式伸手，华盛顿拒绝。双方拉开架式，准备决斗。判断得分的标志是航母是否进黄海。

第一轮决斗从6月下旬开始。美国在朝鲜方向用联合军演进行挑衅，伊朗则马上升级核问题呼应，以色列跟着就威胁要武力打击伊朗，伊朗则以派救援船前往加沙反制。这时阿拉伯人跳了出来，组织了比伊朗规模更大的船队也要闯加沙。阿拉伯人选在这时出头，是希望北京能继续挑头明确以色列核身份，只要以色列无核了，阿拉伯人睡觉也就踏实了。当然，就算北京不做，阿拉伯人也是通过这种方式给欧洲人提醒，如果想让他们支持地中海计划的话，就得在以色列核身份问题上有所表示。

这么多伊斯兰国家一起闯加沙，非把坐困愁城的哈马斯给救了不行，那时巴以和谈可就出大麻烦了。别人不说，光俄罗斯的漫天要价就够美国人受的，这时，美国人不得不改变了对伊朗动武的念头，在6月24日把修理伊朗的办法换成了史上最严厉的制裁法案，接着在6月25日奥巴马出来喊话，美国不要求人民币快速升值，进一步表示诚意。，中国同意与美国就美国关心的救援船事件和中国关心的天安舰事件做一个妥协，中国不借机揪住开放加沙不放，美国则不指定朝鲜是天安舰的凶手，东北亚一体化出现了一丝曙光。看到了中国对美国的妥协态度，欧盟也就不好再追着以色列不放了。接着，朝鲜对即将举行的韩美军演摆出了擦枪走火的架式，中国也做好了战争准备，眼看无缝可钻，美韩两国在7月15日宣布原定的航母进黄海军演计划取消。美军航母一进黄海失败。

#+HTML:<string><a>
#+LaTeX:\red{
现在，有必要把中国与美国的敌友力量分布对比一下，毕竟是中美决斗的关键时刻。先说中国：非洲，那是我们的票仓；东南亚，已经被中国经济捆绑了，根本没有选择的余地；南美洲，巴西的支持是坚定的，阿根廷也跟中国进行过货币互换，两个政治反美大国古巴和委内瑞拉也不用多说，南美四个影响力最大的国家基本上是全面倒向中国的，小国好对付；再看中东，四个最大的国家，伊朗是我们的，沙特是全面亲华的，土耳其上面提到过了，埃及也早已开始全面反醒亲美路线了，在中东中国的影响力已超过美国；至于中亚，哈萨克斯坦是接受了中国的核保护的，其他几个跟中国搭界的斯坦们也没什么问题，就连远在东欧的白俄罗斯，都愿意充当中国入欧的桥头堡，至于朝鲜和巴铁，那更是没话可说。另外，在巴尔干中国也有相当的影响力（塞尔维亚总理6月24日访华）。
#+LaTeX:}
#+HTML:</a></strong>


再看美国，他是完全被孤立了，这个下场也是罪有应得，谁叫他敌人遍天下呢？八十年代的第三世界债务危机、解体苏联休克疗法、广场协议打压日本、墨西哥金融危机、东南亚金融危机，99年打击欧元、南美金融危机………这些事哪一件不是他干的？他是围着地球抢了一遍，除了中东产油国和以色列。现在美国要倒了，谁会帮他？把他扶起来将来再抢自己？现在是墙倒众人推，只要有机会，谁都会踩上一脚。

这时的德国人，也感觉有必须做点什么了。7月15日，默克尔访华，宣布与中国建立全面战略伙伴关系，开始大量对华输出先进技术、帮助进行中国产业升级。德国人这么做，也有不得已的地方，因为他们多少次希望美国能做出实实在在的让步美国都没有让步，而且在今年上半年差点把欧元掐死了。现在，为了逼美国让步，欧盟必须首先交好中国，同时拉住俄罗斯，之后就可以抬高对美国的要价——允许欧盟整合科沃索。以前，整合科索沃的事可以从长讲议，但现在中国逼美国太急，欧盟不得不先顾这头。因为只有整合了科索沃，欧盟才能真正完成内部整合。如果不能赶在美国这个保护神倒掉之前倒掉之前完成内部的政治整合，将来他那点家底极有可能被中俄联手给抢了。

7月20日，看清了德国人态度的英国人也出来表态，亚洲，特别是中国，将是英国新政府未来外交优先考虑的区域；8月16日，瑞士联邦主席洛伊特哈德宣称，中瑞自由贸易协定谈判有望于明年年初启动。傍样的力量的确是无穷的。对于德国人的投怀送抱，中国也很情领，温总理称默克尔的中国之行“具有历史意义”，并说欧洲市场一直是中国外汇储备的主要投资市场之一。随着中欧关系的猛然抱团，迅速把俄罗斯也牵引了过来。

两个月后，梅德韦杰夫访华，老梅对中国的态度如何呢？别的其实都不用看，只看老梅说的那两句话就可以了：优先发展对华关系，目前俄中关系处于最高水平。现在的中俄欧比起当初在伊核问题上协同抗美的关系来，更近了一步，亚（非）欧大陆经济整合要提速了。在这里需要说明一件事，有点可笑：欧盟力推的地中海计划，其实是法国意大利的最爱，德国人并不怎么感冒，德国人希望优先发展对俄关系。为什么会出现这样的情况呢？看看地图就可以明白，法国意大利在地中海边上，德国则离俄罗斯更近一些。说到底，大家为的还是自己的私利。欧盟，离成为一个国家差的太远了。

第二轮决斗随后展开，这次的战场转到了东南亚。7月20日，东盟外长峰会宣布，10月份的东亚峰会准备邀请俄罗斯和美国加入，10+6又被扩展成了10+8。这是美国人在新加坡之流的小国配合下搞成的，目的是把俄罗斯拉进来制衡中国。结果中国马上提出了“东盟+上合”模式，一下子吓坏了新加坡。7月24日，新加坡马上跟中国签了1500亿元人民币的互换协议，向中国投诚。为什么“东盟+上合”会吓坏新加坡？摊开地图看看，如果“东盟+上合”真搞起来了，新加坡可就处在这个区域联盟的最边上了，也就变得可有可无了。千万不要小看是在边上还是在中间，这是对任何一个国家的发展都是致命的：当年的英国，以自己为核心，把非洲、美洲、大洋州和欧亚大陆编织在自己周围，才有了日不落帝国；之后的美国，以自己为中心，把南美、东亚、中东、大洋州和欧洲编织在自己周围，才有了今天的霸主地位；同样，今天的中国，以自己为核心，努力把东南亚、非洲、南亚、欧洲、中东、大洋洲和美洲纺织在自己周围，再造一个更大的日不落。看到这里大家也就应该明白为什么新加坡不喜欢10+3了，10+3他还是在边上。中国把“东盟+上合”的方案往桌子上一摆，新加坡立即交枪投降，跟中国搞货币互换，支持人民币全球化。

一计不成，美国又想一计，开始分别拉拢意志不坚定的国家。7月31日，美国承诺送菲律宾价值上百亿美元的精确制导导弹；8月5日，美国又说可能会允许越南铀浓缩。8月2日，美国宣布将在未来数周对朝鲜实施更多制裁。8月6日，美国接着放风航母还要进黄海军演。华盛顿的玩火再次引起了北京的警觉，北京再次做出准备对敢于在南海配合华盛计划小国开战的姿态。之后，越南发誓永不与美国结盟，菲律宾则说东南亚国家不需要美国帮助来解决南海问题；朝鲜也宣布将对韩美两国举行的大规模联合军演发动“最严厉的惩罚”。到了8月20日，韩美联合司令部无奈的表示，华盛顿号航母不参加军演。美军航母二进黄海失败。

在这期间发生了香港游客菲律宾被挟持事件，就是中美斗法激起的一个浪花，菲律宾全面对华示好的态度引来了国旗被美国人倒挂。其实，美国的这个警告动作没有多少用处，几个大敌都伸着手要好处呢，这时还有闲心收拾菲律宾？就算奥巴马把菲律宾现政府推翻了，谁敢保证新上台的人会一定对美国客气？这种事华盛顿这么多年也遇上不少了吧？在这一轮的决斗中，以新加坡反水为标志，东盟国家全部明确选边站队了。
#+HTML:<strong><a>以后，美国在南亚再也翻不起浪花来了。</a></strong>
#+LaTeX:\red{以后，美国在南亚再也翻不起浪花来了。}

在中美决斗进入第二轮后，伊朗也开始宣称自己要搞核聚变，再一次用联合行动警告美国，一旦开始闹起来，东亚中东一起乱，看你先顾哪一头。这时，美国也改变了对付伊朗的办法，开始联合一切可能的力量来加强对伊朗的制裁，7月26日，欧盟通过了针对伊朗能源领域的单方面制裁，进入9月份，日本和韩国也先后宣布对伊朗实施单方面制裁。过去几年的制裁，也给伊朗经济带来了不小的麻烦，未了防止出现意外，内贾德签署命令，让革命卫队来掌握经济机构。

按照规矩，欧盟制裁伊朗了，美国应该在巴以和谈上面做让步。这时，又出问题了，以色列拒不让步。以色列不让步的原因主要是欧盟开价太高（全面开放加沙口岸）。其实，欧盟开价这么高也是被中国逼的，因为中国之前要求明确以色列的核身份，直接吊起了阿拉伯人的胃口。如果欧盟的开价太低，根本打动不了阿拉伯人，这也是没有办法的事。但是，如果完全开放了加沙口岸，那哈马斯很快又会活蹦乱跳起来，那时自己的日子又要难过了，为了把哈马斯骗到加沙并封锁起来美国以色列和法塔赫费了多大劲！

恼怒之下的欧盟出手教训以色列，8月3日，以色列遇上了一棵树引起的战争。一棵树战争后，黎巴嫩总统认为自己吃亏了，说要用先进武器装备军队。这时，美国却暂时切断了对黎巴嫩的援助，一看有缝可钻，真主党马上凑合起来说：要不你找伊朗帮忙？那是我大哥，我给你引荐？内贾德一听，马上回应：想要什么武器，拉个清单过来！俄罗斯也出来支持黎巴嫩的主权和领土完整。通过这一棵树，中俄欧之间似乎又要在伊核问题上联合起来。其实，这是欧盟在两面叫牌：如果美国再不做出让步，欧盟可要翻脸了。

两轮决斗之后，金正日点名要美国前总统卡特来朝鲜捞人。这个含义非常明确，你们美国还是从东亚退位吧，带着你们的人（驻日韩美军）走吧。可是，美国人仍然不死心。9月9日美国国防部说，华盛顿号航空母舰还要参加黄海军事演习。这时，美国又在威逼印度与巴基斯坦交火，企图搞乱克什米尔地区，切断巴铁通道。

8月1日，印控克什米尔地区冲突加剧，有8人被打死；2日，印控克什米尔地区再现警民冲突，导致5人丧生；4日，印度安全部队在切蒂斯格尔邦巡逻时遭到反政府武装纳萨尔派武装的伏击，双方发生激战；22日印控克什米尔地区再次发生多起暴力抗议活动。

8月底，解放军进入了巴控克什米尔地区（人数有一万左右）。很显然，这是北京在准备应对可能出现的印巴交火。这也是两个月来，北京第三次摆出准备一战的态度。北京的强硬，摧毁了华盛顿战略摊牌的决心。进入9月份，印控克什米尔又发生多次警民冲突，三个月来死亡人数达到80之多。9月13日，印度内阁开始讨论削克什米尔驻军特权，防止军民冲突再升级。之后，印巴局势趋于稳定。

9月15日，穆沙拉夫宣布，10月1日（注意这个日子）组建新政党重返政坛，计划在2013年参加大选，他要把“一种新的政治文化”带到巴基斯坦，并为巴基斯坦“找回自信”。

在搞乱克什米尔的同时，为了能拉阿拉伯人一起制裁伊朗，美国摆出彻底搞乱伊拉克的架式。这时的美军作战部队已经全面撤出了，伊拉克新政府却依然没有选出来，不排除伊拉克一分为三。这时的沙特，选择了破财免灾，跟美国人签了一个600亿的超大军火定单。沙特大吐血的原因有三，一是为不支持制裁伊朗付出代价；二是花钱买平安，防止美国把中东大乱引向沙特，三是对付伊朗在伊拉克疯狂扩张。当然，美国的恐吓并没有吓住三方已经结盟的土耳其、伊朗和叙利亚。

完成了这两步之后，美国又开始拿重启巴以和谈诱惑欧盟——之前以色列不是不同意完全开放加沙让欧盟很没面子吗？这次补回来。出乎美国人意料的是，这时的欧盟对美国人开出天价，他的要求就是前面提到的让美国同意欧盟彻底整合科索沃。要知道，这时《里斯本条约》已经通过了，美国想从欧盟内部下手击倒欧盟唯一地方就是科索沃了，再把这张牌扔了那麻烦可就更大了——如果欧盟内部整合提速了，那美元会死的更快！所以奥巴马直接说，兄弟，你比我还黑，我还是答应中国人（让出日本韩国）的条件好了！

当然，鉴于美国依然没有宣布取消航母三进黄海的事情，局势还会出现反复。不过，基本上大局已定。美国已经从朝鲜半岛到南海，再到克什米尔，再到中东闹了一圈子了，一点收获都没有。中国不是有这么一句古话吗？一鼓作气，再而衰，三而竭。现在的美国，也已经是“三而竭”了。

【金鸿评论】应该说，对于即将到来的被中国收编的命运，韩国还是可以面对现实的，7月底，中美第二轮斗法的关键时候，朝鲜一进行战争威胁，李明博就安排自己的财长跑到北京来赞美中韩之间曾经的宗藩关系，狂拍北京的马屁，态度非常之好。进入九月份，韩国人又用扩大开城工业员韩方工作人员规模、运送5000吨大米赈和举行朝韩两国两年来的首次军事对话进一步表明了自己投诚的态度。相比之下，日本就要难对付的多。要打个比方说，日本就是一个身强体壮的小个子，有一身的蛮力，真要硬拼，中国对付他也比较吃力，除非一枪（原子弹）把他崩了，可这小个子有个最大的麻烦，就是手脚被人锁着。现在他的主子要卖他，对卖主他是非常不满意，可他实在没有抗拒的能力，除非手脚被松开。美国会松开他吗？永远不会，两颗原子弹的旧仇，加上八十年代金融攻击日本的新恨，决定着美国永远不敢还日本自由身。否则，以日本人的报复心理，会让衰弱后的美国万世不得超生。

北京刚刚对华盛顿开了价，菅直人就蹦了起来，马上开始大谈驻日美军在“威慑中国”方面的重要作用。也不知道这个菅直人是眼瞎了还是急傻了，驻日美军一直只对日本人的钱包和日本女人有威慑作用，可从来没有威慑过中国。接着菅直人又要求强化日美同盟，摆出一副不被美国人玩弄就活不了的架式。中国则用舰队穿越冲绳近海的方式轻轻的敲了一下菅直人的脑袋：面对现实好不好？蹦来跳去有用吗？

现在，有必要全面理顺一下近几年的中日关系：自从北京开打朝核牌起，就露出了将来有一天收编日本的意思，日本对此也非常清楚，但是他不愿意接受。所以，当时的首相小泉就跟小布什谈判：“常言说的好，多年的父子成兄弟，你们美国也给我们当了60年多年的爹了，现在也该当回兄弟了吧？况且你身体也远不如以前壮实了，单凭你自己再想打遍天下无敌手是不可能的，我可以帮你，不过得咱俩拜把子，好不好？大哥？”小布什一听，说：“你不是我儿子，你是我的狗，是DOG，D-O-G，你的，明白？”从那时起直到小泉下台的一一年多时间里，小泉一直试图让小布什接受自己的想法，建立日美美日全球同盟，但是美国坚决不同意。

接着，安倍晋三上台，安倍一看形势，既然小泉的精诚所至换不来小布什的金石为开，那我就不装孙子了，装装大爷试试能不能把日美全球同盟搞到手？于是，安倍开始大玩强势外交，结果依然一无所获。接下来就轮到福田康夫了，他进一步把亲华动作做实，来试探美国的态度，结果很快被美国人搞下了台。之后又经历了两个短命首相，亲美的麻生和亲华的鸠山，最后就到了今天这位号称亲华却一上台就反华的菅直人。应该说，在美军控制下的日本政府，很难出现真正的亲华派，他们亲华只是手段，为了撑开日本全球发展空间的手段。当然，日本不愿意被中国收编，有一个很重要的原因，就是日本经济不比中国差。也正是日本的“经济价值”，让华盛顿恋恋不舍。在07年下半年，次贷危机出现了，美国经济失血严重，为了自救，美国人开始推高日元，日元汇率从07年6月1：124.16经过四个波段的拉升冲到了10年9月的1：82.85，在这四个波段的操作中，肯定有人套利丰厚，同时，疯狂升值日元也沉重打击了日本的出口制造业，有利于美国（也包括欧盟）改善贸易赤字。当然，中国也没闲着，持续采用经济手段打压中日贸易，使中日贸易占中国贸易总额的比例从05年的13%降到了现在9.4%，要知道，日本经济当年之所以从“失去的十年”里面走出来，相当大程度是依靠的对华贸易。现在，中美欧三家联手打压日本经济，再加上中国加强了对东盟的经济整合（这本身就是在排挤日本在东南亚的经济势力），日本经济这几年一直在走下坡路。有这样的恶劣的外部环境，日本的官方和企业界怎么努力都是于是无补的，除非他成为一个独立的国家。

美国这样算计日本经济对中国也有好处：从日本经济上吸血可以减缓美国倒掉的速度，打击日本经济有利用将来的中国收编——有钱人家的狗穷人是喂不起的，可有钱人变穷了之后，狗习惯了低档食品的时候，穷人就喂的起了。所以，站在中国的角度上看，美国不必立即退出东北亚，可以慢慢吃穷日本人，这个现实中国是接受的。

面对着将要出现的巨大变化，菅直人显得非常不适应：一会扬言要由日韩美共治东北亚；一会又履行承诺不去参拜靖国神社（这也是自二战结束以来日本内阁首次集体拒绝参拜靖国神社）；一会又要在新版的《日美共同宣言》中明确提出应对中国威胁；一会发和平宣言要求脱离美国保护伞；一会又跟着美国制裁伊朗；一会重申要强化中日经济合作，一会又正式启动销毁日本遗弃在华化学武器……忽左忽右，忽上忽下，简直就象得了神经病。

到了九月份，忍无可忍的菅直人主动出击了，在钓鱼岛抓了一艘中国渔船，并扣住船长不放，结果被北京狂扁一顿：切断省部级以上联系，切断赴日旅游，停止出口稀土，钓鱼岛执法，军舰巡航春晓……小日本除了被砸疼了干嚎几嗓子外，一点抵抗也没有，的确够可怜的。日本为什么要自取其辱呢？答案很简单，他是在做牌，这个从日本人的一个细微动作里可以清楚的看到：9月17日，日本外务大臣前原说如果一旦证实中国将勘探白桦油气田的话，日本将会采取断然的措施。

19日，这个前原又说：“尖阁诸岛是日本固有的领土，不存在所谓的领土问题……我们以妨碍公务的嫌疑逮捕了该船船长，并将根据日本的法律对此进行严正处理。”

20日，中国的两艘军舰就在高层授意下，前往春晓油气田巡逻，并且开始向春晓油气田搬运勘探设备。

这时，奇怪的一幕出现了，日本安排人出来强调，中方有意把撞船事件扩大成为领土争议事件，日方不会为“挑衅”所动，不采取对抗措施。

很显然，是日本人顺手一指在先，中国应手在后，如果日本真有本事翻脸，在春晓周围马上就会发生军事磨擦，不过日本人的态度马上软了。这里面就有问题了：任何一个国家，对于战争都是很谨慎的，日本也不例外。可他很轻率的就把战争爆发的红线划了出来，在中国应手后自食其言，很显然是不合常理的。他为什么要这样做呢？

其实，这次行动是菅直人向美国人要态度，看美国人是否同意搞日美全球同盟。如果美国点了点，菅直人是绝对不会放人放船的。正是因为美国人的不理不睬，菅直人只能用被中国狂扁一顿惨相告诉美国人，我们（日本人）是无力改变中国即将主导东亚的事实的，你们（美国人）如果真要抛弃我们的话，我们只有向中国投降了。

放人之后，日本还心存幻想，再次试探美国，搞出了日本是在美国压力下放人的传闻。结果中国再次应手：要求道歉、赔偿，并在钓鱼岛巡航，准备再次帮助日本确认美国的态度。结果呢，美国人有闲情倒挂菲律宾国旗，也有雅致陪韩国人搞反潜联合军演，就是没空就去看看日本那艘“被撞坏”的巡逻艇。

【金鸿评论】写到这里，该做一下总结了。

04年以来，北京首先以《反分裂国家法》锁死台湾，反手打出朝核牌在朝鲜半岛拖住美国，开始加快对东盟的收编工作。到了06年，中国以经济捆绑伊朗的方式加入了伊核六方会谈，之后推动伊朗核问题拖住美国，顺手展开全球布局。到06年6月，中俄联手第一次激化伊核问题逼迫美国允许中国加入巴以和谈，结果引得美国企图武力解决伊朗和哈马斯，之后被中国用朝鲜导弹发射和黎以冲突化解。07年夏天，次贷危机爆发，中国顺势推动人民币扩张，争夺全球金融霸权。同时借美国自顾不暇之时，二次激化伊朗核问题进攻美国的巴以和谈防线，美国再次摆出对伊动武的姿态，结果被中俄欧三家联手顶住。之后，美国以巴和和谈问题上对欧盟让步交换欧盟的对伊制裁、以允许欧盟政治整合换取伊拉克配合、以允许科索沃独立换取欧盟的阿富汗增兵，之后，《里斯本条约》出炉，在中俄的力压之下，美国在欧盟没有兑现阿富汗增兵的前提下不得不允许科索沃独立，接着地中海计划启航，欧元与美元的矛盾激化。08年6月，俄罗斯发力争夺石油定价权，美国为自保挑动格鲁吉亚闹事，后被俄罗斯肢解，欧俄新关系上路。

之后，人民币强烈的扩张势头引起了美国的警觉，美国对俄罗斯让步，以放弃东欧反导和在中亚方向对俄罗斯的挤压来换取俄罗斯的阿富汗配合和伊朗制裁。这时，中国在伊朗核问题上面临着以一对三的局面。中国马上调整对策，联弱斗强，化解了美国在伊朗核问题上的进攻。这期间，欧元对美元的步步紧逼和欧盟的拒不增兵阿富汗，引来了美国的杀招。美国先引爆迪拜债务危机警告、后引爆了希腊债务危机下手、制造了欧元危机，欧美反目。后来在最关键的时候中国拉了欧盟一把，欧元危机结束。

中国在全球攻城掠地的同时，也在不断的进行内部经济整合：05年开始的人民币升值是依靠外压进行的第一轮经济结构调整，中国逐步了摆脱对美国经济的依赖，加大对第三世界国家的经济融合，卖血汗、卖资源的局面初步改变；07年次贷危机开始后，中国利用自己的资金优势和外交优势逼迫欧盟和美国大量对华输出先进技术，提升中国经济结构，到今年（10年）年中，中国基本具备了经济上甩开美国的能力。这时中国对美国使用了杀招二次汇改，逼迫美国把东北亚让给自己，由此引发了中美之间的决斗。结果美国的三轮进攻均被中国打退。中国在全球斗争中的战略优势引来了德国的以身相投，中德全面战略伙伴关系出炉，在德国的牵引下，欧盟有全面倒向中国的态势。这时，一手拉着中国另一手拉着欧盟的俄罗斯没有选择的余地，只能全面向中国靠拢。中国以自己的实力再次成功的联合了欧盟和俄罗斯，亚（非）欧大陆全面整合即将提速。拿到了中国配合的欧盟转身对美国开出了退出科索沃的天价，美国不得不拒绝。之后，美国做势把东北亚让给中国。

这就是过去七年局势的整体概况。现在，可能有朋友会问，下一步局势会走向何方呢？巧的很，9月30日发生了几次大事，对下一步的局势走势会有深刻的影响起。下面看一下：

第一件，巴基斯坦宣布将拦截所有开往本国的北约供应军车。大家都知道了，自从上合完成了对阿富汗的战略包围之后，为了从巴基斯坦方向撕开一个口子，美国人是无所不用其极：自杀式爆炸袭击不断，越境轰炸连连，刺激印巴交火，甚至想接管巴基斯坦核武库，结果被中国用两次核爆（朝鲜）才稳住了局面。

9月30日，俄罗斯宣布，坚决反对美欧联手实施的对伊朗经济制（之前俄已为伊朗的首座核电站注核燃料），全面对中国靠拢。这时，美国已不可能再得到俄罗斯的阿富汗配合了。这样一来，巴基斯坦成为了北约（特别是美国）唯一可靠的食道。现在，轮到巴铁老弟开价了：如果想保证这条粮道的平安，第一不准再搞爆炸，第二不准越境袭击。可以肯定的是，美国没有说不的资本，而且随着局势的发展，巴铁兄弟也可以多要一点买路钱，毕竟巴铁也不富裕，公路维护的成本还是很高的。巴铁兄弟在跟着中国苦撑了四年之后，终于迎来了好日子。局势到了这一步，奥巴马喊了几年的增兵阿富汗也该停下了，如果美国不想陷得更深的话。

第二件，中国放了三个被扣的日本人。这件事国人比较关心，有必要详细说明一下：

9月28日，一开始在钓鱼岛扣人时无比强硬的日本外相前原召见了中国驻日本大使，要求中国确保四个日本人的人身安全，并且希望中国能让日本驻华使馆的人每天见这四个日本人一面，关怀之情日月可鉴。我就想不明白，你这么在意这四个小崽子，怎么不要求中国放人？按前原话说，理由应该是“我们只能信任中国”。既然你相信中国还说什么要求保证人身安全还要一天一见干吗？中国政府又不是黑社会，抓人的事全世界都知道，还会虐待他们不成？你到底信任还是不信任中国呢？

前原为什么这么做？一是演戏给国内看，所以他才没话找话说，二是演戏给美国人看，这一点日本官房长官仙谷由人说的明白，改善中日关系的主动权在中国手上（暗指未来中日关系的主导权在中国）。仙谷和前原的表态，其实是在向美国人要态度：如果你真的要退出东亚，我们也只能接受现实了。结果当天有个美国议员说了一句大实话，钓鱼岛自古以来就是中国的一部分。既然美国人决定不管这一摊子了，那中国接下来又是怎么对付认罪态度良好的日本人的呢？放三留一，手法跟日本之前的一模一样，只不过放人的背景大不相同：

9月12日半夜，戴秉国把日本驻华大使丹羽宇一郎从床上拖起来狠狠数落一顿，强烈警告日本人不要误判形势，之后日本放了人；中国则是在日本连放人要求都不敢提的条件下放的。如果站在被放的三个日本人的角度看，放不放他们是天壤之别；可站在国家斗争的角度看，扣一个和扣四个没有区别——事情依然没有结束！很显然，北京摆出了进一步揉搓菅直人的姿态。北京想得到什么呢？道歉，赔偿，另外在钓鱼岛规矩点，不要再生事端。对于中国的动作，美国人的态度是什么呢？希拉里说了，祝中国人民国庆节快乐！她的话其实可以改一改，祝中国人民在国庆节玩弄日本人快乐！

【金鸿评论】美国选择在东亚断腕，必须从其他方向捞点本回来。现在，美国真正可以捞到好处的地方只有两个，欧盟，日本。因为他们三个之间经济上高度竞争，美国的整体实力最强，压倒另外两家自然不在话下。至于第三世界国家，只要对华示好的一律不准美国动，包括印度，这是个阶级立场立场问题。另外，美国对俄罗斯的全方位封堵是必须的，东欧反导要搞，乌克兰格鲁吉亚那边也得往回捞。

对欧盟来说，配合中俄策反以色列，彻底打掉以色列的强硬是他必须得做的，这也是欧盟要求美国对自己让步的资本所在。在中俄的理解下整合科索沃，和亚欧大陆经济整合（地中海计划也可以看作是这其中的一部分），同时加大对南美的渗透，力保欧盟的全球地位不再滑坡。但是，欧元与美元的争锋必将引来美国对欧元的再次下手，关键时刻中国会拉欧盟一把，不会让他倒掉。随着以色列的倒戈，中东会慢慢迎来真正的和平。在实现和平的过程中，中国会扶持起两个代理人集团，一个是土叙伊联盟，一个是沙特领导的海合会。通过这两个集团，中国将控制中东（埃及也会靠过来）。

对俄罗斯来说，努力消磨掉美国在波兰捷克乌克兰格鲁吉亚的影响力，再与中国联手从阿富汗赶走美国大兵，顺势南下联合印度，就可以进军非洲了，再加上与中国欧盟共推亚欧大陆整合、加大对南美的布局，俄罗斯也可以撑开自己的全球发展空间。

在中国修理日本人的同时，俄罗斯也拿北方四岛挤兑上了日本人，两家的配合还是很默契的：一个从琉球方向掐住日本南下的去路，一个从北方四岛方面断了日本北上的路线。美国也可以含笑九泉了，他退出东北亚以后，日本仍旧是瓮中之鳖。至于中国，整合东北亚的关键是收编日本。考虑到日本庞大的经济规模所带来的不利因素，加上不能让美国过快的倒掉，中国允许美国继续吃穷日本，直到日本彻底投降。那时，琉球问题和东海划界也就一并解决。如果走先难后易的路子，把台湾问题和南海领土争端放在解决琉球问题的后面，时间上会慢一点，可效率上会高很多，手法也文雅的多。东亚的问题全部摆平以后，反手解决藏南问题将不在话下。那时，中国就可以成为这个世界的新主人了。

今天是国庆节，是祖国母亲61岁的生日。在这个激动人心的时刻，全球局势也迎来了重大的变革——中国开始一步步主导这个世界了。这一成就的取得，首先要感觉伟大领袖毛主席，是他一手缔造了我们的共和国，并领导中国人民建立了完整的工业体系，搞出了两弹一星，重进联合国拿回了否决票，构建了中美苏全球战略大三角，划分了三个世界搞全球统战，他是中华民族永远的巨人。这一成就的取得，还要感激我们英明的胡哥，他在极端艰难的情况下，领导中国人民在短短几年的时间里，取得了令人惊叹的成绩。

文章写到这里，基本结束了。我的心情也很激动，可是我是个土包子，不会写诗，在这里，只借毛主席的一首诗，表达我此刻的心情：

人民解放军占领南京（1949年4月）

钟山风雨起苍黄，百万雄师过大江。

虎踞龙盘今胜昔，天翻地覆慨而慷。

宜将胜勇追穷寇，不可沽名学霸王。

天若有情天亦老，人间正道是沧桑。




** 【金鸿评论】04年以来的大国斗争回顾（附录）
[2010-10-0117:12:53]



《04年以来的大国斗争回顾》一文共分上、中、下、续和附录五篇，57199字，今天全文都发完了。如果朋友们喜欢，尽可转发，只需注明作者即可。

附录一：怎样搞经济才能真正强大一个国家？

经济是什么？经济就是为了满足人类生产和生活需要所进行的一切活动，这些活动包括生产实物和提供服务。在工业革命以前，人类的经济活动主要是农业和建筑业。工业革命以后，人类的生产活动范围扩大了：

第一次工业革命（蒸汽时代）工业实现了机械化，纺织、采矿、治金行业取得了大发展；

第二次工业革命（电气时代）工业实现了电气化，电力、交通运输、化工、机床、通讯等行业得到了长足进步；

第三次工业革命（信息时代）又让电子技术、原子能、航天技术、新能源技术、新材料技术、生物工程、海洋技术兴盛起来。

在历次的工业革命中，能在前沿领域（产业）有所发展的国家，都是时代的强国，而在这些关键产业无所作为的国家，都只有挨打的份。

第一次工业革命发生在英国，因此成就了日不落帝国；工业革命随后传播到整个欧洲大陆，法国、德国也跟着强大了起来。等到德国强大之后德皇发现，殖民地都被英法两国抢干净了。为了争夺殖民地，德国就联合奥匈帝国等几个国家跟英法等国家抢地盘，爆发了第一次世界大战。当时的中国虽然也加入了英法美组成的协约国并成了战胜国，可是在接下来的巴黎和会上却被出卖了，中国一直希望收回的山东被列国从德国人手里夺去当作人情送给了日本人，由此引发了五四运动。中国为什么会被出卖？因为当时的两次工业革命中国几乎都没参与，经济上太弱小，根据丛林法则，弱者是不被当人看的，不卖你卖谁？

第二次工业革命主要发生在美国，美国也就很自然的成了当时世界上最强大的国家，当时，由于美国的大力扶持，德国也成了这次工业革命的受益者。只是德国人没想到美国人是在借刀杀人，用希特勒的炸弹打残了英法苏三强，等英法德苏拼的元气大伤筋疲力尽的时候，美国对德宣战了，接着打败了德国又顺手摁住了新兴强国日本，一举成为西方世界的新霸主。

从上面英法德美的先后崛起可以看出，只有占领了产业链最高端的国家，才能成为时代的强国。

毛主席时代，中国成功的抓住了第三次工业革命的机会，在当时的新兴产业原子能和航天产业奋勇争先，搞出了两弹一星（最先进的技术从来都是先用在军事上），与美苏一起占领了当时全球产业链的最高端，这才形成了中美苏战略大三角的局面，中国人从此再不受人欺凌，扬眉吐气的成为了世界一极。78年以后，中国开始改革开放，放弃了在信息技术产业努力赶超的机会，却去当什么世界工厂卖血汗、卖资源，卖到两国论出现，卖到了大使馆被炸，这时国人才惊醒了，改弦更张重新开始追。胡哥上台后没几年，中国就有龙芯了，支线飞机跟着上天了，北斗也定位了，高铁也领先了，中国的综合国力上了一个新台阶。

现在，总有人拿着30年前中国人吃不好穿不好来攻击毛主席，说他不会搞经济。试想，一个不懂经济的人，能建立起一套完整的工业体系和社保体系？那些精英们到是懂经济，会接轨，遵惯例，守规则，把中国已经建好的工业体系的最高端部分放弃了去大批进口外国货，自己主动爬到产业链低端去被人奴役，还说什么这是国际分工——人贩子把你全家的女人拐到窑子里去卖身这是不是国内分工？这还不算，还把一套好好的社保体系给砸烂了，把中国人折腾得看不起病、上不起学、养不老、住不起房，死了买块墓地都买不起！这也叫懂经济？这是哪门子经济？也许，这在他们眼里不算什么，他们的最高领理想是把中国彻底搞分裂了，自己好在洋大人的扶持下爬到人民头上当主子。

庆幸的是，胡温没有继续按那一套走下去，而是重新使用毛主席当年搞经济的那一套路子了：

今年9月8日，国务院通过了《国务院关于加快培育和发展战略性新兴产业的决定》，在《决定》中明确将战略性新兴产业定为我国国民经济的先导产业和支柱产业。被圈入战略性新兴产业大名单的有：节能环保、高端装备制造、新一代信息技术、生物、新能源、新材料和新能源汽车等七个产业。这是中国自03年以来的第三轮经济结构调整，之前借着全球金融危机的机会，大量从欧美国家引进先进技术，提升部分目前中国已发展产业的水平，并向广大的第三世界国家转移一部分低端产业，同时全球海量收购资源。如果说之前的结构调整是在打基础的话，那么这一轮调整就是要大发展了。

下面简单分析一下进入大名单的七个产业，看一看下轮经济结构调整将对中华民族的明天产生怎样的作用：

1、环保节能：改革30年来，中国的环境污染已经到了极其危险的地步，再不改善环境，我们的下一代将无法在这片土地上生存；同样，如果不发展节能产业，中国人的生活水准如果达到美国的水平，那全世界的资源都不够中国人自己用的（这也是胡哥上台以后就满世界抢石油抢矿业的原因），那时为了争夺资源，中国将成为全世界的敌人，再次爆发世界大战将是很正常的事情。这应该是北京把环保节能产业列在第一位的原因。

2.高端装备制造产业：装备制造业这个名词是北京为了“和平崛起”专门发明的一个名词，其实是指重工业和军工产业。如果我们高喊发展军工产业，不利于团结那些跟中国有领土争端问题的国家，也会给某些人落下鼓噪中国威胁军事论的口实，所以，我们不发展军工产业，我们只发展装备制造业。这个产业包括各种工业母机（如数控机床、工业机器人、大规模集成电路等等），重要的机械、电子基础件（如电力电子器件、仪器仪表、自动化控制系统等等），重大成套技术装备（如资源开采设备、大型电力成套设备、高铁、输水输气等等），还有就是大型的军工项目，比如北斗、天宫、四代战机、新型核潜艇等等。我们都知道一句话，落后就要挨打。这句话应该改一下：装备制造业落后就要挨打。前面把环保节能列在第一位，是为了我们的下一代能活下去，现在把高端装备制造业列在第二位，是为了今天的我们能活的下去、不受人欺负；

3、生物工程、新材料、新能源、新一代信息技术产业：这四个产业都是新兴产业，也是新的全球经济增长点，中国与西方国家在这几个产业的差距不大，基本处于同一起跑线上，如果集中力量发展的话，更容易实现超越，也有利于中国在这一轮的科技革命中站在前头。

4、新能源汽车：包括燃料电池汽车、混合动力汽车、氢能源动力汽车和太阳能汽车等。把汽车行业列进来，其实是在亡羊补牢。十多年前，房地产和汽车两个行业被搞成了支柱，十多年后，房产支柱把中国人折腾的买不起房子、贫富差距超大，没办法，现在开始打房价，砍支柱。其实，汽车做支柱的麻烦也不小，只不过现在表现还不明显。要知道，在这个世界上除了美国没有一个国家敢把汽车做成经济支柱的。这是为什么？烧油太多，资源供应跟不上！中国这么多人口，如果象美国人那样开汽车，那全世界的汽油都不够中国人自己烧的。如果当初没有大力扶持这个产业也就算了，现在已经扶起来了，产能巨大，就业人口又多，一个房地产支柱还没砍倒再砍汽车这根柱子，中国经济非崩溃了不行，又不能等房地产业收拾完了再它，那样10年时间又浪费掉了。所以，北京出了这么一招，把汽车的动力源改了，不再烧油，问题就解决了。如果不是能源这个瓶颈卡着，汽车行业对于经济发展的正面作用还是非常巨大的，这么一改之后，也就变被动为有利了。而且，新能源汽车方面中国和西方同样处在同一起跑线上，有利于中国赶超超西方国家。这也是胡温的高明之处。

对比三轮结构调整可以发现：第一轮是最被动的，利用处部压力（提高汇率）来调整产业结构的；第二轮则抓住了欧美深陷危机之中的机会，逼他们交出技术；第三轮结构调整是完全主动的，这一轮结构调整采用的是财政、税收、金融政策和行政手段进行的。比如税收减免、贷款优惠、财政补贴甚至奖金鼓励等。结构调整方法由被动转为主动，也是胡温真正掌控了国内局面的表现。另外，调整产业结构时，还应该注意调整产业的区域布局。关于这一点，可以看一下建国60年来的几届领导人的做法。先看毛主席时代：建设大三线，发展云贵川、陕青甘、晋豫冀、鄂湘桂等内地省份，努力拓宽中国的战略纵深，提高老少边穷地区的人民生活水平，增进民族情感和凝聚力。一旦与人开战，根本不用担心用砸坏家里的坛坛罐罐。改革开放以后，一切都翻了过来，重点发展沿海区域，在富起了一部分人之后，也制造出了严重的区域收入差距，还给自己背上了沉重的包袱——万一发生战争，改革的成绩将变为一堆瓦砾。这样的状况是很容易受人要挟的。到了上世纪九十年代后期，李登辉台独闹的厉害，北京绝对是有心武力解决这个问题的。可是，中国的经济重心在沿海，在珠三角。一仗收台的代价是巨大的。为了扭转被动局面，这才重新提出开发大西北，回到了当年建设大三线的老路上。

当然，对于发展经济而言，重视产业结构布局是必须的，但不是全部内容，还要有合理的收入分配制度和完善的社会保障制度做支撑，这样，才能让每一个社会成员都工作的开心、放心。这些工作也都在有条不紊的展开，看报道大家应该有数。20多年来，一直在搞市场经济，宣布企业家和企业管理的书特别多，以至于许多人认为企业家们好似天马行空，一个个是多么的不得了。其实不然。说老实话，做企业还真的没有三篇文章，不然如果解释李嘉诚、霍英东、王永庆、黄光裕这些首富们都没有什么学历呢？其实不仅中国，外国也一样，盖茨、戴尔等人的学历也很低。别看他们读过大学，在他们所在的行业，他们都是低学历者，不信到微软西雅图总部找找看，除了看门的保安恐怕没人比盖茨学历更低了。那么，做企业靠的是什么呢？踏踏实实。本来就是一些简单的事，只要你认真的一遍遍的重复做，必定会成功。有人可能会说，那为什么那么多人做企业都失败了？道理也不难懂，简单的事情不是人人都能做的好的，更何况是重复做。企业管理真正的道道，不超过十句话百十个字，简单的很。

真正对企业发展有致命影响的，还在政策层面。比如前面提到的日本经济遇上的情况，广场协议被打击之后，日本企业大都很受伤；近三年中欧美联合算计日本，日本经济自然在滑坡，这一切是松下幸之助之流无法扭转的。再看中国，近几年进入世界500强的企业逐年增加：06年19家，07年22家，08年26家，09年43家，10年54家。为什么中国企业发展的这么迅猛？因为中国的全球战略帮他们撑开了发展空间。举两个简单的小例子，大家就可以明白：10年7月份，美国来拉欧盟制裁伊朗，伊朗马上宣布了与中国的400亿美元石油合同；接着美国以三分伊拉克吓唬中东各国，沙特一下子买了美国600亿美元的的军火。试想，单凭企业之力，搞个百亿级的定单，要多久？要多难？再比如，一个对华玩具业制裁，多少玩具企业倒闭？中国的一个房地产业做支柱的政策，十年时间造就了多少亿万富豪？这是王石他们有本事吗？如果谁认为他们真是天神的话，过两天看看在今年的国庆黄金周能卖多少房子就知道了（昨天刚刚出台的房价打压政策把全中国所有地产商的销售计划全毁掉了）。

正是因为政治对企业生存和发展的巨大影响力，欧美国家的资本家们才会不择手段的控制他们的政府，为自己捞好处。所以说，西方国家的政府，是资本家的，而中国的政府，是人民的。这就是最大的差距。

附录二：人民币扩张大事记

2007年4月2日，美国第二大次级房贷公司新世纪金融公司申请破产保护，次贷危机浮出水面，中国趁机开始了人民币的全球扩张之路。

2007年6月27日，财政部发行15500亿元特别国债购买约2000亿美元外汇，组建国家外汇投资公司。

2007年8月9日，北京暗示，如果华盛顿实施贸易制裁以迫使人民币升值，它可能清算它大量持有的美国债券。

2008年，中国与越南、尼泊尔、蒙古、俄罗斯和老挝等周边8个国家签订了自主选择双边货币的结算协议。巴基斯坦、尼泊尔、越南、俄罗斯和蒙古等多个国家也通过立法，允许在出口贸易中使用人民币结算。

2008年12月12日，中国人民银行与韩国央行签署的1800亿元框架协议，

2008年12月24日，国务院常务会议提出，对广东和长江三角洲地区与港澳地区、广西和云南与东盟的货物贸易进行人民币结算试点。

2009年1月20日，中国人民银行与香港金管局签署的2000亿元正式协议。

2009年2月8日，中国人民银行与马来西亚央行签署的800亿元正式协议。

2009年3月11日，中国人民银行与白俄罗斯央行签署的200亿元正式协议。

2009年3月23日，中国人民银行与印度尼西亚央行签署的1000亿元正式协议。

2009年4月2日，中国人民银行与阿根廷央行签署的700亿元正式协议。

2009年7月1日，中国人民银行、财政部、商务部、海关总署、税务总局、银监会共同制定《跨境贸易人民币结算试点管理办法》并予以实施。

2010年5月17日，三菱东京日联银行获得中国人民银行与大陆银监会同意，将发行人民币10亿元（约合新台币46.7亿元）债券，成为在大陆发行人民币债券的首家外商，并有助于大陆推动人民币国际化。

2010年6月9日，中国人民银行与冰岛央行签署的35亿元正式协议。

2010年6月19日，中国人民银行宣布，启动二次汇率改革。

2010年6月22日，中国人民银行公布扩大跨境贸易人民币结算试点，在此前上海、广州、深圳、珠海、东莞5个城市的基础上，又增加了北京、天津、内蒙古等18个省区市，作为跨境贸易人民币结算试点地区。境外结算地域，也由港澳、东盟扩大到所有国家和地区。

2010年7月24日，中国和新加坡签署了1500亿元正协议。

2010年8月19日，中国外汇交易中心开始挂牌人民币对马来西亚林吉特交易，这是外汇交易中心推出的第六个外币交易品种。

2010年07月12日，大公国际资信评估有限公司发布了对全球50个国家的主权信用评级报告。这是中国首次打破美国垄断，发布全球范围的主权债务评级。

这一行动是中国争夺全球金融霸权迈出的重要一步——争夺资本品定价权。

2010年9月8日，中国银行在香港发行总额不超过50亿元的人民币债券。





* Footnotes

[fn:jinhong0101] 320 台湾大选

[fn:jinhong0102] 东北亚经济一体化，何谓一体?北京通过对东北亚经济的整合来全面主导东北亚局势，一旦完成，美国影响将被全部挤出，日本韩国将变为中国全球经济布局中的一个棋子。

[fn:jinhon0103] 东山岛军演

[fn:jinhong0104] 阿扁双十致词

[fn:jinhong0105] 吴姨是谁?

[fn:jinhong0106] 亚太安全会议

[fn:jinhong0107] 军事打击伊朗？

[fn:jinhong0108] 巴以和谈

[fn:jinhong0109] APCE

[fn:jinhong0110] 真主党和巴勒斯坦的关系

[fn:jinhong0111] 入联公投

[fn:jinhong0112] 门罗主义

[fn:jinhong0113] 安纳波利斯和会

[fn:jinhong0114] 戈兰高地

[fn:jinhong0115] 黎巴嫩与中国，真主党-伊朗-中国？

[fn:jinhon0116] 集安组织

[fn:jinhong0117] 周小川说，这个美元毛病太多，问题成堆，应该考虑在国际储备中扩大特别提款权的用途

[fn:jinhong0118] 奥巴马

[fn:jinhong0119] x

[fn:jinhong0120] x

[fn:jinhong0121] x

[fn:jinhong0122] x

[fn:jinhongj0123] x

[fn:jinhong0124] x

[fn:jinhong0125] x

[fn:jinhong0130] x

[fn:jinhong0128] x

[fn:jinhong0129] x

[fn:jinhong0135] x

[fn:jinhong0133] x

[fn:jinhong0136] x

[fn:jinhong0137] x

[fn:jinhong0138] x

[fn:jinhong0139] x

[fn:jinhong0126] x

[fn:jinhong0127] x

[fn:01jinhong0131] x

[fn:jinhong0132] x

[fn:jinhong0134] x* Footnotes

