# -*- org -*-

# Time-stamp: <2011-08-04 18:29:23 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent


* 南极气温上升 冻雨致小企鹅大量冻死

  [2008-07-17 14:12:36]


  
    金鸿：人类用自己贪婪的欲望组成的“那只看不见的手”，把各种生物推向了灭绝的境地，也把自己一步步推上了绝路。如果所谓的“市场机制”还在支配人
类的经济活动的话的，人类的灭亡将在不久的将来成为现实，也许100年都用不了。可怜的自作聪明的人类！

    南极地区连续爆发反常暴风雨，导致成千上万只新生小企鹅活活冻死。据估计，经此一难，南极企鹅数目将锐减两成。南极专家认为，这是气候变化给南
极地区带来的又一灾难性影响。

    南极下雨多过下雪

    科学家相信，受灾最严重的阿德利企鹅数目将下降至80%，如果天气短期内不能转好，情况可能更严重，不到10年，这一物种或将从地球上消失。

    在过去50年里，南极大陆的平均温度上升了3摄氏度，达到-14.7摄氏度，冬季频发的暴风雪渐渐被更加冰冷刺骨的暴风雨所代替。

    阿德利企鹅刚出生时仅有薄薄一层保暖皮毛，小企鹅需要40天的时间才能长出防水的羽毛，然而连日暴雨将整个巢穴都浸湿了，企鹅父母在时还能为子女
遮风挡雨，一旦离巢觅食，小企鹅往往会因为体温过低而死。

    “长期以来人们注意到了冰架在溶解，但南极冷雨却是前所未有的新现象，企鹅正面临寒冷致死的威胁。”刚刚从南极归来的纽约探险家强·鲍尔马斯特说
，“它们的皮毛可以在大雪中保护自己，却不能应付暴雨，这就好像一个穿着厚夹克却被雨淋湿的人一样。”

    帝企鹅乐园遭摧毁

    奥斯卡获奖纪录片《帝企鹅日记》描绘了憨态可掬的帝企鹅生存及繁衍的场景，令人印象深刻，然而西雅图华盛顿大学生物学教授笛伊·波尔斯曼痛心指
出，2006年12月，也就是这部电影拍摄不到两年后，她再抵达当年的拍摄地南极南部，“已经完全认不出这就是纪录片里的企鹅乐园。”笛伊说，她完全没看到
帝企鹅幼仔，也看不到浮冰，冰山数目大大减少。据悉，去年9月份，也就是帝企鹅育儿期间，当地曾被一场大型暴风雨所袭击，“极少企鹅幼仔能够幸存。”

    “看见企鹅们脚下都是下一代的残骸，这才是我所见过气候变化最令人震撼以及最直接的证据。”鲍尔马斯特说。
