# -*- org -*-

# Time-stamp: <2011-08-04 18:23:42 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent


* 【金鸿评论】近期国际局势观察（29日更新）
  [2008-05-18 15:28:30]

  
    警告：任何煸动反毛反中央言论的跟贴，一律删除！毛主席和胡主席是我最尊敬的人。

    为了保住中东主导权，小布什下了最大的赌注：在自己下台之前就巴以和谈问题达成协议并让巴勒斯坦建国。其实，要做到这一点，必须让阿拉伯世界满
意，让欧盟配合。阿拉伯世界的要求很简单：巴以谈判必须有一个清晰的机制和明确的时间表。为此，美国向阿拉伯世界施加了强大的压力，所以，欧佩克轮
值主席4月28日出来说油价可能上涨至每桶200美元就不足为奇了。至于布什到沙特谈什么增加石油产量以降低石油价格更是糊弄鬼的，布什真正要和沙特国王
谈的是石油能否继续用美元结算的问题。

    为了压服阿拉伯世界，摆平哈马斯是必须的。所以，以色列一直在加沙不断的发动袭击，目的就是压服哈马斯的支持力量（巴勒斯坦人民）。巴勒斯坦各
派别接受埃及的斡旋后同意与以色列实现停火，以色列依然大打出手。哈马斯的停火举动展示出了足够的和平诚意，在巴勒斯坦人民和阿拉伯世界心目中得到
加分是必然的。而为了维持局面，以色列不得不硬着头皮继续做损人不利已的事情。当然，既此如此，奥尔默特的表现依然让美国人不满意，所以奥尔默特最
近官司连连缠身，美国人的潜台词就是如果干不好你就下台。哈马斯的局面则是越来越理想，兴奋之余的哈马斯来了个顺风扯旗，宣布将扩大其所领导的“政
府”规模，真是一点机会也不浪费。

    美国想在中东摆脱被动局面，必须瓦解伊朗叙利亚同盟。所以，美国对准叙利亚出手了，一方面用所谓的“叙核问题”向叙利亚施压，另一方面用戈兰高地
用诱饵分化伊叙同盟。为缓解叙利亚的压力，伊朗果断的出手放火，宣布自己已经在对外石油交易中完全停止使用美元结算，这是一步险棋，当年的萨达姆就
是因为这一点才能为阶下囚的。非常及时的，盖茨说林肯号航空母舰抵达海湾水域是为“提醒”伊朗美国军事力量的存在的。结果伊朗不但不害怕，反而继续在
伊拉克给美军找麻烦，并且明确表态“除非美国停止武力攻打伊拉克人，伊朗不会与美国就伊拉克安全问题展开新一轮会谈”，用伊拉克泥潭死死拖住美国，确
保自身安全。气急败坏的美军参谋长联席会议主席马伦出来旁敲侧击的吓唬伊朗（5日说，美军久陷伊拉克和阿富汗战场，使得美国难以对伊朗发起任何打击
。）俄罗斯也及时出来给伊朗撑腰（俄罗斯总统普京5日表示，红场胜利日阅兵式展示军事装备不是炫耀武力，而是展示俄罗斯的能力。）另外，各方还在黎
巴嫩狠较了一回劲，真主党通过武装斗争成功的迫使黎巴嫩政府放弃了两项针对自己的决定，此举也成功的为叙利亚减压。

    对于最核心的巴以和平问题，由于哈马斯的搅局，中俄在背后使劲，根本结不出任何果子。中俄的手段还是用伊核谈判撬巴以和谈，只要中俄在巴以和谈
中说不上话，伊核就出不了任何让美国人满意的结果。伊朗不接受停止铀浓缩活动的提议是必然的，并且以以色列不参加国际防止核武器扩散条约为由，提出
自已不会接受大规模的核审查，顺便拉了个垫背的。至于阿巴斯想“与时间赛跑”，那只是一厢情愿。

    布什访问中东的结果很不理想。沙特给中国灾区的捐款大家都看到了，5000万美元现金外加1000万美物资，沙特这一次如此大方，不外乎是表投靠的诚意
。我们已经成功的得到了阿拉伯世界的人心。这一点，是武力征服难以做到的。有了这个基础，阿盟发表声明重申建立以东耶路撒冷为首都的巴勒斯坦国对地
区和平非常重要就非常自然了。美国无奈，不得不下决心先摆平伊朗叙利亚哈马斯等刺头。但是，美国实在没有能力应付两面作战，只在16日宣布恢复对朝鲜
的粮食援助，同时向中国示好，提供四川震区的卫星照片，并在本周末向中国提供两架飞机的赈灾物资。很显然，美国是希望稳住东亚，集中力量收拾中东的
烂摊子。所以，以色列表态，美国和以色列一致认为有必要就伊朗核问题对伊采取“切实行动”，以阻止伊朗研发核武器，并且说到做到，当天就有5名伊朗驻
伊拉克使馆的工作人员在一起枪击事件中受伤（其中两人伤势严重）。接下来，伊朗将面临着严峻的考验。当然，这也是最严峻的一次考验，这一次只要伊朗
顶住了，朝鲜今天的美式待遇就是明天伊朗的待遇，同时，中俄将在中东和平进程中有所斩获。

    东线。胡主席访日的基调早在5月4日10+3财长同意筹建800亿外汇储备基金时就已定好了。在这样的背景下，马英九声称“台湾作为一个东亚国家”自然不
足为奇，最可笑的是美国以裁决美军海军陆战队队员强奸一位日本妇女的罪名不成立的方式警告日本，我才是你的亲爸爸。尽管这种小手腕没什么大作用，却
让那个美国流氓兵走了一回大运，免受了牢狱之灾。接下来，美国还会继续想办法拉拢日本来对抗中国，不过，由于在朝核问题上主导权的丢失，为了稳住东
亚的局势，对朝鲜让步是美国不得不做为的选择，而这一点将是对日本核心利益的最大出卖。所以，日美离心实属必然。这一次中国放日本（包括韩国）进来
救灾本身就是给他们面子，拉拢日韩，把美国赶出东亚甚至整个亚洲，是中国的既定战略，目标正在一步步的变成现实。

    20日更新：俄罗斯国际文传电讯社19日发表文章，声称“印度、蒙古、伊朗、阿富汗、巴基斯坦可能将加入上海合作组织。”如果情况属实，这将是上合组
织第一次扩员，而且规模如此庞大。

   【金鸿评论】在这个时候放出这样的消息，是中俄给伊朗和叙利亚的最大支持，也是为巴基斯坦打气，也是为了近一步拉拢印度和蒙古。震慑的对象自然
是美国，一并警告欧盟。如果伊朗真的成了上合的正式成员，那么结果只有下面两个中的一个：欧盟在伊核会谈中出局，美国对付伊朗的行动全面失败。当然
，中国的行动中也可以看伊朗叙利亚面临的压力之大，中俄决心之强。现在到了欧盟和美国做决择的时候了。所以，我们就看到了阿巴斯出来发飙说什么“巴
方对布什在以色列议会的讲话感到失望和愤怒”，这里面显然有欧盟在出力，警告美国赶快在巴以和谈上弄个结果出来，否则自己（欧盟）也挺不住了——阿拉
伯世界要转投中俄、不再依赖欧盟了。在这个时候俄罗斯获得沙特280亿元武器出口大单也说明了阿拉伯世界人心正在转向。而以色列及时的出来造谣说“如果
巴以不能在今年年底前达成和平协议阿巴斯将辞职”自然有替美国出头警告阿巴斯的意思，其实，单单一个阿巴斯又如何左右的了局面？这样的警告只能让当
狗的奴才们心寒罢了。最有意思的就是印度媒体出来放卫星说金砖四国将在20年内取代七国集团，个中滋味某些国家自己慢慢品尝好了。我们的目标：主导中
东和平进程。

   21日更新：美国白宫20日发表声明，否认了以色列《耶路撒冷邮报》有关美国总统布什计划在其任期结束前攻打伊朗的报道。

   【金鸿评论】中俄一亮剑，美国变软蛋。伊朗的态度也跟着强硬起来，伊朗外长穆塔基直接说“与美国双边谈判问题目前没有列在伊朗的工作日程中”，这
也太不把世界警察放在眼里了。可惜的是，美国没有了反击的能力。在这样的情况下，美国又凭什么收拾掉哈马斯？眼看着哈马斯坐大、在中东的影响力越来
越强，想继续在中东保持影响力的欧盟（其代表是法国）与哈马斯眉来眼去是不可避免的。至于美国人的批评，法国人只能当是听到驴放屁了。如果美国和欧
盟还不打算请中国介入巴以和谈的话，伊朗的表现将会越来越让布什头大。
    对于马英九，一走狗耳，理他干嘛？我们只要摆平了他的主子，还愁它不摇尾巴？其实，322以后，台独牌就废掉了。只要目前的战略能持续下去，收台
只是个时间问题。不必介意。可以预见的是，将来台独分子还会有反弹，但能量非常有限，不值一提。

    美国没有能力压服什叶派的伊朗叙利亚，为保石油美元霸权，只好硬压逊尼派国家：

    美国众议院20日通过一项法案，授权联邦政府可向美国法院控告石油输出国家组织(OPEC)涉嫌操纵油价。这是这个国际组织近来因油价飙涨而遭受的最新
一击。

    【金鸿评论】油价怎么飞上天去的傻子都知道。OPEC能操纵的了油价？那阿拉伯国家就是全世界的老大。贼喊捉贼。

    22日更新：以色列和叙利亚目前正在土耳其的斡旋下举行间接和平谈判，双方可能将签署一份和平协定。未经证实的叙以和平协定草案被以色列媒体提前
曝光，其内容表明伊朗在中东的利益可能会严重受损。

    【金鸿评论】这也是白宫发言人说“美国不反对以色列和叙利亚举行间接和平谈判”的真实原因所在，那就是离间叙伊关系。其实，想离间叙伊关系，关键
是得吓得住叙利亚，否则，都是虚的，当然，想吓住叙利亚，还得依靠以色列关键时刻顶得上去。在这个关键时候，伊朗出来放话，就自己“不需要国际社会
提供任何安全承诺和保证”可以给人足够的想象空间。巧的很，奥尔默特又有了受贿的辫子被人抓住，足见有人已经急的火烧火燎了。不过，奥尔默特好象不
太配合，不然，让新闻局长席曼出来说什么“布什应不会把伊朗核武问题交给下任总统处理”、“他极有可能在任期仅剩一个月的时间时对伊朗发动攻击”干嘛？
这不是攀着美国一起动手吗？如果美国人自己方便动手，还要你以色列干嘛？

    再看一下两条油价方面的消息：

    由于美国原油商业库存意外下降，国际油价21日大幅飙升，纽约市场油价收于每桶133美元之上。  

    利比亚国家石油公司主席加尼姆21日在利比亚首都的黎波里说，世界石油市场价格上涨与供应量无关，即使欧佩克组织增加石油产量也不会改变这一局面
。

    【金鸿评论】油价继续往上飞。美国这是在用高油价压某些小国往自己队里站。想不到的是，利比亚人出来说了句大实话，把天捅破了。当年卡扎菲可是
在美国人面前认了栽的。今天，在布什最需要有人向自己投诚的时候，卡扎菲玩这一手可有点不地道，当心美国炸弹哟。

    一则国内新闻：在20日召开的国务院抗震救灾会议上，总理温家宝更拍板将早先敲定的7月10日前完成 25万套简易房的建设任务，再提前10天。

    【金鸿评论】创造机会，抓住机会。肃贪的最佳时机，打击不作为干部的最佳时机。全面整风！

    23日更新：叙利亚外长穆阿利姆二十一日表示，在土耳其居中协调的间接谈判中，大马士革方面已获得以色列从戈兰高地撤退至一九六七年六月四日分界
线的承诺。而以色列则要求叙利亚全面放弃对黎巴嫩真主党和巴勒斯坦伊斯兰抵抗运动(哈马斯)的支援，并与伊朗保持距离。美国华盛顿大学中东问题专家杜
里.拉莫斯在接受记者采访时称，叙利亚虽然向以色列做出让步，但毕竟获得了戈兰高地这块被以色列事实占领的领土。而对于伊朗而言，该国在中东的利益
无疑将严重受损，这不仅表现在伊朗少了一个对抗以色列的伙伴，还意味着伊朗与叙利亚联合阵线的瓦解。

    据以色列一家报纸21日报道，以总理埃胡德·奥尔默特建议美国海军封锁伊朗海岸线，迫使伊朗放弃核计划。

    【金鸿评论】美国又有砖家出来编故事了。在他们眼里，全世界的人都是傻子，他们说什么别人信什么。如果伊朗叙利亚联盟这么容易瓦解，那什叶派早
就被美国人摆平了。还没等叙利亚人出来辟谣呢，奥尔默特就不打自招了——在这档口上，如果叙利亚真的被招安了，美以现在最应该做的是巩固招安叙利亚的
成果，而不是对伊朗打草惊蛇。这等小小离间计也在大国斗争中使用，真是让人笑掉大牙。当然，看来美以实在没招可用了。除了那一招不太管用的招之外：

    美国能源部长塞缪尔·博德曼２２日说，美国政府不会动用战略石油储备平抑油价，称建立战略石油储备的目的是应对紧急需要，而不是影响价格。 
    【金鸿评论】油价怎么飞起来的美国人最清楚，没有人鼓着腮帮子吹，牛能上天？在这个时候说什么不会采取措施平抑油价是假，拿“应对紧急需要”吓唬
逊尼派才是真的——真有在中东走了火，石油战略储备的“应对紧急需要”的作用才会突显出来。

    其实，这又何必呢？美国在中东还有什么本事可以使？如果真有招没用的话，何至于选一个黎巴嫩总统都得向叙利亚让那么大的步？俗话说的好，打死犟
嘴的，淹死会水的，布什老兄你就扑腾吧。我们有的是时间站在岸上看。

    29日更新：近日，美国海军和空军相继在太平洋地区试射了最先进的洲际导弹，以提高对西太平洋沿岸中俄等国的威慑。

    【金鸿评论】美国打导弹的大背景是俄罗斯放风“印度、蒙古、伊朗、阿富汗、巴基斯坦可能将加入上海合作组织”，所以说美国这是在威慑中俄也没什么
错。其实美国的动作完全是被逼的：胡主席访日成功的拉住了日本，韩国的李明博又被中国扇得晕头转向，眼看着自己在东亚的两个支点即将失控；俄罗斯在
格鲁吉亚连连出手，搞得东欧也不稳定；叙利亚还没震住，伊朗、真主党和哈马斯倒是越闹越精神。权衡之下，不得不出手。

    美国动作之后，三方面开始动作：

    1、以色列就开始对叙利亚软硬兼施。甚至一度从美国砖家嘴里传出了伊朗叙利亚联盟要破裂的消息，不过，在27日伊朗国防部长纳贾尔与叙利亚国防部
长图尔克马尼签署了一份“扩大两国在军事领域的合作”的谅解备忘录却让那位美国砖家下巴脱臼。

    2、美国在巴基斯坦通道上加大了活动力度，谢里夫派有高官被刺，作为暗示性的反击手段，穆沙拉夫放松了对受到软禁的“核弹之父”卡迪尔汗的行动限
制。如果美国真把穆沙拉夫逼急了眼，伊朗也许很快就会造出和巴基斯坦一模一样的核弹来。其实美国也很清楚，在巴基斯坦通道上小打小闹可以，折腾大了
肯定自己倒霉，打个不太好听比方：巴铁就是一个美女，美国流氓上去摸两把我们可能只瞪他一眼，但如果他敢脱裤子，我们一定把他阉了！前年不就是因为
闹得太大直接导致的朝鲜核爆吗？之后就是在东北亚开始被边缘化。这次要是再闹大了，真不知道美国又会赔上点什么。所有人都应该记住前几天外交部副部
长王毅说过的那句话：“请巴基斯坦人民相信，在巴方需要帮助时，中国人民也将永远与巴基斯坦人民站在一起”

    3、格鲁吉亚更是拿着被击落的无人驾驶侦察机说事，格鲁吉亚，抗议亲美总统萨卡什维利由此招来的直拉反击就是在26日有5万名反对派支持者在首都第
比利斯示威，示威者们指责选举舞弊，要求重选。俄罗斯外交部长拉夫罗夫更是“不失时机的”说希望“与格鲁吉亚发展友好关系”——这哪是与格鲁吉亚发展友好
关系，这分明是在警告萨卡什维利“保位要紧”！

    几条战线都没有出现理想的局面，亲美的李明博访华还有什么底气？更何况北京本身就没打算再给李明博面子。就在他访华当天，一艘朝鲜巡逻艇闯入韩
国海域，这艘小艇来干什么的恐怕李明博心里更清楚——与其说这是军事警告，不如说这是政治警告。有了这一闷棒，李明博访华怎么会不出成果？当然了，有
朋友嫌李明博不给我们胡主席开车，我劝那些朋友还是省省吧，李明博要给我们主席开车得先考个中国的驾照才行。

    北京在东线收网的同时，在西线也加大了力度。“风云三号”成功发射，这是一个颗气象卫星，不过据说它还能监测海洋 ——能不能监视波斯湾并传输某些
数据呢？我就不得而知了。

    伊朗叙利联盟进一步巩固之后，哈梅内伊说 “哈马斯应该继续用武力打击以色列、只有武装斗争才能使巴勒斯坦获得解放”意思就非常明显了——替中国在
中东和平进程上要求分权，只要哈马斯继续武装斗争，法塔赫的阿巴斯和以色列就不可能达成任何让阿盟满意的协议。当然，接下来阿巴斯的日子更不好过。

    最后看一条油价方面的消息：英国首相布朗警告，全球正面临一场石油冲击；世界各国如果不协调与合作，将难以缓解油价飙涨的问题。

    【金鸿评论】要叫我看，布朗的警告太过激了，想解决高油价还不容易？不用美元结算不就做到了？
