# -*- org -*-

# Time-stamp: <2011-08-04 18:26:03 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 【金鸿95】中国房地产行业发展趋势

  [2008-06-05 11:50:23]

  
    97年东南亚金融危机之后，中国经济拉不动了，为了扭转颓势，当时的中央政府就用了两招拉动经济：一是把汽车做成支柱产业，让有钱人买车；二是教
育、医疗、住房改革，市场化，逼老百姓消费。站在纯经济的角度看，是可以的，老百姓不花钱不行了，不管是富人还是穷人。但是，这两招都是败笔：一、
汽车产业做支柱是发达国家都不敢做的，除了美国。一来是石油消耗太大，二来占地太多，这在十年后中国的汽车业发展起来后也表现了出来——堵。所以，北
京搞单双号了，深圳也限车了，上海的车牌号更是贵的要死，没办法，车与人争地的结果。当然，这也逼着我们胡主席满世界的抢石油，没办法，石油是汽车
的口粮。这一点以后是要改的，但现在还动不了。二、三大市场化的结果中国老百姓背上了新三坐大山。胡温上台后，重新往回改。到今天，教改医改基本改
回去了，最麻烦的就是房地产。

    搞三改的目的是让穷人花钱消费而不是继续把钱存在银行里——没有消费怎么拉动经济？但实际上，中国当时不具备把房地产做成支柱的条件。因为当时中
国的房地产行业里的企业普遍规模太小，远不成气候。可是，当时“不惜一切代价做了”。“不惜一切代价”的结果是什么呢？在今天中国的房地产行业，设计图
纸的，是设计院；搞建设的，是建筑公司；监督质量的，是监理公司；卖房子的，是房地产代理公司；搞服务的，是物业管理公司。给买房人提供贷款的，是
商业银行。开发商是干什么的？开发商就是个壳，一个包住上面六家的壳；开发商就是找找人打打关系盖盖章的，行贿不行贿就说不准了。当然，开发商变成
了空壳，主要是因为97年做支柱的时候根本不具备条件，是拔苗助长的结果。

    房价之所以能高涨，原因很多。第一，那个美国老太太的故事忽悠的结果（消费信贷的对人民收入的强行超前透支）。这个故事是这样的：一个美国的老
太太20岁的时候开始按揭买房子，等到60岁的时候房子终于属于她了，那么老太太已经在这个房子里已经住了40年。一个中国的老太太20岁开始赚钱，等到60
岁终于有足够的钱去买房子，不过她按照她的年纪也住不了几年就要向马克思去报到了。是贷款好呢还是现款好呢？当然是贷款。但是，贷款买房的负作用有
没有考虑过呢？如果不允许银行按揭、全部现款买房，既使在北京上海，超过80万一套的房子也很难卖得动。但是，现在一套房子能卖200万，为什么？因为
首付只有40万！他们能买的起，是因为付的起首付。所以，房价能从1000元涨上去，靠的就是这是基础。如果没有消费信贷，绝对没有今天的高房价。现在北
京上海等一线城市的房价虽然高，但首付只有二成，剩下的钱是按月还的，所以，想买房子的人只要付的起首付，月收入在支付了月供之后还能活得下去，他
们就会买房——绝大多数的买房人能掏得出的购房款，不会比首付款多多少的。当然，如果允许买房首付降到一成，贷款年限延长到40年，房价还会疯涨。

    有了消费信贷这个基础，再加上中国人多地少和开发商实力有限造成的商品房供应短缺，让房价出现了上涨的趋势，这时，出于套利的考虑，以温州炒房
团为代表的炒家们才大举炒房。

    当然，房价上涨还有一个原因，就是地价上涨了。地价上涨之后建房成本也就跟着涨了起来。地价为什么会涨？是各地方政府经营城市的结果。当然，各
地方政府这么做，也不能只怪他们，他们也没办法，为什么呢？因为有了分税制。分税之制前，税是统一收到，可分税之后。一部分税种地方收，收了地方自
己花。一部分税种中央收，收了入中央财政。从表面看，没什么错。但出了个不大不小的问题，好税种，容易收的，增长性好的税种，全归中央了。地方得到
的税种，都是不好的。各地方政府一看，妈呀，以后的日子难过了！地方上也得过呀，他们也有各种支出呀，他们也得养活一大群人呀，他们中有人还想贪污
呢！怎么办？自已动手，丰衣足食。为什么中国的高速公路收费路量世界第一？这就是原因。现在好了，房地产成支柱了，跟风赚点钱不算错吧？炒地皮！拍
卖！要知道，在中国经济最好的上海，地方财政都有1/3是靠卖地呀。其他的城市，可想而知。

    媒体和专家学者们大造声势一致喊涨就更不用说了，他们知道谁养的他们，当然知道该为谁说话了。所以全国只有一个声音：房价要涨，还涨，还继续涨
！结果有一天，老百姓不敢花钱了！为什么？得留钱买房子呀。所以，中国消费不到GDP的40%，出口却那么高。所以，国际上只要有点什么风吹草动，中国经
济就吃不了兜着走——经济外向性太强的结果。胡温政府虽然在改了，不过想短期内改过来也不容易，人民币一升，把那些血汗工厂全关了，这是用经济手段调
整结构，引导产业升级。

    房价持续在高位运行，也给国民经济的平稳运行带来了巨大的风险。它不仅仅掏空了广大买房的老百姓的钱包，还让他们中的许多人背上了大额的债务，
一旦因为房价的持续走高将供求链拉断导致房价暴跌，将会给他们的生活带来巨大的负担。这里面的道理很简单：房价持续走高，终有一天会高到老百姓买不
起房的地步，那时，原本指望用高房价赚取更多利润的开发商为了回拢资金必然降价。当然，在降价以前开发商们会有一段“有价无市”的坚持高价不降的时期
，但是，一旦被日益绷紧的资金链逼到无力维持局面的时候，降价销售将成为必然选择。但是，在房价掉头下跌时，出于“买涨不买跌”心理的支配，持币等待
的买房人不但不会加入购买者的行列反而会“再等等看看房价会不会再跌的低一点”（他们怕自己买亏了）。在这样的情况下，出现价格暴降出售房产以回拢资
金的情况是很正常的，这种情况与股市暴跌时股民恐慌性抛盘割肉平仓是同样的道理。一旦房价在这样的情况下被打回原形，降价前买房的人将平添巨大的包
袱（举个例子，假如某人在房价下跌前花120万买房产一套，首付50万贷款70万，可房价暴跌后他的房产只值60万，此时，他即使马上将房产卖出以得款60万
归还银行贷款也不够，还得背10万元的债务。这样在房子的一买一卖中自己前期积累的财富就全部失去了）。这样一来，大量“负翁”的出现会带来严重的社会
问题。

    房地产是资本密集型产业，如果房价持续高涨最终把供求链拉断了，接下来房地产开发企业的资金链也会马上崩断。而中国的房地产开发企业大都在银行
有巨额贷款，如此一来，又会为银行增加大批的呆坏帐。

房价的持续走高还会引发大规模炒房现象的出现，从而加重房地产行业的“过度需求”。炒房者大量屯房不是为了居住而是为了低买高卖以赢利，但由于他们的
大量屯房导致本已不足的供应量更显捉襟见肘，从而刺激房地产开发商更大规模的开发，造成房地产业的“过度繁荣”——房地产企业赚得的利润会短时性（十年
内）的远超过其他行业。在利润的驱使下，大量其他行业的优秀企业也有可能放弃对本行业的投资而转向房地产开发，从而造成房地产业的畸形发展。其实，
任何一个行业要想正常的发展，都不能有不合理的超高利润，因为超高利润的存在会吸引过多的投资，进而毁掉这个行业。现在，海尔、联想不都高调在房地
产行业里打拼吗？这样的示范效应会造成什么结果？大量外行的企业涌入房地产行业的结果只能是让无数的房地产企业在竞争中破产，这还是在没有政策干预
房价的情况下。所以，让房价回归理性对所有人都有利，包括开发商们。

    所以，房价持续走高会对国民经济的平稳运行带来极大的隐患。但是，国民经济的运行风险还不仅仅在于房地产业。随着国外热钱的大量流入造成的通货
膨胀的加剧和“金融创新”的发展，国民经济运行中的金融风险也会增加。如果房价高位运行的风险和金融风险叠加起来，危险更大。所以，出于挤出经济运行
风险的考虑，调控房价也是必然。

    不过，因为高房价已经绑架了中国经济，所以调整起来非常困难：如果强行打压房价，中国的房地产企业就会全部完蛋，各大商业银行也得背上巨额债务
，中国的贷款买房者也将背上巨额的债务，中国经济是撑不住的，中国的社会稳定也是问题。所以现在只能慢慢调，稳稳的调。八年能全调整过来就很不错了
——八年后，人民收入高两倍（提高工资+多印钞票），房价基本保持在今天这个水平（或者略有提高）就可以了。当然了，如果真能这样的话，四年后的房价
就基本可以接受了。不过，房价超高的城市肯定会继续受到打压。
