# -*- org -*-

# Time-stamp: <2011-08-04 18:33:23 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 外电评我1966-1976年间科学技术发展

  [2008-11-01 19:52:20]

  
　　金鸿：真相是会吓死人的！
法国《世界报》载文：中国正在征服科学和技术
            　　
    【本刊讯】法《世界报》三日刊载多米尼科·韦尔格斯的一篇文章，题为《知识的长征，中华人民共和国正在征服科学和技术》。摘要如下：
    某些人感到惊奇的是，中华人民共和国能够如此迅速地制造了两颗铀弹，事实上，这要以不容忽视的工业实力，在上述方面相当先进的研究和建成同位素
分离工厂（法国还没有最后建成这种工厂）为前提的。
事实上，一个社会主义国家的政治工业结构可以使人就一个已确定的目标进行巨大的努力，如果政府当局决定这样做的话。
    显然，中国绝不会满足于外国提供给它的直接或间接的援助。它知道，它首先应当依靠自己。它的整个政策在于尽可能快地发展群众教育。培养技术人员
和工程师。
    在一九六○年，中国在研究和教育方面的投资总额还没有达到欧洲最工业化国家的水平。虽然人们还没有掌握比较最新的统计数字，但是中国可能在过去
的六年内已经部分地（虽不说是全部地）摆脱了它的落后状态。尽管这样，但是中国还远远落后于两大国家，而这两个大国的人口比它少得多。这就使人认为
，中国要提高到目前最强国家的水平应该要作出巨大的努力。
    尽管中国的预算相对地来说是低的，然而看来中国正在培养着一支不可忽视数量的专家队伍，它的数目要比法国目前的数目高得多，法国高等科技大学生
只有十三万人。而这种情况对各自居民的人数来说只能是一种正常的现象。
    但是，在访问过中国的西方科学家看来，中国在研究中心和在大学里进行的科学研究同工业化国家进行的研究相比是中等的水平。
    看来中国自从一九四九年以来很好地进行了两个运动：一方面，以向工人和农民群众证明科学和技术的好处并向他们表明采用（甚至是懂得）科学方法并
不是少数专家的事情的方法，教育和改变了他们的精神状态；另一方面，同时培养了一些具有高水平的科技人员，他们在没有外国援助（即使这种援助是必要
的）的情况下独自推动了科学技术的发展。目前中国仍然在这样做，以致于同时并举的这两种努力在相互配合，从而会使这个国家的科学终有一天不再纯粹是
为了民族利益，而会为国际利益服务。
            　　
            　                           　原载《参考消息》，出版日期:1966.03.11

中国完全能够自力发展必需的科学技术
            　　
    日本一评论家认为帝修犯了严重低估错误      　　
     【本刊讯】日本《潮》杂志五月号刊载军事评论家林克也写的一篇评论，摘要如下：
      最近国内外谈论的重点，集中在重视中国的核力量问题上。
      直到中国靠自力使核试验达到成功之前，全世界各国始终是过低估计了中国科学技术和工业水平可能发展到的最大限度。结果造成了对中国核武器的严
重估计错误。
      如果今后仍然重复这种估计错误，就意味着以美国为首的资本主义世界体系的战略、策略出了大破绽。因为这是对是否拥有实战用核弹头、运载工具、
核潜艇和它的实力的估计错误。美国比什么都更怕这一点。
      中国表明它拥有“以一当十”的能力。而且可以证明，中国将完全可能靠自力发展建设一切所必需的科学技术。这绝不是主观的称赞。如果不老实地承认
并理解这个事实，那么，今后就谈不上有谈论中国问题的资格。
      应该研究一下，中国的原子弹工厂是什么样的，中国的热核工业具有怎样的内容呢？重要的事实是：第一，在那样落后的中国革命创业仅仅只有十五年
之中；第二，在以美国为主力的西方各国的军事体系包围之中；第三，在中苏对立以及苏联制造的一切障碍之中；第四，在几千年来少有的自然大灾害之中；
以自己的力量建立了热核工业体系的原因和条件到底是怎样的呢？要是运用一个集中的表达方法，就是要揭开这样一个谜：现代中国在上述四大困难之中，怎
样以自力完成了现代最高的综合的生产体系呢？
    　象已经指出过的那样，核工业不是两手空空在一夜之间就可以实现的。
      第一必须具有一切必需的工业生产体系和技术与科学研究设备。只有有了这种作为基础的基层结构，才能制造核武器和火箭。
      第二是人。从根本上来说，这应该是占第一位的问题。要在最短期间之内培养出成千名的具有高度知识水平的科学家，并且使他们认清事物的本质，发
挥他们的奔放的能力，是这样的政治和思想的问题。
      西方不用说，就连赫鲁晓夫当总理时的苏联，对中国制造核武器的能力犯了根本性的估计错误，就是由于在上述两点上判断错误所造成的。
      现在，世界上能够制造铀二三五的国家，除了美英苏三国之外，只有中国。法国从一九六七年开始生产，这以前只是处于试车阶段。
      议论中国的原子弹工厂（在哪里）实在是没有多大意义，因为说不定每天每天都有新的增加。
      倒不如说中国原子弹工厂的真实所在地是扩展在中国的整个地区。
      不只是核武器，整个的核工业，依靠具有大规模现代工业生产体系和高度科学技术水平。当代中国的现代工业联合企业是数也数不清的。
     从一九五九年到一九六三年，袭击中国的是四大困难，真可说是内忧外患的时期，能够克服这个危机，自不用说是中国最高领导人、同时就是中层以下
的基层党员也带头面对困难解决困难的结果。
            　　
            　　                                  原载《参考消息》，出版日期:1966.05.10
            　　

香港各界人士欢呼祖国热核爆炸成功
            　　
     说这是毛泽东思想的胜利，社会主义的优越性
      【新华社香港十日电】香港工商界、教育界知名人士今晨欢呼中国成功地进行了核爆炸。香港《新晚报》今天报道，中华总商会会长高卓雄说，中国这
次爆炸氢弹，比以前试爆成功的原子弹又进了一步，我国有了这么强大的核武器，国防更加巩固，对世界和平更有保障。这是我国社会主义的优越性，毛泽东
思想的胜利。
      该会副会长王宽诚说，我们中国过去是既贫困又落后的国家，在解放后，短短十几年却取得这么巨大的成就，也体现到人民的力量是无穷的法宝，证明
反对帝国主义侵略，一切要依靠人民力量。同是一个中国，有了好的社会制度，有了毛泽东思想指导，可以创造一切。当此帝国主义对我们不断进行核讹诈、
美苏勾结对付我们的情势下，我国热核爆炸成功，对世界爱好和平的人民具有重大的意义，这是对美帝核讹诈、核垄断的一个有力的反击，对全世界被压迫的
人民无疑是福音。
      汉华中学校长黄建立说：“这是我国科学技术的重大成就，也是对保卫世界和平的重大贡献，是一件大大的好事。这说明了中国人民有了毛泽东思想的
领导才有今日的成功。我们有了核武器，在意义上和别的国家有所不同。我们的氢弹是对核讹诈的有力回击。”
     中华中学校长黄祖芬说：“祖国的成就，海外华侨和港澳同胞感到鼓舞，我们要做对祖国有好处的事情，热爱祖国。”
     香岛中学校长李述龙说，祖国在不到两年间，进行了三次成功的核爆，一次比一次大大提高，很多方面，已经赶上和超过世界先进的科学水平，这是毛
泽东思想的伟大胜利，用毛泽东思想武装起来的中国人民是无往而不利和绝无不胜的。

            　　
            　　                                  原载《参考消息》，出版日期:1966.05.12

日本科学技术厅承认：我核爆炸强大粒子比美苏氢弹试验时多
            　　
    【共同社东京十二日电】政府十二日上午召集厚生、运输、自治、农林、防卫、科学技术等有关省厅的阁员和事务次官，就中国核试验的放射能，讨论当
前的对策。会议还决定在当天下午在首相官邸召开新设的放射能对策本部的会议。      　　
    在这一天的会议上，科学技术厅提醒注意说，这次试验的特点是：“强大粒子”在试验后很短期间就散落到日本；比起一九六一年、一九六二年美苏两国的
氢弹试验，数目较多。
     另外，据在这一天的会议上提出的报告，由于这次试验，迄今检查出来的最大的达到五十一万单位。     　　
    【共同社东京十二日电】全国各地的气象台、卫生研究所、大学已经检出中国第三次核试验的放射能。内阁放射能对策本部十一日下午五时半综合地发表
了到目前为止的测定结果。根据这项测定结果，在全国各地已经测出相当高的放射能，秋田、大阪、米子、仙台、东京各地气象台检出了比平时大五十倍到一
百二十倍的放射能。
            　　
                                      原载《参考消息》，出版日期:1966.05.14

日本经济友好代表团访华后说：中国文化革命是促进生产大发展的动力
            　　
   【本刊讯】香港《文汇报》二十二日报道：由团长国分胜范率领的日本国际贸易促进协会访华经济友好代表团，结束了在我国的访问后，前天由穗抵港。
     该团秘书长田中修二郎，团员倭周藏、重松良树，昨天在旅店接见本报记者时，热烈赞扬中国人民正在进行的无产阶级文化大革命。他们指出：当前这
场文化大革命，是中国人民活学活用毛主席著作，促进人的思想革命化的大革命，是防修、反修的根本措施，也确是最大最好的战备。他们并驳斥西方国家和
日本若干报纸对于红卫兵的造谣和诬蔑，指出红卫兵破四旧、立四新的革命行动，已成为推进中国社会生产力发展的一个强大的推动力量。
    田中修二郎说，他们通过这次在各地的参观，确实看到了中国人民自建国十七年来，克服了种种困难和障碍，进行社会主义建设，工农业取得很大的成就
，中国的科学技术进步很快，人民生活很安定。他们在所访问过的城市、农村、工厂、矿山和研究所，都看到无产阶级文化大革命正在大规模地深入开展的实
际情况。中国人民都在学习毛泽东主席的著作，在毛泽东思想指引下，为建设社会主义而奋勇前进。当前的文化大革命运动，正成为推动生产、技术、文化等
所有领域大发展的动力。他们确认，无产阶级文化大革命是中国社会主义革命的新阶段。拥有广阔土地和七亿人口的中国，是有广阔发展前途的。
     倭周藏说，他确认中国人民已精神总动员，做好一切戒备，随时准备粉碎美国及其帮凶的任何突然进攻。他完全相信，中国有足够力量击败企图侵犯中
国的任何方面的敌人。
     他赞扬中国人民根据自力更生方针，在工业方面的飞跃发展，例如大庆的石油工业的兴起。他说，中国本身已能大量生产自己设计的各种机械和仪器，
为促进工农业的更快更好的发展，并适应七亿人口的广大需要，目前仍由国外进口质量较高的机械和仪器。他并认为中国人民有无穷的潜力，在毛泽东思想的
光辉照耀下，将大大地发挥出来。
      重松良树说，他们在中国各地看到的红卫兵，都很有纪律，一切行动按照预定计划和步骤进行，并且严守秩序。他指出，中国社会并没有像一些报纸所
披露的纷乱情况出现。他说，有些人对红卫兵表现出很大的兴趣，争相评论，但是这些人对红卫兵全无正确的认识。
      谈到中日贸易关系的展望时，他们表示，目前的日中贸易情况，是令人不满意的。但是，佐藤政府的敌视中国政策是不得人心的，对日中贸易的种种人
为障碍终必有打破的一天。发展日中两国人民之间的友好和贸易关系，是两国人民的共同愿望，是任何力量所阻挡不了的。为了保卫和发展日中友好和贸易，
日本国际贸易促进协会决心和日本广大人民一道，坚决同一切阻碍和破坏势力进行不断的斗争。
            　　

    【日本新闻社东京二十二日电】关于中国红卫兵运动，国分说，“我认为，这个运动将在今后的国家建设中起很大的作用。”
    国分说，“当我们看到中国真正的情况时，我们发现我们在从日本动身前对文化大革命的看法显然不符合现实。我们得到的深刻的印象是，红卫兵运动在
以极其井然有序的方式进行。”
    他指出，中国的经济显然很稳定，中国在以坚定的意志执行第三个五年计划。
            　　
            　　

法新社说这次核导弹试验成功证明中国在尖端工业方面取得辉煌成就
            　　
    【法新社巴黎二十七日电】中国的第四次核爆炸证明人民中国不仅在原子方面，而且一般地说在尖端工业方面，取得了辉煌成就。事实上，制造和设计原
子弹和导弹的要求的材料（裂变原料、特种合金、耐火器材等）、工业生产过程、电子仪器，都是只有高度工业化的国家才能实现的。人民中国既会制造原子
弹，又会制造导弹，今天它已作为一个核国家出现，只不过还受到原子弹和核弹头，以及可以发射这些弹头的运载工具的数量的限制。
     第四次试验证明，中国在科学、技术和军事方面正在逐步升级。
            　　
            　　            　　
                                                  　原载《参考消息》，出版日期:1966.10.29

杨振宁在新加坡对记者发表谈话时说：中国科学界对研究工作已达到世界先进水平
            　　
世界科学对中国制成人造胰岛素大感惊异
            　　
    【本刊讯】据新加坡报纸报道，在美国居留的中国科学工作者杨振宁，二十日到新加坡作了三天的私人访问，参观了“南洋大学”，并会见了在西南联大时
的师友。
     杨振宁是在最近应邀出席了澳大利亚国家科学院的科学会议之后，经雅加达抵新加坡的。他已于二十三日离开新加坡续程前往以色列参加原子与物理科
学会议。
    杨振宁在对报纸记者发表谈话时说，相信再过十年，中国在核物理学以及其他科学方面，一定有惊人的发展。
    他说，世界许多先进科学家和研究机构，都在拼命研究人造胰岛素，可是都没有成功。而中国的科学工作者在两年前就制造出来了。这是惊人的，它使世
界科学界大感惊异。从这里可以看出，中国的科学研究工作，已达到了世界的先进水平。
    杨振宁谈到中国最近十年在核物理学的成就时，认为在量方面有很大的进步。他说，这些年来，他阅读到许多有关中国科学方面的杂志，显示了中国在训
练人才方面，很有成就。
    他说，至于在质方面，中国目前还没有达到世界最先进的水准，不能跟先进的国家比较。不过，基于量方面的成就，在质方面追上最先进的水平，只是时
间问题而已。
     杨振宁认为，在物理学方面，目前世界上最有成就的国家是美国，第二是苏联，第三还轮不到中国。他说，据统计，现在中国留美科学家约有三千至六
千人。
     当记者询问是否有意返回中国时，杨振宁表示他没有前往中国的意思，至于将来是否有意回中国头，连他自己也没有想到这个问题。他又表示，他本人
不愿在报纸上就这个问题作任何谈论。
     据《南洋商报》报道，杨振宁曾对该报记者说，中国目前的“对外态度相当傲慢”。他否认中国曾通过他的父亲劝他返回中国大陆。
     据报道，杨振宁目前在美国长岛纽约大学高能物理研究院任职，已经加入了美籍。
            　　
                                           原载《参考消息》，出版日期:1967.02.26

英国库尔特·门德尔森博士谈访华观感：中国工业发展速度惊人
            　　
说中国将在本世纪末使世界其他国家相形失色
            　　
     【本刊讯】英国《太阳报》三月四日以《中国的惊人的技术发展》为题，发表库尔特·门德尔森博士的另一篇访华观感，摘要如下：
      香港和东京的报纸记者喜欢自封为“中国问题观察家”。可是，这些人太过沉缅于等待发生内战了，所以观察不到我们时代的最重大的事件之一：一个无
比庞大的工业技术国家的兴起。
      中国如能保持目前的科学和工业发展速度，就将能在本世纪末使世界其他国家相形失色。
       它有可能在八十年代同西方和苏俄并驾齐驱。
       我最初在一九六○年参观了中国的实验室和工厂。在一九五○年时，曾经是五十年的内战和日本侵略遗留下来的一片混乱和破坏状态。
      从俄国购买的第一批工厂在一九六○年正开始成立起来，但是苏联专家撤走了，工作往往只完成了一半。
       两年以后，尽管俄国人撤走和两年严重歉收，还是取得了显著的进展。
       我参观了一个为制造工作母机生产精密磨具的大工厂，在各大学和工学院里，也获得了明显的进步。
       我通过我的科学界同行，会见了毛泽东和陈毅外长，他们两人都强调中国需要迅速发展科学技术。
       在文化革命的动荡中，这个决心也没有被忘记。
       在红卫兵行进和扩音器哇啦哇啦广播时，各工厂仍在忙碌地开工，生产到处在增加。
       中国工业产品在质量和品种两方面都是很突出的。他们已经有远洋轮船、有空气调节设备的内燃机火车、小汽车、公共汽车、燃气轮机和发电机——全
都是中国制造的。
       甚至更加使人印象深刻的是那些非常先进的产品，如电子显微镜、精密天平、照相机、计算机和各种电子、光学和医学设备。
       事实上，现在中国不能制造的东西极少，而且它正开始以惊人的速度生产。
       在科学院的实验室里，给我看了许多非常先进的设备——例如，在液体氦中使用的超导性磁线圈。
       我的中国同行强调说，他们的成就仍然远远落后于西方国家，但是毫无疑问，他们在短短的几年里，取得了难以令人相信的进展。
      有七亿高度技巧和智慧的人民为基础，中国的技术一旦充分发挥出来，可以与世界上任何一个国家相匹敌。
      可是，还有一个疑问，一个有技术的国家，最重要的产品是科学家和工程师。文化革命从去年夏天起就把中国的大学关了门。
      如果允许文化革命在一九六七年的大部分时间里继续进行，中国可能蒙受极大的损失，不是由于政治上的不统一，而是由于技术训练的中断。
            　　
            　　                              原载《参考消息》，出版日期:1967.03.07
