# -*- org -*-

# Time-stamp: <2011-08-04 18:34:19 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent


* 金鸿时局评论（2008/11/05）

  [2008-11-05 09:39:39]

  
    1、２００８年１１月４日１４时，海峡两岸关系协会会长陈云林与台湾海峡交流基金会董事长江丙坤签署四项协议两岸“三通”框架成形 
　　看一则8日的消息：
    【简评】这也不算什么爆炸性的消息了。下面我在3月4日开始写的＜【金鸿评论】入联公投局势追踪＞一文中的一部分内容：

　　＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊

　　朝鲜外务省发言人8日发表谈话，谴责台湾当局试图进行“入联公投”，并表示坚决反对台湾以任何形式加入联合国。朝鲜中央通讯社援引这位发言人的话
报道说，台湾当局将举行的“入联公投”是恶化台湾海峡和东北亚地区局势的严重行为。朝鲜政府一贯支持中国党和政府建立在一个中国、“一国两制”基础上的
统一政策，今后也将继续支持这一政策。
    上面分析反入联公投的国家时，没有提到朝鲜，因为朝鲜跟中国是一体的（巴基斯坦也是）。中国的朝核牌本身就是冲着美国的台独牌来的，朝鲜这次出
来反公投、支持一国两制本身就是在提前向美国开价——想要朝核出现一点实质性的、可以给美国脸上增点光的突破的话，就用“三通”来做交换吧——不先“三通”
怎么实现一国两制？
    上月底，黑妹赖斯亲自飞了一趟东亚（为核何而），甚至连“绑架问题不会影响将朝鲜从援恐名单中删除”的话都放出来了（当然美国也有威胁日本的意思
在里面），还没有换来六方会谈的复会。朝鲜在等什么呢？大米和重油吗？当然不是，是入联公投熄火。很快，我们就可以看到中国和美国一起玩一把“口头
对口头、行动对行动”的游戏——只要“台海三通”有突破，朝鲜弃核肯定有实质性的进展。如果谁想耍滑头，大家手里都有一把乱牌，愿意较较劲就请便好了。
入联公投的局势跟踪到此为止了。

　　＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊

　　几个月下来，局势的发展基本和当初预想的差不多。为了让朝鲜在东亚老实一点，美国人是丢尽了脸面、赔足了笑脸，最后还是不得不出卖了日本人，在
绑架问题没有任何进展的情况下，把朝鲜从支恐名单里删除了。当然，这也不是能淘换到朝鲜听话的筹码，真正能让金正日大爷有心情安静看球赛的是台湾与
大陆走向和平统一，三通是第一步。下一个要突破的目标是西线。

　　2、 受到美元汇率下滑、欧佩克减产等因素影响，国际原油期货价格４日出现强劲回升，纽约市场油价涨至每桶７０美元之上。

    【简评】看来这年头真是软的怕硬的，硬的怕不要命的。老毛子昨天刚刚拉开架式要跟美国人拼命，布什和华尔街就小腿肚子转筋了。

    为了收拾俄罗斯，把油价往死里砸，砸的北极熊嗷嗷叫，一急眼，熊就把非洲强人卡扎菲拖了出来，要支持利比亚玩核，这还了得？美国人一夜之间就把
原油价格拉了个涨停板。真他妈的没骨气！卡扎菲有了原子弹又如何？哪比得了你们美国人？盖茨不是刚说了中俄的核武器怎么发展都不是美国人的对手吗？
连中俄都不是对手，还怕一个小国穷国？

    3、欧盟轮值主席国法国外长库什内3日在法国南方港口城市马赛表示，欧盟将在国际重大问题上成为美国的“平等伙伴”，寻求与美建立多边主义平等协商
基础上的新型伙伴关系。

    以色列外交部长利夫尼3日表示，她将在即将举行的中东问题有关四方会议上声明，以政府不会签署任何临时性和平协议。

    【简评】欧盟说：大哥，咱俩在中东二一添作五怎么样？

    美国说：哪凉快哪歇着去，再讨价还价就滚出中东！还想搞地中海联盟，做梦！

    4、交部发言人秦刚就中国政府5日发表《中国对拉丁美洲和加勒比政策文件》发表谈话。秦刚介绍说，《中国对拉丁美洲和加勒比政策文件》是中国政府
制定的首份对该地区政策文件。《文件》阐述了中国对拉美政策的总体目标，全面规划了今后一个时期中拉各领域的友好合作。《文件》提出，中国政府从战
略高度看待同拉美和加勒比地区的关系，致力于同该地区建立和发展平等互利、共同发展的全面合作伙伴关系。

     【简评】秦刚说：门罗主义完蛋了，我们现在要抄起家伙到敌人后方去！

    5、外交部发言人秦刚４日宣布：应外交部长杨洁篪邀请，阿拉伯埃及共和国外交部长艾哈迈德·阿里·阿布·盖特将于１１月５日至７日访华，并举行两国
外交部首轮战略对话。
    拉姆安拉11月4日消息，巴勒斯坦伊斯兰抵抗运动（哈马斯）在加沙地带的一位发言人伊哈卜·古赛因4日说，埃及当天开放了与加沙地带交界的拉法口岸
。

    【简评】把埃及全面拉过来的那一天，就是我们主导中东和平进程的那一天！、

     前途是光明的，道路是曲折的，目标是现实的，动作是迅速的。
