# -*- org -*-

# Time-stamp: <2011-08-04 18:32:43 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent


* 金鸿时局评论（2008/10/30）

  [2008-10-30 21:07:04]


  
　　1、据韩联社报道,美国国务院助理国务卿希尔28日表示，除朝核六方会谈当事国外的其他国家也愿意代替日本对朝鲜进行能源援助。

    东京10月29日消息：正在日本访问的中央军委委员、中国人民解放军海军司令员吴胜利上将29日傍晚与日本防卫大臣浜田靖一在防卫省举行会谈。双方均
表示应加强两国海上力量间的交流。

　　【简评】哈哈，美国人居然威胁上小鬼子了。这也是没办法的事，前天马英九拿钓鱼岛石油资源说事，小日本愣是低着脑子不接茬子，让马英九硬是把双
簧演成了独角戏，美国人能不火？不过也是没办法的事，大国斗争不是靠发脾气解决问题的。老吴是反日派，能去一趟小日本很不容易，够给他们面子的了。

　　2、叙利亚周二(10月28日)呼吁联合国安理会采取行动，以防止再次发生类似上周末驻伊美军在叙利亚领土开展的攻击行动。在和记者交谈时，亚阿法利
拒绝评论他是否希望安理会对美国发表一份更能强烈表达抗议的谴责声明或一项决议。他只是说，这将取决于安理会主席（中国）决定采取什么样的行动。

　　据法新社10月30日报道，朝鲜30日谴责了美国对叙利亚村庄的袭击，称美国的行为“不可饶恕”、“灭绝人性”。

　　美国驻叙利亚大使馆在其网站上发表声明称，位于叙利亚首都大马士革的美国大使馆30日将暂时关闭。

　　【简评】中国人做事真他妈的含蓄！有话直说行不？

　　美国在叙利亚武力试探的结果很不理想，自己就成缩头乌龟了——开着大使馆多好？让叙利亚人狠狠的砸了，砸烂了美国人的财产、打伤了美国人之后，美
国再打叙利亚不就有理由了？真恶心人，好好的机会不利用。就这本事前几天炸人家的老百姓干嘛来着？伤天害理的东西！

　　3、据伊朗通讯社29日报道，伊朗前总统哈塔米说，德黑兰和华盛顿可以在本届美国总统大选后开始新的关系。

　　【简评】这有啥办法呀，伊拉克都要撤军了，怎么打伊朗？还开始新关系以后更难混。还是想办法和伊朗缓和一下关系，把欧盟扔一边去好把欧元打下去
。

　　4、中国总理温家宝和俄总理普京于近日举行会谈后，欧洲媒体对此多有评论，有的认为新的中俄关系已形成，称中俄是在建立一个 “反西方轴心”。不过
也有观点认为欧洲不用太担心，因为中俄关系竞争大于合作。

　　据英国广播公司BBC10月29日报道，该公司记者亲身赶赴格俄战争现场做出了“格鲁吉亚军队在俄格冲突中曾向平民开火”的报告。

　　英国商务大臣曼德尔森29日在莫斯科呼吁结束英俄政治争执。

　　【简评】务实的英国佬！还怕把你晾干了不成？

　　5、由于美联储降息的决定提振投资者信心，国际油价２９日强力回升，纽约市场油价暴涨超过７％，重回每桶６７美元之上。

　　6、当人们正在为席卷全球的金融风暴忧心忡忡时，美国有线电视新闻网（CNN）帮大家揪出了导致经济危机的元凶。该网站近日刊登了题为《金融危机罪
魁祸首》的文章，点评人则是CNN著名的新闻主播安德森·库珀。纵观安德森·库珀对“罪魁祸首”们的点评，基本上可概括为领取高薪、胡作非为、纵情市场、
死不认错几点。出人意料的是，被列为十大罪魁之首的竟然是YOU——普通的美国消费者。的确，美国人寅吃卯粮的消费习惯已被视为金融危机产生的基点。
