# -*- org -*-

# Time-stamp: <2011-08-04 18:30:11 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent


* 金鸿评论(2008/10/28)

  [2008-10-13 23:00:05]

  
    这一场金融危机最深层的原因，是美国人的消费思想：寅吃卯粮，借债消费。美国的储蓄率1984年为10.08%，此后不断下降，到2004年为时1.8%，到2005
年则变为-0.4％，2007年更降到了-1.7%。所以，表面上美国人的日子是繁花着锦烈火烹油，实际上他们的亏空大了，美国人欠了一屁股的债。
    而美国自上世纪八十年代出现双赤字以来，其自身创造物质财富的能量就开始严重下降了，换句话说，就是美国人自早就无法自给自足了。这样许多朋友
可能感觉奇怪：那为什么美国人这几十年一直过的让全世界都得红眼病呢？美国人的办法很简单，就是靠资本市场上的国债和各种金融创新手段(包括导致今
天全球金融体系濒临崩溃的CDO和CDS）来吸纳他国的储蓄。据统计，从2000年至2007年上半年，美国共吸纳外国储蓄5万亿美元。各国资金的大量流入压低了
美国长期贷款的收益率，这就刺激了美国资本市场的空前活跃，美国的金融泡沬得到了充分的膨胀，其表面形式就是资产增值（股市涨房市也涨）。同时，在
泡沬吹大的过程中，美国老百姓可以很容易的从资产增值中获得收益，这些收益又很快变成了美国人的消费资金。被金融泡沬迷晕了头的美国人则更大胆增加
负债来超前消费，从而刺激了美国经济的增长。但是，外国资金的流入终究是有穷尽的，美国人也不可能永无休止的借债下去。债务多到一定程度总有把美国
人压垮的那一天，美国的金融泡沬吹到一定程度也总有吹破的那一天。今天，次贷危机全面暴发了，就是这一天来到了。
    当然，如果没有金融衍生工具的放大作用，这次危机的规模也不会太大，但是，有了金融衍生工具的强大的杠杆效应之后，这次危机几乎成了席卷世界的
金融风暴。目前，美欧央行的救市行动是治标不治本的，因为它无法从根本上解决美国本身的巨额债务问题。但是对中国而言，这次金融危机并不是一件太坏
的事情。
    不妨从以下几个角度分析一下：首先，我们肯定是有损失的，所以它是一件坏事。由于金融危机的影响，我们的出口制造业肯定受影响，同时，由于我们
投资了一部分相关的债券，也会造成损失，但是，相对于美国而言，我们这点损失是小的。其次，借着这个机会，我们可以调整经济运行方式，变出口拉动型
为内需拉动型，不再充当世界奶牛，而要变为真正的火车头，让我们的人民享受经济发展的成果，而不是全部送到国外去。第三，也是最重要的，美国病入膏
肓，正好是我们上位的好时候。但是，现在还不是眼看着美国迅速崩溃的时候，因为我们的实力还是相对有限的，如果美国一下子就倒了，在全球范围内造成
的下政治权力真空和金融权力真空太大，一时半会我们自己填不了，只会让别人沾了大光，所以，现在最好的办法就是让美国慢慢的倒下，在此过程中，我们
尽可能多的占领美国人让出的地盘，不管是政治军事层面上的，还是经济金融层面上的。从这个意义上讲，对美国，我们要拉一把，但是，绝对要讲条件。条
件之一，就是要美国承认中国在东亚的主导地位，表现形式就是不再阻阻碍东亚经济一体化的进展，美国宣布将朝鲜从支持恐怖主义国家名单中除名就是一个
具体的动作。只有美国有了这个动作，中国才有可能参与购买美国国债。
美国把朝鲜从支恐名单中删除并没有招来日本的强烈反应，反而引出了日本韩国再提海底隧道方案的事情，很显然，日本看到了美利坚的日薄西山，再加上自
己也有求于中国，所以，回归东亚经济一体化是日本人不得不低头的事情。至于韩国为什么在挖隧道问题上这么积极也也在情理之中，拉个小日本进来平衡一
下中国经济在东亚经济圈的影响，以防自己为中国压死。
    这一场国际斗争，实际上是中俄欧美四方争夺全球领袖地位的斗争。今天的美国，已不在是布雷顿森林体系初建时的那个富甲天下的美国了。美国这个曾
经的世界霸主，被几十年的无度的超前消费和无餍足的滥用美元信誉彻底拖垮了身子，又被次贷危机的火种引起的熊熊烈火烧光了所有家产，让美国走到了国
家破产的边缘。失去了本国经济的支撑，美元的霸主地位也就岌岌可危了。
    多年来，俄罗斯与美国一直是死对头，相互间经济上的依赖度非常小，它不象中国和欧盟，与美国之间的经贸往来频繁、联系紧密，美元猛得趴下了，自
己也受冲击非常大，美元霸权的突然倒台对俄罗斯的冲击是非常有限的。在这样的背景下，俄罗斯率先发起了对美元霸权的冲击。俄罗斯的手段就是想方设法
解构美元与石油之间的联系----只要全世界的石油交易不再用美元结算了，美元霸权也就结束了。俄罗斯这一手对美国而言是致命的，所以，招来了美国的本
能反击，一个反击手段就是操纵油价下跌，因为如果失去了高油价的支撑，俄罗斯经济极有可能很快重回崩溃的边缘（当然，同时倒霉还有美国的另外两个死
对头，伊朗和委内瑞拉）。所以，在石油价格达到147.27美元的历史最高记录后就开始迅速迅速回落，直到今天已突破70美元。不过，油价的暴跌也让所有的
石油输出国腰包干瘪，所以，石油输出国组织在10月24日在奥地利首都维也纳举行特别会议，会后宣布自今年11月1日起日减产原油150万桶，以阻止油价进一
步下跌。欧佩克还明确表态，如果这次减产决定不能遏制油价下滑，将考虑进一步减产。很快的，欧佩克的减产决定让美欧国家“忧虑”，美英德等国纷纷向欧
佩克施压，逼欧佩克恢复石油产量。美国这样做在情理之中，欧盟国家也跟着起哄就没道理了，他们还怕自己买到的石油便宜吗？真是些贱骨头。不过，从欧
佩克的表态和动作来看，非常强硬，也许在这背后就有俄罗斯的统一调度。当然，站在中国的角度看，油价的下降有利于控制中国的通货膨胀，但是，围绕着
石油价格的涨落，在接下来的日子里，俄罗斯与美国（或者说是美英金融石油资本）之间还会暴发激烈的斗争，油价还可能有较大幅度的波动，再加上其他进
口大宗商品比如铁矿石的价格还有可能出现大的波动，所以对中国而言，“未来通货膨胀形势有可能出现交替和反复”。
    另外，美国还在俄罗斯的家门口点了一把大火，就是在奥运会开幕那天，格鲁吉亚对南奥塞梯发起了军事进攻。想不到的是，普京异常狠辣的出手了，非
常干脆利索的拿下了格鲁吉亚。并且，由于俄罗斯得到了中国的强力支持，导致了欧盟在此事上只能充当和事佬，结果，全世界都看到了强大的世界警察连自
己的小兄弟都帮不了，美国人这回面子可是丢到家了。
    当然，美国还有另一个可能扭转被动局面的办法可以选择，就是发动战争。但是，发动战争以扭转被动局面需要几个前提条件：一是有钱打仗，二是能打
赢。就目前形势而言，美国非常缺钱，再加上中俄在背后捣鬼，美国想打赢一仗是几乎不可能的。不过，美国还是通过兰德公司放风说什么7000亿救市不如和
“某个大国”打一仗，想吓住几个胆小的，以此扭转颓势。其实，美国在历史上就没有能够在战场上打败过哪个大国，相反，在战场上栽在“某个大国”脚下的次
数倒是不少。美国可以翻翻自己的老黄历，是不是有这事？
    美国真正比较适合点火的地方有两个：一个是叙利亚，一个是台海。所以，美国通过越境袭击叙利亚来探探风，不过美国的试探并没有吓着谁，相反，招
来了叙利亚的强烈反应，要求“美方对其后果承担全部责任”，阿盟更是“与叙利亚团结一致，支持叙利亚拥有自卫权以维护主权、保护人民生命安全”。其实，
如果美国真敢对叙利亚下手的话，也许驻阿富法美军的好日子就过到头了（俄罗斯从中亚出手教训一下美国大兵是必然的，这也从侧面证实了欧佩克减产有俄
罗斯在出力）。至于在台海搞点小动作，意思也是非常直白的，让北京办事的时候悠着点儿。所以，我们一面看到了马英九说什么台湾在63年前回归祖国意义
非常重大，一面也看到了台独分子追打大陆海协会副会长张铭清的消息。很显然，布什老兄这是在露一手，想到北京看看他操控台湾政坛的能力。其实这又何
必呢？台湾那一帮子败类没有一个能摆上台面的，谁会跟他们一般见识？条件不成熟，你们随便跳；条件成熟了，子弟兵杀过去，送他们到秦城监狱养老去！
美国眼看着直接显摆无效，又打起了小日本的主意，让马英九指示手下探勘钓鱼岛附近油气。钓鱼岛是中日领土争议区域，在这个地方开采油气很显然是在激
化中日矛盾，甚至有意把钓鱼岛问题和台湾问题国际化。不过，这次美国人打错了算盘，现在朝鲜正没事闲的手痒痒，前几天刚刚拳打李明博（朝鲜劳动党中
央机关报《劳动新闻》发表评论员文章称，“如果卖国贼势力不顾我们的反复警告，持续损害我们的尊严并继续坚持反共和国的对决之路，朝鲜不得已将做出
包括全面中断南北关系在内的重大决断。”），脚踢小日本（朝鲜内阁机关报《民主朝鲜》２１日发表评论，主张剥夺日本参与朝核问题六方会谈的资格），
威风的很。现在美国在台海兴风作浪，只能让朝鲜激情高胀——不要忘记了，前几天美国有媒体报道，发现朝鲜有疑似第二次核试验的迹象。前几天的发现也许
是假的，不过，如果马英九这么折腾下去，十有八九朝鲜的第二次核试验就变成了真的，那时，恐怕又有赖斯小姐忙活的了。

 ____________________________________________________________________

    19日更新：

　　巴基斯坦总统扎尔达里在两国合作文件签署仪式上笑得很开心，国内面临重重经济危机的他，在中国终于收获了大礼包。昨天，中国和巴基斯坦签署了11
份协议、备忘录和草案，包括基础设施、能源、电信、工农业、矿产、商贸、灾后援助和航空技术等方面。　　　　　

    伊朗原子能组织副主席穆罕默德-赛义迪10月5日在德黑兰宣布，美国和印度签署的政府间核能领域合作协议是对《不扩散核武器条约》的公然侵犯。　　
　

    巴基斯坦外交部长库雷希昨天在总结总统扎尔达里为期4天的访华成果时表示，中国将帮助巴基斯坦再建设两个民用核电站，以缓解巴基斯坦的能源短缺
状况。外长还透露，不久两国将举行共同经济委员会会议，新成立的由总统扎尔达里担任主席的部长级委员会将每个月举行会谈。此外总统决定将每3个月访
华一次,来促进两国的经济融合。中国还将支持“巴基斯坦的朋友们”论坛。　　

＿＿＿＿＿＿＿＿＿＿

　　简评：

　　第一个在这场全球金融风暴中获得来自中国的支持的是我们的好兄弟巴基斯坦，美国欧盟们还得再等等，再表示表示才行，至于韩国，也得看看他的表现
了。不过，这几天那个韩国鬼子把金胖子惹得很上火，估计北京心里也不爽。

 　　美国真牛，敢于顶住全天下的压力用核诱饵拉拢印度，结果跳出来唱反调的居然是伊朗（不是中国，也是中国），虽然中国没说什么，可手底下真没少
忙活。你美国做的，我中国也做的，你能和印度玩核，我就能和巴铁玩核，看谁不服气？

 　　当然，巴基斯坦也不是《不扩散核武器条约》的签字国，按道理说中国做的也不对，不过，我们的巴铁兄弟说了，愿意加入不扩散核武器条件，前提是
印度一起签字。可惜，老三不干。这能怪谁？跟着大哥有好处捞，也就不怪当兄弟的愿意三个月走一回亲戚了。人心都是肉长的嘛。

＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿ 

　　 昨日（10月18日），全国各地69位市长齐聚深圳参加“中国市长论坛”，住房与城乡建设部副部长仇保兴在论坛上表示：“应该给各城市政府一定的自由度
，各地的政府应该说有能力、也有责任，作出一些政策上的选择。 ”这也是高层首次对各地刺激楼市政策作正式表态。

＿＿＿＿＿＿＿＿＿＿＿　　

　　简评：

　　现在中央所谓的“认可地方政府救市”的态度，只不过是权宜之计，本质并不是想把房价重新拉起来。只不过房地产业是曾经的经济支柱，从去年十月开始
的把房价打下来的行动本身就是在把这根支柱砍倒。但是，砍这些柱子需要立起新柱子来，否则，谁来支撑经济运行。不巧的是，遇上了超级金融风暴，新支
柱的立起更不顺利了，在这样的背景下，老支柱有必要倒的慢一点。否则整个国民经济将一厥不振甚至走向反向。所以，这一次中央的态度，可以说是在做技
术性的调整，而非改变战略。
