# -*- org -*-

# Time-stamp: <2011-08-18 19:16:02 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+title: （转）三问美债信用降级

[2011-08-15 09:21:50]

华尔街所造成的低迷和悲观情绪累积的结果，最近迅疾沉重地打击了全球股市。

许多美国人认为，在2008年金融危机之后，奥巴马政府满怀信心推出的8000亿美元刺激计划，当前来看效果并非理想，并认为这种干预在很大程度上只是浪费金钱而已，这种浪费无疑已让美国政府所拥有的财政赤字越来越大，未来甚至有可能影响奥巴马总统的连任。

那么，<<美国以出售金融产品换取物质产品>>的生产方式是否走到了尽头？或者，包括美国在内的发达国家<<以高负债来支撑高消费，并为全世界提供市场>>的增长模式是否走到了尽头？无论怎样，许多人都很担心上一次美国次贷危机爆发时形成的庞大有毒资产重新发作，从而将美国和世界拖入新一轮金融危机的深渊
。

一个重要的问题是，这样一种局面若果真发生，经济总量世界第二却被庞大美债绑定的中国适合充当救世主吗？另外两个相关联而又必须有明确认识的重要问题是：<<中国3.2万亿美元外储的管理模式应有怎样的改变？人民币升值和国际化能否加速？>>

8月10日，3位学界知名人士中国宏观经济学会秘书长王建、北京师范大学国际金融研究所所长贺力平、对外经贸大学金融学院院长丁志杰，接受《华夏时报》记者专访，分别对上述问题做了精辟分析。

王建：中国应在新危机爆发前做好自己的事

+ 中国适合充当救世主吗？

美元或将崩溃中国须停止紧缩

《华夏时报》：2008年金融危机发生后，世界似乎让中国充当了一回救世主；2009年伦敦峰会上，世界吹捧中国。但地缘政治上美国重返亚洲这个结果是否足以证明，中国充当救世主的努力已经失败，中国并无资格再次充当救世主？

王建：中国2008年的4万亿投资，实际只是自救，而非救世界。客观上，中国最先走出衰退，从而提振了全球战胜危机的信心，但主观上，中国无论政府或企业界恐怕从来都没有充当救世主的心思。

《华夏时报》：您近年来和前不久有关美国可能会在近期爆发新一轮危机的预测，是否正在得到证明？您最近还针对美债危机发表观点说，任何政策都救不了美国，美国需要长时间一点点地把有毒资产消化。从这个角度看，是否可以说，中国难再施援手？

王建：现在，以美股暴跌为标志，美国新一轮次贷危机已经来袭，而且这一次一定会比上一次来得更严重。因为上一次，美国政府手中还有很多办法，比如可以用国债来拖，可以用QE来刺激。但现在，利率已经到顶，QE弄得美元风雨飘摇，财政提高两万亿美元的上限很困难，救市的工具几乎没有了，而问题却比过去要大。比如房贷，2008年底，美国大约有200万个家庭的房贷违约，2010年底已经超过500万个了，现在又有多少个，尚无新的数据。美国能否摆脱危机？根本没有可能。现在美国只能像当年日本那样，用较长时间修复银行资产负债表。

因此，我预测这一轮危机最后将走到美元崩溃的那一步。在这样一个形势下，中国自顾自救恐怕都来不及，还能救美国吗？那简直是开玩笑。被别人戴了顶高帽子，有些人就觉得好像中国已经是救世主了。

但另一方面，中国现在所面临的问题，并非欧美那样很难化解的问题。<<如果中国出问题，一定是中国自己找的，一定是宏观调控错了位。>>中国现在为何还要采取紧缩政策呢？真以为自己可以置身世界经济体系之外吗？真认为美国危机已经结束，已经是太平盛世，可以走过去正常发展的道路了吗？还不觉得一大片乌云仍压在头顶没有散去吗？事实证明并非如此。所以，中国的宏观调控政策，应当立即转到<<保增长>>这条路上来。长期来看，则并非短期宏观调控能解决问题。必须考虑<<如何从外需为主转为内需为主，通过收入分配关系的调整，通过城市化打开内需，必须进行这种彻底的结构性的改革>>。

《华夏时报》：您最近说，美国债务上限提高到2.4万亿美元，如此庞大的债务没有谁敢接盘，只能靠美联储发货币购买，QE3必定会推出。QE3的推出赌上了美元信誉，一旦美元的信誉崩溃，美国商品输入就会断流，经济就会走入一场比1929-1933年更大的危机。中国将如何面对这样的危机？中国经济的当务之急是什么？

王建：那就是<<停止紧缩，立即展开结构调整>>。

很多人现在还很迷茫很麻木，并不知道这是一场大危机来临前的风暴，实际上后边紧跟着一个巨大的危机就要爆发。因此，现在一定要赶快把该做的事情做好，把宏观调控的转向赶紧落实，结构调整的大的任务赶紧铺开。

我为什么说美元要崩溃？在奥巴马下台之前，我估计他会推三期QE，直到QE5，但谁买呢？越推QE，人们越不敢碰，因为掺水掺得太多了，谁还敢要美元呢？

要说美债的危险，是在这里。

+ 问题根源是有毒资产而非美债

《华夏时报》：您如何看美股行情和美国金融市场的变化趋势？

王建：美股正面临一个严重的大下跌行情，也面临一个混乱的金融市场，会有大批金融机构倒闭。

很多人都没有注意到，美股下跌其实是从7月22日开始的，到8月3日，有一个八连跌。8月4日，发生大暴跌，8月8日，又一次大暴跌。

《华夏时报》：如果美国实体经济不良现状再加上有毒资产现身引发金融市场动荡，如果美欧经济都在衰退泥潭中陷得更深，国际流动性避险资金是否必然流入中国并必然推涨中国本已较高的通胀水平？

王建：目前很多人都在谈论所谓美债危机，其实<<哪有什么美债危机！美国股市的暴跌是由什么引起的？>>是美国的有毒资产重新发酵了，这些资产解冻期到了，必须要进入市场，还有一些衍生金融产品到期了也得兑现，但美国现在没有那么多钱兑现，金融机构资产负债表又一次严重失衡。2009年以后，美联储只是用修改会计规则和冻结债务清偿的方式，暂时将金融机构的坏账掩盖起来，或是原来金融机构的坏账转至美联储的资产负债表中，将风险转移了。但华尔街现在回避这个问题，却谈论什么美债上限、欧债风险。美债上限是个问题吗？相对于美债，欧债更不是问题。华尔街现在试图用这个办法转移人们的注意力，美国人很担心发生市场恐慌和抛售美元资产等等更为可怕的行为。因此，<<美债并不是大问题，没办法清算的衍生金融品才是大问题。>>美国金融市场恐慌的不是美债，而是那些到期无法处理的有毒资产，很多金融机构将因此倒闭。

贺力平：还汇于民的前提是汇市更加开放

巨额外储管理模式应有怎样的改变？

匆忙调整必受损失

《华夏时报》：所谓美债危机引发中国3.2万亿外储的忧虑，学界对此亦有不同看法。您怎么看？

贺力平：我们一方面可以有所担心，却也不必有额外的恐慌。其对于中国庞大的外汇储备提出了更多的属于长远性的而非当前的问题，而更重要的是应关注长远的问题，应考虑到今后5到10年内国际金融市场若出现一些不稳定因素，若中国巨额外储资产质量多多少少受到不利影响，应有怎样稳妥的解决办法，寻求怎样的出路。

我认为必须要看到，中国目前的外汇资产其本身在国际金融市场上已经在发挥着一种稳定化的作用，也就是说，中国不作出任何仓促的重大调整，本身对于国际金融市场的稳定就会发挥一种定心丸的作用。如果当局匆忙作出一些决策，反而可能会起到不稳定的作用。

《华夏时报》：据外媒测算，中国持有的美国国债若以至少下跌20%计算，将会损失约2300亿美元，相当于中国人均亏损170多美元。您认为是这样的吗？

贺力平：这个算法完全是主观意义上的，是基于一些纯粹概率的假设。而能否发生，并不确定。由于国际金融市场的动荡实际上是全球性的，如果中国外储遭受到了一定损失，则所有的投资者都会遭到一定的损失，甚至损失有可能比中国还大。当然，中国外储的损失是官方外汇投资的损失，其他国家往往可能是分散的金融机构的投资损失。换句话说，<<国际金融市场并非针对某一国，而是针对全世界。>>从这个意义上看，今天我们所遇到的国际金融市场动荡跟2008年下半年的情形是一样的。<<世界经济把世界各国都困到一条船上了，如果风雨飘摇，如果都不去救这条船，则造成的损失大家都要承担。>>

中国外储在国际金融市场上所占投资虽然相当重要，但毕竟是整个金融市场投资的一小部分，当前的特点在于这种投资主要是由官方机构去进行，而其他国家的投资则相对分散。

《华夏时报》：有分析认为中国实际上已受困于美国国债市场，从某种意义上说，中国已被束缚住了手脚。您认为是这样吗？

贺力平：因为中国美元外储存量较大，若从自身利益上来看，只要做出重大调整，则市场价格必然发生巨大波动，反过来就会对中国自身资产本金和收益都会带来不利影响。就此而言，可以认为中国受困于美债市场。但这种受困应是经济活动中一种很正常的情形。块头大了，占用空间就比别人要多，当挪动一下的时候，就会发现有一定的拥挤感。

<<所谓受困，我认为主要指的是短期内的调整，长期来看，中国可以进行调整，并且主观上的调整空间是存在的。>>

+ 客观认识美元贬值

《华夏时报》：央行行长周小川前几天曾提出要“最大限度地减少国际金融市场波动对我国造成的负面影响”。这是否意味着外储管理模式将有更多改变？

贺力平：这种改变，应是一种长期性、战略性的事情，而且这种改变应当与经常项目持续性的顺差结合起来，与增加国内需求、更多发展国内市场结合起来。在过去几年当中，中央已提出要进行金融管理的改革，相信这件事情已经在做。从汇金、中投的成立等，已经可以看出眉目。今后，应会有更多的思路可以探讨。

+ 但我们不能把问题简单化。

从2009年开始到现在，美元汇率一直有升有降，不同时期对不同货币有不同表现。虽然美国政府希望美元贬值，但其体制决定了并不能总如愿以偿。<<美国本身对美元的外汇市场没有干预，美元在国际市场上究竟会有怎样的变化，取决于全球各大经济体相对的经济增长、通胀的走势，以及包括初级产品等在内的相关因素。>>

美国真正的目的，还是希望经济复苏和稳定，基于这个前提，美元即使有所贬值，并不会贬值到多么糟糕的程度。虽然目前美国经济并不是很好，但世界上其他很多经济体的状况，可能比美国更差。因此对于美元贬值，应相对去看。美元虽可能在一定时间内对某些货币贬值，却并不意味着会长时间大幅度地全面贬值。

美元长时间大幅度地全面贬值的可能性比较低，这一点应有更客观的认识，而不应有简单化的片面认识。

+ 额度不应继续增长

《华夏时报》：不过我们却看到无论学界还是民间对于外储问题有很多不同的看法或建议，比如应否停止外储增长？是否外储越增长损失越大？中国能否要求美国为未来美债潜在的损失和汇率损失提供担保？能否比照上世纪60年代一些欧洲国家因为持有大量美元外储，因担心美元汇率贬值，而与美国签订所谓“汇率损失担保协议”？

贺力平：具体有关中国对美国官方债券投资能否获得汇率损失担保的事情，我认为中美两国政府之间可以进行一定的协商谈判，至于能有怎样的担保措施或形式，两国政府的有关部门可以做些探讨，但从根本上说，我们不应寄希望于这种担保。因为即使美国政府有担保承诺，但担保的程度和范围，我认为都会是有限的。我还是坚持刚才的看法，中国外储长远来看应有调整，我赞成说我们已经有足够多的外储，不希望其继续增长，但这并不是说要人为地采取一个巨大的调整，而应是<<逐渐的调整，更多地应和中国经济发展的政策与结构调整联系起来，作为一个综合性的问题来观察和研究。>>

当然我们也可以采取另一个做法，即央行不再增长外储，而是停止对外储的干预，让人民币汇率完全浮动起来。从长远来看，这种做法也未必不可。但若指望这种调整在今天或明天出现，则可能并不现实。

因为中国国内毕竟有很多人担心汇率的巨大波动，可能造成宏观经济的很多不利。这个背景之下，首先最重要的是要有明确的战略方针，其次，在具体的细节问题上，可以和包括美国在内的国际社会，比如G20平台等，一起来探讨促进全球金融市场和货币市场稳定的一系列解决办法。

+ 市场须有更多开放

《华夏时报》：既然美国很想获得中国的资金，中国能否要求美国来中国香港或上海发行人民币债券，再通过外管局兑换成美元，从而给国内投资者更多的选择，也减缓中国外汇储备的压力？这是否一方面可发展人民币债券市场，让国内居民有更多的投资选择；另一方面也可减轻外储压力？

贺力平：这是可以考虑的问题，但至于美国人来不来，却很难说。中国无须要求美国人来，而是要进行金融市场的改革。如果中国金融市场很发达和高度开放，世界上各个金融机构和个人都可能来。现在问题在于是我们自己关上大门不让人家来。比如中国发行的债券，只让境外投资者少量持有，这个市场本身没有对外开放。中国自己的人民币都不可自由兑换，人家怎么会来呢？境外投资者买了人民币债券之后，当需要卖出的时候，要经过审批，而且要审批多久，谁也不知道，这样谁还会来呢？来了不是反而等同于被捆住手脚了吗？显然世界上没有人会做这样的事情。

《华夏时报》：中国汇率政策应做怎样的改变以避免外储管理的手段受到很大限制？我们可以通过所谓还汇于民、藏汇于民的方式，让民众得实惠吗？直接将外汇储备用于医疗、教育等社会福利会导致通胀吗？对于这些来自社会的疑问，您怎么看？

贺力平：这是一些带有误会的看法。所谓还汇于民或藏汇于民，我们看到，很多发达国家金融机构或投资机构，他们手中有本币资金，也有外币资金，但他们的官方机构，很少有外汇资金。

中国民众个人很多已经拥有不少外汇资金，在人民币升值的情形下，持有者有很强的结汇意愿，要把外汇资金变成人民币资金，但国内的资金要变成投资机构在海外进行投资的资金，这种情形比较少。我们现在有QDII，但只是很小一部分，而且目前还相当谨慎，制约因素较多，可见这个市场之不发达。

要真正做到所谓还汇于民、藏汇于民(<<这个民要理解为个人或企业、投资机构>>)，外汇市场就要更加开放，有一个外汇投资渠道，汇率不再是人民币单边升值预期，而是有升有降，让大家面对汇率的风险，和国际经济走势的不可预测性，形成对外投资多元化，就与现在央行所做的一些事情完全一样，而且可以更加形式多样化。

丁志杰：本币加速升值可约束美量化宽松

+ 人民币升值和国际化能否加速？

取消某些汇率管制时机成熟

《华夏时报》：您最近表示，标普下调美债评级或倒逼QE3出台，这对于人民币国际化，意味着怎样的机会和条件？

丁志杰：标普下调美债评级之后，全球金融市场包括外汇市场动荡起伏，可以说，若美国实施QE3，会在一定程度上冲击世界对美元的信心，从中我们也可看到2008年发生的金融危机至今仍未结束，而由于没有对经济进行必要的调整，美国试图以时间换空间，延缓调整的过程。由此可以认为，国际货币体系正处在趋于变动的过程中。中国在本次金融危机之后，通过双边的货币互换和跨境贸易支付结算，启动了人民币国际化进程。应该说，当前国际金融市场的不稳定，更坚定了中国推进人民币国际化的信心。而最主要的目的，是我们将通过这种努力，可以减少对于其他国际货币特别是美元的过度依赖。

<<但货币的国际化，取决于一个国家的经济实力，经济金融的发展水平，以及货币本身的属性，而不单单是决心。>>

《华夏时报》：当前背景之下，学界对于人民币国际化有更多的分析。有观点认为中国充足的外汇储备是人民币国际化的最好保障，人民币国际化应该加速。您赞同这样的观点吗？人民币如何抓住机遇，加速扩大国际贸易结算规模、推进资本账户开放？

丁志杰：对于人民币国际化的方向，学界观点基本一致，存在的分歧在于人民币国际化的方式和路径上。主要原因是，跨境贸易实行以人民币支付结算以来，人民币在跨境贸易中的使用正快速扩张，但由于人民币升值预期的存在，出现了一些套利型资金支付活动，多表现为进口支付人民币，这一方面产生了所谓人民币热钱；另一方面，在中国国际收支顺差不变的情形下，加大了外汇储备的压力。财务上看，可能存在着一定程度的不合理性。争论便来自于此。

这牵涉到中国的外汇管理和资本管制、人民币汇率改革、人民币国际化协调推进等一系列问题。

我的观点是，人民币国际化是一个长期的过程，当前并不存在不计成本大力推进人民币国际化的必要性，而应协调改革，特别包括汇率改革。从2005年到现在，汇率改革已经进行6年了，既有成功的经验，也可能有些不足和问题。6年来通过不断纠正失衡，为人民币汇率改革进一步加快奠定了基础。当前情况下，外汇资本管制上取消一些不必要的或者已经失效的管制和扭曲，时机已经相对成熟。

+ 美国实际正以邻为壑

《华夏时报》：有研究分析认为，如果不是中国实施让人民币与美元挂钩的汇率政策，并且这一政策被大多数亚太国家所模仿，金融市场早在2007年那一真正的转折点之前很久就会对美国敞开口子借钱的做法说不了。人民币与美元挂钩的做法意味着中国现在已经失去了对其经济的控制力，并将因此而遭受长期痛苦。您同意这样的看法吗？

丁志杰：在中国的对外经贸活动中，中国对美贸易举足轻重，如果要<<保持汇率的相对稳定>>，美元作为最主要的国际货币，起着锚的作用。全球都存在着对美元的依赖和依附，都或多或少或明或暗盯住美元，亚洲尤甚。这在一定时期是合理的，但随着中国经济的发展和中国经济地位的提升，其负面影响开始显现。我们应随着经济形势的变化，调整汇率政策。

<<所谓调整，就意味着怎样与美元脱钩。>>这个脱钩，我认为是个逐渐的趋势。在脱钩过程中，我们要处理很多的问题，其中包括外汇储备的管理等等。现在我们并非陷入所谓骑虎难下的境地，而是可以去改变局面。

《华夏时报》：美国的量化宽松，是否意味着其经济调整的负担压在了中国及新兴市场国家的身上？这些国家是否将继续高通胀？

丁志杰：首先，值得关注的是，目前美国仍在维持的量化宽松，时间不断在延长。我们看到，6月7日伯南克讲话以后，美国加息的时间窗口向后推迟到2012年下半年，这次美债评级下降，又使得美国的量化宽松，明确宣布推迟到2013年年中，同时美联储会后公报里面还讲到积极的货币扩张政策的一些措施。由此可见美国人是从自身的经济金融角度考虑问题，有其合理性。其次，QE2实施期间，美国实体经济没有明显改善。主要是金融市场对美国经济复苏起到了支持的作用。而金融市场的良好表现的主要受益者是华尔街金融利益集团，同时我们也要看到，<<在QE2期间，美国的货币供应量并没有增长。>>

我认为，美国延长宽松货币政策的时间，事实上就是一种以邻为壑的行为，造成了<<过多的流动性进入国际商品市场和新兴市场国家>>，包括中国在内的新兴市场国家货币被动扩张，就等于<<美国向全球输出通胀>>。因此，未来一段时间，包括中国在内的新兴市场国家的资本流入压力和通胀的压力，资产价格伴生的压力、汇率的压力就会出现。

+ 加速升值可约束量化宽松

《华夏时报》：面对上述影响，人民币应否加速升值？

丁志杰：现在来看，<<美国为什么可以肆无忌惮地长期维持量化宽松？>>最重要的一点，在于其能够把释放出的流动性输入到其他国家，美国本身没有受到量化宽松的负面影响。如何能够让美国对于量化宽松采取谨慎态度？就在于大家能够把美国释放出的流动性堵回去。未来一段时间，新兴市场国家可能通过加强资本流入的管理，促使美国更为谨慎地对待量化宽松。就人民币汇率而言，我们可以看到，在过去将近十年的时间内，全球大宗商品价格一直在上涨，但中国出口产品的价格几乎没有太大涨幅，其涨幅与进口产品的价格涨幅相比，几乎可以忽略不计。也就是说，<<中国承担了全球大宗商品价格上涨的主要成本。>>如果人民币升值速度加快，我认为可能对中国出口产生一定冲击，但却可能倒逼出口产品价格的上升，这样就会使得量化宽松政策导致的全球大宗商品价格上涨成本，不仅仅由中国来承担，而且也由那些进口国包括美国来承担，这也会让美国的量化宽松政策受些约束。

从博弈的层面上来看，我觉得，我们不能因为这一轮国际金融市场的风暴而调整人民币汇率政策，更主要的是<<完善人民币汇率机制改革>>，该升则升，改贬则贬，这才能使汇率对于对外经贸活动的调节产生杠杆作用。
