# -*- org -*-

# Time-stamp: <2011-08-23 15:05:23 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 【金鸿评论】关注拜登访华（之二）


[2011-08-22 14:29]


【金鸿评论】随着拜登的到来，东亚局势一片和谐。中国航母下水很显然是日本人不愿意看到的，可是，在第七届北京——东京论坛“外交和安全保障分论坛”上，日本自民党政务调查会会长、前防卫大臣石破茂说，中国有航母很正常，日本不应把中国发展航母视为对日本安全的威胁。

除了东亚以外，还有一个地方的局势开始缓和，就是叙利亚。8月18日，美国和英法德三国领导人先后发表措辞强硬的声明，要求巴沙尔下台。为了逼巴沙尔下台，奥巴马当天还签署总统令，下令立即冻结叙利亚政府在美国的所有资产，禁止美国公民到叙利亚投资，不准进口叙利亚石油和石油制品。不过，欧洲人没有象美国人那样对叙利亚政府实行经济制裁。时间仅仅过了一天，俄罗斯外交部就发表声明，坚决反对西方国家要求叙利亚总统巴沙尔下台的立场，俄罗斯人认为，应当给予巴沙尔足够的时间实施大规模的社会、政治和经济改革。改革嘛，是一项伟大的事业，需要时间，也应该允许犯错误，摸着石头过河，说不定就会被冲走一只鞋嘛，要允许交学费嘛。而且，人家巴沙尔已经承诺停止一切针对示威者的军事活动，并宣布要赦免政治犯，停止实施紧急状态法，在年内举行议会选举，这都是巴沙尔有诚意的表现嘛。

8月21日，叙利亚总统巴沙尔在大马士革说，叙利亚人民的觉悟保卫了祖国，挫败了在近几周来颠覆叙利亚政权的阴谋，叙利亚的安全局势正在好转……

巴沙尔的位子是稳住了，不过疯子扎卡菲就倒了霉了。

 

【金鸿评论】8月20日，利比亚反对派占领了利比亚东部具有战略性的石油重镇布雷加，当天，卡扎菲政权的二号人物贾卢德前往意大利寻求庇护。8月21日，利比亚反对派攻进了的黎波里，卡扎菲的大儿子投降了，二儿子被抓了，利比亚反对派发誓，就算把的黎波里挖地三尺，也要把卡扎菲抠出来。

卡扎菲这会终于明白了，自己的下场比萨卡什维利还惨呀，相信美国人那张嘴还不如相信鬼呀。

这几天利比亚反对派之所以能一个胜利接着一个胜利，首先要感谢欧洲人无私的帮助，没有他们大无畏的国际主义精神，那群乌合之众能打胜仗？近几天，北约（欧洲人）的空袭力度大大增强，就连在联合国投票弃权的德国也悄悄地派兵直接参与北约对利比亚军事行动了。对于这种做好事不留姓名的做法，德国政府的解释是，这11名士兵只是去混饭吃的，既没有指挥权，也没有决定权。

有句俗话叫好心遭雷霹，这回就让德国人遇上了。德国首都柏林连续发生焚烧汽车事件，德国汉堡街头也发生了警民冲突。

利比亚局势闹到这一步，也是美国无能的结果。本来，美国希望想办法逼欧盟与自己一道把巴沙尔弄下台，可是一直未能如愿。现如今，美国经济撑不住了，缺钱救急，可上个月奥巴马走了步昏招——见了达赖，又把北京给惹毛了，现在拜登上门化缘，必须得给北京个交待，于是，在东亚全方位让步了。不仅如此，美国政府还在自己极其缺钱的情况下拨款90万美元帮助受到严重洪涝灾害的朝鲜人民，真是白求恩在世呀。

既使这样，北京仍然不满意，继续开价要求美国支持人民币成为全球硬通货，这摆明是在抢美元的地盘。为了自保，美国只好让以色列在中东闹事，先杀埃及警察，再空袭加沙，最后还抓了120名哈马斯组织的成员。目的自然是保护石油美元结算制。

以色列在中东开了杀戒以后，欧洲人没吱声，不过，不吱声是有条件的，那就是奥巴马不准反对欧洲人活捉卡扎菲。于是乎，疯子倒霉了。美国人虽然没有反对欧洲人在利比亚抢地盘，却也不反对欧洲本土出乱子。刚刚看到路透的消息，说疯子被捕了，如果这是真的，那说明美国与欧盟到了必须翻脸的时候了。

这两天，欧洲人又在家里为了欧盟债券的事情吵上了。最新的消息是，德国和法国强烈反对这件事，理由是会增加本国的融资成本。这个理由只是托词。增加点融资成本算什么？随便倒一只欧洲猪国的救援成本不比这个高得多，真正的原因应该是欧盟需要先把利比亚乱局消化掉，不然，引火烧身可不是闹着玩的，德国不也出了一帮“野孩子”吗？

8月19日，欧元集团主席容克说，欧元区成员国须放弃一般意义上的“经济管理主权”才能在真正意义上实现欧元经济管理整合，才能发挥欧元意义，“未放弃国家经济主权的欧元区经济管理整合体制将是死路一条”。容克的话说的很实在，如果欧元区国家不把财政主权交出来，欧元肯定是死路一条，不过，交出财政主权了之后，各国政府的领导人还有什么权利呢？不交不行，交了太难受，这该如何是好？看来，只有被逼得活不下去的时候，各国才会乖乖的交权，从这个意义上说，欧债危机也是欧元区财政大权整合的好机会。不过，一旦欧元区统一了财政权，美国再想对付欧元可就难了。

 

【金鸿评论】最近几天，美国股市又开始暴跌，奥巴马却坚持要带家人休假10天。对于奥巴马的行为，共和党人和部分民主党人认为，美国正处经济危机之中，总统应该留在华盛顿，白宫发言人却说，有位伟人说过，不会休息就不会工作，总统是没有假期的，不过休息一下还是可以的，现在，总统只不过是跟大家一起旅行去了，任何一个有人情味的美国人都不会反对总统花点时间陪家人吧？

奥巴马旅行的地点是马萨诸塞州的马莎葡萄园岛。奥巴马总统说了，经济状况将决定他是否能连任。奥巴马非常清楚，马莎葡萄园岛是个失业率极高的地方。要想降低这里的失业率，就得有人来旅行，所以，奥巴马总统亲自来拉动当地就业率了。不过，我们更想知道的是，如果当地的应招女郎的失业率也很高，奥巴马总统是否也愿意帮帮忙呢？
