# -*- org -*-

# Time-stamp: <2011-08-18 19:24:20 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+title: 【金鸿评论】英国骚乱事件背后


[2011-08-10 18:20:39]

 【金鸿评论】一场突如其来的骚乱事件从伦敦蔓延到了伯明翰和利物浦，这几个城市相继发生了严重的暴力事件。8月8日晚，伦敦市区进入了全面警报状态，为了稳定局势，部署在伦敦的警力已经从之前的6000人增加到了1.6万人。英国首相卡梅伦和伦敦市长约翰逊不得不食言而肥，提前结束休假返回伦敦处理暴力事件。目前，伦敦已有三百多人被捕……

 

【金鸿评论】8月4日，一名叫达根的黑人男子坐在出租车里被警察拦截，随后，达根身中两弹当场死亡。根据警方的说法，达根和警方交涉过程中态度非常恶劣，并且向警方射击导致警察受伤，现场的警察不得已才将其射杀。

警方的解释无法让达根的家人相信。事后英国独立警方投诉委员会公布的初步弹道检验也显示，杜根并没有开过枪，虽然现场有一支已上膛的枪支，打中警察佩戴的无线电的那颗子弹来自警方的枪支。有网络留言称，达根是在放下枪后被“处死”的。

在托特纳姆，犯罪率一直相对较高，警民关系非常紧张，警察经常粗暴地对待居民，在当地移民看来，警方一直是戴着有色眼镜看待他们的。这一次，无辜的达根被杀点燃了移民们的怒火。8月6日晚，约有300名民众聚集在当地警察局门前抗议，很快，抗议演变成了一场严重的骚乱并在伦敦各地扩散。

骚乱发生前，警方已经收到了很多预警，可是，托特纳姆警察部门的负责人还是在骚乱发生前数小时乘坐飞机外出度假了。骚乱发生后，正在休假的伦敦市长约翰逊也同样拒绝提前结束假期，直至事态变得无法收拾。

 

【金鸿评论】达根之死不禁让人想到了半年前被突尼斯警方逼死的26岁的街头小贩。在那名小贩自焚以后，当地居民与突尼斯国民卫队发生了严重冲突，冲突很快蔓延到全国各地，最后，突尼斯总统本·阿里下台了。

与突尼斯警方相比，英国警方更加可恨：<<突尼斯小贩是在警方的粗暴执法之下愤而自杀的，而达根是无罪被杀的，而且，杀人的警察还编造案情企图蒙混过关。>>

还有一件耐人寻味的事情，在<<茉莉花革命>>中，维基解密是立了大功的，维基解密把本·阿里家族的腐败事实公之于众之后引发了民变，阿里总统才不得不下台的。而在英国骚乱事件中，脸谱、推特等社交网站和黑莓手机是参与骚乱者相互联系的重要工具。达根被枪杀后，当地民众就是利用推特等网站发布信息，抱怨警方失职、号召民众加入街头抗议行动的。骚乱发生后，又有人在不断“推特”即时动态，招呼民众到现场助力。

过去，西方国家一直强烈支持网络自由，反对他国政府对此类网站进行管制，现在呢，英国的社会舆论却在痛批脸谱和推特了。不过，《每日电讯报》认为，社交网络所起的煽风点火的作用远不及黑莓手机，黑莓的责任更大一些。黑莓手机的制造商RIM公司也是知错就改，马上表态愿意协助英国警方展开调查。不过，RIM的表态让一部分黑莓用户很是恐慌，他们担心自己的私人信息会泄露。看来，在西方国家也不是随时随地都能享受民主和自由的。

在英国首相卡梅伦眼里，国内发生的骚乱事件是“绝对的犯罪行为”，必须严厉打击，可是，英国媒体播放的一位骚乱参与者却在呼喊：“我们不要暴力，我们要社会公正，我们要工作”。另有报道称，<<最小的参与骚乱的人仅仅7岁——7岁的孩子懂什么？7岁的孩子都成了暴民，说明什么？>>

 

【金鸿评论】从表面上看，这一事件的起因是警民冲突和种族矛盾，因为托特纳姆是伦敦相对贫穷的区域，那里<<加勒比黑人>>集中居住的地方，是英国失业率最高的社区之一，很多人陷入了绝望之中。

这次参加骚乱的大都是年轻人。本来，他们中的大多数应该上在大学里读书，可是，由于这些移民的教育并没有受到应有的重视，他们大都失去上大学的机会。在以往经济状况好的时候，他们还可以有一份工作做，而在陷入经济萧条的今天，他们中的相当一部分人都失业了，由此对社会产生了强烈的不满。

所以，<<教育上的不平等和经济上的不景气，才是导致这次骚乱的根本原因>>。

全球金融危机以后，英国是最后一个走出衰退的发达国家。今年第二季度，英国的国内生产总值增长率仅为0.2%。失业率为7.7%，是1996年以来的最高水平。为了应对低迷的经济状况，英国政府就采取了紧缩措施，压缩公共开支以削减赤字。由于英国现政府领导人都是家境富裕的白人，他们对社会底层成员有一种天然的隔膜。卡梅伦政府把削减开支的项目选在了教育、医疗等方面。结果，英国社会最贫困、最底层的成员首先受到了冲击。去年12月，伦敦就已经爆发过抗议大学学费上涨的大规模抗议事件；今年6月份，又发生了几十万名公务员和教师走上街头抗议英国政府的养老金改革计划的事情。这些都是英国政府压缩公共开支的恶果。

这一次的骚乱，虽然是由一次偶然的枪击事件引发的，但它反映出来的英国国内的经济问题和卡梅伦政府错误政策却不是偶然的。现在，欧债危机卷土重来，标普下调美国信用等级，全球股市暴跌，全球经济第二次探底的可能性大大增加了，这对复苏最为艰难的英国经济来说又意味着什么呢？谁也不敢说。如果英国经济重新陷入衰退之中，那么类似的事件再次发生还会是偶然吗？

 

【金鸿评论】距2012年伦敦奥运会开幕已经不到一年了，在离奥运会主体育场只有几英里的地方发生了骚乱和抢劫，我们不得不对奥运会的安保情况有所担忧。可是，只要英国经济走不出低谷，英国的社会稳定就始终是个大问题，英国经济不可能在一年内突然繁荣起来，明年伦敦奥运会期间会不会发生类似的事件也始终是个未知数。在摆脱经济困境的道路上，卡梅伦政府还有很长的路要走。
