# -*- org -*-

# Time-stamp: <2011-09-10 01:21:30 Saturday by ldw>

#+OPTIONS:^:nilauthor:niltimestamp:nilcreator:nilH:2

#+STARTUP: indent

#+title:时事评论


* 时事评论

** 虚伪的民主,可怜的人权

[2007-06-0111:35]

问：哪一个国家的石油蕴藏量最多？

答：沙特阿拉伯，政教合一的君主独裁国家

是美国在中东的战略盟友



问：哪一个国家的石油蕴藏量占第二高？

答：伊拉克　



问：萨达姆是谁扶植起来的？

答：美国　



问：本拉登是谁扶植起来的？

答：美国



问：美国攻打伊拉克的理由是什么？

答：伊拉克藏有大规模杀伤性武器　

　　

问：美国攻打伊拉克经过联合国的授权了吗？

答：没有　　　



问：大规模杀伤性武器找到了吗？

答：没有，美国政府说是情报出了问题



问：小布什在参选总统的时候，收取的上亿美金的政治现金

　　主要来源于哪里？

答：美国的军火商和石油商



问：美国的军火石油企业是私有还是国有？

答：是私有的



问：伊拉克战争和伊拉克重建所需要的所有花费来自哪里？

答：全体美国纳税人



问：伊拉克战争给美国人民带来了什么？

答：恐怖主义更加嚣张。美国形象大损，

无数美国士兵在伊失去生命

问：美国人口在全世界占多少比例？

答：6％





问：美国拥有的财富占全世界多少比例？

答：50％



问：全世界一年的军事花费有多少？

答：9000多亿美元



问：其中美国的花费占多少？

答：50％



问：根据联合国的估计，美国军费抽出几成，就可以供应全世界

　　人民的基本生活所需？

答：一成，即大约400亿，这是当初美国报复性攻打阿富汗的费用



问：二次大战后有多少人死（于战争）？

答：8600万





问：伊拉克从何时开始拥有生化武器？

答：自1980年代开始



问：伊拉克是自己发展这些生化武器的吗？

答：不是，材料和技术是由美国和英国的政府及其私人公司提供的。





问：当伊拉克以毒气攻击伊朗（两伊战争时，1980-1988），美国政府

　　有没有谴责？

答：没有





问：1988年，萨达姆以毒气攻击哈拉比亚镇的库德族人，杀死了多少人？

答：5,000人。





问：这次有多少西方国家对伊拉克提出了谴责？

答：0

　　



问：美国在越战时使用了多少加仑的橙剂（含有245-T或245-三氯苯氧乙酸

　　之除草剂，曾在丛林战中用作脱叶剂，英国在马来亚和美国在越南战

　　争中都使用过。名称来源于在越南所用容器周围涂的橙色环。对人有

　　毒，因为含有微量二戴奥辛英，可引起严重的皮疹(氯痤疮)，以及实

　　验动物的婴儿畸型和癌症）？

答：1700万



问：是否有任何证据显示伊拉克和911事件的攻击者有勾结？

答：没有





问：1991年海湾战争中，估计有多少平民死亡？

答：35,000人



问：在海湾战争中，伊拉克造成了西方国家多国部队多少人死亡？

答：零



问：美国用装有推犁的坦克车，活埋了多少中的伊拉克士兵？

答：6,000人





问：海湾战争后，多国部队留下了多少铀乏弹在伊拉克和科威特？

答：40吨





问：根据联合国的估计，1991-1994年伊拉克人的癌症罹患率增加了多少？

答：700％





问：美国宣称它在1991年摧毁了多少伊拉克战力？

答：80％





问：是否有证据显示，伊拉克的武器除了自卫之外，还预备作其他用途？　　

　　

答：没有





问：伊拉克是否比十年前对于世界和平更具威胁性？

答：不是





问：五角大楼（美国国防部）指出，在2002-2003年对伊拉克的攻击中，

　　有多少平民因而死亡？

答：10,000人



问：这其中有多少是儿童？

答：超过一半



凡是中国民众反对自己政府的，就说，看，中国多独裁，

连自己的民众都反对！

凡是美国民众理性反对美国政府的，叫做民主权利，

凡是中国民众理性反对美国政府的，叫做反对民主。

凡是美国民众愤怒反对美国政府的，还是叫做民主权利，　

凡是中国民众愤怒性反对美国政府的，叫做义和团或者愤青。　

凡是反对美国政策的东方国家叫做独裁国家，

凡是反对美国政策的西方国家叫做“老欧洲”。

凡是美国经济发展，叫做经济复苏，

凡是中国经济发展，叫做中国威胁，

凡是美国经济出现问题，叫做正在衰退，

凡是中国经济出现问题，叫做即将崩溃。

凡是美国增加军费叫做维护和平，必须欢欣鼓舞，　

凡是中国增加军费叫做破坏和平，必须深表忧虑，　

凡是美国在海外使用武力，叫做维护稳定，　

凡是中国在境内部署导弹，叫做非常不安。　

凡是美国反对外国??，叫做排外主义，　

凡是美国登上银河号，叫做全面核查，　

凡是中国登上间谍飞机，叫做侵犯主权。

凡是针对美国平民的袭击，叫做恐怖主义，

凡是针对中国平民的袭击，叫做民族自决，

凡是美国反对恐怖主义，叫做反对恐怖主义，

凡是中国反对恐怖主义，叫做压制不同声音。

凡是美国对外动武，叫做推翻专制，

凡是中国捍卫领土，叫做改变现状，

凡是美国人说伊拉克人好，就叫做帮助建立民主，

凡是中国人说伊拉克人好，就叫做同情恐怖分子。

凡是美国在战争中死了人，必须牢记精确数字念念不忘，最好牢记姓名性别

凡是外国在战争中死了人，大概数字都不用记管他男女老幼国别种族，

凡是美国人不幸丧命就大叫大嚷“人权受犯”，

凡是外国人不幸丧命迫不得已说声“深表遗憾”。

凡是美国人质被抓，就怪恐怖分子，

凡是中国人质被抓，就笑网络愤青，

凡是美国人质被解救，就欢呼雀跃，

凡是中国人质被解救，就反问有什么可乐的？

凡是美国解救人质的努力，就编成传奇故事电影大片，

凡是中国解救人质的努力，谁敢叫好就是“歌功颂德”。

** 漫话六方会谈

[2007-06-2215:22:22]

六方会又要开始了。

先为六方会谈正一下名，还是改为四方会谈好一点。谈判桌是人上的地方，狗也上去？中俄美朝都有权利有本事把谈判桌掀了不谈了，日韩行吗？既然只是个看客，上桌子听人家打嘴仗也没多大意思。不过没办法，这边是中朝俄，那边怎么也得拉两个小弟，要不然显得当老大的没势力。这么凑合着谈吧。反正也谈不出什么真正的结果来。

老美是希望半岛无核化，可那只是一厢情愿。反应堆对老金而言那就是冬天在屋里烧的取暖用的炉子，天暖和就熄火，天一冷呢，继续烧呀，穷人嘛，吹不起空调，没炉子怎么过冬？零下三十度呢。

在核武问题上，老美一向奉向双重标准。为了打压我们，让阿三有核；为了保住中东，让小以有核。没办法，为了对付阿三，我们让巴有核；为了打压小鬼子，只能让老金也赶一会时髦。核弹弹嘛，不是一般人能有的，君不见，日不落帝国都不要了吗？

明知无果，还得演戏呀。生活嘛。谁叫人家是世界警察呢，人家连外交部都没有，全世界的事，都是他们的家务事。朝核这么大的事，能不谈？上次弹破了，过了不久，老美带着狗子把联防台湾给删了，让北极熊当了个二传，把老金那几千万美金还了回去，这才有了今天的再谈。说不定哪天出个什么恶心人的事，我们气不顺，再让他停停也很正常。最近，老美没少恶心我们：美会见疆独，日会见台独，澳会见藏独，更见气的是，老美还弄个反共的纪念碑。有本事就真上呀？东突还想起浪？阿富汗那几万霉国大兵还被中俄包着饺子呢，说不定中俄一起兴，把他剁巴剁巴生着吃了。至于西藏，自从青藏铁路开通以后，阿三都吓的直抽筋，何况几个喇嘛。至于台独，有本事就试试吧。

这次六方回谈的结果是什么？一种可能，西线有事，波斯壮汉前几天不是放风了吗？叫老美放人，小布没干，说不定，这边谈的不愉快，那边壮汉挽起袖子就抓几个霉国大兵。那边一点火，老美还得先救火。第二种可能呢，说不定老美再在什么地方把我们惹火了（中俄任何一方），掀了桌子也是常事。看好戏吧。

当然，这次人家还是很有诚意滴。特别是小鬼子，居然要和老金正常化。NND，上次老金放钻天猴的时候，你不是嚷着打他吗？怎么今天这么乖呀？没办法，属狗脸的。说变就变。




** 乱弹台海迷局

[2007-06-3010:21:22]

在所有的地区局势中，大家最关心的就是台海，最容易情绪激化的也是台海，讨论最多的也是台海，最难看清结果和结果如何实现的也是台海。今天自不量力，也来乱弹一翻。

台湾问题，归结起来就是三点：1、能否收回，2怎么收回，3、何时收回。下面一一展开讨论。

*** 能否收回。

答案非常简单，能！美国掺和，日本搅局，没用。如果今天台湾独立，中国马上动手，不用说是胡总这样强势的领袖在台上，换个再软的人在大位上也不会让台湾跑了。千古骂名可是我们这些不肖孙子所承受不了的。为了收台，可以让台湾一片焦土；为了收台，我们可以死一百万人、一千万人（美国能承受多大的伤亡代价？）；为了收台，我们可以让日本群岛永沉海底（日本能做到损失对等吗？）收台，是我们的内内政，道义上我们又是占绝对上风的。所以，我们拥有最强大的战争意志，无人可比。

战争意志决定战争的胜负的结果。其他的，只能决定战争胜负所要的代价。

胡总的强势，这里有一个小例子，省得有人以后再说我们胡总软：大家都知道今年年初的歼10和礼花，可你们知道年初胡总在利比里亚阅兵呢？在外国阅兵，除了美国的总统干过，也就咱胡哥了，（叫哥好，希望他年轻一点呀，国家需要，人民需要呀。）有人可能说，那兵是联和国的维和部队，没错，可胡哥可不是联合国的官员。“同志们好”“同志们辛苦了”那可不是联合国的口号，“首长好”“为人民服务”那也不是吃素的。我敢打赌，只要胡总一声令下，那绝对是一支虎狼之师！

*** 怎么收回

呼声最高的是武统，但是最理想的境界是和统。中国人都喜欢玩高水平，“不战而屈人之兵，善之善者也”，老祖宗的话，没错。

在常人眼里，有从少次应该出手了，却没有出手，大家心里憋得慌，甚至有人骂娘。爱国之心，情有可原。可是，有没有想过，为什么中央一直不动手？笔者的答案可能与所有人的都不一样：榜样。

建国以来，直接打过几仗：抗美援朝、珍宝岛之战、中印边境反击战、对越自卫反击战。我们都赢了。可是，有一个非常重要的现象大家是否注意到了：无论哪一仗，都是我们在忍无可忍的情况下才打的。反过来讲，只要能忍，那就不打。原因在此不多深究。但由此形成了一个我们作战的一个惯性或者说是定式思维，或者干脆就叫“传统”。这一点在经济学上有一个名词叫做“路径依赖”。下面用两个例子解释一下：

第一个：有人将5只猴子放在一只笼子里，并在笼子中间吊上一串香蕉，只要有猴子伸手去拿香蕉，就用高压水教训所有的猴子，直到没有一只猴子再敢动手。然后用一只新猴子替换出笼子里的一只猴子，新来的猴子不知这里的“规矩”，竟又伸出上肢去拿香蕉，结果触怒了原来笼子里的4只猴子，于是它们代替人执行惩罚任务，把新来的猴子暴打一顿，直到它服从这里的“规矩”为止。试验人员如此不断地将最初经历过高压水惩戒的猴子换出来，最后笼子里的猴子全是新的，但没有一只猴子再敢去碰香蕉。

起初，猴子怕受到“株连”，不允许其他猴子去碰香蕉，这是合理的。但后来人和高压水都不再介入，而新来的猴子却固守着“不许拿香蕉”的制度不变，这就是路径依赖的自我强化效应。

第二个：一个广为流传、引人入胜的例证是：现代铁路两条铁轨之间的标准距离是四英尺又八点五英寸，为什么采用这个标准呢？原来，早期的铁路是由建电车的人所设计的，而四英尺又八点五英寸正是电车所用的轮距标准。那么，电车的标准又是从哪里来的呢?最先造电车的人以前是造马车的，所以电车的标准是沿用马车的轮距标准。马车又为什么要用这个轮距标准呢?英国马路辙迹的宽度是四英尺又八点五英寸，所以，如果马车用其他轮距，它的轮子很快会在英国的老路上撞坏。这些辙迹又是从何而来的呢?从古罗马人那里来的。因为整个欧洲，包括英国的长途老路都是由罗马人为它的军队所铺设的，而四英尺又八点五英寸正是罗马战车的宽度。任何其他轮宽的战车在这些路上行驶的话，轮子的寿命都不会很长。可以再问，罗马人为什么以四英尺又八点五英寸为战车的轮距宽度呢？原因很简单，这是牵引一辆战车的两匹马屁股的宽度。故事到此还没有结束。美国航天飞机燃料箱的两旁有两个火箭推进器，因为这些推进器造好之后要用火车运送，路上又要通过一些隧道，而这些隧道的宽度只比火车轨道宽一点，因此火箭助推器的宽度是由铁轨的宽度所决定的。

所以，最后的结论是：路径依赖导致了美国航天飞机火箭助推器的宽度，竟然是两千年前便由两匹马屁股的宽度所决定的。

现在返回来，每次台海出现大的波动时，大家都喊“打”，中央却不动。大家往往很失望，甚至情绪冲动。可大家不防读读建国来的四次战争的历史，每一次也都是忍无可忍时才打的。在打之前，那时人民的心情和我们是一样的。可以负责任的讲，不打，是在为和平而忍耐，一旦动起手来，台湾就是我们的，谁TMD也别想捞一点油水去！

*** 如何收回

至于如何收回，可以说，现在武统的条件具备了。今年收回也在情理之中，不然可能就要拖个十年八年甚至更久一点了。至于到底是文是武，大家都可以讨论，但应该和中央保持一致。我们的胡总和温总都是爱国的，也都是实实在在的在为老百姓做事的，他们是为了谋求民族国家的利益最大化的。大家也不必去刻意的要什么太明确的解答，因为这对国家是不利的。

鬼谷子里有句话说的很实在：“天地之道，在高与深；圣人之治道，在隐与匿。非独忠信仁义也，中正而已矣。”就是这个道理。总之一句话，相信胡总，支持胡总。

当然，有人也一直想挑点事儿看看，在此，换这些人别白费心机了。真正有作为的中国人，做事一向是按部就班，不会受外界干扰的。套用相书上的一句话“万态纷措于前而心常一则”，这才是真正的大富大贵之人。明白否？

在台海，我们军事上是绝对占优的，在前面笔者曾发文《老山姆金蝉脱壳，小日本火中取栗》从道理上推断，F22我们能搞下来，老美害怕才撤的。之后，有网友有异议。难免。毕竟老美科技厉害。前几天偶然间发现一点资料，是官泄的，所以拿出来也无妨：对于F-22的威胁，CCTV-7新开的一个叫防务观察，请了几个军内专家出面作了分析，一个空军防空研究所的专家有一句话意味深长：隐形飞机是从下面看的，如从他上面看，并那么不隐形。

再联想到年初北斗升空紧急组网，大家可以得出什么结论？

至于老美说自己F22明天飞回来，那是哄孩子的。既要回来当初为什么要走？飞来飞去的不费油吗？走的时候就两架趴了窝，现在能不能飞的动还是个问题。再说了，老美说打南盟是为了人权，结果照着巴尔干的兄弟们一顿揍之后，大家忽然发现，欧元软了，北极熊的活动地盘受压制了。老美说打伊拉克是为了大规模杀伤性武器，结果挖地三尽找到没有？老美说打塔利班是为了反恐，打下来之后我们发现怎么阿富汗离我们的西北的窗户怎么那么近呢？风水上说了，西北开窗对主人不利，没办法，中俄联合禁毒带搞起来了，给他包个粽子，这才安全了。当然，美国大兵们，你们就在里面呆着吧。闷？好说，内贾德兄弟有办法给你们找人取乐子，把伊朗境内的一百万难民分批送加去，有聊天的了吧？划拳的都有了。不过，这些人没吃没喝性子野，他们的吃喝拉撒就拜托你们有钱的美国人了。

扯远了，再翻回来。其实，决定战争胜负的绝对不是一件两件的新式武器，战争的意志，正确的战略战术，部队的求胜欲望与凝聚力，哪一样都不比武器在战争中取得胜负发挥的作用差。盲目迷信先进武器是很可爱的，也是很天真的。大韩帝国前几天不就办了一件这样的好事吗？他们的美国老爹给一艘先进的“宙斯盾”，比给日本的技术领先。韩国人举国沸腾。终于当了一回亲儿子，有的疼嘛。其实，那可真是哄孩子的。有本事把你们的什么什么世宗大王弄到深海走一圈去。你们就知道了，那玩艺儿对你们而言，只是个好看的东西。当然，东西也好使，但得分在谁手里。你们的后勤根本就不补不上，出去了，就是送死。不能不说，论后勤，你们比小日本差远了。所以，别自个儿在那傻笑了。明眼人会拿你们当疯子。


** 【奋进社/金鸿95】

** 【奋进社/金鸿95】意志的对决

[2007-09-0114:08:10]

首先简单回顾一下台独最近的一点动向：

美国副国务卿内格罗蓬特28日表示，美国认为台湾“入联公投[fn:2]”是“朝向宣布台湾‘独立’的一个步骤”。对此，民进党秘书长林佳龙称，内格罗蓬特的谈话非常不得体，很失礼，应该收回。

接着传出了“美国只要五分钟时间，就可以动员台湾人民把陈水扁推翻掉”的消息，该消息引起陈水扁当局的愤怒。台“外交部”要求美国政府应就此说法公开澄清。而美方的回应是，“这绝对不是美国政府的立场”[fn:3]。

陈水扁无疑是老美的一个棋子，这个时候跳出来与老美“对抗”，无疑是在唱双簧。这个双簧的目的有二：一是逼北京在中东让步，二是为下一步小马上台开辟通道。对于第一点，我们下面讨论，先简单说一下第二点，近几个月来，小马的表现让所有的中国同胞都看到了，小马也是个不折不扣的台独分子，整个中国大陆，对小马好感全无，而此时，小扁跳出来急独，相对之下，小马的立场倒是有利于两岸和平的、海台稳定的。本着两害两权取其轻的原则，选择小马比选择民进党和李登辉强多了。

再说一下上面提到的第一点，台独越闹越凶，甚至要脚踩到了红线上，而老美也煞有声势的“反对”台独，这分明是在测试北京的红线到底在哪儿，战争的意志有多强，会不会在中东大乱[fn:1]之前发动收台之战。当然，它更希望北京在中东，在巴以和谈或者伊核问题上让步，但这是不可能的。

对面着老美和台独的双簧，北京用行动给出了答案，不仅决意不惜一战，甚至传出将台独分子定性为战犯的声音。当然，在这关键时刻，下面的新闻也许曹钢川出访日菲也许更能说明问题，北京决意提前切断任何企图干涉台海战事的军事力量。

#+LaTeX:\red{如果日本不参与，那么老美单干的可能性几乎为零。}下面是日本三位高官的表态:
#+HTML:<b>如果日本不参与，那么老美单干的可能性几乎为零。</b>下面是日本三位高官的表态:

高村表示，日方坚持在三个政治文件中表达的立场，不支持“台独”。安倍表示，日方坚持在《日中联合声明》[fn:4]中就台湾问题表明的立场，不支持任何单方面改变台海现状的言行。町村说，日方充分认识到台湾问题重要性，坚持在《日中联合声明》中的立场，不支持“台独”。

应该说，上面的表态中，唯一可能能让老美感觉满意的，就是安倍的表态了，他不支持中国动武嘛。但是，如果把三个人的话放在一起看的话，日本的态度很明朗，台海有战事，日本作壁上观。

为了近一步向北京示好，日本前防卫长官中谷元甚至表示“与其和其他国家建立‘自由与繁荣之弧’，不如处理好和中国的友好关系”。其实，金鸿早就在以前的评论安倍在印度提出四国联盟时提出过一个观点：四国联盟只是小日本为了应付老美的权利之计，就目前的局面而言，它纵有贼胆，也没那个贼能耐！当然，面对着小日本的乖巧，北京及时递上了一颗胡萝卜：

外交部网站消息，8月30日，中国外交部长杨洁篪[chí]应约与日本外相町村信孝通电话，双方同意继续积极务实推进东海磋商进程。

既然中国人都这么抬举日本人，安倍当在有资本继续在老美面前大玩强势外交了。

当然，小日本的野心永远是不容低估的，日本防卫省10日时就已经决定在下一财政年度中申请预算，开发自己的新一代隐身战斗机。小日本想造战机，早就不是什么新闻，只不过金鸿有个疑问，
#+LaTeX:\red{没有风洞你怎么造？}这不是上坟烧卫生纸----糊弄鬼吗？
#+HTML:<b>没有风洞你怎么造？</b>这不是上坟烧卫生纸----糊弄鬼吗？

造飞机就不要指望了。建议你们还是以“打飞机”为主，谁叫你们是“自卫队”呢？自卫一下就可以了，只要你们够乖巧，没人骚扰你们。


全球局势就是这么有意思，局势升温将至沸点的，不光是台海，还有伊核，一起来看几条新闻摘要：

德黑兰８月２８日消息：伊朗总统艾哈迈迪－内贾德２８日说，伊朗已经是一个“核国家”，将继续推行其和平利用核能的计划。

布什周二(28日)形容伊朗发展核技术使中东地区"笼罩在核武器种族大屠杀的阴影之下"。

伊朗驻国际原子能机构（ＩＡＥＡ）[fn:5]代表阿里·阿什加尔·绍尔坦尼２９日说，如果联合国对伊朗实行制裁，伊朗将停止与ＩＡＥＡ的合作。

维也纳8月30日电（记者宋国城）国际原子能机构总干事巴拉迪30日在提交该机构理事国的一份内部报告中认为，伊朗在与国际原子能机构合作澄清其核计划中悬而未决问题方面取得进展。

首先来看两个名词：第一个，伊朗说自己是“核国家”，不是指拥有核武器的国家，而是一个拥有完整核燃料循环体系的“核国家”。第二个，"笼罩在核武器种族大屠杀的阴影之下"，以金鸿的眼光看，这是小布什在威胁对伊朗进行核攻击。

我们回头再来看看萨克奇的对伊朗的那条警告：要么拥有核武器，要么被毁灭。说的多么的及时，多么的精准。事到如今，如果还有人告诉小布什，说萨仁兄和默科尔是亲美的，恐怕你就是打折了小布什的腿，他也不会信，也不敢信了。

在前几次的前评中，金鸿一直坚持一个观点，在核问题上，伊朗绝对是吃软不吃硬的，而且，伊朗现在正在等老美送一个可以吃到嘴里的个头又够大的胡萝卜。而老美呢，坚决不给，结果，局势越弄越坏，在小布什的核讹诈都弄出来的情况下，伊朗居然要对伊核问题“不谈了”，要停止与IAEA合作。

这时候，笑话又出来了，巴拉边居然站出来说，伊核问题是有进展的，伊朗是有诚意的，前几天小布什可是刚刚说了伊朗在核谈判上一直在拖延。看来，拆他台的不止一家人。

既然老内有胆量把“核国家”这个词捅出来，如果老美再不软化一下立场，也许下一次老内再说自己是“核国家”的时候，恐怕就不是“拥有完整核燃料循环体系”的“核国家”了，而是“拥有核武器”的“核国家”了，那时，老美又能奈何？

#+LaTeX:\blue{如同老美一直在用台独挑衅北京的底线一下，伊朗同样也在挑衅着老美的底线，}只是不知道，在这场意志的对决中，谁会最先撑不住？
#+HTML:<b>如同老美一直在用台独挑衅北京的底线一下，伊朗同样也在挑衅着老美的底线，</b>只是不知道，在这场意志的对决中，谁会最先撑不住？

几个月来，老金是要风得风要雨得雨，可老内天天顶着挨揍的风险在一线死撑，既然兄弟们都是为了实现和谐地区的，那就该有福同享有难同当，所以，近期，老金一再出来放话，朝核随时会崩。为了防止两条战线作战，老美继续向老金示好：

在前往日内瓦参加美朝双边工作组第二轮会谈前，美国助理国务卿、朝核问题六方会谈美国代表团团长希尔8月29日暗示，不排除在朝鲜完全放弃核计划之前将其从“支持恐怖主义国家”名单中删除的可能性。

这也叫萝卜？“支持恐怖主义国家”是你们老美给人家封的，俺金鸿一直认为，老金是个不折不扣的共产主义战士，一颗红心向太阳，时刻准备为共产主义献身。

你给戴上的帽子再摘下来就想哄住个大活人？可笑。

接下来会出现什么？恐怕只有天知道了。家里被淹了，脾气很差，喝个酒闹个事也是人之常情。

** 【奋进社/金鸿95】峰回路转时

[2007-09-0312:10:49]

先来看一条来自塔利班的消息：

塔利班发言人艾哈迈迪当地时间2日晚间在接受媒体采访时表示，由于韩国未遵守撤侨承诺，所以韩国驻喀布尔使馆等所有与韩国相关的设施都可能因此受到攻击。

记得31日塔利班发言人艾哈迈迪曾表示：“此次绑架是进行圣战的塔利班战士的伟大胜利。我们认识到这种方法(绑架)很成功，因此今后我们将对阿富汗政府的其他友邦继续采用这种手段。”现在问题出来了：

应该说，人质事件塔利班是大有收获的，塔利班完全可以继续以抓人质的方式威胁在阿驻军的美国各盟国，达到逼他们撤军进而最终逼美国撤军的目的。可是，你要抓人要抓吧，为什么一再的公开威胁呢？这样各国不是都有防备吗？如此一来，抓人质的难度将大为增加，这又是何苦呢？又是何必呢？这解开这个谜，我们要放眼中东中亚与东亚的大环境来看。首先看两条伊核方面的消息：

据英国《星期日泰晤士报》报道，美国的一名国家安全专家近日表示，美国国防部目前已经拟定了针对伊朗的“三天闪电作战计划”，该计划首次明确的规定，一旦战争危机爆发，美国将用三天时间彻底摧毁伊朗的军事实力。

据伊朗国家电视台１日报道，伊朗最高领袖哈梅内伊任命贾法里准将为伊斯兰革命卫队总司令，原卫队总司令萨法维少将将担任最高领袖的高级军事顾问。

从老美的前特工（非官方身份）透露出美国将在六个月内打击伊朗，到今天一名国家安全专家表示老美要三天搞定伊朗，老美对伊朗发出的动武信号可以说是越来越强烈，大有黑云压城城欲摧之势。

面对着如此严峻的形势，老内也没闲着，这个人事调动的公布，可以看出伊朗已经做好了充分的战争准备，并且老内专门给自己弄了个军事顾问天天“顾问”以备不豫。

其实，为了保护伊朗，中俄通过和平使命2007军演、北京力保巴铁通道的畅通、俄罗斯力图打通格鲁吉亚通道、俄轰炸机巡逻关岛等一系列的行动，已经将自己的战争意志清楚的表达了出来。当然，与此同时，同样关心伊朗安全的某些同志也弄了点动静出来，一起看一下：

萨科齐27日在法国使节会议上就法国的中东及伊拉克政策进行了阐述,提出美国应该制定从伊拉克撤军时间表的主张。

英国前陆军参谋长、直接参与２００３年英美联军出兵伊拉克决策过程的迈克·杰克逊，在即将出版的自传中以激烈言辞“炮轰”驻伊美军和美国前国防部长唐纳德·拉姆斯菲尔德。杰克逊说，拉姆斯菲尔德在伊战中的决策“纯属脑子进水”。

表面上看，英法都是冲着老美的伊拉克政策来的。（英国人批拉氏批的有意思，一是一点面子没给留，二是弄了个前陆军前谋长出来，这也是没办法的事，布朗几天前刚刚说英国人在伊拉克还有活干，不能撤干净，没办法，不给美国人面子不能不给自己首相面子。）但是，我们不妨从另一个角度想一下这个问题。

中俄欧都希望把老美从老大的位了上抬下来，自己好有机会上位。在这个小算盘下，让老美在伊拉克拖瘦进而拖垮最符合中俄欧三方的利益。在这样的背景下，让老美撤兵不是上策。大国领袖们都不是傻瓜，他们为什么要这么做呢？显然，他们是另有所图。

我们再设想另一种情况：如果老美从伊拉克撤兵了，那么，会出现什么？

很显然，离开了伊拉克这个支点，老美想打击伊朗就变成了难度极大而且是没必要的事情。说没必要，很简单，就算打成功了有什么用？没有了伊拉克的驻军，如果控制伊朗？被打烦了的波斯人对美国佬还不恨的牙根都痒痒？结果不是更反美？

综合上面的一点分析，金鸿得出这么个结论：
#+HTML:<b>英法二国抨击老美的伊拉克政策，是为了表明自己坚决反对老美打击伊朗的。</b>
#+LaTex:\green{英法二国抨击老美的伊拉克政策，是为了表明自己坚决反对老美打击伊朗的。}

有了这么多帮忙的，老内自然底气十足，看下面伊朗方面的动作：

伊朗外交部发言人侯赛尼2日在每周例行的新闻发布会上警告联合国安理会不要出台制裁伊朗的新措施，否则伊朗将重新审视与国际原子能机构的合作。伊朗与国际原子能机构的合作将继续下去，但如果安理会出台制裁伊朗的新决议，那我们就会重新审视与国际原子能机构的合作，同时还会考虑解决伊朗核问题的新途径。但侯赛尼并没有明确说明这一“新途径”是什么。

伊朗总统艾哈迈迪－内贾德２日说，伊朗目前已将３０００多台用于生产浓缩铀的离心机投入运作，而且离心机数量仍在不断增加。

大家都会造名词：伊朗又搞出个“新途径”，什么新途径？看看老肉搞的更多的离心机干什么用就知道了。几个月前老内就宣布过伊朗已生产出100公斤的浓缩铀（如果数量没记错，应该是这么多）。100公斤造一颗原子弹还不大够，再加点量就够了，这不，内监工正在扩大生产呢。

如果老美还抡大棒的话，接下来老内恐怕真要宣布拥有核武器了。

#+HTML:<b>当然，老美对伊朗有打击能力，但是，老美可是要准备付出代价的</b>：
#+LaTex:\red{当然，老美对伊朗有打击能力，但是，老美可是要准备付出代价的}:

一、伊朗被打的有多狠，以色列被炸的就有多惨。以前的中东战争，都是以色列赢的，可是，在那历次的战争中，并没有一个军事大国真正在去帮过阿拉伯世界。只要有那个军事大国诚主诚意的使点儿劲，想叫以色列这样的小国家变为平地不是什么难事，谁叫它那么小呢？

二、驻伊拉克美军肯定会遭到大规模的袭击，那时反美武装肯定是鸟枪换炮的，当然，阿富汗也一样。

三、波斯湾上的美军舰艇能有几艘不被打沉？有兴趣的可以猜一下。

这只是伊朗单方面还手的一个可能结果，如果有人再在旁边拉拉偏架呢？

现在我们重新看一下塔利班对韩国的威胁：

金鸿在人质事件发生后不久写过一篇〈金鸿时评（13/8）地球村里小人物的大智慧〉，文章中提出了金鸿的一个观点：塔利班是在人质事件中是受过高人指点的。后来人质事件的发展大家都看到了,基本上得到了验证.看了家族兄的新文章〈超度2〉，对塔利班的认识又深入了一层：塔利班只是老美的叫法，他们应该叫做
#+HTML:<b>阿富汗抵抗组织</b>
#+LaTeX:\red{阿富汗抵抗组织}
，这些组织并不是一个组织，就象啸聚山林的山大王，有的是杀人越货的，有的是杀富济贫的，也有的也许就是红色割据。当然,这些统称为阿富汗抵抗组织的组织,
#+HTML:<b>背景各异</b>
#+LaTeX:\red{背景各异}
,呵呵。

如果他们只想抓人质的话，大可不必出来一再的放风。因为抓人质并不件容易事，毕竟，在阿富汗，老美的军事实力是绝对不容低估的。在老美眼皮子底下抓他盟友的人，肯定不是简单的事。

很显然，抓人并不是主要目的。

我们不妨这样理解：如果有人硬要武力收拾
#+HTML:<b>伊朗</b>
#+LaTeX:\red{伊朗}
或者
#+HTML:<b>叙利亚</b>
#+LaTeX:\red{叙利亚}
，那么同样有人会不甘寂寞，主动出来先解决
#+HTML:<b>阿富汗问题</b>
#+LaTeX:\red{阿富汗问题}
。老美费了千辛万苦才楔下的这颗中亚钢钉就会在一夜之间被连根拔掉！当然，中东方面该怎么出手怎么出手，这玩艺不是怎么费劲的事。

把老美赶出中亚，有人是不怎么高兴的，我们看一下默克尔访日时的一个小消息就能明白：

德国总理默克尔在访问日本期间呼吁东京继续支援以美国为首的联军在阿富汗的行动，但日本主要反对党的领导人拒绝接受这项呼吁。

都说天下没有免费的午餐，可德法的确弄了一份免费的午餐[fn:6]。搭着老美兵进阿富汗的便车，德法的军事实力也到达了中亚；同样，搭着与中俄政治上合作的便车，德法的军事实力在中亚有了低成本的存在。说低成本，主要是相对于驻阿美军天天死人而言的，不信可以查查每月在阿被干掉的士兵中有几个是德国兵法国兵。如果不是沾了中俄的光，他们也得天天见血----在中东对付老美方面，中俄法德是统一战线的，中法德的经济、技术合作又十分密切，俄法德的能源合作也是潜力无限。

默克尔呼吁东京支援驻阿联军，不是为了老美，是为了给自己多一份国际布局的筹码而已。现在韩国兵要撤，如果日本再不支持，塔利班继续见了外国人就绑，鬼知道老美还能在阿富汗撑几天，如果老美撤了，这张餐桌就被抽掉了。那时，免费的午餐去哪儿找呢？

当然了，想吃这份美餐也不难，北约内部沟通一下，让你们的美大哥对内贾德老兄温柔一点，再温柔一点。


** 【奋进社/金鸿95】亮剑

[2007-09-1521:32:37]

朝核局面刚刚稳住，伊核又要突破，老美正摁不下去急吼吼的喊打，现在又闹出了个
#+HTML:<b>叙核</b>
#+LaTeX:\red{叙核}
，一起看三条新闻摘要：

美国国防部的一位官员12日称，以色列情报机构日前侦察到叙利亚正在秘密安装核设施，这些核设施很可能得到了伊朗方面的帮助。以色列媒体也报道说，以色列上周曾出动军机对叙利亚的这些疑似核设施进行了轰炸。

据《华盛顿邮报》报导，根据美国在过去6个月搜集到的新情报，朝鲜可能正与叙利亚在叙国境内合建某种核子设施。据悉，相关证据主要是由以色列方面提供，其中包括清晰的人造卫星影像，让美国官员相信这个设施可能用来生产核子武器所需的材料。

美国国务院的高级官员14日称，目前有种种迹象显示叙利亚正在从事与研发核武器相关的工作，美国已经将叙利亚列入到全球核研发监控名单。


最近三天来，美国一直单方面连续的曝光叙利亚搞核研究。这个消息究竟是真是假呢？

如果消息是假的，那么，显然美以是为准备对
#+HTML:<b>叶什派</b>
#+LaTeX:\red{叶什派}
的叙利亚动手找借口，以发动战争打垮叙利亚。为了保护叙利亚，不论是叙利亚自己，还是伊朗，或者是俄罗斯、法德，都可以出来为叙利亚辩护一两句。可奇怪的是，连续三天来，除了美国和以色列在那里一唱一合，中俄欧、阿盟、伊朗、叙利亚、朝鲜等方，没有一个吱声的，各人忙各人的，好象什么事都没发生一样。

此一点可以证明：
#+HTML:<b>叙利亚玩核是真的</b>
#+LaTeX:\red{}叙利亚玩核是真的}
。而本文正是基于此一点展开的，当然，如果出现了误判，则本文所写的都不再成立。为谨慎起见，金鸿连续三天都在紧盯与此事相关的新闻，只是一直没有发现除美以外任何一方反应的新闻，只好先写了。

叙利亚玩核的胆子是谁给的？从上面新闻看，叙利亚的核设施是得到了伊朗或者朝鲜的支持。无论是伊朗，还是朝鲜，背后都有同一个国家在支持。很显然，这一回，又有人玩大的了。我们从几个不同的角度来看一下：

伊核局势日趋白热化，美国连连喊打，逼得英法德几乎都要跟它翻脸了。在这种情况下，朝鲜在东亚方面弄出点动静来，是对伊朗最大的策应，这也是金鸿近半个月来的时评中屡次认为朝鲜应该动作一下的原因。

结果，出乎意料的是，朝核局势越来越平稳。而叙利亚方面却传来了与朝鲜帮助建造核设施的消息。这样一来，一举两得：朝核稳定了，朝鲜本身从美国那里大收美元[fn:7]，韩国也乐意看到半岛局势的平稳。如果仅仅为了策应伊朗就让朝鲜一再的出来搅局，则容易让韩国对北京离心。

当然了，如果美国为了逼中国压伊朗在核问题上让步，而再三的让台独往高了跳触到了红线，北京动了手，进而把整个东亚都拉进危局，那时，韩国只有恨美国的份，却没有理由找北京的茬。接下来，美国在东亚将更为被动----美韩同盟的裂痕将撕扯的更大！

美国为了自己的利益，可以让以色列有核，可以让印度有核。让以色列有核，是为了保持以色列在中东的绝对军事优势；让印度有核，是为了从战略上牵制、威胁中国。没办法，为了平衡影响，只好让巴基斯坦也成了核国家。美国为了阻碍东北亚经济一体化，在东北亚埋钉子，拿着朝鲜的核问题大做文章；即然你们美国人拿朝鲜核问题当牌打，那就让朝鲜核问题真正变成核问题好了，结果，朝鲜一核爆，问题倒没了。

再说伊核，当初哈梅内伊主政伊朗之前，美国人可是支持伊核搞铀浓缩的，可伊朗变了天，美国也变了脸。为了石油，美国人要拿下伊朗，最好的动武理由自然也是核问题。只是没想到，当美国人挽好了袖子准备动手的时候，却发现中俄欧全部变成了伊朗的保护神。美国人用尽心机企图对伊朗先封锁拖垮、再动手打残的办法迟迟无法在联合国通过，当然，这也是不可能通过的，一再的找机会对伊朗动武。

在这最关键的时候，叙利亚搞起了核研究。且不说美国人打伊朗的结果如何，就是打赢了，中东就无核了吗？是不是再把叙利亚打垮？委内瑞拉的查维斯对原子弹那可也是望眼欲穿，说不定过不了几天，委内瑞拉也有核了，是不是再打？面对着核研究遍地开花之势，美国人的坚船利炮又能阻止多少呢？如果动不起这个手，在叶什派国家都能玩核的情况下，
#+HTML:<b>亲美的逊尼派</b>
#+LaTeX:\red{亲美的逊尼派}
能沉的住气？他们是不是也向美国人要玩核的申请书呢？如果整个中东都玩起了核，那犹太人不搬家又将如何在中东生存？

美国为了自己的利益，一再对中国的核心利益台湾下手，现在，北京在中东----美国的核心利益地带上出手，更容易让美国感觉到什么是真正的痛苦。正所谓“已所不欲，勿施于人”，如果你们美国人受不了，也就不要为难我们中国人。要交换？把台湾给我送回来！

近来，台独闹的厉害，中央却没有出手，相当多的人就认为我们的中央太软弱。
#+HTML:<b>其实，中国，从建国以来就没有软弱过</b>。
#+LaTeX:\red{其实，中国，从建国以来就没有软弱过}。
中国是个不轻易言战的国家，但是，言战必打，打则必胜。只有那些半瓶醋，才整天把打打打放在嘴边上。

再想想近两年来，出现的一系列的不大不小的事情，如果谁有兴趣，可以去问一下被朝鲜导弹问候过的日本人、被朝鲜核爆震醒了的美国人、越境打击真主党失败了的以色列人、抓过英国水兵的伊朗人、被阿富汗绑架过人质的韩国人，中国到底软不软？

为什么朝鲜那么蛮横？为什么伊朗那么强悍？为什么巴基斯坦那么坚定？为什么新家坡那么老实？为什么希拉克说法国的明天取决于中国？为什么普京说未来中俄关系不变？为什么布什说胡主席是个聪明人？为什么在台独闹的最凶的今天整个阿盟站出来强调支持一个中国？

今天,我们已经从“韬光养晦”走向了“有所作为”，这一切，感谢胡总

** 【奋进社/金鸿95】纸老虎现形记

[2007-09-1820:11:17]

先来看三条来伊核危机的新闻摘要：

德国上周向它的盟友表示，默克尔政府拒绝支持联合国安理会可能对伊朗实施的进一步制裁。德国将退出针对伊朗的联合外交攻势，这是包括国务院、国家安全委员会、总统办公室、副总统办公室等美国相关机构和部门达成的最新共识。负责政治事务的副国务卿尼古拉斯·伯恩斯是通过外交途径解决伊朗核问题的最坚决拥护者。他已经得到过机会，但却一无所获。

英国《星期日每日电讯报》16日报道说，五角大楼和中央情报局官员说，他们相信，白宫已经启动了精心设计的局势升级计划，逐步与伊朗进行军事摊牌。一名美国国务院官员透露，一直努力争取外交解决伊朗核问题的国务卿赖斯也在改变立场，准备与切尼弥合分歧，同意采取军事行动。赖斯的底线是如果美国政府准备开战，必须进行数月的造势，赢得国会的充分支持，否则她将挂冠而去。而布什则私下向她承诺，在对伊朗采取任何军事行动之前，他将与国会领导人进行协商。

为了研究空袭伊朗带来的后果到底如何，美国一个具有保守倾向的基金会组织了来自五角大楼、国务院、国土安全部以及能源部的专家，进行了4个月的模拟试验。在试验中，美国军队对伊朗进行空中打击；作为报复，伊朗封锁了波斯湾石油通往世界各地的海上通道———霍尔木兹海峡。计算机模拟显示，伊朗封锁霍尔木兹海峡将使世界石油价格增长1倍，美国国民生产总值将在一个季度内下降1610亿美元，并导致全国100万人失业。

法国外交部长库什内9月16日表示，国际社会应该准备接受一场因伊朗核危机而造成的战争，但寻求对话解决方案仍应该是目前首选。库什内称伊朗核问题僵局是现阶段“最大危机”，“我们无法接受伊朗造出核弹”。他暗示，有关的军事打击计划拟定工作正在进行当中。他说：“军事参谋长们已在准备相关计划。虽然战争不会很快发生，但我们必须为任何不测制定计划。”

从表面上看，与德国人的撂挑子相比，法国人的制裁建议就是蛮趁老美的心意。不过，如果有人认为这是真的，那就太天真了。估计老美看到法国人露着笑脸提出的建议时，肯定在心里骂：“你们这些东西又在联合起来消遣老子了。”

在这场震憾世界的油桶争夺战中，中俄欧是三家联手，众志成城（当然，意大利的普罗迪和日本的安倍也在削尖了脑袋往里挤，只是没挤进来）。而“欧”，指的是法德英，这三家充分利用人多的优势，充当着油光水滑的中间人的角色，三家轮翻上阵，你方唱罢我登场，忙的是不亦乐乎。

前几天，先由德国人唱黑脸，把伊核危机贴上“失控”的标签转手就扔给了美国人，这还不够，还坚持反对对伊朗加大制裁力度。连盟友都公然造反，搞的老美好不尴尬。时隔几日，法国人登场了，本着打一巴掌揉三下的基本原则，法国人拼命往自己脸上擦红胭脂，俨然成了老美战壕里的忠诚战友----人家法国人也是出了血本的，自己家企业的都不让去伊朗合作了，得赔多少钱呀？美国人是不是得给点儿补偿呀？

其实，这只是表面现象，请大家注意一下法国人的一句话“但我们必须为任何不测制定计划”，难道需要做最坏打算的仅仅是法国人吗？美国人为了打伊朗打算少收1610亿美元，那么，一旦动起手来，油价飞到200美元/桶，其他的依靠进口石油过日子的国家都打算付出什么代价？而这一切，可都是老美对伊朗动手造成的！法国人在大喇叭里这么向全世界发警报，难道所有“不想经济上大出血”的国家不该向老美施压吗？难道不该动用一切手段劝老美大人有大量、不要和小小的伊朗一般见识吗？难道所有“爱好和平”的国家不该要求老美放下屠刀、立地成佛吗？

接下来，在全世界的努力之后，是不是老美又该回到法国人上面提出的“寻求对话解决方案仍应该是目前首选”老路上了？

当然，老美是真够嘴硬的，这已经是第N次发风要打伊朗了，相信在不久的将来，我们还能看到美国人第N+M次声称收拾波斯人。只不过，在大家的耳朵都听出了老茧后，也就都不当回事了。

更何况，打伊朗光“造势”就要准备几个月。几个月后是什么样子？只有耶和华最清楚。一年前，朝鲜核试爆后，老美钢牙咬碎后宣布：“如果朝鲜搞核扩散，美国将立即进行武力打击”。前几天，大家都看到了，朝鲜已经对叙利亚提供过核帮助了，不知道美国人是不是因为贵人多忘事忘了这个茬了？在此，提醒美国人一声：“该打朝鲜了！”

接下来，还是再看一下大家最关注的台海方面的新闻摘要吧：

英国《简氏防务周刊》9月19日(提前出版)一期报道题：中国商级潜艇（093）详细情况浮出水面。

女足世界杯17日拉开了A组小组赛最后一轮,日本队赛后全体球员举起了事先准备好的一条横幅，上面写着：“谢谢中国！”她们的这个举动也赢得了全场球迷的热烈掌声。

最新一期香港《亚洲周刊》刊出对日本前防卫厅长官中谷元的专访，在访问中，中谷元针对处于战略转变期的中日军事关系如何加强对话交流﹑日本在台海有事中的对策和日美导弹防御体系开发现状等问题畅抒己见。

台湾问题涉及到中国核心利益，有关台湾海峡的安全稳定，对日本来说也是非常重要的。万一台海有事，日本怎么办？

台湾问题是中国国内问题，应由中国自己来解决。但是，我认为不应该使用武力、武装冲突的方法来解决。万一台海有事，美国是否会使用武力来协防台湾我不清楚，但如果会的话就会产生军事纷争，如果这对日本也有很大影响的话，日本就会自动成为美国的后方支持。因为日本与美国之间有军事同盟关系，日本有义务为美军提供后方支持活动。当然，台湾问题究竟如何解决，现在谁也不知道，所以我也不能作出断言：台海一定有事。

在这台海之上风高浪急的时候，093曝光意味着什么，恐怕不需要多解释什么了。倒是日本的表现很有意思。

今天中午在QQ群里和几个网友聊天，有人发了日本“感谢中国”的新闻后，我说：“这是日本昨天在为今天（九一八）做功课呢。”有朋友就说我“什么都和政治挂钩”。其实，这也是没办法的事，小日本在这方面是有前科的：前段时间在日本搞的中日蓝球对抗赛上，日本主办方可是为中国队放的中华民国国歌。即然日本人工于此道，我们不能不多个心眼。

接着上面的内容分析，几天前，中国在叙利亚进行过了一次核摊牌的暗示，结果，全世界都没有动静。很明显，除了老美小以[外]，其他人都站在了中国这一边。这样的一个结果，不得不让日本人自己琢磨一下，站在中国人对面、和中国人在台海顶着上的代价是什么？很简单：要么被美国人玩傻，要么被中国人打傻。

所以，小日本软了。看看里面的一句话“日本就会自动成为美国的后方支持”，日本的表态很直白：一旦中国打开了平台之战，美国如果协防台湾，日本会支持美国；如果老美不动手，日本也就省事了。

的确，一旦中国解放了台湾，那么日本人南下的海上通道就落到了中国人手里，确实是危险大增。不过，日本人也想通了：中国不卡他美国人不也卡他吗？一个爹也是叫，两个爹也是喊，没什么大不了的。

老美挑动台独踩红线，目的不外乎是让中国先动手解决台湾问题，自己把日本忽悠进战场，它在背后支持；然后，再在俄罗斯家门口点几把火、牵制住老熊，接下来它就可以轻松的对付伊朗了----英法德的军事力量到达不了中东，只有瞪着眼看的份。

但是，如果老美挑起了中国的平台之战，日本人不插手，那就相当于美国人把台湾白送给中国了。面对着北京的泰山压顶，台湾自己哪有抗拒之力？

老美是没有任何胆量为了台湾和中国单独干一仗的，除非它不想混了。打伊朗它打算付出“100万人失业”的代价，好象是大本钱似的，如果跟中国干，这不叫代价嘛，最少也得让它失业2000万人。不客气的讲，今天，中国人有了玩烂地球的能力！

希望五角大楼不要再追着中国要什么“中国不首先使用核武器”的承诺了，承诺有用吗？你们美国人对我们中国的承诺什么时候兑现过了？如果你们说人话办人事，那么我们绝对一诺千金！

当然，如果真动起手了，把美元储备全扔了、提前埋葬美元的全球霸权地位也不是什么新鲜事。不知道哪个美国总统能付的起这个代价？恐怕他长十个脑袋也不够人砍的！

所以，接下来，老美肯定会在伊核问题上软化，再软化。当然，到目前为止，还没有美国的消息，不过，伊朗方面到是有趣闻传了过来：

伊朗总统
#+HTML:<b>马哈茂德·艾哈迈迪—内贾德</b>
#+LaTeX:\red{马哈茂德·艾哈迈迪—内贾德}
16日再度挑战美国总统乔治·W·布什。艾哈迈迪—内贾德提出在本月召开的联合国大会上与布什公开辩论，并提议举行一次“全球公投”来确定包括伊拉克战争在内的国际问题解决方案。

前几天美国人不是口口声声要找“通情达理”的伊朗人谈判吗？现在老内要在联合国与布什先生公开辩论，这叫不叫“通情达理”呀？全世界人民都来当裁判，这叫不叫“民主”呀？

布什先生，接招吧？

** 【奋进社/金鸿95】对流行乐坛的一点看法

[2007-09-2222:00:31]

跟大家聊一点国内方面的东西：

广电总局对选秀类节目下了重手了，相信让许多朋友都感觉很高兴。的确，这股风该刹。那些有功夫整天参加选秀的俊男美女们去背背《三字经》也比整天在电视上瞎折腾强呀，也省得把我们的下一代叫唆坏了-----个个都想一夜成名、日进斗金，浮燥！

其实，要整的地方还很多：比如个别媒体和娱乐圈。

先说说流行乐坛吧：别的先不提，光看看那些乱七八糟的歌曲的名字，就够让人头大的：

《狼爱上羊》《狐狸爱上熊》：作者这是出于什么考虑呢？是想众生平等吗？就算平等也不能这么乱点鸳鸯谱呀？这不串种了吗？一头大公熊爱上了一只母狐狸，那母狐狸受的吗？至于狼爱上羊，就更有意思了，据所我知，狼爱上的，是羊肉。作者怀疑一切、颠覆一切、为了吸引众人眼球不惜一切的本事真让人不得不服。

《香水有毒》。里面最经典的歌词：你身上有她的香水味，是我鼻子犯的罪，不该嗅到她的美，檫掉一切陪你睡。第一次听到这首词的时候，唯一的感觉就是，这个女人没骨气（要是有人说她贱、我也不会意见）。当然了，花心的男人也许喜欢自己的女人有这样的胸怀。

《苍蝇的眼泪》：看看这个名字真叫人感觉不知所云！

《死了都要爱》：情圣！情痴！千万别在移情别恋的时候被人抓了呀。

《找不找北》：爱人家爱的找不着北？那还能不能找的到嘴呢？

《爱你不是两三天》：是四五天吗？

《算你狠》：你更狠。

《杀了她喂猪》：杀了你喂猪！

……..

这只是随便举了几个例子。今天的中国，确实开放了，也确实自由了。但是，开放、自由得有个度呀，这么折腾下去，还得了？

很显然，有人知道通过武力颠覆我们的国家、将我们大卸八块办不到，就在文化上打主意：用尽一切办法冲击我们传统的道德底线、淡化我们的民族本性，用“温水煮青蛙”的办法搞垮一个伟大的国家。上面的，只是冰山一角。

的确，我们今天要学习西方许多先进的东西，但是，我们民族的精华不能扔了呀？我们要泼掉的是洗澡水，总不能把里面的孩子一块泼了吧？没有了民族性，哪有世界性？

崇尚先进的的科学技术是人类的共性。记得以前我曾经看到一本智力推理书的时候，上面讲过这么一段话：在欧洲，智力推理曾风行欧洲大陆，在他们的推理题中有两个基本的出题要求：一是题目中没有出现的条件不能作为推理结果的根据（常识除外），二是不能在题目中出现中国人。这第一个要求无可非议，第二个也许大家就感觉摸不着头脑了。因为那时的欧洲远没有中国发达，所以，那时的欧洲人对东方文明搞不懂，以至于认为中国人会魔法，所以，如果题目中有了中国人，什么不可能的事就都可能了（比如，西方人搞不明白，为什么一个虫子吐出的丝能做成那么漂亮的衣服----丝稠）。

我无意夸耀中华民族曾经的辉煌（甚至我更以今天的落后为耻辱），在这里只是想向大家展示一个道理：
#+HTML:<b>千万不要因为“一俊”就把“百丑”也当成了“百俊”。</b>
#+LaTeX:\red{千万不要因为“一俊”就把“百丑”也当成了“百俊”。}

我们要学习西方先进的科学技术和管理经验，但我们不能没有了自信，更不能拿着黄鼬当马骑。许多事实证明，我们的研发能力不比西方差，差的是自信心！差的是我们的“让优秀人才脱颖而出”的机制还不够好、不够完善。西方的许多管理经验的确不错，但来到中国，水土不服也属正常，因为那些东西本身就是为西方人的民族性量身定做的----我们可是中国人！所以，我们要辩证的吸收。

在这个改革开放的年代里，我们绝不能在“向西方先进国家学习”的过程中丢失了自己的文化，如果真这样的话，那我们将得不偿失！

文化有多重要？对一个国家、一个社会的重要性我们先不提，先以企业文化为例说一说文化的重要性吧。

企业文化是个比较时髦的词，也被某些人宣扬的神乎其神，以至于随便个公司都在大讲自己的“企业文化”，这个好象大可不必。其实，只有当一个企业销售额达到百亿级别时企业文化还做不好，企业发展才会卡壳，甚至垮掉。就我个人观点而言，可以用两个词语分别从不同的角度代表一下企业文化的含义：
#+HTML:<b>“老板意志”、“企业风气”。</b>
#+LaTeX:\red{“老板意志”、“企业风气”。}

“老板意志”：当一个公司只有几个人或者十几个人的时候，没必要要什么企业文化，只要老板高兴，一天可以围着公司转一百回。他可以随时把自己的意志贯彻到每一个员工的行动中。当企业做大了，比如上了百亿，下面的事业部、高级职能部门、分公司、子公司一大堆，老板再想转一遍，恐怕就是天天睡在飞机上一年也转不完一遍。这时，如果没有一种方式将老板的意志分形式、分部分、分阶段的灌输上全体员工的头脑当中，那么，公司的各部分很容易各行其是、最终把好好的家业内耗掉。

而对于小公司，企业文化不是不可或缺的东西，对小公司而言，金鸿的建议是在公司发展的不同阶段（可以用以销售额为代表的企业规模来进行划分、当然不同行业会有所区别），公司最高层有重点的加强对营销、管理、战略、研发等方面的特别关注与投入，把这些“分别”“全部”夯实、形成自己独特的竞争优势后再对企业文化下手也不晚----文化是一条串珍珠的链子，没它绝对不行，只有它却是远远不够的。

“企业风气”：不同的企业对员工的要求不一样，企业内的风气、员工的整体工作风格也不一样，而这一点往往与企业的行业特点、员工的民族性有关，这些都集中的体现在企业文化方面就是不同企业的文化千差万别。举个例子：微软的文化崇尚自由平等，上面盖茨下到普通程序员，每个员工的办公室都是11平，自己的办公室自己随便布置、以致于有人在自己的窝里玩起了大蟒蛇，上下班时间也比较自由、以完成任务为核心。但是沃尔玛就完全两样：一切规范到底，连微笑都搞出个“八颗牙”的标准。都是世界顶级优秀公司，文化差别不啻天壤。

微软的文化好不好？如果杨元庆把这一套弄到联想去、把柳传志的“斯巴达”方阵给破了，我敢打赌，柳老头非出来骂街不行！原因很简单，联想是搞硬件生产和组装的，首先要保证质量可靠，文化肯定要配套；微软强调创新，“人有多大胆、地有多大产”，气氛自由一点更有利于员工工作时展开想象的翅膀。企业文化还要兼顾民族性，举个例子：中国员工喜欢遇上“请示领导”、以示尊重；但如果一个日本员工随便去请示他的领导，对方一定会骂：“我白养你了！”

花了不少篇幅跟大家聊企业文化，只是为了说明这么一个道理：
#+HTML:<b>一个企业要想真正做大做强都离不开“文化”，一个国家就能离的开？</b>
#+LaTeX:\red{一个企业要想真正做大做强都离不开“文化”，一个国家就能离的开？}

对于民族文化，我也想从类似上面“企业文化”分的两个侧面那样展开一样：

一、与“老板意志”相对应的应该是“崇拜”。中华民族的一大优点，是没有一个强势的宗教统治过、统治的了过，所以，中国人基本上不怎么迷信，也不怎么象西方人那样一到礼拜就得去他们的“神灵”那里去说叨说叨自己这一周又犯了什么错儿，当然，也许今天忏悔完了明天接着犯（你想呀，哪个神有这么好的脾气一天听几亿人念检讨呀，不用说气呀，光累都累死了）。

没有崇拜也有两个坏处：一是没有“神灵”的监督，在独处的时候或者周围没有认识自己的人的时候，很容易犯错误。所以，在中国传统的读书人的个性修养中有一项修炼叫做“慎独”。二就是往往自以为自己是天下第一，无法无天。所以说，崇拜也有崇拜的好处。

而中国恰恰没有一个统一的“崇拜”。在日本，天皇是做为“活着的神”生存在日本人心目中的，“为天皇效忠”是拿命干的、不是耍嘴皮子的。那么，中国应该怎么做呢？

至少，我们应该把我们优秀的领袖人物(比如昨日的毛主席、今天的胡总)的意志贯彻下来(不必非要崇拜)，为实现民族的崛起而共同奋斗，在此过程中找个每个人的生活的乐趣。

二、社会风气：今天的社会风气差到了什么程度！？令人痛心疾首！如果经济发展要以道德的沦丧为代价，那我们宁可不发展！举个简单的例子：给你十个亿，让你住在一个到处是杀人、抢劫、诈骗、吸毒的小镇上，你愿意接受吗？恐怕就算你接受了，来不及享受那笔钱就到另一个世界去了。

社会风气的败坏与个别媒体的恶性误导直接相关！

现在流行歌曲有几首与“爱情”无关？可现在的离婚率有多高？高唱爱情歌曲唱得死去活来的，恰恰三天两头在男女关系上出问题！

现在的离婚率越来越高，与流行歌曲为代表的文化诱引因素有没有影响？恐怕只能用“必然”二字来回答。有人说离婚率高是社会文明进步的表现，这叫放屁！如果你身上的零件有十分之一出问题了，你还有勇气说自己更精神了吗？家庭是社会的基本单位（或者叫细胞），没有微观的家庭稳定，哪来的宏观的社会稳定？

现在的流行歌曲，许多可算的上是“靡靡之音”，要知道，“
#+HTML:<b>淫声亡国</b>
#+LaTeX:\red{淫声亡国}
”绝非虚言！如果谁说这些是老黄历，那只能说明他要么是不懂装懂、要么是别有用心！所以，对于流行乐坛上的这些乱七八糟的东西，有关部门该下死手了！特别需要关注的是，许多歌曲是从港台传出来的，这个口子更应该坚决堵死！

#+HTML:<b>用霹雳手段，显菩萨心肠！</b>
#+LaTeX:\red{用霹雳手段，显菩萨心肠！}


** 【奋进社/金鸿95】真实的谎言

[2007-09-2819:32:12]

联合国总部9月25日消息：美国总统布什25日称，愿意考虑扩大现有15个理事国的联合国安理会，而美国的亲密盟友日本会是成为安理会常任理事国成员的一个绝佳选择。

成为联合国常任理事国，对日本而言，绝对是一种无法拒绝的诱惑；同样，
#+HTML:<b>成为联合国常任理事国，对日本而言，永远是一个无法实现的梦想。</b>
#+LaTeX:\red{成为联合国常任理事国，对日本而言，永远是一个无法实现的梦想。}

今天，布什对日本发出了“成为联合国常任理事国”的支持，不知道大家作何感想？

套用美国人惯用的一句外交词令，“日本成为联合国常任理事国”绝对“不符合美国的利益”。可是，今天美国人硬是做了一件自挖墙角的事，这又是为什么呢？我们还是从小犬纯一狼说起吧：

对布什来说，无论是“玩”日本还是“用”日本最顺手的时候，就是小犬时代。小犬为了实现日本的帝国梦，全面委身于美国，希望以此取得美国人的信任、博得美国人的欢心，在钓鱼岛问题上和东海划界问题上全面支持自己。在美国的支持下，日本不惜于中国翻脸，甚至有意激起战事----当然，日本是希望在激起战事时美国人能参战从而使中美完全对立起来，自已借机摆脱美国人的控制，成为一个不受制于人的强大国家。但是，精明的美国人又岂会上日本人的当？在与中国全面交恶的时候，在小犬不惜出卖自己利益和东亚各国利益死抱美国人大腿的时候，美国人依然在不择手段的算计日本人；而在最需要美国人支持的东海划界问题、钓鱼岛问题上，美国人只是一再的诱引日本人去与中国翻身而使自己渔利，结果，在中国不惜一战的强势对抗下，日本人没有胆量也没有能力单独对抗一个强硬的北京。在经过了数年的努力后，日本人的帝国梦仍然只是一个帝国梦；既然死抱美国人大腿实现不了，调整方法就成为了必然，而调整方法的任务“历史性”的落在了安倍的肩上。

安倍是一个地地道道的军国主义者，他比小犬更“右”，他上台之台，全力支持小犬参拜靖国神厕、否认南京大屠杀、否认慰安妇、支持日本教育界修改教科书。就是这么一个右的不能再右的日本政客，一上台就来了个大变脸：不去靖国神厕以避免刺激北京，同时放风要与俄罗斯平分北方四岛以缓和日俄关系；再拿到了一个相对理想的日中、日俄关系后，再访欧盟“套利”----中俄都瞧的起他们日本人，欧盟是不是也该高看日本人一眼呀？在拿到了比较好用的来自中俄欧方面的几张牌后，安倍开始问布什开价了：希望我反华吗？希望我抗俄吗？好说，给个好价钱-----比如让日本加入伊核六方会谈、比如让日本插手巴以和谈，日本人绝对干。什么时候当主子的管不了狗了？恼羞成怒的美国人开始拿起“慰安妇”大棍疯狂的修理日本人-----大家不要认为美国人是真的关心什么“慰安妇”问题，这只不过是美国人敲打日本人的一个工具罢了，美国人这是用二战旧帐警告日本人：“小子，我才是你爹！”如果美国人正义感，为什么小犬一而再再而三的参拜供奉着二战甲级战犯（许多就是杀害过美国人的刽子手）靖国神厕、公然翻东京审判铁案时，美国人连个屁都不放？那些事情发生时，无论是北京，还是其他东亚国家，可是在对日本狠命的口诛笔伐！

安倍在台上的一年，正是布什在全球布局中极为艰难的一年。在这最需要日本人帮一把的时候，安倍却基本没怎么出手帮一帮布什-----也许这应该算是墙倒众人推吧。与此相反的是，安倍一再的对中国示好。他这么做，一方面是为了自抬身价在答应美国人出卖或者对付中国时能要个好价钱，另一方面，出于经济布局考虑，为了回归东亚经济一体化，它首先必须处理好与中国的关系。而这两方面，都是华盛顿无法接受的。

我们也可以看出来，
#+HTML:<b>日本从来就没有真心诚意的对待过我们中国人</b>
#+LaTeX:\red{日本从来就没有真心诚意的对待过我们中国人}
。他只[之]所以不敢在东海掀起战事，是因为北京的胳膊比东京的大腿还要粗！这么说，许多人可能不认可，甚至有人认为北京打不动东京。在此，我们可以分析一下这个问题：小犬时代，日本人也是喊着“有能力与北京在东海打一仗”的，它为什么不敢打？为什么安倍上台后就没人喊了？为什么自以为强大的不了的日本人面对前问候自己的朝鲜导弹的时候，连个诉苦的地方都没有？它甘心这样的情况出现吗？那它为什么不敢再叫嚣协防台湾呢？不是它不想，是它根本没这个实力！

今年年初，北京露了一手“弹道导弹打卫星”的绝活，不知道大家怎么看这一军事行为的含金量的。首先，被打下的风云1C卫星是800公里高变轨的卫星，仅此一点（打变轨飞行器），就是美国的TMD望尘莫及的。现代的海军战斗力，是建立在
#+HTML:<b>外层空间卫星监控技术引导下的导弹远距离精确打击和准确拦截</b>
#+LaTeX:\red{外层空间卫星监控技术引导下的导弹远距离精确打击和准确拦截}
能力之上的，而具备打卫星能力的国家，只有中俄美三国而已，一旦卫星被打掉，对手将变为瞎子，战争将变为一边倒的局面！日本一直对于自己的反潜技术十分自信，但是，在今天看来，面对是隐身水平一流的中国潜艇，日本人是没什么好办法的。一年前中国的一艘宋级潜艇戏耍美国小鹰号航母的事情，想必大家还记得吧。这只是举了两个例子而已，事实上，由于中国具有完整的军工体系，依赖于任何国家，虽然我们某些武器或装备落后一点，但是，打赢一场现代战争我们是有把握的。就整体实力而言，日本比起我们来，差远了！

现在安倍下台了，福田康夫上台，在他还没有上台之前，日本就传出了“台湾问题是中国内政、应该由中国人自己解决”的声音，再加上福田上台前就声称不再参拜靖国神厕，这些都是美国人最不愿意看到的。为了诱骗日本人重新回到对美国一边倒的小犬时代，这次，布什可下了血本了。

当然，他是寄希望于北京阻挠日本入常成功。

一旦日本入常成功了，那日本还需要美国人的保护吗？美国大兵是不是该撤出日本了？一个拥有“广泛而强大的国际影响力的”日本是不是该拥有航空母舰了？是不是该拥有核武器了？一旦日本入常成[功]，这一切将在三十年内变为现实。如此一来，一个美国全球最大的战略支点就消失了，一个强有力的全球竞争者就会出现，美国人会容忍这样的情况出现吗？恐怕你就是把布什团队全部枪毙了，他们也不会容忍这样的情况出现！

既然美国人想当好人，让北京当冤大头，那大家不妨玩玩：美国人都不怕把日本这个经济怪物放出来，我们中国人怕什么？如果美国人希望成事不足败事有余的日本人到联合国搅局的话，那就悉听尊便好了。

到目前为止，还没有看到来自北京方面的反对意见。很显然，北京在静观其变。我们不妨等等，再等等，相信在日本人入常的前脚迈入的一刹那，美国人会毫不客气的把日本人踹出来！那时，最支持日本人入常的美国人，就该显原形了。



** 【奋进社/金鸿95】漫漫无期弃核路

[2007-09-3019:44:20]

朝核六方会谈近三个月来，一直进展的不错，朝鲜大有弃核之势，许多朋友担心北京这是自废武功，其实，大可不必有此忧虑，朝鲜弃核是一件三五年内难有结果的事。只所以近期内有了较快的进展，与局势的发展有关。

六方会谈一再的出成果，与美国再三的让步直接挂钩。美国为了压下朝核，集中力量对付伊核，不得不再三对朝鲜让步，尽可能抬高朝鲜反脸的成本。当然，在此过程中，朝鲜、北京、俄罗斯都获利丰厚。

美国一方面在对朝鲜大幅让步的同时，却在过去的三个月内先后在巴基斯坦通道和伊朗国家安全上疯狂的施加压力。为此，巴基斯坦付出了巨大的代价，先是国内“恐怖分子”不断的搞爆炸，后是在国内大选问题上一再的恶心、刁难穆沙拉夫，不过，巴基斯坦坚强的撑了过去，我们没有任何理由不为此而对穆沙拉夫表示我们的敬意，当然，时至今日，穆沙拉夫连任已成定局。

在整整一个九月份，伊朗连续的顶住了美国两次的高强度连续性的战争威胁。一方面，得益于伊朗“置之死地而生、陷之亡地而后存”的战争意志；另一方面，得益于中俄的两次果断亮牌：第一次是中俄联手在阿富汗发出的警告（如果美国对伊朗下手，中俄必定收拾阿富汗美军、甚至捎带其他国家的部队），第二次是中国异常狠辣的叙利亚核摊牌，
#+HTML:<b>彻底打碎了美国武力打击伊朗的信心。</b>
#+LaTeX:\red{彻底打碎了美国武力打击伊朗的信心。}

今天，大家都看到了，美国开始强调依靠“谈判和制裁”来解决伊核问题----谈判可以，制裁没门。美国人愿意制裁也可以，中俄可要在伊朗发财了，至于英法德的选择，只是个面子问题，英法德不会完全跟着美国走的。与此相应的，台独也不怎么往高了跳、摸红线了（以我的个人眼光看，近几年平台[fn:8]不太符合北京的全球战略，
#+HTML:<b>平台将是北京拉开全球战略大反攻的序幕</b>
#+LaTeX:\red{平台将是北京拉开全球战略大反攻的序幕}
，现在，还不是全面反攻的时候，所以，北京“引而不发”的可能性更大一点，当然，也不排除被动收台的可能性，只怕美国不舍得把台独牌就这么扔了。所以，爱国的朋友们，最好不要再拿着“北京没用对台动武”就喊什么“北京太软弱”、“国将不国”。不谋全局者，不足以谋一域）。

美国一再在朝核让步，还有一个原因，就是
#+HTML:<b>警告</b>
#+LaTeX:\red{警告}
日本。一旦朝核谈妥了，那就意味着：朝美关系完全正常化了，朝鲜的国家安全不再受美国的威胁。半岛经济整合、东北亚经济一体化全面展开了，半岛彻底无核（包括韩国日本都不能有核）。这样一来，作为朝鲜死敌的日本只能独自面对着一个气势汹汹的朝鲜、一个心怀不满的韩国、一个笑里藏刀的中国、一个冷漠无情的俄罗斯了。在中俄美三家的全力压制之下，日本将被牢牢的定死在东北亚！一直渴望“承担更多全球责任”的日本人，也只能就此画地为牢了。

在过去的几个月里，安倍一直处处跟布什呛着干，搞的布什很不高兴，只好在用慰安妇问题声讨日本人之余，拿着六方会谈一再的出结果来警告日本：再不听话就永远关你禁闭！当然，一旦日本人有乖巧的表现时，美国就在六方会谈上弄点动静出来，让日本人感觉到六方会谈出结果是一百年后的事情，给日本人以无限的遐想空间。

六方会谈轻轻易易的出结果，也不符合中俄的战略利益。朝核是一张好牌，特别是在那个“长着一张什么话都敢说的大嘴”、又“什么都敢干”的金正日先生的全力配合下，朝鲜能干出什么样的、让美国人头大、让日本人恨的牙根子痒痒的事情，还真说不准！一张如此好的牌，通过一轮轮（每一轮又包括若干次）会谈可以拖个十年二十年甚至更长时间，来为中俄提供足够的时间和机会来一次次的大挖美国人的墙角、狂套美元，有心人怎么会轻易放弃？

在这个地球上，需要和美国人做交易的地方太多了，有我们望眼欲穿的
#+HTML:<b>巴以和谈、有利润丰厚的伊拉克重建，还有需要中国对付的台独牌、需要俄罗斯对付的中亚颜色革命国家，</b>
#+LaTeX:\red{巴以和谈、有利润丰厚的伊拉克重建，还有需要中国对付的台独牌、需要俄罗斯对付的中亚颜色革命国家，}
如果不从这里面狠狠的套出点东西来，怎么对得起这张近乎完美的好牌？谈判嘛，不就是斗嘴吗？我们有时间，我们更有耐心，慢慢沟通，肯定会有结果的。一万年太久，二十年足矣。

六方会谈真正谈出了结果，也绝对不符合美国人的“国家利益”。一旦谈妥了，朝美关系正常化了，朝鲜的国家安全有了彻底的保证（美国必须跟朝鲜缔结和平条约以保证不侵犯朝鲜），那么东北亚经济一体化必定全面落实，俄罗斯可以以此为跳板跳入东亚经济圈，摆脱美国对其的经济封锁；中国一方面整合东北亚经济、一方面整合东南亚经济，用整个东亚的经济一体化彻底砸烂美国主导的APEC[fn:9]（10+6就不要提了，纯粹是个怪胎，不可能有结果），从经济上挖空美国的势力范围（再拉欧洲、亲非洲、合中亚、联南美、抱中东，经济上布局全球，实现龙的飞腾）！在东亚经济一体化的强烈诱惑下，日本经济上出轨是必然的、韩国也会因为现实的经济利益而一再的与美国离心，我们就可以从经济上挖空美国在东亚的两个战略支点！美国的崩溃将在不远的将来变为现实！

朝核谈妥对美国人而言，绝对是一个恶梦。美国人也不是傻子，他们不会看不到这一点，所以，只要有机会，他们肯定会想尽一切办法阻止这一结果的出现。虽然今天我们看到朝核六方会谈取得了一系列的进展，但是，说不定哪天有个风吹草动，出现“辛辛苦苦十几年、一夜回到解放前”的情况绝对是一件很正常的事。
#+HTML:<b>朝核六方会谈只不过是一个中俄美进行权利划分的舞台</b>
#+LaTeX:\red{朝核六方会谈只不过是一个中俄美进行权利划分的舞台}
，日韩朝只不过是三家被动参与的利益被划分者，他们三家能得到多少，一方面看自己的本事，另一方面更要看自己盟友的表现。

说到这里，我们不能不说，是我们胡总高明：本来，美国人是打算把朝核问题做成一个阻止东北亚经济一体化的“大石头”的-----有朝核在，朝日是死敌，韩日、中日有旧帐，美国充分利用这些矛盾，再在会谈里埋钉子，让会谈永远谈不出结果，美国自己则可以享受东亚在自己经济势力范围内所带来的一切好处。

让美国人做梦也想不到的是，北京把朝核玩大了，本来朝核没什么大不了的，结果硬生生的让北京搞成了核爆，这下子不要紧，把小日本的核野心刺激了起来。日本人正愁没理由进行核武装呢，机会这不来了吗？一旦日本核武装了，美国还有什么能力“保护”日本？那美国全球最大的一个战略支点也就没有了（在上一篇评美国支持日本入常的文章中，也提到了这一观点，其实，无论日本入常，还是自我核武装、拥有航母，都是美国全球支配地位崩溃的前奏）。美国无论如何也承受不了这一结果，而压下日本的核野心仅仅靠美国人是办不到的，它绝对得求中俄来帮忙。去年朝鲜核爆后，为了压住日本，美国向中俄让了多少步、放了多少血，恐怕美国人是点滴在心头的。

两害相权取其轻。一边是立刻崩盘，一边是温水煮青蛙（六方会谈一步步的出成绩），美国人选择哪个？没办法，就算自己终有一天会被人“煮”了，那也是下一任总统或者下下一任的事了，能缓一天算一天，说不定还能找到咸鱼翻身的机会呢。于是，一个戏剧性的场面出现了：本来半岛和平是美国人最不愿意看到的，朝核这么一爆，最坏的结果居然成了最好的结果！我们不能不佩服胡总“转祸为福”的能力。但是，为了翻盘，美国人肯定会想尽办法拖延时间，并寻找机会阻止这一结果的出现。

而对中俄朝而言，只要美国人不敢打朝鲜，东北亚经济一体化就可以搞，天天努力的搞，在搞的过程中离间韩美关系-----除非韩国人不想在经济上扩大地盘、不想半岛统一。当然，有抗美援朝的教训，美国人还敢再对朝鲜动武吗？既然不敢，那么中俄朝一方面在享受东北亚经济一体化好处的同时，还给自己留一张对付美国人的好牌，何乐而不为？

综合起来看，无论是中国、俄罗斯，还是美国、日本，都不希望朝鲜能谈出个彻底的结果。所以，朝鲜弃核，遥遥无期。



** 【奋进社/金鸿95】没落的帝国

[2007-10-0520:48:13]

看一条伊朗方面的新闻：

中新网华盛顿9月30日电据美国《洛杉矶时报》报道，美国和伊拉克官员们称，伊朗总统内贾德已向伊拉克总理马利基承诺，伊朗将帮助伊拉克切断伊拉克武装分子的武器、资金和其它支持的供应。
马利基的助手称，马利基在对伊朗进行三天访问期间达成了这一协议，伊朗承诺对两国的边境地区实施更为严格的控制。一位陪同马利基总理出席联合国大会的伊拉克总理办公室官员称：“总理最近说，伊朗人已强烈承诺，他们在控制边境方面将采取更严格的控制，就走私进入伊拉克的武器而言，他们承诺的效果已开始显现出来。”马利基的一名政府顾问法鲁克称：“协议包括伊朗政府增加驻边境力量，加强守卫1000公里长边境的力度。”

看来，在美国受了“虐待”的内贾德总统真的生气了，并且开始使黑招了。

做为“切断”武器、资金及其它支持手段的方法，“协议包括伊朗政府增加驻边境力量，加强守卫1000公里长边境的力度。”表面上看起来象模象样的，只是，在此，金鸿想问一句：
#+HTML:<b>事实果真如此吗？</b>
#+LaTeX:\red{事实果真如此吗？}

我们必须看到，如果伊朗想保持国家稳定、不被美国人搞垮的话，在伊拉克境内不择手段的给美国大兵制造麻烦是必须要做好的一件事。如果伊拉克反美武装被美国兵杀光了，那么接下来的伊朗，就是第二个萨达姆领导下的伊拉克。为了保证自己的国家独立和领土安全，伊朗根本没有选择的余地。所以，除非美军撤出伊拉克，否则，伊朗对于伊拉克反美武装的支持，不可能也不敢停下来，这是御敌于国门之外的最好办法。

至于“伊朗政府增加驻边境力量、加强守卫1000公里长边境的力度”，根本就不是为了切断对伊拉武装分子的武器、资金和其他支持的供应的，而是为了保护伊朗自身国家安全的。

9月26日，美国参议院通过了一项关于伊拉克问题的决议。决议称应根据民族和宗教信仰将伊拉克分为3个实体，即
#+HTML:<b>库尔德</b>
#+LaTeX:\red{库尔德}
、
#+HTML:<b>什叶派</b>
#+LaTeX:\red{什叶派}
以及
#+HTML:<b>逊尼派</b>
#+LaTeX:\red{逊尼派}
三大实体，首都巴格达的联邦政府只掌管伊拉克石油收入并负责边界安全。

把伊拉克剁为三块的目的，就是为了让伊拉克打起内战，并且把战火引起伊朗、叙利亚，一旦被拖进战火的伊拉克、伊朗、叙利亚撑不住了，美国在中东翻盘的机会就来了。美国的这个威胁，的的确确吓坏了不少人，包括欧盟、阿盟，不过，伊朗方面好象没有就美国解体伊拉克的决议发表什么意见，只是在时隔四天后，搞了个“加强守卫1000公里长边境的力度”动作，并且美其名曰“切断伊拉克武装分子的武器、资金和其它支持的供应”。

越境为伊拉克反美武装提供支持的，肯定是以伊朗特工为骨干力量，这些人在进出边境时会受到自己人的难为吗？开玩笑吧。很显然，伊朗用自己的行动告诉美国人：想再伊拉克煽风点火就干吧，只是火肯定烧不到伊朗境内，只是在伊拉克的美国大兵需要注意了，别烧不了别人反烧了自己就好！

一面扎牢篱笆的同时，波斯人又开始朝着美国人挤眉弄眼了：

英国媒体1日报道，伊朗方面当天提出将“有条件”帮助美国稳定伊拉克局势。而美国驻伊拉克最高指挥官在前一天也对媒体表示会“有条件地”给与伊朗一些“回报”。分析人士称，双方的紧张关系出现了一定缓和的迹象，但是最主要的是哪一方先让步的问题。

伊朗首席核谈判代表拉里贾尼近日公开表示，如果美国能公布从伊拉克撤军时间表，伊朗将帮助其稳定伊拉克局势。

伊朗又让自己的首席核谈判代表出来就伊拉克形势发表高见了，很明显，这一举动不是有心也是有意的-----如果希望伊拉克局势有所好转的话，就在伊核问题上让步吧，尊敬的美国人？

要求美国人公布从伊拉克撤军的时间表可不是个容易事，就连生猛无比的萨科奇都没有从牛仔布什那里挖到的东西，伊朗人能弄得到吗？我们将拭目以待。不过，伊朗此举却的的确确是在替中俄欧向美国开价。

世界警察也是随便受人威胁的？一向以“我是流氓我怕谁”自居的美国人又同岂会受制于小小的伊朗？出现下面的情况也就不足为怪了：

中新网纽约10月2日电综合报道，美国最新一期的《纽约客》杂志载文称，布什政府目前已经制定对伊朗革命卫队实施外科手术式空中打击的计划，而且这一计划已经得到了英国首相布朗和军方的支持。

真不知道美国人累不累，两年来，从各个国家、各种媒体、各种人物、以各种方式传达出来关于美国要打击伊朗的消息是满天飞舞，多如牛毛，让人眼花缭乱。可惜的是，到今天我们也没有看到出现这样的结果，除了美国人近乎变态的在自己控制的伊拉克领土上以各种理由一次次抓走伊朗在伊拉克的外交人员以泄私忿，结果呢，不光伊朗政府整天吵着向美国要人，伊拉克政府的高官们，也常常跟在美国人屁股后面要求放人。而这样的小动作，丝毫掩盖不了美国面对着一个强硬伊朗政权的无奈。

美国人真的还有能力去打击伊朗吗？不要开玩笑了吧。看看美国大兵在伊拉克和拉富汗的惨样儿吧：

CCTV.com10月2日消息(中国新闻)鉴于伊拉克教派冲突和暴力事件不断，布什政府不断敦促伊拉克领导人加速民族和解，据白宫发言人佩里诺说，伊拉克领导人正在试图确定三项立法：合理分配伊拉克的石油收入；让萨达姆时期的复兴党成员重返伊拉克政府和在各省举行选举。布什和塔拉巴尼都认为，伊拉克议会通过这三项立法是很重要的。

中新网10月1日电综合报道，阿富汗塔利班9月30日说，只要外国军队留在阿富汗，它就不会同阿富汗政府进行任何的谈判。

塔利班发言人当天说，塔利班对接受政府职位不感兴趣，只关心外国军队的撤离。

在塔利班做出这番表态的一天前，阿富汗总统卡尔扎伊表示，他可以向愿意放下武器、加入阿富汗政治体制的反叛分子领导人提供政府职位。

卡尔扎伊9月29日说，他愿意同在逃的塔利班首领奥马尔以及反叛武装指挥官希克马蒂亚尔进行会谈。就在卡尔扎伊发表这番讲话的几个小时前，首都喀布尔一辆拥挤的军用巴士遭到自杀炸弹的攻击，有30人被炸死。塔利班声称对这次炸弹袭击负责。

看看白宫发言人的表态，真替萨达姆觉得冤，他死的早了，不然，说不准还能重新掌握伊拉克的政权，看看人家奥马尔，撑着活到今天，机会来了。

没见过象美国这么无耻的国家，无耻到人让人心生怜悯的地步。为了在伊拉克、阿富汗维持一个低成本的存在，脸是彻底不要了！

如果说“让萨达姆时期的复兴党成员重返伊拉克政府”是合理的，那几年前美国凭什么打伊拉克？难道有萨达姆的复兴党是罪恶的，没有萨达姆的复兴党就是可以接受的？恐怕如果不是因为坚决要为萨达姆报仇的复兴党党员们一再的对美国大兵下手、搞的他们撑不住劲了，他们也不会对复兴党这么客气吧？布什先生就不怕复兴党人扛着萨达姆的肖象走近伊拉克政府办公大楼上班？

至于奥马尔，那是拉登的坚定支持者。如果不为“反恐”，美国人也不会杀入阿富汗吧？既然今天让塔利班领导进入阿富汗政府是合理的，那么当年美国人为什么要推翻奥马尔领导的阿富汗政府？既然塔利班可以成为美国人允许的一股执政势力，那么美国人是不是该撤出阿富汗了？

面对着卡尔扎伊的“招安”，塔利班真是一点面子都没给；同样，我们可以想象一下希望“招安”伊拉克反美武装的塔拉巴尼将会收获到什么呢？我们不防为伊拉克反美武装设计一句台词：让炸弹去回答你们吧！

一个月以来，美国人为了在中东翻盘，疯狂的对伊朗（也包括叙利亚）、中国、俄罗斯、巴基斯坦施加压力（仔细一看，都是上合的人，呵呵），上合一方面稳住阵角的同时，也加大了在阿富汗和伊拉克的“工作力度”，时至今日，效果是彻底表现出来了。

如果美国人真想在中东的日子好过一点的话，还是响应一下伊朗提出的“如果美国能公布从伊拉克撤军时间表、伊朗将帮助其稳定伊拉克局势”的建议吧。否则，拖的越久，死的越惨。

至于布什3日提出的只要伊朗愿意放弃其核计划、美国有可能就伊朗核问题与之进行谈判的建议，是没有什么价值的，这纯粹是个“鸡生蛋”还是“蛋生鸡”的问题（伊朗要求先谈判、价码合适再弃核）。如果美国人真不在意伊朗核技术一日千里、伊拉克泥潭越陷越深的话，大家不妨就这样继续再斗上三年的嘴皮子，就看到时候吃亏的谁。

有颗定心丸吃着，波斯人的自信表白无疑是一种非常正常的流露：

中新网10月4日电：伊朗外长穆塔基在纽约联合国总部表示，伊朗认为美国不会向伊朗发动战争。


美国白宫５日公布的相关文字记录显示，布什总统４日在接受阿拉伯卫视台专访时否认美国正准备对伊朗发动军事打击，但称将继续采取制裁手段迫使伊朗放弃核计划。

伊朗总统内贾德5日在首都德黑兰表示，在巴勒斯坦所有土地从以色列手中获得解放以及“罪犯”被绳之以法之前，伊朗和中东地区的其他国家决不会放弃斗争，巴勒斯坦民众应该举行全民公决投票将以色列驱赶到欧洲或其它国家。

简评：顶住了战争威胁的伊朗开始替北京开价了：
#+HTML:<b>巴以和谈该请北京入场了！</b>
#+LaTeX:\red{巴以和谈该请北京入场了！}



** 【奋进社/金鸿95】房价狂飙的时代就要结束了

[2007-10-1420:16:31]

#+HTML:<b>据报道，监管层前天召集工、农、中、建、交五大银行商讨“第二套住房”认定标准，确定了以下三条原则：公积金贷款不列入认定是否为第二套住房的参考项；已结清贷款的购房者，仍可算作第一套住房贷款者；夫妻双方只要有一方仍有房贷未结清的，再贷款购房需算作第二套住房。</b>
#+LaTeX:\red{据报道，监管层前天召集工、农、中、建、交五大银行商讨“第二套住房”认定标准，确定了以下三条原则：公积金贷款不列入认定是否为第二套住房的参考项；已结清贷款的购房者，仍可算作第一套住房贷款者；夫妻双方只要有一方仍有房贷未结清的，再贷款购房需算作第二套住房。}

仅仅把第二套房子的首付提到40%,新闻上就曝光说北京有许多的业主退房了。看来，如果真想把房价调控下来，并不是太困难的事。

几年来，房价狂飙，一次次的宏观调控都没有能够阻止房价的飞涨。个人感觉，出现这样的情况，有两方面的原因：一是为了国家的整体利益的考虑，过去的几年里不好对房地产市场下狠手，毕竟，相对于整个国家利益而言，近几年来的购房者加起来也只是一部分人，还有比调控房价更重要的事要先做好；二是上面的调控政策并没有被下面有效执行，下面官商勾结的事情太多了，清理也得有个过程。

其实，真正想把房价调控下来并不难，在这里讨论两招：

第二套房首付提到四成，只不过是试水而已，如果有必要，可以提到六成，从第三套房起，不允许贷款；第二套房契税提到25%，第三套房提到100%。如此一来，看哪个炒房的还有利可途？如果谁有钱想改善居住条件，只要舍得花钱，没人拦你。也许有人说这样太狠，可这是没办法的事，谁叫我们国家人这么多呢？我们的城市用地太紧张了，总不能让有钱的人一人住三套房子，没钱的人睡马路吧？既然是社会主义国家，最起码的社会公平总该体现出来吧？如果我们也象澳大利亚一样，就可以人人住别墅了，可我们没那个条件。

哪个城市号称房价降不下来？拿北京做例子吧，成立一家大型的安居公司，专门为符合条件的家庭提供
#+HTML:<b>经济适用房</b>
#+LaTeX:\red{经济适用房}
（保证15%利润），每年交房1000万平米，可以安置15万个新家庭的住房需求，如果感觉这点交房量小，可以提高到2000万平。对于这些安居房，不必办理个人产权证，政府划拨土地即可，如果购房业主要卖房，可以按照买房时约定的价格卖给安居公司，安居公司再卖给其他需要经济适用房的家庭。如此一来，这些经济适用房的房价绝对可以控制在3000元/平方。其他的住房需求交给市场，由商品房来满足。谁敢说如此一来房价会不降？当然，对于购买经济适用房的家庭，要定好明确的标准，购买时也要透明，不要再出倒房号牟利的情况了。

有这两招，真施展出来，房价必降！当然,在实际操作中,不会这么狠,因为那样倒下去的房地产公司会很多很多,代价也会很高,但如果秩序渐近的上的话,也会达到同样的目的。

其实，国家要强力强控房地产市场的信号早就出来了：8月21日新华网显要位置刊登了空军上校戴旭的《房地产支撑不起大国崛起》一文，当时，我在自己的博客上全文转发了这篇文章，并配了简评：“金鸿简评：很快国家就要对房地产行业出手了，这一轮的出手将是异常强硬的，其目的绝对不仅仅是针对房价的。当然，房价在三年内回落是必然的。”如果谁对那篇文章有兴趣，可以从我的新浪博客里的一下，肯定能找到那篇文章。

之所以把这篇文章做为信号，原因很简单：数年前，朱总理在不得已的情况下，为了拉动国民经济，把房地产业搞成了支柱产业；而今天，内外环境全变以了，房地产业再做支柱产业也不再合适。这篇文章就是中央要对房地产业进行定位调整的一个信号。

如果我的判断不错的话，十七大开完后，房地产业的真正强力调控就要开始了，房价将在三年内回归到一个合理的价位。






回复:心向红旗朋友



看东方的评论吧,教授比我水平高的多:

随着马来西亚、印度尼西亚等东盟国家“公开附合”中国的“对话解决缅甸问题”，中国、美国与东盟之间的关系再次向中国方向倾斜，中国依靠东盟解决问题的策略似乎大有收益。不仅如此，还逼得出于自已私利、一直有心为华盛顿缅甸政策张目的新加坡，既为了厘清在此事中自己与欧美之间的“清白”，现任新加坡总理的老爸、新加坡独立之父--李光耀，甚至亲自出面表示“只要条件成熟、新加坡愿意重新并入马来西亚”，一副老脸都不要了的样子实在让人看不下去。在东方评论员看来，倒是马来西亚看得明白，知道李光耀所说的“条件”是永远不会成熟的，因此，一句“马来西亚不需要新加坡”，让国际社会从紧张的国际角力中、难得地欣赏到了一则国际大笑话。





** 【奋进社/金鸿95】反美的土耳奇人

[2007-10-15 17:04:15]

简单看一下土耳其与库尔德武装之间近一周来冲突的情况：
土耳其反政府武装组织库尔德工人党10月7日在土东南部省份舍尔纳克与政府军交火，造成13名政府军士兵丧生。
之后，土耳其政府已经表示，如果有必要的话，土耳其军队将会进入伊拉克北部打击库尔德工人党武装。
美国白宫女发言人佩里诺10日表示，土耳其不应当进入伊拉克境内打击库尔德工人党武装。
伊拉克官员14日说，土耳其部队已开始炮轰伊拉克境内的库尔德族自治区。
土耳其内阁15日将正式决定是否越界打击库尔德武装，并准备要求国会16日表决此项地面军事行动的计划。

其实，土耳其与库尔德武装之间的斗争早就不是两方在斗争，站在土耳其背后的是欧洲人，站在库尔德武装后面的是美国人。
现在，美国在中东泥潭已陷入到了几乎无以自拔的地步：巴以和谈无解、打击伊朗无力、扭转伊拉克乱局无望。这三大难题中的关键就是稳定伊拉克局
势，只要伊拉克局势控制住了，美国就具备了在中东翻盘的能力。
而中俄欧三家，则是想尽一切办法在伊拉克拖死美国人----如果美国人真的扛不住了，可以撤兵，大家都欢迎。而撤兵意味着美国中东战略的彻底失败
：伊拉克都失败了，那打击伊朗不就成了一个梦了吗？伊拉克失败了，阿拉伯国家对美国的畏惧之心将大大减小，美国对巴以和谈的控制力将大大减弱。
所以，美国实在也难以面对在伊拉克失利的结果。为了扭转被动局面，实现咸鱼翻身的伟大梦想，美国向方方面面（包括欧盟、阿盟、中俄）威胁，如
果自己在伊拉克失败了，必将以引发伊拉克内战的方式以爆中东大油筒-----我（美国）要是过不好，谁也别想过好日子！
应该说，从美国议员正式提出三分伊拉克开始，美国就展示出了无奈之下将在中东彻底制造混乱的决心，而美国的动作并没有引起中俄的丝毫顾虑，伊
朗和叙利亚也是强硬依然，就连欧洲也没有如美国人所想的那样被吓倒，唯一一个吓的够呛的就是伊斯兰逊尼派----而它们是美国的“老朋友”，这倒好，敌人
没受伤，朋友倒得罪了。
为了最大限度的震住这些不怕事的主儿，美国人开始动真格的了，于是，库尔德武装越境欺负土耳其的一幕就出现了。美国人这么做，是为了向欧洲人
展示它有能力把伊拉克的内战引入土耳奇。
当然，美国人动真格的，也只能吓唬一下欧盟了，要想吓唬中俄，还差点火侯。近几天大家都看到了：普京与美国人谈欧洲反导时的立场是多么的强硬
，还高调的试验可拦截核弹打击A-135战略反导系统；北京也曝光说自己的北斗系统将会有30颗卫星。这充分说明，东方的两大强权有信心、有决心也有能力
陪美国人玩一会。
令美国人失望的是，不光中俄强硬，欧洲（土耳其是其代理人）也强硬的要死：在美国人的强烈反对声中炮轰了伊拉克境内的库尔德族自治区，不仅如
此，还要准备搞什么地面行动！不知道大家还记不记得，半个月以前内贾德宣布加强守卫1000公里长边境的力度的行动（此行动号称是“帮助伊拉克切断伊拉
克武装分子的武器、资金和其它支持的供应”）。
结合起来看，无论是中俄欧，还是他们的代理人伊朗、叙利亚、土耳其，都没有被美国人吓倒。美国人的讹诈无效！
当然，如果美国人觉得还不过瘾的话，还可以继续吓下去，但是，如果把自己逊尼派的朋友全吓跑了还没有达到目的的话，美国人在中东可就连老本都
赔进去了！

附：我写了一篇评论,发在了中国网，有兴趣的朋友可以去看一下,呵呵：http://forum.china.com.cn/ciicbbs/read.php?tid=245405


** 【奋进社/金鸿95】布什，疯狂还是心虚？

[2007-10-19 12:38:06]

看一条非常有爆炸性的新闻：

    华盛顿消息：美国总统布什17日警告说，如果伊朗拥有核武器，可能将引发第三次世界大战。布什宣称，拥有核武器的伊朗对世界和平是“极大的威胁”，
要阻止第三次世界大战的爆发，就必须阻止伊朗获得制造核武器的知识。  

小布什先生真不愧是个“战争贩子”，小打小闹嫌不过瘾，想搞大的了。这一回究竟是因为受了什么刺激呢？还信心爆棚呢还是自己给自己壮胆呢？这可是个大
问题，有必要研究一下。

几天前，希拉里公开表示，如当选总统将考虑对伊朗动武。此举充分表明，美国人所抱定的独霸中东的单边主义路线，不论是现在在台上的保守主义、还是极
有可能轮岗上台的自由主义，都不会放弃。拿下伊朗、搞定中东的既定目标不会有变化，变化的只是实现目标的手段。

面对着美国人一心想断自己粮道的做法，中俄欧奋起反击。先通过一条新闻看看欧盟的最新动作：

土耳其议会17日以多数票通过了政府有关允许土军越境进入伊拉克北部地区以消灭盘据在那里的库尔德叛军的请求。

美国人用中东大乱没有吓倒欧洲人，反而得罪了土耳其（具体的分析，在《反美的土耳其人》一文）。下一步，美国人再想借道土耳其打击伊朗，恐怕就更难
了。

欧盟变脸了，中国的态度就更有意思，看一条来在本土的奇闻：

16日， “闽台经贸交流座谈会”在高雄举行.中国著名桥梁设计专家林元培先生今日在此间表示，伴着中国大陆大跨度桥梁建设的材料、设计理念、施工工艺等
领域不断创新，建设台湾海峡大桥的技术已切实可行。

都说中国人含蓄内敛，看看这几天，一会儿嫦娥奔月，一会儿北斗要搞三十颗星，这还不过瘾，居然要造跨海峡的大桥。坦白讲，对于桥梁技术我并不内行，
中国的桥梁技术到底多高我也不清楚，不过，要造台湾海峡大桥，首先要解决的问题不是技术问题，而是中国统一问题。陈水扁在台上，肯定不让造。从林先
生自信满满的表态来看，好象陈水扁的态度没有放在他的心上，也许在这位专家的眼里，台湾已经解放了。

当然了，建这么大的工程，胡总的态度最重要。

从APEC胡布会上，北京就把“入联公投”定性为台独，之后，台独的动作一直没停，而北京的武统准备工作也一直在稳步进行。最能体现北京态度的，还是胡总
的报告：我个人认为，报告中关于台湾部分的内容透露出来的最重要的信息是：1、给两岸关系定性，是敌对状态。2、软的更软，硬的更硬。软，是对渴望统
一的台湾同胞的；硬，是对扁马李宋之流的。记得胡总在讲出“绝不允许任何人以任何名义任何方式把台湾从祖国分割出去”一句时全场响起的掌声持续了三十
多秒钟。全体中华儿女的意志是任何力量都抵挡不住的，撄我者折，挡我者死！

小布什深知，想摆平伊朗，必须先压服中国。为了加大压力，他用了两手，一手是台独，另一手，就是开抡经济大棒（为了加大力度，这一次还拉上了欧盟，
欧盟的财长们开了个会，自己的伽利略号集资摊派的事没搞出个结果来，却来逼人民币升值，真是吃饱了撑的，没事找事）。大家可能注意到了，妖魔化中国
制造的行动又开始了。其实，这一手是标准的“杀敌八百、自损一千”，绝对得不偿失。北京一方面正面反击，另一方面加大了抛售美国国债的力度，上个月是
创纪录的80亿美元。北京这是用实际行动证明，八月份所说的“可将抛售美国国债作为经济谈判筹码”并非玩笑，而且正在试水行动中，如果美国不想经济崩溃
的话，这种危险游戏就不要玩了。

最后，我们再看一加俄美交锋，这才是这几天的主战场。普京访问德黑兰，搞出一大堆的花边新闻：先是好心的美国人要和克格勃分享暗杀普京的情报，结果
人家普京不领情，情报不要、伊朗照去。刚刚到伊朗，就听说最近小布什脾气很大，而且没耐心（更年期综合症？），明年下台前一定要打伊朗。普京也是个
高手，给伊朗最高领袖哈梅内伊递交了一份有关伊核问题的、内容保密的新建议，并且一口咬定伊朗玩核没什么大不了的，不就是为了点亮几个电灯泡吗？他
还在里海沿岸国家领导人高峰会表示：“我们不仅不使用任何武力，甚至不考虑使用武力的可能性。” “我们讨论不能让其它国家使用我们的领土，做为侵略或
对其他里海周边国家采取军事行动的跳板。”当听说小布什又兴趣打世界大战争时，普京又开始死命的恶心起他来：

据伊朗媒体报道，伊朗最高精神领袖哈梅内伊近日在会见俄罗斯总统普京时对俄罗斯和伊朗之间停滞不前的经济关系表示不满。他认为，扩展两国关系就是保
障两国利益的“法宝”。他指出，“独立的伊朗”存在有利于俄罗斯，而“强大的俄罗斯”存在则有益于伊朗。

　　普京也在此次会见中表示，“伊朗的强大和在国际舞台上的影响力日渐提高与俄罗斯民族利益息息相关”。他还说，莫斯科同德黑兰的合作中不存在任何限
制，现在甚至未来俄罗斯都会坚定不移的前进在这一道路上。

听说美国正在调动一切力量来制裁伊朗，人家普京呢，却在拍着大腿大叹俄伊之间的经经关系“停滞不前”，----这哪象兄弟嘛。既然不满意，应该怎么办？加
大投入呗。当然，在为暗杀阴谋出了一口恶气之余，普京也没有忘记亮一下肌肉。这不，白杨导弹又试验成功了。布什先生，想打世界大战吗？战火烧到纽约
，如何？

******************************************************************

    最近十来天，中俄美三方的武器大拼比也很过瘾，一起看一下：

11日，为美军弹道导弹防御而配套的移动式情报处理系统“联合战术地面站”(JTAGS)将于12日部署到驻日美军三泽基地。三泽市副市长吉田耕悦在听取说明后
对政府行动迟缓表示不快，称“到部署前一天才来说明，这样做合适吗？”

美国人想干嘛？台海开战了想掺合一下吗？（注意日本副市长的态度，很不满意！如果真打起仗来，美日的配合绝对是个大问题。）

12日，北京就搞出了“二炮戈壁发射数枚新型导弹、发发命中”的新闻，一边是坚盾，一边是锐矛，谁厉害？

14日，塔利班组织宣称，他们利用绑架韩国人质获得的数百万美元赎金用来购买武器，对付阿富汗境内的英国和美国军队。很显然，美国人的北约朋友们可要
注意安全了，塔利班又要抓人质了！

15日据，俄罗斯航天部队周四从哈萨克斯坦境内成功试射了近程拦截导弹。专家认为此次试验的对象极有可能是A-135战略反导系统以及代号为53T6的高超音
速大气层内导弹拦截弹。

如果不出意外，这种类型的导弹肯定能在伊朗的铀浓缩核设施周围找到。

美国五角大楼太空安全局（NSSO）日前给美国政府报告中建议美国拨款100亿美元用于筹建试验卫星，以便向地球传送超过千兆的能量。

在中国玩了一手导弹打卫星的绝活之后，华盛顿对自己的卫星系统也不放心了，想来个太空变阵？不过，北京倒不认为卫星不好用，国防科工委出面宣布，北
斗要上三十颗星！

17日，普京访伊期间将签署50台RD-33涡轮喷气式发动机供应协议，伊朗准备将购买来的发动机装配在国产“闪电”超音速歼击轰炸机上。

为了“抗美援伊”，老熊煞费苦心呀！

17日美空军透露消息，F-22隐身战机可能进驻中亚巴格拉姆基地。

都说美国人信奉技术制胜，真是一点都不假。听说F22很隐形，看不到打不着。还是这样吧，建议北京再点儿导弹给伊朗。鸡窝炸烂了，看他的野鸡去哪！对
了，结算时一定要用欧元。

  http://forum.china.com.cn/ciicbbs/read.php?tid=246441

** 【奋进社/金鸿95】十七大后，房价也和谐

[2007-10-23 12:50:13]

注:本贴首发中国网和平论坛,精华文章.

    举世瞩目的十七大已经召开了，并吸引了全世界的目光。能得到如此的关注度，是中国第四代领导集体共同努力的结果。五年来，无论是国内、还是国际
；无论是经济、还是军事，我们都取得了非常优异的成绩。
    
        对广大的老百姓而言，最关心的，还是民生问题。应该说，在过去的五年来，以胡绵涛同志为总书记的党中央，把民生问题摆到了突出的位置，做了
大量扎实有效的工作，并且取得了非常明显的成绩：
    
         1、免交农业税，惠及九亿多农民。解决“三农”问题被作为各项工作的“重中之重”，农村的投入一次比一次加大，农民得到的实惠一次比一次增多。
不仅取消实行了２６００多年的“皇粮国税”――农业税；而且种粮、良种、农机购置也有补贴。
    
         2、义务教育免杂费，就读初中以下学校仅交学费，数额也比往年大大减少；
    
         3、推行新型农村合作医疗，农民的医药费也可以报销了。推行的范围占到了全国８０％以上县（市、区），广大农村居民看病难、看病贵的问题得
到有效缓解；
    
         4、全国３１个省区市都已经建立了农村最低生活保障制度，覆盖了２０６８万人，使社会上孤寡残疾与弱智者生存费用得到维持.
    
             ……
    
         在我们都看到了也感受到了五年来取得的伟大成就的时候,也不能漠视国内的不和谐因素,比如高房价。
    
         我们必须承认，房价持续高涨，对国民经济的良性运转的危害是非常大的，对于广大需要购买新房的老百姓也是一个巨大的负担。
    
         几年来，房价狂飙，甚至一次次的宏观调控都没有能够阻止房价的飞涨，以致于许多人对房价的调控都不抱希望了。其实，现实并没有那么悲观。
    
         之所以出现这样的的情况，有两方面的原因：一是为了国家的整体利益的考虑，过去的几年里不好对房地产市场下狠手，比如，银行要上市，如果
在此时出手太重，将严重影响国内银行通过上市而带来的发展新契机。毕竟，相对于整个国家利益而言，局部利益还是要让步的（近几年来的购房者加起来也
只是一部分人），比调控房价更重要的事要先做好；二是中央的调控政策并没有被某些地方政府有效执行，地方上官商勾结的事情太多，再加上国外热钱炒房
的推波助澜，地方政府经营城市的理念并未及时转变等等，影响了中央政策作用的有效发挥。
    
         几天前，监管层召集工、农、中、建、交五大银行商讨“第二套住房”认定标准，确定了以下三条原则：公积金贷款不列入认定是否为第二套住房的
参考项；已结清贷款的购房者，仍可算作第一套住房贷款者；夫妻双方只要有一方仍有房贷未结清的，再贷款购房需算作第二套住房。再加上国土资源部刚刚
发布的《招标拍卖挂牌出让国有建设用地使用权规定》（“39号令”）明确规定，“未按出让合同约定缴清全部土地出让价款的，不得发放国有建设用地使用权
证书，也不得按出让价款缴纳比例分割发放国有建设用地使用权证书。” （此举目的是进一步规范了开发商的拿地程序，也为部分开发商蓄意囤积土地的行为
敲警钟）。
    
         再结合 8月21日新华网显要位置刊登了空军上校戴旭的《房地产支撑不起大国崛起》一文看来，中央对高房价的强力调控已经出手了。之所以如此
重视这篇文章，原因很简单：数年前，东南亚金融危机严重影响了我国的国民经济发展，为了拉动内虚，政府在不得已的情况下把房地产业搞成了支柱产业；
而今天，国内外经济环境全变以了，房地产业再做支柱产业也不再合适，这篇文章就是中央要对房地产业进行定位调整的一个信号。
    
         其实，对于房价调控的强硬措施有很多，比如：
    
         1、提高第二套房首付比例（包括从第三套房起不允许贷款等），从第二套房起大幅提高契税以压缩炒房的赢利空间，尽量减少富裕人群大量屯房炒
房的情况出现。
    
    如果有人因为比较富裕想改善居住条件，只要舍得花钱（多交税、全现款买房），不会有人阻挡，我们国家是个人口大国，居住用地太紧张，如果我们像
象澳大利亚一样，就可以人人住别墅了，可我们没那个条件。为体现最起码的社会公平，应该做到人皆有其屋，绝不能让有钱的人一人住五套房子，没钱的人
睡马路！
    
         2、改变目前的居住用房源供应模式，不能把所有的居住用房源全部交给市场来解决，各地方政府应该成立安居公司提供一定比例的经济适用房（比
如20%，安居公司要保证合理的利润，比如10-15%），为符合条件的家庭提供经济适用房，对经济适用房，土地可由地方政府无偿划拨，不必办理个人产权证
----没有人会担心社会主义的地方政府会把人从经济适用房里赶出去。如果购房业主要卖房，可以按照买房时事先约定的价格卖给安居公司，安居公司再卖给
其他需要经济适用房的家庭。如此一来，无论中国哪个城市，经济适用房的房价绝对可以控制在3000元/平方。其他的住房需求交给市场，由商品房来满足。
如此一来，房价必降。当然，对于购买经济适用房的家庭，要定好明确的标准，购买时也要透明，确保避免出现任何见不得阳光的行为。
    
         只要做到这两点，房价必定在一段时间后回归到一个比较合理的价位。当然，上面提到的两点，都已开始行动了，比如：许多城市都成立了专门提
供经济适用房的安居公司----一开始，经济适用房比例会比较低，但随着时间的推移，比例会提高到一个合理的程度。也只有经济适用房的大量出现，才能从
根本上避免那些天价地王的出现，从而降低商品房的价格（在一线城市，高房价中地价的成本所占总房价成本的比例是相当高的）。
    
         如此一来，和谐房价的局面必将出现。我们有理由相信，房价将在不久的将来回归到一个合理的价位。                                       
                                                                    2007-10-15 11:52
** 【奋进社/金鸿95】科学发展观----党的理论发展的新丰碑

 注:本文首发中国网和平论坛,推荐文章

   进入21世纪后，中国在发展进程中遇到了6大基本挑战：人口三大高峰（即人口总量高峰、就业人口总量高峰、老龄人口总量高峰）相继来临的压力；能源
和自然资源的超常规利用；加速整体生态环境“倒U型曲线”的右侧逆转：实施城市化战略的巨大压力；缩小区域间发展差距并逐步解决三农问题；国家可持续
发展的能力建设和国际竞争力的培育。这些困难严重影响着我国全面建设小康社会的进程。我们只能在“全面协调可持续的”科学发展观的指导下，才能得到真
正有效地克服这些严重制约中国未来发展的挑战。
       科学发展观，最初是在2003年10月召开的中共十六届三中全会系统提出的。
    
       科学发展观是马克思主义关于发展的世界观和方法论的在新的历史条件下的具体理论体现，是在新的时代指导我国经济社会发展的重要指导方针，是
发展中国特色社会主义必须坚持和贯彻的重大战略思想，是继马克思列宁主义、毛泽东思想、邓小平理论和“三个代表”重要思想后，党的理论发展过程中的又
一座丰碑。
       科学发展观，第一要义是发展，核心是以人为本，基本要求是全面协调可持续，根本方法是统筹兼顾。
    
       ——必须坚持把发展作为党执政兴国的第一要务。
       1980年1月16日，邓小平在中共中央召集的干部会议上指出：“说到最后，还是要把经济建设当作中心。离开了经济建设这个中心，就有丧失物质基础
的危险。其他一切任务都要服从这个中心，围绕这个中心，决不能干扰它，冲击它。”这一思想到后来被他归纳为“发展才是硬道理”。中国改革开放以来所取
得的举世瞩目的成就，在很大程度上得益于对这一思想始终不渝的坚持。江泽民同志也强调，马克思主义政党必须高度重视解放和发展生力。一个政党是否具
有先进性，归根到底要看它在推动历史使命，必须始终紧紧抓住发展这个执政兴国的第一要务，把保持党的先进性和发挥社会主义制度的优越性，落实到发展
先进生产力、先进文化、维护和实现最广大人民的根本利益上来。把握住这一点，就从根本上把握了人民的愿望，把握了社会主义现代化建设的本质。这些新
思想、新观点、新论断，对于我们党始终保持先进性，具有重大而深远的指导意义。因此说，发展是党执政兴国的第一要务。
       科学发展观是对“发展才是硬道理”进一步的充实和提高。树立和落实科学发展观，必须始终坚持以经济建设为中心，聚精会神搞建设，一心一意谋发
展。
       ——必须坚持以人为本。
       毛泽东同志指出，人民群众是历史的主人；同时指出，人民，只有人民，才是创造世界历史的动力。胡锦涛同志说，相信谁、依靠谁、为了谁，是否
始终站在最广大人民的立场上，是区分唯物史观和唯心史观的分水岭，也是判断马克思主义执政党的试金石。
       坚持以人为本，就是要以实现人的全面发展为目标，从人民群众的根本利益出发谋发展、促发展，不断满足人民群众日益增长的物质文化需要，切实
保障人民群众的经济、政治和文化权益，让发展的成果惠及全体人民。
       ——必须坚持全面协调可持续发展。
       坚持可持续发展战略，统筹人与自然的和谐发展，是科学发展观的一大亮点。在中国经济和社会的发展过程中，出现了许多负面影响因素：人口增长
过快，生态环境比较脆弱、森林草原资源供求矛盾突出，水资源短缺、水体的严重污染，能源供给紧张、矿藏滥采严重等等，要系统的解决这些问题，就需要
我们坚持全面、协调、可持续发展的观点，努力把握好人与自然之间关系的平衡，努力实现人与人之间关系的协调，从而保证中国经济和社会的又快又好发展
。
       可持续发展的思想，突破了单讲按经济规律办事的局限，拓展了经济规律的内涵，不但将物与物的关系深化为人与人的关系，而且涵盖了人与自然的
关系。因此，这不仅是对经济社会发展规律认识的又一个新飞跃，也是我党执政理念的一个新飞跃。
       ——必须坚持统筹兼顾。
       随着改革开放的深入推进，我们面对的社会利益主体数量更多，范围更广，利益关系也更复杂、各种矛盾不断增加。这就要求我们的经济发展过程中
要更加注重统筹兼顾，做到城乡协调发展、区域协调发展、经济社会协调发展、人与自然和谐发展、统筹国内发展和对外开放，推进生产力和生产关系、经济
基础和上层建筑相协调，推进经济、政治、文化建设的各个环节、各个方面相协调。这样，才能更好地妥善处理当前各方面突出矛盾、协调好各种利益关系，
实现全面、协调、可持续的发展。
    
       总的看来，科学发展观，是我们党的新一代领导集体在新的历史条件下提出来的，是与时俱进的理论创新的成果，是解放思想，实事求是的伟大理论
成就！
       只有牢固树立和认真落实科学发展观，才能把中国特色社会主义伟大事业更加成效地推向前进，实现中华民族的伟大复兴！                       
                                                 2007-10-16 21:57

** 【奋进社/金鸿95】自主创新---强我大中华的必由之路
  注:本文首发中国网和平论坛,推荐文章

    提高自主创新能力，建设创新型国家。认真落实国家中长期科学和技术发展规划纲要，加大对自主创新投入，着力突破制约经济社会发展的关键技术。加
快建设国家创新体系，支持基础研究、前沿技术研究、社会公益性技术研究。引导和支持创新要素向企业集聚，促进科技成果向现实生产力转化。深化科技管
理体制改革。实施知识产权战略。充分利用国际科技资源。进一步营造鼓励创新的环境，培养造就世界一流科学家和科技领军人才，使创新智慧竞相迸发、创
新人才大量涌现。
                                           -------十七大报告/胡锦涛
    
       一、科技领先是国家安全的保障
       改革开放三十年了，我们的国民经济有了长足的发展，取得了举世公认的伟大成绩。但是，我们是否可以说，经济发达了、人民文化程度高了，就能
够很好的解决国家命运问题（国家的生存与发展问题）呢？
       答案是：未必。下面的例子就足以说明一切：
       1820年中国GNP（国民生产总值）占世界的32.4％，是同期整个欧洲的1.2倍，但结果是20年后即1840年中国却被英国在鸦片战争中打败。1890年中国
GNP占世界的13.2％，是同期日本的5.3倍，但五年后即1895年中国又让日本打败了，1895年在甲午战争中又被日本打败，中国因此失去香港、澳门和台湾并被
迫签订了一系列丧权辱国的条约。从1840年到1900年，相隔仅60年，中国人竟由世界首富国家的大清臣民沦落为“东亚病夫”。
       今天我们重视GDP（国内生产总值），一定不能只看总量，而要研究它的构成。只有分析GDP的构成，才能看出是一个国家是自主型的国民经济还是依
附型的。一个国家的GDP高不一定就是一个强大的国家，
         在历史上，真正世界性的财富转移，都是靠国家暴力来实现的。100年前的中国和印度是被穷国英国打败的，即使是古代非洲和拉美国家，在哥伦布
发现新大陆之前也比欧洲富裕。他们的财富在欧洲人的大炮和利剑下在近代迅速流向欧洲，成为欧洲资本主义发展的原始积累。
    没有国家安全，财富只是一种没有保障的存在。国家主权是国家财富的基础，是全体公民生存与发展权利的最根本的保障；但是，如果没有国家力量的保
证，一切将流于形势。
       当今世界并不太平，自从第二次世界大战后，大规模的战争就再也没有爆发过，可小规模的战争从来没有停止过：自我们的人民共和国建立以来，发
生的与我们直接相关的战争就有：抗美援朝、抗美援越、对印自卫反击战，对越自卫反击战；还有深深影响全球战略格局的：阿富汗战争（苏阿）、海湾战争
、美国入侵南联盟、美国入侵伊拉克、美国入侵阿富汗。这些战争仿佛都离我们很多，可如果我们看看自己的家门口，那一个整天叫嚣台湾独立的败类陈水扁
不也让我们十三亿华夏儿女如芒在背吗？可恶的是，还有某些国际势力或明或暗的在支持他。所以，我们必须清醒的认识到，只有做好充分的军事斗争准备，
才有可能以战止战，才有可能实现祖国的和平统一。胡锦涛总书记也在十七大报告中指出：…..做好军事斗争准备，提高军队应对多种安全威胁、完成多样化
军事任务的能力，坚决维护国家主权、安全、领土完整，为维护世界和平贡献力量。
       国家安全永远是第一位的，否则，我们就不可能幸福的享受我们辛勤劳动的成果。在主权问题上，我们不能畏惧任何挑战，如果有任何人、任何势力
敢冒天下之大不韪，我们绝对要给它以迎头痛击！
    
       二、核心技术是买不来的
       落后就要挨打，斯大林的这句话永远是有道理的（他同样说过一句话“胜利者是不受谴责的”）。要保障国家安全，就要有领先的科学技术，近三百年
来的西方国家的发展史也清楚的说明了这一点：
       工业革命后，英国成为了全世界科学技术最先进的国家，所以，英国一度成为了拥有全世界最多殖民地的“日不落帝国”；19世纪上半叶法国科学技术
水平赶上英国，19世纪后半叶德国的科学技术水平又赶上法国，20世纪后半叶美国又取代德国成为世界科学技术的增长中心，而法、德、美三国也分别在这三
个时间段上成了当时世界上无可争议的强权。
       而与之形成鲜明对比的是，清朝虽然有全世界GNP最大的国家，却因为在科学技术远远落后于西方国家而难逃被侵略、被瓜分、被掠夺的命运。弗里德
里希 &S226; 李斯特对美国独立战争的性质作了中肯的评价，他说：“一切工业都垄断在祖国的手里，这一点就是美国革命主要原因之一，至于茶税事件只是
提供了革命爆发的一个机会。”
       技术领先，关键是核心技术要领先。前苏联之所以在上世纪八十年代成为世界仅有的与美国科学技术实力并驾齐驱的社会主义强国，依靠的就是领先
的重工业和国防工业的现代化技术。而这些核心技术，是必须依靠自主研发的，如果我们在这个问题上还抱有幻想，那等待未来中国的，只能是拉美式的命运
。让我们永远都不要忘记这些事件：上世纪60年代新中国基本建设因苏联大规模撤走专家而受挫；90年代中国放弃自主研发的运10，选择与麦道合作研制飞机
，最后因美国强行终止麦道与中国航空公司的合作计划而夭折；1999年美国抛出所谓“考克斯报告”、同年底美国强迫以色列中止对华出售预警机……
         毛泽东时代，感谢当时帝国主义封锁和苏联对中国形成的三面合围的险恶外部环境，让我们咬紧牙关，自力更生，最终使国的国防工业建设得到了
快速发展。改革开放后，国家的GDP虽然取得了快速增长。但是，国家技术的自主研究已被我们冷落和荒置多年了。今天，国际安全环境发生了不利于中国的
变化，现实要求我们加大对国家战略产业及其相关技术、尤其是极难通过国际贸易或“跟踪模仿”获得的航天航空和航海潜艇技术的投入（国防技术问题是涉及
到主权的生死攸关的问题）。
       当年，我们在极其艰苦的环境中能研究成功“二弹一星”，难得在条件远胜从前的今天，我们就不行了吗？
       绝对不是！
       华盛顿在就任美国决统的当天，特意穿着国产布料制成的服装，他说：“要使一切后继者，一切后来人的立法者，获得一次深刻的教训，告诉他们怎样
才能够促进这个国家的福利”。
       今天，中华民族把科技进步聚焦在增强自主创新能力上，这是一个历史性进步！在其背后，我们已经品尝了太多的酸甜苦辣！
    
       三、自主创新与国际竞争力
       自主创新能力是国家竞争力的核心。只有拥有强大的自主创新能力，才能在激烈的国际竞争中赢得主动权。
       改革开放以来，在我们取得了举世公认的成就的同时，我们也越来越清楚的感觉到了种种“约束”：为什么这么多年产业结构调整不过来？为什么中国
目前只能是“世界加工厂”？为什么只能是“中国制造”？为什么资源环境问题越来越突出？……所有这些问题，都有一个共同的原因，就是科技进步不足，自主创
新能力不足。
       增强自主创新能力，需要的是决心和勇气。这么多年来全国研发资金刚刚超过GDP的1％，而国外普遍是2％～3％？我国大中型企业3／4没有研发机构
、研发投入也只有营业收入的1％左右，而外国跨国公司却普遍达到3％～5％甚至10％以上。出现这样的问题，我们的一些领导人和企业负责人难辞其咎。他
们缺少意识、决心和勇气。只要我们的决心、意志和注意力凝聚起来，“两弹一星”的业绩不难再现！
       中央提出要坚持把推动自主创新摆在全部科技工作的突出位置，是顺应形势要求的,是国家的重大战略抉择。
       自主创新从内容上包括三方面的含义：一是原始性创新，即通过科研和开发，努力获得更多科学发现与技术发明；二是集成创新，即通过各种相关技
术成果融合汇聚，形成具有市场竞争力的产品和产业；三是引进技术消化、吸收和再创新：在积极引进国外先进技术与设备的基础上，进行充分地消化吸收和
再创新。
       自主创新在过程上包括两个方面，一是知识创新，二是技术创新。知识创新是着重对自然界的研究并获得新发现，具有基础性特点，主要以大学和科
研院所为主体；技术创新则是着重将基础科学研究成果转化为技术服务人类，强调成果的应用性，它往往以企业为主体。知识创新和技术创新的有效衔接就在
于两个创新主体的有机结合。就是说，作为技术创新的主体的企业主动向高校和科研机构进行投入或者提出所需要的带有产业化的科研方向，以获取原创性成
果，实现原始创新。作为知识创新主体的高校和科研机构主动参与技术创新过程，用知识创新成果解决其技术创新的难题，主动将知识创新成果在企业转化。
    
       四、我国当代科技发展基本状况
       中国科技的发展速度被认为是史无前例的。目前，中国高技术领域的研究开发水平与世界先进水平的整体差距已经明显缩小，60%以上的技术接近国际
先进水平，25%的技术虽仍落后于国际先进水平，但在原来基础上也有了很大进步。
       中国科技飞跃发展变化主要发生于上世纪的后50年。从1949年11月中国科学院成立起到20世纪60年代，全国科研机构已增加到1600多个，遍布各主要
学科领域和技术领域；专业从事研究工作的科技人员有近20万人。2005年，我国R&D经费为2360亿元，占国内生产总值的比例为1.3%；从事R&D活动人员120万
人年，；科学家与工程师达98万人年，财政科技拨款总额为1270亿元，占国家财政支出总额的比例为 3.8%。
       来自中国科学院、高等院校、产业部门、国防部门和地方科研机构五方面的科技大军及它们的合理分工、互相配合，构成了中国的科研体系。中国科
学技术协会所属的160多个全国性的科技学术团体及其在各大、中城市设立的分支机构，也是科学技术研究的重要力量。
       20世纪80年代以来，政府陆续推出了一系列科学技术研究发展的整体计划，旨在战略性地全面提高国家在21世纪的综合科技竞争力。这些发展计划主
要有：
       《高技术研究发展计划》（简称863计划）：该计划选择了生物、航天、信息、激光、自动化、能源和新材料等7个高技术领域作为中国高技术研究发
展的重点，1996年又增加了海洋技术领域。迄今为止，政府向863计划投放了约110亿元人民币。15年来，该计划共获国内外专利2000多项，累计创造新增产值
560多亿元，产生间接经济效益2000多亿元。该计划培育出了高技术产业生长点，不仅极大地带动了中国高技术及其产业的发展，也为传统产业的发展提供了
高技术支撑。从2001年至2006年，863计划将集中资源对重大项目进行投资，总经费中的55%用于支持重大项目。首批安排的“超大规模集成电路”、“电动汽车”
、“软件”、“高速磁悬浮列车”、“功能基因组与生物芯片”、“创新药物与产业化开发”等十大项目已于2001年底启动实施。
       星火计划：是始于1986年的另一项全国性科技计划。该计划旨在依靠科技进步振兴农村经济，在农村普及科学技术、带动农民致富。科技的星星之火
已燃遍了广大农村。
       火炬计划：1988年，我国宣布在全国范围内开始实施一项高科技产业化发展计划，与“863计划”的侧重点不同的是，该计划通过建立一批被称为“孵化
器”的机构（也称创业服务中心）来加速高新技术成果的转化。火炬计划实施以来，在国家级53个高新技术产业开发区里，已建立了100多家创业服务中心。
       攀登计划：从1992年开始实施的此项计划目的是加强国家对基础性研究的支持，推动基础性研究持续稳定地发展。
       此外，中国也已先后同150个国家和地区建立了科技合作关系，同近百个国家和地区缔结了政府科技合作或经济技术合作协定。以民间形式开展的国际
科技合作与交流更为活跃。中国科协及其所属团体共参加了244个国际科技组织，有293人次的科学工作者在国际科技组织中担任执委会（理事会）执委（理事
）以上职务，281人次担任国际组织专业委员会领导职务；中国科学院有253名科学家在国际科学组织中担任职务；国家自然科学基金会已与36个国家的科学基
金组织签订了合作协议和备忘录。近五年来，中国引进国外专家超过40万人，派出培训的各类技术管理人员约20万人。
    
       五、科技创新的国家规划
       按照科学发展观的要求，我们在全面建设小康社会的过程中要实现可持续发展；而可持续发展就必须依赖于科技的进步。社会可持续发展的基础是经
济发展，必要条件是环境保护，而核心是科教。科技在发展生产与经济过程中起的作用所占比重，今天已达60—80%，美国更是高达90%以上，而高科技的作用
更是举足轻重（据世界银行统计，高技术和技术含量较高的商品占各国出口商品的比重，日本高达97％，德国为90％，美国为82％）。
       胡锦涛总书记在第四次全国科技大会开幕式的讲话中提出：中国未来15年科技发展的目标是，2020年建成创新型国家，使科技发展成为经济社会发展
的有力支撑。而“创新型国家”的标准是：科技促进经济社会发展和保障国家安全的能力要显著增强，基础科学和前沿技术研究综合实力要显著增强，并要取得
一批在世界上具有重大影响的科学技术成果。
       为了适应形势的发展变化，加速科学技术事业发展，国务院研究制定了《国家中长期科学和技术发展规划纲要》，确定了到2020年中国科技发展的重
点和基本部署：优先发展能源、水资源和环境保护技术；掌握装备制造业和信息产业核心技术的自主知识产权，提高我国产业竞争力；大幅度增加对生物技术
研究开发和应用的支持力度；四是以为重点，突破重大成套装备和高技术装备、新一代绿色制造流程和装备、制造业信息化等一批产业关键技术，全面提高重
大装备和产品制造的自主创新能力；超前部署基础科学和前沿技术，努力发展空天技术和海洋技术。未来5年，还特别注重加强农业、卫生、环境、城市和城
镇化等公益性的科技发展，以提高人民的生活质量、保证公共安全。同时还把加强国家和区域创新体系建设，支持地方科技事业的发展，作为重要的发展基础
和制度保障。
       十一五期间我们把增强自主创新能力放在更加突出的位置，要解决好这样几个方面的问题：第一是要把解决经济社会发展的瓶颈制约放在优先位置，
力争在能源、资源、环境、农业、信息等关键领域取得重大突破。第二，积极发展对经济增长有重大带动作用，具有自主知识产权的核心技术。第三要继续加
强基础研究和前沿技术研究，在信息、生物、空间、海洋、纳米等领域超前部署，加强重大科技设施和条件的建设，实施若干重大科学计划。第五，按照有所
为有所不为，进一步集中重点，集中优势力量启动实施一批重大科技专项。
    
    五、近几年取得骄人成绩
       1、世界首个血管内皮抑制素抗癌新药
    烟台麦得津生物工程股份有限公司研发的抑制和治疗肿瘤的抗癌新药“恩度”，正进入药品上市的审批程序，顺利的话，明年春节后将能上市。专家说，这
一新药的诞生，意味着抗癌新药也有了“中国造”。
    2、中国第一台可以投入临床应用的全身CT机
    　　曾经，进口CT机等医疗设备长期垄断国内市场。1997年10月，中国第一台可以投入临床应用的全身CT机在东软问世，继美国、德国、日本之后，我国
成为第四个能够生产CT机的国家。
    　 3、技术领先世界的振华港机
    　　世界首创的用于自动化码头双小车岸边集装箱起重机等100多项专利技术先后诞生。正是凭着世界领先的技术，振华港机已连续6年居全球市场占有率
榜首。
       4、中国芯
    　　结束我国彩电没有“中国芯”的历史———“信芯”：
    　　今年6月底，海信集团研制成功我国音视频领域第一块自主知识产权的数字电视处理芯片———“信芯”，结束了我国年产7300万台彩色电视却没有“中国
芯”的历史。
    　　奇瑞：第一颗汽车中国“芯”
    今年4月，奇瑞ACTECO发动机（见中图）投产，这使中国轿车拥有了第一颗“中国芯”，发动机水平与世界差距缩短了20年。　　
    我国首款64位高性能通用CPU———“龙芯”二号：
    　　2005年4月，由中科院计算所研制的高性能通用处理器“龙芯”二号问世，是国内首款64位的高性能通用处理器CPU芯片，功耗和成本均远低于国外相当
的芯片，但性能已经超过威盛的C3芯片。该芯片是我国拥有完全自主知识产权的产品。不久，国家智能计算机研究开发中心与曙光信息产业公司宣布将部分采
用“龙芯”处理器，力争在2008年前后研制出进入世界前三强的高性能计算机。
       5、中国3G标准走向商用
    　　11月中旬，3G中国标准TD—SCDMA先进入欧洲市场，罗马尼亚运营商决定建设海外第一个TD—SCDMA试验网。这意味着中国3G标准开始走向世界。
TD—SCDMA将确立我国在全球3G市场的重要地位。
       6、我国家电企业发起制定的第一个国际标准
    　　12月初，国际标准委（IEC）大会主席宣布：海尔防电墙技术正式通过IEC组织的关于生产工艺和检测流程的审议。这意味着明年在伦敦举行的第七十
届IEC大会上，防电墙技术将正式成为国际标准。
    7、超一流企业卖标准
    　　今年5月，中国国际海运集装箱（集团）股份有限公司取得了2011年国际集装箱标准化技术委员会（ISO/TC104）年会的主办权，使这个负责国际集装
箱制造和操作标准管理的机构的“标准”大会首次移师中国。目前，中集拥有ISO国际标准化组织委员1名；参与起草4项ISO国际标准；研究并提出了近20项有针
对性的提案和意见，并被ISO组织编号后作为正式文件公布。
       8、集成电路装备获得突破
    科技部、北京市和中电集团等有关企业共同投入研发资金，研制出适合8英寸硅片100nm工艺微电子芯片制造关键设备、高密度等离子体刻蚀机和大倾角注
入机试生产样机。
    100nm分辨率148nmArF准分子激光步进扫描投影光刻机，目前正处于分系统验收、内外配套件集成并总装的阶段，有望在今年底完成。
       9、高档数控系统取得进展
    经过“十五”前各类科研项目的支持，我国中档以下数控系统的国产化率已超过50%，“十五”期间科技项目支持的重点是高档数控系统的研发。
    我国研制并生产了十多台为东方汽轮机厂开发的加工60万千瓦汽轮机、40英寸大型叶片用五轴联动大型叶片加工中心，加工精度与加工效率可与进口瑞士
同类机床相当。
    研制成功大型舰船螺旋桨用重型七轴五联动车铣复合加工机床。可实现螺旋桨的一次装夹多表面的加工。
    面向飞机大型板类件加工的横梁移动式龙门五轴加工中心问世。
    光学非球曲面超精密磨削技术及设备研究项目研制成超精密铣磨纳米加工设备。
       10、部分能源装备实现自主研发
    “十五”期间，科技部安排了兆瓦级风电机组研制，自行研制的1兆瓦级变桨距双馈式变速恒频和1.2兆瓦无齿轮箱直驱永磁两种风力发电机组于2005年实现
并网发电。
    新型水煤浆气化技术经过国家科技计划的连续支持取得突破。  
       11、工程机械技术竞争力提高
    在工程机械方面，我国掌握了液压、刀盘、测控及系统集成等土压平衡盾构机的关键技术，成功研制出6.34米国产土压平衡盾构机2台，并在上海地铁施
工中得到了实际应用，并有20多台已经中标，将陆续投入使用。
       12、乙烯裂解炉达到国际先进水平
    13、镁合金压铸装备主体实现国产化
    14、今年以来，我国装备制造业捷报频传
       ４月１２日，沈阳鼓风机(集团)有限公司与中国石化股份有限公司天津分公司签订了１００万吨／年乙烯装置裂解气压缩机组合同，这标志着我国开
始拥有百万吨级乙烯装置的核心部件；
       ６月１１日，华能玉环电厂运营的国内首套国产百万千瓦超超临界机组，即国内单机容量最大的火电机组，在经历了半年成功运行后，经测试主要技
术指标均达到国际先进水平；
    ７月１０日，哈尔滨电机厂有限责任公司制造的三峡工程首台国产化７０万千瓦水电机组正式投产，我国水电装备步入自主研发时代……

       美丽的长卷展开了，勤劳智慧的中国人民已经添上了浓墨重彩的一笔。让我们乘着十七大的东风，在胡锦涛总书记的带领下，坚决贯彻科学发展观，
戮力同心，合衷共济，共创中华民族的美好未来！                                                                                              
                2007-10-18 20:02
                

** 【奋进社/金鸿95】关于教育下一代的一点思考

最近，又看到出现了一个名为《香烟爱上火柴》的流行歌曲，感觉就象《狼爱上羊》、《狐狸爱上熊》一个套路。这类有违伦理的的歌曲（《香烟爱上火柴》
里面有一句歌词“老鼠爱上猫咪…”）相关的文化管理部门该出手管管了，清理一下这些文化垃圾！难道它们对这个社会的危害还少吗？

看看监狱里的少年犯们，有几个没有受过色情、暴力方面的书籍影视等文化垃圾的熏陶？这样的教训还少吗？

在我们周围，经常有人说八零后、九零后的人的年轻一代基本报废了，这样的观点有点偏激，不过，在年轻一代身上表现出来的整体素质的确堪忧。但是，大
家有没有想过，他们为什么会这样？难道他们就不是受害者？他们可是八零年以前的人教育出来的呀！问题出现在孩子们身上，可问题的根源又出现在谁的身
上呢？

我个人认为，在年轻一代身上出现这样的情况，应该有三个方面的原因：

1、教育（家庭和学校）教育的失误。只要学习好就一俊遮百丑，只重视智育忽视德育（体美劳今天不讨论）教育出来的下一代出现了多少笑话！说几个报纸
上登过的小例子：小两口结婚几天就去离婚，一问原因，说是一个人喜欢牙刷头朝下放而另一个喜欢头朝上放，因为谁也不牵就对方所以过不下去了；刚刚生
的孩子就扔路边了，原因是两个人都嫌对方关心孩子少；新考上研究生，家里没钱支持，逼着老母亲进城清理厕所来供自己上学﹍﹍

2、社会风气的影响，一切向钱看，把我们的小太阳们培养的八面玲珑，处理起人际关系来比成年人还要熟练（至于许多年轻的女孩子嫌挣钱少不够花销干卖
身的兼职挣外块大家也就不要大惊小怪了，大家要做的事是，求上苍保佑不要娶到这样的女孩子）。

3、文化垃圾的影响，举个例子，现在的孩子为什么如此的性早熟？没有电视连续剧的功劳，能这样吗？三岁的孩子就整天哼着情呀爱呀的流行歌曲，难道还
不让我们震惊吗？他们懂得什么是爱！

孩子是无罪的，他们渴望长大、渴望成熟，为了达到这个目的，他们就会有意无意的向各种所能接触到的“榜样”模仿。所以，在孩子们面前，我们每个人都应
该告诉自己：“所有中国的孩子都是我的孩子，我应该用话语和行动去教育我所接触到的每一个孩子！”并且将它溶入到自己的行动中。

给大家讲一个小故事，说的是在一个小村子里，家家户户都种南瓜。有一个瓜农为了产量更高就努力的改良自己的南瓜品种，在他的努力之下，取得了不错的
结果。这时，一件常人意想不到的事情出现了：他免费的把自己的优质的南瓜种送给邻居们种。有人就说，你高价卖给他们不好吗？这样还有好的收入？他的
回答是：“如果我的邻居们不买，他们的南瓜产品种不如我的，在蜜蜂授粉的过程中，就会把邻居们的不好的南瓜花粉授到我的南瓜里，从而让我的南瓜品种
也越来越差。为了我的南瓜越结越大，我必须让我的邻居的南瓜品种也变好。”教育孩子也是一样，孩子是生活在他和小伙伴们的圈子里的，如果他周围的小
朋友都不学好，那他也肯定跟着学坏。这也是近朱者赤、近墨者黑的道理。为了创造一个对所有孩子成长都有利的环境，我们所有的人都应该行动起来，都要
为我们的下一代做出好的榜样！

另外，要加大力度清楚各种文化垃圾。对于有毒的食物，大家都知道避而远之，谁也不会去主动吃这些东西，如果事先知道的话；但是，对于文化垃圾就是不
这样了，特别是孩子们，他们辨别是非的能力有限，面对着各种新奇、个性、另类的文化垃圾，他们不但不会感到讨厌，反而感觉“好玩”-----好奇是人的天
性。这种潜移默化，对孩子们的杀伤力才是最大的！而孩子们因为知识有限、经验欠缺斟别能力，这就需要我们的社会还为他们设置防火墙。

为了我们的民族后继有人，为了我们的国家繁荣昌盛，我们需要高素质的人民----是整体素质高而不能寄希望于个别的精英。为了达到这个目的，所有有良知
的中国人都得行动起来，因为，你责无旁贷！


** 【奋进社/金鸿95】国际时事评论(2007/11/3)

　　英国《泰晤士报》记者萨拉·巴尔斯特28日撰文认为,布什政府已经为此做好军事、政治、外交和舆论准备。如果强硬外交路线无法奏效,布什有可能在他
的最后一年任期内发动第三场战争。
布什先生最近不太顺利，无论是国外的敌人，还是国内的对头，都一致的评价他有“神经病”，一个总统有神经病可不是闹着玩的，当然，还有更有意思消息也
冒了出来：
美国佐格比(ZogbyInternational)民调公司29日发表最新民调指出，有52%的美国选民支持美国政府，“为了阻止伊朗开发核武器”而对伊朗采取军事行动。
这项电话调查据说是从全美超过1000位选民中进行的。这里面的数据有没有造假我们不得而知，不过，在10月27日美国的11个城市同时举行反战游行，其中规
模最大的旧金山的有3万人参加了，示威者中有不少人反对美国政府对伊朗开战。这两个截然相反的情况同时出现确实值得玩味。
拿下伊朗摆平中东是美国的既定战略，看来他们对此是不到黄河不死心了。打伊朗的理由就是美国在搞核武器，而有趣的是，巴拉迪28日刚刚表示，没有证据
显示伊朗正在研制核武器，美国对伊朗的政策是在给该问题“火上浇油”。
欲加之罪，患无辞乎？
美国也很清楚，在现在如此被动的局面之下，布什也知道直接对伊朗动手是不可能的。仅仅一个伊拉克泥潭就让布什团队一个头两个大！
我们先看一下伊拉克的局势：

　　驻伊拉克美军29日向伊拉克当局移交了卡尔巴拉省的防务。至此，联军已经向伊方移交了18个省中8个省的防务。
移交防务并不代表美国要撤军。事实上，美国参议院21日表决的一项限期从伊拉克撤军的法案刚刚搁浅。
在移交8个省防务的当天，10名逊尼派的部族长老被人绑架了（为了迷惑善良的人们，基地组织又背了黑锅，这十名部族长老号称都在主张打击基地组织的）
，绑架他们的是逊尼派的死对头叶会派的武装分子。按照正常的逻辑，逊尼派的武装势力也该对叶什派下手了。美国人精心制造的伊拉克内战一触即发的局面
出现在了阿盟、欧盟的面前，接下来，大家该考虑一下，如果伊拉克大规模内战暴发了，自己会亏多少？如果自己随不了接下来的后果，那么，就该反过来再
求美国大兵出面稳定局势了，美国人说的明白，防务移交后，美军只有在“紧急情况下或应伊拉克当局要求时”才会出动。在吓唬人之余，美国人还没忘记给周
围的邻居递上一个胡萝卜：
新华网大马士革10月30日电正在叙利亚访问的美国国务院负责伊拉克难民事务的高级协调员詹姆斯·福利30日表示，美国愿与叙利亚政府及国际社会合作，以
缓解伊拉克难民的苦难和给接收国造成的消极影响。
看来，为伊拉克反美武装提供支持的不仅仅是伊朗，叙利亚绝对有份！所谓“以缓解伊拉克难民的苦难和给接收国造成的消极影响”是假，从叙利亚方向切断伊
拉克反美武装与外界的联系是真！
这也是一个小小的试探：如果叙利亚很配合的切断了伊拉克反美武装的通道，那么美国肯定会给叙利亚以好处。其他的方向，如沙特、科威特方向自然更容易
对付；再回手以管住库尔德武装为价码逼土耳其也就范了，那就只剩一个刺头伊朗了，接下来就可以把伊拉克内战引入伊朗境内，如果伊朗扛不住也低头了，
那么美国极有可能扭转局面反败为胜。
可惜，人算不如天算，首先，土耳其第一个出声了：
土耳其外交部长阿里·巴巴詹11月1日表示，土耳其部队越境进入伊拉克，打击库尔德工人党武装及围剿其基地的行动不算“入侵”。
拿着枪到别国的领土上抓人杀人还不算入侵，这叫什么道理？这个道理很明白，美国人带着枪可以伊拉克“放火”，那么，土耳其人自然可以在伊拉克“点灯”（
想让土耳其与美国合作，难！当初库尔德武装之所以与土耳其干起来，与土耳其不配合美国的中东战略直接相关）。在土耳其对库尔德武装死死不让步之时，
伊朗方面也传来了新的消息：
为了解决伊拉克的安全问题，伊朗希望与美国进行新的对话。这是正在伊拉克访问的伊朗外长穆塔基昨天在巴格达与伊拉克外长兹巴里会谈后举行的记者招待
会上讲这番话的。
第一次见波斯人对美国人这么有善意，只怕美国人不敢领情！至于下一步美伊合作会再传出什么消息，我们拭目以待。

在伊拉克局势没有丝毫毫转的同时，阿富汗又传来了坏消息：阿富汗塔利班“国防部长”毛拉-达杜拉声称，塔利班将发动更为猛烈的冬季攻势，将在南部地区
发动“起义”。在他喊话的同时，数百塔利班武装人员在坎大哈附近频频活动，与驻阿联军和阿富汗安全部队激烈交火。很显然，这是塔利班在有意识的用行动
配合这位国防部长。[/b]
在伊拉克阿富汗无解、伊核无助、巴以和谈无奈的背景之下，美国为了集中力量先收拾好中东乱局，在东面的朝核谈判中咬着牙让步，于是乎，朝鲜弃核进程
出现了可喜的进展。一起看一下：

[b]　　首尔10月29日电韩国外交通商部朝核外交企划团团长林圣男29日在板门店说，朝鲜方面当天表示将从11月1日起开始对其核设施实行“去功能化”，并切
实履行第二阶段弃核措施。另据韩国联合通讯社29日报道，朝鲜已经提出一份要求提供发电设备等援助的详细清单。
老金很会搞创收，援助自然是以老美为首来买单。来看，这1.03亿美元很快就到位了，虽然不以钞票的形式。
为了对老金示好，展示自己的诚意，老美也做起了好人好事：一艘朝鲜货轮29日晚在索马里首都摩加迪沙外海遭武装海盗劫持，海盗要求支付1.5万美元赎金
，但货轮上22名朝鲜船员30日制伏海盗，强行夺回货轮掌控权。在冲突中至少2名海盗身亡，另有5人被抓获。看到这里，我们还没来的及为朝鲜兄弟的神勇鼓
掌，美国海军就出来抢功劳，他们发表声明称，曾经帮助朝鲜船员制服海盗。眼看着自己的主子在老金面前变成了一个软骨头，有人大为恼火：
据日本媒体10月30日报道，由于连续10年未交租金，日本政府正在考虑对美国驻日大使馆提起诉讼，要求其偿还所有拖欠资金。美国大使馆位于东京中心地带
，按照合约，美国向日本政府承租一片面积为1.3万平方米的国有土地。1998年，日本政府提出增加租金，但是遭到华盛顿的强烈反对，从那时起，美国就停
止支付租金。
　这则消息足以让人喷饭。大笑之余，我们可以得出一个结论，，吃霸王餐与有没有钱没关系，与有没有力气有关系。从另一个方面讲，在对小日本的正确态
度方面，美国人为我们做了一个光辉的榜样。
在小打小闹没捞回自己想要的东西之后，福田又开始对着他的主子耍起了“胡萝卜加大棒”的把戏：
11月2日，日本首相福田康夫再次会晤最大的在野党民主党代表小泽一郎，寻求尽快重启自卫队在印度洋的供油活动。由于日本政府未能与国会就新反恐特别
措施法案问题达成一致，防卫大臣此前一天下令撤回在印度洋执行供油补给等任务的两艘战舰。
据日本时事社2日报道，日本国会众议院在当天下午召开的全体会议上批准对朝鲜经济制裁期限再延长半年，参议院也将于近期审议。
福田一面在美国人非常关心的在印度洋为美英等国军舰提供燃料补给问题上积极努力，周旋于执政党与在野党之间，尽心竭力可以一斑；另一方面对着老金痛
下重手，经济制裁不单不解除，反而在还在远没到期之就再行追加。
这与前几天高村在解除对朝鲜经济制裁问题上的圆滑回答形成鲜明对比。看来，福田的脾气也上来了：如果美国人还想指望他出力的话，那就不要再对朝鲜让
步，不要再出卖日本人的利益，否则，搅你的局！
为了防止断了老金的财路，北京也在关键时刻出了一把手，开始拿日来处理在遗弃化学武器中的资金迟迟不到位说事，显然是在警告福田最好规矩点，否则将
遭到来自北京和华盛顿的双重打压（中美居然又做了一把朋友）。

朝核局势中，北京唱主角莫斯科唱配角；伊核局势中，莫斯科在前后北京在后台。为了让伊朗的国家安全更有保障，老熊还真没闲着，妙手连出：
　　俄罗斯战略火箭兵29日在哈萨克斯坦境内的拜科努尔发射场试射了一枚ＲＳ－18型洲际弹道导弹，导弹准确命中位于堪察加半岛的目标。
试射是打着“检验超期服役的ＲＳ－18型洲际弹道导弹的技术性能”的旗号进行的，可是，这枚导弹是问候谁的，谁心里最清楚。仅仅过了一天，被问候过的主
儿就自动站出来了：
据俄新网消息，美国军方在夏威夷成功进行反导系统新型武器试验。试验中拦截导弹在飞行最后一分钟击落弹道导弹。
按照美国导弹防御局(MDA)的说法，这次试验的目的是拦截地球大气层外导弹。美国人比较实在，那枚RS-18洲际导弹正好对得上号。其实，这样的把戏也就是
自己给自己壮一下胆子罢了，没有什么实际价值。俄罗斯的战略导弹是能变轨的，美军根本防不住。
在打打导弹之余，老熊也没忘记再搞搞磨擦：
据香港《文汇报》报道，前苏联加盟共和国格鲁吉亚警察前天在边境与俄罗斯维和部队发生冲突，格指俄维和部队非法闯境，总统萨卡什维利前天亲自到场表
达不满，并下令俄国维和部队离开，事件令两国关系再度紧张。
冲突时，俄国维和部队殴打和扣留5名格国警察，至于打人抓人的原因，老毛子的说法是格国警察先威胁开枪。毛子的逻辑很简单：你敢吓唬老子，老子就揍
你！
再联想到10月28日格鲁吉亚著名寡头巴德里-帕塔尔卡齐什维利在伦敦宣布准备依法向国内反对派提供财政资助这一点，我们有理由相信，俄罗斯非常渴望在
格鲁吉亚搞一场反颜色政变，重新把斯大林的故乡抱入怀中。
在俄罗斯的重点照顾之下，波斯人也是狠话不断，号称要用肉弹对付美国大兵。在威胁无效之后，美国人又软了下来：
美国白宫女发言人佩里诺30日对记者发表谈话说，人们不要担心美国要对伊朗进行军事打击，美国正在通过可能的外交途径解决伊朗核问题。她还披露说，“
美国政府将与盟国共同努力，迫使伊朗放弃打着和平的旗号制造核武器的计划，下个星期，布什总统将与到访的法国总统萨科齐和德国总理默克尔就这一问题
举行会谈”。
美国人话音刚落，伊朗官员与来访的国际原子能机构工作组在1日就结束了为期4天有关伊朗P－1和P－2型离心机问题的最后一轮会谈，而且，伊朗和国际原子
能机构都对会谈的趋势感到满意。
看来，巴拉迪也不是好欺负的，国际原子能机构这回是一点面子都没给美国人留。布什该后悔了，当初得罪这尊大神干嘛来着？
当然，有一点不能不说，就是，美国对伊朗的经济封锁还是给伊朗制造了不小的麻烦（虽然伊朗的经济垮不了）。虽然伊朗中央银行29日公布本财政年度上半
年（3月至9月），伊朗能源出口总收入高达256．25亿美元，比上年同期提高1．1％。相信在接下来的日子里，上合成员国和其他亲伊朗国家都会加大与伊朗
经济合作的力度，当然，对中国企业而言，这也是个机会。因为美国是没有能力对伊朗发动大规模的空袭的。搞搞小磨擦倒是可能，只怕伊朗的报复会非常猛
烈。

当然，美国也有相对主动的一面，就是在巴铁通道上。
一方面巴境内依然不安定，爆炸不断；另一方面，巴基斯坦最高法院对对穆沙拉夫竞选连任案依旧没有判决，并且又提出了一个条件，就是逼穆沙拉夫同意让
谢里夫回国。[b][/b]
当年，穆沙拉夫就是发动政变把谢里夫赶下台才当上的总统，现在让谢里夫回来绝对是一个大麻烦，这个条件是穆沙拉夫极难接受的。有强硬的上合撑腰，老
穆大可强硬一把！

** 【奋进社/金鸿95】老穆，干的漂亮！

[2007-11-04 20:41:43]

  进入紧急状态后的巴基斯坦局势跟踪之一

这条新闻我已经苦苦等了很久，今天才盼来，真不容易。为了它的到来，搞一篇。

先看看这则喜讯：

　　新华网伊斯兰堡11月3日电（记者饶博）巴基斯坦总统、陆军参谋长穆沙拉夫3日宣布在全国实行紧急状态并同时颁布了一项临时宪法令。

　　据官方的联合通讯社报道，根据临时宪法令，宪法将被中止；参议院（上院）和国民议会（下院）以及旁遮普省、信德省和俾路支省的省级议会将维持正
常运作；联邦和省级内阁将维持正常运作，联邦政府总理以及省首席部长和省长均将保留原职。

　　据当地媒体报道，穆沙拉夫宣布实行紧急状态后，巴警方包围了最高法院，首席大法官乔杜里和其他几名法官被解职。各大城市没有发生骚乱事件。巴有
关方面在首都伊斯兰堡各主要路口部署大量警力，严密盘查往来车辆。据悉，伊斯兰堡将在未来几天内维持高级别警戒水平。

老穆终于强硬出手了。应该说，这是在意料之中的事情。为了今天的强硬出手，老穆也做了不少工作，下面我们回顾一下老穆之前所做的两个关键性动作：

1、  打狗给主人看

打狗的动作发生在10月上旬：

巴基斯坦战机10月9日轰炸部落地区武装分子的藏匿处，使巴军方为讨伐叛军而在此一地区激战4天以来造成的死亡人数上升至250人。当地的很多平民逃离了
冲突地区。部落长老呼吁双方停战。

当时我在10月12日的评论中给出的观点是：

“我们最关心的是：这些被打死的叛军是谁支持的？

回头想想，被老美折腾烦了的老穆死活要穿着军服参加巴基斯坦大选，无奈之下的美国人只好任其所为。在老穆高票当选之后，又推着反对老穆的人出来搞什
么上诉-----怎么着呀，还想废了老穆到手的大位不成？

于是乎，老穆开始用枪炮说话了：那些多事的人再不收手的话，俺可要扛着枪去总统府上岗了！”

此时的老穆虽然真火了，还没打算撕破脸皮，只是希望通过打击反判武装从侧面敲打一下美国，给自己一个下台阶（承认总统大选合法），体面的解决问题。
可没想到，有人硬是给脸不要脸，反而以各种理由把对老穆总统合法性的裁判日期一推再推，直到把老穆彻底推到了自己的对立面。

2、  以赖对赖

这个发生在１０月２７日：

巴基斯坦铁道部长拉希德２７日说，巴总统穆沙拉夫将在巴最高法院就其竞选总统连任资格案作出裁决后再决定是否不再担任军职。

对此消息，我在30日的评论中给出的观点是：

“老穆的意思很明白，如果法院有胆量不判老穆的总统之位合法，那么老穆有就胆量用手中的枪炮为自己的总统位置合法性做证明。如果没记错的话，当年老
穆就是发动政变上的台，既然曾经有过初一，那么再有个十五也是很正常的事。枪杆子里面出政权，这是公认的真理。

如果真到了那一步，那么某些人可就是赔了夫人又折兵，既得罪了老穆还没捞到好处。还想老穆在阿富汗帮忙？还想抢巴基斯坦通道？做梦去吧。

有了老穆如此强势的动作，我们有理由相信，巴法院很快就会判老穆的总统之位合法。”

在此，再解释一下“以赖制赖”的含义：我老穆已经仁至义尽了，你们就不要逼我了。否则我可真要翻脸了。此时，老穆是真火了，这次的警告完全是摊牌式的
。

3、逼上梁山

没想到美国人愣是不知进退、不知死活，不但不见好就收，反而变本加厉：

巴基斯坦首席大法官乔杜里30日命令政府允许前总理谢里夫回国，并表示政府9月再次将谢里夫驱逐出境，违反了最高法院稍早的判决。

对于这则消息，我在3日的评论中给出的观点是：“当年，穆沙拉夫就是发动政变把谢里夫赶下台才当上的总统，现在让谢里夫回来绝对是一个大麻烦，这个条
件是穆沙拉夫极难接受的。有强硬的上合撑腰，老穆大可强硬一把！”

果然，老穆强悍的出手了，第一个收拾的就是这个狗腿子乔杜里。

虽然这次行动不是政变，但达到了与政变相同的效果。新任的首席大法官是老穆推上去的，在接下来的判定其总统选举合法性问题上会做出什么判决我们就不
用去动脑子想了，那是秃子头的虱子----明摆着的。

接下来，该美国人难受了：怎么面对老穆的“专制行为”呢？

平静接受吗？“民主”的招牌还挂不挂？

不接受？回头还指望不指望老穆帮忙给阿富汗困局解套？

干掉老穆？如果不怕巴基斯坦的核武库里的原子弹落到伊斯兰极端势力手中那就干吧。

布什先生会做出什么选择呢，估计最多是嘴上骂两句也就过去了；如果聪明的话，最好闭上嘴。

应该说，老穆选择了一个非常好的出手时机。此时，布托正在出国探亲回家的路上。老穆一玩硬的，就等于逼布托提前选队伍站位，是选择亲华还是亲美？

如果亲华，那就是接受现实，明年的总理极有可能是布托的，这样一来，老穆可以团结到尽可能多的国内支持，布托也可以咸鱼翻身。相信随着中巴经济一体
化的推进和充当中印石走廊带来的经济回报足以让巴基斯坦人民富裕起来，一旦经济问题解决了，什么矛盾都好化解。

如果亲美，那么接下来的命运，要么是继续流亡，要么是被以贪污罪的名义投入监狱。这两个结果哪个都不乐观。

我个人认为，布托选择亲华的可能性更大一点。毕竟，华盛顿给不了巴基斯坦太多东西；而北京就不同了，那可是一个全天候的战略伙伴。孰重孰轻，一目了
然。

** 【奋进社/金鸿95】紧急状态后的巴基斯坦


  进入紧急状态后的巴基斯坦局势跟踪之二

    一、从几个侧面看巴的紧急状态  

    1、坚定的支持者：北京  

外交部发言人刘建超６日 刘建超在例行记者会上说，巴基斯坦是中国的重要邻国，中方高度重视、关注巴基斯坦局势发展，相信巴基斯坦政府和人民有能力
解决自己的问题，希望巴基斯坦保持稳定和发展。   

   【金鸿评论】北京的态度很简单，我们的巴基斯坦兄弟有能力解决自己的问题，所以，某些打算管管闲事的人最好不要乱伸手，以免自讨没趣。当然，这
个态度和3日的表态略有差别，就是多了一句“巴基斯坦是中国的重要邻国”，既然是重要的邻居，那么如果出现了自己不想看到的事情的话，那北京绝对不会
坐壁上观的。当然了，从北京四平八稳的态度来看，一切都在掌握中。  

不知道大家注意过没有，在穆沙拉夫宣布国家进入紧急状态前几天，网上有一篇文章广为流传达，题目叫《这条路永远对中国开放》，这篇文章让许多朋友感
觉“特别爽”，现在回头想想，这是不是老穆在行动之前做的一点舆论准备工作？  

在巴基斯坦进入紧急状态后，巴基斯坦当地最大的报纸发表文章称，巴政府要求紧急状态令执行后，要高度关注当地中国人的生活，加强对中国人人身安全的
保护力度。这一点足以和上面的那篇文章相互响应起来，它展现出来的一个事实就是：在外交取向上，巴基斯坦，穆沙拉夫，优先考虑北京的利益。  

这样的兄弟，我们不能好好对待？  

2、布托：利益的共享者  

　　据路透社报道，在巴基斯坦穆沙拉夫总统宣布巴进入紧急状态后，巴当局今天(4日)逮捕了前总理贝-布托所属政党的一位高级领导人和数位反对派人士。

据巴基斯坦媒体4日报道，巴前总理、人民党主席贝·布托呼吁巴总统穆沙拉夫取消紧急状态并恢复宪法。贝·布托4日在接受采访时补充表示，她同意穆沙拉夫
的“诊断”，即国家正面临极端主义日益增长的威胁，但在“治疗方法”上与穆沙拉夫有分歧。  

【金鸿评论】老穆抓布托的手下，无非是杀鸡给猴儿看：要么跟我走，要么在国外呆着；如果回国跟我对着干，监狱里有地方盛你，抓人的理由是现成的，腐
败。而布托在第一时间飞了回来，其行动本身就说明，她上了老穆的船，并且人家也说了，同意穆沙拉夫的“诊断”。  

至于她的“呼吁取消紧急状态并恢复宪法、但在“治疗方法”上与穆沙拉夫有分歧”，是为了告诉方方面面，搞紧急状态是老穆自己的主意，自己不是同谋，跟自
己没关系。  

3、美国：无奈的失意者  

美国对巴基斯坦总统穆沙拉夫宣布紧急状态持谨慎态度，3日敦促穆沙拉夫遵守承诺，在明年早些时候举行自由选举。白宫国家安全委员会发言人戈登-约翰德
罗说，所有相关各方均应尽快并且和平地“沿着民主道路”前进。正在土耳其访问的美国国务卿赖斯此前表示，她对穆沙拉夫宣布紧急状态深感不安。赖斯说，
“美国的立场已经非常清楚，那就是不支持采取超越宪法的措施。我们将会敦促他们承诺举行自由公平的选举，同时敦促各方保持冷静。”  

【金鸿评论】我就搞不明白，老穆又没有抓你的情郎，赖斯你不安个什么劲？巴基斯坦跟美国隔着十万八千里呢，管你什么事？  

随着老穆动作的增大，局面越来越让美国感觉失望，于是号称不想批评老穆的布什跳了出来：  

    华盛顿消息：美国总统布什要求巴基斯坦总统穆沙拉夫结束巴基斯坦的全国紧急状态并回复民主。这是布什在穆沙拉夫宣布全国进入紧急状态后，首次就
巴基斯坦的局势表态。   

　　布什在白宫办公厅与土耳其总理举行会谈之后，对美巴反恐合作给予了一定的肯定。他说：“穆沙拉夫在打击恐怖主义、极端主义方面是一个强有力的斗
士。”  

美国当局正检讨目前对巴基斯坦政府数十亿美元的援助计划。但有媒体表示，由于巴基斯坦对美国非常重要，因此美国不会因此而停止对巴基斯坦的援助。  

【金鸿评论】不看别的，就看布什这打一巴掌揉三下的投鼠忌器的劲儿，就知道，一旦老穆真翻了脸，布什是一点招儿都没有！早知今日，何必当初？你干嘛
把人家老穆逼到这一步呢？  

接下来，老穆大可放开手脚干，如果布什希望巴早一点解除紧急状态的话，最少让自己的那些狗腿子们安静一点，不要再上街闹事了！  

至于威胁打内战，这种没有任何含金量的威胁还是收了吧。人家老穆可是说了，宣布进入紧急状态的原因就是“恐怖主义和极端主义的蔓延发展已经危及巴基
斯坦的主权”，如果有人愿意进这个套的话，岂不是给老穆的行动做了一个很好的证明？  

事实上，恰恰相反，在这个巴国内矛盾最容易激化的时候，却连一声大的爆炸都没有听到。这也正好让我们看出来，那些天天搞爆炸的“恐怖分子”到底是些什
么玩艺！（当然，在巴阿边境地上，路边炸弹伤了一个巴国士兵，这只能算是小打小闹）。  

4、印度：怕事的邻居  

印度边境安全部队(BSF)指挥官迈特拉将军向印度报业托拉斯证实，印度军方目前已经将提升边境戒备等级的命令下达到驻扎在查谟和克什米尔地区、旁遮普
邦、拉贾斯坦邦、古吉拉特邦的一线部队。  

【金鸿评论】印度人为自己的行动找的理由是：“在巴基斯坦全国进入紧急状态之后，巴政府军未来可能会加大对极端分子的打击力度。为防止圣战分子可能
潜入印度逃避打击，印度政府随即命令军方提升印巴边境地区的戒备等级。”  

这个理由可谓冠冕堂皇。其实，印度人担心的是巴基斯坦的部队在边境上搞磨擦。因为现在是巴国内矛盾最容易激化的时候，一旦局面出现了不利于老穆的变
化，出于转移国内人民注意力和国内注意力的考虑，在印巴边境上闹点儿事出来是很正常的。这样可以减轻老穆自己的压力。出于怕吃亏的心理，印度加强边
境的戒备等级就很自然了。  

其实，印度人的心眼也忒小了点。就算老穆真找事，也不可能引发大规模的冲突，如此一来，就算吃亏又能吃多少？何必兴师动众呢？搞得生怕天下人不知道
似的。三兄，想办大事呢就得有大胸襟、大气魄，否则，就别动不动跟这个比、跟那个攀了，你的个头还不够呀。  

5、伊朗：凑热闹的朋友  

伊朗方面5日还宣布，伊朗代表将与巴基斯坦代表9日将签署“和平管道”最终协议。伊朗代表卡尼姆·法尔迪说，应伊朗的邀请，巴基斯坦石油部副部长将于7日
抵达德黑兰，并与伊朗能源部长为签署“和平管道”协议举行会晤。  

【金鸿评论】在这么敏感的时刻搞出这么大的动静，也只有刺头的伊朗会办了。这条能源管道对巴的经济意味着什么，巴国内方方面面的势力该琢磨一下了；
同时，不要忘记了，这条管道可是冲着人家老穆才签下来的。就算你们该老穆有仇，跟钱也有愁吗？  

估计，有人又要恨的牙根痒痒了。  

    据报道，土耳其库尔德工人党前领导人奥斯曼·奥贾兰日前表示，为了避免受到土耳其军队的攻击，驻扎在伊拉克北部的库尔德游击队正在向伊朗境内转
移。  

    【金鸿评论】不得了，老美又拿着库尔德武装来吓唬伊朗了，怎么着？又想把战火烧到德黑兰呀？前几天库尔德武装对付土耳其闹了个什么结果自己还没
数吗？自找没趣！不过，老美的行动还是得到了来自俄罗斯的回应：  

　  格鲁吉亚政府4日指控俄罗斯3架军机当天早上侵入南奥赛梯的领空3公里，历时一分钟。  

【金鸿评论】土耳其有欧盟护着，伊朗也有俄罗斯罩着呀。这年头，不认个大哥还真不好在外面混！  

二、穆沙拉夫的手腕  

1、对反对派  

据巴基斯坦联合通讯社报道，西北部落地区的武装分子4日释放了此前绑架的200多名安全部队士兵。  

【金鸿评论】这件士兵被绑架的事件本身就非常的蹊跷：士兵被抓本身不能说是被“绑架”而应该说是被“俘虏”；这些士兵在被“绑架”的过程中并未进行激烈的
反击，也没出现大的伤亡，这给人以无限遐想的空间，是不是周瑜打黄盖？  

在这个巴国内矛盾最激化的时候，老穆的对头却放人了，说明什么？第一，老穆肯定让步了，但不是无原则的让步，因为现在是老穆最需要强硬的时候，稍一
不慎就会满盘皆输；第二，对方有诚意和解，缓和矛盾。否则不会出现这种情况。  

老穆通过在这里的让步，向方方面面的国内敌对势力展示了他“温柔”的一面，即愿意通过协商解决问题。在这时出现这个皆大欢喜的事件，也说明了敌对势力
内部阵营正在瓦解。老穆的政治手腕不简单呀。  

在展示出柔的一面的同时，老穆也没有忘记示强，每天被逮捕的反对派人氏在不断的增加就是最明显的表示。  

2、对某些国际势力  

阿富汗当地官员5日称，塔利班武装分子已在阿富汗西部地区攻占了第三座县城。驻阿富汗联军此前曾称，塔利班分子已无力发动大规模的军事攻势。  

【金鸿评论】不能不说的是，老美在阿富汗已经快抗不住了。现在塔利班开始反击了。在这样的背景下，如果老穆稍微动点歪主意，驻阿美军的日子就要多难
过有多难过！  

所以，如果不想看着自己的大兵天天死人的话，最好不要得罪那些不该得罪的人。  

 *******************************************************************************  
再简单评论一下朝核局势的进展：  

首尔消息：朝核问题六方会谈美国代表团团长希尔11月2日在首尔透露，美国专家组已经抵达朝鲜为监督宁边核设施去功能化做准备。他同时表示，朝鲜半岛
和平机制谈判应在朝鲜实现无核化后进行。  

【金鸿评论】就冲希尔这一句话，美国根本没有从根本上解决朝核问题的诚意。让朝鲜先去核是不可能的。  

打个比方说吧：一个拿着枪的大个子（美）总想欺负一个拿着一把小刀的小个子（朝）。现在，大个子说，我们讲和吧，不过你得把小刀先扔了。可能吗？如
果小个子连小刀都没了，还有什么能力保护自己？岂不只能任人宰割？  

美国希望的，只是暂时把朝核问题压下去，先集中精力处理中东和中亚的滥摊子，一旦腾出手来，朝核马上变天！当然了，希尔只所以如此露骨的表示出这层
意思，也是不得已，美国面对的来自福田康夫的压力太大了（此评论接着3日的朝核部分），他是为了向福田表明，美国绝对无意在朝核问题上出卖日本利益
，现在让步妥协只是暂时的。  

面对着美国毫无诚意的举动，老金居然一点动静都没有，乐呵呵的继续“弃核”。其实，老金的算盘打的也很精：现在，一来国家安全有保障，二来经济建设不
耽误，三来美国人愿意烧钱买一时的平安，自己又何乐而不为呢？现在考虑的最多的，是如何借着这个机会多榨出点美元来。毕竟，过了这个村，就没这个店
了。  

日本人还没来的及消受美国人的好意，穆沙拉夫就搞了个紧急状态。眼看着美国人在中东是王小二过年，一年不如一年，日本人能不想给自己留条后路？  

　　日本外相高村正彦11月6日说，日本有可能承担朝鲜核设施去功能化的部分费用，他同时表示，分担这笔费用和向朝鲜提供财政援助是不同的。  

【金鸿评论】日本人露出了回归亚洲的念头，虽然非常的含蓄。我们也不能不承认，福田的确老道。  

眼看着日本人春心荡漾，俄罗斯人赶快给了回应：  

中新网11月6日电 据日本媒体报道，正致力于远东"东西伯利亚地区开发的俄罗斯政府将符拉迪沃斯托克市近郊的港口设施指定为经济特区，打算从外国招商
引资，并将该地区建设发展成俄罗斯的东大门。  

【金鸿评论】俄罗斯人很清楚，小日本不是东西，可是，相比之下，美国佬更不是东西。饭得一口一口的吃，这些家伙也得一个一个的修理，先对付大对头才
是正经。对付的办法很简单，分化离间，各个击破。再说，俄罗斯经济和日本经济是比较互补的，俄罗斯也需要日本的资金和技术，而俄罗斯有日本人眼红的
资源和市场，双方岂不一拍即合？  

眼看着老毛子拉着自己的小情人要私奔，美国人火了：  

据美国《纽约时报》网站４日报道，伊拉克石油部长沙赫里斯塔尼日前接受记者采访时说，曾经与俄罗斯签署开采合同的伊拉克西古尔奈油田将最早于明年初
进行新的招标。   

    中俄美在东亚的利益分配未能让各方满意之前，朝核永远谈不完；中俄欧美在中东的利益分配未能让各方满意之前，伊拉克重建永远是不可能的，爆炸声
也永远不会停止。正因为如此，在半年前伊拉克总统塔拉巴尼访华时拿着一份老的石油合同诱惑北京才没有得到任何满意的回应，俄罗斯也不是傻子，如果美
国人有兴趣这份石油合同送出去，那就悉听尊便，只是，恐怕还没采出石油来，爆炸就跟来了------美国人有十几万大兵在伊拉克，照样无法安心的采油就是
个例子。所以，威胁无效。  

** 【奋进社/金鸿95】老穆，你赢了

进入紧急状态后的巴基斯坦局势跟踪之三

中新网11月7日电巴基斯坦斯瓦特地区一位不愿透露姓名的警官在接受记者采访时称，6日当天共有数百名伊斯兰武装分子发动了袭击，但当地的驻守力量大约
只有24名警察和数名士兵，他们没有进行任何有效地抵抗，伊斯兰武装分子随后攻占了斯瓦特地区的多座小镇，并占领3座警察局和1处军营。伊斯兰武装分子
目前已经在这些被攻占的小镇升起了他们自己的旗帜。攻击事件发生后不久，巴基斯坦军方立即派遣多架武装直升机前来支援，他们对伊斯兰武装分子的工事
进行了打击，但目前还没有接到任何人员伤亡的报告。

巴基斯坦伊斯兰武装发言人斯拉吉汀在接受记者采访时说，“我们没有伤害这些被俘虏的警察和士兵，并将允许他们回到各自的家乡，因为他们没有对我们进
行还击。”

【金鸿评论】在昨天的评论中，我就给出过这样的一个观点：不看别的，就看布什这打一巴掌揉三下的投鼠忌器的劲儿，就知道，一旦老穆真翻了脸，布什是
一点招儿都没有！

果然，伊斯兰武装分子的行为证明了我的判断。

前天，曾有人拿着打内战来吓唬老穆。为了把戏演的真一点，肯定得弄点行动出来。行动是行动了，可结果很有意思，大家看好上面的内容：被俘虏的警察和
士兵都没有受伤害，并且允许他们走人！理由就不重复了，反正在这个世界上，最不值钱的东西有两样，第一是理由，第二还是理由。

在保护伊朗国家安全方面，三条通道非常重要：土耳其（欧盟）、土库曼斯坦（俄罗斯）、巴基斯坦（北京）。在这三条通道中，土耳其和土库曼斯坦立场都
不够坚定，只有巴基斯坦坚定的站在北京一边。所以，在美国打伊朗所必须切断的三条通道当中，巴基斯坦首当其冲。只要摆平了巴基斯坦，土耳其和土库曼
斯坦都好对付。所以说，在伊核问题上，巴基斯坦受到的来自美国的压力绝对不比伊朗小！（关于这个观点的详细分析，在我前面的《辛苦了，老穆》一文中
写的非常详细，有兴趣的朋友可以到我的博客里查看。）

许多朋友都认为谢里夫也不反华，我也赞成这种观点。巴基斯坦最大的敌人是印度。如果没有中国的支持，巴基斯坦根本不是印度的对手。美国一直在努力的
拉拢巴基斯坦以便进一步控制中亚，同时，它也在拉拢印度以对抗中国。如果要问美国人在印度和巴基斯坦哪个更重要的话，那么，美国人肯定说印度更重要
。所以，为了自保，无论谁在台上，都会努力的寻求来自中国的支持，而不可能去反华。

现在美国天天喊打伊朗，但是在三条通道均未切断的情况下，美国不会冒然行事的，否则，伊朗必然变成第二个越南。

但是，如果一个亲华也亲美的人当上了巴基斯坦的总统，那时的巴基斯坦通道也就不象现在这么稳固了。一旦巴铁通道变得摇摆，那么土耳其和土库曼通道将
变得更不稳固。伊朗的国家安全面临的威胁将比现在大的多！当伊朗感觉到它的国家安全面临巨大的威胁而又没有可靠的外来援助保障它的时候，伊朗还会象
现在这样在伊核问题上如此强硬的对抗美国吗？每个国家都是自私的，都会优先考虑自己的国家利益。如果伊朗让步了，那么，北京的中东战略将大打折扣。
因为无论是为了下一步在伊拉克重建中争得更大的蛋糕还是跳出巴以和谈，都离不起伊朗这块跳板。所以，美国威胁巴基斯坦，就是直接威胁中国的核心利益
。

面对着来自美国的挑衅，北京又怎会容忍？何况胡总一向在该强硬的时候从来就不含糊！既然美国挑战中国的核心利益，那么，来而不往非礼也！

虽然这次行动本身对巴基斯坦国内局势造成影响不大，但是，一旦引发了多米诺骨牌效应，还是不可小视的。既然对手都沉不住气出手了，那给他点教训也是
应该的：

全国人大常委会副委员长成思危7日表示，中国应调整外汇储备结构，应当以强势货币的升值，来弥补弱势货币的贬值。他指出：“由于欧罗兑人民币是升值的
，美元兑人民币是贬值的，这两者结合起来，就可以有效弥补。”成思危的言论，牵动了国际汇市的敏感神经，市场解读成思危暗示中国将调整新增的外汇储
备结构，包括增加欧罗等强势货币资产，减少美元等弱势货币资产，令美元崩围。欧罗首次突破一点四七美元，美元兑日圆更重挫两日圆。

【金鸿评论】美国征服世界的三大工具：美元、民主、美军。其中，美元是核心，民主是用来“骗”的，美军是用来“抢”的。

成思危副委员长只不过轻轻一句话，美元即遭猛击。华盛顿又怎会不知道这其中的厉害？如果再这么对着干下去，美元提前崩盘真不是不可能的。谁还敢说中
国人说话没份量？

眼看着中国人出嘴这么重，布什终于扛不住了：

国际在线报道(记者许钦铎)：美国副国务卿内格罗蓬特7日表示，巴基斯坦总统穆沙拉夫是美国反恐战争中不可或缺的盟友，与巴基斯坦及其人民保持伙伴关
系是美国唯一的选择。

新华网华盛顿１１月７日电（记者李学军赵毅）美国总统布什７日表示，他当天与巴基斯坦总统穆沙拉夫通了电话，敦促巴议会选举如期举行，并要求穆沙拉
夫辞去兼任的陆军参谋长职务。

【金鸿评论】祝贺穆沙拉夫将军，布什已经服输了，你当总统不会再有人使绊子了。同时，非常佩服布什先生，很会给自己留面子，把所有的软话都交给了自
己的副国务卿先说，剩下的撑面子的话却留给自己。谁说只有中国人爱面子？

    从表面上看，布什并没有说任何让我们听起来感觉顺耳的话，我为什么说布什服软了呢？还是打个比方吧：假如你去服装店买衣服，你相中了一件衣服，
店老板要300元，你只给200元，双方互不让步。店老板知道，200也不赔，就是赚的太少，可巧的是，一天都没开张了，让你走了又感觉亏的慌，可是，卖200
元也不怎么甘心。这时，你说，如果200不卖自己就不要了，店老板非常无奈，只好很不高兴的话：“交钱，马上交钱！”现在，布什大人就是这个老板。     

在自己的位置得到了来自世界上权利最大的总统的承认之后，老穆也很干脆：

中新网11月8日电据巴基斯坦当地媒体报道，巴基斯坦总统穆沙拉夫7日称，巴将于11月15日之前作出国民议会任期和大选日期的决定。

【金鸿评论】OK，天晴了，大家出来晒衣服吧！

** 【奋进社/金鸿95】精明的布托

[2007-11-10 20:26:42]

进入紧急状态后的巴基斯坦局势跟踪之四

巴基斯坦前总理贝·布托即将与总统穆沙拉夫摊牌，她7日呼吁民众展开大规模抗议活动，抗议军事统治者穆沙拉夫宣布国家进入紧急状态。与此同时，美国总
统布什敦促穆沙拉夫尽快放弃军职举行选举，但美国也表示，穆沙拉夫是美国不可或缺的盟友，暗示不会对巴基斯坦进行制裁。

法新社报道，布托无视警方扬言镇压，矢言9日将在拉瓦尔品第市举行集会，并呼吁如果穆沙拉夫不妥协，民众13日就从拉合尔“长征”至首都。

两度担任总理的布托7日在伊斯兰马巴德会见其它反对党领袖，会后她召开记者会说，美国的主要盟友穆沙拉夫必须在15日前恢复宪法、宣布大选如期于1月举
行，并且辞去陆军参谋长的职务。“我呼吁巴基斯坦民众挺身而出。我们处于劣势。”

巴基斯坦过去三天持续传出反穆沙拉夫抗议活动，遭到安全部队镇压，原先布托未表态支持抗议活动，外传她希望谋取权力分享协议。现年五十四岁的布托说
：“奉阿拉的旨意，将有大批民众挺身而出。如果我遭到逮捕，民众应该继续奋斗。”

数百名布托的支持者聚集在伊斯兰马巴德的国会大厦外，布托讲完话后数分钟，警方开始使用催泪瓦斯，并持棍棒对付群众。最少三人遭逮捕。首都稍早有将
近一千名反对派人士举行和平集会，西北部白夏瓦市也有两百人示威抗议。

总理阿齐兹7日与执政党巴基斯坦回教联盟的国会议员开会，宣布14日将决定大选日期；穆沙拉夫也出席了这场会议。穆沙拉夫则告诉议员，他希望“尽可能不
要偏离选举时程”。

【金鸿评论】布托真的要号召民众“造反”吗？

在黎明之前，有几十分钟的时间天会格外的黑，这就是所谓的“黎明前的黑暗”。

大家千万不要被布托的障眼法迷了眼。布托的这个举动，无非是为自己明年赢得大选挣点分而已，可怜的是，穆沙拉夫同志这次成了映衬布托光辉形象的反面
人物。布托的喊话，显示出了他精巧的政治功夫。布托的行为，充分证明了她在35岁时就能登上了权力的巅峰，确实有其合理性存在。

在展示分析之前，我想先提两个问题：

为什么布托在穆沙拉夫达到了宣布进行紧急状态的目的（逼布什承认不再拿总统连任合法性做文章）、并承诺明年大选后才跳出来极力反对穆沙拉夫搞紧急状
态？

在宣布国家进行紧急状态的第一时间里，穆沙拉夫就毫无顾忌、杀鸡儆猴的抓了布托手下的高官，可是，为什么布托现在如此强烈的反对穆沙拉夫却没有被投
入监狱、甚至穆沙拉夫连“软禁”这个词都不愿意用？

我们先看一下巴国进放紧急状态之初，布托做了什么：

穆沙拉夫宣布国家进入紧急状态后，布托马上回国，并在媒体面前公开表示，她同意穆沙拉夫的“诊断”（国家正面临极端主义日益增长的威胁）。虽然他也表
示，在“治疗方法”上与穆沙拉夫有分歧；至于“呼吁巴总统穆沙拉夫取消紧急状态并恢复宪法”并不是她所要表达的关键意图（这是句废话）。

就此，我在7日的《紧急状态后的巴基斯坦》一文中给出的观点是：“老穆抓布托的手下，无非是杀鸡给猴儿看：要么跟我走，要么在国外呆着；如果回国跟我
对着干，监狱里有地方盛你，抓人的理由是现成的，腐败。而布托在第一时间飞了回来，其行动本身就说明，她上了老穆的船，并且人家也说了，同意穆沙拉
夫的“诊断”。

至于她的“呼吁取消紧急状态并恢复宪法、但在“治疗方法”上与穆沙拉夫有分歧”，是为了告诉方方面面，搞紧急状态是老穆自己的主意，自己不是同谋，跟自
己没关系。”

另外，我个人的感觉是，布托的“同意穆沙拉夫的诊断”一语包含着对穆沙拉夫的充分谅解的意思，毕竟，目标是否一致才是最重要的，手段（方法）上的分岐
不决定本质。

虽然穆沙拉夫逮捕了布托所在政党的高官，却没有发生布托所在的人民党及其支持者的大规模示威活动。很显然，布托在背后做了很大的工作。要知道，布托
所属的人民党，是巴基斯坦最大的反对党，如果他们一起出来闹事，局面失控也有可能。

这足以说明，布托在后台支持了穆沙拉夫一把。之后，在紧急状态下，巴基斯坦国内并没有发生大规模的骚乱，再加上北京帮忙收拾了外部（国际上）的不和
谐因素，穆沙拉夫成功的达到了目的。

再看一下布托现在呼吁民众“造反”的背景：是在布什不再就穆沙拉夫总统连任的合法性问题纠缠不休时做出的。

现在，穆沙拉夫的目的达到了，也该轮到布托捞一把政治利益了。

在紧急状态之初，布托协助老穆稳定了国内局势，得到了来自执政方的肯定。现在，布托呼吁民众造反，更是为了获得在野党的民众支持者的支持（因为她敢
于顶住压力追求“民主”），也为明年的大选拉一下选票，为明年的执政铺平道路。

政治这玩艺，说复杂，也麻烦；说简单，也容易。不就是分利益吗？

接一来的一幕我们也看到了：布托半推半就的被“软禁”以后，布托的支持者并没有做出太过激的行为，之后巴警方也很快解除了对布托的活动限制。很显然，
这是一场双簧。

布托与老穆合作的这一把真的很漂亮，这也正应了中国那句老话：男女搭配，干活不累。

二位，合作愉快！

****************************************************

在巴基斯坦局势发生了有利的转变之后，在台海和缅甸方面也出现了不错的信号：一个是台湾承诺坚决不造核武器（这要感谢内贾德那三千台离心机），二是
昂山素季愿意与缅甸政府合作了。看来美国面临的压力太大了，反正，打死我我都不相信布什先生皈依了佛教！

接下来，内贾德老兄该及时的向世界人民汇报一下浓缩铀的最新产量，给美国加加码，逼它在经济制裁方面松松口、让让步。毕竟，只有波斯的同胞们也得过
上好日子才算的上地区和谐！


** 【奋进社/金鸿95】最重要的管理素质

对于管理者而言，究竟什么素质最重要呢？

在回答这个问题之前，先来看几个例子很有意思的例子。在中国历史上，平民出身而登上帝位的封建皇帝中，最有名的是汉刘邦、明朱元璋、宋赵匡胤，刘裕
也可以算是一个。在这四位中，没有一个正儿八经上过学的，而且大都是痞子出身，贪财者有之，好色者有之，爱赌者亦有之。其实，就连我们的毛主席算上
，他也不过是个师范的中专生。

中国的企业家当中，声名最显赫的是张瑞敏，而他只是个高中生。当然，就这个高中生，却是第一个到瑞士洛桑商学院讲过课的中国企业家。象李嘉诚、霍英
东等巨富，文化也都低的可怜。不要认为这是中国特色。世界超级富豪盖茨大学没上完就辍学了，而他的微软里可是聚集了全世界最有智慧的工程师。还有盖
茨的老搭档艾伦，甲骨文公司的埃里森，戴尔，他们都是大学的辍学生。而为这些大学上完的学生们打工的人，却个个都有高学历。这些现象，难道不值得我
们去深思一下吗？（我并不是说上大学读书没有用，只是感觉，有些关键的管理素质不一定是大学里所能培养出来的。）

这些例子，有政治家、有企业家，而且都是最顶级的管理者，可以说他们是很具有代表性的。

由此我们可以确信一点，管理者最重要的素质不在这些形式上的东西。那究竟是什么呢？我觉的应该是眼光。

按照管理上的决策理论，管理者的工作就是做决策。决策的正确程度决定了管理者水平的高低。而决策的正确程度，关键就取决于管理者的眼光。

眼光，是个比较复杂的概念。它应该包含三方面的内容：长远程度，就是说站在时间的角度上能够看的远，用孔子的话说就是“人无远虑、必有近忧”；开阔程
度，就是对事物之间纵横联系的把握，即“不谋全局者、不足以谋一域”；精细程度，这一点相对简单，就是对一件事的各个细节把握的深入程度。

眼光既然如此重要，那么有没有办法提高呢？当然有，就是多读书。大家都知道，读书可以“开拓视野”。

按照传统的观念，中国人信奉的是：一命、二运、三风水、四积德、五读书。在这五点当中，前四点都是唯心义义的，只有第五点是唯物主义的。唯心主义的
东西不一定不好，但是，唯物主义的东西肯定是好的。多读书对人绝对是有好处的。

当然，站在能力的角度而言，管理者最重要的素质是用人。而要用人得当，就必须学会识人、育人、评人。而这些能力，同样需要眼光来发现、来判断。当年
，毛主席第一次见粟裕，就说这个年轻人将来可以指挥百万大军，那时的粟裕，只是个排长。他的眼光，穿透了时间。

** 【奋进社/金鸿95】寻亲记

    先看一下福田访美之前的盖茨访日的一个镜头：  

       9日，盖茨在与日本防卫大臣石破茂和外相高村正彦会谈时说，美国保证向日本提供“核保护伞”，美日两国目前正在进行合作的导弹防御计划是对“核
保护伞”的补充。盖茨还表示，即使朝鲜半岛实现无核化，美国仍将维持导弹防御网。   

    【金鸿评论】我们最关心的是，美日合作的导弹防御网是防的什么导弹？是朝鲜能打到东京的大浦洞导弹吗？美国可是从来就没有这么关心过日本人。美
国真正希望防御的，是能打到美国的东风21导弹。  

    从这里我们也可以看出来，所谓的美日军事同盟，只不过是美国人打着同盟的幌子利用日本人而已。日本人也不是傻子，今天的中国已非昔日可比，这个
肉盾可不是好当的，弄不好就会真的“一亿玉碎”（如果北京打出的飞向美国的核弹被布置在日本的导弹防御系统“拦截成功”，核弹在日本上空爆炸，我们将有
幸目睹这一壮观景象）。  

    为了让大和民族能还拥有一个明天，为了能先活下去（不管灿烂不灿烂），在这个事关日本国运的问题上，福田没敢给美国留下丝毫的幻想，马上做了回
应：  

    日本《读卖新闻》11日报道，因现任首相福田康夫重视与中国的关系，因此今年版的日本外交蓝皮书中，将不会列入麻生的此一外交构想。  

    【金鸿评论】从这一点，我们也可以看出，日本人没有胆量再回到对美一边倒的小犬时代了。  

     当然，为了给接下来的福田访美能捞一把好处，福田也是一点儿的时间都没耽误，同时打出了四路拳风，下面我们一路路的看一下：  

     日本参院全体会议14日上午以自民、民主、公明等各党的多数赞成，批准把对朝鲜的经济制裁延长半年。该经济制裁包括全面禁止朝鲜船只进港及朝鲜
商品进口。  

        【金鸿评论】日本在这个时候拿经济制裁说事，自然是在给六方会谈搅局。因为六方会谈的任何实质性发展，都意味着日本受伤深一层。日本不敢在
朝核问题上对美国翻脸，只好变着法子刺激朝鲜。面对着日本的刺激，朝鲜非常配合的跳了起来：  

    朝鲜主流媒体《劳动新闻》和《民主朝鲜》14日分别发表评论，指责美国和日本最近举行的联合军事演习破坏了当前的对话气氛，是“非同寻常的军事动
向”。  

    【金鸿评论】朝鲜用行动证明，他完全有兴趣陪不甘寂寞的日本人玩一把，反正闹到最后，出面买单的肯定是美国人，吃了亏的美国人再反过来再去敲日
本人的竹杠。这一点已经在以前的较量中证明过多次了。  

    当然，现在的情况稍有不同：在过去的一年中，美日关系恶化严重，现在福田即将访美“修复”美日同盟，被动无比的美国人也急需得到日本的支持，在这
样的背景下，真不是修理日本人的时候。福田也瞅准了这个空档，用小动作暗示美国，不能再在朝核问题上损害日本的利益了。  

    这是福田打出的第一路拳风。  

      据香港明报报道，中国民间反日运动领袖童增透露，向以反华态度强硬见称的日本右翼政客、东京都知事石原慎太郎有意访华，并透过中间人提出欲与
童增在北京会面，缓和中日民间关系，童增为此致信石原开列条件，要求石原以书面形式为日本当年侵华向中国人民谢罪。石原昨日已收到信函，将于日内回
覆。   

　　  

      【金鸿评论】石原慎太郎是个什么东西？朋友们应该都知道，这个是个死硬的反华派。现在，反华的石原慎太郎居然要访华了。很显然，这决不仅仅是
他石原慎太郎一个人的事，他代表的可是整个日本右翼。在这个福田访美的口子上，日本右翼却来对北京示好，我们不能不怀疑：无事献殷勤，非奸即盗（这
是第二路）。如果有谁不相信我说的话，可以看看下面的消息：  

    福田14日下午在官邸会见了将于22日起访华的自民党政策调查会长谷垣祯一，让他将亲笔信转交给中国领导人，表示“希望尽早访问”中国。  

    【金鸿评论】在日本人放出风来要全力修复日美同盟关系时，福田却又转过脸来对北京示好。这个动作对布什来说，可不是好消息。布什可是指望着用日
本封堵中国的。  

    当然，福田对北京示好是有条件的，他是希望尽早解决东海油气田开发问题，他还要求中国做出“政治决断”。  

    这个“政治决断”是什么东东？不外乎是在告诉北京，如果你在东海给我石油，我就考虑象韩国一样也跟华盛顿拉开距离。毕竟大家在江湖上混，为的就是
个“利”字。但是，如果北京不同意在东海让步呢？  

    这么一看，福田的示好可谓是包藏祸心。这哪是示好？分明是威逼利诱！  

    福田对北京同时打出了一软一硬两套拳风，一方面是想尽可能的从北京这边套取政治红利；另一方面，也是用北京反逼华盛顿-----北京为了拉我可是花
了本钱的，如果布什还希望日本能给美国人卖力的话，那也得正儿八经的“意思意思”才行。  

    当然，为了让自己伸手要好处的行动显的更加隐晦一点，福田也没忘记向布什示好：  

    日本检察官16日称，他们已撤消了4名驻日美军海军陆战队队员涉嫌轮奸日本一名19岁少日本警方必须征得美军同意后才能扣押、调查嫌疑人。  

    【金鸿评论】看了这个消息，恐怕那些一直在打日本娘们主意的兄弟们又该流口水了。盼望着中国早日强大起来，将来有一天，我们把美国兵从日本赶走
，我们也去驻军。那时，报名去日本驻军的人一定多的挤破了头！  

    （比起安倍来，福田要圆滑的多，他知道，自己是胳膊扳不过大腿，要好处的时候也是陪着笑脸。这样最大的好处是，即使要不到好处，也不会挨揍。这
是第四路拳风）  

    综合上面福田打出的四路拳风来看（对北京一手软一手硬、对华盛顿一手软一手硬），是标准的两面下注的手法，我们也可以看出来，福田的确是老奸巨
滑。不过，他的招数也不怎么样高明，从本质上来说，他的招数和下台的安倍过去一年里用的是一样的。其实，日本人选择亲华还是亲美是他自己的事，做出
来选择后就要承担相应的后果、得到应得的利益，这不是可以要挟别人的本钱。这个道理，耍小聪明的日本人，永远不会懂。  

    福田在访美之前做了这么多的“准备工作”，他访美又会得到什么呢？  

    据报道，布什在当地时间16日上午在白宫欢迎福田。两位领导人在会后会晤媒体时都一致表示，两人就相关议题进行了实质性的讨论。布什对福田上任后
首次外访就前来华府表示感谢，认为这是福田重视美日坚定盟谊的表现。福田则强调，他首次出访就来到这个日本的“唯一盟友”美国。  

    布什告诉福田，在处理北韩议题的过程中，美国不会忘记被绑架的日本公民，也不会忘记他们的家人。  

    福田则向布什表示，阿富汗绝不能再成为恐怖主义的温床。他将竭尽所能，促成新反恐法在国会早日通过，以便恢复为盟军在印度洋提供海上加油的服务
。  

    福田也重申，日本将继续与美国合作，达成朝鲜半岛完全非核化的目标。  

    【金鸿评论】忙活了十来天的福田最后什么都没得到。看来，福田在国内的支持率又得跌了。  

    在朝鲜绑架日本人的问题上，福田是希望在其访美期间能得到布什支持的。可惜的是，他彻底失败了。当然，布什还算有良心，还没有忘记这些日本公民
，并且记得他们的家人。但是，记得又有什么用？  

    堂堂大和民族，被小小的朝鲜欺负了，居然连个替自己说话的人都找不到，还玩什么“强势外交”，还承担什么更多的“全球责任”！建议福田还是老老实实
呆着的好，免得受辱更多。  

    当然，眼看着自己的主子一点好处都不给自己，日本人也开始发牢骚了：  

    就日美首脑会谈上福田康夫向布什表示尽力促使新反恐对策特措法早日成立一事，日本共产党委员长志位和夫17日发表谈话批评称，“表明了根深蒂固的
追随美国的态度”。  

 ***************************************************************  

    下面再简单看一下巴基斯坦局势的发展:  

    美国助理国务卿内格罗蓬特在与总统穆沙拉夫会晤后决定延长在巴基斯坦的停留时间。 作为巴基斯坦实施紧急状态以来来访的最高级别的美国官员，内
格罗蓬特给穆沙拉夫带去了一个明确的信息：取消紧急状态，交出军权，确保巴基斯坦明年举行公正、自由的选举。  

　　但是，BBC报道称，内格罗蓬特可能并没有收到来自穆沙拉夫的多少回应。早些时候，穆沙拉夫曾经告诉BBC，在实行紧急状态期间巴基斯坦仍然有可能举
行"可信"的大选。穆沙拉夫一直坚持说，只有巴基斯坦的安全局势得到改善，才会取消国内的紧急状态。   

　　在与内格罗蓬特会晤之前穆沙拉夫还说，只要军队掌权，巴基斯坦就能确保安全。穆沙拉夫同时还警告，如果明年1月举行大选时局势不安定的话，巴基
斯坦的核武器有可能落入坏人手中。   

　　内格罗蓬特是在星期五(11月16日)抵达巴基斯坦的。在巴基斯坦期间他还曾经会晤了目前巴基斯坦军队的副统帅以及反对派领导人贝·布托夫人。据报道
，他与布托通电话时，告诉她"温和力量"应该共同合作，让巴基斯坦重新实现民主。   

    【金鸿评论】在布什与穆沙拉夫的“坦率交流”仍然没能让穆沙拉夫解除紧急状态之后，只好让国助理国务卿内格罗蓬特直飞伊斯兰堡。至于此行的目的，
也不过是希望完成布什没有“交流”到的东西。  

为了让内格罗蓬特的到来显得更有分量一点，巴基斯坦这几天出的事还真不少：  

　　1、巴基斯坦境内的武装冲突和爆炸案多了，而且强度增大了：17日，巴基斯坦西北部落地区发生教派冲突，截至17日已经造成45人死亡；18日，巴基斯
坦一列由卡拉奇开往白沙瓦的火车18日在行驶途中遭埋设在铁轨附近的炸弹袭击，造成一人死亡、两人受伤。  

    在穆沙拉夫宣布国家进入紧急状态之初，巴国内一反紧急状态前爆炸声不断的情况，变的非常安静。至内格罗蓬特访巴前，动静又大了。  

    2、《纽约时报》也在报道中宣称，穆沙拉夫钦点的军方接班人基亚尼是“亲美温和派”，并称基亚尼也是“西方看好的穆沙拉夫接班人”。在这个穆沙拉夫
最需要军方支持的档口，《纽约时报》的报道来的绝对是时候。只是，用这样的离间计算计人，是不是损了点？穆沙拉夫毫无疑问是亲华的，而他钦点的接班
人却是亲美的，这还得了？一旦几天后辞了军职，巴军方还不马上换旗？美国人是不是希望穆沙拉夫现在拿掉基亚尼、进而在支持他的军官中产生反叛情绪，
让穆沙拉夫成为孤家寡人？  

    3、16日，巴基斯坦的两名前总理决定结盟，结合人民党和伊斯兰教联盟的力量，同穆沙拉夫对抗。布托一改紧急状态之初对穆沙拉夫“诊断”的认同，跳
到了穆沙拉夫的对立面。  

    一时间，无论是巴国内的方方面面都出现了矛盾激化和有可能激化的场面。这些无疑为内格罗蓬特增加了不少可以发挥作用的地方。  

    有北京的强力支撑，伊朗都敢把“原子弹头设计蓝图”拿出来炫耀一番，还不用说作为“全天候合作伙伴”的穆沙拉夫了。虽然美国的算盘打的很响，不过结
果还是非常失望。穆沙拉夫一点面子都没给这个美国国务院二号人物，直接拒绝了他代表美国政府提出的解除紧急状态的要求。  

    为了达到目的，内格罗蓬特向穆沙拉夫“清楚地表明”，紧急状态不结束，援助金额将减少，后果非常严重。穆沙拉夫则警告，如果明年1月举行大选时局
势不安定的话，巴基斯坦的核武器有可能落入坏人手中。   

    如果援助是可以威胁穆沙拉夫的砝码的话，还用得着内格罗蓬特先生亲自来伊斯兰堡跑一趟了？穆沙拉夫宣布国家进入紧急状态的第一时间，美国就是拿
着撤销援助来做威胁的，结果又如何呢？  

    至于穆沙拉夫的威胁，可就严重的多了。如果巴基斯坦国内真的出现动荡的话，在伊朗发现“丢失的巴基斯坦核武器”绝对是件很正常的事情。那时的美国
，又能如何？如果核武器落入基地这类真正的恐怖组织手中，再被运到美国的某个大城市引爆，那时的美国，又能如何？  

    无奈之下的，内格罗蓬特只好“不走了”。你不解除紧急状态，老子就不走了！向来强硬的无以复加的美国人，今天居然耍起赖来。不能不承认，这样的国
际笑话，不是天天能看得到的。  


** 【奋进社/金鸿95】同床异梦的盟友

[2007-12-06 19:25:21]

一、巴基斯坦大选

据巴基斯坦媒体报道，穆沙拉夫11月30日在接受美国广播公司独家采访时称，如果明年1月8日的选举导致巴局势形成一个令他无法接受的局面，他可能会考虑
辞去总统职务。

【金鸿评论】大丈夫能屈能伸，这句话用在穆沙拉夫身上是再合适不过了。

穆沙拉夫真想辞职吗？那他拼着命的把国家搞成“紧急状态”干什么？包括美英和国内的反对派在内，他得罪了多少人？这又是何苦？

很显然，这是穆沙拉夫同志近期的又一次“耍赖”。上次是宣称：“只有在总统合法性问题被法院审完后再决定是否辞去军职”。上次没有“赖”成功，所以被迫宣
布国内进入紧急状态，用武力达到了自己的目的。时至今日，新麻烦又来了。

谢里夫要带领着一大帮的反对派抵制大选，布托也来混水摸鱼、自抬身价，让老穆同志非常不爽。得，再赖他一回。

反正人家老穆说了，西方必须承担巴基斯坦目前政治危机的责任。 “如果存在一个失败的话，那么这也不是巴基斯坦的失败。”-----不是巴基斯坦的失败，又
是谁的失败呢？

不妨把话挑明好了。如果老穆逼着真下了台，那时，巴斯斯坦的核武库一定会丢上了三件两件的核武器，至于是“长了腿”跑到了伊朗还是跑到了反美的伊斯兰
激进势力手里，那就看老穆的心情有多坏了。

至于接下来局势的发展，可以认定，谢里夫会破罐子破摔，继续寻机闹事，因为作为穆沙拉夫死对头的他是不可能当选新总理的；而布托则会做做样子，总理
之位应该还是她的。当然，他对穆沙拉夫的“反对”也仅仅限于形式上，否则，下场只有一个，因贪获罪。

二、中日关系

外交部发言人秦刚４日在例行记者会上确认，中国国家主席胡锦涛将于明年应邀访问日本。 

【金鸿评论】为了能促成我们胡总访日，日本人可是煞费苦心。

从福田访美前放风“石原慎太郎有意访华”开始，日本人就开始做工作。当然，石原的表现也有日本欲从自己在中美之间选边站的“重定位”中捞好处的意思，可
惜的是，北京与华盛顿一个是不见兔子不撒鹰，一个是不见鬼子不挂弦。最后，福田访美是两手空空而归，既没从华盛顿手里套得“美国全球合作伙伴”的好处
，也没有从北京捞到“东海谈判”的好处。

眼看着美国式微，北京越来越惹不起，小日本加大了对北京“友好”的投入。于是就有了下面的新闻：

30日，日本防务省称，在驻日美军强烈要求下，被迫取消了中国军方代表团参观日本宙斯盾驱逐舰 “雾岛”号的行程安排。

【金鸿评论】这个消息后来又被日本人自己否定了，说什么不是美军的要求，而是中日之间的关系还没“铁”到那一步，所以不能让参观这个宙斯盾。

看成看不成一个宙斯盾并不是什么大事，关键是小日本的姿态。背着美国人让中国人参观这个宝贝宙斯盾，那可是对日美军事同盟的直接出卖。

这一行动所要表达的意思就很容易理解了：日本人愿意离美国人远一点，离中国人近一点。（日本最大在野党民主党的小泽一郎不就主张“日本应和美国和中
国建立对等和等距的等边三角形关系”吗？）

眼看着日本人和自己离心离德，下一步美国人会采取什么要的行动来修得日美关系呢？这可不是一个简单事。

应该说，日本人对改善中日关系是有一定诚意的。但是，这些还不足以促成我们胡总访日。大家都知道，咱们胡总是个大忙人，日本人的这点意思还不够份量
。

紧接着，胡总在会会见日本外长高村时，要求日本反台独，高村一口应允。如果日本真的答应了反台独，就意味着台海发生了战事，日本不会加入。如果日本
不加入，那美国肯定不会自己为了台湾和中国发生冲突。接下来暗中操纵台独闹事时，美国人就该掂量着来了。

小鹰号靠港被北京拒绝的消息这几天炒的特别热。现在，真相也出来了：这个不知死活的东西敢走台湾海峡（有给台独壮胆的暗示在里面），不扇他耳光扇谁
？再结合北京搞的跨军区军演来看，北京已经做好了动武的准备。

日本逃出战场，从理性的角度讲是好的；但是站在感情的角度讲，大家都希望借着战争狠狠的教训这些杂种一顿，一血前耻，一清旧恨！

三、美以关系

美国于3日发布的情报报告指出，伊朗曾在2003年中止了一项核武器研发计划，但继续进行浓缩铀提炼工作。《美国国家情报评估报告》指出，他们有“高度的
信心”认为，伊朗在国际压力下曾在2003年中止了它的核武器计划。

【金鸿评论】北京说“伊朗进进铀浓缩活动是出于和平目的”；那是睁着眼说瞎话；美国说伊朗“中止了核武器研发计划”，那是闭着眼说胡话。连内贾德都已经
说自己是“核国家”了，美国人倒替伊朗遮掩起来，难道说“核国家”不是“拥有核武器的国家”而是“种核桃树的国家”？

美国人此举又是为何呢？对伊朗示好？美国能放弃独霸中东的计划吗？如果真是这样，那他应该跟中俄欧谈谈伊拉克重建而不是自己在这里玩文字游戏。

其实，美国这一手是冲着谁来的，谁就会跳的最高，看看下面这条新闻，还真有人不给美国的情报部门面子：

以色列国防部长埃胡德·巴拉克4日说，即便伊朗2003年时可能中止研制核武器，它也可能在随后的几年里重启这一计划。

【金鸿评论】可以看出来，美国人炮制出这篇报告纯粹是在警告以色列人。在中东，军力超强的以色列只有一个真正的敌人，就是伊朗。如果没有美国人在背
后为以色列撑腰，一旦以色列与伊朗动起手来，以色列被打残甚至“消失”都很正常。反正大家都对一个现象非常的好奇：以色列宣称自己有原子弹，可是谁也
没见过；伊朗也宣称自己是核国家，有没有原子弹谁也说不准。两家子一打起来就知道真假了-----是骡子是马，牵出来骝骝！

应该说，美国人能玩出这一手也真不容易。至少，布什的那张本不漂亮的脸又被本国的情报部门抽了几下子----你不是天天都在说伊朗在打着和平利用核能的
名义造原子弹吗？自己人都给你拆台了。这下子内贾德老兄可高兴了，马上自豪的宣布：美国情报部门日前有关伊朗早已停止核武器项目的报告实际上是宣告
了伊朗核计划的“胜利”。不管这次对以色列进行警告的结果是如何的成功，在这一回合的伊核较量中，布什的脸这回是丢大了！

这也足以证明，以色列与美国之间的矛盾确实够大了。

为了“换得”（也包括“逼得”）欧盟、阿盟与自己在伊核问题上的合作，美国人巴望着以色列能在安纳波利斯会议对巴勒斯坦、阿拉伯世界做出让他们满意的让
步，无奈以色列为了保证自己的长远利益不受损害，坚决不让步，奥尔默特甚至明确表示“巴以和谈不会受具体时间表的制约”。这下子可麻烦了，好不容易把
欧盟、阿盟连哄带骗搞得跟自己一条战线来对付伊朗（前提是以色列放血），让精明的犹太人一句话全赶跑了。

这倒好，精明的内贾德一把就抓住这个千载难逢的好机会，顺手抛出了两个绣球：

内贾德在第28届波斯湾合作委员会首脑会议上大声宣布，这次海合会为“加强和发展地区国家间的兄弟友爱关系创造条件”。其实，这哪是海合会创造的机会，
明明是犹太人送给内贾德的机会！让在中东被日渐孤立的伊朗有了成为“与地区国家、邻国团结合作标志”的国家的机会。

在美国动用各种手段加大了最伊朗的经济封锁之后，已经让伊朗的经济出现了不小的麻烦。在过去的几个月里，伊朗只要一有机会就让自己的头面人物主动出
来宣传“美国不会对伊朗动武”的论调就足以证明这一点：伊朗这么做是为了尽可能的稳定投资者的信心，从而保证国内经济的正常运行。

眼看着美国人在中东是越混越没人样，有心人早就起了另寻靠山的心。眼看着内贾德跟自己称兄道弟，沙特阿拉伯就很给面子。于是，很快就传出了“决定投
资5亿欧元在伊朗西北部哈雷斯市建设燃气轮机发电厂”的新闻。

这还不算，内贾德也抓住机会与欧洲人进行了一番“沟通”：一面告诉欧洲人“巴勒斯坦人的真正代表没有参加会谈。他们的利益被忽视。”一面让自己的外交部
发言人阿里·侯赛尼对外表态，希望欧盟方面继续支持伊朗与国际原子能机构(IAEA)的合作进程。

这两下子也砸得布什浑身难受：美国人满心的指望以色列让步来换得阿盟对其巴以和谈方案的支持，进而通过在巴以和谈问题上与欧盟妥协来获得欧盟对经济
制裁伊朗的支持，现在让内贾德一句又给搅了。美国人主持招开的安纳波利斯会议上根本就没有把代表阿拉伯利益的人请去！这下子欧盟还会买美国人的帐吗
？如此一来，捞不到好处的欧洲人只能继续充当伊朗六方会谈的协调人角色了（亲近中俄）。于是乎，我们又看到了默克尔在《德国之音》广播电台上声称希
望与中国维持“良好的伙伴关系”的一幕。

这么一来，美国人打算通过拉拢阿盟、欧盟来对伊朗进行经济封锁进而控制伊朗的计划硬生生的被以色列给搅了！原因就是以色列人不愿意放血。布什能不上
火？

没办法，再不警告一下也不行了，至于脸面，在这个紧要的关头就顾不上了。这才有了上面美国情报部门狂抽布什耳光的一幕。

　　其实，对美国人离心离德的又何止以色列人呢？英国人也是也在号称“由于经费不足皇家海军已无力应对一场重大战争”了吗？（就在英国人批露这一事实
之前，内贾德刚刚宣布“伊朗已经是个核国家”，英国人不愿意卷入对伊战争之心已是再明白不过的了。）

四、委内瑞拉修宪

委内瑞拉总统查韦斯3日发表全国电视讲话，承认他的修宪公投计划失败。委内瑞拉国家选举委员会此前表示，查韦斯提出的修宪公投没有获得通过，最终以
49.29%比50.70%的微弱差距宣告失败。

【金鸿评论】“唯大英雄能本色，是真才子自风流”。

何谓本色？不掩其长，不盖其短。查韦斯坦然面对修宪的失败，不为自己的失败做丝毫的文饰，足以对得起“本色”二字。

查韦斯，英雄也。


** 【奋进社/金鸿95】俄日双簧

    下面一段新闻东方已经评过了，我只是感觉这段新闻非常有意思，越想越感觉有趣，索兴把它写出来，不怕炒东方的冷饭。先看一下这则新闻内容：

    据日本政府12月13日透露，俄罗斯在两国争议海域扣留了4艘日本渔船。日本方面对此表示愤慨，并要求莫斯科做出解释。

    据美国媒体报道，日本外务省官员透露，俄罗斯海岸警卫队13日凌晨在北方四岛（俄称南千岛群岛）之一的国后岛附近扣留了日本渔船。

    日本公共广播公司NHK报道说，4艘渔船和11名船员都被俄罗斯当局带到了北方四岛之一的色丹岛，船员没有受伤。

    日本外务省负责俄罗斯事务的官员称，日本“无法接受”俄罗斯扣留日本渔船，因为日本享有对争议岛屿的主权。日本官员要求俄罗斯方面做出解释。俄罗
斯驻日使馆尚未做出回应。

    此前，根据日俄达成的捕鱼事务协议，只有登记注册船只才能在两国争议海域作业。日本渔业署的消息称，参加本季度捕鱼的所有28艘登记在册日本船只
都已经在13日返港。这意味着13日被扣留的日本船只可能不是协议授权的登记渔船。

    【金鸿评论】再强调一次，福田康夫的确滑的可以，滑的可爱。

    日本人明明知道自己被俄罗斯人扣下的渔船“不是协议授权的登记渔船”，理亏在己，却偏偏拉开架式就俄罗斯给个“解释”。难道日本人的胳膊比俄罗斯人
的大腿还粗？这不是存心找事吗？这可真是怪事。

    当然了，怪事自有怪事的道理。

    先看看日本冲着俄罗斯来这一手的大背景：美国为了逼北京在伊朗让步、支持它制裁伊朗，利用台独分子疯狂的对北京施加压力，并一再的用美台之间的
双簧向北京暗示，如果不让步则台湾将宣布独立。北京则针锋相对相对，用一个20亿美元的石油合同清楚不过的表明了自己的立场。其次，这20亿美元算不了
什么，只是个姿态而已。两年来，北京砸在伊朗的美元加起来远超过1000亿美元（有消息说是2000亿），另外，仅仅砸在巴基斯坦与伊朗边境的瓜达尔港就有
500亿美元之多。在伊朗有中国的战略利益这一点所有列强心里都有数。

    为了应对台湾可能出现的独立，北京双管齐下：一方面通过外交途径要求各个国家反对台独（支持北京的国家据说已有180个以上），一方面加强军事准
备，积极备战。面对着北京的强势，华盛顿无比被动。华盛顿是不可能为了台湾和北京打一仗的，因为华盛顿需要和北京交换利益的地方太多了，比如伊核、
朝核，比如伊拉克重建、阿富汗乱局、巴以和谈。这些问题对美国而言，哪个的重要性都不比台湾差。何况北京还是华盛顿最大的债主。它只能寄希望于日本
加入战场，用日本消耗北京体力，从而在中东找到喘息的机会。

    当然了，一个被北京打傻了日本更有利于美国的控制。日本人的脑袋也不是夜壶做的，他们自己有自己的小九九。其实，从过去三四个月的表现来看，日
本人早已逃出了战场。只不过，新上台的福田康夫表现的更滑头一点罢了。比如，胡总会见日本外相高村时要求日本表态反对入联公投，高村的回答是“中日
发表联合声明以来，日本的立场都是一贯的”。这样的回答等于什么都没说，日本人可以从过去的对华政策中挑出让美国人满意的条款，也可以找出让北京满
意的条款。

    近几日“同一首歌”在南京大屠杀纪念日赴日演出引起了泫然大波，许多人在大骂CCTV 媚日。其实，稍微动脑子想一下就能明白，如果不是上面的意思，
CCTV的台长绝对不敢做这种事。这一行动所传递的行为，与其说是示好，不如说是强烈警告。坦白讲，如果我是福田康夫，那我感到的，将是刺骨的寒意。如
果中日能友好，那么北京能放下那千万笔的血债；如果日本人不识抬举，敢加入接下来几个月随时可能爆发的解放台湾的战争，那么，南京大屠杀的场面出现
在东京绝对是再正常不过的事情。这一行动所包含的“坚忍”绝非常人所能做出的。过去的几年里北京是怎么收拾死硬的小泉纯一郎的大家都看的清楚，所以，
我想没人会怀疑北京对日本的强硬态度吧？

    面对着北京的强烈警告，日本人也感觉的确有必要做点什么了。于是乎，俄罗斯抓日本渔民的一幕就很自然的出现了。

    应该说，这一幕与半年前伊朗人抓英国水兵的一幕如出一辙。美国人不是逼日本人表态协防台湾吗（如果日本不加入战场，那么台湾就相当于美国白送给
北京，台湾的武装力量可以忽略不计，一旦台湾解放，就相当于北京卡住了日本的咽喉，这也是美国用后果在逼日本做出决定）？日本人的态度出来了：现在
毛子哥抓了我的渔民了，美大哥是不是该替我说句公道了？

    布什这下子可真傻了：没想到那龟孙子比我还阴！美国人怎么可能插手俄日领土纠纷？美国对付俄罗斯和中国的办法是“分别单挑”：对付俄罗斯是在波兰
-捷克-乌克兰-格鲁吉亚一线，在俄罗斯与欧盟之间砸楔子、利用颜色革命在俄罗斯家门大摆天门阵；对付中国是在台湾，利用台独牵制北京的精力。现在俄
日领土纠纷出来了，如果布什出来为福田康夫撑腰，那正合了普京的心意，因为普京就可以光明正大的与我们胡总在东亚联手对付美日，这样一来，北京的压
力将大大减少。北京也就会有更大的精力夯实巴基斯坦通道、巩固伊朗-叙利亚（包括真主党）联盟，在巴以和谈和伊拉克重建问题上也会花更多的心思给美
国政策添点儿佐料。而这些行动将会极大的支持在东欧（反导问题）与美国斗得昏天黑地的俄罗斯，也会让“老欧洲”看到与越战越勇的中俄联手的好处，从而
出手管管整天跟美国人眉来眼去的“新欧洲”（可以挤出美国对东欧的影响从而加快欧盟的内部整合），从而让中俄欧在中东抗美斗争中更加团结。所以，布什
根本不可能出面替日本人说话。可是，如果不给自己的盟友撑腰子，福田就有了对付布什的办法了-----我们是盟友，我的大麻烦你不管，你又凭什么要求我
一再的为你卖命呢？要我在台湾为你拼命可以，我们把“北方四岛-钓鱼岛-台湾”问题打包处理如何？

    俄罗斯也从这一行动中得到了不少的好处：首先就是让美国看到了中俄联盟的无懈可击。再就是让正在忙着开门迎客布署TMD系统的波兰捷克看一下，他
们全身心投靠的美国盟友是如何关照盟友利益的（美国在日本已经布置了导弹防御系统，却不管日本人的死活，它只是希望借日本的国土来防止打到美国本土
的东风导弹），那么，接下来波兰捷克在变成美国导弹基地时是不是要多长个心眼、免得白给美国人当炮灰？

    最后，我们可以理顺出俄罗斯抓日本渔民事件的来龙去脉了：首先是日本通过某些途径向俄罗斯放风，有“不是协议授权的登记渔船”去俄日争议海域捕鱼
，接着心领神会的俄罗斯海军出手抓人，最后由心怀鬼胎的日本人大喊“要求莫斯科作出解释”，结果就是美国人吃个哑巴亏，看着日本人“合情合理的”逃出了
可能出现的台海战场。




** 当西方“民主”遇上中国“实事求是”

    “美国黑人的投票权到１９６５年才真正开始；瑞士是到了１９７１年，所有的妇女才获得了投票权，瑞士才实现了真正意义上的普选。如果要推动西方
式的民主化，西方自己首先要向别人解释清楚，为什么你们自己真正的民主化过程毫无例外都是渐进的，都是在现代化之后才实现的？”

    国人看世界：我见到的西方民主

    论坛：不能把民主的什么东西都看作是“西方的”

    求是：如何看待西方民主制度? 照搬从来不能成功

    今年６月下旬，在德国慕尼黑郊外一个风景如画的避暑山庄，知名的马歇尔论坛举行了一场中国问题研讨会，由笔者主讲中国的崛起及其国际影响。演讲
后，一个欧洲学者问道：“您认为中国什么时候可以实现民主化？”笔者反问：“您的民主化概念怎么界定？”他颇有点不耐烦：“这很简单：一人一票、普选、
政党轮替。”说完，还补充了一句，“至少这是我们欧洲的价值观。”

    笔者表示完全理解和尊重欧洲价值观，但随即问他：“您有没有想到中国也有自己的价值观，其中之一就是实事求是，英文叫做ｓｅｅｋ　ｔｒｕｔｈ　
ｆｒｏｍ　ｆａｃｔｓ（从事实中寻找真理）。”笔者接着说：“我们从事实中寻找了半天，就是没有找到发展中国家通过您所说的这种民主化而实现现代化的
例子。我走访了一百多个国家，还没有找到。”这时，一个美国学者大声说：“印度。”笔者问他：“您去过印度吗？”他说：“没有。”笔者回答：“我去过两次，
而且从北到南，从东到西都去过。我的感觉是印度比中国要落后至少２０年，甚至３０年。我在孟买和加尔各答两个城市里看到的贫困现象，比我在中国２０
年看到的加在一起都要多。”

    又有学者说：“博茨瓦纳？”笔者同样问道：“你去过没有？”他说：“没有”。笔者答道：“我去过，还见过博茨瓦纳总统。那是一个人口才１７０万的小国
。博茨瓦纳确实实行了西方民主制度，而且没有出现过大的动乱。这个国家资源非常丰富，民族成分相对单一，但即使有这么好的条件，博茨瓦纳至今仍是一
个非常贫穷的发展中国家，人均寿命不到４０岁。”

    “那么哥斯达黎加呢？”又有学者问。“你去过这个国家吗？”回答还是“没有”。笔者的回答是：“我２００２年访问了这个国家。那也是一个小国，人口才
４００多万。相对于中美洲其他国家，哥斯达黎加政治比较稳定，经济也相对繁荣。这个国家９０％以上的人口是欧洲人的后裔，各方面起点不低。可惜哥斯
达黎加至今仍是一个相当落后的国家，而且贫富差距很大，人口中２０％还处于贫困状态，首都圣何塞给人的感觉更像个大村庄，有很多的铁皮屋、贫民窟。
”

    之后笔者干脆反问：“让我举出西方民主化模式在发展中国家不成功的例子？举１０个、２０个、还是３０个？还是更多？”我简单谈了一下美国创建的民
主国家菲律宾、美国黑人自己在非洲创立的民主国家利比里亚、美国家门口的海地，还有今天的伊拉克。此时，有一些听众开始点头，一些人摇头，但就是没
有人起来反驳。笔者便再追问了一个问题：“在座的都来自发达国家，你们能不能给我举出一个例子，不用两个，说明一下哪一个今天的发达国家是在实现现
代化之前，或者在实现现代化的过程之中搞普选的？这里论坛的哪位能举出哪怕一个？”还是没有人回答。我说：“美国黑人的投票权到１９６５年才真正开始
；瑞士是到了１９７１年，所有的妇女才获得了投票权，瑞士才实现了真正意义上的普选。如果要推动西方式的民主化，西方自己首先要向别人解释清楚，为
什么你们自己真正的民主化过程毫无例外都是渐进的，都是在现代化之后才实现的？这个问题研究透了，我们就有共同语言了。”

    我还顺便讲了一个自己的假设：“如果中国今天实行普选会是一种什么样的结果呢？假如万幸中国没有四分五裂，没有打起内战的话，我们可能会选出一
个农民政府，因为农民的人数最多。我不是对农民有歧视，我们往上追溯最多三四代，大家都是农民。我们不会忘记我们自己农民的根，我们不歧视农民，不
歧视农村来的人。但是连领导过无数次农民运动的毛泽东主席都说过：严重的问题在于教育农民。一个农民政府是无法领导一个伟大的现代化事业的，这点你
们比我还要清楚。”

    当时因为还有其他许多有意思的问题，民主化的问题就没有继续讨论下去。实际上任何人只要花点时间读上几本西方民主理论的入门书，就会知道西方大
部分民主理论大师，从孟德斯鸠到熊彼特，都不赞成为民主而民主，都认为民主只是一种程序、一种制度安排、一种游戏规则，其特点是“有限参与”，而不是
“无限参与”。当然也有像卢梭这样的理想主义者，呼唤人民主权，不停地革命，但法国为此付出了异常沉重的代价，最后实现的也不是卢梭期望的“目的民主”
，而是“工具民主”。

    美国宾州大学教授爱德华·曼兹菲尔德和哥伦比亚大学教授杰克·史奈德最近出版了一本著作《选举到纷争：为什么正在出现的民主国家走向战争》。书中
的基本观点是：走向西方民主模式的这个过程，最容易引起内部冲突或外部战争，因为政客们只要打“民粹”牌就容易得到选票。整个上世纪９０年代里，许多
国家举行自由选举后，便立即进入战争状态：亚美尼亚和阿塞拜疆开打，厄瓜多尔和秘鲁开打，埃塞俄比亚和厄立特里亚开打，还有布隆迪、卢旺达的大屠杀
，导致１００多万人丧生，当然还有南斯拉夫令人痛心的分裂和战争。我去年访问了前南斯拉夫所有国家，光是波斯尼亚战争中死亡的人数，最保守的估计都
超过１０万人！成为欧洲二战后死亡人数最多的战争。

    再看看中国，走自己的路，在不到３０年的时间里，保持了政治稳定，经济规模扩大了１０倍，人民生活普遍提高，虽然仍存在各种问题，有些还相当严
重，但中国的崛起，整个世界有目共睹，大多数中国人也对国家前途表示乐观。中国的相对成功为中国赢得了宝贵的话语权，这种话语权就是可以和西方平起
平坐地讲道理，你有理，我听你的；你没理，你听我的。要是都听西方的，中国早就解体了。

    在民主化这个问题上也是这样，西方还是没有摆脱“惟我正统，别人都是异教”的思维模式，这种思维模式在历史上曾导致了无数次战争，几乎毁灭了西方
文明本身，西方本可以从中悟出很多道理。但是西方，特别是美国似乎还没有从中吸取足够的教训。如果西方真心想要在发展中国家推动民主，就应该认真总
结自己民主发展的历史，其中一个关键问题就是民主化的顺序，西方原生态的民主社会自己演变的顺序大致可以这样概括：一是经济和教育的发展，二是市民
文化和法治社会的建设，最后才是民主化。这个顺序搞错了，一个社会往往要付出沉重的代价。现在西方却要求第三世界在民主化上一步到位，把最后一步当
作第一步，或者三步合为一步，不出乱子才怪呢。（张维为瑞士日内瓦大学亚洲研究中心高级研究员  来源：中青在线-青年参考  ）


** 【奋进社/金鸿95】有感于万科降价

[2007-12-25 20:08:27]

    高房价不仅仅是个民生问题，还是影响国民经济平稳运行的重要因素。以前我已数次发文讨论高房价的问题，一篇是《从一则新闻想到的》、一篇是《十
七大后房价也和谐》（还有一篇《房价狂飙的日子就要结束了》与此篇是换汤不换药，组材形式不同但内容一样）。每篇得出的结论都是一样的，那就是房价
会降。今天看到了万科降价的新闻，就再写一篇文章讨论房价，总结一下思路。

    经过思考，我个人感觉，三方面的原因导致房价必然下降：

    一、释放经济运行风险，保证国民经济正常运行。

    1、房价持续在高位运行，给国民经济的平稳运行带来了巨大的风险。它不仅仅掏空了广大买房的老百姓的钱包，还让他们中的许多人背上了大额的债务
，一旦因为房价的持续走高将供求链拉断导致房价暴跌，将会给他们的生活带来巨大的负担。这里面的道理很简单：房价持续走高，终有一天会高到老百姓买
不起房的地步，那时，原本指望用高房价赚取更多利润的开发商为了回拢资金必然降价。当然，在降价以前开发商们会有一段“有价无市”的坚持高价不降的时
期，但是，一旦被日益绷紧的资金链逼到无力维持局面的时候，降价销售将成为必然选择。但是，在房价掉头下跌时，出于“买涨不买跌”心理的支配，持币等
待的买房人不但不会加入购买者的行列反而会“再等等看看房价会不会再跌的低一点”（他们怕自己买亏了）。在这样的情况下，出现价格暴降出售房产以回拢
资金的情况是很正常的，这种情况与股市暴跌时股民恐慌性抛盘割肉平仓是同样的道理。一旦房价在这样的情况下被打回原形，降价前买房的人将平添巨大的
包袱（举个例子，假如某人在房价下跌前花120万买房产一套，首付50万贷款70万，可房价暴跌后他的房产只值60万，此时，他即使马上将房产卖出以回款60
万归还银行贷款也不够，还得背10万元的债务。这样在房子的一买一卖中自己前期积累的财富就全部失去了）。这样一来，大量“负翁”的出现会带来严重的社
会问题。

    2、房地产是资本密集型产业，如果房价持续高涨最终把供求链拉断了，接下来房地产开发企业的资金链也会马上绷断。而中国的房地产开发企业大都在
银行有巨额贷款，如此一来，又会为银行增加大批的呆坏帐。

    3、房价持续走高会短时性（十年内）的让房地产企业赚得远超过其他行业的利润，在利润的驱使下，大量其他行业的优秀企业也有可能放弃对本行业的
投资而转向房地产开发，从而造成房地产业的过度投资、过量开发的畸形发展。

    4、房价的持续走高还会引发大规模炒房现象的出现，从而加重房地产行业的“过度需求”。炒房者大量屯房不是为了居住而是为了低买高卖以赢利，但由
于他们的大量屯房导至本已不足的供应量更显捉襟见肘，从而刺激房地产开发商更大规模的开发，造成房地产业的“过度繁荣”。

    从以上四个方面来看，房价持续走高会对国民经济的平稳运行带来极大的隐患。但是，国民经济的运行风险还不仅仅在于房地产业。

    随着国内金融业的发展和对金融创新的需求，股指期货的推出都将成为必然。股指期货推出后，金融风险会大幅增加。可以举例说明：假如现在股市指数
是3000点，某些庄家联手以巨资入市（比如八千亿美元），用半年的时间吃足筹码，在股指高涨的信心支持下，广大散户和基金也纷纷看好股市，股市指数被
推高到了6000点。此时，庄家们在股指期货市场上以巨资买跌（比如买股指跌到4000点）。此后在股市上疯狂砸盘，从而引发股市恐慌性抛盘，股市暴跌。因
为他们吃筹码时股价低，所以砸盘时依然会赚钱。同时，因股指的暴跌他们还可以从股指期货上狠赚一笔。当股市上的股票价值被砸倒底以后，他们再次大笔
资金入市，顺手抄起那些被严重低沽的优质股票，为下一轮次的获利收集筹码（如果能在股市暴跌时能收购掉进资本陷阱的优秀企业那就更是喜事一件了）。

    如果房价高位运行的风险和因股指期货推出带来的风险叠加起来，危险更大。比如，在上面所举例子中股市暴跌时，更会增加房市供求链拉断的风险。因
为已经太多的人在股市上破产了，从而导致需求大幅萎缩，从而出现股市暴跌引发楼市暴跌的局面。

    所以，出于挤出经济运行风险的考虑，调控房价也已成为必然。

    二、房地产业支持不起中华崛起，不适合做支柱产业。

    十年前，出于国内外经济运行环境的不得已，把房地产业做成了支柱产业。其实，任何一个真正发达的国家，都不是依靠房地产业来支持国家强盛的。强
国富民靠的是科技领先。前几年数次调控，房价都没有降下来，一个非常重要的原因就是房地产业是支柱产业，所以，打压房价一直难见实效。随着国内产业
结构的调整和研发投入力度的增大，具备了给房地产业“换位”的条件。

    过去的几年里，数次调控都没有取得良好的效果，与房地产业的支柱地位是有相当关系的。作为支撑经济运行的支柱产业，国家不可能强力打压它，以避
免影响国民经济的良性运转。

    8月21日新华网显要位置刊登了空军上校戴旭的《房地产支撑不起大国崛起》一文，新华社是代表中国官方态度的,这篇文章的刊登就是中央要对房地产业
进行定位调整的一个信号。

    三、地方政府“经营城市”的做法将会发生改变。

    过去的数年里，有些地方政府为了增加地方上的财政收入，大力“经营城市”，在居住用地拍卖中大把的赚银子。这样做在无形中增加了房地产开发的成本
。房地产开发商搞房地产开发是为了赢利，他们必然把这部分成本转嫁到买房者的身上。由此可见，“经营城市”是高房价的推波助澜者。

    十七大后，各地方政府开始准备换届。正如易宪容先生所说，中国的房价会不会降取决于明年。“取决于明年”不是因为明年有奥运会，而是因为明年是地
方政府的换届年。如果换上来的地方领导能改变“经营城市”的理念，房价下降将是一件非常自然的事情。

    我们有足够的理由相信，明年开始的地方政府换届会为我们选出务实的为人民服务的新一届地方领导。十七大后，中组部由中央政治局委员李源潮亲自
抓,我们相信，中央对地方的人事管理会有一个全新的局面。中央是政策的制定者，地方政府是执行者。上面的好政策需要下面不折不扣的贯彻执行才能发挥
出作用。我们也相信，随着地方政府的换届，胡总书记和温总理为我们制定的好政策将得到更好的执行。

    综合上面三方面的考虑，房价下降是必然的。

    从“首付四成”的政策一推出，部分南方一线城市的房市就进入了冰河期，甚至房价开始调头。

    随着房地产调控力度的加大，房地产业大腕们的表现各不相同：王石的万科带头降价；任志强则宣称“房价下跌对国民经济不利”，有“地产教父”之称的冯
仑则发表了一翻“未婚女性刺激房价上涨”的言论。对于任大嘴，我无意置评，种什么树就收什么果子好了。倒是冯仑的表现让人大跌眼镜，这哪象教父级的人
物说的话？如果打个洞就能住人的话，还有人买房吗？还有高房价这一说吗？而王石，在这关键时刻，带了一个好头。

    一个人，不论在哪个行业，只要真正有所作为，想让自己的名号挂上个“家”字应该不是件太困难的事。只要满足一个条件就可以了，那就是有“社会责任
感”。一个政治领袖，如果没有社会责任感，那他就是一个政客（比如陈水扁），如果有，那他就是一个政治家；一个写文章很好的人，如果没有社会责任感
，那他就是一个写手（比如郭敬明，公然剽窃还不承认），如果有，那他就是一个作家（比如鲁迅）；一个搞企业的老板，如果没有社会责任感，就算他的企
业做的再大也只能算是一个富豪，如果有，那他就是一个企业家。由此看来，只有王石对得起“企业家”这三个字。

    与“只能富人盖房子”的任志强不同的是，王石一直在努力的加入为穷人盖房子的行列。其实，抛开社会责任感不说，单就市场嗅觉而言，王石也够精明。
沃尔玛是最大的连锁超市，它就是主要为平民服务的，麦当劳在美国也主要是卖给穷人吃的，而这两家企业，不论是规模，还是赢利性，都是不得了的。这也
说明了一个道理，只有真正利人，才能充分利已。

   当年，朱总理把房地产业做成支柱产业时，就请王石做自己的地产顾问（据说无薪），今天，又是王石带头降房价。而且，万科几年来一直没有大量屯地
，万科权益储备为1818万平方米，可用于2-3年的开发。相比之下，碧桂园的杨首富（5400万平储备、六年都开发不完）就比较危险了。按照《闲置土地处置
规定》，超过两年不开发的将被无偿收回。王石降价卖房是不是为了加快储备用地的开发以被没收的可能？一旦中央下了重手，以没收土地的方式对付屯地的
开发商来降房价将是非常自然的事情，对此，大家没有必要去怀疑----五年多了，胡总书记和温总理的行事风格（亲民务实）大家也都见识过了。

    当然，如果房价在政策的压力下猛然掉头下跌，会严重打击房地产这个行业，也会损害大批高价买房老百姓的利益。所以，中央有意放慢动作，让房价平
稳下降。从“第二套房以个人为单位还是以家庭为单位”的确定过程就能清楚的看出来（先放风说由银行自已确定，接着几个大银行多数说“以家庭为单位”、个
别说以“个人为单位”，经过一两个月的市场适应后中央再明确规定，“以家庭为单位”），中央是希望用温水煮青蛙，而不是用油把青蛙炸了（以各种方式缓冲
风险，希望所有有良知的开发商都能体会胡总书记和温总理苦心）。但是，如果哪个开发商认为自己有能力与国家利益博弈的话，不妨试一把，也好感觉一下
在破产的道路上“潇洒走一回”是什么感觉。
** 【奋进社/金鸿95】西方经济学的“原罪”


改革开放以来，西方经济学渐渐成为主流。出于提高素质的考虑，近两个月来用业余时间学习了一下。刚刚学完微观经济学部分，就发现了许多问题。这些问
题细细看来，绝非细枝末节，而是关乎这套理论的是否科学的大问题。

在经过反复思考之后，金鸿发现微观经济学的研究方法上存在着三个原则性错误，现列举如下：

第一、  经济理性主义。

微观经济学在做分析时，有一个最基本的前提，就是“理性人”。即认为所有的人和企业的经济行为都是理性的或者合乎理性的（而不是本能的或者感情用事的
），也就是说“济经人”都会做出最优化的行为，而不受感情的影响。这一点，是脱离现实的。

举个例子：拿我们普通人来说，在购物时常会做出两种举动，冲动消费和冲动不消费。 “冲动消费”，指的是因一时的购买冲动而掏钱购物，之前根本没有购
物的打算或者没打算当场做出购买决定，这一种消费者心态在各种促销场合被商家广泛的利用（不仅仅是快速消费品，耐用消费品同样如此）。 “冲动不消费
”，是指，在消费者购物时，已决定购买某件商品，可因为销售人品的不当言行引发了顾客的反感而决定不再购买。这种情况也是生活中经常见到的。消费者
往往为了自己的“面子”（尊严）、对自己“上帝”地位的维护，而放弃自己中意的商品另选其他本不打算选择的商品。也正是基于对消费者这种心态的迎合，现
代企业都强调“服务意识”。如果上升到“企业档次”的层面，就是“一流的企业做标准，二流的企业靠服务，三流的企业抓质量”。这些日常生活中比比皆是的非
理性行为决定了“理性人”根本就是不可能存在的。

既然推论结论的最基本假设都是错误的，那凭什么得出正确的结论？皮之不存，毛将焉附？难到是歪打正着？

当然了，按照经济学家们的解释，这是一种“科学的抽象”，是为了在做经济分析时“抽出主要的、基本的因素”，并在此前提或基础上，提出一些“重要的理论
结论”，并据此对人们有关经济行为作出预测，提供行动方针或政策决策的理论基础。金鸿个人并不否认这一观点，但是，上面的事实说明了一个道理，那就
是这些经济学理论是建立在一定条件之上的；也就是说，如果现实中的某些情况不符合这些假设，那么这些结论就不再适用；也就是说，这些经济学理论并不
是万灵丹，我们还需要考虑这些经济学理论决定不了、解决不了的问题我们该怎么解决，而不是言必称“西方经济学”。

其实，上面的缺陷还是次要的。毕竟，任何理论都有它不适应地方，我们应该抱宽容的态度。最关键的是，西方经济学以“理性人”以前提做理论推导时，包含
了另一个更深层次的心理暗示：资源配置应该优先考虑个体最优（包括个人收益最大化和企业收益最大化），并给人们以这样一种感觉-----个体最优可以带
来整体最优；而我们社会主义国家在配置有限资源的时候，首先应该考虑的是整体利益，任何个人利益和部门利益都必须为整体利益让路。虽然西方经济学里
没有明确的做出这样的论述，但它的所有微观经济学理论的推导中，都在分析如何实现个体最优而不提整体最优，这本身就是一种极大的误导。

我们引入市场机制是为了引入竞争机制，利用个体（包括个人和企业）追求自身利益的最大化的动力来发挥个体的主动性、积极性和创造性，为优化整个社会
的资源配置提供帮助，防止出现“干多干少一个样、干与不干一个样”的无效或低效个体行为。我们同样需要明白的是，市场机制只是手段，是为了实现我们的
社会主义共同富裕的目的的手段，不是目的。对此，我们绝对不能本末倒置。我们必须明白，市场机制是在一定范围内有效发挥作用的，而不是包治百病的神
药。

诚然，个体最优在许多情况下有利于实现整体最优；但是，同时在许多情况下，实现整体最优往往意味着某些（甚至是许多）个体无法实现最优，而只能是次
优、甚至很差。因为在许多时候，整体利益与整体中的某些个体利益是相冲突的。如果我们按照西方经济学的理论来做推导和说明，那就得优先考虑个体利益
而非整体利益，这与我们的社会主义制度合的来吗？在这种冲突出现的时候，我们优先需要考虑的是整体利益。而有利于实现整体利益最优的办法就是宏观调
控。我们需要竞争机制，更需要宏观调控。近年来，改革过程中屡屡听到某些“经济学家”发出震惊世人的言论，指责国家的某些政策方针违反“经济规律”。在
此，禁不住想问一句，这些“经济规律”是不是建立在“种种假设之上的西方经济学理论”？这些“经济学家”们又是在为谁的利益代言？

第二、信息完全。

就是假设个体能得到做出决策行为所需要的全部信息。可是，现实世界中，这个假设是绝对不成立的。生活在现代社会的人们都知道，信息是最值钱的最东西
。正因为信息值钱，许多大企业才会花巨资建立信息系统，也才会有专业靠整理、分析信息发财的大公司存在。

如果有全面系统的信息，就不会有人再做出错误的决策，也就不会有公司破产，也就不会有贱买贵卖的投机行为，也就不会有股市上的有人暴利有人被套。活
生生的现实摆在那里，认为人们能得到全面信息的假设又该如何解释这些现象？

举个例子：美国拥有全世界最强大的情报系统，中央情报局（CIA）和联邦调查局（FBI）闻名于世，可就是它们，穷多年之力都没有抓住拉登。可见，在许多
情况下，想搞出正确的信息是一件多么困难的事。奇怪的是，明明办不到的事，经济学家们却当它是三岁孩子就会的本领。难道普通人和社会上的一般规模的
企业比CIA和FBI还厉害？难道在经济学们的眼里，世人都是“前知五百年、后知五百载”的神仙？

再举个例子：微观经济学的市场与价格决定理论都是用信息完全这个假设为前提进行的推导。市场与价格决定理论是微观经济学中的最要组成部分，它们讨论
的内容分析的主要是完全竞争市场、完全垄断市场、垄断竞争市场和寡头垄断市场的均衡价格和均衡产量。信息完全就是推导这些理论的假设条件之一。信息
完全这个假设毫无疑问是不成立的，那么，建立在这个假设之上的那些结论的正确性又有多少呢？其适应面又有多广呢？（在后面文中有对“古诺模型”的质疑
，可以充分说明这些理论的可信度有多低！）

第三、模型陷阱。

打开经济学教材的第一感觉就是：公式遍地是，图表满天飞。看似科学严谨，实则漏洞百出。随便建立一个模型就是幂指对函数一齐上，动不动就微积分，好
象多么的规范！其实，现实世界跟这些模型根本就对不上号。

每一个模型都是这样：先做一堆假设，然后列出几个包括五个以上变量（甚至无数变量）的函数公式，接下来再假设某些变量为常数，把剩下的变量进行微分
或者复杂的方程组求解，推导出一堆结论公式。当然，这些结论给人的感觉是，很科学，很正确。

可一旦把这些结论与现实经济现象进行对比时，却发现相去万里。为什么会出现这样的情况？原因有二：一是假设的前提不正确，二是现实经济行为往往不能
微分（无限细化）。所以，完美的微积分被经济学家运用到经济分析中却成了骗局。金鸿的观点，可能许多人会反对（金鸿在下面文中会通过对一个经典的经
济模型的批驳来证明自己的观点）。

在市场与价格决定理论中有一个非常经典的模型，叫古诺模型（双头垄断理论），这个模型是建立在六个假设之上的：市场上只有两个生产者，产品完全相同
；产品的生产成本为零（两个生产者的生产成本相同也可以）；总需求是线性的；信息完全；生产者的行为具体连贯性和可参照性；经济理性主义，两个生产
者均以利润最大化为目标。

经过一系列复杂的推导之后，得出一个结论，两个生产者为市场提供的产量为总需求量的1/3。将古诺模型中的厂商数量放大后（N个）的结论是，每个厂商提
供的产量为总需求量的（N/N+1），也就是说，市场上不存在生产过剩（即有未能销售出去的库存积压）。这一结论与现实状况完全相反！因为在古诺模型中
，所以厂商提供的产量（总供给）加总都不超过市场总需求量，而现实是，许多行业存在生产过剩，即总供给大于总需求。

为什么会出现这样的情况？因为西方经济学假设的前提有严重的错误。主要错误有两个，就是上面讨论过的经济理性主义和信息完全。现在生活中，人们并不
是理性的，极少极少有人能控制住自己的欲望以实现行为最优化，而是受个人贪欲的控制，做出非理性的举动。现实生活中，每个人都有欲望，都有追求（没
有欲望的人，要么死掉，要么出家）。而有欲望的“俗人”，往往非但不能控制好自己的控制，反而不惜代价的来满足自己的欲望。所以，我们看到的现实就是
，太多的的人因为自己的贪欲（贪财、贪色、贪权）而违法犯罪。按照西方经济学的假设，应该没有人去犯罪才对，这可能吗？这还是人间吗？天堂也不过如
此。至于全面信息，就更不可能了。正是没有全面信息，才会出现错误决策。在经济学家们的眼中，世人应该都能掐会算的神仙吧？

再来看一下古诺双垄断模型的推导过程，其最初设想是以“一个独占者垄断市场、然后有一个竞争者进入该市场”展开分析的。按照古诺的分析，第二个厂商进
入市场后会提供总需求量的25%，第一个厂商会减少产量（从最初提供总需求的50%变为37.5%），之后第二个厂商会再把产量提高到总需求量的31.25%，之后
第一个生产者会把产量进一步减少到34.75%……最后形成均衡，两个厂商各提供总需求量的1/3以分别获取最大利润。

在这一设想中，两个厂商在竞争中表现的多么的谦恭文雅！现实中有这样的厂商吗？我们看到的现实是，当新的竞争对手进入市场后，市场上的主导者总是想
尽一切办法去封杀新进入者的生存空间（包括降价、霸占市场销售渠道、甚至控制关键原材料等办法），市场竞争往往是你死我活的，甚至许多企业会动用非
法手段。再加上某些厂商决策的盲目性与冲动性，导致了几乎所有行业都出现了（或者出现过）生产过剩，这更是与经济学家们的假设格格不入。为什么经济
学家置现实与不顾？做出这种与现实截然相反的“经典模型”来有什么用？粉饰太平？

正是由于微观经济学在研究方法上存在着明显的漏洞，导致对市场机制的作用产生了过高的估计。在现实生活中，市场作用有其局限性。

市场机制可以优化个体行为，从而有利于资源配置的优化。但是，市场机制也有过度“功利性”的一面。举个图书出版业的例子：当整个行业全面市场化之后，
图书出版商为了扩大销售，只能迎合图书购买者的心理，出版买书人喜欢的图书。比如，某个出版商专门出版面向青少年的书籍，为了迎合小读者，他们将大
量印刷恋爱小说、武侠小说甚至色情小说。只有这样，它的图书销量才会上的去,才会赚得更多的利润。但是，这些书籍对小读者们的身心有益吗？对他们的
成长有利吗？很显然，答案是否定的。在互联网企业竞争中也出现了这样的情况。各网站为了吸引上网者的目光，提高流览率，把许多色情、暴力、猎奇的文
章列为头条。这样一来，点击率是上去了，企业的“最优化”也实现了，可读者在不知不觉中被进行了一次次的“反面教育”，这对整个社会的社会风气有好处吗
？答案同样是否定的。这个例子充分说明，许多情况下，个体最优实现了，整体最优却没有了。物质需求满足了，精神却变得空虚了。如此一来，谈何“效用
最大化”？我们发展经济是为了满足物质需要，但不能放弃精神追求。而市场机制在提高对社会成员“精神满足”方面，有先天的不足，因为这套理论是建立在“
利用个体追求私欲满足的本性”这一基础上的。

市场机制的确有利于优化资源配置，但是，它只适合能够全面展开竞争的行业，有些行业因为有部分资源易于被垄断，这些行业必须加强宏观调控，而不能将
其“自由放任”、完全交给那只“看不见的手”。比如房地产业。中国是一个人多地少的国家，在沿海许多省份，建设用地非常稀缺。如果把这些城市的住宅建设
全部交给市场，必然会出现优先给富人盖房子的现象。因为富人更有购买力，把有限的建设用地用来建设适合他们居住的房子比给穷人盖房子更有利可图。另
外，因为每年供应的土地量少，有实力的开发商可以大量屯地以减少市场上的竞争对手、提高销售价格、增加利润。如此一来，开发商个体实现行为最优化了
，所以，象房地产这样的行业，加强管理和调控是必需的。唯有如此，才有可能实现整体最优。

其实,如果不加强对市场的管理和调控,任何一个行业在其生命周期的变化中，都会由最初的竞争状态转变为垄断状态，使资源配置效率大打折扣。市场机制是
配置资源的一种手段，只有善加利用、扬长避短才能有利于我们的社会主义现代化建设，才有可能实现全社会的和谐发展。

任何一种理论都是对现实世界的抽象。通过合理的抽象，来描述客观世界，总结出规律性的东西，进而指导人类改造自然的种种活动。可是，如果通过一系列
的抽象之后，得出的“理论中的世界”与“客观的世界”有明显的差距甚至完全相反，这种理论就有问题了。在出现这样的情况时，我们应该相信现实，还是应该
相信那些所谓的“科学理论”？

综合上面列举出来的种种明显缺陷，西方经济学理论不是建立在客观事实之上的一门科学，而是建立在种种“不可能实现的理想状态下”的空中楼阁。虽然它华
丽无比，却无法给人居住。所以，西方经济学的科学性是非常值得怀疑的。那些整天抱着西方经济学理论招摇撞骗的“经济学家”们，到了走下神坛的时候了。


** 【奋进社/金鸿95】曙光

[2007-12-28 19:25:25]


美国国务卿赖斯21日在国务院举行的记者招待会上表示，她不排除访问朝鲜、伊朗和叙利亚的可能性，但这3国必须首先满足一些条件。

【金鸿评论】看来，美国情报机构提供的伊朗已于2003年停止核武器计划的报告终于“打动了”美国政府的那群老鹰，扮出了鸽子相的赖斯也顺势表现出了一点
作为女人应有的温柔。

对于布什政府而言，这绝对是无奈之下的选择。几年来，美国一直希望以核问题为借口拿下伊朗，实现自己独霸中东的梦想。可在中俄欧的联手阻截下，没有
任何进展。不仅如此，美国还在伊核问题上屡屡被算计，特别是中国，抓着伊核(配合着朝核)，不停的制造问题刺激美国的战略神经，美国被逼无奈，多次让
步，可局面越来越不利。

近一年来，中国削尖了脑袋想挤进巴以和谈，可美国人始终把大门关的死死的，对坐在巴以和谈谈判桌上的俄罗斯更是极尽排挤之能事。这对于有志于成为世
界一极的中俄而言，绝对是不可接受的。几个月以来，北京加大了力度，用伊核危机升级（比如内贾德声称伊朗已是核国家）逼美国敞开大门请自己介入；美
国却选择了对欧盟让步来换得欧盟的伊拉克、阿富汗的合作、制裁伊朗的不反对。于是，失去了耐心的北京选择了另起炉灶，与在巴以和谈上郁郁不得志的俄
罗斯联合出手：俄罗斯从美国人手里“抢牌”，中国则在后面自己“做牌”并给俄罗斯“递牌”。

叙利亚外长穆阿利姆26日在此间会见了到访的中国中东问题特使孙必干，双方就地区局势交换了意见。

孙必干在会谈中说，中方一贯主张中东问题有关各方在联合国有关决议、“土地换和平”原则、“阿拉伯和平倡议”的基础上，通过谈判解决争端，实现阿以和平
共处。中方支持叙利亚收回戈兰高地的正当要求，希望叙以之间早日重开和谈，这将有助于中东问题的全面解决，也有助于中东地区的和平与稳定。中方愿同
有关各方共同努力，为推动叙以尽快复和谈和中东地区实现公正、持久的和平发挥建设性作用。

穆阿利姆赞赏中方在中东问题上的公正立场，表示叙将坚持和平选择，通过谈判收回被占领土，解决与以色列的争端，并为实现中东地区的和平与稳定做出更
大贡献。

【金鸿评论】孙特使的这次中东之行，目的非常明确，就是抢夺巴以和谈的主导权。从新闻报道的结果来看，收获的确不小。

俄罗斯人出手了，声称“准备在巴勒斯坦两大派法塔赫和哈马斯之间进行调解”。其实，这哪是当“调解人”？分明是跟美国抢人！美国人一方面控制着以色列，
另一方面收买了法塔赫的阿巴斯，从而牢牢掌控着巴以和谈。而坚决维持伊斯兰尊严的哈马斯始终被美国人视为眼中钉，一心希望除之而后快。而俄罗斯，却
在支持哈马斯。现在，俄罗斯出面为法塔赫和哈马斯调解。如果调解成功了，两派拧成了一股绳，会亲美吗？那俄罗斯会干吗？结果只能是两派一起反对以色
列。当然，法塔赫可以不接受俄罗斯的调解，继续坚持出卖伊斯兰世界的利益，那时，俄罗斯就可以利用阿拉伯世界（与俄罗斯关系很好的叶什派就更不用说
了）对法塔赫的愤怒狠狠的将它修理一番。而一旦俄罗斯对两派的调解成功了，巴以和谈就该换一种玩法了：美国人控制着和谈的一方以色列，俄罗斯人控制
着和谈的另一方法塔赫与哈马斯（抢牌）。那时的巴以和谈就不是美国人说了算了，本来靠边站的俄罗斯人就可以自信的坐在“大堂上”，而现在在巴以和谈中
大显玲珑身段的欧盟就得找个地方休息一下了，俄罗斯则会顺势把中国拉进来，那时的美国，情将何堪？

近期欧盟在巴以和谈中从美国人手里捞到了不少的好处，法国总统萨科齐出访阿富汗访并暗示有可能增派部队到阿富汗协助当地军警就是个明显的标志，当然
，萨科奇也很聪明，只说协助当地军警，不提打击塔利班。显然，欧盟还没有自大到认为自己在南亚有和中俄搏一把的地步。为了最大限度的削弱美国的力量
，而不激起欧盟的强烈反对,俄罗斯在欧盟与美国进行了精确切割：

一方面对美继续强硬的进行军事震慑（25日俄罗斯北海舰队的“图拉”核潜艇成功发射了一枚洲际弹道导弹）；一方面对欧盟示好（21日俄罗斯外长拉夫罗夫说
，俄不打算在本国欧洲地区增加常规武器，并建议给北约国家的常规武器总量确定最高限额），同时对欧盟进行警告，不要美国靠的太近，否则，重回冷战状
态不是不可能。俄罗斯的软硬兼施很快收到了效果，欧盟通过自己的代理人土耳其及时应合了俄罗斯（土耳其总理埃尔多安和俄罗斯总统普京于25日通电话，
表示两国将继续深化在能源领域的合作）。

配合着俄罗斯的动作，中国也干脆利索的出手了：强调“应该启动黎以、叙以两线和谈”（做牌）。应该说，整天撸着袖子想和以色列下手的有主要有三家，依
次是：哈马斯、真主党、叙利亚。而这三家之间有着千丝万缕的联系：真主党是哈马斯的支持者，叙利亚（也包括伊朗）是真主党的支持者。既然巴以和谈迟
迟谈不出个三六九来，开个黎以、叙以和谈有何不可？而且，北京的支持可不是耍嘴皮子，何况孙特使有言在先：“支持叙利亚收回戈兰高地的正当要求”。这
个态可不是白表的，它意味着北京站在了叙利亚的背后，愿意充当叙利亚的保护人。整天担心被美国人用推土机把地盘给推平了的阿萨德（叙利亚总统）可以
松口气了（现阶段美国最想也最有可能武力打击对象就是叙利亚，而不是整天对着发狠话的伊朗），叙利亚的国家安全也得到了双保险（另一个保护人是俄罗
斯）。

有了叙利亚对北京的的支持，不愁亲美的黎巴嫩政府不给面子，因为它还要提防着硬了腰杆子的真主党来“夺权”---那时如果真主党要夺权的话，一可借民意
，二可靠武力，三又有大靠山（中国在黎巴嫩与叙利亚的边界处有“维和部队”，可充分保障来自叙利亚的战略物资可以源源不断的运到真主党手里，而不被黎
巴嫩政府军卡死运输通道）。更有意思的是，北京可以通过叙利亚、真主党和哈马斯之间的联系来支持在巴以和谈中至今没拿到主导权的俄罗斯（递牌）。

当然了，如果黎以、叙以两线和谈谈出了好结果，尝到了甜头的阿拉伯人肯定会对北京投怀送抱，那时的巴以和谈就被北京抽成了空架子，美国人主导中东和
平进程的日子也就结束了。所以，美国人是绝对反对启动叙以、黎以和谈，因为那绝对不符合“美国的利益”。那以色列会不会也跟着美国人反对呢？恐怕它该
惦量一下了：有了北京的支持，叙利亚肯定有胆量主动找以色列的茬子。那时的以色列还敢强硬的对付叙利亚吗？

也许，哈马斯就是一面镜子。按照美以的一贯做法，对哈马斯是不讲客气的。只不过有了中国（也包括俄罗斯）深层次的介入，伊斯兰世界也变得越来越强硬
了，25日埃及否认以色列对其阻止走私武器不力的指责就是个明显的例子。这充分说明，某些人在给哈马斯提供武器支持时的胆子是越来越大了，就算是美国
人很不高兴也没用（美国国会决定暂停对埃及一亿美元的年度军事援助）。

胡总的这次出手，完全是摆出一副拆掉美国主导的中东和平进程的架式（当然也是对俄罗斯的支持）。这一幕给人的感觉是似曾相识，今年年初，胡总就在越
南狂拆美国主导的APEC骨架时露过非常相似的一手。不同的是，美国通过控制APEC维持自己世界经济的主导地位，通过控制中东和平进程维持自己世界政治的
主导地位。胡总的在一年内连续两次出手，哪里还有韬光养晦的影子？分明是大有作为！

当然，中国全面切入中东和平进程还有相当长的路要走，中国的介入必将遭到美国强烈的反扑，这是必然的。不过，手握伊核、朝核主导权的中国有理由期待
一个好的结果会出现。非常赶巧的是，在美国非常希望与伊朗、朝鲜适当改善一下关系的同时，在这两个国家却传出了让布什团队最不愿意听到的消息：

23日，伊朗议会国家安全和外交政策委员会发言人贾拉利称：“伊朗将很快发布国际招标书，以便建设19个核电站，每个核电站的发电量为1000MW。这些计划
是与伊朗议会一项生产20000MW电力以满足伊朗需求的议案相对应的。”

25日，朝鲜《劳动新闻》发表评论，指责美国强硬派和军方好战势力无视当前的形势发展，鼓吹军事对峙，搅乱六方会谈。26日，朝鲜劳动党机关报《劳动新
闻》就日本17日在美国夏威夷海域实施弹道导弹拦截试验一事发表评论文章，谴责称“此举十分鲁莽，将加大东北亚地区的战争威胁”。27日，朝鲜指责国际社
会在推迟已承诺的对朝能源援助，并暗示有可能放缓核去功能化的速度。

【金鸿评论】看来，伊朗和朝鲜都不是省油的灯，一个是蹬着鼻子上脸（伊朗），一个是趁火打劫（朝鲜）。接下来该如何摆平它们？恐怕只有求助于北京了
。估计北京会说：“好办，只要巴以和谈那边……”


** 【奋进社/金鸿95】短评：布托之死


   27日下午，巴基斯坦人民党在拉瓦尔品第的一个公园举行上千人集会，贝·布托到场发表讲话,呼吁支持者在明年1月8日议会选举中投票给人民党。集会结
束后，当地时间下午5点30分，贝·布托乘车准备离开。据目击者称，就在此时，有两名枪手分别从不同方向突然接近贝·布托乘坐的汽车并对她开枪射击，二
人随后引爆了绑在身上的自杀性炸弹。

    贝·布托颈部中一颗弹，头部中两颗子弹，其中颈部的一枪是致命性的。也有报道说，是其后的自杀性爆炸最终夺去了贝·布托的生命。事件发生后，贝·
布托立即被送往当地医院。巴基斯坦人民党已证实，贝·布托于当地时间下午6点16分在拉瓦尔品第总医院去世。也有报道说，贝·布托到达医院时就已停止呼
吸。这名巴基斯坦人民党领袖享年54岁。

    【金鸿评论】这绝对不是一起简单的恐怖袭击事件：朝布托射击的冲锋枪口几乎顶到了她的身上，很显然，布托的保安工作有明显的漏洞。自贝·布托回
国后，针对她的刺杀和爆炸事件就接连不断，难道负责她安全的人员就不知道？

    究竟谁是杀死布托的主谋？第一时间，基地组织出来认帐了。不过，事情真的这么简单吗？我们不妨这么看：谁是幕后主使，在制造了这起事件之后，谁
的敌人的损害将是最大的。就目前来看，最大的受害者却是穆沙拉夫。而穆沙拉夫刚刚搞完一场让美国人差点赔光老本的“紧急状态”。

    所以，与其说这是一起恐怖刺杀阴谋，不如说是一起伺机搅乱巴基斯坦政局的政治阴谋。而谢里夫可以乘机兴风作浪，他在贝·布托去世后立即宣布抵制
大选。

    布托无疑是个是牺牲品。贝·布托遇刺的消息传出之后，人民党支持者在伊斯兰堡、拉瓦尔品第、卡拉奇、白沙瓦和奎达等主要城市上街抗议，并制造了
一些骚乱事件。现在的巴基斯坦，走到了国内大乱的边缘。可怜的巴基斯坦！

    现在的巴国内局势，对穆沙拉夫而言，是一个极大的考验。如果处理不好，巴国可能天下大乱；如果处理的好，则可以让自己的统治更加稳固，因为如果
布托活着并当选总理，肯定会分他的权。而现在的巴国内，已无人能对穆沙拉夫形成挑战。

    这起事件，已不仅仅是影响着巴基斯坦国内的政局，还影响着全球局势的发展。正如我在今天刚刚写完的上一篇评论《曙光》中提到的观点： “中国全面
切入中东和平进程还有相当长的路要走，中国的介入必将遭到美国强烈的反扑，这是必然的。 ”没想到这么快就看到了一个结果。

    美国希望切断我们的巴基斯坦通道，就算不能切断，也要让它变得不那么通畅（制造巴基斯坦乱局），以减小自己在巴以和谈上的压力。 只不过，这一
手太黑了。毕竟，布托也算是个亲美派。如此的对亲近自己的人下死手，岂不让天下人寒心？即使暂时摆脱了困境，也必将在众叛亲离中走上绝路。

    既然“恐怖主义”对着我们的巴基斯坦兄弟下手了，北京绝对不会坐视不理，也许，很快就会从巴基斯坦国内传出新的布什先生也心惊肉跳的消息来。我们
拭目以待好了。


** 
   27日下午，巴基斯坦人民党在拉瓦尔品第的一个公园举行上千人集会，贝·布托到场发表讲话,呼吁支持者在明年1月8日议会选举中投票给人民党。集会结
束后，当地时间下午5点30分，贝·布托乘车准备离开。据目击者称，就在此时，有两名枪手分别从不同方向突然接近贝·布托乘坐的汽车并对她开枪射击，二
人随后引爆了绑在身上的自杀性炸弹。

    贝·布托颈部中一颗弹，头部中两颗子弹，其中颈部的一枪是致命性的。也有报道说，是其后的自杀性爆炸最终夺去了贝·布托的生命。事件发生后，贝·
布托立即被送往当地医院。巴基斯坦人民党已证实，贝·布托于当地时间下午6点16分在拉瓦尔品第总医院去世。也有报道说，贝·布托到达医院时就已停止呼
吸。这名巴基斯坦人民党领袖享年54岁。

    【金鸿评论】这绝对不是一起简单的恐怖袭击事件：朝布托射击的冲锋枪口几乎顶到了她的身上，很显然，布托的保安工作有明显的漏洞。自贝·布托回
国后，针对她的刺杀和爆炸事件就接连不断，难道负责她安全的人员就不知道？

    究竟谁是杀死布托的主谋？第一时间，基地组织出来认帐了。不过，事情真的这么简单吗？我们不妨这么看：谁是幕后主使，在制造了这起事件之后，谁
的敌人的损害将是最大的。就目前来看，最大的受害者却是穆沙拉夫。而穆沙拉夫刚刚搞完一场让美国人差点赔光老本的“紧急状态”。

    所以，与其说这是一起恐怖刺杀阴谋，不如说是一起伺机搅乱巴基斯坦政局的政治阴谋。而谢里夫可以乘机兴风作浪，他在贝·布托去世后立即宣布抵制
大选。

    布托无疑是个是牺牲品。贝·布托遇刺的消息传出之后，人民党支持者在伊斯兰堡、拉瓦尔品第、卡拉奇、白沙瓦和奎达等主要城市上街抗议，并制造了
一些骚乱事件。现在的巴基斯坦，走到了国内大乱的边缘。可怜的巴基斯坦！

    现在的巴国内局势，对穆沙拉夫而言，是一个极大的考验。如果处理不好，巴国可能天下大乱；如果处理的好，则可以让自己的统治更加稳固，因为如果
布托活着并当选总理，肯定会分他的权。而现在的巴国内，已无人能对穆沙拉夫形成挑战。

    这起事件，已不仅仅是影响着巴基斯坦国内的政局，还影响着全球局势的发展。正如我在今天刚刚写完的上一篇评论《曙光》中提到的观点： “中国全面
切入中东和平进程还有相当长的路要走，中国的介入必将遭到美国强烈的反扑，这是必然的。 ”没想到这么快就看到了一个结果。

    美国希望切断我们的巴基斯坦通道，就算不能切断，也要让它变得不那么通畅（制造巴基斯坦乱局），以减小自己在巴以和谈上的压力。 只不过，这一
手太黑了。毕竟，布托也算是个亲美派。如此的对亲近自己的人下死手，岂不让天下人寒心？即使暂时摆脱了困境，也必将在众叛亲离中走上绝路。

    既然“恐怖主义”对着我们的巴基斯坦兄弟下手了，北京绝对不会坐视不理，也许，很快就会从巴基斯坦国内传出新的布什先生也心惊肉跳的消息来。我们
拭目以待好了。


** 【奋进社/金鸿95】布托之死 (二)

[2007-12-30 19:38:43]


美国有线电视新闻网（CNN）著名主持人沃尔夫&S226;布利策27日晚公布了巴基斯坦前总理娜齐尔布托生前写给他的一封邮件。贝布托在邮件中批评巴官司方
对她保卫不够严密。布利策说，给他这封邮件时，贝布托要求，除非她遇袭死亡，否则不得公开邮件内容。

【金鸿评论】这个料曝的真及时。只是有一点让人不明白，象这种对她“保卫不利”的牢骚为什么不是由她所在的人民党的成员捅出来，而是由一个远在天边的
美国人讲出来？可惜的是，布托死了，死无对证。在科技如此发达的今天，如果有人想造一封假的电子邮件，真不是一件难事。就连五角大楼的计算机系统不
也经常被黑客入侵吗？当然，这只是猜测，究竟是真是假，我们也不得而知。

不过，有一点我们是可以想象得到的，那就是，布托的忠实支持者会把满腔的怒火发泄到没有满足“布托的”要求而造成布托遇刺身亡穆沙拉夫身上。巴基斯坦
天下大乱甚至被分裂的局面不是不可能出现。

布什团队在巴基斯坦通道上真是下了血本，大有一副不达目的誓不罢休的态度。巧的很，布利策话音未落，从中国方面也传出了声音。

暨南大学教授庄礼伟发表了一篇名为《贝布托的政治遗产》的文章（庄教授的身份是暨南大学东南亚研究所副所长，博士生导师），里面有这么两段话：

……可以说，刺杀贝布托的人，一定是不能从巴基斯的和解、安定之路中获利的人，而是试图从巴基斯坦的混乱、分裂中获利的人，它们出于其自私、残暴的个
性杀害了贝 布托，就是希望把水搅浑，刺激各政党之间的恶斗，使国家政治生活迟迟不能正常化，这样他们就可以趁火打劫、趁机坐大。

巴基斯坦是一个充满悲情的国家，贫弱、破碎，但它同时又是世界上唯一拥有核武器的穆斯林国家，如果它乱到极点，就不仅会伤已，也会伤人。……

【金鸿评论】（最大可能的）切断巴基斯坦通道，降低中国在中东的影响力和控制力，是美国摆脱中东被动局面的关键步骤。因此，几年来，美国在巴基斯坦
的犯罪行为从来就没有停止过。巴基斯坦国内从未停止的“恐怖袭击”的真正幕后主使是谁，大家心里都清楚。

庄教授上面的第一段话非常清楚的概括出了美国和巴基斯坦国内某些势力的真实动机。从CNN名嘴一刻都不耽误的曝料就可以看出，美国人火上浇油的动作是
多么及时，搞乱巴基斯坦的目标是多么的明确！

当然了，有志于在中东大显伸手的北京绝对不会、也不可能让美国人的行动得逞。在此，不妨把我28日评论中的一个观点再拿出来看一下：“既然恐怖主义对
着我们的巴基斯坦兄弟下手了，北京绝对不会坐视不理，也许，很快就会从巴基斯坦国内传出新的布什先生也心惊肉跳的消息来。我们拭目以待好了。”

北京的做法果然和我开始想的差不多：

---- “如果它乱到极点，就不仅会伤已，也会伤人。”“伤人”伤的是谁？当然是已经搬起了石头华盛顿。又是如何伤的？当然是“核武器”。除了“核武器”，也
没有别的东西能让布什先生真正心惊肉跳的了。

布什先生可要注意了，如果巴基斯坦真的这样乱下去，巴基斯坦的核武器说不定哪天就会丢上一件两件的。当然了，肯定是“恐怖分子”偷去的。据说“恐怖分
子”们一直认为原子弹爆炸时的声音不如中国的爆竹响，所以他们打算弄一个引爆了听听是不是真的。至于引爆地点嘛，听说许多恐怖分子看好纽约。

如果布什先生不希望听到那些可能让他彻夜难眠的、心惊肉跳的“坏消息”，那就“解铃还需系铃人”。巴基斯坦乱局，拜托布什先生劝劝谢里夫，不要抵制大选
了-----都一把年纪了，还闹腾什么呀？回家抱孙子不好吗？也劝劝那些天天在巴基斯坦境内搞爆炸的“恐怖分子”，放下屠刀，过安生日子去吧。听说那些恐
怖分子大都信耶酥，而不是穆斯林。

还有一点要说明：北京这一次的反击直接选在了巴基斯坦，而不是从伊核、朝核或者日本等其他方向上。很显然，这是一次硬碰硬的对抗。也是北京更自信的
一个表现（做出这个决定的人，八成是老大）。这也是明确的回应华盛顿：“想操练操练？地方随便你挑！”这也是北京为了尽可能的减少与华盛顿的纠缠，达
到自己的目的。因为闹完了巴基斯坦之后，华盛顿十有八九会在别的什么地方再放一把大火来打乱北京的“工作进度”。至于北京的目的，非常简单，就是：“
中东和平进程（并非一定是巴以和谈，也许是叙以、黎以和谈）的庄，老子坐定了！”

斗到这一步，结果基本出来了，穆仁兄的政权绝对没问题，让步的肯定是小布什。国际斗争中有一条真理，那就是：光脚的不怕穿鞋的。欧美的大资本家都是
穿鞋的，他们的瓶瓶缺罐罐太多（不然怎么说人家有钱呢），不过，打了哪一个他们都会心疼死。所以，玩命的时候他们就不敢上了，虽然平时他们够狠、够
黑。我们呢，是光脚的，穷是穷了点，但我们敢折腾、关键时刻敢上，大不了全打了烂了再重建！他们能下这个决心吗？所以，我们不会输。借用毛主席的一
句话说就是：帝国主义都是纸老虎。


** 【奋进社/金鸿95】布托之死 （三）

[2007-12-31 14:24:28]


昨天写评论是看着晚报上的新闻写的，没看到中间还发生了几条新闻。再结合刚刚看到的新闻，发一篇：

1、美国白宫发言人施坦策尔28日说，美国对巴基斯坦核武器的状况很放心，并认为在巴前总理贝·布托遇刺后，巴核武器并没有落入极端分子手中的危险。

2、巴基斯坦内政部28日召开新闻发布会，介绍了贝-布托遇刺案调查结果。内政部发言人同时警告，巴基斯坦另一位反对党领导人纳瓦兹·谢里夫目前也面临
暗杀危险。

3、巴基斯坦总统穆沙拉夫29日下令执法部门依法严惩挑起骚乱的暴徒，以恢复社会秩序。

【金鸿评论】中国刚刚暗示过巴基斯坦的核武库有可能失控，布什就出来表态了：不怕！不能不佩服的说一句：有种！不过，还想顺便问一句：真不怕吗？

既然布什敢赌，裤子都脱下来压在了赌桌上，那就给他个裸奔的机会！

既然美国人不怕天下大乱，铁了心要把巴基斯坦搞乱，有强硬的北京撑腰，穆沙拉夫自然毫不客气：谢里夫的人身安全也有问题！

至少从表面上看，这是非常符合逻辑的：既然亲美的布托都被恐怖分子干掉了，而且是在保安不利的情况下刺杀的；那么，同样亲美的谢里夫也是恐怖分子的
眼中钉，出现刺杀谢里夫的行动也是很正常的事情，再加上谢里夫被穆沙拉夫视为肉中刺，对他保安不利就更正常了，所以，谢里夫的人身安全更没有保障。
可以预料的是，如果美国继续挑动巴国的内乱，出现对谢里夫放冷枪的事情是必然的，第一次肯定要不了谢里夫的命，如果还有第二次，那谢里夫的小命基本
就不保了。至于能出现几次对谢里夫的刺杀行动，就看布什的表现了。不过，这样一来又出现了一个问题：处于双方力量严重挤压之下的谢里夫，会不会重新
选边站？这也是一大看点。

布什为了自己的国家利益，不惜把自己的盟国（至少在公开场合，美国称巴基斯坦为盟友）搞乱，甚至搞分裂。这样的做法是对巴基斯坦国家利益的最大侵犯
。只要是巴国的利益集团，只要不是亲美的傀儡，那不会容忍这样的行为。以穆沙拉夫为代表的维护巴国正常权利的政治势力奋进反抗是必然的。

所以，穆沙拉夫对谢里夫的警告不是冲着谢里夫来的，而是冲着布什来的。这是最直白的警告：如果美国人再继续对巴国的混乱局面煽风点火，那么，在巴基
斯坦被分裂之前，巴国内的亲美派将被全部剿杀！应该说，穆沙拉夫也是真急了：先拉个垫背的再说！

还有一点需要说明，就是布托的死因：巴政府方面说，贝布托遇袭时头部撞到汽车天窗的控制杆，受伤后不治身亡。人民党官员则说，贝布托中枪而亡。其实
，这是穆沙拉夫精心准备的一个测试点。布托刚刚死亡时，媒体的报道全是枪击，现在却变成了“撞头”。其实，人已经死了，对大国斗争而言，怎么死的都是
一样，反正是因被袭而亡。穆沙拉夫这样做的目的，就是为了测试一下美国的反应-----是继续找茬还是就此打住。如果美国希望借着巴基斯坦大乱继续煸阴
风，布托的死因就是个不错的把柄，而这个把柄是穆沙拉夫主动送出来的。现在就看美国人有没有胆量接过来了。当然了，穆沙拉夫敢这么做，本身就说明了
他的自信。

做完了这些准备工作之后，穆沙拉夫对内开始了铁腕政策，“严惩挑起骚乱的暴徒，以恢复社会秩序。”

巴基斯坦通道的安危，是关中国的全球战略利益，是中国撬动全球利益的支点：无论是伊核控制权，还是分享伊拉克重建利益，还是介入中东和平进程，还是
中国的非洲战略，还是中国的南美战略，甚至包括朝核（包括日本）、台海、中亚战略，都离不开巴基斯坦这个战略支点。所以说，中国承受不起巴基斯坦通
道的失败。

布什直接对着中国的巴基斯坦通道下死手是对中国核心利益的最大挑衅，这比支持台独要严重的多！做为交换，中国的作法就是：废掉日本，或者日本全面倒
向中国，倒向当然包括中国代替美国在日本驻军。因为日本是美国全球战略的最大支点。既使这样，中国仍然会亏。作为第二补偿，在巴国解体之前，巴国内
的亲美派必将遭到全面剿杀，同时，巴国核武库里的原子弹还会丢失三五枚（原因很简单，巴国大乱，控制不利）。至于这些原子弹何时会在美国的哪个大城
市爆炸，就看伊朗和叙利亚的国家安全情况了。如果这两个国家遭到了打击甚至核攻击，那么，喜欢用人弹进攻的伊斯兰极端势力在美国引爆几颗原子弹也是
情理之中的事。反正大家都知道，伊斯兰极端势力对巴基斯坦渗透非常严重，说不定这些家伙就有关系不错的哥们负责管理原子弹，在巴国大乱的浑水里摸走
几条小鱼不是很正常的事吗？

对于巴基斯坦通道争夺的后果，所有的大国心里都有一本帐。美国的狠辣出手没有吓坏穆沙拉夫，也没有吓坏北京，倒是吓坏了福田康夫。福田康夫在中国的
表现大家都看到了，什么承诺“四不”，什么“中日除了友好别无选择”，日本国内媒体也跟着附合：“台海有战事，日本不参与、日美安全保障条约正处于崩溃
的边缘”。日本人的表现，如果用四个字来概括，那就是：乖到家了！出现这样的结果，全拜布什所赐，不然北京怎么会说“超过预期”呢。

还有一点需要强调，现在是各大国摊牌的关键时期，要加强对国家领导人的保安工作(狗急了跳墙,这些畜生什么事都干的出来)。这是绝对必需的，中国民族
腾飞的希望就寄托在他们身上。胡总和温总是我们中国人的脊梁，他们是我们这个国家最可宝贵的财富。对他们的安危，不能有丝毫的疏忽大意！

现在的局势，不知道大家怎么看，至少在我个人眼里，比台海爆发战事要严重的多。如果巴基斯坦通道被封死了，中国的战略空间将被极大的压缩。这场较量
我们输不起。所以，我们别无选择。没办法，拉开架式，准备拼命！

当然，我们做好了玩命的准备之后，八成就打不起来了。这个世界就是这么邪性。现在，巴基斯坦局势的最新消息出来了：

4、巴基斯坦人民党和穆斯林联盟（谢里夫派）３０日宣布参加定于明年１月８日举行的议会选举。

5、美国白宫发言人托尼·弗拉托２９日说，在巴基斯坦前总理贝娜齐尔·布托遇刺身亡后，是否变更议会选举日期的决定应由巴官方作出，美国只要求选举公
正、自由。同日，巴方表示，贝·布托遇刺的调查工作不需要外国协助。

【金鸿评论】谢里夫也居然不抵制大选了，美国人也不掺合了。看来，局面是真的要缓和了。那些大爷不玩了?没劲！


** 【奋进社/金鸿95】布托之死 （四）


1、据巴基斯坦拉瓦尔品地总医院1日透露，巴基斯坦政府对该医院曾参与抢救巴基斯坦前总理贝  布托的所有人员施加巨大压力，要他们不得透露任何关于布
托死前数小时的消息。布托的同僚当天还透露，布托被刺杀当天曾计划通过掌握的“铁证”揭露巴基斯坦情报门欲操纵原定1月举行的大选的“阴谋”。

2、伦敦警察局外交保护小组工作人员1日表示，将在做出评估并与巴基斯坦人民党的领导人商议后决定到底怎样保护贝  布托的儿子----19岁的比拉瓦尔  所
尔达里。

3、巴基斯坦决统穆沙拉夫的发言人奎雷西表示，穆沙拉夫正在考虑接受英国政府协助调查的申请。奎雷西尔，布托的丈夫应当为他妻子死亡的真正原因所引
起的争论负责，因为他拒绝在布托死后立即进行验尸。

从白宫表示“美国只要求巴基斯坦议会选举公正、自由”、谢里夫派宣布参加议会选举开始，围绕巴基斯坦通道的争夺开始了新的玩法。那就是，（美英）以谢
里夫为主，努力在议会选举中从穆沙拉夫手里分得权利。

今天曝出的新闻，就是最好的证明。如果巴政府施加的压力真的很“巨大”的话，恐怕那些医生们就不敢张嘴了。布托手里的操纵大选的“铁证”，就更让人感觉
奇怪了。如果布托能从巴情报系统搞出这么关键的东西来，那说明她神通广大；但是，她为什么就没有搞到有人要行刺她的情报呢？这个情况不比那个所谓的
“铁证”更重要？反正这年头，弄“证据”最容易，当然了，有可能是找出来了，也有可能是造出来的。

当然了，既然穆沙拉夫如此的喜欢玩弄政治手腕、如此的没诚信，那么，在接下来的大选中，巴国人应该绝对不能投票给穆沙拉夫的人。这大概是此次曝料的
一个目的吧。

只不过，这个算盘打的忒精明了点。于是，马上遭到了穆沙拉夫的反击：

穆沙拉夫考虑接受接受英国政府协助调查的申请的动作，是一个非常精巧的政治手腕----穆沙拉夫用“贝布托遇袭时头部撞到汽车天窗的控制杆后不治而亡而
非中枪而亡”做成了一个测试点，测试一下美国的反应，是继续给巴国大乱煽风打火还是就此打住；同时也震住布托的丈夫（因为他有腐败案在身）。结果非
常理想，白宫马上宣布，不再掺合巴国大选。而布托的丈夫因为有把柄攥在别人的手里，所以“拒绝了在布托死后立即进行验尸”(需要注意的是,调查的内容有
两个方面，布托是否是被枪击而死、布托被谁杀死)。

现在伦敦警方跳出来要保护布托的儿子所尔达里。很显然，局势有变。伦敦保护是假，挟持人质是真。当然，布托家族可以拒绝伦敦的好意。那时，八成马上
就会有人对所尔达里打冷枪。这时，伦敦警方就可以跳出来说话了：看，我们想保护他是对的吧？但是，如果接受了伦敦方面的保护，那就意味着，人民党要
在大选中力挺谢里夫（布托被杀，意味着巴国的人民党被美英抛弃了）。

现在，穆沙拉夫的回应来了，放风要允许英国人协助调查布托的死因。如果英国人掺合进来，局面就又变了。我们可以设想一种情况：如果穆沙拉夫和英国人
达不成妥协，恼羞成怒的英国人把布托的真正死因（中枪而亡）捅了出来，那时会如何？穆沙拉夫脸上无光是肯定的，但是他可以把责任推到得出“布托遇袭
时头部撞到汽车天窗的控制杆后不治而亡”结论的下属身上，从而可以为自己开脱掉责任（大不了公开道个歉）。那布托的丈夫呢？如何为自己开脱？布托家
族的尊严何在？人民党的声誉何在？那时，人民党可就全赔光了，布托家族也就完了，因为布托一死，这个家族中再也有没有有胆有识的人了。

所以，无论是对于布托的丈夫而言，还是对人民党而言，英国人的介国绝对是致命的威胁。那么，如何才能避免这一状况的出现？穆沙拉夫的条件是明摆着的
：绝对不准支持谢里夫。

只要满足了穆沙拉夫的条件，打发掉英国人不是件困难事。无论是出现枪击谢里夫的“带点血腥味的恐怖事件”，还是在阿富汗出现针对驻阿英军的“更血腥的
恐怖袭击”，都可以看作是告诉英国人做事要“悠着点的”警告。

这篇文章是2日写的，一直没得空闲发出。这几天又发生了不少事，基本上是围绕着上面的局势斗争的延续。我简单把新闻罗列一下：

4、巴基斯坦内政部长1日称，他们就此前错误公布贝-布托的死因表示道歉。贝-布托遭到暗杀后不久，巴内政部发言人曾公开表示贝-布托是在躲避袭击时头
部撞击汽车天窗而死亡的（对人民党方面威胁有效，之后穆沙拉夫通过在布托死因上道歉展示柔和的一面）。

5、巴基斯坦一位激进的神职人员1日晚向贝·布托之子比拉瓦尔发出了警告，这位神职人员坚持称：“比拉瓦尔现在已成为袭击目标（结合下面第十条新闻看）
。

6、中新网1月2日电  巴基斯坦选举委员会刚刚宣布，原定1月8日举行的议会选举将推迟到2月18日举行（结合上面第四条看，对人民党示好后再次展现自己强
势的一面，“在巴基斯坦我说了算！”）。

7、巴媒体援引来自贝·布托所属人民党的最新消息称，贝·布托的伤口不是由子弹造成的，而是来自某种精密的激光武器（替巴内政部的“失误”找台阶，同时
引发竞猜：“激光枪是从哪个国家弄出来的？”）。

8、代表欧盟访问巴基斯坦的法国外长贝尔纳·库什内2日会晤穆沙拉夫时表示，法国愿意“贡献专家团队”，协助调查。库什内在这一事件上的措辞颇为谨慎。
他说，法国方面支持巴基斯坦、尤其是总统穆沙拉夫在反恐领域的努力；如果巴方需要，法国愿意提供帮助，不过，只是贡献技术专才，无意展开国际调查（
法国人真够娘们的，忸忸捏捏,装模作样）。

9、面对选举推迟，巴基斯坦人民党领导人、贝·布托的丈夫扎尔达里说，人民党将参加推迟后的选举。不久后，另一重要反对党穆斯林联盟（谢里夫派）也表
示不会抵制选举。“我们不会把战场白白留给（穆斯林联盟领袖派），”穆斯林联盟（谢里夫派）一名发言人说(老穆成功分裂人民党与谢里夫派并全面主导大
选局势)。

10、3日，巴方宣布将邀请英国伦敦警察局协助调查贝·布托遇刺案。英国方面已答应这一请求，并将于本周末前派出反恐专家小组前往巴基斯坦协助调查，缉
拿真凶。与此同时，巴人民党拒绝英国协助调查此案，要求联合国参与调查，但美国则表示联合国没有必要介入（联合国？也希望中国淌这趟浑水？）。

当然，因为巴基斯坦局势的变化，在东亚方向、中东方向和非洲方向都顺势展开了一系列的变化：最有意思的是朝鲜，一会儿要求美国签定停战协议以激化美
日矛盾，一会儿通过“打着抵抗华盛顿准备向自己发动攻击的幌子声称自己将加强军力和提高作战实力”来向美国表明东亚局势美国左右不了，同时呢，还耐着
心的在弃核问题上陪着美国玩一把（因为有美元赚）。而中东方向的局势也很微妙，如果不相信，看看五天来以列色、法塔赫、哈马斯和美国的表现就知道了
。如果再加上德国在阿富汗的表现（德国国防部一位发言人2日在柏林说，尽管目前巴基斯坦局势动荡，但德军不会增兵阿富汗）、以及沙特的表现（沙特王
储希望进一步加强沙中战略合作关系），那就更说明问题了。


** 【奋进社/金鸿95】中国的全球战略


    写中国的全球战略，不得不从美国写起。因为美国是中国最大的敌人，而中国也是对美国霸权威胁最大的国家。

中国的全球战略目标，自然是打倒美国的霸权。问题是，我们该怎样做，才能达到这个目标呢？要打倒美国的霸权，首先必须明白，美国霸权的命门在哪里。

美国霸权的命门，就是美国的金融霸权，美国的超强军力是为美国的金融霸权服务的。美国的金融霸权，第一表现就是美元是世界通用货币，第二表现就是美
国掌握着全世界大宗商品的定价权。

美元之所以牢固的占据着世界通用货币的位置，是因为美元跟石油捆绑在一起。说到美元与石油的捆绑，不得不提巴以和谈。美国是通过控制巴以和谈来保证
美元与石油捆绑在一起的：

美国通过以色列时刻威胁着中东产油国家的安全，而美国对以色列的支持是全天候的。因为没有一支全面抗衡美国人的力量在中东，所以，受着威胁的阿拉伯
国家不得不也倒向美国，以求在美国的庇护下获得国家安全上的保证。当然，美国人是收保护费的。美国人要的保护费就是阿拉伯国家的石油用美元结算，然
后阿拉伯国家必须把通过出口石油挣得的美元重新投资（和花费）到美国。这样一看，阿拉伯国家完全是美国的“奶牛”。同时，美国利用伊斯兰逊尼派与叶什
派的矛盾，通过拉拢阿拉伯国家来围剿叶什派国家，实现自己独霸中东的梦想。

美国就是这样把美元和石油死死的捆在一起的。石油作为最重要的战略资源是任何一个国家都须臾不可离的。借着石油这种战略资源，美元成了全球通行的货
币，世界各国也主要以美元为储备外汇进行国际结算。美国因此而获得的好处是无法估量的：首先就是美国人通过过多发行美元造成美元贬值（全球性的通货
膨胀）以引发世界财富的重新分配----直接表现就是各国储备的美元价值“缩水”了，这也相当于美国向全世界人民征了税。另一个重要好处就是美国通过操纵
石油价值来达到掏空某些国家经济、保卫自己世界第一强权位置的作用。在这一点上最经典的案例有两个：一个是1973年放手让美元疯长400%，狠剪了一把发
展中国家的羊毛，二个是压低油价、残酷打击苏联经济最后导致苏联解体。

所以，美国要想继续始终保持自己的世界第一强权的位置，必须牢牢的控制住中东，把石油和美元死死的锁在一起。而想到打倒美国霸权的唯一办法，也是把
石油和美元分割开。要想让石油输出国家改变用石油结算的现状，就必须为他们提供安全保护。现在的中东在美国人的保护之下，这些国家不用美元结算行吗
？现在伊朗的石油已经改用欧元了，就是因为中俄为伊朗的国家安全提供了保护；而当年小布什之所以下决心推翻萨达姆政权，也是因为萨达姆想把出口的石
油改为欧元结算而又没有国家能保护的了他。

现在，不光伊朗，叙利亚也处在了中俄的保护之下了：2007年12月26日，中国中东问题特使孙必干与叙利亚外长穆阿利姆会晤时，孙必干宣称，中方支持叙利
亚收回戈兰高地的正当要求，希望早日重开叙以和谈。这就是中国最明显的态度。支持叙利亚收回戈兰高地就意味着中国愿意卷入叙以纠纷、得罪以色列和美
国，保护叙利亚的国家安全。只要中俄在中东的军事影响力越来越大，愿意接受中俄保护的国家将不仅仅是逊尼派国家，阿拉伯国家也会产生这样的“想法”。

当然，有“想法”是一码事，付诸行动是另一码事。如何能让阿拉伯世界把“想法”变成行动呢？办法只有一个，就是让他们看到跟着中国（也包括俄罗斯）能得
到好处。如果叙利亚能在中俄的支持下，顺利的重开叙以和谈并得到相应的好处（类似的，中俄正在做准备工作的还有黎以和谈），因为在巴以和谈上迟迟看
不到欧盟为他们争得正当权益，产生另攀高枝的冲动将是不可避免的。

其实，一开始，中国俄罗斯是寄希望于在巴以和谈中从美国手中分权的，只不过，美国选择了宁可对欧盟让步，决不对中俄松口的做法。等得不耐烦的中俄只
好自己准备谈判桌了。也好，中俄比美国要大方，一开就是两桌：叙以、黎以和谈。谁敢说只有欧洲人关心中东和平？——美国在中东花大力气搞的是“中东民
主”，欧盟向中东国家推销的才是是“中东和平”。接下来，不管是通过新开的两桌谈判替叙利亚、黎巴嫩捞得好处，还是迫于中俄在场外的压力而威逼以色列
对巴勒斯坦让步，都会被阿拉伯国家及时的捕捉到，并增加向中俄靠拢的决心。

只要中东产油国家一个个的站到了中俄这边，中俄就可以有步骤、有次序的让这些国家与美国慢慢的脱钩。当然，中东国家石油不用美元结算了，会先改成欧
元，这也是欧盟求之不得的，也是欧盟一直在努力做到的一点。这样还可以激化美欧之间的矛盾。面对着直打自己七寸的欧盟，美国人一定会全力反击。另外
，因为中国持有巨额的外汇储备，可以时不时的拿着这笔巨资是多一点美元还是多一点欧元做文章，在美欧中间灵活的跳一下摇摆舞——只要中国动作一大，同
样拿着大把美元储备的日韩印等国家肯定跟着做动作。这样可以从经济金融层面给中国也不时的捞一点油水出来。而俄罗斯也可以趁乱做一下出口石油用卢布
结算的工作，跟着拆一下美元的墙角。

只要这样努力下去，把美元与石油彻底拆分了家，美国人耀武扬威的日子的就结束了。当然，打倒美国霸权是一个系统的工程，不是仅平几条妙计就可以做到
的。

我们必须在以下六个方面做好扎实的工作：

1、科技上赶超。只要美国是世界上科学技术最先进的国家，它就永远是世界的领袖国家。要想把它赶下领袖的座位，科学技术方面必须赶超它。以我们中国
人的创新能力，只要坚持独立研发，二十年内全面赶超是可以实现的。

2、政治上顶住。在国际斗争中，必须坚决顶住美国的压力，保护所有朋友的利益，寻找一切机会打击美国，包括愿意充当其走狗的国家。在联合国，无论是
中国俄罗斯，还是法国，该动否决票时坚持不要客气。

3、军事上压住。狗急了跳墙。把美国逼急了，它肯定会找机会发动战争以扭转局面。所以，要坚决打击美国的一切军事冒险意图。只要美国敢动手，必须坚
决回击。只有充分的准备战争，才能防止战争的发生。

4、经济上拆散。充分联合一切可以联合的力量，拆散美国的经济势力范围。APEC必须拆掉，把日本、韩国和东盟拉离美国的势力范围。在美国的后院也要狠
挖墙角。在非洲，更要想办法把美国人顶出去，因为非洲有资源和廉价的劳动力。不要以为美国的那些大企业有多么多么强的竞争力，只要把美国的经济势力
范围掏空了，美国的那些巨无霸级的企业会统统破产。一句话，把美国商人赶回美国本土去！只要美国的企业不行了，美国的军事、科技、金融就基本歇菜了
。

5、金融上掏空。用石油欧元在中东排挤石油美元，人民币、卢布、日元居中策应。

6、实力上消耗。利用伊拉克和阿富汗两个战场全力消耗美国的有生力量。美国一时半会下不了撤出阿富汗的决心，因为美国一撤，上合就在伊朗、巴基斯坦
、阿富汗连为一片，直逼中东。美国在中东的压力将会更大。只要美国从阿富汗一撤，土库曼斯坦将全面投入上合，阿塞拜疆也会“学习土库曼好榜样”，吉尔
吉斯斯坦呢？乌克兰呢？所以，在阿富汗美国必须死扛。伊拉克的情况也差不多。只要美国一撤，伊拉克的石油一桶也没有美国人的份。签了的合同又如何？
照样废掉！有本事再打回来！伊朗也会更加的无法无天，叙利亚也会学着伊朗的模样装大爷。阿拉伯国家还在乎以色列？个个都会往中俄的怀里钻。

只要这些方面都做到了，打倒美国霸权不在话下。接下来的欧盟就要容易对付的多——一个政治上不统一、军事上不够强大的组织是成不了世界霸主的。既使中
国不收拾它，俄熊也会啃了它。欧盟到头来只会落个给别人做嫁衣裳的下场。当然既使知道这个下场，它仍然会在中东狂拆美元墙角，因为如果不这样做，它
亏的更多。

既然写中国的全球战略，就不能不回顾一下中国过去的全球战略是如何执行的：

我们的人民共合国刚刚建立，美国就侵略朝鲜、直逼中国。毛主席带领着中国人民抗美援朝、保国卫国。一战下来，打出了中华民族的尊严，打出了中华民族
的生存空间。

1959年，中苏分裂。中苏分裂的真实原因是：艾森豪威尔上台后，变美国的战略从“遏制”为“大规模报复”，一切跟核战争挂钩，放弃过去认为在有限战争中不
应使用核武器的想法，决定只要军方认为军事上需要就可以使用核武器，面对美国以核优势为后盾的“大规模报复”战略和“战争边缘”政策，苏联决定“缓和冷
战”。 1956年2月的苏共二十大就提出了“和平共处”、“和平过渡”总路线。这实际是要求已经当政的共产党不要得罪美国，没当政的共产党（包括当时没统一
的越南）别再走暴力革命的道路。潜台词：既然“一颗小小的火星就可以引起核大战”，那象抗美援朝那样的麻烦今后不能沾，免得惹火烧身，为了你的国家统
一把我苏联拖进核战争。

这样一来，中国收复台湾、维护领土完整和统一的民族利益就跟苏联的冷战需要矛盾了：要统一台湾就必须反掉美国的干涉。经过麦卡锡主义肆虐、顽固坚持
冷战理论、敌视中国的美国坚决拒绝跟中国做任何妥协，甚至根本不承认中国政府，只承认在台湾的蒋介石当局代表全中国。最典型的事例就是1954年日内瓦
会议上杜勒斯拒绝与周总理握手——敌视到这个份上，怎么“缓和”？即使中国放弃统一台湾美国都不会答应，更不用说中国坚持收复台湾了。毛泽东面临的问题
是：是为苏联的冷战需要而牺牲中国的民族利益，放弃收复台湾的努力，还是为中国的民族利抵制苏联的冷战需要？毛泽东“咬定青山不放松”——咬定中国的民
族利益绝不松口。这才是中苏决裂的根本原因。

在一般人看来，当时的中国实在是毫无希望了：外有强敌，内乏粮草，压力空前巨大，处境极端艰难，“黑云压城城欲摧”。中国既没有力量对抗苏联，更没有
力量对抗美国，又没有办法劝说美苏改弦易辙改变对中国的敌对态度。

在这个中华民族面临空前危机的时刻，毛主席使出了他最得意的国际斗争谋略：中苏论战+抗美援越。具体的做法是：支持越共中央武装统一越南；《毛泽东
选集》第四卷出版，指出 “帝国主义和一切反动派都是纸老虎”，要和美国打“人民战争”、“持久战”；批判苏联对美投降、背叛马克思主义。

毛主席这一下子同时戳到了美苏两家的痛处：美国苏联都是在自己阵营里当老大的主，最怕的是镇不住台。美国惟恐被看成“纸老虎”而众叛亲离，决心不让南
越垮掉，马上跳进了越南战争的泥潭，从此越陷越深。这下苏联也坐不住了：袖手旁观、任凭美国肆意欺负“社会主义大家庭”的成员北越，那“龙头老大”的面
子何在？威信何在？还保得住“社会主义阵营领袖”的地位？于是不得不援助越南对抗美国。而且为了证明自己才是正牌的社会主义阵营的盟主，不但援越，而
且专给中国当时给不了的先进武器。——抗美援朝时中国的先进武器都得自己花钱向苏联买，买回来自己学着使用，然后再自己费尽心血送上前线去拼命。现在
倒好，毛泽东一个“中苏论战”就让苏联一个子不要还卯着劲地白给，给的还净是当时中国给不了的好玩艺，还不劳中国人冒险，由老毛子亲自出马送货上门把
着手教越南人使用，或者直接派人操作——这等于无偿帮着中国实现“让美国吃个史无前例的大败仗，使美国自己得出结论：跟中国敌对没有好处，不得不有求
于中国”的战略总目标。这下中国可省大发了：有人心甘情愿倒贴着白帮忙还不用领情——我不谢你，你也不觉得是在帮我，连“聒噪”两字都省了，代价不过是“
中苏论战”的一通笔墨官司——世界上还有比毛泽东的这招阳谋更巧妙更合算的买卖吗？苏联这一上劲，美国更不敢无限制扩大战争了：要扩大，是扩大到中国
还是扩大到苏联？结果：战争一直老老实实局限在越南，使越南战争变成了一场符合毛泽东理想的时间、理想的地点、理想的方式的理想的人民战争，没有扩
大到中国。再加上中国是在指责苏联背叛马克思主义，对美国搞投降，这种指责本身就使苏联清楚中国没打算和美国联手对付自己。如果放着越南不管却跟美
国伙在一起收拾中国，就没法证明自己是“正统马列主义者”和“国际共产主义运动的领袖”，所以既下不了决心也没有借口立即进攻中国。毛泽东巧妙地利用了
美苏矛盾，限制了战争扩大，争取了时间，使中国得以加速备战、加快“两弹一星”、开展三线建设，使自己的安全有了切实的保障。

美国几十万大军陷在东南亚的沼泽里无法自拔，苏联则趁机大举扩张，在全球到处挖美国墙脚。美国此时突然如梦方醒：上了毛泽东的大当了。原来美国真正
的要害利益不是在东南亚的烂泥潭里，而是在中东和欧洲；真正威胁美国利益的不是“好战”的中国，而是美国以为“可以有共同利益”的苏联。美国敢情被毛泽
东诱进了越南战争的沼泽地白挨揍，如同老牛掉进井里——有力没处使，进不得退不得，眼睁睁看着苏联坐大而无可奈何。如果还不顾一切继续在越南硬抗到底
，就等于自我了断，把世界霸权拱手让给苏联。不管是谁当美国总统，借他八个胆他也不敢走到这一步。

1969年尼克松上台后宣布美国从越南撤军，使战争“越南化”，通过谈判取得“体面的撤退”—— 不管你南越是死是活，反正我美国得走人了。我走后你南越有本
事就靠自己活下去，没本事就听天由命。我真正关心的是别一垮一大片，弄得我管也不是不管也不是。只要美国脱身后只垮掉一个南越，那就谢天谢地，就算
“体面的撤退”了。

1972年尼克松访华，向毛主席登门求和。既然有求于毛主席，那就不得不满足毛主席开出的价码。最终结果：美国解除对华封锁和外交孤立政策，承认一个中
国、台湾属于中国，支持恢复中国的联合国席位和常任理事国地位、联华制苏。从此，世界政治力量的格局开始从“美苏两极世界”演变为“美、中、苏”三极的
“新三国演义”。（毛主席时代的中国战略部分系摘抄黎阳先生的《如何看毛泽东时代》一文，在此提出感谢。）

可惜的是，这时的毛主席，年世已高，没过几天就离我们而去了。毛主席刚刚过世不久，奇怪的一幕马上出现了：中国开始韬光养晦了！刚刚打完八年抗战时
，中国遍地废墟，毛主席没有韬光养晦；刚刚建国时，中国一穷二白、内外交困，毛主席也没有韬光养晦。为什么在毛主席刚走、中国外交形势一片大好的时
候却要韬光养晦？

韬光养晦的结果是什么？有两个标志性的事件可以说明一切：国内方面，运10下马；外交方面，美国国会通过了《与台湾关系法》。从运10下马开始，中国开
始了“以市场换技术”的道路。自主研发哪比的了引进技术快！结果呢？还是拿大飞机来做例子吧，如果不是胡主席执政，今天支线飞机能不能下线还是个未知
数，更不要提大飞机了。国有企业先是搞合资、合作，最后干脆大甩卖。还是毛主席留下的底子厚，二十多年都没卖光。仅此一点，说毛主席不懂经济的人就
得统统闭嘴！至于那部严重侵犯中国主权、干涉中国内政的《与台湾关系法》，就更不用提了，如果毛主席他老人家在世，就算美国国会的议员们拿枪顶在卡
特（当时的美国总统）的脑袋上，他也得把国会刚刚通过的那部《与》法给否决了！——一面有求于中国要急着跟中国建交，一面还敢对中国内政指指点点？也
是美国人时来运转，中国开始韬光养晦了！我们一路的韬光，一路的养晦，直到有一天，我们的大使馆都被人炸了，这时，国人猛然发现，再养下去中国就完
蛋了！

天佑中国，胡主席上台了。05年3月14日，《反分裂国家法》通过。那时，胡主席刚刚带领中国人民走出了非典的阴影，稳住了阵角。《反分裂国家法》是一
部《与台湾关系法》迎头撞车的法律。美国人通过《与》法来干涉中国内政、给台独势力打气、并随时准备在美国人需要的时候挑动台独搞独立以打断中国的
经济建设进程。《反》法则迎头撞来——除非美国人真的敢于为了台湾跟中国打一仗，否则就不要再给台独分子发错误信号了。所以，我们有幸看到了一幕非常
有趣的场面：美国众议院以424比4通过决议案，敦促布什对反分裂法提出严重关切——如此压倒性多数通过决议案愣是连个“反对”都不说，不是“纸老虎”是什么
？从此，再也听不到美国人开口闭口的把《与》法挂在嘴上了。

从这时起，胡主席带领着中国人重新开始了征服世界的道路（对此，我们不必隐晦，任何一个国家都希望征服世界，我们为什么就不可以呢？）。为什么如此
看重《反》法呢？道理很简单：如果我们的内政都能随随便便被人指点，我们又凭什么让我们的朋友依靠我们、敌人惧怕我们？我们连保护好自己的能力都没
有！所以，当《反》法强硬通过的时候，就是我们胡主席向全世界宣布“当年打得美国佬满地找牙的中国人又回来了”的日子。

从此以后，中国的全球布局有条不紊的展开了：

1、东亚方向：用《反》法捆死了美国的台湾政策；把朝鲜纳入自己的保护范围，支持朝鲜经济发展和东北亚经济一体化、离间韩美关系；推动“东亚核竞赛”
，直至06年用朝鲜核暴全面离间日美关系；加快推动东南亚经济一体化，把东盟做成中国的“后院”。

2、北亚方向：完善上合功能，全面深化中俄联盟，中国支持俄罗斯政治上、军事上对美强硬、经济上俄罗斯允许中国布局中亚，努力实现为上合成员国及其
前苏联国家的全面经济捆绑。

3、西亚方向：与巴基斯坦全面捆绑并以此为跳板跳入中东；对印度既拉且打，军事上威慑、经济上拉拢，分裂所谓的“美印日澳同盟”；大手笔投资伊朗与伊
朗捆绑、跳入直到控制伊核会谈进程，至到今天准备以伊核问题为桥头堡全面插手中东和平进程。

4、非洲方向：全面深化与非洲国家的联盟关系，经济上进一步融合，政治上加大对非洲盟友国家的支持。

5、欧洲方向：经济、科技层面加深合作，政治上加强协同，努力建立抗美统一战线。

5、美洲方向：毫不客气的与俄罗斯欧一起插手美国后院，当然，中国欧洲以经济布局为主、俄罗斯以军事政治为主（包括卖军火）。

透过这些，我们可以依稀看到了毛主席的影子——胡锦涛同志接过了毛主席的枪。


** 【奋进社/金鸿95】西方经济学的陷阱


    与只凭想象说话的微观经济学相比，西方经济学中的宏观经济学理论还是有一定科学性的。为什么那些经济学精英们不再坚持用分析微观经济的思路来分
析宏观经济呢？道理很简单：如果经济学精英们希望他们的理论能上得“庙堂”，就不得不在许多地方“从实际出发”，而不是一分析问题就 “假如假如”的云山
雾罩一翻。但是，宏观经济学同样存在着许多陷井，是我们不得不防的。现在把它们揪出来，以示世人：

    一、过时的萨伊法则：

    200年前，萨伊提出了被西方经济学界奉为经典的“萨伊法则”，即供给会创造出自己的需求，换句话说就是“生产会自行创造销售”。
    这一观点正确吗？恐怕大家会说，不一定。因为在今天的市场竞争中，有太多的企业由于销路不畅、库存积压而导致资金链断裂、企业不得不破产，所以
，现实并不支持“生产会自行创造销售”的观点。
    不过，如果我们换一个角度看，萨伊法则又有它非常科学的一面。这个观点是1803年提出来的，当时的欧美国家都处于卖方市场。在卖方市场条件下，萨
伊法则是基本正确的，至少没有明显不符合经济社会现状的地方。欧美国家进入买方市场是150年以后的事了（中国经济进入买方市场是1995年以后的事情）
。我们可以拿中国经济作例子简单看一下卖方市场的一个事实：年纪大一点的人应该都还记得当年的“布票”、“肉票”吧？这些“票”就是卖方市场现实下厂家生
产产品供不应求的一个真实写照，在这样的现实之下，“生产”当然“会自行创造销售”，就怕你生产不出来！
    萨伊和李嘉图以萨伊以萨伊法则为基础得出一个重要推论：所有商品都生产过剩的经济危机是不可能的。应该说，这个推论没错：在卖方市场条件下，怎
么可能出现全面的生产过剩呢？如果出现了，那就是买方市场了。从这里就可以看出萨伊法则的局限性。很显然，这是一个过时的理论。而现代的西方的宏观
经济学就是建立在萨伊法则基础上的。
    一栋建立在沙子上的大楼谁敢住？
    19世纪初，美国福特汽车公司通过推行流水线和科学管理大规模降低生产成本，确立了在汽车市场上的霸主地位。成功后的大老板福特曾经傲慢的说过一
句话：“我不管顾客需要什么颜色的汽车，我的汽车只有黑色的。”这句话把生产厂商在卖方市场上的强势地位清晰的描绘了出来，当然，这也是一句实话，如
果不是因为福特汽车都是“黑色的”，它也成不了霸主——大规模标准化生产以降低成本从而确立自己在汽车市场上的成本领先优势正是福特汽车的成功之道。但
是，随着汽车市场从卖方逐渐进入买方市场，仅仅一个“黑色的”汽车外壳已满足不了顾客追求个性的要求，福特公司却没有及时跟上顾客需求的变化。这时，
小斯隆当上了美国通用汽车公司的总经理。他采取了事业部制来对通用汽车公司进行管理，注重满足顾客的个性化需求。于是，通用汽车公司迅速超过了福特
汽车公司成了汽车市场上的新领袖。成也“黑色”的福特在市场竞争中落得了个败也“黑色”的结果（当然，福特制、科学管理理论和小斯隆的事业部制都是划时
代的企业管理理论）。从这个例子可以看出，生产厂商在卖方市场和买方市场上的表现完全不同。
宏观经济学也支持这样的观点：宏观分析的投资需求是一定时期的单个厂商或企业的投资汇集而成。单个的厂商（或企业）的投资心态都发生了变化，宏观分
析的投资需求能不也跟着发生变化？既然现实都变了，理论为何不“与时俱进”？我们都知道“刻舟求剑”的故事。在那个故事中，那个找剑的傻子只不过是坑了
自己而已。现在，打着“科学”、“经典”旗号的经济学精英们又是在坑谁呢？他们可是在对我们的宏观经济政策指指点点！
    鉴于凯恩斯的宏观经济模型同样以萨伊法则（S=I）为基础进行推导，所以对萨伊法则的错误推导不得不再做一点更深入的剖析：
    萨伊法则的等价命题是：任何数量的储蓄都会全于变为投资（S=I），其实，这一点是否成立，有两个关键的因素必须考虑到：一、萨伊认为货币只有“价
值尺度”和“交易媒介”两种职能，这与事实远不相符。现实经济生活中，货币至少还有一个“价值贮藏”的功能，这就意味着，在社会上会有一部分钱存在“既不
消费也不储蓄（投资）”的状态。二是在部分准备金制度下，银行系统有创造货币的功能（存款乘数）。由于这两个因素的存在，决定着萨伊法则是错误的（
即S≠I）。
    需要指出的是：萨伊的理论尽管与今天的经济社会状况不相符，在他本人生活的那个时代，萨伊的理论还是有其合理性的。比如，货币的“中性”观点（货
币供应量的多少及其增减变化，对于实物领域即商品总量及其构成以及各商品的交换比率等三个方面没有任何影响，货币及其数量只决定商品价格的名称及其
绝对水平），在当时社会也是合理的。因为那个时代处于金本位时代，几乎没有通货膨胀。进入廉价货币（纸币）时代则不然，刻意的增发纸币必然引发通货
膨胀，货币当然也就不再呈现“中性”。从这个意义上说，萨伊比起一代宗师凯恩斯来，还多了一点学者的良知。

    二、凯恩斯骗局：

    凯恩斯号称西方经济学史上的革命性人物，其形象一直光辉无比。今天的经济学精英们，多数为凯恩斯的徒子徒孙。可是，他的理论是一套彻头彻尾的骗
局。下面一一列举：

    1、掩盖真相的“工资刚性”
    “凯恩斯革命”推翻了萨伊法则关于宏观均衡的国民收入和就业量必然是充分就业的教义，作出了“工资刚性”的假设。即货币工资在一定时期内固定不变，
这不同于萨伊法则关于劳动市场是完全竞争这一前提。在完全竞争条件下，只要存在失业，工人之间的竞争将迫使货币工资下降。而凯恩斯认为，在现实生活
中，工人坚持不肯降低的是货币工资，有些失业工人，在货币工资不变物价上升、从而实际工资降低的情况下也是愿意就业的。很显然，凯恩斯的假设是有悖
于常理的。难到工人们都是自欺欺人的傻子：五毛钱两个的鸡蛋不买，专买二毛五一个的？
    当然了，象凯恩斯这种天才，既然做出了这种假设，肯定有他的目的。从他的“工资刚性”假设本身自然看不出他的目的，他的目的体现在他由此而推导出
的经济政策主张里。他的政策主张是：降低货币工资，现实上或政治上难度很大，而通过增加货币供应以提高物价，从而降低实际工资，既简便易行，又可得
到减少失业的效果。从这里，我们应该看到：降低货币工资在实际生活中是很正常的，失业工人之间的竞争必然导致工资下降。前几年不是传出过有大学毕业
生为了进去好一点的公司就业而不要工资的吗？凯恩斯却说“难度很大”，很显然，他在说谎。他说谎的目的是什么？就是“增加货币供应”！
    在金本位下，增加货币供应是很难行的通的，因为只有“上帝”才能制造黄金；那么，怎样才能增加货币供应呢？自然是用廉价货币（即纸币）。但是，在
“凯恩斯革命”之时，英国正从金汇兑本位向不兑现纸币本位过渡的时期。由此可以清楚的看出凯恩斯“闹革命”的目的了：为廉价货币政策张目！
    不过，在廉价货币通流的情况下，过度的增发货币必然导致通货膨胀而造成社会财富的重新分配。如果发行货币的银行归国家所有，那么，普通老百姓可
能不吃亏，因为国家可以通过自己手中掌握的过多发行的货币来对老百姓进行补贴，在这种情况下，甚至可以促进社会收入分配的公平化。但是，如果银行掌
握在私人手里，那时，增发货币就意味着变相掠夺普通老百姓的财富。说到这里，大家应该明白了，“凯恩斯革命”是在从理论上对私人银行家的掠夺行为合法
性进行辩护。
事实上，凯恩斯年青时就已经认识到了通货膨胀的巨大的危害：没有金本位的情况下，将没有任何办法来保护人民的储蓄不被通货膨胀所吞噬。凯恩斯本应该
是金本位的坚定拥护者，为何后来将黄金贬低为“野蛮的遗迹”、鼓吹廉价货币理论？因为他也是“理性人”，也要实现个人收益的最大化。当然，凯恩斯“理性”
的结果，就是红的发紫，紫的发黑。

    2、欺骗世人的消费函数
    凯恩斯的消费函数C=a+bY是其宏观经济模型中的一个非常重要的函数。但是，这个消函数并非统计归纳的结果，也不是根本先验的假定进行推演的结果，
只是以偶然观察为依据；而另一消费函数C=bY是对经济事实统计归纳的结果。美国经济运行的事实数据证明，凯恩斯的消费函数C=a+bY在短时期内（比如十年
）是与事实吻合的，但是，如果把考察的周期加长（比如七十年）来观察，则凯恩斯的消费函数并不正确，正确的函数形式为C=bY。
    为什么会出现这样的情况？
    其实，短周期的消费函数之所以是C=a+bY而长周期的消费函数C=bY的原因很简单：每个周期之间通过以严重的经济危机出现的年份为断点（关于经济危机
成因的讨论在后面部分），而每次严重的经济危机都造成了强烈的社会财富再分配效应（我个人认为用这个名称比较合理、姑且这么形容）——经济危机本身是
大资本家、大银行家来打劫中小资本家、银行家、其他中产阶级和普通劳动者财富而制造出来的经济崩溃状态。正是因为社会财富在经历过了严重的经济危机
上进行了重新分配，才造成了消费函数的突变。如果没有恶性的经济危机的存在，那么，无论是短周期，还是长周期，其消费函数都是一样的，即C=bY。我们
国家不存在因恶意的通货紧缩而出现的经济危机，所以，我们做宏观经济分析时，应该用C=bY这个函数而不是凯恩斯的那一个；当然了，计划经济时期（
1950-1978年）的消费函数可能与1978年以后的不一样，这是很正常的事情，因为经济体制不一样。
    当然，在凯恩斯的推理中也有破绽：
    按照凯恩斯的分析，人们的消费支出与其收入之间具有一种稳定的函数关系：收入增加消费支出也会增加，但消费的增量小于收入的增量。凯恩斯的消费
函数就是以此为基础导出的。但是，如果仔细看一下上面凯恩斯的观点，大家会发现，凯恩斯的消费函数应该用二次函数才是科学的（一阶导数为正，二阶数
为负），而凯恩斯故意用了一次函数来描述消费函数，这一点显然与“经济学精英们”一贯以“科学严谨而不怕麻烦”的风格制做经济模型的做法不相符。这是为
什么？道理很简单，二次函数与现实经济运行根本无法吻合，所以他不得不用一次函数来代替（把二次函数Y= -ax2+bx+c中的-ax2项去掉，并对bx+c两项进行
重新修饰）。
    现在我们就不得不多长个心眼了，即然年轻时的凯恩斯就发现了通货膨胀的危害、最后却替那些制造通货膨胀的人辩解，为什么他就没有发现这个消费函
数存在的问题呢？就算他没有发现，他的那些徒子徒孙们难道就没有一个人去怀疑过吗？对于这个问题，有必要深思一下。凯恩斯关于“消费的增量小于收入
的增量”的观点包含着一个道理，就是消费不足导致的有效需求不足是必然的，而有效需求不足的必然性意味着失业存在的必然性。而且，随着经济的发展，
消费的“萎缩”会越来越严重——失业也会必然增加，严重到一定程度就是经济危机。——真相出来了，凯恩斯用自己的理论（包括消费函数公式）为世人洗脑：经
济危机是必然的，不是人为的！——这样体贴资本家们心思的“精英”怎么会不红？怎么可能不是一代宗师、革命性的人物？只要资本主义制度存在，资本家们肯
定会把凯恩斯的理论奉为《圣经》。
    按照凯恩斯的说法，消费函数C=a+bY中的a为自主的消费，即收入为零时也会有消费。乍一看，这是正确的，对个人而言，即使失业也要消费，再一想，
对一个社会而言，如果所有人都不工作，同样也需要消费，所以a是存在的。但是，事实果真如此吗？如果一个社会中的所有人都不劳动（收入为零），他们
需要的消费品是谁提供的？难道是从天上掉下来的？对一个经济体而言，只要有消费存在，必要意味着有等量的收入（劳动）存在。消费和收入是一枚硬币的
两个方面，不可分割。所以，现实中，不可能有那个可恶的a！（同样的道理，凯恩斯的税收线性函数、进口线性函数也都是错误的，两个函数都没有那个固
定不变的常数项。）
    可笑的是，某些西方经济学精英们为了把凯恩斯“偶然观察”出的函数与事实吻合起来，煞费苦心的搞了一大推的“收入假说”（包括绝对收入假说、相对收
入假说、恒常收入假说等）。现在，这些“假说”应该改成“假话”了。
    当然了，不能不说的是，凯恩斯确实是个“精英”，谎言编造的如此高妙，利用对人类直觉的欺骗来蒙蔽世人，的确不简单。可惜，再狡猾的狐狸也逃不过
猎人的眼睛。

    3、胡编乱造的货币需求模型
    按照凯恩斯的观点，人们对货币的需求有三种动机：交易、预防和投机。投机动机的意思是，人们之所以愿意持有不能生息的货币，是因为持有货币可以
用来买卖投机性的债券（即政府永久公债）。
    如果不考虑购买公债的利息收益，站在公众整体的角度看，购买公债进行投机是一种零和博弈，有赚钱的就有赔钱的，今天所有人都赚钱了明天就会有大
批人赔钱。但是，如果考虑利息收益，对公众整体而言，购买公债是一种投资行为。这和买股票是一样的，从个人角度看是投机行为，从公众角度看是投资行
为；而且股票的涨跌规律和公债是完全一样的，都是“市场价值与利率成反比例变化”。
    当然了，按照经济学精英们的观点，公债利息不能计入GDP，只能算是“转移支付”，因为取得利息收入的人没有提供相应的物品和劳务。但是，这只能是
精英们的一厢情愿罢了。公债、股票和储蓄对公众而言，都是投资——储蓄也是投资，只不过是通过银行间接进行的。如果硬要说这三种投资有什么区别的话，
那就是他们的风险和回报率不一样。需要强调的是，储蓄行为是投资行为不代表公众储蓄额等于社会投资额。
    公众购买公债是为了获利，但是，公债是永不偿还本金的（凯恩斯即以此为前提进行的分析）。所以，我们看到的事实是，公众中始终有一部分人持有债
券（准备高价抛售债券以获利），还有一部分公众持有“投机”货币（准备低价购买债券以便在高价时出售获利）。这一点和股市上股民的整体情况是一样的，
也是有人持股有人持币；和厂商的流动资本也是一样的，一部分已变成了消耗品、工人工资等，一部分做准备金；和公众出于交易动机持有货币也是一样的，
一部分已购买了消费品，一部分做准备金。所以，凯恩斯所谓的“投机动机的货币需求”应该分成两部分：一部分是投资，归入储蓄(S)；一部分是准备金，归
入交易动机的货币需求。
    现在，我们可以清楚的发现，货币的总需求就是货币的交易需求。如果用“货币的供求与利率的决定示意图”表示，在任一时点上都是一条垂直于横轴的直
线。而货币当局决定的货币供给在任一时点上，也是一条垂直于横轴的直线。现在，是不是有的朋友感觉到迷茫了？——在货币需求量与发行量不同时，两条直
线是不相交的；因为他们是平行线，无论利率如何变化，都不会相交。这该如何解释？其实，这才显示出现实经济世界的本质：如果货币发行量大于需求量，
就意味着出现了通货膨胀；如果货币发行量小于需求量，则意味着出现了通货紧缩；只有货币发行量等于需求量，才意味着经济运行中既没有通货膨胀也没有
通货紧缩。因为货币发行是货币当局决定的，所以，不论是出现通货膨胀还是通货紧缩，都是“人祸”，而不是因为那只“看不见的手”。
    现在，大家应该明白了，凯恩斯为什么要弄出一个“投机动机的货币需求”了。如果不把货币需求直线搞成曲线，如何与货币供给线相交？如何隐藏通货膨
胀的实质？其实，把“交易动机的货币需求”与“投机动机的货币需求”相叠加以得出“货币总需求”是没有道理的，这就象一个人告诉你：“我今年30岁，上过4年
大学，所以我今年34岁。”你一定会回应他三个字：“神经病！”
    明白了上面的事实，也就更容易理解为什么会冒出个 “流动性陷阱”来了。现实中哪有什么流动性陷阱，只有“凯恩斯陷阱”！
    凯恩斯对“流动性陷阱”是这样表述的：在现行利率很高（比如10%）时，人们预期日后的利率只跌不涨，则投机性货币需求为零；而在另一极端即利率最
低（比如2%）时，人们预期利率只涨不跌，此时人们必将卖出债券以持有货币，由此，货币当局在公开市场活动中收购债券所增加的货币供应量，必将全部被
公众作为价值贮藏手段保存在身边，这就是流动性陷阱。下面看一下凯恩斯表述中的破绽：
第一，流动性陷阱与现实不相符：当利率最低时，人们如果真的都认为债券价格以后只跌不涨而卖出债券（在理性人的假设下）时，就会出现集体抛售的局面
，这时，债券价格必然会在极短的时间内暴跌，这种情况可以叫恐慌性抛售。这时，抛售者面临的选择只有两个：一是深度被套，如果是这样，就意味着无法
象凯恩斯那样上嘴唇一碰下嘴唇就把债券换成货币；二是割肉抛售，如果是这样，能换回多少货币？又会损失多少货币？凯恩斯也没说。当然了，有人可能会
说，货币当局会大量吃进债券以维持债券价格稳定。现实会如此吗？如果货币当局是私人的银行家，他们会“学习雷锋好榜样”吗？如果货币当局是为社会公众
服务的，由于并不是每个人都在买公债，如果货币当局这时大量吃进公债就是在帮助一部分人止损，那没买公债的人不就亏了吗？货币当局做这样的买卖合理
吗？
    第二，就算是货币当局通过某种只有“上帝才有的能力”在公债价格非常平稳的情况下把公债买了过来，社会上存在的公债总量也是有限的。在这样的情况
下货币需求曲线怎么又会变成了与横轴平行的直线？它应该是一个点才对！在这个点上，公众手里只有货币，没有公债。也就是说，在此时，货币当局继续增
发货币，根本就没有公债可以从公众手里收购。现在，大家应该明白了凯恩斯不去确定公债总额的原因了：如果确定了公债总额，他又如何任意解读“无论货
币当局如何收购公债以增加货币，都会被公众当作价值贮藏手段保存在身边”，并造成一种货币需求可以无限增加的假象？他又如何解释货币当局严重过多发
行货币造成货币供给量线与货币需求线无法相交的情况？现在好了，因为“流动性陷阱”，货币需求线可以平行与横轴并无限延长，就算货币当局造成10000%的
通货膨胀，都可以蒙混过关了！
    ——好不精明的凯恩斯！敢玩弄世人的凯恩斯！一代宗师就是这个德行？难怪后世的经济学精英也是这个德行！因为有一个好榜样！
    在此也顺便说明一下为什么07年中国的通货膨胀如此严重：有太多的“热钱”通过地下钱庄或者其他非法渠道进入了中国，并兑换成了人民币，所以，中国
经济体中的货币就比实际的货币需求量增大了，即货币过量发行了，所以通货膨胀出现了，这也是06、07年中国外汇储备不合比例的高速增长的原因。出现这
样的通货膨胀也不是我们的政府愿意看到的，因为“热钱”不是走的合法渠道，所以不在我们的央行控制之下，这也是06、07年中央狠查地下钱庄的原因。只有
非法流入“热钱”的渠道堵死了，才不会出现我们的央行被动过量发行货币的现象——只要有美元进入了我们的储备体系，我们就得发行等价值的人民币进行兑换
。
第三，既然买公债可以算投机动机，那买股票同样得算投机动机。现实经济生活中，在利率非常低的时候，公众往往更多的把钱投到股市上去，造成股市的暴
涨。这时，“流动性陷阱”如何解释？
    由于凯恩斯的货币需求模型是编造的太不合情理，所以，在以此为基础进行分析时，闹出了大笑话。在《宏观经济学》教材（注：本案例是从复旦大学出
版社出版的《西方经济学》第三版一书中照搬的，该书作者为宋承先、许强。）第191页中有一个关于“货币的供求是怎样从失衡趋向平衡”的例子，内容摘要
如下：
    前提：利率为6%，此时人们自愿持有的货币为1050亿元（交易动机1000亿元投机动机50亿元），利率为4%时投机动机100亿元，利率为3%时投机动机150亿
元。
现在，假设当前利率为6%，而货币供应为1100亿元，下面看一下凯恩斯大佬是如何把“失衡”搞“平衡”的：在此时（人们手中有100亿投机货币）人们会将多余
的货币购买债券，由此引起债券价格提高、利率下跌，直到利率跌到4%为止（此时货币总求增为1100亿元，恰好等于既定的货币供给）。同样的推理，假设当
前利率为3%，其他条件不变，在此时，公众愿意持有的投机货币是150亿元（大于手中的货币100亿元），人们将卖出债券持有货币而引发债券价格下跌、利率
上升，直到利率升到4%为止（此时货币总求增为1100亿元，恰好等于既定的货币供给）.
    现在，可以看到那个大笑话了：在利率为6%时公众明明是在花钱，花钱花得利率都跌到4%了，而利率降到4%时公众手里还有100亿元的投机货币。公众花
的是谁的钱？怎么花不花的就不见少呢？在利率为3%时（公众此时手中有100亿投机货币）公众明明在卖出债券持有货币，为什么利率升到4%时公众手中还是
只有100亿的投机货币？卖债券得到的货币哪儿去了？
    至于凯恩斯分析的三种均衡利息率的变动情况（供币供应量的变动、收入水平的变动、投机性货币需求的变动）问题就更多了，多得我实在懒得去批判它
。如果朋友们有兴趣，可以自己去批判它一下。
    由于凯恩斯的货币供求与利率均衡理论是错误的，在此基础上推导的IS-LM模型自然是错误的。

    4、、倒因为果的AD曲线
    凯恩斯在推导总量需求曲线AD时，是以货币供给量不变为前提，假设“物价水平变化”，来观察国民收入是如何变化的。很显然，这是一种倒因为果的分析
方法。在经济社会中，国民经济的运行是通过商品交换进行的。商品交换则是以货币为媒介，货币的正常流动代表商品交换的正常进行。所以，货币在经济体
中的流动是因，全体劳动者创造的国民收入PY（即国民财富）是果。用公式表示就是MV=PY。在正常运行着的经济体中，货币供应量（M）没有变化，货币的流
通速度（V）是没有道理发生突变的。这就象是一条在正常的流动着小河，在水量（可比作货币供应量）没有增加的情况下，河水流速（可比作货币流速）怎
么会出现加快的情况呢？如此一来，国民收入又怎么会发生突变？物价水平又如何会发生突变？凯恩斯的这个假设是没有任何道理的！
    现实情况是：国民收入不变，货币供给量增加则物价水平提高，货币供给量减少则物价水平降低。货币供给量与物价水平是水与船的关系，水涨（货币供
给量增加）则船高（物价水平提高）。反过来则不成立——如果说水没涨船却高了，这可是天下最大的怪事了！船是怎么高上去的？这可不是市场那只“看不见
的手”能办得。到的，只有依靠“上帝之手”了。
    当然了，如果硬要说一下AD曲线的道理，那就是：（对任一条AD曲线而言，）在使用同一货币的不同经济体中，在相同的货币供应量条件下，在不同的物
价水平时，对应的国民收入也不同。重新强调一遍，它只能指的是不同的经济体。
    至于总量供给曲线AS，就更是胡说八道了。在这里凯恩斯故意把由于增发货币而引发的通货膨胀和成本上涨混为一谈。增发货币而引发的通货膨胀对经济
而言是恶性的，因为这样会掠夺公众的财富（如果央行是全民所有的则可通过补贴弱势群体促进社会分配公平化）；成本上涨则是良性的。
    下面解释一下为什么说生产成本上涨是良性的：
    在一个国家，不同企业之间的劳动生产率（生产力水平）都是不一样的。一般说来，生产率最高的企业的工人工资是最高的，而同行的生产率较低的企业
的工资也不会比生产率最高的企业低太多，因为如果差别太大则优秀员工会大量流失造成企业破产。如此一来，生产率较低的企业的生产成本就会比较高。随
着一个国家整体生产力水平的提升，所有企业的工人工资都会跟着提高，生产成本也会跟着提高（生产率先提高的企业先涨以吸引人才，生产率落后的企业不
得不跟着涨工资）。对于生产型的企业如此，对于提供服务的企业更是如此。比如饭店，社会生产率是否提高对工饭店服务员的工作效率几乎没有什么影响（
如端盘子的服务员），可他们的工资依然会跟着整体社会的整体工资水平不断提高，就是这个道理。
    这种生产成本上涨是良性的。如果生产率提高了而所有工人的收入没有提高，因生产率提高而多生产出来的商品由谁去消费？生产是需要消费来拉动的。
生产持续扩张而消费能力不足会影响经济增长。如果一个国家的劳动生产率不断提高而生产成本始终都没有上涨，倒是说明这个国家有问题了。当然，有人可
能会说，成本上升出口会受阻。这倒是正确的——也正是因为这个原因，随着一个国家生产率的提高，出口产品的技术含量才会越来越高。
    而凯恩斯又意识的把成本上涨与通货膨胀混为一谈，给狼披上了羊皮，居心何在？通货膨胀是指货币过量发行，而成本上涨是因为工人收入提高。二者绝
对不是一回事。
    因为AS、AD曲线都是错误的，所以，凯恩斯的宏观经济模型是毫无价值的。至于那些精英们用AS-AD曲线分析出来了的形形色色的通货膨胀理论，全部都
是骗人的鬼把戏。
    从逻辑性方面来看，凯恩斯的《通论》（即凯恩斯的革命理论）完全可以说是胡编乱造。一套理论编得如此糟糕还能成为正统的理论，确实是大本事。时
势造英雄，一点都不假。在此，我也正告中国经济教育界的爱国学者们，到了编一本逻辑上讲得通的经济学教材的时候了。

    三、西方经济学的狭隘性

    受制于西方经济学分析问题的出发点，即“如何实现个体最优化”，精英们在分析宏观问题时，总是容易犯下“差之毫厘，缪以千里”的错误。下面通过一个
被凯恩斯写进了现代西方宏观经济学教科书的案例来看一下西方经济学的狭隘性，这个案例就是“节俭的佯缪”。
    勤俭持家，节约储蓄，在任何社会都是个人的美德，但是，按照西方经济精英的说法，对一个社会而言，这种观点往往不成立。他们的理由是：假如一个
社会还存在着发展生产的潜在能力，在这场合，假如每家每户都节制消费，产品会因缺乏需求而表现为生产过剩，由此导致社会生产进一步减少和个人收入下
降、收入减少，生活水平下降，而且，这一动态过程是累积性的恶性循环，最后会引发经济危机。这个经济分析号称是经过“上世纪30年代的经济危机检验的”
。事实果真如此吗？
    拿中国经济做例子吧。从1952年到1978年26年间，中国的国民经济平均增长速度是6.5%（当时的世界经济平均增长速度只有3%），这一速度是任何一个国
家都无法项背的。这26年的时间，中国在一个连造罐头的马口铁都得靠进口的落后的农业国基础上建立起了一个拥有完整工业体系的强大国家。中国的工业体
系之完善，除美俄两国之外，再无第三国可比。不得不强调的是，那时中国绝大多数年份处于被封锁状态，没有外来投资，全靠中国人民苦干实干。当然，我
们的收获都是货真价真的：没有通货膨胀，没有内债，没有外债，不卖资源，不恶化环境。但是，在那近三十年的时间内，中国人民吃不好、穿不好，举国上
下无比节俭，也正是因为如此，直到1978年，中国的轻工业企业并不发达。如果按照“节俭的佯缪”的观点，近三十年的“恶性循环”下来，中国经济应该空前危
机才是，可为什么那时的中国经济没有表现出一丝一毫的“恶化”迹象？是精英们错了还是中国错了？
    其实，这个道理很简单，只不过，那些眼里只有“个体最优”的精英们永远都不会懂。还是让我这个只学了十八天宏观经济学的门外汉给他们上上课吧。
    的确，生产是靠消费需求来拉动的。如果消费需求萎缩则生产规模也发展不起来。不过，消费需求并不只包括个人消费需求，还包括社会需求（或者称集
体需求），比如兴修水兴、改造农田、修桥筑路等等（这都是毛主席给我们打下的好基础呀），社会需求的旺盛同样会拉动生产的高速发展。这才是我们的共
和国建国28年来重工业发展迅速、国民经济高速发展的原因。也不怪那些精英们不懂这个道理，他们眼里哪有国家利益、民族大义？只有“私人利益的最大化”
。在他们眼里，失业率能降到4%就是奇迹了，他们哪能理解当时的中国零失业是如何实现的！正在因为他们太“理性”，才会有“公地悲剧”：一群牧民在一块公
共草场放牧。一个牧民想多养一只羊增加个人收益，虽然他明知草场上羊的数量已经太多了，再增加羊的数目，将使草场的质量下降。牧民将如何取舍？如果
每人都从自己私利出发，肯定会选择多养羊获取收益，因为草场退化的代价由大家负担。每一位牧民都如此思考时，“公地悲剧”就上演了－－草场持续退化，
直至无法养羊，最终导致所有牧民破产。——这个道理还不简单吗？有便宜不赚王八蛋。在精英们眼里，这居然是合理的！

    综合起来，我们可以得出结论，西方经济学中的微观经济学完全是一套建立在虚幻假设基础上的、没有实用价值的理论，是一套为掩盖资产阶级剥削行为
的实质的理论。宏观经济学则是一套淡化资产阶级剥削行为、并帮助大资产阶级掠夺广大百姓利益的理论。那些西方经济精英都是在替资本家做辩护，没有一
个是为老百姓说话的。所以，当他们从嘴里再吐出不象人话的惊人之论的时候，一律板砖伺候！



** 请你参与

[2008-01-17 18:41:23]



    今天看《齐鲁晚报》，出现了一个“纪念改革开放30年”的系列报道，里面讲述了一个河泽东明县柳里村农民分田到户的故事，他们在77年初曾在村里搞过
一个类似于分田到户的“借地”的尝试，这一行动比安徽的小岗村早了一年多。很显然，他们也是中国农村改革的排头兵。柳里村的书记“冒着做牢的风险”带头
搞“借地”的原因是因为“村民吃不饱”，结果一搞借地粮食就够吃的了。

    现在，我有个疑问，难道分田之前农民的劳动积极性就那么差？这和下面这些篇文章写的是截然相反的。

    同样，按照黎阳先生的《如何看毛泽东时代》一文里给出的一组数字也好象和上面的内容有出入：“中国目前每年粮食总产量约4．69亿吨，总消费4．9亿
吨，缺口2100万吨靠进口。如果中国仍处于被封锁禁运的状态，那这2100万吨就进口不成。那现在也照样得“凭票供应”。”

    如果按照黎阳先生的那种思路来分析，农民能“吃饱饭了”应该主要是因为中国能进口粮食了——中美就是在那个时候建交的，之后就不再对华封锁了。我希
望把这个问题搞清楚，哪位朋友有中国建国以来的每年的粮食产量（总产、亩产、全国人均都要）和每年的粮食进口数量的统计数据？分析问题应该实事求是
，数字可以说明一切。

    ——麻烦哪位手里有数据的朋友跟贴提供给我，谢谢！

    下面一篇文章的名字叫《驳 “计划经济养懒汉”之说  》

    媒体上常见到所谓“公有制和计划经济是懒汉经济”、“养懒汉”之说。这也正是当初有人把工人阶级下岗失业、砸碎铁饭碗以及强使集体经济的农民分田单
干的理由。每每听来令人义愤不平，究竟历史真象如何？不能不为之一辩。

    所谓“计划经济养懒汉”，完全是主流经济学家们一种莫须有的杜撰。何谓“懒汉”？这只能理解为不劳动、图享受、游手好闲之人。明情人可想：这种人在
过去那种充满革命激情、纪律严格的年代，有可能存在吗？。精英们一直把计划经济说成是“专制经济”、“没有自由”、“人们都在严格的管制和监督下劳动”，
照此说来，在那种环境中怎会有大量“懒汉”、“游手好闲”的人存在？这岂不充分地说明精英们信口雌黄、自相矛盾，对计划经济完全是欲加之罪、何患无词吗
！

世人皆知，那时的共产党把旧社会遗留下的大量乞丐、盗匪、妓女、游手好闲之人都改造成了自食其力的劳动者，难道却又把劳动者养成“懒汉”、“好吃懒作”
的人不成！

    人们知道，在市场经济下，发展、建设主要靠的是资本、金钱，没有钱什么事也干不成。但在新中国初期，资本、物质条件极其短缺，发展经济、搞建设
完全靠的是人力、劳动者的双手。诸如大庆油田石油会战、建设兵团开发新疆农业基地以及开发北大荒、建造红旗渠等，其设备、条件极其简单，开上去的主
要就是人，硬是靠劳动者的双手在荒原、戈壁上创造出了财富。新中国的工业起步投资都很少，许多工厂都是由老一代工人们白手起家创建的。正是他们的劳
动、拼博、无私奉献，才使中国工业从无到有，创建起自己的石油、煤炭基地，钢铁基地，汽车、机车、机床、造船等机械制造基地、化工基地、电子工业基
地等，形成了独立完整的工业体系。农业上，完成了对大江大河的治理，干部群众齐上阵，修水利、建水库、打机井、改土造田，把大部分土地改造成能排能
灌的稳产高产田，基本上解决了中国的吃饭问题。全国粮食产量人均占有量在1979年就超过了改革之后的2003年，等等。老一辈创业者在当时经济条件下取得
那样巨大的成就，做出了那样的改天造地的业绩，是什么样的“懒汉”才具有那样神奇的力量！

    正如胡总书记说：“在社会主义革命和建设时期，我们确立了社会主义基本经济制度，在一穷二白的基础上建立了独立的比较完整的工业体系和国民经济
体系，使古老的中国以崭新的姿态屹立在世界的东方。”（2006年在纪念中共建党85周年大会上的讲话）。党的十七大报告更明确地指出：我们要永远铭记，
改革开放伟大事业，是在以毛泽东同志为核心的党的第一代中央领导集体“带领全党全国各族人民建立新中国、取得社会主义革命和建设伟大成就以及艰辛探
索社会主义建没规律取得宝贵经验的基础上取得的。” 这显然是对过去计划经济时期的建设成就的肯定。也是对所谓“懒汉”论者的当头一击。

    若论劳动的辛苦程度，过来的人们都不会忘记，当时无论是工厂、农村，还是机关、科研部门，干部群众一年中谁休息过几个星期天？不仅节假日、星期
天很少休息，而且平时也因突击生产、工作任务而经常加班加点，就是正常的政治学习、开会也是一律放在晚上。对比现在，就只说当时没有“双休日”这一条
，每个人每年就多干两、三个月的活吧！更不必说那时至少没有任何干部和群众中有整天吃吃喝喝、酒场不断、所谓“革命小酒天天醉”现象吧！也没有任何干
部群众从昼到夜地打麻将、赌博、“十亿人口九亿赌”现象，以及公费游山玩水、泡歌厅、抱小姐、包二奶那种功夫吧！更没有任何群众经常上访，甚至开着拖
拉机、汽车群体上访等事情吧！对比起来，那时与现在，究竟何谓懒汉多，何谓积极性、劳动效率高？这岂不是十分明白的事情吗？

    指责上一代人为“懒汉”的人，倒不如看看目前，各部门机构臃肿、冗员成堆，吃闲饭的人之多，历史上何曾有过？全国仅仅吃财政的人数就有改革前的十
倍之多。据有关统计资料，全国每年公款吃喝达3700亿元，公车消费3986亿元，公款出国旅游达2400亿元，公款赌资外流2000亿元，还有知识精英们的学术腐
败、成果造假费用等，仅此几项合计起来每年就有12000多亿元。如此天文数字的腐败成本，请精英们回答：能够养多少懒汉？能建多少大工程、大项目？能
给广大低收入群体增加多少收入？

    精英们长期间连篇累读地攻击计划经济时期“出工不出力”，请问如今各行各业“拿钱不干事”的又有多少？社会上漂荡的失业、没有劳动机会的人，甚至闲
置的大、中、专毕业生有多少？这种现象又叫什么“经济”？

    精英对“懒汉”、“不劳而获”的问题感性趣，值得欢迎，但无论从那方面讲，也总找不到计划经济那里去吧！

    对了,有关于粮食的统计数据的朋友请跟贴告诉我,谢谢!


    

** 【奋进社/金鸿95】把战火烧到美国去

到2007年年底，中国的外汇储备已超过1.5万亿美元了。这是一个非常危险的信号--这说明，一场中美金融决战已经打到了关键时刻。

02年年底中国的外汇储备是2864亿美元，03年年底中国的外汇储备是4032亿美元，04年年底中国的外汇储备是6099亿美元，05年年底中国的外汇储备是8188亿
美元，06年年底外汇储备为10663亿美元，07年年底外汇储备为15300亿美元。

通过这几个简单的数据大家可以发现，从06年开始中国的外汇储备出现了不合比例的高速增加。这说明，国际银行家们对我们下手了：大量的热钱通过地下钱
庄流入中国，央行不得不发行等量货币，所以中国经济出现了严重的通货膨胀。因为“购买”人民币的美元太多，人民币供不应求，所以人民币被强推着升值。
但是，如果我们升值，许多低利润的出口型企业将亏本、甚至破产。因为这些企业大都安排了大量的生产工人，如果这些企业都破产了，将影响我们的经济增
长和社会稳定，所以我们不能升值，就算升也只能慢慢升。由于我们的币值有升值趋势，所以又吸引了大量的热钱来购买人民币套利，如此一来，人民币升值
趋势更强烈，由此引发恶性循环。在这样的情况下，如果我们的央行顶不住了，人民币大幅升值，则热钱套利成功（比如，一美元兑八美元时他们把五千亿美
元兑成四万人民币，我们的央行被迫大幅升值到一比四，他们再把四万亿人民币兑成美元，即得一万亿美元。一进一出他们就赚了五千亿美元。这里还没有计
算热钱进入国内后炒房市、炒股市的获利。），同时，我们的以出口为主的企业将因人民币大幅升值而出现出口严重受挫甚至大面积破产的情况、进而引发大
量的工人失业，经济大萧条出现。

如果打个比方形容现在的局面，应该是这样的：中国经济就象一个大水库（水库里的水就是国内的货币，总水量就是是我们积累下来的国民财富），现在，外
面的洪水（即热钱）疯狂的冲击中国的金融大堤，因为中国的汇率是受管制的，所以，它们只好打了些暗孔（即地下钱庄）往中国经济这个大水库里注水，注
进来的水太多了，所以水库的水位上升很快（严重的通货膨胀出现了），因为水库内的水位快要高到的堤坝的顶了，所以水库里的鱼开始往堤坝外面跳了（鱼
儿就是国内的企业，鱼儿跳出代表国内企业受损）。现在，敌人的目的是用洪水冲垮我们的大堤，只要大堤一垮，水库内的水就会从缺口涌出去，水库里的鱼
儿草儿也会裹胁着冲走（即我们的国民财富将会严重流失，国内的企业也将落入他人之手）。如果真的出现了那样的情况，那就意味着日本经济衰退、苏联经
济崩溃的那一幕在中国重演了。我们的经济倒退二十年将是很正常的事情。所以，护堤是目前经济管理中重要的工作。所谓护堤就是堵住热钱流入的暗孔（狠
查地下钱庄），同时想尽一切办法把热钱从中国的经济体中剔出去(或者冻结)，这样才能消除中国的通货膨胀。

应该说,这种局面是非常被动的，那么，怎么做才能摆脱这个被动的局面呢？

我们大家都知道一句话，叫做“良好的开端是成功的一半”，这句话在国际斗争中同样适用。在每一阶段的国际斗争中，能赢得一个良好的开端往往就意味着在
斗争中已经成功了一半。那么，这个“良好的开端”在国际斗争中指的是什么呢？是“把斗争的主战场选在什么地方”。下面通过回顾建国以来在历次大的国际斗
争中“选择斗争主战场”的对错对中国在斗争中主动还是被动的影响：

1、抗美援朝。这一次是毛主席在被动中选择的战场。朝鲜半岛之所以暴发战争，是因为金日成挑起的。当时，他与斯大林密谋后即开始对南韩发动了统一战
争，当时的毛主席并不知情。结果，美国人抓住把柄加入了战场，金日成则被打的惨不忍睹。而此时，原来支持金正日的斯大林却不支持对美作战，甚至希望
金正日在中国的东北建立流亡政权。斯大林的原意是把苏美斗争的战场选在中国的东北。斯大林的目的很明确：让美国人支持南韩傀儡政权统一朝鲜半岛，威
胁中国的东北。那时的东北是中国的工业基地，美国人肯定会借着统一后的南韩挑衅中国。刚刚解放的中国哪是美国的对手，肯定求救于他。结果就是苏联在
中国的土地上发动一场“中国保卫战”。战争规模肯定是可控的，而有地利人和优势的苏联肯定输不了。结果只能是中国东北被打烂、依附于苏联。但是，没想
到的是，高瞻远瞩的毛主席看明了这一点，就算苏联不支持，自己也要和美国打一仗。结果大家都知道，我们赢了。不过，在战争中，我们用的苏制武器大都
是买的——为什么苏联支援的比较少呢（当然苏联也无偿支持过中国）？就是因为苏联不希望中国赢。通过这一阶段的对抗可以发现，毛主席在被动中“主动选
择了战场”——朝鲜，才打出了中国人的生存空间。

2、抗美援越。这一次是毛主席挑的主战场。赫鲁晓夫怕和美国打核战，要求中国不能和美国正面冲突，而中国要解放台湾就必须和美国正面冲突，为了中华
民族的根本利益，毛主席选择了与苏联绝裂。之后，公开支持越南统一，并大力宣传“美帝国主义是纸老虎”。眼看着自己支持的南越政权抗不住了，美国人为
了不让全世界把它挡成纸老虎，奋不顾身的跳入越南战场。与此同时，毛主席与苏联大打笔墨官司，批判苏联对美投降。身为社会主义阵营老大的苏联面子上
挂不住，开始全力援助越南打美国。应该说，在中苏绝裂前，中国是倒向苏联的；绝裂后中国则暴露在了美苏两强的火力之下。当时的中国很弱，对抗两强看
似无生路可寻。可毛主席硬是用他的妙计调动两强互欧。最后，在泥潭里扛不住了的美国人不得不向毛主席求和，结果呢，中国得到的最大收获就是成为了拥
有否决权的联合国强权。这一阶段的斗争，中国完胜。

3、苏联入侵阿富汗，这是苏联自己往火坑里跳。其实，那时的中国已经有点亲美了。这近十年的斗争，中美联手在阿富汗成功的消耗掉了苏联的强大实力，
从政治层面上讲，苏联的解体与此直接相关。之后，缓过手来的美国开始算计中国了。

4、李登辉闹台独。这一次，美国人联合日本把斗争的主战场设进了中国的台湾。应该说，前三个阶段的斗争，中国都没吃亏，这与以前的战场都不在中国境
内是有直接关系的。这一阶段的斗争中国无比被动。其实，这个道理很简单，就象两个人打仗。在哪儿打最好？肯定是在对方家里，如果赢了，对手家里的盆
盆罐罐就全被砸了；就算打平了，也能顺手砸他几块玻璃。如果在自己家里打，赢了也会有家俱被砸坏。所以，尽量不能在自己家里打。如果打不到对方家里
怎么办？那就尽量在他有存货的地方打，只要一打他能顺手砸他的东西就好

5、朝鲜核爆。胡总一上台，就出了非典——居然有人想把战场设进中国大陆！他们想不到的是，胡总干脆利索的稳住了局面。一场反击战开始了。美国又开始
拿台独说事，并用钓鱼岛把日本诱惑进来对付我们。这点鬼把戏糊弄谁？又想玩当年连李登辉那一出？结果，胡总没理这个茬，直接开打东亚核竞赛——朝鲜宣
布有核。把主战场拉到了美国人被打得头破血流的朝鲜。之后，中国重新取得了主动权。直到朝鲜核爆成功，日美关系被彻底离间，中国在东亚取得全面主动
权。此后，中国通过与伊朗进取利益捆绑，成功的将战场推进到了伊朗。而伊朗也很聪明，把对美斗争的战场推到了伊拉克（阿富汗也有一部分）。直到今天
，胡总要把战场进一步推到以色列的家门口。在伊核斗法期间，台独一直在挑事，许多热血的朋友就大喊“打这些狗娘养的”。可是，现在能打吗？人家是巴不
得把战场重新设进中国呢。。当然，这并不是说要任凭台湾独立。只是个机会选择的问题——要打也得在我们选择的时间点上打，而不是被别人逼着打的。现在
如果要打就在中东打，那里美国的利益最多。所以，现在，不到万不得一，不能武力收台。当然了，如果逼得没办法动了手，那我们就不客气了，到时候战场
肯定不是一个，也许是三个四个——我们要赔了，谁也别想赚一个子儿！

综合上面大国斗争的历史可以发现，选择一个有利于我方的战场对斗争的胜负是至关重要的。金融战也是一样的。我们不妨回顾一下，当年东南亚金融危机时
，美国人把金融战的战场选在了中国的家门口东门亚、甚至杀到了中国的香港，那一战如何呢？虽然我们在香港顶住了，可是我们的经济也大受拖累。

今天，美国为了咸鱼翻身，把金融战的主战场直接选在中国本土。我们应该怎么做？就地反击？那样赢也得亏。那我们应该怎么做呢？两手准备：一手是稳住
阵角，另一手则是把战火烧到美国本土！

稳住阵角的动作早就开始了，分这么几个方面：1、08年货币政策从紧，控制流动性泛滥。按开篇时的比方说就是把一部分水库里的水抽到另一个安全的地方
，把水库里的水位降下来。2、查地下钱庄，这个一直在进行。3、打压房价。热钱进来了，为了赢利他们在努力炒作房市、股市以求暴利。当然，他们不会选
择投资实业。如果他们选择了，我们双手欢迎，招商引资还有愁钱多的？为了不给他们以炒作的空间，必须把房价降下来。现在还在房市里的钱让它冻住——要
么就割肉解套。股市倒是不怎么怕他翻腾，那里绝对是我们的地盘，不愁玩不死它们。4、扩大内需。一个标志性的事件就是家电下乡，此举是在改变中国经
济主要靠出口拉动的局面，当然，此非一日之功。后继的其他的扩大内需的动作还应该有跟进。同时，作为拉动内需的必要条件，全民人民涨工资是必然的。
我们不能再给外国人充当廉价劳动力了。目前我个人注意到的就是上面这些，也许不够全。当然，我个人感觉，在经济结构调整方面，有必要充分注意。打压
某些投资过热的行业，以避免热钱钻到这些行业里凑热闹——让热钱要么自已滚蛋，要么变成长期投资！

稳住阵角是基本的，关键是把战火烧出去。现在，中国的内忧甚大；但是，美国也不是无缝蛋！一个次贷危机就把美国经济拖的差不多了。美国人搞次贷危机
，抢劫本国老百姓的财富我们不管，把许多外国金融机构也坑的不轻，大家都看到了，中国的几个大银行也有亏损，至于欧洲和日本，更是深受其害。这个次
贷危机一搞开了，美国的资本家们是一箭三雕：国内坑老百姓，对外贬值以赖债（各国的美元储备因为美元的贬值都缩水了，就相当于赖了一部分债不用还了
），寻找机会抢劫他国财富（对我们的金融战就是）。

现在只是开始，这场危机绝对小不了。当然，这正是我们可以点火的机会。要想点火，首先必须做好的一点就是，控制住美国经济危机的范围，不要让它出美
国。其次才是如何趁火打劫，乘机吞并陷入困境的美国优质公司。

欧洲去年12月份搞了个不小的动作，推动什么地中海联盟。意思很明白，把地中海国家圈入自己的经济势力范围。一旦美国经济大衰退，好为自己的企业找到
新的产品出口地，免得因为销售不畅出现严重亏损甚至大批企业破产的局面，也就是为了防止经济危机往自己家里漫延。中国这方面也应该没有停步，印度的
那个总理来中国大谈经济合作就是个例子。最好是中俄欧抱团，把非洲、东盟、中东、南美、南亚、中亚、大洋洲全部圈进来，那时候不愁小日本闻不得腥味
往里钻。当然了，北美的墨西哥和加拿大能拉进来就更好了。一句话，沿着美国筑防火墙，让经济危机在美国国内充分的发酵，不愁玩不死它。

下一步就是如何打劫的问题了。国家开发银行拒绝给花旗融资大家都看到了。为什么这么做？抬高门槛。如果我的判断不错，有心人一定开始充分利用自己的
全世界的影响力了，利用各种手段，堵死美国借钱从国外借钱的渠道，让它们不得不求“某个人”，那时，就可以开价码了。在明天撑不住了的更多的需要融资
的美国金融机构再求钱的时候，一定难度更大。当然了，为了公平，还得分配一下，给朋友们排排队，大家都有份。只要配合得好，趁火打一回美国人的劫是
完全有可能的。

在文章的最后说明一点，我写得这一篇文章主要是提供一种思路性的东西。我的经济金融知识还有限，手里除了新闻更没有别的资源来源。所以，在有些方法
上可能会有错误的地方，希望大家审慎对待。


** 最后一个毛主席示范村

[2008-01-25 20:03:01]

    德国《明镜周刊》1月24日文章，最后一个毛主席示范村

　　红色的旗子迎风招展，晨曦中飘扬着歌颂毛主席的歌曲。南街村的村民保留了40年前的计划经济和毛主席纪念馆。这个镇子投资数百万修建了一个毛主席
体验公园。

　　在中国的这个小村庄里，每天叫早的不是公鸡的打鸣声，而是歌唱毛主席的歌曲“东方红，太阳升，中国出了个毛泽东！”当中国的13亿人越来越多地习惯
市场经济时，南街村依旧保持着40年前的旧容貌。

　　在朦胧的晨曦中，人们骑着自行车穿过东方红广场，这个广场是1993年纪念毛主席诞辰100周年时修建的。广场正中间是白色大理石的毛主席雕像，似乎
正等待着第一缕阳光的照射。

　　在这个中国中部贫穷的河南省，时间似乎停滞在40年前，在毛主席像的周围红色的旗子迎风飘扬，马克思、恩格斯、列宁和斯大林的雕像也矗立在广场的
四周。

　　骑着自行车的人群是去上班的，他们工作的地方是20多家集体所有制的村工厂。除了雕像外，他们还坚持着计划经济。工人免费享受医疗、教育、食物和
住房。

　　“在中国南街村是很特殊的，”40岁的银行职员陈欣健（音译）说，“所有的都是集体制。只是工资不高。”在中国的其他地方都在为贷款、增长的健康费用
和上升的房价而发愁的时候，南街村的人却没有这样的麻烦，56岁的王宏斌（音译）说道，他做了30年的村支书，护卫着村里的集体生活。

　　村子的商店里当然也出售人物玩偶、图片和其他的纪念品。墙上的挂钟也传出东方红的音乐，还配着毛主席的图像。对南街村的村民来说，保持对毛主席
忠诚也可以给他们带来收入，因为他们的村庄吸引很多旅游者来参观。

　　旅游者购买纪念品，参观毛主席雕像，逛体验公园，这个位于田野和工业园区间的体验公园是花了数百万欧元修建的。在里面游客可以乘坐小型电车，参
观仿建的毛主席出生的屋子。

附:南街村概况:
  南街村是一个在村党委坚强领导下，走集体共同富裕道路的村庄，生产资料全部公有，生活资料部分私有，属公有制集体经济。分配制度采取“工资+供给”
的分配方式： 
 
    随着集体经济的不断发展壮大，南街村的分配方式逐步由原来的工资制演绎成一种新型的分配方式——工资制加供给制。 

 实行工资加供给制，主要考虑到两方面的因素：其一，我国目前是社会主义初级阶段，干部、群众的思想觉悟还没有达到相当的高度，还必须实行工资制，
体现社会主义多劳多得的分 配原则，以达到鼓励先进、鞭策后进的目的。同时 ，集体已经具备了较强实力，有了实行供给制的物质基础，搞一部分供给的成
分，体现共产 主义按需分配的原则，让人们感受到共产主义的美好，一直想着共产主义，努力干共产主义 。其二，从南街村的实践看，供给制成分的增加，
有利于加强精神文明建设，是铲除私心和 防止腐败现象滋生蔓延的有效途径。私心是万恶之源，一切恶习从私心而来，而私心又是从 私有制产生出来的。所
以说，私有制的成分越大，人们产生的私心就越大。南街村首先解 决生产资料集体所有制问题，通过不断壮大集体经济，增强吸引力，使个体、私营经济逐
步 转向了集体经济，实现了生产资料全部集体所有制。但生活资料还没有完全公有化，人们在 生活方面、消费水平方面还会继续攀比，诱发私心。因此，必
须通过分配这个渠道，扩大供 给部分，彻底解决生活资料私有制的问题。

 南街村民目前的分配比例，工资部分占30%，供给部分占70%，以后工资的成分会越来越小，供给的成分会越来越大，供给的档次会越来越高，最终让每个南
街人富得个人没有一分钱存款。

 就工资部分来讲，南街村在具体实施过程中体现了“四个倾斜”：

 第一是集体与个人相比，向集体倾斜。不断扩大公共积累，增加公益福利，不断提高公有化程度。不搞那些高收入、高分配、分光吃净、挥霍一空的败家子
做法。

 第二是脑力劳动与体力劳动相比，向脑力劳动倾斜，充分体现科学技术是第一生产力和对知识、对人才的尊重。

 第三是外工与内工相比，向外工倾斜。南街企业的1万多名职工，在各自的岗位上勤奋工作 ，为南街事业的发展作出了重要贡献。村党委在政治上一视同仁
，量才使用；在分配上，相 同工种，外工工资要比南街村籍的职工高出20%—30%。

 第四是农业工人与企业工人相比，向农业工人倾斜。南街村农业尽管已实现了机械化作业，但工作环境还比较差，劳动强度还比较大，因此，农业工人比企
业工人的工资一般要高。这 样做，不仅体现了向苦、脏、累、险工种的倾斜，而且更有利于缩小三大差别。

 南街村的供给制始于1986年。当时尽管集体经济实力还很薄弱，但党组织一班人就果断决定 ，每年要增加一至两项福利，自寻压力，自出难题，逼出力量，
逼出智慧。从1986年至今 ，由最初的水、电免费发展到面粉、鸡蛋、啤酒、食用油、肉、豆浆、鲜鱼、气、子女入托 上学、医疗、住房等20多项共公福利全
部免费，使广大村民膳食更合理、身体更健康。逢年 过节，村里都要发放节日食品，尤其是春节，小到瓜子、糖，大到鸡、鱼、肉，节日食品达三十多种，
村民们一分钱不花，就可以过一个快快乐乐、富富足足的好年。不少老 人感慨地说：“村领导安排得真周到，我们想不到的也都分回来了。”

 从1993年起，南街村开始建设高标准的住宅楼，大套三室一厅，92平方米；小套二室一厅，74 平方米。村里统一配备了冬暖夏凉的中央空调、彩色电视机和
高档家具；卧室里席梦思床、高低柜、床头柜款式新颖，一应俱全；液化气灶、抽油 烟机等都是统一配置。卫生间设施齐全，一天24小时热水不断，村民们
洗澡十分方便。一 套住室耗资近8万元人民币。

 在南街村工作的外籍职工，也逐步扩大了供给成分。目前，职工们在食堂就餐一律实行了主、副食免费；职工公寓宽敞明亮，房间内配有中央空调，冬暖夏
凉。村里统一配备了床、被、脸盆、水瓶、茶杯、小柜等。到南街村上班，只要带上换洗衣服就行了。逢年过节，村里都要给职工发放节日食品，让大家高高
兴兴地回家和家人团聚。平时职工们洗澡、理发全部免费。各项文体活动丰富多彩，职工 们每年都能看到几十场电影和10多场戏曲节目。对表现突出的职工
，南街村吸收为荣誉村民 ，和南街人享受同等待遇。对生活困难或遭受天灾人祸的职工，村里给予特别照顾。对外籍 科技人员，南街村更是视为宝贝，关怀
备至，在住房、孩子入托、上学、用车等方面，都优 先考虑。不少科技人员感动地说：“南街村的工作环境、生活环境太好了!南街人这么看重 我们，我们只
有贡献全部的聪明才智，才不辜负乡亲们的厚爱。”


** 【金鸿95】巧合,还是必然?


第一个甲子：1889-1948  自立    中华民族寻求自救之路的60年
1889-1918   中国民族资产阶级革命（右翼）    失败      三十年河东
1919-1948   中国工农无产阶级革命（左翼）    成功      三十年河西
 第二个甲子：1949-2008  自强    中华民族建设强大祖国的60年
1949-1978  自立更生                  1966-1976        1976   四人
1979-2008  对外开放                  1992-2002        2008   四日
第三个甲子：2009-2068  自胜    中华民族领袖世界的60年


** 【奋进社/金鸿95】解决西方经济学的三大悬疑


西方经济学有用吗？

在我看来，西方经济学在目前看来，完全是一门无用的伪科学。为什么这么说？还是通过一个例子来说明问题吧：

假如你是一个司机，要送一车货去一个陌生的地方(不好意思，我也假如了一回；当然，看完了这个例子，就没有人会说我是在“假如”了)。为了正确无误而又
快速的到达目的地，你需要一个向导。什么样的向导才算符合条件呢？第一，认路，不能让你把车开到沟里去了，把货洒一地；第二，不能绕弯路，那样多耗
油；第三，知道在什么地方应该加速、什么地方应该减速、走多远应该把货加固一下免得掉了货，既要尽可能快的到达目的地又要避免出车祸。

现在，把上面“假如”换成现实：司机就是一个国家的政府，开车就是管理经济，向导就是做顾问的经济精英，不把车开到沟里去就是避免经济危机，不多耗油
就是避免通货膨胀，知道在什么地方应该加速就是知道经济应该如何增长、知道何时应该加固货物就是知道应该如何调整经济结构以适应经济增长。

下面，我们看一下，做向导的精英们称职不称职：无论是经济危机的成因，还是通货膨胀的成因及防治，还是经济增长理论，在西方经济学界都吵的一塌糊涂
，众说纷纭，莫衷一是。如果你是司机，你敢用这个的向导吗？在路上，你问他：“现在路上人少，前面有个拐弯的地方，我可不可以不减速？”向导说：“假
如……你就可以加速。”结果你一加油门，冲过去后才发现，前向是个180度的大拐弯，不好！开沟里去了！”你又问他：“现在前面没人，路又平，可以加速吗？
”向导回答：“假如……。”结果你一加速，前面突然窜出一条狗，你刹车不及，把狗撞死了——原来这个地方有个养狗的。结果赔了几百块钱人家才放你过去。接
下来，有问题你还敢问这个向导吗？这样的向导有什么用？

任何一门科学，都是用来解决问题的。经济学这样的科学，就更是为了替一国的老百姓谋福利了。可是，西方经济学能做到这一点吗？要说解决问题，经济学
最需要解决的问题就是：如果避免经济危机？如何消除通货膨胀？如何保持经济增长？只要这三个问题解决了，经济学家就是上帝派来的天使。可是，恰恰是
这三个问题，他们一个都没解决！

现实中，这三个问题真的那么难解决吗？下面一一解决之，只希望解决后经济精英们都改行吧，不要再糊弄老百姓了。

1、经济危机的原因：

在人民创造了相当数量的财富上，银行家们通过央行恶意的制造通货紧缩，资金链断裂引发大量企业破产、大面积的工人失业，失业人数太多引发需求下降，
进而造成更大规模的企业破产，形成恶性循环。这就是经济危机的原因。至于银行家们这样做的好处，那就是可以以超低价收购已破产或者陷入困境的优质的
企业资产，扩充自己的实力。

2、通货膨胀的原因

是因为纸币的过量发行造成的。好处就是可以不着痕迹的掠夺人民的财富。

3、经济增长的原因：

如果看西方经济学的观点的话，又该迷糊了：哈罗德增长模型、新古典经济模型……又是一大堆形形色色的理论，每种理论都是一大堆的公式和图表。这不禁让
人想到了一句话：经济学理论就象比基尼，暴露的都是重要的，隐藏的才是致命的。在对于国家经济政策没用的地方，经济精英们总能达成一致，可一到关键
的地方，每人一套理论，看看谁的都有道理，再仔细想想，哪个都有缺点。就象上面的经济危机的成因、通货膨胀的成因，都是有大堆的理论，再仔细想想，
谁的都有错误。现在又冒出一大堆的经济增长理论来。我们该听谁的？谁是对的？

看看他们得出结论之前的那一堆假如吧，把现实世界抽象成了一个不可能存在的世界（比如哈罗德模型中的一个假设，社会的全部产品只有一种。——这种高水
平的玩笑也只有经济精英们都开的出来）。在不可能基础上做分析得出的结论靠的住吗？他们全都是错的。听他们哪一个我们都会被带到沟里去。我就搞不明
白，分析经济问题真的那么麻烦吗？我还真不信这个邪。下面是一个比方，大家看看有没有道理：

一个经济体就象一个人，经济增长就象人长个子。人的个子是如何长高的？动力在哪儿？恐怕有人会说：“傻瓜都知道，多吃饭呀。”对经济体而言，“多吃饭”
意味着什么？增加供给！当然了，有人会说，供给增加要靠需求增长来拉动的，否则生产出来的东西没人消费也没用。其实，供给是企业生产出来的，供给增
加意味着工人工资会增加，即需要会增长。所以，供给增加就意味着需求增加——这样说并不意味着它们之间的比例是合理的。

当然，出于全面考虑问题起见，再从需求这个角度来分析一下：需求包括个人需求和集体需求。个人需求主要是个人消费品，大都靠轻工业企业提供；集体需
求比如国防安全、修桥铺路、电力电信、兴修水利、改造农田等等，主要靠重工业企业提供。当然，轻工业企业的生产设备、厂房等本身就需要重工业企业提
供（注：在此，实际上把农业和建筑业都划到了轻工业里面了，不太符合原来的产业划分，这样分析只是为了明确产业间的因果关系，不涉及其他）。所以，
从整体来看，经济增长的真正起点和拉动力首先在重工业。如果重工业不发展，轻工业就无法发展——不要说可以进口，重工业不发达的国家肯定不是一流国家
，我们中国是世界三大强权之一，没有理由靠进口却不发展自己的重工业。轻工业不发展，个人消费品都无法增长——经济增长的目的不就是为了改善人民的生
活水平、让人民过的更幸福吗？

当然，重工业、轻工业之间的发展有个合理比例的问题，企业的积累和给工人发的工资也有个合理比例的问题，这是不容回避的——只有调整好了这个比例，才
能保证供需平衡。随着经济的发展，经济结构也需要不断调整，才能保持社会生产力的全面提高——就象一个人，新陈代谢是全身都在进行，但需要一个过程，
有这么一个数据：一个人身上的所有细胞的组成部分七年就会全部换一次，也说是说七年前的你和现在的你从物质层面讲已完全不是一个人了。而新陈代谢的
过程中，人体各部分的比例是不断变化的（比如婴儿的头占身体总长的三分之一，成人则只有七分之一了）。经济体也是一样，也有个新陈代谢的问题，也有
个结构如何调整的问题。

当然了，我的分析中没有那一大堆的假如，也没有一大椎的公式，好象不够科学，希望精英们不要笑话。再简单说一下上面提到的“合理比例”是如何确定的：
注重历史数据，系统编制预算，随时调整偏差。根据过去国民经济统计数据的变化趋势进行计划，在执行中及时反馈信息，根据偏差及时调整，这样就足够了
。

当然，我这种分析思路和精英们是完全不同的。我是从“全国一盘棋”的角度出发的，精英们是从“追求个体最优”的角度出发的。因为只一个“全国”，所以，按
照我这种思路分析，只有一种合理的推动经济增长的方式。而“个体”就太多了，不同的精英代表不同的资本家（或者资本家组团，至少有的资本集团是专做重
工业、有的专做轻工业），他们的理论自然统一不起来——都想搭着经济体总体增长的便车自己实现最优。

再简单说一下如何调整偏差和比例的问题：对于需要优行发展的、作为拉动经济发展的重工业，国家可以直接投资或者采用低利息贷款吸引民间投资，国家也
可以增加采购额度以刺激投资；对于出于经济结构调整考虑应该限制规模的行业，则可以采用贷款高利率、提高征税比例、设置进入门槛（比如投资额低于多
少多少不给批）；对准备淘汰的行业，甚至可以设置关停期限、强令关停。为了刺激需求，国家可以采用设置最低工资标准、年工资最低增长速度、有针对性
的现金补贴等到，为了平衡收入，可以对高收入者高比例征税等等。

国与国之间的经济竞争也是一场战争，只不过不见血而已（不要说什么双赢，打不过你才和你“双赢”，打的过你谁和你“双赢”？）；但是，这样的战争后果往
往不次于流血的战争。比如当年的苏联经济崩溃，如果不这经济崩溃了，苏联也不会解体。这样的结果，靠战争都实现不了——当年有谁敢进攻苏联？所以，经
济政策是不容出错的。如果用那些通过一大堆的“假如”才搞如的理论来指导我们的经济运行，结果只能是家底赔光，给人家当孙子！

最后，再强调一遍，现实不容“假如”！整天靠着“假如假如”的纸上谈兵式的逻辑骗人的精英们，你们应该改行了！求求你们了！


** 尽管起飞时不知降落何处 温总理坚决风雪南巡
[2008-01-31 13:10:47]



    金鸿:周恩来,天恩来；温家宝，家中宝。敬礼！“人恒过,然后能改。入则无法家拂士,出则无敌国外患者,国恒亡。然后知生于忧患,而死于安乐也。”
 
    国务院总理温家宝在雪夜中坐飞机再转火车赶赴湖南视察雪灾情况，慰问群众，并指挥救灾工作。

      温家宝总理这趟到重灾区湖南视察，可谓几经波折。二十八日下午六点三十分，在结束一天的繁忙工作后，温家宝决定立即赶赴湖南。当时到长沙的各
项交通工具都受冰雪阻碍，不能畅行，但一路上总理毫不犹疑，坚决要到灾区慰问民众。

　　在没有接待手册，没有行程安排，甚至连飞机能在哪里降落，降落后转乘什么交通工具都不确定的情况下，温家宝毅然登上了专机舷梯。他说：“（湖北
）天河机场六点三十分我们决定（出发）的时候，还说可能降，现在说这还下大雪。那我们就到这（南昌）下。南昌基本有把握了，我就问志军（铁道部长）
能不能坐火车进去（长沙）。随便的车，我们能挤进去的就行，能走就行，有一节车厢也行。”

　　在得知南昌至长沙和武汉至长沙的火车机车受电网异常影响，也可能被阻断时，温家宝表示：“走到哪儿不行了，我就换汽车！”此时，南昌昌北机场的塔
台又传来消息：昌北机场因天气恶化不能降落。在与空军商量后，温家宝决定专机先起飞，随时联系武汉和南昌机场的塔台，临时决定降落地点。温家宝乘坐
的飞机最终在天河机场降落，后转乘火车于二十九日晨抵达长沙。另据本报记者张思静长沙三十日电：二十九日下午三时，温家宝来到京珠高速湘潭段，踏着
厚厚的覆冰，步行十余里，看望沿途连续奋战的消防、交警、路政、司乘人员以及被堵旅客。

　　踏雪访京珠高速

　　在湘潭马家河路段，有十座五百千伏高压输送线路塔杆因冰雪倒塌，为了近距离考察倒塌的高压铁塔，温家宝并没有沿覆冰已被清除的既定路线前行，而
是突然跨过中间的隔离带，走到维修人员身边，向他们仔细询问线路抢修情况，对坚守一线的工人们表示感谢。

　　下午五时，温家宝来到湘潭职业技术学院和京珠高速株洲段，看望被困车上的旅客。他鼓励大家要共渡难关，并承诺会加紧路面清障，让大家早日回家。
直至晚间八时半，温家宝一行才从已经复航的长沙黄花机场乘坐专机，转赴下个目的地广州。

　　三十日，温家宝冒雨考察广东省春运及市场供应工作。上午，温家宝来到广州火车站视察，慰问滞留旅客，看望一线执勤的铁路工作人员以及公安干警、
武警官兵，并指导当地抗灾救灾工作。
 
　　大公报报道，温家宝总理昨天广州之行，为寒风中的市民旅客带来洋洋暖意，直言总理爱民，而且“一点架子都没有”，在广州东川新超市与市民谈聊物价
与生活时，更让部分市民感动到流下热泪。记者在采访中发现，总理在匆忙走访中始终带有两种表情：亲切的微笑与忧患的凝重。

　　在广州火车站广场上，面对成千上万的滞留旅客，一身黑色大衣的温总理以其招牌式微笑与旅客们握手问好。他左手握着扩音器，动情地说：“大家回家
都很心切，你们的心情我完全理解。”两鬓浮白的总理嗓音有点哽咽，脸上有些憔悴，但眼神却坚定有神。随后，温家宝嘱咐工作人员向旅客派发了饼干、八
宝粥、矿泉水等食物，更令旅客大受感动。

　　而在看望一线执勤的工作人员时，温家宝在转达党中央、国务院的亲切慰问和衷心感谢的同时，面色凝重地强调：“现在广东特别是广州遇到的最重要的
问题，就是旅客群众，要解决这个问题。”他又表示：“我们干部和群众要不怕困难，耐心细致，做好管理，保证安全。”对市民旅客的亲切与对政府部门的严
格，一览无遗。

　　除了目前迫在眉睫的春运问题，春节市场情况也是总理担心的问题。在东川新超市走访时，温总理所到之处无不受到热烈欢迎。一名菜档主表示，总理非
常关心菜价问题，“他很爱民啊！”一名女孩与总理握手后更激动流泪说：“我最喜欢他亲切的笑容，跟他握手后，随手将手上一枝花送给他，他也很辛苦。” 

灾区滞留旅客：“看到总理什么怨气都没有了”

　　1月29日，总理温家宝在湖南长沙火车站看望滞留车站的旅客。温家宝总理对旅客说，春节快到了，我给大家拜个早年。你们被困在火车站，还没能提早
回家，我表示深深的歉意，现在我们正在想尽一切办法抢修，一定把大家送回家过春节。 

　　另据报道，昨天，虽然冰冻的长沙仍然寒意袭人，但不少市民却三五成群地聚在一起谈笑风声，多日冰冻造成的烦躁与不安似乎全没了踪影。 

　　李辉是滞留在长沙火车站的八千多旅客之一。谈起昨天见到在这里考察指导湖南抗灾救灾工作的温家宝总理的情景，这位急着回家的大学生无法抑制自己
的激动：“冰冻是不可抗拒的天灾，并非党和国家的什么决策所造成，但温总理却表情凝重地向我们致歉。这不仅需要勇气，更需要对人民的真情。有这样的
总理领导我们的国家，这是我们民族的幸运。”

　　他说，自己往来于学校和车站之间已经连续六天了，“看到总理，什么怨气都没有了。我们国家这么大，管理难啊！我们没有理由不坚决支持、配合党和
国家的安排。” 

　　十二岁的湖北女孩苏杰今天打电话给在广东打工的父亲，告诉他自己昨天在湘潭的安置地见到温总理的情景，骄傲之情溢于言表。“温爷爷要我把奶奶照
顾好，我做到了耶！”她还告诉父亲不要急，“因为温爷爷说，我们很快就可以见到你了。” 

　　作为一名环卫工人，蒲宏愿已在街上连续战斗了三天。“再冷的天我也要挺住。我们必须要让市民有更好的出行环境，这样也好让总理放心。” 

　　滞留在长沙的近万名高校学子开始商量如何响应总理的号召，用自己的力量为抗灾献出一份力。“咱们去车站接没地方住的老人和小孩吧。”“我们在网上
邀集没回家的人一起过年吧。”…… 

　　总理感动人民，人民用实际行动回报国家。“为节电，我家已不开空调了。”“我想呼吁更多的朋友留在长沙过年，不给国家再增加负担。”“我和邻居已经
约好，下午一起上路扫雪。”…… 

　　总理的到来，为冰冻的三湘大地带来了阵阵温暖与感动。如今，这种温暖与感动已经变成湖南民众抗击冰灾的坚定与信心。


** 【奋进社/金鸿95】绝招

[2008-02-03 00:38:58]


    台当局“中央选举委员会”昨日举行会议，决议“入联公投”和“返联公投”将与“总统”大选同在3月22日举行。

【金鸿评论】这则消息不禁让我想起一个笑话：一对夫妻第一胎生了个女孩，可他们非常想要一个男孩，于是给孩子取名叫“招弟”，希望下一胎生个男孩。结
果第二胎还是个女孩，于是他们又给这个女儿取名叫“再招”。可意想不到的是，第三胎还是个女孩，于是这对夫妻也火了，给小女儿取名为“绝招”。

看看台湾当局的表现，活脱脱就是美国人的“绝招”。在展开分析这个“绝招”之前，我们先看一下美国人搞过的“招弟”与“再招”是什么模样：

1、“招弟”

2007年10月19日，国民党“立委”苏起在台“立法院”爆料，表示收到来自民进党内部的可靠消息显示，陈水扁下令“中科院”研发核子武器。同日，伊朗外长穆塔
基表示，将在国际原子能机构（IAEA）的监督下建立一个核能合作组织，以此和其他国家在核能和平利用领域展开合作。

很显然，美国是希望中国在伊核问题上向他让步，才让台湾方面爆料台湾要造原子弹的。没想到的是，北京没理台湾的动作，却由伊朗接了招——要在中东开展
核竞赛。美国人毫不示弱，又让台北方面放风陈水扁要搞“入联”圣火路跑。俄罗斯人也马上赶进来凑热闹，《生意人报》10月23日发出消息，说中国将在2008
年到2010年间完成向伊朗提供两个大队（24架）歼－10战机的合同。面对着中国的强硬姿态，美国人不得不让步。于是，“入联”路跑搞成了一个大笑话：台湾
民间路跑社团24日爆料指出，主办单位为动员各地民间路跑、慢跑社团人士参加，凡参加者可领得“车马费”。路跑本来是打算为台独造势的，结果拆了台独的
台（路跑的人是拿钱买来的）。这让北京非常满意。于是， 25日外交部发言人刘建超在例行记者会上表态，俄罗斯媒体所称“中国将在未来两年内向伊朗出售
歼－10战斗机”的报道不实。因为美国实在也压不住伊朗在发展核技术上的强硬姿态，只好在29日让陈水扁出来保证，民进党当局不会研发核武器。而此后，
伊朗帮助其他国家发展核能的事情也就没有了下文。

2、“再招”

台湾当局“外交部”1月29日宣称，享有南沙群岛“主权”不容质疑。菲律宾总统府文官长荫美沓30日说，他已经命令外交部确认有关台湾在具有争议的南沙群岛
的一个小岛上建造包括一个飞机跑道在内的建筑物的报道。荫美沓表示，菲律宾坚持一个中国原则，所以只会和中国政府交涉。北京则马上表态，中国对南沙
群岛及其附近海域拥有无可争辩的主权，我们有信心、有能力维护国家的主权和领土完整，我们将继续致力于维护南海地区的和平与稳定。

本来，美国人希望用陈水扁来搅浑南海的海水——激化中国与东盟国家在领土问题上的矛盾，让中国把精力从中东转移出来。可令美国人失望的是，菲律宾根本
就不进这个套，反而强调“坚持一个中国原则”，这不仅让本来打算渔利的美国人一点好处没捞到，而且在自己操纵的台独问题上大丢其脸（美国对台独是表面
反对实际纵容）——支持台独意味着支持美国，反对台独则意味着跟美国政策保持距离。如果再让陈水扁在南海闹下去，台独在国际社会就更没有市场了。

无奈之下的美国人使出了他的“绝招”。

从表面上看，这是台独（包括美国）摆出了强力进攻的姿态；不过，我倒是感觉，“入联公投”离结束的日子不远了。

在《孙子兵法》里有句话：“辞强而进趋者,退也。” （后一句是“辞卑而备者,进也。”）过去的许多战争都证明了孙子的这条原则是正确的。在这里我可以举
一个例子，毛主席有一首很有名的词《井岗山》，里面有这样一句：“黄洋界上炮声隆, 报道敌军宵遁。”描写的就是他遇上的这个情况。其实，这一条原则不
仅仅适用于战争，也适用于国际斗争。如果某方真想做一件事，那就扎扎实实的做就可以了，没必要整天嗷嗷乱叫，生怕别人不知道似的。

其实，美国人这样使“绝招”，也是被逼得，它在中东实在是太被动，所以章法全乱了。下面看一下这几天中东又发生了哪些让美国人烦心的事情：

30号,以色列最高法院驳回了人权组织要求恢复向加沙地带正常供应电力和燃料的申诉,从而为以政府继续对加沙地带实施制裁提供了法律保障。

伊朗议长阿德勒30日在开罗表示，伊朗与埃及两国恢复全面外交关系仅是“时间问题”。

巴勒斯坦民族权力机构主席阿巴斯30日表示在未满足某些条件的情况下将不会与哈马斯举行会谈，法塔赫接受对话的前提是哈马斯放弃对加沙地带的控制，并
同意提前举行大选。

巴勒斯坦伊斯兰抵抗运动(哈马斯)1日在拉法边境采取措施，阻挠埃及封锁边境。

【金鸿评论】阿巴斯提出的对话条件非常的露骨——这跟打劫的强盗问路人“你要钱还是要命”没什么两样——如果哈马斯不接受提前下台和入弃加沙的要求，以列
色的封锁将会继续下去；但如果哈马斯接受了，也就意味着美国在相当大程度上摆脱了在巴以和谈问题上的被动局面，也就意味着中俄在巴以和谈问题上重新
变得无从着力。配合着阿巴斯的威胁，以色列的封锁行动又开始了。

很显然，哈马斯下台对中俄而言是不能接受的，对哈马斯和整个伊斯兰世界也是不能接受的。在这个关键的时候，传出伊朗与埃及即将全面恢复外面关系的消
息，这对哈马斯而言绝对是场及时雨——伊朗、叙利亚、真主党、哈马斯，都是一根绳子上的蚂蚱，一个蹦三个就跳。伊朗和埃及关系的恢复意味着埃及绝对不
会看着哈马斯被以色列人活活饿死。于是我们看到的就是哈马斯阻挠埃及封锁边境的场面。其实也对，你今天封了明天哈马斯再炸墙不是还得废炸药吗？

连埃及都要离美国而去了，整个伊斯兰世界还有谁会和美国一条心？看来只剩下法塔赫的领导人阿巴斯了——“走狗”这个帽子他是戴定了。

在中东方面布局顺手的北京自然不会对台独讲任何的客气。国台办马上做出了回应，台当局举办“入联公投”将付沉重代价。接下来会发生什么呢？

美国人会不会再拿出《与台湾关系法》来给台独打打气？我想应该是不会的。如果美国人真敢这么做，中国军方有人出来象朱成虎少将那样表态一番将是很自
然的事情（2005年7月底,解放军国防大学防务学院院长朱成虎少将在接受某媒体采访时就曾直言不讳地表示：“如果美国决定干涉,我们将坚决予以还击。我们
将对西安以东所有城市遭到摧毁作好准备,当然,美国也得做好中国摧毁美国数百个城市的准备。”）当然了，也许根本就用不着中国军方再表态了，伊朗和朝
鲜再在核问题上表表态就够美国人受的了。

入联公投已被明确的定性为台独，一旦开始则北京必打。如果美国不进入战场，基本上相当于把台湾白送给中国。美国人还没蠢到那一步。所以，入联公投在
最后时刻来个急刹车将是非常正常的事情。

附：这是年前本人的最后一篇评论。明天就回老家过年了。老家在比较偏僻的农村，所以近十天不会上网发文了。谢谢大家的来访。春节愉快！来年再见！


** 【金鸿评论】昨日重现
[2008-02-18 20:14:50]


巴勒斯坦伊斯兰抵抗运动(哈马斯)5日对埃及军队在埃及与加沙相邻的拉法边境冲突中动用武力表示遗憾。

【金鸿评论】拉法边境冲突事件在这种方式收场标志着以色列“饿死”哈马斯的计划彻底失败了。4日冲突发生后，埃及安全机构负责人指出：“尽管发生了严重
冲突，但拉法口岸的萨拉丁大门并没有为此而关闭。”这充分说明，埃及是站在哈马斯这一边的。出现这个结果也不容易，有人是出过力的。此前，传出了中
国要在伊朗建海军基地的消息。这显然是给埃及打气的。这条消息和前段日子传出中国要卖歼10给伊朗的消息是一样性质的，那就是警告美国在中东“做事悠
着点儿”。只要美国行动收敛了，就都没有下文了。正是因为现在埃及跟哈马斯有一腿，以色列对哈马斯的指责才不是空穴来风——哈马斯从埃及走私进巴勒斯
坦境内大批尖端武器。哈马斯这样做，也是未雨绸缪，以色列早就为困死哈马斯计划的失败准备了第二方案，那就是磨刀霍霍准备动手。看一条早一点的消息
：

以色列维诺格拉特(Winograd)委员会30日将公布一份报告，称现总理奥尔默特应该对2006年的黎以战争失误负责。

【金鸿评论】既然有人扯出了06年黎以战争，我们就简单回顾一下这一场让真主党名声大阵的战争的前因后果：战争发生之前，哈马斯正遭受着美以的全面封
锁，有垮掉的危险。在这关键时刻，真主党袭击了以色列哨所，打死7人抓走2人，以色列马上停止了针对巴勒斯坦的“夏雨”军事行动，把枪口转向了真主党。
以色列当时的目的很明确，先灭了真主党、压缩叙利亚对黎巴嫩的影响力，再回头收拾哈马斯，从而提高本国的安全系数。可动了手之后以色列才发现情况不
对：以色列的最初想法是让美国在伊（拉克）叙（利亚）边境上集结兵力镇住叙利亚，自己干掉真主党，可美国人死活不敢出手。心里发虚的以色列就没敢对
真主党下死手，所以真主党越战越勇（更奇怪的是，真主党的武器越打越好）。从实力对比来看，以色列是完全有能力灭掉真主党的，只不过为了保护以色列
的国家利益（如果没有美国的介入，以色列单方面对真主党下死手，极可能招出叙利亚和其他中东国家的的攻击），奥尔默特出工不出力，最后以色列成了众
人眼里的“失败者”。从这个意义上讲，奥尔默特应该对冲突的失败负责任。这场冲突的直接后果就是，阿拉伯世界敢跟美国人顶牛了，亲美的埃及也开始检讨
自己的外交政策了。今天埃及愿意出手帮助哈马斯的种子就是那时埋下的。从对06年黎以战争回顾中我们可以发现，那次以色列的出手，其目标始终没离开哈
马斯，所以，今天以色列人出来翻了帐，无非是在警告方方面面，哈马斯再不听话我可要下死手了。

那一次的冲突让欧盟非常的难受，因为其中东利益被美国严重挤压而无力还击。本来欧盟希望在巴以和谈问题上与美国配合着排挤中俄，结果自己反被美国排
挤了。而最后帮他们解围的人（也就是逼近美以停止攻击真主党的人），就是中国和俄罗斯。所以，为了防止这难受的一幕再次重演，欧洲人在加沙被封锁问
题上不能不表态了：

3日埃及总统发言人阿瓦德当天发表声明称，穆巴拉克与索拉纳一致认为，加沙地带目前的局势不能再继续下去。双方指出，以色列的封锁是造成在与加沙接
壤的埃及边界地区所发生事件的原因，以方必须停止目前的行为。

【金鸿评论】应该说，欧盟这个表态很巧妙，因为他拉了一个不错的伴儿。埃及的明确表态，有利于阿拉伯世界的团结——许多阿拉伯国家一向视埃及为叛徒。
现在，欧盟拉着埃及狂批以色列本身就是在向阿拉伯世界显示自己的“本事”——在中东和平问题上自己对阿拉伯世界还是很有用的（尽管欧洲人的想法有点一厢
情愿）。而且，此前欧盟通过德国拒绝美国要求它在阿富汗南部部署军队的要求和承诺加大对朝鲜的资源开发投资的方式向中国示好，通过为中亚五国打击阿
富汗贩毒活动提供4400万欧元拨款的方式换取中俄对自己在阿富汗存在的支持，并希望重新找回在伊核问题上“中间人角色”的位置。

欧洲人的做法让美国恼火无比：朝鲜半岛这边反美的卢武铉要下台了，亲美的李明博刚刚打算上台后用经济封锁的方式帮美国重新夺回朝核问题的主导权，这
边八字还没一撇呢，那边欧盟就出手给化解了。你说可恨不可恨？至于“打击阿富汗贩毒活动”更是可恼，本来中俄就通过在阿富汗周边设立禁毒带来对阿富汗
进行经济封锁、增加美国大兵在阿富汗生存难度的。现在倒好，欧洲人胳膊肘子往外拐，计算上自己（美国）了。

不过，欧盟的这点表示恐怕还不够。不用说中俄，就连伊朗也不会这么容易放过欧盟的。接下来，欧洲人还有活干，那就是与中俄联手封杀美国提出的制裁伊
朗的方案。

面对着欧盟的“反水”，局面又出现了新变化：

2月12日以色列副总理拉蒙说，“哈马斯的日子已经屈指可数，最长也就几个月。”这是以色列政府第一次公开表示要摧垮哈马斯。

黎巴嫩真主党组织指挥官伊马德-摩乌尼亚12日在叙利亚首都大马士革发生的一起汽车炸弹袭击事件中丧生。

【金鸿评论】不能不承认，历史总是惊人的重演。这一幕跟黎以战争时的情况惊人的相似。以色列的主意没有变，就是把真主党和哈马斯全部解决，以增加本
国的安全系数，可它也担心叙利亚出兵支援真主党。而要阻止住叙利亚的介入，就需要美国在叙（利亚）伊（拉克）边境上集结兵力对叙利亚形成军事阵慑。
对此（美国人能否做到），以色列毫无把握。为了试探美国和叙利亚的反应，以色列玩了个声东击西，嘴上喊着要“摧垮哈马斯”，却对真主党的领袖人物下了
手。不过，各方的反应让以色列非常失望：

美国政府13日对黎巴嫩真主党武装领导人被炸死一事表示欢迎。

叙利亚内政部长马吉德13日发表声明，强烈谴责12日晚发生在叙首都大马士革并造成一名黎巴嫩真主党高级官员身亡的汽车炸弹袭击事件。

西方外交官在13日表示，伊朗已经开始测试高级第二代离心机。

美国白宫女发言人佩里诺14日表示，美国支持伊拉克和伊朗发展良好关系。

中国日报网环球在线消息：黎巴嫩真主党领袖哈桑·纳斯鲁拉14日宣称如果以色列想要打仗的话，真主党已做好同以“公开作战”的准备。

【金鸿评论】从这些来来往往中可以清楚的看出，伊朗绝对会配合真主党对付以色列的，而叙利亚也不在乎瓜田李下。面对着这些刺头们的强硬态度，美国人
的反应居然是软化、软化、再软化。无奈的以色列居然选择了与06年8月的老招势来提醒美国，一起看一下：

巴勒斯坦安全部门官员15日晚称，以色列军队空袭加沙中部布赖杰难民营，造成至少8人死亡，40人受伤，其中10人伤势严重。

【金鸿评论】以列行的暴行与上次唯一不同的是，那次空袭了黎巴嫩的加纳村，这一次是沙加的难民营。对于以色列制造的这种残忍的人道主义灾难，任何一
个有良知的人都应该谴责。这也让我们看清了以色列是个什么样的国家。

那一次袭击完了加纳村之后，黎以战争很快就结束了，那个结果让奥尔默特的美国老板很不满意。这一次呢？恐怕还是个老结果，因为在中东美国人已经说了
不算了。不过，估计奥尔默特又要贪官司了。


** 【金鸿评论】关于科索沃独立问题的分析
[2008-02-25 19:36:05]


 在科索沃独立问题上，欧美是各打各的算盘：让科索沃独立，先借助美国的支持把俄罗斯的影响力挤出，进而整合整个欧洲经济，再把美国的影响力挤出，
让欧洲成为世界一极，用欧元压倒美元，是欧洲的算盘。从这里可以看出，无论是美国，还是俄罗斯，左右着科索沃局势对欧盟而言都是心腹大患。

让科索沃独立，之后利用科索沃引发的俄欧矛盾以及欧洲的内乱来影响欧洲经济整合、压住欧元进而拆掉地中海联盟，解美元霸权的围，是美国的算盘。

本来，欧盟希望通过让科索沃独立来达到自己经济、政治目的，可是，在过去的一两个月的斗法中，在美国人最被动四大问题上，欧盟没有在任何一个问题上
掌握主动权：

1、伊核问题。上面提到过了，欧盟之所以一再的对中俄让步，就是因为在伊核问题上他已暂时失去了中间人的位置。2、伊拉克问题。要想稳定伊拉克局势，
欧盟能起一定的作用；但是，如果伊朗和叙利亚不买他的帐，欧盟将起不了大作用。现在，伊朗和叙利亚都在中俄的保护之下，欧盟凭什么认为自己在伊拉克
局势稳定中的作用不可或缺？3、阿富汗问题。如果中俄翻脸，在阿富汗的欧洲人就得天天见血。在这里，欧盟绝对是有求于中俄的。4、巴以和谈。如果没有
哈马斯，欧盟在美国人面前根本没面子，因为以色列和法塔赫都听美国人的。而哈马斯离了欧洲人照样活——在对加沙封锁行动中，哈马斯度过难关可不是靠着
欧洲人的帮忙。

如果在这四个问题中的随便一个问题上欧洲人能有控制权，都可以作为将来和美国在科索沃问题上讨价还价的筹码，可是，这四个问题上，欧洲人没有一个说
了算！在这样的情况下，科索沃独立将是美国挤压欧盟的筹码。按道理说，欧洲人玩大国外交也有几百年的历史了，应该够老道，这次为什么干的如此毛燥？
如果欧洲人想反败为胜的话，只能通过在某些方面对中俄让步来完成了。

而现在的美国，无论在伊核、朝核，还是在伊拉克、阿富汗、台海和巴基斯坦通道上，都玩不出赢来，现在居然有心思再开辟新战场和欧洲人玩一局？是精力
过剩了，还是眼高手低？当年，克林顿通过发动入侵南联盟的战争成功的打软了欧元，顺手埋下了科索沃独立的种子——科索沃独立实际上是当年克林顿留给布
什的一笔外交遗产。现在，布什把这张牌打了出来，不过打的不是时候，所以，一张好牌给打臭了。这也没办法的事，水平不一样。过去，在东亚斗，中国只
能和和美国的代理人日本过招，根本近不了美国的身——美国用李登辉台独来挤压中国，而李登辉服务于日本人（这是美国在中国面前拉台日本的身价）。现在
翻了过来。在东亚斗，胡总用《反分裂法》捆死台独，用朝鲜死死缠住美国，美国人拼命折腾近不了中国的身，美国没办法，弄了个国务院副总理（副国务卿
希尔）不干别的，专门伺候金正日，就这样，老金还三天两头发脾气，搞得希尔天天往朝鲜飞。高手与庸手的差别，就在这里。

接下来，美国为了在科索沃压倒欧盟，也得在某些方面向中俄让步，否则中俄就会帮着欧盟算计美国——不管怎么说，现在欧美俩兄弟在科索沃开辟了内战的新
战场之后，肯定可以成为中俄捞外块的好地方（这也是我在以前的分析中认为科索沃不会独立的原因）。

在以前，在伊核斗争中，中俄联斗美国，双方都拉拢欧盟，欧盟是香饽饽；今天好了，风水轮流转，咱也当一回香饽饽。坚持一条基本原则——有便宜不赚王八
蛋，谁给好处都吃，吃他个河枯海干！

事实上，在科索沃宣布独立之前，美国人和欧洲人就表现出让步的意思来了，看一下：

美国军方和政府官员12日说，两架俄罗斯轰炸机9日在西太平洋上空“过度飞近”美国一艘航空母舰的事件并不具挑衅意味。

据俄罗斯空军远程战略航空兵消息人士2月13日表示，俄军图-95MS战略轰炸机2月9日在太平洋上空巡逻飞行时成功完成了搜索和发现美军航母的战斗训练任务
。

欧盟贸易委员彼得·曼德尔森14日启程前往莫斯科，准备与俄罗斯就俄加入世界贸易组织问题再度举行谈判。曼德尔森在行前发表的声明中说，俄罗斯加入世
贸组织是欧盟优先考虑的事项之一，这不仅会给俄罗斯带来好处，而且也有利于地区经济和全球贸易体系

俄罗斯原子能建设出口公司总裁谢尔盖&S226;什马季科(Sergei Shmatko)14日表示，俄罗斯将增派将近一倍的工作人员前往伊朗建设布什尔核电站。

【金鸿评论】许多朋友很关心俄罗斯轰炸机9日飞过一艘美国航母的事情。这与全球局势的进一步激化是息息相关的：一方面是以色列国防部长宣布将升级对
加沙的军事行动；一方面是科索沃宣布将在2月17日独立；日本也想混水摸鱼，要求俄罗斯归还北方四岛（这也是9日俄罗斯战略轰炸机闯入日本领空的原因）
，就连在格鲁吉亚，都有亲俄的人（格鲁吉亚反对派领导人帕塔尔卡齐什维利）提前做了牺牲品，老毛子能不火？俄罗斯强的硬表态是非常自然的事情。眼看
着老毛子发火了，美国人不得不示好，因为将来用的着人家的地方还多着呢。至于有没有挑衅意味，那还不是上嘴唇一碰下嘴唇的事？当然了，不管美国人怎
么想，反正俄罗斯人是铁了心不给面子，“就是去执行战斗训练任务的”！欧盟也没忘了提前打点一下，拿出一个大果子开始诱惑俄罗斯人。看着果子眼馋的俄
罗斯人吞了一下口水之后，却亮出了拳头——你们都想别耍着老子玩，否则，伊朗那边都够你们喝一壶的！有好处敢快拿出来！至于日本，根本就没有捞一把的
资本。

欧美都有求于俄罗斯这是很容易理解的，但要说有求于中国，许多朋友可能不认可，因为 “中国的手不够长”，伸不到欧洲。其实，中国的绊马索早就设好了
，而且已小有斩获，一起看一下：

伊朗石油部长努扎里最近表示，伊朗石油产品交易所将于下周启动。

朝鲜劳动党中央政治局委员、最高人民会议常任委员会委员长金永南15日在平壤表示，朝鲜决不容忍美国的任何敌对行动，将采取强硬的对应措施。

中国国务院总理温家宝15日晚应约与德国总理默克尔通电话。默克尔对中国部分地区遭受雨雪冰冻灾害表示慰问。默克尔说，德国致力于同中国发展良好的战
略伙伴关系，加强在双边和国际事务中的合作。德国将继续坚定支持和奉行一个中国政策，反对台湾“入联公投”，不支持“西藏独立”。德方祝愿北京奥运会取
得圆满成功。

【金鸿评论】伊朗的石油交易是用欧元结算的，这能不让盼望着欧元干倒美元的欧洲人心花怒放？可是，在伊核问题上，最吃重的角色是中国。如果中国不高
兴，那欧洲人只能做石油欧元的梦去了。所以，在这时默克尔出来自已抽自己耳光也是值得的。不过，按下葫芦瓢起来，这里刚刚摆平了默克尔，那边又出问
题了：

据报道，英国外交大臣米利班德12日宣称，西方必须继续努力促进民主的传播，极权国家的崛起将影响世界民主的进程。在演讲中，米利班德更形容中国为“
极权国家。

【金鸿评论】这位米利班德先生刚刚被开水烫着了吗？为什么要大肆攻击中国呢？

其实，这也不全怪英国人，谁让他们刚刚走了狗屎运呢？

英国军方10日表示，英军驻伊拉克巴士拉的军事基地9日遭到导弹袭击，目前不清楚袭击者的身份。

【金鸿评论】英国人遇上的，绝对是稀罕事，因为在伊拉克，美英联军遇上的多是没有什么技术含量的路边炸弹。被人拿着导弹问候，绝对说明问题——有人对
英国人的表现非常不满。那么，究竟是英国人做了什么犯忌讳的事情呢？看看英国人在阿富汗的表现就知道了：德国人死活不敢答应在阿富汗增兵，英国人却
一再要求北约盟国赶快增兵。眼看着英国人在破坏即将重新联合起来的中俄欧抗美组织的团结，能不给他个教训？

让人想不到的是，挨了一下子之后还在继续为美国人拉皮条。也难怪，这些盎格鲁-撒克逊的子孙里面的确有一部分是脑子进了水的，要不然他们怎么怎么会
传出下面的笑话？

英国一家电视台4日公布一项关于历史名人的调查结果，竟然有大约四分之一的受访英国人认为，前首相温斯顿·丘吉尔是虚构人物，有接近60％的人则认为，
福尔摩斯是现实中存在的人物。

【金鸿评论】在这个世界上，有两个小小的岛国是最讨厌的：一个是最凶残的，它的名字叫日本；一个是最狡猾的，它的名字叫英国。这两个国家虽然都不大
，却都非常的“自大”，一个自称“大日本帝国”，一个自称“大英帝国”，其实，就是两个巴掌大的国家。有句话是这么说的：“男人的野心和身高成反比”，这句
话用在这两个“大号”的国家身上，也适用。不同的是，它们中有一个的确称霸过世界（日不落帝国），一个却在征服世界的道路上折戟沉沙。今天，他们同样
都渴望辉煌，渴望成为世界的主宰。可是，当真正的巨人醒来的时候，哪有你们的份？

回过头来继续说中国设的绊子：这边伊朗向欧盟了叫牌，那边朝鲜也对着美国人开始喊话。应该说，以后打劫美国更容易一点——看看美国人在伊拉克都急成什
么样子就知道了，一边为了稳定局势不得不立法允许允许前复兴社会党成员出任公职以尽可能的为自己减压（刚刚打下伊拉克时所有复兴社会党分子都是要清
洗的），一方面还造了两封伊拉克基地组织头目的信件，并在信件里说基地组织正面临着“重大危机”。如果基地组织真要完蛋的话，美国人还会的着对萨达姆
的支持者示好吗？全部收拾了多利索？

接下来，两边还得给北京送礼。谁还敢说没有中国的份？打开麻袋，准备装钱！另外，在科索沃独立问题上还有两个比较有争议热烈的观点与大家讨论一下：

1、中国为什么不明确反对科索沃独立？北极熊这个家伙对“地盘”这个东西超乎寻常的敏感，巴尔干半岛是又俄罗斯人的传统势力范围，如果中国过多介入，
非但不会被感激，反而容易召来不必要的误解（中国想借机抢地盘？）。斯拉夫民族发源于科索沃，也就是说，科索沃是俄罗斯人的老家。如果依靠中国才能
摆平科索沃局势，斯拉夫民族的尊严何存？所以，中国表面上保持一种中立的态度是最好的。当然了，背后做什么就另当别论了。其实，在目前欧美都认为自
己能玩转巴尔干的情况下，中俄最好的就是瞅准机会狠狠打劫，直打得他们扛不住了再逼科索沃取消独立是最好的。这也应该算是 “钓鱼”。

2、台湾会不会象科索沃一样独立出去？

有许多文章都认为，科索沃独立有可能引发骨牌效应，出现什么苏格兰独立（英国）、甚至台湾独立。这种担心没有任何必要。今天科索沃能独立，绝对不是
阿尔巴尼亚人说了算的，而是大国斗争的一个阶段性结果。如果这种情况出现在中俄英法美的国内，其结果将是武力镇压，而不会象塞尔维亚那样“动用一切
和平手段”。领土问题一向是用铁和血来说话的。台湾是中国的内政，如果真的出现了台湾象科索沃今天的局面，那就意味着中国要亡国了。这种情况在是不
可能出现的。

科索沃问题是老鼠拉木头——大头在后头，科索沃不独立，欧美矛盾不会明朗化。现阶段，俄罗斯并没有真正吃亏，只不过非常丢面子而已。真正的好戏还在后
头，我们拭目以待好了。


** 【金鸿评论】次贷危机\人民币升值\雪灾对中国社会的影响
[2008-02-25 19:38:34]

                        
财经                    

金鸿:一周前发表的<倒春寒>一文太长,故拆成三篇<昨日重现><关于科索沃独立问题的分析><次贷危机\人民币升值\雪灾对中国社会的影响>
 
 在国际政治、军事斗争中，中国是顺风顺水、稳健布局，美国则是在中国（及俄罗斯）的强大压力下苦苦支撑；但是，在经济、金融层面，中国则面对临着
来自美国（甚至欧洲）的巨大压力，我们也是在艰难中苦熬。美国次贷危机、人民币升值、南方雪灾对中国的影响都是大麻烦，下面详细展开讨论一下这三个
问题：

1、美国次贷危机对中国带来的负面影响

据统计，自次贷危机爆发以来，我国去年第三季度对美出口已出现较大幅度的回落——第一季度，我对美出口同比增幅达20.4%，第二季度下降到15.6%，第三季
度更是降至12.4%。同时，因为戴着危机的“帽子”，美国可以在全世界同情的目光中贬值。对于有巨额美元储备的国家而言，美元贬值就是变相赖帐。这也给
我们控制人民币的升值速度带来了很大的麻烦。没办法，拆了东墙补西墙。从美国这边亏了，就从欧盟这边补一下好了。所以，一方面人民币对美元升值很快
，另一方面，对欧元却在贬值。

我们不得不面对的一个现实是，中国经济增长的结构是严重失衡的，投资和出口对中国经济增长的贡献最大，而居民消费支出占GDP的比重不到40%（正常值应
该在70%以上），也就是说，“内需严重不足”。出现这样的情况，是由于多年来一直强调“出口创汇”而造成的经济发展畸形。不要怪中国的老百姓不花钱消费
，他们都不是傻子，过去政府在社保、医保和教育等公共品的生产上投入严重不足，老百姓没办法，只能减少消费来存钱给自己养老、防病、买房子、供孩子
上学。这种局面直到胡温当了家才真正发生了改变。但是，美国的次贷危机让我们正在进行的结构调整难度大增。

随着中央逐年加大对社会保障体系的投入，老百姓会越来越“敢花钱”；只剩下一座大山想搬开比较麻烦——高房价。做到这一点，需要全社会的共同努力，特别
是房地产开发商们的支持。如果中央用铁腕降房价，不是做不到，只是那样做有可能让这个行业的绝大部分企业大伤元气。但是，如果非要让“调整结构成功”
以“破产一万家房地产公司”为代价的话，那么中国人民肯定会选择同意。如果用强硬的调控政策对付房地产市场，可能给中国的银行业带来数万亿的呆帐。这
当然是个大包袱。但是，在过去的十几年里，中国人民消化掉的呆帐恐怕不止几万亿了吧？所以，如果非要付出这个代价的话，中国经济还是可以承受的。而
且，一旦结构调整成功，以后的经济发展就顺利多了。当然，如果开发商们配合中央的政策，损失就小多了。

其实，任何一个行业要想正常的发展，都不能有不合理的超高利润。至少，超高利润的存在会吸引过多的投资，从而毁掉这个行业。现在，海尔、联想不都高
调在房地产行业里打拼吗？这样的示范效应会造成什么结果？大量外行的企业涌入房地产行业的结果只能是让大量的房地产企业在竞争中破产，这还是在没有
政策干预房价的情况下。所以，让房价回归理性对所有人都有利，包括开发商们。

2、人民币升值问题

人民币对美元升值不利于对美出口，但是，人民币升值的好处大家想过了吗？

最明显的就是，可以大量的节约用美元计价的原材料的成本。比如，现在石油是100美元/桶，在1：8的汇率下是800元人民币/桶，进口1亿桶石油就要花800亿
人民币。但是，如果汇率是1：4，进口1亿桶石油只要花400亿元人民币就可以了。这一下子就是400亿的成本节约！大家都知道，中国人卖什么什么不值钱，
中国人买什么什么涨价。这是国际资本集团在用剪刀差来压榨中国人民的血汗。现在，国际上大宗的商品交易都是用美元计价的。如果人民币能不断的升值，
本身就可以抵消相当大部分的原材料价格上涨对我们的经济带来的负面影响，保护我们的利益——如果不是07年人民币的较大幅度的升值，国际油价持续走高给
中国经济带来的负面影响更大。

人民币升值是好事，但是，升值速度必须受我们自己控制，而不是被别人逼着升，更不能一步到位。中国的经济体本身就是多年积弱的，就象冬天里一个身体
素质极差的人，躲在温暖的屋里临时没生病。如果现在一下子把他扔到冰冷的水里，身体肯定受不了，休克是小意思，一命呜呼都不奇怪。现在能做的，就是
先打开一点窗户，进来一点冷风，慢慢适应，再打开门，之后再走出去……

人民币升值，中国企业的出口会受阻，这是坏的一面。不过，任何事情都有其两面性。我们常说一句话，就是“逆境可以磨练人”。那么对出口型的企业而言，
人民币升值这个“逆境”，是不是也是一次磨练的机会？答案是肯定的。人民币升值，低附加值产品的出口将严重受阻。那些指望着“卖资源”、“卖血汗”发财的
企业面临的选择只有两个：要么关门，要么换个活法，走生产高附价值产品的路子。

一般说来，能出口的企业都是一个国家的优秀企业，但是，随着人民币的贬值，许多竞争力很差的企业都能出口了，许多本来不该出现的血汗工厂也出现了，
这对我们的经济体而言是非常不利的。打个比方，这里有一个舞台，一开始只允许经过专业训练的演员上台表演。这时的节目数量是比较少的，但演出质量是
有保证的，演出队伍的素质也是比较高的，演出收门票的收入也不低。可是后来变了，凡是张得开嘴伸得开腿的都允许上台表演（即贬值）。于是乎，一夜之
间演员阵容空前庞大，节目数量就象坐了火箭一般飞窜，但是，节目的质量变得惨不忍睹。再想收门票？演出质量那么差，不要钱都没人去看了。门票收的越
少，演出质量就越差——没有钱去请高水平的演员了。中国二十多年来的 “出口创汇”政策也是如此，造就了大量的整体素质奇差的、没有核心竞争力的企业（
这些企业就象长在人身上的良性肿肉，看着是块肉，还很有份量，但对身体没用处。为了身体强健，只有把他们割掉。当然，在割的时候，流血是必然的）。

那些所谓的“加工贸易”企业不就是在卖血汗吗？为什么人民币升值5%就活不下去了？因为利润太少。为什么没利润？因为没有核心竞争力（没有自己独到的技
术、没有自己的强势品牌）。这些企业的生存就是建立在工人的低工资之上的。成为世界工厂绝对不是什么好事，人力资源的低成本更不是中国的竞争优势。
一个美国人每月能挣1500美元中国人为什么不行？我们中国人贱吗？没有一个是发达国家是卖血汗的。

人民币在不断的升值，逼迫着这些企业转型：既要给工人高工资，还要有高利润，这就要求这些企业加大研发投入，提高自己产品的含金量。当然，各级政府
应该在政策和财力上支持这些企业的研发。当然，许多制造业企业通过往内地搬迁来保持自己的低成本优势（因为那些地方可以给工人开低工资）。对于这些
企业税收政策绝对不能太优惠，用地政策要从紧，抬高他们的运作成本（可以逐年加压，给他们喘气的时间）。不然，随着人民币的升值，这些企业还是死路
一条。

人民币升值的过程，就是中国出口企业的炼狱过程。在这个过程中，会有大量的工人失业，这是我们这个多灾多难的民族必须面对的现实。美国次贷危机爆发
的“恰逢其时”，大大增加了这个炼狱的残酷程度（让失业工人增加的更多了）。但是，从另一个角度看，这也是好事（在后面会说明这一点）。在人民币升值
过程中，我们需要做的，是把握好升值的速度。同时要尽可能的防止对人民币的套利行为，这就需要我们的金融系统严查内鬼，以最大限度的减少损失。不过
，要改变受制于人的现状，要增强我国经济体的竞争力，损失一部分外汇储备是没办法的事。谁让我们以前错了呢？

3、刚刚过去的一场雪灾的后续影响

08年伊始，一场突如其来的雪灾席卷了半个中国：四川、贵州、湖南、湖北、江西、安徽……说句实在话，对于这场雪灾，其他的影响我都没有太关注，我最担
心的，就是粮食问题。

这场雪灾造成的绝产面积，据报道已有1.05亿亩（不知道这个数据是不是“保守估计”）。有一种说法是：中国目前每年粮食总产量约4．69亿吨，总消费4．9
亿吨，缺口2100万吨靠进口（相当于缺口为4.3%）。而1.05亿亩农田一季的产量最少也是3000吨。这就是说，中国的粮食进口量有可能翻一番！去年中国进口
粮食的价格已创了历史最高，今年呢？——价格高一点可以容忍，关键是如果那时把可以从国际市场上买到的粮食全部买进来还不够怎么办？

1月22日，全国人大代表、“杂交水稻之父”袁隆平的学生、“杂交稻制种方法”和“杂交稻制种超高产方法”两项专利发明人黄培劲指出，从种种迹象看，今年内
地的粮食价格也可能飙升，因为农村劳动力大量转移到城市，导致耕地大面积抛荒，而有些基层政府官员隐瞒这一严峻事实，反而夸大种植面积，谎报粮食数
量。当下，一个不争的事实是，近年农村劳动力大量转移到城市，留在乡村的父老们随著年龄增大和生活好转，也越来越不愿继续耕种务农。加上城市扩容，
各地招商引资大量占用土地，耕地面积越来越少。粮食减产的趋势，从湖南去年收购的粮食总数量就可以得到验证。随著农村劳动力大量转移到城市，不少农
村已经变成“空心村”、“留守村”、“妇女村”、“老幼村”，这对农业生产产生的负面影响已经逐渐凸现出来。如果农村出现百分之六十的农户不种田，中国的粮
食危机就会随着到来。

粮食问题是关系到社会稳定的大问题，其重要性怎么强调都不过份。人命关天呀！这个问题如何解决？

我想，下面的功课是必须做好的：

（1）、保证足够的劳动劳动力。直接对实际农业劳动人口按人头进行补贴，减少进城打工农民的数量、特别是打算去卖血汗的农民的数量（正好可以把因人
民币升值而破产的企业中的农民拉回来）。为此，补贴的数量要有足够的吸引力。只有这样，才能保证足够的农业从业人员。现在的农村，大量缺乏有一定专
业知识和学历的劳动力；而另一个现实是，每年有超过百万的毕业生毕业后找不到工作。所以，中央应该出台有吸引力的政策，把他们吸引到农村去，为社会
主义新农村的建设出力。

（2）、确保充足的耕地面积。停止对农村的圈地运动，放弃大建设开发区来促进经济发展的政策。加快空心村改造，不能再让没人住的老房子闲着却用耕地
盖房子了。加强农村地区的基础建设，增加农村的吸引力，提高农村的现代化水平。逐步减少农产品特别是初级农产品的出口，提高出口农产品的附加值。随
着农业机械化程度的提高，会有越来越多的农民从农田里解放出来，所以，各地应该充分利用当地优势，大办集体企业，发展特色农业，安排富余人口，以提
高农民的收入水平和生活质量。

（3）加大对农业的扶持力度。大规模的重建农村基础设施，包括农业水利建设，农机建设，农村金融信贷机制，农村生产和信用合作社。

（4）用合作社，公社等集体生产的运作模式把农民联合起来。中国最富裕的农村，如南街村、华西村等，无一不是集体所有制模式。当年的农村改革急先锋
小岗村虽然现在粮食吃不了，可穷困依旧。邓小平说过：“实践是检践真理的唯一标准。”既然分开干不能富，那就联合起来。事实上，个体的小农生产与农业
现代化大生产是背道而驰的。在美国，一户农民使用现代化的农机设备可以种上千亩地。现在，农田分散在农民手里，如何达到欧美国家的水平？强行把农民
的土地集中到少数人手里又不行——那样中国还是社会主义国家吗？所以，唯一的办法就是在坚持土地集体所有的前提下，把土地集中起来，以合作社（或公社
）为单位，实现农业生产方式的现代化。同时，用解放出来的人口来发展集体企业。这样，农民再也不用奔波数千里去打工了。毕竟，中国人是安土重迁的。

　　（5）稳定农业价格体系。对农业生产物资进行政策性补贴（以工业反向扶持农业是发达国家的通行政策），确保其供应数量和价格稳定。严格控制农资
的流通领域，必要情况下可以进行行业管制。把对于流通领域的暗补改变为对于个体农民的实补，避免价格倒挂情况的出现。

另个，还有三方面的工作要配合跟上，方能起到良好效果：

（1）、计划生育政策要从紧。现在，许多地方超生依然严重(在某些地方超生五六胎的都很正常)，但是，中国的土地实在也养活不了再多的中国人了。如果
中国人口能实现负增长的话，将大大减轻整个社会的就业压力、减轻整个社会保障体系的压力，对中国经济体的整体产业改造和技术进步也是大有好处。现在
，允许独生子女生二胎的政策让人很不解。本来，一对夫妻照顾四个老人一个孩子就够累的了，再多生一个孩子压力不是更大？我们这个社会福利体系要承担
的任务是不是更多了？所以计划生育政策必须从紧。少数民族兄弟也该为计划生育事业尽一份力；不能光抓汉族人，不抓少数民族。都是中华儿女，都有责任
。

（2）、退耕还林中央去年已经叫停了，但是，在许多地方依然在进行。原因来自两个方面：一是许多农民不得已。举个例子，假如农民甲在自己的农田里种
了树，他的邻居乙不得不也种树。因为如果继续种庄稼的话，庄稼长不好——甲种的树的树根会伸到乙的地里，庄稼从地里抢营养的能力肯定抢不过树木（还有
个树挡着庄稼阳光的问题）。二是某些地方政府对依然在进行的农民种树行为睁一只眼闭一只眼。建议中央对此事抓紧，铁腕待之。如有必要，对于那些庄稼
地种成经济林的土地，给以经济补偿返耕也是值得的。

（3）、对于那些用玉米造燃料公司，建议中央给他们一部分补偿让他们转产或者关门。对于在内地新开的制造业企业在工业用地政策上一定要从紧，死保18
亿亩耕地。

以上的各项措施，概括起来就是两个字，就是“开源”（除了计划生育一项外）；要做好粮食工作，仅仅“开源”是不够的，还要做好“节流”工作。

如果中国的粮食缺口以前真的只有4.3%的话，那就意味着中国的粮食完全可以不进口——中国人浪费粮食太严重了！只有到那些各种各样的酒店、饭店、食堂看
看，大家才会明白中国人浪费粮食有多么严重。可以毫不夸张的说，那些地方的浪费率绝对不低于30%。另外，大家在家里吃饭就不浪费（倒剩饭剩菜）吗？
所以，如果中国人真的能够珍惜每一粒粮食的话，中国的粮食是完全可以实现自给自足的。

中国人浪费粮食的毛病到今天形成了已不止三天两天了，所以，要想纠正不是一件容易事。这需要中央出台文件，甚至通过立法来解决。既然夏天用空调不超
过26度可以定成规矩，那么给节约粮食立法应该没有人反对。而且，在粮食问题上无论是立法时还是监督执行时，都是站在道义的高度上的，手腕硬一点阻力
也小，用它收拾那些不作为的官员非议也少。

今明两年，注定是风高浪急的两年。在困难面前，我们应该万众一心，众志成城。相信在胡温的正确领导下，神奇的中华民族定能挽狂澜于既倒，障百川而东
之！


** 


** 老山姆金蝉脱壳，小日本火中取栗


** 金鸿时评：(30/8)地球村里小人物的大智慧






[fn:1]中东大乱
[fn:2]入联公投
[fn:3]新闻来源
[fn:4]《日中联合声明》
[fn:5]国际原子能机构
[fn:6]免费的午餐
[fn:7]援助？
[fn:8]什么平台
[fn:9]APEC


