# -*- org -*-

# Time-stamp: <2011-08-04 19:18:14 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+title: 破局东北亚

* 【金鸿评论】破局东北亚之一
  [2010-10-12 13:12:06]

  
美国总统奥巴马8日致函国会，表示他将放宽对中国采取的武器出口限制，批准对华出口C-130运输机以应对海上原油泄漏。

巴基斯坦外交部9日宣布将重新开放北约向阿富汗运输军需物资的主要陆路通道。

【金鸿评论】美国愿意卖C130只是个友好的态度，巴铁重开通道也只是个友好的态度，但这两件事足以成为标志性事件。它们标志着中美之间的三轮决斗结
束了，从此，中美由斗争转向了斗和。当然，斗和也是斗，不同的是，斗争有可能把局势斗崩了，斗和则以妥协为主，双方追求的是更少的让步，更多的得
益。

中国希望逼美国在东北亚让步，解除对朝鲜的经济制裁、朝美关系正常化，迈出东北亚一体化的第一步。所以，朝鲜开始重申应该早日统一，建立高丽民主
联邦共和国了（朝鲜对韩国示好）；俄罗斯和韩国的朝核六方会谈代表团团长也在一起商量俄韩战略伙伴关系的发展问题了（俄罗斯对韩国示好）；被中国
不明不白扣了半个月多的日本人高桥定也被放出来了（中国给日本人面子的同时和美国默契了一回）。真是其乐融融呀。

为了能迫使美国让步，中东方向的伊核六方会谈和巴以和谈同时出现了变化：

9日，伊朗外长穆塔基表示，伊朗准备好10月底或11月初就其核计划与六个主要核大国进行谈判。

9日，阿巴斯提出，如果巴以和谈失败，巴方将要求美国承认巴勒斯坦国。阿盟8日宣布，给美国一个月时间解决和谈僵局。

【金鸿评论】算一下阿盟给美国的最后期限，跟伊朗给出的谈判开始时间，正好有个交集，11月初。看来，中美斗和的高潮期，应该在这个时间段上。

以前，中国是以朝核支持伊核，只要伊朗那边有麻烦，金正日就把朝鲜那边弄的更乱，以此分担内贾德的压力。现在，伊朗的安全已经没有问题了，又是解
开锁在金正日手上的金手铐的关键时候，这时，也就到了伊核支持朝核的时候了。

现在，俄罗斯已经回撤到原来的立场上，欧盟对伊朗的制裁也是个空名儿，现在，中国要用亚欧大陆经济整合这根绳把俄罗斯和欧盟拴在一起，三方同时又
能借着伊核问题的激化来逼美国让步，岂不美哉？

三家联手敲美国的竹杠，美国又吃谁呢？吃日本。现在中国放人就是在给美国的暗示。估计接下来日元会有一波贬值，之后会接着再升！为什么要这样做？
主要是怕一口气把日元推到顶会把日本彻底搞垮了，以后美国就没得吃了。所以，还是让日本经济恢复一下，好多吃几回。

在重新拴住俄欧的过程中，中国获利将是最多的，所以中国也是最积极的。这不，北京已经开始动用土耳其这颗棋子了。

中国与土耳其关系急剧升温大家都看到了。09年疆独闹事的时候，土耳其还是跳的最高的，为什么不到两年就连北约的体面都不顾了呢？主要是中国给的好
处太多了。

土耳其处在一个极其重要的战略地理位置上，各方竞相拉拢，但谁也对他不放心（生怕拉过他来又跟别人跑了），所以，土耳其其实一直也是很尴尬的。自
从在伊朗核问题上露了一回脸之后，一切都变了，这一点有点象小沈阳春晚亮相：

上春晚之前虽然小沈阳很火，但仅限于东三省，自从上了春晚，出场费立马涨了一百倍；土耳其也是一样，虽然早就是个地区性大国，可仅仅在中东地区有
点影响力，而且因为中东是列强必争之地，他不但不能发挥自己的影响力，还常常受窝囊气，自从在伊核问题上露过一回脸，马上身价倍增。之前一直担心
的库尔德斯坦问题也通过土叙伊结盟解决了（伊拉克现任总理马利基有望组阁成功）。

小沈阳能有今天，不全靠赵本山在后面推的吗？成名之后小沈阳不是一个劲给赵本山磕头吗？其实不用说磕头了，让他叫爹也干哪。再看土耳其对中国的态
度，不就完全可以理解了吗？

现在，中国又开始借着土耳其这个支点开始搞串联了：

土耳其外交部长达武特奥卢6日说，土耳其期待波兰明年下半年担任欧盟轮值主席国期间促进土耳其与欧盟的关系。

【金鸿评论】加入欧盟符合土耳其的利益，但要等明年下半年才当代理班长的波兰来帮忙，那可什么都耽误了。土耳其的这个态度，是为了表示自己愿意促
进亚欧大陆经济整合的，要知道，波兰是美国往俄欧之间砸钉子的地方。

接着，德国总统武尔夫也要开始访问俄罗斯了，目的是扩展双边经贸关系；不过这时普京又拽了一把，说中国可能将成为俄罗斯天然气的最大消费国。要知
道，欧盟一直希望得到俄罗斯的能源，现在想要上门订货了，人家却要说要先批发给给别人，这不是存心抬价吗？

在普京自抬身价的同时，梅德韦杰夫也不忘贬低一回奥马巴：在与施瓦辛格会见时，老梅邀请他到莫斯科当市长。要知道，施猛男明年一月就要下台了，这
时老梅挖人的意思是非常明显的——你奥黑连州人级人物的就业问题都解决不好了，还有心思来找我的麻烦？


* 【金鸿评论】破局东北亚之二
  [2010-10-17 12:19:16]

  
【金鸿评论】近来，货币战争成了热门话题，这也很正常，它本身就是目前中美斗法的主战场。关于这个货币战争，各路神仙是众说纷纭，莫衷一是，我呢
，不象许多专家学者们那样，手里掌握着各种各样的数据资料，只好借事实说话。我相信，行动说明一切，其他的都是空谈。谁家里有多厚的老底自己最清
楚，谁家里有多大的窟窿要补自己也清楚，虽然在人前可以耍耍嘴吹吹牛，可真正掏钱的时候，还是惦量一下自己腰包够不够鼓。

次贷危机爆发后，美国经济大失血，不得不制定了从伊拉克撤军的计划表并逐步撤出了战斗部队；现在美国又在推动阿富汗和解进程了，如果再算上之前奥
巴马已经宣布的11年7月开始从阿富汗撤军，足以说明美国经济又有大麻烦了。过去八年里，美国在这两个战场上扔进去的军费大约在1万亿左右，如果打不
赢抢不到石油可是没人给他报销军费。设身处地的想一下，死了那么多人花了那么多钱坚持了那么久的一块阵地，谁愿意丢？现在，他宁可亏本也想撤出阿
富汗战场，就足以说明，美国经济要出大事了。当然，也有人造谣，说美国的军费是中国出的，因为中国买了美国国债，而美国国债缩水了，这相当于中国
替美国出钱了。这种说法很可笑，既然有中国这个冤大头，美国为什么不接着打下去，干嘛要撤军？难道他在同情中国？

现在，美国的问题还没到最严重的时候，什么时候美国也从阿富汗撤出了战斗部队，就说明美国这个病人彻底倒到床上快要一命归西了。为了不要把老命搭
进去，美国开始了自救行动。他打算怎么自救呢？开动印钞机。至于奥巴马的那个出口倍增计划，是糊弄鬼的，除非他有本事一把火把华尔街烧了。

【金鸿评论】美国开动印钞机，对中国其实是个好事：开动印钞机的后果是美元缩水，信用受损，这样一来哪个国家还愿意存美元？如果没有其他货币可以
选择，大家自然只能忍耐，但如果有选择呢？自然都愿意避险。欧元、日元、英镑是靠不住的，这三种货币还不如美元可靠，但是人民币就不同了，币值稳
定，经济规模大，又有足以对抗美国的强大军事力量（不要说中国军力比美国弱，共和国建国以来在战场上我们从没输给过美国）。所以，美国开动印钞机
，恰恰是给了人民币扩张的机会。至于中国手里的两三万亿的外储，说句实在话，全亏了又如何？现在是在进行货币战争，既然是战争，就要有牺牲，就要
付出代价，关键是一定要打赢。美元霸权值多少钱？不用算细帐，大体一估就可以，过去几十年美国用这个霸权把全世界抢了一遍，获利至少100万亿美元。
拿3万亿换一个值100万亿的东西划算不？另外，一旦美元崩溃了，美国经济也就全完了，那时，苏联解体时卢布暴贬俄罗斯人被洗劫的一幕将会在美利坚上
演，到那时，随便一抢就可以回本了。所以，算帐要算大帐，光算小帐就不要研究国际局势了。

现在，我们要做的是，利用美国经济急需输血必须开动印钞机的机会，趁火打劫一把，逼他在东北亚让步，给朝鲜松绑，允许中国从经济上全面整合东北亚
。满足了我们的条件，美联储开动印钞机我们没有意见。

现在中国对付美国的做法是以逸待劳、借力打力，用欧盟和俄罗斯来挤压美国，美国什么时候被挤压的受不了了，就会对中国让步了。对于中国的算盘，俄
罗斯和欧盟也是很清楚的，他们也不愿意帮着中国抢地盘，所以，自C130卖给中国的消息传出之后，中国就开始在外围积极的创造条件，推动俄罗斯和欧盟
挤压美国。有人可能会问，为什么中国不直接进攻美国？因为这会让俄罗斯和欧盟捡便宜，不划算。如果打个比方来说的话就是这样：让美俄欧三个人打去
吧，他们打的越厉害，口袋里掉出来的东西就越多，我们站在一边正可以捡，如果我们也上去打架去了，那时不光难捡别人的东西，搞不好自己口袋里的东
西也会往外掉。

俄罗斯最近的小日子过的很舒服。自从老梅访华全面靠向中国以后，不再在中亚跟中国内耗，转而往西进攻乌克兰方向反攻美国，欧盟也跟着凑热闹，以不
与美国联手对付俄罗斯淘换一份与乌克兰的自由贸易协定，对俄罗斯来说，欧盟掺合乌克兰比美国掺合要强，所以俄罗斯趁机要价，准备搞掉美国在吉尔吉
斯的基地。 15日俄罗斯又把查韦斯拖来见面，又签了一堆的文件，还要给委内瑞拉建设一座核电站，继续在美国的后院捡筹码。美国却没有任何还手之力，
这又是为什么呢？因为他的手脚被欧盟缠住了。

【金鸿评论】美国是非常清楚中国的算盘的，所以他现在想尽一切办法逼欧盟与自己一起进攻俄罗斯，以避免被俄欧挤压的情况出现（他为什么不直接进攻
中国？已经攻过三轮了，全部失败，还让自己的巴基斯坦粮道倒了霉）。可是，希拉里两次要求俄罗斯从南奥塞斯撤军都没得到欧盟的呼应，恼火之下，美
国开始给欧盟颜色看了。

11日，以色列总理内塔尼亚胡要求巴勒斯坦承认以色列是犹太民族国家以换取延长犹太人定居点限建令。内塔尼亚胡开出的是天价。阿巴斯怎么敢承认以色
列是犹太民族国家？如果他承认了，那几百万巴勒斯坦难民还回不回家？阿拉伯人还不马上把他宰了？

就在这时，埃及也代表阿拉伯人逼迫欧盟：11月份在西班牙巴塞罗那举行的第二届地中海联盟峰会成否开成取决于巴以和谈的进展情况。

埃及最近的表现很有意思，他一直在充当阿拉伯世界的反以先锋，10日埃及总统穆巴拉克刚刚建议阿拉伯国家要对邻国（指以色列）政策统一立场，11日埃
及外长盖特就要求把巴以和谈跟地中海联盟挂上钩了。要知道，1980年埃以媾和以后，埃及就被阿拉伯世界视作叛徒了，现在他居然要和众多的阿拉伯国家
统一立场了，而且第一个跳出来给欧盟好看。很显然，如果不是有人背后使劲了，就是埃及眼红土耳其今天的地位了。

埃及代表阿拉伯人的这个表态，相当于把欧盟架了起来，接着美国就在下面生了一堆火（内塔尼亚胡开出的开价），准备把欧盟烤了。

【金鸿评论】美国的这个态度自然也是在逼欧盟，跟自己一起进攻俄罗斯，同时在货币战争问题上与自己保持一致。所以，很在自然的，到了12日美联储表
态，说自己准备推出进一步的宽松货币政策，接着印钞票。

这时，中国国家外汇局回应，人民币汇改不等于升值，直接警告美国，小样，你敢乱来我就整死你！东北亚的事没给个交待以前，你的印钞机就停几天吧。

泰国也跟着中国出来表态，说要对海外投资者征收15％的利息预扣税，以阻挡热钱流入和泰铢升值。此前，新加坡、菲律宾、越南曾先后站出来与美国划清
了界线。过去一年多以来，美国差点用红衫军把泰国整得天下大乱了，泰国能在这时站出来是很不容易。

为了推动欧盟继续跟美国在中东斗下去，中国派出特使开始访问中东，时间是11日至23日，访问的国家是约旦、以色列、巴勒斯坦、土耳其和埃及，目的是“
劝和促谈”。

欧盟一看有帮手了，也跟着表了态，不过，这个态度让美国人大失所望。他们拿希腊说事，说希腊有能力在2012年之后通过在金融市场上融资来满足自己的
资金需求，所以不再需要救助。我们都知道，希腊前段时间差点被美国整残了，现在欧盟拿希腊说事很显然是在告诉美国：我不上你的当！这一下子气坏了
美国，他马上宣布自己在一个月前实施了一次亚临界的核试验，一个巴掌扇了过来；之后，美国又说自己正试图找到一种能够让巴以直接谈判继续下去的新
模式，以避免双方谈几天就卡壳，诱惑欧盟重新站队。结果，美国又失望了。

【金鸿评论】13日，在欧盟的默许下，内贾德访问黎巴嫩。美国一看大怒，马上说内贾德对黎巴嫩的访问是挑衅行为，并正式承认以色列是犹太国家，进一
步拉高了欧盟推动地中海联盟的难度。

这一天，中国特使吴思科到了以色列。吴大使一张嘴就不怀好意，说中国对陷入僵局的直接谈判很关心，现在可是中东和平的机会，以色列你可要抓住呀。
以色列人苦笑一声说，多谢吴哥好意，你们帮忙我们很感谢呀，我们希望通过谈判实现两国方案。此话一出，阿巴斯大喜，马上问，老兄你真的要和我搞两
国方案吗？那你们打算给我多大地盘呀？把你们（美国和以色列）画出的边界地图给我看看行不？又闹了个大红脸。

眼看着欧盟的支持没到位，盖特纳不得不出来消毒，说眼下全球货币战争还打不起来，大家不要怕。在先稳定一下局势之后，盖特纳又继续拿是否宣布中国
为汇率操纵国试探北京的态度。北京则通过人民日报的海外版直接回应，美元才是汇率战的始作俑者！

欧盟一看中国的支持到了，马上又补了一张牌出来：

【金鸿评论】14日，欧盟提议到11月在维也纳就伊朗核问题举行新一轮会议，准备用伊朗核问题这个杠杆压美国。北京一看，好得很，就等你这句话了，马
上公布了8日时新型地空导弹首次实弹命中小反射面目标的旧闻，暗示可以废掉F22，给欧盟和中东国家打气，有我顶着，往大了玩！

本来，美国承认以色列为犹太国家的动作就惹恼了阿拉伯人，现在中国人又出来给他们撑腰，当天沙特石油部长就宣布，伊朗将在2011年担任欧佩克轮值主
席国。准备给伊核这个杠杆上再给美国人加份量，现在好了，伊朗核问题真把石油美元给装进来了，有了这一步，巴以和谈的含金量可就大大缩水了。眼看
着美国被阿拉伯人欺到了头上，北京顺势表态，与南海问题无关的国家不要插手南海争议，哪凉快哪儿歇着去，华盛顿方面则没有任何反应。

在这同一天，吴大使又到了巴勒斯坦跟阿巴斯会见，表态支持建立独立的巴勒斯坦国，继续给欧盟输送弹药。

到了14日晚上，以色列批准了在东耶路撒冷犹太人社区新建设238栋住宅，终结了近一年的非正式新住宅建设冻结令，继续在巴以和谈问题上为欧盟制造障碍
。

这时，聪明的内贾德在黎巴嫩道出了所有阿拉伯人的心声，犹太复国主义者都是该死的！并且给阿拉伯人鼓劲，别他以色列今天这么强硬，他很快就要消失
了。

【金鸿评论】眼看着伊朗搅局，美国非常生气，反手对日本施压，逼日本在15日宣布停止开发伊朗的阿扎德干油田的开发并撤离伊朗。撤就撤吧，日本人走
了正好中国人接手。

这时，埃及又代表阿拉伯人出来警告美国了，说如果以色列继续在约旦河西岸扩建犹太人定居点，阿拉伯国家可能要求联合国承认巴勒斯坦国。这对美国而
言，这可真是个坏消息，真把这事弄到联合国去了，那美国可就是搬起石头砸了自己的脚了。所以当天晚上美国人就开始对以色列批准新建住房感到失望了
，也不承认以色列人所说的以美在此问题上达成默契的事了，转而继续努力创造条件促使以巴恢复直接谈判了。有了这一态度上的缓冲，到了15日美国完成
了变脸：反对以色列或巴勒斯坦在直接和谈停滞期间单方面采取行动！

美国人的这个反对单方面行动，其实不是反对以色单干的，因为以色列办的事本身就是美国指使的；也不是反对阿巴斯单干的，因为阿巴斯没这个胆量；他
是反对阿拉伯国家把巴勒斯坦建国捅到联合国安理去会的。可惜的是，美国的这个表态实在没有什么威胁，连口头上的威胁都没有。

中国这时则继续警告美国，说中国不会成为美国国内问题的替罪羊，东北亚不让步印钞机你就休想开起来。美国无奈，只好自己给自己找台阶下，说因为人
民币升值速度很快，所以暂不认定中国为“汇率操纵国”。人民币升值真的很快吗？和欧元英镑日元相比又如何呢？既然人民币三个月升3%都是很快的，那欧
元英镑日元等等三个月涨幅超过5%的货币是不是可以贬一贬了？

埃及在这一轮斗争中的表现值得表扬。

【金鸿评论】到了16日，局势出现了转机我们希望的转机：朝鲜宣布，做好了六方会谈的准备工作。老金把手一伸，奥黑哥，给我开锁吧？韩国方面也传出
了准备增设部门以加强对华外交的消息，李明博还算不傻。

只不过最近日本跳的很高，又是在河内宣称钓鱼岛是日本的固有领土，又是拉美俄加入东亚共同体，又是准备往阿富汗派遣自卫队医官和护士，又是往中国
驻日大使馆寄送子弹邮件，又是包围中国大使馆……折腾的不亦乐乎，他倒底想干什么呢？很简单，希望他爹高抬贵手，让日元贬一贬值，否则真要活不下去
了。

做为配合，土耳其总理埃尔多安表态，美国政府支持恐怖主义，因为在以军袭击加沙救援船事件时，美国执行了双重标准。土耳其的这个表态达到了四重目
的：第一，抢埃及的风头；第二，逼美国在伊拉克让步，第三，支持了中国，第四，给欧盟输送了弹药。

局势越来越好看了。

说几句闲话，我和网友miguel是15日认识的，我是看他的文章写的好才推荐给大家的。有人说是我和他是一个人，这是瞎说，我吃饱了撑的，一个人弄俩博
客，写今天发的这一篇文章就费我20个小时的时间，我哪有精力再这么折腾？还有，有朋友回贴说也想写写，这是好事，我支持，你们可以开博客嘛。写文
章最起码可以整理自己的思路，而不是人云亦云的看东西。我看了几位朋友的留言，比我07年刚刚写东西时强多百倍，不信可以去查我最初写的东西，那个
滥就不用提了。大家多写点，我也可以少写嘛。

* 【金鸿评论】破局东北亚之三
  [2010-10-20 22:32:22]

  
