# -*- org -*-

# Time-stamp: <2011-08-04 19:18:43 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent


* 金鸿时局评论
  
** 金鸿时局评论（2008/11/14）
  [2008-11-14 13:21:36]

  
    1、朝鲜《劳动新闻》12日发表评论说，实现朝鲜半岛无核化和维护半岛和平取决于美国的态度。朝鲜将根据美国的态度采取相应的措施。

    朝鲜外务相朴义春和到访的伊朗外长穆塔基12日在平壤说，在维护国家主权的斗争中两国将相互支持和声援。

    朝鲜国防委员会的中将金永哲日前表示，开城工业区是军方的土地，要韩国企业回韩国做事。朝鲜军方人士的这些言论很明显是暗示可能会要求韩方企业
撤出开城工业区，因此，朝鲜今后是否会采取关闭开城工业区的措施备受关注。

    【简评】在被金融风暴冲击的快要破产的时候，李明博还是死活不肯松开抱着美国人大腿的那双手，现在不收拾他收拾谁？其实，自从中国主导了东亚局
势之后，就一直在刻意的拆分韩美同盟。在李明博上台之前，这一行动一直进展顺利。想不到的是，李明博上台以后置于韩国的国家利益与民族利益于不顾，
死命往美国人怀里钻，我们是拖都拖不出来。没办法，扁他！

    应该说，前期的修理让李明博基本明白了自己算棵什么样的葱，不过，表现还是不怎么让人满意。现在，借着金融风暴，朝鲜下了死手——要么李明博离美
国人远点，要么韩国企业离朝鲜远点。这样一来，快要破产的韩国经济是雪上加霜了。下一步，就看李明博的表现了。

    至于朝鲜向美国要的态度，就是乖乖的站在一边，不要在东亚事务上横插一杠子！不然，咱们东边不响西边响，看谁更怕天下大乱！

    2、伊朗总统艾哈迈迪—内贾德12日在伊北部城市萨里警告说，伊朗将对敌人的侵犯行为予以明确还击。

    据法国媒体13日报道，巴基斯坦警方称，一位伊朗外交官今天在巴西北部边境被身份不明武装分子绑架，其保镖在袭击中被杀。

    【简评】为了给马上要招开的G20峰会上捞点儿筹码，美国人又拿着打伊朗做引子了。只是，美国人吓唬伊朗的次数太多了，伊朗已经彻底麻木了，该干
什么还干什么。如果美国人打算打伊朗的话，那应该先帮自己的盟友以色列的老百姓移一下民，否则，以色列真的会消失的。

    3、美国总统布什十三日走访纽约华尔街并发表讲话，试图提升民众应对当前这场经济危机的信心和勇气。

    据俄新网报道，乌克兰国防部部长尤里．叶哈努罗夫认为，未来几年该国不会加入北约，因为为此需要进行大量工作。

    法国总统萨科齐11月13日表示，美元不应该再被当作“唯一的全球通用货币”。

    现任欧盟轮值主席国法国总统萨科齐宣布，将在十二月六日在波兰格但斯克会见达赖喇嘛。

    【简评】开个金融峰会可真不容易。布什专门跑到自己的老板家里拍胸脯，当时布什是这么说的：“

全世界都会相信美国仍是世界经济的领导者。”  当然，为了让某些不怎么相信这一点的人也相信，布什不惜在北约东扩问题上向俄罗斯做暂时的口头让步。
不过，不知道俄罗斯人会不会相信这种空口白牙的承诺？对普京而言，与其相信美国要把摁住乌克兰不加入北约，不如相信自己的拳头能把加入北约后的乌克
兰打的满地找牙更实在一点。

    就在布什自信满意的装老大的时候，有人偏偏不买帐，抢班夺权之心昭然若揭。当然了，欧盟也知道单凭自己想挑翻美国不可能，又重新打出了达赖牌来
要挟中国。

    唉，何苦来着？这是一张早就打烂了的牌，连英国人都承认了自己过去的政策是“时代错误”、英国“非常肯定地”承认西藏是中华人民共和国的一部分了，
萨克奇一个人玩西藏牌就不感觉孤单吗？

    4、G20峰会明天召开，有报道指日本计划向国际货币基金组织(IMF)借出1060亿美元贷款，援助受创新兴国家，分析指日本希望藉着带领国际救市行动，
拓展外交影响力。

   【简评】麻生这时候放出这种消息来问他的主子要价钱有点不仗义，美国人正巴望着有人帮忙撑美元霸权的场子呢。这下好了，日本人就跟欧盟鬼混去了
。也许麻生认为，现在是摆脱美国控制的好机会。

    接下来我们要看的是，美国人怎么腾出手来修理小日本了。

    5、国务院10日上午在北京召开省区市人民政府和国务院部门主要负责同志会议。国务院总理温家宝发表重要讲话。温家宝指出，中央出台扩大内需促进
经济增长的十条措施，对于克服当前的困难和保持长远的发展都具有重大意义。实施这些措施，总的要求是，出手要快，出拳要重，措施要准，工作要实。“
快”就是要迅速出手，争分夺秒，不可贻误时机；“重”就是要实施坚决有力的措施，从根本上扭转经济增速过快下滑趋势；“准”就是要抓住关键，突出重点，
能起到立竿见影的效果；“实”就是要抓好落实。

    【简评】不得不佩服这一届领导人驾驭局势的高水平。国务院日前提出了扩大内需10项措施，非常及时，也非常到位。

    （1）由于金融风暴对中国外向型企业的冲击，大量的工厂关门、工人失业，现在中国大力上马基建项目，可以吸纳相当数量的劳动力，减缓就业压力，
同时提高整个社会的现代化水平，提升全国人民的福利水平；

    （2）加快建设保障性安居工程（加大对廉租住房建设支持力度，加快棚户区改造，实施游牧民定居工程，扩大农村危房改造试点）。这一行动既保护了
与房地产相关的各个行业，包括建材、钢材、家具、家电等，也通过增加供应的办法直接冲击高房价。可笑的是，在这样的情况下，几个房地产界的“教父”级
人物居然出来歪曲中央意图，误导世人，真是笑话！如果哪个开发商认为楼市回暖了，房价可以接着升了，那只能说明，他离破产不远了。对房地产行业，我
只想再说一话句：中央是救房市不救房价，保民生护银行不保开发商！

    （3）扩大内需是调整整个中国经济结构的最关键一环，它既可以改变我们经济上受制于人的局面，也可以中国老百姓享受到经济发展的成果。这两点，
前者意味着“独立自主”，后者意味着“为民谋利”，从这个角度上讲，胡温是真真正正实实在在为中国老百姓办事的当家人。另外，扩大了内需还可以扩容中国
的市场，加强中国经济的魅力，吸引更多的优秀人才（外来投资就不说了，有没有我们都可以活）。

    （4）大量的基础设施投资必然带动中国重工业的发展，结果中国军工业的大手笔投入可以看出，中国经济正重新走向毛主席时候以重工和军工为龙头拉
动中国经济增长的模式。

    （5）有了这一连串的出手，中国经济可以对全球金融风暴持超然的或者说是置身事外的态度。如果谁拿着中国只有怎么怎么吐血帮助哪些国家脱离金融
危机才能保持自己不受损失的嘴脸来要挟中国话，不妨试试看，倒底谁先死。


** 金鸿时局评论（2008/12/16）
   [2008-12-16 13:36:13]

   
2008年12月15日报道，美国五角大楼官员称，印度正准备空袭巴基斯坦境内的恐怖分子训练营和基地，美国方面正力阻印空军发动袭击。美国五角大楼的3位
官员向CNN透露，美国方面已经获得消息，印度空军部队正在为“执行某项任务”做准备。据悉，印度空军已经进入“警戒状态”。其中一位美国官员称，公开迹
象表明，印巴这两个拥有核武器国家越来越有可能爆发冲突，情况比人们预想的还要糟糕。另一位美国官员则透露，印度已经完成对巴基斯坦境内恐怖分子训
练营发动空袭的初步准备，目前美国正在说服印度对空袭行动保持克制，但印度似乎已经决定发动空袭。

【金鸿评论】近期，围绕着印巴关系各方展开了一轮轮的互动。

就在美国五角大楼好心好意的劝说印度不要对巴基斯坦发动空袭的同时，中国也与印度在新德里举行了中印国防部第二次防务安全磋商。而中巴第六届防务安
全磋商也在北京同时举行。一时间中印巴三国之间你来我往，好不热闹。

就在印巴之间战争冲突可能性不断增大的同时，驻阿联军的后勤补给线也遭到了越来越多的袭击。让美国人不舒服的是，巴西北边境省政府已没有多余的力量
为驻阿联军的补给车辆提供安全保护了，同时，由于遭受恐怖袭击可能性的加大，在阿富汗的巴基斯坦卡车司机15日也拒绝向驻阿北约和美军部队运送补给，
因为“不安全”。看来，陆路补给出问题了，下一步，美国和北约有必要考虑以空运为主来给反恐战士运补给了。

空运应该是最安全的，只不过花销会增加一点而已。

说来也怪，在美国没有开始反恐之前，没听说过世界上有那么多的恐怖分子，自从美国的反恐战争打响之后，恐怖分子是越来越多，而且大有燎原世界之势。
所以，与其说美国是反恐先锋，不如说美国是支恐大本营。

如果从这个角度看看美国军官对调解印巴关系的好意，也许我们会看到另一种解释：

首先，印度“相信”，是巴基斯坦境地内的恐怖分子制造了孟买的惨案；

其实，巴基斯坦境内还有大量的准备对印度再次发动恐怖袭击的的分子没有剿灭，而这些恐怖分子随时会发动第二次类似于孟买恐怖袭击的恐怖事件。

所以，为了保证印度的国家安全，为了保证印度的金融市场稳定，为了保证印度的经济继续发展，不管谁阻挡，基于印度的国家利益，印度都必须对巴基斯坦
境内的恐怖组织进行剿灭；如果巴基斯坦强行制止自己的行动，印度为了自己的国家利益，与巴基斯打一场反恐战争都是必须的！

如此看来，美国军官的调解与其说是“好意”，不如说是“祸心”更恰当一点！如果说得更明白一点，不如说这是在威胁印度：再不对巴基斯坦动手，第二波的恐
怖袭击又会登场了！在这样的背景下，我们印度怎么可能不会对巴基斯坦张牙舞爪？

如果印巴开战，印度的损失我们暂且不管，我们的巴基斯坦通道将会被切断，中国对伊朗的支持力度将会大打折扣，中国在伊核会谈中的话语权和影响力也将
大受影响，所以，协调好印巴关系，保证南亚不起战火对中国而言是非常重要的。所以，中国军方高官访印也就成为了必然。

为了满足一已之私利、不惜把自己的“盟友”推入战火之中，这样的朋友是不可能被人尊重真心支持的，相反，必要时还以颜色也是必须的。所以，我们就看到
了驻阿联军的补给线一再的被袭击的事情出现，而恰恰在美国最需要巴基斯坦“反恐”的时候，巴基斯坦的边境政府却“没有力量”出来反恐了，虽然他们也在积
极的向中央“求援”，可援助却总是姗姗来迟。

现在，面临着选择的主要有两方：

一是印度，是否与巴基斯坦开战？如果不，第二次大规模的恐怖袭击随时会到来；

二是美国，是否停止威胁印度？如果不，自己在巴基斯坦的补给基本都成了送给巴国恐怖分子的圣诞礼物了。

现在，这两方势力都在咬着牙坚持着，看谁最先挺不住了。

应该说，印度是希望和平的，因为战争的风险太大了。所以，在本月14日印度总理辛格才会说：印度希望与巴基斯坦实现关系正常化，但是巴基斯坦首先必须
确保其领土不被恐怖分子用于袭击邻国印度。就是希望巴基斯坦能用自己的行动劝一下美国人，不要再跟自己过不去了。

这场处于战争边缘的争端会在什么方式收场呢？恐怕会让那些唯恐天下不乱的人失望了。来自巴基斯坦的最新消息，巴基斯坦总理吉拉尼拒绝了布朗要求印度
和巴基斯坦允许英国警方盘问孟买连环恐怖袭击案被捕疑犯的要求（或者其它外国调查人员也一样），向外界明确表态，这是印巴之间的事，任何包藏祸心的
第三方都别想横插一杠子！


** 金鸿评论：切莫急病乱投医
   [2008-12-17 08:39:06]


   
    近日，恒大和万科在南京的楼盘因为降价引起的相关问题，将要受到物价部门和房管部门的处罚。日前，南京市物价部门已经向南京万科发出《价格行政
处罚预先告知书》，对南京恒大还在调查中，但是，“查处是不可避免的”。

    可以说王石流年不利，因为错误言论而招致口诛笔伐的事情刚刚平息；为了让公司度过危机而降价售房又惹上了大麻烦：先是售楼处被砸，接着就是自己
的分公司老总被警告——据传，由于万科一直未承诺不降价，某地方一市级高层领导，甚至将万科一名高管训斥了一通，并声称“万科若敢降价，后果自负”。今
天呢，又接到了大额罚单。

    如果那些力保房市的地方政府仅仅是为了保房市的话，他们没有必要对开发商下手——把开发商们搞的心寒了谁还再来投资搞开发？一种比较流行的观点认
为，相当多的地方政府的财政来源主要依赖卖地，一旦房价暴跌，地价必然暴跌，以后的财政来源靠什么？所以，许多地方官成了比开发商还怕房子降价的人
。

     为保房价，各地政府招数连出，甚至有出怪招的，近来传的比较有名的有两件：
　　（1）12月11日，南京江宁区房管局局长周久耕在江宁楼市的“年终总结”上表示，“为防止烂尾楼等一系列连锁反应的出现，房管部门将查处恶意降价楼盘
。”

　　（2）前不久，保利、新湖中宝、万达、华润等22家开发商在沈阳市组成不降价联盟，承诺一年内不降价。同时，铁西区区长李松林表示：区政府将先期
预存500万元，对参加联盟承诺不降价的开发商因此造成的损失给予赔偿。

    对于这两件事，特别是前一件，闹的是沸沸扬扬。民间对周局长的回报是：有人人肉搜索出周局长在会议上抽的是1500元的“95至尊”。

    对于第二件事，可以说，地方上那点补偿真不算什么，500万不过十几套房子的价格（好象沈阳的房价在四千左右），随便哪个项目卖到尾盘剩点房子都
比这个数大。如果开发商真的因为不降价造成了损失，恐怕这个数再加两个零都补不过来。再说，那些钱都是老百姓纳税的钱，公然拿公钱补私利会引发什么
后果？还是惦量一下的好。

    当然，许多地方这么多也是迫不得已，一旦财政收锐减，以后的日子是很难过的。不过，以上的办法能起到遏制房价下降的作用吗？

    答案是否定的。原因有二

    其一：用非常手段保房价，有悖于市场规则且不说（我对市场这玩艺没感情），仅仅对开发商的剿杀能力，就是非常可怕的。据中国房地产及住宅研究会
等测评，2007年，万科、保利、富力、中海等12家重要房地产开发企业的土地储备高达3亿平方米，如果按2007年的开发速度，消化这些土地储备需要5年以上
时间。现如今房市日趋低迷，销售回款减慢，则需要更长的时间来消化这些土地。如果各地都用非常手段，那也许10年、15年都消化不完这些土地。根据现行
的用地政策，两年不开发就要收地，那时，开发商就赔得更惨了。再就是，如果开发商自己手里的地都消化不了，那怎么可能有钱再买地呢？一旦土地的需求
量大量减少，反而会造成土地价格的进一步暴跌，所以，非常手段损害的极有可能是自己！

    其二，也许可以用非常手段做到让开发商不降价，但谁能做到让老百姓心甘情愿的在高价位掏钱买房？今天的开发商们只所以降价，就是因为在高价位上
无人买房，开发商不得不降价刺激需求，不然，谁会跟利润过不去？现在，如果用行政手段阻止房价下跌，只会让打算买房的老百姓形成更强烈的降价预期，
结果只能是有价无市！最后先撑不住的，肯定是开发商！（市场经济下，现金为王。）当然，如果在这种情况下还想保房价，只有最后一招了：银行输血。那
可是犯中央的大忌的，这个可要惦量一下了。

    另外，不得不说明的一点是，高房价是变相掠夺普通老百姓财富的最快捷手段。现简单分析如下：

    假如中国目前总的财富存量是100万亿人民币，中国70%的普通老百姓拥有总财富的20%即20万亿，现在，在每年这70%的人需要28亿平方的住房（即每年每
人需要3平方），那么在下面几种模拟的情况下，老百姓手里的财富数量将会有巨大的差别：

    平均房价1000元/平方时：每年普通百姓花在住房上的总款为2.8万亿，老百姓手里可以剩17.2万亿；

    平均房价3000元/平方时：每年普通百姓花在住房上的总款为8.4万亿，老百姓手里可以剩11.6万亿；

    平均房价7000元/平方时：每年普通百姓花在住房上的总款为19.6万亿，老百姓手里可以剩0.4万亿；

    也就是说，当平均房价到了7000元/平方的时候，只需要一年的时间，70%的普通老百姓手里基本没钱了。这基本可以解释，为什么许多城市大量出现房奴
的原因。

    当然，以上的分析仅仅是个模拟，中国的总财富倒底有多少？财富在各阶层的分配比例倒底有多少？我都不是很清楚，所以，这个分析未必准确，它只能
在一定程度上说明一点问题，仅此而已。

    不过，上面的分析还是基本上说明了高房价对老百姓财富的强大掠夺能力。由此也可以看出，广大老百姓对高房价的深恶痛绝。所以，那些准备用非常手
段救市的地方政府要注意一下了：这些做法极有可能招致民怨沸腾，甚至出现群体性事件。这就得不偿失了。

    综合一下可以得出结论，非常手段保房价只会适当其反。相比之下，倒是深圳的做说比较好：

    曾深圳市地方政府公开表示不会出台救市政策，结果在中央系列政策的刺激下，反而成了近期市场上的成交先锋。

　　据统计，11月深圳全市商品住宅成交套数为6039套，成交面积为55.41万平方米，成交金额69.29亿元。而10月份深圳新房成交总套数为3483套，成交面积
为34万平方米，成交金额43.2亿元。11月的成交量较10月增长73%。出现成交量大幅增加的原因是住房成交价在下降——11月深圳房地产市场成交均价为每平方
米12506元，环比下跌4.48%。国家发展和改革委员会公布的11月全国70个大中城市房屋销售价格相关数据显示，深圳新房价格同比下降18%，环比下跌2.4%。

　　其实，价格是市场供求的天平，价格下降必然会刺激需求增加。这是最基本的市场规律。在现行的市场经济条件下，按市场规律办事、因势利导才会取得
满意的效果。

   在许多情况下，无为而治是最好的。


   

** 金鸿时局评论（2008/12/18）
   [2008-12-18 11:07:49]

   
    潘基文秘书长星期三（17日）在纽约总部举行的年终记者会上表示，过去几个月中，他一直在按照安理会的要求就组建一支多国部队处理索马里问题积极
接洽各国，但目前他的努力尚未取得成果。

    【金鸿评论】按照潘大人的说法，大家都认为，“目前部署维和行动的时机还不成熟，仍缺乏有利的条件”。

    怎么才算“时机成熟”了呢？是不是潘大人的老婆去非洲旅游被海盗抓了之后就时机成熟了？

    至于潘大人嘴里的“缺乏条件”，是缺乏什么条件呢？是不是缺乏某个大国因为自己的非洲司令部没着落所以不愿意带头出力这个条件？如果因为区区小事
就不愿意负责任的话，中国可以很愿意出一把力的。12月16日，中国外交部副部长何亚非就在联合国安理会索马里海盗问题部长级会议上表过态，中国正积极
考虑近期派军舰赴索马里海域参加护航活动。

    既然某些人喜欢讲条件，不给好处就不干，那我们可以干，不计回报，不图名份——中国将向索马里海域派出由两艘驱逐舰和一艘大型补给舰组成的舰队，
执行维护国际海运安全的任务。这支舰队将在西方的圣诞节之后从海南三亚出发，第一阶段的任务期大致为3个月。

    不知道此刻潘大人还在调强各种各样的困难是何居心呢？非要非洲兄弟同意美国把司令部安下了才具备了条件、成熟了时机？如果真是这样的话，我们不
禁要怀疑：这是为了打击海盗，还是为了扩充地盘？如果再想的远一点：那些近几天才冒出来的搞的满世界都出了名的索马里海盗究竟是何来路？是不是某些
人在养寇自重？

    也许，让某些人非常不爽的是，一向低头韬光的中国居然要派海军远赴重洋了！我们绝对相信，只要中国海军过去了，凡事第三世界国家的货船有难，中
国海军一定会出手。如此一来，好象离了布屠夫，大家照样可以不吃连毛猪了。

    中国这个局搅的好！够劲！


    

** 金鸿时局评论（2008/12/19）
   [2008-12-19 11:58:15]

   
据报道，中国周三对美国提出警告，如果美国不抓住时机进行必要的经济改革，中国可能会停止继续购买美国国债。

看到这则消息给我的第一感觉就是，中国终于正面出手了。在过去的几个月里，为了挽救美国的金融体系，美联储采取了疯狂印刷美元的办法来保护美元霸权
。，虽然美联储在疯狂的开动印钞机，但是，由于中国依然在大量的买入美国国债，支持着美元和美国国债的信用，从而给了美国进行自救的支撑点。如果这
种局面持续下去，极有可能让美国度过此难关，所以，在这个关键时刻对美国出手，拿它一把才能让我们有所收益。

如果中国真的拒买了美国国债甚至抛售美国国债，由于市场信心的欠缺，美国国债极有可能被市场疯狂抛售，出现美国国债殖利率的上升的情况，由此也会引
发美国市场长期利率的飙升，如果真的出现了这样的局面，美国的金融衍生产品市场将彻底崩溃，美国经济也将万劫不复。

在这样一个恶劣后果的参照下，美国必须拿应中国的某些条件了。那么，现在中国最想要的是什么呢？

还是通过观察中国与欧盟之间的斗争来分析一下吧。

按北京最初的打算，是在华盛顿金融峰会上出工不出力，把欧盟力推的欧元夺权的努力给架空了，以此后果逼迫欧盟在改变全球金融规则方面对我们做出某些
实质性的让步。

但是，结果并不太如意。欧盟在金融峰会上一票也没有捞到之后恼羞成怒，立即把峰会之前的“萨克奇会见达赖”的事情做实了，狠狠的恶心了一把北京。当然
，为了展示自己的团结和强硬，欧盟对中国进行了先发制人的警告——12月3日欧盟委员会反倾销部门投票决定对产自中国的碳钢紧固件产品征收高达87%的反倾
销税。欧盟对中国的这种报复行为并没有太多的实质意义（不管是会见达赖还是对华的经济制裁行为，因为在目前的危机之下欧盟撑不住一场经济战），却让
中欧之间的裂痕撑大了。直接结果就是美国得利——美元获得了更多的喘息机会。

当然，北京也没有丝毫手软，一方面口诛笔诛，一方面展开了经济报复。北京的目的很简单，就是希望用最快的速度解决欧盟，逼其低头就范。没想到欧盟死
扛，坚决不对北京让渡权利。

无奈之下，为了让欧盟真正看到后果的可怕，中国高调在周边推销人民币——目前，中国已经与包括俄罗斯、蒙古、越南、缅甸等在内的周边八国签订了自主选
择双边货币结算协议。特别是12月12 日，中国人民银行与韩国银行签署了一个双边货币互换协议，两国通过本币互换可相互提供规模为1800亿元人民币/38万
亿韩元的短期流动性支持。

现在，欧盟需要考虑一下了：一个美元还没有扳倒，如果再起来一个人民币，欧元的未来会是什么？我们可以毫不谦虚的承认，人民币要比欧元有竞争力。

也许我这样说，会有许多人不以为然，甚至认为我在说大话。因为欧盟的经济实力要远强于中国。但是，经济实力并不是决定一种货币成为全球硬通货的最重
要条件，否则，日元早就不是今天这个样子了。

其实，不知道大有想过没有，决定一国货币成为全球硬通货的最重要条件是什么？

在回答这个个问题之前，我们首先需要搞清楚一点，货币的本质是什么？是信用。在法币条件下，对于任何一个国家来说，这个国家发行的货币都是依靠国家
信用来支撑的。所以，本国国民出于对国家信用的信任，才会愿意无限量的持有本国货币。如果本国货币在本国国民心目中失去了依任，照样会被“拒收”——表
现形式就是把本国货币换成实物、他国货币、贵金属、珠宝、古董字画或者其实可以被人们广泛接受又有保值能力的东西。

同样，一个国家的货币为什么能被其他的国家广泛信任并愿意大量持有呢？同样是因为信用，因为这个国家可以信任。一个国家被其他国家信赖的最重要条件
是什么？是武力，是军事实力。这才是支撑一国货币的根本所在。信用只在大炮的射程之内。所以，任何一个国家的货币如果真正想成为全球硬通货，它必须
有强悍的军力。这才是人民币比欧元更有竞争力的原因。这个竞争力靠的是共和国建国的头三十年我们英雄的子弟兵用生命和鲜血打出来的，是那一代领导人
英明神武拼出来的。说到这里，大家可以很容易的理解为什么空袭南联盟都能把欧元炸瘫、把美元打强的了，不就是因为欧盟没有强大的军力而美国拥有吗？

现在，人民币加大了扩张的力度，就是做给欧盟看的，如果再不对华妥协，将来再想妥协都没有机会了，因为那时人民币已经壮大了，不再需要欧元作战略掩
护了。不过，这样做的副作用也是很大的，因为这样会吸引美元攻击力，把人民币变成攻击的靶子，给欧元减轻轻压力。所以，对人民币而言“广积粮、缓称
王”才是上策，不过，在今天火烧眉毛的情况下，不得不为了。

中国今天的经济状况到底有多艰难，我没有第一手的数据，不过，从温总理刚刚出台的房地产救市政策看，中国经济是非常艰难的。因为中央不但给二套房松
了绑，还允许有条件的部分房地产企业输血！给二套房松绑极有可能把房价重新炒起来，给部分房地产企业输血也有可能增加他们扛着不降价的耐力，所以，
这两条有可能引发的一个后果就是房价回升。

从过去的行动来看，胡温的本意绝对是把房价打下去，不过，在金融危机严重冲击中国、造成大量外向型企业破产的背景下，如果强行打压房价，把曾经的经
济支柱——房地产业也打死了，会再拖垮大量的相关行业企业，比如钢铁、建材等，会让中国经济举足维艰。而一量中国经济减速太猛极有可能出现社会动荡，
这个道理很简单：一辆以120公里/小时高速行驶的客车猛然减速到60公里/小时时，车里的所有人都会重心不稳，甚至有人会被惯性扔到地上去。为了防止因
为中国经济减速严重造成的恶劣后果，减小一点打压房价的力度甚至扶持一下房地产企业都是不得不做的事情。

不过，这样做的副作用是很大的，一旦把房价调头回升，让那些困在一线城市房地产市场上的热钱解了套，中国的房地产市场可就到了彻底崩溃的时候了——以
前的房地产泡沫在不断增大，就是因为不断的有的热钱进来炒作，现在如果大量的热钱抽逃，只会让房价暴价，因为接盘的资金大量减少了。那时，才是中国
房地产行业的悲剧，也是中国经济的悲剧，更是中华民族的悲剧。

在此，不得不提醒那些对房价抱幻想的开发房和那些救市不择手段的利益相关者一句，一旦房价回升让热钱跑掉了，中国的房市将成劫不复，你们（特指那些
高负债的开发商们）也将尸骨无存。所以，借着中央的救市春风，赶快降价卖房回拢资金才是上上策，温总理在部署的促进房地产市场健康发展的政策措施中
明确指出，“要引导房地产开发企业积极应对市场变化，促进商品住房销售”。这句话如果说的直白一点，就是“赶快降价！”

当然，现在房地产企业也大都扛不住了，所以才会有代言人出来高呼“现在买房就是爱国！”事实求是的说，这句话有一定的道理。在现在的形势之下，买房可
以让稳定房地产行业的资金链，从而维护房地产上下游行业的健康发展，这对国家和民族都是有利的，所以，可以说是“爱国”。但是，既然老百姓买房是爱国
，那某些开发商和利益相关者死活扛住房价不降让老百姓买不起房是什么行为？是不是“害国”？从上面的分析可以看出，房地产行业事实上已绑架了中国经济
，并且在一定程度上左右着中国的内政外交政策。可惜的是，太多的人只顾自己的利益不顾大局，这样的结果最终将是害人害已。

就在中国正面打击欧盟的同时，中东方面的形势对欧盟也越来越不利。

近日来中东局势也是风云巨变，在上月25日时，正在美国访问的以色列看守内阁总理奥尔默特还说，以色列和巴勒斯坦能在不久的将来就双方争端中的“核心
问题”达成协议。因为“以巴双方现在对重要问题的看法非常接近，已经到了该做决定的时候。”

仅仅过了九天，、以色列外长利夫尼就在在7日举行的内阁会议上呼吁重新对加沙地带停火形势进行评估。理由是哈马斯在加沙地带的统治是以色列“难以容忍
的”，他主张对发射火箭弹的人员采取行动，并对加沙地带实施经济封锁。

面对着以色列的咄咄逼人，伊朗也毫不客气的接招了：伊朗红新月会10日在德黑兰表示，他们会将向被以色列封锁的加沙地带运送价值10万美元的救援物资，
以缓解那里的人道主义危机。并且话中有话的强调了一句“这艘货轮很有可能在中途被以色列军方扣留” 。看来，两家子都不是怕事的主。

一旦巴勒斯坦地区大乱，最先受冲击就是欧盟和他们的地中海计划，所以，美国（含以色列）和伊朗（含真主党、哈马斯）的行动是冲着谁来的，那就不必多
解释了。当然，伊朗还是唯恐欧盟不明白自己的意思，专门紧急召见法国驻伊朗大使，“抗议法国总统萨科齐对伊朗总统内贾德的批评性言论。”

为了防止欧盟倒戈，12日以色列又弄出一则报道，宣称美国候任总统奥巴马承诺向以色列提供核保护伞，以避免其受到来自伊朗的核威慑。其目标不外乎是警
告伊朗规矩一点儿——欧盟是我美国大爷可以吓唬的，又岂是你小小伊朗能恐吓的吗？你还是自保吧。其实，美国人的核保护伞好象是谁都可以送的的，上世纪
八九十年代，美国不也对中国提供过一把吗？面对美国的恐吓，伊朗继续做自己该做的事。

16日，内贾德指桑骂槐，打着抨击萨科齐“蛮横”旗号，继续重申“绝不会承认以色列”。与内贾德一唱一合的是黎巴嫩真主党总书记纳斯鲁拉，他在前一天晚上
（15日）发表视频讲话，强烈谴责以色列封锁加沙。

伊朗和真主党的“劝告”并没有换来欧盟的回头，于是，在17日加沙地带的巴勒斯坦武装人员向以色列南部发动了火箭弹袭击，紧接着，哈马斯18日在一份发给
媒体的声明中正式宣布，该组织与以色列之间的停火结束。

看来，搅黄地中海计划的行动各方真的是不遗余力，现在也到了欧盟做出选择的时候了。同样，面临着中国强烈警告的美国，也该有所表示了。


** 金鸿时局评论（2008/12/21）
   [2008-12-21 18:30:25]

   
     石油输出国组织（欧佩克）轮值主席、阿尔及利亚能源和矿业部长沙基卜·哈利勒１９日在伦敦参加一次能源会议时说，欧佩克各成员国将继续减产，
直到原油价格稳定。欧佩克１７日宣布从明年１月１日起削减原油日产量２２０万桶，从而使该组织从今年９月起的日均减产额度达到  ４２０万桶。不过
国际市场原油价格并未出现反弹。１９日纽约商品交易所１月份交货的轻质原油期货价格收于每桶３３．８７美元，比前一交易日下跌２．３５美元，处于
近５年来的最低点。沙特阿拉伯石油和矿产资源大臣纳伊米１９日表示，每桶７５美元的价位“公平合理”，低于这一水平的价格将导致更多不稳定因素，并
将影响投资者信心。英国首相戈登·布朗当天也呼吁各方采取措施防止油价剧烈波动，认为油价剧烈波动不符合任何人的利益。

     【金鸿评论】这一轮斗争可真激烈，原油市场上也是狼烟四起。在今年年初的时候，纽约市场油价突破了每桶100美元大关，到7月11日，原油价格达到
了天价每桶147.27美元，到现在，居然跌到了区区33美元。

     在油价高涨的时候，美国说涨价的原因是供应不足造成的，并且逼着欧佩克减产。现如今，欧佩克已连续两次减产，油价却丝毫不见抬头。这倒底是为
了什么？难道半年羊的石油的需求是今天的几倍不成？从油价走势与欧佩克减产之间的关系来看，我们实在找不出除了操纵市场之外的其他原因可以解释这
种现象的了。 很显然，从年中开始的油价暴跌是冲着俄罗斯去的，今天欧佩克连续两次减产、并且声称要“继续减产直到原油价格稳定”背后也是依靠俄罗斯
做的支撑。区区几个石油输出国，还不敢挑战美国。

      这是一场围绕着石油定价权展开的战争。战争的两个主角一个是美国，一个是俄罗斯。美国希望的是把油价打下去，干脆利索的摆平俄罗斯后好腾出
手来收拾中国和欧盟；俄罗斯希望的是把石油定价权夺过来（表现形式是把油价拉起来或者用俄罗斯希望的方式来结算石油价格），不然自己的命运将始终
掌握在别人手里。

     这一场战争美国输不起，没有了石油定价权，美元就成了天空中断了线的风筝，控制权全失；同样，俄罗斯也输不起，油价被持续的打下去，要么自己
对美国让步，要么外汇储备耗光，无论哪种结果，都将把普京变为无牙老虎。所以，双方必将全力以赴。

     美国依靠的是资本的力量，所以，欧佩克越减产，油价越是“报复性”的下跌，俄罗斯则依靠自己的军力和能源供应能力，怂恿着欧佩克减产。

     在美俄斗法的过程中，大多数的欧佩克国家都是被迫加入战场的。所以，在这场斗争结束之前，欧佩克国家都是无奈的受害者。所以，欧佩克中的产油
大户沙特阿拉伯才站出来弄了个所谓的“公平合理”价位，其目的只有一个，希望双方在这个“公平合理”的价格下停止争斗，否则，自己和一帮子小兄弟全得
跟着坐标过山车。在这样的背景下，我们再来看布朗的呼吁，就有点嚼头了：表面上看是各打五十大板，但不要忘记了，美英的石油资本是一有人，所以，
布朗的劝和其是不是针对的美俄，而是欧佩克成员国——不要跟着俄罗斯起哄了，你们再减产油价也不会涨，还是把俄罗斯架空了之后，油价会涨回去的。

      其实，这一轮的油价暴跌对美国也没什么好处。不说别的，光自己超量发行的美元纸币往哪里存都是个问题——油价跌意味着用美元结算的美元需求会
减少。所以，这也在考虑美联储“藏钱”的能力——如果这些美元藏不好流通到了美国的国内市场上（再加上为了救市美联储海量印刷的纸币）会引发恶性的通
货膨胀加剧美元汇率的下跌，从而加快美元霸权地位的终结。不过到目前为止，美联储玩技术玩的很漂亮，美元近期不是还有所升值吗？不过，总有纸里包
不住火的时候，这也是俄罗斯寄希望于可以咬牙挺过去的关键所在。

     再加上觊觎美元霸权的还有欧元、日元和人民币，甚至巴西都想借机揩美国的油，俄罗斯当然有理由坚持对抗下去；同样，如果不能杀熊吓猴，美国以
后的日子更没法过，所以，美国也必须坚持打下去。

     既然战争的双方暂时都是受害者，那受益者是谁？当然是石油进口国，特别是中国。不说别的，看看中国的外汇储备吧，今年7月时18000亿美元，那时
的油价是140一桶，只能买130亿桶，可如今呢，石油40美元，能买450亿桶，半年间翻了两个跟头。这小财发的......让人都不好意思说了。

当然，这要感谢北极熊的努力。所以，以后看着北极熊有所不支的时候，我们要适当拉一把，以增加熊力。

    现在的形势是：美国略占优势，所以，大熊，上去咬它！


    

** 【金鸿评论】打铁还需自身硬

   [2008-12-23 16:16:05]

   
为进一步落实适度宽松的货币政策，中国人民银行决定：从2008年12月23日起，下调一年期人民币存贷款基准利率各0.27个百分点，其他期限档次存贷款基
准利率作相应调整。同时，下调中央银行再贷款、再贴现利率。

【金鸿评论】中央稳定经济的动作是重拳频出。就在昨天，国务院办公厅刚刚出台了《关于促进房地产市场健康发展的若干意见》，要求房地产开发企业要
根据市场变化和需求，主动采取措施，以合理的价格促进商品住房销售。为什么中央的调控动作如此之密急呢？还是先看两条似不相关的新闻吧：

据伊朗通讯社报道，伊朗政府说，为加强伊朗保卫边界和防空力量，俄罗斯将向伊朗提供先进导弹系统。

莫斯科12月19日消息：据俄罗斯媒体报道，俄罗斯石油公司总裁谢尔盖·博格丹奇科夫认为，与合作伙伴向卢布结算方式过渡，研究实施这种可能性的各种方
式是"非常有前途的"。

【金鸿评论】关于是否卖S300给伊朗的事情也不是第一次炒作了，在这个档口上，俄罗斯又把这件事翻出来是为什么呢？

其实，俄罗斯卖S300给伊朗是虚的，是在制造问题。目的呢，是向美国要价的。俄罗斯的开价不高也不低——石油定价权。前天在分析俄美石油定价权的争权
时，得出的结论是俄罗斯暂时处于劣势，所以，俄罗斯必须得反击。

果然，吃了亏的北极熊下了手。要卖S300给伊朗。当然，这只是手段。俄罗斯的目的就是要把石油定价权抢过来——要么油价重新升起来，要么默认俄罗斯用
。表现形式用卢布结算出口的石油。

当然，俄罗斯卖S300给伊朗引发的一个直接后果就是伊朗有了更加强硬的本钱，这必将削弱欧盟在伊朗六方会谈中的话语权，因为伊朗的自我保护能力增强
了，欧盟的协调人能力就不再那么重要了。此举也是在逼欧盟一把，逼不愿意向南方国家（包括中国俄罗斯）让渡金融权利的欧盟赶快行动，大方一点。

就在这时，中东方向还传出了一条新闻：

以色列外长、前进党主席利夫尼21日表示，她如果能够在明年2月的大选中当选总理，将会结束巴勒斯坦伊斯兰抵抗运动(哈马斯)在加沙地带的统治。

【金鸿评论】虽然这个利夫尼是个娘们，不过够狠，看来她想把哈马斯那帮穷弟兄赶到地中海里去，不过不知道哈马斯那帮弟兄会不会游泳。记得一年以前
哈马斯还招过一回海军，不知道招成了没有，当时的条件就是：“会游泳就行”。看来今天这本事用上了。

以色列有人跳出来刺激哈马斯那帮急炮仗的目的无非是为了激化巴勒斯坦局势，拖一把地中海计划的后腿。结果自然是警告欧盟，不要反水！要知道，18日
时哈马斯等四个巴派别就在加沙地带宣布，与以色列达成的停火协议正式结束，不再延续。看来，信奉枪杆子里面出政权的不止我们中国人。现在，不管是
以色列，还是哈马斯，都想玩硬的了，这可有看头了。

以色列的金主是美国，哈马斯的后头可是伊朗叙利亚，伊朗叙利亚的保护神则是中俄。两边同时想在中东激化局势，挤压地中海联盟，无非是逼欧盟往自己
的阵营里靠一下。

这个前怕狼后怕虎的地中海计划，铸定是个姥姥不亲舅舅不爱的怪物，人人欲除之而后快。这也没办法，谁叫欧盟一盘散沙没有强悍的武力呢？

大国斗争的焦点向来是权利。这个权利是什么呢？在今天，主要的表现形势就是金融霸权。因为现在这个霸权在美国人手里，所以，现在中国俄罗斯和欧盟
纷纷冲着美国人捅刀子，不为别的，想抢俩小钱花花。

现在在次贷危机搞的火烧连营的今天，大家的日子都不好过。个个着急。俄罗斯不惜再次翻出卖S300给伊朗就是一例，当然，中国也很着急，如果不着急，
为什么连续的出台稳定经济的政策呢？

21日国务院办公厅发布的《关于促进房地产市场健康发展的若干意见》明确要求房地产企业主动采取措施，促进商品房销售——中央要房企搞“促销”了，现实
生活中大家对“促销”见多了，不就是降价吗？

这也和我前几天写的那篇分析中央为何出台新的房产政策的文章考虑的吻合了，新的房产政策的确是要求房企“赶快降价”。出乎意料的是，这次中央说的这
么直白。可见情况紧急！

中央希望的是，近快让房市软着陆，因为过去中央已采取了一连串的促进消费者买房的政策了，但是如果开发商不降价配合，这些政策也很难起到效果。但
是，如果市场这么僵持下去，半年后会死大批的房企，相关产业的企业也会倒大霉。那时，中国经济只能硬着陆了。现在，中央出手是为了尽快把房价拉下
来，补平市场供求之间的裂缝，从而可以加快中国经济的转型速度，提高中国经济的活力。

当然，再次降息也许房地产有关——降息意味着买房贷款的还贷压小减小，这样会刺激住房的消费。当然，降息还有两个作用：增加流动性，缓解企业的融资
成本，帮助企业度过难关；降低热钱对人民币套利的预期，稳定中国的金融秩序。

如果上述目的都实现了，那么，结果就是人民币更加坚挺。人民币强势又会进一步促进中国经济的转型，形成一个良性循环。

如果没有外力的逼迫，中央不会对调控经济（包括房市）如此的着急。那么，这个外力是什么呢？看一条早一点的新闻：

华盛顿16日消息：美联储在美东时间周二下午宣布至少降息七十五个基点，将联邦基准利率从百分之一，降至零至百分之零点二五之间的范围。这使得美国
利率降至历史最低点。

【金鸿评论】近几个月来，美国采取了极不负责任的救市政策，疯狂的印钞票。为了避免一伤俱伤的结果，中国一直在买美国国债支持美元信用。到现在，
美国要挺而走险！部分启动“开面全动印钞机”的行动，试探各方反应，应该说，这是非常危险的。如果真让美国人成功了，不说别的，光把这部分海量发行
的没有任何抵压作背书的和真美元一模一样的绿纸中的一部分弄到第三世界国家（甚至日本印度）去，收购了这些国家的企业，也就完成了美国以假骗真的
行动，也就完成了次贷窟窿的填补工作。

下面具体解释一下：一个国家发行货币是要有东西做抵压的。比如金本位时代，被低压品是黄金，也就是说，发行多少纸币，就要有多少黄金存着，拿纸币
的人随时可以把纸换成黄金。在法币时代，靠的是国家信用，欧美国家的央行以国债作抵压发行纸币也算是靠的国家信用，因为国债就是以国家的信用作支
持的，

不过归根到底，纸币的真正抵压品是本国的实物产品，其他的都是假的，黄金也不例外。如果一个国家生产的实物没有增加，黄金突然海量增加了，结果依
然是通货膨胀，打个比方，本来一个国家一年生产一亿个馒头（所有的东西都折算成馒头，这样好说明情况）这个国家有1百万两黄金，以此数量的黄金为抵
压发行了一百万元的纸币。现在，一两黄金能买一百个馒头，一元相当于一两黄金。如果现在这个国家的生产能力没有改变，突然黄金数量暴增，成了一千
万两，现在，一两黄金只能买十个馒头，不要认为这种情况不会出现，最初跑到美洲新大陆新了大批金银回国的欧洲国家就出现了这样的情况。他们抢到了
大量的黄金，可是国内的生产能力没有增加，所以物价暴涨。这也验证了了马克思的理论：货币只不过是一般等价物，能够标明实物的价值却代替不了实物
。

现在的美国，在生产能力没有多大改变的前提下，现在为了救市大量的增发了纸币，这些纸币其实是没有任何抵压品的，所以其实是假币，这些假币的唯一
真实作用就是向以前的真币里渗水——制造通货膨胀。但是美联储的金融技术高，把这部分多发行的纸币冻了起来，而没有进入流通领域，所以从外表上看不
出来，美国也没有出现严重的通货膨胀。但是，这些纸币迟早要进入流通领域的。当然，进行流通领域的可能性有两种：一是联储纸里包不住火了，结果是
美国暴发恶性通货膨胀，美元贬值，美元霸权加速瓦解；二是美国暂时稳定了国内经济，美元还没有贬值，美国人把这部分钱拿了出来，当然，这些钱以被
救助企业的企业资本的面目出现。因为美元一直是国际硬通货，在这时美国大企业把这部分假币拿出来收购他国企业，谁也不能说它们就是假币吧？但一旦
收购成功了，美国就完成了假币换实物的过程。这个过程充分完成之后，美国的次贷窟窿也就补好了。

现在，是个关键的口子上，美国人开始玩险了。一旦成功了，次贷“危机”也就变成了次贷危“机”，美国不但倒不了，反而会借机攻城掠地。所以，必须破掉
美国的这个阴谋，但是，怎么破解呢？关键就是压住美元霸权，不给美国喘息的机会。所以，中国和俄罗斯双双出手了。

当然，美国也不傻，也同时在向各方出手了：

对付俄罗斯，就是把油价往死了打，俄罗斯好容易在后台操作了一把，让欧佩克把产能降了降，结果是美英操纵着石油进一步暴跌；

对付欧盟，就是利用巴勒斯坦局势的转向，挤压地中海计划；

对付中国，则是在印巴地区搞乱子。可恨的是，印度居然配合美国玩险。可能印度建国建的太容易了，所以亡国也不知道心疼。现在在克什米尔玩火的后果
是什么？这完全可能要了印度的命！可他居然还敢折腾！当然，中国对印度的警告是在行动上的，23日上午，在西昌卫星发射中心把 “风云二号”06星送入了
入了预定轨道，监视青藏高原和印度洋地区的情况，并且解密了部分可以干掉阿三地面部分的武器装备。

普京是个硬汉子，毫不客气的还以颜色，一面武装伊朗回报美国，一面强推卢布——既然美元计价的石油价格涨不上去了，那就直接用卢布好了，为什么现在
不提欧元了？因为欧盟不放权，所以不能给他好处。

当然，美国也在拿搞乱巴基斯坦吓唬我们的巴铁——22日巴基斯坦西北部部落地区当天发生一起导弹袭击事件，至少造成7人死亡。巴官员说导弹可能是美军发
射的。不过希望美国还是悠着点儿好，不然，伊朗核问题再起波澜也是很正常的，因为伊朗的粮道要断嘛。如果伊朗真有大动作了，那第一个跳出来妥协的
还是欧盟，那时中俄的要价就是部分让度金融权利，结果将是美国人自己搬石头砸自己的脚。

现在，要想破美国的局，俄罗斯的配合已经可以了，伊朗有必要跳一下，最关键的，是中国自己要争气。什么意思呢？卡住美国的脖子不给他暂时喘息的机
会——现在美联储疯狂的印钞票希望缓和经济恶化的局面，如果他缓和了，他就可以用多印的纸币去国外搞收购了，但是，只要美国经济持续恶化，他就没有
机会去那么做！

为什么前一阵子人民币要贬值？一国货币贬值的直接后果就是出口产品的竞争力增强，进口货更加昂贵，所以，人民币贬值有利于中国顺并，美国则会持续
逆差。如此一来，美国的经济状况只会更加恶化。同时，中国还要把自己做强，做强人民币的实力和影响力，只有这样，才能冲击美元的霸权地位，同时警
告欧元，再不配合老子就不甩你了。怎么才能做到增强人民币的实力呢？前面分析过了，尽快把房价拉下来，保证国民经济的正常运转，进而加快中国经济
的转型速度，提高中国经济的活力。


** 金鸿时局评论（2008/12/25）
   [2008-12-25 10:56:52]

   
    谢谢朋友们送的电子礼物！

    1、德国《法兰克福汇报》22日头版以“柏林要收容关塔那摩囚犯！”为标题披露称：德国外长施泰因迈尔证实，奥巴马已表示，将在两年内关闭关塔那摩
监狱。德国准备收容关塔那摩监狱的囚犯，其中包括17名中国“东突”分子。该报称这是德国政府“团结奥巴马”的举动。

    【金鸿评论】在中交交恶、中欧关系紧张的今天，德国站出来刺激中国是别有深意的。不过，说这是默克尔看上了帅哥奥巴马有点冤枉她了，其实是老
女人在拉萨克奇一把。

    现在，中国把报复的火力集中在了法国身上。德国也怕法国顶不住，在原来立场上做太大的后撤、进而损害整个欧盟的利益，主动出手攻击中国来分解
法国的压力。

    的确，萨克奇见达赖有替法国自己的国家树威信的意思，但是，他同时也是在替欧盟争好处，所以，同为欧盟核心国家的德国出来替法国扛一把也是在
显示一下欧盟的团结和自己的“责任心”。

    所以，在目前的情况下，北京不应该分散精力，对德国的挑衅，以口水战对应之；对法国，继续狠揍，直到他趴在地下叫“大爷”为止！

    2、据俄罗斯《独立报》报道，格鲁吉亚外交部长瓦沙泽12月22日宣布，第比利斯和华盛顿将于12月23日最后磋商涉及安全、经济、人文和民主化领域内
合作的两国战略伙伴关系文件，其框架协议将在2008年年底前签署。

    俄罗斯大使谢苗·格里戈里耶夫20日透露，该国与阿布哈兹可能在未来几周签署军事合作协议。他指出，“军事领域合作和共同警卫阿布哈兹共和国国境
协议将是双方希望近期签署的首批文件之一”。

    【金鸿评论】对于美格之间的战略伙伴关系文件的签署，按某些“格鲁吉亚政治评论家”的说法是这样的：与美国的合作会规定美国人在格鲁吉亚的存在
，从而敦促俄罗斯放弃侵略行动。”

    可惜，俄罗斯太不给面子，不但没有放弃侵略行动，反而加强了在“阿布哈兹共和国”国境上的警卫，不知道面对着侵略了自己盟友的俄罗斯，美国有没
有胆量和能力跟俄罗斯打一仗呢？

    “兴灭国、继绝世、举逸民，天下之民归心焉。”这可是美国捞资本的好机会呀。上一次奥运会期间本该属于美国人出风头的机会让布什错过了，这一次
就看奥巴马先生的了。

    有人说：奥巴马是哪棵葱呀？这颗葱可不简单，天下的葱都是白皮的，就他，黑皮的！

    抓住机会哟。

     3、一家美国情报咨询机构在一份最新报告中说:“印度对巴基斯坦境内目标的军事行动,实际上早已箭在弦上”、“印度极可能对巴基斯坦控制的克什米尔
境内目标,采取单方面的空中精确打击,地面特种部队同时越境攻击”。

    【金鸿评论】据美国媒体报道，印度总理辛格12月23日发表言论试图缓和印巴双方关系的紧张局面。辛格表示:“没有人想要战争。”

    什么叫皇帝不急太监急？看看美国那些狗头军师就知道了。

    印度是想捞一把，但他清楚的很，那一把不是打一仗打出来的，而是吓唬中巴吓唬出来的。如果真动上手，绝对是得不偿失的。

    在过去的几天里，北京已经为可能暴发的战争做好了足够的准备：风云上天，大预出嫁，火炮制敌…在这样警告之下，一惯喜欢非暴力不合作的印度人还
有胆量动手吗？还是在媒体上过过嘴瘾算了，那样的话，不管怎么吹都忙不了国。

    4、哈萨克斯坦总统纳扎尔巴耶夫23日签署了关于批准两份哈美两国谅解备忘录的法律文件。按照备忘录内容，哈方将向在阿富汗境内执行反恐任务的美
军战机提供交通走廊和备用机场。

我国的战略石油储备正借低油价之机开始提速。近日，由中国石油承建的新疆鄯善原油储备库一期工程正式建成投产，来自于哈萨克斯坦的原油同时开始注
库储备。

    【金鸿评论】哈萨克斯坦敢于在这时加强与美国的联系，恐怕是得到了中国的的默许。要知道，中国是为哈萨克斯坦提供核保护的。

    当然，中国在这时曝光自己增加战略石油储备也是在拉俄罗斯一把（这也应了我在前几天分析俄美石油定价权之争的分析中的观点），因为中国增利油
储对于国际原油市场来说，绝对是个利多消息。油价可以借着这个消息涨一涨了。说一这里，许多朋友可能不高兴了，让油价继续跌下去该多好？

    可惜，国际斗争没这么简单，要想实现自己的利益最大化就不能吃独食，该给朋友一点好处的时候哪怕自己吃点小亏也得给。就拿现在的油价来说，如
果油价不反弹一下，不光俄罗斯，就连伊朗和委内瑞拉也撑不住，如果他们中有人倒下了（比如俄罗斯），或者有人撑不住对美国低头了（比如伊朗），或
者有人家里大乱了（比如委内瑞拉），那时会严重损害我们的全球布局：

     如果俄罗斯倒了，美国会重新把油价拉到一百美元以上，那时，中国经济又会面临高通胀和剪刀差的双重折磨；

     如果伊朗软了，中国在伊核问题上的主导权就会失去，胡主席五年的辛苦就会毁于一旦；

    如果委内瑞拉乱子，恐怕会涉及其他的南美左翼国家，甚至有可能给美国重新稳固后院的机会，其战略压力就会大为减轻。

    所以，让油价适当回升一下，特别是在中国的援手下油价重新回升一下，不光俄罗斯，众多的产油国（包括沙特）都会感激中国。这也是我在过去预测
油价会在四十至九十美元之间波动的原因。

    当然，对俄罗斯绝对不能只给甜枣哄着，该抡巴掌时也是不能客气的。这一次默认美国在中亚扩张势力范围就是个警告：

     美国介入的力度加大会重新让俄罗斯感觉到危险——对俄罗斯而言，把地盘让给中国也比让给美国合算，毕竟中俄合作多争斗少，俄美则是死敌。

     对哈萨克斯坦来说，这也是一个利益最大化的好机会，美国想在哈萨克砸个楔子不能白砸，地皮钱是少交不了。同时，还可以借美国的势力抵消一部分
来自俄罗斯的压力。另外，还可以变相的替中国敲打俄罗斯一回，一举三得。没办法，八面玲珑才是小国的生存之道。这也是现实世界的生存法则。

    5、据俄新网报道，俄罗斯科学院院士塔季扬娜·德米特里耶娃星期五(19日)称，俄罗斯已获悉制造海洛因用的乙酐是从哪些国家进入阿富汗的。德米特
里耶娃说，这样就可以证明，进入阿富汗的乙酐不是像以前认为的来自俄罗斯等国家。

    【金鸿评论】要知道，塔利班政权曾在2001年以违反教义为由下令禁止种植鸦片，之后，阿富汗的鸦片产量一度下降了90％。

    但是，就在同一年的年底，美国大兵推翻了塔利班政权后，阿富汗国内的鸦片种植产量马上东山再起：在塔利班倒台的第二年，阿富汗鸦片产量一跃达
到3400吨，占据了当年全球鸦片总产量的70％。2003、2004两年，阿富汗鸦片产量不断创出历史新高，，从3600吨暴涨到4200吨，独占全球鸦片产量的近90
％。2005年，卡尔扎伊政府被美国批评禁毒不力后阿富汗鸦片的产量暂时滑落到４１００吨。不过，一年之后，鸦片产量又反弹到4500吨。到2007年，联合
国毒品和犯罪问题办公室在8月27日发布了《2007阿富汗鸦片调查》中称，当年阿富汗的鸦片产量达到了“创纪录”的8200吨，占世界鸦片总产量的93％，已经
超出全世界鸦片需求量近3000吨。

     还有一个非常有意思的现象：阿富汗鸦片种植情况有明显的地区差异，阿富汗约70％的鸦片产自南部与巴基斯坦相邻的5个省，其中仅赫尔曼德省的产
量就占阿富汗鸦片总产量的50％；而在中部和中北部的省份，鸦片种植量却在大幅减少。

    美国官方对此的说法是：，鸦片生产与反叛武装密切相关，凡在鸦片生产的地区，反叛武装军队都会比较密集出现；塔利班利用鸦片种植来满足自身的
利益，用鸦片所得进行装备；塔利班向鸦片种植者征税，并为鸦片贩子的走私活动提供保护。

    不过，现在出现了一个问题：美军主要集中在阿富汗南部，阿富汗的鸦片产量也主要集中在阿南部，当然，跟驻阿联军和塔利班接火最激烈的地方也在
阿南部，从表面上看，美国的说法有道理。但是，为什么在相对安宁的、塔利班活动也不频繁的阿北部种鸦片的人越来越少呢？因为在阿北部，鸦片种植者
和鸦片贩子们得不到美军的保护。

    6、保留一部分存档新闻，今天不作分析：

    特拉维夫12月18日消息，以色列看守内阁总理奥尔默特18日说，以色列与叙利亚通过谈判达成一项和平协议是“可能”的。

    俄罗斯外交部长拉夫罗夫22日在与巴勒斯坦民族权力机构主席阿巴斯举行的联合记者会上表示，俄罗斯愿意资助巴勒斯坦。拉夫罗夫说：“我们准备奖励
那些同巴勒斯坦进行合作的俄罗斯公司，已经有这方面的具体计划，今天将在克里姆林宫进行讨论。”

    据报道，玻利维亚总统莫拉莱斯说，拉丁美洲国家应当驱逐在他们国家的美国大使，直到美国解除对古巴的长期禁运为止。

    法国和巴西23日签署了总值86亿欧元的军火协议。巴西将从法国购买50架美洲豹直升机和5艘潜艇。协议还包括法国向巴西转移技术，帮助该国发展自己
的军火工业。协议是在萨科齐对巴西进行为期两天的访问结束时签署的。

    据韩国报章23日称，美国要求韩国继续向阿富汗派遣军队。

据朝鲜中央通讯社报道，朝鲜人民武装力量部部长金一哲次帅23日在平壤表示，如果美韩好战势力发起战争挑衅，朝鲜人民军将给予“坚决、无情”的回击。

    圣诞节前夕，欧盟通过新的玩具安全指引，内容涉及提高对儿童玩具的生产材料、检测标准等，中国玩具成为重点监管对象。预计新举措不但严重打击“
中国制造”在欧洲圣诞黄金档期的销售，更令已在金融海啸中萧瑟过冬的国内玩具制造企业，雪上加霜。

     北京24日消息，中国国家质检总局昨天下午对美国输华大豆发出风险预警，要求各地加强对美国输华大豆的检验检疫。

    当地时间12月22日，美国国际贸易委员会以6:0的投票结果，批准了美国商务部对产自中国的环状焊接钢管征收最多40.05%的反补贴税，以抵消中国政府
对本国钢管制造行业的补贴。这一投票结果，为美国商务部发布其反补贴税课征命令扫清了障碍。

    据韩国《朝鲜日报》根据外电报道分析称，由于美国日渐兴起的贸易壁垒表示不满，中日欧可能联合向世界贸易组织（WTO）向美起诉。

    莫斯科12月23日消息：据俄新社报道，俄罗斯联邦政府总理弗拉基米尔·普京表示，天然气输出国论坛工作合法，没有违反国际法。


    
** 【金鸿评论】以色列为什么血洗加沙？
[2008-12-30 15:53:35]



27日，以色列战机和武装直升机对哈马斯控制的加沙地带发动了大规模空袭，已造成三百多人死亡，另有约700人受伤。事后，以色列总理奥尔默特和国防部
长巴拉克警告，27日针对哈马斯的空袭行动只是一项军事行动的开始。并称，这项军事行动可能持续数周。以军地面部队已在加沙边境地区完成了集结，有可
能实施地面作战行动。可奇怪的是，以色列国防部长巴拉克称：我们的目标是重创哈马斯，迫使其停止针对以色列公民和以色列国防军的火箭发射和其它敌对
活动。以色列并不计划征服加沙地带或者推翻哈马斯政权

【金鸿评论】这可真让人摸不着头脑了，以色列即然大打出手，而且凶残无比，把本已比较平静的巴以局势搞得骤然紧张得不得了，却不是为了消灭哈马斯、
将其赶出加沙，这样能解决什么问题？岂不是越打直越乱？其实，没道理的事情不止一件：在屠杀哈马斯的前一天，以色列还做了另一件让人非常难以理解的
事情——以色列重新开启了通往加沙的通道，允许人道主义物资输入。封锁加沙困死哈马斯是以色列一直以来不泄追求的目标，为什么一边给哈马斯松绑一边却
要动刀子呢?

在分析这其中的原因之前，我们先来看一下各方对以色列屠夫行为的反应吧。各方主要是美国、欧盟、俄罗斯、中国、伊朗、阿盟、埃及。下面一一的看一下
：

1、美国：美国敦促以色列在攻击哈马斯目标时，应避免对平民造成伤亡，但是警告说，如果要结束暴力，伊斯兰运动必须停止火箭攻击。

美国的态度很明显，不希望现在冲突平息，因为他给结束暴力提了个条件，就是哈马斯先停止火简攻击，而这一点对于刚刚吃了大亏的哈马斯来说，是不可能
的。除非以色列先对哈马斯做出某些原则性让步。而在目前情况下，这同样是不可能的

2、欧盟：欧盟轮值主席法国发表声明说，对加沙地带暴力升级表示极大的关注，对于大量平民伤亡感到震惊。声明还表示对以色列的轰炸和加沙发射火箭表
示谴责，并要求立刻停止这些行动。欧盟呼吁立即停火。

欧盟的代表非常坚决，别打了!当然，欧盟是站在同情哈马斯的立场上的。

3、俄罗斯：俄罗斯要求以色列和哈马斯停止相互攻击。

俄罗斯的态度和欧盟接近，不过说话好象有点不痛不痒的，只能说是亲欧的立场

4、中国：有记者问：中方对当前加沙局势有何评论？秦刚说：中方对以色列在加沙发动军事行动，加沙紧张局势升级表示严重关切。中方谴责造成平民伤亡
的行为，反对用武力解决争端，呼吁有关方面保持最大克制，通过对话解决分歧。

中国的态度呢，除了从人道主义立场上的态度以外，有点事不关已的意思。

5、伊朗：伊朗最高精神领袖哈梅内伊向全世界的穆斯林发布一道教令，“让他们以任何方式反对以色列对加沙发动的攻击，捍卫巴勒斯坦人民”。

伊朗自然是希望以色列好看，所以无论声援还是经援都没少，坚决支持哈马斯抗争到底。

5、阿盟：阿拉伯国家联盟则发表了一份措辞强硬的声明，谴责以色列对加沙发动的攻击，但原计划28日在埃及首都开罗召开的一次阿拉伯国家联盟紧急外长
会议被推迟到星期三。

阿盟的态度自相矛盾，在这样的情况，仅仅谴责是不够的，但是，要统一阿拉伯世界的声音总得先开个会吧?可这些家伙们居然把本来可以开的会给推了两天
，显然是在等待什么东西，他们在等什么呢?后面分析。

6、埃及总统穆巴拉克在一项声明中对以色列在加沙开展的军事行动进行谴责，并说以色列是占领军，应该对死伤者负责。

埃及这一次对以色列是毫不客气的，站在了和伊朗叙利亚相似的立场上，这也是很不容易的。

现在谈到了埃及，要多说几句。以前分析中东局势的时候，我曾经提过一个观点，中国与埃及全面建立起战略合作伙伴关系之时，就是中国主导中东和平进程
之日。为什么这么说呢？以色列国的创始人古里安曾说过一句话：“没有埃及，以色列不会面临战争；没有叙利亚，以色列不会实现和平。”果如斯言，自从以
色列与埃及媾和之后，以色列就再也没有面临过战争，除非是他主动挑起的。现在，在中东，伊朗是中国的小兄弟，沙特一心往中国这边贴，如果埃及也争取
过来了，中东的大国就都是我们这边的了，这时，中国还主导不了中东局势吗?

其实，在以色列血洗加沙之前，大家之间有过一连串的互动，一起看一下：

应埃及总理纳齐夫邀请，中国国务院副总理李克强２４日晚抵达开罗国际机场，开始对埃及进行正式访问

埃及总统穆巴拉克25日会见来访的以色列外长利夫尼时表示，希望以色列和巴勒斯坦武装分子双方都保持克制，避免局势进一步恶化。

一艘埃及散装货轮25日在索马里附近海域遭海盗袭击，船员中枪。正在附近巡逻的德国护卫舰迅速派直升机前往救援，在海盗登船前及时救出货轮。

26日快讯，据新华社报道，中国海军舰艇编队从三亚启航，赴亚丁湾、索马里海域执行护航任务。

26日，以色列重新开启了通往加沙的通道，允许人道主义物资输入。以色列官员说，国防部长巴拉克同安全部长们会谈后，并在国际社会的要求下做出这一决
定。

【金鸿评论】请大家注意了，是中国的李副总理访埃在先，以色列外长见穆巴拉克在后；而且，就在以色列外长与埃及总统会见的当日，埃及货轮遇上了海盗
，出手相救的是却是欧盟的人。同时，在中国海军出发的当天，以色列放开了加沙的通道

以色列外长去埃及干什么呢?自然是探一下埃及的立场，是否能协助自己继续封锁加沙，不知道大家记得不记得，前些日子，就是在哈马斯快被饿死的时候，
咬着牙把与埃及之间的隔离墙炸开了，才救了自己的命，当时，埃及默认了哈马斯的行动。其实，如果埃及愿意帮忙，以色列完全有可能困死哈马斯，但是结
果呢?以色列的行动证明了自己的算盘落空了。

哈马斯是美国的眼中钉，特别是以民选的方式上台以后，更是让美国人恨到了骨头里。美国自然希望埃及能帮自己一把，所以在让自己的小跟班探口风的同时
，也没忘记用另一种方式敲打一下埃及，可惜，德国人出手搅了局。至于后面的两条新闻，稍后分析。

当然，为了把埃及拖在自己的阵营之中，无所不用其极：

根据以色列《耶路撒冷邮报》27日报道，加沙地区的哈马斯官员27日表示，他们之所以遭以色列空军的闪电袭击，是因为埃及提供了假情报。

加沙遇袭后，哈马斯发言人公开表示，有“第三方”与以色列勾结起来，试图推翻哈马斯的统治。哈马斯的一位部长稍后表示，“第三方”就是巴勒斯坦自治政府
和埃及政府。

如果埃及真想推翻哈马斯的话，继续困城就可以了。何必自绝于整个阿拉伯世界呢？过去的几十年，埃及这个阿拉伯世界眼里的叛徒所受的冷眼还少吗？

其实，埃及过去的行动已经证明了一切。这一次埃及给哈马斯或许真的提供了假情报，但是可以确信的是，埃及也上当了。从这里也可以看出埃及地位的重要
，和美国影响力在中东的日薄西山。

当然，对加沙冲突表态最有意思的还有一个人，就是阿巴斯。按照阿巴斯的说法，以色列的空袭行动是“犯罪行为”，他呼吁国际社会就此进行干预。

既然你阿巴斯认定这是犯罪，而且自己手里有人有枪，为什么不还击，还要等什么国际干预?国际是谁?美国吗?美国人说了，不是停火的时候！如果美国不管
，那还有谁会管呢?这就要看这次冲突的最深层次的原因了。

从表面现象就可以看出来，加沙大乱、以色列还有可能发动地面攻击的情况下，最受冲击的就是欧盟主导的地中海联盟了。正因为这样，欧盟才第一个火急火
了的要求停火。在过去一年多的时间里，欧美之间在中东是相对比较默契的。为什么这一次美国突然出手断欧盟的财路呢？还是看看欧盟干了什么好事吧：

23日法国和巴西签署了总值86亿欧元的军火协议。巴西将从法国购买50架美洲豹直升机和5艘潜艇。协议还包括法国向巴西转移技术，帮助该国发展自己的军
火工业。萨科齐还表示，巴西应该在国际事务中扮演更加重要的角色，并成为联合国安理会的常任理事国。

【金鸿评论】过去一年多以来，为了拉个伙计帮助自己摆拖困境，美国用支持科索沃独立、暂时的中东和平，来换取欧盟来帮助自己稳定阿富汗和伊拉克，封
锁伊朗。结果呢，欧盟在封锁伊朗方面是出了一把力，我们就看到了萨克奇一上台就一改希拉克的做法，一口一个制裁了，表现得好象多么的亲美，还有那个
死娘们默克尔，其实，他们不是为了美国，而是为了欧盟自己。不过，在阿富汗呢?欧盟的表现就让美国非常失望了：十天前，美军参联会主席马伦上将宣布
，2009年将向阿富汗增兵3万人，同时，北约要求其他成员必须跟随美国向阿富汗增兵。美国表现的很积极，而法国德国呢，跟没听见的似的，一点动静都没
有。就连美国的大奶英国，也只不过装了装样子，承诺增兵300人。美国派三万，英国派三百。现在美国人一定在心里骂上了：妈的，英国佬派的是天兵吗?以
一当百?逼得无米下锅的美国人不得不招当地的二鬼子替他们卖命了不帮忙也就算了，最可恶的是，欧盟还在自己的后院里埋地雷!非要把巴西扶起来，还要当
什么联合国常任理事国。这不是要美国人的命吗?

这还不算，还有另一个更让美国人头疼的事情出来了：26日，中国海军舰艇编队从三亚启航，赴索马里海域执行护航任务。

关于索马里护航，大家都很关注，把这次军事行动分析了个遍。不过，在这里，我要从另一个角度分析一下这个问题：其实，中国军舰的航行路线图，就是人
民币的扩张路线图。人民币是选择了南下。先东南亚，再南亚，再非洲。人民币南下的第一站东南亚是抢美元和日元的地盘。

不知道大家注意了没有，那几天朝鲜天天闹腾：

一会儿要对韩国“先发制人”，一会儿发表什么“控诉书”，说当前朝韩关系恶化的责任完全在韩国方面。这是折腾个什么劲呢？自然是警告美国，别不老实，否
则老子的核弹又要暴了。当然，不管朝鲜怎么闹腾，美国就是不接招，害得一心希望天下大乱的小日本是蠢蠢欲动：23日，因撰文否定政府历史见解而被撤换
的日本前航空幕僚长田母神俊雄站出来大喊“日本应该有核弹发射权”。小日本是巴不得朝鲜再暴一颗核弹，自己好借机从美国控制下逃出来。可惜，不管没他
怎么跳，美国就是不接招，结果，跳到了半空的小日本把自己给晾了起来。

正因为朝鲜的牵制，人民币在东南亚冲击美元，才没有招来美国的报复。真可谓“朝鲜在手，东亚无忧”。

在人民海军兵赴索马里的同时，以色列重启了加沙通道。这是美国在在默认人民币的扩张。从本质上讲，货币就的核心是信用。一个国家的货币能否成为国际
货币，就看这个国家的国家信用，国家信用靠什么体现?黄金吗?不是，是武力。真理在大炮的射程之内，信用同样在大炮的射程之内。当年，英国海军天下无
敌，所以当时的英镑是黄金的代名词，现在美国的航母舰队横行四海，所以，美元是首屈一指的硬通货。人民币怎么才能走出去?海军护航是必须的。

正因为这样，在中国海军军舰前往索马里海域执行护航任务的同时，日本国内要求出兵索马里的呼声骤然升高。小鬼子真是想去打海盗吗？那些海盗就是他的
美国爸爸造出来！日本是希望日元成为真正的国际硬通货，所以找个理由也想让自己的军舰走出去而已。可惜，美国虽然挡不住中国军舰，却完全可以挡得住
日本的八大金刚。

人民币南下会冲击欧元，这是不可避免的，其直接结果就是加剧欧元与美元的对立。看一下全球货币战争的力量分布吧：中东是美元对欧元；北美是美元的天
下；南美过去是美元的天下，现在欧元扶植巴西阿根延、中俄扶植古巴委内瑞拉等国起来反抗美元；东南亚是人民币对美元，非洲下一步是人民币对欧元。

随着人民币的步步紧逼，欧元唯有加大在美国后院的活动力度来逼美元对自己让步，因为欧元需要中国的地方太多了，无论是伊核问题、巴以和谈、阿富汗伊
拉克还是科索沃，欧盟需要中国的地方太多。所以，在过去中国一再逼欧盟在金融主导权方面对自己让步时，欧盟只有死守，没有反攻的能力。

同样，美国也惹不起中国，因为美国需要中国的廉价商品，更需要人民币对美元的支撑。但是，中俄欧都往死里逼他，他该怎么办?

对俄罗斯，是用低油价狠砸，同时又在格鲁吉亚搞小动作。26日格鲁吉亚外长瓦沙泽的话号称一个月后将到美国美方签署“历史性文件”。当然了，俄罗斯也不
吃亏，当天就宣布往委内瑞拉等七个南美国家卖防空导弹。客观的说一句，美国在俄罗斯家门埋的这个钉子得等一个月后才能有结果（也许会有变故），而俄
罗斯在美国后院放的这把火可是现在进行式。

对付中国呢，美国主要靠侧面包抄，在南亚克什米尔地区点火，可印度迟迟不敢动弹，美国不得已，把那个韩国鬼子拖了出来——在巴基斯坦前总理贝布托遇刺
身亡一周年纪念日，潘基文秘书长26日特别发表声明，要求彻查事件真相，将行凶者绳之以法。声明指出，应巴基斯坦方面的请求，秘书长已同意成立一个独
立的调查委员来对刺杀事件有关情况进行全面审查。

美国无非是想借机直接插手布托死因的调查进而把凶手指向克什米尔，目的嘛，印巴开战!乘机切断中国的巴基斯坦通道，改变自己在伊核问题上的被动局面
。美国这样做，也是想鼓励欧盟，赶快在阿富汗增兵，配合自己的阿富汗政策。可惜的是，欧盟没敢动。

既然欧盟光吃好的不干活，那自己还对他让那些步干吗?先把地中海联盟的台子给他拆了！结果，加沙冲突骤起!

哈马斯和以色列一交火，欧盟第一个急眼了，所以，第一个喊停火自然就是他了。

美国人说什么呢——“条件不成熟!什么时候条件成熟?自然是欧盟宣布阿富汗增兵之后。

所以，加沙在打的火热的29日，塔利班也没闲着，一个劲的过嘴瘾，将要“如同战胜前苏军那样击败美军派来的援兵”。其实，这是塔利班在警告欧盟，这里没
你什么事，不想找死就别来凑热闹。

前面分析的时候，提到了阿盟的态度自相矛盾，为什么?他们是在等待。等谁呢?自然是欧盟，看欧盟有什么办法能扭转目前的巴以局势?既然你欧盟有本事搞
地中海联盟坐中东的桩，你就得有本事稳定局面，不然谁也不敢跟你混。但是，他哪有那个本事呀?所以现在的欧盟是急的团团转。直接后果就是中俄的身价
立涨。

为什么俄罗斯表现出了相当的亲欧立场呢?因为对俄罗斯而言，从长远看，欧盟比中国更适合做合作伙伴，中国做伙伴只是十年八年的事，将来肯定是对头，
而欧盟就不同了，既有钱又没有武力自我保护，最需要强大的北极熊的保护。但是，眼前欧盟是靠不住的，现在欧盟还是美国的半个跟班，必须打倒了美国把
欧盟抢过来才行。

接下来，我们就看欧盟怎么表演了。想要以色列停止暴力活动，那只有依靠中俄的力量。而中俄出手，必须具备两个条件中的一个：欧盟在国际金融改革问题
上对中俄做实质性的让步，阿盟统一声音对外求救。

不过，暴力冲突对以色列而言也不是好事，他毕竟只是个代理人，打半天真正能捞到好处的也不是他，而是自己背后的人。所以，表面上看，以色列出手非常
的狠辣，其实，以色列也不想打了，所以才一出手就这么狠。

之前，以色列干过几次这样的事了：一次是06年打击真主党的关键时该，轰炸了加纳村；一次是今年2月，以色列军队空袭了加沙中部布赖杰难民营。那两次
行动之后，巴以冲突就缓和了。为什么呢？就是因为以色列不想打了，所以问自己背后的利益相关者：还想让我打吗?你得答应我的什么什么条件才行。美国
答应不了，所以，美国就默认以色列停止了进攻。

这一次，以色列是冲着欧盟出的牌，想让我停下来吗?你得有所表现才行！当然，这次和上两次也有不同之处，就是前两次是打了好久之后以色列才玩的狠，
这一次是一上来就下了狠手。这只能说明以色列也不想出力干活了。毕竟，谁愿意自己的国家流血死人呀，特别是为了别人。半年的准和平状态，美国的大势
已去，让以色列开始离心离德了，这恐怕是美国在中东的大损失。




** 【金鸿评论】加沙冲突局势连续追踪（2009/01/02）
[2009-01-01 10:17:30]


    德国外长施泰因迈尔２９日晚与巴勒斯坦民族权力机构主席阿巴斯通电话，讨论目前加沙地带不断升级的紧张局势。施泰因迈尔在通话中强调，哈马斯必
须停止对以色列城镇的攻击并立即停火。

    正在召开的海湾阿拉伯国家合作委员会（海合会）首脑会议将讨论单一货币的命名问题，未来的海湾单一货币可能叫“凯拉米”或者“海元”。

    【金鸿评论】阿拉伯世界在这个时候不全力制止巴以冲突却出来大谈单一货币问题好象不太是时候，不过，如果他们另有所指就不同了。

    德国人也急眼了，扯着嗓子要求停火。有用吗？红口白牙一嗓子别人就不打了？你得拿出东西来！

    前面的分析中，我曾经提到过，阿盟自相矛盾的态度是在等待，等待欧盟的行动。可惜，欧盟让人很失望。无奈之下，阿拉伯世界只好一方面用单一货币
展示自己的团结，一方面也是在警告欧盟，如果你没本事保中东的平安，石油欧元就不要指望了，还不如我们自己的海元可靠呢。

   ３１日阿拉伯国家联盟外长会议就要举行了，阿拉伯世界会统一出什么样的口径来呢？就看欧盟这两天内的表现了。不过，欧盟让人失望的可能性会大一
点。

   至于这一轮的加沙冲突，虽然来势汹汹，不过估计打不了几天。真要闹腾大了，油价可是要大幅反弹的。能把油价压到这一步也不容易。

    至于我们，是稳赚不赔的，我们的原则是不见兔子不撒鹰，唯一的不同就是看兔子是欧盟放的还是阿盟放的。

___________________________________________________________

12月31日

    朝鲜驻华大使馆一名官员当天说，如果日本不提供作为回报的重油援助，朝鲜就将中断核设施的去功能化作业。

　　巴基斯坦政府30日宣布，暂时关闭驻阿富汗美军和北约部队的陆路后勤补给线“卡巴通道”，以便集中火力打击日益猖獗的塔利班武装成员。

    据路透社报道，美国当地时间星期二宣布，将向联合国提供8500万美元以援助巴勒斯坦在西海岸、加沙、约旦、黎巴嫩和叙利亚的难民。

    俄罗斯联邦外交部长拉夫罗夫30日在接受俄罗斯VESTI电视台节目中表示，美国应当坚决利用该国在中东地区的影响，努力促使巴以双方就建立巴勒斯坦
国达成协议。

    据法新社报道，31日法国总统萨科齐称，欧盟将向中东派遣部长代表团。欧盟呼吁以色列和哈马斯立即并永久停火。

    以色列政府表示，不能接受法国提出的关于停火48小时的建议，而恰恰相反，将把打击哈马斯的战斗按计划继续进行下去。

    【金鸿评论】随着加沙局势的吃紧，中国的主导优势越来越明显。所以，借着这个机会，中国加大了在东亚对美国影响力的挤压力度。现在朝鲜逼日本送
重油是假，借美国人的手打日本才是真。目的自己是进一步收编小日本。

    日本一直不给重油援助，是因为朝鲜还没有给“绑架事件”以交待，日本人面子上过不去。现在，在美国最需要中国在加沙冲突中坐壁上观的时候，又怎么
敢在东亚兴风作浪？可尽管他努力的把脑袋低下去，无奈有人非把他的耳朵揪起来让他干点儿活，你说难受不难受？这也算三十六计中的“借刀杀人”吧？

    与朝鲜联动的是巴基斯坦。这段日子，巴基斯坦承受着巨大的战争压力，现在可以喘口气了。巴基斯坦打击塔利班是假，逼迫美国在南亚停止做挑动印巴
战争的事情才是真。不过，从行动来看，美国还不想在南亚放手，因为美国在加沙又做了一件事——捐款8500万美元给难民。

    去年中国汶川地震时美国政府只不过捐了50万美元——难道加沙冲突比中国的大地震死伤还多？再说了，如果美国真的有良心，为什么不让以色列停火？很
显然，这是虚情假义！既然是这样，那美国为什么还要大把的掏银子呢？

    道理很简单，他是怕以色列的炸弹炸不垮哈马斯的精神却炸垮了自己的奴才阿巴斯！这些钱虽然是给的联合国，但是肯定会有大部分转到阿巴斯领导的法
塔赫的帐户下去！正是因为如此，以色列在对哈马斯大打出手的时候才会说自己不是为了“征服加沙地带或者推翻哈马斯政权”，因为征服了加沙的同时就意味
着阿巴斯完蛋了，整个阿拉伯世界的怒火会统统发到阿巴斯头上去！所以，这一轮的加沙冲突不是一场军事战争，而是一场政治斗争，与以色列的国内大选没
多大关系！西方的民主选举其实没什么意思：弄上两个流氓来让你挑一个，表面上你有选举权了，你有自由了，其实，不管谁上来，都是强奸你！这样的游戏
好玩吗？

正是有阿巴斯这一重的顾虑，决定着这一场冲突的时间不会太久。不要忘记了，阿巴斯从冲突一开始就在大喊芝麻开门的(国际干预)。如果芝麻迟迟开不了
门,阿巴斯也就算寿终正寝了。

    既然美国人还希望以色列继续拉磨，以色列只好“拒绝法国的48小时停火建议”、 “继续军事行动”。其实，如果不是美国对南亚可能出现的战争还抱有幻
想，巴铁一亮牌加沙马上就会停火。不过，不希望南亚大乱的还有俄罗斯，因为他也不敢保证一旦中国的巴基斯坦通道被全面切断了等待他的会是个什么后果
，所以，给美国出点难题是现在必须做的。于是，拉夫罗夫又在要求美国帮助巴勒斯坦建国了。

    这可要让美国人难受了，一年以前美国人精心组织了一场安纳波利斯中东和会，当时有人可是立了军令状的，一年之内帮巴勒斯坦建国。现在，一年过去
了，巴勒斯坦国谁也没看到，不过加沙的死伤枕籍可是有目共睹！现在，布什先生如何向世人交待呀？

    还有一点要说的就是，安纳波利斯峰会之后，美国与欧盟在巴以和平问题上就组成了统一战线，由此也给了阿拉伯世界无限的期待。现在，一年过去了，
欧盟也没能给阿盟带来任何的惊喜，恰恰相反，在众人期盼巴勒斯坦国出现的日子里，阿拉伯世界却在面对着血光之灾！这可真是个莫大的讽刺。相信即将招
来的阿盟外长会议会对此有所表示的。

    俄罗斯人尖锐的要求不仅仅是针对美国的，同时也在影射欧盟。谁让他稳稳的在中东和平进程上坐了一年的庄呢？其实，俄罗斯也是在对欧盟开价：想要
加沙停火吗？来求我吧。

    这不，萨克奇又要往中东派人了，而且是要做到“立即并永久停火”，这个卫星放的可不简单，照我的眼光看，除非今天中东没石油了，萨克奇说的才有可
能变成现实。萨克奇的话唯一能证明的，就是让所有人都看出欧盟心里是多么的着急！

    心急是好事，急了才会想办法采取行动。欧盟的弟兄们，放血吧？

____________________________________________________________

 1月1日

    先来一段环球掠影
   【金鸿评论】加沙战火一起，世界乱作一团：
    美国宣布，要以色列停火，哈马斯必须先停止发射火箭弹；
    俄罗斯说，要哈马斯停火止发射火箭弹，以色列必须先解除加沙封锁；
    以色列说，部分解除可以，全面解除老子不干！
    哈马斯说，那咱哥俩就接着玩！卡桑旅，增员一千！
    欧盟干急眼，大喊，能不能先停下歇两天？
    美国说，不行，别怕伤了人没钱治，我给8500万！
    中国说，我也捐！
    伊朗表态，以色列高官都是狗娘养的，我要缺席审判！
    印尼说，我们家里有人憋不住了，要参战！
    阿拉伯世界老百姓上街游行：美帝国主义王八蛋！把他们的使馆全砸烂！
    约旦国王王后往前站：巴勒斯坦缺血了，我们献！
    ……

    据新华社报道，从加沙地带发射出的一枚火箭弹，击中以色列境内一座距边境42公里的城市，成为哈马斯武装发动的最深入以色列的袭击。
    据以色列媒体报道，以色列内阁将于周三召开会议，讨论是否接受法国提议的48小时休战计划。
    埃及总统穆巴拉克强调指出，埃及与加沙地区之间的唯一口岸——拉法口岸，只有巴勒斯坦民族权力机构主席阿巴斯的部队重新部署完毕且有欧盟观察员在
的情况下才能开放。

    【金鸿评论】欧盟是真急眼了。不过没想到欧盟是以给哈马斯送弹药的方式发火的。结果，欧盟一发火，以色列就打怵了。从这里也可以看出，表面上武
装到牙齿的以色列是多么的虚弱，这也是没办法的事，谁叫它那么小呢？根本就没有战略纵深，这样的国家是不经打的。
    以色列号称周三讨论法国提出的48小时休战计划，一是为了拖延时间，既满足背后老板继续打下去的要求，也是在向自己的后台老板求救，再不帮我一把
这个仗我可就没法打了，二也说明了今天是个非常重要的日子，因为阿盟的部长会也在这一天。也许，冲突结束的日子就在周四。
    至于穆巴拉克的表态，只能说明埃及承受着越来越大的压力，他是在向伊斯兰世界诉苦——阿巴斯这个叛徒不配合我自己在中间太难做人了！如果想要阿巴
斯渗合进来，还是要看欧盟的表现。穆巴拉克其实是在分化压在埃及身上的压力——如果欧盟连联合放生一条救生通道的能力都没有，还搞什么石没欧元？还是
找个安静地方歇着去吧。中东这个刀光剑影的地方不是你能混的开的。
    就在埃及向欧盟转移压力的同时，有人从另一个方向也向欧盟施压了。
    12月31日，俄罗斯黑海舰队“叶伊斯克”号小型反潜舰上的一位军官向俄新社记者透露，在阿布哈兹海域负责安全战斗执勤的俄罗斯黑海舰队击落5架格鲁
吉亚无人驾驶侦察机。
    俄罗斯天然气工业股份公司总裁米勒31日在莫斯科说，该公司与乌克兰石油天然气公司有关明年天然气供应的谈判无果而终，俄方将于2009年1月1日莫斯
科时间10时起中断对乌克兰供气。
    俄罗斯外交部称，哈马斯准备暂停向以色列发射火箭弹，但前提条件是以色列解除对加沙的封锁。
    【金鸿评论】俄罗斯为加沙开价了。不过价码够高的，他想打包同时解决格鲁吉亚和乌克兰问题。欧盟深知其中的厉害，赶紧想办法先压下其中的一个——
乌克兰问题，至于格鲁吉亚问题，有美国在前面扛着，自己不着急。
    所以，乌克兰赶紧还债，“我们不仅缴纳了１１月的费用，还预付了１２月的钱，”可俄罗斯得势不饶人，马上回应道，乌克兰仅仅支付了１５亿美元欠款
，而没有支付滞纳金。 “债务和滞纳金是两回事”。看来，俄罗斯的债是阎王债呀。不仅如此，俄罗斯还要兴师动众的成立一个“断气行动中心”——有必要吗？
不就是关几个阀门吗？找两个力气大的工人就办了，何必搞的跟真的似的？当然，如果这个行动中心要是去加沙干活的就另说了。
    现在，俄罗斯以调解加沙冲突为砝码强逼欧盟在格乌问题上向自己靠拢，以减少自己的正面压力。俄罗斯的算盘打的不可谓不精明，不过，美国人怎么可
能答应呢？这样一来，不成了给别人做嫁衣裳了吗？所以，以色列马上回应，继续在加沙进行军事行动！现在欧盟也不能把不停火的帐算在以色列头上了吧？
谁叫俄罗斯瞎渗合呢？当然，以色列也知道俄罗斯惹不起，所以，以色列一面继续军事行动，一面放开加沙口岸，允许大量运送物资的卡车进入加沙地带。没
办法，现在不是全面解决哈马斯的时候。
    哈马斯也不是傻子，自然知道这其中的利害，为了最大限度的减少自己的损失，强应的向以色列表态：如果以色列兑现其向加沙地带派遣地面部队的威胁
，哈马斯将战斗到底，“直至只剩最后一口气”。如此一来，以色列该犹豫了，这个仗怎么打？再把哈马斯打的太狠了，恐怕哈马斯手里就会有射程更远的火箭
弹了，但如果打轻了又达不到最大限度削弱哈马斯、保障自身安全的目的，自己该怎么办？
    除了以色列，还有更难受的人，就是阿巴斯。眼看着哈马斯在战争中越来越有威信，接下来自己还怎么在巴以和谈的谈判桌上玩？没办法，装装样子吧。
于是乎，阿巴斯开始“威胁放弃与以色列和平谈判”，以示其对以色列袭击加沙的反对态度。
    当然，在这一场冲突中受挤压最厉害的，就是欧盟了，眼着动嘴调停无望，萨科齐不得不表态， 1月5日出访中东地区“寻求和平之路”！与萨克奇配合的
，就是黎巴嫩总统苏莱曼，此君表态，黎巴嫩愿意当关于加沙问题阿拉伯国家首脑紧急会议的东道主。其实，你去不去没什么大不了的，该放的血放一点加沙
冲突自然会停下来。
    加沙停火的日子应该不远了，如此一来，在战火中并没有伤筋动骨的哈马斯理所应该的冲突的获胜方，一如06年的黎以冲突。有这样的成果在，哈马斯领
导人哈尼亚当然有理由宣布，“胜利即将来临”。
______________________________________________________________
1月2日

下面，从几个与加沙局势密切相关的分战场看一下局势的发展：

1、  印巴

这两天印度和巴基斯坦可真是一对难兄难弟，昨天连遭四起事故：

巴基斯坦靠近阿富汗边境的部落地区遭到数枚导弹袭击，至少造成5人死亡，1人受伤。

巴安全部队同武装分子在位于西南部的俾路支省发生交火，造成13人死亡。

印度东北部阿萨姆邦发生连环爆炸，目前已有5人死亡，40多人受伤。

一艘印度油轮在亚丁湾海域遭到两艘索马里海盗船袭击，幸而一艘马来西亚海军直升机赶往现场，印度油轮得救。

【金鸿评论】这一系列的变故的起因是印巴关系的缓和，两国以“交换核设施清单”的方式相互致意，这让一直希望印巴大乱的某国怒从心里起，恶向胆边生，
连下狠手：对印度出手是为了逼印度打出第一枪，引起印巴局势的大乱；对巴基斯坦，则是警告其不要混水摸鱼，不要以为自己受加沙局势的牵制就非要在南
亚让步。

为了缓解印巴双方、特别是巴基斯坦承受的压力，阿富汗塔利班也加大了活动力度，又是杀警察，又是杀高官，向方方面面展示，不管驻阿联军的努力有多大
，阿富汗局势始终没有任何好转，这里的混水欧盟还是不要趟的好。要知道，加沙冲突之所以暴发，就是因为美国要逼欧盟在阿富汗增兵。

2、  中亚

借着加沙冲突带来的身价提高，俄罗斯加快了自家门前大扫除的行动力度：

12月29日，格鲁吉亚反对派工党领袖沙尔瓦-纳杰拉什维利在第比利斯宣布，工党当日已开始正式启动对国家总统萨卡什维利的弹劾程序。

1月1日，俄罗斯天然气工业公司新闻局透露，该公司已完全停止向乌克兰供应天然气。

【金鸿评论】俄罗斯的铁算盘打的是真精，想借着加沙冲突一起、欧盟和美国都需要俄罗斯帮自己一把（至少是不给自己添乱）的机会，同时解决两个问题。
于是，我们就看到了，在走狗萨卡什维利面临倒台的时候，美国方面并没有什么动静，美国人可真是难得糊涂呀。

而对欧盟来说，无论是格鲁吉亚还是乌克兰，都是可以用来和俄罗斯做交换的筹码，只要俄罗斯开价合理，这两个麻烦就让美国人慢慢想办法好了。但是，如
果俄罗斯不给自己好处，那就能拖就拖，能压就压，先保加沙平安再说。所以，俄乌这一轮斗气一开始，乌克兰就出奇的乖巧，倒是俄罗斯得势不饶人。就是
这样，无论是欧盟新任轮值主席国捷克，还是德国，都一个劲的让乌克兰赶快答应俄罗斯一切可能可答的条件，把这事儿压下去再说。在这大乱之时，美国也
顾不得和俄罗斯再开一桌了，只好让尤先科出来低头，不管俄乌斗气斗到什么程度，保证欧盟不受影响。

不过，尤先科还给俄乌斗气留了个后门——他在1日发表声明中是这样说的，乌克兰和俄罗斯将在本月7日前解决两国之间的天然气争端，并签署相关供气协议。
要知道，萨克奇是5日访中东，也就是说，如果萨克奇访问中东如果做了什么让美国人非常不开心的事，俄乌之间再发生什么意外的插曲也是非常可能的。欧
盟可要掂量着办了。

3、  东欧

　　即将担任欧盟轮值主席国的捷克却公开支持以色列对加沙采取的军事行动。

波兰总理图斯克12月31日表示，在波兰境内建立美国导弹防御系统的问题上2009年将不会被“过度加速”，有关这项投资的全部决定掌握在美国人的手中。

【金鸿评论】会打劫的不光是大国，小国干起这买卖来更是一点儿都不含糊。不同的是，捷克是冲着法德这两个自己家里的老大哥要钱，波兰则是在向美国开
价。

看来，这年头谁先找事谁倒霉，待着设卡收费的主儿们太多了。没办法，谁让金融风暴席卷全球呢，总得弄俩小钱给孩子们做件过年的衣服穿穿吧？

4、埃及

埃及官员说,索马里海盗1日在亚丁湾海域劫持一艘埃及货轮,船上共有28名船员。

【金鸿评论】那支黑爪子还是不肯放过埃及。看来，埃及在阿拉伯世界里的地位太重要了。为了防止阿拉伯世界真的统一了声音搅了自己的局，有人真是不择
手段呀。

5、中国

朝鲜《劳动新闻》、《朝鲜人民军》和《青年前卫》3家报纸1日联合发表元旦社论，表示要在新的一年里吹响建设强盛大国总进军的号角声，掀起新的革命大
高潮。

中共中央总书记、国家主席、中央军委主席胡锦涛昨日在纪念《告台湾同胞书》发表三十周年座谈会上的讲话播发后，台湾官方、政党、媒体、学界都有不少
正面的回应和反响。

【金鸿评论】在过去的六天里，中国是大国中最低调的一个。唯一比较大的动作就是捐给巴勒斯坦权利机构100万美元。其实，那个掏钱的动作说明了中国的
立场——既然美国英国不怕打烂加沙，认为自己掏几块银子就能把阿拉伯世界的怒火化解掉，那在这场冲突中从来没损害过一点阿拉伯利益的中国自己更超然——
此事与我实在没多大关系！

当然，中国低调还有另一方面的原因，就是中国的家门口还有几件事要办，不过出面的人不都是中国而已：第一件事就是缓和印巴局势，由巴基斯坦出面；第
二件事就是强推东亚一体化，由朝鲜出面；第三件事就是彻底捆住台湾，由胡主席亲自出面。

这三件事办的顺利程度不同，经济一体化和台湾的事办的最顺利，特别是经济一体化的事，李瘪三一改往日狠舔美国人屁股的嘴脸，开始“呼吁朝鲜与韩国进
行合作、共同开创新的未来”了，可以断定的是，朝鲜不跟韩国合作有未来，韩国不跟朝鲜合作没有未来。

比较麻烦的就是印巴局势，不过，从各方的表现来看，只要印度再挺一把，事情也就过去了。不过，如果印度再犯迷糊颠三倒四可能会搅乱了局，那时，出手
收拾他的，肯定是俄罗斯了。

等这几件事都办的差不多了，阿拉伯世界的声音的统一的差不多了，如果那时欧盟还不让步，我们就该在阿拉伯世界期待的目光中亮牌了。

6、以色列

正在巴黎访问的以色列外长利夫尼1日表示，以色列将继续打击哈马斯并保持对哈马斯的“压力” 。

巴勒斯坦伊斯兰抵抗运动(哈马斯)1日证实，哈马斯高级领导人尼扎尔·拉扬在当天的以军空袭中丧生。

以色列总理奥尔默特1日表示，以方不希望在加沙地带“发动一场持久战”，也不热衷于“扩大战线”，而是希望此次行动的目标能够尽快实现。他还重申，希望
建立一个国际机构，负责监督和执行“可能与哈马斯达成的任何停火协议”。

以色列国防部长巴拉克1月1日晚突然宣布对约旦河西岸实行48小时封锁。

【金鸿评论】从以色列的言行可以看出，以色列的后台老板是真急眼了，所以，自然也要把欧盟逼上梁山：

一方面正面拒绝了法国的停火建议，让欧盟在阿盟面前颜面扫地；

一方面炸死了一名哈马斯高级领导人，为局势的进一步恶化埋下了伏笔——哈马斯的报复是不可避免的，而报复以色列的结果又会引起以色列的进一步扩大行动
；

一方面封锁了约旦河西岸，实事求是的说，我对加沙的地理情况并不熟悉，不知道进出加沙的关键口岸是如何分布的，不过，从地图上大体一看可以看出：以
色列封锁住了加沙的东面口岸之后，救援物资只能走西面了——西面是埃及。不知道大家还记不记得，昨天埃及总统穆巴拉克可是为开放口岸提过条件的——条件
本身就是在将欧盟的军，所以，现在以色列其实是在顺风点火，进一步把压力压到了欧盟的身上。

以色列为什么要这么做？以色列总理奥尔默特已经说的很明白了——“希望此次行动的目标能尽快实现”！此次行动的目标是什么？欧盟在阿富汗增兵，伊核配合
。这是最基本的要求。

以色列在为后台老板全力以赴的同时，也提出了自己的要求：

　　自以色列27日开始对加沙空袭以来，哈马斯对以色列南部的导弹和火箭炮袭击也进一步深入，以色列担心哈马斯的火箭弹可能威胁到以色列位于迪莫纳的
核设施。

【金鸿评论】以色列这是在指桑骂槐。他担心的不是哈马斯那两颗火箭弹，而是伊朗可能拥有的原子弹，他这是在向美国示警：如果伊朗拥有了原子弹，就别
指望自己以后还能再冲锋陷阵了。

不过，美国的回应没等人，倒是有人出来接茬了：

朝鲜《民主朝鲜》报2日发表评论，指责美国在核问题上推行“双重标准”，实际上起到了核扩散的作用。

朝鲜骂的是谁？对号入座吧？如果美国可以让某些不该有原子弹的人拥有了原子弹，那朝鲜有原子弹也不是什么错误，既然朝鲜都能有原子弹，伊朗为什么不
能有？

7、综合

【金鸿评论】从以上各方面临的情况来看，承受压力最大的是欧盟，最不愿意让步的也是欧盟，这样一来，加沙冲突结果出现后吃亏最大的肯定也是欧盟。如
果欧盟聪明，就赶快让步结束加沙冲突，否则，地中海联盟也好，石油欧元也罢，只不过是一场镜花水月而已。



** 【金鸿评论】加沙冲突局势追踪（2009/01/08）

[2009-01-08 19:54:29]



这一轮的加沙冲突引暴了大新斗争的洗牌。

借着这一轮的冲突，大国之间展开了利益交换和权利斗争。美国主动揭开了加沙冲突的盖子，率先对欧盟发牌，逼欧盟让步。除了加沙冲突这个主战场之外
，还有几个分战场：

【金鸿评论】最抢眼的就是俄乌斗气。俄罗斯借势挑起俄乌斗气，也逼欧盟向自己靠拢。我们就看到了一个有趣的现象：一边是打的热火朝天，一边是斗的
冰天雪地。在欧美俄三方的角斗中，阶段性成果已经出来了，那就是欧盟以放风“绕开乌克兰新建天然气管道”的方式向俄罗斯靠拢，俄罗斯盘面上占优势。

另外，美国好象要借与俄罗斯之间的斗法，把欧盟重新压倒的意思。这一点，可以继续观察，不过，有些信号已经表现的非常明显了。

【金鸿评论】其次就是处在走火边缘的印巴局势。虽然有人无所不用其极的挑起印巴战火，但在严重后果的顾忌下，印度最终没敢迈出这一步。3日巴基斯坦
以“重新开放北约给养物资通道”的方式向欧美展现出自己希望地区局势稳定的诚意。之后得到了欧美的较积极响应。阶段性结果是：印度放低身段，美国让
步，欧盟不出头，中巴占优。

【金鸿评论】第三个比较热闹的地方就是台海。

总体上说，在加沙冲突中表现最低调的就是中国。不过，在自己的家门口，中国是没少了忙活：胡主席亲自高调的对台喊话之后，得到了台湾各届的回应不
小，便马英九迟迟没有回应。于是，就传说了胡主席在在内部场合对马英九评价（“我们把他看得太高了！”），这一敲打之后，马英九马上就有了点回应，
不过，马英九的回应不能让人满意，看来，胡主席想和谐台湾是很困难了。还是稳住台湾几年后动武比较实在，到时把那些杂七杂八的玩艺全部收拾了也利
索，别弄的跟香港似的，还养着一帮吃里扒外的东西。

眼看着中国要统一台湾，日本自然沉不住气了，在目前的大气候下，强行挑动局势他又没这个本事，只好拿着“与台湾举行民间渔业磋商、讨论钓鱼岛近海捕
鱼权”这类事情来试探美国的反应，不过，美国的反应让日本人很失望，是什么呢？美国向朝鲜提供的最新一批粮食援助将在本周之内运抵朝鲜！

总体上说，在这一片：中国主导，日本沦落，美国边缘化。

【金鸿评论】随着大国斗争的发展，各方在伊核问题上的权利也在发生微妙的变化。美国越来越倾向于与伊朗缓和，欧盟的中间人角色越来越不重要。随着
欧盟在伊核问题上的边缘化，欧盟在巴以和谈问题上也越来越无足轻重了。而俄罗斯趁机想扩大影响力，一个比较大的动作就是1月4日的时候俄罗斯总统特
使萨尔塔诺夫提出的充当以色列与哈马斯接触的中间人的提议，当然，以色列外长拒绝了这个建议。显然，美国还打算用巴以和谈来诱惑一下欧盟。丢了面
子的俄罗斯反手就是一击：有消息称，俄罗斯正在测试最新的S-400防空导弹系统，预计它将提供给俄罗斯在中东的盟国。俄罗斯的中东盟国会是谁？叙利亚
的可能性比较大。现在该轮到以色列挠头了。

【金鸿评论】不过，还有更让以色列心烦的事情，这也是一轮加沙冲突中最有戏剧性的一幕：1月7日晚，埃及向哈马斯发出最终通牒，要求哈马斯在当地时
间1月8日上午6点之前对埃及停火方案做出答复。与此同时，以色列空军对加沙南部城市拉法和费城走廊地带的走私地道进行了猛烈的轰炸。看这阵势，大有
压垮哈马斯之势。

其实，埃及这样做并不是重新倒向了美以，而是专门采用的一种自我减压方式而已。说的通俗一点，埃及的喊话应该这么理解：各位老少爷儿们，我这边压
力太大了，我自己已经替哈马斯扛不住了，大家快来搭把手吧。埃及这么一喊，果然有人出来帮忙了：

就在埃及给哈马斯的最后期限到来前的几个小时，也就是８日的早晨，以色列北部地区遭到多枚来自黎巴嫩的火箭弹袭击，至少２人受伤。火箭弹是谁发射
的呢？黎巴嫩真主党说不是他们干的，哈马斯也说不是自己干的。那这到底是谁干的呢？据说是个“不知名的巴勒斯坦组织”。不过，就在7日黎巴嫩真主党的
老大纳斯鲁拉还呼吁“真主党抵抗力量做好准备以应对一切可能发生的局面。”动手的居然不是真主党的人，这可真怪了。

眼看着以色列把哈马斯打的满地找牙，旁边的真主党撸着袖子吐着唾沫在旁边咬牙较劲，突然，从后面一块板砖扔了过来砸了以色列一下子，以色列定睛一
看，砖头是从真主党所在的方向扔过来的，可人家真主党说了，不是他干的。哈马斯也说，我刚刚正趴在地上呢，也不是我干的。以色列蒙了，妈的，是谁
扔的砖头呢？唉，这个哑巴亏吃的﹍﹍真有点不是时候。

现在，那些准备继续向埃及施压的人该琢磨一下了：再这么打下去真主党会不会被卷进去？如果真主党也下了水，，再打下去整个阿拉伯世界会不会也跟着
下水？如果真那样，又一场中东战争可能真要开打了。

在这样的背景之下，阿盟自然有本钱抬高一下嗓门了：1月7日，阿拉伯国家表示决不接受一份不具有约束力的主席声明，决心推动安理会立即就它们早先提
出的决议草案进行表决。为什么会出现这样的情况？因为两年前的黎以冲突把真主党打成了阿拉伯世界的英雄。现在，是不是再让以色列重打一回？估计战
果还不如上一回呢！因为上一回至少欧盟还敢扛一把，这一回他可是一点本钱都没了。

阿盟的高调不是冲着别人，对象还是欧盟。阿拉伯人的意思很直白：既然你们跑前跑后那么忙活都没有替我们争取到利益，那以后就不要再辛苦了，巴以和
谈谈判桌上的椅子不是随便一个人就可以坐的，还是换人好了。该换谁呢？看看谁在一旁不吱声，估计就是他了。

【金鸿评论】这一天，我们已经等了很久很久。巴以和谈，到了换一种玩法的时候了。从去年322入联公投之后，中国就开始全力以赴的把巴以和谈的桌子上
挤了，没想到费了这么大劲才成功，真不容易呀。

【金鸿评论】从加沙传来的最新消息是以色列又遇到了新一轮的来自黎巴嫩方向的火箭的问候，而以色列军方的反应是：“正在考虑还击！”其实，他哪是在
考虑怎么还击？明明是在等待美国的指令！而埃及也在致力于“三天之内促成加沙停火”，看来，加沙冲突这几天真的要结束了。


** 【金鸿评论】中国主导世界的日子来到了！
[2009-01-10 18:52:31]


    安理会在纽约当地时间1月8日晚以14票赞成，美国一票弃权的结果就加沙冲突通过了第1860号决议。该决议呼吁立即、持久和全面遵守停火，以促成以
色列从加沙全面撤军。
    【金鸿评论】为了这个1860号决议，阿盟和欧盟在联合国大楼里吵翻了天，好歹弄出个决议来，可在加沙交战的双方居然都不买帐：
    以色列说：“那协议我不考虑！”
    哈马斯说：“那协议我不接受！”
    这可真是皇帝不急太监急。
    其实，双方不停火，是因为背后的关键人物该捞的好处没捞到，做为马前卒的小人物自然要在前后继续冲锋陷阵，要不怎么叫代理人呢。
    如果美国的目标实现了，他不会在决议表决的时候弃权。同样，如果哈马斯身后的支持势力的利益得到了满足，他就不会接着跟以色列玩命了。
     在1860号决议吵出来之前，以色列总理奥尔默特还在暗示要扩大目前在加沙地带展开的军事攻势，以“实现既定的行动目标”。
    以色列的“既定行动目标”是什么？欧盟在阿富汗增兵，配合美国的伊核政策。而这两点欧盟一直都没敢答应。既然美国推着以色列启动这一轮冲突的目
的没有达到，美国自己不会投停火的支持票，以色列也自然不考虑停火协议。所以，两边还得接着打。与此同时，有两条消息非常自然的冒了出来：
    美国智库和平研究所8日在这里发表报告说，美国及其盟友的现行阿富汗政策只侧重于短期目标，没有一个全面而统一的战略。报告建议即将上任的奥巴
马政府重新调整在阿富汗的军事和重建政策，并将稳定和重建阿富汗的努力作为一项至少需要十年才能完成的长期任务。
    美军中央司令部司令彼得雷乌斯称，美国与伊朗在阿富汗有共同利益和目标，这有利于美伊两国达成共识，合作打击塔利班武装分子。
    【金鸿评论】和平研究所的报告说的不够实在，实际情况是：不是美国没有长期战略，是欧盟的阿富汗配合不到位。这一次美国政策让自己的智库出来
伸手向欧盟要支持，也实在是够坦白的了。可惜，欧盟这一回还真是难得糊涂，愣装没听懂！
    不得已，美国使出威胁的手腕，摆出一副和伊朗合作的样子给欧盟看——再不配合我，伊核问题就没你的事了！
    当然，这也是美国最后一次拉拢欧盟了，因为美国也同时做好了另一种准备：
    据英国《卫报》1月8日透露，据奥巴马团队内部消息，即将入主白宫的奥巴马执政团队，将与巴勒斯坦武装组织哈马斯建立联系，一改往日布什政府孤
立哈马斯的策略，具有“破冰”的非凡意义。
    【金鸿评论】随着美国正式与恐怖组织（哈马斯）进行接触，巴以和谈不可避免的将会换一种玩法：一边是以色列，一边是哈马斯。眼看着机会来临的
哈马斯自然是一分钟也不耽误：哈马斯宣布，将于9日起不再承认阿巴斯的巴勒斯坦民族权力机构主席地位。
    在这一轮的加沙冲突中，有一个现象大家应该都注意到了：埃及居中调停最卖力。
    其实，不是他想当和事佬，他是身不由已，被美国逼到前台来的。因为只要他愿意配合以色列，足以困死哈马斯，根本不用以色列动手打。但是，埃及
现在不想做阿拉伯世界的叛徒了，所以，他不愿意配合以色列。
    现在美国就逼他了：你不配合我困死哈马斯可以，你必须逼哈马斯停止向以色列发射火箭弹。而哈马斯停止发射火射弹的前提是以色列解围加沙。这又
是以色列不能接受的，因为这样做的结果就意味着放任哈马斯做大。随着哈马斯势力的壮大，法塔赫在巴以和谈中的重要性就迅速衰减——阿巴斯早就不代表
阿拉伯世界的利益了。
    现在，哈马斯已经喊出来口了：不承认阿巴斯的地位。为什么？因为他有能力把法塔赫顶到一边去了。以后，巴以和谈的双方，一方是以色列，另一方
，就是哈马斯了，至于法塔赫，彻底出局可能没那么快，不过他的用处就小多了。
    以色列的背后肯定是美国，哈马斯的背后是谁呢？俄罗斯，中国。
    虽然中国对哈马斯没有太直接的支持，伊朗可没少支持哈马斯，而中国和伊朗可是有直接的利益捆绑的。这就是为什么我们的外长杨洁篪专门应约在9日
和伊朗外长穆塔基通电话呼吁加沙停火的原因。所以，奥巴马那边放风与哈马斯接触其实就是在承认中国入了巴以和谈的局。至于欧盟，以后的巴以和谈会
有他的椅子，不过以后他说话就没人听了。
    在中国的态度表明了之后，外交部发言人秦刚马上宣布，中国中东问题特使孙必干将于近日访问埃及、以色列和巴勒斯坦，目的嘛，“推动加沙紧张局势
走向缓和！”
    萨克奇“总统”空跑了一趟中东没成功的事，我们的孙“特使”能成功吗？让我们拭目以待吧，因为这是中国第一次走进巴以和谈。
    今天，我们中国人有理由欢呼，因为我们杀进了美国的经济心脏！我们攻破了美国的最重要防线！美国人看我们脸色的日子来到了！
    大手笔的胡主席，终于在低调中带领着一个伟大的民族重新走向了世界！

    回首往日：从《反分裂国家法》稳住阵角，到朝核爆破主导东亚局势，再到1000亿美元与伊朗经济捆梆坐庄伊核，再到今天杀进巴以和谈，一步一步，
走得扎扎实实稳健无比。我们有理由期待，21世纪是中国的世纪，而胡主席，必将是继毛主席之后中华民族的第二个伟大领袖。这是中华民族的幸运，也是
上苍对崛起中的龙的传人的最大赐福！


** 【金鸿评论】加沙冲突局势追踪（2009/01/08）
[2009-01-08 19:54:29]



这一轮的加沙冲突引暴了大新斗争的洗牌。

借着这一轮的冲突，大国之间展开了利益交换和权利斗争。美国主动揭开了加沙冲突的盖子，率先对欧盟发牌，逼欧盟让步。除了加沙冲突这个主战场之外，
还有几个分战场：

【金鸿评论】最抢眼的就是俄乌斗气。俄罗斯借势挑起俄乌斗气，也逼欧盟向自己靠拢。我们就看到了一个有趣的现象：一边是打的热火朝天，一边是斗的冰
天雪地。在欧美俄三方的角斗中，阶段性成果已经出来了，那就是欧盟以放风“绕开乌克兰新建天然气管道”的方式向俄罗斯靠拢，俄罗斯盘面上占优势。

另外，美国好象要借与俄罗斯之间的斗法，把欧盟重新压倒的意思。这一点，可以继续观察，不过，有些信号已经表现的非常明显了。

【金鸿评论】其次就是处在走火边缘的印巴局势。虽然有人无所不用其极的挑起印巴战火，但在严重后果的顾忌下，印度最终没敢迈出这一步。3日巴基斯坦
以“重新开放北约给养物资通道”的方式向欧美展现出自己希望地区局势稳定的诚意。之后得到了欧美的较积极响应。阶段性结果是：印度放低身段，美国让步
，欧盟不出头，中巴占优。

【金鸿评论】第三个比较热闹的地方就是台海。

总体上说，在加沙冲突中表现最低调的就是中国。不过，在自己的家门口，中国是没少了忙活：胡主席亲自高调的对台喊话之后，得到了台湾各届的回应不小
，便马英九迟迟没有回应。于是，就传说了胡主席在在内部场合对马英九评价（“我们把他看得太高了！”），这一敲打之后，马英九马上就有了点回应，不过
，马英九的回应不能让人满意，看来，胡主席想和谐台湾是很困难了。还是稳住台湾几年后动武比较实在，到时把那些杂七杂八的玩艺全部收拾了也利索，别
弄的跟香港似的，还养着一帮吃里扒外的东西。

眼看着中国要统一台湾，日本自然沉不住气了，在目前的大气候下，强行挑动局势他又没这个本事，只好拿着“与台湾举行民间渔业磋商、讨论钓鱼岛近海捕
鱼权”这类事情来试探美国的反应，不过，美国的反应让日本人很失望，是什么呢？美国向朝鲜提供的最新一批粮食援助将在本周之内运抵朝鲜！

总体上说，在这一片：中国主导，日本沦落，美国边缘化。

【金鸿评论】随着大国斗争的发展，各方在伊核问题上的权利也在发生微妙的变化。美国越来越倾向于与伊朗缓和，欧盟的中间人角色越来越不重要。随着欧
盟在伊核问题上的边缘化，欧盟在巴以和谈问题上也越来越无足轻重了。而俄罗斯趁机想扩大影响力，一个比较大的动作就是1月4日的时候俄罗斯总统特使萨
尔塔诺夫提出的充当以色列与哈马斯接触的中间人的提议，当然，以色列外长拒绝了这个建议。显然，美国还打算用巴以和谈来诱惑一下欧盟。丢了面子的俄
罗斯反手就是一击：有消息称，俄罗斯正在测试最新的S-400防空导弹系统，预计它将提供给俄罗斯在中东的盟国。俄罗斯的中东盟国会是谁？叙利亚的可能
性比较大。现在该轮到以色列挠头了。

【金鸿评论】不过，还有更让以色列心烦的事情，这也是一轮加沙冲突中最有戏剧性的一幕：1月7日晚，埃及向哈马斯发出最终通牒，要求哈马斯在当地时间
1月8日上午6点之前对埃及停火方案做出答复。与此同时，以色列空军对加沙南部城市拉法和费城走廊地带的走私地道进行了猛烈的轰炸。看这阵势，大有压
垮哈马斯之势。

其实，埃及这样做并不是重新倒向了美以，而是专门采用的一种自我减压方式而已。说的通俗一点，埃及的喊话应该这么理解：各位老少爷儿们，我这边压力
太大了，我自己已经替哈马斯扛不住了，大家快来搭把手吧。埃及这么一喊，果然有人出来帮忙了：

就在埃及给哈马斯的最后期限到来前的几个小时，也就是８日的早晨，以色列北部地区遭到多枚来自黎巴嫩的火箭弹袭击，至少２人受伤。火箭弹是谁发射的
呢？黎巴嫩真主党说不是他们干的，哈马斯也说不是自己干的。那这到底是谁干的呢？据说是个“不知名的巴勒斯坦组织”。不过，就在7日黎巴嫩真主党的老
大纳斯鲁拉还呼吁“真主党抵抗力量做好准备以应对一切可能发生的局面。”动手的居然不是真主党的人，这可真怪了。

眼看着以色列把哈马斯打的满地找牙，旁边的真主党撸着袖子吐着唾沫在旁边咬牙较劲，突然，从后面一块板砖扔了过来砸了以色列一下子，以色列定睛一看
，砖头是从真主党所在的方向扔过来的，可人家真主党说了，不是他干的。哈马斯也说，我刚刚正趴在地上呢，也不是我干的。以色列蒙了，妈的，是谁扔的
砖头呢？唉，这个哑巴亏吃的﹍﹍真有点不是时候。

现在，那些准备继续向埃及施压的人该琢磨一下了：再这么打下去真主党会不会被卷进去？如果真主党也下了水，，再打下去整个阿拉伯世界会不会也跟着下
水？如果真那样，又一场中东战争可能真要开打了。

在这样的背景之下，阿盟自然有本钱抬高一下嗓门了：1月7日，阿拉伯国家表示决不接受一份不具有约束力的主席声明，决心推动安理会立即就它们早先提出
的决议草案进行表决。为什么会出现这样的情况？因为两年前的黎以冲突把真主党打成了阿拉伯世界的英雄。现在，是不是再让以色列重打一回？估计战果还
不如上一回呢！因为上一回至少欧盟还敢扛一把，这一回他可是一点本钱都没了。

阿盟的高调不是冲着别人，对象还是欧盟。阿拉伯人的意思很直白：既然你们跑前跑后那么忙活都没有替我们争取到利益，那以后就不要再辛苦了，巴以和谈
谈判桌上的椅子不是随便一个人就可以坐的，还是换人好了。该换谁呢？看看谁在一旁不吱声，估计就是他了。

【金鸿评论】这一天，我们已经等了很久很久。巴以和谈，到了换一种玩法的时候了。从去年322入联公投之后，中国就开始全力以赴的把巴以和谈的桌子上
挤了，没想到费了这么大劲才成功，真不容易呀。

【金鸿评论】从加沙传来的最新消息是以色列又遇到了新一轮的来自黎巴嫩方向的火箭的问候，而以色列军方的反应是：“正在考虑还击！”其实，他哪是在考
虑怎么还击？明明是在等待美国的指令！而埃及也在致力于“三天之内促成加沙停火”，看来，加沙冲突这几天真的要结束了。




** 金鸿时局评论（09/01/21）

[2009-01-21 16:56:09]


【金鸿评论】首先全景式的展示一下十天来加围绕加沙冲突各方展开的行动，从这里面我们可以发现很多有趣的东西：

9日，联合国安理会通过停火决议。因为代理人背后的人的利益没有得到满足，所以，以色列说：我们要继续打下去；哈马斯也说：停火协议管不着我们。

10日，布什开价：只有哈马斯先停止向以色列境内发射火箭弹、停止走私武器才能实现加沙持久停火；普京也开价：只有乌克兰签署了对乌克兰过境运输天然
气进行监督的多方委员会的议定书后才能供气。10日晚，以色列说：对加沙我们还要再炸几个星期；俄罗斯说：乌克兰在签署的成立过境输气监督机构的议定
书中加了内容，我们不会用这份议定书。俄罗斯的意思很明白：我就不信我拖不住你欧盟的后腿！

12日，中国中东问题特使孙必干在埃及提出了中国政府对于目前加沙局势的五点主张。当天的哈马斯有如神助，获得了先进的防空武器，击落了一架以军直升
机；以色列则破天荒的表态：讨伐哈马斯的战争结束在望；看着大家都在“有事好商量”，俄罗斯也说，已经做好尽快向欧洲供气的准备。

13日，以色列向加沙城发动了最猛烈打击，希望在停火前做大可能的摧毁哈马斯的有生力量，如果上帝保佑，甚至可以炸垮哈马斯；不过，以色列很快受了警
告：有“不明身份”的人员从约旦境内向以色列巡逻队开枪射击。识趣的以色列马上表态，将派高级谈判代表前往埃及与哈马斯进行“决定性”对话！

14日，俄航母库兹涅佐夫海军上将号日前抵达叙利亚港口，同日，俄罗斯外长拉夫罗夫与以色列外长利夫尼通电话，要求尽快停止加沙地带的流血冲突。拉夫
罗夫在打电话之余，还写了一篇文章，说俄罗斯与欧盟将建立战略伙伴合作机制。

15日，巴勒斯坦和以色列已达成停火协议，协议将在15日之后的“72小时之内”生效；巧得很，俄乌两国总也理通电话，商定17日在莫斯科举行工作会晤，解决
对欧洲供气问题——俄乌之间也搞了一个“72小时之内” 。

16日，内贾德和马沙尔“意外地”出现在了阿拉伯国家紧急峰会上。马沙尔表态，拒绝接受以色列的停火条件，并号召阿拉伯国家断绝同以色列的所有联系。叙
利亚总统巴沙尔马上响应：无限期停止与以色列之间的非直接和谈，并号召所有与以色列有外交关系的阿拉伯国家关闭以色列大使馆（不知道叙利亚的强硬与
那艘“目的不明”的俄罗斯航母有没有关系）。紧接着，卡塔尔和毛里塔尼亚两国决定冻结与以色列的关系。土耳其也跟着凑热闹：“由于以色列无视联合国决
议继续对加沙发动进攻，应该取消其联合国成员国资格！”之后，阿拉伯国家首脑紧急会议发表声明，强烈谴责以色列对加沙的入侵。

承受不住压力的以色列装模做样的表示：内阁将于17日就是否在加沙地带实施单方面停火进行投票。俄罗斯总理普京也表示，恢复向欧洲提供天然气的协议将
很快达成。

18日，以色列将单方面停止在加沙的军事行动，不过停火后以色列军队“将在加沙停留数天”。哈马斯则称将继续抵抗“直到以军撤出加沙”，并且说到做到的向
以色列南部发射了6枚火箭弹，以色列军方也中规中矩的“就事论事”，只对加沙地带北部的火箭发射点进行了一次空袭。眼看着以色列变乖了，哈马斯宣布，
停火一周，不过，以色列必须在此期间从加沙撤军，并开放加沙地带口岸允许救援物资进入。

当日，俄乌两国也就解决两国天然气争端问题达成了协议，俄罗斯将重启过境乌克兰输往欧洲的天然气，但是快要被俄乌斗气折腾出神经病的欧盟却却再也不
敢相信俄罗斯与乌克兰的话——对协议能否得到执行“保持谨慎”！

19日，以色列国防军又说：以军没有撤出加沙地带的具体时间表。其实，这哪里是没有时间表，完全是在看新上台的奥巴马的开价能否把欧盟吸引过来，实现
攻打加沙的目标。不过，20日，欧盟选择了深化与中国的互利合作。当天下午，以色列军方自打耳光，撤出了在加沙地带的剩余部队。

【金鸿评论】从这十年天的你来我往中可以看出，这一轮的加沙冲突铸定与俄乌斗气结下了不解之缘：挑起这一轮加沙冲突的是美国，美国是希望以加沙冲突
为筹码，逼欧盟配合自己的伊核政策和在阿富汗增兵。而俄罗斯顺手挑起俄乌斗气也是在向欧盟叫牌：必须得向自己靠拢，否则冻死你们！所以，加沙打得紧
的时候，俄乌也吵的狠，加沙停火了，俄罗斯也供气了。当然，面对着美俄的同时施压，欧盟选择了与俄罗斯合作，也就是拉夫罗夫笔下的“俄欧战略伙伴合
作机制”。

加沙冲突和俄乌斗气的转折点发生在12日，中国的中东特使出访中东。从这一天起，加沙冲突开始出现停火迹象，而乌克兰以“将使用俄罗斯的天然气作为将
俄天然气输往欧洲的技术性耗气” 主动挑起新一轮的斗气，在此之前，是俄攻乌守。

应该说，在12日之前，斗争的主要是美俄欧三家，美欧双双出手拉欧盟（不过都是拿着刀子逼）。随着中国的介入，俄罗斯的主动权得到了加强，因为中国加
入巴以和谈对俄罗斯是个强有力的支持，而力阻欧美联合、把欧盟拉入自己的怀中也是俄罗斯崛起的必然选择。这也是俄罗斯从一开始就无怨无悔的冲在前面
的原因。中国介入之前，美国在俄乌斗气上是持让步态度的，但是中国介入之后，美国的态度来了个180度大转弯，这是为什么呢？因为之前美国是希望用自
己的退让换取欧盟的阿富汗配合，可惜一直没等到；而中国介入之后，欧盟更不可能向自己靠拢了，无奈之后，美国只好干起了损人不利已的勾当：我过不上
好日子你也别想过清净日子。

所以，在这一轮斗争中，最被动的就是欧盟。特别是在俄乌斗气中，欧盟是个不折不扣的受气包，还是欧盟委员会主席巴罗佐说的很实在：欧盟已成了俄乌斗
气的“人质”，欧盟的天然气供应安全成了俄乌双方手里的筹码，这种局面对欧盟而言是“不可接受”的！不过，欧盟能怎么反击呢？强力警告乌克兰：“如果想
靠近欧盟，那么（乌克兰）在输欧天然气问题上就不应制造麻烦！”如果乌克兰不听话的话，那么将会“失去欧洲信任”。所以，让乌克兰挑事的后果是美国人
自己搬起石头砸自己的脚。

【金鸿评论】在这一轮的斗争中还有一个受气包，就是以色列：黎巴嫩有人扔火箭弹过来，约旦有人打黑枪，卡塔尔和毛里塔尼亚跟他冻结关系，伊朗又在要
求他消失了﹍﹍真不知道等真主党把法塔赫全部干掉以后以色列的日子该怎么过。

【金鸿评论】现在，奥巴马上台了。不过，在他上台之眼，内贾德就开始给他上眼药了：美国新政府应首先改变干预国际事务的政策。美国对各种事务的干涉
只能限于美国领土范围。中东及世界其他地区都不受美国“管辖”，世界人民也没有赋予美国管理国际事务的权力。

实事求是的说，内贾德说的没错，不过，这相当于宣布：世界警察被人撤职了。这个下马威对于奥巴马而言，不可谓不狠！

有内贾德的要求扔在这里，奥巴马算是被判了死刑了。他这八年肯定连布什那八年都比不了。可以预料的是，奥巴马只能选择与伊朗对话。那伊拉克的烂摊子
呢？阿富汗呢？与美国拥有相同价值观念的欧盟将何去何从呢？

我们不希望美国从伊拉克撤军，因为这将有利于美国继续失血。但是撤军也许是奥巴马不得不做出的决定，时间大约在一年之内。之后的阿富汗会变成一块“
食之无肉弃之有味”的鸡肋，而最终选择撤军也是奥巴马不得不做的一件事，时间应该不会超过三年。

至于中国，看看我们的特使，到中东走一圈子就能让加沙停火，就知道我们在巴以和谈上的份量了。所以，我在此劝告那样不自信的中国人一句：切勿妄自菲
薄，我们本来就是一个强大的国家！

另外，能让温和的沙特有胆量公然宣布可能放弃 “阿拉伯和平倡议”的人会是谁呢？


** 温家宝接受金融时报专访:中国救不了资本主义
[2009-02-03 10:06:01]


    新华网伦敦2月2日电中国国务院总理温家宝1日在伦敦接受英国《金融时报》主编巴伯的专访，就中国应对国际金融危机、保持经济平衡较快发展及其他
问题回答了提问。全文如下：

巴伯：温总理，我下次再去中国，希望去中国的农村看看，而不仅仅是大城市。

温家宝：非常欢迎你去。你可以随便问。我给你讲的一定是真话，但是我不一定把所有话都告诉你。

巴伯：温总理，非常高兴能够采访您。本周您也访问了达沃斯。在达沃斯，人人都在谈论如何重树信心的问题。有人也谈到要恢复信心，需要解决银行业的问
题。中国面对目前的金融危机可以采取哪些措施以恢复信心？

温家宝：我这次出席达沃斯论坛和访问欧洲，可以说是一次“信心之旅”。我带来了中国应对金融危机的信心，也带来了同欧洲加强合作，推进全面战略伙伴关
系的信心，带来了世界携手共进，共渡时艰的信心。我对中国经济应对危机的信心是建立在科学态度和求实精神之上的。主要表现是，信心的来源在于我们对
形势的正确判断；来源于改革开放30年形成的强有力的物质基础和良好的体制；来源于中国有一个稳健的金融市场体系；来源于中国有广阔的市场潜力和回旋
余地；最重要的是来源于政府坚决果断的决策，决策的力度和决策的速度。

巴伯：现在中国政府出台的经济刺激方案规模是否足够大？是否需要采取进一步的措施？

温家宝：应对金融危机必须有足够的规模刺激经济增长。但是这个措施应该是完整的、全面的，标本兼治，远近结合。我可以把我们一揽子计划概括为五个方
面。第一，扩大内需，大规模增加财政投入。第二，调整和振兴产业。第三，大力推进技术改造。第四，建立比较完善的社会保障体系。第五，保持金融的稳
健以支撑经济。需要我说一下数字吗？

巴伯：您可以举一两个证明您的观点。

温家宝：我们将在两年内投入4万亿元人民币扩大内需，特别是消费需求。我们将投入6000亿元来推进科技创新。我们将投入8500亿元，来推进医药卫生体制
改革。金融危机还没有见底，我们将密切关注形势的变化，及时果断出台新的措施，使所有这些措施的效果产生在经济衰退之前。这样做事半功倍，否则将事
倍功半。

巴伯：许多亚洲的经济学家看到中国ＧＤＰ第四季度大幅下滑，好像是摔下悬崖一样。您是如何评价的？

温家宝：中国去年全年ＧＤＰ增长9％，去年第四季度增速大幅下滑，增长6．8％。由于金融危机的影响，外需减少，企业经营困难，部分行业产能过剩，经
济下行压力加大，失业人数增加。我们的确面临极大的困难。你会问我，在这种情况下，为什么你还有信心？

巴伯：温总理，您猜到我脑子里在想什么了。的确，我在思考为什么您这么有信心，认为中国经济如何奇迹般地在2009年实现8％的增长目标？

温家宝：是8％左右。

巴伯：您如何使那些统计专家相信中国能实现8％的经济增长目标？

温家宝：取决于四个因素。第一，你所采取的这些政策措施一定是正确的、管用的。我们所有的这些措施都旨在刺激实体经济，刺激最终消费。这次金融危机
对中国经济的影响也主要在实体经济。第二，出手要快。中央财政去年12月份1000亿元的投资从项目到资金已经完全到位。春节以前第二批1300亿元的投资从
项目到资金也已经完全到位。第三，出拳要重。特殊时期必须采取特殊手段，不拘常规。决策的速度和执行的力度决定成功和失败。第四，工作要实。我们在
去年年底到今年年初很快实行了家电下乡，农机下乡，汽车下乡。今年1月1号开始，实行增值税转型，减轻企业负担1200亿元。这些措施都到位了。

巴伯：我认为在这个方面的消费需求是相当重要的，有这样一种观点，说消费者需求是具有爱国主义色彩的，对此您赞同吗？

温家宝：我们不简单提这个口号。但是我们认为促进经济发展还要靠最终消费。

巴伯：但这个口号还是很吸引人的。

温家宝：群众是否消费，消费多少，不在口号，而在他手里有没有钱，在于市场有没有适销对路的产品。在这方面，我们做了几件事情。今年年初，我们给
7400万低收入者发放了一次性补贴，每人100到150元。我们连续第四年提高企业退休职工的退休金，增长10％，每人110元。我们提高了最低生活保障水平，
给低保和抚恤人员增加补贴。我们还做了一件事情，就是对1200万教师实行绩效工资制度，使义务教育阶段的教师工资与公务员的工资达到同一个水平。群众
有钱了，就可以消费了。我给你讲一个故事，就是我们从元月20日开始到12月31日为止，对购置1．6Ｌ以下的汽车实行购置税减半的政策，第一天汽车销售火
爆，连库存都卖光。

巴伯：待会儿我还想问温总理几个关于这次国际金融危机的国际层面的几个问题。但在这之前，我想再问一个有关国际金融危机对于中国农村的影响的问题。
您原来曾经说过，您到过中国2000多个县，那么我想问的是现在农村出现失业人数增多以及农民工返乡的现象，您认为会不会影响社会稳定？中国政府将采用
什么具体的措施来应对这方面的挑战？另外一个问题是有人说中国政府可能用8000亿元来给中国农业银行注资，我想问一下是不是有这样一个决定。

温家宝：当我担任副总理的时候就分管农村工作，我当总理以后一直把农村工作放在全部工作重中之重的地位。西方的一些人很难理解。这次金融危机，由于
部分企业的裁员，大约1200万农民工返乡。会不会造成社会不稳定？其实在这里我要给你讲一讲，中国农民工进城务工总计两亿人，跨省流动的1．2亿，由于
金融危机回乡的到目前为止是1200万。由于农民工是流动的，也就是说，城市有活干的时候他就进城，城里没有活干的时候他就返乡。乡里绝大多数还保留他
的土地。土地是农民最大的社会保障。我们应该感谢农民工，他们为现代化建设做出了贡献。在金融风波当中，他们又成了劳动力一个大的蓄水池。中国农业
银行是我们五大银行最后一家进行股份制改革的银行。应该在这里说明一个情况。正是由于中国在十年前就开始了银行的改革，包括剥离不良资产，建立现代
企业制度，实行股份制改革，才使得中国的银行资产规模，资产质量，利润水平，不良贷款率和资金流动性都保持比较好的水平。农业银行改革我们要把握好
四点。第一，坚持为农服务的方针。第二，继续剥离不良资产。第三，政府予以注资，充实资本。第四，实行公司治理结构改革。

我们农行最后决定注资大约是300亿美元，相当于2000多亿元人民币。

巴伯：谢谢。刚才您谈到，中国为刺激经济增长所出台的大型一揽子计划，我想国际社会，特别是美国，也期待中国采取更多的措施，上周针对人民币汇率问
题中国面临着巨大的压力，比如美国新任财长说中国在操纵人民币汇率，您决定将采取怎样的措施来说服美国采取更照顾中国关切的态度，您对中国操纵人民
币汇率的说法有何态度？

温家宝：说中国操纵人民币汇率是毫无根据的。我们从2005年下半年开始实行人民币汇率形成机制改革。3年多来，人民币汇率对美元有效升值21％，对欧元
升值12％。我们实行的是以市场供求为基础，参照一篮子货币，有管理的浮动汇率制度，这种制度符合中国现实、国情和需要。

我想讲一个观点，就是保持人民币在合理均衡的水平上基本稳定，不仅有利于中国，而且有利于世界经济，也有利于当前世界克服金融危机。许多人没有意识
到，如果人民币汇率大起大落，将是一场灾难。

巴伯：温总理，根据您刚才回答的，是不是可以这样理解，您还是认为，中国政府应该坚持10年前所作的决定，即排除人民币贬值的可能性。

　　温家宝：我刚才已经说的非常清楚，我们实行的有管理的浮动汇率制度，在合理均衡的水平上保持人民币汇率基本稳定。

巴伯：温总理，现在我们知道，国际金融危机至少源于美国，美国有很多风险管理和监管领域的错误，但是也有人说，这场金融危机一部分的原因也是由于世
界经济失衡，比如他们指出，中国有2万亿美元的外汇储备，对持这种观点的人，您有什么回应？

温家宝：我认为这种观点是荒谬的。这次金融危机始作俑者是某些经济体自身经济的严重失衡，主要是长期的双赤字，靠借债保持的高消费。对一些金融机构
，长期失去有效监管，使他们利用高杠杆率来获取巨额利润，一旦泡沫破灭，灾难就留给了世界。一个有13亿人口的发展中大国，目前人均ＧＤＰ水平只相当
于英国的十六分之一。我们急需资金进行建设，改善民生。那些靠举债而过度消费的人反过来责难借给他钱的人，这不是颠倒是非吗？中国有句话，叫猪八戒
倒打一耙。我在达沃斯谈到这个观点的时候，大家是赞同的。

巴伯：温总理，我想恐怕中国还需要继续购买美国国债吧？

温家宝：这件事确实很敏感，我们毕竟有巨额的外汇储备，这些外汇储备是需要加以经营的，购买外国国债是一种方式。但是是否继续买，买多少，将根据中
国的需要，并且按照外汇安全、保值的要求来决策。我们希望美国经济好转。我们也认为，当前稳定国际金融市场，对应对经济危机，提升市场信心，使国际
经济尽早复苏是有利的。

巴伯：有人提出这样一种呼吁，希望中国在外汇储备中拿出一部分钱流转到国际货币基金组织，以换取在国际货币基金组织中更大的投票权，作为应对金融危
机的办法，中国对于这种说法有何态度？

温家宝：我们主张，首先要改革国际金融机构，包括国际货币基金组织。要增加发展中国家的份额，代表性和话语权。同时也要加强对国际金融机构贷款的监
管，资金使用的监管。

巴伯：我问您这个问题是因为30年以来，很多人说只有资本主义才能救中国，可是现在他们恐怕要转变观点。很多人说只有中国才能拯救资本主义。

温家宝：我不这么看。我头脑是清醒的。因为我们是一个有13亿人口的发展中国家。我们面临的任务是十分繁重的。我们要走的路还十分漫长。如果你到中国
东部的城市，和伦敦差不多。但是你到中国的西部地区和农村，差距就很大。我坚定地认为，把中国的事情办好，就是对人类最大的贡献。我们坚持“三要”，
就是要标本兼治，不要头疼医头，脚疼医脚；要加强合作，不要以邻为壑；要把自己的事情办好，不要把麻烦推给别人。

巴伯：那对美国而言，美国总统奥巴马是不是在这个问题上给过一些保证呢？

温家宝：从竞选演说到执政很短的一段时间，我们看到美国新政府的表态。我们希望尽快同美国政府进行接触，因为保持中美两国之间的这种合作关系有利于
整个世界的稳定、和平与繁荣。

巴伯：在这个问题上，我想进一步地再提一个问题。您这个回答是不是可以这样理解，就是到目前为止，美国新政府，或者说奥巴马总统还没有向中国政府明
确保证美国政府不会把人民币和其他有关问题以咄咄逼人的方式加以利用来逼迫中国，或者是更愿意在这些问题上照顾中国的关切？

温家宝：在前天奥巴马总统与胡主席的通话中，他表明了愿意与中国加强合作的态度。但是美国内部也还是有杂音。因此我希望贵报替我传递一个信息，我们
希望加强合作、共同应对危机。这是大局，符合两国根本利益。

巴伯：我想呢，可能这个问题如果说存在的话，更多的是存在于美国国会中。对于美国国会您有什么信息？

温家宝：美国的自身制度我们不加以评论。但是最终起决定作用的还是美国政府的决策。他们应该用长远的、战略的眼光看待中国。在当前，特别应该紧紧围
绕携起手来、共同应对金融危机、克服困难这个中心，推进中美两国建设性的合作关系。

巴伯：我还想在这里提一个有关中国外汇储备的问题。现在中国政府是否打算使用部分外汇储备刺激国内经济增长，比如说用于财政投入。

温家宝：外汇储备是一个国家经济实力的表现。我们正在研究外汇储备如何使用。你们都是专家。外汇储备是中央银行用人民币购买的，是中央银行的负债，
如果财政使用必须发行国债，购买来用。第一，我们正在探讨、探索如何合理有效地运用外汇储备来为我们的建设服务。去年，我们就发行1．5万亿元国债，
购买了2000亿美元的外汇，由中投公司运营，包括通过企业对外投资。第二，外汇必须用在国外，用在对外贸易和对外投资。因此我们希望用外汇来购买中国
亟需的设备和技术。这是一个很专业的问题。

巴伯：现在国际社会对中国的期望越来越高了，中国也在采取进一步的措施加强研究可再生能源的投入力度。今年晚些时候将在哥本哈根召开气候变化的国际
会议。中国会不会在会议上签署有关气候变化的条约？

温家宝：我前天在布鲁塞尔同巴罗佐主席专门就这个问题进行了深入的交谈。中国的观点主要有三：第一，中国支持哥本哈根会议，支持应对气候变化所采取
的各项积极措施，支持发展绿色经济，而且认为发展绿色经济很可能是应对金融危机的一个新的经济增长点。第二，在应对气候变化上，中国是高度重视的，
成立了以我为组长的国家领导小组，并且制定了第一份应对气候变化的国家方案，据我知道，这也是发展中国家的第一份国家方案。我们在“十一五规划”中已
经制定节能减排的约束性目标，也就是每年单位ＧＤＰ的能耗要降低4％，5年降低20％。前两年我们没有完成任务。2008年我们完成了。我们还将继续把这种
做法长期坚持下去。这也可以看作是中国自我限制的一种办法。第三，中国难以在哥本哈根会议上承诺量化目标，因为中国还处在发展中。欧洲已经有几百年
工业化的历史。我们才有几十年。我们有13亿人口，但人均温室气体排放量比发达国家低得多，累计排放更低。但是我们仍然抱着积极的态度加强同欧盟的合
作，特别是在节能减排、低碳经济、环保技术上。

巴伯：温总理，在采访之前，有人告诉我，要问和政治有关的问题，得特别小心。

温家宝：可以随便问。

巴伯：有人说问这个问题得特别小心，因为用中国人的话来说，如果不小心就会被“戴帽子”、“穿小鞋”。谈到中国未来政治体制的发展，您认为能不能在10年
内实现中国全国人民代表大会代表的直选？

温家宝：其实经济和政治是不可分的，我还是想从经济的角度来回答这个问题。我们正在进行的是经济体制改革和政治体制改革。这两个方面都是重要的。没
有政治体制改革的成功，也不能保证经济体制改革的成功。政治体制改革的目标就是要建设社会主义的民主政治，保障人民民主选举、民主决策、民主管理和
民主监督的权利。我们要建立的社会应该是一个公平正义的社会，是一个让每一个人在自由和平等的条件下得到全面发展的社会。这就是我为什么很喜欢阅读
亚当·斯密的《道德情操论》的原因。亚当·斯密于1776年出版了《国富论》，他也写了《道德情操论》。在《道德情操论》里有一段非常精彩的论述，他说，
如果一个社会的经济发展成果不能真正分流到大众手中，那么它在道义上将是不得人心的，而且是有风险的，因为它注定要威胁社会稳定。我一直认为，公平
正义是我们社会主义制度的首要价值。在西方人看来，中国人好像怕民主、怕选举，其实不然。我今年在记者招待会上曾经讲过，只有人民信任你，人民才能
让你坐在台上。我们现在实行的是村级的直接选举，乡、县和不设区的市人民代表的直接选举，县以上实行的是间接选举。但是我坚信，群众能管好一个村，
就一定能够管好一个乡，一个县，也就能够管好一个省。但要按中国的实际情况，发展具有自己特色的民主方式，循序渐进。

巴伯：所以就可以进一步拓展民主，提高民主的水平，让人民可以发表不同的看法。

温家宝：是的，一个政府不应该怕人民，应该创造机会让人民监督和批评政府。

巴伯：我想，您又一次知道我在想什么，因为准备采访时我也有自己想引用的亚当·斯密应对金融危机的话。其实这句话也是来自您最喜欢的《道德情操论》
。

温家宝：这本书很长一段时间不引人注意，我觉得它的意义不亚于《国富论》。他只有两次在《国富论》和《道德情操论》里提到看不见的手，一只看不见的
手是市场，一只看不见的手是道德。

巴伯：我可能早都已经记得非常清楚了。不管一个人有多么的自私，但很明显在一个人的本性中总是有一些原则，这些原则让他对其他人的福祉产生兴趣，能
够为他带来幸福感和快乐的感觉。虽然他从别人的福利中并不会得到具体的好处，只不过他得到的好处就是能够看到他人幸福。

温家宝：我很欣赏这句话。

巴伯：再次感谢您能接受《金融时报》的采访。

温家宝：谢谢。


** 内幕曝光：德国人为何敢在中国三峡建巨型化工厂？

[2009-02-08 10:50:08]



金鸿：我不是这方面的内行，有没有内行的人说明一下这里面的内容是否可靠？

2月4日，大年刚过，辛勤的重庆市环保局某人知会某报记者，1月12日，环境保护部部长主持召开常务会议，原则通过了巴斯夫重庆MDI化工项目的环境影响
评价意见。该人士说：“但这还不是最后的结果。”只要环保部的正式批文没下，最终项目是否落户重庆还难说。环保部周部长将亲临重庆考察，就项目具体
细节和重庆市政府进行磋商。

继巴斯夫在南京投资的最大单体项目——扬子石化-巴斯夫一体化项目之后，巴斯夫这家号称世界化工巨头的德国企业将在三峡库区投资一座巨型的MDI项目，
设计25万吨天然气制乙炔单台装置规模和40万吨MDI单台规模，它的“巨”――将成为全球最大的MDI生产基地。据说，这是迄今为止重庆市引进的规模最大的外
资工业投资项目。巴斯夫全球执行副总裁薄睦乐表示，如果获批顺利，MDI项目预计2012年投产。

作为聚氨酯的主要原料，MDI广泛应用于生产PU浆料、PU鞋底原液等，巴斯夫预计未来10年，聚氨酯市场以每年6%左右的速度增长。该项目投产后，将形成年
销售产值500亿元人民币的天然气化工集群，利税超过100亿元，可直接或间接带动库区25万人就业。

这么有效益前景是、又能带动这么多人就业的好项目，巴斯夫集团为什么不把这个项目放在德国本土呢？

他们为什么不把奔驰汽车和宝马汽车总部也搬到中国来？

当然是因为污染和环保。

当然也是因为发达国家向发展中国家转移高污染化工生产企业多少年前就早已经“蔚然成风”。

德国巴斯夫集团总部设在路德维希港，在39个国家设有350多个分厂和公司，位于路德维希港的巴斯夫集团总部和巴斯夫股份公司像一座“小城市”，占地面积
达7平方公里，在路德维希港工作的职工共有5.5万人。巴斯夫的不少产品是从原油和天然气中提炼出来的。巴斯夫拥有自己的煤、石油和天然气资源。近几
年巴斯夫侧重在石化一体化方面发展，以乙烯裂解为龙头，带出一系列产品，第一个项目的产品就是第二项的原料，以此一体化发展。我想，这重庆MDI项目
应该是所谓“一体化”发展的一个不小的部分吧。

如果巴斯夫的重庆MDI项目建成，我把它比成悬在三峡大坝天灵盖上的一个巨型化工厂。

距此25年前的1984年12月3日凌晨，印度中央邦的博帕尔市（Bhopal）美国联合碳化物（Union Carbide）属下的联合碳化物（印度）有限公司（UCIL）设于
博帕尔贫民区附近一所农药厂发生氰化物泄漏事件，2000多名博帕尔贫民区居民即时丧命，之后更有2万人死于这次灾难，20多万博帕尔居民因之永久残废，
现在当时居民的患癌率及儿童夭折率，仍然因这些灾难远比其它印度城市为高。而美国联合碳化物集团，经过在美国和印度多番诉讼，因这次惨剧只向印度
政府赔偿4亿7千万美元，以及出售了该集团持有的联合碳化物（印度）有限公司50%股权，以兴建治疗受影响居民的医院和研究中心。该事件被认为史上最严
重的十大工业灾难之一（博帕尔事件见http://baike.baidu.com/view/603558.htm）。

现在，德国人又敢要在长江三峡水库的天灵盖上建化工厂了。

它一旦出现泄漏、爆炸或者其它任何化工厂都可能发生的事故，将可能形成多大的危害呢？

有媒体记者展示了他们在有关此MDI项目的“环境影响报告书”内容，在报告书中，巴斯夫对MDI项目“三废”的治理和排放将采取一系列措施，如：

MDI预聚过程中产生的废气，将通过废液焚烧炉来焚烧或经专用洗涤剂洗涤后排放，MDI生产工艺尾气含甲苯、甲醛和苯胺，将燃烧处理等。在污水的处理上
，巴斯夫承诺，MDA装置中和萃取工序产生的盐水和MDI焚烧炉产生的烟气洗涤水，去MDA装置盐水精制工序精制后，做重庆天原化工有限公司氯碱装置的原料
，不外排。固废有氨蒸馏废液和精馏残液，将通过焚烧处理。MDA装置产生的废活性碳及污泥，将送重庆市固体废物处理中心处置。苯储罐的废气吸收液将送
焚烧炉处理。在排污方面，化工项目落户地重庆长寿化工园区还实行了公用工程一体化。MDI项目员工的生活污水可直接排入园区污水管网，经园区污水处理
厂进行处理达一级标准后才能排放到长江。除了“三废”,MDI项目还需通过消声、隔声、减振等措施，解决还有来自凉水塔、冷冻机、大功率机泵等连续产生
的噪声，避免扰民现象。

“环境影响报告书”最后称，拟建项目符合国家产业政策；正常生产时所排废气、废水和产生的噪声对大气、地表水和声环境影响较小；项目投产后不会使现
有环境质量发生明显变化；项目建成投产后具有良好的环保、社会和经济效益。

但这份报告书中并没有提到关于巴斯夫集团与环保的另一条资讯，我正可以在此给其补充上：

2008年6月30日，国际环保组织绿色和平在北京召开新闻会，炮轰世界化工巨头巴斯夫集团执行环境信息公开“双重标准”，并且称其上海巴斯夫工厂还存在超
标排污嫌疑。事情缘于2008年4月26日，绿色和平组织曾在正式发布的《企业污染物信息公开状况调查》报告中，将包括巴斯夫、丰田汽车以及宝马汽车在内
的13家跨国企业列入“黑名单”，指责这些企业在环境信息公开方面执行“双重标准”。三天后，巴斯夫通过媒体回应，“巴斯夫在全球和中国执行同样的标准”
，就信息公布方面“完全遵守当地法律”。绿色和平再次指责巴斯夫执行“双重标准”的依据是他们后续的又一次调查。他们通过各种公开渠道收集信息发现，
尽管没有相应法律强制性规定，但巴斯夫在德国、美国和加拿大都主动通过官方网站直接向公众公开其详细的污染物排放信息。而它在中国的所有15个独资
和合资的生产型企业都没有这么做。

曾在环保方面有过如此“劣迹”的这家化工巨头的这份“环境影响报告书”这回就那么可信吗？

但现在，这个号称世界最巨型的MDI化工项目的最终落户重庆决定权似乎就掌握在国家环境保护部的手上了。但在环保部公布的拟批准建设项目环境影响报告
书上还是声称，重庆MDI项目总投资80亿元，环保投资达6.96亿元，废水污染物排入外环境量及废气污染物排放量均满足化工厂最终建设地重庆（长寿）化工
园区及其北部拓展区总量控制要求。

然而，任何化工项目都伴随着高污染、高毒害，在水库区发展化工项目，一直以来在业界都存在巨大争论，去年11月，环保部在重庆专门召开了三峡库区化
工、石化产业环境与发展研讨会，专家认为，西部地区尤其是三峡库区要加快发展，赞成在三峡库区发展化工石化产业；但中国的专家们也明确表示，针对
三峡库区环境敏感因素，必须做到以下几点：库区化工高起点，相关项目达到国际先进水平；严格控制化工、石化产业发展中有毒有害污染物的排放，确保
污染物的累计影响不会威胁库区水环境的安全；按照循环经济的模式进行发展；把环境风险防范作为重点内容加以考虑；统筹制定化工石化产业规划，从规
划角度对发展规模严格控制。

中国人的“虽然…但是…”讲话方式向来滴水不漏，但又让人觉得上面的话没一句有用。

纵然有那份“环境影响报告书”在，其实也没有人敢肯定，这项德国人投资的化工项目绝对百分百安全（世界上根本没有百分百的事），也没有人肯定在三峡
大坝存在的上百年来，悬在它天灵盖上的这个巨大化工厂也可以百年安然无恙。

哎，谁肯想想百年之后子孙们的事呢？

对此，司马还有一忧，一旦战争来临，或者三峡工程可以坚如磐石，但这个巨型化工厂若受以攻击，产生剧烈的污染和泄漏，对整个长江水域和下游地区的
破坏将不可想像。

真佩服重庆官员们的胆量。

2007年3月在全国人大、政协两会上，中国科学院院士赵玉芬等105名全国政协委员联名签署提案，建议厦门PX化工项目迁址，引起了媒体和民众的强烈关注
。20076月1日和2日，据说有超过5000名厦门市民以“散步”的形式，集体在厦门市政府门前表达反对诉求，厦门市政府被迫宣布缓建，并委托中国环境科学研
究院评估可能对环境的影响。最后的结果是，福建省政府和厦门市政府因此决定迁建PX项目。

由翔鹭集团旗下的龙芳烃投资的PX项目，预计工程投资额高达人民币108亿元，是厦门最大的化工项目。每年工业产值可望达到800亿人民币，占厦门市去年
本地生产总值近七成。厦门的PX化工项目，无论从投入规模还是创造效益上说，都高于现在这个被叫成世界最巨型的重庆MDI化工项目。

因为关乎三峡工程的整体安全，关乎三峡库区这一地理地区千百万老百姓的生活安全，有印度博帕尔事件、吉林化工厂爆炸事件、重庆中石化爆炸事件的前
车之鉴，所以，在此最最强烈要求，德国巴斯夫集国重庆MDI化工项目的最终可行性交由全国大人专家委员会表决讨论，国家环保部或者重庆环保局，或者重
庆市政府都没有对此项目最终的决定权。

项目计划中的该项目“年销售产值500亿元人民币，利税超过100亿元，直接或间接带动库区25万人就业”的前景固然吸引人，但实现这个美好前景的前提必须
是这个化工项目对当地人民、对三峡水土、对下游环境的威胁程度必须达到百分之零，否则，即使在百分之一的可能中产生的风险都将是毁灭性的。

我想，这其实才是巴斯夫集团不可能把这个项目设在德国本土的最主要原因吧。

详细报道了重庆MDI项目的《21世纪经济报道》评论说，这个项目“极大考量着库区的环境安全”，但我觉得它们说得还不全面，更全面的说法应该是：它不仅
考量着库区的环境安全，更考量着中国各级政府在关心民生、保护环境、促进民主和推动经济方面的综合、理性而谐调的执政能力。



** 【金鸿评论】贴身肉搏之G20峰会
[2009-03-29 14:15:15]


从三月份初开始写。

【金鸿评论】现如今，大国斗争的核心直指美国的金融霸权。美国要想维护住自己的金融霸权，就必须拆解开中俄欧三方在伊核问题上达到的协作关系。因
为如果拿不下伊朗，美国的大中东计划就失败了，美国的金融霸权也将随着美国全球战略的失败而失去。

所以，奥巴马一上台，就打了一个新算盘，想以东欧反导牌交换俄罗斯的伊核合作，以此离间中俄欧。无奈，今非昔比，只要俄欧合作的好，东欧反导必将
有花无果，俄罗斯用不着在这个问题上求美国；但是，伊核问题上俄罗斯抓的筹码才是俄罗斯手里最有价值的一张，如果俄罗斯就这么轻易的丢了，那普京
不成傻子了吗？结果，俄罗斯一点面子没给奥巴马。

既然巧实力办不能事，只好让以色列打着伊朗能造原子弹的旗号哭着喊着应该打伊朗，结果被伊朗革命卫队司令回了一句，我们有射程超过2000公里的导弹
！再打？以色列也在伊朗导弹的攻击范围之内了，这可怎么打？既然打不得，就接着制裁吧，12日，奥巴马宣布对伊朗的制裁措施延长一年，不过，刚刚过
了两天，中国就和伊朗签了32亿的天然气大单。看来，内贾德说奥巴马比较“幼稚”也是有道理的。

眼看着中国跟伊朗搞合作发大财，俄罗斯眼睛也发红了，怎么办能弄俩小钱花花呢？还是卖军火吧，伊朗不是一直眼红俄罗斯的Ｓ－300防空导弹吗？只要伊
朗出钱，就卖给他！这年头，经济都危机了，现金为王嘛，只要给钱多，别说导弹，就是原子弹都卖！

有了中国和俄罗斯一文一武同时护法，美国再想收拾伊朗就变得难于上青天了。为了防止欧盟借着这个机会也出来敲一把竹杠（巴以和谈），美国开始主动
的低三下四的和伊朗进行“秘密接触”了。接触的结果是什么呢？人家希拉里说了，尽管伊朗非常冷淡，但老娘还打算继续跟伊朗亲密接触！

单纯的看美俄斗法，在经济金融霸权层面，是美国占优势，美国已经成功的把石油打了下去，俄罗斯经济苦苦挣扎在泥潭之中；不过在政治和军事层面，俄
罗斯更主动一点，手里拿着伊核牌的俄罗斯狠撬美国砸在东欧的楔子，逼得美国在中亚和东欧步步后退。再加上俄罗斯对欧盟本身就有优势——石油和军力，
这两点对欧盟来说，都是非常需要的。石油可以解决欧盟的经济发展问题，军力则可以平衡美国的影响力。俄罗斯也是吃准了欧盟的心思，逼着欧盟向自己
靠拢。而欧盟无论在科索沃和平问题上还是与美元争霸的问题上，都是有求于俄罗斯的，不得已以承认格鲁吉亚在俄格冲突中为侵略者的方式向俄罗斯靠拢
，得势不饶人的俄罗斯则顺手让南奥塞梯判格鲁吉亚总统萨卡什维利的刑，以此全面挤出美国在中亚地区的影响力。被逼的快要喘不过气来的美国只好威胁
欧盟，要和俄罗斯建立联合导弹防御体系。天下人都知道美国在东欧的导弹防御体系是冲着俄罗斯来的，现在居然要和俄罗斯联手搞了，这下子热闹了。美
国和俄罗斯倒是可以化敌为友了，对欧盟来说无异是开门揖盗，一个黑心的美国还没赶走，又来了一头贪心的北极熊。欧盟该做何打算呢？

【金鸿评论】虽然欧盟是中俄欧美四方中军事实力最弱的一方，但是中俄美三家也非常明白，把欧盟拉到自己这边来的好处是巨大的。美国知道，拉过欧盟
就可以对中俄进行强行封锁；俄罗斯知道，拉过欧盟就可以重振雄风；中国知道，拉过欧盟就可以横行天下。欧盟也是吃准了三家的心思，所以处处挟身自
重。当然，它也没别的办法。既想捞好处，又没有力气顶在前面，只好处处借力打力，狐假虎威。美国为了拉过欧盟，就在非洲做文章，拿着苏丹总统扎垡
子，要抓苏丹总统。可惜，这边还没出手呢，就有人出来大喊刀下留人了。出声的是海合会和伊斯兰世界联盟，不过，幕后的主使应该就是沙特了。沙特的
亲华行为自然招来了欧美的咬牙切齿，所以，英国出头对沙特含沙射影。不过，结果并不理想，看来，沙特是铁了心跟着中国混了。

【金鸿评论】在美国眼里，最大的敌人是中国。如果没有中国这个强敌，无论是收拾欧盟还是俄罗斯，都是易如反掌的事。所以，美国在中国身上花的代价
也最大。无论是在南海，还是在巴基斯坦。

南亚的事大家都看到了，虽然一开始菲律宾跳的够高，可中国的渔政军一到，菲律宾亲美派（特别是军方）马上老实了。至于日本，就更不在话下了。有许
多人老是抱歉北京办事太窝囊，不够强悍，其实，只有那些没实力的国家才怕被别人看扁了，整天想着表现表现自己，在家门口，我们的优势是无人能及的
，不信就看看两件小事上各家的表现就知道了：

日本说，麻生因为家事缠身无法按期访华，北京却非常自信的说没这事，该什么时候来他还会什么时候来；北京说，该菲官员因为家里有事要推迟访菲，菲
总统府则说，菲中关系仍然强劲。

【金鸿评论】倒是巴基斯坦那边非常麻烦。不能不说的是，穆沙拉夫在台上的巴基斯坦还是非常稳定的，可这位老兄脸皮不够厚，你就是死抱着军权不放谁
还能把你赶下去不成？结果自己刚刚把军权送了人就为人轰下台去了。上来个扎尔达里上人心里很不爽，看这位老兄怎么干吧。说不定哪天把巴军方惹火了
，就被清场了。

不过，事到如今，再想以切断巴基斯坦通道的方式威胁伊朗已经晚了，现在金融危机已经深化到了美国必须交出一部分金融权利的地步，美国再想通过在伊
核问题上翻盘、进而重振大中东计划、捆死中俄欧已经来不及了。所以，如果美国继续在巴基斯坦边境上玩狠的，结果极有可能是把扎尔达里玩下去，军方
重新上台。那时，对美国更不利。

【金鸿评论】当然，美国可以在中国的家门口一把火一把火不停的放，我们也是来而不往非非也。这段时间金正日在那里一刻也没闲着，在桌子上不停的变
着魔术，一会儿手里拿了颗导弹，一会又变成了卫星，嘴里还不停的叨念：“我的原子弹哪里去了？一二三，看我变，快出来，原子弹！”害得奥巴马整天提
心吊胆的，生怕老金再闹大了。当然了，表面上，不论是美国还是日本韩国，个个都硬的要死，日本说，我们可以用 “星球大战之子”干掉朝鲜导弹，韩国也
说，我们有祖传的“世宗大王”！希拉里更是威胁朝鲜里：“朝鲜试射导弹将付出代价，会影响六方会谈的！”真不知道希拉里是不是真过糊涂了，难道金正日
真的比内贾德好对付？到是美军北方司令部司令说了句非常有意思的话：美军将朝鲜视为“非常有限的威胁”。既然是小意思，何必一家人兴师动众呢？哄谁
呢？

还有更会凑热闹的人，就是查韦斯，在美欧联手要抓苏丹总统的时候声称准备和哥伦比亚开战。既然有人想把中国的势力范围里面砸钉子，那有人在美国的
后院点火也不算什么稀罕事。

在顶住美国的同时，北京也没有忘记继续修理萨克奇。应该说，这回萨克奇也是真急了，把那帮子“中国人民的老朋友”一波一波的往北京送，给自己当说客
说好话。其实，这些都没用，北京这次是铁了心了，谁的好话都不听。俗话说的好，解铃还须系铃人。只要萨克奇出面低头道歉认错，这事就算过去了。否
则，拉法兰西拉克再跑一百趟也没用！道理很简单，如果西拉克老兄真想中法合好的话，为什么不去劝说萨克奇承认错误偏偏来要求胡主席大人大量呢？难
道犯错的人比受害的人面子还大？北京这一次教训萨克奇的用意很简单：从今往后，谁也不许过北京的红线，否则，杀无赦！

【金鸿评论】萨克奇真正担心的是，自己一面冲着美国发镖，一面还冲着北京出拳，两面都是强敌，而自己是站在欧盟的第一线。稍不小心自己就会被人打
趴下了，结果让自己家里那帮认钱不认人的兄弟们给卖了，特别是英国。前些日子，英法两国的潜艇在海底撞上了，那绝不是什么误撞，几乎可以断定，那
是法国人恨透了英国人落井下石而进行的警告。那次碰撞的结果是英国的潜艇瘫了，被人拖了回去，而法国的潜艇瘸了，自己爬回去的。显然是英国吃亏要
大一点。

【金鸿评论】近日里，有一件事炒的沸沸扬扬，就是周小川叫板美联储的事。其实，这是很正常的事。美国看着暗地里骗骗不到钱了，就开始明着抢，从18
日开始明着靠印钞票来救市。这种打家劫舍的买卖居然明着干到中国头上来了，中国再不表现一下怎么行呢？

其实，所谓的超国家货币只是个幌子。真实的意思是向全世界喊话，准备拆美元的台了！因为欧元放血还不够多，所以，绝不挺欧元，中国俄罗斯打的都是
这个算盘；至于周小川提到的扩大发行SDR，只不过是抛给欧盟的一个诱饵罢了，欧盟真想把它吃下去那是要花大代价的。其实，中国和俄罗斯真正支持的国
际货币，就是自己家里的人民币和卢布。美国欧盟在这一点上也是心知肚明的，在接下来的G20峰会上给人民币让渡战略空间是必然的。美元以后的日子肯定
是不好过，但是一时半会倒不了，因为有中国扛着它呢——在周小川对美国开价之前，中国中央银行的副行长可是表过态的，“将继续购买美国债券！”至于欧
元，前景堪忧。中俄欧美四家就它有钱没军力，这一方极有可能成为三家瓜分的对象，日本就更不必说了，只不过是案板上的一块肉而已。

最后一个值得关注的，就是俄罗斯。只要它跟中国合作的好，联手出牌，肯定吃不了大亏。但如果自以为是连中国也不甩的话，被中美联手算计一把也不算
意外。


** 【金鸿评论】G20峰会追踪（3日更新）
[2009-04-01 18:27:34]



    【金鸿评论】G20峰会明天就要召开了。在这磨刀霍霍之际，大家都打出了自己的大牌。让黑帮教父奥巴马最高兴的是，小日本决定冲在第一线替自己扛
一把，看来，小日本这会又要上演一回金融战争版的神风敢死队了。 不过，这下子可苦了萨科奇和墨克尔了。这两位心里可骂吧：小日本你活够了也就算了
，干麻要搅我们的好事呢？麻生你的大嘴巴不好使，脑子也进水了吗？

   本想拣个果子却被人涮了一把的萨科奇只好转过身来对中国低头，这回的中法新闻公报也算给了北京一个交待，不过，想在伦敦跟胡主席见一面恐怕比较
困难。就算法国人可以功利一点，至少中国人用不着这么功利。除非萨科奇当面赔罪。这会萨科奇让步的，不光是西藏那边，还在对美国的南亚配合。其实
，回头抽梯子的还止一个法国？英国也不在从伊拉克撤军吗？

   伊核问题自不必说了，希拉里腆着脸说，美国一名外交官在海牙的一次国际会议中与伊朗代表进行了交流。现在美伊两国开始试探性地改善关系了，可伊
朗直接说“谁跟那孙子见面呀，根本没那事！”可怜希拉里一张漂亮的脸，又要发红了。恼怒之余，以色列又出头了，准备暗杀重要的伊朗科学家！号称是为
了阻止伊朗造原子弹。暗杀是什么行为？标准的恐怖主义行为！美国不是要反恐吗？先把以色列从地图上抹掉算了！对了，人家奥巴马上台后就不怎么喊反
恐了，难怪恐怖主义这么张狂呢。究是什么原因让奥巴马顾不上反恐的呢？也许是因为家里太乱了，有人公然在喊着美国应该解体了。真不知道那些媚美的
、一心想拿绿卡的中国人此时有何感想？

   当然，以于以色列的那点小动作与某些人比起来，可就是小流氓见大流氓了，塔利班领袖马苏德声称“很快”对华盛顿发动袭击，这可不是闹着玩的，美联
储拼命注水都盘不活美国经济，现在要是炸弹在华盛顿一炸，美国股市不跳楼才怪呢。也许，这才是G20峰会前有人对美国的最强警告。看来，明后两天，美
国不让点步是很难过这一关了。

   【金鸿评论】东北亚热闹依旧：美国海军“成功的”在太平洋上地进行了一回弹道导弹和巡航导弹的拦截试验，然后又装模作样的威胁朝鲜，“敢打导弹老
子修理你！”之后，再温柔的给朝鲜个面子，我们通过分析朝鲜火箭的整流罩设计后，相信里面装的是卫星，而不是弹头。看来朝鲜真是穷到家了，居然只有
一只火箭！不过，朝鲜有点一要筋，不大懂什么叫借坡下驴，一方面要起诉两名“非法入境”的美国记者，一方面通告美日韩，如果火箭被击落将对美日韩宣
战 ——要是真打起来了，六方回谈还能谈吗？小布什去年仅有的那点外交政绩可也要让奥巴马扔掉了，接下来美国还有什么呢？

    这几天，苏丹总统巴希尔很忙，刚刚出国访问完了事，又要跑到麦加去朝觐，你说你在家里老老实实呆着不行吗？不知道有人要抓你吗？你也太拿着村
长不当干部了吧？当然，这点面子上的小事相信奥巴马还是不会放在心上的，大人不记小人过嘛。真正让他闹心的，也许是伊朗。原本指望把伊朗拉进设在
阿富汗的谈判桌好拆上合的联盟，想不到俄罗斯借风行船。既然美国也认为伊朗是地区大国，应该让它充分发挥作用，那区区一个阿富汗又算的了什么呢？
所有的重大国际问题，其中包括伊拉克问题、中东和平进程、巴勒斯坦问题、阿富汗问题、黎巴嫩问题都应该有伊朗的份。相信哈梅内伊听到这话心里一定
乐开了花。不过，奥巴马恐怕又是一张苦瓜脸了。

    【金鸿评论】当然，俄罗斯打出这张牌也是冲着美国去的。 G20峰会上欧盟基本上可以确认啥也捞不到了，中国该到手的东西也到的差不多了，让步的
是美国，眼红的很却乖乖在一旁站着的是欧盟，就剩下一个不甘心的俄罗斯了。俄罗斯能得到什么呢？看明天伊朗会有什么动静了，如果配合到位，美国该
放血的还是得放血的。

3日更新：

     法国总统萨尔科齐表示，虽然他与中国国家主席胡锦涛会面时，宣称西藏属于中国，但不等于他不可以见达赖。

     【金鸿评论】经查，此消息在网络上见于雅虎新闻，是转的今天的《明报》。消息应该属实。

      在伦敦上窜下跳的萨科奇这一回真是把实用主义玩到家了，估计布朗之流看到这种场面只有望洋兴叹的份。就在昨天，萨科奇在胡主席面前还象个乖
孙子（在与胡主席见面时，萨科奇不仅表示法国坚持西藏是中国领土不可分割的一部分，也坚持台湾是中国领土不可分割的一部分），今天居然又想充大爷
了。当然，萨科奇完全可以继续见达赖，不但萨克奇可以见，布鲁尼也可以见；不但萨科奇可以以爱丽舍宫的大堂上见，布鲁尼也可以在自己的卧室里见。
这是他们的权利嘛，我们管不了，相信萨克奇也管不了。

     这场金融峰会真正的赢家是北京，人民币的扩张行动得到了各方的默许，中国的争霸之路布局顺利。

     勉强保本的是华盛顿，它可以继续小心翼翼的偷开印钞机剥削全世界，对于美国私开印钞机的行动，大家不要大惊小怪，别光盯着自己家里那一万多亿
的美储，别忘记了，美国国债总额在十万亿以上，我们占的只不过是个小头而已，穿鞋的都不怕我们光脚的怕什么？美国有本事就用印钞机把美元霸权给印
丢了，我们这一万亿美储也不要了，全当跟美国打了仗的军费了，如何？结果是中国人白干小半年、美国经济倒退三十年，谁更惨？国际斗争哪有不付出代
价的？

     德国一直想要的东西——加强对对冲基金的管制也终于看到影子了，不过究竟能管制到什么程度这就不好说了，因为这是奥巴马说了不算的事情。

     最大的失意者是欧盟，它满怀希望的夺权行动彻底失败了。一心想当欧盟大哥大的萨克奇自然成了最失落的人。之前寄希望于中国会对自己加以支援的
萨克奇反过来狠狠恶心一把北京、出一口闷气、过一把嘴瘾、耍一把孩子气也是可以理解的。不过，国际斗争拼的是实力，要的是理智，这回再摸老虎屁股
可不是闹着玩的。耍耍嘴是没什么大不了的，要动了真格的这回萨克奇绝对会被北京斩于马下，不信就见见达赖试试。其实，欧盟的失意在峰会召开之前就
已确定。周日时欧盟就表态，本次峰会讨论中国在IMF中增大发言权为时过早。从中国人的办事习惯来看，大事是绝对不会临时抱佛脚的。到了开会之时了再
讨价还价什么都晚了。既然中国的配合不到位，区区一个欧盟想夺权绝对是做梦，它不失意谁失意？

     在中国的领导下，第三世界国家也有所斩获，不然卢拉不会狂拍北京的马屁。现在小兄弟们都看清楚了，真正能叫板美国、黑欧盟一把给大家弄点实惠
玩艺的也只有北京了。大大方方的给北京站脚助威等北京真成了老大的那一天肯定没亏吃。

     在向IMF的注资中，北京只掏了400亿，北京一定调子，哪个第三世界国家都不会傻乎乎的多捐银子了。这么一算5000亿的份子钱还真有点难凑！北京这
是有意拿欧盟一把。（欧盟1000亿，日本1000亿，美国好象也是1000亿，加起来才3400亿，还有1600亿的缺口）

    北京是不见兔子不撒鹰——其实就是见了兔子也不撒鹰——北京开的价是先给我增加在IMF中的话语权我再掏钱，而这也只是个托词而已。因为在欧美的拉锯
中，欧盟是不可能也不敢轻易的答应北京的要求的。很自然的，北京不会多掏钱了。只是这回害苦了小日本，1000亿扛在了第一线，好歹也算为主子尽了力
了。有小日本的1000把上一扔，再加上北京带着一帮穷弟兄们要求重算话语权，也不知道到明年年底的时候欧盟在IMF中还能剩多少表决权？美元的地位是暂
时稳定住了。这回奥巴马恐怕认明了一个道理：这条好狗是打死都要拴在家里的，关键时刻真能救自己一把呀！

     这不，关键时刻朝鲜人民军总参谋部又给美国人约法三章了。其实，朝鲜是替北京向奥巴马开的价：美军后撤给北京让出战略空间，收紧狗链子别让它
出来乱叫唤，李明博要么下台要么跟美国保持距离。

     北京的要价够高，只是不是知道奥巴马有没有不给的本钱呢？连个远在天边的苏丹都玩不了还想在东亚跟北京硬碰硬，还是省省的好。

     在伦敦没捞到好外的俄罗斯回头又在利用自己的地缘优势挤压欧盟了，而在峰会上不得不稍做让步的华盛顿也重新抄起了中东乱局朝欧盟叫板，从这些
动作来看，接下来，欧盟还会吃大亏。没办法，谁都知道在强敌面前吃了亏再找个软柿子捏一把补回自己的损失来。


** 转：大规模“美元注水” 再次让世界震颤
[2009-04-13 10:10:19]


《又一轮大规模的“美元注水”，再次让世界震颤》（中国经济周刊    2009-04-07）

　　北京时间2009年3月19日凌晨，有“世界央行”之称的美联储再次传出令世界瞠目的消息，美联储当季货币政策会议决定，将在未来6个月内，收购价值
3000亿美元的美国长期国债；并在未来12个月内，收购价值7500亿美元的房利美、房地美抵押贷款证券，外加1000亿美元“两房”债券。

　　这是一种什么行为？通俗解释是美国开动印钞机大量“印钞”；专业说法是美国将在12个月内投放基础货币1.15万亿美元。

　　1.15万亿美元是什么概念？金融危机发生后，美联储奋不顾身地破例允许全美商业性金融机构用那些已经毫无流通性的垃圾资产作为抵押品，从联储获
得抵押贷款，而且一再延长这些抵押贷款的期限，这实际就是美联储投放基础货币——印钞，其新增规模高达2.3万亿美元；现在，如果再加上即将投放的
1.15万亿美元，美联储新投放的基础货币共计3.45万亿美元。

　　而在金融危机发生之前，美联储资产负债表上的负债(约为基础货币量)也就1万亿美元；但现在，美国的基础货币总投放量已经达到了4.45万亿美元。

　　从1万亿骤增至4.45万亿，历史罕见。所以，美联储3月19日“印钞”的消息一出，美股大涨、美债大涨、油价大涨、金价大涨……这一天，美国国债价格坚
挺、收益率被进一步压低。10年期美国国债收益率从前一日的3.01%下降至2.48%，创下美国自10年期国债发行以来的历史最低点。

　　一夜之间，世人对全球性通缩的担忧骤然转向了通胀，而几乎所有美元资产的持有者也都再次调动起敏感的神经，算计着自己多年积累下的财富将蒙受
怎样的损失。

　　更为残酷的是，如果美国的行为稍有失当，很有可能将把世界经济导入一场新的灾难——全球性滞胀。

　　滞胀灾难来临

　　也许有人会问，为何在金融危机发爆发前的2007年，美国的GDP达13.8万亿美元，但基础货币总量只有1万亿美元？答案是，这正反映了美国当年的信用
发达程度，使用金融杠杆上百倍地放大了货币的总量。但是，现在不行了。随着金融危机的不断深化，金融市场中的大量衍生品再也找不到交易对手了。于
是，它们变成了坏账；于是，去杠杆化变成了当今世界的潮流。

　　在此背景下，站在美国利益角度看，美联储“印钞”做法不仅无可厚非，而且方向正确。因为去杠杆化意味着金融机构创造货币的能力大幅萎缩，美联储
必须大规模投放基础货币，以维持金融市场的流动性，维系贷款市场正常运转。

　　但问题是，方向正确的事情是不是可以无度而为？更危险的是，就算美联储所投基础货币数量并未过度，但以华尔街大型金融机构为首的金融投机者势
必会利用此事大肆操纵商品期货市场(石油价格之所以在供求平衡之际也能被炒到每桶147元，不就是投机力量的杰作吗？)。可以想象，往后的一年间，美联
储每一次收购债券、放出基础货币都会为商品价格上涨提供机会，为市场操纵者提供可被利用的工具。

　　如果这件事真发生了，除了美国，世界其他各国无异将陷入一场更为严重的灾难——全球性滞胀：非美元国家不仅要承受经济衰退的痛苦，还要承受高通
胀的压力，从而为挽救经济付出难以估量的高昂代价。一方面是价格暴涨，一方面是经济萧条，灾难性的滞胀再次降临。

　　也许有人会提出反对理由：增大流动性可以推动经济恢复增长。但不要忘记，流动性推动经济增长必须具备一个重要的前提条件，即有强大的需求存在
——人们愿意更多的借钱投资或消费。但现在存在大量需求的国家已经屈指可数，中国是一个，因为中国政府有强大的财政能力，而美、欧、英、日等发达经
济体都面临着一个共同的问题：目前还找不到恢复经济增长的动力。欧美尤其如此，在GDP中占有70%地位的消费，已有相当一部分转向储蓄，如金融危机之
后，美国的国民储蓄率已经从0扩张到了5%。

　　如果找不到经济增长的动力，那美国大量投放基础货币(流动性)的直接后果只能是美元贬值，以美元计价和结算的商品价格虚涨。

　　金融投资家罗杰斯3月18日公开指出：世界范围的大量印钞，结果必然导致大宗商品价格暴涨，尤其是石油，它的价格一定会超过前高(147美元一桶)。
同时这会导致全球经济大萧条。

　　摩根·士丹利中国区主席斯蒂芬·罗奇也在3月23日指出：全球经济将在今后相当长的一段时间里处于低迷状态，而且会在滞胀中度过。

　　全球市场已露不祥征兆——当全球经济毫无复苏迹象、甚至还在滑落之时，国际大宗商品价格已经开始上涨，至少已开始剧烈振荡。

    国际金融市场大乱

　　数月以来，大宗商品价格与美元币值间在过去数十年中形成的“负相关关系”，已呈现微妙变化，国际金融市场也因此更是“乱象”丛生。

　　在此，我们仅以商品指数(1957年由美国商品研究局编制，英文缩写CRB)和美元指数(1985年由纽约棉花交易所编制，英文缩写USDX)为例。

　　2008年3月17日，美元指数创下了编制以来的历史最低位70.69点，直至当年7月3日一直徘徊在71至74点的地位；此间，商品指数一举冲上历史最高位615
点。2008年7月15日，美元指数开始强劲上涨，从72点起步至12月5日升到88点；此间，商品指数一如既往地与美元指数走势保持“负相关关系”，呈现了大跌
走势，从历史最高位的615点一路跌至322点。

　　但是，2008年12月之后情况变了，美元指数开始大起大落，12月5日至18日，期间短短8个交易日，美元指数从88点下跌至77点，并于 2009年3月9日再次
升回到89点，而后又在3月19日跌回82点。但此间的商品指数，拒绝跟随美元指数上蹿下跳，一直横卧在330点到360点之间做窄幅波动。

　　再看黄金市场。过去数十年间，黄金价格与美元币值之间的“负相关关系”更加明确——美元贬值，黄金价格则上涨。但是，近几个月情况也一改常态：无
论美元升值还是贬值，黄金价格始终于高位徘徊。就连《华尔街日报》关于黄金市场的专栏评论员也写到：“通常情况下，美元汇率上涨将打压以美元计价的
金价。但是，同时应指出的是，近来金价的变化不遵循这一规律的情况比较多。”

　　为什么会出现如此异常的变化？

　　从大的趋势看，一场空前全球性金融危机已经让世界清晰地看到，国际大宗商品以美元作为唯一计价与结算货币充满弊端，加之美国对其债权国完全不
负责任的态度和行为，必然导致世界各国努力改变国际货币体系的现状。而这样的努力，必然撼动美元原有的霸权地位。比如，国家间的货币互换以及由此
导致的国际贸易本币结算，就是对美元地位的强大挑战。

　　美元地位的弱化，反映在国际大宗商品市场上必然是一种迷茫——找不到方向感。商品价格与美元币值之间的旧有关系开始被打破。

　　从另一角度看，贸易保护主义势力的再次抬头，为了增加出口减少进口，货币竞相贬值必然成为各国政府的政策选择。世界银行3月17日发表报告指出：
自金融危机爆发以来，全球各国推出或拟推出的保护主义措施大约有78项，其中47项已付诸实施。而在付诸实施的措施中，就包括了货币的贬值。

　　各国货币的竞相贬值，以及贸易保护政策频频的出台，导致外汇市场各个货币间的比价关系(汇率)变动频繁，且幅度加大。这样的市况，使得以避险为
目的的投资者深感持有任何一种货币都不保险。怎么办？远离外汇市场，而转向商品市场避险。

　　如果这样的避险情绪主导了市场，那大宗商品价格更不会再看美元的脸色——无论美元是升是贬，大宗商品的价格都会一味上涨。而一旦这种情况发生，
那各国货币的强弱，势必将通过对大宗商品的购买力加以体现。

　　眼下，这一情况还未爆发，只是因为通过商品市场避险的做法尚未变成市场的普遍认知而已。但国际金融市场已出现的种种乱象值得跟踪关注，这将是
判断美元“注水”能否引发全球“滞胀”的一个重要关注点。

    欧元区最倒霉？

　　从通缩到滞胀的大逆转，可能迅雷不及掩耳。

　　北京时间3月19日早上的新闻称：在伦敦G20峰会的筹备会议上，欧洲和美国的财长发生冲突。美国认为：现在的当务之急是不惜一切代价救市场、救经
济、救金融；但欧洲认为：应当先改革。

　　表面上看，这样的争议不过是个孰先孰后的次序问题，但事实远非如此简单。欧洲似乎已经意识到，如果美国依靠大量为美元“注水”去挽救经济，而又
对强大的投机势力不加监管，那世界将不得不面对更加凶险的经济困境——滞胀。

　　为什么说滞胀给欧元区带来的困境更大？原因是，一旦衰落和通胀同时发生，只有货币政策手段的欧元区只有听天由命：紧缩将压制本已恶化的经济，
宽松则助推物价进一步攀升。更严重的是，如果欧元区成员国为维护本国利益而各行其是，那欧元将面临解体风险。

　　所以，欧洲希望美国立即强化监管，以抑制过度投机，就算美国不得不给美元“注水”，商品价格也不会无度上涨。对美国而言，如果先解决金融监管问
题，再实施经济救助，本国经济恢复会慢一点，美国的比较优势会弱化一点，甚至会痛苦一时，但可以换来全球经济与金融的长治久安。所以，美国应避免
因一己之私，为自己短期的快感，致他国生死于不顾，

　　显然，美国没有接受欧洲的意见，而是赶在G20伦敦峰会之前，将“生米煮成了熟饭”：除了美联储1.15万亿美元的债券收购计划之外，美国财政部3月23
日更放出“有毒金融资产”的处置计划，其中同样涉及美联储向“有毒资产”投资人提供低息抵押贷款融资的手段，而抵押品正是投资人购买的“有毒资产”。这
一决策同样意味着：基础货币投放、“印钞”、注水。

　　欧洲难受、日本难受、中国难受……美国以外的几乎所有国家都将承受实实在在的重大损失：只要你持有美元资产，你的资产就将被无情地“注水”。

　　美国把美元——这种特殊国际结算货币只当成本国货币而任意作为，毫不顾及美元持有者利益；那么世界各国是不是还要支持美元？是不是应该考虑重新
构建一种比单一美元更有效的国际结算货币？是时候了。

　　但美元绝不会自动退出历史舞台。3月24日，当中国人民银行行长周小川撰文指出“世界应当考虑采用一种‘超主权货币’取代美元国际结算货币地位”时，
美国反应强烈，总统和财长居然先后跳出来反对此提议。

　　这就是美国，它强奸了世界却拒绝一切补偿，甚至不许别人讨论防范措施。

　　美国有百利而无一弊

　　全球性滞胀一旦出现，对于美国是绝对的利大于弊，所以美国不怕滞涨。对于美元贬值引发世人对美元失去信心，美国也不怕。

　　为什么呢？自金融危机发生后，世人对美元的信心就已丧失殆尽，但又奈何？只要美元的国际大宗商品计价与结算货币的地位不变，只要美元在贸易体
系中的主导地位不变，无论对美元看不看好，都必须持有美元。

　　再有，即使滞胀对美元构成不良影响，但滞胀对所有非美元货币不良影响更大，美元相对于其他币种而言不仅不会贬值，反而升值，甚至激励世人更多
地持有美元。如金融海啸发生后，美国作为危机发源地，曾有相当一段时间，美元不仅没有贬值反而升值，原因就在于此。

　　其实，在滞胀过程中，只有美国可以在价格上涨中获利。因为，国际大宗商品的定价权在美国人手里、国际大宗商品价格通常是美国机构在操纵。所以
，国际商品市场、外汇市场的大起大落，不仅不会增加美国金融与经济的风险，反而会使美国的金融机构再次赚的盆盈钵满。

　　美国的金融机构一旦恢复了赢利能力，美国经济的一盘大棋就活了。首先，它可以为美国企业带来急需的信贷融资；其次，它将推动金融股以及其他金
融商品的价格上涨，使金融机构为交易性资产价格下跌而产生的拨备回拨，重新变成金融机构的利润，从而推动股价进一步上涨，形成良性循环；再次，股
市上涨会吸引大量资本流入美国。

　　1月份的数据表明，美国的资本流入已经无法平衡美国的贸易逆差，当月贸易逆差360亿美元，而资本净流出1489亿美元。这样的单月资本流出量已经创
下美国历史之最。国际收支平衡状况的恶化必然导致美元贬值。但是，美元贬值恰好又为美国的出口和实业经济体创造一个有利环境。

　　由此可见，在国际货币体系没有发生实质性转变之前，美元“注水”对美国是有百利而无一害，却给全世界带来灾难。这恐怕也是世界各国对“美元注水”
愤怒的关键所在。

   美元生病，中国应对症下药

　　世界主要经济体只有中国经济还在增长，因此中国不会发生滞胀。但是，全球性滞胀一定会影响中国，主要表现是：通胀高企，真实经济增长有所放缓
。

　　这一判断的依据是，其一，原材料价格的大幅上涨必定影响中国的投资热情；其二，如果上游价格上涨传导至下游，那消费势必受到不良影响；第三，
本来经济萧条就使得中国的主要出口国需求下降，现在价格又上涨了，导致需求进一步减少，从而使中国出口遭遇雪上加霜的痛苦。

　　中国怎么办？

　　重新启用行政手段应对“输入型通胀”

　　笔者认为，无论是应对当前的金融危机，还是应对未来可能出现的全球性滞胀，中国都必须充分发挥两大特有的优势：其一，中国拥有庞大的内需市场
；其二，中国拥有强有力的行政手段。这两大优势是中国有能力安度金融危机的根本保障。

　　面对价格的上涨，中国需要重新启用行政手段“保增长、管物价、补民生、扛通胀”。但无论如何不能采用紧缩的货币政策控制通胀，原因如下：

　　第一，美元“注水”引发的全球性通胀，与中国内需经济的冷热无关。换句话说，通胀是输入性的，不是中国经济过热引发的。所以，如果用人民币紧缩
政策去抑制通胀，那无异于“自杀”。相当于“别人生病，我们吃药”，不仅治不了别人的病，反而会使我们“药物中毒”。

　　第二，中国如果采用紧缩的货币政策应对通胀，不仅没用，反而会使中国内需经济变得更加困难。进一步抑制投资、抑制消费、抑制就业，后果不堪设
想。

　　没有更好的办法，中国只有“扛”过去，而“扛”过去需要不小的代价。比如，按照过去的项目安排，4万亿元投资够用了，但一旦发生原材料价格大涨，那
完成同样的项目就需要多花钱。这一点，我们必须有所准备，钱再多也得花。

　　再比如，物价上涨必然导致居民消费下降，这时中央政府恐怕还得花更多的钱，通过补贴促进消费；至于出口，长远看，需要产品升级；而近期看，政
策应当更多地转向对低端消费品出口的刺激，因为危机之时，国际高端商品市场需求将大幅萎缩，价格再低也无法刺激需求，而只有低端消费品、生活必需
品市场需求不会受到太大影响，而低价政策会取得不错的效果。

　　在财政补贴、尤其多补贴低端消费品、生活必需品出口同时，让人民币适度升值，借以缓解进口商品价格上涨的影响。

　　敢于利用“热钱”

　　一旦全球性滞胀发生，人民币资产将成为全世界最好的避险资产。

　　半年以来，美元兑港币的汇率一直被压制在1:7.75(港元升限)附近，甚至迫使香港金管局不停地投放港元以避免港币过分升值；与此同时，国际上各色
亚洲基金投资中国的资产规模也在迅速膨胀，这些迹象说明，国际游资，即热钱在不断地流入香港(用外币换取港元)。它们真是因为钟情香港才来的吗？显
然，它们的目标是：购买以港元计价的人民币资产。

　　香港如此，中国内地是不是可以避免“热钱”的冲击？历史告诉我们，不可能。国际游资无孔不入的特质，中国早已领教过，所以，靠堵的方式不仅没用
，反而会无限加大中国的监管成本。其实，对于“热钱”不必心有余悸，“热钱”是个中性的东西，用好了有利，用不好才有害。

　　从有利的角度说，“热钱”大规模流入，一来可以很自然地营造人民币宽松的环境；二来可以为中国企业提供一个大规模直接融资(发行股票和债券)的环
境，使民间投资更好地跟上政府投资的脚步，迎合积极财政政策。

　　从有害的角度看，“热钱”大量流入势必再次吹起中国的资产“泡沫”。那该怎么办？实际上，“泡沫”也是一柄“双刃剑”，用好了是好事，用不好是坏事。

　　纵观人类经济的发展历程，尤其是资本主义发展的历史，从重商主义时代的远洋贸易到网络时代的信息产业腾飞，每一次历史性的经济转折和特定产业
的高速成长都离不开巨额资本的推动，更伴随热点产业的资产泡沫。可以肯定，没有“铁路股泡沫”，就没有当年铁路网迅速扩张；没有“互联网泡沫”，也不
可能在短短数年之间形成今天这样一个庞大的互联网产业。关键问题是，泡沫过后能够留下什么？留下多少？

　　目前，中国可以利用热钱——通过产业政策，把资本引向中国经济需要的方向；通过“适度”的资产泡沫，让我们希望强化的经济领域获得足够的资本支持
。如节能环保、新能源，以及传统产业的整合改造、拥有优势产能行业的国际供应链打造等等。

　　切不可放弃这样一个历史性机遇。过去400年间，资本主义靠无度而贪婪的资本挥霍，实现了经济、军事、科技、舆论等等——他们所希望的一切霸权。如
今，中国通过30年改革开放也终于迎来一个历史性的“资本机遇”，我们是不是可以利用好这个机遇，完成富民强国的梦想？这同样在考验着中国人的智慧。

　　“热钱”再度大规模涌入中国的时间或许不会很晚。2009年3月28日，摩根大通和瑞士银行——这两家世界顶级的投资银行，几乎同时建议它们的投资客户“
重仓中国”、“高配中国”。

   用人民币升值对抗美元贬值

　　美元“注水”后，欧元区也传出消息，欧洲央行不仅会进一步减低利率，而且会通过购买企业债券放出基础货币，这种做法同样是给欧元“注水”。

　　尽管欧元区最先发出改革国际货币体系的提议，但最近的态度好像并不积极。尤其是面对中国提出用“超主权货币”取代美元在国际贸易中地位的问题上
，欧洲一副扭扭捏捏的样子，不说是也不说非，只说：为时尚早。

　　为什么会这样？暂时不改变现行的国际货币体系对欧洲是有好处的。首先，欧元在国际储备货币中排行老二，美国通过货币“注水”蚕食发展中国家外汇
储备资产的好处，欧元同样可以得到，只是好处没有美国大而已；其次，欧洲央行不愿意过度压低利率，所以必然会考虑通过投放基础货币的方式，实施宽
松的货币政策；第三，目前欧元区企业债券的利率非常高，欧洲央行收购企业债券，不仅会压低债券利率，而且会压低信贷利率，对欧洲经济恢复有好处；
第四，欧元“注水 ”会不会打压世界对欧元的信心？会，但天塌下来有美国在前面扛着，从历史看，这符合欧洲一贯的做法。

　　鉴于这样的好处，欧元“注水”顺理成章。但这样的做法会置发展中国家于水火，更加大了商品市场价格暴涨的概率。

　　那么，人民币也要注水贬值吗？答案是否定的，相反应当允许人民币兑美元、兑欧元做出适度的升值姿态。

　　理由一：在国际主要货币纷纷贬值的时候，人民币升值不仅可以凸现人民币和中国政府的国际形象，而且在未来国际货币体系重构中，占据有利地位。
理由二：国际资本争夺现在已经开始，未来会愈发激烈。如果人民币表现坚挺，那非常有利于中国吸引国际资本，并取得优势地位。理由三：人民币适度升
值与中国强化内需经济的国策相吻合；中国内需经济的发育必然呈现两大特质：资源与设备的进口需求大；国内的产业整合加速，而货币升值有利于企业整
合，把着力点集中于扩大内需。理由四：人民币适度升值有利于中国对抗可能出现的“全球性滞胀”。对于中国而言，可以减轻输入性通胀的压力。理由五：
美元贬值蚕食中国外汇储备，这是令国人无比痛恨而又无奈的事情。但人民币升值可以对抗美元的贬值，人民币可以率先与国际大宗商品价格指数挂钩，而
避开国际货币汇兑的混乱期。

　　当然，人民币适度升值，对中国可能会有一些负面的影响，如对出口不利。但必须看到，这一轮出口下滑和1997年的情况完全不同。那时，中国商品出
口受阻源于亚洲各国货币的大幅贬值。但那时发达经济体的需求还在，只要政府加大出口退税的力度，想办法让出口商品便宜一些，中国出口还是可以取得
一些优势。但现在，全球所有经济体的所有需求都在下降，商品便宜会刺激需求增加吗？恐怕不行。至少，通过人民币贬值和提高出口退税的手段，对出口
的刺激作用边际效率很低，远不及1997年。

　　选择合适且优势的贸易政策

　　“穿”，尤其是那些被冠以“低端消费品”的“穿”是人类生活的必需品。改革开放30年，中国在服装、鞋类方向已经积累了大量产能。有人认为，这样的产
能应该淘汰或转移至劳动力更为廉价国家，比如越南。这种想法是错误的。

　　我们该淘汰的只是“高污染、高能耗、破坏资源”的所谓“两高一资”的产能，而对于轻纺工业那些“劳动密集型”的低端消费品产能，不仅不能向国外转移
或淘汰，反而需要特殊的保护性措施和有效地产业强化。纵观人类经济发展的历史，一些发达国家之所以发达，他们都是在历史的某一时期，控制了某种人
类生活的必需品。比如：粮食、石油、货币等。

　　所以，中国拥有巨大的、人类生活必需品的产能，这恰恰是中国工业最大的优势，也是中国就业市场稳定的基础，更是中国工业利于不败之地的基本保
障。看看统计数据，此次金融危机过程中，不仅没有下降反而有所上升的中国出口商品就是服装、鞋类。其他一些高档商品、机电产品或生产装备——这种经
济困难时期可买可不买的出口商品，无论怎样刺激都不会有太好的结果。日本就是很好的例子，它的出口商品有许多是高端消费品，所以这场金融危机一来
，出口萎缩远比中国严重；法国也一样，艺术品出口几乎停滞了。

　　其实，对于低端消费品，关键不是利润太低，而是利润被国际大渠道商和零售商拿走了，没有留在中国人手里。所以，中国政府该做的是：借金融危机
之势，帮助中国企业向产业链的下游——国际市场的批发、零售环节拓展。比如，鼓励轻纺工业龙头企业境外开店，鼓励大型商业企业境外收购零售终端等等
。还有，用所有可能的优惠政策和各种可用的手段、哪怕是行政手段，加大产业整合力度，提高行业集中度，避免竞相杀价，兄弟相残。当然，反对贸易保
护主义，让欧美在零售业放行中国企业，更是中国政府的立场、企业的权利。

　　金融危机，是灾难也是机遇。全球新的货币体系的构建、经济秩序的调整无疑是一场大搏弈，也是发展中国家与发达国家之间一场空前的较量。发展中
国家必须在国际货币体系的角逐中获得胜券，实现责任与话语权对等、权力与义务的平衡。



** 《对话》：揭秘金融帝国
[2009-04-14 12:36:32]


《对话》2009年4月12日播出  ——揭秘金融帝国

大卫·罗斯柴尔德（洛希尔金融集团主席）
托马斯·席勒（李特尔咨询公司中国区总裁）
谭雅玲（中国国际经济关系学会常务理事）
翟山鹰（国际资本运营精英学院首席教授）
邓庆旭（新浪网财经中心总监）
李柏林（精英投资董事总经理）
吴晟（北京博然思维咨询有限公司客户总监）
邓肯·斯帕克斯（英国驻华大使馆经济及贸易政策参赞）
（人名按出场顺序）

节目导视：
    这是一个曾拥有50万亿美元财富的家族，却在中国不为人所知，这是一个曾操纵各国股市的资本大鳄，现在却以保守而著称，这是一个曾支配世界经济
的金融帝国，却无人知晓它惊天的实力。究竟什么是这个神秘的金融家族——罗斯柴尔德的真相？罗斯柴尔德家族第六代掌门人将来到《对话》现场，为您亲
身解密罗斯柴尔德。

    罗斯柴尔德，一个神秘而古老的金融家族，当250年前第一代罗斯柴尔德开始创业的时候，他只不过是法兰克福的一个普通犹太商人，仅仅用了不足100
年的时间，罗斯柴尔德家族控制了整个欧洲的金融命脉，在其鼎盛时期，势力范围遍布欧美，所控制的财富甚至占了当时世界总财富的一半，达到50万亿美
元，相当于目前美国全年GDP的四倍，世界主要经济体的国债由他们发行，每天黄金交易的开盘价由他们来确定，世界各国的股市都随着罗斯柴尔德资金的走
向而波动，他们被称为当时欧洲凌驾于英国、法国、德国、俄国和奥地利之上的第六帝国，他们五箭齐发的族徽也成为了世界金融权力的象征。

主持人（陈伟鸿）：
    我现在就是在神秘的罗斯柴尔德家族的北京办事处，我身旁的这个书架上摆放的都是和这个家族相关的一些传记作品。虽然对于大多数的中国公众来说
呢，我们对于罗斯柴尔德家族并不是非常地熟悉，但事实上他们在一百多年前就来到了中国，大家可以看到这儿，这是当年李鸿章写给罗斯柴尔德家族一封
信。
    改革开放之后呢，罗斯柴尔德家族在第一时间也就是1979年，就重新回到了中国，而和他们有业务往来的呢都是像中石化、中石油、阿里巴巴、海尔这
样的一系列的公司，但是他们自己却并不为金融界之外的人所熟知。这个神秘的家族是如何来缔造他们庞大的金融帝国的？为什么他们又会如此的低调？今
天，罗斯柴尔德家族的第六代掌门人大卫·罗斯柴尔德来到《对话》，马上我们就和他一块回到《对话》现场，共同来探究这个神秘的家族。
   
主持人：
    欢迎你和大家在我们的《对话》节目当中见面，大家都说罗斯柴尔德这个家族非常地富有，那你能告诉大家这个家族究竟有多少钱吗？

大卫·罗斯柴尔德（洛希尔金融集团主席）：
    我觉得我不告诉你这个答案，你也不会惊讶的，我们从来不对外公布，因为我们的祖先，他们是250年前创建了企业，那么当时我们家族是非常有势力的
，但是在今天，我们罗斯柴尔德家族认为如果再去成天数钱已经不是什么很有意思的、很好玩的事情了。所以我不能告诉你我到底有多少钱。我知道你为什
么对这个问题感兴趣，我想这可能跟一本在中国出版的畅销书有关，但是这本书和我们家族的真实情况还是有差距的。

主持人：
    所以我想今天把您请到我们《对话》节目的现场，我们希望您能告诉大家一个真实的罗斯柴尔德家族。来，有请。
    刚刚从办事处回来，其实给我印象最深的就是办事处的书架上关于罗斯柴尔德家族的一系列的传记作品。我知道在您的法国庄园，在您自己的书房里，
据说有好几百本和罗斯柴尔德家族有关的一些传记，那这么多书当中，大多数人会用什么样的词汇来描述这个罗斯柴尔德家族呢？

大卫·罗斯柴尔德：
    我想恐怕很难找出一个或者两个这样的形容词来形容我们家族，比如说很富有、很有钱，我们家族已经有250年的历史了，所以如果要用一个形容词来形
容，恐怕是长寿。

主持人：
    在我们看到的许多书当中，无论是正说或者是戏说，关于这个家族的描述都特别特别地多，马上呢我们来看看下面这段往事。

（播放短片）
王凯：
    一说起罗斯柴尔德大家都知道，特有钱，可是有钱到什么程度呢？在一本畅销书《货币战争》中曾经说过，罗斯柴尔德家族最多的时候曾经拥有50万亿
美元的财富。您要知道，现当今的首富比尔·盖茨财富最多的时候不过是600个亿，也就是说罗斯柴尔德家族曾经相当于800个比尔·盖茨的身家。所以直到今
天，在西方如果有人发了财，人们常会说，您看看，又是一个罗斯柴尔德，而不会说又是一个比尔·盖茨。可就是这么一个家族，今天从一些可以找得到的财
务数字上看，一点都不起眼，比如说，罗斯柴尔德银行目前一年的营业额也就是大约100亿美元吧，还不到汇丰、花旗这些银行的一个零头。怎么会有这么大
的落差呢？是罗斯柴尔德家族受到了什么重大的打击，真的衰落了？还是他们可以一直很低调，隐藏了自己的真实实力，恐怕只有罗斯柴尔德家族自己才知
道。

主持人：
    刚才听这段介绍的时候，我特别留意了一下罗斯柴尔德先生的表情，但是我实在猜不透，这个表情的背后究竟是觉得听起来很新鲜，还是听起来很自豪
，或者说是有点听腻了，之前大家都这么说我们的家族。

大卫·罗斯柴尔德：
    我们从来不把所有的东西放在一个篮子里面，我们会进行多元化的投资，我们做银行做葡萄酒，做各式各样的投资，所以很难知道总共有多少财富。不
管我们的财富是汇丰的30%，还是他们的一半，对我们这个家族来说，其实我们并不在乎到底有多少，我见到过很多很有钱的人，他们很有钱，但是他们并没
有任何的影响力，他们的财富非常庞大，但是他们并不能够影响别人。那么所以我们面对我们的祖先的时候，我们不仅仅是要传承祖先传下来的这个家业，
我们还要适应现在的这个世纪。现在与十八世纪、十九世纪、二十世纪都不同了，我们更希望能够把我们的这个实力、这个影响根据时代的发展而有所改变
。

主持人：
    所以呢，实力和影响力有的时候并不是完全靠数字，就能够彻底地、贴切地把它说明白的。为了要继续来找寻这个低调的罗斯柴尔德家族真正的实力和
影响力，我们也特别从很多公开的媒体和资料当中搜集了一些资讯，放在了我们这个罗斯柴尔德家族的档案当中。在这当中呢有几个事实，第一个我们知道
你们家族最近的一次婚礼，是您的堂兄伊芙琳的婚礼，婚礼的晚宴地点是设在白宫，当时美国的前总统克林顿也出席了这场婚宴。

大卫·罗斯柴尔德：
    因为他的妻子是希拉里的朋友，所在华盛顿举行了一个晚宴来庆祝。

主持人：
    看来呢这个消息至少是得到了确认。再来呢，第二个档案当中记录的事情是这样，在美国的社交界似乎有这种说法，就是如果在一天当中同时接到了来
自白宫的一张邀请和来自罗斯柴尔德的一份邀请，那么我更愿意选择后面的这次邀请，是不是这样的情况？

大卫·罗斯柴尔德：
    我想这取决于个人吧，不同的人有不同的选择。

主持人：
    您最近邀请到的贵宾是谁，能跟大家透露一下吗？

大卫·罗斯柴尔德：
    我可以告诉您一些例子，比如说政界的人物，像以前德国的前总理施罗德，他也是中国的老朋友了，他对我们公司来说，一直都是非常重要的一个顾问
。还有萨科齐，在他当总统之前，我们就是朋友了。

主持人：
    我看到在罗斯柴尔德家族的档案当中记录了这样的一些投资，南非的戴比尔斯公司，很多人知道这个是一家钻石公司，他们拥有全球70%的钻石的产量。
再来呢还有巴西淡水河谷、力拓、必和必拓，这三家铁矿石集团可以说是让中国的钢铁企业又爱又恨的三家企业，因为他们的铁矿石产量也是占据了全球70%
的一个市场份额，那么这几家公司的背后其实都有罗斯柴尔德家族的身影。
    在这个投资的对象当中，我看到了还有酒店业，比如说圣雅克大酒店，这是很多的国家领导人去法国的时候可能都必须想要住的一家酒店，也是你们的
投资。还有在座的各位如果喜欢葡萄酒的话，一定听说过拉菲，那这个是您的这个家族真正投资的。
    当我们看到很多的人他们是不断的通过并购、通过重组，让自己在一个行业当中越来越大的时候，你们却不断地分散到了其他的一些行业，这是出于什
么样的考虑？

大卫·罗斯柴尔德：
    我们是走上了多元化经营的道路，那么我想从某个意义上来说，我们家族是忠实于我们的家族的渊源，我们有三个传统的投资领域，他们是葡萄酒、艺
术和银行，我们还投资于铁路，甚至包括在中国和印度的铁路。此外的话，我们也非常青睐那些自然资源，比如我们会投资一些矿产，但这并不是意味着我
们就不投资新的领域了，只不过这些是我们家族一贯投资的传统领域。

主持人：
    其实不仅仅是您刚才说到的多元化，很多人还注意到了你们投资方面的一个分散化。有人说，以前的罗斯柴尔德家族可能更像是一个航空母舰，但是今
天你们通过不同的方式，让大家觉得你们有点像潜在水下的潜水艇，有的时候甚至你在投资当中都看不到罗斯柴尔德家族的身影了，是不是担心树大招风？

大卫·罗斯柴尔德：
    这样的印象不正确，我们并不是有意把自己藏起来，我们也不是刻意地神秘或者是低调的，其实我觉得你老是说你自己，没有什么意义，我觉得你能够
保持一定的神秘感的话，那么你会更长寿一些，因为那些经常被媒体曝光的人，这些人变得会非常地傲慢，而且人们要是在媒体上经常地看见你，会觉得你
很烦，而我并不想给人这样的印象。

主持人：
    所以你注意了，从进入到我们演播室的第一刻到现在，罗斯柴尔德先生已经强调了非常多次“神秘”这两个字，您的神秘感让我们觉得，更有一分好奇不
断地在推动着我们要去探究这个神秘而低调的罗斯柴尔德的家族。
    在这份档案当中我看到了还有这样的描述，就是在这次的金融危机当中，我们罗斯柴尔德家族无论是资产、无论是投资，都是没有受到任何一点的损害
。

大卫·罗斯柴尔德：
    如果因为我们一点损失都没有，而说我们高明的话，我觉得对其他的金融机构不公平，我们罗斯柴尔德避开了损失，但是并不代表我们是最聪明的，而
且因为我们保守，因为我们已经传承了六代，所以会更加地谨慎。

主持人：
    是不是因为了保守，所以我们在这次席卷了全球的金融危机当中，我们才没有受到影响？

主持人：
    你如果已经是传承了六代家族财富的话，那么你显然会比第一代的人相对来说更加保守，因为我们想更加持久。所以我觉得，我们因为谨慎保守而避开
这次风险是应该的，而且我们所提供的服务是金融服务，而不是一个资本运营，所以我们的风险很小。所以我觉得属于你来做投资，还是应该谨慎一些，起
码要有一个中长期的眼光。如果你本身就是一个谨慎的有中长期观点的人，那么你可以来投资，如果你要是一个想赚快钱的人，我就会劝你慎重。

主持人：
    刚才大家认识到了神秘的罗斯柴尔德家族的冰山一角，这也是他们在中国媒体上第一次来接受我们的访问，我想对于在座的各位来说，不知道从刚才我
们这位对话当中，对罗斯柴尔德家族有了多少的进一步的了解。

托马斯·席勒（李特尔咨询公司中国区总裁）：
    我们一直在谈论罗斯柴尔德家族，这个家族历史非常悠久，大家都知道，他与各国政府的关系非常好，他们的收入当中有一大半以上都是来自于这些各
地的政府，他们主要是对这些政府提供顾问咨询的服务，他们一直秉承的是长期经营的理念和业务模式，而不像投行那样拼命地用杠杆的方式借贷。也许投
行们追求的是一种梦想，让很多人能够在短时间之内赶快致富，但是往往它反而促成了大家的贪婪，他们是这种家族型的一个企业，而且是家族型的金融机
构，我觉得他们的态度是不一样的，他们关注的是一个企业的长久永续的经营，这应该是现在全球都推崇、学习的典范。

谭雅玲（中国国际经济关系学会常务理事）：
    通过看中国的比较著名的《货币战争》、主持人的对话，我觉得体会最深的保守，这种保守特别是在这场金融风暴当中，那么它的规避是跟它的经营理
念和经营方针紧密联系在一块的。为了企业的长久生存，那么它采取有利于自己长项的这个品种或者市场这个角度来进行自己的选择。

主持人：
    你觉得罗斯柴尔德家族在规模上它是一个什么样的程度？能跟大家介绍一下吗？

谭雅玲：
    罗斯柴尔德这个家族，它虽然在业界从规模的数量上并不是很透彻，包括刚才大卫爵士他也没有明确地回答你他的规模，那么如果跟花旗、跟雷曼这样
比较大的、有影响力的银行去比的话，那么怎么样来比较它的规模优势。透过这场金融风暴，可能我们更值得吸取或者更值得总结的是，规模的强大在于风
险规避的有效，规模的强大在于自我战略和自我了解的透彻，所以像罗斯柴尔德集团这个家族，它最重要的是量力而行，充分地自我。

大卫·罗斯柴尔德：
    我听到你们说到了花旗和雷曼，雷曼也是一个百年老店，这个问题非常简单，雷曼它的领导人也是非常聪明的银行家，但是他忽略了一点，就是当一切
市场向上的时候，一切都非常好，当利率很低的时候，当流动性过剩的时候，当市场上行的时候，当一切都是好消息的时候，大家就会被冲昏了头脑，但是
他们忘了，一段时间的好天气之后一定会有暴风雨。雷曼兄弟的资产负债表上，那些资产的质量都不高，已经明显地资不抵债了，而我们家族没有，也没有
这种胃口和兴趣，对我们这个家族来说呢，我们仍然忠实于自己的核心经营观念，就是提供金融咨询，给人们理财，所以我们不会冒这样大的风险。

主持人：
    其实要说这个家族留给我的印象，就是我们靠着250多年延续下来的一种声望和影响力。只和政府之间做一些很大的生意，你觉得这样的描述准确吗？

大卫·罗斯柴尔德：
    是的，我们确实有很多政府的业务。

主持人：
    看来这个多少有点像咱们中国的红顶商人，马上有人举手了，来，您的定义是什么？

翟山鹰（国际资本运营精英学院首席教授）
    罗斯柴尔德家族很有意思的事就是，当你们在滑铁卢打仗的时候，在中国有一个山西平遥日升昌票号，也是最早的投资银行家，商业银行家的老板叫雷
履泰。就是我感觉您为什么能走到现在，一个很重要的原因，就是因为您是为家族企业，这个世界上我们人类创造，只创造了衡量人技术能力的标准，但是
没有任何东西能衡量人的道德水平。道德不能衡量的时候，技术水平越高，可能对家族危险越大。

大卫·罗斯柴尔德：
    但是不管怎么说，就我们这个家族来说，我们有自己的原则，我们的原则就是团结、正直和勤劳，所谓的团结就是家族成员之间要团结，然后勤奋就是
说你要努力的工作，而正直就是说，你做的事情对自己要有好处，也要对别的人有好处，而不是仅仅为自己赚钱。对我们罗斯柴尔德家族来说，我们是犹太
家族，你也知道我们的当年是怎么艰难起步的。那么我们在二战期间遭受巨大的创伤，因为很多犹太人都被迫害，被关到集中营里，甚至被杀害了。我今天
为什么要把这个惨痛的经历说出来呢？因为我们的家族成员就曾经在集中营里丧生，如果你亲眼目睹或经历过那种惨剧的话，你就知道这个世界是非常脆弱
的，其实一个国家和一个民族的命运在那样的一个时代也是很脆弱的。其实我们平时走的路离悬崖也就一步之遥，但我们家族秉承的谨慎的理念和团结、正
直、勤奋的原则，能够让我们从历次的危机中化险为夷。

主持人：
    这样一个神秘的家族究竟是如何打造这个庞大的金融帝国，其实我们的答案还依然在寻找过程当中，接下来我们要请大家继续来看一看这个神秘的家族
250年来的一个金融财富之道，我们一块来看。

（播放短片）
王凯：
    1815年的6月18日，一场大战在法国滑铁卢展开了，一方是法国的皇帝拿坡仑，一方是英国的将军惠灵顿，这就是历史上著名的滑铁卢大战，与此同时，
一场没有硝烟的，以英国公债作为武器的大战也在伦敦交易所拉开了帷幕。就在当晚上八点，这个拿坡仑败局已定，于是在战场上有这么一个人骑着快马，
乘着快艇飞快地赶回了伦敦，谁啊，这就是内森·罗斯柴尔德提前安插在战场上的信使。当时的内森·罗斯柴尔德一个人孤零零地站在伦敦的港口，就等着这
个信使，当内森听到这个消息之后，二话不说，直奔交易所，他的第一个举动就是卖掉手里所有的公债。哎哟，英国输了这四个字，瞬间就充斥了整个交易
所，大家都恐慌性的抛售，恐慌到什么程度，一百英镑面值的公债瞬间就可以跌到5英镑，可就在这个时候，内森·罗斯柴尔德反而吃进了所有的公债，等英
国赢了的消息传来以后，这个价钱已经涨到天上去了，仅此一役罗斯柴尔德获利有多少？2.3亿英镑，相当于现在的500亿美元，您要知道，股神巴菲特投资
了60年，截止到2007年也就是这次金融危机之前，身家不过才是500亿美元，类似这样的案例在罗斯柴尔德家族的历史上是屡见不鲜，有人就问了，为什么总
是罗斯柴尔德家族能赶上这种一本万利的事？有人分析，这罗斯柴尔德是抓住机遇的天才，可也有人说，他们每一笔的投资都有着幕后的黑手。

主持人：
    关于机遇您又听到了两个完全不同版本的解说，其实刚才呢，我们看到的无论是拿坡仑的滑铁卢或者是罗斯柴尔德的凯旋门，至今还都是哈佛商学院经
典案例当中，每个人都必须去看、必须去学的，我想刚才那个故事对您来说也非常熟悉。

大卫·罗斯柴尔德：
    我要评价两点，其实即便到现在，没有人真正知道当时获利到底是多少，第二点我要说的就是，每一次故事大家都能够说得很精彩，都在说有人赚了多
少钱，但是没有人去关注，一旦我们当时投资失败，也会损失得一无所有。

主持人：
    从今天我们回过头来看这段历史，你会为当年自己的先辈内森，他的做法感到骄傲自豪，还是觉得他的做法也有一些你不认同的地方，如果换成是你的
话，当时你就在这个码头上等待，听到消息的是你，做决定的也是你，你会用同样的方式，还是有另外的解决方式？

大卫·罗斯柴尔德：
    是这样的，这个问题很难回答，我很难设身处地地去想，如果是我当时会怎么做，但历史的魅力也正在于此，就是它是无法去设想，也是无法去重现的
。

主持人：
    这个家族在自己的发展历史上究竟抓住过多少次的机遇，可能没有人做过专门的统计，我们的这本罗斯柴尔德家族的档案当中其实记录了一小部分，我
们把其中的几条拿出来和各位一起来分享一下。
    1802年，家族抓住了丹麦王室财政紧张的机会，获得了给王室贷款的资格，从此进入到了和各国政府做生意的殿堂。
    1798年到1813年，通过资助英国军队两万亿英镑升值到了五千万英镑。
    1898年购买苏伊士运河的股份，获得了56%的年收益。
    我想任何一个机遇都会让我们心动，但是我们常常也会问，为什么总是你们家族抓住了机遇？

大卫·罗斯柴尔德：
    你能够抓住当时的机遇是因为时势造英雄吧，我给你一个新例子，在1982年的时候，我们在法国的银行被国有化的时候，我们不得不从200年前我的前辈
詹姆斯创办的银行搬到一个非常小的办公室，当时我们就只有我跟父亲还有我们俩的秘书，一共四个人。现在我们经营了26年之后，已经是法国最成功的一
家投资银行之一，拥有了超过650名员工，现在我们是市场的领袖。

主持人：
    您说到的1981年密特朗总统让当时法国银行都国有化，所以很多的私人银行其实是退出了这样的一个市场，别人都看不到机遇，为什么你觉得这个时候
你可以再次地进入这个市场，继续来做私人银行？

大卫·罗斯柴尔德：
    其实当时法国的私人银行被国有化的时候，并不是因为经济和市场的原因，而且被国有化的银行与我接下来所要办的私人银行是截然不同的，与英国的
私人银行也是非常不一样的，所以当时的国有化反而给我们创造了这样的一个机会，让我们能够整合应法银行之间的优势。
    但是在1982年的时候，我们当时还受到一个限制，就是几年内不能够再用我们罗斯柴尔德的名字再开银行，而当时罗斯柴尔德的品牌已经传承了五代，
声誉受到大家的敬仰，但我们却不能够用罗斯柴尔德这个名字来成立银行，我们当时都觉得挺不公平的，而就是它太不公平了，反而让我们更有发展的动力
。

主持人：
    刚才这个例子能够多少让大家看到，罗斯柴尔德家族在面对机遇的时候，他们是如何思考、如何决断的。其实在这儿呢我还特别想从咱们今天的档案当
中，再找到几句历代的罗斯柴尔德所说过的一些话，不知道这些话语当中是否透露出他们掌握机遇的一些秘笈。比如说第一代罗斯柴尔德曾经说过这样的一
句话“我蹲下、跪下是为了跳得更高。”也正是这样的一句话做潜台词，我们才看到33年的努力之后，他们才争取到了第一次为王室理财的机会。
    下面的一句是第五代罗斯柴尔德传人说的“时代永远不会因为没有罗斯柴尔德而停止前进，只有罗斯柴尔德跟着时代前进。”还有一句也特别需要提出来
和大家分享，据说是罗斯柴尔德家族的一个祖训，“我们一定要和国王一起散步。”这个真的是我们祖训当中的一句吗？

大卫·罗斯柴尔德：
    应该是吧，但现在会有些不同，这些改变的地方在哪里呢？其中有一条祖训并没有正式成文的写下来，但是基本上是我们的潜台词，就是家族的女性是
不可以经商的，但是今天的话已经不是这样了，你看看我女儿，我很高兴她就是一个银行家，所以也就是说我们应该顺时而变，时代变了，那么因为我有必
要撤出法国，我同时当时也理解到被国有化的银行，它之所以被国有化，与我接下来所要办的私人银行是非常截然不同的，与英国的私人银行是非常不一样
的，所以这两条是不同的，走的是不同的路，所以当时的国有化的目的，是希望能够整合英法之间的这些机构或者私人银行。那么同时在1982年的时候，我
们当时受到限制，有几年之内不能够，再用我们的名字再开银行，所以如果说你今天是在银行业，然后你已经有了生意，当时罗斯柴尔德已经经历了五代，
声誉受到大家的敬仰，然后你还不能够用罗斯柴尔德这个名字来成立这个银行，我们当时都觉得挺不公平的。也要变，这样的话你才对于你们家族的定位、
对你自己的定位更加准确。

主持人：
    今天台下的各位从刚才我们分享的这几句罗斯柴尔德家族的非常著名的语言当中，来找寻一下他们抓住的原因和秘笈究竟是什么？

邓庆旭（新浪网财经中心总监）：
    就是我觉得总结是四个字，前两个字是“远见”，就像是第一代罗斯柴尔德家族，梅耶·罗斯柴尔德说的“我们无论是蹲下、跪着，都是为了更好的站起。”
反映了这个家族的远见。第二个“坚韧”。

主持人：
    坚韧，何以见得？

邓庆旭：
    因为历经这么多代，罗斯柴尔德家族屹立不倒，中间的波折其实我们已经有很多都见诸媒体了，其中有很重要的一点，就是有犹太人一种坚韧的特质。
比如说跟您同一代的，跟您的祖先同一代的中国有一个红顶商人叫胡雪岩。胡雪岩我觉得他的发家历程跟罗斯柴尔德家族发家的历程其实是有很大的相似的
程度的，但是现在已经看不到这个胡雪岩的这个家族的后代在商业上的一个身影了。但罗斯柴尔德家族依然活跃到现在，坚韧是很大的一个作用。

主持人：
    来，我们听听李先生您怎么判断他们抓住机遇的原因。

李柏林（精英投资董事总经理）
    刚才那几条祖训的话我们深有启发，但是我可以用另外一句，罗斯柴尔德家族的一句话来概括，就是“我们是手表的机理，但每个部分都是那么的重要。
”

主持人：
    这句话您是从哪看到的？

李柏林：
    从罗斯柴尔德网站上。

主持人：
    这是您亲自放到网站上的一句话吗？

大卫·罗斯柴尔德：
    好的，那么其实刚才他们两位的评论有一些相似之处。你说成功的秘笈到底是什么？我们这个家族所从事的领域当然需要你有很好的判断力，但前提是
你要掌握大量的信息和情报，因为如果你是自我封闭，然后闭门造车的话，那肯定是不能成功的。所以对我们这一个家族来说，我们有一个传统我们会保持
，也就是我们跟政府靠得很近，所以我们知道政府想什么，我们也知道公众在想什么，公众害怕什么，同时我们也和那些大公司很接近，所以我们对于他们
的战略都了解得很清楚，而且我们也是一个历史悠久的家族五，虽然我们也变得是比较保守，但是我们积累了很多的财富和其他的东西，几代人的努力积累
下来，那么你的判断力肯定就更加敏锐了。

李柏林：
    我想问一下罗斯柴尔德是如何设计自己企业的生态系统来把握住机遇的。

大卫·罗斯柴尔德：
    在我看来，这个世界上商业投资的机遇太多了，投资的机遇太多了，但是如果你整天都想着赚钱，或者你总是过于在意的话，你经常会犯错误，但是如
果你愿意坐下来，去想一想，平静一下的话，你会辨别出很好的投资机会，现在金融危机接近了尾声，其实已经有很多的投资机会，我觉得最聪明的投资，
就是不要过度频繁的投资，而是关键的机会去把握住，去做你真正了解的和你能够做得好的，我们应该去做一个冷静的旁观者，而不是成为一个积极的演员
。

吴晟（北京博然思维咨询有限公司客户总监）：
    我想问的是，对于罗斯柴尔德家族来说，你们成功的秘诀是什么？尤其在这次金融危机中，你们是如何保持这个秘诀的？

大卫·罗斯柴尔德：
    最重要的是，人人都希望能够掌控自己的命运，但如果你要掌控你的命运的话，你所能做的其实是有限的，我们法语有一句俗话是这么说的，就是你的
胃口再大，也不可能把所有东西都吃下去，因为吃的太多你消化不了，我认为这适用于任何的一项业务的。你的企业可以尽可能的增长，可以一年增长10%、
15%，让你的业务越做越大，越来越繁荣兴旺，但是做得太大，你可能会丧失掉你的灵魂。

主持人：
    那其实对于全球的战略而言，是不是这一刻你觉得中国的投资机会来了？对于你这次到来中国，可能有各种各样的猜测，我们来听其中的一种猜测，看
看这个猜测有没有道理。

李柏林：
    罗斯柴尔德一直在讲公司的发展重要要在信息获取，所以我是通过我的信息获取，了解到罗斯柴尔德这个家族来中国，可能是受到欧洲一些著名的企业
厂商选择买家。

大卫·罗斯柴尔德：
    如果真的告诉你我来的目的，我今天明天会干什么，你会觉得很惊讶的，所以我觉得我们中国的员工是很不容易的，他们也非常努力，我能做的就是过
来看看他们，来给他们加加油，同时和他们一起去拜访一下客户，来支持他们的工作。

主持人：
    其实人家这次来是慰问员工的，也就是说你刚才猜测的到中国来替一家欧洲著名的汽车厂商寻找买家是完全猜错了。

大卫·罗斯柴尔德：
    现在这种猜测是错的，但是明天呢，明天也许机会就出现了，对不对？所以机遇为什么这么的有美感，就是因为你不知道它什么时候会来，如果你能准
备预知的话，那这个生活就没意义了。

主持人：
    这个的确是让我们感兴趣的地方，机遇究竟什么时候会来，机遇出现的时候是不是我们可以出手的时候，看看下面的这段历史往事。

（播放短片）
王凯：
    诸位请看我手里这张图，是不是有点眼熟？这就是1911年泰坦尼克号出海时候的照片。想当年围绕着这艘永不沉没的船，曾经展开了一场激烈的商战，
当时几乎所有的保险公司都争相为泰坦尼克号提供保险，是啊，永不沉没，那就是稳赚不赔的买卖谁不想做啊。可有这么一家保险公司不凑热闹，这就是罗
斯柴尔德旗下的皇家太阳保险公司，事后就有人追问罗斯柴尔德，您怎么就会有这种先见之明呢？您怎么就能做出这种反常的决定呢？这罗斯柴尔德的会轻
描淡写，他说，我就觉得吧，这艘船太大了，它未必能浮得起来。您看，该放弃还是得放弃，不过这样的放弃，我们在罗斯柴尔德家族的历史上是屡屡见到
，这一次一次的放弃背后是进取精神的丧失还是深思熟虑的结果呢？或是罗斯柴尔德家族250年历史当中不可逾越的铁律？

主持人：
    虽然这已经是一百多年前的事了，但是我们还真的特别想问一问，当时不去为全世界都为之瞩目的泰坦尼克号保险，真的像当年您的先辈所说的，这只
船太大了，可能扶不起来，所以我们不去保险，还是说在这句话的背后实际上我们做过什么样不为人知的事情？

大卫·罗斯柴尔德：
    这个原因我也不知道，我确实没有太关注泰坦尼克号这件事情的细节，我只知道确有其事，可能故事当中具体的细节不一定非常准确，但是具体的细节
我就不知道了。

主持人：
    这个例子没有让我们找到他们取舍的标准。那我们再找两个事例，我们继续来打开这个罗斯柴尔德家族的档案，在这当中也记录了历史上罗斯柴尔德家
族在很多次别人眼中的机遇面前，你们选择了放弃。
    第一件放弃发生在2004年的4月14日，罗斯柴尔德家族宣布退出了黄金的一个定价体系，而在之前的两百多年历史当中我们知道这个家族一直是牢牢掌握
着世界黄金的定价权。

大卫·罗斯柴尔德：
    这个问题我可以回答，因为退出黄金定价权这个决定是由我做出的，首先这有历史的原因，黄金的价格在以往都是由我们在伦敦的银行来确定的，那么
所以有人说当时所有的黄金投资的活动都是我们的办公室所操纵的。但后来我们对黄金的定价权更多的只是一个象征意义，在黄金的市场上已经有很多家来
参与了价格的制定，并不仅仅是我们在伦敦的办公室说了算，当我从我的堂兄手里接手黄金的业务后发现，其实如果你要在这种黄金行业做成功的话，你必
须要做大，因为你要花很多的钱来影响市场。
    第二个原因是我认为放弃了黄金定价权也没有什么关系，因为定价权和盈亏已经没有必然的联系一当时花了很多的时间向公司德人解释，我更希望把我
们的业务集中在我们的核心业务上，而黄金交易与核心业务关系不大，我们即使放弃了也没什么关系，作为黄金定价权的把持者，曾经是我们家族的荣耀，
但现在它们已经不是我们家族的重要业务了，所以放弃了也没有关系。

主持人：
    那还有第二个放弃，我们也非常地感兴趣，就是金融衍生品让很多人赚到了很多的钱，看到别人在从事金融衍生品的时候，你们难道自己内心没有过一
种冲动吗？

大卫·罗斯柴尔德：
    金融衍生品，这个太好回答了，金融衍生品是个非常复杂的行当，那么如果你有很强的实力，有非常昂贵的IT的设备，然后有非常成熟的控制风险能力
，那么你是有可能成功的。但是即便如此，不久之前，你知道了很多投资银行在衍生业务上也都亏了很多。所以我说只有那些大的金融机构，它才做得起这
一个金融衍生品的，但是对于单独一个家族来说，你也去做金融衍生品的话就太愚蠢了。当然我知道在过去二十年，这些金融衍生品创造了大的财富，但是
很多人讲金融衍生品使很多人赚了钱，却不讲过去二十年之内也有很多人失意。

主持人：
    我们注意到您不仅仅会舍弃这些高回报但是高风险的产品，而且还会刻意的远离高速的发展，之前我和我们中国代表处的一位代表在聊天的时候，他讲
到最初上任的时候特别向总部提出了一个计划，就是在两年之内让中国区的业务量扩大四倍，但是总部好像并没有批复，为什么？

大卫·罗斯柴尔德：
    我们其实并不是完全想避免像您刚才说的这种高增长，我给你举一个例子能够说明这个问题，比如说我们在伦敦的办事处已经有两百多年的历史，在金
融危机的当中我们把它撤了，然后我们要重盖一个十四层的非常昂贵的一个办公大楼，那么你觉得这是保守或者谨慎小心吗？我觉得不是，所以保守的时候
应该保守，但你觉得事情该做的时候还是要去做。

主持人：
    我们又一次听到了您提到了这个关键词“保守”，事实上很多人希望赚快钱，但是你们没有刻意的去赚快钱，是因为钱已经赚得够多了，还是因为我们需
要保守，让自己的脚步更稳健一点？

大卫·罗斯柴尔德：
    其实没什么大道理，其实我不是那个想这么多的人，我没有一定要用道德的尺度来衡量，只要有赚钱的机会，我们肯定就要抓住这个机会。

主持人：
    从罗斯柴尔德家族两百多年的发展历史来说，究竟是哪些我们该做的、可以做的，哪些是我们不该做的、不可以做的？

大卫·罗斯柴尔德：
    这个问题很难回答，我相信每个人都有不同的看法。有些人天生就是一个顶尖的交易员、顶尖的商人，能够嗅出这些商机，但是我认为，在我们罗斯柴
尔德的第一代当中可能有一点这样从商的基因吧，但是在我们后面几代里面，我们可能并不具备这样的天赋，对于不具备天赋的人要采用一种农夫的方式，
就是要长期地去观察，然后总结出一种趋势，从而找到机会，而我们就属于这样的一种模式，我们要农夫一样去兢兢业业的去观察趋势，然后做出最好的决
定。

主持人：
    我想听听在座的各位，你们从这当中读到了什么。

李柏林：
    通过放弃来聚焦，通过聚焦来沉淀，通过沉淀来造就辉煌。

翟山鹰：
    因为我也做投资银行的，我跟罗斯柴尔德先生很有同感，就是做自己看得懂的东西，做自己能够了解事情背后，全面了解所有东西的投向，对于投向的
明确确定是你确定所有投资行为的根本。

主持人：
    刚才的这番话当中，是不是非常明显地透露出两个字，就是“保守”？

大卫·罗斯柴尔德：
    我喜欢你的评价。

主持人：
    大家都在说您保守，但是保守和创新之间是不是一对矛盾。

大卫·罗斯柴尔德：
    不是的，不是的，我告诉你一些我个人的事情，我做生意已经40年，今年我已经66岁了，我看到有些人，他总是想我要变得更富有，但是你要知道这总
是有个限度的，你是要有自己的野心，但这并不意味着你不需要保守，这二者并不矛盾，比如我就很有野心，我希望我们的家业能够一直传承，我希望我们
能够变得更加环球化，更有影响力，更专业、更发达，但是我并不是整天都在想如何变得更富有，因为一个人只能同时坐一把椅子，开一辆车，睡一张床，
所以觉得财富是需要一个积累的过程，如果你每天都在想着我要致富，我要致富，可能反而会适得其反。保守并不意味着后退，而是谨慎地向前走。

主持人：
    在很多描述罗斯柴尔德家族的书里面常常会提到这样的一句话，就是当别人悲观的时候，往往是这个家族看到希望的时候，那么今天当很多人觉得说，
金融危机对我们整个的经济有很大影响的时候，有些人信心不是很足的时候，我很想知道你们是不是在这当中看到了信心，看到了机会。

大卫·罗斯柴尔德：
    这次经济危机的深度和广度都史无前例，我们整个金融秩序受到了强烈的冲击，金融系统也重病缠身，现在的世界各地的资产的价格都在大幅下降，即
使那些质量比较好的，质量相对下降地比较少，但也有了很大的下滑。所以从投资的角度看，到危机见底的时候，投资的机遇很快就要来了。

邓肯·斯帕克斯（英国驻华大使馆经济及贸易政策参赞）：
   男爵先生，我也要问一个问题，那么现在由于有经济危机，各国政府都在疲于奔命，应该说这一次的经济危机是这几代人以来面临的最危险的一次，那么
您觉得在这次经济危机当中，中国能够做什么贡献，从而让经济快速复苏，或者是避免以后再次发生危机？

大卫·罗斯柴尔德：
    这个问题很难回答，因为我对中国不是很了解，中国现在主要的问题一个就是出口的下降，但中国又出台了一个四万亿的经济刺激方案，这是很大的一
笔钱了，这个四万亿的刺激方案就是一个目的，避免更多的人失业，尤其是要挽救一些中小型企业，不要让他们倒闭了，目前我们已经看到了初步的成效，
我觉得我们应该会对中国更乐观一些，因为中国的起步很好，而且中国本身的金融体系还是比较健康的。

主持人：
    今天我们非常感谢您来到中央电视台的演播现场，带着我们一块来走进这个神秘而庞大的金融帝国。
    之前我在办事处借了一本书，叫《世界银行家》，在这本书里有这样的一句话“如果您想完全了解这个神秘的家族，那是几乎不可能的。”经过了这么长
时间的对话，我不知道大家对于这个神秘的罗斯柴尔德家族了解能够多多少，但是我想至少在这次对话当中，让大家纵贯250年罗斯柴尔德家族发展的历史，
也让我们看到了一个真正的世界银行家身上必须具备的一些品质和特征，我们在这里还是要特别感谢您做客《对话》，也谢谢大家收看我们今天的节目，再
见。



** 美国《外交》：马克思会为金融海啸开什么药方？
[2009-05-15 21:12:12]


     五／六月号的美国《外交》（Foreign Policy）期刊发表专文说，马克思大作《资本论》近日在全球热销（德国一家书店的销量由2007年的一百本增至
去年的数千本），反映了这次危机之广泛和惨烈，及导致许多资本主义信徒出现了意识形态的迷失。

　　这篇题为《完全摩登马克思》（Thoroughly Modern Marx）的文章说，为什么人们要为马克思招魂？其中一个原因是他在150年前就准确预言了当今资本
主义全球化（capitalist globalization）的出现及其后果－－即今次金融海啸的发生；更甚的是，他还为此预留了解救的“药方”，值得我们今天作为参考
。

　　马克思在《共产党宣言》中就开宗明义指出：“资产阶级如果不使生产工具经常发生变革，从而不使生产关系－－亦即全部社会关系－－经常发生变革，
就不能生存下去。‥‥资产阶级既然榨取全世界的市场，这就使一切国家的生产和消费都成为世界性的了。”这段话简直是金融市场现况的镜映：当今资产阶级
的领跑者－－华尔街的高层－－为了创造利润而不断对金融工具进行“创新”，再把这些工具所制造的产品倾销到世界各地，埋下了孕育金融危机的种子。

　　马克思如果今天仍然在生，他会毫不犹豫地指出，证券和衍生产品等金融工具尽管有助于近数十年的高速经济增长，但同时亦直接催生了一个又一个的
经济泡沫，当中最重大和危险的就是美国的房地产泡沫。正因这个泡沫对于美国消费者需求及全球股市的持续高企至关重要，所以当它一旦最终爆破的时候
，所产生的后果会是如此的惨烈。马克思会以此作为“资本主义发展到最后，会像一个魔法师，无力再控制自己召唤出来的魔鬼”的完美例子。 

    更重要的是，马克思认为资本主义无可避免会导致社会的疏离，让人与人之间的关系只剩下赤裸裸的个人利益和金钱交易，这现象的一个后果即如各企
业今天碰到经济不景，首先想到的就是裁员和减薪，令社会涌现大批失业和无家可归者。同时，这种疏离亦会使社会中各成员不能团结一致去建立取资本主
义而代之的另一种制度。

　　因此，马克思为今天的危机开出的第一个“药方”，将会是解决这种全面的社会疏离和无力的情况。在150年前，他认为当时如雨后春笋浮现的工会和工人
政党是踏出了正确的一步。在今天，他会鼓励人们成立新的利益公同体、协会和组织，用以抵抗资本主义的现状，并开始抉择如何更好地满足自己的需求。

　　马克思开出的第二个“药方”，将会是号召金融市场的公有化，并“通过拥有国家资本和独享垄断权的国家银行，把信贷集中在国家手里”（《共产党宣言
》）。吊诡的是，这一倡议在今天也的确找到鼓吹者，但这人却是英国金融业的建制中人，同时也是伦敦经济学院教授的威廉．比特（Willem Buiter），肯
定不是一个“马克思主义者”。

　　今次金融危机所曝露的关于资本主义的荒谬性，甚至已超越了金融的领域。例如，美国总统奥巴马为解决气候问题，提出二氧化碳排放配额的拍卖机制
，让这配额可以在市场上自由交易；但这种交易制度却须依赖于现成的、充斥衍生工具的金融市场，这就让人为的操纵和波幅大起大落变成无可避免。因此
，马克思的第三道“药方”，将会是提倡打破“以资本主义市场解决一切问题”的逻辑，转而利用国家集权的机构解决诸如气候变化等问题。

　　最后，在第四道“药方”中，马克思会呼吁世界各经济体，为了应付目前的金融危机，应以团结一致的行动取代勾心斗角。但与此同时，新的变革却必需
由各国的内部做起，包括劳动阶级需先解决与其国内的资产阶级之间的关系，为达致这目的，经济、政治和法律制度也需作出相应改革。而正因各国国情有
所不同，变革的措施也必需因应其各自的实际条件。但无论在任何情况下，马克思都会强调，变革的雄心壮志是不可或缺的。

　　上述“药方”成为现实的机会有多大？就算在金融危机水深火热、世人迷失焦虑的今天，这个问题也是难以预料的。如果马克思今天仍然在生，他也不会
断言，当前的危机将何时得以解决，及将以怎样的方式解决。与执著于幼稚乌托邦情结的浪漫改革家相比，马克思从来都是一个伟大的现实主义者，他或许
仍会视当前的危机为资本主义漫长自我演化过程中，必然出现的一个阶段。

    金鸿：计划经济要回来了。



    

** 金鸿评论（09/05/25）
[2009-05-25 15:14:27]



    新华网平壤５月２５日电（记者高浩荣　姚西蒙）朝鲜中央通讯社２５日发表新闻公报说，朝鲜当天再次“成功地进行了地下核试验”。公报说，这次核
试验是“应科技人员的要求”进行的，也是“千方百计加强自卫的核遏制力的一项措施”。公报表示，朝鲜的核试验“将对保卫国家和民族自主权，保证朝鲜半岛
及周边地区和平稳定做出贡献”。

    韩国联合通讯社２５日援引外交消息灵通人士的话报道说，朝鲜当天在咸镜北道花台郡舞水端里发射了１枚射程为１３０公里的地对空短程导弹。 

    据法新社报道，美国国务院发言人表示，美国政府“尚不能够”证实朝鲜于当地时间25日进行了核试验。

    据法新社报道，俄罗斯国防部称，朝鲜25日进行的核试验爆炸威力相当于1万吨至2万吨TNT当量。朝鲜外务省发言人２４日在平壤说，俄罗斯反对联合国
制裁朝鲜。

    欧洲联盟对外关系委员瓦尔德纳２５日说，朝鲜进行新的地下核试验“非常令人担忧”。

    捷克外交部长称，由于朝鲜25日宣布进行了核试验，欧盟对此感到“非常不安”。捷克是目前的欧盟轮值主席国。

    韩国总统李明博２５日中午紧急召集相关各部长官参加的国家安全保障会议。韩国军方当天宣布提高对朝鲜侦察级别。

    【金鸿评论】俄罗斯心平气和的说，朝鲜的原子弹试验成功了。虽然朝鲜犯错误了，不过大家不能揍他，还得劝他；

     美国装模做样的说，真有这事吗？

     日本恨恨的说说，大伙削他一顿？

     韩国无奈的说，老大这态度。。。我再看看局势发展再说话吧。

     欧盟说，我得帮帮美老大，不然压不住中国了。

     中国冷冷的站在一边，一言不发，想中暗想，不是有人想玩狠的吗？我先把底牌亮出来，看谁有胆亮跟着掀牌！

     接下来，巴基斯坦那边会安稳得多了。


    【金鸿评论】近来的邓玉娇案闹得沸沸扬扬，上层一直没有人表态。许多人由此很失望，认为北京“不怎么为老百姓办事”。其实不然。

     不知道大家注意过没有，有许多案件，比如虎照案，林嘉祥案等等，这些案件都炒得全国皆知，但最高层基本没表什么态，这是为什么呢？

     因为中国是社会主义国家，是人民的国家。与敌对势力斗争不是“当官的”人的责任，而是全国人民的责任。每一个人都有责任起来与之斗争。这也是共
产党的传统。

    共产党建党伊始就是这样：依靠工人农民与各方敌对势力斗，抗日战争时是这样，解放战争时是这样，抗美援朝是这样，西南剿匪是这样，文革清右也
是这样，而且是最高潮的表现。

    现在，中国很乱，每一个人都有责任在自己力所能及的范围内做点事。与邪恶势力作斗争不仅仅是胡温的事，他们虽然是一国领袖，但他们也只是人民
中的一员，我们怎么能把所有的责任都加在他们身上呢？

    所有骂娘的人都应该闭上嘴巴了。用你的行动为这个社会做点事吧。现在，我们这个国家需要每一个有良知的人站出来做事。只要你是人民中的一员。

******************************************************************

《村长候选人关于自己兄弟在村东头乱放爆竹的谴责声明》

    全村老少爷们，昨日个咱村出事了。闹事的是我家兄弟二愣子，他公然违反村规，在村东头乱放爆竹，差一点引起火灾。对于二愣子的这种恶劣行为，
兄弟我坚决反对，非常反对，强烈反对。

    不过，听说有人因为这件事想揍他，我觉得，这种心情是可以理解的，但是，这种行为是绝对不允许的。谁要是揍我兄弟，就是打我的脸，对此，兄弟
我坚决反对，非常反对，强烈反对，绝对反对。

    为了防止火灾，保一村平安，全村禁止放爆竹兄弟我的坚决不移的一贯立场。兄弟我强烈要求二愣子信守不放爆竹的承诺，停止引进村东头火灾的行为
。不过，兄弟我不准备没收他的爆竹和火柴，因为我觉得这个东西对一个成年人来说，是可以有的。当然，二愣子的邻居鬼混子从道理上讲，也是应该有的
，不过，他家大哥煤老板不让，所以，鬼混子真没有。对此，大家也都表示理解。

    保证村东头的稳定平安，符合全民老少爷们的共同利益。在此，兄弟我希望大伙在二愣子放爆竹的问题上保持冷静，想骂的可以骂两句，不过不要当面
骂，在自己屋里随便骂，隔着墙吼两嗓子也成。不过，只许动嘴，不许动手，不然，兄弟我是无法做视不理的，因为当年堂上二老交待过，一定要照看好这
个小兄弟，不能让他吃了亏。兄弟我只有照办。当然，我会在村东头禁放爆竹问题上继续努力，努力，再努力，至少嘴上如此。                         
               候选村长   老钟叔于即日

************************************************************

    新华网北京５月２５日电　据朝中社报道，朝鲜宣布于５月２５日进行第二次核试验。中华人民共和国外交部就此发表声明，全文如下：

    ２００９年５月２５日，朝鲜民主主义人民共和国无视国际社会普遍反对，再次进行核试验，中国政府对此表示坚决反对。实现半岛无核化，反对核扩
散，维护东北亚和平与稳定，是中国政府坚定不移的一贯立场。中方强烈要求朝方信守无核化承诺，停止可能导致局势进一步恶化的相关行动，重新回到六
方会谈的轨道上来。维护东北亚地区的和平稳定，符合有关各方共同利益。中国政府呼吁有关各方冷静妥善应对，坚持通过协商和对话和平解决问题。中方
将为此继续作出不懈努力。


    朝鲜军方２７日发表声明，宣布朝鲜将不再受军事停战协定约束，并不能保证美韩舰艇和普通船只在其西部海域的航行安全。

    美国国务卿希拉里２７日重申，当同盟国韩国和日本遭到朝鲜威胁时，美国将向韩日两国提供保护。

    【金鸿评论】美国将提供什么保护呢？收拢难民吗？希拉里只敢说保持韩日却不敢说修理朝鲜，就说明美国真成了无牙老虎了。

    这次朝鲜横得可以。让全世界都看看，昔日看谁不顺眼就揍谁的世界老大今天沦落到了被人砸了场子也只能装糊涂的地步。既然往日的黑社会老大任人
欺凌了，那么谁是新的霸主呢？这个问题的答案是非常简单的。中国是不称霸的，但是，中国的小兄弟是无人敢惹的。以后，地球村的村民们就可以清楚的
知道，跟着谁混是可以横着走的了。

     朝鲜真的有原子弹吗？也许朝鲜只是面子上好看一点。也许原子弹的控制者另有其人。



** 【金鸿评论】炒股与定价权

   [2009-09-13 23:12:03]

   
    以前说过要写一篇文章《财富流向的指挥棒——定价权》，后来没有发。其实当时都构思好了，考虑到举的例子是施政中正在采用的许多政策，比较敏感
，就作罢了。现在研究股票，又联系到了定价权，索性以炒股为例写一下，也算没有失言。天下之事，一致而百虑，殊途而同归。当大家明白了庄家怎样操
纵股价赚钱的时候，也就明白了中国如何通过在伊核朝核问题上坐庄为自己捞取利益了。

    股市是最体现市场经济制度的地方。因为市场经济是通过价格发现引导社会资金流动进而完成资源配置的，价格发现是其核心。众多的西方精英攻击计
划经济攻击的重点也是计划经济对许多产品的价格扭曲。乍一想，精英们说的是有道理的，为什么有些东西明明值十块非逼它卖三块？不合理嘛。其实不是
这样的。随便举一个例子：近期各地水价上涨。从价格发现的角度讲是完全合理的——“我就卖的贵，有本事你不喝，我赔钱！”老百姓能不喝吗？结果是本来
就过的很紧巴的日子更难过了。水厂的老板自己是肥了，广大的“弱势群体”更弱势了。现在我们再来看，把水价扭曲一下好不好呢？其实，这是两个不同角
度看问题做事的结果：一个是首先考虑个体利益最大化，一个是首先考虑整体利益最大化。哪个更好呢？见仁见智好了。

    在价格发现方面做的最到位的地方，就是股市。价格的变化会在每一秒钟出现在价格显示屏上。但是，这里只有冷冰冰的数字，没有任何感情。股市就
是个合法抢钱的地方，这里没有道义，充满了欺诈——这就是市场经济的本质——表面上合情合理按规矩办事，实际上全是见不得人的东西。

    我的话偏激吗？且不说为了引导股价变化而满天飞的小道消息和谣言、股评，仅仅那些骗线，就足以让涉市未深没有多少水平的股民们吐血了。这两种
方式都是骗，只不过一种是明着骗，一种是暗着骗罢了。当然，后者略显得文明一点。

    进入股市，大家都是为了赚钱。可是，如何才能赚到钱呢？四个字，低吸高抛。说起来很容易，不过做起来很难很难。对于散户们来说，想赚钱，唯一
的办法就是跟庄。当然，有人可能说价值投资。我承认，价值投资有道理，不过，价值投资的成果如何实现呢？也是靠庄家把股价拉起来嘛。所以，说到家
还是靠跟庄。

    庄家怎么赚钱呢？自然也是低吸高抛。一般说来，庄家要想控盘，至少需要拿到流通盘的40%。如果少了就控制不住价格，另外手里还要有足够的预备资
金。唯有如此，方能在别人大量抛盘时接得住以稳定股价，并能在有人大笔买单时能卖得出足够股票以防止价格大起大落。也就是说，唯有如此，才掌握了
这支股票的定价权。

    有了定价权就可以任何控制股价吗？可以，前提是手里有足够的资金。打个比方：某支股票有1亿的流通股，最开始股价是1元，这时一个盘子只要1个亿
，如果庄家控一半，占5000万，再准备5000万就足够了（大不了必要时把散户手里的5000万股全吃进来）。如果股价涨到了2元，这时盘子就是2个亿了。如
果涨到10一股呢，就是10个亿。如果庄家在1元时吃了5000万股，那涨到10元时，他得最多再准备5个亿的资金，才能保证稳的住股价——保证能以10元一股的
价格吃得下剩下的5000万股。如果涨到100元一股呢，那就可能再需要几十个亿的资金了。从这里可以看出，定价权是靠大笔资金做后盾的。其实，股价的涨
跌跟油价是一个道理，只要有足够的资金，想让石油多少钱一桶就多少钱一桶。别说200美元，2000美元都没问题，只要庄家们的资金充足。推而广之，去年
世界粮价的波动也可以以此说明。

    还有一个有意思的问题，大家可以自己想：温总理是如何拉抬粮价给农民增收以调整八亿农民收入的？（社会财富流向的指挥棒）

    上面说的是股票定价的基本原理。其实，在实战中，庄家获利是要经过四个步骤的：吸筹，震仓，拉升，出货。吸筹就是悄悄的建仓，到了一定程度，
没人卖了，这时庄家就开始震仓，把股价拉起来再猛得砸下去，这时，不明就里的散户一害怕就卖了，庄家就又吃到了筹码。等庄家把筹码吃饱了，就开始
拉升股价，拉高到一定程度，再把股票卖给跟风的散户。庄家获利出局，散户高位套牢。这就是庄家操盘的基本手法。当然，实际操作中要复杂的多，特别
是震仓。现在是越震越狠，配合着对敲，一个猛回头砸下，不光获利盘被吓出，大量的跟风盘都亏着出局（关于这一点可以看一下浪莎股份600137，这个妖
庄八月初和九月初各玩了一次这一手）。

    炒股要想赚钱，做为散户，只能跟庄。怎么跟呢？吸筹阶段不进，低位震仓时不进，高位震仓时高抛低吸，拉升时跟着抬轿子。所以，炒股不仅仅要选
好股票，更要选好介入的时间。

    举个例子吧：比如几个小时前分析的几支生物股：应该说，科华生物洗盘洗的最干净，周一最有可能上涨，但是，它可能是那几支股里面上档压力最大
的一支，周五还没涨到8%就被压了回来，虽说压回来的力量不大，可庄家借力周一回调一把的可能性有没有呢？谁也不敢说没有。上面的19-22元这个价格区
是个非常关键的阻力线。再说下周的大盘走势会如何？万一一个大跌，庄家逆势强攻的可能性有多少呢？所以，要根据股票的走势去判断。

    最后还有一点需要说明：对庄家而言，炒股就是打仗，有计划更要适应变化。比如，原来计划今天的股价先跌后涨，最后涨到什么价位，结果在上涨过
程中遇到了很强的阻力，这时，庄家的计划极有可能改变。

    要想在股市里赚钱，只有抱着斗争的思想去操作。


    

** 【金鸿评论】也谈钓鱼岛扣人事件
   [2010-09-17 21:44:21]

   
看国际问题，要看大背景，不要只看这一件事。否则，即使是赢了，在许多人眼里也是在输。

应该说，在现在的大环境下，小日本在钓鱼岛扣人，是自己找不自在。不过他还以为自己很高明，抓住了机会。

事情的起因是这样的：

美国为了集中力量摆平阿富汗塔利班和拿到一份制裁伊朗的决议案（韩日两国都刚刚通过了制裁伊朗的方案），不惜在格鲁吉亚方向上对俄罗斯让步；

不惜在巴以和谈方向上和科索沃方向上对欧盟让步，要求欧盟增兵阿富汗；

为了拖住中国，美国再次抛出台湾问题（陈水扁曾下令研发核武），并在南海引着东盟小国跟中国争领土，

在做好了这三方面准备的同时，加大了对巴基斯坦通道的施压，搞乱克什米尔地区，切断中国西进的通道，希望以此压服伊朗，或者至少拿到一份有用的制
裁方案出来。

这时，是中美对决的关键时刻，谁都不好分神再对付第二家。

可就在这时，日本跳了出来，抓了中国渔民。

日本最初的意思，应该是在跟美国人讲价钱：你把台湾问题抛出来，是不是希望闹大了我去跟中国打仗？那好，我的钓鱼岛你管不管？如果你管，台湾有事
我就管，如果不管，我也不管。

日本的坐地起价被希拉里用演说中把日本排在韩国后面的方式直接驳回，没讨着好处的小日本，反手拿竹岛主权问题与韩国纠缠上了。

其实，这是日本人在向美国示威：你说到底我大还是韩国大？

按理说，这时日本应该放人了，可他还不死心，还是不放，这时北京真恼了。一开始，北京对日本扣人事件的态度是很温和的，虽然说是要求马上放人，可
口气一点也不严厉。马上放出了“恣意妄为则自食苦果”的狠话，并掐断了东海谈判。接着，日本就放了14个人。不过没有放船长。

这时，日本再扣着船长就是跟中国过不去了，这跟拿着竹岛折腾韩国让美国人恼火是一样的。

其实，这事情再闹下去，他什么都得不到了，各方的态度他都看到了，而且是两面挨耳光子。可这头猪就是不开窍。

胡温只好用不见日本经济代表团的方式警告日本，不要闹腾了，再闹你可要吃大亏了。可这头猪居然厚着脸皮说撞船事件不会立即影响中日贸易。

的确是，现在中美对决，没人能腾出手来收拾你。可等两边达成了妥协，就会一起来收拾你！那时你就等着喊爹求饶吧！到那时，两个爹一起下手，看你叫
哪一个亲爹才好！

给船长判了10天的刑，小日本最多玩9天，否则，必遭重手！

再把中美对决的事说完：

巴铁通道是掐不断的，印度已经开始严管自己人了。只要印度不闹，巴铁是识大体的。

欧盟如果不能增兵阿富汗，美国肯定第一个拆地中海计划的台，这一点已经通过以色列战机入侵黎巴嫩领空的方式警告过了。

另外，在这关键时刻，卡扎菲提出要建非洲联合政府，这摆明是拆地中海计划的台。卡扎菲是替谁在警告欧盟呢？八成是中国。因为美国和俄罗斯与利比亚
的关系都才不够硬。

写这段文字时，我没把新闻录进来，所以，不是很严谨，有感兴趣的，可以自己查相关新闻。按时间顺序。


** 【金鸿评论】再谈钓鱼岛扣人事件（全程跟踪完毕）
   [2010-09-20 08:49:01]

   
据法新社9月19日消息，日本当局今日宣布延缓放回被非法抓扣的中国渔船船长，将非法抓扣期限再延长10天，并称此举是因为“中国渔船撞击日本渔船”所致
。

     韩国济州海洋警察厅19日表示，对于在韩国专属经济海域（EEZ）进行捕捞活动的中国籍拖捞船辽章渔25068号（41吨级）渔船，进行了拘捕。

     19日晚，外交部副部长王光亚就日方19日下午决定继续非法扣押中方船长事，向日本驻华大使丹羽宇一郎表示强烈愤慨和抗议。王光亚指出，日方如不
立即无条件放回中方船长，中方将采取强烈反制措施，其一切后果由日方承担。王光亚强调，日方制造的这起事件已经对中日关系造成了严重损害，今后事
态如何发展，完全取决于日方做何选择。

    【金鸿评论】打得一拳开，免得百拳来。现在只不过是一个韩国在跟，下一步东南亚国家再跟着起哄，那就麻烦大了。

     今天小日本鬼子要是再不放人，必须给他一个教训。找个合适的地方，打沉他两艘船！   

    保证主权和领土完整，是任何一个有尊严的国家必须坚守的红线。对敢于越过红线的敌人，必须给予正面的、强力的回击！在这个问题上，没有任何回
避的理由。

————————————————————————————————————————

中国的两艘军舰今日启程前往东海执行巡逻任务。未经完全证实的消息说，东海舰队的两艘驱逐舰根据高层的命令，今日已经前往东海，有可能到中国开发
的春晓油气田（日本名“白桦”）附近海域执行巡逻任务。 
   在17日深夜，前原就任外务大臣的记者会见中，曾经明确表示，如果一旦证实中国将勘探白桦油气田的话，日本将会采取断然的措施。
    中国外交部已经承认，中国在日本海上保安厅逮捕中国人船长之后，开始向春晓油气田搬运设备。并表示这是中国在行驶自己的主权。外交部没有说明
是些什么机械设备，但是，日本媒体报道说，这些设备主要是一些勘探设备。

新华网杭州9月20日电(记者章苒、屈凌燕)垄断4S店汽车消费贷款业务、收取高额利息并向4S店支付返利——丰田汽车金融(中国)有限公司20日因商业贿赂收到
杭州市工商局江干分局的行政处罚听证告知书。

【金鸿评论】北京果然打算玩狠的了。日本不是不允许中国单方面开采春晓油气田吗？还说若要开采则采取断然措施。那好，我给你个断然的机会，你敢派
军舰过来吗？如果敢来，那就打沉他两艘！让他知道知道在太岁头上动土的厉害！如果不敢来，那好，马上给我乖乖的放人。

北京这会干的真叫漂亮！这一次坚决把小日本整服气！不打任何折扣的！

刚刚扣人那会儿，那个厚脸皮的日本产经相说这事不会影响到中日贸易，现在，北京也从贸易层面上给日本敲警钟了。何去何从，你自己看着办！（20日更
新）

————————————————————————————————————————

    日本政府消息人士昨天（20日）强调，中方有意把撞船事件扩大成为领土争议事件，日方不会为“挑衅”所动，将不采取对抗措施。
     【金鸿评论】说明一下，我为什么前天说扣人事件的性质变了。因为在19日的时候，日本的外务大臣前原诚司说了下面一番话：

    “尖阁诸岛是日本固有的领土，不存在所谓的领土问题。这里是一个优良渔场，中国大陆和台湾的渔船也前来这里，但领海内的渔业活动是受到禁止的。
当时，中方渔船不听从劝告，撞到巡逻船上，我们以妨碍公务的嫌疑逮捕了该船船长，并将根据日本的法律对此进行严正处理。”

    如果没有扣人事件，日本说钓鱼岛是他的，中日没有领土争端，那我们可以认为这是在打口水仗，嘴上还击一下就可以了；如果他扣人了，也承认中日
有领土争端，那我们同样没有必要把这一事件升级；可现在是，他既扣人了，又说领土是他的，还按他的国内法处理我们的人，这是绝对不能允许的。如果
这时我们让步了，那就是等于承认钓鱼岛是日本领土了。

    建国以来，中国还没有哪一届领导人敢出卖国家领土。所以，对于日本的挑衅行动，唯有全力还击，而没有任何妥协退让的余地。

    在中国强硬的派出了两艘驱逐舰以进一步紧张局势之后，小日本倒软了，自己打自己嘴巴，反说是“中方有意把撞船事件扩大成为领土争议事件，日方不
会为“挑衅”所动，将不采取对抗措施。 ”

    坦白说，日本人的表态，我看后真是哭笑不得。小日本的确滑的可以，也滑的可怜！既然你没胆量升级，那就乖乖放人吧？不要再丢人现眼了，好不好
？你不要面子，我们还要呢！

————————————————————————————————————————————

　　中新网纽约9月21日电 (记者张朔孙宇挺魏希)中国总理温家宝当地时间21日晚在纽约会见旅美华侨华人、中资机构及留学生代表时说，钓鱼岛是中国的
神圣领土。日方最近在钓鱼岛海域抓扣中国渔民和渔船，至今不释放中方船长，这是完全非法的、无理的，已经对中方船长及其家人造成严重伤害，并激起
海内外全体中国人的愤怒。
　　温家宝说，中方多次严正交涉，日方置若罔闻，中国政府不得不采取必要的反制措施。在此，我强烈敦促日方立即无条件放人。如果日方一意孤行，中
方将进一步采取行动，由此产生的一切严重后果，日方要承担全部责任。
　　温家宝指出，经过多年艰苦努力，中日关系得到改善和发展，这一良好势头遭到严重破坏，完全是日方一手造成的。日本政府应该迅速改变错误做法，
使中日关系回到正确轨道上来，这有利于两国人民的根本利益，也符合和平、合作世界潮流。

【金鸿评论】放人的时候到了。不给中国总理面子的后果绝对是小日本承受不起的。

————————————————————————————————————————

    【金鸿评论】北京的最新动作：

    全面禁止对日出口稀土，

    限制赴日旅游 ，

    抓了4个擅闯河北军事管理区的日本人；

    日本的反击：

    邀请达赖喇嘛在亚太经合领导人非正式会议前一天去广岛；

    前原再次调强：“尖阁列岛自古以来就是日本的固有领土，不存在中国方面主张的领土问题，将按日本的国内法处理中国船长。

    相对于北京全面开花的立体打击，日本的还击基本没什么力度。在亚太经济领导人非正式会议前一天把达赖请到日本去，不是在恶心北京，而是在给华
盛顿找麻烦。试想，在这种美国最希望能团结中国的时候偏偏让中国的领导人不开心，会能开出好结果来？

    至于前原再次把扣人事件上升为领土争端问题，再踩北京红线。无非是摆出一副死猪不怕开水烫的架式：

    你打他，他抱头不还手；

    你骂他，他就稍稍顶两句嘴；

    你跟他说人话，他听不进去；

    真是老鳖咬手，死不松口。除非把他脑袋剁下来。
    再想想此次事件发生的原因，应该是日本被逼急了。
    中国要搞东北亚一体化，说白了就是要美国把日本韩国这两块地盘让出来给中国；

    早几年美国顶的住，坚决不干，次贷危机之后撑不住了，为了自救只好拼命的从日本那边抽血；

    小日本想往中国这边靠靠吧，华盛顿就整他。看看日本自小泉以来换的这些首相吧：

    安倍、福田、麻生、鸠山，这些走反美亲华路线的首相最多只能干一年，偏偏反华的小泉能干五年，还不能说明问题吗？

    现在菅直人上台了，能不心里打鼓？这时我们就再次看到了极为反常的一幕：

    上台以前的亲华派上台后却开始反华，这跟上台前极其反华的安倍上台后却坚决抗美的一幕如出一辙。

    当年安倍上台后坚决不访美，不管小布什怎么砸他，逼得困境中的小布什让步让日本举办了一场巴以和会，安倍这才乖乖的访美了。
    今天的中国也有类似的情况，中国是不适宜与日本全面摊牌开战的，菅直人也是抓住了这一点，死死咬住一个中国船长不放，问中国要好处。中国狠砸
他他就低头任砸，但就是不松口。也想从中国手里捞到类似安倍那样的意外惊喜。
    但是中国不是美国，中国是有原则的，不可能为了哄他高兴就放弃自己的原则。

    现在情况的确有点麻烦。不过从今天日本请达赖一事来看，日本好象是希望北京能压一下美国，以减轻自己的压力。

    毕竟，日元这几年升值升的太多了，从07年6月的1:124升到今天的1:84,这个价格已经创了15年来的新高,仅次于95年4月的1：79.7历史最高价。日本经
济都快被美国折腾死了，他是真要撑不住了。

    这应该是这一次菅直人抱头任揍却又死不松口的真正原因吧。

    接下来北京将如何应对呢，本博将密切关注。

————————————————————————————————————————————

    美国时间23日夜，美国国务卿希拉里在与日本外务大臣前原诚司举行首次会谈时表示，美国政府的理解是，尖阁列岛（中国名“钓鱼岛”）属于日美安保
范围之内。这是自本月7日，日本海上保安厅逮捕中国人船长事件发生以来，美国政府负责外交的高官第一次正式就尖阁列岛问题直接表态。但是，美国国务
卿发言人随后表示，对于尖阁列岛的主权问题，到底属于哪一个国家？美国政府不会就此表态。希拉里国务卿在与日本外相的会谈中，要求日中两国共同协
商，一起来解决这一问题。

    据日本共同社今日报道，日本冲绳县那霸地方检察厅当天宣布放还非法抓扣的中国渔船船长。

    【金鸿评论】坦白说，我昨天还以为小日本真扛揍呢。没想到才过了一天就撑不住了。

    不过这里出现了一件非常有意思的事，放人的事发生在美国刚刚同意把钓鱼岛纳入到日美安保范围之后，这可太不给美国人面子了。

    当然，如果对比前一天发生的那一件事，就可以得出结论了：昨天小日本刚刚打了一张平日里美国人最喜欢看的达赖牌。

    我在昨天的分析中曾说过，把会见达赖放在亚太经合组织领导人非正式会议前一天，纯粹是在给美国人添乱。

    结果，只过了一天，希拉里就开始刺激小日本了。表面上看，希拉里好象是在支持小日本，其实不然。首先要明白的是，以前每当中日之间为了钓鱼岛
发生冲突的时候，美国人的态度总是一句话：对于钓鱼岛，我们的态度就是没有态度。这一点就足以说明，美国人不可能为了钓鱼岛去跟中国人开战。那如
果解释希拉里同意把钓鱼岛纳入日美安保范围呢？

    其实道理和日本人要见达赖一样，这是美国人反过来折腾日本人：虽然希拉里同意把钓鱼岛划入日美安保范围之内，但希拉里的发言人随后专门表态：
希拉里并没有说钓鱼岛是日本的，这是中日两国需要自己解决的事。

    这是在暗示日本人：你不是借着见达赖拆我的台吗？那好，我也给你搭个台子（把钓鱼岛划入日美安保范围之内），你敢上去唱戏（与中国发生军事磨
擦）吗？如果菅直人真敢，那到时希拉里就会说，这是你们两家的事，我事先说过的，你们自己商量着办吧。我在中东挺忙的，阿巴斯他们正等着我呢。到
那时，小日本可就真傻了。

    本来，菅直人想做一张牌出来，希望能换回点东西来，结果，没等北京接招，华盛顿就出手化解了。权衡之下，再不放人北京的打击会越来越狠。还是
放了的好。

    另外，前几天有两个细节，不知道大家注意过没有：第一是杭州查丰田的时候质检总局解禁了日本奶粉的出口，第二是禁止对日出口稀土的消息传出后
商务部立即做了否认。

    很显然，北京是在向菅直人展示自己强硬的一面的同时，也告诉他，中国还是给他留了后路的，如果再不抓，可就真没机会了。菅直人权衡再三，选择
了放人。

    最后留一个问题：为什么安排“杭州”来查“丰田”？看看各位看我文章的朋友们，功底如何，呵呵。


    

** 【金鸿评论】为什么安排杭州查丰田？
   [2010-09-25 19:00:22]

   
   我想，来看我文章的人都是关注时局的人。所以出这个小题目，让大家也学着自己做分析。其实，07年以前，我也是看别人写东西的。慢慢的自己开始写
，写的多了水平也就提高了。

   分析一条新闻，首先要看它的背景形势，其次是与他有关联的新闻，单纯的拿着一条新闻做分析，弄出个一二三四五其实是没有价值的。

   日本虽然放人了，但事情没有完，北京又提要求了，道歉，赔偿。要明白，中国极少要求赔偿的，只要伸手要钱了，是不会空着手回来的。不过后续的局
势都是小波澜了，就不追踪了。

   安排杭州查丰田的前一天，日本外务大臣前原曾说过：
    “尖阁诸岛是日本固有的领土，不存在所谓的领土问题。这里是一个优良渔场，中国大陆和台湾的渔船也前来这里，但领海内的渔业活动是受到禁止的。
当时，中方渔船不听从劝告，撞到巡逻船上，我们以妨碍公务的嫌疑逮捕了该船船长，并将根据日本的法律对此进行严正处理。”
   在此言论之前，扣人事件是小事情，不值一提。但前原这番话一出口，扣人事件马上上升为眼前必须解决的领土争端问题。所以北京放出了胜负手，一是
安排抗州查丰田，二是军舰巡航春晓。

    17日，前原曾经明确表示过，如果一旦证实中国将勘探白桦油气田的话，日本将会采取断然的措施。

    既然日本认定中国勘探春晓也是眼前必须解决的领土争端问题的话，那就派军舰来吧。如果不敢，还是收了摊子的好。
    现在的问题是：查丰田与巡航春晓有关系吗？

    有，有直接关系。

    首先，这两手是一文（经济打击）一武（军事解决）。

    其次，看看地图就知道，春晓和浙江隔海相望，一旦动起手来，补给肯定要靠浙江，而杭州是浙江的首会。北京用行动告诉日本，我已做好了充分准备
，从后勤到前线，你准备好了吗？

    至于为什么打击的是丰田，也很简单，给日本人提个醒。前些日子奥巴马差点没把丰田整死，当时如果中国也跟着下手的话，丰田可能就真破产了。要
知道，过去几年美国人打击日本经济可是不遗余力的，把日元汇率从125推高到了84块，日本经济大受打击，最后奥巴马还嫌不过瘾，直接砸丰田，给通用克
莱斯勒腾市场。 现在中国查丰田就是警告日本，中国也有能力对日本经济进行致命打击，不信可以试试，只要中国动起来了，美国肯定跟上。

    这一文一武的两招，是地地道道的摊牌行动，最后通谍式的。所以日本马上表态，不对抗！

    另外，在这里来看我文章的朋友们约法三章：凡是反毛反胡的、反社会主义的、胡乱骂人的回贴，一律删除！



    

** 【金鸿评论】简评黄陈之争
   [2010-09-28 13:06:27]


   
    持续两个月之久的国美控制权大战将迎来决战日。明天下午2点半，国美特别股东大会将在香港铜锣湾怡和街88号富豪酒店地库一楼富豪宴会厅召开。
    【金鸿评论】陈晓是个标准的SB。从判黄光裕放杜鹃的那一刻起，就决定了黄光裕必须得赢，这是北京的态度。这场控制权之争，陈晓输了还好，要是
赢了，就等着进监狱吧，哪个先富起来的屁股底下没有一堆滥事？

 ——————————————————————————————————

    没留神，把今天的决战看成了昨天。现在结果出来了，这个结果有调和矛盾的味道，事先达成妥协的可能性极大。一方面，陈晓的刀的确被夺下了，一
方面陈晓又留任了，这应该是给陈晓的最后机会了。何去何从，就看他下一步的表现了。


** 【金鸿评论】又一轮房价调控开始了

   [2010-09-30 09:37:46]


   
　　为进一步贯彻落实国务院关于坚决遏制部分城市房价过快上涨的通知精神，国家有关部委近日分别出台措施，巩固房地产市场调控成果，促进房地产市
场健康发展。

　　据了解，这些措施主要有：

    一是各地要加大贯彻落实房地产市场宏观调控政策措施的力度。要立即研究制定贯彻落实国发[2010]10号文件的实施细则。

已印发实施细则的地区，要根据最近国家有关部委出台的政策措施进行调整和完善。房价过高、上涨过快、供应紧张的城市，要在一定时间内限定居民家庭
购房套数。严格实行问责制，对政策落实不到位、工作不得力的，要进行约谈，直至追究责任。

　　二是完善差别化的住房信贷政策。各商业银行暂停发放居民家庭购买第三套及以上住房贷款；对不能提供一年以上当地纳税证明或社会保险缴纳证明的
非本地居民暂停发放购房贷款。对贷款购买商品住房，首付款比例调整到30%及以上；对贷款购买第二套住房的家庭，严格执行首付款比例不低于50%、贷款
利率不低于基准利率1.1倍的规定。各商业银行要加强对消费性贷款的管理，禁止用于购买住房。对不认真执行差别化信贷政策的商业银行，一经查实要严肃
处理。继续支持房地产开发企业承担中低价位、中小套型商品住房项目和参与保障性安居工程的贷款需求。

　　三是调整住房交易环节的契税和个人所得税优惠政策。加强对土地增值税征管情况的监督和检查，重点对定价明显超过周边房价水平的房地产开发项目
进行土地增值税的清算和稽查。加快推进房产税改革试点工作，并逐步扩大到全国。

　　四是切实增加住房有效供给。各地要加大对各地2010年住房建设计划和用地供应计划实际完成情况的督查考核力度，切实落实中小套型普通商品住房和
保障性住房建设计划和供地计划。房价上涨过快的城市，要增加居住用地的供应总量。认真落实支持公共租赁住房建设的税收优惠政策。鼓励金融机构支持
保障性安居工程建设，抓紧制定支持公共租赁住房建设的中长期贷款政策。

　　五是加大住房交易市场检查力度，依法查处经纪机构炒买炒卖、哄抬房价、怂恿客户签订“阴阳合同”等行为。对房地产开发企业土地闲置、改变土地用
途和性质、拖延开竣工时间、捂盘惜售等违法违规行为，要继续加大曝光和处罚力度。对有上述违法违规记录的房地产开发企业，要暂停其发行股票、公司
债券和新购置土地，各商业银行停止对其发放新开发项目贷款和贷款展期。

     【金鸿评论】政策的出台选在了一个非常敏感的时刻，国庆前一天。国庆和五一历来是卖房的好时候，也是涨价的好时候。

      首付提高30%是打压市场需求的，二套房50%和1.1倍利率及三套房停贷是打压炒房的，房产税是打压已有多套房人的，加上已经出台的囤地者一年不准
买地是逼开发商增加供应量的，加大保障性住房建设力度是减少商品房购买需求的。这次的打压比上次更成体系。

      这个时候泼出一瓢比史上更冷的水还要冷的水，只能说明北京打压房价的坚决态度。

      不要这说这一轮调控是史上最最严厉的，随着产业结构升级的加快，房地产商的苦日子还在后头。当年为了扶植这个产业放水太多，才导致这个行业
的超常规发展。现在随便掐一把，地产商们就会疼得不得了。

      这不，又有要提出新政可能误伤消费者了。这可真是笑话。不是有刚性需求吗？怎么会误伤？等房价一降，误伤的消费者不但不会很受伤，而是会很
感激。

      四月份出台政策后我的判断失误了，主要是低估了利益集团的对抗能力。今天的政策表明，他们同样低估了北京打压房价的决心。

      一线城市房价不降30%，政策是不会收手的。

      房地产业的好日子结束了。房价必然会降，达不到三成降幅，政策是不会收手的。没有最严，只有更严。

      新兴产业规划已经出来了，谁有钱投资可以往那些行业投，那里是淘金的好地方，房价的明天，将是漫漫熊途。到底能跌多少呢？因为缺乏第一手的
宏观经济数据，不好再乱讲了。只能这样说，住房的投资价值将会慢慢消失，它将重新变成消费品，人人消费得起的消费品，（当然，这可能需要3-5年左右
的时间吧）。


** 【金鸿评论】换个思路打房价如何？
   [2010-10-02 19:15:29]

   
     【金鸿评论】房价牵动着国人的心，可就是屡打不降，反而越打越涨，这样下去也不是个办法。四月份出台的严厉政策依然没有把房价打下来，不得不
在国庆之前再出新政。新政的效果如何呢？谁也不敢说一定能行。

    不过这样拖下去肯定不是办法。这么一轮一轮的折腾，买房的观望，卖房的死抗，抗来抗去资金链越抗越紧。也许哪一天撑不住了，恰好再出一个政策
，就把全国的楼市都打崩了。到了那时可就麻烦大了，开发商死是肯定的，银行也被背债太多，对经济一点好处也没有。

    现在房价不降，最大的麻烦是没有大公司带头降价的，一旦有大公司带头了，就好办了。现在，可否换个思路来操作？

    选一个中等城市，要求是房价偏高、大开发商云集的那一种，搞个特殊政策，把楼市泡沫挤碎。其实这个政策也不是多么难，比如把第一套房首付提到
五成、二套房全款，保证楼市崩盘（对于这个城市的地方财政，可以特别照顾一下）。

    这个楼市崩了盘之后，大开发商们可以拆了东墙补西墙，不至于一下子把一个城市的坏帐全压到银行。同时，对大开发商来说，有一个项目资金链断了
，就会影响他们其他项目的资金链，这样可以逼他们在其他城市降价卖房以快速回拢资金自救。另外，这样做还可以给大开发商们一个楼市崩盘的真实体验
，看他们是不是真的不害怕崩盘，如果怕，就带头降价；如果还有人接着抗，那就接着挤碎第二个、第三个，看谁最先挺不住。

    这样做的好处，既可以避免钝刀子割肉越割越疼（全国大规模崩盘情况的出现），保住大开发商们的性命，也可以坚定买房人的信心，提高政策效率，
还可以稳定金融，保证经济平稳过渡。


** 官媒评“房价最该降”八城市 三亚济南列前两位
   [2010-10-06 09:14:22]

   
    近期楼市政策迭出，全国一二线城市房价走向如何引人关注。在国庆前夕“二轮调控”突然出炉之际，新华网“新华房产”栏目评出了“2010中国房价最该下
降的八大城市”。江苏没有城市入选这个名单。

　　位居第一的是海南三亚市。2008年上半年三亚的滨海洋房与集合别墅售价在7000元左右，下半年上涨至9000元，2009年上半年迅速上涨至14000、17000
、19000元，至岁末，三亚出台了一人限购五套房政策以抑制已经突破三万元大关的海景别墅或洋房。

　　新华房产给出的评价是，三亚作为国际旅游岛的金三角中心，受到国内外消费者的青睐，房价快速上涨亦在预料之中，但如此短的周期集中翻番如此厉
害，再现了比当年更为惊人的疯狂。除非热钱与投机资金作怪，不然不可能短期集中上涨如此迅速，预期伴随政策管制与当地行政控制措施出台，再加上整
体环境的紧缩，三亚跌幅应该排名最前。

　　其他七个城市按顺序分别是济南、杭州、东莞、武汉、长沙、青岛和重庆。新华综合

————————————————————————

呵呵。。。。。。。。。。



** 【金鸿评论】吃了原告吃被告
   [2010-10-07 23:08:11]

   
日本中央银行昨日宣布将银行间无担保隔夜拆借利率从现行的0.1%降至零至0.1%。

温家宝会见韩国总统称各方应早日重启六方会谈。

中投副总经理汪建熙(Jesse Wang)周二表示,随着中投将注意力转向新兴市场,其可能购买俄罗斯出售的国有资产。

黎巴嫩议会多数派、受西方和沙特支持的“3·14”联盟6日发表声明，抗议叙利亚司法机关3日针对包括黎巴嫩国家检察官、警察部队领导等在内的33人发布逮
捕令。

美国国务卿希拉里·克林顿6日在华盛顿举行的《美国－格鲁吉亚战略伙伴关系纲领》第二次会议上发表讲话，再次要求俄罗斯从阿布哈兹和南奥塞梯撤军。
希拉里还表示，美国继续支持格鲁吉亚加入北约。

联合国秘书长潘基文6日敦促巴勒斯坦和以色列努力就核心问题进行直接谈判。

【金鸿评论】在展开分析之下，先说明一点：在目前的全球斗争中，中国并不是在实力远强于美俄欧日印等各方，而是处在一个远比他们强的位置上。中国
本来就是全球低端产品的最大出口者，中国这几年又成功的收编了东盟，再加上与日本韩国经济的进一步融合，这让中国成了全球中低端产品的主要提供者
。美国和欧盟（日本也可以算上）是在生产高端产品，可是，在天下大乱的时候（不光是战争，严重经济经济也算），没有高端产品可以活，没有低端产品
没法过。这个道理很简单，没有苹果手机照样过，不穿裤子怎么出门？中国正是靠的这一点，才让欧美两方离不开自己。而俄罗斯的经济在全世界没有什么
影响力，强有吓死人的军事力量，美国自然想法设想往死里整他，以免有一天俄罗斯经济上也强大了以后来挑战自己的位置，欧盟也怕被这个有枪没钱邻居
抢了，所以有机会就愿意配合美国打压俄罗斯，美欧的联合打压，自然把俄罗斯推向了中国这边。于是，中国成了美俄欧三方关键时候都必须靠一靠的安全
岛。

中国国内的问题也是一大堆，这个只要眼睛没毛病的人都能看得到。我平时不写是感觉写多了也没什么用，我又解决不了问题。如果我能使上劲，那我肯定
少写不了。好了，下面接着上回的尾巴分析：

上回最后说的是美国要对欧盟下手了，结果，第二天发生了一件吸引全世界眼球的事情：中德超常规会晤。

前面曾说过，7月份默克尔访华与中国建立战略伙伴关系、对华输出街技术、帮助中国进行产业升级，其实是被逼的。他必须先拿到中国的支持，才有本钱拉
高对美国的要价，要求美国支持自己整合科索沃。

我们可以想一想，哪个国家愿意把最好的技术交出来？即使交，也得慢一点、分批交吧？等局面一变自己形势有利了，也就不会再交了。这个算盘所有人都
会打，德国人自然不例外。那中国怎么对付呢？很简单，不见兔子不撒鹰。你不是想让我支持你吗？你拿多少技术出来，我帮你多少，你有耐心慢慢交，我
就有耐心慢慢帮。如果让我等烦了我还不要你的技术了呢？这就是主动地位的有利之处。

所以，我们就看到了一幕，默克尔7月以后多次要求温总理访德，可温总理出发去欧洲的时候，还没有安排访德的行程。最后不知道三娘使了什么功夫，把这
事促成了，于是乎，三娘亚欧峰会也不开了，急匆匆的回去做准备，还非要安排在梅泽贝格宫见面，要知道，这个地方以前只接待过六个人：希拉克、萨克
奇、普罗迪、巴罗佐、小布什、梅德韦杰夫，全是一把手，而我们温相是二把手。为了多一点会谈的时间，还专门安排直升机接送。就这样，这么短的时间
，这么突然的会见，居然搞出了一个新闻公报，我一看都感觉很奇怪，看来，真是被形势逼急了，这回的让步绝对是少不了的。中国要技术，德国要经济支
持。成交。

【金鸿评论】中德达成了交易之后，奥巴马傻了，再想搞欧盟难了，没有办法，奥巴马只好变脸，拿出巴以和谈这个大萝卜来哄欧盟。对美国而言，眼下必
须拦住已经开到了叙利亚的欧洲车队和阿拉伯车队（声援哈马斯的）。

于是乎，又有人出来“敦促”巴勒斯坦和以色列努力应该就“核心问题”进行直接谈判了。不过出来“敦促”的这个爷是个傻子，谁不知道巴以和谈最核心的问题
是圣城问题、难民回归和边界问题，最后才是定居点合法性的问题。这位爷对这三个主要的问题一概不提，逮住个定居点问题当核心，这是在拿谁到傻子呢
？

不过，有了态度总比没有好，尽管这个态度是美国给欧盟的。很及时的，黎巴嫩就和叙利亚吵起来了。看来，车队要原地休整了。

中东局面稍缓，希拉里就开始逼俄罗斯从南奥塞梯撤军了，看来，美国还是舍不得丢掉乌克兰呀，毕竟，这是插向老熊心口的一刀。

现在中国该做什么呢？只要在外围做一下热身就可以了。朝核六方会谈也不用太着急，反正现在德国人给好处了，先吃到肚子里再说，一下子塞进嘴里的肉
太多容易噎着。现在的局势是：

从中国这边赔了的欧盟要从美国和俄罗斯身上找回来，现在已经拿到了美国的中东让步，下一步是再逼科索沃让步。

美国开始算计俄罗斯，极力讨回在格鲁吉亚（及乌克兰）方向失去的东西，欧盟也会趁机揩俄罗斯的油。

美国在中东方向的损失从哪里补呢？找日本人要。所以，接下来日本的小日子恐怕又要难过了。昨天刚刚把利率降到零准备对付日元升值，现在这招恐怕不
好使了（今天下午一点日元已经升到1：82.11了）。哪天日本被吃的受不了的时候，他就会想起找中国帮忙来了，到那时，我们再吃日本技术。

当然，俄罗斯接下来也可能很被动，将来要求帮忙也很正常。帮忙没问题，中国人一向热情，不过好处还是得要的，亲兄弟还得明算帐嘛。中国已经提前开
好价了：中投副总经理汪建熙说了，可能购买俄罗斯出售的国有资产。要说中国提出的条件，还真让普京很难受：现在普京的确很缺钱，所以不得不搞一点
私有化救救急，可他绝对不希望卖给中国的主权基金，因为这样做有肉包子打狗的嫌疑。可是真要拒绝，恐怕也不容易，个中滋味，大家自己体会。这不软
不硬的一刀子，还真够普京受的。

现在是美俄欧三家互斗，中国在一边看热闹。谁撑不住了来贿赂一下，中国就帮谁一把。三家是越斗越惨，中国是越吃越肥，爽吧？

这样做也确实有点不地道，摆明就是吃了原告吃被告嘛。（10月7日）




** 【金鸿评论】借刀杀人
   [2010-10-09 21:16:11]

   
从今天起，如果一篇文章中用到的新闻太多的话，我将不再全部列出。如果大家有兴趣，可以去新华网、新浪新闻、中新网等网站的国际新闻频道查。我没
有任何情报，分析的基础就是新闻。

【金鸿评论】言归正转，先看一件怪事：

9月11日，中国在西沙群岛海域扣押了越南的一艘渔船及9名渔民。之后越南一点动静也没有，过了10天之后，越南突然想起这事来了，赶紧要求中国“迅速无
条件释放越南渔船及全部渔民”。中国驻越使馆代表的回答是，这艘渔船在捕鱼时使用了炸药，中国决定对船主进行处罚，缴了罚款后就会放人。越南人一听
，大呼荒唐，说中国扣押处罚越南渔船是“无理的”。不过之后又没动静了，到了10月6日,越南又想起这9个渔民来了，接着要求中国“立即无条件释放被扣押
的越南渔船和渔民”。

中国出手扣人，与中美决斗有关，警告越南不要站错了队，所以，越南第一时间连人也没敢要。过了10天，越南才要求放人。这一天，是温总理要求日本放
中国船长的日子，此前一天，中国曾对日本放出过胜负手，日本没敢应手，钓鱼岛扣人事件的局势到这一天就完全明朗了。这时候越南大着胆子要求放人，
潜台词是：现在东亚局势平静了，你该放我的人了吧？结果，北京还没放。为什么？航母三进黄海的事还没完呢。

可是现在越南又想起要人来了，而且态度比上次强硬了，注意，要求放人的前提从“迅速”变成了“立即”。是谁给了他胆子呢？很显然不是美国人。那又是谁
呢。我等了两天，才等到下面这条新闻：

8日，俄罗斯海军计划重建在越南金兰湾一处已经不存在的军事基地，此举恐令南海地区的形势变得更加复杂。

【金鸿评论】说到俄罗斯，先看一下俄欧美三方交手的情况：

考虑到可能面临美欧联手算计，俄罗斯先发制人：7日，俄罗斯总统梅德韦杰夫出访塞浦路斯时再次呼吁缔结新欧洲安全条约。他的理由是什么呢，“单靠北
约和欧盟不能解决欧洲的安全问题”——在俄罗斯眼里，欧洲的安全很成问题。北极熊果然是不穿衣服的，赤裸裸呀。第二天，北约秘书长拉斯姆森（丹麦前首
相）马上回应，北约成员国应当与俄罗斯在反导系统领域合作。欧洲人接受威胁。

欧洲人的态度让希拉里很不高兴，因为此前希拉里曾经大声要求俄罗斯从南奥塞梯撤军。于是加沙枪声又起，有人警告欧洲，步调要走一致啦。这时，希拉
里再次喊话，要求俄罗斯从南奥塞梯撤军。

要说欧洲人不敢跟着美国人对俄罗斯下手，也是有原因的。在此前两天，美国还想把欧盟撕碎了，靠着中国的支持才渡过了一劫。惊魂初定的欧盟怎么敢马
上跟着美国人走？接下来美俄欧三家如何斗法，还得再观察。回头说金兰湾的事。

【金鸿评论】越南在这时拉俄罗斯，充分显示了他的投机本色。

如果越南拉的美国，那中国可以直接出手揍他，可俄罗斯不同。美国是死敌，把美国赶出东南亚是原则，谁拉美国谁就是敌人，这是红线。可俄罗斯不同。
俄罗斯是上合的战略伙伴，是朋友，要团结。所以，对于越南拉俄罗斯的事，中国不能正面打击越南，更不能与俄罗斯翻脸。

但是，越南海军进入金兰湾是绝对不可以接受的事情。如果俄罗斯进来搞一搞经济上的合作，是可以容忍的，但他的军事力量进来是绝对不行的。这会直接
干扰中国彻底收编东盟小国。

现在，重进金兰湾是俄罗斯在放风，越南并没有正面回应。很显然，越南是在试探中国的态度。如果这个放风就能逼中国放了人，那么，以后只要有麻烦，
他就会打这张牌，这对中国很不利。也许俄罗斯人进不了金兰湾，可对中国始终是个要挟。

那么，中国应该怎么应对呢？

结合目前的局势，有个办法可以一试：从金融层面下手，借刀杀人。怎么讲呢？先看一下目前的全球金融局势了：

今天3月18日，美联储开始实施量化宽松的货币政策，正式启动印钞机。之后的三个多月里，全球汇市相对平稳（欧元除外）。进入7月份，日元、英镑等货
币纷纷开始升值。

进入10月份，伯南克又说要购买更多资产提振经济，要二次开动印钞机。这时，日本第一个蹦了出来，把利率降到了零，准备对抗日元升值。接着，韩国、
泰国、新加坡等也纷纷介入市场。巴西财长曼特加则喊出了“我们正处于一场国际性的货币战争中”的声音，至此，货币战争的盖子揭开了。 

近两个月来，一直有人在瞎吵吵，说什么中国对美国让步了，中国软了，特别是解决钓鱼岛扣人问题的时候，许多人一口咬定中国对美国让步了，因为人民
币升值了。其实，现实根本不是这样。我查了一下近两个月几个主要国家货币兑美元的波动情况：

日元，从1：87升到了1：82，升值至少6%；

欧元，从1：0.75升到了1：0.71，升值至少6%;

瑞士法郎，1：1.04升到了1：0.96，升值在8%以上；

新加坡元：1：1.35升到了1：1.3，升值5%左右；

澳元：仅过去一个月就升值了8.3%；

而人民币呢，两个月来累计升值2%。

对比这组数字可以清楚的发现，人民币的升值是非常小的。要说这2%的升值是在对美国让步，还不如说是在照顾其他货币升值的国家。因为现在国际贸易大
都是用美元结算的。美元暴贬直接恶化了这些国家的出口环境，如果人民币死死盯住美元不贬值，那这些国家的对华出口就会有大麻烦，进而引发不必要的
贸易战。人民币稍升一点，可以堵一下他们的嘴。

前几天，温总理访欧时欧盟也要求过人民币升值，其实欧洲人也不是在替美国人说话，他们是在替自己说话！要知道，从六月份以来，欧元已经从1：0.84的
低谷升到了1：0.72，升幅达15%，这让欧盟怎么受得了？从08年10月以来，欧元已经坐了三回过山车了，经济上真没少受折腾。

当然，近几天的事实也证明了这一点：

6日，盖特纳对中国发最后通牒，要求建立“有效的多国机制”解决人民币低估问题。

同日，温总理在欧洲做工作，希望欧洲人不要跟美国一起掺合人民币升值问题。

同日，IMF总经理史特劳斯康承认，货币战一旦开打，全球经济就完蛋了，他说自己也支持人民币升值，但他认为人民币升值应该是北京当局改变政策、转而
提高内需的结果。这个过程可能费时数年，美国人当然不愿意等这么久（这个态度显然是亲华的）。

7日，欧洲人掉转炮口，开始狂轰美国，说他才是引发全球货币战争的罪魁祸手。这时，美国成了孤家寡人，凭他一已之能，又是重病缠身，如何打赢一场货
币战争？

8日，美联储理事布拉德表态，美联储可能要等到12月再就量化宽松做决定，美国喊了暂停。

9日，周小川在华盛顿举行的IMF和世界银行的年会上拒绝了美国和欧洲对加快人民币升值的要求，他说中国的货币改革将以渐进的方式进行，这个态度和上
面的史特劳斯康所说的非常吻合。

美国已经被金融危机折腾的受不了了，不印钞票他也没有其他的办法了。如果真不让他印钞，那他就只有死路一条了。但是，这钞票也不能白印，先让步后
印钞是必须的。这回就看美国怎么放血了。估计六方会谈要出成绩了。

如果美国开动了印钞机，肯定希望顺便来个水淹七军。对付这一招，无论是建水库还是修水渠，北京都干的很漂亮，中国这边是没什么问题。只要中国稳的
住，那第三世界国家就都能稳的住，前提是靠过来。美国真正可以啃到肉的国家，也就剩日本了。

当然，那个一心投机的越南是个例外。对于他，北京可以敞开一个口子，让华尔街再吃他一回，就象08年5月那样。对付这种好了伤疤就忘了疼的东西，只有
一个办法，那就是狠狠的给他一个教训，看他还敢不敢放北极熊进金兰湾！


** 66名中央干部将空降地方任职 全为部委后备干部
   [2010-10-14 16:44:24]

   
    金鸿：扛着尚方宝剑到地方，意味深长。看来某些父母官得注意了，再不换思想可就要换人了。

　　前段时间热议的“各部委及中央直属机构派出60名正局级干部到地方任职锻炼”一事终于尘埃落定：随着中央和国家机关到省区市交流任职干部培训班的
开幕，来自54个中央和国家机关部委的66名干部即将走向新的岗位——地方干部。

　　此次参加交流任职的66名干部分别来自54个中央和国家机关部委。66名干部中，平均年龄46.5岁，年龄最小的41岁，中青年干部是主体，而且他们几乎
都为各部委的“后备干部”。“未来几年后，这些人可能处于中央决策层。这些基层工作经验，无疑也是推动决策进行，”公共行政学专家、中国行政学研究会
常务理事、国家行政学院公共管理教研部教授竹立家指出，此前培养后备干部，多为单位内部培养，缺乏基层工作经验。而目前将干部直接派驻地方，则可
以更全面地了解中国地方发展状况。　



