# -*- org -*-

# Time-stamp: <2011-08-04 18:17:55 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent


* 【金鸿95】革西方经济学的命
  [2008-04-16 10:46:17]

  
西方经济学研究的对象是人类需求的无限性与资源稀缺性之间的矛盾。也就是说，西方经济学是在研究如何解决这么几个基本问题：生产什么和生产多少？怎
样生产？为谁生产？因为它的“高尚”地位，所以在西方国家被称为“社会科学之王”。

从18世纪60年代起，英国开始了工业革命；与此同步的，亚当密斯创立了西方经济学。这一理论成为了政府应该实行自由放任的经济政策提供了理论根据，从
此以后，“看不见的手”代替了“看得见的手”；从此以后，社会生产力迅速提高，资本主义经济高速发展，西风压倒了东风。

可是，人类发展到今天的结果又是什么呢？下面是一点简单的总结：

1、水资源枯竭：许多科学家预言，水在21世纪将成为人类最缺乏的资源。联合国秘书长潘基文不也在2007年12月3日说洁净水资源短缺可能成为未来国家间发
动战争的“有力诱因”吗？

2、海洋被污染：赤潮频发、石油污染严重、废弃物过度排放……

3、臭氧层被破坏：南极上空的臭氧层是在20亿年的漫长岁月中形成的，可是仅在一个世纪里就被破坏了60%。如果没有臭氧层的保护，地球上的所有的生命都
将消失。

4、土地退化和沙漠化：现在，地球上每分钟就有10多公顷土地被沙漠吞噬，也就是说沙漠正以每年700万公顷的速度扩展，日趋严重的荒漠化正威胁着10多亿
人的生存；与此相关的粮食危机也逐渐表现了出来。

5、温室效应：导致病虫害增加、海平面上升、气候反常、海洋风暴增多。如果地球表面温度的升高按现在的速度继续发展，到2050年全球温度将上升2－4摄
氏度，南北极地冰山将大幅度融化，一些岛屿国家和沿海城市将淹于水中，其中包括几个著名的国际大城市：纽约，上海，东京和悉尼。

6、大量物种消失：2007年４月，第三届世界植物园大会在武汉开幕，从大会上传出的消息是：全球目前已有34000多种野生植物被列为濒危物种；每年1000个
物种消失，物种消失的速度明显加快。如果任由其发展下去，，地球上近1/4的物种在未来50年内将遭受灭绝之灾。地球是一个大生物圈系统，如果它的平衡
被严重打破，人类绝对不会独善其身。

7、森林面积减少：据绿色和平组织估计，100年来，全世界的原始森林有80％遭到破坏。森林被誉为“地球之肺”、“大自然的总调度室”，对环境具有重大的调
节功能。人得肺癌活不了，地球得了就能活吗？

至于其他的废物质污染、核污染、基因污染、噪音污染等等就更不用提了。

不要觉的污染那么容易治理，事实上治理污染的成本是相当高昂的，甚至是得不偿失的，所以才出现了西方发达国家大量非法向海洋和发展中国家倾倒危险废
物的现实。

西方经济学的鼻祖亚当密斯说过：“所有人都以利己之心为动机，从事经济行为，在公正法律的支配下，由看不见的手(市场)引导，走向私利和公利的和谐统
一。”可是，两百多年的发展却证明，他说的不对，倒是恩格斯的话得到了验证：

 “我们不要过分陶醉于我们对自然界的胜利。对于每一次这样的胜利，自然界都报复了我们。每一次胜利，在第一步都确实取得了我们预期的结果，但是在第
二和第三步都有了完全不同的、出乎预料的影响。常常把第一个结果取消了。”

    人类正在不断地遭到环境的报复，这都是人类贪婪无度的向地球索取的结果。我们人类正在品尝着自己盲目行为的恶果。而这一切，仅仅靠公民的节能意
识与环保意识是绝对不够的。现在的最大问题是：是什么导致了人类如此的贪婪？

答案：市场经济体制造成的，都是那只“看不见的手”引导的结果。

市场经济体制的本质就是纵欲经济，它放纵着人们的欲望——所有的个体（无论是个人还是企业或者其他组织）都在追求自身利益的最大化，满足自己的私欲（
以物质需求为核心）。每一个个体都在为了实现自身利益的最大化而努力时，也就出现了人类向大自然无度索取的情况。这种局面在市场经济体制下是无法改
变的。

还是用一个例子来说明一下吧：比如彩电行业。企业为了生存，希望消费者能大量的购买自己的彩电，一个家庭买100台最好，那是VIP顾客。但是，制造彩电
是需要资源的，大量浪费资源的结果是什么？不就是上面那些触目惊心的事实吗？在市场经济体制下，对于这种情况政府能管吗？政府能禁止一个家庭买100
台彩电吗？还是政府能够限制哪一家彩电企业的生产规模扩张？再拿家用电脑行业做例子，现在的电脑技术进步飞快，根据那个摩尔定律，CPU的性能每18个
月提升一倍。这样一来，电脑的使用寿命远未到期就大量淘汰了。还有手机，更新换代的速度更快。但是，电脑电视手机这些电子产品垃圾当中含有铅、汞、
镉等重金属元素，这些重金属很容易进入土壤和水里，进而给人类和环境带来长期的危害。处理这些垃圾的代价却是极为高昂的，欧美发达国家经常采用的一
个办法是向中国发展中国家大量出口电子垃圾，以保证他们国家的山清水秀（即污染转移）。这只是一个电子类消费品行业的例子而已，其他哪个行业不是这
样？一边是无度的索取，一边是大量的制造垃圾，结果是什么？不就是人类集体自杀吗？

    如果用一个比方来说明，就是：地球是一个参天大树，人类是树上的蛀虫。在一定范围内，蛀虫从树上吸取养分对大树造不成实质性损害，因为它有再生
能力。但是，一旦蛀虫越长越大，数量越来数多时，大树就吃不消了，终有一天，大树会被啃死。之后的蛀虫去哪里生存？再找一棵大树？如果找不到新的大
树呢？

只要那支“看不见的手”继续指挥着人类，人类无度的向自然索取的局面就不可能改变，整个自然环境被彻底破坏将是必然的，接下来就是自杀。如果人类还希
望自己的子孙后代能够长久的在这个世界上活下去，这种经济发展模式必须进行根本性调整。人类必须从放纵整体欲望的发展模式转向控制整体欲望的模式的
发展模式。

    市场经济体制是无法控制人类贪婪欲望的，它无法在人类总需求与地球供应能力之间达成一个平衡——保证既满足人类的正常需要，又不透支地球母亲的体
力，也就无法做到人与自然的和谐相处。所以，现在到了革西方经济学的命的时候了。如果我们还希望自己的子孙后代能够幸福快乐的生活在这个世界上的话
，如果人类不希望自己成为地球上最短命的一个物种的话。

最后，用一句环境保护的广告词结尾：不要让人类的眼泪成为地球上的最后一滴水。
