# -*- org -*-

# Time-stamp: <2011-08-23 16:02:45 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 最近的一点思考（4）

[2011-08-23 02:01:54]

其实回到黄帝族奠定了在部落联盟中的主导地位之后，这种部落政治里面，还是应该有三大势力互相平衡。所以当尧作为部落领导联盟的时候，他的主要盟友，就包括炎帝族的四大酋长，所谓四岳。

这个时候，政治中的一件大事，就是黄河的洪水问题。

当时的洪水问题，和今天的洪水问题，有相同之处，也有不同之处。可以确定的是，黄河当年的泥沙问题，肯定没有后来那么严重。虽然喜马拉雅山在印度次板块和欧亚大陆板块的冲撞中，不断升高，导致了黄土高原的气候趋于干燥，但黄土高原在远古时代，应该还是有大片草原和森林。

这个地方的环境开始受到影响，是随着地球变暖之后，中国北方可耕种气候北移，出现了秦朝和汉朝为了打击匈奴而进行的军垦计划。当然 *后来黄土高原环境的彻底恶化，还是要归咎于明朝时候，和北元对抗的大规模毁林造田计划，和清朝为了对付准葛尔蒙古的军垦计划。*

既然尧所面临的洪水问题，不是黄河流沙问题，那么应该是那些问题呢？其实就是在黄河的上游，缺乏洪水时候蓄水，和缺少时候补水的蓄水池。而一旦在上游突降暴雨的时候，那么黄河在中原的中下游地带，通常是没有达到山东的东平湖之前，是可以相当于一个扇面的方式，爱向哪里流，就朝哪里流。

而这个改道的口子，基本上就是小浪底之后的孟津一带，那么任何改道就是中原地区人民皆为鱼鳖。北边的黄河故道，可以从新乡、去保定，从天津入渤海，而南边的黄河故道，可以从兰考，进洪泽湖，夺淮河入海。

黄河这种爱上哪就上哪的脾气，当然把当时的人们给折腾的够呛。不过看一下黄河灾难，在上游的炎帝旧部，和在山东下游的蚩尤旧部，都不是受灾群众，基本上可以打酱油。而在中原的黄帝旧部，就是受苦受难最厉害的了。

按照今天的想法，很简单，就是一方面要在上游建立蓄水池，那么就是地处于小浪底的三门峡水坝，用来调节黄河的水量。另一个就是要在上游，给洪水一个去处。当然今天就要考虑在黄土高原进行生态改造，防止过多泥沙入黄河。

这方面最经典的做法，就是陕北的高西沟。可惜的是，后来在中国农业的树典型上面，高西沟输给了山西昔阳的大寨，导致了中国农业的发展走了一条不同的路子。

但是建立三门峡水坝，这样的工程估计是在古代是不可能的了，唯一可能的法子，也许就是在渭河流域里下点功夫，可以让这里出现某种分洪的机制，那么最起码可以让渭河的洪水不要全部灌入黄河，还可以让黄河上游的洪水，分一点过去。

不过这种想法，在那个时候肯定是行不通的。因为尧的四大酋长，都是炎帝族的。不可能像后来的陕西省委那样，中央说啥就尽量配合了，结果三门峡治水，陕西自己好处是没有得到，鸡毛是飞了一地。

鲧的治水方案，肯定就主要是中游下手，那么法子很简单，就是 *尽量加固堤坝* ，把黄河限制在应该呆在的河道里面，不要乱跑。

这个法子，自然大部分都是中原地区的人民要出苦役的事情，肯定有不少怨声载道。但是该法子有两个大毛病，一个是 *特大洪水你肯定防不住* 。另一个就是 *堤坝的维护，是很成问题的* 。

那就是一旦水源不足的时候， *本位主义* 倾向出现。就会有些部落，会在鲧建立的堤坝上面挖一个孔，放水给自己的农田。然后也没有维修，那么大水一来，堤坝有毁了。这样的现象，大概是几千年后，也同样出现。

鲧治水的失败，应该是影响到了尧的权力继承计划，结果就不得不“让贤”给舜。而舜的支持者，则是以东夷族为主，共工等人在权力斗争中成了牺牲品，于是大禹出场了。

大禹的治水方案，除了修堤坝之外，还讲求为黄河分流。就是说你黄河在中下游有不少直流，那么我就首先要搞好水文调查，把各支流的情况给搞清楚。然后那些支流可以疏通入海，就把它们给疏通了。哪些支流，可以有个大湖蓄水，就把它们给修整好了。

那么 *大禹动手的是那些支流？* 一个是疏道了九河、漯水和济水，让它们直通渤海。九河就是黄河泛滥之后，从天津到山东惠民之间的低洼地，都成了黄河的出海口。这些是黄河北面的支流。

另一个就是开通堵塞的汝水和汉水，以及泗水和淮水，把部分的洪水分流去了长江。

从这里看出来，虽然分流的很多工作，必须由黄帝族的中原部落们去完成，那么在靠近出海口的地方，或者是淮河的地方，这些工程必须是有东夷族的部落们来干了。而从汉水往长江分流，肯定就是要三苗的群众们出来干活了。

于是东夷族，和它们的亲戚们三苗各部落，自然不愿意为你中原的人们出血出汗，所以人家就开始闹情绪了。

可以知道的是，大禹在洪水治理上的成功，肯定就团结了大多数黄帝族部落的人在大禹中央的周围。而依赖于东夷势力制衡炎帝势力的舜，肯定就要悲剧地让贤了。

大权在握的大禹，又因为治水的原因，对各地的山川土地都做了实地考察，又对土产特产了如指掌，那么收起税收来，那可是刀刀到肉，你想瞒报和逃税都比较难了。于是接下来的两个历史事件，一个叫做 *讨伐三苗* ，另一个叫做 *涂山大会杀防风氏* ，都可以看着前面闹情绪的后继事件。

当然最后就是大禹把大权传给自己的儿子启，又引发了黄帝族部落内部的权力斗争，自然是后话。不过可以看到的一个现象，就是当时的黄河治水，是最大的政治。那么根据如何治理的方案，而导致的各类利益集团的权力斗争，就一点都不令人出奇。
