# -*- org -*-

# Time-stamp: <2011-08-23 15:37:01 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 最近的一点思考（1）

[2011-07-30 15:02:38]


最近发生在挪威的事情，让我有了一些思考。

这个思考，暂时没法归结到哪个系列里面，而且关于历史的一些理解，还没有查阅资料证实，只能说是一些初步的想法。

现在我们处于的地球大环境，应该是一个变暖的环境。当然看过我的东西的朋友知道，我对于地球变暖的看法，和戈尔那帮伪专家的看法不太一样。因为地球在上一个千年，其实是在变冷，经历了一个小冰川时代。那么 *现在的地球变暖，其实是在这个寒冷时代之后，向正常的温度的回归。*

而这个回归的时间，大概会持续到2100年代。但是这个回暖的过程，也是一个波动的过程，就是这种 *30年为一个周期的波动过程* 。而我们现在处于的阶段，其实是趋于冷冻的波动，就是大概从2000年到2030年这个阶段。

这个阶段，其实就是中国需要完成工业化的阶段。这种完成工业化的时候，对能源的需求极大。上一次的变暖过程，就是从1970-2000这个阶段，中国是只赶上了一个工业化的尾巴。而且在这个阶段，工业化真正完成的是东亚的日本、韩国、新加坡，以及中国的香港和台湾。而且还出现了东欧的去工业化。

但是关于地球变暖的炒作，在这个阶段并没有成为世界舆论的主要风行话题之一。只不过伴随着中国的全面工业化的进展，就非常“偶然”的变成了最热门的话题了。而且关于地球变暖的原因，就和我们并不理解的地球变化，或者说太阳变化等等因素，没有了关系，从而成为人类的工业活动，尤其是中国发展的工业活动，大大相关了。

其实中国还是算运气比较好的，如果中国高速的经济发展，正好在30年的变热区域，那么估计中国人要被西方的口水给淹死了。而随着中国经济的进一步发展， *粗放型的耗能发展模式，会被精致的高能效发展模式取代。*

那么在下一个30年，地球开始进入更热的时段，需要工业化的印度、东南亚等国家，就要承担地球变暖的替罪羊了。

对人类来说，最适合生存的地方，其实是温带。我还没有查实具体的数据，但在印象中，大概是应该北边是北纬40度线，到南边的北回归线这个区域。

那么这个区域，在亚洲，南边边界，从东到西，在中国，大致是台湾岛的嘉义、澎湖列岛、广州、云南的个旧，然后是孟加拉国的达卡，过印度的中部，巴基斯坦的卡拉奇，然后过阿拉伯半岛中部。在非洲，就是埃及的阿拉旺，过撒哈拉沙漠的北部。然后在美洲，则是古巴的哈瓦那，穿过墨西哥的中部。

这个区域的北部边界，从亚洲，就是从日本的本州岛北部、朝鲜半岛的咸兴、中国的丹东、北京、大同、嘉峪关-玉门关、喀什，然后从中亚的费尔干纳、布哈拉，过里海到巴库，到土耳其的安卡拉，过希腊半岛的北端、意大利半岛的南端，过地中海，穿过西班牙的马德里附近。而在美洲，则是经过美国的费城、辛辛那提、过加州的北部。

在这样的一个温带地区，几乎是人类最早文明的起源之地。而在这个区域之外，就是所谓文明人眼中的野蛮人居住的地方了。而鉴于前工业化时代的主要人类生活，要么就是农耕定居型，要么就是狩猎游牧型，而北部边界，基本上就是这两大文明类型的分界之处。

当然要是简单的这样划界，是无法说明欧洲的情况，也无法解释罗马帝国作为人类早期文明的主要活动地之一。欧洲的人类居住条件，可以归结两个自然因素。一个是作为内部海洋的地中海（要知道，以前是没有苏伊士运河这个出口的），导致了更北端的法国和意大利半岛温暖一些，可以适合人类居住。

另一个因素，就是来自于墨西哥湾的暖流，在流入大西洋之后，本来是沿着北美洲东岸，一路北上，应该最后进入北极。如果这样的话，在欧洲的北部，其实是无法居住的，尤其是波罗的海应该彻底结冰。

可是这个暖流，到了波士顿附近，突然改变流向，横穿大西洋到了英国，然后过英格兰海峡，最后进入了波罗的海。这个暖流，就使得欧洲变成了适宜人居住的地方，使得这个温暖区，北移到了55度线。

*那么这个区域的划分，和地球的温度变化有什么关系？*

其实人类就像候鸟一样，当地球变冷的时候，在北方的游牧民族无法生存，于是就进行 *南侵* 来争取生存的权力和空间。这个是大家都非常明白的历史事实。可是大家比较不注意的另一个情况，就是当地球变暖的时候，在南方的定居民族，也必须逃避过热的生存环境，并且因为地球变暖使得北部的寒冷地带适合于耕种，于是开始其 *北伐* 的过程。

*所以说我们现在处在的这个时代，其实是南部的人类，生存条件恶化，必须向北部迁徙。* 那么从世界范围来讲，这个迁徙过程，大概会是几个主要的方向。

一个就是在美洲大陆，会出现来自南部的，主要是从墨西哥和其他中美洲，以及加勒比海地区的人民，会逐渐向美国渗透。而美国的所谓白皮肤的假原居民，则会因为北部温度的升高，继续向美国的北部，以及加拿大的北部迁徙。

这个地方，因为所谓美洲还是新大陆，美国和加拿大对人类人口增长的容量相当大，因此吸收的可能也比较大。

那么在欧洲，则是以北非为主要的人口来源地，向南欧的主要国家，比如说法国和意大利，以及以土耳其为主要来源地，向德国和北欧的渗透。这个地方由于人口密度较大，而且 *旧人口中的基督新教和新人口中的伊斯兰教，意识形态冲突比较大，会造成比较大的社会震荡。挪威出现的问题，就是这个社会震荡的先兆。*
