# -*- org -*-

# Time-stamp: <2011-08-23 15:55:08 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 最近的一点思考（3）

[2011-08-22 04:01]


前面提到的两个问题，引发了不少争论。

第一个就是有读者认为，世界大趋势的变化，不能只以全球气候作为唯一的考虑因素。这种看法是对的。我之所以把气候作为一个切入点，是因为 *气候影响的是人类生存的大环境，而这个大环境也包括生态状况、人口密度、生活水平等等。总之，一切让人类生活出现不适应和不舒服的地方，都可以考虑到这样的一种生存状态。而人类迁徙，就是发生在这样的一个情况，在尽可能的情况下，需要向更适宜生活的地方迁徙。*

当然人类社会实行了部分工业化和贸易全球化之后，对人类面临的自然灾害有了比较强的应付能力。要是放在以前，比如说出现大饥荒和大地震，比如说汶川、巴基斯坦、海地和日本那样规模的地震，或者索马里、俄塞俄比亚等等的饥荒，现在都可以看到人类的救助反应。

要是这样的情况发生在以前，那么当地的整个社会结构自然崩溃，带来的必定是灾民的大规模迁徙。

*在全球变冷的情况下，在古代出现的就是北方游牧民族，对南方定居民族地盘的侵掠。在中国的古代，有记载的应该是四次比较大的阶段。*

因为缺乏历史的考证，现在很难说，发生在5千年前黄帝族、炎帝族和蚩尤族的争斗，是这样一种情形。但大致可以确定的是，蚩尤族主要是以山东为中心的东夷族。而炎帝族，则很明确是以陕西和河南西部为主的古羌族。

倒是黄帝族的来历有些疑惑。如果按照大家认同的说法，认为黄帝族活动在中原地带。因为很简单，黄帝和炎帝联盟，与蚩尤的大战，是发生在逐鹿，也就是今天的河北，基本上是在桑干河地域和太行山的五台山以北地界。

这里是今天的北京的西部，和张家口的南部，比较像是从蒙古高原入侵南部的主要战场。如果黄帝族是中原部落，其和东夷族的主战场，应该是在河南和山东交界的菏泽和濮阳一带，其实就是刘邦和项羽之争，以及汉朝周亚夫平定六国之乱的战场。

因此我个人的看法，黄帝族当年应该是游牧于蒙古草原，极有可能是在气候变冷的情况下，南部入侵中原。因为先是获得了处于西北的炎帝族的支持，形成了军事同盟，最后打败了蚩尤族。这个结果，就是北方游牧民族迁徙入中原，而中原的一些东夷族，或者败走辽东和朝鲜半岛和日本岛，或者南迁，称为淮夷、以及后来生活在吴越地区和荆楚地区的百越。

而战胜蚩尤族之后，昔日的军事同盟炎帝族和黄帝族又争斗中原的主导权，最后是以黄帝族战胜为结果

当然黄帝族和炎帝族同出于少典部落，可以说是后来大概从关中，经过黄土高原进入河套的鄂尔多斯草原，然后在蒙古草原出现权力真空的时候，占据这个游牧之地。

这种情况后来的历史上有过多种重复。比如说匈奴亡后，乌恒和鲜卑兴，突厥亡后，回纥兴，然后回纥亡后，契丹兴，都是这样的填空游戏。

因此看待中国之后的历史，基本上可以确定的，之后的夏商周三个名称，夏似乎是黄帝族的后裔的联盟，商似乎是蚩尤族的后裔的联盟，而周似乎是炎帝族的后裔的联盟。

学术界的一种新的看法，就是不把夏商周看成是后来的朝代更替的形式，而是看成是一个同时存在的三个同心圆。其实就是大家各族的基本盘，一直都是存在的。只不过根据大家实力的强弱，在夏的时代，算是大家听从夏的号令，而在商的时代，大家听从商的号令，在周的时代，大家听从周的号令而已。

其实就是说中国大一统的政治形势，其实是到了秦朝在真正开始。而即使是在周朝的时候，各种名义上顺从，其实行为上独立的政治实体，还是有几千甚至上万家。最后是通过了不断的战争和兼并，然后从春秋到战国的七大政治国家，才最终成为了秦始皇的一统天下。而这个一统天下，主要的是靠着郡县制的政府结构代替了封建制的政府结构，靠的是官员的推荐选拔制度，取代了贵族血统传承的官二代制度来实现的。

可以引用的一个佐证，就是《公羊春秋》里面对“王正月”的大一统思想的强调。这种号称“六合同风，九州共贯”的情形，其实是并不存在的。当时号称天子的周王，每年向诸侯颁布历书的时候，希望大家都用同样的日历。

可是人家宋国这样的商地，自然是用自己的殷历，杞国这样的夏地，当然是用夏历。

如果这样理解历史的话，那么商朝势力占据主导地位，似乎又预示了天气变化，可能是向变暖的方向发展，这样导致了农耕民族的实力增强，而且商朝兴起的主要原因，大致是对马的掌握。

在古代时候，马作为一种军事武器，是非常重要的。因此古代的部落，谁的畜牧业发达，谁的军事力量就比较强大。而商朝的兴起，主要来源于对马的畜养技术，从草原的放牧，变成的圈养，并发明了马车来促进经济和社会生活，这就导致了其在军事实力上的增强。

那么当商朝兴起，在军事上实力增强，那么又在气候变暖，可耕农田可以向北部纬度高的地方移动，那么就显然出现了夏朝衰亡的情况。而在这种情况下，夏朝的一些部落，自然就会理所当然地，向从前适应于游牧的草场回归，因为那里的生存条件变好了嘛。

这里就提到了我对司马迁《史记》中关于匈奴来源的一个描述，就是 *匈奴是在商灭夏之后，其中的夏的一族北迁。* 由于司马迁所处的时代，是汉朝和匈奴交往非常密切的时代，这种关于匈奴来源的说法，自然是非常接近于匈奴族的本事认定。考虑到当时的匈奴没有入主中原的野心，因此和后来那些想来中原过日子的北方游牧民族，认亲戚的需要有所不同。

其实这说明了一个事实，那就是随着气候和居住条件的变迁，古代的中国各族部落，是可以北上和南下，前面谈到的黄帝族似乎是这样，后面出现的周族，其实也经历过从到北部游牧，后来又南下周原定居的过程。
