# -*- org -*-

# Time-stamp: <2011-08-23 15:10:05 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+STYLE: <link rel="stylesheet" type="text/css" href="css/org.css">

#+TITLE: 关于时事和时局

*** 关于时事和时局

很多读者，看《苍天黄天》和《最近的一点思考》不太耐烦，说是看不到时事的评论。

其实要看懂今天发生的时事，请回去看我3年前的系列，就明白了。

通常我是比较喜欢关注未来发生的事情，这个就不是时事，而是时局，就是按照各种条件的存在，未来局势的走向。

所以看我2008年5-6月的东西，主要是提供国际经济危机到来之后的解困之道。

我提出的“削强藩，均贫富，严吏治”的纲领，也是立足于中国未来十年，要解决中央政府权威，地方行政管理扁平化，社会分配不均，和基层政府组织黑社会化等等问题。

在内部发展上，我也提出了城市发展中的区域化，以高铁带动的新能源、新交通和城市间的同城化。这种人流、物流上面的整合，再加上互联网的普及，带来的信息流整合，最终要解决中国内部的割裂的地方市场，同时这种新的社会模式，会迫使地方政府的权力萎缩，从现在的经济发动机模式，转换成未来的公共服务提供模式。而经济发动机的增长，慢慢就会由企业，尤其是国企替代。

当然我也提出了中国内部自己的经济循环圈，以及这个循环圈走出国境，包含亚非拉，形成一个人民币为主干的生产循环。西部的发展，也同样的放到中亚的大局之下。当时我在2008年初的看法是，新疆软的一手不够软，西藏硬的一手不够硬。现在看来那时候的很多政策建议，今天都得到落实。

所以现在看我的东西，也是要到了2015-16年的时候，才会让大家感到透彻。《苍天黄天》的主要立足点，就是希望中国确实落实国民收入翻倍计划，避免走入帝国扩张之路。要防止历史上的大国崛起的教训，不要在今天的中国产生。

有兴趣的读者，可以去看一看这方面的历史，这样就会更明白地理解我的文章。

1. 俄罗斯帝国在克里米亚的战争。最后是新教的英国、天主教的法国、伊斯兰教的奥斯曼帝国，群殴了俄罗斯。结果导致了德国的崛起。
2. 德国在威廉下的盲动，没有听从老丞相俾斯麦的苦劝，陷入一次世界大战而被摧毁。
   
所以今天中国国内泛滥一片要和谁谁开打，要给谁谁颜色看看的躁动心理，值得大家警惕。

想我这样的立场，在2010年前，肯定是极右派的眼中之钉，而今天肯定是极左派的眼中之钉。所以大家不要惊奇。

既然大家都关心现在发生的事情，那么就简单评论一下吧。

在美国的大事情，主要是4件事。

**** 第一件是美国国会算是给国债的信用卡调高了上限，但是在收税方面没有突破，因此主要落手的地方是砍政府支出。

就是说上层富人不受影响，中下层中产们要收紧裤腰带。因为国防预算是一大目标，国防部长和三军总参谋长说，要小心，士兵们的饷银刚刚够谋生，不要逼人太紧了。

同时奥巴马总统发表讲话，强烈督促企业界，一定要解决1百万的退伍军人失业问题。活不下去的枪杆子，不是那么好玩的。

**** 第二件是标普把美国国债降了一级，直接影响就是打击美国经济。目前看来美国的新就业创造职位NFP的数字，似乎有些小猫腻，与大家一致的预测的7万3，翻到了11万3，估计是希望刺激一下市场。不过看来这个数字，也是不甚理想。

**** 第三件是美军海豹队的直升机在阿富汗东部，给打下来了。有可能是干掉本拉登的24个海豹队员牺牲了，加上陆军的特种部队人员，总数是31人。现在还无法判断，是不是中了人家的肩扛地对空。如果是那样，说明阿富汗的局势会更加恶化。

**** 第四件就是美国想继续留在伊拉克，而这个会不会引发美军和什叶派游击队的大规模冲突，是一个未定之数。

而中国的事情，大概也是4件吧。

**** 第一件是航空母舰瓦良格要出海了。前几天，中国战斗机驱赶美国U-2侦察机，表明了这里的对瞪眼睛，会加剧。美国的观点是，现在这里的军力是平衡的，是和谐的。你中国现在要打破平衡。中国的观点是，现在这里的军力是不平衡的，是你美国压制的结果，所以我中国军力必须大幅度增长，达到可以和你平衡，那才是真正的平衡。所以这里的局势，短期、中期和长期，都不会安静，只会从紧张走向紧张。直到真正的平衡达到的一天。
**** 第二件是新疆的喀什又有不怕死的出来找死了。这个其实是好事，因为喀什特区的实际工作达到了效果，有人撑不住，要出来搅局，把进展慢下来。
**** 第三件是动车事故。主要是两方面的问题，一方面是安全和管理问题，牵涉到铁道部改制、中央大部制等等方面。另一方面是事故的处理和善后，表明过去的一套处理方法和侧重点（比如山东的铁路事故），在过去行得通，今天已经不被民众接受了。说到底，就是新的社会生活体系，必须有相适应的政府和行政管理体制。
**** 第四件是最近闹得满城风雨的方正事件。很简单，就是“发展是硬道理”，不能和”只要GDP”画上等号。发展，不光是要经济发展，要赚多点钱，还要有社会的精神文化发展，要民族人格的发展。为了经济发展，而出卖民族尊严，那就是违背了发展的本意。



*** 时事和时局补充

[2011-08-09 04:56:47]

先说一下不幸丧生的美军海豹队。这次的海豹队员，不是一般的海豹队员，而是属于海豹第六队。这个第六队，通常是选择海豹队员里面最精华的人员，因此算是精英中的精英。

美国在反恐战争中，有三只秘密队伍，除了海豹第六队之外，就是陆军的三角洲，和中情局的特别行动队。而中情局的特别行动队，都是从海豹队员里面招募。而陆军三角洲，则是从陆军特种部队游骑兵里面的精华选取。

因为这支队伍，是属于高级机密，其行动和人员组成都是保密的。所以倒底这次牺牲的战士，有没有本拉登行动里面的人，外界很难知道。而这次损失，会极大地鼓舞塔利班的士气，也会打击美军的士气。如果死的人，还是同一批人，那么对士气的影响更大，因此不管真相如何，官方一定要否定的了。

另外就是对标普的降级，今天导致了美股的大幅下跌。奥巴马出来喊话，说是不管什么人评级，美国国债都是三个A，永远都是3个A。而且引用巴菲特的话，说俺们美国应该是4个A才对。

也有不少人评论，说标普早已经没啥信用了。而且按照美国新银行法的规定，你不需要根据评级机构的评级来决定资金的储备量，只要自己内部评估就行了。当然最好就是美联储宣布，大家不要用这个标准，可以继续按照持有美国国债依照3个A的法子就行了。

其实这些解释，都没有搞清楚，这个事件的真实含义。

<<当一个主权国家发行货币，其货币是代表了一种负债。就是你给我一个货币，我可以兑换回来我需要的商品。如果你没有对应的商品来支撑这个货币，那么货币就会发毛了，就是说不值钱了。>>

当年美国在没有独立之前，其中最红火的贸易，就是向印第安人收购毛皮，然后转卖到欧洲。可是当时国际贸易之间用的金子，不被印第安人认可。印第安人认可的货币，是串起来的珍珠。所以大家必须先去买珍珠，才可以去印第安人那里换毛皮。

后来在美国南北内战期间，为了打仗，林肯大幅度发现债券。那时候，如果政府欠了你的钱，就付绿票子给你，但是政府来收你的税，就要收黄金。于是在纽约就出现了美元-黄金炒卖场所。<<因为美元的命运，和联邦军队的战绩有关，所以这个时候大家看到兑换率波动，就知道联邦军队的战况。>>那时候炒家们为了最快的掌握信息，雇用的情报人员，比林肯自己要早知道战场实况。当然，这个不排除有人赌了一个结果，就试图买通战场上的指挥官，有意打败仗。<<这个时候的华尔街，是被林肯骂为李将军的第五纵队。>>

<<对任何货币来说，你必须有一个锚，就是拿来回笼货币，行使你的负债责任的一个工具。>>在布雷顿协定下，西方国家的货币，全部以国际储蓄货币美元为基础，而美元以黄金为基础。
你拿了美元，跑来结算，我美联储就以黄金来回收发行的美元。这个法子实行了不少年，最后就是<<美国在越战中发行了太多的票子，而通过二战积累的黄金不够了，于是美国国债隆重登场。>>

其实曾经想过用纸黄金的概念，就是你拿美元来，我给你一个纸片，上面书写“黄金五万两”。你拿回去，不能兑换。这当然没法行得通了。于是美国又眉头一皱，计上心来。你看看，全世界的安全，都是我保证的嘛！这样吧，你们手上的美元，自己消掉一部分，就算是交了保险费了。
这个就是<<美国国债发行和美元定期贬值制度>>。这样的话，你拿美元来结算，我就给你美国国债。而每次当美元发行过量，导致你手头美元过多，那么就采取美元贬值，同时促进美国货出口给你，来回收你的美元。

由于美国制造业逐渐萎缩，而不萎缩的部分，比如说高科技和军工这一块，又不对中国开放，而中国手头又掌握了最多的海外美元，那么这个制度现在也面临一个困局。

那就是说，<<整个美元为基础的国际金融体系，以及建立在上面的贸易和金融衍生品市场，都是根基于美国国债>>。

可是美国国债和黄金结算不同在于，黄金你给了就给了，而<<美元国债确必须支付利息。而这个利息必需来源于经济增长带来的税收增长>>。而一旦国债数量过大，而经济增长率过低，那么国债利息很可能就会导致税收不足支付，这样的话，体系就没有办法运作下去。

而标普的动作，其实是大家一直就有共识，总有一天会发生。只不过这一天终于来到的时候，很多人不适应而已。现在出现的情况，就是<<国债的零风险信誉受到挑战，那么以这个为基础建构的整个大厦，就会出现不稳定局面>>。

<<把国债上升的速度，和财政赤字的削减挂钩，其实是变相为国债封顶。>>那么美国经济赖以扩张的发动机被人熄火，将面临一个比较麻烦的停滞局面。

这个时候，世界经济需要的是给全球金融体系增加一根柱子，因为你的大柱子美元，和小柱子欧元，都风雨飘摇。

*** 再谈时局和时事

[2011-08-12 14:34:46]

前面说到世界经济需要另一根柱子，马上就有读者想起人民币取代美元问题。这种想法的朋友，为啥不能放弃一下非此即彼，非黑即白的思维方式？

人民币完全可以作为世界金融的三大支柱来撑起这个危机四伏的大厦嘛。美元还可以打理你的北美洲、南美洲和加勒比海。甚至跑到非洲，也没有关系。欧元，就是要争取南欧元向北欧元看齐，大家行为一致一点。你现在火头已经烧过了希腊、爱尔兰、葡萄牙，开始点着了西班牙和意大利，再下一步烧到英国和法国，就杯盘狼藉了。

人民币其实只要解决了东南亚、中亚和部分南亚（印度之外），再保证三分一到一半的能源，用人民币结算，那世界经济就会好很多了。

毕竟要是东亚这个经济发动机也熄火，那这个世界真要大乱了。

人民币在中亚和南亚的扩张，不是太大问题。倒是在东南亚，开始受到了一些阻击。尤其是以美国外交和军界为主的东南亚的遏制行动。

于是有人在网上喊杀喊打。这些人不知道，美国在东南亚的军事介入，是要花钱的。美国这次达成的国债协定，其中一条，就是参众两院，各派6个人出来，两党占半数，组成一个12人帮，来解决裁减1.5万亿美元的开支问题。

如果这个协议达不到，那么就会自动裁减1.2万亿美元，而其中的一半是从国防经费裁减。

<<美国现在的国防经费，主要要解决三个问题。>>一个就是军人的薪水和医保福利。一个就是现在进行的多头战争中的设备的购买和补充问题。不要小看了阿富汗和伊拉克的设备损耗。人家游击队一个炸弹，大概不到1百美元就可以搞定，把你一架装甲车给掀了，就是几百万美元，甚至上千万的损失。而且在沙漠和山地作战，对设备的损耗尤其大。这些都是大把花钱的地方。

最后一个就是美国好要大力投资在高新武器上，用来保证和中国、俄罗斯的武器差距。这个要花的钱更大。这样一裁减，就会让不少项目受到影响。比如说现在的F-35的前途，就变得不是那么清晰了。

在这种情况下，美国就是有心想在南海介入，也不一定有足够的银子。

因此中国是没有必要，猴急猴急地找架打。慢慢加强实力，今天航母出海，明天新战机出台，不断施加压力，就行了。

另外看到美国的国会那帮傻冒们，又开始想拿台湾来说事了。其实应对方法也很简单，只不过看中国政府有没有勇气做了。<<如果美国向台湾卖F16C/D，那么你就向伊朗卖J10。>>其实就这么简单。

<<中国现在的经济局面，还是要看通胀什么时候出现消退迹象。因此货币上的大趋势还是要从紧，当然不排除关键行业上的支持。>>

和2008年不同，当时中国对外贸的依存度还是过大，必须靠自己的刺激计划，来解决<<农民工的失业问题>>。而今天，中国在内需上已经有所进展，对外贸的依存度开始降低，因此没有必要再次防水。倒是好好经营一下<<人民币的外溢>>，可以减缓国内的物价压力。

当然国际大宗商品价格的走低，也会有所帮助。这次就<<一定要趁着欧美出现二次衰退危险的情况下，在能源和原材料上大幅度攻城拔寨，手上那么多美元，在加上人民币在进口结算上的进展，是时候好好在外面收购一把了。>>

最近发生的另一件事情，就是英国的<<黄金甲>>们到处抢劫和放火，算是给西方幸灾乐祸，看人家阿拉伯世界一片乱局的舆论们，一个回报。

但是倒是不少中国人，开始幸灾乐祸了。我倒是觉得，大家没有必要，看别人的乐子，因为我们自己也好不到哪里去。倒是<<好好研究一下，英国骚乱中的脸书、推特和黑莓的作用，值得安全部门好好借鉴。>>

其实用推特在短时间里面，号召起来几百号人，去抢劫超级市场的事情，美国已经发生好几起了。不过没有像英国这个，抢了还给打砸烧，搞得伦敦像是战场一样。

问题的关键点在于，<<最近几年下来，全世界不少国家的小伙子们没有工作机会了。>>年轻轻轻，又失业，无所事事，在街头一帮一帮晃来晃去，总有一天会搞出乱子来的。中国又不是没有见过这个场面，比如说80年代严打时候，就是这种情形。

因此中国政府必须提高警惕，<<要花大力气解决年轻人的就业问题>>。其中重中之重，是年轻的大学毕业生和退伍军人。<<如果解决不了这些人的生活问题，通胀又高企不下，然后又看到什么富二们出来开百万名车显摆，那就会成为社会乱局的导火索了。>>
