# -*- org -*-

# Time-stamp: <2011-08-23 15:26:18 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 再谈时局和时事

[2011-08-12 14:34:46]


前面说到世界经济需要另一根柱子，马上就有读者想起人民币取代美元问题。这种想法的朋友，为啥不能放弃一下非此即彼，非黑即白的思维方式？

人民币完全可以作为世界金融的三大支柱来撑起这个危机四伏的大厦嘛。美元还可以打理你的北美洲、南美洲和加勒比海。甚至跑到非洲，也没有关系。欧元，就是要争取南欧元向北欧元看齐，大家行为一致一点。你现在火头已经烧过了希腊、爱尔兰、葡萄牙，开始点着了西班牙和意大利，再下一步烧到英国和法国，就杯盘狼藉了。

人民币其实只要解决了东南亚、中亚和部分南亚（印度之外），再保证三分一到一半的能源，用人民币结算，那世界经济就会好很多了。

毕竟要是东亚这个经济发动机也熄火，那这个世界真要大乱了。

人民币在中亚和南亚的扩张，不是太大问题。倒是在东南亚，开始受到了一些阻击。尤其是以美国外交和军界为主的东南亚的遏制行动。

于是有人在网上喊杀喊打。这些人不知道，美国在东南亚的军事介入，是要花钱的。美国这次达成的国债协定，其中一条，就是参众两院，各派6个人出来，两党占半数，组成一个12人帮，来解决裁减1.5万亿美元的开支问题。

如果这个协议达不到，那么就会自动裁减1.2万亿美元，而其中的一半是从国防经费裁减。

*美国现在的国防经费，主要要解决三个问题。一个就是军人的薪水和医保福利。一个就是现在进行的多头战争中的设备的购买和补充问题。* 不要小看了阿富汗和伊拉克的设备损耗。人家游击队一个炸弹，大概不到1百美元就可以搞定，把你一架装甲车给掀了，就是几百万美元，甚至上千万的损失。而且在沙漠和山地作战，对设备的损耗尤其大。这些都是大把花钱的地方。

*最后一个就是美国好要大力投资在高新武器上，用来保证和中国、俄罗斯的武器差距。* 这个要花的钱更大。这样一裁减，就会让不少项目受到影响。比如说现在的F-35的前途，就变得不是那么清晰了。

在这种情况下，美国就是有心想在南海介入，也不一定有足够的银子。

因此中国是没有必要，猴急猴急地找架打。慢慢加强实力，今天航母出海，明天新战机出台，不断施加压力，就行了。

另外看到美国的国会那帮傻冒们，又开始想拿台湾来说事了。其实应对方法也很简单，只不过看中国政府有没有勇气做了。 *如果美国向台湾卖F16C/D，那么你就向伊朗卖J10。其实就这么简单。*

中国现在的经济局面，还是要看通胀什么时候出现消退迹象。因此货币上的大趋势还是要从紧，当然不排除关键行业上的支持。

和2008年不同，当时中国对外贸的依存度还是过大，必须靠自己的刺激计划，来解决农民工的失业问题。而今天，中国在内需上已经有所进展，对外贸的依存度开始降低，因此没有必要再次防水。倒是好好经营一下人民币的外溢，可以减缓国内的物价压力。

当然国际大宗商品价格的走低，也会有所帮助。 *这次就一定要趁着欧美出现二次衰退危险的情况下，在能源和原材料上大幅度攻城拔寨，手上那么多美元，在加上人民币在进口结算上的进展，是时候好好在外面收购一把了。*

最近发生的另一件事情，就是英国的 *黄金甲们* 到处抢劫和放火，算是给西方幸灾乐祸，看人家阿拉伯世界一片乱局的舆论们，一个回报。

但是倒是不少中国人，开始幸灾乐祸了。我倒是觉得，大家没有必要，看别人的乐子，因为我们自己也好不到哪里去。倒是好好研究一下，英国骚乱中的 *脸书* 、 *推特* 和 *黑莓* 的作用，值得安全部门好好借鉴。

其实用推特在短时间里面，号召起来几百号人，去抢劫超级市场的事情，美国已经发生好几起了。不过没有像英国这个，抢了还给打砸烧，搞得伦敦像是战场一样。

问题的关键点在于，最近几年下来，全世界不少国家的小伙子们没有工作机会了。年轻轻轻，又失业，无所事事，在街头一帮一帮晃来晃去，总有一天会搞出乱子来的。中国又不是没有见过这个场面，比如说80年代严打时候，就是这种情形。

因此中国政府必须提高警惕， *要花大力气解决年轻人的就业问题。其中重中之重，是年轻的大学毕业生和退伍军人。* 如果解决不了这些人的生活问题，通胀又高企不下，然后又看到什么富二们出来开百万名车显摆，那就会成为社会乱局的导火索了。
