# -*- org -*-

# Time-stamp: <2011-09-12 21:12:38 Monday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#***STARTUP: indent

#***TITLE: 最近的一点思考

#***AUTHOR: 井底望天


*** (一)

[2011-07-30 15:02:38]


最近发生在挪威的事情，让我有了一些思考。

这个思考，暂时没法归结到哪个系列里面，而且关于历史的一些理解，还没有查阅资料证实，只能说是一些初步的想法。

现在我们处于的地球大环境，应该是一个变暖的环境。当然看过我的东西的朋友知道，我对于地球变暖的看法，和戈尔那帮伪专家的看法不太一样。因为地球在上一个千年，其实是在变冷，经历了一个小冰川时代。那么现在的地球变暖，其实是在这个寒冷时代之后，向正常的温度的回归。

而这个回归的时间，大概会持续到2100年代。但是这个回暖的过程，也是一个波动的过程，就是这种30年为一个周期的波动过程。而我们现在处于的阶段，其实是趋于冷冻的波动，就是大概从2000年到2030年这个阶段。

这个阶段，其实就是中国需要完成工业化的阶段。这种完成工业化的时候，对能源的需求极大。上一次的变暖过程，就是从1970-2000这个阶段，中国是只赶上了一个工业化的尾巴。而且在这个阶段，工业化真正完成的是东亚的日本、韩国、新加坡，以及中国的香港和台湾。而且还出现了东欧的去工业化。

但是关于地球变暖的炒作，在这个阶段并没有成为世界舆论的主要风行话题之一。只不过伴随着中国的全面工业化的进展，就非常“偶然”的变成了最热门的话题了。而且关于地球变暖的原因，就和我们并不理解的地球变化，或者说太阳变化等等因素，没有了关系，从而成为人类的工业活动，尤其是中国发展的工业活动，大大相关了。

其实中国还是算运气比较好的，如果中国高速的经济发展，正好在30年的变热区域，那么估计中国人要被西方的口水给淹死了。而随着中国经济的进一步发展，粗放型的耗能发展模式，会被精致的高能效发展模式取代。

那么在下一个30年，地球开始进入更热的时段，需要工业化的印度、东南亚等国家，就要承担地球变暖的替罪羊了。

对人类来说，最适合生存的地方，其实是温带。我还没有查实具体的数据，但在印象中，大概是应该北边是北纬40度线，到南边的北回归线这个区域。

那么这个区域，在亚洲，南边边界，从东到西，在中国，大致是台湾岛的嘉义、澎湖列岛、广州、云南的个旧，然后是孟加拉国的达卡，过印度的中部，巴基斯坦的卡拉奇，然后过阿拉伯半岛中部。在非洲，就是埃及的阿拉旺，过撒哈拉沙漠的北部。然后在美洲，则是古巴的哈瓦那，穿过墨西哥的中部。

这个区域的北部边界，从亚洲，就是从日本的本州岛北部、朝鲜半岛的咸兴、中国的丹东、北京、大同、嘉峪关-玉门关、喀什，然后从中亚的费尔干纳、布哈拉，过里海到巴库，到土耳其的安卡拉，过希腊半岛的北端、意大利半岛的南端，过地中海，穿过西班牙的马德里附近。而在美洲，则是经过美国的费城、辛辛那提、过加州的北部。

在这样的一个温带地区，几乎是人类最早文明的起源之地。而在这个区域之外，就是所谓文明人眼中的野蛮人居住的地方了。而鉴于前工业化时代的主要人类生活，要么就是农耕定居型，要么就是狩猎游牧型，而北部边界，基本上就是这两大文明类型的分界之处。

当然要是简单的这样划界，是无法说明欧洲的情况，也无法解释罗马帝国作为人类早期文明的主要活动地之一。欧洲的人类居住条件，可以归结两个自然因素。一个是作为内部海洋的地中海（要知道，以前是没有苏伊士运河这个出口的），导致了更北端的法国和意大利半岛温暖一些，可以适合人类居住。

另一个因素，就是来自于墨西哥湾的暖流，在流入大西洋之后，本来是沿着北美洲东岸，一路北上，应该最后进入北极。如果这样的话，在欧洲的北部，其实是无法居住的，尤其是波罗的海应该彻底结冰。

可是这个暖流，到了波士顿附近，突然改变流向，横穿大西洋到了英国，然后过英格兰海峡，最后进入了波罗的海。这个暖流，就使得欧洲变成了适宜人居住的地方，使得这个温暖区，北移到了55度线。

那么这个区域的划分，和地球的温度变化有什么关系？

其实人类就像候鸟一样，当地球变冷的时候，在北方的游牧民族无法生存，于是就进行南侵来争取生存的权力和空间。这个是大家都非常明白的历史事实。可是大家比较不注意的另一个情况，就是当地球变暖的时候，在南方的定居民族，也必须逃避过热的生存环境，并且因为地球变暖使得北部的寒冷地带适合于耕种，于是开始其北伐的过程。

所以说我们现在处在的这个时代，其实是南部的人类，生存条件恶化，必须向北部迁徙。那么从世界范围来讲，这个迁徙过程，大概会是几个主要的方向。

一个就是在美洲大陆，会出现来自南部的，主要是从墨西哥和其他中美洲，以及加勒比海地区的人民，会逐渐向美国渗透。而美国的所谓白皮肤的假原居民，则会因为北部温度的升高，继续向美国的北部，以及加拿大的北部迁徙。

这个地方，因为所谓美洲还是新大陆，美国和加拿大对人类人口增长的容量相当大，因此吸收的可能也比较大。

那么在欧洲，则是以北非为主要的人口来源地，向南欧的主要国家，比如说法国和意大利，以及以土耳其为主要来源地，向德国和北欧的渗透。这个地方由于人口密度较大，而且旧人口中的基督新教和新人口中的伊斯兰教，意识形态冲突比较大，会造成比较大的社会震荡。挪威出现的问题，就是这个社会震荡的先兆。


*** (二)

[2011-08-03 16:29:56]


其实现在看来，北非移民的方向，主要是以法国为主。

因为北非的不少国家，是旧法国殖民地，也是法语流行的国家，这些地方的移民，自然是以法国为主。虽然这次挪威出来砍人的白人右派哥们，认为社会主义对欧洲的危害太大，强调多元文化已经侵蚀了基督教，所以希望欧洲能够恢复天主教传统，重振当年的十字军的斗志，针对穆斯林的侵袭，采取另一场圣战。

当然当年十字军的圣战，从大的战略意义上来讲，是一场保卫战，应对东罗马帝国，被塞尔柱突厥占领。但是从战术上来讲，是一场进攻战，是以今天的法国和德国等地方为主的基督徒向东边征讨，而且最后是屡战屡败，在技术先进和战力优势的穆斯林军队的打击下，是一败涂地。

对欧洲的极端右翼来说，今天的对抗，不论是战略和战术上，都是一次背水之战，因为觉得给人家杀到老家来了。这样的情绪，虽然没有出现在欧洲的主流媒体上，但是从瑞士的制止建造尖塔、法国的制止穆斯林女人戴面纱、还有瑞典的行为，都表达了民间的暗流汹涌。

不过今天的天主教徒们，似乎比起新教徒们，要更加软弱和温和。因此在短期内，看到的欧洲反穆斯林潮流，似乎不是针对北非的移民。倒是来自中东、以及巴基斯坦的移民队伍里面，倒是让欧洲人恐惧的情形更甚。

但是随着穆斯林人口在欧洲的比重坐大，比如说到了2050年的时候，穆斯林人口在欧洲的比例，估计会达到25%，那么在文化上和宗教上，都可以和欧洲文明不分伯仲抗衡的内部异端文化，你自己的文明，因为缺乏宽容的内涵，无法消化别人的文化，那么就很显然地会最终走向文化冲突。

在美国的情形，就是旧人群的新教文化，和新人群的天主教文化的和谐问题。大家都知道美国历来出任总统，要求的是WASP男人。WASP，就是White白人，Anglo-Saxon就是盎格鲁-撒克逊、Protestant就是新教徒。

迄今为止，所有的美国总统，都是来自于欧洲北方白人—英国、德国、荷兰和爱尔兰的血统。唯一不合乎这个标准的，一个是肯尼迪，是爱尔兰后裔的天主教徒，一个是奥巴马，是一半爱尔兰后裔的混血儿。

而今天美国的白人仍然处于增长状态，因为靠了南部的红脖子们死命生孩子。但是这个趋势会在2040年停止，使得白人占美国总人口的比例，从1960年代的85%（今天是67%），下降到2050年的47%。而拉美裔人口，会从今天的16%增长到29%。非洲裔则保持不变为13%，而亚裔会从5%增加到9%。

可以想象的是，在这样的一个人口布局下，拉美裔的政治力量会变得相当强大。而作为美国社会同化和维系大家一体的意识形态，就是美国特有的华盛顿共识体系，是建立在作为个人的美国梦，就是说只要你个人奋斗，就一定会出人头地，和整个国家的经济强大地位，来保持各自不同宗教、种族、文化和民族的一致性。

有美国学者，把美国大致分为很多个不同的小社区种类，就是说其实现实上并没有一个一体的美国，而是由不同类型的人群社会自己安身立命，然后通过意识形态的体系，而链接在一起。

那么当美国经济开始失去昔日的光辉，美国梦越来越艰难的大趋势，无法提高自身主流文化的宽容度，又无法有效地同化其他的文化，将成为美国社会的很大的挑战。

因为很简单，当年的苏联帝国，就经历了中亚的穆斯林人口在生育率上的大幅度赶超，然后在1989年左右，俄罗斯族的人口比例，下降低于50%，然后引发了苏联帝国的分崩离析。

当年能够把苏联境内的各民族和各宗教团体联系在一起，靠的是共产主义意识形态。而当这个基点，受到了撼动，那么整个国家的链接，就折断了。

这个过程，我在以前的系列里面提到过，并用了一个名词，叫做“内部殖民化”。这个名词，可以比较明显地描绘目前在美国和欧洲出现的情况，其实包括德国总理梅克尔等人在内，都发表了关于欧洲多元文化的努力算是彻底失败了。

当然，并不是其他的国家，就会比美国和欧洲好多少。对俄罗斯来讲，这个也是同样的问题，那就是俄罗斯面临来自于中亚国家的穆斯林人口，向俄罗斯北迁的问题。而现在因为美国在中亚的动兵，还难以看出这些人群迁移之后，来自南亚，比如说巴基斯坦的人口，会不会北上，填补这些人口丧失的真空。

至于印度次大陆，可以看到的，其实有同样的北移的趋势。在西北部，可以看到印度教徒，大规模向印度占领的克什米尔地区移民，在北部，可以看到同样的印度教徒去占据被印度非法吞并的锡金，和非法占领的中国藏南。而在局势不稳定的东北部，则可以看到来自于西孟加拉邦的印度教徒，和孟加拉国的穆斯林，向北部蚕食。

当然印度人口的北迁，会在气候暖化之后，印度次大陆因为水源紧缺，形成更大的压力。但是印度的最大障碍，是因为中国的关系，无法顺利地越过喜马拉雅山。这估计也是印度一直梦想着把西藏从中国分裂出去的一个主要原因。想象的话，一个独立的西藏，估计迟早都会成为印度的盘中餐。

而中国在几个北方大国里面的情形，在比烂中，相对要好一点。一个是中国的民族融合历史上做得比较好，比如说最难以同化的犹太民族，在中国是自己心甘情愿地给同化掉了。作为中华文化核心的儒法家（我自己搞出来的一个新词，来描绘道德修为和法规行为的内儒外法的儒法一体化），是非常世俗的意识形态体系，在魏晋南北朝时代，成功地融合了佛教和道家，算是达到了三位一体，那么今天要做到的，就是五星红旗，迎风飘扬，就是要以儒法家为那颗大星星，然后让佛教（包括大乘的显宗和密宗）、道教（包括各种地方教种）、伊斯兰教和基督教（包括犹太教和天主教）这四颗小星星，大家和谐的团结在一起。


*** (三)

[2011-08-22 04:01:52]


前面提到的两个问题，引发了不少争论。

第一个就是有读者认为，世界大趋势的变化，不能只以全球气候作为唯一的考虑因素。这种看法是对的。我之所以把气候作为一个切入点，是因为气候影响的是人类生存的大环境，而这个大环境也包括生态状况、人口密度、生活水平等等。总之，一切让人类生活出现不适应和不舒服的地方，都可以考虑到这样的一种生存状态。而人类迁徙，就是发生在这样的一个情况，在尽可能的情况下，需要向更适宜生活的地方迁徙。

当然人类社会实行了部分工业化和贸易全球化之后，对人类面临的自然灾害有了比较强的应付能力。要是放在以前，比如说出现大饥荒和大地震，比如说汶川、巴基斯坦、海地和日本那样规模的地震，或者索马里、俄塞俄比亚等等的饥荒，现在都可以看到人类的救助反应。

要是这样的情况发生在以前，那么当地的整个社会结构自然崩溃，带来的必定是灾民的大规模迁徙。

在全球变冷的情况下，在古代出现的就是北方游牧民族，对南方定居民族地盘的侵掠。在中国的古代，有记载的应该是四次比较大的阶段。

因为缺乏历史的考证，现在很难说，发生在5千年前黄帝族、炎帝族和蚩尤族的争斗，是这样一种情形。但大致可以确定的是，蚩尤族主要是以山东为中心的东夷族。而炎帝族，则很明确是以陕西和河南西部为主的古羌族。

倒是黄帝族的来历有些疑惑。如果按照大家认同的说法，认为黄帝族活动在中原地带。因为很简单，黄帝和炎帝联盟，与蚩尤的大战，是发生在逐鹿，也就是今天的河北，基本上是在桑干河地域和太行山的五台山以北地界。

这里是今天的北京的西部，和张家口的南部，比较像是从蒙古高原入侵南部的主要战场。如果黄帝族是中原部落，其和东夷族的主战场，应该是在河南和山东交界的菏泽和濮阳一带，其实就是刘邦和项羽之争，以及汉朝周亚夫平定六国之乱的战场。

因此我个人的看法，黄帝族当年应该是游牧于蒙古草原，极有可能是在气候变冷的情况下，南部入侵中原。因为先是获得了处于西北的炎帝族的支持，形成了军事同盟，最后打败了蚩尤族。这个结果，就是北方游牧民族迁徙入中原，而中原的一些东夷族，或者败走辽东和朝鲜半岛和日本岛，或者南迁，称为淮夷、以及后来生活在吴越地区和荆楚地区的百越。

而战胜蚩尤族之后，昔日的军事同盟炎帝族和黄帝族又争斗中原的主导权，最后是以黄帝族战胜为结果

当然黄帝族和炎帝族同出于少典部落，可以说是后来大概从关中，经过黄土高原进入河套的鄂尔多斯草原，然后在蒙古草原出现权力真空的时候，占据这个游牧之地。

这种情况后来的历史上有过多种重复。比如说匈奴亡后，乌恒和鲜卑兴，突厥亡后，回纥兴，然后回纥亡后，契丹兴，都是这样的填空游戏。

因此看待中国之后的历史，基本上可以确定的，之后的夏商周三个名称，夏似乎是黄帝族的后裔的联盟，商似乎是蚩尤族的后裔的联盟，而周似乎是炎帝族的后裔的联盟。

学术界的一种新的看法，就是不把夏商周看成是后来的朝代更替的形式，而是看成是一个同时存在的三个同心圆。其实就是大家各族的基本盘，一直都是存在的。只不过根据大家实力的强弱，在夏的时代，算是大家听从夏的号令，而在商的时代，大家听从商的号令，在周的时代，大家听从周的号令而已。

其实就是说中国大一统的政治形势，其实是到了秦朝在真正开始。而即使是在周朝的时候，各种名义上顺从，其实行为上独立的政治实体，还是有几千甚至上万家。最后是通过了不断的战争和兼并，然后从春秋到战国的七大政治国家，才最终成为了秦始皇的一统天下。而这个一统天下，主要的是靠着郡县制的政府结构代替了封建制的政府结构，靠的是官员的推荐选拔制度，取代了贵族血统传承的官二代制度来实现的。

可以引用的一个佐证，就是《公羊春秋》里面对“王正月”的大一统思想的强调。这种号称“六合同风，九州共贯”的情形，其实是并不存在的。当时号称天子的周王，每年向诸侯颁布历书的时候，希望大家都用同样的日历。

可是人家宋国这样的商地，自然是用自己的殷历，杞国这样的夏地，当然是用夏历。

如果这样理解历史的话，那么商朝势力占据主导地位，似乎又预示了天气变化，可能是向变暖的方向发展，这样导致了农耕民族的实力增强，而且商朝兴起的主要原因，大致是对马的掌握。

在古代时候，马作为一种军事武器，是非常重要的。因此古代的部落，谁的畜牧业发达，谁的军事力量就比较强大。而商朝的兴起，主要来源于对马的畜养技术，从草原的放牧，变成的圈养，并发明了马车来促进经济和社会生活，这就导致了其在军事实力上的增强。

那么当商朝兴起，在军事上实力增强，那么又在气候变暖，可耕农田可以向北部纬度高的地方移动，那么就显然出现了夏朝衰亡的情况。而在这种情况下，夏朝的一些部落，自然就会理所当然地，向从前适应于游牧的草场回归，因为那里的生存条件变好了嘛。

这里就提到了我对司马迁《史记》中关于匈奴来源的一个描述，就是匈奴是在商灭夏之后，其中的夏的一族北迁。由于司马迁所处的时代，是汉朝和匈奴交往非常密切的时代，这种关于匈奴来源的说法，自然是非常接近于匈奴族的本事认定。考虑到当时的匈奴没有入主中原的野心，因此和后来那些想来中原过日子的北方游牧民族，认亲戚的需要有所不同。

其实这说明了一个事实，那就是随着气候和居住条件的变迁，古代的中国各族部落，是可以北上和南下，前面谈到的黄帝族似乎是这样，后面出现的周族，其实也经历过从到北部游牧，后来又南下周原定居的过程。


*** (四)

[2011-08-23 02:01:54]


其实回到黄帝族奠定了在部落联盟中的主导地位之后，这种部落政治里面，还是应该有三大势力互相平衡。所以当尧作为部落领导联盟的时候，他的主要盟友，就包括炎帝族的四大酋长，所谓四岳。

这个时候，政治中的一件大事，就是黄河的洪水问题。

当时的洪水问题，和今天的洪水问题，有相同之处，也有不同之处。可以确定的是，黄河当年的泥沙问题，肯定没有后来那么严重。虽然喜马拉雅山在印度次板块和欧亚大陆板块的冲撞中，不断升高，导致了黄土高原的气候趋于干燥，但黄土高原在远古时代，应该还是有大片草原和森林。

这个地方的环境开始受到影响，是随着地球变暖之后，中国北方可耕种气候北移，出现了秦朝和汉朝为了打击匈奴而进行的军垦计划。当然后来黄土高原环境的彻底恶化，还是要归咎于明朝时候，和北元对抗的大规模毁林造田计划，和清朝为了对付准葛尔蒙古的军垦计划。

既然尧所面临的洪水问题，不是黄河流沙问题，那么应该是那些问题呢？其实就是在黄河的上游，缺乏洪水时候蓄水，和缺少时候补水的蓄水池。而一旦在上游突降暴雨的时候，那么黄河在中原的中下游地带，通常是没有达到山东的东平湖之前，是可以相当于一个扇面的方式，爱向哪里流，就朝哪里流。

而这个改道的口子，基本上就是小浪底之后的孟津一带，那么任何改道就是中原地区人民皆为鱼鳖。北边的黄河故道，可以从新乡、去保定，从天津入渤海，而南边的黄河故道，可以从兰考，进洪泽湖，夺淮河入海。

黄河这种爱上哪就上哪的脾气，当然把当时的人们给折腾的够呛。不过看一下黄河灾难，在上游的炎帝旧部，和在山东下游的蚩尤旧部，都不是受灾群众，基本上可以打酱油。而在中原的黄帝旧部，就是受苦受难最厉害的了。

按照今天的想法，很简单，就是一方面要在上游建立蓄水池，那么就是地处于小浪底的三门峡水坝，用来调节黄河的水量。另一个就是要在上游，给洪水一个去处。当然今天就要考虑在黄土高原进行生态改造，防止过多泥沙入黄河。

这方面最经典的做法，就是陕北的高西沟。可惜的是，后来在中国农业的树典型上面，高西沟输给了山西昔阳的大寨，导致了中国农业的发展走了一条不同的路子。

但是建立三门峡水坝，这样的工程估计是在古代是不可能的了，唯一可能的法子，也许就是在渭河流域里下点功夫，可以让这里出现某种分洪的机制，那么最起码可以让渭河的洪水不要全部灌入黄河，还可以让黄河上游的洪水，分一点过去。

不过这种想法，在那个时候肯定是行不通的。因为尧的四大酋长，都是炎帝族的。不可能像后来的陕西省委那样，中央说啥就尽量配合了，结果三门峡治水，陕西自己好处是没有得到，鸡毛是飞了一地。

鲧的治水方案，肯定就主要是中游下手，那么法子很简单，就是尽量加固堤坝，把黄河限制在应该呆在的河道里面，不要乱跑。

这个法子，自然大部分都是中原地区的人民要出苦役的事情，肯定有不少怨声载道。但是该法子有两个大毛病，一个是特大洪水你肯定防不住。另一个就是堤坝的维护，是很成问题的。

那就是一旦水源不足的时候，本位主义倾向出现。就会有些部落，会在鲧建立的堤坝上面挖一个孔，放水给自己的农田。然后也没有维修，那么大水一来，堤坝有毁了。这样的现象，大概是几千年后，也同样出现。

鲧治水的失败，应该是影响到了尧的权力继承计划，结果就不得不“让贤”给舜。而舜的支持者，则是以东夷族为主，共工等人在权力斗争中成了牺牲品，于是大禹出场了。

大禹的治水方案，除了修堤坝之外，还讲求为黄河分流。就是说你黄河在中下游有不少直流，那么我就首先要搞好水文调查，把各支流的情况给搞清楚。然后那些支流可以疏通入海，就把它们给疏通了。哪些支流，可以有个大湖蓄水，就把它们给修整好了。

那么大禹动手的是那些支流？一个是疏道了九河、漯水和济水，让它们直通渤海。九河就是黄河泛滥之后，从天津到山东惠民之间的低洼地，都成了黄河的出海口。这些是黄河北面的支流。

另一个就是开通堵塞的汝水和汉水，以及泗水和淮水，把部分的洪水分流去了长江。

从这里看出来，虽然分流的很多工作，必须由黄帝族的中原部落们去完成，那么在靠近出海口的地方，或者是淮河的地方，这些工程必须是有东夷族的部落们来干了。而从汉水往长江分流，肯定就是要三苗的群众们出来干活了。

于是东夷族，和它们的亲戚们三苗各部落，自然不愿意为你中原的人们出血出汗，所以人家就开始闹情绪了。

可以知道的是，大禹在洪水治理上的成功，肯定就团结了大多数黄帝族部落的人在大禹中央的周围。而依赖于东夷势力制衡炎帝势力的舜，肯定就要悲剧地让贤了。

大权在握的大禹，又因为治水的原因，对各地的山川土地都做了实地考察，又对土产特产了如指掌，那么收起税收来，那可是刀刀到肉，你想瞒报和逃税都比较难了。于是接下来的两个历史事件，一个叫做讨伐三苗，另一个叫做涂山大会杀防风氏，都可以看着前面闹情绪的后继事件。

当然最后就是大禹把大权传给自己的儿子启，又引发了黄帝族部落内部的权力斗争，自然是后话。不过可以看到的一个现象，就是当时的黄河治水，是最大的政治。那么根据如何治理的方案，而导致的各类利益集团的权力斗争，就一点都不令人出奇。


*** (五)

[2011-08-27 14:39]

以黄河治理为契机，而展开权力倾轧，在后来的朝代里面，一直没有停过。北宋的时候，新党和旧党就因为黄河应该北流还是东流的治理方案，杀得昏天黑地。

而在抗日战争胜利后，当政的国民党政府，对自己挖开花园口，迫使黄河改道，令无数淮海人民成为鱼鳖的罪行，不加检讨。却因为当地的人民无奈搬迁到了黄河的旧道，而这些地方又变成了共产党的解放区。于是国民党政府，大义凛然，以遵循科学和尊重历史的态度，要堵上花园口，让黄河水回到故道，并在不给予充分时间搬迁的情况下，企图用黄河水来淹没解放区军民。

当解放区的军民忙于应付洪水的时候，人家国民党军队又不失时机的杀了过来。结果如何？那就是后来的淮海战役中，被老蒋淹了两次的当地老百姓，成了埋葬蒋家王朝最有力的因素。

国家大事，用于权争，古代是这样，现代是这样，未来也不会有啥子不同。当年的黄河治水是大家厮杀的战场，后来大运河开通的漕运也是同样的道理。元朝和清朝，发生了海运和漕运之争，今天大家看到的高速铁路混战，都是走的同样一条路数。

看一下清朝在公共工程上面的论战，某种程度上可以了解一下中国今天的关于高速铁路等等领域的争论。

清朝的时候，主要的是三大公共工程，一个是黄河治水，一个是盐务专卖，一个是漕运维护。这三个部门，都有专门的河道总督、盐务总督和漕运总督专职办理。

但是在乾隆治下，权臣和绅已经建立了官僚系统的大规模腐败的庇护体制，使得这些系统成为大量候补官员的混日子的地方。而在政府系统里面，大规模的腐败无法得到控制，又影响当时政治体系面临宗教团体白莲教的挑战。这个在嘉庆杀了和绅，决心改革的时候，成为主要的政治斗争。

嘉庆帝的改革，主要是两方面。一个是大批更换省一级官员，把各地的总督和巡抚差不多全给换掉了。另一个就是大幅度减缩政府财政，以断绝政府里面的贪腐行为。

但是在漕运问题上，情况变得相当的复杂。漕运系统，几乎就是相当于今天的铁道部。人家有和各地总督平级的漕运总督，而且各省有漕运官员，还有在运河旁边世袭屯田的旗丁提供漕运船只。当然漕运还有自己用于巡逻和保护河道和运输船队的兵勇，还有在各地方的检查站和关卡，再加上雇用的挑夫，那就是很多人都要靠这个系统吃饭。

而当时因为系统里面有不少等待候补放官的官僚，都挂在漕运吃饷，又加上价格的不断上涨，导致了整个运作系统的成本太高。而这些有导致的漕米的商品化，因为当地方官员因为治下的农民负担不起粮食的要求，那么就只好实行商品化原则，从市场购买粮食来补足。同时干活的人，越来越多的成为无业游民被招募来的水手。

因为征收粮食的地方官，和保证漕运粮食完成份额的漕运官，是属于不同体系，自然就展开了政治斗争。这个情况下，关于海运取得漕运的政策争论，就变成了一大朝廷的斗争焦点。

而这种不同利益斗争的结果，又因为黄河的原因，变得迫切了。那么黄河怎么又和漕运混在一起呢？那是因为运河过黄河的体系比较复杂，靠了一系列的湖泊作为吞吐，可以在运河水低的时候，靠着黄河的水溢出来，引黄济运。

但是当时黄河治水在河道总督的管理下问题却是成堆。其中有和绅的影响，虽然嘉庆帝换了两任总督，但改变不了一个事实。那就是如果黄河治理得太好，那么河道衙门的预算和拨款，就会飞走了。因此河道衙门的主要治水任务，是要保证黄河定期的泛滥一下，以证明政府拨款治水，是非常英明的。

而政府拨下来的治水专款，又经过种种渠道，进了京官们那些批款子下来的口袋里，导致了只有十分之一的款项，用于河道清淤工作。当然并不是京城里面的其他官僚都是傻子，因为毕竟清理河道，会雇用一部分无土地和无定居的游民，如果这些游民没有活干，那么国家的和谐问题，就严重了。

因此黄河是迟早要出问题，结果就是黄河发了洪水，就堵塞了运河，导致了漕运船只上不了北京。河道的问题，不光是影响了漕运，还影响了盐务。因为黄河洪水影响的是淮河流域，就是江苏的北部一带，而这里又是主要晒海盐和制盐的主要地方。

谈到盐务，就更是一个头痛的问题。和河道、漕运不同的一点是，虽然河道和漕运问题重重，但是可以说好歹受益的人们是官僚体系里面的各个集团，可以说是肉烂在了锅里，算是为国家稳定做出了贡献。

可是盐务最大的问题，是走私私盐，导致国家盐税的损失，而盐税是内务府的主要收入来源。

但是要是治理盐务，大力打击走私问题，就会触及到一个非常要命的隐患。那就是私盐买卖，事实上是容纳了很大一批的无土地和无定居的游民。现在人家是忙于刀头舔血赚一个玩命财，如果你把这些人的生计给端了，你想让他们干嘛？

考虑到当时朝廷已经彻底失去了对农村的控制力，而且一些县城的基层组织也涣散了，政府决定不要去惹事。当时的各种宗教秘密社团，在农村里面蓬勃发展。有佛教和道教渊源，但是带着反清倾向的白莲教、天地会和三合会，也有信奉上帝上身的神秘基督教团体。比如说，在广西一带的客家人居住地，基督教传教非常兴盛，最后终于酝酿出来拜上帝会的基督徒发动的太平天国革命。

所以当你的基层组织涣散，被各种宗教组织占领，结果就是只能表面上喊一喊维稳，真正可以维稳的工作反而不敢做了。

*** (六)

[2011-08-29 15:22:30]


可是办理海运的想法，遭到了沿海和沿河两方面的商业集团的强烈反对。对沿海来讲，自从1684年康熙帝取消了沿海商业贸易的禁令之后，当时已经有很多私人的船队，进行海运，主要是将华北的大豆运到南方。因为没有相应的货物可以从南方运到北方，这些海运的船只，通常都只有装载着沙子作为压舱北上。

因此赞成海运的官员，设想如果可以结合现有的私人海运法子，把漕粮往北运的时候，给人家一个20%私货的份额，然后回航的时候把大豆往南运，那岂不是更经济，把成本就降下来了。而其中最主要的降低费用，就是海运可以绕过漕运中间层层的关卡和检查站，可以避免雁过拔毛。

但是你不让人家拔毛，人家岂肯善罢甘休。其实当时的河运已经事实上商业化和私人化了。河边附近的商家们，已经包揽了漕运的生意，而且私底下带了私货北上，而且早就不是空船南下，而是带了私盐南行。这么一来，大家自然就是反对声高唱入云。

另一个原因，就是漕运水手们的生计问题，如果朝廷不给人生计，岂不是把这些游民给推到反清复明的阵营里面去了？而对海上贸易商来说，也怕朝廷介入。本来人家生意做得好好的，根本没有入大伙儿的视野，突然要改了漕粮海运，虽然会因此而增加生意，可也同样因此变成了朝廷内部各派集团的博弈新工具，成了新的大肥肉，那么谁知道朝廷里面的内斗结果如何，岂不是自己找麻烦？所以也是反对。

于是一个对国家有利的公共工程转变，就这样鼓噪一阵子，随着黄河洪水退却，堵住的漕运船只到达北京，一切归于平静。

最后的变化，反而是朝廷不可控制的变化。一个是1853年黄河改道，让漕运基本上难以进行。另一个就是太平军占领了江南一带，切断了运河通道。最后一个就是水手阶层里面，慢慢秘密会社兴起，使得这个阶层充满了反满的人物，那么自然朝廷也就不再顾忌你的生计问题。

于是在各种危机的时候，反而变革变得异常容易了。困扰政府多年的漕运问题，终于因为海运开通而得到解决。

如果看今天中国的高速铁路问题，你是不能直接拿漕运问题来做对比。但是你可以用同样的方法论来看清楚这个问题。

在清朝时代，漕运、河道和盐务，在江苏的淮安一带，形成了一个交接点。因为淮安是漕运总督的所在地，处于运河和淮河的相交之处，也是漕粮集中的集散地。而淮安的西部，是洪泽湖，差不多是黄河每次改道就要直奔的地方。在淮安的东部，则是盐城。所谓盐城，当然就是中国海盐的主要产地了。

那么中国高速铁路的位置，在于它是铁路部门主要侧重于客运的一支偏师，但是这几年却成了重中之重的主力部队。

为啥这样呢？因为铁路主要是两个功能，一个是客运，一个是货运。从经济效益上来讲，客运是赔钱的，货运是赚钱的。但是中国的国家利益，要求你一定要保证客运的通畅，可以允许全中国的人民，可以走南闯北、东进西来。不要小看了这一点， *正是因为铁路的畅通，在保证了中国成为一个政治统一的现代国家。*

这里稍微扯远一点，大家都知道，以前从内地到西藏拉萨，路途遥远，非常之困难。主要的一条交通要道，就是从云南到西藏的茶马古道。连当年中央人民政府的代表张经武入拉萨，还必须绕道印度的西孟加拉邦的加尔各答。

虽然后来在解放军和各族人民的辛苦努力下，川藏公路、青藏公路和新藏公路陆续开通，但是直到青藏铁路的建成和通车，在真正从根本上解决西藏和内地的紧密联系。

南疆的情况也是这样。从军事的角度来讲，控制了吐鲁番附近的达坂城，基本上南疆就无险可守。但是清朝时候经历的数次外部势力在南疆的分裂活动，主要的短板，是后勤供应的困难。

尤其是一旦河西走廊出现问题，比如同治回乱的现象，那么对新疆的掌控就成了问题。这个现象，一直到1949年之后，才得到彻底的解决。其中一个是北疆进行的军团建设，使得粮草对内地的依赖解决了。另一个就是新疆的铁路建设，尤其在南疆的环塔克拉玛干线路的完成，那么任何想在这里搞分裂的势力，就没有那么容易得逞了。

那么把话题扯回来，当年的军阀割据的时候，采取的法子，就是铁路车不同轨，有意识地采取了阻断各省民众的交往，从而达到产生不同身份认同的结果。

*因此中国铁路客运的主要目的，就是要低成本地解决内部的人民自由流动的需求，以此保证中国各地的人们可以维系政治上的身份认同。*

但是客运的压力，又因为沿海地区的外向型经济蓬勃发展，需要来自于中西部地区的农民工而形成运力不足的情况。在这种情况下，客运必须占据货运的空间，而使得货运的运力也不足了。

*不过要看铁路的功能，你必须把铁路放在整个中国的交通体系里面看。从交通的角度来讲，应该是4个大的体系。一个是刚才说的铁路系统，一个是航空系统，一个是高速公路系统，一个是海运系统。*

当然以前还有长江航运系统，估计黄河系统早就没有了。而长江航运也慢慢随着航空的发展，客运这一块，大概就只剩下了旅游了。当然货运还是有一些空间。

那么看这几大系统，可以看出，航空系统主要是客运，公路和海运系统主要是货运。公路上的客运基本上是短途和长途汽车，主要是用于弥补边远县城到火车站的城市，差不多起的是城市地铁和公共汽车的功能。

*** (七)

[2011-09-04 09:10:49]

海运系统和铁路的竞争也几乎没有。现在中国的海运系统，其实最大头是全球贸易，走向世界各大洲，在国内的部分，主要干的是北煤南运。

煤炭南运的港口，大概就是河北的秦皇岛港和黄驿港、天津港、山东的青岛港和日照港。基本上就是来自于陕西、山西和内蒙古西部这“三西”的煤炭，通过大秦铁路、朔黄铁路等等，西煤东送，然后从这些港口南煤北运出海。

如果考虑到中国经济发展的一个大变化，就是中西部省份开始经济加速时代，那么其中一个重中之重，就是沿海地区的劳动力密集产业，转移到劳动力的原产地中西部，而沿海地区开始向高精尖发展。

这个变化从交通格局来说，自然就是铁路部门担负的客运要求，尤其是针对工资收入低的来自中西部到东部打工的农民工的需求降低了。所以这个也是铁路部门，敢于取消便宜的绿皮车的底气。因为人家中西部的不少人开始要留在当地就业了。

但是因为产品装配在中西部了，那么你的原材料、半成品如果还是依赖从东部的港口进口，或者你的主要产品，不是经过亚欧大陆桥出去，还是要通过沿海港口出去，那么显然对货运的要求就比较大了。

所以在这种情况下，大家都看得出来。铁路的盈利状况会有所改善，因为货运量增加，赚得多了，而低成本客运量减少，补贴少赔得少了。这样的大肥肉摆在那里，各路神仙不带齐刀叉，拿你开刀，吃唐僧肉，那才是天下的怪事呢。

所以要裁减你铁道部，纳入大交通部是一个路子。把铁路系统砍成几十大块，本事大的抢货运专营公司，没那么大的也可以抢热线的客运公司。

而这个时候的铁路客运，基本上就可以说是主要满足商业客人和中产阶级了，人家穷农民工都当地就业了嘛。这样的话，你当然可以让这些人“被高铁”了，因为人家是出得起这个份子的。

当然网络上一片大骂高铁票价，是因为大家骂起LV来，丝毫不觉得心疼，但是要是能够占国家客运补贴的好处，干嘛不摆出一副为农民工伸张正义的傲娇模样。其实人家农民工可能早就改乘更便宜的长途汽车，被一场大火烧死，还不是被你这帮道德代言人彻底漠视。

不过要命的是，高速铁路速度太快，就踩进了人家中短途航空的地盘。因为人家的客源和你高铁的客源，基本上是重叠了。从北京飞广州，如果油价不冲破100美元的话，人家航空还可以占优势，可是从北京飞上海，从广州飞武汉这样的中途，航空非悲剧不可。

因此从利益博弈和有饼大家分的角度来讲，高铁降速是一定道理的。这种降速，可以导致一部分商业客户回归航空，而对不赶时间的中产阶层消费者而言，估计主要的影响，是长途和中途，比如说你成都和重庆的想进北京，那就只好坐飞机了。

但是短途的客人，比如说北京去天津，南京去上海，上海去杭州，基本上受影响不大。所以结果自然是皆大欢喜。

不过在铁路货运中的煤炭问题，可以看出来，一个是这些铁路基本上不占据中国的铁路主要干线，比如说京广线和陇海线之类，因此不会成为各种利益的博弈之处。倒是中西部发展中，人家不想成为简单的原料输出者，希望可以搞一些高附加值的东东，比如说我不做西煤东送，但是可以做西电东送，这个如果扯起皮来，又把电网这个大老虎给拖进来了。

这样的话，电网的整合问题，中西部发电企业问题，东部和南部省份的电网和发电问题，铁道部的煤运利润和海运各公司的利润等等，又会是一场大混战了。

而铁路其他货运的能力的提高，对高速公路长途货运，以及各地方政府依靠这些来雁过拔毛的各种公路收费站和关卡的收入问题，又值得一个一个具体的分辨了。

很可能出现的结果，可能是中国政府自己没有办法解决，反而要靠外部不可控制的力量来完成。比如说清朝的海运代替漕运，就是被外部不可控制的因素改变的。那么要是中东和北非的各种变故，导致石油价格的某种特定变化，那么才可能在中国引起连锁的洗牌效应。

不管怎么说，我在2008年大力鼓吹的高速铁路已经有了雏形。无论你是靠有人搞大跃进出来的，还是有人发疯折腾出来的，总算是出来了。总比奥巴马的美国高铁计划，还在图纸上折腾强多了吧。哪怕就是主干线跑个300公里，也比没有强吧。

谈完了铁路的问题，就接着谈中国的民族南迁的历史。

中国历史上第二次的北方游牧民族南迁，应该算是从周族避难，走到周原，直到文王奠定了崛起的基础，由武王完成了讨伐商朝的任务开始，到后来西北的戎族各部落的向东南方向迁徙，导致了镐京陷落，平王东迁。

这之后的北方侵袭，基本上因为管仲治理的齐国，实现了“尊王攘夷”的华夏族同盟，算是遏制住了。而随着气候的变暖，开始了秦朝和汉朝，向北部的扩张。而这种扩张的结果，一直延续到迫使了北匈奴的西迁。

然后第三次的地球变冷，又引发了北方游牧民族的南下。这次的南下，主要不是军事的入侵，而是北方的各少数民族，在中原经历了汉末黄巾之乱，各路军阀的混战，一直到了三国抗衡，然后在西晋的时候才短暂平息。这场乱局，北方各游牧民族的军事能力被中原的各军阀们借用，而在中原人口大幅度减少的时候，他们又成为了主要的劳动力补充力量。

但是这个时候的中原文化，已经受到了佛教的侵袭和道教的发展，董仲舒做了什锦大杂烩儒学，失去了整合的影响力，而导致了居住在中原的各游牧民族，保持了独立的文化体系，从而出现了内部殖民化。这个现象，就是今天的欧洲和美国开始面临的文化困境。

*** (八)

[2011-09-11 10:35:21]
 

在进一步论述之前，先解释一下 *内部殖民化* 这个概念。

所谓 *殖民化* ，主要是指某种文化，通过人口迁徙的方法，将带有自己文化特征的主体民众，移民到非文化地区，然后通过对原住地文化的改造或者说替换，以及对原住地民众的同化或者说种族灭绝，建立起自身文化的过程。

这个在历史上非常典型的做法，就是欧洲殖民主义者在南北美洲、以及非洲、大洋洲、和南亚等地的行为。这种殖民，通常是通过军事征服，然后强制宗教替换，再达到文化认同。其中某些阶段还包括对原居民的种族灭绝。

所以说殖民和简单的移民是有区别的。如果当初欧洲人移民到了美洲，完全遵循美洲印第安人的传统，然后也贡献自己的文化优点，那么这样产生的新文化，就不能算是殖民。

这种行为，更相当于中国传统中的外来民族的归化。

当然世界上的事情，也不是非黑即白。有的外来民族，本来是通过军事征服，希望能够殖民的，但因为在不同的文化冲击下，自己被同化，因此可以说本愿是要殖民，最后却被同化。

那么 *内部殖民化* ，通常指的是作为强势文化的一方，自愿地接受了外来的文化人口，但由于种种原因，而无法将接受的人口同化，从而导致了自己的内部主体，变成了外来文化占优势。

从这个角度去看，当年中国在三国和西晋开始了北方各游牧民族移居长城之内，是中原王朝自己的选择，而不是后来那样，是被人家军事征服的。而且移民进来的各族人民，在文化上基本上保留了自己的文化特点，在当时的不少省份中间，外来非文化人口，基本上达到了本地人口的一半，甚至一些地方还超过了本地人口。

在西晋的八王之乱后，很多汉族氏族大家庭衣冠南渡，也使得人口比例面临了变化。从这个角度来讲，中国当时的内部殖民化形势，和2050年预测的美国和欧洲形势，应该比较接近。

形成内部殖民的主要原因，就是文化上无法同化。当然如果你觉得文化同化，就是一种文化，比如说主体文化，把其他的非主流文化完全替换，从而让人家灭绝，那就是属于比较硬性的一种方式。这种方式，在唯我独尊的一神教文化，是非常明显。那就是只有我才是唯一的真理，你其他的都是妖魔。

要是你面临的非主体文化，也是同样的唯我独尊，那就是比较强烈的冲突了。这个在欧洲，主要是新教和天主教，面临伊斯兰教的挑战。而在北美，作为主体的新教，其实差不多同化的西欧天主教，使得新教为主导的政治社会文化体系，被西欧天主教所接受。

但是面对来自南美的南欧天主教的人口比例，这些政治社会文化体系，是否面临挑战，是一个未定之论。

当然这个唯我独尊的一神教的难题，其实相对宽容度大一些的多神教（看一下印度教徒对其他宗教的迫害）也要面临和想法子脱困。

但是当不少朋友，在谈到宗教问题和民族问题的时候，经常过多的注重关于计划生育而引发的汉族人口和少数民族人口的比例问题。以及关于汉族人口占总人口比例，从而对应我前文谈到的美国白人人口和苏联的俄罗斯族人口问题。

从这种关注中，自然而然地，就有人引申出要把少数民族汉化的意图。

这就牵涉到另一种意义的同化，就是从各种主体和非主体文化中，你能不能发展出一个全新的融会贯通的新文化。当然新的文化中，主体文化占的比例要大，是无容置疑。但是这种全新文化，却可以把本来的几种思维因素，完全的和谐和融合在一起。

因此强调汉化，是一种非常狭隘的看问题思维方式。中国要的绝对是不能是汉化，而是应该 *中华民族化* 。在这个中华民族化的过程中，各种民族，不论是主体民族，还是少数民族，其文化、语言、风俗都应该得到更好的保护，并在全民族的努力之下，更加发扬光大。

但是这个中华民族化的目标，必须是保证一种世俗化的温和中正的宗教氛围下，才可以实现。这就是我提出，引起争论的"*五星红旗，迎风飘扬*"的意图。

提出反对意见的，主要是两个角度。第一个就是我提出的“儒法家”，其中主要的儒家因素，有没有能力去和谐和融合其他的各大宗教。第二个就是如果这种可能不存在，那么应该用其他的什么方法。

很明显一种就是共产主义的理想，一种就是民主自由的理想。

先谈一下这两种不同理想的实践结果。前面一个就是前苏联，可以说是实行得比较好。后一个就是现在的美国和欧洲。但是大家看到，苏联最后的结果，是彻底崩溃，其中曾经势力微弱的俄罗斯的东正教、乌克兰的天主教、和高加索地区和中亚的伊斯兰教等等，都蓬勃发展，还引发了不少地区的冲突。

那么欧洲的不少国家，已经公开承认多元化文化的努力其实失败了，唯一可以等待结果的就是美国。

企图通过其他宗教融合，比如说印度的印度教，可以看到在南亚次大陆上，还是有不少的宗教冲突，尤其是印度与巴基斯坦，暂时解决不了问题。印度内部的宗教冲突，也有越演越烈的趋势。

而中国历史上的融合，却是比较成功的。这种融合，基本上是对中亚传入中土的佛教的文化同化，以及来自西北方的信奉佛教的游牧民族，同化得比较彻底。

