# -*- org -*-

# Time-stamp: <2011-09-15 11:34:09 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 龙之声国际观察 第十九期（2011年09月09日）


 *【新闻链接】* 2011年9月6日外交部发言人姜瑜举行例行记者会
问：请介绍法国外长朱佩访华有关安排。中法双方是否会讨论利比亚问题？

答：朱佩外长将于12日至14日对中国进行正式访问。访问期间，杨洁篪外长将与他举行会谈，中国国家领导人将予会见，双方将就中法关系及共同关心的国际和地区问题交换意见。朱佩外长在北京期间还将出席中法语言年“中国法语年”开幕式。

当前中法关系保持良好发展势头。一年来，两国高层互访、会晤频繁，这充分体现了两国关系的高水平。目前，双方正积极落实两国领导人达成的共识，共同致力于建立互信互利、成熟稳定、面向全球的新型全面战略伙伴关系。相信朱佩外长此访有助于推动两国关系向前发展。

关于利比亚问题，如果双方谈到这个问题，我想也是正常的。关于当前利比亚的局势，中方认为当务之急是尽快结束武装冲突，避免更多人员伤亡，通过政治手段解决利比亚危机。国际社会应切实尊重利比亚的独立、主权、统一和领土完整，切实尊重利比亚人民的自主选择。

在利比亚战后重建问题上，中方认为联合国应该发挥主导作用。国际社会应该在联合国的框架下，支持利比亚战后重建。中国愿与国际社会一道，共同推动利比亚局势走向缓和，使利比亚早日走上和平、和解和重建的道路。

 *【新闻链接】* 外交部发言人姜瑜６日表示，联合国应在利比亚战后重建中发挥主导作用。国际社会应在联合国框架下支持利比亚重建。中方愿与国际社会一道，共同推动利比亚局势走向缓和，使利比亚早日走上和平、和解、重建之路。
 
姜瑜在例行记者会上回答有关利比亚“全国过渡委员会”地位的问题时表示，中方对其地位的承认要“水到渠成”。

姜瑜说，关于利比亚局势，当务之急是尽快结束武装冲突，避免更多人员伤亡，通过政治手段解决危机。国际社会应切实尊重利比亚的独立、主权、统一和领土完整，切实尊重利比亚人民的自主选择。

她说：“利比亚的动荡是暂时的，中利友好是永久的。我们重视利比亚‘全国过渡委员会’的地位和作用，愿意与其保持密切沟通，推动双方关系继续平稳向前发展。”

姜瑜表示，在参与利比亚战后重建的问题上，中国有关公司将自行进行评估决策。中方愿与利比亚在相互尊重、平等互利的基础上开展互利经贸合作。“我们愿为利比亚重建提供力所能及的帮助。”

 *【时事解读】* 在法国总统“顺道”来华访问体温还留在华夏大地之时，法国外交部长就迫不及待的要来中国访问，其背后还是想当然的认为，在欧洲已经“顺利拿下”利比亚之后，欧洲目前所要做的第一件事，就是坐实在利比亚的利益，这个利益，就是深埋在沙漠深处的石油。

在金融之战打到今天这个份上，作为世界两大主要货币之一的欧元一直在美元的攻击下苦苦挣扎。而中国出于国家利益，为防止欧元溃败而导致美元一支独霸，一再在倾向性的支持欧元与美元对峙。

而欧洲能否取得在与美元对抗中的相对平衡，那么稳定欧洲内部及欧洲的后院，也就是所谓的大地中海地区，是关键所在。当初法国之所以在利比亚战争中，在西方阵营中打头炮，原因也在这里。在与各主要角力的讨价还价中，利比亚战事之所以如此顺利，背后离不开另外两大力量的支持，这两大力量，就是一直关注并在利比亚、北非着力很多的中国与俄罗斯。

法国人明白利比亚战事顺利的原因何在，因此，法决策核心阶层的两位轮番出马，是摆在明面上的事。

可以说，中俄两国协调立场，特别是俄罗斯态度突然转变前夕，中国国家主席在上合组织开会后，先后访问了俄罗斯与乌克兰两国，随后，俄总统通过G8峰会上与法国总统与美国总统会谈后（注意顺序）发表声明，“卡扎菲必须下台”，两个半月后的2011年8月上旬，俄又声明承认利比亚反对派为“合法”政权。“随后”，反对派作战能力突然大增，如摧枯拉朽之势，占领利比亚首都。

细心的读者，如果你仔细研讨观察员给定的上述事件的发生顺序及结果，你就明白，利比亚战争这么顺利的真正原因了。也许并不是乌合之众的利比亚反对派别战斗力突然增强，更不是突然出现的多管火箭炮如何威力巨大，而是突然出现的神秘特战部队。想一想空中的战斗机狂轰乱炸，地面装备精良的特战部队，卡扎菲那点作秀可以，战斗力低下的部队哪是对手！

再谈中俄态度调整的原因。在以希腊为突破口，然后蔓延到葡萄牙，西班牙，已经有苗头向欧洲的核心国家之一意大利侵袭的金融攻击，一旦让美国资本得手，出现欧洲溃败而金融秩序大乱，其结果可能就是欧洲国家的经济低迷甚至崩溃，引发的就是欧洲此起彼伏的游行，抗议和动乱。作为俄罗斯的经济支撑最核心的欧洲一旦到此地步，以能源为生存的俄罗斯，到时看到的就是石油“大甩卖”进而导致俄罗斯经济崩溃，其大国雄心也可能随之湮灭，这个局面一旦出现，对俄来说，是多么可怕的景象！

于是乎，在俄与法美两国总统会谈后，由于得不到美国的承诺，俄及时的调整了立场。而此次调整立场，与出席上合组织会议并在莫斯科访问的中国国家主席的沟通是必不可少的。于是，利比亚战争急转直下。要知道，五月份老卡的军队一直在围着班加西在打，在俄罗斯发表声明后就丢盔卸甲，这才是利比亚战事突变的根本原因。

中国只所以在利比亚问题上早先保持低调，而在利比亚战事已近尾声时突然高调，大谈“联合国”的作用，其目的不言自明。龙之声观察员认为，在国家利益层面，以讲道义条件下的搏取利益，总比赤裸裸的强占要好得多。

中国最先保持低调的原因所在：

在欧美金融战的背后，在经济全球化的今天，欧元的成败，与中国的金融利益是相关的，中国不希望看到美元独霸世界，而是中国需要的是一个“多元化”的和谐世界，当然也包括货币。

在金融战中，更深层次的是，如果欧洲在与美国的金融战中看不到任何希望的情况下，欧洲再次出现二战后的场景是非常现实的事：欧洲向美国资本妥协，欧元象日元一样的货币功能，作为美元的辅助货币。那么，经济与军事上刚刚走向快速发展的中国，会随时在美元领导下的欧元，日元攻击下，失去成果。这不是龙之声观察员骇人听闻的增加恐怖，而是现实中的事。不然，中国副总理就不可能在拜登来华之际，去香港指导工作，周常委到中国周边去“视察”了。

中国谈联合国主导的目的：

首先是一种道义，更是一种责任，最重要的是可使中国的国家利益最大化。

在欧洲欲强行解禁被联合国封存的卡扎菲资产之际，中国提出反对，理由是，需要在联合国的监督下，这笔钱解禁后，到底去哪里，用在什么地方，一旦达到条件，“自然是”这个水到渠成，说给欧洲特别是法国听的成分比较大，因为利比亚反对派组成的过渡政府，还不值得中国这样做，它的身份还没到这种地步。

要知道，西方在金融战中，已经是伤痕累累，在使用这笔钱时，燕过拔毛，是在正常不过的了，且是必然的事。这是中国的义务，通过联合国监督这笔钱的去向。

而法国外长在法国总统体温在中国大地上还有余温之际就来中国，是要做实利比亚的利益获取，而中国在这场博弈中，能获得什么样的利益，特别是能源利益，则是下一步要谈的了，因为，只有谈了才能水到渠成。也就是，法国需要拿出诚意来与中国合作，否则，则可能是此路不通。

这是中国说给非盟听的。无论西方大唱中国是非洲的新“殖民”宿主，还是鼓吹中国的威胁主义，都离不开利益这个秤，中国提醒非洲，要想达到非洲利益的最大化，还必须做些什么，比如，在联合国上提个协议，通过中高阶层喊喊“非洲”利益，并赞同中国交由联合国主导，那么，西方为达到利益的维持，不会一下子做绝，还真得“在乎”非洲真的在想什么。

所以，越是这样达成默契，中国的工作及中国确实是在非洲争取利益的做法，就会越顺利，越有章法，越有说服力，而西方就越会“在乎”中国在说什么。

在需要中国在利比亚局势合作问题上，欧洲特别是法国，姿态还真要放低得多，因为欧洲在拿下利比亚，实施大地中海计划，特别是欧元咸鱼翻身，还有许多事要做，还有许多艰苦的事要面对，利比亚战事接近尾声，只是欧洲“万里长征”的第一步！


 *【新闻链接】* 【埃菲社伊斯坦布尔9月2日电】土耳其外交部发言人今天宣布，土耳其已经做好部署雷达系统的准备，该系统是北约导弹防御系统的组成部分。冷战以来，土耳其就对北约具有重要的地缘战略意义。中东和亚洲反西方政权的增多使土耳其的价值日益提升。

 土耳其和德黑兰之间的关系近期遭到破坏。双方在叙利亚骚乱和伊朗军备政策等方面的分歧使土耳其犹豫不决。部署雷达系统只会使形势更加紧张，因为伊朗将该系统看作威胁。

 *【新闻链接】* 【俄罗斯《消息报》9月3日报道】土耳其外交部发言人宣布，美国雷达将部署在土耳其，而不是前总统小布什所计划的捷克。预计这套机动雷达系统AN/TPY-2将安装在土耳其东南部的凡城附近，距离伊朗边界不远。

数座高山将阻断雷达的“视线”，因此无法借助雷达观测俄洲际导弹的发射。但伊朗的导弹可尽收眼底，若是向欧洲方向发射，雷达可在导弹飞行的头几秒发出预警。

但俄罗斯专家认为，这种布局可使美国有能力影响俄罗斯的南部邻国。《莫斯科防务》杂志主编米哈伊尔•巴拉巴诺夫相信，美国将借助雷达观察外高加索和中亚的空域。他说：“部署机动雷达站本身并不对俄及其核遏制构成威胁。但雷达站可提高美国对若干前苏联加盟共和国的侦察能力。”

地缘政治问题研究院院长列昂尼德•伊瓦绍夫认为，对美而言，监测伊朗并非其首要目的。他说：“美国一直不断打造自己的反导系统，就是想让俄罗斯的核潜力变得一钱不值。”

*【新闻链接】* 【俄塔社莫斯科9月2日电】俄罗斯外交部就土耳其外交部发言人今天关于土境内即将部署美国反导系统雷达站的讲话发表评论说，这种前景 “使得从美国和北约获得其欧洲反导系统不针对俄战略核力量的法律保证变得更加迫切”。

外交部要求迸一步加强俄一北约理事会框架内正在进行的对话，并以实际内容充实关于欧洲反导系统的讨论，尤其应考虑到该系统对地区和全球稳定的影响。

*【新闻链接】* 【美国《防务新闻》周刊网站9月2日报道】在土耳其表示将部署预警雷达作为北约导弹防御系统组成部分后，俄罗斯今天要求西方作出新的安全保证。

俄罗斯还证实了早些时候提出的一个要求，即“要坚决在法律上保证部署在欧洲的反导系统不针对俄罗斯的战略核部队”。

华盛顿之前说，无需作出这种书面保证，因为双方现有的核裁军协议中就包含这样的语句。尽管遭到俄罗斯的反对，北约还是决定推动欧洲导弹防御系统计划。这是对莫斯科和华盛顿在2009年 “重启”关系的主要刺激之一。俄罗斯担心，该系统会让其核部队显得多余。但北约说，该系统只能防御有朝一日像伊朗这样的国家部署的小型核武库。

*【新闻链接】* 【法新社报道】法国总统萨克奇发表声明，如果伊朗刻意发展核武器，必然会面临残酷的军事打击。

萨科齐警告伊朗：如果研制核武器将遭“军事打击”\space 巴黎消息：据法新社8月31日消息，法国总统萨科齐于当地时间31日发表讲话，成伊朗若继续尝试研发远程导弹及核武器，将遭到其它国家的“先制军事打击”。    报道援引萨科齐的话说：“伊朗在军用核能以及远程打击技术方面的野心，已经构成了一种正在成长的威胁。这可能导致其它国家率先对其发起攻击。法国将不惜一切代价阻止这样的局面出现。”

*【新闻链接】* 俄罗斯外交部：不能容忍干涉叙利亚内政。\space 据俄新网报道，俄罗斯外交部新闻司周二（30日）发布消息说，俄罗斯认为干涉叙利亚内政是不可容忍的，并呼吁叙利亚当局立即进行政治改革和经济改革。

 *【新闻链接】* 俄罗斯高官将赴叙利亚 与反对派磋商局势。据俄新网6日报道，俄罗斯联邦委员会国际事务委员会主席米哈伊尔•马尔格洛夫本月8至9日将在莫斯科与叙利亚反对派小组进行磋商。

 马尔格洛夫5日向俄新社透露：“叙利亚反对派小组请求继续6月初开始的就叙利亚局势发展交换意见的活动。”据他称，会面中将对叙利亚内部的进程予以特别关注，包括从安塔利亚会议到伊斯坦布尔会议之间反对派计划设置方面的变化。　　

 马尔格洛夫指出：“实际上，这些会议相隔时间不过1个半月，但两次会议的参加者明显不同，并且对于国家未来发展的？也不相同。

 *【时事解读】* 龙之声观察员认为，要读懂以上新闻，还真要费些功夫。但是读者如果这样去联系，土耳其与叙利亚的距离，再联系俄罗斯正在做什么，也许就明白个所以然。如果继续联系法国人威胁伊朗的用意，说辞，则会更清晰的多。

要清楚土耳其的身份。首先是世界上具有传统影响的伊斯兰国家，其次是北约国家，还有一个是“欧洲”国家，虽欧洲不喜欢它的欧洲身份，到现在还没有在欧盟扶正，还是二奶角色。而地理位置上处于欧亚大陆，处于一个关键的战略路口上，更为重要的是，土耳其一直没有忘记那个“大突厥帝国梦”，而土耳其认为机会来了。

原因一：在欧洲金融危机并不比美国差，而债务危机更进一层，欧盟国家总体水平参差不齐，心又难齐，要摆脱目前的困境，与俄罗斯的合作是必不可少的。

欧洲与俄罗斯在叙利亚问题上必然要协调立场，没有俄罗斯的首肯，欧洲想在叙利亚问题上想有所作为，那是难以想象的。观察员认为，如果欧洲达到俄罗斯的目标，使俄罗斯在叙利亚的战略利益能持久化，更扩大化，巴沙尔就是下台，也是“可接受的”，因此，俄罗斯与叙利亚反对派别磋商局势，目的就摆在桌面上，要清楚的是，俄罗斯在利比亚问题上“已经”了一次，再“将已经一次”，是有可能的，可能性有多大，就看给的价码是多大。

这个价码给的不合适，那么“不能容忍干涉叙利亚”就会立竿见影。

原因二：土耳其做为叙利亚的邻国，对一向为欧洲所不容的情势，一直耿耿于怀，如果欧洲联合俄罗斯再将叙利亚整合在欧盟框架内，土耳其在“欧洲”的伪身份，就更不值钱。为达到土耳其的国家利益，土耳其需要表达些什么，就再正常不过了。

原因三：利比亚战事在中俄的协调下，已近尾声，美阻止欧洲主导的非洲问题的顺利展开，已经迫在眉睫，更深一层的是，欧洲基本上已经掌控了黎巴嫩，一旦在叙利亚问题上再与俄罗斯联手，将叙利亚与黎巴嫩连在一起作为战略支撑，互为倚靠，全面介入中东，就为时不远了。要知道，一旦如此，在叙利亚支持下的真主党，与巴勒斯坦力量联合，美国在中东非伊斯兰世界的核心支点，就面临极大的危险。于是，土耳其与美国心有灵犀，就在所难免了。

美国在土耳其重提“反导”的目的。俄国人明白，美国人的反导是怎么回事，“威胁俄罗斯”也许是口头表达，但美国人就是明确无误的告诉俄罗斯与欧洲，此路不通。没有土耳其的配合，想整合叙利亚，对欧洲来说，是难以想象的，何况还有个随时会“改变”立场的俄罗斯！因此龙之声观察员认为，这个反对，反的不是俄罗斯，而是欧洲。

反导是军事层面的提醒，这个提醒来得很及时，美国人要欧洲明白，你那点军事实力要类型非洲的小国还可能，要糊弄其它大国，就是做梦了。

法国威胁伊朗的用意在什么地方？

法国人自我感觉良好。利比亚战事在欧洲特种部队的配合下，意想不到的顺利，让法国人有些飘飘然了，法国人认为，在顺利“拿下”利比亚之后，大地中海计划，可以再重提了。要说法国代表的欧洲，不觊觎地中海的核心国家，伊斯兰世界举足轻重的国家，中东问题解决最最关键的国家之一――――叙利亚，是不可能的。而伊朗作为叙利亚最重要的盟友，面对叙利亚目前的险恶处境，出于唇亡齿寒的道理，绝对不会无动于衷。

法国人在提醒：不要给我添乱！

欧洲与中东问题搅在一块，越乱，对美越有利。

俄罗斯所要的保障，是永远得不到的，因为欧洲的保障形同虚设，而美国人不可能在这时候给俄罗斯保障。其实，俄罗斯人明白，这个保障是得不到的，但做为战略测试，测试欧洲的态度，还是可能的。

如果俄罗斯得不到测试的欧洲回应，那么，利比亚的分配协议，就肯定难产！更谈不上欧洲要俄罗斯配合一起整合叙利亚，“共享”中东利益了了！

为了更进一步的说明，在利比亚战事结束，而利益分配还远远不能说可实行，下面我们在看下列新闻。


 *【新闻链接】* 德国前总理施罗德提议：建立“欧洲合众国” 。柏林消息：据媒体报道，德国前总理格哈德•施罗德4日说，为防止欧洲再次爆发经济危机，欧洲需要一个统一政府，建立“欧洲合众国”。

 施罗德说：“当前的危机清楚显示，一个统一货币区不能缺少统一的财政、经济和社会政策……我们应该成立一个受欧洲议会监督的政府，那意味着‘欧洲合众国’。”　德国现任总理默克尔和法国总统尼古拉•萨科齐上月会谈，提出成立欧元区经济政府、成员国实行财政平衡政策。欧元区其他国家反应冷淡，施罗德则支持这些提议。施罗德说，这是一条正确道路，是发行欧洲债券的前提，“投机者们将打消分割它(欧洲债)。

 *【新闻链接】* 欧洲央行候任行长：欧盟成员国应修改《里斯本条约》据欧洲媒体报道，欧洲中央银行候任行长马里奥•德拉吉5日在巴黎说，欧元区国家目前采取的短期措施仍不足以应对主权债务危机，欧盟成员国应修改《里斯本条约》，加强经济治理，解决危机的根源性问题。券市场)的主意”。

 *【新闻链接】* 俄罗斯外交部3日透露，俄方已向利比亚“国家过渡委员会”提出赴俄商讨能源合作事宜。据俄罗斯国际文传电讯社报道，俄罗斯外交部长拉夫罗夫当天表示，应利反对派要求，俄罗斯向“国家过渡委员会”提出派员赴俄磋商的邀请。“届时我们将讨论所有相关事项，”拉夫罗夫称，此前利比亚反对派曾向俄罗斯提出商议未来能源合作的要求。

利比亚“国家过渡委员会”对媒体表示，五家国际能源公司正在恢复在利比亚的运营。这是的黎波里为重建因为内乱和制裁而遭受重创的经济所作努力的关键一步。这五家能源公司包括意大利大型石油企业埃尼集团。

 *【时事解读】* 不久前，IMF总裁拉加德女士说过这样的话“欧洲主权债务危机和美国财政失衡是全球经济复苏面临的主要问题”。“ 拉加德建议美国当局在减少公共债务和支持复苏中找到平衡，尤其是在面临严重长期失业的情况下。她还表示，美国目前需要制止强制拍卖抵押房产，并阻止房屋价格下跌和住房支出情况恶化”。

而拉加德女士作为欧洲的代表提出“IMF呼吁银行业补充资本 遭欧洲拒绝路透法兰克福9月1日电---国际货币基金组织(IMF)呼吁银行业筹集最多2,000亿欧元(2,900亿美元)新资本,但欧洲政界人士周四予以拒绝,这加剧了有关决策者可能低估债务危机严重性的担心”。

更在之前，德国提出增加欧洲央行的权限。

结果是“欧洲政界人士周四予以拒绝”，于是出现了“欧洲央行候任行长：欧盟成员国应修改《里斯本条约》”，细心的读者会发现，欧洲主要大国在想什么，做什么，被“德国前总理施罗德提议：建立“欧洲合众国””一语道破！

欧洲看到在与美金融对峙中的劣势！如果欧洲能用一个声音说话，在与美元对抗中步调一致，何至于欧洲的金融与债务问题四面透风。欧洲主要大国需要的是代表欧洲在金融方面的决策权，至于那个“欧洲”合众国，也许只是个幌子，也许真有这个心事，那是将来，而不是现在，一个对美元资本斗争伤痕累累的欧元，已经使欧洲举步维艰了，哪来的精力与资本搞什么合众国！

目前欧洲的困境在于，东欧一把号，西欧一把号，西欧吹的调子是老欧洲的谱，而东欧吹的调子是美国人的曲！欧洲是大国一把号，小国一把号，大国吹的是集中权利，小国吹的是利益共享。英语区吹一把号，法德语区吹的是一把大号一把小号同吹，拉丁语系又吹另一把号，斯拉夫们吹的调子杂音如噪声。。。。，真为难了欧洲人。

因此，在利比亚战事未卜，俄就迫不及待的要“商讨”与利比亚的能源合作了。因此，无论是欧洲主要国家想与俄罗斯合作整合叙利亚，还是目前利比亚的利益分配，欧洲还有巨量艰苦的路要走，何况还有一个东方国家在盯着欧洲的一举一动！

【新闻链接】国务院总理温家宝与欧盟委员会主席巴罗佐通电话 。 温家宝说，世界经济正处在一个复杂、敏感、艰难的时期。各国既要实行有效的、负责任的宏观经济政策，有针对性地解决突出问题，切实把自己的事情办好；也要同舟共济，凝聚共识，加强协调合作。中国有信心、有能力保持经济平稳较快发展，为促进世界经济复苏和强劲、可持续、平衡增长作出应有贡献。   温家宝表示，欧盟经济稳定关系到世界经济稳定，欧盟经济复苏有利于世界经济复苏。欧盟陆续出台了一系列缓解债务压力、推进结构改革、改进经济治理、促进经济增长的措施，这对于稳定市场、防止形势恶化发挥了重要作用。作为欧盟的全面战略伙伴和主要贸易伙伴，中方密切关注欧洲经济形势，向欧盟及有关国家提供了真诚的支持和帮助。中方对欧洲经济和欧元始终抱有信心，将继续把欧洲作为主要投资市场之一，希望欧方确保中方对欧投资安全。    温家宝指出，不断推进中欧全面战略伙伴关系符合双方的共同利益，顺应和平、发展、合作的时代潮流。中方愿与欧方一道，增进政治互信和战略互信，把携手应对当前困难和实施各自的发展战略结合起来，坚持平等相待、互利共赢的正确道路，增强携手应对挑战的积极势头。双方要密切沟通配合，开好第十四次中欧领导人会晤，以更多的合作成果向世界传递信心和力量。
巴罗佐表示，在当前形势下，欧中作为战略伙伴，应保持密切沟通，探讨如何共同应对挑战。欧方正在采取措施，努力维护欧洲经济的稳定，有能力解决面临的困难。欧方感谢中方对欧元和欧元区经济的支持，高度重视与中方的对话与合作，认为这符合欧方的利益，对欧方至关重要，愿加强双方在贸易、投资、创新、能源、网络安全、人文等领域的合作，欢迎中方扩大对欧投资。希望双方共同努力，使第十四次欧中领导人会晤取得成功，进一步增强欧中关系的战略性，为欧中关系未来发展指明方向。

【新闻链接】温家宝与日本首相野田佳彦通电话
　2011年9月6日，国务院总理温家宝应约与日本首相野田佳彦通电话。　温家宝祝贺野田佳彦就任日本首相并表示，中日是一衣带水的邻邦，在广泛领域拥有共同利益，保持两国关系长期稳定、健康发展有利于增进两国人民的福祉，促进亚洲乃至世界的和平与繁荣。中国政府愿同日本新内阁一道，坚持中日四个政治文件的原则，保持高层交往；积极扩大各领域交流与合作，密切在地区和国际事务中的协调配合；以迎接中日邦交正常化40周年为契机，推动两国战略互惠关系取得新进展。温家宝祝愿日本地震海啸灾区的人民早日重建家园，过上安宁的生活……。

【新闻链接】李克强会见日中经济协会访华团　
　新华社北京９月６日电　（记者谭晶晶）国务院副总理李克强６日在人民大会堂会见了以张富士夫为团长、米仓弘昌为最高顾问的２０１１年度日中经济协会访华团。
　　李克强说，中国和日本都是亚洲和世界上的重要国家，双方发展长期稳定的睦邻友好合作关系，符合两国和两国人民的根本利益，也有利于亚洲乃至世界的和平、稳定与繁荣。双方应着眼大局和长远，加强对话，增进互信，深化交流与合作，推动两国战略互惠关系健康稳定发展，希望日本经济界的各位朋友为中日关系的健康稳定发展继续发挥积极作用。

【新闻链接】《纽约时报》称美国已厌烦日本频繁更换首相据共同社报道，5日的美国《纽约时报》社论指出，“美国政府已就应对日本频繁更换首相感到厌烦。”此外该报还主张，不要借本月下旬的联大会议之机举行“礼节性的”日美首脑会谈，认为“奥巴马总统应当(把日本首相)邀请到白宫举行(正式)会谈。”

【新闻链接】韩更换统一部长官 韩媒称对朝鲜政策或出现变化韩国总统李明博30日决定免去玄仁泽的统一部长官之职，提名曾任驻中国大使的前总统室室长?佑益接任。其间，朝鲜和韩国朝野一直要求韩国政府应改变对朝政策并罢免玄仁泽。韩国《朝鲜日报》对此分析称，韩国政府的对朝政策可能会出现或大或小的变化。　　
同时，李明博还将文化遗产厅厅长崔光植、国务总理室室长?采民和大国家党议员金锦来分别提名为文化体育观光部长官、保健福利部长官和女性家庭部长官。此外，企划财政部第一次官任钟龙被提名为部长级的国务总理室室长，由大国家党议员李在五担任的特任长官一职暂时空缺。玄仁泽被提名为总统统一政策特别助理
韩高官暗示对朝政策将有变 将寻找改善关系途径据韩国《朝鲜日报》报道，韩国统一部长官提名人柳佑益31日暗示称韩国对朝鲜政策会有所变化。柳佑益当天在首尔朝韩会谈本部举行的记者会上说：“对朝政策方向会一贯坚持下去。但如果有必要，会寻找能使韩朝关系取得实质性进展的途径。”
韩高官赴美商讨重启六方会谈事宜。
李明博或于11月会见俄总统 商讨输气管道项目据韩联社报道，韩国总统李明博或将于11月会见俄罗斯总统梅德韦杰夫，就韩朝俄输气管道项目进行磋商。
韩国政府消息人士1日透露，李明博正在考虑于11月在美国夏威夷举行的亚太经济合作组织(APEC)峰会期间或在法国G20(二十国集团)峰会期间会见梅德韦杰夫，李明博还考虑亲自访问俄罗斯，会见梅德韦杰夫。
韩国拟于中秋节后向朝鲜提供首批赈灾援助物资据韩联社报道，韩国政府预计在中秋节后向朝鲜提供第一批赈灾援助。韩国政府一位负责人5日表示，对朝赈灾援助准备工作正在顺利进行，预计下周中秋节后，韩国政府将首次向朝鲜提供赈灾援助。

【时事解读】巴罗佐与温总理通电话，核心还是目前的金融与债务危机。观察员认为，中国高层认识到：一个可与美国抗衡的欧洲，在目前中国实力还未达到“那个”度的情况下，与欧盟的存在某种程度的联合，在债务问题上拉欧洲一把，是符合中国利益的，而欧洲出于目前自身的金融困境，需要中国的帮助，也是一种战略需要。

在对抗美元独霸上，欧洲与中国，是有交集的，关于这个问题，在龙之声观察18期中有详细论述，这里就不在继续评论了。


观察员想强调的是，作为中国的近邻，另一个亚洲经济大国日本，近年来，在中美两个夹缝中求平衡，是受了罪的，当年，那个一味亲美的小泉，在它当政时期，在亚洲问题上的处理，可谓是度日如年来形容，以后日本每个新首相在与华关系中，还是大有感触的，虽不时的通过语言与行动方式来达到美国人的理解，但还是不敢走的太远，美不给小日本新头领脸子看，小日本具体策略上，还只是口头上，不太敢过深的配合，毕竟民族利益大于政客利益。而中国要的是日本的“行”，而不是言。

另一个亚洲宇宙大国，自然是点滴在心头！


无论是韩国的商人政府，赴美商谈，还不如说去讨主意，还有送给朝鲜月饼表示亲善，都是在这一背景下产生的。


商人政府感觉到了，在东北亚被彻底边缘化的危机。商人与其说是去与俄国磋商那个在现实中根本不成立的管道，意思是在给美国人的表演，大韩国，已经尽力了，如果美国不给更大的利益与战略支撑，我真的是支持不下去了。


而美国人是感觉到了。

【新闻链接】菲总统访问中国，所获得颇丰，签500亿大单
菲总统回应维基解密：美须改善情报部门工作质量 据新加坡《联合早报》6日报道，菲律宾总统阿基诺指出，美国必须改善其情报搜集和评估，以确保他们所获取的情报是正确的。
阿基诺是在维基解密发表的一份美国解密电报形容他“缺乏自信和不够果断”之后，做出这样的反应。
维基解密最近公布的有关美国外交电报写于2010年1月22日。当时的美国驻马尼拉大使克里斯蒂•肯尼在这份电报中形容，当时还是参议员的阿基诺是个“缺乏自信和不够果断”的人，还说他是为了传承家族的政治传统而竞选总统。
对于这份密报的内容，阿基诺表示，美国和菲律宾的关系不会因此受影响。
不过他指出，美国情报部门应改善工作质量。他说：“他们(美国)或许应该检讨本身评估和搜集必要信息的能力，以确保所获取的情报是准确的，然后才用来参照做决定。”
他也质疑在菲律宾的美国外交人员所准备的报告，是否根据最好和最完整的情报来撰写。
菲律宾叛军与政府和谈搁浅 望马来西亚介入调解据外电报道，菲律宾国内最大的反政府武装“摩洛伊斯兰解放阵线”6日表示，他们将等待马来西亚调解人的到来，以帮助减少其与菲律宾政府之间的分歧。在此之前，他们将不再与政府进行和谈。


【时事解读】美国人介入南海的意图，在中方强硬的表态、具体行动后，东盟的个别国家，感受到了，美国人介入南海的决心与“诚意”到底是个什么玩艺。
在美国人失望之余，还是有很多手段可用，于是，维基解密对象，又频频光顾东盟中的有关国家，如菲律宾。更为拙劣的是，与反对派的和谈搁浅。
这个维基解密可以说时机的把握很准，而与反对派的和谈搁浅来得太及时了。而马来西亚的介入和谈，来得也是恰巧。
观察员不想在这个地方再继续展开，不想再浪费读者们的宝贵时间与智力，但相信，已经明白观察员将这部分新闻内容罗列的用意了。
龙之声观察员想强调的是，中国已经通过钟声（中国声音）发出明确的信号，如果还有个别国家在南海问题上心存幻想，还想再测试中国维护核心利益的的决心，那就硬头来碰好了，无论是曾经自称世界军事第三的某个国家，还是自以为可依靠主子的力量达到不可告人的目的的菲国，以损害中国的核心利益，那就来好了，只要不怕头破血流。
龙之声观察员想告诉有关国家，谈比吵好，和比战好，理智比利令智昏强。
不然，500亿可不是白签订的，那是互惠的。


【新闻链接】中国外交部：中国支持巴勒斯坦建国。以19667年领土为起点，重建巴勒斯坦国。

【新闻链接】北约将与印度分享反导技术。据印度媒体昨天报道，作为“具有战略意义的一步”，北约将与印度分享其建立导弹防御系统的技术，以帮助印度获得击落敌对导弹的能力。据悉，该合作计划将由美国主导。印度也将成为继俄罗斯之后，第一个与北约在反导领域进行合作的非北约成员国家。
“你们（印度）面临导弹威胁，我们（北约）也面临着导弹威胁。我们需要防御来自敌对导弹威胁的目的是相同的。”在这篇发自北约总部所在地布鲁塞尔的报道中，一位北约高级官员说。

【新闻链接】美驻阿大使警告：彻底清剿塔利班前不能撤离阿富汗
据英国媒体9月6日报道，美国驻阿富汗大使瑞安•克罗克日前表示，美国必须继续开展针对基地及塔利班组织的反恐战，并警告说，在完全清剿塔利班之前，美军不应该提早撤离出阿富汗。这是克罗克在9•11事件十周年之际接受媒体采访时作出的表态。他说：“这一场反恐战仍未完结。我们所需要做的，便是显示出有策略的耐性，这是打赢持久战所必需的……在这个过程中，还需要更多的资源和时间，希望我们能坚持下来。”他还说，美国政府应在未来几年加大资金投入，支持并帮助阿富汗政府及其安保部队。
克罗克指出，基地以组织及塔利班成员非常顽固，因此美国要按照原定计划，全面完成在阿富汗的反恐任务，否则塔利班势必“东山再起”，连同基地组织筹谋策动新一轮的大型恐怖袭击，届时将会再次出现类似9•11袭击的局面，令美国国土安全严重受到威胁。

【时事解读】北约的反导，不如说是美国人的反导。以前，反恐，是个闯门汉，哪里有利益，就反恐到哪里，现在，反恐变成反导了。众所周知，北约当初建立的原因和组成上都是以欧美国家为主的，而当下不惜打破地缘观念拉拢印度，明眼人一看就知道其目标所指，观察员认为，这里不外两个意思：一，印度利用反导技术去防备谁？自然是巴中，而实际针对的当然主要是中国，这点伎俩和手段，用中国的古话叫“司马昭之心，路人皆知。二，看下当下北约的主要成员国，美、英，法，德等国，无论是美元还是欧元当下都深陷危机之中，各国对北约的军费支持都呈逐渐下降的趋势，很差钱，可以说北约的现状。此时此刻拉拢印度加入这个在北约内部都深受批评的烧钱项目，想来认为印度人傻钱多了。让印度人花钱，为美国的霸权出力。这事在当初打的反恐牌，谁不支持，不是被威胁包容恐怖份子就是发生恐怖事件，孰不知，很多恐怖份子都是其一手训练出来的，那么当下这招不太灵了，于是中国威胁论就大行其事了，手段上也从“反恐”，变成了“反导”。

这里龙之声观察员要指出的是，相对于印度方面而言，要知道中国的一贯外交政策是不结盟和和平外交政策，在中国的外交字眼中，更多的是和平、和谐、和睦，与邻为善、以邻为伴，这些都是中国周边外交政策的不变选择，在当下中国发表《中国的和平发展》白皮书的前提下，更不会轻易对谁去动用导弹攻击。与其辛辛苦苦的花费大价钱的去反导、为人作嫁衣裳，到头来鸡飞蛋打，当了别人的炮灰；不如把这些钱好好的解决下国内的民生问题，把虚荣的光鲜化为内在实力；伊斯兰及阿拉伯崛起的恐怖运动威胁，要远大于巴中，而以小人之心度君子之腹的事，做多了，会形成心里阴暗，成为无时无刻不在的梦魇，而把国貌变得更加“憔悴”。
