# -*- org -*-

# Time-stamp: <2011-08-14 11:40:37 Sunday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+STYLE: <link rel="stylesheet" type="text/css" href="css/org.css">

#+TITLE: 龙之声国际观察 第十六期

（2011.08.12）


<<【新闻链接】格林斯潘：美做得相当出色 无双底衰退风险 欧洲前景堪忧。>>据媒体报道，前美联储主席格林斯潘(Alan Greenspan)周日在接受NBC电台采访时表示，美国国内经济状况好于欧洲国家，并看淡美国出现双底衰退的风险。

格林斯潘在NBC电台的“与媒体会面”节目中表示，全球是否会出现双底衰退“取决于欧洲，而不是美国”。“美国实际上做得相当出色，虽然经济呈现疲软态势，但还是向前发展。”

2011年上半年美国经济波动很大，第一季度经济接近萎缩，引发市场担忧美国经济将再度陷入衰退。上周，美国政府就提高债限达成协议，7月就业数据显示新增11.7万岗位，这些利好消息令市场的担忧情绪有所缓解。但国际评级机构标准普尔在上周五宣布将美国的AAA主权信用评级下调至AA+，对美国的经济复苏进程造成打击。

格林斯潘表示，经济数据显示，美国经济正在放缓，“我不认为会陷入双底衰退，但我确实看到经济放缓迹象”。

他指出，欧洲市场占美国出口总额的1/4，并且是许多美国企业的业务所在地，因此，欧洲将决定美国经济的复苏进程。

当前，欧洲领导人正在奋力控制主权债务危机的蔓延，目前这场灾难已波及欧元区第三大经济体——意大利，并将引发全球金融市场的动荡。

格里斯潘称，意大利的危机可能将动摇欧美市场。“当意大利面临发售债券困难时，将给欧洲带来一大难题，因为是欧洲确实无力救助意大利这样的大国，这也将牵连美国经济。

他指出，尽管标普下调美国主权评级，但美国国债不像意大利国债那样，仍是一项安全的投资产品。

“这并不是信用评级问题。美国能不断地印钞票来偿还任何债务，其违约的机率为零。但是标普的下调举动确实打击了美国的自信心，并将会带来一些出乎我预料之外的更深远影响。”

美国评级被下调后，最先开市的海湾地区及以色列市场周日均出现暴跌。格林斯潘表示，周一全球股票市场可能也将步其后尘。


<<【时事解读】终于格林斯潘这个老狐狸出来说话了。>>格林斯潘在NBC电台的“与媒体会面”节目中表示，全球是否会出现双底衰退“取决于欧洲，而不是美国”。“美国实际上做得相当出色，虽然经济呈现疲软态势，但还是向前发展。”



如果我们不带有色的眼镜来看的话，格林斯潘的这个话是非常正确的。如果要求修正的话，那就是“全球是否会出现双底衰退“取决于欧洲，而不是美国””改为<<“美国是否会出现双底衰退“取决于欧洲，而不是美国””>>这样可能会更准确一点。



<<因为美元与欧元不可能共生而无矛盾的原因，特别是今天流动性泛滥而导致美元与欧元矛盾进一步激化的情况下，如果能吃掉欧元，美国就获得了巨大的战略腾挪的空间，美元危机就得以化解。美国就不可能出现双底的衰退，美国不出现双底的衰退，全球就不会出现双底的衰退，尽管有的国家会“退”的很厉害，但是全球不会。所以美元对欧元的攻击不仅仅不会减弱，相反，还会加强。直到欧元被击溃（目前不可能，不仅美国没有这个力量，其他国家也不可能让美国完成这样的战略目标），或者欧元向美元妥协，再或者，有的国家出现战略性的错误，给美国提供了更好的攻击对象。>>



一个希腊就已经让欧盟头疼不止了，让人开始担忧欧盟的主权信用问题会不会层出不穷，会不会在一次又一次的救援中耗尽欧盟的精力，分化欧盟的合力。然后就是西班牙、意大利。欧元区这样按下葫芦浮起瓢的局面是欧盟极为头疼的，如果希腊还是“小伤”，那意大利就是“大创”了。意大利的财政赤字达到国民生产总值的120%，国债高达1.8万亿欧元，是希腊之后欧元区中负债最多的国家。作为欧盟第三大经济体，意大利如果出现债务危机，欧元拯救基金将无法进行援助，因为其债务已经超出了拯救基金总数。

如果在利用利比亚问题彻底的引爆意大利，一方面“欧元拯救基金将无法进行援助”，可能导致承担着欧元拯救基金中的大部分抵押国家的德国和法国最终失去金融市场的信任；另一方面据法国政府6月公布的数据显示，法国公共债务占国内生产总值的比例已上升到85.4%，虽然低于深陷债务泥潭的希腊，但也远超出欧盟规定的60%的水平。除了自身债务水平外，法国的金融体系还可能被其他债台高筑国家的风险传染。据统计，截至2010年底，法国最大的4家银行持有葡萄牙、意大利、爱尔兰、希腊和西班牙的机构和个人债务总计近3000亿欧元。一旦这些国家经济发生重大风险，法国银行恐遭受巨额损失。通过欧债危机的一步一步发酵，慢慢的拖垮欧元，从而彻底的击溃欧元呢？


这种可能性是非常大的，但欧元不会眼睁睁的看着被美元一举击溃。欧元要反抗。<<这个反抗可以从两方面来进行。第一，迅速的解决利比亚的战事，收拢被自己敞开的门户。第二、迅速的认清形势，不要再抱有幻想，要果断的向中国妥协，让利给中国，寻求中国支持。>>


<<对于这两个方面，我们认为，第一个是想办到，实际上办不到的>>，尽管据“德国之声”网站援引《伦敦时报》8月8日透露一份利比亚反对派制定的70页战略文件称，利反对派不认为仅凭自己的力量就能将卡扎菲赶下台，而是寄希望于卡扎菲营垒中发生政变。根据该战略文件，反对派方面相信，卡扎菲现政权中约有70%的高级官员会承认新政府。反对派方面迄今已延揽了约800名现任官员，这些人将参与新安全机构的建设。利比亚的反对派近期以来示好不断，但是因为利比亚问题不是一个单纯的社会动荡或者说是仅仅是内战的问题。<<利比亚问题是世界性大变局的一个缩影，是涵盖资源产地和黄金水道上所有动乱的一个组成部分。所以只有欧元向美元妥协，或者被美元击溃，利比亚的战事才有可能平息。>>

于是，我们看到，从希腊开始，美国开始了一波又一波的进攻。而欧盟能做的就是一方面继续的顶住美元攻击的压力，继续协调各国的利益冲突，团结起来，共度难关。另一方面，就是加快利比亚的战争的进程，早点结束。可是无论是前者，还是后者，局势的变化都不能让欧盟满意。

在上个月的21日通过的对希腊实施第二轮紧急救助的方案。救助贷款额度为1090亿欧元；贷款利率约为3.5％，还款期限为15年至30年。在去年5月底，欧元区国家决定对希腊进行第一轮救助，救助金额为1100亿欧元。仅仅一年的时间，仅仅在希腊这个地方，已经吞噬了2000亿欧元。


难道，欧盟出问题的和将要出问题的仅仅是一个希腊吗？

意大利和西班牙也被人盯上了，后面还有。美元的战略是明显的，你不是要救吗？我让你慢慢得救，慢慢的拖，慢慢的耗，这样的持久战对于高福利的欧洲国家来讲，虽然见效慢，但杀伤力会非常大，美国可以用自己的美元霸权优势慢慢的耗死欧元，如果没有人插手的话。

对于欧盟来说，知道被美元击溃的灾难是什么，也知道向美元妥协的代价是什么？如果向美元妥协，那欧元得独立性就会受到影响，其信用要打折，未来有被美国收入囊中的可能。如果不向美国妥协，那就要寻求中俄的支持，来度过难过。这就是第二个方面。

<<关于第二个方面，是欧盟能做到却不想做的。>>我们认为，中欧如果能抱团取暖，欧元就不可能被击溃，中国经济也会减少不必要的波动，不仅如此，甚至还会有重创美国的可能。对于欧元来说，虽然目前的损失会大，但长远的利益会得到保证。欧元需要认清目前险恶的局势，早点决定该向谁妥协，以现在这个局面而言，当欧盟进行冒险的利比亚战争陷于胶着，欧盟就应该放弃幻想了。这就要考验欧盟的智慧和勇气，讲智慧是需要分辨合作和妥协的对象，讲勇气是说要为了大局牺牲局部的利益。

当我们把美元论述的如此强悍的时候，可能有人会觉得不舒服。美国不是一直在走下坡吗，美国的实力不是已经严重下降了吗，怎么还有这样攻击的能力呢？

是的，美国是一直在走下坡吗，美国的实力是已经严重下降了，但<<现在不是比谁更好，而是比谁更不烂>>。虽然美国的国势已经下降，但美元的霸权依然没有旁落，虽然美国的国内问题也很突出，但<<自从2008年金融危机以来，艰难的都是普通民众，获益的还是金融寡头，当世界再一次的陷入低谷，他们是有充足的现金和可以透支的信用来进行抢掠的。>>



来看看奥巴马怎么说的。



<<【新闻链接】美就信用降级回应中方关切 称美国将履行义务。>>针对中国舆论对美国主权债务信用评级遭标准普尔历史性降级的关切和批评，美国国务院发言人马克•托纳8日回应称，美国政府能够履行、也将履行自己的义务。在谈及中国持有美国国债的问题时，托纳表示，美国财政部部长盖特纳已经表示，他相信中国仍将是美国的有力投资者。

盖特纳7日在接受美国媒体采访时表示，自己不担心中国会减少美国国债的购买。 他说：“中国的经济实力非常强劲，我相信他们将来还会是美国坚定的投资者。我相信这一点。”

盖特纳表示，标普的糟糕判断显示出其对美国财政缺乏了解。他再次保证：“美国国债本周绝对和上周一样安全，标普降级没有改变一切。”

美国总统奥巴马当日也出面“信心喊话”，试图安抚投资者，他说“无论一些评级机构说什么，美国一直而且将始终是3A国家。”为了证明市场仍对美国的债务信用有信心，奥巴马还引用全球著名投资家巴菲特最近力挺美国债信时说的话：“如果有4A级，我将会把它给予美国。”

国际评级机构标准普尔5日作出决定，将美国主权债务信用评级从顶级的AAA级下调至AA＋级。这是美国历史上第一次丧失3A主权信用评级。这一事件发生后，引发中国国内对持有的美国国债可能因此“缩水”的关切。中国目前是美国国债的最大持有国。7月18日，美国财政部公布的数据显示，截至今年5月，中国持有的美国国债达1.1598万亿美元。



<<【时事解读】不管是托纳还是盖特纳，说的都是一样的话，那就是相信美国，相信美国国债。>>美国的国债可信吗？奥巴马说：“无论一些评级机构说什么，美国一直而且将始终是3A国家。”看看，美国的总统都否定了美国的评级机构，为什么其他国家遇到评级机构的指指点点就恐惧的不行呢？为什么就没有奥巴马这样的“风度”呢？比奥巴马更有“风度”的巴菲特，他说：“如果有4A级，我将会把它给予美国。”

只是，把世界拉入衰退的美国人说出如此有“风度”的话，真的让很恶心。但我们却不能因为恶心而嘲笑与轻视，在恶心的同时，我们还要保持清醒。


在7月16日的观察中我们说：关于“美元举债上限提高”的问题，在经过“痛苦”的妥协后，是能够得到解决的。<<“痛苦”的含义有两个，一是对于两党来说，必须要做出让步，这是痛苦的，二是对于世界来讲，如果美国人“痛苦”了，世界就一定要跟着“痛苦”。>>

终于在最后的时间，在“痛苦”达到高潮时，两党向对方妥协了，虽然这种“痛苦”有太多作秀的成分，但是，对于世界人民来说，美国人“痛苦”了，世界一定要跟着“痛苦”的“痛苦”才是真正的“痛苦”。

从两党关于美债上限的分歧开始，世界就跟着痛苦了，而在国际评级机构标准普尔决定，将美国主权债务信用评级从顶级的AAA级下调至AA＋级。痛苦开始扩大蔓延，并且在“七伤拳”作用的放大下，重创了世界的资本市场，引发了众多国家对未来局势的担心。

针对全球金融市场当天出现的剧烈动荡，阿根廷总统克里斯蒂娜4日呼吁拉美国家做好充分准备，防止发达国家将金融危机的严重后果转嫁给包括拉美地区在内的新兴市场国家。克里斯蒂娜当天在出席阿根廷冶金业大会时发表讲话说，全球股市当天的大幅下跌给南美国家敲响了警钟，警惕发达国家将金融危机的后果转嫁给其他国家。

墨西哥财政和公共信贷部长埃内斯托.科尔德罗9日表示，尽管全球金融市场8日经历了2008年以来的“最糟一天”，但墨西哥国内各项宏观经济指标平稳，墨有能力抵御此次美债危机的影响。由于担心美债危机会对过分依赖美国的墨西哥经济造成严重影响，墨西哥股市投资者信心在标普下调美国主权信用评级之前就已出现动摇。墨西哥股市IPC指数自7月29日起即显露颓势，从35999.34点一路跌至8月8日的31715.78点，累计跌幅达11.9%。单是8日一天，IPC指数就大跌5.88%，创下了2008年以来墨西哥股市单日最大跌幅。

巴西总统罗塞夫8日在首都巴西利亚表示，巴西经济是强大的，拥有稳固的银行系统、庞大的国内市场和充沛的银行储备，因此巴西不惧怕可能出现的新的国际金融危机。 罗塞夫是针对当天巴西股市出现暴跌讲这番话的。在国际评级机构标准普尔公司5日下调美国主权信用评级后的第一个交易日里，圣保罗股市收盘时大幅下挫8.08%，主要股指博维斯帕指数跌破50000点关口，并创2008年11月以来单日行情下跌最惨纪录。罗塞夫还呼吁美国和欧洲国家采取必要措施以避免自身危机继续恶化。她说：“不应把自己不明智的国内政策化为全球灾难。为此，世界各国都应要求美国和欧洲将其增长与投资纳入正确轨道。”

欧洲的资本市场也好不到哪去了，一样随美国的资本市场凌乱的飞舞。

国务院总理温家宝9日主持召开国务院常务会议，分析当前国际金融形势及其影响，研究制定应对措施。会议指出，当前国际金融市场出现急剧动荡，世界经济复苏的不确定性、不稳定性上升。我们要冷静观察，沉着应对，做好防范风险的准备。会议强调，中方支持有关各方为金融稳定和经济增长所做的努力，支持20国集团财长和央行行长关于稳定金融市场的声明，要求有关各国切实采取负责任的财政、货币政策，减少财政赤字，妥善处理债务问题，保持市场投资安全和稳定运行，维护全球投资者信心。国际社会要加强宏观经济政策沟通协调，推动实现世界经济强劲、可持续、平衡增长。

这些国家无论是信心的经济体还是老牌的资本主义国家，都不约而同的发出同样的声音，仅仅是担心经济的周期性波动带来资本市场的紊乱从而引发国内的矛盾的迅速爆发吗？龙之声观察员认为，有这样的考虑，但我们认为他们所担心的还是美国的“七伤拳”变成“化功大法”


当“七伤拳”变成“化功大法”

在金融洪水猛兽的冲击下，如果老牌的资本主义国家都难以自保，如果相对大的新兴经济体也勉强应对，那无数小国的命运就堪忧了。当出现世界性的恐慌和衰退，在被打击的伤痕累累的欧元之后，在人民币没必要走向国际化的时刻，依然拥有霸权的美元还是有足够吸引力的。如果能驱动资本向美国回流，在这个过程中巧妙的定向的杀戮“非美资本”，那就完成了 “七伤拳”变成“化功大法”的“乾坤大挪移”。<<这就是奥巴马和巴菲特“3A”“4A”的信心所在。>>

显中国功夫，中国财政部将于本月中旬在香港正式发行200亿元人民币国债。此举一出，即引发世界的关注，在此敏感的时刻，人民币大胆走出国际化过程中举足轻重的一步，正确的时机做正确的事情，在此美欧债务危机的阴霾下，国际金融机构投资者的资金配置必然要发生变化，人民币国债自然具有巨大的诱惑力和杀伤力，如果当国际投资者逐渐学会并习惯将人民币资产放入投资仓将有助于加快人民币国际化的步伐。这虽然是一个长期的过程，但相信在美元价值不断被稀释和美元霸权受到世界广泛置疑的背景下，推进人民币国际化进程，提高人民币的国际地位，对于中国实现外汇储备资产保值增值、规避潜在的汇率波动风险无疑具有重要意义。

单方的努力只是一个层面，观察员认为要阻击“化功大法”的形成，仍需要全球“非美势力”的努力。从大国的角度来说，需要中欧的合作和中俄的配合。从金融来说，需要加强<<安全的意识>>和<<抗风险的能力>>。从地域来说，关键的地方要截击，配合美国跳的欢的国家要教训。


<<【新闻链接】美军最精锐的“海豹”特种部队直升机遭袭击>>  当场死亡31人多家英美媒体经由情报消息源获知，机上总计38名死亡者中，包括20多名美国海军海豹突击队第六分队特种兵。今年5月，正是这一美军最精锐特种部队在巴基斯坦突袭、捕获并击毙“基地”组织头目乌萨马•本•拉丹。


<<【新闻链接】北约16辆油罐车在巴基斯坦遭炸弹袭击被焚毁>>  据媒体报道，8月6日，16辆为驻阿富汗美军提供燃料的北约运油车在巴基斯坦西北部开伯尔－普赫图赫瓦省遭炸弹袭击，起火并被烧毁。由于政治与经济上的便利，美国以及北约军队非常依赖巴基斯坦至阿富汗的供给通道。近几月，塔利班组织则增加了针对该通道的袭击，已有数百辆北约运输车辆被袭击。


<<【新闻链接】韩媒：朝军向延坪岛附近海域开炮  不清楚炮弹是否落入韩国水域>>  据韩联社报道，韩国军方相关负责人10日表示，朝鲜10日向延坪岛附近海域开炮，韩军对此进行了应对射击。该名韩军负责人说听到三声炮响，并推测其中一发落在北方界线(NLL)附近，因此进行了应对射击。另据报道，韩国方面称：不清楚炮弹是否落入韩国水域。


<<【新闻链接】韩美16日联合军演针对朝鲜  韩三军总参谋长参加>> 据韩国《中央日报》网站8日报道，据韩国政府消息灵通人士称，韩美两国在本月16~26日举行的乙支自由卫士(UFG)联合军演时，将编制应对核武器、导弹等大规模杀伤性武器(WMD)的联合机动部队，进行用以探测、消除、解散和移动朝鲜WMD的演习。

据悉，韩美两国军队在电脑上进行的UFG模拟演习中，美军方面将有包括3000名海外增援等共计2.2万余人参加，韩国方面将有作战司令部级以上的20余万名军人参加。

据介绍，“联合机动部队(JTF-E：Joint Task Force-Elimination)将以美国陆军第20支援司令部为主，韩方则将有国军生化房防护司令部350余名要员等参演”，“演习由找出核武器、导弹以及生化武器等朝鲜WMD的隐藏地区和对WMD进行消除、破坏、解散、移动等方式进行”。

报道指，韩美两国军队从2009年开始就开始举行针对与朝鲜WMD相关的联合军演，并在每年春季举行的关键决断(Key Resolve)军演时动用兵力和装备进行实战演习。


<<【新闻链接】朝鲜说韩方所称延坪岛炮声来自朝鲜民间建设爆破>> 据朝中社11日报道，朝鲜北南军事工作会谈北方团长10日在就韩方称朝鲜军队在延坪岛附近海上进行炮击一事答朝中社记者问时表示，朝鲜当天在邻近“西海5岛”的黄海南道一带为建设大型人民生活设施而进行正常爆破作业，但韩方却将其说成是朝鲜军队进行炮击，捏造事实，并企图借此进行军事对应行动。


<<【时事解读】美国要想完成“化功大法”，需要的是美元的霸权，而美元的霸权离不开美国军事的霸权，如果美国没有分布全球的军事基地，如果没有没有庞大的海外驻军，如果没有先进的军事装备。美元的霸权也不可能在美国走下坡路的时候，还能继续的维持。所以保持强大的军事力量对于美国来说是不可或缺的，因此尽管美国的军费已经惊人，但要让美国消减军费支出，那无异于与虎谋皮。>>

虽然不能通过消减美国军费来弱化美元霸权，但是选择关键的节点打击美国军事的信心和阻碍美国的军事行动却是完全可能的。所以我们看到了美军最精锐的“海豹”特种部队队员的死亡，这种心理的打击其震慑意义非常巨大，如果美国坚持的要把“化功大法”进行到底，那么类似在阿富汗的美军直升机坠毁的“事故”会越来越多。

如果说在阿富汗的直升机被击落是依靠把美军 “留下来”，那在巴基斯坦此起彼伏的油罐车被袭击就要把美军“赶出去”，无论是“留下来”还是“赶出去”，都是的美军的打击，造成的效果就是想走，走不掉，想留，留不下。最终造成的作用就是<<消磨美军的力量，给美元“放血”>>。

至于不自量力的“宇宙大国”韩国，一直以来小动作不断。如果一直阅读龙之声国际观察的朋友，一定不会惊讶。因为，我们一直都在强调的一个问题就是：<<在金融危机在进一步的深化和国际局势剧烈变动中“韩国躲在中国的身后躲避金融危机的猎杀，如果韩国策应中国，这躲的就无可厚非，但是韩国经常性地搞这样那样的小动作，除了能展示‘宇宙大国’无聊之外，还能让人感觉到‘恶心’与无耻。>>这种成心的挑衅会不会成为‘狼来了’的谶语，奉劝李明博政府，要好好的领会”，可是让人失望的是，李明博政府并没有领会到，尽管其后，朝鲜给了许多提醒，但是李明博政府依然充满侥幸地像新加坡那个李光耀一样，<<一方面从中国获得经济利益，一方面希望美国来制衡中国。>>这样的“好事”似乎已经被韩国新加坡这样的国家视为必然了，一个仰中美鼻息的小国，在世界局势剧烈变化的今天，竟然觉得已经牢牢的“吃定”了中国，真是让人跌破眼镜。

面对李明博的不识时务，中国能做的就是治病救人，要治治李明博的“病”。被延坪岛的炮声吓破了胆的李明博，再次听到延坪岛方向的炮声时，已经成了惊弓之鸟。竟然连“不清楚炮弹是否落入韩国水域” 就紧张的进行了“应对射击”。而朝鲜说韩方所称延坪岛炮声来自朝鲜民间建设爆破，这给紧张的李明博增添饿不少滑稽的色彩。

从李明博执政以来，李明博着眼的就是利用美国来压制中国，从压制中获得中国的利益，抛弃了上届卢武铉政府的“阳光政策”，故意恶化朝韩关系。站在朝鲜民族的利益上说，李明博就是不折不扣的历史罪人，因为经历了分裂的朝鲜半岛，在卢武铉的努力下，出现了融合的可能，可是，依附于美国的李明博，无视这种可能，不仅不去推动，而且还想尽办法破坏。


在龙之声观察第七期我们这样给过分析：“龙之声观察员在这里想强调的是，中国要给韩国一个彻底的教训，要对美国这个所谓的“盟友”（其实可以出卖）实际上是“殖民地”进行一个系统的打击。那就是在半岛统一的问题上，给朝鲜更多的支持。一方面督促朝鲜进行对外开放，加强中国和朝鲜的经济联系，另一方面彻底打破韩国以韩国为主导的统一梦。”

今天，龙之声观察员再给“大韩民国”商人出身的总统先生提个醒，如果从商人角度，唯利是图无可厚非，但如果是个政治家，低层次的说是个政客，特别是面对整个国家利益与民族利益时，唯利是图就是致命伤。这就是政治军事的残酷性。

韩国不停的军演，我们不想知道李明博到底想干什么，我们想知道的是你李明博能干什么？不知道自己的实力与面临的极其危险艰苦的前景。盲人骑瞎马一般的乱撞，不仅有头破血流的危险，还有万劫不复的可能。我们建议李大总统，要保持一定的清醒与低调，在半岛上，千万不要轻易听“别人”的空口许诺引诱而冒险。因为，格鲁基亚的殷鉴不远。

下边让我们在最后，把目光转向印日，在上期观察中，我们剖析了日本的恐惧和投机心里，本期的最后，将再次列举几条新闻，让大家更清楚的看到被美国人所看重的印日两家的奥妙心里变化

<<【新闻链接】《印度时报》：中国对日本施压并向朝鲜派遣海军>>  北京：中国向其邻国朝鲜派遣海军舰艇编队已对日本造成巨大压力。而且还控诉日本发表关于北京方面军事威胁的错误言论。该舰艇编队包括一艘导弹护卫舰“洛阳号”和一艘训练舰。“洛阳号”该舰已于周四抵达朝鲜元山市。东京方面对中朝双方密切的军事关系已担忧已久。

此次军事行动是在日本方面对中国海军在其海域活动频繁增加提出警告（可能造成威胁）后进行的。两国在中国东海部分海域的归属权问题上已发生争端。

对于日益嚣张的中国，东京方面发表了一份关于中国军事威胁论的（防卫）白皮书。东京方面甚为担心因为中国的第一艘航母已近完工下水，该航母的活动海域可能极为靠近日本。（防卫）白皮书写道中国的国防预算比起5年前已飙升近70%，然而日方在此期间却将军事支出削减近3%。（防卫）白皮书提出警告源于中国外交部发言人马朝旭称日本不应该背离其长期的防卫姿态。他还指出北京方面仍对日本在二战前后军事侵占中国的行为感到痛心。“我们希望日本方面以史为鉴，认真反省其国防政策，多做有利于加强与邻国增强信任的事。”马朝旭表示。国防部的官网还批评了日本（防卫）白皮书中不负责任的评论。


【新闻链接】据印度《印度时报》8月12日报道，印度国家安全顾问梅农11日就中印关系表示，印度媒体和时事评论员在谈及中印关系时要“学会温和的品质”。梅农强调，有必要确保中印两国不会对彼此产生误解。

报道称，梅农称，中国不会相信印度媒体和评论员未使用命令式的报道来谈论中国。他称：“我们必须承认其他一些国家出于自己的理由会也像我们这样做。但我们为什么要同像中国这样强大的邻国制造自我预言式的冲突呢？”


【新闻链接】日拟将2011年度经济增长率预期下调至0.5% 日本共同社8月11日消息，日本政府11日初步决定，将把2011年度的实际经济增长率预期从原先的1.5%下调至0.5%。

受东日本大地震导致零部件供应链断裂等因素影响，生产和消费一度严重受挫，日本政府认为大幅下调经济增长预期在所难免。


【新闻链接】日本右翼媒体《产经新闻》8月12日报道称，15日即将迎来“终战纪念日”，但在12日上午的记者会上，菅直人内阁成员中没有一人表露出参拜靖国神社的意向。

报道对菅直人内阁表示“不满”和“惋惜”，称菅直人在上任之初就表明“不会参拜靖国神社”。在2010年8月15日当天，菅内阁中“竟无一人”前往靖国神社，在即将到来的2011年“终战纪念日”预计也不会有官员参拜。


【时事解读】在前期的龙之声观察中，观察员曾建议：对于日本，我们的建议是：如果日本真的心存幻想，以为配合美国人对中国金融攻击或者其他方式的攻击的话，我们要早作准备，发现苗头后，什么一衣带水，什么邻邦，中国都要抛到脑后，直击日本的命门，只要他敢于冒险，不仅仅是美国人可以给他套绳子，中国更有理由可以做，中国更有能力做。也许我们的决心可彻底打消日本人的投机心理，我们的实力方可断送日本人的冒险心理。

本期最后，龙之声观察员认为有必要再次重复以上建议，与印度方面的两边做戏不同，当下可以看到，当下之日本的政局再临动荡，右翼势力显化膨胀之际，在中国航母已经海试的时期，被投机和恐惧所左右的日本当局，是很有可能做出对东亚稳定不利的不智之举的。

不过“天要下雨，娘要嫁人”，我们相信该来的早晚会来，既然日本方面有心玩，不妨就大胆的动手好了，中国方面在崛起的路上正实际需要一块垫脚石，民心可为，民意可用，如果日本方面再次做出不利中国的举动和挑衅的话，我们有理由相信那么再临失去的十年，或是更加长远的失去，都是一种大势所趋的必然，地缘争斗中，实力永远是占有绝对的主导权的，冲动之下的冒险必然招来更加危险的后果。另外可以看到当下的日方所谓《白皮书》的发表已经实际引起了日韩双方的争斗越演越烈，说明利益之下，一切对抗结盟都不过是虚幻的存在，挑动周边的动荡和政治上的短视，只会是“福祸无门、惟人自召，善恶之报，如影随形”。

