# -*- org -*-

# Time-stamp: <2011-08-19 20:20:37 Friday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 让美欧的金融斗争进行到底

[2011-07-09 20:06:20]

美欧的交手日益白热化，后面的问题会出现哪些变化呢。

1、美元全胜，欧元崩溃。这好像不可能，中国果断的出手，挺欧元，就是保持起码的平衡。这种平衡，可能是表面的或者暂时的，但因中美在时间上要求的趋同而导致的妥协是必要的。

简言之，就是美元一定要打击欧元，中国也一定会救，但美元也一定能达到打击的预期目标。当然这个预期目标，美国人也知道，不是欧元崩溃，而是尽可能的弱势。没有相对于弱势的欧元，美元就没有起码的转圜空间了，所以攻击欧元是美元所必须。但欧元也不会因这轮的攻击而崩溃，至少这一轮不会。

中国挺欧元，并不是去做无意义的撒钱，而是尽可能的调动美欧互博，为将来美欧因互斗导致各自有求于中国而向中国妥协打下基础。中国是不可能眼看欧元被攻击至崩溃而无动于衷，所以，美元全胜，欧元崩溃目前这是不可能的。

2、美元攻击失败，欧元突围成功。这也是不可能。以美元百足之虫死而不僵的实力与欧元与生俱来的缺点。美元的攻击不可能没有效果，只是效果多少而已。同样，欧元也不可能取代突围成功，一个希腊就已经让欧元头疼万分，后面还有更大的考验。欧元要做好准备，未来的困难要远胜今日。

3、既然不分胜负，那就是一个僵持的局面，这样僵持的局面，是中国所最希望看到的。从世界的货币来看，日元已经随着日本的快速衰落已经彻底的失去了与美元欧元三足鼎立的可能（当然就是没有日本的衰落，美国也不会让日元出头），唯有人民币才是最具竞争力的货币。那么人民币怎么样走向世界，这是中国着力要解决的问题。人民币走向世界最为可靠的保证就是中国强大的经济和遍布世界的毛细血管。没有这个保证，强行的启动，只能给对手留下攻击的命门。所以，人民币走向世界是一个细致的靠实力说话的活。

鉴于此，<<中国需要的还是时间，需要时间来让美元与欧元的信誉在金融危机的冲击下扫地，需要时间让美元与欧元在为了各自存活的斗争中消耗。所以能合理的挑动与支持美元与欧元的斗法，这就是目前中国所要干的事情。>>

下面我们在观察几个有意思的问题。

大家有没有注意到最近欧盟包括英国对中国的态度比以前好多了。以前的欧盟可不是这样的，总是利用车轮战法来刺激中国，现在开始用车轮战法抚慰中国了。美国也是这样，像基辛格这样的老家伙竟然不断的提示中美的战略利益了。面对中国在南海的用强，美国保持了相当的冷静，这在以前也是相当难得的。

如果而我们能够<<在美元与欧元这样的僵持中，逐渐的完成东南亚和东北亚的整合>>，那人民币想不成为国际硬通货都难。当然，这只是我们的预期，不可能就这样顺利的实现。中国要面临的就是做好与欧的沟通，和保持欧元相对的弱势，因为一旦欧盟占了上风，并不会比美国更好对付。同时也要做好对美国的斗争，没有斗争，就没有尊重，<<信奉实力的美国人，只有看到你的斗争的实力多寡，才会想起妥协的多少>>。


#+begin_center
2011-07-06
#+end_center
