# -*- org -*-

# Time-stamp: <2011-08-19 20:55:34 Friday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 挪威爆炸枪击背后的博弈

[2011-07-23 18:32:58]

一、相关新闻

中新网7月23日，据外电报道，挪威警方发言人23日称，发生在首都奥斯陆的两起爆炸和枪击事件已经造成至少87人死亡。针对乌托亚青年夏令营枪击事件，挪威警方发言人称：“我们已经证实至少有80人死亡。我们不排除死亡人数仍将上升。”该发言人暂时无法给出夏令营枪击案中有多少人受伤。而在之前发生于奥斯陆市中心的爆炸事件还造成另外7人死亡。

事发后，警方已经逮捕了一名与该国右翼极端组织有联系的男子，目前正在对该男子在奥斯陆西部居住的一套公寓进行搜查。有媒体援引挪威警方消息人士的话称，这名被捕的男子今年32岁，这两起袭击事件可能都是其一人所为，而且“(此次袭击事件)看起来与国际恐怖组织毫无联系”。“袭击事件好像与伊斯兰恐怖活动没有联系，看起来更像是一个疯狂男子的所作所为。”

二、挪威为什么急忙的和外国恐怖组织撇清关系？

面对这么大的伤亡，事件还没有调查清楚。可是警方消息人士就这样说了，“(此次袭击事件)看起来与国际恐怖组织毫无联系”。“袭击事件好像与伊斯兰恐怖活动没有联系，看起来更像是一个疯狂男子的所作所为。”

有关系也好，没有关系也好，惨案刚刚发生，取证还没有完毕，就如此急忙的要和外国恐怖组织撇清关系，是为了什么？是想控制影响的范围，还是想隐藏什么？

我们知道就在本月的13日，印度孟买再遭恐怖袭击一日连发3起爆炸。至少造成17人死亡、81人受伤。

5天后，中国新疆的和田，也出现了恐怖袭击事件。7月18日中午12时10分左右，新疆和田市纳尔巴格街道派出所遭一群打着圣战标语，手持砍刀、斧头、燃烧瓶等凶器的宗教极端分子袭击。造成1名武警战士、1名协警牺牲，2名群众被害。事发后，公安、武警迅速赶赴现场，当场击毙14名、击伤1名正在行凶和负隅顽抗的暴徒，成功解救6名人质。

而在昨天，欧洲出现了更为恶劣的恐怖事件，已经导致87人死亡，也许随时间的推移，死亡的人数还会上升。联系印度孟买的爆炸案，中国和田的恐怖事件，短短的10天之内，在世界局势处于微妙时期的关键节点上，出现如此密集的恐怖事件，难道都是巧合不成？

对于微妙时期的关键节点上出现的影响巨大的恶性事件，如果仅仅就事论事，我们可能看不到背后掩藏的本质，要弄明白是怎么回事，必须放到复杂而诡异的国际局势中来解读，下面我们通过这些事件，来分析一下背后大国博弈的惨烈。

三、美欧不可调和的矛盾

自从欧元诞生那天开始，美欧的矛盾就不是内部矛盾可以说清楚的。1999年欧元诞生，就注定了美国与欧洲将来必然出现分道扬镳的局面，而欧元诞生后的南斯拉夫战争虽然将欧元打击的奄奄一息，可并没有把欧元斩尽杀绝，随后的美国过分的高估了自己的实力。发动了两次海湾战争，又跳进了“帝国的坟墓”——阿富汗。在对外的战争胜而不利的情况下，2008年，美国的金融危机爆发，<<金融危机的爆发使美国失去了无限造血的功能>>，不得不启动一轮又一轮的“量化宽松”，用这个杀人不见血的动听的名词洗劫世界。

在人民币没有国际化，美元因为美国金融危机的问题而走弱的情况下，打击另一个世界通货——欧元是挽救美元的最便捷的方式。因此，<<打击欧元就是维护美国经济所必须>>。

欧盟在2011年做了一件关乎欧盟命运前途的大事，那就是法国开打利比亚。对于利比亚战争，欧盟就在进行冒险，这种冒险是<<地中海计划>>召唤的野心所致，同时也是看到美元和欧元必将在“虚拟经济”走下坡后，通过超发货币掠夺世界的过程中面临殊死的搏斗的提前准备。

我以前提过一个观点，就是在这场世界大变革中只能是“<<剩者为王>>”，这是说明了斗争的惨烈。欧盟处于这样的不妙的远景，选择了冒险，<<通过对利比亚的战争，来完成地中海的计划，获得北非的资源，为将来击溃美国的进攻积蓄力量。>>这是欧盟的算盘，但是这个举动是要冒巨大的风险的，那就是如果利比亚的战争旷日持久，久攻不下或者利比亚国内一直都不能稳定。简言之就是利比亚不能提供将来欧盟所想要的资源和缓冲。相反，利比亚一直处于混乱，而且越来越乱的情况下，那靠近利比亚的欧盟的地缘优势可能立即就变成劣势。就是说<<利比亚不仅仅没有成为欧盟的盾，却成了美国攻击的矛>>，那欧盟的处境就会非常的不妙。

还有就是在利比亚战争持续进行的过程中，美元提前发动对欧元的进攻，那欧盟将腹背受敌。事实上，局势就是这样发展的，在欧盟进行对利比亚的战争之后，美国不可能看着欧盟的地中海计划的成形而无动于衷，也不可能放过这个极好的进攻机会而贻误战机。所以，在利比亚战争中，积极的欧盟和消极的美国形成了巨大的反差。在欧盟对利比亚的进攻中，美元吹响了进攻欧元的号角。<<最好的攻击对象就是希腊，进攻的子弹就是“穆迪”等美国的几个评级的公司。>>不断的调低欧盟国家的债务评级，来引爆欧元区的危机。特别是对希腊，对这个本身问题比较多的国家发起了最凶猛的进攻，<<企图通过对希腊这个点的攻击，拉整个欧元区下水，击溃欧元>>。

<<美国的目的非常简单，要么击溃欧元，消除欧元在美元走弱后对美元的威胁；要么就是欧盟在美国的打击下告饶，选择妥协，来配合美国对中国的金融攻击。>>因为对于美国来说，要想彻底的摆脱金融危机的不良影响，只能在欧元与中国身上打主意。要么在能保证美元不崩溃的情况下再超发天量的货币，要么就是通过金融战争或者其他战争的途径掠夺。如果能够解决美元再天量发行不崩溃，那更好，可惜根本就做不到。如果不行，如果欧盟能配合美国对中国进行金融掠夺，也是不错的选项。

四、美元与欧元斗法的可能结果

对于美元与欧元的较量，可以尝试的这样分析。

1、美元全胜，欧元崩溃。这种情况是美国最想，但却不可能实现。不要说欧元会殊死的抵抗，就是中国也不可能眼看欧元被攻击至崩溃而无动于衷。中国会果断的出手，来挺欧元，保持起码的平衡。这种平衡，可能是表面的或者暂时的，但因中美在时间上要求的趋同而导致的妥协是必要的。

虽然中国挺欧元，但美元也一定能达到打击的预期目标。因为，欧盟选择了对利比亚动手，就留下了空挡，也就选择了被美元攻击的现实。当然这个预期目标，美国人也知道，不是欧元崩溃，而是欧元尽可能的弱势。没有相对于弱势的欧元，美元就没有起码的转圜空间了，所以攻击欧元是美元所必须，而在攻击后，美元走强也是应有之义。但欧元也不会因目前的攻击而崩溃，至少这一轮不会。

中国挺欧元，并不是去做无意义的撒钱，而是尽可能的调动美欧互博，为将来美欧因互斗导致各自有求于中国而向中国妥协做点准备。所以，美元全胜，欧元崩溃目前这是不可能的。

2、美元攻击失败，欧元突围成功。这也是不可能。以美元百足之虫死而不僵的实力与欧元与生俱来的缺点。美元的攻击不可能没有效果，只是效果多少而已。同样，欧元也不可能取得突围成功，一个希腊就已经让欧元头疼万分，后面还有更大的考验。欧元要做好准备，未来的困难要远胜今日。

3、既然这样，那就是一个僵持的局面。这样僵持的局面，是中国所最希望看到的。从世界的货币来看，日元已经随着日本的快速衰落已经彻底的失去了与美元欧元三足鼎立的可能（当然就是没有日本的衰落，美国也不会让日元出头），唯有人民币才是最具竞争力的货币。那么<<人民币怎么样走向世界>>，这是中国着力要解决的问题。人民币走向世界最为可靠的保证就是中国强大的经济和遍布世界的毛细血管。没有这个保证，强行的启动，只能给对手留下攻击的命门。所以，人民币走向世界是一个细致的靠实力说话的活。

鉴于此，中国需要的还是时间，需要时间来让美元与欧元的信誉在金融危机的冲击下扫地，需要时间让美元与欧元在为了各自存活的斗争中消耗。所以能合理的挑动与支持美元与欧元的斗法，这就是目前中国所要干的事情。也就是说美元与欧元的殊死较量对于中国是有利的。

五、另一种攻击

美元与欧元斗争的僵持不可能成为常态，僵持注定要被打破。当利比亚的反对派继续的猛进，当中国的领导人走马灯的在欧洲访问，当中国决定的采取扶助欧元的政策，美国意识到马上就击溃欧元是不可能的，美国想到了击溃欧元之外的另一条路，那就是对中国的金融掠夺。方式有两种，<<一个是通过外部的战争，来打断中国的发展，达到金融攻击的目的；另一种就是制造中国的内乱，来破坏中国的发展。>>

对于外部的战争，那就是通过刺激印度，挑起印巴关于克什米尔的战争，然后将中国拖到到战争之中。对于中国的内乱，疆独藏独就“是好棋子”。

孟买爆炸案发生后，印度总理发表声明：要求士兵冷静团结。这个态度是值得肯定和表扬的。“冷静”就是不要跟随相关势力而舞，做出有损于印度国家利益的事。因为克什米尔这颗随时可能引爆的炸弹，必须要冷静的克制才能保证不爆。

当印度的冷静被欧盟清清楚楚的看到，欧盟不仅看到了印度的冷静，也看到了向美元妥协来配合美国对中国攻击方案的不可行。欧盟想到的还是如何加快利比亚的战争，如何协调各国关系，全力救助希腊。

既然外部战争不可为，那另一种尝试就出现了。达赖走上前台，开始了傀儡的表演，几天后中国新疆和田发生了恐怖袭击事件。但是让策划者始料不及的是，藏独和疆独的共同“表演”并没有引起欧盟的兴趣，对藏独和疆独一直都抱有极大兴趣的欧盟这次却出奇的安静。无论是妥协的条件也好，还是默契的召唤也好，欧盟都表现出了“聋哑人”的特征。当然让欧盟变成“聋哑人”的除了自己泥菩萨过河的原因，还有就是疆独藏独策划者的无能与中国行动迅速的霹雳手段。

六、挪威爆炸枪击案，目的何在？

<<欧盟“安安静静”的干什么呢？>>欧盟“安安静静”的干了两件事：一是调整了对利比亚的政策。法国外交部长阿兰·朱佩(AlainJuppe)20日称，卡扎菲如果弃权，仍可以留在利比亚。在利比亚反对派猛烈的进攻下，在北约对利比亚的轰炸下，欧盟提出了的不是更严厉条件，而是放宽了对卡扎菲的要求，这必然有利于快速的解决利比亚的题。

二是法德领导人经过长达7个小时的磋商，对希腊第二轮援助方案达成共识。然后欧元区17国领导人21日在布鲁塞尔就欧元区债务危机问题举行特别峰会，最终通过了对希腊实施第二轮紧急救助的方案。再然后，也就是第二天，挪威大楼爆炸，出现枪击，死亡惨重。

到底是谁下的黑手？据美国《纽约时报》报道，一个名为“全球伊斯兰圣战助手”的恐怖组织宣称对奥斯陆22日爆炸负责。该组织称，袭击是对挪威在阿富汗驻军以及侮辱先知默罕默德作出的反应。该组织还威胁将发动更多袭击。不过这一说法无法得到证实。

我们知道挪威是北约成员，在阿富汗有500名挪威士兵参加反恐战争。但这能成为这个名不见经传“全球伊斯兰圣战助手”的恐怖组织发动这样震惊世界的恐怖袭击的理由吗？美国已经开始从阿富汗撤军，挪威的撤军也是迟早的事。况且就是出于愤怒，发泄的对象竟然是无足轻重的挪威，而不是不是美法英德这样的“大”国。

其实明眼人都知道，<<原因不在阿富汗，而是在利比亚，>>我们知道。挪威也参与了在利比亚的战争，挪威曾派出了6架F16战斗机参与对卡扎菲政权的袭击。不过挪威政府在上月底曾表态，挪威的战机将从8月份开始撤出在利比亚的军事行动。挪威国防部10日在一份声明中说，打算从8月1日起撤出北约对利比亚军事行动。在此之前，北约本月1日决定延长对利比亚军事行动90天。也就是说，军事行动定于9月底前结束。

我们把相关的事件串联起来，就看到挪威爆炸枪击案，是有人对<<利比亚战争的变化>>感到焦虑了，对中国攻击的行动无人响应，对欧元区推出的第二轮<<对希腊的援助方案>>感到极为不满。<<为阻止利比亚战争脱离自己的方案运行，促使像挪威这样的国家脱离利比亚战争，为瓦解欧盟的团结，把动荡引入到欧盟的内部，为进一步的弱势欧元做准备>>。

挪威爆炸枪击案，死难的是挪威的百姓，被警告的却不是挪威，而是欧盟！

#+begin_center
会同天下2011-7-23
#+end_center

