# -*- org -*-

# Time-stamp: <2011-08-19 21:24:42 Friday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 机不可失 失不再来

[2011-08-07 21:57:31]

自从欧盟决定进行利比亚战争开始，欧盟就在进行一项关乎前途命运的<<赌博>>，赌注就是欧元。

一、欧盟在利比亚战争爆发前所面临的选择


<<欧盟当时面临的就只有两条路>>，是放弃欧元还是坚持下去。放弃欧元，就是完全的听命于美国，反之，在世界经济水平进一步下滑的情况下，那就是和美元撕破脸。

如果要是放弃欧元，那欧元可就不仅仅是短命，而且死的特别的窝囊，毫无壮烈可言。从欧共体到欧盟的演化，从欧元在艰难中产生，到踉踉跄跄的前行，欧盟能吃的国家和不能吃的国家都一口吞下了，我们能看的出来，欧盟是有野心的。在2008年美国金融危机开爆以后，欧盟似乎看到了美元垮台后自己可以立马成精的可能，其不自量力的表演，不仅没必要获得其他力量的支持，相反，还遭到了喘口气后的美国剧烈的反击。在美国看来，欧盟的蠢蠢欲动已经不局限于防守的范围了，抢班夺权的表现已经淋漓尽致，在美元信用下降的情况下，如果不能有效的击溃欧元，最起码击溃欧元的进攻，那美国衰落的速度会更快。相对于人民币来说，欧元的威胁目前更大。

<<志大才疏的欧盟>>也闻到了这种不祥的气息，经过多轮的试探和推演，在世界必将动荡的时刻，欧盟选择了利比亚这个可能是个坑，会埋葬欧元，也可能是一个宝，会照亮欧元的地方，进行了一场豪赌。

二、利比亚对于欧盟的意义。

关于这个问题，我在《利比亚局势的系统观察》里已经做出了分析，为说明的方面，我重新组织一下主要的内容。

从地缘政治上来说，利比亚的对于欧洲的意义重大。欧洲的整合是欧洲的唯一出路欧盟要解决的第一个问题，就是经济上的整合，标志就是欧元。而欧元的出现，对于目前世界硬通货美元来说，不是福，只是祸。因为<<欧元的存在，各国对美元的需求会降低。这是美欧不可调和的矛盾>>。

欧盟要解决的第二个问题，就是政治整合，2009年《里斯本条约》获得欧盟全部27个成员国的批准，政治整合慢慢的走出了雏形。

第三个要解决的问题，就是军事的整合，这个问题，非常明显，但却难办，就是<<拆解北约，形成欧盟自己的军队>>。那就意味然美国滚蛋。

第四个要解决的问题，就是要有一块足够辗转腾挪的地方。把地中海变成内海是再好不过了。欧盟能接上非洲的资源，就会减弱对俄罗斯的依赖。这对欧盟和俄罗斯在东欧问题上讨价还价是有巨大好处的。法德孜孜以求的地中海计划就是为欧盟的将来打基础的。如果这四个问题在有限的时间内被逐一的解决，那欧盟就有问鼎天下的实力了。如果能毕其功于一役，那就是天赐良机了。

从欧盟的这种需求出发，利比亚是欧盟所必取。在没有搞定科索沃之前，只能想不能做。所以欧盟对卡扎菲的友好，更多是为了长远的打算。在没有能力搞定卡扎菲之前，要保证卡扎菲不被美国搞定。保证这块肉鲜活的放在那里，等待时机，吞下去。同样道理，美国也担心利比亚被欧盟吞下去，所以保持卡扎菲的独立地位，对美欧都很重要。这是一种微妙的平衡。是欧美互不信任和对利比亚都有觊觎的表现。这种表现，短时间成就了卡扎菲，让他安稳的度过了好多年。但是当国际局势进一步激化，无论是大国还是小国的生存空间变小的时候，在美国的力量相对下降以后，利用地利之便，欧盟对于控制利比亚，推行地中海计划的渴求就变得非常的强烈。

三、美欧在利比亚原则性的区别

美国是很想独霸利比亚的，但是卡扎菲还是有几两硬骨头的，美国一直没有有效的控制卡扎菲。虽然绞死萨达姆震慑了一把，但是卡扎菲利益美欧的矛盾依然屹立不倒，在美国没有能力独自吃下卡扎菲的时候，美国的要求就是“我吃不下，谁也别想吃下”。特别是欧盟，<<美国是不可能让欧盟顺顺利利的拿下利比亚的>>，所以从利比亚的战争一开始，美国一直都是出工不出力。就这样耗着，看谁耗得过谁？

对于欧盟来说，利比亚的战争越早结束越好，因为攻击利比亚是冒着巨大的战略风险的，“兵贵胜不贵久”如果在利比亚的战场打成了持久战，那么美国一定会乘这个大好时机，加大对欧元的进攻。如果欧元沦陷，那利比亚战争也就没有胜利的可能了，就是太阳从西边出来，胜利了，还有什么意义呢？

于是，我们看到，从希腊开始，美国开始了一波又一波的进攻。而欧盟能做的就是一方面继续的顶住美元攻击的压力，继续协调各国的利益冲突，团结起来，共度难关。另一方面，就是加快利比亚的战争的进程，早点结束。可是无论是前者，还是后者，局势的变化都出乎欧盟的预料。

在上个月的21日通过的对希腊实施第二轮紧急救助的方案。救助贷款额度为1090亿欧元；贷款利率约为3.5％，还款期限为15年至30年。在去年5 月底，欧元区国家决定对希腊进行第一轮救助，救助金额为1100亿欧元。仅仅一年的时间，仅仅在希腊这个地方，已经吞噬了2000亿欧元。

难道，欧盟出问题的和将要出问题的仅仅是一个希腊吗？

意大利和西班牙也被人盯上了，后面还有。美元的战略是明显的，你不是要救吗？我让你慢慢得救，慢慢的拖，慢慢的耗，这样的持久战对于高福利的欧洲国家来讲，虽然见效慢，但杀伤力会非常大，<<美国可以用自己的美元霸权优势慢慢的耗死欧元，如果没有人插手的话。>>

所以对于希腊的第二轮紧急救助，当欧洲的头头脑表现乐观的时候，我丝毫不觉的危机已经过去，美国要的就是欧盟的“添油战术”，似乎有希望，但是慢慢得让你失望。对希腊的第二轮救助方案只是延缓了希腊破产的时间，如果欧盟不对其他国家让步寻求支持。那欧债危机一定会向意大利、西班牙等欧元区核心国家蔓延。希腊注定要成为欧元区国家中第一个出现债务违约的国家

四、欧盟的选择。

当时就只有<<两条路>>，是放弃欧元还是坚持下去。正是因为不放弃的原因，欧盟才选择折腾的，但是因为自身实力的原因，在没有外援的情况下，欧盟已经没有力量完成当初的战略设想了。不要说地中海计划无法实现，因为力量透支的原因，就是自保都显的困难。

目前欧元需要做出选择的就是一个妥协的问题，如果向美元妥协，那欧元得独立性就会受到影响，其信用要打折，未来有被美国收入囊中的可能。如果不向美国妥协，那就要寻求中俄的支持，来度过难过。其目前的损失会大，但长远的利益会得到保证。这就要考验欧盟的智慧和勇气，<<讲智慧是需要分辨合作和妥协的对象，讲勇气是说要为了大局牺牲局部的利益>>。

五，未来局势的展望

可以预见的是，对于美国来说，自然是百足之虫死而不僵，不可轻视美国的力量，特别是“币权”的力量。如果能击溃欧元，在一个时间段内，美元就安然无恙了，美国也就取得了相对长点的疗伤时间，可以度过危机。所以美元对欧元的进攻是会一直延续的（因其他力量的介入，可能会出现一些变化），而欧元也不可能被一击而溃。

在欧元的反抗中，美元与欧元的信誉会受到极大的损害。欧盟在危机的关头向美国妥协的可能性很小，除非欧元实在太弱和美国开出的妥协的条件太诱人；在目前，欧盟向其他力量妥协的可能性是很大的。因为大家有一致的需求——废了美元的霸权。这个统一战线是可以建立起来的，至少在短时间内可以。讲短时间是因为，如果欧元获得了其他力量的支撑变得难以攻下，那美元也不得不调整策略，向相关力量表示妥协。一句话，就是<<战斗是异常激烈的，但妥协随时存在。>>在相同的战斗对象和不同的妥协组合中，美欧都会注意招式不能使老的问题，也会注意及时调整拉和打的手段。

最后讲的有点绕，希望不要被绕进去。<<我们该思考的是：美元与欧元的斗法，因其复杂性。无论是他们的战斗还是妥协，都有幻想的成分存在，都有相应的时间差存在，都有防御或寻求外部力量的动机存在。作为将来要走向世界的人民币，作为看似在局外，其实已在局中的中国，我们该利用美欧的争斗与妥协做点什么呢？>>

机不可失，失不再来啊！

#+begin_center
会同天下 2011年8月7日
#+end_center
