# -*- org -*-

# Time-stamp: <2011-08-19 21:50:51 Friday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 利比亚局势的系统观察

[2011-03-22 23:04:25]

日本核电站的硝烟还没有散尽，利比亚的战火已经开始蔓延。我们生在这样的世界，究竟是有幸还是不幸。利比亚的战火会烧到什么地方，会引发世界怎样的动荡，会给大国间的较量增加怎样的不确定因素。

 一、利比亚问题的由来


利比亚是北非的一个国家，位于地中海南岸。地理位置非常重要，是美国、西欧和亚洲的中东、西亚、南亚、东南亚、东亚之间的海运线的必经之路。人口不多，600多万人，面积不小，有170多万平方公里，但可耕地面积不多，约占全国总面积的 2%。粮食不能自给，大量靠进口。国民信仰伊斯兰教，有丰富的石油资源，石油生产占国民生产总值的50－70%，石油出口占出口总值的95%以上，<<人少地多，资源丰富，位置重要，这就决定这块土地必然会成为大国争夺的目标，>>简言之，这样的国家是不能独立存在很久的。特别是在美国势力衰落欲浑水摸鱼来翻盘，欧洲整合步伐加快欲毕其功于一役，中国和平崛起稳步赶超欲进一步经营非洲的今天。这个美国不喜欢，欧洲不认可，没有向中国递交投名状的国家，要是不出现问题，那是不可能的。

现代的利比亚要从二十世纪说起。1912年10月利比亚在<<意土战争>>后成为意大利的殖民地。二战期期间，无能的意大利很快就失去了利比亚，我有时真的很纳闷，出帅哥的意大利，为什么军队的战斗力就那么弱，二战之前，就有被埃塞俄比亚打败的历史。二战中，在英法的打击下，也没有表现出应有的强悍。1943 年初英、法占领利比亚南、北部。1951年12月24日利比亚宣告独立，成立利比亚联合王国，伊德里斯一世为国王。1969年9月1日，由卡扎菲领导的 “自由军官组织”发动军事政变，推翻了亲美的伊德里斯王朝统治，卡扎菲的时代就此开始。直到现在，卡扎菲统治利比亚已有40多年了，能和老卡一样牛的，就是另一个老卡——卡斯特罗[fn:kaslote]。

[fn:kaslote] 菲德尔·亚历杭德罗·卡斯特罗·鲁斯（Fidel Alejandro Castro Ruz，1926年8月13日－ ），古巴前国务委员会主席和部长会议主席，古巴共产党第一书记。2011年4月19日，古巴前领导人菲德尔·卡斯特罗在一份刊发的报纸中撰文证实，自己已经辞去古巴共产党最高领导人职位。

 二、卡扎菲与美国的恩怨


两个老卡都有抗美的经历。1970年6月，卡扎菲收回了美国在利比亚的军事基地。由于越战和美苏争霸的原因，美国没有马上反击，直到1980年，美国才宣布利比亚为“支持恐怖主义国家”。第二年，两国断交。1986年，美国总统里根下令停止与利比亚的经济和贸易关系。在这样的情况下，卡扎菲的内心还是不惧的，因为中东没有还没有被美国拿下，苏联也不会坐视美国把利比亚变成美国的殖民地。

但是，时代的变化实在是太快了，1991年苏联解体，美国大口的吞噬苏联解体带来的利益。第一次海湾战争后，美国明显的加快了大中东计划的步伐。 2001年“911事件”后，美国发动了大规模的第二次海湾战争。一方面蛙跳进入中亚，一方面美国加强了对非洲的军事干预。卡扎菲见势头不妙，也选择了退让，一改与美对抗的强硬立场，积极配合美国的反恐。同时卡扎菲也积极的同欧洲各国改善关系，并敏锐的发现并利用欧美因为伊拉克战争带来的分歧。而美国政府绞死萨达姆之后，美在伊拉克依然是胜而不利的局面下，对卡扎菲采取了威慑和利诱相结合的怀柔政策。<<2008年，美国的次贷危机引爆了欧美金融危机>>。美国加强了和中俄欧的争斗，卡扎菲也就安安稳稳的到了2011年。

虽然美国政府采取多种措施，来化解金融危机带来的深刻问题，但是美国的国势依然在走下坡路。<<其霸权的根基——美元与石油>>都被剧烈的侵蚀。其间与中国、俄罗斯和欧洲的争斗与妥协都没有根本性的改变美国的困局。<<两次“量化宽松”，给世界注入了动荡的基因>>>。2011年从突尼斯开始，一场席卷无数小国的动乱开始上演。卡扎菲与美国的麻杆打狼——两头怕就此结束。

到了要结果的时候了。美国的经济已经不能再等下去了，自然想趁机顺水推舟让卡扎菲下台，控制利比亚资源与地缘，扼住世界的咽喉，给世界注入更大的不确定，更方便的浑水摸鱼。（关于这一轮混乱各国利害的分析，参见拙作《风云激荡下的世界局势》，那里有更细致的分析，这里不再重复。）

 三、卡扎菲与欧洲的是非


从地缘政治上来说，利比亚的对于欧洲的意义重大。<<欧洲的整合是欧洲的唯一出路，当法德放下民族仇恨，抛开历史恩怨，走到一起的时候，欧盟所求的就不会小。否则，没有必要也不可能法德走到一起。>>

欧盟要解决的第一个问题，就是经济上的整合，标志就是欧元。而欧元的出现，对于目前世界硬通货美元来说，不是福，只是祸。因为欧元的存在，各国对美元的需求会降低。这是美欧不可调和的矛盾。

欧盟要解决的第二个问题，就是政治整合，2009年《里斯本条约》获得欧盟全部27个成员国的批准，政治整合慢慢的走出了雏形。

第三个要解决的问题，就是军事的整合，这个问题，非常明显，但却难办，就是拆解北约，形成欧盟自己的军队。那就意味然美国滚蛋。

第四个要解决的问题，就是要有一块足够辗转腾挪的地方。把地中海变成内海是再好不过了。欧盟能接上非洲的资源，就会减弱对俄罗斯的依赖。这对欧盟和俄罗斯在东欧问题上讨价还价是有巨大好处的。法德孜孜以求的地中海计划就是为欧盟的将来打基础的。如果这四个问题在有限的时间内被逐一的解决，那欧盟就有问鼎天下的实力了。如果能毕其功于一役，那就是天赐良机了。

从欧盟的这种需求出发，利比亚是欧盟所必取。在没有搞定科索沃之前，只能想不能做。所以欧盟对卡扎菲的友好，更多是为了长远的打算。在没有能力搞定卡扎菲之前，要保证卡扎菲不被美国搞定。保证这块肉鲜活的放在那里，等待时机，吞下去。同样道理，美国也担心利比亚被欧盟吞下去，所以保持卡扎菲的独立地位，对美欧都很重要。这是一种微妙的平衡。是欧美互不信任和对利比亚都有觊觎的表现。这种表现，短时间成就了卡扎菲，让他安稳的度过了好多年。但随着平衡被打破，这种表现也必然会毁了卡扎菲。这就是成败萧何的道理。

在2001年“911事件”出现后，卡扎菲表现出合作的意愿，美欧都迁就着。尽管，法德力推的地中海联盟，被卡扎菲猛批，并拒绝出席地中海峰会，虽然当时的法德恨得牙痒痒，却没有表现出应有的强硬。

可是<<卡扎菲对地中海计划的抵制，让法德等欧洲国家看到，卡扎菲的政府的存在，对于欧盟的千秋大业是一个巨大的阻碍，有机会，剪除之，成为了欧盟主要国家的共识。>>特别是法国，对非洲是有非分之想的，当年的“辉煌”也搅动着高卢雄鸡的不甘沉默的心。

 四、弃权不代表没有自己的主导意见


中俄都有经营非洲的历史，中国近些年干的还很好。安理会3月17日召开会议，要求在利比亚设禁飞区的，中国、俄罗斯等国投了弃权票。

追溯过去，当年美苏争霸，苏联曾经支持过利比亚，甚至利用利比亚作为他的代理人干预中非局势，为什么现在就哑巴了呢？真是时移世易啊。当年美苏全球争霸，可谓风光无限，可现在的俄罗斯，已经不复往日雄风。他的利益范围仅仅限于周边，更远的地方已经够不到了。况且利比亚动乱，油价会高企，这正是俄罗斯所想要的。

中国以和平崛起的姿态，在怀疑的沉默中壮大。中国经营非洲是深耕细作，这就动了别人的奶酪。西方国家就愤愤不平了。给中国下绊子的越来越多，手段越来越恶劣。美国一直以来没有停止对中国的遏制，中国的发展也到了关键的时期，是向前一步，实现质的飞跃，还是退后十步，永远停留在量的积累。这是一个大问题。

中国需要非洲，需要非洲的资源，需要世界的安定，但是，对于美国来说，如果不能接受美国的城下之盟，中国需要的，自然就是该破坏的。而以目前中国的实力，还不具有正面突击的能力，或者说，还不到正面突击的最佳时间，<<中国有止战之心，却无止战之力。中国还想再获得一个战略机遇期。再给中国10年，完成经济转型，为将来实现东北亚的整合打下基础，实现中华民族的伟大复兴。>>

 五、战争终于爆发


 <<2011年3月19日，巴黎时间17时45分左右>>，法国战机在利比亚对利政府军的一辆军车开火，实施了首次空中打击。之后几小时内，法国“阵风”和“幻影－2000”战机又进行了3次空袭，摧毁了利政府军数辆装甲车。与此同时，部署在地中海的美军和英军军舰与潜艇也向利境内发射了百余枚“战斧”巡航导弹。
 
 卡扎菲发表电视讲话称：“现在应该打开武器库，用各种武器武装所有民众，以捍卫利比亚的独立、领土完整和荣誉。”
 
这场军事行动的代号是“<<奥德赛黎明>>”。这样阵容的列强去侵略一个小国，却起了这样一个名字，这个“黎明”不知道会是谁的黎明，但无论是谁，都不可能是利比亚百姓的黎明。这场战争带给利比亚的只能是黑暗，痛苦，乃至死亡。

<<因为发动战争的国家各怀鬼胎，决定这场战争不会轻易的结束，>>是谁陷在其中，谁会用自己国家将士的生命体味利比亚人民的痛苦，将是一个未知数。美国因为前车之鉴，这次显得谨慎的多，但是局势的发展，将慢慢失去控制。奥巴马还是没有打破美国总统在位期间发动战争的魔咒。

 六、未来局势的设想


<<大国不可侮，小国不可横。>>是国家生存的法则，侮辱大国有灾，小国强横易亡。“故小敌之坚，大敌之擒也” 。

既然，局势的发展形成了合力，这种合力，必然就会被各种势力所利用。当美国的“量化宽松”的猛虎出笼，小国的生存就会越来越难。既然乱局已经不可避免，那么各国都会行动起来。<<在世界变局的背景下，卡扎菲安全的平衡被打破，向卡扎菲动手，成为了美国和欧盟的共同选项，>>其间的区别是，美国已经没有能力或者有所忌惮的不愿独自行动，当然还有其他国家的掣肘。而法国为代表的欧盟则想在行动中取得先手，为后来的利益分割埋下伏笔。

<<当平衡被打破，当利益在短时间趋同，就上演了列强去攻打一个主权国家的丑剧。>>卡扎菲儿子还算是有种的，称父亲不会下台，誓言战斗至死。其实通过卡扎菲父子的讲话，可以判断，仅仅从战场上来说，胜负是已分了的。

但是，当飞机起飞，当爆炸声响起，问题就解决了吗？利比亚是一个潘多拉的盒子，打开是很容易的，但是飞出的魔鬼谁能制服。美国之于利比亚，其破坏性是明显的，建设性可以忽略不计；法国之于利比亚，从长远来看，建设性是明显的，短时期破坏性也是明显的。因为法美在利比亚的未来定位上有根本性的区别，欧美的矛盾是不可调和的，内部的分裂会慢慢的明朗化。

<<欧盟希望通过利比亚战事，巩固欧元的地位，协调欧盟的政治一体化，整合欧盟的军事力量，拆解美国控制的北约，并为地中海计划打下基础，有毕其功于一役的野心；而美国则希望能够让利比亚进一步的混乱，造成通道受阻，削弱欧盟的力量和打击中国的经济，缓解美国的经济压力，有一石三鸟的意思。>>

美国虽有一石三鸟的意思，但，美国是异常谨慎的，这个原因以前分析过，而<<欧盟是法动德不动，留下了退路。>>似乎都机关算尽，但会误了谁的卿卿性命，还未可知。

多国军事打击利比亚的行动继续引发国际社会的争议。俄罗斯总理普京斥责有关的行动是“中世纪十字军东征”，“不合逻辑”。他还表示，俄方不支持安理会有关在利比亚设立禁飞区的决议。土耳其等国表达了相似的立场。

<<分歧的加剧，意味局势的复杂。>>战胜卡扎菲是容易的，建设好利比亚是艰难的。美国会不会慢慢的陷入伊阿之外的“第三战场”，我希望他陷进去，美国的帝国思维也容易陷进去。让狂妄的帝国继续高声的咆哮、继续流血、继续的用他仅有的精气神去挥霍。欧盟的算盘打得很精，但是美国怎么可能让欧盟快速的整合利比亚，让欧盟毕其功于一役。<<美欧会发现打着打着，就打成持久战了。>>中国对于利比亚的局势发展是很有前瞻性的，九天八夜，中国政府从局势动荡、险象环生的利比亚撤出[[35860]]名中国公民，说明中国是有准备的。中国在观察等待，找到最好的时机出手。

 七、没有结局


<<世事如棋，局局常新，生而赴死，死而复生。大国博弈，逞智斗勇，极尽诡异之道；成败利钝，精彩纷呈，令人眼花缭乱。>>可作为个体的人则是的悲哀的，利比亚的局势会进一步的恶化。因粮食不能自给，大量靠进口，可以判断，在局势进一步恶化后，利比亚的百姓会生存艰难。打着人道主义幌子的欧美，必然会造成更大的“人道”危机。

 孙武说：“亡国不可以复存，死者不可以复生”，可悲可悯者，良可多也！

 

 
#+begin_center
会同天下  2011.03.22
#+end_center
