# -*- org -*-

# Time-stamp: <2011-08-19 20:35:05 Friday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 从微妙的中菲关系看中美在南海的政策

[2011-07-22 13:48:26]

一、相关新闻

2011年7月20日，5名菲律宾议员和一些菲律宾军方人士登上南沙群岛第二大岛中业岛，在岛上升起菲律宾国旗，并与非法控制该岛的菲驻军唱该国国歌。　

中业岛为南沙群岛岛礁之一，长800米，宽500米，面积0.33平方公里，是南沙群岛第二大岛。虽然从清朝以来，该岛便有中国渔民居住。中国渔民曾在岛上种植椰子、木瓜、番薯和苋菜等。但是，建国后，中国的海军力量极为薄弱，无法维护在中业岛的治权。1971年起，中业岛被菲律宾占领，目前依然被菲律宾实际控制，岛上不仅有菲律宾驻军，还建有一个机场。如果从1971年开始算起，中业岛已经被非法控制了40年。


面对菲律宾的议员登上南沙群岛并安插菲律宾国旗一事，外交部发言人马朝旭表示，中方对菲议员登岛表示强烈抗议，菲方上述行动严重侵犯了中国的领土主权。


二、有点复杂的中菲关系。

如果说以前因为中国海军力量弱小的缘故，菲律宾还有可能这样做，在中国已经日益强大的今天，菲律宾怎么还会这样做呢？是出于什么样的想法？简单的说，是谁给他壮胆，答案只有一个，那就是美国。所以，讲中菲的关系，就一定要带上美国，否则就有讲不清的可能。

先从美菲关系说起，从20世纪早期直到冷战结束，菲律宾一直是美国的仆从国，美军一直是菲律宾国家安全的支柱。所以美国对菲律宾的影响是深远的。在1992年，随着基地使用协定到期以及前苏联解体，菲律宾政府终止了美军在该国驻军的历史。

苏联解体，日元升值，冷战后美国获得了政治经济的双丰收，成了世界真正的霸主，名副其实的超级大国。随着国力进一步的增强和没有现实对手的顾虑，美国的信心与野心开始极度膨胀，而没有控制的欲望必然造成可怕的灾难。美国<<借“反恐”之名，行征服世界之实>>，义无反顾的跳进了“帝国的坟墓”——阿富汗。美菲之间的关系，因为美国驻军的撤离和美国战略重心的转移而淡化。

中菲关系在2004年是一个分水岭，那一年，伊拉克一个极端主义组织绑架了一名菲律宾工人，并以让菲律宾从伊拉克撤军相要挟。在强大的国内舆论压力下，菲律宾被迫从伊拉克撤军，这让美国非常的不愉快，美菲关系受到损害。这时菲律宾及时的加大了对中国的关注，中菲关系开始出现质的变化。军事交流不断，经济合作良性快速的发展，菲律宾在中菲的军事交流与贸易中受益，成为东盟地区重要的一支力量。

三、利用和平衡

美国和菲律宾是互相利用的关系，对于菲律宾来说，能有大国支持其对利益的巩固与获取，那是最好不过的；对于美国来说，面对中国的快速崛起，美国太需要给中国制造麻烦来阻止或延缓中国的发展，基于此，美国和菲律宾的互相利用就是最正常不过的了。

不仅是菲律宾，对于东南亚国家而言，“<<大国制衡>>”而达成的平衡是东南亚一些小国长期奉行的外交政策之一。无论是美强中弱还是中强美弱，都是这样。对于中国目前的崛起，东盟国家心里面是异常复杂的，他们不想在自己的周边出现超级的大国，担心超级大国的存在会对自己的发展产生不利的影响，特别是这样的大国如果没有节制的扩张或者说是侵略，那小国的命运就堪忧了。当年的日本就是用这样蛮横的武力侵略了东南亚国家，给他们带来了深重的灾难。所以，东南亚国家内心对于周边大国有天然的防备心理是非常正常的反应。

对于目前，虽然美国有不可告人的目的，怀有对东南亚国家的狼子野心，但是有些国家选择在玩危险游戏——走钢丝，妄图借助外国势力解决南海争端。因此一些东南亚国家并不排斥美国势力的介入，但是我要提醒的是，从来都是“<<请神容易送神难>>”，不要干“<<引狼入室>>”的蠢事。

在中国晋升为亚太地区的增长发动机以及美国相对衰落的合力作用下，特别是中国已经宣示了南海是核心利益的情况下，能平衡中国影响力的美国，已经不能给东南亚国家带来他们希望的东西了。自顾不暇的、处于下降通道中的美国能给菲律宾带来什么好处呢，所谓的安全，也只是一个不可能兑现的承诺。

四、中美在南海的纠葛

我们知道，去年中国已经宣示了南海是中国的核心利益，前不久中国在南海示强，用强有力的行为警告了越南，这是中国在南海方面政策转变的一个标志。

讲南海问题是一个历史遗留问题，一点都不夸张。二战结束后，美国成为东南亚的统治者，相对于日本的残暴，美国的统治相对温和的多，特别是出于冷战的需要，美国对于东南亚国家的采取了拉拢和扶植的政策。菲律宾就是一例，<<对于可能被共产主义的赤化的国家，美国发动了战争来消灭，越南就是这样的情况>>。

二战后的相当长的时间，美国虽然政策的重心在欧洲，但因其力量的强大，在东南亚的地位仍然是举足轻重的。虽然苏联一度扶植越南，进军金兰湾，但是影响力有限。后来苏联解体，俄罗斯式微，美国对于东南亚在强悍国力的威慑下就摆布的更加得心应手了。这样的情况一直持续到中国的崛起。

中国建国以后，海军力量一直是非常弱小的。对于广袤南海的主权，虽有要求，但无力维护。而东盟一些国家利用中国当时海军力量的弱小和自己国家地利之便，开始占领这些的岛屿。中国因为力量投送的限制，只能进行抗议。直到<<1988年中越海战>>，才夺回了一部分岛礁。

中国在近十年中，力量有了质的飞跃，特别是美国2008年金融危机的爆发，中国力量被提前登场。美国在东南亚影响力下降的同一时期，中国与东南亚诸国在经济、政治等领域的联系不断加强，在东南亚的影响力也不断提升。

在这场必将改变世界格局的大变革中，<<中国确立在南海的核心利益和恢复在南海行使主权是中国最低的要求>>。面对中国的崛起，美国人坐不住了，为了抗衡中国在东南亚日益增强的影响力。2009年7月21日希拉在泰国首都曼谷高调表示要：“美国重返东南亚。”

但让我纳闷的是，既然说是重返，那就应该离开过，没有离开过，哪里有重返的说法呢？难道像《金刚经》说的那样“无所从来，亦无所去”？更让人感到可笑的是，重返两年了，却不知“重返”到哪里去了。

美国在金融危机之后高调“重返东南亚”，其<<司马昭之心>>是路人皆知的。一者，美国要在全世界展示其力量，树立其对美国的信心，来给美国的经济打强心剂，方便推行杀人不见血的所谓“量化宽松”；二者，面对中国在金融危机中抗打击的表现，美国需要在中国的周边挑起地区冲突，制造事端，扰乱东南亚和平发展的环境。在阻挡中国发展的同时，把滞留在东南亚的美元通过动荡给挤走，回流美国，给美国救急。

五、中美之于东南亚国家的不同

正是上面的原因，美国“重返东南亚”也好，美国和东南亚各国的合作利用也好，都不会有什么美好的前景可言。这种的互相利用，一定不可持续，最终一定会让相对弱势的一方在某个利益不对等的交换中伤痕累累。东南亚国家，做好这样的准备了吗？

这方面对于中国来说，则恰恰相反。中国正快速的发展，中国也愿意采取通过外交途径来解决南海问题。在中国快速崛起的今天，中国与东南亚国家间的双边关系日益密切。实现互利双赢不仅是现实写照，也已经为历史所证明，东南亚各国已经从中国的经济发展中得到了实实在在的好处。

况且，对于东南亚国家而言，中国与东南亚各国在地缘上接近，经济上互补双赢的优势是美国无可比拟的。中国的军事力量突发猛进的发展，<<打造东南亚的安全框架>>已经指日可待。当年东南亚金融危机，中国用当时并不坚实的肩膀担起了大国的责任，说明中国是可以依靠的力量，而现在，美国的那个“虚拟经济”的发动机时常抽风，中国的“实体经济”的发动机正常运转，中国正在用强大的经济和军事力量羽翼东南亚国家已经是有目共睹的事情，没有<<中国的坚守>>，东南亚国家早已经被金融资本血洗也是不争的事实。

就目前局势而言，有些国家幻想依靠美国来维护自己不恰当的利益是不现实的，如今的美国就是一座冰山，冰山能靠吗？相信菲律宾即便没有智慧找到解决问题的办法，也会看到中国解决南海问题的决心。有话好好说，有事慢慢谈，不要消耗中国的耐心，不要挑战中国的底线。趋利避害是人性使然，不要为了蝇头小利，招来无妄之灾。


#+begin_center
会同天下2011-07-21
#+end_center
