# -*- org -*-

# Time-stamp: <2011-08-24 21:01:25 Wednesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话35：看事情不能用一个方向

[2010-12-27 03:42:53]


就像越南一样，如何改革，自然就是看中国的经验。

当年中国改革的时候，是政治强势领导人邓小平在位，因此某种程度上可以压制住军队的势力。

中国的法子是分了三步，一个是对越边境自卫反击战，是在军中立威，同时一大批年轻的将领，因为战功而取得了一些退休的老将。

第二步是裁减军费和人员。但是同时，又允许军队经商。

这一条路子是减轻了国家在军费上的负担，有利于改革开放向经济发展为主的方向变化。同时让军队可以捞点外快，补偿一下日子。其实是在新时代背景下，南泥湾精神的重现。

当然这种新时代的屯田，面临的和汉朝时候同样的一个问题，就是 *如何在突出了军队的生产力的同时，又可以保证军队在军事上的战斗力。*

某些方面，比如说国防工业军转民，或者是以前对外援助革命的武器输出，变成了外交和商业并重的经济活动，都可圈可点。但是也出现了某些军队企业，牵扯进了走私大潮里面去了。

因此下一步，就是在90年代中期出现的禁止军队经商，重现由国家军费养军队的情况，但这个是在经济发展之后的事情了。

相比较于朝鲜，朝鲜军队在武器输出方面，已经走了商业化的路子。其中以出口伊朗和叙利亚为主。

当然这个出口，受到美国打压很厉害，因为 *出口伊朗的武器，然后就会转送到苏丹，然后走秘密路线，经过埃及，到了巴勒斯坦哈马斯组织的手上。*

*而出口叙利亚的武器，就会转送到黎巴嫩，到了黎巴嫩真主党的手里。*

这个商业行为，同时也变成了外交上的一个砝码。你美国要想俺停止，出钱。

相对于邓小平，金正日在朝鲜对军方的约束力也是比较强。所以要想改革，保证军队不会阻止，一定得他在世的时候，才有可能完成。这也是为啥朝鲜在想确保外部和平环境的举动，非常之急切。

因为解决不了的话，朝鲜以后出现军政府，就是背离党指挥枪，而出现枪指挥党的情况，几率会比较大。

军人是打仗的。如果军人也可以把经济搞好，那打仗的本事就值得怀疑了。缅甸军政府就是这么一个活生生的例子。

*但是要约束住军人，一是要防止军队大强势，搞军事政变。二是要防止军队甩担子，引外敌入侵。*

对朝鲜另一个比较有利的，除了军队在武器输出的商业活动中有收益之外，就是核子能力的发展。

因为在核武器问题解决之后，如果朝鲜仍然具有和平运用核子能源的权力，具有快速核子武器化的能力，还是可以保护国家免受外敌入侵。

就是说，军队的砝码可以相对降低。

而朝鲜的经济发展，也不是希望出现那种一边倒依赖中国的局面。因此中国倡导的东北亚经济圈，或者说图们江经济区，至少把中国东北、朝鲜和俄罗斯远东，扯到一起。如果可以加入韩国和日本，那么朝鲜估计感觉很爽一定。

毕竟投资的多元化，给自己的砝码要多一点。但是在这个多元化之中，中国成为主导，也是比较顺理成章和可以接受的安排。

这种以朝鲜作为主体来思考的行为，肯定和李明博希望朝鲜政权崩溃，而由韩国来主导的想法，有根本的冲突。

从韩国的角度来讲，武统代价固然比较大，会是以韩国社会和经济回到60年代为战争代价。但是要是以美韩军事联盟为基础，在武力上震慑住朝鲜，可以确保韩国可以在朝鲜崩溃的时候，采取武力接管。

但是这个接管问题，有一个很大的经济代价，就是要统一和接管朝鲜，靠韩国的经济实力，就是吃奶的力量都用完了，还是很难做到的。

那么这个时候，韩国就需要借助外力，那就是要美国、日本，甚至中国来为韩国统一朝鲜的账单付账。

有人为诧异，怎么可以逼中国来买单？

有三个砝码可以使用。

第一个是韩国“不允许”美军推进到三八线以北，“不让”美军驻军鸭绿江边。

第二个是韩国“不再”对中国的吉林延边朝鲜族地区，有主权要求。

第三个是韩国保证中国在未来朝鲜的经济发展中，扮演主导作用。

前面两个，基本上是空手出牌，就是用无牌打你的有牌。第三个，可以说是收买政策，也可以说是借你的资金，来保证俺的顺利接收和发展，是草船借箭的招数。

而从长远来看，韩国的企图，是要变成一个世界大国。那么左手搭上美国军事超强的战车，右手搭上中国经济超强的战车，用美国的军事同盟来制衡中国，增加韩国自身经济上讨价还价的砝码，同时用中国的经济同盟来制衡美国，增加韩国自身军事上讨价还价的砝码。

那么有一天，韩国人觉得自己在经济上，可以有竞争得过美国的企业，在军事上，可以有比中国先进的武器装备，日子不是过得很爽？

有一天美国真的衰落了，就是利用价值完了，那么就一脚把美军踢出去。朝鲜半岛也统一了，中国也是平起平坐的经济伙伴了，美国人就该滚蛋了。

其实 *韩国的大国目标，就是未来的东亚局势中，韩国可以和中国平起平坐而已。*
