# -*- org -*-

# Time-stamp: <2011-08-23 19:26:55 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话7：经济不发展，一切皆扯淡

[2010-10-15 14:40:32]


有读者问道了当时美国在1920年代和中国的对比，说到美国当时的国内环境和国际环境。其实在俺的《四面楚歌》一书中的美国系列篇中，已经写得非常明白。

这里就简单的总结一下。

当时美国的国内民意是支持有效率和有所作为的罗斯福独裁，而反对所谓国会的民主，和最高法院的法制。

其中一个原因是美国最高法院，在1920年代就已经宣判最低工资制违反美国宪法。罗斯福新政中的几次行政命令，试图建立最低工资制，都被最高法院裁定违法而失败，直到1941年的一次判例，最高法院才宣布了这个法律合乎宪法原则。

*可以说美国对屁民关怀的法律，是在一个所谓独裁总统的推动下，经过了20多年的斗争，在法院的不断打压之下，最后才得到实施的。*

当时的美国人，对民主这个词是比较反感的。 *美国人今天的民主概念，是在1980年代，开始开发出来对付苏联的意识形态工具，因为美国六十年代的压迫黑人和七十年代的反越战，都让美国体制陷入不小的危机。*

当然在黑人民权运动之后，给予了黑人精英体制内的道路，虽然黑人屁民仍然生如草芥，但至少没有被人在这方面穷追猛打了。

*对自由的理解，也不是今天大家想象的那种个人至上的个人自由，更多的是起源于美国早期一帮新大陆殖民者，以家庭和教会为联系，而形成的自治的小社区的自由。*

这种小社区的自由，而反对大政府的干预，是今天美国的不少黄巾军人士的基本看法，以后会谈及这一点。

因此当时美国的制度危机，大家讨论的海外模式，最主要的是意大利的墨索里尼的独裁模式。希特勒的模式不受到大众欢迎，最主要是大众愤恨的华尔街金融大鳄们，是希特勒工业化的主要资金支持的金主，所以算是恨屋极乌了。

其实那个时候，在美国的南部各州，黑人是事实的奴工。比如说你白人社会不给黑人工作，然后警察在街上见到黑人，查有没有工作证。没有就坐牢，然后就把犯人租给美国的大企业，比如说美国钢铁集团等等，去做奴工。

再看一看排华法案，后来的把日裔美国人关集中营，到后来的麦肯锡主义兴起，其实如果条件恶化，美国也是有可能走到希特勒那样的屠杀少数民族的路子。后来逃离希特勒暴力的德国犹太人，跑到了美国殖民的古巴，结果被美国政府拒绝接收，然后赶回去给希特勒。 *而那个时候，全世界只有中国在接收犹太难民。*

那么当时美国的国际环境，倒是比较安稳。主要的国际冲突是在欧洲，是介于英国为首的西欧集团和德国，以及英国和苏联的冲突。美国倒是可以把自己置身于事外。而且最后的结果，还是因为美国在中国东南地区的势力范围受到了日本的侵害，最后被日本偷袭珍珠港而拖入了战争。

相比较而言，中国的国际环境不能说太差。 *其实当苏联崩溃和其后的俄罗斯衰落之后，中国的国防威胁算是真正的解除了。* 虽然说现在美国常常剑指沿海，在黄海、东海和南海晃来晃去，但是还看不出美国有真正的对中国威胁之意。

而美国在中国西部边界的大动作，也是属于七伤拳，未伤人，先伤己。就像当年美国在朝鲜和越南的几次动作一样，自己并没有讨多少好去。

*因此中国的主要问题，还是在于如何解决自己的内政。而作为一个国家的最关键之处，就是你的经济还可不可保持高速的增长。*

当然这个高速对不同的国家不一样。比如说中国两位数字算是高速增长，而美国以前是5%就算是高速了。欧洲的德国，到了3%，也算是高速了。

在高速增长的经济下，问题虽然出来的多，但是整个社会，不论是资本家阶层，还是劳工阶层，相比而言，都比较有活力和有干劲。那么在整个蛋糕还可以做大的时候，财富高端的人们，对让点利益给其他穷人，还是比较容易做到。

最起码是比大家钱包都在缩水的时候容易做到。而且中国现在处于的一个阶段，还是以 *产业资本* 发展为主的阶段。

这个阶段的人，看问题的角度不同。因为任何一个大的产业集团，需要很多人的合作才可以奏效。所以这些集团的大佬们，比如说以前的亨利福特，今天的比尔盖茨等等，都比较容易体会到自己的财富，其实是由公司里面的上万员工的协作，才可以实现。

因此这些人，对手底下干活的人，比较有感情。

但是当美国发展到今天，很多钱是由金融资本家，在电脑面前的几个按钮控制，就赚来的时候，这些金融奇才们对社会其他阶层的感受，就大不一样了。

因为这些股票等等金融产品里面的交易，真的离开广大的普罗大众太远了，所以这些人心里的感受，就是这大笔钱，都是俺的天才智慧赚来的，俺谁得不用靠。

这种盈利模式，就导致这些大佬们心态傲慢，不可一世，和极度自私。不光是完全不能和产业资本家相比，就是和他们的前辈，比如说摩根等人，主要还是靠支持企业发展的银行贷款起家的老一代金融家，都不可同日而语。

记得有一位有三十年经验的银行家，在90年代的时候，是摩根斯坦利的高层管理人员。那个时候的经济情况不太好，于是公司董事会开会，决定是不是要裁减员工。

董事长说，只有两个选择。一个就是所有的高层管理人员，削减30%的花红。一个就是公司员工裁员5%。

结果先表决，让高层管理人员们举手，同不同意裁减花红。表决结果，在20多人中间，只有3个人举手。

最后的决定，就是高层管理人员保持巨额花红，然后下层干活的员工，被裁员5%。

这位银行家是举手的3个人之一。这事之后，他退出了金融界，因为在他的眼里，觉得 *当员工不再重要的话，那么这个公司也无所谓呆下去了* 。

中国前一阵子的工人罢工，大致得到了公司老板们的不同程度的加薪的回应。要是等到中国的大部分公司，都走到金融资本这个地步，那么局面就会大不一样了。比如说 *美国今天的所有企业的盈利，超过一半是靠金融相关的企业实现的。*

前面说到美国劳工阶层，要靠三个不同的方法，来补偿因为实际工资收入降低的缺口，那么有人就问：为啥美国劳工的工资收入在降低？
