# -*- org -*-

# Time-stamp: <2011-08-24 09:24:55 Wednesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话15：水淹七军和两虎相争

[2010-11-05 15:45:51]

这个星期是美国的中期选举，结果以财政保守为主要诉求，要求美国政府削减赤字的草根运动茶叶蛋们，让民主党在美国众议院的多数党地位，给悲剧了。

其实在奥巴马上台的时候，俺就知道他的问题了。

就是不知道审时度势。

如果是俺的话，那么在就职典礼的时候，俺就会这么说：

My first priority is job creation, my second priority is job creation, and my third priority is job creation.  Have a decent job is not just a basic right for every American. It is also the foundation of American dream.

翻译过来，就是“俺的第一要务是创造就业，俺的第二要务是创造就业，俺的第三要务是创造就业。有一个适当的工作不光是每个美国人的基本权利，也是美国梦的基石。”

因为只有工作才是对大部分美国的中产阶级最重要的，不把精力集中在这里，喊些美国不做老二，要保持做老大，自然就是脱离了群众。那么两年后，被人家翻盘，也是不足为奇的事情。

不过虽然美国人对财政赤字高企非常担忧，还是不能阻止美国联储局，开始开闸发大水。

上次谈到了美国要做的贸易保护政策，和1970年的时候做了一个对比。但是在1970年的时候，美国除了和欧洲人开打贸易战，对欧洲产品进行配额限制的同时，就是开始打开水闸，用天量的美元，准备淹没德国。

在1971年3月，经济合作发展组织公布了一个报告，警告天量美元会拖垮欧洲的金融体系。当时的估计，是美国在1970年出现天量的110亿美元支付赤字之后，在1971年会出现60亿赤字。

*而这些所谓赤字，就是流动到欧洲的美元过剩热钱，用来冲击欧洲的金融次序。*

结果出人意料之外，在1971年的第一季度，在欧洲各国的反对之下，尼克松政府进行了大规模减税政策，导致第一季度的支付赤字，就达到了60亿美元，并出现了美国的贸易赤字。这个贸易赤字，是1969年之后，首次出现，从此之后，美国就开始了贸易赤字的海外掠夺政策。

当然后来的第二季度，美国政府又搞出了60亿美元的赤字，不过这个都是后话，因为在4月份的时候，德国马克和瑞士法郎，就已经在大量美元的冲击下，面临严重的升级压力。

本来在1969年底，德国的外汇储备是71亿美元。但在这一轮冲击之下，一下子上升到了167亿美元，在一年多的时间里，增长了96亿美元，算是翻了一个跟斗还要多。

虽然德国不敢还击（美国大兵在政府门口操练呢），但是法国、荷兰和比利时就开始报复，从美国兑现了4亿2千万美元价值的黄金。

然后美国对德国的货币攻击大幅度提速，在5月4号一天，从美国流入德国的美元达到了12亿美元，用来兑换马克。接着第二天的头一个钟头，就有另外的10亿美元冲进了德国。这一下，导致了德国的外汇储备飞涨到了190亿美元，迫使德国中央银行不得不关闭了外汇兑换市场，希望和邻居们商量如何解决这个问题。

这个时候，美国的喉舌们开始张口嗓门劝降了。当时的主要吹鼓手，是两大犹太经济学家，萨缪尔森和弗里德曼，其主要调调，就是要求德国将马克升值，让其与美元脱钩。

本来德国的想法是，要努力保证小欧盟六个国家的金融稳定，一直的想法都是要建立一个类似于美国联储局的欧洲联储系统。因此德国当时的经济部长席勒提议，如果在天量美元的冲击下，不得不靠浮动来控制局面的话，最好就是将大家都货币挂在一起，

其实就是曹操的铁索连环船政策。当时 *德国* 、 *荷兰* 、 *奥地利* 和 *比利时* 都还可以，只是 *法国* 和 *意大利* 的币值比较弱。因此德国的建议，就是俺出一笔钱成立一个基金，来帮助你这两个弱势兄弟保持稳定。

而这笔基金，就是要用来作为未来的欧洲联储系统。

可是法国人，老子不干。 因为法国人，不希望德国人的控制能力太大，从而导致自己的影响了减弱。当然意大利人也不干，因为怕这样的话，将意大利里拉的币值拉得太高，对自己的筹款不利。

法国说，如果你考虑货币浮动的话，那么老子就杯葛欧洲的联储系统。

其实这个法德之争，在最近也差点弄出了大问题。

因为在雷曼兄弟 *被自杀* 之后，欧洲人已经意识到自己的金融系统是千疮百孔。那天俺听到了美国小白脸财政部长盖特纳的一个访谈，他说次贷危机中德国的几个银行受的打击也不小。好像是损失的金额，比德国一年的GDP还要高。

因此当时欧盟就成立了一个极端机密的小组，提前研究应付欧洲金融系统，因为希腊等等国家受到攻击，而出现的崩盘危险，希望早点找出对策，以避免被人家火烧连环。

可是这个小组，搞了一年半，没法达成意见共识。为啥？是因为法国和德国谈不拢。

这次和1971年那次相反。那时候是德国希望大家一起行动，但是法国人不情愿。而这次是萨科齐要早点出钱（当然是德国出大份额），默克尔不干。

其实看上去德国人不是那么小气和吝啬的人。俺觉得今天从得到的各种数据来分析，应该是两个原因。一个就是盖特纳说的，德国金融系统受到美国次贷拖累很重，另一个就是为了应对经济萧条，德国政府对企业进行补贴，让这些企业用政府的钱支付工人工资，以避免大规模裁员。

在这个困苦的局面之下，德国的选择自然就是一个拖。那就拖到了美国金融大鳄们在2010年初对希腊的开刀。

因为德国的拖延，欧元体系差一点就被美国人给悲剧了。后来是因为来了中国这个外援，一方面是中国大量美元的驰援，另一方是中国内需的带动了德国的经济恢复。

这样才使得欧洲逃过又一劫，但是问题还是存在，就是一座山头上面两种老虎如何和平共处。

而且其中的一只老虎开始逐渐衰弱，于是只好找到自己以前的恩爱情仇的老搭档，开始建构一个英法同盟，从而开始从二次世界大战之后的法德联盟，转而走回之前的英法同盟，和崛起的德国较劲的局势。
