# -*- org -*-

# Time-stamp: <2011-08-24 08:29:05 Wednesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话11：Canuck说，革命形势一片大好

[2010-10-22 14:16:06]

大本涨水小川漫，中国这个涨息的动作，会不会有用，还要看后继发展。

其实美国要用超级流量的美元，来淹死对手的做法，在1970年代就干过。

在1970年5月份，当时的美国财政部长大卫-肯尼迪警告其他国家，如果这些国家不想方设法让美国产品出口进去，美国国会就会开始实行贸易保护。

当时美国政府手上的武器，第一个就是对纺织品入口美国的配额限制。在6月份尼克松总统接见了美国纺织工业的代表，答应不反对国会通过法案，将美国的纺织品进口额削减40%（所以说美国人一张口，就是40%），回到1967-68年的水平。

那个时候的美国，正如美国商业部长斯坦自己坦承，虽然美国在关贸总协定下面享受了不少特权，山姆大叔事实上“是世界人民的 *吸血大叔（Uncle Sucker）* ”。美国采取的是两面三刀的手法，当斯坦部长在支持国会通过贸易保护法案的同时，美国联储局主席伯恩斯却在汉城，表扬韩国、台湾、香港和泰国等等在出口上做得很好。

其实美国的架势一摆出来，就是一边会对欧洲和日本进行打压，同时又在韩国等地发展替代供货商，从而加大自己手上的砝码。

当然在对付欧洲和日本上，美国也先尝试了分而治之的办法。美国先邀请欧洲共同体派人来华盛顿谈判，保证不对欧洲的纺织品和鞋类进行打击，而是主要对日本产品开打。但是欧洲人没有上当，因为他们害怕答应了美国的要求之后，人家马上又翻云覆雨，签订好的协议墨水还没有干，人家美国又开始在电子产品等等上面动手了。

美国这种翻脸不认人的手法，估计中国人在这两年是真正的领教过了。

不过美国这次的很多动作，比如说黄海上的航空母舰疑案，今天要来明天又不来，一时要打雷，一时要出太阳，和中国政府自己内部的某些人士，有很大关系。

可以说，正是中国外交部的一些人物，不断向美国人暗示，你要是想得到中国在经济上对美国的合作（就是说答应美国的予取予求，为美国经济危机买单），你必须，记住了，必须要在中国周边的地方，中国比较敏感的地缘政治上，有所表示。

如果你美国这么做的话，经济上的事情，好商量啊。

于是听懂了的美国人，就开始在中国周边的敏感地缘方面，频频出手表示了。

于是达赖进白宫玩一把了，台湾军队换新武器了。南海开始成为美国核心利益了，黄海要开始玩航空母舰游戏了。钓鱼岛上日本人开始撒野了，南韩整天忙活着找架打了。

还不用提中国西边那一大堆动作了。

美国凭空就造出了一大堆劫材，于是就向中国开经济让步的条件了。以为半个中国政府，哪里敢抗衡一个半美国政府，没料想突然之间，中国的外交开始转向，倒是令海外不少所谓专家大吃一惊。

前一阵子看到加拿大的一些网友谈到，运到加拿大的中国产品要比到美国的产品，少收5.5%的入口税。而由于美国和加拿大是北美自由贸易区，所以你要是把中国货转卖到加拿大，你就必须把原产地中国报上去，就要补上5.5%的税收。

当然如果你把这些货物变成加拿大原产地，就可以吞掉这个差额了。不过区区5.5%而犯法，似乎没有什么意思。

可是要是美国国会通过针对中国的贸易法案，所有中国产品要加个40%的税收，那么这个差距就是45.5%。

接近一半的利润啊，你觉得加拿大人会干嘛？ *Canuck们* 表示，大家情绪非常平和，革命形势一片大好，比大家发梦，梦到的还有好。

是人都可以想得出来。加拿大人一定会说，中国进口货，请不要贴牌子，你省点事情，俺们自己贴上个Made In Canada就行了。

不过你要是闲着没事，那么也行，你就直接贴加拿大制造就行了。反正俺们的海关、政府官员和国会议员，都会利益均沾，谁也不会真当一回事。

那人家美国政府要加强海关，查这些产品如何？

那也有其他法子，就是说走私。俺不信你美国的边防军，可以管住美国和加拿大这条漫长的边境。

而且还有墨西哥那条边境，也要管呢。

这个情形，就会让人回想到 *1920年代* ，当美国实施禁酒令的时候，加拿大的酒铺和酒厂就真是热火朝天，夜不闭户了。

那时候美国要求加拿大不要出口酒到美国，所以大家买酒的时候，要么说俺们自己喝，或者是转卖到第三国古巴。

于是大家买到酒之后，就是蛇有蛇道，鼠有鼠道。本事大的，像黑手党的大佬刀疤卡彭，就动用火车、货船和飞机等等装货，一年可以赚1亿美金。本事小的，就自己带酒闯关，把酒藏在内衣里面、胸罩下面、裤衩档下。还有的就把汽车备用胎割开，把酒瓶藏在车胎里面。

有的在大湖上打鱼的加拿大渔民，发现只有往美国走私一次酒，就比一年打鱼赚到的钱还要多。

那种人人走私酒的做法，不光是加拿大人这么干，连边境州的美国人民也加入了行列。他们要么自己过境去买货，要么在美国国境内接货，然后向内地的各州走私贩卖。

也许你要问，那美国政府是吃素的？不能派联邦人员去守边境？

当然派了，而且还派了不少。不过后来人家这些联邦执法人员，发现查到走私贩的时候，人家塞了一个信封过来，比自己一年的工资还要多。那你收不收？

*所以如果美国要将中国商品加40%的税收，然后中国政府争锋相对，将这些出口美国的商品增加同样40%的出口税，俺敢保证，中国对加拿大和墨西哥的出口，会突然一飞冲天。*

这样的贸易制裁通常的后果就是如此而已。美国制裁伊朗之后，世界各国出口阿联酋的产品也突然增加了不少。

所以美国国会那帮议员，也就是诈唬一下而已。也只有中国外交部里面的一些人，还真当回事呢。

当年美国要用限制欧洲和日本对美国出口产品作为武器，压迫这些国家的货币升值，当时大家想到的第一个报复手段，就是停止进口美国的农产品，尤其是大豆。

这一招美国人不怕。你不从俺这里进口大豆和豆油，你还去哪里买？因为俺们美国对第三世界很多国家的农业援助，已经把这些农业给折腾得差不多死光了。

你还敢冒着自己国家的农产品上涨的危险，来和俺打贸易战？俺少穿一件衣服，你少吃一顿饭，看谁怕谁？

于是欧洲人说，俺们不拿粮食开玩笑。俺们有另一个狠招，有你好瞧。
