# -*- org -*-

# Time-stamp: <2011-08-24 21:08:13 Wednesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话36：朝鲜半岛的各自小算盘

[2010-12-28 05:38:15]


谈到韩国的大国目标，也许有人会认为韩国人是在意淫。

其实如果仔细看一下，现在的所谓世界大国，一个是以西方发达国家为主体的西方七国集团，和一个是渐渐兴起的新兴国家金砖四国集团。

韩国经济现在是世界排名第12位，比七国集团里面的假货加拿大经济规模要大。

而排在韩国之前的11个国家，包括西方七国的其他六国美国、日本、德国、英国、法国和意大利，和金砖四国中国、印度、俄罗斯和巴西。还有就是金砖国家的未来候选人墨西哥，比韩国稍微靠前，排在第11位。

考虑到金砖国家将来会慢慢形成东方七国集团，就是说和西方七国集团分庭抗礼的一个新工业国家集团，那么在未来的三个候选人当中，非洲的南非（已经要参加明年的金砖国家会议了）、中亚的土耳其和东南亚的印度尼西亚都是候选人。

那么看一下韩国的经济规模，是不是挤进这个集团的实力还是有的？而且说不定，人家这边做个动作，七国集团马上就招手呢。

考虑到加拿大这个假货，靠着和美国的关系，被滥竽充数混进了西方七大国集团，那么人家韩国，如果可以解决好朝鲜半岛统一问题，人口基数可以和英国、法国等对比，如果经济好好搞的话，那么也有可能可以超过意大利，而达到英国那样的水平。

要是韩国可以紧跟中国这个东方七国集团的老大，那么顺理成章，像加拿大跟美国那样，跟着中国走，那么在东亚经济成为世界中心的时候，做上这么一个位置，也可以说是众望所归。

考虑到韩国历史上的“事大主义”的传统，外部有一个没有解决的统一问题，整个大环境处于一个超级强权势力衰落，另一个超级强权势力逐渐上升的阶段，出现国内势力的观点分歧，是继续紧跟现存但是衰落的强权，还是做好准备迎接新崛起的强权，肯定是个很自然的现象。

在这个现象中，因为现代民主选举制度的原因，出现政策上的摇摆和反复，自然不是怪事。而在韩国的民意之中，以40岁作为分界，年纪大的比较亲美，年纪轻的比较亲中，也是很明显的事情。

在中国和美国两大强权的博弈之中，韩国如何左右逢源，在夹缝中寻求利益的最大优化，自然是理想的上上之选。那么在实际运作中，如何做到局势可控，一方面尽量不要恶化和中国的关系，另一方面不把自己彻底变成美国的一个工具，是当前的亲美派韩国政府，需要把握的尺度问题。

当李明博政府，在对朝政策上，走跟随美国的紧密道路，期望的自然是美国可以在军事上和经济上支持其军事接管朝鲜的计划。而考虑到韩国总统是一届任期制，如何在2012年选举中，保证大国家党的政策可以延续，是需要间断性的恶化和朝鲜的关系，同时在大众民意中，导致仇视朝鲜的人口比例增加。

而朝鲜的各种举动，自然也有这个政府换届的考量。那么如何在松松紧紧，张张驰驰之间，影响这个选举。

所以最近一段时间，韩国显示出强烈地挑衅姿态，是因为韩国民意中挑起的仇视朝鲜情绪过猛，你不表示强硬，就得引咎辞职而下台。而这个时候，朝鲜表达出容忍的态度，也是避免局面彻底失控。

下一步，就是韩国军方必须跑到北京，给中国交一个底，然后相关各方会自己制定对策，来保证情况可控。

而对朝鲜来讲，相比于韩国的军事接管，把朝鲜统一在自己的主体政权之下，朝鲜知道自己在经济和常规军力上处于逆势，所以统一主张就比较现实。

朝鲜的主张，其实就是一国两制。简单说来，就是一个国家，一个民族，但是两个政府，两种制度。在以前，朝鲜的主张，和韩国一样，都是一个国家，一个民族，一个政府，一种制度，就是俺吃掉你。

现在因为韩国占强势，所以主张是要共容共荣。

但是一个先决条件，就是你不能是一个殖民地傀儡政府，外国驻军，就是美军，必须走路。

其实这个条件，也应该是中国的先决条件。

*朝鲜半岛要谈统一，第一条就是外国驻军，必须退出这个半岛。第二条，就是必须以和平方式解决，不许一个吃掉另一个。*

当然这个韩国人自己打的算盘，和美国打的算盘，又要差很远。

人家美国人怎么肯把这么一个好地方给放弃？在东亚的军力，还要用来在几个国家（包括中国），进行讹诈和抽血，来挽救帝国经济呢。

*如果美国不肯走，那么朝鲜半岛，就只能维持现状，保持军力平衡。朝鲜统一不了，美国是罪魁祸首，不要赖到中国头上。*

因此现在看维基泄密中，关于几个中国外交官的看法，确实是证明中国政府里面，脑残的混混是多了。

什么可以接受韩国主导统一，可以接受作为美国军事盟国的统一的朝鲜半岛之类，简直就是出卖中国的地缘利益了。

*中国的主张其实可以很简单。*

第一，  就是要和平，不要战争。任何单方面非和平的方式，改变半岛现状，都是不可接受的。

第二，  就是统一是朝鲜民族自己的事情。外国势力必须退出朝鲜半岛。

第三，  就是统一的朝鲜不允许参加任何外部军事同盟，尤其是针对中国的军事同盟。

第四，  就是统一的朝鲜，必须成为中国的全方面的战略伙伴。

要是这样几条做不到，那么就是维持现状。

不过日本的新防卫计划，算是借船出海，倒是必要一番深意。
