# -*- org -*-

# Time-stamp: <2011-08-23 18:51:58 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE:  闲话4：药品是要拿来害人的


[2010-10-02 07:16:02]

有朋友说，你对转基因的态度是不对的。不能把转基因食品，就给放到了垃圾食品一栏去了。

说是，你要相信俺们科学和俺们科学家的良心啊。

现在有一个好处，就是搞转基因鱼、转基因肉的公司，还是一些小公司。孟山都等等大巨头还在忙着横扫全世界，把它的 *大豆* 、 *玉米* 和 *西红柿* 等等，向全世界推广了。

而最近刚刚有研究机构，发现在种植转基因玉米的美国中西部，玉米产生的杀虫和杀草蛋白质，已经通过雨水等等，流入了附近的所有河流。

这些蛋白质对其他生物、植物和生态环境的影响，现在还很难判断。

但愿俺们是幸运的，因为你只要在网上查一下孟山都和生态灾难这两个词，你会吓得从座位上跳起来的。

这两天的一个新闻，就是在美国Wellesley大学的一个研究者Susan Reverby，发现了一些秘密的没有公开的材料，然后就爆出了美国政府和科技界的一个丑闻。

说得是， *在1930年* ，美国有一个很要命的流传病，就是梅毒这种性病。因此当时的医学界就想试一下可不可以用青霉素来治疗这个病。

想法好得很吧？于是在美国政府的支持下，美国医生们派出了一个医疗队到了中美洲的穷国危地马拉，说是要开一个治疗梅毒的诊所，来援助贫穷和苦难，没有得到适当的医疗的当地人民。

然后在美国国家卫生部和泛美卫生局的支持下，当时的危地马拉政府也同意，就把这个医疗诊所给开起来了。

这个诊所干什么呢？就是用美国政府的钱，请了一帮妓女，然后检查一下看这些妓女有没有性病。如果有，好极了，如果没有，就帮她们种上去。然后就让这些妓女去服务军队的士兵和监狱里的囚犯，把这些性病传染出去。

据这些记录记载，大概超过1600人被美国有良心的医生们有意的传染上了性病，其中696个被染上了梅毒，772个被染上了淋病。

当然这些做法，都是瞒着所有当事人的。

结果就是用青霉素去试验一下，看有没有效。如果没效的话，你就自求多福了，反正第三世界国家的人，还能算是人吗？

大概有三分之一被美国政府传染的病人，没有得到合适的医治。而这些人又结婚，生孩子，把性病就一直传播了出去。

这个试验进行了2年。然后差不多类似的试验，在美国阿拉巴马州的Tuskegee进行。

大概在40年的时间里面，从1932年开始，一直到1972年曝光，这个试验选择了超过400个黑人男人被染上了梅毒之后，打着扶贫，医疗下乡之类的政府计划的幌子然后谎称给人家免费医治，但是其实什么药都没有给。

这个研究是看一下如果不治疗的话，梅毒会如何影响一个人的健康和如何传染给家庭其他成员。这些没有得到任何治疗，但却以为被政府治疗的黑人，当然就不乏把性病传染给了妻子，甚至是新生儿身上。

想象一下当时在黑人民权运动之后，很多黑人对美国联邦政府是充满感激之心，因此对联邦政府名下的医药下乡，是很信任的。当这个真相后来暴露之后，黑人们的怒火可想而知。

这些都是在被美国政府认为垃圾人类的身上进行的试验。不过不要以为你是高级人类，就会运气好一点。

另外发生的一件事，还和中国有点关系。

话说在朝鲜战争结束之后，发生了一件让美国政府非常下不了台的事情。

那就是在参战双方交换战俘的时候，有21个美国战俘拒绝回自由民主的美国天堂，自愿选择了居住在“邪恶”的共产主义国家。

这个事件给美国政府和军队造成很大的震动。大家研究的结果，就是这些共产党人发明了一种心理控制的方法，可以洗你的脑而控制你的思维和行动。

于是美国政府出钱，让美国一流的心理学家们研究怎么去控制别人的脑袋，而这个秘密研究项目，是以美国和加拿大的公民为主，是在美国第一流的大学哈佛大学开始。

这次的白老鼠，不是他们眼中的垃圾人类，而是美国白人中最精英的精华，就是上哈佛大学的新入学学生。

试验的主要目的，是要发现方法来影响和控制人的脑袋，然后可以找出好的方法，让中情局和其他美军情报部门可以在审讯中，把情报从顽固的囚犯那里给撬出来。

当然其他的目标，就是如何发明一些药，给当时的美国左派人士偷偷放到咖啡里面，然后你吃了之后，会刺激脑子冲动和非理性的思考和行动，从而让你在公众面前说的话和做的事，神经兮兮的，因此你的信用破产就破产鸟。

还有就是在咖啡、香烟、食品等等里面，稍微放一点，你吃了之后就眼睛模糊，浑身乏力，头脑开始不清醒，人家问啥，你就老老实实说啥。

当然有的方法，就是用语言上的侮辱，还有性虐待，来达到你屈服的目的。

诸如此类的东西，俺们后来都在关塔纳摩监狱、伊拉克和阿富汗的美军监狱里面看到。

不过当时美国政府用来试验的，是能够有机会入学哈佛大学的高材生。

其中有一个高材生，是一个神童。在16岁的时候进了哈佛大学，然后就在这个计划下饱受折磨，令其心智的发展，出现了爱走极端和对美国社会的仇视。

后来拿到博士学位后，这个天才在25岁的年纪，就成了世界级名校伯克莱加大对助理教授。然后他辞职不干了，在许多年后成为了举世闻名的邮包炸弹。

在这样的背景之下，你要俺信任那些转基因公司搞出来的转基因三文鱼？
