# -*- org -*-

# Time-stamp: <2011-08-24 11:10:25 Wednesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话27：谁来花钱和花在哪里

[2010-12-06 12:53:55]


有读者要求，希望俺对中国农业的发展，好好发表一下意见。

但是俺并不是农业专家，更不是中国农业专家，所以很难把话说到点子上。

因此也许将来有时间了，俺会补交这个课题。那么现在就大致简单地说几句，希望有兴趣的朋友，可以自己在这方面好好做一下功课。

要说一下农业，先说一下，关于中国的京沪铁路，突破了新纪录，就是每小时，可以跑486公里。

当然明年或者后年京沪高铁通车之后，也不可能是在这个速度上运营。但是以中国高铁技术的突飞猛进，5到10年之后，也许500公里一小时，并不是一个梦想。

*那么这个速度对中国的区域整合是什么样的影响？*

看一下上海吧。从上海到安徽合肥，大概就是470公里左右。所以说， *一小时经济圈* ，就会把长三角扩大到安徽的合肥和浙江的温州，这么一个包括2亿人口的大区域里面。

那么如果你以500公里作为一个尺子，从合肥到郑州，从郑州到石家庄，从石家庄到呼和浩特，从北京到沈阳，从沈阳到哈尔滨，从郑州到西安，从西安到兰州，从西安到重庆，从重庆到贵阳，从贵阳到昆明，从贵阳到南宁，从南宁到广州，基本上，西宁以东的中国所有大城市，都基本处于1-2小时的交通距离之内。

在这种情况下，中国这些地方的任何一个农村地区，大概到最近的一个大城市圈，基本上都会在1小时之内（如果乡村公路修完了之后）。这个才是对中国农业影响最大的地方。

因为你要是真正的了解农业，你就明白， 真正的农业生产率的大幅度提高，并不是包干到户，家庭联产责任制等等这些制度上的变革。 *真正的农业生产的飞跃，其实在于城市化的发展，从而在城市产生的生产和服务工具，被运用在了农业之上，而导致了农村的大发展。*

*而这些发展，不光是农业生产的科学育种、综合种植，而且更重要的是，对农产品的初级加工、储蓄、冷藏、保鲜，农产品投放市场中的运输等等，都必须来源于城市在技术和服务上的提供。*

为了保证各地人民的基本生活需要，非常明显的一个行政办法，就是让各个城市的市长，管好自己地方的菜篮子，然后各个省的省长，管好全省的米袋子。

但是这样的做法，对发展一个统一的国内市场，并不是长期有效，只是属于临时抱佛脚，明天要考试，今晚才熬夜的法子。

其实中国可以做到的是，就是建立 *在高铁技术上的区域化* ，发展针对城市圈的蔬菜基地，由国家基金主导，农业部下属的专业服务公司，为各个地区的农民提供初级和中级加工服务，这样才可以减少中国农产品从农民手里到消费者手里， *中间环节太多* ， *利润盘剥层次过多* ， *流通环节消耗太大* 的问题。

不解决好这个问题，这些基本民生品，估计就一直变成社会稳定的一大隐患。

如果对这个领域，有兴趣的朋友，要是想投资和发展这方面的生意，应该是比较有前途和钱途的。这种利己又利人的商机，是应该好好利用的。

而对这个领域，只是有兴趣研究的朋友，俺倒是推荐可以去看 *Jane Jacobs* 的著作，尤其是《 *城市经济学（The Economy of Cities）* 》。她的研究，主要是西方和日本的城市发展经验。

其实俺倒是希望了解一下中国北宋时候的汴京，和南宋时候的临安，因为大规模城市化，对当地农业生产方式的影响。如果俺没有记错的话，中国的农业专家曹锦清老哥应该对南宋农业的研究比较深，可以好好阅读一下。

当然保证粮食安全，除了把自己的农业产出、流通等领域优化，另一个办法，就是到海外土地比较富余的国家去圈地。

这些地方，有美洲的巴西等国家，有非洲大陆，有南亚的巴基斯坦，东南亚的老挝和柬埔寨等等，都是可以好好考虑的。以中国农业技术的高超，这些地方都可以成为中国的粮食生产基地，在满足当地人民的食物供应之后，还可以解决中国的粮食短缺问题。

前一阵子，俺谈到过货币政策和财政政策，在推进经济发展中的不同切入方式。

现在看来中国和美国这两个世界最大的经济体，似乎要走不同的路子。

那就是中国正式宣布走出了萧条，开始从财政和货币两宽松的方法，走向了财政放松和货币收紧的政策。

而美国在仍然在试图走出萧条的中间，开始从财政和货币两宽松的方法，有可能走向财政收紧和货币宽松的政策。

俺曾经描述了 *财政和货币政策的不同侧重点* ，简单地说，就是财政政策基本上是两个路子。一个就是政府工程，在中国，就是铁（路）公（路）鸡（机场）大干快上。另一个就是民生工程，发钱给大家补贴。

货币政策基本上，就是谁来借钱，俺不收或者少收利息，你们使劲地往外贷款吧。

从另一个角度来讲，财政政策可以说是政府主导，而货币政策可以说是私人资本主导。

市场万能者，是很反感财政政策的。因为人家相信，一个 *经济上的歌德巴赫猜想* ，就是市场会有效率地解决资源配额问题，而政府，就是乱花钱。

不过要是情况真那么简单的话，美国就不需要搞QE2了，因为你QE1就应该达到效果了嘛。

其实前一阵美国经济的恢复，尤其是就业问题上，很大程度上来源于美国政府的财政投入，简单来说，就是几大动作，一个是现金换旧车，一个就是打丰田救三大国营汽车公司的命，一个就是人口普查请人，一个就是初次买房者补贴，一个就是联邦政府拨款防止地方政府裁员。

而 *美国要走紧财政放货币的政策，就是希望政府干预退出，而由私人资本出面来完成这个复苏过程。*

*当然这个政策的危险之处，在于你这个接棒能不能顺利完成。如果转不成的话，就等着二次探底吧。*
