# -*- org -*-

# Time-stamp: <2011-08-26 11:53:36 Friday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话33：政府付账，谁来买单？

谈到美国在阿富汗的困境，还忘记提到了美国著名外交家霍尔布鲁克的不幸离世。霍老兄，大概是美国硕果仅存的几个真正的外交大才，他的去世确实是对美国外交实力的一大损失。说真格的，这样的人才是对世界和平多有建树的人，可惜那些号称和平奖的东东，开始变成了炸药奖，不是在为鼓励和平，而是在鼓励爆炸。

当然老霍空出来的位子，大概很难找到人来填补。现在美国驻阿富汗大使艾肯伯里，和阿富汗总统卡尔扎伊的关系，基本上是水火不容。如果把阿富汗裔的哈利勒扎德在给请回来，也许有助于改善他和卡尔扎伊这个老伙伴的关系，可是哈利勒扎德和巴基斯坦各界的关系，是另一个水火不容，基本上就会把美国政策带回奥巴马上台之前的瘫痪局面。

回头谈中国经济的问题，其实就是2008年的后遗症而已。

当2008年美国的金融危机向全世界蔓延的时候，当时大家采取的就是一个法子，就是 *政府付钱来填坏帐* 。

所以俺说这是政府把坏帐这个铁牛，从金融界接了过来，自己给抗上了。

那么今天就是各国政府抗的铁牛，现在要找一个解决的办法。

这个办法，就是要 *全民来承担这个责任* 。于是以欧洲为主的国家，开始实行 *紧缩财政* 政策。这个政策，就是政府出了钱给银行家们填窟窿，发奖金，那么这笔钱，只好要从政府的支出里面减出去了。

*所以法国要拿退休福利下刀，英国要增加大学学费3倍，四个小猪国家，也要紧缩日子。*

而同时又是 *货币宽松* ，就是说银行家们可以拿更多的钱，希望他们的私人投资，可以填补政府财政紧缩的空缺。

美国其实也是在走同样的路子，不过现在要求财政紧缩的势力刚刚开始占领权力的位子。而美国联储局忙着干的是，如何在美国和全世界人为制造通货膨胀，从而让全世界人民为华尔街的金融家们的奖金买单。

*中国的局面有些不同。中国的金融界受到的牵连非常小，其实真正的风险，还是来源于地方政府变相融资平台，和对中国房地产市场的牵连程度。*

*但是中国真正的风险，是来源于西方各国的信用紧缩导致的有效需求减少，从而导致大规模出口导向的企业倒闭，引发大规模农民工失业的危机。因此中国的四万亿财政刺激计划，出发点是解决这样一个危机。*

所以当时采取的方法，就是先治病保命，然后再应付重药带来的副作用。

而这个副作用，就是客观上为高涨的房地产市场，保了驾护了航，从而导致本来过热的一线大城市的房地产市场，在2009年逆势而上，形成了2010年下半年的社会问题。

至于现在大家颇为头疼的通货膨胀，倒不是那么可怕。

因为你看起来颇为严重的5.1%的CPI，剔除了能源和食品之外，就是核心CPI其实只是1.6%。大家都知道，理想的通货膨胀率，应该是核心CPI在2%。

*那么中国的问题在哪里？解决的办法是什么？*

一个问题，就是食品支出在CPI构成中的比重过大，大概是45%。如果这个比例，没有真实地表达中国普通民众的生活支出比重，那么就应该进行调整，从而准备地反应出经济的实际情况。

但是如果这个比例，确实代表了普通人民的生活情况，那么表明中国目前的国民收入分配体系，必须进行重大调整，要更加向低收入家庭倾斜。要让中国人民的收入中，占食品支出的比重大幅度降低。

*不然的话，发展经济有个屁用。*

*这个就要求，一方面要控制住食品价格，另一方面要增加工资收入。*

*要控制食品价格，不代表着要靠打压食品的收购价格，从而牺牲农民的利益，来保证城市平民的利益。真正的方法，是要靠发展现代农业，提高农业生产率，在整修水利、科学育种、农业机械化、农地集成化等等上面下功夫。*

*还有就是产品加工，理顺农产品到达消费市场的流通渠道上面，让农民更多地享受到增加值。在西方国家出现的“Fair Trade”的概念，其实可以运用在这个上面。*

当然政府加大农业补贴，直接高价收购农产品，然后以平价投放市场，这个中国历史上经常使用的平准法，也应该运用。在增加农民收入的同时，保持物价稳定，这样的政府干预，还是需要的。

不过大家要明白的是， *温和的通胀对经济颇有益处* 。如何把通胀预期控制在一个合理的水平，是一件很细微的工作。

因此如果政策手段过重，从而引发经济急速下降，导致对整个经济的冲击，那就是画虎不成反类犬了。

*所以现在的一手紧货币，一手松财政的法子，算是不得已的权宜之计。就是说，一边踩着油门，一边踩着刹车，看路况如何，然后决定向哪边的力可以加大一点。*

倒是看着中国的一帮所谓经济学家们的胡扯，让人只好摇头。

现在有不少人主张通过人民币快速升值，来“便宜”地从海外进口能源和原材料。岂不知要干这个，2009年才是大手笔的时候？

当然那个时候，同样的这帮人，忙着鼓吹大举进军美国国债市场，救美国就是救自己呢。

*中国现在的情况，利率政策和汇率政策，都不宜大动。板子要高高举起，轻轻落下。中国的出口产品，可以适当提价，把原材料和能源价格上涨的压力，转移给全世界。*
