# -*- org -*-

# Time-stamp: <2011-08-24 12:32:46 Wednesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话34：可控和不可控

[2010-12-26 03:00:23]

虽然俺在谈中国经济问题，可是大部分读者，还是在问朝鲜半岛。

*朝鲜半岛的大背景，俺已经说过，就是朝鲜希望和美国直接会谈，签订一个互不侵犯的和平协议。而美国则希望继续利用军事威胁和经济封锁的压力，最终希望达到朝鲜经济崩溃，出现大规模难民潮，用来冲击中国的东北。*

美国在1992-1995年期间，克林顿政府和朝鲜关系有所缓和。当时美国的估计是，金一到金二的权力转移会导致朝鲜崩溃。所以那个时候，所谓“国际社会”的关注和炒作，是中国东北的所谓违反人权的难民政策。

当时的想法，是中国国有企业的大规模破产，许多工人被迫下岗。尤其是在东北这样国企多的地方，失业问题尤其严重，社会稳定前景堪忧。这个时候，海外势力乘机进来，企图发起失业工人搞中国的团结工会运动，而后来出名的某些气功团体也高歌猛进。

这个时候，如果朝鲜崩溃了，跑过来过千万的难民，那就是对中国经济的一大打击。

这一招后来没有起作用，金二最后屁股坐稳了。于是就光荣地进入了“国际社会”的邪恶黑名单的三大魔鬼之一。

第一个魔鬼，*伊拉克* ，被“国际社会”阴谋了一把，没有发展核子计划，却被人用核子武器威胁为借口，给暴打一顿。

那么另外两个魔鬼， *朝鲜* 和 *伊朗* ，就只好发展核子计划，用来防身了。

中国在这个局面中，选择了打酱油的态度，显然是一个愚蠢的政策。

*本来这个政策，如果整个大环境，就是美国对朝鲜的态度改变，采取美国在2000年代以后，对付越南的政策，或者是1978年以后，对付中国的政策的话，那么促进朝鲜和美国的关系正常化，是可行和符合中国利益的。*

*而同时，在朝鲜半岛的小环境下，如果韩国政府采取的是金大中的阳关政策，逐渐脱离美国控制，实现独立自主的外交政策，希望在美国和中国之间采取等距离外交，那么中国也可以促成朝鲜和韩国双方增进合作，减少摩擦，缓和关系。*

*但是在这两个大小环境都不具备的条件下，中国的和稀泥的六方会谈，肯定就会在参加者各自心怀鬼胎的情况下，反反复复，忽悠而已。*

本来人家朝鲜要的是和美国自己双边会谈，人家美国的回答，是谈个屁，你有啥资格。朝鲜的回答是，俺经过多年努力，在种蘑菇上面有些成就，而且中东的叙利亚等国家，对俺的种蘑菇技术很羡慕，希望引进去种。如果你美国，要想维持中东以色列的种蘑菇专利垄断，还是和俺喝杯酒，交个朋友吧。

结果就是找了一帮亲戚朋友，六个人坐在一起喝酒。然后中国这个主人说，俺有点急，去方便一下，结果其他几个也跟着方便一下，就说，朝鲜和美国，你两位先聊着，于是客观上双方会谈还是实现了。

朝鲜说，俺们是双方在谈。美国说，不对，这还是六方会谈。于是大家都可以自圆其说。

既然朝鲜说，俺开发出来的这一大堆蘑菇苗子，是花了不少成本和心血的，俺自己不种了，又不卖到中东，你看多浪费啊！不如，你买？

于是美国转头对韩国说，支票簿带来了？韩国的回答，带来了，不过太贵，可能买不起。

对韩国来说，自从李命薄上任以来，阳关政策变成大炮政策，其中一条主要的变化，就是以前韩国尽量会和中国商量，来协调大家的政策，现在就希望由韩国制定政策，来要求中国协调，变成和韩国一致。

这样的要求，作为判断的基点，就是通过中国和韩国贸易的大幅度提高，在中国出现了一个具有影响力的对韩贸易利益集团。而且韩国政府认定，在韩国的意淫连续剧在中国大热的情况下，韩潮风行，已经在中国的舆论界和政府官员中，形成了一个极度崇拜韩国的群体。

因此在文化战争中，韩国政府认定，已经彻底打败了中国，具有了文化和心理优势。在这种情况下，反正碰到韩国的事情，就夸张地大肆吹捧，把没有那么好的东东，吹到了天上。而对朝鲜的事情，就夸张地大肆污蔑，把没有那么差的东东，给描述成地狱。

而且要是有人对韩国的东东，发出一点不敬的声音，马上又是抗议，又是外交照会。于是中国外交部门和宣传部门的韩国粉丝们，就开始出来封人的口。

这样的舆论一边倒的形势，引发了中国的一些人士自然不满，也导致了日本和台湾某些势力，对韩国用文化优势来带动经济竞争优势的担忧。

于是从日本和台湾的某些舆论，开始制造恶心韩国人的东东出现。其中最有名的，就是韩国人争夺中国名人的传闻。一下子是孔子是韩国人，然后孙中山是韩国人等等，不论是真是假，都在中国恶心了韩国一把。

但是韩国也有自己的小算盘。如果从2010年开始到2015年结束，这个时间段可以算作是朝鲜，从金二企图到金三的转换，不排除朝鲜会发生大规模的乱局。

因为很简单，一到二容易，二到三艰难。台湾从老蒋到小蒋可以比较平稳，你要是再下一城，难度其大。这个在全世界大概都是同理。

那么既然朝鲜经济上也困难，上一次的金融改革也是一大失败。其实在权力转换的过程中，最后是不是金三坐稳，还是由各实力派妥协一个政权出来，都不重要。

*重要的是新政府，可不可以把经济搞好。*

这个时候，朝鲜的 *先军政治，就是军事和国防优先的政策* ，自然是要调整到发展经济为主，那么就要退到第二位。

而这个退却，自然会受到军队和相关利益集团的抵制。从利益上来讲，如何转移到经济建设为主，而不影响军人们的福祉，是一个主要考量。

当然这个是需要和平的环境才可以实现。如果这个时候，与韩国和美国的关系持续紧张，国防没法放松，军队抵制改革的理由增强，那么自然就搞不下去了。

不过这样下去，经济也就跨掉了，是不是？因此这个是一个大悖论。

*因此半岛局势紧张，是对韩国和朝鲜军方有好处的。但是可不可控，是一个关键。*
