# -*- org -*-

# Time-stamp: <2011-08-24 11:59:15 Wednesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话32：新一年又要开始了

[2010-12-23 05:17:22]


记得2010年1月1号元旦，俺开始写《新年展望》，谈到了美国的新年愿望，曾经用戏谑的语言，把《新闻周刊》的10大“预测”调侃了一下。

现在就把这些话列出来，大家看看美国政府的执行能力如何？

1. 美军阿富汗大捷！
2. 中国经济崩溃！
3. 巴基斯坦大乱！
4. 政变推翻委内瑞拉的查韦斯！
5. 欧洲穆斯林和反穆斯林对砍！
6. 伊朗会大乱！
7. 巴西是新中国！
8. 英国经济更加萧条！
9. 欧洲老倌们金融危机又来了！
10.卡斯特罗死掉，古巴又是俺们的了！

第一条，美军阿富汗大捷，现在看来真是发梦一样。美军在阿富汗采取的主要是反游击战术，靠得是政治和外交手段为主，军事手段为辅的法子。

这个法子主要是希望通过军事上彻底打击塔利班，然后把他们逼到谈判桌上面来，最终用政治办法解决阿富汗问题。

*美国的最终目的，是让美军在阿富汗的负担，可以从10万多人，减少到3-5万人，然后可以利用这个军事存在，来遏制中国势力西进。说白了，就是阻止欧亚大陆的丝绸之路的第重建。*

不过要达到这个目的，难度奇高。天时、地利和人和，都不在美国一边。

从天时来讲，美国最大问题当然是现在自身的经济困境。因为经济有问题，不光会导致你用兵的困扰，而且跟着你跑的小兄弟们，也没有了奔头。你说，人家会不会另谋出路？

从地利来讲，阿富汗是欧亚大陆的十字路口，就是东亚、西亚、南亚和北亚的交通要道。因此这个地方，是兵家必争之地，任何想在这里动手的帝国，都在这里挖了自己的坟墓。阿富汗，帝国坟场，这个可不是虚名。

如果美军困在这里，北边是俄罗斯，东边是中国，西边是伊朗，南边是巴基斯坦。虽然这几家，没有一个国家，可以和美国的军力单挑，但是考虑到美国实力衰退，此消彼长，加上中国和巴基斯坦，中国和伊朗，中国和俄罗斯，俄罗斯和巴基斯坦，这一系列的双边关系，都会让阿富汗的美国军事存在，变得很脆弱。

在人和方面，就是所谓赢取民心，winning hearts and minds的行动，并不顺利。因为美国把援助和经济行为，正式归纳为阿富汗对塔利班战争的主要组成部分，因此有政府支持的官方和非官方组织，在这些地区加强了经济行动。

而这个行动挤压了原来中立的国际组织，在阿富汗进行人道援助的空间。因此来自于北约参战国家的各类非政府组织，有些本来是和政府行为完全无关，甚至反对自己国家政府在阿富汗战争的慈善组织，就被塔利班力量，归纳为替北约军方唱红脸的力量。

最近一年来，自从美国的新战略出台之后，不少来自北约国家的慈善组织，遭到了塔利班的打击，从而事实上让这些本来没有意愿配合政府行为，但是实际上做到了收买人心的组织，生存困难。

在外交能力方面，希拉里在美国想非正式变成总统（先出任国防部长，然后做2012年副总统候选人，希望当选之后成为钱尼第二）的愿望，因为维基泄密一事，遭受了巨大打击。

维基泄密，和美国政府之后的下三滥的应对招数，造成了两个后果：

一个是希拉里主导的美国外交系统，基本上失去的各国的信任，从而导致外交行为的困难。这次美国去朝鲜斡旋的是新墨西哥州长理查德森，本来就是当年想出任美国国务卿的最有力人选，最后被希拉里给赶出了局。

而且美国副总统拜登，最近亮相频频，结合他在CNN上对让他再2012年爽快让贤的留言，轻蔑的回复，同时希拉里偃旗息鼓，可以看出奥巴马政府的软实力外交，受到了一定的损害。

另一个就是以希拉里为首，希望利用美国政府对谷歌、youtube、twitter、facebook等新网络工具的控制，以互联网言论自由为旗号，通过新技术手段，对中国、俄罗斯和伊朗等国家发动攻势，而同时对欧洲等国家，采取信息监控的行为，因为对维基泄密的应对，从而导致这个攻势破产。

不光是欧洲国家，开始围剿谷歌，企图把欧洲的信息控制权重新夺回来，世界各地的网络黑客，也在近期内把美国政府作为人民公敌。

本来要用言论自由来打击别人，最后搞得美国自己成了被打击的最大对象，真是对希拉里的一大讽刺。

而且美国政府，对阿富汗周围环境国家的期望，全部落空。

首先是中国的经济没有崩溃。当然喊中国经济崩溃，已经喊了30年了，再喊出笑话，也不是奇怪的事情。

对中国经济乱发表意见，当然是政客们的一种意淫。但是其中也不乏所谓的学者和专家，尤其是所谓基金的牛叉经理们，号称预测了当年亚洲金融危机和美国金融危机等等的人，也出来胡说八道。

很简单，这些人的基本认定，是在于他们对西方模式的经济运作的特点，来作为结论。说到底，连中国历史都没有读过的人，来分析中国情况，那只能是笑话。
