# -*- org -*-

# Time-stamp: <2011-08-24 10:56:22 Wednesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话26：独立自主和全球化

[2010-12-05 02:50:00]


看来美国在东亚的大动作，已经有点收成回来了。本来奥巴马在G20开会的时候，搞不定的美韩自由贸易协定，终于在要和朝鲜开战的威胁之下，顺利签署了。

这个可以看做是第一笔保护费吧。

这个协议，主要是要解决韩国市场对美国产品开放的问题。要开放的市场，主要是两个，一个就是美国现在大力扶持的三大国有汽车企业，需要在韩国市场上攻城拔寨主。另一个就是美国的农产品，尤其是荷尔蒙牛肉，要占领韩国市场。

上次讲到1970年，美国对欧洲实行的货币战争，其中一个主要目的，是要逼迫欧洲各国，尤其是北欧各国的货币升值。

但是没有提到美国的第二个目标，就是要打破欧洲的农产品市场保护。当时欧洲的农产品市场，是靠各国之间的货币稳定解决的。美国的目标，是靠打破欧洲人的铁索船政策，就是靠逼迫北欧国家的币值，和南欧国家的币值之间的差距扩大，而将欧洲国家的农产品市场一一攻陷。

如果考虑美国的全球战略，就是著名的海权战略学家马汉的论点，控制全世界的主要交通通道。

这个战略，其实不是什么新东西。中国古代的匈奴，也是走的这么一条路子，就是靠控制河西走廊和丝绸之路的各个关口，来收买路钱。

美国的海军布局，基本上控制了世界上的主要交通咽喉，但是要是人家所有的国家，都给你来个自给自足，就是说，如果你自己国家生产的东西，就满足自己国家的需求，那么贸易一下，也不过就是锦上添花而已，对人家国家的基本经济生活没有多大影响，那么你控制这些交通也没有多大屁用。

当然一个国家，要自给自足，是有一定难度。但是要是人家几个邻居，大家互相补充一下，用来自保，那么也达到差不多的目的。

因此，为了防止这个局面出现，就是说人家美国花了大钱建造和维持的全世界关卡，要发挥作用，你就必须打破各个国家，独立自主的经济发展模式，或者各个地区，要搞区域整合的抱团取暖发展模式。

*这个就是全球化的利益基础。*

当然不是说全球化，没有其他的用处。比如说，国际分工和资源配置等等，都是全球化鼓吹的所谓地球是平的，俺们大家都住在一个地球村的观念。

但是这种虚假的说辞，并没有解决全球化华丽外衣下面的残酷事实，就是这个全球化，必须是更高效的维护目前国际经济分配格局的不变。

所以说，你必须有无限制地国际资本流动，但是你必须限制国际劳工流动。因为很简单，操纵做国际储蓄货币的国家，可以用无限制地的国际资本流动，来获取超额利润。但是具有大量人口贫穷的国家，却不能靠送出廉价劳动力的人口去发达国家，去分享全球化的红利。

因此墨西哥和中南美洲的非法移民，中国福建的偷渡客，北非非法到欧洲的移民，都是人家要限制的对象。

然后理直气壮地反对无限制移民的国家，同样理直气壮地反对你发展中国家，对国际资本（就是人家的资本）不能任意进出你的国家。

或者就是发达国家，理直气壮地要求你必须遵循人家已经建立起来的知识产权保护特权，要求你老老实实地交付使用费。但是又同时理直气壮地控制技术转让，用贸易壁垒来防止你的发展。

全球化的结果，就是没有一个国家的经济，可以闭关自守。你的经济要想运作正常，就必须和其他国家进行大规模的贸易活动。

而你要进行这些贸易活动，就必须通过所有美国海军控制的关卡。

于此相配合的战略，就是控制资源产品。在这些资源产品中间，有两个是最重要的，就是北京奥运会主题歌大大声唱出来的：

*油和米。*

油，狭义地来讲，就是石油，或者说能源，包括铀矿、天然气等等。广义地讲，就是包括铁矿石、铜矿，还有稀土等等资源。

米，狭义地来讲，就是粮食。广义地讲，包括主要的民生消费品，包括大豆、棉花等等。

而美国外交战略的一大目标，就是要垄断世界的粮食市场，通过全球化分工的意图，劝说其他国家，你自己种粮食，是经济上不划算的，是让你的城市消费者吃亏的。

不如俺供应你便宜的粮食，然后你的农民种一些经济作物，比如说香蕉之类的，那么不是大家共赢？

于是很多国家，比如说海地这样的，就不再具有粮食自给自足的能力了。于是前几年，当美国决定，俺们要烧粮食来开汽车的时候，世界上有不少种经济作物的国家，就出现粮荒，大家上街暴动了。

当然不是所有的国家，都会傻成这样。最起码欧洲的国家，对这一招是心知肚明的。所以欧洲出现的货币统一制度，其中的一个重要基石，就是欧洲自己的农业政策。

大概大家不知道，欧洲大部分国家，都是农业发达国家，而令人想不到的最发达国家，是法国。

在这些国家里面，是不大会听到所谓张口就乱喷，要虚弱欧洲国家的农业能力，让国际市场，特别是美国政府，来控制你的粮食供应的。

不要以为城市化和工业化，就一定会带来农业的衰弱。其实历史经验给出了相反的答案，真是因为城市化和工业化，才会带来农业从传统耕作，到现代农业的发展。
