# -*- org -*-

# Time-stamp: <2011-08-24 11:53:52 Wednesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话31：大家都在混日子

+ (上)

[2010-12-19 09:10:08]


看来今年早些时候，俺是寄希望于中国一线大城市的房产，可以降低30%，起码是冲销掉2009年的涨势，还是对国务院的决心或者说能力太乐观了一点。

至于二线城市以下，俺从来没有觉得会出现降价，尤其是沿着新开发的高速铁路一线。

不过现在回头看了一下，俺在2009年8月2号的一篇评论，是明显带有对这一届国务院的疑虑的。

应该说，对一线大城市，比如说上海、北京和深圳等地，在今年的第二个季度，还是出现了轻微下跌的拐点，但是这个拐点，因为后继政策跟进不佳，导致了之后的房价反弹。

也许这个政策变化，同当时做的银行压力测试有关。一种可能就是当时放出的风声，就是说银行在搞30%房地产的压力测试，也是一支疑兵，是想打击房地产炒风。另一种可能，就是一查银行，发现资金平衡表外面的猫腻太多，没有搞清楚，不敢下重手。

当然另一个就是城市皮包地产公司，就是地方政府的融资平台，带来的欠账到底是多大，估计也是颇有争论。

记得看到总理在美国有线电视的采访上，说是有1万多亿美元的各类政府债务，要是真实数据更大的话，只能采取时间换空间的法子，看是不是可以靠经济增长来消化。

*总之土地财政不解决，大城市的高房价就没有根治的法子。而要解决土地财政，那就是回到了两个字：削藩。*

*廉租房* 和 *经济适用房* ，可不可以起一个减压阀门的作用，是以后两年的关键。选择部分城市的部分地区，进行定点爆破，也是一个防止总爆炸的操作手段。

但是关键的关键，在于要搞好文宣，在资本的狂欢盛宴之中，作为人家盘中餐的小民，不要去起哄。

因为现在不少所谓卖出去的房子，其实是空置没有人住的。既不是人家买来自己住，也不是买来租出去，只是空在那里，作为所谓保值的投资而已。

所以这些空置的房子，是没有投入进房地产交易市场，客观上对租金的上升形成压力，也对新房屋的销售产生推波助澜的作用。

要是真的想赶一些二手房子出来，只有规定 *如果5年没有人住的空房，考虑征收房屋空置税等等* ，估计就可以起到一点作用。当然你要是赶出来太多，会形成房地产市场的崩盘，也不是好事。所以不是说真的没有办法，而是现在的一届政府，可以说是跛脚政府，反正过两年要交接了，自己干嘛惹那么大麻烦。

倒是下一届班子，还有10年的日子要熬，现在不动手，等到了自己坐在火炉上面烤的时候，那就是别有一番滋味在心头了。

而问题的关键，就是看明年你的经济适用房和廉租房可不可以到位。如果还是像这一届政府这样打酱油，做维持会的话，那以后的日子可不是那么好过的。

+ (下)

[2010-12-22 05:19:27]

其实俺认为，中国大城市周边的中等城市房价的上涨，是一个好事。

虽然看一个地方的房价，你可以用中位价作为一个衡量的标准，但是就是在同一个城市，不同的区域，房价还是有差别。

不知道现在中国的情况怎么样，但是在过去，上海曾有一种说法，叫做“令要浦西一张床，不要浦东一间房”。在美国这里，也是一样。有一些地方，比如说奥克兰的好区，房子要超过1百万美元，但是在差的地方，和你房子差不多大，估计是10万美元都不到。

*因此问题在于，大家并不是所有的房子都买不起，而是自己心仪的房子买不起。*

也许有许多房子，其实是可以买得起的，只不过因为交通、社区等等不同的因素，让这些地方的房子，变得没有吸引力了。

所以如果中国的 *高速铁路* 和 *同城化* ，可以推广得好一些，以前一些城市外面的边缘地区，就会变成有吸引力的地段了。

当然这些地方的房价会有一定的增长，但是伴随着价格增长的同时，也是居住质量和社区发展水平的提高。

比如说上海的房地产均价，大概是2万3的水平了，而周边的城市，比如说嘉兴和湖州，大概房地产的价格，是8千左右。因此如果你的城市发展搞好了，同城化趋势起来了，这些地方的新建房屋，就会对上海的房屋起到一个均价的作用。

就像中国的社会一样，大家都认为贫富悬殊是一个大问题，需要搞收入分配调整，就是要 *均贫富* 。那么中国的房价也是一个问题，需要搞价格调整，也是要 *均贵贱* ，让本来便宜的房子高一点，让贵的房子便宜一点，这个才是真正的房地产健康发展的出路。

要做到这个，就要 *解决社会资源向大城市倾斜的问题* 。促进大国企向大城市周边迁移，从而把一些高薪工作迁移出大城市。然后就是在教育、医疗和通勤方面，好好发展中小城市，这样就可以把现在的一线大城市的房屋崩盘风险降低。

等到中国的二线城市，房屋市场发展起来，也不怕你上海房地产崩盘，是不是？

*在中国，把食品价格看住，就基本解决高通胀风险。下一步的转型，一个大的重点，就是把农村给盘活，所谓发展新农村的问题。*

在这个发展规划上面，其实中国有很多现成的例子，可以借鉴。主要的案例，是日本、韩国和台湾农业发展的经验。

*解决农村发展的观点，除了送电下乡、送车（电动汽车和电动摩托）下乡之外，村村通、路路通，是保证人流和物流的基础。*

*在这上面要发展的就是宽屏上网，解决信息流，以及金融下乡，解决资金流。*

*当然金融下乡，引发的土地流转，如何保护农民能够获取土地转型，就是从农用地，到工商用地和居住用地，所带来的高附加值，是这个发展能不能成功的关键。*

*如果搞好了，农民和地方政府的收入都有了保障，如果搞不好，再变成一个圈地运动，那就大家都做好准备，一起玩完吧。*
