# -*- org -*-

# Time-stamp: <2011-08-23 19:17:54 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话6：为啥美国的前景黯淡

[2010-10-14 11:10:26]

本来是要接着谈美国的黄巾军的，但是还是想把这一段关于美国前景的闲话先说完，然后大家就明白美国黄巾军的危险性。

其实这段闲话，可是一点都不闲。看懂了这一段话，不光是可以明白美国的未来走势，而且还会明白中国的未来走势。

有人批评俺对于中国的前景过于乐观（虽然俺本身是谨慎乐观），和对美国的情景过于悲观，那么看了这一段闲话，应该可以了解俺判断的主要来源。

要搞清这个关联，先要从一个人谈起。

这个人叫做艾克斯（Marriner Stoddard Eccles），大概不是太多的人知道这个名字。

怎么说呢？艾克斯于1890年出生于美国的犹他州，家里是摩门教徒。他老爸去世之后，22岁的他重组了家族的银行业务，当时就变成了百万富翁（想一想1910年代的1百万美元，那是很值钱的）。

作为美国有名的年轻企业家，在1929年发生的大萧条打破了艾克斯对一直信奉的经济理论和信念产生了怀疑。于是他在经过了仔细的研究和观察之后，提出了自己对当时美国经济发展的基本看法。

大家知道，美国在1920年代，就是第一次世界大战结束之后，经历了一个Roaring Twenties的突飞猛进时代。在这个时间段里，美国的制造业大幅度发展，劳工的劳动生产率大幅度提高。但是大部分的经济发展的收益，没有通过劳工工资的大幅增长而让工薪阶层受益，而是大部分以企业利润的方式，进入了资本家和企业家的腰包里。

这样就出现了两个大问题。一个就是 *制造业规模和产能的大幅扩大，而造成供应过剩* 。另一个就是 *劳工收入增长缓慢，造成工薪阶层消费不足* 。

*于是为了解决这个问题，就开始了以分期付款方式出现的信用消费模式。*

这种情况导致的后果，就是美国经济出现了两个大泡沫。一个是有钱人钱多得没有地方去，于是房价和股价成了他们炒作的主要战场，出现了 *资产泡沫* 。

另一个劳工阶层的借贷消费，造成了 *债务泡沫* ，

*然后1929年的纽约股市爆破，导致了两个泡沫一起破碎。美国经济陷入萧条。*

看明白了这一点，艾克斯在美国国会主张，美国要采取政府干预的公共财政支出，而且要提高最低工资制（之前美国最高法院判定最低工资制违法美国宪法）。

要知道艾克斯的这个主张，其实比凯恩斯提出来的要早，而且本来美国的小罗斯福总统，还是个预算平衡者。

然后艾克斯就于1934年到1948年期间出任了美国联储局主席，算是领导了小罗斯福的新政，成立了FDIC联邦银行保险系统，还在后来出现的布莱顿森林协定、国际货币基金会和世界银行的成立上面，立下不少功劳。

那么这一段历史对美国和中国的今天，有什么意义？

那就是中国现在的经济结构，与美国当年非常类似。中国也有产能过剩，也有劳动生产率大幅提高之后，劳工阶层获得的红利太小。

不过中国还没有出现信用费用的借钱消费，中国政府也开始在最低工资制，工人集体薪水谈判制度等等上面有努力，基本上走的是类似小罗斯福新政的正道。

因此俺对中国的乐观，是建基在这个历史对比上的。如果你觉得中国现在的社会问题严重，那你还得真要研究一下美国当时的状况。

那时的美国，黑手党盛行，各类社会精英如医生和牧师参与非法酒的生产和销售，社会群体事件层出不穷，出现多个州的武装民众占领政府事件，退伍军人游行示威被军队镇压，人民决定用枪到银行挤提，各种抢银行的大盗兴起，其事迹被人们广为传诵。

而黑暗的奴隶制仍然在南方秘密进行，黑人和其他少数族裔仍然过做非人一般的生活。

但这些问题，都没有阻碍美国的崛起，而罗斯福的新政起了决定的作用。

而中国今天的情况，要远远好于当时的美国， *只要中国政府可以把分配体系调整，解决分配不公平问题，没有理由相信中国的情景会黯淡。*

而美国相对于那个时代，却是非常不同。

不过有一个情况相同。那就是在美国历史上，只有两个年份，出现社会财富的极度不平均。

就是说 *美国最顶端的1%的收入水平，接近了美国整个国民收入的25%左右。*

这两个年份，一个是 *1928* 年，一个是 *2007* 年。

*其实严格来讲，扣除通货膨胀因素，美国的工薪阶层的收入，从1970年代开始后，一直是实际下降的。*

就是说今天的美国人，其实收入的实际水平是低于他们的父辈。

*为了解决收入不足的问题，美国社会采取了3个方法来补偿。*

第一个就是把老婆赶出去干活。在1970年，有幼儿要照顾的母亲而必须出外工作的妇女，只占总的母亲人数的20%。但是到了1990年代，已经提高到60%。

这个就出现了所谓的 *DINS家庭* （Double Income，No Sex），就是夫妇忙于轮班工作，连性生活都要让步的双职工家庭。

第二个就是 *增加工作的时间* ，加班加点。美国工薪阶层大概每年比欧洲工人要多干350多个钟头，甚至比日本要多干50个钟头。日本工人从1990-2000 年，比以前少做了191个钟头，而美国工人增加了37个钟头。

这些补偿方法，都没有效果之后，第三个方法出现了，那就是 *用自己的房子抵押来贷款出来消费* 。

而和大萧条时代同样的故事，就是财富集中在了少数人手里，大家就拿去炒资产泡沫，不光是房产和股票，还包括新的金融衍生品。

结果就是资产泡沫和信用消费泡沫一起起爆。

*那么在泡沫爆破之后，美国政府干些什么？就是要救市。*

第一个市场是 *资本市场* ，就是股票和债券市场等等。在这里的人群基本上是有钱人，是最可以经受到财务损失的人们。

第二个市场是 *房产市场* 。可以说很多中产阶级的大部分身家都在房子里面，房子一缩水，那就很痛苦。

第三个市场是 *就业市场* ，可以说这个是所以工薪阶层的根本。不管你是蓝领还是白领，没有这个市场，就很麻烦。

可是 *美国政府救了资本市场，而没有救就业市场和房产市场，因此美国的贫富悬殊，会更加恶化，比2007年还要恶化。*

