# -*- org -*-

# Time-stamp: <2011-08-24 10:18:41 Wednesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话21：其人之道，还治其身


[2010-11-22 14:11:51]


在谈中国的七伤拳之前，先要回答读者一直问的问题，就是 *小川老兄说的中国的池子是什么？*

首先，俺说过最好的蓄水池是你的邻家大院。结果后来看到 *印度* 央行的领导们说，印度要达到赶超中国的计划，首先就是要GDP增长速度先赶上。你中国是9%，俺们就得2位数，是不是？

而要达到这个增长速度，印度需要大批的外来投资。俺们欢迎外国游资。

印度去年的财政年度，外来资金流入量，大概是536亿美元。今天就达到了913亿美元，增长了70%。因此印度现在大概就吃掉了1千亿美元的货币增量。而印度政府觉得还不够，因此估计这个水池还可以蓄多一些水。

第二个水池，俺本来不想公开说，但是看来大家也会猜到。那就是中国的 *香港* 。

香港现在的国际热钱，大概是6500亿港元，换算成美元，大概也有800-900亿美元。因此这里还可以蓄水1千亿到1千5百亿。

当然香港的股市和房价会受到颇大的压力， 这就要求香港政府立即动作，保证普通香港市民不要卷入地产和股市泡沫中间，同时增加经济适用房的供应，缓解房屋的硬性需求。

不过如果可以通过香港股市和房地产市场吸收外来资金，然后一举而歼灭之，那么殃及池鱼的香港市民为国家做出了贡献，那么中央政府之后帮他们抹平一些损失，也不是问题。

第三个水池，其实应该是 *中国的股市和房市* 。但是中国的房市已经高企，而且大概有50%的房地产资金，已经是外来的热钱，因此这两个市场的操作空间不大，只能是10%左右的上上下下震动而已。

把游资吸收一部分，让股市到一个高点，然后就来一个政策发布，用海绵把水挤一把。这个算是古代刑法的凌迟处死的路子。

那么除了股市价格，增大股市的总量，是一个更好的办法。这个办法，就是走当年美国人在互联网泡沫的路子，通过大量的新公司的上升，把外来资金吸收。当年美国的纳斯达克从5000点跌到1千多点，消灭了不少欧洲和中东的资金，算是把美国十年的贸易逆差给平了。

第四个水池，就是 *中国的中西部发展* 。让外面的游资走进内陆，去发展中国的新农业、新市镇，从而把热钱，放到冰箱里，把它变成了冷钱。

因此这几个步骤一起来，估计就可以把美联储的6千亿给消化掉。让你变成春雨，来个润物细无声，泥土入海，一去不回。

*现在美国针对中国的主要是两个。* 一个就是人民币汇率，另一个就是关于外贸顺差不应该超过一个经济体的GDP的4%的提议。

对人民币汇率，俺已经说过很多。就是在 *当前美元独大的国际体系下，无论人民币是涨还是跌，对中国都没有太大好处。因此中国的关注点，不是人民币涨跌的问题，而是人民币变成国际贸易结算货币的问题。*

俺一直的提议，就是 *世界经济天下三分，以人民币、美元和欧元形成一个三角体系。然后各个地方的其他小货币，自己在本地挂靠。*

就是说加拿大元、墨西哥比索、巴西里拉等等，你就挂靠在美元上面，英镑、瑞士法郎等等，你就挂靠在欧元上。而日元、韩元、澳洲元等等，你就挂靠在人民币上。

*那么俺们只要确定地区货币，比如说人民币区域内的货币，大家做到货币稳定，那么整个世界的货币体系，取决于三大货币的调整，那么大家就会在保持地区货币的一体性方面，解决当前国际金融和货币市场，盲目强调自由化，而引发的大幅度波动，从而导致国际金融次序动荡。*

因此人民币是可以缓慢有序的升值的，但是这个升值的时间和速度，必须根据中国和东亚经济的具体情况具体处理。说白了，就是 *俺大爷高兴就涨一下，不高兴就不涨，还要跌一下。一起取决于大家的表现如何，要想中国动作，就得拿出些实货出来，老想着投机取巧，空手套白狼，那是没门。*

而关于贸易顺差不超过4%，那倒是可以考虑一下。

中国的贸易顺差大，其中一个原因，就是美国对中国实行出口限制和投资限制。你这些限制取消了，自然中美贸易的平衡就会好一些。

当然中国在贸易顺差上需要减少，可是这个比例是贸易顺差，和GDP规模的比较。如果俺中国的GDP规模变大，那么这个比例也可以变小嘛，是不是？

俺一直就说，中国的GDP是低估了。低估了，多少，是不是应该好好的整理一下。比如说按照PPP的计算，都可以和国际组织展开合作，把中国真正的GDP规模算清楚一点。总而言之，GDP规模变大，也是一个降低比例的方法。

其实这些都不是中国的七伤拳。 *中国真正的七伤拳，在于放慢经济发展的速度。*

目前美国大概2%的增长，很大程度上在于中国经济的拖动。如果中国主导放慢经济速度，好好做好自己的内部经济结构的调整，说不定就把美国的增长给放没了。而且中国只要开始放慢速度，受到影响的是包括澳洲和加拿大这样的原材料经济，估计可以造成靠套利汇率交易的能源和原材料投机资金，高速平仓。

这种情况下，大量平仓的美元投机资金，暂时会推动美元汇率回升，也会造成发展中国家经济体中出现暂时的资金短缺现象。

而这个时候，中国就应该把手上的美元资产，比如说美国的国债和公司债等等，脱手一些，转而在价格合理的情况下，对这些发展中国家经济进行资金支持，来填满这个空缺。

而且美联储现在在美国受到的质疑非常大，尤其是在货币政策上，和奥巴马政府的高度一致，已经违反了政治中立的原则。这将会受到美国中期选举之后，以财政紧缩作为主要政策诉求的新国会的压力。

如果美联储的举动，在短期内起不到舒缓失业率和稳定房地产市场的作用，那么下一轮的量化宽松，就是所谓你躲过了这一轮洪峰，俺就给你再来一轮的法子，估计难道相当之大。

而如果美国国会决定对中国入口产品进行惩罚性税收制裁，那么中国就要想好应对的法子。

这个就是俺前面说过的， *就是中国需要提高对美输出产品的价格。如果美国加入口税50%，那么中国就应该加上一个同等的数额。这样会导致美国人的生活成本指数翻上去，而中国对美国出口贸易量肯定会大幅降低，但是对加拿大和墨西哥的贸易出口，就会惊人的上升。*
