# -*- org -*-

# Time-stamp: <2011-08-23 17:01:18 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话2：好吃的转基因三文鱼

俺说美国颇像当年的东汉末年，有不少读者表示异议。

当然了，董卓进京之前，还有何进要出现，还有遍地烽火的黄巾军。

*看美国历史，主要看几个关键点。*

第一个点，当然就是美国建国，在独立战争之后出现的两党之争，就是北方以汉密尔顿领军的联邦党人，对决南方以杰弗逊领军的民主共和党人。

这个时候的美国是虚弱的，因此国内政治受到英国和法国势力的干涉，对外关系和对内斗争，楚河汉界，泾渭分明。

第二个点，就是在 *1812年战争* 之后，亲英国的联邦党人衰败，而有南方民主共和党的奴隶主们主导政治，出现向西部扩张来增加奴隶制势力的举动。这个阶段的美国政策，是以种族屠杀印第安人和攻掠墨西哥，抢夺土地，然后大量买进非洲黑奴，发展以供应英国纺织业为主的棉花原料的殖民地经济模式。

第三个点，就是美国内战。因为东北方的发展，美国算是赶上了半个第一次工业革命。对工业革命的要求，与继续奴隶制农业经济的现状，导致了南北冲突。而北方的胜利，和对南方的三光政策，保证了美国赶上了第二次工业革命的潮流。

非常值得关注的是，当时世界的多数后发国家，都在这个时候开始了赶超英国这个工业革命先发国家的运动。

在中国，是镇压了太平天国后的洋务运动，在日本是明治维新，在德国是普鲁士崛起，在俄罗斯是废除奴隶制，开始工业革命。

然后30年的改革开放，各个国家都颇有成效。但由于各国处于的地缘政治空间不同，而形成了不同的国家命运。

德国在俾斯麦的经营之下而崛起，但是面临着生存空间上的东西挤压。西边是仍然强大的英国，东边是崛起的沙俄。而威廉二世没有听取俾斯麦韬光养晦的建议，来好好消化和固盘，因此引发了和英国冲突的第一次世界大战。

俄罗斯则在第一次世界大战中，损失颇为惨重，引发了布尔什维克革命。

中国则因为在东亚竞争中，战败于甲午战争，从而导致了国家的进一步衰亡。

日本则因为战胜中国而崛起，并因为欧洲在第一次世界大战中，无力东顾而大肆扩张地盘，最终因为侵入了中国东南这个英国和美国的势力范围，而导致和英美对抗。

在所有这些后发大国之中，美国的地缘地位最佳。因为美国的崛起，并没有挑战到霸主大英帝国和其他各个挑战国德国的利益。美国在美洲的对手，只不过是衰落的西班牙。因此美国可以靠一战而胜利，占领的加勒比海和菲律宾。

而中国因为1890年代的战败，自然下一个30年自然没戏。等到另一个30年开始， 以1931年日本继续侵华（ *俺反对将918作为抗日开始，应该把甲午战争作为中国抗日的起点* ）作为起点，中国仍然是被人家宰杀的猎物。

这个过程一直到1949年结束，然后军事能力的建立，保证了中国在下一个30年，国际次序重新洗牌的时候，可以开始自己的积累。

所以看今天的美国，你可以把1890年作为美国的第4个点。可以说美国从1776年到1890年大概120年的时间里面，完成了婴儿到少年的成长过程。

最麻烦的少年成长之痛，the growing pain，就是南北内战。

然后在下面的这120年中，就是美国从青年到中年，然后开始步入老年的状态。最主要的转折点，就是美国国力到了表面最强盛（其实已经内有虚火了）的1990年，然后在2000年开始从高潮退潮。

在这一段时间里面，也可以说是3个点。

第一个点，就是罗斯福的新政时代。这个时代，是美国从老罗斯福的对内安抚，对外用兵，开始帝国主义的吸血时代。这个时代带来的财富，出现了门阀做大，社会分化严重的社会现象，经济快速增长，危机不断出现，大亨骄横跋扈，人民暴力抗争，是这个时代的特点。

这个时代，如果以汉朝来比喻，相当于西汉末年的情况。

而小罗斯福力挽狂澜，就是一个成功的王莽。或者说你让刘秀坐了王莽的位置，从而避免了大规模的暴乱。当然第二次世界大战的开打，使得小罗斯福的集权成为可能。

第二个点，就是里根的新政时代。这个时代，基本上就是要打破罗斯福时代的新政措施，已经用了几十年，成为强弩之末。好的作用基本用完，副作用却不断呈现。因此出现了加水加面的揉面措施。

第三个点，就是小布什的伊拉克战争。这个时代，基本上就是在更高一个层次上，走回了罗斯福之前的美国状态，又出现了极端的社会分化和财富的极度不平均。

但是比那个时代更要命的，是两大趋势的出现。

一个就是实体工业空心化。这个导致的结果，就是依靠制造业创造大量工作机会的方法，已经无效。而这种方法，是当年小罗斯福的主要法宝。

一个就是依靠过度信用消费。这个导致的结果，就是美国失去了经济发展的主要发动机，而且令整个政府和国民，都陷入了债务危机。

而现在的美国，非常有可能，会出现高企的失业率，变成美国人生活的一个常态。 *而在下面面临的挑战，就是如何处理政府的财政赤字和债务负担。*

美国的财政问题，其实非常简单，就是两大块：

一块就是国防和军费。

一块就是社会安保福利和医疗福利。

要解决入不敷出问题，你可以增加税收。不过看了一下，关于小布什时代的减税政策，该不该给富人延期的对抗中，你可以看出增税的难度之大。

那么就只有裁减财政支出。

你砍了穷人的福利，就是逼着人家起来造反，就是说逼黄巾军出来。

你砍了军队的福利，就是逼着人家起来政变，就是说逼董卓进京。

当然还是要好好想办法解决一下，这个就是请世界人民吃美味的转基因三文鱼。
