# -*- org -*-

# Time-stamp: <2011-08-23 20:09:59 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话10：大本撒钱，小川节水

[2010-10-21 07:26:47]

*看来这个星期，让很多人出意料的，就是中国人民银行加息的行为。*

要了解经济，就必须知道，其实经济不是那么复杂的事情。大部分经济学家，只不过是一些学究，发明些模式出来，把自己也搞不清楚的东西，弄得好像很有水平的样子，然后就发明一些怪不拉叽的词汇，就出来忽悠大家了。

比如说美国联储局主席直升飞机大本哥，说了一个词汇，叫做“量化宽松”。很多人就不是太懂，因为听起来倍高深。

其实说白了，换一句大白话，叫做“ *印钞票* ”，那么全世界，上没有上过学的都懂了，哪怕你是个大文盲，也知道大本在干嘛。

大本哥印钞票之后，是干嘛呢？

两件事情，一个就是去 *买政府国债* 。

美国政府想花钱，但是财政收入，也就是税收，收不上来，因为人家说经济危机了，你还说嘛税。

穷人说，收税，嘿嘿，你看俺这个破样子，有钱交吗?

中产阶级说，收税，俺工作都没有了，你他妈还要收俺税？

富人说，你那个谁谁谁，哪有自己跟自己的钱过不去的，你疯了？

所以就没有钱，或者说没有足够的钱，收上来。

*那么要花钱，就要借债，买国债来融资。*

这个国债，就是大家来买。你私人可以买，俺公司可以买，他基金可以买，最后其他外国的中央银行，比如说中国的央行，可以来买。

国债的信用是建立在国家基础上的，而大家干了一些美国政府，觉得短期信用还可以靠得住，可是长期信用，有一点让大家心里毛毛的。

于是大家决定，俺们不如不买长期美国国债，只买短期的美国国债，这样的话，风险不就小了嘛。

那么美国中期国债，就卖不动了。

这个长期国债，其实主要是两个期，一个是30年期，一个是10年期。

而10期美国国债，是非常重要的一个指标。那就是美国房屋贷款市场的长期利率，是靠10年期国债来决定的。

大家知道美国买房子借贷，你可以借30年长期的，也可以借3-5年短期的。

通常就是你短期的利率，是按照美国联储局的基准利率，加一个基本点，比如说2.5%到3%的样子。那么你美联储基准利率是0的话，你的短期房贷也就是2.5-3%的水平。

房贷的30年期，就按照同样的办法处理，在10年期国债收益率上，加上基本点，就是5.5-6%左右了。

那么要是大家不买，或者买少美国10年期的国债，那么收益率上升，就会导致美国房屋贷款30年利率增高，对美国经济恢复不利。

和短期债劵不同，美联储可以开一个会，自己决定基准利率（不过现在已经到了0了），而这个长期利率，就只有一个办法： *美联储印钱自己买* 。

那么美联储除了买 *美国政府的长期国债* ，来压低长期利率，同时做的，就是买 *机构债务* ，说白了，就是印钱给两房，让他们有钱借给大家买房子。

这两个举措，其实都是要稳定美国现在危机重重的房屋市场。

但是也不是光要稳定房屋市场，而是对其他两个市场：资本市场和就业市场都希望有所帮助。

最近看到大家在瞎争论一气，关于货币主义和凯恩斯主义谁是谁非的问题。看起来，争论的政策焦点在于，你是要靠货币投放的松度，来推动私人投资的兴旺，还是要靠政府财政的支出，来带动需求的提高。

其实在现实社会里面，哪有这么非白及黑的情况。美联储放松银根这个货币政策，可以表现在压低基准利率，也可以表现在认购国债或者公司债来压低长期利率。

而美联储印出去的钱，可以交到私人公司手里，也可以交到政府手里，大家都拿出来花，你还分得清那些是财政政策，那些是货币政策？

所以你反正都是在印钱，那么就是看你印出来的钱，关键不是谁来花掉，而是花在哪里。

政府拿到手里的钱，估计一个用处，就是把本来就臃肿不堪，需要裁减的政府雇员队伍稳住。

这个是大家比较反感政府花钱的一个原因。就是效率及其低下，可以说大部分会给浪费掉了。俺住的小城市里面，就有一部分奥巴马复兴美国的救助计划项目。干啥呢？就是在人行道的旁边，本来种了树木的地方，深挖一个大坑下去，然后在旁边堆砌一些挺好看的水泥。

说是这样一来，以后雨水就可以自动流下了浇灌树木的。

于是俺们美国就复兴了，呵呵。

那么是不是私人来到了美联储超级便宜利率的贷款，就可以帮助美国的就业市场？那也不一定。人家一转身，这些钱就进了股市了。

你修人行道，还要雇几个人干活呢，进了股市炒卖，最多就是雇了几个电脑干活而已。

更糟糕的是，有些钱拿去炒石油期货的，结果美国汽油价，俺眼看着上个星期的一天，从2.95的价格，一天涨了7次，到了3.15了。这样俺们中产阶级们的日子更难过了。

一个更要命的问题，就是资本是涨了翅膀，人家是会飞的，是可以用光速，在全球飞来飞去的。

就是说你在电脑里面，打几下，人家通过光纤，从太平洋或者大西洋底下，就电闪雷鸣，飞走了。

所以你看一下当年日本采取低利率政策，放出去的钱，放到哪里去了。反正肯定不在日本，那是铁板钉钉的事。

当大本哥印了钞票之后，这个钞票估计也是要飞走的。为啥呢？因为虽然本哥的钞票交到了奥巴马手里，但是人家其他人省下来没有去买长期国债的钱，就要另谋出路了。

这个出路，就是中国。就是说， *美国联储局要用洪水来冲中国。一方面是印钞票导致美元贬值，一方面就是要把通胀输出到中国。*

于是中国就必须想办法来应对这个通胀，那么央行的升息，就是这个应对的一个手段。
