# -*- org -*-

# Time-stamp: <2011-08-25 11:22:21 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话57：中东局势和发展道路（四）

[2011-02-07 13:31:29]



那就是说，中国的外交战略，要以建立一个多级合作的世界次序为基础，坚持和平共处五项原则，支持各地区的国家，保持自身的国家独立和民族自主，反对霸权主义，为人家国家决定谁应该出任总统。

当然帝国扩张也是一种转嫁内部矛盾的方法，所以那些在祖国和帝国争论中的一方，当将今天的中国界定为他们心目中的帝国之后，就否认这个中国是他们的祖国，于是就大声鼓噪，要在中国闹革命了。

记得俺在关于政治改革系列中提到，对中国现状不满的力量，有右派的，也有左派的。而现在喊革命喊得比较有力的，不是右派（右派势力还是暗地里想搞颜色革命，但是明面上还是喊深化改革），反而是左派。

这里俺说的左派，并非俺这种要求缩小贫富差距，增加民众参政和议政，实行执政为民的中左派，而是提倡走文革道路的极左派。

俺在政改系列中，没有对极左派批驳，是因为其鼓吹的一套东东，不光是不切实际，而且人家极右派的东东，还可以拿西方体制，来作为成功范例。虽然俺们可以说，那个东东，是合乎人家西方的文化传承和历史因素的，是中国这样后发的国家，没有历史机遇达到的，总算还是有个东东可以讨论。

而极左派的那套玩意，把文革时代的东西拿出来，骗骗80后和90后的后辈也许还有可能，但是对俺这个年纪的过来人，那是一点效果也没有。

虽然俺是出生比较晚，因此58年那样的情景是没有见到过，但是相比较于今天的孩子，还是有很多不同的。比如说，今天的孩子，问自己的父母，爷爷、奶奶、外公和外婆，去了哪里了？得到的回答是，在你没有出生之前的某某年，他们因为没有饭吃而饿死了。你觉得这个孩子的心灵冲击会这么样？

而俺自己的祖父母，只有一个外婆生存下来。俺的一个小姨，其实并非亲的，而是俺外婆走亲戚的时候，从死人堆里拣回来的。这些恐怕是今天的人，难以想象的。

即使是在70年代的时候，中国还出现今天印度和其他的一些发展中国家有的事情，那就是路有饿孚倒毙的情况。

记得我还是个孩子的时候，就亲自接待过拿着大队支部开出来讨饭证明的农家妇女，挨家挨户讨饭。那个时候，大家家里都是穷得叮当响，能够给的只是一些剩饭，而且有的甚至是变了味的。

如果不是因为我们给这个农家妇女提供了避寒的地方，你大概就会在雪地里多看见一具尸体。然后太阳出来的时候，她就把讨来的剩饭，在太阳底下摊开来晒。自己吃一点，然后就把晒干的饭，装入麻袋，抗回家，就是未来一年全家的口粮。

而在文革期间，到处都是群众斗干部，算是整个政府体系崩溃了，然后就是为了抢夺政治权力的群众斗群众。在位子上的，就坚持认为，目前革命形势一片大好，简称“好派”。

而在台下的，就坚持认为，目前革命形势好个屁，简称“屁派”。然后就是相当于今天台湾那样，大家各自有广播车，宣传队，整天拉着队伍上街游行。

比今天台湾还要厉害的，就不是只是针对某个政治人物的暗杀和枪击事件，在文革中的武斗，那是大规模的，像是城市游击战那样的。有武器的，那就上枪炮，没有武器的，木棒石头，也成为了武斗的工具。

这种社会乱象，最后靠了军管才得以遏制。

不是所有人，都是这么热衷于武斗的。像俺父亲那样，都是经历了在朝鲜战场上生死搏斗的退伍的军人，反而倒是对这些武斗，躲得远远的。其实不奇怪， *经历了真正残酷厮杀的人们，是不会对武斗这样的杀戮感兴趣。*

*正如经历过革命的人们，是不轻言革命的。*

对俺这样的人，正是因为从身边的实际生活看出去，才知道什么叫做民不聊生。所以才有对政治和历史的兴趣。如果换了今天，也许人生的理想，就会是当个电影明星、当个歌星等等。

所以要了解俺们那一代人，你必须知道俺们出生和长大的时代背景。因此可以理解， *那一代人出现了不少普世右派，你可以质疑他们对西方的看法之肤浅，但不应该怀疑他们的真诚。*

在政改系列中，俺提出左派和右派，如果谁先跳出来要推翻体制，也许会导致这个社会，向他们不希望发展的方向变化。

从俺的角度来讲，虽然俺是赞成中国社会向重视弱势团体，向保障民生的左面转，但是如果要俺选择极左派路线，那俺宁肯选择向右走了，毕竟对俺们这个年代的人，要做一个选择，那是太容易了。

*因为很简单，那就是人生在世，追求的是自由二字。*

*而自由，可以大致分成三个方面的自由。*

一个就是 *政治自由* ，比如说政教分离啊，你可以参与政治过程啊，等等。

一个就是 *社会自由* ，比如说你信仰宗教啊，等等。

一个就是 *经济自由* ，比如说你可以选择工作啊，等等。

中国现在的社会，在政治自由上，还需要做很大的改进，但是在社会自由和经济自由上，已经有了长足的进步。别的不说，几亿农民的生活提高，走出贫困线，就是史无前例的事情。

*因此任何以名义上的政治自由的给予，不论是左派吹嘘的文革时代的人民民主，还是右派吹嘘的西方普选下的金钱民主，如果都是以俺们在社会自由和经济自由上的损失为代价，那一定是要提防的。*
