# -*- org -*-

# Time-stamp: <2011-08-25 13:14:28 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话69：能源依赖和周边环境

[2011-03-07 03:29:02]



这两天没有更新，因为写的东西，给无意中删掉了。同样的事情发生在《说文论文》里面，其中大概两三篇的东西，一直都没法恢复。

继续谈一下利比亚的局势。

在中国政府撤侨这件事情上，俺是持支持态度的。因为 *利比亚的局势，可能需要几年的时间才可以稳定。*

美国之所以在利比亚的事情上犹豫不定，是因为对利比亚的内部情况并不了解。和埃及不同，美国在埃及的渗透很深，基本上埃及军队的团一级军官，人家美国国防部都有直接的联系。

因此透过这些联系，人家了解到实际情况，然后大家商讨出一个价格，就把老穆巴拉克给牺牲掉了。但是利比亚，美国没有这样的渗透力，人家内部谁是谁都不知道，所以难以妄动。

而且在现在的自由利比亚，就是利比亚起义的东部地区，也是基地组织的根据地之一。在1990年代的时候，卡扎菲和基地组织在利比亚恶斗相当激烈。而当美军入侵阿富汗和伊拉克之后，利比亚的东部地区，贡献了最多的外国自由战士，和美军打仗。

这也是美国和卡扎菲在北非合作的一个基本点。那么倒底东部反抗组织的实力如何，里面基地组织的势力多大，如果卡扎菲给推翻之后，利比亚会出现什么样的政府，这些都是美国现在没有答案的问题。

所以美国现任国防部长盖茨，在提出了“历史垃圾桶”理论之后，又有了一个新的发明，叫“领导人医院验脑”理论，说是如果任何美国领导人要动员陆军，去入侵任何一个国家，应该先到医院去验一验脑袋，看一看是不是有神经病。

利比亚的问题，一种可能是出现苏丹那样南北分裂，而出现东西苏丹分治的局面。但是这样的局面，必须是通过武装斗争之后，大家谁也不能干掉谁，而且人也死得比较多，像苏丹那样，就是死了2百万人，大家都打得有点精疲力竭，打不动了。

当然还有就是外部强权的干涉，在这里达到平衡状态，谁都没有能力可以独吃，只好划分已有势力范围。

最近卡扎菲向中国和俄罗斯喊话，颇有这种考量在里面。但是 *就算这种平衡可以出现，卡扎菲下台，也是一个定论* ，然后让他比较受到西方接受的儿子赛义夫出来主持局面，也许也是一个选择。

当然有一个比较麻烦的问题，就是利比亚不是出现苏丹化，而是出现索马里化，那么北非的乱局，就不是一年两年了。这个不符合中国的利益，更不符合美国的利益，因为索马里化的利比亚，那就是基地组织的美梦成真了。

考虑北非和中东的局势，容易犯的一个误解，就是把这些地方的变化，看成一个中美对抗的过程。看到美国利益受损，就理所当然地认为中国的利益必然增加。其实这种看法是很片面的。

*中国由于自己经济的高速发展，对能源和原材料的需求比较大，因此在北非是要求更大的发展。而美国同样因为想摆脱对中东能源的过分依赖，也在北非寻求更多的机会。从这个角度来讲，中国和美国是有竞争关系的。*

但是这种竞争关系，要依赖于一个安定的环境，可以让你来竞争。比如在非洲的安哥拉，中国是开垦者，但是最后美国要插一脚，进来分一杯羹，你不能不让人家分。因为本身安哥拉自己，也希望能源的客户多样化，而不愿意被你一个国家垄断。

但是同理，本来美国一国独大的国家，也希望看到其他国家过来竞争。在以前，这种情况一出现，中情局立刻就把人家给做了。可是在美国势力衰落的今天，这一套自然也玩不下去了。

就是颜色革命这样的，你老跑到隔壁街上去放火，去烧俄罗斯和中国的势力范围，但是这个火烧起来之后，风向一转，很快你美国住的小区，就要被火烧得无处逃杀了。

所谓 *己所不欲，勿施于人* ，就是这个意思。

因此在北非这些地方，中国和美国其实是有共同利益的。比如说埃及的穆巴拉克，是中国的老朋友，也是美国的老朋友。而利比亚的卡扎菲，和美国曾经交恶，也和中国颇多不合。

*中国需要的是一个稳定的环境，可以进行投资，而美国需要的是一个稳定的环境，可以保证以色列的生存。*

不过美国人的能力，在于破坏，是一个nation destroyer。而中国人的能力，在于建设，是一个nation builder。比如在伊拉克，美国人破坏之后，当局势最终稳定了，中国人就可以去搞建设。在阿富汗，也是一样。

*坚守了这个底线，中国只要保证，俺有资金、技术和建设能力，就可以慢慢地等待这些地方的局势尘埃落定，不需要卷入任何人家的内斗就行了。*

而中国在非洲的主要动作，应该集中在 *如何有效地维护南北苏丹出现的和平局面* 。在南苏丹可以加强投资力量，如何让南北双方，都和中国的合作之中，享受到经济发展的好处，然后进行和中国更紧密的合作，是中国应该下大力气的地方。

如果读者有兴趣，可以回头读一下俺的《花开花落》中关于能源的一些看法。其中一个主要的观点，就是 *中国在对传统的能源依赖之中，最好是从石油倾斜，转向天然气倾斜* 。

去年中国的中海油在美国得克萨斯州，成功地投资了美国的页岩气公司，对吸取开发技术上应该有好处。如果在技术上有所提高，那么中国的西南地区，比如说俺老家的黔北地区，加上四川和重庆的南部地区，都是比较丰富的天然气储藏地。

*总之中国的能源依赖，要逐渐地向自己的周边地区着重，* 比如说中国东海、南海、东南亚、印度洋地区、俄罗斯远东和西伯利亚、哈萨克和中亚地区，超过了伊朗和沙特阿拉伯，要保障安定，花的力气就比较大了。
