# -*- org -*-

# Time-stamp: <2011-08-25 10:11:55 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话47：2011猜想（3）

[2011-01-20 15:50:08]

每天发生的新鲜事儿真多，有点让人喘不过气来的感觉。

前面说得美国QE2的资金，一大笔进了CDS去爆欧洲的国家。有人问，为啥美联储发行了N量的货币，却见不到高通货膨胀？

主要是 *这些金融衍生品和CDS的蓄水量非常大，是几十个大三峡。* 要不然的话，岂能一个小崩溃，就差点瘫痪全美国金融体系。

但是对欧洲国家债券市场的打击，事实上造成了欧元的下跌，这个目标是和美国政府，希望美元对欧元下跌，而导致出口产品竞争力增加的初衷，是背道而驰的。

所以说，许多胡扯起来头头是道的经济学家，其实自己都不知道自己在干嘛。

比如说，美国一大帮子人炒人民币汇率问题，说的是想让人民币狂升，而导致亚洲货币普遍对美国上涨。据说这样可以增加美国对亚洲地区的出口。

但是不想一想， *美国产品的竞争对手，主要是日本和德国* 。而日元对美元汇率，已经乖乖地涨上去了。而 *欧元是一个亚洲美元过剩的出气阀门* ，就是说当亚洲人出口太多，手上拿了太多过剩的美国，他们就把这些美元，换算一部分成欧元。

*这个动作，其实是抬高欧元对美元的汇率，对美国出口竞争力，有大大的好处。如果你逼得亚洲货币集体上涨了，这方面其实是帮助了德国竞争力。*

8看美国产品和中国产品，其实真正处于硬碰硬的竞争，不超过15%产品范围。*

这些产品主要是两大类，一类就是 *网络设备* ，尤其是路由器，说白了，就是中国的华为对抗美国的思科。大家也看到了，美国政府到处打压华为的动作连连出台，其实和美国政府对付日本丰田公司是一个招数。最新的美国汽车销售数据，福特和通用，排在头两位，销售额上升，丰田排在第三，销售额下降。

另一类，就是 *新能源产品* 。这个也是为啥美国开始了WTO案件调查，主要是打击中国在这方面的竞争力。

至于其他的， *美国出口中国的产品，多数是波音的飞机，很多医疗器材，还有就是农产品。而中国的大部分是电子、机械和化工产品等等。*

*看起来美国要求人民币升值，最主要的考虑，估计一个是导致大批中国资金，到美国房地产市场上来为美国撑住阵地。另一个考量，就是事实上降低美国的负债水平。*

因为距离美国国债的天花板15万亿美元，已经没有多少空间剩下了。现在共和党控制的众议院， ()如果不提升这个天花板，那么美国国债就要崩溃。*

但是要再次提高这个天花板，自然茶党们要提出不少的附加条件，在砍预算上，给奥巴马政府勒裤腰带。

可以预见的是，占优势的共和党众议院，和略占优势的民主党参议院，会导致政治博弈陷入胶着状态。

这个时候如何削减美国的财政赤字，是一个令人不敢寄予太多希望的事情。

本来联储局QE2的一个主要想法，就是控制美国十年期国债的利息。但是随着通胀预期的增加，10年期国债利息反而有走高的趋势。如果可以突破4%，那么美国联邦政府的运作，就会面临颇大的困难。

而在这个大背景下的美国经济，如果勉强达到3%的增长率的话，失业问题基本无解。

同时美国的州和城市一级，会逐渐进入希腊状态。

前一阵子，大家关注的一个标志性的事件，就是 *阿拉巴马州的一个城市，开始拒绝支付退休福利给前政府雇员* 。结果就是这些本来退休的前警察、消防员和教师等等，有的不得不出来找工作，有的靠大家救济过日子，还有的就干脆一死了之。

要是这些城市和州，开始大规模地拒绝支付退休福利，或者靠大幅度提高物业税来弥补亏空，那么发生在亚利桑那的暗杀国会议员案件，出现的频率就会越来越密。

如果美国在2-3年之内，就是在2015年左右无法摆脱经济困境，那么2016年美国总统大选，会出来什么样的人物，就真的令人关注了。

那时候恐怕战争是真的无法避免了，但愿美国的经济不要走到那一个地步。毕竟战争的灾难，对世界上的很多人，都是太过沉重。

今天大家在伊拉克和阿富汗发生的战争，只是作为一个看客，是无法体会到这两个地方人民的生离死别的痛苦。

但是从现在的局势看来，在突尼斯发生的革命，俺觉得应该叫做“ *饥饿革命* ”比较靠谱。和突尼斯处于同样饥馑困境的，就要包括周边的阿尔及利亚等等国家。

不过最要命的是埃及。 *如果饥饿革命蔓延到了这里，导致激进的穆斯林兄弟会上台，那么伴随着以巴和谈破裂，那么这个地方，就会是下一个战争的爆发点了。*

*中国需要靠文职官员们，全世界拿着支票簿，纵横捭阖，为国家赢取和平的周边环境，也靠军队和军工的科研人员们，努力利用这个空间储存弹药。*

从这个角度来讲，中国一系列军事大杀器的官泄，不排除是一个敲山震虎的先手。预先警告一下，要想点炮仗，找别的地方去。

所以听到有传言说，中国在2010年12月29号的时候，在海上实验了一颗DF21D，如果是真的，那么也是在意料之中。

毕竟J20成军还有5-6年时间，要是最后阶段的制导技术开始成熟，那么也不失为一个马上就可以运用的杀器。

其实从导弹打卫星，到卫星变轨，到嫦娥接近月球表面的操作，这一系列的实验，标志着制导技术的逐步成熟。
