# -*- org -*-

# Time-stamp: <2011-08-26 09:01:54 Friday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话86：美国战略转变（一）

[2011-05-04 04:44:14]


这篇叫做闲话，但是谈到的话题，却一点都不闲话。可以说这篇博文，是所有闲话系列中最重要的一篇。

如果你是政府相关机构，或者是主要智囊团体的专家，那么这篇闲话，你可要打起十分精神，好好的阅读了。

读者问起本拉登死后的美国战略，我的主要看法，是 *美国会采取战略收缩策略，来应对目前美国面临的局势* 。

首先大家应该明白的是，美国是继承了英国的传统，那就是一个海洋强权，基本上是走了马汉老兄定下的路子。

而和陆地大国相比，比如说历史上的沙俄和德国等等，美国的陆军从来就不具备一等一的作战力量。看一下美国参与的大规模战争，第二次世界大战，太平洋战区，从关岛、菲律宾到日本本土，基本上都是海岛战争。在欧洲战场，也是法国诺曼底登陆这样的战斗，和德国、俄罗斯那种内陆战斗，是区别很大。

当然后来的朝鲜战争和越南战争，也是在半岛，就是接近海岸的地方进行。这样的环境，保证了美国海军的优势，和通过海军进行空中控制的手段，来保证战争有利于美国。

因此这种态势，导致了美国考虑到以中国作为一个潜在的敌人的时候，如果阿富汗战场这样的内陆战争比较棘手的时候，退而求之，就是希望通过海上运作的离岸平衡手，大概是最有利的选择。

那么看 *中国目前的安全态势* ，自从中美合作，在阿富汗战场拖垮了苏联之后，中国来自北方，就是说东北、正北和西北的安全威胁是基本消失了。那么可以操作的地方，基本上是三大块。

考虑到中国在东北亚的朝鲜战场上直接出过兵，在东南亚的印度支那战场上间接出过兵，在南亚也和印度打过边界战争，那么要想在中南半岛上，进行直接针对中国的军事行动，是极其不现实，也是成本非常高的。

那么在以反恐战争为借口，通过巴基斯坦、阿富汗、哈萨克斯坦一条线，想形成一个围堵中国的国家链，现在看来成本也是非常之高。

退而求其次，最好的选择，自然就是 *以印度洋和太平洋海域作为一个离岸平衡点，然后通过自己在这里的盟友的操作，和中国冲突，而自己扮演仲裁和拉偏架的角色* ，当为最佳选择。

在东北亚，韩国是扮演炮灰的角色，而日本是扮演离岸基地的角色。因为韩国是美国希望事态恶化的前沿，而又可以随时后撤，让局势和缓。真的擦枪走火，自己又不用损伤。

但是日本这个离岸基地，在核辐射扩散之后，有被削弱的可能。而随着中国势力的不断增强，日本慢慢也会沦落为韩国那样的炮灰前沿的命运。

作为退出第一岛链来避免中美之间碰撞的收缩手段，美国就必须打造以澳大利亚到关岛这个新的离岸基地。

而这种考虑，就必须把印度尼西亚和马来西亚推到前沿，和中国对抗。可是看来事态的发展，是事与愿违。中国在印度尼西亚和马来西亚的投资和市场整合，会导致这一战略意图落空，那么作为美国最坚定的遏制中国的走狗的新加坡，则面临非常危急的局面。

在中南半岛上，大致是三个地区“大国“：越南、泰国和缅甸。这三个国家，基本上采取一边倒的机会不大，但是也不敢轻易得罪北方的大国。那么显然不可能成为平衡之手。

那么在这个区域，美国希望能够出来和中国对抗的炮灰，自然是 *印度* 。如果美国可以拉着印度对抗中国，而自己又可以保持在中东和北非（美国的北非，其实只是埃及）这个节点上的控制力，那么确实是可以在印度洋上游弋，保持离岸平衡的姿态。

但是这些想法，都是美国战略界的想法，并不一定和军队的想法一致。而最近美国军方开始干政，提出了自己对未来世界格局的一些新的思维。

正如美国参谋长联席会议主席穆伦将军经常说的一句话，就是 *美国的国家安全的最大威胁，已经不是崛起的中国，不是穆斯林恐怖主义运动，而是美国千疮百孔的财政和经济* 。

大概在4月中旬，美国军方为这个政策，公开发表了意见。这个意见书，是以Y先生的名义发布的。这个Y先生，是何许人也？其实是美国三军参谋总部，就是穆伦将军手下的两个高级幕僚，一个是海军上校Wayne Porter，一个是海军陆战队上校Mark Mykleby。

当然人家会说，这个观点，只是俺们两个小军官的私人想法，不代表穆伦将军同意俺们的意见，也不代表美国海军、海军陆战队、三军参谋总部和国防部的意见。

不过按照美国外交关系协会，就是美国战略界的主导团体的看法，如果这些想法不代表美国军方的意见，那才是奇怪了。

当然某种程度上来讲，军人议政，从来都是美国的政治禁忌。但是 *到了军人也不得不议政的时候，说明文人政府的功能，无法应对国家的危机* 。

也许最近不少美国学者谈论罗马历史，讨论美国会不会出现凯撒，什么时候出现，并非空穴来风。
