# -*- org -*-

# Time-stamp: <2011-08-25 20:00:55 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话70：有人有鞋，人人有枪


[2011-03-10 15:41:53]


看着利比亚的局势，想起了英国诗人亨利的《浪漫》中的这两句诗。

Some had shoes，but all had rifles.

有人有鞋，人人有枪。

就是说穿鞋的怕光脚的，而人家利比亚现在大部分是光脚的。

看到CNN发了一条爆炸新闻，说是卡扎菲和叛军商谈下台问题。看的时候，不由得摇头。俺们西方的媒体，制造新闻的本事，是越来越大了。看来在王府井把自己变成新闻，不是一次偶然。

因为从利比亚的局势来看，现在显然是卡扎菲稳住了阵脚，控制住了首都，开始有限的反攻了。在这之前，叛军没有把握气势，一鼓作气，兵临城下，被人家守住了底线，卡扎菲哪有这么愚蠢，反而要投降了？看来又是屁股决定了嘴巴，心里想的事情，就变成新闻来热炒了。

外人看利比亚两派斗争，可以说是两只烂军在比谁更不烂。

卡扎菲的基本力量中，有来自于黑非洲的雇佣军。因为老卡梦想着搞一个非洲联邦国，所以扔了不少钱，在黑非洲拉关系。而他在黑非洲各国，也有不少军阀朋友。

一旦有问题，大把钱一洒，这里来几千，那里来几千，上万的人马就齐了。在非洲那样的地方，不像中国，要有点出息，怎么也得有10来万精兵。人家非洲，一个连长，带上百号人，就可以在一个国家搞政变了。

叛军可以依赖的力量，主要是基地组织，派往伊拉克和阿富汗同美军作战锻炼出来的小股力量。但是叛军的软肋，在于兵多而不精，人虽众，但是没有组织，各派势力面和心不和，颇像当年六国反秦，大家都作壁上观，没有一个项羽出来搏命。

现在大家打的主意，就不是自己努把力，而是希望西方可以出来干预，帮他们解决老卡问题。

而老卡，则表面很淡定，但底下非常勤奋，出尽招数，来分化叛军一方，可以说如果他不急于动手的话，应该颇有翻盘的机会。因为现在西方各国，在军事干预上还犹豫不定，如果他出手太重的话，被叛军和充满敌意的西方媒体，真的假的照片摆上头版，大打悲情牌，而迫使美国和北约出手，那就只有吃瘪了。

另一个就是利比亚的石油设施，不能遭到破坏。因为现在的国际油价，已经为全球经济的复苏带来了隐忧，最起码欧洲有再次陷入衰退的危险。如果这个时候，利比亚交战双方急眼了，拿石油设施当人质，那就是逼北约出手了。

这也是为啥这几天，叛军大造舆论，说是卡扎菲会拿石油设施出气，就是这个路数。

如果卡扎菲够狡猾的话，他就会保持战争在一个可接受的状态。保持零敲碎打的姿态，等着叛军力量的分裂，然后就拉一帮，打一帮。而在国际关注上，则等着沙特局势恶化，或者也门和阿曼先乱，从而把美国和欧洲的注意力转移。

有读者在伊朗，因此比较关心伊朗的局势。

谈伊朗的局势，先要介绍一个事情。那就是伊朗在开发核能的时候，没有依赖于自己的制造能力，而是靠德国西门子出的设备。

那么某一天，西门子派人和美国能源部，共同商讨如何防止被人找到软件的漏洞，而提高防护能力。经过这个技术交流，美国和以色列就彻底掌握了如何“保证”西门子设备安全的诀窍。

于是一个专门的病毒软件给开发了出来。这个病毒，一旦隐藏在了电脑里面，就会搜索这个电脑里面有没有西门子设备的控制程序。如果没有的话，那么就偷偷地将病毒复制，传染到其他的系统。

从这里可以看到伊朗人做事的糟糕之处。最起码自己内部有内奸，所以设备的资料被人家掌握了。另外就是必然有人把这些病毒带进来。其实想一想，伊朗的几个核物理学家，被人家炸死和炸伤，就知道伊朗的保安工作太水了。

那么这些病毒，终于成功地接近了伊朗的加速器，就干了两件事情。一个就是向中央控制系统发出虚假信息，让中央系统以为一切尽在国军的掌控之中。

另一个就是下命令，让加速器飞快加速，越来越快，然后就突然叫停。那么结果就很明显了，那就是你给汽车猛踩油门，然后突然踩一脚刹车，那就是车毁人亡了。

于是伊朗大概6千多个加速器，就有1千多个给报销了。而由于美国对伊朗的严密制裁，要搞来部件来修复，有比较困难。这样伊朗搞出核弹的时间，就被推迟了。

那么推迟到多晚？根据以色列情报部门的估计，伊朗搞出核弹，需要5年时间。那就是说，这个时间点是2016年。

2016年，是一个很有意思的数字。

因为俄罗斯的T50，中国的J20，和美国的F35，都大概以这个时间段，作为成军的时间。

而对美国来说，对伊朗的底线，在于伊朗马上组装原子弹。但是对以色列来说，则要更早。因此对伊朗核子计划的推迟，让美国和以色列的主战的鹰派和主和的鸽派，都有充分的时间，可以从容安排。

以以色列为例，政界的内塔尼亚胡，就是主战派。而他的三军总参谋长，就是主和派。美国也是一样，政界的一帮子，尤其是犹太人政客，像利伯曼和舒默等人，都是主战派，而军方的不少将军，反而是主和派。

对主和派来讲，现在也许还可以威逼利诱伊朗放弃计划，一旦你开始轰炸伊朗，那人家就铁定了心，不惜代价，非要把原子弹搞出来。

而对主战派来讲，就是需要时间。今年主战派的造势活动，相当于1998年对伊拉克战争的准备工作。那次是化了5年时间，等到合适的总统出现。而这一次，也是要为2012和2016年的白宫换人，早早做好准备。
