# -*- org -*-

# Time-stamp: <2011-08-25 12:20:30 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话65：这一次玩大了

[2011-02-26 02:54:32]


*现在全世界的乱局，要找的罪魁祸首，那就是美国的联储局。*

因为美元是世界经济的基础货币，因此美国的联储局，也是相当于世界的中央银行。

当美联储，乱发货币，那么世界上通货膨胀大行，就是意料中的事情。

第一个当然是0利率政策，第二个就是QE2。QE2的目的，是要把美国长期债卷压低。可是你压低的结果，就是人家大银行和大基金们，想赚钱不好赚，那就只好全世界寻找更好的回报。这么一来而去，这些钱，就跑去疯炒大宗消费品市场了。

于是国际粮价、糖价、棉花价、大豆价、玉米价，诸如此类，加上原油价，都呼啦呼啦扯风狂涨了。

中国自己内部的通胀，当然也有中国人民银行发币过剩的问题。只不过全世界就是一个地球村，每个国家，就是一个个坑。你美国最大的水龙头，拼命放水，再加上其他的日本啦、欧盟啦，一起放，你不自己放水，把自己的坑给填了，人家的水也会流过来，是不是？

虽然说中国是拼命管制资本账户流动，但是各种瞒天过海的伎俩还是有的。比如说某些企业，包括中国的国有企业，在中国收紧货币的时候，就可以通过人家海外分企业，去便宜借钱，然后就调度回来。

在你自己的通货膨胀压力，比别人高的时候，你自己的利率就得比人家高。当然，你和别人的差距，就比较大。那么对抗这个水往低处流的物理定律，难度就会大。

这个时候，必须实行的一个办法，是要保护你自己的优良资产，就是那些实实在在，可以下金蛋的母鸡企业，不要被人家放出来的水，给扒拉去了。

这些可不是上海的商业地产之类的。或者是美国纽约的商业地产之类的，当然可以让日本人大手笔露脸，然后几年后，连裤叉都没有的东东。

而是真正的实业的东东，就是每次中国企业想在美国购买，都被美国国会给否决掉的东东。

*所以中国出台美国标准的“反对你用稀释后的票子，来买俺的好家伙”法案，是适当其时的。不是老是说俺们中国不和美国接轨吗？那就好好接一次吧。*

其实中国干的其他事情，是俺在2008年就提议过的，大伙儿没有注意留意吧。一个就是中国手头的外汇，确实有不少回流了。另一个就是这些离开美国回流的外汇，有不少用来回购外资企业在中国的优良资产了。

中国对美国国债的兴趣大减，已经不是投资界的秘密。这个也是美联储印钱自己买的一个背景因素。

在《大国游戏》里面，俺谈到过一件事情。那就是当年美国和沙特阿拉伯关系恶化，导致了沙特阿拉伯从美国撤走资金，结果美国的应对方法，是通过爱国投资法案，把美国企业海外盈利，汇回国来的税率，从35%降低到7%。

这次奥巴马到加州和企业大佬们吃饭的时候，已经讨论这个方案了。

*本来联储局放洪水，用来淹没全世界的一个目的，是希望用高涨的通胀，来压迫中国按照美国的要求，把人民币升值40%。*

但是这个放水，导致了国际粮食价格的暴涨，开始打击全世界的贫困人口。第一个引发的副作用，就是 *中东和北非的乱局* 。

所以在G20会议上，美国财长盖特纳虽然大言不惭地向全世界保证，美国通胀压力不大（言下之意，俺们还可以继续灌水，来个QE3什么的，不达目的，绝不是收兵），可是目前乱局的蔓延，已经开始让美国人自己也坐不住了。

因此小盖向中国发出和平协议的喊话，就是如果你中国的人民币按照俺们的位置上来了，美国可以“帮助”监管大宗商品市场，以保证期货价格不至于不可控制。

在美国的七伤拳的拳风下，如果中国的七伤拳是，俺收紧银根，让经济冷却，放慢经济增长。不是说全世界有两个经济发动机吗？北美的那个已经歇菜了，那么东亚这个俺们也转慢一点，看你其他国家的经济如何恢复？

估计首先要跳起来的，就是加拿大、澳洲之类的国家了。

*即使是美国和欧洲，现在那点可怜的增长率，也是靠中国的投资需求带动。如果中国这里开始熄火，大家就只好双脚跳了。*

当然中国自己跑慢一点，也要看一下国内的就业问题。要把商品房的疯涨压住，就得把廉租房的建设给搞上去，这样的话，来个狸猫换太子，算是就业不受影响。

而且 *大力开发3线和4线城市* ，导致农民工们就近上班，也会影响沿海出口业的用工情况，然后就把工资水平给抬了上去。再加上人民币汇率的缓慢上升，油价上升带来的运费上升，各种原材料涨价带来的半成品价上升，再加上民工荒导致的开工不足而减少中国厂家之间的恶性竞争，都会让中国的出口产品，抬高价格，到美国去。

那么美国会不会迎来伯南克和盖特纳梦想的通货膨胀呢？

也不一定。因为美国的零售商们日子也难过，而且加上美国家庭经济困难，并且各种垃圾商品，家里堆得满满的，导致了硬需求不足。

*在这样的情况下，进口成本上去了，又不敢向顾客转嫁，会变成企业盈利变小。* 那么这些企业的反应，就是一个， *削减成本，继续裁员* 。反正，人家真正赚钱的时候，是感恩节之后嘛。
