# -*- org -*-

# Time-stamp: <2011-08-25 10:27:48 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话49：为啥要交联邦税？

[2011-01-25 15:59:53]


前面说到美国州政府破产的问题，其实比较麻烦，对美国普通人民的民生影响比较大的是市政府这一个层次。

先说说美国的社会结构，这样不了解的人，就会比较明了一点。

在美国的州之下，存在着一级政府，叫做County，有人翻译成县。其实这个县如果对应的是日本那个县，还说得过去。但是对中国人来讲，就会产生误解。

其实 *国的县，比较类似于中国古代的州，或者是郡* 。通常是一个County下面，有7-8个城市。也可以大致类比于中国的地区，然后下面就是一堆县级市那样。

然后在县下面，就是城市。这两级政府的主要税收来源，一个是 *物产税* ，一个是 *销售税* 。

因此当政府财政收入有问题的话，就是在这两个税上面打主意。

物产税，通常是学区资金的来源，就是说整个地区的公立学校，靠这些税收来支撑。

但是这个税收，有赖于地产市场良好。你要是房子不光不涨价，而且还有越来越多人断供，那么这个部分的收入，就会大受影响。

而销售税，比如说最近俺们这里，就涨到了9.75%，而且还想涨0.50%，差不多是十分之一了。这个税，依赖于大家消费，你经济不好了，大家不肯花钱了，或者你税上去了，为了保证自己的收入，不少收现金的商家，比如说餐馆之类，就偷偷少报，也会影响到收入。

收入不够，支出又很大，于是许多地方政府，考虑削减支出。

但是大家要知道，通常和大家生活有关的事情，是在这一级政府完成的。

比如说 *学校的好坏* ， *警察治安* ， *在街上收垃圾* ， *医疗服务* ， *消防车来救火 *等等，都是大家切身相关的事情。

在俄亥俄州的Ashtabula县，面临的就是这样一个情况。这个县，本来有112名警察，先是第一轮削减到70名，然后第二轮削减到49名。

整个县是1900平方公里，现在只有一辆警车。警察局说，俺们没有巡警，街上是一个警察也看不到。俺们只能对即刻发生的犯罪采取行动，你要是财物犯罪，那是没得理了。

本来还有缉毒队，有刑侦队，现在都给撤了。只有一个警员负责罪证处理，就是说你的家里被人爆窃了，你的汽车被人偷走了，都没有人可以处理。唯一的警员，就是帮你出一个报告证明，你可以拿出找保险公司索赔。

这个是很多城市都出现的问题，就是治安越来越差。

在去年3月，印第安纳州著名的普度大学，由土木工程师们为各个城市开了一堂课程。这个课程的名字，就叫做“Back to the Stone Age”，神马意思？就是“回到石器时代”。

那么这个课程是教什么的？很简单，就是教大家如何把铺好的，但是维修费用比较高，现在开始失修，到处都是坑的公路，给打成碎片，回到维修费用低的石头路。

这个就是现在美国流行的基建工程维修方法。比如说密歇根州，已经把50英里的柏油马路，给基建成了碎石路。

发生在小城市的事情大家可能不关注，但是在俄亥俄州的辛辛那提市，已经开始缩减收垃圾和除雪服务。这一次美国东部到处大雪纷飞，搞得很狼狈，比如说纽约市，就是因为垃圾工人被大幅裁减的原因。

当然大家还记得，为了给纽约911事件后的救护人员赔偿的官司，是花了很大一笔纽约市的城市预算的。其中还有过亿的资金，是给大律师们拿去零花的。

在得克萨斯州的达拉斯市，公共地方，比如说公园里面的垃圾，政府已经不再处理。

另外的一些地方，比如说密歇根州的Flint市，88个消防员给解雇了23个，有两个消防局给取消。

想一想吧，要是你家附近的两个消防局都关门了，然后着火了，消防员要从比较远的地方开车过来，这一耽搁，路上多用的10来分钟，就是人命关天，就是巨大财产损失。

前面一些城市，还是回到Stone Age， 有的城市就是回到Dark Age （中世纪黑暗时代）。比如华盛顿州的Shelton市更绝，整个城市有860盏街灯，现在是关掉了114个。晚上城市的街道上，黑咕隆冬，看你还敢不敢上街。

也有很多城市，就是停止的公交汽车服务，还有的就是关闭了图书馆。

受到打击比较大的是学校，教师被解雇，学生要减少班级，搞大班制度。学校同时减少上课的天数。

据美国城市联盟的报告，大概63%的城市，会大幅削减社会治安（削减警察），大概60%的城市，会大幅度削减社会服务（削减消防等等）。

不是说美国联邦政府不知道这些城市的困境，在去年8月，奥巴马政府给了260亿美元，部分用于保住教师们的职位。但是这点钱，只是堤坝上面插一个指头去防洪。

据专家们预计，现在的地方政府，还没有完全明了金融危机带来的房地产问题，对他们的财政的真正影响。因为这些地方政府，对物业税的评估，是每三年一次，要到了2011年中期的时候，他们才知道问题的严重性。

另外一个要命的问题，就是美国的很多地方的基础设施，已经到了崩溃的边缘。

大家都记得2007年明尼苏达州的一座大桥突然坍塌，导致了13个人死亡，145人受伤。根据美国土木工程师协会的估算，美国在基建上面，光是高速公路和桥梁，就欠了1万6千亿美元的建设账。美国的桥梁中间，有25%结构有问题，随时会倒塌。

其实比这些更要命的，是美国的河堤。比如说俺们加州的不少河流，都是像黄河那样的悬空河，靠堤坝那护住下面的农田。

但是这些堤坝因为资金缺乏，年久失修，如果一旦碰到大风暴，堤坝一决口，就麻烦大了。因为这样的结果，就会导致旧金山湾区的海水倒灌，那么包括硅谷在内的七百多万人口，就没有淡水喝了。

不要以为这是危言耸听。当初新奥尔良的堤坝，号称可以抵御五级飓风，结果在三级飓风的打击下，就彻底悲剧了。

大家看到了这么多的问题，都是因为没有钱，尤其是地方政府没有钱的缘故。但是又不能加税，大家已经交了不少税，不过大部分被联邦政府拿去了。

然后联邦政府，就把这些钱，拿去给华尔街发红包和奖金了，还有拿到阿富汗和伊拉克去建设民主了。

于是人们开始问，干嘛要交联邦税？
