# -*- org -*-

# Time-stamp: <2011-08-25 20:16:04 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话71：能源安全和核能应用


[2011-03-13 13:59:05]

前面说到中东和北非的乱局，导致世界能源市场的动荡。

对很多人来说，尤其是华尔街的人来说，你利比亚杀来杀去，死它几百万人，人家都不太在乎。因为利比亚对全球能源的影响，并不是决定性的。

*真正对世界能源有影响，那就是沙特动荡。* 按照华尔街的说法，如果沙特动荡，那么你就要考虑一下石油2百美元一桶，会对经济有什么影响。

当然如果你对计算感兴趣的话，那就要多用一些数字。华尔街的建议，是你应该一直算到5百美元一桶的价格。

其实要摆脱对中东和北非石油的依赖，除了俺建议的开拓周边国家的石油能源，比如说南海和东南亚等等，或者说增加天然气的运用之外，还有一个办法，就是要加大核能的比重。

但是在这次日本经历的大地震中，现在碰到的一个大问题，就是日本福岛第一发电厂出现了可能的核岛熔化而出现核泄漏问题。

这个估计会对中国的核能利用产生不是负面影响。

因此这个系列，就是想对大家进行核能运用的初级科普，免得大家被“有良心”的XX学家们，给卖了拐了。这个XX，可以是历史、金融、经济、地震等等，这个你懂的。

福岛第一核子发电厂，总共有6个反应堆。这次出了问题的第一反应堆，和开始要出问题的第三反应堆，是通用和东芝的产品。第二反应堆和第六反应堆，也是通用产品，第四反应堆，是日立的产品，第五反应堆，也是东芝产品。每个反应堆的发电量相同，第一是46万千瓦，第二到第五，是78万千瓦，第六是110万千瓦，分别在1970，74，76，78 和79年落成，上网发电。

这些反应堆的设计，第一反应堆是BWR-3型，第二到第五是BWR-4，第六是BWR-5型。

在核能技术上，大家可能都听说过重水堆和轻水堆的区别。其实主要的不同，就是你用来做中子减速器的东西不同。一个是含有氧化氘的水，称为重水，一个是不含氧化氘的水，称为轻水。

这两种方法各有所长，但是 *重水的一个主要功能，就是发电之后的副产品，是可以用来制造核子武器* 。而轻水堆，就不会有这个担忧，因此是很多民用核能的主要选择。

在轻水堆中，大概是两大类型。最常用的一种，叫做PWR，也称为加压堆。而日本福岛的是另一种类型，也称为沸腾堆。

其实这两种类型差距不是特别大。要理解这个，你要知道，所有的核能，你必须有一个东西，叫做反应堆。这里就是你的核燃料在这里进行核裂变。对这个反应堆的理解，就是说里面有核燃料，再加上控制棒等等，来进行可控制的核反应。

那么在核反应之后，产生了大量的热量，你必须把这个热量给带出来。那么所谓轻水，就是靠水泵给打进去，然后在反应堆里面，变成了蒸汽，在输出来。

压力堆和沸腾堆的主要区别，就是沸腾堆的轻水，是会沸腾的。而压力堆，是靠压力保持高温，是不需要沸腾。

那么这个蒸汽出来之后，通常是通过两级的涡轮机，先是高压涡轮机，然后压力降低的蒸汽，就通过低压涡轮机，来产生转力。

*那么这个转力，出来干什么呢？有两个用途，一个是接上发电机，用来发电机。*

*另一个功能，就是接上螺旋桨，作为交通工具的动力。现在的用处，基本上是两个地方，一个是核动力航空母舰，一个是核动力潜艇。*

所以从理论上来讲，你的核反应堆，如果可以做到微型、安全、常温常压运行等等，你是可以搞核动力飞机、核动力汽车，或者搞一个居住小区的核电小站。

估计看到这里，有不少人屁股开始坐不住了，呵呵。

回到日本福岛的问题，就是你轻水堆里面的轻水，其实是一个内循环。就是推动完涡轮机之后，这些蒸汽就进了冷凝器。这里就必须进行另一个热交换，就是另外一个冷水，就将这些蒸汽的热能带走，然后人家蒸汽，又变成了液体，再通过水泵，给打进反应堆去，如此往复，以至永远。

*那么这个第二次热交换的外循环，在福岛就是用了海水来实现的。*

好了，等到地震了，就出现一个问题，那就是电力中断。这个问题，一出现，就使得你抽海水进行外循环的水泵，和将液体轻水推到反应堆的水泵，都不工作了。

那不是应该有后备发电机吗？是的，后备的柴油发动机是工作了一下子，就是几分钟吧。结果就是海啸来了，把柴油发动机给水淹七军了。这个时候，最后的电池，就开始发力了。

可是这个电池只有8个钟头的力气，这样的话，慢慢就没有办法去冷却反应堆了，这个时候反应堆里的温度越来越高，到了不可控制，那就要熔化了。一熔化，气体在里面一爆炸，反应堆的金刚壳子一化掉，那么核辐射就飘出来了。

而且一飘，就可能飘过太平洋到美国来。现在日本的最后一招，就是灌海水进反应堆，看可不可以把核燃料给冷却下来。

如果看一下第二代核电的表现，现在只发生了三场大事故，分别是 *1979年美国的三里岛* 、 *1986年苏联的切尔诺贝利* ，和 *日本福岛* 的这次事件。

虽然说数量上比较安全，但是因为大家都是谈核色变，一个事故的危害程度也比较大，因此如何搞出新一代的技术，就是说核电站第四代，是各国努力的方向，而中国在这方面，也加快的研发步伐，和投注了大量资金。

可以说大概从2020年到2030年，应该是这些技术开始成熟，可以运用的时间段。
