# -*- org -*-

# Time-stamp: <2011-08-25 10:19:14 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话48：如何让州政府破产

[2011-01-22 16:10:56]



最近在华盛顿比较热门的话题，其实不是中国主席胡锦涛访问美国。

从11月开始，美国政府里面的一些人，就开始考虑如何让美国各个负债累累的州政府，宣布破产。

这些政府面临的财政问题，不是短期缺钱的问题，而是长期性的结构问题。

其中最主要的是政府退休公务员，就是那些老师、警察、消防等等前政府雇员的退休金，现在找不到着落去解决。

但是美国的州政府，从州宪法来讲，是怎么也要付这些退休人士退休金的。除非，要有个办法宣布州政府破产，就可以赖掉这个责任。

但是按照美国的宪法，各个州是主权独立的“国家”，就是说不可能按照美国联邦破产法的保护，想三大汽车那样，宣布破产，然后由美国联邦政府注资去解决问题。

因为要这么做，你就得修改美国联邦宪法和各州宪法，而这个又是玩不了的游戏。

所以现在有一种想法，就是通过国会建立一套州政府破产程序，然后让各州宣布破产，赖掉责任，然后再赖掉州债，然后有联邦注资，就是说美联储印票子，搞一个重组。

在2008年的时候，很多州因为财政困难，向联邦政府借了一大笔钱发工资，本来以为经济马上反弹，就可以通过税收增加来还钱，没想到这两年差强人意，而现在还要开始还借钱的债务，真是雪上加霜。

各州的政府雇员已经听到风声，开始组织起来，在国会议员里面，寻找自己的同盟军。他们放出的话，就是你州政府宣布破产，不关俺事，但是要是想动俺们的退休金，你就走着瞧吧！别怪俺们没有事先警告你。

美国的政府公务员制度，颇有一点中国的顶替的传统，就是老一辈的公务员，其子女也有不少回来混这个位置。因此当老人家们的退休金成了问题，就会同样影响到现在当班的，比如说警察叔叔们的心情。

前一阵子俺们硅谷所在的地方的圣荷西市，因为要投票讨论警察叔叔们的退休金问题，结果警察局发出劝告信，警告投票的人们，如果你们惹到了警察叔叔们的霉头，后果自负啊。因为警力不够，大家士气低落，要是发生啥子事情，比如说有人到你们家用枪化缘，不要打911电话，俺们没兴趣知道详情。

所以最后美国州政府和各县市政府的财政窟窿，要到底怎么来填平，才不会引发社会不稳定，就看美国的经济可不可以复苏了。

有读者问， *美国经济要如何发展，才可以解决就业问题？其实俺在以前已经说过，大致就是3%的增长率，就会保持失业率在现在这个10%的水平。如果达不到这个数字，失业率会继续恶化。*

要想让美国的失业率下降，就必须保持5%的增长率。而这个增长率，大概现在没有人敢做这个预测。

前面说到，其实美国的经济掌控人，选择货币政策，是因为财政政策的实施比较难，所以选择了货币政策这个比较容易的路子，比较美国经济，主要是被几大金融机构控制。

而中国政府选择财政政策，也是因为权力集中，在财政政策上比较顺手。中国的资本市场，也不是很完善，依赖货币政策，不一定能够达到政策目的。因此大家都是贪一个容易，倒不一定背后有多少高明的理论支撑。

当然财政政策和货币政策，各有利弊，主要在于你依赖的人，去推行你的政策，肯不肯以社会和全局的利益为考量，要是大家都是以私利为先，为了个人和小集团利益，而牺牲大众利益，那么你政府的官员，和银行的大亨，都会让你的政策，南辕北辙。

从这个角度来讲，美国不是没有计划的经济，而是人家的计划，不是在政府部门里，而是在华尔街的圆桌会议中实现的。

所以说美国也是有政治局的，不过这个政治局不是在白宫，而是在华尔街。美国也有发改委，这个发改委，就是高盛集团。

虽然美国各大公司董事会里面超过三分之二的董事，都是金融界的人士，但是在1995年的时候，美国最大的六家金融集团的总资产，只占美国GDP的17%。

但是在2007年之后，这个比例，增加到了55%。结果就是在2008年金融危机发生了，那么这些金融家们就要悲剧了？

不是。在布什政府和奥巴马政府的大力救助下，在2009年这六家金融集团的资产，对美国GDP的比例，上升到了64%。

而且对金融界最有威胁的人，前美联储主席沃尔克，被奥巴马政府给踢出了局。反而，曾担任过克林顿政府商业部长的戴里，出自华尔街的大摩，将出任奥巴马的幕僚长。

这个安排，表明的两个变化，第一个是和华尔街有密切关系，开始在华盛顿重新抬头。第二个就是美国政府部门前一阵子，装模作样和装腔作势，要拿华尔街肥猫开刀的架势，应该顺利收场了。

那么下一个问题，就是 *靠华尔街主导的美国经济，如何走出复苏？*

曾经和一位银行家朋友谈论过这个问题。他象其他有远见的朋友们一样，提出的只有一个解决方法，就是 *从中国大规模移民* 。

他觉得要是移民两千万中国人来美国，那么就可以带动美国整个经济的发展。

其实想一下，如果每个移民来的中国人，只要带50万美元，那么美国的投资和市场，都解决了。

不过俺认为，这些人再拖家带口，七大姑和八大姨的来一下，就折腾1亿人过来了。中国少一亿人，不是什么大事情，而美国多出一亿人，就是中国人占25%，美国白人怕不怕？

朋友认为，那么很快墨西哥和其他的南美洲移民在美国就要超过25%，如果这个是唯一选择的话，是不是中国人让人安心点？

他的看法，这个是美国经济重振的唯一办法，除此之外，别无出路。

俺倒是认为，在加州和美国西海岸，倒不是一个问题。最近北加州的两个大城市旧金山和奥克兰，都出现了华裔市长，如果中国崛起的势头不减，华人大规模移民来加州，倒不是没有出现的可能。
