# -*- org -*-

# Time-stamp: <2011-08-25 12:04:42 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话63：埃及革命的背后（四）

[2011-02-24 13:27:55]

[和谐]


其实，当时米洛舍维奇的支柱里面，有两根已经在无意识之中干了。一根就是年长者，是米洛舍维奇的主要支持者。可是，当16岁的年轻学生们不断被警察抓起来，被政府指责为恐怖分子，已经慢慢地让祖母们很不愤了。

另一根就是警察队伍。波波维奇的年轻人们对警察叔叔非常尊敬，经常在电视摄影机的镜头下面，手捧鲜花和糖果，给警察叔叔们送去。而且每次要和警察叔叔对抗，大家都不是骂警察叔叔（比如说，香港的抗议学生们那样），而是为他们欢呼。

欢呼的镜头，大家可以在埃及军队进解放广场的时候看到埃及学生们的动作。其实，你只要安安心心地让军队到达人家的站岗地点，让人家完成如山倒的军令要求，又不要去围追堵截军队人员，不要把人家无辜的士兵给杀了，军队也不会吃饱饭没事干，拿你当枪靶子。

给警察叔叔送花的镜头，在巴林可以看到。虽然警察们用子弹作为回礼，不过，相信会影响未来的政府支持率。

于是，缅甸学生们把自己放到了缅甸社会的各个阶层里，开始了画图工作。这个是波波维奇的主要战友迪吉诺维奇的发明，就是把对社会有影响力的各个阶层，进行一个评判，看他们想要得到什么，和对政府的支持度有多大。

这个工作的主要任务，就是在相当长的一个历史时间里面，你搞清楚那个阶层，对政府的支持，晃动了。然后，要搞清楚，在缅甸历史上的那个事件，导致了这个晃动。

说白了，这个就是每个中国人都明白，毛泽东主席搞过的《湖南农民运动考察报告》中的阶层分析。就是说谁是俺们的朋友，谁是俺们的敌人。然后，你就根据这个报告，去发动革命的主要队伍，去寻找革命的同盟军，然后，去统一战线里面团结可以团结的阶层。

结果就是缅甸的受训者们很快把图给画出来了。学生们想要私人的学校。商人们想要可以信赖的银行系统。农民们想要国家的粮食补贴。

这些要求里面，有哪些东西没看到？民主！人权！看到没有？没有人要民主和人权！

*对人民来说，民主、人权就是狗屎。* 波波维奇很直率地告诉他的学生们。没有人对这些东西放个屁。你听到那些反对党领袖大言不惭地天天发表演说，说民主啊，人权啊，都是扯蛋。

因为这些东东，对老百姓没有屁用。记不记得甘地的食盐游行？人家的诉求，不是「英国佬滚出印度」，而是俺们要自己做盐。

下一步就是如何行动了。不是那种声势浩大，引得外国媒体围观那种行动。而是非常非常小，一步一成功，风险非常小，成本非常低，危险也不大的行动。

马上有学生说：要是我们大家某一个时刻，在窗户那里点燃蜡烛，当然政府没有办法逮捕一万人，但是，总是可以找到一个，抓他的全家，来杀鸡给猴看，是不是？

当然了，导师同意这个看法。那是因为你的动机是政治性的。你可以搞不政治性的嘛。比如说，你政府是不是电力供应不够？于是，大家想到了一个问题。因为仰光政府已经不收垃圾了，那么，俺们可以搞20个年轻人，去收垃圾，然后，搞到更多人加入，然后，找到市政府，交一个影响力大的人士签名的请愿信，告诉政府，这是你的问题。

这个法子得到了导师们的赞赏。其实，这个就是发展平行的管理机构，取代政府的功能。这一招叫做「米奇尼克战术」，是当年为波兰工会量身订做的。对缅甸来说，你们当年不是在2008年的「拉尔基斯台风」之后，参与了自发的清理尸体运动？好，如果市政府对你们的清理垃圾运动，不理不睬的话，怎么办？

俺们就把垃圾扔在市长的眼皮底下，有缅甸反对人士很爽地说。

大师笑起来。你还是可以选择低风险的办法，就是给垃圾拍照，拿去给政府看。

另外一个组讨论的结果，就是要开展一个光脚行动，来纪念「袈裟革命」的和尚们。这个主意就是要以100个年轻人开始，用电邮或者社交网络把他们组织起来，大家光脚去公共场所。

因为庙里要脱鞋，所以，就先从庙里开始。然后，在地上抹上颜色，结果就可以看到多少脚印，知道有多少人参与了。

可是，政府来抓你，怎么办？大家就带着一双坏了拖鞋，拿给警察看。或者说，俺准备跑步呢。

但是，人家看到了你的脚印，就跟着脚印，去抓你了。那就晚上做，这样，你搞不清楚谁干的。

不过，人家警察没那么笨，这个还是很容易被追踪到。最后，灵机一动，不如让猫狗们来干？在缅甸有很多流浪猫和流浪狗，俺们给他们东西吃，然后，前面放着颜料，它们就会展开光脚行动了。

大家即刻容光焕发了，民主猫狗斗士！多刺激啊。

最后的训练内容，就是让缅甸的学生们观看2008年，由丹麦人拍摄的记录缅甸「袈裟革命」的记录片。其实，这个片子，大家以前都看过，还为自己是其中的参与者而激动万分呢。

但是，经过CANVAS训练之后，大家的视角大不相同了。俺们确实好勇敢，好感人，可是，可是，

俺们怎么那么死蠢啊，那么没脑啊，那么不负责任啊！

学生们的观感是，那样的革命是不会成功的。因为没有组织和纪律，大家一冲动地上了街，提出的革命目标是无法达致的。

对，导师们首肯到。现在，你们开始明白，俺们说的非暴力运动，和你们干过的是彻底不同的。之后，你们就知道应该怎么干了。
