# -*- org -*-

# Time-stamp: <2011-08-25 20:46:52 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话76：军权、君权和神权


[2011-03-26 15:14:12]

上次提到这个闲话会谈一下利比亚和法国，所以算是信守诺言，就从法国谈起。

如果你在谷歌上面查询“法国军事胜利（French military victory）”这一句英文，谷歌会提示你说，“你是想找法国军事失败吧。法国军事胜利，没有一个文件吻合。”

所以大家说笑话，这次法国在利比亚用兵，是要寻找拿破仑时代之后的法国第一场胜利。

其实这个是有点夸张了。人家法国好歹在第一次世界大战中，虽然被人家德国兵临巴黎城下，但是最后还是战胜者。可是因为美国人不地道，不玩以前大家搞同盟，你出人我出钱的把戏，而是玩你打仗我借钱，你输赢俺不管，只收钱的游戏。

本来英国是出钱给法国打仗的，因为任何保证欧洲大陆各大国内斗的游戏，都是对英国利好。可是因为英国自己又从美国借了不少钱，所以只好从法国追钱。这样下来的结果，就是法国在第一次世界大战中，是胜利者。可是做胜利者，要还钱，比法国在普法战争中被打败，赔的战争赔款还要多。你看这胜利者当的多窝囊。

所以后来法国没有办法，只好逼着德国人多赔款，结果就是人家德国人就抬出了一个小胡子出来，让天下再多乱了一次。

可以说 *法国佬在第一次世界大战算是被美国人给坑了。那么这次利比亚动武，倒是有点法国人坑美国人的意味在里面。*

因为对美国人来说，和卡扎菲的恩怨情仇，其实已经差不多烟消云散了。卡扎菲本来就成了美国在北非合作对付基地组织的伙伴，而基地两个组织，就是在今天对抗卡扎菲的东利比亚运作，而且人家东利比亚，是向伊拉克贡献了最多和美军作战的穆斯林海外兵团。

所以对美国人来说，其实穆巴拉克也支持过，对抗议民众开火的也门和巴林政府，美国也没有什么怨言。但是苦于舆论压力，美国不得不有所表示。

其实对美国最好的局面，就是大声咋呼，嚷嚷着要搞禁飞区，然后在联合国一表决，最好就是俄罗斯，或者中国，投否决票，然后美国就可以大声指责，俄罗斯和中国冷血之类，俺要救人，你们无耻地拉着俺不让救，是可忍，孰不可忍！

这样把老大的责任，从肩膀上一卸，偷偷地捂住嘴笑着就回家了。

因为对美国来讲，卡扎菲砍不砍人，真是无关痛痒。美国在利比亚的石油利益，只不过一天五万桶，真是塞牙缝的数字。如果 *利比亚搞乱了，成了索马里，那么基地组织趁机坐大，那才是美国头痛的地方* 。

当然对法国来讲，情况大不相同。法国要搞的地中海圈俱乐部，最捣蛋的就是卡扎菲。如果法国可以把卡扎菲搞下台，让现在的反叛军掌权，自然法国就对利比亚未来的政治立场，起决定性的掌控作用。

就算卡扎菲没有倒，如果可以借美国的军力，把卡扎菲的力量削弱，那么一个东西分裂的利比亚，也会对法国的整合起大利，因为这就叫做 *分而治之* 。

至于东利比亚可能的基地组织兴起，反正你只要不对法国动手，去打以色列或者美国，又干俺法国佬屁事。而且到现在为止，到巴黎搞事的人，除了阿尔及利亚的反叛组织，还没有非洲的其他人。

不过如果巴黎地铁在未来的一段时间里，来一个大爆炸，俺倒是一点都不奇怪。如果卡扎菲的军情部门，去搞这么一下，来报复法国，有可能。但是另外一个可能，就是拉登大叔的基地组织，到法国搞一把大手笔。

这样的话，拉登这个卡扎菲的大死敌，就可以趁机嫁祸给卡扎菲，然后让自己的两个仇人之间的厮杀升级，最好杀得不亦乐乎，两边都大伤元气，那才叫爽呢。

有种看法，认为现在美国是希望借利比亚的事情，吸引大家的焦点，就会转移对沙特和巴林这个美国软肋的关注。其实不然， *在“国际社会”的媒体的一致努力下，全世界不明真相，尤其是西方国家那些自以为是，以为自己什么真理到在手的广大群众们，已经被忽悠得立场坚定，旗帜分明了。*

那就是在其他国家发生的，是人民要求民主反对独裁的正义合理行动。但是在巴林的绝对不是。在巴林发生的是，伊朗在背后当黑手的，企图依靠什叶派教众，打击逊尼派教众的信仰冲突。

所以在巴林开不开枪，俺美国管不着，教派冲突啊，千年历史啊，不好乱拉架了。

不过这种表述方法，在西方舆论和民众之间，可以轻易地得到共鸣。但是要命的是，这种定义，就把伊拉克给拉进浑水里面来了。

其实伊拉克，尤其是其什叶派的中心纳杰夫，比伊朗对全世界的什叶派教众，更有权威性。

虽然说伊拉克真正有民众支持基础的年轻宗教领袖萨德尔，一直对西方，尤其是美国，敌意甚浓，但是什叶派当之无愧的宗教领袖西斯塔里一直比较温和，这次也被逼出来表示不满。再加上黎巴嫩的真主党领袖拉斯努拉也出来发话，这些大佬的态度如何，对中东的其他国家，比如说沙特、也门和约旦，甚至叙利亚，都会产生重大影响。

谈起什叶派新月带的兴起，不得不重提一下令美国人吐血的伊拉克战争。

美国在伊拉克战争上，明码上打的虎皮，就是要搞美国独霸的大中东计划，表面上要搞“民权为主权”的游戏。

*而中东和北非的所有国家，基本上是三大类型。*

第一种是埃及、利比亚、叙利亚、也门、和伊拉克这样的“军权为主权”国家。第二种是沙特、约旦、阿尔及利亚、巴林和科威特等海湾小国这样的“君权为主权”国家。第三种是伊朗这样的“神权为主权”国家。

如果说当年纳赛尔领头，伊拉克的巴克尔和利比亚的卡扎菲跟进的第一次穆斯林革命，是用“军权”来推翻西方控制的“君权”，那么现在面临的第二次摆脱西方支持和控制，针对各国自己的“军权”和“君权”的革命，会不会带来“神权”的大行其道，是非常值得大家的关注。
