# -*- org -*-

# Time-stamp: <2011-08-25 09:40:43 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话43：鲲鹏展翼和飞龙在天

[2011-01-13 06:10:48]

今天先抛几个书袋。

《庄子》逍遥游中说，“北冥有鱼，其名曰鲲，鲲之大，不知其几千里也。化而为鸟，其名为鹏，鹏之背，不知其几千里也，怒而飞，其翼若垂天之云。”

《易经》乾卦中说，“飞龙在天，利见大人”。

*要了解中国的历史和文化，这两本经典著作，不能不明察。*

在飞龙在天之前，是什么？先是潜龙勿用，说的是龙潜于深渊，应忍时待机。是不是挺像那句韬光养晦？

然后就是见龙于田，君子终日乾乾，夕惕若，厉无咎。

然后就是或跃在渊，无咎。说的是见机行事，把握时机。

而庄子说的，则是庞然大物，在地上扒拉过日子的鲲，有朝一日，变化为鸟，一飞冲天，怒而飞的情景。

看了这两句，不知道大家对美国国防部长萝卜头盖茨的历史垃圾桶和民族韧性有何评价？反正英国人说，你啥都可以去和中国人比，但是千万不要去比两样，一个就是 *韧性* ，另一个就是 *历史* 。

盖茨说，1970年代，关于美国衰落的话他听得多了，可是那些小瞧美国的国家（就是指的是苏联和日本）已经躺在历史的垃圾桶里面了。你不要小瞧俺美国的韧性啊。

这个警告是说给中国领导人听的。

美国外交杂志，却有不同看法。

外交杂志发表文章说，这一次狼是真的来了。

因为美国能够战胜苏联，一大原因是经济是苏联的弱项。而且当时苏联的东欧自己成为一个体系，和西方各国经济老死不相往来。而且苏联经济上超过美国，难度比较大。

因为美国能够战胜日本，原因是日本虽然经济很强，但是经济实力大于美国也是不可能。因为日本的人口基数小，只占美国的三分之一。要是日本经济向美国看齐，日本人均收入必须是美国的三倍。

*有可能吗？没有。因为日本缺乏资源和市场，两头在外。政治、外交和军事上，是美国的殖民地。从殖民地抽血而补养自己，是殖民主子天经地义的行为。*

所以日本就这样给抽进了历史的垃圾桶了，因为日本历史是俺们美国人写的。

从这个角度，理解1980年代，日本有战略学者，希望靠日本的经济实力和技术领先，结合中国的人口规模、市场潜力和军事（核子武器）、外交（安理会常任理事国）地位，打造一个中日国，来抗衡美国，还是颇有远见的。

但是今天的中国，是真的狼来了，是披着件人畜无害小白兔的大灰狼。这个是外交杂志的结论。

因为中国的人口基数比美国大四倍，所以中国的人均收入到了美国的四分之一，那么整体经济规模，就可以和美国抗衡。

那么因为这个人口而形成的市场规模，当中国花同样数额的钱去开发一个相同的技术，分摊到人口上面，就比美国的成本要低。

*而成本就是打败对手最犀利的武器，不论是在民用还是军用技术上。*

因此从未来的发展上，中国在科技研发上的优势，是可以打败世界上任何一个竞争对手。

除了研发分摊的成本低外，你维持的成本也不高。比如说如果中国的一架歼20和美国F22同价的话，那么分摊下去的费用，也是中国要低。

而在研发更重要的一个环节，那就是研究人员上面，人口基数大的好处，就是你一个科研人员，俺可以有四个科研人员。

当然你如果象印度一样，空有人口基数，而不好好搞教育，那就是100个文盲，去竞争人家一个博士生，那也是无用。

另外就是如果你自己虽然重视教育，但是很多优秀的学生，你贡献到人家国家去，比如说美国科技工程专业的博士生，有60%来源于外国，里面很多来自于中国，那也是在减低你这个竞争优势。

与附近认识的一些来自中国的工程人士们谈到J20，有不少人都不以为然。总体看法，就是你老共那点水，还敢跟人家美国叫板。

人家美国，那才叫如何如何。

*这大概是中国这二十来年在教育上的失败，教育出了一大批对自己民族和人种缺乏自信心的人士。*

看这些朋友们的基本态度，相比于从香港、台湾、新加坡、韩国和日本看到的评论，大概都是比较类似。就是 *这近百年来，被西方政治统治和文化洗脑之下，已经丧失了一种文明和文化的自信心。*

从这个角度来讲，歼20的出现从单纯的军事意义上很重要，但是在民族自信和文化重建上的意义，则非常不同凡响。

因为这一次，俺们可以看到 *中国出现了一大批科技领军人才，堪称为民族的脊梁* 。

*杨伟、甘晓华、张立同、黄伯云等等在中国科技战壕里面，辛辛苦苦挖坑的人，才是这个国家不断走向进步的主要原因。*

正如当年新中国建立的时候，也是有少数的中国科技人才，对这个民族和文化有信心，才搞出了 *奠定中国大国地位的两弹一星* 。

那些俺们耳熟能详的名字，钱学森、邓稼先、王淦昌、钱三强、周光召等等老一辈民族精英的旗帜，终于在这一代人中间，有了继承人了。

一句话， *中国人是有能力的，只要中国各界的人士，抛弃五四运动以来，自我阉割的民族自我歧视倾向，扔掉造X不如买X的心态，抵制国企买办们（无论是民用的美日无敌论，还是军用的俄式先进论）的忽悠，中国下一个十年，将会充满惊喜，年年井喷。*

飞龙在天，鲲鹏展翅。
