# -*- org -*-

# Time-stamp: <2011-08-25 09:33:59 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话42：中国威胁论和美国国防预算

[2011-01-09 17:34:24]

提醒中国政府，注意信息安全，这也是俺年初在谷歌事件上，发表了一系列博文的意思。

当然估计希拉里的攻势失败之后，谷歌估计会放低身价，装出一付不再理政治，只想赚人民币的样子，希望能够偷偷的回村，打枪的不要。而面书说不定，也想悄悄地混进去呢。

前一阵子大家都知道，就是维基泄密颇有点让希拉里端起石头砸了自己的脚的意外。

现在美国司法部在做一件事情，就是要把他们心目中的维基“恐怖分子”的私自秘密，全部给拿到手。其中一个就是在推特上面的私人信箱里面的东西。

而被追查的一个女人，原来是冰岛这个国家的国会议员。

这就出了一个问题。人家这个女议员没有在美国犯法，因此美国政府其实对她并没有法律上主权，去拿她私人的东西。

但是问题出在她在推特上注册的账户，因为推特是美国的公司，那么就变成了美国政府的管辖地了。考虑到上次推特为了满足美国政府要求，支持伊朗的颜色革命，而变更公司的运作，那么这样的问题就比较麻烦了。

那就是你任何国家的公民，如果依靠美国政府控制的高科技公司，比如说谷歌、推特、面书等等，其实完全没有任何隐私可言。

美国公民反而因为有法律保护（虽然只是纸面上的，随时可以被爱国者法案给推翻），还可以应对一下。而外国公民又不受美国法律保护，就因为用力美国商业公司的产品，就变成了任意对付的目标了。

所以为啥在欧洲，人家各个国家开始要搞自己的信息主权安全，就是这个道理。

看到这两天，网上的军迷们亢奋异常，对J-20赞不绝口，心里嘀咕， *大家起哄些啥子嘛？*

平心而论，J-20不是什么新的东西，就是一个F-22的对手版嘛。

俺之前曾经发过帖子，谈到中国的WS15发电机，接近了美国90年代初的水平，其实就知道第五代战斗机，那是马上就要亮相了。

*中国的发动机制造，主要软肋是工艺水平。* 通过工艺提高，那么自己的发动机达到推重比10的水平，应该是指日可待的事情。

*那么J-20的横空出世，有什么作用呢？*

就是把中国隔壁的几个宵小，估计给吓个够呛。以现在中国的发展速度，J-20也许在2015-17年就可以成军，那时候估计美国的盟国们手上拿到的缩水版F-35，就没有太大的用处了吧。

看到台湾一帮家伙，说是要赶紧引进F-16C/D，心里不由好笑。什么感觉？就是人家英法联军把大炮亮出来之后，你僧格林沁赶紧去蒙古调节更多马匹来。

俺倒是好心建议这些人士，省点钱吧，将来J-20不缺乏靶子机，日本和韩国那里多的是呢！

不过人家美国人对这个消息倒不是太大反应。为啥？因为F-22其实已经飞了N多年了，也不是什么新技术了。

人家美国现在玩的新东东，叫做空天战机。

这个代号叫做X-37的空天战机，就是你用火箭发射上去，然后据说2小时之内，就可以从太空攻击中国的目标，然后在飞回来，准备下一次用。

说的是这个新大杀器一出来，就让你好看，和这个比起来，F-22就没有多大用处了，是不是？

其实，美国这个东东，和中国的弹道导弹打航母，是一条路子，就是 *俺是从太空上揍你* 。

不过大家恐怕不知道， *中国人的航天技术，其实比航空技术要高。就是说中国人造火箭的能力其实高于造飞机。*

就是说如果中国开展和美国的太空军备竞赛，其实要比中国和美国进行航空军备竞赛要强得多。

所以说J-20真的不是什么先进的东西，而且俺的估计，当J-20开始装备部队之后，也许就是落后的飞机了。当然人家日本、韩国、印度和台湾，也许连这样的落后飞机也没有呢。

如果俺说， *大家对J-20热炒，其实是中了调虎离山之计* 。你这么热衷于J-20的首飞（其实去年已经飞过了，大家不知道而已），难得不知道， *比J-20更牛，和美国最新最高科技的武器，可以比美的东东，已经飞行成功了？*

很早一阵子，俺就说过中国的军工界会出现一个大井喷，会有很多破纪录的东西出现。回头去看俺写的《新年展望》里面，曾经谈到了 *美国要是被中国拉进了军备竞赛，那就是非悲剧不可了* 。

看一看中国的 *反卫星导弹* 、 *反航母导弹* 、 *反中导系统* 、 *北斗系统* 、 *登月计划* 等等，你就知道将来的热闹可有一阵子。

反观美国，在国防预算上面，倒是要被人提议裁减一下了。

被出血的一个项目，就是减少过百架的F-35采购。在这样一个困境下，可不可以让F-22重新开始生产，都是一个疑问。

美国本来的信念是，在西太平洋上，美国的空中优势是不可挑战。

因为 *没有了空中优势，就没有海上的优势。没有空中的绝对垄断地位，那么航空母舰就是漂浮在海上的大棺材。而中国的新武器出笼，基本上就是为了冲破第二岛链。*

大家可能还不知道，东风21的C型（D型是航母杀手）外号就叫“ *关岛快车* ”，那么增加了J-20，美军在西太平洋的优势就不复存在，看来美军和共军以国际日期变更线划开太平洋而治的时代，还真是要快速到来了。

*所以不要恐惧人家大谈中国威胁论。等你真能威胁人家的时候，人家就会大谈中国好伙伴论了。*
