# -*- org -*-

# Time-stamp: <2011-08-25 11:08:24 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话55：中东局势和发展道路（二）

[2011-02-04 03:15:46]


*当然如果政府的腐败太过，而且你经济发展的扩张速度不足，或者说像中国那样，发展速度开始降低，那么社会不公平的结果，就会变成首要问题。*

看一下台湾人民，对蒋经国时期政府腐败的容忍，和对陈水扁时期政府腐败的憎恶，就可见端倪。

因此俺在2008年对中国政府的提议中，谈到了三点。 *削强藩* （弱藩不需要削），要解决的是，重新树立中央政府的权威和行政动员能力。 *均贫富* ，要解决的是，当经济发展速度开始放缓，人民对政府官员腐败和社会分配不公平的容忍度降低的问题。

而 *严吏治* ，要解决的是，在没有一个很好的制度可以彻底解决官员的贪腐问题，而且还需要挖掘官员的执政能力，因此官员考核的标准，还是要以能为先，以廉为辅。过一段时间，就打击一次贪腐官员，保证腐败的程度在一个可控制的范围。

但同时如果过于强调反贪腐，而造成清廉但是无能的官员充斥政府体系，那么这个国家出问题的机会要更大，时间要更快。

这虽然不是一个完美的法子，可是谁让俺们不是生活在 *天顶星* 那样的完美星球上，而是生活在地球这个人人私欲横行的世界呢。

东亚社会传统上是一个重视平等的社会，因此有“不患寡而患不均”的传统。而中国多年的社会主义教育，也是强调平等和公平，这个是文化传承的优点。

但是 *任何事情都要避免走极端* 。比如说网上看到说什么一个拥有一亩三分地的农民，要从唐朝开始工作，不吃不喝才可以在北京市中心买一个房子。心里想， *你吃饱饭撑得慌，要跑北京市中心买房子干嘛。*

比如说美国人的平均收入是3万多美元。那么你硅谷的一个高级软件工程师，每年赚10来万美元，比大家人均要高3倍多，日子还不错了吧。

可是你要去买比尔盖茨，或者是其他大富豪的豪宅，那些过亿美元的东东，也要不吃不喝干上1千年才行呢。这样的比较，有什么比头呢。

这个社会不可能出现大家梦想那样的平均社会。有人喜欢拿美国来说事情，可是美国的贫富差距之大，比中国有过之而无不足。

简单地以房子来说事情，中国大部分的房屋拥有人，是全额拥有，只有比较少的一部分，是靠银行贷款。而美国的大多数房屋拥有人，是欠银行贷款，一旦工作无着，马上就要被扫地出门。

也有人拿挪威的社会主义来说事，却没有看到挪威的人口，和挪威的石油资源相比，简直就是另一个科威特。

*中国的未来发展，如果可以做到象日本那样的贫富差距，就应该算是比较理想的了。*

东亚社会，除了文化传承上，给了一个相对能干的政府体系之外，另外一个文化传承，就是宗教势力，在社会结构中的弱化。

中国的宗教势力，主要是来源于印度的佛教，和在佛教盛行而刺激下产生的道教。这两个宗教的盛行，得益于东汉末年开始，在中国的政府能力下降的局面。宗教影响强大，导致政府权力旁落，政府信用降低。而政府能力衰落，人民生活不安定，那么宗教影响力又可以弥补这个空档。

*中国宗教势力的顶峰，在魏晋南北朝，伴随的同时是中国历史上最动荡的年代，就是政府行政能力最低的时候，不是没有内在联系的。*

中国政府行政地位的确立，和宗教的关系彻底定位，主要发生在唐武宗灭佛之后。但是一旦政府能力降低，宗教势力乘机而兴起，发生在元末的白莲教，清末的回乱，拜上帝会，等等，都为此做了备注。

中国在90年代中期，政府行政能力和信用的衰弱，也引发了大量的民间宗教的盛行。出现了以反政府为主要诉求的转转功，也是这样的背景之下出现。

当然客观地看待中国共产党的兴起，可以看出来这个运动背后的 *准宗教现象* 。不少研究中国历史的海外学者，都比较过共产党运动中的道德自律，和当年的太平天国，有不少类似之处。

其实今天看一下当年的共产党人，比如像夏明翰那样的砍头不要紧，只要主义真的献身精神，确实具有宗教里面的那些圣人的风采。而且那时候，一种非常普遍的行为，要是放在今天，是比较少见和不切实际的。

*但是中国的幸运之处，是准宗教力量的兴起，来改变社会混乱的局面，靠的是坚定的信念，可以用血肉之躯抵挡住人家的钢铁之师。*

而这种理想至上，不顾现实的行为，发展到了极端，比如说宁要社会主义的草，不要资本主义的苗的宗教行为，对社会和经济的发展也是损害颇大。 *中国的幸运，是最后终于实现了由理想到现实的转型。* 这种转型恢复了中国历史传承的政府行政能力，也让宗教极端势力缺乏萌生的土壤。

看一下伊朗的历史，就是效法西方的民主制度，受到了内部保守势力和外部帝国主义干涉的联手谋杀，然后必须靠着宗教势力来解决问题。而在新的政治体系建立之后，宗教势力又不能像世俗政治转化，从而无法完成政治的顺利转型。

*看埃及的局势，以及整个中东的局势，是要明白问题的关键，在于宗教势力在填补空白之后，是否可以顺利转型。而且在这个转型中间，是否可以建立起一套有效的政府行政结构。*

*至少从目前看，在中东的各种西方化努力，基本最后都是以独裁和军队专权为收场。而一个相对独立于宗教势力，又非西方支持的军队之外的世俗势力，还没有产生。*
