# -*- org -*-

# Time-stamp: <2011-08-25 09:19:50 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话39：吃水不完挖井人

[2011-01-01 02:50:06]



当然了，这些海外中国专家，对中国政府的建议，自然就是要是让美国和你中国，搞冷战，那就大事不妙了。搞军备竞赛，你肯定死定了。

*也不想一想，中国和美国，是哪个国家财政赤字更大，国防预算问题更多？*

如果你F22要花1亿美元一架，俺J20要花1亿人民币一架，那么是你的2.5%的经济增长压力大，还是俺9.5%经济增长压力大？

至于要求中国对朝鲜施加更大压力，要求中国避免因为钓鱼岛而引发日本的民族主义（ *是不是前原诚司们应该克制一点，避免引发中国的民族主义，更准确一点* ），要求中国在南海问题上采取多边会谈等等，都是一面倒地要求中国放软身段，来迎合这些国家的要求。

中国自然不希望将来的东亚变成中国和美国冷战的战场，不过你们这些国家，比如新加坡之流的国家，如此热衷于欢迎美国来冷战，那就冷战一下，看看你们有什么好处，不是挺合理？

*当然最要命的，就是这些海外中国华裔专家的卖拐，还真有人在中国政府里面大声迎合，这个才是造成中国外交政策摇摆不定，被美国看到有机可乘，总是想过来空手套白狼的主要原因。*

*打铁就是要靠自身硬。* 中国未来发展，一定不要忘记四个现代化的后两个，一个是科学技术。

在这方面，可以聪明地引进，然后消化，发展出自己的拳头技术，不是很容易。高速铁路，可以算是一个异类。而其他的方面，比如说，军用的各种技术，或者说民用的核电技术等等，都要靠自己大量资金的投入，才可以得到有效的产出。

而在军事现代化上面，那就是不管别人怎么吆喝，都要花大力气做的事情。要是有人威胁， *要搞军备竞赛的话，那就大大欢迎。谁不搞，谁是小狗。*

今天看到中国的军队，走上了真正的现代化道路，于是感叹于这个转变的来自不易。

再加上，前面提到的军队曾经经商的问题，发现有人对中国军队转变的整个过程，并不是太了解，并且把这些问题，怪罪于当时决策的邓小平。

所以除了俺觉得这些人的看法，对邓小平老爷子不够厚道和公允之外，也有必要把这个来龙去脉说清楚。

*中国军队转型，其主导者，其实是始于毛泽东主席。*

在 *1975年* ，毛主席提出了整顿军队的思想，然后亲自点将，由邓小平出任解放军总参谋长，开始对军队的减肥工作。当时的减肥工作，主要是降低军费在国家预算中的比重，降低军队总人数。这个工作，当时是由邓小平和叶剑英老帅一起主持的。

本来原订计划，是将军队裁减26.2%，结果是一年之后，裁掉了13.6%之后，因为反击右倾翻案风运动，邓小平又给下了台。

然后在1977年底，军队改革继续实行，完成1975年的计划。

第三次裁军，是 *1980年* ，大力精简机关，压缩的主要是非战斗部门。然后在1982年，炮兵、装甲兵和工程兵三兵种领导机关撤减，合并成总参业务部。铁道兵划归给铁道部，基建工程兵撤销。

这个时候，中国军队的总兵额从660多万降到了423万，差不多减了三分之一。国防费用占国家财政的比例，从1979年的17.37%减低到1984年的10.63%。

然后在1984年，就是前面提到的继续裁军100万，在3年之内，把国防预算减低到9.27%。 *这个大背景下，大量军队人员，需要转移出来，正是这个背景之下，才出现了军队经商问题。*

经商问题，其实在其他国家行业中同样出现。

比如说电力部门吧。你有电网要维修，以前是大而全，由电力部门里面的维修单位给解决了。现在是要精简机构了，于是隶属于电力部门的单位，自己成了一个独立核算的公司，然后就把自己的活儿给自己包了。这个过程，最后就变成这些公司慢慢就独立出去了，不再隶属电力部门。可是由于历史渊源，其中的纠缠难以说清，最后就变成你给我活儿，俺给你回扣之类的了。

军队也是这样。刚开始时候，是由军队里面的后勤和支持单位成立公司，到社会上去捞活，同时也服务军队的需求。

这样从社会上捞来的钱，就养了这些未来会被精简出军队里面的人员。同时国家预算里面，就把这部分支出给去掉了。

这样慢慢下去之后，军队里面的冗员就逐渐脱了钩。然后就逐渐变成了市场化运作，就是军队不再向过去那样大而全，什么功能都有。 *很多支持的服务，就变成了军队出钱向社会购买。*

而可以为军队提供服务的，自然有以前军队分出去的，也有其他国企，甚至包括私人企业。

这个时候，出现的问题，就是 *掌握合同权力审批的后勤军队干部们，就有机会吃回扣了。*

*这个就是后来大家比较反感的军队腐败问题* ，让大家开始担忧军队战斗力了。

其实这样的问题在美国有同样出现。那就是当年美国国防部长拉姆斯菲尔德，在美军里面，进行了类似上面这个把大而全的军队功能，裁减了不少支持部门，然后就把这些活儿，给了Halibaturn这样的国防承包商。

其中的腐败有没有？和中国军队相比，那不是一个数量级的。

*美军的战斗力有没有降低？俺可以和你保证，美军的战斗力的变化，和后勤这么包出去，是没有太大关联的。因为战斗部队，和后勤的运作，并不是那样的影响。*

当然如果作战部队，也拿出来搞生产，确实会影响作战能力。谈南泥湾的359旅，大家也许应该看一看这只当年的红军劲旅，后来的战争历史。

总之，历史原因自然有历史的利弊，大家今天不需要厚古薄今，把军队经商中的问题，直接就上岗上线，要去清算改革开放去了。 *其实，不论是南泥湾，还是新疆建设兵团，还是80年代的军队经商，都是历史上的不正常状态。*

后来经历了江泽民和胡锦涛两任领导人的继续裁军和改革，中国军队的现代化终于在30年的过程中，渐显雏形。在1997年-2000年三年之间，江泽民主政，又裁减了50万人员，陆军精简18.6%，海军精简11.4%，空军精简12.6%，和二炮精简2.9%，全军控制在250万人以下，占国家财政减低到7.6%，是新中国历来最低。

从2003年-2005年，中国再次裁军20万，经过了艰难的6次大裁军，中国才进入今天的现代军队体制。 *而下一步的任务，就是继续加大军队反贪反腐的力度，以维持军队后勤机构和武器系统研发采购的效率。*
