# -*- org -*-

# Time-stamp: <2011-08-26 09:24:24 Friday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话89：美国战略转变（四）

[2011-05-10 14:57:18]


先补充一下，上文谈到的《外交》杂志，应该准确地说，是《外交政策》（Foreign Policy），免于和《外交事务》（Foreign Affair）搞混了。

那么《外交政策》刚刚出了一篇徼文，叫做 *《高盛如何创造了食物危机》（How Goldman Sachs Created Food Crisis）* 。这篇文章的作者，叫做Frederick Kaufman，是美国著名杂志《Harper》的编辑。因此他的这个观点，已经不是新闻，但是今天被《外交杂志》登出来，用意深远。

按照这篇文章的说法，美国芝加哥的粮食期货市场，本来是为了抹平农产品市场因为天灾影响到的价格波动。在这个市场里面，通常是进行非常专业的期货买卖交易，大部分是由和这个行业有关的农民们，或者是像麦当劳这样的大型餐饮集团来进行。而作为投机商的炒家，就为市场提供了流动性，本来的比例，大致是5比1，就是20%的参与者是炒家。

在1991年高盛率先推出了高盛大宗商品指数GSCI，把能源、原材料、粮食等等，就给搞了一个指数，让外行们也可以像投资股票指数，比如说标准普尔那样，来炒卖了。要命的是高盛指数，主要是为大家买涨而设计，并没有相应的卖空手段。

然后其他的各家，都跟进推出了自己的指数，比如说JP摩根、AIG、巴克莱、德银、熊士坦、雷曼兄弟等等。而高盛指数，在2007年就转给了标准普尔。这个指数的大头是能源，大概占了70%，农产品占了10%。而能源中原油是大头，占了总指数的55%多。

在这些指数准备到位之后，美国政府的监管单位，大宗商品期货交易委员会于是就在1999年放开管制，给大家捞钱机会， *于是世界性的粮食价格危机，就这样给搞出来了* 。

结果就是从2000年开始，投资在这些大宗商品基金里面的钱，翻了50倍。在2003年，市场资金是130亿美元，到了2008年就变成了3180亿美元了。小麦的单价，就从60磅在4-5美元的水平，一下子飙升到了25美元。

这样一来，整个市场的炒家，现在大概是4个对一个相关行业企业。而 *全世界的饥饿人口，就被推上了20亿人* 。于是大家就看到了2007-8年发生在一些国家的暴乱，今天就变成了诱发中东和北非大规模乱局的导火索。

*而且这个食物危机，还会继续向人口密集的南亚蔓延。*

当然这个情况，是符合美国联储局推动全球性通胀，为美国经济解套了既定方针。

但是对美国军方人士，甚至对国防外交和战略界的人士来说，这样有通胀和饥荒导致的乱局，就为扮演世界警察角色的美军带来的困扰。

因为一来是美国如果不能出手，或者无力出手平乱，就摧毁了美国全球霸权的合理性理由。既然你不能维护社会治安，你就没有资格当全球警察。你没有资格当全球警察，你就没有资格去收治安保护费。

第二是 *世界各国出现的乱局，必然有利于为应付物质贫困无法解决，而转向于心灵和精神诉求的宗教运动* 。而这种宗教运动，尤其是在北非、中东和南亚，这些最有可能遭到粮食危机打击，而又是伊斯兰教主导的地方，出现的结果，就是宗教保守主义的回潮。而这个又是美国担心的，会带来恐怖主义的进一步发展。

在Y先生提出的三个很模糊的对策之中，第一个比较清楚，就是美国必须重视教育，发展美国下一代的人力资源。虽然这个主张，和美国现在联邦政府和各级州县市政府，大力裁减教育经费，解雇教师的做法，南辕北辙，不过在道理上大家还是应该认同的。

第二个对策，就是靠美国自身来解决发展的可持续性问题。其实就是美国需要的各种资源，应该以美国本土作为解决的来源，而不是过度依赖于海外。

第三个对策，就是利用美国自身的资源，来解决世界性的问题。而世界的问题，其中一大面临的困境，是人口的快速增长，会在本世纪中叶达到90亿人口。

美国以其广袤的土地和农业科技，可以为世界大量人口提供粮食供应，从而依赖于掐住其他国家的脖子，通过对粮食的供应，来发挥自己的影响力。

*其实这套思路，和美国控制石油的思路如出一辙。* 唯一的区别是，石油是工业的食物，你要想发展工业化，就会被捏着脖子。可是对没有兴趣，或者没有能力发展工业化的国家，还是直接捏住你人的脖子比较好。

听我的话，就有粮食给你。不听的话，饿死你丫。其实这条路子，是俄罗斯关欧洲天然气龙头的不同翻版。

当然除了粮食之外，可饮用的淡水也是下一个争夺的目标。

那么从这个角度来看，如果美国战略家和军界的目标，是要靠粮食这个软实力，来作为影响世界各国的一个主要工具，代替必须依靠军力这个硬实力，来控制中东以及中亚，那么华尔街对农产品的搞法，显然是与这种设想，有根本的冲突。

因为你要是想用粮食援助来收买人心，这个高价也搞得你自己难以维持。而高价格的粮食，带来的必然是全世界的社会不稳定。

*任何国家的不稳定，必然会带来强势政府（如果不陷入索马里那种乱局的话）的兴起，这个自然又和美国抛售的普世价值大相径庭。*

所以对华尔街的不满，自然是符合逻辑的。
