# -*- org -*-

# Time-stamp: <2011-08-25 09:54:15 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话45：2011猜想


[2011-01-16 15:59:34]


因为J20的原因，没有机会回答读者的一些提问，这里就从军事领域跳出来，重新回到经济上，并对2011年的世界和中国经济发展，给出俺的猜想。

台湾来的网友aiguille，问了两个问题，一个是美国大印钞票，形成的恶性通货膨胀如何解决？第二个问题，就是中国如何解决资源问题？

在回答这两个问题的时候，先说一下背景资料。

*在苏联垮台之后，大家当时所接受的所谓共识，就是共产主义那套是不行了，国家主导经济发展行不通了。全世界都在搞市场导向的经济和政治改革，因此看来繁荣和发展，是主要靠私人企业和自由市场来决定，政府要靠边站了。*

这套理论，是很多人都信了，尤其是很多中国主流政经人物们信了。不然的话，你是难以接受中国国企在90年代被MBO杀戮的事情。

*但是这个理论，美国人是不信的。美国金融界里话事的人是不信的。美国金融界里话事的犹太人是不信的。*

美国人相信，在这个所谓的自由市场和私有企业之上，政府的控制作用依然重要。其实美国人信奉的和 *陈云* 老爷子的鸟笼经济，相差不远。原理是一样，只不过你的笼子要多大，笼子的材料，是钢丝的，还是竹子的，那就各有千秋了。

自从弗里德曼的货币经济学提出来之后，货币政策在经济调控中的作用，就被提高到了以前没有的地位。

其实从 *美国人的角度* 来看，比较简单。就是 *政府的作用，是替经济发展提供一个良好的软硬件基础。* 比如说，你搞高铁、高速公路、机场、港口和桥梁等等，是硬环境，你提供法律体系，搞环境保护、产业扶持、税收优惠、反垄断法等等，是软环境。

那么政府财政政策，在收入税收上调节，在行业倾斜上运作，在公共支出上增减，其实都是非常重要。

但是美国的情况是，财政政策权力分散，大家要搞民主，一大堆参议员和众议员，为各自的集团利益和地区利益而博弈，结果是导致财政政策比较难产，效率低下。而经过博弈之后的出台政策，并不一定符合原先制定政策的初衷，不一定对经济的发展具有正面的推动作用。

而货币政策，则是因为基本上依赖于美国联储局这个中央银行，和联储局下面的几个大商业银行和投资银行，因此具有权力集中，效率比较高的优势。

因此美国的经济决策人物，避难择易，是理所当然的事情。

在这样的一个现实选择之下，你再搞一帮御用经济学家，好好论证一下货币经济学的真谛（比如发几个经济学炸药奖状之类）和中央银行“独立”于政治权力之外的伟光正，那么事情不就成了？

于是你只要假定，低通货膨胀率对长期经济发展有益处，而中央银行的主要任务就是要看守通胀，那么货币政策就可以自圆其说了。

那么在格林斯潘的治理下，通货膨胀一直比较低。这个低通胀率，很大因素是因为制造工厂中国的出现，为世界经济体系多提供了几亿的廉价农民工，而导致物价指数偏低。

结果这个就变成了美联储货币政策的伟光正的丰功伟绩，于是乎格林斯潘拼命往全球经济系统里面注水，最终就导致了泡沫之后的信用崩溃。

本来你要货币政策起作用，你金融系统必须运行正常。 *好比说，你金融系统就是一个供水系统，美联储这个总供水源头，向系统注水，然后银行系统这些分流中心，就负责把这些水，送到家家户户的水龙头里面。*

然后终极用户，你消费者和实体企业，一开龙头，自来水就流出来了。

那么当你系统出现问题，自来水流不到终极用户那里，一方面就是你联储局不断加水，导致主管道洪流泛滥，满街都是水。另一方就是终端这里，没有水出来。

那么这些水跑到哪里去了？

当美联储搞QE2的时候，其操作程序是这样的。在美联储纽约分部专门有一个小组，负责向美国的19个大 *券商* ，比如说高盛和大摩等等买3-5年要到期的美国国债。

这些券商的作用，就是 *帮美国政府包销国债* 。因为如果你政府发行国债，结果大家不热心认购，导致国债拍卖流产，这个面子就丢大了。

国债拍卖流产，不关是丢脸，还可能造成金融恐慌，一下子就把整个美国经济体系给摧毁了。

所以这些包销的券商，其中一个任务，就是如果俺卖的国债没有人买，你就得自己吃下去。因此这些券商手上，还是有不少自己吃下去的国债，那么现在联储局，其实买的是这些券商的手上存货。

等联储局印的钱，去买这些券商的国债，其实就把印出来的钱转发给了这些券商。

本来美联储的原意，是你然后把这些钱，就贷款出去给企业和消费者，那么经济就活起来了，是不是?

可是人家这些金融机构，对你的想法，没有兴趣。人家自己拿到这些钱，就拿去干最来钱的东东去了。那就是拿去炒。

美国股市的上扬，其实能够容纳的资金量并不是太大。 *真正的大容量，其实是两个市场。一个是金融衍生品市场，尤其是大宗商品交易市场。*

大宗商品市场热炒的结果，大家都知道，就是 *原材料和农产品大幅涨价。农产品涨价的结果，就是社会动荡。*

现在第一个例子，就是突尼斯。而且 *很多农产品依赖于国际市场的国家，都会成为这个美联储QE2政策的牺牲品。*

比如说，墨西哥有一句民谚，没有玉米，就没有国家。而 *墨西哥的玉米已经彻底被美国控制，出现粮荒问题，那是迟早的事情。*
