# -*- org -*-

# Time-stamp: <2011-08-25 21:21:20 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话81：雾里看花和水中捞月


[2011-04-17 01:59:57]


几个热点继续跟踪一下。

首先是美国国内的两党在联邦财政预算的白热化。说来说去，就是 *谁来付账* 的问题。

从地方政府的层面上，就是砍教师，削减教育经费。然后美国刚刚完成的全国人口普查，显示了美国白人占总人口比例，下降到了64%。这10年来，总人口变化增长率很小。但是18岁以下的白人人口，下降了10%，占总18岁以下人口的54%。

而少数族裔人口大幅度增长，主要是西裔人口增加差不多43%，到了5千万。就是说美国人中六分之一。这个不包括非法移民人口，估计是大概1千万-2千万之间。

西裔的一大要命问题，就是中学缀学率高。大概接近一半的西裔中学生会缀学，比黑人还要高（44%）。当然白人的缀学率是22%，而亚裔大概可以忽略不计。

现在看美国的幼儿园新生入学情况，差不多10个娃娃中间，6个西裔，2个亚裔，一个白人，一个黑人。以上面谈到的18岁以下的变化率，那么每10年翻一番的话，那么20年-30年之内，西裔人口的比重，是很快会达到1亿到2亿之间，那么整个美国的人口构成，尤其是年轻劳动力人口构成，就大不一样。

然后加上中学的缀学率。加上美国整个社会在教育上面投资的减少。

美国联邦政府的财政预算之战，算是搞定了2010年的几个月，但是2011年的战斗又开始。其中可以预料的是，在国防预算、社会安全、联邦医疗保险三大块的斗争激烈之下，其他的支出，都会遭到毁灭性的打击。其中估计会包括高铁、电网改造、高速公路维护等等基建投入。

那么现在看20-30年后的美国，国际竞争力从何而来？

我曾经谈到过 *美国的阶级分化，会掺乎进种族和文化因素。* 就是说，美国的大概一千五百万左右人口的亚裔，和占美国总人口10%左右，就是三千万人口的白人富裕家庭，会出现某种合流趋势。

就是说这些亚裔人口，和白人家庭年收入超过20万美元的富裕家庭一样，会吃健康食品（有机啊等等），而不是垃圾食品（就是吃得出现痴肥症状，也影响智力发育那种）。会上私人学校保证质量的小学和中学，然后就是去哈佛和耶鲁等等常青藤大学。

我附近的一位北京来的老中，干了几年修车技工，后来自己开了家小修车铺面，然后儿子去了哈佛，就是这样的非常普通的例子。

这条路子出来的年轻人，那还是有竞争实力的。有趣的是，这个阶层的年轻人（不管是亚裔还是白人，还是混血）都是普通话的最勤奋的学生。

另一条路子，就是吃垃圾食品，然后去经费被砍了不少，教育没有质量的公立学校。当然也有能够最后凭自己刻苦勤奋上名校的，但是大多数就是好的上一般学校，差的就是中学缀学。

*前一个阶层，有钱有势。后一个阶层，有人有票。* 而大家斗争的焦点，就是前一个阶层，会大部分有自己的企业，或者公司高管。后一个阶层，就大概会向政府部分挤，靠政府吃饭。

你也许会说，那么不是很多低级的职位，比如说农场工人、建筑工人、餐馆帮工、清洁工人、还有家庭保姆，都有不少西裔的人口？是的，但是这些工作岗位，大部分都是没有身份的非法移民在干呢。合法的，才不会那么傻。人家要走捷径，通过选票改变社会分配原则。

当然第一阶层的人，肯定不会放弃政府高位的，因为那些是分赃的决定权。但是中下政府阶层的位置，估计大多数都会被第二阶层的人口占领，然后就来一个家庭顶替类似的东东，老子退休，儿子顶上，妈妈退休，女儿上位。

*所以将来美国的大政府和小政府的争论，要不要砍政府财政，砍多少，都会隐含着这个种族和文化背景。*

本来我还担忧，亚裔，尤其是中国人，会步犹太人的后尘。因为个人能力很突出，大家都是生意人、高技术专家、医生、律师等等，却没有了一个重要的东西，那就是枪杆子。

白人当然不同，军队和警察，还是以他们为主。你看一下白人警察，向老黑和老墨开枪的劲头，就知道人家不好惹。反观中国人，就简直成了穷人对富人泄愤的最好目标。

相对于白人中间的各种民兵组织，尤其是各类以联邦政府和军队作为假定目标，天天演习准备打仗的这些组织（本来我写美国黄巾军，就是指这些人，但是后来没有完稿），和黑人和西裔中间开始坐大的各类武装黑帮组织（比如说墨西哥的毒贩武装的美国分支）等等，亚裔是要差太多。

在美国南部，比如说德州和亚利桑那州，有些白人武装，已经可以公开抗税，而联邦政府无奈，采取忽略的态度。

不过最近看到了一条新闻，说 *在南加州，有一帮华人组织了一个伪美军预备役军队* ，领头人开始被联邦调查局起诉的事情。仔细查了一下，原来这样的组织，还不止一个。据说这些组织，有不少是美军退役的华裔军人，搞的东东，叫做“ *美军志愿后备队* ”，其实就是相当于那些白人民兵的组织。

*这个是一种好事，因为出现乱世，最起码你有自己的杀人机器。* 在加州和德州美国两个最大的州，白人都变成了少数族裔，那么你自己有军队，攻击别人略显不足，用于自保还是绰绰有余了。这样的民兵，不在乎多，有问题的时候，可以拉出来10万人，就够用了。
