# -*- org -*-

# Time-stamp: <2011-08-25 11:00:03 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话54：中东局势和发展道路（一）

[2011-02-01 05:04:32]


先给各位读者拜年，祝大家在新年到来之后，事事如意，阖家幸福。

下面这个系列，有点犹豫，因为谈到的话题，可以放在这个闲聊系列，也可以放在关于政治改革的系列，还可以放到《说文论文》系列。不过，先把它写出来，至于将来放到哪里，就以后在考虑吧。

前面谈到埃及人看待土耳其模式的时候，俺专门用了一个非常特定的限制词“ *阿拉伯大城市的居民们* ”。

为啥这么用呢？因为埃及，和中国以及世界上的大部分发展中国家一样，有一个社会问题，那就是 *城乡差距* 。

就是说大城市里面的居民，和中小城市以及边远乡村的居民，大家的生活水平不一样，生存状态不一样，因此造成的思想意识的不一样。

相比于大城市，比如说开罗这样的地方，很多城市居民教育水平比较高，现代化意识相对浓厚，世俗意识比较浓，那么想土耳其这样的发展模式，得到的接受程度比较高。

可是出了开罗，到了下面的中心城市或者乡村，那就是完全不一样。

那就是宗教意识比较强，传统思维比较深厚，和教育水平不高。

*因此在这样的土壤下出现的政治形态，你要是运气好的话，那就是伊朗那样的。你要是运气差的话，那就是阿富汗塔利班政府那样的。*

在这样的环境下，你要搞西方的普选民主，那么真是要自求多福了。

为啥呢？很简单，大城市里面的居民，影响力强但是人口少，城市外面的居民，影响力弱但是人口多。你要搞一人一票，结果就是具有差距的城乡两地人民，开始以人口和影响力来进行博弈，那么你这个社会，就开始出现大麻烦了。

在泰国，前面的这一帮子，俺们知道，叫做黄衫军。后面的那一帮子，叫做红杉军。

在伊朗，前面的这一帮子，俺们知道，叫做改革派或者反对派。后面的那一帮子，就是内贾德的支持力量。

而普选民主，在欧洲和北美这些相对发达的西方国家，之所以问题小一些，是因为本身其社会结构，完成了工业化和城市化的变革，人家的农业是现代农业，人口少。

因此没有发展中国家，这样的一个城乡结构冲突。

这里说到中国右派支持的普世民主，会在发展中国家带来冲突和混乱，中国左派们就开始笑哈哈了。

不要笑得太早，左派们主张的人民民主同样行不通。

因为问题的症结在于， *当你考虑到尊重人民，或者说大多数人民的意愿的话，你一个国家的有效资源，就必须向这些大多数人民倾斜。*

*对发达国家而言，这个大多数人民，是和国家的工业化和城市化形式高度一致的。可是对发展中国家而言，大部分是农业国家，你的资源倾斜，就去不了工业化和城市化，那么你就逃脱不了世界国家竞争中的落后的结局。*

*而落后，就意味着要挨打。*

*因为人家西方国家，不是菩萨再世，人家是打家劫舍的强盗。你要自卫，就必须工业化和城市化，不然结果就是一样，你啥政治形态，都改变不了这个局面。*

而且 *事实证明，只有工业化和城市化实现了，才出现真正意义上的农业现代化。* 因此从这个角度，去理解中国以前的工农业剪刀差，去理解英国出现的圈地运动，都必须在这样一个大的背景下考虑。

当然知道工农业剪刀差，知道你工业化和城市化的过程中，需要资源倾斜，靠了剥削农村来支持城市发展，但是你要是不能首先做到，将农民转换成城市居民，然后在工业化和城市化，开始出现规模，可以开始反哺农村，从而推动农村的农业现代化，那么你这个国家，也是搞不下去的。

而要完成这一样一个国家转变，你无论如何，都需要一个强有力的政府。不然的话，你一个权力分散，没有行政和组织能力的政府，不被人家发达国家继续拉大差距，都已经是万幸了，还想去赶超人家?

看了一下世界上的发展经验，比较成功的后发国家，主要的成功经验，基本上是在东亚。

而在东亚，基于几千年中国文化的传承，产生了一个有行政能力的政府体系，对社会的力量动员相对比较强。

但是 *这个体系过去的软肋* ，是在于文化传统中，对无为而治的追求，出现了政府力量，基本上只到了县一级。

整个社会运作，靠的是地方士绅的自主，而且整个政府体系，出现的是财政能力偏弱，动员能力不强。

因此在辛亥革命之后，政府体系的现代化改变，就大幅度进行。基本上可以说， *在1949年以前，国民党的主要贡献，在于建立起了大城市到中等城市的政府行政组织的现代化建设。*

*而1949年之后，共产党的主要贡献，在于把这种现代化政府组织形式，从大中城市，推广到了小城市和乡村。*

一个国家要现代化，没有这样的全民性的组织转变，那是根本不可能的。

*强大的政府，自然带来强大的动员和组织能力。但是权力的集中，而缺乏制衡，也会带来决策错误的灾难性后果。*

*而且缺乏制衡的权力，也会自然地带来政府的腐败。*

但是在现代化进程之中，尤其是早期阶段，因为经济规模的迅速扩张，和经济发展速度的突飞猛进，当大多数人民得到了发展的好处，那么政府的腐败程度，相对比较容易被人民忍耐。

这个时候政府的能力，就是说你是 *腐败而有能力* ，非常重要。最怕的是腐败而无能，比如现在埃及这样的，那才是要命的问题。
