# -*- org -*-

# Time-stamp: <2011-08-25 11:44:07 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话60：埃及革命的背后（一）

[2011-02-21 10:52:30]


美国的《外交杂志》周刊刚刚发表了内部人士罗森伯格的一篇文章，详细描述了埃及青年运动的幕后动作。

话题首先是要回到2008年。当时在埃及的一个城市马哈拉（El-Mahalla el-Kubra）发生了一件事情，就是埃及国有企业的纺织厂工人们，因为物价高涨和工资太低，准备在4月份的第一个星期天，出来罢工。

这件事情引起了一帮子在首都开罗，玩高科技的年轻人的注意。于是这群人在脸书上开了一个团体，准备在4月6号的时候，在整个埃及组织声援的抗议和罢工行动。

这个脸书团体，很快就有7万人加入响应。

但是在网上搞活动，和在街上搞活动，还不是一码子事。在马哈拉的工人罢工之中，警察占领了工厂，禁止了罢工。结果就是抗议变得很暴力，示威者们放火烧了不少建筑物，警察们开始开枪镇压，最后是两个人死于冲突。

而网上组织希望号召的全埃及的声援运动，却没有了踪影。这就显示出了现在所谓的社交网络新工具的软肋：你可以一下子搞出在网上搞出很多同伴，可是一离开网络，这些群体就散失得无踪无影。

要搞革命，你这些工具只可以通一下风，报一下信。根本成不了大事。所以大家决定要去革命圣地延安去取经，取颜色革命的真经。

而这个革命圣地，就是在塞尔维亚的贝尔格莱德。

于是埃及革命小子，一个20岁的博客阿德尔（Mohamed Adel），独自去西天取经。

在贝尔格莱德有一个组织，简称为CANVAS，全名叫做“ *应用非暴力行动和战略中心（Center for Applied NonViolent Action and Strategies）* ”。这个组织的形成，是因为在1990年代塞尔维亚的年轻学生们把米洛舍维奇给搞下来了。然后得意非凡的学生们决定，把他们的经验向全世界出口，从而开始训练超过50个国家的运动人士。受过这个组织训练的包括后来搞成了的格鲁吉亚、乌克兰、黎巴嫩、马尔代夫和现在的埃及。

那个这个组织教你些什么呢？不是在网上怎么用新媒体去组织人群，而是在街上怎么干。阿德尔在受训一个星期之后，带着学来的宝贵知识回国了。然后他开始训练其他年轻人，最后他的组织“四月六日青年运动”和另外一个组织Kefaya，就成了这一次埃及开罗革命的主要组织力量。

对最近埃及的革命带来整个中东和北非的动荡，人们的关注主要是在新媒体的运用，或者超级大国美国的支持态度如何等等。但是真正的原因，其实在于背后组织的能力：就是你有没有办法，把一盘散沙的不满者，变成街头不怕死的斗士。

这个要求的不是喊口号、发宣言、找外国记者们事先埋伏，或者接受外国媒体采访，诸如此类的表面功夫。而是要靠 *长期的组织建设、自我约束、团结一致、和长远规划* 。

一句话，就是你要把自己搞成一只军队那样，然后时刻准备着，静如处子。之后，就在一个火花产生的时候，要求你动如狡兔，发挥出组织力量，然后一击而中。

导致乱局的导火索其实很容易发现。比如说汽油涨价了，反对党有个领袖给人干掉了，自然灾害发生后政府反应速度太慢，或者说某个城市的警察和城管打死了一个小贩，等等。

这种事情发生，通常会引发大众的怒火。可是，光是怒火不够。因为大家有火了，政府应对得当，拖一下时间，或者是惩罚几个官员，大家的火就消掉了。

而要利用大家的火，把一个政府给咔嚓掉，需要一个准备非常充分的组织，抓住机会，赶紧 *煽风点火* ，把事态给搞得最大最好，让参与各方都无退路。

*因此所有的革命，你外行们看起来，似乎是一个偶发事情，是很即兴的事情。其实不然，事实是人家已经做了几年的准备。比如说，埃及这一次，最起码有组织的准备，就进行了3年。*

其实在这个塞尔维亚组织出现以前，美国政府和其盟国，已经花费了无数金钱和资源，在全世界搞推翻他国政府的颜色革命。

但是美国等国家的传统搞法，有些不同。美国的搞法，通常还是和比较有影响和地位的反对派组织联手。CANVAS的做法不同，他们专门找幼稚的年轻学生。

这么做的原因，俺的估计，是年轻学生比较容易糊弄。因为你已经有影响的反对派组织，无论如何和政府体系，有矛和盾的复杂依赖关系，因此利益所限，也不愿意彻底和政府决裂。

而通常学生们这样的外人，可以有理想主义色彩，想事情比较简单和天真，因此比较容易接受过极(激)的运动目标，不会轻易和政府妥协，一定要以要么你政府死，要么我学生死的方法，玩一铺大赌局。

CANVAS的起家，是在1998年十月的一次聚会。这些学生们当时为了反对米洛舍维奇，已经连续游行了100天，但是一点效果都没有。

大家讨论了革命的困难之后，发现最大的一个问题，是塞尔维亚人民不相信可以推翻米洛舍维奇，或者不敢这么干。而反对党组织，则更多地作为反对派领导人自己捞取政治权力的工具。

所以大家觉得革命的事情，只能让年轻人们来干了。而关键的重点，是如何把年轻人，给忽悠起来卖命。你不能纠缠于具体的事务中间去，比如说菜这么贵啊，工作机会少啊，诸如此类。

因为政府总是可以作出一些让步，然后大家目标达到，就回去该干啥就干啥了。你革命目标就达不到了。

*因此革命的目标，不是这些具体的生活问题。而是关于俺们年轻人的自我身份认定。* 就是说俺们要让年轻人们接受，革命是一件很爽、很酷的事情。要让大家相信，俺们推动的是一种生活方式，让政治搞得成为一件很性感的事情。
