# -*- org -*-

# Time-stamp: <2011-08-26 11:07:16 Friday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话97：好铁要打钉，好男要从军

[2011-06-05 15:09:06]


*中国在南海维护国家主权和经济权益，需要靠的是两方面的力量。*

+ 第一个，就是对这个海域的安全保护，可以进行有效执法。

目前中国在南海的领海保护任务，主要是国务院下属的国家海洋局的海监总队。在2010年，威武的海上城管们，出勤了188次，再加上海上城管的空中支队，也出勤了523次。大概这些出勤，驱赶了违规操作的闲杂人等，船只是1306艘，飞机是214架，还有43艘不便说明的目标（估计美军的间谍船等等）。

当然这些出勤，也包括黄海和东海，但是大家估计都知道南海，是重中之重。

最近发生的中国海上城管，依法执法处理越南犯法的石油勘探船，不足为奇。而且将来这样的情况越来越多。

因为以前海管们，钱少、船小、人员和装备都不够，所以抓小偷的次数，和抓住的小偷人数也不多。以前是大概几个月，你的船才巡逻一次，现在大概是几个星期。等到新的海监船大规模投放，就可以增加到几日巡逻一次，甚至可以每天巡逻的地步。这个时候，小偷的日子就没有那么爽了。

要想增加中国海洋权益的保护，加大海监自然是一个不可避免的法子。在这上面，中国可以学习海洋大国美国和日本。大家都知道，日本在钓鱼岛附近的海监是做得比较严密，这个在技术上是值得中国学习。

但是在制度上，日本海监隶属于国土安全部，导致了海上争执这样的外交和国防大事件，由比较份量不重的政府部门处置，是不明智的。

美国的海上城管，就是有海岸巡防队负责。而海岸巡防队，是属于美国海军的后备役部队。就是说海上城管，平时是抓抓偷渡、贩毒等等，但是一到战争期间，可以马上作为海军使用。而这个要求，就导致了城管们的船只是按照军舰的规格、城管们的训练是按照军人的要求来做。

*因此中国的海监总队，其实应该归属于国防部，作为海军的后备役部队。而国务院的海洋管理局，则可以着重在海洋研究、海洋气候和环境监测、海洋资源的开采和保护上面。*

+ 除了海监之外，第二个重要的因素，就是深海能源的勘探和开采能力。

大家知道，深海开采风险还是颇大的。像BP在墨西哥湾搞出的大污染，就是不重视安全的结果。

中国在深海石油技术上还是一个初学者，现在中海油的深海平台981刚刚在上海完工，大概可以在几个月内出现在南海某个地方。另外铺设深海石油管道的201也近期完工，可以开发南海这个被称为第二个波斯湾的能源处女地。

至于南海到底有多少石油，估计现在大家只是估计而已。不过这个估计，就认为南海的石油，基本上和沙特阿拉伯的总储量是差不了太多。也就是如果中国可以把自己坚持的主权领海给拿下了，那么就成为排名沙特阿拉伯之后的第二大石油国（第三是伊拉克，第四是伊朗）。

当然这样的估计，不能完全当真，毕竟人家沙特阿拉伯的石油，开采成本是非常低，不可能和你深海石油相比。不过，如果中国可以早点动手，抢占先机，那么就算是将来一对一和其他小国进行谈判，那么先手占的便宜大，就算是将来需要共同开发，让一小块给人家，也可以吃大头。

*对美国来说，如果你需要中国的合作，来稳定中东，那么你就得考虑中国的能源需要。* 如果中国的能源大部分依赖于中东，或者更准确地说，依赖于伊朗，那么你就别想着中国会在伊朗对你美国有“建设性”的作用。

要支持中国的能源需求，就必须对中国在自己的主权领海—南海拿石油，保持缄默。当然，鉴于你埃克森和雪佛龙技术上领先，现在赶紧和中国合作，还是有一点好处分。不然的话，过几年中国的深海开采技术赶上来之后，你想来凑份子，俺还不睬你呢。

中国的能源来源保障了，倒不排除可以做个和事佬，在伊朗和美国之间斡旋一下，看一看大家各自的要求，可不可让一让步。本来，伊朗问题，就是中国、俄罗斯、欧盟和美国四方在调停嘛。

*考虑到能源需求上，用煤炭，已经天怨人怒了。不用说环境污染，就是因为抢煤抢得吃相难看，各种大大小小的煤老板，层出不穷的矿难，在河南、山西、内蒙搞出来那么多的不和谐事件，都和这个煤炭大有关联。*

核电的话，在日本自宫之后，大家对核电的信心大幅降低，不足为奇。原因很简单，核电站大部分时间都是安全的，但就是百万分之一，是不安全的。而这个百万分之一的不安全，导致的灾难，却是毁灭性的。而日本福岛的福娃（辐娃更确切）暴动，只是长篇连续剧刚开了个头。

估计大家能够希望的，就是2020年之后，看MSR这样的新技术是不是可以成熟。而在这之前，本来中国比较亲眯的水电，也在国内受到不同势力群体的攻击，估计在大规模开发，机会不大。

这个时候，也许一个无奈的选择，就是靠在南海里面拱猪，拱它十年到2020年，希望新能源技术可以有重大突破。

而在这个关键时期，拿下南海，颇类似于当年美国拿下加勒比海。

*当年美国的国际局势，于中国今天颇为相似。那就是经历了血腥和无耻的自由资本的30年突飞猛进（从美国南北战争内战结束的1860年代，到美国走向帝国扩张的1890年代），国内因为分配极度不平均导致了社会不稳现象。而当年和流氓资本大亨勾结的民选官员，不论是联邦政府，还是地方政府，都是极度腐败。*

比如说纽约州的议会就通过了一个法律，说是如果你受贿的是现金，或者没有具体的受贿理由，那么你受贿就是合法。诸如此类的东东，比起今天的中国，是过之而无不及。 *这个时候，美国的解困之路，一个就是国内社会改良，一个就是海外帝国扩张，来保持把馅饼做大，然后在继续让流氓大亨多分的前提下，也提高屁民的分配水平* 。

这个时候，横空出世的老罗斯福和马汉，奠定了美国海军，迅速上升为世界第二的过程。

*而当时世界超级海洋霸权的英国，开始忙于应付普鲁士崛起的挑战，而无力应对美国的崛起。地区性的霸权力量，西班牙则经历实力衰弱，法国则在拿破仑时代，已经退出了美洲大陆。这个时候，美国就是靠战争打败的西班牙，占据了西班牙的主要路冲古巴，导演了巴拿马省从哥伦比亚的独立，和开通了巴拿马运河。*

今天中国面临的局势，比当年美国还要看好。因为美国对加勒比海无法有主权要求，而中国对南海的主权要求，具有国际法的认可和历史的传承。

当年的世界第一强权英国，面临德国的挑战，无力兼顾美洲。而今天的美国，在中东、北非和南亚的位置，也是捉襟见肘。虽然美国在东北亚，还保持了一定的实力，可是在东南亚确实是比较薄弱。最要命的是，因为美国一方面是能源依赖中东太大（虽然也试图从非洲替代），而且又背了犹太人这个包裹，可以想象的是，美国在中东的维持，会越加艰难。

其实当年西班牙在美洲的地位，勉强可以用日本在东南亚的地位替代，不过日本这个地位，已经在日本自己的经济危机和东南亚金融危机的双重打击下，早已破灭。现在处于核扩散打击之下的日本，基本上在东南亚是歇菜了。

*所以中国的出路，在于加速发展海军成为世界第二（尤其是产生一大批具有硕士和博士水平的舰长），争取在2020年的时候，慢慢将控制力扩展到整个南海。如果那个时候，新能源技术突破了，那么当然谢天谢地。如果还得靠旧能源的话，那么就守住南海，看着中东一片战火，也不用担忧了。*
