# -*- org -*-

# Time-stamp: <2011-08-25 11:15:36 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话56：中东局势和发展道路（三）

[2011-02-06 06:13:53]


最近看了一些网友的反馈，以及一些论坛上的文章，发觉有不少人在争论帝国和祖国的问题。

首先谈一下对帝国的看法。这个要相比较于历史上的两个阶段。

一个阶段，就是美国在1860年代美国内战之后，北方主导的大资本实力，在南方横扫了奴隶制农庄经济，在西方摧毁了印第安人部落经济，从而将美国带入了资本寡头垄断的帝国主义扩张阶段。

这个时候的美国，是资本强盗大亨盛行的年代，产生了洛克菲勒、摩根、凡德伯、卡耐基等等，吃了你连骨头都不吐的大鳄。

这种资本的大规模积累，当时面临着两个挑战。一方面要面对的是国内受剥削的工人（当时是依赖于美国人口的快速增长造成的劳工供应充足）开始的劳工运动，另一方面要应对的是对海外原材料和市场的争夺。

在这种形式下，美帝国主义登上了历史舞台，靠着理论家马汉、政治家老罗斯福，带动了美国转型，从美国共和国，而演化为美国帝国。

美帝国的对外战争和掠夺，主要是集中在加勒比海地区，当然也包括东亚和太平洋区域的菲律宾、关岛和夏威夷。因此其主要抢夺的对象，是针对衰落的西班牙帝国的旧地盘，而没有敢于挑战英帝国和法帝国的势力范围。

另一个历史阶段，就是德意志统一之后，发生的德皇威廉二世和铁血丞相俾斯麦的意见冲突。

当时德国在快速工业化之后，面临的同样是海外掠夺资源和市场的问题。但是德国的生存环境要比美国差太多，面临的是被法帝国和俄罗斯帝国的联手遏制，而限制德国人的生存空间的问题。

因此当时德国的国家安全目标，就是第一要防止法国和俄国的结盟，第二要保证英国和俄国的世界范围的大国游戏不能停止，第三要建立长期的德国和英国的同盟。

但是在保守和稳重的俾斯麦出局之后，德国的这些战略目标没有一个实现。

因为为了保证德国的海外殖民地利益，德国开始大力发展海军，希望靠修建德国柏林到奥斯曼帝国的城市巴格达的铁路，从而获得伊拉克石油，并利用巴士拉港口，进入波斯湾，然后靠这里出发，绕过英国人控制的埃及苏伊士运河，更好地连接自己在非洲和亚洲的殖民地。

而德国的这些举动，自然就危害了控制伊朗南部和北非的英国的利益。而且和奥斯曼帝国的联手，也遏制了英国在中东的扩张。当然强大的德国陆军，一旦像当年普法战争那样，打垮法国，控制法国的西北部，那么就控制了英吉利海峡，从而严重威胁到了英国人的生存。

结果就是在这种扩张政策的影响下，英国和法国结盟，并和俄国划分了全球争霸协议，从而停息了英俄之间的大国游戏。而且英国将德国看着了主要的竞争对手，拒绝和德国签订同盟协定，尽管威廉二世和英国皇室的亲戚关系，都没有改变这个局面。

而反观中国目前所处的国际环境，大概最困难的局面是在2008年，处在欧美的携手围堵之下。

但是随着美国和欧洲经济陷入困境，这种对中国的围堵，最起码在欧洲已经烟消云散，只能靠炸药奖之类的东东恶心一下了。

而美国对中国的围堵，在东北亚算是有些做实，在东南亚还处于胶着状态，但是在西南亚和西北亚，美国的军事行动，都没有多大的作为。

而且以埃及乱局到导致的波及效应，会影响到美国在约旦和也门的布局，导致一个北非、中东、西亚，美国全线溃败的局面。

而这种溃败，引发的也是美国和伊斯兰势力的对决。美国为了守住中东，会不会直接用兵而激发这种冲突，都会造成美国在中国的西部，没有办法合围的局面。

因此中国今天的局面，相比于没有美国当年的局面那么好，也没有德国的局面那么差。

而中国在巴基斯坦的铁路建设，可以类似于德国的巴格达铁路，以通往波斯湾和印度洋作为主要诉求。

但是和德国不同的是，中国固然面临马六甲海峡那样，类似于德国苏伊士运河的掐脖子困境，但是中国还有缅甸通道，还有老挝-泰国高铁通道，可以经营。

而中国和巴基斯坦的关系，相比于当年德国和奥斯曼帝国的合作有所不同。当年的奥斯曼帝国为了保住中东，不得不面临和英国的争端。

巴基斯坦和印度的冲突，基本上可以限制在克什米尔地区，而且印度虽然得到了美国的支持，但是印度国力比较弱，还是没有能力对中国的战略利益导致太大的威胁。

因此中国在目前的局势之下，是否有必要走帝国主义扩张道路，是值得怀疑的。

因为中国现在没有迫切的需要，也没有足够的实力，可以把美国从亚太地区赶出去。而中美刚刚达成的协议，是承认美国在亚太地区有其战略和经济利益。而 *中国军力的大幅度增长，与其如说是威胁到美国，不如说是减低了美国对中国的予取予求的威胁能力。*

而 *中国和欧洲在经济上的合作大于对立* ，在非洲和法国达成利益妥协之后，中国可以靠和西班牙与葡萄牙的合作，开发南美洲和非洲。可以和英国、法国和德国合作，搞一个中欧联合舰队，保证苏伊士到马六甲的航路安全，还可以和俄罗斯合作，搞一个北冰洋航线，以及这两天同埃及局势紧张相映成趣的 *重庆到德国铁路开通* 。

*所以中国的海外战略，还是要实行王道，反对霸道，既要缓称王，又要不称霸。*
