# -*- org -*-

# Time-stamp: <2011-08-25 21:34:07 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话85：美国黄巾军（2）

[2011-04-24 03:18:41]

接着谈美国黄巾军问题。不过先谈一下美国现在的高油价问题。朋友小本（本嘉明）和人辩论，认为油价会近期探底，结果他预测的时间段，油价不光没有探底，还反复了一下，冲了上去。

但俺认为本兄弟的看法基本面上没有问题，只不过对投机市场经验不足。正如俺很早前就说过，玩炒油价的大户，是高盛、大小摩这些美国政府的真正后台老板。但是人家开始埋伏的时候，大概是2009年的夏天和秋天，当时的内部报告，俺也看到了，就是2011年的目标价，是105美元（德州轻油）。

当这个目标达到之后，你要考虑的就是 *如何脱手* 的问题。因为美国是一个车背上的国家，油价的飙升，就是GDP的下降，就是失业率的提高。所以油价到了一定程度，是会激起民怨的。

这个时候，肯定会有金融专家出来，和大家说，中东来乱局啊，原油上200美元都不是问题啊！你等着看6美金的汽油价啊！

什么意图呢？就是油价现在还是太便宜了，大家抢购期货合同，要尽快啊。因为你这些小户和散户，就是说不像人家高盛和大小摩，是美国政治局常委那一级别的，你不努力认购，人家手上的花儿没有办法传到你这里。

所以鼓点是要击下去的，石油价格在105-115之间要徘徊、起伏、辗转反侧，每次一掉下来（为啥？是因为人家老大们出货出得猛），非政治局常委们就一拥而上，抄底去了。

*折腾这么几轮，大佬们出得差不多了，那就是要美国政府的高官们出来为民请命的时候了。*

于是奥巴马说，司法部你要管一管油价炒卖问题了。这个也是为了让油价辗转反侧用的。然后大佬们因为“害怕”了，出货了，但是小佬们还不怕死，抢到了便宜货，油价转到左边身，睡了一阵子，又转回右边去了。

于是奥巴马又说，司法部要成立专职工作组，去抓几个毛贼给全国人民看看。在下一步，就该司法部专职小组成立，然后就是专职小组，准备起诉某某基金，因为明明人家高盛和大小摩，已经考虑到国家利益，采取了“配合”政府的行动，主动放弃了高利（雷锋啊！），把油价成功地从115降低了105，你这个混球又给买上去了，是可忍，孰不可忍！抓你呢！

明白这个，就知道，油价大概还会摆动一阵子，应该在进入夏天的时候，大概到5月底和6月中的时候，就会出现下跌了。美国老百姓还没有搜刮够呢，你4月15号之后，拿回来的退税，还没有被再收一次呢！

现在炒得厉害的美国预算，看来对联邦医疗和社会安全福利要动刀子难度不小。美国的普通民众，甚至包括共和党，以及茶叶党，大概有70-80%都大部分反对动刀子砍中层人家。毕竟人家几十年按时候交了钱，到人家开始享用劳动成果了，你说给你一刀，那也说不过去。

但是同时，赞成动刀子杀富的，却不少。刚刚出炉的华盛顿邮报和ABC的联合民意调查，发现72%支持对有钱人（年收入25万美元以上）加税，其中54%强烈支持。

在这个背景下的美国政府预算之争，以及5月底美国政府国债信用卡刷爆顶，都会带来美国政治的进一步分化和党争激烈。

在这个情形下，看美国的黄巾军，可以说是遭遇了一场 *完美风暴（Perfect Storm）* 。

在这个风暴的中心，是美国的经济困难，造成的民生困境。不管是两年前的民主党左翼横扫美国国会，还是去年的共和党右翼卷土重来，花生屯和花儿街（华盛顿和华尔街）这两个花花之地，都是换汤不换药，城头大王旗是变了，可是其他的实质东东，却没有丝毫改变。

这会导致依赖于选票作为工具，相信民主选举制度可以改变的不是边缘人士，开始考虑到要换一种法子。而这种法子，表现在个人的层面上，就是亚利桑那州的国会议员，被人枪击事件。

另外一个原因，就是奥巴马的上台。在美国黄巾军的极端部分，其实是不少白人至上的种族主义者。看到黑人出头，尤其是那种白人女人被黑人男人搞出来的孩子出头，是非常之愤怒的。

这个导致奥巴马在没有正式成为美国总统之前， *在6月和12月之间，就遭遇了4次企图暗杀事件* 。

*想对奥巴马动刀子的，是宾夕法尼亚州的民兵，是丹佛市的白人种族主义者，是田纳西州的光头党，而最可怕的一次，是北卡罗纳州的美军军营里，一位现役的海军陆战队员想干掉奥巴马。*

不过最耸人听闻的一次，是在缅因州的一个白人新纳粹党人James Cummings准备自己制造一个核子脏弹，在奥巴马宣誓就职的那天，在华盛顿引爆，对美国首都进行核袭击。






