# -*- org -*-

# Time-stamp: <2011-08-25 10:46:39 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话52：埃及、中东和北非（上）


[2011-01-27 05:25:30]


前面说的埃及会是一个关键的麻烦点，果然埃及现在开始乱了。

俺把突尼斯革命成为“饥饿革命”，是因为这个地方的乱局，会影响到整个北非和中东。

受到影响的大国，有不少。包括美国、欧盟和中国，都会受到波及。

简单地把这个地方发生的问题，归结于政治制度，或者有的人认为是美国黑手，都是很幼稚的想法。

*发生在这些国家的乱局，结构性原因，有政府贪污腐化，有人口增长过快导致就业机会不足，有年轻人口，就是20岁以下的男性在人口比例中过大，社会不稳定。当然导火索，就是食物价格，这个主要就要归功于美联储的QE2了。*

看突尼斯变局的后继发展，主要是看引发的多米诺效应。看这个多米诺会不会，把阿尔及利亚、利比亚和埃及给推到。

对中国而言，这个效应，会不会影响苏丹的稳定，从而引发北苏丹和南苏丹的战火重燃，都会中国利益有深刻影响。

而对欧盟来说，这个地带，是欧盟的地中海计划的主要领土，要是这些地方的独裁、亲西方、主张世俗生活的政府统统垮台，而由沙特瓦哈比教派深刻影响的穆斯林极端势力上台，那就是一个大噩梦。

因此从某种意义上来讲，这次发生在突尼斯的革命，颇为类似于1979年的伊朗革命。伊朗革命，是穆斯林世界对西方的反抗的里程碑事件，但是主要还是穆斯林少数派什叶派的宗教势力上台。

而如果埃及不保，穆斯林兄弟会在埃及掌权，那么就会导致穆斯林多数派的逊尼派中的极端宗教势力上台。

而这个局面出现，对美国的大中东计划，是一个沉重的打击，会直接改变自从 *戴维营和谈* 之后，出现的埃及和以色列合作的基础。那么中东离开大乱的局面，就难以避免了。

从以色列的角度来讲，1979年伊朗革命，使得以色列损失了一个盟友。虽然伊拉克算是以色列的敌人，但是伊拉克战争之后，伊朗升级成为第一号敌人之后，伊拉克似乎成了伊朗的延伸。

在伊拉克最有影响力的政治人物沙德尔刚刚从伊朗回到了伊拉克，大概在等着美国撤军之后，才开始发力。

而受伊朗影响的黎巴嫩真主党开始操控大局，现在再来一个埃及变天，然后看一下以色列和土耳其关系，已经形同水火，可以看到情势的艰难。

而且一旦以色列人觉得自己的背已经贴到了墙上，已经无路可走，就通常会狗急跳墙。

而如果穆斯林兄弟会的势力上台，那么改变他们和加沙地带的哥儿们哈马斯的关系，立刻就可能开放埃及边界，从而导致哈马斯实力大增。

这个还没有考虑，是否穆斯林兄弟会的势力，会不会在沙特和约旦等国家蔓延。

一旦这些国家出现穆斯林宗教势力政权，大概会类似于伊朗那样，基本是反西方的取态。但是因为人家是打着西方的民主自由招牌，西方的军事干预，估计缺乏道德旗号。

也许对西方最理想的结局，就是出现土耳其那样的，虽然独立于西方之外，但是对西方并非深恶痛绝的政府。
