# -*- org -*-

# Time-stamp: <2011-08-25 13:01:50 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话67 ：自带干粮的五毛

[2011-03-02 05:20:19]


看历史，是要看大势。

这种大势，是可以奠定几十年局面的。

读者会问，那么怎么不能奠定几千年局面呢？

要奠定几千年局面，是非常难的事情。在中国这样几千年历史的国家，也没有出现几件。

俺搬开指头数了一下，其中第一件，应该是起源于周朝的民族，以文化而非血缘而定。这个观念，引申下去，就成了 *华夷之辩，教化而定* 。

因此早先的各族，还要拐弯抹角地扯到炎黄的血缘，后来就彻底以文化而定了。

第二件，当然就是秦始皇统一中国后的 *书同文（但不同音），车同轨等专业化标准* 。然后在这个标准下的中央集权的郡县制。

当然彻底实现了这套制度，是要到汉朝。这个时候，天下的概念，才真正变成了现实。

第三件，就是隋唐开始的 *科举制度* ，奠定了中国社会人才竞争，而防止了阶层固化的问题。

第四件，就是 *推翻帝制* ，确立了现代国家的概念和制度，从而奠定了中国今天这样的一个多民族和多元文化的情况。

那么影响几十年局面的事情，就可以谈很多了。这两天，看了《五星红旗迎风飘扬》中间的一段，就是在中苏关系极度恶化的时候，硕果仅存的几个老元帅碰头讨论国际大势，得出的结论，是 *中苏矛盾，大于中美矛盾，美苏矛盾，大于中美矛盾，因此中国的战略转变，应该是联美抗苏* 。

这个转变，是一个战略大转向。从《中苏和平友好协定》成型的1950年代，中国当时最大的威胁，是美国。因此联苏抗美，在朝鲜顶住了美国的军事北侵，保住了东北之后，就可以把苏联势力，从东北赶走。

而在东边，是对沿海岛屿的一系列清除，最后是炮打金门，稳住了局势。

在南边，是把美国遏制在了17度线以下，在西边，是稳住了西藏，教训了印度。

但是当中苏在珍宝岛冲突的时候，主要的威胁是来源于北方。这个时候，毛泽东读了明史，看了朱升给朱元璋的九字真经，于是提出了 *深挖洞、广积粮、不称霸* 的口号。

这个口号，就是今天非常出名的外交政策，叫做“人畜无害小白兔”。

毛泽东对美国记者雪老哥（Snow）说，苏联你怕啥子嘛？俺中国人全挖了防空洞在地下呢，怎么可能威胁你老大哥呢！

而对美国，就是俺都不称霸，老老实实在第三世界呆着呢。承认你当之无愧的老大地位。不过你要俺承认你是老大，你就干老大的活儿，也要管一管北极熊吧！

广积粮，后来换了一个叫法，叫做以经济建设为中心。

这个战略转变，一直延续到了2008年。

这两天，俺也学习毛主席，开始读一些历史。不过俺看的不是明史，而是清史。

看的是洪秀全的太平军造反这一段。

这段历史，有一个很有意思的现象，那就是官军都是饭桶。要么是吃里扒外，要么是尸位素餐。

本来调去应付广西情况的林则徐，病逝于路中，结果继任者都是肉食者鄙。

因为肉食者鄙， *曹刿* 就只好自己出来打仗了。

曹刿这样的人，是不拿国家俸禄的。按今天的话说，就是不是 *官方的五毛* 。

但曹刿这样的人，又是现存制度的维护者，因为他自身的利益，和现存制度有关。

所以曹刿，应该叫做 *自带干粮的五毛* 。

千万不要小看了自带干粮的五毛。在太平军起事之前，官兵在鸦片战争中的表现令人为耻辱，导致当时招聘的地方民兵，都看官军不起。比如在广东的抗英战争中，人家三元里的民兵，也要强于人数最多的官兵。

这种情况，在之前的历史，比如说金兵南下入江南，南宋官军望风披靡，还是浙江一带的山民，对金兵杀伤力颇大。

在后来，当日本皇军，从广西入侵贵州，国民党大军也是跑得比兔子还快，倒是贵州少数民族的山寨军，打得小鬼子求生不得。

在太平军起事之后，邻近的湖南，也出了一些自带干粮的五毛党。

其中一个最著名的文人，叫做江忠源。因为对官兵的鄙视，他带着自己筹集的五毛军楚勇，在湖南全州城外的蓑衣渡，伏击了太平军，几乎将太平军搞得全军覆没。

如果不是其他官兵的配合不力，太平天国估计这里就报销了。但是这一仗，太平军最重要的组织者冯云山战死，为未来太平天国的失败奠定了基础。

冯云山这么说呢，可以说，他就是太平天国的周恩来。

除了江忠源，当然还有当时在贵州做知府的另一个湖南人胡林翼。虽然是朝廷命官，但是他的钱粮和兵马，都是属于自带性质。这之后的湖南的曾国藩、左宗棠，和安徽的李鸿章，大家都走了大致相同的路子。

不过这个情况，就是靠人家自带干粮的五毛来稳定社会次序，而你官方的五毛们只顾大吃大喝，不体悯恤， *前方吃紧，后方紧吃* ，也导致了中央集权和政府信用的日渐破产，导致后来当自带干粮的五毛党，就是袁世凯领衔的北洋军，不合作了，那么你就被几个反贼在武昌给咔嚓了。

自带干粮的五毛党江忠源，写了一首诗，抒发了对造反民众的同情：

哀此贫氓力耕种，年丰仅足偿什一。

今年不复望有年，坐令沟壑填白骨。

但见富人百无忧，谁怜贫者为饥出？

贫人一旦为饥驱，富人岂得安其室？
