# -*- org -*-

# Time-stamp: <2011-08-26 11:17:18 Friday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话98：南海攻略（上）

+ (上)

[2011-06-09 15:55:44]


看到一些读者的评论，颇有不少义愤填膺，说的是啥人家越南30%的GDP都是南海的石油开采出来的。听起来好像说是越南偷了中国多少多少石油，于是一片中国政府无能，要好好教训越南的喊打喊杀之声遍起了。

*其实看一下一个新加坡出的地图（不能保证完全正确），可以看一下，大部分的石油开采的油井都是在中国领海的九段线之外。当然也不排除，在马来西亚那边，因为九段线划得比较霸道，快划到人家岸上去了，所以可能人家近海油井可能会踩线。*

从这个图（新浪贴不上来），可以看出来，大部分石油开采，都是在这些国家的近海。这个非常好理解，因为近海开采石油，一个是技术要求没有深海那么高。而开采深海石油的技术，大概就是美国、英国、挪威等少数西方国家具备。如果他们要来参与，必然会考虑到各国的领土争端问题，没有自己国家政府的强力支持，估计是会比较犹豫的。

越南的石油开采，主要是在胡志明市外海的Cuu Long海域（图上靠近岸边的那两口井）和Nam Con Son盆地（靠近南沙群岛西部地的那几口井）。如果有往九段线里面拱的，大概就是被越南拿来打擦边球的万安滩附近。这次被剪了电缆的越南勘探船，应该就是在这里吃了瘪。

当然这个海域还进行了多次的越南渔船闯关被驱赶到事件，应该是中越争端的主要地区。

 

当然中国和越南谈判中，不是没有妥协的部分。比如说，极小部分的海域，确实有从越南的大陆架自然延伸在200米等深线以内，是可以做出让步。

那么中国在这个领域，采取的是一种首(守)势，目的是制止越南的石油勘探慢慢就从近海，一口一口偷吃进了九段线。而在另一个区域，就是采取攻势，必须加快自己的深海石油勘探和开采工作。

所以现在菲律宾政府强烈要求知道，中海油的981会去哪。而有一种估计，是因为在南海的北部海域，中国的勘探工作做得比较到位，因此开采会从北部开始。而这个北部，非常有可能就是在南沙群岛的东北点。

如果想了解我对南海争端的看法，可以回去看《新年展望》的第二篇。这里只是说明， *中国在南沙群岛的政策基调，应该是与相关国家一对一地协商不同的立场，反对非相关的第三方国家进来吓掺乎。*

*如果有人来掺乎，那么自然就没得谈。那么在这种情况下，应该避免海上的军事冲突，就是说不应该动用中国的海军来和人家对抗。但就必须依据中国管理的海域，执行中国的法律，以海监这个工具，依法办事。不是说，法律至上嘛。*

其实除了增强海上执法力量，加速自己的深海能源开发之外，我曾经提到过的第三个方法，就是应该 *放开南海开发给民间资本* 。

比如说，在一些条件好一点的岛屿上，开发个 *海上游乐场* 之内(类)的。在一些岛屿附近，搞一些像永暑礁那样规模的，可以有 *海上旅馆* ，然后旁边有水上游乐项目，可以停游艇和水上飞机的地方，再开发 *无土蔬菜培植* ， *海水淡化设备* 等等，开发成主要旅游度假地方，那么人气慢慢就会旺盛起来。

我曾经介绍过美国考虑建立一种海上漂浮的军事基地，正式名称是VLFS（Very Large Floating Structure）。可以用来解决在海外建立不依赖于人家国家的军事存在。

当然如果中国自己可以开发这种技术，那么在世界主要航道的区域，就是处于南沙群岛的永暑礁，和西沙群岛的永兴岛中间，来那么两三个。这样的人工漂浮岛，可以军用，也可以民用，搞好了，就真的可以搞出南沙市、西沙市和中沙市了。

如果这样的东东可以搞得成，那么建立势力坐大了，在斯里兰卡的外海的印度洋上，也来那么几个。这样的话，中国自己的海上生命线，才可以得到维护。

+ (下)

[2011-06-12 02:22:29]


最近发生的中越海上纠纷，第一次应该是万安滩的北部，而第二次应该是万安滩的南部。因为万安滩大致就是在东经110度，和北纬7度左右，因此如何你看到任何新闻说，是在110度的东边，那么肯定就是在九段线之内了。

*之所以最近这样的事情多起来，是因为中国的深海开采技术，要开始出来小试牛刀一把了。*

其实在南海能源开采上，本来就是近海易，深海难。因为这个原因，很多周边国家，都是在近海开采，然后逐渐往深海里拱。正如越南在万安盆地的开采，也是主要是靠近自己海岸的浅海海域。要想拱进来，资金是一个问题，技术更是一个问题。

所以这次和中国渔船发生纠葛的越南勘探船，其实还是一艘法国船，租来干活的。 *而中国的一直对策，就是在自己没有技术开采的时候，是也骚扰为主。*

骚扰的结果，就是搞得希望来合作的西方主要石油公司，得不偿失，没有进行正常的勘探工作。

但毕竟这些地方离人家国家近，离中国远。所以人家可以和你打运动战和游击战。你海上城管要是几个月来一趟，那么我还是有不少时间可以干活，是不是？一旦海上城管天天来，日日晃，那就比较麻烦。

这时候是看你的城管手上的家伙比较扎眼，还是俺非法小贩的家伙比较顺手。这个就是所谓海上的船只对峙。

当然这个时候，海上城管可能就要换大船了，和小船撞起来，也比较划算。

然后船用完了，就该飞机出场了。人家机场也比你近，于是就会来几架的飞机，在你头顶上玩几下花花。这个城管们是只好干瞪眼了。

于是有消息说，在今天的6月底的时候，据说海上城管们会放水一个可以停飞机的海上平台。那么这样的话，就可以把这个平台开到离开永兴岛和永暑礁中间位置，靠近110东经线的海域，这样的话，城管们的飞机，也可以拿出来在人家的头顶上，飙来飙去了。

看越南国内群情激愤，可以理解。毕竟CPI已经飙到快20%了，是属于靠近社会动荡的边缘。这个时候，炒作一下外国威胁，给大家找一个泄愤的去处，也是一个维稳的好法子。

但是也正因为这样，正如俺以前说过， *越南经济已经风雨飘摇，不排除就是在今明两年内有一次比较大的震荡。这个时候，需要的是两个东西。*

一个就是外来的“不附带条件”的救援资金。另一个是外面的给你喘口气的产品市场，可以帮助你度一下难关。

而这个时候，就是解决南海和越南争端的最佳时机。毕竟越南人民，是俺们中国人民的小老弟，几千年的亲情了。想想当年被美国人炸得死去活来，也是靠了中国才把美国人打跑了。

所以大家和为贵，反战反战。好好坐下来，谈一谈，共同开发，俺是大股东，你是小股东。俺是大份子，你是小份子。开出来的东东，俺分多一点，你分少一点。

然后这套原则，用于和其他的有争议的国家，俺们自己关起门来和谐和谐，就解决了。

不然的话，光靠大嘴仗，你也是一点油都开不到。要是海上城管的飞机平台和石油平台，一起在自己的领海干活，你还真敢往那里扔炮仗？

*所以南海的和平前景是很明朗的，不要心急，悠着点。*
