# -*- org -*-

# Time-stamp: <2011-08-25 21:40:25 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话85：美国黄巾军（3）

[2011-04-30 15:18:43]


回头来谈美国的黄巾军。

首先是读者对我认为美国这次是在利比亚犯傻，表示异议。而且认为欧美合流，而不是分歧，是干涉利比亚的最主要因素。

其实美国学界对奥巴马批评最厉害的一个观点，就是奥巴马的外交政策是盲拳，完全没有章法。虽然大家也批评小布什的外交政策，但人家好歹有一个章法。

而奥巴马却是乱拳。这一点，从美国在埃及的政策上，表现得最为明显。

当时是沙特老王爷强力劝阻，你不能抛弃穆巴拉克。因为毕竟人家为美国卖命了几十年，如果你这么容易就翻脸了，那么其他的美国盟友，会如何想？肯定是 *抢先在你出卖俺之前，先把你给卖掉* 。

本来奥巴马是想让穆巴拉克快速下台的。但是大家突然发现埃及原来还有一个宪法。平时是真的没人当这个宪法一回事，可是里面有一条，说如果埃及的总统挂了（比如萨达特那次）或者辞职了，那么人民议会的议长，就要接任总统，然后等到下一次选举结果。

可是当时做这个位置的老兄，怎么说呢，是一直公开主张用军队去横扫广场的。所以他在抗议者的眼里，是比穆巴拉克还要可恨。所以肯定是无法让人家咽下这口气的。

因此当时穆巴拉克的方案，是他虚位几个月，然后改掉这条发文，再下台。可是当奥巴马和穆巴拉克通了一天电话，无法确定穆巴拉克是不是缓兵之计。然后就在之后的记者招待会上，说出“要马上移交权力”的话。

这句话让埃及的小年轻们觉得奥巴马是在他们那一边。而希拉里，就被认为是站在穆巴拉克那一边。结果当希拉里访问埃及的时候，提出要和4个青年组织的领袖见面的时候，这些小年轻们一口拒绝。不过当美国记者问他们，如果要是奥巴马要见他们，见不见？他们一口说，当然见！

只要看一下奥巴马的名字： *巴拉克-胡赛因-奥巴马* ，就让俺们无限亲切啊！

而这个名字，就让美国的很多白人，非常不爽。无他，太他妈“老外”了。除了少数学者知道个中缘由，大部分美国人一听到胡赛因，就想起了伊拉克的 *萨达姆-胡赛因* 。而且还有电视台评论员，把 *奥巴马* 和 *奥萨马* （本拉登的名字）给读混了的。

所以黑人和“穆斯林”，这两大美国忌讳的事儿都碰一块了。在美国红脖子里面非常盛行的谣言，就是奥巴马用来做总统宣誓的那本圣经，其实只是外壳而已。里面其实藏着一本可兰经。

当时想在华盛顿特区爆一个核子脏弹的家伙，就是这样一个白人至上种族主义者。这老兄其实并不穷，家里给他留下了超过2百万美元的遗产，结果就被他拿来采购原材料，自己在家里开了个实验室，搞装配呢。他还有弄出来不少计划，比如如何利用自己的女儿被个小背包，里面装着炸弹等等。后来他这样搞下去，终于把老婆搞火了，一次吵架之后，老婆掏出枪来，就把他给轰了，这样来调查杀人案的警察，在发现了这个核子武器的组装厂。

但是大部分的民兵组织，还没有这么极端。更多的是吵吵嚷嚷，要奥巴马这个老外，快拿张出生证出来，证明你最起码不是出生在美国。

*这些黄巾军，现在干的事情，就是天天演练，进行和假象中的敌人对抗的军事演习。*

*那么他们假象中的敌人是谁？* 有几个。一个是伊斯兰教恐怖组织，一个是墨西哥毒贩武装，一个是私人军队，比如说黑水军，当时被政府雇用，维持风灾之后的新奥尔良市的社会治安。当然最明显的一个敌人，就是美国军队。

于是大家就问这么一个问题：要是联邦军队真的同你开打，你们行吗？虽然说，当年联邦政府对付了德州的瓦科组织，但人家报复炸了奥克拉荷马的联邦大楼，一命换一命，你搞死我百把人，俺也搞死你百把人。

黄巾军的理论家们，提出了两种战法。第一种，是你占领城市，俺占据乡村，来个城市游击战。这个是毛主席战法。第二种，是一次消灭一个敌人，集少成多，事就成了。

而 *这些美国黄巾军的主要骨干，基本上是美国小地方的警察和消防员。* 在一些美国人的眼中，只有小城镇里面的警察，才是真正的权力维护者。居然有不少人认为联邦政府为非法，如果联邦人员到了俺这旮瘩，就把他丫给抓起来。

对这些小地方，美国政府采取了息事宁人的态度，也懒得去惹他们。哪怕有些地方和组织，出现抗税现象，反正也不缺你那点钱，就当没有看见算了。

但是这种双方相安无事的局面，不知道可以维持多久。不少黄巾军忙着备战，不是主动出击，而是防止大事发生，比如说大规模的流行病（想刚开始炒作猪流感那样）、经济彻底崩溃、大城市饥民出现、生化或者核子恐怖袭击、太阳黑子变动导致地球灾难、墨西哥毒贩武装入侵、黄石公园火山大爆发摧毁美国粮仓等等，都可能导致美国政府宣布全国戒严，而这就是武装起义的信号。

在这些人看来，他们才是美国开国之父的真正传人，而现在的美国，倒是被老外们（比如说那个名字怪怪的，不是在美国出生的奥巴马）给占领了。看一看遍地的墨西哥非法移民吧。看一看到处的中国产品吧。看一看因为全球化（就是联合国接管美国）下美国的失业率吧。

所以他们觉得自己是在“敌后”作战呢。他们要捍卫自己心目中的美国，而且认为美国宪法最为基石的一条，就是修正案第二条：拥有枪支。
