# -*- org -*-

# Time-stamp: <2011-08-25 09:47:05 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话44：猛禽是这样给炼死的

[2011-01-14 06:11:38]


网上谈黑丝带的多了，有一种看法，就是把她和爱抚（F）娘娘（22）相比。

那么大家也许想了解一下，如此凶悍的孙二娘，为啥就被腰斩了呢？

在谈这个问题之前，想说一下 *中国国防战略的转变* 。

*中国的战略转变，就是从以前的被动的国土防空和近海防御，变成了现在的空天一体，从太空、高空、低空、海面和海底的整体国防体系。不再强调被动的防守，而是增加了攻防兼备的积极防御政策。*

那么从军队运行体系上来看，可以说从1980年代国防现代化谈的是机械化，尤其是陆军的机械化，到了今天的信息化，尤其是海空军，和战略导弹，一起形成的多兵种协同一体化的目标。

在1960年代的时候，当年完成的各种大三线，都是以中国的沿海地方，作为前沿阵地的。那么当中国的国防能力不断加强，以及中国大西部的开发，都会导致中国的国防线，必须大幅度地向外部延伸，从而达到拒敌于国门之外的目的。

从短期来讲，为和平统一台湾做准备的军事手段，要求的是中国必须有能力从台湾和菲律宾之间的巴士海峡，和琉球群岛各岛屿之间的几条水道，东出太平洋，把台湾岛控制在中国的军力优势之下。

而中期来讲，中国必须在东面，突破美国以关岛为中心建立的第二岛链，并同时开始解决南沙群岛的主权被侵犯问题，而掌握马六甲海峡、巴拉巴克海峡、和爪哇海的通航安全。

在远期来讲，中国需要和美国达成军力平衡，从而把中国的国防线，推进到东经180度的国际日期变更线。这里，美国的防守体系，就由阿留申群岛、中途岛、和夏威夷岛作为主体。

当然如果能在10年到15年之间，中国的实力可以达到东经150度线，那么把这个区域，作为大家的缓冲区，也未尝不可。

不过美国现在的战略，还是以维系第一岛链作为首选，其中以琉球的普天间基地为核心。因此琉球人民的态度如何，将会影响这个计划。

所以中国在钓鱼岛上面的动作，要考虑日本政府有可能利用把钓鱼岛交给琉球，来采取借力打力的手段。

美国的后备战略，自然是考虑到如果在第一岛链无法遏制中国，那么就只好退到第二岛链，以澳洲为主要依托，对中国采取离岸平衡战略。

而中国的应对，肯定是大规模投资印度尼西亚，从而在澳洲的西北建立根据地。然后通过到马来西亚吉隆坡的高铁，带动的投资，基本上可以抗衡这个战略。

在西部就相对容易，主要是保持巴基斯坦和伊朗这两个地区大国和盟友，不落人敌对势力之手，然后在军事上增加对印度的压力，那么可以保证西部的平安。

好了，回头来谈美国的孙二娘为啥给咔嚓掉，需要知道几个数据。

第一个，就是美国的F22是不是有美国空军吹嘘的那么好，从而让日本、韩国、台湾，以及中国的带路党们，激动得泪流满面，还是要打上几个问号。

美国空军对F22提出的22个关键技术要求，在2004年，只有2个达标，2006年5个，2008年7个。在2009年，F22就被开始推上了手术台，准备给砍了。

第二个，是这个飞机的隐身问题。孙二娘和很多美国的娘儿们一样，皮肤不好。现在是每在空中耍一个钟头，爽过了之后，落地要接受34个小时的按摩。而且一半以上的时间，是要解决皮肤问题。

因为涂料技术不过关，一个内部反出来的工程师，一直在控告马丁哥在隐身材料上作假和欺骗。而且还出现涂料脱落之后，被卷进发动机里面的恐怖事件。

所以孙二娘不是你啥时候约会，她都敢出门的。碰上个下雨天，被水一淋，涂脂抹粉的花容月貌马上就掉下来，那就不好玩了。

因此F22其实没有参加过任何实战，主要还是在没有敌人威胁的美国领空上保卫祖国。

第三个，就是维护费用昂贵。F22平均飞行1.7个钟头，就会出现重大安全隐患。每一个小时的飞行成本是44000美刀。

为啥维系这么贵？是因为这个计划，是当年美国空军的一个 *钓鱼工程* 。

钓鱼工程，就是先由空军订立一个计划，然后知道要花N千亿，就说只要花N十亿。于是成功立项之后，就请了分布在44个州的100个分包商来提供货源。

这种情况的好处，就是这个工程变成了“大到不能倒”的规模。以后追加投资的话，质量出问题的话，你都不能砍掉这个计划。

因为44个州后面，就站着88个参议员，在美国参议院的100个参议员表决中，你觉得胜算如何？

但是这样干的结果，就是质量控制有问题。结果许多运到总装配生产厂的零件，尺寸有问题，没办法磨合。

于是总装车间，在生产线旁边开了一条手工打磨线。不合规格的零件，就临时用手打磨，然后装上去。那么你以后维护，更换零件的时候，怎么办？

于是每架飞机的造价，就到了3亿5千万美元。

所以到了2009年，大家终于撑不住了，只好退出去腰斩。

这个过程，值得中国吸取教训，在J20生产过程中，不要好大喜功。
