# -*- org -*-

# Time-stamp: <2011-08-26 10:50:49 Friday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话95：三分天下谁主沉浮

[2011-05-29 08:41:23]


伊朗虽然是一个地区性大国，但是在波斯王朝覆灭，被阿拉伯人征服之后，运气就比较背。

当波斯萨珊王朝被阿拉伯人给打下来之后，其残余的王室力量，归顺了唐朝，成为了唐朝设立在伊朗高原的波斯都督府。可是当时的阿拉伯势力如日中天，不光是把唐朝的这个都督府给灭了，后来还把唐军从中亚赶回了北疆。

伊朗被伊斯兰化之后，又没有搭上主流派的大车，而成了伊斯兰少数派什叶派的大后方（人家大本营在伊拉克的纳杰夫）。这样就造成伊朗想成为一个地区性的大国，总是得面对大部分的“异教徒”，需要对这些“异教徒”施加足够的影响。

二次世界大战后的世界，要想说话有分量，你必须具有原子弹。所以 *伊朗的核计划，不是从伊斯兰共和国开始，而是从巴列维国王的伊朗王国，就开始了* 。

当时巴列维的想法，就是俺死死跟从最猛的超级大国美国（考虑到当时伊朗的北部，面对的是苏联的加盟共和国，也是古代波斯王朝的地盘，例如亚美尼亚、阿塞拜疆、土库曼等等），拿个鸡毛当令箭，又有种蘑菇的高科技，就可以在中东风光一时了。

虽然当时美国对自己的这个小兄弟，搞核武计划有保留，不过那时候人家伊朗和以色列的犹太人，可是哥俩关系不错。在中东石油危机对以色列禁运的时候，就是伊朗的油轮运油到红海，给以色列救命。

但是在1979年伊朗革命之后，尤其是美国支持的伊拉克在萨达姆的领军下，在后来干掉萨达姆，但是当时是作为萨达姆的美国主要联络人拉姆斯菲尔德的运作下，对伊朗发起了入侵战争。

伊拉克和伊朗的争端，除了萨达姆要压制占主要人口比例的伊拉克什叶派之外，一大原因就是伊拉克和伊朗的领土争端。

这个争端主要是关于巴士拉附近的两河三角洲的领土划分问题。因为英国人虎口拔牙，把伊拉克的科威特省给扒拉出去了，变成伊拉克基本上没有什么出海口，所以希望能够在伊朗那里求点海岸线回来。

结果伊朗的巴列维国王，以支持库德人造反作为筹码，搞得萨达姆手忙脚乱，结果在谈判中占尽劣势，最后为了换取伊朗不支持库德人，就在巴士拉海岸线上签订了吃亏的条约。

而一看伊朗搞革命，自己内部乱了，那萨达姆还不趁机翻盘？可是毕竟伊朗块头比较大，老萨在刚开始占了便宜之后，后来就被人家给翻了过来。然后N年之后，又想找科威特的晦气，想重新统一祖国，这下就真的被悲剧了。

有意思的是，成也萧何，败也萧何。萨达姆因为拉姆斯菲尔德的支持而雄起，又被拉姆斯菲尔德给灭了。之前一直要干掉本拉登的美国前国防部长盖茨，当年就是支持本拉登在阿富汗和苏联开打的中情局局长。

那么伊朗在两伊战争之后，缓过气来，面临的是巴列维国王同样的问题，就是如何影响“异教徒”逊尼派的人们。

对逊尼派国家的政府们，伊朗政府觉得没有戏。尤其是戴维营之后，逊尼派的政府们基本上除了卡扎菲，都是美国的看门狗。虽然伊朗人和本拉登不是战友，但是大家的认同点一致，那就是中东人民的压迫者，第一位就是各国的亲美独裁政权，第二位就是亲美的以色列。

*而伊朗人无法获得这些国家的政府统治者的认同，还可以赢得逊尼派的小老百姓的认同。要做到这一点，只要做一件事：那就是对以色列强硬。*

所以伊朗就出了一个内贾德，整天拿以色列和犹太人的兴奋点说事。一下子又否认纳粹屠杀过犹太人啊，一下子又要把以色列从地图上抹掉啊，再加上支持黎巴嫩真主党和以色列干了一架。

而当埃及的穆巴拉克配合以色列绞杀哈马斯的时候， *哈马斯的老爸，埃及穆斯林兄弟会* 无能为力，伊朗大施加援手，赢得了逊尼派的老百姓的拥护。

其实后来土耳其利用加沙的封锁，也来了同样一手，一下子就变成了中东阿拉伯老百姓心目中的英雄。

*美国伊拉克战争的最大赢家，大家都知道，是中东新月带动什叶派。* 伊朗自然也是主要得益者。在美军强力打击逊尼派势力的时候，什叶派的萨德尔也就是嘴上喊着反美，心里却是乐呵呵，等着美国佬和逊尼派民兵鬼打鬼。

在美国调整战略之后，中东的三角平衡，出现了伊朗实力开始做大。在这个背景之下，通过伊朗核问题的一系列操作，逊尼派的国家，比如沙特和其他海湾国家，老是催促美国和以色列，怎么还不动手？

对他们来讲，最好就是你把德黑兰给炸回旧石器时代，而同时伊朗也把以色列给炸回新石器时代，那俺们逊尼们睡觉都会笑醒的。

那么看现在这个局面， *阿拉伯民主之风狂吹，导致的结果，就是大部分亲美的逊尼派政府，都在风雨飘摇之中。*

*美国在中东的政治困境，主要就是因为美国对以色列的支持，导致中东阿拉伯国家的人民普遍反美。* 而一旦这些国家的民主进程越深入，那么民意对国家政治的影响越大。这样的话，这些国家的政策，就会越加反美。

那么在中东局势诡异异常的局面下，伊朗考虑到了逊尼派国家的亲美敌视伊朗的政府们纷纷下台的话，那么这些逐渐掌握政权的民众，或者没有掌握政权，但是影响力扩大到民众，必然导致这些国家和伊朗的矛盾减少，因为大家都是统一战线，反以色列嘛。

可是这之前的以色列和伊朗的矛盾同样变成的主导矛盾，也会让未来的冲突，可能会把伊朗作为中心目标。这个对伊朗自然不是很有利。

那么一个聪明的做法，是 *现在反正亲美政府们倒了，那么这些国家和以色列的矛盾就会上升，而变成中东地区的主要矛盾* 。比如现在哈马斯和法赫塔和解了，加沙的边境埃及也开放了。这个时候，就是要把以色列的巴勒斯坦矛盾激化，让这个矛盾成为中东的主要矛盾，成为让所有国家选边站的矛盾，就会降低伊朗被卷入未来冲突的机会。

*所以如果伊朗的精英们足够聪明的话，就是考虑让内贾德下台的时候了。* 这个时候弱化和以色列的矛盾，就会把伊朗摆到了坐山观虎斗的位置上。如果伊朗突然表现出要和平解决核问题的诚意，那就是一个信号了。
