# -*- org -*-

# Time-stamp: <2011-08-25 10:42:44 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话51：军备竞赛和和平崛起

[2011-01-28 01:33:53]

大家对J-20的横空出世而感到吃惊，是因为大家平时对新闻不够关注。

其实中国四代机的明确官方透露信息，是2009年11月8日，中国空军副司令员何为荣接受了中央电视台《面对面》访谈节目，谈到了中国四代机的试飞会马上进行。

而一直困扰中国航空的发动机研发，其实在2009年中的时候，似乎有了重大突破。

大家知道，中国在发动机上面卯足的目标，是美国的F119，也就是美国F-22用的发动机。而要达到这个水平，通常用的衡量参数是推重比，就是你发动机像个蚂蚁，可以举起比自己重多大的米粒。

F119的参数，是10，而美国今后研发的高推重比发动机，目标是15-20。

要提高这个参数，你主要的方向，一个是减轻发动机结构的重量，另一个就是提高发动机结构的合理性，让其燃气温度更高，效率更好。

主攻的方向，就是利用轻质高性能的材料，让这些材料具有轻盈、高强度和耐高温的特性。材料越耐高温，用于冷却材料的气体就越少，用于燃烧做功的气就越多，热效率就越高。而且，涡轮前温度就可以更高，效率也就更高。  

以F119作为例子，其三级叶片，采用宽弦叶片，是采用钛合金，需要用一个技术，叫做“整体钛合金铣削成型”（估计有人还记得在这个博客，读到过这个名词，呵呵）来做成两半叶片，然后经过4个（懒得在说这些专业名称了）后继工序，就完工了。在这方面，我们的差距不仅仅是一项工艺，由此连带的工作母机，材料，都有差距。

这个其实是美国在1991年推出F-22时候，就掌握的技术。可以说中国已经完全解决了。

那么美国下一代研发的高推比发动机，采取的材料上，已经不再用钛合金，而是用很多种不同的复合材料。比如说，用碳化硅纤维增强的钛合金基的材料。

当然不光是发动机的叶片，你的叶盘、叶环等等，其他的一系列部件，如果采取的是一次成型技术，比如说“粉末合金无余量精密铸造成型”（例如采取喷射技术等等），以及其他的各种复合材料的研发、制坯和整件成形等等，都有很多潜力可以发展。而且这些基础工艺的突破，会在其他领域“溢出”，导致其他领域的一些突破，星星之火，可以燎原。

读到这里，俺就不想在技术上扯下去了，总之如果你有这样的工艺和材料突破，肯定要干的就是两件事。一个就是拿新的技术，去改进已经成型的发动机，比如太行，搞个WS-10G之类的，用来对付着飞J-20。

然后希望能够好好的完善WS-15，作为将来J-20成军的选择。总之，今天你能看到的J-20，发动机是可以做到10-12，将来也许可以看到15。

但是最让人鼓舞的是，在2020年到来的时候，当美国的最新发动机出现的时候，中国的发动机已经和人家处在同级的水平。那个时候，中国世界先进技术大国的地位，才可以真正的确立。

从这个角度，再看中国的另一个杀手锏，就是号称航母杀手的东风21D型弹道飞弹，也可以说是初步战斗水平已经形成。

这个从美国海军的战略变化，从1990年代开始的近海浅海战略，恢复到2005年之后的深海远海战略，可以看到对这个武器，美国海军颇为忌惮。

其实了解这个东西的人，知道这种导弹的出现，起源于钱学森老爷子在40年代提出的“ *钱学森弹道* ”概念。这个概念说的是，可以集合弹道导弹和飞航导弹的优点，让导弹起飞到大气层的时候，采取的是助推的方式，但是当导弹重新返回大气层的时候，则是采取可灵活变向的滑翔方式。

当这个导弹在高空滑翔的时候，就可以采取自身的定位系统，最终到了航母的头上，然后以一个直线坠落的方式，攻击母舰。

对这种攻击方式，美国海军已经进行了防守研发，最后的结论是无解。

因为人家打下来的是一个点，你的反导导弹，要打中这个点，谈和何容易。

当然这个导弹要真的形成威胁，也要在于你的 *全球定位系统* ，比如北斗成型。北斗大概等到今年3月份发射之后，基本在亚太地区成型，然后在2012年底彻底覆盖亚太地区。

另外就是 *OTH雷达*，加上各种无人侦察机等一系列的侦查和定位系统，才可以完成这个战术体系。

当然也不应该低估美国军工的反应。就在去年底，大家炒J-20的时候，美国试验了电磁炮，这个月试验的某种反GPS武器，据说美国的超远程轰炸机也要出台。

因此在空天飞机、激光武器、无人飞机、电磁武器（包括未来航母电磁弹射器）等等新武器上面，还有一番龙争虎斗。

所以说当年的1929年大萧条，经历了三年的困境，在期中考试的时候，俺们看到了美国的罗斯福、英国的邱吉尔、德国的希特勒、意大利的墨索里尼等等，上台执政。

然后这些强人们，在经过了大致又三到四年的时候，期末考试来了，大家的成绩都不太合格，于是第二次世界大战爆发。

*阳关下没有新鲜事，中国的幸运在于政治制度的优势，导致了政治权力的连续性。*

相比于全世界大多数的国家，发生在中国期中考试的时候的权力交替，政策延续性会比较好，出现大政策转型，从而出妖蛾子的机会几乎没有。

而且中国还不存在2016年的期末考试权力交替问题。

但是世界其他的国家，就很难说。如果大家的成绩太差，2016年的时候，像美国这样的国家，民生仍旧艰难，老百姓失去的耐心，对“魏玛”政府深恶痛绝，然后外面某个地方，比如说中东，燃一颗火星子，那么就不排除有人狂扔大炮仗了。

*因此中国的军工在这5年的作为，可以决定中国的未来。*
