# -*- org -*-

# Time-stamp: <2011-08-26 10:42:44 Friday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话94：牵牛要牵牛鼻子

[2011-05-24 14:28:44]


本来应该写完闲话93的下，但是这里先发这个系列。

*读者问到奥巴马的新中东政策，要俺发表评论，一句话，逗你玩呢。*

中东的中心问题，是以色列和巴勒斯坦冲突。而要解决这个冲突，就是要考虑让巴勒斯坦自己建立自己的国家。

而这个目标，必须解决三个问题。

一个就是以色列和巴勒斯坦之间的划界问题，一个是当初被从联合国认定的以色列的领土上，被赶走的巴勒斯坦难民回归权利的问题，一个是耶路撒冷城市划界的问题。

按照联合国界定的难民身份，当年被赶走的巴勒斯坦人，经过在外面的几十年的游荡，是应该全家，更准确地说，全家族回到故土。可是如果这样一来，犹太人就会担心，自己将来是不是就变成了少数民族了，在自己的犹太国里面，也挡不住人家人口增长了。

本来这些主要是1948年战争，被赶走的巴勒斯坦人，在1950年的时候，总人数是71万。而在2010年，这些联合国认可的难民总人数，达到了470万。

那么现在以色列有多少人口呢？大概在2011年是775万。其中犹太人占了76%，就是589万。而阿拉伯人在2006年，就超过了20%，就是150万。其中大部分是穆斯林，也有9%是东正教或者天主教。

如果这些巴勒斯坦难民全部回来，那么以色列的主体民族就是他们了。

所以犹太人是死也不干的。他们坚持的底线，就是只有当时出生在以色列领土上的巴勒斯坦人才有资格回来。

不过长期来看，对犹太人还是不利。就是人家的法宝， *女人的肚皮，厉害无比* 。犹太人的生育率是1.7%，阿拉伯人的生育率是2.6%，增长最快的是阿拉伯人里面的穆斯林，是2.8%。

另一个耶路撒冷划界的问题，就是阿拉伯人认为东耶路撒冷是他们的，应该成为未来的巴勒斯坦国首都，而犹太人认为统一的耶路撒冷是其控制之下，没有商量的余地。

这个地方，是大概犹太人占60%，巴勒斯坦人40%。虽然犹太人不断的鲸吞蚕食，慢慢地一点一点啃巴勒斯坦人的地盘，但这十来年，顽强的巴勒斯坦人靠自己的高生育率，开始扭转了这个局面，是人口对比逐渐向有利方向变化。

而第三个问题，就是在划分边界上面，以色列当然是希望以今天的最大控制区划界，而沙特为首的阿拉伯联盟建议，以1967年边界划界，让以色列保持通过1948年战争赢得的大于当年1948年联合国划给以色列的土地。

现在奥巴马提出的，就是支持沙特的这个方案，但就想办法，让以色列现在非法开发的50百万人的安置区，可不可以用经济危机那种，好债券换银行烂债券的方法，让以色列用烂地换人家巴勒斯坦人的好地。

不过对这个意见，以色列目前的反应是坚决反对。反正谁也不知道，明年美国总统选举结果如何，你奥巴马反正也没有能力去强迫以色列遵守这个意见， *说到底，就是逗你中东的阿拉伯人玩呗* 。

最起码奥巴马这个举动，是向阿拉伯人示好，尤其是向前一阵因为穆巴拉克下台而导致关系恶化的沙特示好。

另一个很多人注意不到的就是美国的一个动作，以前的美国私人军队的老大王子（Prince）先生，最近被阿联酋花了几亿美金，请去为阿联酋王国建立一只完全有外国雇佣兵组成的军队，来控制海湾的局势。

因为很简单，中东和北非的乱局会持续，一旦出问题，美军如果在国际法和道义上，都不方便出手的话，尤其是其目的，不是要支持为民主自由而反对独裁起来造反的什叶派民众，而是要保卫海湾各个国家的独裁王室政权的话，出美军不方便，那么出私人公司的保安部队，就是几天前刚刚“脱掉”美军军服的特种部队战士，那么还是比较顺手，是不是？

看海湾国家，基本上就是和伊朗隔海相望，在波斯湾南岸，依偎在大块头沙特的身边，从北到南，由小到大，依次是巴林、卡塔尔和阿联酋。科威特，本来是伊拉克的一个省，被英国虎口拔牙，硬给独立出来，则是是在波斯湾的最顶端。

阿联酋的最北端，则是非常靠近伊朗的霍尔木兹海峡，这里与波斯湾分界，就是阿曼所在的阿曼湾。

那么可以考虑到就是美国的意图，是要以前美军特种部队的方式，加上外面找的一帮雇佣兵，比如说来自英国、加拿大等等，或者是南美洲和非洲等地招募的外籍兵团，就是要稳定住沙特一线。

而在最西面的埃及，奥巴马希望可以扔20亿美元的银弹，看一看可不可以收买新兴起的埃及新实力派人物，采取一个守势来护盘。

美国新中东政策的另一个意图，是希望至少装模作样地推动一下以巴和谈游戏，为现在逐渐升温的以巴冲突，适当降温。

*其实中东的主要冲突是三大块，一个是以色列和巴勒斯坦的冲突，一个是以色列和伊朗-叙利亚-黎巴嫩真主党的冲突，一个是沙特-伊拉克逊尼派和伊朗-伊拉克什叶派的冲突。*

从伊朗的角度来讲，因为美国在伊拉克战争的愚蠢行为，导致了 *什叶派弯月带* 的复兴。什叶派在伊拉克坐大，在黎巴嫩开始占据主要地位，都带来了和逊尼派冲突加深。

而其实伊朗这些波斯人和以色列的犹太人，并没有什么血仇。在巴列维国王时代，人家双方还是盟友呢，和伊拉克的萨达姆倒是真的深仇大恨，血债累累。

但是伊朗要在地区做一个地区大国，就必须提高在逊尼派阿拉伯国家里的影响力。那么最容易的办法，就是推出内贾德这样的猛人，出来拼命恶心以色列。
