# -*- org -*-

# Time-stamp: <2011-08-25 09:26:58 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话41：舆论战争和网络技术


+ (上)

[2011-01-03 10:50:30]


要是你没有看到闲话40，那非常抱歉了，只有在这里给你说一声新年愉快。

有不少读者因为看了一些网上的流言，问了一下中国的廉租房政策，不知道房租到底是在哪一个水平。

这里转一个2009年的旧闻，说的是广州有部分经济房和廉租房，其中有些人拿到手之后，就转手出租，按照低于市价的优惠价格，然后谋取利益。

那么这些广州的廉租房，是什么样的房租？就是每平方米一元，那么有些违法的人，就是用1100一个月租出去，吃中间的差价。

从这里可以看出，廉租房的政策确实是有的。当然政策的受惠面也是比较小，而且某些地方的监管不严，还有被人从中牟利的现象。

那么看到网上的留言，那简直就是低估大家的智商。其实想一想， *如果你是北京市委书记，你会怎么做？*

肯定俺就会配合中央的新政，把刚刚完工不久的第一批廉租房，赶紧安排一些贫困户住进去，然后陪着领导一起上电视，这才是做官之道，是不是？

想起了发生在2008年西藏拉萨事件之后的一些事情。先是在网络上出现了一张图和一个谣言，说是西藏事件，是武警装扮成喇嘛干的。这个图片出来之后，赖和尚，和他的西方一帮学者和政客们，立即上了欧美的新闻访谈节目，大谈这个所谓的阴谋。

然后有一个很支持赖和尚的美国人，开始有些疑惑，他说，中国要开奥运会了，从常理上来说，会为自己找这样的麻烦？

所以有人在考验网民的智商呢。反正任何中央出台的东西，都是有人要努力搅一下浑水，打击中央的政治信用。

+ (下)

[2011-01-07 05:53:13]



最近美国著名的《外交》杂志发表文章，对希拉里的网权大于主权攻势，进行了深刻反省。

总的看来，这篇文章认为，希拉里把事情搞砸了。怎么说呢？其实鬼子已经进了村，干得还挺不错。可是希拉里大声张扬，让敌人们（当然还有朋友们）全部提高到警惕。

偷偷的进村，打枪的不要。这是反思出来的结论。

该文章本来还提到了偷偷进村的成效，包括发生在伊朗的未遂的颜色革命，和发生在新疆七五的屠杀事件，新科技组织技术和方式，都起了关键作用。

但是当希拉里这个棒缒，希望联手美国硅谷，把高科技明确作为美国的国家武器之一（在美军、美元、粮食等之外），却希望其他国家，不会蓦然惊醒，发现原来国家的安全和主权已经受到威胁，那么就未免太小看人家的智商了。

俺曾经谈到过 *农业安全* 、 *能源安全* 和 *金融安全* ，现在看来还有增加一个，就是 *信息安全* 。

*所谓信息安全，就是你一个国家的信息架构，比如说通信系统和设备，信息储存和处理等等，都要掌握在自己手里。这一点，从来就是美国这样的国家信奉的基本理念。*

不信你看一看中国南方报系，算是比较亲近和认可美国价值和美国国家利益的企业，想要购买《新闻周刊》，人家美国是什么态度？

中国在这方面，吸取的教训，大概有好几个。

第一个就是西藏拉萨暴乱发生后，为了切断暴乱组织在印度的指挥通道，中国切断了西藏和印度的通讯联系。

但是印度相关部门，专门向中方通报，这个联系还存在，是通过香港的部分所谓“民主”人士们提供的中间转换系统。

第二个就是在新疆发生的屠杀事件，中国进行了彻底断网。

这之后，大家听到的估计不太多。俺这里就介绍两个。一个是在山西太原，有人通过新技术手段，发送短信造谣说要发生大地震，结果导致上百万居民惶恐走上了街上躲避。

另外一个就是某位反政府活跃分子，在钓鱼岛事件的高潮时期，通过微博煽动热血沸腾的年轻人，到上海世博去防火烧日本馆。

要防止这样的事情发生，或者说依赖法律去惩罚这些犯法者，就不能让这些信息流通渠道的经营权，让外国强权掌握。

美国这方面是如何做呢？很简单， *按照美国法律，所有的高科技设备，必须预留后门给美国政府。不然的话，你就不能在美国经营。*

好比说，如果你在某个通讯上用了加密措施，然后美国安全部门，用了很猛的大型计算机，花了几个星期，解了密，里面说，“傻B了吧？”，那么你没有犯法。

可是你要是有个东东，让人家解不了密，好了，你就会被判刑坐牢。

希拉里的这次动作，还是让某转圈子功组织发了一笔小财，因为美国国会拨款150万美元给他们去折腾中国。当然其实人家以为可以拿到400万，对没有太多余粮的地主颇为不满，但问题更严重的是，不光美国的“敌对”国家，比如说俄罗斯和中国等等，考虑发展自己的信息安全产业，而排斥希拉里的硅谷木马军团，现在连美国的盟国，比如说土耳其，都在考虑这个问题。

而欧盟在对谷歌的起诉，也是走的这个方向。就是要搞自己的谷姐，自己的面书等等。

*因此从克林顿到小布什的飞机大炮，到奥巴马和希拉里的短信微博，走的都是美国帝国的霸权术。不要以为你换了个马甲，一下子是民主人权，一下子是言论自由，一下子是公平贸易，俺们就不认得你了。*

在中国，大家也可以看一下所谓的有图有真相。

赖和尚散发的“武警扮喇嘛“（很多年前武警参与好莱坞拍片图），热老太散发的“警民对抗”（湖北石首的图），最近的两张图，一张是郭大妈环游世界，另一张是一位有名的普世派记者把湖南的非法集资案作为温州事件的图，有什么一致的地方？

还有就是有人把当年中国青年反日游行的图，给包装成湖北阿娇图，都是同一路子。

因为中国年轻人的强烈反弹，西方的媒体已经不敢在假照片上面乱来了，于是战场转移到了互联网上面。
