# -*- org -*-

# Time-stamp: <2011-08-25 21:01:48 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话78：天然气和绿色能源

[2011-04-07 09:40:08]


最近将以前写的《花开花落》重新修订了一下，看到里面我的一个能源建议，就是大力开发天然气。现在看来这个建议，确实是一个方向。

因为很简单， *煤炭已经被人判了死刑，缓期N年执行。*

而新能源中的水能，在三峡大坝上炒到今天还没有平息，而水库里面的移民问题，还有些屁股擦得不太干净。云南那边再搞水电，也是噪音颇大。

那么太阳能、风能、潮汐能等等能源技术，还在继续努力，要做到大规模取得现有的传统能源，仍然在短期内不太现实。

至于石油嘛，大家看到了中东和北非这个乱局，可不是一天两天可以搞定的。而且 *任何依赖外部能源，交通线安全是一个问题，国际市场价格受到美联储属下的基金冲击，成本又是一个问题。*

前一阵子当初热火一阵的核能，重新包装了一件绿色的外衣，本来想迎来生命的第二春的，这些被日本人胡来一次，福岛的辐娃们牵着手，高高兴兴出来逛街，就把大伙儿都心思又搞乱了。

虽然现在中国已经在建的核电厂会继续下去，但是新项目估计就要歇菜了。

核能的第一个，也是唯一一个春天，是从1973年开始。当时的情景，就是中东乱局导致了石油禁运。那个时候的石油飙升，迫使很多国家考虑替代方案。

当时的巴西军政府根据自己的客观条件，走上了乙醇燃料的道路，就是用巴西漫山遍野，又容易生，质量又非常好的甘蔗来提炼燃料，算是摆脱了对石油的依赖。

*美国现在搞的玉米乙醇燃料，是跟人家巴西的没得比。美国这玩意，就是骗国家补贴，经济成本上根本不划算。*

而其他的几个大国，比如说美国、法国和日本，走的道路，就是大规模上核电。当时美国核电上得非常快，就像中国的大跃进一样，呼啦呼啦地就把104个核电反应堆全给搞上去了。

但是美国这之后，出现的经济衰退，市场上根本容纳不了这么大的产能。尤其是1979年三里岛核电站，给大家小泄一下，引起了公众的恐慌，结果美国核电站的春天，就歇菜了。这之后，再没有新厂兴建，全是靠的老技术（和日本福岛一样，不少是通用电力GE的Mark 1 沸水堆，安全很糟糕的那种），已经过了设计期，现在靠延长寿命的法子，来继续贡献。

就像上一次的中东和北非乱局，造成全球能源政策的变化，而这一次估计也是同样，就是会造成现有的主要消费国家，开始思考不同的出路。

而这个出路，对中国和美国来讲，都是一样，就是我在《花开花落》写作的时候，就是2008年下半年提到的，走天然气道路。

天然气有几个优点，一个是中国和美国，都是天然气大国。这两个世界主要能源消费国家，同样都是煤炭大国。因此如果可以用天然气替代石油和煤炭，大家的碳排放目标，估计都可以达到了。

对中国而言，另一个好处，就是中国的天然气储量，在世界大概是排在3和4位，和伊朗的储存量差不多。而其他的领先者，是第一名土库曼和第二名俄罗斯。而俄罗斯的天然气，大部分是在西伯利亚和伏尔加地区，输送到中国新疆的距离，不是那么太远。而土库曼也是中国军力，尤其是陆军，很容易到达的地方。

如果哈萨克的高速铁路建成了，那么就更方便了。

至于在用途上面， *天然气产生的氨是化肥的主要原料。而且用天然气来发电，可以替代煤，天然气也可以替代石油作为交通燃料。*

现在大家炒得热火的，就是页岩气。

和通常的天然气不同，页岩气藏得比较深，而且页岩的透水性比较差，需要人工的方法，在页岩里面搞出些裂缝出来。

现在的做法，就是打井的时候，先是向下钻，钻进页岩层之后，然后横向打井，打它个3千米左右。接下来就是井的外面放一些炸药，就把页岩炸一大堆裂缝出来。

这之后，就向里面灌入混入沙和化学物的水，就把天然气给逼出来了。

在这一领域上，中国和美国有政府之间的合作，而且中国自己的国家页岩气研发中心，已经成立，就等着技术成熟，可以开始大干一场了。

中国的页岩气，可以说是到处都有。西北的塔里木盆地、吐鲁番盆地、准葛尔盆地、鄂尔多斯盆地、松辽盆地、渤海湾盆地等地，西南的四川盆地等，都有大量的储存。如果搞得好的话，大概中国一半以上的用气量，都可以靠页岩气来解决。

美国在这方面，是走得比较早，所以技术比较成熟。而中国和美国，以及欧洲的挪威等国家的合作，在这方面可以进行技术跟随，虽然要付人家一些钱，但可以少走不少弯路，来获得自己的能源安全，也是一个双赢的办法。

这样下来的话， *城市用天然气，农村用沼气，就是中国的一个发展方向。* 而且农村的电动自行车，将来发展的电动汽车（如果电池的持久性、车的速度，不需要那么牛叉的话），和城市的清洁天然气巴士，再加上用电的高速主干铁路、城际高铁、城市地铁，那么中国发展的最大瓶颈能源，就可以迎刃而解。

大家关注的是中国的高铁成网，但是不知道中国的 *天然气成网* ，也是一个更令人兴奋的话题。从中国内部来讲，几大气田，自然是从西向东，就是新疆-甘肃-陕西-山西-河北-北京-天津，和四川-湖北-安徽-江苏-上海，这样两条横主干道，然后就是从北到南，就是内蒙-宁夏-陕西-河南-湖北-湖南-广东这一条纵主干道。

然后就是中亚接上新疆，俄罗斯接上新疆、内蒙和东北，缅甸接上云南-贵州-四川等，再通过各种分道，那么整个中国的能源，就不成问题了。
