# -*- org -*-

# Time-stamp: <2011-08-25 20:31:36 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话73：中国核工业补充

[2011-03-17 01:48:42]



另外在谈到中国的核电站的时候，有些信息不准确，还有一些不完整，这里就更正和补充一下。

中国现在运行的核电站，应该是三处地方，而不是两处。

广东的大亚湾核电站和岭澳核电站，因为地理位置差不多，算是一处。这个地方，离主要大城市香港、广州和深圳太近。

大亚湾核电站用的是法国M310技术，应该是第二代核电技术。和日本不同的是，中国所有的核电站，都没有用安全性能差的沸水堆，而是用了相对安全的压力堆。这里是两个反应堆，是98.4万千瓦，在1994年并网发电。

岭澳有三期工程，第一期两台机组用的是中国自主研发的第二代CPR1000技术。这个技术，也是第二代，不过有时称为二代加，是晚期二代技术。装机容量是99万千瓦，在2004年上网发电。

现在在建估计近期要完工的二期，是用了CPR1000的改进型。装机容量是100万千瓦。第三期则差不多要开工，用的是和二期相同技术。

浙江海盐的秦山核电站，则是中国自主开发的第一个核电站。这个电站的问题，也是离大城市上海和杭州太近。

秦山也是三期工程，第一期用了是CNP300技术，1个30万千瓦的小反应堆，于1991年并网。因为是第一个核电站，到现在为止，已经大修过数次。

第二期工程，是两台改进后的CNP650技术，容量是65万千瓦，于1996和1997并网。算是中型了。然后扩建工程，就是增加两台，可能一台最近已经并网了，另一台大概今年就会上网。

从时间段分析，这两个型号，应该都是在早期第二代的技术上开发的。

秦山三期，则是引进了加拿大的CANDU 6重水堆技术，两台机组是720万千瓦，于2002和2003年并网。这个技术应该算是第二代的晚期和第二代早期的技术。

上次漏掉的，是在江苏连云港的田湾核电站。这个核电站的第一期和第二期工程，是用了俄罗斯的第二代技术AES-91。一期的两台机组，106万千瓦，于2007年并网。二期的两台仍然在建设之中。而第三期的两台，将转用中国自己的CPR1000。

其他在建的，首先是用了AP1000，也被称为三代加技术，在AP600基础上开发。是现在属于东芝，但仍在美国的西屋公司的技术。

这个模型，是在中国首次运用，因此引发了不少争论。现在在建的是浙江台州的三门电站（上篇错写成三水）的两台，和山东烟台的海阳电站的两台。这两个核电站比以前有所进步，就是离大城市要远一些了。最近的比较大的城市，是山东的青岛、烟台和浙江的宁波。

AP1000，相比于AP600，主要是减少了操作部件。比如说安全阀门，少了一半（就是说出问题机率下降了），水泵少了35%，安全有关的管道少了80%，控制线少了85%，建筑结构小了45%。

大家知道这次日本反应堆碰到的一大问题，就是冷却系统失灵。这个也是核电站必须考虑到最重要问题。

就是说在核反应堆关闭之后，你剩下的热量必须靠冷却系统给清理掉，不然的话，核原料在反应堆熔化，你就出大事故了。

AP1000用了一个技术，叫做被动冷却系统（Passive Core Cooling System）。这个冷却系统，用了少有30个阀门，在关闭反应堆之后的30分钟内运作。据说这些系统，其电力不依赖于外部电源或者柴油发动机，其阀门不依赖于液压或者气压空气系统。

如果一切按照西屋说的那样的话，这个被动冷却系统，可以保持72个钟头的降热功能。这之后，建筑顶上的一个大水箱，就可以继续依靠重力往安全壳里面浇水，保持降温。

但是有一个叫做Arnold Gundersen的工程师出来挑刺，说AP1000的安全壳，有问题。他认为这种安全壳设计，中间的混凝土和钢有空隙，会导致生锈。当然这个受到了西屋公司的强烈否认。

前面文章里面谈到了俺对飞机撞击的担忧，是因为在中国三门和海阳会各建设6个机组，但是最先的4台机组，据说没有安全壳加固以防止飞机撞击的设计。这个希望有关部门要澄清一下，如果没有设计的话，应该加进去，毕竟还没有建设完嘛。

当然不少读者回帖中谈到了秦山、大亚湾等等核电站，已经考虑到了这个因素。

AP1000在美国也会上马14个，分别会在北卡、南卡、乔治亚、阿拉巴马和佛罗里达各州。因此安全因素上，中国和美国是绑到了一起，要是有点瑕疵的话，美国技术就要输给法国的EPR了。

和AP1000竞争的就是法国的EPR，现在在建的是广东台山核电站。这之前，在法国和挪威，也个有一台在建，算是三代加技术。

中国其他在建的核电站，基本上都是中国的CPR1000技术。这些地方，有福建宁德、辽宁大连的红沿河、广东阳江、福建福州的福清、秦山一期位置的方家山。还有就是AP1000的湖北咸宁。

总之，中国的核电厂在选址上面，比日本要安全得多。而且有后发优势，选择的类型也比日本要好。当然，不是说，中国就可以放开胆子，像日本人那样不要命地胡来和乱来。

如履深渊，应该是中国核工业企业的基本态度。 *要相信技术，但不迷信技术。*

 

另外，在微薄上发了一条消息。
