# -*- org -*-

# Time-stamp: <2011-08-25 21:08:02 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 闲话79：能源，还是能源

[2011-04-09 15:52:50]


今天的原油价格（德州轻油）终于跳过了110美元大关，到了112了。

对这个价格，俺并不感到惊奇。价位不奇怪，但是时间点是快了一点。

大概是在2009年秋吧，俺看到了摩根斯坦利和高盛的内部报告，在这些报告里面，看到美国大投资行，已经开始炒石油。其目标价位，当时提出的是在2010年底是95美元，2011年底是105美元。

考虑到市场炒东西，肯定会有一帮傻冒在高点抗铁牛，所以通常要给一个10点的浮动空间，所以只要在105-115之间，都说明到了这些大投资行的目标点。

*其实这次的高油价，和2008年差不多，就是和经济的基本面没啥关系，而是和大投行和大基金的用来炒卖的弹药有关。美联储通过QE1和QE2的两次输送，自然这些大鳄手上子弹充足。*

因为这些大行冲击国际经济次序，自然是自己要靠掠夺发财，但是同时也是希望用高通胀来洗劫全世界，特别是希望高通胀导致中国社会稳定出大问题。

俺曾经写了一篇闲话，谈到大家的七伤拳。那么中国的七伤拳，就是把中国的经济发展速度降下来，把世界剩下的唯一经济发动机，给歇掉25-30%的速度（从10-11%增长降到7%），用来挤爆西方国家货币超发的泡沫。

所以大家可以看一下，在美国、欧洲和日本之间，倒底那一家会先爆。

从这个角度看，日本自己开始喝铀咖啡和钚牛奶炮制的鸳鸯奶茶，也可算是一个七伤拳吧。

*从地缘政治的角度来讲，现在所谓中东和北非的乱局，其实对石油供应并没有实质性的影响。* 因为这个地方的关键，是在沙特。而沙特比任何国家，在两手上都要强。萝卜沙特最大，你想结婚？国家给钱。你想买房子？国家给钱。你想办企业？国家给钱。

*沙特的钱，多得就像沙。这一大根萝卜，不砸死你，也会坑死你。沙特老国王，最想看到的就是让你结婚，然后拼命生孩子，拿老婆孩子栓住你。如果你还是想搞事，不甘心，那政府也可以出钱，让你投奔拉登叔，想做人肉炸弹，去炸美国人、英国人、以色列人，俺老国王决不拉着你，还帮你出赡养费，养你全家呢。*

一句话，不要在沙特内部搞。不听话的，杀无赦。而且全世界的大国都喊好呢。谁要他们离不开沙特的石油呢。而沙特稳住，国际石油就没有价格问题。

说是石油到达目标价位是预料之中，但是在这个时段，是有些早。也可以说市场利用了这次夸大的中东北非乱局来谋利益。即使没有这个借口，人家这些大鳄们在以色列的关系，还是可以在年底之前，搞出一些局势紧张的局面来，达到目标，并不是一件难事。

但是 *在这个当口，把油价炒到这个高位，对美国经济全面复苏有两个不利因素。* 一个就是打击了美国的消费恢复。另一个就是油价高涨带动的粮食高涨，会引发世界更大规模的乱局。这个会导致美联储的QE2，甚至之后的QE3和QE4，出台有更大的难处。

如果美国不能解决赶一大批资金到美国来的话，到了6月份，QE2到期的时候，美国的国债会遇到一个危机。

怎么办？其实一个办法，就是靠日本央行，大幅度增加流动性。而这些流动性，要以Carry Trade的途径，进美国来帮助支撑美国国债市场。还有就是中国的各路第五纵队们，是否要开始造势，帮助赶一批或者吓一批游资过来？

但是美国自己本身的资本，错误地压了奥巴马的注，最后发现奥巴马“反企业”，会不会这个阶段，过分投入，造成美国经济虚假繁荣，从而为小奥奠定连任的基础？或者还是折腾一下，把小奥拉下马再说，然后希望能够把自己人整上去？

小奥现在已经开始提前筹款，要预备10亿美元的竞选弹药，也许就是对面临的对手，颇为忌惮。

俺的感觉，就是如何做，大家并没有定论。所以应该看到 *美国政策的混乱和反复，会是这半年的常态* 。

而中国自己的能源战略，自然要加速进行，避免将来成为人家绑架的人质。

谈起天然气，不是读者都觉得中国的天然气储量，应该没有那么乐观。俺这里大致引用的是中国政府的官方数据，所谓宣传口的东东。实际情况是不是这么乐观，那么还要看近期的走势。

最起码中国的天然气网络已经颇具规模，就看供应量可不可以上来了。

另外很多读者，也问道，难道俺们也要把煤炭给推出去斩了吗？

最近注意了一个消息，就是中国的一家企业在3月底，投资了美国休斯顿的一家公司，叫做Synthesis Energy。投资额是8380万美元。

这家公司的技术特点，是用一道工序把煤炭变成合成天然气。据称非常经济、非常低成本，可以将低质煤炭，像是烟煤和褐煤，给变成高质量的天然气。这个技术，已经在中国内蒙古的褐煤，和山东枣庄的烟煤，当然还有美国、加拿大和澳洲的不少煤炭。

如果这个技术，不是忽悠的话，那么会对中国的天然气管道，也许提供另一个气源。
