# -*- org -*-

# Time-stamp: <2011-08-22 13:59:11 Monday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 【友人评序】

2008年在中国历史上注定是不平凡的一年。但这种不平凡不是体现在辉煌奥运会上，甚至也不是体现在四川大地震这种百年一遇的重大事件上——它们的效应主要体现在短期和局部，对长期和总体而言，它们的影响都是一般性的。 *2008年目睹的，是一种结构性和全局性的变化。*

这种变化首先是世界性的，这集中体现在由美国的次贷危机引发的金融危机以及它后续的对美国、对发达国家、对全世界的各种效应。这种变化是深刻的，虽然主流媒体想尽各种办法来掩饰各种问题及它们的深度，试图推迟危机的爆发，但在2008年，这种努力还是最终失败了。 *这个变化说到底，是世界秩序和格局的变化和重构，是以美国一国超强为基础的世界秩序的崩坏和难以为继。*

其次，是这种变化与中国的密不可分。这里有几层意思：第一，是这种变化的发生，本身就是中国参与塑造和促成的结果；第二，是中国又受到这个结果的影响，在短期之内，甚至表现为冲击；第三，这种变化的走向、趋势，仍然而且更加取决于中国的道路选择。这里面，国人对第一点的认识是最不充分的（外国人反而清醒得多），而这直接影响到对第二点的评估与应对，以及对第三点的愿景与方案。

面对这种客观的变局，主观能动方面的变化已经不可避免。2008年美国大选，民主党总统候选人奥巴马以"Change"作为竞选主轴，最终以较大优势取得胜利，说明美国全国上下在这个历史关头，对变化的认识已经比较到位了；但在大洋对岸，对变化的必要性、紧迫性的体认，在危机前的数年相对来讲却有些滞后。终于在金融危机的催化下，早就提出来的" *科学发展观* "，得以全面推动，并上升到了前所未有的高度。

在这个时候，对中国面对的外部和内部形势进行全面和深入的分析，并以此为基础重新思考、评价过去的成败经验，明确未来的方向和将要面对的问题，就显得十分必要了。"改革开放三十周年"的回顾并不意味着守成，更不意味着固化，而是应该首先着 *眼于未来，落实于创新* 。

在这方面，更多的声音、更多的视角是必要的，而井底望天的《大国游戏》系列在这方面是一个大胆而成功的尝试。宽广与全球性的视角是这本书的突出特征，尤其在对中国面临的外部形势和挑战方面，作者的很多分析都是独到的、新鲜的。对习惯于在既定的国际体制安排下进行安定生活的国人来说，这本书的很多观点甚至是具有挑战性的。但这正是这本书的价值所在。比如说，巴基斯坦的红色清真寺事件跟中国有何关系？四川大地震的同时缅甸在发生什么？关押在关塔纳摩的恐怖分子会不会被放虎归山？对这些问题作者都做出了分析和解释。

我们面临的内外挑战从来都是耦合的。 *准确认识外部的压力，跟"努力办好自己的事"永远是一体两面。* 所以作者在介绍与中国密切相关的国际局势的同时，时时注意落实到中国的应对之上，尤其是注意提醒那些薄弱的环节。在大多数人都目光都聚集在东南沿海和对外经贸的时候，作者提醒我们，在地缘政治和能源安全方面，要更多得注意西北与西南，尤其在缩小地区差距和推进民族团结方面，都有很多事情可以做。

*大国崛起，首先是大国民的崛起。大国国民的标志，首先是对大事、大问题感兴趣，* 在这方面，《大国游戏》对于这种社会氛围的培养，必将起到积极的推动作用。[fn:daguoyouxi0102]

[fn:daguoyouxi0102] 《友人评序》的作者为一名在日本学习、工作的中国年轻科学家，独立政治经济评论人。

