# -*- org -*-

# Time-stamp: <2011-08-22 14:05:20 Monday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 【忆江南·答读者等数篇】

【2008年6月2日·忆江南】

    那天，看了我哥哥关于江南的记忆后，忽然一股淡淡的乡愁从心底里爬了出来。它好像一条沉睡多年冬眠的懒蛇，阴阴沉沉的在荡漾的春日下，探出个丑陋的头。令我一颗死水般平静的心情，禁不住翻起了几丝波澜。

    记得年少的我，最喜欢在“穿衣欲滴杏花雨”的时节，漫无目的在江南的乡村里游荡。那时，总是在村口和田间，擦肩而过几位纯纯而土土的村姑。她们红扑扑健康的脸庞，完全有违历朝历代的文人骚客笔下那些纤纤细细，温柔如水的江南女儿。村姑们穿着打着补丁的蓝衫，黑色的裤子，一朵白色的茉莉花插在鬓边，那浓浓的香味和青春的体味，肆无忌惮的扑鼻而来，和着她们侬侬吴语的歌声，走出了好远仍让人不禁回首。

    当然，我那个年纪，还未到男性荷尔蒙沧海横流的时候，所以难以体会戴望舒之流的伤春人士，哀哀怨怨地在深深的雨巷里，打着把油纸伞，无聊病态地徘徊，想碰到那位象丁香花一样幽怨的姑娘。

那时的我，年少气盛，自以为是，恃才傲物和趾高气扬。虽不是出生在江东，却染上了江东子弟的豪爽之气，大概可以用二十年后自嘲的一首诗来描述：
最是江南少年郎
暮春烟雨独倘佯
浮云一片梳豪气
桃花数朵酿文章
才拙大言笑管乐
学浅低眼抛苏黄
二十年觉汗梦冷
拗口击节唱沧浪

管乐，指的是春秋战国时代的管仲和乐毅。管仲身为春秋五霸齐恒公小白的丞相，倡导“尊王攘夷”，保证了中原国家的集体安全。乐毅为战国燕国名将，对付强大的齐国，以弱胜强，连下70余城。三国时的诸葛孔明常以管仲乐毅自比，可惜五丈原而逝，无所建树。

苏黄，则是指宋代名家苏东坡和黄庭坚。二人诗词文章书法都是难得的大家，但政治上守旧而反对王安石变法。

    以我当时小小年纪，居然如此轻看古人，直是小子不知天高地厚，二十年后，为此汗颜，也不为过。

    而唱沧浪，指自春秋开始流行的大众通俗金榜名曲沧浪歌。

    战国楚人屈原被流放，遇一渔父。渔父问：“这不是三闾大夫吗？这么落得如此田地？”屈原叹道：“众人皆浊我独清，众人皆醉我独醒。就是这个下场了。”

    渔父劝道：“明白人都会变通。大家都浊，你就和他们一起和稀泥。大家都醉，你就和他们一起开怀好了。这么故作高深干嘛？”

屈原回答：“我听说，洗了头，至少也要弹弹帽子。洗完澡，至少也要抖抖衣服。跟这帮人混在一起，宁可跳进湘江喂鱼。这么洁白，怎能被这个俗世染尘？”

渔父莞尔一笑，走了。唱起了沧浪歌：
                     沧浪之水清兮，
                     可以濯吾樱。
                     沧浪之水浊兮，
                     可以濯吾足。
后来，屈原没有食言，果然跳汨罗江而死。

突然想到，下个星期就是端午节了。不知汨罗江江水，今年是浊兮，还是清兮？


【2008年7月22日·答读者之一】

    最近，一位极富才情的读者，送了我一首诗，病后小歇，以韵为答。

    原诗如下：
沧海横流酒数盏，万山纵览棋一盘。
枭雄剑指决战处，书豪墨洒青史间。
春秋功过谁人述，大国游戏我笑谈。
乱世自显英豪色，指点江山欲比肩。
笑濯长缨达旺南，醉饮龙驹北海湾。
朝踏樱花辕门侧，暮赏钟鸣西洋边！

    这里是我的答诗：
旧瓶仍见酒半盏，席地静思腿单盘。
蓝鸟咿呀荆棘处，红杏白萍相应间。
风云变幻何须述，前人笑罢无所谈。
乱枪杀黑胭脂色，可留狐裘为比肩？
依稀一曲梦江南，邻里新茶出台湾。
闲时撒水剑兰侧，但求顽鹿不吃边！


【2008年6月-8月·答读者之二（摘录）】

2008年6月
网友A：
    问井底老师一个问题：油价的大起传说主要是犹太人金融炒作的结果，为什么犹太人要为了一点小钱，让俄国、伊朗、委内瑞拉、沙特阿拉伯等犹太人的敌国得巨利呢? 
作者：
犹太人为利而行，是个没有祖国和道义的民族。现在的国际市场只是挤压西方价格体系中的消费者。对体系之外的国家并不有效。中国的很多石油，如果从伊朗，苏丹等地进来，就会是比较低的价格。

2008年8月
手机用户：
    我们是90后的，我周围的人都很自我为中心，但一到汶川地震和3.14事件，他们心就向内，刀向外，让我很吃惊呢。都关心国家。 
作者：
    自古英雄出少年。当年李世民18岁已经驰骋天下。不过年轻有才不等于成年也会如此。你可以看我的“忆江南”，就知道笔者在少年时很了得，但现在就无所作为。
不过，不要计较你的父辈的批评，他们在你的年纪，要比你们差劲多了，但向父母造反却是高手。哈哈。

网友60后：
    作者写得太好了。
    我是一个60后的大学生，看到年轻一代这么才华横溢，真的感到后继有人，老来有靠。
    我们这代人是从贫穷中走过来的，继承了祖父父辈用鲜血和辛苦给我们留下来的依然贫弱的江山。
    可能在你们的眼里我们这辈人有点唯利是图，这也是事实。从小我们穿的是打补钉的衣服，最多每个月吃一次肉，等到长大读了大学了，肩上背负了全家对过好日子的期望，父母已经在常年艰苦的生活后浑身是病了，家里也是什么积蓄都没有。我们疯狂的挣钱，什么累活苦活都愿意做，记得自己那十几年每天除上班还做老鼠工（现在说的第二职业）每天工作十六个小时。因为父母要养，后代要培养。
    到你们这一代的时候，也许已经不用再为养父母而发愁，而我们这一代，需要负担全家人。
    我们这代人对政治和国际风云的关注比较少，甚至可能连上网的比例都比较少。我们的心里更多的是工作工作赚钱赚钱，但是我们这一代也是社会的基石，现在还是社会财富的主要创造者。
    在我们的心里，没有物质基础，一切都谈不上。
    我们经常在让后代衣食无忧的情况下，辛苦之余也会忧虑，比我们物质条件更优越的下一代会不会成长为公子哥儿只会吃喝玩乐。然而在看到这么多才华横溢有强烈责任感的新一代，真的觉得中国有前途。
    我们这代人好比是一个体格不够健壮的辛辛苦苦的农民，一边是床上躺的是和恶霸打架浑身是伤的父辈，经常提醒我们不要忘了我们的祖传宝贝还摆在恶霸的博物馆里。一边是自己还打不过恶霸，每天超常工作还要忍气吞声向恶霸交保护费，以求恶霸不打碎家里的瓶瓶罐罐，不打自己的子女，给恶霸买路钱让他们低价持有我们的一些股份，以便能够通过那条被恶霸占了的村里的路外出打工。
    而2008年，恶霸又来对我们舞手舞脚要提保护费了，正打算象往年一样增加一些保护费，突然看到自己几个70后80后已经长大起来的儿子，亮出肌肉对恶霸说不了。

我们真的很高兴，儿女们很成器，能文能武，中国的未来在你们身上。

