# -*- org -*-

# Time-stamp: <2011-08-30 13:00:53 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 【第九篇·方向】

#+begin_center
【写作日期】2008年7月24日——30日
#+end_center


乱枪杀黑胭脂色，可留狐裘为比肩。

--自题

+ 八十一

如果我们看一下发生在贵州瓮安和云南孟连的事件，就可以发现这样一种社会思维逻辑已经初见端倪，即地方政府部门未能解决地域内部的各种利益纠纷，最后将警察力量摆上了台，希望能够通过暴力威慑而控制局面。而地方民众则希望通过挑起冲突，把地方政府的盖子揭开，以寻求高一级政府甚至中央政府的直接干预，来一次性解决长期以来不能解决的利益纠纷问题。

*这种情形确又透露出一个很重要的中国社会的特点，就是在地方政府管制水平极为低劣的今天，即使在地区利益冲突白热化导致大规模群体事件时，民众对政府系统尤其是中央政府的信心仍然很强，这就给予了中国政府一个难得和可贵的时间缓冲，使中国政府可以从容的解决地方政府管治能力的普遍问题，而不会带来全社会的整体动荡。*

理解这个问题很关键，这样才会得出对中国这个社会的现状和发展一个理性的思考，而不需要过激的反应或过激的变革来解决并非致命的问题。 *现在中国政府的两个施政重点，一个是发展，一个是稳定。这两个重点本身就是矛盾的，稳定要求的是少变化，而发展则是带来最大的变化，但是变化就会造成不稳定。反过来，不稳定就会阻碍发展。当然没有发展，社会虽然静如死水，但也就安稳了，可不是我们所需要的。中国三十年来的经济发展，在世界文明史上是没有先例的，所以造成的变化之大可想而知，如果要求中国政府事事都能未雨绸缪，提前规划，似乎有些强人所难。对没有先例的大事情，只能在小步骤上摸着石头过河，走一步，看一步。现实的做法，似乎应该是先清楚的明白快速改革和发展带来的问题会有一大堆，那么就要把它们的轻重缓急弄清楚，不得不解决的大问题，如环境污染、通货膨胀、基本民生、贫富差距拉大，就业机会，当下重药，摆上日程，而对第二等的问题，如政府管理水平、贪污腐败、公权力无制约等问题，可以放到第二步。对小程度的地区性的乱局，不需要过度紧张，就像人经常得小感冒一样，不断的可以增强免疫力，而不致于突发重病。*

和谐社会是一个值得奋斗的目标，但就没有必要为了一个表面上的和谐而忌病畏医，采取高压手段来寻求一个虚假的稳定。 在一切以发展经济为中心的口号下，经济生产的四要素：资金、技术、土地和劳动力，对于当地政府来说，自然知道其中哪些比较稀缺，哪些相对过剩。设想一个穷地方，想吸引唯利是图的资本家们来投资，自然要不得不做出某些方面的牺牲，才会令这帮吸血鬼跑过来。如果不是在这些穷地方可以逃避其他地方更严格的环保法规，更健全的劳工保护，这帮混蛋干嘛冒这么大的风险，飘洋过海穿山越岭过来创业？而当地政府给予的各种优惠，不计算官僚们经手的好处费，自然是通过土地、人工等方面的克扣，来吸引这些外来投资，指望他们可以为当地经济添加活力，创造出繁荣局面，提高当地人民生活水平，最后，为自己升官建立政绩。

在这种情况下，当然很明白一个官员的屁股会坐到那一边。 你觉得他会去得罪那些物以稀为贵的投资外地商人呢，还是多得赶都赶不走的民工？这从整体上，结果就会变成以一部分民众未能得到其应有的经济利益为代价，来对整个社会起积极作用。 *现在要解决这个矛盾，一个办法就是放弃以经济的快速发展作为政府的首要任务，开始平衡思考发展中的民众各方的利益分配的协调，即胡锦涛主席号召的科学发展观，采取重质而非重量的方法，使经济发展趋缓一些，但是当地的群众则可以真真实实的享受到经济发展的好处。避免某些地区，空有一个飞速增加的GDP账面数字，而得益的却更多只集中在一小部分利益群体上，甚至是即便大家的碗里饭多了，但想烧政府大楼的情绪却积累激化了。*


+ 八十二

中央政府可以做到的是，进行一个标准的人民民意普查，通过经济发展、环境保护、社会治安、人民生活、政府水平五个方面按期收集民意，作为对地方官员政绩的一个评判标准。而地方政府在评判标准的改变下，则应该逐渐有意识的退出经济发展的参与角色，不再直接介入当地的各方利益纠纷，开始扮演一个中立和中介的仲裁角色。警察力量要变成维持社会次序的力量，而不要变成各方力量角力的先锋。而且对一个地方的有限乱局也不必过度反应、乱用重典，事后对违法犯纪的官吏和借机打劫的分子同时秋后算账，这反而对长治久安有好处，打完这些官民两边的害群之马，双方理性温和的势力才可能抬头。

*如果看一下中国近期的发展，大致有几种情况。* 一种是沿海地区如珠江三角洲，投资商来自香港，劳工来自内地。当地人要么通过亲属关系帮香港老板亲戚做管理阶层，或者偷师学艺成功，自己出来当老板。这种当地政府的功能很明确，完全让市场机制处理去外地劳工的薪酬问题，而全力保障外商香港老板和本地二老板和管理层的利益。因为这些被剥削的外地劳工都是外地人，缺乏当地政府的人际关系，所以没有组织和人脉可以向当地政府进行挑战。再加上在开放之初，即使是微薄的低工资，由于沿海和内地的巨大差距，居然要相当于好几个月的中西部内地工资，所以这些外地民工过去也一般接受了这种结局。因此在这种条件下，劳资冲突的主要原因是来自于工人的欠薪和因为工伤引致的残废赔偿问题。

后来，由于市场体系相对完善，各类企业来自世界各发达国家，也带来对什么是公平待遇的不同解释，加上开始有对熟练技工和工人对企业认同感的需要，市场机制开始调整提高工资水平，以减少频繁的跳槽带来的产出损失。

在这种情况下，加上中央政府对农业税的减免，和一些早期的熟手工人开始回到家乡，用几年的血汗钱建立自己在乡下的企业，就造成了一定程度的劳工短缺现象，使工人在生产要素的方程式中有了更有利的竞争位置。而中国经济下一步必须调高产业换代，由发达的沿海地区向高附加值产业链提升，强制保护工人利益，为中国创造出可以和日本竞争的高技术工人阶层，那么就必须有《劳动合同法》（新劳动法）这样的保护工人阶级合法权益的法律出台。

这个新法规会推高中国沿海地区的劳工成本，迫使这些地区从低利润的服装、制鞋和玩具外来代工等低端工种，换代成至少是中利润的电脑、机械和通讯设备的外来代工。而随着工人素质和质量管理能力的进一步提高——只要知道所有的世界名牌产品都在中国生产，就知道工人技术不是问题，工人工资进一步上涨，中国的企业就无法也不应当再以产品代工的身份去赚取品牌的高附加值，此时就要靠华为之类的公司与人竞争。这是一个必经之路，因为最好的制造工人都在中国，一旦名牌产品如索尼、思科必须走到越南等地去寻求低工资，他们的产品质量就不会超过中国自己的品牌。这时中外企业的竞争就变成了销售、包装、广告和服务这些软活儿。

*中国政府在《劳动合同法》（新劳动法）上一定要坚持住，不然的话，中国的发展将走入死胡同。*


* 八十三

当然不是所有靠外来劳力来支持经济生产的地方都可以避免官民冲突，但是至少由于缺乏本地民众的介入，这些冲突的规模要小很多。比如发生在广东惠州的湖南民工对地方政府的冲击，颇类似清末广东人在上海的小刀会对当地政府的挑战，这些行为基本上和地方利益纠纷无关。甚至更可能是当地政府为当地人利益，与外地人口在其生活和生存空间上的博弈。其中恶劣的行为，如山西的黑砖窑事件，绑架外地的童工为奴隶，但这种“生意”就得到了很多当地人的默许和支持。 *和本地人相比，外来人口总是要吃亏和受气，这似乎是个普世真理。* 即使今天的美国，常常被当地人欺压和盘剥又投诉无门的，通常是来自墨西哥和其他中美国家的非法移民劳工。

中国发展的另一种情况就是在中西部。与珠江三角洲的发展道路不同的是，在西南这些贫困省区，当地的人民没有办法去寻找什么其他地方的外来人口来供自己剥削，所以只能退居于最后被人吃完肉，喝完汤后舔舔盘子的地位。而当地的地方政府也与沿海地区的各级地方政府不同。沿海各地政府特别是珠三角地区的政府维护商家利益时，也一般就维护了本地人利益，只是会损害外地劳工利益；而这些地方政府在维护外来商家利益时，就损害了本地人的利益。经手这些工作的官员，由于没有替罪羊可以拉出来宰，只能下求尽快满足自己私人、亲属和朋友的利益，牺牲广大对他们无关紧要的百姓，这样就导致了他们和他们的群众基础的分裂。

在这种情况下，进行民主选举是毫无意义的，因为无论你选出什么样的官员，如果他所面对的是同一张大饼，无法照顾普遍利益的话，最后的结局还是要抢先分他和他的支持者的利益的，这对管治水平的提高，是换汤不换药，不能得到实际的变化。更为危险的是，在民主选举制度下，中西部的官员们可能不得不通过非经济的身份来寻求政策的支持者，由于他们不少人来自外地，所以不能像广东一些地区那样用语言和文化，来区分“我们”（说广东话的香港商人和本地官民）和“他们”（韶关以北的北方佬），那么，像“城里人”和“乡下人”，或者更恶劣的汉人和“蛮族”（少数民族）之分，就有可能冒出丑陋的头出来。在实行了民主选举的印度各邦及以下级别的地方政府折腾出来的印度各宗教各教派之间的残杀，就是前车之鉴。

单纯的依靠纯粹的市场经济模式，似乎不是一个最好的解决方法。考虑到目前对西部和内地的开发大多是以资源和能源为主，调整这些资源能源产品的价格，让他们趋于合理化，让穷地方多留利，是一个事半功倍的好办法。这样可以把这些地方的利益大饼做大，这样当地政府官员在分饼的时候，困难要小一些。另外的方法是，对矿山等资源进行国家专卖制度，凡是参与开发的（外来投资）企业，必须缴纳特殊费用，达到既保证他们获利，又限制其利润率，这样就使当地百姓吃剩菜的时候，还有点油水可舔。再一个就是发展中国自己的“公平贸易”系统，减少对落后地区产品的压价收购，取消不必要的中间环节，让这些地方的产品，可以直接在大城市的超级市场直销。

如果说美国政治制度中有最值得学习的部分，那就是将 *政府功能分散化* ，它的客观作用是让抗议的矛头消散，不会大闹。比如说前一阵美国纽约警方的过度使用暴力，激起黑人百姓不满。事情是一位第二天就要结婚的黑人新郎，在参加完单身派对后，被警察用50多枪射杀。结果这些警察被告上法庭，但就和所有之前与之后射杀黑人的警察一样，被宣判无罪释放。当然了，黑人们又会走出来抗议几天，但最后就是不了了之。因为美国和中国不一样，对警察的不满，不会变成对纽约市政府的不满，即使对法院的不满，也会大事化小小事化了变成探讨法律程序中的几个普通陪审员为什么就那么“糊涂”的学术性问题。而在中国，一个集中的政府（尤其地方政府），当然有效率高的好处，但也有要承担所有责任的坏处，这种政府比较容易成为众矢之的。


+ 八十四

另外需要考虑的是，美国的村镇大会（Town Hall Meeting）因为与人民的日常生活非常有关，讨论的事务非常直接，不需要代议（从而让专职政治骗子没有机会），可以为中国地方政治的决策透明度和地方事务的民意参与提供一个好的参考。这个大会最主要的功能不是在于选举镇长，而是在于对镇子里的大事直接咨询和发表建议。对任何市政方针提供正反双方的辩论和公证会，以提高政府决策的透明度和广泛性。在中国各大城市的小区里，和小城市的镇子里，都不失一个可以借鉴的好方法。

而中国乡镇的发展模式，依靠香港老板、本地人参与，利用外来廉价劳动力的珠江三角洲模式并不是唯一可供参考的范例。浙江依靠私人企业及江苏过去依靠乡镇企业的做法，都是相对更可取更值得借鉴的榜样。当然这些地方的人民素质比较高，开放程度比较大，见多识广，加上心灵手巧，这些素质不一定在中国所有地方都有，但也并不是就要求中国所有地方都能够富比江南的程度。只不过是说江浙案例在如何带动共同致富，减少快速贫富分野方面会有所帮助。

在如何重建中国乡镇这个大课题上，从清末、民国到人民共和国，有过很多实验，也有过成功和失败的各种教训，其总体有一个倾向，就是都不去讨论如何将这个层次当作自身一个实体来建构，而是想方设法要将所谓城市里的先进方式，从政治体系、文化建设、社会组织等方面，去向“落后保守”的小城市和乡镇推广渗透。而中国的所谓“大城市文化”，如上海、广州、天津等等，又受到西方文化的强烈影响，其形式上的“非中国化”和作为中国传统的根本基地的农村之间，当然具有一定的冲突。国民党号召的新生活运动，就是城市压制乡村，想强行在乡镇推行现代化的过激例子。而五十年代的人民公社，也是不顾当时的客观社会组织条件，强行硬上马带来比较严重的负面影响的历史教训。

毛泽东政治革命的成功却靠的是一个对这种趋势的完全颠倒，即反过来，以农村和乡镇包围大城市。因此中国的改革家们需要一种新的思维，就是在中国城市化和现代化的过程中，如何发挥中国的传统（也就是说让现代化不一定是“非中国化”），创新出一种新型的新乡镇体系。而不是采用线性思维，简单的把大城市的发展，完全照搬到这些地方。因为在中国宽阔的内陆大地上的问题，不可能靠“深圳的香港化、东莞的深圳化、韶关的东莞化”这样的“轮轮‘改造’、依次‘非中国化’”来解决。

也许中国应该花一些时间，好好研究北美如美国和加拿大的小城镇和乡村建设方法，以及德国巴伐利亚州的先例，再结合中国苏南、皖南和浙南的实例，也许在这些方面可以有所作为。

当然以乡镇为主体，就必须最大可能的让乡镇居民和精英们对地区的事务有极大的参与权和决定权，而不是让来自于“发达城市”的管理者高高在上的训斥。从这一点上，中国的政治改革就应该从现有的乡镇选举发展一步，开始定期透明的乡镇大会，对短中期的重大决策、群策群力、民主集中，学习当年共产党三四十年代在乡镇依赖民意施政的好传统，不断通过专业化的经济、教育、卫生、环境和发展委员会，将地方上的各类党内和党外的能人都包括进来，逐渐将社会的非政府机能从现有的政府体系转移出去，最终形成一个新局面。当然，在这个过程中，要注意机制制衡，避免出现一地的治理让某一强势家族势力一手遮天。


+ 八十五

中国政治改革的一个误区在于，现在某些理论派人士，对民主制度寄予了太大的幻想和过高的期望值，以为只要有了民主这个“好东西”， 一切疑难杂症都会在这副灵丹妙药之下迎刃而解。这种荒唐的想法的逻辑和当年文化大革命期间那套“宁要社会主义的草，不要资本主义的苗”的理论，其实颇为相似。

西方社会通过自己数百年的社会实践，发展出来适合自己传统和文化的西方民主制度，是用了很多的努力的。如果中国人以为可以越淮而橘，不费吹灰之力，就能享受人家的成果，那就是真的发南柯一梦。中国人需要做的是老老实实地虚心学习别人的长处，不光是西方的，还有东方的如日本、新加坡，包括我们自己的台湾和香港的各种政治实践，取其精华去其糟粕，然后针对中国的各种政治现实，进行渐进的、实验性的尝试。不是把建成一个叫什么名词的模式为目标，而是 *立足于解决具体的问题，最终为自己创造出一个适合自己的政治制度* 。而且由于中国文化的多元化，可能最后的结果还会有几种不同的模式。当然这个过程是很辛苦，不是一蹴而就，但是没有办法，天下没有白吃的午餐，一个懒惰，不愿意动脑筋创造和辛勤付出的民族是没有好日子过的。

世界上许多人对美国政治制度的一个最大的误解，就是以为美国是真正的民主社会。这些人并不知道美国的实际政策并不是由民选出来的领袖人物决策。 *美国的精髓是“自由”，也就是自由资本主义，而大家都知道资本主义的灵魂：资本，是不能靠民主来决策的，而是由专业的精英阶层控制操作的。各种社会其实都一样，它们的社会制度必须保障其中认定的精英的利益，比如说美国保障美国的资本（金融）家，中国古代保障儒生，以及不同宗教社会里保障教士、和尚、喇嘛等等。*

英国在香港的做法就非常直接露骨。英国人是在绝对保持英国人在法律（大部分法官由英国人担任）和银行界（汇丰、渣打、有利银行等英资银行为发钞行）的支配地位后，才开始向香港华人开放其他经济领域的。在英国人实行的立法会上，为了保障有钱商界的利益，采取了功能组别与民选名额严格区分的方式，让相当大比例的立法会议员专门从所谓“专业功能组别”的小圈子中去选（比如商业、会计师、律师等等），使有钱人比一般老百姓有更多的发言权。商家人士为他们的地区代表选举之后，又可以在小圈子里再选一次，以保证在立法会里的一定份额。这样可以在任何法律问题上，充分考虑到商界的利益，而使香港保持一个自由资本主义经济体系的状态，由商界和法律界精英操控。

美国的做法就是，把国家政治里非常重大和关键的经济政策权利，从民选的政府里分离出来，由私人机构去控制。这个系统就是有名的美国中央银行——美国联储系统（Fed），其权力移交和美国的选举无关，其内部运作则是由美国的各大金融机构控制，而且其对国家经济政策的决定，不需对公众负责。美国联储局名义上是政府的一部分，但实际上不光可以不听命于选民选出来的政府，反而可以用专家管理的名义，实行和政府以及民意相左的政策。联储局由十二个分行组成，而这十二个分行则由美国各大银行控股，由这些银行的老板出任分行行长。这些主要银行估计大家都非常熟悉，如著名的银行花旗银行、摩根大通、美国银行等等。当然总统和国会有权任命联储局的主席，但是这些职位，以及美国政府里财政部长，一般都是来源于华尔街的专家（如现任财政部长保尔森就是高盛的前老板），所以最后的美国经济政策当然要围绕这些金融资本巨头大银行（以及团结在这个核心周围的券商、交易所、经纪行、信用社、房贷商、保险商等等）组成的华尔街利益集团转圈。


+ 八十六

而在决定经济活动和资本流向，利润分配这些重大决定时，美国的普通公民是没有说话权利的，只有华尔街的股民们可以通过道琼斯和标准普尔指数，对联储局表达少数的“有钱”阶层的民意。如果你觉得这些大银行的老板们坐下来，为联储局的下一个货币政策做决定的时候能如圣人一般不考虑他们自己的私人利益的话，那就是太天真了。那么有人问可不可以对这些会议的全部记录进行媒体监督呢？不可以。每次联储局开会，会在一个月后公布开会的纪要，但是按照美国法律，联储局不会为这些会议保持完整的记录，且记录也分三种，公开的那种很不完整，而且语言极尽可能的晦涩，而不公开的部分受到国家机密保护的程度比中央情报局还要厉害。

基本上，美国的联储局是一个既是政府部门，又是私人机构的怪胎，但却就在美国经济运转中扮演了一个心脏的角色。美国大企业家亨利·福特曾说过，如果美国普通人民今天晚上知道了联储局是怎么一回事的话，不到明天天亮，就会有一场革命。本来，联储局的任务是通过这帮自我约束的保守主义的金融大亨们，来抵制民选政府里的民粹主义盛行的国会和行政部门，对美国的经济进行自我调节的自由资本主义式控制，但是当这帮大亨肆无忌惮的只是追求自我的利益，罔顾普通人民的权益时，就会出现07、08年这样的系统崩溃的危险。而美国当前由次贷危机带来的整个资本主义金融体系的信用危机，和联储局的胡作非为具有极大的关系。

*某种程度上，美国历届总统候选人在参选时，都会靠咒骂中国来增加选票。因为美国民意中的中国，被西方媒体妖魔化得推到极致，美国的普通人民均被洗脑。* 但是这些赢得了民意的总统们在当选之后，却个个实行和中国合作的政策，不惜与民意背道而驰，其中一大决定因素就是华尔街的大亨们和中国关系不错，期望能够通过代理中国人口袋里的庞大积蓄，来赚取巨大的利润。当然这种想法说起来也无可厚非，如果中国人可以通过和他们的合作，真的能得到双赢，那确实何乐而不为。

但是中国人需要搞清楚的一件事，就是如果有一天我们要让步到允许美国大银行以控股的方式参与到中国的各大银行的运作之中，就必须同时保证让各中国的大银行也可以以对等的方式，参与到对美国大银行的控股中去。[fn:jdwtdgby0994]而且不能由美国国会使绊子，挖陷阱，出现迫使中国金融机构参股控股却必须放弃投票权之类的流氓行径。

[fn:jdwtdgby0994] 从2008年的后继局势发展来看，这个“不公平”在危机中反倒是对中国的金融企业起了一定的保护效果。但是等到危机结束之时，笔者的主张仍然要加以贯彻。——作者补注。

另一件不能让头脑发昏的事情，就是中国的金融改革中，不能完全听信华尔街的大亨们出任的“专业顾问”的意见，也不要完全信赖那些来自香港金融界的买办混混们的建议。所谓让中央银行“独立化”，就是让中国的中央银行国际化，变成这些华尔街大亨掌控的全球金融自由资本主义的其中一环。 *中国的人民银行必须听命于中国政府的国务院，成为服务于中国整体经济的一个宏观调控机制，不能被私有的尤其是国外私有的金融机构绑架。*

美国另外一个限制民主政治的机制是选举中对初选的高门槛政策。如果你想参选，而且不是只求玩着爽一回的话，就必须参加进民主和共和两党，受到其利益集团操控的现有格局的严格控制。初选的起始金额是1500万，如果你的捐款只是平民来源，而不是富有的利益集团，一个热身赛就会令你弹尽粮绝，无以为继。


+ 八十七

所以最后剩下来的幸存者，都不得不对现有的利益集团的财政支持和竞选承诺，作出一定的妥协，而保证这些集团在新政府的政策中，能够得到合法的利益输送（不然干嘛当初出钱给你）。看一下美国政府的行政机能，除了被分出去交由华尔街控制的经济部门如财政部等，剩下的另一个大头，就是对外关系中的国防部、国务院和情报部门。而这些部门的技术精英则由石油大亨、军火大亨和国防部承包商完全控制，通过由退役的将军们和政府官员在这些企业出任高位来进行利益连锁，再由这些企业资助的各种思想库，如美国企业研究所、兰德公司、外交关系研究会[fn:jdwtdgby0995]等等智囊组织，提出方案，然后大家就瓜分占美国政府最大财政份额的国防预算。

[fn:jdwtdgby0995] *美国企业研究所* ，American Enterprises Institute （AEI），创办于1943年，是美国为企业商界代言的思想库，以鼓吹“有限政府、个人自由、私有企业”等美国自由民主资本主义的“精髓”著名，在小布什上台以后非常活跃，成为顶级思想库。 *兰德公司* ，RAND Corporation （取英文“研发”二字字首合成，Research and Development），原为美国军方进行军事运筹研究的机构，后转变成覆盖范围广泛的智囊咨询机构，一些著名学者，如鼓吹“历史终结于民主自由资本主义”的日裔美国人福山曾供职于此。 *外交关系协会* ，Council on Foreign Relations （CFR），被认为是对政府尤其是外交政策最有影响力的私人思想库。现任主席是David Rockefeller。有重要影响力的出版物《外交》（Foreign Affairs）

当然美国在这个世界秩序里，还是要采取内王外霸的方法区别对待。对自己一类的那帮朋友喽罗，如号称的“自由世界（Free World）”或者“国际社区（International Community）”里的盟国，主要还是要用谈判协商的方法，以王道来分赃，但是对非我族类的阿拉伯-穆斯林世界、非洲和南美，那就是霸道的做法，以暴力和阴谋，随便牺牲美国南部和中西部民风淳朴的小伙子（Rednecks and Cowboys），让他们作为普通士兵，在为上帝和为美国梦想而战的名义下，用血来换取这些私人企业的高额利润。

而美国内部的无聊纠纷，就通过繁杂和低效的法院体系，让普通人为一些微不足道的蝇头小利，或毫无现实意义的意气之争（比如可不可以堕胎，同性恋可不可以结婚之类），在这些法院的各种一审、二审、上诉、反上诉之间的冗长的程序中，浪费时间耗来耗去。国会则是作为美国民主的门面，让各种声音在那里炒得不亦乐乎。除了为地方分猪肉而不顾及美国整体利益，天天忙于通过肉桶议案[fn:jdwtdgby0996]外，美国国会最拿手的把戏，就是对世界各国和他们半打子都扯不上关系的事情上发表议案进行抗议。比如说，中国的西藏问题属不属于国际事务啊，土耳其当年对亚美尼亚人动武算不算种族屠杀啊，法国炸薯条该不该改名成自由薯条啊，等等等等，忙得不亦乐乎，而自己国家的问题，只要民主党和共和党发觉不可能在问题的爆料过程中打击对方而让自己上位，两党操纵的媒体就会只字不提，当没事发生过。

[fn:jdwtdgby0996] “肉桶议案”，Pork Barrel，指国会议员“为本州选民和利益集团的项目争取联邦经费”的议案项目，其中部分项目纯粹是浪费公共资源。比如2008年9月底的7000亿美元救市议案，在众议院修改通过时，就因为塞入大量此类子项目、附属条款，让该议案从3页膨胀到450页。例如为了专门挽救一家曾经提供过政治支持的玩具公司而在这种全国性法案里硬塞进专门优惠玩具业的条款。

当大寡头拿走了国家的大头利益之后，他们也不得不扔下些骨头给其他没有这些特权的人群享受。因此国会和法院就是一个好的场所。各种非重要的团体，就开始形成自己的利益集团，出动自己的游说公司，开始收买各地的国会议员。当然，金融大亨、石油大亨、军火大亨之流的大人物因为拥有政府已经拿了大头，就不会再参与这些鸡毛蒜皮的蝇头小利之争。此时留下空间，让工会来游说他们的贸易保护法案，印第安人来游说他们的支持赌场修建议案，黑人来游说他们的公平法案等等。

而在其他一些非重要的政府部门里，就进行某种程度上的利益分赃，让给那些次要团体。比如说邮局、税务局、车辆管理局、社会安全局，再加上公共教育系统，就交给如黑人中产阶级等，让其获得了垄断利益。至于造成的公共教育质量低下则无关紧要，反正有钱人的子弟会在学费昂贵但教育质量高的私人学校就学毕业，保证他们的竞争能力和特权。这些贫穷的黑人和拉美人的子弟则也还是可以通过管理松懈的公立教育体系拿到名不符实的毕业证书，去那些他们爸妈退休空出来的政府低层职位就职。而美国的法院则是一个缓缓运作的绞肉机，让人们在公平和正义的假象中，慢慢的消耗。


+ 八十八

只要美国人民可以每天从电视上和报纸上读到他们的幸福美满和自由的生活，又可以在每两年一次和每四年一次的国会和总统选举的好莱坞大戏上演中感觉他们是国家的主人，以为自己可以改变这个社会而对未来充满希望，那么，这个民主选举游戏当然可以继续玩下去。

中国是不是该有这样一个制度？很多理论家会慢条斯理地告诉你，其实啊，任何制度都有其短处和长处，代议制民主制度一样，不过呢，西方的代议制民主制度虽然问题很多，但却是问题最少的一个制度。他们的说法也许没有错。中国拥有这样一个制度也许不是什么坏事，但是问题是，我们应不应该用巨大的社会代价去换取这个制度？ *我们的改革家们和理论家们，在吹嘘这个制度尽善尽美的时候，是因为自己无知，食洋不化，传递错误的信息，还是有意误导我们的人民呢？*

美国的PEW公司推出他们的全球民意调查，发现中国的民意中82%的人民觉得中国的发展方向是正确的，86%的人民觉得中国的经济状况很好。这些都是全球23个调查国家里排名第一，比排第二位的澳洲要高出20个百分点。[fn:jdwtdgby0997]

[fn:jdwtdgby0997] 当然，这种民意调查可能由于其采样、统计的偏差，有其一定的局限性，但仍然可以说明一定的问题。中国人只要正视问题，理性对待，一定能解决各种矛盾，决不会输给任何国家。

同样的调查在美国只有23%的美国人民认为国家走的路子是正确的。为啥自我感觉人民可以参与政治民主，改变社会的美国人民对未来的看法，要比没有这样的参与力的中国人民要灰心？这难道不值得研究东西方政治制度比较的专家们思考吗？

并不是中国人民对当前中国的政治制度没有意见和没有要求改革的需要，大伙儿对通货膨胀、环境恶化（宁肯经济速度放缓，就业机会减少，也希望改善环保）、贫富加剧、地方政府腐败等等，都是意见很大，但大家对这些方面的改善也有信心。只要中国政府和民众保持清醒的头脑，增加基层民众对施政的参与度，做到施政的公开性和透明度，提高基层政府人员的素质，增强对官员行为的党内和党外的监督，有限制的放松地方官员对媒体的干扰，通过对全国性民意论坛上，尤其是互联网的控制放开，形成一个普遍的各级政府对人民民意的尊重，中国就可以对西方的民主人权自由之类的无聊说教、无赖诬陷、无知指责和无耻抹黑，无动于衷和不屑一顾，根本不需要浪费时间去废口舌和人辩论。

中国人更不需要低声下气的，很抱歉的向西方人解释，中国因为国情，因为落后，还需要等待更长的日子，才可以仿效西方人。我们可以告诉他们，到底中国现在的情况有多少中国人满意，西方的现在的情况有多少西方人满意。我们可以告诉他们，中国不需要选举希特勒的民主，不需要弗吉尼亚工学院的自由，不需要让印第安人开赌场谋生那样的少数民族政策，更不需要黑人高比例坐牢的公平法律系统，不需要关塔纳摩的人权，也不需要伊拉克战争的外交政策。西方人可以自己在家里意淫，认为自己的制度完美的很，不过那些都是和中国人没有什么关系，中国人必须走自己的路，把自己的事情做好，仅此而已。[fn:jdwtdgby0998]

[fn:jdwtdgby0998] 本文写作于2008年7月份，该年9月金融危机深化之后，“走好自己的路，办好自己的事”似乎变得流行了。——编者注。

如果他们仍然喋喋不休的话，告诉他们十年后大家再看看吧。


+ 八十九

*中国人应该感觉到很幸运，因为他们在这过去的三十年中，居然有了一个喘息的空间，能够无大碍的发展经济，改善人民生活水平。在西方各国投入的军费仍然超过世界总军费的70%，在中国常规军力仍然落后西方至少二十年的悬殊实力下，在以美国领军的北约指东打西，走南闯北的恶劣国际环境下，中国居然没有被人教训。这自然和后院里那几根粗壮有力的狼牙大棒——战略核武器有关，但也和中国让人馋得流口水的潜在的巨大市场有关，和中国政府倡导的开放改革和经济全球化令那些西方的大商家们心有盼望相关。当然，世界上总是有些脑袋比石头硬，不知天高地厚，但是就有几分血性敢于向西方叫板的小国枭雄们，不断地将西方敏锐的鹰眼，从中国这个大块头身上引开。这个反西方的阵营是中国在西方独断的丛林里谋生存、求发展的天然盟友，虽然在西方长期的军事打击，经济封锁，政变阴谋，和舆论中伤下，这些小国居然有野火烧不尽，春风吹又生的燎原之态，为中国在争取善意的国际空间下和平发展，提供宝贵的同盟军作用。*

*中国人应该庆幸，到目前为止，除了在贝尔格莱德挨了几颗炸弹之外，中国基本上躲过了西方的军事打击，从而可以在这段时间里大力改善国防的落后水平，使任何针对中国的军事行动成本越来越高，以至于不符合西方发动战争的利润原则。虽然这段时间里，中国已经变成了北约的第一号敌人和打击目标，但是由于北约仍然忙着“攘外必先安内”，不得不投入精力解决南斯拉夫这个异类，又忙着蚕食俄罗斯，打通被俄罗斯控制的中亚能源走廊的出口。并还因为其东进战略在格鲁吉亚-乌克兰一线受阻，西方的前线基地土耳其也极有可能被开发成一个基督教与伊斯兰教绞杀的新战场，西方无暇东顾，完成缝合他们的包围圈。*

在中国的俗话里，有一句话是“朋友来了有好酒，豺狼来了有猎枪”。这句话其实是错的，因为中国人不明白，来自西方的很多人，特别是政客、非政府组织及到处搜集攻击材料的记者，本质上并不是中国人的朋友，只是当你的猎枪口径够大火力够猛时，他们就才会不得不成为你的朋友。所以中国人今天要唱的流行歌曲，应该是“ *猎枪够大有朋友，猎枪没有见豺狼。* ”

西方人对中国人的偏见和恐惧不是那么容易消除的。来源于东方的匈人是导致西方的西罗马帝国灭亡的主要起因，被称为“上帝之鞭”的阿提拉令西方人胆寒。同样来自于东方的突厥，消灭了西方古典文明的最后领地东罗马帝国，占据了君士坦丁堡，令西方进入了没有文明的落后蛮荒时代。又是来自东方的鞑靼和蒙古，对西方民族进行又一轮的杀戮。可以说从19世纪的“黄祸论”到20世纪末的中国威胁论，把中国人妖魔化，都有其历史和文化上的渊源——虽然这些东方草原民族和中国文明本身无直接联系。这不是中国人大声说自己热爱和平，把龙的形象藏起来，再把憨厚可爱没有威胁的大熊猫抬出来，就能够改变，让西方人睡个安稳觉的。

西方人并不会像这些中国人所希望的那样去理解，他们更可能认为：你看那《功夫熊猫》里面，那只傻傻肥肥的大熊猫，表面上是一个安稳温顺，不和人撩事斗非的中餐馆端盘子的侍应，其实他和他的同胞唐山大兄李小龙一样是个西方人恐惧的武士，虽然在端盘子，其实血管里其实流动的还是凶猛的到处喷火的“龙”的血液。而且，这只功夫熊猫，由于他的可爱笑容，恐怕比凶猛的龙更要可怕。所以，思维的差异，会令认识的差距不断加深。 *中国人不要一厢情愿，一定要做好心理准备，无论你如何和平，别人都会强行把西方的喷火怪物（当然，这种“龙”的形象和中国的龙完全是两回事情，但好莱坞已经不去做任何区分，而是不断强化这种印象，胡编乱造的《木乃伊III》就是一个例子）的大帽子安在你的头上。*


+ 九十

估计在可以预见的将来，中国在西方公众的形象仍然会被继续抹黑。不过中国人也许需要平心静气的面对这个情况。因为西方的媒体其实对广大的公众而言，并没有那么大的号召力。 *西方的普通人民，和世界各地的人民一样，更关心的是物价是不是上涨了，工资是不是调高了，工作机会是不是多了，生活的费用是不是降低了，孩子的学校教学质量是不是提高了，社区里的治安是不是恶化了等等此类不被媒体精英们看得上眼的鸡毛蒜皮的小事情。* 而媒体精英们和专家学者们，关心的是如何造成一个全民皆兵和同仇敌忾的假象，以区区数人，比如说几个专职抗议人士，冒充百万大军，摇旗呐喊，摆出一副声势浩大的场面。

笔者认为，中国政府略有不当之处，是在奥运会的对内诠释上，过度的和三十年改革和开放取得的经济成绩相联系。中国人民扬眉吐气，欢庆自己的好日子，当然没什么错。只不过以奥运会作为契机，打开大门欢迎各方客人，也应该了解一下哪些人是来助兴同乐的，哪些人又是来砸场子的。其实中国人应该有颗平常心，知道自己今天的好日子来之不易，除了通过自己的辛勤努力，还包括了许多老朋友、穷亲戚的护持，在西方惹来憎恨的白眼、嫉妒的红眼、愤怒的青眼、不屑的冷眼和贪婪的热眼，都是极其正常和可以理解的事情。 *只要中国继续保持和外界交往，继续平和的面对外界的指责，只要中国的经济发展对西方国家的真正操控的大亨们仍然有利可图，任何在国际舆论上对中国的口诛笔伐和任何政客的搔首弄姿，都对中国的实际利益没有损害。这样的日子多一天，中国的实力就会增加一度，从而可以避免过早的同西方在军事上摊牌。*

只有在中国自己的经济实力发展到可以和西方抗衡的时候，当西方资本对中国市场的梦想落空，西方本性里希望用暴力解决问题的习惯才可能重新抬头。正如当年大英帝国在鸦片战争前对曼彻斯特商会的保证是，以中国一个省份的市场，就可以令这些英商有做不完的订单。只有在中国政府实行像清政府那样愚蠢的闭关锁国政策的情况下，用武力打开中国市场才会成为西方资本的首选。 *只要中国政府保持有限度的开放，能够在保障本国商业利益的情况下，不断的扔些甜头出来，中国应该还是可以争取到10-20年和平的世界环境，可以任由美国和北约在中国周边国家，开设军事基地，建立无效而耗费巨大的防守链，就像中国古代的长城，在真正对抗的时候却不起实际的功能。*

*中国的全球战略和对外政策，还是要以寻求和谐、避免对抗为主。* 在可能引起和西方强烈冲突的能源争夺上，中国应该一方面利用国际反西方势力，借力打力，不参与西方垄断的国际商品定价体系，而是以中国的特殊身份，在西方实力不逮的地区抢占资源，支持非西方的势力抬头，为中国的经济持续发展提供保障。中国在这些地方，比如非洲和南美，一定要改善自身企业与当地人民的利益分享比例，建立起一个互惠互利的经济关系，利用当地人民的势力来应付西方的夺利行为。
