# -*- org -*-

# Time-stamp: <2011-08-27 10:25:38 Saturday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 【第五篇·西北】



堂堂背我随余子，微许知音一叶桐。
--【清】王夫之

+ 四十一

除一般贸易以外，美国希望打击的是伊朗的汽油进口和原油出口。也许你会惊奇，伊朗虽然是原油生产国，但在美国数十年的经济制裁下，因为设备老化，缺乏部件，其本国的石油提炼能力已经不能满足国内的汽油需求，而要从国际市场每天买大约700万加仑汽油来消费，占伊朗消费总量的40%。本来这些汽油通常从欧洲进口，但由于美国的制裁，伊朗不得不转入亚洲市场，从新加坡入口，通过支付欧元现金而逃避美国的制裁。同时，伊朗支付了中国的中石化22亿欧元来将伊朗的两大炼油厂生产量提高三倍，并试图开发天然气液化技术来彻底解决燃油的进口问题。
 
图5.1 产油国伊朗因为炼油能力不足而依赖进口成品油而导致汽油危机

伊朗政府也试图提高汽油价格，但是在愤怒的年轻车主群体抗议之后，不得不作罢。由于伊朗和美国的对抗会是一场持久战，如何做到汽油的自给自足是保持国内稳定的一个重要因素。而美国的当前策略，就是如何使伊朗难以从亚洲进口汽油。

在美国犹太人的大力推动下，美国国会由纽约的民主党议员爱克曼和印第安纳的共和党议员彭斯提出在2007年的制裁伊朗法案中，增加条款，禁止世界任何国家向伊朗出售汽油，并惩罚任何在伊朗能源工业投资的国家。

很明显，在伊朗能源上投资的国家，首当其冲的是中国，尤其是中石化与伊朗合作的最新的石油和天然气合同，当时美国就暗示，可能会以中石化是在美上市公司为理由，对其制裁。而中国就暗示，会以中国公司退出美国股市来作为报复来打击美国已经摇摇欲坠的金融系统。

在伊朗的石油市场上，大的买家除了中国，就是日本。本来日本曾经非常配合美国的政策，从伊朗撤出了投资，但是发现美国许诺的从伊拉克提供的替代石油未能兑现，自己的能源来源遂陷入困境，于是便对美国的制裁不再热心。而且日本从伊朗买入的石油，全部用日元计价。而美国财政部之所以几乎没有对日本施加压力，可能也因为是日本不能不进口油，美国又没法兑现诺言，日本再不从伊朗进口，就会影响经济，没有其他选择。

印度同样对美国的制裁三心二意。本来印度计划从伊朗经过巴基斯坦铺设供应自己的油气管道，因为美国的反对而泡汤。加上在美国情报部门对伊朗的核计划作出不利于布什政府的评估后，中石化就立即和伊朗签订了液化天然气合同，这些都令印度人耿耿于怀，认为盲目跟着美国走，就是自取其辱。[fn:jdwtdgby0563]

[fn:jdwtdgby0563] 美国情报机构在2007年11月出版的《国家情报预测》（National Intelligence Estimate），彻底动摇了布什政府的伊朗政策。中石化即在一个星期后与伊朗签约。关于印度人的酸葡萄反应，可参考《亚洲时报》（Asia Times）2007年12月由前印度外交官巴达拉库玛（Bhadrakumar）发表的文章“中国把美国和印度抛在身后”（China leaves the US and India trailing）

当然美国的目的也许并不是彻底打垮伊朗的经济，而是要让伊朗人的日子艰苦，最后不得不接受美国苛刻的谈判条件，最好可以造成危机，让伊朗自己内部发生政策争吵，从而给予美国可乘之机进行颠覆。对待中国和伊朗的经贸关系，美国根本不敢用贸易战的威胁来要挟中国，一个可能性的方案就是告诉中国，如果因为中国的不配合，美国对伊朗的制裁不能达到目的，那美国剩下的选择就是不得不进行伊朗战争，而那可不是你中国想看到的局面吧！

另有一种化解中国与伊朗合作关系的方法，就是最近由美国《大西洋月刊》上卡泊林[fn:jdwtdgby0564]在他关于中国的新疆和西藏的一些见解中提出来的“交易”法。他认为新疆和西藏的情形和台湾不同，“牵涉中国人（卡帕林仅仅指汉族和他们看不出和汉族区别的西南少数民族）的民族感情”，所以美国在操作这些问题时，要比较小心，不能得罪了所有的中国人，而使中国成为美国的敌人。最好是和中国人面对面沟通，比如布什总统就不应该学那些欧洲的“小”国（大概指法国之流的不入流国家）去抵制奥运会，而是应该和中国人协商，在新疆和西藏问题上换取中国在世界其他地方（估计如伊朗，缅甸和苏丹等）支持美国的行动。

[fn:jdwtdgby0564] 卡泊林，Kaplan，此君正是2005年关于台海中美大战的放风者，通常代表美国国防部一些势力的观点

+ 四十二

美国在伊拉克艰辛的经营了5年，终于有机会在纸面上对伊拉克石油进行分赃。2008年年中，西方的五大石油公司，即美国的埃克森、雪佛龙、英国的BP、英荷的壳牌，加上法国的道达尔（也许这是为什么法国新总统萨科奇让人觉得比布什还布什的原因），终于和伊拉克政府签订了一个私相授予的开发合同。令人瞩目的是这一交易不遵循石油界通常进行的公开拍卖，价高者赢的惯例。伊拉克政府石油部的石油专家们——也就是来自于上述五巨头的洋顾问们，经过仔细反复评估得出结论：把合同给予这5家公司，对伊拉克政府和人民是最好的选择。[fn:jdwtdgby0565]

[fn:jdwtdgby0565] 后来局势的发展，表明这个伊拉克新政府，多少还有民族羞耻之心，有搞“拖字诀”的意图——作者补注

这个合同是在美国和伊拉克政府签订了28个永久使用权的军事基地以及美国出兵抢回石油输出港巴士拉之后，才签署成的。如果美国可以保证石油公司员工的安全和石油输出管道的畅通，那么就至少可以部分的解决日本的石油短缺问题，让日本在制裁伊朗问题上跟着美国走，使美国可以对伊朗施加更大的压力。当然，和当初发动战争的原定计划不同的是，美国的人民是无法追回这些年在伊拉克用兵的军费了，直接的收益者只能是这五大石油公司。唯一的变数就是伊朗支持的什叶派民兵（甚至由伊朗特种部队假扮的什叶派民兵）会不会容忍这个抢油合同计划得逞，这仍然是一个未知之数。

图5.2 伊拉克石油分赃图

这就令人不禁想问，伊朗一仗到底会不会在布什离任之前[fn:jdwtdgby0566]开打？笔者的估计是机率不大。其中最大的原因是，伊朗的核计划本来距离核武化尚有一段时间，而假若美国真的动手对伊朗进行空中打击，并不能完全将这个计划摧毁，如果反而引起伊朗无休无止的报复，尤其是在伊拉克通过什叶派反击或直接打击以色列，那都会令美国好不容易叼到嘴里的伊拉克石油肥肉又增加变数，想来想去既不必要也不划算。而且，美国的主要战略目的是占领伊朗，如果不能靠自己的地面部队，就得扶持亲美的伊朗政府，而这两个选择似乎在目前的情况下，都不太现实。不过，如果美国可以将战争的危机刺激到一触即发的地步，一个新上任的美国总统反倒可能可以用强势的谈判地位，和伊朗暂时消除敌意，来换取伊朗对美国在伊拉克的霸权的承认，不再会挑战美国在伊拉克的大肥肉利益，若能做到这一步，把颠覆伊朗推到将来伺机而动，也不失为一个好选择。

而且，美国在黎巴嫩和巴勒斯坦问题上也有和伊朗讨价还价的空间，只要把法国拉进分赃团队里，就保证了英法两国知道在哪边站队，那么国际上就不会再有在美国的中东政策上说三道四的声音。

那么伊朗肯不肯白白放弃百年不遇的崛起机会，把好不容易吃到口里的伊拉克再吐出来呢？这对伊朗也是一个考验。 *现在伊朗的对策是，一方面竭力争取加入上海合作组织，希望借俄国和中国的力量来应付美国和欧洲的压力，另一方面，希望能够有一个相似于欧盟的亚盟出现，能够让伊朗的未来完全与西方和欧美脱节，而成为亚洲经济的一个重要组成部分，通过与中国、日本和印度的经济联系来带动伊朗的经济起飞。*

两者结合，最佳的选择就是，伊朗能够与中国和俄国建立起一种实际意义上的军事同盟，为自己在研制出核武器之前提供安全保障，进而使伊朗成为亚洲经济圈的一个边界防守力量。其实伊朗在这方面一直很积极，而俄国也因为北约的步步紧逼而愿意合作，反倒是中国似乎不愿出头，觉得自己力量还是太弱，无法担负起保卫伊朗的责任。

从俄国的角度而言，如果欧洲可以从伊拉克、伊朗取油取气，当然会虚弱其对欧洲的能源武器的威胁砝码。如果能够至少令伊朗的能源全部流向东方而非欧洲，那这是一个力图通过垄断对欧能源供给以作砝码的俄罗斯求之不得的结果。虽然俄罗斯不可以公开出兵“保卫伊朗”，但是在提供先进武器给伊朗上面，俄罗斯也似乎比中国更有能力，也更有意愿。


+ 四十三

如果考虑到国际大势的变化，世界的经济，文化和政治中心向东亚漂移是一个不争的事实。而在这一大变局中，美国的超强角色自然会衰退，但是瘦死的骆驼比马大，美国的国土、人口和经济实力，还是比较可观， *如果美国能及时将其全球力量收缩，而不是再到处在全球扩张，那么它就不会象历史上所有的帝国一样，轰然倒塌。美国还会在一个多极的世界次序中扮演一个重要角色，而真正受到打击的反而是欧洲。*

在东亚为核心的新次序中，最为重要的是中国、日本和印度的经济、政治和外交关系。当这三个国家实现以中国和印度的独立自主的经济为基本，配合上日本在观念中的脱欧返亚（当然美国重兵驻境，有一定难度）时，欧洲的地位就会大幅降低，最后与崛起的阿拉伯、俄罗斯、巴西和南非处于同一层次。

这对西方在世界资源中享有的垄断是一个噩梦。所以如果能够在亚洲的未来三强中制造事端，以二桃杀三士，引出个火烧连环船，应该是上上之选的对策。

图5.3 具有挑战力的“亚洲三士”与能破坏离间三者的“二桃”

而这个“二桃”，从今天的情况来看，就是石油、天然气代表的能源，以及其他各种原材料。如果美国和北约可以控制住中东，解决伊朗，北上中亚，然后南下中北非，就可以控制住亚洲三强的命脉。至于中南美洲，通过浩瀚的太平洋施加影响恐怕还是一个梦想，只有在二十年后，也许集三强之力，才可以和美国领军的北约对抗。但是三强可不可以熬到那一天，出现那样的完美整合，还是互相之间未及达成共识就已经咬个你死我活，都是未定之数。

当然，从西方的角度来看这个问题，三强中除了中国之外，印度和日本不足为惧。日本在政治和军事上仍然是美国的殖民地，在经济上虽然是世界老二，但是日本人民的卖命工作，经常成为替美国和欧洲人民付账的提款机，比如第一次海湾战争中的大部分军费都由日本人支付，甚至出现了支付期间因为兑换率变化使原来答应的日元金额兑换成美元后缩水造成的前后差额也要补上的事情。日本人非常恼火，但都不得不忍气吞声。而当日本经济一旦过强，就遭到了美国和欧洲的口诛笔伐，责令悔改，一直到日本陷入经济衰退为止。日本作为一个岛国，市场在外，资源在外，能源在外，一切命脉取决于美国人的脸色，从美国的角度来讲，日本颇象英国的地位，以日本来平衡亚洲大陆的中国就是学以英国来平衡欧洲大陆的法德联盟。只不过唯一的区别是，英国是美国的堂弟，日本只是美国的马仔。

在南亚的印度，则是另外一个不同的情况。印度邯郸学步，继承了英国人替他们建立的无法运作的民主体系，过去几十年一直无法有效的解决国家的发展问题和周边的安全环境问题。凭着一批绝顶聪明的印度软件工程师，以及印度人民作为数学发源地的底蕴，印度终于在全球化的今天可以在外包业中异军突起，在电脑和医药等行业上可以有所建树。但是印度的体制造成其官僚体系腐败，效率低下，利益集团在频繁的选举中不断侵蚀公共利益。在周边关系上，还是未能完全处理与巴基斯坦、孟加拉国和斯里兰卡的紧张关系，而且印度的战略界和军界，仍然为1962年的中印战争的失败而耿耿于怀，非常容易陷入美国和西方国家利用印度抗衡中国的挑拨离间。印度有限的海军力量却因为美国在印度洋区域的薄弱而在本地独占鳌头。也许，美国在巴基斯坦的介入还不是太顺手，在缅甸的颜色革命也不成功，在斯里兰卡通过上次南亚海啸的渗透也没有结果，这些超级大国的失手让印度可以暂时心安，但中国的任何举动，哪怕是商业的动作都能让印度精神过敏。[fn:jdwtdgby0567]

[fn:jdwtdgby0567] 美国战略界认为，由于周边布满中东、中亚、非洲、澳洲等重要地区，印度洋将是21世纪的主要争夺之地，美国、中国和印度必然在这里展开海权之争。鉴于美国国势衰落，无法在这里占统治地位，因此如何平衡和调解中国和印度之争，将是美国外交的一大重要问题。


+ 四十四

在西方的商业词汇里有两个新词，都和中国有关。一个是中印区（Chindia），另一个是中中区（Chime）。[fn:jdwtdgby0568]

[fn:jdwtdgby0568] Chindia，系中国China和印度India两词综合而成。Chime，系中国China和中东Middle East（ME）取各自词部简写连接而成。后来，在美国危机深化时期，又有美国人希望强调G2和所谓中美利益共同体，发明了Chinamerica一词。但如果说中印区和中中区概念意味着对于国际政治经济秩序的革新，那么中美区却意味着对过去国际政治经济秩序的一种挽救和维持。——编者注。

中印区指中国和印度的经济联系和一体化，这将为世界创造出一个巨大的市场。而在历史上，中国和印度这两个国家，从来都是在世界经济上排名第一和第二，只是在近代才开始衰落。持这种意见的人，在印度不占少数，他们主张利用中国和印度在人力资源上的长处，比如中国和印度高科技人才在世界上的二分天下的地位，结合中国和印度裔移民在世界各地的经济和商业地位，一方面同欧洲和北美竞争，另一方面甚至可以用这个巨大的中印经济体，带动整个发展中国家集团，如南非和巴西等国的经济起飞。

中中区则指中国和中东的经济联系和一体化，以中东穆斯林国家的能源优势结合中国的制造业优势实现经济合作，中国在政治、外交和军事上对中东国家进行支持，而中东国家在金融和投资上参与中国市场发展，使亚洲可以从太平洋海岸到地中海岸建立起一个富裕和稳定的市场。

对这个远景，西方学术界有不同的解读。以美国和西方霸权为核心价值的地缘战略派，如美国国防部和欧洲各国的国防部，各大西方军火生产商，和各大能源公司，对这个局面是非常恐惧。加上宗教和文化冲突论者，如哈佛大学的塞缪尔·亨廷顿之流，因为散布儒家文化和伊斯兰文化合力对抗西方基督教文化的威胁，也对这种中国和中东的合作充满疑虑。而西方的另一些强调各文化和谐的人士，却欢迎这个局面出现。他们的观点是，由于西方本身无能力解决中东对西方的仇视和恐怖活动，如果中国的经济发展可以为中东创造出一个富裕和安乐的中产社会，也许反而能为彻底解决中东人民对西方的恐怖袭击问题另辟蹊径。

这两个概念听起来很动听，而且实际操作上也可行，但不是没有弱点。

在中中区，有三个方面可以打击阻止其成型：一是北约和美国在阿富汗的军事行动升级，让更多的美军、英军、法军和德军加入战地，可以把战火烧到巴基斯坦，通过巴北部的军事行动和南部的俾路支独立运动，切断这条新的丝绸之路；二是西方增加在中东的军事基地，比如法国最近在阿联酋新签下的阿布扎比海军基地；第三个就是支持针对中国新疆的疆独运动，搞乱中国的边疆，并在中国和穆斯林世界中打下钉子。

在中印区，虽然中国和印度的领土争端没有任何导致冲突的迹象，但西方用对西藏独立运动的炒作，通过由西方人直接控制西藏流亡组织的方法，倡导暴力和恐怖活动，有可能使中国和印度的分歧增大，而出现火烧中国和印度这两艘连环船的局面。


图5.4 中印区(Chindia)和中中区(Chime)示意图及其各自的危险

至少在印度，已经有人看到了这个危险。在美国国会议长佩洛西在拉萨骚乱后，去达兰萨拉为藏独打气，印度的评论家就指出，当两个大象打架的时候，大象脚下的那块草地就会遭殃。中国和美国就是他们眼中的大象，而印度就是其笔下的草地。很值得寻味的是，美国已经开始有媒体炒作印度的阿萨姆邦（在与中国存在领土争议的藏东南的南边）的武装独立运动，一旦在印度的藏独分子开始实施针对中国的恐怖暴力活动，就会在中国产生出你做初一，我做十五的可能报复心理，从而把两国拉入更多的冲突之中。


+ 四十五

那么中国的新疆和西藏政策应该做出什么样的调整，来应对这个新的挑战呢？

通常在施行这些政策时，必须考虑到软硬两手。硬的一手打击在西藏和新疆的分离主义势力，软的一手努力提高少数民族的生活水平，团结一切可以团结的力量。这样的政策才可以既使所有赞成国家民族政策的人士可以得到实际的好处，又使形形色色反对国家统一和企图破坏民族安定的分裂分子受到打击。

笔者个人的感觉是国家在新疆等西北地区，还有让少数民族同胞获得更大经济利益的政策空间；而在西藏，目前似乎有点过于看重单一的经济扶持和补助，对于一小撮为了享受了既得利益又四处惹麻烦的分裂分子显得有些过于大度。相对于西藏，国家在新疆的投资资金似乎有提高的必要，在投资的项目中，也应该有所调整。除了技术密集型的石油，化工和能源工业外，还应该大力发展劳动密集型的轻工业和民生项目，为大量维吾尔族和其他少数民族的农业剩余人口提供脱贫和就业的机会。

中国在解决新疆的问题上应该比西藏更容易，因为疆独的恐怖主义活动在国内和国外都没有多大的市场，而中国在上海合作组织又得到周边国家的支持，巴基斯坦与中国有极友好的关系，这些都使疆独势力无法建立起成规模的基地。再加上疆独势力缺乏整合，也没有有声望的领袖人物，这都影响了其行动的能量。美国已经试图在这方面下功夫，包括去年布什接见热比娅，欧洲企图提名她为诺贝尔和平奖，想把她捧成领袖，都可以看作加大干扰中国稳定的一个前奏。

而现在美国国会的运作，企图将美军在阿富汗战争中与基地组织和塔利班作战时俘获的17名东突组织的恐怖分子，从古巴的美军关塔纳摩监狱中释放出来，也是考虑到疆独组织势力太弱，需要把这些曾参加了车臣对俄军的苦战，甚至让美军吃过苦头的战士，放出来咬中国人。当然，这在某种程度上也是背书了中国政府在反恐上的成绩可观，使美国不得不用这种方法来补充疆独力量。

对美国的这个行动，中国必须有足够的警惕。这些恐怖分子不排除将手持美国或其他的西方国家的护照，潜入巴基斯坦、阿富汗或者其他中亚国家，操作针对中国的恐怖活动。中国的反恐人员应该在这些地区进行布置，争取在第一时间就将这些恐怖分子清除掉。

中国政府还需要对民族政策进行调整，不能仅仅依靠民族自治，还需要倡导民族融合，鼓励和提倡汉族人民学习少数民族语言，风俗和文化，把保护和发扬民族文化作为各族人民的共同责任。在学校教育中，不光要鼓励少数民族学生以民考汉的方式提高其汉语水平，还要提供优惠激励，为汉族学生提供汉考民的机会，使在将来可以做到真正的双语和多语的机会，使各民族群众在生活和工作中可以任意使用多种语言而没有交流和理解上的问题。这样在民族融合的基础上，才可能真正的施行民族自治。

从这个角度来看，现在在各民族自治区尤其是新疆和西藏的从小学到高考以及高等教育的模式似乎需要作出调整。从这个角度来看，现在在各民族自治区尤其是新疆和西藏的从小学到高考以及高等教育的模式似乎需要作出调整。目前的情况，在基础教育和高中教育上，形成了“好学校”和“差学校”之分，而大批当地民族学校，由于人才缺乏，沦落为所谓的“差学校”。长此以往，恶性循环，只能是造成在孩子心中就埋下对立的情绪种子。而在好学校中，民族语言课程又成为走形式的装饰性课程，其结果是好学校仅仅成为汉族子弟返回内地大城市，和一批优异少数民族子弟考取内地民族大学、学院的跳板。而在内地民族学院中，又出现一些少数民族优秀学生，由于内地与外界特别是国外交流频繁，受到渗透进内地的国外分裂势力蛊惑，去“反思自己的民族境况”，反过来倒变成一些分裂势力的积极骨干的情况。

笔者认为应当强化对这些地区的师资投放，建立大批的民族教师拔高班，建立直接管辖，基本覆盖少数民族和汉族人口的基础教育系统，让汉族和少数民族全面插班混合上课，鼓励同学的日常交往，鼓励孩子从小使用各种语言混杂交谈，鼓励在这些地区的汉族中的少数民族语言普及，配合以物质奖励。并对高考体制进行改革，大力建设当地的大学，淡化那种刻意去强调民族划界的色彩的教学体制。


+ 四十六

在民族教育上，中国政府不光要推动基础教育，而且还要大幅度的依赖国内的非政府组织，普及职业学校，通过和各种国有企业和私营企业合作的方式，为少数民族的农村劳动力提供适当的技术培训，使少数民族在技术工种就业上的比重增高。另外在支持中小企业方面，对多民族的合作企业提供优惠贷款，争取在少数民族中形成一股维护社会稳定的比较富裕的中产阶层。

另外一个需要思考的问题是少数民族的宗教问题。新疆的宗教阶层，基本上对政府政策持拥护政策，这和西藏的情况有本质的不同。由于新疆的各少数民族都是全民信教的民族，宗教人士在社会中的地位尊贵，而且对群众的影响力在很多情况下比政府还要大。如果宗教阶层在社会中享有其应得的地位，就会成为社会的稳定力量。反之，如果宗教人士觉得在现代社会中有被边缘化和被冷落的感觉，就会变成对社会稳定的不良因素。

这里就牵涉到笔者本人关于中国的一点未来设想。笔者比较反对西方的多党政治，而喜欢中国传统的无党政治。其实，笔者认为，一种“儒家社会主义”的模式，似乎有参考的价值。“只有社会主义才能救中国”，这句话是对的，因为以中国的人口和资源的极不平均，盎格鲁萨克森式的资本主义，会造成贫富差距过大的局面，最终造成阶级的对抗引发国家的崩溃。看看香港，九龙的半岛酒店和重庆大厦一墙之隔，天上地下恍如两个世界。所以，在中国这样的国家，每产生一个类似香港的那种无良地产大亨或玩弄股票的股市大鳄或大股东，就会导致几万家庭无屋可住，无饭可吃。而西方多党政治所玩弄的游戏，其实就是以金钱为后盾的游戏，那么必然让话语权为各个经济利益的强势集团缩垄断。这种强势集团垄断舞台来瓜分国家利益，不光会导致恶质政治，造成中国的实际地方割据，还会如历史上一样导致下层人民赤贫化。

如果中国不想向西方式的多党政治发展，而是考虑笔者所说的“儒家社会主义”框架，那么就需要一个凌驾于社会各集团之上的，一个有责任心的真正名副其实的精英阶层，来代表全社会各族和各界人民的利益，使各种利益之间的协商都可以在该框架下达成妥协。如果这一点能够做到，那么中国就不会如西方社会一样，在选举中浪费大量的社会资源，搞到最终还是为各自的一党之利互相争夺，玩零和游戏。在这个问题上，我们要的不是搞各个利益集团代表的西方式政党的轮流执政，而是有中国文化特色的全体人民的共同执政。不过，从目前中国的现实情况来看，要达到这一点，还有非常多的工作需要做。特别是在构建地方政府的利益激励机制、指标引导和人才选拔体系上，要加以反思。

这样就要求以各种形式，吸收各阶层的力量，让工人阶级、农民阶级、科技人员和管理人员都有真正的代表。而对社会稳定和发展具有重要作用的宗教力量，尤其是少数民族宗教力量，理所应当的也应当通过各种灵活的形式，包括在内。

而在中国政治现实中，已经有在全国人大和政协中重用宗教人士的先例。所以，在现在的基础上，建立一些更紧密的工作关系、合作关系，并不是一件难事。当然，笔者这种思路，对于任何一个在社会上有影响力的势力（绝不仅仅限于经济影响，还包括社会影响，文化影响）都是适用的，都应该被包容进现有的体系中来，这种涵纳包容的能力本来就是中国传统政治实践的一个宝贵遗产。


+ 四十七

在中国今天的快速经济发展中，人民不再受过去的户口制度的束缚，可以因为投资和工作的原因在全国流动。如果中国政府不能做出一个比较合理的地区性的产业分工，就会造成很多的社会问题。比如中国以出口为目标的劳动密集型工业，多集中在沿海的东南部和南部，虽然解决了中部和西部的部分省份的农村劳动力就业问题，但就造成了铁路春运的大问题，出现了类似2008年初的大风雪的恶劣天气而导致交通瘫痪那样的风险。而且这种消化劳动力的方法，对汉语语言能力相对较弱的少数民族，如维吾尔族、藏族、苗族等等，都起不了太大的帮助。而中国政府在西部的部分地区的投资，又会将中部的大量劳动力吸收入新疆和西藏，导致与当地人造成职业上的争夺。再加上各民族的语言、风俗和文化上的区别，更容易产生误解而增加矛盾，从而造成社会的不稳定局面。

笔者的看法是，不应该把中国看成一个单一的，传统意义上的国家而进行全国一盘棋的规划，而应该利用中华民族长期以来政治统一、但经济独立、且文化多元的特性，利用中国区域经济的特殊情况，对中国的主要地区在工业分布，就业机会创造上，进行一个中长期的规划安排。

目前看来，中国已经基本上抢占了世界的低档消费品市场，靠在土地、能源、原材料和人力越来越昂贵的沿海地区，继续靠廉价商品去开拓国际市场，在今天北美和欧洲逐渐陷入衰退的短中期展望上，几乎不具备可持续性。而依靠大力开拓东南亚、中亚、南亚、西亚、中南美和非洲的市场，也只是权宜之计。中国的下一步发展方向是增加内需，在持续的基本建设上，再增加内部的消费。而中国经济发展能否成功，就要看中国的低档品制造业是否可以转移到成本相对便宜的中西部，沿海地区是否能发展出中高档消费品来满足中国自己的市场。

如果以中国的东部大都市为中心，我们可以大致的划分出这样几个都市圈：

一是以北京为中心，包括天津、大连和青岛在内的环渤海圈；二是以上海为中心，包括南京、无锡、苏州、杭州和宁波在内的大长江三角洲；三是以香港为中心，包括澳门、深圳、广州在内的珠江三角洲。这三个地区应该是中国在世界上与其他国家竞争的本钱所在。这些地区要做到两个方向的转变：

一是发展高附加值，高资金积累型的新型工业。利用在科研和教育上的优势，发展新型的能源技术、材料技术、生化技术、纳米技术、电脑和人工智能等等朝阳工业，并以北京、上海和香港为地区中心，发展出影响亚洲的金融贸易文化中心。

二是发展以占据中国未来中高档消费市场为主的消费品牌工业。以中国文化的五千年底蕴，中国从来都是世界高档消费品潮流的领导者和生产者，以中国人在吃喝玩乐上的高尚品味，应该能够创造出引领世界消费市场的衣食住行文化。在中期内，尽量以满足中国的内需为主，防止这个丰富的市场被欧洲，尤其是法国的垃圾品牌如LV、Gucci、Channel等抢占。值得庆幸的是，中国新一代消费阶层是以80后为主导，因此缺乏上一代人无可救药的盲目崇拜欧美风尚的习惯，再加上这次由西藏骚乱引发的对法国文化以及欧洲文化的反感，都是中国这个工业发展的助力。


+ 四十八

在具体操作上，可以由中央政府牵头，但是具体的事务应该由地方的各级政府协调，讨论如何在税收和财政上给予支持。而中国的文化和娱乐界则在这个建立自己文化风尚上需要扮演重要的角色。

从中华文明的亚文化体系来看，北方的汉满蒙朝鲜亚文化圈，可以建立以大连为窗口的时尚中心，发展出自己系列的文化产品。例如以满文化为基础的旗袍，可以在吴越文化的上海的变更改进下，产生出影响全球的服装潮流。如果以北京的雅文化和艺术家的创意，建立起以文化为核心的高档消费品系列，不光可以涵盖中国的北方，还可以辐射外蒙、俄国远东的滨海地区、朝鲜、韩国和日本。

东南的吴越徽闽亚文化圈，本身已经有很多精品，例如徽州的文房四宝的书法文化，宜兴的紫砂壶和闽浙徽的精品茶叶的茶文化，苏州的园林和盆景的园艺文化等等，都可以通过上海这个中心而集其大成，发展出清雅细致的服装、饰品、家居用品等等系列。

而南方的岭南文化，本来香港已经具有世界一流的研发、生产、包装和行销的水平。唯一可惜的是香港由于雅文化的缺乏，结果英国式的狗仔队窥探私人隐私的庸俗市民街井文化横行。这就造成部分南粤人民如珠三角地区的一些居民，形成一种自卑心态（颇似韩国文化界），以自己的文化为耻，反去盲目崇拜欧洲和日本。如果能够解决这个问题，通过政府大力支持艺术家和本土文化，香港就非常有可能成为东方的一个时尚中心。

从这次与西方媒体对抗中，产生出来的民族消费主义，可以在发展中国自身的中高档消费品产业中起很大的助力。其实利用民间的力量保护自身的工业，在欧洲和美国从来都是家常便饭，中国人需要好好学习而加以利用。美国这些年来民间不断有社会团体，企业和地方政府发起抵制中国产品的风潮，而欧盟不断的单方面破坏中欧之间的贸易协定，对中国产品设置各种各样的配额、关税或非关税壁垒。中国的消费者也应该形成一些影响团体，以非政府的形式出面，对危害中国自身发展的欧洲高档消费品进行阻击，借这些人在损害中国人民感情上的行为，如巴黎市政府对达赖喇嘛的表彰，英国的大学对藏独的支持，某些登山户外运动服装品牌对藏独人士的钟爱等等，发起不同规模的抵制行动来针对这些地方的商业品牌。而且，中国要趁机大力支持中国的消费产品企业搞出自己的替代品牌抢占自己的国内市场，而不是放任有好资质的企业去炒股赚快钱，对于一些地方政府公然把本地重要商业地段划为只允许国外品牌入住的“高端商业‘租界’”的做法，要进行查处和惩罚。这些行动，需要长期的跟进，而不是三分钟的热气。笔者建议中国自己的企业家应该看到这个机会，向西方国家，甚至日本和韩国学习，捐一些资金给这些非政府、非赢利的中国消费者组织，以便长期的配合跟进。笔者希望大家明白，今天的国家之间，除了合作，更多的是争斗。商场如战场，如何减少内斗，一致对外，是企业界需要好好思考的问题。

除了上面提到的三个重要城市圈的转型之外，我们可以还可以看到以武汉为中心，涵盖鄂湘赣的楚文化区；以西安为中心，涵盖陕晋豫的中原文化区；以重庆为中心，连成都，拉萨的巴蜀羌藏亚文化区；以昆明为中心，包括滇黔桂的壮苗缅傣亚文化区；以银川和西宁为双核心的融合中东阿拉伯、波斯文化和汉文化的伊斯兰亚文化区；再加上以乌鲁木齐为中心的伊斯兰突厥亚文化区。


+ 四十九

在这些地区里，如何创造出足够的劳动密集型产业，而解决中国庞大的就业和农业人口向城镇人口转移的问题，是中国政府面临的最严峻的挑战。在将来的10-15年间，中国必须从农村转移出3亿人口，使中国成为城市人口约占70-80%的小康社会。乡村人口从目前的7亿水平，降低到4亿水平，城市人口从目前的6亿水平增加到9亿水平。

如果我们以区域经济的角度来看这个问题，就会得出一个粗略的发展远景。发展大中型城市群，建立500万到1000万人口的城市，是无法避免的，但是必须防止出现巴西的里约热内卢、印度的孟买和美国的纽约之类的贫民区。在人口分布上，中国的地质和环境基本上合理，但是由于客观地理资源条件的限制，西部的人口数目虽然少，但人口压力却很大，反倒是东部和中部的一些省份有移民的空间。

从东部沿海转移出来的劳动密集型工业似乎应该考虑到三个区域。第一就是中国人口压力最大的河南地区。那里和山东西部和南部的内陆部分，安徽的北部和江苏的北部，以及陕西和山西，是中国北方人口的主要集中地。在这个地区建立劳动密集型产业，可以利用郑州和徐州的交通枢纽，连带附近省份，通过连云港作为出口港。这里的优势在于劳动力比较便宜，而相对于珠江三角洲和长江三角洲，又比较靠近中国的能源基地山西、内蒙和新疆。在节能和环境保护兼顾的情况下，这里应该可以作为中国低价消费品的主要生产地。

第二个考虑的地方是湖北、湖南和江西地区，其人口也在1.8亿上下。这里虽然南北有京广铁路线和京珠高速公路，东西有长江，但目前该地的劳动密集型产业，只是成为珠江三角洲的辐射方式，不能成为带动地区发展的龙头产业。似乎应当利用武汉的科研水平，发展新型节能汽车、精密仪器、机械设备、微电子、激光等等制造业，逐步升级，会是个不错的选择。

第三个区域就是成都和重庆，需要大量的工作机会，带动附近地区的就业市场。这里建立的消费品生产地，可以供应西南的云南，贵州和广西，还为这些区域和东南亚的越南、老挝、柬埔寨、泰国和缅甸区域经济一体化提供支持，还可以通过未来建设的滇缅通道，提供产品到南亚的孟加拉国、斯里兰卡和印度的东部。

由于中国西部的环境条件不适合人口居住，尤其是西北的沙漠化和干旱都限制了产业的发展。所以中国的西部政策必须是以输入面向本地人的工作机会为主，而不是招引外来劳动力和当地的少数民族竞争。在新疆，如何建立以喀什、和田和阿克苏为主体，面向巴基斯坦和阿富汗的商品基地，如何建立伊宁、塔城为主体，面向哈萨克斯坦和其他中亚国家的商品基地是关键。中国在这里的政策要做好以下两点，一是加强对少数民族的职业培训，避免形成汉族教育水平高而享受高收入工作机会，少数民族教育水平低而只能得到低工资收入的局面。要提高优惠计划，培养出少数民族的技术工人阶层，使他们在职业市场上能有一个公平的竞争起点。二是通过惩罚和诱导多种方法组合，杜绝私人企业中招聘的歧视现象。目前，在中国的不少地方，不乏外省民工相比本地工人在职业市场被某些私人企业主歧视的问题。这个歧视性对待，如果表现在民族之间，那么在少数民族省区就会比较容易成为国外敌对势力做文章的主要工具。


+ 五十

在中国西北的另外一个区域，即甘肃，青海和宁夏，则应该有两方面的考虑。一是发展成为中国的军工基地和航天工业基地，二是为西藏以及尼泊尔、不丹等地提供旅游制品等消费用品。如何在这一区域创造出足够的就业机会，而防止出现各族人民相互争夺，是一个很急迫的问题。

人们也许会认为新疆和西藏的分裂主义势力是中国稳定的大患，但事实是这些势力，尤其是海外支持的势力，在国内普通百姓包括少数民族百姓中，并没有广泛的群众基础。而真正令中国政府不能掉以轻心的，是其他西北省区存在的一定程度的民族摩擦，即藏族和其他当地少数民族如回族之间的关系。笔者认为，如果掉以轻心，不及时加以疏导，带来的负面影响可能会比简单的分裂势力问题更厉害。

本来藏族的藏传佛教从印度传入时，正是起源于中东的宗教势力东扩南下，对印度本土宗教如佛教、印度教势力带来巨大打击之际。看一看今天印度国内超过1亿5000万的穆斯林，以及巴基斯坦和孟加拉国多达3亿以上的穆斯林人口，可以想象当年对古印度的冲击规模。所以当时的印度本地宗教对于西北的外来宗教的对立情绪是可想而知，而藏传佛教的理想——香巴拉王国（Shambala）传说，也是关于佛教获得宗教复兴后的极乐世界。过了不久，信奉伊斯兰教的一些民族，跟随成吉思汗的蒙古大军南侵，在西北地域的南部定居下来。由于当时蒙古族接受了藏传佛教，所以在蒙古族的统治下，藏族和藏蒙外其他民族的关系，可以通过蒙古族的仲裁而获得相对的平稳。在元朝灭亡后，另外的蒙古部落，如来自天山南麓吐鲁番的和硕部，仍然控制青海、甘肃一带，把握着局势，其间通过支持五世达赖喇嘛剿灭西藏的其他藏传佛教派别后，建立了黄教（格鲁派）的法权和蒙古族的政权。这种由异族仲裁维持平衡的模式一直到清朝，只不过是满族替代了蒙古族的统治地位。但是在1911年辛亥革命之后，清朝灭亡，西北的控制权就落入当地少数民族军事力量马家军的手里。而马家军的领导人马步芳对藏族的统治比较严厉，除了沉重的苛捐杂税外，还包括宗教改宗。当时的甘南藏族头人，通过层层贿赂国民政府官员，终于有机会觐见蒋介石，要求把藏族地区从青海划归甘肃，以从行政上逃脱马家军的统治。

可以想象的是，传统上被藏族视为“汉藏一家”的共产党军队开进西北时藏族的欢迎程度。当时有一个藏族部落赶着牛羊要去首府交税，见到了绵延不绝的解放军部队，当被告之是汉族为主的军队时，年轻人全部欢呼雀跃，要求协助解放军的队伍，而部落头人当场决定要把税交给解放军。年老的部落长老则比较谨慎，询问解放军可否向他们展示一下实力——在他们眼里的所谓实力，就是要有1000骑兵才值得放心。当时的解放军指挥员让数万骑兵列阵经过，这些长老便消除了疑虑，衷心拥护。[fn:jdwtdgby0569]

[fn:jdwtdgby0569] 见解放军第一野战军西北战史资料。

当然，对当时的藏族头人来讲，解放军关于民族团结的主张令他们有些不解，因为他们记得当年曾有汉人的军队在西北被当时的少数民族军阀部队杀得很惨，现在却不按传统的思维进行报复。经过了多年的努力，不断的教育、疏通、诱导，共产党终于让这些少数民族之间丢弃结怨，和平共处，而且修好了藏族内部不同游牧民族部落间的世代冲突。

但随着中国经济的改革和开放，社会的流动性增大，再加上一些别有用心人士的不断传谣，藏族和其他少数民族之间，以藏族挑起的冲突有增长的趋势。如果不好处理这个问题，那么共产党在五十年代所作出的实现民族和解的努力就会付诸东流。



#+begin_center
【写作日期】2008年6月29日——7月4日            
#+end_center























*** 【第六篇·对策】


何当踏破双芒屐，却向昆仑望故乡。
--【近代】王国维

五十一


其实种族问题，在世界任何一个多民族国家都是一个敏感问题。最近在美国的南部各州，就发生了中学里非洲裔学生和拉美裔70学生的大规模打斗事件。这两个种族的冲突，主要原因是两族青年人的教育水平都比白人和亚裔要低，所以在低工资、低技能、非专业的职位上进行竞争，而这种工作因为美国工作机会向海外流失，反而机会较少，竞争激烈。再加上作为少数族裔的拉丁裔，也加入了享受政府名额有限的少数族裔优先计划的行列，在本来黑人垄断的福利大饼中，虎口夺食。这样，面对近十几年快速增长的拉丁裔人口，非洲裔黑人不得不忧虑。

另外一个种族冲突就是发生在黑人社区，曾经有犹太人去黑人区开商店，赚了黑人的钱后，就到富人区买房买地，完全对黑人社区的发展没有反馈促进贡献。而当犹太人赚够钱撤出后，韩国移民又故计重施，从而引发了在洛杉矶的黑人针对韩国裔的冲突事件。

其实中国的各种族间要和谐得多，比如在多民族区的云南，广西和贵州等地，很少听到这类民族冲突事件。而在青海和甘肃发生的藏族和回族等其他少数民族之间的不合，也不是很难解决。这个问题本身出现的原因，在于中国开放改革后，从严格限制的计划经济转为自由发挥的市场经济，在这新环境下，藏族这种传统从事农牧业，社会讲求等级次序的民族，就会不太适应，产生某种失落感。而遗传基因里充满了商业细胞的回族、撒拉族等少数民族等，简直就是如鱼得水。所以很快就会在几个民族群体之间的生活水平上出现差距。再加上一些少数民族和汉族的商业活动，像犹太人和韩国人那样，走进了藏民聚集区，但又社群活动相对封闭，这就使这种冲突性情绪逐渐蔓延。如果地方政府在这方面处理不好，就会有部分与国外配合的“有心”的知识精英或者宗教人士在其中操作，通过对藏民中知识文化水平低的农牧民，散布量身定做，精心编造的谣言，就可能带来很多原本没有预料的后果。

要解决这个问题，中国政府必须明白，靠市场经济的力量和自由竞争来提高人民生活水平的办法，并不完全适合中国所有的56个民族。其中一些少数民族缺乏足够的训练和教育，在职业竞争市场上本来就没有一个公平的起点。而且很多少数民族在基本的现代工商业的工作要求上，比如说定时的工作时间、按照工作成绩而定的奖金制度、从事服务业工作要“顾客至上”的商业道德等等，都不太习惯。比如说，藏族通常待人单纯友善，但当一个顾客七挑八挑，要求商店这样那样服侍自己的时候，有的藏民商人就会觉得自尊受到了影响。所以不能完全把中国东部理所当然的企业制度、商业文化，采取一种高高在上的态度强行安到少数民族地区，似乎要把“落后”的藏族逼进现代化的好日子。如果我们反感西方人那种不可一世高高在上，用人权、自由和民主来教训我们的态度，而对他们竖中指，那么我们就应该将心比心，站在藏族和其他少数民族的角度上，认真的听取他们的意见，和他们一起合作解决面对的问题。比如说，可不可以在藏区新开设的服务业上尽量避免采取汉族或其它少数民族独资的方式，可采取尽可能让多民族以多种模式共同入股（如以劳资关系员工持股，社会关系共同合伙入股等等方式）的合股企业形式。政府可以做的就是为这些多民族企业提供贷款上的优惠，并在就业上以雇佣当地藏民为主。如果当地缺乏足够的合适人选，就应该成立有针对性的职业训练计划，为藏民定做一些有针对性的就业培训，使他们能够享受到经济发展带来的益处，从而和其他民族的致富速度比较接近，这样就不会让他们有经济地位相对降低的感觉。


五十二

多民族合作企业的方式，马来西亚是一个到目前为止相对成功的范例。本来，马来西亚的华裔，人数虽少，但却掌握了马来西亚大部分的经济命脉，因此和马来族裔的关系一向紧张，在社会不安定时，经常成为马来裔贫苦平民暴乱的主要攻击对象。后来马来西亚政府实行了华裔向马来裔让利的计划，即将华裔企业中分出少量股份，比如5%-10%的比例，让给马来裔人。当初，华裔对这个政策很反感，认为自己辛勤工作，却不得不免费去养一些好吃懒做的马来裔。但是他们很快发现那些能够拿到让利的马来人，都不是等闲之辈，而是马来裔社区里宗教和民意的领袖人物。这些人当年在清真寺里的几句话，或者在当地报纸上的几行字，就可以引发马来平民的大规模骚动。但当这些精英人物成了华裔商业的生意伙伴后，不光不再挑动骚乱，而且还经常出来平息可能发生的种族冲突。更重要的是，通过了不同民族的合作，大家开始利用不同方面的能力，齐心合力，进而推动了整个社区的发展。当然，近来，马来西亚因为本身是小国，不得不在国际经济浪潮中沉浮，尽管有强人马哈蒂尔勉力引导航船，但是由于在国际经济竞争中，不再是80年代那样的世界明星，所以过去形成的安定局面，近几年来有所动摇，但马来西亚起码能够在民族关系动荡不安的东南亚保持较为超然的状态，其中的经验，仍然值得中国加以参考。

所以，对走进藏区或长期乃至世代已经定居在当地做生意的少数民族，甚至汉族，应该明白，如果他们能在自己赚钱的同时也让当地的藏族分利，其实对自己生意的长期发展更有利。而享受这些分利，参与合作的藏族，必须是支持国家政策，拥护民族团结并在社区的民众中有影响的宗教和世俗人士。支持国家统一、民族团结和提高人民生活的民族人士，理所当然要享受经济发展的好处，而鼓吹分裂、民族冲突和扰乱社会次序的人士，就必须在各方面受到打击，这个政策决不能因为国外一些敌对势力的大声喧哗而有所改变。笔者认为中国政府没有必要对西方国家的杂音太过关注而投鼠忌器，结果反而鼓舞了国内的一些分裂分子的气焰，得寸进尺，得陇望蜀。

如果解决不好青海、甘肃和西藏本地藏族和其他少数民族之间因为某些商业误会而引发的矛盾，后果会相当严重。一方面，海外藏独势力可以将藏族经济生活提高慢于其他民族的情况，归罪于中国政府，并攻击中国当前的民族自治制度，借机鼓吹说什么如果藏人真正“当家作主”，比如说独立，就能真正的“保护藏人利益”。另一方面，会把主动权送给某些头脑比较冲动的宗教界人士，而他们在群众自发议论中发表“权威意见”的时候，往往用不可调和的宗教情结来代替容易妥协的具体经济诉求，结果使情况容易失控。比如在藏区流行的一些流言，从外地人看来非常荒唐。但是对青海和甘肃的藏族，曾有过当年军阀逼迫自己改变信仰的历史经历，又有信仰中传说的中亚伊斯兰教新兴力量在印度和中亚横扫佛教势力的痛苦记忆，就很容易相信。这样就把众少数民族之间本来容易解决的经济问题变成了你死我活的信仰问题。

    随着中东在油价高涨而造成钱包鼓胀，阿拉伯国家，尤其是沙特阿拉伯对中国的投资会越来越多。而与阿拉伯人在文化、宗教和血缘上都有紧密联系的西北不少少数民族，靠娴熟的阿拉伯语，将会成为他们的经济伙伴和雇员。当年被解放军打败的军阀马步芳就是率整个家族流亡沙特阿拉伯，并最后入籍老死在客乡的（当然，沙特也可以说是宗教意义上的“真正家乡”）。可以想象，如果这些少数民族中的知识文化精英，看到海外的藏独势力背后是印度和西方的大力支持，在国外中东冲突局势升级的情况下，他们的一些亲阿拉伯文化精英就会相应号召针对西方和印度来开拓另一场圣战。而藏族对阿富汗的塔利班摧毁巴米扬大佛的行为已经非常气愤，而看到美军打击塔利班则感到很过瘾。这些问题落到了国际颠覆专家的手里，加以运作，又是一个火烧连环船，搞乱中国的契机。


五十三

西藏和其他藏区的问题，有一些是由人口增长带来的。在过去的农奴制下，大部分的藏民必须承担领主和高级僧侣的奢侈生活，导致自身的消费物资非常缺乏，再加上工作条件恶劣，医疗卫生落后，藏族的婴儿出生死亡率高，藏族平均寿命大约35岁。而在共产党执政后，在国内的领主被改造成自食其力的人，许多僧侣还了俗，达赖喇嘛和他的一批领主和活佛们，逃到了印度，吃上了美国政府的供养，这些都使藏族农牧民的经济负担大幅度减少。加上中国政府在公众卫生上的努力，而藏族又不受计划生育的限制，结果导致全国的藏族人口增长了180%，从五十年代初的200余万人增长到今天的550万人，其平均寿命也增长到了72岁。可别小看这个72岁，因为世界最富裕和发达的美国人均寿命也是72岁。

但是，人口的增长同时也对西藏和其他藏区脆弱的天然环境造成巨大的压力。以青海为例，本来藏族牧民依赖天然的草场，可以靠自己放养的牛羊群，而有很好的生活。但随着人口的增加，放牧的人增多，草场在过度的放牧中开始沙化，这就要求限制牧民的放牧活动，把多余的人口转移到其他产业中去。而在这个过程中，对牧民的职业训练和心理辅导尤其重要。从传统的生活中转型，对他们的生活和心理都是一个重大的变革，如果处理不好，就会使其中的一些群体出现像美国的黑人社区和印第安人社区的状况，即很多人住在政府提供的免费房屋内，但由于工作和前途没有着落，演变成为社会不满动乱的根源。

另外一个问题就是藏族人口平均年龄很低，大约在20岁（维吾尔族也是这个情况）。通常这种年龄结构的社会都会有一定程度的动乱。中国内地平均年龄20岁时，大约是在70年代，我们都知道那时中国的社会情况。即使在文革结束后，也存在着大规模的年轻人打群架的社会现象。而美国平均年龄20岁时，正是风起云涌的六十年代，以反越战、吸毒和嬉皮文化为特征的年轻人向整个美国秩序掀起了挑战。如何将年轻人的骚动情绪通过一些正当的渠道，如流行文化中的反叛行为，或体育运动进行适当的引导，是政府需要考虑的问题。

如果中国政府不对这些问题有所防范的话，这两个因素就会很容易被海外藏独势力利用，来配合由部分寺庙喇嘛的分裂主义行为。如果看一下历次西藏和藏区的骚乱，可以发现主要的闹事者都是以前藏尤其是拉萨周边三大寺庙里的部分喇嘛为主。而班禅喇嘛治下的后藏地区则不会参与这些分裂活动。至于藏传佛教的噶举派、宁玛派和萨迦派，则比较关注于自身的宗教实践，对中国政府的宗教政策持支持态度，也不关心世俗政治的权利分配。

    中国政府在处理这些闹事的寺庙时，由于过分在意西方国家的舆论和西方政府的态度，显得过于宽松。结果一些西方国家报纸就借机造势，为达赖喇嘛的海外宗教势力通过派出人员的方式来控制这些寺庙上出谋划策。这些势力，已经到了利用来自其他藏区的喇嘛学徒到这些大寺庙学习的机会来传播渗透的地步。而08年春，在其他藏区的寺庙里出现配合拉萨的响应活动，与这种海外的计谋策动，恐怕有密切的联系。


五十四

其实喇嘛学徒在寺庙间串门学习，是藏族社区在历史上很传统的方法，效果是通过宗教上的师徒传承关系而达到宗教上的影响，并在客观上实现组织上的领导控制。中国政府如果在这方面不加足够注意和管理的话，就会使得这些年轻的喇嘛缺乏社会信息，偏听偏信，这就让美国控制的藏独势力留下了空间，通过散布精心编制的谣言，来煽动不明真相的群众冲击当地的社会次序。

中国政府似乎寄这样一种希望，即认为西方的舆论和公众之所以轻信达赖藏独势力的谎言，是因为他们对西藏和其他藏区的情况并不理解，如果中国政府想耐心的向他们介绍事实，以为他们就有一天会用比较客观的态度来看待西藏问题。

笔者认为这种希望是不实际的，残酷的现实是，现在的海外藏独运动完全由西方政府在背后运作，而作为海外藏独精神领袖的达赖喇嘛反倒只是一个傀儡，对这些运动势力并无真正的控制能力。在美国的藏独操作是由两个组织进行的，一个是“国际支持西藏独立”组织，得到美国民主党的左翼自由派势力如国会议长佩洛西等人的支持，而加入了很多好莱坞的过气明星来增加声势。另一个就是自由亚洲电台（具体来说是藏语和汉语部门）。这个电台号称民间组织，但其实是由美国共和党内的右派控制。这次事件，基本上所有西方媒体关于西藏的报道，都是这个电台提供的假消息。

这一左一右两个组织的资金来源都是美国国会下的国家民主基金会（National Endowment for Democracy，NED），而具体操作执行，都是由中情局的退休专家发挥余热。笔者的分析是，之所以在3月14日发动动乱，主要原因是利用这一事件，影响台湾的大选。即使这个主要目的没有达到，美国在今后的操作中肯定会加大砝码，继续向中国政府施压，最终达到中国在世界其他地方，比如苏丹、伊朗等能源地区向美国输送利益。

现在海外的藏独势力基本上可以分成三大部分：一个是达赖喇嘛和他的家族。虽然达赖喇嘛在中情局的宣传攻势中，已经成功的建立了以达赖喇嘛带点童真幼稚的灿烂笑容为形象的西方商业品牌。而他带口音的英文，听起来高深而朴素的佛学哲理，也已经把傻乎乎的西方普通人忽悠的死去活来，在西方如鱼得水。但是他的家族还是要考虑他圆寂后的家族经济问题。如果能够通过和中国政府成功谈判，使达赖喇嘛重建其在中国的尊贵地位，他的家族不光可以继续享受达赖喇嘛在海外的巨大商业利益，还可以在西藏和其他藏区的经济事务中占最大的股份，直到下一个达赖喇嘛家族的产生。当然在下一个达赖喇嘛的转世灵童的选择权上，还是会有一场争夺和政经利益的重新洗牌。所以可以说，达赖喇嘛的家族是海外藏独势力中最想和中国政府谈判和达成妥协的。

第二个势力是以西藏的流亡政府主席桑东活佛为领导的老一辈流亡藏人。这些人完全靠打达赖喇嘛的旗帜生活，当然其中的一些活佛也在西方国家发展自己的势力，以保证有一日三餐。这个势力是当年中情局支持的武装暴动和之后的游击骚扰的主要参与者，因此对最后被美国抛弃的经历有惨痛记忆，因此现在他们在配合美国的行动时，会比较注意是不是只是被人当枪使。

第三个势力即是年轻一辈在海外出生的藏人，以“藏青会”和“自由西藏学生协会”为代表。这些年轻人基本上是在美国、加拿大和欧洲各国长大，完全受西方势力的操纵，为西方国家的利益服务。现在海外藏独势力的内部斗争中，主要是这个势力攻击桑东政府贪污腐化，想抢权取而代之，从而在配合西方政府时能更为其所用，方便行事。


五十五

　　中国政府在西藏问题上必须有一个现实的看法，就是美国在西藏问题上绝不会善罢甘休，而中国同美国在这个问题上的争斗会是一个长期的过程。因此中国在考虑其政策时，就不能投鼠忌器，必须在需要对分裂势力打击的时候，不能因为顾及美国的舆论捆绑住自己的手脚。更重要的是，当美国总统和国会议员接见达赖喇嘛的行为（包括西方其他国家的类似行为），被藏独各派势力夸张化，向国内有联系的分裂势力转递错误信息的时候，这些分裂势力会错误的认为西方政府将真正的支持他们的分裂和暴力活动而铤而走险，向中国政府叫板。如果中国政府在这方面由于对西方舆论的顾虑，而不能强势打击这些势力，那么就会印证了这些势力对局势的估计，从而变本加厉。其实西方政府支持藏独势力的主要目的是希望中国政府在国际事务中对西方国家让利来作为西藏问题的交换砝码，他们很清楚藏独势力并不能真正动摇中国的根本，因此在操作藏独的力度方面有很好的拿捏。

　　最近西方国家的政府和媒体在藏独势力的支持上有所收敛，一方面和中国政府做了适当让步，与达赖喇嘛的私人代表重开谈判，给了西方一个台阶下有关系。但其实更重要的原因是，中国民间和海外留学生的反西方情绪由于西方媒体和政客的操作动作过大而强烈反弹，使西方意识到他们可能在将来不得不面对一个对西方充满敌意的强大的中国，而胆颤心惊。同时由于美国军事强权在伊拉克和阿富汗的战局都不够理想，美国和西方经济影响力的衰退，西方希望能通过对中国施压的方式，依靠中国的实力在中东和非洲等地为他们的利益而出力。这就是所谓“负责任的共同利益者”的真正含义。

　　在全球层面上，西方当然会拿出他们自己的萝卜和大棒政策。大棒政策就是支持台湾和大陆继续对抗，干扰目前在“九二共识”下“模糊主权争论，创造双赢局面”的两岸良性互动，争取以清晰的“一中各表”而制造显性的“两国论”；然后支持整合疆独分裂势力，干扰中国的中亚和中东能源供应线；最后就是争取进一步掌控西藏局势，在中国和印度之间制造事端。

　　美国对西藏的操作，就是争取能够在拉萨建立领事馆71，直接与西藏内部的各派势力进行接触。现在美国的西藏情报来源和搅局操作，还是主要以依赖海外各派藏独势力作为中间媒介来进行，这对美国有两方面的不利。一是海外各派藏独势力会有意的错误传递美国的意图，误导内部的势力以谋求自己的利益，这样会造成美国的政策失误，使局面失控，损害美国在中国的整体利益。另一方面是海外藏独各派势力，为达到自身的目的，会误导美国政府，而令他们的决策行动与当地的实际情况脱节。只有美国政府能够直接和中国内部的各派藏人中的势力接触，有独立的情报来源时，才可以通过随时调整对不同派别的支持力度，来控制任何行动的规模。正如美国在台湾国民党和民进党的不同派别中进行操作，以到达台湾各党派任何行为都可以让美国利益最优化的目的。


五十六

　　笔者认为，国家在西藏的各种管理特别是宗教管理，需要明确传达两个信息：一是任何西藏内部在民族事务上反中国政府的力量，都是西方和海外藏独势力的无谓的牺牲品。即使中国政府在任何国际事务上向西方妥协，或者在任何条件上向海外藏独势力妥协，这些内部的分裂势力都不会得到任何好处。美国政府在本国和海外执行自己的操作的时候，从来遵从这个原则。中国在处理西藏和藏区的骚动时，如果骚动人员的诉求是和自身合理权益，特别是经济权益相关的，可以和政府讨论。但是，如果诉求是配合海外势力行动制造分裂活动、恐怖活动，就应该严厉打击，连带其支持网络一锅端。对参与闹事的宗教机构要有经济、人员上的重点管理，不要放任增长膨胀，对于海外返回的喇嘛和其他藏区的喇嘛要防止其从事政治性的颠覆活动。这也是为让这些地方获得正常的经济生产能力着想，让当地人们更多的参与生产建设而不是过度供奉寺庙，是光明正大理直气壮的。

　　二是借近些年来尼泊尔的政局的迅速变化，配合该国新执政的出身贫苦人民的共产党政府，加大在这个国家的投资，较快的提高该国人民的生活水平，以此督促尼泊尔新政府把其境内的藏独势力赶出该国。至于印度方面，虽然西方操作西藏问题的意图中不乏挑起中国和印度的冲突的用心，但只要不会导致大的危机，掌握一些小的和局部的事务，其实是不无好处的。中国可以做的是，给印度施压并力求让印度最后能将藏青会组织赶出其境内。具体的操作方式，可以是对印度吞并锡金的历史事件，表达某种保留或者关切，对锡金和阿萨姆邦的独立运动和当地的农民争取正当经济利益的自发抗争带来的社会动荡，和一些非政府组织一起，表达一种忧虑或关切。

　　在应对美国和西方在西藏的操作问题上，要充分总结民间这次在抵制法国家乐福和去法国旅游的成功经验，允许一些专门的以抗议西方为主要活动的非政府组织存在。一旦美国和欧洲政府在西藏问题上一有动作，这些组织就可以加以配合，造成一种中国民间的强大的反西方声势，对这些国家的政客进行阻吓。而且这种组合不能让其成为一种空喊，在2008年的火炬事件期间，法国一些奢侈品品牌非常嚣张的逆风公告，什么“抗议者没有购买力，不是他们的主要客户，自己的在华营业一切照常”等等，这其实是一种在民族情感和经济上的双重公然蔑视，造成了相当的负面影响。对于这样的企业，必须有实际的操作产生经济压力，让其经济利益受损，以便实现实质性的收敛。

　　西方在和中国的游戏中，基本上是以两手来对付中国政府。一手是用其政府在官方名义上与中国推行友好政策以确保自己获得丰厚的经济利益，一手是以个人或非官方组织名义出面的政府官员、国会议员、社会名流，以及政府控制的非政府组织，跳出来搞与中国为敌的动作，包括打击中国的海外利益，支持中国内部的暴力行动等等。如美国政府包括布什在内的高官和国会中佩洛西等领导人物，都公开支持海外的藏独和疆独暴力组织。在欧洲如英国、法国和德国，都有藏独和疆独组织活动。中国也应该向这些老师学习，可以考虑采取恰当形态，对于世界穆斯林世界以反西方为主的组织表达一种关心，保持相当的接触和经济上的往来。这对于增进和穆斯林世界的兄弟感情，削弱新疆的分裂势力，也有很大的好处。

　　在可以预见的将来，笔者认为中国将越来越难以用置身事外的方法处理国际事务。一厢情愿的希望自己能够安静的发展自己的经济，不被西方骚扰，是行不通的。西方国家是不可能平静地看着中国这个非我族类的国家成为世界上的主要强国的，不可能不试图在路上挖陷阱和拍砖头，更何况目前中国在经济上其实也通过出口外需与西方挂钩，不一定占据主动地位，所以可趁之机还是很多的。当然，西方知道光靠捣乱的方法风险性也很大，所以就会不断的祭出胡萝卜来，忽悠爱面子的中国政府和人民。

　　在笔者看来，中国政府和人民在奥运会前期宣传活动上已经被西方砸了一板凳，就要认情形势，做好准备（本文写于2008年7月初。——编者注）。由于中国人民非常爱国，非常为自己举办奥运会感到扬眉吐气，所以这样一个在国外看来很大程度上已经蜕化成现代商业运作的体育活动，就被人民给予了“中国人民站起来了，中华民族再次复兴”的大面子。笔者要提醒读者的是，咱们对于北京奥运会，一定要做好充分的估计，你看一个奥林匹克山上取来的火种被冠以圣火地位到处巡游的机会，全球的反华势力都要倾巢出动来砸场子。那么等到奥运会真正上演的时候，可以想象将有多少反华势力嚷嚷要冲进北京，借着你主人想要搞一个历史上最大最棒的盛会的时机，大闹特闹搞个乌烟瘴气了。72


五十七

　　好在中国人民和政府已经有所醒觉，习近平同志在奥运临近前关于对奥运会要有平常心的表示就是一个好的开端。其实这次奥运会，为了应付海外敌对势力的破坏，对奥运会的保安措施，实际上已经造成了对旅游业的打击，使这次奥运会的经济效益大大降低。

在应付西方反华组织希望在北京奥运会上的搅局行为，中国的民众可能会有比较好的应对方式。西方在自己的媒体上搞洗脑可以概括成：“中国人民很善良，中国政府很流氓。西方政府要体谅，西方人民要逞强。”，就是有意区分中国的群众和政府，把中国的人民群众，用好莱坞勾勒弱势国家的人民的一贯手法，渲染成一批其实在民族问题上与政府持不同意见的群体，此所谓“中国人民很善良”。所以西方政府要对这批唯唯诺诺而不敢为的人民多加理解，此所谓“西方政府要体谅”，而所谓争头出气，就要靠我西方无数民间勇士，“勇闯北京”，来一次“仗义执言”，此所谓“西方人民要逞强”。所以所有西方媒体对中国的抹黑，都是以中国政府为对象。而来北京捣乱的西方政治流氓，如拿着西方政府工资的“记者无国界”之流的职业运动混混，在中国捣乱时，如果中国政府出面处理，就会招惹西方媒体的大肆群攻。中国苦于此，所以才会居然过分投鼠忌器，疏忽大意，居然让一些流氓在中国的长城上打出西藏独立的大旗。

　　中国的应对方式，就应该让西方人明白，在今天的中国，你西方混混不再可以像19世纪末那样，横行东方国家，独享随意耍流氓的特权，更不是今天的中国还要一味的让步，去“以中华之物力，结与国之欢心”。中国人民虽然善良和好客，不过13亿人民中，那也不缺乏头脑容易激动的青年。既然你们这些西方来的流氓要在北京搞事，那也就不能排除北京的一些小年轻因为“义愤填膺的情绪”，在这些白种流氓胡作非为的时候作出一些较为激动的回敬。在中国的警察赶到现场前，这些小年轻又适可而止，提前离场。中国政府会依法将这些触犯了中国法律的外国流氓拘留，同时发表声明，不鼓励群众采用自行激动手段来应对这些外国人违法活动——但是很遗憾，希望这些外国人好自为之，不要滥用中国人民的好客情谊，在中国的街道上乱打让中国人反感的标语旗号，胡作非为。其实，不要以为这帮西方流氓是什么亡命之徒，或者是什么敢于献身的理想主义者，他们只敢按西方“政治正确”的方针起哄，在所谓道德高尚的议题上走走街，如果让他们去纽约街头打出支持本拉登的标语出来，不知道还可不可以活着走出来。

　　这种灵活的法律运作方式，并不是没有先例，举一个美国的案例如下。在奥运火炬来到美国旧金山之前，曾有几个隶属于自由西藏学生组织的职业混混，违反当地的法律，阻碍交通，爬到金门大桥的吊索上挂标语。而大桥的工作人员不得不冒着生命危险，去把这些标语取下来。事后，旧金山法院对这个犯法行为进行宣判，判罚这些混混必须在社区组织做义务工作，可荒唐的是，他们需要做义工的社区组织，就是他们自己的自由西藏学生组织。从这里可以看到美国“法律至上”的具体运作方法。

　　而担任旧金山警察保安活动总顾问的戴利警长，对记者谈到了他本身的亲身经历。戴利曾是美国特种部队军官，退役后曾出任过美国前总统克林顿的保镖，后来出任旧金山一个分局的主任。在一次藏独分子在中国领事馆前进行的未经批准的非法静坐抗议活动中，戴利带领他的下属，去规劝抗议者结束非法活动。结果在他试图劝说一个喇嘛时，对方突然从袖口中掏出一个木棍，冲着他的头上就是一棍子。经验丰富的戴利吃了个大亏，因为他以为西藏喇嘛都是热爱和平的善良人士。让他更恼火的是，这个打警察的凶僧被逮捕后，因为美国上层人士的干扰，检察官拒绝起诉，最后无罪释放。戴利对旧金山警察的建议是，必须把藏独的喇嘛当作恐怖分子一样对待，严加防范，不然吃了亏都有苦说不出。73

　　中国在对待这些政治流氓的时候，也不能按常理出牌。必须改变过于顾及西方的舆论而不能有效的维护自己的利益的情况出现。


五十八

除了要应付西方的上述大棒政策，中国需要提防的是西方拿出最大的一颗大萝卜，来满足中国人的虚荣心，这就是以允许中国加入西方八大工业国这个大亨俱乐部，用西方既定的规则，令中国为西方的利益服务。在当前西方在世界各地的影响力大幅减弱，需要中国的帮忙才可以在世界的很多地方维持其利益的情况下，这个大胡萝卜很可能会适时送上。如果中国人满足于这种虚妄的做世界大国的美梦，就会傻乎乎的牺牲自己的利益，成为西方国家的帮凶。

中国在世界事务上的政策，还是要用明初的九字真言“高筑墙，广积粮，缓称王”为基石。首先要“高筑墙”，增加国防力量，建立一支“中洋”海军（相对于中国目前的近海海军和美国的远洋海军而言，覆盖能力介乎其中的海军），能够保护中国的海外利益和中国从本国及巴基斯坦沿海到中东和北非的海上新丝绸之路，必须能够做到防止“当代匈奴”来扰乱这条生命线。中国军队除了在潜艇和护卫舰上要加速国产为主的发展，还要充分运用友好国家的支持，通过贸易上的互利共同体，把中东和北非的国家的利益同中国的利益绑在一起。

　　“广积粮”可以从两个方面来考虑：一个当然就是发展生产经济，这恰恰是中国人做得最好的一点，另一个就是要进行长远的战略物资储备，比如在东南亚和非洲发展以中国市场为主的粮食基地，补偿中国因为大规模城市化带来的耕地损失。在原材料上，中国应该大量动用手上过多的美元储备，在中亚、东南亚、南亚和北非购买矿业资源，在美元进一步大跌前，抢占全球的资源。在石油资源上，长远来说，中国应吸取美国的教训，建立一个以替代能源为主的经济；在目前，就应该充分利用一些产油国家，如伊朗、苏丹、委内瑞拉等国和西方的争执，在油价上取得优惠，支持中国经济的继续发展。

当前高居不下的油价（本篇写作于2008年6月底7月初，时逢国际原油价格达到接近150美元的高点。——编者注。），会对西方国家，尤其是美国的经济造成极大的打击。中国必须让反美的产油国知道，如果中国得不到相对于市场现价大幅削低的石油供应，就会导致经济衰退，则中国就无法为他们提供必要的保护，那么他们就可能成为西方强权下一个军事干涉的目标。楚人无罪，怀璧其罪，这个道理估计这些国家的领导人也听得懂。如果他们的目的是要打击以美国为首的西方经济，他们大可以一方面增加对中国需求的石油输出，另一方面继续减少对西方为主的国际市场的供应，让西方那些投机基金在把美国股市和房市炒死了之后，再在石油期货市场上把油价炒过150美元一桶，令按照国际油价定价能源的西方消费者为此买单。

　　且中国在这些产油国家，比如说非洲一些国家的贸易，是用中国的基建工程换取当地的能源。某种意义上来说，是一种易货贸易安排。随着能源和原材料价格上涨，建筑工程的价格也相应提高，应该可以保证中国经济不受打击。在国内政策上，不应该实行政府补贴的汽油低价格政策，而是应该放开以消费者为主的汽油价格，扼制耗能交通方式如大排量私家车的发展，但在生产和基本民生的耗油，例如农业、能源、公共交通运输等等，应该根据各自重要性采取对应的退款支持政策。在能源效率方面，则必须通过严格的管制，使汽车等耗能品的能耗效率达到高水平。


五十九

　　“缓称王”是中国人最需要考虑的问题。这并不是说要坚守邓小平所说的“决不出头”，因为中国已经不可能置身于国际政治之外自己过自己的小日子；而是说中国要把自己定位在一个穷国，一个发展中国家。即使在十年，二十年后成为世界第一的经济体系，人民生活到达小康水平，中国的人均收入仍然属于发展中国家，或自己要坚持自己还是发展中国家的一员。因此中国要拒绝参加西方八国组织，应该出头成为发展中国家的领袖，在与非盟、东盟、拉美的Mercosur74，还有阿拉伯联盟之间牵线搭桥，促进南南合作。当然也要与美国为首的西方国家在南北合作和对话中，就全球贸易、环保、能源合作、防治温室效应上寻求合作。

中国在联合国安理会常任理事国中是唯一一个在近现代没有对世界其他国家进行殖民的大国，因此可以被众多发展中国家看作是安理会中唯一和真正代表自己利益的大国。在联合国改革方面，对增加日本和德国成为常任理事国的提议，中国应该持保留态度和有条件的观望，因为这两个国家即属于西方阵营，又是美国政治傀儡。中国更应该支持发展中国家的代表或者国家联盟，如阿拉伯联盟、非洲联盟以及未来将可能出现的拉美联盟获得安理会常任理事职位，让巴基斯坦、沙特阿拉伯、埃及、南非、苏丹、巴西、墨西哥和委内瑞拉等国，都可以在安理会轮流坐庄，使联合国做到真正多元化。

按照这种思路，所以说中国对于目前与欧洲联盟的关系必须重新审视。前几年，因为美国新保守派一意孤行，而法国在希拉克，德国在施罗德的领导下，强调欧洲与中国的战略伙伴关系，发展多极社会，防止美国独大，这是一个正确的道路选择。但当美国势力衰退，中国势力兴起时，新上台的德国总理默克尔和法国总理萨科齐，出于一些意识形态上的原因，不光重新向美国靠拢，开始向中国叫板，而且还在世界事务中，担当反华马前卒的角色。相比较于新保守派已日益出局，对华日益灵活的美国政府，默克尔和萨科齐这对黑风双煞，反倒是有“比布什更布什”的架势。

在这种情势下，中国政府在拉萨事件后对欧洲主要国家一些举动的政策，却是仍然想以过去的“分而攻之、各个击破”的策略来达到目的。可是中国人需要明白的是，中国和欧洲之间，并不是一些中国的国际问题专家所宣称的那样没有利害冲突，可以做天然的盟友。

　　中国，与欧洲和美国的冲突，根源在于对当前这套经过西方世界数百年的杀戮和掠夺所建立的国际既有秩序。在这个现存的国际秩序中，只占世界大约四分之一的西方世界，要消费占世界四分之三的资源。现在你中国以占世界五分之一的人口，要想过小康社会，在2020年即使只达到大约人均收入4000到5000美元，也就是算成购买力平价仅相当于西方的三分一的水平，也势必会加入现在的世界资源大饼分配。这简直就是从无论是欧是美的西方人那宽裕的饭碗里虎口夺粮，是不可以忍受的大逆。只要看一下欧洲对中国在非洲投资的态度，就可以知道其中的奥秘。

　　除非中国人可以发明一种新的经济运行方式，即依赖于可再生的能源，和新型的建筑材料，从而避免在石油、天然气、各种金属矿石上和西方极度浪费的消费文化展开残酷竞争，否则，中国人就不可能和西方人成为真正的盟友。而由于美国开始调整政策，不再如过去那般口出狂言大谈新欧洲优秀啊旧欧洲没落，不再忙于把法国炸薯条改成自由炸薯条75，中国和欧洲之几年前在美国新保守派攻击欧洲的背景下确立的伙伴关系，也开始慢慢对欧洲失去其重要性。再加上美国现在开始允许法国等欧洲国家参与伊拉克石油分赃，法国又在阿联酋开设海军基地，这些因素都会使欧洲对中国的态度发生微妙的变化。


六十

因此，欧洲在应对中国过去那种“分而治之、以夷制夷”的策略上，采取车轮大战的对付方法。2007年就由德国领军对付中国，默克尔带头接见达赖喇嘛，开启08年春的拉萨暴乱序幕。中国缺乏思维弹性的“专家”们，就得出“德国的影响力在世界范围内不如英法”的谬论，让中国开始在经济上教训德国，却把大块经济馅饼扔给来访的萨科齐和布朗。没想到喂饱了白眼狼回去后，欧洲就转由法国萨科齐来唱去年德国的高音部，英国布朗唱中音部，默克尔唱低音部。只见萨科齐高调见达赖喇嘛，布朗低调见达赖喇嘛，默克尔倒是找个借口避开锋芒。

眼见新的三重唱，中国“专家”们的反应就是突然一百八十度大转弯，宣称什么与德国的关系已经恢复正常，法国的行为不必多虑，据说原因是“法国在欧洲的影响不如德国”，督促中国政府要准备对德国扔经济馅饼。当然，因为法国和英国在中国拿到的超巨型大饼可以吃上好几年，所以这个新三重奏可能还会唱一段时间，此间英法就可以继续在世界上展开打击中国的行动。而等到中国在未来两年喂饱了德国之后，才再次轮到德国出马。

中国人实在该变得聪明一些。既然欧洲在世界事务上已经重新成为美国的马仔，那么中国就应该只把他们当作美国的马仔。在国际事务上不需要在欧洲的身上浪费时间和精力，只需要和他们的主子打交道，谈妥协定，让他们的主子回家自己传达会议精神就行了。

在这方面的谈判策略上，我们倒应该向朝鲜学习。朝鲜人需要同时和美国和日本谈判，它对日本的喋喋不休只回一句：你日本不过是美国的一个州而已，根本不需要来参加什么谈判。我和美国谈什么，由你老爸回去给你打声招呼就行了。

　　在如何应对中国的态度上，美国也有不同的分歧。意识形态旺火上身的共和党总统候选人麦凯恩宣称要把俄罗斯从西方八国俱乐部踢出局，而且永远不让中国加入，但就要吸取印度这个“世界最大民主样板”入会。这位老朽不知道，如果中国不买你八国俱乐部的账，掉头自己开一家新夜总会的话，你那个俱乐部就会变成和世界银行、国际货币基金组织一样，门可罗雀，名存实亡。最近美国一些学界人士的新提议，倒值得中国学界人士好好研究加工。这个新建亦就似乎所谓建立以美国和中国为主的G2俱乐部，将中美之间定期进行的战略经济对话提升到一个对国际政治各方面有举足轻重作用的主要政策的出产源。当然，美国这套想法，就是由美国和中国共同管理世界经济和安全事务，中国可以作出太极顺手，借力用力，自己发挥出一套新的原则。

具体说来，中国应该就势“支持”美国的这一想法，添加进自己的内容。作为一个代表世界大多数发展中国家利益的大国，中国可以提出增加地区性国家组织在地区性事务的主导作用的建议，并把中美两个大国的作用，定位成“在地区性国家组织之间进行协调、引导”。比如说中东的伊朗问题，中国可以主张应该主要由欧佩克组织和阿拉伯联盟牵头，在“欧-阿”框架内找出一个合理的解决方法，而美国和中国来协调，但都不起决定性的作用。再如非洲的津巴布韦政治危机，中国要坚决反对西方主导的制裁甚至军事干预的政策，而应该主张依靠非洲联盟对这一本地事务的处理意见，来决定政策导向。

　　总之，中国在世界事务上，应该逐渐排斥欧盟对非欧洲以外的事务的发言权，不需要尊重这帮黑社会的自以为可以得到大佬待遇的小喽罗。他们既然只不过是美国全球事务的一个马前卒，那么就只应当得到马前卒的地位，中国在国际事务上即使要寻求共识，也只需要同美国去寻求共识。






【写作日期】2008年7月6日——7月12日            

