# -*- org -*-

# Time-stamp: <2011-08-27 09:25:01 Saturday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 【第四篇·石油】





深夜忽听巴渝曲，起剔残灯酒尚温。

--【明】王叔承

+ 三十一

美国在伊拉克的战略失误还包括其对伊拉克难民的驱赶不够彻底。如果你了解欧洲殖民者在北美、南美、澳洲、新西兰和非洲的征服史，就清楚那种对原居民采取彻底的种族灭绝政策，再大规模的移民占领其资源的做法，被历史证明十分有效。比如在今天超过3亿人口的美国，其原著民印第安人（包括混有其他民族血液的混血儿），加上阿拉斯加的爱斯基摩人，根据2006年的统计数据才240万，就是这个历史政策的成功之处。[fn:jdwtdgyx0151]

[fn:jdwtdgyx0151] 反过来，这个“人口融化”也是今天许多西方学者开始担心“欧洲穆斯林化、美国拉美化”的一个原因

当然在今天的世界里，尤其是自认为占据人类道德最高点的美国人，要把这个方法在新形势下发扬光大，需要做出聪明的改变。可惜美国在这方面比起欧洲人差得太远。美国迄今为止也只是“清理”掉了70多万伊拉克平民，赶出了4百多万的伊拉克难民。而且这些被赶走的人口，还不是产油区的人口，反倒多是大城市的有产和中产阶层。 *而欧洲的国家和大公司们在非洲的手段就要高明得多。比如在民主刚果挑起的内战，就是通过利用当地的不同民族之间的仇恨，由那些部落自己提供战士，附近的八个非洲政府参与，由欧洲国家提供军火互相残杀。结果在大部分资源丰富的地区产生了无人居住区，这就方便欧洲公司的开采。而这场欧洲人深感“痛心”的非洲人自己之间的杀戮，最少导致了540万人死亡，估计流离失所的人数恐怕更多。而提供财政和军火支持的欧洲国家在拿到分赃的大头之后，因为开采的地方是无人区，无所谓污染扰民或者低价雇工的争议，所以还不会受到环保分子和人权斗士的批评。*

吃够苦头的美国只好在2006年调整策略。美国在伊拉克的政策调整其实主要有两点： 一是改变和逊尼派民兵交战的策略，改为扶持的方法，令他们和什叶派互相残杀，来阻挡伊朗势力的增长。二是美国大幅度增兵伊拉克，保证伊拉克石油产量大幅增加，打击现在一浪高过一浪的油价。

这两点牵扯到一系列具体方法的改变。在第一点上，美国必须放弃原先打击沙特阿拉伯的目标，转和沙特阿拉伯重新和好。有两个因素有助于这个问题得到解决。一是犹太因素削弱，久拖不决的伊拉克战争被美国国内反对势力，尤其是民主党利用大加攻击，新保守派的各方人马在美国政府内纷纷落马，导致犹太裔分子对政府的影响减弱。此外以色列开始把伊朗的威胁放到了首位，沙特阿拉伯暂时退居仇敌老二，这也影响了美国政府的政策转向。有趣的是，2006年底美国民主党在国会选举大胜的当晚，笔者就预测美国当时的国防部长拉姆斯费德会辞职，结果果然他第二天一早就交了辞呈。二是伊朗威胁日渐凸出，2006年年中在黎巴嫩，以色列和伊朗的前锋黎巴嫩真主党开了一战，号称第二次黎巴嫩战争，结果不是很理想。加上伊朗对哈马斯的影响越来越大，而哈马斯又在巴勒斯坦选举中上台，这些都导致了美国快速和沙特阿拉伯和解，然后在整个中东地区，包括伊拉克，开始武装训练逊尼派民兵，来对抗伊朗支持的什叶派的势力。

有趣的是，这等于美军开始训练他们以前的死敌。而且完全不能确信这些民兵得道以后，到底是会先向美军开枪，还是先向亲伊朗的什叶派民兵开枪。曾有美军军人问逊尼派战士，会不会仍然想杀死他，该民兵回答：“是的。但不是今天。”[fn:jdwtdgyx0152]

[fn:jdwtdgyx0152] 如驻伊美军博客《军队伙伴》（Army of Dude）中的文章《我敌人的敌人的敌人的敌人……》即谈到了美军和前对手之间的微妙关系。

第二点，却是美国的一个难题。虽然布什政府后来决定对伊拉克增兵，但是人数只不过数万。而美国想要彻底控制伊拉克的油田和输油管道，至少也要将现在的兵力加倍。当然，虽然伊拉克政府不甘心被美国拿油而试图把油田放给中国为首的亚洲国家，但只要美国杀价不要杀得太狠，还是可以用枪逼伊拉克政府就范。美国在增兵上的核心难题是，如何既在国内开辟兵源，又不会采取美国人民反感的征兵制。 *笔者倒有一招可以支给美国，那就是瞄准非法移民。* 美国已经有超过1000万的拉美非法移民，如何处理他们的身份问题已经在国内炒得天翻地覆。据报道，已经有数百甚至上千的非法移民用偷来的社会安全号码参加了美军——当然是为了赚美国身份，但有些居然真献出了生命，美国政府已经破例授予了这些勇敢的战士公民权。所以说，如果美国政府颁布一条法令，任何非法移民如果在美军服务三到五年，就可以变成美国公民，那么估计会人头涌动，很多“黑人”（非黑皮肤，乃黑户口是也）小伙子报“国”参军，为美国人民在中东抢油，真是为国、为民、为人、为己的大好事。既解决美国的非法移民合法化问题，又避免啃上让美国人讨厌的征兵制这块硬骨头，还可以防止美国经济被石油输出国慢慢的勒死。


+ 三十二

*过度的依赖外国石油，在油价疯涨的今天已经成了美国的癌症。* 如果处理不好，美国这个超级大国的老命也许就会呜呼于此。伊拉克的石油很可能就是帝国生死存亡的生命线。今天的民主党也许只是利用美国人民厌战的情绪抢夺白宫宝座，一旦目的达到后，就会装模作样的从伊拉克撤出一些人马，但会 *在伊拉克建立一个永久的基地，保持大致5万到7万的军队，维持美国对中东油源的控制，希望有一天可以把油价打下来。如果你看一下美国在日本和德国的驻军，就可以看出50年内伊拉克的大致情形。*

其实今天的美国是一个缺乏智者的时代，国内政治和外交事务都被主要利益集团操控。这些集团为达到一己私利，不惜牺牲国家的长远利益。美国由于其在世界上的文化和思想上已经毫无信用可言，经济体系在金融信用丧失后几乎崩溃[fn:jdwtdgyx0153]，当然要用唯一可以依赖的军事实力为美国在世界上争利，这本无可厚非。但是如果不把好钢用到刀刃上，结果不光白白浪费美国大兵的生命，而且还事倍功半。

[fn:jdwtdgyx0153] 本文写于2008年6月下旬，3个月后雷曼兄弟倒台引发又一波金融危机，印证了作者对美国经济的判断。——编者注。

美国今天面对的，不是一个简单的石油供求脱节的问题，不是因为中国和印度的发展而导致供应量短缺的问题。如果听那些无知的经济学家妖言惑众，就完全搞不清楚问题的根源。 *美国和西方今天面临的问题是西方对世界的统治和欲取欲求的日子已经到了完结的时候。* 由于西方，尤其是美国的经济完全依赖于外部的能源，而这些能源又被非西方甚至敌视西方的国家所控制，美国面临的就是意识形态化的能源民族主义，甚至还有宗教和文化冲突的因素掺杂在内。

今天的石油市场并不是一个简单的供需市场，而是非常类似于2000年美国加州电力危机时的电力市场，类似于一个金融投机场所[fn:jdwtdgyx0154]。由于美国的基础建设是建基在能源工业上，对石油和天然气的需求所可容忍的降低空间不是太大。而石油的供应量方面，石油输出国组织具有很大的控制力。随着油价的高涨，他们就可以降低产量来护价。再加上很多石油的开采， 比如中国和一些产油国的合同油，完全是从油田直接运回中国，丝毫不经过石油市场。这就使得限制了供给公开市场的石油产量调解的灵活度，而国际市场的油价便太容易被金融投机资本以各种借口炒作，又由于美国的汽油定价直接与原油市场价挂钩，投机导致的油价上涨就直接打击美国人民本来并不宽松的钱袋，使大家不得不在其他消费上节衣缩食。

[fn:jdwtdgyx0154] 一种物品一旦被“金融化”，即带上了金融属性，那么它就不再服从“价高引诱需求减少供给增加，价低需求增加供给减少”这套经济学家天天念叨的简单规律了。所谓金融属性，就是这个物品可以被不断的再次转卖，通过转手价差获得利益。这时，价格就不再是购买者的成本，而是购买者的收益了。这种金融属性物品很容易出现价格越涨越多人追捧的现象。股票、房地产都是典型例子。而石油、金属甚至电力等大宗商品，通过期货合约等手段，也可以带上金融属性。

由于油价高涨，就会带来全面的物价上涨，导致高昂的通货膨胀，实际消费支出降低。而消费的降低会造成国内经济的实际增长停滞，甚至衰退。这个结果就是所有经济学家最恐惧的滞胀，再加上固定资产的失血，唯一的希望来源于美元的大幅度贬值，这可以增加美国产品的国际竞争力，而推动美国制造业的出口。

但是 *美元的狂贬也带来其他问题。* 如果你看一下用欧元计算的石油价格，其实涨得不像美元这样离谱。如果美国国民的大部分消费物品还是像这样靠进口的话，美元大幅贬值可能促进出口未成，反而先造成普遍的消费品物价更大幅度上涨，增加民生的困境。而且虽然美国的产品具有的竞争力，但也不一定可以便宜到可以和新兴经济体竞争的地步。比如印度是全球药物的最大伪造和冒牌产地，美国的药物就是在美元贬值后，如果没有版权保护，还是无法和其竞争。

再加上美国过去因为经济结构变化等自身的问题，导致过去二十多年公共教育投资不够。而在一些美国竞争不占优势的工业里，劳工再培训不足，这时一些利益团体倾向于政治上施压，而通过保护主义法案来维护自己的利益。在民主党当政的今天，这些机会就会更大。这样国际贸易持续二十年的自由开放可能走逆。另一个对美国出口的不利因素，就是国外民族消费主义的兴起。一个最近的例子，就是韩国民众对美韩自由贸易协定中的美国牛肉进口进行的大规模抗议。而在一些本来就对美国不满的中东国家和石油输出国，不排除当地的消费者以不选择美国产品来有意打击美国经济。

有趣的是，发生在中国消费者身上的事，就印证了这种危险。本来西方世界，希望将他们这个世纪的新鸦片——简单化、标签化的美式民主自由，用来忽悠其他国家的人民，让他们能够从中夺利。结果没想到却作茧自缚，反受其害，最后成了忽悠自己。法国支持藏独的结果，就是遭受中国消费者抵制造成经济损失。美国新保守派在伊拉克忘记了自己的抢油目的，正二八经地在那里搞民主自由，结果是令自己的经济困局越来越深。


+ 三十三

如果美国人可以集中兵力，控制住自己专用的油源，然后利用一个5到10年的过渡期，像中国一样，快速的改变自己的经济结构和汽车文化，大幅度的建立起以高速列车为主干的公共运输和交通系统，然后利用自己所仍然具有的技术和研发优势，与其他的世界能源消耗大国如中国、日本、欧洲和印度合作，大力开发可再生能源和替代能源，使美国人可以不再完全依赖于汽车和高速公路，那么就会彻底降低美国对海外能源的依赖。这样只需要通过美国自身的石油和天然气开采再加上加拿大和墨西哥湾的资源就能够满足国内需要，美国也就不会再 *受制于人* 。

而最忌讳的事情就是，如果美国用军事力量把油价打下去后，美国人民又认为日子恢复正常，开始过鸵鸟把头埋进沙里的日子，等着下一个能源危机的来临。正如对海外石油依赖的危机感在上个世纪70年代比今天还要厉害，但危机终结后一切造常，没有产生任何实际的影响。

另外一个问题，就是在美国的民主制度下，想要改变既存的汽车文化，进行快速的基础建设转型，也是一个难题。各种利益集团的角力争斗，国会的院外集团的游说，环境保护分子的干扰，法律程序繁复，司法上不断上演攻防阵地战，都会使这一过程看不到头。相对于中国的快速基建能力，美国的制度具有很大的劣势。

比如说，在环保法律上，中国一个禁止使用超薄的塑胶袋的法令每年就能减少87万桶原油用量。虽然所有的法令都有一个执行的问题——许多超级市场可能会完全蔑视这些法令。但由于此法一出，薄塑胶袋的生产商已经被迫开始转型做其他行业，可以想象很快薄塑胶袋的存货就会用光，而不再见于市面。而在美国由于制度的问题和游说集团的强大，美国无法通过一个联邦的法令，只能够靠各市政府自己来立法。美国加州的旧金山就是首个通过类似立法的城市，而全美国也有很多城市想跟进。但是，这些城市首先面临一个大问题，就是塑胶袋生产商对他们的法律诉讼。对旧金山等大城市而言，因为财大气粗，不怕和这些生产商对簿公堂，而很多财政拮据的中小城市，就不敢惹这些制造商，从而放弃了这个节省能源的环保法律。美国在汽车燃油效率和排放量的法律上，都同样处于这种困境。

美国面临的挑战一个是来源于国内政治的无聊内斗，一个是来自于外部世界政治经济中心转换。在世界上，非美国和非西方国家的经济影响力日渐强大而导致美国影响力的削弱，而美国恶质的两党内斗又使美国无能力转变自己而应付调战。

美国的政治实质恶化在于两党会花费很大的精力去争吵一些对国家和人民没有太大实质意义的课题。比如妇女有没有权利堕胎，同性恋可不可以用“结婚”这个名词等等。而在关心民生的议题上，靠穷人票源的民主党要求加税收加支出，靠富人财源的共和党要求减税收减支出，最后角力的结果就是减税收加支出，落得个皆大欢喜。那么节源开流之后，钱从哪里来呢？印多点钞票去借债，把孙子和重孙子的钱都花光。等到大家都觉得要减少支出的时候，就先开始缩减教育经费，让未来一代为这一代借债的奢侈生活还债。那么那未来一代，就将在与世界其他各国竞争时营养不足。

而美国最绝妙的一点就是，它的民主制度造成任何人都不需要为这些胡作非为负责。人民做主，都是你们自己选出来的，要赖只能赖你们自己。每四年的换届，又导致整个政界目光短浅，个个追求短期利益牺牲中长期利益。虽然选民们理论上具有挑选厨师的权利，但是就是用奥巴马师傅替换布什大厨，炒出来的菜还是咕唠肉和柠檬鸡。

当然，美国人民自己也难脱干系，现在的经济状况是需要开源和节流。但是穷人愿不愿意勒紧本来就已经紧的裤腰带去支持缩减福利？富人肯不肯拿多点私房钱出来，拯救国家？军火商可不可以不再操纵政府增加武器购买？一个宣扬个人主义和利己为中心的文化，可不可以为了整体的未来而牺牲一己的利益？看来答案都是否定的。这就决定了美国在未来难于应付世界的新挑战，而对美国最致命的挑战，就是美元作为世界经济和金融体系基石的崩溃。

如果这一情形发生的话，美国不光在世界经济和金融上的垄断地位丧失，而且其全球强大的军事力量也会因此而轰然倒塌。


+ 三十四

也许难以令人相信的是， *美元在世界经济和国际金融的地位，也取决于沙特阿拉伯的态度。* 虽然没有明确的条约，但是大多数历史学家和国际政论家相信，沙特和美国之间有一个不成文的协定，即美国为沙特提供安全保障，沙特保证世界石油以美元定价。这一安排起源于1974年，使与黄金脱钩的美元，可以依赖黑金石油继续保持世界货币的地位。

在欧佩克内部早有要求放弃美元的声音，其中吵得最大声的是委内瑞拉的查维斯和伊朗的艾哈迈迪·内贾德。早在2005年，委内瑞拉已经把主要的外币换成了一半欧元、一半人民币，并将石油收入帐号从美国的银行转到了欧洲和中国，只留下了少数美元当零花钱。伊朗则大部分是欧元，但就在差不多同时，由于核计划的争执，把钱从欧洲银行转入到中国的香港和上海。当然，伊朗和委内瑞拉更换货币的借口不会是政治上需要对抗美国，而是经济上美元象一个没有降落伞的跳伞者以自由落体的速度下降，石油输出国没有理由将他们宝贵的黑金去交换一堆绿花花的废纸。

当然在欧佩克里，真正说话顶用的人是沙特的阿卜杜拉国王。沙特的原定计划是在2010年推出一个海湾统一货币（Unified Gulf Currency），采取与欧元挂钩，或者和一个一篮子货币挂钩的形式，替代今天海湾各石油输出国本身货币与美元挂钩的形式。从当今发展的趋势看，一篮子货币的机会比较大。而在这个篮子里，以人民币、日元、印度卢比等亚洲货币的比重一定会占大头。届时海湾国家可能就可以以自身的这个海湾统一货币作为石油的结算货币。

要了解国际石油市场运作，必须明白今天的国际市场石油价是以美国纽约商品交易所里西德州轻油期货价（West Texas Intermediate）和英国伦敦国际商品交易所的北海布伦特原油期货价（North Sea Brent Crude）为基准，而这两个市场都是用美元定价。 *要想放弃美元和石油的挂钩关系，就需要建立非西方的石油定价基准和非美元的期货交易所。* 前者比较好办，由两个替代品：通常海湾国家对亚洲的出口价是以迪拜轻油（Dubai Crude）为基准，同时欧佩克自身也有一个“原油参考篮子”（OPEX Reference Index），由主要产油国各自出产的油比例混合而成，在2005年6月15号后，包括了阿尔及利亚的撒哈拉沙漠混油（Saharan Blend）、印尼的米纳斯油（Minas）、伊朗的重油（Iran Heavy）、伊拉克的巴士拉轻油（Basra Light）、科威特的出口油（Kuwait Export）、利比亚的伊塞德油（Es Sider）、尼日利亚的蚌尼轻油（Bonny Light）、卡塔尔的海油（Qatar Marine）、沙特的阿拉伯轻油（Arab Light）、阿联酋的姆尔班油（Murban）和委内瑞拉的BCF 17油。

但是建立一个非西方的交易所是一个挑战。伊朗曾经试图开一个欧元石油期货市场，但是由于交易量太小，加上美国和欧洲的抵制，还有交易所自己交易技术方面不够，并不是太成功。也许一个有效的做法，就是在香港（或新加坡，但是香港应是首选，因为中国的关系）开设一个亚洲为主的石油交易期货市场，以欧佩克的原油参考篮子作为定价标准，而以人民币作为交易的结算货币。当然现在中国也许不愿意在世界金融体系上强行出头，但是等过了2010年，中国政府可能没有其他的选择。[fn:jdwtdayx0455]

[fn:jdwtdayx0455] 本文写于2008年6月下旬，4个月以后，中国与很多国家签订人民币互换协议，人民币国际化的步伐明显加快，虽然相关讨论，还颇有混乱之处，建设香港为中心的人民币贸易结算基地，也还需要先对香港打扫好屋子。但是作者在这里的预计以及在第二卷中的建议，看来是与现实的发展，颇为吻合。——编者注。

当然即使石油由美元定价，也不排除交易双方用其他货币结算，不过由于兑换率的风险，这种方法就会增加交易成本。比如说，由于美国对伊朗展开的金融和经济战争，伊朗已经完全退出了美元系统，而依赖于欧元去完成国际贸易，但这就增加了其交易成本开支。货币结算问题之所以要命在于，如果石油输出国不再接受美元作为付款方式，即使仍然用美元定价，也将导致主要石油消费大国，如中国、日本和印度，不再需要准备大量的美元储备来支付石油进口，估计大约三分之一到百分之四十的美元储备就必须转换成新的结算货币，而美国联邦储备局就必须把这些多出来的美元吸收回去，其结果就是大幅度的美元贬值和美国国内物价上涨。当然对所有现在持有太多美元的国家来说，如果这个过程太快，影响会太大。所以大部分持有美元储备的国家会倾向于一个受控制和缓慢的过程。而在这一过程中，美国经济就不会遭受象1929年大萧条那样的沉重打击，而会走一条类似日本那样二十年无法复苏的不死不活的道路。

因此， *沙特阿拉伯就是掌握美国命运的关键所在* ，美国和沙特的关系变暖，是从2006年11月美国副总统切尼访问沙特为起点。而这次访问的意义在于使美国和沙特放弃前嫌，共同面对伊朗的崛起。以色列同黎巴嫩真主党刚结束的战争结果不尽人意，也迫使美国不得不寻求沙特的合作。而这个合作到底会持续多长呢？


+ 三十五

美国和沙特关系改善的结果，不光是沙特在911中不清不楚的干系不再被美国追究，而且美国也不再在沙特等国鼓励民主革命。当然，由于美国对伊拉克的逊尼派民兵从交战改为扶持政策，那些和美国在伊拉克打打杀杀几年的外国战士们（超过一半是沙特公民），也就做个顺手人情，不被西方媒体所提起。

美国还答应出售价值200亿美元的高科技武器给沙特，以应付伊朗的军事挑战。而以色列人对这个军售的风险还是洞若观火，他们害怕逊尼派极端分子已经渗透进沙特的陆军和空军，结果还没等沙特和伊朗人开打，这些人已经先冲以色列人开火。有以色列的情报说，曾有基地分子坦承他们已经可以控制数架沙特空军的F-15战机，可以随时发起对特拉维夫的恐怖袭击。而在头一批供应沙特的军火中，大约有9百个改装袋，可以把常规的炸弹改装成激光制导炸弹或者卫星定位系统导航的智能弹（Joint Direct Attack Munitions ，即JDAM）。

以色列的担忧不是没有根据，但其主要目的是对美国政府施加压力，保持布什总统不会改变他许下的任何巴以和平协定都不会让以色列退回1967年中东战争分界线的承诺。而沙特所倡导的和平计划的核心就是回到那个边界。而今美国同沙特走得如此亲近，不免令以色列担忧其基本利益会被牺牲。

另外，美国政府同意出售核技术并帮助沙特发展自己的核计划，以换取沙特不再通过巴基斯坦获得核子技术。这个决定同样引起了美国国会的疑虑。因为很多美国政界中的亲犹太人势力觉得沙特还没有完全证明是自己同一条战壕里的战友。纽约州参议员舒默甚至指责在国际油价高涨的时候，沙特没有帮助美国朋友过关。在08年5月，舒默在国会的演讲里，更扬言要在国会通过法案阻止对沙特的军售，除非沙特可以增加每天一百万桶石油生产，让美国的每加仑汽油价格可以下降50-75美分[fn:jdwtdayx04556]。只不过布什在08年1月对沙特访问时，他的情石油增产的请求，被沙特国王轻轻松松的一句话给拒绝了——沙特国王告诉布什总统，他的国家已经是全力在开采石油，没有任何的多余生产能力了。

[fn:jdwtdayx04556] 由于有长期的国外能源支持和依赖汽车的消费习惯，美国汽油长期维持了低价传统，一般在2美元左右。2008年6月原油价格达到140美元/桶的高位时，美国汽油平均价格达到每加仑4美元的较高价位（约合每升1.06美元）。每加仑下降50-75美分是很大的降幅。——编者注。



图4.1 布什在08年初紧急访问沙特，希望沙特增产石油

这还算是客气的。对英国人，沙特人就没有这么礼貌了。在1989年，沙特从英国购买了价值430亿英镑的军火，但在911事件及美军入侵阿富汗后，经手这次采购的沙特王子班达尔苏丹被英国内部线人爆料，从英国军火商英国航天系统公司（BAE）收取了10亿英镑的回扣。班达王子本人出使美国超过二十多年，和布什和切尼的私人家庭关系极为密切，但就在911事件后，被纽约市长朱利安尼拒绝他为死难者的捐款。现在班达王子在父亲成了王储之后，更上一层楼，出任沙特王国的国家安全会主席，自己也富甲天下，有什么必要贪污呢？据对沙特王室财政运作熟悉的人士，班达自己的账户、沙特驻美国使馆的账户、和沙特王室在美国的账户，从来都不分。看起来当初这笔黑钱的目的似乎是有其他不可告人，也不能公开的目的。而这些目的就成了911事件后，“有心”人特别想爆出来的动机。但在2006年底，也就是美国和沙特开始重修旧好的时候，英国政府单方面宣布停止对这件贪污案的调查，因为调查下去，“有损于英国国家利益”。对这个宣布，英国政界当然有人不满，尤其是在野党政客趁机攻击执政党在这个案件里的个人利益。欧洲经合会也对此不满，决定开始自己的调查。而沙特对英国的回应是，如果英国人在这件事上继续咬住不放，就会影响沙特与英国在反恐战争上的合作。考虑到大部分国家恐怖分子都是来源于沙特阿拉伯，如果没有了沙特政府的合作，那英国就等着伦敦被人多炸一次吧！[fn:jdwtdayx04557]

[fn:jdwtdayx04557] 英国《卫报》在2008年2月15日报道“秘密报告透露来自沙特王子的威胁”（Secret papers reveal threats from Saudi Prince）。伦敦曾于2005年遭遇袭击。 

图4.2  沙特国家安全顾问班达王子警告英国少管闲事

英国人当然知道其中的厉害，得罪沙特阿拉伯的风险实在太大。连纽约被撞得稀巴烂的美国政府都当没事了，而且美国媒体都不愿意踩这趟浑水，英国也就没什么必要在这个小事上纠缠下去，只是要求沙特看紧来自巴基斯坦部落区的默哈加丁（Muhajadeen）[fn:jdwtdayx04558]，让他们不要再“访问”英国。

[fn:jdwtdayx04558] 默哈加丁，Muhajadeen，是指巴基斯坦与西北阿富汗沿线交界地区一代出身的宗教战斗人员。在80年代的反苏战争、阿富汗内战和90年代以来袭击美国的一系列活动中有所参与。

+ 三十六

沙特对中东和自身的安全考虑大概有以下几条思路：

1．让整个中东成为非核区。但是这个选择不可能，因为以色列不干，自然所有西方国家也都不同意。

2．因为1走不通，沙特就必须有自己的核威慑力量。这种力量，可以是自己发展核武，或者由核大国提供保护伞。

3．本来，这个核大国就是美国。但是，因为911事件后，美国内部有人对沙特不满，光靠与美国政府现在的官员的私人关系来维持核伞，似乎不是上上之选。

4．所以，一个可以信赖的核大国，比如巴基斯坦，就更有吸引力。巴基斯坦同为穆斯林，而且还是逊尼派，国家又不是太富，同宗又满口袋钞票的沙特就更有挥洒的空间。

所以说沙特肯定不会走回对美关系一边倒的老状态，而在美以联合对付伊朗的行动中，沙特更会采取一种隔岸观火、火中取栗的姿势，希望让犹太人和波斯人两败俱伤。而美国对沙特这种态度的应对，就是一方面答应帮助沙特发展自己的核工业作为甜头，另一方面又在巴基斯坦利用北约军队和阿富汗傀儡军四处点火，给巴基斯坦和中国压力，阻止巴基斯坦核力量伸进中东。

就原油这个最终目的来说，伊拉克的原油至少有1150亿桶，而目前采油只在相对稳定的库德族地区进行，由一些北欧和土耳其的小石油公司在运作，出油量达到了200万桶一天。但是这些产量产生的300-400亿美元收入只够伊拉克政府自己分钱，而美军大量的军费开支和重建工作远远不止这个数目，光2007年就花掉了美国3680亿，丝毫也没有减轻的迹象。美国议员们气得在国会骂街，要求伊拉克至少自己支付重建费用。目前埃克森、雪佛兰、BP和英荷壳牌等大油商还在等待，想着局势稳定后齐心合力地把每日出油量提到600万桶，可在美国布什后的新政府的伊拉克政策定型前，他们能做的就是等待。

而美国政府在这一段时间里的主要考虑就是如何把被伊朗抢去的优势夺回来，然后再如何通过对伊朗核计划的炒作而实现对其国际经济制裁，重新树立美国不可挑战的中东霸权。

美国在伊朗的经济制裁基本上是杀人一千，自伤九百。当然，由于美国本身目前并没有和伊朗的任何经济联系，所以它推动的经济制裁是主要通过逼使欧洲的英国、德国和法国等来到达最终目的。但是，对伊朗的制裁，就和美国这几年对朝鲜的经济制裁一样，绕不过中国这一关。美国制裁的结果，不光是迫使伊朗退出美元经济，而且还使伊朗经济与西方经济体系如欧洲的联系逐渐中断，而与东方尤其是中国的经济联系越来越强。一旦伊朗的经济在将来完全依靠和东方的贸易生存，将来的伊朗在政治和外交就更难以产生一个亲西方的政府。而如何产生一个亲西方和亲美的伊朗政府，本来是美国对伊朗颜色革命的最大和最重要目标。也就是说，美国的经济制裁似乎产生的是一个反效果，使伊朗的强硬派的地位越来越稳。


+ 三十七

要了解今天的美国和伊朗的仇恨，就要从美国中情局在 *1953年* 发动政变推翻伊朗民选政府说起。

当初，伊朗独立后，民族主义情绪高涨，当时的民选政府不得不考虑将伊朗石油国有化，或至少在英国拥有的盎格鲁-伊朗石油公司（Anglo-Iranian Oil Company）里分多一点。而在此之前，每当伊朗政府对英国肆无忌惮的掠夺稍有不满时，英国都会运用军队推翻伊朗政府改而扶持一个新的傀儡政府。不过，到了1950年，虽然英国在伊朗仍然有很多亲英势力，但当英国的新一轮政变计划被伊朗政府在英国驻伊朗大使馆发现时，所有英国的外交官（也可以说是间谍）被伊朗全部驱逐出境。

被赶出去的英国佬，当然非常恼火，先是对伊朗石油出口进行禁运，造成伊朗经济重大损失。但是这个民选的摩萨台政府，就是不肯将石油工业控制权重新交还给英国，只愿意就英国应该享有的分红进行谈判。于是英国首相邱吉尔决定出兵攻打伊朗，但是可惜时世变迁，英国已经不再是世界老大，所以邱吉尔就向美国总统杜鲁门请示，可不可以让英国出兵伊朗，倘若美国不肯，是否可以由美国政府利用其驻伊朗的大使馆出头，然后让英国在伊朗的势力配合，搞一场政变。

杜鲁门一口拒绝了英国佬的提议。因为当时的美国还想拉拢新独立的世界各国，意图建立一个美国主导的国际新次序，当然要同臭名昭著的老牌殖民帝国主义划清界限。所以一直等到好战的艾森豪威尔政府上台，邱吉尔的这个提议才得到实施。计划的领军人物是美国总统西奥多·罗斯福的孙子小罗斯福，时在美国中情局中东分局任职。接受政变的任务后，小罗斯福以假身份证偷渡进伊朗，在英国情报局地下组织租用的地方藏身，开始组织政变行动。
  
图4.3 三个罗斯福。左：西奥多·罗斯福（美国1901-1909总统）；中：科明·罗斯福（中央情报局头目）；右：富兰克林·罗斯福（美国1933-1945总统）。三人关系是“爷爷：孙子：远房叔叔”

其间小罗斯福差点不慎暴露了自己是名门之后。他时常去土耳其大使馆的网球场打球并接触联络关系。有一次，一个球没有打好，他脱口而出：“啊，罗斯福！”结果打球的同伴们问他怎么会有这么怪的感叹方法，他只好编个谎话说他是个很忠诚的共和党员，在他长大的共和党地方支部，因为大家很恨罗斯福这个混蛋民主党总统（富兰克林·罗斯福总统是他远房叔叔），所以人人都把“罗斯福”当成“他妈的”来做为粗口。[fn:jdwtdayx04559]

[fn:jdwtdayx04559] 这些细节均来自科明·罗斯福的自传《反政变：控制伊朗的斗争》。

结果在美国大使馆的主导下，小罗斯福利用伊朗的亲英势力终于把伊朗的民选政府推翻了，扶持建立了巴列维国王政权作为美国的傀儡。当然，由于美国的出力，英国无法再独自拥有盎格鲁-伊朗石油公司，于是进行了改组，主体变成了现在的英国石油公司（British Petrol，简称BP），并容许其他八家西方石油公司分赃。

*这个成功的政变，对世界历史具有重大的影响。* 一是经过这次政变，让美国找到了一个经济而有效的方法去推翻一个自己不喜欢的政府，而中央情报局就成了美国外交政策的决策中心。结果此后第二年就发动了危地马拉政变，然后中情局介入了几乎每一个中美洲和南美洲的政变。在中国，美国中情局也很快成了达赖喇嘛的老板，在印度和尼泊尔遥控在中国的颠覆活动，一直遥控到尼克松访华为止。而在1990年后，由于中情局的恶名远扬，其颠覆他国政权的专家们便改变身份，摇身一变而成为一些所谓“非政府”组织，在全球范围内，为美国的地缘和经济利益大兴颜色革命。据法国电视台的“颜色革命”纪录片的披露，仅在前苏联的加盟国，这些“非政府”组织就投资超过了一亿美金用于中情局革命。


+ 三十八

*另外一个重大影响* ，就是这个1953年政变，埋下了伊朗1979年的伊斯兰革命的导火索，并带动了整个穆斯林世界的反西方思潮以及今天伊斯兰世界针对西方的极端恐怖活动。

  
图4.4  美国1953年推翻伊朗民主政府的政变，是中东恐怖主义根源之一。右图为伊朗领袖摩萨台

本来，穆斯林世界在近现代积弱，和中国、印度等等古老文明国家一样，是在西方通过科学和工业革命带来的强大军事暴力打击下，吃够了苦头。落后就要挨打，尤其是在缺乏基本人性的殖民帝国主义列强面前，很多知识分子和各界精英开始思考民族改革之道。其中不乏很多人接受了西方即是文明的广告台词，天真的以为只要自己放弃民族传统，改变自身文化，全面向西方学习，就会变成一个被西方人尊重和平等对待的国家。所以除了早先中国义和团运动之类的以卵击石的仇外风潮的话，很多人以为只要按照西方的方式运行，那么民族的尊严和国家的独立，就可以得到保证。

但是，看着伊朗摩萨台政府这批完全由西方教育出来，对西方体制佩服得五体投地，心服口服的政府官员们，被西方打下十八层地狱，而被认为是造成伊朗积弱而已被推翻的国王制度，又被西方重新树立起来，伊朗失望和愤怒的知识分子就开始回到他们本民族的传统，而霍梅尼的伊斯兰革命就取得了人民的强烈支持。

1979年的伊朗革命给美国人留下的最深刻的印象，就是美国外交官被扣为人质。当然，所有的美国媒体都会一致攻击伊斯兰革命分子，大嚷这些热血分子抓按理应受到国际法保护的外交官为人质是一种无耻和野蛮的做法。不会有人出来教育美国无知的民众，正是这些文明的外交官曾经在一个主权国家发动政变推翻民选政府。美国随后进行了由特种部队进行冒险救援的军事行动，又以失败而告终，最后只能在两伊战争中，靠偷偷给伊朗武器才把人质换了出来。

今天我们回头看这段历史，自然有不少感慨。其中一点就是为什么在伊朗当时能有那么强大的亲英力量，而且可以强大到推翻一个国家政府的地步。伊朗人对英国人的狠毒是非常明白的，有一句伊朗谚语说，假如你走在路上，被一块石头跘到，那块石头一定是英国人放的。但在英国的长期统治下，手段高明的英国人已经培养出一批伊朗的“英国”人，一旦需要为英国利益而动作，他们就响应而起。尤其是言论自由下的英文报纸里，充满了英国的情报人员，通过媒体散布谣言，比如说伊朗总理摩萨台是同性恋等等，在伊朗制造危机。

其实同样的情况也在印度出现过。印度在1947年独立后，尼赫鲁为首的政府希望能够通过不结盟运动而确立印度的国际地位，而印度本地的精英“英国”人就运用其力量，大举攻击印度政府的外交政策，强烈要求印度参加其宗主国英国参与的北约，给印度的外交政策造成了极大的困扰。

当然中国在收回香港时也面临着同样的问题。好在中国政府曾经有过在新疆，尤其是伊犁地区俄国势力太大的教训，也有在1962年伊犁事件之后清除俄国[fn:jdwtdayx0460]60影响的经验，所以在香港的处理上，亏吃得要小一些。另一个因素是英国的势力今非昔比，而中国也不如当年的伊朗和印度那么好欺负，经过了基本法解释权一役，英国就不再敢乱来。此役，本来为英国人掌控的香港法院（最高法官中九占其四，上诉法官中21占11，还不包含香港“英国”人）企图以法律至上的名义，抢夺基本法的最终解释权，并以此限制中国掌控的香港特区政府的施政，被中国法理上由中国人大的权威而击退。

[fn:jdwtdayx0460] 这里指前苏联。——编者注。
  
图4.5 伊朗20世纪历史上的三位领导人 左：摩萨台首相；中：巴列维国王；右：霍梅尼教长

图4.6 当时的美国副总统老布什，在迎接美国使馆人质归来

有意思的是，伊朗和印度两国都用了二十余年时间把亲英势力彻底清除，而中国在1997年后，在香港开展了中学为主的国家意识教育，计划在二十年后的2017年才开始放开选举，这无疑是一个聪明的做法。这样的话，一方面中国已经成为一个世界级大国，另一方面香港的亲英人士们大概已经廉颇老矣，再香的政治饭，也已经吃不下去了。


+ 三十九

美国对伊朗的经济制裁，主要是利用美国在世界金融体系中美元的特殊地位，破坏国际经济游戏规则，逼迫世界各国的银行和企业牺牲经济利益来实现美国的外交政策。

本来一个合法的制裁，需要来自联合国安理会的授权，但是很明显的是，由于中国和俄国在制裁伊朗所认同的程度问题上和美国具有很大的差距，最后各方争论、协商和妥协的结果，自然和美国的期望值距离太远。于是美国通常会自己搞一套更为严厉的制裁计划，希望通过在世界金融体系里的主导地位，将国际公权力变成一己的私器而为所欲为，甚至不惜以摧毁这个美国国运所依的世界经济体系。

为防止国际犯罪集团利用世界金融体系进行跨国度的经济犯罪，包括如走私和贩毒等等，美国财政部被授予了可以对世界金融体系中的各国企业，尤其是参与洗黑钱的银行调查的权利，并根据调查的结果而宣布制裁，制裁措施包括将其中犯法的银行赶出国际金融体系。其中最具杀伤力的武器，就是任何和疑犯有经济瓜葛的银行都会被列入制裁的黑名单上，而其他银行通常会因为不想失去利润丰厚的美元生意，被迫自动断绝和美国财政部想要打击的银行的联系。

可想而知，在911后的新国际形势下，在美国国会很快就通过了由后来的民主党候选人参议院议员克里提议的法案，利用美国财政部在世界金融体系中的特权，打击恐怖组织的金融活动。本来，这个改变也不是太过分，但是美国政府里的聪明人士，马上就想到了用这个手段来到达军事上无法做到的外交目的。首当其冲的就是朝鲜，但是美国在操作过程中却发生纰漏，在企图用澳门汇业银行杀鸡给猴看，来迫使中国银行等切断与朝鲜的经济联系的计谋中，最终彻底搞垮朝鲜的目的没能达到，却把朝鲜逼得实验了原子弹，这让美国的东亚外交陷入危机。

美国两党并没有认识到这种玩法的危险性，如法炮制来对付伊朗。领导这一行动的是美国财政部的恐怖主义金融情报办公室（OTFI，Office of Terrorism and Financial Intelligence）主任赖维，其主要任务就是走遍世界上任何一个和伊朗有生意往来的国家，利用一切方法，包括威胁，使这些国家断绝与伊朗联系，而达到在经济上孤立伊朗的目的。

俗话说，一条铁链的强度就在其最弱的一环上决定。美国对伊朗的经济和金融制裁，最弱的一环当然就是在中国。而美国能依靠的主要力量，还是他那个心不甘，情不愿的欧洲盟友，其中最重要的就是当时伊朗最大的贸易伙伴，在伊朗有巨大经济利益的德国。德国作为当时对伊朗贸易的最大出口国，光一年出口的产品的价值就达到55亿美元。当然很多厂商不愿意德国做出超过联合国法案要求的制裁，搞得和自己的钱包结仇，而德国各级政府也要顾虑减少出口而带来的工作职位的损失。但是，德国难拒美国的压力，又因为总理默克尔极度亲美，所以最后决定与美国合作，对伊朗实施经济制裁。不过德国人也向美国人表达了其内心的忧虑： 如果不是所有的国家都同心合力，有人乘机在其中抢占德国让出的伊朗市场，那就会不但使制裁达不到效果，而且把制裁伊朗变成了制裁自己。

德国人的担忧并不是杞人忧天，在德国参加制裁行动后，中国就轻易的变成了伊朗的最大贸易伙伴，拿走了德国自己空出的市场。伊朗的石油也主要出口到亚洲的中国和日本，而美国最想打击的伊朗经济环节——外资对伊朗能源工业的投资，也出现了中国为主，亚洲各国跟进的局面。


+ 四十

当然德国人不是一开始就没有试图抗拒美国的要求。德国人先表示理解美国对制裁的坚持，因为美国和伊朗几乎没有什么经济联系，而德国既然有那么多生意，有自己的苦衷，所以就不应该去完成比联合国要求的制裁更多的任务。不过，美国不会接受一个“不”的答案，尤其是仍然有美国驻军的德国。美国人的回答是，难道你德国政府坚持支持恐怖分子吗？难道你会继续让伊朗人发展核工业，对犹太人进行“再”一次大屠杀吗？[fn:jdwtdayx0461]

[fn:jdwtdayx0461] 这里指美国把德国和伊朗做生意说成是支持伊朗，并把此和当年纳粹德国的灭犹行为并列，以此“政治正确”的原则来压德国就范。

等到犹太人这张牌打出来，德国人就不敢再多嘴了。于是德国政府乖乖地将政府的出口保证信用取消，使出口伊朗的德国企业没有了政府的收款保证。然后，美国财政部的官员，绕过德国政府，亲自上门，一家一家的敲开任何和伊朗有关系的企业，把一封封美国财政部金融制裁的恐吓信递交进去，大约在2007年年中，终于把德国对伊朗的出口打了下来。看德国对伊朗的出口，在2005年同比增长24%，达到44亿欧元，在2006年下降了7%，回到41亿欧元，到了2007年，因为美国的干扰，进一步下降了13%到36亿欧元。[fn:jdwtdayx0462]

[fn:jdwtdayx0462] 本文写于2008年6月，后因为美国势力在2008年减弱，德国人犯法的胆子大了点，使得该年德国对伊朗出口增长8.9%，达到39亿美元，仍然落后于2006年的水平。——编者注。

德国人所能做的就是马上把其他的“犯法”者指出来。德国媒体大幅度报道了法国企业如标致、雷诺和道达尔等大企业继续在伊朗运作的事情。德国外交部还公布了美国的企业如微软、卡特彼勒、可口可乐和百事可乐等，都以迪拜分公司的名义在伊朗运作，却又不受美国制裁的影响。当然最有力的说明，就是在德国对伊朗出口大幅度下降的同时，中国的对伊出口却是大幅度上升。如果美国不能解决这个问题，德国人就会大喊不公平。

那么美国如何解决这个问题呢？上次朝鲜制裁的丢脸还没有解决，这次似乎应该有不同的方法。本来美国的原先考虑是，利用欧洲的银行对中国同业施加压力，让欧洲银行对中国的几大银行说，如果你不停止和伊朗人做生意，我们再和你做生意就会被美国财政部制裁，最后不敢和你继续玩，你觉得伊朗那一点生意值得牺牲我们之间的大生意吗？计划得倒是不错，但欧洲的银行没有人愿意出这个头。于是美国财政部绕过中国政府，偷偷地威胁这些中国的银行要在他们的美国业务中下绊马索，让这些银行自己考虑考虑。

美国主要想打击伊朗利用信用（Line of Credit）做生意的经营方式。由于美元为基础的企业信用最终要在美联储的纽约分行结算，美国就可以很容易知道，哪家国际银行在为伊朗企业提供信用，这就可以威胁这些银行使它们的美元生意受到打击。结果，中国的银行也不想得罪美国人而影响自己的生意，就减少了对伊朗企业的信用提供，导致伊朗不得不派出代表到中国去协商，可不可以建立一个中国-伊朗银行，专门用来结算两国之间的贸易。对这个提议，中国没有采纳，因为还不想与美国彻底撕开脸面。于是中国的企业和伊朗的企业，就采取了三个暗渡陈仓的方法：一是退出美元系统，采取欧元结算的方法，这样就可以不需要在纽约结算；二是采取欧洲比利时的斯维福特（Swift）系统，用电汇转账的方式；三是让伊朗企业采取在迪拜成立影子公司，以中国和阿联酋的贸易作为名义，来代替公开的中国和伊朗的贸易。

很快欧洲的其他想和伊朗做生意的公司也换成了欧元结算以逃避美国财政部的追杀。而美国对欧元的结算并没有法律上的管辖权，必须让欧盟的所有国家的法律进行修改，才可能做到，可想而知其难度之大。另外美国完全无法知道，到底谁在“犯法”，所以没法进行制裁。而对保密至上的斯威夫特系统，如果一旦必须向美国政府提供客户信息，这个系统就无法再运行下去，所有欧洲国家会在这上面同美国决一死战，并指控美国只不过借伊朗的名义打击美国以外的金融组织，为美国的金融企业提供不公平的有利竞争条件。

美国剩下的招数只能是对阿联酋施加压力，要其禁止伊朗企业在迪拜开公司。果然阿联酋通过了一条这样的法律，但是美国人又没办法去核实到底这个法律施行得如何，最后还是你有你的张良计，我有我的过墙梯，唯利是图的商人总是可以发现自己的锦囊妙计。

而美国人的制裁越多，到最后就发现世界上越来越少人用美元，而美国为此将来也许会付沉重的代价。


#+begin_center
【写作日期】2008年6月24日——6月27日            
#+end_center
