# -*- org -*-

# Time-stamp: <2011-08-30 15:29:57 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 【第十篇·崛起】


#+begin_center
【写作日期】2008年7月31日——8月4日  
#+end_center

青丝一束莫笑短，直下长洲缚蛟龙。

--自题

九十一

在具体的操作上，中国在这些地方应该避免和西方直接交锋，而由当地的国家扮演对抗的角色。中国要做的是每当西方要对这些国家下手，采取各种敌对行动的时候，做好应对的方案，使西方的行为不能如愿。例如津巴布韦就是一个最好的例子。这里中国依赖于南非和南部非洲发展组织的运作，成功的防止了西方势力一次对非洲的强力介入。如果中国能够和南非共同努力，促成津巴布韦政府当权派和反对派的和解，让南非总统姆贝基好好露一脸，使非洲人可以真正的处理非洲事务，那么中国就能够在南部非洲获得稳定的支持，为本国和当地的经济的持续发展，提供良好的社会环境。

在经济上，中国应该利用自己在农业科研上的优势，帮助津巴布韦的黑人发展农业经济，使这些非洲国家可以摆脱被长期以来欧洲白人通过控制农业技术，垄断经济命脉的局面。通过和中国的出口贸易，西方针对非洲国家的经济制裁将不再有实效。更重要的是，令西方尤其是欧盟各国企图通过这些白人势力控制非洲国家的政治和经济的算盘落空。

而在另一方面，中国又需要争取西方的合作，在替代能源和再生能源方面，加强共同开发，使中国和西方双方对化石能源的需要降低，以避免引起过度的恶性竞争。

中国最好的位置应该是在西方阵营和反西方国家之间摇摆，利用自己的特殊身份，扮演一个中介的角色，既让西方国家忙于应付这些所谓“捣蛋”国家的挑战而无暇思考对付中国，又可以令中国在他们的冲突中，通过两边施压或施援，来化解冲突的白热化，从中获得利益。

在伊朗危机上，中国的处理方法，是一旦美国摆出强硬姿态使对抗恶化，中国就需要增加和伊朗的合作来减低美国对伊朗的压力。而一旦伊朗的强硬派向美国挑衅，中国就警告伊朗使其行为避免过激。总之，中国的对策是不和任何一方势力公开结盟，也不排除和任何一方势力有限度的合作，使自己的利益在各种冲突中最佳化，通过灵活的变化，不断化解各种冲突，使之不至于失控，造成整个国际体系的崩溃。

当然，从2008年的形势来看，中国已经无法躲过西方的关注。逼迫中国表态，支持西方统治的现有国际体系，并利用中国的特殊身份和日益增长的经济实力和政治影响力，为西方利益服务，当是西方的首要选择。在这种形式下，以资源争夺为契机的运作，在中国黄海、东海和南海，用与其说是真正的为资源不如说以此为契机的目的，来恶化中国与东亚和东南亚周边国家的关系，阻碍中国和这些国家经济和市场的一体化，打击中国在这些地区日增的影响力。

而在中国内部，所有的对策都是削弱中国政府的权威为目的，以台湾、新疆、西藏及历史问题作为操作平台，企图增强中国因为改革开放向地方放权引致的中央权威下降的趋势，通过对民主、地方自治、民族自决的鼓吹，在中国内部各地域中，支持分裂、分离和离心势力，在所有中国的外交和国防政策启动政策争吵，挑动高姿态的爱国主义势力和西方支持的颠覆势力之间进行公开直接摊牌对抗，来压缩中国在国际外交上的斡旋空间。

在舆论上，则是施加压力，企图让中国政府在无准备的情况下仓促上马政治改革，试图再次上演前苏联解体的一幕。令中国政府陷入各种内部公开化的争论中，无端消耗精力，让目前中国内部经济发展不平衡带来的地区差异在媒体上不断夸大，企图在沿海和内地、东部和西部、城市和农村以及不同族群之间进行挑逗，让相互之间爆发公开的争利斗争。其用心在于让摧毁大家都认可的起仲裁功能的中央权威，方便操作，达到分裂中国的意图。


+ 九十二

*中国的政治实践中，有一个非常特别的现象，就是普通民众对中央政府有不可动摇的信心。* 这种信心是许多西方学者非常困惑和不解的。从他们的政治经验里，他们不会对自己的国家领导人有这种信任（当然除了美国之外，大多数西方国家的领导人也只不过相当于中国一个省长而已），但这些西方人却对他们的最高法院具有不可怀疑的信任，而绝对服从最高法院作出的仲裁。

其实中国的中央政府在民众的心目中，也起了这个西方最高法院的作用。中国传统历代王朝都说明，这个最高权威是不能被怀疑的，一旦被怀疑，那么这个社会就要陷入大动荡。在中国进行任何的政治改革，都必须考虑到这个因素，任何以削弱中央政府在人民中的权威的改革方案，对中国作为一个统一的国家来说，都是一个自杀行为。1911年的革命，推翻了清政府的权威并结束了帝制，但新建立的共和国试图用加强地方自治的民主制度，来构建新的中央权威，结果失败，造成各地军阀和地方势力事实上独立的状态。而日本在这个时候入侵中国，结局正如汪精卫所描述，中国只有各省的省防，但却没有国防。这种情况下，中国作为一个没有统一政治力量的国家，当然无法应对外强的挑战。反之，中国在1949年后再次建立起中央政府的权威，形成了一个统一的政治力量，就可以以当时的微薄之力，居然顶住美国及其同盟在朝鲜的军事干预。

有人问以中国当前的政治体制，可否成功崛起以应付西方的挑战。笔者曾用了一个类比，中国人，中国青年一代，在08年春天在西藏和地震后表现出来的那种发自心底的自信心，那种没有任何什么事是不可能的态度，与美国在五十年代的“无事不可为（Can Do）”的自信非常相象，只是在规模上乘上10而已。而美国当年的政治制度与今相比，只要看看到1940年还有数百万黑人被美国地方政府公开做奴隶的这个事实，就知道中国的今天比美国当年不知要进步多少。如果美国当年可以成功的在世界崛起，那么就没有理由怀疑中国以今天的政治制度不能做到同样的事情。

*中国在政治改革的领域里，一定要区分体制改革和机构改革，并把重点和先发点，放在提高政府效率的机构改革上面。人们通常把体制改革和机构改革混淆而混为一谈。机构改革，也称行政制度改革，其着重点在于对行政部门的运作，对其效率和权责等方面，进行民主化和科学化的调整，以提高政府管治水平。通常一个政府的运作是否有效，和其产生的方法有一定的关联，但并不是绝对的因果关系。这也是为什么新加坡和香港的政府，在效率和廉洁上都名列世界前茅，但如果用选举的民主程度的标准来看，则根本无法和其他国家地区如台湾、韩国、菲律宾等比较。*

所以需要弄清楚人民到底抱怨的问题是在体制上面，还是在机构上面后，中国政府才可以对症下药，采取切实有效的手段，来提升现在普遍过于低下的政府管治能力。在提高对政府官员监督方面，香港的廉政公署，是一个比较成功的机构，其运作方面，颇似中国明朝时的东厂，在人员构成、组织关系和财政来源上，都独立于其监督的政府机构之外，对被其监督的政界和商界，具有极大的阻吓作用。


+ 九十三

*但是廉政公署虽然有很大的正面作用，但也存在缺点，一是在于采用秘密行动的方法，因此在信息公开和舆论导向上具有滞后性；另一缺点是它属于“秋后算账”，只能对政府的腐败行为和商业犯罪起追讨效应。为了弥补这些不足，对政府部门的施政过程就必须有超前、放患于未然的机制。*

*香港政府的做法是，定期由政府部门主管向民选（包括功能组别推举）的立法会进行政策说明和解释，并接受议员的公开质询。公开质询的内容，不光有专门部门的即时计划，还包括未来的计划和过去工作的总结，这使官员问责制可以落到实处。这些措施，都可以在中国现存的人民代表大会和政协的机制里施行，而不需要太大的体制改变。把这些问政、听政和督政的形式程序化，就可以提高施政的公开和透明度，使官员腐败和官商勾结的空间被压缩，这样廉政公署的有限功能就可以弥补不足。*

在具体领域的监督手段上，应该有效的利用新兴媒体，如互联网的快速和广泛性，防止地方上的贪官污吏只手遮天，逼迫民众去靠把事闹大来得到高层的关注。地方政府的机能改革，即政府精简繁琐的规章，将经济活动的管理权交给社会，可以使政府利用决策权为私人从中牟取暴利的机会减少，而这又有待市场经济的发展完善。

*贪污腐化、官商勾结和商业犯罪，应该是监督的重中之重。 但是我们应该清楚的明白，凡是有人的地方，就会有腐败。任何措施的目的，只是把这些腐败控制在一个社会可以接受的范围之内，而不会造成太大的社会代价。要知道，在人类的任何社会中，财富和资本的积累，都是无耻和血腥的。无商不奸，无富不恶，基本就是人类放之四海皆准的真理。在中国这三十年的发展中，不排除许多有钱人是靠黑起家，当然更多的是利用计划经济和市场经济的双轨制的灰色地带而暴发。对大量侵吞国家和人民财产，造成社会巨大损失的蛀虫，当然要深究到底，但是要避免社会中的普遍仇富心态，把运动扩大化。*

可以想象，一旦心态普遍到失控的地步，盲目的民粹主义兴起，对这些年发展的过程中产生的贫富分野，自然会有清算和公平的要求。那些靠灰色地带暴发的富人，立即就会卷款而逃，走到加拿大之流的国家，直接把中国人的财富“捐给”外国人。即使象赖昌星之流的罪犯，加拿大都可以找出各种理由来挽留他，以中国侵犯人权为借口，拒绝对其遣返。恐怕是要等赖某人以高昂的律师费的形式，将他带到加拿大的赃款（中国人的钱），全部变成加拿大人的钱（法律费用）后，这个拔河才会告一个段落。这样看来，最后的结果就是把中国人的财富，用小鬼搬运法的伎俩，移花接木，变成加拿大人的财富。

中国人不能落入这种发生在其他发展中国家如拉美国家的陷阱。 *中国人必须做的是，保持国家的政治稳定，不要有政治动乱。鼓励这些财富在中国本地进行投资活动，创造就业机会。另外通过宗教的感召力，或者是自然灾害（如汶川大地震）的同情心，使这些利益享受者，可以通过慈善事业、福利捐款等等，来补偿其对这个社会应尽的责任。中国政府还可以通过税收杠杆，鼓励这些私人资金办学，开图书馆，建养老院等等。正如历史上很多祸害人类的家族，如诺贝尔家族、洛克菲勒家族、卡耐基家族等等，都在通过这种形式对社会作出应有的补偿。*


+ 九十四

*中国从古到今的传统，就是政治统一、经济独立和文化多元。* 如何保持和完善这个体系，是中国人必须深刻思考的问题。自从1840年以降，中国经历了耻辱的100年，饱受列强侵略、传统沦丧、国破家亡，不得不学越国的勾践卧薪尝胆，奋发图强。这个向西方虚心求教、不耻下问、忍辱负重，甚至低声下气的态度和过程，是值得肯定的。但是任何学习，都有个目的，就像你上大学，不过是学一门本事，拿一个毕业证书作文凭。以今天的情形来看，在学了西方150年后，中国人已经有能力保护自己的家园，已经不再那么轻易的可以被西方军事讹诈。而中国的经济，已经开始恢复在鸦片战争之前世界超强的地位。 *那么我们干嘛还要向西方继续学习？难道就是为了学习而学习没有其他的意图？或者是只要西方有的，哪怕是些垃圾，我们都要老老实实的拿回家里来当宝贝供着？*

是不是西方人大喊一声，这个是普世价值，我们就连脑袋都不挠一下照单全收？是不是西方人高呼跳啊，我们就要问到底要跳多高？是不是一个破章程，有几个西方国家签署了，我们就一定要跟着签？

*中国人已经到了一个必须用自己脑子想事情的时候了。* 不要动不动就号称，要向世界看齐，要和国际接轨。殊不知，如果你自己在家里铺一条快速有效的高速路，人家就会当你是国际标准，要和你接轨。中国需要的不是自高自大、孤芳自赏和目光短浅，但是也不需要妄自菲薄、自惭形秽和诚惶诚恐。 *中国人应该对自己今天的政治制度和社会结构，充满自豪和骄傲，为这三十年的史无前例的辉煌成就而欢欣喜悦，当然同时要保持冷静的头脑和平和的心态，以一个外科杏林高手的敏锐目光，认真的对我们今天的社会进行仔细的分析，随时对其进行手术和修补。*

*中国今天最大的问题是人才的缺乏，任何完美的制度在低水平的人才操作下，都是事半功倍。* 中国这个年纪人才的断层跟六十年代文化大革命有关，那时大批年轻人被一车子拉去上山下乡，向贫下中农学习，因而被剥夺了真正的教育机会。因此对他们，我们应该有同情心，并且可以理解目前由他们为主，在中国当前社会的政治和经济领域操作中，水平偏低的现实情况。比如我们金融界“高手”们在黑石上市和摩根斯坦利等等的投资，可以被称为土包子交学费。比如我们某些东部沿海地区的官员们，在美国文化势力衰退，需要依赖引进中国文化因素（如功夫熊猫）来混饭吃的今天，仍然热衷于引外资让土地花大钱去修建迪斯尼乐园。他们的希望是，用中国人的资金、中国人的土地和中国人的顾客，来向美国人交专利费。可以想象的是，当上海附近的省份的人民，缺乏上海人民那副热爱外国人的媚态而不鸟你的时候，你这个美国大乐园可以去骗谁的钱。

以笔者愚见，目前中国在这些方面，还是越少变更越好，让中国人民可以安安稳稳的忽悠过这几年。 *如果中国能够在当前世界经济陷入低潮，美国和欧洲同时出现衰退的情况下，能够集中精力在经济发展上，压住通胀，保住增长，发展自己的高附加值工业，完成沿海经济从出口型向内需型的转型，忘掉奥运会这些虚名，切实地保持繁荣，就可以满意的给自己盖棺定论，把大规模的变革留给下一代去做。*


+ 九十五

与许多我的同代人的观点不同，笔者对中国的“70后”和“80后”非常看好。这一代人和中国当年周恩来和邓小平代表的那一代人很相似，他们中不少精英分子有良好的教育（包括许多在西方留学）和对作为中国人的自豪感。就像能说流利英文和法文的周恩来们一样，这一代的年轻人知识渊博，见多识广，不像五六十年代出生之人，言必称欧美，物必叹洋货，盖个破房子也要欧陆风情，搞得你不知道还以为生活在法兰西城堡里。

对这些与笔者同龄的同胞对西方文明那种一看见，一听说，就开始两眼发亮，面带红光，呼吸急促，嘴角流涎的姿态，笔者只有摇头苦笑。通常一个黑人想叫自己的儿子学音乐，马上就会拿一把萨克斯风，开始吹黑人的蓝调。一个拉美人马上就会拿一把西班牙吉他，开始弹古典弗拉明戈。而我们的这些中国同胞，倒会拿起个西洋的小提琴，开始拉莫扎特。记得一个黑人曾为此感到困惑，问笔者是不是中国没有自己的民族音乐和乐器，因为他记得走过唐人街的时候，还看到有人拉“两根弦的中国小提琴”。笔者答道，不是，中国的乐器比西方的还要多，中国的音乐源远流长，博大精深，只不过这些人在西方的学校里学多学死了，觉得中国的东西是垃圾而已。

可以想象如果中国的社会由这帮人设计的话，不知道中国会不会变成19世纪的欧洲？反正现在整容手术和磨皮技术都很高超，完全从房屋、街道、衣物、用品、语言（反正我们都会英文，那怕多么洋泾浜）、文字（记不记得汉语拼音化的主张）和相貌（整容没问题，可能身材改造上需要多点功夫，不过所有人都可以光顾美国快餐店恶补荷尔蒙鸡）等等彻底改变，创造出华兹华斯[fn:jdwtdgyx1099]笔下的英国完美乡村社会。

[fn:jdwtdgyx1099] 华兹华斯，W Wordsworth，(1770-1850)，英国浪漫派诗人，喜欢用诗歌描绘田园景色。

所幸的是，中国的社会已经呈现多元化，在民间无需论资排辈，由于这个年龄层英才奇少，对中国的影响（或说是危害）没有那么大。

这个年龄层中滞留在海外的那批人士，多数经过多年的奋斗，不论是学高八斗的博士，还是一个英文都不识的草民，都已混到有车有房，有地有产。这些人吃苦耐劳的韧性，倒是可以和今年初雪灾时的民工相比，且毫不逊色，大有我中华民族勤劳奋发的底蕴。他们对工作也有一种平和的态度，不论是各行各业，高低贵贱，都可以坦然的面对而不会怨天尤人。而且还可以在这些往往不尽人意的职业中，靠踏踏实实埋头苦干，获得些成绩，也算事业小成。他们差不多都上有老下有小，拖家带口，基本上都能够尽孝道，体现中华民族的传统美德。由于对自己的能力通常有某种过低的评价，加上对出头的谨慎，因此有多大的头就带多大（更多是偏小）的帽，不求矮子强出头害人又害己。在他们身上体现了中国人最美好的职业道德，在工作中不偷懒和不掺假。而他们的处世哲学，则带有强烈的大动乱时代的烙印，不轻易出头，因为怕枪打出头鸟，而且还有中国传统的内涵中，那种隐忍不发的沉静。

这些可爱的品格，用在对的地方，就给他们如虎添翼，但如果用在错的地方，就使他们自废武功。可以说他们在美国这种国家的成就相对于欧洲和日本，要大的多，但仍然是没有发挥出应有的潜力。


+ 九十六

当然在美国乐观和夸张的文化的氛围下，他们这种深藏不露的品格，往往就成为一个包袱。当他们和美国人竞争时，人家是三分墨水上大红，有一点颜料就要开全球连锁的印染超级市场。而谦逊自卑的中国人，就生怕自己显露得太多，做不到价廉物美，不被人接受。

这种姿态非常明显的表现在中国的饮食文化上。色香味俱全，丰富文化内涵的中餐，居然搞到便宜得可以和麦当劳的汉堡包争宠。而各方面都要比中餐低几个档次的日本寿司，居然敢以高过中餐两倍的价格叫板，而且还是门庭若市，甚至食客之中出人意料的包括那些只肯吃便宜餐的中国人。档次稍低于中餐的法国餐和意大利餐，则干脆敢叫天价，忽悠到让你觉得花不了大钱就想死。试想一下一个连你自己都当垃圾对待而不珍惜的文化，又叫外人如何敬仰？当然笔者也见过这代人的豪杰，靠天不怕地不怕的蛮劲，居然就是硬打出了一片天。尤其是在美国高科技界里那些中国人的创业者更是如此。没有他们，我们这一代人真的是无地自容，连个遮羞布都不配有。可惜的是，这些栋梁之材不一定对在中国干事业有兴趣，不然真是中国现代化的一大助力。

而流落海外的那些对在中国“干事业”有兴趣的少数的政治精英，如果有机会执政，那就会将是中国之祸。那些人既不了解西方，又不了解中国，还以为自己在将来的中国政坛上仍然有希望，对他们同辈在中国政坛开始接班颇为不服，大有舍我其谁的自负心态。平心而论，这里面不乏一些人有点才气，但就是自视过高，眼高手低，志大才疏。虽说现在上台的那些同辈不一定比他们有才华，但就一定比这些人要务实。如果这些人没有流落海外，估计又是批搅泄物棍，成事不足，败事有余。

不要以为笔者对他们有偏见，其实这些人除了到处寻找经济老板，基本上无一技之长可以在西方谋生。他们写篇文章倒是人权、民主、自由、平等、博爱、普世价值等等统统上，通篇都是高屋建瓴的大鎯头，对着你一顿乱砸。但是字里行间，挑灯细看，却是文化大革命的大字报水准，尽泼妇骂街的能事。最可笑的是，这些人号称对中国文化精通，却连一篇打油诗都凑不出来，号称对西方社会了解，却连美国历史都没有读过。

而中国的新一代看到的是中国高速发展的社会，经历的是划时代的变化。在他们看惯了北京、上海、广州和香港的街景，很难想象他们会在纽约、巴黎、伦敦和柏林像他们的父辈那样跌掉下巴。在看到中国不足的地方，他们也会有有能力改变的自信，不至于像他们的父辈那样天天想当场找个洞钻进去。他们对中国传统的坚持，更是让笔者肃然起敬。看到他们在西藏事件后在互联网上对西方媒体的反击，更是令人由衷钦服。本来唯一的担忧是，他们由于多是独生子女，也许太个人中心主义，对他人的处境缺乏恻隐之心。但是这种担心在他们汶川大地震的表现中一扫而空，令人为中国的未来信心倍增。

*如果一定要在他们身上挑刺的话，那就是勇猛有余，冷静不足。当然以他们的黄口白牙，青春年少，要做到心不浮、气不燥，老成持重是不现实的。他们对社会的了解还是太肤浅，对中国传统的认识，虽然有心愿但是缺功力。对西方文化的态度也不够平和，多情感上的盲目抵触和情绪性的反感，缺乏细微的观察和理性的直面。*


+ 九十七

对这一代的年轻人，可爱之处在于他们的自尊心和自信心是发自心底的，没有三代前先辈那种“百年耻辱”的自卑情节。虽然他们的知识和见识极端欠缺，但是对中国文化和西方文化的基本见解，却比自1840年后每一代的前辈都要正确和高明，不论是曾国藩、李鸿章、张之洞、康有为、梁启超，还是孙中山及蒋介石、毛泽东、周恩来和邓小平。这一代人，可能是迄今唯一真正可以令中华文化复兴于世界文明之林的民族之英的群体。

当然要做到这样天地间罕见的大成就，首先要做到 *心要热，头要冷* 。在应对西方一些恶势力的挑衅之下，要有理、有利、有节和有益，可以随心所欲的调控，收放自如的操作。在思想上要坚定但不过激，在行为上要谋定方可后动，在配合上要上通同时下达，在情绪上要愤怒却无失控。对西方牛鬼蛇神要争锋相对，但不要格杀勿论。在向前辈学习上，除了笔者提到的五六十年代一代人的优点之外，还要学习他们对其他文化的热情和虚心，但就不要学他们对其他文化的盲目崇拜。因为众所周知的原因，那代人在1989年以前看到的世界和人生的体会，和这一代人在1990年后经验和感官到的中国，那是大相径庭，自然会对西方文化有天堂地狱般天上人间两重天的滋味。这两种体验和态度都是错的， *因为真正的现实是在我们地球的人间，而这两代人都应该将其态度向相反方向上的转变，才会印合我们祖宗的家传之宝——中庸之道，才会令我们真正做到阴阳协调，使我们的新文化营养平衡。*

*古语说，宁静而致远，集百川归大海，本来是我们中华民族的本色。回望神州五千年，我们这个以千百万不同基因组成，数万不同部落来源形成的民族，应该体验到我们血液里那遗传的凝聚动力。我们的血来自于祁连（古拉丁语Caelum，天）的吐火罗、天山的突厥、庭州的沙陀、阴山的敕勒、河套的匈奴、大湖的回纥、罗布泊的楼兰、伊犁的赛德、敦煌的月氏、昭武的羯胡、吐谷浑的氐羌、海东的党项、须弥的吐蕃、大理的摆夷、三峡的巴濮、汉中的蜀彝、湖广的三苗、岭南的百畲、江淮的百越、滨海的东夷、燕赵的东胡、嫩江的室韦、漠北的达怛、塞北的鲜卑、辽东的乌恒、安岭的柔然、云中的拓跋、木伦的契丹、长白的靺鞨、纥升骨的高句骊，还有那无数未能记载的祖先，都是黄帝、炎帝和蚩尤等等先祖的儿女。今天我们以世界第一大族的浩浩风姿，集五十六汉满蒙回维藏壮苗等等，比欧洲的文化和传统更多样的兄弟姐妹，如果不能领世界文明风气之先，恐怕是死后无论入天堂、九天、西天或是黄泉，都无脸见我们的列祖列宗。*

*我们的上一辈用他们的血与火的自我祭祀，化云为剑，抹雨成犁，呕心沥血，如履薄冰，为我们民族打造了前无古人，大概也是后无来者的创世纪的经济奇观，那么我们就没有理由不拍着胸脯，接过这柄中华民族薪火相传的火炬，大声说，让我们在这下个三十年创造出我们中华民族的文化奇迹，让我们民族的每一员都可以衣食温饱，安居乐业，老有所依，少有所养，平等互助，让我们的所有先贤，都可以因为我们而自豪。这才是我们民族那种“天行健，君子以自强不息”的进取精神，和“地势坤，君子以厚德载物”的处世态度。*


+ 九十八

*中国在世界上真正的崛起，不能只是在于经济上、基础建设上、城市发展上甚至是军事实力上成为世界超强。而且必须在文化上，创新出一种新的中华文化，像我们令全世界敬仰的先辈一样，为世界文明添加异彩。*

在中国历史上，我们不缺乏成为世界的文化领头羊，因此可以明白一种开放和谦虚的心态，是我们民族文化复兴的根本。正如古时赵武灵王的“胡服骑射”、汉武帝的“汗血宝马”、唐太宗的“夷汉一家”，中国文化的辉煌都离不开对其他文化的虚心学习，互通有无。 *今天的年轻人，需要做的是，在每一次对西方的行为抗议之后，都要问自己一声，西方文化中有哪些东西，是好的和值得我们学习的。如果有一天，你发现你的问题越来越难回答，中国文化的崛起在那一天就完成了。*

*中国在今后，不光要争取在国际经济上、国际政治上和国际外交上的话语权，还要争取在国际文化上的权利，不能时时成为西方对中国政治打压的目标。而如何在文化上抢夺到地位类似于今天中国在经济上获得的这种话语权利，是中国这一代人必须要解决的问题。*

首先可以做到的是，拒绝承认西方国家意图强迫中国接受的“普世价值”。世界上根本不存在自我标榜的普世价值，因为任何人提出的价值，必须被全世界的人接受和认可，才可以被宣称为普世价值。如果只是在人类大家庭中少部分人认可的价值，就不能称为普世。 *以中国的13亿人而言，占世界五分之一的人口，任何世界上的价值，没有中国人民的认可，就没有资格自我标榜。*

过于线性思维，简单的以西方构建的章程体系为纲，在上面不假思索的无保留的签字，在文化价值上没有做充足的工作，以游兵散勇的实力去拥抱垄断成一块铁板的西方文化价值势力，似乎近似于一种事实上的无条件的投降。而陷入西方国家的议题圈套，同西方国家进行政府之间的“人权对话”，必然是自己把自己绑起来，让西方人打耳光。因为无论中国人对自己的国家，对自己的政府和对自己的社会如何满意，都不会令西方国家满意。中国人的生活状况，人民是否安居乐业，根本不是西方人关注的目标。无论你对他们做出什么样的让步，他们都会找到更多的议题来指责中国，再加上有些被思想控制或者经济控制的中国异类人士，随时按照西方的指挥棒跳舞，没有议题就会制造议题，没有新闻就会编造新闻，总之只有一天中国变成像日本和韩国那样，当西方心甘情愿的奴隶，他们才会得到满足。正如一个原本单纯简单的奥运会，如果不能像1964年的东京和1988年的汉城那样向西方卑躬屈膝，就会被中伤为1936年柏林，似乎中国人刚刚杀掉六百万犹太人。

*中国应对的方法，下下之策就是同这些西方国家进行双方都没有诚意的对话和谈判，希望用太极推手，虚与委蛇。中下之策就是低声下气地解释中国的难处，比如什么我是发展中国家，经济文化落后，人民教育水平低，需要更多的时间来实现西方用了三百年达到的自由民主水平，请你们谅解等等。中上之策，就是对人权概念进行补充，加入生存权之类。但这些策略全部是用被动的应付的方法，还是在西方国家圈定的废话框架里绕来绕去。*


+ 九十九

*如果要了解中国人应该采取的上上之策，就必须明白我们处在的大时代，是一个西方强权日薄西山的时代，是西方文明对世界其他文明灭绝和摧残数百年之后，自己走进了穷途末路的困境的时代。* 在这个时代里，西方已经在经济上受到亚洲的中国（以及中国文明区）和印度文明的挑战。而在政治上历来被视为美国和欧洲后院的拉美和非洲，要求摆脱西方控制的呼声也越来越强。在国际能源命脉的中东，虽然美国为首的西方联军多次用兵，仍然不能压制伊斯兰世界的复兴。

*在这个西方维持自己统治地位的能力越来越弱的情况下，将西方的一己私利，包装成普世价值，要求任何非西方的国家为西方利益服务，简直就是要求中国人民在站起来之后，再跪下去。* 可笑的是有些脑残的中国学人，还在要求中国拥抱西方的普世价值，利用奥运会全盘西化，象日本一样，用我们的血汗换来的经济财富，为西方利益做欲求欲取的提款机。而且还威胁国人说，如果中国不向西方国家提交降表，西方就不承认中国是一个大国。中国人就不会得到世界（好像世界只是他们几个人而已）的尊重，中国人就没有了面子，马上就会不想再活在这个世上了。更可笑的是，西方媒体常常宣称，西方国家当初不应该接受在北京开奥运会，好像国际奥委会也是其政府的一个部门似的。

*西方之所以很在乎中国人可不可以就范，主要在于没有中国的投降，他们不可能实施普世价值下的民主、人权和自由的新帝国主义。总所周知，非法的伊拉克战争就是在这个新标签下的行为，但实际目标却是伊拉克的石油。如果这个道德帝国主义的新干涉原则能够得到联合国的认可，西方国家的目标就公然会指向伊朗、叙利亚、黎巴嫩、缅甸、苏丹、索马里和利比亚。正如当年大英帝国的鸦片战争，是为了保护在中国从事毒品走私活动的英国商家的私有财产神圣不可侵犯这个当年的普世价值。但是中国人的私有财产，抢得走的都送到大英博物馆，抢不走的就给你一个火烧圆明园，根本不会得到同等对待。即使在2008年，大谈人权的西方国家，更在乎的是在拉萨街头杀人放火的那些暴徒的人权，而不是那些被烧杀的无辜民众的生命权和财产权。*

*中国要做的，是不需要和西方进行官方的正式交流渠道，而是运用民间的力量，以毛泽东的拿手好戏，你打你的，我打我的。中国应该和印度、埃及等等国家发起“国际文化关注会”，将西方列强当年非法抢夺的各国的文物财富，奇珍异宝列出来，要求西方国家无偿退回。* [fn:jdwtdgyx10100]另外和伊斯兰国家成立“伊拉克和阿富汗战争受害者和难民关注委员会”，要求西方国家补偿。总之，在这些方面，中国不能总是处于被动状态，必须开始利用自己的力量，团结其他成日被西方欺压的国家，共同进退。

[fn:jdwtdgyx10100]  2009年3月，果然出现了关于圆明园兽首的争议。——编者注。

*世界经济发展到今天，全球经济的驱动力正从西方衰退，而转移到新兴的经济体。在未来的数年中，美国和西欧有非常大的可能会同时陷入经济衰退，中国和印度会很容易的成为西方政界和媒体的替罪羔羊。而西方日益带上民粹色彩的新一代政客，则会将制造业工作的流失归罪于全球化和发展中国家，而导致西方贸易保护主义的重新兴起。[fn:jdwtdgyx10101]

[fn:jdwtdgyx10101] 到2008年年底，美国经济刺激计划中“购买美国货”条款、英国兴起的“把工作留在英国”等口号，表明作者的预测基本应验。——编者注。


+ 一零零

在这种背景下，西方国家会一方面施加压力让中国开放市场，另一方面就会用市场和非市场的方法，关闭部分内部市场。比如在美国，可以通过媒体夸大中国制造产品的问题来增加中国企业的进入成本，或者是通过国会的国家安全听证会，来限制中国的投资机会，迫使中国只能投资有利于美国但对自己无益的地方。欧洲则会用各种复杂的欧盟标准，限制中国产品和品牌的进入，迫使中国厂家永远只能做欧洲品牌的代工，让欧洲商家拿高附加值利润。

*估计国际贸易组织（WTO）在今后数年，将会变成一个只能坐看各方争吵的论坛，而不会对世界贸易的促进起到什么真正的作用。* 在过去，WTO的局势和划分很清晰，就是发达富裕国家和发展中贫穷国家利益争执，界限分明和逻辑清晰。但是现在情况却大不相同，以中国、印度、巴西、南非为代表的新经济体，成了第三集团，这批国家经济总量大，所以国富，但仍是发展中国家，仍然民穷。发达国家当然不会那么轻易让步，因为他们认为没有理由，要让他们的强势经济无私的向你弱势经济输血，而要求这些发展中的大国让步，也不容易，凭什么这些仍然贫穷的人民要向富有的发达国家人民让利。

其结果就是国际贸易体系将会破裂，也许国际贸易组织还可以保住个名不符实的虚名，但其实质功能就会像世界银行和国际货币基金会一样退出历史舞台。世界经济会日益趋于地区化和双边化，这会为中国在世界经济中的新地位，提供一个活动的空间。

*中国大概会在下一个十年，开始占领世界高档消费品的市场，完成中国经济的结构性转变。* 如何将在制造业上形成的生产优势，延伸到文化上的优势，就需要产生一大批可以和世界最高水平竞争的专业人才。如果对世界的时尚趋势和流派不了解，就不能知彼，而对自己的文化不了解，就不能知己。光靠跟世界风而不能拿出自己的家底来，最后只能是二流货色。 *我们的新一代人，必须学习中国的历史，了解我们的文化产品。* 我们的古代文化，从夏商周的玉器和青铜器，一直到明清的家具，都不是任何世界一个文化可以相比的。而且这只是汉文化的一部分，如果我们可以将我们的少数民族的文化发扬光大，比如说把云南、贵州和广西丰富多彩，领世界风骚的服饰拿出来进行改进，就可以在世界上杀出一片天地来。

在军事上发展强大的国防更重要，但就不要玩航空母舰这样的面子花活。应当选择西方最薄弱的部分有针对性地建设有效武器装备。西方的新十字军东征已经在伊拉克陷入困境，如果要啃下伊朗这个硬骨头，可能就会力竭而亡。因此西方战略家们下一步，一定是以世界和平的假口号，挂羊头卖狗肉，企图制止非西方国家在核武器上的渴求，因为这些非西方国家会希望利用有限的核武器来抵消西方在常规武器上的强大优势。而当美国的全球防御系统因为太过昂贵而无法发展保证核打击下己方安全的话，这种诱骗的手段，可能是唯一的选择。

西方在军事上的乏力，在经济上的萧条，使其只能在文化上虚张声势。其实中国人对他们这种垂死挣扎，没有必要反应过度，中国政府也不需要强烈抗议。中国人只需要对西方媒体的歪曲污蔑笑破大牙就行了。西方人今天那种看到中国的翻天覆地的变化又故作不屑说“还是我老祖宗的民主好”的酸态，简直是阿Q老兄重新转世，让笔者大声惊奇。只要中国可以在文化上崛起，西方世界日薄西山的日子，就已经不远了。



本卷完
