# -*- org -*-

# Time-stamp: <2011-08-22 13:58:23 Monday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 【编者文代序·这是一个什么时代】

2008年，是一个将被历史记住的年份。

不是故作玄虚

＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊

20世纪的后半叶，英伦有学者，名曰 *霍布斯邦·霍* 教授在浩瀚史海中蓦然回首，看到了四个年份。

它们分别是：

- 1789年，发表了《人权宣言》的法国大革命；
- 1848年，终被镇压安抚的欧洲1848年革命；
- 1875年，席卷欧洲的大危机，大萧条的降临；
- 1914年，第一次世界大战爆发，欧洲启动告别世界中心舞台的序幕；

再就着他有幸亲眼目睹的另一个重要时刻：1991年，苏联红旗落幕，穷尽其后半生，洋洋洒洒，写出四本史证力著流传后人。并以此学识，为不列颠女王封爵。

它们分别是：

+ 《革命的年代 1789-1848》
+ 《资本的年代 1848-1875》
+ 《帝国的年代 1875-1914》
+ 《极端的年代 1914-1991》

1991年以后是什么年代？2008年以后是什么年代？

誉有当代史学泰斗之称的霍老先生，并没有给出答案，也许，作为历来长于回顾的历史学家，他也不愿意冒风险，为我们远眺蓝图。

＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊

奥巴马说：We Need Change!

美国需要，改变！

于是，在危机乌云中的11月，他，有色人种，民主党的原非热门候选人，最终当上了美国总统。

我们不知道他是否有能力，向他引以为榜样的 *民主党先贤罗斯福* ，救美国于危情，我们更不知道他是否有能力，能够在最长可能八年的任期里还他的选民一个让他们怀念的 *肯尼迪的六十年代* 。

需要改变？改变什么？为什么要改变？

＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊

大概是由于古老的老大帝国脾气的传承，国人的反应程度，似乎自晚清以来，就慢一拍。

在美利坚举国喊变的时刻，中国正在庆祝改革开放30周年。但是，四处蔓延的经济萧条的忧虑，已经弥散在中国各地，尤其是东南沿海这个过去的“经济明星”的上空。

霍老先生停笔的年代，是1991年。大概从更早的1980年起，到2007年，可以被称呼为“资本的年代II”，而其中从加速到繁荣再到狂欢的年岁，就是1991年到2007年。

从某种意义上来说，中国与美国，在过去的16年里，宛如两个钩子，相互勾合。有 *美国的产业空心化、全民负债化、经济金融化，对应的就是中国的工业化、车间化、和社会结构的剧烈“工厂化”* 。

这第二个“资本的年代”，与百多年前的第一个“资本的年代”（1848-1875年）相比，最大的不同，就在于百年前的那个资本狂欢，很大程度上是各个国家之内的狂欢和社会分化，尽管英国的资产阶级日益成为了资本输出的寄主，但在那个年代，除了跨国的证券认购以外，产业的跨国转移，阶层的跨国分化，尚不明显；而在 *现代债务信用货币制度* 和发达的航运、信息科技的扶助下，这15年的资本狂欢，却是一个跨越国界的盛宴，今天的美国的 *寄主化* 
#+INDEX: 寄语化
，远远超出了富裕阶层的范围，而是蔓延到社会的广大角落，人们用负债的方式创造了大量的货币，而亚洲，主要是中国的厂主，或发疯的追求这些他们个人眼光里看到的“货币”财富——美元，或者不由自主地卷入到这个跨越大洋的游戏里去。

当然，寄主的生活，终究要有偿还的一天。尽管世界各国主流媒体想方设法掩饰各种矛盾——2006年8月26日，正是“流动性（货币）过剩”充斥世界财经媒体的时刻，每个经济学家都在高喊：钱，太他妈的多了。不识趣的美国财经评论家Peter Schiff警告：好日子快要结束了……各路专家神棍，包括这资本的年代的启动人——美国里根前总统顾问 *拉弗* 哈哈大笑：Peter是个疯子，彻头彻尾的神经病。[fn:daguoyouxi0101]

[fn:daguoyouxi0101] 尽管Peter Schiff开出的药方让人不敢恭维，然而还是要钦佩他在危机前的勇气。至于那个拉弗，当时还敢在电视上和Schiff打赌，可到了两年后的2008年又还嘴硬不肯服输，王顾左右而言他，成为美国全国的笑话。

1年以后，金融连环爆炸炸响，2年以后，哀鸿遍野。

＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊

游戏崩盘了，资本的年代2.0，终结了。

当奥巴马高喊Change口号的时候，慢一拍的一些国人，正在自满于中国取得的辉煌经济数字，以“20世纪美国取代英国，21世纪中国取代美国”的简单逻辑，沾沾自喜。

如果这种简单的自喜，暗示着固化，习惯于过去的日子，甚至想把它永续长存。那么，国人的自我欣赏，实在是赶错了时候。因为市场经济的诡异，就在于那个寄主的危机，会把这个勤奋的生产者，以商品堆滞，停工关门的方式拉下深渊。——对，这对于中国这个生产者，非常的不公平！但，这是事实！

- 1848年到1875年，“资本的年代”
- 1991年到2007年，“资本的年代 2.0”

- 1875年到1914年，“帝国的年代”
- 2008年到 ???? 年，“??的年代?.0 ?”

＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊

*事物是呈现螺旋性上升的。国际格局也一样——从经济，到政治，到军事。*

在19世纪“资本的年代1.0”的30年里，世界的中心——欧洲发生了深刻的变化，这就是德国大陆力量的崛起前奏。

在21世纪“资本的年代2.0”的15年里，世界的整体——地球发生了深刻的变化，这就是中国的崛起前奏。

1830年，“德意志”只不过是个地理概念，1875年，德意志不仅是一个国家，而且是欧洲大陆上最强大的国家。

1992年，“中国”只不过是世界银行“低收入国家”中和埃及巴基斯坦孟加拉国并列的一员，2008年，从伦敦《经济学人》到纽约彭博财经资讯到处是对China的呼唤、议论、念叨、诅咒，或酸，或妒，或羡，或盼，或捧，或鄙。

不同的是，德国人是有意为之，中国人呢——这个国家的很多实权领头人自己压根没有意识到。

19世纪的德国人中诞生了国民经济学家李斯特，勾勒了亚欧大陆桥，他的思想上的学生们，勾勒了德国为中心，从土耳其到中东的经济体系的庞大构建计划，并且弥散到沙俄、土耳其、波斯诸国，以为首相。

中国人中呢？似乎，尚未有可比肩者。

＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊

人类的生活，归根到底是经济生活，是产品溪流的生产与消费。

世界的变化，归根到底是生产与消费在五大洲之间的转移。

*什么是世界的变化* ，最大的变化就是产品的来源地的变化——无论这产品，是华为中兴比亚迪把东洋西洋打得落花流水的拳头产品，还是或蚂蚁型或山寨型工厂昼夜输出的极大程度上受制于他人的“低端”产品。这个变化，一层带一层，带动社会结构的变化，政治潮流的变化，以及——军事焦点的变化。

A 这种变化，世界经济格局的巨变，本身就是中国这个大象踩进世界这个澡盆，去参与、塑造、或被动或主动促成的结果。

B 而这个世界巨变所编织出来的经济网络，又直接作用于他的编制者——现在的中国，并在发生麻烦的时候，很可能在短期内带来巨大的负面冲击。

C 巨变后的世界体系，再次走到下一次巨变路口的时候，下一轮游戏怎么玩，决定于中国的道路选择。

三十年前，十五年前，在美国的邀请下，中国参加了游戏，名字叫 *全球化，自由化* ；

在这个游戏中，中国成长了，虽然不免有很大的代价；

今天，游戏被客观的经济之力终结了，但是，游戏后的话语权，至少有一半落在中国手里；

是继续被动适应，乃至走向功败垂成，还是化被动为主动，打造自己的游戏？

崛起前奏，记住，仅仅只是个前奏。

高潮或者走调，还看后头

＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊

*2008年的年初与年中，我们有大雪，有火炬卫士，有大地震，有奥运会；*

冒天下之大不讳，不得不说，这些都是我中国人民意志的痕迹，但与其说是这一年的主题，不如说是这一年的烘托。

当事者迷，旁观者清。

一位身处海外的中国人，在这个特殊的年份里，留下了一份特殊的政治经济笔记。

有感于70后、80后的中国年轻人护卫火炬的激情，按捺不住心中纠缠那一丝丝忧虑与窃喜。他决定用高中生也能接受的通俗语言，诠释国际政治与经济。

让老百姓也能看明白政治与经济！

这篇笔记始于火炬保卫战和汶川大地震后的2008年5月23日，第一卷《大国游戏》终结于奥运前夕的8月5日，第二卷《花开花落》起于奥运揭幕的8月6日，终结于华尔街山崩地裂的10月4日，第三卷《梦幻泡影》起始于美国朝野慌乱的10月5日，终结于金融危机开始发酵蔓延世界的2009年1月17日。第四卷和第五卷，目前尚在编写中（截至本序写作时）。

当国人习惯于旧游戏中的思维定势，聚焦于东南沿海弥漫的寒流之时，作者从 *地缘政治* 和 *能源安全* 入笔，勾勒从中亚、中东、北非、欧俄的政经大景，提醒我们早做准备，重视我们的西北、西南、华中、中原、东北，走出不平衡的被动现状，打造本国主导的经济自主循环。

回顾笔记的写作时间，与天下种种大事的发生日期，读者不难发现，《大国游戏》系列，仿佛真的变成了这世界上游戏的诸大国之间的预演剧本。

玄乎？事实也。

＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊

*新美国基金会* （The New American Foundation），这个美国科技新贵手中的思想库，未来奥巴马政府的可能的重要指针策源地，将此作为口号：

*Big Idea for New America。*

中国呢？谁来提供“大主意”？谁来为路线的灵活应变提供来源？

What Idea? What China?

是时候了！

*大国，大国民，大主意，大思想，才能玩得起大游戏。*

*大国游戏。*

*逐鹿地球。*
