# -*- org -*-

# Time-stamp: <2011-09-15 20:38:25 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 【第一篇·多事秋】





【写作日期】2008年8月5日——12日            

#+begin_center
人生莫言短，却道白发长。
安得千里目，登楼望故乡。
#+end_center



** 一

笔者对写作并没有太大的兴趣，尤其是对这些超级大国尔虞我诈的阴招损术，三滥功夫，非常不屑。再加上做了太久的闲云野鹤，早就看淡了那种见面不如耳闻的钓誉沽名。之所以一改初衷写这一卷《大国游戏》（详细见《大国游戏I》一书），主要起因在于08年春天的拉萨事件，以及铺天盖地袭来的西方国家对中国政府、人民和文化展开的无情杀戮。这都让笔者不能再继续采菊东篱，置身事外。结果一不小心，居然在2008年5月23日到8月3日两个来月的时间里，从无意中写完了一百回，但自觉颇有言犹未尽之意。赶出来的东西质量自然一般，只是苦了热心的读者们要忍辱负重，硬着头皮看下去。

其实，俺一个不名一文的村野莽夫，从来也没有想过去踩这趟浑水。但看到俺家里那帮谦谦秀才们在中西无赖的内外夹击下，颇有些招架不住。搞得洋鬼子们欺俺中华无人，不由得按耐不住心头的无名怒火（说来惭愧惭愧，笔者过去还以为早已修炼到心如止水的境界了呢），出来给大家做一番讲解。对未能远谋的庙堂肉食者，支几个绝招，抛几包锦囊。对稀里糊涂不知就里的芸芸看客，扯开那面纱，爆几个阴谋。让大伙儿对西方道德君子们的青面獠牙，多识几分清晰的印象。

在俺们的老祖宗里，从来不缺乏竹林七贤中那如阮籍、嵇康、山涛、刘伶、阮咸、向秀和王戎之类的人物，号称达则兼济天下，穷则独善其身，治世而趋庙堂，乱世而避山野的君子。而笔者这个赤脚山民，既无陶渊明乐于贫贱之修养，也无诸葛亮心怀逐鹿的抱负，只取的是“太平而隐，乱世而起”的人生态度。在多事的2008之秋，如果不帮助家人们度过难关，恐怕弄不好又有一天大厦将覆，害得俺山人又不得不出世，重整破碎的大好山河。那于民岂不是天大的灾难，于己岂不是天大的麻烦。看来为己为人，都应该强自出头，提犁作剑，落叶飞花，驱魔除障，不能再故作清高，不理世事，怕他年死后见俺祖宗周文王时，被老爷子一个大耳光煽过来，打得俺眼直冒五天神佛。

在西藏骚乱后，笔者头一个反应看法就是，西藏的行动是美国的偏师，美国的主攻方向还是台湾。其目的在于希望中国政府在西藏进行过激的镇压，借机渲染抹黑，来逆转台湾的选情，从而在最重要的选前一星期，使台独势力可以重掌政权。当然，中国政府没有上当，在对暴乱的镇压上非常克制。台湾同胞也没有上当，还是没有投票给主张隐形台独的民进党。

当然，笔者不认为台湾同胞们会去通过那个相当于战争宣言的“台湾入联公投”。即使民进党靠大选绑架公投而在选举中获胜，他们也肯定会由选举委员会宣布公投没能过关（即使票数过关也要搞成不过关）。其实，台湾公投设计出来就是用来忽悠大陆人民，让大陆的解放军将士们热血冲脑，搞个军事演习，射几个空包导弹，挑动民情，帮台独势力助选而已。

唯一可笑可叹的是，西方各国政府和媒体已经准备好了对中国的文攻武吓，于是在亚洲自由电台的新闻编造机器引领下，对中国人民和政府进行了一长串肆无忌惮的歪曲和中伤。结果却引起了全球华人的大反击，导致了数亿中国百姓开始发出“做人不能太CNN”的感慨。而中国的大多数人也从此看清了西方的真实面目。

这，恐怕是始作俑者所料未及的结局吧。


** 二

其实，早在2001年北京拿到奥运主办权之后，各类异议团体已经准备大闹一场，西方媒体和政客也都已经准备届时和中国豪赌一把。

所以说08年的这次拉萨暴乱在选择的时机上很值得探讨。其实信号在07年由德国总理默克尔接见达赖喇嘛就开始放出来了，然后就是一场由美国众议院议长佩罗西主导，美国总统小布什配合的授予达赖喇嘛金牌的颁奖仪式，传递信息，接着拉萨哲蚌寺的喇嘛便开始抗议。对此，中国以拒绝美国海军小鹰号访问香港做为报复，但看来美国人并没有把中国放在眼里。

如果你对西方的情况了解的话，就可以发现这个战略在西方学术界和战略界早已经成型。

在学术上的方法，是以客观研究历史的名义不承认中国现有的领土。其中一个流氓的做法就是将中国人（Chinese）和汉人（Han）对等，这样所有的非汉族中国人，就被称为“非中国人（Non-Chinese）”，也就是变成了可以同中国人对应的名词。比如说，“中国人和西藏人”（Chinese and Tibetans）、“中国人和维吾尔人”（Chinese and Ugyhurs）、“中国人和满洲人”(Chinese and Manchurians)、“中国人和蒙古人”(Chinese and Mongolians)，这种列比写法在英文报刊杂志上比比皆是。在现代社会，这种做法，就像是把非白人美国人当作“非美国人”，把科西嘉岛人说成是“非法国人”一样荒唐。不过西方媒体从来都是他们可以放火，你不可以抽烟的强盗逻辑。

这样的区分法，主要是达到一个歪曲历史的效果，因为当年的清朝皇帝是满族，那么清朝就不是中国的一个朝代。这种随意篡改历史的伎俩非常可笑，因为在清政府中，除了满族的爱新觉罗家族是皇族外，身为王爷和高官的人士就是各族都有。而中国五千年的历史，从来都是多民族共处。但是西方历史学家大谈此类学说的目的或客观效果是，只要断定清朝不是中国人的王朝，那么西方就可以不承认中国今天的领土完整 ，因为今天的中国是以清朝的继承者身份，传承清朝的国土作为其领土主张的现代国家法理基础的。如果将西藏人、新疆人（或维吾尔人）、蒙古人、满洲人、以及台湾人从中国人的概念里分离出来，主张以明朝的疆土来为将来的中国划界，就可以不承认中国对台湾、西藏、新疆、内蒙和东北的主权。当然，如果将来战略需要，又可以进一步发挥，根据民间传闻去发现什么明成祖朱棣为蒙古人啊，或者明太祖朱元璋可能是回回啊之类，继续篡改中国的历史以服务目的。

在这种“客观公正”的历史观下，追求以上地区的独立就成为理所当然。台湾的独立条件当然是最好的，但是西藏、新疆这两个地方，也都可以通过对西方公众洗脑，说成是在1950年人民解放军的“侵略”下才成了中国领土，所以是非法的占领；渲染所谓在解放军进入之前，这些地方都是独立的国家的理论。当然，现在内蒙古和满洲没有独立运动，但是也还是可以操作，用外蒙古来影响内蒙古，在延边挑起独立分离运动等等。以联合国宪章里关于殖民地人民可以有民族自决的权利的条款，开始堂而皇之的支持中国境内的分离主义恐怖活动。

当然，对这些西方人士来说，最理想的情况是，由台湾独立而挑起一场大战，同时又在西藏和新疆支持分离武装势力，这样就可以把中国搞得分崩离析。


三

不过，从现实的角度来看，在台湾打一场大仗可能是中美两败俱伤，所以一个更可行和经济的办法是以台湾为主，西藏和新疆为辅，以骚扰和牵制为基本手段，尤其是对后二者重点操作，令中国政府坐立不安，不得不向美国付保护费来买个安宁。

对新疆的操作，主要是在2007年中，在四个国家——美国、英国、加拿大、澳洲（陆克文上台之前）的舆论上报道中国对穆斯林信徒的宗教迫害（其实报道的基本就是维吾尔族，因为西方普通媒体并不清楚中国有十几个信奉伊斯兰教的民族），并由英国散布假消息来挑动巴基斯坦北部部落里的极端分子对中国在当地的利益进行攻击。这就是红色清真寺事件 的起因。但是巴基斯坦对极端分子大开杀戒后，一度内乱，西方眼看挑逗伊斯兰极端势力有点过火失控，可能殃及巴基斯坦的核武库安全，所以暂时在新疆收手。而当08年春台湾大选牌失效之后，美国又开始对新疆下重手。先是由美国国会通过对中国在新疆事务上进行谴责的议案，然后开国会听证会希望放美国关押的东突恐怖分子精英出山，接着就是布什接见热比娅，为疆独恐怖组织打气。在超级大国美国的鼓励下，东突分子果然在喀什对边防武警开始了袭击活动。

    而西藏在今后的十年内，将是美国对付中国的主要操作手段之一。从佩罗西到印度达兰萨拉访问，到麦凯恩会见达赖喇嘛，再到奥巴马与其的私人信件往来这些美国各派强化与西藏流亡势力的联系动作，不难得出这一结论。上一次在七十年代，美国抛弃藏独势力，是因为要拉中国来对抗苏联 。而今日中国成为美国的第一竞争对手，估计是美国也难会在这个问题上自动收手。为求自保，中国对流落海外的旧西藏分裂主义势力政策只能日渐强硬。

具体说来，笔者的建议是，可以争取和海外藏人的温和势力和解，但必须对极端组织如“藏青会”之流狠狠打击（这些组织完全受美国和英国势力操控，其实对藏人的真正利益毫不关心）。有证据在手的话，可以宣布其为恐怖组织，并对尼泊尔和印度施加压力，将其人马赶回欧洲和北美。对今春和达赖喇嘛的代表谈判，笔者并不十分赞同，原因一是藏独势力并非他所能控制，真正的后台老板是美国政府，二是和达赖喇嘛的谈判很难谈出实际结果，反而徒增西方国家在这一中国内政问题上继续粗暴干预的胆量。中国人要明白的是，无论中国在藏区采取什么样的政策，其结果都不会改变西方国家在这个问题上的态度。因为西方国
 
图1.1 70年代分裂分子被歼灭的尼泊尔北部山区穆斯塘的入口处

家根本不在乎藏人的福祉，他们在乎的是如何才可以把中国搞乱，令中国各族之间互相残杀。

中国应该在西藏采取更强硬的政策，大不了就是那些不安分的效忠于达赖喇嘛的拉萨寺庙的格鲁派（黄教）喇嘛们，每二十年闹一次而已。因此笔者建议打击这些黄教寺庙，切断其最近几年非常泛滥的以收取学生的名义从其他藏区吸引和尚，用师徒相受的方法发展他们的影响力的渠道。同时应该大力支持其他西藏教派，如噶举派（白教）、宁玛派（红教）和萨迦派（花教）。当然，格鲁派内部的班禅势力需要大力支持，还有就是可以支持格鲁派里的多吉雄登派（Dorje Shugden）对抗达赖喇嘛对他们宗教自由的残酷迫害。

要理解雄登派和达赖喇嘛的纠葛，你就必须对西藏的历史和藏传佛教有比较深入的了解，这里笔者没法细述，只是这个仇口起源于当年的五世达赖喇嘛，在现在的十四世手里变成了头痛的事情 。


四

果然，欧洲和美国的雄登派喇嘛们，在达赖喇嘛的柏林忽悠会上站出来抗议。他们举起的写着“达赖喇嘛，不要再撒谎了！”和“达赖喇嘛，停止宗教迫害！”的大标牌，令盲目跟从达赖喇嘛的西方傻冒们有些困惑。而在最近一次纽约电台城音乐厅（Radio City）的一次宗教忽悠会上，数千名达赖喇嘛的美国忠实信徒们，把他们上师关于“宗教自由”的教诲牢记在心，几乎对上百名和平抗议的雄登派喇嘛大打出手。害得纽约警察必须将这些雄登和尚们带走，剥夺他们抗议的权利。
    
图1.2  左：多吉雄登神像；右：雄登派信徒在美、德等地追踪抗议，由于雄登派喇嘛怕被达赖喇嘛手下的打手打击报复，不得不让其西方徒弟出面

在《纽约时报》之后的报道中，平时口若悬河的美国藏学家们，对记者的询问都三缄其口，因为他们和达赖喇嘛关系不错，所以“不便对此事情妄加评论”。 

在台湾的对策上，08年春笔者的估计是，美国是想在西藏和其他藏区发起大规模抗议活动，引诱中国政府的镇压，然后在台湾选举前的最后也是最重要的一个星期，使台湾选情逆转。

有人会问： 美国不是讨厌陈水扁，喜欢马英九这位哈佛大学毕业，身怀美国绿卡，三句话就会有两句谈到美国式民主的哈美人士吗？其实不能用如此简单的二分法来看美国的台湾政策。美国确实不喜欢陈水扁，倒不是因为陈水扁不肯向大陆狂吠，而是因为陈水扁不听话，不按照美国的指挥棒转。因为美国在现阶段无法解决中东的乱局，所以无力应付在台湾海峡同中国对抗，而此时陈水扁偏偏要成天和大陆玩擦边游戏，不符合美国现阶段的策略。所以说美国要的是一个希望台独但又不宣布台独的势力在台湾当政，也就是谢长廷之类的台独温和派。

对马英九，美国其实是很不放心。国民党与共产党关系越来越密切，再加上马英九当年的保钓背景 ，都使美国对他的政府到底会和大陆走多近，深感忧虑。所以通过西藏问题来影响台湾选举，其实是很高的一招。正所谓项庄舞剑，意在沛公。

可惜的是台湾人民太聪明，不亦步亦趋尾随美国。而且在马英九胜选在望时候又爆出美国偷偷将核弹技术转让给台湾以支持台独势力的丑闻。接下来又是海南三亚博鳌论坛上的胡萧会，为两岸合作画出清晰的远景。可以说如果无意外的话，两岸关系会有一个至少八年的稳定期，而在这个最关键的时间段里，如果顺利，中国就会崛起成为世界大国，稳执世界经济和外交的牛耳。


五

所以很快我们就听到美国智库专家开始“忧虑”：两岸走得太近，会对美国利益造成不利影响。

接着美国就开始出招：一是宣布美国在台协会（非官方组织）将会增加美国海军陆战队作为官邸守卫，二是宣布在台协会官员不再由退休外交官担任，而以现职外交官出任。这两个措施就是把原来非官方的经济、文化和商业办事机构，变相的上升为外交机构。另外一个配合做法就是，清晰化“一中各表”中的“各表”，从而推动事实上的“两国论”。

当然中国本来想以默认台湾的“各表”，对其采取既不承认，也不否认的模糊策略。以灵活务实的态度，为两岸创造出一个双赢的局面。所以说如何巧妙的互动以化解美国的杀招，值得关注。

同样对台湾来说，采取务实的态度，“不要表述”一个中国的内涵，是台湾在当前经济困境下走出孤立的一个高招。只不过这种两岸之间的默契，会严重损害美国的利益，因为这样她就不可以在兄弟阋墙之中火中取栗。所以，美国在在台协会上这几个新动作已经至少让海外的台独势力大受鼓舞。本来在美国的台独组织从来都不在奥运会上做文章，以免激怒大陆普通民众，但是后来就有21个在美国的台独团体，呼吁美国总统小布什抵制北京奥运会的开幕式。

这就是我对美国在新的对台政策调整上的基本判读： 在“一中各表”的“各表”多下点功夫，而推动公开的“两国论”。

本来大陆寄望将上台的马英九团队会好好合作，以模糊的方式搁置两岸争议，以务实的态度营造出一个互利双赢的局面。没想到马英九立即就走出了一手险棋，迎合美国（当然还有日本——别忘了李登辉主动出来要帮马英九改善台日关系的举动），抬出李登辉的木偶赖幸媛出任“陆委会” 主委一职。

大家都知道，李登辉是“两国论”的版权拥有者。马英九把他的代言人请出来，就是在国民党的两岸合作的高速列车里安上了个“戒急用忍”的大刹车。

本来国民党的“四驾马车”——连战、萧万长、江炳坤和苏起，基本上把整个运作系统一体化，连战和萧万长可以直接通天到胡锦涛主席，而江炳坤和苏起又与陈云林熟悉，这就使两岸关系在具体运作上有很高的效率。但是现在多了个大刹车，立即使局面增加了不确定因素。这就难怪大陆的台商和在台商界人士听到这一消息，立即跳脚大骂。就连老牌干练的李光耀都给了马英九个“不成熟”的评语。

从理论上来讲，马英九是司机，因此赖幸媛这个刹车阀，应该由他来控制。但是，谁敢说李登辉就没有控制这个刹车的能力呢？如果政府里安插了李登辉的棋子，那么在未来的施政过程中，如果马英九路线和李登辉路线方向一致，那么就像高速公路同一个方向上的不同行车道，不会出现问题，但一旦两者用意的路线出现偏差，就会让施政出现困扰。

（作者此文其实写于2008年5月，到2008年8月写作大国游戏第二卷时再次搬出。所以他在这里所谈的台湾局势，主要是针对写作当时（2008年5月初）的一些环境写的。到2008年11月，随着陈云林成功访台和两岸签署诸项经济合作互惠协议，两岸关系已经快速进入新的时代。为了保留作者的原著见解，在本书第一篇部分，以基本不变的状态展现作者的看法，希望读者能够理解。——编者注。）

六

当然有人会问: 马英九并不傻，难道没有想到其中的厉害？为什么马英九会这样做？

表面上来看，马英九是为了讨好五百万没有投他票的绿营选民，希望通过蓝绿和解为台湾内部赢来共识，从而可以更顺利的“拼经济”，为台湾目前的困境解套。

但实际上马英九是在为自己设套。因为对海峡两岸关系发展最不利的情况就是在交往中存在不确定因素，而不确定因素正是美国最想看到，如此则可以将以台湾牵制大陆的战略发挥到极致。而马英九的做法，会使大陆对他的政策清晰度增加疑惑。以后，就是他会对大陆的善意信誓旦旦，号称回投桃报李，大陆对他的态度恐怕也会退一步为“听其言，观其行”了。

那么，这会对两岸关系的互动造成什么样的不良影响呢？
 
本来，一个有魄力的领袖人物，应该有比较开阔的视野和敢作敢为的决断。马英九挟选举大胜的余威和国民党在国会一党独大的局面，本来可以在以下几个领域里大有作为：

1．对台湾政治进行大幅度改革，在两岸关系上与大陆达成共识，彻底走出无聊的统独之争。以提高行政效率、打击贪污腐败和避免族群内耗为施政重点。把想靠挑起人民内斗而坐收渔利的台独投机派彻底打出政治舞台，为台湾的未来打下一个长治久安的基础。

2．全力发展台湾经济，建立一个互利互惠的“一中市场”。为台湾经济在未来国际的经济衰退大环境下，以大陆的经济发展为依靠，建立起一个安全网。使饱受经济疲软困扰的台湾人民，能够安度随后几年的国际惊涛骇浪。 

3．在与大陆建立一个很深厚的互信关系后，取得大陆的谅解，由两岸共同协商出一个妥善的解决方案，为台湾扩展出一个合理的国际活动空间。比如在加入世界卫生组织等议题上，其实还是有很大商量的空间。 

可惜的是，马英九不是一个有魄力和远见的政治家。他更像一个中国传统知识分子，总是对自己的形象顾影自怜，生怕自己的一言一行会引起人非议。其实，这种总是想讨好所有人的领导人，到最后会搞到所有人都得罪，而且很可能得罪的最厉害的，反而是自己原先最忠实的支持者。推出这种没有担当改革风险的勇气，不负责任，样样事情都不沾锅，不为人民解决实际问题，只是每天关注自己的公众形象的领导人，恐怕是一味纯粹追求民主政治选举制度的宿命。再加上当初为了讨好选民，马英九向韩国的大忽悠李明博借招，拍胸脯，夸海口，放卫星，让台湾人民产生“马上好”的幻想，真让人为台湾人民的前途忧心。

当然马英九的支持者最担心的是，会不会给北京送出一个错误的信号而影响两岸已经破冻的合作关系。其实他们不必太过担忧，因为马英九送出的信号对他自己来说一点都不错，就是以李登辉为主导的政治冷淡经济温暖的隐形两国论。其实这是和美国的对华关系比较一致的，也是美国最想看到的两岸布局。


七

其实马英九团队对台湾人民忽悠的空头支票，全部需要大陆的配合才有兑现可能。世界经济的整体恶化的大走势并不是你那张令小S之流发情的英俊面孔一出现就可以扭转的，所有的利好不是“马上台”就会“马上来”。通货膨胀、经济衰退、油价飞涨、金融危机，这个令世界上所有执政者都头痛的“滞胀”问题，需要的是未雨绸缪、诚恳务实、脚踏实地、行动果断的领导决策，而不是你去做一统江湖的蓝绿共主，企图建立起一个台湾内部的“小联合国”政府就可以用政治妥协消解。如果想要把方方面面的利益都要照顾到，反而有可能变质：扔给绿营的好处会被绿党民众看成是打发叫花子，而蓝党民众就觉得自己选举中的汗马功劳不被尊重，自己这帮马英九支持者成了鸟尽弓藏、兔死狗烹的炮灰。

在这样南辕北辙的施政方针下，一个简单的组阁都变成了头疼的问题，更何况将来的政府运作。在马英九的操作下，台湾未来的政府不是由一批团结一心，同仇敌忾的执政精英组成，而是由一帮面和心不和的各派人士，在内部对各项政策争吵无休，在外部互相钳制，导致政府效率低下，行政机构扯皮，官员反应迟钝。如果经济上不能快速有斩获，再出几桩类似于钓鱼岛撞船这样的突发事件，马英九政府在民众中的信心估计很快就会破产。

当然，台湾和南韩的情况有一个跟本的区别，这就是台湾背靠中国大陆。笔者当初看了李明博的大跃进“747经济航天计划” ，第一反应就是为韩国人民忧心。这混小子恐怕要搞到韩国倾家荡产进当铺。说实在的，笔者从李明博当选那天起就在等着他宣布韩国启动经济危机应急方案，而且这次可能比1997年那次更惨，搞不好李明博要变成李命薄。韩国1997年经济危机，主要是受资本帐户开放的货币危机下的大企业集团债务所累。这次即将到来的危机的主角将是中小企业加上消费者家庭。他们都在巨大的债务压力下，只要外资一撤退（当然上街游行的中下层棒子们还在喊反外资），楼市和股市一爆，韩元一大跌，很快就会发现原来大部分的外汇储备只是短期外债的暂存而已。那时李明博唯一的选择，就是象越南一样，跑到中国求救。

（作者在写此文时，为2008年夏。韩国在2008年底果然爆发资金外流的危机，印证了作者的判断。韩元暴跌至1500韩元兑换1美元的水平。此后又在2009年2月期间再次陷入危急境地。但韩元的暴跌，使得韩国电子产品的国际美元价格迅速下降，为韩国电子厂商如液晶面板企业获得了订单。使得韩国的实际生产开工相对于日本和中国台湾反而有较好表现。台湾液晶面板企业和芯片企业群体等电子产业在2009年2月陷入近乎绝境的地步。随后随着中间流通企业补入库存有所改良，截至编者更新修改为止，仍处于反复波动中。——编者注）

而马英九的计划 虽然也是一个大骗局，但是好在其依赖对象是中国大陆，以国民党内的元老连战、吴伯雄，加上成千上万的在大陆的台商的共同努力，台湾经济虽然不会有长足的成长，但也不至于受突发危机的困扰。汶川大地震后对岸救援合作在大陆引发的同胞亲情，使得至少在大陆客去台湾旅游和两岸客运包机直航上没有跳票，但是马英九政府不能去夸大这些因素对台湾经济的推动作用，也不能有完全依赖的指望心态。就算大陆有心帮助台湾，也不能预期会向对香港那样的大规模让利。再加上赖幸媛之类的马英九新宠会在内部上下其手，恐怕不能指望台湾经济能有多大的作为。

令人感叹的是，自台湾实行民主选举以来，从李登辉，到陈水扁，再到马英九，似乎在领导人能力素质上，有点九斤老太，一代不如一代的趋势。

至于从大陆的角度来看，只要台湾不被台独势力把持，不去碰撞大陆的底线，能够为大陆经济发展争取最关键的和平十年，没有必要为对岸的这些政治小动作而烦恼。


八

对大陆台湾经济一体化这个不可避免的趋势，本来马英九是没有必要对民进党的可能杯葛而顾虑。其实如果你回顾台湾商人到大陆投资的历史，就会发现最先进军大陆的台商都是民进党员。因为八十年代台湾的政治经济资源被国民党垄断，这些绿色商人不得不走入对对岸大门初开的大陆赚钱。而当陈水扁执政后，民进党的绿色商人们可以靠控制政治资源的政府搞利益输送，从各种公共工程中中饱私囊了。当然也就不需要辛辛苦苦去大陆打拼了。所以自然在与大陆经济联系的问题上，可以信誓旦旦，大谈军事和经济安全考量，为三通和投资设置各种障碍。而变成在野党的国民党，既然政府的垄断利益大锅无法再伸筷子进去夹肉，所以只好硬着头皮西进大陆，发展自己的经济实力，等待机会卷土重来。

所以说当马英九上台后，民进党势力又被打出了政府食堂，为了开锅，唯一的选择就是去大陆找经济机会。这个时候，中国政府发表了声明，对放弃台独主张的绿党人士，过往不究，欢迎来大陆投资，就是因应这个局势变化的一招。而绿党的在任县市长和议员们，为了自己选区和地方的支持者和民众的利益，就得乖乖的登陆，去为自己的产品和商家推销。在这个过程中，很多绿党的一方豪杰就免不了和大陆的各级官员打交道，寻求地方一级的合作。 

当这些县市的合作成一定的规模，民进党就不得不学习国民党，形成一个统一的党的政策，来处理和大陆的交往问题。如果他们不这样做的话，国民党就会对大陆关系起主导作用，而使民进党在台湾最重要的政治和经济问题上，被边缘化而失去主动权。

所以马英九可以完全不需要在大陆政策上，出于对民进党的顾虑而以牺牲政府的行政效率来笼络绿党民众。如果他可以借700万支持他的多数人之势，励精图治，快刀斩乱麻，使台湾经济有一个不错的表现，使台湾的普通民众，不论蓝绿红黑，生活水平都可以水涨船高，那么他就不用担忧自己的下一任期问题。而现在他却因为有500万民众没有投他票，整天耿耿于怀，梦想自己形象完美，人见人爱，车见车载，如有一个人呛声，马上就变得如丧考妣，回去对着镜子，抚摸自己的羽毛，长吁短叹，简直就是个中看不中用的银洋蜡枪头。

以这种不以台湾人民的福祉为基本思考点的策略施政，天天考虑如何让全台各地、各党、各派的政客们能够心甘情愿的臣服在他英俊潇洒的小马哥的座下，武林一统，三呼万岁，其结果就是让那些治国一塌糊涂，搞党争和族群分裂上不愧大内高手的狠角色们，又有了在体制内翻天覆地的机会。估计真正的行政专才在这些政治高手的制衡下恐无计可施，最后只能挂冠而去。

试想一下，本来马英九的经济竞选623口号里的水分已经不少，又加上他在选上后夸大了与大陆经济一体化的中短期项目如旅游、投资台股的经济改善效应，而以大陆自己面临的经济转型压力，估计在未来一年内中国政府本身的经济压力会比较重，又要兼顾保证香港和澳门不受到世界经济衰退的打击而影响社会的稳定，可能无法对台湾经济进行利益输送。在这种情况下，台湾的经济也许短期内不会改善，反而有可能会进一步恶化，而人民的怨恨情绪将可能高涨。


九

在这个经济不振的背景下，加上马英九的小联合国政府扯皮严重，还要同时和国民党掌管的国会（本来与立法院长王金平因为党内初选出茅招而有牙齿印）及国民党党部（基本上还是由连战和吴伯雄操控）暗战，一有突发事件，这个政府基本上处于瘫痪状态，而政府的迟缓反应，又会被亲国民党和亲民进党的蓝绿两派媒体口诛笔伐，结果变成两头受气，里外不是人。

以笔者的估计，马英九政府大概在08年年底左右，就会把选举中获得的本钱耗尽，在心浮气躁、脾气火爆的台湾人民和口不择言、穷追猛打的台湾媒体的十面埋伏下，风雨飘摇，信用破产，名誉扫地。

（作者是依据写作本篇日记时的环境——台湾股市持续阴跌，台湾民众怨言连连做出这一预言的。在后继的局势发展中，台湾受到各类消息的刺激，如陆客旅游等，有所信心恢复。但台湾本地的经济矛盾和社会矛盾，仍然处于一个较为对立分化的状态。——编者注。）

也许当初马英九拜李明博这个师兄就是一个大错。看看李忽悠在韩国经济和朝韩关系上的困境（搞到连北京奥运会朝韩都不一起出场了），估计这就是小马弟的明天写照。

当然即使台湾经济陷入困境，导致政治不稳，大陆也不会对马英九见死不救。总之，在经济上大陆还是应该尽量配合台湾的善意，不要让台湾的商界和百姓为马英九的愚蠢而买单。至于在政治上，还是应该提高警惕，避免李登辉的即兴表演在两岸关系上增加变数。而对美国的态度，需要仔细观察，但不需要太过敏感。尤其是对美国希望恢复对台军售这一个问题上，要有一个全面的考虑。

美国对台湾的军售，自然目的是增加美国对台湾的影响力，但也是台湾向美国老板交保护费的一个必然手续。中国应当积极的利用台湾军力增强作为一个好的借口，乘机大力扩充军费，并发动文宣攻势，指责美国在东亚挑起军备竞赛（同时还可以对美国破坏国际核不扩散条约提供印度核技术，挑起南亚军备竞赛这件事情广泛报道）。而在发展军备的时候，内心里应该清楚不是以台湾军队为假想敌，而是以美国和日本军队作为假想敌，迫使美国和日本在经济衰退的情况下继续加大军备建设，导致美国陷入更大的困境。

本来美国现在要同时打两场仗，又要花大钱在高科技武器的研发上面，如果还要同时应付中国和俄罗斯在高端上的挑战及全球伊斯兰圣战组织在低端上的骚扰，那么在资源上就会有些捉襟见肘。不要小看美国在伊拉克和阿富汗战争中的设备损耗，伊拉克的沙漠气候让许多价值昂贵的重武器，如阿帕奇和黑鹰直升机、布拉德利装甲车以及亚伯兰坦克，都会比通常情况下损耗要快，造成维修费用大幅提高。而伊拉克反美武装用路边炸弹，以区区的一百美金，就可以令几百万，甚至上千万的设备报废。这些都令美国的军费开支持续大涨。

只要中国在军队发展上面，遵循经济节省的原则，把钱花在刀刃上，比如说外太空卫星战技术、电子干扰和抗干扰技术、信息对抗战技术、无人超小型飞行器技术，以及低音高速的潜艇和其他水下装置制造等等，就能够对美军形成一定程度的困扰，从而继续保持以发展经济和提高人民生活水平为主的主线。最好不要花钱在一些中看不中用的花拳绣腿上，比如说大而无用，在现代海战中被称为“海上移动大棺材”的航空母舰。 这样，中国就可以在这场竞赛中占上风。


十

其实在现代战争中，由于隐形材料的发展，飞行速度的增快，打击精度的提高，很少有大型航空母舰可以在开战第一天的战斗中幸存下来。现在一个最热门的领域，就是发展具有高度隐蔽性的海底潜水母艇。这种潜水母舰携带大量高速飞行武器，可以隐蔽地接近敌方的航母战斗群，然后释放出这些可以在海水里游动的飞行器。这些飞行器长约1米到2米，悄悄接近舰队后突然升出水面，贴着海平面以超音速向海上目标发动攻击。以现有的防卫技术，能防止这种攻击的自卫能力，几乎不存在。由这种高科技为基础的新时代“群狼战术”打击航空母舰上，非常有效，而且就好像是老鼠对大象，经济成本很低。

当然另一方面，大陆军队必需要和台湾军队增加合作、交流和互信，以防止“擦枪走火”为说词，与台湾军方进行各种人事上的交往，这样就会让美军开始担忧卖给台湾的武器有泄密的可能，从而为美国的台湾政策增加困扰。而且这种交往对缓和军队间的敌对情绪，互相停止导弹对瞄，协调两岸在南海和钓鱼岛维护主权的行动，乃至于进一步发展到海上为两岸合作开发石油天然气的设施护航，都会带来深远的影响，最后为两岸签署和平协定提供坚实的保证。

中国人民应该明白，不到万不得已的地步，一定不可以向台湾开战。任何中华民族兄弟之间的屠杀，都只会令外人得益。对两岸最要紧的事，并不是短期内寻找一个政治统一的可行性方案，而是两岸在亚洲地区的政治和地缘战略意见上，要同声同气，共同进退，不要被外人上下挑动，自相残杀。

我们要明白，古代中国在关于政治体制上，有自己一套行之有效的方法，其中的优点并不是起源于欧洲的现代民族国家体制可以替代。随着中国在世界上政治、经济、军事和文化的全面复兴，中国在亚洲地区影响力全方位的扩大是指日可待的事情。在中国内部实行的少数民族地区自治制度和在香港和澳门实行的“一国两制”特别行政区制度，都是有意义的尝试，可以为未来更新颖的制度创新，带来很多成功和失败的经验。中国不光要找出一种可以照顾到台湾特殊情况的国家模式，还要为未来外蒙、西伯利亚、朝鲜、缅甸、越南、老挝、柬埔寨、泰国参与进中国为主形成的一个文化和市场统一区域，寻找出一个可行的方案。另外如何将巴基斯坦和中亚各国这些西域的古代中国势力范围整合，形成一个比上海合作组织更紧密的群体，都值得好好的思考。

其实，现代民族国家体系发源于支离破碎的近代欧洲，如果机械性的按这种思维去考虑问题，就会造成各国画地为牢，互相猜忌。而古代中国为核心的东亚的附属国朝贡体系，又缺乏对小国的平等和尊重。现在欧洲联盟试图建立一个统一的欧洲，是某种建立新型国与国密切关系体系的尝试，但欧盟除了在统一货币和中央银行方面成果显著，在统一市场、人员和物资自由流通有所进展外，其他的财政、政治、外交和军事上的整合，都非常乏力，甚至反过来制肘联盟级机构的工作，上不上下不下，反而让联盟整体运作效率下降，无法形成和世界其他超强的有效竞争。如何建立比欧盟更紧密的一种政治关系，是亚洲将来不得不考虑的一个方向。

