# -*- org -*-

# Time-stamp: <2011-08-30 16:22:51 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+STYLE: <link rel="stylesheet" type="text/css" href="../css/org.css" />

#+TITLE: 大国游戏卷II 花开花落(Shifts of Powers)


#+AUTHOR: 井底望天




** 【编者文代序·制高点】
#+include "【编者文代序·制高点】.org" 
** 【友人评序】
#+include "【友人评序】.org" 
** 【本笔记写作前中后大事记略表】
#+include "【本笔记写作前中后大事记略表】.org" 
** 【纵论世界科技·经济·社会政策之30年轮回转型】
#+include "【纵论世界科技·经济·社会政策之30年轮回转型】.org" 
** 【第一篇·多事秋】
#+include "【第一篇·多事秋】.org" 
** 【第二篇·高加索】

** 【第三篇·里海油】

** 【第四篇·欧罗巴】

** 【第五篇·俄罗斯】

** 【第六篇·新能源】

** 【第七篇·统众藩】

** 【第八篇·经济圈】

** 【第九篇·理结构】

** 【第十篇·正金融】

** 【太阳能产业之三国演义】

** 【卷后录：里海能源·高速铁路·地中海同盟·中国创造的呼吁】

** COMMENT content


【写作日期】2008年8月13日——17日            








 









第二篇


京华十里路，璀璨追汉唐。
酒酣当上马，西北斩恶狼。


十一

（作者本文写于2008年8月中上旬，时逢奥运会。——编者注）

炒得火热也吵得热火的北京奥运会，终于开场了。开幕式的一场视觉和听觉大宴，算是给世界人民上了一堂中国文明的幼儿园入门课。那气势磅礴的击缶和太极，估计除了令世人震撼和感叹之外，还会让有些人心生怯意，从此明白中国人民不可欺，国家不可侮。

这场超凡的文化启蒙，并不在于炫耀中国五千年文明的博大精深，造福亿万人类的无数发明，而是向世界显现“有朋自远方来”的开放胸襟，“朝闻道，夕死可矣”的求知欲望，以及“三人行，必有我师”的虚心态度。这种集古老和现代于一身，汇自豪和谦卑在一体，固守本族的传承，汲取他族的智慧，重新打造出一种更为辉煌的华夏精神的理想，当是我辈不可推卸的历史责任。那丝路的花雨，西洋的骇浪，恰恰是中国今天为世界贸易和制造大国的最佳注释。而张艺谋、陈其钢和蔡国强，这些世界一流的艺术家，开始为“中国制造”这个传自古代的金字招牌，注入新鲜的活力，为中国经济创造出一个契机，使中国产品在面对品质的困扰和西方的杯葛之后，如凤凰涅磐，浴火重生。这也要求全体中国人同仇敌忾，对任何想摧毁我们民族声誉的败家子奸商们，当杀无赦。 

笔者不想重复他人的吐沫，大谈神奇李宁的“夸父追日”，大个子姚明和小不点林浩的携手领军入场，或者水墨画卷之秀，唐乐盛装之浓，因为数年后，太多的人会忘记了这些细节，只留下淡淡的鸟巢印象，大伙儿又会一窝蜂的对春节晚会七嘴八舌和大放厥词。以中国的人口之多，艺术家的水准之高，原创之新颖独特，过两年玩出一个比这个开幕式更酷更型的盛宴，也不是什么难事。

如果中国人民一定要在这个奥运会中记得什么人的话，我提议的首选候选人是一位美丽姑娘，她的名字叫刘岩。这位无缘在开幕式现身为世界展现她的动人身姿的艺术家，当为奥运开幕式的第一英雄。如果奥运会后还需要任何计划实行的话，一个首选，就是从奥运收入中拿出一个基金出来，集全球医学专家之力，努力使她重新站起来，回到她热爱的艺术舞台。中国的真正复兴，不光是经济、军事和政治硬实力的崛起，还要包括文化、艺术和思想的重振。每一位艺术家，就像我们民族历史上灿如星海的诗人、画家、作家、名伶等等，都是值得全民族珍惜的国宝，没有对他们每一位的爱护，我们民族的前途就不会光芒四射。

我们还要记得16位在喀什献身的武警战士，没有他们的牺牲精神，就没有让我们可以从容举办奥运会的和平环境。我们还应该记得为奥运会做出奉献的所有志愿者们，希望其中可爱的大学生们，可以自豪的在他们将来的求职履历中，放上“北京奥运志愿者”一行，为他们加分。我们更应该记得所有参与建设北京鸟巢、水立方、盘古巨龙、歌剧巨蛋，央视大裤衩的外省民工，还有为了北京这些建设改造而不得不迁移的北京居民，正是这些一个个小我的牺牲，才可能造就我们民族今日的繁荣昌盛。而我们未来的政策，就是如何让这些为社会的整体利益而牺牲的人们，得到最好的补偿，令我们的社会成为一个真正意义上的和谐社会。


十二

奥运会开幕式的另一个看头，就是美国软脚蟹总统布什和俄罗斯新沙皇总理普京比邻而坐。估计这两位仁兄除了欣赏表演，向自己的运动员挥手之外，还是有很多其他共同话题要谈的。而这些共同话题一定是关于俄罗斯与格鲁吉亚的战争，以及其背后的一大串一言不合就会问候对方老娘的头痛问题。

在笔者的《大国游戏》里，我并没有花太多的注意力在俄罗斯上，因为我认为这个世界未来真正的大国只有两个，那就是美国和中国。俄罗斯，和欧盟、日本、印度等等，都只能算是个“中”国，不时发发纵横捭阖的黄粱梦而已。

在解体之前，苏联一直就解决不了自己经济落后的问题，空有广袤的国土和资源，加上超过两亿八千万的人口，还是没法成为世界的超级经济强国。在十四个加盟共和国分裂出去后，剩下的俄罗斯的人口只是1.5亿左右，而且由于出生率低（理论上育龄女性平均2.2个孩子才可以保持人口稳定，而俄罗斯的这个数字2000年是1.25，2008年才恢复到1.40），男人寿命远远低于女人，每年的人口递减近百万 ，照这个速度下去，不到50年，俄罗斯的人口就会减少1/3，造成适龄工作人数缺乏，而经济情况会更加恶化。好在现在的石油和天然气价格飞涨，在某种情况下减轻了俄罗斯的经济压力 。
 
图 2.1 俄罗斯联邦境内人口自1992年以来的下降趋势图

所以，欧洲和北约认为在世界大国的长跑耐力比赛中，俄罗斯是百分之百的输家，理由无它：人太少。欧洲各国与俄罗斯不同，面对人口劳力短缺的困境，欧洲采取是有限制的吸收高科技移民人才的政策，补偿适龄劳动力不足和人口老化带来的挑战。这些国家在吸收来自东欧国家和亚洲国家如中国、印度等人口大国的人才上的做法很有成效。当然他们面临的主要挑战是，如何融合来自土耳其、阿拉伯和北非的信仰伊斯兰教的移民，解决这些人带来的宗教冲突。如果解决不好的话，社会动荡是一个大的隐患。

俄罗斯则对来自其他国家的移民心怀疑虑。本来俄罗斯自身的人才，由于自然条件和经济条件的原因，有向西欧和美国移民的趋势，而俄罗斯要吸引来自欧洲的移民又不是一件易事。只有来自亚洲，尤其是中国的移民，勤劳肯干，哪里有肥哪里长，在西伯利亚开垦出一片天地。但是因为皮肤颜色不同，以及此降彼长带来的俄罗斯族人口数量上日益明显的劣势，使得许多俄罗斯人对此胆颤心惊，敦促政府下令限制中国商人和农民的进入。结果这种只出不入的情况，当然使人口流失更加严重。而由于公共医疗系统在90年代剧烈变革中的瘫痪，艾滋病的流行，再加上俄罗斯人狂饮伏特加的天性，都使得国内人口大幅减少。
 
图 2.2 北约东扩图 紧逼俄罗斯

记得过去当北约将军们和他们的俄国同僚开定期碰头会的时候，欧洲人总是要以这样一个笑话开始：“中（国）芬（兰）边界无事否？” 。每次苏俄的将军们就会恶眼瞪着笑得快岔气的西方将军们，无可奈何。

在苏联垮台和各加盟共和国独立出去之后，俄罗斯有一东一西两个忧虑。东边的是担心中国势力北上吞并西伯利亚和远东（中国众多的人口自沙皇以来就一直是地广人稀的俄罗斯人最担忧的一个问题之一），这个最近十几年来俄罗斯的报刊一直在嚷嚷但除了炒作中国农民在西伯利亚的农业经营以外，尚未在现实中发生真正让俄罗斯头大的事件；西边的就是北约的东扩，西方势力不光接管俄罗斯的前附庸国家如东德、波兰、捷克、斯洛伐克、罗马尼亚、保加利亚和匈牙利，又肢解斯拉夫小弟南斯拉夫，拿走克罗地亚、斯洛文尼亚、波斯尼亚、马其顿、黑山和科索沃，去手断脚，只剩下一个光秃秃的塞尔维亚，估计也迟早是北约的囊中之物。


十三

而俄罗斯的那些前苏加盟共和国随从也同样逃不出北约的手心，波罗的海三国爱沙尼亚、拉脱维亚、立陶宛和东欧的斯洛文尼亚、斯洛伐克、保加利亚、罗马尼亚，于2002年布拉格高峰会上被邀请加入北约，并于2004年3月29日在伊斯坦布尔高峰会前正式入会。北约还和波罗的海三国签署了波罗的海空防协议，由各国轮流提供四架战机执行针对俄罗斯的空中预警任务。当然这些姿态都是对俄罗斯象征性的威胁。由于俄罗斯帝国在1917年失去了芬兰，再加上波罗的海出口被德国、丹麦、挪威和瑞典堵住，这块西北地区对于俄罗斯的战略地位就已经削弱了。而俄罗斯和北约基本上互相识相，使这三个小国成为事实上的非军事缓冲区。同时俄罗斯的传统重镇圣彼得堡有能力箝制任何来自于西北方的威胁。
 
图 2.3 东西乌克兰分界图及克里米亚的位置

俄罗斯的真正心脏区在更南部的白俄罗斯和乌克兰，失去这两个地区将使莫斯科的前门洞开。虽然俄罗斯历史上两次面对西方入侵，最终都获得胜利，但都是以焦土政策为代价的。在莫斯科拖垮拿破仑，在斯大林格勒打败希特勒，用的都是同归于尽的战法，自身的元气也大伤。虽然西方的颜色革命在乌克兰成功，但是乌克兰在宗教、地域和人民上，是一个亲西方和亲俄罗斯的势力五五开的国家。和许多国家的民族混居不同，乌克兰基本上可以从首都
基辅、切尔卡瑟（Cherkasy）、文尼察（Vinnytsia）以西，和切尔尼戈夫（Chernihiv）、波尔塔瓦（Poltava）、克罗沃拉德（Kirovohrad）、敖德萨（Odessa）以东，清晰得划出一条线，西边亲西，东边亲俄。既然亲西方的天主教徒占据西乌克兰要加入北约和欧盟，俄国就让亲俄罗斯的东正教徒占据东乌克兰，继续捍卫俄罗斯心脏莫斯科地区，并保持在克里
米亚维持一支全俄唯一有效的舰队黑海舰队。即使乌克兰东西不分裂，如果她想继续向西方投怀送抱的话，俄罗斯就可以通过挑动克里米亚独立来制造事端，引发一场战争。

可叹俄罗斯虽然是一个大国，但连一个像样的出海口都没有。波罗的海被敌国环抱，而且长年结冰，和东边遥远的海参崴一样（海参崴主要是因为西伯利亚铁路过长，补给困难的问题），没有太大的用处。本来当年中国东北，俄罗斯帝国已经抢下了暖水军港旅顺，可以通过当时的南满铁路向北连接海参崴，只是后来在1904年的日俄战争中被日本打败，计划落空。在二战结束后，斯大林又旧梦重燃，希望通过建立中苏联合舰队的方式，持续性地租用军港。结果这个提议被中国拒绝，俄国只得在1955年放弃了这个天然良港。俄罗斯对暖水军港的渴望，还表现在后来越南统一后对金兰湾的租用上。那时苏联已成强弩之末，但1979年，苏联太平洋海军入住金兰湾后，还是与美国在菲律宾的苏比克海军基地形成隔海打擂台的架势。只不过俄罗斯这个西方人鄙夷的欧洲经济病夫，十年后就国家破产，建立全球系统，海外称霸的梦想破灭。
 
图 2.4 俄罗斯历史上、现在和未来规划的重要军港示意图

最近几年，在普京的中兴下，俄罗斯经济稍有起色，就重点大国梦。为了针对美国在东欧的波兰和捷克设置全球导弹防御系统，俄罗斯先是恢复了战略轰炸机巡航，然后又大谈重返越南金兰湾，又再次走进美国鼻子下的古巴乃至石油后院委内瑞拉，增加与美国讨价还价的砝码。


十四

在1783年成功兼并了克里米亚后，在黑海的塞瓦斯托波尔，俄罗斯终于有了一个比较理想的天然良港。但是驻扎在这里的俄罗斯黑海舰队，却首先就要受到奥斯曼土耳其帝国在博斯布鲁斯海峡控制，而即使通过该海峡，进入地中海，南边去红海进印度洋的出口苏伊士运河，以及西边去大西洋的出口直布罗陀海峡，又被英帝国堵住。这就造成了俄罗斯帝国和英帝国之间为争夺暖水港口而展开的大游戏对决（The Great Game），这个游戏从西边的巴尔
干土耳其，经高加索波斯，一直玩到东边的中亚阿富汗印度乃至中国的新疆西藏。
 
图 2.5 19世纪40年代起沙俄南下的海洋之路受阻情况及在陆地上发动的与英帝国的全面博弈（大游戏）

俄罗斯帝国首先在南边通过一系列对波斯帝国的战争实现南下策略。在第一次俄波战争后，通过1813年签订的久里斯坦条约，俄罗斯抢下了阿塞拜疆、格鲁吉亚东部，和现在还归属俄国的达吉斯坦。而后又通过一系列的战争，控制了整个格鲁吉亚和亚美尼亚。但俄国的南下受到了英国的对抗，在伊朗的中部受到了阻止，结果是俄国和英国两分伊朗，各控北南，但是都没法独自兼并，只能通过对伊朗王室的软硬兼施，互相箝制。俄国和英国在阿富汗的对抗同样陷入僵持状态。而在中国的西部，俄国控制新疆，英国控制西藏，也是寸土不让。这种状态直到20世纪初德国在欧洲崛起迫使俄罗斯和英国不得不握手言和后才改变，使正在火热进行的中国瓜分游戏暂停，才有中国保住了对新疆和西藏的主权。虽然中国在西藏失去了对藏南的控制，在新疆也失去了伊犁西部领土的主权，而且今天仍然要面对没有彻底平息的藏独和疆独分裂主义运动后遗症，但相较于这个大游戏对其他地区造成的损害和深远影响，中国人要幸运得多。

正是由于地缘政治游戏玩到一半被英国作梗，中途卡壳的原因，格鲁吉亚变成了俄罗斯的另一个软肋。笔者对格鲁吉亚的第一个感受是，地方虽小，人才辈出。苏联枭雄斯大林就是格鲁吉亚人，后来在戈尔巴乔夫时代出任苏联外交部长并在1995年后出任母国总统的的谢瓦尔德纳泽也是格鲁吉亚人。至于西方，曾在海湾战争中立下奇功，并于九十年代中期出任美军参谋长联席会议主席的沙利卡什维利将军，还是格鲁吉亚人。

格鲁吉亚与俄罗斯的关系，可以说是剪不断，理还乱。本来在俄国势力兴起前，位处西亚北端的格鲁吉亚是西部的土耳其奥斯曼帝国和南部的波斯帝国的双雄逐鹿之地，为求自保，不得不借助俄罗斯帝国的崛起作为权宜之计。虽然格鲁吉亚于1801年在名义上以多个小公国先后加入的形式并入俄罗斯帝国，但和俄国人时而和睦，时而打架的日子一直没有停过。直到俄罗斯帝国打败了奥斯曼和波斯后独大高加索，格鲁吉亚才彻底失去了独立地位。

格鲁吉亚本来和俄罗斯很相似，都是东正教国家（这也是为啥他们会借助俄罗斯来抗衡伊斯兰帝国奥斯曼和波斯的原因）和农奴制经济。俄国贵族刚开始急于把格鲁吉亚融入俄罗斯其他地区，因而在政府管制上有些重手，对格鲁吉亚文化和风俗不够尊重，结果导致了1832年的贵族叛乱和1841年的全民造反。这些动乱迫使沙皇改变政策，派出了比较务实的维隆佐夫伯爵担任高加索总督，慢慢赢得了越来越西化的格鲁吉亚贵族的支持。

但是俄罗斯帝国在1861年决定放弃农奴制，开始追赶西方的工业革命，实现大规模工业化。可是它1864年在格鲁吉亚推行的农奴制改革，让农奴主贵族和农奴都很不满意。农奴主贵族因为没有了来自农业的收入，穷了，而因为格鲁吉亚的农业生产条件极差，取消农奴制后农奴们的生活也没有太大的改善，农奴们也恼火。历史的蝴蝶扇动翅膀，谁也没想到这个本来试图消灭农奴制的不成功的经济改革，会为后来百年的革命、叛乱还有战争种下祸因。


十五

正在这世道轮换，旧制式微之际，由于工商业的兴起，本来来自外族，有第二犹太人美誉的经商民族亚美尼亚人，聚焦在格鲁吉亚城市区。由于之前因为身份世袭，已经垄断了商业贸易和手工业，这商人民族就在这个历史变革下得到了最大的好处。结果由于对俄罗斯皇帝指手画脚强行改革政策的不满，添上对外族亚美尼亚人经济强势的不愤，格鲁吉亚民族主义就势兴起。
    
图2.6  左：19世纪商人民族亚美尼亚人从土耳其移入格鲁吉亚；右：格鲁吉亚本地山地农牧民

其实如果看一下中国藏区当年的情形，似乎有某些相似之处。共产党在西藏之外的藏区取消了农奴制，造成了对农奴主贵族的利益损害，因此对政府不满。正如格鲁吉亚和俄罗斯是宗教同胞，其憎恨的对象不是针对俄罗斯民族而是推行取消农奴制的沙皇政府，藏区的农奴主叛乱打出的也是“打倒‘红’汉人”的口号。不过宗教因素也有添乱的成分，格鲁吉亚教廷不愿意把教权交给俄罗斯东正教大牧首，而俄罗斯资本主义改革的主要得益者——外人亚美尼亚族信奉的是基督教（非东正教），改革的结果就是让向来政教紧密结合的东正教国家俄罗斯的最高统治者——沙皇的权威降低，再蔓延到整个俄罗斯境内，便出现类似中国清朝末期的体制之争，各派人士如保皇党、君主立宪派、宪政派、布尔什维克派及其他各种杂七杂八的派逐渐兴起，导致了政局不稳。

当然中国取消农奴制的政策比格鲁吉亚的结果要好，其中重要的原因就是藏区的农奴们真正享受到了经济上的好处。而中国的宗教政策除了针对当初参与叛乱的寺庙和喇嘛外，在文革以前都比较合理，对藏族文化和风俗都非常尊重，并未造成民族为划线的分野。反而是解放军里的藏族部队骁勇善战，叛乱队伍里的“白汉人”（国民党军人）也冲锋在前，总之是在为自己的政治信仰而不是民族而战。而经济上获得收益，政治上提高地位的西藏农奴们对叛乱不支持，也是这些叛乱不成气候的一大原因。

反倒是在中国经济开放后，藏区的一些其他少数民族，就像当年格鲁吉亚城市里的亚美尼亚人一样，在经济上收益较多，而这个其实是刺激藏族民族主义的一个主要因素，并已经为人所领悟，受到当前某些藏族干部在某种程度上的支持。而现今某些藏族的知识分子，也开始挑动，将民间对政府的一些不满情绪（比如说不接受达赖喇嘛的和谈条件），上升为针对汉民族的仇恨。这些人开始言必称“卫藏”（西藏地区）、“安多”（Amdo，青海地区）、和“康”（Kham，四川西部和西藏最东部如昌都等），不承认中国官方的省市地县区名，把一些不存在的旧地名喊来喊去，而且开始以文学的名义来篡改历史，试图美化旧农奴制的残酷，发表一些关于过去的农奴们如何怀恋美好旧社会田园牧歌的生活的故事（有趣的是他们都使用的是“据老人言”这种模糊文字来改写历史，而采访的都是旧西藏上层社会的老人）。这种企图挑动民族主义，导致中国内部各民族冲突的行为，必须加以警惕。

再说当年的格鲁吉亚，这个经济问题就演变成覆盖经济、政治、宗教和民族的大难题，越滚越大，终于导致1905年格鲁吉亚大暴动，而这个山地小国的大暴动又跟火药桶连环爆炸一样带动了俄罗斯本土的1905年革命，最后迫使沙皇政府放松控制，实施改革。于是一位叫杜卡斯维利（Djukashvili）的共产党领导人开始暂露头角，他，就是后世举世闻名的斯大林。由于格鲁吉亚上个世纪就已经和俄罗斯帝国有过三反目三进宫的经历，反叛经验丰富，所以在俄国革命爆发后，格鲁吉亚也就趁着主子内乱宣布了独立，但随着苏联红军打败了旧俄白军重鼓收复故土之势，就只好作罢。在随后的几十年里，苏联对它这加盟共和国格鲁吉亚、亚美尼亚、阿塞拜疆等等，这里划过去，那里划过来，搞得你中有我，我中有你，再加上本来这些高加索地区的历史历来就是一锅大杂烩，搞到后来一闹独立，大家都可以翻开历史书，公说公有理，婆说婆有理，找出对自己有利的部分大肆宣传，最后兵戎相见。
    
图2.7  俄国1905年革命与当时的斯大林


十六

    二十年后，纳粹德国杀进苏联想到高加索抢石油 ，格鲁吉亚的一帮人又不给老乡斯大林面子开始闹独立，配合德军作战成立了格鲁吉亚军团（正是今天美军那位沙利卡什维利将军的老爸领军），结果在德国打败了后又不得不老实了。而斯大林的大面子和对民族团结的倡导，使格鲁吉亚人有七十万参加红军走上战场（战死三十五万），保家卫国，令其民族主义终于消失。
 
图2.8  二战期间的格鲁吉亚军团、首领沙俄流亡人物沙利卡什维利亲王、其子美国沙利卡什维利将军

可是好景不长，赫鲁晓夫起来清算斯大林，许多对斯大林的攻击就转化成对格鲁吉亚人的自豪感和民族自尊心的攻击，引发了1956年的年轻格鲁吉亚学生走上街头，抗议赫鲁晓夫。数千学生自动聚焦在第比里斯的斯大林雕像前，开始喊口号：“伟大的斯大林万岁！伟大的列宁斯大林党万岁！伟大的格鲁吉亚苏维埃万岁！”。喊口号运动很快蔓延到整个共和国，最后被赫鲁晓夫镇压，上百学生丧生。这个捍卫国际主义共产党领袖名誉的事情倒阴差阳错的再次引发了格鲁吉亚新时代的民族主义兴起。而赫鲁晓夫偏偏个人倾向于反民族主义，在反斯大林之后很热衷于搞地方分权政策，这就给了格鲁吉亚族的共产党干部乘机发展地方势力的机会，和民间的草根民族主义里应外合（有点像80年代的西藏政策）。

而和中国相似的是，在苏联计划经济的垄断下，这些地方势力的发展使资本主义的苗开始刷刷的长起来了，既享受着其他地方大工业大计划提供工业品的好处，又可以开个体户搞一点工艺品葡萄酒茶叶等苏联紧俏的消费品，格鲁吉亚居然变成了全苏联个人生活水平提高最快的地方（想想苏联科学院专家们能发明原子弹核电站却要去排队抢购南斯拉夫裙子彩电就知道格鲁吉亚会如何占便宜）。赫鲁晓夫对格鲁吉亚的放手，当然也是因为自己上台之初在斯大林一事上和格鲁吉亚人民搞得太僵，现在井水不犯河水，大家相安无事，所以就给了格鲁吉亚发展小生意资本主义的空间。当然，经济发展快了，接着就是政府腐败和官员贪污盛行，引发了老百姓的不满。这时未来的外交部长及总统谢瓦尔德纳泽闪亮登场，从1964年到1972年出任格鲁吉亚内政部长（相当于公安部），凭借其打击贪官污吏的铁腕手段赢得了民心，并导致了格共第一书记，贪官总头目马扎万那泽下台，自己被提升成第一把手。

老谢是一个相当能干的政治家，在他的领导下，格鲁吉亚经济高度发展，政府腐败官员纷纷落马，格鲁吉亚成了全苏联的经济之星，令格鲁吉亚人个个扬眉吐气，开始恢复因为斯大林被人打翻再踩上一万之脚后丧失的民族自尊心。而希望分裂出苏联的势力也就慢慢开始成型，其中一个原因就是全苏联被克格勃打击的异议分子，从四面八方逃到了格鲁吉亚这个相对自由的地方。谢瓦尔德纳泽则靠着他个人的能力，镇住了各派势力，保持了经济增长，稳住格鲁吉亚这个大船。
    
图2.9  左：1956年事件纪念碑；右：苏联1977年宪法通过时的纪念邮票

但格鲁吉亚的独立势力已经愈来愈强，里程碑事件就是1977年苏联对1936年的宪法作出第四次也是最后一次的修改，其中一个问题是其中第75条的语言条款。本来所有苏联的加盟共和国都以俄语和当地民族语言共同作为其官方语言，只有外高加索的三国：格鲁吉亚、亚美尼亚和阿塞拜疆例外，只定义自己的语言为唯一的官方语言。而1977年对这个宪法条款的修订，就是要解决这个独特的现象，把俄语添入这三个加盟国的官方语言，享受和格鲁吉亚语、亚美尼亚语和阿塞拜疆语同等的地位。


十七

1978年苏联按例行惯例让各共和国法院依次点头认可这个新宪法修改案的时候，阿塞拜疆毫无意见，亚美尼亚有些小的不愉快，但是格鲁吉亚反应剧烈，闹得鸡飞狗跳。其实莫斯科应该是要预见到这个情况的，因为两年前苏共中央在格鲁吉亚推行俄语教育的行动，已经受到过很大的杯葛。结果1978年4月14日，格鲁吉亚的数万大学生走上街头，要求本地政府拒绝接受俄语作为官方语言之一。这次抗议和1956年那次一样，很快就出现了军队和学生的对峙，一场更大的流血冲突似乎无法避免。

正在这关键时刻，老谢书记挺身而出，一方面劝告学生不要把情况弄到不可收拾，一方面赶紧联络莫斯科，要求暂停对宪法的认可程序。莫斯科当时对事态的发展非常震动，又因为当时面临的国内问题重重，决定还是不要恶化局势，采取了让步的办法化解了这场冲突。而这个后来被称为“格鲁吉亚语言日”的日子，就成了新格鲁吉亚民族主义的开端，并导致了后来1991年格鲁吉亚脱离苏联的独立。

不过苏联不愧是个超级民族大国，格鲁吉亚固然在大家庭里是少数民族小兄弟，但是在格鲁吉亚的自家庭院里还有少数中的少数民族。于是格鲁吉亚的各少数民族对格鲁吉亚小老哥得势的局面非常不安。当时的少数民族地区，已经对格鲁吉亚越来越强的民族主义心怀疑虑，因此对苏共中央这个无先例的重大让步非常恼火。从历史上看，深受布尔什维克课本教导，“民族自决权”成为其政治正确教条和紧箍咒的苏共中央，缺乏不惜一切代价保持民族团结和融合的决心。在格鲁吉亚这个领头闹事的地区做这样的让步，不仅没有平息分离势力的不满，反而鼓励了分离势力的成长壮大，导致了全苏联的各少数民族都开始寻求独立。而既然老大苏共中央如此，那么俄罗斯人这个主体民族，虽然在很多其他加盟共和国里住着不少族人，但对上层维护国家统一的决心就不太有信心了，也不会为了国家的统一而战了。最后叶利钦站在莫斯科街头上的坦克上面大手一挥，于是俄罗斯帝国树倒猢狲散，几百年基业毁于一旦。

再话说苏共中央的重大让步令第比利斯暂时平静下来，但格境内黑海边上的少数民族地区阿布哈兹怒火万丈，要求退出格鲁吉亚，加入北边的俄罗斯苏维埃联邦共和国。这个要求自然被莫斯科拒绝。但打一手拉一手，莫斯科不得不通过拨下巨款，在基础设施落后的阿布哈兹大修公路，投资各种工程建设，并成立专门的阿布哈兹大学，给予更多文化上的自主权，不强行推广格鲁吉亚语，而实行阿布哈兹语、格鲁吉亚语和俄语各自独立的部门。在政府职位上实行名额制，保证阿布哈兹族有足够的政治地位，以求平息不满。
 
图2.10  左上：格鲁吉亚及周边地区民族林立；右下：阿布哈兹、南奥塞梯和阿扎尔地区示意图

有讽刺意味的是，当格鲁吉亚族的民族主义情绪高涨时，阿布哈兹族和奥塞梯族自身的民族主义也伴随着兴起，最后使各民族之间的冲突逐渐升温。苏共被这样一个怪圈弄得团团转：因为对格鲁吉亚的民族主义的要求让步导致了阿布哈兹的不满，所以就必须向阿布哈兹的民族主义要求让步，结果又引发了住在阿布哈兹自治地区的格鲁吉亚族起来抗议。此时一批格鲁吉亚知识分子为抗议在阿布哈兹地区掌权的阿布哈兹族共产党干部歧视格鲁吉亚族人士，就向本地总书记老谢和当时苏共领导人勃列日涅夫写信请愿。


十八

于是八十年代到来了，街头抗议更多了。格鲁吉亚人一方面要求莫斯科给予更多的自主权让自己作主，另一方面又要求阿布哈兹人放弃其自主权而让格鲁吉亚人为他们作主。老谢则左右逢源，一方面支持民族主义的温和派在保护文化、语言和历史上的要求，一方面又镇压要求彻底独立和推翻苏维埃制度的激进分子。又由于在他的治理下，格鲁吉亚的经济一路增长，所以在层出不穷闹出这么多的抗议事件后，他不光没有受到任何处罚，还由于他的摆平各方势力的能力受到赞赏。在戈尔巴乔夫上台推行开放改革政策后，老谢时来运转，于1985年上了一层楼，出任苏联的外交部长，到西方世界为苏联争取合作伙伴，来支持戈尔巴乔夫的新思维新政策。
   
图2.11  左：戈尔巴乔夫和他的外交部长谢瓦尔德纳泽；右：改革新思维宣传画

偏偏在他离任之后接棒的帕提亚希维利是一个保守且无能的庸才，完全无力处理在开放改革政策下带来的各种挑战。结果到了八十年代末，格鲁吉亚民族主义者和其他少数民族主义者之间从政府到民间越斗越狠，闹到枪战的地步。而南奥塞梯则是暴力冲突最火热的地方。本来历史上，除了1918-1920年间奥塞梯族和格鲁吉亚族曾经打得你死我活以外，两族人民还是和平地住在一起的，互相通婚，融合得比较好。但随着格鲁吉亚人越来越激进，奥塞梯人也开始了他们的独立运动。

正如前文提到，在俄国十月革命期间，格鲁吉亚曾宣布独立，由社会民主工党的少数派孟什维克（由马尔托夫领导，与列宁领导的多数派布尔什维克对立）掌权，成立了格鲁吉亚民主国。而奥塞梯人则组成了全国委员会，讨论在俄罗斯的北奥塞梯和在格鲁吉亚的南奥塞梯组成一个统一的自治政体。这个组织很快就卷入了苏共内部的意识形态之争，但布尔什维克最终掌握了决定权，并主张将南奥塞梯并入俄罗斯。这样就很容易明白为啥大家要开劈了，一是南奥塞梯应该留在格鲁吉亚还是俄罗斯这个领土问题，一是孟什维克和布尔什维克全方面针锋相对的意识形态斗争。

当然落实到实处，问题就更要复杂许多。比如说，亲俄罗斯的布尔什维克奥塞梯人宣传说，当地贫苦的农民（全体奥塞梯人大概都合乎这个标准）不需要向苏维埃政府交税。南奥塞梯的农民们听得心花怒放，可以想象，当孟什维克的格鲁吉亚政府官员带着军队来强行收税，宣布要对暴力抗税的农民格杀勿论的时候，这些农民们会有怎样的反应。于是在1918年3月15日，南奥塞梯的农民们发动了起义，并一度顶住了派来报复的格鲁吉亚人民卫队的攻打。农民军4天后杀进了省城茨辛瓦利，屠杀了全城的格鲁吉亚族人，并将城市抢劫一空。格鲁吉亚军队终于在3日后夺回了首府，自然开始了报复性的民族屠杀。南奥塞梯农民的暴动最终被扑灭，随后而来的是残酷的打压行动。最后所有的奥塞梯人把孟什维克和格鲁吉亚人等同起来，并完全支持布尔什维克。在随后的两年里，奥塞梯人的暴动规模愈来愈大，但每一次都被格鲁吉亚残酷镇压，造成大量死伤。


十九

 
图2.11  左上：1918年孟什维克为主的格鲁吉亚民主国成立仪式；右下：1921年红军灭亡该政权

可当时列宁希望和格鲁吉亚民主国保持和平，再加上奥塞梯的暴动屡遭失败，布尔什维克不愿妄动。结果是南奥塞梯人不得不逃过边境进入俄罗斯。直到苏联红军在俄罗斯全境内彻底打败了白军后，才开始结集在北奥塞梯。红军在1921年对格鲁吉亚发动了战争。在苏联红军向南推进中，奥塞梯人不断加入战斗，最终于2月彻底打败了格鲁吉亚军队，4月成立了格鲁吉亚苏维埃。新政府决定成立南奥塞梯自治区，将奥塞梯族地区、奥格混血人民和一些纯格鲁吉亚族村镇划归奥塞梯人自治，并送了茨辛瓦利这个奥塞梯人本占少数的城市给他们作为首府。

虽然当时的各次战斗和报复行动很残酷，格鲁吉亚人对一些村镇采取了三光政策，导致了超过五千奥塞梯人死亡，占奥塞梯族总人口的8%。但和民族仇恨自古根深蒂固的阿布哈兹不同，格鲁吉亚和奥塞梯两族之后基本上做到了和睦共处，而在自治区学校内可以使用和教授自己的奥塞梯语，基本上做到了相安无事。但随着70-80年代格鲁吉亚民族主义兴起，恐惧万分的奥塞梯人开始把这段历史搬了出来，指责当年格鲁吉亚人搞种族屠杀。而格鲁吉亚人就反驳说，死人的数字被夸大了，虽然当年杀你们杀得很厉害，但是是你们先开杀的，而且你们是俄罗斯用来搞乱格鲁吉亚的工具。

吵吵嚷嚷之间，发生了一个重大事件。先是1989年3月，数千阿布哈兹人走上街头，要求从格鲁吉亚退出去。紧接着是格鲁吉亚的独立建国势力，以莫斯科支持阿布哈兹人为借口，于4月走上街头，要求格鲁吉亚政府镇压要求脱离的阿布哈兹势力，同时要求自己从苏联独立出来。这个抗议活动在9日到达高潮，导致格鲁吉亚政府完全瘫痪，当地警察不再听命，同情示威者。万般无奈之下，莫斯科只好通过驻高加索的苏军来执行维持社会次序的任务。当时虽然苏军乘坐坦克和装甲车进入市中心，但士兵并未荷枪实弹，只是手拿警棍和铁锹（美国当年在洛杉矶平乱可是真枪实弹），围住示威者，步步进逼，但都会留出一条路，让示威者后退。在这之前，没有一位格鲁吉亚政客站出来企图化解局势，只有格鲁吉亚东正教大主教劝告示威者撤离，但没有人愿意听他的废话。

结果虎狼之师的苏军士兵不知道什么叫做适可为止（这也是为啥警察在这方面是专家），于是有20名年轻少女和老年妇女在清场的过程中丧生。其中一位16岁少女被大铁锹拍脑袋的过程还被反对派录了下来，到处播放。其他十九位死者的脸也有伤痕，被格鲁吉亚电视台大肆播放。民族主义反对派指责苏军过度暴力。其他的男人们虽然有人受伤，但没有死亡。全格鲁吉亚罢工罢课罢市开始了，悼念日搞了40天，此间虽然政府宣布了格全境戒严，但抗议活动一直没有消停。
 
图2.12  格鲁吉亚首都第比利斯民族主义运动的当时照片和宣传画，这场运动给苏军以致命一击

这时候苏军站出来说，大部分死者是在慌乱中被人群践踏而死的。于是有一位苏联人民代表大会议员索布恰克（此公后来出任了列宁格勒市长，大笔一挥把自己这块宝地改回老名圣彼得堡，并提拔和任用了一位英才普京做他的副手，还帮助叶利钦起草了新俄罗斯联邦宪法，后来又收了一位学生梅德韦杰夫）领导了事件的调查。这位戈尔巴乔夫的改革同路人，调查了一会，得出苏军“过度残暴”的结论，并将责任人士交给了司法部门审判。

 
图2.13  左上：调查格鲁吉亚事件的索布恰克当年的照片，普京为其助手； 右下：“民主派”索布恰克在苏联人民代表大会上作证认为苏军和强硬派利加乔夫应承担责任； 左下：普京上台后逢索布恰克去世特意为他发行的悼念邮票。索布恰克的“圣彼得堡帮”其实在苏联解体中起了关键作用

二十

这一自打嘴巴的调查结果造成了苏共中的强硬派在人民中失势，并从此使得政府难以再使用军队来应付国内的骚乱。本来莫斯科一口咬定是示威者先动手，但是5月评上国家总统新职称的戈尔巴乔夫，号称要用最高领导人名义为整个事件承担责任，并宣布格鲁吉亚民族主义分子毫无过错！还把怪罪的矛头直指那只不过是奉命行事的军队，这直接导致后来苏联军队对国家分裂毫不关心。

这一事件也迫使格鲁吉亚共产党政府集体辞职，使极端民族主义势力趁势在政府里占据了重要位置。而在戈尔巴乔夫的改革开放政策下，自由主义尤其是反苏论调在本来受官方控制的媒体里受到了鼓励。于是在几个月后，格鲁吉亚最高会议在11月正式谴责了1921年苏联对格鲁吉亚民主共和国的占领和兼并。而毫不示弱的奥塞梯人则宣布自己成立奥塞梯苏维埃社会主义共和国，要求格鲁吉亚把其地位从自治区提高到共和国。格鲁吉亚的反击是，宣布格鲁吉亚语为整个格鲁吉亚的官方语言，要求强制执行，并宣布不得成立任何地区性的政党，避免奥塞梯民族主义者在他们那块领地里名正言顺的控制局势。

在整个苏联风雨飘摇的情况下，戈尔巴乔夫再起新政，决定在1990年2月放弃一党政治，开始允许各共和国进行多党民主选举，使各加盟共和国里的民族主义者纷纷上台。结果各共和国开始与中央政府进行法律战争，宣布中央法律凡是和地方法律抵触，即为无效。并在当地经济中增加控制，拒绝向中央政府交税。而过去由中央计划委员会制定的物质调配方案，完全在各地坐大的局面下失效，使整个国家经济的供应和需求网崩溃，造成了经济齿轮卡住停转，人民生活水平极度艰难，使人民对苏联政治体制的不满更加增大。在开始民主选举后的一个月，1990年3月，立陶宛和爱沙尼亚首先宣布独立，开始了苏联崩溃的过程。而格鲁吉亚的选举在当年10月进行，结果是反对派领袖加姆萨胡尔季的圆桌同盟当选。掌握大权的他遂趁机在1991年3月掀起了全民公投运动，得到了接近98%人民（当然不包括阿布哈兹、奥塞梯等地区）支持独立的满意结果，便在1991年4月9号，即苏军镇压两周年之际，宣布独立，并以当日为格鲁吉亚国家团结日，作为一个公众假日。
 
图2.14  格鲁吉亚及格鲁吉亚内部各个自治共和国在从属于苏联和独立后的旗子

    
图2.15  加姆萨胡尔季宣布独立

加姆萨胡尔季则在苏联正式崩溃后，发动了将苏军基地赶出去的运动。但他的铁腕手法惹怒了其民族主义阵营里的旧同僚。新怨爆发，加上苏军留下大量军火，格鲁吉亚里的各派势力纷纷组织自己的民兵武装（就像今天伊拉克一样），改文斗为武斗，为了争权夺利而开始了火并。反对派成功的在1991年12月发动了武装政变，将加姆萨胡尔季和他的武装支持者包围在政府大楼，最后老加从下水道逃跑成功，在1992年1月只身飞出重围到了车臣。
   
图2.16  左：老谢就职；右：老谢总统看望前线战士

格鲁吉亚新政府缺乏得力的领导人，于是邀请已经因为苏联解体而失业的外交部长，被称为“高加索银狐”的老书记谢瓦尔德纳泽，回来主持大局，成为格鲁吉亚的新总统。在这段时间里，格鲁吉亚政府也派出军队和民兵，于1992年8月去阿布哈兹镇压分裂主义势力。刚开始格鲁吉亚的战绩还不错，但是从北高加索地区陆续有大量的阿布哈兹人的兄弟民族，组成外籍民兵军团加入反格鲁吉亚的战场，很快将战局逆转过来。

























【写作日期】2008年8月13日——17日            








 











 

图3.0  俄罗斯/里海对欧洲的能源供给路线图：石油（粗）和天然气（细）
两大类能源的具体路线和特定区域的规划，请读本卷三、四、五篇



第三篇


海西广袤地，四野皆苍茫。
烟尘骤然起，前军报擒王。


二十一

在这些赶来参战的外籍兵团，其中就不乏出了名的雇佣兵民族——骁勇善战的哥萨克人，以及不惜绑着炸弹在身上和你同归于尽的车臣人，当然还有格鲁吉亚人指责的由俄军装扮成的假民兵。结果格鲁吉亚军队惨败，不得不从阿布哈兹撤军，并使得所有当地的格鲁吉亚族都被赶了出来。这场战争，导致了14000人丧生，30万人流离失所，但结果使阿布哈兹族和格鲁吉亚族有一个清晰的居住地理分界，所以再开打的机会要小得多。
   
图3.1  阿布哈兹战争情景和逃亡的格鲁吉亚族难民
 
图3.2  格鲁吉亚的相对位置和当时的沿黑海的战局

而格鲁吉亚在南奥塞梯的军事行动就要顺利得多，格鲁吉亚军队在放火烧毁奥塞梯人的数座村镇，造成数百人死亡后，奥塞梯人只能采用“打不过就跑”的战术，超过十万之众逃过边界，躲入俄罗斯的北奥塞梯地区。不过因为格鲁吉亚在阿布哈兹的惨败，造成了两个后果，一个是在西南部接近土耳其，在黑海边与阿布哈兹南北相望的阿扎尔自治共和国（Adjara） 获得事实上的独立；二是逃到车臣的加姆萨胡尔季，卷土重来，和他的支持者开始了反政府的武装叛乱，并占领了格鲁吉亚的西部位于阿布哈兹和阿扎尔之间的港口波季。

在这个最关键的时刻，俄罗斯领导人叶利钦犯了一个极大的战略错误。加姆萨胡尔季的叛乱，给邻近的亚美尼亚和阿塞拜疆带来了不安，担忧格鲁吉亚的内乱会造成整个地区的动荡。俄罗斯当时还想用独联体的方式，重新构造出一个旧苏联的松散版，因此不得不掺和这件事。如果俄罗斯想达到目标，必须和加姆萨胡尔季摈弃前嫌，交好合作。虽然加姆萨胡尔季是一个激进的民族主义者，而且是格鲁吉亚独立脱离苏联的始作俑者，并拒绝加入独联体，但是当时的俄罗斯如果能选择支持他和格鲁吉亚政府对峙，并控制黑海港口城市波季，就可以把独立的阿布哈兹和阿扎尔这一北一南连在一起，由俄罗斯控制，则格鲁吉亚政府必然不战自降，老加被送回总统宝座，看到自己整个海岸线落于它手的傀儡国主自然会知道自己的斤两，加入独联体也未尝不可，而格鲁吉亚整个沿海会名正言顺、货真价实的继续留在俄罗斯的手中。

但老谢的温和面孔对俄罗斯似乎更有吸引力，而且不能低估他在俄罗斯高层里深厚的私人关系，再加上他本人从来都倡导和俄罗斯保持友好的关系。结果俄罗斯出兵支持格鲁吉亚政府平叛，在1993年12月把加姆萨胡尔季的叛军全部消灭，其本人则以自杀收场。于是谢瓦德那泽以加入独联体作为报酬，来感谢俄罗斯的军事和政治支持。

很快俄罗斯就享受到了错误政策的苦果：在1994年，俄罗斯境内北高加索地区的车臣共和国为了脱离俄罗斯而独立，开始了第一次车臣战争，而格鲁吉亚这一次既忘记了独联体成员国的身份，也完全原谅了车臣勇士们两年前在阿布哈兹将格鲁吉亚军队杀得人仰马翻的国仇，对车臣战士提供避难所和各种物资资源。至于那个“希望保持和俄罗斯良好关系”的谢瓦尔德纳泽，自己也差点在1995年8月的民族主义者策划的一次汽车爆炸中被暗杀。为了继续保持他的权力，老谢虽然狠狠打击了企图干掉他的政敌，但不得不向国内强烈的反俄罗斯势力让步，其做法就是前门拒熊，后门入鹰，把美国引入自己所处的战略地位极其重要的外高加索区——这就是俄罗斯的南大门。

老谢在1995年11月和2000年4月的两次总统大选中，靠舞弊而赢了大多数。但是这只老狐狸已经开始廉颇老矣，力不从心。他的手下和家庭更是贪赃枉法，胡作非为，留下无数把柄。虽然接受了来自美国的大量军事和经济援助，并和北约签订了战略伙伴关系协议，要求加入北约和欧盟，做出和美欧亲如一家的姿态，但随着美国势力和影响越来越大，格鲁吉亚内部的亲美倒谢势力，开始抬头。



二十二

“亲美派”其中的佼佼者就是现任格鲁吉亚总统萨卡什维利。小萨其实是格鲁吉亚的亚美尼亚裔人，毕业于乌克兰的基辅大学法律系。在加姆萨胡尔季倒台后，出任格鲁吉亚政府的人权委员。后来被美国看中，由美国国务院的基金会弄到哥伦比亚大学学习，并在乔治华盛顿大学法学院毕业。他还同时拿到了法国斯特拉斯堡的国际人权学院的毕业证书。在1995年任职于纽约的大律所，几年后，被老谢在全球招募格籍青年才俊的物色活动中相中，回到格鲁吉亚，被选为国会议员。在他主导的委员会下，建立起一套新的选举制度，独立的司法系统和非政治的警察力量，而导致他名声鹊起，成为谢瓦尔德纳泽之后，第二受欢迎的政客。但是在2000年成为司法部长之后，他和内阁里的其他部长的矛盾越来越大，遂在一年后辞职，退出执政党，成立了自己的反对党。

萨卡什维利以新进的改革派和西化派的身份，对腐败的官僚体系提出挑战，再加上他受到美国和欧洲的大力支持，自然声势十分浩大。结果在2003年的大选中，通过指责执政党选举舞弊，小萨发动了大规模的街头运动，逼使了老谢辞职，完成了后来出名的玫瑰革命。
   
图3.3  2003年格鲁吉亚玫瑰革命的情景与萨卡什维利总统

其实这场革命在那个时候发生是预料之中。因为在一年前的2002年，发生了两件对于格鲁吉亚来说事关重大的事件。一件是世界银行和欧洲复兴开发银行 投资修建石油管道，即从阿塞拜疆的首都巴库（Baku）出发，经过格鲁吉亚的首都第比利斯（Tbilis），到土耳其的地中海港口杰伊汉（Ceyhan），提供将阿塞拜疆和土库曼的里海石油不经过俄罗斯而运往以色列和其他欧洲市场的路径。这个项目总投资是39亿美元，光建设就为格鲁吉亚人带来了非常大的经济利益。另一件是格鲁吉亚和美国签订协议，由美国派遣特种部队帮助格鲁吉亚军队训练。两年来教官训练不少，提拔有加，估计格鲁吉亚军队自己也就明白在下一轮内斗中，应该在哪一边站队。

以格鲁吉亚这样一个穷国，来自美国和欧洲的大量投资，对人民生活水平的提高当然很快。而看一下当时的欧洲的富裕和俄罗斯的相对贫困，任何加入欧盟和北约的提议，参与欧 
图3.4  精心策划将中亚里海能源与欧美连接的“巴库-第比利斯-杰伊汉”石油管道（BTC线）
   
图3.5  美军装备、训练格鲁吉亚军队
    
图3.6  2007年格鲁吉亚在第比利斯发生的街头运动

洲经济一体化的外交主张，当然听得人民心里发痒。而对官员腐败的攻击，自然容易被人民拥护。于是萨卡什维利在2003年的选举大胜，只不过他的政府也不比之前的任何一届政府干净多少，结果三年后的2007年，又见大批抗议群众走上街头，抗议政府腐败，只不过这次是要求小萨总统下台。但有美国军事撑腰的小萨先生可不是孤家寡人的老谢，调动手下的“美械师”通过镇压扑灭了反抗活动，并关闭了所有反对他的媒体，将反对派打下监狱，或逼着逃亡海外。

小萨又展开宣传攻势，指控俄罗斯情报人员在背后主导了这次针对他的“俄版颜色革命”。其实在抗议发生之前，萨先生已经和俄罗斯之间发生了间谍纠纷，并以格鲁吉亚国内“反俄罗斯”的“天然”政治正确性，给反对派安上“俄罗斯走狗”的大帽子。萨卡什维利是铁了心要跟着美国走，甚至它在伊拉克派遣的部队数量也迎头赶上，紧跟英美之后名列第三。在如今普京眼皮底下玩火，俄罗斯当然不会放过任何一个推翻这个小萨政府的机会。


二十三

萨卡什维利虽然在2008年初的提前选举中，以52%（还不知有没有舞弊票在内）的微弱多数优势当选，但很明显，由于伊拉克战争而导致的美国军事和经济衰退，以及俄罗斯在油价高企下的经济和军事复兴，格鲁吉亚境内的力量对比已经发生了此消彼长的改变。而萨卡什维利为了改变颓势，决定对国内的事实独立地区——南奥塞梯、阿扎尔、阿布哈兹等地开刀，用披上格鲁吉亚民族主义外衣的方式来巩固自己的权力。在美军的训练和军火供应下，他的第一次行动是在2004年，赶走了独立了13年的阿扎尔自治区的军阀阿巴施德泽，并于2007年底逼迫俄罗斯放弃了在阿扎尔首都——巴统 的军事基地。而这次行动的目标只是抢回南奥塞梯的控制权，把那里的两个俄罗斯军事基地和维和部队赶出格鲁吉亚。

据称小萨和普京之前曾通过电话，小萨不知天高地厚，要求俄罗斯从南奥塞梯撤军，还加上一句：美国和欧盟都支持他保持格鲁吉亚的领土完整的主张。普京则是以他一贯的恶言恶语回告萨卡什维利，他可以把美国和欧盟的声明贴在自己的屁股上，到处给人看（俄罗斯粗话，意思是俄罗斯只当美国和欧盟在放屁）。最后的结果就是我们看到的俄格战争，在格鲁吉亚军队先动手后，早已整装待命的俄罗斯军队，立即就杀进了格鲁吉亚。

对于这次冲突，不能简单的归咎于俄罗斯和美国的对抗，也不能更轻易地用西方和东方冲突来定义。这次冲突必须放在一个更大的地缘政治框架下，理解成一种多重角色在打群架的局面。对这个大局看清楚了之后，才可以明白中国在这个群架混战里，应该采取什么样的对策，如何寻找最有利于中国利益的势力平衡。

首先要探讨的是，这次冲突中的主要角色——格鲁吉亚，在挑起和俄罗斯的打斗后，有什么好处。格鲁吉亚是一个小国和穷国，人口大约有460万，GDP是103亿美元。如果你对比一下中国的香港，人口是700万，GDP2067亿美元，澳门人口50万，GDP143亿美元，新加坡人口400万，GDP1613亿美元，就知道它经济的水平。即使和中国的穷省相比，格鲁吉亚大致比最穷的贵州要富一点，和排名倒数第二和第三的云南和甘肃接近。格鲁吉亚在2001年时，有54%人口生活在贫困线之下，在玫瑰革命皈依西方后，通过世界银行、国际货币基金会和欧盟的各种经济输血援助，总算在2007年，减少到34%。格鲁吉亚的经济主要在于旅游业和葡萄酒，但是这些产品和服务80%的消费来自俄罗斯。2006年，因为俄借口酒里的重金属超标，格鲁吉亚葡萄酒被禁止出口到俄国，给这个穷山国的经济造成重大打击。

其实从历史上来看，格鲁吉亚主要是靠吃买路钱为生的。它的最大资产就是自己的地理位置——地处黑海路口，是欧洲和亚洲的路冲。早在当年丝绸之路的贸易通道上，格鲁吉亚这块地区就起了重要的中转站作用。今天，格鲁吉亚想要在世界经济里分一碗饭吃，就有赖于亚欧大陆桥 的重建。亚欧大陆桥可以使位于西部的欧洲和位于东部的中国通过陆路进行物资交换，以替代遥远的海路。欧亚大陆的两端本来就比较发达，有世界两大制造大国中国和德国，加上其他世界主要经济体日本、法国和意大利，两强结合如虎添翼，当然，处于路途中间的东欧、巴尔干、南俄罗斯、中亚等地区，由于交通不便的原因，相对比较落后。


二十四

如果能重新建立起连接中国和欧洲的新丝绸之路，将有助于将中亚的石油天然气和其他矿产原材料向东西两个制造中心输送，又可以让东西中三块互通有无，进行产品贸易，提供各类生活用品，提高这些位于桥中间的落后地区的生活水平。而这些落后国家的经济发展，又有助于东亚和西欧的制造大国开发新的市场，刺激本国生产发展。
 
图3.7  两条亚欧大陆桥的走向情况及关键经过的枢纽城市

现在的亚欧大陆桥有两条，一条基本是利用20世纪初俄国首相维特建设的西伯利亚大铁路，贯穿俄罗斯，东西连接海参崴和莫斯科，然后向西从莫斯科通到欧洲，这条线的南部可以导向中国，从北京通过蒙古的乌兰巴托在贝加尔湖接上，还有一条南部支线是由哈尔滨接海参崴。但这条路的气候环境比较恶劣，铁路也比较年久陈旧。另一条主干道则大致沿着历史上的丝绸之路原线，从中国的连云港开始，向西经陇海，兰新线的徐州、武威、哈密、吐鲁番到乌鲁木齐，再由西经北疆铁路到达中国边境的阿拉山口，进入哈萨克斯坦的德鲁日巴（即俄文版的“友谊关”，因为Druzhba即友谊之意），然后从这里分三路通往欧洲。

对于这后一条主干道的建设思路，可以主要由中国牵头，中亚的六个国家跟进，恢复历史上的丝绸之路。对中国来讲，这条线可以缓解中国海外市场运输线的脆弱，从而逐渐避开今日海上匈奴——美国对海外丝绸之路的钳制。这条铁路线的主要通道是哈萨克斯坦，因此
 
图3.8  中国-哈萨克斯坦边境阿拉山口/德鲁日巴口岸的情景

可以依赖俄罗斯以及哈萨克斯坦境内占人口40％的俄罗斯族帮助守卫。如果俄罗斯将来出现实力衰落的情况，则中国可以像盛唐时控制西域一样，把握从伊犁到里海的地域，通过强大的陆军和自己的哈萨克族人，保护这条通往欧洲的经济动脉。而在中国国内，这条交通线可以带动西部经济发展，将劳动密集型企业向中西部转移，并使新疆的各族，尤其是哈萨克族受益非浅，从而保证中国的西部安宁，并将中国在中亚的影响力恢复到安史之乱之前的唐朝时的水平。

这条路出中国阿拉山口后，北线从哈萨克北上与西伯利亚铁路接轨，经俄罗斯、白俄罗斯、波兰、德国，最终到达欧洲最大的港口荷兰的鹿特丹。此线已经在2007年11月开始运行。通过这条铁路，中国产品从连云港到莫斯科只需15天路程，到德国的汉堡只需18天。而相同的海运路线，则需要40天才能到德国和荷兰。

而这条通道的中线有三条选择， 一是通过阿克特科直直向西，过俄罗斯萨马拉，再接入西伯利亚大铁路的最西边的延伸段，进入白俄罗斯、波兰、德国直到荷兰，也可以选择南边走乌克兰、斯洛伐克、匈牙利、奥地利、瑞士、法国，直到其英吉利海峡的港口，最终可通过海运连接英国和爱尔兰。另一条是从南边经阿拉木图，顺着吉尔吉斯斯坦边界过乌兹别克斯坦的塔什干，再折回哈萨克斯坦沿西北或西向直行，接入俄罗斯境内的铁路。还有一条则是到乌兹别克的塔什干后继续西南前行，到土库曼斯坦的阿什巴哈德，然后再向西过里海到阿塞拜疆的巴库，路过格鲁吉亚的第比利斯，从格鲁吉亚的波季港过黑海入保加利亚的瓦尔纳到达欧洲东南部的巴尔干半岛，再过罗马尼亚、匈牙利，到奥地利。萨卡什维利2006年访问中国，估计和商量这条通道有关，因为俄罗斯的铁路网完全可以从里海的西岸——巴库对格鲁吉亚进行截流，让物流在到达格鲁吉亚之前转而北上，进入俄罗斯汇入中线的北支，那么格鲁吉亚的买路钱就会打水漂。

南线则是从中线第三条路中的土库曼斯坦的阿什巴哈德，分出一条90年代建设的新线，向南进入伊朗，到达东北部大城市马什哈德，再西进首都德黑兰，然后从西北的大不里士进土耳其，过博斯普鲁斯海峡，进入保加利亚，从这里可以分流到南欧、中欧和西欧。

有意思的是，这个以货运为主的铁路线基本上和俄罗斯、中亚及西亚北部的石油及天然气入欧洲的路线相同，所以很自然就要面对俄亚-欧洲的油气管道派生出来的地缘政治争斗。


二十五

在之后的几篇中，笔者将算几笔账，说说俄罗斯与欧洲之间不得不说的故事——能源。

俄欧能源问题，目前主要是石油与天然气。能源问题，归根结底，是能源从产地向使用地输送的问题，在输送过程中，大有文章可做。这个问题不可避免的要把未来能源基地——里海牵扯进来，而这个地方，西部就是高加索，东部是中亚，南部则是伊朗阿富汗，牵扯到无数分故事，东可连中国，南可达中东，西边自然就是本篇的主角——欧洲。而对于欧洲来说，石油是小头，天然气是大头。笔者先讲小头这块——石油。

石油的输送和天然气大不相同，石油可以全程管道输送，但也可以用管道输送到港口后运上船再输送，还可以在管道出现故障时，改用油罐车，通过火车运送到港口。但是天然气就不同，没有管道，就只有用液化的方式，才可以罐装运输，但这样运输成本就大幅增加。

俄罗斯通往西欧的石油管道基本是三个走向。其北线基本上是运到波罗的海边上的港口装船运出，最北的路线（也叫波罗的海管道系统 ）是从圣彼得堡附近的港口出国，而稍南一些的管道隶属于“友谊”石油管道系统，则经过白俄罗斯——这个俄罗斯事实上的领土 的北部，与部分波罗的海管道系统汇合，到立陶宛后分两支，分别去拉脱维亚的文茨皮尔斯港和立陶宛的帕兰加港。而中线是苏联时代修建的“友谊”管道主体，也分两道，北道由白俄罗斯南部插入，西入波兰然后分两支，一支是为了给当年小兄弟波兰供血用的，贯穿波兰，直到格但斯克港口，另一支则是当年民主德国的生命线，所以插入今天的德国东部，在其境内分南北两只，一只北上直到罗斯托克，一支南下莱比锡，盖住原民主德国；南道则在白俄罗斯南部靠近切尔诺贝利的地方插入西乌克兰，又散开分两只，当初的主要目的是供应原捷克斯洛伐克和匈牙利以及前南斯拉夫和南欧，所以一支经斯洛伐克到捷克的布拉格，另一支经匈牙利，再进入克罗地亚到奥米沙利港，经亚德里亚海装船去意大利。至于南线，也是分两大部分，北边的南线网络由俄罗斯中部伸出的三条油管进乌克兰，一路供应东乌克兰，然后汇聚到黑海港口敖德萨上船，另在此还分道北上接上中线“友谊”管道覆盖中乌克兰；最南边则是所谓“萨马拉-新罗西斯克”管道系统，直接从俄罗斯中部的石油州萨马拉一路南下接到俄黑海东岸港口新罗西斯克和图阿普谢出海。
 
图3.9  俄罗斯及南部里海的前苏联共和国向欧洲供应石油的管道示意地图

俄罗斯的天然气管道，笔者打算放到论述乌克兰问题的时候再加以描述。这里还是先谈一下“棋眼”格鲁吉亚境内的石油和天然气管道。

为什么说棋眼是格鲁吉亚？因为欧洲来自于东方的能源——无论是上文做了介绍的石油还是下文要介绍的天然气，来自东方的供应大头，基本在原苏联境内（尤其是天然气）。原苏联境内的这些能源地分为两类，一类是目前俄罗斯境内的，另一批是俄罗斯境外，其他苏联共和国境内的——这主要就是里海沿岸国家。苏联时期先开发的能源，主要在俄罗斯境内，而里海的能源，除了里海西岸的阿塞拜疆是老产地以外，其他的都属于正在建设的新兴之地，他们的能源走哪条路输向消费地，还没有完全决定，因此也成了各大国博弈的地方。

里海主要在前苏联地区的南部，如果延西北方向，并入俄罗斯境内既有的输送管道（无论石油、天然气），那么自然是俄罗斯求之不得的——尤其是天然气，将强化俄罗斯对欧洲各种事务讨价还价的筹码。欧洲自然不太愿意这样，它和美国都希望能够相对摆脱俄罗斯的路径控制，因此希望建设一条“极南线”，即从里海向西南延生，走土耳其这一条线路，不粘俄罗斯领土半寸。目前的几条石油、天然气的“极南线”即经过格鲁吉亚。石油方面就是“巴库-第比利斯-杰伊汉”石油管道，而且希望土库曼的油田也能有一根海底管道铺过来接上。俄罗斯自然是把它看作眼中钉，千方百计要让欧洲在这个地区的努力无功而返。

走“极南线”，经过高加索供应西方和土耳其的油气管道来源主要来自前苏联的三块地方，一是上面所说的俄罗斯本土，有少量原油从北边运下来分摊运力，一个是老牌石油开采地——里海西岸的阿塞拜疆，另一个是新兴的里海东岸地区——中亚的哈萨克和土库曼（虽然这块还没真正开发出来）。目前通过格鲁吉亚所在的南高加索咽喉的石油主要是来自本地的阿塞拜疆。从阿塞拜疆的巴库出来西运欧洲的石油路线有两条，一条是通过格鲁吉亚的第比利斯，入土耳其经埃尔祖鲁姆到土国港口杰伊汉，从地中海上船供应以色列和欧洲，这就是号称世界第二长输油管道（仅次于“友谊”管道），2005年投入使用的“巴库-第比利斯-杰伊汉”石油管道（简称BTC油管 ）；另一条则是到格鲁吉亚的黑海港口苏帕沙在那里装船。此外，巴库的石油还可北行，沿里海岸边北上俄罗斯，最后加入俄罗斯的最南线。
 
图3.10  俄罗斯借打击格鲁吉亚对欧洲敲山震虎，又一手安抚土耳其和里海产油气国的战略布置图

和去土耳其的BTC油管平行的是从阿塞拜疆巴库油气田供土耳其的天然气管道，但只修到土耳其东部的埃尔祖鲁姆就停 。很耐人寻味的是，在格鲁吉亚动手招惹俄罗斯之前4天，即08年8月2号，在土耳其境内的油管中转站被人放炸弹炸了，使这条每日可输送1百万桶的油管不得不关闭。土耳其境内的库尔德族分裂武装——库尔德工人党宣布是他们干的。但明眼人就指出，石油管道旁边的天然气管道毫发未损，这让人感到非常蹊跷，因为库尔德工人党的仇人是土耳其政府，不去破坏供应土耳其的天然气管道，反而破坏主要输给以色列和欧洲的石油管道，似乎不太合逻辑。在之后的战争中，俄罗斯并没有像格鲁吉亚大肆渲染预言的那样去炸毁格境内的石油和天然气管道，只是在黑海封锁格鲁吉亚海岸，使本来就因为战争而被英国石油公司关闭的苏帕沙无法运行。管道破裂，海港封锁，所以阿塞拜疆石油只能改为罐装，通过铁路向土耳其运输。但是铁路必须通过交通要道，即斯大林的出生地哥里，但俄罗斯军队随后就占领了该地，使所有的交通都瘫痪。无怪乎战争爆发后，美国和欧盟大声疾呼，要俄罗斯退出哥里这个战略要地。
 
图3.11  左上：BTC石油管道启动（2006）；右下：BTC石油管道施工（2007 土耳其段）；
左下：BTC石油管道被炸（2008 土耳其段）
 
图3.12  格鲁吉亚哥里城被俄军攻占，铁道枢纽被毁

当然，俄罗斯不想得罪阿塞拜疆和土耳其，所以巴库的石油还是可以增加输送量，通过去俄罗斯的油管和铁路双管齐下。对土耳其，因为战争初期BTE天然气管道关闭了两天，俄罗斯就增加了穿越黑海向土耳其供气的“蓝流” 管道的供气量，另外伊朗也雪中送炭，多输气到土耳其救急。俄罗斯国会杜马的政治顾问杜金则在接受土耳其媒体的访问时，直截了当地告诉土耳其，应当将“巴库-第比利斯-杰伊汉”石油管道当条死亡管道，因为这条管道不能再运作下去了——库尔德工人党的游击队会一路破坏下去。看来这条欧洲花费390亿美元建成的1770公里长的油管前景堪忧。


二十六

如上面所说的，西方修建这条BTC管道的目标，可不只是阿塞拜疆的里海石油和天然气，而是土库曼斯坦和哈萨克斯坦尚未真正开发的大量石油和天然气。这条通道的重要性在于给予西方唯一的绕过俄罗斯的里海能源通道。而要保证拿到里海的能源，西方就不得不保证卡在中间的格鲁吉亚的安全。
 
图3.13  欧美俄中四家对于里海石油运输的不同规划（虚线表示尚停留在纸面上）

其实这块地区能源，除了通过俄罗斯拿油外，其里海石油通往外界海洋的最短线是穿过伊朗下波斯湾，但是众所周知，美国、以色列与伊朗势不两立，西方的石油公司不太可能参加这个计划。本来另一个计划是从土库曼斯坦走东南路线过阿富汗，巴基斯坦，从印度洋出海，占据亚洲石油市场，但这个计划因为沿途搞不定塔利班武装而无法成功（而且不排除俄罗斯或伊朗的情报人员借塔利班之名捣乱）。其实即使是从阿塞拜疆西行，从土耳其东部边境插入的方向，也不一定非要过格鲁吉亚，更短而成本也更低的路线是走亚美尼亚，但这里有三个问题：一是亚美尼亚和俄罗斯关系不错，二是亚美尼亚对百年前遭到土耳其人屠杀的事刻骨铭心，对土耳其人今天仍不肯背“种族屠杀”的骂名耿耿于怀（也许美国国会通过法案，认定奥斯曼土耳其帝国迫害强行迁移亚美尼亚民族的行为是种族屠杀，就是为了拉拢亚美尼亚），三是亚美尼亚和阿塞拜疆在纳加尔诺-卡拉巴赫地区的领土争端还没有解决。这就迫使西方不得不多花点冤枉钱，从格鲁吉亚绕道，来保证这条唯一的不受俄罗斯和伊朗控制的通道。

而以色列本来想分一杯羹，利用一条旧油管 ，从杰伊汉装油，入港口阿什凯隆，既供应以色列，又可以南下红海港口埃拉特，从红海运往亚洲，还可等他们的犹太兄弟们在石油期货市场上把油价炒上天后，好好的赚一笔。不过据说对于以色列一条更省钱的方法是，通过黎巴嫩沿地中海岸，借叙利亚一小块飞地，接上土耳其的杰伊汉。如果以色列以其超强的军事实力，将亲伊朗和叙利亚的真主党打残，扶持亲西方和以色列的黎巴嫩基督教长枪党民兵，估计叙利亚不得不乖乖就范。可惜的是，在2006年那一场恶战中，武装到牙齿的以色列军队，拿土八路真主党竟毫无办法，结果造成其势力越发强大。而且俄罗斯开始在这个叙利亚飞地上开设军事基地，阻断以色列的通道，还可以在必要时封锁土耳其的杰伊汉港口，这条油路只好作罢。

俄罗斯也是乘机发力，看准了美国和北约在伊拉克和阿富汗军老无功，在伊朗和巴基斯坦无计可施，再加上布什政府即将下台，而同时西方各国和中国在奥运会前刀光剑影，无暇北望。于是借小国挑衅之机，一剑封喉，将格鲁吉亚局势打得稀烂。笔者曾对这届美国总统大选评论道，如果年轻幼嫩的奥巴马上台，碰到中国和俄罗斯两个老辣的对手，可能会没有什么好日子过。看来普京正是找准了这个机会，向美国叫板。
  
图3.14  哈萨克-中国石油管道示意图

那么中国在这个棋局中，应当如何应对，来获取自己最大的利益呢？其实中国和哈萨克斯坦之间从里海向东运油的管道正在建设。这条油管分三期建设。第一期的最西端已经开通，但目前主要是将哈萨克中西部的石油沿此管道从东向西运输，运输能力是每天将12万桶汇入俄罗斯的网络。而2005年竣工并开始输油的第二期部分，就是连接中国的哈境内的东段，这部分全长962公里的二期油管，从哈萨克斯坦中东部的阿塔苏出发，抵达中国和哈萨克边界的阿拉山口，目前建成管道的输油能力大致一日20万桶，原定在2011年增加到每日40万桶。但是在中国在2008年完成新疆独山子的炼油厂等配套设施后，不是没有提早提高供油量的要求。目前正在继续修建的是连接这东西两部分的“肯基亚克-昆库尔段”第三期工程。预期在2009年下半年竣工，并在2011年达到全部设计的输油能力。


二十七

其实从陆地上运输石油，经济成本要比海运高得多。这也是为什么中国石油进口，大致接近40-50%来源于中东（主要是沙特阿拉伯和伊朗），30%来源于非洲（主要是安哥拉、尼日利亚和苏丹）这些远隔大洋的地方。但是因为目前这些地方通往中国的海路受制于人，再加上路途遥远，和平时期还不是问题，一旦局部地区动荡，对中国的能源打击就比较大。

从哈萨克斯坦入油的主要好处是安全，因为中间不经过任何第三国，而且花钱在哈萨克斯坦对中国反疆独恐怖组织有很大助益。但不好的地方就是管道线路长，光是从边界的阿拉山口到新疆独子山炼油厂就要264公里，等到2011年哈境内全线完工，接上阿克托别油田，到里海边的阿蒂拉乌，总长是3千公里，成本也并不低。而且哈萨克斯坦的冬天寒冷，会造成油管里的油容易凝固，使输油困难，对油管的维修和保养费用也都相对增加。

　　中国和哈萨克斯坦石油合作面临的另一个困难是，里海海底石油的勘探和开采在技术上要求较高，中国技术较为不足。哈萨克斯坦的里海北部油田基本上是高压油田，含有大量的毒气硫化氢，而且冬天还结冰。当然如果中国能够购买一些比较有经验和技术的欧洲公司，尤其是来自北欧的对中国不敌视的石油开采公司，可能会在这方面有所帮助和进展。另外一个拦路虎就是开采权问题，里海的很多油田，在90年代独联体国家一片混乱的时候，被美国欧洲人捷足先登，为雪佛龙和其他欧洲公司控制。这些实权力量比较倾向于支持美国提倡的南向和西向的输油管道。

　　当然在俄罗斯和格鲁吉亚交火之后，里海西岸去土耳其的杰伊汉的BTC管道（大约日供应量85万桶）和黑海东岸苏帕沙的管道（大约15万桶）都无法运作，而北向去俄罗斯的管道基本上只是每天10万桶容量，这样的管道网堵塞会对中亚的石油出口尤其是阿塞拜疆带来影响，使得它考虑其他路线。但在短期和中期，这些事情都还不会对中国有多少帮助。俄罗斯在格鲁吉亚促成的动荡，主要是强迫欧洲国家，尤其是西欧乖乖就范，支持俄罗斯的里海石油输送计划。

看看俄罗斯在里海东西两岸的部署。西岸阿塞拜疆已经在通过格鲁吉亚进行运作。而对东岸的哈萨克斯坦，现在从哈萨克斯坦里海出产地到俄罗斯黑海港口新罗西斯克的管道可以每日运输大约70万桶，而且可以再增加10个新油泵站达到130万桶。这条线还可以加进俄罗斯几大石油公司的油田的油，是现在最为理想的里海外送油路。其实美国的石油公司，如雪佛龙等，也在这条路里有大约22%的股份，对他们也是大有利润可图，但问题是，西方与俄罗斯的几大合伙人内斗不停，在转运费和执照费，还有税收问题上，西方石油公司经常和俄罗斯公司大打出手。另外一个大问题就是如果走这条俄罗斯出海的线，油轮规模还是要受狭窄的博斯普鲁斯海峡制约的，运输能力多少受到限制。
 
图3.15  俄罗斯主张的里海北岸石油线，将哈萨克乃至土库曼的能源出口纳入本国网络

　　还有一个不能忽视的问题，就是中亚国家虽然对俄罗斯依赖很大，但又不愿完全被它控制。俄罗斯人有一句谚语，扒下一个俄国佬的外皮，你会发现这里面其实是一个鞑靼。 俄罗斯不善于用萝卜，太喜欢用大棒，总是搞不定身边的小老弟们，这与其直接率真、简单粗暴的民族习性有关。而这次拿大棒狂揍格鲁吉亚这个泼皮小弟，恐怕引起恐慌的不只是乌克兰、波兰和捷克，大概白俄罗斯和中亚的“斯坦”家族众兄弟，都会有些芒刺在背。如果俄罗斯老是陶醉于自己的政治复兴，重新幻想自己当年的世界超强地位而没有其他根本性的生产力进步，那么只不过换了个能源武器代替过去的飞机大炮而已。而这些小国们就不得不想办法，抱外人的大腿，以作为对俄罗斯的牵制。


二十八

最令笔者捧腹的是，这次的兄弟阋墙中，有来自车臣的维持和平部队和哥萨克的志愿兵参加搅局。其实无论是成天打杀的车臣死士，还是收钱为人消灾的哥萨克雇佣兵，都是为了帮自己的弱小亲戚奥塞梯人才跳进去，而不是对俄罗斯人有好感来为帝国卖命。即使是俄罗斯军队从格鲁吉亚的杀戮中救出来的阿布哈兹人和南奥塞梯人，都并不都喜欢俄国佬，只不过没有选择，两害之间取其轻。而一旦局势变化，民族利益需要他们和俄罗斯人开杀，他们也会毫不犹豫倒戈，如同当年在车臣发生的战争一样。而当初美国希望将势力推入格鲁吉亚，拉其和乌克兰一起入北约，就是希望能够造成北高加索，如车臣和达吉斯坦的独立，把俄罗斯的南部边界推出北高加索，将里海和黑海打通。
 
图3.16  北高加索民族林立，西方意图将其分离出俄罗斯，从而方便自己的运作

当然任何俄罗斯和北约在西部的你争我夺，你一记双龙戏珠，我一招黑虎掏心，对东边稳定求发展的中国都是一件好事。相对于西方在格鲁吉亚部署的BTC管道被俄罗斯折腾，俄罗斯的管道被乌克兰乱搞，东边送向中国的管道一路畅通，而且还是从安稳的北疆入口。这不光有利于中亚的石油东送，还对中国从土库曼斯坦输送天然气的计划极其有利。

以现在的经济情况来看，中国的石油消耗量大致是一天650万桶，自己生产大概是350-400万桶，需要进口来补偿250-300万桶的缺口。如果中国可以对自己的石油消费结构，进行一个全面的检讨，并推出相关的引导政策，应该可以争取在石油进口这个头痛的问题上有所缓解。

比如说中国的交通用油，在汽车燃油能耗节约水平上比欧洲平均水平要低15-20%。如果赶上这个标准，就会为中国一天节省40万桶油。在中国未来的交通发展方向上，应该是以公共交通为首要考虑思路，发展以电力为主的高速列车网、城市地铁网、用清洁再生能源的公共汽车网和长途汽车网。在发展私人汽车市场上，提高汽油价格，并增收燃油税，尤其是对耗能高的油老虎SUV等车型，增收每年计的环境保护税。

而在发电方面，不光是彻底禁止燃油发电厂，而且要发展依靠风能、太阳能等再生能源，替代因为电力不足的小型柴油发电机。如果把这部分用油省下来，一天恐怕就可以节约35-40万桶原油。

在化工方面，从节省能源的角度也可以发现很多可以节省的地方。光是过去超级市场用的塑胶袋，就需要一天10万桶油，简直就是哈萨克斯坦油管现在一半的输油量。另外在建材工业上，发展替代材料，也可以减少石油消耗量。

　　其实中国的能源需求和美国有所不同，主要在于中国的能耗大部分用在发电，主要是煤电，进口的石油，用于生产的居多，汽车等交通用油比例相对较小。美国的能源消耗中石油是大头，但作为世界第一大石油消耗国，这头号能源中用于发电的只占4%，反而交通运输占了70%。即是在一天2070万桶中，发电用84万桶，但交通用1470万桶。如果中国可以在以上几个方向努力，减少石油进口量3-4成的目标还是可以达到的。
 
 
 
图3.17  美国在全世界的石油进口图表与分布示意图
（下表包含了上表的原油。下表比上表的数字高出越多，说明该国越有本国的石油加工能力）

二十九

中国在石油的使用上，不仅需要完善生产、加工这些供给体系，而且要在需求调整上下功夫，这就必须要建立一个更合理有效的国内市场，调整价格机制，在节能上下多一点功夫。中国的能源政策，一定要避免重蹈美国的覆辙！美国自身的石油生产量已经超过每日900万桶，邻近的加拿大可以向它供应180万桶，墨西哥向它出口供应160万桶，委内瑞拉还可以供应140万桶，这四个美洲大国给美国的供应量合计高达1380万桶，却连美国国内各类汽车烧油都不够。

中国的能源政策还是应该以提高电力生产为主，尤其需要在传统火电以外的电力开发上下大功夫。除了在风力发电和核能发电上增加比重，还要投资在清洁煤上，另外在天然气上可以考虑增加比重。至于电力部门曾经着重的水电，在汶川大地震后，进行大水电开发，尤其是在四川和云南进行梯级大水电站的开发的计划，应该慎重考虑，而且中国的“西电东送”计划，从贵州的乌江、南盘江、北盘江到云南的澜沧江、红水河各路电站向华南地区的送电，以及金沙江各电站和三峡、葛洲坝等水电站向华东地区的送电，都基本上已经完成，而且再进一步开发的潜力已经降低。相反，在边远山区进行小水电站建设，以满足当地人民生活的需要为目的，既减少建设输电线路的成本，又非常经济而且对生态环境没有太大损害，所以可以多加考虑；唯独企图建立更多的大型水电站来满足向大城市和东部供电，似乎今天已经不是一个明智和经济的选择。

中国需要做的是加大向煤矿工业的投资，使中国的煤矿工业从劳动密集型转化成资金密集型。一方面提高产出，另一方面不至于因为设备落后导致屡屡发生的重大安全事故。现在已经实现的对燃煤价格的市场化放开，使煤炭工业增加了利润。但必须对利润率进行严格管理，保障按一定的比率提取，成立一个安全基金，甚至可以灵活掌握调整，价高的时候多提，价低的时候少提，用于生产设备更新和安全条件提高，而不是令煤矿老板一夜暴富及管理阶层单独得益。另外一个做法是，在煤价中抽安全赔偿费和保险费，为出矿难的煤矿工人提供高额补偿基金。大家要明白，在以利润挂帅的企业中，想靠政府命令意志去强调安全政策，实效不会太大。只有用货币信号诱导，让一个企业在发生矿难下赔偿受难工人的成本大大高于投资安全设备的费用，企业才会不需要政府天天去行政督促，而是自动就将生产安全放在首位。

中国的另一个出路就是利用天然气发电。以中国的经济发展，如果大家想生活水平翻两番，那么对能源的消费，即使加进节能技术之后，估计恐怕也要比现在的消费量增加3倍。而中国天然气利用在国内总能源消耗的比重，基本上可以忽略不计，相比于西方国家天然气使用占到能源总用量20%-30%，非常之低。由于中华民族是一个喜欢炒菜做饭的民族，因此发展天然气作为民用、交通、化工、肥料等等种种用途，非常重要。

其实中国在天然气上的优势非常明显，一个原因是中国本身是天然气大国。光是陆地上发现的天然气已经过26万亿立方米，还不包括东海盆地和海南岛南部的莺歌海-琼东南盆地。第二个原因是因为世界上最大的能源消耗国美国也是天然气大国，据美国能源部的统计发现的天然气资源为5.9万亿立方米（但据不同私人机构的估算，美国的天然气储量有可能达到60万亿立方米）。美国的天然气2007年消费量是6525亿立方米，而生产量是5473亿立方米，缺口只有52亿立方米，很容易解决，所以和中国的竞争没有这么激烈。

 
图3.18  世界天然气的主要蕴藏国生产国和消费国示意图

三十

第三也是非常重要的原因是，所有世界天然气大国土库曼斯坦、俄罗斯、伊朗等等，都是距离中国比较近，而且可以通过陆路到达。

据现有资料表明，土库曼斯坦（当然，任何关于天然气的储蓄量的资料都是预测）是天然气世界第一大国，大约有100万亿立方米。俄罗斯为第二，大约48万亿，伊朗第三，大约27亿立方米，和中国接近。而在天然气用量上，这些天然气的主要的消费市场是欧洲，而不是美国，由于欧洲本身军事实力弱不喜对抗，又靠近俄罗斯这个大天然气出口国，只要可以解决和俄罗斯的关系，应该在天然气来源上不存在太大问题。
 
图3.19  中国与中亚、俄罗斯相结合的西气东送大战略示意图

土库曼斯坦的天然气也是一个世界地缘政治的大棋局，而在这个棋局中，中国占据领先地位。在中国的西气东送大战略中，第一阶段的战略是建设了由塔里木盆地的轮南油气田和鄂尔多斯的长庆油气田的供应基地（两地加起来差不多接近20万亿立方米），从新疆的库尔勒、吐鲁番、哈密，入甘肃的河西走廊，过张掖、武威、兰州和宁夏的中卫，然后到榆林的靖边，再到河南的洛阳，穿过安徽的合肥、江苏的南京，最后过常州、无锡和苏州，到达上海，全长大约4000公里。这个天然气管道可以每年输送170亿立方米给沿途各地，现在已经基本饱和，需要提高输气能力。而新建的陕京二线天然气管道，则是由靖边出发，沿鄂尔多斯市的毛乌素沙漠东南边缘，过内蒙古，经黄土高原入山西，过吕梁山和太行山，进入河北，最后到北京的大兴区。这条线路共长935公里，其供应输气量是每年120亿立方米。

第二阶段的战略就是在土库曼斯坦。土库曼斯坦向东走的输气管分三段，分别在土库曼斯坦、乌兹别克斯坦和哈萨克斯坦。土库曼斯坦段长188公里，于2007年8月开工，乌兹别克斯坦段长525公里，也于2008年6月开工，哈萨克斯坦段长1293公里，则于2008年7月开工。这条线起点是土国境内阿姆河边巴格德雷区的边境城市格达伊姆，经乌兹别克斯坦和哈萨克斯坦，在进入霍尔果斯后，过乌鲁木齐，然后接上西线东送第一期的管道，过甘肃到宁夏的中卫。折向南，到陕西的西安，再通过一条支线在这里和北边的靖边相连接，从西安继续向东经河南，转向南，从湖北到江西南昌，最后到广东的广州，其数条支线则分头去安徽、浙江、上海、湖南和广西，全长超过7000公里。大概会在2010-11年全部完工，年输气量为300亿立方米，并可以增加到400亿立方米。

这条线对中国未来的能源安全非常重要，有需要的话，连中国在伊朗北帕尔斯的天然气生产基地（44亿立方米一年）也可以接上这条管道，不再需用船以液化气的方式过波斯湾，印度洋和马六甲海峡绕一大圈运回中国。而且中国和俄罗斯签订的在2011年由俄罗斯双线向中国一年供气680亿立方米的计划，也可以考虑从西线经阿尔泰接乌鲁木齐，东线则由库页岛，经伯力（哈巴罗夫斯克）进中国，通过哈尔滨，过沈阳和北京接在一起，建立一个从中亚、北亚和中国合一的天然气大网络。


































【写作日期】2008年8月18日——23日            





	


 









第四篇


月白秋夜凉，挽弓当择强。
空弦鸣鏑去，敌酋已惊亡。


三十一

除了从土库曼引入的里海天然气以外，中国国内的另一条天然气线路，则是将四川的天然气向东延伸加入长江三角洲的输气管。估计在所有的线路在2011年运行后，中国应该可以开始对用煤为主的发电厂进行清洁煤改造，使中国的能源消费向环保清洁发展，并摆脱对石油在经济发展上的依赖。

土库曼斯坦的天然气，和哈萨克斯坦以及土本国的石油面临的问题，或者说争夺，那就是应该从哪条路引出来。其实最早谈得最多的线路计划，是从土库曼斯坦南下，进阿富汗的赫拉特，然后穿过阿富汗到南部重镇坎大哈，从这里进巴基斯坦的奎达，或者通一条线路到印度，或者到巴基斯坦南岸，通过液化气从印度洋出海到达印度。（平行于笔者前文所谈的美国里海（西岸）石油路线计划中经过伊朗的那条。但是因为里海天然气产地土库曼在里海之东，伊朗至东北，里海石油现有的主要产地阿塞拜疆在里海之西，伊朗之西北，都要向东南引的话，前者可走阿富汗，不必经过伊朗，后者则绕不开伊朗，所以前者比后者还可行一些。）

但是我们都知道谁在控制坎大哈这个地方——那就是塔利班。而且也不排除伊朗的特工人员会进入这条线路的沿路各个地方进行破坏，既可以干扰线路又可以让在这里蹲点的塔利班承担责任。所以说这个计划已经吵吵嚷嚷了10年了，其间美军发动阿富汗战争，杀进阿富汗，而且不断在赫拉特和坎大哈用兵、扫荡、剿匪，但是仍然无法达到战略意图。从能源争夺的角度来讲，塔利班武装在这个地区的保持、发展、壮大，对伊朗、俄罗斯和中国都是一个乐于见到的局面。
 
图4.1  各国筹划的里海天然气布局引导计划

而地区大国伊朗也不会闲着，它的意图是将土库曼斯坦的天然气向南边引下来，但不要经过阿富汗，而是纯粹穿过本国领土，再连上其自己的天然气开采，从波斯湾出海。也可以建一条管道进巴基斯坦，然后分两条，一条经东北进中国的喀什，一条经东入印度。不过这条线路也不可能建设，因为美国会说不。美国通过在外交上的压力，自然可以让印度退却，然后通过在巴基斯坦搞乱局面让中国参与这套伊朗计划发生麻烦。当然美国打击伊朗方案的意图是两方面的，一是自己控制土库曼出来的天然气通道，二是打击伊朗的经济。但是如果中国不按照伊朗的南线方案去建设，而是选择经过乌兹别克斯坦和哈萨克斯坦的东北路，就会使美国的这些意图落空。

但是如果按照中国天然气战略的第二步规划那样选东北路运输土库曼天然气，在一定程度上，巴基斯坦的经济发展就会受到影响。因为巴基斯坦在这轮建设中在经济上的受惠就相对减少了，而巴基斯坦的经济繁荣，则和中国新疆的社会稳定息息相关。

为了稳定新疆，特别是在巴基斯坦的经济发展可能受制于地区油气地缘政治操作的情况下，中国在新疆的战略应该是，加大力量投资南疆，发展喀什、和田、阿克苏和克孜勒苏四个地区，建立起与巴基斯坦的高速公路、高速铁路、石油管道和天然气管道。即主动带动新疆的发展，再让经济带打通巴基斯坦、伊朗、土库曼、乌兹别克和哈萨克这个中亚国家环。这样，一方面使南疆成为一个劳动力密集的制造业中心和转运出口中心，令千万余维吾尔族和其他少数民族的农牧民可以快速脱贫，将南疆的棉花、水果等传统农业，转化成有机和绿色的现代化农业。另一方面则可以将从伊朗等地引入的天然气，分头输送到这些地区，免费供应当地人民作为燃料，扭转当地人砍树为薪的习惯，以保护南疆的胡杨树资源。甚至还可以将这条线分支通过库车东南入轮台，西南上西藏。

当然，在打通中亚国家环，实现里海、伊朗天然气供应新疆百姓之前，也可以就地取材，直接保护胡杨木与生态环境，因为塔里木的轮台县自己有天然气。即现在可以建设中国自己在南疆的管道，先输送轮台的天然气供应外围，以后一旦西边境外管道有气进来，改变一个方向就行了。
 
图4.2  让南疆社会安定和经济发展一举两得的建议示意图

南疆的喀什、和田、阿克苏和克孜勒苏这四个地区是疆独势力和中国政府争夺的主要地区。如果不解决这个地区的经济发展问题，或不带动巴基斯坦北部地区的经济发展，要想得到真正的稳定，不会是一件易事。当然，现在因为美国从阿富汗的不断干扰，使这个计划具有一定的难度，但是中国必须考虑到美国最终会在阿富汗被拖垮，并不得不最后放弃这块地方，而且伊朗的核争议，数年后也会有一个结果，所以要及早计议，为中亚国家环的打造，做好准备。


三十二

在巴基斯坦现在的政治博弈一片乱局的时候，中国还是不要为局势所迷惑，而应该继续加强与巴基斯坦政府各专职部门、军队和情报部门、企业界、宗教领袖等等的全方位交往，想办法逐渐使巴基斯坦的极端宗教势力失去市场，将巴基斯坦并入中国的统一市场框架里来。过去中国在这个地方，大多数的考虑是将经巴基斯坦与中东联系上的能源通路安全，而未将中国在非洲原材料（能源、矿产品以及将来的农产品）基地和制成品市场和巴基斯坦联系起来，进行统一计划。以中国现在对非洲的经营，在苏丹的小小动作已经遭到美国和欧盟的全力封杀。其实中国在非洲的进油量顶多就是一天一百万桶，根本没有损害西方的利益。因为中国是世界上唯一一个全国普遍进行大规模土木建筑的大国（中东迪拜等大兴土木之地和中国比毕竟只是星星点点），而其他发达国家对非能源原材料的实际消耗还不是很大，所以中国目前在非洲的原材料，特别是非能源原材料和矿产经营，还没有遭到多少阻击。但估计在不久的将来就不会这么幸运了。

例如，美国就将是一个未来会给中国的非洲战略可能带来大异数的国家。08年的这场金融经济危机，由于美国国内金融、政治操作瘫痪，各个利益集团在大选来临之际争夺激烈，使得对美国影响重大的基础建设更新问题还暂时未被提上日程，对中国的原材料安全短期内还不造成威胁。但五年之内，美国的老朽级基础设施出现普遍性的瘫痪需要大修的时候（高速公路和电网自60、70年代甚至更早的罗斯福时代以来就没有修过），势必将和中国在非洲展开争夺战。所以，如何保证中国在非洲的投资和国家利益是一个需要未雨绸缪的大问题，不然在五年后直面西方挑战时，就会有大麻烦 。

以中国在非洲的经营方式和在基本建设上的耕耘，把主要原材料基地和输送线路途经国连在一起，不是一件难事。中国必须有巴基斯坦这个兄弟，以其在伊斯兰教国家里比较高（因为核武器的原因）的地位，出面帮手处理非洲事务，以瓜达尔港和卡拉奇港为基地，或者通过近海路线到红海的苏丹港，或者从阿曼直接上岸过也门或沙特阿拉伯跨海到达苏丹港，或者到也门后经过可能会修建的亚非跨海大桥 到吉布提接上埃塞俄比亚的铁路线直通苏丹。而人力资源充沛的中国和巴基斯坦，在保卫自己在非洲的利益而在中东非洲大兴建设这一点上，比美国和欧盟要有优势的多。所以在中巴铁路的建设上，不能只看到建设成本 ，还要考虑到未来中国经济的全球布局，要看到南部尽头瓜达尔港以外的世界——这条中巴铁路在中国的未来经济圈中将起到的枢纽意义。

 
图4.3  巴基斯坦、中巴铁路对于未来中国与中亚、非洲的经济圈的意义

谈完了土库曼斯坦天然气这盘棋的东路和南路，历数完中国-巴基斯坦计划和伊朗与美国的斗法，我们可别忘了土库曼斯坦的第三条路——过里海向西去欧洲的路线。这条路现在是全世界最有看头的游戏。在欧洲市场上，天然气最大的消费国家是德国、英国和意大利。以2007年的数据为例，德国年用天然气962亿立方米，自产179亿，缺口是782亿，英国年用量是956亿，但自己生产力强，可以生产757亿，只有缺口199亿，意大利年用量是849亿，自己只产7亿，需要进口842亿。再下来是法国年用量为435亿，自产11亿，需要进口424亿，西班牙年用量为366亿，自产9亿，需要进口357亿。除了这些大国之外，其余欧洲小国都是一年用几十亿，加在一起都不是太多，可以忽略。

除了英国有点自给自足以外，欧洲内部只有两个国家是天然气供应国，可向本国以外输送。一个是挪威，年产量909亿，自己只用53亿，可以出口856亿，另一个是荷兰，年产量766亿，自己用466亿，可以出口300亿。尚不足于弥补其他国家的需求缺口。这些余留的缺口理所当然成为俄罗斯试图抓住的商机，而其最主要的市场是德国和意大利。如何建立起一种经济上的互利关系，并在这个基础上重新界定俄罗斯和欧洲其他国家的政治和地缘关系，欧俄到底将演变成逐渐融合的伙伴还是变成势不两立的仇敌，将是21世纪里除了美国衰落，中国复兴之外的第三个国际性大焦点。


三十三

如果要真正了解俄罗斯和欧洲的关系，就必须从历史追溯到现在。现在发生的俄罗斯和西方（其实分欧洲和美国）之间的冲突，不能像许多所谓的评论家一样，简单理解成过去冷战框架下北约代表的西方和苏联集团对抗的复活。

首先要搞清楚，欧洲是一个什么样的概念。其实欧洲是一个环中环、圈中圈，有骨干、核心、伙计乃至外来安插的特洛伊木马好几个层次。第一个核心硬壳就是“小欧盟”，这算货真价实的欧洲，由5个国家组成，即以法国和德国两大哥作为核心，加上三个小兄弟荷兰、比利时和卢森堡。这个“小欧盟”，再加上近代以来相对落后处于边缘地位的意大利，在1952年成立以能源煤炭和重工业钢铁为一体化目标的欧洲煤钢共同体，接着又在1958年成立欧洲经济共同体和欧洲原子能共同体，然后于1967年将这三个原本的专业经济、科技组织合并成立欧洲共同体（“欧共体”），即为欧盟的前身。在这六个国家中，意大利是一个异数，经
 
图4.4  “核心欧盟”五国与意大利——组成欧盟原型的最初六个国家

常有不同声音吵吵闹闹。再在外面一层，就是于1973年加入的英国、丹麦和爱尔兰，和1981年加入的希腊，1986年加入的葡萄牙和西班牙，这就是欧共体12国。大家知道，英国由于在欧盟里无法代替德国和法国的地位起主导作用，又是一个美国的跟屁虫，所以在欧盟里好比半个特洛伊木马，一条胳膊向里拐，一条胳膊向外拐，利用其和美国的表兄弟关系，在两边平衡，获取自己的最大利益。以至于经济金融界里一般所说的“欧洲”，都不把英国放进去。
 
图4.5  到1995年为止欧盟的组成——欧盟15国中的核心国、外围国和美国“木马”——英国

欧洲共同体在苏联崩溃后，于1992年正式成立欧盟，开始向东发展。1995年吸收了奥地利、瑞典、芬兰达到15国，这15国覆盖了通常的“西欧”概念，所以今天在扩大到27国的大欧盟里，还有“欧盟15国”的说法，以核心自居，聚集起来自己开会。近10年后，在2004年吸收了塞浦路斯、匈牙利、捷克、爱沙尼亚、拉脱维亚、立陶宛、马耳他、波兰、斯洛伐克和斯洛文尼亚入盟，在2007年吸收了罗马尼亚和保加利亚入盟，把范围覆盖到了原来的边缘国家和前苏联的势力范围内，这就是今天的27国“大欧盟”现状。下一步计划则是考虑克罗地亚和其他的巴尔干半岛国家，前苏联境内的乌克兰和格鲁吉亚，当然，可能还有那个晾了几十年就是不让入会的土耳其。
 
图4.6  2008年欧洲的构成图（省略西欧内部的核心、外围、假“欧盟国”的区分）

欧洲人明白一个道理，欧盟5亿的人口（其中有1亿多一点是在名不副实的东欧穷国），和12万亿GDP的经济（且不管其中有多少水分），如果不能团结在一起，分头出击，去和美国和中国两大世界强权竞争，那么只会个个沦为附庸。所以，只能合在一起一个拳头说话。但是问题在于欧盟目前的决策机制导致其本身是一盘散沙，在所有重要问题上都拖拖拉拉，文山会海，没完没了，极难达成一致，这使他们进行更紧密的合作的可能性令人怀疑。正如笔者在《大国游戏》第一卷里所言，在二次世界大战结束后，欧洲面临的是美国和苏联两强的对抗，而且在苏伊士运河危机后，昔日的强权英国选择了臣服美国，而法国人则选择了和德国合作，建立一个团结的欧洲自己人的欧洲。这也是为什么1966年法国总统戴高乐宣布退出北约军事一体化，提出建设“欧洲军事合作”的原因，因为他觉得北约就是美国军事控制欧洲的工具，欧洲生活在北约军事伞的保护下只能失去了自己的独立性。

美国很明白，上个世纪的两场世界大战，都是因为欧洲列强无法应对自己中间的新霸德国的崛起引发冲突造成。因此它的二战后世界新次序的规划，其主要任务就是重建德国（同时在东亚重建日本），使德国在经济、科研和制造业恢复了世界大国的地位，为其所用，但是在政治、外交和军事上，要保证德国受到美国压制，无法出头，不让自己重蹈当年老帝国主义的覆辙。美国对德国的军事占领，以及半个世纪来对德国在二战行为上的口诛笔伐建立的“政治正确”，让昔日令世人闻风丧胆的德国铁军，变成了一支连加拿大军队都不如的花架子摆设。

而德国的老邻居和过去的老对手法国，虽说军事上也是一团软蛋，经济上，自一代英杰戴高乐 以后也相对乏善可陈，但却正好具有德国所没有的政治、外交地位——联合国安理会常任理事国。


三十四

但是如果把法国和德国合在一起，互相结合，其势力就不可小觑。以德国的8000万人口，加上法国的6000万人口，就是1亿4000万，和俄罗斯大致相同，比日本（1亿2000万）要多。如果再加上荷兰（1600万），比利时（1000万），和卢森堡（50万），差不多是1亿7000万。而德国的2007年GDP是3.32万亿，加上法国的2.56万亿，达到5.88万亿，在加上荷兰的0.77万亿，比利时的0.45万亿，和卢森堡的0.05万亿，总额是7.15万亿，可以和5年后的中国相比。虽然军事是一个最大的劣势，但因为其邻居的英国和俄罗斯都经历了力量衰落，而其余临近的欧洲国家中连过去仅有的地区准军事强国南斯拉夫都被肢解，因此无人可以威胁到其安全。只要他们不主动去向中国和美国挑衅。因此，在世界其他地方，如广大亚非拉地区，尤其是法国人觉得还属于自己后院的黑非洲，这个核心欧盟（主要是法国）甚至还觉得可以敲敲锣，动动武，吓唬吓唬外人。

这就是为什么在1994年，面对苏联解体后的新形势，德国和法国政府里的明眼人，对欧盟的扩大和北约的东扩不是很感冒，反而提出一个反向而行的方案。这个方案就是以除去意大利后的原欧共体内核五国（法德荷比卢）为核心，建立一个紧密的团体。在这个紧密的国家团体内部，不光取消边界，令物资和人口自由流动，而且还要统一货币、外交和国防政策。而其他的欧盟成员则围绕这个核心国家团体组成第二层“国家环”，保持现有的合作体系。至于从苏联集团崩溃以后分出来的东欧新国家，则让他们组成第三层。形成具有核心的“三级欧洲国家圈”。

不要以为后来欧盟端出来的“欧元大餐”和这个“核心国单干”的方案有什么沾边形似的地方（比如两者都涉及统一货币）！这个核心国方案的要害就在于形成领导欧洲的“核心力量”，而这一设想与现在“欧盟”内部大小国力量均摊（甚至让小国有不相称的过多权力）的乱糟糟的局面几乎完全对立。后来实际搞出来的那个“统一货币”的欧元大餐，用政出多头的政治大勺去搅拌，从现在看，实在是煮成了一锅糊粥。而“核心国单干”方案倘若成功，倒当是真正克服欧洲国界支离破碎的缺陷，打造出一个凝为一体，货币、外交、军事样样强的新超级大国的终南捷径。

但对核心以外的其他国家而言，这种“核心国单干”的政治道路却并不是最优的安排。比如对英国来说，它就不希望核心成型——因为它这个已经衰弱的“日不落老翁”绝不可能是核心，甚至连参与核心也没份。所以英国乐见于欧盟新扩入尽可能多地的东欧国家，这样就可以稀释德国和法国的影响力，使欧盟成为一盘散沙，避免自己被边缘化，而且也非常符合它历史上从18世纪以来的对欧洲大陆“分而治之”的原则。而许多欧洲小国家之所以想参加欧盟，是希望享受到经济一体化的好处，倒并不希望有一个中心的原则要去遵守，要去付出牺牲。目前这个欧盟和美国与中国都不同，例如一旦经济上出现困难，中国和美国都可以通过不同的国家诉求，打出各种名义要求人民为这些诉求而在经济上做出牺牲（比如说中国为反击台湾独立而战），而欧盟一旦出现问题，除了核心5国以外，那些烂漫的意大利人西班牙人、心怀二意的不列颠人和只想伴美国老大的东欧人，基本上将是树倒猢狲散，缺乏凝聚力。

而且对英国和那些小国家而言，欧盟也只能提供经济的好处。在国家安全上面，欧盟是一个空架子，只有美国主导的北约才可以为他们提供真正的安全。北约和欧盟是一个完全不同的概念，但两者越大都对于真正的“欧洲”不利。

为什么？

北约越扩大，标志着从军事管道施加的美国的影响力越大。
欧盟越扩大，标志着经济政治上作为核心的德国和法国的影响力越稀释。

北约是1949年组建的，由美国、加拿大、英国、法国、比利时、丹麦、意大利、荷兰、卢森堡、挪威、葡萄牙和冰岛12国组成。在1952年，希腊和土耳其加入。1954年苏联提出入会申请，声称这样才可以真正的保护欧洲的和平，当然这个提议被北约拒绝——北约就是用来对付苏联集团的。结果在撕破脸皮的局势下，北约考虑到没有西德的加入，盟军根本不够人手来应付苏联可能的入侵，所以在1955年接受了西德入会，这反过来导致了当年由苏联、匈牙利、捷克斯洛伐克、波兰、保加利亚、罗马尼亚、阿尔巴尼亚和东德8国建立了华沙条约组织。
 
 
图4.7  上：欧盟东扩，权力因体制规定而分散；
下：北约东扩，法德核心的声音被稀释，强化美国绝对领导地位


三十五

北约很快就受到了内部的一个挑战，那就是1958年上台后的法国总统戴高乐，对北约内部由美国一家独断的局面和英美间特殊关系表示不满。估计当时法国的要求是提高法国的地位，使北约出现三驾马车，即由美国、英国和法国共同领导。当然，其实当时法国这个要求也是夹带私货，希望以自己的影响力的提升带动北约重点转移，覆盖到法国的战略要地，如当时反法游击战闹得正欢的北非殖民地阿尔及利亚，利用北约的力量来维护法国的利益。

这个要求自然被当时的美国总统艾森豪威尔拒绝。其实当时即使美国介入阿尔及利亚的战争，最后的结果不一定会让法国如愿所偿。因为美国在法国于奠边府与越共交战全军覆没之后，插手法属殖民地印度支那，开打越南战争，最后还是以惨败收场。因为不愿意看到美国在欧洲事务上独霸，又要挟不成，法国最后在1966年摊牌，退出了北约军事系统，并把美国军队赶出了法国。美军不得不将北约总指挥部从巴黎迁到比利时首都布鲁塞尔，并从法国的十个军事基地撤出了200余架战机。据说当时撤军的美国将军质问法国人，是不是要将战死在诺曼底的所有葬在法国的美军坟墓都搬出去。

直到现在，法国新上任的总统萨科齐才试图全面返回北约的军事系统，在里面扮演更重要的角色，以图在这个军事组织里制衡因为过多的亲美东欧小国加入而加剧失衡的美国影响力。这事实上在北约里就造成以法国和德国为主导的旧欧洲和以波兰和捷克为主导的新欧洲之间裂痕越来越深。

北约在1982年接纳了西班牙入会，1990年纳入了原东德，在1999年，则接纳了3个原东欧国家波兰、捷克和匈牙利，然后在2002年扩张到波罗的海三国爱沙尼亚、立陶宛和拉脱维亚，以及东南一线的斯洛伐克、罗马尼亚、保加利亚和原南斯拉夫境内的斯洛文尼亚，最后在2008年的布加勒斯特会议上，决定接收克罗地亚和阿尔巴尼亚。但在该会议上，美国和老欧洲在乌克兰和格鲁吉亚入会问题上，一个倡导，一个反对，最后没有达成妥协。

要想清楚的了解欧盟和北约的分野，只要看一下2003年时对美国伊拉克战争的各国态度就可以了然于胸。当时美国表示支持其伊拉克战争的“志愿同盟”（Coalition of willing），在欧洲的国家包括“老欧洲”的英国、意大利、西班牙、荷兰、丹麦、冰岛、葡萄牙和“新欧洲”的阿尔巴尼亚、保加利亚、捷克、匈牙利、格鲁吉亚、爱沙尼亚、立陶宛、拉脱维亚、马其顿、波兰、罗马尼亚、斯洛伐克、乌克兰，以及身为“老北约”但老在欧盟门口撞墙的土耳其。可见里面只有荷兰一家“欧盟核心国”，还大概多少和荷兰皇家壳牌石油公司四处找油有点关系。当然，这帮喽啰，大部分都是动动嘴，收点犒劳钱。虽然也不乏像波兰和丹麦那样真积极派兵参加战斗的，还有意大利、西班牙这种看萨达姆倒台后墙倒众人推，尾随着派兵参加占领的小兵。但一旦情况不妙，比如意大利被人肉炸弹袭击，西班牙马德里地铁被恐怖分子爆炸，立即就风声鹤淚，拔腿就跑。

而欧洲硬核法国和德国，在伊拉克战争期间则是完全站在反对的立场上，还和俄罗斯形成了一个三国联盟，抗议美国的独断专行。其实那个时候还真的产生了欧洲最有前景的安全合作机会，当时的三国真是同声同气，采取了共同进退的姿态，来制衡美国独大的局面。
 
图4.8  伊拉克战争期间“志愿同盟”国家分部图——处于老欧洲核心国之外


三十六

如果欧洲东拉俄罗斯，以法国和俄罗斯在联合会的地位和两国的核力量，加上德国的科技和工业能力，法国的文化和潮流影响，以及由德法合作的空中巴士等一系列关键工业，再加上俄罗斯稳定的能源供应、1亿4000万人口和1.29万亿GDP，则就会得到人口2亿8000万，经济总量接近7万亿的法德俄三国集团，几乎和美国在政治、军事、经济上平起平坐。

当然美国是不会这么轻易的让欧洲这样搞三强整合，折腾出一个可以摆脱美国领导的失控局面的。美国用的方法是利用了德法联盟和俄罗斯整合中间那个最大的障碍，即是地理上在他们中间隔着的国家——波兰。七十年前，在德国和俄罗斯针锋相对，互相死掐的时候，中间隔着一个波兰，当然是一个好的缓冲区，但在两国希望紧密团结，共同对外的时候，再夹着一个不听话的波兰，那就是一个大桩子，造成俄罗斯和德法联盟之间的困扰。

要是换了以前，在希特勒和斯大林当政时，如果想要相互合作而又看到这个波兰这么麻烦，肯定是重操故计，两边一夹击，把波兰给分了。当然今天情况大不相同，波兰的背后有美国撑腰，德国本土则有美国重兵驻扎，再加上俄罗斯相对实力衰退。波兰人拉上美国这个大力士，在两个不可靠的大国中间也可以安稳睡觉。

当年虽然希特勒对波兰人进行的杀戮，和斯大林不分伯仲，但似乎今天的波兰人对德国人的原谅似乎多于对俄国人的历史宽容。这从德国足球队的两大波兰裔前锋克劳泽和普多斯基为德国效力的行为，似乎可以看出一二。而机智的美国人看准了这个契机，在波兰建立针对俄罗斯的全球导弹防御系统，在属于北约集团的德国和北约之外的俄罗斯之间插进一只脚，使它们在反伊拉克战争建立的同盟没有了持续发展的空间。而由于欧洲人普遍不满俄罗斯在西方尊崇的民主自由价值上的退却，也使得德国和法国国内人民产生了对俄罗斯长远计划的疑虑。再加上德国领导人更迭，换上了个意识形态挂帅的昏头女元首默克尔，更让美国人破坏德俄合作的计划事半功倍。

美国在波兰建立反导弹系统的基本考虑，就是挑起和俄罗斯新的军事冷战对抗，以拉俄罗斯进入新军备竞赛的方法，打击俄罗斯在普京执政后和世界石油价格高企的情况下出现的中兴局面。在挑起与俄罗斯的对抗后，美国可以利用和波兰以及捷克的双边协定，保障其国家安全，又可以利用其在北约的操控力，在英国以及一帮新欧洲的喽啰的鼓噪下，将德法联盟拖落水。

而俄罗斯在格鲁吉亚的军事行动，则会迫使波兰加速向美国妥协，将讨价还价了好一段时间的反导弹布防协定立即签署，并且逼迫欧盟和北约中的老欧洲国家重新考虑乌克兰和格鲁吉亚的入会问题。同时美军可以借人道援助的借口，入驻格鲁吉亚，这样可以由特工操作在达吉斯坦和车臣的破坏行动，对俄罗斯特工在格鲁吉亚油气管道安全上的操作，来个以眼还眼，以牙还牙。

另外一个对德法联盟和俄罗斯整合有阻碍的问题就是，所有俄罗斯的石油和天然气管道都要从乌克兰和波兰经过，才可以达到德国、法国和意大利这些欧洲市场。


三十七

2006年3月-4月期的美国《外交事务》杂志 上，出版了一篇标题为《美国核力量独霸的崛起》的文章，向全世界发出了这样的警告：冷战时代两极拥有能互相毁灭的核武器的核平衡时代已经接近结束，今天是几乎冷战以来，头一次，美国一国差不多接近获得核独霸的地位。在不久的将来，美国既有可能具备了在第一轮打击内就可以彻底摧毁俄罗斯或中国的远程核武库的能力。而俄罗斯、中国和其余的世界所有国家，将在未来的许多年里，都要苟且偷生在美国核独霸的阴影下。

在苏联垮台后十年内，俄罗斯的战略核武器也像其经济一样，受到了致命的打击，其远距离轰炸机数量下降了40%，远程弹道导弹数量下降了60%，最要命的是那进行核反制的关键武器——可以在第一次核打击下保持生存的核反击力量，发射远程导弹的核潜艇，居然下降了80%。而与此同时，美国的核武器得到了长足的发展。美国开发出了新一代的射程为3500公里的战斧导弹，这些导弹高速而精确，几乎是不可拦截。仅2003-2006短短三年间，美国已经在各类军舰上安装了6000个发射装置。以美国当前的实力，基本上可以在第一波的攻击中，彻底打击所有的俄罗斯战略目标。

正是以这种强大攻击力为后盾，美国决心在波兰和捷克安装全球反导弹系统，主要目的是帮助美国在对付俄罗斯上，补偿原来对俄罗斯导弹早期预警的缺陷。在没有这些东欧基地之前，美国需要几分钟的时间才可以计算出俄罗斯发射的弹道导弹的各种数据。而在捷克安装监视雷达后，这个过程缩短到了几秒。因此，一个可行的攻击俄罗斯的计划是，首先由巡弋在波罗的海和白令海的美军舰艇，发射巡航导弹摧毁俄罗斯的远程核武器的井底发射架、移动发射车、核潜艇和战略空军。而且还可以摧毁指挥中心、导弹防御系统、军事机场、海军基地和通信中心。然后再发动第二波的攻击，由航空母舰战斗机群和远程轰炸机群，打击地面军事力量如陆军的坦克和装甲力量，以及军事工业。在某种程度上，美国已经在对付阿富汗、伊拉克和南斯拉夫的战争中，对这个作战策略进行了小规模的预演。
    
 
图4.9  美国摆出来的波兰反导系统是为了防范伊朗的示意图；美波反导系统签署；俄罗斯白杨M型导弹

俄罗斯当然十分明白这个道理，并将建立在波兰和捷克的反导弹系统，看成这个战略的核心组成部分，因此当美国声称这些系统是为了防备伊朗的导弹时，普京反唇相讥，提议说既然你是为了防伊朗，那么干脆将反导系统放到俄罗斯在阿塞拜疆的基地以提高防范伊朗的能力吧。当然，美国不会吃他这一套。

那么俄罗斯的反制方法是什么呢？俄罗斯的白杨-M型洲际导弹是世界上仅有的在加速到超音速时还能在每分钟内两次变换方向以逃避雷达测探的弹道导弹。这个导弹也可以用于短程发射，令美国的导弹防御系统无计可施，利用其多弹头再入分离器系统，可以同时携带针对不同攻击目标的10个核弹头。所以俄罗斯的反制手段是，当美国开始对俄罗斯进行打击时，在美国巡航导弹发射后的10-15分钟内，俄罗斯用携带核子弹头的短程导弹，攻击美国的反导弹系统和其他欧洲各国。美国的巡航导弹需要2个半到3个小时的时间，才能击中所有的俄罗斯目标，而俄罗斯的核弹头，只需要10-15分钟，就可以摧毁捷克。

而在捷克的雷达被摧毁后，俄罗斯在北海待命的核潜艇，就会在第20分钟攻击波兰。俄罗斯相信，因为核战略平衡已经被美国在核科技的领先而打破，俄罗斯唯一的选择是在攻击方制造不可接受的损失，而逼美国坐下来谈判。


三十八

当然从美国现在的态度来看，好像它对俄罗斯的对策不以为然。而且除了在军事上对俄罗斯加大压力之外，美国还以重金支持俄罗斯内部的反普京势力，企图以支持人权和民主的名义，在俄罗斯制造内讧。美国国务院也把针对俄罗斯的颠覆列为其2007-2012年的主要任务之一。

当然，对中国，美国也有同样的战略考虑。但是其对华反导系统的计划部署国家，一个是日本，一个是澳洲。这两个国家这数年下来都与中国经济关系过于密切，让美国的计划实施存在难度。尤其是在澳洲，陆克文上台给自己定下的一个主要任务，就是不要学霍华德 ，栽进和中国对抗的陷阱。至于日本，在中国成为其最大的出口市场之后，任何挑起中日关系冲突的行为，必然受到企业界的全力抗拒。

美国在波兰和捷克的作为，以及在乌克兰和格鲁吉亚的举动，都把欧盟尤其是德法联盟摆上了台。俄罗斯素来有以大帝国自居的脾气，不甘被人宰割，以它融合了北亚草原民族如蒙古人血液的简单粗暴的性格，一定会大力反弹。而这种反弹就发生在了格鲁吉亚身上，结果却迫使所有的欧洲国家不得不进行“政治正确”的表态去支持格鲁吉亚。当然，西方的大部分回应都是虚张声势，除了美国进军格鲁吉亚去人道援助，北约在黑海显示军力外，所有亲美的“新欧洲”东欧小兵和英国，都会大声鼓噪，想重新在乌克兰和格鲁吉亚入北约一事上翻案。此外还可能会像当年美国副国防部长沃尔福威茨烧中国贝雷帽一样，在一些象征性的国际事务上撕面子，比如说把俄罗斯赶出G-8，不允许它加入WTO，给俄罗斯难看（WTO之所以已经要沦落为“象征性”的空谈俱乐部，是因为这个组织在如今金融、粮食、贸易保护主义重起的一拨一拨危机的冲击下，估计不久就要破产了，而且除了能源这个命根子，俄罗斯本来也没有多少东西可卖）。但是，确实有些惩罚招数就会比较有真正的杀伤力，比如要求欧盟所有的国家不能单独和俄罗斯签署双边能源协议，而要欧盟整体行动批准。以欧盟那种办事磨蹭到太阳下山的风格，估计能断绝俄欧能源协议的可能性。

之前笔者谈过俄罗斯对欧洲的天然气和石油输送，天然气是大头，而石油的量其实并不是很大，其总数大致在2007年为一天476万桶，其中还包括其他中亚国家如哈萨克斯坦等国的产量，而俄罗斯自己的产量大概是394万桶，其中卖到德国的只有42万桶。本来德国的总石油消耗量是一天265万桶，不是太多，因此就算是俄罗斯能够完全把哈萨克斯坦的那块油源垄断，其欧洲市场也并不大。

为什么会出现这种需求绝对量相对不大的情况呢？最主要的原因就是西欧的经济科技已经比较成熟和合理。在西欧，汽车是一种奢侈品，而不是美国那样的生活必用品。欧洲人日常出行更多依靠节省能源的公共交通，汽车也都是小排量的且并不热销，所以对石油的需要量基本上已经稳定，没有太多成长的空间。德国以外的欧洲国家，如法国日用197万桶，意大利日用188万桶，英国日用183万桶，都比较低。虽然世界油价的大涨，会使得一些工业用户以及个人如出租车司机和渔民受到冲击，但对其真正的经济损害有限。前一段整个石油的炒作，主要是用中国的经济发展为借口，如果中国可以走欧洲的发展道路，在2010-2011年后，以天然气和其他非石油能源为主要能源支柱。那么估计其他发展中国家如印度就会立即跟进。而这样会导致世界石油需求预期降低，使国际石油价格降低到40-60美元一桶 ，对于中国和各个非产油新兴国家的发展有缓解负担的作用。当然，这可能会对主要靠依赖石油出口的国家，包括俄罗斯，带来一定程度的影响。


三十九

所以说俄罗斯对“巴库—第比利斯—杰伊汉”油管的争夺，只是一个虚晃一枪的幌子，因为这个管道出的油，是摊给亚洲、美国和欧洲的，而且如果拿不到哈萨克斯坦的供油，这个流量不足的管道就会一直亏损下去。俄罗斯的真实意图似乎是敲山震虎，企图阻吓从土耳其埃尔祖鲁姆出发延伸到奥地利的纳布科(Nabucco)天然气管道，而保障俄罗斯提倡的南部的天然气“南流”线路。天然气，而不是石油，才是欧洲的命门。下面，笔者就开始谈谈俄罗斯对欧洲战略中的重头戏：天然气。

欧洲对天然气的需求，和石油相比，是一个不同的图景，天然气才是欧洲能源的主角，俄罗斯在天然气上才能握住西欧的软肋。但从俄罗斯输往西欧的天然气，和其石油一样，必须通过两个国家才可以到达目的地。而这两只拦路虎，一个是乌克兰，一个是波兰。所以对于敌视俄罗斯的人来说，只要控制住了这两个国家，就等于卡住了俄罗斯的天然气能源出口。

自从乌克兰颜色革命之后，俄罗斯就一直试图控制乌克兰的天然气管道，不惜通过威逼和利诱的方式，但仍然无法使乌克兰就范。最后双方因为定价的争执，使俄罗斯在2006年1月，对乌克兰停气。但乌克兰就从天然气管道里偷气，结果导致了后面的欧洲国家供气不足，影响了俄罗斯对这些国家的服务保证。这之后，又闹过一次乌克兰赖账不肯付钱的事件，使俄罗斯对其深恶痛绝，但又苦于不能得罪德国和意大利这些大客，居然对乌克兰无计可施。
 
图4.10  俄罗斯及其周围地区对欧洲天然气供应的路线图

现在的情形是，俄罗斯有两大类天然气管线进乌克兰，一条由白俄罗斯过乌克兰西北部，和其他两条在西乌克兰相交汇在一起，叫TransGas线，经斯洛伐克，在其境内分两道，北入捷克进德国，南入奥地利进意大利。北边又有一条叫“Yamal-欧洲”线 的，是从白俄罗斯过波兰，入德国北部。而东南边还有一个从俄罗斯的图阿普谢港附近穿过黑海东南部，到土耳其的萨姆松港的“蓝流”管道，它经安卡拉过博斯普鲁斯海峡进伊斯坦布尔，用于供应土耳其。现在俄罗斯天然气最大的客户是乌克兰，向它年供635亿立方米，占其消费量的66%，然后就是德国390亿立方米，占消费量的36%；土耳其234亿立方米，占其消费量的64%；意大利210亿立方米，占它消费量的25%；法国98亿立方米，占消费总量的20%。

从这里可以看出，如果俄罗斯可以和土库曼斯坦签订协议，比如现在谈妥商定，于2009年开始建立天然气管道，通过俄罗斯向欧洲送气，其市场的前景会非常乐观。但是要使这个前景成为现实，不受波兰和乌克兰的干扰，俄罗斯必须设计一个绕开正道（中部线路）的迂回路线。即和西欧最大的两个市场德国和意大利合作，建立一条北线，可以绕过波兰供气德国，再建立一条南线，可以绕过乌克兰供应意大利。如果这两条线路建设成功，俄罗斯就不会再像现在这样投鼠忌器，而是直接将乌克兰，波兰和捷克的供气卡断或者抬高价格，让这些国家老老实实，不敢再去做美国的小走卒。并且杀鸡给猴看，让其他那些东欧喽啰，如罗马尼亚，匈牙利等，乖乖的看俄罗斯的脸色做人。

这个北线计划，就是从圣彼得堡附近的维堡（Vyburg）出发，通过波罗的海海底，直接接到德国的格拉斯夫。如果这个管道能建成的话，其输气量可以高达300亿立方米一年。而这个所谓“北流”计划（Nord Stream）的总裁就是德国前总理施罗德 ，但是由于其管道必须避过波兰的海域，还牵涉到芬兰、瑞典、丹麦的领海，它的环境保护报告迟迟不能通过，需要花多点银子才可以最终成功。


四十

而南线计划则是和意大利合作（起初邀请了意大利前总理普罗迪 出任总裁，但没有应允），从黑海的伯里哥法亚开始由海底线路进保加利亚，然后通过俄罗斯的血肉兄弟塞尔维亚和黑山，再过海进意大利。另外还可分一条管道，从塞尔维亚入匈牙利，进奥地利这个欧洲的汇集点，然后分流到德国、法国等地。这条管道的好处在于塞尔维亚和黑山是自家兄弟，既可以保证管道安全，又可以在经济上帮他们一把，实在是皆大欢喜。至于保加利亚，俄罗斯已经于2008年初搞定，由两国一国一半拥有输气管。这条管道的输气量也是预订在300亿立方米一年，两条线路运行后，就可以让乌克兰、波兰和捷克这帮头上生反骨的东欧魏延们喝一壶了。

但是这里有一个关键的问题，就是在黑海底铺设的管道，必须经过乌克兰的海底大陆架，因此必须乌克兰同意其出具的环境影响研究认证报告后，俄罗斯才可以开工。而俄罗斯筹划的这条管道，本来就要绕过乌克兰，修建一条俄罗斯能全盘控制的线路，可想而知，是不可能被批准的。

这里又扯出了下一个热点，那就是克里米亚。换句话说，如果这个超过70%人口是俄罗斯族的自治共和国宣布独立的话，凭借驻扎在港口的俄罗斯黑海舰队，乌克兰就不再拥有对这个海域的发言权。

其实在1992年5月，克里米亚国会已经通过了独立法案，但决定暂不执行。而俄罗斯国会在同时通过法案，宣布取消1954年由赫鲁晓夫把克里米亚从俄罗斯苏维埃共和国划给乌克兰苏维埃共和国的决定。在1994年，克里米亚的地方总统的竞选口号就是“与俄罗斯统一”，只不过在俄罗斯和乌克兰双方政府的督促下，才没有折腾下去。

如果现在由格鲁吉亚挑起的这场冲突继续扩大，尤其是乌克兰现政府强行加入北约的话，估计大家将看到乌克兰会分裂成东西乌克兰两个国家，而克里米亚则要么加入俄罗斯，要么寻求独立。这将会是欧洲的下一个热点。
 
图4.11  克里米亚地图、国旗和赫鲁晓夫

以目前的形势，俄罗斯已经宣布承认阿布哈兹和南奥塞梯独立，但同时又开始在新闻里大肆报道，重新恢复格鲁吉亚人斯大林在俄罗斯历史上的地位。笔者估计普京希望发出信号：俄罗斯对格鲁吉亚没有恶意，只是对美国代理人萨卡什维利深表反感，如果格鲁吉亚人民决心推翻这个政府，重新和俄罗斯和好，那么阿布哈兹、南奥塞梯这些地区的归宿问题还有的商谈。而当大部分格鲁吉亚人觉得被萨卡什维利误导，被美国出卖之后，会有什么选择，现在断定还为时过早。只不过格鲁吉亚人和南奥塞梯人的居住太混杂，不是很容易划出一条清晰的分界。任何真正的独立和分治，都会牵涉到种族的迁移，也许就会搞得像当年印度和巴基斯坦那样。

只不过无论最后的结局如何，对这两个地区的人民都是一个安全的保障。普京用了一招俄罗斯人最拿手的老伎俩（当初在中国的伊犁地区也用过），即从2000年起，发给这些地区人民俄罗斯护照，因此任何针对他们的军事行动，俄罗斯都可以理所当然的以保护本国公民的名义进行干预。

