# -*- org -*-

# Time-stamp: <2011-08-04 12:05:57 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 星期四 05年7月14日




** 日本批准企业在中国专属经济区试开采石油天然气




【东京14日消息】日本经济产业大臣中川昭一１４日下午举行紧急记者会，正式宣布批准帝国石油公司在东海海域的中国专属经济区试开采石油天然气。这是日本政府首次认可日本企业在中国的专属经济区开采中国石油天然气资源。

日本经济产业省４月开始启动审批民间企业试开采东海油气田的手续。由于中日两国在这一海域的权属问题上存在严重争议，到目前为止，只有帝国石油公司一家正式提出试开采申请并获得批准，其他企业还在观望。

在日本经济产业省授予帝国石油公司试开采权后，该公司须在３０日之内交纳完毕“试开采执照税”，并由九州经济产业局给予登记注册。然后提出详细的试采掘施工方案，进入试开采准备阶段。

一些石油开采企业认为，近来，中日两国在历史认识以及历史教科书等问题上摩擦不断。在这个敏感时期参与试开采存在严重争议的东海油气田，势必会使两国关系进一步紧张。日本部分企业认为，帝国石油公司虽然获得了试开采权，但真正进入实际采掘，还必须慎重判断。　

中日东海油气田之争源于中日专属经济区界线的划分之争。按照《联合国海洋法公约》的规定，沿岸国可以从海岸基线开始计算，把２００海里以内的海域作为自己的专属经济区。专属经济区内的所有资源归沿岸国拥有。中日两国之间的东海海域很多海面的宽度不到４００海里，日本主张以两国海岸基准线的中间线来确定专属经济区的界线，即所谓的“日中中间线”。但日方提出的中间线主张没有依据。中方一直没有承认。而东海海底的地形和地貌结构决定了中日之间的专属经济区界线划分应该遵循“大陆架自然延伸”的原则。中方考虑到存在争议，为了维护两国关系，一直没有在存在争议的海域进行资源开采活动。对于东海划界问题上的争议，中方一贯主张双方应该通过谈判加以解决，多次强调，“搁置争议、共同开发”是解决东海问题的唯一正确选择。




【时事点评】在东方评论员看来，日本在这个时候宣布“正式宣布批准帝国石油公司在东海海域的中国专属经济区试开采石油天然气”的消息，显然与赖斯从北京转道东京、这中间的“点点滴滴”直接相关。


*** 小泉抛出“这个消息”，显然是“美日”精心计划中的一步

东方评论员认为，在赖斯于北京“公开承认”“朝核问题”“不再是”美国之前坚持的”朝鲜无核化问题“、而是中国所坚持的“朝鲜半岛无核化问题”后、华盛顿在朝鲜半岛的“无力感”是一览无遗。

在这种背景下、我们注意到，小泉纯一郎在与赖斯协调了“朝核问题”立场、离开日本抵达韩国之后、“美韩”却因彼此基本立场的“分岐巨大”、而在“自说自话”。因此，东方评论员认为，小泉政府在盘算多日之后、选择在赖斯离开韩国之后不久、就立刻抛出“这个消息”，显然是“美日”精心计划中的一步。


*** 东海问题一直是中日关系“极其敏感”的一个问题

事实上、东海问题一直是中日关系“极其敏感”的一个问题。我们知道、4月份前后，中日间的一轮外交大战、最直接的导火索就是“日经济产业省在４月开始启动审批民间企业试开采东海油气田的手续”。

对那场外交角力，相信大家仍然有深刻的印象、那就是，面对日本右翼挟着自己不可告人的私心、在迎合美国战略需要中、急剧“窜起来”的“极其嚣张”，中国的对日政策也调整得“极其强硬”、结果是、在北京发出“事情（中日关系）的性质将会发生改变”的强烈警告后，终于经过日本外相的“北京败北”日本首相的“公开道歉”而告一段落。


*** 中日关系变得“毫无弹性”的几个因素

在东方评论员看来，总体而言，中日关系已经变得“毫无弹性”可言，但是，我们认为，造成这一局面的真正原因，并非取决于中国“愿意与否”、而是取决于下面几个主要因素”：

第一，在东方评论员看来，过去一百多年、日本之所以能成为中国最凶恶的敌人，就在于它甲午战争中打败了满清政府、通过对中国的掠夺与破坏建立了强大的经济和军事实力、使其实力在100多年来、一直在中国之上、并因此而自我造就了一番“民族优越感”。


*** 历史上，中国的统一、与民族资本的快速发展趋势、就引起过日本的“紧张与不满”

然而，早在清政府经辛亥革命推翻后，新成立的中华民国内部尽管矛盾重重、军阀割据、国家内乱不断、但随着西方现代科学技术的源源流入，逆境下中国社会的经济生产力水平还是取得了相当程度的发展进步；而且随着时间的推移，民国中央政府还是逐步地成功剥弱了各地区割据军阀们的势力，中国实现内部社会彻底统一的前景！

很显然，中国的统一趋势、与民族资本的快速发展引起了日本高度的紧张与不满。据史料称，当时的日本关东军司令本庄繁、就坚决主张“必须要抢在中华民国政府实现全中国的彻底统一之前抓紧机会发动全面的侵华战争，并乘西方诸列强尚未从一次世界大战的创伤中恢复过来、无暇东顾之机，彻底武力征服中国、进而独霸之！”


*** 日本全面侵略中国，还在于一个“罪恶目的”

在东方评论员看来，日本关东军司令本庄繁（后来自杀），是一个极其了解中国内情的“中国通”，他之所以主张“抢在中华民国政府实现全中国的彻底统一之前抓紧机会发动全面的侵华战争”，其思想就源于日本帝国早在明治维新初期就提出了“先蒙满后中国、先中国后世界”的“全球殖民方针，并认为当时的中国、就是实现这套“全球殖民方针”的最好机会。

值得强调的是，当时主张全面侵略中国的本庄繁、这个了解中国内情的“中国通”之所以会认为当时侵略中国是最好的机会、还在于一个罪恶目的，那就是通过战争“及时打断”中国的民族工业发展进程、从而让中国的经济和科技“永远成长不起来”。


*** 日本人的“远大抱负”、说白了恰恰是在战略上的“幼稚无知”！

然而，东方评论员认为，当日本最早提出这套“全球殖民方针”时，其国力尙远远不如当年作为世界第一强国的大英帝国。有意思的是，这个大英帝国在经历了长期的对外侵略与殖民统治之后，其“经验与教训”就已经告诉了英国人在中国这块土地上、“什么应该干、什么不能干”。

在我们看来，率先用坚船利炮打开中国国门的英帝国、在面对中国广阔的国土和众多的人口，寻思着“能干的东西”里面、就没有日本人的这种“先蒙满后中国、先中国后世界”的“全球殖民方针”、而“只满足于”割去中国的香港、通过与中国“做生意”的方式、着眼于“在经济上”殖民中国。

事实上，在东方评论员看来，大英帝国“没有心思”占领中国的另一个原因，就是在欧洲、美洲有太多的列强“需要去制衡”、这就是说，英国人知道“做什么都是要付出代价的”。

由此可见，日本人的“远大抱负”、说白了恰恰是日本人在战略上的一种“幼稚无知”！


*** “幼稚无知”的日本人、在历史上就为美国全球战略“所充分利用”

在东方评论员看来，日本在战略上的“幼稚无知”还远不止于此，侵华战争之后，日本庞大的军事资源都投放在中国大陆，对中国的久攻不下、以及对苏联军事力量的顾忌、极大消耗了日本的国力。

再加上欧洲列强彼此间也消耗得差不多了，在亚洲方向，美国终于开始一改早先对日本“什么都卖”的中立政策、“策略地”收紧对日本的战略物资出口、促使日本的军事机器开始走向无以为继的边缘。

也正是在这种背景下、战略上“幼稚无知”的日本、表面上是为了寻找西太平洋上的资源、特别是石油资源而主动攻击的美国、但事实上、日本却是被美国“逼进”夺取“英美西等西方列强”在亚洲殖民地的太平洋战争的。显然，战略上“幼稚无知”的日本人、当时并不清楚“主动地”与所有强权、特别是与当时的生力军--美国为敌、不仅保不住已经占领的土地、反而在军事上更加无以为继。

结果是，美国在英国人最希望美国加入战争的欧洲战场方向之外、率先在英国等老牌帝国鞭长莫及的西太平洋上攻城拔寨，借打击日本法西斯的旗号、顺便将英国法国等“西方反法西斯盟友”的利益、通过让当地人独立的手段、也一一消减干净。而英国、法国也只能眼眼睁睁地看着美国“名正言顺地”就这么收刮自己、而说不出一个不字。

由此可见，“幼稚无知”的日本人、在历史上就为美国人“所充分利用”，被彻底纳入美国的全球战略之中。



*** 昨天的“这一幕”似乎又要在今天的大国角力中重新上演

在东方评论员看来，如果日本社会不能主动制止日本右翼的冒险、昨天的“这一幕”似乎又要在今天的大国角力中重新上演。

前面说了，当时日本全面侵略中国、还在于一个罪恶目的，那就是通过战争及时打断中国的民族工业发展进程、从而让中国的经济和科技“永远成长不起来”。现在，国家的利益更多地是在靠军事力量的支撑、通过经济上的渠道来夺取的。

因此，如何借助美国遏制中国的战略需要、实现军国主义复活、并及时打断、阻碍中国业已成长起来的“经济与科技”之进一步成长的道路、从中国手中重夺东亚领导权、显然成了日本保守势力的又一“战略梦想”。


*** 日本通过“衰败的十年”、也终于明白了一个道理

事实上，没有政治、军事力量保障的日本，在经济上是吃了大亏的。特别是战后４０年的高速发展又是日本人以为在经济上战无不胜，并一度用“日元”、而不是用“炸弹”在美国攻城拔寨，从夏威夷沙滩、到美国地标、是一一置于禳中，直至美国人惊呼日本人收购了整个美国。

只是不曾想到，在经济上锋芒毕露的日本、却在80年代后期至90年代初期、一再遭遇美国的政治强压、用“汇率武器”发动的强力反击、并因此导致经济上的大衰退。

因此，日本通过这“衰败的十年”、也终于明白了一个道理、那就是没有独立的政治、军事力量、根本就不可能有独立的经济政策，充其量不过是个“经济大国”、在“本质”上不可能是个“经济强国”、就是勉强做到了，就会对别人产生威胁，别人也不充许你去做什么经济强国。


*** 清醒地认识到现实国际政治“残酷性”的法德两国、选择了合作

东方评论员认为，法国、或者德国所选择的路应该是日本认真思考的，如果按日本的逻辑去思考、那么以法国和德国的条件、都会彼此间争个你死我活。

然而，事实上不是，这两个在二战中打得你死我活的邻国、心里明白、在这个世界上，美国是容不得法国、或者德国来挑战其世界霸权的、特别是德国心里更是有数，因为仅凭二战那段历史、就足以让华盛顿发挥一切想像力、将德国孤立起来、并制造欧洲内部的对立。

结果是，清醒地认识到现实国际政治残酷性的法德两国、也就选择了合作、借一个强大的欧盟来实现自己的强国梦。特别是德国、资源同样匮乏、自己的军力也不强，也没有核武器，也明白没有军事保障，就没有经济保障的道理、但是，德国人非常聪明地选择了与法国和解、选择了与法国一起、共同努力做大、做强欧盟、意在让欧盟的政治、军事力量来保护自己的经济发展空间，借欧盟的掩护、来实现自己的政治报负。


*** 与德国相比，日本在国家战略决策上仍然充满了“幼稚”

显然，日本却拒绝这样做，拒绝与中国合作、拒绝通过亚洲一体化、将整个亚洲做大、做强、并通过一个强大的亚洲来保障自己的经济发展空间、来避免80年代未被掐着日本生命线的美国、强行用汇率武器打掉了日本的经济发展势头的历史重演。

不难看出，与德国相比，日本在国家战略决策上仍然充满了“幼稚”，幼稚到相信一个没有军事力量、在国际上没有政治形象、没有自然资源、且与整个亚洲为敌的日本、就是能“在与美国、中国、甚至是欧盟的相互利用、相互竞争中”最终胜出、就是能最终摆脱中国压制、美国的控制的东亚安全格局、就是能在不依靠亚洲的情况下、独自与欧盟和将美洲视为自己后院的美国来进行“经济决斗”，并在同时、从政治上（历史问题）、军事上（钓鱼岛、东海主权争端）、经济上（打断、干扰中国的经济建设）全面压倒中国、逼迫北京做实质性的让步，从而在亚洲、甚至是世界强权面前“彻底毁掉”中国的形象、中国正在努力强化的、一个“负责任大国”的形象，从而最终取代中国、领导亚洲、最终实现自己的大国梦。


*** 日本的“革命”才开始、就已经陷入了德国极力避免遭遇的“孤立处境”

然而，现实是残酷的，对日本而言，旨在与中美争夺东亚领导权、企图颠覆现存的东亚安全格局的“革命”才刚刚开始，可以说就已经陷入了德国极力避免遭遇的孤立处境，在东方评论员看来，从日本在花了大把日元之后，竟然在亚洲找不到一个在共同提案上签名的亚洲国家，甚至是被美国极力拉拢的、日本酒了大把金钱的越南也“都不敢愿意”，从这就可以看出日本被自己那套“不自量力的大国战略”孤立到了何种地步。


*** 一个没有自信、急功近利、惧怕强权的日本保守势力、有什么资格去争什么亚洲领导权？

在东方评论员看来，日本之所以拒绝中国提议的东亚、东南亚国家、印度提议的亚洲一体化、一方面是惧怕中国在亚洲一体化中居于领先地位，显然，这根本就是“没有自信”的表现；

另一方面则是出于日本保守势力的“急功近利”的特性、欲通过让军力快速突破、来迅速突破受制于目前这种“看不见日本的”国际秩序、还有一个说不出口、却最为亚洲国家不齿的原因，那就是惧怕美国，试问，一个没有自信、急功近利、惧怕强权的日本保守势力、有什么资格去争什么亚洲领导权？


*** “中国政府的选择”将最终决定日本的战略决策“是幼稚、还是明智”。

显然，说一千、道一万，日本保守势力在没有栽“更大的跟头”之前，日本社会恐怕是不会回头的，因为就“历史与现实”来看，日本本来就是个“问题国家”，大和民族“本来就不是个有大智慧的民族”。

因此，东方评论员认为，在日本保守势力再次认为现在就是打断中国现代化进程的、确保自己能压倒中国之“天赐良机”、准备进行政治、军事冒险的时候，毫无疑问、“中国政府的选择”将最终决定日本的战略决策“是幼稚、还是明智”。

不过，在东方评论员看来，日本保守势力是在将北京“可能的激烈反应”计算在内之后、才宣布对日本企业发放许可证的。剩下来的，无非就是紧张地等待中国的反应、再图后策。

因此，我们也不妨也来看看北京在和一时间内做出的反应。下面，是我们刚刚收到的、由中国最权威官方媒体新华社的一则新闻稿。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com


** 我国将毗邻区和专属经济区海域纳入海事监管范围





【北京14日消息】新华社北京7月14日电：交通部海事局的海事巡逻船“海巡31”号，目前正在东海海区执行巡航任务。交通部海事局常务副局长刘功臣表示，今后，中国海事将把毗邻区和专属经济区海域纳入正常监管范围，不断加大巡航监管力度。

刘功臣介绍说，“海巡31”船已先后对南海、东海和黄海水域的毗邻区和专属经济区海域的国际航线、海上施工作业区、油气平台及海上过驳作业等进行了巡航监管。

“海巡31”船巡航总指挥、广东海事局通航处处长王继洪介绍，以前，我国的海事巡逻船艇吨位小、抗风能力和续航能力差，主要执行沿岸水域监督管理任务，对毗邻区和专属经济区难以实施有效监管。

在这次巡航中，“海巡31”船使用船舶光电跟踪取证系统、甚高频、雷达搜索、AIS等设备，先后对“春晓”气田和其作业区内的“现代2500”轮、“现代423”轮等以及“平湖”气田进行了查询，对韩国籍“现代2500”轮甚高频无人值守和值守人员不懂汉语等违章行为进行了监管。

近年来，我国海事系统不断加强海上安全监督力量建设，先后建造了一批吨位较大的海巡船舶。今年2月22日加入中国海事监督船舶序列的3000吨级“海巡31”船是一艘适航无限航区的船舶，也是我国第一艘装备了直升机起降平台、直升机库和飞行指挥塔等全套船载系统的民用船舶，把我国海事的有效监管范围拓展到毗邻区和专属经济区海域。



【时事点评】我们注意到，交通部海事局常务副局长刘功臣介绍说，“海巡31”船已先后对南海、东海和黄海水域的毗邻区和专属经济区海域的国际航线、海上施工作业区、油气平台及海上过驳作业等进行了巡航监管”。


*** 这当然是对日本的“事实警告”

另外，这则消息是于日本方面宣布消息之后，就“立刻见诸于世”的，显然，北京对日本的这一轮挑衅、是有事前准备的、特别是提到了中国水域的“毗邻区和专属经济区海域”，不难看出，这是一把就将东海、钓鱼岛所有争议的海域、悉数划入了“海巡31”的“任务区”，这当然是对日本的“事实警告”。


*** 有必要详细了解一下这个“海巡31”

在我们看来，既然中国将“海巡31”作为第一个反击手段摆了出来，我们也就非常有必要详细了解一下这个“海巡31”。

东方军事评论员就表示，该轮为我国首艘3000吨级装备舰载直升机的海上巡视船，也是我国自行设计建造的第一艘装备直升机库的“非军事船”，由于该轮集各种高科技于一身，在技术上具有几大特点：

第一，具有全向海上搜索、通信能力，并拥有一个直升机起降平台、可起降一架EC135型直升机。在5级海况时，不论夜间或白天，直升机均可自由起降。因而，“海巡31”可形成海、空结合的立体海上巡逻。

第二，该船配备了中国第一台光电跟踪取证系统，可以及时快速地捕获目标并进行自动跟踪、可以实现海上现场声像和数据的直升机与船舶之间的传输及船岸之间的互联和传输。

第三，“海巡31”最大航速22节，在18节航速(34.7公里/小时)时，可抗击11级风浪。值得一提的是，该船还安装有电动反渗透造水装置，每天可造水15吨，这就确保其续航力达6000海里，可续航40天。

最后一点，也是东方军事评论员特别强调的，即：“海巡31”是一艘专职海事巡逻的“巨轮”、有3000吨级，这比许多护卫舰的吨位还要大，因此，它已经具有到达“世界任何一个海域和港口”的技术能力，新闻中所提到的所谓“适航无限航区”、就是这个意思。

也正是如此，中国方面在第一时间里就针锋相对地、将海事巡航监管范围“扩展到”中国所有水域、及其毗邻区和专属经济区海域、首先在技术上是有准备、也是有保障的。


*** “海巡31”，似乎就是专门为日本民用探测船只“量身订制”的


显然，这个最新的“监管范围”包括了中日存在争议的东海所有海域、也包括钓鱼岛海域在内、以及相应的国际航线、海上施工作业区、油气平台及海上过驳作业等，这完全是在公开警告日本、“不要尝试”在东海有争议区域“用日本企业”冒险。

否则，以“海巡31”的吨位和技术能力，特别是这些似乎就是专门为拦截、取证、甚至捕获敢进入有争议区域的日本民用探测船只所“量身订制”的。


*** 北京需要做的“第一件事”

事实上，也正是中国在东海问题上态度“非常强硬”，中国高层、国务委员唐家旋就亲口公开警告过日本“谨慎行事”，因此，东方评论员注意到，自日本4月开始启动审批民间企业试开采东海油气田的手续以来，还只有帝国石油公司一家正式提出“试开采申请”并获得批准，而其他企业、“仍然在观望”之中。

显然，日本之所以“有企业在观望”，就有如日本也有一批人认为：小泉政府挑衅中国的外交政策、必然会受到来自北京在经济上、以至于军事上的反击、从而断送中日关系，并在中日关系完全破裂之后、接着就会遭到美国全方位的打压、经济上更严密地控制、而最终“不会成功”。

因此，在东方评论员看来，如何让“取观望态度”的日本企业、特别是对中日关系、美日关系取观望态度的日本政治势力“彻底相信自己的某种感觉”，是北京需要做的“第一件事”。


*** 就目前中日综合实力对比来看，日本在军事方面的选择余地并不大

这样，如果小泉政府出于外交、内政上的双重需要、让日本企业试开采东海资源的话，必然遭到中国“海巡31”这一类“非军事用船”的拦截、甚至扣押，当然，我们也注意到日本经济产业省长官在宣布这一消息时、也强硬地扬言，“在动用军事力量护航方面，日本有多种选择”。

然而，就目前中日力量对比来看，日本在军事方面的选择余地并不大，无非是仗着那个“美日军事同盟”，但是不要忘记了，直到目前为止，狡猾的华盛顿从来没有将“中日有争议的区域”、在法律上规定为美日军事同盟的涵盖范围，这就是美国“置身事外”的最好保证。


*** 美国人非常清楚玩“这种否认之否认”好处、也非常懂得“玩转中日关系”的奥妙

不仅如此，东方评论员还注意到，在钓鱼岛主权问题上、美国甚至在口头上的“公开承诺”都是“一变再变”，显然，美国人非常清楚玩“这种否认之否认”好处、也非常懂得“玩转中日关系”的奥妙，那就是，“美国在东亚的最大国家利益”并不在于中日一旦发生军事冲突后，美国为彻底打败中国、而去冒着核战争的风险去为日本争夺领土，而恰恰就是“中日能够爆发军事冲突本身”。


*** 华盛顿决策层今天在东亚搞得这一切，到底是为了什么？

首席评论员指出，华盛顿决策层今天在东亚所搞的这些“挑唆”、“怂恿”，恰恰就是想要让中日发生军事冲突、从而彻底破裂中日关系、在严重削弱中国实力的同时、将日本也彻底抓在手中，从而给中国极力推动的东亚经济一体化、制造最大的障碍、并在这个过程中、将日本对美国“唯一有竞争力”的经济、科技实力、给消解、融化掉，直到全部纳入美国的经济结构之中、以加以控制。


*** 一种“一针见血”的观点

在这一点上，对美国而言，日本比起台湾来，可利用的价值就要大得多。因此，有国际战略人士就一针见血地指出：站在华盛顿决策层的角度来看，一旦将来需要打“台独牌”、美国如果能够成功做到在战争初期控制住与中国间军事冲突规模、并同时将日本推向台海战争中、制造出中日军事冲突、那么，作为中美最现实的一种利益交换、华盛顿有可能拿一个“尽可能完整”的台湾去换一个被北京“打烂”的日本。


*** 对可能的中日军事冲突、为了取得胜利，北京不会顾忌使用任何手段

对此，东方评论员的理解就是，作为台湾的经济规模和结构而言、无所谓“打烂”、再说，北京不到万不得已、也不会将台湾完全打烂；而对于日本、一旦发展到军事冲突，为了取得胜利，也为了减少损失，关键时候，北京不会顾忌使用任何手段、甚至是战术核突击。

因此，就日本的经济规模和经济结构而言，遭受重创的日本，很有可能会被美国或者欧洲“经济接收”。

不难想像，日本右翼政客在叫嚣“有多种军事选择”的背后，是日本自身军事实力的严重不足。


*** 华盛顿不太可能去为日本的利益火中取栗

如此一来，在东方评论员看来，只要中国单纯地在东海争议海域、钓鱼岛方向、用军事手段教训日本，华盛顿不太可能将那个并不包括这些区域的“美日军事同盟”、冒着与中国开战的巨大风险、给硬套在自己身上、在“核火”中去为日本的利益“火中取栗”。

另外，不要忘记了、中国在自己身边的阿富汗、不用自己动手、只需通过大力支持当地的反美武装、就可以给那里的一万多美军“找足够的麻烦”、在如何支持游击队“打击侵略者”方面，中国在苏联打的那场阿富汗战争中、就做了许多、只不过那时的“中美”是合伙做的，并将鼎盛时期的十万强大苏军拖在那里长达十年之久。

在东方评论员看来，美国人一定会记得，中国在这方面的经验、不比它通过这招拖弱苏联、激化苏联国内矛盾所得到的经验少多少。美国人在与中国公开为敌、且军事交手方面、恐怕自知占不到多少便宜。

事实上，就在日本再次挑衅北京的时候，与日本走得渐进的“台独”也在蠢蠢欲动，突然在南海“太平岛”上做起了文章，然而有意思的是，中国国台办却扔出了一则有关钓鱼岛的消息，说是大陆准备为台湾渔民护渔，显然，“为台湾渔民护渔”只是一种“公开的说词”、真正的目的却正是东海主权问题。在一起了解这则有关“太平岛”的后续消息后，东方时事评论员、军事评论员将继续日本问题的讨论。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
