# -*- org -*-

# Time-stamp: <2011-08-04 11:49:02 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

*  2005年7月01日 星期五


** 【东京消息】据日本媒体6月30日报道，7月6日至8日在英国苏格兰举行的八国峰会期间，美国总统布什将不同日本首相小泉进行单独会谈。

日本外务省官员称，美方给出的理由是，这次峰会布什总统不准备与参加国首脑进行单独会谈。

这个决定使得日本颇感意外和焦虑，因为日本迫切希望能借这次峰会之机获得美国在联合国安理会改革问题上的谅解与支持。

6月中旬，美国抛出自己的联合国安理会改革方案，表明只支持扩大两个常任理事国的名额，一个是日本，另一个未指名。被美国“钦点”的日本处境最为艰难，顺势接下美国的大礼意味着放弃了四国联合作战，也必将为此失去不少支持票；坚持四国团结，强行递交草案要求表决则会开罪美国，同样会希望渺茫。因此，日本目前的策略是不放弃四国同盟，同时努力做美国的劝说工作。

不过，美国好像始终没有让步的意思。日本一筹莫展之际，把希望寄托在八国峰会日美首脑会谈上。但美国刻意在这个时间避开日美首脑单独会谈。

有分析认为，除了安理会改革的因素外，布什不见小泉的另一个原因是牛肉进口问题。自从2003年12月美国发现疯牛病后，日本一直禁止进口美国牛肉，为此美国曾多次同日本磋商，可日本始终没有让步。本来预计今年八九月份有条件恢复对美国牛肉的进口，谁知前几天美国又发现了第二例疯牛病，看来即使布什亲自做小泉的工作，日本也不会对美国牛肉实行解禁。

所以，既然美国难以在“入常”问题上向日本让步，日方也肯定不会在解禁牛肉进口上对美国妥协，干脆来个一概不见，省得见了面却谈不拢，令双方觉得尴尬，让日美关系伤了和气。



【时事点评】在东方评论员看来，在即将举行的八国峰会上，布什将不同日本首相小泉进行单独会谈的消息、可以说让小泉纯一郎“极其丢脸”。

*** “美国的牛肉”硬是能与联合国的常任理事国“扯上关系”

一般认为，“牛肉进口”和“日本入常”，本是两个看起来“互不搭界”的事情，然而，当“蛮横的”布什、遇到了因中日、中韩关系恶化而变得“里外不是人”的小泉之后，“美国的牛肉”就硬是能与联合国的常任理事国“扯上关系”。


*** “牛肉”问题上，满世界“被布什欺负得最厉害的”恰恰就是它的“两个跟得最紧的跟屁虫”

在东方评论员看来，不说别的，就以“牛肉”问题而言，满世界“被布什欺负得最厉害的”不是别人，恰恰就是它的“两个跟得最紧的跟屁虫”，一个就是小泉纯一郎所代表的日本，再就是陈水扁所代表的台湾。

事实上，华盛顿为了疏解国内因“疯牛病”影响出口、而过剩的大量牛肉，一直在运用外交途径拼命地“向可能之地”推销，以解开其它国家或地区之进口禁令，在东方评论员看来，日本和台湾就是美国精心挑出来的“可能之地”。

先看看日本的情况。对小泉纯一郎而言，从一再爆发疯牛症的美国进口牛肉，是不可想像的，在东方评论员看来，小泉纯一郎之所以在这个问题上要对布什说“不”，就在于如果他对布什说“好”，那么，就意味着他得立刻下台。

根据我们的了解，在日本，这不仅是个事关民众健康的大问题、更是一个关乎日本农民利益的大问题，而令小泉纯一郎不敢轻易承诺布什的原因则在于、他所在的自民党一向因是日本农民利益的代言人、而受益非浅。


*** 从“这一片牛肉”上，可以清楚地看到美日关系畸形到了何种程度！

然而，就是这么个谁在台上都不敢让步的问题上，小泉纯一郎却接连遭到华盛顿的“连番重压”。在东方评论员看来，除了这一次外，最明显的一次，就是赖斯在她上任美国国务聊、3月份展开的亚洲“处女行”中，一到日本、赖斯不仅开门见山地提出了“牛肉”问题，而且还“恶狠狠”地撂下话“如果解禁进口牛肉问题得不到解决，将损害美日之间的其他合作”。

在东方评论员看来，值得强调的是，那时日本刚刚把自己的名字添进美国“协防台湾的名单”中、而赖斯在见了小泉之后、还要与北京谈朝核问题、台湾问题、这都是用得着日本的地方。

而赖斯还就敢一边有事求着日本、一边站在日本的土地上、当着小泉纯一郎的面，在那儿“登鼻子上脸”。由此可见，日本在企图借“美国需要自己”之机、“欲拿华盛顿一把”、而实现其一举成为“普通国家”、并“为历史翻案”之战略意图时候、终因中日、日塭关系恶化，失去外交弹性、再加上自身实力不济、而品尝了“捉鬼反被鬼捉”的痛苦，东方评论员认为，从“这一片牛肉”上，我们就可以清楚地看到、美日关系畸形到了何种程度！


*** 在华盛顿的眼里，早已经将日本看透了，也看扁了

显然，在华盛顿的眼里，早已经将日本看透了，也看扁了，在东方评论员看来，正因有了这些背景，我们对布什准备在八国峰会上、拿着“疯牛肉”与小泉纯一郎“比划”那个、早已经被布什“颠来倒去、说话不算话多次”的“支持日本入常”，是一点儿也不奇怪！


*** 相对日本而言，台湾的处境更惨

另外，再看看台湾。作为美国精心挑选出来的另一个“可能之地”，指望美国提供保护的台湾，其代表人物陈水扁也早已经被布什看透了，也看扁了。

相对日本而言，台湾的处境更惨，早先，不仅在并不具备开放条件的时候，就在全球率尔解禁美国牛肉进口，而且，现在美国的“疯牛症”又起，尽管台湾岛内民众纷纷对进口美国牛肉表示强烈不满，但他陈水扁还就是不敢让商家“将美国牛肉下架处理”、更别说禁止进口了。由此可见，嘴巴里满口的“民主、民生”时髦词叫着的陈水扁当局，就是“不干人事儿”。


*** 布什何以敢拿八国峰会“这方国际舞台”给小泉纯一郎脸色看？

在东方评论员看来，布什在“牛肉”问题上敲打小泉纯一郎、不过是在借题发挥，我们认为，布什之所以敢拿八国峰会“这方国际舞台”给小泉纯一郎脸色看，绝不是因为日本不敢松口的“牛肉问题”，也不是华盛顿从来不放在心上的“日本入常”问题，而恰恰是小泉纯一郎访问韩国、从卢武铉身上“赚取点数”的事情、犯了布什的大忌。

在我们继续展开这个话题之前，再来看两则分别来自华盛顿和东京的消息。


《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com



** 美众议院国际关系委员会批准谴责朝鲜决议案




【华盛顿消息】美国众议院国际关系委员会（主席亨利•海德）３０日（当地时间）上午举行全体会议，批准谴责朝鲜绑架并扣留韩国人和日本人的决议案。

据联合通讯社报道，海德计划推进该议案在众参两院获得通过。该案由海德提出。

该议案敦促称：“朝鲜民主主义人民共和国绑架韩国人和日本人是恐怖主义及严重侵犯人权的行为，朝鲜应立即交出所有幸存绑架者和韩军战俘。”

议案中承认解决朝核问题的重要性，但要求美国政府在与朝鲜政权进行谈判时，不应以朝核问题为由，不提绑架事件等重大人权问题。

议案还要求美国政府，在朝鲜放弃国家支持绑架行径以及就所有绑架事件进行完整说明前，不得将朝鲜从支持恐怖主义国家名单中删除。

** 日本官房长官称朝鲜或于本月底重返六方会谈




【东京消息】中日本官房长官细田博之今天声称，朝鲜可能在本月底重返朝核问题六方会谈。

细田博之在新闻吹风会上称，朝鲜方面已不再断然拒绝重返朝核问题六方会谈，朝鲜的立场已发生了变化。

美国和朝鲜官员最近在纽约举行的一系列会议使人们认为恢复朝核问题六方会谈的希望有所增加。

韩国联合通讯社30日报道，朝核问题六方会谈朝鲜副代表李根正在纽约参加一个外交政策会议，他可能与美国官员就重启六方会谈举行会谈。

参加劝说朝鲜重返六方会谈的美方官员包括美国六方会谈特使约瑟夫·狄长礼、国务院朝鲜事务办公室主任吉姆·福斯特。

朝鲜二月份称，它已拥有核武，并拒绝重返朝核问题六方会谈。它正寻求美国作出不对朝鲜动武的保证。



【时事点评】在之前的点评中，我们已经说过，在朝鲜半岛的这场角力中，北京和华盛顿正在上演着一出抢夺韩国的大戏。显然，就如我们在之前的《东方时事解读》中所说的那样，小泉纯一郎从急于启动朝鲜半岛经济整合的卢武铉那里、得到了些许让步、以此为分界点，日本在历史问题上更强硬了，然而，只要我们看看小泉纯一郎自那之后在朝核问题上的表态，就不难看出，日本在朝核问题上显得远不如之前那么爱“多嘴多舌”了。

*** 美国对日本“有点不放心”

事实上，也如我们之前所说的那样，朝鲜半岛经济整合、或者是东北亚经济一体化进程，抛开日本右翼的立场不说，那么，它是“符合”日本的长远国家利益的。在东方评论员看来，也正是有这种“符合”，美国对日本是有点不放心的，担心小泉纯一郎顶不住国内外、特别是中国和韩国的压力，而默许、或者寻机参与朝鲜半岛经济整合进程、从而让华盛顿独力面对中国、俄罗斯帮助韩国实现“借朝鲜民族统一大旗、图谋半岛经济整合”的“危局”。

东方评论员认为，华盛顿有这层担心这也难怪，我们知道、早在去年7月份，在北京明确表示支持朝鲜政治稳定、支持朝鲜进行经济改革之后，日本的小泉政府就是最急于与朝鲜建立外交关系的国家，就经济利益而言，日本不仅有参与朝鲜经济改革的动机，而且，在东方评论员看来，其参与朝鲜经济改革的动机“还是非常实在的”。


*** 卢武铉要有所作为的话，首先自己就得顶住华盛顿随之而来的强大压力

但是，在东方评论员看来，在朝鲜半岛上、下棋的不是日本，而是中美两家，因此，我们认为，如果美国始终坚持“要朝鲜先行弃核”的不妥协之立场的话，那么、首先，韩国的卢武铉要有所作为的话，首先自己就得顶住华盛顿随之而来的强大压力。

另外，东方评论员认为，由于美日间的畸形关系，在历史问题上“不再强硬”的韩国、至多也只能指望换来日本对朝鲜半岛经济整合进程的“不反对”而已。

因此，说到底，只要华盛顿保持强硬，韩国还是得依靠“中俄”这两个军事大国、力争建立一套保障朝鲜半岛和平的多边安全体制，为朝鲜半岛的和平稳定提供保障，从而在“逐渐进行民族统一”的旗号下、去尝试整合韩朝经济。


*** “六方会谈”的六个成员国中，似乎只有美国这一家“绝对不想”看到这种局面

我们认为，不难看出的是，对“韩朝经济整合”这步棋而言，它不仅是韩国、朝鲜想要的一种结果，也是斯科想走到的一步，更是北京希望看到的一种局面，就是日本人、如果站在日本的经济利益的角度去看，也没有强烈的动机去坚决反对。

因此，在东方评论员看来，“六方会谈”的六个成员国中，似乎只有美国这一家、有100个理由认为它“损害了”美国的独霸全球的战略计划、“破坏了”华盛顿遏制中国、包围俄罗斯的战略布局，从而“绝对不想”看到这种局面。


*** 短短数天，布什手中的“破坏者名单”就愈来愈长。

于是乎，每当朝核问题的气氛有所缓和的时候，美国的一些政治人物往往就会跳出来，说一些“不合时宜”的话、尽可能地去化解“韩国的努力成果”、阻止“朝核问题”以一个“同情朝鲜的立场”之方式、在一种“相对公平、合理”的模式下、“分步”解决的可能性。

在之前的点评中，东方评论员多次强调，眼下，布什一直在让赖斯和切尼轮流出场、扮演着这个“破坏者的角色”，昨天，“破坏者”的名单中、又加进了驻韩美军司令拉波特这个新名字。

过了一天，美国的国会又亲自披挂上阵，通过“批准谴责朝鲜绑架并扣留韩国人和日本人的决议案”的方式，再次对“各方的努力”说“不”。在东方评论员看来，短短数天，布什手中的“破坏者名单”是愈来愈长。


*** 美国国会通过的这份议案“非常有针对性”

东方评论员注意到，美国国会通过的这份议案“非常有针对性”，第一，它“承认解决朝核问题的重要性，但要求美国政府在与朝鲜政权进行谈判时，不应以朝核问题为由，不提绑架事件等重大人权问题”。同时，该议案还“要求美国政府，在朝鲜放弃国家支持绑架行径以及就所有绑架事件进行完整说明前，不得将朝鲜从支持恐怖主义国家名单中删除”。


*** 布什“放风”在不单独见小泉后、小泉也赶快出来对朝核问题“吹风”

而一向“唯华盛顿马首是瞻”的日本，在布什“放风”在“G8峰会”上不打算单独与小泉纯一郎“聊一会”之后，今天也恰到好处地出来“吹风”，再次对朝核问题上“高分贝”发表见解，说什么“朝鲜方面已不再断然拒绝重返朝核问题六方会谈，朝鲜的立场已发生了变化”。对此，在东方评论员看来，真不知卢武铉“是气还是恨”！


*** 布什和小泉纯一郎这是在“一唱一和”，对卢武铉“打横炮、使邪力”

在东方评论员看来，布什和小泉纯一郎这是在“一唱一和”：布什搬出了美国国会、继续“用行动”力压朝鲜无条件地让步、意在坚持要按美国的要求重启六方会谈，还进一步“搞高难度动作”、将“日本人质问题这一日本私货”正式加进了“六方会谈”；

与此同时，我们也就看到了小泉纯一郎的“投桃报李”，赶快出来帮着“敲边鼓”，“用嘴巴”“将朝鲜安排好了一个屈服者的角色”。

非常清楚，“美日”这“一唱一和”、实际上就是在给韩国实现重启“六方会谈”的努力“打横炮、使邪力”、为朝鲜半岛的缓和、稳定设置新的障碍，

显然，不论是对中国、还是韩国、或者是俄罗斯，任何一个想从朝鲜半岛经济整合中获取战略利益的一方，都得用自己的实力与决心，卸掉“美日”打来的这股“横炮与邪力”、主动去争取那份利益。

下面，是中俄联合军演的一则报道，按报道，中俄历史上首次联合军事演习将于8月18日-25日举行，整个演习的规模与层次都大大地提高了。在阅读了主要内容之后，东方时事评论员、东方军事评论员将一起继续今天的东亚部分。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com



** 中俄联合军事演习将于8月18日开始分三阶段进行




　【北京消息】中俄历史上首次联合军事演习将于8月18日-25日举行，俄方将派出王牌部队。中俄两国国防部长将前往现场观摩。

中国国家主席胡锦涛今天起程访问俄罗斯。据贡恰罗夫透露，胡锦涛将在访问期间与俄罗斯总统普京谈及军演。

双方制定相关文件

俄罗斯国防部6月28日宣布，俄罗斯和中国国防部官员将于近日签署参加今年8月在中国境内举行的“友谊-2005”联合军演的部队地位协议。

据俄罗斯国防部消息人士透露，目前俄国防部对外关系局与此前到访的中国军事代表团正在制定上述文件，这份文件将最终确立俄罗斯部队前往中国境内进行演习准备和实兵演练的法律基础，同时将规定双方参演人员数量。

俄驻华临时代办贡恰罗夫27日表示，目前两国军方保持着密切的联系，军演准备工作进展顺利，不存在任何战略或技术障碍。

对于此次联合军演，俄罗斯政府一直给予高度重视，并多次派军方高层人员来华商讨有关细节。俄罗斯总统普京更是亲自出面，督促军方加紧制定演习方案。

俄军3000我军5000

俄方来自空军、空降兵和海军的约3000名军人参加此次中俄军演，而中国方面将派出超过5000名士兵和军官参演，也就是说，参加此次中俄军演的人员将超过8000人。

俄方参演兵力兵器具体组成是：被称为王牌空降师的俄军第76空降师一个空降连的兵力、俄第55近卫海军陆战师的一个特种连、俄空军远程战略航空兵两架图-95MS战略轰炸机、四架图-22M3远程轰炸机、俄空军前线航空兵苏-27SM歼击机分队、俄运输航空兵11-14架伊尔-76运输机、俄海军太平洋舰队一艘大型登陆舰和一艘大型反潜舰。

俄先头部队熟悉地形

俄国防部资料显示，此次演习计划于8月18-25日分三个阶段举行。

首阶段将于18日~19日在远东军区境内举行，地点是海参威（符拉迪沃斯托克），主要是俄罗斯和中国军队总参谋长级别的军事、政治磋商，将最终通过双方参演兵力使用的决定。

演习的第二阶段将于20~22日在中国山东半岛和其附近黄海海域举行。

演习的主要阶段，即实弹射击演习将于23-25日举行。

消息人士指出，应中国方面请求，俄罗斯国防部长谢尔盖·伊万诺夫已决定在演习开始前10天向中国境内派出部队，此举是为了俄军部队熟悉了解中国战区和地形。




【时事点评】东方军事评论员认为，中俄联合军演选择在8月18日开始，显得非常耐人寻味。我们知道，8月15日，是日本投降日，更是中国人民抗日战争胜利60周年的纪念日，还是朝韩双方的国土光复日。

*** 这一个多月的时间，可以说是中日关系的一个关键时期

今天，有外电报道，中国海军的军舰出现在钓鱼岛周围，在东方评论员看来，如果此消息属实，那么只能说明一件事，即，北京对小泉纯一郎的新一轮敲打已经开始了。

显然，在我们看来，从现在到8月15日，这一个多月的时间，可以说是中日关系的一个关键时期。

另外，东方评论员注意到，今天，日本政府又在出尔反尔、“放风”说什么“将在7月开采石油，抗衡中国即将在8月完成的春晓油田”，显然，这里面又有一个“8月份”的时间概念在其中。

在东方评论员看来，“如此多的大事”都指向8月、这也就注定从“现在”到“8月15日”、是一个具爆炸性的时间段。


*** 如果......中日关系就将向“华盛顿期待已久”的“完全破裂”方向再靠近一步

首席评论员指出，几天前在东京举行的“第二轮中日战略对话”、不仅“没谈出结果，还不欢而散”，就是日本今天再次抛出“将在7月开采石油”的“理由”，然而，在我们看来，如果日本政府在这一期间继续“以极端的手段”挑衅中国、比如说“将7月开采石油”的“放话”加以实践的话，那么，中日关系就将向“华盛顿期待已久”的“完全破裂”方向再靠近一步，即，北京就很可能将“抗战胜利60周年纪念活动”与这次中俄联合军事演习“浑为一体”，并在这一背景下、对日本单方面的“采油行动”、以强硬的手段加以制止。


*** 是“中俄”在远东“有共同战略利益的一次公开宣示”

事实上，东方评论员认为，除了中国有“自己的打算外”，这次联合军事演习，可以说是中俄在远东“有共同战略利益的一次公开宣示”。

东方军事评论员注意到，演习重点从最初的地区反恐作战推演至抢滩登陆作战及区域远程战略轰炸，可以说涵盖了俄罗斯（反恐）、中国（台海）的现实需要，而最有意思的就是区域远程战略轰炸的科目了。

消息说，参加这次演习的，中国方面则派出5000兵力，包括战略导弹和核潜艇，而俄罗斯方面，则将出动3000官兵，并使用可用于核突击的中远程战略轰炸机图－－160、图－－95及图－－22。

对此，东方军事评论员的看法是，如果朝核问题“进一步恶化”（非常可能）时、“假设”中国或者俄罗斯、、“愿意公开地”为朝鲜提供军事保护，那么，这显然是在演习一旦朝鲜遭受一方、或几方的军事打击之后，中俄“可能”进行的军事行动和“可能的”打击方向。至于这种“可能的行动”之目标到底是台湾岛、还是朝鲜半岛、或者是日本列岛，以及是否果真会出现这样的局面、恐怕“只有天知道”了。



*** 中俄联合军演不仅“盯牢”了朝鲜形势,也兼顾了东海局势

在我们看来，一旦事情走到北京准备展示“军事强硬”这一步，那么，东方评论员认为，就说明日前北京让日本自民党前干事长带给小泉纯一郎的、“在经济上严厉打击日本”的话“就要兑现了”。

显然，在经济上严厉打击日本，是需要“先行营造舆论的”，而这一步，在中国准备、并确定纪念“抗战争胜利60周年”的纪念方式和规模的“过程”中，就可以做到。

因此，在东方评论员看来，中俄联合军演选择在8月18日开始，不仅“盯牢”了朝鲜半岛形势、也兼顾了东海局势，给了中国一个充分地发挥空间,即可见机行事，考虑是否需要在日本社会面前，营造出一幅“都与日本有领土之争”的两大军事大国、联合针对日本的“景象”、从而达到一种在军事层面“对日示强”的“强硬姿态”。


*** 任何一个国家想在东亚保持长久的影响力、首先取决于”其军事实力

东方评论员认为，就如我们在昨天的点评中所说的那样，不论是中国、俄罗斯、或者是美国，日本，任何一个国家想在东亚保持长久的影响力，都取决于其经济条件和能力，但是“首先取决于”其军事实力。

在东方评论员看来，而中俄联合军演，正是中国和俄罗斯展现各自军事实力的舞台，意在向方方面面展现各自可以“用以确保自己在东亚、东北亚战略利益”的军事实力，这自然对美国宣称的军事打击朝鲜、以及“美日”凭以捞取亚太战略利益的“美日安保指针”具有警示作用。


*** “此事早已敲定”的“强调”、是强调给谁看的呢？

另外，东方评论员认为，这次联合军事演习所透露出来的信息远不止这些。眼下，胡锦涛主席已经在与普京举行会谈了，而中国和俄罗斯在他们正式会谈前，就“正式发布”了联合军事演习的规模、地点、内容，可以说是这是在有意向国际社会“强调”，强调“此事早已敲定”、军事演习“本身”并不在两国首脑峰会的议事日程内。

只是这种“此事早已敲定”的“强调”、是强调给谁看的呢？在我们看来，“强调”的对象就是美国、这是不言而喻的。


*** 华盛顿显然相信它手里“拥有许多”扼杀朝鲜经济改革的工具

值得强调的是，从美国官方最近一个时期的立场和姿态来看，华盛顿的决策层显然相信它手里“拥有许多”可以扼杀朝鲜经济改革的工具：先在联合国安理会通过谴责朝鲜发展核武器的决议案，对朝实行经济制裁；通过防扩散安全倡议在海上加强拦截朝鲜的贸易出口；加强驻韩美军的实力并对朝鲜施展消耗对方的军事战略和谋略等等。显然，在东方评论员看来，这些都是美国新保守派早在几年前，就已经准备好了的、“原汁原味的手段”。

当然，我们必须重视的是，华盛顿手中还相信它有通过战争来扼杀朝鲜经济改革的极端手段。


*** 面对“这一展示中俄有能力维护远东共同战略利益的强烈信号”，美日“都要严肃对待才是”


然而，从演习地域“跨越中俄两国”的演习规模，中俄两国防部长都将亲临前线督战的指挥规格，特别是中俄双方都将动用了各自的战略常规及核打击力量的演习层次来看，面对“这一展示中俄有能力维护远东共同战略利益的强烈信号”，只怕方方面面，特别是美国和日本、“都要严肃对待才是”：那就是，上述那些“原汁原味的手段”、恐怕没有一条“能打开局面的”。

*** 要尽可能地“坚定”卢武铉“继续走下去的决心”

不过，东方评论员认为，这里面的关键因素是韩国的态度取向。今天，布什已经在借美国国会的力量、来“拂”卢武铉的“脸面”了，在我们看来，这一方面说明布什仍然强硬，显然，从美国共和党控制的参众两院选择在美朝“六方会谈”代表在华盛顿“开会”的时候、才“通过”该议案的事实来看，布什政府有意以此向“六方会谈”的其它成员国“宣示”华盛顿“绝不妥协的立场”。

而另一方面，也说明布什在阻止卢武铉出于民族、国家利益、与中俄合作、搞东北亚经济一体化的问题上，已经有点儿“黔驴技穷”了。在我们看来，如果华盛顿在朝核问题上“继续强硬”，并以实际动作干扰韩国与朝鲜进行经济合作的计划，那么，中俄搞这种大规模的联合军事演习、展现共同维护朝鲜半岛和平稳定、为东北亚经济一体化提供安全保障的“决心与实力”，就特别具有战略意义，既，它可以起到尽可能地“坚定”卢武铉“继续走下去的决心”的作用。


*** 再次强调我们的一个观点

总之，在东方评论员看来，就如我们在昨天所说的那样，此次军事演习固然有警告美日“介入台海企图心”之目的，但是，最主要的恐怕是以“中俄”的强大军事实力、为周围国家都需要的朝鲜半岛的和平与稳定进行“保驾护航”、一来是支持朝鲜在重返“六方会谈”的时候，“大胆地坚持合理的要求”，二来，也是为韩国能顶住美国的压力、着手进行的朝鲜半岛经济整合“提供必要条件”。

下面，东方评论员的关注焦点将转向中亚。在一则有关胡锦涛主席访俄的消息之后，我们将开始今天的中亚部分。


《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
