# -*- org -*-

# Time-stamp: <2011-08-04 13:19:15 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

#+STARTUP: indent

* 2005年4月22日 星期五

下面让我们目光从台湾海峡转向印尼亚加达。首先，是一则报道小泉纯一郎道歉的消息。在东方评论员看来，小泉终于低头了，这是好事，然而，只要我们看看小泉纯一郎的“道歉场合”和“道歉形式”，就不难看出，小泉纯一郎根本就在那里“口服心不服”。我们还是先来看看这段新闻，然而，再给出我们的观点。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 小泉发表演说对日战争罪行表示反省和道歉

【印尼亚加达消息】据报道，22日，小泉首相在亚非会议（万隆会议）50周年纪念首脑会议上发表演说。首先，他谈到了历史认识问题，引用战后50年（1995年）时任日本首相村山富市发表的“村山谈话”中对于过去殖民统治和侵略“深刻反省和发自内心的道歉”，强调今后日本也将继续走“和平国家”的路线。

此外，小泉首相还表示，为加强亚洲、非洲地区的合作伙伴关系，日本将增加政府开发援助（ODA）额度等，积极实施经济援助。

分析认为，今年是二战结束60周年，小泉试图通过强调“为世界和平和繁荣做出贡献的决心”和树立“和平国家”的形象，避开中韩对小泉参拜靖国神社和历史教科书审核问题的批判。


【时事点评】在东方评论员看来，小泉纯一郎是在他的外相带着自己的亲笔信求见温总理“不果”的尴尬下、承受着日本国内指责他为在改善日本与中国、韩国关系上“不作为”的巨大压力忽然“又一次”想起了这个十年前发表的“村山谈话”的、说得再清楚些、小泉是在北京摆出不再“单方面”顾及中日关系何去何从的重大压力下、不得不道歉的。既然“道歉”是被迫的，那当然不会是“口服心服”的了，事实也正是如此，在我们看来，从小泉今天的道歉的整个过程来看，其“口服心不服”的细节是贯穿始终。

*** 小泉今天的所做所为，似乎“仍然”是在让我们“似曾相识”

首先，在东方评论员看来，小泉纯一郎今天的所做所为，似乎仍然是在让我们“似曾相识”，请大家注意这么几点，第一，小泉纯一郎又将前首相村山富市发表的“村山谈话”给掏了出来，在前天的点评中，我们就曾经对小泉“再次想起”这个“村山谈话”之“实质”做过分析（详细内容见4月20日的《东方环球时事解读》）。

显然，小泉纯一郎在这里尽管是在“道歉”，但是，他所用的的伎俩是“一如既往”：东方评论员认为，小泉这次“再次不顾”日本前首相村山怒斥他将“‘村山讲话’变成表面文章，真是可耻”的指责、又一次将“村山谈话”当成了“历史问题已经解决”的“挡箭牌”。

*** 在日本这个“问题国家”里，对历史问题的认识仍然是个“非常大的问题”

我们要注意的第二点是，小泉纯一郎在表示“道歉”时的“遣词用字”上、显然也展现了“口服心不服”的心态。我们知道，日本人表示歉意时，“谢罪”这两字是最强烈的，然而，小泉纯一郎既然“没有谢罪的心态”，自然不会有“谢罪”的表态了。

很清楚，他用的仍然是“道歉”这个词，事实上，日方已多次为战争进行过所谓的“道歉”、但就是一直回避用“谢罪”这个词，包括所谓的、有“和平宣言”之称的“村山谈话”、也都是如此。显然，在东方评论员看来，在日本这个“问题国家”里、日本社会对历史问题的认识仍然是个“非常大的问题”，这个问题也“从来就不曾”真正解决过。

*** 小泉又一次发挥了他从来不缺的“小聪明”，将“道歉”也“世界化”了

第三，我们还应该注意的是，小泉纯一郎主要是在中国的强大压力下“道歉”的，然而，这个对中国“一肚子怨气”的日本首相，看来又一次发挥了他从来不缺的“小聪明”。

不是吗？我们就看看小泉纯一郎是如何又“心生一计”的：中国不是要他道歉吗？中国和韩国不是将历史问题国际化了吗？那好，“这些话”他就是不单独面对中国和韩国说，他就要表演一把，把“道歉”也“世界化”、将“道歉的舞台”搬到“亚非峰会”这个国际场合上、去向国际社会道歉。

*** 是针对中韩将“日本历史问题国际化”的一个报复

在我们看来，小泉纯一郎这种“小聪明”虽然是针对中韩将“日本历史问题国际化”的一个报复，真实意图是“想在世界面前堵住中、韩两国的嘴”，然而，就如我们之前一再所说的那样，几年的事实已经充分地证明，小泉的“自作聪明”最后总是难逃“自取其辱”的结局，在日本国内如此，在国际上也是如此。

在日本国内，前面说了，他为了参拜靖国神社找理由，投机取巧、偷梁换柱地盗用“村山谈话”、被村山斥之为“真是可耻”。

*** 几年的时间证明，小泉政府总是“聪明反被聪明误”

而在国际上，他想与“德、印、巴西”结伙、以此壮胆、去挑畔中国、“玩”强行“申常”，却被中、韩瞧准时机、一把将他的政府“钉在了”国际社会这个大舞台上、在世界范围内掀起一股“深刻揭露”日本罪恶历史、“帮助”、“教导”日本反省这段历史的“运动”，从而让那些与日本“结伙申常”的国家“大叹受日本的拖累”、“与日本这种不愿意正视其法西斯历史的国家结伙入常不明智”，显然，我们在国际上看到的仍然是小泉政府的“聪明反被聪明误”。

这一次，既然小泉纯一郎又玩“小聪明”，当然，中韩等国又怎么会让他就此轻易过关？下面，我们就先来看看中国的相关反应，之后，东方评论员将回到这个话题。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 小泉为侵略“道歉”　李肇星：没听见

【印尼亚加达消息】日本首相小泉纯一郎在印度尼西亚出席亚非高峰会时，再度为过去日军侵略亚洲道歉，不过，中国对此似乎摆出高姿态，外长李肇星以正在与他国代表谈话，没听到小泉的说法为由，不愿意正面评论。

小泉纯一郎在亚非高峰会的致词时，以前首相村山富市1995年的谈话为基调，表示日本对於过去在亚洲各国的殖民侵略行为，所造成的损失与痛苦，表示深切痛悔和反省。他说，「日本以谦卑的心正视历史事实，深切懊悔并由衷道歉。」

不过小泉的致歉似乎打动不了北京当局。人在会场的中国外长李肇星被问及对小泉道歉的看法时，说「我没听到，我刚才和象牙海岸外交部长有非常友好的会谈。」不过李肇星呼吁两国以史为鉴，面对未来；他也重申，各国外长都支持一个中国政策以及订立反国家分裂法，坚决反对台独。

在此同时，小泉表示，他将在23日与中国国家主席胡锦涛会晤。他是在回答记者问及是否会与胡锦涛双边会时说，「我获知的是，我们将在明天举行。官员还在安排会面时间。」小泉希望藉亚非高峰会的机会，与大陆国家主席胡锦涛会面，协商化解近日中国反日情绪，舒缓两国紧绷关系。小泉在前往印度尼西亚途中，向随行记者表示，「仇视不会有任何结果。友谊是最重要的，我会以这个观点来谈。」


【时事点评】说实在的，在得知小泉表示道歉时、就在会场坐着的李外长竟然“没听见”时，时事评论员们都觉得“非常搞笑”。我们注意到，李外长解释他“没有听到”的理由是“我刚才和象牙海岸外交部长有非常友好的会谈”。

*** 北京这次“逼小泉道歉的目的”非常清楚

由此可见，不论李外长是“真没听见、还是在那里有意暗示小泉道歉“不值一听””、东方评论员是“无从得知”。但是，事实上，北京这次逼小泉道歉的目的非常清楚，那就是要日本政府正式表态，选择中日关系“何去何从”，因此，尽管小泉纯一郎的道歉是一副“心不甘、情不愿”的样子，作为中国的外交部长，李外长显然以一句“两国以史为鉴，面对未来”、表示了中国的高姿态、向国际社会、于第一时间内传送了在小泉“道歉”、并表示“要走和平国家路线”之后、中日关系“最应该走的道路”是什么。

*** “暂时维持住”了中日关系

显然，不论是小泉在道歉时表态要“走和平国家路线”也好，还是李外长强调的“两国以史为鉴，面对未来”、都是个“抽象”的东西，因此，如何将这个”抽象的东西“具体化才是最重要的。

东方评论员认为，日本的道歉听得太多了，日本所做的承诺也太多了，就如李外长在北京当着日本外相町村信孝所下的结论那样“日本政府已经失信于中国人民”，因此，“道歉”只是暂时解决了个“表面态度”问题、暂时打击了日本右翼的嚣张气焰，“暂时维持住”了中日关系。

*** 小泉被迫道歉的一个重要意义就在于，日本保守势力“不敢对美国保守主义托付终身”

另外，在东方评论员看来，小泉纯一郎的被迫道歉的一个重要意义就在于，它表明“美日军事同盟”并非什么铁板一块，这一结果让华盛顿保守势力再次看到，尽管它想一把就控制住日本、但日本保守势力尽管反华、但也“还不敢就此与中国决裂、而对美国保守主义托付终身”。

显然，美日之间的心怀鬼胎、并然沉重打击了台独势力的依靠“美日军事同盟”军事抗统的嚣张气焰。除了上面的这些之外，小泉纯一郎的道歉并没有什么太大意思，因为，这种道歉不过是小泉的权宜之计：首先，由于承受国内的巨大压力，他还是得想办法见到胡锦涛主席。而为达此目的，在日本，他就再次抛出了“村山谈话”，结果，北京方面的反应仍然是“不置可否”，这次公开“道歉”之后，据说中国外交部仍然“在研究研究”，仍然没有肯定的结果。

第二，小泉纯一郎在用这种公开“道歉”堵中、韩的嘴，其算盘当然是“以空间换时间”，暂时度过“这一劫”，用“公开道歉”重启“入常进程”。


*** 中国更是已经准备好了一件日本必须“立刻去努力”的具体事情


然而，在东方评论员看来，关键是日本在今后得拿出具体行动来落实“走和平国家路线”的承诺，事实上，对今天小泉纯一郎的“道歉”、中国外交部肯定是早有预案、而对小泉纯一郎的“不情不愿”表示“要走和平国家路线”，中国似乎更是已经准备好了一件必须日本“立刻就去努力”具体事情、去针对小泉纯一郎的“权宜之计”。

下面，我们就先来看看这件“应该立刻就做的事情”、究竟是件什么事情？

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 孔泉称东海争议应通过磋商解决

【印尼亚加达消息】中国外交部发言人孔泉表示，东海争议应该透过磋商来解决。日本不应该采取单方面的行动，东海共同开发的问题，应该从政府层面开始


【时事点评】显然，就如之前《东方时事解读》中所点评的那样，此次中国在北京不给日本外相“一点面子”，虽然是小泉政府几年下来、对中日关系“破坏”的一个“总爆发”，其中、日本公然要借“美日军事同盟”染指台湾、为其侵略历史翻案、等等都是重要原因，然而，细究起来，“最直接的导火索”就是孔泉所说的“东海争议”。

*** 中国决定不再去单方面努力维护中日关系的“转折点”

显然，日本政府于在4月13日强硬地宣布“日本政府开始为民间企业办理有关申请东海油气田勘探权的手续”、其中，日本经济产业省当日甚至给日本九州经产局发出指示，“要求尽可能快地处理由民间企业提出的有关在东海从事油气田勘探的申请”之后、是中国决定不再去单方面努力维护中日关系的“转折点”。

我们知道，日本最近一系列挑畔行动中、以小泉政府不顾中国政府的严正警告、单方面宣布向日本企业发放东海资源勘探许可证这件事最为严重，就如国务委员唐家旋所警告日本所说的那样，一旦日本政府果真这样做了，日本企业人员、设备出现在中国认为具有主权的领海上，那么“问题的性质就变了”。

在昨天的点评中，我们也再次就这个“性质变了”做过解读，在东方评论员看来，这句话的意思可以理解为“中日关系将处于公开对立的状态”，东方评论员认为，中国政府表示，日本的决定“是对中方权益和国际关系准则的严重挑衅、并保留作出进一步反应的权利”、不难看出，这句话“是有实质内容的”，事实上，日本外相就是在这种背景下“带着任务”、“揣着小泉的信”来到北京的。

*** 验证了我们的一个观点：气势汹汹的町村信孝在北京“跳得越高”，小泉政府就“越加难看”

现在，中日间是几经交锋，结果就如我们之前所说的那样，气势汹汹的町村信孝又是提抗议、又是要求中国道歉、还专程去日本驻华使馆“收集证据”，然而他这次到北京来“强硬的不是时候”，他在北京“跳得越高”，其结果必然是让日本政府“越加难看”。


*** 既然“东海争端”是一个转折点，那么，北京的态度也就“非常现实”

现在、四面楚歌的小泉纯一郎终于“盯不住了”，不得已做出了所谓的“道歉”，然而总是这么“空口白牙”是没有什么意思的、既然“东海争端”是一个转折点，是日本挑畔中国的“高潮部分”，那么，北京的态度也就“非常非常的现实”，既然日本本来就没有城意道歉、自然也“用不着去计较”小泉纯一郎的“没有城意”，而只要“敦促”小泉纯一郎“拿出实际行动去道歉”就足已，不是吗？我们就认为，“说得百遍不如去做一件”。

在东方评论员看来，孔泉在这个时候立刻提出“东海争议应该透过磋商来解决、日本不应该采取单方面的行动，东海共同开发的问题，应该从政府层面开始”这个建议，事实上是北京“强硬态度的继续”、是对日本这种类型的道歉不满的最好“回击”。

*** 孔泉笑眯眯“不经意”吐出的这个建议，才是“最让小泉难受”的地方

我们的观点是，孔泉在那笑眯眯的表情下、“不经意”吐出的这个建议，才是“最让小泉纯一郎难受”的地方。显然，如果接受孔泉的建议，那么，日本政府就“必须立刻停止”在领土问题上、挑畔中国、韩国，要么接受中国的建议“搁置争议、共同开发”、要么就象之前那样，眼睁睁地看着中国自己在东海继续开发。

很清楚，这样一来，小泉纯一郎绝对在国内无法向他一直依靠、并纵容的日本右翼势力“好好交待”。

然而，如果他不接受，那么，也很清楚，他好不容易下决心做的这个“道歉”，不仅不能帮日本解决任何问题，还可能对日本的“大国梦”引发两个长期的麻烦：首席评论员认为，这两个麻烦可以说是“一外一内”。

*** 很可能会出现一个“没完没了”的问题

对日本而言，小泉纯一郎此次“道歉”封堵中国、韩国、甚至是国际社会的嘴的意图非常清楚，那么、中国、韩国就有必要以各种方式、比如战争赔偿、教科书问题、日军在华遗留毒气弹处理问题、韩国一再引起民愤的“慰安妇”问题等等、一切可以与日本“没有清算历史”挂上钩的事情，都可以“一而再、再而三”地，就象这次将“日本历史问题国际化”所做的一样，以国际社会对德国法西斯的完整清算的标准、去“不断提及”、以敦促日本“按国际标准”进行反省和清算，除非日本真诚地反省历史，不然，在东方评论员看来，这将是一个“没完没了”的问题。

*** 在日本“是否应该接受国际组织更严格的检查”的问题上，中韩应该有能力去做点什么

在国际上，日本也可能面对国际社会另一波“针对日本形象和地位”的国际“大声讨”。在昨天的点评中，我们已经提到了这个可能性，那就是朝核问题由“美国的定义”向朝鲜暗示的方向、进行“扩大化”问题，在东方评论员看来，朝鲜已经公开表示了朝核问题有必要包括美国驻韩的核武器问题、也包括根除韩国的核武能力问题，可就是偏偏不提这个“让朝鲜痛恨的”日本的名字，这是金正日有意对小泉纯一郎在“网开一面”吗？

在东方评论员看来，恐怕没有谁去这样认为，这样，日本的“核武能力”在日本拒不认错、不清算历史问题的情况下，与德国法西斯有着一样罪恶历史的日本、竟然企图制造大规模杀伤性武器、这“是否应该接受国际组织更严格的检查”？在东方评论员看来，在国际化日本历史问题已经有了经验的中国和韩国，在这方面“应该有能力”去做点什么。

*** 华盛顿到时不给日本下份“乱药”、就算是日本“烧了高香”

要知道，在解除日本核武能力的问题上，华盛顿的立场是“非常微妙的”，在这方面，华盛顿不给日本下一份“乱药”、都可算是日本“烧了高香”，日本是指不上美国“城心地帮着说话的”。这一点，在美国支持日本“入常”的“出尔反尔”的问题上，在“默许”国民党、亲民党主席到大陆访问的问题上，可以说华盛顿长期以来、一直奉行着的“严控日本”、并只顾自己利益、“根本就不顾及日本这个盟友的感受”之立场是“一览无遗”，这本身就是昨天、和日本高层一直“互通有无”的李登辉突然“提前24小时”跳出来“哀叹”一番的根本原因：因为他的日本主子在这场较量中、可以就是脸面扫地。

下面，是日本国内的一则报道，说的是日本80名国会议员集体参拜靖国神社的事情，事实上，在东方评论员看来，日本右翼尽可这样做，“好得很”，他们这样做当然是在向国际社会“示威”、然而，这也正为我们上面提及的一些“可能性”提供了充足的炮弹。在一起了解了这些日本右翼今天的“所做所为”之后，时事评论员将继续谈小泉“低头”之后的事态发展。
《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
