# -*- org -*-

# Time-stamp: <2011-08-04 13:11:36 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 2005年8月30日 星期二




** 中国将隆重纪念抗战胜利六十周年




【北京消息】2005年8月30日上午10时，国务院新闻办公室星期二举行记者会，介绍纪念中国人民抗日战争暨世界反法西斯战争胜利60周年一系列重大活动的举办情况。

据介绍，中国人民抗日战争暨世界反法西斯战争胜利60周年重要纪念活动有五场，即9月2日至3日将举行的文艺晚会，向人民英雄纪念碑敬献花篮，中央领导同志为部分抗战老战士、爱国人士、抗日将领代表颁发纪念章，纪念大会和招待会。

国家主席胡锦涛还将在人民大会堂会见抗战老战士和参与过中国抗战的国际友人，并为他们颁发奖章。中国政府共邀请了上千名参加过抗日战争的老战士，老同志，国际友人和他们的后代前来参加此次纪念活动。另外，负责接待传媒的纪念活动新闻中心，将于9月1日开始对外开放。

在会上，中台办副主任王在希则在回答记者提问时肯定了国民党军队在抗日战争中的重要作用。他还表示，中国抗日战争的胜利，是包括台湾同胞在内的全体中华儿女共同抗击日本侵略者的伟大胜利。

另外，中国人民对外友好协会会长陈昊苏在记者会上表示，中国坚持以和平、发展和合作的旗帜处理国际事务，愿意在以史为鉴这样一个共识的前提下，和日本发展长期友好合作的关系。

纪念抗战胜利五场重要活动

国新办副主任王国庆在记者会上表示，中国人民抗日战争暨世界反法西斯战争胜利60周年重要纪念活动有五场，即9月2日至3日将举行的文艺晚会，向人民英雄纪念碑敬献花篮，中央领导同志为部分抗战老战士、爱国人士、抗日将领代表颁发纪念章，纪念大会和招待会。

第一场是文艺晚会。定于9月2日晚7：45在人民大会堂大礼堂举行，参加人员包括党和国家领导人及各界代表6000人。第二场是向人民英雄纪念碑敬献花篮。定于9月3日上午9时在天安门广场举行，参加人员包括党和国家领导人及各界代表1万人。第三场是中央领导同志为部分抗战老战士、爱国人士、抗日将领代表颁发纪念章。定于9月3日上午敬献花篮结束后，约9：30在人民大会堂湖南厅，由国家主席胡锦涛向抗战老战士、海内外爱国人士和抗日将领代表颁发纪念章。第四场是纪念大会。定于9月3日上午10时在人民大会堂大礼堂举行，参加人员包括党和国家领导人及各界代表6000人。第五场是招待会。定于9月3日晚6时在人民大会堂宴会厅举行，参加人员包括党和国家领导人及各界代表约2100人左右。

以上五场重要纪念活动是整个纪念活动的重头戏。此外，还有其他一些纪念活动。一是学术研讨会。学术研讨会定于9月2日至4日在京西宾馆召开。二是大型主题展览。已于7月7日在中国人民抗日战争纪念馆隆重开幕，中央政治局常委参观了展览。李长春、刘云山、陈至立等党和国家领导人出席了开幕式。

还有两个进京展览和香港举办的展览：第一个是“太行精神光耀千秋”展，已于7月1日至15日在北京展出，后在重庆、长沙、哈尔滨等地巡展。第二个是8月9日在国家博物馆开幕的南京大屠杀史料展。第三个是国家博物馆、香港《大公报》等六家单位8月10日开始在香港联合举办的展览。三是海内外爱国人士、抗日将领或其遗属纪念中国人民抗日战争胜利60周年座谈会。座谈会定于9月3日下午4时在人民大会堂东大厅举行。四是群众性抗战歌曲大联唱活动，由中国文联和中央电视台主办“爱我中华--抗战歌曲大联唱”。8月14日演出，8月15日曾在中央电视台黄金时段播出。

另外，还制作了纪念册，组织展映、展播和出版一批优秀文艺作品。

纪念抗战并非进行反日教育

中国人民对外友好协会会长陈昊苏在记者会上表示，中国坚持以和平、发展和合作的旗帜处理国际事务，愿意在以史为鉴这样一个共识的前提下，和日本发展长期友好合作的关系。中国领导人反复强调，要一心一意搞建设、全心全意谋发展。中国人民建设好自己的国家，也就是为世界和平作出了应有的贡献。

王国庆也表示，不能说因为中国现在存在着一些问题，就不去纪念中国人民为此作出了重大牺牲而取得的，也是中国近百年来让中国人民最自豪的一个胜利，那也是没道理的。

他表示，中国是以伟大的爱国主义精神来纪念我们的胜利，而不是以狭隘的民族主义来看待那场战争的。


【时事点评】东方评论员认为，按国新办副主任王国庆在记者会上的介绍，这次中国人民抗日战争暨世界反法西斯战争胜利60周年重要纪念活动有五场，即9月2日至3日将举行的文艺晚会，向人民英雄纪念碑敬献花篮，中央领导同志为部分抗战老战士、爱国人士、抗日将领代表颁发纪念章，纪念大会和招待会。

*** 北京隆重纪念抗日战争胜利60周年“另一个重要因素”

显然，相比以往的纪念形式，抗战胜利“一个甲子”的纪念活动显得隆重得多。在我们看来，这其中自然有世界反法西斯胜利60周年、中国人民抗日战争胜利60周年的因素、但是，中日关系在建立外交关系后的空前恶化、无疑是北京隆重纪念抗日战争胜利60周年“另一个重要因素”。

在我们继续展开讨论之前，先来看看日本保守势力的最新动态。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 小泉纯一郎暗示在大选获胜后将去参拜靖国神社




【东京消息】日本首相小泉纯一郎昨日暗示，在9月11日的众议院大选结束后，如果他能继续担任首相，将会不顾中韩等国的反对，前往参拜靖国神社。

“适当判断”参拜时间

今天，日本第44届众议院选举正式拉开战幕，各党将公布选举告示。昨天，作为自民党总裁的小泉和其他5名主要政党的党首举行了大选前的唯一党首辩论，并作出上述表态。

当被问及今年是否计划前往参拜靖国神社时，小泉说：“看看我以前做过的事情，你就会知道我会采取什么样的行动。单凭我们放弃参拜靖国神社，我不认为我们同中国的关系就会融洽。”但小泉不愿表明他前往参拜的确切日期，只是重申自己会作出“适当的判断”。

关于已经中断多时的日中首脑互访问题，小泉称：“每年都在国际会议的场合堂堂正正地举行会谈。”他还补充道，近些年来，中日两国在经济文化关系方面一直在改善。

不过，与自民党联合执政的公明党代表神崎武法明确表示：“在这个问题上我和首相的看法不能苟同。作为首相不应该参拜靖国神社。各邻国都很讨厌。”

由于邮政民营法案8月8日在参院未获通过，因此小泉当天宣布解散众院进行改眩此次大选目前共1086人登记参选，角逐480个席位。而自民党与最大在野党民主党将在总共300个小选区中的280个展开角逐，竞争相当激烈。



【时事点评】之前，我们一直强调，眼下对小泉纯一郎而言，压倒一切的“要务”不是中日、日韩关系、也不是美日关系、而是赢得“9月11日”的议会大选。

*** 在日本选举结束之前、小泉的“所做所为”如何才能“看清楚、说明白”？

因此，在东方评论员看来，在日本选举结束之前、小泉纯一郎的“所做所为”只能立足于“捞取选票”的角度、才能“看清楚、说明白”。

事实上，值得强调的是，今天，日本第44届众议院选举才算是“正式拉开战幕”，为此，作为自民党总裁的小泉纯一郎与其他5名主要政党的党首、在昨天特别安排举行了大选前的“唯一的一次”党首辩论，而小泉这番“一旦大选获胜将继续参拜靖国神社”的“暗示”、就是在“辩论”的现场“一吐为快”的。

在东方评论员看来，自小泉纯一郎因邮政民营法案8月8日在参院未获通过，而于当天宣布解散众院进行改选、置自民党的分裂于不顾、拿自民党的前途做赌注、进行他个人政治生命的豪赌以来，这次“选举行情”可以说是变幻无常。


*** 一个让几乎所有观察家都“大跌眼镜”的现象

首先，在小泉纯一郎宣布宣布解散众院进行改选之后、日本社会出现了一个让几乎所有观察家都“大跌眼镜”的现象：小泉纯一郎的支持是“不降反升”：自8月8日小泉解散国会、到8月15日之前，短短一个星期的时间里、小泉任总裁的自民党、其支持率就“突升”至近50%，这不仅让“背水一搏”的小泉纯一郎欣喜不已、就是那个因“担心毁了自民党”而捏着几罐啤酒、亲自登门劝说小泉“不要解散国会”未果、气愤地当着记者的面一边将啤酒罐捏瘪、一边痛斥“小泉是变人（怪人）”的日本前首相、自民党森喜朗派的派头森喜朗也表现得“欣喜不已”：我们注意到，面对飙升的支持率、森喜朗已经有意摈弃前嫌、并开始公开地对小泉这个“森喜朗派”赢得大选“表示出乐观”了。


*** 当时已经“里外不是人”的小泉显然明白这么一个道理

也正是在这种乐观气氛下、在东方评论员看来，在自民党已经分裂、而中日、韩日关系也已经接近冰点的情况下，当时已经“里外不是人”的小泉显然明白这么一个道理：只要能将这种支持率一直保持到9月11日，那么，在继2003年解散国会“赌赢”头一把之后、这次也必然会“旧梦重温”。



*** 小泉再现“变人”的本色、于8月15日来了个“突然变脸”


事实上，也正是为了千方百计地保住这个“接近一半”的支持率，视“赢得大选”为头等大事的小泉纯一郎、在8月15日、即日本投降日、在日本右翼企盼他能兑现几年前上台时许下的、“在8月15日参拜靖国神社”的诺言之际，在国际社会猜测“他会为了赢得大选”而不惜在东海做政治与军事冒险的时候，这个被日本社会广泛称之谓“变人”的怪人、是再现“变人”的本色、于最后关头来了个“突然变脸”，以“不想让日本人社会分裂”为由、并没有将他自己的所谓“个人信念”“当回事”：他不仅没敢“冒天下之大不韪”在“日本投降日”兑现诺言、正式参拜靖国神社、也没敢在东海油气田问题上进行军事冒险、进一步挑衅北京。


*** 对北京的强硬言行、国际战略观察人士“得出了一个近乎统一的结论”

在东方评论员看来，促使自视为“说话算数”的小泉、最后将自己“坚守”的“个人信念”抛在一边的众多因素中、北京在军事上的“极其强硬”、显然起到了核心作用：众所周知、就在那之前不久，北京甚至声称不惜动用核武器打击日本的保护国--美国、在东方评论员看来，这种“不惜核战”“战争言行”、“针对的”是华盛顿一家、但“连带着”日本和台独的神经。

据我们观察，国际战略观察人士“得出了一个近乎统一的结论”，那就是、北京此举显然极大地压制了日本保守势力企图仗着华盛顿提供的核保护伞、在东海、钓鱼岛方向进行军事冒险、以进一步测试北京战略决心的企图心。


*** 让小泉纯一郎“说话不算数”的另一个重要因素

同时，东方评论员也认为，让小泉纯一郎“说话不算数”的另一个重要因素、就是在他解散国会后、其支持率是“意外的大幅上升”、而且可称之为是种“飙升”、这使得本想利用日本社会支持邮政改革的民意、同反对他的政治势力“豪赌一把”的小泉纯一郎、再次看到了延伸其个人政治生命的契机。

相比之下、先前小泉纯一郎所嘴中吐出的那句、让小泉所在的自民党森喜朗派的“派头”-日本前首相森喜朗“感到无比愤怒”的“让反对我的人和我一起完蛋”的报复心理、反而突然就变得无影无踪了。

在我们看来，正是这种“意外的飙升”所带来的契机、不仅让小泉纯一郎抛弃了“8月15日参拜靖国神社”的诺言、而且在东海问题上频频放出所谓的“善意”。


*** 自“8月15日日本投降日”这天算起，“变人”再次让人深刻地感受到其“乖张无常”

显然，这一切的变化似乎都与“8月15日”这天有关。东方评论员认为，自“8月15日日本投降日”这天算起，素有“变人”之称的小泉、在内政外交上、再次让人深刻地感受到其行为举止的“乖张无常”。

根据我们的观察，“变人”变出的第一张脸就在8月15日这天、在日本举行的二战结束60周年纪念活动上，这位“变人”首相是再次进行反省，并再次发表了一份与“村山讲话”类似的讲话。而所谓的“村山谈话”是在1995年，日本纪念战后50周年时，日本前任首相村山富市的在历史问题上的一个谈话，村山当时表示“对于过去的殖民地统治和侵略造成的巨大损害和痛苦的历史事实诚恳接受，痛切反省和道歉。”



*** 小泉何以在8月15日“率先变脸”？

事实上、在靖国神社问题上、或者是在这个阻碍中日关系正常化的“症结”问题上、对小泉纯一郎的“率先变脸”，我们当时就有点评。在东方评论员看来，由于小泉纯一郎再次对“村山讲话”进行了一番精心地“剥皮抽筋”，其意图就是在“刻意”向日本国内“展示”他在参拜靖国神社上“已经注意到了”日本社会的“反对态度”。

显然，参拜靖国神社“已经断送了”日本同亚洲国家、特别是中、韩两国的外交关系、因此、在中国通过提前招回正在访日的副总理吴仪、而将中日关系“一推就倒”的严重事实摆在日本社会的眼前之后，我们注意到，反对小泉参拜靖国神社的声音可以说也经历了一个“飙升”的过程、直到“占了近乎一半”的民意。

不难看出，小泉的“变脸”是基于尽一切手段维护自8月8日到8月14日已经飙升的“支持率”、这也是小泉政府在“9月11日大选前”这段时间中“压倒一切的现实考虑”。


*** 日本从政府到企业、在5天左右完成的一套“变脸术”

也正是在这一“统筹安排下”，我们也就看到小泉内阁中、在8月14日公然以内阁臣身份参拜靖国神社的、在东海油气田问题上态度最为强硬的、声称“在目前情况下、绝不会考虑与中国共同开发的”日本经济产业大臣中川昭一、也突然“变脸”，在小泉“真诚的道歉”后、就立刻对新闻界“改称”：“我并未排除进行共同开发的可能性。”

这还不是全部，与此同时，在东海中日争端中扮演重要角色的日本帝国石油公司、这家早在7月14日就从日本经济产业省正式拿到“在东海中国专属经济区的天然气田试开采权”的日本企业，也跑出来积极配合，抱怨“由于存在安全问题，该公司不可能很快在东海海域进行油气试钻探”。


*** 小泉政府“变脸”的意图是非常功利的

在东方评论员看来，日本从政府到企业、完成这一套、旨在对内缓和日本社会对立、对外制造日本有意协商双边关系之假象的“变脸术”、其时间段大致是8月15日到8月20日的5天时间。

种种迹象表明，其“变脸”的意图是非常功利的，在这一点上，就如我们之前多次强调的那样：小泉纯一郎的这种对内、对外的“暂时性让步”更多地是种策略，其中，一个主要考虑就是9月份的大选。

就是为了在靖国神社问题上“暂时避免”刺激反对他参拜的国内民意、也“暂时卸掉”中、韩等国从外部策应日本国内反对自民党的政治势力、在历史问题上向他继续施加压力的借口、从而最限度的稳住“这份意外的支持率”。

*** 小泉任总裁的自民党人气开始下滑

然而，也就是从8月21日之后，小泉纯一郎意料之外得到的“支持率”、再次给人一个意外：由于反对小泉纯一郎的政治势力、特别是日本民主党提出“养老金问题”的战略开始逐渐奏效，小泉任总裁的自民党的人气开始下滑，按日本共同社在8月27日、28日进行的全国电话民意调查显示，自民党支持率为29.7%，民主党为18.3%，这同7天前的调查结果—自民党31.5%、民主党15.2%相比，差距缩小了近5%。

对小泉阵营最不利的是，第一次有超过40%的人认定、“小泉以这种近乎悲壮的形式推动的邮政改革问题”并不是此次大选中最紧要的问题、相反，日本民主党人、包括被小泉纯一郎清除出自民党的、在邮政法案问题上投反对票的“原自民党人”、所大力宣传的“年金、医疗等社会保障政策”，才是此次大选中最紧要的问题，值得注意的是，持这种观点的人，比8月20日时、是足足增加了“6.4%”。


*** 日本社会“总体上”在右倾

在东方评论员看来，8月21日，可以说是小泉纯一郎通过在8月8日宣布解散国会、树立起来的一副“勇敢地推进邮政改革、勇敢地打碎自民党的光辉形象”开始走向暗淡的开始，我们认为，在内政上“开始失分”，显然再次刺激了小泉纯一郎当前“唯选票是从”的“政治赌徒”之心理。

在之前的点评中，东方评论员曾经说过，由于邮政系统改革总体上对日本经济是有利的、因此，尽管当前有半数日本民众反对小泉参拜靖国神社、但是小泉纯一郎的支持率却仍然是一度能够摆脱中日、韩日关系的冲击、以及靖国神社问题的影响、而出现一种“攀升”的势头。

对日本社会这种一边担心日本外交关系走上绝路、从而反对小泉参拜靖国神社、一边又将“支持率”给了小泉、这一“说怪也不怪”的现象，东方评论员的观点就是：这已经“非常充分地证明了”日本社会“总体上”在右倾、对小泉纯一郎的错误历史观“并不以为然”，也充分地说明了日本社会更看重日本的经济问题、而不是什么对外关系问题、也充分地说明了日本社会更关注的是与自己切身经济利益相关的民生问题、而不是什么“道德、良知”问题。


*** “成也萧何、败也萧何”

中国有句老话、喻之为“成也萧何、败也萧何”。在东方评论员看来，在小泉纯一郎成功地利用自己“壮士断腕”所推动的“邮政系统改革对日本经济是有利的”这一令人同情的改革者形象、和“抽象的经济利益”、赚取了大量支持率之后、却又在反对势力推出“更加具体”、且“更加利民”的经济改革政策的挤压下，正被慢慢地挤回“原形”。


*** 在“表演”问题上，小泉与陈水扁非常类似

首席评论员指出，过去几年的事实表明，小泉政府可谓是个典型的“表演政权”，其“表演伎俩”与陈水扁的“台独”政权非常类似，即，每当支持率往下掉的时候，为了提高气，他就会设法安排一些政治活动来提高支持率。


*** 在咀嚼“慢慢挤回原形”的痛苦与害怕中、小泉纯一郎终于再一次“变脸”

在我们看来，正是在咀嚼“慢慢挤回原形”的痛苦与害怕中、小泉纯一郎终于再一次“变脸”，在我们看来，小泉纯一郎的那张脸可以说已经变得非常清楚了：请大家注意新闻中的这一段，原文是：当被问及今年是否计划前往参拜靖国神社时，小泉说：“看看我以前做过的事情，你就会知道我会采取什么样的行动。单凭我们放弃参拜靖国神社，我不认为我们同中国的关系就会融洽。”

显然，就如众多新闻媒体所指出的那样，小泉纯一郎这是在暗示“如果执政自民党在九月十一日的国会大选胜出，他将会再次到靖国神参拜”。从这个暗示中、我们不难看出，小泉再一次抓起了他的“民粹牌”。


*** 一旦感觉没有把握赢得大选、小泉极有可能再次在政治、甚至军事上冒险

可以肯定的是，他的“再次变脸”将会极大的影响自己的“选票构成”，在东方评论员看来，有一点是可以肯定的，如果日本民主党的支持率继续上升、那么，那些反对他参拜靖国神社有日本民众、将不再是他的关注对象，同样可以肯定的是，届时、为了重新拿回支持率、小泉一定会将赢得大选的“重心”重新移到了8月8日之前、正式操起“民粹牌”、在国际上去“找牌”。

记得在一次点评中，我们的一位时事评论员曾经针对小泉纯一郎的“变脸”说过这么一句话，他认为，现在离日本大选这么一段“说起来已经不长、做起来却绝对不短”的时间内、日本国内会发生什么事“只有天知道”。

在我们看来，小泉纯一郎最为看重的、其“支持率”上的“意外、曲折的变化”，算是“只有天才知道”这一档子的事了。东方评论员认为，在这里，我们愿意继续强调一次，即，对此北京要保持足够的警惕、警惕视赢得大选为眼下最大利益的小泉、一旦感觉没有把握赢得大选、那么，他极有可能再次在政治、甚至军事上冒险、将之前一点点掏出来的、诸如“日本打算与中方在东海问题上尽早恢复协商”等所谓善意扔到一边、在东海问题上挺而走险。


*** 配合着小泉的“再次变脸”、日本帝国石油公司已经“再次”跳了出来

事实上，东方评论员认为，这种苗头已经出现了，除了小泉纯一郎暗示赢得大选、他将继续拜鬼的这件事之外，那个在东海中日争端中扮演重要角色的、在8月15日之后、一度声称“由于存在安全问题，该公司不可能很快在东海海域进行油气试钻探”的日本帝国石油公司、已经“再次”跳了出来，配合着小泉的“再次变脸”、“再次”改口强硬的声称“就是中国不同意，也要开采东海油气”。

当然，在东方评论员看来，与8月15日开始的那次“系列性变脸”施展的套路一样，小泉所施放的信号是同样是“多层次”的，在上外提及的两个信号之外，两天前、日本政府还准备在“冲之鸟”建立灯塔、显然，这是将“冲之鸟”这块北京所定义的“石头”、建成一个日本嘴中的“岛屿”的重要一步，也同样是小泉纯一郎再次“系列性变脸”套路中的重要一环。


*** “国际社会”对小泉纯一郎的“再次变脸”也是早有提防

显然，“国际社会”对小泉纯一郎的“再次变脸”也是早有提防，在东方评论员看来，北京“突然决定”隆重纪念抗战胜利“一个甲子”年的本身，就是在针对小泉纯一郎的“再次变脸”、针对日本保守势力的“可能异动”而做的布署、这也算是打出了一张“历史牌”。

其实、针对日本保守势力的“异动”，另一个关注日本历史问题的亚洲国家-韩国，也终于打出了一张准备多时的“历史牌”。我们注意到，就在昨天，韩国政府让一家民间机构发表了一份3095名“亲日派(又称韩奸)”名单。在东方评论员看来，这对韩国国内势力不小的亲日势力是一个沉重打击，它对“韩日关系”的影响、对“美日韩”军事同盟的冲击“不容小视”。

*** 让我们觉得相当有兴趣的几件事

首席评论员认为，也正因如此，我们对布什宣布他将在9月3日发表一个有关美国战胜日本60周年的讲话、以及公开表示“将把伊拉克比照日本那般进行改造”这两件事相当有兴趣。就表面看来，除了中韩、似乎美国也准备将日本的历史问题“拿出来把玩”一番。

在一段相关消息的后续报道之后，东方评论员将就“中韩”同时对日本打出“历史牌”、以及华盛顿在北京“再次宣布”胡锦涛主席将对美国进行“国事访问”之际、罕见地主动提及美国与日本的历史恩怨这几件事、一并进行讨论，并给出我们的观点。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
