# -*- org -*-

# Time-stamp: <2011-08-04 12:07:56 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 2005年7月15日   星期五




** 解放军少将指美若为台动武中国核武反击




【凤凰卫视7月15日消息】据外电综合报道，中国解放军少将朱成虎警告，如果美国在台海冲突时，向中国发动武力攻击，中国已准备好动用核子武器，向美国作出还击。

报道引述中国国防大学防务学院院长的朱成虎说：“如果美国将他们的导弹和定位发射系统对准中国领土内的目标，我想我们将一定用核武器予以还击。”

朱成虎是在一个为外国记者举行的会议上，发出上述警告。他补充说，中国的领土包括战舰和飞机。

“如果美国人决定干涉，我们就决定还击。我们中国人准备好西安以东的城市全部被毁，但美国人也要准备好数百个城市被我们中国人摧毁，”他说。

报道说，朱成虎较早前警告，中国能够用长程导弹打击美国，但是他威胁在台海冲突中使用核武器，是近十年来中国高级官员鲜少使用的说法。

路透社向中国外交部询问，外交部发言人表示，这个说法是朱成虎个人说法，不代表政府。而国防部回应时拒绝就此发表评论，但表示朱成虎出席的这个会议是外交部举办的。

报道引述美国前议员说，这个说法和中国之前的说法不同。自从1964年中国爆炸原子弹以来，中国官员一直说，不会首先使用核武器。不过，朱成虎不是第一个谈到在台海冲突中使用核武器的可能性的官员。

美国前助理国防秘书ChasFreeman说，在1999年，解放军官员就告诉他，美国如果在台海冲突中介入，中国能够反击美国。

路透社引述中国外交部发言人说，他们正在调查这番言论。



【时事点评】据了解，朱成虎少将是解放军国防大学防务学院院长、可谓是中国“军方高官”，而这席话是日前在香港“明天更好”基金会组织的一次会议上、由他亲口向外国记者表示的。

*** 屹今以来中国方面发出的“最为直白的”警告

显然，这种“我们中国人准备好西安以东的城市全部被毁，但美国人也要准备好数百个城市被我们中国人摧毁，”的警告。可以说是屹今以来中国方面发出的“最为直白的”警告。

因此，在东方评论员看来，我们首先要做的，就是去弄清楚朱成虎少将的“这个讲话”、倒底是个什么背景？

在我们继续讨论这个问题之前，先来看另外一则相关报道。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com



** 核武攻美？解放军将领谈话外界关切

【外电综合消息】对于外国媒体引述中国解放军少将朱成虎说，中国已准备使用核武对付美国，香港浸会大学欧洲文献中心主任杨达今天说，这可能只是朱成虎个人的说法，不代表官方立场，但有军事观察家持相反意见。

外电今天引述英国金融时报报导，朱成虎在向外国记者简报时警告，如果美国因台湾问题攻击中国，中国准备使用核子武器对付美国。他也说，这是他个人的意见，他也不预期中国会与美国发生冲突；但如果美国发动攻击，中国别无选举，只有诉诸核武。

据台湾媒体报道，杨达说，在核武问题上，中国过去一直采取模糊政策，现在朱成虎说得那么明白，不符合中国的一贯立场。研究国际战略的杨达说，核武是战略问题，战略家都不会说得太明白，或点名某些假想敌。所以，他觉得，即使朱成虎确实说了媒体所说的那番话，也只是个人意见居多，并非官方立场。

杨达又说：“有关这种报导，这觉得有点奇怪，我怀疑是报纸的揣测。”

不过，香港的中国军事观察家李风表示，假如报导属实，朱成虎的谈话并非只是个人意见，必定代表中国军方的立场。他说：“他（朱成虎）那些人怎么会有个人意见？怎么敢随便乱说？既然敢接受外国媒体访问，假如乱说，不是要丢乌纱帽？”

李风指出，一国的军事战略原应是含糊处理的，但看来中国在台海问题上并非如此，而是要明白告诉美国它在台海问题上的底线。他说：“这是战略讯息。在台湾问题上，北京采取战略讯息，有话说在先，没有模糊空间，特别是军事方面，一定要让美国明明白白知道。”

他并说，据他了解，在台海问题上，中国军方的看法是一致的，即假如爆发战争，以及美国介入和中国打不过时，就会使用核武。

至于核武攻击的对象，可能只是美国的航空母舰及美军的海外基地。不过，一旦用上核武，双方的手段难免会愈趋激烈，最后攻击本土。

他说：“这里动一下，那面提升，这里又动一下，双方会愈搞愈激烈。”

据称，朱成虎是中共解放军较年轻而受重用的将领，他的观点与副总参谋长熊光楷差不多。熊光楷职责之一是负责解放军对外关系，包括与美国对话；他曾多次访问美国。




【时事点评】我们注意到，按香港浸会大学杨达先生的判断，“这可能只是朱成虎个人的说法”，其理由是“在核武问题上，中国过去一直采取模糊政策，现在朱成虎说得那么明白，不符合中国的一贯立场”。


*** 在东方评论员看来，杨达先生的这个观点是值得商榷的

另外，这位研究国际战略的杨达还说，“核武是战略问题，战略家都不会说得太明白，或点名某些假想敌。所以，他觉得，即使朱成虎确实说了媒体所说的那番话，也只是个人意见居多，并非官方立场”。

然而，在东方评论员看来，杨达先生的这个观点是值得商榷的，显然，这种观点的根据是“对战略问题、战略家都不会说得太明白”。当然，按一般的常识来看，这种根据是“非常严谨”的。


*** 对别国进行核威胁、美国就是一个“现成的例子”

事实上，东方评论员认为，这里就有一个现成的例子，就是美国。要知道美国的五角大楼就公开放风“攻击中国三峡大坝”，而中国军方也是早已经公开宣示：任何对三峡大坝的攻击行为、都将遭到中国的全面报复、并明言这种报复就包括核报复。

因此，我们就有必要弄清楚，五角大楼就公开放风“攻击中国三峡大坝”，这算不算是战略问题呢？

还有，早前，美国国防部的一份正式文件，就公开将俄罗斯、中国等七个国家列为核打击对象。可谁都知道、以俄罗斯公开的核战略打击力量、美国在将俄罗斯列为核毁灭对象的同时，本质上是将自己也列为核毁灭对象。显然，华盛顿的这份正式文件的矛头是直指中国、是在对中国进行“最为露骨的核讹诈”。

这样的例子还有，近来，就在不久前，美国军方高官又公开威胁说“将中国全国的重要军事目标列入美国空军的远程打击目标”、这是否又属于战略问题呢？


*** 美国军方敢说的话，中国军方又有什么不可以说的呢？

显然，如果算、那么、所谓的重大战略问题就不是“不可以”说清楚的，在东方评论员看来，只要符合自己的利益、认为极有必要、而且还可以做、有条件做，那么、美国军方敢说的话，中国军方又有什么不可以说的呢？对此，东方军事评论员就认为，只要有利于达到自己的战略目的、中国军方的强硬、绝对有助于北京最大限度地争取和平解决一系列重大问题。

显然，杨达先生的观点“过于严谨”、而少了点“变通”。



*** 李风先生对中国政府的“运行机制”非常了解

相比之下，东方评论员倒觉得香港的中国军事观察家李风先生的观点“值得重视”。请大家注意这一段：原文是，香港的中国军事观察家李风表示，假如报导属实，朱成虎的谈话并非只是个人意见，必定代表中国军方的立场。他说：“他（朱成虎）那些人怎么会有个人意见？怎么敢随便乱说？既然敢接受外国媒体访问，假如乱说，不是要丢乌纱帽？”

非常清楚、李风先生对中国政府的“运行机制”非常了解，东方评论员也认为，在中国这个严格控制政府对外言论的体制下、在重大问题上、特别是涉外战略问题上、任何一级官员的公开讲话都是要经过官方授权、且“三思而后行的”，更别说这种将严重冲击国际舆论、中美关系的“核战略问题”了。


*** 有几个信息似乎能充分证明我们的推测

当然，朱成虎将军的讲话是否代表个人、或者根本就代表中国政府、中国军方、还是得相关部门出来“认账”才行。然而，有几个信息似乎能充分证明我们的推测：

第一，据我们了解，朱成虎所讲的这番话，并非在一个“非正式场合”、而是在一个官方安排的正式场合；

第二，朱成虎所讲的这番话，也不是与人私下闲聊时“不小心”透露的，而是在他做完一篇题为《当前国际战略形势与中国安全环境》报告之后、在公开回答记者提问时、特别指出的。


*** 外交部一脚将皮球“踢给”了国防部

第三，也是非常耐人寻味的，在这番“核爆炸”般的消息出来之后，在各方人马向中国外交部“正式求证”时，但是，外交部发言人的说法“有两点”值得注意：首先，是说“还在了解情况”，显然，这是即“没有承认”也“没有否认”；其次，是建议“应该向中国国防部查询”、显然，外交部一脚将皮球“踢给”了国防部；

第四，在接到外交部踢来的皮球之后，国防部在回答查询时说的更有意思：“朱成虎将军是在外交部举办的活动中说这番话的”、之后、不仅对“讲话”拒绝评论、而且没有了任何下文。


*** “两大当事部门”的“这个皮球”踢得好、好就好在“什么都没有说，但又什么都说了”

在东方评论员看来，当我们观看了这场中国“两大当事部门”之间的“足球赛”之后、有何感想呢？显然，我们的感觉是，外交、国防部之间的“这个皮球”踢得好、好就好在“什么都没有说，但又什么都说了”，至于其中的奥秘、看来中国官方是“有心”请“有心人士”自己去琢磨、一个“还在了解”另一个“拒绝评论”、如此一来、就没有了任何“框框”、因此，“有心人士”是“爱怎么琢磨就怎么琢磨”。


当然，时事评论员们也自信算是一群“有心人士”，因此，我们也就得好好琢磨、琢磨！事实上，也就在我们“琢磨”的过程中、另一则消息来了，是外交部的、也是我们“等待中的”。

我们先来看看这则消息，之后、东方时事评论员、军事评论员、经济评论员“都有话要说”。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com



** 日本侵犯我东海主权外交部约见日驻华公使




【北京消息】新华网北京7月15日电中国外交部亚洲司司长崔天凯15日紧急约见日本驻华使馆公使渥美千寻，就日本经济产业省14日正式宣布授予日本帝国石油公司在东海中日争议海域的试开采权，向日方提出严正交涉。

崔天凯表示，日方的这一行为是对中国主权权益的严重挑衅和侵犯，也违反了《联合国海洋法公约》的有关规定。中方对此表示强烈抗议。

崔天凯指出，中日在东海尚未划界，双方在划界问题上存在争议。日方利用所谓“中间线”这一单方面主张，在中日争议海域对日民间企业授予试开采权，是站不住脚的。中方明确重申：中方从未承认过所谓“中间线”，也不可能承认。“中间线”以东海域属争议海域，日方在这一海域无权采取单方面行动。如日方试图将自己单方面的主张作为既成事实强加于中方，中方坚决反对，也决不会接受。

崔天凯强调，中日双方应坚持通过对话，平等协商，妥善处理分歧，积极探讨解决办法。这是两国领导人达成的重要共识。中方郑重要求日方切实本着上述精神，立即改弦更张，停止任何侵害中方主权权益的行径。

同日，中国驻日本大使馆也向日本外务省提出了严正交涉。



【时事点评】在“仔细”研读了外交部的“强烈抗议”之后，东方评论员认为，比起4月份的“严重警告”来、这份“内容稍缓”的“强烈抗议”显然是“一系列抗议”中的“第一份”。


*** 北京没有指望这“第一份”强烈抗议能收到实际效果

从我们的经验来判断，北京没有指望这“第一份”强烈抗议能收到实际效果，这就是说、在日本“必然会有的”后续“动作”时、北京的“强烈抗议”会有“第二份”、“第三份”....且“内容”、“措辞”也会“逐渐升级”。

在东方评论员看来，今后、什么“警告”、“一切严重后果自负”等语句、都将视日方的“持续动作”而“一一而至”，显然，这种安排本身就是一种威慑、不仅是对日本逐级施加压力的一种手段、也是有意一步步调动各方舆论的一种策略。


*** 小泉纯一郎极有可能在东海问题上“孤注一掷”、寻求外交、内政困局上的“双突破”

事实上，在13日、14日的《东方时事解读》中、我们连续地针对中国一位退役海军副司令透露的“对钓鱼台问题中国要有军事准备”、国台办扔出的“为台湾渔民护渔”两则消息进行跟踪分析。

在东方评论员看来，就如之前所说的那样，一旦小泉纯一郎和日本保守势力迫于形势的需要，企图以“政治、军事上的冒险”、来寻求在外交、内政困局上的“双突破”、是极有可能在东海问题上“孤注一掷”、从而达到让日本企业的东海探测船、将其拖出“里外不是人”困境之目的。


*** 如果美国不早点摆明立场，中日在东海问题上“擦枪走火”的可能性是“不小”的

在昨天的点评中，在日本问题部分，东方评论员就曾经说过，在东海主权争端的问题上，日本方面尽管在那“唱高调”，说什么“在为日本企业提供安全护航方面、日本有多种军事选择”。

但是，在我们看来，由于中日综合实力的对比，日本在这个问题上的军事选择余地“并不大”。然而，东方评论员也认为，如果企图从中日关系破裂中“渔翁渔利”的华盛顿、不早点认识中日关系破裂的后果、可能引起全球经济上出现一种无法预料的局面、而将自己的立场早点摆清楚，那么，中日在东海问题上“擦枪走火”的可能性却是“不小”的。


*** 北京很可能采取如下几种措施

然而，我们认为，一旦日本企业的东海探测船开进有争议海域，就极有可能“玩出点火花”出来。在东方军事评论员看来，北京很可能采取如下措施：第一，先动用“非军事手段”驱离、甚至扣押日本企业船只、设备；第二，如果日本因此出动军事力量护航，不排除中国先在钓鱼岛方向采取军事行动、将军事动作集中在更具现实意义和战略意义的钓鱼岛上。


东方军事评论员认为，只是如此一来，中日东海主权争端、就立刻演变成了中国“维护中国国家主权统一这一核心利益”的一个“前哨战”，显然，钓鱼岛是中国的领土、也是中国台湾省的辖地、只是日本也声称对钓鱼岛拥有主权。


*** 华盛顿的“几种选择”

有意思的是，与日本签定“美日军事同盟”的防卫范围、并不包括钓鱼岛，也不包括东海争议海域，而美国也从来没有正式确定过在“中日”这两处主权之争中、承认谁拥有主权，按华盛顿前副国务聊的话来说“美国对钓鱼岛主权归属的立场就是没有立场”。

如此一来，华盛顿就有了“几种选择”：第一，如果美国政府“有意”将钓鱼岛主权“解读”为台湾辖地、那么，站在“台独”的立场来看、大陆是主动攻击，“台独”根据美国的口头承诺、当然会要求美国军事介入。

*** 华盛顿随之而来的“某种尴尬”

这样，在东方评论员看来，中国军方高官放风“如果美国因台湾问题攻击中国，中国准备使用核子武器对付美国”就成了事先“打预防针”、显然，在“美国全国人民”都知道美国国会要投票“选举”是否需要一场可能的大规模的、毁灭性的、却怎么想都与美国平民没有关系的核战争时、华盛顿随之而来的就有了“某种尴尬”：至于华盛顿新保守主义决策层怎么从美国的全球战略去思考、是美国决策层那几个“精英”的事，而盯着美国选民选票、更“关注自家性命和财产”的美国国会议员如何投票、那就是美国国会议员们需要认真考虑的事情了。


第二，如果美国政府“有意”将钓鱼岛主权“解读”为“不是台湾辖地”（注意、这与直接解读为“日本拥有主权”有本质区别），那么，美国就有足够的理由“置身事外”，因为“美日安保条约”没有写上钓鱼岛这一块、美国人是两头不用尽义务。

第三，如果美国政府“有意”将钓鱼岛主权直接解读为“日本拥有主权”，那么，在中国在因维护钓鱼岛主权而与日本发生军事冲突时候、美国针对钓鱼岛的任何军事介入、首先就会因“没有法源基础”，而需要寻求法源。


*** 日本“修改”美日安保条款当然是没有任何问题，可关键问题是美国人愿意“寻求这个战争法源”吗？

显然，在东方评论员看来，日本方面“修改”美日安保条款当然是没有任何问题。可关键问题是，十几万大军、花费几千亿美元、近三年时间、美军甚至还没有打胜对伊拉克这个、对自己经济毫无影响的小国家的战争（布什前几天亲口说的），那么，华盛顿决策层怎么就那么有把握去说服美国人民支持一场针对中国这个、与美国经济结合紧密的、军事大国、核大国的大规模战争呢？

特别是现在，又有了朱成虎将军的这篇“准备抺掉美国几百个城市”的“讲话”这么一闹，美国国会的那些、可以说几乎全是从这几百个城市选出来的、几百号议员“是否就一定愿意”投票选择一场旨在保护日本利益，与自己利益无关的大规模战争呢？而且这是一场很可能立刻就得兑现的、与中国间全面核战争。



*** 朱成虎将军的“讲话”，根本就是北京针对“美国全国人民”的一次“全民广播”


显然，在东方军事评论员看来、朱成虎将军的“讲话”，根本就是中国政府的“有意而为之”，不仅不是朱成虎将军的个人观点、而且可以视为北京针对“美国全国人民”的一次“全民广播”。


*** “美国人民”不知道政客说的“协防台湾”对美国人意味着“什么后果”

在东方评论员看来，华盛顿天天挂在嘴边的就是那份“与台湾关系法”、赖斯这次到了北京、仍然将它拿出来显摆一番，显然，华盛顿喜欢这样做的基础、倒不是“与台湾关系法”里面的内容有多么了不得，而恰恰是因为美国社会“根本不知道”华盛顿决策层每每在说出“与台湾关系法”时，往往带出的一句话对美国人意味着“什么严重后果”，这句话就是“美国将履行协防台湾的义务”


*** 东方军事评论员曾经有一句玩笑话：五角大楼最新“中国军力报告”是抄袭80年代版本

众所周知，美国五角大楼喜欢搞针对中国的“中国军力报告”，然而，这份军力报告自其问世以来，在我们的记忆里就几乎没有客观过，从来不缺的就是夸张，夸大中国的军力，然而，有一点我们也注意到了，那就是针对中国最具威胁的核力量，这种“军力报告”却总是保持着“低调”，总而言之，如果不看常规军力部分，而只看核战略打击力量部分的话，东方军事评论员曾经有一句玩笑话，很怀疑五角大楼的最新“中国军力报告”、大概是抄袭自80年代写就的版本。


*** 美国刻意宣传的“中国军力报告”中的“两个令人不解、没有根据的断论”

显然，东方军事评论员认为，“这种严重后果”在美国所刻意宣传的“中国军力报告”中的“两个令人不解、没有根据的断论”所掩盖：第一：“几十年停滞不前的”“中国现有核规模”--“到目前为止中国只有区区二十枚可以打到美国的、落后的、生存力极低、发射准备时间极长的洲际导弹”；

第二，“根本不必在意”的中国“远期核规模”：“到2015年，将有100枚可以投送到美国本土的核弹头”；


*** 似乎美国要“协防台湾”、其“安全性”就有如美国攻打伊拉克一般

不难想像，在这种内容的“中国军力报告”的“掩盖下”、在美国人民的心里、似乎美国高官、军方动毋就要“协防台湾”、其“安全性”就有如美国攻打伊拉克一般。显然，在华盛顿决策层的战略欺骗下，在美国社会看来，一场与中国之间的军事冲突、大概就与美国打伊拉克一样，根本就与美国本土上的身家性命毫无关系，美国人民可能付出的代价，不过是只需要拿出“维护民主的正义感”、掏点军费就行。


*** 朱成虎少将今天的这番言论，彻底揭下了华盛顿这种欺骗宣传的“道具”

然而，在东方评论员看来，朱成虎少将今天的这番言论，可以说是彻底揭下了华盛顿这种欺骗宣传的“道具”、揭露了华盛顿“刻意掩盖的真相”，这就是说，一句“我们中国人准备好西安以东的城市全部被毁”，充分说明中国不必等到2015年、也不必考虑那二十枚“落后的、生存力极低的”洲际导弹是否会生存下去、中国现在就有能力“要美国数百个城市被我们中国人摧毁”。


*** 当我们用笔“涂抺掉”“四十”个重要目标之后，美国绝大部财富就已“被抺去了”

显然，在东方经济评论员看来，如果我们真的对着美国地图去数“数百个城市”的话，那么，当我们用笔去“涂抺掉”“四十”个美国重要城市之后，就已经不难发现，美国的绝大部分财富、就已经“被抺去了”。在我们看来，那余下的几百个美国城市、就算没有遭到核打击、恐怕也将因没有了那四十个城市而将生活在地狱之中。


*** “中国有能力要炸毁美国胡佛大坝”的消息、曾被美国主流媒体“刻意封锁”、“不做报道”

众所周知，去年、在台海局势最为紧张的时候，美国五角大楼的专家、就放言“要用远程打击武器攻击中国的三峡大坝”、而当时的中国军方、也是毫不示弱，并放言“中国也有能力炸毁美国的胡佛大坝”。

然而，东方评论员注意到、这则“中国有能力要炸毁美国胡佛大坝”的消息、却被美国主流媒体“刻意封锁”、“不做报道”，因此，它也就“丝毫没有影响”美国人的“正常生活”，也丝毫没有影响美国政治人物的“政治生活”、也就丝毫没有影响美国社会的“判断力”、同样、也就丝毫没有“从美国社会方面去反向影响”白宫决策者的“言行举止”。

另外，就是不久前中国成功试射、涵盖美国本土的“巨浪二”战略潜射导弹，美国也有什么专家出来、在做了一大堆推导之后、下了个“中国的094没有能力发射巨浪二”、因此中国没有第二次核打击能力、所以中国仍然没有能力核威慑美国、阻止其干涉台海的结论。

结果是，美国政府高官、美国国会议员、甚至是美国的战略智瓤，仍然喜欢在那里拿着“与台湾关系法”说事，仍然在那里拿“不排除协防台海”往自己脸上“贴金”，并以此来与北京“讨价还价”、甚至还以此来“当做利益”、去“招睐民意”。


*** 这种“近乎宣战式的公开警告”、喜欢“挑三拣四”美主流媒体恐怕很难再去“装聋作哑”

显然，在东方评论员看来，恐怕再没有什么利益比得上避免“几百个城市被核攻击”更加重大的了，因此，我们有理由相信，热衷于讨论、甚至修改“与台湾关系法”的美国国会的议员们、对这种“重大利益”、一定会“认真对待”、“严肃处理”的。

还有，我们同样有理由相信，在朱成虎将军这种“近乎宣战式的公开警告”、善于“玩新闻自由”、却又喜欢“挑三拣四”、还经常有意识地“装聋作哑”的美国主流媒体，恐怕很难再去“什么都没有听见”了。


*** 北京是在以尽可能“不可辩解”的方式告诉美国社会，“中国一样可以毁灭美国”

在东方评论员看来，这与之前拉姆斯菲尔德声称“中国军事威胁论”、而中国也就发射了一枚可以涵盖美国本土的“巨浪二”潜射战略核导弹的动机是一样的，那就是，北京是在以尽可能“明白无误”、“不可辩解”的方式告诉美国社会：“中国一样可以毁灭美国”。


*** 如果.....北京还会以更加震撼性的手段去“证实”中国“一样可以毁灭美国”

首席评论员高度评价这一“直白的警告”。在我们看来，这一警告的重大意义在于北京是在“用事实警告”华盛顿决策层：如果华盛顿的战略设计者们认为“这一警告”还不够明白、还能让自己“刻意不相信”中国有能力毁灭美国、而去继续拿着那份毫无约束力的“与台湾关系法”去“招摇撞骗”、继续“不担心会支付任何政治代价”去信口说什么“廉价”的、“不排除美国军事介入台海”之类的话，那么，北京还会有别的、更加震撼性的手段去“证实”中国的核打击力量“一样可以对美国社会进行毁灭性打击”、以更加震撼的方式去冲击美国社会、直到华盛顿决策者这套“自欺欺人”的把戏“玩不下去为止”。


*** 如果....北京是有可能趁美国仍陷在中东、而提前用兵的

当然了，我们应该警惕的是，一旦美国继续怂恿日本在东海挑衅，而美国和台独也决意要利用日本这一挑衅行动的掩护、而以加快“武力抗统”的准备工作、那么、北京是有可能趁着美国主要战略资源仍然投放在中东的时候、提前在维护中国的、包括台湾（钓鱼岛）、东海主权这一核心利益上提前用兵的。


*** 北京当然要做好全面的准备，也要做最坏的准备

在东方评论员看来，一旦北京决定在钓鱼岛、或者台海用兵，那么、任何事情都是有可能发生的，对此，北京当然要做好全面的准备，也要做最坏的准备，显然，最坏的准备莫过于朱成虎将军所说的：“如果美国人决定干涉，我们就决定还击。我们中国人准备好西安以东的城市全部被毁，但美国人也要准备好数百个城市被我们中国人摧毁”。
尽管这一公开威胁仍然是种“宣传策略层次”上的运用，但是，走出这一步，就会有第二步，直到对美国社会造成全面冲击、反过去影响美国决策层的战略宣传。

东方评论员认为，在另一种角度来看，这种针对美国的直接威胁，将对“台独”和日本右翼造成极大的震撼，非常清楚，北京对他们的主子也要喊打，何况他们乎！

在我们看来，这又何尝不是对美国兜售“中国威胁论”的又一次重大反击呢？起码让美国决策层明白，今后任何“不利于中美关系”的言行、都是有“严重后果”的。


*** 在最坏的局面之外，还有一种不可预测的局面发生

朱成虎将军所说这当然是最坏的局面。另外，东方经济评论员也认为，如果华盛顿出于不冒与中国打核战争的风险而没有介入、那么，台海、东海上的任何一场军事冲突，都可能对中国、日本、美国、欧盟以至全球的经济予以重创。

在我们看来，在最坏的局面之外，还有一种不可预测的局面发生：在这个全球化的年代、以中国每年呑吐一万四千亿美元的外贸，现加上日本近一万亿美元的外贸、任何一点风吹草动，这“两大块都”将使华盛顿金融管理当局管理的那套“国际金融体系”、“国际投资市场”遭遇重创，其牵扯范围之广，恐怕是世界所有经济体都无一幸免。


*** 如果“美国人民”不想看到冒“最坏局面”的风险......就请他们的政府“说说清楚”

不过、还好，直到现在为止，事态还在可控制范围之内，在主权问题上，中国没有选择，也没有妥协余地。因此，在东方评论员看来，如果“美国人民”不想看到最坏的局面发生，那就请“置身事外”好了；大陆与台湾统一的事，是中国内部的事，由不着外人插手；中国与日本的主权争端，是中国与日本的事、也用不着美国插手，

如果“美国资本家”不想看到这一“不可预测的局面”发生、那么，就让你们的政府将美国的台湾政策“说说清楚”，将美国在钓鱼岛、东海主权问题上的立场“说说清楚”。东方评论员相信，以“台独”和日本保守势力的“份量”、在寻思是否有能力与中国大陆在台海、东海上较量一番的时候、一定会有自知之明。

在一则来自英国BBC的消息之后，东方时事评论员、经济评论员、军事评论员将继续一起讨论这个话题。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

