# -*- org -*-

# Time-stamp: <2011-08-04 00:29:30 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 2005年6月06日  星期一



** 美日再次渲染中国威胁中方阐述新安全观

【新加坡消息】综合报道，美国国防部长拉姆斯菲尔德4日在新加坡举行的亚太安全会议上发表演说，批评中国快速发展军力，国防支出大幅增加，对周边国家和地区产生威胁。

出席同一场合的日本防卫厅长官大野功统亦呼吁中国公开更多有关军费开支的详情。

对此，中国外交部亚洲司司长回应表示，中国军费开支是合理的。他并强调，早在上个世纪末，中国领导人即针对冷战后国际安全问题的新特点，特别是各国人民普遍希望获得安全的迫切愿望，在多边论坛首倡以互信、互利、平等、协作为核心的新安全观。中国愿意以自身对当今安全问题的科学理解和负责任的行动，为增进地区的和平、安宁与祥和作出自己的贡献。

美防长声称中国无理扩军

美国国防部长拉姆斯菲尔德4日指控中国在没有受到其他国家的军事威胁情况下却增强军备，他认为建立军备会导致区内军事不平衡，尤其是在台海地区。

拉姆斯菲尔德指出，中国的崛起是亚太区域最重要的事实，全球也都乐见一个承诺和平发展的中国。但他强调，亚太区域和全球公正地评价中国的同时，也不能忽略整个区域所关切的事情，那就是中国的军事扩张问题。拉姆斯菲尔德表示，美国国防部的2005年度军事报告很快将出版。

他透露，该报告认为中国的实际军事开销远比官方公布的数字高许多，意味着中国已成为全球军费支出第三高、亚洲第一高的国家。他又指责中国明显在扩张导弹力量，并让导弹发射能力远至全球许多地区。

拉姆斯菲尔德认为中国应该公开更多有关军费开支的状况。

日责中国军费欠透明度

同一场合，日本防厅长官大野功统亦敦促中国公开更多有关军事开支的资料，他说，虽然中国过去十年来的军事预算每年递增逾一成，但不清楚其官方数字是否包括研究开支。大野批评中国在军事开支方面欠缺透明度，并强调日本鼓励中国作出改善，日方对此的立场与美国一致。

此外，美日于今年较早前曾发表联合声明，指已将和平解决台湾问题定为联合目标，中国对此表示过强烈不满，公开表示不欢迎外国干预内政。然而，大野4日却重申这项声明，指美日政府「鼓励透过对话和平解决有关台海的问题」。

大野并试图纾缓外界对东京政府去年推出的国防指引所造成的忧虑，他说：「日本的军事政策是以国防为主导，日本永不会成为一个对外国构成威胁的军事强国。」

中方反驳所谓「中国威胁论」

对此，一同出席此次会议的中国代表团团长、外交部亚洲司司长崔天凯回应说，美国的军费比中国多得多，美国应明白每一个国家均有其防卫重点。中国的军费开支是合理的，美国的批评是站不住脚的。

据悉，中国在今年3月宣布，计划在本年度增加12.6%军费，主要用于军队现代化及军人福利等方面，但强调并非针对台湾。相关官员表示，中国的国防费用同其他大国相比处于一个较低水平，中国今年的国防预算数目同其他大国相比是一个相当低的数目，占中国财政支出的比重以及占国民生产总值的比重都是比较低的。

中国代表阐述新安全观

此外，崔天凯亦于当日表示，早在上个世纪末，中国领导人即针对冷战后国际安全问题的新特点，特别是各国人民普遍希望获得安全的迫切愿望，在多边论坛首倡以互信、互利、平等、协作为核心的新安全观。时至今日，新安全观不但成为中国解决国际安全问题的根本指导思想和价值观，还被载入不少国际文件，日益被国际社会所接纳和奉行。

他说，中国的新安全观首先是综合安全观。中国主张既要继续努力解决尚未解决好的传统安全问题，也要重视解决日渐增多的各种非传统安全问题。他同时表示，中国的新安全观也是发展安全观、合作安全观、共同安全观。中国追求的最终目标是国际社会的共同安全。这有助于为各国开展安全合作指明方向，奠定坚实的基础。

崔天凯指出，在新安全观的指导下，中国近年来与地区内外国家务实合作，积极参与合作解决各类安全问题的努力，为促进地区和平、安全和稳定发挥了独特的建设性作用。






【时事点评】事实上，对这个由伦敦国际战略研究所发起的“亚太安全会议”，东方评论员一直在关注中，在我们看来，由于中日关系近来“持续紧绷”，“跟布什跟得特别紧”的小泉纯一郎、也由于中日关系已经陷入三十年来最糟糕的状况、并因此在国际、特别是国内受到极大压力，这都是我们认为有必要“认真对待”这次美日共同参加的“亚太安全会议”之原因，显然，这次北京仅派出了一个“规模相当小、级别也不高、且由外交部而非国防部牵头代表团”与会，似乎已经说明北京对这次会议“没有兴趣”。


*** 拉姆斯菲尔德“开足马力”、对中国的国防政策进行了“猛烈的攻击”

东方评论员注意到，面对中国外交部牵头的“小规模、低级别代表团”，美国国防部长拉姆斯菲尔德这次在会上依然是“拉高声调”、“开足马力”、对中国的国防政策进行了“猛烈的攻击”。

请大家看看这一段：拉姆斯菲尔德指出，中国的崛起是亚太区域最重要的事实，全球也都乐见一个承诺和平发展的中国。但他强调，亚太区域和全球公正地评价中国的同时，也不能忽略整个区域所关切的事情，那就是中国的军事扩张问题。拉姆斯菲尔德表示，美国国防部的2005年度军事报告很快将出版。

他透露，该报告认为中国的实际军事开销远比官方公布的数字高许多，意味着中国已成为全球军费支出第三高、亚洲第一高的国家。他又指责中国明显在扩张导弹力量，并让导弹发射能力远至全球许多地区。



*** “非正式”抛出了“中国威胁论”

首席评论员指出，拉姆斯菲尔德的这番话，其“内容”显然是“空前激烈”的、可以说与日本之前的言论、是一个腔调。在我们看来，如果他这是代表美国政府“正式政策”的话，那么，也算是“非正式”抛出了“中国威胁论”。

要知道、这可是2月份，华盛顿在拉日本将台湾纳入“美日军事同盟”防卫目标时，都“没舍得公开拿出来”的东西，尽管美国本来就是“中国威胁论”的“发源地和制造者”。


*** 足以令日本人“雀跃不已”

当然了，对华盛顿“终于拿出了”“中国威胁论”，尽管是“非正式”的，但已经足以令日本人“雀跃不已”了。

大家从电视画面里就可以看到，就在同一场合，日本防厅长官大野功统也“立刻附和”说，除了当场“翻译”许多拉姆斯菲尔德对中国的攻击论调，比如“中国在军事开支方面欠缺透明度”，还比如“敦促中国公开更多有关军事开支的资料”之外，这个大野功统还学着美国人的“说话腔调”，说什么“日本鼓励中国作出改善”，最后、还非常肯定地表示：“日方对此的立场与美国一致”。


*** 小泉太需要来自华盛顿保守势力的“支持”了

东方评论员认为，大野功统的“立刻附和”、并强调“日方对此的立场与美国一致”，这些都不奇怪。之前，针对吴仪提前回国，中止与小泉纯一郎的会见一事，有一种观点就认为，北京这是“打狗给主人看”，意思是说，胡锦涛这一耳光打在小泉的脸上，却'痛'在布什的身上。

在我们看来，这种比喻有点“不太确切”，如果改成“.....打在小泉的脸上，却'惊'在布什的心里”、似乎更能描述当前“中美日”三国之间“关系的现状”。

显然，已经被北京“完全冷冻”了的小泉保守政府、在被中国揪住靖国神社问题、在国际社会面前“一再质问”：“是不是要走和平路线、是否准备要走军国主义”的时候、在小泉本人备受日本国内、外各种力量“煎熬”的时候，太需要来自华盛顿保守势力的“支持”了。


*** 布什有如给小泉纯一郎打了一针“强心剂”

而华盛顿对此也是“心知肚明”，自然也是担心小泉纯一郎在这个关键时候“会顶不住”、而从目前日本奉行的这条与中国交恶、却最符合美国战略利益的“对外政策”上、“摇摆”出去。

首席评论员就指出，拉姆斯菲尔德的“抛出”的这番“中国威胁论”、显然就有如给小泉纯一郎打了一针“强心剂”、可以说在小泉纯一郎“最难受”的时候、布什“伸手”扶了他一把。


*** 白宫决策层“是否”已经决定、“现在”就将“中国威胁论”正式抛出来?

然而，大家也许已经注意到了，我们在上述分析中、也一再怀疑拉姆斯菲尔德的“这番话”“是否”代表美国的“正式政策”，也就是说，白宫决策层“是否”已经决定、“现在”就将“中国威胁论”作为美国的“国家政策”正式抛出来。

在东方评论员看来，我们之所以如此地“一再怀疑”，并非认为华盛顿“不想”抛出来，而在于站在华盛顿的立场来看，如果在这个时候“正式确立”“中国威胁论”、并不能“最大限度地保障”美国的利益，显然，这是“绝对不符合”美国决策层的利已主义的。

为了更好的说明这个问题，我们再来看一段相关消息、之后，时事评论员将继续给出我们的意见。
《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 美防长澄清其中国扩充军力言论只是「观察」

【新加坡消息】第四届亚洲安全会议，星期日结束。美国国防部长拉姆斯菲尔德澄清他前一天指中国扩充军力的言论，只是提交国会报告中的一项「观察」。
参加第四届亚洲安全会议的各国代表，在星期日大会结束后，分别举行双边会谈加强合作。

美国国防部长拉姆斯菲尔德和澳大利亚国防部长希尔会面后，向记者澄清日前有关中国扩军的言论，说这只是提交国会报告中的一项观察。

美国国防部长拉姆斯菲尔德表示，这只是国会要求提交的报告所需的一项观察，这只是报告中一项简单的观察。至于我另外提到的是，〔中国〕增加部署看似和台湾地区有关，但这纯粹只是一项陈述。

希尔则表示，应该促请中国在反恐方面扮演更积极的角色。他说本星期稍后到中国访问时，会要求中国运用影响力，促使朝鲜重回六方会谈。拉姆斯菲尔德前一天也发表过类似的言论。而中国外交部响应说，中方坚决支持地区安全合作，任何指中国不愿意参加国际反恐的指控都是不公平和不准确的。




【时事点评】事实上，不论从什么角度上讲，拉姆斯菲尔德如此这般地“事后澄清”、将他前一天“猛烈攻击”中国扩充军力的极端言论，轻描淡写成“只是提交国会报告中的一项'观察'”，似乎充分证明了一点：那就是，拉姆斯菲尔德的事前的那场“猛烈攻击”、与事后的这场“百般狡辩”，都不过是华盛顿“预案中的两个环节”而已。



*** 华盛顿的决策层显然做了“精确的准备”

东方评论员认为，拉姆斯菲尔德在抛出这一番理论之前，华盛顿的决策层显然做了“精确的准备”。

我们还记得，就在5月31日，我们曾经重点点评过布什的一番讲话，在我们看来，布什当天在白宫新闻发布会上针对中美关系做了“最新的表态”，可以说其中已经“暗含”了拉姆斯菲尔德今天的某种做法。



*** 布什的“单项处理”、是个“老得掉牙的老东西”

东方评论员注意到，布什对中美关系是这样评价的，他说：“我认为中美关系非常复杂，美国人民也应该这么看……我们应该把中国看作经济上的机会......中美关系很难简单地说是竞争对手或者伙伴.........最好的处理方式就是'单项处理'。”

显然，布什所谓的“单项处理”、已经将中美关系“今后将何去何从”说得非常清楚了，如果说得再通俗一点，那就是，“生意上的事情要做、因为布什认为应该把中国看作经济上的机会”、而“围堵中国的事情也要做”、因为布什觉得“最好的处理方式就是'单项处理'”。

东方评论员认为，不难看出按照布什“单项处理”的“新观点”，那么，“中国威胁论”美国也“并非是不想提”、而是“不能提”。

在我们看来，布什的“单项处理”、表现上看似“新观点”，其实，却是个老得掉牙的老东西，说到底、就是华盛顿这些年来“一直在坚决贯彻之”的对华遏制政策。



*** 与小泉纯一郎一直“暗中满意”的“政冷经热”是一路货色

事实上，首席评论员就指出，布什的“单项处理”、其实与小泉纯一郎一直“暗中满意”的“政冷经热”是一路货色。在我们看来，日本不过是一个借助美国起着地区性作用的力量，日本在亚洲之外的地方、其政治、军事影响非常有限。因此，中国在与日本处于“政治冷淡”的同时，由于日本并没有能力、从根本上去影响中国在亚洲之外的战略利益，因此，中国和日本之间倒还也能维持一段“政冷经热”的时光。


*** 美国与日本可以说有着本质上的不同

而在这一点上，美国与日本可以说有着本质上的不同，因为美国的国家利益在全球各地，而中国国家利益的视野、也随着中国综合国力的提升、也在着眼于全球布局：从东亚、到中亚、再到中东、以及美国的后院南美洲、因此，尽管北京现在无力在全球范围内与美国全面地“公开对垒”、但却绝对有能力“集中一点、或者数点”、去影响、甚至破坏华盛顿的全球战略。


*** 中美间没有什么”政冷经热”的基础


因此，对华盛顿的决策层而言，既然中日间的“政冷经热”、就已经让华盛顿“坐收了不少渔利”，那么，从中国、日本今天“都已经处于”一种眼见美国人“收割利益”、也“只好相互间硬顶着”的处境来看，可以肯定的是，华盛顿如果依据“中国威胁论”的论调而对中国采取强硬遏阻政策，就算是勉强做到了中美间的“政冷经热”，也必然是个“伤人又害己”的结果，明眼人都能看出，一旦中美两大强权处于“公开对立”、那么，不论是欧洲、还是俄罗斯，或者是日本，都将因中美的“政冷”而“受益非浅”。

然而，中美间做得到“政冷经热”吗？东方评论员认为，由于中国在海外、特别是南美洲、中东和中亚的影响，目前主要还是在靠经济和政治影响力来进行拓展的，因此，一旦中美“正式对立”，那么，美国要想阻止中国在世界的影响，想全面遏制中国、其破坏性将不可避免地、“迅速渗入”经济领域。所以，在东方评论员看来，今后，中美间没有什么”政冷经热”的基础。


*** 中国是承受不起，然而，我们也看不出美国有承受能力


显见，如果华盛顿现在就正式抛出“中国威胁论”、并像日本那样、将作为其基本国策加以实行，在国家安全的问题上挑畔中国、将必然导致“中美”的“正式公开对立”、也必然会从根本上破坏中美间的“经济关系”。对此，中国是承受不起，然而，我们也看不出美国有承受能力。

也正因如此，也让我们看到了如下的一幕：美国防部长拉姆斯菲尔德4日在亚洲安全大会上说，“由于没有一个国家在威胁中国，人们奇怪(中国)为什么要增军费”和购买武器。

而就在同一场合，中国外交部亚洲司司长崔天凯当即质问拉氏说，“你真的相信中国没有受到世界任何地方的任何威胁？你真的相信美国受到所谓中国崛起的威胁？”。




*** 崔天凯的“当即质问”可谓是“直达要害”，

东方评论员注意到，美国的这位“向来以不喜欢讲外交辞令”而著称的拉姆斯菲尔德、其回答也一如既往地“问什么答什么”，对崔天凯的第一个问题，他说：“他不知道有任何国家在威胁中国”，而对崔天凯的第二个问题，拉姆斯菲尔德回答得同样干脆：“答案是，不，我们不觉得因中国崛起而受到威胁”。

显然，在我们看来，崔天凯的“当即质问”可谓是“直达要害”，即，如果如果华盛顿“有意”和日本一样、正式提出“中国威胁论”，并将其确立为自己的国家政策而加以实行的话，那么，也就得一如日本那样，公开地承认一个前提：象日本认为中国威胁日本那样、承认中国威胁的美国。



*** 拉姆斯菲尔德的这番“猛烈攻击”的底牌，就这样被崔天凯给掀了

首席评论员认为，我们不知道崔天凯是否“早有准备”，如果是早有准备，那就另说；如果是“临时发问”，那么，在我们看来，这个直达要害的“即时提问”足以显示此人“机警与功底不凡”。

另外，从拉姆斯菲尔德的回答可以看出，不论华盛顿保守主义者心里如何想，起码，直到目前为止，他们是不愿意公开承认“中国威胁论”这一点的，这就是说，不论是“中国威胁美国”也好、还是“美国威胁了中国”也罢，华盛顿都不愿意明确承认，如此一来，拉姆斯菲尔德的这番“猛烈攻击”的底牌，就这样被崔天凯给掀了，即，不过是“摆摆样子”而已。对此，日本人恐怕心里“很不受用”。



*** 这位“向来只知道强硬的老头”为何不愿意“真诚面对”“中国威胁论”？

在我们看来，既然拉姆斯菲尔德这位“向来只知道强硬的老头”也不愿意“真诚面对”“中国威胁论”、这就说明，华盛顿离正式提出“中国威胁论”或许还有许多事情没有准备好，在东方评论员看来，华盛顿没有准备好的事情里面，最重要的一条就是日本还没有与中国“彻底决裂”，中日关系“冷”虽然是“冷到了极点”，但离“破裂”还有本质区别。




*** 日本“捎带的这些私货”、明显有“冲撞美国东亚战略”的痕迹

之前的点评中，我们一再强调一个观点，那就是，日本在这一轮与中国的“明争暗斗”中、实际上借华盛顿希望日本在钓鱼岛、东海主权问题上挑畔中国之便、顺手将韩国的独岛、朝核问题等、可以“为日本带来好处的私货”都给捎带上了。

站在华盛顿的立场来看，日本“捎带的这些私货”、明显有“冲撞美国东亚战略”的痕迹，结果是“美韩军事同盟”的“牢固度”、已经被日本右翼“给稀释了”。




*** 美国东亚战略、日本的内心深处都“浸透了”“两面性”

在东方评论员看来，日本之所以敢“冲撞美国东亚战略”、就在于中日关系之间还有个“政冷经热”、这样，中日关系也就“还有一线生机”，而现行的美国东亚战略“浸透了”“两面性”：虽然有“借日本、台湾遏制中国”这关键的一面，但是，借中国压制日本的因素，也一样的关键和不可或缺。

显然，在日本政府的“内心深处”，也充斥着“两面性”：即如果难借美国倚重自己的战略时机，促使中美关系也“公开对立”起来，那么，自己不仅可以摆脱中美联手压制的“东亚安全”的既有格局，也可实现“政治、军事大国”道路上的实质性突破，还可以为自己日后主动调整中日关系奠定坚实的基础。




*** “中国威胁论”日本可以提，而华盛顿则不可以提

可问题是，北京会在历史问题、这个“大是大非”的问题上让步吗？如果不会，那么，那就只有日本自己找台阶下了，不然，在北京一再强调“历史问题”是改善关系的前提条件的时候，日本又拿什么去改善中日关系？

当然了，日本还有一条路可走，那就是让中美先公开对立起来，只要做到了这一点，那么，即使是中日政治关系改善不了，但做为一个可以满意的底线，保持住中日“经济热度”还是可能的。

显然，中美间由于彼此都在着眼于全球利益、而彼此之外还有欧洲和俄罗斯也在虎视耽耽、加上台湾问题、中东问题、朝核问题、甚至还有个日本问题，中美这些在“战略上的冲突与合作”，注定北京和华盛顿之间断没有“政冷经热”这一说。也说是说，“中国威胁论”日本可以提，而华盛顿则不可以提。

从这里面我们就不难看出，为什么美国人“创造了”并宣传了“中国威胁论”，而“第一个使用者”却是日本人的深层原因了。




*** 华盛顿是“不可能让”中美关系先于中日关系“彻底破裂”之前破裂的

可以肯定的是，一旦华盛顿正式提出，“中国威胁论”，并将其落实，那么，日本的、让中美先对立起来的战略目的也就达到了。之前，我们曾经提出过一个观点，即，华盛顿是“不可能让”中美关系先于中日关系“彻底破裂”之前破裂的。

因此，在东方评论员看来，拉姆斯菲尔德在这次亚洲安全会议上如此这般地攻击中国军事政策、并暗示“中国威胁论”，除了是在以这种“非正式的”、却绝对是挑衅式的方式、用“中国威胁论”试试中国、日本和亚洲国家的反应之外、更大的目的，恐怕在于对已经陷于困境中的小泉纯一郎“以某种声援”，是对北京“打狗给主人看”的一种“反击”，从而拉着小泉纯一郎在“内外交困”的时候、再坚持一会：一来，华盛顿希望中日关系彻底破裂，二来，就算是中日关系后来有所该善，华盛顿也得利用这段“中日对抗的大好时机”、尽可能地渔利。

在东方评论员看来，华盛顿似乎认为最好的渔利机会已经到了，这就是朝核问题，事实上，拉姆斯菲尔德在说了一通“中国威胁”之后、自己竟然就“最后总结”说：“目前朝核问题是美国最大的威胁！”看来，华盛顿的决策层还是非常清楚自己能够做些什么、自己应该做些什么的！

在一段新闻之后，东方评论员将在今天朝核问题的讨论中，结合朝核问题的最新进展，继续对“中美日”间在新加坡的这番“点到为止”的交手展开我们的观点。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
