# -*- org -*-

# Time-stamp: <2011-08-04 00:02:50 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 2005年6月24日 星期五

** 格林斯潘和美财长作证：制裁中国无益美国

【华盛顿消息】美国联邦储备委员会主席艾伦·格林斯潘和财政部长约翰·斯诺23日在国会表示，对中国实施贸易制裁并不符合美国自身的利益，诉诸保护主义反而可能降低美国民众的生活水准。

他们同时警告说，如果对中国进口产品增收关税，世界经济将受到“极为消极”影响。

背景：两议员抛出法案

在制造业利益集团的推动下，美国国会已经提出一系列要求对中国进口商品增收关税的提案。近期，两名美国参议员抛出了所谓的《中国自由贸易法案》，要求中国在两年内改革现行的固定汇率制度，否则便将对中国进口商品征收27.5％的关税。

美国参议院财政委员会23日就美中经济关系举行听证会时，格林斯潘和斯诺均表示，征收高额关税对国际金融体系而言弊大于利。

作证：缺乏证据后果消极

格林斯潘对这种保护主义做法提出严重警告说：“回归保护主义将对全球生活水准的持续显著提高构成威胁，而且以美国最甚，这主要是因为二战后全球市场的开放。”

他说：“据我判断，如果该法案得以实施，后果将极为消极。”

格林斯潘说，部分观察人士“错误以为”人民币对美元汇率的大幅上升将会显著改善美国的制造业和就业形势。这些人声称，由于美中现行货币汇率过低，美国因此失去了成千上万的就业机会。

格林斯潘指出：“我不知道是否存在任何可靠证据来支持这一结论……如果有的话，也仅有极少数就业机会能够得到保护。”

格林斯潘和斯诺建议国会保持耐心，因为汇率改革关系到中国自身利益。格林斯潘表示，中国正在日益成为世界贸易大国，更具弹性的货币“将有助于中国的经济稳定”，从而惠及世界。

他认为，中国将会适时进行改革，而实行制裁措施只会适得其反。

关于美中贸易逆差问题，格林斯潘说：“总体而言，美中双边贸易逆差的扩大，大抵取代了美国与包括日本在内的其他亚洲经济体逆差的扩大。”

格林斯潘表示，实行贸易制裁系“误导之举”，将“毁坏全球贸易体系”，最终必将损害“所有美国求职者以及数百万美国消费者”的利益。




【时事点评】在东方经济评论员看来，作为掌握美国经济大局的美联储主席格林斯潘、和美财政部长斯诺同时在美国会表示“反对对中国实施贸易制裁”、是不同寻常的。

请大家注意这一段，原文是，格林斯潘表示，实行贸易制裁系“误导之举”，将“毁坏全球贸易体系”，最终必将损害“所有美国求职者以及数百万美国消费者”的利益。

*** 中美纺织品争端、可能已经濒临贸易战边缘

之前、我们曾经说过，中美有关纺织品的争端，由于夹杂了太多的政治因素，很有可能会在中美开打贸易战争、或者濒临贸易战的情况下、才会峰回路转。

东方经济评论员就认为，格林斯潘今天将对华实行贸易制裁称之为“误导之举”，并担心这将“毁坏全球贸易体系”，不仅没有减低解决中美纺织品争端的难度，相反，这更加说明、与中欧纺织品争端有本质不同、“夹杂了太多的政治因素”的中美纺织品争端、可能已经濒临贸易战边缘。


*** 格林斯潘说了几句大实话

在我们看来，不论是中美纺织品争端，还是华盛顿压中国人民币升值，这本身与中美经济层面的因素没有太大的关系。东方经济评论员认为，格林斯潘在今天的“作证”中，非常清楚地承认了这么几个观点：第一，征收高额关税对国际金融体系而言弊大于利；第二，人民币升值不会显著改善美国的制造业和就业形势；第三，美中双边贸易逆差的扩大，大抵取代了美国与包括日本在内的其他亚洲经济体逆差的扩大；第四，对华实行贸易制裁系“误导之举”，将“毁坏全球贸易体系”，并损害美国利益。

在经济评论员看来，格林斯潘说了几句大实话，其中，以第一句，即“征收高额关税对国际金融体系而言弊大于利”这一句“最为实在”。


*** 在经济上，是“环球是同此凉热”

我们知道，前些日子，北京说要调控经济，抽紧银根，于是乎，全球股市是应声而跌：近一点儿的，香港、台湾股市跌、远一点的东京、整个亚洲股市跌，甚至与中国隔着太平洋的美国股市也跌、远在万里之外的欧洲股市同样也是跌，总之一句话，“环球是同此凉热”、“无一幸免”。

东方经济评论员认为，之所以出现这种情况，就在于欧美的资本、产品大量进入了中国，而中国的产品和资金也大量进入了欧美的经济活动之中，别的不说，在经济上，中欧美之间可以说是“同进同退”。


*** 危险的美国房地产和美国金融体系

特别是眼前，以美国为例，美国的经济可以说是在依靠房地产撑着，而美国的金融业为了利润，现在已经大大放松了客户信用标准，其贷款优惠条件甚至到了五年内不用还本、只付利息的地步。

最为奇怪的是，尽管美国联储不断调升短期利率，但是，美国用于购房的30年期抵押贷款利率这一长期利率是不升反降，这又进一步促进了美国人举债购置房产的热情、这些都令美国房地产业是一片“欣欣向荣”的景象。

然而，在我们看来，美国近年来房地产的繁荣、其实是靠低住宅抵押贷款利率维持的。东方经济评论员就认为，美国许多地方房租与购房付月供差距拉大、买房用于投资的多于买房用于居住，大量的投资者在购买房产，在许多地方，投机者占到了25%的比例，还有，就是在过去的7年里，美国房价涨幅高达56%，这是一个非常危险的数字。在我们看来，这些现象都是泡沫的信号。

在东方经济评论员看来，如果长期利率稍有风吹草动、就会引发危险，使这个泡沫破裂、从而严重影响美国金融体系。


*** 格林斯潘所担心的“国际金融体系”，其实就是指美国金融体系


众所周知，上世纪90年代中期，格林斯潘就指出美国股市存在“非理性繁荣”，后来美国股市“泡沫”的破灭证明了他的远见。事实上，这一次，我们的判断在格林斯潘那里找到了共鸣，在格林斯潘的眼里，美国房地产在许多地方已经存在泡沫，这种语言与警告，与2000年美国股市崩盘前，格林斯潘发出股市泡沫警告如出一辙。

经济评论员的观点是，显然，格林斯潘今天所说的“（对华）征收高额关税对国际金融体系而言弊大于利”，其中的“国际金融体系”，其实就是指美国金融体系，因为现在这套“国际金融体系”，不仅是按美国标准打造的，更是以美国金融体系为主体来运转的。


*** 富有经验的格林斯潘显然看到了巨大的危险

在东方经济评论员看来，富有经验的格林斯潘显然看到了巨大的危险，这种危险就在于一旦中美经济关系受到重大打击，将迅速扩散到美国金融体系，其中，按最保守的估计，中国将不再有庞大的贸易顺差、那么，中国也就不可能象今天这样、以近2000亿美元的规模、去购买美国国债、从而美国长期利率就有可能迅速攀升，从而让美国房地产贷款利率迅速攀升，迅速加大美国贷款购房者的债务负担，并有可能迫使许多投机房产者破产、刺破美国房地产泡沫，从而完成将损失扩散到美国金融体系的过程。


*** 美国抛出《中国自由贸易法案》，本质上就是中美间政治、军事角力的一种延伸

东方评论员认为，通过上面的分析，我们也就不难看出，美国抛出所谓的《中国自由贸易法案》，要求中国在两年内改革现行的固定汇率制度，否则便将对中国进口商品征收27.5％的关税的做法，说白了，是美国有一批人、想借此达成凭借其政治、军事力量也无法达成的、遏制中国的政治目的。

显然，在东方评论员看来，这本质上就是中美间政治、军事角力的一种延伸。


*** 不论大国之间如何斗，都不可能是当年苏美间的那种“只有对抗没有合作”的模式

首席评论员指出，现在的情况是，不论“中美”之间、或者“中美欧俄”之间如何斗，都不可能是当年苏美两大集团间的那种“只有对抗没有合作”的模式。

众所周知，当年美苏争霸，分别建立了北约和华约两大集团。事实上，许多人在看北约和华约“博奕”的时候，都是在政治、军事上去分析彼此的“你得我失”的，这也难怪，因为两集团间在经济上、几乎就是彼此贫富、相互独立的。


*** 美苏“通过冷战进行争霸”，其实有一个非常鲜明的特点

因此，在东方评论员看来，当年的美苏“通过冷战进行争霸”，其实有一个非常鲜明的特点，那就是，那种争霸不仅是两个“相互对立”的政治、军事体系的争霸，也是两个“相对独立”的经济体系的争霸，其结果是，美苏在政治、军事上尽管在激烈争夺、但是，美苏决策层却几乎不用过多考虑“这种争夺”会对彼此经济的正常运转、会造成何种重大影响。


*** 比较冷战时期的情况而言，目前的国际角力、有三个最大的不同

然而，现在，中美间还算不上是全球争霸、充其量不过是在争夺亚洲主导权。然而，美国的利益却体现在全球各地，如此一来，华盛顿决策层面对的困难是，在它与中国争夺亚洲主导权的同时，欧洲、俄罗斯却在与它争夺着欧洲、中东、中亚事务的主导权。

因此，在东方评论员看来，比较冷战时期的情况而言，目前的国际角力、有三个最大的不同，第一，美国需要遏制的对手绝不是针对当时的苏联、或者化约一样，只有中国这一个对手，而是多家，其中，欧洲、俄罗斯、日本等、或是政治力量、或是军事力量、或是经济力量，都是华盛顿要“分别加以遏制”的对象。

我们知道、美国有位克普兰、是当今新保守派防御和外交政策智囊团的圈内学者，他的观点非常有代表性：即，中国崛起将成为世界强国，并将成为美国在经济和军事上的首要对手；不过，它将比前苏联更难应付，因此，美国军事势力必需从中东转移太平洋，并与亚洲各国建立新型盟友，共同制衡中国的强大。


*** 美国人敢将它在中东唯一占优的战略资源---军事力量、由中东转投太平洋吗？

然而，真实的情况是，美国的主要军事资源仍然陷在中东，不仅所获甚少，却又不愿意拔出来、按照上述观点行事，转投太平洋。为什么？

在东方评论员看来，原因有两条，第一，欧盟一体化虽然遇到挫折，但是，欧盟仍然在，没有垮，这次则结束的伊拉克问题国际会议上，华盛顿仍然是两手空空，这就很说明问题，说明欧盟为了自己的战略发展空间，在中东仍然在与中国、俄罗斯一起、共同阻击、并全力破坏美国的中东计划。

在这种情况下，美国人敢将它在中东唯一占优的战略资源---军事力量、由中东转投太平洋吗？



*** 所谓“与亚洲各国建立新型盟友，共同制衡中国的强大”不过是“吹牛”

第二，就是所谓的“与亚洲各国建立新型盟友，共同制衡中国的强大”，然而，据东方评论员所知，不久前，美国国务卿赖斯访问印度时，就曾以“新一代武器技术”为条件、企图游说印度参加它的反华联盟，但遭到拒绝。

结果是，印度不但认为没有这个必要，反而“更加亲近”中国和俄罗斯，事实证明，就在赖斯“不快”地离去后，中国总理访印度却取得了空前的成功、不仅与印度建立了战略伙伴关系、还与俄罗斯一起建立了“中印俄”伙伴关系。

印度不算，还有澳大利亚、韩国、菲律宾，这都是美国的传统军事盟友，现在似乎都在“将来可能的台海战争”中、与美国划清了界线。在东方评论员看来，美国新保守主义者的、所谓“与亚洲各国建立新型盟友，共同制衡中国的强大”不过是“吹牛”。


*** 美国和这几个需要对付的对手、在经济上的联系太紧密了

第二，站在华盛顿的角度去看，不论是对付来自中国的政治、军事上的挑战、还是对付来自欧洲政治、经济上的竞争、或者控制来自日本在经济领域的压力、华盛顿都心有顾忌，既美国和这几个需要对付的对手、在经济上的联系太紧密了。

特别是“中欧美日”这同家，可以说是相互互为彼此的“前一、二、三位”的贸易伙伴，这与当年美国同苏联争霸时、两家间的经济关系、几乎是“老死不相往来”的情景“截然不同”，

因此，在东方评论员看来，事实上华盛顿在与上述对手“争斗”的时候，除了得担心彼此间的“核摧毁”之外，还得担心彼此间的“在经济上也有可能同归于尽”。


*** 华盛顿为了保持超强的地位，把自己弄得“异常辛苦”

最后一点，也是非常值得强调的、那就是，正是有“这些可怕的后果”，美国现在要为了保持这个超强的地位，也就把自己弄得“异常辛苦”。

在东方评论员看来，特别是欧洲和日本，这在冷战时期，都是与美国一起对抗苏联的军事盟友、对抗华约的经济同盟。而现如今，却无一例外，都成了华盛顿需要在方方面面、加以认真对付的竞争对手，如此一来，华盛顿的政治、军事、经济等各方面的战略资源、就“被大大地牵制与分散了”。



*** 这种“冷角力”与“苏美冷战”也有一个根本的不同


另外，由于中、美、欧这三大经济体、在经济上相互依赖，其中、中国与欧美的经济大体上是互补，而欧美经济是彼此的“你中有我、我中有你”，还有，三者间的经贸总量巨大，在经济上可以说一荣俱荣，一损俱损。

因此，在华盛顿拿着台湾问题、北京拿着朝核问题、彼此相互在东亚对峙的时候，中欧俄和美国在中东对峙的时候、恐怕政治人物的“冷静与现实”、会让各方决策层尽可能地以一种类似“苏美冷战”的方式来进行“冷角力”。

然而，在东方评论员看来，这种“冷角力”与“苏美冷战”也有一个根本的不同，那就是、不仅有“苏美冷战”的“相互核毁灭”因素、还加进了“相互经济毁灭”的因素。


*** 美国新保守主义者似乎“不愿意面对现实”

因此，我们的观点是，卡普兰和其他新保守主义者一样，给我们的感觉是“仍然生活在一个过去的世界里”，幻想着仅凭借美国强大的军事力量作后盾，就可随时随地玩转地球、主宰世界。

然而，既然这些人喜欢这样想问题、并真诚地相信他们所说的，那么，美国为什么不早早地结束已经拖了两年之久的伊拉克战争呢？这些人又如何解释美国耗时两年有余，却拿不下一个被打得一无所有的伊拉克呢？

在东方评论员看来，不是不想，实为不能！如此一来，美国新保守主义者的、除“急功近利、爱走极端”之外，另一个特征可以说非常清晰地呈现在我们面前，那就是，根本就不愿意面对现实。


*** 在格林斯潘这些人经济学家眼里，“相互经济毁灭”的因素、其破坏力恐怕比核武器更令他们恐怖

对此，我们的建议是，既然现在大国间的争斗不仅仍然有冷战时代的“相互核毁灭”因素，还已然加入了“相互经济毁灭”的因素，那么，这些擅长在“相互核毁灭”下玩政治、军事角力的保守主义者，为何不去“请教”一下格林斯潘这一类的经济界人物呢？

事实上，在格林斯潘这些人眼里，“相互经济毁灭”的因素、其破坏力甚至比核武器更令他们恐怖，道理很简单，核武器是“硬杀伤”，在可以相互毁灭的时候，谁都不敢启用，因此，谁也没有为此担心过。



*** 美国有人企图用经济手段实现政治、军事手段都难以达成的战略目的

而“相互经济毁灭因素”可就不一样了，美国的经济危机的情形仍然是历历在目。而美国就有那么一批政治人物、想凭借美国是世界上经济最强的身份、去“试上一试”，试试能否用经济手段去实现政治、军事手段都难以达成的、遏制中国、打断中国经济发展的战略目标。

据我们所知，已经有美国国会议员公开叫嚣，要用汇率武器，让中国象日本那样，经济也倒退10年。



*** 中国这一代领导人非常务实，善于运用、敢于运用自己的实力

对此，东方评论员认为，恐怕北京也没有什么好办法，在关键问题上只能死拼。从而让美国知道“利与害”的人、为了美国自己的利益、去说服那些不知道“利害”的人，这远比中国单方面让步有效得多。

比如说人民币汇率，以中国目前这个金融体系，根本就承受不了人民币在两年内改革现行的固定汇率制度所带来的冲击。

在东方评论员看来，中国领导人是非常务实的，而这种“务实”可以说体现在两个方面，其一，中国这一代领导人善于认识自己的实力；其二，近几个月来的强硬外交表明，中国这一代领导人也善于运用、敢于运用自己的实力。


*** 既然中国金融体系承受不了这种冲击，那就请“国际金融体系”一起来承担好了


显然，对北京而言，如果美国人一定要将人民币汇率制与贸易制裁挂钩，那么，最好的办法只有一个，那就是既然我自己承受不了这种经济冲击，而美国又不肯让步，那就不妨打打贸易战，与此同时，也就顺便请你美国、甚至全世界、大家一起来承担风险好了，就顺便请格林斯潘所担心的、所谓的“国际金融体系”来一起承担风险好了。

不过，在东方评论员看来，好在贸易战这种东西是“看得见、也摸得着”的，也就是说，就算打起来了，大家还可以再坐下来谈。而不象核武器，扔出去就没得救了。

下面，我们将把关注的焦点转到国际期货投资。在一篇有关国际原油价格的分析之后，东方经济评论员、时事评论员将就这一波创历史记录的行情，从经济角度和政治背景上，分别给出我们的看法。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
