# -*- org -*-

# Time-stamp: <2011-08-04 13:20:51 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

#+STARTUP: indent

* 2005年5月31日 星期二

** 中日东海问题磋商未达成共识约定东京再议

【综合消息】最新消息称，中日两国有关东海天然气田探勘争议的磋商已于31日中午结束，双方在油气开发、海境问题上都没有达成共识，但同意尽早在东京展开下一轮磋商。

近期在东京举行第三轮东海磋商

中国外交部发言人孔泉31日在例行记者招待会上说，5月30日和31日，中日第二轮东海磋商在北京举行。中国外交部亚洲司司长崔天凯和日本外务省亚大局局长佐佐江贤一郎主持了此次磋商。双方在磋商中阐述了各自立场和主张，表达了各自关切，并就启动东海划界谈判，推进共同开发等问题深入交换了意见。

孔泉表示，中日双方一致认为应按照中日两国领导人雅加达会晤达成的共识，坚持通过对话，平等协商，妥善处理和解决东海问题。双方商定近期在东京举行第三轮东海磋商。

日本并无诚意共同开发

据日本消息人士指出，日方代表在会谈中要求中国停止开发东海天然气田并提供相关资料，但遭中方拒绝；在海境问题上，双方同意由具法律背景的人员成立工作小组进行讨论；此外，中方提案共同开发东海气田，日方表示在这种情况下不能接受，而日本政府会继续让日本私营公司竞投东海油气开发。

中国在东海油气资源问题上一直坚持“搁置争议，共同开发”的原则立场，早在去年6月就曾提议与日本联合开发东海天然气田，而日本一直对中国的提议表现出消极态度。今年4月13日，日本开始授权民间企业在东海钻探天然气，两国争执进一步升高。

而日本近来又表示愿与中方联合开发东海天然气田，但希望中国先停止开发，并要求中方提供有关东海油气田相关数据，又要求将整个东海作为联合开发海域，这遭到中方拒绝。

中方抗议日本挑衅

而早前，中国外交部发言人孔泉曾明确表示，对于中日在东海划界问题上存在的分歧，中方一贯主张双方通过外交谈判加以解决。日本开始办理一些企业东海油气试采手续的举措是对中国权益和国际关系准则的严重挑衅。中方已经向日方提出抗议，并且保留进一步做出反应的权力。

他说，中方希望中日双方都能够本着两国领导人雅加达会晤所达成的共识，通过对话，平等协商，积极探讨化解双方分歧的办法。

日官员表示应谨慎处理中日对立

另外，日本经济产业相中川昭一在31日的内阁会议后出席记者招待会，在谈到中日关系因东海油气田等问题而严重对立时表示：“有必要在意识到此事已受到全球瞩目的同时继续展开交涉”，强调了谨慎处理的重要性。

他还表示，“经济大国间发生对立冲突是不幸的，希望东海能成为友好之海。”

可能引发两国摩擦

其实，在此轮东海问题磋商之前，无论是相关专家还是媒体均预料，由于中日双方认知差距过大，会谈不大可能会有结果。

专家指出，由于中日两国政府在东海油气田划界问题认知差距过大，这次会谈结果产生结果的可能性极低，而是侧重交换意见，继续保持事务性接触。

据专家分析，如果要通过谈判解决东海争议，双方都要创造条件和气氛。中日双方都曾表示，要使东海成为友谊之海、合作之海。但在目前分歧比较严重的情况之下，双方应首先确定这一问题必须通过谈判解决，而谈判就需要双方各自作出让步。

专家并预测，如果两国间不能确定通过谈判解决东海问题的原则，日本的单方面行动还将可能会进一步升级，东海问题将有可能会引发两国间轻度摩擦，甚至是军事上的摩擦。

而早前，中国外交部发言人、新闻司副司长刘建超在向国内大学生演讲时亦提到，有关中日东海问题非常复杂，只靠一、两次谈判是无法解决的。



【时事点评】在东方评论员看来，连续两天的中日东海问题问题局级磋商今天已经结束，可以说“结果”有两个“不出媒体所料”，第一，双方在油气开发、海境问题上“都没有达成共识”；第二，一致同意“尽早在东京展开下一轮磋商”。

*** 这个时候才想着给周围国家、国际社会和日本国内做点工作，是不是晚了点？

我们注意到，“极右”的日本经济产业相中川昭一在今天的内阁会议后、就中日关系因东海油气田等问题而严重对立时表示：“有必要在意识到此事已受到全球瞩目的同时继续展开交涉”，并强调了“谨慎处理”的重要性。

然而，首席评论员指出，中川昭一所说的“此事已受到全球瞩目”的确不假，在我们看来，中日关系对东亚、全球的经济稳定与繁荣都具有重大影响，因此，如何在国际社会有个好印象，自然非常重要。

因此，在我们看来，在历史问题上、被北京揪住“靖国神社”、且已经被弄得狼狈不堪、并为亚洲国家和日本国内民众“群起而攻之”的小泉政府，在这个时候才想着给周围国家、国际社会和日本国内做点工作，是不是晚了点？

*** 东海问题的激化，就与这个中川昭一有很大的关系

事实上，东海问题的激化，就与这个中川昭一有很大的关系，据了解，中川昭一一向主张对中国持强硬态度，在出任日本经济产业大臣，负责经济产业和能源等问题之后，他立刻主张在东海专属经济区划界问题和能源开发问题上不向中国让步，甚至不惜与中国发生摩擦。

尽管如此，东方评论员认为，中日间在经历了吴仪“如期访问日本”、见了所有“应该见的人”、却独独不见小泉纯一郎这件事情之后，中川昭一在此强调“要谨慎处理”还是“值得欢迎”的。

在我们看来，他的这个“强调”、不过是说了句日本社会、国际社会都想听的漂亮话而已，在我们看来，小泉政府根本就无意去“谨慎处理”、显然，由于中国“在春晓气田正忙着开发”，而且“开发的地点”就是离日本单方面要求的中间线只有“五公里”远，如果按着日本方面的所谓“逻辑”，这根本就是在“抽日本经济区的海底资源”，而日方手上现在是一无资料、二无具体项目，可以说是只能在一边“干看着”。


*** 日本之所以提出在东海“中间划线”，有两重目的

当然，“干看着”的感受是不好受的，日本之所以提出在东海“中间划线”，有两重目的，一是眼红东海海面下的资源，据说除了有着“多少多少亿桶”的原油、天然气之外，还有“多少多少亿吨”的海底矿藏；二则是着眼于中日间的另一个有主权争端、具重大战略价值的钓鱼岛。

*** 所谓的“东海主权争端”之现状

因此，在我们看来，在这“两重目的”的支撑下、小泉政府是“不会”在东海问题上就这样安静下来的。然而，东方评论员认为，尽管小泉政府内心不愿意安静下来，但是，我们也必须看到，在现阶段，小泉手中可用的手段也非常有限。为了更好地说这个问题，我们不妨来看看所谓的“东海主权争端”之现状。


众所周知，日本国土狭小、资源贫乏，因此，有一点做得比较好，那就是一直都非常重视海权，相反，在这一点上，一来、当时中国的海上军事力量非常有限，二来，也是中国的海洋意识“一直比较淡薄”。事实上，直到上世纪70年代，也就是在联合国能源署宣布东海海底“可能储藏着大量的油气资源”之后，中国大陆和台湾，才开始重视“对东海宣示主权”的。

　事实上，中日间在东海问题的争端不仅仅是源于联合国的“上述宣布”，更是因《联合国海洋公约》的“两条内容”而激烈对立，就是说，中日海权之争其实就是《联合国海洋公约》中两条规定在东海实施之争。

我们知道，根据“海洋公约”规定，依国土海岸线延伸200海里的海域为该国的经济专属区。而东海最宽处仅360海里，自然产生了至少40平方海里的争议海域，中日两国在划定各自200海里专属经济区时无法避免地出现重叠。1982年，日本驻华使馆向当时的中国交通部递交了一份地图，这是日本第一次明确提出中日两国之间海域应当依据“中间线”原则划分。而这与中国所主张的依据“自然延伸”原则所划定的我方范围，里外里硬是差了“近三个浙江省”的面积。

对日本提出的这种“在争议海域中间划线，一国一半”的解决办法，立刻就被中方否决，因为中方的根据是《海洋公约》的另一条“大陆架”原则，而根据“大陆架自然延伸”原则，东海的大部分海域都是中国大陆架的自然延伸，冲绳海沟以西的全部海域都属于中国的经济专属区。

如此一来，两国在“海权划线的问题”上产生的矛盾，导致了今天中日两国“各持一辞”的现状。



*** 东海的“搁置争议、共同开发”方案，其实是南海解决方案的一份“拷贝”

据了解，在北京举行的围绕东海油气田开发的中日司长级磋商中，中方的提案，就是在日方“单方面”主张的“中间线”开始到冲绳海沟为止的区域进行共同开发。显然，根据“大陆架自然延伸”原则，中方主张的这一共同开发区域，已经做了让步，因为这一块海域原本就是属于中国的经济专属区。

因此，东方评论员认为，如此一来，北京在东海问题上所主张的“搁置争议、共同开发”，在“本质”上也就成了中国与菲律宾、越南等国达成的、在南海问题上“搁置争议、共同开发”之解决方案的一份“拷贝”。


*** 菲律宾和越南、在南海争端上先后采取了“现实的态度”

众所周知，菲律宾、越南与中国之间、分别就开发南海资源已经达成了“搁置争议、共同开发”的协议，而在此之前、他们之所以不愿意与中国达成“搁置争议、共同开发”的协议，就是想趁中美战略对峙的机会，趁各自在北京和华盛顿眼中都行情看涨之机、企图在南中国海从中国身上狠敲一笔。

然而，东方军事评论员认为，由于中国经济的迅猛发展，这两个国家事实上在经济上都在依靠中国经济的带动，再加上中国的海、空军战斗力这几年里有了跳跃式的提升，特别是随着新一代中国的潜艇和战斗轰炸机已经形成战斗力，它们所代表的军事突击力量、已经前出到第二岛链，在我们看来，这些实实在在的“现实变化”、再加上在一系列主权争端、中国已经以足够的事实证明了自己是“绝不会无原则让步”的客观事实，都促使菲律宾和越南这两个中国的邻国、在南海争端上先后采取了“现实的态度”：即


*** 这种“现实态度”可以说是“非常之现实”

在东方评论员看来，这种“现实态度”可以说是“非常之现实”：既然与中国间的主权问题在短期内根本就解决不了，而中国的综合实力、特别是军事实力又在迅猛提升，特别是华盛顿出于自身的战略考虑、在现阶段内，更多地只会躲在后面、去挑唆“堪用的棋子”去挑畔中国、意在让自己“伺机渔利”、根本就没有准备、也“不可能”亲自上阵去与中国“拼杀”。

因此，这些在华盛顿眼中“堪用的棋子”、也先后学着美国在伊战中的铁杆盟友--澳大利亚一样，在考虑到如果跟随华盛顿、明目张胆地遏制中国、不仅在国家安全利益上得不到切实地保障、“还得搭上”已经到手、或者可能到手的经济利益之后，这些所谓的“棋子国家”也开始“务实地”与美国为了自身利益而拼凑的、“第一解决不了自己的主权问题、第二也解决不了自己生计问题”的“遏制中国包围圈”保持了一定的距离。


*** 日本的对华政策实际上正处于一个调整的“关键期”

然而，从菲律宾和越南的情况来看，日本则是“别具一格”，不仅没有与美国的“遏制中国的包围圈”保持距离，反而靠得更近了。

东方评论员认为，日本对华政策的之所以表现得“咄咄逼人”，与日本军国主义固有的“军事扩张传统”有莫大的关系。在我们看来，日本的对华政策实际上正处于一个调整的“关键期”，或者说日本进入了一个新的“扩张躁动期”。

在我们看来，在日本的历史上，从丰田秀吉统一日本列岛起，日本就进入“第一次战略扩张”的躁动期，之后，日本有三次发兵朝鲜，但都是以失败而告终；第二次是从明治维新直到二战战败，可以说在将近８０年的时间里，几乎每一年、日本都没有停止过军事扩张的行动。

东方评论员认为，这期间，与中国有关的有甲午战争、日俄战争、九一八事变、七七事变等，都是日本搞军事扩张的一部分。

*** “成为大陆国家”的心理在日本是深深扎根的

我们认为，日本始终没有忘记要“向外扩张”，主要缘于它的岛国特点，岛国缺乏资源和战略空间，日本人不能满足于小岛生存，因此想摆脱岛国地位，成为大陆国家，根据我们的观察，这种“成为大陆国家”的心理在日本是深深扎根的、也正是在这种心理的驱动下，以至于在日本投降之前，日本人甚至喊出了“宁可放弃本土，也不放弃满洲”这句话。

当然，对外扩张在不同时期的表现形式不一样，二战后，日本主要通过经济手段达到扩张目的。但是，近些年来，中日力量对比出现变化，日本似乎是“第一次”开始担心自己在中日力量对比中处于下风，担心中国经济、特别是军事力量的强大削弱它的国际影响力，更担心中国统一台湾、从而彻底地切断了它“南下的生命线”。


*** 日本与菲律宾和越南有何不同

总之，在我们看来，日本与菲律宾和越南不同的是，由于它对亚洲、甚至是世界有战略野心，因此，日本人“对遏制中国有不亚于美国的战略需求”。因此，东方评论员认为，日本右翼主导下的这“新一轮扩张躁动”、本质上是与美国“遏制中国”之战略目标“紧紧联系在一起的”。

然而，就如我们在上面将菲律宾和越南归之为华盛顿一度认为“堪用的棋子”一样，日本在华盛顿决策层的眼里，不过是一枚“份量更重的、但却绝对堪用的棋子”。


*** 美国人看透了日本右翼有这一“本能的战略需求”

首席评论员就表示，这种“份量更重”主要表现在两个方面，一，日本的常规海空军军事力量和经济力量都很强；第二，也是最为关键的，那就是美国保守主义者看透了日本的保守主义者，既就是上面所说的“日本对遏制中国有着本能地战略需求”。

在我们看来，也正因为看透了日本右翼有这一“本能的战略需求”，因此，在华盛顿的眼里，日本是枚“绝对堪用的棋子”。东方评论员认为，只要美国人愿意，它就可以随时利用日本的“这一本能”、去利诱日本。

*** 美国人利诱日本人的情形，如同“主人”与“倔驴”

东方评论员认为，美国人利诱日本人的情形，就如同一个骑在驴背上的主人、在倔驴“走累了”、思考着是否要停下来的时候、就非常及时地掏出一根胡萝卜、绑在线上的，吊在倔驴的前面，从而让座下的倔驴、“眼前又为之一亮”、为了将胡萝卜吃到嘴里、就往前走。

然而，倔驴往前走一步，驴背上主人手上的胡萝卜也在“往前走一步”，结果是，“主人座下的倔驴”因为“自己的倔”而不停地往前赶路、结果却是始终无法吃到那颗“看起来馋，闻起来香”、且就在自己眼前不停晃悠的胡萝卜。

事实上，只要我们稍微总结一下，就不难发现，华盛顿手中的这一类让日本右翼这头倔驴“看起来馋，闻起来香、但就是吃不到嘴的胡萝卜”，可以说是“大把大把的”。

*** 华盛顿手中的胡萝卜、可以说就是在“漫天飞舞”

东方评论员认为，仅是近几个月来，这样的胡萝卜可以说就是在“漫天飞舞”，在我们看来，美国交替使用的“支持和反对”日本“争常”的手段是之，华盛顿决策层和美国学者先后抛出的、有将朝核问题引向东亚核竞赛之嫌的“韩国核武器计划”、也有“美国可以充许日本拥有核武器”这一类让日本右翼“看到了一步就可实现正常国家之希望的说法”、这些“都是之”。

再就是，我们注意到，华盛顿在需要日本加入国家导弹防御计划时，美国官方说曾经半公开地表示过“支持日本拥有对钓鱼岛的主权”。在东方评论员看来，当时，美国人的这席话，可以说真的是挠到了日本右翼的“痒痒肉”，这的确让日本人如获至宝！

但是，让日本人最后“咬牙切齿”的是，美国在初步达到目的之后，“这种说法”在去年3月份中日在7位保钓人士登上钓鱼岛的时候，也就终于有了结果，既、在日本抓了中国的7名保钓鱼人士，从而与中国公开对抗、而最渴望美国人公开表态支持日本的时候，华盛顿却又公开撂下了一句让日本政府脸面全无的话：“美国政府对钓鱼岛主权的立场、就是没有立场”，美国不仅在关键的时候“拒绝表现出立场”，而且，我们注意到，自那之后的一年多的时间里，“支持日本拥有对钓鱼岛的主权”这句话，美国人是从此“绝不再提”。

*** 美国保守主义者操纵起日本保守主义者来、可谓是“颇有心得”，而且是“屡试不爽”

显然，在我们看来，美国保守主义者操纵起日本保守主义者来、可谓是“颇有心得”，而且是“屡试不爽”，东方评论员认为，在与北京对奕的时候，华盛顿摆弄起“日本这枚棋子”来，之所以敢不时地、变着法耍弄“这颗、或者那颗胡萝卜”、在日本眼前晃来晃去、并出尔反尔、从不兑现，就在于“这颗、或者那颗胡萝卜”上面，都被美国决策层精心地涂抺上了“只要再往前面勇敢地走一步，日本就有希望成为普通国家”的“色调与气味”。


在东方评论员看来，在日本于东海挑畔中国的背后，华盛顿是脱不了干系的。而就在日本“在东海发难”的时候，就在去年7月份，当时还是白宫国家安全顾问的赖斯访华，以寻求中国帮助解决朝核问题、并同北京在台湾问题上“开诚布公”、以试图为布什的总统大选商量出一个好的竞选环境的时候，为了配合赖斯访华、给北京施加压力，华盛顿就开始放风“支持日本在与中国存在的东海主权争端中的立场”。

东方评论员注意到，华盛顿开始只是通过学者如此“放风”，除了那个强硬得如“茅坑里的石头”、对任何不顺从美国的国家都“又臭又硬”的助理国务聊博尔顿、当时曾经公开说过一次之外，美国也就“从不再提起”。


东方评论员认为，事实上，在日本，也有相当数量、相对明智的政治人物对日本右翼想搭乘美国“遏制中国的东风”、梦想一举成为“普通国家”的企图“非常不以为然”，在他们看来，华盛顿之所以在一系列重大问题上、一再出尔反尔、一再出卖日本的利益，是因为美国现政府的对外政策之根本任务就是维护“惟一超级大国”，即“美国帝国”的地位不受到任何势力的挑战。

显然，“这些势力”在华盛顿决策层的眼里、可不分是盟国、敌国还是非国家力量。因此，在他们看来，美国是不会容忍世界上唯一两次攻击过美国的国家（一次是二战中、在珍珠港用炸弹攻击、另一次是80年代、用商品攻击）--日本成为真正意义的大国、也就是日本右翼所幻想的“普通国家”的。

因此，在这些政治人物看来，日本一旦与中国为敌，将失去在中美间的战略回旋空间，从而不得不接受美国“更为牢固的控制”。显然，这种“更为牢固的控制”最终将会全面地损害日本的自身利益。也正是因为如此，这些人士主张从日本国家利益的角度出发，不去公开地与中国为敌。


*** 小泉在中日关系上“出牌越多”，反映出他在国内的“政治劣势越甚”


另外，就日本国内政治而言，小泉在国内的支持率一直在下降。在东方评论员看来，如果我们仅从日本国内政治的层面看，那么，小泉在中日关系上出牌越多，就越反映出他在国内的“政治劣势”。

东方评论员认为，小泉在日本国内还是“做了一点事的”，事实上，他实施的改革触动了一些人的利益，其中、值得强调的是，其邮政改革、农业改革触动的是自民党的政治地盘，反而使民主党的势力上升，总而言之，小泉纯一郎和他的自民党、在国内政治角力的游戏中、“日子”也一如日本在国际政治中一样--“很不好过”。

在我们看来，小泉如此这般的“屡屡出牌”，就是要触怒中国，让北京“提前接招”。东方评论员认为，毕竟日本民主党的上层是比较重视中日关系的，因此，小泉纯一郎和自民党“有心”挑动两国关系紧张程度升温，在我们看来，只有这样，反对党民主党内年轻气盛的保守派政治家也许会“一不留神地”跳出来，这就、就很可能造成该党的分裂。

*** 对小泉而言，只有两个选择，要么正视历史，要么就“制造一个更大的争议”

首席评论员就指出，由于历史问题，面对中日关系陷入的僵局，已经到了“不进则退”的境地，因此，在我们看来，对于小泉而言，他只有两个选择，要么正视历史，从而缓和两国关系；要么就是“制造一个更大的争议”，从而分担政府在历史问题上的压力。

不难看出，“东海能源问题”恰恰是一个日本普通老百姓都能“看得见、摸得着”的一根最敏感的神经。触动这根神经，日本社会的激烈反应会刺激媒体，媒体向政府施压，政府就在这个问题上有了“民意基础”


*** 小泉要借用“最大的外部威胁”、来攻击“最大的内部威胁”

首席评论员就指出，对小泉来讲，日本最大的外部威胁是中国，而就日本国内政治而言，最大的威胁可不是中国，而是民主党，因此，小泉要借用最大的外部威胁、来攻击最大的内部威胁，要用中国问题来对付民主党。

也就是在这些“综合背景”之下，小泉纯一郎是一个劲地在“靖国神社”问题、在台湾问题、在钓鱼岛主权、东海主权问题上，一再刺激北京。

*** 在这一阶段里，中国对日本的态度是“中国不生气，但措词很严厉”

事实上，如果我们认真回顾一下，就不难发现，就以今年的事情来说，可以说北京对小泉纯一郎的挑畔“一直保持着克制”，从日本挑选在中国大年初一这个敏感日子突然在钓鱼岛问题上发难、再到日本与美国签定涵盖台湾海峡的“美日新安保指针”，再就是之后的、一而在、再而三地在靖国神社、历史问题上大放撅词，由于这些挑畔严格来讲，都是“政治性的抽象问题”、也就是说这种“抽象的挑畔”“在短期内不可能改变什么”。

因此，中国的反击总是显得“有理有节”，在东方评论员看来，所谓的“有理”在于“坚持原则底线”、而绝不让步；而所谓的“有节”、则在于将反击的主要对象、仍然集中在幕后为日本撑腰的华盛顿身上、从而大体上对日本采取“不理不睬”的态度。

在东方评论员看来，在这一阶段里，中国对日本的“蓄意挑畔”，其态度只能用“中国不生气，但措词很严厉”来加以概括。

然而，这一切到了4月13日就全改变了。之前，我们多次强调一个观点，那就是，日本用以挑衅中国主权的“最激烈的手段”并不是在钓鱼岛，更不是什么“冲之鸟”，而恰恰就是在“东海主权”之争，在东方评论员看来，日本也正是于4月13日、在企图以向日本企业发放东海资源勘察许可证、并以准备来试探中国是否敢于“承受一个完全破裂的中日关系”的时候，而遭到中国“痛击”的。

*** 小泉彻底激怒北京、这一阶段“中国很生气，措词最严厉”

显然，与之前的挑畔手段相比，日本向日本企业发放东海资源勘察许可证、准备在中国大陆架上进行“勘探、开采”的行为，可以说第一次达到了目的：这一次可真是彻底激怒了北京。

东方评论员至今仍然记得中国外交部发言人秦刚在记者会上对日本发出的义正严辞的警告，警告日本“这是对中国国家主权的严重挑衅，中国将保留进一步做出反应的权利”，我们也更清楚地记得中国国务委员唐家旋强硬地表示“（日本）一旦如此，（中日关系）整个事情的性质就完全变了”。而且、也就是在中国政府发出这些警告之后，中国各地也立刻掀起了一波“抗议日本”的大游行，事实上，日本外相也正是在中国这种、从政府到民间的“严重警告声”中跑到北京来的、而小泉本人更是在这种“严重警告声”中“公开道歉”的。


东方评论员认为，到了这一阶段，中国对日本的“蓄意挑畔”，态度完全成了“中国很生气，措词最严厉”

*** 如果.....“什么样的坏结果”都有可能发生

在东方评论员看来，从4月13日到今天为止，中间所发生的事实表明：小泉纯一郎在东海问题上成功地激怒北京的同时，显然又没有想到北京会做出如此激烈地批应，从而在国际社会面前、突然暴露出了他的尴尬，即在拼命用东海问题激怒北京的同时，却并没有做好心理准备、从而也没有能力去承受“彻底激怒北京”的后果。

显然，在我们看来，北京在“将日本准备对日本企业发放勘察许可证”、“定性为”是“对中国主权的严重挑衅、并将保留进一步反应的权利”的政府行为之后，在唐家旋进一步警告“将使整个事情（中日关系）的性质完全变了”之后，可以想像的是，一旦日本政府敢让日本企业凭一纸日本政府发放的许可证、就擅自进入中国大陆架海域“进行相关作业”，那么，可以肯定的是，“什么样的坏结果”都有可能发生，在我们的判断中、爆发军事冲突也“绝非是不可能的”。


*** 对这唯一一条仍然“保持着对话气氛”的“对话管道”，中日似乎都在“有意呵护”

因此，在东海问题“已经具爆炸性”的危险下，在我们看来，由于中日间高层对话随着吴仪提前中止访日行程、实际上“已经全部中断”，事实上，不论是日本首相、还是日本外相“口中一再强调”的、“比什么都重要”的中日关系、目前几乎是靠着双方的“东海问题蹉商会议”来“暂时维持互动”的。

东方评论员认为，对中日间这唯一的一条、仍然“保持着对话气氛”的“对话管道”，中日双方似乎都在“有意呵护”。

在我们看来，这种“呵护心理”令人印象非常深刻，这从双方尽管在油气开发、海境问题上都没有达成共识，但却一致同意按照中日两国领导人雅加达会晤达成的共识，尽早在东京举行第三轮东海磋商，以求坚持通过对话，平等协商，妥善处理和解决东海问题一事中、就可以看出一二来。然而，在我们看来，双方“呵护”的“只是机会”而已，至于“机会”是否能转化为“结果”，起码在近期之内、根本就无法乐观！


我们认为，日本无意解决与邻国紧张关系的心态、其实从另外一件事情就可以看出。在前些天，东方评论员还“表扬”过小泉纯一郎，说他这次在挑衅北京的同时，并没有象以往那样同时去招惹韩国，然而，也就在吴仪中止访问的事情告一段落之后，这位老兄又是“老病复发”，这边在与中国在“中国的东海”谈着，那边又开始在“韩国的东海”（日本海）去动手动脚。显然，小泉纯一郎在全力突破靖国神社“这个突破口”未果、从而“原地转了一个圈”之后，目光似乎又落在了与“核竟赛”“沾亲带故”的朝核问题上，看来，小泉纯一郎仍然不打算放弃其“兴风作浪”、“寻觅时机”的内、外政策。

在了解了韩国、日本军事人员在独岛附近的“对峙”情况之后，东方评论员将把关注的目光投向朝鲜半岛、并继续今天的东亚部分。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
