# -*- org -*-

# Time-stamp: <2011-08-04 12:25:37 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 2005年8月15日  星期一



** 小泉就纪念日本战败60周年表示“真诚道歉”




【东京8月15日消息】日本首相小泉纯一郎１５日就纪念日本战败投降６０周年发表声明，重申日本对在第二次世界大战期间给亚洲国家人民带来的苦难表示“真诚的道歉”。

日本首相小泉纯一郎１５日在日本纪念战败投降６０周年之际发表声明，强调日本要对过去的殖民统治和侵略表示深切的反省和由衷的道歉，坚持走和平国家之路，同各国发展友好信赖关系。

声明表示，日本过去的殖民统治和侵略战争给很多国家，特别是亚洲各国的人民造成了巨大的伤害和痛苦。日本谦虚地接受这些历史事实，对此再次表示反省和由衷的道歉，并向在那次战争中所有的死难者表示深切的哀悼。

声明强调，日本国民由衷地追求世界和平，认为与一衣带水的中国和韩国等亚洲国家携手，一道努力维护和发展地区的和平十分重要。日本要正视过去，正确认识历史，和亚洲各国在相互理解和信赖的基础上建立面向未来的合作关系。

这份声明的内容是在当天举行的日本内阁会议上最后确定的。

小泉说，“我国通过殖民统治和侵略，给许多国家的人民，特别是亚洲国家的人民造成了巨大的损失和痛苦。”

他说，“我们谦恭地接受这些历史事实，再一次表示我们深切的痛悔和我们真诚的道歉。”

小泉说，“当我直面过去，正确对待历史时，我希望建立面向未来的建设性关系，这种关系将建立在相互理解和信任基础之上。”

早在今年4月，小泉在雅加达的亚非峰会上曾就日本发动第二次大战作出过道歉。



【时事点评】在东方评论员看来、尽管小泉纯一郎在巨大的压力下、终究没有敢在中国人民抗日战争胜利60周年纪念日、韩朝联合举行纪念的“光复日”、即“8月15日”这个极其敏感的日子、去参拜靖国神社。


*** 小泉在今天发表的声明中、有许多字眼是“如此地熟悉”

然而，我们也注意到，小泉在今天发表的声明中、有许多字眼是“如此地熟悉”。

首先，小泉说，“我国通过殖民统治和侵略，给许多国家的人民，特别是亚洲国家的人民造成了巨大的损失和痛苦。”此外，他还说，“我们谦恭地接受这些历史事实，再一次表示我们深切的痛悔和我们真诚的道歉。”

相信大家应该还记得，就在4月22日，在亚非首脑峰会上，小泉纯一郎就做出个“真诚的道歉”，且所用的正是上面的“这两句话”。


*** 日本政府的“真诚道歉”、恐怕这个世界上再没有几个人会去相信

结果又如何呢？在那之后的四个月的时间里，我们从来没有看到日本政府、哪怕是任何一点与“真诚的道歉”“相印证”的行动、有的却是日本政治人物公开要为“东京审判”翻案、有的是日本掌控教育的文部省大臣毫无廉耻地、竟然公开宣称遭受日军巨大伤害的亚洲慰安妇“应该感到光荣”、以及日本开始正式采用美化日本侵略历史的新历史教科书。

显然，在今天世界各地都在用各种方式纪念“日本投降”60周年的时候，前几天还一度在“8月15日参拜靖国神社”问题上“放探风气球”的小泉纯一郎、却又想以这几句“早就说过、却根本就不算数”的“陈词滥调”来表示日本政府的“真诚道歉”、恐怕这个世界上再没有几个人会去相信。

因此，在东方评论员看来，一个连“道歉”都无法让人相信是“真诚”的日本政府、又怎么可能让人相信它会去“面向未来”、一个“毫无信用”可言的小泉政府、又怎么可能让人相信它会“坚持走和平国家之路，同各国发展友好信赖关系”呢？

东方评论员认为，除了上述分析可以证明小泉纯一郎的所谓“真诚道歉”是一点也“不真诚”之外，围绕着“8月15日日本投降日”和“供奉甲级战犯的靖国神社”这两个关键词、就在小泉纯一郎表示“日本要正视过去，正确认识历史，和亚洲各国在相互理解和信赖的基础上建立面向未来的合作关系”的前后，小泉内阁就在继续做破坏“相互理解和信赖的”事情。


在我们继续讨论这一话题之前，请再来看一则消息。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com



** 日本经济产业大臣前首相桥本龙太郎参拜靖国神社



【东京8月14日消息】日本经济产业大臣中川昭一１４日上午参拜了供奉着１４名甲级战犯的靖国神社。中川是今年“８·１５”到来之际第一个参拜靖国神社的日本内阁大臣。

中川在参拜之后回答记者提问说，他是用自己的钱支付香火费的。他还说，原计划在８月１５日参拜，但明天有内阁会议，所以提前参拜了。关于是以公职身份还是私人身份参拜的问题，中川没有直接回答，只是说“我是现任内阁大臣”。１４日上午，日本前首相桥本龙太郎也参拜了靖国神社。




【时事点评】东方评论员注意到，在小泉内阁中、在中日东海油气田之争问题上“态度最为强硬”、“态度最为狂妄”的、就数这个“经济产业大臣”中川昭一了。

*** 小泉内阁就是要“恶心一下”中国、韩国

显然，在我们看来，作为日本首相、即内阁总理大臣，尽管小泉纯一郎本人没有在8月15日这个敏感时间去参拜靖国神社，但是，他内阁成员中最具代表性的“经济产业大臣”，却仍然赶在8月15日之前的一天去参拜靖国神社、不仅如此，从中川昭一所说的“原计划在８月１５日参拜，但明天有内阁会议，所以提前参拜了”，以及刻意强调“我是现任内阁大臣”这几句话中，就不难看出，这位在历史问题上、与中日东海争端中、态度都“一味地极其强硬”的日本高官，就是要拿“8月15日”这个日子、和“靖国神社”这个事情来刻意地“恶心一下”中国、韩国一下、“恶心”这两个正在以各种方式纪念抗日战争胜利60周年的邻国，“恶心一下”正在隆重纪念这段历史的亚洲人民、和世界人民的感情。



*** 小泉为自己不在8月15日参拜找的理由是“不想让日本人社会分裂”

不过，就如我们之前所说的，小泉纯一郎是否敢“冒天下之大不韪”在“日本投降日”正式参拜靖国神社、日本是否敢在东海油气田问题上进行军事冒险，都取决于亚洲国家、特别是北京能否尽一切力量压制住日本保守势力的冒险心理。

显然，就小泉纯一郎而言，尽管他为自己不在8月15日参拜找的理由是“不想让日本人社会分裂”，但是，谁都知道、如果不是北京在靖国神社问题上的极其强硬，小泉又怎么去担心参拜靖国神社会分裂日本社会呢？


*** 小泉对支持他的日本右翼“爽约”，显然是北京的“准备工作”起了作用

不难看出，小泉纯一郎在8月15日对支持他的日本右翼“爽约”，并再次在历史问题上表示“真诚的道歉”，显然是北京之前针对“小泉可能冒险在8月15日这个敏感日子参拜靖国神社”、针对日本保守势力有可能在东海问题、钓鱼岛问题挑起事端、所做的长期“准备工作”起了作用。

在东方评论员注意到，这种准备工作是准备应付中日有可能的、在政治、甚至军事上出现冲突的一系列动作。其中包括的中国海军军舰靠近钓鱼岛、也包括将中国最大的、排水量近3000吨、可以抵达世界任何海区、全天候执行“非军事任务”的、且有先进取证手段的“海巡船”投入东海海域海事巡查，更包括中国“借”台海战争、将为日本提供核保护伞的美国公开纳入中国核战略打击目标、从而一展自己的“有一战的决心与准备”。

然而，东方评论员认为，北京所施加的“这种压力”，都是外在的，是政治和军事层面的，因此，在我们看来，这种“外在的压力”小泉纯一郎可以感受到，小泉内阁的阁员可以感受到，日本的政治人物可以感受到，但是，没有经济层面的“外在压力”，日本社会是很难直接感受到，不仅“很难感受得到”、反而极容易为日本右翼所充分利用、被利用来挑动民粹主义、从而在日本民粹主义的掩护下、稍有风吹草动，就想办法唆使日本保守政府在东海经、钓鱼岛问题上进行政治、军事冒险。



*** 北京要警惕小泉仍然极有可能会孤注一掷

因此，在东方评论员看来，在小泉纯一郎“没有敢在今天拜鬼的背景下”，北京更要警惕、一旦小泉在外交（尽早摆脱外交孤立）、内政（赢得9月大选）上需要，仍然极有可能孤注一掷、在主权问题上、主动测试北京的战略底线。


*** 日本右翼的影响“张力”正在扩大

东方评论员注意到，小泉内阁中的环境大臣小池百合子、厚生劳动大臣尾辻秀久更是公然“在８月１５日参拜靖国神社”、在我们看来，他们这种公然的挑衅行为、与中川昭一所透露的、要在日本投降日去参拜靖国神社的“原有计划”、以及“劝说小泉纯一郎不要继续参拜靖国神社”的日本前首相、桥本龙太郎自己却跑去“参拜”、都已经清楚地表明、日本右翼的影响“张力”正在扩大，这表现在两个方面：第一，在日本、在不愿意正确认识历史的问题上、在日本政治人物中、“内心中”支持小泉纯一郎继续参拜的、不仅有中川昭一这种“不仅说、也要做”的“极端右翼势力”、也有桥本龙太郎这种“口是心非”的右倾政治势力。

据来自海外的报道，日本自民党内象中川昭一这种强硬人物，于今天（8月15日）这个敏感的日子参拜靖国神社者是“大有人在”：其中，被认为是小泉接班人的自民党干事长代理安倍晋三赶在国会议员集体参拜之前单独进入大殿参拜。随后，来自自民党和民主党的“大家参拜靖国神社国会议员之会”的23名前众议员、24名参议员以及83名代理人一同参拜。


*** 值得一提的两条

值得一提的有两条，首先，表面上看，今年去参拜的日本议员人数似乎少于去年(众参两院共58名议员以及99名代理人)，然而，在东方评论员看来，人数的减少并不能说明当前国会议员中反对参拜靖国神社的人增多了。

我们注意到，有日本的分析人士就认为，出现这一情况的“最直接原因”、就是在小泉解散众议院，大多数“前议员”都得为自己的位置而奔波、要赶回自己的选举区、为9月11日的竞选“提前准备”去了。


*** 日本民主党“党员”的“参拜激情”、似乎并不比其“母党”--自民党少多少

其次，就是脱胎于日本自民党的日本民主党、其议员在参拜靖国神社的问题上、在国际舆论的巨大压力下、他们所表现出来的“参拜激情”、似乎并不比其“母党”--自民党少多少，尽管身为“在野党”的日本民主党、正致力于赢得9月举行的大选、尽管民主党党首总是在公开抨击小泉纯一郎的“参拜”、公开声称一旦当选日本首相、“他将不会参拜靖国神社”。在东方评论员看来，日本民主党“党员”与他们的“领导”之间的这种强烈反差、这都是我们应该警惕的动向。


*** 从今天参拜靖国神社的日本民众的“人头数”、可数得出日本社会的“右倾度”来

另外，东方评论员也注意到，“今天”来参拜的普通民众数量大大超过了往年的任何时候、据日本方面的统计，总人数将达到创纪录的15万人。显然，在东方评论员看来，我们不难从今天参拜靖国神社的日本人的“人头数”上、就可以数得出日本社会的“右倾度”来。


*** 小泉纯一郎何以敢在国际社会的压力下“耍花腔”

我们认为，正是日本社会“已经有了这样的政治和社会基础”，小泉纯一郎也才敢在国际社会的压力下“耍花腔”：即一面沿袭了10年前“村山谈话”的基调，在“对外”的“广播稿”中、将所谓“真诚道歉”挂在嘴上；

而另一方面，小泉纯一郎却在精心地将“村山谈话”进行“挑挑捡捡”、“掐头去尾”，从而在“对内”的“宣传稿中、用“道歉”这两个字来为日本对那场“罪恶滔天的侵略战争”进行“轻描淡写”。


*** 在内内外外的巨大压力下，仅在今年，小泉已经是“两度”想起“村山讲话”了

事实上，就在今年之内，在内内外外的巨大压力下，算上这一次，小泉纯一郎已经是“两度”想起了日本前首相村山富市的“村山讲话”了。其中、在今年四月份，小泉纯一郎在中国有了“反日示威”后、为了与中国国家主席胡锦涛见上一面，就曾经想起过“讲话”，而且，在与胡锦涛会面时，小泉纯一郎还提出日本要延续“95年村山谈话”的承诺，然而，正是小泉纯一郎“事后的口是心非”的作法、让中国愤怒地招回了在日本访问的副总理吴仪、并取消了她与小泉会面而提前归国。

在东方评论员看来，既然这位小泉纯一郎先生忽然“又一次”想起了“十年前”发表的“村山谈话”，那么，东方评论员在这里也自然得和大家一起“再一次”回顾一下这个所谓的“村山谈话”。


*** 所谓的“村山谈话”

其实，所谓的“村山谈话”是在1995年，日本纪念战后50周年时，日本前任首相村山富市的一个谈话，村山当时表示“对于过去的殖民地统治和侵略造成的巨大损害和痛苦的历史事实诚恳接受，痛切反省和道歉。”

既然小泉“又一次”想起了十年前的这段历史，那么，东方评论员在这里也自然得和大家一起回顾一下这个所谓的“村山谈话”。其实，所谓的“村山谈话”是在1995年，日本纪念战后50周年时，日本前任首相村山富市的一个谈话，村山当时表示“对于过去的殖民地统治和侵略造成的巨大损害和痛苦的历史事实诚恳接受，痛切反省和道歉。”

实际上，根据我们的长期观察，“村山谈话”自十年前的世界反法西斯胜利50周年之际“问世”之后，其“积极的一面”就一直遭到日本右翼势力的强烈攻击，不仅如此，其“含糊的一面”更是经常被日本官员用来当历史问题“已经解决”的挡箭牌。


*** 小泉第一次“记起”“村山谈话”就是在他第一次以首相身份参拜靖国神社的时候

在东方评论员看来，小泉纯一郎自上台后，第一次“记起”“村山谈话”的时间就是在2001年，就是在小泉纯一郎于当年8月13日正式参拜靖国神社、并在参拜前为了降低他参拜靖国神社给当时尚好的中日关系带来的巨大冲击、在发表讲话中“口是心非地”刻意地引用了“村山谈话”的部分内容，也就是“基于错误的国策而进行了殖民统治和侵略”这一段。

据我们了解，在看到小泉纯一郎一边拿着自己讲话为参拜靖国神社做挡箭牌、一边又在那里“断章取意”、只提“日本已经道歉”的“前半截内容”、而扔掉“深刻反省和由衷道歉”的“后半截”之后，当时在大分市家中的村山前首相“顿时是大怒”：痛斥小泉说“既然引用了我的讲话，又为什么去参拜呢？”。


*** “村山谈话”在许多地方“含含糊糊”，给了日本右翼许多利用的空间

对此，首席评论员更是认为，日本保守势力在“利用”其“含糊的一面”方面、可以说简值到了“挖空心思”的地步。

在东方评论员看来，95年日本当时的首相村山富市发表的这个讲话，仍然在许多关键地方“含含糊糊”，这就给日本右翼许多利用的空间。比如：第一，村山当时在强调日本“殖民地统治和侵略”的时候，并未提及有关中国东北部地区或“满洲国”的字眼。因此日本右翼就“抓住这点”，充分地加以发挥、甚至给出了一个日本对“满洲国”的“荒谬见解”，那就是：既然中国、韩国都不反对“村山谈话”，那么由此可见“日本和满洲政府是一体的。


*** “道歉”的说法在日本人的眼里，对应的事情“算不了什么”的事情

第二，就是“道歉”的说法在日本人的眼里，其“对应的事情”属于“算不了什么”的事情。在东方评论员看来，事实上，许多日本人根本就是这样理解的，即，在中国、韩国认为有积极意义的“村山讲话”，不过是个日本“针对那段历史”认为有必要“痛切反省和道歉”的讲话，如此一来，日本在那场侵略战争中的“性质”、日本右翼就可以利用“道歉”这几个“日本字”去“模糊视听”。


*** 日本人的一句“口头禅”

在东方评论员看来，要知道，如果你看过任何日本的有关犯罪的报道，相信都会对日本人的一句“口头禅”有深刻地印象，那就是：受害者或其家属在电视画面上、或新闻报道中“针对罪犯的罪恶行径表达愤恨”的时候、绝对是说“他们连一点谢罪的意识都没有”。

在这里，东方评论员想提请大家注意的是：日本人在表达自己“对罪犯”愤恨之情的时候、用到的绝对是“谢罪”这两个字、根本就不是什么“道歉”所能包含的。


*** 应该用“谢罪”来表明立场“严重罪行”、理所当然地成了一个“只需要道歉”的“小事情”了

显然，久而久之，就在日本另界政府在口头上“道歉来、道歉去”的同时，一个本就应该用“谢罪”来表明立场的“日本侵略亚洲国家时所犯下严重罪行”、结果在日本社会的眼里、就理所当然地成了一个“只需要道歉”的“小事情”了。

既然如此，小泉纯一郎今天所谓的“真诚道歉”、就算就他说得“真诚无比”、可在日本人眼里、“道歉”两字又算得了什么呢


*** “道歉”这两个字眼，在外交场合，日本历届政府都又是“吝啬的可以”

然而，我们又发现一个奇怪的现象，那就是，对“道歉”这两个字眼，在外交场合，日本历届政府都又是“吝啬的可以”：其中，在中日建交的时候，日本的田中首相开始的说法是：对过去发生的不幸事件，对我国对中国人民添的麻烦，表示深深的反省。

对此，中国政府直接加以拒绝，这样，就有了后来的“订正版”，由大平外相正式表明：日本对过去对中国人民造成的损害，痛感到自己的责任，深刻反省。这是中日共同声明。

再就是92年的时候，日本天皇访华、他对日本的侵略历史、用的是“不幸的一段时期”和“深深的悲哀”来加以描绘的。

之后，就是95年，10年前的今天，在日本投降50周年的时候，日本村山首相的发表的这个“村山讲话”。在东方评论员看来，应该承认，95年日本当时的首相村山富市发表的这个讲话，虽然仍然在许多地方“含含糊糊”，但就较之日本“之前”与“之后”历届日本政府的态度而言，已经有了“很大的改进”。

*** 直到目前为止，日本政府从来不肯将“道歉”这两个字写入“书面外交文件”

其中，东方评论员认为，最值得肯定的一点就是，95年日方发表的“村山谈话”，算得上就日本政府首次承认对亚洲国家施行了“殖民统治和侵略”，并表示“深刻反省和由衷道歉”。也就是在这个基础上，1998年，签署了《日中联合宣言》和《日韩联合宣言》，日方也首次以书面形式承认对中国的侵略并“口头道歉”。

事实上，根据我们的观察，直到目前为止，日本政府从来不肯将“道歉”这两个字写入“书面外交文件”交给外国政府，显然，在我们看来，日本官方心里也是非常清楚：“道歉”在国际上的意义根本就等同于日本文字中的“谢罪”。



*** “长期诱导”日本社会逐渐进入历史问题“麻木阶段”的一种手段

因此，我们也就看到了日本人在搞什么“真诚道歉”的“奇怪方式”：即，一方面，日本政治人物可以一遍又一遍地将“道歉”这两个字挂在嘴边，一有外来压力，就可以脱口而出；

而另一方面，却从来不肯将“道歉”这两字写入书面外交文件。在东方评论员看来，日本历届政府持续出现的这种“口头”与“书面”“道歉”的“巨大反差”、表面上是日本人在玩文字游戏、但其本质原因就在于这本来就是日本政府用于“长期诱导”日本社会逐渐进入历史问题麻木阶段的一种手段。

在东方评论员看来，也正是如此，日本社会、甚至许多都堪称是日本友人的日本学者、政治人物都对中国提出了一个令人深思的问题，那就是，“日本已经道歉很多次了、中国为什么还要在历史问题上揪住不放”。显然，一个本应该以“谢罪”的态度来表明立场的”严重历史罪行”，在日本政府的长期操纵下、在日本社会眼里就这样一点点变成了“仅仅需要道歉就可以解决的小麻烦了”。

不难看出，将日本在侵略战争中对亚洲国家犯下的滔天罪行、说成是“麻烦”事一件，不就是日本政府长期以来所秉持的“错误历史观”吗？显然，对北京而言，在继续紧揪住日本历史问题不放的同时，是否可以考虑一下如何切实地破解日本保守势力的这种、意在通过“道歉”、反手去强化日本社会继续在历史问题近乎麻木的手段。


*** 北京应该直接要求日本政府以“谢罪”的用词来描述那段“罪恶历史”

在我们看来，起码在历史问题上，可以直接要求日本政府进行“谢罪”、以取代“正确面对历史”这种“没有明确意图”的外交语言、更不要再对日本政府的任何“道歉”去做什么积极评价：第一，按“国际定义”去理解日本政府的“道歉”、却有个“信用”问题；如果按“日本定义”去理解日本政府的“道歉”、那就根本就是日本政府在“刻意弱化”那段“罪恶历史”。

显然，北京只有直接要求日本政府以“谢罪”的用词来描述那段“罪恶历史”、才可以象不久前中国军方人士直接明确“中国准备核打击美国”、发出明确无误、不可辩解的“强烈信号”、引发美国社会对中美安全问题的一轮“急辩”、从而从深层次触动美国社会的“安全神经”那样，从外面去触发日本社会对“历史问题之性质”的“急辩”、从而从深层次地触动日本社会的“历史神经”


下面，是日本共同社的一则相关报道，在一起了解详细内容之后，东方评论员将继续就如何从深层次地触动日本社会的“历史神经”的问题、继续给出我们的观点。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
