# -*- org -*-

# Time-stamp: <2011-08-04 00:14:06 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 2005年6月15日 星期三

下面，我们将把关注的焦点集中在朝鲜半岛。今天，朝韩政府代表团参加了平壤的６．１５庆典，从新闻报道上看，庆典办得不错，双方还发表了一份“民族统一宣言”，然而，东方评论员注意到，在整个庆典中，韩朝双方显然在有意突出“经济合作”的意味，说实在的，时事评论员们最为关注的也就是这一点。

在一起了解了大概的情况之后，东方时事评论员、经济评论员将一起继续今天的东亚部分。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 朝韩发表民族统一宣言6.15定为“民族日”

【平壤消息】据联合通讯社报道，在平壤参加６．１５庆典的朝韩及海外民间代表团１５日共同发表了民族统一宣言，将６月１５日规定为民族之日，并呼吁消除核战争危险。朝韩政府代表团也参加了发表仪式。

当天，在平壤４．２５文化会馆举行的民族统一大会上，代表们发表了该宣言。宣言中称，朝鲜半岛南北沿着６．１５共同宣言开创的道路前进，共存共荣，以一个民族屹立于世界民族之林，这是全民族共同的心愿和意志。宣言还决定制定６．１５共同宣言发表纪念日（民族之日）。

宣言内容共五条，其中包括以下内容：履行６．１５共同宣言的基本途径是民族内部互助；消除核战争威胁，建立和平的世界；将６．１５共同委员会转变为广泛的统一爱国运动组织。

韩国筹委会常任代表白乐晴说，今年应成为带来和平与统一崭新局面的一年，应加强南北对话与合作，消除军事紧张，搞活部门与地区间的交流，并圆满举行８．１５共同活动等。

北方筹委会委员长安京浩表示，培养民族内部的强大力量，是维护和平的唯一选择。将在反战和平协作的最前线继续大力开展统一运动，粉碎国内外好战势力的战争图谋。

随后，代表们参观了纪念图片展。由朝韩共同提供的这１００幅图片，生动再现了南北铁路和公路连接、金刚山旅游、开城工业园区等６．１５共同宣言发表后发生的可喜变化。

由韩国统一部长官郑东泳率领的韩国政府代表团和朝鲜劳动党中央委员会秘书金基南率领的朝鲜政府代表团将于今天下午２点在平壤人民文化宫举行“６．１５南北政府共同活动”，以弘扬６·１５精神。

这是自朝鲜首脑２０００年发表６.１５共同宣言后，双方政府首次举行共同纪念活动。

另外，韩国政府代表团还计划在金基南于玉流馆主持的午宴上，品尝平壤冷面，与朝鲜代表进行两个多小时的坦诚交流。

代表团还将从下午５点３０分起在青年中央会馆观赏朝鲜文艺团体演出的民族歌剧《春香传》，而后于晚８点３０分出席由６.１５共同活动北方筹备委员会主持的纪念晚宴，祝愿实现和解、合作、和平。

当天下午，朝韩民间代表团计划举行各部门间的活动，讨论扩大交流事宜。

２９５名韩国民间代表团和４０名政府代表分别于１４日上午和下午乘民航包机抵达平壤，并与朝鲜及海外代表团在金日成体育场举行了统一大庆典开幕式，再次确认了切实履行６.１５共同宣言的意志。




【时事点评】稍早，也就是11日，卢武铉和布什在华盛顿举行双边会谈，当时，双方商定了一个结果，即：如果朝鲜放弃核武器，不仅保障朝鲜的体制安全，而且将积极推进朝－美关系改善。

*** 一年前，北京就明确指出华盛顿的要求“有问题”

如果我们仔细看一眼上述卢武铉与布什“商定”的“结果”，就不难发现，说字面上而言，我们并没有看到华盛顿的立场、“较一年以前”有任何的变化，即华盛顿仍然坚持朝鲜要彻底的、以可以得到证实的和不可逆转的方式拆除其核项目，之后才能谈所谓的“协议”与“好处”；

然而，东方评论员也记得，早在一年前，北京对此的态度也非常明确，即“这种要求有问题”。援引当时中国外交部副部长周文重的说法，那就是“美方坚持在美国同意提供任何好处之前要求朝鲜这样做是不合情理的”。


*** 布什没有诚意，是“六方会谈”中断一年的主要原因

对此，首席评论员就指出，一年前，华盛顿抛出的这一立场，其实就是在“有心”要以朝鲜“绝不能接受的条件”阻挡协议，但却拉了其它国家对朝核问题“共同负责”。在我们看来，布什在坚持“朝鲜先放弃核武，美国方再考虑予以安全保证及援助”是以“怕朝鲜食言”做为理由的，然而、在东方评论员看来，朝鲜又何尝不怕美国食言？

明眼人是一看便知，朝鲜如果食言（这种可能性相对较小），华盛顿自然可以撤销“安全保证”，以及停止经援，这似乎“非常简单”，但是，如果美国食言（这种可能性太大），那么，朝鲜已毁的核设施就恢复不了，所以，在我们看来，华盛顿的要求根本就站不住脚。

因此，东方评论员认为，如果各方有诚意“打破僵局”，那么，“唯一合理”的方案就是朝鲜毁核及美国承诺安全保证同时进行。然而，对这唯一合理的方案，朝鲜表示了同意，然而，华盛顿却加以了拒绝。显然，华盛顿在一年以前，根本就“没有诚意”解决朝核问题，东方评论员认为，这正是朝核问题“六方会谈”中断一年的主要原因。

*** 北京分明没有为自己“相信错了”而有任何的“不好意思”，

在我们看来，有一点值得强调，那就是，中美双方在“一年前”于朝核问题上的“对立”，是建立在北京对“华盛顿提出的朝鲜一直在试图通过浓缩铀来制造核武器的说法表示怀疑”之基础上的。

这就是说，直到去年6月份，尽管华盛顿抱出了一大堆的、无可辩解的强有力的证据、显示朝鲜的确拥有浓缩铀项目，然而，让华盛顿气愤的是，北京“不仅愿意相信”朝鲜没有核武器，甚至是一口拒绝“相信”朝鲜有“通过浓缩铀来制造核武器的能力”。

显然，朝鲜现在不仅“宣布自己有核”、并且“还在制造更多的核武器”，这足以证明“北京相信朝鲜”是“相信错了”，但是，在东方评论员看来，从中国对“朝鲜有核”从未加以批评的态度来看，北京分明没有为自己“相信错了”而有任何的“不好意思”，也没有任何改变“既有立场”的意思。


*** 近一年的“风云变幻”，相继演化出了几大历史性事件


显然，国际政治经过近一年的“风云变幻”，特别是中美之间在东亚的“交锋”、相继演化出了“反分裂国家法”、“美日涉台安保指针”、“朝鲜宣布有核”、“连宋先后登陆”几大历史性事件之后，中美在朝核问题上的“对立”更加尖锐了。

在东方评论员看来，这种“尖锐”就表现在有了明确“台独就是战争”的“反分裂国家法”后、事实上，在华盛顿的手中、现在已经没有了它打了几十年的“台湾牌”，而只剩下一张“不敢立刻就打”的“台独牌”；


*** “东亚核竞赛牌”的厉害之处在于两点

与此同时，在“朝鲜宣布有核”之后，北京手上也抓了一张“东亚核竞赛牌”。在东方评论员看来，“东亚核竞赛牌”的厉害之处在于两点，第一，在于它一旦打出去，事实上就将彻底颠覆整个东亚、以至亚洲的安全格局，在中国不得不面对一个全新的东亚格局的同时，也将迫使美国“提前调整”其东亚、亚洲以至全球战略、在很大程度上，美国将发现它需要重新定义“盟友”与“敌人”、重新进行战略资源的布署


*** 华盛顿显然没有做好“提前调整”的准备

我们认为，如果美国是被迫进行这种“提前调整”，那么，“这种提前调整”在波及面上将是广泛的、调整程度将是剧烈的、结果也将是不可预测的。东方评论员认为，在中东进程上“仍然不得要领的”华盛顿决策层、仍然在继续着拟定的、先拿下中东这个“制高点”、再站在这个“制高点”上“合纵连横、各个击破”的战略计划，显然没有做好这种在东亚方向“提前调整”的准备。不然的话，美国人恐怕已经将“台独牌”给打了出来、根本就不可能有“连宋登陆”这一出。


*** “两张牌”是都可以颠覆整个东亚局势、甚至极大地冲击全球现有格局

第二，“东亚核竞赛牌”的第二个厉害之处，则在于它在很大程度上、非常像美国手中挰着的那张、现在不敢立刻就打的“台独牌”，也就是说，着眼于自己的“利害相权”，着眼于自己的全球战略、在需要的时候，华盛顿可以伺机打出“台独牌”，而北京一样可以伺机打出“东亚核竞赛牌”。

在我们看来，这“两张牌”的最大相似之处，在于“拿牌的一方”虽然可以威胁对方，但都不敢轻易打出去，因为不论是谁，不论打什么牌，一旦迫不得已打出去、“两张牌”是都可以颠覆整个东亚局势、甚至极大地冲击全球现有格局的。

就目前而言，美国是现有世界格局的最大爱益者，就将来而言，美国今天所做的一切就是为了维护并深化这种最大受益者的“即得利益”。因此，在东方评论员看来，出于维护这种“即得利益”的本能，华盛顿对“这两张牌”所带来的冲击、都是在尽力地“防患于未然”。


*** 布什一边强调“美国反台独说话是算数的”，一点儿没耽误“台独牌”的准备工作

不难看出，自北京启动“反分裂国家法”之后，美国“连说带做”的“反台独”、就是意在“防患于未然”。

然而，首席评论员就指出，只要我们看看华盛顿是如何为对台军售“沤心沥血”的，看看华盛顿是如何全力拼凑“美日台军事同盟”的，我们就不难看出，布什一边强调自己“反台独说话是算数的同时”，可是一点儿都没有耽误“有朝一日”打“台独牌”的准备工作，



*** “以冷战思维和手法”处理东亚事务的美国人、最感头痛的地方

然而，在东方评论员看来，由于在台湾问题和朝核问题上，北京和华盛顿之间除了都有强硬手段之外，北京还有个经济手段，我们认为，这正是主要是“以冷战思维和手法”处理东亚事务、向亚洲国家兜售“中国军事威胁论”，并强拉别人参与遏制中国包围圈的美国人、最感头痛的地方。

两岸的经济交流、主动权在大陆这边。在东方评论员看来，所谓的“台湾意识”虽然“拒统”、但是，对“两岸三通”、发展经济却不抗拒，因此，我们认为，一旦实现“两岸全面三通”，两岸全面、深层地交流起来，那么，大陆也就立刻找到对台政治影响的着力点，到那时，华盛顿就是想操纵台湾民意、打“台独牌”恐怕就不太方便了。单纯地从“两岸经济整合”上看，时间不在美国人那边。

在朝鲜半岛经济整合的问题上，北京一样可以顺势而为、也有主动权。今天发表了“民族统一宣言”韩朝双方，在这一点上是依赖北京的，北京也有意参与其中，一句话，只要中国拉着韩国一起，迫使华盛顿不敢公开破坏朝鲜经济改革进程，那么，在朝鲜半岛经济整合的问题上，“时间也不在”美国人那一边。

然而，我们也认为，正是在上面两个方向上、时间都不在一心想遏制中国的华盛顿一边、因此，华盛顿决策层是不会那么轻易地、就让“这两种经济整合”走上正轨的。


*** 朝核问题上，华盛顿“立场”暂时没有变、但“态度”还是“有所变化”的


因此，从卢武铉与布什商定的最后结果来看，华盛顿的立场虽然没有变化，但是，美国解决朝核问题的态度却有了“很大的变化”。

东方评论员注意到，就在十几个小时前，美国六方会谈的谈判代表，助理国务卿希尔在美国会就朝鲜问题做证时称：布什政府对朝核问题有一个没有明说的期限，美国也将用尽一切办法解决朝核问题。希尔也表示，除非美国确定联合国安理会不会有成员国投否决票，否则美国不会将朝核问题送交安理会处理。

显然，希尔和这番话有两个重点，第一，希尔“做证”表示“布什政府对朝核问题有一个没有明说的期限”，这较之布什以前的“没有设定期限”、和自夸的“我是一个有耐心”的人，显然是“天壤之别”；


*** 真实的情况是，希尔“非常肯定”北京“会投否决票”

第二，希尔的这番话也是在暗示“不能确定”北京是否会“投否决票”。然而，谁都知道，如果没有北京因素，首先，朝核问题“不会拖成”今天这个局面，其次，朝核问题恐怕也拖不到今天。

因此，在东方评论员看来，真实的情况是，希尔的“不能确定”、恐怕早就“已经确定”、“非常肯定”北京会“投否决票”，所以、华盛顿这才不打算“将朝核问题送交安理会处理”。


*** 美国想象对待伊拉克那样孤立朝鲜的图谋已经走不通了

非常清楚，美国想象对待伊拉克那样，通过联合国发到国际社会“全面制裁朝鲜”、让朝鲜经济“再困难一点”，让朝鲜政权“再孤立一点”的图谋已经走不通了，这样，华盛顿似乎还有一条路，那就是尽可能地对朝鲜实施经济制裁。然而，种种情况表明，这条路似乎也没有多大的希望。

首先，还是北京因素。据我们手上的资料，直到2000年时，朝鲜的对外经贸中，中国和日本所占比例是“大体一致”。然而到了今天，中朝、朝日间的贸易差距已扩大到5.5倍：即，2004年朝日贸易额仅达2.5187亿美元，但朝中贸易额达到了13.8521亿美元。

值得注意的是，从3月1日起，日本积极配合华盛顿的意图、开始对朝鲜船舶进行了全面管制，开始试行的《船舶油浊损害赔偿保障法》是对进入日本港的100吨以上船舶要求必须加入责任险的法律。

但据我们了解，目前往来日本的朝鲜船舶中，只有2.5%加入了责任险，因此，该法律的试行，必然严重打击朝鲜对日本的出口。


*** 日本评估“贸易限制”的效果，觉得“非常乐观”

在东方评论员看来，日本此举，显然是想试图通过禁止朝鲜船只进港，阻止朝鲜对日本的出口、从而让朝鲜经济陷入更大的困难。据消息透露，日本有关方面、在评估单方面对朝鲜进行贸易限制的效果时，显得“非常乐观”，认为日本的制裁、最严重时，会使朝鲜国内生产总值(GDP)降低7%。

我们注意到，按日本官方的评估，那么，朝鲜的GDP推算为109亿~169亿美元，对日出口的完全停止，将使朝鲜遭到多达10亿美元的巨大损失，显然，这将极大地加重北京的负担。


*** 北京对朝鲜加大商业投资的一步是具战略意义的

事实上，华盛顿在“六方会谈”中，唯一可以搭把手的，也只有日本一家了。然而，东方评论员注意到，就在日本听着美国的话，对朝鲜挥舞经济大棒的时候，中国和韩国却反其道而行，纷纷加大了对朝鲜经济上的支持。

其中，中国是在“用实力说话”，据报道，北京不仅从政治上支持朝鲜，还加大了经济、军事援助，在东方评论员看来，最值得关注的是，中国还加大了对朝鲜的商业投资。

显然，对朝鲜加大商业投资的一步是具战略意义的，其性质与经援截然不同，我们认为，北京这是在行动告诉华盛顿，中国不仅要为朝鲜“输血”，还要为朝鲜“造血”，也就是说，在朝核问题的解决方案中，“经济制裁”与“军事解决”方案一样，其前景“根本就不灿烂”。


*** 对日本而言，一个后果就来了

最为重要的是，韩国出于自已国家、民族的长远利益，在看到中国“立场坚定地保护”朝鲜之后，也就有了回旋余地，从而也顶着美国的压力、加大了与朝鲜的经济往来。韩国的这些举动自然不会让华盛顿高兴，与北京的所做所为一样，这些都在很大程度上抵消了日本对朝鲜进行经济制裁的影响。

东方评论员认为，韩国与中国在朝核问题上的立场、都是以缓和并维护半岛局势稳定为目的的现实，事实上已经否决了华盛顿想通过“经济制裁朝鲜”，“换取”迅速解决朝核问题的可能性。

这样，对日本而言，一个后果就来了，那就是，如果日本长时间维持对朝鲜的经济制裁，那么，客观上，朝鲜只能“更加依靠中国”。对此，东方评论员注意到，日本内部已经有人担心：“用不了多久，日本就将会完全失去对朝鲜的经济影响力”。


*** 日本一味跟随美国外交政策“必结的恶果”

在东方评论员看来，日本内部的这种担心，其实“生动地体现了”日本一味跟随美国外交政策“必结的恶果”：那就是，由于日本“总是在考虑”美国的利益，而几乎从不考虑亚洲国家的利益，加上中日、韩日相继“交恶”，使得日本不论是在中美双方眼里、还是在朝核问题上、以及其它亚洲事务上、由于日本对外政策的少了回旋弹性、这样，在本质上讲，日本在亚洲事务上的影响力进一步降低了。

另外，东方评论员注意到，这种“恶果”反过来，又迫使小泉政府必须更紧地跟着布什、日本保守势力认为只有这样、才能体现出日本的重要性来。



*** 美国在朝鲜半岛的利益、其实与中国、韩国、日本甚至俄罗斯都是有根本区别的


可问题是，美国在朝鲜半岛的利益、其实与中国、韩国、日本甚至俄罗斯都是有根本区别的。在东方评论员看来，这些个“根本区别”，可以说主要体现在两个方面：

第一，就经济上而言，在东亚这一块，韩、日、美、俄、以及东盟、澳大利亚都与中国已经形成了一个相互依赖、错综复杂的“国际分工体系”。

也就是说，上述国家都能从一个稳定的朝鲜半岛获取经济利益。然而，在东方评论员看来，朝鲜半岛周边的几个邻国--中国、日本、俄罗斯，如果能利用能源、运输和建设项目、和朝鲜、韩国一道创建一个“一体化经济区”进行“多边努力”，那么，就很可能会给包括中国东北、日本、朝鲜半岛、俄罗斯远东地区的东北亚地区带来“长期和平”，并形成一个东北亚安全机制，从而有可能有效地避免朝鲜半岛爆发灾难性的事件。


*** 我们不难发现华盛顿的“尴尬”之处

从上述前景中，我们不难发现华盛顿的“尴尬”之处，即，如果东北亚这几个要市场有市场、要技术有技术、要资金有资金、且要军事实力有军事实力的国家、如果有朝一日经“朝鲜经济改革”而“整合在一起”，那么，华盛顿在这一地区的传统影响力“几乎”就将立刻被挤得干干净净了。

显然，一个本来可以“各得其利”的相互依赖、错综复杂的“国际分工体系”，当我们一加进美国的全球战略之后，就立刻发现，一个稳定的朝鲜半岛对华盛顿决策层而言，绝不是件什么“好事情”。

*** 似乎也很难指望朝核问题会有个“一劳永逸”的、“彻底的”解决方案

由于“东亚核竞赛”的危险是伴随朝核问题恶化而恶化的，加上北京在“反分裂国家法”划下红线之后，北京的“东亚政策”中、“对台政策”事实上已经成了在“加快军事准备、严阵以待”的强硬政策基础上、中国愿意与美国“努力实现”一个同时保持“稳定的台海局势”和“稳定的朝鲜半岛局势”的“默契”。

在东方评论员看来，就本质而言，台海稳定、朝核问题才会稳定、两岸关系有实质性突破，朝核问题才会有实质性突破。反之亦然！不难看出，丢掉了“台湾牌”之后、绝不愿意再失去“台独牌”的华盛顿是不会让“两岸实质性三通”的，因此，我们似乎也很难指望朝核问题会有个“一劳永逸”的、“彻底的”解决方案。

在这种“预期”下，就如同华盛顿只愿意“台湾问题”阶段性解决、从而以“暂停台独进程”从北京手中换取一个台湾“暂时的缓和”、为自己的中东进程淘换时间一样、在东方评论员看来，北京恐怕也只愿意让朝核问题也“阶段性解决”，从而以“暂时不让朝核问题继续恶化”来从华盛顿手中换取一个朝鲜半岛“暂时的缓和”，从而也为“韩朝经济整合”、也为自己的东北亚经济一体化“争取点时间”。


上面分析了美国在朝鲜半岛的利益、与中、韩、日甚至俄罗斯之间的“第一个根本区别”，在一段新闻报道之后，东方评论员将结合新闻内容，继续展开双方的“第二个根本区别”又在什么地方。
《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

