# -*- org -*-

# Time-stamp: <2011-08-04 00:49:08 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:3

#+STARTUP: indent

#+STYLE: <link rel="stylesheet" type="text/css" href="css/org.css" />

* 2005年6月07日 星期二

** 美渲染中国威胁将中方军力与恐怖主义并列

【综合消息】据海外媒体最新消息称，美国国防部将于近日公布中国军力年度报告书，这份报告书首次将中国军力与恐怖主义并列，放在应警戒的对象中。

美国国务卿赖斯亦指出，美国与中国的关系已经改善到过去以来最好的状况，但中国积极扩大军备，仍然令所有人感到关切。

首次将中国军力与恐怖主义并列

据日本产经新闻今日刊出其发自美国华府的报道指出，美国国防部近日内将公布中国军力年度报告书，其中，将中国急速增强的军力列为“常态威胁”里最高警戒的层级。报道称，这份报告书首次将中国军力与恐怖主义并列，放在应警戒的对象中。

报道表示，美国在九一一恐怖事件后，由于中国方面表现了与美国一起合作反恐的姿势，因此美国政府之前并未特别挑出中国军事力增强之事，但到现在，已到了美国政府无法坐视的临界点。

报道表示，由于“中国的威胁”如同冷战时代里被列为主要威胁的“常态威胁”，因此美国这次将其与恐怖主义威胁并列，显示其未来必须对此采取相关必要对策。

白宫早前曾要求美军方修改报告

而早前消息还一度传出，白宫要求五角大楼对报告中的部分言词进行修改，以免报告对于中国军力发展的描述过于负面。

有媒体分析指出，白宫要求军方对报告内容做出一定的修改是事出有因，最关键一点是这份报告夸张得太离谱。对此，美国以及国际上的一些主流媒体大加讽刺，而美国的一些专业研究机构，特别是政府内部人士的质疑和批评，使得美国白宫受到了一定的压力。同样，他们也担心一份太离谱的报告出台，可能会影响到美国在国际上所谓的客观民主形象。

另外，报告极力攻击中国的战略走向，用大量篇幅渲染所谓大陆加紧武力进攻台湾的准备。分析指，报告对于中国未来发展走向的评估与国际上对于中国的观察与预测是完全不符的，给外界以过分夸大中方敌意的印象。

此外，据白宫官员透露，白宫担心军力报告的用词过于强烈可能影响中美在朝核问题上的合作。

赖斯：中国扩军影响地区军事平衡

另据报道，在美国国防部长拉姆斯菲尔德稍早前在新加坡对中国扩大军备提出质疑后，美国国务院于当地时间6日公布赖斯在佛罗里达州对媒体表示，美中关系已改善到过去以来最好的情况，美中在反恐战争，朝核问题，以及海地维合等各方面，也都密切合作。

但赖斯指出，中国积极扩大军备仍然令所有人都感到关切。赖斯指出，中国扩军已经影响到地区军事平衡，美国因此极力反对欧盟进一步解除对华武器禁运。

相关报道：美恶意夸大中国军力意在阻欧解禁对华军售

美国会草案打击对华军售外国公司

亚洲安全大会否认中国威胁论

此外，为期三天的第四届亚洲安全大会已于5日在新加坡结束。亚洲国家代表强调，各国要更加重视以对话与合作来解决本地区面临的诸多挑战；要相互尊重，共同努力营造一个良好的安全环境。各国代表认为，中国的崛起是一个重要现实，对其他国家不构成威胁。

会议东道主新加坡总理李显龙明确表示，中国的崛起已经成为亚洲一个重要现实。亚洲所有国家现在都想加强同中国的经济关系，而中国也一直在积极帮助其他国家从中国的经济增长中受益。


【时事点评】在昨天的点评中，我们已经说过，拉姆斯菲尔德“猛烈攻击”中国扩充军力的极端言论，都不过是华盛顿“预案中的两个环节”而已。


*** 拉姆斯菲尔德的“虎头蛇尾”、“非常符合”“中美关系太复杂”之精髓

在东方评论员看来，拉姆斯菲尔德将他的“猛烈攻击”、事后却澄清为“只是提交国会报告中的一项'观察'”，这种“虎头蛇尾”的做法、“非常符合”他的老板所说的、“中美关系太复杂”之精髓。


*** 中美双方，都能在世界范围内给对方的核心国家利益“设置障碍”

的确，中美关系是“太复杂”了，复杂到了布什为了更好地处理中美关系、还另创了一个所谓的“单项处理”的名词。

在昨天的点评中、东方评论员已经说过，由于中美双方，都能在世界范围内给对方的核心国家利益设置障碍，而中国除了在东亚地区外，在其他区域内的影响主要都是依靠“政治和经济”带动的，因此，我们认为，华盛顿要想阻止北京给自己“下绊子”、并给对方“设障碍”、就得在“政治和经济的层面”上着手，特别是从经济上约束中国对这些区域的影响。


这就是说，美国一旦将“中国威胁论”正式确立为美国“国家政策”、并加以落实、这就意味着中美在亚洲、甚至全球范围内的政治角力将快速地向中美间的经济领域、甚至向军事领域渗透。

*** 中美关系的全局性、与中日关系局部性有着“本质不同”

因此，东方评论员想再次强调的是，在北京和华盛顿之间，根本就不存在中日争斗所形成的“政冷经热”之可能性。在我们看来，由于中美都是有世界影响、且也都是着眼于今后几十年全球布局的大国，因此，一旦双方走向“公开的政治对立”、一旦这种对立“剧烈地冲击到了”对方的全球布局，那么，受到强烈冲击的另一方，必将作出全面抵抗。

在东方评论员认为，“这种全面抵抗”将对整个世界的政治、经济、安全三个层面产生巨大的影响、这种影响最终将表现在“结果都会变成一场巨大的灾难”之上。

显然，在东方评论员看来，这也正是中美关系的全局性、与中日关系局部性之间有着某种“本质不同”之所在。

在我们进一步展开讨论之前，先来看看中国外交部发言人今天记者招待会，在东方评论员看来，这是一次内容非常丰富的记者会、从中，我们可以解读出许多信息。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com



** 2005年6月7日外交部发言人刘建超在例行记者会上答记者问（节简）


【东京消息】6月7日下午，外交部发言人刘建超主持例行记者会。

　　问：李肇星外长何时访问中东？

　　答：李肇星外长有出访中东的计划，具体时间我们还在和有关国家协商，有确切消息后，我会向大家通报。我想，这次访问是中方同有关国家发展友好合作关系的一次重要努力，也将是中方推动解决巴以冲突的又一次努力。

　　问：中方说“四国集团”提出的建议是“危险举动”，你能否解释一下为什么是“危险举动”？曾培炎将出访俄罗斯、卡塔尔等四国并出席南方首脑会议，中方将在南方首脑会议上提出什么建议？

　　答：不久前，李肇星外长同有关方面，比如在同非盟主席和尼日利亚外长通电话时，就“四国集团”提出的有关方案明确表明了中方的立场。他表示，联合国安理会改革事关全体会员国的共同利益，涉及各方切身利益，必须发扬民主，充分协商，达成广泛共识。“四国集团”在各方对改革方案尚未达成广泛一致的情况下，匆忙提出并强行推动表决其框架性决议草案，不利于联合国会员国的团结，违背了联合国改革的初衷，有损发展中国家的利益。在目前各方对四国集团提出的方案还存在较大分歧的情况下，我们呼吁各会员国坚持协商一致的原则，继续通过充分、民主、透明的讨论，寻求一个兼顾各方利益，赢得广泛支持的方案。

　　关于你的第二个问题，今天中午，曾培炎副总理已经离开北京前往你提到的几个国家访问，他将同有关国家领导人就发展双边关系、加强各领域的合作深入交换意见，此访将推动中国同有关国家的合作。你也提到了曾副总理参加南方首脑会议的问题，第二届南方首脑会议将于6月12至16日在卡塔尔首都多哈举行，南方首脑会议是发展中国家最高级别会议，中方高度重视。中国是发展中国家的一员，加强与广大发展中国家的团结合作是中国外交政策的重要组成部分。中方愿与各方一道推动本届南方首脑会议取得成功，进一步促进发展中国家间的合作。

　　问：中方对巴基斯坦提出的不希望安理会增加常任理事国的建议持何立场？

　　答：你提到的这一问题再次证明国际社会对联合国安理会改革方案还存在各种各样的看法和主张。在这种情况下，为了使联合国安理会的改革能达到预期目标、增强联合国安理会今后在维护世界和平和促进共同发展方面的效率和作用、有利于联合国会员国之间的团结，有利于增加发展中国家代表性，进行充分、民主、透明、公开的磋商是非常必要的，只有通过这样的磋商，各方才能就有关问题缩小分歧，达成共识。

　　问：上海合作组织首脑会议下月将在哈萨克斯坦召开，中方希望这次会议取得哪些成果？关于乌兹别克斯坦问题有什么考虑和主张？在上海合作组织首脑会议召开前后是否有中俄首脑会议在莫斯科召开？即将在英国举行的G8峰会上，胡锦涛主席将参加哪些会谈，提出哪些主张？

　　答：你提出了一个非常超前的问题，在目前的情况下，我很难对你的问题做一个预测。有关上海合作组织首脑会晤的问题，各成员国已经就这次会晤达成了共识。中方正在积极考虑出席，有了确切消息，我们会及时发布。

　　至于中俄首脑会晤，中俄两国元首有定期会晤的机制，会晤的具体时间在确定之后会通知你。

　　有关G8问题，中方已经接到有关方面邀请，正在积极考虑，有关消息会及时发布。

　　问：美国国防部长拉姆斯菲尔德在新加坡表示，中国军费开支的增长将威胁亚洲地区的平衡，请问中方有何评论？日本外相町村信孝昨天表示，中国一直批评日本首相小泉参拜靖国神社是荒谬的，中方对此有何评论？美国和朝鲜官员6日在纽约就重启六方会谈问题进行了会晤，请问中方是否赞成此次会晤？

　　答：关于第一个问题，我想多说几句，中国是一个热爱和平的发展中国家，奉行独立自主的和平外交政策，实行防御性的国防政策，坚持走和平发展的道路，是维护亚太地区和世界和平的重要力量，这是国际社会公认的事实。近年来，随着经济发展，中国的国防费用略有增长，增长部分主要用于改善军队官兵的生活条件。中国无意、也没有能力大力发展军备。事实上，中国的国防费用与其他大国相比始终处于较低的水平。去年中国的国防费用是2117亿元人民币，美国的国防开支是4559亿美元，换算成相同货币来比，美国的国防开支是中国的17.8倍，美国的人均国防开支更是中国的77倍。所谓的中国实际军费开支已经居亚洲第一、世界第三的说法毫无根据。同时，为了应对复杂多变的国际形势，捍卫国家主权、安全和领土完整，中国军队需要更新一些武器装备，这无可厚非。任何制造和渲染中国军事威胁的言行都不利于本地区的和平与稳定。希望美方尊重事实，多做有利于中美关系健康发展、有利于亚太各国增信互信，有利于本地区和平与稳定的事。

　　关于第二个问题，靖国神社里供奉着被远东国际军事法庭审判的甲级战犯。这些战犯是日本军国主义的元凶。他们的双手沾满了受害国人民的鲜血。日本领导人去这个地方参拜，显然是对日本军国主义侵略历史的否认。这个简单的事实，世人皆知，日本的有识之士也一清二楚。不敢正视历史，千方百计地以其它理由加以掩饰，只能是欲盖弥彰。

　　关于第三个问题，中方一直欢迎、鼓励同时积极促成美朝会晤。这次会晤得以实现是有益的。关于会晤的内容和结果，目前中方还没有得到相关情况，我们将同有关方面沟通，了解有关情况，以便为六方会谈的早日恢复继续作出建设性的努力。

　　问：请问玻利维亚外长访华是否将受其总统辞职的影响？中国是否有兴趣投资玻利维亚的天然气等自然资源？上次朝核问题六方会谈至今已近一年，请问中方是否认为复谈有希望，对朝核问题的谈判有何期待？

　　答：关于你的前两个问题，中国同玻利维亚是友好国家，我们一直在关注玻利维亚的局势变化，希望玻利维亚局势能尽快恢复平静。关于玻利维亚外长希莱斯先生是否如期访华的问题，目前我们还没有接到波方更改其外长访华行期的通知。至于中玻双方是否会在自然资源方面进行合作，中玻是友好合作国家，在许多领域都有良好合作，我们对与玻开展互利合作持开放态度。

　　关于六方会谈的举行是否还有希望的问题，中方认为在任何时候都不应该对半岛核问题的和平解决失去希望。从去年第三轮六方会谈结束之后，各方都在为六方会谈再次举行、为和平解决朝鲜半岛核问题继续努力。目前虽然各方还存在分歧，但各方都表示六方会谈应该继续下去，所以我们认为还是应该保持耐心、以建设性的、务实态度和诚意推动半岛核问题的和平解决进程。

　　问：据报道中国财政部长金人庆将于本周赴英国参加八国集团会财长会议，请证实。胡锦涛主席是否将参加7月在英国举行的八国集团会议？

　　答：关于第一个问题，我没有得到具体消息，中国财长和八国集团财长有交流的机制，请你跟财政部核实一下。关于第二个问题，目前还不能给你一个准确日期，但关于胡主席应邀参加在英国举行的“8＋5”会议的事，中方正在积极考虑。

　　问：日本外相町村强调日本通过经济援助对很多国家的发展作出了很大的贡献，因此别国批评日本是军国主义国家或是不爱和平的国家是不对的，你对此有何评论？

　　答：对这两个问题应该区分清楚。我想不论是中国还是亚洲的其他受害国，从来都没有因为日本向其他国家提供援助而说日本在走军国主义道路。我们反对的是日本领导人参拜靖国神社，是日方在历史问题上采取荒谬的态度。不能因为日本曾向有关国家提供过援助，就掩盖和否认日本曾对有关国家造成伤害的那段历史。我们认为，日方向有关国家提供援助，开展经贸合作，这些都是积极的努力。但也应该指出，这种合作是互利共赢的，不是单方面的恩惠。

　　问：上海合作组织外长会议决定给予巴基斯坦、印度、伊朗等国以观察员国地位，这对上合组织在打击恐怖主义、维护地区和平与安全等方面将产生什么影响？

　　答：巴基斯坦、伊朗、印度都是本地区有重要影响的国家，我们欢迎和支持三国成为上海合作组织的观察员。6月4日在阿斯塔纳举行的上合组织成员国外长会上，各方原则商定，同意给予三国观察员地位，并将在7月初的上合组织阿斯塔纳峰会上就此作出正式决定。中方相信，巴基斯坦、伊朗和印度成为上合组织观察员，将进一步促进上合组织与三国的互利合作。

　　问：据报道，朝鲜和美国通过纽约渠道会面的部分原因在于美方将一年之内召开六方会谈作为最后期限。你是否相信美方有最后期限？这种最后期限是否具有建设性？本周晚些时候韩国和美国领导人将在华盛顿会晤。中方对此次会晤在解决朝核问题方面有何期待？

　　答：我没有听说有这样一个最后期限，我也注意到美方表示，无意提出这样一个最后期限。在目前情况下，各方需要保持耐心，多释放善意，以建设性的态度推动六方会谈早日恢复。有关各方在就六方会谈的恢复进行各种级别的磋商。我们也希望韩国和美国的元首会晤就有关问题形成建设性意见，推动六方会谈早日恢复。

　　问：美国国防部长拉姆斯菲尔德在新加坡会见了中国哪位官员？拉姆斯菲尔德是布什内阁中唯一尚未访问中国的资深官员，他是否接到过中国的邀请？为何没有访问中国？法国和荷兰的全民公投相继否决了《欧洲宪法条约》，中方对此有何评论？这对中欧关系有何影响？最后提一个关于历史问题的看法。很显然，日本侵华暴行对中国来说仍然是一个记忆犹新的伤口。那么中国为什么能够淡忘或原谅800年前蒙古军队烧杀抢掠，却不能原谅日本的侵略呢？

　　答：先回答你的最后一个问题，这个问题可能需要你我坐下来边喝咖啡边探讨，能够谈上三天三夜。在你提到的一些历史问题上，我们有不同的看法。今天我无意就你刚才提到的我不同意的观点进行反驳，建议你仔细研究一下中日历史。我想，你提的问题的核心是中日之间的历史问题。我们要求日方对历史问题采取负责任的、正确的态度，这对中日关系发展以及日方自身的发展都是有利的。日方应多做能取得亚洲人民信任的事，而不是相反。

　　出席此次在新加坡举行的对话会的中方代表团团长是外交部亚洲司司长崔天凯先生。至于他是否在新加坡同拉姆斯菲尔德先生进行会晤，我还不得而知。但是我知道他们进行过一些交谈。

　　关于最近有关国家就欧盟宪法举行了全民公决，中方无意干涉欧盟内部事务。但中方支持欧盟一体化进程，愿意看到欧盟在国际事务中发挥更大的作用。中国和欧盟在许多重大的国际问题上有一致的看法，比如说我们都主张多边主义。我们希望欧盟的扩大和一体化能够有利于欧洲的繁荣稳定以及中欧关系的发展。

　　问：中方是否已经确定了胡锦涛主席今年访问朝鲜的事宜？

　　答：我没有听说这方面的消息。

　　如果没有其他问题，记者会到此结束，谢谢大家！



【时事点评】在东方评论员看来，发言人刘建超的这次答记者问，可以说涉及到了全球各个区域，也涉及国家间关系的所有层面：其中，有东亚的台湾问题、朝核问题、日本问题、有中东问题、但特别提到了美国“现在正在忙于处理”的巴以冲突。

此外，还有伊朗、巴勒斯坦、印度成为“上海合作组织”观察员的中亚问题、还有美国的后院南美洲相关问题、还有中国与“富国俱乐部”G8在政治、经济方面建立对话渠道的问题，“四国集团”共同闯关联合国安理会的联合国改革问题，可以说当今世界所有的“重点、难点问题”，是“一网打尽”。

*** 这些重点、难点问题“似乎”都是政治、经济问题、而与“军事”无关

显然，从今天的记者的“所提的问题”、与刘建超的“相应的回答”来看，中美之间、中国和其他国家之间、“需要合作”的地方太多了。同样，从记者的“问题”、与刘建超的“回答”来看，这些需要合作的“重点、难点”问题似乎都是单纯的政治、经济问题、而与拉姆斯菲尔德“猛烈攻击”中国扩充军力毫无关系。

然而，如果我们仔细研读刘建超的回答、事情显然又不是这样。

请大家注意这么一段话：.........所谓的中国实际军费开支已经居亚洲第一、世界第三的说法毫无根据。同时，为了应对复杂多变的国际形势，捍卫国家主权、安全和领土完整，中国军队需要更新一些武器装备，这无可厚非。任何制造和渲染中国军事威胁的言行都不利于本地区的和平与稳定。希望美方尊重事实，多做有利于中美关系健康发展、有利于亚太各国增信互信，有利于本地区和平与稳定的事。


*** 刘建超抓住了拉姆斯菲尔德“猛烈攻击”中国扩充军力的要点，那就是“中国军事威胁论”

刘建超的这番话的确抓住了拉姆斯菲尔德“猛烈攻击”中国扩充军力的要点，那就是“中国军事威胁论”、尽管刘建超本人并没有将其“文字化”。

在昨天的点评中，东方评论员已经说过，布什在5月31日提出了一套处理中美关系的“新观点”、即所谓的“单项处理”、而其根据就是“中美关系非常复杂”、按布什的话来说，那就是“复杂到了”“中美关系很难简单地形容说是竞争对手或者合作伙伴”这种程度。

显然，如果我们顺着布什的“这种观点”去解读的话，那么，拉姆斯菲尔德“猛烈攻击”中国扩充军力、“本质上”就是一种对“中国威胁论”的“进行变种”，怎么说呢？在东方评论员看来、华盛顿是在“有意”将一个笼统的、“很难精确地形容”中美关系之内涵的“中国威胁论”、也要进行一番“单项处理”，而处理的结果就是拉姆斯菲尔德嘴里吐出来的所谓“中国扩充军力带来的威胁”。在东方评论员看来，这也就成了另外一个新名词，即“中国军事威胁论”。



*** “中国军事威胁论”与原版的“中国威胁论”一样，都有点“曲高和寡”的味道

事实上，“中国军事威胁论”是否有市场，美国人心里还是有数的，其实，就在这个周未的第四届亚洲安全会议上，除了“中国威胁论”的“版权”所有者美国、在卖力地吆喝“中国军事威胁论”之外，唯一跟着附和的、就是世界上“第一家正式使用”“中国威胁论”这个“产品”的日本了。

与此同时，东方评论员注意到，其它亚洲国家，包括主办国新加坡在内，都一致地与美日“唱反调”、公开表示“不认为中国是威胁，认为中国是机会”，看来“中国军事威胁论”与其原版的“中国威胁论”一样，都有点“曲高和寡”的味道。


*** 大多数亚洲国家，非常清楚自己想得到的是什么

东方评论员注意到，会议东道主新加坡总理李显龙就明确表示：中国的崛起已经成为亚洲一个重要现实。亚洲所有国家现在都想加强同中国的经济关系，而中国也一直在积极帮助其他国家从中国的经济增长中受益。

而其它亚洲国家代表则强调，“各国要更加重视以对话与合作来解决本地区面临的诸多挑战”；“要相互尊重，共同努力营造一个良好的安全环境”。

显然，这些从中国经济的发展中、已经获得了实实在在经济利益的亚洲国家，非常清楚自己想得到的是什么，那就是一个“通过对话和合作”而营造一个“良好的安全环境”。


*** 没有“雄厚的”“政治、和军事资源”保护的经济资源、就是再庞大、也是“非常脆弱”的

稍有政治头脑的人，都不难想像，以中国今天的政治、经济、特别是军事实力，亚洲要想获得一个“良好的安全环境”，没有中国的参与和配合、是根本就做不到的。

以97年亚洲金融风暴为例，在那之前的几年里，由于外资、特别是日本的大量资本投入，一时间里，这些国家的经济发展迅速，而所谓“东南亚模式”更是气势如虹。然而，由于没有“雄厚的”“政治、和军事资源”、日本庞大的经济资源也就显得“非常脆弱”，根本就无力保护自己在东南亚的投资。

事实证明，在欧美联手打击下、日本为了自保（准确地讲、日本实际上也的确没有综合能力去保护它在东南亚诸国的投资），而置东亚、东南亚“经济稳定的大局”于不顾。


*** 对中国的“责任心”和“综合实力”，亚洲国家的心中是“非常有数”的

结果是，反而是中国着眼于自己的未来、也着眼于一个亚洲大国的责任，从而在政治和经济上顶住了欧美的压力，坚持让人民币稳定、从而为东南亚、东亚的经济复苏奠定了坚实的基础，在东方评论员看来，这些反过来、也对中国经济与亚洲国家经济进一步整合提供了机会。

后来、在国际政治角力中、有诸多证据显示，对中国的这一“力挽狂澜于即倒”所表现出来的“责任心”、和“综合实力”，这些亚洲国家的心中、是“非常有数”的。


*** 中国“愿意负责任”的结果

现在，美国和日本为了自己的一已之私、美国想通过在中国和日本、以及其它国家中“搬弄是非”的手段，为继续拼凑一个“反华包围圈”，制造“可行的理论”依据。在东方评论员看来，由于亚洲国家从97年金融风暴“间接获得的支持”、和近年来从中国的经济发展中“直接赚到的好处”，都能够品味出“是谁曾经砸过自己的饭碗”，而又谁又曾经在最困难的时候帮过自己一把”的、而这两者间的“是非曲直”更是不难判断：即，尽管从根本上讲，中国也是为了自己的利益，但是，中国之所以在客观上帮了东南亚国家一把，就在于中国将这些国家的利益，也放在自己的长远利益的考虑之内，而这正是东南亚国家愿意与中国搞“10+1”、搞东亚经济一体化的基础，也正是中国“愿意负责任”的结果。


*** 华盛顿的决策层在“宣传策略”上显然“有侧重点”

当然了，仅仅着眼于经济上的利益，在大国眼里，都不过是些“小道理”而已，然而，在东方评论员看来，华盛顿挑在这个时候抛出“中国军事威胁论”的目的，也就是针对这些“着眼于经济利益”的“小道理”的。

因此，在亚洲、特别是东南亚这一块，华盛顿的决策层在宣传策略上显然“有侧重点”，这就是“不谈经济”、只谈“军事和安全”、并以此来“突显”中国的“军事威胁”到了何种地步。


*** 一个有如“兵慌马乱的时候，老百姓才是最遭殃的”一样简单的道理

有意思的是日本。日本则想借美国拼凑反华包围圈的机会，以给美国“当打手的身份”、也在中美间“煽风点火”、力图营造出一幅“中美全面对抗”的局面，显然，要达到这一目的，仅仅是个“中国军事威胁”是不能让日本人满意的，而在政治和经济上，单单一个日本，又是不足以遏制、或者搞跨中国的，这也是日本最早使用比“军事威胁论”要全面得多的“中国威胁论”的原因。


然而，在这些亚洲国家眼里，不论是日本所正式使用的“中国威胁论”也好，还是美国这次抛出的“中国军事威胁论”也罢，都是在“借口这种、或者那种的威胁”在制造亚洲国家与中国之间的“对立和紧张”。

值得注意的是，据说美国国防部将于明日公布中国军力年度报告书，这份报告书首次将中国军力与恐怖主义并列，放在应警戒的对象中，显然，这样的一份报告，根本就是在“刻意制造”亚洲经济环境、安全环境的“混乱”。

东方评论员认为，有了97年金融风暴的“九死一生”的经历，这些国家“当然不愿意”为这样、或那样的威胁论“叫好”，在这些国家的眼里，让中国和美国“在某种程度上竞争”、对他们是有好处的，然而，在东方评论员看来，这些国家的领导人也明白，一旦这种竞争延伸到“政治、军事上的恶斗”、以至于最后发展到“中美圈地、各国选边”，那么，最终倒楣的还是这些区域内的“小国家”。这个道理非常简单，就有如“兵慌马乱的时候，老百姓才是最遭殃的”道理一个样。


*** 华盛顿对“军事威胁论”不受亚洲国家欢迎，应该心中有数

东方评论员认为，华盛顿对拉姆斯菲尔德的“军事威胁论”不受亚洲国家欢迎，自然应该心中有数，因此，我们也就看到了下面的一幕：

请大家注意这一段文字：原文是，另据报道，在美国国防部长拉姆斯菲尔德稍早前在新加坡对中国扩大军备提出质疑后，美国国务院于当地时间6日公布赖斯在佛罗里达州对媒体表示，美中关系已改善到过去以来最好的情况，美中在反恐战争，朝核问题，以及海地维合等各方面，也都密切合作。

在我们看来，赖斯所说的“美中关系已改善到过去以来最好的情况”这句话，引起了我们的兴趣，刻薄地讲，赖斯的“这种观点”显然是抄袭其前任--鲍威尔的，大家应该还记得，鲍威尔可是念念不忘“美中关系处于三十年来最好时期”、可以说，他在任上最后两年，大凡在中美紧张时、一谈到中美关系，这位有名的鸽派就喜欢将这句话拿出来念叨一番。

可惜的是，只是念叨来、念叨去，丝毫没有影响中美在东亚、在中亚、在中东、在世界各个角落里，彼此都是“该干什么、还是在干什么”。

*** 赖斯似乎“完全体味到了”鲍威尔的在位时的心情

因此，东方评论员认为，赖斯所说的“美中关系已改善到过去以来最好的情况”这句话，似乎已经证明了她不仅已经完全接替了鲍威尔的角色、也完全体味到了鲍威尔的在位时的心情，那就是，美国在这个世界上虽然力量很强，但远非可以“随心所遇”的。因此，这就要继续扮演好鲍威尔所扮演的“红脸角色”，在美国的五角大楼-这一鹰派大本营向外挥舞大棒的时候，赖斯就得从美国国务院往外“不时派发胡萝卜”，在我们看来，这个所谓的“美中关系已改善到过去以来最好的情况”、不也是这么一根胡萝卜吗？显然，与其说它是说给北京听的，倒不如说是说给东南亚国家听的来得准确。

东方评论员认为，看来，在亚洲这个地方，谁都清楚，不论是中国还是美国、或者是日本、都清楚搞冷战式的全面对抗、是不得人心的。

*** 对“中国威胁论”、华盛顿决策层“还存有争议”

事实上，就在明天，美国国防部的《中国军力报告》就要上场了，从拉姆斯菲尔德的“中国军事威胁论”在面向亚洲进行推销时“并不叫好”的情况看，从赖斯“抄袭鲍威尔语录”的情况看，美国决策层内部对“中国军事威胁论”依然有争议。

在昨天的点评中，东方评论员曾经说过、由于中美关系远比中日关系复杂，而华盛顿又绝不可能让中美关系于中日关系破裂之前先行破裂，因此，在我们看来，在现阶段内，日本可以说”中国威胁论“，而华盛顿却不行。

东方评论员的观点的是，不论是笼统的“中国威胁论”也好、还是经过“单项处理”过的“中国军事威胁论”也罢，华盛顿决策层都“还存有争议”。

*** 北京的“非正式反应”

当然，在我们看来，表现出“这种争议”的本身，就是有意义的：第一，“这种争议”原本就是向中国、或者亚洲国家施加压力的一种手段，第二，表现出“这种争议”、还可以试探一下北京和相关国家的反应，显然，就北京而言，从几天前五角大楼提出“中国军力报告”，而被白宫要求修改之后，北京起码已经在两个方向做出了反“非正式的反应”，一个是中亚，这就是“上海合作组织”“扩编”、而另一个方向，就是朝核问题，朝核问题现在几乎“又玩到了春节前后的紧张气氛”；

最后一个方向，就是在中东了、也就是最贴近美国核心利益的方向。东方评论员注意到，刘建超今天已经说了，中国外长准备出发“到中东一游”，据说将去谈美国“正在忙着处理”的“巴以问题”。只是我们还注意到，刘建超还“卖了一个关子”，说是“时间未定”。

在东方评论员看来，这个“时间未定”恐怕“大有名堂”。事实上，在华盛顿官员的眼里，李外长近半年来已经去过中东几次了，有意思的是，每一次去，总是中美关系非常紧张的时候、而且，让华盛顿极为不满的是，李外长每一次还“都不干好事”。如此一来，东方评论员也就难免会猜想一番，那这一次去了呢？会干“好事”吗？我们就一起观察事态的后续发展好了。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
