# -*- org -*-

# Time-stamp: <2011-08-02 20:35:31 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

#+STARTUP: indent

* 2005年4月21日 星期四

** 眼见情势演变，李登辉决定第一时间跳上火线

【台湾消息】据台湾媒体报道，李登辉质疑国民党主席连战访问中国大陆「身分、时机不对」，国民党发言人张荣恭今天说，连战以最大在野党主席身分访问中国大陆，是关心台湾与台海，身分绝对适当。

报道说，连宋即将联袂登陆，李登辉对在野党领袖连续要登基，相当不满，21日下午召开中外记者会强烈批判，他强调，两岸对谈方式，应是政府对政府，而两岸要谈，不只是跟北京谈，且要有其他国际国家一起谈，地点应是两岸以外。

自称已失眠好几天的李登辉痛批，连宋相继要登陆，身分不对、时机不对，伤害主权，行为也好像在伤口洒盐，他强调未经政府授权，不得谈判，此举非常不智，而此时机访问中国，制造台湾人民不在意假象，完全打消326愤怒的台湾民众心声，质疑是混淆国际视听。

据台联党主席苏进强转述，李登辉本来要在22日召开任务型国代记者会时才露面，但眼见情势演变，李登□决定第一时间跳上火线。据了解，为这场下午3点召开的记者会先暖身，除了前总统资政辜宽敏和李登辉外，台联党主席苏进强也会参加这场记者会。

东森新闻说，李登辉在这场由手护台湾大联盟举办的「面对国家迫切危机－－坚决反对连宋联共卖台」记者会上说，连战和.对谈，台湾人不会承认，.是中国执政党，但国民党只是在野党，去谈没有意义。
李登辉以高亢的语气说，去大陆要谈，也不用谈什么和平法，而要多谈谈实质性的东西，例如以前海基会和海协会谈，都是谈实质性东西，对台湾人有帮助。

李登辉痛批，中国才刚通过反分裂国家法，国际对其有反感，连宋此时却要访中，他一堆美日朋友都来电问他，「台湾在搞什么东西呀」，李登辉动气的说，中国推出反分裂国家法，连宋前往中国，是制造两岸和平的假象，他认为，连宋应该在美国大卫营，而并非前往北京会见胡锦涛，两岸会谈应包括美国及日本在内。

李登辉对连宋两人赴中国访问，提出「6个不对」，包括原则不对、身份不对、时机不对、两岸对谈方式不对、地点不对、政府公权力不张。他建议两岸如果要政府对政府对谈，应该在美国华盛顿，由美、中、台、日四国坐下来谈。

有媒体报导称，李登辉在20日邀集本土社团，表示中国通过反分裂法，连宋却相继访中，这是他「一辈子从未碰到这样的危机」，严重程度远甚于96年飞弹危机，为此，他已经几天睡不好觉，因为「政府好像被掏空了！」现在国家没有方向，也不知道究竟谁能保卫台湾。

中时晚报说，二月份扁宋会后，本土社团与陈水扁间出现裂痕，民进党藉着326游行拉近两者的距离，但随着连宋登陆与国代选举逼近，20日下午李登辉临时召集20余位本土大老商讨国内局势，据了解与会人士对民进党的批判声浪异常强烈，咸认为陈水扁让连战、宋楚瑜前往大陆，就是与台湾所有人民决裂，

更对陈水扁与政府提出强烈批判，群情激愤下连「阿斗」都脱口而出，形同泛绿势力的再次分裂。本土人士指出，第二次国共和谈代表邵力子一行人于1949年前往中国，结果包括谈判代表、幕僚、秘书与翻译等全数投共、无一人返回台湾，本土社团决定将于26日连战出访当天，到机场送他一张单程机票，告诉连战「不用再回来了！」

张荣恭晚间在国民党中央表示，连战身分绝对适当，至于时机必须创造，过去五年看不到两岸关系进展，连战决定这个时候访问大陆，一定会坚持台湾尊严、两岸和平、对等，时机靠创造，这是连战的思维。

他表示，所谓的本土社团发表声明「抹红连宋」，有些人对和平没有能力，对战争没有本事，只能制造口头对抗、抹红对手、背离主流、形成不安。

他说，本土团体所谓连宋访问大陆是帮中国大陆解套，其实连战的做法是帮台湾解套，因为过去五年来，政府或独派团体围堵台湾。中国大陆围堵不了台湾，政府却围堵台湾，让台湾无法加入东亚经济整合，连战是帮台湾解套。

本土团体也质疑连战没有资格和大陆对谈，是「去政府化」，张荣恭表示，五年来政府在两岸关系上没有作为，形成「无政府化」。以春节包机为例，政府接手、朝野分工，在野党「助政府化」，连战访问大陆是为台湾搭桥铺路，不希望独派人士毁桥拆路。




【时事点评】我们注意到，围绕着连战和宋楚瑜争先恐登陆大陆，不甘寂寞的李登辉、今天也终于也一把跳了出来。在东方评论员看来，这位“日本皇民”在连战就要“正式登陆”的前夕才跳将出来、拉高声调，强烈表示反对，一来是“时机”到了，二来也有早就忍受不住的原因在里面。

*** 李登辉好象是在那里“狗急跳墙”

因此，就这两点而言，东方评论员认为，那位秉承李登辉旨意去日本靖国神社“寻根”的台联党主席苏进强、“转述”说什么李登辉“眼见情势演变，李登辉决定第一时间跳上火线”倒也显得“非常贴切”和“颇为生动”。

其实，只要我们看看李登辉的反对连战到大陆来的理由，就不难看出，什么“原则不对、身份不对、时机不对、两岸对谈方式不对、地点不对、政府公权力不张”，可以说这位上了年纪的“老人家”、硬是一口气憋出了“六大不对”，的确让人们似乎看到了李登辉好象是在那里“狗急跳墙”。

*** 为什么李登辉“忍了这久”、却突然忍不下最后的“24小时”？

东方评论员注意到，按苏进强的话来说，自国民党将登陆大陆的计划具体实施之后，一直显得比陈水扁要有“涵养”、“从不吐露一个相关字符”的李登辉、本来是准备“继续涵养”到22日，也就是要在22日召开任务型国代记者会时“才露面”的，然而，为什么这位忍了这久、却突然忍不下最后的“24小时”、非得比原计划“提前整整一天”跳出来呢？

显然，在东方评论员看来，我们有必要思考一下、从21日到22日这“24小时”间，已经发生了什么事、或者可能会发生什么重大事件。因此，在我们看来，尽管我们现在是在评论台湾话题，但是，时事评论员认为有必要将两篇已经放在其它话题里的新闻稿挪到这里，做为我们讨论的资料。下面，我们就先看看这些个“挪用的新闻稿”，讲的是些什么事情。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 韩外交部次官：6月是六方会谈“心理底线”

【汉城消息】据韩国联合通讯社报道，韩国外交部次官补宋旻淳今天称，今年六月底是朝核问题的“心理底线”。

宋旻淳在接受美国哥伦比亚广播公司的采访时说，“到今年6月份，第三轮六方会谈将整整过去一周年，这是心理底线。朝鲜推迟参加六方会谈，使人们无法看到会谈前景。会谈各方已普遍认为目前的情况不能无期限拖延下去。”

宋旻淳同时透露，韩美还未就“将朝核问题提交安理会审议”一事进行讨论，韩国政府目前正制订相关对策。

“提交安理会并不能解决所有问题，而且还可能成为安理会的负担，”宋旻淳说。

他同时对朝鲜关闭核反应堆的做法进行了评论。“韩国正在密切关注事态发展。认定停止运行核反应堆就是为了提取钚还为时尚早，这可能是在进行维修检查等技术性调整，”宋旻淳说。

** 朝鲜：要实现无核化美国须撤走周边所有核武器

【平壤消息】据报道，朝鲜劳动党中央机关报《劳动新闻》21日发表评论说，要实现朝鲜半岛的无核化，美国就必须撤走其部署在韩国及周边地区的所有核武器，彻底消除核威胁，同时必须根除韩国走核武道路的可能性。

　　评论指出：“这是实现朝鲜半岛无核化的关键。”关于朝鲜拥有核武器问题，评论说，美国对朝鲜实施核扼杀政策，朝鲜不能坐以待毙。朝鲜拥有核武器是为了应对美国日益加重的先发制人的核打击威胁，防止战争，捍卫自己的思想与制度、自由与民主。

　　评论表示，美国所说的“无意侵略朝鲜”不过是空话一句，缺乏实际保证。只有美国以实际行动放弃敌视政策，显示出愿与朝鲜和平共存的诚意，朝核问题才能得到解决。




【时事点评】事实上，从我们过去几个星期的解读中，大家不难看出这台湾问题、朝核问题、中日关系、中美关系间的种种巧合：就在赖斯从北京回去之后、中国领导人在接待来访的朝鲜高层、仍然放出“朝核问题是个需要耐心的问题、不可能短时间内就解决”的意思之后，“心领神会”必须在台湾问题上“不再能光说不做”的华盛顿、一面开始公开地与日本的“要为朝核问题划定最后期限”的强硬政策拉开距离，并压陈水扁和宋楚瑜一起端出个“十点共识”、以“中间路线”的方式，为台海描出了一副“趋向稳定、和平”的“政治图画”。

*** 华盛顿的小动作可以说是“随处可见”

东方评论员认为，华盛顿“如此这般”也是不得已而为之。但是，我们只要细细观察就不难注意到，华盛顿的小动作可以说是“随处可见”。

根据我们的观察，美国人其实是在一面以此“兑现”对北京的承诺、一面去利用“扁宋会”去做彻底瓦解台湾“蓝营”的勾当，最后，也是最重要的，美国人还在想着如何去利用这一“可怕的趋势”、去“间接刺激”真心感到了“中国威胁”的日本、去更大限度的挑畔北京。

*** 白宫在利用台湾给北京“制造各种问题”的手段可以说是“极其老到”

显然，这种行为，一方面显示了美国为急于稳定东亚、不得不向中国兑现“反对台独”的战略心态，但另一方面，也体现了白宫在利用台湾问题给北京“制造各种问题”的经验和手段、可以说是“极其丰富与老到”。

不难看出，自赖斯离开北京后，近一个月来，华盛顿用一个“两岸和解”的“表象”，通过一系列外交手腕、利用日本想迅速成为政治、军事大国的急功近利心理，成功地达成了在中日间尽可能“制造对立”的目的。

*** 进入四月份后，世界局势是为之一变

但是，进入四月份后，世界局势是为之一变，这表现在温家宝总理访问南亚取得成功。

首席评论员指出，与美国一样，日本对中印这两个亚洲大国的快速接近不仅“非常不爽”、对印度这个自己一度想拉之入针对中国的“亚洲北约”国家、最后却选择去与中国进行全面合作、也感到非常害怕。

*** 台湾社会最为怪诞的一幕

因此，我们也就欣赏到了台湾社会最为怪诞的一幕，那就是，正当国际间发起百万人联署向联合国请命，让各界重视日本迄今尚未解决的战争责任问题，而北京也放风称“还愿意看到联合国分裂”，有意阻止日本加入联合国安理会常任理事国之际，4月4日，抢在温家宝总理6日访问印度之前，李登辉一手扶持的“台联党”主席苏进强，竟然冒天下之大不韪，到日本参拜象征日本军国主义的靖国神社。


*** 苏进强“拜鬼”，意味日本决定在压中国让步的动作上，准备“放手一搏”

事实上，在东方评论员看来，李登辉和苏进强这种人、在台湾敢做这种“全然是民族败类才肯干、且愿意干”的事情、其实一点也不怪，不要忘记了，李登辉就公开声称过“钓鱼岛是日本的领土”，结果如何，台湾不是还有那么多人支持他吗？

显然，就如东方评论员在过去的点评中所谈到的那样，李登辉让苏进强于4月4日去日本靖国神社“还愿”、“拜鬼”、本身就意味着在赖斯访印收获不大、促使日本决定在压中国让步的动作上，准备“放手一搏”了。

*** 唐家旋严重警告日本

只是，我们必需十分警惕的是，那些为数不少的、支持李登辉、并自视为“日本皇民”的台湾人，就是日本人认为可以在台湾问题上、向中国“示强”、让华盛顿看到日本在台湾“也有力量”的筹码。由此可见，李登辉当时让苏进强于4月4日、率团去日本正式参拜靖国神社、本质上是日本准备在中日关系上“放手一搏”的前奏。

接着，我们也就看到了日本宣布通过了扶桑社的美化日本侵略历史的历史教科书、特别是不顾中国政府的严重警告、宣布“准备向”日本企业发放勘探中国东海资源的许可证。

我们知道，在日本做出这一宣布这前，国务委员唐家旋就警告说，一旦日本向日本企业正式发放许可证，其后果是极其严重的，因为那样的话，“问题的性质就变了”。

那么，这个所谓的“问题性质变了”是个什么意思呢？在东方评论员看来，其意思就是“中日关系将全面转向对立”、从而彻底阻断日本指望借美国需要自己之机、压中国先行让步、继而继续在中美之间玩“借力打力”、图谋摆脱受制于“中美夹缝”、直到日本摆脱美国为止的“小聪明”。

*** 中国“不仅有实力这么做”，而且还“有决心”这样做

显然，中国在联合国以“联合国改革不应该设时间表”阻拦了安南提出的、有利于日本的改革方案之本身，其重大意义体现在两个方面，第一，这是北京向亚洲国家、向世界、特别是日本国内各种政治势力正式展示中国“有实力打击”日本的大国梦；第二，中国此举更是在刻意显示、中国不仅有实力这么做，而且还“有决心”这样做、有决心用自己的力量、带领韩国等亚洲国家一起、以包括经济在内的各种手段、去打碎日本的军国梦。

*** 小泉纯一郎颇有“小聪明”这一点“的确不虚”

不难看出，日本的那个一惯就极其强硬的外相，就是在这种危险下跑到中国来、传送小泉纯一郎的亲笔信的。然而，日本外相一到北京，日本方面就放风说那小泉纯一郎给温家宝总理的亲笔信，在东方评论员看来，小泉纯一郎颇有“小聪明”这一点的确不虚，因为如此一来，可以说“地球人都知道”、若按外交礼节的常理来看，日本外相应该在面见温家宝总理时“面逞”，从而实现会晤中国总理、提升“来访者”待遇、和中日这次交流级别的目的。

*** 向来讲究礼节的中国政府，就是不安排给日本外相这种“面逞”的机会

然而，出乎各国外交官们意外的是，直到这位外相逗留在北京的最后一分钟，向来讲究礼节的中国政府、“并没有看重”这种外交礼节，就是不安排给日本外相这种“面逞”的机会。

可以说，日本外相是以“兴师问罪”的方式、来寻求“中日缓和”的，首席评论员指出，这种态度，本来就带有试探中国底线的图谋在里面，因此，可以肯定的是，戴着强硬面具来北京的町村、能从中国能带回去的信息、自然也是“再强硬不过的了”。

在之前的点评中，我们已经说过，小泉政府“何去何从”，是选择中日决裂、美国对日本的完全控制、还是选择维持一个可以交流的中日关系，以继续在中美间相对自由，可以说时间“已经不多了”。

*** 李登辉今天公开“跳出来”、似乎已经暗示了一种可能性

其实，在东方评论员看来，今天，李登辉公开跳出来，质疑国民党主席连战访问中国大陆“身分、时机不对”，事实上，似乎已经暗示了一种可能性，那就是，小泉纯一郎“准备低头”了。

在东方评论员看来，与日本政府“互通有无”的李登辉在这个时候提前跳出来攻击美国默许下的、国民党主席连战、亲民党主席宋楚瑜登陆的事情，只有一种可能性最大，那就是，日本在与中国的这一轮争斗中、可能再一次没有得到华盛顿的“有效配合”。

*** 朝鲜、韩国，今天一前一后，何以突然大谈朝核问题？

显然，如果我们从这个角度去看朝鲜、韩国，今天一前一后、分别也抢在中国、日本“正在商量”是否可以安排胡锦涛见小泉纯一郎之前，突然大谈没有进展、却也“相对安静”的朝核问题，整个形势就一目了然了。

只是，东方评论员注意到，韩国和朝鲜在谈同一个朝核问题时，其立场非常有趣，请大家注意这两段文字：

宋旻淳在接受美国哥伦比亚广播公司的采访时说，“到今年6月份，第三轮六方会谈将整整过去一周年，这是心理底线。朝鲜推迟参加六方会谈，使人们无法看到会谈前景。会谈各方已普遍认为目前的情况不能无期限拖延下去。”

而朝鲜劳动党中央机关报《劳动新闻》21日发表评论说，要实现朝鲜半岛的无核化，美国就必须撤走其部署在韩国及周边地区的所有核武器，彻底消除核威胁，同时必须根除韩国走核武道路的可能性。

*** 两家“表达”立场的方式似乎是在“异曲同工”

非常清楚，在我们具体评论其立场之前，有必要注意一下两家“表达”立场的方式似乎是在“异曲同工”，要么是“专访”、要么是“评论”，总而言之，都是采用的“可以充分说明立场”的方式、向全世界进行“广播”的，这比单纯地发布简短的新闻、“能将立场彻底说清楚”的程度要大得多。

那么，这两家想说明什么呢？东方评论员注意到，韩国外交部次官补宋旻淳今天谈的重点是：六月底是朝核问题的“心理底线”。朝鲜劳动党中央机关报《劳动新闻》的评论说的核心则是，要实现朝鲜半岛的无核化，那么美国在韩国及周边地区的所有核武器，以及必须根除韩国走核武道路的可能性”。

*** “六月期限”说的“版权”可是日本“独家”所有

显然，这看上去不由得让人琢磨：近来一直眉来眼去的朝鲜、韩国怎么相互又干上了？其实不然。在这里，我们首先要说的就是这个所谓的“六月心理底线”的说法，大家应该还记得，“六月限限”说的“版权”可是日本“独家”所有的，早在赖斯访问中国的时候，日本就单方面放风说“美国日本在六月设立解决朝核问题的期限的问题上达成了一致”。

当时，在东方评论员看来，这当然是个强硬姿态，如果日本人所说不虚，那么，这将对整个朝核问题的解决、以至中美在东亚的战略安排产生严重的影响，事实上，我们也对“六月期限说”进行了连续的跟踪解读。


*** 韩国提“六月期限”显然是颇有“醉翁之意”

然而，之后中国外交部发言人公开表示，认为朝核问题是个需要耐心的复杂问题，且没有听说美国国务聊赖斯在北京提过这一期限。最有意思的是，几天后，美国总统布什更是亲自出来辟谣，说“华盛顿没有为朝核问题设立期限”，从那开始，在《东方时事解读》中，时事评论员才开始不再去关注这个问题。

可是没有想到的是，我们今天再次遭遇“六月期限说”，显然，日本人抛出的这个“幽灵”，自然与日本人有最大的关系。在东方评论员看来，韩国在小泉纯一郎在表态将“何去何从”之际的这个节骨眼上、“重背”日本的“假造出来”的那个、最后让小布什都得出来亲自辟谣的“朝核问题的谎言”，显然是颇有“醉翁之意”，不要忘记了，美国和日本之间、在朝核问题的“立场协调”上、因日本内心里夹杂了一个“核军备竞赛”“私货”，而早已经变成了一个“不伦不类”、“非敌非友”的关系了，


*** 韩国和朝鲜在维护朝鲜半岛和平、稳定这个“最高利益”上，还是紧紧地靠在一起的


有意思的是，就在韩国“学着日本的口吻”，侵犯日本的“版权”、“强调”“六月期限”这个说法的同时，也在强调韩美还未就“将朝核问题提交安理会审议”一事进行讨论，并坚持认为几天前闹得风风雨雨的朝鲜“停止运行核反应堆就是为了提取钚还为时尚早”，除此之外，还认为“（朝核问题）提交安理会并不能解决所有问题”。

东方评论员的观点是，非常清楚，韩国和朝鲜在维护朝鲜半岛和平、稳定这个“最高利益”上，还是紧紧地靠在一起的。


*** 朝鲜的立场几乎就是对北京的“朝核立场”的一个“异地解读”


更有意思的是朝鲜的说法，在东方评论员看来，首先，朝鲜的立场几乎就是对北京的“朝核立场”的一个“异地解读”，我们知道，中国官方对朝核问题的定义、从来就是“朝鲜半岛无核化问题”，从来就没有将“朝鲜无核化问题”。

显然，在加上个“半岛”这两个字之后，朝鲜的朝核问题就又有了一层“新意思”，既，要实现朝鲜半岛的无核化，应该包括美国部署在韩国的核武器、以及韩国的核能力问题”。


*** 平壤“舌头”所指的、另一个国家--日本的名字，就呼之欲出了


不难看出，朝鲜的这篇幅评论将北京的立场也加以了扩大，加了个“周边地区”，什么意思？当然没有人去认为朝鲜说的是中国和俄罗斯、那么，在朝鲜已经点了韩国的名、要求“同时必须根除韩国走核武道路的可能性”之后，那么，平壤舌头所指的、另一个国家--日本的名字，就呼之欲出了。


*** 韩朝似乎是在将美日间在“核竞赛”问题上的那种“不伦不类”的关系又拉到“太阳底下来烤”


在东方评论员看来，朝鲜这哪里是在要求必须根除韩国走核武道路的可能性，分明是在要求“必须根除日本走核武道路的可能性”，显然，这也分明是在将美国和日本在“核竞赛”问题上的那种“不伦不类”、“各藏私心”的关系又拉到“太阳底下来烤”。


*** 国际社会是否会再一次掀起一轮日本“有无资格”大讨论？

不过，首席评论员则表示，还好，朝鲜这次并没有点日本的名，这样一来，这篇评论的“警告色”非常浓厚，不然，一旦朝鲜明确点日本的名，并要求根除日本的“核武能力”，那么，一旦中国也择机公开地表示支持、日本在继历史问题之后，可以肯定的是，日本“内心深处的阴暗面”将再次被国际社会“暴晒”。

在我们看来，一个在历史问题死不认错的日本、拒不清算法西斯行为的日本，不仅想当常任理事国，而且还想着当核大国，那么，国际社会是否会再一次掀起一轮日本“有无资格”大讨论，其可能性绝对很大，尤其是伊朗那边、伊朗又在给欧盟“脸色看”的时候，东方评论员认为，不排除一旦伊朗拿着朝核问题之现状说事、坚持不让步，欧盟是否会就伊朗的要求找华盛顿、和联合国原子能组织“讨要个”“朝核问题的解决经验”、也不是不可能的。

*** 韩国和朝鲜似乎在敦促日本“认清形势”

不难看出，韩国和朝鲜的这些个让美国和日本“无法反对”的提议，应该是在给美国、特别是日本施加新的压力，并似乎在敦促日本“认清形势”：那就是，在决定是否尽一步“放出日本”之前，一定要考虑亚洲国家的意见，不然，将在亚洲陷于孤立的美国、将进一步依靠日本，这样，美国要么被日本所胁迫、答应给日本以核武装，那么，亚洲其他国家也将会要求核武装，那一天，也必然是美国军事力量离开亚洲、包括日本的那一天。

*** 乘着中日之间刀光剑影，华盛顿催促北京尽管快解决朝核问题

因此，东方评论员认为，这几天、乘着中日之间刀光剑影之际，想收渔人之利的华盛顿、终于开始以旁观者的姿态开始在朝核问题上“兴风作浪”、在台湾问题只不过仍然只是在“闹得水响”的时候、就在催促北京尽管快解决朝核问题了。


*** 这一篇专访和一篇评论，让国际社会第一次看那张“东亚核竞赛”牌的“全貌”

在我们看来，在北京最看重的“两岸三通”还八字都没有一撇的时候，又怎么可能去帮华盛顿去搞什么朝鲜无核化，有意思的是，就在这几天日本登鼻子上脸，北京不得已一改在中日关系上“默不做声”的态度、而暂时将目光“只盯着”日本、从而立刻让华盛顿“找到了施加压力机会”的时候，朝鲜半岛传来的这一篇专访和一篇评论，客观上帮助了中国、让美国、也让国际社会第一次看到了北京手中的那张“东亚核竞赛”的牌的“全貌”。

*** 看到这种因历史问题引起的麻烦“没完没了”日本会如何选择呢？

在这种情况下，东方评论员认为，如果华盛顿在“朝核问题”的无核化范围是否会延伸到日本的问题上，不能给日本一个具体的说法，而日本在亚洲国家面前还拒不低头的话，那么，可以肯定的是，中国、朝鲜，甚至是韩国，是极可能继续利用“朝核问题”“重新定义”这个问题，一边压华盛顿在日本是否应该清除核武装能力上、在日本历史问题上“应该有个态度”，一边象对待、处理日本历史问题那样，将日本无核化与日本入常的问题“再挂钩”，从而在国际上继续“讨个说法”。

看到这种因历史问题引起的麻烦“没完没了”之前景的日本，会如何选择呢？其实，在我们头脑里，李登辉今天“提前24小时”的狗急跳墙，似乎已经暗示了某种答案，就让我们一起试目以待好了。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
