# -*- org -*-

# Time-stamp: <2011-08-04 13:03:22 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent
* 2005年8月23日 星期二

** 中俄军演双方导演部对第三阶段演习充满信心


【中新网8月23日电】中国军网刊登图片报道称：“和平使命—2005”中俄联合军事演习第二阶段演练结束时，双方导演部和联合指挥部的将军们手挽手合影，对定下联合战役决心以后即将展开的第三阶段实兵演习充满信心。

第三阶段是实施交战，依托海上封锁、两栖登陆和强制隔离作战3个实兵课目，演练中俄双方共同应对新威胁、新挑战，在统一的战略意图和战役指挥下，所采取的联合军事行动。

“和平使命—2005”中俄联合军事演习第二阶段22日结束。中俄双方总导演对这一阶段取得的成果表示祝贺，对表现突出的两国军官给予褒奖，并颁发了奖章。


海上封锁作战演练中国168舰参战

参加“和平使命-2005”中俄联合军事演习的双方海空军部队，经过数天高强度实兵对抗，23日在山东半岛东南海域进行海上封锁作战演练。

11时许，首先演练夺取和保持局部海区制空权。中方多批先进战机飞临作战海区，以空中待战和截击行动，对海上联合机动编队实施空中掩护。随即，联合部队空军后续梯队临空，“敌”我双方围绕夺取局部海区制空权展开激战，中方发射空对空导弹，拦截来袭“敌”机，有效控制作战海区的制空权。

在保持作战海区制空权的同时，海上联合机动编队针对来袭的“敌”潜艇，实施海空立体反潜作战。舰载反潜直升机持续实施对潜搜索，并发射反潜鱼雷实施对潜攻击。水面舰艇编队在直升机引导下，编队发射火箭深水炸弹，一举将来袭潜艇“击沉”。

11时20分许，在中俄预警机和巡逻机的引导下，首先由潜艇发射潜舰导弹，对“敌”水面舰艇编队实施隐蔽攻击。继而，中方歼轰机临空，连续发射空舰导弹对“敌”实施突击，俄方驱逐舰发射“马斯基特”导弹对“敌”舰进行精确打击，中方水面舰艇编队利用巡逻机数据链传输的目标信息，连续发射数枚导弹，对“敌”实施超视距远程毁灭性打击。

在海上连续突击的同时，联合机动编队运用预警系统及时发现“敌”空中来袭兵力兵器，组织编队舰空导弹和速射火炮，对来袭飞机、导弹进行拦截。同时发射红外干扰弹、光电干扰弹、箔条干扰弹，对不同制导方式的来袭导弹实施软抗击，削弱了“敌”空中反击能力，赢得了海上封锁作战的主动权。

参加海上封锁作战演练的兵力有：俄罗斯太平洋舰队“沙波什尼科夫海军元帅”号大型反潜舰、“激烈”号导弹驱逐舰、“卡-27”舰载直升机和A-50预警机；中国海军的3艘驱逐舰、3艘护卫舰、2艘潜艇以及20架各型飞机。

中央军委委员、中国人民解放军总参谋长梁光烈上将，中央军委委员、海军司令员张定发海军上将，中央军委委员、第二炮兵司令员靖志远上将现场观摩演练。

俄罗斯国防部作战组组长、陆军副总司令、中俄联合军事演习导演部俄方总导演莫尔坚斯科伊上将，中国人民解放军总参谋长助理、中俄联合军事演习导演部中方参谋长章沁生少将也观摩了演练。

这次海上封锁作战演练是由北海舰队司令员张展南海军中将和俄罗斯太平洋舰队司令费奥多罗夫海军上将指挥的。



【时事点评】我们注意到，在这次联合演习阵容上，在海面上、中方参演的军舰包括168新型驱逐舰、136现代级驱逐舰、567江卫级护卫舰、而在水面下，解放军也有最新型常规潜艇登场。

*** 今天的演练可以说是“美日”最关注的部分

在东方军事评论员看来，今天的演练可以说是美国、日本“最为关注的部分”，既中俄两军的“合成演练”，事实上，之前，美军太平洋司令所说的、“我们也想看看他们能拿出什么东西来”、实际上就是指的这一部分。

我们认为，通过全方位监视这次军事演、在军事层面，“美日军事同盟”最想搞清楚的就是两件事：第一，“中俄两军能否形成战斗合力”；第二，解放军最具威胁的水下突击力量、是否已经对美国庞大的海上军事目标形成了“威慑力”。


*** “潜射反舰导弹”将逐渐成为一种“主流攻击手段”

我们注意到，根椐中俄“联合作战计划”，中国海军编队与俄罗斯太平洋舰队编队将一起配合、对海区实施封锁、同时、两军空降和机降部队也将实时举行空降突袭作战。包括图－95轰炸机和战斗机在内的二十多架飞机首先“控制战区制空权”和“打通空降场”。

在双方将如何配合、并实现战役目标的问题上，请大家注意这一段，原文是：在中俄预警机和巡逻机的引导下，首先由潜艇发射潜舰导弹，对“敌”水面舰艇编队实施隐蔽攻击。继而，中方歼轰机临空，连续发射空舰导弹对“敌”实施突击，俄方驱逐舰发射“马斯基特”导弹对“敌”舰进行精确打击，中方水面舰艇编队利用巡逻机数据链传输的目标信息，连续发射数枚导弹，对“敌”实施超视距远程毁灭性打击。

我们知道，潜射反舰导弹是现代潜艇作战的重要手段，而且其发展趋势显示、这种攻击方式将逐渐成为潜艇打击海面、天空目标的一种“主流攻击手段”。


*** 这是一场“高水准的海上实兵演习”、具有“鲜明的针对性、与实用性”

据我们观察，发射潜舰导弹对“敌”水面舰艇编队实施隐蔽攻击的是中国新型常规潜艇，而向这艘潜水艇“提供目标数据”却是“中俄”预警机和巡逻机，这就是说，通过这次配合、使这次联合军演显现了“海空联合作战的特征”、并证明了中国海军“水下”攻击部分与空中预警部分、在“数据链”上“已经成合成出了战斗力”。毫无疑问、就凭这一点、这是一场“高水准的海上实兵演习”、具有“鲜明的针对性、与实用性”。


*** 解放军发展潜射导弹的“简明历史”

据我们了解，早在80年代、解放军就制造了一种称之为“鹰击-8”的、以潜艇为平台的反舰导弹，并为此专门改造了一艘老式33G型潜艇。

然而，由于限于当时技术上的储备不足、这种最大射程仅有42公里的导弹、不仅没有相应的水下发射装置、也只能够以“水面状态”发射，甚至整个导弹的弹翼也没有实现折叠。

后来，随着技术的进步，解放军抛弃了这种水面发射方式、特别是在90年代、在39型“宋”级潜艇服役后，从鱼雷管发射潜射反舰导弹才真正走向“实用化”。据我们所知、目前、解放军定型列装的反舰导弹为“鹰击-82”型导弹，采用涡轮喷气发动机，射程在150公里以上。

显然，在军事评论员看来，如果没有意外的话，今天在中俄预警机和巡逻机的引导下、由潜艇在水下发射的这枚潜舰导弹、就是“鹰击-82”型。此外、值得一提的是，解放军还在自制的同时、引进了俄罗斯的潜射反舰导弹，其射程约在200公里左右。


*** 在“信息获取”的能力上，“老式”和“新型”潜艇似乎没有大的差别


然而，仅有好的潜射导弹和发射平台，仍然不足以形成“足够的威慑力”。东方军事评论员认为、水下的潜艇在“信息获取”的能力上、事实上不足以让一枚能够攻击100到200公里外目标的导弹充分发挥出其“打击效能”。

道理很简单，就目前的技术而言，眼下世界上最先进的潜艇都不可能依靠“艇载系统”探测到50公里开外的目标，在这方面，“老式”和“新型”潜艇似乎没有大的差别、在我们看来，它们都是“近视眼”。


*** 潜艇要想进行“超视距”导弹攻击必需得到“水上平台”的支援

因此，一艘搭载先进潜射导弹的潜艇、要想进行“超视距”导弹攻击、首先就得“看得远”，这样、就必需得到“水上平台”的支援。显然，我们认为，这种“水上平台”可以借助搜索面较潜艇大得多的海面舰只、也可以借助搜索半径更大的、停留在天空中的预警心机、巡逻机、以进行“目标搜索”、和“数据指引”。当然、如果要在远离陆地的深海作战、就得借助探测距离更远的军事卫星进行目标引导了。

不难看出，在这种情况下、是否能够确保“水下发射平台”与“水上搜索、引导平台”之间的“良好通讯能力”、就显得极其重要。

值得强调的是，就在2003年，据我们了解，解放军已经成功地解决了“超远程保密通信”的问题，这样，加上中国已经开发出自己的大型、先进的预警机、以及性能非常不错的军事侦察与通讯卫星，覆盖范围、指示精确都“够用”的卫星导航系统，这样，解放军实际上已经可以让大多数“新、老型号”的潜艇都能够具有相同的超视距攻击的“技术能力”。

*** “真正标志着”中国的潜艇已经具备了远海、“超视距”作战能力

另外，军事评论员还认为，值得强调的是，今天解放军通过展示这种“通过空中搜索、引导”、再“由水下发起攻击”的“海、空、天三维立体联合作战”模式、才“真正标志着”中国的潜艇已经真正具备了远海、“超视距”作战能力。

事实上，不论从什么角度来看，解放军实际上已经成为了世界上为数不多的、“可以完全依靠自己的资源”、在大洋深处进行“超视距攻击”、或者对大型海上目标进行“远程精确打击”的武装力量


*** 解放军向世界展示潜艇的“超视距”作战能力、其战略意义是极其深远的

东方军事评论员认为，解放军海军选择这个全球注意力都聚焦在黄海的时候、向世界展示潜艇的这种“超视距”作战能力、其战略意义是极其深远的，在我们看来，这将意味着在未来可能的冲突中，这种“海空”、甚至“海天”联合作战模式所带来的“超视距”攻击手段、将是解放军攻击海上大、中型目标（诸如航空母舰、驱逐舰）的“重要远程打击手段”。

我们知道，潜艇部队是中国海军的主要威慑力量、因此，中国潜艇这次展示的“潜对舰”导弹“超视距”攻击能力，将正式标志中国在潜水艇战术的运用上、上了一个新台阶。也正因意义如此重大，华盛顿方面也就“恰到好处”地、抛出了一个针对中国潜艇的“威胁论”。

下面，我们就来看一下相关报道、之后，东方军事评论员将继续回到这个话题。



《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com


** 美军出台《增强反潜作战能力》报告、欲逐步加强反潜链条


【国防知识报报道】美海军出台了一份名为《增强反潜作战能力》的机密研究报告，报告认为潜在敌国的柴电潜艇数量正不断增多，还称俄罗斯、伊朗等国的潜艇以及朝鲜的小型潜艇也会构成一定威胁。为此，报告主张美国海军以更多经费加强侦察搜寻设施，改善武器装备，大力提高美太平洋战区反潜作战能力，以“快速摧毁具有相当规模的常规动力潜艇部队”，以遏制亚太各国迅速掀起的潜艇发展热潮，同时也为未来卷入潜在的台海和朝鲜半岛危机奠定基础。

据美国《海军时报》等媒体近日报道，瑞典海军“哥特兰岛”号常规攻击潜艇日前抵达美国圣迭戈北岛海军航空站，开始充当“假想敌”协助美海军苦练反潜作战。美国海军认为，未来战争中，对手将通过部署噪声较小的柴电潜艇的方式，阻止美军进入至关重要的沿海战略地区。这些海底深处“寂静无声”的杀手，很难被发觉，美军舰艇极有可能经常会成为敌军鱼雷的攻击目标，海军作战部队在沿海水域的自由出入将变得非常困难。为应对未来战争和潜艇的威胁，近年来，美军急于提高其在亚太地区海域的反潜作战能力。为此，美军不仅租借外国潜艇苦练反潜本领，还出台了一份名为《增强反潜作战能力》的机密调查报告，并专门成立了太平洋舰队反潜作战司令部以加强反潜作战协调与组织，还正在研制一种新型海上反潜侦察机。美海军的一系列行动证明其准备在亚太打一场反潜战。


强调“增强反潜作战能力”

2003年5月，美海军出台了一份名为《增强反潜作战能力》的机密研究报告，报告认为潜在敌国的柴电潜艇数量正不断增多，还称俄罗斯、伊朗等国的潜艇以及朝鲜的小型潜艇也会构成一定威胁。为此，报告主张美国海军以更多经费加强侦察搜寻设施，改善武器装备，大力提高美太平洋战区反潜作战能力，以“快速摧毁具有相当规模的常规动力潜艇部队”，以遏制亚太各国迅速掀起的潜艇发展热潮，同时也为未来卷入潜在的台海和朝鲜半岛危机奠定基础。

报告建议：①建立反潜战训练机制、成立高级反潜战中心以增强对敌潜艇打击能力，并进行实际训练。②发展可部署的预警技术，比如传感器、定位系统以及信息网络。③发展可在浅水中发挥威力的机载反潜战鱼雷。④明确现有声纳浮标物资及其他机载反潜战能力的不足。⑤保证对未来海上巡逻机及反潜战直升机发展的资金投入。⑥调整3艘～6艘攻击潜艇至太平洋地区，报告称：“分析表明派驻3艘以上的潜艇至关岛或夏威夷的基地将大大提高美军太平洋战区的反潜战能力。”⑦在美国东西海岸发展浅水测试地带。⑧派遣25艘具备反潜作战能力的濒海作战舰（目前正在生产中）至太平洋地区。

成立反潜战司令部

2004年4月8日，美海军太平洋舰队在圣迭戈成立了舰队反潜战司令部，主要负责反潜作战，全面筹划反潜力量。这一新的作战司令部使命包括集成先进的反潜作战网络、建立反潜作战条令、探索作战概念、负责反潜战训练并辅助海军领导人制定反潜战策略，为联合反潜作战及训练设定统一的标准，确保美军与盟军安全进出战区，能够在海上形成一道防护网，为在舰队转型的同时保持反潜战的作战效率。


美国P-3反潜机

具体来说，舰队反潜战司令部执行的任务将逐渐增加，主要集中在5个反潜战领域：通过高水平的舰队反潜战训练提高海军反潜战能力；在战区、作战小组、单艘舰船、潜艇及飞行中队等各个层级上对作战能力进行评估；协调每个学员反潜战训练的改进和训练资源；鼓励创新，并加快获选的新的反潜战技术和训练方法的交付过程；提高战区水下作战能力。美太平洋舰队官员指出，目前，太平洋舰队辖区大，反潜力量过于分散，Ｐ－3Ｃ反潜机大多已过不惑之年，若不全面筹划反潜力量，将空中、水面与水下反潜力量联合起来，太平洋舰队则难以应对亚太地区潜艇数量增多而带来的潜在威胁。美海军作战部长克拉克上将表示，海军应能保证联合部队从海上向内陆目标迅速接近，而近岸环境下的战场空间控制对海军这一能力的体现至关重要。在该关键地区，未来高效反潜战要求的将不仅仅是先进的技术和新的思路，更要求先进网络和传感器的高度集成、新的作战概念和舰队反潜战训练。舰队反潜战司令部由一名海军将级军官领导，作为第三梯队司令官受美海军舰队司令部司令管辖。舰队反潜战司令部的创立和初始运作将由美太平洋舰队司令负责。

更新作战理念

美海军舰队反潜战司令部成立后，积极研究制订了新反潜作战方案，以对抗柴电潜艇。今年3月美国海军反潜作战部队指挥官约希哈拉上校宣布，美国海军研究、制订一种全新方法，突破潜艇海底封锁，弥补美军现行反潜作战战术中的不足。2004年12月出台的全新“作战概念”已于2005年初得到了美国海军作战部长克拉克上将的批准，开始实施，舰艇指挥官将于近期开始接受培训，学习对抗敌方柴电潜艇、突破海底封锁、迅速进入沿海战区的非传统战术。克拉克上将认为全新反潜作战概念与指导反潜战的传统方法有明显的区别，新作战概念的制订是一个明显的进步，是冷战以来美国海军第一部旨在发展反潜战术和技术的指导性文献。全新反潜作战概念的核心是在未来武装冲突中，美军指挥官将通过部署在沿海战略地区的小型传感器网络，及时得到关于敌方潜艇可能部署位置的更加准确的情报，在进入相应水域前能够及时掌握敌方潜艇兵力部署情况，迅速抢占先机，夺取制海权。现在，美军舰艇无法及时得到这类情报，通常使用对可疑区域实施密集火力侦察的方式防护敌方潜艇攻击。这种防御姿态造成了美国舰艇的机动困难，很难顺利进入特殊战区，特别是未来可能发生战事的沿海战略水域。此次通过的全新作战概念采取“进攻态势”，要求美军舰艇迅速反应，在敌方有机会部署潜艇之前，快速进入斗争区域，击退敌方进攻。

负责作战行动的美国海军作战部副部长纳斯曼上将表示，对美国海军来说，全新反潜作战概念中快速反应设想是史无前例的，先前，美国海军并不是特别重视反潜作战，视反潜战为“非常缓慢的战事”，不屑一顾。纳斯曼上将认为，对美国海军指挥官来说，在与敌方潜艇对抗时，最大的挑战是如何掌握机敏的战术和迅速获取情报的能力。在反潜行动中，美军不能仅仅依靠潜艇、水面舰艇和飞机，还需要各种水上和空中传感器，及时搜集情报，提供完整的战场空间态势图，实时向各舰艇指挥官通报。

美军反潜部队指挥官约希哈拉上校指出，新作战概念规定要尽量缩短反应时间，争取从先前的数月缩短到数日，成功实施这一概念的关键在于具体背景下迅速掌握主动权的能力，确保美军控制未来战斗空间，总之，是保障迅速进入某个区域并对其进行控制的能力。约希哈拉上校宣布：“先前的战略是建立在磨擦基础上的。我们过去试图更多的杀死他们，以避免自己被他们杀死。现在的新概念认为，我们没必要一定要消灭？敌方？潜艇，我们只是要保障在能够让我们感到满意的环境中行动。”非传统反潜战术主要是为未来战争设计的，广泛采用一些最基本的战斗原则：诱骗和欺诈、信息战、心理战。非传统反潜战术主要用于解决一个基本问题：如何影响敌军行动以迅速进入作战区域完成我们的使命？约希哈拉上校表示，海军领导人确信这一战略将会非常有效，因为它考虑到了实战经验和舰队指挥官的需求，是由军事专家在分析现实情况、准确预测未来战斗局势的基础上制订的。总部设在圣迭戈海军基地的反潜作战司令部，负责搜集各舰队信息，了解各舰队在填补能力缺口时的需求，保障指挥官优先权的满足。如果不能提供这种支持，无法满足舰队需要，新作战概念可能就会被舰队指挥官们否决。

现在美国正为提高反潜作战能力加紧忙活着，但是目前美军能否快速提高反潜作战能力还面临的一些困难。首先是一体化指挥控制网的建设问题，如果美国海军和其他部队不能部署和发展完善的指挥控制网的话，是无法达到既定目标的。五角大楼虽已斥资数十亿美元发展军事高科技通信，却没有重视能与所有军事装备实现一体化联接的联合指挥控制网的建设，目前距离把所有装备都联接在一起的能力还有很大的差距。其次，海军非常需要能自动处理情报的传感器，但可能不会有足够的带宽保障向陆上或海上？舰艇？人工控制的工作站实时传输大量数据，这对技术人员来说是个非常严峻的挑战。第三，为满足未来反潜作战的需要，必须研制和装备制导精确度更高的高速攻击鱼雷和其他新型武器。据悉，为保证上述问题及时得到解决，美国海军反潜部队计划与军工企业密切配合，经常向后者提出较为广泛的技术装备要求，保障反潜作战能力的全面实施。

积极研制新一代反潜机

据美国《每日防务》4月1日报道，美海军会在5月份对新一代ＭＨ－60Ｒ反潜直升机的机载武器系统进行作战评估。该武器系统由洛克希德·马丁公司研制。美海军将在今年12月份接收首批4架ＭＨ－60Ｒ。ＭＨ－60Ｒ飞机由联合技术公司的分公司西科尔斯基公司制造，将取代美海军所有的ＳＨ－60Ｂ和ＳＨ－60Ｆ直升机。ＭＨ－60Ｒ集ＳＨ－60Ｂ和ＳＨ－60Ｆ的功能于一身，并在系统功能上作了更大的改进，例如改进了ＡＰＳ－147雷达、电子侦察系统和ＡＮ／ＡＱＳ－22反潜战系统。ＭＨ－60Ｒ飞机有望到2006年2月进入批产阶段。美海军计划采购254架ＭＨ－60Ｒ。对ＡＰＳ－147雷达的改进包括新增了逆合成孔径雷达，能够提供目标识别、长度测量等功能，并可存储图像留作进一步分析使用。对该雷达的其他改进还包括潜望镜探测、任务预规划和数据融合。ＡＬＱ－210的改进包括拓展了工作频率，提高了系统的方位角精度和敏感度。ＡＮ／ＡＱＳ－22的改进包括提高了目标探测与定位的信号处理能力以及水声任务计划能力。美海军试验工作队已于2月15日完成了技术评估，在5月1日开始阶段性的里程碑评估。在技术评估期间，美海军ＨＸ－21和ＶＸ－1试验中队同时对所有机载武器分系统的使用和开发性能进行了测试，重点测试了多功能雷达、电子侦察系统与雷达告警接收机、机载吊放式声纳与音响设备和数据融合的性能等。

此外，6月22日日本广播协会电视台报道，美军的4艘新型潜艇将于近期建成，美国计划今后至少将其中的2艘部署到太平洋地区。这种被称为ＳＳＧＮ的新型潜艇可以搭载相当于4艘导弹巡洋舰规模的154枚战斧巡航导弹，而且配备有可秘密护送特种部队登陆的小型潜艇。据美国海军当局人士透露，第一艘新型潜艇将于今年秋天建成，通过试航后，4艘中至少2艘将在2007年正式部署到亚太地区，以参加该地区的作战行动。报道称，这批新型潜艇将以关岛等为据点，监视中国和朝鲜半岛的局势。美军还准备向其太平洋司令部辖区增派78架海上巡逻机，以大幅提高海军对抗中国等国常规柴电潜艇的能力。

租借潜艇“假想敌”陪练提高反潜

英国《简氏防务周刊》报道称，瑞典皇家海军Ａ－19级潜艇“哥特兰岛”号在今年5月底由一艘重型驳船运载从瑞典出发，6月28日到达加利福尼亚州圣迭戈北岛海军基地加入到美海军第11潜艇中队。这份连艇带人年费用高达1750万美元的租借协议是在瑞典国防物资管理局和美国之间签订的。“哥特兰岛”号将驻扎在美国，将继续挂瑞典国旗，其上的艇员和岸基保障特遣分队（包括技术人员和备用艇员）都是瑞典人，美方人员将登艇进行观察和协调。在该艇出发前，它在考库姆公司进行了一次维修，主要包括给该艇安装一套新型卫星通信系统、改进空调系统、增加淡水产生装置和一套商用海上通信设备的应急电源。“哥特兰岛”号攻击潜艇指挥官维斯塔丝表示，“哥特兰岛”号攻击潜艇和艇上作战人员是分开抵达美海军航空站，作战人员目前已经做好战备准备，随时可执行出海作战任务。对于“哥特兰岛”号攻击潜艇来说，此次也是其首次部署到太平洋海域执行军事任务，这攻击潜艇的艇员编制为33人，此次赴美参演军事任务的瑞典海军有30人，其中包括19名军官和11名士兵。

根据美海军制定的计划，“哥特兰岛”号攻击潜艇将在美海军反潜作战训练中扮演敌军部队的角色，作战任务为对抗美海军航母打击大队和远征打击大队、空中巡逻部队以及其他部队。在长达一年的租借期内“哥特兰岛”号将会频繁地与美海军展开反潜练习，除去休整与补给的时间外，一年之中将有160天的训练时间。也就是说，瑞典潜艇一年之中有近1／2的时间当美军陪练，要扮演随时袭击美军的“敌人”。

瑞典的潜艇制造技术世界一流。此次美海军租借的“哥特兰岛”潜艇是目前世界常规潜艇家族中的佼佼者。瑞典海军“哥特兰岛”级常规潜艇首艇“哥特兰岛”号于1992年11月开工建造，1995年2月下水，1996年4月服役。该级艇长60．4米，宽6．2米，吃水5．6米，水上排水量1240吨，水下排水量1490吨，水上航速10节，水下航速20节，水下继航能力336小时／6节，下潜深度200米。装备4具533毫米和2具400毫米鱼雷发射管，共携带雷弹18枚。此外，还装备了可携带水雷的外挂装置，可带水雷22枚。瑞典海军共装备了三艘该级潜艇，即“哥特兰岛”号、“乌普兰”号及“霍尔兰”号。“哥特兰”潜艇最引人注目的地方就是装备了不依赖空气动力装置？ＡＩＰ？，极大地增强了潜艇的隐蔽性。一般来说，常规潜艇在航行时需要定期上浮，用消耗空气的柴油发电机为电池充电，因此很容易被敌方的雷达与声纳探测到。但采用ＡＩＰ技术的“哥特兰岛”潜艇却可以在水下航行时为蓄电池充电，能在水下连续航行数周，从而大大降低了暴露的几率，同时噪声也大为降低。此外，该潜艇为长水滴外形，经过了多次流体动力学试验，具有航行阻力小、噪声低的特点，还具有良好的稳定性和操纵性能。目前在常规潜艇中，只有同样装备有ＡＩＰ的俄罗斯“阿穆尔”级潜艇能与之媲美。


美国海军海狼级核动力攻击潜艇

国际分析人士亦指出，瑞典海军“哥特兰岛”号攻击潜艇之所以被美海军选择为“假想敌”陪练反潜，原因就在于该潜艇拥有独特的ＡＩＰ推进系统。目前美军虽然拥有强大的核潜艇部队，速度和马力都比柴油引擎潜艇好，但潜艇的攻击对抗活动是从在海水中确认对方位置开始，而新式柴油潜艇引擎相当安静，因此美军将其视为重要威胁。而且一直以来，美海军进行的反潜训练都是用美军自己的潜艇充当“敌方”，即使在与盟国的反潜作战演习中，也一般围绕协同作战、敌我识别等课目展开，假想敌的扮演者仍是美军自己。由于目前美海军中已没有常规潜艇服役，美海军只能用体积庞大的核潜艇代替小型常规潜艇训练，加之演练中的“敌我”双方都比较熟悉各自的战术战法，因此美军每次的反潜作战演练看似效果不错，但实际上只是“捉迷藏”游戏的翻版。美国大西洋舰队潜水艇部队指挥官唐纳德中将高度赞扬了瑞典潜艇的性能，认为这一租借活动将大大地提高美海军的反潜能力。

美军担心来自亚太地区的威胁

随着美军战略重心转向亚洲，美国越来越担心来自亚太地区的海洋下面的“威胁”。亚太地区水域广阔、岛屿众多，造价低廉、隐蔽性能好、威胁力大，能执行海上封锁、侦察监视、水下袭击、特种作战等多种任务的潜艇受到各国的青睐，成为近年来各国军备力量建设中的重中之重。据美国军事专家估计，亚太水下有近100艘潜艇在秘密活动。目前世界各国的潜艇加起来才700余艘，其中还包括在建未下水的。据美国媒体称，在东南亚，印尼拥有6艘潜艇，而且今后还打算购买与研制20艘潜艇。新加坡和越南也早已迈入潜艇国家之列，新加坡海军目前拥有4艘“海蛇”级潜艇。马来西亚从法国和西班牙订购了2艘常规潜艇。另外泰国准备外购或租用潜艇，菲律宾也计划引进该国历史上首艘潜艇。预计到2010年，仅东盟国家就将至少拥有20艘常规动力潜艇。在东亚，一向神秘的朝鲜潜艇部队被美军认为是其对抗美军的撒手锏。据美国媒体公布的资料称，朝鲜潜艇分别部署在日本海和黄海，其中以日本海居多。美军认为，这对其海军构成了不容忽视的威慑。另外，美国的老对手俄罗斯也有30多艘潜艇，且目前还正大力加强潜艇部队建设，研制更加隐蔽、机动速度更快与打击力更强的战略核潜艇与常规潜艇。关于中国的潜艇，西方军事观察家一直认为这是一支不可忽视的水下力量。

美国海军认为，未来战争中，对手将通过部署噪声较小的柴电潜艇的方式，阻止美军进入至关重要的沿海战略地区。这些海底深处“寂静无声”的杀手，很难被发觉，美军舰艇极有可能经常会成为敌军鱼雷的攻击目标，海军作战部队在沿海水域的自由出入将变得非常困难。因此，美军越来越担心潜艇对其构成的潜在威胁。

美国海军官马克·爱德华海军少将称，由于太平洋地区各国拥有的潜艇数量众多，且其中有196艘的所有者不是美国的盟国，美国及盟国海军必须针对它们进行训练，了解其性能特点，找到对付它们的办法。美国海军前太平洋舰队司令法戈则表示：“世界正在改变，重心已经转移到亚太地区。该地区应是美海军未来主力所在，但美军在亚太地区的潜艇只有23艘，远不及该地区的其他国家潜艇的数目。”


美国海军反潜战专家斯蒂文斯上校指出，大部分常规潜艇，特别是噪声很低的潜艇，无法被装配在美国海军核潜艇和水面战舰上的传统声纳设备所发现，主要原因在于现代化柴电潜艇都有比较先进的推进系统，能在水下安静地行驶，同时还采用隐形技术，铺设吸波涂层。另外，仅靠技术装备还是无法保障获得决定性的优势，精巧的战术和有针对性的严格训练肯定能弥补落后技术装备的不足。斯蒂文斯上校表示：“我们不能轻视旧潜艇，哪怕是20年或30年以前的，它们也可能成为我们强有力的对手，许多事情取决于他们的人员训练和军事学说。一艘技术装备水平低的旧潜艇，如果拥有非常有竞争力的乘员，可能会比那些装备最为先进但人员训练水平和意志较差的最新型潜艇强大，构成一个更大的潜在威胁。”

可以看出，亚太各国目前积极发展潜艇，而美国军方要“增强反潜作战能力”，这显然是“先发制人”的一步棋，是“先发制人”军事战略的又一具体体现。




【时事点评】首先，我们之所以将此文“全文转载”，就在于这篇文章非常全面地描述了美军的心态，即在面对各国、特别是中国日益加强水下攻击力量的时候，明显地在为其不可一世的航空母舰战斗群“担着惊、受着怕”。

然而，我们也注意到，对这种具体的威胁，负责作战行动的美国海军作战部副部长纳斯曼上将表示，对美国海军来说，全新反潜作战概念中快速反应设想是史无前例的，并认为“先前，美国海军并不是特别重视反潜作战，视反潜战为“非常缓慢的战事”，不屑一顾”。


*** 美军“反潜”、从来都是“只怕做不到、而不怕想不到”何来的“不屑一顾”之说？

对此，军事评论员认为，美军海军作战部的这位军事高官、之所以说出“不屑一顾”的大话来、恐怕是心中又在“泛酸”。根据我们的观察，恰恰相反，由于前苏联对美国海军航空母舰最大的威胁就来自水下、因此，美国海军也一直将“反潜”列入其作战目标的“重中之重”，在与前苏联的角力中、再加上欧盟、中国、日本、印度的水下力量也在日益增强，都对美军海上航空母舰群构成重大威胁，华盛顿的决策层从来就没有放松对美国盟友的“看管”，而在防备这些军事强权的过程中、美国海军在“追求其反潜能力”方面，“一直在努力地追求最好”，从来都是“只怕做不到、而不怕想不到”、又何来的“不屑一顾”之说？


*** 美军高官对“反潜”“不屑一顾”的真正原因

东方军事评论员看来，这位说“大话”的美国海军作战部副部长纳斯曼上将对“反潜”“不屑一顾”的真正原因，其实在他这句话中已经“不小心地”给“点破了”，这就是，以今天的军事技术而言，“反潜战”对任何一个国家而言，的确为“非常缓慢的战事”。


因此，为了改变“不屑一顾”的军事指导思想，我们注意到、美军约希哈拉上校宣布：“先前的战略是建立在磨擦基础上的。我们过去试图更多的杀死他们，以避免自己被他们杀死。现在的新概念认为，我们没必要一定要消灭？敌方？潜艇，我们只是要保障在能够让我们感到满意的环境中行动。”

另外，在东方军事评论员看来，按美军的这种战术设想，即要保障美军“能够在他们感到满意的环境中行动”、美军计划依靠所谓“非传统反潜战术”、而这种“非传统反潜战术”将主要用于解决一个“基本问题”：如何影响敌军行动以迅速进入作战区域完成我们的使命？


*** 美军准备冒着遭遇“潜艇打击力量”的风险、而进入的“至关重要的沿海战略地区”、只能是台海

那么，美军准备进入到哪些作战区域呢？请注意这一段，原文是：美国海军认为，未来战争中，对手将通过部署噪声较小的柴电潜艇的方式，阻止美军进入至关重要的沿海战略地区。

显然，傻瓜都看得出来，美军准备冒着遭遇“潜艇打击力量”的风险、而进入的“至关重要的沿海战略地区”、似乎只能是台海附近，也有这个地方、才符合美军对未来战争的设想中的“两要素”，第一，美军必须冒遭到军事打击的巨大风险，显然，看看这个世界，能让美军如此小心的军事力量、只有俄罗斯、中国、欧盟、印度这几家；而美军一直叫嚣着要进入的所谓“至关重要的沿海战略地区”、似乎就只有台海这一处了。如此一来，解放军才是美军眼中的“敌人”、才是美军急于反潜的对象，这一点也就不言自明了。


*** 美海军未卜先知“预测出”自己在进入台海时“可能陷入处境”

有意思的是，按中国军方加快发展水下攻击力量、和远程精确打击力量的初衷、也不在于“杀死他们（美军）”、也在于“如何影响敌军行动以迅速进入作战区域、以完成我们的使命”。在我们看来，就这点而言，“中美”双方似乎有点“英雄所见略同”。

再者，东方军事评论员注意到、约希哈拉上校似乎非常“确信这一非传统战术将会非常有效”，理由是“它考虑到了实战经验和舰队指挥官的需求，是由军事专家在分析现实情况、准确预测未来战斗局势的基础上制订的”。


显然，在我们看来，就中美两军在台海附近的对峙而言，在预测“未来的战斗局势”的时候、美国海军已经未卜先知地预测出了自己在进入台海时“可能陷入处境”，请大家注意这一段，原文是：在“未来战争中，对手将通过部署噪声较小的柴电潜艇的方式，阻止美军进入至关重要的沿海战略地区”。而这些海底深处“寂静无声”的杀手，很难被发觉，美军舰艇极有可能经常会成为敌军鱼雷的攻击目标，海军作战部队在沿海水域的自由出入将变得非常困难。因此，美军越来越担心中国潜艇对其构成的潜在威胁。


*** 没有将中国常规潜艇携带的“水下超视距”打击手段考虑在内

不难看出，“美军的预测”似乎“只是在担心”会受到鱼雷的攻击、而没有将解放军今天展示的这种具有先进的推进系统，能在水下安静地行驶、“在浅海海域内比核潜艇灵活得多”的、中国新型常规潜艇携带的潜射导弹、这种“水下超视距”打击手段考虑在内。


*** 一艘能水下发射反舰导弹的攻击型潜艇，将造成敌方反潜力量的“极大负担”

在我们看来，一艘能水下发射反舰导弹的攻击型潜艇，将造成敌方反潜力量的“极大负担”。据相关资料估算、要找寻、并有效阻止这样一艘潜艇的攻击，保护已方的重要目标，一架反潜机“需要警戒的范围”至少比搜寻一艘仅携带普通鱼雷的攻击潜艇、要增加近200倍，而要“警戒”重要目标所处的整个海区、其花费的时间要增加近30倍。

因此、军事评论员认为，如果解放军海军在战术上强调“潜艇群”的作战方式，那么，这将更加使得敌方反潜机需要警戒的海区范围将“成几何级数增长”。


*** 美日”监视力量这次“最为尽心的部分”

另外，军事评论员认为，还有一点值得观察：即，在为这次发射潜射导弹的中国潜艇提供“目标数据”的过程中、俄罗斯军方到底扮演了何种角色还“有待考证”、假如俄罗斯的空中预警机和巡逻机也参与了“战场信息收集与引导攻击”的整个过程，那么，这将标志着中俄两军在“战场信息共享”方面已经取得某种突破。

据说，为全程跟踪监视中俄两国军演，太平洋的美军早已进入“临战侦测”状态，并已形成了从空间到水下“六位一体”的全方位、多渠道、立体侦察监视系统、而日本的侦察系统也是早已就位、瞪大眼睛盯着中俄将拿出什么东西。

显然，这方面的进展正是“美日军事同盟”最为关注的地方、考证“这种可能性”、以及“中俄信息共享到了何种程度”的工作、也是“美日”监视力量这次“最为尽心的部分”。


*** 美国人也清楚，在多种攻击手段面前、航空母舰是一副飘在海上的“活棺材”

显然，在军事评论员看来，美国人也清楚，航空母舰战斗群对付那些没有什么打击力量的小国、弱国绝对是“见谁灭谁”、然而，要恫吓欧盟、俄罗斯、中国、印度这些具战略纵深的“潜在威胁”、且具多种攻击航空母舰手段、特别是远程打击力量、水下攻击手段的军事力量而言，在很大程度上、却是一副飘在海上的“活棺材”。

因此，美国人在拥有世界上最庞大的海面战斗平台的同时、在准备继续享受这种“海面平台占绝对优势”好处同时、也不得不开始思考某种“军事变革”，在我们看来，美军这种将解放军视为“假想敌”、针对中国对海上目标打击力量、特别是远程打击力量的飞跃式提升，华盛顿突然写出了一部“中国潜水艇威胁论”，正是这种“军事变革”中的一部分。


*** 在运用其海军威慑方面、在宣传其台海政策方面、美军有意着手进行某种“军事创新”

此外，军事评论员还认为、除了这种“理论”性的东西之外，在我们看来，华盛顿企图针对中国这样的国家、在运用其海军威慑方面、在宣传其台海政策方面、有意着手进行某种“军事创新”。

请大家注意这一段，原文是，6月22日日本广播协会电视台报道，美军的4艘新型潜艇将于近期建成，美国计划今后至少将其中的2艘部署到太平洋地区。这种被称为ＳＳＧＮ的新型潜艇可以搭载相当于4艘导弹巡洋舰规模的154枚战斧巡航导弹，而且配备有可秘密护送特种部队登陆的小型潜艇。据美国海军当局人士透露，第一艘新型潜艇将于今年秋天建成，通过试航后，4艘中至少2艘将在2007年正式部署到亚太地区，以参加该地区的作战行动。报道称，这批新型潜艇将以关岛等为据点，监视中国和朝鲜半岛的局势。美军还准备向其太平洋司令部辖区增派78架海上巡逻机，以大幅提高海军对抗中国等国常规柴电潜艇的能力。


*** 解放军同样要注意研究应付这样一种局面

显然，美军这是想在西太平洋增强“不易受到攻击”的“水下打击力量”、从而不让易受攻击的、不可一世的航空母舰暴露在中国的各种火力打击之下。在东方军事评论员看来，针对比伊拉克、南斯拉夫强大得多的军事力量、华盛顿似乎准备尝试着让“比现在更加强大的水下打击力量”替代航空母舰战斗群作为威慑的“主打方式”、可以猜测的是，作为今后美军“继续宣传”“一定会介入台海”的“介入模式”、“不易受到攻击”的“水下打击力量”很有可能成为美国宣传的“主要工具”。

因此，在我们看来，中国军方在致力于提高自己的“水下打击力量”、做“军事斗争的准备工作”时、非常有必要在加强研究如何“通过水下”去威胁美国海面上航空母舰的时候、同样要注意应付这样一种局面、即：在台海方向，美国可能会用不易受攻击的“水下打击力量”、来替代易受攻击的航空母舰、前出到台湾近海、并以此作为来威胁中国、支持台独“武力拒统”的主要手段。


另外，我们注意到，美国海军反潜战专家斯蒂文斯上校指出，大部分常规潜艇，特别是噪声很低的潜艇，无法被装配在美国海军核潜艇和水面战舰上的传统声纳设备所发现。
在我们看来，中国官方媒体日前公布的新型常规潜艇、实际上就是这样种噪声很低、不易被现有技术发现的潜艇。在一段相关资料后，军事评论员将简单地介绍一下中国这款新型潜艇的主要性能。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
