# -*- org -*-

# Time-stamp: <2011-08-04 11:51:13 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 2005年7月04日 星期一

 



** 中俄两国共塑负责任的大国形象

【人民日报海外版】7月1日，中国国家主席胡锦涛与俄罗斯总统普京在莫斯科签署《中华人民共和国和俄罗斯联邦关于21世纪国际秩序的联合声明》，这是自1997年中俄发表关于世界多极化和建立国际新秩序的联合声明之后，又一次就如何建立国际新秩序表明共同立场，它展现了中俄两国作为世界大国和联合国安理会常任理事国，对国际公正、安全、稳定、发展与繁荣所肩负的责任。

人类社会的发展是一个不断融合、不断进步的过程。随着文明进步和科技发展，原来分散的国家和洲、区正被紧密联系在一起，形成今天共认的“地球村”，共谋这个“大村”的安全与发展已成为所有“村民”的共同责任。自上世纪创立联合国之后，国际社会避免了发生新的世界大战。但是60年来世界发生了无数的新变化，过去建立的一些政治、经济和安全秩序需要与时俱进的革新。特别是上世纪90年代以来形成的世界格局，为某些国家搞“单边主义”创造了条件；形形色色的恐怖主义、极端主义、大规模杀伤性武器扩散以及国际犯罪对世界安全构成新挑战。广大发展中国家也急切希望通过改革现有不合理的国际秩序求发展，如何建立21世纪国际新秩序，已成为世人热论的话题。

中俄两国本着互信、互利、平等、协作，尊重多样文明，谋求共同发展，创造双赢多赢的新安全观、发展观，提出如何建立国际政治、经济和安全新秩序的原则立场和基本设想，旨在借今年联合国成立60周年之际，与世界各国一道推进联合国的改革，使其更富有代表性、更能有效维护世界和平，促进各国发展。中俄以双边关系从不正常到正常、从睦邻友好到战略互信不断深化的经历告诉世界，只要放弃以对抗为特征的“冷战”旧思维，接受以“协商与合作”为特征的新观念，不论双边还是多边、地区或整个国际间的相互关系都会朝着有利于和平、有利于发展的方向前进。

以实力为基础、以武力为手段建立国际关系的观念已经落后，那种以牺牲其它国家安全关切、保障少数国家或国家集团利益的旧时代应当成为过去，以谋取世界或地区霸权为目标的争斗应当停止。新的时代要求新的思维、新的原则和新的秩序。中俄两国通过自己的身体力行，共塑负责任的大国形象。世界各国特别是大国，应当倾听时代的步伐、世界的声音，拿出勇气和魄力，为建立更加公正、合理、民主、高效的国际新秩序而努力。


【时事点评】纵观胡锦涛与普京1日在莫斯科签署的《中华人民共和国和俄罗斯联邦关于21世纪国际秩序的联合声明》，一共有十二条之多。在东方评论员看来，这份声明可以说是中俄之间专门就国际秩序发表的第一份联合声明，声明的12点内容全部关系到国际事务。

*** 与媒体相比，“联合声明”本身在文字上要含蓄得多

但在东方评论员看来，这份举世瞩目的“中俄联合声明”，从第一条一第九条，实际上是在用大篇幅的文字阐述“什么是21世纪人类面临的核心问题”、和确保解决这一问题“人类应建立什么样的国际秩序的重大问题”，在我们看来，这无异于为全世界描绘出了一幅“和平、正义的远景”。

事实上，资料员从今天的人民日报中为我们挑选的这篇新闻稿、也非常到位地、“从媒体的角度”解读了“联合声明”中的那幅“远景”、也从媒体的角度高度地赞扬了中俄“为这种远景”拿出勇气和魄力、共塑负责任的大国形象。

然而，在东方评论员看来，与媒体相比，“联合声明”本身在文字上要含蓄得多，东方评论员注意到，“联合声明”只是在“字里行间”里“暗示”中俄将联手、致力于建立一个涵盖“政治、军事、经济”方面的新秩序、并以此挑战美国在国际事务中“一家独大”的“强烈愿望”。


*** 仅有“美好的远景”和“强烈的愿意“是不够的，关键是要有“行动方案”

显然，东方评论员认为，仅有“美好的远景”和“强烈的愿意“是不够的，关键是要有“行动方案”。因此，首席评论员就指出，如果从“行动方案”的角度去看的话，那么，整个“联合声明”的核心在“第十条”和“第十一条”。

请看原文：

十、区域一体化是当前国际形势发展的重要特征。双方指出，建立在地区开放、平等合作和不针对其他国家基础上的多边区域组织在国际新秩序形成过程中发挥着积极作用。在经济领域，地区倡议应促进贸易共同体更加开放和富有成效。在地区安全领域，建立兼顾各参与方利益的、开放的、不针对其他国家的安全合作机制具有根本性意义。双方支持各地区一体化组织建立横向联系，营造互信、合作氛围。

十一、中俄新型国家关系正为建立国际新秩序作出重大贡献。中俄关系的实践印证了本声明所述原则的生命力，同时表明，在此基础上可以有效发展睦邻友好合作关系，解决各种问题。两国决心与其他有关国家共同不懈努力，建设发展与和谐的世界，成为安全的世界体系中重要的建设性力量。

*** 中俄所谈妥的“区域一体化”起码有两个方向

显然，上面的“两条”实际说的是如何建立“中俄新型国家关系”，其中，东方评论员注意到，“双方”不仅用到了“区域一体化”这几个字，而且在第十条中、还特别“强调了”这种“区域一体化”在建立美好的“国际新秩序”过程中、应该“发挥积极作用”。

不难看出，“这两条”不仅“点出了”中俄有意“以区域一体化”的方式来“为建立国际新秩序作出重大贡献”，而且还在“反复暗示”这种“区域一体化”不仅是“安全方面”的、而且还涉及“经济领域”。

对此，首席评论员就指出，就这种”反复暗示“而言，“这两条”中还暗藏有这么一层意思，即胡锦涛与普京所谈妥的“区域一体化”起码有两个方向。

为了更好的说明这个问题，我们再看看胡锦涛在与普京签署了《中俄关于21世纪国际秩序的联合声明》之后，于结束俄罗斯行程之际，中俄共同发表的另一份重要文件--《中俄联合公报》的有关内容，之后东方评论员将继续进行这一话题。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com







** 中俄发联合公报就多个重要问题达成一致

【新华社消息】在中国国家主席胡锦涛3日结束对俄罗斯的国事访问，离开新西伯利亚之际，中国和俄罗斯发表《中俄联合公报》。在公报中，两国指出已经就能源合作、军事合作、联合国改革、互相举办对方的“国家年”以及反恐等一系列重要问题达成了一致。联合公报全文如下：

　　中俄联合公报

　　应俄罗斯联邦总统普京邀请，中华人民共和国主席胡锦涛于2005年6月30日至7月3日对俄罗斯联邦进行了国事访问。胡锦涛主席同普京总统举行会谈，分别会见了俄罗斯联邦政府总理弗拉德科夫、联邦会议联邦委员会主席米罗诺夫和联邦会议国家杜马主席格雷兹洛夫。

　　两国元首全面总结了2004年10月北京会晤以来中俄关系的发展成果，本着相互理解和信任的精神，讨论了中俄战略协作伙伴关系的现状和前景，就重大国际问题和地区事务坦诚深入地交换意见，达成广泛共识，确定了双边关系进一步发展的方向和加强两国在国际舞台上战略协作的基本原则。

　　一

　　两国元首满意地指出，在双方共同努力下，中俄政治互信已上升到新水平，各领域合作不断扩大和深化。两国战略协作伙伴关系进入新的发展阶段。

　　双方重申，发展中俄战略协作伙伴关系是两国对外政策的优先方向。这一选择符合两国和两国人民的根本利益，有利于维护地区和世界的和平、稳定、发展。

　　双方将按照2001年7月16日签署的《中华人民共和国和俄罗斯联邦睦邻友好合作条约》的原则和精神，深化政治互信，扩大互利合作，加强在国际和地区事务中的协调和配合，推动中俄战略协作伙伴关系持续稳定向前发展。

　　双方强调，两国元首2004年10月14日批准的《〈中华人民共和国和俄罗斯联邦睦邻友好合作条约〉实施纲要(2005年至2008年)》(以下简称“《实施纲要》”)对未来几年两国各领域合作的发展具有重要意义。双方对《实施纲要》的执行情况表示满意，认为必须继续努力，全面彻底地落实该文件的各项规定。

　　二

　　双方指出，2004年10月14日签署的《中俄国界东段补充协定》同1991年5月16日签署的《中苏国界东段协定》、1994年9月3日签署的《中俄国界西段协定》一起，将长达4300多公里的中俄边界线走向全部确定，为两国睦邻合作和人民世代友好提供了可靠保障，为维护亚太地区及世界的安全和稳定作出了重要贡献。双方决心共同努力，积极落实国界协定及其他与国界有关的协定，把中俄边界建设成为联结两国人民友谊和合作的坚实纽带。

　　三

　　双方认为，两国在涉及国家主权、安全和领土完整的重大问题上相互广泛支持，是中俄战略协作伙伴关系的重要特征。

　　俄方重申在台湾问题上的原则立场，认为台湾问题是中国的内政，外部势力无权干涉。俄罗斯坚持一个中国原则，反对任何形式的“台湾独立”，不接受“两个中国”、“一中一台”，反对台湾加入联合国及其他只能由主权国家参加的国际组织，不向台湾出售武器。俄方理解中方根据《反分裂国家法》为实现国家和平统一所做的努力。

　　中方重申，坚定支持俄罗斯在维护国家主权和统一、打击分裂主义和恐怖主义方面所做的努力。

　　双方认为，中俄国家安全磋商机制的建立，标志着两国安全合作迈上新台阶。双方将充分发挥该机制及两国有关部门安全磋商机制的作用，共同应对新挑战和新威胁，维护两国的共同利益。

　　双方强调，中俄军事合作对深化两国互信发挥着重要作用，有利于维护地区和世界的和平稳定。双方愿进一步推动两军合作和交流。

　　双方认为，《中华人民共和国国防部和俄罗斯联邦国防部关于举行联合军事演习的备忘录》的签署，表明两军交往发展到新的水平。双方将共同努力，搞好中俄首次联合军事演习。双方指出，中俄举行联合军事演习旨在提高两军有效应对新挑战和新威胁的作战能力，不针对任何第三国。

　　双方将在现有基础上，采取实际步骤，促进中俄军技合作向更高水平、更广领域发展。

　　四

　　双方指出，“世代友好、永不为敌”的思想在两国得到广泛支持。双方将继续深化和扩大民间交往，增进两国人民的相互理解和传统友谊，巩固中俄关系的社会基础。双方高度评价中俄友好、和平与发展委员会的工作。

　　双方强调，2006年在中国举办“俄罗斯年”、2007年在俄罗斯举办“中国年”，是未来两年双边关系中的大事。双方将认真筹划，制订“国家年”活动方案。通过举办上述“国家年”活动，为两国政治、经贸、科技、人文等领域的合作增添新的活力。

　　五

　　双方指出，近年来中俄经贸合作保持着快速发展的势头。2004年双边贸易额达到创纪录的212.3亿美元。今年双边贸易仍保持着20%以上的高速增长。

　　双方将进一步挖掘中俄经贸合作的巨大潜力，改善贸易结构，提高机电产品比重，努力使双边贸易额到2010年达到600亿至800亿美元。

　　双方对中俄投资合作的发展势头表示满意，高度评价2005年6月在圣彼得堡举行的第二届中俄投资促进会议，以及会议期间达成的一系列大中型投资项目。双方将继续举办投资促进会议，扩大和提高中俄投资合作规模和水平。双方将在各自法律框架内，积极采取措施，为落实双方达成的合作项目创造良好的投资环境和必要条件，以实现到2020年中国对俄累计投资120亿美元的目标。双方将尽快签署中俄政府间鼓励和保护相互投资的协定。

　　双方指出，第16届哈尔滨经贸洽谈会的成功举办有助于加强和促进两国实业界在实施俄东西伯利亚和远东地区发展战略及中国振兴东北老工业基地战略方面的互利合作。双方将继续积极推进地方合作，鼓励边境地区开展更加紧密的协作。

　　双方将继续落实在投资、科技、运输、航天、民用航空、通讯及信息技术、和平利用核能及银行间合作的项目。

　　双方认为，加强能源合作对提高中俄经贸合作整体水平具有重要意义。此次元首会晤期间双方签署油气、电力等领域合作协议标志着两国能源合作迈出新的一步。双方决心根据《实施纲要》，进一步推动落实中俄在石油天然气领域的合作项目，包括中俄原油管道建设项目和在两国境内共同开发油气田项目，责成两国有关企业就上述项目进行具体磋商。

　　双方强调，积极扩大两国人文领域合作，包括逐步落实双方在文化、教育、卫生、体育、旅游、新闻、电影和档案等领域商定的活动具有重要意义。

　　双方认为，有必要提高环境保护和自然资源利用方面的合作水平。

　　六

　　双方认为，国际局势正在发生复杂深刻的变化。越来越多的国家赞成国际关系民主化、世界格局多极化和发展模式多样化。经济全球化和区域合作不断加深和发展，为各国社会经济发展提供了新的机遇。但世界上依然存在不稳定不确定因素，存在不少“热点”地区。传统和非传统安全问题相互交织，严重威胁世界的和平与发展。

　　两国元首高度评价双方签署的关于21世纪国际秩序的联合声明，认为该声明体现了两国对重大国际问题有相同看法和立场，表明两国致力于建立公正合理的国际政治经济新秩序的愿望和决心，有利于推动21世纪国际秩序朝着健康稳定的方向发展。

　　双方认为，中俄战略协作伙伴关系为建立国际新秩序作出了重大贡献。今年是第二次世界大战结束60周年，中俄两国呼吁世界上所有国家就建立21世纪国际新秩序开展广泛对话，决心同各国一道，为建设和谐与发展的世界而不懈努力。

　　七

　　双方重申支持打击一切形式的恐怖主义，主张在联合国及其安理会协调下，根据《联合国宪章》和国际法准则，加强国际社会合作，制定长期、全面的反恐战略。

　　双方反对将恐怖主义同具体国家、民族和宗教挂钩，反对在反恐问题上采取“双重标准”。

　　双方指出，中俄同为恐怖主义的受害者，将进一步加强合作，同这一邪恶势力作斗争。

　　八

　　双方指出，联合国在维护世界和平与安全方面发挥着不可替代的重要作用，必须进一步提高联合国及其安理会在解决重大国际问题方面的核心作用。

　　双方支持联合国改革，认为联合国改革应有助于加强多边主义，提高联合国的权威和效率以及应对新挑战和新威胁的能力。希望2005年9月14日至16日在纽约举行的联合国首脑会议能通过反映千年宣言目标和任务连贯性的决议，加大各国落实这些目标和任务的实际力度，促进提高联合国在关键领域的协调作用，巩固21世纪集体安全体系，建设稳定和公正的国际秩序。

　　双方认为，联合国安理会改革涉及各方切身利益，相关决定应在最广泛协商一致的基础上作出。为避免造成会员国分裂，中俄反对在安理会改革问题上人为设定时限，表决未经协商一致的方案。

　　九

　　双方指出，同中俄毗邻的中亚国家有其独特的历史、文化和传统。双方充分尊重这些国家自主选择发展道路的权利。维护地区和平稳定符合中亚所有国家的长远和根本利益，也有助于整个欧亚地区局势健康发展。双方表示将加强中俄与中亚国家在双边和上海合作组织框架内的协调和合作，以维护该地区的安全和稳定，打击恐怖主义、分裂主义和极端主义。同时，双方重申，将深化和扩大同中亚国家的双边合作，为促进中亚国家经济发展作出不懈努力。

　　双方指出，上海合作组织的建立和发展对加强成员国的睦邻互信和友好合作，促进本地区安全、稳定和经济发展具有重要意义。上海合作组织已成为建立公正合理的国际政治经济新秩序的重要因素。双方将采取切实措施，同其他成员国一道，深化和拓展上海合作组织框架内的安全、经济及其他领域的合作。

　　十

　　双方愿共同努力，本着战略协作伙伴的精神加强合作，维护亚太地区的安全和稳定。双方愿进一步加强两国在东盟地区论坛等区域合作机制下的对话、协调与合作。

　　中国欢迎俄罗斯加入“亚洲合作对话”，愿继续努力促进俄加入“亚欧会议”。中国欢迎俄罗斯与东亚已建立或正在形成的区域一体化体制建立联系。

　　十一

　　双方重申，坚持朝鲜半岛无核化目标，坚持对话和平解决方向，坚持维护半岛和地区的和平与稳定，支持朝韩继续改善关系，支持朝鲜与有关国家实现关系正常化。双方一致认为，六方会谈是寻求解决朝鲜半岛核问题的最好最有效的方式。双方对有关各方近来为推动复谈所做的积极努力表示欢迎。双方呼吁会谈各方保持耐心，显示灵活，以建设性态度积极推动早日重开六方会谈，并使会谈取得进展。双方愿进一步共同采取协调一致的步骤，和平解决朝鲜半岛核问题。

　　双方坚决反对核武器扩散，主张通过外交手段在国际原子能机构框架内尽早解决伊朗核问题。双方支持国际社会为推动政治解决伊朗核问题所做的外交努力，愿在这一进程中继续发挥建设性作用。

　　双方指出，两国元首在友好、互信、合作的氛围中进行了会谈，取得重要实际成果。双方对会晤成果表示满意。

　　中华人民共和国主席胡锦涛邀请俄罗斯联邦总统普京在方便的时候访华。普京总统愉快地接受了邀请。访问具体时间由双方通过外交途径商定。

　　二00五年七月三日





【时事点评】在上面的点评中，我们之所以认为的7月1日的《联合声明》的核心蕴藏在“第十条”和“第十一条”里面，就在于“这两条”清楚地说明，中俄有意“以区域一体化”的方式来“为建立国际新秩序作出重大贡献”，并“暗示”了在中俄有意进行的“区域一体化”合作中、将涵盖政治、经济、军事各个层次的合作。


*** “后者”在对“前者”进行“解释”


不难看出，在7月3日的《联合公报》中，就明确指明了中俄准备朝哪几个方向去进行“区域一体化”。因此，在东方评论员看来，7月1日的《联合声明》与7月3日的这份《联合公报》相比，可以说在很大程度上、是“后者”在对“前者”进行“解释”。

在东方评论员看来，这种解释不仅有“对那幅美好远景的再描绘”，更重要的是通过解释，呈现了一个中俄准备实现这一远景的具体“行动方案”。

请注意《联合公报》第九条中的这么一段：“上海合作组织已成为建立公正合理的国际政治经济新秩序的重要因素。双方将采取切实措施，同其他成员国一道，深化和拓展上海合作组织框架内的安全、经济及其他领域的合作”。



*** 胡锦涛与普京谈妥的“区域一体化”的第一个方向非常清楚

在东方评论员看来，如此一来，胡锦涛与普京所谈妥的“区域一体化”的第一个方向就非常清楚了，即：在中亚方向，其代表性的问题就是“如何完善”“上海合作组织”的功能，“如何扩大”、“什么时候扩大”“上海合作组织”的影响。




*** 中俄将“上合组织”“有所作为”、“练兵”的第一步、选在了“联合国改革”这个世界级的问题上

首席评论员指出，不论是“联合声明”、还是“联合公报”，我们都能在“字里行间”感觉到这么一层意思，即：北京和莫斯科无时不刻地在“有意拔高”上海合作组织，在我们看来，北京和莫斯科通过为两份重要文件在向国际社会、特别是美国和欧洲“宣示”：在求得国际势力的均衡方面，上海合作组织“应该”、也有能力“有所作为”。

显然，“联合公报”表明，中俄将上海合作组织“有所作为”、“练兵”的第一步、选在了“联合国改革”这个世界级的问题上。



*** 中国的一大外交成就

与此同时，东方评论员又注意到，最新消息显示，明天，也就是五日举行的上海合作组织领导人会议将发表阿斯塔纳宣言，而宣言内将会发表上海合作组织有关联合国改革问题的“四点共识”。

据透露，上海合作组织“四点共识”将与北京的立场“非常接近”，如果是这样，那么，这不能不说是中国的一大外交成就。


*** 日本早就计划好了，也要同中亚国家坐在一起“聊一聊”


根据我们得到的消息，日本早就计划好了，一等这次上海合作组织峰会之后，最早在8月下旬、想请中亚5国、和日本一起，搞一个“5+1”外长会议，这就是说，日本也要同中亚国家坐在一起“聊一聊”。

在东方评论员的记忆里，日本搞的这种“5+1”会谈、是继去年8月后的第一次。我们注意到，对此，日本外相町村信孝公开声称“日本将关注中亚局势变化，也将呼吁各国进一步推动民主改革以及市场经济”，当然，最后，他仍然没有忘记提一句日本喜欢挂在嘴边的“开发援助(ODA)”。


*** 日本的这个所谓“重要手段”的确起了些作用

东方评论员认为，这也难怪，因为日本外务省在2005年度外交蓝皮书这清清楚楚地这样写着：“政府开发援助是日本外交的重要手段之一。”

客观上讲，日本的这个所谓“重要手段”的确起了些作用。就在上个月初，日本外相町村信孝就带了一个团展开了其为期５天的东南亚三国（文莱、越南、柬埔寨）之行，结果是让小泉纯一郎爱恨交加。

其中，让小泉最为欣慰的就是越南的态度了。我们注意到，在日本外相町村信孝就曾经到越南总理府“闭门会见”了一个多小时后，越南总理明确表示“支持日本加入联合国安理会常任理事国的立场”。而町村信孝则表示，“２００５年将向越南提供９亿美元的资助，比上年增加８％”，并声称双方已经就越南加入世界贸易组织（WTO）的双边市场准入谈判达成了“基本协议”。


*** 一笔“日本入常”与“越南入世”、外加９亿美元的资助的“国际交易”

显然，在东方评论员看来，这一“日本入常”与“越南入世”、外加９亿美元的资助的“国际交易”，是进行得是如此“丝丝入扣”，“WTO”、“日元”都成为了交易中的“筹码”。

事实上，看到“日元”在越南身上是如此地好用，在小泉纯一郎身上持续了数年之久的“援助疲软”也开始突然复苏。我们注意到，在6月10日，小泉在一次记者招待会上兴奋地说：“必须纠正（政府开发援助）是浪费、没有必要的想法，不仅不能像现在这样削减，而且到了必须研究增加的阶段。”


*** 小泉纯一郎“援助疲软”的突然复苏，为的是重复一次“与越南之间的故事”

在东方评论员看来，小泉纯一郎“援助疲软”的突然复苏，就是要服务于日本当前外交的主要任务—“争常”，种种迹象表明，日本新增的“ODA”第一笔就可能花在中亚国家身上。

有消息说，町村信孝准备将ODA拿到中亚，并将重点集中于援助五国水资源建设和维护治安领域项目上。对此，我们更是注意到日本外务省官员露骨的直白：“增加ODA的方针，目的是'提前排除一些可能成为日本进入常任理国的障碍的要素'”。非常清楚，日本在中亚搞的这个“5+1”，正是准备再重复一次“与越南之间的故事”。

当然了、对有些国家“日元”吸引力的确不小，特别是有着“美元”配合的时候，也的确好用，在东方评论员看来，这一点在越南的身上，可以说体现得淋漓尽致。然而，这种急功近利的“援助”，对其他国家、特别是对即注重经济发展、更注意政治稳定、国家安全，即看重”“美元”、同时更加看重“人民币”和“卢布”的国家而言，其“功效”几何，还有待观察。


*** 北京以“上海合作组织”的名言、用“四点共识”提前打了日本人一记闷棍


事实上，中亚五国对日本拿着“开发援助(ODA)”当“请谏”、请自己“喝茶”的意图是非常清楚的，其中一个重要话题就是“日本入常”的事儿；然而，日本想得到什么，也同样清楚，那就是尽全力想请“五国”与北京“反对日本入常”的立场“保持一定的距离”。


现在可好，“五国”中的几家、是一边收着日本人的“请谏”，一边却已与北京在上海合作组织的框架内早早地敲定“四点共识”，真可谓是策划中的“5+1”还没有影儿，北京就已经借助多边合作的威力，以“上海合作组织”的名言、用“四点共识”提前打了日本人一记闷棍。


*** 中俄有意将“联合国改革”的“话语权”，作“第一笔政治资本”注入到“上海合作组织”内

联合国改革问题，由于中俄两国都是联合国常任理事国，因此，事实上，两国在这个问题上都处于一言九鼎的地位，在东方评论员看来，两国决策层在用联合国改革问题为自己谋利方面，都颇有心得，私下的交流也是“非常充分”。

首席评论员指出，中国、俄罗斯之所以要在这次首脑会议的前前后后都在“强调”这个问题，就在于不论是胡锦涛还是普京、都有意尝试一下，尝试将“联合国改革”这一世界极的问题的“话语权”、作为“第一笔政治资本”注入到“上海合作组织”内、注入到这个由中俄两国控制的、却也是“唯一的一个”华盛顿无法染指的国际区域安全组织内。


*** 作为一个建议，中俄可以尝试把“联合国改革议题”的“部分权力”让渡给“上海合作组织”

显然，由于“中俄”是“五常之二”，事实上已经把握了“联合国任何改革方案”的生杀大权，作为一个建议，中俄只需把在这个问题上的“部分权力”让渡给“上海合作组织”，那么，获得这一世界级问题“部分话语权”的“上海合作组织”、绝对有可能成为“四国集团”与“咖啡俱乐部”必须重视、与对话的国际组织。


*** 独联体集体安全条约组织已经开始为“上合”制造声势了

有意思的是，最新消息说，独联体集体安全条约组织秘书长在莫斯科表示，“该组织愿与上海合作组织开展更密切的合作”，东方评论员特别注意到，该组织秘书长就“强调”说：：“没有上海合作组织的参与，就无法在阿富汗周边建立起一条真正有效的反毒品安全带。”

对此，首席评论员就指出，独联体集体安全条约组织是俄罗斯主导的，非常清楚，这个组织第一个出来“力捧”“上合”，拉抬“上合”，就是在为“上合”走上国际论坛制造声势。


东方评论员认为，如此一来，中俄在不损害自己“否决权”的情况下，完全可以通过让上海合作组织“部分代替自己”去与方方面面谈论“联合国改革”这个问题，从而达到提高“上海合作组织”“这一品牌”的“含金量”、并以此去间接提高各成员国、特别是中亚国家的“含金量”，最后达到从政治层面增强“组织的凝聚力”的目的。


*** 真正能体现“组织的凝聚力”的是实实在在的“经济关系“

然而，在我们看来，从政治层面增强“组织的凝聚力”、只是第一步，东方评论员认为，真正能体现“组织的凝聚力”的是实实在在的“经济关系“。现实情况下，俄罗斯与上合组织中的中亚国家有着“扯不断，理还乱”的经济联系，事实上，这也正是美国搞成了几宗颜色革命，结果却发现仍然不能让“靠颜色革命中上台”的所谓民主政权、比以前表现得“更亲美一点”的原因。


*** 4月25日实际上是“中俄美欧”中亚博弈的一个分界点

显然，这些国家都明白，民主不能当饭吃。同样，东方评论员认为，华盛顿也一样知道“民主不能当饭吃”，因此，连接里海和地中海的巴库(阿塞拜疆)―第比利斯(格鲁吉亚)―杰伊汉(土耳其)石油管道(简称“巴杰管道”)，成了华盛顿决策层眼中、彻底改变这一尴尬处境的战略工程。

首席评论员认为，这条石油管线是4月25日正式开通的，在我们看来，由于该管线是里海产油区直通地中海、也就是说是中亚国家“甩开俄罗斯石油管道网”、直接向欧美出口石油的首条输油动脉，而且还是美国主导的战略性工程，因此，4月25日实际上是“中俄美欧”中亚博弈的一个分界点。


*** 美国人“狡猾地挖着”哈萨克斯坦通向中国和俄罗斯石油管道的“墙角”


对中国而言，“巴杰管道”的开通不仅直接影响我能源安全，而且对我地缘政治利益与军事安全利益亦产生了“潜在的负面影响”，在东方评论员看来，所有的这些影响都是与中亚国家“石油的流向”紧密相关的：“巴杰管道”是美国主导的，石油进去之后，是运送到西方的。


然而，美国人狡猾之处在明知“巴杰管道”上游油源不足，也要建如此规模的管线，其意图就是在日后去引进哈萨克斯坦石油，形成与中哈管线争油之势，去挖哈萨克斯坦通向中国和俄罗斯石油的“墙角”。

据估算，至少每年要从哈引进2000万吨石油才能保证“巴杰管道”的运营。而哈萨克斯坦油田的产量难以同时满足中哈管线、“巴杰管道”及俄罗斯管线的供油需要。

这就是说，不论是已建或拟建的“中哈管道”、还是“中乌管道”，都可能面临着无油可运的局面。


*** 华盛顿对“巴杰管道”倾注了太多的心血，企图建立控制欧亚大陆的战略基点


由此可见，华盛顿对“巴杰管道”倾注了太多的心血、绝对是物有所值、也是蓄谋已久的。在东方评论员看来，美国主导搞“巴杰管道”、绝不单是了获取里海石油，更重要的企图是寻机改变里海地区的政治生态，建立控制欧亚大陆的战略基点。

东方评论员认为，事实上，“巴杰管道”的开通，为美扩大在里海地区政治、经济、军事存在“提供了民主之外的武器”，在我们看来，如果中俄应对不当，就可能迅速打破中亚的地缘政治格局，因此，我们认为，在这一过程中，受冲击最大的无疑是俄罗斯、而中国的地缘政治利益也会受到相当程度的影响。


*** 成了中国、特别是俄罗斯中亚战略的一颗“毒药”


不难看出，它的开通，正好成了一颗解决“美国在中亚国家搞民主不能当饭吃”之尴尬的“灵丹妙药”。因此，也就成了中国、特别是俄罗斯中亚战略的一颗“毒药”。

在东方评论员看来，对俄罗斯而言，失去了中亚国家石油的“专运权”、所造成的经济损失、其后果是灾难性的，我们认为，时间一长，这种“灾难性”将体现在中亚国家可以摆脱对俄罗斯的依赖，从而由经济层面逐渐向政治、安全层面扩散。



*** 华盛顿决策层“早就已经拟好了的”战略规划

显然，美国通过“巴杰管道”、将取得与中亚国家的“经济对话渠道”，而根据我们的观察，借能源合作扩大军事存在，是美国中亚、里海战略的既定方针。因此，在东方评论员看来，稍后，在里海地区扩大军事存在、继而影响、控制某些地区国家的外交取向，使它们更多地服从美国的意志，打破“中俄欧美”各大强权在中亚地区的利益平衡、是华盛顿决策层“早就已经拟好了的”战略规划。

其实、东方评论员已经注意到，有消息说，华盛顿已经以维护“巴杰管道”安全为由，要求阿塞拜疆同意美在阿驻军、并提出了组成所谓的“里海卫队”战略、筹建美国主导的“里海能源防卫体系”。


东方评论员认为，正是经历了4月25日这个“中俄美欧”中亚博弈的“分界点”，也面临着华盛顿上面这份“拟好了的战略规划”，“中俄”近两个月来，显然加大了合作力度。



*** 伊朗成为观察员的意义尤为重大

在我们看来，最能体现这种力度的，有两个方向，一个就是上海合作组织决心吸收印度、巴基斯坦、伊朗为观察员，另一个就是中俄在东亚即将举行的、旨在朝鲜半岛安全的联合军演。

东方评论员认为，前者的意义在于、“上海合作组织”的影响、将一把扩展到南亚和西亚地区，打通连接中东的陆上通道，并成为欧亚大陆上覆盖面积最大、包含人口最多的安全与经贸区域国际组织。

如果说得时髦一点的话，那就是，中俄主导的、扩容后（要待上述三国正式成为会员国后）的“上合”、将与美国主导的北约“遥遥相对”，在国际社会面前都将以一个“巨大反恐组织”的面目出现、只是到底是反恐为主、还是制美为辅，恐怕各方都将是“心照不宣”。



*** 吸收伊朗，是要军事实力、也是要有经济实力做后盾的

特别地，首席评论员就认为，伊朗成为观察员的意义尤为重大，这就是说，与印度和巴基斯坦的情况不同，中俄对吸纳伊朗体现了高度一致，这就保证了伊朗在需要的时候，即华盛顿准备切断伊朗与外界的联系的时候，伊朗极有可能作为一个“与南亚两国能源安全紧捆在一起的”“利益共同体”、一起快速加入上海合作组织、从而确保伊朗在国家安全、与经济安全方面、与中国、俄罗斯“保持可靠的地理联系”。

在东方评论员看来，事实上没有任何事情比中俄两国决心有朝一日正式将伊朗、这个华盛顿处心各虑“欲拿之而后快”的国家“纳入上合这个区域安全、经济混合型组织内”、更能在世界面前塑造“负责任的大国形象”的了,显然，这样做是要军事实力做后盾的，也是要有经济实力做后盾的。

在一段来自英国BBC的新闻之后，东方时事评论员将继续讨论这一话题，看看中俄在伊朗问题、朝核问题、这两个美国盯得最紧的方向上，可能会如何塑造一个“负责任的大国形象”。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com


