# -*- org -*-

# Time-stamp: <2011-08-04 12:19:13 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

*  2005年8月09日 星期二





** 民主党上台或利中日关系或邀胡锦涛访日



【香港明报8月9日报道】小泉解散国会、提早大选的决定，顿时令人关注日本政局变迁对其外交路线的影响。中国社会科学院的中日问题专家冯昭奎指出，小泉确有可能藉于8.15参拜靖国神社，捞取选举本钱。他和日本琉球大学国际关系学系副教授林泉忠都认为，若在野民主党能藉此机会一举上台，相信能即时改善中日关系，林甚至相信可造就胡锦涛访日。

小泉拜靖国拉票“华须审慎免中计”

现为日本爱知大学客座教授的冯昭奎说，虽然在野民主党近年冒升迅速，大有挑战自民党执政地位之势，但小泉不是没有胜算，大概双方机会是“一半一半”。日本传媒曾盛传小泉一旦宣布提前大选，便会在8月15日参拜靖国神社，把国民视线转移到中国，突出他会对华说不，冯昭奎认为有此可能。

冯说，4月中国示威者的过激示威令许多日本人反感，故日本鹰派期待小泉参拜时再次激起中国人的过激行为，以掀起日本人的民族主义情绪，在9月的选举中力挺小泉，是以冯认为中国的对应很重要－－反对参拜很重要，但不要反应过激，否则只会助了小泉和日本右翼一把。不过琉球大学国际关系副教授林泉忠则认为，因当下社会民意大都反对首相参拜靖国，小泉在8月15日参拜靖国神社的机会未必太高。对于民主党可能有机会上台，冯昭奎表示若成真，对中日关系将较有利。他指出，小泉在外交上一面倒亲美，在中日关系上极具煽动性；而民主党党魁冈田克也则较稳重，比较重视亚洲关系，若他上台，中日紧张关系能即时缓和。

民主党党魁倡与中韩修好

民主党党魁冈田克也曾一再表明，若他当首相，会努力修补与中韩关系，绝不参拜靖国神社；就改宪问题上，该党主张改宪，但反对更改宪法中有关放弃战争的关键第9条。林泉忠说，民主党若胜出，将即时解决横在中日关系之间的靖国参拜问题，虽未必能解决所有问题，但已足以制造良好的气氛。“如果民主党上场，我相信中国国家主席胡锦涛很有机会访问日本，而且很快会实现。”

他指出，4月底中国出现反日浪潮后，民主党内部成立了历史学习会，其成员更上电视向国民讲解中国的对日观点。“民主党告诉国民，72年中日外交正常化时周恩来已表明，中国认为日本要为侵略负责的只是小部分的军国主义分子，其余大部分日本人和中国人民一样都是受害者。现在中韩与日本闹僵，是因为自民党部分掌权者把小部分军国主义者和大部分人的界线模糊化，令中韩感到混淆。”林泉忠相信，民主党在选战中会集中两点攻击自民党，其一是自民党内政不得民心、政策令日本社会分裂；其二为自民党令日本与中韩关系跌至谷底。“这阵子，日本社会开始觉醒到与邻国关系的重要性，社会呼声都倾向反对参拜靖国，这对民主党是很有利的。”

记者指出，民主党内一样有保守势力，例如担任副党首的着名右翼政客小泽一郎就势力甚大。但林泉忠相信，冈田近两年带领民主党，建立了颇不错的开明形象，支持度进一步攀升，反对参拜靖国等立场，已成为党内基本共识，不会轻易改变。



【时事点评】日本邮政改革遭参院反对而受挫，小泉政权因此陷入危机。面对内阁总辞职和解散众议院两个方案，小泉终于把事先针对“造反者”的“两杀招”兑现成了“实际行动”，选择了后一方案。


*** 冯昭奎先生的另外两个观点，我们也是“深以为然”

东方评论员注意到，对日本提前大选的前景，中国社科院中日问题专家冯昭奎的观点是：尽管在野民主党近年“冒升迅速”，但是小泉不是没有胜算，因此，双方机会是“一半一半”。

另外，冯昭奎先生的另外两个观点，即：一是认为“小泉确有可能藉于8.15参拜靖国神社，捞取选举本钱”；第二是“若在野民主党能藉此机会一举上台，相信能即时改善中日关系”，我们也是“深以为然”。


*** “判定”小泉的政治生命即将结束、显然没有充分考虑到“两点”

对于第一点，首席评论员就指出，“邮政法案”因自民党内部有人“造反”而最终“被废”、对小泉而言、当然算得上是一大打击。但是我们也认为、如果要据此“判定”小泉的政治生命即将结束、显然没有充分考虑到“怪人”有可能的“怪招”、和日本社会一种非常值得警惕的现实。

就目前而言，客观上讲，在日本“绝对亲华”与“激烈反华”一样，都只是一小撮人，在我们看来，绝大多数日本人对中国并没有“特别的看法”，但是，就如我们之前所说的，日本社会有种“鱼群”效应、是非常容易被影响的，这就为小泉纯一郎提供了想像的空间。

另外，由于邮政系统对日本政治有着举足轻重的影响，邮政系统本身、以及依附在它上面的利益群体、原本就是日本自民党的“重要票仓”，在东方评论员看来，小泉纯一郎在丢掉了这部分选票之后、自然会在其他方向去“弥补”。


*** 小泉“的确有心”打“8月15日参拜靖国神社”这张牌的心思

这一点、在小泉的一次公开活动中、就表现得非常清楚。东方评论员注意到，在今天日本首相官邸举行的一次记者会上，在回答记者的相关提问时，对于在9月11日众院选举之前是否会前往参拜靖国神社的问题，小泉纯一郎采取了“避而不答”、“无可奉告”的态度。

东方评论员认为、标榜自己“重视诺言”的小泉纯一郎、“的确有心”打“8月15日参拜靖国神社”这张牌的心思、

在我们看来，邮政改革是小泉1992年担任邮政大臣时就定下的目标，久而久之，这件事已经上升为一种精神追求。日前、面对自己所属的森喜朗派系的“派头”--森喜朗，小泉甚至“悲壮地宣誓：为了自己的“信念”，他“不惜被杀死”。

根据我们的观察，在日本，大多数选民还是支持邮政私营化改革的，因此，东方评论员认为，小泉可并非真的认为自己会因改革而“丢掉脑袋”，而是想“借这种支持”来“煽动国民的支持”来实现自己的政策主张，解散众议院、提前大选，靠“国民牌”豪赌一把。


*** 一种危险的思维定式

另外，我们也注意到，不论是冯昭奎先生、还是日本琉球大学国际关系学系林泉忠副教授，在访问中、似乎都将小泉纯一郎捞取选举本钱的计划、集中在“他可能藉于8.15参拜靖国神社”这个方案上了，在东方评论员看来，只盯着小泉纯一郎参拜靖国神社这一点、而忽略小泉政府有可能在东海、钓鱼岛上“先行”挑起事端、这是非常危险的一种思维定式。


*** 必须高度警惕小泉可能在挑起“中日主权冲突”的基础上、再去参拜靖国神社

连续几天，针对日本在朝核问题陷入某种孤立、日本“入常”遭到北京的“封杀”（中国有官员明言、就算是四国提案通过了，最后也不过是废纸一张），以及日本国内政局可能引起的中日关系进一步恶化、直到小泉提出的邮政私营化相关法案被废，小泉冒险解散日本国会等一系列变化、东方评论员就一再强调、必须高度警惕小泉纯一郎的“困兽犹斗”、必须高度警惕小泉纯一郎在东海“油气开发”、钓鱼岛“主权宣示”这些中日双方根本就没有回旋余地的问题上、突然挑起事端、并“在这个基础上”、再去参拜靖国神社、这时候、本来有52%民意“反对”参拜靖国神社的日本社会、很有可能在小泉政府刻意挑起“中日主权争端”这一没有任何弹性问题的刺激下、在“鱼群”效应的作用下、给彻底扭转过来。

还有，小泉纯一郎的“政治豪赌”的结果如何、不仅对日本国内政局有着“巨大冲击”、而且这种“冲击”必然将冲出国界、对包括中、美、日、韩国相互关系在内的东亚局势、产生微妙的影响。

也正是如此，华盛顿的眼睛也在盯着这次大选将何去何从。在一则消息之后，东方评论员将继续回到这个话题。


《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 美担心日本会出现政治空白、认为政局持续混乱将影响美日关系


【东京8月9日消息】据日本广播协会电视台报道，就日本解散众议院举行大选问题，美国政府认为，这对日美关系不会有大的变化，但是如果政局持续混乱，将可能会对两国间的问题以及安全保障政策产生影响，因此将会密切注视今后的动向。

　　鉴于在反恐活动中小泉首相一贯对美国的行动给予了支持，因此，美国政府把日本看作是最值得信赖的同盟国之一，同时对小泉政权进行的结构改革路线也表示了支持。

　　就解散众议院问题，美国政府到目前为止还没有公开表态，但是，一般认为，布什总统对与他个人关系很近的小泉首相的决断抱有极大的关心。



【时事点评】在东方评论员看来，华盛顿对日本政局的“担心”是有的，但是恐怕还远没有到“揪心”的地步。根据我们的观察，日本社会的右倾化是“由来已久”，整个社会总体上趋向保守已经成了事实。因此，在我们看来，不论小泉的“政治豪赌”结果如何，短期内对小泉政府目前奉行的“对美国一边倒”的外交政策、不会有太大的改观。


*** 在野民主党上台，对中日关系的改善“虽然会是即时的、但也是有限的”

前面说了，冯昭奎先生有两个观点，即：一是认为“小泉确有可能藉于8.15参拜靖国神社，捞取选举本钱”；第二是“若在野民主党能藉此机会一举上台，相信能即时改善中日关系”，我们对此也是“深以为然”。

然而，我们也认为即使日本在野民主党能藉此机会一举上台，对中日关系的改善“虽然会是即时的、但也是有限的”。


*** 小泉的外交政策，并没有受到来自在野党的任何“有效反对”

在东方评论员看来，小泉为首的保守势力执政几年来，抛开在国内政策上受到反对党的强力牵制之外，小泉纯一郎上台以来所奉行的“对美国一边倒的”外交政策、可以说并没有受到来自在野党的任何“有效反对”。

其中、有可能成为“解散议会”最大的赢家的日本最大的反对党-民主党、实际上在过去几年中、甚至在修改日本和平宪法的问题上、“相当程度上”都在与小泉为首的日本保守势力“狼狈为奸”。


*** 日本军国主义、极端民族主义的“复活历程”、实际上是日本社会的一种“发泄”

事实上，也正是在这种“朝野”合力的效应下，近年来，“对外强硬”的“标语”、越来越成为时髦的“政治口号”。东方评论员认为，中日之间围绕小泉参拜靖国神社所爆发的争斗、表面上是历史问题引起的，但是，本质上却是“中、美、日”在地缘政治上的“战略思维”上的冲突。

从地缘政治的战略思维角度看，日本政府以一系列极端手法、全力挑衅中国和亚洲邻国的行为，本质上是日本极端民族主义和军国主义“思维”、借美国欲挟日本遏制中国这一战略需要而“复活”的“必然”。

东方评论员认为，日本军国主义、极端民族主义的“复活历程”、实际上日本经济在欧美联手打压下、停滞了“近十年”的一种“发泄”，是之前规划过“雁行模式”、自居为“头雁”的日本、面对被日本“设计”为“尾雁”的中国的崛起、却被从主导者渐渐被边缘化的一种“发泄”。


*** 最近十年来，日本社会的一个“显而易见的事实”

在我们看来，一个显而易见的事实是：最近十年，日本国内总是在对所谓的“国家定位”问题而争吵不休，然而，与此同时，我们也注意到，在“精神层面”上、即关于日本历史责任的讨论、却几乎“被完全地”付之阙如。

这些事实已经充分说明，我们已经“完全看不到”日本社会、或者是日本政治、经济管理阶层、甚至是日本学者对历史责任的反思、清理，在东方评论员看来，这一点是与十年前的日本有着“本质差别”的地方，这种“本质差别”不仅是“上述”那种“发泄”的结果、更与战后日本在美国战略利益下“刻意保留”其原有政治、经济乃至思想框架、有着极为密切的“逻辑关系”。


*** “对历史的清算”成为德国社会、民族的“本能”

我们认为，日本和德国都是法西斯战败国，然而在历史的清算问题上，德国和日本间的情况、却因“两国社会在认识历史问题”上的巨大反差、而形成鲜明对比。
众所周知，战后德国，在历史问题上，一个最大特点、就是知识界和整个社会关于历史责任的反思从来未曾停止过，这就使得“对历史的清算”成为德国社会、民族的“本能”；

值得强调的是，在德国统一后，重造“一个强大的德国”的政治理念、也一度勾起过德国“极右思潮”的“抬头”，但是，结果却让我们看到了“对历史的清算”这种德国社会、民族“本能”的威力，即：在对历史责任的“本能承担”面前，德国极右思潮和势力始终只能局限在一定范围内，根本就不可能进入德国的“政策层面”。


*** 日本社会对德国那种“从根子上反省历史的态度”、在理解上却出了“可耻的偏差”


而反观日本，由于日本社会在战后可以说“从来没有正视过那段侵略历史”，因此，在日本历史教科书、将“侵略中国”写成“进入中国”几十年的时间里、日本社会对德国那种“从根子上反省历史的态度”、在理解上却出了“可耻的偏差”。


*** 许多所谓的“日本友好人士”对历史问题的理解

东方评论员认为，最能说明这种可耻偏差的、莫过于许多所谓的“日本友好人士”的理解了，在我们看来，他们反对日本军国主义、也承认日本侵略中国、和其它亚洲国家、并还承认日本侵略军的行为残暴、犯下了战争罪行、也给被侵略国家带来巨大灾难，对这一点、我们认为是值得肯定的；

然而，这些“日本友好人士”在理解德国那种“从根子上反省历史的态度”时、却得出了“是因为希特勒太坏了”、“是希特勒这么个罪人带领德国法西斯犯下的罪行”，所以德国人有必要做出全面的反省。


*** 让我们无法理解的的一种“荒唐的认识”

与此同时，让我们无法理解的是，他们还庆幸日本“没有出现希特勒这么一个大恶人”，因为日本军国主义的决策者不是哪一个人、而是当时的日本政府、因此、他们也就得出了“日本与德国在那段历史中是不同的”这种荒唐的认识。

在我们看来，值得强调的是，持有“这种荒唐的认识”绝非个别、而是具有广泛的代表性的，特别值得强调的是、这种“这种荒唐的认识”的持有者中、相当部分是“日本友好人士”、是“日本反对军国主义”的日本学者，是日本致力于中日友好的“骨干分子”，由此带来的、对日本社会历史观上的“负面影响”、就是可想而知的了。


*** 日本极右思潮和势力为什么非常顺利地进入了日本的“政策层面”

另外，根据我们的观察、在日本、甚至许多被认为是属于“亲中派”、或者是反对“错误历史观”的日本友人、或者日本学者、也有着强烈的“担心中国”的心理。东方评论员认为，正是有着“这些复杂背景”，在自视为“与德国不同”的日本，日本极右思潮和势力、也就非常顺利地进入了日本的“政策层面”。


*** 东方评论员愿意“再次强调”一种可能性

因此，在日本极右思潮和势力、已经顺利地进入了日本的“政策层面”的现实下，东方评论员愿意“再次强调”一种可能性，那就是北京应该警惕小泉纯一郎为了赢得选票所采取的策略，即先在东海、钓鱼岛方向挑起主权争端、之后、在激起“中日”两国社会的情绪之后、再去参拜靖国神社，在我们看来，在“这种先后顺序下”，对小泉纯一郎而言、在是否将参拜的时间挑在“8月15日”这个敏感的日子之问题上、“反而更加灵活了”：显然，在与中国之间爆发主权争端、成功煽动起日本民族情绪的情况下、如果不选择“8月15日”、甚至在9月投票前、小泉纯一郎都不参拜靖国神社、反而可以缓解与韩国、和其它国家的矛盾、缓解日本国内反对参拜靖国神社的不满、从而将所有的矛头直指中国。


*** 不论日本在9月份的大选结果如何，指望日本对外政策来个180度的大转变、是不切实际的

在存在这一可能的前提下，首席评论员的观点是：不论日本在9月份的大选结果如何，指望日本对外政策来个180度的大转变、是不切实际的，不仅如此、北京反而要有中日关系进一步恶化心理准备。

在我们看来，就算是日本反对势力--比如说民主党党魁冈田克上台也是如此，尽管现在他一再表明，“若他当首相，会努力修补与中韩关系，绝不参拜靖国神社”。试想，如果小泉纯一郎之前已经挑起了中日东海主权之争，那么，下台的小泉留下的就是一个中日两国民众“情绪对立”的乱摊子，不难想像的是，在主权问题上、在日本民族情绪高涨的情况下、不论谁上台、到时都不可能轻言退让。

另外，东方评论员认为，假设小泉不敢在东海挑起主权争端、假设民主党最后赢得大选、从日本国内的情况来判断，恐怕民主党席位也很难过半、从而必须与其它党派“联合组阁”、甚至包括与某些偏右势力妥协、才能上台。

在我们看来，在这种情况下，虽然“反对更改宪法中有关放弃战争的关键第9条”、但却赞成修宪”日本民主党、一旦赢得大选级阁执政、在日本社会这种“历史观”面前、在日本社会已经右倾化的现实面前，“最大的可能”是继续小泉纯一郎这种“全面倒向美国的外交政策”，而基于更好地与美国讨价还价的战略目的、不让靖国神社问题成为“勉强维持”中日关系的障碍、却是可能的。只是这种“勉强维持”，解决不了中日关系间的关键问题。

在我们看来，“这种关键问题”就是日本“正在面对着”一个强大的中国。下面是日本《共同社》的一篇有关“中美日”关系的分析报道，在一起阅读主要片段之后，时事评论员将继续讨论中日间的“这个关键问题”。


《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com


