# -*- org -*-

# Time-stamp: <2011-08-04 19:19:04 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 2005年8月05日 星期五




** 王光亚称四国联盟强行推动联大表决是死路一条




【新华网8月5日电】中国常驻联合国代表王光亚4日在纽约联合国总部接受媒体采访时强调，在非洲联盟已拒绝给予支持的情况下，四国联盟最好的出路是撤回它们不得人心的决议案。

王光亚指出，中国在安理会改革问题上的立场是始终如一的。中国主张各国就安理会改革进行广泛讨论以达成最大共识，安理会任何改革方案都应该优先考虑发展中国家的代表性。四国联盟的决议案从一开始就与中国的原则立场不相符。四国决议案主要为少数几个大国谋利益，而且四国还企图把其拟定的“增常”进程强加给联合国所有成员国，这是非常危险的。

他说，四国联盟的这一做法，在联合国成员国之间及各个地区内部都产生了很大的分歧和分裂，严重破坏了9月联合国首脑会议的筹备工作。因此，中国对四国决议案采取坚决的反对态度。

王光亚强调，中国的立场是非常明确的，即使有一部分非洲国家加入四国的决议案，中国仍坚决反对这一决议案。因为如果非盟与四国的决议案合二为一，新决议案仍然是四国决议案的变种。他说，“今天非盟首脑会议的结果对四国是不利的。他们应清醒地认识到，如继续强行推动联大表决其决议案，只能是死路一条”。

王光亚说，在当前的情况下，四国联盟、“团结谋共识”及非盟三方的安理会扩大方案都很难得到绝大多数成员国的支持。各成员国应进行认真的磋商，吸收各个方案的优点，努力弥合分歧，以寻找能得到绝大多数成员国支持的折中方案。各方达成妥协的机会仍然是存在的。中方认为，以增加任期超过两年的非常任理事国为基础的方案，未免不是一条出路。

王光亚否认中国会像日本外相町村信孝及其常驻联合国代表大岛贤三最近宣称的那样最后改变对四国决议案的反对立场。他说，这是一种强加于人的流言。中国政府、中国人民在安理会改革问题上的立场非常清楚，不管四国决议案得到多少支持，中国的反对立场都不会动摇。更何况事实一再证明，四国决议案不可能得到绝大多数成员国的支持。即便它能得到三分之二联合国成员国的同意，也是一个分裂成员国的方案，是不得人心的。中国、美国及其他许多重要的国家，到了最后批准阶段，也是不会积极推动各自国家的议会批准这样的方案的。

在被问及对日本可能因“入常”不成削减联合国会费有何评论时，王光亚说，这是一种威胁和讹诈。他指出，各国缴纳联合国会费的比例，是由联大决议规定的。如果日本决定以削减会费威胁各成员国，那将是非法的行为。联大有关各国缴纳联合国会费的决议是具有法律约束力的。如果日本采取这样一个非法的行动，那是不会得到别国的同情和支持的。

四国联盟7月初向第59届联大提交了一项框架决议案，要求增加6个安理会常任理事国和4个非常任理事国。四国一直寻求与非盟就安理会扩大达成妥协，将双方的“增常”决议案合并。但在4日举行的非盟特别首脑会议上，绝大多数非盟成员国拒绝与四国妥协。没有拥有53个成员国的非盟的支持，四国将很难在联大获得决议案通过必需的三分之二多数票（128张）。


【时事点评】在东方评论员看来，王光亚今天的这番讲话、可以说是迄今以来、北京最重的一次讲话，一句“四国联盟强行推动联大表决是死路一条”不仅表示了中国在这个问题上、将坚持到底的决心，也充分展示了北京对自己最终能封杀日本“入常”是胸有成竹。

*** 北京和华盛顿“罕见的一致”，可以说体现了两层意义

事实上，在昨天的点评中，我们就针对王光亚与新到任的美国驻联合国大使博尔顿“达成的协议”给出过我们的一个观点，那就是，北京和华盛顿在阻止“四国集团”提案时所表现出来的“罕见的一致”，可以说体现了两层意义：

第一，中美两国在联合国改革的问题上，可以说是到目前为止“最能”捍卫“联合国五大常任理事国”利益的两个国家，“两国”说出了法、英、俄这三个常任理事国想说却因各种原因、而没有说出的心里话：因为不论是中国还是其他几个、手握否决权的常任理事国，没有任何一家、真心的愿意其他国家来分分享自己手中的特权。

此外，除了上面这条“说不出口”的理由之外，中美反对“四国提案”的“表面理由”都与自己的“另一个利益”息息相关：即，北京要借此打击日本，美国则在借机报复德国。

事实上、从日本后来的动作来看、有无“否决权”并不是它“申常”不可缺少的条件，因此，在这种前提下，可以这样说，如果没有中国因素、日本是四国中“最不需要”进行“捆绑”的一家。

然而，也正因为有了中国因素、日本“反成了”四国中“最需要”进行“捆绑”的一家、在东方评论员看来，这“里里外外”的“出入”，恐怕只有小泉政府心中感受最深。

*** 北京的真正意图在于借此继续恶化日本保守势力的“内、外部环境”

第二，首席评论员就指出，不论是北京要借此打击日本，还是美国在借机报复德国、说到底、仍然是个表面的理由、是个借口。在我们看来，北京的真正意图在于借此继续恶化日本保守势力执政的“内、外部环境”。


在我们进一步讨论这个问题之前，再来阅读一篇相关分析报道。



《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com



** 国际先驱导报：小泉8月15日可能参拜靖国神社



【国际先驱导报8月5日报道】目前日本政界绝大多数人士都认为小泉连续5次参拜靖国神社几乎已成定局，现在仅仅是年内的时间选择问题而已

国际先驱导报驻东京记者孙巍报道今年以来，由于日本邮政民营化改革举步维艰，参拜靖国神社不仅是小泉兑现2001年竞选承诺的问题，更与日本政局走势及自民党内部斗争紧密联系在一起，呈现出十分复杂的特性。


取悦保守派做“最后冲刺”

当前，日本政坛的最大焦点莫过于被称作小泉“心病”的邮政民营化改革。本月5日，日本参议院将审议此项改革法案，如果能顺利通过，小泉的政治形象就会抹上“光辉的一笔”。但目前的形势并不乐观，由于此项改革深深触及了一些人的既得利益，正遭到部分邮政系统出身的自民党国会议员的强烈反对，随时都有夭折的可能。据悉，截至上周末为止，明确表示反对的自民党国会议员有14人，缺席或可能投弃权票的估计有20人左右。假设5日的众院表决所有议员全部出席，在执政党支持、在野党反对的情况下，只要自民党中的反对者超过18人，就会导致该法案成为废案。

在万般无奈之下，小泉使出了最后一记撒手锏，威胁说：若参院否决该项法案，将强行解散众院实行大选。如果真的发生这种情况，那么小泉为争取更多的支持，在8月15日前往参拜靖国神社的可能性就会陡然增加。目前，日本政界许多人都认为，如果小泉能够兑现竞选时的承诺，在8月15日参拜，对于自民党在众院选举中获胜会有很大帮助。自民党内部甚至传出“如果小泉15日参拜，自民党将会大获全胜”的论调。

根据《每日新闻》的调查，尽管日本国民反对小泉参拜的比例达到51%，但自民党内部支持其参拜的比例却高达62%。一位前内阁成员指出“8月15日参拜是对日本政界保守势力的莫大支持”，小泉为维系其支持层，很可能选择8月15日参拜。如果小泉真的成行，他将成为1985年中曾根康弘内阁以来作为现职首相在“8·15”当日参拜靖国神社的第一人。

右翼发动20万人前往参拜

而随着8月15日的临近，日本右翼终于按捺不住，开始蠢蠢欲动。8月1日，日本发行量最大的《读卖新闻》和右倾的《产经新闻》同时刊登了整版广告，提出召集20万人在8月15日参拜靖国神社。

从广告中可以看到，活动的发起人就是“大家都来参拜靖国神社国民会”。广告的左下方是发起人名单及职务，其中就包括东京都知事石原慎太郎、日本遗族会顾问前参院议员坂垣正等人。石原慎太郎借此广告宣扬：“在战争期间，20来岁的年轻人最熟悉的一句话，就是'靖国神社见！'。”

广告刊登了日本国民参拜靖国神社的大副照片，并赤裸裸地宣扬：“8月15日那天，在靖国神社的参拜大道上我们将召集20万人进行各种各样的追悼活动。此外，在靖国神社院内的'游旧馆'还将展示先人走过的历史轨迹和死难者的遗书等物品。大家靖国神社见！”

广告在显著位置刊登了有元首级人物参拜过靖国神社的12个国家名单及大使、武官级人物参拜过靖国神社的35个国家名单，试图以此彰显参拜靖国神社的“合理性”及“国际性”。在广告的右下方还刊登了靖国神社的交通图以及8月15日各项活动的举办时间和地点及出席的“嘉宾”等内容。

8月2日，由跨党派保守派议员组成的“日本会议国会议员恳谈会”等5个团体在国会内举行记者招待会，发表声明要求小泉纯一郎在8月15日参拜靖国神社。这五个团体中的成员包括355名日本议员，大部分是执政的自民党党员。声明称，中韩两国反对小泉参拜靖国神社是对日本内政的干涉，在表示抗议的同时，同样反对将甲级战犯分别祭祀以及建设国立死难者追悼设施。该声明还叫嚣，日本首相参拜靖国神社是“一个国家领导人的责任”。

妄图给参拜批上“合理外衣”

除了“8·１5参拜”的观点外，目前日本舆论也在推测其他时间参拜的可能性。一种说法是希望小泉在靖国神社秋季大祭时去参拜，这一时间是日本遗族会所希望的。不过由于秋季大祭是在10月17日至20日之间进行，届时中国国内纪念抗战的活动仍将接连不断，所以正如外务省一位干部所言，“如果考虑对外交层面的影响，选择这一时间同样是下策”。

有鉴于此，为了最小限度地控制参拜靖国神社对中韩两国的影响，又有人提出让小泉在今年年底参拜。一位首相官邸的人说“首相在元旦前后参拜既履行了竞选承诺，又可以把负面影响降到最低”。当然，与此相类似，有人主张选择12月8日进行参拜，因为60多年前的这天，日本袭击了美国的珍珠港，这样一来小泉参拜靖国神社就有了乞求和平、不让战争重演的“合理外衣”。

尽管在参拜时机上各界说法不一，但万变不离其宗，小泉参拜靖国神社将成为不可回避的事实。7月29日，小泉与日本全国都道府县议会议长会举行座谈时，曾就是否参拜靖国神社问题表示“将做出适当判断”。不过，这种“判断”不会是放弃参拜，而是要“判断”何时去参拜。


【时事点评】看到这则报告，大家也许要问：小泉纯一郎敢在8月15日冒天下之大不韪参拜靖国神社吗？对此，东方评论员认为，如果在近段时间内、北京不能出台什么新举措、发出中日关系有“政冷”向“经冷”迅速扩散的信号的话、那么，陷于“内外交困”中的小泉为了摆脱困境、是有可能去的、但更有可能在钓鱼岛、东海方向挑衅中国。

*** 日本“申常”的企图可以说有多层，但是最基本的却是两条

我们知道，日本“申常”的企图可以说有多层，但是最基本的却是两条：第一，在日本不更改现行政策下，如果“申常”成功（注，还不是“入常”，日本“入常”可是要在“申常”成功之后、必须经中国人大批准的事情）、则是小泉政府、也是日本保守势力的“大功一件”，也将是日本保守政策的胜利、从此、日本保守政策的执政基础将得到极大的增强，再要想强迫日本社会改变小泉纯一郎这一套政策更是难上加难！什么“修改和平宪法”、“为东京审判翻案”、甚至是跨入核门槛，都将理所当然地成为日本的下一个目标。

第二，如果“申常”失败、日本右翼则早已经准备好了、那翼是顺势将所有的脏水都扣在别人头上、这个“别人”就不仅是中国了、还有韩国、甚至美国。总而言之，只要能利用“是外国存心不让最有资格的日本入常”这一点、来激起日本的民粹主义就行。

可以想像的是、只要能激起民粹主义、让日本社会“坚信”是国际社会在与日本为敌，那么，同样的，什么“修改和平宪法”、“为东京审判翻案”、以及跨入核门槛，也都将理所当然地成为日本的下一个目标。

不过、种种迹象表明，特别是日本右翼借几家主流媒体、大做“广告”呼吁日本全社会支持小泉参拜靖国神社一事，并非说明小泉在参拜靖国神社问题上开始主动、反而更加说明小泉政府正在承受巨大的“内、外压力”。


*** 小泉纯一郎已经开始追求这么一个目标

在我们看来，这种压力一个是来自对日本而言及其重要的中日关系的确到了“一推就倒”的地步，而另一方面、也来自小泉纯一郎在“参拜靖国神社问题上”也已经到了如果不满足日本右翼的要求、小泉内阁和小泉本人、及其亲信的政治前程也到了一推就倒的地步。

因此，首席评论员就指出，日本保守势力在做了多次试探，在经过中国民众的“反日游行”、胡锦涛主席明言靖国神社问题是中日关系的症结、以及吴仪副总理提前中断访日行程这几个“北京绝不会让步”的回答之后，在明知道历史包袱扔不掉的情况下，之所以还要拿对中日双方“都非常重要”的中日关系做赌注、在历史问题上继续强硬，就在于它已经开始追求这么一个长期目标，既：通过不停地参拜靖国神社、为日本军国主义翻案等方式、来体现对中国的一种长期对抗的架势、以此来维持日本岛国民族的民族自尊心、并以此来持续强化日本保守势力的民意基础、趁势解决一些国内重大问题、以实现其长期执政的目的。


*** 日本社会”具有种“鱼群”的特性

在东方评论员看来，日本有个外交传统，就是在紧要关头总会依附一个国际强者，并经常利用国外形势，制造舆论，从而去“左右国内政局”。

实际上，这种为日本政客所惯用的一招，就是日本人所谓的“外压”、即利用危机意识去实现长期的战略目标。事实上，首席评论员就指出，日本政治人物之所以热衷于“外压”，就在于日本社会非常像“游动中的鱼群”，稍有惊慌，就容易在“危机感”中、集体改变“游动方向”。

有意思的是，“日本社会”所具有的这种“鱼群”特性，在吴仪副总理突然中止访日行程、强烈冲击日本社会、并一度让小泉纯一郎处于相当孤立的境地的“整个过程”中、可谓是表现得淋漓尽致。

以前、日本人是利用所谓的“朝鲜威胁”，来“启动”日本人“危机意识”的。现在，“朝鲜威胁”已经为日本社会所“麻木”，因为经过这些年的炒作，日本民众已经清楚，朝鲜威胁不了日本。

因此，在急欲强化日本社会右倾化的日本保守势力看来，所谓的“中国威胁”也就呼之而出了。在东方评论员看来，日本一年来一直围绕钓鱼岛、东海主权问题“打转转”，并不惜在美国之前将“中国威胁论”塞进其国防文件之中、一个重要原因，就是出于借“中国威胁”、来达到激起“日本鱼群”的“危机意识”、将日本社会赶向“极端右倾”的方向。


*** “日本社会”所具有的这种“鱼群”特性，也为北京“精确地利用了一次”

不曾想的是，“日本社会”所具有的这种“鱼群”特性，也为北京“精确地利用了一次”。事实上，自胡锦涛警告中日关系是“一推即倒”、且吴仪突然中止访日行程、在日本本土给了小泉纯一郎一记耳光之后，“日本鱼群”就立刻被“一推既倒”的中日关系所“激励”、其结果我们也都看到了，那就是几乎是在一夜之间就开始“狂咬”小泉纯一郎、这中间、以日本众院议长河野洋平召集日本多位前首相出面“猛批”小泉、甚至以“幼稚、白痴”的形容词“为小泉画像”最具代表性。


在东方评论员看来，就在小泉纯一郎为代表的日本保守势力被“日本鱼群”“狂咬”的时候，隔着太平洋的华盛顿新保守主义者、可以说是及时地抛出了它之前一直不愿意“正式兜售”的“中国威胁论”，并从军事、经济、政治的各个层面、“一一加以论证”。

显然，布什在这个时候亲自上阵、全力叫卖“中国威胁论”、一个重要动机就是要拉小泉纯一郎一把，帮日本保守势力稳住阵脚。（注，最主要动机则是测试中国的战略能力、与决心、及着眼于分解“中欧俄”抗美集团、这一点将在今天的欧洲部分进行展开）


*** 在反对小泉参拜靖国神社问题上，“日本鱼群”又有了新动向

然而，根据我们的观察，在反对小泉参拜靖国神社问题上，“日本鱼群”又有了新动向、对此，我们也专门解读过，那就是在前天、也就是12日，日本执政的自民党、其众参两院部分议员联手成立了一个所谓的“反参拜机构”、称之为“靖国问题学习会”。

东方评论员注意到，这个新成立的“靖国问题学习会”、其“政治立场”就是坚决要求小泉在参拜问题上采取克制态度。


*** 让小泉“兴奋”的一面

不过，这只是问题的一方面，这当然让小泉纯一郎“心烦”的一面，与此同时、也有让小泉“兴奋”的一面，那就是日本保守势力“支持小泉参拜”的呼声也在“越来越高”，日前、日本两家大报刊登的那则广告只是一方面，“真正的支持”在于“反参拜机构”“靖国问题学习会”成立之前、一个为小泉叫好、拼命为“参拜”煽风点火的“支持参拜靖国神社年轻国会议员之会”组织也已经开始运作了。值得注意的是，这个为小泉“参拜”叫好的“带头者”、就是有可能接替小泉首相职位的极右分子--自民党干事长代理安倍晋三。


*** 让小泉纯一郎真正害怕的是“外伤”

在东方评论员看来，日本出现这两个立场相去甚远的“议员组织”、其实放出了一个强烈的信号，那就是日本自民党内部围绕“支持与克制参拜靖国神社”的两派力量、开始公开形成“对决”。

显然，这还只是小泉纯一郎的“内伤”，让小泉纯一郎真正害怕的是“外伤”，我们知道，小泉政府是由自民党和公明党联合组阁、并得到执政权的。不难看出，对小泉而言，如果没有公明党的支持，小泉本人就得下台、而自民党也不可能掌握日本政府，因此、来自公明党的声音就成了小泉“必须聆听”的声音。

然而，日本公明党党首神崎武法日前也通过电视，再次重申了自己的立场，要求小泉停止继续参拜靖国神社，在东方评论员看来，神崎武法的“这一立场重申”、自然代表着公明党内部的主要立场，因此，这再次推高了自民党内、以及日本民众要求小泉停止参拜的呼声。


*** 日本主流媒体对小泉现实处境的评语就是：“他到了最困难的时刻”。

只是小泉纯一郎的麻烦还不止这一处，东方评论员认为，中日政治关系到了“一推就倒”、且已经开始影响到经济的地步、而日本反对“邮政民营化改革”的势力扬言要“废掉”小泉执政几年来的、“唯一说得出口”的政绩；再加上在“入常”问题上、由于中美已经开始“公开联手”、显然、在这个问题上日本是再遭华盛顿的“黑手”、从而被国内强烈质疑他“紧跟美国疏远亚洲”的外交政策“是否明智”，这些都成了小泉“无从解决”的难题，事实上，日本主流媒体对小泉现实处境的评语就是：“他到了最困难的时刻”。



*** 小泉要想走出困局，就必然会借“外力”化解“上述一大堆内政外交难题”

首席评论员就指出，另史上，美国有一位政治人物曾经针对所谓的政治、就说过这么一句：“任何政治（包括国际政治）都是地方政治的体现”，在我们看来，这句话说得太绝对了，在许多情况下，用它来描绘一个有杰出能力的政治家，未必合适，但用它来为“政客”画像、却往往“精确得吓人”。

显然，小泉纯一郎是个典型的投机政客，如果我们用上面“这句名言”来为他照像，就不难发现，已经“焦头烂额”的小泉、现在要做的、也正在做的、就是在“反向套用”上面这个公式，将日本地方政治（日本右翼的政治主张、日本国内反对参拜靖国神社的民意、邮政民营化改革、日本自民党内部的斗争、日本经济界的反弹等）上的困难，放在国际政治中去寻求出路。

在这种情况下，东方评论员认为，之前、小泉抛出“批准日本企业勘探东海资源许可证”这一张牌、来刺激北京、就是想迫使北京做出激烈反应之后、再来寻求解决之道、实际上是一套借“外力”化解“上述一大堆内政外交难题”的政治手段。


*** 中美联合国改革问题上，就结成了这么个“奇怪的联盟”

前面说了，北京将日本“申常”的路彻底封杀、其真正意图在于借此继续恶化日本保守势力执政的“内、外部环境”，然而、“明了”北京这种意图的华盛顿、为何也在这种关键时刻“黑”了日本一把呢？

东方评论员认为，美国除了和中国一样、不愿意别人分享自己的特权、以及报复德国、并借此压德国起着重要作用的欧盟、与自己多点合作、少点对抗的意图之外，同北京一样看清了日本国内政治的华盛顿、也想借与北京联合打破日本“申常”美梦之机，继续刺激日本保守势力、继续将中日关系往绝路上引。

也正是如此，出于各自相同、不同、甚至是根本对立的利益与动机、中美联合国改革问题上，就结成了这么个“奇怪的联盟”。在东方评论员看来，北京对华盛顿的心思、可要特别注意。


*** 北京更应该将警惕的目光盯在钓鱼岛、和东海方向

因此，东方评论员认为，北京在防止小泉孤注一掷、冒天下之大不韪于8月15日参拜靖国神社、准备好应对策略的同时，更应该将警惕的目光盯在钓鱼岛、和东海方向。

在我们看来，北京必须警惕小泉纯一郎可能以“主权争端”这种根本就不可能有回旋余地的极端形式、来挑衅自己、如果中国被迫做出激烈的、甚至是军事上的反应、那么，日本保守势力就会利用中国“可能的激烈反应”、“激励”“日本鱼群”的民粹情绪、从而让他们的“总代表”--小泉纯一郎渡过眼前的难关、并为他们今后的“总代表”强化执政基础。

*** 我们所指的“有效措施”必须是经济上的、甚至是军事上的强烈反应

所以，东方评论员认为，在这期间，北京必须以最有效的方式让日本明了“冒险将为日本和日本保守势力带来得不偿失的后果”、以及北京针对日本可能的冒险将采取的“措施“、和落实这些措施的决心。显然，就目前来看，对日本保守势力的任何“政治上的劝说与警告”都只是给他们带来了极大的压力、但却没有让它们死心，因此、我们所指的“有效措施”必须是经济上的、甚至是军事上的强烈反应。

尽管北京做出强烈反应、定会被日本右翼势力所利用，但在东方评论员看来，一旦小泉政府在钓鱼岛、东海问题上冒险、北京必须不惜一切地、动用一切手段予以痛击、一则，可以鼓励日本反对小泉的政治势力、再则，也是最为关键的，那就是中国目前正在执行着的稳定中亚、顶在中东、打通南亚、联合俄欧、经营东亚、压住日本的战略计划、如果北京不能做出强烈反应、就将被日本社会和国际社会、特别是美国和俄罗斯视之为“北京做出让步”、从而迅速调整自己的政策。如此一来，北京上述的战略计划、必将因为“压住日本”的失败而彻底失去平衡。


下面，是两则短消息，一则是有关“六方会谈”最新进展的，而另一则是中俄联合军演的、在一起了解详细情况之后，东方评论员将把关注的焦点投向朝鲜半岛。


《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
