# -*- org -*-

# Time-stamp: <2011-08-04 13:20:00 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

#+STARTUP: indent

* 2005年3月25日 星期五

** 美国务院不评论陈水扁参加反反分裂法游行

【华盛顿消息】 据报道，岛内舆论一般认为，陈水扁亲自上街，应该是在美方不反对的情况下做的决策；对此，美国国务院今天强调，对于哪些人参与台湾反反分裂法游行，国务院没有评论。国务院副发言人埃瑞利表示，美国的立场是鼓励两岸寻找对话的机会，美国也继续鼓励双方避免采取会被视为是单方面步骤，也避免采取试图透过对话以外方式解决歧见。他重申，美国反对任何升高两岸紧张的行动。


** 国民党:扁326上街不讲话是担心「言论闯祸」

【台湾消息】据台湾媒体报道，国民党发言人张荣恭昨天中午指出，陈水扁宣布326全家上街头，但不会演讲，主要是怕美国质疑陈水扁激情又起，可能会出现「言论闯祸」，所以陈水扁决定不讲话。
 
张荣恭指出，预料326游行，将有不少民众诉求「制宪、正名、台湾国「，如果国际社会认为陈水扁暗中策动游行，将丧失国际社会对台湾的同情，这在两岸分别争取国际同情之际，对台湾十分不利。
 
他认为，陈水扁主张向大陆要民主，举行326大游行，犹如台湾人民是大陆政权的子民，也犹如陈水扁成为「台湾特首」，完全是自我矮化；「中华民国是主权独立国家，早已主权在民」，怎么会有向中国要民主的道理？
 
他指出，虽然陈水扁以香港为例，要求民众游行，陈水扁也强调台湾情况不同于香港，但国际媒体报导时，恐怕会以台湾和香港作比较，误以为台湾如同香港，是中国政权下的地方政府，严重伤害台湾尊严。
 
张荣恭表示，大陆制定反分裂国家法企图堵住台独道路，陈水扁所提的「四不一没有」比反分裂法更前一步堵住台独；如果陈水扁信守「四不一没有」，大陆的反分裂法就无用武之地；326游行的独派人士，除了向大陆抗议外，更应该抗议陈水扁的「四不一没有」，陈水扁应该说明「国家」路线为何？
 

【时事点评】在之前，我们已经多次说过，台独势力将所谓的反制“反分裂法”的游行放在“326”，就是在等候赖斯在北京与中国领导人“充分交流”之后、再按华盛顿给“台独”下达指令行事。

因此，在东方评论员看来，国民党发言人张荣恭今天所讲的、陈水扁宣布326全家上街、却不演讲，主要是怕美国，是符合逻辑的。


*** 华盛顿和陈水扁之间的这种把戏演得“太逼真”了

显然，赖斯回去了，陈水扁就立刻“宣布326全家上街头，但不会演讲”，这摆明了是华盛顿向北京做的一个姿态。例外，我们还注意到一个细节，据说台湾的媒体又捅出了一则消息，说的是赖斯回到华盛顿之后，美国驻台官员就立刻与陈水扁会面，而陈水扁也就在稍后宣布“只上街、不演讲”，不难看出，华盛顿和陈水扁之间的这种把戏是演得“太逼真”了。因此，对此美国务院今天当然“没有评论”。

在东方评论员看来，不论怎么看，都是华盛顿在力劝陈水扁不不要挑衅，而陈水扁也是难得地“顾全大局、委曲求全”，如此一来，华盛顿是对北京“有个人情”，而陈水扁在“台独”内部也有个交待。

可问题是，北京并没有领这份“虚假的人情”，在东方评论员看来，客观上讲，大陆对台湾内部政治运作的影响甚微，而华盛顿对此则是“自有一套”，在台湾内部政治的运作上，北京也只能在一旁手握着部“反分裂国家法”、去静静地看着华盛顿和台独势力在那里“大玩双簧”。
 

*** 不论是华盛顿手中的“台独牌”、还是北京手中的“东亚核竞赛”，都是日本想要的

然而，好在现在有了一部墨香未尽的、授权中央军委、国务院、必须确保国家领土完整、且在不得已的情况下”必须动武”的“反分裂法”，因此，华盛顿和台独之间再怎么玩双簧，在近期之内，美国出于自己的战略考虑、还是不敢让“台独”玩出格的。

如此一来，以对华盛顿而言，华盛顿也只能心里想着“反分裂法”和“胡四点”、在那里小心地准备着“台独牌”，对北京而言，现在手中仍然还扣着一张“东亚核竞赛”的牌。不难看出，不论是华盛顿手中的“台独牌”、还是北京手中的“东亚核竞赛”，都是日本想要的，日本都能从中获取巨大的利益。


*** “台独牌”和“东亚核竞赛”牌，之所以成其为牌“都少不了日本”这个因素
 
然而，问题是，这“两张牌”的发牌权都不在日本的手中，特别是在东方评论员看来，这还不是问题的全部。最有意思的是，“台独牌”和“东亚核竞赛”牌要想玩起来，且之所以成其为牌，都少不了日本这个因素。
 
先说“台独牌”的玩法。不难想像，没有日本的保证、保证全力提供军事支援、那么，美军在台海这个地方要想有效介入“可能的台海战争”，那是句“大话”，换言之，华盛顿费心费力将日本拉进涵盖台海的“美日军事同盟”，为的就是让“自己人”相信美国有能力介入台海，从而有资格打“台独牌”，从而一来为“台独”护行，二来警告北京在准备启动“非和平方式”时“要三思”，
 
另外，就是北京手中的“东亚核竞赛”了。在之前的点评中，我们一再强调一个观点，那就是，“朝核问题”对华盛顿之所以重要，就在于美国看重日本和韩国的战略价值。特别是日本因素，在东方评论员看来，也不难想像的是，如果没有日本的“核梦想”，如果不担心日本摆脱自己的控制，继而会“反咬一口”、在这个时候，华盛顿是不太会在乎朝鲜“有核无核的”，那么北京手中的那张牌、也就不成其为“牌”了。


*** 美国面对的选择似乎不多，好像只有两个

然而，正是有了日本这个让华盛顿一直极其警惕的因素，北京手中挰着个“东亚核竞赛”，惹得日本在美国急欲稳定的东亚、是“又跳又闹”、这种局面终于让华盛顿认识到、要想继续向过去那样让“朝鲜半岛”处于“可紧可松”的可控的“紧张状态”，已经难以为继了。

显然，美国面对的选择似乎不多，好像只有两个，一是缓和，其结果就是带着中国所希望的“诚意和灵活”、回到“六方会谈”，不仅要谈，还要解决“实际问题”，在东方评论员看来，华盛顿以一种灵活姿态去改变对朝鲜的敌视政策、以利于朝鲜进行经济改革、这才是北京“所要求的建设性”。不难看出，这不仅是北京乐见的“建设性”、更是韩国乐见的“建设性”。

另一种选择就是“让朝鲜半岛局势进一步紧张”，显然，其结果是不需要华盛顿“多做什么工作”，因为、日本正在拼命地做着这种事。
 

*** 日本做的这种事，是从两个方面着手的

在东方评论员看来，日本做的这种事，是从两个方面着手的，第一，是朝鲜半岛方向，比如说、强硬要求朝鲜无条件回到“六方会谈”、并为之划下”6月“为最后期限，在独岛问题上一再“有意的”挑畔“韩朝”民族情绪，等等，都是出于这种目的，为的就是刺激朝鲜和韩国、让朝鲜半岛的政治安排更乱、并逼朝鲜“跳得更高”、最好就是做出让日本有机可乘的“大动作”来。
 

*** 日本“唯恐北京不震怒”的嘴脸是曝露无遗

第二，就是北京方向，日本在冲着北京的动作近来可以说是更密集了。日本又在“高调地”篡改其侵略历史，还倒打一耙、指责中国“在搞反日教育”，另外，还公开声称台湾海峡是“国际海域”、日本的责任维护其稳定、最后还不忘记指责中国“不高兴”日本成为常任理事国等等，在东方评论员看来，日本这种“唯恐北京不震怒”的嘴脸、可以说是曝露无遗。
 
 
*** 北京表现得还就是“不震怒”，一如既往地、就“拿着日本想要的那张牌”只与美国“谈问题”

然而，北京表现得还就是“不震怒”，就如上次通过朝鲜“宣布有核”、挰着手中的这张牌，迫使“美日”在搞出了一份“美日安全共同声明”后，在日本自感被美国出卖、而与美国相互埋怨、相互揭短的过程中所做的那样，干脆将日本丢在一边、一如既往地“拿着日本想要的那张牌”只与美国“谈问题”。

事实上，北京的这种策略再次起到了效果，在东方评论员看来，布什和小泉纯一郎在是否给“朝核问题”划出期限的问题上“所生出的龌龊”，实际上是美日各自战略利益
上“既有矛盾”造成的。

我们认为，它原本就存在着、只是北京和华盛顿之间的重大战略利益的“交叉点”、远不止台海、朝鲜这两处、因此，经北京“用核问题这么一挑”、美日之间在战略利益取向上的分岐、就立刻彰显出来而已。
 
下面，我们就来看看赖斯访华的一则后续消息，从中我们似乎能看出华盛顿在朝核问题上的政策取向上、在想些什么。
 
《东方时代环球时事解读》http://www.dongfangtime.com
