# -*- org -*-

# Time-stamp: <2011-08-04 13:21:20 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 05年6月10日 星期五

 

** 美众院竟通过所谓支持台领导人访美修正案

【华盛顿消息】美国联邦众议院国际关系委员会9日通过HR2601号外交关系授权法案，其中包括修正第806节条文，支持台湾民选领导人前来美国进行高阶访问。

这项没有拘束力的修正条款为：“与台湾‘民主’选出的领导人及指派的官员直接沟通，包括台湾‘总统’、‘副总统’、‘外交部长’及‘国防部长’，符合美国的国家利益。根据103-416号公共法律，国务院应允许台湾高阶官员访问美国，与美国官员讨论共同关切的议题。国务院应与台湾‘外交部’合作，促成台湾高层官员与美方对口官员会面。”


【时事点评】在东方评论员看来，美国人这段时间在台湾问题上“说话算话”是越来越明显了。只是不是“反台独”、而是“支持台独”的“说话算数”：前面有白宫的“不设前提”的要求两岸和谈、现在、美国国会又有了台湾民选领导人、也就是支持陈水扁前去美国访问的“修正案”。


*** 与美国会“严重关切”中国通过“反分裂国家法”时所玩的把戏“如出一辙”

然而，东方评论员注意到，这份“修正案”，仍然有如早前美国国会表示“严重关切”中国通过“反分裂国家法”时、所玩的把戏“如出一辙”、即，都是“没有拘束力”的“说话可以不用负责的”“叫嚣”，其对北京施加外交压力的意图非常明显。

另外，在我们看来，美国的“行政与立法”两大系统在同一时间内向“台独”放送错误信号，显然是在“及时地”警告北京，东方评论员认为，这种“警告”就是：在“台湾问题”上“仍然是美国人说了算”。


*** 在“台湾问题”上美国人“说了算”，这在“某种程度上”是事实

东方评论员认为，客观上讲，在“台湾问题”上美国人“说了算”，这在某种程度上是事实，那就是在“台独进程”“轻重缓急”的控制上、在如何操纵台湾民意的问题上，的确是美国人“说了算”。

然而，由于北京已经在3月份将那个“最后通谍”式的、不惜一切代价也要坚决粉碎“台独”重大事变的“517声明”法律化成一部、对中国决策层有约束力的“反分裂国家法”之后，美国人“说了算”的也仅限于操纵“台独进程”的“快与慢”而已，也就是“台独”的“量变过程”而已。

不难看出，“台独”和支持“台独”的国际势力，是否敢于制造“台独重大事变”的“质变”，恐怕就不是美国人“说了就算”的事儿、在东方评论员看来，这是美国自我判断“有无足够的实力”、“敢打”、并“值得打”这张“台独牌”的问题。

在我们进一步点评美军“有无足够的实力”、“敢打”、并“值得打”这张“台独牌”的问题之前，再来看一段消息、看看中国军方的一种观点。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 中国军方：中国非伊拉克卷入台海代价巨大

【综合消息】综合报道，针对美国总统布什日前在接受专访时有关台湾问题的言论，中国军方长期关注台湾问题的一位将领表示，台湾问题是中国内政，不容别国干涉。中国不是伊拉克，倘若别国真要卷入台海事端，中国军队定会令他们付出不能承受的代价。

卷入台海事端代价巨大

美国总统布什近日在接受霍士电视台专访时再度重申，如果台湾遭到任何国家入侵，美国会基于《台湾关系法》的精神「挺身而出」，而当被问到如果台湾受到中国大陆武力进攻，美国是否会遵守承诺协防台湾时，布什回答说：「是的，我们会。」

据香港文汇报报道，中国军方一位长期关注台湾问题的将领表示，某国军力强大，世界第一，这是事实。但中国人捍卫祖国领土和主权完整的决心不可动摇。

这位将领强调，「中国并非伊拉克」，一旦别国胆敢干涉中国内政，卷入台海事端，中国完全有能力使他们付出不能承受的代价。

美向台售武发错误信息

这位将领引述中国政府发表的《2004年国防白皮书》指出，中国人民坚决反对任何形式的「台独」分裂活动，坚决反对任何形式的外来干涉，坚决反对任何国家向台湾出售武器或与台湾进行任何形式的军事结盟，决不允许任何人以任何方式把台湾从中国分割出去。

白皮书批评美国虽多次重申坚持一个中国政策、遵守三个联合公报、反对「台独」的立场。但却继续提升售台武器的数量和质量，向台湾当局发出错误信号，不利于台海局势的稳定。

李侃如：中美关系或出现坎坷期

另据报道，克林顿政府时期的白宫亚洲政策资深主任李侃如周四解读美国总统布什对中美关系的评价时说，布什使用“错综复杂”一词不如之前选用的“坦诚和建设性”关系那么正面。而中美关系由于目前的一些难题和美国国内的政治气氛可能面临一段坎坷的时期。

他说，中美目前面临几个重要的议题需要解决，包括朝核问题、经贸关系和知识产权的保护等。而由于布什不用再竞选总统，准备在08年参加选举的政客已经开始寻找攻击政府的话题，这就使中美关系的积极发展更加困难。

基辛格：中美必将走向对抗的观点是错误和危险的

而另一方面，前美国国务卿基辛格周四在《国际先驱论坛报》上以“冲突不是选择”为题目发表评论文章指出，有人将中国的崛起和德国在20世纪初期的崛起相比，认为中美必将走向对抗，这样的假设是错误和危险的。他说，从历史上看，军国主义从来不是中国的风格，因此美国在对华政策上也不应该使用冷战时期的遏制政策。

基辛格说，台湾问题经常被看作是引发中美军事冲突的一个可能性。他说，中美双方在过去的几十年来都在这个问题上保持克制，只有双方都放弃了坚持多年的克制才可能引发冲突，而这样的冲突远远不是不可避免的。

他说，中国和亚洲的崛起正在将国际政治的重心从大西洋移向太平洋。这一现象将在未来几十年内大幅改变现有的世界秩序。美国应该认识到中国不会消失，而和中国冷战对美国也没有好处。他说，为了世界和平，美国应该和中国合作。

基辛格还指出，中美双方都应该认识到他们对待对方的态度是很重要的。中国不应该将美国排斥在亚洲事务之外，而美国也必须明白，对于一个有着四千年连续发展史的中国，在交往中使用恃强凌弱的口吻是不合适的。




【时事点评】在东方评论员看来，北京敢制定、并执行“明列有”必须以“非和平方式”维护国家主权完整的“反分裂国家法”、显示出来的是“敢用、也必须用战争方式解决台独”的“决心与意志”，显然，北京宣示这种“战争的决心与意志”、其勇气来源于“台湾是中国的核心利益”，“倚靠”的是维护国家主权的决心和维护国家主权的实力。

*** 大陆落实“非和平方式”所倚靠的实力、就是以战略核打击实力为基础的“全球打击能力”

一个已经为国际社会体认的事实是，北京通过“反分裂国家法”显示出的决心、是一种“台独就是战争”的决心，而一旦“台独进程”从“量变到质变”的时候，大陆“启动”“反分裂国家法”相应条款、落实“非和平方式”所倚靠的实力、就是以战略核打击实力为基础的、如拉姆斯菲尔德所说的“可以让导弹射向任何目标、任何国家”“全球军事打击能力”。


*** “中国并非伊拉克”，是对布什“这一论调”所做出的、“针锋相对的反击”

之前，我们也注意到，布什日前是“再度重申”：如果台湾遭到任何国家入侵，美国会基于《台湾关系法》的精神“挺身而出”，而当被问到如果台湾受到中国大陆武力进攻，美国是否会遵守承诺协防台湾时，布什回答说：“是的，我们会。”

因此，在东方评论员看来，中国这位将领所强调的、“中国并非伊拉克”，“一旦别国胆敢干涉中国内政，卷入台海事端，中国完全有能力使他们付出不能承受的代价”的说法、显然是对布什“这一论调”所做出的、“针锋相对的反击”。


*** 眼下，美国在可动用的“战争能力”上，已经到了它能够使用的极限

在东方军事评论员看来，美国的军事能力有多强、准备、并支持一场战争的能力有多强，通过“北约VS前南联盟”、“美国VS伊拉克”这两场实力悬殊的战争中，就可以清楚地看出来了。


*** 美国“需要操心”的地方太多了

特别是伊拉克战争，在过去两年后，美国庞大的军事资源仍然扔在伊拉克而不能动弹。值得强调的是，在备受主要是从叙利亚渗透到伊拉克反美武装袭击的同时，一向“指哪打哪”华盛顿、除了动嘴之外，还就是不敢把紧靠在伊拉克旁边的、对巴以冲突如何解决起重要作用的叙利亚“怎么样”。

现在，欧洲在忙着一体化进程、排挤美国在欧洲的军事、政治势力的同时，还在美国最关注的中东、特别是两伊问题上“上下其手”；中国也在忙着东北亚、东亚经济一体化、并以此做为慢慢清除美国在东亚、东北亚、以至整个亚洲影响力的手段，同时，还在中亚增强影响，意在打通向西的、通往欧洲的欧亚大陆桥、并以此与欧洲在战略上相策应；在南亚方向、与印度合作，意在打通从中国西南、经南亚到中东的陆上能源通道。

而最有意思的是就是俄罗斯，显然，俄罗斯除了在中东、中亚、欧洲方向与美国有战略纷争的同时，眼光还死死地盯着美国在亚洲最重要的盟友--日本，大有找准机会“伸一腿”的心思、意在吸引日本的资金与技术，一来帮助日本摆脱中美的压制、二来，则结合俄罗斯自己的资源优势、开发地处东北亚的、紧靠中国东北、朝鲜的远东地区，以图东山再起，从而避免沦为中国、欧洲的资源供应基地的处境。


*** 华盛顿何以不敢对“巴以冲突”起重要作用的叙利亚“怎么样”？

正是有了上面这么“许许多多的背景”，我们就不难发现对各个大国而言，“最为重要的战略要点”，一个是中东的伊朗、再就是东北亚的朝鲜。

值得强调的是，叙利亚的“大国背景”相比上面两个战略要点、要“弱得多”，在这种情况下，美国在对付身后站着两个、或者更多个大国的朝鲜和伊朗的时候，也就更是“只能做君子”-只能动口而不能动手了。


*** 仅是伊拉克这一家，就已经几乎到了美国能够调动、并使用的极限

东方军事评论员认为，这足以说明在周围大国都在虎视耽耽美国在全球的利益的时候，美国需要注意的地方太多了，因此，在战争能力的使用上，在经济能力的支持上，仅是伊拉克这一家，就已经几乎到了美国能够调动、并使用的极限。


*** 美国人深深的知道，仅凭航母舰队是不能打败中国的

然而，就如这位中国将军所说的那样，“中国不是伊拉克”，不仅如此，在东方评论员看来，中国也不是南斯拉夫、还不是越南，因为中国有广阔的战略纵深，众多的人口，还有远程核打击力量、更重要的是，中国有自成体系的军事工业、这就注定了中国有很深厚的战争潜力和核报复能力。

根据我们的了解，美国人深深的知道，仅凭航母舰队是不能打败中国的，因为美国在伊拉克战争中、在大批盟军、和阿拉伯国家军事基地的帮助下、还得调用了6艘航空母舰，尽管这些航空母舰本身不过是一个非常安全的“飞机场”，不承担任何作战任务，还不不必担心任何攻击。

由此可见，对付一个几乎没有抵抗能力、更没有攻击能力的伊拉克，就得如此兴师动众，那么，要对付有各种直接打击美国航空母舰战斗群、甚至美国本土之军事手段的中国，华盛顿又准备动用多少艘航空母舰呢？从这些航空母舰上得起飞多少军机呢？

有意思的是，我们刚好有了一份来自美国“最权威研究机构”评估报告、其中，有一相关段落就提供了这么一个“令人深思”的数据。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 美国智库兰德：美国必须准备1500架以上的飞机

【华盛顿消息】美国智库兰德公司曾分析说，美军一旦卷入台海冲突，可能出现四种状况，都是由司令部开始因应第一步：威慑、局部战争、全面战争以及核战争。

如果大陆单纯使用导弹攻击或海上封锁，美国不必与大陆进行大规模冲突，所以美军以一个航母战斗群在台湾外海采取戒备，同时进一步以物资协助台湾。如果大陆没有罢手，美国开始集结兵力，增强威慑力度。

但是如果威慑策略失效，美国可能与中国发生正面冲突，局部或全面战争都可能出现。美国必须准备1500架以上的飞机以有效压制解放军，并取得制空权。这就要与其它地区司令部共同因应了。

进入司令部，一份辖区涵盖示意图上除了标出有条约义务的国家(例如日、韩)外，也标出美国有安全承诺的四个地区，分别是密克罗尼西亚、马绍尔群岛、帛琉以及台湾。示意图上，韩国、朝鲜是不同颜色，可是台湾和大陆却同为黄色，目的在显示“一个中国”政策。然而，所谓辖区内的四十三国(不含美国)，却又是把台湾和大陆分开计算，也把朝鲜北南分开计算。



【时事点评】我们注意到，兰德在这份报告中认为，“美国可能与中国发生正面冲突，局部或全面战争都可能出现。美国必须准备1500架以上的飞机以有效压制解放军，并取得制空权”。

显然，1500架的飞机，是不可能装在美国所有的十几艘航空母舰上的，另外，我们也注意到，兰德还认为，要做到这一点，美军太平洋司令部“要与其它地区司令部共同协调”。

*** 中国完全有能力使他们付出不能承受的代价

非常清楚，美国人还没有自大到仅靠一个太平洋司令部就能威慑中国的。东方军事评论员就认为，何况美国的航母舰队、在向台海附近集中的过程中、不仅不可能消灭中国的远程核打击力量和深海核打击力量。

相反，美国的航母舰队、特别是为这些航空母舰提供后勤保障的运输力量，以及这批数量庞大的军机部暑在他国的、比如说在日本军事基地、还是这些打击力量、以及远程突击武器最好的标靶。在我们看来，战时的中国、的确“完全有能力”使美国付出不能承受的代价。


*** 日本战争后，其利益又如何体现？

另外，多年以来，除了朝鲜战争、越南战争之外，不论怎么讲，美国事实上都是在靠欺负弱国获得的“硕硕战果”，和中国在台海这里开战、显然是极具风险的，稍有闪失，丢了台湾不说、恐怕整个东亚都不保。

此外，美国的国际声望也必将一落千丈，历史上，越战的失败、就使的美国在二战中积累起国际声望丧失殆尽，并一把就失去了在与苏联对抗中的优势地位，以越战争为转折点，苏联开始掌握全球争霸的主动权，又以阿富汗战争苏联失败为转折点，美国重新拿回主动权。

在东方评论员看来，有了这些历史上的教训和经验，在现在这种大国伺立的形势下，华盛顿自然会“仔细评估”到底哪头更重要、为了台海与中国正面冲突，就是保住其世界霸权的唯一途径吗？如果是，那自然会见输赢，这就很可能令战争失控，直到打核战争，其中、日本在这种战争中、其利益在什么地方？如果不是，那么，华盛顿维持其全球霸权的另一途径是什么？日本在华盛顿的另一种选择中，其利益又如何体现？


*** 中美会给日本这样一个置身于外的机会吗？


作为美国在欧亚大陆谋局的一个“支点”，日本其实不能算一个有“独立”的大国。不难看出，由于华盛顿需要照料的全球战略要点太多，而日本不仅离中国太近、且日本自己太小，纵深有限，其经济更是不能支持长时间的战争，何况战争结束后，不论是中国统一，还是台独独立，只有两种结果，第一，中美之中必然有一家的势力空前强大，这时的日本、自己是否能摆脱中国或者美国的控制，都是未知之数。第二，就是，一家被削弱，而另一家则更弱，这时，日本如果没有参战、或者没有受损失，自然是最大的赢家，然而，中美会给日本这样一个置身于外的机会吗？



*** 不排除中国于战争初期、就用核力量直接突击参与战争的日本主要军事基地、和港口的可能性

在我们看来，一场持久战、消耗战代价很大。东方评论员认为，这样两个军事大国打仗很难控制战争的规模不扩大，这样容易引发横跨太平洋的大战、甚至是核战争，如此一来，这样对美国而言代价极大，对中国而言代价也极大。

在东方军事评论员看来，如果美国敢打台独牌、并强行卷入台海战争，那么，离开日本的军事支持是不可能的。因此，我们认为，在关键时候，出于“不战而屈人之兵”的诱惑，不排除中国于战争初期、就用核力量直接突击参与战争的日本主要军事基地、和港口，从而迅速打掉美国海军在这一区域内作战潜力的可能性。

在很大程度上，由于中国打击的是日本目标、或者中国海上军事力量单个目标价值有限，这就等于将是否突击中国本土、从而“启动核大战”的选择权踢给了华盛顿。


*** 如果....恐怕又将直接导致东亚格局的“乾坤大挪移”

显然，东方评论员认为，日本在自己没有核武器的情况下，介入台海战争是有遭受中国核突击的危险的，合理的推测是，日本必然会以此要求美国准许日本跨入核门槛。

在我们看来，可问题是，跨入了核门槛的日本，必然会引发朝鲜半岛上的韩国也会寻求核武装，有了核武器的韩国和日本，将如何处理与美国的军事同盟关系，是否能善待意在监视自己的美国的军事基地、或者是否美国和日本都“同时愿意冒着核战”的风险、同时在台海与中国发生直接冲突、恐怕只是有可能、但又不是完全可能，显然，如果美国和日本中的一家，各自对台湾的战略价值“有着不同的评估”、而据此反映到“参战意愿”上来，那么，这恐怕又将直接导致东亚格局的“乾坤大挪移”。


*** 一个类似“蛋生鸡、还是鸡生蛋”的“简单而又复杂”的问题

因此，在东方评论员看来，美国和日本“对台湾的战略价值”、对台海战争“利与弊”之评估是“不可能完全一样”的，这样，华盛顿是对北京“先打台独牌”、还是“先打日本核武牌”，日本是“先要核武”、“是否参战”，在美国决策层的头脑里，很可能是一个类似“蛋生鸡、还是鸡生蛋”的“简单而又复杂”的问题。


*** “狡猾的”、做事从来都按法律行事的美国人、早就明白这样一个道理


然而，在东方评论员的记忆里，华盛顿从来没有敢就《与台湾关系法》的协防台湾的条件“加以明晰”，也就是说，“狡猾的”、做事从来都按法律行事的美国人、早就明白这样一个道理：那就是，在台湾这个牵一发而动全身的问题上，将原本应该“明细”成一种具有“可操作性的”法律、给模糊成任意解读的“精神”、才最符合美国的利益。

东方评论员认为，也只有在这种情况下，什么“与台湾关系法”、“美日军事同盟”、“遏制中国”，“武力抗统”、“协防台湾”、“对台军售”，“朝核问题”、“中东问题”、“日本定位问题”、甚至是“人民币”、“纺织品”问题、如此总总，也就“都能找到卖点”。

说到对台军售，下面还有一则消息，在一起阅读之后，东方时事评论员、军事评论员将继续讨论台湾问题。我们知道，中国外交部发言人刘建超日前曾经表示，“希望美国不要通过军售向台湾当局传递错误信号，以致局面“不可收拾”。因此，结合这段新闻，我们将再次谈谈这笔会导致局面“不可收拾”的“对台军售”、其“要害实质”到底在哪里？

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
