# -*- org -*-

# Time-stamp: <2011-08-04 11:54:27 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

*  2005年7月06日 星期三

   

** BBC：中亚领导人抨击西方威胁该地区稳定




【英国广播公司消息】英国广播公司（BBC）6日报道，鉴于在阿富汗的大规模反恐军事行动已经结束，包括中国在内的上海合作组织成员国签署宣言，敦促以美国为首的外国军队应该确定从该组织成员国撤军的最后期限。

BBC的消息说，这份名为《上海合作组织成员国元首宣言》与本月初中国国家主席胡锦涛与俄罗斯总统签署的关于２１世纪国际秩序的联合声明相呼应。中俄两国元首认为，该声明体现了两国对重大国际问题有相同看法和立场，表明两国致力于建立公正合理的国际政治经济新秩序的愿望和决心，有利于推动２１世纪国际秩序朝着健康稳定的方向发展。

这家广播公司认为，此次上海合作组织成员国签署元首宣言，是因为该组织的成员国指责近两年来发生在格鲁吉亚、乌克兰和乌兹别克斯坦的骚乱都具有西方背景。

BBC援引哈萨克斯坦共和国总统纳扎尔巴耶夫的表态报道：“决不能允许外部势力干预主权国家的内部事务。”乌兹别克斯坦共和国总统卡里莫夫也抨击说：外部势力正威胁着中亚地区的稳定，并把“它们的发展模式”强加给该地区。




【时事点评】一方面，阿斯塔纳峰会是“颜色革命”发生后上海合作组织成员国元首之间的首次聚会，而另一方面，就如在昨天的中亚部分，东方评论员所说的那样，“上海合作组织”通过这次阿斯塔纳峰会、暂进解决了中亚国家侧重“经济性”与俄罗斯侧重“政治性”、以及中国侧重的“以经济整合政治”的“路线问题”。


*** 确定了上海合作组织的“总路线”

对此，首席评论员就指出，仅凭此点，阿斯塔纳峰会也将成为本年度最重大的国际事件之一。在我们看来，经此峰会，上海合作组织即以政治上对外（美国）强硬、经济上对内（中国）开放的模式，确定了上海合作组织的“总路线”。

在东方评论员看来，在政治上对外强硬的问题上，这次峰会“以组织的名义”发表了两个重要共识：第一，就是哈萨克斯坦共和国总统纳扎尔巴耶夫，和乌兹别克斯坦共和国总统卡里莫夫所归纳的那样：外部势力正威胁着中亚地区的稳定，并把“它们的发展模式”强加给该地区；第二，敦促以美国为首的外国军队应该确定从该组织成员国撤军的最后期限。


*** “强硬的对美政治立场”，似乎更符合莫斯科的“胃口”

显然，在上述两个共识中，上海合作组织的“政治矛头”、可以说是直指华盛顿。东方评论员就认为，这一“强硬的对美政治立场”，虽然符合北京的利益，但在目前的政治角力中、却似乎更加符合莫斯科胃口。


*** 限期“临时布署”的外国军队从上合组织成员国撤军，应该是莫斯科“最主张”提出的

我们注意到，元首宣言刚一发表，俄罗斯外长拉夫罗夫就立刻直言不讳地表示，“消灭和清除从阿富汗渗透到该地区的任务应当由集体安全条约组织和上海合作组织的相应机构来完成”。在东方评论员看来，俄罗斯如此迫不及待就有理由的，因为美国在中亚的军事基地、是华盛顿在所在国搞颜色革命的大本营，首先呑食的就是俄罗斯的“现实利益”。

因此，东方评论员认为，限期“临时布署”的外国军队从上合组织成员国撤军、与其说它是北京“最希望”提出的、还不如说是莫斯科“最主张”提出的来得准确（关于这一点，我们将在稍后的讨论中，进行展开）。


*** 面对“中俄”联手“驱除鞑虏”，华盛顿的自信心已经不那么足了

然而，不论是谁最主张提出的，东方评论员看到的如下事实才是最重要的：第一，“中俄”已经在公开宣示“准备带领中亚国家将美国排挤出中亚”；第二，美国也开始酸溜溜地用“没有一个基地重要到离开它，我们就不能运行的程度”的说法、来为自己寻找台阶了。显然，面对“中俄”联手欲在中亚“驱除鞑虏”的“宣言书”，华盛顿的自信心已经不那么足了。


*** 北京一直所追寻的目标

东方评论员认为，在经济上“对内开放的问题”上，绝对是北京一直所追寻的目标，在我们看来，北京在中亚政策、或者说是北京想借助上海合作组织实现的一大目标，就在于以在经济层面寻求上海合作组织成员国的经济整合、并在这个基础上与中亚、俄罗斯形成“政治经济利益共同体”、并联手俄罗斯、将美国势力逐出中亚、寻机打通由中国经中亚、通往西欧的欧亚大陆桥。从而一手从中亚得到稳定的能源供应，一手为中国的资金和商品找到一片稳定的市场，


*** 北京追寻这种目标，是有事实依据的

在东方评论员看来，北京追寻这种目标，是有事实依据的。首先，从地理上看，中亚国家发展国际贸易“存在天然缺陷”：其与海洋的最近距离也在1700多公里以上，而且要途经阿富汗等国，然后进入印度洋，目前这条出海通道、因阿富汗没有稳定下来，也基本上还没发挥任何作用。

与此同时，另一条路，即经由中国新疆、甘肃，然后取道连云港，就成了中亚国家主要的出海通道。这中间，比如哈萨克斯坦和乌兹别克斯坦这两个最重要的中亚国家，事实上都在利用中国连云港进出口货物，如此一来，现实的情况就是，就是在中亚最偏僻的地方、我们也能见到大量的中国商品。

因此，在东方评论员看来，由于中国的经济与中亚那种以能源、资源为主的单一经济模式、有着极强的互补性，再加上地理上的天然优势，事实上，随着中国经济的持续快速发展，这些中亚国家也就越来越把中国看成“最为理想的合作伙伴”了，事实上，中国已经在起着带动中亚国家经济多元发展的“动力引擎”的作用了。


*** 这次峰会的成果，是一连串“颜色革命”的必然结果

在我们看来，这次峰会之所以如此醒目，就在于它是中亚一连串“颜色革命”之后的首次峰会，而这次峰会之所以如此重要，就在于“两点”，第一，它是欧美围着俄罗斯边境搞的一串“颜色革命”，客观上起到“点醒”作用之后的必然结果。

东方评论员认为，欧美在格鲁吉亚、乌克兰、吉尔吉斯斯坦“得”，“彻底点醒了”那些承袭于前苏联政权结构、却又想在“中俄美欧”四大势力间跳舞的中亚国家统治阶层，我们认为，正是这种“点醒效应”，直接导致了欧美在乌兹别克斯坦策划颜色革命时，终遭到乌兹别克斯坦政府的坚决抵抗，并敢于使用武力来保护自己手中的政权，从而造成华盛顿在乌兹别克斯坦的“重大损失”，在这一点上，乌兹别克斯坦一早就要求美国限制使用在该国的军事基地就是一例。


*** 现实的国际形势促使中俄双方“有意淡化”“心结”

另外，这种“点醒效应”同样发生在俄罗斯的身上。在东方评论员看来，中俄两国间的、特别是近100年来一直比中国强大的俄罗斯、始终对中国的快速发展怀有一种戒心。我们认为，近年来、尽管中俄的关系虽然有了极大的发展，但是，从远东油管建设一波三折、和胡锦涛主席这次访俄还“专程安排”了俄罗斯新西伯利亚一站“进行公关”等事实，无一不说明、俄罗斯对中国的“不放心”始终没有完全消除。

东方评论员注意到，随着中俄经贸合作的深入，“中国威胁论”也传到了俄西伯利亚地区。一些俄罗斯人甚至还将其“本地化”，将“中国威胁论”解释成中国人进入该地区意在对俄罗斯进行“人口扩张”和“经济扩张”。

然而，现实的国际形势促使中俄双方“有意淡化”这一心结，原因在于中俄两国都面临以美国为首的西方保守势力越来越大的战略压力。


*** 直到不久前，北京都不愿意在东亚之外“公开地亮明”“挑战美国利益”立场

在东方评论员看来，这种压力对中国而言，表现在西方保守势力企图遏制中国的和平发展，在人民币汇率、纺织品贸易以及中国军力等问题上，频频向中国发难，美国甚至通过加强美日联盟，就是利用“台独”、通过“运营”日本这颗战略棋子，让日本作为插手中国台海事务的马前卒，跳上在东亚对抗中国的第一线，而自己则居中策应、从而最大限度地保持政策的灵活性，即，一面维持正常的中美关系，一面亲自出面与中国保持合作、一面却通过日本、利用台独对北京“下药”。

与此同时，直到不久前，除了台湾、朝核问题之外，北京都不愿意公开地亮明自己“挑战美国利益”的立场、而只愿意策略地以一种“与欧洲、俄罗斯一起抗美”的姿态出现。


*** 北京这一姿态的转变，其背景就是美国“正在论证”“中国威胁论”的可行性

显然，北京这一姿态的转变，就在于美国正“上上下下齐动员”、在“中国威胁论”的理论指导下、“拿着放大镜”在政治、经济、军事各个方面拼命地“论证着”所谓的“中国威胁论”的“可行性”。

在我们看来，中国与美国之间的关系，发展到今天，由于中国的综合国力的提高，已经堪称这个地球上最为复杂的双边关系了，这首先就表现在中美双方在众多国际问题上，有广泛的“相互利用价值”。也正是这种广泛的“相互利用价值”、使得对于中美双方而言，如想让战略利益最大化，就得确保“不要公开地相互为敌”。


*** 我们想在这里再次强调的一个观点

因此，就如我们之前一再强调的一个观点那样，那就是，别的国家都可以将“中国威胁论”立为“国策”，包括日本在内，唯独美国不可以，为什么？在东方评论员看来，其中的原因太多，在这里只说两点：，第一，美国的战略利益不止在亚洲，而它的对手也远不止中国一家；第二，中国在亚洲的影响力和综合国力，已经不是华盛顿想压制就压制得了的了。


*** 华盛顿若将“中国威胁论”付诸实践，对美国的全球战略是“弊远远大于利”

因此，东方评论员认为，华盛顿若果真将“中国威胁论”付诸实践的话，那么，它对美国人的全球战略来说、是“弊远远大于利”，事实上，在我们看来，美国国内对此有清楚认识的“有智之士”是大有人在。

在我们看来，出于维护自己的霸权的目的出发，华盛顿决策层在“中国威胁论”的问题上，必然是慎之又慎，在我们看来，在这个问题上，起码美国人要比日本人慎重得多。


首席评论员指出，显然，北京同意在“上海合作组织”元首宣言中、公开要求“外国军队”从成员国“限期撤军”，就是针对美国的“以论证中国威胁论”的方式、去“侦察”中国、试探欧盟、俄罗斯、以及日本的可能态度时、所做出的一项“反侦察”措施，

在我们继续这一讨论前，再来看一则分析文章，说的是人民币的问题。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 人民币汇率“牌局”的美国套路



【中华工商时报文章】《中华工商时报》今日载文指出，人民币汇率之争有如牌局，两个对手是中国和美国。中国是守方，但主动权在中国手里。美国是攻方，但他的牌点和牌路在明处。这副名叫人民币汇率的牌局叫的将牌是经济，但真正打的是政治。这副牌打到这个时候，恐怕将近尾声了。

由美国参议员舒默和格莱汉姆领衔提出的逼迫人民币升值的提案目前已被搁置。其中的原因据说是6月30日下午，这两位参议员在与财政部长斯诺和联邦储备委员会主席格林斯潘举行会晤后宣布，他们对行政部门解决这一问题有信心，因此暂时搁置对该法案的投票表决。

果真是美国议员对行政部门有信心吗？不是。是他们对自己的牌路很清楚。从格林斯潘和斯诺的角度看，人民币汇率是经济问题。从美国政府和国会的角度看，人民币汇率是政治和战略问题。

格老说的没错，人民币升值解决不了美国的贸易逆差和纺织工人失业问题。这一点，斯诺也清楚，布什也清楚，舒默和格莱汉姆恐怕也明白。表面上看，美国政府和国会是出于利益团体的政治压力而要求人民币升值的，但透过民意的薄纱，其实可以看到美国政府的全球战略在隐隐发力。

格老和斯诺只是两张将牌，美国人真正的牌路是获得战略利益。

战略利益包括两方面。

一方面是让人民币升值，削弱中国产品的国际竞争力，其目的是避免中国产品对美国市场和全球市场造成冲击，防止中国产品在美国市场可能占据垄断地位，从而既可以维护美国的经济安全，又可以维持美国的自由竞争体制。

另一方面是让中国产品让出市场，为美国战略伙伴提供机会。大家都明白，人民币升值的结果并不会让美国工人的日子好到哪里去，主要原因就是其他国家的产品会替代中国产品，这个替代国可能是墨西哥，可能是越南，可能是印度，也可能是多米尼加。实际上，美国在用市场换取这些国家的战略支持。

在这种战略思维下，美国人对中国汇率体制改革的要求将是坚决和持久的。如果单纯用经济和民意的维度去考虑美国人的牌路就显得太简单了。对于美国人来说，中国不是替罪羊，中国是刚刚进入草原的一只狼。让人民币升值，就是让狼降低奔跑的速度。

当然，美国也了解中国的底牌。中国的底牌也是政治。但中国经济的崛起使得中国汇率体制本身存在内在的改革要求，在这个背景下，中国所能做的不是坚持不让人民币升值，而只能是坚持让自己做主人民币何时升值。

所以，格林斯潘和斯诺，舒默和格莱汉姆，本来是两种花色，但他们现在做出了一致的选择，这就是等中国出牌，也就是让中国自己做主。

他们不看过程，只等结果。这是美国人的默契。




【时事点评】在东方评论员看来，这篇评论对牛皮哄哄的美国国会、是如何“不得已”将逼迫人民币升值的提案“自动搁置起来”的分析可以说非常到位。

根据我们的观察、在华盛顿这边，可以说动员了学者、舆论、国会议员、政府高官等一切可以动员的力量、一天到晚到狂炒“中国威胁论”的各种版本，但是，直到目前为止，都不过是在和拉姆斯菲尔德“在新加坡首抛中国军事威胁论”时、所做的事情、所抱的期待一个样，即在试探北京的反应、也在试探各方势力、各方强权的反应：看看北京是否强硬？探探各方会否跟进？

*** 北京再度强硬声明“绝不让步”之后，格林斯潘就出来打圆场了

事实上，在东方评论员看来，不仅纺织品、汇率问题是政治问题、就是中海油收购案也是政治问题。在中国政府于胡锦涛主席出席G8+5会议之前，再度以强硬地声明“绝不让步”的态度之后，格林斯潘就出来打圆场了，说什么“他们对行政部门解决这一问题有信心，因此暂时搁置对该法案的投票表决”。


*** 汇率问题本身就是美国在“论证”“中国威胁论”“经济版本”的可行性

实际上，汇率问题也是美国“论证”“中国威胁论”是否可行的试探手段之一，表面上看，欧洲、美洲、都对中国的人民币汇率有意见，有想法，这本身就是美国在“论证”“中国威胁论”的“经济版本”的可行性。

因此，华盛顿玩的这手是在“挟天下以令中国”，然而，中国的强硬说明，中国的人民币当然可以调整，但绝不是在自己承受不了的情况是被迫调整，更不会在强迫下被迫调整，因此，中国也不得不摆出一副“挟天下以令美国”的姿态，即，如果美国国会一意孤行、硬要打贸易战争的话，那中国只能奉陪，别无他法,只是整个世界的经济、包括美国、欧洲、恐怕也将因此画出一个“拐点”。

东方评论员认为，中国在人民币问题的极其强硬，本质上讲，与同意上海合作组织公开要求外国军队限期撤军一样，是在对美国“论证”“中国威胁论”的警告。

*** 华盛顿是未得“论证”“中国威胁论”之利、却已经品尝了“论证”“中国威胁论”之“弊”

在这一点上，朝核问题已经不为美国所控制、韩国出于自身利益、在中美对立间、有选择中国而居之的意图；中俄一致支持中亚诸国、并对美发出了“逐客令”，上海合作组织欲准备将美国的死敌-伊朗纳入自己体系之内等等，都说明华盛顿是未得“论证”“中国威胁论”之利、却已经品尝了“论证”“中国威胁论”之“弊”。


在东方评论员看来，一旦华盛顿将“中国威胁论”立为国策，必然遭到北京的全力反击，而这种反击对美国全球战略带来的冲击，从这次上海合作组织公开要将美国从中亚扫地出门、就可见一斑。显然，这次中俄一致、让“上海合作组织”公开地将政治矛头指向美国，根本就是拜美国近来炒起来的“中国威胁论”、对中国从政治、到军事、最后到经济的一番“穷追猛打”所赐。


*** 那份“难产”多次的“中国军力报告”再行推迟几周，根本就不令人意外

在这种变化下，东方评论员认为，美国五角大楼不得不将计划于本月发表的、那份“难产”多次的“中国军力报告”、以“需全面评估”的理由再行推迟几周，根本就不令人意外。

然而，首席评论员指出，不论华盛顿多么地谨慎，它以对中国总得有个“最后态度”，因此，在我们看来，如果几个星期之后，如果美国“不再推迟发表”，那么，那份“千呼万唤不出来”的“中国军力报告”总会告诉我们华盛顿决策层是如何定位中美关系的。



*** “天要下雨、娘要嫁人”，华盛顿如何选择，毕竟是华盛顿自己的事情

我们认为，如果美国人在慎之又慎后，仍然将中国威胁论“立为国策”、并加以身体力行的话，那么，类似中亚今天发生的这种、北京联手其它势力、“公开挑战美国利益”的事情，美国还会在东亚、中东、西亚遇到，甚至会在美国自家的后院--南美洲遇到。

东方评论员认为，一旦结局如此，我们无法预料中美之间具体会发生什么，但是可以肯定的是，就如双方如果开打贸易战争一样，其结果必然是中美双方的战略利益、都将受到极大的损害。

同样，还可以肯定的是，一旦华盛顿正式确立“中国威胁论”，并将其落实，那么，日本人梦想的、让中美先对立起来的战略目的也就算彻底达到了、对此，美国人是心知肚明的。然而，“天要下雨、娘要嫁人”，华盛顿几个星期后“如何选择”，毕竟是华盛顿自己的事情，我们只能是拭目以待。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
