# -*- org -*-

# Time-stamp: <2011-08-04 00:11:51 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 2005年6月16日 星期四

** 6月16日外交部发言人刘建超在例行记者会上答记者问（节简）

【北京消息】6月16日下午，外交部发言人刘建超主持例行记者会。下面是有关东亚部分的节简内容。

　　
问：1994年美国与朝鲜达成协议，朝鲜关闭宁边两座核反应堆。最近朝鲜政府对美国专家说，他们已经重新开启了核反应堆，中国政府对此有何评论？中国认为朝鲜是有核国家还是无核国家？第二个问题，据说美国国防部长可能在今年秋天访华，请问在中方看来访问能否实现？美国国防部长访华对中美两国有什么意义？

答：关于第一个问题，我们在这里已经多次讲过，中方对朝鲜方面的核开发情况并不了解。我们希望朝鲜半岛是一个无核武器的半岛，我们希望有关问题和各方的关切能够在六方会谈的框架内得到解决，疑惑也应该在这个框架内得以澄清。我们希望各方朝着这个方向作出积极的、建设性的努力。

关于第二个问题，中方重视同美方在军事领域开展交流，以增进相互之间的了解和互信。我们欢迎美国国防部官员包括拉姆斯菲尔德本人对中国进行访问，希望有关交流能够促进双方在军事及各领域的合作。

问：是否能介绍下个月印尼总统访华的情况？

答：中国和印尼是本地区两个有重要影响的国家，在各领域有着良好的合作，双方高层互访和交往也很频繁。高层领导人之间的互访和面对面的交流对促进双边关系非常重要，有着不可替代的作用。我们欢迎印尼总统苏希洛先生在方便的时候对中国进行访问。具体安排双方还在磋商。中方非常重视这次访问，将给予贵国总统热情友好的接待。

问：本周，国际动物福利保护组织致信中国外交部，要求中国不要支持日本扩大捕鲸的努力。该组织说，过去5年，中国在60项决议中的59项上支持了日本，这是否准确？中国自己并不捕鲸，为何要支持日本？另外，上周中国驻联合国官员说六方会谈几周内就能恢复，这是否能实现？

答：我想在这里向你介绍一下中国在捕鲸问题上的基本原则，这就是积极养护和合理利用，在充分科学依据的基础上，通过慎重研究和各国协商一致，有限制地利用鲸类资源。

关于第二个问题，尽早恢复六方会谈是有关各方以及国际社会的共同愿望。近来我们也注意到有关各方开展了有益的接触，包括美朝之间的接触。我们对有关进展感到高兴，希望有关各方继续作出切实的、建设性的努力，推动六方会谈尽早重开。至于何时召开，还没有一个时间表。

问：前两天，美国六方会谈谈判代表希尔说，中国为推动朝鲜重返六方会谈所作努力不足，你对此有何评论？

答：中方一直在为推动朝鲜半岛核问题的解决作出自己积极和艰苦的努力，这一点已得到国际社会的普遍认同。我们认为相互尊重是朝鲜半岛核问题六方会谈得以重新召开的重要基础，我们希望有关各方，特别是半岛核问题的主要当事方能够作出积极的、建设性的努力。

问：日本遗族会会长、自民党原干事长古贺诚本月11日表示，小泉首相在参拜靖国神社问题上应该考虑邻国的感情并寻求它们的理解，中方对此有何评论？是否可以将其看作是中国对日外交战略的成果？

答：中国对日本的外交战略或者说中国的对日政策是坚持“以史为鉴、面向未来”，致力于同日本发展世世代代友好下去的睦邻关系。这种长期友好对中日两国人民都是好事，有利于两国人民的实际利益。在日本领导人参拜靖国神社的问题上，日本国内也有各种意见。有些人士提出的有利于中日友好和改善中日关系的观点和主张，应该受到日本政府的重视。同时，我们也认为,日本领导人参拜靖国神社问题本身是原则问题，而不仅仅是感情问题。希望日本领导人切实认识到这个问题的高度敏感性和严重性，以实际行动取信于国际社会和亚洲邻国人民。

问：卢森堡外交大臣昨天接受新华社记者专访时，承认在解除对华军售禁令问题上面临着来自日本和美国的压力。有专家分析，由于欧盟下任轮值主席国是英国，而英国与美国之间又存在着极为密切的关系，对华军售禁令问题难以在年内得到解决，中方是否同意这一观点？

答：在解禁问题上，欧盟受到了一些没有道理和不必要的干扰。中国和欧盟之间解决这一问题并非针对第三方或任何其他国家，也不会损害他们的利益。有关国家在这个问题上予以阻挠是没有道理的，也是我们坚决反对的。欧方应该从中欧关系的大局出发，履行承诺，尽早解除对华军售禁令。这将对双方各领域关系的发展，特别对消除中欧关系发展过程中的重要障碍是有利的。

问：关于中日关系，最近一些中国媒体称，中国外交政策通过最近吴仪副总理的紧急回国而表现得比较主动，你对此有何评论？

答：中国的外交政策是基于中国人民的意志所制定的外交政策，换句话说，中国的外交是中国人民的外交，是为中国人民服务的外交，也是为维护世界和平，促进共同发展这个目标服务的外交。中国外交非常重要的出发点，是与世界各国在和平共处五项原则的基础上发展各个领域的合作。我们非常重视同我们的邻国发展睦邻友好关系。同日本发展世代友好的睦邻友好关系，也是我们的一个目标，我们也在朝着这个目标作出努力。但是，中日关系的改善和发展需要双方共同作出努力，特别是日方应本着“以史为鉴、面向未来”的原则，在历史和台湾问题上采取正确的态度。



【时事点评】显然，外交部发言人刘建超今天主持的这场例行记者会、不论是“问的问题”还是“回答的内容”，都集中在朝核问题上。

大家请注意这么一段，原文是：问：1994年美国与朝鲜达成协议，朝鲜关闭宁边两座核反应堆。最近朝鲜政府对美国专家说，他们已经重新开启了核反应堆，中国政府对此有何评论？中国认为朝鲜是有核国家还是无核国家？第二个问题，据说美国国防部长可能在今年秋天访华，请问在中方看来访问能否实现？美国国防部长访华对中美两国有什么意义？

答：关于第一个问题，我们在这里已经多次讲过，中方对朝鲜方面的核开发情况并不了解。我们希望朝鲜半岛是一个无核武器的半岛，我们希望有关问题和各方的关切能够在六方会谈的框架内得到解决，疑惑也应该在这个框架内得以澄清。我们希望各方朝着这个方向作出积极的、建设性的努力。

*** 刘建超在“揣着明白装糊涂”

在昨天的《东方时事解读》的朝鲜部分，我们再次分析了华盛顿的朝核政策，在我们看来，与一年前“六方会谈”中断时相比，华盛顿是“立场”没有变，对此，北京显然也是在“有样学样”，“原有立场”也是“不变”。

我们注意到，在回答“中国认为朝鲜是有核国家还是无核国家？”这个问题的时候，发言人刘建超只是简单地用了一句“中方对朝鲜方面的核开发情况并不了解”来加以“搪塞”，在东方评论员看来，最能体现北京“原有立场”不变的，恐怕就是刘建超这种“揣着明白装糊涂”的态度。

首席评论员指出，华盛顿在将“台独进程”推进到修宪这一步后，又在背后挑唆日本在钓鱼岛、东海闹事之余、还将台湾拉入“美日安保指针”的战略目标，在做完这一切之后，却还企图在台海方向只用一个“台湾在野党登陆”的代价、就立刻将台海稳定下来，这可是算得上是“将算盘顶在脑门上打”才“打算得出来的心机“了。

显然，北京在朝鲜宣布有核、而且还一再强调“正在制造更多的核武器”的时候，却“揣着明白装糊涂”，就是要“一口咬定”“对朝鲜方面的核开发情况并不了解”，这也算得上是“你打我一拳，我也要踢你一脚”。

*** 华盛顿为什么要死抱着“朝鲜必须先无条件废核、再谈其它”的“教条”不放？

东方评论员认为，华盛顿死抱着“朝鲜必须先无条件废核、再谈其它”的“教条”不放，这也不奇怪。我们知道，布什自5年前上台之后、可以说是“一点时间都不愿意拖延”、就立刻废弃了克林顿政府与朝鲜达成的“核框架协议”。

在我们看来，布什之所以如此的“迫不及待”，就是因为在随着布什上台、而准备大干一场的美国新保守主义“决策团队”的眼睛里、朝核问题与台湾问题一样，早已被“设计成为”确保“不要爆发”、但一定要“时时冒烟”的火山口。

*** 台湾和朝鲜“起着某种杠杆的作用”

在美国新保守主义精心策划的“气呑全球”的战略中，台湾和朝鲜“起着某种杠杆的作用”，通过“不时地拨弄一下台湾和朝鲜”、让东亚局势“或松或紧”、不仅是压迫中国和日本、韩国配合美国全球战略的最佳策略，也是“随时狙击”这些国家、特别是中国趁美国的“注意力”聚焦在中东的时候、在亚洲扩展势力的最好工具。


显然，除非朝鲜在“无条件地彻底解除核计划”之后、再行改组政权结构、从而成为一个无法稳定的、却又开在中国、俄罗斯身边的“民主之花”。而在华盛顿的“战略地图”中、一个“改造成了民主政权的”朝鲜、如果不听从华盛顿的安排、那么就必然会成为朝鲜半岛的动乱之源，成为将来“阻止”中国、日本、韩国、俄罗斯远东区域进行经济整合的“关键枢杻”。也正是有这一层战略企图，所以，在现阶段，除此之外的、“朝核问题的任何解决方式”都将“难入”华盛顿的“法眼”。


*** 拟定计划“新保守主义者”和执行计划的“传统保守主义者”之间爆发过“内讧”

然而，“时势比人强”。只是一年多来，华盛顿“不顺心的事情太多了”，华盛顿的新保守主义所拟定的全球战略、在第一步，也就是伊拉克问题上就“栽了个大跟头”，为此，负责拟定计划的美国“新保守主义者”和专职执行计划的美国“传统保守主义者”之间甚至爆发过“内讧”。

东方评论员注意到，其中最为激烈的一次，就是“新保守主义”的“旗手兼军师”--美国“旗帜周刊”的主编、就领衔发起过一轮“打倒”拉姆斯菲尔德的“运动”、他指责拉姆斯菲尔德---这位美国传统保守主义的代表人物、“没有执行好”既定战略、并要求这位“强硬的老头”立刻辞职。


在东方评论员看来，华盛顿全球战略在伊拉克的“受挫”，是典型的“出门就跌一跤”，可以说至今仍然没有爬起来，也难怪为此“准备了十几年”的新保守主义者“如此窝火”。然而，除了中东、另外在东亚、南亚的角力中，尽管美国人也“下了血本”，然而，结果仍然是“差强美意”。


*** 华盛顿在东亚的“不懈努力”也带来了“严重的后果”

在东方评论员看来，华盛顿在东亚的“不懈努力”也带来了严重的后果，我们认为，这种“严重后果”表现在这么几个地方，第一，华盛顿在台湾问题上用自己的“信用全无”、“赚”来了一个“反分裂国家法”。

第二，美日从一开始就各怀鬼胎，华盛顿在自己战略利益的考虑下，为了维护这个这个、对美国最有利、对日本最不利的亚洲安全框架、不可能立刻就钓鱼岛、东海划线等事关中国主权的问题上公开支持日本的立场，也是基于这种私心、华盛顿甚至不愿意将“中国威胁论”放进“美日安全指针”。

事实上，根据我们的观察，华盛顿这些脚踩“中、日两只船”的私心、已经引起日本国内政治势力的强烈反弹，开始要求小泉政府对“全面倒向美国”、只顾及美国利益、却损害日本、亚洲利益的外交政策“进行反省，只是以复活军国主义为已任的小泉政府、对华盛顿在钓鱼岛主权争端、“入常”、“核武装”等一系列重大问题上、在支持日本时始终表现得“三心二意”、是“敢怒不敢言”。

第三，在“朝核问题”已经被北京有目的地、深化成“东亚核竞赛”的压力下，为了防止日本政治人物、利用朝核问题大做文章、诱导并动员国内社会主动冲击核门槛，布什政府上台5年来、似乎“第一次有了”尽快稳定朝鲜半岛局势的紧迫感。


*** 韩国国内已经出现了对美国东亚政策不利的“政治张力”

第四，出于对朝核问题进一步恶化的担心，也出于对华盛顿“强硬朝核政策”的极度不满、更出于韩国急于落实以朝鲜为着力点、开拓市场、并进行产业配套的经济政策，韩国国内已经出现了对美国东亚政策不利的政治张力，在东方评论员看来，这种“政治张力”的“集中体现”，就在于两点：一个就是韩国公开禁止美国使用韩国军事基地介入可能的台海战争；而另一个则是韩国出现了一股“脱美亲中”的势头，而这一势头的“集中体现”，就在于韩国正在忙着与中国商量签订“自由贸易区”的事情。在东方评论员看来，此举表明，韩国似乎已经确定了其最大的经济利益、将来自北京这一边。


*** 曾经死去的“阳光政策”正在借“朝鲜半岛统一”而“还魂”

第五，也是华盛顿最为恼火的，那就是几年前、布什“亲手掐死了”韩国前总统金大钟提出的、着眼于强化“朝韩”双方经济联系的“阳光政策”、可现在，现任总统卢武铉不仅有意继续强化“朝韩”双方的经济联系、更是与朝鲜一道提出了“朝鲜半岛统一”的构想。

不难看出，曾经死去的“阳光政策”正在借“朝鲜半岛统一”而“还魂”。

*** 美国想立刻就“掐死”“卢武铉的政策”恐怕不那么容易

首席评论员指出，尽管我们不认为“朝鲜半岛和平统一”是个短期内就可以实现的事情，但是，这个由“韩朝”双方共同提出的构想，显然给华盛顿强硬派和韩国的亲美势力出了个难题，那就是，美国在“掐死”金大钟“阳光政策”的时候，其策略是先将“阳光政策”抺上是帮助了“邪恶的朝鲜政权”的色彩、从而得到来自韩国内部亲美政治势力的“公开的支持”。

然而，这一次，美国想立刻“掐死”“卢武铉的政策”恐怕不那么容易。

*** 几年前，布什何以要置“阳光政策”于死地而后快？

在东方评论员看来，布什政府之所以要置“阳光政策”于死地而后快，就是因为“阳光政策”的“灵魂”、在于通过强化“朝韩”双方经济联系，提提升朝鲜的经济水平、从而为韩国的经济找到一条新的出路，此外、在这一基础上，让朝鲜半岛南北差距逐渐缩小、从而慢慢走上统一。

前面说了，按美国的“设计”、朝鲜和台湾一样、是“不能爆发”而又“必须冒烟”的火山口。显然，不论是金大钟的“阳光政策”、还是卢武铉的“民族统一”、都犯了美国新保守主义拟定之全球战略的“大忌”。


有意思的是，恰好在韩国总统卢武铉访问美国之前，美国兰德公司公布了一份研究报告，为了更好地说明问题，我们将这份我们已经点评过的资源翻出来、并附在下面。在一起“回顾”几个数据之后，东方评论员将继续这个话题，看看兰德公司在美国的战略策划中，起着一种什么作用。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 【资料】兰德公司报告称:朝鲜半岛统一需费6700亿美元

【东方档字NO.200506050274】据韩国联合通讯社报道，美国兰德公司日前发表一份报告，称朝鲜半岛如果真正实现统一，需要耗费6700亿美元。

兰德公司近日在其网站上公布了向美国国防部长办公室提交的一份报告，报告称，“朝鲜半岛实现统一需要花费的资金，主要取决于朝韩两国统一的方式，另外包括实现国内稳定、人力培训、安置及社会整合等方面”。

兰德公司称，“通过模拟分析，我们得出结论认为，以2003年的购买力计算，朝鲜半岛最终统一需要花费500亿到6700亿美元”。兰德公司称，他们的统计数据主要是根据三种假设来进行计算的，这三种假设分别是：通过制度演变实现统一、一国崩溃实现统一及通过战争实现统一。

兰德公司在报告中称，“令人难以置信的是，朝鲜半岛的统一，将比德国统一耗费更多的物质资源。这主要是因为，与前东德、西德相比，朝鲜与韩国的经济差距更大，其人口差距也更为明显”

该报告称，朝鲜的人均国内生产总值只有韩国的6%至12%，而1990年东西德实现合并时，东德的人均国内生产总值是西德的25%至33%。



【时事点评】我们之所以将这份已经点评了的“旧闻”摆出来，就是想让大家明白，兰德公司说起来是个“享有盛名”的民间研究机构，然而，我们有太多的证据去证明、兰德的许多研究报告（当然不是全部），从内容到形式、在美国政府众多的“战略欺骗”中、都扮演着一个非常关键的角色。


*** 报告似乎是为配合“卢武铉9日访美”而“量身订做”的

就这份报告而言，就如我们在6月6日《东方时事解读》中所分析的那样，其“数据”与“假设”、与其说是“科学分析”、“合理假设”，都不如说是为了配合“卢武铉9日访美”而“量身订做”的来得准确。


*** 卢武铉此次前来见布什，比金大钟那次见布什时、心里要“硬气得多”

非常清楚，卢武铉到美国去，就是要谈“朝鲜半岛的统一问题”。在东方评论员看来，尽管布什与卢武铉一样清楚，“朝鲜半岛的统一”绝对卢武铉要与朝鲜加强经济联系的“借口”，但是，就目前而言，由于韩国国内有股“脱美亲中”的潮流、这使得卢武铉此次前来见布什，比金大钟那次见布什时、心里要“硬气得多”。

事实上，时事评论员们至今大都清楚的记得，当时的布什是如何蛮横地当着金大钟的面，否决“阳光计划”的。


*** 华盛顿就是想“一口咬死”、也是一时“无法直接下口”

显然，就结果而言，在东方评论员看来，在布什面对卢武铉发出威胁、称“美军可能从韩国全面撤军”之后，仍然没有能压服卢武铉，这就使得华盛顿的朝核政策，必须面对卢武铉已经扯起了“民族统一”这面大旗之“现实”。

首席评论员指出，这一次，卢武铉实际上是将已经死掉的“阳光政策”的“灵魂”，塞在了“朝鲜半岛和平统一”的口号下，因此，华盛顿就是想“一口咬死”、但面对这个顺乎民意的“民族统一”，也是一时“无法直接下口”。


*** “好雨知时节”的兰德报告

因此，在我们看来，兰德的这份“数据详尽”、“结论明确”的研究报告，对华盛顿而言，实在是有点“好雨知时节”的味道在其中。不难看出，按报告的说法，朝鲜半岛的统一远比德国的统一来得麻烦，因此当年的东西德经济、文化水平的差距远比现在的“朝韩”之间来得小，因此，可以肯定，德国为统一付出的巨额代价，足以让韩国人“心有余悸”。

但是，东方评论员注意到，有国际问题专家已经点破了其中的“玄机”，既，兰德公司分析出来的“朝鲜半岛最终统一需要花费500亿到6700亿美元”这一结论，今后很可能将成为韩国内部亲美势力给卢武铉借“统一”、搞“朝韩”经济整合之政策“埋钉子”、“下乱药”的理论依据；

也就是说，德国为统一付出的代价过于巨大之“事实”，以及兰德公司在报告中所称的“朝鲜半岛的统一，将比德国统一耗费更多的物质资源”之结论，已经为韩国的亲美势力“反对”卢武铉的朝鲜政策、“提供了完美的理论依据”。在我们看来，如果“6700亿美元”这个天文数字“真实可信”的话，，那么，韩国的任何一位傻瓜都看得出来，韩国政府掏不出这笔钱。


*** 韩国在玩“明修栈道（南北统一）、暗渡陈仓（经济整合）”的把戏

当然了，东方评论员认为，不论是卢武铉、还是布什，恐怕没有谁真正相信朝鲜半岛几年内就能统一的。然而，不论是卢武铉、还是布什，心中也都清楚，韩国在这个时候扯起“民族统一”的大旗，不过是在玩“明修栈道（南北统一）、暗渡陈仓（经济整合）”的把戏。


*** 北京也在等着“这一出”

对华盛顿决策层而言，真正的麻烦不是韩国，而是北京。事实上，北京也在等着“这一出”。目前，以担心“制裁会导致朝鲜的经济崩溃、从而将会让大批难民涌入中国境内”为由头，中国不仅一直在拒绝“对朝鲜实施经济制裁”、反而在向朝鲜加大投资，说好听点，这是在帮朝鲜“造血”，说直白点，这显然是在抢占商业先机。

这还不算，北京还拒绝加入由美国牵头的，有60多个国家参加的旨在阻止交易危机武器和原料的“防扩散安全倡议”。而韩国也拒绝加入这个“防扩散安全倡议”，众所周知，这个所谓的“防扩散安全倡议”、如果用在朝鲜身上，其主要目的就是要对任何驶往朝鲜的运输工具进行随意检查、扣押、从而实现对朝鲜的全面制裁。

显然，韩国不仅在加入“防扩散安全倡议”的问题上与中国看齐，同时，汉城也在象北京那样，正在加大对朝鲜的投资。在东方评论员看来，北京似乎已经成功地催动了心仪已久的“东北亚经济一体化”。


*** 华盛顿能不着急上火吗？

前面说了，对朝核问题，布什政府的意图非常清楚，说白了，那就是“不想解决朝核问题，而只想稳定朝核问题、只想用各种手段让朝鲜陷入经济困难、直至投降”。然而，在中国和韩国的“这些具体措施”下，朝鲜不仅不会就范，反而会活得更好，华盛顿能不着急上火吗？

另外，在昨天的点评中，我们已经分析了，日本在按美国的旨意，于3月份就开始对朝鲜进行经济制裁了。而同样按日本内部的估计，由于中日间与朝鲜的经济往来的规模差距已经很大了，长久下去，日本担心对朝鲜的经济影响力将迅速消失。

*** 被“诱骗出局”的日本，心里又做何感想呢？

因此，向来眼谗朝鲜资源与地理位置的日本、在眼看着中国、韩国加紧投资朝鲜的时候，当初被美国抛出的“韩国核问题”这颗“核胡萝卜”从“朝鲜经济改革进程“中诱骗出局的日本、心里又做何感想呢？

东方评论员认为，如果中国和韩国一道，“坚决排除掉”以“军事打击”、“经济制裁”这两条途径“逼迫朝鲜就范”的可能性，而华盛顿又拿不出其它的“好办法”来阻止朝鲜进行经济改革的话，也拿不出够份量的“胡萝卜”继续诱惑日本的话，那么，日本是有可能“愿意相信”“帮助朝鲜发展经济”、加入、并促进“东北亚经济一体化”的方法才是“彻底解决朝核问题”的“唯一出路”的、也有可能再次尝试通过加入朝鲜经济改革、寻找主导“东北亚经济一体化”、继而主导东亚经济一体化的机会的，当然，这不是一天两天的事情。

*** 华盛顿一定会“竭尽全力”去破坏“东北亚经济一体化”的

只是面对“这一可能性”，华盛顿能不着急吗？事实上，在东方评论员看来，美国人这次的确着急了，因此，也一定会“竭尽全力”去破坏北京最想得到的“东北亚经济一体化”。下面是一段来自华盛顿的消息，一起阅读之后，我们将继续今天的朝鲜话题、简单谈谈华盛顿可能在哪两个方面给北京“下乱药”。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
