# -*- org -*-

# Time-stamp: <2011-08-02 20:04:36 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

#+STARTUP: indent

* 2005年03月24日 星期四

** 2005年3月24日外交部发言人刘建超在例行记者会上答记者问（节选）

【外交部网站消息】3月24日下午，外交部发言人刘建超主持例行记者会。

问：有些报道称美方认为今年六月是六方会谈复谈的最后期限，朝鲜总理朴凤柱访华期间，双方有没有提到这一问题？在核问题上朝方有何回应？通过朴总理此次访华，中方是否感觉六方会谈能在近期恢复？
 
答：在朝鲜总理朴凤柱访问中国期间，中国领导人同他就朝鲜半岛核问题深入交换了意见。中方阐述了在朝鲜半岛核问题上的立场，也向他通报了最近中国同有关国家，包括美国在朝鲜核问题上进行磋商的情况以及各方的观点。朴凤柱总理非常重视中方的看法，也重视中方通报的情况。他表示朝方对中方为实现半岛无核化、维护朝鲜半岛的和平与稳定所作的重要努力表示赞赏。同时他也指出，朝方实现半岛无核化、通过对话和平解决核问题的立场没有变化，朝方将继续为实现这一目标作出努力。他也重申，朝方不反对六方会谈，也没有放弃六方会谈，今后会谈条件成熟时，朝方愿随时参加六方会谈。从这次访问来看，在恢复六方会谈进程问题上没有取得突破性的进展。但我相信有关会谈和意见交换对六方会谈的进程是有益的。目前在恢复六方会谈上有关各方，特别是主要当事方朝鲜和美国还存在着很大的分歧，这些分歧对六方会谈的恢复造成了一些障碍，主要症结是双方还存在着很深的不信任，缺乏必要的良性互动。我们希望有关各方在保持耐心与克制的同时，多做有助于增信释疑的事情，共同为早日复谈做出建设性的努力。
 
　　
问：据报道，朝鲜总理朴凤柱此次访华期间，邀请胡锦涛主席访问朝鲜继续谈六方会谈问题，请证实。美国希望朝鲜完全拆除核武器，而朝鲜方面则只表示愿意暂停相关活动。请问中方对此有何评论？
 
答：朴凤柱总理访华期间曾代表金正日总书记对胡锦涛主席发出邀请，邀请胡主席在方便的时候对朝鲜进行访问。胡主席对邀请表示感谢。中朝双方都高度重视高层互访。


关于你的第二个问题，在朝鲜半岛核问题上目前美朝双方还存在分歧，比如朝鲜对美国的对朝政策还持有怀疑，希望美方收回“暴政前哨”的说法，放弃对朝敌意等。同时，美方也在怀疑朝方是否真正愿意放弃核武器。回顾已举行的前三轮六方会谈，我们可以看到，当时各方达成的一个重要共识就是各方都同意以协调一致的步骤通过“口头对口头，行动对行动”，来推进朝核六方会谈进程，而其中的第一步就是要冻结核计划。这一步骤由于六方会谈没能顺利进行还没有取得进展。我们希望各方从朝鲜半岛无核化、朝鲜半岛和平与稳定的大局出发，拿出诚意、显示灵活，尽快恢复朝鲜半岛核问题的六方会谈。


问：中国在日本争取成为联合国安理会常任理事国问题上的立场是什么？请问中国将如何与美国常驻联合国代表博尔顿进行合作？中国是世界银行贷款的最大接受国之一，在世行将如何与可能的下任世行行长沃尔福威茨进行合作？
 
答：关于第一个问题，我在星期二的记者会上已经阐明了中方的立场。中方支持联合国安理会的改革，改革的关键是要优先增加发展中国家的代表性，增强联合国安理会应对新威胁和挑战的能力，提高其工作效率。安理会改革事关重大，应该由联合国各会员国在充分协商的基础上，达成广泛一致。
 
关于第二个问题，关于博尔顿先生被任命为美国驻联合国代表的问题，中美双方在联合国框架内进行了良好的磋商与合作，我们希望双方继续在联合国进行有效的磋商与合作。
 
　　
问：据报道，日本冲绳县石垣市议员拟于今年6月向市议会提议制定所谓“尖阁列岛日”条例。请问中方对此有何评论？
 
答：我们对此表示严重关切，并已通过外交渠道向日方表明了严正立场。我在此重申，钓鱼岛及其附属岛屿自古以来就是中国的领土，中国对此拥有无可争辩的历史和法律依据。日方对钓鱼岛采取任何单方面行动，都是对中国领土主权的严重侵犯，都是非法的、无效的，中方坚决反对。
 
问：美国表示支持日本加入联合国常任理事国。中方对日成为常任理事国持何立场？
 
答：我们理解日方希望在国际事务中发挥更大作用的愿望。我们同时也希望日方能在历史问题上采取正确的负责任的态度。你也注意到，最近中国的公众对日方成为联合国安理会常任理事国评论很多。我们希望日方在历史问题上采取正确的态度，以取信于人。
 
问：北朝鲜总理说如果条件成熟，他愿意随时重返六方会谈。我的问题是如果条件永远无法成熟，中国是否考虑采取其他方式解决朝核问题？中国至今看起来仍很有耐心，但是，你们的耐心是不是有限度的？你们是否同其他各方在工作层面就此进行过讨论？如果六方会谈没有能够如期进行的话，还有没有其他的方式？
 
答：各方现在正为尽早恢复旨在解决朝鲜半岛核问题的六方会谈进行努力。六方会谈是解决朝鲜半岛核问题的一个切实可行的、现实的最佳途径。有关各方都应该表现出足够的耐心，表现出善意，拿出政治智慧和勇气，为早日恢复六方会谈创造必要的气氛和条件。至于耐心的问题，从朝鲜半岛核问题一发生，包括中国在内的各方都认识到这是个艰巨的问题，不可能一蹴而就。解决这样一个极其复杂的问题需要各方的耐心和努力，也需要有思想上的准备，这个问题的解决将是一个比较长期的过程。尽管如此，各方应朝着尽可能早地解决这个问题的方向努力。这就要求各方拿出诚意，体现出灵活，特别是直接当事方应尽更大的努力。
 
 
问：据昨天的报道，美方为恢复六方会谈设定的期限是6月底，美方对中方有何表示？中方对所谓的期限持何态度？
 
答：我还没有听到有关期限的说法，美方也没有向我们提出所谓的期限。大家共同的愿望是希望六方会谈能够尽早地恢复。希望各方为恢复六方会谈创造气氛和条件。
 
问：中国政府认为在东海中国与日本有争议的区域存在多少石油和天然气？中国是否满意日本给予中国参与世博会的签证数？
 
答：我无法预测也无法回答东海的油气蕴藏量有多大。在东海划界的问题上我们主张“搁置争议，共同开发”，逐步解决存在的分歧。
 
世博会是世界各国展示自我、加强交流与合作的盛会。中方非常重视，将以积极的态度参加此次世博会的有关活动。我们祝愿世博会取得成功，我们也希望日方为中方参与世博会的有关活动提供方便。
 
问：朝鲜总理说，如果条件成熟，他们愿意重返六方会谈。何谓成熟的条件？能不能说得更清楚一点？
 
答：朝方在其外务省“2·10”声明以及后来的一系列表态中已表明朝方需要何种名分和条件，才会重新参与六方会谈，所以我们也希望其要求能够得到有关方面的重视。我们更希望有关各方都能够释放善意，拿出诚意，采取灵活态度。
 
问：中方优先支持发展中国家在联合国安理会的代表性。中方是否可能就此使用否决权？德国国际人权协会发表一个向台湾人民问候的公开信。信中指出《反分裂国家法》是针对台湾的战争法，要求中国无条件收回。中方有何看法？

答：我已多次重申，中国支持联合国安理会改革。我们希望改革应该在协商一致的基础上，通过民主协商达成广泛一致。关于联合国安理会常任理事国的否决权问题，建议你回去做做家庭作业，看看否决权是如何行使的。
 
关于你的第二个问题，我还是第一次听到这个消息。如果你所谈的情况属实，那说明你提到的这个组织根本不了解《反分裂国家法》。它在信中所阐述的观点是颠倒黑白的，完全是由于没有对《反分裂国家法》进行认真研究而得出的错误结论。我们对立法宗旨已经做了很明确的阐述，希望他们认真研究，正确认识这部法律。
 
问：前天，温总理与朴总理会见时，签订了两个协定，分别关于环境和投资，请介绍一下具体的条文或协定内容？
 
答：正如你所说，在温家宝总理同朴凤柱总理会谈后，双方签署了两个文件，一个是关于促进和保护投资的协定，另一个是环境保护的合作协定。很抱歉，我没有看到具体内容，所以没有办法向你介绍。但我想从题目中你也可以看出是两份什么样的协定。
 
 
问：在各大网站，上百万网民签名反对日本成为安理会常任理事国，您对这种民间反日情绪有何看法？
 
答：我不认为这是一种反日情绪，相反是要求日方在历史问题上采取正确的、负责任的态度。至于中国政府在联合国安理会改革的立场，我已多次阐明。
 
问：中国是否满意日方给予中国参加世博会的签证数目？
 
答：我还不了解日本给中方参加世博会的签证的数目，可以帮助你了解一下。如果有必要的话，我们会要求日方作为东道主给我们提供更多的方便。
 
问：关于六方会谈你谈到希望朝鲜和美国多做一些增信释疑的事情。此次中方在与赖斯和朴凤柱分别的会谈中，除通报情况和交换看法之外，中方是否提出建议？据悉，李部长在与赖斯的交谈中曾建议美朝可以先举行双边对话，请证实。
 
答：中方在与赖斯国务卿及朴凤柱总理会晤时都谈到了朝鲜半岛核问题，并作出了劝和促谈的努力。中方也希望美方能同意以适当的形式进行美朝之间的直接接触。美方也表示愿在六方会谈的框架内同朝鲜进行接触。
 
问：朴凤柱总理参观了上海、沈阳以及鞍山的工农业项目。他是否将从中国学习经济改革方面的经验？
 
答：此次朴总理访华的日程安排是双方经过外交磋商确定的。我们充分考虑了朝鲜客人的要求。在此次会见过程中，朴凤柱总理也多次表示，朝方愿意借鉴中国在改革开放和现代化建设方面的经验，希望能在中国多走一走，看一看。我们据此安排了他的日程，希望他能够满意。
 
问：赖斯国务卿来访期间，中美就《反分裂国家法》做了怎样的磋商？《反分裂国家法》中提到要以非和平方式解决台海问题，中美磋商中是否涉及将以何种方式使台湾回归祖国？中美之间是否有热线？
 
答：在赖斯国务卿访华期间，中美双方就《反分裂国家法》问题交换了意见。中方向赖斯国务卿详细地介绍了立法的宗旨和有关考虑，表示，《反分裂国家法》规定国家在一定的条件下，采取非和平方式及其必要措施维护国家主权和领土完整。但这是在争取国家和平统一，制止国家分裂的努力及可能性完全丧失的情况下迫不得已做出的最后的选择。这也是任何一个主权国家都必须采取的立场。这也从另一个角度说明《反分裂国家法》是一部维护台海地区和平与稳定的法律，是一部反对和遏制“台独”的法律，也是一部有利于本地区和平与稳定的法律。我们“和平统一、一国两制”的主张没有变。我们希望美方能够正确认识和理解这部法律的宗旨。总之，这是一部和平的法律而非战争的法律，更不是战争动员令。
 
中美两国领导人及外交部之间经常通过电话进行沟通和联系。双方就一系列问题进行过交谈。联系渠道是畅通的。
 
问：在欧盟解除对华军售禁令问题上，中方是否有具体措施来促成此事？
 
答：中方已经向欧盟多次阐述了要求欧盟解除对华军售禁令的立场。中方主要着眼于中国与欧盟现有的战略合作伙伴关系。在这样一种关系的大前提下，维持政治歧视是不合时宜的，也不利于中欧关系正常发展。中方立场欧盟应该清楚，我们希望欧盟早日做出正确决策。
 
 
 
 
 
【时事点评】通观刘建超的答记者问，媒体最关心的还是朝核问题。只是在昨天的《东方时事解读》中，我们曾经对日本外交部门向外面散发消息、称美国订下“今年六月底”为最后的限期一事，在东方评论员看来，由于朝核问题已经“极其敏感”、而“期限一说”也就“事关重大”。因此，在昨天、我们已经针对“日本单方面放出消息、在美国方面却无从考证”这点、提出过自己的疑问。
 

*** 赖斯在北京的时候、“是否”也当着中国领导人的面“的确”提出过“6月期限”一说？

在我们看来，除了日本人泄露出来的这则消息给了个“6月期限”之外，我们并没有发现美国人提及过“6月”这个时间，然而，这个期限为什么是“6月底”、而不是其它什么的时间？

对此，我们注意到，有分析人士表示，或许是因为最后一次“六方会谈”是在去年的6月份，因此美日将期限“定在一周年”的时候也非常自然。

然而， 在东方评论员看来，这种观点过于“牵强”，但是“原因是否如此”并不重要，重要的是赖斯在北京的时候、“是否”也当着中国领导人的面“的确”提出过“6月期限”一说？
 
 
*** 日本在美国人面前底气仍然不足

就如我们昨天点评中所说的那样，如果日本所言的“6月期限”是美日间达成的“君子协定”期限的话，那么，我们很可能看到的结果是：在今后几个月里，日本将会停止出于“核武梦”、快速成为“正常国家”的目的、去进一步刺激韩国、刺激朝鲜的做法，而转以配合美国的、急欲稳定朝核局势的新“朝核政策”。

此外，在东方评论员看来，如果赖斯在北京当着中国领导人的面“的确”提出了“6月期限”一说，那么，可以肯定的是，华盛顿感受到的、来自日本的压力非常之巨大，然而，如果赖斯在北京根本就没有提出这一期限，而是日本人在那里“任意解读”，如果属于后者、那就说明尽管日本不顾美国的感受、在东亚闹得凶，但在美国人面前底气仍然不足，并不敢利用华盛顿有求于已的战略机会，去主动地对美国的对外政策“指手划脚”。
 

*** 日本外交部所言的“6月期限”根本就是在那里“自说自话”

有意思的是，在今天的记者会上，外交部发言人刘建超碰巧也回答了一个类似的问题。请大家看这一段，原文是：

问：据昨天的报道，美方为恢复六方会谈设定的期限是6月底，美方对中方有何表示？中方对所谓的期限持何态度？

答：我还没有听到有关期限的说法，美方也没有向我们提出所谓的期限。大家共同的愿望是希望六方会谈能够尽早地恢复。希望各方为恢复六方会谈创造气氛和条件。
 
显然，从刘建超的表态中，我们可以清楚地看出，由于赖斯在北京并没有当着中国领导人的面“提及”这一期限，因此，日本所言的“6月期限”根本就是在那里“自说自话”。
 
如果嫌刘建超说的话“还不够清楚”的话，那么，我们不妨来看看美国总统在一次正式表态中、是如何肯定或否定的。
 
《东方时代环球时事解读》http://www.dongfangtime.com

** 布什否认为六方会谈设最后期限

【华盛顿消息】美国总统布什今天对朝鲜领导人金正日发出迄今为止最为直接的呼吁，要求金正日为了远东地区的和平与稳定倾听国际社会的呼声。布什并表示对中国国家主席胡锦涛，以及中国政府其他官员最近在朝核问题上的表态感到“欣慰”。
 
布什23日与加拿大总理马丁和墨西哥总统福克斯在德州克劳福德举行为期一天的峰会。在回答媒体有关朝核问题的提问时，布什说他刚刚听取了国务卿赖斯东亚之行的简报，美国在解决朝核问题上并没有设定时间表。布什说他是一个有耐心的人，然而他仍然忍不住直接向朝鲜领导人金正日喊话。
 
布什：“（在朝核问题上）有一个办法可以取得进展。我重复一遍，对于（朝鲜领导人）金正日，这是他要做出的选择。我们已经做出了我们的选择。中国已经做出了他们的选择。其他（参加六方会谈）的国家已经做出了他们的选择。为了远东的和平，宁静和稳定，金正日必须倾听（我们的呼声）。”
 
布什说，他对中国高层领导人最近在朝核问题上的表态感到“欣慰”。
 
布什：“我感到很欣慰，今天（中国国家主席）胡锦涛和中国政府在这个（朝核）问题上表达了持续的关切，并且表达了对其重要性的理解。”
 
三国首脑在23日发表了关于建立“北美安全与繁荣伙伴关系”的共同声明，其中的一项重要内容是联手应对亚洲经济体带来的竞争。
 
据了解，北美三国新建立的伙伴关系在加强反恐，边境检查，及开放贸易等方面采取众多新的措施。有白宫官员表示，三国希望建成世界上最强劲的安全和经济联盟，在能源和贸易方面应对主要来自中国和欧盟的挑战。
 
 
 
 
【时事点评】我们注意到，布什的这番言论、是他听取了刚从北京返回的赖斯所做“简报”之后，公开发出的。


*** 美国总统亲自跑出来“辟谣”

显然，美国总统在这个时候明确地表示“解决朝核问题上并没有设定时间表”，并标榜自己“是一个有耐心的人”，本质就是在亲自跑出来“辟谣”，在东方评论员看来，这从侧面也足以说明日本抛出的那个看似不起眼的“6月期限”、其性质是很严重的。
 
 
*** 昨天我们提出一个假设也就不成立了

如此一来，在昨天我们提出一个假设，即：如果日本所言的“6月期限”是美日间达成的“君子协定”的话，那么，今后几个月里，日本很可能就会停止去进一步刺激韩国、刺激朝鲜的做法，以配合美国急欲稳定朝核局势的“新朝核政策”、也就不成立了。

首席评论员则认为，在赖斯并没有在北京将日本人提出的“期限”说当成“自己的条件”之后，特别是在日本单方面“散布谣言”、最后弄得布什也亲自出来要公开否认“有此一说”之后，我们似乎有理由认为，美国的日本之间也许又生出了什么“龌龊”。在东方评论员看来，以我们的经验，美国的日本之间如果真又生出了什么“龌龊”、那也一定是中美之间、在北京已经“谈妥了什么”、而华盛顿和日本之间、在东京仍然有什么事情“没有谈妥”。
 
 
*** 中国领导人“只是在做自己愿意做的事情”、并没有布什“所夸得那样好”

此外，东方评论员注意到，布什说，他对中国高层领导人最近在朝核问题上的表态感到“欣慰”。然而，从刘建超在今天记者招待会上的相关表态来看，中国领导人在朝核问题上“只是在做自己愿意做的事情”、明显与布什的“欣慰”不符、并没有布什“所夸得那样好”。

 请大家注意这两段，原文是：

问：据报道，朝鲜总理朴凤柱此次访华期间，邀请胡锦涛主席访问朝鲜继续谈六方会谈问题，请证实。美国希望朝鲜完全拆除核武器，而朝鲜方面则只表示愿意暂停相关活动。请问中方对此有何评论？

答：朴凤柱总理访华期间曾代表金正日总书记对胡锦涛主席发出邀请，邀请胡主席在方便的时候对朝鲜进行访问。胡主席对邀请表示感谢。中朝双方都高度重视高层互访。

关于你的第二个问题，在朝鲜半岛核问题上目前美朝双方还存在分歧，比如朝鲜对美国的对朝政策还持有怀疑，希望美方收回“暴政前哨”的说法，放弃对朝敌意等。同时，美方也在怀疑朝方是否真正愿意放弃核武器。回顾已举行的前三轮六方会谈，我们可以看到，当时各方达成的一个重要共识就是各方都同意以协调一致的步骤通过“口头对口头，行动对行动”，来推进朝核六方会谈进程，而其中的第一步就是要冻结核计划。这一步骤由于六方会谈没能顺利进行还没有取得进展。我们希望各方从朝鲜半岛无核化、朝鲜半岛和平与稳定的大局出发，拿出诚意、显示灵活，尽快恢复朝鲜半岛核问题的六方会谈。
 

问：朝鲜总理说，如果条件成熟，他们愿意重返六方会谈。何谓成熟的条件？能不能说得更清楚一点？

答：朝方在其外务省“2·10”声明以及后来的一系列表态中已表明朝方需要何种名分和条件，才会重新参与六方会谈，所以我们也希望其要求能够得到有关方面的重视。我们更希望有关各方都能够释放善意，拿出诚意，采取灵活态度。
 
 
*** 刘建超只是说“胡主席对邀请表示感谢”，却并没有说“接受邀请”

显然，刘建超的这一番话，有几个重点，第一，刘建超肯定了“金正日总书记对胡锦涛主席发出邀请，邀请胡主席在方便的时候对朝鲜进行访问”这条消息，然而，值得注意的是，刘建超只是说“胡主席对邀请表示感谢”，并没有说“接受邀请”，显然，在东方评论员看来，这是在“避嫌”，防止别有用心的人将此“上纲上线”、去指责北京在华盛顿带来一份有“建设性的建议”之后，仍然在“强硬地”支持朝鲜的立场。

在东方评论员看来，北京公开保护着朝鲜是个不争的事实，然而，如何保护得“巧妙和高效”，却是个很有技巧的问题。我们注意到，刘建超在回答记者的问题时，一方面通过不说明是否“接受邀请”来“避嫌”，另一方面，还通过表明“中朝双方都高度重视高层互访”这一态度、来“宣扬”北京和平壤“也的确”对“赖斯带来的建设性建议”进行过“认真的考虑和研究”。


*** 中国在“朝核问题”上、是在刻意保持一种中间人的角色

只是经过“认真的研究和考虑”之后，“在恢复六方会谈进程问题上没有取得突破性的进展”，其原因就非常清楚了，我们认为、北京显然是在认为“与中国的立场无关”，在东方评论员看来，中国外交部正是通过刘建超在回答问题时，以罗列清单的方式，来“充分证明”朝鲜和美国之间的立场还“有待磨合”的。

不难看出，中国在“朝核问题”上、是在刻意保持一种中间人的角色，在我们看来，保持“中间人”所特有的灵活、将极大地丰富中国借美国之手、去打压日本的手段。
 
 
*** 北京在罗列这“朝美间”的“争议”的时候，显然没有包含“朝鲜宣布有核”这一事实

根据我们的观察，刘建超在发言中罗列了朝鲜早已提出的要求，比如希望美方收回“暴政前哨”的说法，放弃对朝敌意等、与此同时，刘建超也着重提到了“各方之前所达成的一个重要共识”，那就是各方都同意以协调一致的步骤通过“口头对口头，行动对行动”，来推进朝核六方会谈进程，而其中的第一步就是要冻结核计划。
 
在我们看来，北京在罗列这些“争议”的时候，显然没有包含“朝鲜宣布有核”这一事实，我们认为，这与朝鲜于2月10日宣布有核，而中国外交部发言人孔泉于一个星期之后公开强调“半岛核问题应该从现有基础”上解决的立场是一脉相承的。


*** 刘建超的意思就是在“建议”有关方面“忘掉朝鲜宣布有核”这件事

东方评论员认为，孔泉所说的“现有基础”指的就是“朝鲜宣称已经有了核武器”这个“现有基础”。现在，时间已经过了一个月，刘建超今天虽然没有重提“现有基础”这几个字，但是，字里行间，刘建超将中国政府的这一立场也是非常清楚表达了出来：在我们看来，刘建超的意思是在“提醒方方面面注意”、应该立足于“朝鲜已经宣布有核的事实”，从而根本上就是在“建议”有关方面“忘掉朝鲜宣布有核”这件事，继续回到以前达成的共识之基础上，通过“口头对口头，行动对行动”的方式去解决“半岛核问题”。
 
 
*** “朝核问题”是个和“台湾问题”一样、也是个“极其复杂的问题”
 
此外，刘建超的发言中，还有一点值得一提，他与布什一样，不约而同地说到了“耐心”的问题，原文是：“至于耐心的问题，从朝鲜半岛核问题一发生，包括中国在内的各方都认识到这是个艰巨的问题，不可能一蹴而就。解决这样一个极其复杂的问题需要各方的耐心和努力，也需要有思想上的准备，这个问题的解决将是一个比较长期的过程。”
 
显然，在东方评论员看来，如果中国领导人让赖斯“捎上一句话”，将“朝核问题”是个和“台湾问题”一样、也是个“极其复杂的问题”这类的话捎回美国、捎给布什，那么，布什在听完赖斯的亚洲之行“简报”后、在日本单方面宣布“6月期限”几天之后，才突然大谈“美国在解决朝核问题上并没有设定时间表”、并自夸“是个有耐心的人”，那就“非常符合中美角力、但又互有所求的逻辑”了。
 
 
*** 我们应该重视这次布什的讲话
 
首席评论员认为，我们应该重视这次布什的讲话，在我们看来，布什在赖斯回去之后、直接向朝鲜领导人金正日“喊话”、这也许是中美在“朝核问题”上有了默契的一种信号，但是否如此，还待进一步地观察。
 
 
*** 对北京的“建议”，华盛顿恐怕是“有意暂时妥协”，日本则根本就“无法接受”
 
我们的初步判断是，对北京的“忘掉朝鲜宣布有核”、而直接“回过各方过去达成的共识”这种“建议”、急于将朝核问题稳住的华盛顿恐怕是“有意暂时妥协”、而拼命想将朝核问题搞大的、将东亚政治局势搞乱、以便乱中取利的日本、则根本就“无法接受”。

在我们看来，如果从这个角度去看“美日”之间在所谓的“6月期限”问题上“各拿一把号、各吹各的调”，那就一点也不奇怪了。
 
 
*** 只要不早早地就正式声明“将否决日本”，那么任何公开、或暗中“反对工作”，都是可取的
 
另外，刘建超的讲话中，再次谈到了日本想成为常任理事国的问题。值得注意的是，刘建超认为“上百万网民签名反对日本成为安理会常任理事国”不是一种反日情绪，相反是要求日方在历史问题上采取正确的、负责任的态度。
 
首席评论员指出，我们赞同政府的这一观点和立场，在这里，我们也呼吁大家积极参加到这一活动中来，为营造一种那民间舆论声势、尽到自己这一份责任。

另外，在我们看来，北京的立场可以更加鲜明一点（下面再展开）。就如我们昨天所说的那样，中国肯定会找日本的一些麻烦的。我们认为，在联合国正式投票之前，“只要不早早地就正式声明”“将否决日本”，那么任何公开、或暗中、官方和民间的“反对工作”，都是可以考虑的。

 
*** 日本要想单纯地去满世界里“拉票”、是要耗费巨大的政治资源、经济资源的。
 
在我们看来，日本不是发起了一场声势浩大的“拉票”运动吗？好得很，我们知道，联合国相关的章程是：联合国五个常任理事国不能有一个否决票，联合国成员国要有2/3以上的国家表决通过才行。 因此，日本要想单纯地去满世界里“拉票”、是要耗费巨大的政治资源、经济资源的。
 
东方评论员认为，中国作为亚洲唯一有否决权的常任理事国，也是遭受日本侵略受害最深的国家，许多也遭受侵略的东南亚国家、由于自身力量不足、它们也只能是看着中国如何动才能决定自己怎么做。

 
*** 中国政府在这个问题上什么时候正式表态、如何表态，就要看决策层如何拿挰了
 
首席评论员指出，这种等待和众望所归、正是北京的优势所在，然而，值得强调的是，如果北京长时间没有一个明确方针，迟迟不表态，反而容易激起这些国家的失望和不满。
 
因此，在我们看来，中国政府在这个问题上什么时候正式表态、有个时机问题，如何表态，也有个技巧问题，这就要看决策层如何拿挰了。

 
*** 借世界反法西式斯胜利60周年之际、将日本“申常”与历史问题挂钩，明正言顺地“帮助”日本做一个“反省历史”的常任理事国
 
东方评论员认为，中国都有必要在关键的时候公开地站出来，以一种负责任的态度和决心、去直接影响其它国家的态度和决心，在我们看来，作为一种建议，北京可以考虑将阻击日本拉票的策略“定位在”支持日本在反省历史的前提下、去申请常任理事国”。
 
这样做的好处是明显的：一方面、通过带着韩国等其它“正在寻找方向”的亚洲国家、“于明于暗”、借世界反法西式斯胜利60周年之际、将日本“申常”与历史问题挂钩，表面上，可以名正言顺地要求日本对其侵略历史做出正式的反省，从而在世界范围内发动一场让国际社会旨在“认清日本”的舆论运动、而在暗地里，则可通过用各自的政治、经济资源、去制造舆论、全力阻止日本“取得资格”，达到全线拉抬日本“拉票”的政治成本和经济成本的目的。从而让日本在“爬到”正式投票之前、就得付出沉重的政治和经济代价。
 
当然了，至于投票后、北京再如何处理，那就是视情况“酌情处理”的“另外一回事”了。

 
*** 带领亚洲国家“去共同帮助”日本正视历史的中国，其获得的利益必定是长远的
 
另一方面，这种过程本身就是一个制造形象的过程，在东方评论员看来，一个公开的、以实际行动、以对国际社会负责的态度、去带领亚洲国家“去共同帮助”日本正视历史的中国，其获得的政治、经济利益必定是长远的。
 
在东方评论员看来，正是痛恨日本是一个不肯正视历史的日本，所以，日本在亚洲是不受欢迎的，因此，如果中国和其它国家一道、通过这种“定位在”“帮助日本反省自己”的过程中、让世界了解了日本是一个和纳粹一样罪恶、却至今不肯清算自己的日本，那么，我们有理由相信它必然在世界也是不会受到欢迎的。
 
这种结果，对一个想成为国际社会有影响的大国的日本，不论最后能否成为常任理事国，其遭受的打击也将是深远和广泛的。
 

下面，我们将关注的焦点转向中亚。最新消息表明，吉尔吉斯斯坦总统已经签了辞职书。尽管这则消息还的待证实，但是，吉尔吉斯斯坦的局势不能不引起我们的担心。
在东方评论员看来，由于该国与中国的联系非常紧密，我们“并不担心”今后的吉尔吉斯斯坦政府会全面倒向美国，只是，直到目前为止，时事评论员一直在注意的、“上海合作组织”方面始终没有任何消息。

首席评论员认为，不论出于什么原因，上海合作组织作为涵盖这一区域的安全组织、在吉尔吉斯斯坦出现如此大的变故的情况下、至今却是“无声无息”，这只能说明上海合作组织“还有许多功课”要做。

在一段吉尔吉斯斯坦的最新局势报道之后，我们将就吉尔吉斯斯坦今后的趋势，给出我们的观点。
 

《东方时代环球时事解读》http://www.dongfangtime.com
