# -*- org -*-

# Time-stamp: <2011-08-04 00:28:02 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 2005年6月03日 星期五



** 韩美日六方会谈代表在华盛顿举行非正式会晤

【华盛顿消息】据联合通讯社报道，韩美日等三国六方会谈首席代表在1日晚举行非正式会晤，讨论了解决朝核问题的六方会谈重启方案。

美国国务院有关负责人2日称，三国代表在前一天举行了非正式晚宴。

据该负责人介绍，六方会谈美方首席代表、美国务院亚太事务助理国务卿希尔1日下午先后与日本外务省亚大局局长佐佐江贤一郞和韩国外交部次官补宋旻淳举行双边协商，之后就以“个人名义”为他们主持了非正式晚宴。

虽然是一次非正式会晤，但这是自今年２月２６日三人在首尔晤面之后举行的首次讨论朝核问题。

该负责人还说，希尔以个人名义邀请韩、日首席代表出席晚宴，促成此次会晤。但没有正式讨论朝核问题。

华盛顿一位外交消息人士就韩美日三方举行正式协商的问题表示，日方态度积极，表示如果有提议可以接受，但韩方则持否定立场。

《日本经济新闻》曾援引日本政府有关负责人的话报道，韩国政府表明，希望暂时保留韩、美、日三国六方会谈首席代表会谈。

据一位消息人士称，佐佐江贤一郞和希尔在双边协商中达成共识认为：没有迹象表明朝鲜即将进行核试爆：如果朝鲜重返六方会谈，就采取建设性的“柔和接近法”，已做好相关准备；即将举行的韩美、韩日首脑会谈等重要活动结束以后，为加强韩美日三方合作共同努力。

据该消息人士称，美日代表还希望朝鲜早日表现出积极的反应，并重申，为使朝鲜重返六方会谈，有必要加强外交努力。

但韩国方面拒绝回答宋旻淳与希尔的协商讨论了哪些问题。



【时事点评】我们注意到，韩国方面是“拒绝回答”宋旻淳与希尔的协商讨论了哪些问题。在我们看来，既然韩国方面不愿意说明，那么，我们也只要去猜测了：显然，有一定是非常明显的，那就是重启“六方会谈”的情况“不容乐观”。

*** 美日达成“没有迹象表明朝鲜即将进行核试爆”的共识，这颇为“耐人寻味”

请大家注意这一段，原文是：佐佐江贤一郞和希尔在双边协商中达成共识认为：没有迹象表明朝鲜即将进行核试爆：如果朝鲜重返六方会谈，就采取建设性的“柔和接近法”，已做好相关准备；即将举行的韩美、韩日首脑会谈等重要活动结束以后，为加强韩美日三方合作共同努力。

在东方评论员看来，日本的佐佐江贤一郞和美国的希尔、现在竟然还能达成“没有迹象表明朝鲜即将进行核试爆”的共识，这颇为“耐人寻味”。

我们知道，最早发现、并向外界通报“朝鲜即将进行核试爆”是华盛顿，而最希望朝鲜“最好立刻就进行核试爆”的莫过于日本，然而，这两个“心态微妙、对朝核问题何去何从各怀鬼胎”的国家突然地一致认为“没有迹象表明朝鲜即将进行核试爆”，这岂不怪哉？


*** “连宋”登陆之后，在朝核问题上华盛顿就开始“频频出招”

事实上，近期以来，自“连宋”登陆之后（确切地讲、是从连战登陆的同一天开始的），华盛顿在朝核问题上就是“频频出招”：其中，既有好言相劝的“利诱”，也有恶语相向的“威逼”、一会是快言快语地“承认朝鲜是主权国家”、一会又“立马变脸”、重弹“军事解决”朝核问题的可能性不能排除；


*** 美国内各系统、部门“全面配合、上演了一幕“威逼利诱”的“全景电影”

最有意思的就是所谓“朝鲜准备核试爆”的事情了。根据我们的观察，近几个星期以来，围绕着“朝鲜准备核试爆”，可以说美国国内各系统、各部门是“全面配合、上演了一幕“威逼利诱”的“全景电影”：首先，美国的情报系统动用了最先进的太空侦察技术手段、在“发现了确切的证据”之后，立刻就声称“朝鲜准备核试爆”，接着，美国国会立刻就提出了“各种各样、花样齐全、计划周到”的、应对朝鲜核试爆的“应对方案”。

接着，也就是几天前，美国空军的15架F—117隐形战斗机再次借与韩国进行军事演习的名义、进驻韩国军事基地，以适应“朝鲜半岛的作战计划和地形”；最后，就是美国保守主义头目-美国国防部长拉姆斯菲尔德将访东南亚，声称“主谈朝核问题”。


*** 华盛顿用自己特有的“肢体语言”强调：“我已经不耐烦了”

在东方评论员看来，华盛顿拉着日本、韩国“如此如此、这般这般”、显然，美国在朝核问题上、已经用自己特有的“肢体语言”向方方面面强调这么几个字，“我已经不耐烦了”。


然而，在朝核问题上，由于事关日本和韩国这两个“美国亚洲战略之锚”、华盛顿从来就不敢掉以轻心。因此，在东方评论员看来，如果华盛顿“的确”觉得自己有能力做到“军事解决朝核问题”的话，恐怕不仅早就已经没有什么朝核问题了，也更不会有“连宋登陆”的事情发生了。

在昨天的点评的台湾部分，东方评论员再次强调了一个观点，那就是，只要华盛顿认为陈水扁“还可以再等等”、那么，北京自然也可以认为朝核问题“更有必要再等等”。


*** 北京的战略意图“非常清楚”

首席评论员指出，事实上，大陆的《反分裂国家法》在打乱了华盛顿自己原先计划好了的、以一个紧张的“台海局势”、去威逼北京在战略上全面让步的基础上、也彻底理顺了北京的“朝核政策”和“南亚政策”；

另外，中国与俄罗斯的关系也处于“向好”的、“相互信任”的方向调整中、值得强调的是，对俄罗斯而言，尽管“这种相互信任是被迫”的，但是，这已经足以让我们可以期待：中国和俄罗斯联手、离建立一套有效的“中亚政策”已经不远了。

显然，在我们看来，这一系列的“打乱”、“理顺”、“调整”，实际都不过是“中美”双方在与世界其他大国之间、为了达到一种新的、暂时的区域平衡、而做的一系列努力的代名词。

在东方评论员看来，北京的战略意图已经非常清楚：那就是，继续将“战略注意力”放在中东方向、在与欧洲、俄罗斯一起、尽力阻止、破坏美国中东进程的同时，也尽力地努力经营好朝鲜半岛，和南亚、中亚这几个方向。


*** 中国在“朝核问题”仍然是“我行我素”

显然，在台湾问题上，根据我们的观察，北京除了“更下气力”地“进行军事准备”之外，于政治层面反而摆出了一副“不急不忙的态度”。在东方评论员看来，北京的这种“不急不忙”、就表现在大陆“并不急于”让华盛顿去逼迫陈水扁做什么，相比较而言，在两岸关系上，反倒是华盛顿和陈水扁显得有点“迫不可及待”。

首席评论员指出，大陆的这种“并不急于”、则集中表现在“朝核问题”仍然是“我行我素”，也就是说，华盛顿在让“连宋按大陆乐见的顺序”先后登陆之后，并没有得到北京的帮助、从而如愿地在“朝核问题”问题上“得到些什么”。

六方会谈已经中断快一年了，但目前仍没有任何迹象表明北京有意让朝鲜将返回谈判桌旁。事实上，始终没有得到什么的华盛顿，在“连宋”成功登陆后，已经表现出不耐烦了，我们注意到，自“连宋”返台后、美国就一直在威胁朝鲜，先是要将朝核问题提交安理会，再是不断散布朝鲜准备核试爆的消息。最后，美国朝鲜问题特使狄长礼还宣称要讨论“五方会谈”方案，想把朝核问题最重要的当事国——朝鲜排除在外。

更有消息说、华盛顿甚至私下里向北京提出，要中国中断对朝鲜的石油供应，结果遭到了中国的“婉拒”。


*** 有一件事，可以是是除了美国官员“不知道”之外，谁都清楚

在东方评论员看来，华盛顿是否果真提出过这种要求、或者北京是否有“婉拒”这一说，事实上都不重要，重要的是朝鲜“依然强硬”、而中国也依然在努力地“帮朝鲜搞经济改革”。

另外，有一件事，是除了美国政府“不知道”、“从不提起”之外，谁都清楚，那就是，中国的企业和投资、和韩国的一样，正开始大量出现在朝鲜，东方评论员认为，就凭这一点，也足以证明北京“根本就没打算放弃朝鲜”。


*** 近半个月来、我们对朝核问题的分析一直在“凸现一个重点”

在朝核问题上，由于韩国与朝鲜就挨在一起，韩国更有心借朝鲜的经济改革，将整个半岛的经济整合起来，因此，“朝韩双方”这种“重和平求发展”的心愿，使北京在朝核问题上的处境“大为主动”。

之前，可以说近半个月来、我们对朝核问题的分析一直在“凸现一个重点”，那就是朝鲜的经济改革问题。可以说连续多期，我们在讨论朝核问题时，东方的时事评论员都是和经济评论员一起进行共同讨论的，事实上，时事评论员和经济评论员所共同关心的倒不是朝鲜经济改革本身，而是北京如何通过参与“这种经济改革”、参与韩朝双方的经济整合，而慢慢在东北亚“促进”经济一体化。


*** 不论是东北亚经济一体化、还是东亚经济一体化，都是华盛顿“欲除之而后快”的

首席评论员就指出，对中国以至于整个亚洲都至关重要的东亚经济一体化、因中日关系搁浅而暂时搁浅，如果北京能着手先行启动“东北亚经济一体化”，在我们看来，不论是东北亚经济一体化、还是东亚经济一体化，都是华盛顿“欲除之而后快”的事物，华盛顿的决策层非常清楚，这将对“美日”或者“美韩”同盟、都是一个巨大的威胁，


*** 北京只须“不急不躁”地、拉着韩国人、俄罗斯人共同地“做点实事”就行了


在东方评论员看来，如果美国没有本事让中东今后的局势、朝向美国有利的方向发展，只要中东局势在可见的将来“没有大的变化”，那么，华盛顿尽可以“抓着小泉纯一郎做武器、押着陈水扁做文章”，在“中日关系”上“挑灯拨火”、在“两岸和平”的问题上“虚虚实实”，在朝核问题问题上“松松紧紧”，然而，只要北京“不急不躁”地、拉着韩国人、甚至是俄罗斯人为朝鲜半岛、俄罗斯远东地区、中国东北的“稳定和发展”、共同地“做点实事”就行了。

显然，华盛顿在中东“打仗”“死人”、北京在东北亚“搞建设”“赚钱”，谁急谁不急，是一目了然。


*** 在台湾问题上，北京在完成了“止独”的基本布局之后，剩下来的就是“观察并等待”

在之前的点评中，东方评论员曾经多次强调一点，那就是，连战在大陆“豁出去”之后、从而取得了“大陆之行的完胜”，并到达了自己一生的高峰，从而令自己立于不败之地。

然而，我们同时也指出过，连战的最大麻烦将来自于国民党内部的冲击。在东方评论员看来，近些天来，国民党内部的“林林总总”已经充分证明了一点。好在连战“有大陆之行的辉煌”，在国民党的内斗中、仍然处于一个相对有利的姿态，从而为国民党“一旦分裂”，连战仍然有可能收拾好殘局打下了基础。

相比较言，在台湾问题上、由于“反分裂国家法”已经生效、连宋也成功“先后登陆”、北京在完成了“止独”的基本布局之后，剩下来的就是“观察并等待”连战“如何处理好”来自内部的冲击。


*** 在“国民党的领导权”“没有尘埃落定”前，北京不会再有什么“大动作”

在东方评论员看来，在“国民党的领导权”“没有尘埃落定”之前，北京在台湾问题上不会再有什么新动作。然而，值得警惕的是，现在“两岸和平”的问题上，是华盛顿表现得倒比北京“积极得多”，显然，我们认为，美国之所以在台湾问题上“皇帝（北京）不急急太监（华盛顿）”，催促“两岸进行和谈”，就在于布什现在正忙着“一手牵着小泉纯一郎要如何如何刺激中国、一手拉着陈水扁怎样怎样稳住大陆”、并在这种基础上冲着北京、在朝核问题上“漫天要价”。


*** 华盛顿在朝核问题上的“要价”非常简单

事实上，我们认为，华盛顿在朝核问题上的“要价”非常简单，主要就是两点，第一，要快，而且是刻不容缓；第二、就是要一步到位，要彻底解除朝鲜的核能力。

东方评论员认为，对华盛顿心思非常了解的北京，也一早就说过，“朝核问题很复杂、要有耐心，不可能一蹴而就“，在东方评论员看来，北京所说的“很复杂”、应该说的就是“布什手中还扯着的、配合着布什做小动作的那两个人”。

*** 北京要求华盛顿“要有耐心”、实际上是涵盖了整个东亚局势

而大陆所说的“要有耐心，不可能一蹴而就”，更是在与华盛顿的“要价”针锋相对。东方评论员认为，美国的东亚政策非常清楚，那就是“暂时稳定”，然而，华盛顿在为实现这一目标时，所用的手段却又与这一目标相矛盾：既，美国决策层一方面想借“两岸和谈”稳定台海、一方面又想借挑唆日本与中国对抗、在中日间制造紧张、从而以此对中国施加压力、迫使中国接受有利于美国的“东亚安排”。

显然，美国的手段与目标是冲突的，而北京要求华盛顿“要有耐心”、表面上是针对朝核问题、实际上是涵盖了整个东亚局势。在东方评论员看来，中国外交部发言人的一句“要有耐心”，说白了，根本就是对美国这一矛盾之“东亚政策”的“不买账”。

*** 大陆的对台策略：“一切都等国民党的“内部纷争”平息之后，再来处理

显然，根据我们的观察，北京的处理包括“台湾、朝核、日本”三大问题“交织在一起”的东亚局势时，其手段和方式都显得“非常冷静”，特别是在台湾问题上，由于两岸局势离“两岸三通”这一“核心指标”相距甚远，而“连宋”回去之后，都遇到了各自的、来自内部的麻烦，特别是国民党，内部正因党主席之争而闹得不可开交。

因此，大陆的策略就是“一切都等国民党的“内部纷争”平息之后，再来处理、否则，一个“在分裂的危险中挣扎着的”国民党、不仅很难去充当大陆的一枚、促进台湾政治生态转化的“高效率棋子”、反而容易成为美国、陈水扁手中用以彻底瓦解“泛蓝”势力的“药引子”。


*** 在朝核问题上，中国的策略是“不见兔子不撤鹰”

其次，在朝核问题上，中国的策略是“不见兔子不撤鹰”，也就是说，在两岸之间到达“两岸实质三通”这一层面之前，所有的“两岸和平景象”都不过是“虚拟的”，在东方评论员看来，对这些“虚拟的”玩意，北京又怎么可能去“投挑报李”？而装出一付“真诚促和”样子的华盛顿、又怎么心甘情愿意的、就这么眼看着北京“毫无回报”之心而无动于衷？

显然，在东方评论员看来，由于中日关系近来气氛“非常紧张”，再加上欧盟那边也“接连出了两件大事”，因此，华盛顿似乎觉得机会来了、显然，在华盛顿决策层看来，“这种机会”足以有理由让陈水扁“先缓一缓”，也足以鼓励小泉纯一郎“再强硬一些”、还可以在“朝核问题”上再催促一下。

下面，我们就先来通过一则新闻，看看美国是如何催促北京的，之后，东方评论员将继续今天的东亚部分。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com


** 平壤：解决朝核问题应从消除美核威胁做起

【平壤消息】朝鲜中央通讯社３日发表评论说，解决朝鲜半岛核问题不应仅仅是朝鲜放弃核武器，而应该是从消除美国的核威胁做起。

评论说，最近美国等国屡屡散布“朝鲜弃核即朝鲜半岛无核化”等论调，似乎朝鲜放弃核武器，朝鲜半岛无核化即告实现。这是对朝鲜半岛无核化本质的歪曲。

评论说，朝鲜当年发起了朝鲜半岛无核化的倡议，并为这一目标的实现进行了努力。然而，美国把核武器运入韩国，导致半岛无核化进程瘫痪。美国现政府把先发制人的核攻击作为一项政策，使得朝鲜不得不拥有核武器以求自卫，从而直接导致了朝鲜半岛的核对抗。

评论强调，朝鲜半岛无核化的焦点应该首先放在消除美国的核威胁上，以及在朝鲜与有关国家之间建立信任关系。




【时事点评】在东方评论员看来，朝核问题，其实就是华盛顿准备与北京在《反分裂国家法》已经“正式生效”的基础上，“首先要搞定”的一个“战略合作”课题。
事实上，我们之所以将其列为中美“首先要搞定”的一个“战略合作”课题，就在于朝核问题的“何去何从”、将对日本、韩国的“何去何从”有着“决定作用”。


*** 这篇评论，意在强调“朝核问题”的“核心定义”

我们注意到，朝鲜中央通讯社的这篇评论，意在强调“朝核问题”的“核心定义”，也就是说，平壤方面这是在“做一种解释”、“解释”朝核问题的“现状和内核”到底是什么？

东方评论员认为，朝鲜方面所说的“消除美国的核威胁”，事实上就是在强调北京有关“朝核问题”的定义，即，中国官方从来都在强调的一种观点：“朝核问题”是“朝鲜半岛无核化问题”、而不是单纯的“朝鲜无核化问题”。


*** 朝鲜为什么要“死死地拉着美国单挑”？

显然，在我们看来，按中国官方的立场，“朝核问题”自然就包括有美国在韩国部署核武器的问题，如此一来，平壤的这篇评论、无非是在替北京“将朝核问题之本质挑明”。

让华盛顿不满的是，华盛顿眼中的“朝鲜核问题”、不仅早已经被北京“另有目的”地“定义”成了“朝鲜半岛核问题”，而且还被“夹塞进了”东亚核竞赛、美日安保条约的问题。

非常清楚，按照北京对“朝核问题”的这种“官方定义”，不难看出，朝鲜为什么要“死死地拉着美国单挑”，北京为什么“始终如一”地将“美国和朝鲜”看作“朝核问题”的当事方，也就是说，中国一再强调的“当事人”要拿出诚意来的说法，从来就是站在这一立场上进行表述的。


*** 对美国最强硬的两个欧盟核心国家”相继出了问题，不可避免地帮助了华盛顿

东方评论员认为，现在，在中东、特别是在“两伊”问题上、华盛顿并没有什么进展，也就是说，在中东方向，布什、拉姆斯菲尔德每天听到的“除了坏消息”之外、还是坏消息。

然而、“有关中东的好消息”却从中东之外的一个方向传进了美国决策者的耳朵里，这就是欧洲内部。

东方评论员认为，欧盟宪法被法国民众否决的事实、再加上欧盟的另一架马车--德国总理施罗德在国内政治中“已经跛脚”，这些不仅对法国、德国联手、致力推动的欧洲一体化是个沉重的打击，也是对“中欧俄”阻击华盛顿中东战略的一个挫折，在东方评论员看来，因“对美国最强硬的两个欧盟核心国家”相继出了问题、相当程度地削弱了欧盟对华盛顿的“政策硬度”，“这种削弱”不可避免地帮助了华盛顿，而“这种帮助”从美国人日前“不怀好意”地表示“乐见欧洲一体化进程顺利进行”就可见一般。


*** 希拉克、施罗德的“不顺心”、的确给了华盛顿决策圈以“某种想像力”

在我们看来，华盛顿对欧盟宪法遭挫、施罗德“跛脚”的这一番“幸灾乐祸”并不值一提，但是，“法、德”这两个欧盟核心国家“相继出事”，希拉克、施罗德的“不顺心”、的确给了华盛顿决策圈以“某种想像力”。

在东方评论员看来，眼下的情况是，在华盛顿的默许下，日本右翼甚至到了公开敢为“东京审判”翻案的地步、因此，中日间自然也就会“斗得正酣”、再加上法、德这两个与中国关系最近的欧盟“两大核心”新近受挫，华盛顿的“新、旧保守主义者”显然又开始活跃起来。

*** 华盛顿的中东政策可能又在酝酿“调整”了

我们认为，最近美国屡屡散布“朝鲜弃核即朝鲜半岛无核化”的论调，其实就是一个强烈的信号，首席评论员就指出，华盛顿这次主动地、在之前它一直回避的“朝鲜半岛无核化”这个名词上做文章，主动地将“朝鲜半岛无核化”解释成“朝鲜弃核”，从而主动地“触动”北京的立场，这说明华盛顿的中东政策可能又在酝酿“调整”了。

在东方评论员看来，如果我们的判断不错的话，那么，对华盛顿的决策层而言、不论是台海政策、还是朝核政策、以及伊朗政策都会产生一种“再调整的冲动”，至于华盛顿是否有、更或者有什么“相应动作”，时事评论员也将和大家一起、去拭目以待。

下面，是一则译自俄罗斯《真理报》的报道片段，在一起了解具体内容之后，我们将进入今天的中亚部分。


《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
