# -*- org -*-

# Time-stamp: <2011-08-04 11:53:02 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

*  2005年7月05日 星期二

** 上海合作组织成员国元首宣言（全文）




【新华网阿斯塔纳７月５日电】上海合作组织成员国元首理事会会议５日在哈萨克斯坦首都阿斯塔纳举行，会议发表了《上海合作组织成员国元首宣言》。宣言全文如下：

上海合作组织成员国元首宣言

（２００５年７月５日，阿斯塔纳）

上海合作组织（以下简称“本组织”或“组织”）成员国━━哈萨克斯坦共和国、中华人民共和国、吉尔吉斯共和国、俄罗斯联邦、塔吉克斯坦共和国和乌兹别克斯坦共和国元首２００５年７月５日在阿斯塔纳举行上海合作组织成员国元首理事会会议，声明如下：

一

２００４年６月１７日塔什干峰会提出的进一步发展和巩固上海合作组织的所有任务已基本完成。本组织稳步推进成员国的多边合作，积极同其他国际组织和国家开展合作。

２００４年启动的本组织常设机构━━北京秘书处和塔什干地区反恐怖机构（简称“反恐机构”），成为保障组织顺利运作的有效集体机制。反恐机构的领导机关━━理事会的作用日益显著，并应进一步加强。

为提高上海合作组织及其所有机构和机制的工作效率和协调作用，元首们商定，国家协调员理事会在２００６年峰会前，就加强秘书处作用和将秘书处领导职务俄文名称改为上海合作组织秘书长提出建议。

元首们指出，采取必要措施，落实２００５年６月２日在阿斯塔纳举行的本组织成员国第二次安全会议秘书会议达成的协议十分重要。

为促进反恐机构落实《打击恐怖主义、分裂主义和极端主义上海公约》，元首们同意按照已有的常驻秘书处代表机制的原则，建立成员国常驻反恐机构代表机制。

元首们相信，峰会期间通过的《上海合作组织成员国合作打击恐怖主义、分裂主义和极端主义构想》有利于提高合作效率，使反恐机构的活动更明确，更有针对性。

元首们认为，２００５年秋即将在莫斯科举行的政府首脑（总理）理事会会议，将对执行２００４年９月在比什凯克通过的《〈上海合作组织成员国多边经贸合作纲要〉落实措施计划》，把成员国对外经贸、交通、环保、紧急救灾、文化和教育部门合作引上务实轨道起到具体推动作用。这一会议还将确定本组织合理的财政预算政策。

本组织实业家委员会的组建工作已近尾声，它应成为促进本组织框架内一体化进程的新资源。各方将本着协商一致的原则加快建立本组织发展基金。同时，各方同意加强银行间协作，为实施区域合作项目提供融资支持。

元首们指出，外长理事会做了大量建设性工作，强调，业已启动的国际问题磋商机制切实运转十分重要。元首们认为，确保本组织审慎和有针对性地开展对外交往是一项迫切任务。这些问题原则上应由外长理事会解决，而本组织常设机构对外交往的日常协调工作则由国家协调员理事会会同反恐机构理事会负责。

元首们相信，给予巴基斯坦、伊朗、印度本组织观察员地位，将增加本组织在各领域开展多边、互利合作的潜力。

本组织国际声望日益提高的重要标志，是本组织２００４年１２月获得联合国大会观察员地位，２００５年４月与东盟和独联体签署谅解备忘录。

近期，国家协调员理事会应会同秘书处和反恐机构制定共同立场，使本组织能够最有效地与联合国秘书处及各委员会开展交往，落实同其他国际组织签署的合作文件，在平等和相互尊重的基础上与区域组织、论坛及有关国家建立联系。

二

元首们指出，在矛盾的全球化进程中，在平等、相互尊重、不干涉主权国家内政、非对抗思维和不断推动国际关系民主化的原则基础上开展多边合作，有助于维护普遍和平与安全，呼吁国际社会超越意识形态和社会制度差异，树立互信、互利、平等、协作的新安全观。

世界文化和文明的多样性是全人类的财富。在信息技术和交通迅猛发展的时代，这种多样性应促进相互了解和宽容、避免极端态度、发展对话。应充分保障各国人民选择自己发展道路的权利。

元首们坚信，公正合理的世界秩序应建立在巩固互信、睦邻、建立真正伙伴关系、不谋求垄断和主导国际事务的基础上。国际法，首先是《联合国宪章》的原则和准则的主导地位越强，这一世界秩序就会越稳定、越安全。在人权领域，必须严格和始终尊重各国人民历史传统和民族特点，坚持所有国家主权平等。

元首们支持联合国进行合理、必要的改革，以提高效率，维护权威。重申联合国改革应遵循最广泛协商一致的原则，不应为改革设立时限及强行推动表决尚有重大分歧的方案。

元首们认为，２１世纪，亚太地区必将在促进和平与发展中发挥重要作用，主张：在整个亚太地区或次地区不应出现分界线；国家间的任何误解和争端都应通过谈判和平解决；应在这一充满活力的地区营造持久友好、相互理解、协作和建设性的氛围。推动实现这一目标，是本组织的一项主要工作。

元首们支持中亚国家为维护本国和整个地区和平、安全与稳定所作的努力，赞成本组织在促进中亚稳定和经济发展方面积极发挥作用。


三

元首们认为，成员国应共同努力，有效应对国际和地区安全与稳定面临的新挑战和新威胁。

这一共同努力应具有综合性质，能切实促进成员国对领土、居民、生活保障和基础设施的关键部门实施可靠保护，使其免受新挑战和新威胁的破坏，为本组织内各国的持续发展和消除贫困创造必要条件。这一共同努力包括：

━━开展成员国外交、对外经济、执法、特种和国防部门的密切合作；

━━充分发挥成员国安全会议秘书会议机制的作用；

━━制定本组织对威胁本地区和平、安全与稳定的事态联合作出反应的有效措施和机制；

━━共同制定和实施反恐措施；

━━协调各成员国安全保障方面的法律；

━━在研制和应用应对新挑战和新威胁的现代技术装备领域进行合作；

━━在大众传媒领域建立应对新挑战和新威胁的有效机制；

━━培训相关人员。

本组织成员国将制止在本国领土上策划和实施恐怖活动，包括针对其他国家恐怖活动的企图，不向被指控或涉嫌实施恐怖、分裂和极端活动的人员提供庇护。在本组织其他成员国提出相关请求后，严格遵照成员国现行法律移交这些人员。

将采取措施完善和提高本组织地区反恐怖机构的工作效率。

重要的是，本组织应在打击国际恐怖主义框架内解决消除恐怖主义的物质基础的问题，首先要打击走私武器、弹药、爆炸物和毒品，打击有组织跨国犯罪、非法移民和雇佣兵活动。特别要注意防范恐怖分子使用大规模杀伤性武器及其运载工具，防范信息恐怖主义。

为打击资助恐怖主义、分裂主义和极端主义的活动，包括将非法收入合法化的活动，迫切需要在本组织框架内制定统一方法和标准，以监控涉嫌参与恐怖活动的个人和组织的资金流动，同时积极推动上海合作组织参与相关国际努力。

根据２００４年６月１７日签署的《上海合作组织成员国关于合作打击非法贩运麻醉药品、精神药物及其前体的协议》，深化打击非法贩运麻醉药品、精神药物及其前体的合作应成为优先方向。本组织愿积极参与在阿富汗周边构筑“反毒带”的国际努力，参与制定并实施专门计划，帮助阿富汗稳定社会经济和人道主义形势。

我们支持并将继续支持国际联盟在阿富汗进行反恐行动的努力。今天，我们看到阿富汗在国内局势稳定方面发生了积极变化。为开展反恐行动，上海合作组织一些成员国向联盟各国提供了地面基础设施以临时部署军队，还提供了地面及空中军事运输通道。

鉴于阿富汗反恐的大规模军事行动已经告一段落，上海合作组织成员国认为，反恐联盟有关各方有必要确定临时使用上海合作组织成员国上述基础设施及在这些国家驻军的最后期限。

从预防和消除已成为新威胁重要组成部分的各种技术性灾难来看，保护和发展关键基础设施、交通设施越来越迫切。本组织成员国将制定多边机制，对可能发生的灾难及其后果进行监测、交换分析性信息，为进行联合救援行动创造必要的法律和组织条件，包括按统一方法培训人员、迅速调遣人员和实现技术装备的兼容。

上海合作组织将为国际社会维护陆地、海上、空中和外空安全的努力作出建设性贡献。

为提高打击恐怖主义、分裂主义、极端主义及应对其他挑战和威胁的能力，本组织成员国将根据多边经贸合作纲要及其落实措施计划，不断扩大经济合作。在生态和合理利用自然资源领域采取实际措施。

提出一致的方法和建议，在居民中采取预防性措施和进行相应解释工作，以抵制错误引导社会舆论的企图，是一项迫切任务。成员国将积极扩大本组织框架内教育、文化、体育、旅游等领域的合作。

元首们认为，本组织为保障安全和加强自身能力所作的共同努力，丝毫不损害其他国家的利益，不意味着要建立某种同盟。这样做完全符合本组织的开放原则，符合为应对新挑战和新威胁而进行广泛国际合作的精神。




【时事点评】在东方评论员看来，在中俄联手下，上海合作组织的潜力无疑是非常巨大的，显然，胡锦涛与普京在“会前的见面”中一口气签了一大串的、打着“务实合作”烙印的“合作协议”，也就注定了这次“上合峰会”必然会成为“上合组织”欲通过“加强务实合作”、将巨大的潜力转化为“看得见、摸得着的成果”的一个里程碑。


*** 其“名副其实地长期存在”将取决于能否在“经济上共同繁荣”

显然，如果我们顺着这个思路去分析这篇元首宣言的话，那么，我们就会非常清楚地看到，“务实”的精髓、在宣言中可以说是“无处不在”。

首席评论员认为，中俄要想让上海合作组织能够“名副其实地”长期存在，那么，仅靠军事实力是不够的，在我们看来，上海合作组织的成立、取决于所有成员国希望在安全问题上的“同舟共济”，但是，其“名副其实地长期存在”将取决于能否在“经济上共同繁荣”。

*** 中俄的策略就是以“反恐”为旗帜、来达到国家、经济安全上的战略目标

在我们看来，就目前而言，在国家安全上、中俄的策略就是以“反恐”这个长期任务为旗帜、来达到国家、经济安全上的战略目标，在这一点上，与美国打着反恐的旗号谋取世界霸权的策略如出一辙。

但是东方评论员认为，假若忽视了其他领域、特别是在经济上的相互协助与合作，那么不论是“反恐”这面旗帜多么鲜艳、都不足以维持上合组织的凝聚力，从而导致各国在政治、军事上的合作或有心无力、或有名无实，如此一来，上合组织必将会沦为权宜的、半心半意的“花架子”。

*** 今天的元首宣言中，就花了大量篇幅谈经济问题

有意思的是，在今天的元首宣言中，就花了大量篇幅谈经济问题。

首先，我们来看定段文字，原文是：元首们认为，２００５年秋即将在莫斯科举行的政府首脑（总理）理事会会议，将对执行２００４年９月在比什凯克通过的《〈上海合作组织成员国多边经贸合作纲要〉落实措施计划》，把成员国对外经贸、交通、环保、紧急救灾、文化和教育部门合作引上务实轨道起到具体推动作用。这一会议还将确定本组织合理的财政预算政策。

本组织实业家委员会的组建工作已近尾声，它应成为促进本组织框架内一体化进程的新资源。各方将本着协商一致的原则加快建立本组织发展基金。同时，各方同意加强银行间协作，为实施区域合作项目提供融资支持。

在东方评论员看来，这段文字的重点有两个，第一，各国确定了“稍后将在莫斯科举行的政府首脑（总理）理事会会议，将敲定“上合组织的财政预算政策”；第二，“各方同意加强银行间协作，为实施区域合作项目提供融资支持”。


*** 中亚国家的“焦点问题”，源于前苏联时期

显然，从这一点上看，不论是北京还是莫斯科，心里都非常清楚，那就是，中亚各国的“焦点问题”，仍然是“经济的落后”，在东方评论员看来，“经济的落后”而导致的社会不满、这不仅是华盛顿大搞“颜色革命”的基础、也是这也是滋生恐怖、极端主义的温床。

然而，造成这一情况的主要原因就是在苏联时期，这些中亚加盟共和国一直在被当成原料供应地在使用，结果，久而久之，中亚经济就成了今天这副“经济单一，结构畸形”的经济模式。


*** 如果只是“输血”、就与华盛顿对中亚的经济援助没有本质的区别

事实上，近年来，针对美国的咄咄逼人，和中亚国家的“焦点问题”，中俄两国在经济上对中亚各国都提供了不少援助，并有意逐步加大对各国建设项目的投资。

然而首席评论员则指出，这些措施都是非常必要的、但是，这更多地是在“输血”、而非“造血”，与华盛顿的经济援助没有本质的区别。

在我们看来，上合组织成员国间的经济合作只有过渡到“造血”这一层，才能真正密切彼此的经济交往，才能真正使成员国之间的利益变得密不可分，才能真正保持上海合作组织的旺盛生命力。


*** 在为中亚国家造血的问题上，中国相比美国而言、有着经济结构和地理上的极大便利优势

东方评论员认为，在为中亚国家造血的问题上，中俄相比美国而言、有着地理上的极大便利优势，特别是中国，可以说与经济结构主要是能源与资源型的中亚经济、有极高的互补性，这表现在中国一方面可以大量进口这些国家的能源与资源，另一方面，也可以向该地区输出数量巨大的、价格合适的生活用商品，这是任何一个国家都无法做到的事情。

显然，在我们看来，中国日后可以努力的，就是尽可能将一些生产放在资源丰富的中亚国家进行，一方面可以减少生产成本，而另一方面着着实实地为这些国家“造血”，从而令上海合作组织的合作内容“有血有肉”。


*** 俄罗斯与中国在“如何搞好”中亚经济的问题上的一种分岐

但是，需要非常注意的是，首席评论员指出，中亚经济结构的这种“历史与现实”，在今天俄罗斯与中亚国家的经济关系中、仍然没有根本地改变。在我们看来，这也就引出了俄罗斯与中国在“如何搞好”中亚经济的问题上一种分岐。

在东方评论员看来，这种分岐可以说集中地表现在对待“中亚共同市场”的态度上。


*** 中亚国家搞“中亚经济共同体”的目的就是准备“左右逢源”

众所周知，中亚四国自独立以来，就在中亚经济共同体基础上于2001年12月组成中亚合作组织，在东方评论员看来，中亚国家搞“中亚经济共同体”的目的就是准备“左右逢源”，即同时积极参与欧、亚经济共同体。

值得一提的是，为了实现这一战略、去年乌兹别克斯坦就挑头提议，是否可以在中亚也建立一个共同市场，称之为“中亚共同市场”，其“公开的宣传标语”是“吸引更大的资本进入中亚，带动地区的整体繁荣”。


*** “中亚共同市场”的提法，事实上让普京“非常不高兴”

然而，东方评论员注意到，这个“中亚共同市场”的提法，事实上让普京“非常不高兴”。要知道，尽管这几年来，俄罗斯的经济有了起色，但是，这种起色在很大程度上是受益于近年国际油价的高涨所致。

因此，东方评论员认为，普京的“不高兴”源于俄罗斯的“尴尬”，而“俄罗斯的尴尬”在于与前苏联时期相比，俄罗斯与中亚诸国的经济关系本质上不过是“新瓶装旧酒”而已，显然，以俄罗斯的经济结构、维持中亚诸国的生存还可以，但要增加对这些国家的投资、带动这些国家走上整体繁荣，就勉为其难了。

在东方评论员看来，按“现实”的“国际社会分工”，俄罗斯的角色显然更象是一个能源与资源供应国，仅靠卖资源为生的俄罗斯，是无从复兴的、自然也很难向中亚大量投资、这又何以带动中亚国家向往的整体繁荣？


*** 在俄罗斯的强烈戒心下，多年以来，上海合作组织只停留在政治层面

要知道，中亚诸国原来就是苏联的加盟共和国，是俄罗斯的“自留地”，长久以来，俄罗斯实际上搞的是一套、依靠它与这些国家固有的经济联系、极力排斥任何强权对当地经济的深层次介入、从而确保自己对中亚命脉的“事实控制”。显然，这种被排斥的对象国中，不仅有美国、欧洲、也有中国。

不难看出，在俄罗斯的强烈戒心下，多年以来，上海合作组织只停留在政治层面，在实际内容上、至多延伸到了联合反恐这一层。显然，这种局面更多地反映了莫斯科与北京一起创建上合组织、意在“稳住中亚控制里海石油”的初衷，而与北京与俄罗斯一起创建上合的、意在“整合中亚得到里海石油”的初衷“相去甚远”。


*** 面对喜欢在大国中玩平衡的中亚国家、和戒心甚众的俄罗斯，北京只能等待

然而，喜欢在大国中玩平衡的中亚国家、普遍都对限制美国势力的、“政治型”“上海合作组织”持“不积极态度”、更期待一个“经济型”的“上海合作组织”，在东方评论员看来，建立“中亚共同市场”的那条“公开宣传标语”、即“吸引更大的资本进入中亚，带动地区的整体繁荣”这一愿望，就是在这种“更大的期待”中产生的。

只是对于俄罗斯而言，直到不久前、”中亚共同市场”这几个字、听起来都觉得非常“分外刺耳”，根本就是“哪壶不开提哪壶”。

相比而言，又想增强“上海合作组织”“政治性”、更想强化“上海合作组织”“经济性”的北京，在华盛顿在中亚“腾挪”之际，在这种“各方都有小九九”的限制下，可以做的只能是拿出耐心、做好准备、等待机会。


*** 中亚的“不积极态度”、俄罗斯的“强烈戒心”、终因几事“在很大程度上给中和了”

东方评论员认为，中亚国家对“政治型”“上海合作组织”所持的“不积极态度”、以及俄罗斯对经济型“上海合作组织”的强烈戒心，终因几个月前的几件事“在很大程度上给中和了”。

在我们看来，一件是继乌克兰颜色革命之后，美国又成功地在吉尔吉斯复制了一遍，这是华盛顿第一次将“颜色革命”的颜色、涂抺进了上海合作组织的区域内。
再就是，在吉尔吉斯得手的美国、又企图在乌兹别克如法炮制，结果乌兹别克政采取了有别于别国政府的手段、以强力镇压的手段解决了美国的计划。

首席评论员指出，上述两个成员国的“不同遭遇”，以及华盛顿靠民主破坏当地政权的“不遗余力”、平息了其他国家对“政治型”“上海合作组织”不满，从而愿意进一步加强其“政治性”。


*** 这份元首声明，使得“上合”框架中、第一次有了“中亚共同市场”“清晰的影子”

再就是那条美国主导的、连接里海和地中海的巴库(阿塞拜疆)―第比利斯(格鲁吉亚)―杰伊汉(土耳其)的“巴杰石油管道”、于两个月前的“开通”、以及将于九月正式输油，显然，表现上华盛顿是在抽里海的石油，实际却是在抽俄罗斯“油管网”中的“血”，在东方议员看来，“巴杰石油管道”的开通，就是冲着中俄两国的中亚战略来的，特别是对俄罗斯而言，其中亚战略已经被这条年输送能力达8000万吨的石油管线，给彻底抽空了。

我们认为，这种局面，也就迫使俄罗斯必须调整那套、通过控制中亚能源出口路线、从而控制中亚经济命脉、对中亚实行“事实控制”的策略。

也是到了这个时候，俄罗斯在犹豫了一年多后，似乎才突然发觉“中亚共同市场”听起来不那么刺耳了，也才觉得搞中亚共同体似乎“的确有其必要”。

在东方评论员看来，从这份元首声明中的、有关经济合作、特别是银行间合作的描绘，使得“上海合作组织”的框架中、第一次有了“中亚共同市场”“清晰的影子”。


*** 成员国在强化其“政治性”的方面，也达成了一个“引人瞩目”的“共识”

当然，这是成员国有意强化其“经济性”的一个共识，在另一方面，成员国在强化其“政治性”的方面，也达成了一个“引人瞩目”的“共识”。

请大家注意宣言中的这么一段：我们支持并将继续支持国际联盟在阿富汗进行反恐行动的努力。今天，我们看到阿富汗在国内局势稳定方面发生了积极变化。为开展反恐行动，上海合作组织一些成员国向联盟各国提供了地面基础设施以临时部署军队，还提供了地面及空中军事运输通道。

鉴于阿富汗反恐的大规模军事行动已经告一段落，上海合作组织成员国认为，反恐联盟有关各方有必要确定临时使用上海合作组织成员国上述基础设施及在这些国家驻军的最后期限。

*** 加上“临时”二字后，这份“组织要求”的矛头就直指华盛顿

东方评论员注意到，“元首们”一致认为“我们看到阿富汗在国内局势稳定方面发生了积极变化......阿富汗反恐的大规模军事行动已经告一段落”；另外，也是最重要的，是“上海合作组织成员国认为，反恐联盟有关各方有必要确定临时使用上海合作组织成员国上述基础设施及在这些国家驻军的最后期限”。

众所周知，美国自攻占阿富汗以来，今年可以说是美军在阿富汗情况最为糟糕的一年，而“元首们”却一致认为“我们看到阿富汗在国内局势稳定方面发生了积极变化”，并以此首次“以组织的名义”要求外国在上海合作组织成员国的外国“临时”驻军限期撤离。

东方评论员认为，在“上合”以组织的名义要求外国驻军限期撤离的要求中，有两个字非常关键，这就是“临时”两字，目前，在上合组织成员国驻扎的外国军队，只有俄军与美军两家，俄罗斯军队的“存在”是由来已久，而加上“临时”二字后，这份“组织要求”的矛头就直指华盛顿。

*** 中亚诸国向中俄的、旨在限制美国影响力这一政治立场“积极靠拢”的重要信号

在东方评论员看来，这是中亚诸国向中俄的、旨在限制美国在中亚发挥影响力这一政治立场“积极靠拢”的重要信号。

我们知道、华盛顿是扛着反恐大旗进入中亚的，因此，中俄要将美国的势力挤出中亚，除了搞好经济合作、“强化”中亚国家“这一积极性”之外，在政治、安全层面，最好的办法就是“抢过”美国手里的反恐大旗，在上海合作组织的框架内“打造”一只强大的反恐利器、“更积极地帮助反恐”、甚至将反恐的范围从中亚扩展到西亚、南亚、并与中东美国主导的“反恐阵地”“对接”。

在我们听听一则来自俄罗斯国家电视台的消息摘录之后，再来继续谈论这一话题。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
