# -*- org -*-

# Time-stamp: <2011-08-04 11:58:48 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 2005年7月12日 星期二

  

** 7月12日外交部发言人刘建超在例行记者会上答记者问

 

　　【中国外交部网站消息】7月12日下午，外交部发言人刘建超主持例行记者会。下面是有关中亚问题部分节简：
　　
　　问：赖斯此次访华总体而言非常成功，使得六方会谈得以恢复。但她会见胡锦涛主席等中方领导人时，双方显然还有不同意见。中美在哪些方面意见不一?赖斯在记者招待会上表示，美国不会从阿富汗撤军，而此前上海合作组织曾表示希望美撤军。据新华社报道，胡主席也对赖斯表示，中国永远是一个和平崛起的国家，对美没有威胁。他为什么要提这个问题？

　　答：胡锦涛主席和赖斯国务卿小范围会见的时间比较长，有40—50分钟。双方谈到了很多问题，既谈到了中美间的双边关系问题，也谈到了朝鲜半岛核问题。此次赖斯国务卿访华期间，胡锦涛主席、温家宝总理和唐家璇国务委员与她会见、李肇星外长与她会谈中，双方就一系列问题交换了意见，其中既有共识也有分歧。我们认为，有分歧并不可怕，关键在于双方能够深入交换意见，扩大共识，增进了解。

　　关于你提到的美方表示拒绝从上海合作组织有关成员国撤军的问题，中方的立场是，上海合作组织有关成员国在“9·11”之后积极配合国际反恐联盟在阿富汗的行动，为稳定阿富汗局势作出了重要努力。同时，它们也认为，现在的局势发生了重大变化。有关国家提出应明确使用有关地面设施和在其境内驻军的最后期限，中国对有关国家的意愿表示理解，认为他们的意愿值得重视和尊重。正因为如此，有关内容写进了《上海合作组织成员国元首宣言》。有关具体安排还有待于上海合作组织的有关国家同反恐联盟的有关国家进行商谈。

　　你在第二个问题中把撤军这件事情和中国的和平发展联系在一起，我认为没有什么理由。中国在走和平发展道路，中国不威胁任何人。

　　问：最近，美国多位高官接连访华，这是以往罕有的。这反映了中美关系怎样的状态？美国一方面希望与中国合作，另一方面又加强了对中国纺织品设限，中方对此有何评论？

　　答：中美最近有很多交往，并且互访层次很高，这与中美两国关系总体上保持稳定的发展势头有关。两国领导人已经就进一步推进中美建设性合作关系达成了重要共识，有关共识也在逐渐落实。你提到的一系列接触和互访也是双方在落实两国领导人达成共识的具体表现。中美双方都认为中美关系发展到今天的程度来之不易，对两国人民的发展都是有益的。中美关系发展到今天，出现一些问题和分歧是难免的。因此，中方主张在平等互利和相互尊重的基础上，不断地扩大共识，消除分歧，妥善解决两国之间存在的问题，包括贸易问题。我们相信通过平等协商，这些问题是可以逐步解决的。

　　


【时事点评】在我们看来，外交部举行的这场记者招待会，可以说是自上海合作组织元首宣言明确要求“临时部署”的外国军队“离开”成员国、中美高层又经历“近距离对话”之后的、第一次“正式表态”。

●中亚问题、才是中美这次高层对话的“重中之重”

对此，首席评论员就指出，赖斯的这次访华、表面上是在处处强调“主要是为了朝核问题而来的”，然而，在我们看来，不论是掩盖在“朝核问题”下面的中亚问题、才是中美这次高层对话的“重中之重”。

在我们具体展开今天的中亚部分之前，我们再来看一则消息、看看刚从吉尔吉斯斯坦总统大选中以近9成得票率当选的代总统巴基耶夫、是“如何赶华盛顿上路”的。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com


** 
吉尔吉斯斯坦新总统举行记者会 督促美撤军


 
 【中新网7月12日电】据悉，在吉尔吉斯斯坦总统大选中获胜的代总统巴基耶夫在11日召开了当选后的首次记者会见，表示因为参加阿富汗作战而在吉尔吉斯斯坦驻留的美军，已经迎来讨论“是否有必要的时期”，督促了美军的撤退。

根据吉尔吉斯斯坦中央选举委员会11日宣布的总统选举初步结果，代行总统职务的吉总理巴基耶夫在选举中占据绝对优势，当选总统已成定局。

吉中央选举委员会发言人说，在对95%的选票进行统计后得出结果，巴基耶夫获得88.9%的选票。

吉尔吉斯代总统称俄仍是战略伙伴  
 
当天，吉驻俄大使透露，美国部署在吉的军事基地有可能很快关闭。他说，当选总统巴基耶夫明确表示过，俄罗斯过去是、现在是、今后仍将是吉的战略伙伴。

绝对优势赢得大选

在10日举行的吉总统选举中，巴基耶夫在已统计的99．52％的选票中获得86．97％的选票。根据吉选举法，吉中央选举委员会应在投票结束后3日内将选举结果提交吉宪法法院，而后者应当在收到选举结果后的4日内对选举合法性作出裁决，如果裁决选举结果合法，那么在此后的30日内，新总统将在议会宣誓就职。

巴基耶夫11日下午在吉政府大楼说，吉总统选举顺利完成是人民的胜利。巴基耶夫说，在担任总统后他将邀请吉政坛重要人物库洛夫出任总理一职，这一点不会有变化。

俄军基地不可替代

吉尔吉斯斯坦驻俄罗斯大使朱马古洛夫11日说，随着阿富汗局势的变化，美国部署在吉尔吉斯斯坦马纳斯的军事基地有可能很快关闭。

朱马古洛夫当天对媒体发表谈话时说，鉴于阿富汗局势出现进展，美国部署在马纳斯的军事基地正在改变其原有用途，撤除该基地早已是可以预见的。他说，吉领导人在哈萨克斯坦首都阿斯塔纳举行的上海合作组织峰会上明确表示，鉴于阿富汗国内局势日渐缓和，部署在吉的美军军事基地应确定撤除的最后期限。他认为，这完全有可能在不久的将来得以实现。

在谈到俄罗斯部署在吉的坎特军事基地时，朱马古洛夫说，该基地是独联体的一个关键军事基地，其作用不可替代。俄罗斯过去是、现在是、今后仍将是吉的战略伙伴。当选总统巴基耶夫也明确表达了这一立场，并强调，在吉部署俄军事基地在战略上是非常重要的。

2001年，美国及其北约盟国借反恐之名屯兵中亚，在比什凯克的马纳斯国际机场设立军事基地，现驻扎有约1500名美国及其北约盟国的军人，还部署了部分战斗机。俄罗斯出于战略考虑，随即在吉设立坎特军事基地。

 


【时事点评】事实上，自上海合作组织的“元首宣言”公开发表之后，国际社会就一直在瞪大眼睛注视着“中俄”联手在中亚打击华盛顿的后续动作。然而，在我们注意到直接受到“颜色革命”冲击的两个国家--乌兹别克斯坦、吉尔吉斯斯坦在极短的时间内、就立刻要求“美军撤走”的这一幕之后，多少还是觉得“来得太快了”。


●“颜色革命”的参与者、和最大受益者的对“颜色革命”“总导演”的“不假颜色”

 大家都知道，刚刚当选的吉尔吉斯斯坦代总统巴基耶夫，之所以是该国的“代总统”，就是拜美国搞的“颜色革命”所赐。

 因此，在东方评论员看来，非常有意思的是、这位身为“颜色革命”的“参与者”、也是“颜色革命”最大受益者的代总统、在正式当选后的首次记者会上就“不假颜色”地、直接让“颜色革命”的总导演华盛顿“走人”，足以说明美国的中亚政策、特别是布什第二任期就职时就大做、特做广告的“移植民主计划”、是“何等的失败”！


●中亚国家有办法将美国人赶走吗？

 与此相对应的就是乌兹别克斯坦政府的反应了。众所周知，作为“颜色革命”的“革命对象”，该国政府更是一早就公开提醒华盛顿“应该离开了”，并第一次公开向美国索要“使用该国军事基地的相关费用”。

  总而言之，到目前为止，上海合作组织可以说是从“组织”到各成员国，都已经充分表达了“要求美国撤军”的意愿。当然，东方评论员也注意到，美国官方的正式反应仍然是“不撤军”、其根据无非就是事先与中亚有关国家签定的“协议”。

显然，在东方评论员看来，华盛顿这是“想赖着不走”，那么，这些中亚国家有办法将美国人赶走吗？

东方评论员注意到，乌兹别克斯坦外交部先前已经正式发表声明，专门提出了美军在其境内继续驻留的问题。基中，声明就直接指出，哈纳巴德军事机场只是供美国人临时使用，对打击塔利班的军事行动提供必要的支持，没有任何协议规定其在战事结束之后继续使用的权利。乌外交部还要求美国支付乌方为美军基地提供行动保障和警卫服务的费用，并对美军飞机和人员对附近生态造成的损害进行赔偿。


●一个“需要首先解决、却又似乎不太好解决的问题”

 在东方评论员看来，那份声明的在要求华盛顿撤军的同时，显然知道有一个“需要首先解决、却又似乎不太好解决的问题”，那就是“如何界定”针对塔利班的反恐战事“是否结束”。


●华盛顿凭借来与提供军事基地的中亚国家“据理力争”的“支点”

 非常清楚，美军当年以打击塔利班为由、在向中亚国家“申请”军事基地的时候，是有协议的，也就是说，莫斯科当时出于靠近华盛顿的目的、而同意中亚国家向美国提供军事基地的同时，也是知道这些协议的，因此，上海合作组织在“限期”美军撤出的时候，也只能笼统地说“限期”两字，

事实上，这些借用军事基地的协议、正是华盛顿凭借来与提供军事基地的中亚国家“据理力争”的“支点”。


●用“协议之外”的要求来“找华盛顿的麻烦”

然而，有意思的是，乌兹别克斯坦外交部在正式发表的那份声明中，已经点出了拆解这一“支点”的工具：东方评论员注意到，乌外交部明确要求美国“支付乌方为美军基地提供行动保障和警卫服务的费用”，还要求“美军飞机和人员对附近生态造成的损害进行赔偿”，显然，在我们看来，这已经有用“协议之外”的要求来“找华盛顿的麻烦”的意思。


●“支付这些基地保障与警卫服务费用”的说法，我们也是第一次听说


据我们所知，美国当时同意支付大笔的军事基地使用费之后才进驻中亚国家军事基地的，而美国向相关国家“支付这些基地保障与警卫服务费用”的说法，我们这才是第一次听说。

不论如何，乌兹别克斯坦已经根据上海合作组织的“有关精神”正式向美国提出了这一系列的要求，这就是说华盛顿在根据“已有的协议”“据理力争”的时候，必须评估自己对“这些协议外的要求”是否有足够的能力应付？


●“反恐战争”是否结束的“判断标准”，本就是个“艺术性问题”而不是“科学性问题”

对此，首席评论员就表示，针对阿富汗塔利班组织的“反恐战争”是否已经结束的“判断标准”，本来就是个“艺术性问题”而不是个“科学性问题”，根本就无从“具体量化”。

因此，东方评论员认为，手中“挰着协议”的华盛顿、的确可以“就反恐战争是否结束”这一“艺术性问题” 与相关国家“摆事实、讲道理”，特别是英国伦敦刚好发生了恐怖袭击事件，在我们看来，华盛顿和伦敦就是想“将爆炸的组织者”的帽子“硬戴在”塔利班组织的身上，经过一番“定向侦察”之后，也是“完全办得到”的事情。


●华盛顿“拿着协议与所在国政府”可以“讲道理”，同“老百姓”又如何“讲清楚道理”？

然而，就算是按照协议规定、华盛顿的确“有理”、且华盛顿也有信心“据理力争”赢回局面，可问题在于华盛顿“拿着协议与所在国政府”倒是可以“讲道理”，却恐怕很难在所在国政府不提供保护的情况下，与以各种方式（包括游行示威、包围美军军事基地、阻碍美军正常行动、妨碍美军基地正常运转）要求美军离开的“老百姓”去“摆事实”“讲道理”、如此一来，也就勿谈“可以讲清楚这些所谓的道理”了。


●要知道“民主”不是美国人的专利

东方评论员认为，要知道“民主”不是美国人的专利、表达民主的形式、美国人不仅见过不少，也“创造过” 不少！因此，在东方评论员看来，只要当地政府“有足够的决心”将上海合作组织明确提出、“要求临时驻扎的外国军队从成员国撤军”的精神加以“彻底落实”的话，那么，这些国家的政府是有很多办法让华盛顿“不想走也得走的”。在我们看来，其中，恐怕最高效的方式就是运用“民主”这一招了。


●这些国家是否有足够的决心办成这件事，中俄的态度最为关键

对此，东方评论员就认为，类似上述的这种“拿协议外的东西”给华盛顿“出难题”的思路、就非常可取、也会非常有效。

然而，在这里，东方评论员想再次强调的就是这些中亚国家要有“足够的决心”，另外，东方评论员还想强调的一点是，这些中亚国家是否有“足够的决心”、则取决于“中俄”两国“如何决定”。


●“什么时候撤军”绝对是可以拿来“坐在世界地图上”“充分切磋”“充分交换”的条件


在我们看来，在美国“撤军问题”上，既然中亚国家“有许多办法”让华盛顿“不想走也得走”、那么、北京、莫斯科以及华盛顿这三家可以说“彼此也就心里有数了”，那就是、“这个问题”其实已经被纳入了“三家各自”全球战略格局之中了，这就是说、“什么时候撤军”绝对是“中俄美”可以拿来“坐在世界地图上”、去“充分切磋”、“充分交换”的条件。


●在这种背景下，我们再去看刘建超的“答记者问”，就显得“别有意味”


显然，在这种背景下，我们再去看刘建超在记者会上、针对“赖斯在记者招待会上表示，美国不会从阿富汗撤军”的问题、所给的一段答记者问，就显得“别有意味”。原文是这样的：

答：......关于你提到的美方表示拒绝从上海合作组织有关成员国撤军的问题，中方的立场是，上海合作组织有关成员国在“9·11”之后积极配合国际反恐联盟在阿富汗的行动，为稳定阿富汗局势作出了重要努力。同时，它们也认为，现在的局势发生了重大变化。有关国家提出应明确使用有关地面设施和在其境内驻军的最后期限，中国对有关国家的意愿表示理解，认为他们的意愿值得重视和尊重。正因为如此，有关内容写进了《上海合作组织成员国元首宣言》。有关具体安排还有待于上海合作组织的有关国家同反恐联盟的有关国家进行商谈。


 东方评论员注意到，刘建超在回答中、可以说是“言简意骇”，完整地描绘了“要求美国撤军的前前后后”：第一，中国的立场是、与成员国的看法一样，即中国“...也认为，现在的局势发生了重大变化”；


●刘建超在“这一段”话中所给出的“暗示”

 第二，也是最重要的，就是“有关国家提出应明确使用有关地面设施和在其境内驻军的最后期限”、而“中国对有关国家的意愿表示理解”，并“认为他们的意愿值得重视和尊重”。最后、刘建超还强调“正因为如此，有关内容写进了《上海合作组织成员国元首宣言》”。

 显然，刘建超在“这一段”话中所给出的“暗示”、即“对阿富汗反恐结束的看法”与“限期美国撤离”的要求，都“非北京所提”的意思，是一目了然。


●与我们之前的一个判断“非常吻合”

 如果您一直在关注《东方时事解读》的话，那么，相信您对我们“之前所做的一个判断”应该有些印象：即我们认为“与其说是北京希望提出（要美国撤军）的、还不如说是莫斯科最希望提出的来得准确”、显然，“这个判断结果”与刘建超“今天的有意透露”、其内容是非常吻合的。


●北京“一不小心”“将这点抖露出来”，显然有着两层目的

 在东方评论员看来，北京之所以“一不小心”“将这点抖露出来”，显然有着两层目的：首先，这给了普京“天大的面子”，从而抬高了“原本在美国面前几乎无牌可打”的俄罗斯之身价。

 非常清楚、如果华盛顿“想赖着不走的话”，按北京的“透露”，可以清楚地看到，刘建超将北京的作用“描绘得”非常清楚，即在整个过程中不过是个“协从”。

 如此看来，华盛顿要想达此目的，那么，恐怕首先就得自放身段：在东方评论员看来，一直对“修理普京”不遗余力的布什、恐怕“首先就得请求普京的同意”才行。

 显然，在北京如此抬高莫斯科“关键作用”的情况下，尽管赖斯想在这次访华中“部分解决”“撤军时间的问题”，无疑也就碰上了北京“刻意保持低调”这枚“软钉子”。在东方评论员看来，北京的这种“低姿态”非常明智：第一，在向来将中亚视为自己后院的莫斯科看来，北京这样做自然是在强调自己无意与其争夺中亚主导权，这当然令其“非常受用”；

 第二，北京真正要争主导权的地方是在“东北亚”方向，显然，从这一层面来看，东方评论员认为，“中俄”决策层，似乎已经为各自在中亚、东北亚中担任的角色、有了“充分地默契”。

事实上，今天，在东方评论员看来，在刘建超主持的记者会上，不论是“问题”还是“回答”、其重点其实都是“朝核问题”，下面，在我们一起了解记者会的另一部分、有关朝核问题的节简内容后，我们将开始讨论今天的朝鲜问题。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
