# -*- org -*-

# Time-stamp: <2011-08-02 23:04:15 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

#+STARTUP: indent

* 2005年6月01日 星期三

** 专家：日采「文攻武迫」对中国进行战略试探

【香港大公报报道】中国著名军事战略专家王湘穗三十一日在接受该报记者专访时表示，日本正通过「文攻武迫」的战略步步紧逼中国，对中国进行一种战略试探。

王湘穗说，作为二战的战败国，日本在外交一向是「低调」的，但近一段时间以来，日本的外交政策发生了重大改变。日本正通过「文攻武迫」的战略步步紧逼中国，如日本政府正式宣称接管钓鱼岛上的灯塔、石原慎太郎登陆冲之鸟礁、登记若干居民钓鱼岛和冲鸟岛户籍、教科书、参拜靖国神社主权论、抨击中国「反分裂法」、渲染中国反日游行、批评中国民族主义等等都属于「文攻」；如美日安保条约包括台湾、反对欧洲对华售武解禁、台湾现役上将访日等等则属于「武迫」。日本的对华战略正在进行战略性的转变，表现出日本强烈地想成为政治大国的意向。

王湘穗告诉大公报记者，日本在战略上对中国的挑衅，其目标在于让美国遏制中国，进而彻底改变目前在西太平洋地区仍然存在的雅尔塔格局，改变日本在国际上的弱势地位。

日本通过激怒中国，让中国有一些过激的反应。一方面使日本民众产生对中国的敌意，造成一种危机感；另一方面，日本精心设计了两难问题让中国应对。也就是说日本在挑起一些事端后，如果中国无反应，日本则取得东海等实际利益；如果中国反应，则散布中国威胁论，怂恿美国出手，日本就能从中获利。「从这个意义上说，这是日本右翼或政客处心积虑、精心设计、有预谋有计划、有战略背景的诱兵之策，而不是偶发的矛盾。」

谈到中国目前所作出的反应，王湘穗认为尚属恰当。首先是回击日本的挑衅，坚持原则，同时又表现出顾全大局的愿望，并采取相应行动。比如胡锦涛的五点意见、吴仪访问日本。其次是有理、有力、有节，比如国务院副总理吴仪本来是出于改善中日关系的目的而访问日本，但由于缺少改善关系的气氛，特别是感受到这是日本布设的一个局，毅然取消会面。王湘穗形容吴仪，该见的人都见了，就是没有见日本首相小泉，既表达了对日本国民的友好态度，又回击了右翼势力，赢得了国内民意的支持，同时又向日本政府传达出中国对待中日关系严肃认真的态度。


【时事点评】在东方评论员看来，这篇幅报道侧重强调了两个方面，第一，近期、日本在战略上对中国的挑衅，是“日本右翼或政客处心积虑、精心设计、有预谋有计划、有战略背景的诱兵之策，而不是偶发的矛盾。”；第二，中国目前所作出的反应“尚属恰当”，特别是通过吴仪“如期访问”日本、但又提前中止访问行程，从而是“既表达了对日本国民的友好态度，又传达出中国对待中日关系是“严肃认真的”，从而既赢得了国际舆论的支持、又准确地回击了右翼势力”，对这“两点结论”，我们“深以为然”。

*** 这种观点可谓是“一针见血”

另外，我们也注意到，王湘穗先生还认为，日本在战略上对中国的挑衅，其目标在于让美国遏制中国，进而彻底改变目前在西太平洋地区仍然存在的雅尔塔格局，改变日本在国际上的弱势地位。在东方评论员看来，这种观点可谓是“一针见血”。

事实上，

长久以来，东方评论员也“一直在强调”日本热衷于东亚“全面出击”、“四面树敌”的深层原因、在我们看来，小泉政府这种“不合常理”、“挑畔四方”的主要目的、就是为了“全力打乱”目前这一套“东亚安全格局”，非常清楚，这套美国主导，中美联手压制日本政治、军事能力的东亚安全格局、正是脱胎于二战结束时确立的“雅尔塔格局”。


*** “翻案”也深藏着美国政府不可告人的企图心

在上周的一期点评中，我们曾经重点讨论了日本厚生劳动省政务官森冈正宏公然挑畔“国际良知”的、否定“远东国际军事法庭”的行径，在东方评论员看来，森冈正宏所声称的、对东条英机等日本十四名甲级战犯的历史性审判是“违法审判”、以及靖国神社内供奉的所谓甲级战犯不是罪人，只是战胜国单方面施加的卷标之类的“翻案”行径、
不仅深藏着日本政府不可告人的企图心，也深藏着美国政府不可告人的企图心。

*** “假亦真来真做假”的“辩解”与“辩护”

东方评论员注意到，尽管森冈正宏发言后，日本内阁官房长官细田博之对此是“急忙澄清”，并表示森冈正宏的言论“是对事实的错误诠释，与政府立场不同”，只是“一位众议员表达自己的想法”，而小泉纯一郎也在第一时间内赶快地跑出来为森冈言论降温，也公开地表示“他参拜靖国神社，并非向战犯致意，又说日本接受远东国际军事法庭作出的裁决，东条英机是甲级战犯”，如此等等。

但是，“这些辩解”是话音未落，小泉纯一郎所在的日本自民党的高层、就一个个地蹦出来为森冈正宏辩护，我们认为，这些“假亦真来真做假”的“辩解”与“辩护”，在东方评论员看来，恰到好处地验证了森冈正宏的这套言论、根本就是日本右翼所做的一次“精心策划之政治冒险”。


*** 华盛顿的“难得糊涂”

首席评论员指出，直到今天为止，我们都没有看到被森冈正宏“指责为”一次“单方面施加的卷标”行为的“负责人”--美国人，对此有什么“立场清晰”的正式反应，显然，这种“难得糊涂”、以铁一般的事实不可辨驳地证实了这么一点，那就是，美国和日本在这次“翻案”的闹剧中、是各自扮演了“各自的角色”。


*** “再论”森冈那天散布的“那套谬论”是一种“极其危险的信号”

我们曾经说过，森冈那天散布的“那套谬论”、其实是一种“极其危险的信号”，在东方评论员看来，它之所以“极其危险”主要就在于两个方面：

第一，东方评论员注意到，美国政府和美国主流媒体，对日本右翼的这一“对美国大不敬”、“翻美国当年主持、判决日本甲级战犯的东京审判之铁案”的行径、惊人地保持一致，总而言之，向来以民主、自由卫士自居、崇尚法治的美国政府、特别是美国主流媒体，对这一挑畔人类良知的野蛮行径，是既不主动谈及、更没有丝毫的谴责之意。

*** 华盛顿似乎在尝试将“这种翻案的可能性”、也当成一颗“胡萝卜”扔给日本

显然，在东方评论员看来，美国上下、从官方到媒体的“不闻不问”，只能说明一个事实，那就是，华盛顿似乎在尝试将“这种翻案的可能性”、也当成一颗胡萝卜扔给日本，挂在日本右翼的眼睛、鼻子前，让其“看着眼里馋，闻起来倍儿香”，从而驱使日本右翼“这头笨驴”继续往“联美反华”的道上走。


*** “翻案”的真实目的比这些“说得出口”的东西“更加不可告人”

第二，日本右翼的这一“翻案”，表面上看全是冲着“远东军事法庭、东京审判”而来的，然而，在东方评论员看来，其真实目的比这些“说得出口”的东西“更加不可告人”。

首席评论员认为，日本为甲级战犯“翻案”充其量也只是手段而已，是为了推翻“东京审判”对日本军国主义、和发动侵略战争的甲级战犯罪行之“历史定论”而必须施展的手段之一。


*** 日本右翼“更深一层目标”

然而，在我们看来，日本右翼想推翻“东京审判”的“历史定论”也只不过是为了达其“更深一层目标”的手段。东方评论员认为，日本右翼“更深一层目标”就是全面推翻“现行的、日本作为一个给其他国家带来深重灾难的法西斯战败国、所必须严格遵守的各种国际法、和日本的和平宪法”。

第三，只要我们稍稍梳理一下当年建立“远东军事法庭”的“法理基础”、稍稍整理一下“东京审判”之后、日本被强制遵行的一系列国际、国内法，我们就不难发现，《开罗宣言》、《波茨坦公告》正好构成了战后日本“必须严格遵守”的国际法基准，与中国利益紧密相关的是，《开罗宣言》承认台湾等被占土地是中国的固有领土，并规定日本必须将其归还中国。

而《波茨坦公告》第六条则规定：“欺骗及错误领导日本人民使其妄图征服世界之威权及势力，必须永久剔除。”第十条规定：“对于战争人犯，包括虐待吾人俘虏者在内，将处以法律之严厉制裁。”


*** 美国因为一已私利，事实上从一开始就为日本“翻案”“留有后门”

显然，《开罗宣言》强调了台湾是中国的领土，而《波茨坦公告》则强调了“必须铲除日本军国主义”的要义，然而，由于美国出于要将日本打造成一枚遏制前苏联、牵制中国的战略棋子的“利益私心”，对《开罗宣言》和《波茨坦公告》并没有彻底执行。

在东方评论员看来，美国决策层因为一已私利，事实上从一开始就为日本“翻案”“留有后门”。我们认为，这其中最典型的事情就是保留了日本的天皇制，从而让日本的天皇--裕仁，这个发动并经历了日本侵略战争全部过程、并负有核心责任的战争罪犯，在美国的庇护下、逃脱了《波茨坦公告》、以及据之建立的“远东军事法庭”的制裁，从而为日本军国主义复活“预埋下了伏笔”。


*** 一句“要成为普通国家”，实际上就是砸碎捆在日本身上这些“条条框框”的“代名词”

而美国当时为日本制定的“和平宪法”，则彻底摆脱了日本战前确立军国主义体制的《大日本帝国宪法》的影响，其中“放弃战争”的第9条规定：日本“永远放弃以国权发动的战争，武力威胁和行使武力作为解决国际争端的手段”，“为达此目的，不保持陆海空军及其他战力，不承认国家之交战权”。

不难看出，日本右翼之所以“口口声声”、以近乎“悲情”的方式哭着喊着要成为一个所谓的“普通国家”，就在于它的身上有着这些“条条框框”、阻止了他们复活军国主义的美梦。而一句“要成为普通国家”，实际上就是砸碎捆在日本身上这些“条条框框”的“代名词”。


*** 日本争取成为“普通国家”的过程，实际上就一个全面挣脱“国际法”约束的过程


东方评论员认为，甚至可以这样说，日本争取成为“普通国家”的过程，实际上、从来就是一个日本政治人物企图“毕其全功于一役”、全面挣脱《开罗宣言》、《波茨坦公告》、日本“和平宪法”约束的过程。

事实上，如今日本"和平宪法"的许多内容已名存实亡，在东方评论员看来，如果北京在这一轮与日本、美国的全面较量中、不能让日本社会“彻底警醒”，那么，日本修宪只是时间问题。

然而，日本对"和平宪法"的违背乃至最终抛弃，是否就一定将为日本“明目张胆地”走向世界军事大国、全面成为一只强权“扫清全部障碍”呢？在东方评论员看来，恐怕“不一定”！

*** 美国新保守主义者在拟定美国战略时，也清楚一个事实

美国新保守主义者在拟定美国战略时，也清楚一个事实，既，不论现在日本的政治人物多么听美国的话，但是，最终影响日本对外政策的基点，仍然是日本政治人物眼中看得见的“国家利益”。

显然，在日本右翼的眼里，最大的国家利益似乎就是将日本强大的经济实力、转化为“强大的、但一定是独立的政治、军事能力”，而就军事能力而言，当首推发展出一只足以挑战美国海军的海上军事力量，从而确保将自己的海上生命线从美国手中拿回来。

东方评论员认为，日本的“这种国家利益”当然与美国的国家利益相在着“本质的冲突”。因此，在白宫决策层看来，是绝对不能容忍日本右翼在掌握政权之后，去重建一个极具野心的、日本军国主义政权、挑战美国的海上霸权的。

*** 华盛顿已经开始在背后施展一系列手段、以求能“遥控”日本国内政局


我们知道，在日本右翼的骨子里，“大东亚共荣圈的霸权梦”就一直没有“因投降而彻底消失过”。

东方评论员认为，我们可以清楚地看到，就在美国继二战“用原子弹”这个大规模杀伤性武器、在太平洋战场上打败了日本“用炸弹对美国发起的进攻”之后，日本企图用军事力量称霸的能力被彻底消灭了，到了90年代初，华盛顿又用“美元汇率”这个金融武器、再次打败了日本“用商品”对美国发起的“第二次攻击”，于是，日本企图用经济力量称霸的“现实性”也几乎被打没有了。


*** 日本人对美国的“美元武器”最终得以“心领神会”

事实上，日本人对美国的“美元武器”最终得以“心领神会”、是在97到98年的亚洲金融风暴中遭受到欧美的最后一击：在日本经济泡沫最终被华盛顿经济管理层挤破之后，日本人跑到东南亚投资，并想以此为生产基地，去与欧美周旋，结果，仍然遭到“美元汇率”这一金融武器的暗算、经此一役，日本人终于明白了是什么回事？原来，美国人用巨大的金融资本、借着“美欧”制定的金融游戏规则，轻而易举地将日本人在产业方面赚的钱、巧妙地给掏走了一大半。


实际上，也正是日本于军事和经济上两次都败于美国，特别是近十多年来，日本经济被美国强力打压、陷入十年衰退之后，华盛顿已经开始在背后施展一系列手段、通过左右日本经济政策、去调控日本右翼的活动空间，以求能“遥控”日本国内政局。


*** 小泉的鼓吹的“大胆而柔软的改革”，也终于从“雄心壮志”拖成了“牛皮哄哄”


事实上，小泉政权是在2001年上台的，也是在97年亚洲金融风暴之后、日本经济陷入最艰难的时候上台的。日本国民是在热盼小泉纯一郎拿出“治国良方”、拯救日本经济的期盼中将小泉纯一郎扶上台的。

在东方评论员看来，他上任以来打出改革旗号，开始似乎“挺得人心”，然而，美国与欧洲联手、压日元升值的“广场协议”、所造成的“后遗症”仍然将日本的经济拖得越来越糟，在这种情况下，小泉的鼓吹的“大胆而柔软的改革”，也终于从“雄心壮志”拖成了“牛皮哄哄”。

于是乎，日本国内各路人物就“如何拯救日本急剧衰落的经济”陷入了“长时间的激烈争吵”。据我们观察，争吵的双方不是外人，就是自民党内的主要派别和自民党的小泉政府。而争吵的内容也不是别的什么，而就是除了在外交政策上听美国人的之外，是否在经济政策上也要听美国人的？


*** 美国人“痛失”了一次掌握日本经济命脉的大好机会

在我们看来，“争吵”的根本原因是日本是否要继续“按美国人开的药方”拟定经济政策，而“直接的导火索”则是小泉政府曾经提出了一项“按照美国的方式对日本金融实施大手术的计划”。

东方经济评论员就认为，按照这个计划，日本的主要银行“极可能”被迫被国家接管，由国家出资加速处理呆帐。

而所谓的“处理呆帐”又是个什么玩意呢？事实上，简单一句话，就是不再对那些没有没有偿付能力的公司贷款，停止日本人称之为“延命政策”的金融政策，强迫这些企业倒闭。

在东方经济评论员看来，小泉政府当时提出的这项计划，实际上没有考虑日本的发展动力并非金融而是由金融支持的产业。显然，我们认为，在当时日本的经济状况下、如果日本果真“按美国人开的药方”治经济疲软的话，那么，由于该政策会造成大量企业破产，员工失业，从而毁掉日本经济的“真正动力”，这样，失去动力的日本经济、又反过来会冲击坏账高筑的日本银行、从而令日本金融雪上加霜，最终的结果、“很可能”是日本的许多银行、今天恐怕都已经被美国金融世头“廉价地收到了自己账下”。

就在日本双方都在叫骂的时候，日本的经济这时正好借助中国经济的强劲增长、而慢慢有了起色，小泉纯一郎的这一套“美式金融政策”终究没有实行，从而让美国人“痛失”了一次全面渗入日本经济“核心环节”、掌握日本经济命脉的大好机会。



*** 在调控日本政治局面的能力上，美国远没有达到“随心所欲的”地步

在东方评论员看来，失去这一“极好机会”的美国、在调控日本政治局面的能力上，虽然远没有达到“随心所欲的”地步，但是，从其“紧密地配合着”日本右翼、将日本社会一步步地导入右倾化的这一过程来看，华盛顿对日本社会的操纵能力，实际上与日本右翼力量的壮大成正比。

因此，在美国决策层的眼里，在如何“增强对日本政局的调控能力”的问题上，适当增强日本右翼势力是一个非常有效的办法。而日本右翼势力的消涨，在一定程度上与日本国内经济状况有着莫大的关联度。真实的情况是，自90年代初以来，美国将日本的经济打入十年衰退期，客观上为日本右翼坐大提供了一个极好的机会。


*** 欧美的确想“再次刮起”97年亚洲金融风暴，但是困难太大

显然，美国的所“痛失”的这次大好机会，就是因为日本将经济依托在中国、将中国这个欧美决定不了其政策取向的“具独立决策权、且也有庞大经济容量的国家”做为投资基地、去与欧美周旋。

欧美的确想再次刮起97年亚洲金融风暴，但是困难太大，因为中国与日本97年时所依托的东南亚国家、有着本质的不同。可以说不论是政治、军事上都可以独立行事，就是中国的经济规模也是欧美想以在再刮一场金融风暴的一大困难，何况还有一个“相对独立”的资本市场。因此，如何让中国在经济政策上为欧美挤压日本经济开方便之门（这也将损害中国的经济），就成了欧美此次联手在经贸问题上对中国施加压力的深层原因。当然了，保护欧美的纺织业，不过是表面上的理由而已。


在东方评论员看来，这也正是欧美近来联手在纺织业、人民币汇率问题上“一起”对中国施加压力的根本原因所在，在欧美决策层看来，将中国最有利可图的纺织业拿出来，与人民币放在一起说事，成功的机会就大得多。

然而，东方经济评论员认为，在现阶段内，由于欧美的经济都不稳定，也都遭遇到了困难，因此，欧美“未必想让”大体上与自己经济互补的中国经济垮下去，但是，却绝对想将与自己全面竞争的日本经济“再次重创一次”。就美国而言，如果能通过中国的配合，再将将日本企业重创一次，不仅对美国企业有帮助，也对美国再次掏出那份未完成的“日本经济药方”提供了另一次机会、还也对日本右翼继续增强影响有诸多助益，真可谓是何乐而不为？

事实上，在我们看来，中国突然在贸易上摆出的强硬姿态，不仅出乎欧美的意料，实际上也出乎日本的意料。也正是中国有了这种“出奇的强硬”，撤销了准备于今天将开始实施的纺织品出口加税政策，也就引起了各方一系列政策调整。

我们先来看看日本的政策反应，之后，东方评论员将继续这个话题。

** 日本官房长官指日本无意探勘东海油气资源

【东京消息】据报道，日本内阁官房长官细田博之今天在东京例行记者会表示，中国已在东海有主权争议地区钻探油气资源，日本并无计划在东海探勘油气。
日本与中国因东海海域主权及油源屡屡出现争议，日本希望中国能停止钻探，并认为中国将从日本领域抽取天然气。

中国昨天已拒绝停止钻探的请求，转而建议二国在北京就合作探勘展开谈判，藉此解决纷争。

根据日本研究显示，东海蕴藏最多达2000亿立方公尺的天然气，完全仰赖石油进口的日本与经济高速成长的中国为确保工厂持续运转，家庭用油不至匮乏而展开东海油源争夺战。



【时事点评】显然，在我们看来，如果中国顶不住人民币升值的“这种压力”，那么中国经济当然可能遭受重创，但是日本的经济很可能会比97年亚洲金融风暴还要惨。

在我们看来，北京有必要寻找一种办法，在调整人民币汇率政策之外、以一种经济政策的方式，将这种来自欧美的外在威胁、尝试直接转移到日本头上，从根本上反击美国和日本右翼联手对中国的挑衅。

*** 与欧美拉开架式，准备开打贸易战，就是一种尝试

在东方经济评论员看来，与欧美拉开架式，准备开打贸易战，就是一种尝试。在我们看来，日本人似乎肯定中国充分吸取了日本签下“广场协议”的教训，而不可能让人民币在强压下去升值。

我们认为，中国与欧美之间打贸易战，恐怕谁都打不起，犹以欧美更甚、因为被欧美指责为设限对象的，许多都是欧美自己的投资、并在中国赚取大量利润的企业，既然这样，在中国已经表明态度之后，欧美也就有可能“另僻他途”，直接从日本身上打主意。


*** 日本国内政治势力、日前对小泉纯一郎的反弹力度已经增强

在我们看来，日本国内政治势力、日前对小泉纯一郎的反弹力度已经增强，其中，以与日本自民党联合执政的公明党党魁神崎武法的反弹最为引人关注，他说：“虽然在参拜上，每个人都有自己的信条。但是，为了国家利益，小泉纯一郎首相必须得自我控制。“我并不很喜欢说这会破坏联合执政的话，不过，要指出的是，若要破坏这种联政关系，或许只需要一瞬间。”

最后，这位公明党党魁还威胁道：“我并不很喜欢说这会破坏联合执政的话，不过，要指出的是，若要破坏这种联政关系，“或许只需要一瞬间”。”

在东方评论员看来，我们又一次看到了“或许只需要一瞬间”、看来胡锦涛主席的描述中日关系“有可能毁于一旦的”“砌墙论”，“似乎”也感染了这位公明党党魁“说话语气”。


而小泉政府在中国一连串攻势之下，也终于在东海问题上的立场已经有所软化，这种软化则表现在日本公开表示“近期没有计划让日本企业勘探、开采东海资源”。

东方评论员认为，这与中国摆明态度“绝不在压力之下放开人民币”、并为此不惜与欧美拉开架式，准备开打贸易战大有关系。

*** 北京从经济角度去处理与欧美、日本的政治问题，应该有相当的收获

首席评论员就认为，就目前中国目前“所作出的各种反应”而言，的确是可圈可点，在我们看来，北京从经济角度去处理与欧美、日本的政治问题，应该有相当的收获。显然，这样做的好处是，既然它是种尝试，那么，可以期望的是，如果成功，它既可以瞄准日本的要害--日本经济、去回击日本、美国的挑衅，同时，又可以在坚持原则，充分表现出中国“顾全大局的愿望”。

在一段日本共同社的新闻报道之后，东方时事评论员、东方经济评论员将继续就美日联手“翻案”，中欧美准备开打贸易战之间的“联动”话题、继续展开“共同讨论”。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
