# -*- org -*-

# Time-stamp: <2011-08-04 00:23:10 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

*  2005年6月09日 星期四



** 朝鲜称拥有并正在制造核武要求核国家待遇

【汉城消息】据韩国联合通讯社报道，朝鲜外务省副相金桂冠表示，目前朝鲜正在继续制造核武器。另据美国ABC电视台8日晚在大型新闻节目《今晚世界新闻》中报道，在朝鲜接受记者伍德勒普的采访时，金桂冠承认正在继续制造核武器的事实，但是对于是否拥有可打击美国的导弹的提问，做出不置可否的反应。

在此次采访中，当伍德勒普问及“朝鲜是否拥有核武器”时，金桂冠回答“是”；而对于拥有几枚核武器的提问，他表示“有足够的核武器来应付美国的攻击”。

金桂冠表示：“具体数字秘密。”当被问及“是否正在制造更多的核炸弹”时，他回答“是”。

伍德勒普指出，朝鲜还没有进行核试爆，许多分析家不能确定朝鲜拥有核武器。

伍德勒普报道朝鲜在过去几年进行远程导弹发射试验的事实之后，介绍了就朝鲜的导弹能力采访金桂冠的内容。

当被问及“朝鲜是否拥有可以射到美国本土的导弹”时，金桂冠没有直接回答，只是重复“我们制造导弹的目的不是为了进攻美国”。

朝鲜要求美国给予有核国家待遇

另悉，在朝-美6日的接触中，朝鲜要求美国承认其是“有核国家”，并给予相应待遇。

据《朝日新闻》8日发自华盛顿的报道称，朝鲜却没有提出将六方会谈转变为“军控会议”这一此前曾提出过的主张。

今年2月10日，朝鲜外务省发言人发表声明称“朝鲜已经拥有核武器”，但直接通告美国已成为“有核国家”，并要求给予相应待遇，还是第一次。

据该报称，美国认为朝鲜的这一要求的目的在于迫使美国认可拥有核武器的事实，并在今后与美国的交涉中得到更多让步。因此，美国不会接受这一要求。

据北-美关系消息人士称，朝鲜驻联合国大使朴吉渊向到访朝鲜驻联合国代表部的美国务院负责朝鲜问题谈判的特使约瑟夫•德特拉尼明确表示，美国应该给予朝鲜核国家的待遇。但是，没有提及具体要求的待遇。

据《朝日新闻》报道，美国政府和华盛顿的外交家普遍认为，朝鲜“似乎放弃”将六方会谈转变为军控会议的此前的主张。

据5月底曾访问过朝鲜的斯坦福大学教授约翰•路易斯称，朝鲜方面主张六方会谈不应单方面要求朝鲜放弃核武器，有必要消除美国在朝鲜半岛的“核威胁”。

据该报分析，“有核国家待遇”是指将朝鲜视为同美国平等的有核国家，以在六方会谈中讨论军费问题。从最终目的来看，如果朝鲜弃核，美国也应该裁减驻韩美军，并从核先发制人打击的名单中删除朝鲜。

据悉，美国政府内部有分析认为：“朝鲜要求与巴基斯坦享有同等待遇。”

虽然巴基斯坦曾强行进行核试验，并扩散核技术，但自发生911事件后，其与美国的关系反而得到了巩固。


【时事点评】在东方评论员看来，朝鲜在这个时候“要求”与巴基斯坦“享有同等待遇”，其目的恐怕有两点：第一，表面目的在于迫使美国认可其拥有核武器的事实，可以肯定的是，美国是绝不会接受这一要求；

*** 朝鲜的“真实意图”

这样，朝鲜的第二个目的也就出来了，即其真实意图、则在于通过这一“美国根本就不可能公开答应的要求”、意图“以攻为守”，而在今后与美国的交涉中得到更多让步。

在朝核问题上，东方评论员一向认为，自布什几年前上台以来，立刻调整了其前任克林顿政府的全球战略，实行新保守主义者为他准备的一套“布什主义”，因此，从那个时候起、布什不仅“没有心情”、也根本就认为“没有必要”去彻底解决朝核问题，反而将朝鲜核问题当成了一张“可松可紧”的牌来打。


*** 为何布什认为“没有必要”彻底解决朝核问题？

其实，布什主义“如此对待朝核问题”的道理是非常简单的：一个稳定、缓和的朝鲜半岛，根本就与美国现行的、先取中东、再取中亚，从而彻底割裂欧亚大陆上、所有具有与美国争夺全球利益大国之间的战略协调能力的这一套全球战略、根本就“不相符”。

因此，对于“六方会谈”，除了韩国政府想借此暗中继续搞旨在“共同发展朝韩经济”的“阳光政策”之外，可以说在开始的时候，各方都一直是不太重视的，因为谁都知道在六方会谈上不会达成什么协议，也不可能达成协议，这是美国现行的全球战略所决定的。


*** 今天，华盛顿解决问题的“紧迫感”却有了180度的“大转弯”

我们知道，朝核问题“六方会谈”中断了近一年，可以说在这一年间，美国的欲彻底根除朝鲜核能力的“朝核政策”没有根本性转变、但是，到了今天，华盛顿解决朝核问题的“紧迫感”却突然有了一个180度的“大转弯”。


*** 华盛顿的这个“大转变”、有一个非常明显的转折点

在东方评论员看来，华盛顿的这个“大转变”、如果仅仅从“时间”上看的话、是有一个非常明显的转折点的，这就是中国的“春节”。而也就在今年春节的年三十、“初一”，日本分别做了两件事情。

首先，在大年三十这天，日本众院以全票的方式通过法案：世博期间台湾访日游客免签证。显然，在东方评论员看来，日本政府这是在刻意强调：它“不想”消除自己让李登辉访日带来的政治影响、而代表日本社会的日本议会、也不打算表示什么改善“中日关系”的“诚意”。

其次人，就是中国大年初一的这天，日本又突然在钓鱼岛主权问题上挑畔中国、将日本的政治团体在钓鱼岛上设置的灯塔、作为日本国家财产由海上保安厅接手守护与管理，并声称“有关手续正在办理之中”。

最值得注意的是，在中国提出强烈抗议之后，日本外相町村信孝当天就公开抛出“两个强硬观点”：第一，中日不存在钓鱼岛领土的问题、日本政府接管钓鱼岛灯塔是极为内政性的措施，轮不到中国说违法或者无效。

第二，这位以强硬著称的日本外相“不仅还高姿态地要求中国冷静”、反而“别有用心”的声称：中国简直是在利用钓鱼岛问题引发国内人民的仇日情绪，是在整个太平洋地区发出“仇恨”的讲话。

显然，日本在大年初一突然在钓鱼岛上“闹事”、并以中国人民的情感作“标的”、并将北京的立场渲染成是在整个太平洋地区发出“仇恨”的讲话，在东方评论员看来，日本的这种做法，无论是从时间的选择、还是在事件性质的敏感度上，以及“事后辩解”的“遣词用句”上、都是在“有意”以极端的手段挑衅北京，完全是有预谋、有计划的行动。

*** 美国怂恿日本搞的“这一出”、主要目的有两个

现在，时间已经过去4个多月了，这中间的许多事实证明，当时、在日本进一步挑衅中国的背后，就是华盛顿在“一手策划”、而美国怂恿日本搞的这一出，其主要目的有两个：

第一，借钓鱼岛争端事实上是“中、日、中国台湾”三方间的争端，从而寻机制造卖点、努力将钓鱼岛问题国际化。而在东方评论员看来，他们这样做的目的，就是要“扯出萝卜带出泥”，意在警告“台湾问题也可以这样的国际化”，并以此对北京施加压力。

第二，对华盛顿而言，也是最重要的，就是在有意借日本武力“保卫钓鱼岛”之名、打造“建立美、日、台”军事同盟之实；而台湾的陈水扁、李登辉对此自然是心领神会、当时也是闻风而动、积极配合、立刻声称有必要举行“三方会谈”、以解决争端，如此云云。


*** 东亚问题，在某种程度上讲，早已经简化成了一个“东亚核军备竞赛问题”

上面的“如此这般”，都是美国、日本、台独势力的如意算盘，然而，在离美国伙同日本在钓鱼岛上、拿着那根“灯塔”做了一回文章“还没有20个小时”，有意思的是，与北京关系密切的朝鲜、也在朝鲜半岛上扔出了一枚“即时炸弹”：公开宣布“朝鲜已经有核”，并宣布“无限期退出六方会谈”，除此之外，平壤还“首次公开强调”，说朝鲜“已制造了用于自卫的核武器”来应对美国的敌对政策。

不仅如此，也是在大年初二，在中东方向，与北京关系也不错的伊朗，也“向华盛顿发出了措辞强硬的声明”，当时，伊朗总统哈塔米就坚定地表示，伊朗不放弃核能开发计划，并同时声称“任何敢以此为借口入侵伊朗的国家都将陷入“烈焰熊熊的地狱””。

众所周知，表面上，角力东亚的是“中美日”三个大国，但实际上，真正玩牌的却是北京和华盛顿两家。如此一来，中美间的许多问题、不论是“日本问题”、还是“台独”问题、甚至是朝核问题、以及主要的东亚问题、比如说：韩国最为关心的朝鲜半岛的统一问题、中国、俄罗斯、韩国非常在意的东北亚经济一体化问题、还有中国、美国极为重视、日本急于颠覆的东亚安全框架问题等等，在东方评论员看来，主要的东亚问题，在某种程度上讲，都简化成了一个“东亚核军备竞赛问题”。


*** 中美间在东亚问题上的一系列“交手”、都在围绕着“两个进程”运转


事实上，从那时开始，中美间在包括台湾问题、朝核问题、日本定位等东亚问题上的一系列“交手”、都在围绕着“两个进程”运转，在东方评论员看来，这“两个进程”分别就是华盛顿手中操纵的“台独进程”和北京手里控制的“朝核进程”。

在我们看来，几个月来的事态发展也已经证明，中美间在中东问题上，特别是伊朗核问题上的立场，不可避免地与“朝核问题”“将如何解决”挂上了钩。

东方评论员认为，仅从政治和安全的角度上讲，这些简单“列举出来”的、“剪不断、理还乱”的“错综复杂”、恐怕就是布什“一而再、再而三”强调中美关系“太复杂”的“原因中的几个”吧。


在我们继续讨论、展开我们的观点之前，我们再来看一则消息。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 中国在朝鲜半岛无核化问题上立场明确而坚定

【北京消息】中国外交部发言人刘建超今天下午在此间例行记者招待会上说，中国政府在朝鲜半岛无核化问题上的立场是明确而坚定的。中方历来主张朝鲜半岛无核化，希望有关各方向这一目标继续做出建设性努力。

今天下午，来自美国、法国等国的记者对朝核以及六方会谈重启问题表示出很大的关切。在回答有的问题时，刘建超指出，尽早重开六方会谈是有关各方和国际社会的共同愿望。近来，朝美双方两次在纽约进行了接触。朝方也表达了重返六方会谈的意愿。中方对此感到高兴，希望有关各方继续做出建设性努力，推动六方会谈得以尽快恢复。

刘建超说，中方一直非常明确地主张朝鲜半岛实现无核化。这也是六方会谈的根本目标。参加会谈的所有各方都主张六方会谈的宗旨和最终目标就是实现半岛无核化。

“当然，这个问题非常复杂，解决起来有极大困难。”刘建超表示，“中方希望能够尽早恢复会谈。有关各方的关切、问题和各种各样的考虑都可以在六方会谈的框架内提出来，由各方通过协商逐步达成共识加以解决。”

刘建超说，从朝核问题发生的第一天开始，中方就认为，解决这样一个问题将是一个长期的、非常艰巨的过程，可能会出现这样或那样的波折。但是，有关各方都一再重申，要朝着实现朝鲜半岛无核化的目标共同努力。

“有了这样的目标，再加上大家的努力，不管这个问题多么复杂、多么艰巨，只要大家能拿出诚意、释放善意，同时有务实、建设性的态度，这个问题今后会逐渐得以解决。”刘建超表示，“六方会谈进程也会不断地、哪怕有时候会比较缓慢地向前推进。”

在回答记者相关提问时，刘建超说，中朝之间就双边广泛的问题也包括朝核问题进行着不断地接触和磋商。至于近期是否再派员去朝鲜，现在还没有这方面的消息。


【时事点评】东方评论员认为，外交部发言人的这次答记者问，在朝核问题上，可以说有“三个看点”：第一，刘建超说，“中方一直非常明确地主张朝鲜半岛实现无核化。这也是六方会谈的根本目标”；

*** 刘建超在那里说来说去，分明是在“诉苦”、“打预防针”

第二，刘建超说，“中方希望能够尽早恢复会谈。有关各方的关切、问题和各种各样的考虑都可以在六方会谈的框架内提出来，由各方通过协商逐步达成共识加以解决。”

第三，建超说，从朝核问题发生的第一天开始，中方就认为，解决这样一个问题将是一个长期的、非常艰巨的过程；并同时认为“不管这个问题多么复杂、多么艰巨，只要大家能拿出诚意、释放善意，同时有务实、建设性的态度，这个问题今后会逐渐得以解决。”“六方会谈进程也会不断地、哪怕有时候会比较缓慢地向前推进。”

首先，笼统地讲，就上面的“三个看点”而言，首席评论员就认为，其实、刘建超在那里说来说去，事实上“始终都是在强调”这么一句话，那就是“这个问题非常复杂，解决起来有极大困难。”，不难看出，北京这分明是在“叫苦”、也是在“打预防针”、意在“通告”方方面面、“不要想着一夜能解决所有问题”。


*** “成双成对存在着”的“两个问题”，是中美在东亚“够勉强合作”的基础

另外，在东亚这个地方，还有一个“非常复杂，解决起来有极大困难”的问题、这就是台湾问题，在我们看来，在“台独问题”没有让北京“完全放心”之前，“朝核问题”也注定不会出现让华盛顿“完全放心”的解决方案。显然，我们认为，这两个问题，不仅“互相牵扯”、而且还都具有“非常复杂，解决起来有极大困难”特点。

在东方评论员看来，“成双成对存在着”的这“两个问题”，正是北京和华盛顿眼下还能“够勉强合作”、让整个东亚暂时维持稳定的基础。


*** “朝核问题”何以对美国如此重要？

台湾问题对中国的重要性，我们不需多言，而“朝核问题”对美国的重要性，则表现在它最终“处理的好与坏”，将直接关系到日本和韩国、这两个美国在西太平洋安全架体制的“最重要锚点”的稳定。

事实上，美国在亚洲分别以日本和韩国这“两个锚点”分别构筑了“美日”、“美韩”军事同盟，在华盛顿决策层的眼里，“美日”、“美韩”军事同盟是相辅相成为一个完整的“美日韩”军事同盟的，然而日本与韩国、朝鲜间的关系、客观上又使得“美日”、“美韩”军事同盟有种相互平衡、相互制约的因素在里面。


*** 北京“默认”“朝鲜宣布有核”、华盛顿第一次有了妥善解决“朝核问题”的“紧迫感”

今年春节之后，由于北京“默认”“朝鲜宣布有核”、并有意打“东亚核竞赛牌”，相比以前而言，“朝核问题”“严重恶化的可能性大大增加了”。而因有个日本因素在里面，华盛顿第一次有了妥善解决“朝核问题”的“紧迫感”。


*** 日本“四处出击”，其“言行举止”充分证明了日本政府的企图心

而日本的意图也非常明显，几个月来，日本在东亚是“四处出击”，攻击中国、挑战韩国、寻畔俄罗斯、其“言行举止”充分证明了日本政府的企图心，即：它想借着华盛顿让其出头挑畔、牵制中国之机，有意达成三大目的：

第一，通过在独岛主权、和历史问题上挑畔韩国，迫使韩国做出激烈地反应，从而寻机打破“美日”、“美韩”军事同盟间的平衡；

第二，再通过刺激朝鲜、中国、在中美间深化对立、进一步促使朝核问题恶化、直到失控。从而造成东亚核军备竞赛的局面，最后与朝鲜、韩国一道、一举跨入核门槛、颠覆东亚安全框架、摆脱中美联合压制的局面。

第三，通过与周边国家、特别是与中国、俄罗斯这两个核大国的争端，来体现一种以“常规军力”挑战“核大国”的“悲情”，日本右翼是不会忘记这一点的，即，日本挑战争的韩国也有朝鲜的核武器撑腰。显然，日本之所以想制造出这种“悲情”，就是在为“促使朝核问题恶化、直到失控。从而造成东亚核军备竞赛的局面”而做准备。

显然，这种“悲情”拿到美国人面前，就成了日本“进一步卖力”的“前提条件”，如果将来拿到日本社会面前，就成了修改“和平宪法”、充许日本“核武化”的敲门砖。

*** 刘建超其实是在“放录音”、“录音带”似乎是“农历正月”里录下的

其次，如果我们对“三个看点”一一解读的话，那么，我们就不难发现，刘建超其实又是在“放录音机”、而且“录音机”里的“录音带”上的内容似乎就是2月份“农历正月”里录下的、孔泉的“讲话要点”。

我们知道，早在2月份的时候，也就在朝鲜“宣布有核武器”之后，中国的外交部“好像是放了假似的”，直到“过了近一个星期的时间”之后，才正式通过外交部记者会发布新闻、“标明”中国的“正式立场”的。


*** 孔泉当时所强调的“现有基础”经过几个月后，“越发体现出其重要性来”

事实上，孔泉当时的讲话，也是有几个要点的：其中最重要的是，当时孔泉正式“透露了”中国政府对朝核问题解决策略上的思路：即，“对半岛核问题及朝鲜方面合理的安全关切，应在现有基础上，通过六方会谈机制，通过各方的不懈努力，特别是当事方朝鲜和美国显示诚意，表现灵活，寻找彼此都能接受的解决办法，最终实现半岛无核化”。

显然，在东方评论员看来，孔泉当时所强调的“现有基础”这个词，在经过几个月的“坎坎坷坷”之后，“越发体现出其重要性来”，我们认为，孔泉当时所说的“现有基础”，指的就是“朝鲜宣称已经有了核武器”这个“现有基础”。


*** “朝鲜宣称已经有了核武器”还不是“现有基础”的全部

然而，在北京看来，“朝鲜宣称已经有了核武器”还不是“现有基础”的全部，众所周知，在半岛的南边，去年9月份的时候、韩国也曾经闹过“核风波”，时间是去年9月份，当事人也不是别人，也是华盛顿。

因此，要彻底解决朝核问题、那么这个美国人“自己挑起来”的、日本在旁边“心有所盼”的、“韩国核浓缩铀”的事儿、是否也必须拿到“六方会谈”中、去一揽子加以解决呢？


*** “朝核问题”“如何定义”，本身就是一个战略问题、而非一个“战术问题”

在东方评论员看来，大家现在对“半岛核问题”的“朝鲜核问题”之间的“本质不同”应该有很深的印象，直到几天前，华盛顿也首次地触及了“半岛核问题”这个它之前一直回避着的概念，而朝鲜则不仅多次强调“朝鲜半岛核问题”、其中有一次甚至“已经往朝鲜半岛核问题的圈圈内划进了日本核能力的问题、并声称要一并解决之”。

由此可见，围绕“朝核问题”的“如何定义”，这本身就是一个战略问题、而非一个“战术问题”。


*** 北京“态度鲜明”，朝鲜才能够在“宣布已经有核”的“现有基础”之上、继续做了两件事

也就是说，当时，孔泉就已经在“暗示”这样一种立场，即：尽管“中方一向所坚的持朝鲜半岛无核化”、但并不认为“朝鲜宣称已经有了核武器”已经破坏了“中美日韩俄”共谋的半岛无核化之“大业”。

因此，在东方评论员看来，也正是有了北京的“这么个鲜明的态度”，朝鲜才能够如此这般地、在“宣布已经有核”的“现有基础”之上、敢于继续做两件事：第一，去进一步要求“将美国在韩国部署核武器的问题、甚至于日本有核潜力的问题、一并考虑在内”。

事实上，这一步，就在4月份，美国在背后支持日本在东海问题上、以对日本企业单方面发放勘探许可证的手段、来严重挑畔中国底线的时候，朝鲜就已经“公开地这样做了”。


*** “此时”和“彼时”，竟是“如此地似曾相识”！

第二件事，也就是今天朝鲜外务省副相金桂冠所表示的：“目前朝鲜正在继续制造核武器”，并正式要求“美国给予有核国家待遇”。

另外，孔泉当天讲话，还谈到了一个“困难”，其原话是“由于问题的复杂性，谈判的进程一直是曲折而艰巨的，所取得的每一步进展都需要各方表现出极大的诚意、耐心、灵活和冷静”。

在我们看来，显然，孔泉当时强调的是“问题的复杂性”、“谈判的进程的艰巨性”，并认为“所取得的每一步进展”“都需要各方表现出极大的诚意、耐心、灵活和冷静”，这与刘建超今天所说的，“第三个要点”说的是一回事。

事实上，如果我们对比一下四个月前的台海、朝核局势，看看北京和华盛顿现在分别在朝核、台湾问题上的角力，就不难看出，“此时”和“彼时”，竟是“如此地似曾相识”！

在我们回到这个话题之前，再来读一份新闻摘要。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com



** 美国促大陆与台湾进行实质对话不预设前提

【华盛顿消息】据报道，美国国务院东亚事务助卿希尔七日敦促两岸应在不预设前提条件的情况下展开实质对话。他并重申，美国关切中国的军力扩张。

希尔也提到，中国正对台湾采取两手策略，一方面孤立台湾、不愿宣布放弃对台用武；一方面吸引台商，鼓励经济整合，使大陆对台湾投资人更据吸引力。

美国国会参议院外交关系委员会东亚小组七日就中国崛起对美国的影响举行听证会，希尔应邀在听证会中报告备询。

在答覆东亚小组主席议员穆考斯基询及反分裂国家法通过后，美国政策有否改变时，希尔指出，美国政策一致，鼓励台湾和中国大陆以对话和平解决歧异。他重申美国政策是基于美国的“一个中国”政策、三公报及台湾关系法。美国不支持台湾独立，反对任何一方片面改变现状。

希尔也说，“我们相信，两岸最近提出的立场中，包含可以构成实质对话基础的弹性”。被问及台湾反对党领导人访问大陆一事时，他说，美国希望这种对话能扩及台湾当局。“美国政府强烈鼓励所有形式的两岸对话。”

他说，真正的关键是，中国要采取重要的下一步，也就是和台湾经适当程序选出的代表展开接触。

希尔强调，亚洲的未来将靠强大而重承诺的美国。他说，美国在亚洲的角色并未式微。中国的崛起是自然的，美国欢迎自信、和平、繁荣的中国。

另外，会后有记者问希尔对台湾刚通过的“修宪案”有何看法，希尔表示他没有评论。



【时事点评】我们注意到，“再次”要求强海两岸“不设前提条件”的情况下展开“实质对话”，不是别人，而是专职“朝核问题”六方会谈美国代表团长职务的、美国国务院东亚事务助卿希尔。

*** 今天的刘建超的确是在“重复着”孔泉“昨天的故事”

东方评论员认为，今天和昨天的“台海和朝核问题”，有了“这么多的相同”、已经足以证明今天的刘建超的确是在“重复着”孔泉“昨天的故事”，然而，在这种“证明”的同时，我们认为更值得强调的是，我们“仍然没有听到”刘建超说过什么朝鲜的“半个不好”，这就是说朝鲜外务省副相金桂冠今天一面声称“目前朝鲜正在继续制造核武器”，一面正式要求“美国给予有核国家待遇”、所有这些、从北京的立场来讲、恐怕同4个月前“朝鲜宣布有核武器”的心态一模一样：那就是“默许”！

东方评论员认为，这就是说，在朝核问题上，尽管情况已经有了很大不同，比如，朝鲜先是“宣布有核”、现在又声称“要继续制造核武器”、也“不否认”“将核武器装上射向美国的导弹的猜测”，然而，中国却仍然还是那个立场、“没有任何变化”；


*** 华盛顿可以“信誓旦旦”，北京也可以“面不改色心不跳”

布什在“连宋登陆”、两岸关系有了缓和之后，却又声称将依据“台湾关系法”协防台湾、要求两岸“不设前提”进行“实质性和谈”、继续向“台独”“播放错误信息”。除此之外，华盛顿还能“信誓旦旦”拍胸脯向北京“保证”“美国反台独说话算数”的。

在我们看到了“这一幕”之后，我们自然也就“非常理解”北京为何也能“一面目睹着”朝鲜“宣布有核”、继而“准备继续造核”、一面还可以“面不改色心不跳”、表面上大谈“半岛无核化取得进展、需各方努力”、实则鼓励朝鲜“有话大胆说”。


*** 北京现在也变得“非常现实”，是“见人说人话、见鬼说鬼话”

东方评论员注意到，尽管布什在台湾问题上“故技重施”的时候、也没有忘记给北京“戴上一顶高帽子”，说什么他相信“中国对美国所做的承诺”，可是，根据我们的观察，北京现在也变得“非常现实”，那就是，对待什么样的对手、就施展什么样的套路，说白了一句话，见人说人话、见鬼说鬼话。

显然，在东方评论员看来，北京现在变得“如此世故”，美国人信用全无是一大原因，但是，更主要的原因还是中国的综合实力相对强大了、美国实力相对下降了，这样，北京自然也就有了和华盛顿“玩世故”的本钱。

在东方评论员看来，不论是吴仪“放”小泉纯一郎的“鸽子”、还是在纺织品问题上的“朝令夕改”、都能体现出中国在“朝核问题”上的“说归说、做归做”、并且在“对美国打东亚核竞赛牌”的问题上、也是“敢说也敢做”的特色来。



*** 华盛顿在东亚问题上，恐怕得小心再小心一点

冲着这一点，华盛顿决策层在东亚问题上，在台湾、朝核、日本问题上，恐怕得小心再小心一点。

毕竟东亚不稳，美国精心谋划的这盘“东起东亚”、西至东欧”、横贯欧亚大陆、割裂“中欧俄”战略联系的“大棋局”、就免不了落个“提前鸡飞蛋打”的结局。



*** 美国今天在台湾问题上“出尔反尔”的目的

在“反台独”的问题上，北京不会幼稚到去相信什么“美国反台独说话算数”。然而，就如我们之前所说的那样，北京现在并没有指望统一、而只要能做到“止独”。

我们认为，北京手上要做的另一件大事，就是和韩国一起，推动朝鲜经济改革，帮助“韩朝”经济整合，从而与俄罗斯、韩国、朝鲜一道促进东北亚经济一体化，并以此吸引日本。

在东方评论员看来，由于华盛顿在目前还不敢打“台独牌”，因此，美国今天在台湾问题上“出尔反尔”、不过是想在“先阻止”台海局势快速向有利于大陆方向移动的同时、也着眼于“敦促”北京加快解决朝核问题、从而稳住日本和韩国。

*** 北京现在真正想要的“现实目标”

而北京要的是华盛顿不要阻拦韩国参与东北亚经济一体化进程，如此一来，华盛顿要想得到北京的帮助、重启“六方会谈”、阻止朝核问题进一步恶化，首先就得让朝鲜半岛有个有保障的缓和局势。

首席评论员指出，如何切实保障朝鲜半岛和平与稳定，从而启动东北亚经济一体化进程，这才是北京现在真正想要的“现实目标”。显然，在这个问题上，华盛顿也昌不会轻易让步的。如此一来，中、美、韩、朝、、日、恐怕还得“八仙过海、各显神通”了。

在一段来自日本媒体的报道之后，我们的关注焦点，将转向日本国内、看看小泉纯一郎近来“过得如何”！

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
