# -*- org -*-

# Time-stamp: <2011-08-04 12:10:57 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 2005年8月02日 星期二




** 日正式通过防卫白皮书、要求日美密切安保




【东京8月2日消息】据报道，日本内阁2日通过《2005年度日本防卫白皮书》，白皮书在去年12月日本制定的新防卫大纲的基础上，明确了积极推动日美安保的态度。

有关台海两岸军力，白皮书指出，台湾在2006年以前，海军、空军和地上部队还足以确保质的优势，但若不有效转换战力，2006年以后，大陆将慢慢取得军事优势。

对中国海洋活动表示警惕

日本防卫厅长官大野功统在2日的内阁会议上就《2005年度日本防卫白皮书》作了汇报，并通过了审议。该白皮书表示对于中国军事现代化是否超出防卫需要，日本必须密切监察。

白皮书指,中国一艘核动力潜艇去年11月驶入日本冲绳对开水域,显示中国海军增加在日本周边地区的活动，日本公众非常关注事件，日本政府已经要求中方解释，并期望中方会加强透明度，加深互信。日本也关注中国在日本的专属经济区附近的东海勘探天然气，表示日本必须有所戒备。

妄言台需加强战力

白皮书还对台海两岸军力进行了相关的分析，称台湾在2006年以前，海军、空军和地上部队还足以确保质的优势，但若不有效转换战力，2006年以后，大陆将慢慢取得军事优势。

白皮书指出，两岸军力不应只以量的比较，也必须判断各种因素，包括：一、大陆陆军虽拥有压倒性的兵力，但对台湾本岛的登陆攻击能力有限；二、大陆海空军的数量虽占压倒性优势，但台湾在质的方面占优势；三、大陆拥有短程弹道飞弹，对台具有飞弹攻击能力。

报告还指出，两岸军力的比较不只是兵力、装备的性能或数量，还需判断运用态势、军队精练程度和后勤支持等因素来判断，基于这种角度，今后两岸军事现代化和美国军售台湾武器的动向值得瞩目，特别是北京军事急速现代化，不久的将来，台湾质的优势有出现重大变化的可能性。

紧急事态时日提供美后方支持

据悉，白皮书是在去年12月日本制定的新防卫大纲的基础上，强调建立有效应对恐怖主义和弹道导弹等“新威胁”的完善体制的必要性，并明确了积极推动日美安保的态度。

文中指出，日美安保体制的合作关系是以美国的参与和美军展开以确保日本周边地区的和平与安定为基础，在日本周边出现紧急事态时，两国将从事包括外交在内的所有努力，并由日本提供美军后方支持。

早在今年2月，日美在安保谘商“二加二会谈”表明，和平解决台海问题是两国的共同战略目标，日本外相町村信孝并于4月在纽约的演讲上，表明台海是美日安保同盟因应的范围，显示出台海问题是周边事态因应对象应不容置疑，台海若出现状况，美军出动因应危机的话，日本势将提供美军后方支持，以间接方式共同对付紧急事态。

对中日人民造成很坏影响

美国国防部上月也发表中国军力报告，指中国军力快速增长，对区内构成威胁，而这次日本的新防卫白皮书，把矛头直接对准中国海军，是日本帮美国叫嚣中国威胁论的表现。

相关专家表示，作为公开发表的这份白皮书，将对中日两国人民造成很坏的影响，因为国民不会从技术层面去分析这些文件，媒体的报道会加深两国人民的不信任感。对日本国民来讲，政府让他们相信中国军力对日本有很大威胁，若日后其政府在钓鱼岛或者增强自卫队等方面提出议案，他们便会支持政府。而对中国老百姓来讲，老是看到日本政府的不友好表示，更会增加他们的反感情绪。



【时事点评】在东方评论员看来，就在北京主持的六方会谈进入到关键时刻，日本的小泉政府、可以说是“动作频频”。一方面，在北京，就在第四轮六方会谈进入确定共同文件内容这一收尾阶段，似乎只有日本人在那里表现得“天马行空、独来独往”，偏要置朝鲜核问题“这个核主题”于不顾，要去反映什么“人权和绑架问题”。


*** 小泉将美国人的“人权”问题与自己的“绑架”问题捆绑在一起，意图“强行闯关”

事实上，所谓的人权问题，从来就不是日本人关心的重点，而是美国人的“最爱”。显然，我们认为，小泉纯一郎这次坚持要将“人权”与“绑架”问题一起塞进议程，事实上不过是在“有意”投美国人之所好、将美国人的“人权”问题与自己的“绑架”问题捆绑在一起，意图“强行闯关”，不难看出，这与日本在“入常”的问题上、想借“四国集团”强行突破的手法是如其一辙。


*** 华盛顿“无法左右”、却又不得不“深陷”朝核问题的原因

对朝核问题的“性质”，之前，我们就多次强调过，对美国而言，“朝核问题”是一个“可松可紧”的问题、但却绝对是个重要问题。东方评论员认为，美国人之所以想将朝核问题拖下去、却不敢让它失控，就在于这个问题处理不好，将严重冲击美日、美韩军事同盟、要知道、这可是支撑美国旨在遏制中国、包围俄罗斯、阻碍东亚经济一体化、分隔中日、俄日战略接近的西太平洋战略的两个相互支撑、却又相互牵制的战略锚点。

显然，在东方评论员看来，如果不是有这么一层战略因素，那么，很难想像、朝核问题会成为今天这种既让华盛顿“无法左右”、却又不得不“深陷其中”的朝核问题。


*** 不论是日本还是韩国，事实上也都在反向地“利用中美争斗”

东方评论员认为，也正是看到了这一层，不论是日本还是韩国，在明知华盛顿在利用自己遏制北京的同时，事实上也都在反向地“利用中美争斗”，一边防备中美达成协议会对自己的利益造成损害，另一方面也意图借助朝核问题尽可能地达成自己的战略目的。



*** 对日本而言，如何好好地利用一下这一“关键时刻”有着不可抗拒的诱惑力


对日本而言，现在正是中美在朝核问题上“斗法”最为关键的时刻，因此，如何精心策划、好好地利用一下这一关键时刻，在通往“军事大国”、“政治大国”的方向上“再次疾跑一段”，显然有着不可抗拒的诱惑力。


*** 日本针对北京的“小动作”也是一个接着一个

事实上，自北京在7月31日、正式提出“第一版”“共同文件草案”之后，“六方会谈”就进入了关键时期。而也就是在这一期间，日本针对北京的“小动作”也是一个接着一个。

首先，就在昨天，日本影响最大的两家保守派报纸《读卖新闻》及《产经新闻》、竟然一起刊登了一则整版广告，呼吁日本“全体国民”到靖国神社进行参拜。


*** “全国参拜”广告的“两层险恶用心”

在东方评论员看来，日本右翼的这一动作，表面上是在呼吁“全国参拜”，但是该广告的“两层险恶用心”是不言自表：第一，广告意图是“鼓励小泉在8月15日、中国人民抗战胜利60周年纪念日、朝鲜民族解放日进行参拜，显然，一旦小泉敢如此行事，必然激起中国、韩国社会的强烈反应。因此，小泉纯一郎虽有此心、但却一时还不敢付之行动。


*** 再谈中日关系中一个非常值得警惕的“新特点”

然而，就如我们在昨天的点评中所说的那样，在日本右翼媒体处于日本主流声音的今天，在诸如《读卖新闻》及《产经新闻》这些有影响媒体的长期煽动下、以及小泉政府有心利用美国不甘心在东亚渐失主导权的心态，韩国惧怕中国将来影响力太强的心态下、准备在历史问题、中日、韩日主权争端问题上“孤注一掷”、如果北京最后让步，则小泉纯一郎当然就可以成为最大的赢家；如果北京强硬反击，在日本右倾化媒体的渲染下、就必然会激起日本社会的民族情绪。

显然，东方评论员认为，在这种“孤注一掷”的危险心态下，“靖国神社”问题已经被日本右翼“煽动”成了一张牌、并已经被小泉纯一郎尝试着当成了一张针对北京的牌来打，在我们看来，这是中日关系中、一个非常值得警惕的“新特点”。不难看出，日本在这个时候抛出这则极具挑衅性的广告，显然有警告中国、韩国的目的。


*** 这则“整版广告”是在为日本、美国的“六方会谈”代表团“提供场外支持”

第二，首席评论员就指出，对照这一“新特点”，我们很容易看清楚这则“整版广告”有着另一层不可告人的动机，即：是在为日本、美国的“六方会谈”代表团“提供场外支持”，意在以中国、韩国都十分注意的“靖国神社”问题、拿中日、韩日在历史问题上的重大矛盾“做炮弹”、怂恿、并策应华盛顿在朝核问题上、继续尽可能地强硬、从而让美国向中韩施加压力、以达到将日本前面所说的“人权”与“绑架”问题一起捆绑着、塞进六方会谈议程的目标、从而保证日本的声音始终出现在“六方会谈”的始终、从而保证“日本的利益”“有机会封装”在东北亚多边安全体制之中。


*** 日本今天一口气就通过了两则刺激中国的“文件”

在东方评论员看来，在六方会谈的关键时刻，除了7月31日抛出的那则广告之外，日本人的“小动作”还包括日本东京都教育委员会已决定，明年春季建校开学的4所东京初高中一贯制学校将使用由“新历史教科书编撰会”编写、扶桑社出版的中学历史教科书。

特别值得注意的是，就在今天、日本有关部门可就说是“一口气”就通过了两则直接刺激中国的“文件”、除了上述新闻中的日本05年度国防白皮书之外，还有一份小泉纯一郎已经炒作了两三次的一项法案、即日本议会抢着通过了“台湾居民入境永久免签证”的法案。

*** 学习美国、日本《防卫白皮书》“拿腔拿调”

首先，是日本内阁今天通过的2005年度国防白皮书、白皮书称“日本应对中国军事现代化加强警戒，要密切注意中国的海军舰艇动向”，另外，《防卫白皮书》还学着美国五角大楼7月19日抛出的《中国军力报告》措词、“拿腔拿调”的明确“关注了”中国曾警告过日本的台海问题。

不仅如此，我们注意到，《防卫白皮书》除了不厌其烦地用国防预算数字的演绎手法来影射“中国威胁”外，还按五角大楼的“文字习惯”“提醒”台湾，“警告”台湾在2006年以前，海军、空军和地上部队还足以确保质的优势，然而，“若不有效转换战力，则面对中国人民解放军大幅军事现代化，2006年以后，中国大陆将慢慢取得军事优势”。


*** 有了这份“东施效颦”的《防卫白皮书》，宣传“中国威胁论”的全套宣传资料、可以说“全部出齐”了

对此，东方评论员认为，日本这种“不惜篇幅”、“东施效颦”般地抛出的这份《防卫白皮书》，以“美式”的观点来表达对中国军力的极度关注，其意图非常值得警惕：在我们看来，日本挑在“六方会谈”最关键的时刻跳出来，本身就是在刻意强调在与与美国7月公布的《年度中国军力报告》遥相呼应。

大家应该还记得，就在美国推迟三次、终于公布了《中国军力报告》之后，台湾也紧跟着弄出了一份所谓的、鼓吹“中国威胁论”的《国安报告》，再加上日本今天的这份报告，可以说是有关宣传“中国威胁论”的全套宣传资料“全部出齐”了。


*** 有人在“等着看”北京是否接受“这份威胁”

显然，首席评论员就指出，到目前为止，华盛顿一手导演这出、在东亚以兜售“中国威胁论”为手段，欲达到强化美日安保条约、建立“美日台”军事同盟为目的的“前期准备工作”可以说已经完成了“理论部分”。接下来，就是看北京是否接受“这份威胁”，并以此来逼迫中国在其它方向做出让步。

不难看出，这种等着看北京“是否接受这份威胁”的势力中，不仅有等待中的美国人，更有等待中的日本人。

因此，等待中的日本人、似乎象是担心北京看不懂自己的意思、感受不到来自日本的威胁，从而在报告中不仅“报告”了所谓台海军事形势，还第一次学着美国人、尝试给“台独”开起了“药方”。


*** 日本这也是在试探北京的、在放向台湾出售武器的“探测气球”

请大家注意这一段，原文是：白皮书指出，两岸军力不应只以量的比较，也必须判断各种因素，包括：一、大陆陆军虽拥有压倒性的兵力，但对台湾本岛的登陆攻击能力有限；二、大陆海空军的数量虽占压倒性优势，但台湾在质的方面占优势；三、大陆拥有短程弹道飞弹，对台具有飞弹攻击能力。

报告还指出，两岸军力的比较不只是兵力、装备的性能或数量，还需判断运用态势、军队精练程度和后勤支持等因素来判断，基于这种角度，今后两岸军事现代化和美国军售台湾武器的动向值得瞩目，特别是北京军事急速现代化，不久的将来，台湾质的优势有出现重大变化的可能性。

非常清楚，日本的这份白皮书在“有了这一段露骨的、旨在鼓动台独“军事抗统”的“药方”之后，其“对台政策”可以说完成了“质的变化”，到现在为止，在台湾问题上、在台湾问题上，日本俨然要当“第二个美国”。第一，日本这是在冲着北京警告、它愿意充当与美国一样的角色，公开插手台湾问题，并对中国公开开打“台湾牌”、意图以此谋取日本在其它方面的战略利益。

第二，日本这也是在试探北京的反应、与可能的对策，本质上是在为日本有朝一日再学美国、向台湾出售武器“放探测气球”。


*** 日本人的这次动作，其功课似乎做得非常精确

首席评论员指出，日本人的这次动作，其功课似乎做得非常精确。在我们看来，小泉政府是瞄准了华盛顿在朝核问题六方会谈上的尴尬与无奈，是即受到中国、俄罗斯的压力、又受到韩国的压力，因此，日本似乎相当自信：一个在“朝核问题”继续强硬、就很可能失去韩国的华盛顿，为了继续支撑其东亚战略、必然会更加信赖日本的作用。

因此，在六方会谈最为关键的时刻，日本表面上针对北京的“上窜下跳”、又何尝不是在借机强调日本对美国的重要性、特别是没有了韩国之后的重要性，并以此在这种关键时刻“拿美国人一把”？


事实上，华盛顿在朝核问题上“进退维谷”的尴尬、激发了日本这种冲着北京喊叫、事实上却是“拿美国人一把”动机，在我们看来，对于华盛顿而言，日本被激出了这种动机一旦表面化，又理所当然地会被美国代表团拿着、作为新的筹码去向中国、韩国讨价还价、要求北京这个“六方会谈”“共同文件草案”的主笔、以及在这轮六方会谈中向美国直接施加压力的韩国、同意再改改“草案”的内容。

另外，只是华盛顿也不是省油的灯，在日本如此这般利用美国的同时，华盛顿又何尝不会拿日本人的利益与北京“说事儿”？（这一点，将在后面再作分析）。


*** 美国日本有那里相互利用、频频出牌、那北京的牌又在哪里？

然而，既然美国日本有那里相互利用、频频出牌、那北京的牌又在哪里？东方评论员认为，有一点请大家不要忘记了，那就是，在之前，一连近一个星期的点评中，东方评论员已经用大量的篇幅、从各个层面论证了这一轮六方会谈、对华盛顿和北京而言、完全是“两种前景、两幅心态”的理由。今天，我们不再多谈。

总之，在东方评论员看来，对华盛顿而言，在很大程度上，迄今为止，它对第四轮六方会谈所表现出来的“积极性”、在很大程度上是被“诚心诚意”帮助韩国稳定朝鲜半岛、进行南北经济整合的中国、和“急于稳定朝鲜半岛局势”的韩国给“逼出来的”。


*** 美国参加这轮六方会谈的背景，是美国从政府到民间、充斥着对韩国的强烈不满

要知道、美国参加这轮六方会谈的背景，是美国从政府到民间、充斥着对韩国的强烈不满。东方评论员注意到，在美国、一种游行的观点就是，美国已经证实“胡萝卜”无法使朝鲜改变政策，但韩国却阻止美国向朝鲜挥舞“大棒”。

在我们看来，这种游行观点显然点出了朝核问题的实质。事实上，美国人心中认为最有效的“大棒”并非什么军事打击（因为有中国在后面站着、军事打击朝鲜的风险与代价太大），而是“经济制裁”。

然而，众所周知，在这个问题上，韩国出于自己的国家与民族的政治、经济之长远利益、与着眼于维护东北亚稳定的北京“站得极近”：不仅强烈反对军事解决朝核问题、也强烈反对经济制裁朝鲜，理由就是北京的立场：和平对话是解决朝核问题的唯一出路、帮助朝鲜走出经济困境是解决朝核问题的根本出路。


*** 出于政治角力的现实性、华盛顿最好的办法似乎就“只能让六方会谈成功、而不能失败”

因此，我们认为，对华盛顿而言，在韩国这个盟友的“热切期望”中，只要朝鲜不提出新的、让韩国感觉到“不合理”的要求，那么，出于政治角力的现实性、华盛顿最好的办法似乎就“只能让六方会谈成功、而不能失败”了，否则的话，美国这只“已经松动”的战略之“锚”，在无法再对华盛顿抱有幻想之余、就很有可能在中国、俄罗斯“诚心诚意”的引诱下、而“彻底起锚”、从而就会让美国的、撑起其主导亚洲角色的西太平洋战略框架、立刻就“坍塌一半”。


*** 朝鲜已经开始拿美国对韩日提供的核保护伞当作筹码

首席评论员认为，种种迹象显示，六方会谈到了最紧要的关口。事实上，有消息说，朝鲜已经在六方会谈上、本着半岛无核化的精神、开始拿美国对韩国和日本提供的核保护伞当作了筹码抛了出来，据说韩国暗示不反对放弃美国的核保护伞，这就是说，朝鲜与韩国在这个问题上是在唱双簧，其目标是直指美国在韩国的军事存在、在我们看来，美国人“绝对听得懂”这是什么意思、是谁的意思。

在东方评论员看来，朝鲜抛出而这种筹码、其“直指的范围”甚至包括日本的核武器问题，显然，日本的核武问题、就是美国向日本提供核保护伞的潜台词。不难看出，在日本上窜下跳的时候，朝鲜的这一举动、虽然非常对北京的胃口、但却不一定北京的意思，东方评论员认为，日本核武问题一直是北京手上的一张牌，但却不是现在愿意就打的一张牌。

因此，我们的判断是，核保护伞问题是韩国“主动要求”的，意在逼迫华盛顿放弃强硬态度、让六方会谈得以继续。而北京不过是“无所谓”、也不好直接反对韩国的主张而已。


*** 在某种意义上，一个失败的“六方会谈”似乎对中国更具战略意义

东方评论员认为，显然，最希望六方会谈成功的莫过于韩国人。在我们看来，对北京而言，在这个时候如果北京能有效地帮助韩国克服惧怕中国控制朝鲜半岛的心理，那么，比起一个成功的“六方会谈”，在某种意义上，一个失败的“六方会谈”似乎对中国更具战略意义：对北京而言，如果能避免建立一个以“六方会谈”为基础的多边安全体制，那么，北京就可以避免韩国所期望的一种局面，既：让美国作为一个半岛局势平衡者的角色、来平衡朝鲜半岛经济整合、也就是东北亚经济一体化的过程中、中国可能会迅速增长的影响力；

正是在这种背景下，在东方评论员看来，北京实际上对朝核问题第四轮六方会谈持超然的态度，美国让步，六方会谈就会取得成功，朝鲜半岛经济整合开始、这就非常不错了！

*** 韩国人对六方会谈为何如此重视？

当然，如果美国不让步，继续强硬、六方会谈就会失败、这个时候，就要看韩国如何决定、何去何从了，显然，对朝鲜半岛这种不确定局势最着急的就是韩国，事实上，韩国人的“着急”不仅仅是政治上的因素、也是经济上的因素，但最希望“六方会谈”成功却出于政治因素。

要知道，韩国经济现在是非常信赖东亚经济、特别是中国市场，站在韩国的立场来看，这会影响韩国的政治、经济的独立性，因此，如何尽早开发朝鲜、启动朝鲜半岛经济整合进程、并以此联络俄罗斯资源、吸引日本对朝鲜半岛的投资、让日本的利益“登陆”朝鲜半岛、让俄罗斯的资源为已所用，让日本、俄罗斯在朝鲜半岛安全问题上起到更大的作用、就成了韩国抵消中国、美国影响力的“当然考虑”。


*** 韩国的心态，对日本下决心抛出这一连串小动作起到了巨大的诱惑作用

值得强调的是，韩国的这种需要在六方会谈基础上建立东北亚安全机制、最大限度地拉拢日本、俄罗斯、在多边框架内制约中国、美国这两大势力的“平衡心态”，也对日本下决心抛出这一连串小动作起到了诱惑作用。


*** 对小泉的这一冒险所引发的后果，不仅北京、就是华盛顿，都得认真对待

不难看出，连续几天，日本表面上针对中国的一系列“小动作”，事实上、是针对韩国的“角色与处境”“谋定而后动的”，尽管其拿历史问题当牌打的手段卑鄙、客观上讲，对小泉纯一郎的这一冒险、以及其不可告人的动机、不仅北京、就是华盛顿，都得认真对待。

因此，在“朝核问题”而引起的东亚局势可能的巨大变化的问题上，就是北京与华盛顿之间，其实在许多问题上也“需要交流与沟通”，其中、在如何即打日本牌、又要控制好日本的问题上，中美从来就是“开城布公”的。


*** 中美启动中美战略对话机制的一大原因

事实上，这也正是美国副国务卿佐立克赶在六方会谈最紧张的时候访华、启动中美战略对话机制、并公开表示将参与六方会谈“共同文件”商定进程的一大原因。

在一段来自华盛顿的分析报道之后，东方时事评论员、经济评论员将一起、就胡锦涛主席9月访美、中美最高层级对话中应该涉及的几个问题“提前”给出我们的一些观点。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
