v# -*- org -*-

# Time-stamp: <2011-08-02 22:53:32 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

#+STARTUP: indent

* 2005年5月26日 星期四

** 2005年5月26日外交部发言人孔泉在例行记者会上答记者问（节简）

【外交部网站消息】5月26日下午，外交部发言人孔泉主持例行记者会。

　　孔泉说：女士们、先生们，下午好！回答问题之前先宣布几条来出访的消息：

　　应国家主席胡锦涛的邀请，秘鲁共和国总统托莱多将于6月2日至6日对中国进行国事访问。

　　大湄公河次区域经济合作第二次领导人会议将于2005年7月4日至5日在云南昆明举行，中国国务院总理温家宝将出席并主持会议。

　　应俄罗斯外交部长拉夫罗夫、哈萨克斯坦外交部长托卡耶夫的邀请，李肇星外长将出席6月2日在俄罗斯符拉迪沃斯托克市举行的中国、俄罗斯、印度外长非正式会晤和6月4日在哈萨克斯坦首都阿斯塔纳举行的上海合作组织成员国外长会议。

　　应外交部长李肇星邀请，智利共和国外交部长瓦尔克将于5月29日至31日对中国进行正式访问。

　　下面我非常高兴回答大家的提问。

　　问：你能否提供秘鲁总统访华的详细日程？

　　答：秘鲁总统托莱多访华期间，中国国家主席胡锦涛将与他进行会谈，中国全国人大常委会委员长吴邦国和国务院总理温家宝将同他会见。会谈和会见的议题既包括双边关系，也包括双方共同关心的地区和国际问题。除北京外，托莱多总统还将去上海、西安和广州进行访问。

　　提供一点背景情况，也许对你有用。秘鲁是同中国最早建交的南美洲国家之一。两国建交34年中，双边关系发展很顺利，双方在各领域的合作不断加强，政治互信不断增强。去年中国和秘鲁贸易额是19.4亿美元，中国存在一定的逆差，中国进口15亿美元，出口4亿多美元。尤为重要的一点是，从今年1月开始，中秘两国宣布建立全面合作伙伴关系。我们深信，托莱多总统的这次国事访问，一定会有力地推动中国和秘鲁的互利合作在新的基础上更快地发展。

　　问：请介绍乌兹别克斯坦总统访华时会谈的内容，尤其是中乌友好条约的内容。双方在安全及反恐合作方面有何进展？

　　答：昨天下午，中乌两国元首举行了会谈，会谈的具体情况，新华社已经进行了全面的报道。会谈的议题很广泛，包括双边关系，涉及政治、经贸、文化、科技、教育等各领域的合作，同时双方就共同关心的地区和国际问题交换了意见。

　　你刚才提到的中国和乌兹别克斯坦的友好合作伙伴关系条约，这个条约是两国元首签署的。在条约中，双方表明了进一步发展中乌互利友好合作关系的强烈愿望，特别谈到了双方将进一步加强在有关领域合作的具体措施。这些条约将作为进一步巩固中乌关系发展的政治法律基础，而且预示着两国政府将以这个条约的精神和原则为指导，在更加坚实的基础上不断扩大和深化中乌之间的友好互利合作。

　　在条约签署之后，两国元首还出席了中国和乌兹别克斯坦经济技术合作协定、海关互助协定等10多项合作文件的签字仪式。今天下午，国务院总理温家宝和国务委员唐家璇还将同卡里莫夫总统举行会见。

　　问：包括巴基斯坦在内的一些国家申请成为上海合作组织的观察员。中方对上合组织的扩大持何立场？是否支持巴基斯坦成为上合组织观察员？

　　答：上海合作组织在对外交往方面一直采取积极态度。事实上，上海合作组织已同东盟签署了谅解备忘录，体现了上海合作组织期望同其他地区组织和国家开展交往、增进互信、加强合作的意愿。有些国家包括巴基斯坦希望成为上海合作组织的观察员，进一步发展同上海合作组织的关系。我们注意到这一点。上海合作组织成员国正在对此进行认真的研究。我们希望根据上海合作组织的议事日程尽快就有关事宜通过协商一致达成共识。

　　
　　问：中国是否考虑到在5月13日事件后邀请乌兹别克斯坦总统访华会招来国际上的批评？你能介绍一下中乌反恐合作的过去及前景吗，例如中乌之间的军事演习？现在有多少东突分裂主义分子在乌藏匿？

　　答：中国和乌兹别克斯坦是友好邻邦，我们希望在和平共处五项原则基础上发展同乌兹别克斯坦的友好关系。特别是在当前情况下，中亚地区面临着恐怖主义、分裂主义和极端主义的威胁，同时也都面临着加快本地区发展的任务。中国和乌兹别克斯坦有许多共同点，有许多共同利益。进一步加强中国和乌兹别克斯坦的双边关系，一方面使中乌在政治、经贸、教育、文化、科技及海关等领域的合作更加富有成果；另一方面也有利于共同努力维护地区的和平与稳定，共同致力于地区的发展与繁荣。

　　上海合作组织成立的目标就是要加强本地区国家合作，共同打击损害本地区和平稳定的恐怖主义、分裂主义和极端主义。在这一框架内，上海合作组织举行了一些联合军事演习。具体下一步什么时候、以什么方式举行，这将由上海合作组织成员国共同讨论来决定。

　　东突分裂主义分子在中国制造了许多恐怖主义事件，乌方对中国政府在这个问题上的立场是充分理解和支持的。我们希望本地区国家加强合作，共同打击恐怖主义活动，因为这些活动不仅仅针对一个国家，而是针对整个地区，甚至包括世界其它国家和国际社会。

　　
　　问：梁光烈总参谋长会见了印度国防部长和其它军方领导人，中方对此有何评论？

　　答：应印度军队领导人邀请，中国人民解放军总参谋长梁光烈上将于5月23日至28日对印度进行正式友好访问。访问期间，梁光烈总参谋长与印度的军队领导人和国家领导人就双边关系，特别是进一步加强两军交往深入交换意见。这次访问具有重要意义，这是在两军近年来交往合作势头不断发展的背景下，两军高层领导人的直接交往。这种交往有利于双方进一步加强互信，增进了解，有利于双方进一步扩大在军队领域的交流与合作。我们期待着这次访问取得圆满成功。

　　问：俄罗斯联邦委员会批准了《中俄国界东段补充协定》，中方何时批准该协定？何时开展勘界工作？

　　答：不久前，俄罗斯国家杜马已经批准了这项重要协定，昨天俄罗斯联邦委员会也批准了这项协定，我们对此感到高兴。中国的立法机构实际上一直没有停止有关审批工作，将会加紧进行。双方将共同努力，使中俄边界成为和平的边界、合作的边界、友好的边界，成为两国人民世代友好的纽带。

　　


【时事点评】在昨天的中亚部分，我们将全部版面都用在了“解读”中乌两国元首签署的《中华人民共和国和乌兹别克斯坦共和国友好合作伙伴关系条约》，显然，由于这份条约的详细内容并没有公布，因此，对该“条约”的“解读”，我们不过是从“猜测”的角度去加以分析的。


*** 这次访华，世界各大国无不“屏住呼吸、瞪大眼睛”

事实上，对乌兹别克斯坦总统卡里莫夫的这次访华，世界各大国无不“屏住呼吸、瞪大眼睛”。而中国决策层以过次访问更是重视有加，早在邀请他正式来访之前，孔泉就在外交部记者会上明确宣布，中国支持乌兹别克斯坦政府镇压骚乱的行动，并将最近发生在乌兹别克斯坦的事件“定性为”乌国的内政。


显然，中国这次清晰地给出了自己的立场，在东方评论员看来，这一“提前确立立场”，其意思非常明显，第一，中国领导人这是给足了卡里莫夫面子，这就是说，不论之前所传说的、乌兹别克斯坦总统卡里莫夫是主动寻求中国的支持也好、被动地反击西方的谴责也罢，都将是一种政治愿意，而很难形成一个“具体方案”。


在东方评论员看来，这种“猜测”也因为中国的“提前表明立场”、而烟消云散，也就是说，卡里莫夫此次访华，不是要寻求什么“表面上的支持”，因为这些意愿性的东西，中国已经提前给了，显然，央我们看来，“中乌”两国这是明白地告诉西方国家、特别是华盛顿，两国的这次高峰对话，不是来“空谈意愿”的、而是来确定具体方案的。

*** 我们所希望的“具体内容”、就是能补上“上海合作组织”的“漏洞”

在昨天的点评中，我们一再强调：从胡锦涛主席和卡里莫夫总统在会谈中一再强调的“.......在上海合作组织框架内团结与协作，共同打击“三股势力”，维护地区和平、稳定与安全.....”这种语义中，结合乌兹别克斯坦面临着巨大的内外压力，不难看出，“这种语义”意味着该“条约”里“很可能”包括有帮助乌兹别克斯坦政府维持国家安全、和政局稳定的“具体内容”。

显然，我们所希望的“具体内容”、就是能补上“上海合作组织”的“漏洞”，能补上“上海合作组织”中所没有的、却又非常必要的“以军事手段帮助区域内国家维持国家安全、和政局稳定”。


*** “骚乱事件”本身又颇让美国、欧洲颇为尴尬

一直以来，在乌兹别克斯坦镇压骚乱这个问题上，北京表示出来的立场与欧洲和华盛顿的看法截然不同。东方评论员注意到，前天，也就是5月24日，美国国务院发言人鲍彻还在说，美国和其他国家都"更为团结一致和坚定地"要求乌兹别克对那次造成数百人死亡的暴力事件进行独立调查。

不难看出，鲍彻在这里所说的“其他国家”指的就是欧洲人，而就在卡里莫夫动身前往北京的同时，北约也开始在那边“喋喋不休”起来，并发了个声明，一则敦促乌政府接受独立的国际调查，第二，则是和华盛顿一样，“高调”谴责乌安全部队在处理骚乱事件时“不适当地”使用武力。

*** 搞国际调查是假，在乌兹别克斯坦“再创作一幅颜色革命”才是真！

东方评论员认为，就华盛顿而言，搞国际调查是假，而借调查的过程、去想办法、找机会、从而将“民主的颜料瓶”偷偷地打开，在乌兹别克斯坦“再创作一幅颜色革命”才是真！然而，要做到这一点，乌兹别克斯坦政府必须是个弱势政府才行，乌兹别克斯坦境内的“民主力量”象个民主的样子才行。

在东方评论员看来，这次“骚乱事件”本身就颇让他们尴尬，哪有上千人组织起来，去抢枪支、砸监狱、放罪犯的“民主”？显然，向来比美国还要重视民主的欧洲人，只好将眼睛盯在“不适当地”使用武力的层面上。

然而，对美国和欧洲而言，乌安全部队在处理骚乱事件的过程表明，该政府决策果敢、手段严厉，这是之前在格鲁及亚、乌克兰、吉尔吉斯斯坦所没有出现过的。

*** 欧盟和美国人在这个问题上显然也在“同床异梦”

因此，首席评论员指出，乌兹别克斯坦政府的强势，显然令欧洲人有充分的发挥空间。在我们看来，就在中亚“推行民主”这个问题本身而言，欧洲人也是非常愿意，然而，面对乌兹别克斯坦政府这么个强势政府，现在是否就要搞什么“颜色革命”，欧盟和美国人在这个问题上显然也在“同床异梦”。

在我们看来，欧洲人似乎更是在“将”华盛顿的“军”，根据我们的观察，与华盛顿相比，欧盟似乎“更加有兴趣”去逼乌兹别克斯坦政府接受国际调查。

*** 美国担心其军事基地很可能“被逼挪窝”

我们知道，美国在乌兹别克斯坦有军事基地，当然，与欧洲人相比，放在以前，这可是个“巨大的资产”，然而，在东方评论员看来，出了这档子事之后，特别是乌兹别克斯坦政府态度坚决、以武力的方式“加以处理”之后，“复杂的局势”令华盛顿决策层感觉到，有必要将“颜色革命”的事情放一放，道理很简单，如逼急了乌兹别克斯坦和俄罗斯，那自己好不容易得到的“这方”军事基地，很有可能被乌政府当成“美国搞颜色革命的基地”而“被逼挪窝”。

*** 本身就是欧盟对美国人“打民主牌”的一种表现

显然，欧盟就没有必要担“这份小心”，在东方评论员看来，“敦促”华盛顿“去逼”乌兹别克斯坦政府接受“国际调查”，本身就是欧盟对美国人“打民主牌”的一种表现：一方面可以“以民主价值观”逼着华盛顿跟着自己喊叫，“意在激化”美国与警惕着“颜色革命”的乌兹别克斯坦、俄罗斯、和中国之间的固有矛盾，最好是将美国的军事基地给逼出来；

*** 欧盟搅局的企图心很强烈

再就是，从形式与力度上看，欧盟本身就是在“虚张声势”、“假戏真做”，利用这一事件搅局的企图心很强烈、显然，让华盛顿在中亚站稳脚跟并不是欧盟的利益所在。在东方评论员看来，一旦美国在乌兹别克斯坦“势微”，不能排除欧盟最后有可能“反戈一击”，从而得到乌兹别克斯坦政府的“认可”，显然，这将是欧盟也成为乌兹别克斯坦日后“搞大国平衡政策”中的一方之捷径。


*** “有趣的画面”随着卡里莫夫飞机的起飞“立刻就出现”了

但是，在东方评论员看来，按照北京的立场，那么，这次“暴力事件”也就是乌国的内政，而乌兹别克斯坦是一个主权国家，因此，在其国内发生的问题、乌兹别克斯坦当然有权自己作出评判。

事实上，华盛顿和欧盟、北约的这些个要求、立刻遭到了乌总统卡里莫夫的明确拒绝，值得注意的是，卡里莫夫在明确拒绝之后，就立刻启程访华，而东方评论员也注意到，有趣的画面也就随着卡里莫夫飞机的起飞、而立刻就出现了，那就是：华盛顿立刻调整了立场，一改之前“只知道”猛烈抨击乌政府的做法，也“开始记起了”狠批“制造骚乱者”的不当行为。

显然，北京这次的处理方式与吉尔吉斯斯坦是“迥然不同”。在我们看来，从北京“明确立场”的态度看，这完全是以一种“明快的方式”果断介入。东方评论员认为，促使华盛顿“突改腔调”的重要原因恐怕有两条，第一，就是北京这次态度鲜明地支持乌兹别克斯坦，并邀请卡里莫夫访华；

第二，北京这次邀请卡里莫夫访华，本身是否意味着“中俄”在“上海合作组织”章程问题上有什么“新的想法”吗？如果是，那就意味着俄罗斯愿意“重新考虑”中国在中亚的角色，也意味着“中俄”关系向前跨了一大步。

一般认为，之前，华盛顿和欧盟“如此这般”地强调国际调查，都与其惯用用“民主武器”、搞“颜色革命”的企图有关。然而，既然有了上面所说的“这一层”，那么，同床异梦的美国和欧洲、只好将什么“橙色、玫瑰色”的“民主的颜料瓶”暂时收起来，不得不将眼睛“真心或假意地”盯在“不适当地”使用武力的层面上，“心不在焉”要求由国际组织展开“独立调查”了。

然而，如果我们假设的这些条件成为事实的话，那么，乌兹别克斯坦会接受国际调查吗？在我们继续这一话题之前，我们再来看一段相关新闻报道。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 吉尔吉斯斯坦代理总统巴基耶夫要求中俄出兵吉国

【俄罗斯国际文传讯塔什干消息】昨天，吉尔吉斯斯坦代理总统巴基耶夫向国际文传电讯社透露，对于乌兹别克斯坦东部的反政府暴动而产生的难民大量涌入吉尔吉斯斯坦南部的奥什地区，将同意以俄罗斯为中心的独联体(CIS)集团安保条约和包括中国在内的上海合作组织成员国的部队驻留。

　　在3月的政变中刚刚建立的吉尔吉斯斯坦政权十分重视防止因为难民涌入而造成伊斯兰激进派基地所在的奥什地区局势动荡，出现对吉尔吉斯斯坦脆弱的政权基础造成冲击的事态。吉尔吉斯斯坦政府希望依靠同样担心中亚动荡局势的俄罗斯和中国的军事力量来填补其权力空白。

　　俄罗斯、中国对调兵一事并没有做出公开的反应，但可以预见，乌兹别克暴动后的中亚局势将成为7月上旬在哈萨克斯坦首府阿斯塔纳召开上海合作组织首脑会议时的主要议题。



【时事点评】在东方评论员看来，如果这条消息“最终得以落实”，那么，将是中国在中亚政策的一个巨大突破。


*** 如果该消息“最终得以落实”，将是一个巨大突破

首席评论员指出，这种消息其实就是我们一直所期盼的，可以说是自上海合作组织成立以来、所一直期盼的。在我们看来，如果该消息“最终得以落实”，那不仅是上海合作组织的一个巨大突破、也是中国中亚政策的一个巨大突破，本身也是中俄关系的一个巨大突破。


*** 现在的“上海合作组织”、不过是个“无牙老虎”而已！

在之前的点评中，我们一直认为，由于俄罗斯对中国心存顾忌，又将中亚诸国视作自己的传统势力范围，从而对中国在该地区的影响极其警惕。在东方评论员看来，莫斯科对北京的“警惕”、从“上海合作组织”的“安全手段”几为“空白”就可知一二。

显然，按“上海合作组织”现有的章程，“上海合作组织”成有维护成员国安全和稳定的责任，但我们翻遍了整部章程，都弄不明白“上海合作组织”有什么手段去尽到这一责任，也就是说，这个世界上唯一让华盛顿“控制不了的”、让华盛顿耿耿于怀的“地区性安全组织”说穿了、不过是个“无牙老虎”而已！


*** 吉尔吉斯斯坦一直在搞所谓的在“大国平衡政策”

在3月份，吉尔吉斯斯坦刚经历过改朝换代，执政近15年的总统阿卡耶夫最后是“匆匆宣布辞职”，并前往俄罗斯，从阿卡耶夫最后选择落难俄罗斯，我们就不难看出，俄罗斯是“如何尽心尽力地关照”这些前苏联加盟共和国、现在的中亚国家的了。

事实上，吉尔吉斯斯坦前总统阿卡耶夫、之所以长期以来同时在莫斯科、北京和华盛顿这三颗鸡蛋上“跳舞”，就在于他想利用大国强权之争，来牟取最大的利益。因此，至少在表面上，吉尔吉斯斯坦一直在搞所谓的在“大国平衡政策”，即同上面的几家都搞好关系，都不得罪。


*** 小国家都欲做个“小个子的渔翁”、以图“玩转大国”

众所周知，吉尔吉斯斯坦有一个北约的军事基地，那是2001年12月，北约以“支援阿富汗反恐战争”为名，在吉尔吉斯建立了“甘希”军事基地。基地名义上隶属北约，但部署的30架飞机和1600名军人，其实主要来自美国，因此，它是个“地道”的“美国货”。

如是乎，在吉尔吉斯斯坦的地面上，是既有俄罗斯的军事基地，也有美国的军事力量，在同时保持“美俄”势力的同时，吉尔吉斯斯坦还引入了中国因素，同中国大做生意，将中国的经济影响力牵引进国内，从而在吉尔吉斯斯坦实现了俄、美、中三大势力的大体均衡。

然而，在东方评论员看来，保持这种“平衡政策”也是要有基础的，那就是各大强权在吉尔吉斯斯的力量都得平衡才行。事实上，也正是一些小国家的统治阶层喜欢搞这种所谓的“平衡政策”、都欲做个“小个子的渔翁”、以图“玩转大国”，才给自己带来的致命危险。


*** 几个国家的统治者在倒台前都有一个共同点，都经历了一个“共同的过程”

事实却是，这一政治“冒险剧”，在前苏联加盟共和国、现在已经独立的独联体成员国中、可以说是屡屡上演。在东方评论员看来，其中早一点的有格鲁及亚、近一点的有乌克兰、再近一点的就是吉尔吉斯斯坦。

不难看出，上述几个国家的统治者，在倒台前都有一个共同点，那就是都经历了一个共同的过程，即，一开始都是亲西方的，特别是亲美、从而与俄罗斯拉开一段距离，但由于当时的统治者都是前苏联的官撩，非常熟悉前苏联的那一套，在国内政治、经济政策上也与俄罗斯走的路“如出一辙”，即，不仅在经济上搞不好，而且还形成了一群以权力为基础的爆富阶层。在我们看来，这都为美国为首的西方、去播撒“民主的种子”，并以民主为武器去影响、并控制统治者提供了充足的条件和肥沃的土壤。

*** “小个子的渔翁”在“玩转大国”的过程中、正在离危险越来越近

在我们看来，由于这些国家与俄罗斯的经济联系太紧，特别是这些国家都有石油，而出口这些石油都大多得通过俄罗斯的管道，又着实离不开俄罗斯，到了这个时候，这些统治层就感受了“执政的风险”，那就是，美国在逼、俄罗斯在顶、有时候中国也要伸伸手，去拉一把。

我们知道，这些国家本身都来源于前苏联，也就是说，在过去近一个世纪的时间内，不论是政治、经济、还是军事、甚至是人员成份，都与俄罗斯有着千丝万缕、却又剪不断、理还乱的联系，从而又不可能与俄罗斯一刀两断。

再就是吉尔吉斯斯坦，由于与中国接邻，受中国经济影响也非常大，也不可能只顾及俄罗斯和美国的利益。如此一来，这些“小个子的渔翁”要想在自己的切身利益、与上述在大国利益之间保持平衡就开始困难了。

在这种情况下，原来都想做个“小个子的渔翁”的、格鲁及亚、乌克兰、吉尔吉斯斯坦的前统治者，在“玩转大国”的过程中、其实正在离危险越来越近。

在东方评论员看来，随着这些国家内部矛盾的日益尖锐化，特别是经济不振引发的贫富两极化，自然会反映到国内民意、朝向对政府不满的方向变化，加上这些国家又充许美国在国内开设了军事基地，从而更不可能去阻止美国“用美元”培植所谓的民主势力。

根据我们的长期观察，这种不满的快速增长，也就成了美国用“美元和民主”在这些国家内快速扩张自己势力、快速增强自己影响力的良机。


*** “新生事物”华盛顿在力量壮大之后、自然会“反客为主”

首席评论员指出，随着“美俄”势力在各国政治势力中的此消彼涨，原来不过是“新生事物”的华盛顿、在力量壮大之后，自然会反客为主、向当地政权提出更多、也更加实质、具体的要求，以图将“利益的天平”往美国这边挪一挪。

在东方评论员看来，不论这种要求是什么，其目的都只有一个，那就是挤压俄罗斯在上述国家的利益、压迫俄罗斯的战略空间，并遏制中国在当地的影响。

显然，面对华盛顿在自己国内培植“民主”势力已经坐大，可以说不论是格鲁及亚、还是乌克兰、更或是吉尔吉斯斯坦的“前统治者”，都心知肚明，然而，对他们而言，是知道了、但也已经晚了。


*** “鸡蛋”上跳舞的整个过程，可以总结出很多“经验与教训”

对他们而言，尽管可通过反省在“两个（美俄）”、或者“三个（美俄欧）、（美俄中）”“鸡蛋”上跳舞的整个过程，总结出很多的“经验与教训”，但是，由于“过去的舞台”早已经不复存在，因此，以“成王败寇”的事实、去反省“这一段”的话，那么，对这些统治者而言，恐怕得到的只是教训而已。


*** 另两个有必要“反思”的国家，恐怕就是俄、中了

在东方评论员看来，另两个值得反省的国家，恐怕就是俄罗斯和中国了。我们认为，由于俄罗斯将上述国家、及整个中亚都视为自己的传统领地，因此，它在积极抵抗华盛顿渗透、掠夺它的同时，它历来的做法，就是在拼命与美国搏斗的同时，还没有忘记要“不时地转过头来”、用眼睛死死地盯着北京，防范着北京在中亚的一举一动、唯恐中国趁虚而入。

根据我们观察，中国和俄罗斯是“上海合作组织”中最大的两个成员国，也是两个最有力量的核心国家，也正是中国和俄罗斯之间有着某种“不默契”，才给了美国在中亚大搞“颜色革命”的空间、也正是中国和俄罗斯之间有着某种“不默契”，才让华盛顿在搞掉了格鲁及亚、乌克兰、清除俄罗斯的外围之后，居然直接将手伸到上海合作组织、伸到了中国身边的吉尔吉斯斯坦。

*** 华盛顿在吉尔吉斯斯坦的动作，不过是在“试试水温”

首席评论员一早就指出，华盛顿在吉尔吉斯斯坦的动作，不过是在“试试水温”，看看有着“中俄”两大力量的“上海合作组织”有何反应。也如我们之前讲过的那样，事实证明，“上海合作组织”两个最有力量的核心国家之间的仍然缺少“默契”，“上海合作组织”事实上没有采取任何有效的动作。显然，华盛顿的目的暂时似乎达到了。

*** 如果站在美国的立场去看，这明显是“考虑不周”

然而，东方评论员注意到，西方有战略分析人士当时就指出，华盛顿在吉尔吉斯斯坦的行动，看起来“得分”，然而，如果站在美国的立场去看，这明显是“考虑不周”。

对此，我们深以为然，在东方评论员看来，该分析人士提示了三层意思，我们归纳了一下、大意如此：

第一，就如我们在3月份的点评中所一再强调的那样，在吉尔吉斯斯坦，由于旁边就是中国和俄罗斯，该国的正常运转、根本就离不开这两个大国，因此，不论是谁上台，都不可能全面倒向华盛顿。

*** “颜色革命”将彻底“点醒”中亚国家和俄罗斯

第二，华盛顿在吉尔吉斯斯坦的“颜色革命”，将彻底“点醒”中亚国家，促其统治层检讨自己的“平衡政策”的利弊、认清“玩转大国”的风险、以扎牢篱笆。

第三，就是客观上“有可能”帮助俄罗斯“正确评估”自己的实力，“下决心默许”中国在中亚发挥更大的作用、以挤压华盛顿在该地区的渗透力。

在东方评论员看来，第三点尤其重要，可以说该学者“点到了问题的关键”。显然，对美国而言，这的确是试探“上海合作组织”到底是个什么组织的好机会。面对美国在中国本北部这个邻国的突然发难，在公开场合，从来都是严宣示主权和实力不干涉他国内政的中国、突然发现自己“没有发言权”，也就是说，尽管中国是上海合作组织的倡议国，也是核心成员国，然而，在看着华盛顿在自己的身边“伸手试探水温”，并在自己眼皮底下，将吉尔吉斯斯坦这个“上海合作组织”“反恐中心”所在国的“整盆水”、彻底搅浑、而不能说什么、更不能做什么。

显然，北京之所以没有发言权、就在于两点：第一，“上海合作组织”根本就是个“无牙老虎”，中国不能援引“上海合作组织”中的任一条“去做什么”；第二，俄罗斯对中国不放心，中国在对中亚局势做什么的时候，必须考虑到与俄罗斯的关系。而俄罗斯却根本就没有什么强硬对策、去维持它自视是自己领地的吉尔吉斯斯坦政局稳定。

结果是，俄罗斯的力量、或者是“上海合作组织”的力量，那次显得太弱了，在华盛顿发动的民主攻势下，根本就不足以成为该国政权的依靠，并保障该国政局的稳定。


*** 意味着俄罗斯“承认自己不再单独有能力”保持中亚的稳定

因此，在东方评论员看来，中乌两国签署“友好合作伙伴关系条约”，再加上吉尔吉斯斯坦方面有意“同意以俄罗斯为中心的独联体(CIS)集团安保条约和包括中国在内的上海合作组织成员国的部队驻留”，这“两条”很可能是建立在“各成员国”有意修改“上海合作组织”章程之基础的，如果果真如此，那么，这将意味“上海合作组织”各成员国都确认“有必要共同行动、以军事手段保障区域内的安全和稳定”，这也将意味着俄罗斯“承认自己不再单独有能力”保持中亚的稳定、从而意味着俄罗斯愿意让中国在中亚进一步发挥作用，从更深层次去与中国进行区域内战略合作、以缩减美国在该地区渗透的空间；

*** 乌政府在刻意避免重走“格、乌、吉”三国“颜色革命”的老路

最后，这还意味着中亚国家、甚至是俄罗斯、都的确被这几场“颜色革命”“点醒”了，在东方评论员看来，从乌政府在处理骚乱事件所表现出的“决策果敢、手段严厉”、并在事后顶住美国的压力，与中国签定“友好条约”的整个过程来看、乌兹别克斯坦政府在刻意避免重走“格、乌、吉”三国“颜色革命”的老路，不难看出，如果乌兹别克斯坦国内的“骚乱事件”最终给“上海合作组织”配上了一副牙齿，从而让中国和俄罗斯一起，可以相互配合，名正言顺地担负起区域内安全保障责任，那么，这将对整个中亚、甚至象伊朗、巴基斯坦这样的外围国家的安全，都能起到一种辐射和吸引作用。

*** 具备军事手段的“上海合作组织”、就能为这些国家提供这样一个靠山。

东方评论员注意到，孔泉今天在记者会上表示，“上海合作组织”期望同其他地区组织和国家开展交往、增进互信、加强合作的意愿。而且“有些国家包括巴基斯坦希望成为上海合作组织的观察员，进一步发展同上海合作组织的关系”。

显然，巴基斯坦的意向说明，许多对自己国家安全感到担心的国家，都在想办法寻找一个靠山。而一个具备军事手段的“上海合作组织”、就能为这些国家提供这样一个靠山。在这种情况下，乌兹别克斯坦还会接受什么、旨在搞乱该国政局的“国际调查”吗？恐怕不可能！

在我们看来，“配上了牙齿”的“上海合作组织”将对中国的中亚政策产生巨大的助益，我们也认为，对中俄间进一步消除彼此的戒心，进一步深化双方的战略合作也将产生巨大的助益。当然了，这一切的“好处”，必须有个前提，那就是各成员国、特别是俄罗斯一致同意，修改“上海合作组织”章程，承诺由成员国提供的军队、去保护成员国的国家安全与政治稳定。

下面，我们将把关注的焦点投向欧洲。下面是一则来自德国的消息，在一起阅读之后，东方评论员将就德国总理施罗德的政治前程展开讨论，并以此作为今天欧洲部分的开始。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
