# -*- org -*-

# Time-stamp: <2011-08-02 19:44:27 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

#+STARTUP: indent

* 2005年03月18日 星期五

** 大陆「反分裂国家法」引爆两岸华府外交战

【台湾消息】 据东森新闻报报导，中国大陆反分裂国家法在华府引爆两岸外交战，一向对台湾友好的美国国会成为台湾反攻的前哨，台北驻美代表李大维除了私下密集拜访国会议员，3月16日也亲自到众议院发表演说，希望争取美方的支持，将反分裂法所引发的危机化为对台湾有利的转机。

美国联邦众议院16日针对谴责反分裂法的决议案进行表决，台北驻美代表李大维亲自到国会山庄坐镇，掌握议员投票的情形，并接受国会台湾联机议员邀请，以「台湾与中国的关系及中国的反分裂法」（Taiwan-China Relations and China’s Anti-Secession Law）为题发表演说，向议员们说明反分裂法对两岸关系的冲击。
 
李大维以两岸春节包机，陈水扁表明任内不宣布「独立」等具体措施为例，表示两岸关系正在缓和，大陆提出这项法案，对和平没有帮助，他说，「反分裂法不但不利两岸关系，也对世界秩序造成严重伤害，我们希望不论是美国国会还是行政部门，都不要低估反分裂法的严重性。」这场演说有11名众议员出席，会后进行私下会晤。
 
另台据中央社报导，李大维提出反分裂国家法的四点严重影响，第一、中国对台湾的直接威胁更加扩大，第二、台湾海峡原本就脆弱的稳定出现动摇；第三、反分裂法完全否定和平、自由、民主、人权以及对国际社会负责的普世价值，不顾亚太地区的和平及发展；第四、反分裂法挑战台湾关系法。
 
他并以最新民调显示，93%的台湾民众反对反分裂法，91%表示台湾前途应该由台湾自己决定，80%表示愿意维持现状、不接受一国两制。他批评反分裂法蔑视美国对台政策的精髓，也就是不片面改变现状以及和平解决歧见，反分裂国家法不像中国所宣称是一部和平的法律，而是缩短中国对台动武的决策时程。
 
北京去年底拋出反分裂法之后，华府成为两岸外交战的竞技场，在第一线作战的李大维除了不断和行政部门沟通，掌握布什政府的反应，也密集拜会美国国会友台议员争取支持。
 
反分裂法通过后，李大维认为最大的挑战就是要化危机为转机，向美方寻求弥补的措施，将局势扭转到对台湾有利的方向。李大维表示，「我们希望美国对反分裂法，持续采取坚定而有原则的立场，我们也希望美国重申台湾关系法中防御台湾的承诺。」
 
众院以424比4通过决议案，敦促布什总统对反分裂法提出严重关切，李大维对压倒性的票数感到满意，但也随即指示代表处同仁，去看看是哪四位众议员投下反对票，滴水不漏的外交战，是希望台湾在反分裂法的风暴中转危为安。
 
中央社并引述台湾「外交部长」陈唐山17日透露，美众议院通过决议案，对反分裂法表达严重关切后，「这两天美国参议院也会通过类似决议」；他说，台湾冷静因应反分裂法，「好处慢慢会来」，包括「我们讲的话，美国会比较信任」、美方支持台湾参与国际组织等。
 
他说，反分裂国家法草案版本出炉后，美方期待台湾政府「冷静以对」；陈唐山认为，台湾在因应作为上持相当克制的冷静态度，在国际宣传上，可将「理性文明的台湾」与「野蛮无理的中国」显出强烈对比，把「麻烦制造者」的形象丢给中方。
 
陈唐山透露，台湾的冷静获得美方肯定，他相信「好处慢慢会来」，包括台美交流更趋频繁，「我们讲的话，美国会比较信任」，继续支持台湾参与世界卫生大会等国际组织。他说，这种微妙变化，近期驻美代表李大维与美方的互动，李大维已感受到「双方气氛好多了」。
 
中国通过反分裂国家法后，中方是否可能在外交领域作出补偿？陈唐山说，「不敢有此奢望」；如果中国真的有诚意弥补对台湾的伤害，就应该放弃打压台湾国际生存及活动空间，不是只给一点小惠、甜头给台湾尝。
 
 
 
 
【台湾消息】 对于美国众议院于16日针对谴责反分裂法的决议案进行的“表决”，东方评论员在昨天已经给出过自己的观点，在我们看来，尽管该“决议案”是对美国政府“毫无约束力的”、根本就是一种“声明性”的“决议案”、要以此来解读成什么两岸的“外交战“、恐怕有点“名不符实”。
 

*** 美国政治层对“反分裂法”是何等的“敌视与无奈”

但是，从此中可以清楚地看出，美国政治人物对中国的统一、对这部几乎让美国的“与台湾关系法”暗然失色的“反分裂法”是何等的“敌视与无奈”。

我们注意到这么一段，原文是：众院以424比4通过决议案，敦促布什总统对反分裂法提出严重关切，（台北驻美代表）李大维对压倒性的票数感到满意，但也随即指示代表处同仁，去看看是哪四位众议员投下反对票，滴水不漏的外交战，是希望台湾在反分裂法的风暴中转危为安。
 
众所周知，美国众议院是“管钱的”、而美国参院才是“管外交的”，这就是说，没有美国参院的“掺和”，这种涉及外交的“决议案”，实在是没有什么“意思”。
 
然而，按美国的宪政体制，就算是美国参院的“掺和”，也通过了一份类似的“决议案”，如果最终“无法形成”对美国总统有约束力的“决议法条”，那么，我们也看不出这与“单纯地发泄情绪”有什么区别，也没有什么“实质性的意思”。
 

*** 台湾当局和华盛顿的这一套把戏，玩来玩去，玩的就是给台湾社会看的
 
就再退一步讲，就算是美国参、众两院最终“形成了”对美国总统有约束力的“决议法条”，就象上面所说的那样，要求布什政府“对反分裂法提出严重关切”，这反而会成为一则让国际社会的感觉“幽默”的“笑话”，不是吗？布什政府早已经“对反分裂法提出严重关切”了，用得着美国国会“兴师动众”专门要求布什这样去做吗？

由此可见，华盛顿和台湾当局的搞的这一套把戏，玩来玩去，玩的就是给台湾社会看的、其目的就是要让台湾社会相信“美国太在乎台湾了”。
 

*** 420位美国议员在那里“同仇敌慨”般地表示着“严重关切”，实在是有点搞笑

在东方评论员看来，从新闻稿的字里行间，我们不难看出李大维的“得意”，不是吗？他竟然还要看看“是哪四位众议员投下反对票”！然而，就如我们之前所说的那样，就是这么一份台湾花大本钱啃下来的这份“决议案”，仍然不敢对“反分裂法”说“反对”这个词，而是沿用了美国政府的“统一口径”、结果是420位美国议员在那里“同仇敌慨”般地表示着“严重关切”，实在是有点搞笑。
 

*** 不难看出，“反分裂国家法”的生效，对“台独”和支持台独的国际势力的反击是非常沉重的

我们不清楚这位深谙美国政治架构的“台北驻美代表”、在听到“420位美国众议员”“在那里齐声高唱”着的只不过是“敦促布什总统对反分裂法提出严重关切”、而不是提出“反对”的时候，心里真的就和表面上所表现出来的一样，果真是那么的得意吗？
 
只是，对这一点一定非常清楚的“台北驻美代表”、却偏偏表现得对这一成果“如获致至宝”，而美国的国会，却也愿意这就么陪着台湾“瞎胡闹”，从整个事情中不难看出，“反分裂国家法”的生效，对“台独”和支持台独的国际势力的反击是非常沉重的。
 

*** 这部“深具弹性”的“反分裂国家法”正式生效后，已经对世界格局产生了重大影响

事实上，在东方评论员看来，李大维还是“有两下子”的，请大家注意这么一段，他说“反分裂法不但不利两岸关系，也对世界秩序造成严重伤害，我们希望不论是美国国会还是行政部门，都不要低估反分裂法的严重性。”

我们认为，他这句话说到点子上了。在我们看来，这部“深具弹性”的“反分裂国家法”正式生效后，必将、而且实际上已经对世界格局产生了重大影响。首席评论员曾经多次指出，如果北京能成功地制定出一部超越“台湾问题”、着眼于世界格局的“反分裂国家法”，那么，华盛顿在筹划其全球战略的时候，将继中东问题之后、再次意识到自己的“战略失败”。
 

*** 美国的这种“战略失败”就主要表现在这么两个方面

时事评论员们普遍认为，美国的这种“战略失败”就主要表现在这么两个方面，有意思的是，在第一个方面上，这位李大维已经“替我们总结出来了”，我们在这里也不妨援引一番：他说，“我们希望美国对反分裂法，持续采取坚定而有原则的立场，我们也希望美国重申台湾关系法中防御台湾的承诺。”

显然，李大维是“非常清楚”美国对“反分裂法”“反对”与“严重关切”两种立场之间“天壤之别”的。然而，让台湾当局遗憾的是，美国的行政、立法两大系统在表达”反对“”反分裂法“的情绪上，其用词上是高度的统一、是除了“严重关切”还是“严重关切”。
 

*** 华盛顿在亚洲安全体系中的权威已经严重受损

东方评论员的观点是，不难看出，在全球格局中被动的华盛顿、这一次在“反分裂国家法”的面前的确“软了”，也就是说、就在台湾当局、日本希望华盛顿能“重申台湾关系法中防御台湾的承诺”的等待中，在韩国、澳大利亚、英国、以色列观察华盛顿是否敢于在这个时候“重申”、以确定是否有必要为自己的外交政策“引入一点新元素”的时候，由于华盛顿不敢在这个时候“重申”“防御台湾的承诺”，如此一来，事实上在美国的盟国的眼中，其《与台湾关系法》的信用已经严重受损，美国在亚洲安全体系中的权威也已经严重受损，继而，美国在世界体系的霸主权威也受到了损害。
 

*** 中、欧、俄罗斯、甚至日本、都有可能重新审视美国的地位

可以肯定的是，今后，中、欧、俄罗斯、甚至日本、都有可能重新审视美国的地位，重新审视它们与美国的关系，也将重新审视彼此之间的关系。在东方评论员看来，中日关系是否会以此为契机、慢慢有些积极信号出来，也是值得我们观察的看点。
 

*** 在“中美和台湾之间”的游戏中，“极具弹性”的“反分裂法”、从根本上取代了“一度有弹性”的“与台湾关系法”
 
另外，美国的战略失败，还表现在华盛顿以前那种“随意解读”、“玩转”《与台湾关系法》的手法、在充分体现中国政府“战争意志与决心”的“反分裂法”生效后、已经走进了历史。
 
东方评论员看到的结果就是，“反分开国家法”以自己战争意志、从根本上压缩了华盛顿随意解读“与台湾关系法”的弹性，换而言之，在“中美和台湾之间”的游戏中，一个弹性的“反分裂法”、从根本上取代了一度弹性的“与台湾关系法”。
 

*** 今后一个非常值得关注的问题
 
因此，可以想像的是，随着国际局势的进一步演变，一旦华盛顿决定再度调整中东政策、台湾政策，那么，是否会以修改这个“已经没有了弹性”的“与台湾关系法”、并以“这个修正过程”为切入点，引导另一轮的、“武力拒统”式“台独进程”、将是非常值得关注的问题。当然了，这是后话，今天在这里我们不打算对这个话题进行展开。

如此可见，也正是因为有这么一层，所以在东方评论员看来，美国新保守主义主导美国外交政策之后，特别是在其伊拉克政策陷于困境之后，为了防止中欧接近、过分相信“强硬的支持台独”将可以换取“更多的中国让步”，终于在伊拉克、伊朗问题“无解”、导致其中东政策走进“死胡同”之后、又将其一向左右逢源的“对台政策”、也给引进了死胡同，从而导致中美在朝核问题、台海问题上的关系、日益更象是种“全面对抗”关系。
 

*** 北京和华盛顿、目前都在想办法避免这一极大压缩双方国际回旋空间的糟糕结局

事实上，中美的这种“全面对抗”的关系还没有彻底成形，但是，已经因为“美日安全共同声明”涵盖台湾、北京公开支持“宣布有核的朝鲜”、而几乎接近于成形。对这种结果，我们注意到，美国的战略人士就感叹说，“反分裂法”生效是不幸的，这种“不幸”造成的结果、就是华盛顿有对外政策、在继中东政策失败之后、遭遇的又一次“重大失败”。

首席评论员指出，我们之所以认为中美“对抗”关系“接近于成形”，就在于北京和华盛顿、目前都在想办法避免这一极大压缩双方国际回旋空间的糟糕结局。

下面是一则来自日内瓦联合国人权委员会的最新消息，在一起了解相关背景之后，东方评论员将继续讨论这一话题。
 
《东方时代环球时事解读》http://www.dongfangtime.com

** 美国首次不提反华人权议案，中方对此表欢迎

【日内瓦消息】  综合报道，正在日内瓦参加联合国人权委员会（人权会）第61届会议的美国代表团17日举行新闻发布会，正式宣布不在本次会议上搞反华提案。对此中国代表团团长、中国常驻联合国日内瓦办事处及瑞士其他国际组织代表沙祖康大使说，美国这一决定既有利于中美之间的人权对话，也有利于两国人权状况的改善。
 
美国将不提出批评中国人权的议案
 
美国代表团17日举行新闻发布会，正式宣布不在今年的联合国人权委员会议中搞反华提案。这将是10多年来美国首次没有提出批评中国的议案。据BBC报道，不愿意透露身份的美国官员说，美国代表已经通知人权委员会中的50多个其它成员有关美国的决定。多年来，有关中国人权纪录的问题已经成为了联合国人权委员会中的激烈争论点，而美国也连续多年提出批评中国人权纪录的议案。
 
美国官员说，美国方面多年来一直同中国就人权问题保持接触，而且在过去一年中取得了一点美国方面喜欢的进展。去年10月，美国国务卿鲍威尔曾经表示，美中两国已经达成协议，旨在重开有关人权问题的对话。
 
有分析认为，美国今年不在联合国提出中国人权纪录，可能与美国国务卿赖斯将在3月20日访华有关，在此之前，美国国务院在2月28日发表了有关包括中国在内的多国国家的人权状况的报告。另据美国媒体报道称，美国国会两党议员对布什行政当局的这一决定表示不满。
 
为了反制美国每年在人权问题上对中国的诘难，中国近年来也由国务院提出美国的人权记录。今年中国官方发表的《2004年美国的人权纪录》说，美国政府理应反省自己的所作所为，正视自己存在的严重问题，而不应热衷于发表“人权报告”对其他国家进行指责。
 
中国表示对抗不得人心
 
沙祖康接受新华社记者独家采访时说，美国决定不在人权会上搞反华提案是件好事，这避免了中美在人权会上的对抗。对抗不得人心。在美国放弃对抗的情况下，中国愿与美国在平等和相互尊重的基础上进行对话，共同解决各自在对方人权问题上的关切。
 
沙祖康说，保护和促进人权是长期的系统工程，也是没有止境的。在人权问题上，世界上没有一个国家是完美的，中国和美国也不例外。沙祖康认为，美国决定不搞反华提案是明智之举。他说，中国反对对抗，但也不惧怕对抗。新中国成立以来特别是改革开放以来，中国政府一直高度重视人权，并不断促进和改善人权。中国新一届政府更是鲜明地提出了“以人为本”的执政理念。
 
中国呼吁成员国多一些合作
 
据新华社报道，此前，中国常驻日内瓦联合国代表团团长沙祖康大使代表发展中国家“相同观点集团”在会上发言，呼吁人权会成员国之间多一些合作与对话，少一些指责与对抗，共同为恢复人权会的作用和声誉而努力。中国代表的发言受到各方广泛关注，发展中国家对此普遍表示赞赏和欢迎。
 
“相同观点集团”由近20个发展中国家组成，是近年来活跃在国际人权领域的重要组织。中国今年连任该组织协调员。由53个成员国组成的联合国人权委员会每年3月至4月在日内瓦举行年会，本次会议预计于4月22日结束
 
 
 
 
【时事点评】 我们注意到，按美国官员的说法，华盛顿“正式宣布”不在本次会议上搞反华提案，是因为中国人权在过去一年中“取得了一点”美国方面喜欢的进展。
 

*** 华盛顿根本就是在“言不由衷”

然而，在东方评论员看来，华盛顿说中国人权在过去一年中“取得了一点”“让美国方面喜欢的”进展根本就是在“言不由衷”。

然而，就在欧美为欧盟“解禁对华军售”的争吵处于关键时刻，就在美国一向“以人权为硬理由”对欧盟“晓之以情、动之以理”、最后干脆公开威胁欧盟“不要解禁”的时候，美国人自己却在“中国人权问题上”突然“撤火”、并肯定了中国在过去一年中“取得了一点”美国方面喜欢的进展，如此“自相矛盾”、就不担心由此引起的来自国际社会的“耻笑”吗？
 

*** 布什何以如此“不顾体面”？

显然，如果美国人说的是真话，那么，华盛顿在过去一年里、一直在“拉高调门”、“以人权为理由”强烈指责“欧盟解禁对华军售”的行为，就实在是太虚伪了。

对此， 首席评论员指出，华盛顿之所以“不顾体面”、抢在这个时候继续向北京示好，其原因还是在为赖斯的访华“尽管 可能地营造出轻松的气氛”。
 

*** 我们不认为有关台湾及“反分裂法”的事情是中美这次战略对话的焦点

我们认为，赖斯此番前来，重点的话题有三个，一是朝鲜问题、再就是日本问题、最后就是伊朗核问题，在东方评论员看来，我们之所以不认为有关台湾及“反分裂法”的事情是中美这次战略对话的焦点，就在于为了配合赖斯的这次访问，华盛顿可以说是“煞费了一番苦心”，在我们看来，台湾问题已经被华盛顿“煞费苦心”定位在了“筹码”的层次。

我们知道，北京要制订“反分裂法”，是在去年十二月十七日由中国最权威的官方通讯社--新华社对全世界进行“广播”的，到今年3月4日胡锦涛主席提出“四点意见”，再到3月8日王兆国对“反分裂法”的“草案”正式给予“说明”，最后到十届全国人大三次会议闭幕时、审议通过，可以说这一过程是漫长和公开的。

因此，在东方评论员看来，在3月14日通过“反分裂法”时、恐怕可以说台湾全岛上下、是妇孺皆知，这就是说，如果陈水扁当局、或者民进党早就拥有充裕的时间、去“筹划”如何反对“反分裂法”的游行活动。
 

*** “台独”将“大游行”的日期放在下一个星期六，根本就是在等待华盛顿的“指令”

如果我们站在岛内“台独”势力的立场来看，那么，这个被“台独”冠之以“反制”“反分裂法”的所谓的“大游行”的最佳时间，就应该在“反分裂法”刚刚通过的本星期的星期六、星期日进行，也就是3月19日、或者是20日。

然而，3月20日却刚好是美国国务聊赖斯抵达北京的日子，这就是说，就“时间”这一因素而言，东方评论员认为有两个方面值得一提，第一，“台独”势力将“大游行”的日期放在下一个星期六，根本就是在等待“中美交锋”的结果，也就是说，在等待华盛顿的“指令”，然而，这还只是问题的一个方面。

我们认为，就在“台独”等候赖斯访华消息的时候，华盛顿又何尝不会和“台独”私下里“眉来眼去、暗通消息”？
 

*** 美一直在为赖斯就任美国务聊首次访华“准备着筹码”

在东方评论员看来，从华盛顿近来一连串动作来看，布什为了配合赖斯的“顺利访华”，可以说是一直在为赖斯就任美国务聊首次访华“准备着筹码”。粗粗数来，不包括赖斯自己访问南亚的印度和巴基斯坦，试图影响南亚局势，从而为自己的访华“拉抬声调”的努力在内，白宫的决策层在朝鲜方向、伊朗方向、以及台海方向也都做出了一系列的部署：
 

*** 白宫决策层为了赖斯的“一路顺风”，可以说是“做了不少的实事”

首先，我们说了，赖斯此次前来的一个重大议题，就是朝核问题。东方评论员注意到，赖斯于13日启程、正式展开对中国和韩国等亚洲六国的外访的之后，几乎是第到一站，都忘记不了要对朝鲜“叮咛”几句，特别是赖斯当天在前往亚洲访问的第一站印度，我们看到，她“公开揭露”说“朝鲜希望单方面与美国举行会谈”，然而，我们也注意到，这位准备在北京同中国领导人好好谈谈朝鲜问题的赖斯，最后坚定地表示“美国不会答应这一要求”。

与此同时，五角大楼而更是默契，立刻安排美国“小鹰号”航母在韩国展开了一轮近似实战的联合军演，与此同时、美军在日本还不停地放出有关“正在加紧部署两艘新型宙斯盾级驱逐舰”的消息出来，显然，白宫决策层为了赖斯的“一路顺风”，可以说是“做了不少的实事”。


*** 赖斯此言是对华盛顿亚洲政策的“高度概括”，也是其北京之行的“主题宣示”

另外，东方评论员注意到，美国国务卿赖斯日前就对媒体表示，美国不是“反中国”的，但华盛顿对中国军事现代化的情况十分关注。
 
首席评论员指出，赖斯此言是对华盛顿亚洲政策的“高度概括”，应该视为她对这次北京之行的“主题宣示”。在我们看来，如果将这句话“翻译过来”，其意思非常清楚，那就是说，美国将继续以“美日军事同盟”为核心确保台海现状的稳定，美国将“美日军事同盟”是否包括台湾当作一种“筹码”、并准备在这一层面上与北京“有话好好说”。
 

*** 华盛顿应该清楚，朝核问题已经是“今非昔比”

然而，东方评论员认为，如果赖斯“死抱着”“这种意思”到北京访问，恐怕很难指望在朝鲜问题上会从北京给布什带去什么“好消息”。

我们认为，华盛顿应该清楚，朝核问题已经是“今非昔比”：日本在“大年初一”抛出了“钓鱼岛主权争端”，而朝鲜紧跟着在“大年初二”宣布自己有核，就在日本和朝鲜这般的“夹枪带棒”之下，北京和华盛顿，更是各展手段：就在华盛顿怂恿日本在钓鱼岛闹事，而将一个“相对单纯”的中日“钓鱼岛争端”、涂抺上“美日台军事同盟”的“新色彩”的同时，一直在朝核问题上“陪着”华盛顿“打太极”的北京、也将一个“相对单纯”的“朝美”“朝核问题”加进了“东亚核竞赛”的“底料”。
 
 
*** 一直想在“朝核问题”“打太极”、“拖时间”的华盛顿、第一次有了“紧迫感”

首席评论员指出，不可否认，华盛顿在“钓鱼岛争端”上涂抺“美日台军事同盟”“新色彩”的同时，的确让北京感到了华盛顿正在着力准备“台独牌”的“空前危险”，然而，作为反击、北京将“朝核问题”加进了“东亚核竞赛”的“底料”、而日本出于自己的政治、军事野心、不顾美国的“感受”、且“非常配合地”在东亚一味地“搞事”，而朝鲜也是一味地“和着”日本的节拍、顺着日本的“核心理”、在那里给日本“担茶送水”、陪着日本玩、这些立刻让一直想在“朝核问题”就这么“打太极”、“拖时间”的华盛顿、第一次有了“非妥善解决不可”的“紧迫感”。
 

*** 华盛顿之所以愿意看到“南亚核竞赛”、而不愿意看到“东亚核竞赛”，就在于东亚有个日本因素

其次，就是日本问题，在东方评论员看来，“朝核问题”之所以让华盛顿有了“紧迫感”，就在于“东亚核竞赛”这个因素。现在，赖斯正在南亚访问，南亚两国就是在”南亚核竞赛”的情况下，在华盛顿睁一眼、闭一眼的默许下、一夜之间成了核国家的。

然而，华盛顿之所以愿意看到“南亚核竞赛”、而不愿意看到“东亚核竞赛”，就在于东亚有个日本因素。事实证明，华盛顿的这一选择是不错的，在印度成了核国家之后，给北京造成的麻烦，远大于给华盛顿带来的“不方便”。

但是，日本就不同了，可以肯定地说，一旦“朝核问题”最终演变成“东亚核竞赛”，而将日本送进了核门槛，那么，按美国的战略家所评估的就是，它将给华盛顿造成的“灾难”，远大于给北京带来的“麻烦”。换而言之，“南亚核竞赛”和“东亚核竞赛”对美国而言，其结果是完全相反的。
 

*** 如果赖斯还在那里“一味强硬”....?

因此，在东方评论员看来，在这种情况下，如果赖斯还在那里“一味强硬”，死抱着针对中国的“美日军事同盟”不放，但愿这只是表面上的宣言，而不是实际上的底线，如果不然，赖斯的这次访问，与她去年7月的那次同样旨在解决朝鲜问题的“访华失败”相比，结果不仅好不到哪去，而且很有可能引发朝鲜的更进一步的、挑逗日本的动作。

事实上，北京让华盛顿难受的选择还有，那就是继续加强与欧盟、俄罗斯的战略合作，近段来，我们清楚地看到，北京在伊朗核问题上一直“没怎么发声”、这本来就是一种“态度”，也就是说在北京不会从伊朗问题上撤手的同时，愿意考虑不主动刺激华盛顿的神经。

然而，从日前华盛顿再一次公开指责“中国继续向伊朗转移敏感武器技术”一事来判断，美国人显然拒绝将北京在伊朗核问题上的“没怎么发声”、“当成”是北京“已经在照顾”华盛顿的“感受”、是在向华盛顿让步的“事实”。
 

*** 一旦赖斯这次访华再次失败，北京和华盛顿都将面对如何收场的问题

由此可见，一旦赖斯这次访华再次失败，北京和华盛顿都将面对如何收场的问题，第一，北京很可能就得准备承受华盛顿大规模提升与台湾军事合作的压力，以及“台独”挟“美日军事同盟”、再次走向“某种形式独立”的危险，显然，如何解释“反分裂法”、是否启动“非和平方式”，也就摆到了北京的面前。
 
而与此同时，华盛顿就得掂量一下，它自己如何面对一个更加强硬的朝鲜，以及一个与自己渐行渐远的韩国、还得准备面对一个战略上对华盛顿更显重要的日本、以及日本会借此拉抬身价、向华盛顿“伸手索要”“核武器生产许可证”、放松军事控制的危险。总之，美国目前依赖韩国、日本、台湾、并在控制日本、台湾的基础上建立的与中国维持平衡的军事防线，就可能立刻瓦解。如此一来，在中东问题仍然不知何去何从之际，华盛顿就得“提前面对”“重新安排”亚洲安全框架的“战略性大调整”，在这一点上，我们至今还没有发现、哪怕是一位的美国战略分析人士、公开提出过“相应的可行方案”来。
 
 
*** 政治的现实性、是会让“中、美决策层”考虑以另一种形式进行较量的

显然，这种局面一旦形成，对中美双方的利益都是一种极大的损害，所以，在我们看来，政治的现实性、是会让“中、美决策层”考虑以另一种形式进行较量的。

中美之间就算这次谈不好，也不至于一步彻底“闹翻”。由于“台独”的高度敏感性，华盛顿很可能不敢在这方面挑畔北京、以作为向北京施加压力的手段，但是，一步步提升美台军事合作层次同，为“武力拒统”做准备，就如北京一步步通过朝鲜刺激日本一样，催发日本国内对美国的不满、离间美日、韩美关系、都是中美双方在东亚较量中、可以为对方制造麻烦、刺激对方神经、而可以“边谈边做”的事情。
 

*** 看到美国在“朝核”、“反分裂法”问题上受到挫折、欧洲和俄罗斯“立刻行动起来”

此外，对北京而言，美国在国际问题上事实上已经是“孤家寡人”，这就让中国有更多的选择项去从全球格局上去反击华盛顿。在东方评论员看来，可以肯定的是，如果赖斯这次访华再次失败，如果我们再次看到中国在伊朗核问题上、在关键时刻站到第一线，或者再次听到北京对华盛顿的伊朗核政策说“NO”，我们将一点也不会意外。

事实上，同样看到美国在东亚安全问题上、在朝核问题上、在“反分裂法”问题上受到挫折的欧洲和俄罗斯、也不想放过利用华盛顿“又一次失败”、中美“有可能走向对抗”的机会，在进一步拉拢北京的问题上，可以说欧洲和俄罗斯“是立刻行动起来”。
 

*** “反分裂法”的正式生效，不仅不会影响欧盟“解禁”、更会促进欧盟“解禁”

按现在的大国博弈局势，东方评论员认为，尽管在“反分裂法”的问题上，欧盟内部“有些杂音”，但是，可以肯定的是，“反分裂法”的正式生效，不仅不会影响欧盟“解禁”、而且还很可能会促进欧盟“解禁”，在东方评论员看来，欧盟内部有“杂音”是欧盟内部的问题，欧洲领导人不是一直顶着这些“杂音”、在国家利益的吸引下走到这一步的吗？
 
另外，从华盛顿在这个时候说出“中国人权有改善”之一类的话来看，显然，美国对“解禁”问题已经没有抱太大希望，因此，我们认为，既然华盛顿都没有指望这种“杂音”能帮助它阻止“解禁”，我们又何必多此一举呢？

下面，在一段有关欧盟和俄罗斯对“反分裂法”的最新评价之后，我们将提前进入今天的欧洲部分，看看欧盟和俄罗斯是如何给华盛顿“下套”的。
 
 
 
《东方时代环球时事解读》http://www.dongfangtime.com
