# -*- org -*-

# Time-stamp: <2011-08-02 13:37:40 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil


* 2005年03月16日 星期三

  

** 朝称不能背着“暴政据点”恶名参加六方会谈

   【平壤消息】朝鲜外务省发言人16日发表声明说，如果美国不收回对朝鲜“暴政据点”的侮辱性言论，朝鲜参加六方会谈将是“无法想象”的。

   发言人说，赖斯最近在接受英国路透社和美国《华盛顿时报》采访时表示，不会为自己称朝鲜为“暴政据点”而道歉。

   发言人说，美国一方面称自己的谈判伙伴为“暴政据点”而且拒不收回此种言论，一方面又希望自己的谈判伙伴尽快返回六方会谈，这本身就不合逻辑，实际上与放弃六方会谈也没什么两样。如果美国真想重开六方会谈，就必须收回这种侮辱性的言论，以现实、理智态度行事。

   发言人指出，赖斯的言词再一次暴露了美国不愿与朝鲜和平共处、试图孤立和扼杀朝鲜的对朝敌视政策。正因为如此，朝鲜为捍卫自己的政权，维护地区和平与稳定而继续加强自卫性核武库的行动是完全正当的。

   发言人还劝告美国，任何试图通过第三方来向朝鲜施压的想法都是愚蠢的，任何压力都不会使朝鲜改变自己的立场。


   【时事点评】在东方评论员看来，平壤所说的第三方当然是指的北京。我们知道，美国国务聊赖斯又要到北京进行访问了，我们还知道，这个“暴政据点”（暴政据点前哨）的“新名词”本身就是赖斯于1月18日、在正式上任前、于美国国会做听证时率先抛出来的。
 
*** 朝鲜在这个时候提这个要求、其针对性是可想而知的

    因此，在我们看来，朝鲜在这个时候提这个要求、要求美国收回对朝鲜“暴政据点”的侮辱性言论，并以此作为“回到六方会谈”的先决条件之一，其针对性是可想而知的。
 
   然而，在东方评论员看来，朝鲜是否参加六方会谈、其实早已经不是一个朝鲜自己能说了就算的事情了。这就是说，假如华盛顿“能成功地”通过“第三方”来对朝鲜施加强大的压力、那么，朝鲜“不参加”六方会谈也将是“无法想象”的、可问题是，华盛顿能够成功地“游说”北京、通过北京说服平壤回到“六方会谈”吗？

   在进行进一步展开之前，我们认为很有必要再回过头来看看
   #+HTML:<a>与朝鲜问题“脉动相联的”、台湾问题</a>
   #+LaTeX:\red{与朝鲜问题“脉动相联的”、台湾问题}
   上的一些最新进展。

   《东方时代环球时事解读》http://www.dongfangtime.com

** 华盛顿对《反分裂国家法》口头表示“不悦”

   【华盛顿消息】据报道，美国国务院东亚助卿被提名人希尔今日表示，中国制定“反分裂国家法”是一种片面行动，美国促请两岸不要以任何片面行动改变现状。在参议院外交委员会的提名听证会上，希尔答询时说，“反分裂法”于事无补，美国坚持台海争议唯一解决方式是经由和平途径，美国反对使用武力。

   议员问到“反分裂法” 是否涉及改变现状，他回答说，在实质上，这是一种片面行动（approach），美国持续敦促任何一方不要尝试以片面行动改变现状。他重申美国的一贯政策，包括一个中国政策、三个公报、《台湾关系法》以及不支持台湾“独立”。

   国务院例行演示文稿会上，发言人包润石重申上周说过的，反分裂法与最近两岸关系和缓的趋势背道而驰，只会使立场更加强硬。他说，“我们反对任何以和平以外的方式试图决定台湾前途”。有人问及“美国是否会采取任何具体行动以表达不悦”时，包润石回答说，“我想我们刚刚做了”。意指刚才表达立场即是。

   有人问道台湾要在三月廿六日示威抗议一事。包润石表示，他对这些抗议、反应并无任何特别的看法。白宫发言人麦克雷兰则在例行演示文稿会上表示，这项法律是个“不幸”，对台海和平与稳定没有助益，“我们继续鼓励两岸对话，我们相信这对确保和平稳定、降低紧张，非常重要”。

   他说，片面改变现状会升高紧张，所以任何一方都不应如此。
 

   【时事点评】在东方评论员看来，美国官方的此番表态，事实上是继中国通过《反分裂国家法》，美国政府十四日做出所谓的“不幸”、“于事无补”这一类的“不疼平痒的关切”之后的继续。
 
  事实上，我们从来就“没有指望过华盛顿会喜欢”这部《反分裂法》，只是在东方评论员看来，华盛顿表示出“不悦”的本身、不过是为了向台湾岛内“准确地传送”一些北京所说的“错误信号”、而让台湾社会相信：美国“绝对不会”放弃“台湾”，因此，在这个问题上，我们今天不打算多说。在东方评论员看来，倒是美国人围绕着“反分裂国家法”、前前后后所选择的一系列表达“不悦”的“方式和措词”、倒值得我们评上一评。
 
*** 美国“最反对”的就是北京强调“非和平方式”“阻独”的做法

    就在全国人大常委会上周公布反分裂国家法“草案”，确认将以“非和平方式”处理台独问题后，我们注意到，美国政府的“统一口径”是：除重申“反对两岸任一方采取改变现状的片面行动外”，就是“无助两岸关系”、再就是“与当前两岸关系和缓的趋势背道而驰。”

    之后，白宫当时还将“非和平方式”形容成是对台湾的“惩罚性措施”，并以此“呼吁北京重新考虑”。而那位对台湾向来“非常同情”的美国务院亚太副助卿薛瑞福曾经在“反对”“反分裂法”的问题说了最尖锐的一个词，那就是公开批评反分裂法是“错误”，还要求大陆“设法修补”。

    在东方评论员看来，美国“最反对”的就是北京强调“非和平方式”“阻独”的做法，然而，就在以授权中央军委、国务院有“启动”“非和平方式”为手段、去阻止国家分裂为核心的《反分裂国家法》如期通过之后，就在台湾有人盼望着美国能有“更进一步、更深一层”表示“不悦”的时候，结果、我们看到的是，美国人最后吐出来的不过是“不幸”这个词。
 
*** 非常值得我们注意的一个细节
 
  我们认为，尽管华盛顿在公开场合，从来都是以一种“反对”“反分裂法”的面目出现的，然而，直到今天为止，尽管美国政府的“反对”情绪是跃然纸上，但却从来没有将“反对”这个词正式“说出口”。在我们看来，这是非常值得我们注意的一个细节。
 
*** 不把“反对”这个词正式“吐出来”，华盛顿可以说是“用心老到”

    首席评论员指出，华盛顿之所以处处表现出“反对”“反分裂法”、但却从不把“反对”这个词正式“吐出来”，可以说是“用心老到”，在我们看来，这表面在这几层“用心”。

    第一，之前，我们曾经说过，对北京这部旨在
    #+HTML:<a>干扰美国全球战略部署</a>
    #+LaTeX:\red{干扰美国全球战略部署}
    的“反分裂国家法”，华盛顿之所以嘴里说不出什么正式“反对”的话来，主要原因在于有自知之明：即“就是反对也无济于事”。
 
*** “搞政治”的人、就得面对现实

    第二，东方评论员认为，既然北京此次立法“反分裂国家法”是着眼于全球战略，那么，华盛顿的决策层应该明白这么个道理，那就是，既然挡不住“反分裂国家法”的“正式出炉”，那么，“搞政治”的人、就得面对现实，即，必须在北京用《反分裂国家法》打乱了自己
    #+HTML:<a>原先计划好了的“台海政策”</a>
    #+LaTeX:\red{原先计划好了的“台海政策”}
    的基础上、重新去和北京在台海局势、东亚安全、乃到亚洲安全、中东问题上“有话好好说”。

    显然，如此一来，美国如果对一部“势必通过”、或者“已经通过”的《反分裂法》做“正式”、但却注定是“无效”的“反对”，那么，美国的“反对”就真成了 “错误的信号”，必将激起“台独”势力对《反分裂法》的极度反弹，也就等于将“中美之间”在一系列战略问题上“有话好好说”的基础、给“正式地、毫无效果地反对掉了”。不难看出，经验老到的华盛顿，这次没有给自己找这样一个麻烦。

    在东方评论员看来，上面所说的朝鲜问题，也正是华盛顿准备与北京在《反分裂国家法》已经“正式生效”的基础上，首先要谈到的一个“战略合作”课题。
 
*** 朝鲜问题事实上已经从一个“可控的热点”、被彻底“鼓捣成了”一个牵一发而动全身的“火山口”
 

    然而，华盛顿眼中的“朝鲜核问题”、早已经被北京“另有目的”地“定义”成了“朝鲜半岛核问题”，而这其中、还被“夹塞进了”东亚核竞赛、美日安保条约的问题，总而言之，在我们看来，现在的朝鲜核问题，经被华盛顿“怂恿日本在钓鱼岛问题上挑衅中国”、拿到了一份包含台湾问题的“美日安全共同声明”之后，又经朝鲜突然“宣布有核”、北京顺势抓起了一张“东亚核竞赛”的牌、事实上已经从一个“可控的热点”、被彻底“鼓捣成了”一个牵一发而动全身的“火山口”。
 
*** 小泉政府这次是“唯恐东亚不乱”

    东方评论员认为，由于日本在钓鱼岛、独岛（日本称竹岛）、北方四岛等一系列主权争端问题上、是全线出击、“挨着个地”寻畔几个核国家：先挑畔中国、再激怒韩国、朝鲜、最后还咬住了俄罗斯、在我们看来，小泉政府这次是大有“唯恐东亚不乱”、好借机
    #+HTML:<a>扩充军备、特别是核军备</a>
    #+LaTeX:\red{扩充军备、特别是核军备}
    、且“不达目的不收兵”的气慨。
 
 
*** 日本当局的主要着眼点，还是在于为日本今后的国际地位“寻畔出”一条捷径来

    事实上，在日本国内，小泉纯一郎的日子并不好过，因此，借助“领土争端”这种手段，来加强自己的政治声望无疑是一大目的，然而，根据我们的观察，日本当局显然将目前这种美国陷于中东、有求于日本，中国顾忌亚洲经济一体化进程，顾忌“中日相争”而让美国渔翁得利、也不方便与日本彻底翻脸之际，当成了实现其“正常国家”的天赐良机。
 
*** 日本眼中的“捷径”，就是成为一个核大国

    因此，日本当局的主要着眼点，还是在于为日本今后的国际地位、“正常国家”“寻畔出”一条捷径来，在东方评论员看来，日本眼中的这条“捷径” 就是成为一个核大国，以日本的人口规模、经济实力和常规军力，一旦跨入了核门槛，什么“国际地位”、“正常国家”、“军事大国”都成了手到擒来的东西，但是，这条捷径能否走得通，似乎在日本人看来，关键就在于能否让东亚局面“更加混乱”一些。

    有迹象显示，就在日本在钓鱼岛、独岛、北方四岛“拼命搞事”的时候，东亚的局势看起来的确比以前更加混乱了。下面，我们再来看一则“朝鲜外交部”的声明，之后，我们还会继续讨论这个话题。

    《东方时代环球时事解读》http://www.dongfangtime.com
   
** 朝鲜扬言已准备研制更多核武防卫美国的侵略

   【平壤消息】据外电报道，朝鲜外交部表示，朝鲜拥有核武可以防止美国采取侵略行动，朝鲜已经准备研制更多核武。

   朝鲜官方通讯社引述外交部发言人指，事实证明，朝鲜拥有核武可以保证区内军力平衡，也可阻吓区内爆发战争，维护和平，朝鲜将会采取必须的反制措施，包括增加核武，对付极端仇视朝鲜，图谋推翻北韩现政权的美国。

   据路透社报道，朝鲜外交部发言人说：“事实表明，我们拥有的核武器能够确保地区力量平衡，是阻止战争爆发和维持和平的重要威慑力量。”发言人接着说：“朝鲜将会采取所有必要的应对措施，其中包括增强核武器力量，以应对美国终结朝鲜核计划的险恶用心。”


   【时事点评】显然，在东方评论员看来，东亚这块地方，要说乱也真够乱的。这边，是日本在那里“转着圈、挨着个”地得罪人，而且得罪的都是有核家伙的国家。
 
 
*** 朝鲜似乎已经在为日本所渴望的“东亚核竞赛”放风

    如果我们再仔细看看日本得罪的这些国家名字，就不难发现，不论是中国、韩国、朝鲜、俄罗斯、都是“六方会谈”中的“正式成员”，加上日本自己，还有那个美国，“无一不与核”沾边带故：要么本身就是身居“五大核国家”之列，如中、美、俄、要么就宣称自己“有了核武器”、比如朝鲜，最不济的也都有
    #+HTML:<a>立刻生产核武器能力</a>
    #+LaTeX:\red{立刻生产核武器能力}
    ，比如日本和韩国。

    因此，在这种情况下，我们再去品味朝鲜昨天所说的，“朝鲜拥有核武可以保证区内军力平衡，也可阻吓区内爆发战争，”的说法，就不难品出、朝鲜这似乎已经在为日本所渴望的“东亚核竞赛”放风了。
 
*** 突然抛出这番“重磅言论”，显然是在有意“砸”华盛顿

    在我们看来，朝鲜外交部在局势如此敏感的时刻，突然抛出这番“重磅言论”，显然是在有意“砸”华盛顿、而且是有意“砸给”日本人看的：美国国务聊赖斯将到北京，其重点就是朝鲜问题，平壤在这个时候“放炮”，与上面所强调的、“美国任何试图通过第三方来向朝鲜施压的想法都是愚蠢的”的说法，其意图可以是一脉相承的。
 
 
*** 平壤这样做的最直接好处，可直接“拉高”华盛顿与北京“讨价还价”的“困难度”

    在东方评论员看来，就如华盛顿近日来默许陈水扁当局、有限度地“反弹”“反分裂法”、有意给赖斯的北京之行制造筹码一样，北京默许朝鲜这样做的最直接好处，就是可以直接“拉高”华盛顿与北京“讨价还价”的“困难度”。

    要知道，华盛顿之所以在“美日安全共同声明”的问题上“首鼠两端”，赖斯在这个时候跑到北京来，不就是怕亚洲安全框架崩溃、不就是怕北京手中的那张“东亚核竞赛”牌打出去了吗？
 
*** 首次将之与“区内”军力平衡“挂钩”，是在“不怀好意”地“哪壶不开提哪壶”

    现在，朝鲜再提“继续加强自卫性核武库”，并首次将之与“区内”军力平衡“挂钩”，分明是在冲着“美日之间”的那个、名为“同盟”、实为“主仆”的“军事同盟”关系、在“不怀好意”地“哪壶不开提哪壶”。
 
*** 在东亚的这局牌局中、真正玩牌的只是北京和华盛顿

    东方评论员认为，就目前的情况看，似乎离日本当局所期望的局面更近了些，然而，一直在“处心积虑”地寻求“借机发挥”的日本人、也必须看到这一层，既，在东亚的这局牌局中、真正玩牌的就是北京和华盛顿。

    在我们看来，对日本而言，很不幸的是，玩牌的这两位尽管在一系列战略利益上“拳打脚踢”、争得厉害，但是，在如何控制、压制日本的问题上，只要有可能，双方都是绝对有意继续合作的。
 
*** 赖斯的此次来访，就是为了商讨出一个双方都能接受的办法

    因此，日本要想指望朝鲜能说出、或者做出更能让日本“借机发挥”的事、或者话来的话，还得看看中美这一轮“战略对话”、或者“战略争吵”、能谈出、或者吵出个什么结果来。

   在我们看来，由于“东亚安全”早已经装着“两大热点”、一个是台湾、再一个就是朝鲜，因此，总体上看，由于北京和华盛顿“在实力上的碰撞”，北京一时解决不好华盛顿插手的台湾问题，而华盛顿面对一个北京公开支持的朝鲜，也是一时拿不出“可以如愿”解决朝鲜问题的高招。

    结果是，由于中美都有意让东亚局势服务于大局，服务于自己的全球战略，因此，在我们看来，在某种程度上，正因为北京和华盛顿在“朝鲜、台湾两个问题”上同时“对抗”、反而容易让中美两国“在对抗的气氛中”、寻找出一个“大体维持局面”、却能“各取所需的”方法来。
 
*** 如何敲打日本，或者干脆继续放纵日本，是北京必然会对华盛顿提出的一个选择题
 
   东方评论员认为，赖斯的此次来访，就是为了商讨出一个双方都能接受的办法。然而，根据我们的观察，赖斯的此番重头戏之一的印度之行、并不理想，尽管印度和美国之间谈成了针对中国的“毫无内容”的“加强防务合作”的意向，但是，印度和美国之间、在伊朗问题上的矛盾却被进一步激化了。

   因此，为集中精力投身于中东事务、想安排好针对中国的、南起印度、东至日本的、意在防堵北京借机挤压美国亚洲利益的华盛顿，带着印度之行的“不愉快”，要想成功地“游说”北京、通过北京说服平壤回到“六方会谈”、仅仅揣着一个“不正式反对”“反分裂法”、或者“压制”陈水扁当局不得做出极端的“反制”行为、来权当礼物，恐怕是远远不够的。

   在东方评论员看来，如何敲打日本，或者干脆继续放纵日本，是北京必然会对华盛顿提出的一个选择题。在我们进一步展开讨论华盛顿可能会选择哪个选择项之前，我们再来看看两则消息。

   《东方时代环球时事解读》http://www.dongfangtime.com

   

