# -*- org -*-

# Time-stamp: <2011-08-02 22:02:42 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

#+STARTUP: indent

* 2005年5月11日 星期三

** 宋楚瑜清华大学演讲全文

【北京消息】下面是我们根据录音整理的宋楚瑜在清华大学演讲的全文：

尊敬的顾校长，中共中央台办陈主任，各位老师、各位同学，大家早安、大家好。听到顾校长刚才的一番赞美之词，套句北京人所说的话，听到之后，忒高兴了。昨天天气预报说可能今天有一些雷阵雨，但今天到清华大学看到不仅是风和日丽，而且是拨云见日，这不就是大家所期望两岸雨过天晴、拨云见日，这种期待都是大家所共同的。

在今天楚瑜和我们亲民党的大陆访问团特别到清华大学来是因为明个儿要跟清华大学出身的胡锦涛总书记见面，在明个儿和他见面之前，亲自来目睹执中国科技牛耳的清华大学，看看所谓国之英才的未来，我们亲民党所有的成员要向在这边的老师和同学致上无限的感佩之意。

刚刚顾校长特别提到，在台湾有两位政党的主席，中国国民党的连战主席和楚瑜分别在“五四”的前后来到了大陆，又分别在北大和清华来演讲，这是一项非常别具深厚意义的一种安排。因为“五四运动”的德先生、赛先生是中国人自省自强的开始，我们两个人分别到德先生和赛先生的大本营来演讲，正代表两岸人民的共同期待，炎黄子孙出人头地的共同愿望。

走进清华大学的校园，楚瑜内心有无限的感佩，清华大学在民族的衰败当中立校，在战乱的废墟中重新再生，以科学跟学术来强国雪耻，造就了像胡锦涛先生和许许多多将近三百位以上的副部长的这些党政要员和文法商、科技这些精英持续推动整个中国的改革开放。清华确实是我们共同的骄傲。

不只是在北京，同样的清华1955年在台湾复校。50多年来，台湾的清华也培养着超过35000位精英。他们不但在台湾的经济发展和科技发展上扮演积极的角色，占有举足轻重的地位，更是亚洲在台湾称之为硒谷，在大陆称之为硅谷的新竹科学园区占有不可或缺的重要地位。

基于20世纪初的惨痛教训，我们彻底地认识到现实，了解到世界的趋势，彻底的自我检讨、彻底的在失败当中我们能够学习，兼容并蓄的开始成长，迎头赶上，开始超越，这是和解和平到和谐合作的一个成长过程。清华大学的经验就是中西合成的再生的经验，西方科学实务的态度，跟中华人本精神在清华巧妙结合，在这边既有王国维先生、朱自清先生等一流的文学大师，也有李政道、杨振宁诺贝尔获得者。

所以，不论是在大陆还是在台湾，清华的学校史正是中华民族否极泰来的成长史，也是和解再生迎头赶上的奋斗史。所以，清华这个学校，我们用16个字来形容“一块招牌，两间店面，殊途同归，自强不息”，这不正是两岸当前的一个缩影吗？

清华大学的经验就是中西合成的再生的经验，西方科学实务的态度，跟中华人本精神在清华巧妙结合，在这边既有王国维先生、朱自清先生等一流的文学大师，也有李政道、杨振宁诺贝尔获得者。基于20世纪初的惨痛教训，我们彻底地认识到现实，了解到世界的趋势，彻底的自我检讨、彻底的在失败当中我们能够学习，兼容并蓄的开始成长，迎头赶上，开始超越，这是和解和平到和谐合作的一个成长过程。

我们成长的方法是从消除误解到了解，从了解产生谅解，然后从谅解找出方法来化解，由化解再产生可长可久的和解。在这个过程当中，我们不但没有吃亏，反而因此成长，而从中找到自我定位，重新取得民族的自尊。所以，清华的经验就是全中国人最好的经验。

从这段历史我们了解到真正的和解不是原则立场的妥协，而是民族再生的一个开始，楚瑜抵达北京的时候讲了一段话，历史应该是一面镜子，而不是一条绳子。镜子让我们看到自己的做为，看到前人的教训，提醒自己不要犯同样的错误，绳子是一种纠缠，让过去的冤孽影响到现代人理性的思考，两岸的历史和未来千丝万缕、千头万绪，包括在座的所有的台湾和大陆的同胞们跟相关的政治人物能有更大的智慧，让中国人共同处理自己中国人的问题。

另外，一个全球必须面对的必然趋势，那就是中国的崛起。就在两天之前的5月9日，这期美国新闻周刊NewsWeek以“中国的世纪”来做封面的报道，这个报道中说中国近年来的突飞猛进的成就。报道说改革开放的25年以来，中国成功的让超过3亿以上的中国人民脱离了贫穷。

而去年美国最大的超市就是沃尔玛，它是对美国贡献有2％GDP的首富公司，在它的6000多个供应商里面，有5000个是来自于中国，占所有供应商的80％。现在美国人学中文的急切的程度超过去学法文，以往我们讲电影，是美国文化的代表。但现在，中国的电影明星却向美国输出，在大陆有张艺谋，在台湾有李安，章子怡更是大家都认识。

所有的数据和事实都说明中国正在快速地崛起。15年以前，美国认为浦东的开发是不可能的事，但现在却是亚洲金融的中心。欧美的经济学者都认为，以这种干劲和快速发展的程度，中国经济的实力在2015年将超过日本，而且在2039年会超越美国，这是了不起的愿景和共同成就。

外国人对中国的崛起，是既羡慕又害怕的。其实，外国人所不了解的，中国人一向讲求王道，富国的目的是为了立民，中华人民百年来深受帝国主义深害，在复国以后，不但不会霸道，而会柔以克刚，这是向外国人展现东方文化的特质，全世界都在等待东方这条巨龙能够腾云而起，但两岸的中国人我们准备好了吗？这就是我们要谈话的一个主题。

现在是中华民族有史以来最繁荣、富足的时候，也是中国人摆脱百年屈辱最关键的时刻，因此，两岸真正的敌人不是兄弟彼此，而是束缚了中国数百年的落后和贫穷，仍旧让中国人挣脱落后和贫穷成为一个均富的社会，这才是海峡两岸共同追求的目标。事实上，五十年以前，台湾就认清了贫穷才是“国家”发展最根本的障碍，分配不均才是让国民党政府撤退到台湾的主要原因，因此开始励精图治发展经济，创造了台湾经济的奇迹。

创造台湾经济奇迹的经验是与同时维持“一高两低”，就是“一高”，持续的高经济成长；“两低”，就是低通货膨胀、低失业率。同时，要维持稳定的物价水准和充分的就业，最后政府通过税制和教育让穷人有翻身的机会，力求维持较均衡的所得分配，整个的社会和经济不但要使一部分人能够富起来，更要让所有的家庭都能够富起来，这就是均富。

依照台湾的经验，达成均富最重要的手段就是偏向于社会性和教育性。一方面让每一个人都有公平的机会来攀爬社会的阶梯，而另外一方面知识就是权力。也就是培根所说的知识就是力量，只要掌握知识，就不会一代一代、世世代代的穷。蒋经国先生在执政台湾16年当中，1972―1978年，台湾每一个国民的所得从4820元美金成长到5829元美金，成长了11倍。但最高的所得的家庭1/5和最低的1/5，一直当中的差距维持在4―5倍以下的水准。

现在台湾有21项IT产品居于全球龙头的地位，去年台湾这个弹丸之地，生产了4500万台的笔记本型的电脑，占全世界的71％。即使我们现在的经济状况有所起伏，但是台湾每一个人的国民所得一直能够保持在12000元―14000元的水准。台湾经济奇迹真正的意义不是在于富，而是在于均富。

台湾经济的成长的主要原因不是因为我们物大地博，或者资源丰富，而是在于全球布局运营的管理和提高全球的竞争力，因此近五十年的台湾和1978年改革开放以后的大陆成功的能够从贫穷翻身的原因，可以归纳为三个，那就是尊重市场、尊重专业、尊重制度。在这三个因素当中，资本市场和专业人才只能够提供一时的突破，但制度的改革才能创造一个长远和全面的成长。

前任的WTO，国际贸易组织的秘书长、做过泰国副总理兼财政部长曾说，中国加入WTO之后，对亚洲各国最大的挑战，是制度的竞争，是谁能够在制度的改革上最好，谁才是真正的赢家。

两岸在制度的调整上，能够有互补互通的空间，比如说中钢和台湾的产业合作可以作为大陆的参考，股市房市的过热可化解降温，而不是迅速破灭，大陆通过称之为知识财产权来保证创新的动能，这些方面都可以两岸多加交流。

我在这里要提到一位温世仁先生，这位台湾企业家，不但文章写得好，而且还是慈善家。两年前过世的英业达所说的消灭贫穷才是最大的商机。他到黄羊川，说那里是不用带布景就可以拍电影的地方。他过世一周年的时候有上万人排队去吊祭，他说两岸人民的合作就是改善制度、取长补短，改善经验，相互帮助。

解决我们对方的内在问题，面对国际的挑战，我们不只是要有医院和学校，更要把医院和学校带到农村去。带到农村去，在台湾所做的一切的努力，让每一个人都能够享受现代化的设备，享有最基本的人权和照顾，这才是真正最贵的待遇。

所以我们要的是基本教育、基本建设和最重要的在台湾称之为“基本班底”，在大陆称之为“骨干力量”，就像清华所培养出的学生一样。

前几天，楚瑜到南京，在夫子庙前面有一位老先生穿过重重的警戒跑到我们团员面前，说了一句话，宋先生不要打仗。我们共同要让两岸成为共同的市场、共同繁荣的市场，不需要打仗，无论是民族的需求，一个中国大陆和平稳定的中国，是符合世界全球大家共同利益的事情。

趋势大家都知道，但是有一条政治的“黑水沟”横在海峡两岸之间，使得双方的交流不能这样顺畅，我们必须从历史来了解这条“黑水沟”的形成，才能搭起和解和合作的桥梁。在历史上，台湾常常被视为“化外之地”，许多福建、广东的人民为了生存冒险来到台湾，那种艰难的过程一般人很难想象。

在台湾史里面，民间流通着一条“杜甫悲歌”，一开始是劝君莫要过台湾，台湾恰是鬼门关，知生知死谁都难”，而客家人每个人都会唱的“客家本色”，唐山人过台湾，我要半点钱，唐山人过台湾，身上没有半点钱。他们每天过的日子就是拿着生姜蘸着醋吃，他们都没有埋怨。这些先辈们能够历经风霜落根台湾，就形成了台湾特有的“台湾意识”，这种台湾意识又经过政治的强化，在明清两代形成村船不许下海。台湾的罗汉饺就是这样来的。台湾的乡亲自求多福，说的难听点就是自生自灭。

台湾就像一个家道中落，又被卖出去的养女，又把台湾割让给日本，日本人把台湾当成殖民地，一直到1949年。我们努力地打拼，深深体会出艰难的悲情。
那种既怀念原乡，又扎根于现在家庭的一种心境。两边都是我们的家，一边有我们的祖先，一边有我们的子孙，没有人会要去争取一边的认同而去放弃另外一边，这就是各位大陆的乡亲，您慢慢去体会。

其实，大多数的台湾人既不否认自己是炎黄子孙，也信仰着大陆上面来的妈祖和关公，还有更多的神明来自于大陆。但是400年的疏离，100年的隔绝，50年的对抗，尤其是两岸的不同制度让台湾和大陆的隔阂越来越深。

请各位同学、大陆的乡亲不要把台湾意识跟“台独”划上等号。台湾意识是在长期的历史脉络中自然形成的一种认同台湾人跟地的一种情感，“台独”是要把中国从中国大陆彻底割裂的一种企图。不可否认，台湾意识曾经被“台独”所操纵，但是这种政治挂帅的手法反而混淆了台湾真正的心声。

例如为了“台独”而认同日本人，不仅扭曲了历史，也否定了台湾人，这是一小部分人狭隘的个人经验，既丢了根，又抛了本，所以是根本不对。

拿我们亲民党来说，我们是一个在台湾土生土长的政党，但是却有着非常强烈的爱乡爱土的台湾意识，是台湾意识，而不是“台独”选项。我们也有着浓厚的华夏情怀，我们从头到尾坚决反对“台独”，我们一贯所强调的是：“台独”是一条走不通的死路，而“台独”也从来不是我们亲民党和台湾应该有的选项。

两岸的未来必须奠基这种深入的相互了解，台湾人要多了解大陆的改变，而在同时我们也期盼大陆的同胞多了解台湾同胞的想法。两岸应该要一中求同，从了解、谅解，然后去化解，最后和解来产生我们一个民族，中华民族华夏子孙共生共荣的一个新的契机。

所有的中国人都记得我们在夏朝之初那个治水的故事，您还记得鲧用围堵治水无功，而大禹用疏导使得水患不在。孔老夫子说过一句话，远人不服则修文德以来之。
所以宋楚瑜要在这里诚恳的呼吁，两岸没有必要再纠缠在历史的恩怨中，两岸已经梳理了几百年而开始密集的交往也不过是最近十几年来的事。我们用一句台湾闽南话讲，吃饭吃得太快会把碗咬破了。而且应该用耐心，用了解、用谅解诚实来面对历史，务实地来策应未来，才能够让我们两岸共享一个共生共荣的美好愿景，关键的时刻就看我们在这一个月以来所做的天翻地覆的两岸重大变化，让我们有所期待。

简单的讲，两岸的问题的根本解决之道既不是喊话，也不是武器，而是双方的政治精英不愿意见到人民生灵涂炭，不愿意让过去两岸分别在几十年当中努力的成果毁于一旦，那一颗仁民爱物之心以及对中华民族未来共同的期盼，两岸只有把人民的幸福放在第一位，才能倾全力找出可以接受的可行方案。用一句我们清华这些学科学的数学的术语来说，就是找出双方的最大公约数，我相信我们有智慧找出两岸的最大公约数。

从和解到再生的过程，绝对不会是短暂的，也不会是一帆风顺的。李白有一首诗叫做《行路难》。行路难，行路难，多崎路，今安在，乘风破浪会有时，直挂云帆济沧海。我想两岸的和平进程会起起伏伏，但是我们方案正确，我们抓紧脚步，我们有信念和信心，我们也有这个坚持，一定会像我刚刚到清华校园来的时候所讲的，我们两岸一定会拨云见日。

大家都不会怀疑道路为何如此坎坷、艰难、多变，宋楚瑜跟好多关心两岸包括亲民党在内要提着脑袋去做，就是许多像宋楚瑜这样的人，曾经不是亲身的经历过战争的战火洗礼，也是体会了那些骨肉离别、离散的那些痛苦，或者是听到父母在告诉他们子女这些过程的一些艰苦，我们不愿意我们的下一代，让我们的下一代再告诉他们的下一代去讲述这些血淋淋的经验。这就是我们为什么一无反顾的要致力于两岸和平的原因。

最后，楚瑜愿用八个字来形容楚瑜今天的心情，那就是丰碑无语，行胜于言。那个丰硕很大的碑上面不一定要刻任何的字，而在清华的校园里面，大家都看到的，就是在日晷上面刻的四个字，行胜于言。这不但是清华人的信念，也是所有中国人应该奉行的一个价值，它更是两岸双方在未来检视对方诚意和善意的基础。

事实是检验真理的唯一标准，所以宋楚瑜要套用美国过去一位总统肯尼迪所说的一句话，不要光看我在大陆说了什么，要看我们在台湾做了什么。

今天在座的每一位都是在为中华民族写历史，楚瑜深信，让我们一起站在历史的制高点宏观的看我们两岸合作未来的愿景。楚瑜把今天所讲话的题目就定在世界有多大、中国的机会就有多大，让我们一起掌握这个机会，携手同心，脚踏实地，迎接一个为我们两岸中国人来的未来21世纪的世纪。也就是我们刚刚所看到的，那就是中国人未来共同的愿景，让我们携手同心，一起来努力。我们不会让历史说我们错过了这个机会，我们不会让他们失望，我们会加倍努力。谢谢非常大家。


【时事点评】在全程观看了宋楚瑜的这篇演讲之后，有个感觉特别深：显然，带着一脸“沉重”到达北京之后，宋楚瑜“仍然没有想清楚”应该如何决定，至少表面上是这样的。

*** 宋楚瑜“没有最后决定”的迹象是随处可寻的

在东方评论员看来，这种“没有最后决定”的迹象是随处可寻的，我们注意到，这份据说是宋楚瑜和其幕僚一同修改到今天凌晨三点钟的演讲稿，在经宋楚瑜的嘴通篇念出来之后，我们是既没有听到让大陆“不高兴”的“中华民国”，也没有听到让陈水扁发誓“就是翻箱倒柜”也不可能找到的“九二共识”。

*** 如果是寻求“某种平衡”，它也能算得上是一篇“精彩之作”

不难看出，如果宋楚瑜是有意在会见胡锦涛之前、在北京与华盛顿、陈水扁之间、寻求“某种平衡”的话，那么，这样的一篇“堆文砌字”、“内容空洞”、前后文字衔接并不紧密的演讲稿、自然可以达到这样的目的。东方评论员认为，如果仅是站在这种角度去看，它也能算得上是一篇“精彩之作”。

有意思的是，在东方评论员们和大家一起观看宋楚瑜演讲的时候，台湾的陈水扁显然也在密切注视着宋楚瑜在演讲台上的“字字句句”，而且还立刻通过媒体给出了他的“点评”。

下面，我们就先来看一段最新收到的消息，之后，东方评论员将继续回到这个话题。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 肯定?陈水扁:宋楚瑜演说推销台湾成功经验

【台湾消息】据台湾媒体报道，亲民党主席宋楚瑜11日上午在大陆清华大学进行题为「搭起两岸间和解与了解的心灵之桥」的演说，就在台湾泛绿阵营纷纷对于宋楚瑜多次提及反台独而恼怒之余，陈水扁11日上午在会见外宾场合，则以开放包容的态度，看待宋楚瑜在清大演说。陈水扁表示，宋楚瑜演说，是为了推销台湾成功经验。

陈水扁11日上午10点接见韩国「开明我们党」访问团，也代表政府与人民对访宾来访表达诚挚欢迎。接见外宾时，陈水扁特别提到，接待「开明我们党」四位青壮派议员非常重要，但目前还有两个令台湾民众相当关切的现场活动，也正在进行着。

陈水扁说，台湾旅美棒球国手王建民正代表所属的球队纽约洋基队担任主投，刚才正值第九局的赛况，洋基队以七比四领先；而另一个现场，亲民党宋楚瑜主席正在北京清华大学演讲，推销台湾成功的经验。

陈水扁说，台湾民众对两件事情都很关注，守着电视机，对两者都难以取舍。由于上午10点总统正在进行外宾会晤，陈水扁也幽默表示，虽然他舍不得离开电视，但接待韩国朋友，更为重要。

亲民党主席宋楚瑜11日上午在清华大学演说，虽然定题为「搭起两岸间和解与了解的心灵之桥」，也强调两岸未来要靠彼此和解谅解化解来共同创造，但依然在演说后半部高谈亲民党反对台独的立场，稍后也遭台湾泛绿阵营一阵痛批。

不过，陈水扁可能是忙于接待外宾，还未听到宋楚瑜反台独的这个后半部，在接待外宾时脱口而出，称许宋楚瑜清大的演说，推销台湾成功经验。陈水扁这厢肯定宋楚瑜推销台湾成功经验的说法，听在泛绿耳里，尤其是台联骂声隆隆的情况下，是否又会引发泛绿阵营之间的紧张关系，还有待观察。



【时事点评】我们知道，明天，胡锦涛将接见宋楚瑜，也就是说，如果宋楚瑜现在已经拿定了主意、且又够胆量的话，那么，在这篇“临战式”的演讲中，或许会透露出点“什么”出来。

*** 他一定是带有任务而来的，同时也与陈水扁“达成了的某种默契”

之前，东方评论员注意到，从宋楚瑜本人讲话，到他临行前与台湾“行政院长”谢长廷会面，都不难看出，尽管他一再声称“不当任何人的特使”、“只代表亲民党”、然而，这只是大陆发给他“登陆门票”的前提条件。


*** 陈水扁连续两个晚上的“爆料”之后，宋楚瑜似乎已经是“心有余悸”


事实上，宋楚瑜于昨天抵达北京机场后，再次表示他“期待着”与胡锦涛的会面，并“希望建立两岸互信互补之桥”。显然，宋楚瑜再次捡起了“搭桥说”，由此可见，在陈水扁连续两个晚上的“爆料”之后，宋楚瑜似乎已经是“心有余悸”，这更加证实，宋楚瑜一定是“带有任务”而来的，同时也与陈水扁“达成了的某种默契”。

在昨天台湾部分的点评中，我们曾经讨论了陈水扁连续“炮轰”台湾政治势力的方方面面，就如我们所说的那样，在这一出“儿子骂老子”的政治秀中、陈水扁是连带“他台湾的老子”、“美国的干爹”是一块给骂了。

东方评论员认为，这个表面看起来“不合情理”的“抓狂”、显然是陈水扁“精心谋划的一着棋”。


*** 宋楚瑜应该深刻体会到了“扁宋会”是何等后患无穷

我们认为，陈水扁在这个时候“抬出美国最上心的军购案”的一个重要目的，就是意在隔空“拉着”华盛顿事实上“仍然在支持着台独”的“这面大旗”做“虎皮”、警告宋楚瑜在北京“要小心不要乱讲话”。

在东方评论员看来，看来，连续两晚的“叫骂”、“爆料”显然起到了“立杆见影”的效果。有消息说，宋楚瑜也是布置其手下在台湾放话，如果陈水扁继续爆料的话，那么，亲民党也要把“扁宋会”中的“某些章节”拿出还击，并警告说“那样恐怕陈水扁要立刻下台”。

但是，首席评论员指出，既然陈水扁在“扁宋会”中说出了足以让自己下台的“交心话”，恐怕是“来而无往非礼也”，亲民党就敢保证宋楚瑜没有说出让自己“死得更难看”的“知已之言”？

显然，在“蓝”、“绿”、“橙”间跳来跳去的宋楚瑜，现在应该深刻体会到了“失去原则立场”、顺应华盛顿的意思、参加“扁宋会”、并去搞那个“宪法一中”的“十点共识”是何等的“后患无穷”的了。

*** 在听了宋楚瑜的演讲之后、看来陈水扁“心情还真的不错”

在东方评论员看来，宋楚瑜与陈水扁之间究竟有何具体“默契”、我们只能寄希望于陈水扁继续“爆料”，当然，最好是宋楚瑜也“奋起反击”，然而，就目前而言，我们的感觉是，宋楚瑜退缩了，至少表面上是这样的。因此，宋楚瑜与陈水扁之间“默契”、其实可以在这篇讲稿中找到此许答案。


因此，今天的陈水扁在听了宋楚瑜的讲话之后、看来“心情还真的不错”，我们注意到，对宋楚瑜的演讲，陈水扁可以说是“捡了自己受用的”部分形容了一番：是为了推销台湾成功经验，显然，这是对宋楚瑜“讲稿”的肯定。

的确，在宋楚瑜的讲稿中，为了描述台湾的经验“是如何如何”、的确花了其大量篇幅，然而，在东方评论员看来，如果宋楚瑜的这篇演讲的主要部分仅是为了推销台湾的成功经验，恐怕陈水扁是根本就懒得一看的。

在东方评论员看来，陈水扁之所以在大骂宋楚瑜之后、还能耐着性子“看上一段”，主要是想看看这篇演讲中有没有“扁宋会”的影子、有没有“十点共识”的痕迹。


*** 陈水扁“心情不错”的原因在于宋楚瑜“充分解读”所谓的“台湾意识”

请大家注意这么一段。宋楚瑜说：请各位同学、大陆的乡亲不要把台湾意识跟“台独”划上等号。台湾意识是在长期的历史脉络中自然形成的一种认同台湾人跟地的一种情感，“台独”是要把中国从中国大陆彻底割裂的一种企图。不可否认，台湾意识曾经被“台独”所操纵，但是这种政治挂帅的手法反而混淆了台湾真正的心声。

首席评论员指出，我们有理由相信，陈水扁“今天心情不错”的原因并不在于宋楚瑜在大陆推销什么“台湾的成功经验”，而恰恰就是“充分解读”了这个所谓的“台湾意识”。

值得注意的是，宋楚瑜在正式提出“台湾意识”之前，显然做了某种铺垫，一句“台湾就像一个家道中落，又被卖出去的养女，又把台湾割让给日本，日本人把台湾当成殖民地，一直到1949年”可以说是“点出了”台湾社会对大陆“过往历史”的“不满心结”。而这种“心结”正是“台独”赖以生存、和支持“台独”的国际势力随时可以“兴风作浪”的温床。

我们注意到，如果按宋楚瑜的解读，那么，“台湾意识”不过是一种“非常强烈的爱乡爱土的”“对大陆有一丝幽怨的情感意识”，然而，在东方评论员看来，这种所谓的解读，并不能解释为什么台湾在祖国大陆经济比过去有了巨大进展之后，两岸经济有更紧密的联系之后，台湾“赞成统一”的人“却越来越少”的现实。

*** 正是存在着被某种势力“进一步操纵的基础”，“台湾意识”本身就是非常危险的

显然，按宋楚瑜对“台湾意识”的描绘，我们第一个人都可以立刻根据自己对自己“家乡”的认同、而立刻就产生一种“家乡意识”，比如说，我们是北京人、自然会对北京有一种“非常强烈的爱乡爱土的”“家乡情感”，如果套用宋楚瑜的解读的话，自然也就可以说成是“北京意识”，但在这种“北京意识”里面、由于对国家的认同，你是永远也找不到被某种势力“去操纵的基础的”。

在东方评论员看来，正是存在着被某种势力“进一步操纵的基础”，“台湾意识”本身就是非常危险的，对此，宋楚瑜先生“感伤地”建议“各位大陆的乡亲，您慢慢去体会”时，我们必须“心中有数”的。

首席评论员就指出，值得强调的是，宋楚瑜先生对减低“台湾意识”所开的药方、不过是“指望大陆的乡亲，慢慢去体会”，在我们看来，这就奇怪了，大陆人民不是不知道这种历史，也“体会”了几十年，但体会来体会去，体会只求大家都“认可两岸是一个国家”就行，可为何“台湾意识”在这种宽松的条件下却日益浓厚呢？

*** 如何对症下药，宋楚瑜“不是不懂，而是装着不懂”

显然，关键就在于“两岸分裂”，两岸无法“三通”，这就给了国际势力操纵“台湾意识”的空间。东方评论员认为，如果宋楚瑜真的有意促进大陆人民更好的体味一下“台湾意识”，为何不一步到位地开出“两岸全面三通”的“药方”呢？

在东方评论员看来，如何对症下药，宋楚瑜“不是不懂，而是装着不懂”。而这种“装”的背后，就带有“太多的私货”了。

事实上，宋楚瑜去搞什么“扁宋会”、订什么“十点共识”，由“蓝”变“橘”、不就是看中了“台湾意识”有着被“台独”、特别是支持“台独”的国际势力操纵的“内在基础”吗？不就是指望能顺应“台湾意识”、在岛、内外台独势力操纵“台湾意识”的过程中寻觅机会、企图“咸鱼翻身”的吗？

*** 肯定、并时刻准备操纵、并利用“台湾意识”正是“中间中线”的“政策主线”。

东方评论员认为，宋楚瑜在这里大谈什么“台湾意识”，并将之与“台独”撇得一清二楚，有两个目的，第一，它本身就是在迎合台湾岛内那种“惧战、反统”的主流民意，也是为自己“由蓝变橙”找个理由。第二，这恐怕就是陈水扁与宋楚瑜之间“默契”的本质内容了，东方评论员认为，看看那份包装成“回归中间路线”的“十点共识”，我们不难发现，肯定并时刻准备借助美日势力操纵、并利用2300万台湾人的“台湾意识”正是其“政策主线”。


*** “分裂意识”才是“台湾意识”的精髓之所在

我们知道、由于对于社会制度不认同，由于双方经济上的差距，台湾的主流民意本质上就是“企图用分裂来保证他们的经济利益”。在东方评论员看来，这种“分裂意识”才是“台湾意识”的精髓之所在。我们认为，“台湾意识”之所以是种“分裂意识”，就在于它与“台独”的差别、仅仅是因为大陆在“以武力做后盾”不充许台湾独立、这才让“台湾意识”“意识到了”“分裂”还能暂时保证他们的经济利益，而在现阶段，“台湾意识”认为“台独”如能成功当然能长久地保证他们的经济利益，这就表现为“反统”；而不成功则是在“自寻死路”，这就是“惧战”。


*** “台湾意识”和“台独”之间“能不能划等号”是要考虑条件因素的

显然，“台湾意识”和“台独”之间“能不能划等号”是要考虑条件因素的。东方评论员认为，只是台湾现在没有“独立”的本钱，特别是美国人在同中、欧、俄罗斯在全球范围内角力的关键时刻，暂时没有能力、也没有兴趣在这个时候让台湾“走向独立”，然而，华盛顿是不会放弃这种“可能性”的，这也意味着“台湾意识”也是不会放弃这种“可能性”的。

*** 真难为宋先生了，竟然如此地用心良苦

在我们看来，既然有“非常强烈的爱乡爱土的”“台湾意识“的宋楚瑜心里还惦记着这些“可能性”，那就自然会在“国家认同”的问题上加以回避。这就表现在我们听完了全文之后，竟然听不到“一个中国”的相关意思，只是在宋楚瑜的一段“借物喻意”中找到了“那么一点点的意思”。

原文是这样的，宋楚瑜在演讲中表示：清华这个学校，我们用16个字来形容“一块招牌，两间店面，殊途同归，自强不息”，这不正是两岸当前的一个缩影吗？

在东方评论员看来，也真难为宋先生了，竟然如此地用心良苦。我们知道，他是在北京清华大学打这个比喻的，而台湾也有个清华大学，这就是“一块招牌，两间店面”来源。


*** “鱼和熊掌”“欲兼得”的心理，仍然没有完全从宋楚瑜的内心消失

然而，宋楚瑜如此这般“挖空心思”、“咬文嚼字”，不就是想避免提及“一个中国、各自表述”涵义吗？不就是想回避“九二共识”这几个陈水扁“死活不肯认账”的几个字吗？

不难看出，宋楚瑜在抵达西安后，在陕西机场一面高呼“反台独、反一中一台、反两个中国”，一面口头承认“九二共识”，一面大谈“中华民国”、通过强调“第一条”去为“十点共识”的“做广告”、所表现出来的“鱼和熊掌”“欲兼得”的心理、在大陆旨在“促进”的“连续的打压”、与陈水扁旨在“拉住”的“两天的炮轰”中，仍然占据着宋楚瑜的内心，也正是如此，宋楚瑜在演讲中采取了两边“都不得罪”的态度，结果是开始就口头承认了的“九二共识”没有了，而代表着“十点共识”的“中华民国”的说法也没有了，并分别用“中华民族”、和那个“在分裂与独立之间'有条件'摇摆”的“台湾意识”所取而代之。

*** “丰碑无语，行胜于言”，宋楚瑜是“话中有话”

在这种背景下，东方评论员在听到宋楚瑜在演讲时“诚恳的呼吁”：“吃饭吃得太快会把碗咬破了”立刻就觉得“特别刺耳”的原因之所在。尽管如此，我们也注意到宋楚瑜“今天的心情”，他用了“八个字”来形容了他今天的心情，那就是“丰碑无语，行胜于言”，并提示说“它更是两岸双方在未来检视对方诚意和善意的基础”。

不仅如此，他并引用了“事实是检验真理的唯一标准”这一句，来“提请”大陆“不要光看他在大陆说了什么，要看他在台湾做了什么”，显然，宋楚瑜是“话中有话”。


*** 希望宋楚瑜的“行胜于言”在稍后的“胡宋会”能得到体现

首席评论员指出，我们也宋楚瑜的“行胜于言”在稍后的“胡宋会”能得到体现、也希望宋楚瑜的“话中有话”仅仅是宋楚瑜为了排除来自华盛顿、陈水扁方面的干扰而采用的一种临时策略，而不要抱着与大陆“玩权谋”的心态。要知道，“台海的紧张”对大陆而言，远不是问题的全部。

因此，在我们看来，如果到了“胡宋会”时，如果宋楚瑜仍然准备如此这般地“滴水不漏”、仍然还放不下这个“意思多多”的“台湾意识”所代表的“十点共识”的话，那么，可以肯定的是，宋楚瑜一心想将自己拔高成“两岸和平”的“事实推动者”的“登陆企图”，恐怕就成了“水中月”，“雾中花”，不仅如此，宋楚瑜大概还“不得不接受”一个“轰轰烈烈”的“搭桥之旅”、在已经变成了一个前途未卜的“工作之旅”之后、最后变成一个“自己拆自己的桥”的“拆桥之旅”的“无为结局”。

在东方评论员看来，如果一个“轰轰烈烈”“搭桥之旅”、最后落得个“冷冷清清”的“无为结局”，那么，宋楚瑜恐怕也就“又走错了一步”，也就应了我们之前所说的“一步错、是步步错”的这句话。未了、这位有心超越连战、却“什么都想要”的宋楚瑜先生、恐怕会被“背水一战”的连战甩得更远、带着“来了还不如不来”“后悔心情”回到台湾。

有消息说，宋楚瑜在见胡锦涛的时候会端出两个“秘方”。对东方评论员而言，这个宋氏“秘方”是何“配方”，我们无从而知，只能等他本人“献宝”之后才能一见，只是在东方评论员看来，在这个时候他能拿得出手的“秘方”、其“配方”恐怕也不过是“三味成份”。

在一起浏览了这段有关“秘方”的报道之后，时事评论员们将就可能的“三味配方”给出我们的意见，看看它能不能成为防止宋楚瑜“日后后悔”的“后悔药”。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
