# -*- org -*-

# Time-stamp: <2011-08-04 00:16:02 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 2005年6月14日 星期二



** 韩国总理李海瓒将于6月21日至23日访问中国

【北京消息】外交部发言人刘建超１４日在此间举行的例行记者会上宣布，应国务院总理温家宝邀请，大韩民国国务总理李海瓒将于６月２１日至２３日对中国进行正式访问。

** 韩国代表团赴朝鲜平壤参加6·15南北统一庆典

** 【汉城消息】据报道，由40名政府代表和295名民间代表组成的韩国代表团14日分别乘包机前往平壤，参加在那里举行的“6·15《南北共同宣言》5周年民族统一大庆典”。

据韩国联合通讯社报道，韩国政府代表由韩国统一部长官郑东泳率领，当天下午利用直航航线前往平壤顺安机场，随后将参加在平壤金日成体育场举行的统一庆典开幕式。上述韩国民间代表当天上午已乘包机抵达平壤。

韩国政府代表团访问期间将同朝鲜劳动党中央委员会书记兼祖国和平统一委员会副委员长金基南为团长的北方代表团举行“6·15南北政府共同活动”，并于16日拜访朝鲜最高人民会议常任委员长金永南。报道说，韩方代表团将向朝方传递韩美首脑会谈的有关信息以及对南北关系正常化的原则立场，如果能见到朝鲜领导人金正日，将就朝核问题和六方会谈等问题交换意见。

据报道，韩国代表团在平壤参加庆典活动后将于17日返回汉城。


【时事点评】东方评论员注意到，就在中国外交部宣布韩国总理李海瓒即将访华的同时，美国助理国务卿希尔“正在韩国访问”。显然，“中美韩”这三个“六方会谈”中最为关键的“三方”，此时的这番“加紧切磋”，显示朝核问题已经又一次来到了关键时刻。


长期以来，在东方评论员的眼里，从来就没有一个单纯的台湾问题、也没有一个单纯的朝核问题、日本问题、甚至是伊朗核问题。因此，为了更好地说明台湾的现状，东亚安全的现状，中美之间斗争的现状，我们觉得很有必要简单地回顾一下过去一年来的“方方面面”。

*** 过去一年中，隔着太平洋的较量

自去年3月20日台湾“大选”，期间经历美国副总统切尼“意在”支持陈水扁连任的“4月份访华失败”，导致北京公开暗示将支持朝鲜，并将朝核问题正式作为一张对付美国东亚战略利益的“战略牌”给打了起来，并在同时发表了“517声明”、迫使陈水扁“修改520就职演说”。

之后、在6月份，北京又第一次在伊拉克问题上“主动出击”，“带头”“多次修改”美国提交的“伊拉克问题决议案”、并成功阻拦了美国千方百计所想得到的联合国维和人员的“外交豁免权”的要求。事实上，经北京“领头”修改的“伊拉克问题决议案”、对伊拉克战后政治重建、伊拉克什叶派掌权起了非常关键的作用。

与此同时，由于美军失去了“外交豁免权”，这实际上已经令以联合国多国部队名义维持伊拉克治安的美军“变了味”，这将令在执行任务中的美军、今后可能因“行为过当”、而面对刑事上的麻烦，当然，前提是伊拉克政府将来有能力行使这一权力。

*** 赖斯的“第一次失败”

到了7月份，中美间的较量、又经历了一次“赖斯访华失败”，这是赖斯的“第一次失败”。大家应该还记得，赖斯是一回到华盛顿，白宫的决策层就立刻唆使新加坡副总理李显龙访台，以此来为华盛顿的“台湾问题国际化”之“新政策”探路。

*** 新加坡“强出头”、出于两层目的

在东方评论员看来，我们之所以称之为“新政策”、就在于当时华盛顿让新加坡“强出头”、出于两层目的，第一，新加坡是东盟的核心成员，在中国热心的“东亚经济一体化”、“东盟10+1”等合作方式、作用非常重要。东方评论员认为，新加坡之所以“敢出头”，除了有心全面投靠美国之外，在很大程度上，也正是仗着这一点。

显然，美国和新加坡“共谋此举”、可以说居心险恶，说白了，他们就是要看看中国的底线是什么，到底是经济第一，还是主权第一？而其他国家、比如、澳大利亚、马来西亚、菲律宾等国，也都将视新加坡副总理访问台湾的“最后结果”、而最后敲定各自的“对台政策”。

*** 北京“猛烈报复”新加坡，“证实”“517声明”的“不惜一切代价”“所言不虚”

结果，新加坡遭中国的猛烈报复，而且报复的手段就是专打新加坡的“经济影响”，一边切断新加坡政府在中国的重要商业活动、一边在外交上进行猛烈抨击，这还不算，还将凯山防空导弹系统连同制造技术、一并卖给了新加坡的“宿敌”马来西亚。

在东方评论员看来，北京在报复的“程度和手段”上，意在“刻意证明”北京“517声明”中的“不惜一切代价”“所言不虚”。

*** 澳大利亚，“公开、正式”宣布不会和美一起协防台湾

在新加坡公开表示“反对台独”、其它在一边观望的周边国家、“也就看清了”华盛顿的“台湾问题国际化”这条政策也走不通，之后，非常具代表性的事情是，美国的重要军事盟友澳大利亚，其外交部长唐纳和总理霍华德，先后公开地、正式宣布不会和美国一起协台湾。


*** 菲律宾宣布与中国加强军事联系

与此同时，我们也看到，另一个对美国协防台湾极其重要的国家-菲律宾，其总统阿罗约更上将其连任的首次外交访问选在北京、并在北京宣布与中国加强军事联系，签定与中国共同开发南海资源的协议。前不久、更是与中国正式签定了军事合作的协议。


*** 朝核问题被北京一度纳入了中国主导、日本、韩国、俄罗斯配合的局面

就在上面的事情一一发生的同时，东方评论员注意到，“中、美、日、韩、俄”围绕着朝核问题的“共识与分岐”也是愈演愈烈。在我们看来，这些“共识与分岐”在很大程度上、其实就在于这些国家如何看待“东亚经济一体化、以及亚洲经济一体化”，如何定位自己在这一进程中的地位。

不难看出，在这个问题上，华盛顿从自己独霸全球的政治、经济战略出发，其基本立场可以说是完全与另外几方对立的。

东方评论员认为，正是有这么一层，在去年6月“朝核问题”最后一次“六方会谈”期间，由于美国的一味强硬，想将朝鲜半岛长期置于“可紧可松”的“不稳定”之中，好为其中东政策服务，挟持受朝鲜局势影响最大的“中日韩”、去配合其全球战略，结果、在最后一次“六方会谈”中、在应该如何解决朝核问题的“对立”中、竟然出现了让华盛顿尴尬的“4（中日韩俄）：1（朝）：1（美）”、或者“5：1（美）”的场面，最后，朝核问题被北京一度纳入了中国主导、日本、韩国、俄罗斯配合、“准备去搞活朝鲜经济”、以发展朝鲜经济为条件去永久解决朝核问题的道路。


*** 在改善对朝关系上、一度表现最积极的不是别人，而是小泉纯一郎


只是华盛顿眼见朝鲜半岛局势远离自己的战略目标，就开始暗中作梗、但是，去年6月最后一次“六方会谈”后，中国、俄罗斯、日本、韩国都不顾美国的反对、着手准备参与朝鲜经济改革。

其中，在改善朝鲜外交孤立处境问题上、一度表现最积极的不是别人，就是日本首相小泉纯一郎，当时的小泉后来还成功地第二次访问了平壤，并着手与朝鲜建立外交关系。

东方评论员认为，我们从一年前的这段历史不难看出，日本当时与中国、韩国站在一边，有一层打算，即，如果可以的话，则准备从经济上解决朝核问题，其出发点是借其亚洲第一经济大国和技术大国的地位、在整合包括中国东北、日本、朝鲜半岛、俄罗斯远东在内的“东北亚经济一体化”的过程中抢得先机，为其成为“正常国家”打下坚实的基础。


布什政府正是目睹着朝鲜半岛局势已经脱离了自己的控制，并有可能引发自己的亚洲战略危机，最后不得已、到9月份，华盛顿突然搞出了个“朝核问题”。


*** 华盛顿突然抛出“韩国核问题”


在9月份抛出了“韩国核问题”这一险棋。利用日本急于成为“正常国家”的心理，以“核诱饵”引诱日本离开了中国主导的朝核问题进程、从而暂停了北京欲将“朝核问题”发展成为一个“东亚安全架构”的计划，也暂停了“中日韩”有意借此加强东亚经济一体化的努力。


*** 朝鲜也升起一团“蘑菇云”

而朝鲜则在中央政治局常委李长春访问平壤前一天、弄出了恰似核爆炸的一朵“蘑菇云”，且“就是不在”第一时间里给出“合理解释”，而让“方方面面”各怀目的地、在那里不停地“猜猜猜”。


*** 华盛顿亮出“核萝卜”之后，日本又一头扎进了华盛顿的“怀里”

后来，在“韩核问题”之后，在布什亮出“核萝卜”之后，日本又一头扎进了布什的怀里，显然，在东方评论员看来，核武器无疑是日本实现“正常国家”的“增速器”，不可否认的是，以日本的人口规模、经济总量、制造技术、常规军力，一旦跨入核门槛，那么，什么政治大国、军事强权、经济霸主、一一都不在话下，一旦如此，日本不仅有了在亚洲与中国全面抗衡的本钱、也必将在世界范围内与美国一争高低、一别苗头。

也正是有这种可能性，将独霸全球当作自己现行战略目标的华盛顿、又怎么可能容忍日本跨入核门槛？于是乎，在朝鲜升起一朵奇怪的、“类似核爆炸的蘑菇云”之后，华盛顿通过“坚决否认”那是朝鲜“核爆炸”的产物、而最终断了日本想借韩国“研究核武器”、和朝鲜进行“核爆炸”之机、挤进核门槛的念头，从而将那颗让小泉纯一郎“心跳加快”的“核萝卜”给一把收了回去。


*** 朝鲜半岛的局面又恢复到了最后一轮“六方会谈”之前的大体平衡局面

东方评论员认为，在华盛顿通过“韩核问题”引诱日本、从而打断了北京主导的“朝核问题进程”之后，可以说，华盛顿成功地将朝鲜半岛的局面又恢复到了最后一轮“六方会谈”之前的大体平衡局面，即中国、朝鲜、俄罗斯“说话大体投机”，美国、日本“立场大致一致”、韩国则大体居中。

*** 在一番“来回的折腾”之后，最尴尬的就是日本

事实上，在我们看来，在“韩国核问题”上，最尴尬的就是日本，在一番“来回的折腾”之后，可以说其实现大国梦的两条路（参与朝鲜经济改革、整合东亚、亚洲经济是一条慢行路、而跨入核门槛则是一条快车道），可以说“都不上路”，是一头都没有得到。

*** 朝鲜半岛局势更是“急转直下”，台海战争“硝烟集聚”


在东方评论员看来，中美交手经过上述阶段之后，可以说，东亚局势也就达到了“白热化”的程度。这表现在华盛顿在那之后，再次将操纵“台独进程”的“重心”移到台湾岛内，从而在10月份，默让“陈水扁发表台独意味极浓、挑畔味的双十致词”、接着就是台海战争硝烟集聚、大陆再次放风进行大型“具实战特点的东山岛军演”、而朝鲜半岛局势更是“急转直下”。

就在这之后几天，时间刚进入10月份，华盛顿通过多种渠道披露了“两份军事打击朝鲜的军事作战计划”，而中国则将近三万解放军调到中朝鲜边境，换防原来的武警部队。

而之后不久，急需平安渡过大选的布什，让美国前国务聊鲍威尔“抢在美国总统大选前投票前访华”，发表“台湾不是一个主权国家”的讲话。

*** 布什成功连任之后，再次默许陈水扁扯动“台独大旗”以求“泛绿过半”
然而，就在布什成功连任之后，再次默许陈水扁继续以“推动公投制宪”的名义、名为台湾“立委选举”造势、实则想以“泛绿过半”、让泛绿在已经控制行政权的同时，再夺取立法权，从而全面控制台湾、继而彻底阻绝大陆对台湾政治、文化的影响力，一旦做到这一点，华盛顿就必然会唆使台独势力，去继续推动“台独时间表”，通过不停地去“测试大陆底线”的方式、不停地去为美国的伊拉克问题、伊朗核问题中东进程，全球战略牟取最大的利益。


*** 短期内，两件事影响了美国的“对台政策”

另外，也是在这之后不久，短期内，可以说有两件事影响了美国的“对台政策”：第一，北京根本就“不理睬”华盛顿史无前例的“反台独”，坚决地启动了“反分裂国家法”进程；

第二，伊拉克议会选举是如期举行、结果是选出了一个华盛顿最不想看见的结果，既美国伊拉克叶派掌握了议会、在“中欧俄”的策应下，伊拉克政治重建进程也开始脱离了美国事前设定的轨道。


*** “反分裂法”将“台独意味着战争”从“极大的可能性”转换成“绝对的必然性”


而北京则一面在伊朗核问题上公开支持伊朗和欧洲的立场，站在第一线阻击华盛顿的中东战略的核心--伊朗政策，一面果断启动“反分裂国家法”进程，将“台独意味着战争”从“极大的可能性”转换成“绝对的必然性”，意在“迎面拦截”美国、日本和台独相互勾结、全力推动的“和平台独”。

从而最终让布什“终于感受到”胡锦涛在去年11月亚太峰会上所说的：“台独”将断送台海和平...也将危及（包括美国在内”的亚太区域稳定和繁荣的“真实性”，在美国的中东政策全面陷于被动的时候，在华盛顿决策层需要集中精力继续其“拿下中东、控制世界”的战略的需要下、被迫在台湾立法委员选举投票前、开始高调“反对台独”，以暂停“台独进程”、避免“和平台独”在这个华盛顿最需要避免与中国提前摊牌的时候、与“反分裂国家法”的“非和平方式”迎头相撞。


*** 困境中的华盛顿，开始谋求东亚的稳定

东方评论员认为，“台独进程”被“反分裂国家法”堵住了去路、解决伊拉克、以伊拉克为基地、进而解决伊朗的计划，也因伊拉克局势无法稳定而被无限期延迟，在这种情况下，困境中的华盛顿，开始谋求东亚的稳定。

在我们看来，北京必须警惕的是，由于华盛顿的这种“稳定台海、稳定朝核问题”的需求是“短期”的，是为了能为其中东战略“淘换出时间”来，因此，根据东方评论员的观察，北京在同华盛顿一起稳定东亚的同时，显然是在“各取所需”。


*** 进入今年以来，在东亚角力中，华盛顿显然“非常狡猾”

在东方评论员看来，进入今年以来，在最近这一轮东亚角力中，华盛顿显然“非常狡猾”，始终将自己“放在第二线”：一边自己“反台独”，由支持“台独”的第一线退至二线、一边却去“促进””两岸缓和”的手段、一边以此去与北京谈朝核问题，一边还去以此刺激日本、从而将日本拉入协防台湾的军事同盟、让日本从“支持台独”的二线跳到第一线，通过日本去与大陆的台海政策“争高低、别苗头”，而自己则躲在一边，时刻准备通过以一种“第三者的超然态度”，寻找有利时机、逼迫“正被日本咬着”的北京、“以有利于华盛顿的方式”去处理台海、朝核的稳定问题。


*** 在印度的“中得美失”，令整个东亚局势“大致”是向对中国有利的方向演变着

然而，就如我们在之前的多期《时事解读》中所分析的那样，自赖斯3月份第二次访华之后，整个东亚局势“大致”是在按中美预定的方向演变着，只是在这中间，由于中美两国在印度的“中得美失”的巨大反差、以及日本在挑畔中国的事情上“最终的力不从心”，却导致了华盛顿“反而被迫”以一种“相对之前更加有利于北京”的方式、来处理台湾政党的“登陆问题”。


*** 东亚一轮“拳打脚踢”下来，真正被打得“喘气”是谁？

因此，东亚一轮“拳打脚踢”下来，在日本外相“北京败北”之后，受损最大的并不是华盛顿、也不是陈水扁，甚至也算不得是宋楚瑜。我们认为，真正算得上被打得喘气就是“急独”势力，还有日本政府。

在东方评论员看来，日本一直在抢时间制造机会、欲搞乱东亚以“图谋核武”；也想借“美日军事同盟”、通过“插手台湾”去催动“台独”、以让中美“在台海一步对立、在朝核问题直接面对”、从而寻机破坏目前这个沿袭于冷战的东亚安全框架，达到从中美夹缝中逃出来的目的。

*** 东亚棋局、其实已经是“棋到中盘”

显然，在连战拜谒中山陵的背后，由于这上面的这一层，所以，在我们一边要警惕华盛顿还会“想着辙”去重新挑起日本斗志的同时，一边还要心中有数，那就是，“中美日”这场“安排包括台湾、朝鲜半岛、日本战略定位”东亚安全的棋局、其实已经是“棋到中盘”了。

东方评论员认为，华盛顿要陈水扁与宋楚瑜搞这个“十点共识”的目的，是非常清楚的，那就是要打开“两岸和谈”的僵局，从而以此要求北京兑现诺言、继而打开朝核问题的僵局、最后“迅速”打开“东亚稳定问题”这个最大的僵局、将与华盛顿渐行渐远的卢武铉“尽可能拉住”、将正在困难中挣扎的小泉纯一郎“尽可能地稳住”。

然而，前些天，东方评论员已经分析过，卢武铉访美国、在和布什的会谈中，从美国一度威胁要从韩国“全部撤军”来判断，“美韩”间的裂缝不仅仍然存在，而且在继续扩大。

另外，自去年9月份之后，重新紧跟布什的小泉纯一郎、在国内的日子也是难熬。大家知道，自吴仪“拂袖而去”之后，北京施加给日本社会的强硬态度、已经开始发酵、进而促进了小泉纯一郎受到的政治压力“也已经开始发酵”，这之中，以日本“遗族会”、这个坚定支持小泉参拜“靖国神社”“突然改变态度”最能说明问题。


*** 两只美国的东亚战略之“锚”，一只有了“外心”，而另一只则“没有了重心”

在昨天的点评中，我们就着重分析了这一点，在我们看来，日本“遗族会”这个“极右团体”，作为小泉纯一郎最坚定的支持者、现在也开始公开要求小泉“不要参拜了”，这已经说明，企图以历史问题催动日本社会“加速右转”的日本右翼、也已经感受到了“搬起石头砸自己的脚”的痛苦。众所周知，日本“遗族会”不仅是要求小泉纯一郎参拜靖国神社最核心的“右翼势力”，也是小泉纯一郎以参拜“靖国神社”去“回报对自己的支持”的主要对象。


显然，卢武铉和小泉纯一郎、韩国和日本，这两只美国的东亚战略之“锚”，一只早就有了“外心”，而另一只则开始“没有了重心”，这些，开始让华盛顿决策层有点坐不住了，但是，华盛顿这次有力量继续“阻止到底”吗？当然，这将是我们密切关注的事情。

东方评论员认为，今天韩国代表团14日分别乘包机前往平壤，参加在那里举行的“6·15《南北共同宣言》5周年民族统一大庆典”，这实际上很有可能就是那个、已经被华盛顿掐死了的“阳光政策”复活的征兆。

显然，在我们看来，如果华盛顿这次无力阻止“中韩”一起以经济手段、去“稳定”朝核问题之“要价”的话，那么，包括台湾、朝核、日本问题的整个东亚局势也许就开始了“另外一种阶段”。

在我们继续讨论这个“另外一种阶段”之前，我们再来看一则消息，之后，东方时事评论员、经济评论员将就韩国国务总理李海瓒将于６月２１日至２３日对中国进行的“正式访问”，谈谈其中可能会涉及的、华盛顿极力破坏，但中国和韩国、俄罗斯都十分关注的朝鲜半岛经济整合、整个东北亚的经济整合的问题。


《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
