# -*- org -*-

# Time-stamp: <2011-08-04 13:13:27 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 2005年8月31日 星期三


  

** 伊拉克巴格达发生踩踏惨剧：650死238伤


【巴格达消息】中新网8月31日电据报道，伊拉克内政部称，至少有650多人今日在巴格达底格里斯河上的一个桥梁上发生的踩踏事故中丧生，另有238人受伤。

在听到有自杀式炸弹袭击者混入人群的传闻后，参加什叶派穆斯林宗教庆典活动的人群由于惊慌而发生了大规模的踩踏事故，人们纷纷跳入河中，绝大多数死者都是溺水身亡的。

事发时有数千名伊拉克人正在前往卡德米亚清真寺参加一个宗教庆典活动。卡德米亚清真寺是位于巴格达北部旧城区的一个重要的什叶派穆斯林圣地。

在对伊拉克新宪法举行公决之前，主要宗教派别和各民族派别之间的紧张局面正在加剧之中。

今天早晨巴格达全城都有听到爆炸声，至少有七人死于数起迫击炮袭击事件。一名路透社记者报道说，他听到巴格达国际机场附近传来了六声迫击炮弹爆炸的声音，但美国军方还没有证实这一消息。

伊拉克议会于上星期天完成了宪法草案的起草工作，但宪法还必须在10月15日之前举行的公决中获得通过才能生效。



【时事点评】在东方评论员看来，在我们为这种人间惨剧不胜唏嘘的同时，我们也不得不为造成这一惨剧的诸多“人为因素”不胜感慨！


*** “践踏惨剧”显然与这起迫击炮袭击“有直接的因果关系”

在东方评论员看来，正如新闻中所提及的那样，在巴格达踩踏惨剧发生前，百万名什叶派教徒朝圣的清真寺曾遭到迫击炮弹的袭击，当时就有7人死亡，数十人受伤。而这场因惊慌的人群相互践踏而造成的、伤亡近700人的惨剧、显然与这起迫击炮袭击“有直接的因果关系”。


*** 惨案对某些国家、或者某些政治势力而言，可谓是来得“真不是时候”

事实上，我们收到的第一则消息是“巴格达遭受迫击炮袭击、造成５死３６人伤”，由于我们一直在关注伊拉克宪法草案进程，关注着伊拉克国内的什叶派、逊尼派、以及库尔德人之间、为那部至关重要的“伊拉克宪法草案”正进行着的“互斗”，因此，这几枚落在在巴格达的“迫击炮弹”，引起我们的高度警觉，显然，在东方评论员看来，这种惨案对某些国家、或者某些政治势力而言，可谓是来得“真不是时候”。

然而，就我们密切关注“迫击炮弹”是否会“直接落在正聚集在巴格达卡都米耶区的清真寺，参加纪念什叶派圣人——穆萨·卡齐姆阿訇的宗教活动的什叶派人群之中”的同时，参加宗教仪式的人群中却突然流传起“有自杀式炸弹袭击者混入人群”的消息。下面，我们先来了解相关内容，之后东方评论员将继续回到这个话题。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com





巴格达踩踏事故目击者称：“过桥时有人大喊人弹”



【巴格达消息】据半岛电视台报道，在伊拉克巴格达底格里斯河一座桥梁上发生的踩踏事故中有640人伤亡。当时人群听到有自杀爆炸人弹混入参加什叶派穆斯林宗教庆典活动的信徒中后，很多人由于慌不择路拼命逃跑而发生了大规模的踩踏事故。

事故现场拍下的电视画面显示，数万名信徒正在向阿尔·卡德希米亚清真寺走去以纪念什叶派一位德高望众的宗教领袖的祭日。据目击者称，在距离清真寺很近的一座桥上，突然有人大喊有自杀人弹就在人群当中，桥上的信徒们立即慌张地开始四散、希望尽快过桥，还有人直接从桥上跳进了河中。

一个消息人士说：“当时有数十名信徒跳进了底格里斯河，大家都在传有两个自杀人弹混入了人群中。”

电视台的报道称，当时大约有来自巴格达和其他周边省份的100万名信徒正在朝清真寺走去，为了显示虔诚，甚至还有人一路爬着前行。

负责维护事发地点安全的警察局准将卡利德·哈桑表示，发生这次踩踏事故的主要原因是当时过多的信徒正准备过桥，突然听到错误的传言后人群猛跑造成桥上过于拥挤。他说，遇难者大多是被踩死的或是在跳入河中之后淹死的。



【时事点评】对这次“大规模的踩踏事故”，我们注意到，已经有外电开始认为，这“极可能”是伊拉克派别繁多的反美武装中的一部“精心策划的”一次“大规模袭击案”。

*** 六枚迫击炮弹、“就是要轰击”聚集在清真寺周围的什叶派信徒

在东方评论员看来，这种猜测虽然没有提供“直接的证据”、但却也不完全是“空穴来风”。为了更好地说明问题，我们现在不妨回顾一下今天收到的“零零碎碎”的信息：

首先，就在上午，我们收到的那则最早的消息，是一名路透社记者所报道的，他在报道中说：“他听到巴格达国际机场附近传来了六声迫击炮弹爆炸的声音”。事实上、从稍后更加频密的消息判断，这“六声爆炸”就来自巴格达卡德米亚清真寺附近。毫无疑问，这六枚落下的迫击炮弹，其攻击目标也是“显而易见的”，那“就是要轰击”聚集在清真寺周围的什叶派信徒。


*** “这一系列事件”同时出现，不得不让人怀疑这是一起经过周密策划的袭击案

东方评论员认为，尽管这次“直接轰击”当时仅造成了几人丧生，但是，对当时正在朝拜中的什叶派教徒而言，这种“有针对性的轰击”带来的心理影响无疑是非常巨大的。

然而，这还不是事情的全部，我们注意到，后来的消息证实“踩踏事件的幸存者”非常肯定地认为：在什叶派人流通过大桥时，的确有人在喊“人体炸弹要引爆了”之类的话。

另外，伊拉克警方也认为“炸弹谣传造成了人群的失控”、另据CNN的报道，在死亡人群中有几十人并非死于骚乱，而是因为在清真寺内食物中毒毙命。显然，“这一系列事件”同时出现，不得不让人怀疑这是一起经过周密策划的袭击案。


*** 如果这的确是一宗精心策划的“大规模袭击案”，其意图就“具有高度的政治性”

在东方评论员看来，如果这的确是一宗精心策划的、且已经造成近700人什叶派教徒死亡的“大规模袭击案”，那么，其意图就“具有高度的政治性”，我们认为，“策划者”想的就是彻底破坏华盛顿正在竭力进行的、旨在“烫平”几年伊战造成华盛顿内部、以及伊拉克内部诸多“政治纷争”的不懈努力。


首席评论员指出，现在距离布什站在航空母舰上“意气风发”地宣布“伊拉克战争已经胜利”的那天、已经过去了“两年半”的时间，在我们看来，这过去的“两年半”对华盛顿而言，无疑是极其尴尬的“两年半”。


*** 在过去的两年半中、华盛顿一直在忙活一件事儿

期间，仅仅是为了让美国民众“相信”发动伊拉克战争的“合理性”，华盛顿决策层在宣传策略上就是“数易其稿”：从最先的“认定”“伊拉克在发展大规模杀伤性武器”、到之后的“咬定”“萨达姆与本拉登勾结、并发动了911袭击”、再到今天、布什政府正在“搞定”的、“向伊拉克这个独裁国家移植美国式的民主体制”，总而言之一句话，自华盛顿“准备发动”伊拉克战争以来、在过去的两年半中、就一直在忙活一件事儿：“始终不懈”地在为这场已经打了两年半的伊战“找理由、觅根据”，


*** 所谓“伊拉克民主进程”，成了白宫“拒绝制定撤军时间表”之“冠冕堂皇”的借口

就目前而言，在经过了“否定”再“否定”之后，几个月前、布什好歹又捞了条让美国民众一度“将信将疑”理由，这就是布什连任之际、在就职典礼上极力渲染的伊拉克“民主”进程，在东方评论员看来，这似乎已成为“共和党政府”唯一可以让民众信服的发动战争的“理由”，同时也成为白宫决策者“拒绝制定撤军时间表”的、一个“冠冕堂皇”的借口。


*** “美国今后几年大选行情”的“一个关键词”

由于美国明年将举行中期选举，布什所属的、共和党的“议员与洲长侯选人”、迫切需要一个“比现在漂亮得多”的“伊拉克问题”以稳住民心、争取选票，如此一来，“伊拉克民主进程”、毫无疑问地成了“美国今后几年大选行情”的“一个关键词”。


*** 共和党政府要再想找寻个“伊战理由”、在“时间”和“信用”上都来不及了


在东方评论员看来，让布什政府尴尬的是，在“伊战理由”的问题上，在经过“两年半”的“否定”又“否定”尴尬之旅后、如果现在再因“伊拉克宪法”最终无法通过、而令“向伊拉克成功移植美国式的民主体制”这一条精心包装的、最新的“伊战理由”也站不住脚的话，那么，美国执政的共和党阵营恐怕就真的要被选民所抛弃了、道理似乎非常简单，那就是，共和党政府再想找寻个“伊战理由”、哪怕是让美国社会“将信将疑”理由、在“时间”和“信用”上、似乎都来不及了。


*** 就这么个“小小的环节”、布什政府在费了九牛二虎之力的情况、竟然也“没有搞掂”

另外，如果我们将“伊拉克宪法”问题放在美国中东战略、甚至是伊拉克政策的背景下来看、东方评论员认为，现在“闹腾得最欢”的“新宪法草案”问题、也不过是对华盛顿全球战略至关重要的“伊拉克政治重建问题”中的一个“小小的环节”而已。

然而，就这么个小小的环节、布什政府可是在费了九牛二虎之力的情况、竟然也“没有搞掂”。结合伊战以来、布什对美国社会许下的种种诺言、是无一不落空的事实，这就不能不让美国有意问鼎白宫的“有识之士”、去“刻意地”引导美国社会、去认真地思考这么一个问题，即美国新保守主义者所拟定的、准备将伊拉克打造成一个“中东民主之花”、意图逐渐控制中东的“伊拉克政策”是否已经全面失败？


*** 共和党阵营不会睁睁地看着“对手”将“伊拉克问题”当作“提款机”

在我们看来，客观上讲，华盛顿决策圈目前都在为这部“宪法草案”“沤心沥血”，布什自己也在因为这部“迟迟没有定案”的“宪法”承受极大的政治压力。我们注意到，逊尼派拒绝接受“宪法草案”、不仅再次“凸现了”在伊拉克阵亡的美军士兵已经达到了“1900人”这个数字的“恐怖”、更是直接激化了美国国内的反战呼声。

东方评论员认为，这些来自伊拉克国内的“恐怖”与“激化”，似乎都在布什的那个已经暴跌到36%的“支持率”上、得到了“充分地反应”：要知道、这可是自他5年前入主白宫以来的“最低水平”。

首席评论员指出，必须强调的是，尽管因美国宪法限制，布什本人不可能竞选三年之后的美国总统了，但是、不论是他所在的共和党阵营、还是与他瓜葛甚深的美国政治、经济利益集团、都不会睁睁地看着其国内、国外的政治、经济对手，毫无限制地将“伊拉克问题”当作“政治、经济利益”的“提款机”


*** 美国民主党已经再次瞄着布什的这一痛处、声称要给布什和共和党人“好看”

在东方评论员看来，就布什的国内政治对手--民主党而言，在今后几年中继续借伊拉克的乱局、在全国范围内凭借一杆“反战”大旗、在美国接连不断的议会选举、洲政府选举中“攻城拔寨”、“抢夺失地”，也更不愿意眼睁睁地看着民主党人一点点积累这些地方政治资源、最终为“重返白宫”打下坚实的政治基础。

因此，我们认为，布什现在要过的第一关就是美国国会众议院将在明秋进行的“全面改选”，显然，种种迹象表明、美国两党政治人物早已经认定、这是一场难打的选战。

正是基于这一点认识，美国民主党已经再次瞄着布什的这一痛处、放出风来、声称将在9月6日国会复会后、就要给布什和共和党人“好看”。


*** 华盛顿内部“正流行着”对布什的伊拉克政策“信心全无”的“流行病”

然而，在东方评论员看来，面对这么一场硬仗，布什所属的共和党阵营、其最大的敌人并非来自外部、而是来自其内部、因为其内部“正流行着”对布什的伊拉克政策“信心全无”的“流行病”：毕竟，自小布什宣布“伊拉克战争胜利”已经过去两年了，不仅在“经济利润丰厚”的伊拉克“经济重建”问题、仍然是“两手空空”，就是在已经被宣扬为美国大中东民主计划的“标志性建筑”--伊拉克政治重建的问题上、也由于这部“美国版的伊拉克宪法”难产、而仍然是“两眼茫然”、“不得要领”

也正因如此，布什以及他所属的共和党、政治、经济利益集团、都在“望穿秋水般”地期盼着“伊拉克宪法”的“破壳面世”。


*** “靠着”美国当时自己立下的游戏规则，逊尼派早已摆出了一副“废掉”该宪法的架式。

然而，华盛顿想让这部美国色彩浓厚、且也“极具权宜特征”的“伊拉克宪法”“破壳面世”、并“正式指导”伊拉克顺利完成政治重建进程，又谈何容易？对此，东方评论员有一句话愿意早早地就放在这儿，在我们看来，这简值是“比登天还难”！

在我们看来，这部美国版的“伊拉克宪法”是否能够通过伊拉克全民公决、原本就是个“未知之数”。我们知道、根据美国“制定”的“伊拉克临时宪法”，这部美国版的正式宪法、在起草工作结束后，应在10月15日前举行全民公决。

然而，让华盛顿揪心的是，按美国当时自己立下的游戏规则，如果伊拉克18个省中任何3个省超过三分之二的选民投反对票，这部“沤心沥血”“妥协、让步出来”的宪法草案将被推翻，而“制定”它的“过渡议会”也必须解散、如果真走到了这一步，布什在伊拉克政治重建问题上，就真到了“一事无成的地步”。

要知道，伊拉克至少有3个逊尼派阿拉伯人占多数的省份。据我们知道的情况，逊尼派政治和宗教领导人一边拒绝在“宪法草案”上签字、一边也早已呼吁逊尼派民众积极登记参加10月15日前举行的“全民公决”，显然，“靠着”美国人自己立下的游戏规则、逊尼派早已摆出了一副“废掉”该宪法的架式。

今天，东方评论员会议主席团，经过这场极可能专门针对什叶派教徒、意在挑动伊拉克内斗、全面破坏这个华盛顿主导的“伊拉克宪法”“立法进程”的“惨案”，其“命运”必将更加艰难。


*** 我们关注的重点却根本就不在这部宪法上

然而，我们关注的重点却“根本就不在这部宪法上”。在东方评论员看来，这部宪法是否通过，对美国共和党的意义远大于美国国家利益，在东方评论员的眼里、它对美国国家利益而言，几乎没有什么值得一提的“实用价值”。


*** “有无”这部美国版的“伊拉克宪法”并不是关键，关键在于“有谁参与指导”


事实上，我们认为，与这部美国版的“伊拉克宪法”相类似的“美国文件”、可以说“早已拟定”、且华盛顿也一直在“身体力行”，结果、美国人在伊拉克“仍然指导出了”今天这么一副不堪入目的乱象。由此可见，在伊拉克政治重建问题上、有无这部“美国版”的“伊拉克宪法”并不是关键，我们认为，关键在于“有谁参与指导”。


*** 没有“中法德俄”的“认真指点”，美国还真玩不转“伊拉克重建”这档子事儿

显然，“两年半”的事实已经充分证明，要搞好伊拉克的事情、没有“中法德俄”这个“抗美小集团”成员的“认真指点”，仅有英国和日本打下手的美国、还真玩不转“伊拉克重建”这档子事儿、而“中法德俄”几个大国、甚至包括日本、印度在内，还真有人、而且还不止一个、时不时地拿“伊拉克问题”当作向华盛顿“提取政治、经济利益”的“提款机”来着。

东方评论员认为，对华盛顿也好，对布什共和党政府也罢、如果真想解决伊拉克问题、让伊拉克走上顺利重建的轨道、而不让伊拉克问题再刺伤自己的国内、国家利益、恐怕还得放下其中东的“既定政策”，与相应的“对手”坐下来好好商量一下，将各自的利益“重新划拉”一下。

在这一点上，在前面的东亚部分，在讨论胡锦涛主席美国之行的访问行程时、事实上我们已经从国家利益的层面上谈及了，那就是，在中美这次高层对话、胡锦涛主席与布什总统、除了在“包括日本定位、台湾、朝核问题”的东亚一揽子问题要好好商谈之外，如何初步确定中、美双方在中东、中亚的利益、也是几个绕不过去的重大话题。

在一段有关伊朗核问题的最新消息后，东方评论员将继续就胡锦涛与布什之间、在伊朗核问题上可能谈及的问题给出我们的一个判断。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com


