# -*- org -*-

# Time-stamp: <2011-08-02 18:50:43 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

#+STARTUP: indent

* 2005年01月07日 星期五

  

** 华盛顿弃主导赈灾中国显大国风范

【香港成报/社论】  南亚地区的救灾工作正进行得如火如荼，联合国的救灾会议更凝聚了人类的爱心，务求在最短的时间内为灾民送上最实际的物资和救援服务。在灾场里，人们可以看到不同肤色、不同种族、不同国家，以至不同阶层的人，无分彼此地为灾民送上有形或无形的关怀，令人感到这个世界并不冷。

就是这种全人类的暖意，令平时一霸独大的美国也不能在这次救灾工作中妄自尊大。在灾害发生之初，美国只作象征性的援助，后来在国际舆论压力之下，才开始伸出援手，增加拨款，并派出国务卿鲍威尔前往灾区视察。美国在救灾过程中，曾计划拉山头，与日本等同声同气的国家组成核心集团的指挥中心，以主导救灾工作，并从中创造日后能插手南亚地区事务的机会。这是美国在国际上惯用的方法，在阿富汗、中亚地区、伊拉克等地，美国的霸主意识和企图表露无遗。今次，美国也表示可以协助制定海啸预警系统，但背后似乎还有很多未宣之于口的话，令人感到她正希望透过救灾工作来达致政治目的。

不过，在这次联合国救灾会议中，各国一致认为应该由联合国统一指挥救灾工作，迫使美国放弃和解散了所谓「核心集团」的指挥中心。这次算是美国从善如流，不敢冒天下之大不韪。在各国的努力下，如今已筹得约四十亿美元，可以预见，日后的救灾工作将会有较大的成效。不过，联合国鉴于部分国家过去没有兑现援助的承诺，特别要求各国应先交出部分已承诺的捐款。可见经一事长一智，这是人类共同智慧的胜利，不再被个别大国主导和左右一切了。

中国在这次救灾过程中，虽然不是捐款最多的国家，但所扮演的角色却是积极和实际的。中国一直把救灾工作的实效放在第一位，正如总理温家宝所说，救灾工作讲求高效和有序，中国出钱财，出人力，出建议，显示了作为一个负责任的大国的风范。

更值得一提的是，中国全心全意地救灾，没有被某些政治化的行动分散精神。举例说，台湾当局本想趁救灾之机混水摸鱼，在救援物资及有关工作中拓展「中华民国」或「台湾国」的空间，并要求参与联合国的救灾会议。面对这类「抽油水」的计谋，北京方面看在眼里，但没有分散救灾之心，让台湾的物资按计划送到灾区，即使物资上有「中华民国」的字眼，既然是救灾用品，就应该第一时间送到灾民手上，不能延误。不过，对于台湾要求参加以主权国为成员的联合国救灾会议，北京则坚决反对。在在显示，北京处理救灾与政治之间的问题，既坚守立场，又弹性处事。

还有，中国想到日后仍可能出现这类天灾，必须及早集合人类的智慧，研究出更完善的海啸预报系统。本来，美国在这方面的技术是比较先进的，但她没有公诸于世，只留下来为美国预警之用。中国认为不应这样处事，所以大力主张各国尤其是受灾国家共同研究海啸预警之法，中国将作出力所能及的贡献。这与美国只为一己之私相比，更赢得各国的敬重和世人的赞赏。

总之，这次天灾令人类进一步醒觉，必须共同努力面对一切挑战。在巨大的灾难之前，人类的纠纷、争斗、战事、私欲，都显得渺小之极。香港人也应该引以为鉴，洗涤心灵。较早时候，多个政党取消政治性的游行，改为联合赈灾筹款活动，显示爱心为重。今天，香港还有马拉松式的筹款活动，这也许是华东大水灾之后的最大型筹款，所有香港人都应该全情投入，慷慨解囊吧。


【时事点评】 对于这场海啸之中的政治角力，东方评论员也已经说得够多的了。在我们看来，直到目前为止，可以说中国在这场“救援行动”中表现得仍然非常不错！


*** 北京将将救援工作“简单到单纯的人道救援”

在之前的点评中，东方评论员就一直在强调一个观点，那就是：对于这场巨大的自然灾难，中国一定要尽力做好人道救援的工作，以体现一个地区大国应有的责任。然而，也如我们曾经说过的那样，由于“人道救援”仅是前期工作，其后的“灾后重建”将是一个长期、花费巨大的工程，因此，东方评论员认为，北京在安排整个援助工程时，一定要有“两个前提”，首先就是“力所能及”、其次就是“真心实意、将救援工作简单到单纯的人道救援、不要附带任何条件，不要显露什么政治野心”。


*** 在进行对外援助的过程掩饰“政治考虑”方面，中国可以说是经验独到

事实上，谁都知道，在这种大规模救援的背后，又有哪个国家可以不将“救援”与“政治”合在一起考虑的呢？在东方评论员看来，中国也一样，也有自己的政治目的，可关键是，自己应该怎么做，才可以将政治因素隐藏的更好。

东方评论员认为，在进行对外援助的过程中、掩饰自己的政治考虑方面，中国可以说是经验独到，多年前，在毛泽东主席时期，中国对朝鲜、越南、对亚非拉的大规模援助，很多都是在“不附带任何条件”行动中、在经济上付出了许多，但实际却收获了大量的政治利益。而这其中的许多政治好处，包括联合国的特定权力，是现在有的国家想花多少钱都买不到手的。


*** “炸馆事件”后，教训深刻的中国、立刻调整了这种“有偿援助为主”的错误尝试

后来，在90年代中期，北京曾经尝试搞“有偿援助为主”的外援政策，事实证明，这种尝试让中国付出了相当的代价，据我们观察，好在炸馆事件之后，在国际社会一度孤立、从而教训深刻的中国、立刻调整了这种“有偿援助为主”的错误尝试、重新重视“
#+HTML:<a>不附加任何条件</a>
#+LaTeX:\red{不附加任何条件}
”外援的战略作用、并定位在“
#+HTML:<a>力所能及</a>
#+LaTeX:\red{力所能及}
”的水平上。


*** 中国的表现应该用“非常出色”这一词来加以形容

在这次的
#+HTML+:<a>印度洋海啸救援</a>
#+LaTeX:\red{印度洋海啸救援}
过程中，中国的表现就如我们之前一再所指出的那样，可以说应该用“非常出色”这一词来加以形容。东方评论员之所以如此评价中国政府的表现，就在于直到目前，北京在“不附加任何条件、不表现政治意图”、以及“力所能及”这两点上，把握得相当连贯。

现在，如果再回过头去看看在“海啸”中打政治牌最积极的两个国家--美国和日本，那么，我们不难看出：“出人”不及美国“百分之一”、出钱不如日本“慷慨”的中国，显然是靠着自己这种“力所能及”、“单纯的人道救援”行为，在短短几天内，已经让中国在这场“救援政治角力”中赢得了相对主动。


*** 华盛顿的“动机”也就在国际社会的眼里显得“晃眼得多”

东方评论员认为，特别是美国、美国作为一个全球大国，其政治经验也非常老到，在我们看来，利用偶然事件、并从中创造日后能插手、并主导整个过程的机会、从而为自己牟取政治、经济利益，可以说美国在国际上玩得娴熟的手腕、也是其惯用的伎俩。

这次也不例外，然而，我们也注意到，正是由于华盛顿“心机太深”，在救援中考虑的“得与失”的程度和范围、无一不比中国考虑的“要周到许多”、因此，华盛顿的“动机”也就在国际社会的眼里显得“晃眼得多”。


*** 几天下来，华盛顿似乎就已经“风光不再”

事实上，连日来，我们都是在围绕“
#+HTML:<a>海啸外交</a>
#+LaTeX:\red{海啸外交}
”这个新名词来对这场政治角力进行分析、点评的，在东方评论员看来，作为这次世纪大灾难所衍生出来的这个“新名词”，顾名思义，就是相关政治势力、如中美、日，以至美欧、美国与伊斯兰国家等等、在“台上台下”、于“明里暗地”所展开的一连串外交和政治角逐。

几天下来，结果是一度因有能力大规模“调兵遣将”、动用独一无二的航空母舰战斗群、宣布要领导一个“联合救援指挥中心”进行救援行动的美国、似乎就已经“风光不再”了，联合国最新的消息表明，鲍威尔之前所说的“解散由美倡议成立的海啸救灾国际联盟”、也就是上面所说的“联合救援指挥中心”

在一起了解了联合国负责人道救援事务的副秘书长扬·埃格兰的“证实”之后，东方评论员将继续这个话题。

《东方时代环球时事解读》http://www.dongfangtime.com


** 联合国对美国解散海啸救灾国际联盟表示欢迎

【纽约消息】  联合国负责人道救援事务的副秘书长扬·埃格兰（北京时间7日）在纽约联合国总部举行的新闻发布会上说，美国国务卿鲍威尔５日宣布解散由美倡议成立的海啸救灾国际联盟并将该联盟的活动逐步交给联合国协调，他对此表示支持。

据新华社报道，埃格兰说，在美国、日本、印度和澳大利亚上周组成国际救灾联盟后不久，鲍威尔曾表示这一联盟将在适当时候停止存在，由联合国全面负责对海啸受灾国救援活动的协调工作。

埃格兰表示，国际救灾联盟成员国为在印度尼西亚亚齐和苏门答腊等地的救援工作提供了急需的交通运输工具，他们仍是联合国在海啸灾区开展救援活动的重要伙伴。

他说，在海啸袭击最严重的苏门答腊西部沿海地区的救灾工作已取得显著进展，救援物资已开始运抵这一地区的许多村庄。该地区地处偏远，交通极为不便，是开展救援行动最困难的地方。埃格兰还表示，目前联合国还无法得知苏门答腊西部地区在海啸中的确切死亡人数，由于该地区居住的人口多达１００万，很多村庄的遇难人数至今还无法知晓，因此印度洋海啸造成的最终死亡人数可能远超过此前估计的１５万人。

拥有５０００多名成员的联合国职员工会６日宣布，将通过联合国儿童基金和人道主义事务协调厅向海啸灾民捐款１０万美元。



【时事点评】 东方评论员认为，到此为止，可以说“心机太深”、“考虑过多”无疑是一度占据主动的华盛顿、最终失去“救灾指挥权”的主要原因。



大家也许还记得，在之前的《环球时事解读》中，东方评论员曾经强调，由于这场灾后重建将是一个“长期的工程”，因此，开销将是非常之大的，因此，任何“表演性”的、超出自己实力的动作、看似能“先声夺人”，可到了最后，由于中国、美国、日本与受灾国的政治、经济利益关系、很难因这场灾难而轻易改变，因此，在“长期救灾”中的“动机不纯”，非常容易导致与当事国的利益矛盾激化，从而最终尝到“搬起石头砸自己的脚”。

*** 追踪索源，“海啸救灾指挥中心”的“理论基础”正是那个臭名远扬的“中国威胁论”

众所周知，在此之前，美国为了尽可能地收取“政治溢价”，竟然借机想以“亚洲小北约”的框架来搭建一个“海啸救灾指挥中心”，明眼人一看就知，这个“海啸救灾指挥中心”的中心成员是美、日、印度、澳大利亚四国，而其核心就是美国，不难想到，华盛顿成立的这个“海啸救灾指挥中心（核心组）”的理论基础却是与“海啸救灾”完全不沾边的、根本就是我们非常熟悉的、那个臭名远扬的“中国威胁论”。

在首席评论员看来，而日本炮制、美日“联合推销”的这个“中国威胁论”、正是华盛顿“想用来组装”“亚洲小北约”的核心理论。


*** 颇具商人头脑的华盛顿、有着非凡的“将损失转变成商机”的本事

时事评论员认为，几年下来，“中国威胁论”在美、日的一再推销下，市场不见扩大，反日见萎缩，除去美、日这两个视中国为对手的两方外，另外两方--印度和澳大利亚、出于自己的经济利益和战略安全考虑、显然在“贯彻”“中国威胁论”上“有点心辕意马”，因此，“亚洲小北约”的说法虽然已有多时，但却“从未正式现身”，这不能不说是想全面遏制北京的美国之一大心病。

这一次，我们注意到，在灾害发生之初，美国只作象征性的援助，后来在国际舆论猛烈抨击下，这才开始伸出援手，并增加拨款的。然而，客观上讲，东方评论员认为华盛顿还是非常擅长于“将坏事变成好事”的，在我们看来，颇具商人头脑的华盛顿、有着非凡的“将损失转变成商机”的本事、这一点，在借“911事件”进入中亚的整个过程中、美国人的这种能力、就已经得到了非常充分地体现。


*** 用“聪明反被聪明误”形容华盛顿解散“海啸救灾核心组”再贴切不过

然而，中国有句老话，叫做“聪明反被聪明误”，在东方评论员看来，用这句话来形容华盛顿被迫解散才成立几天的“海啸救灾核心组”，就再贴切不过的了。

我们注意到，美国国务卿鲍威尔是这样描述解散行动的，他说“救灾核心组帮助催化了国际社会对救灾工作的反应，它达到了自己的目的，现在它要将自己融合到联合国更广泛的合作中去。”

事实上，谁都清楚，“四国救灾核心组”是布什于12月29日在德克萨斯自家的大农场里宣布的，其目的是要缓解联合国官员对华盛顿在救灾方面吝啬、反应慢的批评。要知道，布什最初仅同意拿出区区1500万美元援助受灾国。


*** 究竟是谁“帮助”了谁？谁又“催化”了谁？

显然，在东方评论员看来，事实就是事实，事实是无可辩驳的，何况这些都是发生在几天前的事情，那就是，以联合国代表的国际社会对救灾工作有正式反应“在前”，美国借机成立“海啸救灾核心组”的行为在后，究竟是谁“帮助”了谁，谁又“催化”了谁，可以说是一目了然、根本就不容狡辩！


*** 玩“将损失转变成商机”把戏、“美国动机”引起了国际社会警惕

在我们看来，美国自己正是在联合国的“不客气”的“帮助催化“下，才决定再玩一把“将坏事变成好事”、“将损失转变成商机”的把戏的。于是乎，国际社会这才看到美国似乎开始醒悟、这首先表现在承诺调动军队救灾、答应增拨援助资金、但是，直到布什准备借机成立“海啸救灾核心组”、欲取代联合国、以支配整个救援进程之后，“美国的动机”立刻就引起了国际社会的警惕。

连续几天，东方评论员一直注视着美国、日本这两个急于在“人道救援行动”中收获“政治溢价”的“积极分子”的“表演”，事实证明，将大批部队开往受灾国的美国、以及想用“5亿美元”将中国比下去的日本，虽然联合“表演”得非常精彩，也确实做到了“先声夺人”，然而，国际社会，包括受援国在内，都对这些“表演性”的动作、收买伊斯兰信众人心的“心机”、欲借救灾之名、行排挤中国、欧洲之实、欲重返东南亚、控制东盟的政治企图、看得清清楚楚。


*** 布什挂出“四国救灾核心组”牌子，引来“海啸外交”这个新名词

据我们观察，自布什将“四国救灾核心组”的牌子公开挂出来之后，华盛顿的“救灾工作”显然就立马变了味、偏离了救灾的方向，所谓的“海啸外交”这个新名词才呼之而出。在这期间，东方评论员注意到，随着“四国救灾核心组”牌子，“海啸外交”的名词，一同涌现出来的，是美国、日本媒体散布的大量攻击中国“救灾不力”的消息。

比如，美国微软-国家广播公司日前发表了一篇名为《中国海啸测验不及格》的文章。文章认为，除了驻日本的美国第七舰队，中国拥有该地区最大的海陆两栖军队，完全有能力向受灾地区输送大批救援物资。因此，该文对中国国防部在印度洋海啸后，却只强调中国将和俄罗斯举行联合军事演习、而对象美国那样调动军队进行救灾不闻不问“非常不满”，并以此来批评中国“言行不一”，指责北京在外交政策上仍旧坚守封闭的“不干涉”原则。

另外，我们还注意到，美国乔治华盛顿大学中国政策研究室主任沈大伟就认为，中国军方具有救灾的基本能力，言下之意也是对“可以利用海上行动能力援助受灾国家”的中国、却没有任何军事动作表示不满。


*** 在美国主导救灾的情况下出动解放军，将很难摆脱“政治上的被动”。

事实上，如果不是别有用心的话，说这些话的美国人应该清楚，之前，中国国防部早已经和相关国家的驻华人员有过相应的接触，然而，事后，中国国防部透露的消息说，中国的任何行动都会事先征求征得对象国同意。

显然，在东方评论员看来，中国国防部的话只说了一半，另一半恐怕就是“中国领导人也要愿意”这一句了。

首席评论员指出，在这场救灾行动中，到底派不派出军队，事实上绝非美国上述观点所说的那样、仅是“救援”上的事情，在我们看来，中国军队一旦在现在这种、美国主导救灾的情况下出动，将军力投放到印度洋，将很难摆脱“政治上的被动”。

显然，投放过少，没有什么帮助，也就更加显得不够诚心，而投送过多，美国、日本的说法就将立刻为之一变，什么中国远距离投放军事力量的能力、早已经大大超出应付“台湾独立”的说法就将立刻被炒起来，从而市场日见萎缩的“中国威胁论”不仅立刻找到了活生生的证据，还将立刻在印度、印度尼西亚、这些国内仍有强大反华势力的国家中找到“反华共鸣”。


*** 华盛顿、日本的大规模调动军队用于救灾就不会受到同样的怀疑吗？


然而，既然出动军队与否如此敏感，那么、华盛顿、日本的大规模调动军队用于救灾就不会受到同样的怀疑吗？

当然不是，在东方评论员看来，如果大规模调动军队用于救灾“只有利而无害”的话，那么，第一，美国、日本的军队早就出动了，特别是急于表现自己军事投送能力的日本。然而，情况并不全然如此，显然，在东南亚名声并不好的美国和日本、在出动绝对有救灾能力的军队之前，也是考虑得非常仔细了的。

东方评论员当时就注意到，许多欧洲的分析人士就认为，华盛顿出动军队有其优势，但这种优势是否能达成其战略目的还为时尚早，因为向这个非常警惕美国动机的地区出动军队、本身就是带有政治风险的，这就是说，华盛顿能否用航空母舰战斗群获取“救援”之外的战果，还不确定。


*** 美、日将简单问题、炒成“两难”的问题之后、再扔给了北京

其次，值得注意的是，东方评论员认为，在美国、日本抛出中国军队对“救灾不闻不问”的同时，其意图显然是在将一个解放军“去与不去”都无关紧要的简单问题、炒成一个“去与不去”都“两难”的问题之后、再扔给了北京。

东方评论员认为，真实的情况是，美国、日本事实上都是在美国自己搞的“四国救灾核心组”的名义下出动的，目前开到救灾现场的军舰，几乎就全部是这两个国家的，只有少量的非美、日的军事力量，在这种情况下，如果中国贸然向该地区投放军队，显然就形成了一个已经辐射到印度洋的中国军事力量、与“亚洲小北约”军事力量对峙的局面，在东方评论员看来，北京领导人聪明就聪明在根本就没有兴趣在这个时候去“与狼共舞”，不然，实际上是在为“亚洲小北约”的核心理论--“中国威胁论”在做免费广告。


*** 美、日之外、似乎都不约而同地对“美军、日军”的军事行动“绝口不提”

现在的情况是，华盛顿以“四国救灾核心组”的名义向印度洋投送军队、显然只获得了“救援”之内的战果，有意思的是，几天下来，美国大兵的救援行动并没有消除有关国家担心美军想重返当地的戒心。

与此同时，东方评论员却注意到：一方面是美国、日本自己在卖力地强调“军事救援”，然而，另一方面，不论是被挡在““四国救灾核心组”之外中国、还是欧洲、或者是俄罗斯、以及众多受援国，似乎不约而同地对“美军、日军”的军事行动“绝口不提”，相反，这些国家似乎还在找理由为同样被排挤在“圈外”的联合国“打抱不平”。


*** 北京瞅准了机会，提出了一项显然极具针对性的提议

也正是如此，北京瞅准了机会，在东盟地震和灾后问题领导人特别会议上，温家宝总理提出了一项显然极具针对性的提议：中国将积极参与以联合国等国际组织和东盟为主导的援助计划。

首席评论员指出，北京的这项提议显然和欧洲、东盟商量过，也可以说就是冲着美国、日本去的，冲着东盟担心美国军事力量重返当地的担心去的，因此，一经提出，立刻就获得了欧洲、东盟国家的响应，也立刻就置美国、日本于一种尴尬的处境。


*** 中国的建议、好就好在考虑到了两个关键角色的利益

在我们看来，温家宝总理的这一建议好就好在考虑到了两个关键角色的利益：一个是已经被美国剥去“救灾领导权”的联合国；另一个就是担心美国重返当地、从而破坏眼前这种、在中、美两大强权间维持平衡以获得最大利益的东盟；


*** 北京这一招可以说“非常狡猾”地拿回了决定权

显然，北京这一招可以说“非常狡猾”，显然，明眼人是一看就明白，北京明里是在拉欧洲、东盟一起，逼美国、日本将“救灾指挥权”还给联合国，实际上是和欧洲一起将“救灾指挥权”又拽到了自己的手心。

现在，“动机不纯”的美国已经在国际社会的压力之下、在相关国家怀疑与警惕的目光中、不得已解散了“四国救灾核心组”，实际上也是将指挥权被迫上交到了联合国的手中。因此，作为“五常”之一的中国、以及“五常”之列的欧洲、俄罗斯也就都重新从美国手中拿回了本就属于自己的那一份决定权。

在东方评论员看来，只是那个本想借这次机会、傍着美国大腿大干一番的日本，就不再能决定什么关键问题了。


*** 在联合国的“帽子”下，解放军出现在灾区将和目前美军主导下的情况有本质的区别

到此为止，在救灾指挥权回到联合国、实际上也是回到中国的手中后，如果灾情进一步严重，那么，如果我们听到中国将派出军队前往灾区，东方评论员将不会意外，为什么？就因为在联合国的帽子下，解放军出现在灾区的意义将和目前美军主导下的局面、有着本质的区别，但是，可以肯定的是，解放军即使出动、其规模也不会太大，一不会让美国、日本找到借机攻击中国的借口，也不会影响台海军事备战。


*** “动机不纯”美、日，才这么几天的功夫就已经尝到了“搬起石头砸自己的脚”的滋味

事实上，在东方评论员看来，在这场“海啸外交”中，在美国早前倡议设立捐款国施援联盟的时候，我们注意到，布什在一一点出了日本和澳洲等国的名字，还真颇有“意气风发”的味道：看看这些国家，无一不是美国长期战略盟友，其中，让人最为深刻的是，华盛顿就连印度都提到了，在最后，在以强调“预料会有更多国家加入”为名单结尾的时候，也偏偏不提中国，无奈北京不陪着玩，东南亚国家大多数领导人也不好骗，结果一度“先声夺人”、然而却“动机不纯”美国和日本，才这么几天的功夫就已经尝到了“搬起石头砸自己的脚”的滋味。


*** 在联合国手下“干活”，华盛顿的“油水不会大”

在我们看来，现在主导权已经到了联合国手中，可以想像的是，因为中、英、法、俄、德都在那“掐着”呢，什么扭转在穆斯林心目中的负面形象，为未来控制马六甲海峡海上生命线打下基础等等、在这些“抗美”大国的牵扯下，华盛顿很难做得比伊拉克更好、更出色。

所以，在东方评论员看来，在联合国手下“干活”，华盛顿的“油水不会大”，因此，商人本色的华盛顿也就很难会有“持久的兴趣”。如此一来，在长期的救援过程中，华盛顿之前所承诺的诸多援助能否兑现，也就只能走一步看一步了，对此，起码东方评论员是持怀疑态度的。值得强调的是，东方评论员并不担心北京的承诺，在我们看来，直到目前为止，中国都在“真心实意”、“力所能及”这两把尺度上把握得非常好，这就为北京利用这次“单纯地救灾”，为日后促进中国与东盟国家建立更加信赖的政治、经济关系打下了坚实的基础。
  事实上，由于中国是在“真实实意”地，且也是在做“力所能及”的工作，因此，温家宝总理在第一个用自己的专机运去16吨救灾物资、表达北京救灾的诚意之后，又一次以“诚意”作为武器，呼吁各国、特别是那些承诺做这、承诺做那的国家也“拿出诚意来”，认真履行各自的援救承诺。事实上，对那些攻击中国“不诚心”的国家来说，这又何尝不是一种反击。在一段相关新闻之后，东方评论员将继续就各大国间的“海啸外交”、展开更深一步的讨论。


《东方时代环球时事解读》http://www.dongfangtime.com
