# -*- org -*-

# Time-stamp: <2011-08-02 19:30:30 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

#+STARTUP: indent

* 2005年01月11日 星期二

东方评论员注意到，在国台办主任陈云昨天上午，在与春节包机协商团会面中赞同国民党提出的包机三项意见，并宣布“正式启动”2005年春节包机业务之后，来大陆商谈春节包机的国民党立委曾永权、章孝严、朱凤芝和张荣恭等人，昨天深夜就已经搭机返回台北。

我们注意到，在机场面对记者的询问时，他们指出：与大陆方面商谈的两岸春节包机相关运作机制，已经正式定案，现在只希望台湾陆委会善意响应。显然，在大陆表示“可以可以”之后，共产党和这一拨还愿意支持“一中”的国民党人，就将球踢回了台湾，踢给了现在“脑子已经很大”的陈水扁。
 
下面，我们就先看看台湾陆委会的“善意响应”，之后，东方评论员将继续跟踪这个“前途未卜”的“春节包机”案。
  

** 台湾陆委会：冀大陆言而有信以台港模式协商包机

【台湾消息】据台湾媒体报道，台陆委会期盼大陆能言而有信，尽速以台港航权谈判模式协商春节包机事宜。陆委会主委吴钊燮在去年十一月曾对台港模式提出二十四字内涵说明，就是「搁置争议，不设前提，相互尊重，实事求是，政府主导，民间协助」。
 
所谓「台港航权谈判」，是指二○○二年台湾与香港谈判两地航运业日后飞行航线与航空公司班机规划。
 
这项历经七次谈判，在当年六月二十九日签订的协议，成为日后重要的谈判模式，主要在于这次谈判，虽是以民间业者为台面上的谈判主体，但在政府委托之下，实际主谈的都是台湾官员。
 
二○○二年六月二十九日晚间八时三十分，在陆委会企划处长詹志宏、交通部门民用航空局长张国政以公会顾问身分见证下，由香港方面授权的国泰航空国际事务处总经理彭立仁、港龙行政总裁许汉忠和华民航空国际事务顾问许勤业三名代表，与台湾政府授权的台北市航空运输商业同业公会理事长乐大信签署「有关台港之间空运安排」，自二○○二年七月一日起生效，为期五年。
 
当时陆委会主委蔡英文曾接受访问表示，那次台港航权谈判，是由政府授权主管官员，由詹志宏及张国政全权主导谈判进行，乐大信则只接受「委托」，在谈判桌上必须听从经授权官员的指示。
 
据指出，当时签订航约上，列有「依据指示签署」字样，表明台湾方面的代表签字，并非只是单纯以公会理事长身分签署，而是在台湾政府授权下所为，彰显政府介入的浓厚意涵。
 
就目前春节包机的协商进展，陆委会已注意到去年十月二十七日大陆国台办发言人张铭清认为，以台港模式进行包机谈判是属可行，陆委会希望大陆方面能够言而有信，以双方可以共同接受的方式立即展开务实协商。
 
不过，国民党籍立委章孝严指出，大陆方面所称台港模式「可行」，是指套用在「实现三通」上，春节包机与三通航权谈判性质不同，参照国际实务，包机不须经过政府谈判，因此，如果陆委会坚持以当年台港航权模式来谈春节包机，这样「可能会破局」。
 
国民党协商春节包机事宜的成员仍呼吁，政府应采取变通做法，大陆方面则须保留弹性，如此，才有可能实现今年两岸飞航春节包机。
 
 
 
【时事点评】在昨天的点评中，东方评论员曾经表示，对这次“春节包机”，两岸都似乎都在“自己在打着自家的算盘”，都希望通过双方都没有民议的“双向、对飞、不落地、多点开放”来实现自己的迥异的政治目标。
 
 
*** 双方明知是个“你得我失”的结果，却似乎都在“信心满满地”愿意陪对方玩一把

在我们看来，不论是谁主动挑起来的、或者谁是在被动应付，显然，在大陆和台湾“异口同声”表示“愿意为在大陆生活、工作的数十万台商提供尽可能的便利”之后，这场游戏就注定是个“零和”游戏，绝不可能出现“双赢”的结局。

有意思的是，大陆和台湾双方不可能看不到这一点，也就是说，为什么大陆和台湾都心里知道“在春节包机”这件事上，双方一定是个“你得我失”的结果，却似乎都在“信心满满地”愿意陪对方玩一把呢？
 

*** 都在认为自己能够从“春节包机”中得到自己想要的

显然，双方都在认为自己能够从“春节包机”中得到自己想要的，至少不会输得很惨。大陆想要的很清楚，一是展示自己的诚意，二是指望通过这次“春节包机”的协商过程，让国际社会，台湾各界能看清楚一个事实，那就是：在“92共识”的大原则下、北京愿意、也完全可以处理两岸的具体问题、开放三通，从而确保台海和平与稳定。至于陈水扁想要什么，今天我们就不多说了，请参见昨天的《环球时事解读》台湾部分。
 

*** 仅就“春节包机”这一事情本身而言，陈水扁当局就必输无疑

然而，首席评论员指出，其实这场游戏一开始，仅就“春节包机”这一事情本身而言，陈水扁当局就必输无疑，为什么？在我们看来，就因为陈水扁一开始就“心在不焉、心有旁骛”。

东方评论员认为，不论陈水扁愿意“玩这一把”、是有收人心、平怨气的心思也好，是着眼搞搞台湾日见边缘化的经济、为不久之后就要开始的台湾地方政府选举、准备一颗除“台独”之外的另一颗“票房大补丸”也罢，事实上，在我们看来，陈水扁最渴望的还是为了想借“春节包机”飞出一个“两岸已经恢复谈判”、“台海已经重新缓和”的假象。


*** 为防止陈水扁“浑水摸渔”，大陆早早就立下了“民间协商”的规则

我们认为，只要“春节包机”能飞出个“台海缓和、稳定”来，陈水扁就不仅可以既满足那个支持台独的总后台-美国的要求、以暂时配合华盛顿的中东战略，还可以在喊出了“台湾是主权国家”之后、得到一个“两岸已经恢复和谈”的现状。

然而，就如我们之前所说的那样，北京是“不会照顾”陈水扁这一愿望，为做到防止陈水扁“浑水摸渔”，制造“两岸官方恢复会谈、或者是在92精神下恢复和谈”的假象，大陆早早就立下了“民间协商”的规则，也就是说，这次“春节包机”根本就没有具有官方色彩的海协会、海基会的什么事。这也就是说，陈水扁想打造的“92会谈精神”根本就与这次“春节包机”的协商过程没有关系。
 
 
*** 陈水扁“假戏真做”地要大陆“言而有信”，决非是一时逞口舌之快

显然，对大陆与国民党来大陆的这拨人达成“协商方式”，陈水扁当局自然有非常不满的理由。我们注意到，台陆委会主委吴钊燮在这个时候又翻出那个“台港模式”，并还据此要求大陆“能言而有信”。事实上，用不着说去年的事，直到几个月前，国台办就明确说过“台港模式可行“这名话，然而，如果台湾方面不是别有用心的话，这种要求根本就无从提出，谁都清楚，“台港模式”是用于“两岸三通”的，和“春节包机”没有关系，大陆也从来没有说过“台港模式”能用于“春节包机”这一类的话。

所以，在东方评论员看来，陈水扁在大陆同意“春节包机”之后，又突然翻出“台港模式”，并还假戏真做地要大陆“言而有信”，决非是一时逞口舌之快，玩文字游戏，我们认为，陈水扁这种欲以“台港模式”这种大陆认为可以处理“两岸三通”问题的方式、来处理简单得多的“春节包机”，其意图就在于想在“春节包机”这场“台独”赢不了的游戏中尽可能地设置人为障碍，以达到另一种政治目的。
 
 
*** “台独”用心显然在于防止大陆借机将两岸局势导入“民间的各行各业、自己去谈两岸三通”的局面

首席评论员指出，不要忘记了大陆在“两岸三通”的问题上、是有前提的，那就是“一中原则”或者承认“92共识”。

非常清楚，同是一个“春节包机”，北京想要的是“两岸经济、民生上的具体问题”可以用“民间协商”方式来处理，台湾当局如不承认一中，那就“可有可无”，请靠边站，让有强烈“三通意愿”的民间力量来谈，然而，意图阻挠“两岸三通”的陈水扁，打的算盘却是，将“简单得多的春节包机”打造成“没有一中原则”的“两岸三通”之实例。显然，大陆在”517声明”中说得清清楚楚，不承认一中原则，不回到“92共识”，两岸官方不可能坐下来谈。

看得出来，陈水扁在这个时候想将“简单得多的春节包机”打造成“没有一中原则”的“两岸三通”之实例，其用心显然在于防止大陆借“春节包机”之例，扩大战果，日后将两岸局势导入“两岸民间的各行各业、自己去谈两岸三通”的局面。


*** 华盛顿是不会让“两岸三通”顺利实现的

然而，事实明摆着，只要陈水扁继续搞台独，只要华盛顿支持陈水扁继续搞台独，台海就没有和平、台海也没有稳定。因此，在美国的全球大战略下，其实“两岸 三通”的局面很难实现，在我们看来，别说陈水扁不愿意“开放三通”，东方评论员认为，就算陈水扁有这个心，华盛顿也不会让“两岸三通”顺利实现的，因为那样一来，不仅将极大地增强中国的经济实力，而且，华盛顿今后出于战略需要、就是想打“台独牌”也“只会变得困难、绝不会变得容易”。
 

*** “争取台湾人心”不过是一种绝对正确、但“操作性不佳”的“好政策”而已

事实上，我们也不认为北京相信几年内两岸能实现三通，但是，有些事情还是要做的，争取台湾人心是一方面，能争取多少就争取多少，但不要太作指望。坦率地讲，在陈水扁阻止“两岸 三通”的情况下，北京的声音台湾民众又有多少人能真正知道、能确实了解？

就如上面所说的“台港模式”，大陆明明是用于“两岸三通”的，可台独把持着台湾媒体，硬要说成是“大陆在言而无信”，由此可见，大陆目前所强调的争取台湾民心，在很大程度上不过是一种“操作性不佳”、却绝对正确的“好政策”而已！

可想而知，东方评论员并不认为北京在说寄希望于台湾人民的时候，心里也的确在这样想。
 

*** 北京真正能用来阻止台独的武器就只能是“以战争相威胁”

在东方评论员看来，既然争取民心不能寄与大的希望，那么，北京真正能用来阻止台独的武器就只能是武力了。如果在以前，“台独没有和平、分裂就没有稳定”靠的是北京“一而再、再而三”的口头警告、而让“台独”和支持“台独”的国际势力可以以“大陆是纸老虎”为理论和根据、也“一而再、再而三”地冲击所谓的“红线”的话，那么，在“反分裂国家法”划定“传说中的红线”、并以国家法律的形式、要求中央政府必须以包括武力在内的一切手段解决“任何台独重大事变”之后，将使得大陆由“纸老虎”彻底地变成“真老虎”。


*** 北京当“真老虎”的感觉还是不错的

首席评论员就指出，通过启动“反分裂法”立法进程，大陆一下子就变成了“真老虎”，在我们看来，至少从目前来看，北京当“真老虎”的感觉还是不错的，起码陈水扁硬着头皮也要玩这个“春节包机”就是一个活生生的例子。而且，北京不仅在“春节包机”问题上占尽便宜，还在施展出“反分裂法”这种近年来最严厉的“止独”手段、欲明确划出“红线”、并加以战争相威胁时，竟然还可以顺带做些“争取台湾民心”的“便宜事”，由此可见，这正应了一句老话，那就是“不使出霹雳手段、哪能见菩萨心肠！”

显然，正是这部仍然在拟定中的“反分裂国家法”、不仅让大陆变成了“真老虎”，也是迫使一心想在合适时机打出“台独牌”的华盛顿、不得不授意陈水扁同大陆“玩这一把的”“真正动力”之所在！
 

*** 台湾当局在同大陆玩这个难有胜算的游戏时、眼睛瞄着的是什么？

既然如此，大陆如何制定这部“神龙见首不见尾”的“反分裂国家法”、也当然就是台湾当局在同大陆玩这个“零和”、却难有胜算的游戏时、眼睛瞄着的、内心中最关注的问题。

在昨天的点评中，我们也这样说过，如果陈水扁这次最终同意按两岸各家航空公司、或者行业协会之间、用“纯商业的方式谈判”的方式、最终默认在“92共识”的大框架内来飞“春节包机”的话，那么，可以期望的是，北京的“反分裂立法”进程可能将会缓和一些。

在这里，我们想强调的是，我们所说的“缓和”指的是拟定“反分裂国家法”期间，可能“不容易”听到一些极其严厉“反台独”条款之“意向”出现在中国的官方媒体上、或者出自涉台部门的官员口中。

然而，有意思的是，就在我们做出这种预期的同时，陈水扁当局却迫不及待地透露出一些耸人听闻的消息，据引用者解释说，那就是“反分裂国家法”中的一些内容。

下面，我们就先看看陈水扁让手下又搞到什么秘密情报，之后，东方评论员将继续同一个话题。
 
 
《东方时代环球时事解读》http://www.dongfangtime.com
 

** 台陆委会透露：已经知道“反分裂法”将打击台商

【台湾消息】据台湾媒体报道，昨天岛内媒体引用陆委会主委吴钊燮的说法，认为大陆的反分裂法将会设立特别法庭惩处台独，甚至大陆台商与到海外旅行的台湾人都会遭殃。
 
今天台媒体记者追问陆委会副主委邱太三，这项情资是如何获得，但邱太三不愿回答，而记者追问刚与邱太三会晤的台联立委，陆委会是否已经确定反分裂法将会有类似条文？立委说，邱太三并未明讲。
 
邱太三应台联党团邀请，前来报告对于两岸春节包机与大陆反分裂法的因应之道。
 
不过对于反分裂法的内容，是否将把民进党与台联党员，以及在政府工作者都视为台独人士，甚至是否将威胁到未来到大陆经商的台商，和前往非邦交国旅行的岛内人士？陆委会是如何掌握到这项情资？邱太三对此什么都不讲。
 
而台联立委则声称，反分裂法等于是认为只有一个中华人民共和国，“已经是改变现状的行为”，而威胁台商与出岛观光人士的条款，根本是“违背人权”。至于记者追问陆委会如何得知反分裂法将有类似条款？立委说这是根据部分中国大陆学者提出的主张，至于邱太三是否说，陆委会判断类似主张将纳入立法？党团总召黄宗源坦承：他并没有明讲中国一定这么做。
 
 

【时事点评】首先，这条新闻的标题就够吓人的，不过、在东方评论员看来，对那些稍具一点“政治感觉”的人士而言，恐怕在第一时间内就会确认：这肯定是条“假新闻”。
 其实，说起假新闻，今天还有那么一条，那就是海外媒体纷纷在今天的显著位置抢发一条“不大也不小”的新闻，说什么“赵紫阳已经不在人世”了，然而，来自中国的官方消息则斥之为“纯属不实报导”，并称赵紫阳身体尚好！
 

*** 陈水扁却让自己的陆委会主委吴钊燮抛出这条“吓人”的消息，其居心何在？

事实上，对媒体不经查证就抢新闻、拼消息，东方评论员在这里无意多说什么，因为上述新闻虽然“不实”，但更多地不过是对一位前中国领导人的关心而已，尽管这种关心也夹杂着点点滴滴、各种各样的目的与动机。

然而，对陈水扁当局在这个时候、在两岸都在“比比谁更有诚意地给在大陆的台商提供方便”、在两岸“民间代表”都在热烈地商议着如何让“春节包机”穿梭于海峡两岸的时候，陈水扁却让自己的陆委会主委吴钊燮抛出这条“吓人”的消息，其居心何在？其愿意促成“春节包机”、方便台商的诚意又何在？
 

*** 这条吴钊燮故作神秘“骇人新闻”、似乎东方评论员早在半年前就看到过

东方评论员注意到，按吴钊燮的说法，他认为“大陆的反分裂法将会设立特别法庭惩处台独，甚至大陆台商与到海外旅行的台湾人都会遭殃”。

直到目前为止，我们从来没有看到任何有关“反分裂法”立法内容的“可靠消息”，至于对这条“骇人新闻”、这条吴钊燮故作神秘“不肯透露”消息来源、在引用之余还偏偏做出一副欲保护消息来源的“重大新闻”、似乎东方评论员早在半年前就看到过。

在我们看来，设立特别法庭、惩处搞“台独”、企图分裂国家的重要人物是当然之举，就这种“几乎肯定会有”的东西、还用得着“消息来源”吗？还用得着故意做出一副“欲说还休”、“不肯透露”的样子吗？
 
 
*** 吴钊燮的说法，就是要有意将“台独”与“台商”之间强行画等号！

显然，陈水扁在这个“台商”都希望能从大陆“直接飞回老家过年”的时候，掂出这份“不是新闻的新闻”、还精心加以重新包装，当然是有其政治目的的。

在东方评论员看来，按吴钊燮的说法，其意图非常清楚，就是要有意将“台独”与“台商”之间强行画等号！
 
 
*** 倒是“戴绿帽子”、死心塌地支持台独的“绿色台商”可能会被“这几句话”吓着

众所周知，不久前，大陆还发动了一场专门打击“绿色台商”的运动，显然，明眼人一看“绿色台商”这几个字就会明白，大陆一早就将拥护统一的台商、一心赚钱的台商、与那些在大陆赚钱、却死心塌支持台独的“绿色台商”区分开来。

很清楚，在东方评论员看来，对那些拥护统一的台商、或者是一心赚钱的台商，在上一轮的打击“绿色台商”的“运动”中、他们受过冲击吗？他们有必要害怕”反分裂法”吗？

倒是那些“戴绿帽子”的、死心塌地支持台独的“绿色台商”要当心了，如果今后还要搞台独，如果触犯犯了“反分裂法”，特别法庭（如果到时是这样称呼的话）当然会把他请去“过堂”，依法判罪！

说到这里，东方评论员觉得还得提一点，那就是，对那些拥护统一的台商、一心赚钱的台商、陈水扁抛出的这条吓人的消息很难起作用，因为大家心里都明镜似的，“白天不做亏心事，半夜不怕听敲门”，倒是那些与陈水扁、李登辉这些台独首要分子串通一气、死心塌支持台独的“绿色台商”可能会被“这几句话”吓着，为什么？
 
 
*** 中国政府向来主张的“严惩首犯，不问协从”

很简单，尽管陈水扁让他的陆委会主委吴钊燮在抛出这条“吓人”消息的同时，不怀好意地将“几种台商”混在一起，心怀叵测地将“一般台湾民众”与搞台独的“首恶分子、重要人物”不加区分，但是，人们仍然会看得清清楚，那就是，吴钊燮所说的、“大陆台商与到海外旅行的台湾人都会遭殃”这句话、绝对应该是“继续搞台独、并触犯《反分裂国家法》的台商与到海外旅行的台湾人都会遭殃”。

在东方评论员看来，加上“继续搞台独、并触犯《反分裂国家法》”这个前提之后，一旦台海战争被“台独”分子挑起，就非常符合中国政府向来主张的“严惩首犯，不问协从”之“惩治战犯”的原则。


*** 陈水扁仍然在想办法“做点什么”

上面说了这么多，无非就想说明一点，那就是，陈水扁在这个时候、在台商们都在想着直接飞回老家过年的时候，却借机拿着那部专门针对他与李登辉、陈唐山这一类死心塌地“台独”分子的“反分裂法”、转而去威胁、恐吓台商，一方面充分暴露其“乐见事成”的虚伪，另一方面也充分暴露了陈水扁在硬着头皮、眼睁睁地看着国民党出风头、看着共产党以实际行动向各方显示自己的和平诚意、展示中国政府真正愿意兑现“只要有利于台胞的事情我们都会尽力去做”之诺言的同时，仍然心有不甘，仍然没有忘记那部让美国和“台独”如梗在喉的“反分裂国家法”、仍然在想办法试图在干扰“反分裂法”方面做点什么。

之前，我们说过，陈水扁是一定会反抗的，今天，在陈水扁让陆委会主委吴钊燮抛出这条“吓唬台胞”的消息的同时，他还放出了另一位“台独”干将，通过另一种方式表达着“台独”的决心，下面，我们就看看此人是谁，他又说了些什么！
 
 
 
《东方时代环球时事解读》http://www.dongfangtime.com
