# -*- org -*-

# Time-stamp: <2011-08-02 21:01:50 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

#+STARTUP: indent

* 05年5月09日 星期一

** 台湾《联合报》：大陆官方通令，媒体不可提“搭桥之旅”

【台湾消息】据台湾媒体报道，亲民党主席宋楚瑜到大陆四天，大陆官方开始改变宣传策略，通令不可提“搭桥之旅”，对宋楚瑜个人情况不要多所着墨。报道方式也采取了一些防范措施。

据台湾《联合报》报道，大陆方面考虑宋楚瑜即兴演说时会出现“不合时宜”的政治用词，原先中央电视台第四频道对宋楚瑜每项行程的现场实况转播，从前天起改为先播一个头，宋楚瑜讲话预录证实没有问题后再播出全部。

亲民党秘书长秦金生昨天上午指出，中共官方限缩大陆媒体报道宋楚瑜大陆行的降温动作，主要是在意他在公开演说中一再提及“中华民国”。

他认为，这不会对宋楚瑜的“搭桥之旅”造成太多的障碍。

《联合报》报道指出，宋楚瑜在陕西机场表态“反台独、反一中一台、反两个中国”后，民进党中央在台北提高批宋力度，而陈水扁总统前天晚间反驳宋楚瑜的“台独非选项”说，更让北京谨慎观察外界对宋此行的反应。

此前，陈水扁点名要宋传话，却又否认九二共识和宪法一中，早已使得宋楚瑜此行处境格外艰难。

秦金生昨日说，九二共识，是创造性模糊，扁宋十点共识，则是异中求同，宋楚瑜坚持反台独，强调台独会带来战争，陈水扁则认为台独是选项，是台湾民主多元声音的一种，两者认知或有不同，但都无损“扁宋十点共识”以中华民国为最大公约数的基础。

由于12日宋楚瑜与胡锦涛总书记会晤，双方在政治议题会达成什么共识尚未确定，在此情况下，中共官方不愿媒体在“搭桥之旅”上作文章，以免误导大陆民众。

此外，宋楚瑜离开国民党自创亲民党，与国民党有些恩怨纠葛，北京也不希望混乱大陆民众的印象，通令大陆媒体少在这方面作文章。

宋楚瑜核心幕僚张显耀昨日澄清说，宋楚瑜早已对“搭桥之旅”四字说明含义，是要“为两岸搭起互信之桥、合作之桥与沟通之桥”。

他说，台湾一些媒体认为宋楚瑜是为了胡扁会铺路，但宋楚瑜早已表明，此行仅以亲民党主席身份访问，不代表任何人。

“如果清楚宋楚瑜定位，就会知道（宋为“胡扁会”铺路）是不可能的，这种揣测是过度的解读。”

张显耀进一步指出，陈水扁并没有说过要宋帮他促成“胡扁会”，而北京方面也没有这个意思。胡扁若要会面，并不是有没有宋楚瑜搭桥的问题，而是（陈水扁）的立场问题。因为九二共识是两岸复谈的基础。

台湾媒体分析说，宋楚瑜日前在陕西祭皇帝陵，提到“中华民国”四字，央视当时立即切断画面。因为宋被视为代表扁，而扁定义的中华民国仅限台澎金马，是一边一国架构，不是领土涵盖大陆的宪法中华民国。

前天宋祭拜中山陵，央视虽然直播祭文宣读的画面，但现场的声音却是遭到消音的，以主播台主持人与来宾的对谈取代。




【时事点评】在东方评论员看来，继连战在“胡连会”后、揣着“联合新闻公报”和“三项大礼”、满载而归之后，失去“头彩”的宋楚瑜是否能在“胡宋会”中扮演好“合适的角色”，完成这次大陆之行的“压轴戏”，就成了世界的焦点。

*** “胡连会”达成的“五点愿景”可以说是达成了两个目的

事实上，大陆通过“胡连会”达成的“五点愿景”可以说是达成了两个目的，首先，“五点愿景”除了第五条说的是纯属“国共两党”的事情、拟建立一个“定期交流平台”以外，在其余的“四条”前面，我们都可以非常清楚地看到“促进”这两个字。

显然，在东方评论员看来，这“促进”的对象可就多了，表面上当然就是陈水扁和民进党的“台独路线”，其次则是躲在其后的华盛顿东亚战略和它的“对台政策”，然而，我们只要看看宋楚瑜在临行前的“一番调整”，就不难深刻地感受到，就眼前而言，首当其冲的“被促进者”就是这个“善于变色”的宋楚瑜和他的亲民党。

*** 连战“将牌打尽”，陈水扁和宋楚瑜都遇到了难题

大家应该还记得，连战还在大陆访问时，由于连战和国民党公开地、以“联合新闻公报”这种“白纸黑字”的方式、不仅承认12年前、两岸“的确有”“九二共识”这一层、也公开表明国民党现在的“反对台独”的立场，最后还在“字里行间”处处强调“两岸全面三通”的可能性与紧迫性。

显然，就如我们之前所说的那样，连战这是将宋楚瑜、陈水扁原来准备拿来、以及可以拿来与大陆“讨价还价”的筹码，一把就“抢先给用尽”了。

不难看到，面对连战“将牌打尽”，陈水扁和宋楚瑜都遇到了难题。其中，陈水扁将如何调整我们先暂不说，单就是宋楚瑜，非常清楚，他为了这趟大陆之行不至于“空口白牙”，不得不在最后成行前、再次让他的高级幕僚再往北京一趟，以商量“话题”。


*** 宋楚瑜是“人”“已经登陆”，而“心”仍然“留了一半”在台湾

在之前的点评中，我们曾经对此提出过这么个观点，那就是，如果宋楚瑜不能在与胡锦涛“正式面谈”之前的几天里，就“九二共识”这一问题与陈水扁“达成默契”、从而直接由宋楚瑜在北京用“九二共识”将“扁宋会”搞的“十点共识”中的基础---“宪法一中”给抽换出来的话，我们认为，宋楚瑜的高级幕僚就是住在北京“不走了”，恐怕也“商量不出”一个什么“两全其美的好办法”来。

现在，宋楚瑜“人”是“已经整个的登陆”，而“心”仍然“留了一半”在了台湾。东方评论员认为，从宋楚瑜在行程中的种种表现来看，显然，与连战和国民党访问团完全不顾及“十点共识”、所做的“背水一战”显然不同的是，他与他的亲民党直到今天为止，仍然没有能够走出“十点共识”的阴影。


*** 无法走出“十点共识”的阴影，就在于宋楚瑜“处境尴尬”

在我们看来，宋楚瑜之所以无法走出“十点共识”的阴影，就在于其“处境尴尬”，而这种“尴尬”又是宋楚瑜“投机取巧”的“政客心态”自己酿造的。

东方评论员认为，宋楚瑜的“尴尬”可以说主要表现在两个方面：第一，不论是“扁宋会”，还是因此而“产出”的“十点共识”，本质上都是源于宋楚瑜的骑墙心理、和一个倾力于中东、而急于稳定台海、朝鲜局势、企图“以和待变”的华盛顿“一拍两和”而产下的一个“怪胎”；

也是宋楚瑜、亲民党在去年年底立法选举惨败后、想通过打“大陆牌”重新搭建一个“比现在更大的政治舞台”之投机心理驱动下、与迫于来自华盛顿外部政治压力、和台湾经济日益边缘化的内部压力、而急于缓和两岸紧张气氛的陈水扁政府“一拍两和”而产下的一个怪胎。

*** 在精心拨打算自己的算盘珠子的时候、宋楚瑜显然“做错了什么”

东方评论员认为，如果仅从“打大陆牌”的角度来看，宋楚瑜的这个算盘还算是打得不错的。然而，事情搞成今天这步模样，非常清楚、宋楚瑜在精心拨打算自己的算盘珠子的时候、显然“又做错了什么”。

在我们看来，宋楚瑜错就错在错判了大陆通过“反分裂国家法”之后的国际形势、更错判了大陆在维持东亚战略格局中的重要作用，从而一头倒在了华盛顿的怀里、去急急忙忙的参加华盛顿一手导演的“扁宋会”。

*** “一步错、是步步错”

结果是，“一步错、是步步错”。由于北京的拒绝，他不仅“不能抢得头彩”、头一个实践自己提出的“登陆”“创意”，反落得个如此尴尬的境地，即：在连战已经将宋楚瑜和陈水扁“所有可以拿得上台面”、去与大陆讨价还价的筹码一一耗尽的情况下，他要么靠得华盛顿更近点，那就得被迫“更加尽职地”扮演陈水扁“代言人”的身份、去把“扁宋会”的结果--“十点共识”揣到北京来，想千方百计在“胡四点”与“十点共识”之间“搭桥铺路”；



要么，就是学被华盛顿抛弃、而不得不“豁出去了的”连战、果断地离华盛顿“再远一点”，拿出当年他标榜自己“比台独还要台独”的劲头来，这次用实际行动去证明“他比连战还要连战”、从而重新与陈水扁划清界线，然而，如此一来，这就需要宋楚瑜也拿出魄力来，他要想超越连战，就必须“有别于”连战。

不然，宋楚瑜就算与陈水扁划清了界线，也许可以走出陈水扁、“十点共识”的阴影、但却很容易“又回到”正在大放光彩的连战的阴影里，就和当初的“连宋配”搞选举时一个样。


我们认为，失去先机的宋楚瑜，最“尴尬”的地方倒不是他想选择什么角色，在我们看来，善变的他、只要有可能达成在台湾政坛上继续玩下去的政治目的，是不会在乎什么“独”与“统”、“蓝”与“绿”的。



*** 宋楚瑜“最为尴尬之处”


因此，在首席评论员看来，在“独”、“统”、“中间路线”，或者在“蓝”“绿”“橘”“三色”中跳来跳去、都不足以让其尴尬，而就是那种“进退维谷”、“什么都想要”、又“什么都怕得不到”、才是宋楚瑜“最为尴尬之处”。

东方评论员认为，不得已被排在连战后面登陆的宋楚瑜，在目睹所有现在看得见、摸得着的好处、大礼都被连战用“九二共识”、“反对台独”“这只网”给一网打尽之后，现在似乎不太容易想出一个什么“好办法”、为陈水扁、更是为他在“胡四点”与“十点共识”之间“搭建桥梁”，也不太容易找到一个“好办法”在大陆和台湾社会面前去证明“他可以比连战还要连战”了。

很清楚，已经“失去先机”的宋楚瑜，直到今天仍然是“丢不下”那个赋予他“些许”台湾“官方色”、“公权力”的、以“宪法一中”为掩饰的“十点共识”，以在大陆眼里保持一种“与连战身份不一样”的“格调”，用“十点共识”为自己和亲民党谋取更大的政治利益，这就表现在宋楚瑜在这几天里、是走到哪就将那个代表“宪法一中”、而领土范围都已经遭到陈水扁与“十点共识”同时抛出的“三段论”“修改了的”“中华民国”唱到哪里。


*** “鱼和熊掌”欲兼得的心理在作祟

而另一方面，东方评论员又注意到，宋楚瑜在抵达西安后，在陕西机场表态“反台独、反一中一台、反两个中国”，并也口头承认“九二共识”，却又在那里大谈“中华民国”、通过强调“第一条”去为“十点共识”的“做广告”，一来探探大陆对他的“搭桥之旅”的口气如何，二来也是让华盛顿、陈水扁“有所放心”，对宋楚瑜这一套“滴水不漏”的做法，东方评论员的观点是，这根本就是“鱼和熊掌”“欲兼得”的心理在作祟。


东方评论员注意到，亲民党秘书长秦金生所说的“九二共识，是创造性模糊，扁宋十点共识，则是异中求同”，则是宋楚瑜、亲民党这种“什么都想要”的心态的最好注脚。

*** 宋楚瑜必需明白，他是“不可能”让大陆和华盛顿、陈水扁“同时满意”的

在目睹了宋楚瑜在大陆的既要“十点共识”、也要“九二共识”的“投机心态”，显然，“鱼和熊掌”欲兼得的宋楚瑜，必需明白一点，那就是，不论他怎么“投机”，是“绝不可能”让大陆和华盛顿、陈水扁“同时满意”的。

在我们看来，既然宋楚瑜仍然心存幻想，“舍不得”那个给他披上“官方色彩”的“十点共识”、又想通过这次”搭桥之旅”、通过“承认”“已经被连战确认”的“九二共识”、在“胡四点”与“十点共识”间“牵线搭桥”、从而取得“比率先承认九二共识的连战还要出色的访问成果”，首先在大陆这里就“过不去”。


*** 大陆对“搭桥之旅”这几个字“表现出想法”是理所当然的

在之前的点评中，我们已经分析过，宋楚瑜所谡的“搭桥”，就是想在“胡四点”与“扁宋十点共识”之间“穿针引线”、“扮演桥梁”的角色。在宋楚瑜“不是陈水扁特使”的“保证”下，在国民党已经先行登陆的情况下、如何利用宋楚瑜、迫使“十点共识”在已经承认“宪法一中”的基础上、如何“再进步一步”，去符合“胡四点”中要求的“一个中国”、“九二共识”，大概就是大陆邀请“已经符合登陆标准”的宋楚瑜、做此“搭桥之旅”的本意了。

然而，宋楚瑜在西安一落地，就立刻做起了“十点共识”的“广告”，这种探探大陆对他的“搭桥之旅”的口气如何做法，大陆当然要做出强烈反应。

我们注意到，上面这篇新闻稿强调说：中共官方不愿宋楚瑜通过媒体在“搭桥之旅”上作文章，以免误导大陆民众。在我们看来，由于12日宋楚瑜与胡锦涛总书记会晤，双方在政治议题“会达成什么共识”尚未确定的情况下，一连几天的访问、仍然没有让宋楚瑜、亲民党形成一个“明显倾向的政治立场”之前，大陆对“搭桥之旅”这几个字“表现出想法”是理所当然的。

*** 也是全面刺激宋楚瑜“胆子更大点”的必然一手

其次，东方评论员也认为，大陆对“搭桥之旅”“表现出想法”的意图有二：一是给宋楚瑜以教训、断其“鱼和熊掌”欲兼得的幻想，二也是在继续利用连战在“豁出去之后”取得的“空前成功”、去全面刺激宋楚瑜也“胆子更大点”、本身就是“下好连宋这两步棋”的必然一手。


有意思的是，就在大陆给宋楚瑜脸色看的同时，隔着海峡“紧盯形势”的陈水扁也赶紧跑了出来“要说两句”，在我们继续讨论这个话题前，我们就先来看看陈水扁说了些什么，之后，东方评论员将继续这个话题。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 陈水扁狠批连宋登陆言行

【台湾消息】据中央社台北8日报道：陈水扁8日接受电视台专访时，抨击连战、宋楚瑜在大陆时的言行。

不接受胡连会新闻公报

　对于国民党主席连战访大陆提及「联共制台独」，陈水扁说，「中国没有民主的选举、不可能政党轮替、军队没有国家化、没有新闻自由、没有宗教自由，所以连战的『联共制台独』说，是他中国之行『非常大的败笔』，绝多数的两千三百万人民不能接受。」

　陈表示，「去中国要让人鼓掌很简单，就说他们爱听的话，说所谓的大中国民族主义即可。有人说『中国热』，但为何不利用所谓『中国热』，也来个『台湾热』。」

　陈水扁又表示，没有任何一条法律禁止国民党主席连战访问大陆。他说，纵然他不赞成连战访问部分谈话，但这是个人言论自由，政府不能因为这样把连战抓起来；这无关颜色，也非软弱与否的问题，任何人坐到他这个位子都一样。谈到连胡会新闻公报，陈水扁说，「连胡会新闻公报是披着新闻公报外衣的新闻稿，是会谈纪要，不过，部分内容，政府不同意也不能接受。」

指宋楚瑜言论互相矛盾

　对于亲民党主席宋楚瑜在大陆提出反对两国论、两个中国的言论，陈水扁表示，「如果亲民党主席宋楚瑜反对两国论、两个中国，又要说『九二共识、一中各表』，两者相互矛盾；如果中华民国是一个国家，难道和中华人民共和国一样？两者可以划上等号吗？」

　陈说，他曾向宋楚瑜表示，「希望宋楚瑜跟中国说扁宋十点共识第一点」，「中华民国主权现状，要受到两岸与国际社会承认与尊重」，他要看宋楚瑜有没有推动落实，「有没有跟中国说」。
　
　宋楚瑜提到台独不是选项，陈表示，「扁宋十点共识的第六点，『台湾前途由两千三百万人民决定』；不能只说『中国统一』是唯一选项，别人对未来有不同思考，就变成不是选项，这是不尊重两千三百万人民自由选择的权利，和扁宋十点共识有出入。」

　谈到「九二共识」，陈水扁说，「九二共识根本不存在，中国主张的九二共识是一个中国原则；希望中国领导人胡锦涛来台湾，他会陪胡锦涛到海基会看看到底有没有九二共识，如果没有，以后就不要再说有九二共识。」




【时事点评】陈水扁说连战的“联共制台独”说，是连战中国之行“非常大的败笔”的说法“有点意思”，可问题是，如果真如他所说，是“绝多数的两千三百万人民不能接受”的话，那么，别的不说，起码那个“最善于变色”的宋楚瑜是决不敢去“紧赶慢赶”展开“搭桥这旅”的。

事实正相反，连宋相继访问大陆，两岸关系不断升温。岛内泛蓝的民意支持迅速飙升，而泛绿则大幅下跌，在这种情况下，这位“绿营头目”却偏要“掩耳盗铃”、有意思去说什么风凉话，也算是让人叹为观止了。

*** 陈水扁“部分拒绝”的本质就在于“不反对”“两岸之间的这种交流模式”

我们注意到，在谈到连胡会新闻公报时，陈水扁说，“连胡会新闻公报是披着新闻公报外衣的新闻稿，是会谈纪要，不过，部分内容，政府不同意也不能接受。”显然，陈水扁拒绝的是“部分内容”、而不是“新闻公报的全部”，显然，“部分拒绝”的本质就在于“不反对”“两岸之间的这种交流模式”，这就为华盛顿与陈水扁都急需的、宋楚瑜的“搭桥之旅”提供了“一定的空间”。

*** 对宋楚瑜的“投机性格”，陈水扁在提前“打预防针”

然而，陈水扁在“字里行间”，又一次让东方评论员捕捉到了“他深深地不安”，我们注意到，陈水扁说，他曾向宋楚瑜表示，“希望宋楚瑜跟中国说扁宋十点共识第一点”。

众所周知，这个“第一点”就是“宪法一中”。而陈水扁还说，“中华民国主权现状，要受到两岸与国际社会承认与尊重”，他要看宋楚瑜有没有推动落实，“有没有跟中国说”。

不难看出，对宋楚瑜能否在最后关头、将“十点共识”带到“胡宋会”中去、呆在台湾的陈水扁、似乎没有了“十足的信心”。显然，陈水扁在这个时候跑出来、以“如果亲民党主席宋楚瑜反对两国论、两个中国，又要说'九二共识、一中各表'，两者相互矛盾”来指责宋楚瑜“两者相互矛盾”、也是在对宋楚瑜的“投机性格”提前“打预防针”，担心宋楚瑜在最后关头、在大陆的压力下抛弃“十点共识”。

*** 亲民党高层“刻意去强调这一原因”、其意图就有点耐人寻味

事实上，在东方评论员看来，大陆限缩媒体报道宋楚瑜大陆行的降温动作、“并非”象亲民党秘书长秦金生昨天上午所指出的，主要是在意他在公开演说中一再提及、陈水扁所强调的“第一点”--“中华民国”，只是亲民党高层在陈水扁“非常紧张”的敏感时候、去“刻意去强调这一原因”、其意图就有点耐人寻味了：明眼人一看便知，这分明是在向方方面面“大声感叹”大陆“态度强硬、并还在加压”。


*** 宋楚瑜何以悄悄更换这次大陆行的“广告词”？

根据我们的观察，大陆对“搭桥之旅”这几个字“有想法”的最初迹象，是在宋楚瑜眼见连战将所有的好处都一网打尽、满载而归之后，担心自己的“大陆行”如同鸡肋、遂派其核心幕僚张显耀于宋楚瑜启程前往北京、与大陆“商量”没有具体结果之后，才表现出来的。

在东方评论员看来，宋楚瑜已将这次大陆行的“广告词”、由“搭桥之旅”悄悄地换成了“工作之旅”就是最好的明证。台湾有消息透露说，宋楚瑜在“九二共识”的问题上，行前与陈水扁“暂未达成共识”。

如果是这样，宋楚瑜将“搭桥之旅”悄悄地换成了“工作之旅”，一来是迫于大陆的压力、二来本身也是他在向陈水扁“叫牌”，要求陈水扁“不反对”他用“九二共识”去替代“十点共识”的“第一条”，做为他将“十点共识”带到“胡宋会”中去的“敲门砖”、从而实现他想以“官方色彩”去“有别于连战”、继而超越连战、重抢“登陆计划”之“头功”、将自己置于“两岸和谈”的“事实推动者”的高度。

*** 大陆“这几天”台湾事务的工作重点

这就是说，在“九二共识”已经成了连战的功劳之后，不论宋楚瑜在之后的“胡宋会”中是口头承认也好，是学着连战也出个“联合新闻公报”“白纸黑字”加以确认一番也罢，本质上都没有“太大的突破”，对大陆而言，如果宋楚瑜此番前来只是在炒连战的“剩饭”，那意义就不大，充其量不过是“锦上添花”而已。

在我们看来，通过“胡连会”，大陆在从连战这里拿到了“九二共识”的“确认件”之后，如果通过压急于建功立业的宋楚瑜、去迫使对“两岸和平”寄予期待的陈水扁尽快在“九二共识”的问题上“表态承认”、从而启动“两岸三通”谈判，当然是最好的结果。

然而，如果陈水扁继续在“九二共识”的问题上、顾及“台独”势力的压力而不肯后退的话，那么，在宋楚瑜“鱼和熊掌”欲兼得、而不能得兼的现实下，如何“力压”宋楚瑜彻底抛弃“十点共识”，将“胡宋会”的对话焦点放在“两岸如何全面三通”、而非在“胡四点”和“十点共识”这两个“在前提条件上就原则对立的”问题上去空费口舌、就成了“这几天”的工作重点，显然，大陆的策略就是“以后一种可能性”为主打方向，从而掏空陈水扁的最后防线，去侧击“台独”势力的反扑。

*** 大陆促进宋楚瑜“胆子更大点”是有可能的

我们注意到，亲民党大陆访问团上午前往中山陵谒灵时，并没有比照在西安祭黄帝陵模式，念出祭文的“中华民国”字眼，而宋楚瑜在祭文中写着“三民主义千秋万世、一统中国全民共享”，就有大陆官方媒体解读，连战没有提到的中国统一，宋楚瑜换个方式包装提出来了。

显然，从宋楚瑜的“这点变化”不难看出，大陆促进宋楚瑜“胆子更大点”是有可能的。然而，对宋楚瑜的“这点变化”，陈水扁自然也就“坐不住了”。

*** 如果不想被大陆“给剥了个精光”、陈水扁根本就没有太多的选择

不难想像，如果大陆成功地让宋楚瑜同意在“胡宋会”中、将双方对话焦点放在“两岸如何全面三通”上，如此一来，在“九二共识”已经不是“胡宋会”的问题之后，如果能在“两岸应该如何三通”的问题上达成共识，那就“活生生”的是在谈“胡四点”了，哪里还有“十点共识”的什么事？

当然，台湾问题不可能不考虑华盛顿的影响，然而，华盛顿在这个时候想得问题也太多了，什么伊朗核问题、朝核问题这两天“都恰到好处地”“消息不断”，而在这些方面，华盛顿又不能不考虑北京的影响，因此，在华盛顿一心想尽快得到那份名义上可以保证台海几十年和平的“中程协议”之的全盘计划下，“十点共识”远不是问题的全部。

而对于陈水扁，则不然，一旦事态发展到果真没有了“十点共识”以“遮羞”，却又得承认“九二共识”，可以说，陈水扁也就被大陆“给剥了个精光”。

因此，在“连宋相继登陆”之后，尽管陈水扁遭受台独势力的极大压力，然而，明白不能拂华盛顿之意愿的陈水扁，如果不想被大陆“给剥了个精光”、事实上，根本就没有太多的选择。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

就在台湾问题错综复杂的同时，朝核问题问题也是一日三变，有消息说日本又在老调重谈，翻出了“朝核问题最后期限说”，不难看出，华盛顿在台湾问题仍然没有实质性结果之前，对自己所做的、所谓“促进台海和平”的一系列动作、索取回报的劲头是愈加按捺不住。

下面，我们先来了解这段新闻，之后，东方评论员将把点评的焦点放在朝鲜半岛方面，并继续今天的东亚部分。
