# -*- org -*-

# Time-stamp: <2011-08-04 12:56:28 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 2005年8月18日 星期四



** 中俄“联合军演”开始，两军总参谋长声明：“不针对第三方”


【符拉迪沃斯托克８月１８日电】中国人民解放军总参谋长梁光烈上将和俄罗斯联邦武装力量总参谋长巴卢耶夫斯基大将１８日表示，“和平使命－２００５”中俄联合军事演习不针对第三方，不涉及第三国利益，不对任何国家构成威胁。
　　
　　当地时间１８日１２时（北京时间１８日９时），梁光烈和巴卢耶夫斯基在会见记者时指出，此次演习旨在深化中俄互信，增进彼此友谊，促进交流合作，提高两军应对新挑战、新威胁的能力。
　　
　　两军参谋长１１时（北京时间８时）共同宣布演习开始后，在位于符拉迪沃斯托克的俄罗斯太平洋舰队礼堂会见了记者。
　　
　　梁光烈说，此次中俄联合军事演习主要演练战略磋商与战役筹划、兵力投送与展开、实施交战三个训练问题。演习跨越两国陆、海、空域，参演军兵种齐全，演练科目较多。
　　
　　巴卢耶夫斯基说，中俄举行联合军事演习绝不意味着两个大国想要建立什么军事集团，也不会对其他国家的利益构成威胁。
　　
　　会见记者前，两国总参谋长签发了中俄联合军演战役训令。会见后，梁光烈向俄罗斯“太平洋舰队战斗荣誉纪念碑”敬献了花圈。


中俄联合军演两军总参谋长战略磋商在俄举行


梁光烈说，当前，国际和地区局势复杂多变。中俄加强战略协作，有利于双方共同应对新威胁和新挑战。上海合作组织是中、俄及中亚国家在本地区倡导和树立新安全观，建构新型区域合作模式的成功实践。中俄作为上海合作组织的重要成员，应该重视发挥上海合作组织机制的作用，采取切实措施，同其他成员国一道，积极推动组织框架内的防务安全合作，共同维护本地区的安全与稳定，促进地区发展与繁荣。

巴卢耶夫斯基说，俄罗斯与中国在广泛的国际和地区性事务中，有着相似或相同的看法。两国之间的友好合作有着深厚的历史基础，潜力巨大。进一步巩固俄中战略协作关系，扩大和加深各个领域的互利合作，不断丰富其内涵，提高双边协作的质量和水平，符合两国和两国人民的根本利益，有助于保持地区和全世界的和平与稳定。

中俄两军总参谋长指出，举行联合军事演习，是中俄两国领导人着眼国际形势的发展变化，为深化两国战略协作伙伴关系做出的重大战略决策，有利于进一步充实两国战略协作伙伴关系的内容，充分展示中俄战略协作伙伴关系的新进展，也有利于增进两国在军事和安全领域的互信，加强两军在军事训练领域的合作，提高两军应对新挑战、新威胁的能力，对共同维护地区安全、促进世界和平，具有十分重要的现实意义和深远的历史影响。此次联合军事演习，不针对第三国及其利益。

中国人民解放军副总参谋长、中俄联合军事演习导演部中方总导演葛振峰上将，俄罗斯国防部作战组组长、陆军副总司令、中俄联合军事演习导演部俄方总导演莫尔坚斯科伊上将向两军总参谋长报告了“和平使命－２００５”中俄联合军事演习的准备情况。随后双方总导演向参演部队下达演练课目、明确演练目的、提出演练要求。导演部双方参谋长向参演部队介绍初始态势、宣布作战时间。战役指挥部依据导演部意图，展开第一阶段的演练。第二、三阶段的演练将在中国山东半岛及其附近海域进行。

中国人民解放军总参谋长助理、中俄联合军事演习导演部中方参谋长章沁生少将，济南军区司令员、中俄联合军事演习联合战役指挥部指挥员范长龙中将，济南军区政治委员、中俄联合军事演习联合战役指挥部指挥员刘冬冬上将，俄罗斯太平洋舰队司令费奥多罗夫海军上将，参加了战略磋商。

梁光烈一行还参加了巴卢耶夫斯基举行的欢迎宴会。梁光烈等是当地时间１７日下午抵达符拉迪沃斯托克的。






【时事点评】今天，在俄罗斯符拉迪沃斯托克，“和平使命―2005”中俄联合军事演习终于在这里拉开了帷幕。在东方评论员看来，此次联合军演不仅是中俄(苏)建交55年来的“第一次双边”军演，同时也是“两军”自上世纪60年代交恶后首次面对面的“深层次的合作”，显然，这“当然标志着”两国新型军事互信合作关系达到了40年来的新高点。

*** 这次军演的“演习沙盘”早已经超出了台海问题、朝核问题、中日关系问题

在昨天的《东方时事解读》中，我们是以一个专题的方式、从战略的角度详细地分析了中俄联合军演的战略意义。显然，在我们的眼里，这次军演的“演习沙盘”早已经超出了台海问题、朝核问题、中日关系问题、其影响可以说从北京的战略重心东亚、穿越俄罗斯的战略重心中亚、涵盖印度的战略重心南亚、“中欧俄印”都有重大利益交集的西亚（伊朗）、而直达“驳接”上了华盛顿的战略重心--中东。


*** “中俄”越是强调不针对“第三者”，国际社会就越是起劲儿地“寻找、打听”这个“第三者

因此，在东方评论员看来，也正是有着这么一层“大背景”，世界上的第一个大国都对这次中俄军演“极其重视”。我们也注意到，不论是中国还是俄罗斯，可以说从政府到军队、从官方到民间，总是在那里解释、强调中俄这次军演的矛头“绝不指向”任何“第三者”。

显然，“中俄”越是强调不针对“第三者”，国际社会就越是起劲儿地“寻找、打听”这个“第三者。有意思的是、有的明明够不上“第三者”的身份、却偏偏在那儿拼命地弄出些响声，好让人知道自己受了威胁、以抬高自己的身份。在我们看来，这中间最典型的就是“台独”；


*** 日本媒体攻击“和平使命2005”是在“挂羊头、卖狗肉”

而有的明明受了“真实的威胁”、其政府却在那里“少言寡语”、但却通过其媒体大肆炒作，攻击“和平使命2005”毫无和平可言，全然是种“战争威胁”、是在“挂羊头、卖狗肉”、这种态度最典型的持有者就是与中、俄、韩都有领土争端的日本；

而最有意思的是有人在战略格局上“深深地受到了刺激”，但是政府却非常喜欢“抛头露面”，对整个演习的“指向与动机”“极力地加以淡化”，在那里说什么“中俄联合演习是中国跟俄罗斯之间的事情”，“我们也想看看有什么新东西”。在这里强调一点，这可是美国国务院副发言人艾瑞里、和美军太平洋司令几天前针对中俄联合军演、分别做出的“轻松状”。

然而，华盛顿果真象艾瑞里“口中所说的”、“只是中国跟俄罗斯之间的事情”那般的轻松吗？

在一则有关“另一个联合军演”的消息后，东方时事评论员、军事评论员将继续回到这个话题。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com



** 韩美将在下周进行联合军演朝鲜强烈谴责


【汉城消息】据法新社报道，美国与韩国军方17日正式宣布，两国军队将在下周举行为期12天的联合军事演习。此前朝鲜谴责美韩此举是向朝鲜施压，从而迫使朝鲜在六方会谈中让步。

韩美联合军队指挥部在一份声明中称，演习主要内容是进行电脑模拟军事演习，将从8月22日持续到9月2日。

声明称，演习的目的是评估与提高韩美在实施防御朝鲜半岛重要行动中的组织与协调能力，以及联合防御程序，计划与系统。

更多演习细节没有透露。此前报道称美方将有超过1万人参与，韩方参与的具体人数仍然未知。

美国在上周已将演习消息通知了朝鲜政府。朝鲜随后谴责美国和韩国是在为“发动先发制人袭击做准备”。

朝鲜军方发言人在本月13日的声明中同时说，美国和韩国的目的是迫使朝鲜“在六方会谈中接受美国提出的不合理要求”。



【时事点评】在继续讨论中俄联合军演前，我们先来说说美韩间的军事演习。据了解，美国与韩国准备搞的这个军演称之为“乙支焦点透镜05”。


*** “乙支焦点透镜”其实包括“焦点透镜”军事演习和“乙支”政府演习两部分

事实上，在东方军事评论员看来，韩美间举行“乙支焦点透镜”联合军事演习可以说是一个“传统节目”了，就时间而言，这种演习是韩美自上世纪60年代起举行的“例行军事演习”，顾名思义，“乙支焦点透镜”其实包括“焦点透镜”军事演习和“乙支”政府演习两部分。


*** 韩国“至今不肯公布”韩军的参演人员

据美国方面公布的消息，我们注意到，演习将分两个阶段进行：第一阶段从8月22日到26日，主要“乙支”部分，即是韩国政府部门参与的政府演习，而第二阶段从8月29日到9月2日则为军事演习，这乙是所谓的“焦点透镜”部分。据说包括驻韩美军在内的5000多名美军官兵将参加此次演习，韩军军团、舰队司令部、战斗飞行团也将参加。

但是，东方军事评论员认为，有两个非常耐人寻味，第一，美方一家就“超过1万人”，但韩国“至今不肯公布”韩军的参演人员；第二，演习主要内容是进行电脑模拟军事演习，但在时间的安排上似乎“非常之敏感”。

*** 如果......那么第四轮六方会谈就得在朝鲜半岛上“焦点透镜”的“枪炮声”中进行了

显然，在东方评论员看来，我们所说的“非常敏感”是指的“焦点透镜”部分、也就是演习的军事部分。要知道，此前、由于美国不同意朝鲜发展民用核计划的要求，朝核问题第四轮六方会谈在8月7日于北京休会的时候，可是定在“8月底”复会的。

不难看出，在今后的近十天的时间里、如果六方会谈复会的时间、和“焦点透镜”部分进行的时间都没有改变的话，那么，朝核第四轮六方会谈就得在朝鲜半岛上“焦点透镜”的“枪炮声”中进行了，显然，在东方评论员看来，朝鲜谴责美韩此举是向朝鲜施压，从而迫使朝鲜在六方会谈中让步、绝对不是无中生有、无的放矢。


*** 到底是“美国”欲借“乙支焦点透镜05”向朝鲜施加压力、还是“韩国”想这样做？

我们注意到，按法新社的报道，遭到朝鲜方面谴责的是“美韩”，然而，在东方评论员看来，到底是“美国”欲借“乙支焦点透镜05”向朝鲜施加压力、还是“韩国”想这样做，恐怕是大有文章。

事实上，朝鲜的谴责针对的是华盛顿。请注意新闻中的这一段，原文是：美国在上周已将演习消息通知了朝鲜政府。朝鲜随后谴责美国和韩国是在为“发动先发制人袭击做准备”。此外，朝鲜军方发言人也曾经在本月13日的声明中“揭露”说，美国和韩国的目的是迫使朝鲜“在六方会谈中接受美国提出的不合理要求”。


*** 种种迹象表明，第四轮“六方会谈”没休会、“休会了的”六方会谈“还在谈”

还有，“焦点透镜”演习的主角华盛顿、近日是开足马力“重谈老调”、一再强调一个“非常模糊”的论调，即“美国的对朝政策没有变”，而朝鲜方面则干脆得多，我们注意到、朝鲜劳动党机关报《劳动新闻》今天（8月18日）明显到“回到了从前”、“开始呼吁”美军结束在韩国的军事存在，并发表评论说：“只要美国军队驻扎在韩国，东北亚和世界其他地区就没有和平与安全，朝鲜与韩国也不能实现和平与统一。”

上述种种迹象表明，第四轮“六方会谈”没休会、“休会了的”六方会谈“还在谈”、而且还是“美朝”之间的“双边会谈”。在东方评论员看来，美国与韩国准备在朝鲜半岛上搞的这个“乙支焦点透镜05”军事演习、表面上看、的确是冲着朝核问题去的。


*** 美国的强硬政策、丝毫没有因为“乙支焦点透镜”而得到任何的好处

可问题是，“乙支焦点透镜”军事演习连续搞了这么多年，去年、前年都搞过，但是，事实证明，因北京深深地介入，美国在朝核问题上的强硬政策、丝毫没有因为“乙支焦点透镜”而得到任何的好处，更何况在六方会谈体会期间，“围绕着”朝鲜半岛进行军事演习的还不止“乙支焦点透镜”这一个：在韩国“还没有确定”它自己最终会为“乙支焦点透镜05”提供多少兵力的时候，中俄两国的近10000万人的部队已经展开、并正式操演起来。


*** “和平使命2005”的整个演习将分为三个阶段进行

我们注意到，整个演习将分为三个阶段进行。十八日至十九日为第一阶段，主要演习形式为中俄双方在符拉迪沃斯托克举行新闻发布会，双方总参谋长将进行沙盘推演。8月18日至19日为演习的第一阶段，中俄双方将在俄远东军区境内举行首长司令部演习。在俄太平洋舰队司令部所在地符拉迪沃斯托克(海参崴)，中俄两军还将举行总参谋长级别的军事、政治磋商。

8月20日至22日为第二阶段，也是实兵演习阶段。中俄双方的参演兵力将移师中国的胶东半岛和黄海水域。据了解，根据两军指挥部的演习构想，在中国陆海空军的配合下，俄空降兵一个连的官兵将搭乘伊尔-76运输机在胶东半岛某地实施机降，直插“敌”后。空降过程中，俄空降兵还将空投一批武器装备。与此同时，俄太平洋舰队第55海军陆战师的一个海军陆战连将搭乘大型登陆舰在胶东半岛某海域抢滩登陆，向岸上之“敌”发起进攻。演习期间，参演部队将对“敌”目标进行实弹射击。


*** 中国和俄罗斯都赋予了这次联合军事演习以极深厚的“战略内涵”

8月23日至26日为演习的第三阶段。在俄前线航空兵苏-27SM歼击机分队的掩护下，俄远程航空兵将出动2架图-95MS“熊”式战略轰炸机和4架图-22M3“逆火”式远程轰炸机飞临黄海上空，用巡航导弹攻击海上的靶标。虽然俄方没有透露巡航导弹的型号，但军事分析人士普遍认为，图-95MS、图-22M3轰炸机可能发射射程达3000公里的AS-15巡航导弹。

在东方军事评论员看来，“和平使命2005”是中俄首次大规模的、在中俄双方领土上同时进行的、高水平军事演习,无论是从演习规模、过程安排、还是时间、地点的选择上，都可以清楚地看出、中国和俄罗斯都赋予了这次联合军事演习以极深厚的“战略内涵”。

下面，我们就先来看看解放军总参谋长梁光烈上将、是如何解释选择在山东半岛附近进行军演的。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com



** 中国军方总参谋长解释在山东半岛附近军演原因



　　【符拉迪沃斯托克（俄罗斯）消息】在位于符拉迪沃斯托克的俄罗斯太平洋舰队举行的“和平使命—2005”中俄联合军事演习记者招待会上，总参谋长梁光烈上将和俄罗斯联邦武装力量总参谋长巴卢耶夫斯基大将回答记者提问时说，相信这次演习一定能够取得圆满成功。

　　有记者问：中俄两国历史上首次举行联合军事演习，双方将如何进行协同指挥？联合军事演习在中国的演习地点确定在山东半岛及其附近海域，对此有何考虑？

　　梁光烈回答说，两军的协同，是演习的重点和难点。基本做法是：在战役层面，主要采取两军联席会议形式，共同定下决心，联合制定计划，共同组织协同，联合指挥行动。在技术层面，共同制定协同动作信号，规定通信联络频率等相关措施。为了搞好这次演习，两国军事专家组和参演部队做了大量的准备工作，相信这次演习一定能够取得圆满成功。

　　在回答关于演习地点的问题时，梁光烈说，主要有三点考虑：一是山东半岛及其附近海域具备较好的陆、海、空演练区域，场地条件较好，训练设施比较完善，适合陆海空诸军兵种协同训练；二是我军在这一区域军兵种比较齐全，有多次与外军在非传统安全领域进行联合演练的经验；三是当地经济发达、交通便利、给养条件优越，便于组织演习的后勤保障。

　　巴卢耶夫斯基说，中俄两军的编制确有区别，但不会影响演习效果。这次联合演习是两国友好与合作的象征，是两军协作的象征，我们将高兴地看到这次演习一定会取得成功。



【时事点评】东方军事评论员注意到，对这次军演，俄罗斯联邦武装力量总参谋长巴卢耶夫斯基大将的观点是“这次联合演习是两国友好与合作的象征，是两军协作的象征”。

*** 选择山东半岛作为“两军协作的地点”就让人“联想不已”

然而，在我们看来，中俄这次选择山东半岛作为“两军协作的地点”就足以让人联想不已。因此、东方军事评论员认为，尽管解放军总参谋长梁光烈上将针对“地点”的一番“滴水不漏”的解释显得“顺理成章”，但都让人“无法完全相信”。

第一，山东半岛对中国和俄罗斯都“别具意义”，在我们看来，选择这个昔日苏联军队攻击中国军事计划中的一个极佳的登陆场、一个事关中国安全的战略要地，今天却被北京“有意识地”开放给俄罗斯，并放心地让俄罗斯军队提前10天熟悉地形、真是应了一句老话：“没有永远的敌人，也没有永远的朋友”。


*** 整个军演战场与朝鲜半岛“直接接壤”

第二，我们知道，联合军事演习的“主战场”是山东半岛及其附近的黄海水域，显然，在地图上看，山东半岛本来就与朝鲜半岛隔着黄海“相望”，再加上黄海本身也是演习战场的一部分，可以这样说，即整个军演战场与朝鲜半岛“直接接壤”，在东方军事评论员看来，中俄军演战场与朝鲜半岛之间“贴得是如此之紧密”，紧密得没有任何“地理缝隙”去容纳一个“军演与朝鲜半岛无关”的的解读空间。


*** “非同盟国”之间举行的联合军演，很少有达到这个规模的

另外，在规模上，此次联合演习的兵力超出战术演习范围，已相当于一次小规模战役演习。东方军事评论员认为，俄军自建军以来，很少与别国举行师一级规模的实兵联合演习，而10000人的规模则已经接近了师级规模的实兵演习。

事实上，在国际范围内，虽然美军与欧洲盟国、韩国、日本等搞过一些上万人规模的演习，但在“非同盟国”之间举行的联合军演，很少有达到这个规模的。


*** 我们的一种观点似乎“正在得到了证实”

最后，在时间上，“和平使命2005”似乎和“乙支焦点透镜05”一样，也是为第四轮朝核问题六方会谈的休会期而“量身订做”的。

之前，我们曾经说过，第四轮六方会谈很可能随着中俄军演的高潮而达到高潮，现在看来，尽管六方会谈暂时体会，但从美国和朝鲜之间突然升温的“唇枪舌剑”、韩国对朝鲜“保留民用核能力”的“公开同情”，以及“中俄”与“美韩”、“美日”间准备举行的一系列“在规模上”类似、“在地点上”相关上、“在时间上”“非常巧合”等一系列情况来看，我们的这种观点似乎“正在得到了证实”。

这就是说，在朝鲜公开谴责“美国、韩国”企图借“乙支焦点透镜05”向朝鲜施加压力的同时，美国又何尝不在暗中对“朝鲜、韩国”在借“中俄”的“和平使命2005”撑腰、向自己要价恨得牙根痒痒呢？


*** “和平使命2005”在军事层面上、其战略指向是直指美日军事同盟

在这里，东方评论员想提醒的是，如果我们仔细“数一下”上面一句话中所包含的“国名”，就不难发现，刚刚休会的朝核问题六方会谈中的“六方”、已经出现了五个，唯一不在其中的就是日本。

我们知道、在东亚区域内，现有的领土争端包括中日钓鱼岛以及东海争端、韩日独岛争端，俄日北方四岛争端、非常清楚，所有这些争端少不了日本这个主角、而日本之所以敢四处出击、到处惹事生非、自然是华盛顿给使的眼色、而美国在东亚一带的任何军事行动、在少了“美韩军事同盟”这支“矛”之后、将更加依赖美日军事同盟。显然、“和平使命2005”选择在胶东半岛“上演”，在军事层面上、其战略指向是直指美日军事同盟。

*** 美国人忙得很，“演习只是中俄两国间的事”不过是故作“轻松状”而已

事实上，“美日同盟”的两个盟友对此也是心知肚明，也早已准备了一场与“和平使命2005”规模相仿、地点相关、时间相近、“极具报复性”的联合军演。

显然，在东方评论员看来，“读懂”了“和平使命2005”之“使命”的美国人的确“忙得很”，“演习只是中俄两国间的事”不过是故作“轻松状”而已。

下面，是一段摘自日本《读卖新闻》的一段评论片段，在东方军事评论员看来，尽管我们不同意其“政治立场”、但是，就军事层面来看、文章中对“和平使命2005”的一种看法，还是值得重视的。在一起了解详细内容之后，东方时事评论员、军事评论员将一起给出我们的观点。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com


