# -*- org -*-

# Time-stamp: <2011-08-04 12:59:28 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 2005年8月17日  星期三




** 解读中俄联合军演：有战略考量反映政治军事取向


【解放军报报道】双边或多边军事演习是目前国际上经常举行的、国家间增进了解互信的一种重要方式，不是什么新鲜事。以往的一些参演国也经常进行相关的介绍与宣传，但由于军事演习固有的特殊性，人们对联合军演却始终有一种挥之不去的神秘感。


联合军演大都有其战略考量

联合军演是提升国家间总体关系，威慑和牵制潜在对手的重要手段。军事关系是国家总体关系的重要组成部分，通过联合军演，参演国之间提升了军事合作层次，获得了对其他国家某些战略要地、机场、港口等的准入权，促进了国家间总体关系的发展。这对潜在对手是一种强有力的威慑和牵制。美军为了塑造对其有利的国际安全环境，在东亚重点加强与日、韩之间的军事同盟，每年都和日、韩举行多次大规模联合军演。这些演习绝大多数是以朝鲜、俄罗斯等为假想敌组织实施的。美操纵并落实“美日防卫合作指针”相关的联合军演，以及在中国周边举行的联合军演，也有很强的针对性。

联合军演是表明国家政治立场，增强双边和多边互信、合作的重要途径。在国际政治上，国家不但需要通过外交途径，公开宣扬政治主张，也需要通过包括军事途径在内的其他方式，显示政治决心与政策取向。9·11事件以后，反对和打击恐怖主义成为国际社会的共同愿望，许多国家不但公开谴责恐怖主义行为，表明愿与国际社会携手打击恐怖主义的立场，而且通过联合军演，显示了愿与国际社会共同合作的决心。近年来，以国际反恐、人道主义救援等名义举行的联合军演，占到联合军演总量的80%以上。今年4月独联体集体安全条约组织在塔吉克斯坦境内举行的“边界——2005”联合军演，保加利亚、美国、土耳其、希腊和西班牙5国海军7月在黑海西部海域举行的“微风——2005”联合军演，都是以应对国际恐怖主义袭击为主基调的演习。

联合军演是强化军队战备水平，增强联合军队协同作战能力的重要措施。异国军队联合作战，诸军兵种间密切配合、协调一致行动的难度很高。演习是军队训练的最高形式，是提高战备水平的重要手段。通过联合军演，有助于发现和减少军队间的不协调，强化战备水平，增强联合军队密切配合和协同作战的能力。美军参联会在公开文件中就表示，联合军演除了可以炫耀武力外，最重要的是可以为未来的多国军队行动做准备。“卡卡杜7”联合军演结束后，澳大利亚军方负责人也曾表示：“‘卡卡杜’系列演习进一步增进了我们与其他地区军队的合作能力，对保证各国军事合作至关重要。”

联合军演是演练和展示高技术装备，吸引军火订单的重要舞台。海湾战争以来，高技术武器装备在战争中的突出表现，越来越赢得人们的青睐。各国在削减军队总员额的同时，纷纷研发和购置高技术装备，以图通过提高装备技术含量，增强作战能力。演习是和平时期展示新装备的重要舞台，特别是联合军演所隐含的商机，被世界各国特别是军事强国所看重。一些国家在参与联合军演时，刻意推出一些从演习需要来看没必要出现的装备，其目的除了检验新装备外，也在于展示其优越性能，吸引军火订单。

联合军演演什么

联合军演的内容，某种程度上反映着参演国的政治、军事取向，历来为国际社会广泛关注。20世纪60年代以来，世界各地举行了数千次规模不等的联合军演，尽管特点各异，但其内容不外乎三类。

以潜在对手为想定作战对象，为提高联合军队针对性作战能力而组织的联合军演。这类演习是历史上次数最多、规模最大的联合军演，因为演习以潜在对手为想定作战对象，能够比较准确地反映参演国的作战思想甚至作战方案，因此特别引人瞩目。美韩“协作精神”、“焦点透镜”、“雏鹰”、“阿尔索伊”、“跆拳道”等联合军演，演习方案常常以朝鲜发动“进攻”为背景，演练各种应付方案。

为检验编制、装备，发展作战思想和战法而组织的联合军演。随着国家政治、军事战略和装备技术的发展，军队编制、装备和作战思想、战法等也处于不断发展的过程中，编制、装备、作战思想和战法等的改变，本身不能说明其合理性，在缺乏实战检验的前提下，演习是最好的检验方式。2004年美英法德等11国举行的“眩目风暴行动”联合军演，其目的就在于推动联合部队转型进程。

为应对非传统安全威胁，以联合反恐、维和、人道主义援助、灾害救援等为主题组织的联合军演。近年来，非传统安全威胁凸显，以联合反恐、维和、人道主义援助、灾害救援等为主题，为应对非传统安全威胁组织的联合军演数量激增。我国参加的上海合作组织成员国武装力量“联合-2003”联合军演，就是联合反恐军事演习，它对进一步强化反恐合作机制、维护地区安全稳定打下了良好的基础。今年以来，世界各地举办的所有规模较大的联合军演，几乎都融入了应对非传统安全威胁的内容。乌、美、格、阿4国刚刚结束的“2005·和平之盾”联合军演，就是以联合维和行动为主题的。

联合军演怎么演

按实战要求演习，仗怎么打，兵就怎么练。这是各国军队对演习的基本要求，联合军演也遵循这一原则。但这不等于联合军演都是实兵、实装、实弹、实地的演练。事实上，联合军演不仅可以区分为指挥所演习和野外训练演习，根据使用的技术设备，还可以包括计算机辅助模拟训练演习等方式。

指挥所演习方式组织的联合军演，演习在联合军队司令部内或者联合军队司令部与有关军兵种司令部之间进行，通常无实兵或只带少量实兵参加。此类联合军演，目的是演练各级指挥员和参谋人员的指挥、协调、控制能力，提高联合军队指挥员和指挥机关的指挥、协同能力，为联合军队的作战配合奠定基础。使用实兵的目的通常不是演练实兵行动和战术，而是为了向各级指挥员和参谋人员显示演习中的战场情况。高级别的联合军演，如战区以上，通常采取指挥所演习的方式；战区以下级别的联合军演，在以指挥员和参谋人员为演练对象时，也常常采取指挥所演习方式。著名的“阿尔索伊”系列联合军演，1996年以来俄美举行的4次战区导弹防御联合军演，都是以指挥所演习方式组织实施的。

野外训练演习方式组织的联合军演，是想定作战条件下联合军队在野外进行的单方或对抗性演习，实兵、实装、实地组织、实施。通常以联合部队为训练对象，重点演练战术级科目，特别是演练战术运用的方法与程序等。以野外训练方式组织演习，虽然耗时、费力，但对检验作战理论、武器装备、体制编制和评估作战方案等意义重大，能够获得真实、科学的结论和翔实的数据，是不可缺少的演习样式。今年4月黑海沿岸国家举行的“黑海伙伴关系——2005”联合军演就属于这种方式。

野外训练演习便于造势，因此用于政治、外交目的的联合军演，通常也采取这种方式。美军认为，随着经费紧缩和技术进步，可能减少野外训练演习，增加模拟训练演习，但不管技术变得多么高级和先进，指挥千军万马打赢战争的胆识与魄力，只有通过真枪实弹的搏杀才能建立起来，而且计算机辅助演习根本不可能产生野外训练演习可能引起的那种政治影响。

计算机辅助模拟训练演习方式组织的联合军演，是利用计算机模拟仿真技术和设备对联合军队指挥员和参谋人员进行的演练。利用计算机辅助，特别是采取建模与仿真技术组织演习，训练手段简单直观，演习的难度和强度可调、可控，演习过程具有可逆性和可重复性，便于演习组织和增减参演人员，同时也能够在大幅降低演习费用的前提下保证训练效果。据美军统计，组织一次诸如“海洋冒险”或“坚固盾牌”等级别的大规模演习，通常需要大约80余万个人日工作量和4000万美元，使用模型和仿真器材，不但可以提供相同的训练并达到同样水平，而且只需要动用8万个人日工作量和花费350万美元，费用降低了90%。正因为如此，随着计算机和网络技术的进步，以模拟训练方式组织演习，被越来越多的国家采用，联合军演中也经常见到这种方式。如“2005·和平之盾”的第一阶段演习，就是在乌克兰国家国防研究院，借助计算机网络实施的。



【时事点评】在东方军事评论员看来，解放军报的这篇文章、从政治、军事的“专业角度”、非常好地解读了“联合军演”的意义，即它通常通过获得对其他国家某些战略要地、机场、港口等的准入权，来提升彼此间的军事合作层次，向来被用来当作“提升国家间总体关系，威慑和牵制潜在对手的重要手段”。


*** 中俄规模联合军演意在“公开双方政治主张，显示政治决心与政策取向”

另外，对有关国家在一些特定国际背景下举行的“联合军演”所蕴涵的战略信号，文章中还做了另一番“展开”。请大家注意这一段，原文是：“联合军演”还是表明国家政治立场，增强双边和多边互信、合作的重要途径。在国际政治上，国家不但需要通过外交途径，公开宣扬政治主张，也需要通过包括军事途径在内的其他方式，显示政治决心与政策取向。

显然，在东方评论员看来，中俄间的这次大规模联合军演，就有着上面所描绘的这些“鲜明特征”。

在我们进一步解读中俄联合军演的战略意义之前，再来看一则相关消息。


《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com



** 北京正式邀请印度观摩中俄军演


【新德里消息】中国驻印度大使孙玉玺8月17日在这里指出，中国和印度这些年在军事领域加强相互信任方面取得良好进展,双方友好交往频繁。中国已正式邀请印度派高级别观察员观摩即将举行的中国和俄罗斯的联合军事演习。

孙玉玺在接受本社记者专访时表示，在历史上，中国和印度曾有过友好交往的时期，也曾在边界上兵戎相见。进入新世纪，作为世界上最大的发展中国家，同时又是经济快速发展的国家，中印两国建立了面向和平与繁荣的战略伙伴关系，两国关系获得全面发展，各个领域的友好交往全面开展。

在军事领域，两国政府和领导人非常重视建立相互信任的关系，积极开展友好交往和交流。中国的军事学院曾派代表团访问印度，中国军队总参谋长梁光烈也来印度访问。双方都相互邀请对方派观察员观摩本国的军事演习。这次中国与俄罗斯联合举行大规模军事演习，中国也已向印度发出邀请，希望印度派观察员前往观摩。

孙玉玺说，在边界问题上，温家宝总理今年四月访问印度时，双方签署了关于解决边界问题指导原则的协议，为两国解决这个历史遗留的边界问题创造了良好的气氛和条件，同时，双方决心不让边界问题影响两国关系继续向前发展的大局。随着两国交往的不断增加，增进了彼此的相互了解，消除了印度某些人对中国崛起的疑虑，不再视中国为印度安全的威胁，相反，认为双方的共同发展和合作符合两国的根本利益，有利于地区和世界的和平与稳定。

在这个大环境下，在两国边境地区上出现了一派平静和祥和的气氛，两国的边防部队频繁开展各种交往和交流活动，例如共同举办庆祝两国的传统节日的活动和体育友谊比赛等。

孙玉玺指出，这些举措增进了两国军队的相互了解和沟通，对双方建立相互信任的关系起了积极的作用，同时也为两国最终解决边界问题创造了良好的氛围。



【时事点评】在之前的点评中，东方评论员就多次给出过我们的一个观点，即，中俄联合军演当然会考虑到台海因素，但这种考虑绝对不是主要的、在我们看来，中俄联合军演的一个重要战略意图就是为朝核问题进程“提供另一种选择”，为韩国在华盛顿拒不让步的情况下、自行启动朝鲜半岛经济整合提供一种有别于“六方会谈”框架之外的“安全模式”。

*** 那种只将眼睛主要盯着台湾的观点、显然是“格局太小”

因此，在东方评论员看来，那种只将眼睛盯着台湾、认为北京是在借这次军演、警告华盛顿等其它国家不要介入台海问题的观点、显然是“格局太小”，我们认为，北京还不至于指望莫斯科会在军事层面上帮助中国武力解决台湾问题，华盛顿也不会相信这一点。

另外，我们还想强调的是，朝核问题、或者是东北亚问题也仅是中俄联合军演考虑的众多重要因素之一，东方评论员认为，北京、莫斯科的欲借军演达成的目的“远比这要宽广得多”。


*** 不论是北京、还是莫斯科、都在将这次军演渲染成自己全球战略的一个“重要开端”

在东方评论员看来，北京“正式邀请”印度派高级别观察员观摩中俄这次大规模“联合军事演习”、以及邀请伊朗、等上海合作组织成员国、观察员“观摩”、就是不让美国、日本人参观、这其中所蕴涵的战略信号是非常清楚的，那就是，不论是北京、还是莫斯科、都在将这次军事演习渲染成自己全球战略的一个“重要开端”。

事实上，与上述那种“小格局”的观点相比，华盛顿的战略决策层显然有另一种立场，那就是“中俄关系正在解冻，这也正是我们要在亚洲与印度改善关系的原因之一。”


*** 华盛顿“读懂了”到中俄的“战略意图”

显然，华盛顿“读懂了”到中俄的“战略意图”，也就说，“中俄”将以这次军事演习为标志，开始一系列的战略调整，其调整范围涵盖中亚、中东、南亚、东亚。
简而言之，中俄有意在上述区域内“相关利益上”展开战略合作。

客观上讲，在首席评论员看来，华盛顿的战略家还是非常睿智的，但是，不论华盛顿的战略家是如何地睿智，“似乎都无法看清”美国在亚洲的战略、实际上是一条越走越窄的道路，显然、在亚洲、美国正走在一条以冷战思维为基调、以“中国威胁论”为理论、以“拉帮结伙”遏制中国为主轴的“冷战思路”上。


*** “高处不胜寒”的华盛顿

在我们看来，华盛顿决策层之所以选择这条路，客观上是应了中国一句老话、谓之为“高处不胜寒”。因此，东方评论员认为，为了维护和强化自己的政治、经济、军事霸权、华盛顿似乎找不到“遏制潜在对手”之外的任何政策。仅凭此一项，就足以让华盛顿的亚洲战略“总体上处于”一种“逆潮流而动”、心有余而力不足的困境之中。显然，华盛顿在“瞄着”中俄战略关系解冻、而致力于改善“美印”关系的时候，就痛苦地感受到了这一点。


*** 对谁才是世界的威胁、谁想限制自己的战略发展空间、“列强”心里是有一本账的


我们都清楚，华盛顿的全球战略核心就是阻止任何一个国家发展到威胁美国全球霸权的程度，而在华盛顿的眼里、不论是欧盟、还是中国、俄罗斯、都具有成为全面威胁美国旨在支配全球之全球战略的庞大潜力。

目前，在欧盟的“一体化进程”遭遇重大挫折之后，中国似乎已经被华盛顿通过鼓噪“中国威胁论”、而被“有意识地突出为”美国的“唯一威胁”。然而，由于中国综合国力已经提高到近100多年来最为强盛的时期、中国经济上对世界经济的贡献度、以及对东亚的辐射度已经到了没有人忽略的地步，再加上国际社会目睹了美国“拿着”单边主义在中东进行的“实践”，已经让国际社会、特别是欧盟、中国、俄罗斯、印度、以及巴西这些地区强势中心，对谁才是世界的威胁、谁想限制自己的战略发展空间、心里是有一本账的。


*** 就中印的“历史”而言，两国间的矛盾其本质在于地缘因素

在东方评论员看来，就中印的“历史”而言，两国间的矛盾其本质在于地缘因素，我们认为，在地缘因素的基础上，引致中印关系一度对立的原因有两条：第一，双方过去最为严重且发生直接冲突的两个问题—西藏与边界问题；

第二，在冷战期间，美苏对峙、本质上也是在欧亚大陆上的争霸，东亚的中国和南亚的印度、事实上同处于冷战前缘。显然，这样的特殊地理位置,注定了这两个相邻的大国成为当时两极霸权“你争我夺”的焦点,基于自己利益，中印也必然会在美国和苏联之间有所偏移、也因此造成中印长期以来的外交对峙、战略相持。


*** 中、印和美国之间的战略冲突、都绝对大于中印之间的战略冲突

不过在现在，由于美国是当今唯一的超级大国，其先手控制中东、中亚的石油资源、再支配世界政治、经济的野心是昭然若揭，而中国和印度都是正在崛起的大国。

在我们看来，就目前而言，北京面对的是西太平洋、战略重心在东亚、战略重点是突破一、二层岛链封锁线,突入太平洋,与美国在东现角力、着重在西太平洋方向上挤压美国的势力，在太平洋方向扩展自己应有的利益和权利；

与此同时，印度面对的则是印度洋，其战略重心在南亚次大陆、战略重点在于控制临近中东这一能源中心地带的印度洋。显然，如果除去边界争端，那么，无论我们站在什么角度上去看，中国、印度和美国之间的战略冲突、都绝对大于中印之间的战略冲突。


*** 美国担心受到中印的“双向冲击”

东方评论员认为，事实上华盛顿的战略家们对此也是心知肚明，在他们看来，如果放任中国和印度“搞经济建设”、那么中印将来发展起来的政治、经济、军事力量,必然沿着靠近中东的印度洋方向、沿着靠近韩国、日本、台湾的太平洋方向、双向冲击美国的全球战略格局、从而冲击、并动摇美国在中东、东亚的战略布局。


*** 绝对不允许“中印”埋头建设的华盛顿、抛出了一套“连环计”

由于中国与印度都是历史悠久的大国、也是人口大国，还是科技大国（不是强国）、都具备将来在政治、经济、军事、科技成长为世界一极的巨大潜力。因此，在华盛顿决策层看来，任何对“中印”经济发展不加以遏制的念头都是愚蠢的，都将给美国的全球战略带来灾难性后果，也必将导致美国失去对印度洋和太平洋的军事控制、继而是失去其全球经济主导权、最终失去美国的世界霸权，这是绝对不允许的。

也正是如此，绝对不允许“中印”埋头建设的华盛顿、自然就会想起尼克松遗留下来的政治遗产--“大国制衡”政策。为了“拉一个打一个”，华盛顿的战略决策者抛出了一套“连环计”：第一，是舆论上的，即大声宣传印度经济的“突飞猛进”、并在国际上营造一种有必要把投资重心转向印度的声势。

第二；就是所谓“中国威胁论”，根据我们的观察，华盛顿在向印度人“解说”“中国威胁论”时、是极其卖力的，有了“投资印度的意向”之后，再去“费力地猜测”“中印到底谁能主宰亚洲”就成了“理所当然”的第二步了，

然而，在东方评论员看来，对以美国为首的西方舆论高唱中国和印度“争雄”，印度人显然有两种不同的看法。一种是被西方舆论牵着鼻子走、开始以一种“洋洋得意”的心情、“夹杂着警惕的眼光”审视着中国；而另一种是“看透了”西方总把中国和印度的发展看成“相互对着干”，并且想方设法鼓励这种“对着干”的“叵测居心”，认为把中国当作印度发展的障碍是愚蠢的。

东方评论员就注意到，印度国大党少壮派领袖就持后一种观点。


*** 华盛顿竟然打出了“帮助印度成为一个强大国家”的旗号

令人惊奇的是华盛顿使出的第三招---竟然打出了“帮助印度成为一个强大国家”的旗号。

然而，只要对美国全球战略之核心稍有理解的人都知道、华盛顿“肯”帮助印度“成为一个强大的国家”的本身，就是对印度的侮辱，显然，印度之所以得到美国政府的“如此青睐”，就在于在华盛顿决策层的眼里、中、美、俄、欧盟、印度这些将来“最有可能”成为世界一极的“政治经济体”中、印度绝对是“最不可能的”一个。


*** 对印度“最为有利的策略”可不是“选边”站

然而，在东方评论员看来，这个“最不可能者”的领导层、对华盛顿的“真心帮助”自然也是“不敢相信”，事实上，在“中美印”的互动中、对印度“最为有利的策略”可不是“选边”站、而是在“中美”之间“左右逢源”、在“中美俄”间游刃有余、并站在印度洋这个欧亚中心地带、于“中欧俄美”间扮演一个四两拨千斤的角色、从而为自己“已经起飞”的经济建设、赢得一个最好的外部条件。


*** “极不高兴”的赖斯一回国，就给印度脸色看

结果，在美国国务聊赖斯3月访问印度期间，面对赖斯的众多合作条件、比如售给印度F-18军机、但印度仍然是一口拒绝了与美国合伙遏制中国的要求。结果、“极不高兴”的赖斯一回国，就给印度脸色看、宣布向印度的对立面--巴基斯坦出售了一批F-16军机。


*** 印度人知道自己手中“有的是牌”、不怕华盛顿不来

有意思的是，东方评论员注意到，当时，印度政府是立刻拉高声调、向华盛顿提出严重抗议。显然，东方评论员认为，印度之所以在拿到比F-16更先进的F-18之后、仍然“得了便宜还卖乖”，就在于印度领导人非常清楚，亚洲大陆的地缘政治正在激烈动荡：苏联在14年前消失，美国现在又不能填补因此而留下的战略空白，这就为亚洲画出了一个新的活动空间、因此，在目前这种“中欧美俄”四处角力的国际背景下、地处欧亚中心地带的印度人、知道自己手中“有的是牌”、不怕华盛顿不来。


*** 中印双方建立战略互信奠定一个“坚实基础”

首席评论员认为，值得强调的是，印度在“力争一个和平环境、致力于经济建设”这一政策取向上、与中国是高度一致的，在我们看来，仅凭这一点共识，这足以为中印双方建立战略互信奠定一个“坚实的基础”。

也正是在这种战略取向上的互信下，中印“都有意暂时放下”地缘政治上的长期争端、启动经济层面的战略合作。


*** 中印实现战略接近的“最大动力”

东方评论员认为，事实上，华盛顿遏制北京、以及支配全球的企图心、是中印实现战略接近的“最大动力”。在东方评论员看来，华盛顿越是对北京采取对抗的态度，北京也就越可能会积极地去和其他亚太国家“密切合作关系”。其结果，也就是华盛顿“也会越多地尝试”同此这一区域的国家建立各种密切关系。



*** “愿意”购买美国军火的印度、同样“也愿意”与中国建立“战略合作”

有意思的事情就是这样发生的。结果，“我们”也就看到了4月份、温家宝总理访问印度“取得了圆满成功”（温家宝总理的原话）这一幕，之前因“拉印遏中”未果、而“气呼呼”地离开印度的赖斯、也就看到了“愿意”购买美国军火的印度、同样“也愿意”与中国建立“战略合作”关系这一幕。

温家宝总理四月对印度的访问的一大成果，在于双方将结束两国边界争端纳入正常轨道，双方同意从战略的高度尽快解决这一争端，印度明确承认西藏属于中国，而中国第一次明确承认“印度共和国的锡金邦”，客观上讲、在这一点上、北京是作了让步的，因为印度承认西藏属于中国是一种“重申”。


*** 华盛顿切实地感受到自己在亚洲的势力“正在遭受挤压”的气氛

但在这一“谅解”的基础上、中国与印度建立战略合作关系。东方评论员认为、北京在南亚方向地缘政治上的安排更多的是针对美国的，对于北京来说，中印建立战略互信、事实上已经非常成功的让美国的盟友日本、在亚洲本质上已经没有了任何用来借以遏制中国的“重要盟友”。

在我们看来，日本在亚洲遭到孤立，一方面对华盛顿未必是坏事、这有助于日本更紧地依靠美国；但另一方面，华盛顿也因自己在亚洲利益的代理人日本“被北京孤立”、而切实地感受到自己在亚洲的势力“正在遭受挤压”的气氛。

东方评论员认为，在这一点上，在美军在中亚的军事基地的“去留问题”上、在“中俄”将伊朗、印度、巴基斯坦这三个重要国家、“一把发展成”上海合作组织的准成员国的问题上、似乎体会得“更加深刻一些”。


*** 中印“密切彼此关系”的举动中、就包括“军事演习”

东方评论员注意到，之后，中印“密切彼此关系”的举动是一个接一个，其中，就包括“军事演习”方面的事情。我们知道，2003年中印海军在上海举行联合军事演习，那次演习的倡议者是当时的印度国防部部长费尔南德斯。显然，该演习被看成是两国关系史上的里程碑。有意思的是，我们注意到，印度“再次”提出了举行第二次中印海军军演的建议，除了邀请中国海军进入印度洋，印度还将邀请中国军方观摩秘密军事演习。


*** 最值得注意的一件事情

显然，在“密切中印战略性关系”方面，中印间或举行、或观摩对方的“军事演习”、绝对是一个非常有效的手段。在东方评论员看来，最值得注意的是、印度正在准备在印度洋地区通过建立一种新的多边安全框架来打破其以往的孤立。

东方评论员认为，印度提出与中国在印度洋举行海军军演的目的也正在于此。与此一样，中国和俄罗斯将印度列为上海合作组织观察员、并邀请印度“参与”“和平使命2005”，本身就意味着“中俄”愿意在印度洋建立“新的多边安全框架”中、扮演重要角色。


*** 这简值是在“抄华盛顿中东战略的后路”

在东方评论员看来，这种包括“中俄印”这三个分别有着世界上任何一个国家都不敢小视的常规军力、以及核力量的军事大国的、“新的多边安全框架”一旦成形、由于它紧靠美正在全力经营的中东、和华盛顿“必拿下而后安”的伊朗、毫无疑问、它对华盛顿全球战略的“规划者”的刺激、是非常强烈的，我们认为，这简值是在“抄华盛顿中东战略的后路”。


*** 印度这这一轮“中美俄印”互动中、无疑成了“最大的赢家”

也正是如此，在防止核扩散问题上的态度一向非常强硬布什政府，似乎有点急了，在牙隔赖斯访印“不高兴地”回国之后仅四个月，于7月18日，也就是中俄正式开始军事演习“一个月前”、摇起一根巨大的橄榄枝，即，美国政府承诺向印度民事核能研发项目提供全面合作，等于承认了印度核国家的地位、从而为进一步提升美印关系、拿掉了一个巨大的障碍。这样一来，印度这这一轮“中美俄印”互动中、无疑成了“最大的赢家”


*** 华盛顿在南亚闹了个“前倨后恭”、“信用全无”

然而，在前面我们已经说了，“高处不胜寒”的华盛顿，让华盛顿的亚洲战略“总体上处于”一种“逆潮流而动”、心有余而力不足的“困境”之中。显然，华盛顿在“瞄着”中俄战略关系解冻、而致力于改善“美印”关系的时候，不仅“因此”而没有达成让印度选边站的目的，反而把自己“给送进去了”：在东方评论员看来，华盛顿在南亚政策中，最失败的一点，倒不是“不高兴的赖斯”让布什给卖了、闹了个“前倨后恭”，而是自己被迫在印度和巴基斯坦间“选边站”。

首先，按照《不扩散核武器条约》的规定，凡是拒绝签署该条约的国家，都不能得到任何形式的核援助。而且，多数情况下，将面临核武器禁运的制裁。

但是，在东方评论员看来，印度恰恰是个在拒绝签约问题上态度最为强硬的国家，我们认为，华盛顿在对印度的核问题上，采取双重标准，不仅“无法服众”、“全失信用”、而且还会招来“严重的后果”，事实上，北京在朝核问题、伊朗核问题上、都正在对这一点“加以充分利用”。


*** 有意思的是，现在，这招棋华盛顿“也下成了臭棋”

显然，美国承认印度而不承认巴基斯坦“是核国家”的“选择”、实际上是在印度的压力下、被迫与巴基斯坦拉开了距离，根知道、自攻打阿富汗之后，华盛顿就一直在致力于用巴基斯坦作为筹码来压迫印度、并尝试着挤压北京。有意思的是，现在，这招棋“也下成了臭棋”。

另外，东方评论员认为，由于那个路人皆知的全球战略、以及攻打伊拉克的事实、华盛顿要想让人相信它的“诚意”是非常困难的。在印度为了确保自己的能源安全问题上、美国人就再次痛苦地感受到了“没有信用”苦痛。

在我们看来，在能源问题上，我们可以更加非常清楚地看到、印度对那个自称“愿意帮助其成为强大国家”的美国是多么地“不放心”、为此，一边“笑纳”华盛顿伸过来的“核橄榄枝”，一边印度却更大力度地与北京、莫斯科展开了“务实的合作”、要求北京、莫斯科来保障印度的能源安全、这对华盛顿而言，等于是“又闹了个笑话”。

在一则相关消息后，东方评论员将继续就这一问题进行展开。


《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
