# -*- org -*-

# Time-stamp: <2011-08-04 11:56:07 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 2005年7月08日 星期五

** 外交部宣布：吴仪将出访中亚四国、时间长达10天




【中国外交部网站消息】据中国外交部发言人刘建超昨日宣布，应哈萨克斯坦共和国、乌兹别克斯坦共和国、土库曼斯坦、塔吉克斯坦共和国政府邀请，国务院副总理吴仪将于7月13日至22日对上述四国进行正式访问。

访问哈萨克斯坦期间，吴仪副总理将与哈萨克斯坦副总理叶西莫夫共同主持召开中国和哈萨克斯坦合作委员会第二次会议。两位副总理去年7月2日在北京共同主持了该委员会第一次会议。中哈合作委下设经贸、能源、交通、科技、人文等十个合作分委会。委员会负责协调事宜。




【时事点评】在东方评论员看来，在很大程度上，仍然在举行的G8峰会、不仅因为参与者彼此间“心结”沉重，而难有成果，就是其“应有的光芒”也已经因为“中俄”在
“G8会前”的一连串的、“有组织”、“有预谋”的“联合行动”、以及在“G8会中”、伦敦“意外的”爆炸案给“打磨得”一干二净了。

*** 上海合作组织元首宣言中、有一条信息特别值得注意

在昨天编发的“时事解读特别评论”中，“中亚专题组”就特别指出，上海合作组织元首宣言中、还有一条信息特别值得注意，那就是，“本组织（上海合作组织）愿积极参与在阿富汗周边构筑“反毒带”的国际努力，参与制定并实施专门计划，帮助阿富汗稳定社会经济和人道主义形势”。

在我们看来，上海合作组织愿意“参与制定并实施专门计划，帮助阿富汗稳定社会经济和人道主义形势”的心情确是“不假”，但是，在东方评论员们看来，“这种愿意”不过是手段，掩蔽在这后面的“真正目的”就是“寻机”将北约（实际上就是美国）从阿富汗挤出去、甚至是将阿富汗也纳入组织之内。

*** 阿富汗有着极其重要的战略价值

东方评论员认为，阿富汗这个中国历史上史称大夏的地方，从来就是中外交流的战略要地，因为它本身就是那条“古丝绸之路”的要冲。只要我们打开地图，就不难发现，它北接欧洲大陆、以及现在的中亚五国，南接南亚的印度、巴基斯坦、东邻西亚的伊朗，西边还与中国境内仍然有“东突”分裂势力活动的新疆相接壤。

在我们看来，也正是因为处于这种“南来北往”、“四通八达”战略要地，无论对美国的世界战略，还是对中国、俄罗斯的自身安全而言，阿富汗都是个必争之地。

在这方面，其实不需多说，只要我们回想一下当年冷战时期的一段历史就可以一清二楚了。当时，在伊朗爆发伊斯兰革命之后、华盛顿丢失了伊朗，尔后，中美苏三国立刻都将关注的焦点定格在与伊朗毗邻的阿富汗。

结果，在近十年的时间内，中美联手支持阿富汗游击队、将十万苏联军队拖在阿富汗，从而打碎了苏联欲打通这条通往南亚的战略要道、压迫当时还是美国的盟国巴基斯坦、寻机与印度联成一线的战略计划。仅通过阿富汗战争这一幕，相信我们就不难体味阿富汗的战略价值是何等的重要。

*** 美国战略家们的一种设想

显然，抛开别的因素不说，根据我们的观察，华盛顿的战略家们显然认为，美国如果能拿到中亚更好，如果拿不到，退而求其次、也可通过“民主移植计划”将中亚搞乱，通过培植极端势力，分裂势力、从而将中亚做成“中俄”的另一个车臣，做成一个极端分裂势力的大本营、从而将这个经济落后的地区、作为“大包袱”扔给中俄、自己则隔着太平洋“在旁边使劲”。


*** 这套“假民主”“真控制”民主移植计划的“核心目的”

在东方评论员看来，华盛顿这一套“假民主”、“真控制”、“如果得不到就搞乱”的民主移植计划，其核心目的就是：不论美国能否得到中亚，都可以为其“长期占据阿富汗”的战略制造“一大片缓冲区”。


*** 中俄主导的“上合组织”与美国主导的“北约”全力争夺的一个“香饽饽”

第三，值得强调的是，就是上面提到的那个土库曼斯坦。大家知道、这是“中亚五国”中的、唯一不是“上合”成员国的中亚国家。在东方评论员看来，这个从“前苏联”独立出去的、位于中亚西南部的内陆国、却绝对是中俄主导的“上合组织”与美国主导的“北约”全力争夺的“香饽饽”。

打开中亚地图，我们可以非常清楚地看到，在地理上看土库曼斯坦、是个西濒里海，北邻哈萨克斯坦，东北部与乌兹别克斯坦接壤的国家，可在东方评论员看来，这还不算完，“最核心的价值”在于它还东界华盛顿“已经占据着的”阿富汗，南接美国“极渴望控制”的伊朗。


在东方评论员看来，如果是“上合”得到了这个国家，那么，“上合”就可以从中亚直接与伊朗相连，直出西亚；如果美国主导的“北约”控制了该国，那么，加上仍然在“北约”手中的阿富汗，事实上美国就可以“彻底切断”从中亚通往伊朗、巴基斯坦“最便捷的通道”。


*** 美国在土库曼斯坦的介入极深

东方评论员认为，由于有了这么一层“战略要素”，再加上上述那些独天得厚的地理条件，注定美国人会在土库曼斯坦的身上“下血本”。事实也正是如此，美国在土库曼斯坦的介入极深，这一点从中俄始终无法将土库曼斯坦发展为上海合作组织的成员国就可以看出。

东方评论员注意到，美国计划从那里兴建一条穿越阿富汗、通往阿拉伯海的天然气管。在我们看来，也正因华盛顿有把握控制土库曼斯坦，它才敢想、也才敢做这个工程、不过，有意思的是，它还只是计划，也就是说，美国人还没敢干这件事，那么，这中间的问题出在哪呢？华盛顿对土库曼斯坦没有信心了吗？在东方评论员看来，事情不那么简单。


*** 这条天然气管“最核心的价值”不在经济层面，而在政治层面

对此，我们的观点是，这条天然气管“最核心的价值”不在经济层面，而在政治层面。前面说了，“北约”（实际上是美国）一旦控制了土库曼斯坦、和阿富汗，就可以“彻底切断”从中亚通往伊朗、巴基斯坦“最便捷的通道”，在这里，我们之所以提出一个“最便捷通道”的概念，就在于这个“最便捷通道”实际上是中亚最近的一条通往大海（阿拉伯海、印度洋）的路径、也是印度从中亚获取石油最便捷的一条路径。


显然，一旦通往中亚的这条油路被华盛顿彻底控制，而中东或者被美国控制、或者被美国推入战乱，那么，印度所有的能源线也就掐在了美国的手中，这正是印度不愿意参与美日遏制中国的同盟、而甚至愿意反其道而行之、宁愿与中国、俄罗斯搞“三国能源合作”、甚至“有意不惜将俄罗斯的石油通过中国引入印度”的根本原因。


*** 印度在尽管可能地让自己处于“下棋”、而不为人“所下”的地位

但是，在东方评论员看来，不论印度如何拒绝“美国、日本的请求”去共同遏制北京，都是出于自己的国家利益：一方面借北京的力量、防止华盛顿提前对自己进行打压、另一方面，借华盛顿不敢在这个时候得罪自己、而在北京、莫斯科、欧洲面前抬高自己的身价。

最重要的是印度不想因此而被捆在美国的身上、失去一个借助建设亚洲经济一体化、与亚洲国家、特别是中国一起发展壮大的机会、并与世界其他大国一起、共同阻止华盛顿取得中东、中亚，或者搞乱中东、中亚，从而确保自己有个最为要紧的“和平、稳定外部环境”。

因此，在东方评论员看来，站在印度的立场来看，不论是美国、还是中国、都是不可靠的，都是潜在的竞争者。因此，不论是伊朗的能源、还是中亚的能源、或者是俄罗斯的能源，美国控制的油气管道、还是中国控制的油气管道，也不论是美国市场、还是中国市场、欧洲市场、是“都需要的”、只有这样，才能尽管可能地让自己处于“下棋”、而不为人“所下”的地位。


*** 这条引自土库曼斯坦、经阿富汗、到阿拉伯海的管道是专门为印度设计的吗？

显然，美国计划中的那条引自土库曼斯坦、经阿富汗、到阿拉伯海的油气管道，就能让印度在将来在拥有伊朗能源管道（伊朗、经巴基斯坦、到印度的石油管道正在计划中）的同时、还可以选择俄罗斯能源管道（俄罗斯经中国到印度）、除此之外，就是也可以选择美国投资的这条引自中亚的能源管道。

因此，在表面上看，这条引自土库曼斯坦、经阿富汗、到阿拉伯海的管道，似乎毫无疑问，就是专门为印度设计的。



*** 美国人的心思要远比这“深得多”！

然而，首席评论员就曾经指出，美国人的心思要远比这“深得多”！

在东方评论员看来，从华盛顿建设这条管道的计划就可以看出，美国人压根就没有想过会失去阿富汗，换句话说，美国已经将阿富汗视为自己的掌中之物、私有财产、而加以全盘经营的。



*** 要想长期占据阿富汗，美国就得让阿富汗人“自己能养活自己”


我们认为，美国要想长期占据阿富汗，一个重要的前提就是得让阿富汗人“自己能养活自己”，并过上一天比一天好的好日子。显然，这就需要让阿富汗“生产、创造财富”。


*** 一旦阿富汗天然气经这条管道送到了海上，阿富汗将被打造为中亚的以色列

众所周知，阿富汗盛产樱粟，但这是毒品，这正是上海合作组织元首宣言中明言“要堵绝的一条财路”。当然，阿富汗也有丰富的天然气，但一直埋在地下，在东方评论员看来，让这些埋在地下的天然气养活阿富汗人，这也正是美国计划修建那条引自土库曼斯坦、经阿富汗、到阿拉伯海的管道的主要考虑。

不难看出，一旦阿富汗的天然气经这条管道送到了海上，那么，华盛顿新保守主义者设计的、旨在长期占据阿富汗的计划就有了物资保障、也就有望彻底实现了。从此，阿富汗将被打造为中亚的一颗美国钢钉，在破坏中亚稳定方面、将与破坏中东稳定的以色列、起到一样的坏作用，换而言之，那时，华盛顿决策层就会有条件、而将阿富汗打造成中亚的以色列。


*** 中国、俄罗斯、甚至是印度、对华盛顿这一战略企图都极其警惕

此外，那个地处中亚深处的土库曼斯坦、也将因此而被华盛顿抓得更牢。由此可见，这条管道对美国的中亚战略是何等重要。不是别的，是因为它建成与否、将对美国能否长期有效控制住阿富汗起决定性的作用。事实上，中国、俄罗斯、甚至是印度、对华盛顿这一战略企图都极其警惕。


因此，从印度“放风”有意让俄罗斯的石油经中国流向印度这一点、我们就不难看出，起码俄罗斯和印度这两家、就对美国这种将阿富汗视为隔断中亚与南亚、西亚战略联系之要塞的战略、是极其不满、也非常警惕的。

显然，在印度看来，不论从中亚哪个点建一条通往南亚的管道，只要美国在阿富汗一天，那么，些中亚到南亚的石油管道都会被美国掐住一天。东方评论员认为，这对一个不愿意被美国控制的印度而言，是非常危险的。


*** 如何将华盛顿从阿富汗、从中亚赶走，也是印度最为迫切的需要

在东方评论员看来，事实上，如何将美国从阿富汗、从中亚赶走，不仅成了北京的需要，更成了俄罗斯、印度最为迫切的需要，显然，在这种背景下，印度愿意和巴基斯坦、伊朗一道、而北京、莫斯科也一致同意他们同时成为“上海合作组织”的观察员、就在于中国、俄罗斯、印度都充分地考虑了这一层。

不难看出，已经成为上海合作组织观察员的印度、巴基斯坦、伊朗、之所以有参与这个区域性安全组织的愿望，就在于看到了在“中俄联手”下，上海合作组织将发挥极其重要的作用。而这种“极其重要的作用”、首先就表现在它可以给中国、印度这两个正在快速发展的国家一个非常需要的稳定环境、和一个稳定的能源来源。


就目前而言，由于伊朗、巴基斯坦、特别是印度正式成了上海合作组织的观察员，因此，美军占据下的阿富汗、事实上已经在上海合作组织的包围之内了。尽管上海合作组织的影响还没有正式扩大到南亚，但是，印度出于自己的战略利益，再加上巴基斯坦的牵制，在将华盛顿挤出阿富汗、中亚的问题上，是有可能与中俄主导的上海合作组织保持一致的。

*** 华盛顿没有实施这个计划的原因、是否就是因为被“中俄巴印”给堵住了？

因此，在东方评论员看来，只要“中俄”通过自己的影响力、或者通过上海合作组织的影响力、分别让相互牵制的巴基斯坦和印度“堵住”美国计划中的那条引自土库曼斯坦、经阿富汗、到阿拉伯海的油气管道，那么，美国在阿富汗的日子就会非常难捱，要知道，阿富汗除了有丰富的天然气之外、可以说是什么都没有（因为运不出来），显然，如果将这条美国间在为土库曼斯坦、阿富汗“打造饭碗”的管线给堵住，那么，美军控制下的阿富汗、可就什么值钱的东西也运不出来了。

前面说了，美国对这条管线还处于计划阶段，华盛顿没有实施这个计划的原因、是否就是因为被“中俄巴印”给堵住了、说实在的，并没有确切有消息可以证实，但就效果而言，管道没有动工与管道被堵住了、是一个效果。


*** 欧盟一位国际问题专家的观点

我们认为，在上海合作组织元首宣言中、有关阿富汗的政策已经说得很清楚了，既“本组织（上海合作组织）愿积极参与在阿富汗周边构筑“反毒带”的国际努力”。

东方评论员注意到，欧盟一位国际问题专家就指出，“一旦上海合作组织完善了自身功能之后，我相信宣言中所说的、在阿富汗周边构筑“反毒带”的国际努力”可以视为一种对阿富汗的“经济制裁”的警告”。

的确，在美国人帮阿富汗从地下挖出天然气、送到海边、供给客户之前，阿富汗的主要创汇经济不就是毒品吗？由此可见，这种将在阿富汗周边构筑“反毒带”、与“经济制裁”阿富汗“直接挂上钩”是有道理的。


*** 在有大国干预的情况下，任何一个政权都不可能在一个长期贫穷的社会坐稳位置

在我们看来，如果有朝一日中俄主导的上海合作组织、果真在阿富汗周边构筑“反毒带”、或者对美国控制下的阿富汗实行“经济制裁”，要么美国人就得用美元、或者物资给阿富汗“大量输血”，将阿富汗养着，要么，就象现在这样，任由阿富汗继续贫穷下去、而且比现在更贫穷。

然而，在东方评论员看来，在有大国干预的情况下，任何一个政权都不可能在一个长期贫穷的社会坐稳位置，何况阿富汗是个派系众多、善搞内战的国家，可以说是一点就着。不要忘记了，它的旁边就是中国、俄罗斯两个在联合国有否决权的政治、军事大国。

由此可见，上海合作组织一旦完善了自身功能（主要是统一的军事行动能力和协调的经济政策），那么，上海合作组织的存在、本身就绝对是对美国阿富汗政策、中亚战略的全面围剿。

*** 关键的一条，就是中俄要先将上海合作组织的事做好

众所周知，中俄本来就对阿富汗的影响很大，特别是中国，对如何通过支持阿富汗游击队、与苏联打冷战本来就有经验。

不难想像的是，如果继续贫穷的阿富汗人、或者重新陷入内战的阿富汗人、在看到旁边的中亚国家、在上海合作组织的组织内能够稳定政局、发展经济、更或者能够建立中亚共同体，不用“中俄”从中挑拔各种政治势力，恐怕美国人就是花再多的美元、想稳住阿富汗的民心都难。

显然，不论是将美军挤出上海合作组织成员国、还是将美国挤出阿富汗、关键的一条，就是中俄还先将上海合作组织“内部的事务”做好。毫无疑问，当务之急就是“以务实的经济合作”充实上海合作组织的合作内容。


*** 吴仪副总理的10天的访问，是中俄共同搞好组织内事务的第一步

在东方评论员看来，应哈萨克斯坦、乌兹别克斯坦、土库曼斯坦、塔吉克斯坦政府的邀请，国务院副总理吴仪将于7月13日至22日对上述四国进行正式访问，正是各成员国有意加快经济合作的重要一步、也是这次峰会后、中俄共同搞好组织内事务的第一步。

我们认为，专责经贸的吴仪副总理、在10天的访问行程中，一定会与中亚国家敲定一大批“惠及各成员国”的具体合作项目、从而切实地将元首宣言“落在实处”。

在这里，我们再回过头去看乌兹别克斯坦、吉尔吉斯斯坦先后、公开要求美国从该国尽早撤军、或者要求就使用军事基地的事情重新安排、另提条件的做法，也是各成员国将
元首宣言“落在实处”在具体表现。


在东方评论员看来，要北京去平壤，这是布什早就在催促的事儿，不过令布什遗憾的是，胡锦涛主席“似乎没有兴趣”亲自赴朝，不难看出，外交部“赶在赖斯访华之前”发布这条消息，真可谓“意味深长”。

下面，我们先来听听外交部发言人宣布的另一条外事消息，说的是国务委员唐家璇、将以胡锦涛主席特别代表的身份，将于7月12日至14日对朝鲜进行正式友好访问。之后，东方时事评论员，军事评论员将一起就今天的朝鲜问题展开讨论。


《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
