# -*- org -*-

# Time-stamp: <2011-08-02 19:39:23 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

#+STARTUP: indent

* 2005年03月17日 星期四


** 美称中国仍向伊朗提供大规模杀伤性武器技术

【综合消息】据海外媒体报道，美国指责中国仍在继续向伊朗提供非常规式武器和军民两用技术。美国官员称，中国仍在向伊朗转让用于大规模杀伤性武器(WMD)的部件和技术。相关人士透露说，中国向伊朗提供的一些关键部件是通过巴基斯坦中转到伊朗的。
 
据世界论坛新闻网报道说，负责武器控制的美国助理国务卿拉德马克(StphenRademaker)日前告诉美中经济安全评估委员会，中国的“不可接受的(武器)扩散活动仍在继续”，“我们特别关注中国向伊朗继续转让的CBW-和与导弹相关的技术，尽管中国强迫接受武器禁运。”
 
据悉，中国向伊朗液体燃料导弹项目转让的关键部件包括，两用的导弹部件、原材料和关键技术。美国官方称，与此同时中国还向伊朗提供了一些与生产化学武器相关的产品设备及技术。美方已确认一家中国向伊朗出售武器技术的公司，这家中国公司自1997年起就已为美国的制裁对象。
 
美国官员指责说，中国政府未能阻止这家曾向伊朗出售过化学武器项目的中国公司。另一家仍在向伊朗提供武器技术的中国国营公司，便是多次遭到美国制裁的中国北方集团公司。
 
美国政府官员称，中国公司出口武器和技术的主要对象，是中东地区的产油国，而这一地区是早已被西方国家列入制裁的地区。此外，中国北方集团公司还向苏丹提供了先进的武器系统，并培训该国军队去镇压南部的起义和达尔富尔省。
 
美国助理国务卿拉德马克称，中国北方集团公司就是向伊朗提供武器技术的主要供货商，尤其是在与大规模杀伤性武器有关的项目上，该公司已先后五次遭到美国政府的制裁。
 
 
 
【时事点评】在东方评论员看来，对于华盛顿指责中国“仍在继续向伊朗提供非常规式武器和军民两用技术”、这并不奇怪，奇怪的是，这次美国官员的理由竟然有这么一条：即，美官员称，中国公司出口武器和技术的主要对象，是中东地区的产油国，而这一地区是早已被西方国家列入制裁的地区。这真可谓是“只准洲官放火、不许百姓点灯”的荒唐逻辑，要知道，向“中东地区的产油国”卖武器卖得最凶的，恰恰是美国的军火商。
 

*** 华盛顿在这个时候“旧话重提”，是准备“讨价还价”的信号

然而，美国的逻辑尽管荒唐，但是，在东方评论员看来，华盛顿在这个时候“旧话重提”，不过是在故技重施：以我们的经验、象这样的指责，通常“总是发生”在华盛顿准备和北京坐下来、认真地进行“讨价还价”的信号。

换而言之，时事评论员们已经习惯了这一点，那就是，每每听到华盛顿叫嚷说中国仍然在搞武器扩散活动的指责的同时，我们总是会看到中美之间要么即将宣布有高层的会谈，要么就是中美之间已经准备开始会谈了。

在继续讨论这个话题之前，我们再来看看中国外交部发言人刘建超、在今天的记者会了都说了些什么。
 
 
 
《东方时代环球时事解读》http://www.dongfangtime.com

** 2005年3月17日外交部发言人刘建超在例行记者会上答记者问

【外交部网站消息】3月17日下午，外交部发言人刘建超主持例行记者会。

问：据报道，曾庆红副主席与切尼副总统通电话，讨论了有关世界银行的问题。中美是否就提名沃尔福威茨为世行行长事达成一致？中方对此提名持何立场？

答：昨晚，曾庆红副主席与美国副总统切尼就世行的有关问题交换了意见，也讨论了下一任世行行长人选的问题。世行作为当今最重要的国际发展援助机构，在国际多边发展援助领域开展了许多有益的工作，对全球发展事业起到了积极的推动作用。我们希望世行的新任行长能够继续为国际发展援助多做实事，多倾听发展中国家的声音，领导世行为国际发展援助作出更大贡献，推动世界经济的持续、平衡和健康发展。中方愿意与有关各方继续保持沟通与合作。
 
　
问：美国朝鲜半岛问题特使抵达上海，将与韩、日半岛问题大使就朝鲜半岛核问题进行磋商，中方将派谁参加这一磋商？将带去什么新建议？重启六方会谈问题现在有何新进展？

答：据我了解，在上海举行的这次会议是一次民间学术研讨会，由中国和美国有关学术研究机构共同举办，邀请了有关国家的官员和学者参加。关于会议具体情况，建议你向上海国际问题研究所了解。中国外交部有官员以个人身份出席会议。会议有利于各方为六方会谈的重开提出看法和建议，对恢复六方会谈是有益的。
　　中方在恢复六方会谈问题上的立场是坚定的，我们将继续为六方会谈的早日恢复作出努力。至于何时恢复，取决于各方的努力和共识。


问：今天，日本外相宣布中日就2008年停止对华日元贷款问题达成了共识，请证实。你对此有何评论？

答：我没有听说双方达成了共识的消息。关于日本对华日元贷款，中方的立场没有变化。日本对华日元贷款是特殊历史和政治背景下作出的互惠资金安排。中日双方正就有关问题进行磋商，希望双方能够从两国关系的大局出发，妥善处理有关问题。
　

问：美国国务卿赖斯即将访华，她是否会与中方谈及朝鲜半岛问题？朝鲜要求赖斯就“暴政前哨”的说法道歉，如美国道歉，中方是否认为这对早日恢复六方会谈会起到作用？第二个问题，中方对赖斯本人有何看法？

答：对于朝方的要求，美国应该采取什么样的态度，应该是美方决定的事。中方认为，坚持以对话方式和平解决朝鲜半岛核问题符合各方利益，希望有关各方作出积极努力，本着务实灵活的态度推动六方会谈的早日恢复。我相信在六方会谈过程中，通过深入的讨论，有关方面的关切会逐步得到解决。第二个问题，赖斯是美国的现任国务卿，我们愿同她一起工作，推动中美双边关系的发展及在国际和地区事务中的磋商与合作。我们期待她即将对中国的访问取得成果。
 

问：据有关报道，在朝鲜北部靠近中国边境的地方，朝鲜政府对一些蛇头进行了公开处决，中国政府方面了解有关情况吗？中国政府持何态度？　

答：我没有看到你谈到的消息，也不了解情况，无法作出评论。


问：你刚才表示中国希望与世界银行保持合作关系。下任行长可能是沃尔福威茨。沃尔福威茨曾对中国发表过一系列挑衅性的言论，中国对他担任世界银行总裁有何看法？

答：无论谁当选世界银行行长，我们都愿意同他在平等的基础上进行合作。


问：美国国务卿对把《反分裂国家法》与取消对华军售禁令联系在一起，中方对此有何评论？第二个问题，美国国务卿即将访华，中方将与之就台湾问题和《反分裂国家法》谈哪些具体问题？

答：我们已就欧盟解除对华军售禁令问题多次阐明立场，没有变化。第二个问题，赖斯博士对中国的访问还没有进行，有关消息在访问期间我会向大家介绍。
 
　　
问：苏丹达尔富尔地区局势变得更加恶劣，中国对此有何评论？是否反对国际社会对苏丹采取经济制裁？

答：联合国安理会成员国正在就达尔富尔问题进行磋商，我们认为当务之急是安理会应尽早部署在达地区的维和行动，帮助落实来之不易的《全面和平协议》。这对达尔富尔问题的解决将是有益的。


我们注意到苏丹政府已开始按照安理会有关决议要求审判有关人员，大规模侵犯人权和违反国际人道主义的行为应该受到惩处。中方希望国际社会作出积极努力，推动达尔富尔局势朝好的方向发展。


问：朝鲜中央通讯社称美国已把航空母舰调到韩国参加军事演习。中国对此举动有何评论？此举会不会导致六方会谈延迟？

答：现在朝核六方会谈遇到了一些困难和问题，正处于一种僵局。在此时刻，我们希望有关各方多做有助于早日恢复六方会谈的事情。


问：美国国务卿赖斯和印度、巴基斯坦官员进行了会谈，讨论美国、巴基斯坦和印度之间的国防合作。中方对此有何评价？　

答：我们欢迎美国同南亚各国发展友好合作关系，希望有关合作和安排能对本地区局势起到积极作用。   
 
        
【时事点评】显然，从刘建超主持这次记者会的“所问所答”中不难看出，其话题触及了“中美战略层次”多个主要问题。其中既涉及到经济层面的“合作”，但更多的是中美彼此间在国际利益上的“冲突”。
 

*** 布什让“设计伊拉克战争”的沃尔福威茨“另派用场”，何以引起欧洲人的强烈不满？

东方评论员注意到，在记者会上，有人提到了“中美是否就提名沃尔福威茨为世行行长事达成一致”的问题。沃尔福威茨是何许人也，想来大家都清楚，虽然身为学者出身，但却是位美国国防部内的新保守主义的核心人物，虽曾经在四任美国总统手下担任过官职，但却是一个极端的鹰派政治人物。

在我们看来，布什在这个时候让“设计伊拉克战争”的沃尔福威茨“另派用场”，“转行”去世行“搞经济工作”，已经引起了欧洲人的强烈不满。

东方评论员注意到，欧洲媒体已经开始指责说、这是华盛顿有意将五角大楼的“军事霸权”移植到世界银行，去搞“经济霸权、金融霸权”。然而，首席评论员则认为，上述因素当然有，但是，布什此举主要考虑恐怕并不在此。


*** 布什此举为的是“重置”美国国务院的“本来面目”

在我们看来，布什不顾欧洲人的感受，凭借美国是世行第一大股东的特权，强行向国际社会推销这位名声糟糕的沃尔福威茨，为的是“重置”美国国务院的本来面目。

众所周知，按美国的行政架构，美国的外交政策一向是由美国务院掌握，但在布什的第一任期内，鲍威尔和切尼、拉姆斯菲尔德、沃尔福威茨这一班鹰派核心层、在政策上的冲突，最终导致副切尼和五角大楼一道，事实上剥去了美国国务院的外交决策权。


*** 遭遇“中欧俄”全力阻击，迫使布什不得不考虑调整中东政策

然而“伊拉克战争”的“在军事上完胜、在政治上完败”，以及美军在期间犯下的种种恶行，令“设计这场战争、并身体力行”的五角大楼“名声扫地”，现在，华盛顿更是在中东问题遭遇“中欧俄”的全力阻击，迫使布什不得不考虑调整五角大楼“主导设计”的中东政策。
 

*** 华盛顿的这种调整仍然是属于“微调”性质的

然而，在东方评论员看来，值得强调的是，直到目前为止，华盛顿的这种调整仍然是属于“微调”性质的，即，不论是美国在“中欧俄”压力下、被迫于“中欧俄”同意让联合国大规模参与“伊拉克政治重建”，先行启动“巴以和谈”，还是让步同意“中欧俄”坚持的保留伊朗和平利用核能的权利，都不过是权宜之计，都是为了和“中欧俄”去“边谈边斗”。

我们认为，华盛顿在“反对”“台独”的高调，与“反对”“反分裂法”的低调，所形成的强烈对比，事实上，也属于配合其“微调”中东政策的一种，也不过是权家之计。
 
*** 布什有意在为其信赖的“外交家教发挥主导作用、扫清障碍

只是在这种权宜的策略下，一味喜欢“高打强攻”的五角大楼，显然不再适合制定外交政策，因此，作为布什“微调”其中东政策的必然，就是将外交决策权重置到美国国务院、让美国国务聊理所当然地成为外交政策的决策核心。

据了解，美国防部长拉姆斯菲尔德一年之内“就要走人”，而布什这时让其副手沃尔福威茨提前离职，在东方评论员看来，五角大楼的两只老鹰的“先后离去”，立刻显出一度从美国国务院那里夺过来的外交决策权的五角大楼、已经“日显式微”。这就是说，布什费这番功夫，根本就是有意在为其信赖的“外交家教”--女国务聊赖斯发挥其外交政策的主导作用、扫清障碍。

之前，东方评论员也曾经点评过另一位极端鹰派人物--美国务院的高官--博尔顿被调任联合国一事，在我们看来，这位一度在正式场合声称：联合国应该“只有一个”具否决权常任理事国（当然是指美国）、并公开声称美国应该“外交承认”台湾的外交高官，被调任联合国外交代表，这本身就非常“耐人寻味”。


*** 把博尔顿“塞进”联合国，是“准备利用”其强硬的一面去与“列国”周旋

首席评论员指出，布什把博尔顿“塞进”联合国，当然是“准备利用”其强硬的一面去与“列国”周旋，然而，要知道，联合国是个“公共场所”，是做什么事都需要“举手表决”的地方，在那里，经“伊拉克一役”、“在军事上完胜、在政治上完败”的美国人、早已经不是“一言九鼎”的了。

因此，在我们看来，到时，如果博尔顿还敢将其“决不妥协”的那一套、从美国国务院办公室里照搬到联合国的议事厅中去的话，那么，肯定会被“世界列强”的外交代表、利用联合国的“现行机制”、给“修理得够呛”。

可问题是，既然布什这样用博尔顿有被修理的风险，可为什么还要冒这个风险呢？对此，我们注意到，美国媒体的一种意见就认为，白宫之所以愿意冒这种风险，显然是在准备让极端强硬派如国务院的代表人物博尔顿、五角大楼的代表人物沃尔福威茨“暂时远离”外交决策中心，好让相对温和的、为布什所信赖的赖斯去主持外交大局。

值得一提的是沃尔福威茨的人事安排，在东方评论员看来，由于此人是伊拉克政策的制定者和推动者，因此，我们认为，随着沃尔福威茨的“转行”、伊拉克政策、迟到伊朗问题、巴以问题的决策权也就一并转到了赖斯的手中。
 

*** 两个“异曲同功之处”

在东方评论员看来，布什这样处理似乎非常得体，这种人事安排，表面上是对极端鹰派人物的“论功行赏”、安排了一个“好去处”，但实际上，由于联合国的机制所限，博尔顿就是“再怎么极端，再怎么冲动”、也翻不起大浪来。

然而，博尔顿那种不可能改变的、发自内心的“极端与冲动”，却能在联合国时时刻刻地“发出一种强硬的声音”，从而让赖斯主导下的国务院、以相对温和的方式，去与“列国”的同行们打交道。

在我们看来，这与布什在第一任期之内的，让其国务院、鲍威尔“唱红脸”，让五角大楼、拉姆斯菲尔德、沃尔福威茨“唱白脸”、向世界“兜售”其外交政策 的模式，有着异曲同功之处。

还有，另一个异曲同功之处在于布什似乎有意将“唱白脸”的“角色安排”、从军事、外交领域扩散到经济领域，这就是说，一旦沃尔福威茨果真上就任世界银行行长这一要职，那么，这本身就意味着，美国有意在经济层面上也能“发出一种强硬的声音”。


*** 北京对华盛顿的这一套人事任命“有想法”，外交部发言人“话中带话”早早打起了“预防针”

东方评论员认为，对世界银行而言，从专业角度上看，沃尔福威茨是否胜任世界银行行长这一重任可能有点问题，然而，对白宫而言，从美国利益的角度去看，沃尔福威茨一定会非常尽心地利用手中的权力，为华盛顿的外交政策、用经济手段“继续唱好白脸”这一角色。

在我们看来，和欧洲一样，北京对华盛顿的这一套人事任命“多少有点想法”，因此，也是早早地就打起了“预防针”，我们注意到，曾庆红副主席与美国副总统切尼就世行的有关问题已经“交换了意见”，外交部发言人更是“话中带话”地提出“希望”，说：“希望世行的新任行长能够继续为国际发展援助多做实事”。
 
 
*** 华盛顿迫不得已而准备“有话好好说”的背后，是为了喘一口气、并寻找更好的时机“翻盘”

尽管如此，在东方评论员看来，布什的人事调动显示，起码在近期内，布什和赖斯、将更多地以一种相对温和的、愿意与“中欧俄”“有话好好说”的姿态出现在我们面前。

然而，我们必须心中有数的是，从布什“善待”、并继续重用鹰派极端核心人物的迹象来看，在华盛顿迫不得已、而准备“有话好好说”的背后，是为了暂时“喘上一口气”、并寻找更好的时机去离间、分拆“中欧俄”之间的战略协作关系，从而为日后“翻盘”寻找战略机会，以继续推进其既定的全球战略、中东计划、以及对华政策。

因此，在东方评论员看来，“中欧俄”更应该有必要利用华盛顿“被迫微整”其中东政策之机，协调好各自利益、保持最大限度地团结，不给美国以丝毫喘息的机会，从而迫使华盛顿在一系列外交政策上、“继续微调下去”。
 

*** 美国现在想喘上一口气的地方不少

显然，美国现在想喘上一口气的地方不少，在中东，有伊拉克问题、也有伊朗核问题、还有那个已经被迫启动了的“巴以和平进程”，然而，就“巴以和平进程”而言，由于这是华盛顿在“中欧俄”的压力之下、用以换取“中欧俄”同意联合国“更积极”参与伊拉克政治重建的一个先决条件。
 
 
*** 美国人担心，布什启动的“巴以和平进程”很可能导致“严重的政治后果”

在华盛顿的战略分析人士看来，布什启动的“巴以和平进程”很可能导致严重的政治后果，在我们看来，这种所谓的严重政治后果，首先就表现在它是一个远比美国的“中东民主计划”更容易推销的“中欧俄”之“中东和平计划”的重要组成部分，因此，一旦“巴以和平进程”全面走上正轨，那么，一旦以色列人品尝了“和平”带来的甜头之后，以色列政府是否还有足够的“决心和动机”为美国推销“中东民主计划”去打打杀杀？
 
如果美国的中东钢钉--以色列都融入了“中欧俄”的“中东和平计划”，可以想像的是，“中欧俄”的“中东和平计划”事实上也就离取代美国的“中东民主计划”不远了，如果这样的话，真不知道布什政府几年来、耗费金钱、损兵折将、打下伊拉克之后，究竟还能得到什么？
 

*** “中欧俄”现在要做的，就是继续逼着华盛顿，去继续推动“巴以和平进程”

因此，在东方评论员看来，在中东问题上，“中欧俄”现在要做的第一件事，就是继续逼着急于拉联合国帮忙搞定伊拉克政治重建进程的华盛顿，去继续推动“巴以和平进程”，直到不可逆转地启动“中东和平路线图”为止。
 
否则，就应该坚决反对联合国更大规模地介入伊拉克事务，从而让伊拉克的什叶派、以及一切对美国严重不满的政治势力，去继续找华盛顿的麻烦、最终不让美国人“喘哪怕是一口的气”。
 
我们认为，在台湾问题上、朝核问题上，都有不让华盛顿喘一口气的可能性，在一段有关朝鲜的新闻报道之后，我们再来谈如何在朝核问题上继续给华盛顿施加压力。

《东方时代环球时事解读》http://www.dongfangtime.com 
