# -*- org -*-

# Time-stamp: <2011-08-02 13:50:58 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

* 2005年03月14日 星期一

  

** 《反分裂国家法》获通过（全文）
   
   【人大网站】 《反分裂国家法》2005年3月14日第十届全国人民代表大会第三次会议通过

   第一条 为了反对和遏制“台独”分裂势力分裂国家，促进祖国和平统一，维护台湾海峡地区和平稳定，维护国家主权和领土完整，维护中华民族的根本利益，根据宪法，制定本法。

   第二条 世界上只有一个中国，大陆和台湾同属一个中国，中国的主权和领土完整不容分割。维护国家主权和领土完整是包括台湾同胞在内的全中国人民的共同义务。

   台湾是中国的一部分。国家绝不允许“台独”分裂势力以任何名义、任何方式把台湾从中国分裂出去。

   第三条 台湾问题是中国内战的遗留问题。

   解决台湾问题，实现祖国统一，是中国的内部事务，不受任何外国势力的干涉。

   第四条 完成统一祖国的大业是包括台湾同胞在内的全中国人民的神圣职责。

   第五条 坚持一个中国原则，是实现祖国和平统一的基础。

   以和平方式实现祖国统一，最符合台湾海峡两岸同胞的根本利益。国家以最大的诚意，尽最大的努力，实现和平统一。

   国家和平统一后，台湾可以实行不同于大陆的制度，高度自治。

   第六条 国家采取下列措施，维护台湾海峡地区和平稳定，发展两岸关系：

   (一)鼓励和推动两岸人员往来，增进了解，增强互信；

   (二)鼓励和推动两岸经济交流与合作，直接通邮通航通商，密切两岸经济关系，互利互惠；

   (三)鼓励和推动两岸教育、科技、文化、卫生、体育交流，共同弘扬中华文化的优秀传统；

   (四)鼓励和推动两岸共同打击犯罪；

   (五)鼓励和推动有利于维护台湾海峡地区和平稳定、发展两岸关系的其他活动。

   国家依法保护台湾同胞的权利和利益。

   第七条 国家主张通过台湾海峡两岸平等的协商和谈判，实现和平统一。协商和谈判可以有步骤、分阶段进行，方式可以灵活多样。

   台湾海峡两岸可以就下列事项进行协商和谈判：

   (一)正式结束两岸敌对状态；

   (二)发展两岸关系的规划；

   (三)和平统一的步骤和安排；

   (四)台湾当局的政治地位；

   (五)台湾地区在国际上与其地位相适应的活动空间；

   (六)与实现和平统一有关的其他任何问题。

   第八条 “台独”分裂势力以任何名义、任何方式造成台湾从中国分裂出去的事实，或者发生将会导致台湾从中国分裂出去的重大事变，或者和平统一的可能性完全丧失，国家得采取非和平方式及其他必要措施，捍卫国家主权和领土完整。

   依照前款规定采取非和平方式及其他必要措施，由国务院、中央军事委员会决定和组织实施，并及时向全国人民代表大会常务委员会报告。

   第九条 依照本法规定采取非和平方式及其他必要措施并组织实施时，国家尽最大可能保护台湾平民和在台湾的外国人的生命财产安全和其他正当权益，减少损失；同时，国家依法保护台湾同胞在中国其他地区的权利和利益。

   第十条 本法自公布之日起施行。

   【时事点评】说实话，在拿到“反分裂国家法”的正式文本之后，东方时代的时事评论员们普遍感觉到了“有种震憾”，即，“反分裂国家法”并没有划出“极其清楚”的“红线”，这就是说，将来“台独势力”如果真的制造了“台独重大事变”，那么，对于什么是“台独重大事变”，中国人大将通过“解释反分裂法”、而不是以“对号入座”的方式去加以认定，那么，这种“释法”加以认定、和明确划定“红线”之间到底有何不同呢？

*** 《反分裂国家法》的核心要义在什么地方

    在我们一步给出“具体观点”之前，我们还是先来看看这部已经生效了的《反分裂国家法》的核心要义在什么地方。纵观全文，不难看出，“反分裂法”的核心在于第二条，第八条。

    在东方评论员看来，第二条的重要性在三点：

    第一，在于它将“世界上只有一个中国，大陆和台湾同属一个中国、台湾是中国的一部分”这种政策性宣示，从法律上加以明确了，也就是说，正式在法律上确认了两岸关系的现状就是大陆和台湾都属于一个中国的一部分。

    第二，今后，任何与中国正式外交关系的国家，由于事实都是在确认中华人民共和国是中国的唯一合法政府的前提下，与中国建立外交关系的。所以，由于台湾是中国的一部分，在涉及台湾问题时，这些“建交国”的任何行为都有必要不与《反分裂国家法》相冲突、而中国在执行《反分裂国家法》处理台湾事务的过程中，在寻求相关国家的帮助的问题上，比如协助抓捕，并引渡“台独罪犯”、切断“台独”势力的经济来源等等、对中国和被中国要求提供帮助的建交国而言， “反独”也就“都有了”法律依据。

    第三，最后，也是最重要的，这是今后人大“释法”、鉴别是否满足“三条件”、判别是否需要采取“非和平方式”的去维护中国统一的法理根据。
 
*** 一个“动用”“非和平方式”的条件“变更”引起了我们注意

    其次，就是第八条，原文是：“台独”分裂势力以任何名义、任何方式造成台湾从中国分裂出去的事实，或者发生将会导致台湾从中国分裂出去的重大事变，或者和平统一的可能性完全丧失，国家得采取非和平方式及其他必要措施，捍卫国家主权和领土完整。

    首席评论员指出，第八条中的一个“动用”“非和平方式”的条件“变更”引起了我们注意，既“任何方式造成台湾从中国分裂出去的事实，或者发生将会导致台湾从中国分裂出去的重大事变，或者和平统一的可能性完全丧失，”

    根据与北京事先披露的“草案”进行比较，很明显，启动“非和平手段”的条件还是“三个条件”，但是， 我们不难发现，最后一条已经由“和平统一的条件完全丧失”悄然换成了“和平统一的可能性完全丧失”。

    东方评论员认为，通过这一条件的修正，不难看出“修正后”的“正式文本”，较之“草案”相比，更加体现出了一种特性，那就是“最大的弹性”。
 
*** 人大获取了一种“主观解释的便利”

    在我们看来 ，这种“最大的弹性”是指将来一旦人大有必要“释法”界定中央军委、国务院对台启用“非和平方式”“是否适当”时，更加具有“主观性”和“模糊性”。

    显然，由于《反分裂国家法》已经正式通过、且即日生效，因此，自今天起，全国人大实际上“已经正式授权”中央军委、国务院对“台独事实”或者“台独生大事变”有“当机决断”、“事后请批”的权力。

    所以，在东方评论员看来，这本质上是让中央军委、国务院今后有更大的主动性和灵活性、视国际形势的变化去“便宜行事”，而人大也可以利用这种“模糊性”来为启动”非和平方式”的正确与否，获取了一种“主观解释的便利”。
 
*** “释法界定”去取代“具体划红线”的方式，无疑更富有“进攻性”

    东方评论员认为，由于《反分裂国家法》是以一种“主观判断的”“释法界定”去取代“具体划红线”的方式，来判断是否满足启动“非和平方式”的“三条件”，在我们看来，在当前这种国际局势跌宕起伏，变幻难测的形势下，无疑更富有“进攻性”。

    尽管在之前的《东方时事解读》中，我们一再强调过“反分裂法”的立法过程也许是个“有趣的过程”，我们也一再强调过“反分裂法”的内容确定和立法进程都要“超越”台湾问题、而着眼于世界格局、紧盯着中东局势，而在内容上加以“紧松”、在进程上控制“快慢”。

    然而，我们也一直坚持认为，在具体条文上，有必要具体划定几条主要的“红线”、以防止“台独”和支持“台独”的国际势力“立刻”就进行冒险、伺机挑畔“反分裂国家法”的权威。
 
*** “反分裂法”的确是充分考虑到了内容的“紧松”问题

    事实说明，“反分裂法”的确是充分考虑到了内容的“紧松”问题，在东方评论员看来，这种“充分考虑”的结果就是将以“解释反分裂法”“第八条”的方式，去灵活界定“是否启动”“非和平方式”。

    可以这样说，这种“将释法第八条”的方式，可以说是根据国家的意志、和国际形势的具体情况，一旦北京认定有必要抢在美国决定打“台独牌”之前，提前解决台湾问题、而需要从“紧”，可以说就可以立刻启动台海战争。

    在我们看来，陈水扁稍早宣称的“台湾是主权国家、台湾主权的变更需要台湾2300万人决定”的说法，就可以解释成“和平统一的可能性完全丧失”，从而立刻启动“非和平方式”。
 
 
*** 人大“似乎有意时刻准备着”去“解释第八条”

    然而，首席评论员指出，通过人大“似乎有意时刻准备着”去“解释第八条”这点来看，如果国际形势的发展表明：华盛顿有可能在自己意识到中东战略彻底破产、反手大打“台独牌”、以冲击中国的方式、打乱“中欧俄”的战略协调、进一步压缩中日之间的战略回旋空间、从而去提前策应其全球部署；

    在这种情况下，如果北京认为暂不宜启动“非和平方式”似乎更合适的话，可以想像的是，人大将从“松”的角度去解释“第八条”。不要忘记了，“非和平方式”中除了有极端的武力攻打之外、还有经济封锁、军事封锁之类的、相对缓和的手段可供选择。
 
*** 北京也有必要视情况从“紧”去“解释第八条”

    同时，我们还应该警惕，美国或者在其中东战略全部得手之后，在完成其全球布置、完成针对中国的战略布置之后，那么，华盛顿也可能反手大打“台独牌”、利用“台独”来打断中国的正常建设、给中国制造巨大的战略困难。

    显然，为了避免这种被动的局面发生，北京也有必要视情况从“紧”去“解释第八条”。由此可见，中国立法部门和执法部门、如何去理解、解读这个“第八条”端的是要视世界局势发展而定，才能最大限度地保障中国的核心利益。
 
*** 由于没有具体的“红线”，《反分裂法》将“紧松”问题发挥到极致的同时，也是有负面作用

    然而，我们在看到《反分裂法》将“紧松”问题发挥到极致的同时，也是有负面作用的：由于没有具体的“红线”，那么，台独和支持台独的国际势力，特别是华盛顿，很可能会选择一个时机去挑畔、测试“反分裂法”的权威，为极可能启动的“两岸和谈”、甚至中东问题的谈判制造足够筹码。
 
*** 尽管吕秀莲的“这一总结”充满了“怨恨”、然而多少还显露了几分“政治素质”

    事实上，针对这种人大的“主观解释上的便利”，东方评论员注意到，在美国休斯顿过境的台湾“副总统”吕秀莲就表示出强烈不满，她说：《反分裂法》条文虽然少一条，但却一点都没有让步，并指责“中国一手掌握立法、诠释、制裁权”，还认为：条文内容全是“反独促统”的政治声明，强迫台湾接受“一中原则”。

    在我们看来，尽管吕秀莲的“这一总结”充满了“怨恨”、然而，撇去感情因素，客观地讲，她的这几句话多少还显露了几分“政治素质”。

    的确，东方评论员认为，由于北京不仅掌握着“立法权”、更重要的是有“诠释权”和“制裁权”，因此，《反分裂国家法》通过并立即生效之后，也就立刻引起了巨大的反响。

    下面，我们先通过几则消息，首先看看台湾内部的反应，之后，我们将继续这一话题。

** 陆委会回应反分裂法「谴责」大陆要求道歉

   台湾消息】据台湾媒体报道，针对中国大陆「反分裂法」，陆委会14日代表台湾当局发表声明，「谴责」中国大陆的作法，应该为此向台湾人民「忏悔」、「道歉「，同时也呼吁其它国家共同给予谴责。

   陆委会主委吴钊燮发表四点声明，声称「中华民国」主权属于台湾2300万人民，绝不容许中国大陆藉任何手段「侵犯」，任何改变都只有台湾人民有权决定。吴钊燮表示该法提供「以非和平方式处理台海问题」的法理基础，为解放军开出「并吞」台湾的「空白支票」，并要大陆向台湾人民「忏悔」。

   这份声明不但「谴责」中国大陆，更明白要求中国大陆必须道歉，否则台湾方面也不排除会采取必要措施，降低对两岸关系的不利影响。

   声明再次鼓吹所谓「台湾不隶属于中华人民共和国，中华民国与中华人民共和国共存于世且互不隶属」，并假借民意说这是「全体台湾人民」明确的共同主张；是台海长久以来的「现状」。声明还污蔑大陆是「东亚地区动荡不安的最主要根源」。

** 北京通过反分裂法马英九提“公开信”抗议

   【台湾消息】据台湾媒体报道，北京14日上午通过反分裂国家法，
   #+HTML: <b class="mark-text-1"> 台北市长马英九</b>
   #+LaTeX:{台北市长马英九}
   提公开信，表达台湾大多数人民都希望维持“中华民国”现状，但反分裂法漠视台湾主流民意，既无必要也不明智，反而激起反感，对两岸关系发展带来不必要的阴影。马英九下午还将邀集泛蓝的县市首长一起表示抗议。

   对于反分裂法14日得以通过，马英九上午提出“公开信”抗议，下午则要邀集泛蓝执政的县市首长公开抗议，并举行国际记者会。

   马英九所提出的公开信，一开始即指出，“坚持和平，对等协商－为抗议‘反分裂国家’致国际社会的公开信。”据信中指出，北京通过针对台湾而制订的反分裂国家法，这一举动，引起台湾人民强烈的反感与国际社会极大的关注，也对两岸现状投下重大变数。我们身为“中华民国”地方政府首长，为了向国际社会表达绝大多数台湾基层民众的不满与抗议，特别举行国际记者会，对国际媒体发表这封公开信。

   公开信内容指出：我们认为：大陆当局应该清楚认知，“中华民国”自1912年“开国”以来，就是“主权独立”的“国家”，迄今并未改变。事实上，台湾地区大多数人民都希望维持“中华民国”现状，少数主张“台湾独立”与“正名制宪”的人士，并不能代表台湾的主流民意。何况近月来，陈水扁曾在国际场合明白宣示“正名制宪”之不可能；“行政院”谢长廷院长也指出，政府必须遵守“一中宪法”。

   另外，台湾也有禁止主张分裂“国土”的法律。因此，大陆当局以台湾少数人的主张作为理由来制订“反分裂国家法”，明显漠视当前台湾大多数人主张维持“中华民国”现状的主流民意，既无必要，也不明智，反而激起大多数台湾人民的反感，对两岸关系的发展带来不必要的阴影。事实上，台湾坚定维持“中华民国”现状，就是解决两岸问题的关键，也是台湾朝野各党派的最大公约数。

   海峡两岸自1949年起即处于分治状态，大陆当局从未统治过台湾，目前台湾治权也不及于大陆，因此双方的政治争议应该在维持现状－也就是“大陆不武、台湾不独”—的基础上，透过双方对等协商的和平方式来解决。但今日大陆当局以单方制定国内法的方式，意图以“内部”问题窄化两岸争端，并明示可能以非和平方式处理两岸问题，对两岸的互动投下重大变数，实非必要与明智之举。对此，我们必须严正表达我们的不满与抗议。

   台海和平是东亚区域稳定与安全的关键因素，有赖海峡两岸政府真正展现追求和平的决心与具体行动。值此两岸甫因今年初春节包机合作良好而展现和解善意之际，我们呼吁两岸仍能珍惜此一难得契机，以客观冷静的态度面对问题、解决问题。“反分裂国家法”的制定固然令人感到遗憾，但我们并不愿看到两岸因此再度走向激情对抗，仍然主张尽快恢复对话，透过对等协商解决争议，以维护台湾民众的利益并符合国际社会对两岸和平的期望。

   我们希望国际社会充分了解台湾主流民意的现状，以及解决两岸问题的关键，鼓励并协助两岸双方在维持“中华民国”现状的基础上，展开和平的对等协商，为两岸人民谋求福祉，也为区域稳定作出贡献。我们也呼吁大陆当局放弃单方面以非和平手段解决两岸问题的作法。最后，我们更期待执政当局能够以更理性务实的态度，以促成两岸和平为目标，更积极推动两岸对话与协商。

   【时事点评】我们注意到，《反分裂国家法》可以说是正式通过了，今天，可以说直到现在为止，我们并没有看到陈水扁公开跳出来说点什么，就是那个不久前在前台”跳得最高”“叫得最响”的台“行政院长”，在事先已经安排有“记者招待会”将表明立场的情况下，最后竟然也是“杳无意讯”、让媒体记者白等一场。
 
  我们看到的是，就在台湾的“总统”、“行政院长”都因种种原因没有露面的情况下，却推出了这个差点被陈水扁“整编掉”的“陆委会”、来代表台湾当局发表声明，表明态度。
 
*** 吴钊燮是闭口不提“和平条文”，死死地咬住“第八条”

    从新闻中可以清楚地了解到，陆委会主委吴钊燮在所发表的“四点声明”中，充满了对“反分裂法”的攻击之辞，其手法很简单，就是“断章取义”。

    我们注意到，吴钊燮是闭口不提“反分裂国家法”中的“和平条文”，死死地咬在有关启动“非和平方式”的“第八条”上，一口咬定“该法提供'以非和平方式处理台海问题'的法理基础，为解放军开出'并吞'台湾的'空白支票'，并要大陆向台湾人民'忏悔'、'道歉'”。
 
*** 如果台独势力继续搞台独，那么，“第八条”也的确就是张“空白支票”

    在东方评论员看来，就如我们之前所说的那样，如果台独势力继续搞台独，那么，“第八条”也的确就是张“空白支票”。然而，问题是，面对这张 “空白支票”，台独的“大头目”、比如陈水扁、谢长庭为何不现身抗争、而派出一位吴钊燮在那里威胁说什么“台湾方面也不排除会采取必要措施，降低对两岸关系的不利影响”。
 
*** 吴钊燮的这句话就“说大了”

    事实上，在我们看来，吴钊燮的这句话就“说大了”：要知道，如果“台独”势力还能做得了主去“采取必要措施”，有决心去降低“两岸关系”的话，那么，我们又怎么会有机会看到那个、不仅对陈水扁、对民进党、甚至是对整个“台独”和支持“台独”国际势力都是“只失不得”的“春节包机”呢？


*** 马英九的表态，引得时事评论员们“有话要说”

    显然，“春节包机”是华盛顿逼着陈水扁放飞的，因此，
    #+HTML:<b class="mark-text-1">在台湾如何反应的问题上，真正做得了主的是华盛顿。</b>
    #+LaTeX:\red{在台湾如何反应的问题上，真正做得了主的是华盛顿。}
    因此，在我们没有看到美国方面的正式反应之前 ，东方时代的评论员们也压根就没有指望陈水扁能针对这部“反分裂国家法”、“敞开心扉”地说出个“一二三”来。

    因此，东方评论员认为，对陈水扁通过吴钊燮亮明的态度，我们“没有往心里去”，相较而言，倒是这个国民党的政治明星马英九的表态，引得时事评论员们“有话要说”。

    我们注意到，台北市长马英九在公开信中，开口闭口地大提什么“台湾大多数人民都希望维持“中华民国”现状”，大提什么“反分裂法漠视台湾主流民意”，是“既无必要也不明智，反而激起反感”。

    在东方评论员看来，就如之前所说的那样，我们早已经将马英九和宋楚瑜一样，被归之为“
    #+HTML:<b class="mark-text-1">隐性台独</b>
    #+LaTeX:\red{ 隐性台独}
    ”，并定性为“台独”的一大隐忧。
 
*** 马英九指责“大陆当局以台湾少数人的主张作为理由来制订“反分裂国家法””的意思何在？

    请大家注意这么一段：原文是，公开信内容指出：我们认为：大陆当局应该清楚认知，“中华民国”自1912年“开国”以来，就是“主权独立”的 “国家”，迄今并未改变。事实上，台湾地区大多数人民都希望维持“中华民国”现状，少数主张“台湾独立”与“正名制宪”的人士，并不能代表台湾的主流民意。何况近月来，陈水扁曾在国际场合明白宣示“正名制宪”之不可能；“行政院”谢长廷院长也指出，政府必须遵守“一中宪法”。

    另外，台湾也有禁止主张分裂“国土”的法律。因此，大陆当局以台湾少数人的主张作为理由来制订“反分裂国家法”，明显漠视当前台湾大多数人主张维持“中华民国”现状的主流民意，既无必要，也不明智。

    对这一段，东方评论员想分析的是，马英九指责“大陆当局以台湾少数人的主张作为理由来制订“反分裂国家法””的意思何在？
 
*** 我们从这位马英九的身上，再一次看到了宋楚瑜的影子

    显然，他强调“近月来，陈水扁曾在国际场合明白宣示“正名制宪”之不可能；“行政院”谢长廷院长也指出，政府必须遵守“一中宪法””这一情况在前，不难看出，这位国民党副主席、有意竞选下一任国民党主席和台湾“总统”的马英九，已经将陈水扁当局归之为“ 主张维持“中华民国”现状的主流民意”的范围内。

    这就是说，我们从这位马英九的身上，再一次看到了宋楚瑜的影子，至于马英九是否会成为宋楚瑜第二，什么时候会成为宋楚瑜第二，相信不久就会看到答案。

    东方评论员认为，在华盛顿的授意下、宋楚瑜已经和陈水扁打得火热，搞出了个“联合声明”和“十点共识”，那么，马英九或者是说国民党又准备和陈水扁一起搞出个什么花样出来呢？
 
*** “反分裂国家法”生效之后的、又一个斗争焦点

    在我们看来，马英九和陈水扁，或者说是国民党和民进党、在美国的安排与压力下，能拿出来的花样之一，恐怕就是那个我们一直挂在嘴边的“中程协议[fn:4]”了。

    然而，我们曾经说过，“中程协议”的条文不是主要问题，关键是前提条件，那就是“一中原则”，或者“九二共识“[fn:5]。因此，在我们看来，在华盛顿在全球战略被动的情况下，在在华盛顿想调整东亚布暑、以防止北京钻华盛顿的战略空子，排挤美国在亚洲利益的安排、还没有达成目的的情况下，如何拿到一个“名义上”可以保持台海几十年和平的“中程协议”，就成了“反分裂国家法”生效之后的、又一个斗争焦点。
 
*** 北京可以同意的是在“一中原则”下的“中程协议”

    东方评论员认为，尽管“反分裂法”中没有明指“两岸和谈”必须是承认“一中原则”，但是，由于胡锦涛在4日的讲话中、于“四点意见”非常明确地列明了这一条件。

    因此，可以肯定的是，就目前而言，由于国际形势复杂多变、台海和平还是比战争要容易控制，因此，北京可以同意的是在“一中原则”下的“中程协议”；

    而对于台湾而言，由于“的反分裂国家法”的巨大压力，陈水扁、宋楚瑜已经在美国的主导下、搞了个“十点共识”、承诺必须遵守“一中宪法”、而马英九又在借指责北京之余、顺带为陈水扁、宋楚瑜承诺必须遵守“一中宪法”进行“背书”。因此，在东方评论员看来，台湾的目的也很清楚，那就是，
    #+HTML:<a>在华盛顿因其战略需要暂缓台独进程的时期内，台湾各政治势力的一个共识就是：“一中宪法”下的“中程协议”。</a>
    #+LaTeX:\red{在华盛顿因其战略需要暂缓台独进程的时期内，台湾各政治势力的一个共识就是：“一中宪法”下的“中程协议”。}
 
*** 美国人要一份“中程协议”的最终目的很明确

    至于美国人，其实最终的目的很明确，那就是一个“名义上”可以确保几十年的“中程协议”，至于是否是“一中原则”已经顾不得了。

    #+HTML:<p><a>只要有了这份“中程协议”那么，一来可以借自己是唯一能控制“台独进程”的力量这一点、来压中国在全球战略上做出让步、二来借“反分裂法”去约束台独，从而尽可能地去维持一个短暂的台海和平。</a></p>
    #+LaTeX:\red{只要有了这份“中程协议”那么，一来可以借自己是唯一能控制“台独进程”的力量这一点、来压中国在全球战略上做出让步、二来借“反分裂法”去约束台独，从而尽可能地去维持一个短暂的台海和平。}

    华盛顿则可借机全力推进其中东战略，从而全力推进其全球战略。第三，也是最重要的是，那就是，华盛顿一旦在中东得手、在东亚面置完毕，那么，就可能随时鼓动“台独”撕毁“中程协议”，让“台独”成为一个彻底消耗中国实力的强大工具。
 
*** 华盛顿可以随时鼓动“台独”撕毁“中程协议”，北京也可以视情况“主观解释第八条”

    然而，现在“反分裂国家法”的正式文本却是一个以“解释第八条”为启动“非和平方式”的“弹性版本”，因此，华盛顿如想借“反分裂法”去量化“台独进程”，反倒显得没有了标准。

    也就是说，华盛顿可以随时鼓动“台独”撕毁“中程协议”，让“台独”成为一个彻底消耗中国实力的“强大工具”，而北京也可以视情况“主观解释第八条”，也可以随时启动“非和平方式”去提前解决台湾问题、从而在华盛顿的“台独时间表”之外，去提前解决“台独”，将“台独”变成美国的战略包袱，极大地干扰其全球战略计划。
 
*** “弹性版本”的“反分裂法”的通过，的确给了我们一种“震撼”，

    事实上，在东方评论员看来，这个弹性版本的“反分裂法”的通过，的确给了我们一种“震撼”，那就是，中国政府在保持“弹性”启动“非和平方式”的同时，也意味着有极大的“决心和意志”去宣示“台海必有一战”、去面对“台海必有一战”。
 
 
*** 对中国而言，一个由自己挑选时机启动的台海战争，绝对比一个由美国挑选时机的台海战争、要来得容易得多

    在这里，我们想引用温总理的一句话，他在回答一个美国记者的有关“反分裂法”的问题时说，"你可以翻开1861年贵国制定的两部反分裂法，不也是同样的内容吗？而且随后就发生了南北战争。"

    在东方评论员看来，不论是有意还是无意，这句话给人的感受很深：美国的两部反分裂法没有阻止南北战争，因此，中国的“反分裂法”很可能也阻止不了台海战争，然而，我们也有理由相信，如果“台湾必有一战”的话，那么，一个由中国自己挑选时机启动的、“主动统一中国”的台海战争，绝对比一个由美国准备好之后，再挑选时机、让台独挑起、北京被迫进行的镇压分裂势力的台海战争、要来得容易得多。

    下面，我们刚收到一则来自华盛顿的消息，在一起了解内容之后，东方评论员将就华盛顿对“反分裂法”通过之后的可能动作进行分析，并做为今天台湾部分的结束。
 



[fn:4] 中程协议
[fn:5] ”一中原则"、"九二共识"
