# -*- org -*-

# Time-stamp: <2011-08-02 22:25:43 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

#+STARTUP: indent

* 2005年5月20日 星期五

** 吴仪提议发展中日经贸关系建立自由贸易区

【东京消息】正在日本访问的吴仪副总理，就发展中日经贸关系提出了六点建议，其中有关自由贸易区、能源合作、建立钢铁等产业的联盟等内容，为中日经贸关系的发展，打开了一扇窗户。

吴仪提出的主要建议包括：

一、尽快启动中日双边自由贸易区进程，与东亚一体化进程和中日韩合作相协调；二、推进能源合作。双方应本着平等互利的原则，积极推进能源领域的交流与合作；三、促进产业战略对话。双方可在钢铁、造船、精密仪器、IT、软件等重要产业领域加强合作，进而探索建立某种形式的联盟，就产品结构、产量和发展方向进行战略协调。

进入21世纪以来，在中国成为世界上贸易增长最快的主要经济体的同时，也是全世界最活跃的建立自由贸易区的倡导者。按照自2002年正式启动的中国和东盟自由贸易区谈判，中国与东盟的印度尼西亚、马来西亚、菲律宾、新加坡、泰国和文莱等六国将在2010年建成自由贸易区(与柬埔寨、老挝、缅甸和越南四国将在2015年建成自由贸易区)。届时中国与东盟将建立世界最大自由贸易区。

中国已先后启动了与南部非洲关税同盟、海湾合作委员会，以及与澳大利亚和新西兰的自由贸易区谈判。在拉丁美洲，中国已经与智利展开自由贸易谈判。目前，中国已经启动了涉及23个国家的自由贸易区谈判。此外，中国正在与巴基斯坦等国进行自由贸易区建设的可行性研究。与印度建立自由贸易区也在考虑之中。

亚洲经济一体化的关键是中日建立自由贸易区。中国前总理朱镕基，最早于2002年11月向韩国和日本提出建立自由贸易区的主张。温家宝总理去年11月在第八次东盟与中日韩领导人会议上表示：“建立自由贸易区是经济一体化进程中不可逾越的阶段。”

考虑到中日关系目前停滞甚至有倒退危险的情况，吴仪再提自由贸易区，如果这一进程能够启动，不仅为中日关系打破僵局创造了新的空间，而且未来建立一个包括所有东亚经济体在内的亚洲共同市场，可望是顺理成章之事。

自由贸易区能为中国贸易的长久持续增长创造稳定的国际环境和安全体制。在世界贸易组织框架下的纺织品贸易自由化刚开始生效，中国纺织品出口在欧洲和美国遭遇保护主义，为中国敲响了警钟。以世贸组织为代表的全球贸易自由化，因为受到欧美利益集团的强烈反弹，而使中国的贸易环境面临诸多不确定的因素。世贸组织新一轮多边贸易谈判推动的自由化进展缓慢。同时，伴随中国对外经贸的快速发展，贸易争端数量也不断增加，贸易摩擦呈全方位扩展之势。

中国和日本，有着共同的与欧美贸易摩擦的经历。从华盛顿到布鲁塞尔，把如今的中国与上世纪八九十年代的日本相提并论已经时尚了一阵。回顾一下西方工业大国联合对日本从汇率调整到美日贸易谈判的历史，就不再奇怪中国目前所面临的处境。中国与全球第二大经济体日本建立自由贸易区，其贸易创造及从欧美市场的贸易转移，加上联手在双边和多边贸易体制上的谈判力量，将成为真正在国际贸易中与欧美抗衡的一极。我们认为，建立包括日本在内的亚洲自由贸易区，是中国实现亚洲共赢的最佳战略选择。

吴仪关于钢铁等产业建立从合作到联盟的构想，令人不禁联想起欧洲一体化的进程，正是在半个多世纪以前，从法国和德国，加上荷兰、比利时和卢森堡的“欧洲煤钢联盟”启程，逐步深化为一个欧洲共同市场。法德轴心，成为冷战时期欧洲经济一体化的“双发动机”。这一基本格局，直到今天的欧洲联盟都没有改变。



【时事点评】在之前的点评中，我们已经说过，吴仪此次访问日本，是以“交换看法”的名义去的，东方评论员认为，这实际上也是北京以日本外相访华要求中国道歉为契机、迫使日本在“维持一个可以正常交往的中日关系”和“接受一个不正常的、完全受控于美国的美日关系”之间做出了明确的选择。


显然，以小泉纯一郎被迫在国际社会面前“公开道歉”（尽管这种道歉是毫无诚意的）为标志，日本政府实际上是在北京和华盛顿的“共同威逼利诱”之下、“选择了前者”。


*** 日本用以挑衅中国的最激烈的手段不是在钓鱼岛，更不是什么“冲之鸟”，而恰恰就是在东海主权之争


在东方评论员看来，日本用以挑衅中国的最激烈的手段不是在钓鱼岛，更不是什么“冲之鸟”，而恰恰就是在东海主权之争，是日本企图以向日本企业发放东海资源勘察许可证、以准备来试探中国是否敢于“承受一个完全破裂的中日关系”的时候，遭到中国痛击的。

根据我们的观察，从日本宣称向企业勘测东海资源发放许可证、到中国方面严厉警告“这将使整个事情（中日关系）的性质发生变化”、再到国内爆发“反日”游行、“日本外相的访华败北”，最后到小泉纯一郎“公开道歉”，在很大程度上，很可能是中日关系、甚至于国际局势的一个转折点。

为了更好地说明这点问题，我们不妨再来看两则消息。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 石原慎太郎登上冲之鸟礁石并称其是“岛屿”

【东京消息】５月２０日，日本东京都知事石原慎太郎２０日下午抵达冲之鸟礁石进行“视察”，并声称该礁石是“岛屿”。

石原当天乘坐客轮抵达冲之鸟礁石，日本国土交通省官员、东京都政府官员以及记者等１００多人随行。石原在“视察”时对新闻界说，冲之鸟礁石是个“小岛”。

日本媒体指出，石原此行的目的在于表明冲之鸟礁石周围２００海里是日本专属经济区。

《联合国海洋法公约》第１２１条规定，岛屿应是高潮时高于水面的自然形成的陆地区域；不能维持人类居住或其本身的经济生活的岩礁，不应有专属经济区或大陆架。冲之鸟礁石实际上在涨潮时仅有两块床垫大小的礁石露出水面，无人居住，更无法自我维持经济活动。

中国政府曾多次表示，中日双方对冲之鸟礁石可以主张的海域的性质和范围有不同认识，双方应通过友好协商，妥善处理由此产生的问题。

** 小泉纯一郎表示并非以首相身份参拜靖国神社

【东京消息】据报道，日本首相小泉纯一郎表示，他参拜供奉甲级战犯的靖国神社，并不是以首相身份参拜，只是他个人对战时死难者致意。

小泉纯一郎出席国会一个委员会时说，他是以私人抑或官式身份参拜靖国神社，对他来说并无分别，但他说，他并无以首相身份参拜靖国神社。

这次是小泉首次澄清他参拜靖国神社的身份，他上任后曾经四次参拜，但其中最少一次他在名册上，以首相留名，并乘坐官方汽车前往神社。




【时事点评】对日本东京都知事石原慎太郎这个人，相信大家尽管都不喜欢、但却都知道有这么个人，知道他是以一本《日本可以说不》而“一举成名”的极端右翼人物。
众所周知，在石原慎太郎的脑子里，日本早已经是“天下第一”、或者是“与美国一样并列第一”，不然，日本又拿什么去对美国“说不”？


*** 中国在“务实”，日本在“务虚”

因此，眼前的景象也就别有一番情趣：一边是中国副总理吴仪访问日本、以“务实”的态度，在中日双方都可以大有作为的经济层面、大谈亚洲经济一体化，大谈中日经济合作；而另一边则是日本的刚刚“道过歉”的首相、还有这个强硬得对谁“都说不”的东京都知事，偏偏在那里“务虚”，偏偏在不可能短期内解决问题的政治层面、鼓捣些“刺耳”的声音来。


*** 什么是“冲之鸟”？

在这里，我们先来简单地介绍一下这个“冲之鸟”。所谓的“冲之鸟”位于琉球群岛以南海域，距离东京1740公里，按北京的说法，它实际上是一块岩礁，涨潮时“仅有几个平方米”大小的礁石露出水面，因此，中国认为这种“礁石”是不具备“主张专属经济区”条件的。

然而，在日本人的眼里，这个“高1米多，宽约4.6米”的“礁石”分明是个“岛屿”，而有了这个岛屿，日本就可以在其周边200海里设定自己的专属经济区。

东方评论员注意到，据石原慎太郎的发言人说，这位72岁的“潜水爱好者”打算当天在“冲之鸟”附近海域潜水，获得周围环境的“第一手资料”。

在东方评论员看来，前面已经说了，日本用以挑衅中国的最激烈的手段不是在钓鱼岛，更不是什么“冲之鸟”，而恰恰就是在东海主权之争。另外，不论如何，我们对石原慎太郎本人“坚定的右翼立场”、是毫不怀疑的，然而，也正是这一点、我们难免有些疑惑，那就是，主张“日本可以说不”的石原慎太郎、为什么不敢去更敏感些的钓鱼岛宣示主权？


*** 谁都清楚，中国可是在东海问题上雷霆一怒、才将日本外相逼到北京来的！

另外，日本不是已经宣布对日本企业发放东海资源勘测许可证了吗？而且，谁都清楚，中国可是在东海问题上雷霆一怒、才将日本外相逼到北京来的！因此，在东方评论员看来，或者“更厉害点”，为了表明强硬的决心，小泉纯一郎不如干脆让他的东京都知事、或者日本企业，拿着日本政府的放可证，一步到位，将船直接开到东海有争议的区域，直接到东海去获得周围环境的“第一手资料”！


*** 小泉纯一郎似乎“压力太大了”

由此看来，不论是又开始叫喊要拜参靖国神社的小泉纯一郎、还是这个以72岁高龄冲到“冲之鸟”、并“不顾自己安危”、潜水打探周围环境“第一手资料”的石原慎太郎、或者是已经主导日本政府的日本右翼、都不过是在那里“自演自唱”、“外强中干”罢了。

有意思的是，小泉纯一郎在事过几天后，终于又主动出来澄清是以“个人名义”参拜的，当然，就其原来立场而言，这是个小小的让步，似乎是在向北京摆摆“和解的姿态”。

但是，东方评论员也注意到，他又在另一个场合表示“他以私人抑或官式身份参拜靖国神社，对他来说并无分别”，显然，小泉纯一郎不愧是“变人”，其变脸的功夫，比起台湾的陈水扁来，是一点也差不到哪去。同样，也似乎和陈水扁最近变来变去的原因一个样，那就是“压力太大了”。


*** 这不是“做秀”是什么？

另外，就是那个石原慎太郎了，在东方评论员看来，72高龄还要千里迢迢、坐着海船去冲之鸟玩水，真可谓是“死都不惧”。俗话说得好，死都不惧，还有何惧哉？因此，在东方评论员看来，如果石原慎太郎“果真有种”，为何不在最为敏感的“东海主权”问题上做做文章？

最起码也可以登上中国声称自己有主权的，“非常敏感的钓鱼岛”上去宣示“所谓的主权”、为何偏偏选择了一个是日本说是“岛屿”、而中国偏说那只是“礁石”、在这个“岛”和“礁”都没有说清楚的“冲之鸟”去登什么“岛”、潜什么水？这不是“做秀”是什么？


*** 日本右翼的这一套做法真可谓“似曾相识”

显然，在日本经过权衡、并已经用事实证明“自己不能承受一个完全破裂的中日关系”之后，日本东京都知事石原慎太郎的“冲之鸟”之行、以及稍早的，日本将十几二十位日本人“入籍”钓鱼岛、更或是小泉纯一郎再次宣称不排除参拜靖国神社，并要求“外国不要干涉”等等，都是在那里“狂演政治秀”，在这点上，日本决策层的那种想借“恶心”中国、捞回点面子，“秀”给日本社会看的心思非常强烈。

在东方评论员看来，日本右翼的这一套做法真可谓“似曾相识”：“台独”势力搞的所谓“法理台独”、“和平台独”，其“打擦边球”的手法、“不敢却又不甘心寂寞”、总想心态和日本人今天的所做所为、不是如出一辙吗？


*** 在中日之间经过一次摊牌之后，事实上，以日本的政界和商界的冲击都是非常大的

东方评论员认为，在中日之间经过一次摊牌之后，事实上，以日本的政界和商界的冲击都是非常大的，显然，既然日本政府和经济界都认为“不能承受一个破裂的中日关系”，都有这么个“正确的态度”，那么，如何让“几近破裂”的中日关系离开目前这种“不进则退”的境地，就成了一个非常现实的问题。

因此，在我们看来，北京通过让自己的副总理访日，实际上已经摆出了一种姿态，这本质上就是在“催促”日本社会、特别是日本经济界“去敦促”日本政府，在改善中日关系上，将“正确的态度”落实到“具体的行动”中去。


*** 吴仪今天提出了“六点建议”，实际上就是一份“具体的清单”

显然，吴仪今天提出了“六点建议”，实际上就是一份“具体的清单”，也就是说，北京这是在向日本社会“广而告之”，只要“如此如此，这般这般”，中日关系自然就可以健康发展，中日之间就可以继续“经热”，中日间的许多敏感问题也就可以“继续谈”、至于一改“政冷”的僵局。

在东方评论员看来，既然“东海争端”中的“发放许可证”这一环节是日本挑畔中国的“最为敏感部分”，也是中国已经明确标定的、判断“事情（中日关系）性质变否”的红线，那么，北京的态度当然也就“非常明确”，即只要中日关系在东海问题上，在近期内不突破包括“这条红线”在内的敏感问题，那么，串日之间的许多事情、都可以坐下来“慢慢谈”。


*** 在诸如涉及领土、主权这一类高度敏感的问题上，中日间短期内是解决不了的

我们认为，中日之间可以坐下来谈的事情有许多，但是，在东方评论员看来，就目前而言，不论是美日涉及台海的军事同盟、还是钓鱼岛、更或者是根本就是一个日本“自说自话”的冲之鸟问题、以及“历史问题”、都不是个一天两天就“谈得透、争得清”的问题。

事实上，在这点上，只要看看韩国和日本之间的独岛（竹岛）之争的情况，看看日本国内右翼势力极其嚣张这一点，相信大家不难非常清楚地看出来这么一个道理，那就是，在诸如涉及领土、主权这一类高度敏感的问题上，既然短期内解决不了，那就不妨维持现状。


因此，首席评论员就指出，上述诸多问题，都是“纯政治”问题，也都是短期内“解决不了的问题”。那么，在我们看来，中国最好的做法，就是迫使日本接受如下的观点，即，中国在原则立场上是不会让步的，因此，只要日本不去碰这些原则立场、在中国的核心利益上挑起争端，那么，中国就不妨就让其“长期化”，从而不让这些短期内解决不好的问题、去维持“政冷”、去妨碍“经热”。


*** 北京“真正想谈的”恐怕只有一件，而想做的恐怕主要还是只有一件

根据我们的观察，中国似乎正是这样做的，因此，在北京有意“虚化”上述问题的同时，北京“真正想谈的”恐怕只有一件，而想做的恐怕主要还是只有一件，这就是迫使日本“从政府层面”、去推动亚洲经济一体化，从而在经济一体化的基础上，去建立亚洲共同体。

因此，在东方评论员看来，中日之间，可以说再没有比经济问题更加实际的问题了。就如新闻中所说的那样，一旦中国与日本建立起自由贸易区，其贸易创造及从欧美市场的贸易转移，加上联手在双边和多边贸易体制上的谈判力量，将成为真正在国际贸易中与欧美抗衡的一极。


*** 与欧美经济抗衡，其实也是日本的经济战略目标

事实上，说起与欧美经济相抗衡，其实也是日本一直在追求的战略目标。日本现在围绕中国市场进行的全球经济战略布局，其核心也正是为了实现这一战略目标。

在东方评论员看来，小泉纯一郎之所以在其外相访华、在中国“摊牌”后，被迫道歉，从而“选择维持中日关系”，最根本的原因就在于日本清楚这么一个事实，那就是，一旦中日关系彻底破裂，不仅中日经济都将受到重创，更关键的是，日本现在着眼于与欧、美经济竞争、甚至与将来的中国竟争的“全球经济布局”，必然早早地就彻底崩塌。

在东方评论员看来，而这正是“尽管双方都将遭到重创”，但是、中国却可以承受、而日本不能承受双方关系破裂的根本原因之所在。


*** 日本视欧美为“两极”，但欧美都没拿日本当回事

此外，还有政治层面的原因，东方评论员注意到，早在冷战结束初期，日本就立刻提出了建立“日美欧”三极世界的新观点，在我们看来，这一观点显然“没有人听进去”，结果是，从90年代初的海湾战争、到90年代未的科索沃战争，再到现在“还不算完的”伊拉克战争、美国和欧洲都在以实际行动一步步地否决了“日美欧”的“三极世界。

其中，华盛顿想的是如何谋求独霸世界，而欧洲人则热心于“建立欧洲人的欧洲”。不难看出，在日本人心目中视为“另外两极”的欧美、都在继续自己的计划，丝毫没有正眼看日本。

在东方评论员看来，事实证明，日本视欧美为“两极”，但是，它所认为的“两极”、却不约而同地都没有拿“自视为世界一极”的日本当回事。


*** “孤立的日本”、再一次感到了中日关系的重要性

特别让日本“不爽”的是，由于欧美经济结合的极其紧密，在很大程度上到了你中有我、我中有你的程度，这就使得日本企业在欧美两大市场上、在许多关键行业，在面对欧美企业联手的时候“备感艰难”。

东方评论员认为，这种“政治和经济”上的“双重失落感”、使“孤立的日本”、再一次感到了中日关系的重要性，并将“中日关系”定义成“建立一个有利于日本的国际政治、经济新秩序”的重要因素。

东方经济评论员指出，中日间的经济合作，可以说在2000年是个转折，当时，有“双重失落感”的日本、在面对欧美的“不待见”之后，看到中国加入WTO在即，日本国内对华的投资开始了“恢复”。


*** 日本不能承受中日关系破裂，不仅是政治是的需要、同时，也是经济上的需要

根据我们早年的资料，就在第二年，即2001年、在欧美出现经济同步下滑的背景下，日本对华直接投资立刻增加了“二成五”，合同金额则比上年增加了“近五成”。

在东方经济评论员看来，中国的崛起不仅带动了日本经济的复苏，而且还改变了日本经济一贯仰赖美国的状态。根据日本自己的数据，近年来，日本对美国的出口增长4%至6%，而对中国出口的增长率竟然高达20-30%。显然，以对日本而言，从根本上讲，日本不能承受中日关系破裂，不仅是政治是的需要、同时，也是经济上的需要。


*** 欧美对日本的“定位”是非常清楚的

东方评论员认为，欧美对日本的“定位”、是非常清楚的，这表现在两个方面，第一，欧美已经以“实际行动”充分地证明，他们拿“日欧美”三极论“没有当回事”；第二，欧洲人在选择抗衡美国霸权的战略合作伙伴的时候、显然在方向上与日本的判断一致，的确选择了亚洲方向。

但是、日本人“失落地看到”欧洲人的目光显然越过了“自己认为有能力的日本”，也没有停留落在华盛顿公开宣称“美国可以帮其成为大国”的印度，而是落在了美国人认为“有必要加以遏制”的中国、这些“铁的事实”实际上已经完全证明了日本的“大国梦”、不过是“自己在做梦”。


*** 日本在经济、政治上的出路

因此，在东方评论员看来，就这点而言，日本尽早地响应中国的“号召”、“尽早地”也在政府层面去推动“中日自由贸易区”、继而让东亚经济一体化走上下轨，最后带动亚洲经济一体化、亚洲共同体的建设，也不仅是日本在经济上的出路，同时，也是日本在政治上的出路。

我们认为，日本“单独成为一极”的美梦破灭，在实际上已经堵死了的情况下，日本的决策层有必要面对这一现实，将其能在世界发挥重要影响的途径建立在和中国一起、推动亚洲一体化的前程上，在这个过程中，与中国、印度、韩国、以及东盟国家一起、在形成“亚、欧、美洲”三大“政治经济体”的战略格局中、各自发挥各自的作用，这才是正确的选择。


*** 东亚经济一体化的关键就是“中日韩”能否尽快建立自由贸易区

我们知道，亚洲最有活力的地区是东亚，而中国和日本、韩国是东亚最大的三个经济体、因此，在东方评论员看来，亚洲经济一体化的关键中日韩所在的东亚经济的一体化，而东亚经济一体化的关键就是“中日韩”能否尽快建立自由贸易区。

从这中间我们不难看出，中日如果能建立自由贸易区，更是关键中的关键。由于中日经济的高度互补，也由于中国对自己的大国地位、和将来的前途充满自信，因此，在尽快建立中日自由贸易区、以至亚洲经济一体化的问题上，从来就是促进者。


*** 嘴上自信“可以说不”的日本，内心深处里对自己却“没有足够的信心”


这一点，从日本着眼于“日欧美”三极论，而最早提议推动东亚一体化，最后、却由于担心中国“抢了头彩”、其态度就立刻来了个180度大转弯，转从提议方变成阻挠方。

然而，最后看到中国与东盟搞了个“10+1”之后，就急匆匆地挤进了“10+3（中日韩）”，显然，从日本对东亚一体化态度转变的整个过程、我们可以清楚地看出，那个嘴上自信“可以说不”的日本，在内心深处根本就在自己“没有足够的信心”。

东方评论员认为，这种“没信心”的心态，一经“投射”到这些“非常实际的”政治、经济问题上，立刻就让我们看到了一个在亚洲经济一体化、东亚经济一体化问题上“心态矛盾的日本”，立刻就让我们看到了一个、因自己想主导、却又害怕中国主导了整个进程的日本、始终在那里“首鼠两端”、“进退失据”。

*** 以中日韩为主体的东亚经济一体化是“有可能性的”

在中国和韩国已经在着手解决自由贸易区的问题后，日本如何加入进来，已经成了一个日本无法回避的问题。显然，如果日本也主动、或被动地加入了进来，那就意味着日本也和韩国一样，最终选择了离美国再远一点，离中国再近一点的道路。

不难看出，以中日韩为主体的东亚经济一体化是“有可能性的”，只是，要做到这一点，日本就得抛弃重走军国主义老路的企图，而走一条“见容于”亚洲国家的和平路线，显然，这是个困难的过程。

*** 日本“必须依靠亚洲才能活下去”

首席评论员指出，我们不认为日本人会主动走上和平道路，我们也不认为日本社会会主动清算历史，然而，有一点我们必须强调，那就是，就如上面所分析的那样，日本在现在、和将来、似乎都“必须依靠亚洲才能活下去”。

显然，东方评论员认为，在欧美“不认为”日本有机会、也不会给日本机会在政治、军事上去挑战他们自己的时候，在欧美经济仍然与日本经济处于竞争性质的时候，在日本经济仍然会在相当一段时间内、与中国、韩国等亚洲国家“处于互补性质”的时候，在欧美都在努力地、将中国做为其全球经济布局一个关键区域的时候，在政治、军事上受到中美压制的日本，似乎只有着眼于将自己整合进亚洲一体化、从而赢得中、韩的信任和配合，继而在政治和经济上，找到另外一条出路。


*** 在美国和欧洲人的战略中，都想让军国主义的鬼魂、去引诱日本与中国在政治上走上对立

在我们看来，对日本而言，不论是主动、还是被迫选择和平路线、起码都是选择了“一条活路”。目前，华盛顿在潜意识里总是把中国视为未来最有可能挑战美国霸主地位的竞争者，是既想改善与中国的关系，在这个世界最大潜在市场的发展中最大限度地获取利益，并在将来与欧洲、日本、中国的经济竞争中占有利地位，又要千方百计地对中国的崛起加以遏制。

而欧洲则有点不同，因为欧洲需要中国这支力量去牵制美国的霸权。所以，欧洲人在战略上做得隐蔽得多、也狡猾得多。

然而，在东方评论员看来，在美国和欧洲人的战略中，如何以军国主义的鬼魂、去引诱日本与中国在政治上走上对立、继而在经济上对立，而自己则利用中日对立，给自己的企业抢占先机、在中国进行经济布局创造更大的机会，可以说在欧美决策层的头脑中，都占有相当重要篇幅，这一点，从欧洲，美国“都不愿意反对”日本成为常任理事国的事情中，就可以看得一清一楚。

显然，在日本，有一批人也明白这个道理，明白日本根本就没有重走军国主义老路、去充当世界一极的本钱，特别是明白日本要能活下去、日本的经济要想保持对欧美的竞争力，根本就离不开亚洲、离不开致力于亚洲经济一体化的中国经济的配合。

*** 吴仪带“六点建议”访日、本质上是以高姿态、去做日本社会的工作

不难想像，这些人正是“六点建议”的“建议对象”。东方评论员注意到，吴仪提到了“欧洲煤钢联盟”，显然，在我们看来，起码在中日争抢能源的问题上，对欧洲各国经济合作起到重大作用的、并促成一个欧洲共同市场的“欧洲煤钢联盟”、其模式是非常有借鉴意义的。

另外，如法德轴心，成为冷战时期欧洲经济一体化的“双发动机”的事实，其实也是中国、日本一起走亚洲经济一体化的过程中，可以考虑的一条道路。

在东方评论员看来，吴仪提出的“六点建议”、以及同时所做的这一番讲话，实际上可以理解为中国在做日本社会的工作，特别是日本经济界的工作。

我们认为，在中国日本间已经“有过一次摊牌”的经历、并且以日本的暂时后退为结束之后，吴仪带着“六点建议”访问日本、本质上是在以一种高姿态、去做日本社会的工作。

*** 日本保守势力、为何突然象被烫伤了一样“狂叫不已”？

非常清楚，日本一旦走上融入东亚经济一体化的道路，也就等于挖掉了日本右翼的生存根基，这就有如“两岸三通”也将彻底铲除“台独”势力的生存环境一样。

在东方评论员看来，这也是正是吴仪带着“六点建议”去日本的前后，日本首相、东京都知事等日本保守势力、突然“象被烫伤了一样”、在靖国神社、钓鱼岛、冲之鸟问题上“狂叫不已”的原因之所在。

显然，日本右翼势力的羽翼已丰的事实说明，中日间的问题不是一天就能解决的，这就需要我们讲究方法，那就是，既要有先前“摊牌”式的大棒，也要今天“以经济为重的”有胡萝卜。

下面，我们将把目光转向中东，在一则来自以色列的新闻报道之后，时事评论员将开始今天的中东部分。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
