# -*- org -*-

# Time-stamp: <2011-08-02 22:50:43 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

#+STARTUP: indent

* 2005年5月25日 星期三

** 日本政府三次言而无信行为威胁中日关系改善

【人民日报海外版文章】中国文化圣人孔子有句名言：“言必信，行必果。”日本领导人近来言行，却是言无信，行不果。

中日两国领导人上月在雅加达会晤时，胡锦涛主席就中日关系发展提出的五点主张中谈：“正确认识和对待历史，就是要把对那场侵略战争表示的反省落实到行动上，绝不再做伤害中国和亚洲有关国家人民感情的事。”小泉首相表示，日方愿根据胡主席提出的五点主张的精神，积极推进日中友好合作关系。5月16日，小泉出尔反尔，在国会答辩时公然表示，对“参拜靖国神社被说成是美化军国主义感到意外”。小泉透露，今后还将继续参拜靖国神社，至于何时前往“将做出适当判断”。此为近来日方言而无信其一。

胡锦涛主席在五点主张中谈到：“要坚持通过对话，平等协商，妥善处理中日之间的分歧，积极探讨解决分歧的办法，避免中日友好大局受到新的干扰和冲击。”小泉对此也表示赞同。然而，日本政府5月17日以回答国会议员提问的形式透露：“有18名日本国民的籍贯位于与中国有领土争议的尖阁诸岛(中国称为‘钓鱼岛及其附属岛屿’)”。日方自知“转移籍贯”这种偷偷摸摸的小动作难以从正常渠道公布，只好采用异常形式披露。此是近来日方言而无信其二。

胡锦涛主席在五点主张中谈到：“要正确处理好台湾问题。台湾问题是中国的核心利益，涉及13亿中国人民的民族感情。日本政府多次表示坚持一个中国政策，不支持‘台独’。希望日方以实际行动体现上述承诺。”日本外相町村信孝日前在纽约发表演讲时，就日美将台湾问题纳入所谓共同战略目标事声称：“不能因此认为日本的防卫线扩大到了台湾，因为台湾本来就是日美安保条约的对象，这与日本迄今对台政策没有任何不一致。”此是近来日方言而无信其三。

尽管中日关系在发展的过程中遇到了严重困难，但中方发展中日友好合作关系的方针没有改变。日方不仅没有认真落实两国领导人达成的共识，而且接连发表不利于两国关系的言论，频繁给中日关系制造新的干扰和冲击。由此我们不禁要问：小泉首相言而有信乎？（人民日报海外版）



【时事点评】在东方评论员看来，继昨天中国外交部发言人义正严辞地为小泉纯一郎“定性”之后、今天，中国官方的权威媒体《人民日报》也将小泉纯一郎定性成“言无信、行无果”之辈。

*** 日本国内媒体经过中日官方的一番口水战之后，显然开始两极分化

到今天为止，距离中日之间的爆发这场“外交风波”已经是第三天了，期间，东方评论员也一直非常关注各国媒体的反应，在我们看来，对中日之间的这场“口水战”，除了亚洲曾经遭受过日本侵略的国家外，或者是与日本相勾结的“台独”势力之外，恐怕没有哪个政府愿意出来说什么。

因此，几天来，我们的注意力一直落在各国媒体的身上，在东方评论员看来，各家媒体只要经过几天的“充分观察”、“兼听两边”之后，谁对谁错，从各国媒体的态度就可以知道个大概。

在这中间，我们特别留意日本国内的媒体，在东方评论员看来，围绕这起风波，日本国内媒体经过中日官方的一番口水战之后，显然开始两极分化。

*** 日本媒体：“导致这一局面的原本就是小泉的言行”

我们注意到，《日本经济新闻》就发表了一篇题为《中日应该停止让关系恶化》的社论。有意思的是，文章中到处可以看到中国方面的观点，即中国国家主席胡锦涛的一系列有关中日关系的重要讲话，其中既有两国首脑在雅加达会晤时，胡锦涛提出的、小泉纯一郎也同意了的、要日方遵守包括历史问题在内的“五项主张”，甚至胡锦涛在上周末接见日本自民党干事长武部勤、强烈抨击日本首相小泉纯一郎继续参拜靖国神社的谈话内容。

当然，更为重要的是，该社论的立场也“非常明确”，即：小泉纯一郎不应该在那之后的国会中继续表示“参拜靖国神社”以及“不准他国干涉参拜”等影响双方关系的发言。

此外，日本共同社昨日也刊发署名文章称，他们虽无意为中方的行为进行辩解,但是有必要明确一点，即导致这一局面的原本就是小泉的言行。


另外，我们也注意到西方媒体的反应，其中，法国著名的《回声报》就中日关系的现状、也发表文章说：日本在缓和两国的紧张气氛方面没有做任何事情。就在中国副总理吴仪访日的这一周，日本一再发生小规模的挑衅就证明了这一点。

还有，我们也注意到日本国内政治势力的不同声音，大家先看一段相关新闻报道，之后，东方时事评论员、东方经济评论员将就“中日关系”的实质、展开今天的日本部分。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 日本民主党人士批评小泉外交已走到极限

【东京消息】据共同社报道，日本民主党国会对策委员长钵吕吉雄在25日上午的记者招待会上，针对中国表明副总理吴仪取消与首相小泉纯一郎会谈的原因是“小泉关于参拜靖国神社的发言”一事，对小泉提出批评称:“若说原因在于首相的发言的话，那么小泉外交已走到极限，事态十分严峻。”

钵吕在指出“副总理突然取消会谈是失礼节”的同时，针对小泉强调说：“首相自己阻碍了同东亚各国之间的友好关系。有必要尽早结束小泉内阁。”




【时事点评】我们注意到，日本民主党国会对策委员长钵吕吉雄的一句话说得不错，那就是“（小泉纯一郎）首相自己阻碍了同东亚各国之间的友好关系。有必要尽早结束小泉内阁。”

显然，在东方评论员看来，不论是对中国、还是对日本，甚至是对整个东亚国家而言，如果有可能，当然是“尽早结束小泉内阁”

*** 中日关系是东亚最重要的一个外交关系

东方评论员曾经强调过，中日关系之所以重要，就在于它是亚洲内部、特别是东亚最重要的一个外交关系，对中国而言，一个良好的中日关系，是“顺利推动”东亚一体化的基础。

我们知道，眼下，美国的全球战略非常明了，那就是在未来几年或更长，首先稳定住东亚，然后集中力量对付中东，在解决了伊拉克问题后，再解决伊朗的核问题，从而占据中东这个“世界霸权的制高点”。

显然，稳定东亚的核心，就是要确保在这个“未来几年或更长”、在华盛顿集中经营中东的时间段内，大陆不对台湾动武。

*** “日本问题”正是中美双方全力争夺的“一个点”

东方评论员，在东亚稳定的层面上，其实并列有三大问题，即台湾、朝核问题、再就是日本定位问题。

可以这样说，尽管“连宋颠倒顺序相继登陆”出乎了华盛顿的算计，但是，直到目前为止，北京和华盛顿仍然是“各自主导了其中的一个点”：显然，在东方评论员看来，北京拿到的是“朝核问题”，而华盛顿手中仍然牢牢地控制着“台湾问题”。

不难看出，“东亚”剩下的最后一个问题就是“日本问题”，事实上，这也正是中美双方全力争夺的“一个点”。


*** 小泉纯一郎“制造卖点”、“待价而沽”

记得在上周未的东亚部分、在我们点评中日关系时，我们曾经说过，中日之间，现在集中的冲突其实都是政治层面的，也就是说，都集中反映在诸如涉及领土、主权这一类高度敏感的问题上，在我们看来，这些日本一手挑起来的“政治问题”，本身是日本右翼企图借美国遏制中国、需要日本的战略需要，一来为军国主义招魂，二来，借自己在中美两国而言，都是“身价不菲”、从而借此来要挟北京和华盛顿分别做出战略让步。

东方评论员认为，小泉纯一郎近来之所以敢对北京“登鼻子上脸”、如此极尽挑畔之能事，就在于他也在以这“一个点”而自居，并时时地“制造卖点”、以“待价而沽”，并欲借这一“侍价而沽”的过程，摸清中美两国的底牌、力图在“军事、政治大国”的问题上“有实质性的突破”。


*** 日本右翼势力之所以如此“反华”，也在于他们也看清楚了这么个事实

我们认为，日本右翼势力之所以如此“反华”，就在于他们也看清楚了这么个事实，即：看清楚了中、美都在“刻意经营”一个稳定的东亚，从而分别为自己的中国的经济问题、美国中东问题争取时间。

谁都知道，中国目前的主要任务是发展经济，因此，小泉政府也是赌中国最终会以经济为重、赌中国定会为“将极大增大中国国力”的东亚经济一体化、而于最后关头对日本让步。

因此，日本人非常相信要达目的之唯一出路、就是抢在中国进一步强大之前，赶在美国集中精力处理中东问题、而极其需要日本跳出来遏制中国的时候，毕其功于一役、从中国这个当今的大国、自己充当亚洲领导者的最大对手、而且又是在日本侵略战争中损失最大的国家身上，一举打开战略突破口。


*** 小泉纯一郎选择的突破方向也正是这个“历史问题”，

长久以来，影响日本赢得得到亚洲国家充分信任、容许日本成为一个“政治大国”的就是这个“历史问题”，就是日本如何对那场侵略战争的进行清算的“清算问题”。因此，我们也不难看出，日本右翼和小泉所代表的新一代保守势力、他们选择的突破方向也正是这个“历史问题”，其突破口就选择在借奉有发动这场战争的甲级战犯的“靖国神社”。

在这里，我们首先来谈谈日本政治人物最想从中国这里得到什么？在东方评论员看来，日本政治人物最想从中国这里得到的就是“历史问题”。办是为何中日之间在这个问题上有如此大的对立，日本的“历史问题”为什么又“如此的关键”呢？

*** “日本在本质上还算不上是个独立主权的国家”

在东方评论员看来，多年来，小泉之所以一再不顾中日关系恶化的危险、也要坚持参拜靖国神社，就在于小泉所代表的日本新一代保守政治人物、与日本经济界眼睛里盯着的东西还是“有差别的”，那就是“更加看重”“看得见、摸得着的眼前利益”，显然，在日本新一代保守政治人物的眼中、这些最显眼的、“看得到、摸得着”的东西之中、就是能成为所谓的“普通国家”。

东方评论员认为，日本之所以如此眼谗一个“普通国家”的名份，其原因说出来也挺可怜的，就在于日本本质上远不是个“普通国家”，在政治、军事政策上就受到一连串的、来自国内、外法律、和国际势力的制约，在美国的控制下、在某种意义上讲上，根本就算不上是个“独立国家”。

因此在我们看来，日本之所以如此眼谗一个“普通国家”的名份的真正原因其实就是“日本在本质上还算不上是个独立主权的国家”

*** 一个走和平路线、非常符合中国的利益

在我们看来，日本如果彻底地清算了历史，清除了日本重走军国主义老路的可能性，那么它自然可以赢得亚洲国家的信任，在这一基础上，北京其实是乐于让日本成为“普通国家”的。

道理很简单，一个走和平路线、且经济、技术力量雄厚的日本，非常符合中国的利益，也非常有助于东亚、甚至于是亚洲经济一体化的形成，从而可以加速将美国的势力挤出东亚、甚至是整个亚洲。


*** 日本右翼头脑中的“快速催成”思维

但是，我们知道，世界的保守主义者，大凡都有一个共同的毛病，那就是“目标上，总是急功近利、在手段上，从来就好走极端”。东方评论员认为，这一点“通病”，不论是在美国新、旧保守主义者、还是日本的新、旧保守主义者身上，都可谓表现得淋漓尽致。

近几年来，美国新保守主义者“一手策划”的、美国传统保守主义者“身体力行”的“伊拉克政策”、可以说从战争计划、到战后重建计划，从华盛顿决策层“执着于”用刺刀和炸弹“独霸”中东、并“强推”中东民主进程的过程，无一不体现了“急功近利、好走极端”的特征。

相比较而言，日本右翼那种欲借着日本社会也想成为”普通国家”的愿望，在变着法地想着如何才能将日本“快速催成”一个“政治、军事大国”，东方评论员认为，在日本右翼头脑中“快速催成”的思维中、更能体现出“急功近利”、好走极端”的特征。


*** 在日本保守势力的眼中，德国走的是条“慢车道”

众所周知，日本右翼有一个“坚定的梦想”，即欲重建日本军国主义当年的“辉煌”，显然，日本人不愿意象德国人那样，“以诚心清算历史赢得欧洲国家信任，一点点解开历史的包袱，从而慢慢地在欧洲、以至世界发挥越来越重要作用”，在日本保守势力的眼中，德国走的是条“慢车道”，因此，他们成天想的就是“如何驶上快车道”。

在这种“快速催成”的思维下，他们第一个要做的事情、就是要“强行地”为历史翻案，从而达到在“短期内”就彻底抛掉“历史包袱”、从而搬掉“普通国家”路上的最大的一块绊脚石。


*** 这场“日本历史观”的较量中，其实隐含了两重深层意义

东方评论员认为，中日围绕"历史认识问题"的争执和较量只是外在的表象，深层次蕴涵的“核心”、却是两国之间国家意志的“较量”。在东方评论员看来，这场“历史观”的较量中，其实隐含了两重深层意义。

首先。日本右翼心里想的，是如何独自主宰亚洲，这根本就是个“排他的国家主义”，以日本右翼所具有的“急功近利、好走极端”的特性，在日本右翼不可避免的“急功近利”中，也必然会再一次“重走极端”，严重冲击东亚的稳定。

也正因如此，在东方评论员看来，即使我们在历史认识问题让步，最后，只要中国仍然比日本强大、仍然比日本表面得更像一个亚洲的领导者，那么，也不可能带来中日关系“根本性的改善”。

从历史的教训、和事实的经验，从任何一个角度上来看，如果让日本右翼的这一所谓的“毕其功于一役”的赌博得逞了的话，那么，不论是对中国也好、对亚洲其他国家也罢，无疑如同被迫吞下一包“白粉”、看似能稍稍缓解当前的局面，但其后果却是“吸毒成瘾”、且再也无法“戒毒”。



*** 中国负有“不可替代地核心责任”

第二，在现实上，中国在全球中的地位不容置疑，在历史上，在日本侵略战争中、中国受到的伤害最大；因此在东方评论员看来，日本保守势力也非常清楚，只有从中国这里打开缺口、日本才能真正地永久性摆脱这个“历史包袱”。值得强调的是，也正是由于这种“现实”和“历史”条件，决定了在打碎日本“清算历史包袱”美梦过程中、中国负有“不可替代地核心责任”。


*** 日本右翼的另一个“如意算盘”

首席评论员更是指出、只有从中国这里打开缺口、那么、日本不仅能真正地永久性摆脱“历史的包袱”、继而实现“重建国家的目标”、更重要的是，日本右翼还能借机实现其如意算盘中的一个关键战略。

显然，既是受害最深、又是当今在亚洲最有影响的中国、一旦单纯地因顾全亚洲经济一体化之大局、而在政治责任上稍有软弱、在历史问题上有所后退，那么，在整个亚洲、特别是深受日本侵略军摧残的东南亚各国的眼中，中国这个有着联合国常任理事国的、在亚洲金融风暴中屹立不倒的、力保朝鲜不充许美国军事解决朝核问题的“负责任大国”之形象、就会立刻崩塌、而那个处心积虑地与中国争夺亚洲主导权的日本、反而就将“不战而胜”。


*** 一旦北京对日本让步，没有安全感”、韩国也就必然退回到“美日韩”同盟中去

特别值得强调的是，一旦北京对日本让步，那么，刚刚从“美日韩”同盟中松动出来的韩国，就将立刻感到没有一个坚固的、可以“借以腾挪的支点”、也就“没有安全感”、也就必然重新退回到“美日韩”同盟中去。

由此可见，日本这次显得聪明了一点，没有在冲撞中国的同时，去招惹韩国。我们注意到，这一次、韩国可以说在日本历史问题上基本上是“一声不吭”，在东方评论员看来，这就是在“于关键处”观察中国、看看北京将如何处理日本，态度是否坚决。


*** 北京这次能否再次打掉小泉纯一郎的嚣张气焰，影响将是极其深远的

首席评论员就认为，北京这次能否再次打掉小泉纯一郎的嚣张气焰，并迫使日本社会对小泉的这一套外交政策进行清算，其影响将是极其深远的。

在我们看来，它将直接关系到朝核问题的主导权，而一旦北京失去朝核问题的主导权，那么，中国不仅在东亚安全问题上无牌可打，更将令台海局势进入华盛顿的步调，道理很简单，到时，北京也将失去从“东北亚”方向启动东亚经济一体化进程的机会。

如此一来，朝鲜的经济改革无从谈起、“中朝韩俄”东北亚经济整合也就无从谈起，而靠东北亚经济整合、去催化“中日韩俄（远东）”东亚经济一体化的进程更是无从谈起。

更为糟糕的是，中国指望着用东亚经济一体化来扩展经济发展空间、并将美国挤出东亚、从而逐步分解美日军事同盟的计划也就无从谈起。在东方评论员看来，一旦到了这种地步，那么，“美日韩”同盟会重新聚合、那么，朝核问题也就将成为中国的政治经济包袱，而不是资产了，


*** 吴仪取消与小泉会面的举动，更是为了“避免向对方发出误导日本社会的错误信息”

在我们看来，以小泉纯一郎为代表的新保守势力，除非遭到重大打击，否则，是绝不会在历史教科书、南京大屠杀、靖国神社等问题上后退一步的。然而，我们想强调的是，在历史问题这个“大是大非”的问题面前，中国哪怕是一点点的让步都是不可取的、更不用说象某些“对日新思维”所说的在历史问题上可以“全面让步”的了。

对中国而言，吴仪取消与小泉会面的举动，可以说是在小泉纯一郎一连串“背信弃义”下的“迫不得已”，在我们看来，这不仅是在向日本政府表示最严正的抗议，更是为了“避免向对方发出误导日本社会的错误信息”，从而让日本社会看到问题的严重性。

*** 日本国内出现这种声音“非常值得重视”

东方评论员注意到，日本民主党今天上午对小泉提出批评称:“若说原因在于首相的发言的话，那么小泉外交已走到极限，事态十分严峻。”并强调说：“首相自己阻碍了同东亚各国之间的友好关系。有必要尽早结束小泉内阁。”

在我们看来，日本国内出现这种声音“非常值得重视”。东方评论员认为，要保持、并强化这种声音的前提，就是北京得“继续保持目前强硬”、既不再与小泉政府的高层接触。

前面说了，中日关系是亚洲最重要的一对外交关系，对中国而言，它很重要，但仍然是个局部，但对日本而言，由于日本在其他地区的政治影响力几乎没有、而它在亚洲的政治地位和影响力，更多是借助“中美日”这种三角关系而产生的，因此，可以这样说，随着中日关系的破裂，日本的“亚洲外交”也就走到头了。

也正是基于北京“关闭了与小泉政府间高层对话大门”的事实，日本民主党才得出了“小泉外交已走到极限，事态十分严峻”的结论。

*** 北京这次将“中日关系”何去何从的“球”、直接踢到了“日本社会”的脚下

首席评论员指出，现在，中日关系何去何从的“球”、再一次被北京踢到了日本一边，在我们看来，这种状况与日本外相町村信孝于4月17日访问北京时“遭中国摊牌”、逼小泉纯一郎做出明确的选择时之情景“是何等类似”！

然而，这两次之间也有不同的地方，那就是，北京已经将小泉定性为“言而无信”的“政治骗子”。显然，在东方评论员看来，就在北京“关上”与小泉政府高层的对话大门的同时，与其说中国是在“等着”看日本政府的“是何态度”，倒不如说是“等着看”日本社会、日本经济界“是何态度”来得准确。

因此，在我们看来，中国这次明显将“球”踢得更远了，将“中日关系”何去何从的“球”一脚就给直接踢到了“日本社会”的脚下。

事实上，据我们了解，日本的方方面面“都在逼”小泉纯一郎尽快拿出方案解决问题，特别是日本的经济界。下面，我们先看一则相关消息，之后，东方经济评论员将着重通过“欧美日”在汽车和IT、这两个最具代表性的行业里的竞争状况，以经济角度去解读，日本为什么承受不了一个“破裂的中日关系”？

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
