# -*- org -*-

# Time-stamp: <2011-08-04 13:10:12 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 2005年8月29日 星期一

  

** 胡锦涛访美定位：北京华盛顿“不同调”


【台湾媒体报道】据中国时报报道，中国外交部发言人孔泉八月二十五日宣布，应美国总统布什、加拿大总督克拉克森和墨西哥总统福克斯邀请，胡锦涛将于九月五日至十七日对三国进行「国是访问」，并将出席在纽约举行的联合国六十周年元首会议。

中国国家主席胡锦涛以中国最高领导人身分首次访美，美国对此次访问的定位以及接待规格备受关注。据消息人士表示，由于北京认为「面子」极为重要，双方确实在定位上有分歧；而白宫虽强调，对胡锦涛的接待规格很高，不仅享有廿一响礼炮等全军礼欢迎，也将下榻布莱尔国宾馆，但中国从头到尾坚持最高规格的「国是访问」。

中国外长李肇星谈到胡锦涛访美意义时强调，中美关系正处于重要发展时期，此行对推动中美关系在新世纪健康稳定发展具有重大意义；中美之间拥有广泛而重要的共同利益，中国愿与美方一起从战略高度和长远角度审视和处理两国关系。

这是胡锦涛成为中国国家主席以来的首次出访美国，中国一直希望美国能以「国是访问」的规格来看待。不过，一位西方外交官表示，不太讲究繁文缛节的布什，其实极少以国是访问的方式来接待外国元首，而是更喜欢藉着邀请外宾到他的克劳福农庄作客，轻松深入地交换各方面的意见、并促进私人情谊。

据悉，布什一开始就打算邀请胡锦涛到他的私人农庄作客，去年底莱斯还曾向北京透露，布什极为看重胡锦涛的访问，将会有「非常特别的安排」。消息人士透露，这「非常特别的安排」，指的就是去克劳福农庄，一度为了妥协，还提出可以做客总统官方别墅大卫营。

不过，由于国情不同，中国更重视的是「国是访问」的名分，宁可舍「克劳福农庄」。中、美双方为此僵持不下，美方认为，若是前往布什的私人农场，布、胡两人就可以在轻松的气氛中，谈上七、八个小时；但如果是很正式的白宫会面，顶多只能一、两个小时会谈，而大阵仗的国宴则只是摆摆场面、很难坦诚交换意见。

据悉，经过多次的沟通，白宫日前公布胡锦涛访问日程时仍对「国是访问」只字未提。布什政府官员强调，九月七日上午布什将在白宫南草坪为胡锦涛举行隆重欢迎仪式，包括检阅仪仗队和鸣放二十一响礼炮，随后举行正式会谈，并在会谈结束后会见记者；停留华府期间，胡锦涛被安排在布莱尔国宾馆下榻。

据指出，布什政府将胡锦涛访问视为「非常特别」的访问，其接待方式已经相当接近「国是访问」，但就是不愿名之为「国是访问」。一位知情人士表示，这是因为「一开始就没想过要安排国是访问的布什，也不愿意被北京牵着鼻子走」。

美方外交官则说，不管是「正式访问」也好、「国是访问」也罢，美国更在意的是实质，对北京最后决定不去克劳福农庄感到不解。至于中国宣布这是一次「国是访问」，这名外交官回避评论，仅强调华府将给予胡锦涛最高规格的接待。




【时事点评】在上周未的点评中，我们给出了最后一期“中俄联合军演”专题。其中、一如我们近半个月来“展开”“这个军事专题”时、所形成的“讨论习惯”一样、时事评论员、军事评论员、经济评论员在做该专题讨论早、仍然“穿插了大量”的“非军事”因素、向大家展示了这些天来围绕“和平使命2005”演绎的一幅幅“国际风云”。


*** 在最后一期“中俄联合军演”专题中、我们说过这样的一个观点

事实上，就在最后一期“中俄联合军演”专题中、我们说过这样的一个观点，即：可以说从去年年底、北京放风启动“反分裂国家法”立法进程、欲堵死美国一直在推动的“和平台独”的去路，到这次中俄联合军演为止，中间所发生的许多事情、涉及中美双方重大利益的一系列事件、可以说都是北京与华盛顿间为了将来一系列“中美间最高层级”的战略对话、所提前“做的功课”。

也正是基于这种观察结果，东方评论员认为，“中俄联合军演”其实不过是“中美俄”各自带着“强化了的”“美日军事同盟”、“上海合作组织”、“扑朔迷离的”朝核问题、伊朗核问题、巴以和平问题、伊拉克政治重建问题等等、“各自运用”自己可以利用的战略资源、为抢在9月5日之前各自完成“战略展开”、而进行的“战略意图、战略实力”的演示。

因此，我们的判断是，在经过“大国之间”这一系列的“展开”与“演示”之后、早在“去年年底就已经拟定”的这轮中美高峰对话也就到了“合议”的阶段。在东方评论员看来，中国的胡锦涛主席与美国的布什总统计划中的“年内互访”、就是这一系列“最高层级战略对话”的关键“回合”。


*** 对此次访问的“定位”上出现了一个似曾相识的“插曲”

然而，就在中美双方分别公布中国国家主席胡锦涛将在9月访美的消息之后，北京与华盛顿之间的对此次访问的“定位”上又出现了一个似曾相识的“插曲”：我们注意到，就在中国外交部发言人孔泉宣布“胡锦涛主席此行是对美国的“国事访问””之后，立刻、美国白宫发言人达菲就在一场例行记者会上、在回答同一个记者的同一个问题的过程中、以一种似乎“没有听清楚该记者的问题”、从而“答非所问”的回答、对“这次访美”给出了一个与中国外交部截然不同的“定位”。

在东方评论员看来，“该记者的问题”非常明了、即“胡主席在这次国事访问中，他能够为美国提供什么，以平息美国国内日益升高的保护主义和反中情绪？而美国又能够给中国提供什么？”，显然，这位记者关心的是中美元首之间“能谈些什么”，“并没有”明确地问此行是否属于“国事访问”。


*** 白宫发言人一连用了“三个否定句”来加以澄清

有意思的是，在电视画面中，我们注意到、白宫发言人的回答问题的神情、与回答问题的内容都显得非常耐人寻味，他的原话是：“这些资讯等临近会谈的时候再说。我不认为那是一个国事访问。没有国事访问’。没有正式的国事访问”。

不难看出，这位“久经沙场”的发言人在“回答”这个非常清楚的问题时、似乎“没能搞懂”记者提问的核心、而将回答的重点放在澄清“不是国事访问”上、而且、我们还听得清清楚楚，他可是一连用了“三个否定句”来加以澄清的。


*** 对“国事访问”这个词“过于敏感”，才有这种“别有用心”的“答非所问”

然而，在东方评论员看来，这位发言人可不是没有搞清楚重点、而是对“国事访问”这个词“过于敏感”，这才有这种“别有用心”的“答非所问”。

事实上，在东方评论员的记忆中、早在10年前、在江泽民以中国国家主席身份访美时，当时的克林顿政府就来过这么一手、在“国事访问”和“工作访问”的问题上“没事找事”。

其实，说华盛顿这是在“无事找事”也“并不确切”，在东方评论员看来，华盛顿之所以在10年后“故伎重施”、其原因也一如10年前、即中美在准备这次“高峰对话”的过程中、还有许多问题“没有准备好”；其动机也一如10年之前、华盛顿这次仍然“想主导对话的主题”。

然而，根据我们的观察，基于这次访问是在展开了一系列的“台前幕后”的较量、中美双方都做了大量的“功课”之后、都想通过这次“高峰对话”尽管可能“扬长避短”、充分发挥自己手中的筹码的优势、挤兑对方的短处的策略、东方评论员认为、尽管胡锦涛是去做客的、但也不想就这么轻易地“客随主便”地交出“议题主导权”。

因此，之前，北京一早就放出了让华盛顿“不爽”的“风声”。下面，是一则我们已经引用过的消息，为了更好地说明问题，不妨再一起回顾一番。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com




** 胡锦涛访问美国行程确定将不做客布什牧场



【东方档字NO.200508190201】据美国侨报报道，中国国家主席胡锦涛访问美国的具体日期已经确定，其专机将于9月13日下午3时半抵达纽约肯尼迪机场。出席纽约联合国总部举行的一系列庆祝活动后，胡锦涛一行将于15日晚离开纽约前往首都华盛顿，对美国进行为期三天的国事访问。

美国是胡锦涛此次美洲之行的第一站。此后，他还将对加拿大和墨西哥进行国事访问。这将是胡锦涛就任中国国家元首后，对联合国和美、加、墨等国的首次访问。2002年，他曾以中国国家副主席的身份访问过美国。

此前有消息说，美方此次可能安排胡锦涛前往布什总统在德州的克劳福德牧场做客。双方磋商的结果是，胡锦涛此次访问确定为“国事访问”，取消了作客布什牧场的计划。美方将在首都华盛顿，以红地毯、21响礼炮等最高规格接待胡锦涛。

有关人士透露，胡锦涛将于9月13日、14日和15日在纽约停留三天，主要是参加第60届联合国大会高级别全体会议，期间行程相当紧凑。该代表团在纽约期间将入住华尔道夫酒店。届时，大纽约地区侨学界将出动3000余人，在曼哈顿中城48街至51街间的几个主要路口，以高昂的口号、飘扬的国旗，夹道欢迎胡锦涛到访。

中国驻美国大使周文重日前说，美国总统布什年内将回访中国。他认为，中美两国元首的成功互访，必将推动两国关系进一步向前发展。

另悉，中国全国人大常委会委员长吴邦国抵达纽约的时间是9月6日下午。他将出席第二天在联合国总部举行的世界议会联盟议长大会。



【时事点评】资料编号显示，这是一份8月19日归档的消息。请大家注意这一段，原文是：美方此次可能安排胡锦涛前往布什总统在德州的克劳福德牧场做客。双方磋商的结果是，胡锦涛此次访问确定为“国事访问”，取消了作客布什牧场的计划。美方将在首都华盛顿，以红地毯、21响礼炮等最高规格接待胡锦涛。


*** 北京以“国事访问”为理，对“作客”布什牧场“敬谢不敏”

因此，在我们看来，要说布什“不重视”中国元首的此次访问、倒也着实冤枉他了。毕竟在之前，这位向以邀请客人去他的私人牧场作为“最高礼遇”的牛仔总统、“有确有意”邀请胡锦涛到那去“好好聊聊”、以展示他个人的“最高敬意”。

然而，北京方面则是以访问为“国事访问”为理，而对“作客”布什牧场的“好意”“敬谢不敏”的。


*** 这看似简单的“定位”问题、其实其中是“大有名堂”

也正因如此，我们注意到，美国官员似乎在“报怨”北京不懂布什的“一片诚心”。请大家注意这一段，原文是：美方外交官则说，不管是“正式访问”也好、“国事访问”也罢，美国更在意的是实质，并对北京最后决定不去布什的私人农庄“感到不解”。

显然，在东方评论员看来，按这位官员的意思，美国的“宣传策略”也就非常清楚了，即：北京所坚持的“国事访问”属“形式问题”，而华盛顿请中国元首去布什的“那个私人小农场”属“实质”问题，并因此而对北京“只注重”“形式”、而不愿意接受小布什个人风格中“最热烈的欢迎方式”去布什的小农庄一叙“感到不解”。

不过，在东方评论员看来，这位华盛顿官员的抱怨“给弄简单了”、事实上，在“是否国事访问”的问题上，华盛顿何尝不是在“注重形式”？

对此，首席评论员就一针见血地指出，这看似简单的“定位”问题、其实其中是“大有名堂”、其中的一个重要考虑因素、就是“中美日”之间的关系定位问题。


*** 我们不妨先看看什么是“国事访问”？

我们不妨先看看什么是“国事访问”，美国人又是如何定义“国事访问”的接待规格的。按国际外交上的规则，国事访问是指国家元首或政府首脑应他国元首或政府首脑的邀请对他国所进行的“正式访问”。其接待规格大致要有红地毯、并要检阅由海、陆、空三军人员组成的三军仪仗队、或由陆军人员单独组成的仪仗队；鸣礼炮二十一响等。值得强调的是，在美国、“国事访问”的接待流程中、还包括有“白宫会谈”、与“白宫晚宴”这两项。

现在，我们再来看看白宫开出的“接待方式”。按白宫官员透露的“接待细节”，我们在对照上述“外交礼仪”一一核对时、可以清楚地看到，“铺红地毡”、检阅仪仗队、鸣21响礼炮及白宫会谈这几样都不少，唯一不对的地方、就是白宫准备“以白宫午宴代替白宫晚宴”。

显然，就是这个“以白宫午宴代替白宫晚宴”的细节、就足以让布什政府可以向国内的“反华势力集团”、及其“反华同盟国”有个交待，为什么？就在于国与国之间的领导人在外交交往方式中还有个名称、即“正式访问”或者是“友好访问”，也可称“正式友好访问，而国家元首的“正式友好访问”就是所谓的“国事访问”。


*** 美国保守势力可不愿意“自己打自己的耳光”

不难看出，已经公开地将中美关系“正式定位”为“非常复杂”、而“一言难尽”的布什、以及在“中美关系非常复杂”的掩护下、一直都在“全力贩卖”众多版本“中国威胁论”的切尼、拉姆斯菲尔德一帮子人、自然很难“立刻转弯”：的确，在东方评论员看来，对美国保守势力而言，如果“一夜之间”就对中国的关系有个明确的定位、并将中国视为“友好国家”、这无异于等于在国内反华政治势力面前、在华盛顿正在极力拉拢的国际反华势力面前、在“自己打自己的耳光”。

也正有了这第一层“拿不上台面”的“潜意识”，华盛顿也就自然不愿意将这次访问定位为中国国家元首对美国进行的“正式友好访问”、也就是“国事访问”了。显然，说到这里，我们也就不难看出，到底是谁在注重形式了？


*** 华盛顿何以将中美关系“正式定位”为“非常复杂的双方关系”？

在东方评论员看来，华盛顿之所以将中美关系“正式定位”为“非常复杂的双方关系”、就是想将中美关系维持在一种即不明言“战略竞争”、也不明说是“战略伙伴”的模糊状态下。尽管华盛顿“认定”北京将来“一定会”威胁自己的的政治、军事霸权；尽管华盛顿“也认定”中美在经济上“更多是在互补”；

我们认为，白宫决策层之所以将中美关系定义为一种“非常复杂的双方关系”、就在于在华盛顿的眼里、除了中国在政治、军事上的潜在威胁外、它还有其他的敌人：事实是这样的，布什上台后、也就是美国新保守主义集团上台后，因伊拉克战争、已经令欧美关系成为二战以来最糟糕的状态；因美国推动日本发展军力、这却使2005年是美日关系“有史以来最好的时期”，而些却都给美国的外交环境带来了“得失参半”的一种局面：第一，中日关系处于正常化以来最糟糕的状态、这是“得”的一面；而与此同时，让华盛顿决策者非常不爽的是第二点，即，在美国成功地让中日关系处于“一推就倒”的境况后，它也发现“中欧关系”、“中俄”关系都处于冷战后最紧密的程度，显然，这是华盛顿感觉“失”的一面、而且是“颇为失落”的一面。


*** 为什么美国决策层感觉到“明确地定义一个敌人”是如此的困难？

因此，华盛顿又觉得“非常麻烦”、这种麻烦就表现在第三点，即，在华盛顿觉得它可以继续单纯地从政治上去打压能对美国军事霸权造成现实威胁的俄罗斯的时候，它又在面对如何应付欧洲、中国这两个被“内定”为能威胁其全球霸权的主要战略对手、麻烦的是、美国自己在经济上与这两个“政治经济实体”已经到了难分难解的地步：其中、欧洲还是能直接威胁到美国经济霸权的主要竞争对手，这一点与美国坚定的反华盟友--日本所对美国造成“现实的经济威胁”是一个样。

也正因局势是如此地复杂、美国决策层显然觉得在政治、经济、军事上的“主要威胁”不象冷战时、只来自苏联的军事威胁、集中在一个方向、非常好确定，而是来自不同方向，且还分别有前、后、缓、急、侧重不同之分，这就使得美国决策层感觉到“明确地定义一个敌人”是如此的困难，在东方评论员看来，造成这种困难的主要原因，就在于美国的“综合力量”自冷战结束后、相对各个强权而言，是相对地衰弱了、而不是加强了，而其支配全球的战略野心“仍然如故”，而为了达成这个战略目标，华盛顿就需要一个更加有效的“大国制衡”政策，、来确保各强权能够相互制衡、并以此来弥补其相对衰弱的“综合力量”，确保美国相对衰弱的“综合力量”可以继续推行其早已拟定、也不肯放弃的、意在确保其全球政治、经济、军事霸权的“全球战略”。


*** “如果华盛顿尝试将北京视为主要敌人，那么北京就是其主要敌人”

对此，首席评论员就指出，也正是因为根据这一点，我们也一早就指出，任何国家都可以出于自身战略目的、而将“中国威胁论”公开确立为国策来并加以身体力行、只有美国不行，道理就是这么简单，因为任何将中国正式确立为敌人的政策，必然遭到北京的全力反击，从而让华盛顿这套旨在借力打力、让中、欧、俄、印、日之间相互牵制的“大国制衡”政策全面失衡、显然，北京在中亚方向与俄罗斯联手、让美国军事基地限期撤离、这就是对“美国鼓吹、并论证中国威胁论”的警告，其意思就“如果华盛顿尝试将北京视为主要敌人，那么北京就是其主要敌人”，这对美国的全球战略而言，目前是绝对要极力避免的。


*** 在“是否国事访问”的问题上、双方较劲的本质

搞清楚了这些，在东方评论员看来，我们也就不难想清楚这么一个问题、那就是，在这场中国国家元首应邀访美到底是“国事访问”还是“非国事访问”的问题上，在胡锦涛已经明确不愿意接受布什的私人好意、“不方便去”布什的私人牧场、而只想按国际外交规则“公事公办”的角力中，双方较劲的本质是在让国际社会看看中美关系到底是个什么玩意，特别让是那个紧跟美国的日本看看、在日本已经将“中国威胁论”列入“正式文件”之后，却始终在玩花样，从而在美国所期望看到的“东海问题进一步恶化”、并由此确立“中日关系”彻底破裂的问题上“没有表现出最后决心”的同时，美国也一样在玩花样、也在玩一边公开兜售“中国威胁论”、一边却始终不愿意将“中国威胁论”正式确立为国策的花样。


*** 大国间相互戒备的心理，也给北京提供了一种玩“大国制衡”策略的空间

东方评论员认为，“中美日”、甚至是“中欧俄美印日”间这种相互矛盾的战略利益、相互利用、相互戒备的心理，其实也给北京提供了一种玩“大国制衡”策略的空间。因此，我们也就不难看出，在“国事访问”还是“非国事访问”的问题上搞小动作，已经成了华盛顿“向自己的盟友”表明“中国不是友好国家”之“心志”的一种“表面活”。然而，我们同样也不难看出、在这个问题的角力上、到底是谁在给谁出难题、谁在玩花样、又是谁在注重形式了？美国人说是北京、这当然不错，只是华盛顿事实上又何尝不是？

对此，首席评论员指出，如果华盛顿坚持不给北京“国事访问”的“定位”、那么、自然也就是将胡锦涛主席的这次访问“事实地视为”“非友好访问”、而既然不是“友好访问”，那么，胡锦涛在访问时，在许多美国关注的一系列重大问题上、也自然很难指望北京会有个“友好的态度”。这些问题之中、“朝核问题”就是其中的一个。

事实上，在中美外交官就“国事访问”问题上出现“暂时无法确定”的信号之后，在朝核问题“六方会谈”复会的问题上、也传来了“还会继续拖下去”的信号，在东方评论员看来，这些都是“因果相随的”。在一段来自朝鲜媒体的消息之后，东方评论员将讨论“朝鲜半岛”上的最新进展。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

