# -*- org -*-

# Time-stamp: <2011-08-04 00:07:11 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 2005年6月23日 星期四

** 朝鲜方面提出半岛无核化前提条件

【平壤消息】朝鲜劳动党中央机关报《劳动新闻》23日发表评论，表示不能接受美国提出的“先行弃核”要求，并提出，美国消除对朝鲜的核威胁、与朝鲜和平共处是实现朝鲜半岛无核化的前提条件。

　　评论说，最近，美国再度要求朝鲜“先行弃核”，似乎朝鲜“先行弃核”就是朝鲜半岛的无核化，这是无法接受的荒唐逻辑。美国的“先行弃核”是要求朝鲜解除自己的武装，这不是解决问题的正道。美国坚持朝鲜“先行弃核”，只能表明美国完全没有解决核问题的诚意。

　　评论说，朝鲜半岛无核化的实质，是使包括北南双方在内的整个朝鲜半岛成为没有核武器的地区，进而最终消除本地区的核战争危险。但只要美国不撤出部署在韩国和周边地区的核武器，核战争危险就不能消除，朝鲜半岛无核化就永远不能实现。

　　评论同时提出，“美朝和平共处是朝鲜半岛无核化的根本条件”。美国只有承认并尊重朝鲜的制度，愿意和平共处，朝美敌对关系才能转变为友好关系，才能形成有利于实现无核化的积极局面。如果美国不愿承认朝鲜的制度，不想与朝鲜共存，只想着颠覆朝鲜的制度，那么朝鲜半岛无核化就不可能实现。




【时事点评】不知道大家还记得否，在之前的一次点评中，东方评论员还专门就金正日亲口将“朝核问题以及朝鲜半岛无核化问题”“进行区分”给出过分析。

当时，朝鲜领导人金正日表示：如果条件成熟，朝鲜在下个月就可能重返六方会谈。与各方就朝核问题以及朝鲜半岛无核化的其它相关议题进行平等的协商。金正日还表示，如果朝核问题得到解决，将重新加入不扩散核武器条约，接受包括国际原子能机构核查在内的所有的国际核查。

*** 金正日学习布什“好榜样”

对上述这种说法，东方评论员当时的观点是，朝鲜没有象4月份那样，将“朝核问题”和“朝鲜半岛无核化问题”“完全等同”起来，表面上看似乎是让了一步，但实际上，也不过是朝鲜“左手制造问题、右手解决问题”的一个策略而已。

在我们看来，金正日之所以要“左手制造问题、右手解决问题”，大概也是跟着布什学的，不是吗？布什不就是昨天可以骂金正日是“暴君”、今天可以称其是“先生”的吗？赖斯不也是用“暴政前哨”和“主权国家”来轮流描绘朝鲜的吗？

*** 金正日将布什的这一套“原样操演”了一遍

然而，不论是布什如何称呼金正日，赖斯又是如何为朝鲜的国家性质“定性”，华盛顿却是始终“不改其初衷”，即：要求朝鲜无条件的“先行弃核”。

显然，在过去的这段日子里，金正日也是将布什的这一套“原样操演”了一遍：先是在4月份，也是这个朝鲜劳动党中央机关报《劳动新闻》，同样是发表了一篇评论，第一次提出这么个观点，即：“要实现朝鲜半岛的无核化，美国就必须撤走其部署在韩国及周边地区的所有核武器，彻底消除核威胁，同时必须根除韩国走核武道路的可能性”。就如我们之前所说的那样，这是朝鲜“用左手制造问题”的一步。

再就是几天前，金正日亲口将《劳动新闻》的上述结论给修正了一番，将“朝核问题以及朝鲜半岛无核化问题”给区别开来，表面上较4月份的评论让了一步，但实际上，这是朝鲜“用右手解决问题的另一步”。

非常清楚，金正日的“修正”，实际上不过是将“朝核问题”以及“朝鲜半岛无核化问题”分别列为解决“彻底朝鲜半岛无核化问题”的两个阶段，这与平壤坚持的“分阶段解决”的立场“毫无二致”，不难看出，这与华盛顿“绕来绕去”却始终“不改其初衷”，坚持朝鲜“先行去核”的手法是“如出一辙”，真可谓是“异曲同工”！

有意思的是今天，又是朝鲜劳动党中央机关报《劳动新闻》出面，同样是通过发表评论的方式，竟然将金正日的讲话也给“一举推翻”，重提4月份的“老观点”，“再次点破”朝鲜半岛无核化的实质，是使包括北南双方在内的整个朝鲜半岛成为没有核武器的地区，包括美国部署在韩国和周边地区的核武器都在考虑之列。

显然，在东方评论员看来，这个所谓的“周边国家”、是特指日本无疑。


*** 当时的背景与现在的局势有一个显著的共同点：都是中日之间斗争最为激烈的时候

首席评论员指出，事实上，如果我们将朝鲜劳动党中央机关报《劳动新闻》4月份发表评论、第一次将“朝核问题”与“朝鲜半岛无核化问题”相提并论的背景“重温一次”，那么，我们就不难发现，当时的背景与现在的局势有一个显著的共同点，即：都是中日之间斗争最为激烈的时候。

4月份，朝鲜官方的《劳动新闻》，首次明确提出“朝核问题”是“朝鲜半岛无核化问题”这一观点，在我们看来，朝鲜的“这个立场”几乎就是对北京的“朝核立场”的一个“异地解读”，众所周知，中国外交部对朝核问题的定义、从来就是“朝鲜半岛无核化问题”，从来就没有单纯的“朝鲜无核化问题”。

而那时，日本外相町村信孝刚从“北京败北”而归、而北京不仅一口回绝日本所提出的、就日本大使馆受损正式道歉的要求，反而要求日本在历史问题上先行道歉，而小泉纯一郎则在参拜靖国神社问题“死不松口”，声称要酌情考虑；

在东方评论员看来，这还不是问题的全部，更为严重的是，当时，中国还正以非常严厉的态度警告日本，暗示“日本拟对日本企业发放勘探东海资源的许可证”将使中日关系“发生质变”等等。

事实上，正是在这样一种背景下，朝鲜方面突然将“朝鲜无核化问题”与“朝鲜半岛无核化问题”之间“划等号”的。显然，在我们看来，在加上个“半岛”这两个字之后，朝鲜的朝核问题就又有了一层“新意思”，这就是《劳动新闻》4月份所“首倡的”，今天“再次重复”的立场，即：实现朝鲜半岛的无核化，应该包括美国部署在韩国的核武器、以及韩国、及周边国家的核能力问题。

*** 今天的东亚“情形”与4月份相比，是多么地类似

东方评论员认为，有了上面这些“参照系”，如果我们将今天中日间的“斗争现状”与4月份，小泉纯一郎在亚非峰会上、为求得与胡锦涛主席一见的机会、被迫就过去的侵略战争进行道歉的情况“仔细类比”的话，那么，不难看出，今天的东亚“情形”与当时是多么地类似。

第一，现在已经是6月下旬，再过几天，胡锦涛主席有可能出席G8峰会，显然，与亚非峰会时的情况类似，胡锦涛主席与小泉纯一郎又要“在同一场合、同时出现”，这样就有了第一个疑问：胡锦涛和小泉纯一郎有可能会晤吗？

第二，小泉纯一郎刚结束访韩，在东方评论员看来，在韩国，小泉纯一郎显然从“心存小九九”的卢武铉身上“赚得了点数”，再加上华盛顿的朝核政策“强硬依然”，这似乎都让小泉纯一郎“找到了自信”，从而一回到日本，就立刻再次叫嚣“将继续参拜靖国神社”，不难看出，这是公然地与北京叫板，应该也是小泉纯一郎的“殊死一搏”。

东方评论员认为，这与4月份时，日本外相町村信孝“扯着”“日本使馆受损”这面大旗，“气势汹汹”到北京“兴师问罪”的劲头、是何等地“如出一辙”。

*** 日本在重走4月份挑衅中国的老路

第三，在吴仪中断访日行程、提前回国之后，中日间的高层交流可以说是全部中断了。客观上讲，中日关系对中日双方都是重要的，而彼此为了维系一个对话渠道，非常默契的建立了一个“战略对话”渠道。

我们知道、“第一轮战略对话”就是在北京进行的，就是在吴仪提前回国之后举行的。值得强调的是，经过第一次战略对话之后，日本方面有过如下态度：今后几个月不会考虑把探勘特许权授予日本的公司。

然而，就在几天前，日本就出尔反尔、再次公开扬言，考虑将单方面地把探勘特许权授予日本的公司，这无疑又是在重走4月份挑衅中国的老路。

*** 日本的一种尴尬

首席评论员指出，近来，中日关系之所以如此地不稳定，除了日本想借助美国遏制中国的战略需要、实现自己的“大国梦”之外，还有一个重要的原因源于日本自身无法调整自己的心态，在东方评论员看来，这似乎成了日本的一种尴尬，即，一方面，日本现在越来越依靠东亚的经济发展，尤其是中国近乎爆炸性的经济增长。而另一方面，日本人突然发现他无法与这一现实相妥协，那就是中国不仅是东亚政治、军事力量最为强大的国家、也是东亚目前最为重要、也是最有活力的经济实体。

事实上，对“东亚经济一体化”的认识，日本人早在90年代初期就曾经提出过、那时的日本搞出了一个“雁行理论”，日本是头，亚洲四小龙是两翼，而庞大中国、其位置则被日本“摆到了很后很后”。

*** 在日本人设计的那套亚洲经济整合模式中，日本是牢牢占据主导权的

显然，在日本人设计的那套经济整合模式中，日本是牢牢占据着东亚、以至亚洲的政治、经济主导权的。然而，日本的这套经济整合模式，由于日本空有与美国一搏的经济力量、而没有强大的政治、军事力量护航、被美国人“用汇率武器”活生生地给压制了。

东方评论员认为，在经过长达10年的经济衰退之后，不论从什么方面看，日本精心设计的“雁行理论”，早已经成了历史、而让日本人“悲痛欲绝”的是，继被美国压制之后，真正埋葬“雁行理论”的，不是别人，正是被日本人“摆得很后很后”的中国。

*** 让日本人“非常不好意思”的一件事

事实上，正是中国的快速崛起、不仅起到了东亚经济火车头的作用，还起到了拉动世界经济的作用，甚至还让日本人“非常不好意思”的是，骄傲的日本人还发现、其被美国人搞得没有活力的经济、其“复苏”正是靠中国经济的拉动才得以实现的。

现在，世界各地都在搞经济一体化，美国在美洲圈地、欧洲是自成体系，而在亚洲、中国凭借自己的经济活力、更靠自己日益提升的政治、特别是军事实力，也在全力推动经济一体化进程。

而让日本和美国担心的是，中国的这一推动，与当年日本提出“雁行理论”有个最大的不同，那就是，中国不仅在亚洲推销着“经济一体化”，而且以一个负责任大国、且有能力负责任的“大国形象”，正在赢得许多亚洲国家的积极响应。

下面，我们先来看一条新闻报道，在报道中，我们可以看到韩国总理是如何“猛夸”中国的。之后，东方评论员将继续这一话题。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 韩国总理呼吁中韩为东北亚共同繁荣齐心协力

【北京消息】正在访华的韩国总理李海瓒今天在此间呼吁，中韩两国现在应以所建立的坚实友谊为基础，跨越双边合作的范围，为东北亚的共同繁荣集思广益、齐心协力。

六月二十二日，中国贸促会在北京组织中国经济界人士，为韩国总理李海瓒访华一行四十余人举办欢迎会。据悉，李海瓒此次应中国国务院总理温家宝邀请，于六月二十一日至二十三日对中国进行访问，这也是他二00四年六月就任总理以来首次访华。

李海瓒在欢迎会致辞中说，中国经济的迅猛发展令东北亚和平与繁荣前景更加光明。他引用中国儒家亚圣孟子语“天时不如地利，地利不如人和”，在新的东北亚时代，再好的地理条件也远不如中韩两国的紧密合作。

李海瓒说，从目前中韩两国贸易的发展势头看，两国首脑在二00三年共同商定的五年内将双边贸易额提升至一千美元的目标有望提前三年，即在今年年内实现。据悉，二00四年中韩双边贸易额突破九百亿美元，中国成为韩国第一大贸易伙伴。自二00二年以来，中国还一直是韩国第一大投资对象国。与此同时，中国企业对韩投资也在迅速发展。

二00五年，中韩双边贸易额将有望突破一千亿美元。就中韩经贸合作关系的持续快速发展，中国贸促会会长万季飞在致辞中表示，这一方面得益于两国便利的地缘条件和互补的经济结构，另一方面得益于两国相似的文化背景和历史遭遇。他同时指出，随着中国经济的快速增长和韩国产业技术的不断升级创新，两国经济合作前景将更加广阔。

李海瓒表示，为落实中韩两国全面合作伙伴关系，双方不仅在贸易、投资方面，而且要在技术交流、科学、IT、环保、交通、水产资源等各个领域不断深化面向未来的经贸合作关系。他还预祝二00八年北京奥运会和二0一0年上海世博会取得圆满成功，并希望韩国企业积极参加有关项目，为加深邻邦友谊做出贡献。

随同李海瓒出席此次欢迎会的韩国企业家代表团包括现代汽车、三星、SK等韩国知名企业高级管理层代表。中方经济界代表来自中国船舶工业集团公司、中石化、中国银行、鞍山钢铁集团等大型企业。


【时事点评】在昨天的点评中，东方评论员已经说过，“中韩”这次对话，表面上是在催促各方拿出诚意、重启六方会谈，然而，其实中韩双方真正谈的重点就是“经济”。


*** 李海瓒恰到好处地描绘了“中国的形象”

请大家注意这么一段，原文是：李海瓒在欢迎会致辞中说，中国经济的迅猛发展令东北亚和平与繁荣前景更加光明。他引用中国儒家亚圣孟子语“天时不如地利，地利不如人和”，在新的东北亚时代，再好的地理条件也远不如中韩两国的紧密合作。

非常清楚，李海瓒是左一个“新的东北亚时代”，右一个“中国经济的迅猛发展令东北亚和平与繁荣前景更加光明”，恰到好处地描绘了“中国的形象”。


*** “韩国将确保东北亚和平与繁荣前景”的希望放在了北京身上

首席评论员指出，李海瓒的这番话，其实有一个重点，在我们看来，这个重点就是“韩国公开地、将确保东北亚和平与繁荣前景”的希望放在了北京身上。显然，由于北京与华盛顿的角力，中国和美国在东亚的国家利益是“分别建立在”一个稳定、和平的东北亚、和一个不稳定、无法确保和平的东北亚的基础上的，因此，韩国出于自身的经济利益、与安全利益，“只能”将维护东北亚和平的希望放在中国身上。


*** 小泉政府似乎以为吃定了韩国、从而“据此要价”

东方评论员认为，不难看出，尽管韩国内心也在防范中国控制东北亚经济主导权、并因此想力拉日本入局、以平衡中国的影响，但是，日本近几天的“强硬表演”说明，小泉政府似乎以为吃定了韩国、从而“据此要价”、又开始在历史问题上、东海问题上挑衅中国，在“看轻”了韩国在历史问题上的压力之后，想集中力量迫使北京让步，从而将中日紧张局面“再次拉回到”4月份时的那种“一触即发”的状态。


*** 日本“这次挑衅的本钱”似乎来自韩国想“力拉日本入局”

在我们看来，日本“这次挑衅的本钱”似乎来自韩国想力拉日本入局“东北亚经济一体化”。事实上，这也正是华盛顿最感头痛的事情，因为不论是韩国还是日本，更或是澳大利亚，华盛顿这几个周围盟友，无一不在经济上、越来越大地依赖于东亚经济圈、这又在很大程度上依赖于中国经济的发展。

有意思的是，美国本身的经济稳定、也在依赖于中国的经济稳定，这就让今天的世界格局、东亚局势出现了“一种奇怪现状”。


*** “奇怪的现状”在朝核问题上可谓是表现得淋漓尽致

首席评论员就指出，这种“奇怪的现状”在朝核问题上可谓是表现得淋漓尽致：美国和日本一边享受从中国贸易中所获取的巨大利益，一边又想原封不动地保留亚洲的经济格局。


*** 美国的东亚政策有个鲜明特点，那就是“搞破坏”

因此，在东方评论员看来，朝核问题的实质实际上就是：虽然中美日越来越紧密的经济关系的确将三个国家带到一条“经济上共同发展”的船上，但是，美国的东亚政策有个鲜明特点，那就是“搞破坏”、先催动日本社会右倾化，从而破坏中国的东亚经济一体化；再通过强硬的朝核政策，将朝核问题改善可能地拖着，从而破坏东北亚稳定、达到破坏中国的“东北亚经济一体化”的目的，继而从长远角度去破坏亚洲经济一体化。

*** 朝鲜官方媒体再发评论，“再次点破”朝鲜半岛无核化实质的意图何在？

显然，美国的这套“破坏战略”，不仅与中国的利益格格不入，也与周围国家、比如说韩国、俄罗斯、东盟、甚至是日本的长远利益格格不入。

东方评论员认为，也是在这种情况下，在韩国将“确保东北亚和平与繁荣前景”的希望放在了北京身上之后，北京自然也有了筹码，从而也可以集中力量、再次敲打日本。在东方评论员看来，朝鲜在中日关系与4月份“相似的时候”，重提4月份的“朝核问题是朝鲜半岛及周围国家（日本）核问题”的立场，其“指向”是非常清楚的。

在这种情况下，朝鲜官方媒体再发评论，“再次点破”朝鲜半岛无核化的实质，是包括北南双方在内的整个朝鲜半岛、以及周围国家成为没有核武器的地区，在东方评论员看来，其意图主要有三点：


*** 在东北亚局势上，中国、韩国、朝鲜、俄罗斯恐怕就要“另起炉灶”了

第一，这本身就是在对美国的强硬朝核政策说“不”，也是意味着如果华盛顿“坚持不让步”、坚持“先行去核”这一不合理、北京也不可能同意、韩国也打心里也认为“不可”的要求的话，那么，在如何解决朝核问题的层面上、在如何稳定朝鲜半岛、整个东北亚的局势的问题上，中国、韩国、朝鲜、俄罗斯恐怕就要“另起炉灶”了。

第二，站在北京的立场上，韩国心里有“小九九”当然是个“不好的事情”，然而，如果韩国真能将日本拉进东北亚经济一体化进程，那也算是“将不好的事变成了好事”。在东方评论员看来，一旦日本加入东北亚经济一体化进程，将对美日军事同盟的“牢固度”有着重大影响。

显然，这也正是华盛顿近来对日本“狂送”胡萝卜的原因，华盛顿不是又开始支持日本“入常”了吗？而日本不也“罕见地”、公开反对美国所建议的延缓提交“四国提案”了吗？

*** 美国的新保派决心将日本变成“远东的英国”

第三，只要中国、朝鲜坚持“不让步”、绝不“先行弃核”，从而为中国保留下“打东亚核竞赛牌”的条件是非常重要的。在东方评论员看来，只要留有这张牌，那么，美国和日本之间的军事同盟、始终就陷在一种困境之中，即，华盛顿一方面想让日本成为“远东的英国”，在破坏亚洲一体化、阻碍中国崛起的过程中、起到英国今天破坏欧盟一体化、削弱欧盟时所起的“奇妙作用”，然而，美国人又心存有一个对日本军国主义的“心结”、并始终挥之不去。


*** 华盛顿在让日本“重新武装”的问题上、却总是表现得“说得比做的好听得多”

现在的情况是，美国的新保派决心将日本变成“远东的英国”，来对付朝鲜和制衡中国，然而，让美国和日本相互尴尬的是，美国和英国之间之所以可以相互信任，并成功地建立了一个亲密的战略关系，是有前提的，在东方评论员看来，这个“前提”就在于华盛顿可以放心地帮助英国进行核武装，而“这种放心”，美国人从来没有在日本人面前表现出来。不然，日本早就成了一个核国家。

*** 中日关系长期陷于困境的现实压力下，日本是有可能以“重新选择”来威胁华盛顿的

显然，这种“心结”也就始终让华盛顿决策层在让日本“重新武装”的问题上、总是表现得“说得比做的好听得多”。时间长了，在中日关系长期陷于困境的现实压力下，日本是有可能以“重新选择”来威胁华盛顿的。

东方评论员认为，在很大程度上，日本在经济上日益依赖东亚、特别是中国、已经让华盛顿感受到了威胁，事实上，如果日本敢以参与“东北亚经济一体化”、或者是“东亚经济一体”来威胁华盛顿，将起到立杆见影的效果，但是，这种尝试对日本军国主义者而言，却有极大的风险，要知道一旦参与了进去，就必然影响到日本国内政治倾向，那就很难回头的了。显然，就目前而言，由于日本政府还在日本保守势力的手中，美国人“还不认为”小泉政府敢拿这点来要挟美国。

*** 是北京迫使韩国下决心不顾美国的反对启动朝鲜半岛经济整合的时候了

在我们看来，韩国在这个时候力拉日本入局似乎“太心急了点”，东方评论员的观点是，在朝鲜已经摆出了尽可能多的善意之后，在华盛顿仍然不放弃强硬、死抱“先行弃核”的情况下，是时候了，是北京迫使韩国下决心不顾美国的反对启动朝鲜半岛经济整合的时候了。毕竟朝鲜半岛经济整合、对韩国经济的深化发展有着“非常关键的意义”。

首席评论员的观点是，朝鲜“再次点破”朝核问题实质，也有着逼迫韩国丢掉幻想的意图在里面。

东方评论员认为，如果我们从这个角度去看朝鲜“再显强硬”、将几天以来在韩国的努力下、对美国开出的“优惠条件”“悉数收回”，有可能就是“朝核问题”从单纯的政治问题转向为经济问题的开始，如果是这样的话，华盛顿将发现、如果想阻止这一进程的话，就必须有足够的力量阻止韩国、打消卢武铉“民族统一”的决心。然而，这就必然开罪于整个韩国社会，在这点上，韩国国内的亲美势力、恐怕很难公开加以配合。

*** 如果华盛顿阻止不了卢武铉，那么，它将发现自己手中的牌非常有限

因此，在东方评论员看来，如果华盛顿做不到这一点，阻止不了卢武铉维护国家、本民族长远利益的决心，那么，它将发现自己手中的牌非常有限，一是“台独牌”、再就是军事打击朝鲜，除此以外，华盛顿不仅几乎没有牌可打、还得经常承受来自日本的、以也要“加入东北亚经济一体化、重登朝鲜半岛、从而与俄罗斯战略接近”、来对华盛顿的进一步削弱俄罗斯、独霸全球的全球战略加以威胁。

就在中美隔着太平洋交手的同时，俄罗斯在东亚问题上也有了动作，下面，我们先来看一条来自莫斯科的新闻报道，之后，东方时事评论员、经济评论员将继续这一话题、谈谈俄罗斯在远东地区的“一个举动”、又意味着什么。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
