# -*- org -*-

# Time-stamp: <2011-08-02 19:24:07 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

#+STARTUP: indent

* 2005年01月10日 星期一


** 两岸原则同意以对飞多点不停站方式春节包机

【北京消息】 国台办主任陈云林今日上午在钓鱼台国宾馆，接见了到北京洽谈春节包机事宜的国民党立委访问团。外电引述访问团成员之一的国民党立委章孝严表示，双方同意春节包机可以双方对飞、多点及不停站的形式，通航点超出预期，拟扩大至北京、上海、厦门、广州和深圳。双方下午会继续会谈，磋商细节。
 
稍早报道：两岸包机料今日公布 章孝严盼燕重来春不远
 
陈云林表示，只要是有利于台湾同胞的事，大陆都愿意努力去做，如果台湾当局真正顾及广大台湾同胞的利益，言而有信、采取灵活务实的做法，这次台商春节包机完全可以实现。
 
陈云林指出，两岸在2003年首次有包机，是双方做了一件实在的事情，预料双方这次也会着力推动。
 
新华社引述陈云林在会见中谈话称，台湾有关部门已表态2005年台商春节包机可以采取“双向、对飞、不中停第三地的方式。对于此，大陆方面也希望2005年春节包机按广大台湾同胞和航空公司所期待的，实现「共同参与、多点开放、直接对飞、双向载客”。
 
 
 
【时事点评】在东方评论员看来，这一次国民党立委章孝严可以说又一次抢了“镜头”，但是，对“春节包机”“能否成为最终成为事实”，恐怕现在就要下结论还为时尚早！
 

*** 陈水扁为什么“大度地”同意大陆、与台湾的国民党来出这个风头？
 
在整个事情中，如果我们仔细观察，那么，就不难看到这么一个问题，即：陈水扁为什么在中国全国人大常委会刚审完“反分裂国家法”草案，在准备就“反台独”赋予中央政府以实实在在的、看得见摸得着的法律依据的时刻，还“大度地”同意大陆、与台湾的国民党来出这个风头？

我们注意到，之前，国台办提出的春节台商包机是强调“十六字原则”，即﹕“共同参与、多点开放、直接对飞、双向载客”。但是，在东方评论员看来，这个“十六字原则”不过是“手段”，而远远不是“目的”，我们认为，单纯地从北京提出这个“十六字原则”本身、是看不到有什么“政治”含义，因此，“台独”就是想反对、也不能从“十六字原则”中去挑事。
 

*** 大陆和台湾在“春节包机”的问题上，都在“自己在打着自家的算盘”

事实上，早在国台办强调“十六字原则”之前，东方评论员就注意到，台湾陆委会也早已经表示“将争取”以“双向、对飞、不落地”的模式开办今年的春节包机，同时，台湾陆委会还一并表示说：对“多点开放”也乐观其成，因此 ，在东方评论员看来，不光是大陆在以“十六字原则”做手段，陈水扁当局也有意如此达成什么目的。

所以，在东方评论员看来，大陆和台湾之间在谈判春节包机的问题上，似乎都在“各存幻想”、“自己在打着自家的算盘”，都希望通过大陆强调的“共同参与、多点开放、直接对飞、双向载客”、或者陈水扁当局早就“乐观其成”的“双向、对飞、不落地、多点开放”来实现自己的政治目标。


*** 让方方面面都能看到中国大陆既有原则性、又有灵活性的一面

首席评论员指出，事实上，陈水扁与民进党已经将“台独进程”推进到了如此地步，如果能借“春节包机”飞出一个“两岸已经恢复谈判”、“台海已经重新缓和”的假象，还可以缓解台湾商界对陈水扁迟迟不开“两岸三通”而抱有的强烈不满，那可以说是“一石数鸟”。

对于北京，理由也很充足，如果能将两岸“春节包机”做成“国内航线的两岸直航”的敲门砖，一来可以不让一直起劲推动“春节包机”、以图笼络台商人心的台湾各派政治势力“独得其好”，最重要的还是着眼于国际社会，特别是亚洲地区、让方方面面都能看到中国大陆既有原则性、又有灵活性的一面，也就是说，北京在坚持“一中原则”阻止台独的大原则下，仍然注意着宣传自己一再强调的“和平的最大诚意”！
 

*** 这种游戏玩起来，双方就不可能“共赢”，而只可能是“零和”

显然，在东方评论员看来，尽管大陆与台湾是在各家打各家的算盘，但是，只要陈水扁不抛弃台独的企图，这种游戏玩起来，双方就不可能“共赢”，而只可能是“零和”，这就是说，在“春节包机”问题上，只有赢家和输家，根本就没有什么“双赢”的结果。

对于大陆而言，不论是手上已经拿着的“517声明”，还是现在正在起草的“反分裂国家法”，其宗旨都是非常连贯的的，那就是“止独”而不是“促统”，这就是说，不论是“两岸三通”、还是陈水扁承认“九二共识”、在目前北京“都不抱幻想”，因此，如果这次“春节包机”能“飞出一个“抛开陈水扁当局、让两岸非官方部门谈判”的模式出来，也可以算得上是“意外收获”了，因此，东方评论员认为，只要“春节包机”能按“十六字原则”、按北京认可的、“合适方式”谈成，北京是绝不会让陈水扁有机会指说大陆的不是的。
 

*** “春节包机”能否成行的关键点，是谈判的“人员构成与谈判方式”

在东方评论员看来，如此一来，一个谈判的“合适方式”也就成了“春节包机”的关键。显然，陈水扁最希望的就是“两岸官方”来谈，而北京的态度非常明确，那就是，只有回到一中原则、承认“92共识”、两岸才有可能坐下来谈，而且可以谈任何问题。

所以，“ 春节包机”由什么人来谈就成了最大的问题，而大陆所提的“十六字原则”本身根本就不是问题，因为就如前面所说的，陈水扁当局也一早就这么“希望”过，因此，我们在观察“春节包机”能否成行的关键点，就是谈判的人员构成与方式、以及最后确保对飞安全的“技术性协议”。
 

*** 大陆和台湾都有意利用这次“春节包机”的机会，来开一个“如已所愿”的好头

在东方评论员看来，谈判人员的构成与谈判的方式非常关键，这将直接导致确保对飞安全的“技术性协议”是“国际版本”还是“非国际版本”、或者干脆就是“国内版本”。显然，大陆和台湾都有意利用这次“春节包机”的机会，来开一个“如已所愿”的好头。

我们认为，这次春节包机与2003年的那一次起的作用将截然不同，很清楚，国际社会普遍接受“台独”是亚太地区和平与稳定的最大威胁，因此，尽管现在台海局势紧张，但事实毕竟没有燃起烽火，因此，现在的台海现状、自然也就成了方方面面判断今后台海是否走向战争、“谁有最大诚意确保台海和平”的“现实标准”。
 

*** 在中国“反分裂法”正式出台之前，中美在台湾问题上还有那么一点点的回旋余地

首席评论员指出，现在“反分裂法”已经启动，谁都清楚，中国人大制定“反分裂法”的目的、实际上就是北京在下定义、规定什么是台海现状，什么算“台独重大事变”，这不仅将华盛顿一再自命的、“美国有认定台海现状的权力”一把抺去，同时，更是赋予中央政府自动获得以军事手段粉碎“台独”的授权。

因此，我们不难得出这样一个结论，也就是说，不论陈水扁现在的台独进程到了哪一步，事实上都还暂时算不上什么“台独重大事变”，也就是说，在中国“反分裂法”正式出台之前，中美在台湾问题上还有那么一点点的回旋余地，也就是说，在美国中东战略“成与败”还没有完全明朗之前，起码只要华盛顿、陈水扁在“台独进程”上没有“大动作”，华盛顿还没有提前在台海与中国进行摊牌的危险。
 

*** 如果陈水扁愿意以与“92 共识”不冲突的方式来处理，那好，这次“春节包机”不会有任何问题

说到这里，我们不难看出，如何维持目前这个北京认定的这个“台湾现状”--虽然非常紧张、但还不至于兵戎相见的现状，一方面将由北京说了算，由拟定中的“反分裂法”划了哪些“红线”说了算，另一方面，是否执意要兵戎相见，则由“台独”分子自己看着办，是否执意提前摊牌、则由华盛顿自己掂量着办！

因此，在等待华盛顿、“台独”的答案的过程中，这次“春节包机”能否成行，是如何谈成的，就成了北京与华盛顿、大陆与台湾谁有最大和平诚意、谁在以最大责任去维护亚太地区和平与稳定的的评判标准。

显然，如果陈水扁愿意“回到一中原则”，或者“一下子转不过弯”、但愿意以与“92 共识”不冲突的方式来处理“诸如上类的”两岸“具体问题”，那好，这次“春节包机”在大陆方面不会有任何问题，然而，如果华盛顿和陈水扁仍然想借机、又想达到“抽离一中原则”之“利”、又想得到一个“两岸官方也愿意坐下来谈”的假象之“名”，恐怕大陆根本就不会加以考虑，最终华盛顿和陈水扁可能从这次“春节包机”中、除了一部按步就班的、或许加快进程“反分裂法”之外，什么也得不到。
 

*** 国台办显然附加了一个不起眼”硬条件

事实上，为了防止华盛顿、陈水扁继续打造“抽离一中的两岸和谈”假象，我们注意到，国台办在提出的春节台商包机“十六字原则”的同时，显然附加了一个“不起眼”的硬条件：“大陆认为可由两岸航空公司就春节包机有关技术性、业务性安排直接沟通，达成共识，作出安排，各自执行”。

在东方评论员看来，有了这么一个硬条件，陈水扁在“两岸三通”上所一直坚持的“国际版本”根本就“没了影”，但是，我们对这次能以“国内航线”的方式“对飞”也不抱希望，在我们看来，如果让“春节包机”飞出个“国内航线”来，陈水扁、“台独”和支持“台独”的国际势力、可以说在这一局中就什么也没有得到，北京反而一下子就可以让国际社会、台湾社会看清楚：在“92共识”的大原则下、完全可以处理两岸的具体问题、确保台海和和平与稳定、反过来，“台独”和支持台独的国际势力，在费心费力地挑战一中原则之后，却一下子就输了个精光，显然，仅是个“缓解台海紧张气氛、笼络台商人心”的动机，远不足以让华盛顿和陈水扁现在就同意让“春节包机”在一条“国内航线”上飞来飞去。
 

*** 陈水扁绝对不会让国民党“独出风头”

事实上，在东方评论员看来，陈水扁在这个时候突然对“春节台商包机”感兴趣，其最大的动机只是制造出“台海紧张已经缓解”的假象、我们认为，陈水扁、民进党之所以拼命搞“台独”，有两个最重要的目的，一是想借美、日的支持、将台湾从中国分割出去，实现台湾共和国的美梦，第二，则是视“台独”为陈水扁个人、以及民进党长期执政的“补药”。

现在，由于大陆已经在拟定“反分裂法”，因此，就目前来看，陈水扁、民进党想靠“台独”继续拼不久之后就要开始的台湾地方县、市长选举，继续用大举推进“台独”的策略、以将“泛蓝”割喉，显然就风险大增，因此，如何在“台独”之外寻求长期执政的办法，就成了当务之急。
 

*** 陈水扁还会全力避免让北京通过“春节包机”去打破其“台独本色”

在我们看来，一种思路自然是搞点经济，将着力点放在目前正在边缘化的台湾经济也就成了一种选择，从而笼络点人心，给国际和岛内的投资界一点信心，但这一切的前提就是“两岸缓和”。

东方评论员认为，正是有这一层考虑，陈水扁当局一方面对“春节包机”打开局面有种期待，另一方面，绝对不会让国民党“独出风头”，还有，陈水扁还会全力避免让北京通过“春节包机”去打破其“台独本色”，也就是说，如何让“春节包机”“起飞”的同时，又不让国民党得头功、还不让大陆破其“台独形象”，都是他要通盘考虑的。

值得一提的是，坚决支持“台独”的一部分既得利益集团，正是从“台独”中获利颇丰的财团，在我们看到许多台商希望“两岸三通”、心从中获利的同时，我们也应该注意到，这些个从“台独”中获利的台商、也在紧张地、以一种“敌视”的心态看待“春节包机”，而这批人也是陈水扁不能轻易得罪的。
 

*** 如果大陆坚持将“春节包机”按“92共识”的大框架来处理的话，陈水扁是一定会反抗的

因此，东方评论员认为，如果大陆坚持将“春节包机”按“国内航线”、也就是事实上按“92共识”、以及钱琪琛有关“两岸三通”的讲话之大框架来处理的话，陈水扁是一定会反抗的。

所以，为了避免大陆将这次“春节包机”飞成一个“92共识”的“实例”，又要得到“两岸已经缓解、可以坐下来商谈“的假象，陈水扁当局也就得另想办法，这办法也还真是想出来了，下面，我们就一起来看看陈水扁的“好办法”，之后，东方评论员将就“春节包机”的话题进行展开。

《东方时代环球时事解读》http://www.dongfangtime.com


** 台“国防部”出头，反对大陆航机直飞

【台湾消息】两岸春节包机直航关系到台湾防卫安全，台湾陆委会近日将邀集“国防部”等单位开会，提出因应办法。
 
台湾《自由时报》昨天引述台“国防部”官员表示，两岸海上及空中直航，不能以直接穿越台湾海峡的方式进行，否则一旦出现异状，台湾军方的反应时间最多只有五分钟，对台湾安全将有严重危害。
 
台湾“国防部”指出，大陆民航机飞往台湾可带来的安全威胁，包括大陆以民航机对台湾实施电子侦测、战机伪装伺机对台攻击、民航机掩护战机逃避台湾雷达侦测等等。
 
报道指出，绕经香港的直航，也会对台湾安全造成影响。“国防部”表示，两岸包机须以国际航线的规范进行管理，来自大陆的飞机不应直接降落台湾的地方机场，而必须降落台湾的国际机场，遵照国际航线的规范处理，才能降低台湾的安全风险。
 
 
【时事点评】我们注意到，台湾“国防部”之所以反对，理由突然是大陆民航机飞往台湾“可能会导致”台湾军方的反应时间最多只有五分钟这一“严重后果”。

显然，现在几乎已经为陈水扁掌控的台军，而其根据就是：大陆民航机飞往台湾可带来的安全威胁，包括大陆以民航机对台湾实施电子侦测、战机伪装伺机对台攻击、民航机掩护战机逃避台湾雷达侦测等等。


*** 不过是为了与大陆谈条件、而抛出的人为障碍而已！

东方军事评论员认为，如果仅从军事的角度说，台湾“国防部”的担心倒还有确实有那么一点道理，然而，如果还是从军事的角度分析的话，若真的动起手来，解放军的一线机场的军机、仅10分钟就到了台湾上空，显然，就是让台军有10分钟的反应时间又能改变大局吗？显然，陈水扁让台军出头“反对”，本来就是为了反对而反对，不过是为了与大陆谈条件、而抛出的人为障碍而已！
 

*** 华盛顿、陈水扁心里不爽的不是别的，就是那份“反分裂法”

在我们看来，陈水扁当局在大陆原则同意“春节包机”、并提出硬条件之后，显然也意识到若这样谈下去，真的有可能让这次“春节包机”按“92共识”划下的道道飞来飞去，如此一来，钱琪堔所说的“按国内事务进行两岸三通”的缺口也就这么打开了。

东方评论员认为，陈水扁当局、以及华盛顿对这一点不是看不清楚，可问题是，华盛顿之所以让陈水扁在这个时候“冒这个险”是另有所图，在我们看来，在台湾问题上，华盛顿、陈水扁心里不爽的不是别的，就是那份“反分裂法”。

在我们看来，这几天“春节包机”有些许进展，其实与台办主任陈云林以沟通“反分裂法”之名访问华盛顿，与华盛顿之间进行的“坦率交谈”有很大关系。

下面，我们就能过一则新闻报道、一起回顾一下陈云林华盛顿之行，之后，时事评论员将会继续这个话题。

《东方时代环球时事解读》http://www.dongfangtime.com


** 陈云林结束访美　反分裂法具体条文并未涉及 

【台湾消息】据台湾媒体报道，中国国务院台湾事务办公室主任陈云林结束华盛顿之行，美国政府随即向台北驻美代表处演示文稿相关内容。据了解，陈云林并没有带来《反分裂国家法》的具体内容。美方则重申一贯立场，反对片面改变现状，并希望两岸把握时机，早日重启对话。

陈云林在华府最重要的两个行程，一是四日与即将出任白宫国家安全顾问的哈德利（现为副顾问）会谈，为时半小时，国安会亚洲部门资深主任葛林也在座；一是五日与副国务卿阿米塔吉会谈，为时一小时，负责亚太事务的国务院官员也在座。
 
台湾媒体报道说，陈云林此行的主要任务是就北京拟议的《反分裂国家法》与美方沟通。事后美方使用了「坦率，信息丰富、具建设性（Candid, informative, constructive）」形容此次会谈。既称「坦率」，意味双方看法有差异。唯据称会谈过程很平和，美方问了很多问题，陈云林也多方说明中方立场，所以美国以informative形容。
 
由于美国迄今没有看到《反分裂国家法》的具体条文，因此无从「反对」，而是表达「关切」，希望两岸都不要有任何片面改变现状之举。同时美方认为，台湾立法委员选举过后，两岸情势应可走向缓和，因此华盛顿寄望两岸把握机会重开对话之门。此外美国也盼望两岸审慎，不要有任何言行把原本已经敏感的情势弄得更复杂。
 
报导指出，陈云林此行十分低调，媒体在不同地点守候多时，捕捉到他的身影合计不超过一分钟，听到他唯一的话是「谢谢，谢谢」。而且既然都属不公开行程，所以美方迎送时都是礼宾官员出面，主谈者没有出现在媒体前。
 
据了解，北京固然希望藉助美国约束台独，但毕竟认为这是中国人自己的事，所以「台办主任访美一事避免张扬」，大陆媒体全不见踪影。而面对台、港、及其它国家新闻界询问时，北京官员最常说的是「没有具体行程」。
 
至于美国，一方面仍在等待具体内容，一方面也期盼两岸审慎。当然，不论哪一方，如能就敏感议题与美国事前多方沟通，而不是拋出一个又一个意外，自是美国乐见的。这也是何以国务院官员公开说，北京积极与美国沟通，并且派人来美谘商，「美国对此表示欢迎并且认为这是有帮助的」。
 
 

【时事点评】在之前的《环球时事》中，东方评论员一再强调一点，那就是，没有任何理由认为中美之间在台湾的“实质问题”上还有什么好谈的，在我们看来，在“反分裂法”方面，陈云林也不会带去华盛顿“所期望的全文”。

东方评论员认为，北京在这个时候让台办的一把手访美、就是要和华盛顿更加坦率一点，我们的判断是，这种“坦率”是建立在中美双方、对各自的全球战略都一清二楚的基础上的。

因而、在我们看来，对中美间的这次“坦率会谈”、可以理解为一种“在中东问题上，在台湾问题上，在朝鲜问题上、如果华盛顿敢这样做，北京就将那样做”的层次。


*** 美国的对台政策仍然没有什么本质变化

此外，东方评论员注意到，对陈云林的来访，华盛顿再一次重申了其“一贯立场”，说：“反对片面改变现状，并希望两岸把握时机，早日重启对话”。显然，在我们看来，美国的对台政策仍然没有什么变化，仍然在支持陈水扁的“92会谈精神”、仍然在坚持“抽离一中原则”的“两岸和谈”。

然而，如果我们考虑到华盛顿目前的注意力全在中东方向，那么，东方评论员注意到，有分析认为，不排除这种可能，那就是，华盛顿愿意从其支持“双十致辞”和“挑畔一中原则”的立场上稍稍后退，来换取中国在“反分裂法”的立法方面、以一种或者是内容、或者是时间上的“缓和”、从而暂时让台湾问题不要“更大地促进”北京采取“更激进的手段”去挑战美国的中东战略。
 
 
*** 北京应该想办法让“反分裂法”最终“超越”台湾问题

东方评论员认为，上述观点有一定道理，但，在我们看来，北京就是愿意做这样的交换，也不会是拿中东实质利益去交换。因为华盛顿在台湾问题上、已经失去了北京的任何信任，所以，东方评论员认为，中美双方能做的交换恐怕只能是“就事论事”，台湾问题之外的，就在台湾问题之外谈，而台湾问题之内的问题，就用“反分裂法”的进程去谈。

事实上，谁都清楚，台湾问题是影响中美之间的核心问题，但远不是问题的全部，虽然中国还只是个地区性大国，但中美欧三足鼎立的局面已经初显，因此，北京与华盛顿之间在中东、朝鲜、美洲、非洲到处都有利益上的争夺。

也如美国一直在用台湾问题这一样东西来与中国周旋一样，有分析就认为，北京今后将会着重学会用台湾问题之外的东西去与华盛顿“蘑菇”，因此，在东方评论员看来，如何让“反分裂法”去应付华盛顿打“台独”牌、牵制中国之意图的同时，也让“反分裂法”最终超越台湾，以一个不利于华盛顿全球战略的内容、去反向牵制美国的中东、以至全球战略，也是北京应该认真思考和加以利用的因素。
 
 
*** 中国“反分裂法”的立法进程，与中美在全球战略上的布局不可能避免地“捆绑在了一起“

东方评论员认为，这种“思考和利用”的过程，本质上就是我们之前一再说到的调控“立法进程”。在我们看来，北京于中东出手之后、再启动“反分裂法”的立法进程，事实上已经再清楚不过地表明：中国“反分裂法”的立法进程，将与中美、欧美在中东的角逐、北京与华盛顿在全球战略上的布局不可能避免地“捆绑在一起”。

因此，东方评论员不认为北京会在中东方向会因台湾问题有什么实质让步，在我们看来，在台湾之外、在中东、在朝鲜，中国应该是该做什么，就去做什么，因为任何与华盛顿之间用自己的全球战略去换取台湾问题、最终都不会有什么结果。
 
 
*** 大陆的“反分裂立法”进程是否会缓和一些，这次“春节包机”可能是一个“观察点”

现在，北京对华盛顿是高度地不信任，这一点从中国官方媒体“冷处理”陈云林访美的全过程就可以一窥其二。

在东方评论员看来，这次“春节包机”可能是一个非常好的观察点，这个观察点，不仅是我们观察中美近段在台海政策有什么调整的观察点，更是我们观察中、欧、美在中东问题上有什么动作的观察点，也是朝鲜问题、中日关系等一系列重大问题之走向的观察点。

然而，需要强调的是，台湾问题应该只是北京调控“立法进程”的一个因素，而且不应该是最重要的因素，在东方评论员看来，中国的在正式推出“反分裂国家法”之前，最应该参考的中东问题，是华盛顿在中东方向的进展情况、其次是朝鲜问题。
 

*** 不论陈水扁这次如何选择，都只是北京考虑“反分裂法”进程的次要因素

基于“台独”在美国的支持下，实际上早已经踩到了红线，只不过是没有越过而已，因此，不论华盛顿让陈水扁在这次“春节包机”问题上如何选择，在我们看来，都只是北京考虑“反分裂法”进程、与具体条款的一个次要因素。
 
尽管如此，我们也认为，如果陈水扁最终同意按两岸各家航空公司间、以“国内航线”这种“纯商业的方式谈判”、最终默认在“92共识”的框架内来飞“春节包机”的话，那么，可以期望的是，这将有助于北京“反分裂立法”进程“缓和一些”，起码我们“不容易”在近期就听到一些极其严厉的条款“意向”“放风”在中国官方媒体上，这样，陈水扁非常想要的“台海和缓”局面虽然不一定会实现，但是，却不至于在3月份之前、因一些“提前见报”的、“极其严厉的条款”而变得更加危险、更加紧张！
 
在一段有关朝鲜的新闻之后，东方评论员将把关注的焦点转到风云再起的朝鲜半岛。
 
《东方时代环球时事解读》http://www.dongfangtime.com
 
