# -*- org -*-

# Time-stamp: <2011-08-04 00:33:08 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 2005年6月27日 星期一

  

** 日本天皇今首赴海外塞班岛祭拜二战阵亡日军

【东京消息】新京报综合报道日本目前在位的明仁天皇和皇后于今日赴塞班岛，为二战期间在该岛丧生的4万余名日军和1万余名平民“慰灵”，这将是二战结束60年来，日本天皇首次赴海外祭拜二战阵亡日军及平民。

据日本《读卖新闻》报道，日本天皇和皇后将在塞班岛访问两天，期间，二人将首先前往二战期间日军及日本平民拒降投海自尽的两处海边悬崖默哀，然后访问日本在塞班岛建设的“中部太平洋牺牲者之碑”，该碑纪念在塞班岛战役中丧生的所有军民。日本政府在上个世纪七十年代在亚洲各地建设了十余个这样的纪念碑。

最后，日明仁天皇及皇后还将访问专为在塞班岛阵亡的5000余名美军和1000余名在战争中丧生的岛民设置的纪念碑。

报道说，这是日本天皇首次以“慰灵”，而不是以“友好亲善”为目的出访海外。日本天皇皇后曾于1995年二战结束50年之际在日本本土的广岛、长崎和冲绳进行“慰灵之旅”，而此次则将“慰灵之旅”延长到了海外。



【时事点评】我们知道，二战末期，塞班岛是美日在太平洋激战中最残酷的战场之一：1944年6月，美军7万多人对塞班岛发动大规模登陆战役，遭到4万多日军抵抗，7月2日，驻岛日本海军第1航空舰队司令南云大将、守岛司令斋藤中将自杀，其余日军仍然负隅顽抗，被美军全部歼灭。整个战役中，日军几乎全部被打死，共4.1万人，美军则损失1.65万人。后来，塞班岛由联合国交归美国托管至今。


*** 小泉早在3月份就准备安排他的天皇和皇后到塞班“招魂”

东方评论员认为，事实上有心为“历史”翻案小泉政府，早在3月份、在第二次世界大战结束60周年之际，就计划着“要做两件事”：一件就是准备安排他们的天皇和皇后于3月底到塞班岛，祭奠被打死的日军所谓“亡灵”、为日本军国主义者“招魂”；再就是“拒绝”到莫斯科参加纪念反法西斯胜利60周年的红场阅兵仪式。

大家都非常清楚，今年，一进入2月份，中日关系伴随着中美关系的紧张而紧张、一时间真可谓是“风高浪急”，一方面，日本不顾北京的反对、公然将台海纳入美日安保指针，再就是企图在“参拜靖国神社的问题”上寻求实质性的突破。


*** 小泉政府终究“没有敢”按计划做成这两件事

在东方评论员看来，也就是在这个时候，北京开始一改之前模糊立场，公开在日本“入常”问题上亮明观点，并并与韩国一起“大做文章”，成功地将日本的历史问题进行了“国际化、世界化”，发动世界舆论、公开质疑日本没有资格“入常”。

结果，小泉政府终究“没有敢”按计划做成这两件事：首先，将日本天皇拟定的3月底行程取消，再就是，小泉纯一郎最终还是不得不“心不甘情不愿”地“现身红场”。

那之后，中日关系又经历了日本外相町村信孝的“北京败北”、日本首相小泉在亚非峰会上的“公开道歉”、北京强烈警告日本不得向日本企业发放勘测东海资源许可证、以及吴仪提前中止访日行程等一连串重大事件。

由此可见，日本“再次安排”他们的天皇无妇，“在几个月后”启程完成“3月订下的”所谓“慰灵之旅”，事实上意味着并无实权的日本皇室、其角色在日本右翼的精心安排下、已经开始了“某种转变”。


*** 日本天皇夫妇将“慰灵之旅”“搬到了海外”，绝对是“第一次”

东方评论员认为，日本天皇进行类似的“慰灵之旅”，虽然说早已经不止一次了，但是，此次是日本天皇夫妇将“慰灵之旅”“搬到了海外”，却绝对是他们在日本投降之后的“第一次”，可以说是非常的“企图心”。


*** 日本天皇自投降60年以来第一次尝试“新角色”

我们知道，自那位已经死去的、对负有重大战争罪行的日皇裕仁、于六十年前公开宣布放弃神权统治之后，日本天皇在美国草拟的战后宪法中、“被明确定性”为只是日本的象征领袖。

而当初塞班岛在二次大战被美军攻陷时，按日本人的描述，当时岛上4.1万被打死的日本军人，直到最后都抱着“效忠日皇”的念头、此外，岛上还有数以百计日本平民自杀、以示同样的“效忠”之意，考虑到这一层，那么，日皇明仁这次到塞班岛、其角色也就不是什么“象征角色”了，而根本就是在扮演“安抚者”的角色，在东方评论员看来，这当然是日本的天皇自投降60年以来第一次尝试“新角色”。

*** 美日这次是在“公开勾结”

在东方评论员看来，泉纯一郎在这个时候、让他的天皇夫妻二人扮演“安抚者”的角色，而安抚的对象是被美国人打死的日本兵、安抚的地点是被美国托管的“外国”，显然，要完成这一幕，没有日本保守势力和美国新保守势力的全力配合，根本就不可能。

我们认为，美日的这次“公开勾结”、可以视为一种为“日本侵略历史”共同翻案。在东方评论员看来，华盛顿决策层充许日本的天皇夫妇以这种方式踏上美国人管理着的、二战中美国军人付出重大牺牲、损失了1.65万人的塞班岛，不仅是在“与日本人一起”侮辱美国人自己的历史，更是在“共同挑衅”国际良知、这其中散发出的强烈信号，是非常值得警惕的。

因此，今天出版的《人民日报》、以一篇评论的方式、通过对这一段相关历史背景的“充分描述”，对布什政府和小泉政府的这种“企图心”予以了彻底的揭露。

下面，我们先来看看这篇评论，是今天由人民日报刊发的，之后，东方评论员将继续回到这个话题，也来谈谈那段历史。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** “大东亚共荣圈”的欺骗性
#+HTML:<center>
——评日政要否认战争罪责
#+HTML:<\center>

#+HTML:<h1>
【人民日报】
#+HTML:</h1>
日本政要否认战争罪责的主要论点是自欺欺人的所谓建设“大东亚共荣圈”。“大东亚”理念、“大东亚共荣圈”构想是日本发动“大东亚战争”的思想基础。大东亚理念由来已久，其理念创始人佐藤信渊（1769—1850）曾说过：“皇国欲开拓他邦，必先吞并支那国。如果强大的支那尚且不敌我皇国，更何况其它夷狄乎。”他的扩张思想为近代日本大陆政策的形成奠定了思想基础，他的一些主张也被后来的日本军国主义政府付诸于构建“大东亚共荣圈”的实践中。革新派右翼思想家大川周明将主张亚洲各国平等合作的“古典亚细亚主义”思想与日本侵略亚洲的“大陆政策”、“大东亚共荣圈”混为一谈。这不仅造成理论上的混乱，也导致一部分日本人时至今日仍将所谓的“大东亚战争”视为“正义”之举。


　　“大东亚共荣圈”一词由近卫内阁的松冈洋右外相最先使用。1940年8月1日，他在谈到日本外交方针时说，“本着皇道大精神，首先确立以日满支为其一环的大东亚共荣圈”。也就是说，建设“大东亚共荣圈”是日本“皇道外交”的具体体现。“大东亚共荣圈”有两个支柱，一个是“南进”抢占殖民地，解决日本的重要资源问题，另一个是与德、意联手形成“轴心体制”。1942年2月16日，日本首相东条英机在国会演说中称：“大东亚战争的目标就是要使大东亚各国、各民族各得其所，以皇国为中心，确立基于道义的共存共荣的新秩序。”1943年11月在东京召开了“大东亚会议”，这是以“大日本帝国”为家长的“家族会议”，出席会议的6国均为日本扶持的傀儡政府。会议通过了“大东亚共同宣言”，其中前四条都是些冠冕堂皇之语，如主张“共存共荣”、“自主独立”、“相互尊重”、“紧密提携”等。只有最后的第五条“开放资源，以此为进军世界做贡献”才具有实质意义，它彻底地暴露了日本侵略亚洲、称霸世界的企图。


　　“大东亚共荣圈”不是作为民间理想主义的“亚细亚主义”的自然发展，而是“大陆政策”的自然延伸，它是日本政府的一种现实主义追求。近代日本亚洲战略的主题词几经变化，最后定位在“大东亚共荣圈”一词上，大东亚共荣圈与大陆政策一脉相承。所谓“兴亚”、“共存共荣”、“解放亚洲”完全是一句骗人的口号。日本“南进”的目的就是为了打破美国的封锁，取得日本所“必需的物质”，“保证日本在太平洋的霸权地位”。日本之所以打着“解放亚洲”的旗号，是想使其侵略行为合理化，达到欺骗国内人民、便宜行事的目的。乘西方殖民主义者无暇东顾之机，“利用形势”、“行使武力”，夺取西方殖民主义者在东南亚、南亚的殖民地，使日本的势力范围从东亚扩展到南亚，这才是日本构建“大东亚共荣圈”的真实企图。“大东亚共荣圈”不是“兴亚论”的必然结果，而是“大陆政策”的终极表现。“兴亚”口号成为日本侵亚的挡箭牌。“大东亚共荣圈”的欺骗性昭然若揭。


【时事点评】我们知道，“九一八’事变后，日本就开始公开鼓吹“日、满一体论”。全面侵华战争爆发后，在1938年11月，日本首相近卫发表声明，抛出了‘建立东亚新秩序’的计划。并声明：帝国期求建立确保东亚永久和平的新秩序，主要是为了引诱国民党投降，排斥英美等国家，再达到占领中国的目的。


*** 所谓的“大东亚共荣圈”是如何“流行开来”的


到了1940年7月，日本近卫内阁制订《基本国策要纲》，进一步把“建立东亚新秩序”扩大为建立“大东亚新秩序”，声称要建设以日本为中心、以所谓的“日本、满洲、中国”紧密合作为基础，囊括“大东亚”的新秩序和经济协同圈。同年，日本外务大臣台冈洋右8月在发表《皇国外交方针》一文中，主张建立包括南洋在内的“大东亚共荣圈”，也是自那开始，该词就“逐渐流行开来”。


*** 日本深切感到“主宰东亚的机会来了”，

我们打开地图，对比日本近卫内阁的“梦想”，就不难看到，中国的南海群岛、印度支那、马来亚、泰国、新加坡、印度尼西亚、缅甸、澳大利亚、新西兰、印度等国家和地区都被日本人列入到“共荣圈”范围之中。

在我们看来，到了1940年9月，也就是日本明确提出“东亚共荣圈”之后，仅过了一个月不到的时间，日本就与德国、意大利缔结“三国同盟”，组成“轴心国”。东方评论员认为，这实际上就是日本“在东亚建立新秩序”的“开端”。

显然，也就是在那之前，在德国纳粹的攻击下，英国开始“大举收缩”、而法国已经崩溃，可以说整个欧洲势力在亚洲“已经成了过去”，事实上也就是在这种背景下，日本深切感到“主宰东亚的机会来了”，并由此建立、并开始实现“大东亚共荣圈”的构想。


*** 日本军国主义者当时可以说是“同时走了两步棋”

东方评论员认为，为了抓住机会，快速实现“大东亚共荣圈”的构想，日本军国主义者可以说是同时走了两步棋：第一，就是加紧侵略中国，中国的抗日战争也到了最为严峻的时期，此外，日本从1940至1941年，还出兵占领了印度支那、意图阻断中国从反法西斯同盟国接收各种援助的战略通道。

第二，日本人同时还决定趁美国尚未准备就绪，发动突然袭击，意图取得战争主动权，于是在1941年12月，派海空军对珍珠港进行突然袭击，重创美国太平洋舰队。美英随即对日宣战，太平洋战争爆发。与此同时，日本出动陆军，向东南亚各国和西南太平洋各岛发动进攻，并建立殖民统治，直到日本宣布无条件投降。

由此可见，日本所谓的“大东亚共荣圈”的构想。其主要目的就是“侵略亚洲各国”、是要把英美荷等国从亚洲赶出去，自己取而代之。而今天，日本天皇夫妇第一次将“慰灵之旅”“搬到了海外”，选择的地点就是当年日本军国主义者为了实现这个“大东亚共荣圈”、而遭到沉重打击的一个“老战场”。


*** 小泉在这个时候发这个“声明”，实质是一出“哀兵”策略

显然，小泉纯一郎为了“突破历史”、这次最终还是将他的天皇夫妻俩人给“抬了出来”、并送到了塞班岛，在东方评论员看来，小泉此举意图清晰：首先当然是在为军国主义招魂、但更是为了向中国、亚洲国家叫板。

另外，在东方评论员看来，小泉纯一郎已经公开宣布，他将在明年9月份“下台”，事实上，大家应该记得，就此“声明”，《东方时事解读》曾经发过一篇“特别评论”，在我们看来，就如我们在“特别评论”中所说的那样，小泉纯一郎在这个时候发这个“声明”，实质是一出“哀兵”策略：意在明示中国，“不要把他小泉给逼急了”。


*** 向北京显示“狗急了还会跳墙”的“意图”是一览无遗

东方评论员注意到，小泉纯一郎将在明年9月“下台”、其实早就不是什么新闻，对这一说法、最早可见诸去年7月份的报端。当时，小泉纯一郎就因执意“二访”朝鲜、与韩国一道、寻求与朝鲜建立外交关系、并因此而为布什“所不待见”。

事实上，就在那个“看着布什脸色”、也准备前去平壤“再见金正日”的日子里，小泉纯一郎就曾经非常强硬地表示过“他要下台”的话、显然，那一次，小泉纯一郎是说给布什听的。结果，小泉纯一郎果真到了平壤，而布什倒也真没有说什么“不好听的话”。

因此，在时隔一年，小泉似乎在故技重演，挑在中日关系最紧张的时候“再次宣布自己将下台”，其向北京显示“狗急了还会跳墙”的“意图”是一览无遗。说白了，因为北京已经“看轻”了小泉，小泉纯一郎这是有意以“破罐子破摔”的姿态做最后一搏。


*** 中国最具权威的官方媒体发“抢在同一天”发这篇文章的“几层意思”

搞清楚了小泉纯一郎的“企图心”，在东方评论员看来，中国最具权威的官方媒体、抢在日本天皇夫妇以“安抚者”的身份去塞班岛的同天、发表这篇揭露“大东亚共荣圈”的文章，自然不是偶然的巧合，我们认为，起码有这么几层意思：第一，当然是在为日本天皇夫妻二人的塞班岛之行“喝倒彩”，因为对这样的事情，不仅中国政府必须表明自己的立场、中国的媒体也必须表明自己的立场：北京是在警告对手、而媒体方面则是为了给国内舆论“定调”；

第二，是提醒当年被日本军国主义圈在“大东亚共荣圈”内受害国家的警惕。我们注意到，文章认为，日本“南进”的目的就是为了打破美国的封锁，取得日本所“必需的物质”，“保证日本在太平洋的霸权地位”，这些话显然是说给美国人听的，要这些包括美国人在内的受害者、警惕日本重走军国主义的企图心、以及因此给“中美两国”的国家利益“都可能带来巨大的危害”。


*** 揭露日想成“普通国家”的“企图心”，所谓“大东亚共荣圈”就是极好的“着力点”

因此，东方评论员认为，要继续将“日本的历史真面目”在国际上广而吿之，要将日本想成为“普通国家”的“企图心”加以彻底揭露，这个让中国、美国、以及亚洲国家都遭受重大损失的所谓“大东亚共荣圈”、就是一个极好的“着力点”。

而所谓的“大东亚共荣圈”、就为中国与许多亚洲国家提供了一个“共同批判”日本那段“丑恶历史”、以及今天“拒不认罪”的“丑恶面目”的平台。


*** 北京如何确定纪念规模与方式，将是中日关系极其重要风向标

在东方评论员看来，就如我们之前所说的那样，再过不到两个月的时间，就是“中国人民纪念抗日战争胜利60周年”的日子了，也就是亚洲许多国家纪念日本无条件投降的日子，在余下的时间里，蓄意如何确定这次纪念活动的规模与纪念方式，将是中日关系的一个极其重要风向标、也是日本在历史问题上何去何从的风向标。


*** 这是北京在为新一轮的、“敲打日本”发出的信号

第三，恐怕也是最重要的，这也是北京在向日本社会展现出的强硬态度、为新一轮“敲打日本”发出的信号。在东方评论员看来，日本保守势力既然敢在历史问题上挑衅北京，也就不怕所谓的“政冷”，在则强硬的小泉在4月份“被迫道歉”，显然是惧怕“政冷”扩散到了“经冷”。

事实上，日本经济界在3、4月份中，因日本政府参拜靖国神社、修改教科书、公然插手台湾问题而激起中国民众的“反日情绪”中，其损失不可谓不小，因此，东方评论员不排除中国民众的“反日情绪”会因日本右翼的挑衅行为而再次被激发，从而给日本经济更大的打击。在东方评论员看来，中日关系在这两个月中、不仅会是国际政治关注的集中，更可能成为世界经济界关注的焦点。

事实上，类似的风声已经见诸报端了，我们先来读一份海外媒体的消息，说的是日本自民党前干事长加藤纮一从北京带话、警告小泉纯一郎：如果小泉今年继续到靖国神社参拜，将会给日本经济带来严重的打击。稍后，东方评论员将继续这个话题。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
