# -*- org -*-

# Time-stamp: <2011-08-02 22:17:30 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

#+STARTUP: indent

* 2005年5月16日 星期一

** 橘营败选反省「扁宋会」

【台湾消息】据《联合晚报》15日消息：「国代」选举结果揭晓，亲民党政党支持度仅6.11%，在总数300席国代中分得18席。虽然党中央定调为亲民党坚持和解与改革路线必有的阵痛，党内却出现一片要求检讨扁宋合作的声浪，有立委要求立即召开全台党代表大会进行路线政策的公开辩论，更有立委表示，亲民党中央应该要有人为亲民党选举挫败负责，与国民党谈和解、合并。

亲民党在「国代」选举中惨败，党内质疑是扁宋会对亲民党造成影响。14日傍晚「国代」选票开出后，亲民党秘书长秦金生在内部会议中，非常保留地希望成员不要把这次选举讲成是败选，也不要提对亲民党路线检讨的问题，当时就有内部成员认为，亲民党没有面对问题的勇气，因为一旦检讨起来就会指向宋楚瑜。

立委席次减半后恐崩盘

但立委邱毅、林郁方认为「国代」选举结果对亲民党是个不容轻忽的严重警讯。「如果不正视这个危机，难保亲民党不会崩盘。」林郁方说，选举结果说明了亲民党选民不能接受民亲合、扁宋会，亲民党应该要走回头路，与国民党谈和解、合并，否则席次减半后的立委选举，甚至即将到来的年底县市长选举，「亲民党还有什么筹码？」

宋楚瑜看不上「国代」选举

亲民党立委都担心「国会」减半与单一选区确立后，亲民党可能只剩下五席，宋楚瑜就玩完了。据指出，因为宋楚瑜对这次「国代」选举看不上眼，亲民党中央对于任务型「国代」选举也不在意，连党籍立委都受影响，党中央发给每位立委7,000份「国代」选举传单，却连一位立委都没有来取走，至今还堆在党团办公室内。


【时事点评】台湾任务型“国代”选举结果14日晚间揭晓，要知道，“连宋”分别带着“九二共识”、“两岸一中”刚刚回去，“泛绿”的两大头目陈水扁和李登辉又分别在用“想当国父、老不知耻”、“自封为台湾之、不要脸”的“极端语言”互相倾轧，事前许多人都在期待着什么，然而，选举结果似乎让许多人“大出意外”。

*** 在我们具体点评这种所谓的“大出意外”之前，先来看看一些“具体数据”

在我们具体点评这种所谓的“大出意外”之前，先来看看一些具体数据：据资源显示，这次任务型国代选举，共有12政党及联盟参选，其中，得票数最高的四个政党，分别是民进党（164万票）、国民党（150万票）、台联党（27万票）和亲民党（23万票）。

根据投票数所换算出来的席次，赞成的有250席，包括民进党128席，国民党117席，中民党3席、农民党1席、公民党1席。而反对的有50席，包括台联党21席、亲民党18席、以及建国党1席、无党联盟2席、新党3席、张亚中联盟5席。

去年第六届立法委员选举投票率为百分之五十九点一六，民进党得票率百分之三十五点七二，国民党百分之三十二点八三，亲民党百分之十三点九，台湾团结联盟百分之七点七九，无党团结联盟百分之三点六三，无党籍及未经政党推荐者百分之五点九四，新党百分之零点一三。

*** 与去年立法选举相比，李登辉和宋楚瑜的支持率“分别被吸收”

不难看出，与上次立法委员选举结果相比，显然，民进党仍然是台湾的第一大党，国民党是第二大党，这与上次立法委员选举的格局是一致的。然而，结果中也有不一致的地方，这种不一致表现在两个方面：

第一，在这次“国代”选举，民进党得票42.52%，国民党的为38.92%，因此，相比起来，民进党和国民党此次得票率均有所增长，而不论是“急独”的李登辉之台联，还是一度“橘子变绿了”的宋楚瑜之亲民党，得票率都有所下降。

这就是说、在这几个月来，台湾“泛蓝”、“返绿”民众在目睹了让“宋楚瑜这只橘子变绿”、“陈水扁抓鬼反被鬼捉”的“扁宋会”、以及大陆让“必须用”“非和平方式”粉碎台独重大事变的“反分裂国家法”正式生效这“两件大事情”之后，那个旨在与连战拉开距离，而不惜“自弃立场”与陈水扁达成“宪法一中”“十点共识”、从而“由蓝变橘”、要“走自己路的”宋楚瑜和亲民党，以及痛骂“陈水扁抓鬼反被鬼捉”、在机场“武力”拦阻连战飞大陆的李登辉和台联党、结果发现，自己的“支持率”反都让欲与之拉开距离、分道扬镳的国民党、和“痛骂目标”之民进党给“分别吸收”了。


由此可见，在其它小党派得票率变化不大的情况下，这种“分别吸收”正好表现在与台联相比属“缓独”的民进党、以及与亲民党相较属“深蓝”的国民党的支持率大升、而亲民党、台联党的支持率大减上的。

*** 亲民党不仅已沦为“三甲”之外，票数竟然比台联的“27万票”“还要稀少”

第二，东方评论员还认为，在立法选举中惨败的亲民党，这次是“继续惨败”，我们知道、在立法委员选举中，亲民党尽管席次大减，但仍然牢据每三位，其席位是第四位的“台联党”的几倍。

我们知道，亲民党自去年十二月立委选举结果不佳后，宋楚瑜就开始“走自己的路了”。然而，他“走的路”却是“扁宋会”、“十点共识”所标定的“中间路线”这条路。

然而，这一次选举结果表明，亲民党不仅已沦为“三甲”之外，票数竟然比台联的“27万票”“还要稀少”，只有区区23万票、其支持度仅有6.11%，在总数300席国代中只分得18席，与半年前的立法委员选举相比，在其它主要政党变化不大的“陪衬下”，可以说是“退步得惊人”。这对刚刚从大陆回去才两天的宋楚瑜和亲民党而言、其“支持率”可算得上是“遭遇滑铁卢”。

在这种情况下，亲民党内部“出现一片要求检讨扁宋合作的声浪”是不足为奇的。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com


在我们具体点评台湾任务型“国代”选举之前，不妨再来看看取得了“抛四进三”之“佳绩”的“台联党”、又是如何评价自己的。


** 国代选举结果李安妮：台湾党战胜中国党

【台湾消息】台湾团结联盟任务型国民大会代表排名首位，台湾综合研究院副院长李安妮今天表示，从国代选举结果来看，“中国党没有战胜台湾党”，也证明泛绿阵营中，台湾人民需要另一种选择。

国代选举结果出炉，包括李安妮在内的二十一名台联国大代表，晚间都在台联党中央出席记者会，李安妮接受媒体访问时，发表上述看法。

李安妮表示，这次国代选举，受制于“选党不选人”的选制，小党能选得好，一开始就是“missionimpossible”(不可能的任务)，但台联明知不可为而为，仍坚持正名、制宪，奋力一搏，选举结果泛绿过半，“中国党没有战胜台湾党”。

李安妮说，虽然选制有利于大党，但台联仍获二十一席，成为第三大党，证明台联能提供支持台湾主体意识民众另一种选择，未来台联仍应本着“奋力一搏”的精神，坚持制宪正名及帮助台湾成为正常化国家的方向努力。

台联党主席苏进强指出，这次的选举选党不选人，不能与一般选举等同而论，台联这次选举政党支持率为百分之七点零五，仅算锁住基本盘，与台联的预期有落差，却成为第三大党，台联不会得意忘形或灰心丧志，未来仍会坚持与台湾人民站在一起的路线，深耕基层，争取扩大支持。


【时事点评】请大家注意这一句，“中国党没有战胜台湾党”，这是个什么玩意儿？说白了，在这次选举中、取得了将民进党踩在脚下之“空前胜绩”的、成为台湾“第三大党”的台联党，在与民进党吵得“一塌糊涂”之后，难得地、仍然在为“台独”的大局着想，并大度地“将自己与民进党再次划拉在一起”、并以“台湾党”而自居。

*** 不是因为他李登辉的“急独”有多好，而是宋楚瑜的“变色”太糟糕

然而，在李登辉如此顾全“台独”大局的背后，面对的尴尬正是“自己的选票被民进党吸收了”的事实。因此，台联取得的这个“第三大党的佳绩”的主要原因，不是因为他李登辉的“急独”有多好，而是宋楚瑜的“变色”太糟糕，如此而已，在这种情况下，也就要粉饰一下，也就要搞个“中国党”和“台湾党”的“小发明”，并以所谓的“中国党没有战胜台湾党”“一语慨之”。

*** 李登辉“爱女”所说的“中国党没有战胜台湾党”的确不错

既然李登辉“有此发明”，我们也不妨按所谓的“中国党”和“台湾党”这一别出心裁的“统计口径”去统计一番：如果按李登辉“爱女”的说法，那么，台湾主要的“台湾党”的得票数就是民进党的164万票加上台联党的27万票、也就是大约191万票，而所谓“中国党”的得票数就是国民党150万票加上亲民党的23万票、大约就是173万票，所获得的席位分别是149席和135席。

显然，客观上讲，李登辉的那位“爱女”所说的“中国党没有战胜台湾党”的确不错，在这点上，就应该客观地去看诸如什么天气不好、下大雨影响投票率、民进党、台联党动员能力强等等原因。

*** 选举结果反而能“非常准确地”代表了台湾的“主流民意”、也就是“台湾意识”

在东方评论员看来，这些因素也确实是个原因，但都不是主要原因，事实上，在东方评论员看来，“泛绿”的“动员力强”、以及这种选举结果反而能“非常准确地”代表了台湾的“主流民意”，我们认为，这种“主流民意”本质上也就源于宋楚瑜在清华大学演讲中所“重点宣传”的台湾意识。

对于这个“台湾意识”，东方评论员也已经说得够多的了，在我们看来，它根本就是一种“惧战却反统”的“分裂意识”，我们认为，宋楚瑜之所以愿意在清华大学大唱“台湾意识”的“悲情”，就在于宋楚瑜清楚地看到了这种“分裂意识”在台湾的“根深缔固”，而宋楚瑜当时谋划“扁宋会”时，不也是看中了这一“台湾意识”的“大有可为”、而去搞什么“扁宋会”和“宪法一中”的吗？

*** “台湾意识”是国、亲主要部分、以及民进党中一部分人的”共同政治意识“

在东方评论员看来，宋楚瑜看中这一“台湾意识”，其目的是非常清楚的，那就是以“强调”“惧战却反统”的“台湾意识”为工具，第一步，先突出“台湾意识”中的“反统”意识，与国民党“强行”拉开距离、从而好“走自己的路”。

然而，事实上，国民党也有相当一部分人在走、或者准备走“台湾意识”这一“群众路线”，这从其内部的、以马英九为代表的势力一度将“台独”视为“可选项”、并且在连战登陆前，一度在国民党内占有上风、就足以证明“台湾意识”其实已经是国民党主要部分、亲民党、新党、以及民进党中一部分人的”共同政治意识“了。

*** 宋楚瑜非常在意的、“关键角色”的原本含义

因此，在东方评论员看来，宋楚瑜在走出“扁宋会”的寻一刻起，事实上心里已经非常清楚，由于它的政治立场本来就与国民党“没有大的差别”，因此，尽管宋楚瑜对华盛顿安排的2月24日的“扁宋会”是不愿意的，但是，他却“太想穿上”华盛顿示意陈水扁给他“定做”的“官方外衣”，意图在李登辉“假骂”陈水扁、以其“爱女”著名的一句“痛骂”：“老人家是让你去（陈水扁）恋爱、没有让你上床”之“双簧”的“声东击西”下，拿着那个包藏“独心”的“宪法一中”为基础，却又塞进了“四不一没有”的“十点共识”、就想立刻“登陆”取得“历史性突破”，从而、一来可以为华盛顿打开两岸和谈、实践“华盛顿一手导演之中间路线”的僵局、用这个“宪法一中”的“十点共识”去慢慢蘑菇大陆坚持的“九二共识”，从而争取拿到一份、旨在为华盛顿的“台独时间表”争取足够的时间的“两岸和平协议”。


二来，一旦他宋楚瑜如期“率先登陆”，并以此为开端而让两岸和平成了“现实的愿景”（就如连战率先登陆、所取得的成果和声望一样），那么，则可以将他宋楚瑜和亲民党“拔”到“两岸和平”开拓者的高度，如果拿到了上述的、符合美国口胃、旨在拖延时间的“两岸和平协议”，那么，在国“台湾意识”面前，在北京、华盛顿的眼里、宋楚瑜就将成“维持两岸现状”“最主要的功臣”了，事实上，在东方评论员看来，这就是宋楚瑜非常在意的、“关键角色”的原本含义。


*** 这种“关键角色”，正是华盛顿、陈水扁做成“扁宋会”，并“请宋入瓮”的“胡萝卜”

然而，必需强调的是，这种“关键角色”，是宋楚瑜在“美国剧本”中看到的，这也正是华盛顿、陈水扁用来“请宋入瓮”的“胡萝卜”。

非常清楚，非常擅长权谋的宋楚瑜、当然知道这是根“胡萝卜”、是个诱饵，但是，宋楚瑜还是选择了“欣然入瓮”，在宋楚瑜看来，一旦他拿到了“美国剧本”中的这个“关键角色”，和陈水扁、亲民党、台联党一同“挤破”、或者“挤裂”国民党这个挡住自己和亲民党政治前途的“蓝气球”。

那么，到时候，他和他的亲民党就不必再去刻意强调“自己戴的是橙色领带、还是蓝色领带”了，因为在这种情况下，在行政权、在立法院、在两岸关系上都已经“无所事事”的国民党、在内部“独派”、“统派”、“本土派”、“外来人”的纷争中、恐怕早已经分崩离析了。

在东方评论员看来，被“挤破”、或者“挤裂”了之后国民党、除了“独派”之外、其“泛蓝”支持者恐怕都会转投到宋楚瑜、亲民党的账下“听用”。

*** 宋楚瑜“没有看清楚”一个“核心问题”

从上面的分析不难看出，就如我们之前所说的那样，如果仅从权谋的角度来评价，宋楚瑜的这步计划还是很不错的。然而，要命的是，宋楚瑜“没有看清楚”一个“核心问题”，结果反而在北京首先邀请连战登陆后，立刻就陷入被“扁宋会”“套牢”的境地，在东方评论员看来，宋楚瑜看走眼的“核心问题”、就是国际局势的重大转变，而这种转变、也就是华盛顿为何搬出这一部“非常倒美国新保守主义者胃口”的“政治剧本”之深层原因。


*** 所有这一切，说到底，都是给大陆的“反分裂国家法”给逼的

东方评论员认为，华盛顿决策层自立法委员选举前高调“反台独”、到之后促成“扁宋会”、让两人签下让“急独”势力“痛心疾首”的、以“宪法一中”为基础、包括“四不一没有”的“十点共识”，从而将“台独进程”几乎又倒退到2000年陈水扁刚上台时的水平线上，所有这一切，说到底，都是给大陆的“反分裂国家法”给逼的。


*** 陈水扁接连闹的“两个笑话”

华盛顿清楚，“反分裂国家法”一旦正式生效，将对整个东亚格局，至于世界格局将带来的重大的影响，而这种“重大影响”是身居台湾、醉心于台湾民粹、专心于操纵台湾意识的台湾政治人物所难洞悉的，事实上，也就是这种“难以洞悉”，结果导致了陈水扁接连闹了两个笑话：

第一，陈水扁讥笑宋楚瑜想当棋手，却不过是他陈水扁手中的棋子，并将自己拔高到“棋手”这一层次；可据我们观察，在包括台海、朝核问题、日本问题的这一东亚棋局中，下棋的只不过是北京和华盛顿，就是日本的小泉纯一郎，从目前的局势演变来看，也不过是个“大棋子”的角色，真不清楚陈水扁的“自封棋手说”根据何在？

第二，陈水扁在此之前几天、也在闹笑话，他在公开赞扬胡锦涛是个“很厉害的人物”时，还在那里说什么通过“反分裂国家法”是大陆误判了形势，不过是大陆很机智地采用了请连宋“登陆”进行了补救，等等，如此云云。

*** 如陈水扁还在那里“云里雾中”，是“死了也是个糊涂鬼”！

在东方评论员看来，在北京瞄准华盛顿致力于中东事务、务求一个稳定的东亚的战略时机，一面果断、深度地介入“触及华盛顿核心利益”的中东事务，一面放风启动“反分裂国家法”立法进程为标志，一手打掉了华盛顿企图以“台独进程”继续换取北京在全球战略利益的“前提基础”，在这种情况下，华盛顿才迫于全球战略压力，不得已在东亚方向，对北京让步，并开始“反台独”的，这哪里是什么大陆在“误判形势”？，在东方评论员看来，这分明是陈水扁在误判，我们认为，如果大陆没有这种“误判”，别的不说，恐怕连战是永远也到不了北京的，这整个过程是“误判”与“补救”的过程吗？

有意思的是，到了这一步，这个陈水扁如果还象这次一样，在那里“云里雾中”，那恐怕就真的会应了一句老话，是“死了也是个糊涂鬼”！


*** 陈水扁和台湾、都不过是“棋子的格局”

众所周知的是，就在陈水扁当时为立法会“泛绿”过半、而“狂扯”台独大旗的关键时刻，布什可是一度急得用美国国骂“问候”陈水扁的“上一辈家人”的，在这种事实面前，陈水扁哪有半点“棋手”的影子，在东方评论员看来，我们也实在看不出他自称“棋手”的资格何在？要知道，下棋的人是要眼观六路、耳听八方的，在这个问题上，不论是台湾、还是陈水扁，都不过是“棋子的格局”而已。

*** 李登辉看到了这种“危险性”

结果，我们都看到了，就是陈水扁所说的那个棋子---宋楚瑜、在陈水扁所说的“北京的误判”中、犹豫了“7天8夜”之后，终于拿出了“两岸一中”这个符合“反分裂国家法”对“两岸现状”的定义。如此一来，对宋楚瑜而言，是全面抛弃了“十点共识”的基础性“第一条”，即“宪法一中”的框架。

东方评论员认为，就如我们先前所说的那样，在华盛顿的全球战略的压力下，陈水扁最终会承认“九二共识”从来就不是个有悬念的问题，可问题是，北京首先是邀请连战登陆，结果，豁出去了的连战、是在第一时间内就“承认了九二共识”；而大陆邀请宋楚瑜随后登陆，结果宋楚瑜更是在豁出去了之后、于第一时间内就“突破了九二共识”，


在我们看来，李登辉之所以对宋楚瑜率先访问大陆，一开始就“不愿意说什么”、却对连战率先访问大陆“如此受不了”，就在于他也看到了这种危险性：在台湾无牌可打的连战和国民党的率先来访，就意味为了连战为了“咸鱼翻身”、如果顶住华盛顿和国民党内派别的压力，拿出了让原来准备充当“关键角色”的宋楚瑜“处境尴尬”之条件的话，那么，华盛顿、陈水扁精心摆下的这道、以宋楚瑜为棋子打开两岸僵局、欲以“九二共识”换取一个没有保证的“和平协议”的棋局，就完全进入了北京的行棋步调。


*** 不要一厢情愿地认为台湾社会一夜之间就会抛弃“分裂意识”浓厚的“台湾意识”


首席评论员指出，尽管华盛顿也不愿意、日本也不愿意、陈水扁、李登辉更不愿意，但是，在包括台海、朝核问题在内的东亚棋局上，就目前看来，的确进入了北京的步调。

东方评论员就认为，在我们看到“连宋登陆”带来契机的同时，也不要一味地一厢情愿地认为台湾社会一夜之间就会抛弃“台湾意识”，14日的选举结果正好为此给出了最好的注解。

*** 要达到弱化、并瓦解“台湾意识”这个目的，大陆就必须“两手都要硬”

我们认为，要达到弱化、并瓦解“台湾意识”这个目的，大陆就必须两手都要硬：我们知道，“台湾意识”本质就是“惧战、反统”的“分裂意识”，因此，大陆下一步的工作重点是放在用一切“软手段”、去敦促、诱导台湾国民党、亲民党、甚至是民进党向“两岸实质性三通”方向走的层面上。显然，在这种过程中，大陆可以让“台湾意识”想要的胡萝卜“更甜”；

在我们看来，大陆现在有许多的硬手段可以用，首先，已经有了绝对强硬的“非和平方式”的“反分裂国家法”、然而，除此之外，大陆也得一刻也不要放松地、锻打“最强硬的手段”，即，必须全力提升中国的军事能力、从而一刻也不能放松地提高“非和平方式”的“有效性”。在这一过程中，大陆则必须全力让“台湾意识”害怕的“大棒”“更硬”。

*** “如何让大棒更硬”、更是重中之重

在东方评论员看来，这两点是缺一不可，特别是在“如何让大棒更硬”、硬得让美国、日本不敢轻举妄动、不敢乱说话、乱做事方面，更是重中之重。

我们认为，只有这样，只有在中国的军力“继续提高”的情况下，大陆才可更加有效地去利用美国“仍然不得要领”的中东问题、朝核问题、去尽力让华盛顿去自觉地催促陈水扁、将“五项共识”、“六项共识”一一落到实处，将两岸推向“两岸实质性三通”的。

*** 必须在“连宋登陆”的后续效应下、继续下好“连宋”这两颗棋子

第三，也是非常关键的一处，那就是、必须在“连宋登陆”的后续效应下、继续下好“连宋”这两颗棋子，东方评论员认为，就如我们之前所说的那样，由于率先在大陆访问取得历史性的突破，从而得到台湾民意的“好感”，也就取得了“完胜”，在我们看来，连战和国民党事实上只要能顶住国民党内部的“张力”，那么，事实上在台湾内部政治斗争中、已经处于“不败之地”；

*** 宋楚瑜的“两岸一中”，虽然得罪了“台湾意识”，却得到了大陆的肯定

而宋楚瑜这次在被动之余，通过“两岸一中”，虽然得罪了“台湾意识”，但是，却得到了大陆的肯定，从而得以继续其在“两岸互动”中的“关键角色”。


*** 让宋楚瑜继续这一“关键角色”，本质上是大陆将华盛顿的“关键角色”挖过来了

首席评论员指出，大陆让宋楚瑜出任这一“关键角色”，本质上已经是大陆挖了华盛顿的墙脚，将华盛顿的“关键角色”挖到了自己的账下，从而让与先前“扁宋会”时、“处于边缘化”的连战、国民党的位置，与宋楚瑜、亲民党的位置“换了个个”。


*** 要想“咸鱼翻身”、宋楚瑜只能靠大陆的配合，“继续”取得“历史性的突破”

现在，在台湾内部，从这次选举可以看出，宋楚瑜、亲民党的地位是一掉再掉，已经处于生死关头了，在这种情况下，与连战的当时的心理相同，宋楚瑜要想“咸鱼翻身”、只能靠在大陆的政策配合下，“继续”取得“历史性的突破”。


显然，连战“率先登陆”全面缓和两岸气氛，是历史性突破，但这一突破显然是“台湾意识”所渴望的。

而相比之下，宋楚瑜提出“两岸一中”虽然也是历史性突破，但后一种突破，显然“更为大陆所认可”，这就是说，宋楚瑜必须在今后，凭借“两岸一中”带来的“不独不武”为基础，在两岸互动中继续取得“让两岸都认可”的历史性突破，从有可能再上演一出“咸鱼翻身”。

*** 得在“两岸实质性三通”的问题上搞出点名堂来

显然，要做到这一点，就得在“两岸实质性三通”的问题上搞出点名堂来，在东方评论员看来，只有“在这一点”上取得实质性突破，才能让宋楚瑜看重的“台湾意识”、和宋楚瑜必须借重的大陆“同时认可”，也只有这样，已经被“扁宋会”套得无路可走的宋楚瑜、才有“咸鱼翻身”的机会。也只有兑现其在大陆所说的“行胜于言”，宋楚瑜才能在今后的台湾政治博弈中、继续得到来自北京的认可和政策支持。

*** 很可能会看到连战、宋楚瑜、陈水扁在北京、华盛顿的双重压力下，自选立场、“八仙过海”

不难看出，连战和国民党虽然现在是暂处上风，但它也清楚，一旦“登陆效应”过去、而自己“不思动作”，其“历史性成果”就将彻底成为“历史”。这点对带回了“不独不武”、这个可以让“台湾意识”安心政策的宋楚瑜，也是一样。

在这种情况下，东方评论员认为，在中东局势没有大的突破之前，我们也就很可能看到连战、宋楚瑜、陈水扁在北京、华盛顿的双重压力下、相互竟争“台湾民意”、从而国、亲、民三党在为华盛顿“谋求、或阻止一份“没有保障”的“两岸和平协议”、为大陆谋求、或者阻止一个“两岸实质性三通”的“相互矛盾的目标”中、去自选立场、“八仙过海”了。


*** “两岸实质性三通”是化解“台湾意识”的最有效手段

在我们看来，对大陆而言，在宋楚瑜而言，“两岸实质性三通”正是化解以“分裂意识”为出发点的、让“台独”肆意操纵“台湾意识”的最有效手段，只有让“两岸”全面、深层次地“三通”起来，让两岸的经济、文化、媒体、甚至政治、法律“都通起来”，不断扩大整合深度，不断弱化“台湾意识”的生存空间，那么，也就能不断掏空“台独”的生存空间，掏空美国、日本操纵“台独”的操作空间。


显然，在这个层面上，已经说过“不要看我在大陆说过什么，要看我在台湾会做些什么”的宋楚瑜，在“为了活下去”而突破了连战的“九二共识”、提出“两岸一中”之后，事实上已经在某种程度上“得罪了”他最看重的、本是“分裂意识”的“台湾意识。

这从国民党在第一时间里就以强调“九二共识”是国民党的“九二共识”、“两岸一中”是亲民党的“两岸一中”、从而将“国亲立场”分得一清二楚，就可知一二。

*** 在年底的台湾地方选举中“获得新生”，才是宋楚瑜的政治目标

因此，在东方评论员看来，宋楚瑜在“由蓝变橘”、强调走自己的路、却又没有抢到“登陆的第一班车”而明显“迷路”之后，在大陆给出了“不独不武”、“两岸三通”这个化解“台独”民意基础的“药方”之后，宋楚瑜、亲民党如果“还想活下去”的话，恐怕只有“戴着橙领带”，以有别于国民党、民进党的的言行举止、去以行动兑现“行胜于言”，用行动证明、亲民党“做起事来”、比国民党更国民党的了、从而赢得台湾民意，并在年底的台湾地方选举中“获得新生”，这才是宋楚瑜和亲民党的政治目标。

因此，在东方评论员看来，那种认为宋楚瑜对这次“国代”选举看不上眼，亲民党中央对于任务型“国代”选举也不在意，还是有几分道理的。

东方评论员认为，只要宋楚瑜和亲民党在“两岸实质性三通”上有实际的行动，并催动连战有所行动、最后带动陈水扁有所行动，那么，大陆手上的“连战、宋楚瑜”这两颗棋子的“轮番使用”，也才算真正地发挥出了“应有的效用”。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
