# -*- org -*-

# Time-stamp: <2011-08-04 12:21:29 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 2005年8月11日 星期四



下面，我们将关注的焦点转向中日关系。与平常不同的是，今天有关日本的点评，将从两则“台湾消息”开始。在一起了解陈水扁的“最新动态”之后，东方评论员将针对相关内容、给出我们的观点。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com


** 台湾“外交部”称拥东海油田“主权”




【台湾8月11日消息】据台湾东森新闻报道，台湾“外交部”发言人吕庆龙11日宣称，近几个月来，中日因东海春晓油田开发而造成区域紧张，台湾必须宣示这块油田属大陆礁层的天然资源，“所有权属于台湾”。
　　
　　吕庆龙同时又称，如果日本、中国大陆对开发东海油田存有争议，各方应透过谈判协调找出解决方法。
　　
　　吕庆龙说，开发东海油田的问题复杂，涉及主权、经开发衍生的经济利益及能源，大家都在抢。对台湾而言，“我们当然不能光看中国去开采东海油田”。
　　
　　“行政院海岸巡防署”10日发表新书《台湾海洋》，书中警告台湾不能冷眼旁观大陆积极开发原属台湾矿区的东海“春晓油田”。


** 陈水扁宣誓钓鱼台主权属台湾



【台湾8月11日消息】陈水扁昨天宣誓，「钓鱼台列屿的领土主权当然属于台湾」，并称，未来将继续秉持渔权、主权脱钩态度处理台日渔事纠纷，为渔民争取最大权益。

据香港中通社八月十日电，陈水扁上午搭乘直升机抵达彭佳屿，主持「海疆屏障」揭碑仪式时作此宣誓。

扁说，钓鱼台的问题，当局的立场与态度非常清楚且坚定，从来没有改变过，「钓鱼台列屿的领土主权当然是属于我们的、属于台湾的，这一点无庸置疑」。

他声称，有关台日之间的渔事纠纷与渔权问题，将与钓鱼台主权的争议分开脱钩处理，这不但是过去当局就已经拟定的政策，更是渔民朋友一致的期待与诉求。过去是这样处理，未来政府也将秉持相同的原则，继续为渔民朋友争取最大的权益。



【时事点评】在东方评论员看来，事实上、台湾当局今天所称的“东海春晓油田”其“所有权属于台湾”、算起来已经是第二次在中日主权争端问题上“主动表态”了、还有一次就是昨天、陈水扁所宣誓的“钓鱼台列屿的领土主权当然属于台湾”。


*** 日本人这次可以说是“指哪”、陈水扁就“打哪”

对此，首席评论员就指出，“台独”之所以在小泉纯一郎的“邮政改革相关法案”失败、宣布解散国会、提前在9月11日举行大选后的短短两天的时间里，就先后对钓鱼岛、东海油气“突然产生了兴趣”、其实是“早有苗头”。

稍早，就在上个月、在台湾渔民强烈要求台湾当局“护渔”、并与日本谈判渔权的同时，日本方面就“未雨绸缪”地抛出“担心台湾也掺合东海油气资源之争”、并“别有用心”地表示担心，说什么担心“台湾与中国大陆配合”、一起针对日本争夺东海主权。


*** “台独”与日本保守势力相互呼应、狼狈为奸的意图、已经是跃然纸上

在东方评论员看来，日本人这次可以说是“指哪”、陈水扁就“打哪”：日本人说“担心台湾也掺合东海油气资源之争”、陈水扁也就在小泉纯一郎需要“在东海搞事”的关键时刻、也就如日本所担心地那般“挺身而出”。

我们认为，陈水扁这种让日本人的担心变为现实的举动、显然是在“刻意”向日本“暴露目标”、之后、再高喊“向我开炮”。在东方评论员看来，“台独”与日本保守势力相互呼应、狼狈为奸的意图、已经是跃然纸上：即“台独”甘愿为日本人充当挑起中日东海、钓鱼岛主权重大冲突的导火索。

对此，首席评论员认为，陈水扁的举动可以视为是美国和日本向北京提出的警告、是在向北京在一系列重大问题、包括台海、朝核问题、特别是东海问题上“继续施加压力”。在我们看来，对于北京而言，对美日发出的这种“警告”、还真得认真对待。


*** 中国有必要准备一套策略、以应付台湾方面“在钓鱼岛、东海率先与日本冲突”局面

首席评论员指出，对“美日（台）”这一“各有企图”的相互勾结、北京必须高度警惕。在我们看来，中国有必要准备一套、应付台湾方面在钓鱼岛、东海率先与日本冲突局面的策略来。

应该承认，日本保守势力如果一心想挑起东海重大事件，那么，先让台湾“按计划行事”、之后自己再去“被动应对”、同时、再视北京的反应情况而相应动作、显然是风险最小、灵活度最高的一种策略。


*** 一个“更加紧张”的中日关系、绝对就是华盛顿用以弥补在朝核问题上被动的主要筹码


大家应该对我们的一个观点有些印象，那是在之前的一期《东方时事解读》的朝鲜部分，在我们点评朝核问题的“走向”对中日关系的影响时所说的，即，一旦华盛顿不得不在朝核问题上、对北京做出进一步的让步、那么，华盛顿是一定会“在其他方向对这种损失去加以弥补”的。

在东方评论员看来，一个“更加紧张”的中日关系、绝对就是华盛顿期待中的、用以弥补在朝核问题上被动的主要筹码。


*** “这一斗争”之所以如此激烈、就在于北京和华盛顿都清楚地知道“对方的策略”

我们认为，朝核问题是几经波折、但演变到今天这一局面、其“实质”已经演变成了北京拉着韩国想启动、美国拉着日本保守势力想阻止“东北亚经济一体化”进程的“激烈斗争”。

在东方评论员看来，“这一斗争”之所以如此激烈、就在于北京和华盛顿都清楚地知道“对方的策略”：不论是启动、还是阻止“东北亚经济一体化”、对彼此而言，都不过是手段、而不是目的；对北京和华盛顿而言，彼此施展“这一手段”的最终目的、就在于最终能启动、或者阻止意义极其重大的“东亚经济一体化”进程。


*** 在东亚经济一体化的问题上、北京之所以敢如此积极主动、就在于两个字--“自信”

东方评论员认为，进入本世纪以来，中日关系显然有一个重大变化：一方面，尽管北京对日本的指责仍然多于美国或其他国家、但是，就是日本人也不得不承认，北京指责的范围、频率和密度要比20世纪90年代少了许多。

另外，我们还注意到，日本人还承认、大体上北京对日本、亚洲和世界事务采取的态度对日本可以说是“大有裨益”，尤其是中国强调的“和平崛起”、希望与日本一起推进东亚经济一体化、“一再希望”与日本签订“自由贸易协议”等、都是些着眼于与日本在一起建设亚洲的过程中、公平竞争的良好愿望。当然，在我们看来，在东亚经济一体化的问题上、北京之所以敢如此积极主动、就在于两个字--“自信”、自信能够在东亚一体化的进程中成为最大赢家。


*** 日本对中国的挑衅手段、逐渐从“务虚的层面”延伸到“务实的层面”

然而，也是从这一时期开始，在北京向日本示好的同时、特别是在最近的一两年时间里，日本对北京的挑衅却开始多了起来。

首席评论员指出，日本对中国的挑衅手段、是逐渐从“务虚的层面”延伸到“务实的层面”、从“日本首相参拜靖国神社为代表的历史问题”逐渐演变到“以钓鱼岛、东海争端为代表的主权问题”。

进入今年以来，这种情况是加更重，东方评论员注意到，日本对华采取了一系列的“单方面行动”，且涉及的还都是“根本性问题”，这中间以日本同意将美日军事同盟的共同目标涵盖台湾最具代表性、以在东海主权问题上挑畔中国最具爆炸性。在我们看来，总体而言，日本方面表现出强烈的“进攻性和主动性”，这是以前不曾过有的。


*** 日本企业与日本政府之间、在投资中国问题上存有“巨大反差”

但是，东方评论员认为、值得强调的是，就在日本在政治、军事上对北京啒啒逼人的时候，日本商界却对方兴未艾的中日贸易和对华投资持“肯定态度”，这以日本不久前、在四月份中国爆发反日游行之后、于正式文件中警告日本经济界“投资中国有风险”却仍然没有降低日本投资中国的兴趣、可以说是最能说明问题的。

在东方评论员看来，日本企业与日本政府之间、在投资中国问题上存有的“巨大反差”、只能说明日本政治人物在中日关系上在“别有用心”。


*** 中日间又何妨来个直接竞争、相互也签定一份自由贸易协议呢？

我们认为，日本保守势力的“别有用心”、还表现在日本计划与一系列亚洲国家签订自由贸易协定、却就是“不打算”与中国订立自贸协定的事实上。

东方评论员注意到，对此，日本人的内部解释是：“日本与中国分别与东南亚国家签订自由贸易协定、本质上就是在争夺政治和经济主导权”。

中国有句老话，曰之为“是骡子是马、拉出来溜溜”。在东方评论员看来，既然“中、日分别与东南亚国家签订自由贸易协定”问题已经被日本人“定性”成了“中日争夺政治和经济主导权”的层面，那么，“自视甚高”的日本、又何妨与中国来个直接竞争、相互也签定一份自由贸易协议呢？


*** 自视为最具能力领导东亚的日本人，骨子里却充满了“不自信”

显然，我们认为，事实是明摆着的，不是中国“不愿意”、实是日本人“不愿意”也！其实、在东方评论员看来，说日本人“不愿意”、并不确切，显然，从中国积极主动要求与日本订立自贸协定、而日本却“极力拒绝”所映射出的“对比度”来看，任何一个人都不难看出，说日本人“不愿意”根本就是“客气”的、说白了日本人是在“害怕”：自视为最具能力领导东亚的日本人、面对一个自信的、愿意与日本一起在推动东亚经济一体化的进程中、公平竞争东亚领导权的中国、骨子里却充满了对自己的“不自信”。


*** 日本人自觉“时间不在日本、而在中国这一边”

在东方评论员看来，日本人的“色厉内荏”、在外交上是促使日本全面倒向美国、希望借助美国的力量、削弱中国影响力的最根本原因。

这一点在北京意图将美国排除在以东盟10+3为基础的政治决策机制之外，而日本则表面上是在美国的压力下、实际上却非常愿意将华盛顿引入东盟10+3为基础的东亚事务政治决策机制之内、在日本反对中国排挤美国的“所做所为”的背后，是日本人自觉“时间不在日本、而在中国这一边”的心理使然。


*** 日本保守势力想“再一次”“及时打断”中国的现代化进程

我们认为，日本保守势力之所以迫不及待地挑起事端、就在于他们认为时间紧迫，因为在他们的头脑中、成天想的就是如何抢在中国完全强大之前、抓紧美国需要日本共同遏制中国的战略时机，利用美日军事同盟这一层、如何象在三十年代日本军国主义在中国所做的那样、“再一次”“及时打断”中国的现代化进程。


*** 中国只要不犯重大错误，中日两国的国力不久就会“回位”到“历史上占主流”的状态

坦率地讲，中日之间的矛盾是结构性的，中国的强大、也的确不符合“日本右翼眼中的”国家利益；但是，中国的崛起、也绝对不会按日本右翼希望的那样、为了维持一个中日关系、在原则问题上让步，在历史问题上自毁原则、在国际社会面前自毁形象，在东亚经济一体化问题上“划地为牢”、从而将与美国、日本争夺东亚主导权的“历史机会”拱手相让。

东方评论员注意到，就在今天，日本一家由前首相中曾根康弘担任“领导人”的日本智囊机构就警告国际社会，称“中国有这样一个潜意识、即由中国来称霸全球”。显然，日本发出这种声音已经不第一次了，只是在中日关系极其紧张的时候、让人们听起来特别刺耳而已。

不过，我们认为，在日本保守势力上台之后，中日之间出现这种危机是有其必然性的。在东方评论员看来，日本经历了这些年的严重衰退，以及中国经济的快速发展、在东亚地位的极大提高、都促使日本人的自我价值观处在一种“彷徨状态”，显然，大国梦的再次破灭也终于驱使日本走向保守、并再次地“歇斯底里”。

在我们看来，尽管日本现在仍然是仅次于美国的经济强国，但是，中国只要不犯重大错误，中日两国的不仅综合国力、就是经济实力不久也会“回位”到历史上占主流的、繁荣强大的中国和相对弱小的日本之状态。


*** 日本一再挑衅北京、就是想借美国之力、打断这种“回位”趋势

显然，美国自己很难遏制中国、日本就更不可能遏制中国、在东方评论员看来，日本之所以在这个时候一再挑衅北京、就是想借美国之力、打断这种“回位”趋势。

在这里，我们还想补充一点，那就是，不论是日本想得到钓鱼岛、还是想得到东海、都不过是“战术层面”的东西，在东方评论员看来，日本保守势力其实也非常清楚，在钓鱼岛、东海油气这些国家主权问题上的任何争端，在短期内都不可能得到“真正地解决”，道理很简单，因为只要北京不同意（事实上北京也不可能同意），那么，这些主权争端、以及相关的资源都“只能放在那里”、直到“中日”一方的势力完全被对方所压倒为止。

东方评论员认为，显然，如何利用美国“非常需要”自己的时候、借用华盛顿的力量、拉着“台独”、用尽一切手段、一举压倒北京、就成了日本保守势力心中的“当务之急”。

*** 中国“不要犯的重大错误”中，就包括“绝不能对日本的挑衅姑息”

首席评论员指出，我们所说的中国“不要犯的重大错误”中，就包括“绝不能对日本的挑衅姑息”。对此，我们认为可以这样说，一旦日本在东海挑衅行动上得手，即北京同意停止东海开发计划、或者中国默认日本在有争议区域开发油气资源；或者小泉纯一郎胆敢在8月15日、中国人民抗日战争胜利纪念日参拜靖国神社、而北京没有任何有实质意义的反应、本质上就意味着北京选择了避免与“美日”同时对抗的战略。


*** 欲做渔翁的华盛顿、甚至可能“在适当的时候承认钓鱼岛的主权在于中国”

然而，假如真有这一天，那么可以肯定的是，这不仅将极大地刺激日本右翼的心态膨胀、而且还将招致华盛顿的又一次重击，即：由于没有达到让中日关系破裂之目的，下一步，华盛顿肯定会直接将钓鱼岛问题、这个直接与台湾问题、这一中国核心国家利益紧密相关的、北京退无可退的核心问题“正式抛出来”，我们认为，为了达到挑起中日恶斗的战略目的、欲做渔翁的华盛顿、甚至可能“在适当的时候承认钓鱼岛的主权在于中国”，到那时候，恐怕中国不仅更加被动、还得付出更大代价。


*** 美国“论证”其“中国威胁论”、对中国进行“综合评估”的最关键的一个环节

因此，在我们看来，小泉纯一郎是否敢于在8月15日参拜靖国神社、或者是否敢于在东海挑起严重事端，甚至是军事冲突、以及北京是否能成功“事先压制”日本保守势力的冒险意图、或者在“事后”迅速平息冲突、事实上是美国“论证”其“中国威胁论”、对中国进行“综合评估”的最关键的一个环节。

东方评论员认为，任何一件事情都是有代价的，只是有大有小。在我们看来，在现阶段尽一切力量、包括军事、经济手段去压倒、或者平息日本保守势力的冒险意图、或者行为、从而尽尽可能地激化日本国内政治气氛向有利于中日关系方向转化、必将是代价最小的一种战略选择。


事实上，华盛顿对中日关系的破裂尽管一定会持“鼓励”的态度，但是，种种迹象表明，美国人也在暗中准备着“右右逢源”。在一则来自华盛顿的新闻报道之后，东方评论员将继续进行“中日关系”的点评。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
