# -*- org -*-

# Time-stamp: <2011-08-04 12:24:21 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

*  2005年8月12日 星期五




** 美英加澳称沙特要出事发紧急警报关闭使领馆





【新华社8月12日消息】美国、英国、加拿大和澳大利亚4国政府于8月8日先后发出紧急警报，通知4国在沙特公民，“有确切消息证实，新的恐怖袭击正在酝酿”。美国暂时关闭了其使馆和领馆，英、加、澳3国也要求“公民不要前往沙特旅行，在沙特的公民必要时离开沙持”。

美英侨民不敢单独上街

这已是驻沙特的美国大使馆在两周内发出的第二次安全警报。7月25日，使馆发出警告，美国驻沙特士兵接到命令，在卸岗后须取消一切休闲活动。2004年底，美国驻吉达总领馆曾受到恐怖分子袭击，造成6人死亡。在沙的4万多美国人、2.5万英国人和其他国家侨民一直生活在恐怖之中，不敢单独上街，也不敢去周边地区旅行。美使馆工作人员早已习惯了这种生活，他们基本不带家属，而英、澳、加外交人员家属较多。在沙特就要习惯这种恐怖气氛，因此他们并不惊慌。

沙特加强警戒

沙特内政部发言人图尔基表示，沙特安全部门到目前为止还没有得到恐怖活动在即的证据，但不能排除这种可能。美国决定关闭使领馆前，沙特警方在利雅得郊区发现了一个大型军火库，其中有2吨用于制造炸弹的化学物质，这一发现让美国国务院的安全警告显得更必要。

沙特各地的警戒明显加强，巡逻车不断穿梭往来，特别是在美国使领馆的周围和贸易中心等美国人经常出入的地方。沙特东部地区警察局长说，他们并没有接到上级要求加强警戒的指示，目前只是把近3个月刚刚减少的检查点恢复而已。显然，阿卜杜拉国王刚刚登基，不想把气氛弄得很紧张，于是采取外松内紧的方式。

石油价格受到影响

恐怖袭击的警报传出后，国际油价明显上扬，纽约交易市场的原油价格曾一度达到每桶63.99美元，创历史新高。分析人士称，沙特是目前世界上最大的产油国，也是惟一能量增产的国家。本周石油价格的上涨不是因为供应短缺，而是因为安全警戒升级，如果沙特受到袭击，目前不平静的国际油市势必将进一步动荡。


【时事点评】东方评论员注意到，美国暂时关闭了美国驻沙特的使馆和领馆、理由是沙特警方在利雅得郊区发现了一个大型军火库，其中有2吨用于制造炸弹的化学物质，据说正是“这一发现”、让美国国务院的安全警告显得“更加必要”的。

与此同时，我们也注意到按沙特内政部方面给出的消息：“沙特安全部门到目前为止还没有得到恐怖活动在即的证据，但不能排除这种可能。”在我们看来，我们无意说华盛顿发出这一警告的“是别有用心”，相比这下，东方评论员，我们也必须看到这么一个事实，就如新闻中所说的那样：“恐怖袭击的警报传出后，国际油价明显上扬，纽约交易市场的原油价格曾一度达到每桶63.99美元，创历史新高”。

显然，这个所谓的“每桶63.99美元的历史新高”，事实上已经成为历史了、最新的信息是，在“一系列事件”之后，历史的新高纪录已经被“66美元”这个数字所刷新。


在我们具体分析这个“一系列事件”之前、再来看一则最新经济报道，之后东方经济评论员、东方时事评论员将一起展开讨论。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com



** 油价破66美元创新高若持续全球经济将衰退




【综合8月12日消息】今天，国际油价持续创出新高，9月原油期货12日在电子交易时段再度突破每桶66美元，一度升至66.05美元，目前在66美元之下徘徊。分析认为，如果原油一直居高不下，全球经济衰退将是可预期的。普遍认为，对发达国家而言，油价一鼓作气突破70美元完全可能。

分析认为，对炼油厂停产问题的关注是促成油价持续上升的主要因素。近期由于部分炼油厂接二连三发生事故，市场对汽油供不应求的忧虑日益增加，加上国际能源机构IEA周四发表报告，调高今明两年全球石油需求预测，并预期石油输出国组织以外的产油国今年产量将达不到原先估计的目标。专家预期，油价下一个心理关口为每桶70美元。

油价升至66美元创历史新高

9月原油期货12日在电子交易时段再度突破每桶66美元，一度升至66.05美元，目前在66美元之下徘徊。同日，伦敦国际石油交易所9月份北海布伦特原油期货价格也曾高达每桶65.66美元，收盘前回落至65美元，比上个交易日升1.39美元。

近来国际油价的不断上涨给市场造成一定程度的恐慌，但美国政府似乎并不准备进行干预。美国财政部部长斯诺周四表示，目前美国政府没有考虑释出战略石油储备，以遏止持续上升的油价。他又认为，油价在中长期将会下降。

油价短期可能破70美元

而国家信息中心预测部国际石油问题专家牛犁表示，就基本面而言，并无任何新增的不利因素，导致国际油价上涨的还是那些已知的不确定因素，诸如伊朗核问题、沙特可能爆发恐怖袭击等等。一位国际著名证券公司能源分析师认为，在基本面未发生大变动的情况下，油价连破新高，肯定是又有新的炒家入市炒油。两位专家均认为，短期来看，油价一鼓作气突破70美元完全可能。

牛犁还指出，如果原油一直居高不下，全球经济衰退将是可预期的。目前普遍认为对发达国家而言，影响主要体现在生活用油，油价一鼓作气突破70美元完全可能。

若一直居高不下全球经济将衰退

牛犁认为，如果原油一直居高不下，全球经济衰退将是可预期的。目前普遍认为对发达国家而言，影响主要体现在生活用油上，例如汽车、航空等产业。而对发展中国家而言，尽管普遍对高油价实施了保护措施，例如让国有炼厂亏损或者直接进行油价补贴，但这种措施不可能一直维持下去，那将是国民经济难以承受的。


美汽油库存减少是直接原因

据证券日报分析，从直观上看，引发油价上扬的起因是10日美国EIA公布的周度库存报告显示，美国汽油库存连续六周下降，减少210万桶至20310万桶，比去年同期减少790万桶。汽油库存的减少令市场大量买入汽油期货，推高了汽油期货的价格，直接带动了原油期货的走高。

然而，如果我们仔细分析近期国际原油的走势，就会发现，突破65美元的NYMEX现货月上市以来的历史高位，并不仅仅如此简单，而是在一系列内在动因推动下的结果，市场的强势没有发生根本改变，甚至仍在朝着更高的目标前进。

政局紧张对油价形成支撑

8月初，沙特国王法赫德的逝世一度令油价冲高，但随即沙特宣布现有石油政策不会改变解除了投资者的担忧。然而，随后的沙特地区却发生安全威胁，尽管并未直接指向石油设施，但对于目前正处于强势之中的原油市场而言，任何的风吹草动都有可能刺激油价上扬，更何况是主要产油地区的紧张形势呢？

产能不足引发市场担忧

目前，欧佩克的原油日产量已达到3040万桶，而且还在继续上升，佩克增产原油已经导致过去两年全球原油供应量超过需求量，使得原油库存量持续上升，并已明显高于过去5年的平均水平，而全球2005年的需求却相对2004年有所减少。可见，总体而言，全球供应并不短缺。然而，炼油能力的不足却直接制约了油价回落，这也正在成为全球的共识。由于过去油价一直处于相对低位，各国炼油的利润均较低，新建炼厂的投入又相当的大，而且牵涉到环保等多方面问题，故近30年来美国和欧洲国家都没有兴建新的炼油厂。现有炼厂的加工能力又受投资规模大、投资回报时间长的影响，近5年来总的炼油加工能力没有出现大的改观，这与3年来世界对石油产品需求量大幅增加形成了极大矛盾，直接导致总的炼制能力跟不上上游原油产量的增长，从而影响了成品油的市场投放量，导致市场恐慌。

基金入市推动油价上涨

今年五月份，随着NYMEX原油价格从接近60美元／桶的高位一路回落，基金净多持仓一路减持，五月底甚至一度成为净空状态。然而，油价的持续回升很快使得大量基金重新入市作多，并很快回升至2-3万手的净多状态。

作为近年来国际游资大量出入的原油市场，良好的基本面，以及众多的炒作因素，成为基金一直青睐原油市场的主要动因。近期，持续增加的净多持仓再度成为推动油价上涨的润滑剂也就不足为奇。

整体看来，在57-62美元区间进行充分震荡整理之后，国际原油价格选择向上突破，无论是从投资者心理上，还是市场的实际走势上，66美元都不可能是个顶部，市场很可能继续向上。

国内燃料油期货或突破3000元／吨

回到国内燃料油期货市场来看，尽管2950-3000元／吨是投资者心理的绝对高价区域，但随着国际原油的持续高涨，远期合约在价格上涨的过程中出现明显增仓，可见投资者仍积极看好后市。

分析人士预期，只要原油价格继续保持上升势头，则国内燃料油期货主力合约突破3000，并进一步走高应是迟早的事情。




【时事点评】请大家注意这么一段，原文是，国家信息中心预测部国际石油问题专家牛犁表示，就基本面而言，并无任何新增的不利因素，导致国际油价上涨的还是那些已知的不确定因素，诸如伊朗核问题、沙特可能爆发恐怖袭击等等。

*** “基本面未发生大变动”的观点、是非常值得商榷的

此外，我们也注意到，一位国际著名证券公司能源分析师认为，在基本面未发生大变动的情况下，油价连破新高，肯定是又有新的炒家入市炒油。两位专家均认为，短期来看，油价一鼓作气突破70美元完全可能。

显然，以一般的、国际原油市场投资的分析策略去看，两位专家说的都有道理，但是，如果我们从国际能源的政治背景去看、就不难看到，国家信息中心预测部国际石油问题专家牛犁先生所说的“就基本面而言，并无任何新增的不利因素”、以及那位国际著名证券公司能源分析师所认为的、“基本面未发生大变动”的观点、是非常值得商榷的。

*** 面对高得离谱的油价、世界“最大的油老虎”的态度却“显得相当超然”

在这里，东方经济评论员认为，我们的判断与上述观点刚刚相反、即，第一，就基本面而言，绝非“并无任何新增的不利因素”、而是“新增了”大量不利因素；第二，基本面绝非“未发生大变动”、而是“发生了重大变动”。

在东方评论员看来，最能体现原油市场基本面的“不利因素与重大变动”的，莫过于华盛顿的“公开立场”：我们主意到，近一年多来，伴随着国际油价的“屡创新高”的、世界“最大的油老虎”美国的态度却“显得相当超然”。


*** 华盛顿的“超然”、与一系列“不为人所知的隐密因素”息息相关

在油价已经达到历史性的66美元、且油价短期可能破70美元的今天，东方评论员注意到，美国财长斯诺却显得异常轻松，一句“美国政府没有考虑释出战略石油储备，以遏止持续上升的油价的需要”、再次让人感觉到这个世界上“最大的油老虎”、似乎根本就不在意这令人咋舌高油价。

我们认为，华盛顿对油价的态度“如此超然”、与一系列不为人所知的隐密因素息息相关。


*** “维持高油价”，可以说是与华盛顿的全球战略相吻合的

首先、在东方评论员看来，在这个时期之内“维持高油价”，可以说是与华盛顿的全球战略相吻合的。事实上、自上一次石油危机之后，可以说在这几十个的时间里，美国已经完成了产业结构和能源结构的调整，油价的上涨对其本国的影响已经大大小于当年两次石油危机时期；

然而，中国产业结构和能源结构、却让中国经济处在对高油价极其敏感的时期。同时，我们不要忘记了，美国消费者一样会受到高油价的损害，但是，美国的大公司在全球从事石油开采，这笔损失又从其海外业务中得到了一定补偿。所以说，总体上讲，高油价对美国经济的“影响不大”，但对中国经济的影响却“非常之大”，此外、高油价对欧洲经济的影响也非常之大、起码比美国要大得多。


*** 北京不能不警惕华盛顿这种借高油价、图谋“双重政治目的”的策略

事实上、在以往的10年，可以说直到2003年以前，国际油价都很平稳，大概就是每一桶25美元上下，低的时候只有10美元。今年突然涨得如此疯狂，不论是对中国、还是对欧盟来讲，这都是一个非常让人头疼的“变数”。

考虑到近来欧美、特别中美在在一系列战略问题上的激烈较量、东方评论员认为，北京不能不警惕华盛顿这种借高油价推高中国经济运转成本、从而遏制中国发展的策略，也不能不警惕华盛顿有意“借高油价”压迫欧盟、以及中国在许多战略问题上妥协的可能性。


*** 华盛顿曾经将“高油价”作为筹码、让欧盟、中国在伊朗核问题上“小心一点”

显然，在东方评论员看来，华盛顿最想压中欧让步的方向就在中东、最想让中欧让步的就是伊朗问题。


就目前而言，解决伊朗核问题、似乎只有两种方式，一种就是欧洲的“和平方式”，说白了，就是给伊朗的毛拉们一些甜头，即包括把伊朗从“邪恶轴心”的名单中拿掉，恢复与伊朗的外交关系以及解除经济制裁。

而另一个方式，也就是美国新保守主义者一再公开、或者暗示的“武力方式”，就是继续高举大棒，对伊朗根本就不会给哪怕是一根胡萝卜。

事实上，在我们看来，除了欧盟国家在伊朗有大量投资这一因素之外，欧盟之所以强烈主张“和平方式”、而美国似乎有足够的胆量搞“武力推翻”，其实也是与“石油”这两字紧密相关的。

据我们掌握的资料，布什在去年当选连任后、华盛顿就放风说可能将增加3千万桶石油储备。在东方经济评论员看来，华盛顿的“这个放风”、其意图就是想让“当时的市场”预期“油价将再次突破50美元大关”，从而以此为筹码、压“对油价远比美国感冒”的欧盟、中国在伊朗核问题上“小心一点”。


*** 伴随着伊朗核问题的“一再紧张”、油价一再突破历史新高、绝不是单纯的投机因素


根据我们的观察，华盛顿这一次又在玩这种把戏、在我们看来、伴随着伊朗核问题的“一再紧张”、油价一再突破历史新高、绝不是单纯的投机因素、其中、美国的政治意图是主要因素。

显然，东方评论员认为，华盛顿可以将“增加石油储备”作为警告中国、欧盟的信号，这是在美国近8亿桶石油战略储备“完全可以”取代伊朗“一年的出口量”这一能力“做为支撑的”。

假如美国和以色列试图去轰炸伊朗的核设施，那么、在我们看来，石油价格升到100美元一桶的天价、“绝非天方夜谭”，到时、谁能承受？谁又不能承受?在华盛顿决策层的眼里、其答案是不容置疑地。我们认为，这一点、通过华盛顿“非常愿意”在高价时继续买油、继续充注其本已十分巨大的石油储备之举动、就可以非常清楚地看出、


*** 华盛顿“玩高油价”也别玩得太过份了

现在，伊朗已经将联合国原子能组织的“核封条”给扯了，声称将继续其包括“浓缩铀计划”在内的“民用核事业”，在我们看来，这与今天的“油价又创新高”是紧密相关。

在之前的点评中、我们已经说过，在伊朗核问题上，伊朗保留和平利用核能权力是美国的“底线”，而这却是“中欧俄”“下限”、也就是说、与其说是伊朗要保留和平利用核能权力、还不如说是“中欧俄”、以及许多阿拉伯国家在“努力为伊朗”保留住这一权力，因为只有保留这一权力，“中欧俄”才能向伊朗提供民用、或军事用途的“不同浓度”的浓缩铀、才能在战略需要的情况下、伺机打出“中东核竞赛”这张牌：或来平衡有以色列这个“准核武国家”帮助的美国、在中东的拥有的绝对军事优势、或用来从根本上破坏美国的中东战略、更或者本身就是对美国“高油价策略”的一种“制约”，这就是说、你华盛顿“玩高油价”也别玩得太过份了。否则，一个核武装的伊朗、或者美国在还没有从伊拉克上岸之前、就趟伊朗这趟混水，绝对将彻底改变中东、中亚的政治地图，尽管“中欧俄”分别在中东、中亚的利益也将因此受到冲击。


*** 不论是“中欧俄”还是美国、在伊朗问题上是各自抓了一张大牌


显然，就目前而言，不论是“中欧俄”还是美国、在伊朗问题上是各自抓了一张大牌、美国手中的牌就是军事打击（不一定是占领）伊朗后、它有能力“享受”100美元一桶的“天价石油”，而“中欧俄”手中的牌就是一旦伊朗遭到军事打击，“保不齐”伊朗就真给“一夜之间打成了一个核国家”，事实上，在伊朗到底有无核武器的问题上、美国和以色列各自得到的情报、还就是“说不到一块去”。

另外，从国际政治的角度去看，目前中国原油进口50%依赖中东，而中东由于美国石油霸权的存在，再加上海上运输线在美国海军的手中、如此一来，长远而言，中国的石油供应实际上隐伏极大的政治风险。但是，在我们看来，就眼下情况来说，在石油问题上，中国“最现实的麻烦”源于自身经济结构上的弱点。


*** 中国在经济结构上的弱点、实际已经给了美国施展“高油价策略”的空间

在东方评论员看来，中国的经济结构、实际上不可避免地将自己在能源上的弱点暴露给了对手、从而给了别人美国施展“高油价策略”的空间。我们认为，就石油期货市场而言，这一轮的石油期货价格暴涨有一点不正常，绝对有国际炒家“炒作”“中国弱点”的成分在里面。

东方经济评论员认为，从市场的角度来看，“中国的市场弱点”大致如下：

第一，中国“每年需求的增量”中，进口油已占到40％的比例，显然，仅此一点，就足以构成一个国际投机资本“重点炒作目标”。

第二，在东方经济评论员看来，更重要的是，按计划、中国在“今年”将要增加石油储备“安全天数”，显然，中国的“这个计划”无疑给了国际投机资本以巨大的想像空间。

就目前而言，中国的这个“安全天数”可是10天都不到、而按计划、这个“安全天数”将达到90天。不难想像，从10天跃升到90天、中国将要购买的原油、该是多么巨大的一个数字。


*** 中国的“石油储备计划”、释放出一个极其强烈的“多头信号”

在东方经济评论员看来，中国的“石油储备计划”、等于给全球石油投机商释放出一个极其强烈的“多头信号”。

第三，也是极其关键的，那就是中国国内明显缺乏可以把握石油期货市场运行窍门的专门人才、另外、中国操作外汇等金融期货的能力也非常低、这些注定了中国在石油相关投资市场的操作经验不足，谁都相信，现在正是对中国下手的时候。

第四，必须指出的是，在我们看来，中国在产业政策上显然有“明显的失误”，东方经济评论员向来认为，从中国本身利益、和能源情况来说，私人汽车本来就不应该成为什么“主导工业”。

众所周知，上个世纪70年代几次石油危机之后，一些国家已经调整交通工业政策，大力提倡公共交通，而控制私人汽车的发展，而中国却反道而行之，搞什么汽车支柱行业、还从政策上倡导小汽车大量进入家庭，显然，国内的石油需求已经是高居不下，私人汽车业的发展只能促使这种需求的“继续飙升”。在我们看来，对这一决策失误，北京有必要做出调整。


*** 朝核问题六方会谈复会之前，极有可能出现两个局面
　　
另外，东方经济评论员认为，就近期的投资建议而言，由于美国汽油库存连续六周下降，减少210万桶至20310万桶，比去年同期减少790万桶，我们认为，如果在朝核问题六方会谈“复会日期”到来之前、“中欧俄”与美国之间在伊朗核问题上谈不出个结果来，且中日关系没有出现什么“重大事件”，那么，极有可能出现两个局面：第一，是石油价格上的，我们认为，石油价格很有可能在未来两周之内上70美元一桶大关、甚至测试74美元价位；

在东方经济评论员看来，华盛顿今天借一则未经证实的消息、就关闭了驻沙特使领馆、从而引起石油价格的一轮狂飙、已经为美国一旦需要、在下一步通过补充汽油库存、继续“玩高油价”腾出了空间、并“打下了非常好的基础”。

第二，是国际政治层面的，东方评论员有观点是、“六方会谈”的体会期可能再次延长。这一点、在前面东亚部分的点评中、我们已经给出了详细分析。

下面，是一则有关美联储调高利率的报道，在一起了解相关内容之后，东方经济评论员将就人民币利率、汇率未来趋势给出我们的观点。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com


