# -*- org -*-

# Time-stamp: <2011-08-04 00:36:42 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 2005年6月30日 星期四



** 胡锦涛访俄中俄将发表世界秩序宣言

【综合消息】中国国家主席胡锦涛这次出访俄罗斯。旨在于边界问题解决之后，中俄一方面务实解决老百姓关切的具体问题，另一方面谋求破解某些国家独断专行的国际形势。

两国领导人将签署关于21世纪世界秩序的联合宣言，这一重要的政治文件反映了两国对当今世界关键问题的一致看法和对人类发展前景的相同观点。双方认为“不应把国家分成三六九等”。

今年6月2日，中俄互换了《关于俄中国界东段的补充协定》批准书，两个大国经过近40年的谈判，首次以法律形式确定了全部边界线走向。胡锦涛行前通过俄罗斯媒体宣布：“中俄关系已进入全面发展的新阶段。”

重心转向务实合作

随着边界问题的彻底解决，两国之间不存在妨碍双方发展战略伙伴关系的政治问题。俄罗斯外交官员认为，两国最高领导人的对话重心将转向直接关系到两国人民切身利益的、务实的互利合作。

在出访前夕，胡锦涛于6月21日在人民大会堂接受了俄罗斯俄通━塔斯社和俄罗斯第一电视台的联合采访。他指出，双方应加强两国在经贸、能源、科技、军事等领域的务实合作，丰富两国战略协作伙伴关系的内涵。

胡锦涛敦促俄罗斯“认真落实双方在能源领域的协议，努力使有关合作项目尽快实施”。

另外，中方将加强中方有关地区同俄远东和西伯利亚的经贸合作。中方也欢迎俄方积极参与中国振兴东北老工业基地和西部大开发。

“经济合作是双边合作的最重要领域。”俄外交部发言人雅科文科29日在《俄罗斯报》撰文说，目前两国已开始起草2006年至2010年双边经济关系中期发展规划。双方在这份文件中将全面分析两国合作潜力，并采取实际步骤消除阻碍双边经济合作持续发展的问题。

国家不分三六九等

中俄关于21世纪世界秩序的联合宣言将重申，两国主张在尊重国际法、多边主义、平等和相互尊重及提高联合国在国际政治中作用的基础上，建立公正合理的世界新秩序。

俄罗斯外交部发言人雅科文科29日撰文说，俄中一致认为，在国际事务中不应独断专行，不应把国家分成三六九等，不应把社会发展模式强加于人及实行双重标准。国际社会应共同努力，建立新的安全模式，在联合国主持下确定应对新威胁和挑战的全球战略。



【时事点评】东方评论员注意到、胡锦涛主席在出访前接受俄罗斯媒体的联合采访中明确表示“双方应加强两国在经贸、能源、科技、军事等领域的务实合作，丰富两国战略协作伙伴关系的内涵”。

*** 胡锦涛与普京将要谈的“核心”就是“务实合作”

在我们看来，胡锦涛的这一句话中，虽然范围很广泛，但是，从中可以非常清楚地看出，那就是他这次访俄、与普京将要谈的“核心”只有四个字、那就是“务实合作”。
事实上，东方评论员认为，就目前而言，中俄间堪称为“务实合作”的、实际上体现在两个方面：首先就是军事合作，这表现在中国出于战略需要、大量购入俄罗斯的武器系统；其二，就是能源合作了。

*** 俄罗斯是全球最大“独立自主的能源供货商”

在东方评论员看来，近来，由于美国旨在谋求夺取中东油源的战略目的、而强力攻打伊拉克、让整个中东“处于不稳定状态”，因此，不论是对欧盟、还是对中国而言，俄罗斯作为全球最大的、“独立自主的能源供货商”的地位、也日益显露出来了。


其中，最让中国和欧盟看重俄罗斯的，就是作为一个世界级的能源供应商，俄罗斯与中东和南美洲有着本质的不同、这表现在俄罗斯仍然保持着独立的外交政策，和强大的军事实力、这对中国和欧盟这两家欲与美国争天下的“政治经济实体”而言，是最为“难能可贵”的。

*** 如果不是有丰富的石油，俄罗斯恐怕根本就走不进“八国峰会”

首席评论员就认为，如果不是因为俄罗斯享有丰富的石油资源，俄罗斯恐怕根本就走不进“八国峰会”。

我们知道，在2003年，俄罗斯的石油产量和出口量均仅次于沙特阿拉伯，居世界第二位。而在现在，中国也已经取代日本，成为仅次于美国的世界第二大石油消费国。在我们看来，分别在“生产”和“消费”中占据“世界老二”位置的俄罗斯和中国，由于地理位置接近，经济互补、没有任何理由不搞好合作，实现双赢。


*** 在“彼此都高度敏感的问题”上、双方的意见却往往表现得“不那么一致”

然而，由于俄罗斯在刚刚过去的两个世纪里，无论在经济还是军事方面，可以说都一直领先于中国，期间、甚至作为一个超级大国而傲视天下。因此，在东方评论员看来，就中国目前的发展势头而言，曾经辉煌的俄罗斯、是很难就这么心甘情愿意地、眼睁睁看著中国发展成为一个强大邻国的。

东方评论员认为，也正是在这种心理下，使得两个国家在一些“彼此都高度敏感的问题”上、比如中亚安全问题、俄罗斯石油管道走向问题、朝鲜半岛主导权问题等等、意见却往往表现得“不那么一致”。


*** 让俄罗斯担心的是，过去二十年来，北京“反思了太多”、却唯独没有反思“对苏政策”

东方评论员认为，之所以有所谓的“彼此都高度敏感的问题”，其原因归结起来有这么几条：第一，在俄罗斯看来，中国强大后，自然要试图获取亚洲、以及亚太地区的主导权，而这个地区是“强权环伺”，其中就是美国与俄罗斯、以及日本，因此，“这个过程”很可能是一个伴随着冲突甚至战争的过程，并然冲击到到这一地区的稳定和俄罗斯的安全；

第二，也是最让莫斯科警惕的、就是中国世大的人口优势、对俄、尤其是远东地区构成了巨大的压力。在东方评论员看来，这一点也许中国民众“并不太理解”，然而，对俄罗斯而言，却是一个巨大的心理压力。

特别让俄罗斯担心的是，自搞改革开放之后，北京对过去的许多政策、包括对外政策都进行了“再认识”。可以说在过去的二十年中，北京反思了太多的东西、但唯独没有反思“对苏政策”，也没有改变关于沙俄占领中国领土的宣传方式，对这些，俄罗斯可谓是“点滴在心”。

在东方评论员看来，这一切，站在北京的角度，当然都有道理，但是，一经站在俄罗斯的立场、“设身处地”一番的话，那么，在俄罗斯决策层的眼里，北京这是在有意为以后中国强大后向俄提出领土要求而“预埋伏笔”；


*** 俄罗斯决策层总算是明白过来：一个稳定、有内涵的中俄关系实在是太重要了

不过，在我们看来，在经历了欧美这一年多的强力挤压、特别是欧美在前苏联盟共和国搞成了一连串的“颜色革命”之后，可以说将俄罗斯的往中东和欧洲方向的战略空间“榨挤得”一干二净。从发展的现实利益出发，俄罗斯决策层现在总算是明白过来：一个稳定、有内涵的中俄关系、实在是太重要了。

根据我们的观察，俄罗斯内部在总结中苏对抗时期的“惨痛教训”的时候，曾经有过一个共识，那就是，即使与西方的关系进行顺利，如果与中国再次发生对抗，也将会“导致形势极其危险的不稳定，军费不可容忍地增长，最终导致整个改革计划的破产”。


*** 北京又何尝没有可供“反思”之处？

在东方评论员看来，由于近来周围国际环境的巨变，对俄罗斯而言，无论是俄国内经济发展的命运，还是它在世界舞台上的地位、已经都开始直接取决于同中国关系“性质”了。

因此，我们认为，除了同中国建立“积极和充实”的睦邻关系外、俄罗斯别无选择。也正因如此，东方评论员再次注意到、俄罗斯国内甚至产生有这样一种观点，即干脆认为，“从保障俄罗斯的安全角度看，俄罗斯与中国的关系比与美国的关系更为重要”，只是在东方评论员看来，这种看法对北京而言，又何尝没有可供“反思”之处？

事实上，北京一度就因过于看重中美关系的重要性，而一度让其他国家对中国产生了不信任感。好在经过一年多的调整，现在的中美关系已经被中国决策层完全放在了“综合考虑”之中。

东方评论员认为，随着台海一年以来的“风高浪急”、以及华盛顿在中东的“一筹莫展”，北京已经调降了中美关系的重要性、强化了与欧盟的战略合作，在东方评论员看来，中美、中欧关系之所以重要、且相对稳定，就在于这两种关系除了有着千丝万缕的政治因素外、还在于这两种关系都有着丰富的内涵，既相互间超千亿美元的经贸关系。

在我们看来，中美关系的调降，中欧关系的调升、都是建立在综合政治、经济、军事的综合考虑中的“务实的合理调整”。

因此，在东方评论员看来，如何让这些“让莫斯科紧张的问题”不再阻碍中俄关系的进一步提升，北京显然也已经找到了一个“法门”，这就是胡锦涛主席行前所强调的“务实合作”。

为了更好地说明这个“务实合作”，我们一起继续阅读一篇新闻稿，之后东方时事评论员将继续这个话题。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com


** 俄外交部发言人撰文高度评价俄中两国关系

【莫斯科消息】据新华社莫斯科电，俄罗斯外交部发言人雅科文科２９日在《俄罗斯报》撰文说，俄罗斯和中国在各领域的关系充满活力，目前两国关系正在新的历史背景下继续向前发展，这符合两国人民的利益。

雅科文科说，今年６月２日，俄中两国互换了《关于俄中国界东段的补充协定》批准书，两个大国经过近４０年的谈判，首次以法律形式确定了全部边界线走向。随着边界问题的彻底解决，两国之间不存在妨碍双方发展战略伙伴关系的政治问题。两国最高领导人的对话重心将转向直接关系到两国人民切身利益的、务实的互利合作。

雅科文科指出，经济合作是双边合作的最重要领域。俄中贸易额在去年突破２００亿美元大关后仍在继续高速增长。双方投资合作的规模不断扩大。俄中双方于２００４年６月在俄哈巴罗夫斯克举行的俄中第一届投资促进会议上签署的一系列中国对俄投资项目已经进入落实阶段。今年６月在圣彼得堡举行的俄中第二届投资促进会议上，中国对俄投资的地理范围进一步扩大，投资金额也有了大幅度提高。目前两国已开始起草２００６年至２０１０年双边经济关系中期发展规划。双方在这份文件中将全面分析两国合作潜力，并采取实际步骤消除阻碍双边经济合作持续发展的问题。

雅科文科还谈到，目前两国在科技、环保及医疗、体育、旅游等领域的合作也在迅速发展。

谈到中国国家主席胡锦涛即将对俄罗斯的访问，雅科文科说，胡锦涛访俄期间，俄中两国领导人将签署关于２１世纪世界秩序的联合宣言，这一重要的政治文件反映了两国对当今世界关键问题的一致看法和对人类发展前景的相同观点。宣言将重申，两国主张在尊重国际法、多边主义、平等和相互尊重及提高联合国在国际政治中作用的基础上，建立公正合理的世界新秩序。

雅科文科说，俄中一致认为，在国际事务中不应独断专行、不应把国家分成三六九等、不应把社会发展模式强加于人及实行双重标准。国际社会应共同努力，建立新的安全模式，在联合国主持下确定应对新威胁和挑战的全球战略。

胡锦涛主席将于６月３０日至７月７日对俄罗斯和哈萨克斯坦进行国事访问，并出席在英国举行的“八国集团与中国、印度、巴西、南非、墨西哥五国领导人对话会”。访问哈萨克斯坦期间，胡锦涛将出席在哈首都阿斯塔纳举行的上海合作组织元首会议。



【时事点评】请大家注意这一段文字：“随着边界问题的彻底解决，两国之间不存在妨碍双方发展战略伙伴关系的政治问题。两国最高领导人的对话重心将转向直接关系到两国人民切身利益的、务实的互利合作”。


*** 普京对胡锦涛访问的“期待”、也是“务实合作”这四个字

显然，在东方评论员看来，俄罗斯外交部发言人雅科文科在胡锦涛到达莫斯科前夕、于《俄罗斯报》发表的这篇文章，其“核心”还是只有四个字，也是“务实合作”，我们认为，普京对胡锦涛这次访问的“期待”、还是这四个字。


*** 俄罗斯的一个巨大的现实利益就是“如何参与到亚太事务”中来

对北京而言，将中俄已经达成的能源协议尽快落实、使有关合作项目（能源和军事上的）尽快实施、消除扩大双方贸易与投资的障碍、“共同强化”上海合作组织在确保中亚国家国家稳定方面的“作用和工具”、都是事关中俄大局的“务实问题”、“现实利益”，也将是这次访问需要敲定的事情。

然而，首席评论员指出，其实在普京的手中、还有一个“巨大的现实利益”、要与胡锦涛商量着办：即“如何参与到亚太事务”中去。在我们看来，“确保俄在亚太的大国地位”在俄罗斯“恢复大国地位”战略中，占有举足轻重的地位。

众所周知，亚太已经成了世界的政治、经济中心，也已成为中、美、日、俄诸列强角逐的主要地区之一，地处欧亚大陆中心地位的俄罗斯，独独对此鞭长莫及。因此，在俄罗斯决策层的眼里，俄如想重新站起来，也必须主动参与亚太事务，争取获得与其他大国平等的地位，并在地区政治、经济、军事方面发挥重大作用、从而从亚太的发展中分得一份利益。


*** 俄罗斯要想在亚太表现得象一个大国，就得依靠北京的“引见”

然而，近十年的事实证明，华盛顿和作为美国小伙伴的日本、是绝不会主动协助俄罗斯提高在亚太的作用的，因此，俄罗斯要想在亚太表现得象一个大国，就得依靠北京的“引见”、希望中国帮助俄罗斯参与亚太地区的事务了。


*** 朝核问题就为俄罗斯提供了一个绝佳的“切入点”

为达成这一战略目的，在东方评论员看来，朝核问题就为俄罗斯提供了一个绝佳的“切入点”。

俄罗斯的战略企图是通过参与朝鲜半岛和平进程，至少可达到两层战略目的：第一，在地缘政治层次上，意图借以恢复俄罗斯在东亚的传统影响力，从而以东北亚为突破口，继而扩展到整个东亚，直到破解美国在欧亚大陆上对俄罗斯布置的战略合围圈；


第二，在经济层面，俄罗斯想把远东、西伯利亚地区融人亚太经济发展的一体化进程。在这里，介入朝鲜半岛经济整合，参与东北亚、或者东亚经济一体化，正是俄罗斯这一整体战略的“入门一步”。


*** 北京在全面提升中俄关系策略上的“不二法门”

东方评论员注意到，在俄战略分析人士看来，俄罗斯远东地区资源丰富、潜力巨大、周围就是中国、日本、韩国这三个东亚经济实力最为庞大国家，如果借这几个国家的力量、带动远东地区经济的发展、就可以成为带动整个俄罗斯经济振兴的新的增长点。

不难看出，在如何让这些“让莫斯科紧张的问题”不再阻碍中俄关系的进一步提升的问题上，胡锦涛主席强调的“务实合作”，在方向上显然颇合普京的胃口。

由此可见，北京在全面提升中俄关系的策略上，其“不二法门”就是放心地让俄罗斯的资源、“全面介入”朝鲜半岛经济整合、“东北亚经济一体化”进程，并以“东北亚经济一体化”为“支点”，以实际行动去帮助目前还不算“亚太国家”的俄罗斯、参与到亚太事务中来。


*** 边界问题的“彻底解决”，是“中俄决策层”决心全面提升战略关系的“最好注解”


我们认为，困扰中俄多年的边界问题的“彻底解决”，本身就是“中俄决策层”决心撇开政治因素、全力推动包括俄罗斯远东地区的“东北亚经济一体化”进程、全面提升战略伙伴关系的“最好注解”。

然而，东方评论员也注意到，俄罗斯的战略家们始终相信“亚太国家之所以仍严肃地看待俄罗斯的地区领袖地位，只是由于俄罗斯尚存相当大的军事力量”。

对此，首席评论员的“解读”是：任何一个国家想在东亚保持长久的影响力，在地区事务中起主导地位，不仅取决于其经济条件和能力，更是“首先取决于”其军事实力。


*** “中俄”联合军演最主要的目的旨在为朝鲜半岛经济整合“提供条件”

在我们看来，如果从这个角度去考虑整个东亚局势，就不难理解“中俄”为何有兴趣在这个时候举行大规模、高层次、跨国界的联合军演了。

一般认为，这是北京想借俄罗斯军力来“策应”台海。然而，东方军事评论员认为，从演习地点更加靠近朝鲜半岛、演习时间充分考虑到了7月份可能恢复的“六方会谈”来看，此次军事演习固然有警告美日“介入台海企图心”之目的，但是，最主要的恐怕是以“中俄”的强大军事实力、在“为朝鲜的合理要求”“张目”、为周围国家都需要的朝鲜半岛的和平与稳定进行“保驾护航”、也是为韩国能顶住美国的压力、着手进行的朝鲜半岛经济整合“提供条件”。


*** 如果俄罗斯能从东北亚打开突破口、也就掌握了介入亚太事务的“要领”

显然，如果俄罗斯能从东北亚打开突破口、在朝鲜半岛经济整合中站住脚、也就掌握了介入东北亚、以至亚太事务的“要领”：即，俄罗斯的下一个突破方向和突破点早就选好了，这分别就是整个东亚、以及美国的盟友日本。

到了这个时候，俄罗斯对日本的确就“有牌可打”了，一旦中国、俄罗斯、韩国、朝鲜在“东北亚经济一体化”的问题上，搞出了点名堂，那么，这就意味着美国在朝鲜半岛的影响力已经被大大削弱了。在东方评论员看来，如真到了这一步，那么，中俄这次将要发表的“世界秩序宣言”、也算是结出了硕果。


*** 北京其实也可顺便达成自己的战略意图

东方评论员认为，在这种情况下，俄罗斯手中的北方四岛对美日联盟的战略压力就突现出来、再加上俄罗斯庞大的资源，东北亚经济一体化产生的商机，足以猛烈冲击一下“美日同盟”，一旦“美日同盟”象今天的“美韩同盟”一样、在巨大的现实利益、与代价巨大的政治野心的“相互拉扯”下、彼此产生“离心力”的话，那么，不仅俄罗斯撕开了美国针对其的包围圈，北京其实也可顺便达成了自己的意图，实现了让“东北亚经济一体化”催生“东亚经济一体化”的战略目标。


*** 胡锦涛与普京会面要谈的“第一要务”

因此，在东方评论员看来，普京手中的这个“巨大现实利益”，又何尝不是北京的“巨大现实利益”呢？我们认为，“如何确保”朝鲜半岛的和平与稳定，帮助朝鲜半岛进行经济整合，这才是胡锦涛与普京会面要谈的“第一要务”。

只是在首席评论员看来，如果时局果真如此发展，那么，在这整个过程中，在主导权的问题上，中、俄、韩、甚至还可能有日本、和美国、都将有一番激烈地争夺，只是最后谁能笑到最后，是北京如愿、还是华盛顿如意、或者是俄罗斯是最大赢家，只能由事实说了算。


*** 争夺朝鲜半岛主导权，是美国“全球棋局”布势上的重要一步

由此可见，如何解决朝核问题、在东亚、以至亚太格局的发展中，处于何等的“关键地位”。东方评论员认为，争夺朝鲜半岛主导权，是美国“全球棋局”布势上的重要一步，在这一点上，华盛顿是决不会让步的。

不过，争夺的手段有硬也有软，在”硬的手段“不起作用的时候，“软的手段”就要上场了。

*** 国际时局的一个最大变化

目前，国际时局的一个最大变化是向来强硬的布什，正满脸堆笑地、围着中国边境“大搞公关”：日前，布什邀请越南领导人访问美国，让拉姆斯菲尔德找向伊拉克游击队“求和”，最大的手笔就是用“签定了10年国防协议”的方式、向印度“表明心愿”：“让印度成为世界主要发达国家”。

如此等等，单单没有对法国、德国、中国、俄罗斯这几家有能力阻止美国独霸全球的强权“网开一面”。由此可见，美国的“笑脸外交”是多么地具功利与针对性。

在东方评论员看来，由于华盛顿在伊拉克问题仍然无解，中、法、德、俄“仍然在压”美国在巴以问题上“继续往前走”，否则、伊朗核问题也难保不恶化，而也就在这个背景下，由于韩国的“出逃”，它在朝鲜问题上遭到了巨大困难，可以说其强硬的朝核政策到了无以为继的地步。

*** 美国各种势力是轮番出阵，就差对中国公开宣战了

因此，美国决策层将目标调到了中国身上，将因伊拉克战争而对法、德“打击报复”的那一套，全部搬到了北京身上，在东方评论员看来，其对中国的恐吓攻击到了无以复加的地步。

东方评论员注意到，一连数天，其国会议员、媒体以及智库专家，是轮番出阵，就差对中国公开宣战了。只是，这有用吗？在东方评论员看来，华盛顿不能把法国、德国怎么样，恐怕这一次也不会得手，因为中国更不容易被征服、毕竟在中国的手里，可以打的牌比法国、德国更加多。

东方评论员认为，对华盛顿而言，用什么手段不是主要的，保证美国在亚太地区遏制俄罗斯、中国的战略部署不被打乱，确保下个世纪美国的全球霸权才是主要的。

在一段来自美国国务院的最新消息后，东方评论员将继续讨论在中美俄日角力下的朝鲜半岛局势。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
