# -*- org -*-

# Time-stamp: <2011-08-03 23:39:09 Wednesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

* 2005年6月29日 星期三

** 黄长烨：六方会谈最终是中美问题非朝韩问题

【汉城消息】据联合通讯社报道，朝鲜民主化同盟委员长、朝鲜劳动党前秘书黄长烨说：“朝鲜直到最后都将采取拖延战术，直到美国政府换届六方会谈也不会有结果。”

据自由朝鲜广播报道，２５日黄长烨在首尔市某处会见了美国保守派人士、哈德森研究所首席研究员霍罗威茨和美国宗教联合会主任黛博拉·菲克斯，就六方会谈的前景做出上述表示。

黄长烨说：“朝鲜绝不会进行核试验，而且必将参加六方会谈。”并主张说：“现在，朝鲜正在六方会谈问题上拖延时间。这只不过是提高中国和俄罗斯的国际地位并拉拢韩国的手段。”

黄长烨接着预测说：“最后人们会知道，在采取这种拖延战术之后，朝鲜将向韩国索要比金大中时期更多的补偿，使南韩亲北化。”

他表示：“我认为，朝鲜在六方会谈中不会接受美国提出的方案。”并预测说：“朝鲜将继续按照自己的方式使用欺骗手段，而韩国会像金大中政权时期那样，试图基于在南北关系中已取得的成就实现政治目的。”

当被问及“是否认为提及朝鲜人权问题就可以使金正日政权的状况恶化”时，他表示：“这是不值得回答的问题。只有推翻金正日政权，朝鲜才能实现民主。”

报道称，美国的朝鲜民主化相关团体将于两周后发表关于对华战略的声明。黄长烨对此表示：“抓住金正日政权命脉的是中国，在朝鲜的同盟关系中，断绝其与中国的关系，所有问题都会得到解决。六方会谈最终还是美国和中国的问题，而不是朝鲜和韩国的问题，期望通过会见金正日解决问题只是基于错误想法的错误举动。”



【时事点评】事实上，在东方评论员看来，这位朝鲜叛逃的这位最高级别官员所讲的这段话，为华盛顿的朝核政策进行宣传的意图明显、但是，他也的确提出上面两个“实质性的观点”，即：第一，六方会谈最终还是美国和中国的问题，而不是朝鲜和韩国的问题；第二，朝鲜将向韩国索要比金大中时期更多的补偿，使南韩亲北化。


*** 华盛顿何以“特别喜欢”强调北京的重要作用？

东方评论员认为，对“朝核危机”，华盛顿之所以“特别喜欢”强调北京的重要作用，其根本原因就如黄长烨所说的那样，是因为“抓住金正日政权命脉的是中国，在朝鲜的同盟关系中，断绝其与中国的关系，所有问题都会得到解决”。


*** 北京对华盛顿是“道不同”也就“不相为谋”的态度

然而，在东方评论员看来，黄长烨给华盛顿的这条“建议”倒是不错，只是华盛顿要想让中国断绝与朝鲜的关系，事实已经证明：这可是一件难上加难的事儿。

因华盛顿一味的搞强硬朝核政策，“六方会谈”中断已经是整整一年了。结果，美国“无条件地解除朝鲜核武器”的图谋不仅没能得逞，反而因朝鲜“宣布已经有核”而被狠狠地“将了一军”。

现在，华盛顿是从政府到国会，明里给中国“戴高帽子”，称赞中国在朝核问题中的作用是“如何如何的巨大”，实质上、却是在借此找机会把怨气发泄到中国身上，指责北京不对朝鲜施压，指责北京还在给朝鲜大量的经援，东方评论员认为，就差“直接揭露”中国在对朝鲜提供军事保护“这一条罪状”了。

而对华盛顿的“高帽子”也好、“明褒暗贬”的发泄也罢，在东方评论员看来，北京的“辩解方式”虽然含蓄、但却“极其到位”：一方面通过各种机会强调中国主张的是“半岛无核化”，本来就与美国“单纯的朝鲜无核化”是“道不同”。


*** 如果没有北京护着，朝鲜恐怕早就完了

另外，华盛顿也始终没有忘记不时地将华盛顿“戴在自己头上的高帽子”摘下来，还给美国人，除了谦虚地声称“对朝鲜的影响力有限”之外，还强调“给朝鲜经援是出于人道主义考虑”，并有利于说服朝鲜回到六方会谈的谈判桌上来、未了，也总是不忘记用一句“各方都要拿出诚意”的话，“责备”就是美国把朝鲜视为必须推翻暴政国家，才变成如今这个局面的。

在东方评论员看来，如果没有北京护着，朝鲜恐怕早就完了，在这点上，朝鲜叛逃的高官，金正日的老师黄长烨所说的“抓住金正日政权命脉的是中国”，可以说是说到了点子上。

而让华盛顿痛恨的是，如今中国不仅护着朝鲜，还把自己的“责任”推得一干二净，并在世人面前、将一个“没有责任、不诚心解决朝核问题”的帽子“轻轻地放在”了华盛顿的头上。

显然，我们认为，北京对华盛顿种种做法的“不以为然”，全然是出于一种“道不同”也就“不相为谋”的态度、更是出于一种维护自己国家利益的决心、和对包括台湾、朝鲜、日本问题在内的东亚格局的“通盘考虑”。


*** 华盛顿“朝核政策”的“目的与本质”

我们知道，对华盛顿的“朝核政策”而言，其“目标”就是“先行解除朝鲜核能力”，其“本质”就是“搞跨金正日政权”，在朝鲜建立一个所谓的“民主国家”。

显然，在东方评论员看来，按华盛顿的这套策略，一旦先行解除朝鲜的核计划，那么，这不仅就解除了驻韩、驻日美军受到的威胁，同时，还可一举抽掉北京手上的“东亚核竞赛”这张牌，从而迫使手中无牌可打的北京、不得不在美国手中仍然挰有“台独牌”的情况下，更多地接受有利于华盛顿的战略安排。

一旦如此，目前已经对华盛顿表现出“离心力”、对北京表现出“向心力”的韩国、将在国家安全的重压下、立刻失去方向感，从而“快速回归”美韩军事同盟，重新依靠华盛顿。

在这种情况下，华盛顿再想通过军事高压逼迫韩国配合，全面制裁、并以此推翻、或者拖垮金正日政权，也就是“指日可待”的事情了。对此，中国决策层当然是“坚决反对”。


*** 伊拉克成为“民主国家”后的那种“混乱”、如果出现在朝鲜，恐怕美国人“梦寐以求”的


从伊拉克的例子来看，建立一个民主政权的最快手段就是军事手段。然而同样从伊拉克的例子可以看出，军事手段不仅快，而且“后遗症”也很大。

但是，在东方评论员看来，尽管华盛顿决策层在伊拉克“用刺刀”建立的民主的结果“差强美意”，但是，伊拉克成为“民主国家”后的那种混乱局面、以及对周围国家造成的冲击，如果能“移植到”地处中、日、韩、俄间“中心地理位置”的朝鲜、恐怕正是美国人“梦寐以求”的。


*** 华盛顿还曾经提出过这么一个“好建议”

事实上，据我们得到的消息，去年，在台海局势最为紧张、“台独”言行最为嚣张的时刻，作为交换，华盛顿还提出过一个“好建议”，即美国防部长拉姆斯菲尔德和副部长沃尔福威茨甚至一度“希望”北京去鼓动朝鲜士兵来发动一场政变，来推翻金正日政权。然而，北京没有笑纳这么个“好建议”，反而沉下心来，一面通过“反分裂国家法”彻底压住“台独”的嚣张，一面打算通过帮助朝鲜进行经济改革、来稳住金正日政权。


*** 美国想“和平”地“解除朝鲜核计划”已经成为了“不可能的事情”

一年多的“实践”证明，出于美国的全球战略，华盛顿不肯、也不会放弃利用“台独”实现遏制中国的战略企图，因此，也就不可能用一个美国控制的“台湾问题”、诚心诚意地换取一个中国主导的朝核问题。

显然，东方评论员认为，“朝核问题”之所以僵持在“是朝鲜先废核、还是美国先提供安全保证”的层面上，就在于朝鲜和美国彼此间“没有一点儿信任”可言，事实上，在美国把持的“台湾问题”和中国主导的“朝核问题”上之所以无法取得实质性进展，不也是因为中美间已经失去了“相互信任”吗？

在这种情况下，美国要想通过所谓的“和平方式”、借“六方会谈”或者是“除去朝鲜之外的'五方会谈'”、来达到“一步解除朝鲜核计划”的企图、事实上已经成为了“不可能的事情”，而想将金正日政权推翻、一个现在的办法就是在朝鲜“再如法炮制”一个推翻萨达姆政权的过程。

*** 华盛顿本想“杀鸡儆猴”、实际上却打出了“反效果”

东方评论员认为，美国摧毁萨达姆政权自然有太多的理由，然而，这“太多的理由”中，有一条就是企图“杀鸡儆猴”、要逼其他国家就范。

然而，在东方评论员看来，美国攻打伊拉克的行动、除了在利比亚小有所获之外，在其他的“热点”上、似乎产生了“适得其反的反效果”：即，这场战争可能让朝鲜和伊朗得出了“最大的危险”就是“不能制造核武器”的危险之结论。


*** 美国要想将伊拉克模式搬到朝鲜，就得克服“三大障碍”

可问题在于，美国要想将伊拉克模式搬到朝鲜，就得克服“三大障碍”：第一，就是这位朝鲜前高级领导人黄长烨在脱离朝鲜前往西方后，就已经透露了朝鲜“已经拥有核武器”，之后，朝鲜政府也公开承认“自己有了核武器”，这样，在东方评论员看来，这种来自“敌、我双方”的“共同证明”，可比此前许多“这样或者那样的传闻”要有说服力得多。

在东方评论员看来，朝鲜“有核、无核”带来的“不同”，恐怕只有华盛顿决策层心中最为有数。在我们进一步讨论这个话题前，再一起来看一则新闻，说的是驻韩美军最高指挥官拉波特“牛气烘烘”，声称“不管朝鲜拥有一枚还是多枚原子弹，美国和韩国军队都能将其击败”。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 驻韩美军司令:美韩军队能击败拥有核武器的朝鲜

【汉城消息】6月29日，韩国PBC电台播出了一期采访节目，驻韩美军最高指挥官拉波特在采访中表示，不管朝鲜拥有一枚还是多枚原子弹，美国和韩国军队都能将其击败。

　　据路透社报道，拉波特说，美军相信朝鲜至少拥有一两枚原子弹，而且正在改进导弹项目。他在28日接受PBC电台采访时说：“不管朝鲜拥有一枚还是多枚原子弹，都不会改变朝鲜半岛的军事平衡。”

　　他说：“美国和韩国不但有能力击退朝鲜的入侵，而且有能力在必要时大败朝鲜。”但他也指出，美国致力于六方会谈，寻求通过外交途径解决半岛核问题。美国官员也曾多次表示美国没有袭击朝鲜的计划。

　　拉波特说，美军认为，朝鲜拥有实质性的导弹项目，包括远程州际弹道导弹。如果这些州际导弹的能力得到提升，将可以击中美国大陆。

　　美国政府人士说，7月18日，负责处理朝鲜半岛核威胁的美国官员将在华盛顿的国防大学举行军事演习，以模拟应对可能发生的危机。





【时事点评】东方评论员注意到，驻韩美军最高指挥官拉波特显然“信心满满”、一句“不管朝鲜拥有一枚还是多枚原子弹，美国和韩国军队都能将其击败”的豪言壮语，显示出五角大楼的朝核态度“仍然是十分地强硬”。


*** 五角大楼在韩国的土地上狠狠地“揣了卢武铉一脚”

然而，我们也注意到，在另一个场合，有消息说，韩国统一部长郑东泳今天前往华盛顿访问，据说其主要任务就是“试图劝说美国副总统切尼“软化”对朝鲜的强硬立场”。

对郑东泳这次美国之行的“期待”，韩国官方说得非常坦率，那就是“想劝切尼对朝鲜说几句好话，从而有助于劝说朝鲜重返六方会谈，结束持续多时的朝核僵局”。显然，就在卢武铉让郑东泳揣着希望飞往华盛顿的途中、五角大楼就让自己的驻韩美军司令、在韩国的土地上狠狠地“揣了卢武铉一脚”。

*** 华盛顿在“低调”与“高调”、在“强硬与让步”中“反反复复”“很正常”

众所周知，由于朝鲜和中国出于自己的战略考虑，断不会“先行废核”，因此，在“先行废核”无望的情况下，华盛顿出于自己的战略目的，其朝核政策的核心就是“即不能彻底解决朝核问题，又要防止朝核问题进一步恶化”：既，在美国没有处理好中东问题之前，在没有做好对付中国的准备之前，美国的如意算盘是利用这个“六方会谈”、达到让朝鲜问题“谈而不决”的目的，是既不要“朝鲜核问题”如中国、韩国所愿的“分步解决”，又不要让它如日本渴望般地“逐步恶化”。

东方评论员认为，如果我们从这一角度去看华盛顿在“低调”与“高调”、在“强硬与让步”中“反反复复”、也就显得“很正常了”。


*** 美国决策层认为自己手上有牌

在东方评论员看来，这种战略心态上的矛盾，注定了美国在朝核政策上“言与行”的“处处矛盾”，即：一方面在朝核问题上表现出“强烈的急迫感”，另一方面却总是拒绝采取任何“实质性步骤”。

东方评论员认为，华盛顿之所以这样做，就在于美国决策层认为自己手上有牌，而且是好几张牌，足以让华盛顿在朝核问题上“收放自如”，不难看出，最能让华盛顿感觉收放自如的是“台独进程”、其次就是日本牌、最后就是军事打击朝鲜这张牌。


*** 北京经过一番努力与策划，也“有针对性地”抓到了几张牌

事实上，过去，华盛顿是“一直拒绝”与朝鲜进行双边接触，现在、针对美国手上的牌，北京经过一番努力与策划，也“有针对性地”抓到了几张牌：通过“反分裂国家法”让华盛顿操纵“台独进程”时不再象过去那样收放自如了；通过“一步步恶化”朝核问题、也限制了华盛顿打日本牌的自由度。

因此，现阶段对台湾问题没有“更大的幻想”而只限于“止独”的北京，一方面可以“不着急地”耐心等待台湾岛内国民党领导人之争的“结果”，之后再慢慢营造“两岸三通”的条件；而另一方面，也在不急不忙、却非常积极地暗中配合韩国的朝核政策、为“启动韩朝经济整合”创造条件；

现此同时，中国仍然不时地默许朝鲜“不时地用核武器”刺激美国、日本间“相互紧繃”的神经，而又在华盛顿极力阻止朝核问题滑向“东亚核军备竞赛”的过程中，北京也对日本仍然保持着强硬的政治压力、并开始放风要在经济层面“有所动作”、从而继续在这一层面挑拔美日间战略矛盾。


*** 眼下，在东亚方向，北京的真正重点是协助韩国“启动韩朝经济整合”

显然，首席评论员指出，种种迹象表明，眼下，在东亚方向，北京的真正重点放在了协助韩国“启动韩朝经济整合”的问题上。之前，我们多次强调，在华盛顿于中国周围“到处找盟友”的时候，北京的这一通“经济牌、发展牌”打得“甚合各方的人心”，在我们看来，在台海局势上、在中日关系上、在朝核问题上、甚至是在中亚、南亚问题上，都是如此。

在东方评论员看来，事实上，在这个世界上，一心想针对中国搞遏制的，只有两个国家，一个是美国，再一个就是日本，外加一个“台独”势力。

有意思的是，就是“美日”，也没有能够做到“将政治企图和经济利益分掰得一清二楚”，更何况印度、韩国这些将与中国间发展经济合作、视为自己发展必然手段的国家了。

*** 为了拉住韩国，美国的朝核政策终于有了“些许松动”

东方评论员，对维持朝鲜半岛和平的渴望、对“韩朝经济整合”的向往、以及中韩经贸已经突破1000亿美元大关的事实，已经拉得韩国往北京方向飞跑。

也正是在这种背景下，为了拉住韩国，美国的朝核政策终于有了“些许松动”，这表现在美朝代表不久前在纽约进行了两次会晤。在东方评论员看来，客观地讲，这不能不说是布什的“一大进步”，也就是说，不论布什是真心还是假意，美朝“直接对话”都让人们看到了“一线曙光”。


*** 华盛顿非常清楚，要想真正拉住韩国就得想办法，将卢武铉的梦给整毁了

只是首席评论员就指出，华盛顿决策者心中非常清楚，要想真正拉住韩国，就得想办法在不得罪韩国民意的的情况下、将卢武铉“整合朝鲜半岛经济”的梦、给整毁了。


*** 布什让赖斯和切尼轮流扮演着这个“破坏者的角色”

因此，每当朝核问题的气氛有所缓和的时候，美国的一些政治人物往往就会跳出来，说些不好听的话，做些难看的事。在东方评论员看来，布什可以说是在让赖斯和切尼轮流扮演着这个“破坏者的角色”。总之一句话，这俩人说的与做的，只有一个目的，那就是：只要能破坏会谈气氛、将美朝关系“复位”到先前状态、化解掉“韩国的努力成果”、破坏中国非常在意的“东北亚经济一体化”进程就行。

有意思的是，今天我们又发现了一个类似的角色，这就是上面的那位声称不怕朝鲜核武器的驻韩美军司令、拉波特将军。什么“不管朝鲜拥有一枚还是多枚原子弹，都不会改变朝鲜半岛的军事平衡。”，这是什么意思呢？不就是在那里弹唱大家都爱听的、“经济主题”之外的旋律吗？这分明是在与卢武铉“唱反调”。

显然，在东方评论员看来，不论拉波特将军“唱得多么好听”，也解决不了朝核问题，因此，也就改变不了所谓的朝鲜半岛的军事平衡问题，也就不能切实地保障朝鲜半岛的和平与稳定、更无从有助于发展韩国的经济。

*** 北京和华盛顿正在上演着一出抢夺韩国的大戏

因此，卢武铉当然还是得从现实出发，走另外一条解决朝核问题的路子，这就是，如果美国始终坚持不妥协的立场，那么韩国就也得依靠“中俄”这两个军事大国、建立一套保障朝鲜半岛和平的多边安全体制，并在这种基础上全力整合韩朝经济、直到慢慢实现民族统一，从而从根本上消除朝鲜核武器对韩国的威胁。

在东方评论员看来，在朝鲜半岛的这场角力中，北京和华盛顿正在上演着一出抢夺韩国的大戏，其结果，将直接影响华盛顿在一个月后于台海问题上的态度、也将直接影响美日同盟亲密程度、还将影响中俄在中亚、东北亚问题上的合作层次。

下面，是有关胡锦涛主席访问俄罗斯的一则消息。在一起了解相关内容之后，时事评论员将把关注的目光投向中亚地带、并继续今天的亚洲部分。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
