# -*- org -*-

# Time-stamp: <2011-08-04 13:07:24 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

*  2005年8月25日  星期四




** “美朝”图破朝核僵局六方会谈或于9月2日复会




【综合25日消息】朝核问题第四轮六方会谈经过13天的讨论与磋商于8月7日开始休会，并拟于8月29日开始的那一周复会。正访问日本的中国外交部副部长武大伟25日指，中方正考虑在9月2日重开六方会谈商讨朝核问题。

分析人士指出，美朝最近频繁接触，如今中国官员透露可能的复会日期，表明美朝之间的矛盾从一定程度上得到化解。

六方会谈可能9月2日复会

据日本共同社最新报道，朝核问题第四轮六方会谈中国代表团团长、中国外交部副部长武大伟25日上午在日本社民党总部同该党党首福岛瑞穗举行了会谈。会谈中武大伟透露称，有关在9月2日重开目前处于休会期的六方会谈一事，目前正在同与会各国进行最后阶段的调整。武大伟已于前一天表示，六方会谈将“按照计划下周如期举行”。

共同社援引武大伟的话说，9月2日是六方会谈重启的一个可能的日子。日本社会民主党一发言人士25日也证实，六方会谈可能在9月2日复会，不过这位发言人说，武大伟并未说明美国或朝鲜是否已同意这个日期。　

美朝频繁接触

第四轮六方会谈第一阶段会议结束后，朝鲜能否拥有和平利用核能权利成为美朝双方争议的焦点问题。美国要求朝鲜放弃包括和平利用核在内的所有核项目，而朝鲜认为和平利用核能是国际法规定应享有的权利。这一分歧是导致第四轮会谈没有取得进展的核心问题。

为了消除这个障碍，美朝之间进行了频繁的接触，美国国务院当地时间24日称，一个美国代表团23日在纽约与朝鲜官员进行了会晤，为下周重启朝核问题第四轮六方会谈作准备。而在此之前，朝美已通过“纽约渠道”进行了3次接触。

另一方面，朝核问题第四轮六方会谈美国首席代表、助理国务卿希尔23日表示，在第四轮六方会谈第二阶段的会议上，美国在是否允许朝鲜保留和平利用核能的权利问题上可能采取灵活态度。他还指出，和平利用核能的问题并不是六方会谈的决定性障碍，相信能找到解决方案。分析指，美国最初主张朝鲜完全先行弃核，希尔的表态说明美国的态度发生了变化。舆论认为，这个转变很可能成为六方会谈的突破口。

朝鲜调整会谈方向

此外，韩国国家安全委员会事务次长李钟奭8月23日在莫斯科表示，朝鲜政府已调整会谈方向，将“弃核”作为会谈的前提，而不是“核冻结”，而且，今后有望与美国签署和平协定等多种形式的体制安全保障，因此，将于下周复会的六方会谈前景乐观。

李钟奭强调，朝鲜政府也清楚作为有核国就不会有未来。他们希望通过六方会谈积极解决朝核问题，现在只剩下条件问题。他还表示，朝鲜要求包括现有核设施在内，以完全放弃今后浓缩及再处理设施等作为条件，允许原子能发电。如果没有浓缩及再处理设施，则无法开发核武器。

复会后可能持续13天

另据报道，美国国务院高官当地时间24日在回答下周复会的第四轮六方会谈将持续多长时间时说：“可以预测在13天内达成协议，但如果必要，也有可能需要13天以上。”这名官员指出，会谈的最终目标是取得成果，“我们正是把精力集中在这方面”；只要会谈处于有望取得成果的阶段，就会继续努力。

外交分析人士指出，尽管美国与朝鲜在平壤能否拥有和平核能权的分歧造成第四轮六方会谈休会三周，但六方下一阶段会谈前景将是“审慎乐观”的。在休会期间，中国继续的“多边穿梭”与“斡旋”也进一步地得到了各方认可和倚重，让六方在很多问题上的共识得以加深，为复会后六方达成共同文件奠定了“很好的基础”。



** 图们江开发计划中俄朝韩蒙官员会议将召开


【北京25日消息】据媒体报道，联合国开发计划署(UNDP)驻北京代表处25日宣布将就朝鲜与中国、俄罗斯边境上的图们江流域开发计划，于9月2日在中国长春召开五国官员会议与投资说明会。朝鲜方面将由财政相文一峰出席，中国、俄罗斯、蒙古、韩国也将派出相应官员参加。

该计划由UNDP主持，早在1991年就已制定，但是长期以来没有进展。UNDP将在这次会议上就UNDP是否继续对该计划进行支援咨询各国的意见，也可能对计划本身重做调整。



【时事点评】就如我们之前多次强调的那样，朝核问题第四轮六方会谈于8月7日开始休会，“中、俄、美、欧、印、日”要想在拟定的“三周”休会期中谈妥“许多大事”、似乎总让我们觉得时间不够、事实上也正如此，尽管“复会日期”临近、但是、上述“强权”之间的“合纵连横”仍然是“犹战日酣”、这就意味着许多决定“六方会谈”命运的“大事”仍然没有最后“谈好”。

*** 第四轮“六方会谈”能否如期正式复会、始终是个问号

因此，在东方评论员看来，第四轮“六方会谈”能否如期正式复会、始终是个问号。东方评论员认为，通过今天这则新闻，我们应该已经确定，在中俄联合军演结束后、由于美韩联合军演仍然没有结束，显然，北京方面已经建议将休会期挪到美韩联合军演结束之后，这就是9月2日。在此，作为一种可能，为了制造良好气氛、美韩的“乙支焦点透镜05”是否会在9月2日之前“提前结束”、我们认为、这应该是个“观察点”。

然而，更让东方评论员感兴趣的不是“美韩”（严格地讲、应该是美国一家、因为直到目前为止、韩国都不愿意透露参演人员情况、哪有这样的联合军演？）举行的这场根本就是在与“和平使命2005”“别苗头”的“联合军演”、而是上面新闻中提到的“图们江流域开发计划”


*** 如此众多的事件“都指向”“9月2日”

在东方评论员看来，朝鲜与中国、俄罗斯边境图们江流域的“开发计划”、可以说不是个新东西，许多年前就已经在计划了，时事评论员之前也是多次提及。不过，直到前不久、在“中俄韩”联合开发图们流域的问题上、都是“只听楼梯响、就是不见人下来”。

我们注意到，这次“投资说明会”正式开会的日子是“9月2日”。相信大家对“这个日子”应该有深刻的印象，别的不说、就以前面那条引用的新闻而言，其标题就是：美朝”图破朝核僵局六方会谈或于9月2日复会。显然，标题里也有个“9月2日”，还有，我们一直在关注的另一场在东北亚举行的联合军事演习--美韩“乙支焦点透镜”联合演习的“军事部分”、也就是“焦点透镜”部分，按美国方面公布的计划、也将在“9月2日”结束。

不难看出，“9月2日”已经因如此众多的事件“都指向”那一天、而注定成了一个不寻常的日子。


*** 比起“老名单”、一个最大的变化是“少了日本”、而“多了个”蒙古

然而，在首席评论员看来，值得注意的是，今天这份“最新的”、对图们江流域的“开发计划”“感兴趣”的名单中、比如中、俄、韩、朝都是“老面孔”，但比起几年前的“老名单”来、一个最大的变化是“少了日本”、而“多了个”蒙古。


*** 一个非常值得注意的动向

我们认为，由于蒙古本身就是“上海合作组织”的观察员、因此、这是一个非常值得注意的动向。事实上、在之前的点评中、我们已经谈及这个问题、那就是“上海合作组织”在扩展方向上的问题。

到目前为止，由于中俄在靠近朝鲜半岛的地方、已经成功举行了这场大规模联合军演、并在演习科目的安排上、展示了分别针对台海、朝鲜半岛、中亚局势的内容，从而已经达到了展示“中俄”有决心共同成为”上海合作组织”安全支柱、有决心成为维护区域安全与稳定的“核心力量”之战略目的，从而让中亚、西亚、东北亚国家看到了“中俄”维护相关国家“共同利益”的意志与实力。


*** “上海合作组织”的向西亚、更或者向东北亚方向扩展的问题、其实已经提上了日程

因此，在东方评论员看来，由于中东、中亚、东北亚之间的联动性极强、我们的判断是：“上海合作组织”的向西亚、或者向东北亚方向扩展的问题、其实已经提上了日程。当然，这种“日程”是否立刻实施、还要视“中、美、俄、欧盟、以及印度、日本”相互间的进一步互动而定。

东方评论员认为，一旦“六方会谈”最终失败、只要韩国有决心摆脱华盛顿的阻扰、自行启动朝鲜半岛经济整合、那么，为了维护朝鲜半岛的“稳定和和平”、“中俄”或者选择由“中俄韩朝”、在东北亚建立一个“六方会谈”之外的“东北亚安全机制”、或者将“向东北亚方向的扩展”作为“上海合作组织”的、继向南亚、西亚方向之外的、另一个“选择项”。


*** 所谓“图们江流域开发计划“、“本质”上就是“东北亚经济一体化”的一个重要组成部分

事实上、这个所谓的“图们江流域开发计划“、本质上就是我们经常谈及的“东北亚经济一体化”的一个重要组成部分。

我们知道，“朝核问题”最终将如何解决、事实上对“六方会谈”的“六方”的意义是大不一样。就“中俄韩日”这“四方”而言，朝鲜半岛的局势变化直接影响到各国的经济投资环境。

在过去几年中、我们可以清楚地观察到这么一幕，即：每当朝鲜半岛形势一好，同处朝鲜半岛的韩国、其股市就立刻大涨，而外国对韩国的投资也是立马增加；反之，就是股市动荡，外资急剧减少。

因此，在东方评论员看来，朝核问题“六方会谈”最终能谈出个什么结果来、对韩国的国家安全、与经济利益、今后的发展空间、民族统一前途“都是至关重要的”。

另外，对北京和莫斯科而言，朝核问题的结局对中国提出的对东北老工业基地的“振兴大计”、以及俄罗斯通过远东地区拉动经济的策略、也将会有重大影响。


*** 一种“美好前景”成了一种“美好的梦想”

实观上讲，朝鲜半岛周边的几个邻国--中国、俄罗斯和日本，彼此有各自的优势、中国有市场、也有人力、俄罗斯有资源、日本有技术和资金、如果能通力协作、比如说通过能源、运输和建设的“众多具体项目”为“工具”、来进行一个包括朝鲜半岛在内的、东北亚一体化经济区的“多边努力”，那么，这就可能给这一地区、甚至是整个东亚带来“长久和平”，继而促进东亚、整个亚洲经济一体化、从而形成一个与“法德英”为核心的欧盟、美国为核心的美洲、中国日本为核心的亚洲“三足鼎立”的国际竞争格局，这必将从根本上彻底避免朝鲜半岛、台湾海峡、甚至中日之间爆发灾难性的战争。

然而，就目前而言，在美国人成功地利用汇率武器“扔给”日本经济一个“失去的10年”后、并利用日本社会的失落、又转手利用日本保守政治集团对中国综合国力快速提升的恐惧感、成功地“催发”日本社会走向右倾保守之后，“这种美好前景”已经不过是种“美好的梦想”了。


*** “朝核问题”的“本质”就是华盛顿全力破坏东北亚、东亚经济一体化的“关键一步”

在东方评论员看来，就“朝核问题”而言，其“本质”就是华盛顿全力阻止北京在东北亚进行战略展开的关键一步、也是阻碍、破坏东北亚、东亚经济一体化的关键一步。

事实上，布什新保守主义政府一上台、为了顺利展开其“支配地球”的全球战略，为了直扑中东、为了防止中、日、俄、韩的战略接近、特别是为了防止北京利用华盛顿“无力东顾”的这一战略空档启动东北亚、东亚经济一体化进程，就立刻撕毁了克林顿政府与朝鲜签下的“朝核问题框架协议”，一手制造了所谓的“朝核问题”。

东方评论员认为，白宫决策者的企图心、就是为了“制造”一个华盛顿随时可以找理由武力解决的“朝核问题”，从而在中国可以借以吸引俄罗斯、日本、韩国的“东北亚经济一体化”进程中、埋下一颗可以“随时引爆”、并将东北亚、东亚经济一体化“炸出轨”的“不定时炸弹”。

种种迹象显示，“顺利启动了”、却一直在“如何结束”伊拉克战争的问题上“不得要领”的华盛顿、正是为了“精心维护”“朝核问题”这颗可以“随时引爆”的“不定时炸弹”、让其始终能“处于准备状态”，这才在“前三轮”朝核问题六方会谈中、强硬要求“朝鲜必须先行弃核、之后再谈其它”、这种极其苛刻、且“明知”朝鲜、北京根本就不可能接受的前提条件。


*** 美国西太平洋政策的核心

东方评论员认为，按美国新保守主义者拟定的全球战略、其西太平洋政策的核心就是“大国制衡”，即：要利用“美日军事同盟”来遏制中国、利用日本军国思潮、大国野心来制造中日对立、利用“中日交恶”、中俄间的“戒心”来隔断“中俄日”的战略协作、利用“美韩军事同盟”来阻止朝鲜半岛走向和解与稳定、继而通过“美日韩军事同盟”将俄罗斯继续“堵”在国境线之内、利用“美日台”准军事同盟将中国限制在第一岛链之内、从而让“中俄”继续与西太平洋“绝缘”。

总之，华盛顿所设想的、所实践的这一切，只有一个目的，那就是让美国始终处于各种事务的主导地位、为达到这一战略目的，华盛顿一直在不择手段、就是对自己所谓的盟友也“一视同仁”、对日本如此、对欧盟也是如此。

下面，我们就来阅读一份刚刚收到的消息，之后，我们将继续回到这一话题。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com



** 美国将在罗马尼亚黑海海滨开设军事基地



【新华网布加勒斯特电】罗马尼亚国防部长阿塔纳休２５日在位于黑海之滨的康斯坦察市宣布，美国将在罗马尼亚黑海海滨地区开设军事基地。

这是罗官方第一次正式宣布美国将在罗开设军事基地。阿塔纳休说，罗马尼亚和美国目前正在就在罗境内开设美军事基地的选址和运行条件进行商谈。谈判在罗美两国外交部之间进行。两国不就此签署合同，而是将通过发表一项政治备忘录表明双方在这一问题上达成协议。

罗马尼亚黑海海滨地区拥有罗最大的海港——康斯坦察港，罗马尼亚的科格尔尼恰努军事基地也设在那里。２００３年２月美国开始向伊拉克动武后，罗当局曾把这一军事基地提供给美国作为向伊拉克运输军事人员和物资的中转站。





【时事点评】我们之所以将这一“欧洲方向的新闻”插入到这一部分来，是因为华盛顿的“这个动作”其实也与中俄军演的“大背景”紧密相关。我们注意到，对此，法国的一位战略观察人士就一针见血地指出：美国挑选中俄联合军演结束的时候来宣布这一消息、明显有冲着与中国联手举行军演的俄罗斯“喝倒彩”的意味。


*** 华盛顿给俄罗斯脸色看的同时，自然不会忘记对北京也“晓以颜色”

事实上，“中俄联合军演”是中国和俄罗斯“联手”展示有意自西边的西亚、中部的中亚、东部的东北亚“共同挤压”美国势力的“宣言书”，因此，在华盛顿给俄罗斯脸色看的同时，自然不会忘记对北京也“晓以颜色”。

在之前的点评中、其实我们已经对此进行过分析，的确，就在这几天，华盛顿在马英九正式接任国民党主席之后，可以说是立刻就在军售问题上“做起了文章”。在东方评论员看来，如果不出意外、台湾的军售案“最迟”在台湾年底县市长选举后、就会在华盛顿、陈水扁、马英九的“配合下”正式通过。

因此，美国防部长拉姆斯菲尔德在这个时候“重申协防台湾的承诺”，并称台湾为“主权国家”，其行为是公开地在开美国前国务聊鲍威尔的“倒车”，去年10月份，鲍威尔可是一字一句地表示“台湾不是个主权国家”的，在我们看来，拉姆斯菲尔德这样做的意图非常明显，首先是在敦促台湾的陈水扁、马英九尽快通过预算案、而另一方面、也有冲着与俄罗斯联手举行军演的中国“喝倒彩”的意味。


*** “大国”“玩大国战略”的技巧与潜规则

当然，东方评论员认为，如果谁要认为这些个“喝倒彩”的动作不过是“泄愤”，那可就太不了解“大国”“玩大国战略”的技巧与潜规则了。在我们看来，不论是中俄联合军演本身、还是“中俄”一个劲地“此地无银三佰两”般地强调不针对第三者、或者是华盛顿安排在这个时候、分别在东欧方向、台海方向这两个最能刺痛“中俄”神经的方向冲着的“中俄”“喝倒彩”、其用意都是在“半斤八两”、都在向方方面面展示自己的战略意图、以及实现这种战略意图的坚强决心、并以此来坚定、或者动摇“这些战略意图”“涉及到了的”“外围国家”之政策取向。


*** 华盛顿这个时候“来这一手”、就是在威逼乌克兰不要对俄罗斯的压力屈服

众所周知，眼下，乌克兰正准备发起一个与俄罗斯主导的独联体“说拜拜”的运动、而俄罗斯正在“用能源供应这张牌”威胁乌克兰、警告这个俄罗斯“通往欧洲的门户”不要再做对不起独联体、对不起俄罗斯的事情、即不要帮着美国瓦解独联体。

在东方评论员看来，华盛顿选择在今天、即中俄联合军演结束的时候、突然宣布要在紧靠乌克兰的罗马尼亚建立军事基地、此举明显有显摆的意味、显摆美国手中握有波兰、罗马尼亚这两个军事盟友、这可是两个掐着乌克兰通往西欧战略要道的东欧国家。

不难看出，华盛顿在这个时候“来这一手”、就是在威逼乌克兰不要对俄罗斯的压力屈服、同时，也是在进一步落实早已拟定的、将西欧与俄罗斯进行战略分隔的战略意图。
东方评论员认为，美国人此举发出的信息是清楚的，即：第一，华盛顿是不会改变其全球战略的；第二，警告俄罗斯和以德法为核心的西欧国家、欧洲与俄罗斯的陆上交通线在美国人手中；第三，也是警告中国、让中国明白“中欧之间”的战略联系、即那条“串连中、俄、欧”的欧亚大陆桥“是不安全的”，不仅“走海上”不安全、就是“走陆地”也没有保障。


*** “提早”亮出的一张“战略底牌”

在我们看来，华盛顿决策层如此这般显然是在“策应”其对华、对俄政策、弥补其在东北亚、中亚的“诸多不顺”、在与“中俄”于中亚、东北亚、西亚的角力中“提早”亮出一张“战略底牌”。

东方评论员认为，只要有一丝希望，华盛顿就会继续其全球战略，而在这套战略中、东北亚方向、朝核问题被设计成牵制中、韩、俄、日的“不定时炸弹”。在我们看来，东北亚虽然不是华盛顿的“重心”、但经过北京近一年多的运筹、特别是用《反分裂国家法》将华盛顿原本用来威胁北京的、屡试不爽的“和平台独”给一把掐死之后、而华盛顿原本用武力解决“朝核问题”这一选择项、来威胁周围国家的“朝鲜政策”、似乎因中俄通过这次“和平使命2005”所展示的决心、也正式地失去了“表演的舞台”。


*** 华盛顿的尴尬在于两方面

如此一来，在东亚接连失去两张牌的美国、手上需要处理的东亚事务已经变成了尽快将“美日台准军事同盟”落到实处、从而“快速提升台独武力拒统的能力”、和打断北京主导的朝核问题进程，从而“尽快稳定韩美关系”。

在东方评论员看来，华盛顿的尴尬在于两方面：就前者而言，这需要时间、也需要得到日本的全力配合，这样、在给北京施加战略压力的同时，华盛顿也不得不承受来自中国的、来自其他方向的战略压力；就目前而言，北京在朝核问题、伊朗核问题、中亚问题上给华盛顿造成的“巨大麻烦”是有目共睹。另外，华盛顿还得承受日本胃口日增的“战略要价”，在东方评论员看来，华盛顿在最后一刻跳出来给日本以颜色、与北京联手坚决反对“四国提案”、其本质就在于日本不听招呼、华盛顿是“被迫提前现身”。就这个问题而言，还真不知道是中国利用了美国、还是美国利用了中国。

而就打断北京主导的朝核问题进程、“尽快稳定韩美关系”这一层而言，华盛顿似乎突然发现原来准备“拖而不决”的“朝核问题”不仅到了“迫不及待”的地步、还成了一个美国不得不认真、主动处理的“急事”、要命的是，这与之前美国新保守主义者拟定的全球战略是“极不匹配”的。

然而，“中俄”就是要从东北亚“联手打乱”美国的战略步调、在中亚“全力挡住”美国的渗透、并压缩华盛顿全球战略的战略纵深、同时、再在中东利用仍然、也不可能彻底解决的巴以问题、和伊朗核问题、最大可能地团结阿拉伯国家、和欧盟一起最终破坏美国的“中东进程”。


*** 对华盛顿而言，其原先的“朝核政策”处理原则、就是尽一切可能将“朝核问题”继续拖下去

我们知道，几年以来，华盛顿一直在做的事情、就是要让朝鲜半岛“始终处于不稳定”状态、就得象美国人有意识地让台海处于不稳定状态、想借此压北京在中东做战略让步时所扮演的角色那样，即：“一手制造紧张、一手还能控制住局面”。

因此、对华盛顿而言，其原先的“朝核政策”处理原则、就是尽一切可能将“朝核问题”继续拖下去、直到美国人“彻底理顺”伊拉克、搞掂伊朗、再将俄罗斯完全挤出中亚、一方面堵死对中国极其重要的中亚资源之源头、二来彻底控制住印度、并利用“东欧亲美势力”彻底割断欧洲与俄罗斯的战略联系、从而掐断中国经中亚、俄罗斯、联贯欧洲的“欧亚大陆桥”为止，到那时候，华盛顿也许才会认真地来解决所谓的“朝核问题”、只是到了这个时候、对美国决策者眼中的大棋局而言、恐怕就到了其对华、对俄、对日政策的“收官”阶段了。


*** “东北亚经济一体化”是一步走得好、就可全盘打乱美国全球战略的“关键一着”

首席评论员指出，由于“东北亚经济一体化”是一步“走得好、就可令中、俄、日、韩关系全面走活”、全盘打乱美国全球战略的“关键一着”、因此，东北亚地区经济圈能否整合，对中国能否启动包括韩国、日本、东盟的“东亚经济一体化”、并从俄罗斯、澳大利亚获取稳定的能源、矿产至关重要。

不难看出，这一次“和平使命2005”联合军事演习的一个重大战略目的、就是体现中俄双方“决心”用自己的政治、经济、特别是军事实力、来共同维护朝鲜半岛稳定、体现中俄在东北亚地区的、应该共同肩负的“和平使命”。


*** 一个颇具“前瞻性与建设性”的“建议”

事实上，我们认为，与华盛顿不同的是，受朝鲜半岛稳定与否影响巨大的周围国家、特别是“中俄韩”三国要想“永久地”解决朝核危机、“唯一的政策”就是要将朝鲜带入国际社会，其“根本办法”在于加强整个东北亚的经济、政治、甚至是军事整合。

在很早以前，由于清楚地看到“冷战格局”在亚洲、特别是东亚这一带仍然存在，因此，为了找到一条稳定东亚的路子、联合国工业发展组织的一位官员就曾经就提出过这样一种观点，即：必须通过用与东北亚五国及美国有关的能源、运输及其他项目、来清理类似朝鲜半岛能源开发组织的各种项目，从而把这些不同种类的项目融合在一起。

对此，东方评论员的观点是，“联合国这位官员”的意思当时就非常清楚，那就是不妨在东北亚建立一个“新的国际组织”、来协调东北亚有关经济、政治、甚至是安全方向的问题。

显然，在我们看来，这个“建议”颇具“前瞻性与建设性”：朝核问题“六方会谈”成员国中、起码“中俄韩朝”这几个国家是“正有此意”！


*** “中俄韩”已经在着手第四轮“六方会谈”结束之后的“事务”了

在这里，东方评论员想强调一点，那就是宣布这次“投资说明会”的是联合国开发计划署(UNDP)驻北京代表处，在我们看来，通过这一点，不难看出“中俄韩”已经在着手第四轮“六方会谈”结束之后的“事务”了、不论“这种结束”是一个成功的“六方会谈”、还是一个失败的“六方会谈”。

下面，是一则来自日本的消息。连续几天，我们对日本国内政治给予了“连续的关心”、在我们看来，小泉纯一郎日益高涨的支持率、以及中俄联合军演给世界格局带来的冲击、似乎已经让“东海上的波涛”暂时小了许多，然而，中日关系的前景在日本已经为保守势力所控制的情况下、是不会有根本性好转的。在一起了解下面这段新闻之后，东方评论员将就华盛顿在朝核问题上“让步、与不让步”、“六方会谈”“成功与失败”两种结局、来讨论其对中日关系的巨大影响。

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
