# -*- org -*-

# Time-stamp: <2011-08-04 13:20:33 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

#+STARTUP: indent


* 2005年5月13日 星期五

** 宋楚瑜抵台北发表讲话“回家的感觉真好”

【台湾消息】宋楚瑜一行结束大陆访问，于13日下午4时左右返回台湾。马英九去机场接机。宋楚瑜在机场发表了简短的讲话，表示回家的感觉真好。

以下为讲话全文：

各位新闻界的朋友，各位乡亲，回家的感觉真好，我们亲民党大陆访问团回家了，我们带着两岸同胞们大家共同追求和平的远景相互的沟通，做了一些非常仔细的交流。

楚瑜非常感谢中共中央同胡锦涛总书记的邀请，我们亲民党的大陆访问团特别到大陆做了9天8夜的访问，在这个期间我们看到大陆上的一些变化，也看到许许多多的大陆的乡亲和我们一样都希望我们能够追求一个和平的远景，我们在昨天和中共中央，特别是胡锦涛总书记坦诚而且深入的交换了意见，达成六点重要的结论和共识。

今天大陆当局也正式的开了记者会，他们承诺做的许多的措施在我们离开北京之前就宣布特别对于2006年能够全面来直航，同时对于到大陆去访问的简化和相关的措施，以及对于我们在大陆留学生所做的许许多多的安排，包括对他们的学费、就业、奖学金等等，都立刻做了回应。楚瑜在香港机场看了之后，利用这个机会特别向中共中央台办的陈主任和胡总书记表达我们感佩。

楚瑜要再一次的来说，我们看到两岸大家都愿意追求和平，心胸有多大，世界就有多大，我们亲民党这一次把它定位作工作之旅，对每一位团员来讲，都是非常辛苦的，但是我们在沟通和过程当中，深切的了解到只有我们持续的努力，我们相信我们带回来的这些非常具体的这些成果，特别是对于我们农民的照顾，那就是在盛产期大陆承诺愿意来购买我们这些农产品，帮我们农民解决问题，这些许许多多的措施今天下午楚瑜会进一步的就全面这些问题透过记者会向所有的同胞们再一次的详细加以说明。

我们了解到两岸和平的远景真正掌握在我们自己的手中，明天就要投票，我跟陈水扁所谈的他也承诺过不用任何的这些“公投”或者是“宪政”的方法来去搞“台独”，这些也在我们北京的谈话当中只要我们大家能够好好的不要去做这些法理“台独”的事情，千万不要让“公投入了宪”，又把和平的远景又搞坏了，请大家明天投票的时候，不要忘记投给5号，那就是让台湾能够五福临门，不要再把和平的远景丧失掉了。明天的投票非常重要，我们为什么要赶回来，就是要把这样丰盛的成果，不要把我们马上有这么好的远景的事情在明天我们自己又把它丢掉了，所以谢谢大家，稍候再向大家汇报，回家的感觉真好，非常谢谢！



【时事点评】我们注意到，就在今天早上，宋楚瑜离开北京的欢送仪式上，台办主任陈云林说了一番意味深长的话，他讲话的大意有三个要点：第一，宋楚瑜此行取得了重大成果；第二，两岸关系仍然会是“几多磨难”；第三，强调不论宋楚瑜回到台湾会遇到什么困难，包括大陆的十三亿希望和平的两岸同胞，都会支持两岸和平的努力。


*** 大陆再次给了宋楚瑜“一份大礼”

在东方评论员看来，在宋楚瑜于最后时刻“下决心”用“两岸一中”去突破连战的“九二共识”之后，大陆除了送给他“不独不武”这份为宋楚瑜所宣称的、“台湾意识”“最为关注的大礼”之后，显然，又通过陈云林这一席“富有感情”讲话，再次给了宋楚瑜“一份大礼”，这就是“公开的肯定、和公开的支持”。


*** 宋楚瑜取得了在“两岸之间”扮演“关键角色”的资格

首席评论员指出，有了陈云林所说的““重大成果”和“十三亿同胞的支持”，事实上，宋楚瑜这次也就“正式取得了”在“两岸之间”扮演“关键角色”的资格。

事实上，东方评论员注意到，在稍早的一次凤凰卫视的专访中，与胡锦涛主席会谈之后的宋楚瑜，在经历了“记者会”上短暂、却又非常的“不适”之后，“已显轻松”的宋楚瑜、“毫不谦虚地”用一句“亲民党在两岸之间起着关键作用”的话、从而将“关键角色”的这顶帽子“早早地戴到了自己头上”。

显然，今天早上“送机”的时候，大陆通过台办主任陈云林这番“感性”的欢送语、也间接地肯定了宋楚瑜的“自我定位”。

*** 有了大陆的“肯定”，宋楚瑜自然是“回家的感觉真好”！

在我们看来，有了大陆方面的“肯定”，宋楚瑜回台湾的心情、自然就是“回家的感觉真好”！

在昨天的点评中，我们已经提过，到了宋楚瑜拿出“两岸一中”这一步之后，大陆“下好连宋这两颗棋子”的计划可以说是大获成功。东方评论员认为，这种成功首先就表现在立刻让国民党和亲民党之间“先别起了苗头”（详细分析见5月12日《东方时事解读》）、然后，再通过国民党和亲民党的相互竞争、并以“不独不武”做广告语、去推动两岸关系朝向“两岸实质性三通”方向发展，从而一方面继续掏空民进党、台联党的政治基础，一方面“促进”陈水扁尽快承认“九二共识”、或者“一中原则”。

在东方评论员看来，只要能掏空民进党、台联党的政治基础，那么，不论是连战和国民党还是宋楚瑜和亲民党、按宋楚瑜的口气说、是自然会“忒”卖力

因此，已经被大陆的这一套组合拳打得“眼冒金星”的民进党、按照常理自然会出来“鼓噪一番”。下面，我们就一起来看看民进党对“两岸一中”的正式反应。


《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 台当局回应胡宋会拒绝以九二共识为对话前提

【台湾消息】台湾“陆委会”今天就“胡宋会”作出回应，表示不会接受任何以“一中”为实质内涵，包括“九二共识”等在内的说法，作为两岸恢复对话的前提。

　　据“中央社”报道，“陆委会”副主任委员游盈隆上午在记者会中说，宋胡会会谈公报提及有关“九二共识”的叙述，“事实上与当年记录有很多出入”。他声称，“九二共识”就是“没有共识的共识”，“九二香港会谈”也没有任何结论。

　　游盈隆还说，近期以来，由大陆领导人及对台部门相关负责人的言论谈话，以及岛内在野党领袖访问大陆时大陆所表达的态度看来，“充分显示中国对台政策僵化依旧”，“没有展现出改善两岸关系的具体诚意”。



【时事点评】在东方评论员看来，陈水扁当局强硬表示不会接受任何以“一中”为实质内涵，包括“九二共识”等在内的说法，丝毫不令人意外，对于这么一个靠操纵“台湾意识”、视“台独纲领”为“票房补药”的台独党而言，不出来鼓噪、反对那才是奇怪呢！

*** 大陆已经有了足以让自己在台湾问题上、去“举重若轻”的综合实力

首席评论员就指出，如果台“陆委会”副主任委员游盈隆所说的、“充分显示中国对台政策僵化依旧”的这句话，是特指大陆坚持“一中原则”的话，那么，他的说法倒也有几分道理。

在我们看来，大陆当然不会在“一中原则”去做什么“灵活处理”，原因很简单，第一，“反分裂国家法”已经以法律的形式确定了“世界上只有一个中国，大陆和台湾同属一个中国”的“一中原则”，并且也以“坚持一个中国原则，是实现祖国和平统一的基础”这一条款、明确了“一中原则”是将来两岸关系“所有发展方式”的基础，因此，已经受到“反分裂法约束”的中央政府和中央领导人是“不可能去犯法”的；

第二，尽管国际局势仍然极其严峻，然而，由于中国综合国力的相对增强、和美国霸权的相对削弱，东亚、中东、中亚、南美等事关国际全局各个方面、中、欧、俄、美、日的核心战略利益，也已经被“紧紧地卷在了一起”，特别是华盛顿的全球战略虽然更多地表现出赖斯“相对务实”的影子，但是，仍然没有出脱其牟求全球支配权的主线，也就仍然无法摆脱全面被动。

在这种情况下，大陆已经有了足以让自己在台湾问题上、去“举重若轻”的综合实力，因此，中央政府和领导人在“一中原则”上、“也根本没有必要去灵活一把”。


*** “够强硬”的陈水扁、让我们想起了那个“更加强硬的”日本外相町村信孝

因此，在东方评论员看来，此时“够强硬”的陈水扁、让我们想起了不久前那个“更加强硬的”日本外相町村信孝。

对于那位“作风强悍”的日本外相，大家应该还记得我们曾经送给他的一句话，那就是“他在北京强硬的不是时候”。在东方评论员看来，4月17日、“本来就带着任务”到北京访问的町村信孝、却又偏要给日本国内看看他是如何表现出一副“就不妥协”强硬态度的，只是最后让日本国内更清楚地看到了另一幕，即，他的够强硬却令他的老板---小泉纯一郎几日后的“道歉”更加显得“脸上挂不住”。


*** 政治角力是要讲究实力和筹码的

东方评论员认为，政治角力是要讲究实力和筹码的，不论是国与国之间，还是台海两岸之间者是如此。在我们看来，当时的日本外相、似乎就不明白这一点，那就是，中美虽然有不可调和的战略矛盾，但是，在严密控制日本，不让其强大的经济、科技力量转化成一支无法控制的军事力量、去冲击中美共同维持的东亚现有格局的层面上，还是“有足够的共同利益”。

然而，在北京已经摆出一种不再单方面顾忌中日关系“何去何从”的强硬姿态之后，在日本已经面临自己“是应该选择一个继续维持的中日关系、以确保自己继续在中美间保持战略灵活性、从而有机会继续平稳地发展其经济，还是选择一个彻底决裂的中日关系，从而让自己的经济、在继政治、军事之后也彻底落入美国完全控制之中”的关键时刻，那位日本外相却偏偏不识相地“要强硬到底”，结果自然是“搬起了石头砸烂了小泉纯一郎的脚趾头”、

*** 陈水扁和民进党的强硬更是“强弩之未”

我们认为，今天的陈水扁与那位日本外相、现在的台湾当局和当时的日本好有一比，两者都有一个共同点，那就是偏要“强硬着给人看”。然而，日本首相和外相的强硬、是典型的“外强中干”，这让中国的决策层看出来了，相比之下，在“事已至此”的情况下、陈水扁和民进党的“强硬”更是“强弩之未”，对这一点，不要说中央决策层了，就是台湾的一位学者也看了出来。

下面就是一份“揭示”陈水扁用心的分析文章，在东方评论员看来，尽管我们认为其中的部分观点值得商榷，然而，总体上讲，这篇分析算得上是一份剖析陈水扁将“何去何从”的精品。


《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com

** 三布局用心走　王昆义：胡扁会好戏就要上场

【台湾媒体分析文章】据台湾媒体报道，台湾政治局势，近日显得很特别，从国民党主席连战访问大陆，一直到亲民党主席宋楚瑜在大陆演说，强化台湾意识不等同于台独，甚至有机会和胡锦涛共同修正对九二共识的认定。

政坛中延续着陈爆料的口水，什么父子反目，什么优势置入行销，还有政治人物扬言，阿扁用新火灭旧火，结果搞得是遍地烽火。这些台面上政治人物的看法，似乎形成一股气氛：扁已经提前跛脚。

但是，这些口水加上怒火的评论，难道就是看倌要的正解吗？两千三百万台湾人两度用选票选出来的领导人，真的那么不堪一击，随便几个党内立委的抨击，就被激的仆仆跳，呛声爆料泄愤解闷？还是为了区区的514国代选举结果，就让自己因为承不住气，而提前跛脚？

淡江大学战略研究所教授王昆义指出，从连战出访到12日的胡宋会晤，包括期间陈专访爆料，和李登辉划清界线，并且强化九二共识就是一中各表的定义，都是陈水扁过人的精心布局，为的就是要营造环境和气氛，让扁胡会的展开成为可能。

王昆义解读陈近日针对两岸局势所布下的新局面，认为陈在包括台独议题、九二共识、一个中国等三项两岸未来能否开创新局的关键上，做出了令人会心一笑的布局。

王昆义教授强调，目前已经是陈的第二任期，而两岸问题绝对是陈未来历史定位的关键，因此，积极在两岸和平和解上着力，对陈而言，绝对是值得的政治投资，也是应该要思考的重点方向。

衡诸两岸当前的争议，王昆义说，陈归纳出上述的三个关键要项，也透过连战展开访大陆之后，一步棋一步棋地下，也一项一项地成功回收，获致成果。

王昆义说，从二月扁宋会开始，陈在两岸议题的新布局就已经展开，现在船几乎可说是开到河的中间，陈绝对没有回头路，如果因为党内的反弹就嘎然而止，不但对岸等着看笑话的人会笑，连背后原来的支持者也会扬弃他，因此，最好的办法，就是像陈之前透过电视专访，用力挣脱外界儿皇帝的看法，甚至倒打一耙宋楚瑜，争取阿扁基本盘的坚守，站稳之后，再对外呛声，宣告不愿意再成为前的傀儡。

王昆义进一步解读，陈公开向李呛声，宣称不愿意让人当儿子看待，真正的目的在于，把台独包袱通通丢给阿辉伯，跟台独划清界线，让他在和对岸交手时，落得一身清静。当然，也可视为陈向对岸主动发出的反独积极讯息。

王昆义也提醒，当台独基本教义派对陈越反弹时，陈和台独两字，也就成功地渐行渐远了。具体的例证，包括民进党王姓立委11日痛批扁「治国无能，治事无方」，以及独派大老11日下午再度召开记者会，公开指责「阿扁没有救了」，都是三大布局中的精采插曲。

三大布局中，和台独割裂已见成果，王昆义指出，宋楚瑜11日的清大演说毫无新意也欠精彩，太多的经济数据和花俏的语言桥段，其实比连战演说的格局小很多，但其中还是可以听出一些重点，包括将台湾意识不等同于台独，做出明确解释，以及预告12日即将和胡锦涛的会晤，提醒胡宋会在搭桥之旅的重中之重。

陈从阳光之旅开始，把九二共识定位在国民党苏起的个人说法，政府未必认同。还有陈10日接受德国媒体访问，强调台湾在九二共识上，只能接受一中各表。而在11日胡宋会前，府方再追上一笔，主动发简讯表示，希望两岸正面看待九二香港会谈所获致成果。

这一切，总不应该都视为巧合吧！

王昆义指出，陈从扁宋会先建立默契，让宋楚瑜这趟到大陆重新定义九二共识，脱掉争议不断的这四个字眼，代以「一中各表」，将九二共识定义到两岸之间可以共同认知的公约数，为九二共识争取重新定义的空间。而这个期待，可望在12日下午成为可能，宋楚瑜到大陆，搭的正是这个两岸善意的桥，也可看作是为扁胡会搭桥。

陈三大布局中，还有一个中国，坚持一中原则这几个字，当然不容易从陈嘴巴说出来，即使说出来也不会获得台湾民众认同，不过，王昆义也提醒，陈多次重申就职四不一没有说法从未变过，其中当然也包括曾经说过的「未来一个中国」。

王昆义说，不要小看连战访大陆对陈这三大布局的重要性。王昆义认为，陈对于连战访大陆表示祝福，即使连战声言联共制台独，陈都只是嘴巴念念，未对连战祭出违法追诉的报复动作，为的就是让连战去全力表述一中，而扁政府不惩处也不以为意的被动，说穿了正是一种肯定的方式。

精心的布局加上政治大动作，陈推动两岸和解的用心，其实已经悄悄地展现：让李独自背负台独十字架、推宋楚瑜去大陆搭桥、随连战高举一中，如果这一切最后都可以修成两岸正果，这些骂人的、被骂的、委屈的、难言的，通通都有功，因为海峡不必再用鲜血挹注，人命毋须再为政治犬马。

如果这一切的解读，最后都获得证实，那么，两岸尤其是台湾两千三百万人期待超过一甲子的「岁月静好」和安稳生活，绝对可以冀望七月后应该就要登场的胡扁会。




【时事点评】在东方评论员看来，这位王昆义所陈述的“陈三大布局”非常有意思，我们也深以为然，但是，我们认为，他似乎忽略了另一大布局，那就是许文龙的发表“退休感言”的“这一出”。

*** 与搞政治的宋楚瑜相比，商人身份许文龙对“两岸关系”似乎更显得“先知先觉”

由于时间过去的还不是太久，相信大家多半还记得：就在“326”台独势力在台湾搞反制“反分裂国家法”的当天，“绿色台商”许文龙却突然宣布一份对“反分裂国际法”充满赞美之词的“退休感言”，在东方评论员看来，最为有意思的是，许文龙在退休感言中、在“认真地”指出了台湾的经济发展离不开大陆，搞“台独”只会把台湾引向战争之后，还第一次公开声称“台湾、大陆同属一个中国”。
　
现在看来，与搞政治的宋楚瑜相比，商人身份许文龙对“两岸关系”似乎更显得“先知先觉”，早在“326”就在台湾率先提出了“台湾、大陆同属一个中国”的政治主张，真可谓台湾“第一人”，在东方评论员看来，宋楚瑜这个搞政治的、在政治敏感度上，竟然还不如一个做生意的、这岂不是一大讽刺？

*** 许文龙的“背叛”不简单

因此，就如我们在4月27日《东方时事解读》台湾部分所说的那样：许文龙的“背叛”不简单，其实是陈水扁政府内部、或者是民进党内部有人“默许”许文龙“叛变”的。

在东方评论员看来，总体而言，陈水扁、民进党对许文龙的“叛变”所持的态度，可以说是“非常的冷静”。我们也认为，许文龙的“叛变”根本就是“华盛顿编写的剧本”的关键“一节”，而这一节”之所以如此关键，就在于它是是在为启动“两岸和谈”造势。

显然，这是有意在让台湾商界打头炮，迫使北京“先经济、后政治”地、加快两岸和谈的步调，而“先经济、后政治”本身就是在为“宋楚瑜拿着与陈水扁敲定的“十项共识”，走“中间路线”，去与北京谈所谓的、“名义上”可以保持几十年和平的“中和协议”。

*** 陈水扁早就在为日后被迫承认“九二共识”做铺垫

东方评论员当时就认为，陈水扁在美国必须“暂停台独进程”、确保台海稳定的要求之下，让许文龙“公开宣传”“台湾、大陆同属一个中国”，并指出台湾的经济发展离不开大陆，搞“台独”只会把台湾引向战争，主要有两层目的，第一，陈水扁如此这般地从台湾民众关注的经济着手、实际上是在为日后被迫承认“九二共识”做铺垫。

第二，陈水扁的民进党，通过这种几乎赞同默认台商许文龙“反叛”行为的方式，如果能拉拢广大台商、迫使北京提前、在经济层面上启动“两岸和谈”进程，那么，这将彻底将“反独立场”一度模糊的国民党边缘化。（相关详细分析请参见4月26日《东方时事解读》）

*** 华盛顿，陈水扁的共同编写“这部剧本”的主要思路


不难看出，在华盛顿，陈水扁的共同编写的这部剧本中，其主要思路在于先用“宪法一中”与大陆周旋一段时间之后，再用“九二共识”（或者相当于承认一中原则的条件）换取一个“两岸和谈的进程”，和一个稳定的朝核问题。

然后，再让两岸谈成一个“和平协定”，一来得到一个稳定的东亚、从而为华盛顿的中东战略赢得时间，二来也可以为“对台军售”创造机会、为整合“美日台”军事同盟提供条件、从而为将来的“非和平台独”赢得准备的时间。


*** 在小泉纯一郎“公开道歉”之前止，可以说一直在按“剧本”在唱

从这套计划中，我们不难看出，如果按华盛顿、陈水扁的剧本一路走下去的话，那就既可以得到华盛顿、陈水扁想要的“台海和平”，又可以让陈水扁、民进党当局摆脱经济方面的困境。

在东方评论员看来，在被“反分裂法”已经堵住“和平台独”去路、今后必然会为绿营的主张“急独”的台联党、和蓝营倾向维持现状的国民党、和只为选票而摇摆的亲民党所三面夹击，在这种情况下、陈水扁和民进党这个即得利益的个人、与政党、是没有什么不满意的。

首席评论员指出，从华盛顿、陈水扁通过“扁宋会”安排下宋楚瑜这颗棋子开始，可以说直到日本在东海问题上极力挑畔中国、要向日本企业发放资源堪测许可证为止，可以说一直在按华盛顿、陈水扁商量好的剧本在唱。


*** 华盛顿巧妙地利用日本对“台海和平进程”的担心

在“中欧俄”与美国在中东对峙的时候、中、欧、俄、美在中亚又各自有自己的小九九、同时，北京和华盛顿在台湾、朝核问题上也处于对峙状态、在这个敏感的时刻，日本对北京和华盛顿而言、自然都身价百倍。这对日本而言，当然是个借机实现自己大国报负的战略机会。

华盛顿也是瞄着这一“敏感点”，一面通过“反对台独”以避免与“反分裂国家法”对撞，一面则巧妙地利用日本对“台海和平进程”的担心，刺激日本自信能迫使将精力集中在美国身上的中国、最终必将会顾全全局、而对日本做出一定让步、从而不惜触犯中国的核心国家利益、毫无顾忌地公开跳上支持台独的第一线。与此同时，美国则躲在日本和“台独”的后面，避开中国的锋芒、去从容地对整个东亚局面进行操盘。


在东方评论员看来，就以中日关系为例，对中国而言，中日关系的确重要、重要得足以严重影响中国的经济建设，但是，与日本比起来，对中国而言，中国却比日本“更能承受”一个破裂的中日关系。

而对日本则不同，中日关系的破裂，就意味着日本在亚洲的外交彻底完蛋、也就意味着其全球经济布局彻底走入死胡同。我们知道、日本经济与中国更多的是互补，而日本企业产品的主要竞争对手是欧美企业，日本企业更多地是在利用其与中国地理位置近的优势、将自己的许多技术产品通过中国的加工、最后转往欧美市场的。这就意味着、一旦失去中国市场的依托，日本唯一还能借助中国市场、通过在欧洲、美国间腾挪、从而仍然保有相当自主决策力的经济政策、也立刻就会受到来自欧美的联合夹击，一个极大的可能就是，其经济决策权也将彻底落入华盛顿的手中。

*** 以小泉被迫公开“道歉”为标志，华盛顿事先准备的剧本、被北京所打断

不难看出，破裂的中日关系对中国而言，已经是损失巨大，而对日本而言，中国却又比日本“更能承受”一个破裂的中日关系。必须强调的是，“这种承受力的大小”、本身就是一个国家综合国力的具体体现。

正是“中日美”三国之间中有这些“扯不断、理还乱”的瓜瓜葛葛，这就为北京破解华盛顿棋局提供了机会。

东方评论员认为，在中国外交部严辞警告日本“如果那样做将使东海问题必质完全变了”之后、中国国内多个城市爆发反日示威之后，特别是日本外相访华失败、小泉纯一郎被迫在亚非首脑会议上公开“道歉”之后，以日本的暂时让步为标志，华盛顿事先准备的那套剧本、也就被北京的一连串行动所打断。


*** 从整个过程来看，大陆的行棋步调“非常顺畅”

东方评论员认为，至此，北京和华盛顿之间的这场隔空较量中、取得了“阶段性的胜利”。事实上，这次是华盛顿早就摆好棋局、而北京也是欣然落座，但是、让华盛顿意外的是，北京没有按华盛顿的套路“出牌行棋”。


*** 大陆高明之处：先集中精力逼退了日本、而将华盛顿再一次请到了“台海问题”的前台

大陆高明之处就在于先集中精力、迫使日本现在就得选择中日关系何去何从的强硬方式、逼退了日本的公开挑衅、从而扫清了外围、并以此而将一直躲在日本、“台独”后面进行操盘的华盛顿、再一次请到了“台海问题”的前台、从而迫使华盛顿再次亲自与北京“面对面的谈”、“谈”包括台湾、朝核、日本定位问题在内的东亚整体问题。

之后，北京利用华盛顿在伊朗核问题、朝核问题上“等不及”的“战略焦虑”，在成功地迫使华盛顿同意那位已经被自己抛弃、并逼进了墙角的连战先行一步之后，又反手再请被连战的“和平之旅”逼到墙角的宋楚瑜、也“来京一谈”。


*** 陈水扁是否会登陆、又将何时登陆？

现在，在台湾无牌可打、被“扁宋会”挤得几近边缘化的连战、国民党、“为了活下去”、一到大陆就一把就拿出了“九二共识”，而随后因已被“十点共识”套住了宋楚瑜、在连战的一举成功、令国民党在台湾咸鱼翻身之后，深刻地感受到“由蓝变橙”后的空间极度萎缩、也“为了活下去”、在大陆被逼得交出了“两岸一中”。

如今，是棋到中盘，在东方评论员看来，连战、宋楚瑜的相继“成功访问”，让方方面面将目光聚集在了陈水扁的身上，方方面面都在思考的一个问题就是陈水扁是否能登陆、又将何时登陆？


东方评论员认为，在我们一起回顾了“326”时，自“绿色台商”（当然，现在应该摘帽了）就先知先觉地提出了“台湾、大陆同属一个中国”的政治主张起，到身揣“宪法一中”的“十点共识”登陆的宋楚瑜、最终淘涣了个“两岸一中”止、的这段时光后，我们再去欣赏上面的那篇精彩分析，应该另有一番感受在心中。

在我们看来，这种感受就是：剧本演到了这一步，尽管中间几处被北京“硬性涂鸭”，但直到今天为止，对北京和华盛顿而言，在台湾问题上，彼此想得到的结果、在近期内仍然“没有大的出入”，在东方评论员看来，“大的出入”将因北京对剧本的“硬性涂鸭”而在将来表现出来。

*** 华盛顿恐怕只能逼着陈水扁“按原来分配的角色”继续给演下去

事情到了这一步，看看朝核、伊拉克问题、看看伊核、巴以问题、再看看仍然没有完全死心的日本，在东方评论员看来，陈水扁的真正后台老板---华盛顿、恐怕只能逼着陈水扁“按原来分配的角色”、继续给演下去。因此，对陈水扁而言，只要中东方向没有大的变化，那么，华盛顿就“需要他继续”，不难看出，在如何选择的问题上，最终、陈水扁除了要么接受连战的“九二共识”、要么接受宋楚瑜的”两岸一中“之外、根本就没有其他的选择。

当然了，也不排除善于玩文字游戏的陈水扁不定能弄出个什么新名词来，但是，可以肯定的是，不论是如何动听的新名词，要让北京接受，就必须符合“一个中国的原则”，这是绕不过去的。

*** 被大陆肯定为“关键角色”的宋楚瑜，已经有了新想法

我们注意到，拿出“两岸一中”、并被大陆肯定为“关键角色”的宋楚瑜，在摆脱了“十点共识”的禁錮之后、可以说看到了新希望，不仅“干劲十足”，并已经有了新想法，即：他就公开提出，台湾有公权力的地方不是行政系统一家，因为“立法权”也是一种公权力。


*** 宋楚瑜要和连战一起、用法律的方式“压”陈水扁就犯

事实上，宋楚瑜已经在公开建议了，要和连战一起，利用“国亲”在台湾立法院多数的条件、行使“立法”这种公权力、去推动“立法”、从而用法律的方式“压”陈水扁就犯、通过台湾立法系统压行政当局接受连战谈妥的“五点共识”、和他自己谈成的“六点共识”。


*** 陈水扁的一个非常值得考虑的“解套方案”

首席评论员就指出，如果连战和宋楚瑜果真能在“立法院”、利用“多数”的力量逼陈水扁接受“国共的五点共识”、“共亲六点共识”，甚至以此登陆大陆、“再回北京”（88年陈水扁曾经到过北京）、实现世人期待的“胡扁会”，那么，对陈水扁而言，这未必是坏事，道理很简明单，到时他不论是接受连战带回的“九二共识”、还是宋楚瑜签下的“两岸一中”、那可都是被迫的，不论是民进党还是台联党，他陈水扁还都有话说，谁让你们在立法院“挡不住的”？既然“泛绿”挡不住，那也就别怪陈水扁“遵守法律”了、去做“遵纪守法”的“好领导人”了。在我们看来，这倒是陈水扁的一个非常值得考虑的“解套方案”。


东方评论员认为，既然宋楚瑜将“关键角色”的这顶帽子“早早地戴到了自己头上”，那么，他回到台湾后自然会有所动作，以重拾民心，在一段相关报道之后，东方评论员将再谈谈这个毛遂自荐的“关键角色”宋楚瑜、将最可能从哪里着手，他与连战又将如何“再牵手”！

《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
