# -*- org -*-

# Time-stamp: <2011-08-04 13:08:59 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

*  2005年8月26日 星期五



** 美国务院发言人称希尔已做好前往北京的准备




【华盛顿消息】据联合通讯社报道，美国国务院发言人麦克马克２５日（北京时间26日）表示，中国正在与朝鲜等六方会谈当事国继续协商，估计中国将在近几天内公布会谈复会日期。

麦克马克随后称，六方会谈美国团长、国务院亚太事务助理国务卿希尔和其代表团成员已做好去北京进行建设性协商的准备，希望这次会谈能够取得成功。

麦克马克还称，中国当天与朝鲜进行讨论等，继续与六方会谈其他当事国进行着协商工作。

对于朝鲜有没有明确表明重返会谈的意向的提问，麦克马克回答说：“在北京进入休会时各方商定，在８月２９日开始的一周恢复会谈，在通过纽约渠道进行的美朝接触上，还没有听到任何与该商定内容矛盾的信息。”

麦克马克介绍说，所有当事国到目前都认为，上次休会时的恢复会谈的商定仍有效。

麦克马克对“巴基斯坦核科学家卡迪尔•汗博士向朝鲜送去离心分离机的外电报道是否对六方会谈产生影响”的提问，否认称：“我们的观点不会由此而出现任何变化。”



【时事点评】在东方评论员看来，在休会的“六方会谈”即将复会的日子里、“六方会谈”成员国间的“对话”可以说是“空前的活络”，我们注意到，就在这短短的几天里、先是韩国负责国家安全的高官22日开赴俄罗斯、与俄罗斯“六方会谈”首席代表的俄副外长举行了会谈；接着、是24日韩国外长亲自飞到美国、与美国国务聊赖斯“交流观点”、与此同时，美国的外交官还在华盛顿与朝鲜的官员“互通有无”；


*** 这几天的“穿梭外交”显得非常热闹

最后，是“六方会谈”主席国--中国的首席代表、外交部副部长武大伟“应邀”飞到日本、不仅与日本“六方会谈”的首席代表“交换了意见”，还与日本的官员在中日关系的问题“交换了意见”。据说、会谈的气氛“尚好”，而按日本媒体的说法，日本自民党干事长武部勤甚至还有意在“入常”向来访的中国副外长“寻求合作”。

首席评论员指出，就目前的情况看，围绕着休会了的“六方会谈”能否如期在“８月２９日开始的一周”恢复会谈、“六方会谈”的“六方”都在为之“如期复会”而“紧张、认真地准备着”，这使得这几天的“穿梭外交”显得非常热闹。


*** 彼此间“全力角力”的一种“阶段性总结”

然而，俗话说得好，“外行看热闹、内行看门道”，在东方评论员看来，就在这热闹非常之“穿梭外交”的背后，其实是各方在“休会的三周”以来、彼此间“全力角力”的一种“阶段性总结”、是各国在“六方会谈”会场之外展示各自的筹码之后、“再次交底”的一个过程。


*** 东亚安全模式开始进入不可避免的调整阶段

事实上、我们认为，自去年年底北京“放风”要启动“反分裂国家法”立法进程、欲堵死美国一直在推动的“和平台独”的去路，而华盛顿则在明知“和平台独”已无任何模糊空间可供操作、遂高调“反台独”；再到之后的“两个月”期间、美国联手日本共同向中国施加压力、希望北京决策层放缓“立法”进程未果、于是在2月份美国将日本拉进涵盖台湾的“美日安保指针”后，一个原先公开针对苏联的“美日军事同盟”、尽管其大的架构没有变，仍然是美国主导日本协从的框架、但是、其内容却因正式贴上了“针对中国”的“专用标签”而发生了根本性的变化。

也就是从那开始，自二战之后、到五十年代初确立的、也一直沿用至今的东亚安全模式就开始进入不可避免的调整阶段。


*** 中俄联合军演不过是“这一系列较量”的一个“看得见、摸得着”的“高潮部分”而已

显然，在这场不可避免的调整中、不论是北京、还是华盛顿，可以说都在通过直接过招、或是间接交手的方式、尽力地在向对手、也在向“方方面面”不停地展示着自己的战略意图、与实现这些战略意图的决心与能力。

而刚刚结束的中俄联合军演、不过是“这一系列较量”的一个“方方面面”都“看得见、摸得着”的“高潮部分”而已。


*** 联合军演达到的“政治意图”远大于“军事意图”

在前面的专题部分、我们已经对中俄联合军演的“最后一天”给出了点评，东方评论员认为，作为中俄联合军演的最后一个演练科目--联合“强制隔离作战”、它之所以被选择为押轴戏，就在于这个旨在维持区域政治稳定演习的演习科目、“最能体现”中俄在中亚的共同利益、也“最能影射”华盛顿将来会遇到的战略困难。在我们看来，“这些”无疑非常地地体现了此次联合军演的“真正目的”-即中俄双方决策层想通过这次联合军演达到的“政治意图”远大于“军事意图”。


*** 展现维护自己核心利益的“政治决心与国家意志”、远比单纯地展示军力来得实在

就如我们之前所说的那样，由于“中俄美”都是核大国、相互间爆发战争谁“都不能指望有个好结果”。因此，在事关各方的核心利益上，证明自己在关键时刻是否有运用一切手段坚决维护这些核心利益的“政治决心与国家意志”、远比单纯地展示军力来得实在。

在我们看来、“中俄”通过“和平使命2005”里的“具体内容”、来展示自己的战略利益“之所在”、以及将维护这些战略利益的“决心与意志”、才是双方举行这场联合军事演习的真正目的。


*** 与军演“毫不搭界”的国际政治、经济的“互动因素”、

如果你一直在关注《东方时事解读》，那么，有一点印象应该是深刻的，即在我们点评这次联合军演的过程中、除了军演中的“纯军事层面”的内容交给我们的军事评论员进行军事角度的点评之外，时事评论员们在关注这场大规模联合军演的“演习现场画面”的同时、朝鲜半岛局势、中日关系、美日关系、印美关系、台海动态、中亚形势、南亚互动、中东动向、南美洲问题、甚至是世界油价、人民币汇率、中欧、中美贸易争端等国际政治、军事、经济“各方面的动向”、以及东方评论员对“这些动向”的最新看法、总是频繁地出现在《时事解读》“中俄联合军演”的“点评专题”中。

在我们看来，这些表面上看去与军演“毫不搭界”的国际政治、经济的“互动因素”、在时事评论员的眼里、却“正是”在中俄联合军演的强烈冲击下、所必然带来的“阵阵涟漪”。


*** 中美都在为将来“中美间最高层级”的战略对话提前“做着功课”

根据我们的观察，可以说以去年年底、北京放风启动“反分裂国家法”立法进程、欲堵死美国一直在推动的“和平台独”的去路，到这次中俄联合军演为止，中间所发生的许多事情、涉及中美双方重大利益的一系列事件、可以说都是北京与华盛顿间为了将来“中美间最高层级”的战略对话、所提前“做的功课”。


*** 美国想在正在进行中的”“确定双方将来的互动模式”的过程中“先声夺人”

其中，除了那份涵盖台湾的“美日安保指针”外，布什“亲自定义”中美关系为一个很难说清“是敌是友”的、“非常复杂的双方关系”、以及拉姆斯菲尔德亲自出面“兜售”种种版本的“中国威胁论”，并用各种包括政治、经济、军事手段去、想“论证中国是对手而不是伙伴”的“论证”过程，就是华盛顿方面“所做的功课”，为的就是要在中美两国“正在进行中的”“确定双方将来的互动模式”的过程中“先声夺人”。


*** 华盛顿抛出“中国威胁论”，是对北京的一次“全面测试”

首席评论员指出，我们必须清楚的是，华盛顿对“中国威胁论”进行的这种“论证”、其“论证课题”是直指中国的核心利益、不仅有国家安全问题、也有经济安全问题。

在东方评论员看来，“这种论证”其实是对中国包括战略决心、国家意志、实现自己战略决心的手段“是否足够灵活”等“综合力量”进行的一次“全面测试”。对这个观点，在之前的《东方时事解读》中、我们已经多次强调过。


*** 北京面对这场“全面测试”，采用了非常灵活的手段

显然，北京在面对这场“全面测试”的同时，采用了非常灵活的手段，即对“中国威胁论”中最能引起欧洲、美洲国家共鸣的“经济版本”进行“低调回应”、这表现在两个方面：第一，在6月份，北京“以相互让步、但中国让得更多的方式”、迅速与欧盟在纺织品问题上达成协议、从而将一场世界针对中国的贸易问题、在很大程度上变成“中美双方”问题。


*** 在人民币问题上让步，阶段性化解了华盛顿企盼的“欧美在经济上共同施压的一个最牢固的基础”

第二，面对人民币升值的压力、北京也采用了让步的方式，从而策略地缓解了来自欧洲的经济压力、阶段性化解了华盛顿企盼的“欧美在经济上共同施压的一个最牢固的基础”


*** 让人民币升值、对中国经济的损害是肯定的

在东方评论员看来，就第二点而言，客观而方，现在让人民币升值、对中国经济的损害是肯定的，而且是非常大的。事实上，人民币升值本身、以及人民币升值预期、已经伤及中国的众多电子企业，尽管这一点现在表现得不明显，但是，随着时间的推移、这种损害将逐渐积累、并表现出来，北京必须积极应对。


*** 北京仍然控制着人民币汇率的“定价权”


然而，我们也认为，北京在做出这一重大让步的同时，实际上也是在摆出一种万不得已情况下、准备在经济上与美国“硬耗”的姿态。我们在看到北京在人民币升值、并将人民币紧盯“一蓝子货币”的同时、也要注意到中国金融管理当局并没有公布“这一蓝子货币”的“各货币的具体加权权重”，再加上最为关键的“资本项目”仍然没有开放、这就意味着北京仍然控制着人民币汇率的“定价权”。


*** 人民币将进一步升值的市场预期，已经开始对美国长期利率产生影响

也就是说、北京在承受人民币升值损失的同时，在承受人民币必将日益增强升值的市场压力的同时，除了大量抛售美国国债这一不现实、操作性并不强的手段之外，北京实际上也获得了一种、自市场渠道影响美国资本市场的“效率不错的经济手段”。

事实上、根据我们的观察，人民币将进一步升值、中国贸易顺差必将减少、投资美国资本市场的中国资金也必将减少的市场心理、已经开始对美国长期利率产生影响。



*** “明知山有虎、偏向虎山行”的收购是不寻常的


另外，值得强调的是，就是中海油的那场失败的世纪收购，事实上，中海油收购美国尤尼克公司本身，就是顶着美国正在全方位、向全球大力宣传“中国威胁论”的“歪风”而进行的，在我们看来，这种“明知山有虎、偏向虎山行”的收购是不寻常的。

*** 中海油收购，这本身也是北京对美国的一种测试

值得强调的是，中海油高层在公开场合一再强调，“收购”事先请示过中国政府政府。在东方评论员看来，这本身说明收购也是北京对美国的一种测试、第一，是想看看主导国际金融与投资市场、玩转地球的美国人、到底是否能靠经济手段“摆平一切”，然而，测试的结果是大家有目共睹，就是“不行”，与中国企业一同竞标的那家美国公司，最后中标完全靠的是美国的“国家机器”。

第二，就是想测试一下美国政府、美国社会从“内心”中是如何定位中美关系的。只有让国际社会、包括美国社会看清楚了这一点，人们才能明了“市场规则”的“道德良知”挡不住“政治、军事霸权”。


*** 意识形态的东西、仍然是市场经济的“另一只手”

不难看出，这对中国国内某些热衷美国金融模式、盲从西方理论、“开口”市场手段、闭口“国际接轨”的经济理论也是个“讽刺”，对此，我们想说的是，第一，在事关国家命脉的“战略部门”，控制权一定要控制在自己手里；第二，意识形态的东西、仍然是市场经济的“另一只手”。

显然，测试的结果表明，美国社会的价值取向极容易受到媒体的操控，这一点在伊拉克战争中、在事关国家安全的问题上已经表现得淋漓尽致、这一次，国际社会看得非常清楚，在这样的一次商业行为上、在事关国家经济安全的问题、美国那种不容任何人染指“能源”这个美国全球战略核心之企图心、是再一次得到验证。

然而，尽管美国不让中国得到稳定的石油、但北京在别的地方也有自己的办法。在一段相关新闻后，我们将继续回到这个话题。


** 哈萨克斯坦外长认为中国在中亚具影响力优势



【新华网消息】哈萨克斯坦外长托卡耶夫本月23日在会见美《华盛顿时报》的记者和编辑时谈到了中国在中亚的地域优势和影响力等问题。该报24日以《中国在中亚》为题发表文章，报道了会见时的谈话内容：

托卡耶夫认为，最近在扩大在中亚影响力的竞赛中，中国取得了胜利。他说：“我认为哈萨克斯坦除了与这个国家保持友好合作关系外，别无选择，因为我们无法选择邻国。”

当记者问及哈萨克斯坦如何看待几个国家寻求扩大在中亚的影响力的竞争时，托卡耶夫说：“我们的信条是要保持几个大国的利益均衡。”

托卡耶夫承认中国在中亚地区占优势地位。他说：“中国的潜力和雄心都在日益增强。”中国已经在出资铺设从哈萨克斯坦到中国的耗资8．5亿美元的输油管道。这条将于今年12月竣工的管道每天可以输送40万桶原油。中国还持有哈萨克斯坦另一家大的石油公司大约60％的股份。

中国石油公司还与乌兹别克斯坦签署了合资建一个6亿美元的企业的协议。托卡耶夫还谈到了中国给上海合作组织国家提供9亿美元贷款的事宜。托卡耶夫说，与美国不一样，北京不逼迫这些国家实行民主改革。他说，在看待中国的影响力时，“你不得不考虑这一点”。

上海合作组织7月发表宣言说，在阿富汗战争中临时使用中亚基地的反恐联盟成员国（即美国）必须确定一个撤出基地的时间表。托卡耶夫说，上海合作组织“其它国家”主张发表一项明确针对美国的言辞更强烈的声明，但是哈萨克斯坦反对那么做。7月29日，乌兹别克斯坦外交部通知美国方面必须在3个月之内撤离在乌境内的基地。

在反恐方面，美国和中国在中亚地区的利益是一致的。但是，在争夺能源和地区影响力方面，华盛顿和北京看起来是对手。



【时事点评】显然，既然美国人不让中国从市场中获得稳定的石油，那么，北京别无它法，只好自行其事。事实上，北京正在“上海合作组织”的“掩护”下、利用自己的经济实力、正在做整合中亚经济的准备工作、以在中亚建立自己的能源供应基地。

东方评论员认为，在这一点上，北京已经明显有种时不我待的紧迫感，因为在能源问题上，华盛顿已经正式将其当成“现实牌”来打。保住了中亚和俄罗斯这两条能源渠道、中国在与美国“确定”“今后如何相处”的问题上，就少了许多被动。

*** 华盛顿对即将访美的胡锦涛主施加压力、敦促北京做战略让步的一个“市场手段”

就在昨天，国际石油期货又创下了“新纪录”，显然，这在很大程度上是美国政府、借助美国投资机构“做成”的一份“行情图表”，这也是华盛顿决策层准备用以从经济层面冲着即将对美展开访问的胡锦涛主施加压力、敦促北京做战略让步的一个“市场手段”。


*** 北京经过这一轮测试，定会对人民币“定价权”更加不愿意撒手

东方评论员认为，北京经过这一轮针对华盛顿的测试，肯定会对人民币汇率机制中的“定价权”更加不愿意撒手，此外、华盛顿如再来指责中国违背市场、操控汇率、北京也知道了“如何提醒”美国“如何才算是违背市场规律”、以及违背市场规律的确后果严重：比如说，由于人民币有继续升值的预期、中国贸易顺差必将减少的、投资美国债券市场的中国资金也必将减少、更重要的是国际资本已经经中海油的遭遇彻底看清楚了这么一个事实，那就是、拥有7000亿美元巨额外汇储备的中国、欲想让资本大规模投资美国“必将遭到强大的政治阻力”。

总之、东方经济评论员的观点是一惯的，那就是，人民币在这个时候升值、对中国经济不利、同时、对美国经济也不利。对华盛顿决策层而言，压与“美元”充分互补的“人民币”升值，实际上是种损人不利已的政治短视，美国共和党政府、和共和党控制的国会最后在人民币问题上对中国施加压力、是出于自己的政治企图，而这种政治企图、共和党极可能将付出更大的政治代价。

在我们看来，这一点已经得到了验证，今后必将进一步得到验证。


*** 足以让国际投资者对美国的债券投资“感到担心”

在我们看来，这些都足以让国际投资者对美国的债券投资“感到担心”，而这种担心，对每天都需要数十亿美元外资填补贸易亏空的美国经济而言，其对美国长期投资的影响将一天天积累起来、显然，人们一想到长期投资，就容易想到房地产这几个字，的确，房地产已经是支撑美国经济的支柱，但美国房地产的泡沫也是有目共睹，而长期利率“将上升的心理预期”，首先沉重打击的的就是美国的房地产。


*** 人民币升值因素“所起的坏作用”、是格林斯潘早就预料到的


事实上，就在前天，在《东方国际投资》中，经济评论员已经说过，美国房地产泡沫已经开始让格林斯潘感到“空前的揪心”、因为美国的“二手房市场”已经开始回落。

在我们看来，这当然有美国联储“再一次”调升短期利率的因素，但更重要是，之前那种美国调升短期利率不会推高长期利率的“好时光”、似乎已经到了尽头，至于原因嘛，什么说法都有。

在我们看来，人民币升值因素对美国经济“所起的坏作用”、是格林斯潘早就预料到的，不然，“这位经验极其丰富的老头”、以及掌握全面信息的美国财政部、怎么可能一再为“中国先前不升值人民币的政策”拼命说好话、做解释？


*** 北京应对美国“论证”“中国威胁论”的手段、大体还是灵活的

东方评论员看来，北京在应对美国“论证”“中国威胁论”的手段、大体还是灵活的，我们认为，“这种灵活”表现在“将矛盾集中在美国身上”、并在有所让步的同时、也主动出击。

在经济领域外，北京的主动出击更是明显，其中，与俄罗斯一起、主导着“上海合作组织”、并以组织的名义发表了一份旨在让美国部署在“上合”成员国的军事基地限期撤离的“共同声明”，这对美国的全球战略的冲击是不言而喻的，不难看出，中美在“确定”中美“互动模式”之前的较量、是全方位的，不仅有经济安全层面的、也有国家安全层面的。


*** 王光亚所说的那句、“伊朗核问题不应该提交联合国解决了”所起的“破坏性作用”

此外，就是“朝核问题”的解决进程，在东方评论员看来，北京在“朝核问题”中的主动权非常明显，这一点，正是在北京利用韩国急于保住朝鲜半岛长久和平、进而整合朝鲜半岛经济、打开自己的发展空间的战略心理、成功地离间了“美韩军事同盟”、才得以实现的。

还有，在伊朗核问题上，伊朗与欧盟间“真真假假”的争斗，与国际原子能组织间“有理说理”的“口水战”、以及与中国之间“只做不说”的、包括军事在内的“全面合作”、再加上与俄罗斯之间“且说且做”的“互抬身价”、在华盛顿决策层看来，“其中都能看到”中国常驻联合国代表王光亚所说的那句、“伊朗核问题不应该提交联合国解决了”所起的“破坏性作用”。


*** 中美“各自的功课”都还没有做完、或者说对结果双方还没有”相互认可”

总而言之，中美间的“这种对话前的准备工作”一直做到今天，而且、从朝核问题第四轮“六方会谈”的日期仍然没有最后敲定、足以看出，“中美各自的功课”还没有做完，或者说对结果双方没有“相互认可”。

东方评论员认为，这次北京与俄罗斯搞的这个“和平使命2005”、以及美国拉着韩国搞的“乙支焦点透镜05”、对双方而言，都不过是个“阶段性的课题”而已、尽管“这个双方一起做的课题”、其“综合性极强”。

就如首席评论员之前所说的那样，这次中俄联合军演的“政治内涵”远远大于其“军事内涵”、甚至是“经济上的意义”也要远大于其“军事上的意义”。事实上，胡锦涛主席即将展开的美国之行，是在强化了“上海合作组织”功能、“朝核问题”韩国已经不愿意再拖的情况下展开的。


*** 按大国间的博弈潜规则，中美也就到了“坐下来好好商量今后怎么相处”的阶段

说白了，为了这次中美高层对话、美国抛出“中国威胁论”对北京进行战略测试，而北京也通过一系列手段、同样也对华盛顿进行了一番战略测试、在这种“你来我往”的过程中，中国决策层已经充分展示了自己有能力、有决心维护自己的核心战略利益、并将自己的战略资源不加掩饰地“指向”美国的战略核心地带，这样，按大国间的博弈潜规则，中美双方也就到了“坐下来好好商量今后怎么相处”的阶段、尽管“这种确定”不会在一次访问中完成。

也正因如此，我们认为，美国国务院发言人麦克马克随后称，“六方会谈美国团长、国务院亚太事务助理国务卿希尔和其代表团成员已做好去北京进行建设性协商的准备，希望这次会谈能够取得成功”、是有一定根据的。但是，在时间上、很可能还得拖上一段。


*** 胡锦涛主席的美国之行、就是要收获此次“中俄联手”的“政治、与经济溢价”

也正是在这一基础上，东方评论员认为，“中美俄”各自带着“美日军事同盟”、“上海合作组织”、朝核问题、伊朗核问题、巴以和平问题、伊拉克政治重建问题等等、各自可以利用的战略资源、抢在9月5日之前各自完成了“战略展开”、与“战略意图、战略实力”的演示之后，这轮拟定中的中美高峰对话也就到了“合议”的阶段。显然，胡锦涛主席的美国之行、就是要收获此次“中俄联手”的“政治、与经济溢价”、尽管要做到这一点、还有一番争斗。


*** “中美争斗”的几个明显的观察点

在东方评论员看来，“争斗”的一个明显的观察点就是“六方会谈”的进度如何、伊朗核问题有何进展、再就是上海合作组织的声音是否再次加强等。当然，如果中日关系有了走向“和解”的信号、那就意味着中美“就今后如何相处”的问题、接近于达成“阶段性协议”、尽管这种“协议”是动态的、是随时可能变化的，但它仍然对世界格局具有重要意义。

*** 胡锦涛如能“如期成行”、布什11月份回访中国之前，很可能会“临时安排”一次“美俄”首脑对话

另外，首席评论员认为，按我们的经验，胡锦涛主席如能“如期成行”、那么、在布什总统11月份回访中国之前，很可能会“临时安排”一次“美俄”首脑对话，从而华盛顿和莫斯科之间也会尝试为双方关系“确定”点什么，为什么？因为我们认为这才符合“中俄美”间这种“极其复杂的战略互动关系”。

下面，还是一则有关朝核问题的消息，在一起了解之后，我们将继续讨论东北亚经济一体化的问题，显然，在东方评论员看来，“这个问题”也是一张胡锦涛主席可以带到华盛顿去的筹码。
《东方时代环球时事解读.时事节简版》http://www.dongfangtime.com
