# -*- org -*-

# Time-stamp: <2011-08-02 19:53:18 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

#+STARTUP: indent

* 2005年03月23日 星期三

** 传美日限定最后期限 中方力避六方会谈破局

【北京消息】胡锦涛23日下午在人民大会堂会见了朝鲜总理朴凤柱。此前，海外媒体分析，中方不大可能向朝鲜施压，而是积极同朝鲜展开对话。而继日本设定六月份为促成六方会谈努力的最后期限之后，日本东京的外交界消息透露，美国也订下今年六月底为最后的限期。
 
美日为会谈设最后限期
 
据来自日本东京的外交界消息透露，美国已经订下今年六月底的限期，要求朝鲜在限期前重回朝核问题六方会谈。而路透社说，美国对朝鲜拒绝恢复六方会谈已感到越来越不耐烦，美国国务卿赖斯在北京访问时曾多次朝鲜立即返回六方会谈谈判桌。
 
此前，共同社援引多名六方会谈相关人士透露，日本外务省亚洲大洋洲局审议官斋木昭隆在上海召开的专家会议上提交了一份提案，内容为：如果朝鲜对重开朝核六方会谈不作出回应的话，则在6月之前终止会谈，并将该问题交由联合国安理会处理。斋木是六方会谈日本次席代表，而日本政府负责人在正式场合提及终止会谈并交由安理会处理的具体期限则尚属首次。
 
相关分析认为，美日此举的目的在于向朝鲜施压，以促使问题早日得到解决，预计将招致朝方的强烈反对。但也有观点认为，这样设定期限并不仅仅是要表明两国的立场，同时也是想借此观察一下其他各国的反应。
 
中方“会同朝鲜对话”
 
纽约时报22日指出，在美国国务卿赖斯敦促中国就朝鲜核问题继续向平壤压力时，中国国家主席胡锦涛和总理温家宝并没有向赖斯保证一定向朝鲜施压。而赖斯此次东北亚之行中，只要一有机会便会反复敦促“中国应起到积极的作用”。纽约时报引用随行的美国高级官员的话说，中国国家主席胡锦涛和总理温家宝等中国高层领导人在会谈中只是表示“会同朝鲜对话”，但没有谈到具体的施压措施。

关于中国不愿向朝鲜施压的背景，纽约时报分析说，中国不信任美国的朝鲜核情报，可能认为美国对朝鲜的军事打击和朝鲜政权崩溃的危险性，比尚未证实的核武器更具威胁。
 
 
俄罗斯希望恢复六方会谈
 
凤凰卫视驻莫斯科记者卢宇光报道说，莫斯科时间3月23日，俄罗斯外交部新闻发言人雅科列科称，俄罗斯副外长阿列克谢耶夫22日与朝鲜驻俄大使朴义春会晤时重申，俄罗斯赞成尽快恢复朝核问题六方会谈。
 
阿列克谢耶夫还强调，俄罗斯反对将东北亚地区的局势复杂化和损害该地区睦邻关系的任何行为。他说，认真考虑有关国家的建设性意见，将对恢复六方会谈以及在朝鲜半岛实现无核化大有益处。
 

【时事点评】事实上，以6月份为期限的提法最早见诸于日本媒体，消息来源正是日本政府。值得注意的是，与作为配角的日本、对朝鲜摆出的一副咄咄逼人的态度不同的是，朝核问题的主角之一--华盛顿，这次的态度倒显得温和得多。
 

*** 日本向外面散发消息、称美国订下最后的限期非常耐人寻味

在东方评论员看来，日本的外交界向外面散发消息、称美国订下“今年六月底”为最后的限期，这非常耐人寻味。因为直到目前为止，美国方面最强硬的话也仅仅是“六方会谈不能无限期拖延”。也就是说，除了日本人泄露出来的这则消息给了个“6月期限”之外，东方评论员并没有发现美国人提及过“6月”这个时间。
 

*** 布什之前让美国军方“发话”不过是在“故作姿态”

首席评论员指出，显然，赖斯的北京之行本身，已经显示了布什终于迫切地感到“朝核问题”已经不是早前的那个可以“拖一拖”、“缓一缓”“朝核问题”了，但是，从赖斯一到北京，布什就立刻通过美国军方、让美国参谋长联席会议主席迈尔斯出面强硬地表示“如果有必要，美军有能力在阿富汗和伊拉克境内采取军事行动的同时对付朝鲜”，在我们看来，这种态度不可谓不强硬。

但是，赖斯在北京经过两天的逗留之后，临离开时却扔出了这么一句话，她说，“我们无意诉诸武力”，在东方评论员看来，这说明布什之前让美国军方“发话”不过是在“故作姿态”。
 

*** 只要得到北京的坚定保护，那么，朝鲜绝不可能是“伊拉克第二”

我们认为，美军是否有能力“在阿富汗和伊拉克境内采取军事行动的同时对付朝鲜”，可以说已经无需多言，公认的观点是，如果朝鲜“不靠近”中国和俄罗斯，那么，将很难逃脱“伊拉克第二”的厄运，可问题就是朝鲜不仅靠近中俄两国，更是得到了北京的公开庇护，因此，公认的观点又认为，只要得到北京的坚定保护，那么，朝鲜绝不可能是“伊拉克第二”。
 

*** 日本恰恰在这个关键的时候在那里给朝鲜“划期限”、“发通谍”

事实上，迫切需要朝核问题有所进展、以避免“东亚紧张局势”恶化到核竞赛地步的布什、在“故作姿态”的时候终究不敢将话说大，而得给朝鲜有可能重回“六方会谈”留个台阶下。

而就在赖斯带来一份中国认为“可以认真研究一下”的“建设性意见”的同时，也就在各方面都对朝核问题和台海局势是否有积极的转机怀有一丝希望的时候，日本也恰恰在这个关键的时候在那里给朝鲜“划期限”、“发通谍”，并以强硬的口气威胁和警告朝鲜，其“搞事”的居心是一看便知。
 

*** 本质上来讲，日本的角色就是中美间的一种平衡力量

东方评论员认为，从东亚的政治格局来看，对中美两国而言，日本是重要的。特别是在台湾问题上，来自日本全力支持的保证、更是美军可以夸下“一定会军事干预台海”这个“海口”的前提条件。可以说，一个没有多大政治、军事力量的日本，之所以如此重要，就在于它能在中美两大强权的博弈中、找到自己的角色。

首席评论员指出，对日本而言，本质上来讲，它的角色就是中美间的一种平衡力量，仅此而已。可是，一向也想支配亚洲、支配世界的日本，偏偏将自己拔高到了与中国一样、可以与美国一争高下、是可以成为世界另一极的“大国”。对此，华盛顿一直保持着高度的警惕。
 

*** 在中东一再失算的华盛顿，为了瓦解“中欧俄”，可以说先后下了三步棋

然而，美国在中东政策上的失败，在布什于去年11月份连任、立刻攻打伊拉克费卢杰之后，再一次彰显出来，在东方评论员看来，攻打费卢杰加剧了伊拉克选举的困难、更加剧了选举后“伊拉克政治重建”的困难，而这不仅令华盛顿无法从伊拉克抽身，更使得华盛顿中东计划的重中之重、解决“伊朗问题”根本就无从着手。

首席评论员认为，美国在伊拉克遭到的这个“没有想到的麻烦”，立刻被“中欧俄”死死地揪住、从而在伊朗核问题上，以强硬的态度迫使华盛顿考虑将“伊拉克、伊朗、巴以冲突”捆在一起进行解决的“多边主义”。

在我们看来，在中东一再失算的华盛顿，为了瓦解“中欧俄”，可以说先后下了三步棋，一步棋就在乌克兰，只是令华盛顿丢脸的是，在美国和欧洲一起将当时的反对派、现在的总统尤先科“拱上台”之后，并没有让欧洲和俄罗斯之间的缝隙更大些，反而让欧洲和俄罗斯在“面对现实的共识”下，有意“主动消除”因乌克兰带来的不快，这表现在尤先科一上台就立刻分别访问了俄罗斯和欧盟，不仅强调俄罗斯对乌克兰的重要性是无以复加，更强调融入欧洲是乌克兰的前途之所系，并以实际行动兑现这一诺言，宣布从伊拉克撤军，从而将那个为了将自己“拱上台”出了大气力的华盛顿丢在了一边。
 

*** 第二步棋就在东亚
 
华盛顿，为了瓦解“中欧俄”的第二步棋就在东亚。在东方评论员看来，华盛顿走的这着棋，集中表现在两个方面，首先，布什连任成功后，由于没有连任的后顾之忧，就立刻置鲍威尔访体裁所说的“台独不是个主权国家”的立场于不顾，默许陈水扁继续原先的计划，陈水扁也就立刻开始“大放撅词”，于台湾“立法委员”大选前一再放言“制定新宪”，北京没有直接去回应“台独”、不在“陈水扁台独言行”问题上“过多的理论”，反而转换方向、在华盛顿最关心的伊朗问题上“空前地主动”。
 
东方评论员认为，在华盛顿想以强硬的手段逼北京于中东、台海让步不成之后，为了稳住北京、又放下尊严、突然又说什么陈水扁通过玩文字游戏、这才有了美国人对陈水扁的‘新宪法’的说法觉得“受到糊弄”，也因此才有了华盛顿将紧盯陈水扁所谓“新宪法”动向如何、并放言“将做持续性观察”。
 
然而，就在华盛顿宣称“紧盯”陈水扁所谓“新宪法”动向的同时，北京开始放风启动“反分裂国家法”的立法进程，为防止“台独”与“反分裂法”现在就迎头相撞，美国不得已开始了一轮可以说是“空前”的“反台独”浪潮，直到现在。

事实上，在北京启动旨在将“517最后通谍”主要精神法律化的“反分裂国家法”进程之后，美国一再“明阻暗推”的“和平台独”就彻底成了不可能，而”大陆是纸老虎”的宣传口号也被这部授权中央政府有权力、也必须对“台独”动武的“反分裂国家法”扔进了垃圾箱。
 

*** 如何让台湾社会相信大陆不敢对“特定形式的台独”动武，如何为“台独”护行、就成了华盛顿必须解决的问题
 
 
如此一来，如何为“台独”护行，如何让台湾社会相信“台独”仍然有希望，如何让台湾社会相信大陆不敢对“特定形式的台独”动武，从而使美国将来因中东政策、全球战略的需要去“打台独牌”创造条件，就成了华盛顿必须解决的问题。
 

*** 日本也就立刻找准了自己的角色，找准了对外政策方向和感觉

然而，就如前面所说的那样，来自日本全力支持的保证、就是美军可以夸下“一定会军事干预台海”这个“海口”、让台湾社会相信美国有能力“协防台湾”的前提条件。在这种情况下，日本的战略价值也就立刻飙升，因此一个没有多大政治、军事力量的日本，却渴望着迅速成长为“政治、军事强权”的日本、也就立刻在中美两大强权的这场博弈中、找准了自己的角色，找准了对外政策方向和感觉。

在东方评论员看来，日本的这种“方向和感觉”，就表现在日本选择在大年初一的时候，以钓鱼岛主权问题这个极度敏感的问题、去极度挑畔中国政府、其意图就是逼迫中国出手心人强硬手段回击日本，从而好为日本政府利用去动员日本社会、为继续扩军制造舆论。
 

*** 华盛顿是宁愿在“美日安全条约”上放慢点、宁愿在朝核问题上让步一点，也不愿意让日本跨入核门槛

或许日本没有想到北京对日本的挑衅是以朝鲜“宣布有核武器”的方式进行反击，在我们看来，朝鲜宣布有核的最严重的后果就是东亚进入核竞赛，这对中国说不上是什么好事，但对美国而言更不可接受，会因此而“大喜过望”就是“日韩”，特别是日本，显然，如果能借此成为核国家，那么，实际上也就可以摆脱美国的控制、获得根本性的自由。

然而，在东方评论员看来，就如我们现在所看到的这样，华盛顿是宁愿在“美日安全条约”上放慢点、宁愿让“台独”“再委曲一点”、宁愿在朝核问题上让步一点，也不愿意让日本跨入核门槛。
 

*** 在中美还不到摊牌的时候，日本那种摆脱美国、争霸一方的战略目标就注定不会实现
 
事实上，在东方评论员看来，赖斯的北京之行，如果最终能让朝核问题有个各方都能接受的方案（这里面应该包括台湾问题方案）、从而让朝鲜半岛在“六方会谈”的基础上、走出一条甚至会包括欧盟、联合国各种力量在内“多边框架”保障下的、缓和之路的话，那么，一个与中国、韩国这两个亚洲大国闹得不可收拾、却又一无所获的日本，就如同被剥光了衣服一般、站在亚洲各国的眼中、站在世界各国的眼中。
 
由此可见，中美日在东亚问题上的所做所为，特别是中美之间的“边打边谈”、是与各自的战略目标紧紧相随的。在东方评论员看来，在中美还不到摊牌的时候，日本那种摆脱美国、争霸一方的战略目标就注定不会实现，但是，我们说“一无所获的日本”，是指相比它以牺牲它在亚洲国家的信任为代价的这一轮赌博中、没有获取相应的回报，并非说日本就真的什么都得不到。
 

*** 赖斯所说的“毫不含糊地支持”根本就子虚乌有
 
在我们看来，华盛顿为了压制和安抚日本的“核武梦”，3月19日晚，我们注意到，赖斯在东京一所大学发表演说时，突然“最明确”表态支持日本成为安理会常任理事国。她说：“日本通过它的努力和它的特性，已经在民族国家之林中赢得了值得尊敬的地位，这是美国毫不含糊地支持日本成为安理会常任理事国的原因。”
 
可是，只要我们翻翻2004年的备忘录，就不难看到，美国在整个2004年对日本“常任”的态度就在“不断变化”，赖斯所说的“毫不含糊地支持”根本就子虚乌有。在东方评论员看来，在“反分裂法”通过后、赖斯所提的“毫不含糊地支持”，一方面是对为华盛顿甘当犬马、“恶心”中国、搅和台海局势的一件给日本的礼物；第二，则是以此来部分化解在“美日安全共同声明”中出卖日本的一种补偿，第三，恐怕也是最主要的是了，那就是，换取日本在东亚停止“闹事”。
 

*** 我们很可能看到的结果
 
在东方评论员看来，如果日本所言的“6月期限”是美日间达成的“君子协定”期限的话，那么，我们很可能看到的结果是，今后几个月里，日本将会停止出于“核武梦”的目的、去进一步刺激韩国、刺激朝鲜的做法，以配合美国的、急欲稳定朝核局势的、新的“朝核政策”。
 
在连续两天的点评中，我们都跟踪分析了联合国改革的问题，今天，结合一则最新消息，东方评论员将继续在“日本得到了什么”这个问题上再讲几句。
 
《东方时代环球时事解读》http://www.dongfangtime.com

** 欧盟对安南提出的联合国改革方案表示支持

【布鲁塞尔消息】欧盟轮值主席国卢森堡副首相兼外交和移民大臣让·阿塞尔博恩２３日在布鲁塞尔说，欧盟完全支持联合国秘书长安南近日提出的联合国改革方案。

阿塞尔博恩在欧盟首脑会议结束后举行的记者招待会上说，欧盟“百分之百地”支持安南提出的联合国改革计划，认为联合国应当是国际社会预防冲突和危机的“主要工具”。

安南２１日在纽约联合国总部提交了联合国改革报告。他说，即便安理会扩大，新当选的常任理事国也不会拥有否决权。安理会改革的目的是增加发展中国家在安理会的席位，增强第三世界的影响力。
 
  

【时事点评】在东方评论员看来，欧盟首脑会议决定欧盟“百分之百地”支持安南提出的联合国改革计划的结果是“理所当然”，就如我们在昨天的《时事解读》中所说的那样，这份“联合国改革方案”，是一个“中、美、俄、法、英”五大常任理事国“充分妥协”、“充分配合”的结果，也是最有可能成为常任理事国的日本、德国、印度、巴西“相互抬桩”的结果。
 

*** 这一改革进程“真正被激活”的因素，就是美国一手挑起的“伊拉克战争”

我们认为，联合国改革的呼声其实早已有之，这一改革进程“真正被激活”的因素，就是美国一手挑起的“伊拉克战争”。东方评论员认为，这种痕迹甚至可以在安南提交的“报告草案”中找到，我们注意到，《联合国宪章》第51条指出，主权国家有权在遭到袭击时进行自卫，包括对“迫在眉睫的”威胁采取“先发制人”的军事行动。但是，“报告草案”中则明确提出，建议将“预防性”军事行动的决定收归安理会所有，这就是说，对于“潜在的”或“非迫在眉睫的”威胁，是否“预防性”地采取军事行动，应由安理会决定。在东方评论员看来，这一条分明是冲着美国去的。
 

*** 这份“报告草案”正式出炉之后，联合国的改革方案也就“似乎确定了”

我们认为，被“伊拉克战争”激活的“联合国改革”已经成了一股“浩浩荡荡”的潮流，并为世界上100多个国家所支持，因此，在东方评论员看来，在这份“报告草案”正式出炉之后，联合国的改革方案也就“似乎确定了”。

就如我们之前据说的，方案虽然有两个，但最可能的改革方案是增加6个没有否决权的常任理事国以及3个经选举产生的非常任理事国，其中非洲和亚太地区各有2个常任席位，欧洲和美洲各增加1个常任席位。

如此一来，尽管“五常任理事国”没有一家真心愿意让别的国家加进来分割自己的权力的，但“五国”还没有哪一家愿意出这个头去反对改革、去与“百国”公开为敌的。
 

*** 一个没有“否决权”的常任理事国，到底算哪一档子的事，恐怕手握否决权的“五常”心中最清楚

何况增加几个“没有否决权”的常任理事国一来可以顺应要求联合国改革的舆论，二来，“五常”也可以趁机着眼于自己的战略利益，进行全球布局，第三，也是最关键的，并没有让“新一代”常任理事国“抢自己的班、夺自己的权”，毕竟有无“否决权”就是现在“常任”与“非常任”之间的本质区别所在，在东方评论员看来，一个没有“否决权”的常任理事国，到底算哪一档子的事，恐怕手握否决权的“五常”心中最清楚。
 

*** 华盛顿要增加自己的帮手，中欧当然也会在美国不乐意的名单中挑选“对象”

在东方评论员看来，上面那四个“相互抬桩”并得到强大支持的日本、德国、印度、巴西成为“新一代”常任理事国就似乎是“板上钉钉”的事了。别的国家不说，就以这两个国家为例，他们的支持者分别是美国极力支持日本、中国、欧洲也极力支持巴西，这就是说，仅此就可以看出，既然华盛顿要增加一个或两个“常任理事国”、在安理会里做帮手，中欧当然也会有同样的想法，在美国不乐意的名单中挑选象巴西这样的国家去“回敬”。


*** 北京支持巴西、就如同华盛顿支持日本

对中美而言，这种安排更是理所当然的，美国要在中国的家门口增加一个“政治大国”，而中国就在美国的后院挑一个“政治中心”，美国国内近来狂炒中国对南美洲的渗透，也并非是空穴来风，只是主角搞错了，在东方评论员看来，与欧洲在南美的“不遗余力”相比较而言，中国还只是开始、所做的还远远不够。

我们之所以拿巴西说事，就在于从国际战略的角度来看，由于中国和欧洲一样，都已经将拓展影响力的目光投向了美国的后院--拉美，因此，巴西其实是中国、欧洲的首选国。
  其中的道理，就有如华盛顿要放言在中国的身边增加一个“政治中心”东京一个样，让巴西这么个大国在美洲大陆上形成自己的势力，自然也是北京和欧洲乐意看到的事情。之前，东方评论员也已经表示，北京之所以提出要考虑“发展中国家”，其目的多半也在于此。


*** “新一代”的尴尬，其实是“老一代”“共同”“深谋远虑”的结果                                           

在我们看来，考虑到没有否决权这一关键因素，因此，尽管“这一拨”“常任理事国”将来也可以算得上是“体面和风光”的“政治大国”和“政治中心”，在今后的国际活动中，也能凭借这种身份捞取不菲的利益，但是和有“五常”比起来，终究有点“不伦不类”、不是那么回事。

熟悉联合国程序的人都清楚，联合国其实是在“五国”掌握之中运行着的，任何提案，如果没有“五国”的支持，都是白搭，只要“五国”中任何一家抻手阻拦，联合国就什么决议都不可能进行，也正是如此，“老一代”的“五常”可以说凭借这一特权获取了巨大的利益，“五常”中的任何一家又怎么肯让别人来分享自己那份即得的特权呢？

因此，对“新一代”的“常任理事国”而言，其身份的尴尬，其实就是“老一代”“常任理事国”一起“深谋远虑”的结果。在东方评论员看来，“新一代”的“常任理事国”身份的尴尬源泉，就在于“新一代”嫩了点。

要知道，“新一代”在联手鼓动联合国进行改革的时候，其最大的理由就是“五国”就经常为一件事情闹得联合国“只议不决”，效率不高，而“老一代”的“五常”为了保住自己的特权，也正是抓住了这一点，反戈一击的。
 

*** 孔泉在去年所说的一句话，就已经是在“暗埋伏笔”了

在东方评论员看来，比较典型的例子就是中国外交部发言人孔泉在去年所说的一句话，他说“改革目标之一是提高工作效率”，显然，这已经是“暗埋伏笔”了，这就是说，如果再添加几个进“常委”，可以想像，联合国只会更乱，安理会效率更低，在东方评论员看来，这分明是在堵”新一代”要求分权的“嘴巴”。

有意思的是，和北京的态度一样，之后，美国、英国、法国、俄罗斯这些“老一代”，象是商量好了似的，是轮流出来“找理由、谈感想”，说来说去，就只有一点，就是从各个方面、多层次地、去证明“增加有否决权的常任理事国是多么地不合适”。
 
 
*** “五常”在联手将“新一代”赶到了“第二排”的位置上之后，彼此间又开始了角力

结果是，尽管德国、日本等有“雄心壮志”的“新一代”一直强烈地反对成为“没有否决权”的常任理事国，然而，这种“强烈反对”只会更加加强“有否决权的”“五常”的“权力欲”，从而更加坚决地“否决”掉“新一代”的政治抱负。

显然，“有否决权的”“五常”运用自己的特权、坚决地“否决”了“新一代”的“最大愿望”之后，可以肯定的是，联合国的改革虽然带来了一种变化，但是，在“老一代”中的利益纷争更加激烈之后，特别是“这种变化”又是“五常”基于各自战略利益而达成的一种“全面妥协”的结果，也就是说，“五常”在联手将“新一代”赶到了“第二排”的位置上之后，彼此间又开始了角力，为各自支持的“意中人”而拳脚相向了。
 
 
*** 中国肯定会找日本的一些麻烦的

在东方评论员看来，由于安理会扩大需要联合国191成员国三分之二多数通过，因此，日本要想能够成为联合国安理会的常任理事国，路途还“非常遥远”。
 
因此，我们认为，在日本是否能成为安理会“没有否决权的”常任理事国问题上，中国肯定会找日本的一些麻烦的，比如说公开、或暗中去做“反对工作”，全力阻止日本“当选”。
 
但是，最大的可能就是，如果到了最后、日本仍然“榜上有名”，而北京所中意的候选国也在其列，那么北京就不太可能因“就要否决日本”而否决整个改革方案，因为在这个改革方案的安排中，就有北京自己的全局利益之所在。
 
  前面已经说了，一个没有多大政治、军事力量的日本，之所以如此重要，就在于它能在中美两大强权的博弈中、找到自己的角色，在东方评论员看来，就算日本最后成了一个“新一代”的常任理事国，由于没有“否决权”，也就无所谓成为“真正的政治大国”，再加上在军事、经济上仍然“不自由”，可以说亚洲、特别是东亚，仍然是中、美博弈的舞台。因此，对日本而言，本质上来讲，它的角色还是中美间的一种平衡力量，仅此而已。
 
《东方时代环球时事解读》http://www.dongfangtime.com
