# -*- org -*-

# Time-stamp: <2011-09-15 09:59:04 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+STYLE: <link rel="stylesheet" type="text/css" href="css/org.css">

* [2010年7月29日 星期五]


** 北约部队加强科索沃北部地区戒备


【华盛顿消息】[[file:news/2011-07-28.html#7-27][据英国媒体7月28报道]]，在科索沃北部塞尔维亚族民众焚烧边境站导致1名警察死亡后，塞尔维亚警方和北约维和部队28日加强了边境两端的戒备，以防止其他暴力事件发生。

塞尔维亚警察局长接受采访时称：“我们将阻止极端分子从塞尔维亚进入科索沃地区，我们会对国际维和部队提供一切可能的帮助。”

对于暴力事件的发生，欧盟也向双方施压，敦促科索沃和塞尔维亚停止暴力并进行谈判。

科索沃警方27日宣布，特警撤离边境站，但边境税警仍将留驻，此举引发了当地塞族的不满，并演化为暴力事件，部分塞族民众与科索沃国际维和部队发生冲突。事件导致1名警察死亡。

以色列总统首次发表言论：叙利亚总统阿萨德必须下台

【综合消息】据媒体报道，以色列总统27日召开新闻发布会说，以色列认为叙利亚总统阿萨德必须下台。据报道，叙利亚近几个月来反政府示威频发，西方要求叙利亚总统阿萨德“不改革就下台”的局势，让阿萨德压力重重。以色列政府此前对叙利亚局势一直没有置评。27日，以色列总统佩雷斯在新闻发布会上表明立场，称阿萨德下令让军队杀害平民示威者，并下令抓捕示威活动中的数万人，因此必须下台。佩雷斯说，“他离开的越早，对(叙利亚)人民越好”。

他认为，叙利亚政权更迭有利于该国与以色列最终达成和平协定。这是以色列总统首次对叙利亚局势发表官方言论。报道指，作为总统，佩雷斯在很多场合发表与政治有关的言论时需要格外谨慎，此次他公开评价叙利亚局势的举动并不常见。佩雷斯发表此番言论是在以总理内塔尼亚胡之后，内塔尼亚胡近日接受阿拉伯电视台(Al-ArabiyaTV)采访时的措施更为外交化。他说，叙利亚的年轻人应该获得一个更好的未来，但这些应该由叙利亚人民来决定。

【时事点评】众所周知，自“美国利益决策层”基于“美国资本利益”、策动了“埃及之乱”之后，在我们的讨论中，“利比亚之乱”被定性为：将是“方方面面”基于各自利益、进行种种“排列与组合”的一个“观察点”，而“叙利亚之乱”则被视作“国际社会”之“中东共同利益”的“止损点”。值得强调的两点是：

第一，这个所谓的“国际社会”，指的是：在“以色列袭击土耳其救援船队”的“处理进程”中形成的、以“中欧俄”为主、包括阿拉伯联盟、土耳其、伊朗、叙利亚等有意充当“中东地方王”的国家与组织之“集合”。

第二，判断叙利亚这个“止损点”是否被“有效击穿”、从而“触发”上述“国际社会”中的“大多数”、基于各自的中东利益、执行相应“止损动作”的判断标准，则在于叙利亚政府“<<是否有被推翻的危险>>”。

*** 很容易发现新闻中最有价值的文字在于下面几段原文

显然，在上述层面去阅读这两则新闻，我们也就很容易发现：新闻中最有价值的文字、在于下面几段原文：

第一段：塞尔维亚警察局长接受采访时称：“我们将阻止极端分子从塞尔维亚进入科索沃地区，我们会对国际维和部队提供一切可能的帮助。”

第二段：对于暴力事件的发生，欧盟也向双方施压，敦促科索沃和塞尔维亚停止暴力并进行谈判。

第三段：以色列总统佩雷斯说，“他（叙利亚总统阿萨德）离开的越早，对(叙利亚)人民越好”。

第四段：他认为，叙利亚政权更迭有利于该国与以色列最终达成和平协定。

*** 急于加入欧盟的塞尔维亚、甚至还明显表现出一种“惟恐科索沃大乱”的奇怪心态

针对“第一段”，我们想强调的是，在塞尔维亚不惜交出诸多的所谓“<<战犯>>”（实则是对欧盟签“投名状”），甚至“公开放弃”武力阻止科索沃独立（实则是对欧盟承诺“科索沃独立”的“后续发展”将是个“和平进程”），从而意图换取“尽早加入欧盟”之“门票”的背景下，塞尔维亚早已“即”没有动机、也没有能力插手科索沃了，不仅如此，仍然在为“加入欧盟”而“竭尽全力”的塞尔维亚、一段时间以来，甚至还明显表现出一种“惟恐科索沃大乱”的奇怪心态。

*** “本质”上而言，“极端分子”显然是“被”“从塞尔维亚进入科索沃地区”了

因此，在东方评论员看来，从“本质”上而言，“极端分子”显然是“被”“从塞尔维亚进入科索沃地区”了。也正因如此，在塞尔维亚警察局长所说的“我们将阻止极端分子从塞尔维亚进入科索沃地区，我们会对国际维和部队提供一切可能的帮助”的背后，其实是基于上述“奇怪心态”、在向“北约”之“欧盟维和部队”承诺“提供一切可能的帮助”，并在“北约”之美国面前、坚决划清与“已经进入、特别是今后可能大批进入科索沃”之“极端分子”的关系。

*** 为何只有欧盟在“高调”出面、却找不到美国人的“坚定立场”？

如果我们在这个层面去观察“第二段”文字，也就不难明白：针对“科索沃北部塞尔维亚族民众焚烧边境站导致1名警察死亡”，为何只有欧盟在“高调”出面、并“敦促科索沃和塞尔维亚停止暴力并进行谈判”、却找不到美国人的“坚定立场”？事实上，在之前的点评中，我们已经多次强调一个观点，即：站在欧盟的角度，就“埃及之乱”的“后续发展”而言，其最大的危险的于：如果“美国利益”最终无法以“第三种方式（通过巴基斯坦之乱、特别是印度之乱）”进行“南亚破局”的话，或者以“执行‘南亚破局’”的“最逼真式努力”迫使中国做出实质性让步，继而接受“G2”模式、帮助美国（美元）彻底瓦解欧盟（欧元）的话，就可能寻求以“另一种方式”去“求生”，也就是从“利比亚之乱”为支点，对欧盟（欧元）进行“跨海（地中海）一击”[fn:dfttdzknb01]。

*** 再谈“没有必要战略资源作支撑的战略意图，是注定不可能实现的”

显然，类似于美国旨在“南亚破局”的“种种努力（包括将“埃及之乱”导向“印度之乱”的努力）”，对中国而言，即是一种实实在在的“攻击准备”、也是一种虚虚实实的、明显抱有“收获之心”的“警告与威胁，“美国利益”有意从“利比亚之乱”为支点，对欧盟（欧元）进行“跨海（地中海）一击”的“种种努力”，对欧盟而言，也即是一种实实在在的“攻击准备”、同时还是一种虚虚实实的“警告与威胁”。

毫无疑问，针对欧盟的这份“虚虚实实”的“警告与威胁”、美国利益集团也明显抱有一份“收获之心”，即：既期望在“攻击准备”的层面上有实实在在的进展，更期望通过这种“虚虚实实”的“警告与威胁”，或在政治、特别是军事层面上，或在经济、特别是金融层面上，在“中欧”身上各有侧重，最终分别实现“不战而屈人之兵”的“战略意图”。

其实，早在奥巴马政府上台之初、接连抛出“倾听说”与“巧实力”的时候，我们就曾经强调：<<任何战略意图都需要相应的战略资源作支撑，否则，对绝对实力与相对实力都已实质性下降的美国而言，没有必要战略资源作支撑的战略意图，是注定不可能实现的。>>

时至今日，期间一系列的“排列与组合”，特别是<<美国虽精心策划了骇人听闻的“天安号事件”、但最终却“收获”了一艘“以色列袭击的土耳其救援船”>>，这整个过程就已充分地证明了“上述结论”。

*** “没有足够战略资源作支撑”的美国、想以“连横”去破解“合纵”，“必然支付”的“第一笔战略代价”！

至于以“此”为标志，中国强行介入中东、并在欧盟与俄罗斯的策应下将“大国间战略利益主要交易平台”从自己的“重中之重”——南亚方向，推向“欧美”之“重中之重”的科索沃方向的“中东和平进程”这个“点”上，从而令“一切问题都可与美国在中东谈”的“游戏模式”风靡一时，“中欧俄”一时间更是在“伊核之战略协调”下找到了一条“彼此搭台（依次上阵）、共同唱戏（谋利）”的“盈利模式”，而这，更是“美国没有足够战略资源作支撑”、却偏想凭所谓“巧实力”、以“<<连横（中美G2、欧美修补关系、美俄关系重启）>>”之“术”去破“<<合纵（中欧俄战略协调）>>”之“道”、所“必然支付”的“第一笔战略代价”！

*** “没有足够战略资源作支撑”的美国“必然支付”的“第二笔战略代价”！

美国为之“必然支付”的“第二笔战略代价”，就是在施展出“天安舰沉没”这一手段之后，虽然一时间阻止了“中欧”的战略靠近，但是，首先由于欧盟（欧元）看清楚中国力拒“G2”的立场坚定、并明白其中的利害关系（合纵连横的历史教训），其次由于<<欧美国家利益之间矛盾>>[fn:dfttdzknb02]的“不可调和性”，再次由于<<欧美资本利益之间矛盾>>[fn:dfttdzknb03]的“很难调和性”，始终不肯向美国提供实质性南亚配合，终令关乎中国全球利益的“南亚破局”始终未见实质性进展、但关乎“美元本位制”基石的“中东破局”、却因中国循着“东亚、南亚等一切问题都与美在中东谈”、而强行介入中东、最终进入了“不可逆转的进程”。

*** “没有足够战略资源作支撑”的美国为之“支付（注：这关非‘必然支付’）”的“第三笔战略代价”

在东方评论员看来，美国为之“支付（注：这关非‘必然支付’）”的“第三笔战略代价”,就是企图以“以攻为守”的反击上述“游戏模式”、结果却进一步“加快了中东破局进程”。

<<“埃及之乱”的实质>>，在于“美国利益决策层”基于“美国资本利益”的层面，最终以损害“美国国家利益”的方式、针对“一切重大问题都可与美国在中东谈”的、且只要美国被迫参与其中、就必然受损的“大国在中东进行战略利益交换的游戏模式”，决定拿“埃及之乱”作为手段、对其进行的一场“以攻为守”式的反击，不仅如此，在反击之余，其企图心还在于将北非、甚至整个非洲大陆“先”行“<<苏丹>>化”、“再”行“<<索马里>>化”，最后再将“欧亚海上运输线”进行“<<亚丁湾>>化”。

在此基础上，瞄着“南亚方向”，着眼于“暗渡陈仓层面的南亚破局”，如果中国仍然不妥协，则或将“欧亚海上运输线之乱”打造成“中国海上运输线之乱”，从而全面恶化中国“外在的国家安全环境”、通过拉高中国经济的“进出口成本”，全面推高中国经济的通货膨胀水平，不断倒逼中国货币政策“持续加息”、直到“率先进入不可逆加息周期”，为“欧美”最后联手启动“加息周期”、从而启动“世界经济通货紧缩周期”，最终将中国经济等南方经济体由“通胀”迅速送入“通缩”创造条件，继而为“西方已经、或者准备释放的天量流动性”届时或可以极低的成本、或者根本就“不计成本”，通过收购、兼并、直接挤跨等各种种手段、去“直接控制”中国等南方经济体的经济、特别是金融命脉打开“关键之门”。

*** 只要能打开这道“关键之门”，美元甚至可能就此取代全球各国的货币、最终成为正式的“地球货币”

不难看出，只要能打开这道“关键之门”，站在“美国利益”的角度，不仅美国债务危机将成为过去，“美元本位制”将得到空前的巩固、且美元甚至可能就此取代全球各国的货币、最终成为正式的“地球货币”。

也不难看出，我们之所以称“美国决策层”基于“美国资本利益”而策动“埃及之乱”是一种战略冒险，就在于“美国资本利益”企图拿“美国国家利益”在这个问题上赌上一把，赌赢了，则就可以“美元本位制”的“身份”直接打开“关键之门”；赌输了，则至少还有一次机会、即以“欧元本位制”、或者“其它本位制”的“身份”继续去“摸索”那道“关键之门”。

显然，我们之所以将“美国利益”支付的“第三笔战略代价”视之为“并非必然”，在于如下几点：

第一点，在于这是美国利益、准确地讲，是“目前代言西方资本的美国资本”的本性之所在——总是企图控制地球上任何经济体的命脉、特别是金融命脉，以占得支配性地位、获取超额利润，而欲全面达成此目的，“西方资本”在取得“支配地球”的地位后，甚至会采用一些“<<反人类手段>>”、去控制<<人类的构成>>；

*** 在欧元协同攻击中，让欧元与中国、俄罗斯等南方经济体的货币单位“一同湮灭”

第二点，在于这是“非美势力”，准确地讲，是“非美资本利益”、特别是“非美国家利益”尽力抵抗的一种局面。

也就是说，如果“非美资本利益”、特别是“非美国家利益”尽力抵抗，那么，这“第三笔战略代价”也就成了“美国利益”必然支付的，如果“非美资本利益（比如欧洲资本利益）”、特别是“非美国家利益（比如欧盟国家利益）”最终未能尽力抵抗，反而对美妥协，则对“美国利益”而言，这所谓的“第三笔战略代价”不仅不用支付，反而会因“以攻为守”的反击取得成功，迫使“欧盟”在政治与军事上回归“北约体系”、继续接受美国的领导，在经济、特别是金融上回归“美元本位制”，从而或主动放弃欧元，或让欧元在“协助”美元进行经济、特别是金融攻击中国等南方经济体的过程中，与中国、俄罗斯等南方经济体的货币单位“一同湮灭”。

*** 或者反过来，美国利益也期待着中国、俄罗斯等能“坐视”欧盟（欧元）瓦解

或者反过来，美国利益也期待着中国、俄罗斯等能“坐视”欧盟（欧元）瓦解，之后，美国利益就可彻底吸收“欧洲资本”、并借“美元本位制”的强大力量，将“北约”整合成一个完全听命于“美国利益”的“政治、军事、特别是经济组织（请注意这一变化）”，并将美日、美韩、美澳、美新军事同盟等“<<美国私有战略资产>>”一一注入其中，最终包围、肢解中国、与俄罗斯。

*** “美国利益”的“收获之心”仍然在于两点，更在于将“上述两点”做成一个“良性循环”

第三点，也是最重要的一点，即在“第二点”的基础上，我们不难看出，“美国利益”的“收获之心”仍然在于两点：

其一，通过“威、逼、利、诱”的种种手段，有效调和“欧美资本利益之间很难调和的矛盾”，从而让“欧美资本利益之间很难调和的矛盾”在有效调和之后，去主导“欧美国家利益之间不可调和的矛盾”，继而“有效缓和”后者，最终弱化“欧美间的<<三边撕裂>>”、同时强化欧美为代表的“北方”与中俄等为代表的“南方”之间的“<<南北撕裂>>”，这样，“美国资本”就可“借”欧洲资本与“欧美”国家机器之“合力”、在“西方必须主导世界”的旗帜下，去打开那道“关键之门”。

其二，借“其一”的可能性，去威胁中国，迫使中国最终接受G2，“一方面”可令美国自急待深化的债务危机中迅速逃生（我们曾经论证过，G2是美国从债务危机中逃生的、最为简洁且高效的一条路），并反手攻击欧盟（欧元），另一方面，也可利用“一方面”去强化“其一”。

然而，在策动“埃及之乱”从而在中东方向“以攻为守”的背后，“美国利益”的“收获之心”即在于拿到“上述两点”中的任何一点就可满足，更在于将“上述两点”做成一个“自我反馈”的“良性循环”才可确保拿到“上述两点”中的任何一点。

*** 通过上述内容，我们就不难看出这样几个问题的要义之所在

通过上述内容，我们就不难看出这样几个问题的要义之所在：

第一个问题：为何“美国利益决策层”会“基于”美国资本利益、却“有损于”美国国家利益的层面去策动“埃及之乱”？

第二个问题，为何我们要始终强调：美国策动“埃及之乱”表面看也像是个“测试”，但这种“测试”却暗藏有极强的攻击性，且一旦令其“测试”顺利展开，则在“测试结果”拿到之时，也就等同于“攻击凑效”之时，不仅如此，如果在这个时候中国等再去组织反击，就已经来不及了。

第三个问题，为何我们一再强调：站在中国的角度上，一定不能让这种“测试”顺利展开、必要时，一定要果断地予以截击。

*** “截击”的主要原理

而“截击”的主要原理，就是以一切手段“加速”中东破局、或以“任何其它方式”直击“美元本位制”的命门、或者其它的“攻之必救、否则美国全球战略即刻瓦解”的战略要点。

*** 具体的截击方式

至于具体的截击方式，可以是与“国际社会”一道，以“直接废掉”美国主导的<<中东安全框架>>为目标的、强行打通“国际社会”进出加沙地带的“第三条通道”；也可以是与“非西方势力”一道，以直接废掉“西方资本”主导的世界既有的政治、经济（特别是金融）、军事秩序为目标的，对“中东进行最暴力破局”；

当然，在东方评论员看来，还可以是“其它可取得类似攻击效果”的截击方式。比如，将已经由“中国重中之重”的“南亚方向”推至“均远离中欧俄的重中之重”、却“积聚了美国大量核心利益”之中东方向的“大国间主要战略交易平台”，进一步推至“欧美”共同的重中之重——科索沃方向，与俄罗斯等“南方势力”一道，动用一切政治、经济、特别是军事手段，“循”着令“欧美国家利益间不可调和的矛盾”去主导“欧美资本利益间很难调和的矛盾”之原理，促成“欧美利益”在“<<三边框架>>”内的“彻底撕裂”，从而极大地加快“伊核问题最终解决方案（就是<<确定全球新秩序、特别是全球金融新秩序>>）”的“定稿进程”。

*** 补充几个细节

在这里，我们想补充几个细节：

其一，在动用一切政治手段的层面上，要注意伺机在美国后院的方向、启动南美的政治资源、并适时“加注”军事资源；

*** 充分运用好手中的美元资产、特别是“期限不一的美国国债”，令美国搞“<<美债技术性违约>>”难受，不搞更难受；

其二，在动用一切经济手段的层面上，要注意瞄准美国利益内部矛盾、与欧美利益之间的矛盾，伺机启动手中掌握的金融资源；

这中间，就包括充分运用好手中的美元资产、特别是“期限不一的美国国债”，令美国搞“美债技术性违约”难受，不搞更难受；也包括动用人民币汇率手段、伺机带领东亚货币对美元、或欧元大幅度贬值的方式。

*** 瞄准“美国利益”在全球各个热点的“军事部署（注意，包括韩国）”，最大限度的消耗对方

其三，在动用一切军事手段的层面上，要注意瞄准“美国利益”在全球各个热点的“军事部署（注意，包括韩国）”，伺机动用一切可用的方法、调动一切可以调动的资源，去最大限度的消耗对方。

这中间，如果美国在巴基斯坦“继续加力”的话，如果美国与岛内显独、隐独势力（马英九政权）合谋，决定放出陈水扁、搞“部分台独”、以牵制中国的战略资源的话。

*** 最大限度地“鼓励”欧盟（欧元）下决心向“欧盟彻底整合的目标”进行“冲刺”
在东方评论员看来，在这些“可以考虑的手段”中，就包括让驻阿美军的直升机成批的往下掉，也包括朝鲜对韩国岸上目标今天打一枪、明天打一炮，从而将美国部署在东亚、中亚的战略资源也“死死地拖住”，甚至还包括以各种方式、支持南美国家或用政治、经济手段，或用军事手段进一步清除南美的亲美势力，从而将“热点”插进美国的后院、并“点火’、让其“冒烟”，以最大限度地“鼓励”欧盟（欧元）下决心快速解决“科索沃独立后续发展”、并下决心向“欧盟彻底整合的目标”进行“冲刺”。
*** 中国完全可能向欧盟提供“科索沃配合”，俄罗斯“完全有可能”向欧盟提供“科索沃理解”
显然，一旦欧盟决心“冲刺”，那么，在其“冲刺”过程中，欧美间的“三边撕裂”极可能空前激化，一旦如此，不论“欧美”最终谁掌控科索沃问题的主导权（注：这就是“后话”了，相对而言，这不是我们最关心的），则在其它战略方向，中国与俄罗斯“可供收获”的地方那可就“太多了”。
在东方评论员看来，考虑到这一点，在“科索沃问题”上与欧盟没有直接利害冲突的中国，完全可能向欧盟提供“科索沃配合”，而与欧盟有直接利害冲突的俄罗斯，也“完全有可能”在欧盟“冲刺”的过程中，向欧盟提供“科索沃理解”。只要“整体收益”划算就行。
值得强调的是，就是在上述“各种可能”之下，美国以“埃及之乱”为标志，在中东方向进行的“以攻为守”式“反击”，始终没有得到其盟友（欧盟）的实质性配合，结果，不仅未能逆转“中东破局进程”，反而因在埃及、巴林、利比亚、叙利亚、特别是“巴基斯坦（打死本拉登）”等“节点”上、因各种势力的各自抗击与干扰，接连出现“脱稿运行”，其结果也就是“加快了中东破局进程”。

*** 这一所谓的“加快”，“绝非巧合地”集中体现在两个问题上
而这一所谓的“加快”，对比上述所谓的“截击”手段，也就“绝非巧合地”集中体现在两个问题上：
其一，是在最近的一个时间段内，由于叙利亚这个“止损点”受压较大，“数艘”不同国籍的、航线不一、救援物资不同，但目标地却高度统一的“国际救援船”、纷纷涌向加沙。
显然，在“美国利益”不停地向“叙利亚”这个“止损点”施加压力、以测试“国际社会”的“具体反应”的同时，“国际社会”也在用一只接一只的“国际救援船”予以“警告”。
毫无疑问，在这种“测试”与“警告”的背后，一方面是缺少“欧盟实质性支持”的“美国利益”并不敢独自一举击穿“叙利亚”这个“止损点”，另一方面，是仍然守住了“止损点”的“国际社会”中的“大多数”，也无意主动出击。
而在“中俄”等无意主动出击的背后，是期望在守住叙利亚这个“止损点”的基础上，以利比亚这个“观察点”为支点、以继续“观察”，观察什么？在东方评论员看来，首先就是观察“欧美的利比亚政策”在久拖之下、在“三边撕裂”的进一步拉扯之下，是否出现“公开的决裂”。
*** 一旦如此，则“埃及之乱”的后续发展就可能有“两个简单走向”
而一旦如此，在东方评论员看来，则“埃及之乱”的后续发展就可能有两个简单走向：
第一个走向，就是欧盟“回归”上述“国际社会”，从而可以令“国际社会”彻底打通“经埃及通往加沙”的、由“欧美共同控制”的“第二条通道”，从而以最简洁的方式、直接废掉“美国以以色列为安全支点、以沙特阿拉伯为金融支点的中东安全框架”。
第二个走向，就是美国经“利比亚”这个点、对欧盟进行跨海（地中海）一击，手段之一就是直接引爆“欧洲债务危机”，或者，将“科索沃独立后续阶段”直接推进“暴力处理进程”、从而间接引爆“欧洲债务危机”。
如果在这个层面去观察突然爆发的“科索沃北部塞尔维亚族民众焚烧边境站”一事、特别是欧盟“高调”发声，而却不见美国人的“坚决态度”，也就再符合“科索沃逻辑”不过的了。
同样，只有在这个层面去观察这一连串变化，即：近段，北约（欧盟）又开始轰炸卡扎菲势力，而利比亚反对派则称“卡扎菲留在国内的机会已经过时”、“利比亚反对派军事领导人”突然被杀，等等，我们才会明白：在“国际社会”手握“强硬反击方案”暂时守住“止损点”的背景下，在利比亚这个“观察点”上，久拖之下的“欧美利比亚政策”，在“三边撕裂”的进一步拉扯（欧美债务危机）之下，终于出现了我们期望的观察结果，即：“欧美利益”之间已经出现“公开决裂”的“征兆”！
但值得强调的是，“征兆”就是“征兆”，它并不等于“正式决裂”。
*** 在伊朗捅了“马蜂窝”之后，中国立刻与之伊朗签定数十亿美元的商业合同以示“支持”
其二，是在最近一段时间内，“伊核计划”明显取得进展，除了伊朗宣布“加快铀浓缩进度（也就是“核子弹”的问题）”之外，伊朗还在中程弹道导弹层面（也就是“枪”的问题）取得进一步进展，甚至开了一家“意在捅一捅马蜂窝”的“石油期货交易所”。
不仅如此，俄罗斯、特别是中国对伊朗的支持力度明显加强，特别是中国，在伊朗用“石油期货交易所”捅了“石油美元结算制”、特别是“美国资本的国际大宗商品定价权”这个“马蜂窝”之后，中国立刻与之伊朗签定数十亿美元的商业合同，并打算与伊朗进行旨在绕开“欧美对伊经济制裁”的“易货贸易”、以示“支持”的态度。
*** “欧美国家利益间不可调和的矛盾”仍在主导“欧美资本利益间很难调和的矛盾”
有必要指出的是，法国（欧盟）却在这个问题上表现出明显的“骑墙态度”：一方面，法国严厉谴责“伊朗加快铀浓缩进度”的动作、称其为“是对联合国相关决议案的挑衅”，但另一方面，却又并未在对“封锁、孤立伊朗”至关重要的叙利亚问题上、对美国提供进一步的实质支持，比如、加大对叙利亚的制裁力度。
在东方评论员看来，这至少说明一点，即：自“埃及之乱”以来，尽管国际局势历经了一系列的、核心利益间的排列与组合，但在“三边撕裂”的框架内，“欧美国家利益间不可调和的矛盾”仍在主导“欧美资本利益间很难调和的矛盾”、从而令“欧美资本利益之间的很难调和矛盾”、在“西方资本”的框架内仍然“难以有效调和”。
而结合上面的讨论，我们认为，“这”恰恰是“欧美利益”之间“公开决裂”的基础，也就是说，只要“欧美资本利益之间的很难调和矛盾”在“西方资本”的框架内“难以有效调和”，那么，“欧美利比亚政策”之间“公开决裂”的“征兆”就有可能发展为“正式决裂”。
而一旦如此，也就为“中俄”、及土耳其等“中东地方王”利用“欧美”之间愈演愈烈的“三边撕裂”，在“埃及之乱”的“后续发展”中，在共同维护“国际社会”之“中东共同利益”的基础上，遂行自己的战略计划、收获各自的战略利益提供了战略空间。
而为了尽早促成“欧美利比亚政策”的“公开决裂”，我们的建议是：在与俄罗斯充分协调的基础上，一方面，“有条件地”增大对“欧盟科索沃政策”的支持力度，另一方面，在“欧美利比亚政策”上、继续维持目前这种“继续与卡扎菲与反对派均保持接触，但又不承认反对派是唯一合法代表”的“原则”且“又灵活”的立场下，总体偏向于欧盟、有利于利比亚反对派的态度。从而迫使“美国利比亚政策”在“天时（中东破局进程在继续）”与“地利（较欧盟而言，在处理利比亚问题上，美国根本不占地理优势）”与“人和（国际社会中的大多数都有中东破局的愿望）”等因素“均不利”的巨大压力下，不得不主动与“欧盟叙利亚政策”“提前决裂”或者“痛苦妥协”。
至于“痛苦妥协”的“标志形式”，就是美国“痛苦地默认”欧盟快速地吸收塞尔维亚等南欧国家入盟，继而眼睁睁地看着欧盟“借债务危机”之“危”，迅速“夺取”统一财权、军权、直到外交口径之“机”。
就目前而言，尽管“美国资本利益”选择对欧“痛苦妥协”的可能性并不算大，但，就一些显而易见的问题，我们仍然认为有必要提前讨论一二。
毫无疑问，在美国选择“痛苦妥协”的情况下，一个“迅速完成全面整合”的欧盟，无疑会是“西方资本”的又一个“运行载体”，而基于“西方资本”一定要主导国际秩序的“本性”，如何在“欧盟迅速完成全面整合”之前，借“美国国家利益”对“西方资本”的“反弹”，迅速完成“对东亚经济”的全面整合、或者强化“南南合作”，则是中国与诸多南方“政治经济体”需要“提前考虑”的问题。
而作为“两者之中”最为可能的“欧美提前决裂”，则主要是“欧美国家利益”之间的“提前决裂”、并以“决裂”之后的“后续发展”，去“强行”引导、或者迫使“很难调和的欧美.资本利益矛盾”尽可能地向着“有利于美国国家利益（对美国而言）”、或者“有利于欧盟国家利益（对欧盟而言）”的方向、进行“有效调和”，也就是迫使“欧美资本”最终选择“流向”。
*** 埃及国内再次出现动乱将不令人意外
而在东方评论员看来，这种“提前决裂”的“最可能的形式”，站在欧盟的角度上，则可以是寻求中国与俄罗斯的支持、通过“中俄”取得非盟的理解，迫使卡扎菲同意下台、并与反对派和谈，继而，一方面尽可能地稳住利比亚局势，另一方面，将“埃及之乱”的“后续发展”导向第一个简单走向，即：欧盟“回归”上述“国际社会”，令“国际社会”彻底打通“经埃及通往加沙”的、由“欧美共同控制”的“第二条通道”，从而以最简洁的方式、直接废掉“美国以以色列为安全支点、以沙特阿拉伯为金融支点的中东安全框架”。
如果在这个层面去观察埃及的动向，那么，埃及国内再次出现动乱将不令人意外。
最后，欧盟就在上述“两个方面”的掩护下，尽快将塞尔维亚、科索沃等南欧国家（或地区）纳入欧盟、从而“努力地”彻底解决科索沃问题，即：“借债务危机”之“危”，迅速“夺取”统一的财权、军权、直到外交口径之“机”。
*** 站在美国的角度，这种“提前决裂”的“最可能的形式”是第二个简单走向
而站在美国的角度，这种“提前决裂”的“最可能的形式”，则是将“埃及之乱”的“后续发展”导向第二个简单走向，即：再次搅乱利比亚局势，从而在“科索沃问题（欧元问题）”上，趁机对欧盟进行跨海（地中海）一击，手段就是，或直接引爆“欧洲债务危机”，或将“科索沃独立后续阶段”直接推进“暴力处理进程”、从而间接引爆“欧洲债务危机”。

*** “违约”的“双簧戏”，在“技术”上，是可以实现直接、或间接引爆“欧洲债务危机”之“目的”的
值得警惕的是，尽管美国最终必然提高债务上限，但美国国内仍在玩的一场“违约”的“双簧戏”，在“技术”上，“一定时间段”内的“暂时违约”是可以实现直接、或间接引爆“欧洲债务危机”之“目的”的。
然而，根据我们的观察，“美国利益集团”要想“可控地”玩好这出“双簧戏”，并“定向”引爆“欧洲债务危机”，而自己又最大限度地回避实质性冲击，就必须在“技术性违约”之后的“最短时间内”、尽可能“回收”美国国债。
*** 在如何令美国“搞美债技术性违约”难受、不搞更难受的问题上，可以这样理解
因此，在如何令美国“搞美债技术性违约”难受、不搞更难受的问题上，可以这样理解，即：
1）：在之前的点评中，我们多次强调，作为美国的最大债权国（注，是债权国，不是最大的债权群体），在欧美债务危机急待深化的大背景下，在“人民币国际化”这只陀螺顺利起旋之前，中国原则上，就是不抛手中的美国债券，但要在期限、品种上，视国际经济、特别是金融形势不断调整，在规模上、原则上是只增不减，即便是“减”、也只是微幅调整。
*** 警惕美国想用还在不断贬值的美元”“回收”中国及其它债仅国手中的美国债券
总之一句话，在可见的阶段内，都要“令”美国“无法”用“可无限调用、且不用付利息、并还在不断贬值的美元”、去顺利“回收”中国及其它债仅国手中的“付息美国债券”。
2）：值得强调的是，在“现行金融游戏”中，一般情况下，“美元现金”还是可以买到相应的美国债券，但是，要警惕在“未来的金融游戏”中，美国通过“限购令”的手段，或在债券拍卖的程序上做手脚，令中国等手中的、“零利率的美元现金”无法拿到的“有利息的美国国债”。
事实上，早在两年之前，针对中国手中日益增多的美国国债，美国已经在国债拍卖程序上做了些“旨在限制中国增持美国国债、特别是长期国债”的“小试验”。
*** 在关键时刻，“美元现金”很可能无法“质问”美国市场资金利率、特别是对美国金融影响巨大的长期利率
3）：在“2”的层面去观察问题，那么，就不难明白：如果中国等债权国因惧怕“违约”、从而匆匆忙忙地将美国国债换成美元现金、或者其它资产，那么，在关键时刻，“美元现金”很可能无法“质问”美国市场资金利率、特别是对美国金融影响巨大的长期利率，因为，“直接形成”美国市场利率的美国国债，特别是长期国债，都已被美国金融管理当局用“零利率的美元”提前“收回”。
*** 一旦美国国债“正式违约”，我们很想知道的第一问题是
4）：到期“承付利息”的美国国债、即是美国国家信用、美元信用的保证，更是“华尔街金融永动机”的“核心生产资料”，显然，一旦美国国债“正式违约”，我们很想知道的第一问题是：美国经济、特别是美国军事霸权“赖以融资”的“华尔街金融永动机”还怎么运转？
*** 一旦美国国债“正式违约”，我们很想知道的第二个问题是
另外，我们很想知道的第二个问题是，作为美国国债的最大持有群体（中国手中的债权与之相比是小巫见大巫），“美国国内庞大的债权人群”是否接受“违约”的事实？如果不接受，美国社会是否可以保持稳定？如果接受“不付息”，最起码，又可回到第一个问题，即，以美国国债为“核心生产资料”的，以利率与汇率为两个轮子的“华尔街金融永动机”、又该怎么运转？
*** 一旦美国国债“正式违约”，我们很想知道的第三个问题是
我们很想知道的第二个问题是，由美国政府信用“背书”，以“美国税收”作担保的、需付息的美国国债一旦“违约”，那么，“美元”这种不需付息（美元目前是零利率）、且没有“任何偿付担保”的“记账符号”，是否还会有人愿意使用并持有的最大持有群体
*** “同时、稳妥解决这两个问题”的“可行性方案”，应该由“外星人”去提供才是！
坦率地讲，在现有国际经济运行规则下，是现有美国社会道德标准下，特别是，在“美国人的确很富”、富得拥有“几百万亿美元”的、以美国国债为“核心材料”的“纸上富贵”的情况下，“同时、稳妥解决这三个问题”的“可行性方案”，已经超出了我们的智慧水平，应该由“外星人”去提供才是！
*** 有必要指出的是，美国排名前几的“债权国”，恰恰都集中在东亚
5）：在东方评论员看来，基于上述几点，或者在“外星人”给出可行性方案之前，站在美国决策层的角度，如果不能用“违约”、特别是所谓“技术性违约”这些无耻手段、持续引导舆论、继而或“诱导”、或“迫使”中国等债权国“错误地吐出”美国国债、转持零利率“美元”或者其它危险得多的“美元资产”，比如美国股票，那么，这笔庞大的“美国债权”就可以成为人民币在必要时（注，如：欧美联手经济、特别是金融攻击中国）、带领东亚货币、或针对美元、或针对欧元进行大幅贬值，一方面，可成为冲击欧美市场利率、重置欧美经济运行成本、激化欧美“三边撕裂”的“关键工具”；再一方面，则可极大威胁准备从中国“抽逃”的各种热钱，简单地说，必要时，人民币针对某种货币的突然大幅贬值，将极大地呑蚀“这些热钱”在中国市场赚取的利润。
在这个问题上，有必要指出的是，美国排名前几的“债权国”，恰恰都集中在东亚。而它们手握的巨额美国债券（注，并非美元现金），又恰恰为其货币“可能的大幅贬值”提供了“可能”。
*** 令中国在这种问题上处理错误，则将成为美国顺利回收“付息之美债”的“关键”
而以国家为单位，由于中国是美债最大持有者，且地处东亚，是东亚经济的核心，因此，中国处置手中美债的动向，无疑会形成“头羊效应”，如何令中国在这种问题上处理错误，则将成为美国顺利回收“付息之美债”的“关键”。
*** 大幅贬值后的人民币等东亚货币、反而有机会成为世界“最具吸引力”的货币品种
值得强调的是，一旦东亚货币在人民币的带领下大幅贬值后，由于中国经济（东亚经济）依然不可替代，突然大幅贬值的货币就可“顺势”进入“不可动摇的升值进程”、再配合中国（东亚经济体）强大的制造能力，如果中国能为东亚经济提供足够的军事支撑（这一点至关重要），那么，就可令大幅贬值后的人民币等东亚货币、反而有机会成为世界“最具吸引力”的货币品种。
如果在这个层面去观察问题，那么，在美国一边“自打耳光”地邀请朝鲜副外相赴美“商谈实质性问题”、一边又在“南海国际化问题”上“偃旗息鼓”，一边却拿“对台售武”作话题、与中国谈什么“台湾问题”的背后，则是用“三独框架”呼喊欧盟“回家”不成的华盛顿、在关乎“美元本位制”稳固与否的“科索沃问题”与“中东和平问题”上、其核心利益有可能被欧盟“带头”冲击的危险下，欲用“对台军售问题”去换取中国在“科索沃问题”的“旁观”。
值得强调的是，由于目前仍然是“排列与组合”阶段，因此，这种“换取”除具有强烈的“科索沃之需”之外，也仍然有着强烈的、旨在构建上述“良性循环”的动机。
*** 就目前局势，相对中国的全球战略而言，“台湾问题”已经太小了
对此，我们的建议是：就目前而局势，相对中国的全球战略而言，“台湾问题”已经太小了，即便美国承诺、并兑现令“台湾回归”，眼下这种“极其复杂、极其多变”的国际局势也没有足够的时间与空间让中国去消化“台湾回归”，如果没有时间与空间消化，“口头”上的“回归”又有何意义？更何况一个“无足轻重的对台军售问题”？
*** 以“不可逆转的实际行动”承认中国的“南海核心利益”，这是最起码的！
因此，在东方评论员看来，如果美国果真有“十分的诚意”、愿以相当程度的战略代价去换取中国的“旁观”，那么，以“不可逆转的实际行动”承认中国的“南海核心利益”，这是最起码的！
我们注意到，日前，中国国防部首次宣布：中国首艘由“废旧品”改造的用于训练与科研的航空母舰就要建成，显然，在“此”之后，更多、更好的国产航空母舰离下水还会远吗？而在中国航空母舰入役之后（不论是改造的、还是纯国产的），距离中国完全控制“具锦州效应”之“中国南海”、以至东海的日子还会远吗？不论“别人”愿意与否！也不论它是世界头号军事强国、还是区域军事小霸。
因此，我们也就听到刚刚访华归国的美国参联主席马伦就说：美国无意离开“南中国海”。在东方评论员看来，作为美国海军的高级将领，马伦是“听懂了”“科研航母”的意思！知道中国全球海上军事投送能力到来的那天已经很近了！
对此，我们的观感就是：既然“听懂了”还“仍然无意离开‘南中国海’”，那中美之间在中东、科索沃问题上又有什么好谈的？

因此，并不令人意外的是，27日，在科索沃与塞尔维亚交界处的一个边境站遭火烧的同时，中国驻联合国代表在联合国开始高调批评以色列，称“定居点”问题是巴以和平主要障碍，且称：中国对任何有利于巴以和平的建议、方案持开放态度。
显然，在东方评论员看来，这里面应该包含“巴勒斯坦单方面建国”的方案,而一旦中国在联合国公开支持巴勒斯坦单方面建国，则意味着中国同时向“巴以和平问题”与“科索沃问题”注入“同一个冲击性变量”。而这也势必全面牵动南亚、北非局势。
有意思的是，就是在这种背景下，美国的中东钢钉——以色列，其总统首次公开发声：要求叙利亚总统下台！从而摆出一副准备击穿“止损点”的强硬姿态！
对此，我们对以色列有一句劝告：那种“要求叙利亚总统下台”说一次就算了！即不要常说，更不能去“实践”。因为，所谓“止损点”是针对“国际社会”的“中东共同利益“而言的，对以色列而言，该“止损点”一旦“有效击穿”、以色列核心利益必然受到极大损失、且毫无“止损”可言！极可能是“一损千里”、直至崩溃！
从以色列接连对伊朗、叙利亚发出“与其力量不相称的强硬声音”就不难看出，在美国仍然在准备“第三种方式”进行南亚破局、且仍然无意承认中国南海核心利益、也就是“无意兑现”美国自己提出的“中美共管西西太平洋”的情况下，中国的“科索沃态度”就是两个：
第一个是：“旁观”不可能！
第二个是：“静候”美国以国债“违约”、去引爆“欧洲债务危机”、去对欧元“跨海一击”好了！如果果真选择”另一种方式“逃生的话！如果“美国决策层”果真有胆量将这个“违约游戏”玩真、玩实、玩到底的话！那么，在中国历史上早就有“实物本位制”的案例下，在中国与伊朗之间已经准备进行“易货贸易”的情况下，“美元本位制”、特别是“美国的中东安全框架”在一夜之间轰然倒地、也绝不是不可能的事情！
*** 要做好国内安全层面的各项工作
最后，由于国际形势已经进入极其复杂与险恶的层面，因此，基于历史的经验与某些势力具有的“反人类性质”，就目前而言，建议有关部门要做好国内安全层面的各项工作，除了粮食安全、卫生安全、金融安全（网络安全）等“显见”的安全问题之外，再比如，要动用一切手段、切实保护好位于青藏高原的、具有“中华水塔”之称的“三江源头地区”、及中国主要河流，并做好相关处理预案（特别是三防预案）。还比如，做好大型水利枢杻、高压输变电线路、铁路沿线的安全保卫工作及相关处理预案。
就723动车重大事故而言，其教训是深刻的，对此，我们认为：一要彻底调查事故原因，要从设备因素与人为因素两个层面“分头”去究查。
我们想强调的是，在“人为因素”中，除了调度、监测等管理层面等“显见原因”之外，某些从国外进口的核心设备中，是否有自己没有彻底弄清楚的安全隐患、或者是安全陷阱（比如，是否有功能不详、或者“容错不足”的程序代码）？对这些要客观地公布调查结果，如果有，则要及时做好替换工作。
另外，列车事故过程中，沿路控制、信号系统是否正常？如果不正常，是自然原因还是技术原因、更或者是人为、甚至人为破坏的原因？等，对这些也要客观地公布调查结果，如果有，除了及时做好替换工作外，也要做好安全预防工作。
*** 借机抛“铁路私有化”的意图值得警惕！
当然，在我们看来，通过引进、消化、再创新而形成的中国高铁技术，是中国产业升级的“路子之一”，已经对中国经济、以至世界政治、经济、军事格局产生、且还将产生重大影响，其战略意义不容质疑，某些媒体借机抛出“铁路私有化”的话题更是值得警惕！“这些声音”要的不仅仅是“铁路私有化”，而是包括金融、电信、能源、矿产、流通在内的、中国所有战略行业的私有化，因为，“西方资本”已经放出、且还准备放出的“天量货币”，其“真实的意图”、或者“最终用途”、恰恰就是控制这些“中国战略行业”，以最终控制包括中国在内的所有南方经济的经济命脉！
但是，在引进、消化的过程中，是否仍然有某些个环节在“彻底消化”的层面上没有做好、或者没有坚持（比如某些引进的核心组件之程序代码是否彻底经过“排查”，是否与自己的技术100%的兼容）？这些都是值得深究与总结的。

*** 此次重大事故的最重要教训应该有四个
因此，在我们看来，此次重大事故的最重要教训应该有四个：
一，是在事故之后的处理过程中，许多处理环节明显“不合理”也“不合情”，相关部门与社会的“沟通”有问题，从而有必要从源头进行彻底检讨；
二，是类似高铁这种战略交通工具，其各个环节的技术（特别是软件技术）均要“彻底掌握”在自己的手中才行，就“引进”而言，在“消化”的层面上，要做到“重新开发”的程度，特别是“硬件”中的“软件”。
三，也是最重要的，要举一反三，要同时在严重依赖国外产品的民用航空系统建立起类似的“究查体系”，或者预防措施。
在这个问题上，从根本上讲，还是要立足于“独立自主、自力更生”，加快发展中国自己的商用、军用大飞机项目，才是彻底解决此类安全问题的根本方法。
值得强调的是，就“正在发展的大飞机项目”而言，由于“中国大飞机”对欧美的民用飞机产业的冲击度较“高铁”来得更大、更直接（中国高铁对欧美飞机产业的潜在打击是很大的），因此，如果有某些部件、或者技术确有必要引进，那么，就一定要做到“彻底消化”才是，否则，宁可不用！宁可自己开发！即便“成本”不合算也要坚持做到这一点！
四，对以电力为动力的高铁、产品完全依赖国外产品的民航等战略运输，平时要做好“战备”，即，要考虑“战时”电力供应中断、大飞机关键零部件供应中断、或者“人为的突发故障”等可能性。
因此，建议在继续发展高铁的同时，要从战备的角度，保留、并运行足够的内燃机（油动力、特别是煤动力的）为主的“铁路运行线路”，并尽可能“均匀分布”，以便随时可以“顶上去”、并“跨线”调度。


* Footnotes

[fn:dfttdzknb01] 击毙欧元对美元有何好处?

[fn:dfttdzknb02] 欧美国家利益之间的矛盾?

[fn:dfttdzknb03] 欧美资本利益之间的矛盾?
