# -*- org -*-

# Time-stamp: <2011-08-23 14:38:28 Tuesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 《东方时代环球时事解读.时事节简版》 星期五 11年08月19日


[2011-08-23 08:31:57]

　　致各位用户：

　　1：在我们多次声明之后，仍然有一些用户在非法转贴《东方时代环球时事解读.时事节简版》。对这种严重侵犯广大付费用户正当权益的行为，我们表示谴责。

　　2：经过核实，公司已经对一批在网站、论坛、媒体上非法转贴《东方时代环球时事解读.时事节简版》的用户、暂时停止提供后续服务。

　　3：希望各位用户自觉维护自己的权益。同时，也欢迎大家积极提供线索，协助我们做好维权工作。

　　4：对非法在网站、论坛、媒体上转载《东方时代环球时事解读.时事节简版》的个人、网站、论坛、媒体，一经核实，将取消后续服务，此外，我们还会将其ip列入黑名单，不再允许在本网站注册。

　　

哥伦比亚与阿根廷两国总统呼吁：联手应对金融震荡

【布宜诺斯艾利斯消息】据媒体报道，阿根廷总统克里斯蒂娜和来访的哥伦比亚总统桑托斯18日呼吁拉美国家加强团结，共同应对全球金融市场的剧烈震荡。

这是哥伦比亚总统近10年来首次对阿根廷进行正式访问，标志着两国关系的升温。如何应对全球金融市场的新一轮剧烈震荡成为两国领导人讨论的重点议题。

桑托斯指出，拉美国家目前面临的不仅仅是国际金融市场的动荡，而且是世界经济和金融领域的“飓风”，拉美国家绝不能等闲视之。

他说，面对国际金融市场的新一轮震荡，如果拉美国家各自应对挑战，显得势单力薄，但如果团结起来共同应对，加强政策协调，那就具备了相当的实力，而且可以把此次危机转化为拉美国家的发展机遇。

桑托斯同时呼吁身为二十国集团成员的阿根廷、巴西和墨西哥能够统一立场，在二十国集团的会议上代表拉美国家发声。

克里斯蒂娜则在发言中强调，随着美国和欧盟经济增长放缓以及金融市场剧烈震荡，拉美国家未雨绸缪加强合作显得非常必要。她说，为了鼓励拉美企业的经营和生产，应该建立进口替代机制，使得拉美国家市场上销售的制成品基本由本地区的工厂生产。与此同时，拉美国家应该充分利用丰富的自然资源，通过工业加工提高产品的附加值，放弃出口原材料或低端产品的发展模式。

【时事点评】之所以选择这则新闻素材作为本期“焦点点评”的“切入点”，仍然在于一种“ *高度的紧迫感* ”，即阿根廷总统克里斯蒂娜8月4日所发出的：拉美国家做好充分准备，防止发达国家将金融危机的严重后果转嫁给包括拉美地区在内的新兴市场国家。

●有必要“超越”阿根廷总统所处的“地理范围”--拉美，向“方方面面”发出如下呼吁

显然，在我们看来，随着“局势的最新发展（这一点，稍后再行总结）”，特别是，随着“美国资本”所代言的“西方资本”仍然拒绝放下其“必须主导全球”的“本性”，在此完全有必要“超越”阿根廷总统所处的“地理范围”--拉美，以阿根廷总统克里斯蒂的口吻，向“方方面面”发出如下呼吁：

第一，所有“南方经济体”要做好充分准备，防止发达国家将金融危机的严重后果转嫁给包括拉美地区、非洲、东亚、特别是南亚在内的新兴市场国家。

事实上，需要警惕的并不仅仅限于新兴市场国家。

如果在大国层面去讨论问题，则包括有中国、俄罗斯、印度与巴西等；

而在东亚层面上，包括美国所谓的盟友--韩国，甚至还包括美国的另一个盟友-- *饱受“三边撕裂”之痛、却又幻想坐收“南北撕裂”之利，还幻想借机摆脱美国控制的日本* 。

第二，在“第一”的基础上，作为进一步的呼吁，全球的所有“非美利益”都要做好充分准备，防止目前仍由“美国资本”所代言的“西方资本利益”将金融危机的严重后果转嫁给包括“全球几乎所有国家与地区”、包括欧盟。

●“美国国家利益”如果决意继续为这种危机转嫁提供“全平台的支持”，则要做好充分的心理准备

第三，在第一与第二的基础上，还要提醒 *“西方资本”的主要运行平台--“美国国家利益”* ，如果决意继续为这种危机转嫁提供“全平台的支持”，则要做好充分的心理准备，承受一种极其可能的结局，即：一旦“西方资本利益”转嫁金融危机的过程“最终脱稿”，则“该平台”极其可能将承受、甚至是“独自承受”惨重的代价----较另一个超级大国--前苏联的“崩溃”还要猛烈得多、甚至是血腥得多的“崩溃过程”

●“这种关联”在美国历史上就曾经频频上演

值得强调的事实之一就是，在这个问题上，在某种意义上讲，同样依附在“美元本位制”之上的英国，之前因一黑人青年被杀所“意外”爆发的“大规模骚乱”，就已经预示了“这一极其可能性”。

值得强调的事实之二就是，“这种关联（ *经济问题种族化* 、 *或政治问题种族化* ）”在美国历史上就曾经频频上演，显然，如果不是“美国利益”用“美元本位制”的霸权、连续搞了两波“量化宽松”，从而勉强支撑着那本被“新会计准则”所掩盖的“美国金融烂账”，令“美国经济”还在“勉强地稳定运行”着，令“美国民众” 的生活水平“并没有受到实质性冲击”，恐怕“英国式骚乱“、甚至”埃及式之乱”早就在美国发生了。

●“英镑”无法向美元那样“ *赊* ”到足够的“生产、特别是生活物资”以“维持经济勉强的稳定运行”

值得强调的事实之三，也是至关重要的一点就是：基于“第二点”、基于“美元本位制”对美国经济的特殊作用，可以这样说，曾经的世界霸主、今天同样陷入欧美金融危机中的英国（英镑），这次 *之所以会发生“英国骚乱”* ，即在于英国经济规模相对较小、更在于英国的政治、特别是军事力量相对较弱，当然，归根结底，在于 “英镑”无法向美元那样一边“量化宽松”，一边还能利用、或者耗费手中的“相应战略资源”，与其它经济体，特别从“以中国为首的南方经济体”的手中，或 “交换”、或.“购买”、更加贴切地讲、是“赊（请注意这个词）”到足够的“生产、特别是生活资料”，以“维持美国经济勉强的稳定运行”。

●对“美国利益”而言，尽一切手段维持“华尔街金融永动机”的“勉强稳定运行”是如此地重要

值得强调的事实之四是，也是最为核心的两点就是：

第一点：所谓“维持美国经济勉强的稳定运行”，本质上就是维持那部“华尔街金融永动机”的“勉强稳定运行”。

而对“美国利益”而言，这部已经被“铁的事实（先是次贷危机、后是欧美金融危机）”证明为“根本不可能永动”的“华尔街金融永动机”，尽一切手段维持其“勉强稳定运行”是如此地重要，因为， *它事实上担负着为美国民众的生活开支、美国社会医疗养老支付、美国军费开支等诸多“核心项目”进行融资的“融资功能”。*

第二点，在“第一点”的基础上，即然这部被“诸多”诺贝尔经济学奖获得者、在“现代金融工程”理论的包装下，历经数十年，基于期间或发明、或创造的一系列 “金融交易模型”，最终“精心构建”的金融永动机、已经被证明“无法永动”，那么，一个非常自然的结论就是： *这就是一部基于“庞式骗局”之本质的“金融老虎机”。*

●“庞氏骗局”的典型特征

至于什么是“庞氏骗局”？我们无意去详细讨论其历史渊源（“庞氏骗局”源自于一个名叫查尔斯-庞齐（Charles Ponzi，1878-1949）的意大利人之美国行骗史），在这里，只就其“后来发展”给出它的几个基本特征：

首先，最高明的庞式骗局一般是一种“设计得非常 *复杂* ”的投资计划，复杂到普通人、甚至专业机构“会因为根本无法搞清楚、但只要有钱可赚、也就干脆不想搞清楚、或者无所谓能否搞清楚”的程度，总之，最高明的“庞式骗局”的投资诀窍，总是让“人”觉得“不可知和不可复制性”。

值得强调的是，这个所谓的“人”，即包括对金融投资一窍不通的普通人士，也包括拥有丰富专业知识的专业人士与机构。

真实的情况就是，美国华尔街传奇人物、纳斯达克股票市场公司前董事会主席 *伯纳德•麦道夫* 于08年因涉嫌一场金额近500亿美元的“庞式骗局”而遭警方逮捕之后，最令众人“瞠目结舌”的是，许多鼎鼎有名的各行各业的名人、金融投资专业人士、甚至是实力雄厚的跨国投资机构（比如：英国汇丰银行、法国巴黎银行、德国曼恩集团、日本野村证券、苏格兰皇家银行等跨国金融巨头），都是它的“正式、且稳定的客户”。

●不论是最高明的、还是最拙劣的庞式骗局，都具有“ *拆东墙补西墙* ”的共同特性

其次，不论是最高明的、还是最拙劣的庞式骗局，都具有“拆东墙补西墙”的共同特性，也就是利用“新投资者”的钱、去向“老投资者”支付投资利润甚至本金，从而总可以在“游戏结束之前”以一种“近乎不可思议”的方式维持着“稳定的赚钱效应”，并借此从更多的新投资者那里骗取投资、吸取现金流。

●麦道夫将这种“古老且又简单”的“庞式骗局”玩到了何等地步？

真实的情况就是，在麦道夫的“庞式骗局”中，它之所以能让许多“听着庞式骗局长大的”专业人士、甚至“拿庞式骗局当典型反面案例培训员工”的投资机构上当，就在于麦道夫的公司“能有每个月1%的固定回报”，特别是在长达二十年的时间里，不论是熊市还是牛市，它的确“持续且精确地”做到了这一点。

再加上麦道夫头顶上的、在华尔街长年累积的、神一般的光环，最终令“这份投资”成为许多投资者与投资机构、或为了赚取稳定利润、或旨在有效平衡投资风险、而进行资产配置的“标准配置”，并在相当长的一段时间内,“把钱投资给麦道夫的公司竟然成为了某种身份的象征”。

不难看出，麦道夫将这种“古老且又简单”的“庞式骗局”玩到了何等地步？

●可以肯定的是，华尔街上还有更大的骗子！

事实上，几十年的“道行”，让“麦道夫”成了“美国金融界”的另一尊神话，而作为美国纳斯达克市场的缔造者之一，在美国次贷危机全面爆发、从而将美国金融界的另一尊神-- *格林斯潘* 拉下“神坛”之后，“麦道夫”在某种意义上就成了当时受到重创的美国社会、特别是美国华尔街的“最后一道心理防线”。

而随着这尊神像的轰然倒下，人们才终于明白：支撑神像的、仍然是古老的“庞式骗局”！只是这次的主角，是迄今华尔街史上最大的骗子！可以肯定的是，华尔街上还有更大的骗子！

最后， *“麦道夫”的“庞式骗局”之所以能够长时间维持，根本原因在于“美国资本利益”在上世纪90年代迫使“美国国家利益”取消了“银行投资混业禁令”，且默许“美国资本”在资金运作上的“严重不透明”。* 显然，美国政府在监管上的放任自流，最终给了“行骗者”以极大的空间。

●“格鲁吉亚战争”美国反击俄罗斯遭遇惨败，之后，麦道夫资金链彻底断裂,整个真相才大白于天下

真实的情况是，以“麦道夫”事发前两年注册的一家对冲基金为例，有监管之责的美国证券交易委员会竟然从未审查过它的账目。

直到 *“格鲁吉亚战争”美国反击俄罗斯、但遭遇惨败，美国次发危机无法捂住，“欧美国金融危机”全面爆发* ,麦道夫的公司突然面临大规模赎回压力（仅欧洲方面一夜之间就有70亿美元要求赎回）,资金链彻底断裂,整个真相才大白于天下。

●麦道夫与华尔街之间是如此地“形似”而且“神似”

事实上，就“上述讨论内容”而言，如果将其中的主角--“麦道夫”与平台---“麦道夫对冲基金”分别置换成“美国资本”与“华尔街”，再结合美国次贷危机爆发的前前后后，特别是结合 *“美国雷曼兄弟公司的倒闭”触发的“欧美金融危机”* ，并回顾美国投资史上“多年前的”另一个重大事件--美国安然公司的重大期诈事件，我们也就不难看出，两者之间是如此地“形似”且“神似”，还不缺乏“历史的连贯性”。

显然，通过上面的讨论，我们的意图在于让大家明白这样几层事实：

●“华尔街金融永动机”就是个规模更加庞大、交易模型更加神秘的“麦道夫对冲基金”

第一层，华尔街原本就是N个“麦道夫”的集合，“华尔街金融永动机”就是一个规模更加庞大、品种更加丰富、交易模型更加神秘的“麦道夫对冲基金”。

第二层，“麦道夫”通过“只要你相信我，就会保证你每个月至少可赚取1%的利润”的“绝不透明”、维持着一场持续了数十年的“庞式骗局”；

●“华尔街金融永动机”到底是个什么玩意儿？

而  *“华尔街金融永动机”则靠着一大堆由“诺贝尔经济学奖”所“背书”的、号称为“自动对冲、稳赚不赔”的所谓“经济学原理、衍生交易规则”，外加一架架高性能计算机系统里运行的那些、“非方案制定者永远也搞不清楚、也看不明白的、甚至‘后面的方案修改者’还经常将‘最初方案制定者’都能弄糊涂”的所谓“数学模型”，一边将号称“天下第一安全”的美国国债、及“曾经与美国国债一样安全”的“两房次债”等作为“基础生产资料”，从计算机这一端输进去、再加上可操纵的“利率”与“汇率”、股指、大宗商品价格等诸多“金融材料”，就可从另一端“流出”所需的“成品”。*

显然，这个所谓的“产品”，既包括华尔街向全世界投资者“承诺的利润”、也包括“华尔街每年都有的丰厚花红（不论是牛市、还是熊市。而“旱涝保收”恰恰是“庞式骗局”的典型特征）”、还包括为“美国”这个“运行平台”赚取足够的“运行费用”、也就是为“上述核心项目”提供“所需融资”。

●“麦道夫”及“麦道夫对冲基金”的垮台，在于一个“必然之中的偶然因素”

第三层，也是最重要的一层。我们知道，“麦道夫”及“麦道夫对冲基金”的垮台，在于一个“必然之中的偶然因素”。

当时，在格鲁吉亚回合中，因为“欧洲利益”在最关键时刻的不配合，“美国资本”对俄罗斯“ *旨在攻击石油美元结算制”的“普京路线”* 的反击以惨败告终（详细内容见之前的相关讨论纪要），随着美国正式宣布“素有九尾猫之称的雷曼兄弟清盘”，“美国次贷危机”全面爆发、并迅速向“欧美金融危机”发展。

●有两个细节特别值得一提

而在“美国次贷危机”转向“欧美金融危机”的过程中，有两个细节特别值得一提：

第一个细节是：时任美国财政部长的保尔森通过公开声明“美国政府承诺对两房次债进行担保”，从而正式终结了“美国是否将为两房次债提供担保”的“争论”；

我们之所以再次提及第一个细节，在于：强调“美国两房次债”也好，“美国国债”也罢，它们都是“华尔街金融永动机”的“基础生产资料”，因此，除非“美国资本”找到了“新办法”去驱动这架“传说中的金融永动机”，或者“创造”某个“新理论”去替代“华尔街庞式骗局”，否则，指望着“这架永动机”能持续提供 “多项核心融资”的美国政府，是必然不敢让“美国两房次债”倒掉，这也正是我们在第一时间强调“有本事的话，美国政府就正式宣布拒绝担保两房次债”的原因！

同样的原理，在不久前美国国会围绕“美国国债上限”上演“双簧戏”时，这也是我们始终强调“在你美国正式决定拒绝调高美债上限、从而拒不偿付中国等债仅(权)国家的债务之前，根本就懒得理你”的原因之所在！


●欧洲资本利益、特别是欧洲国家利益，“更多地”是“华尔街庞式骗局”的“牺牲者”、而不是“食利者”

第二个细节是，在保尔森宣布“雷曼兄弟清盘”之前，一家德国银行还在雷曼公司的“一再催促下”、将一笔数十亿美元的巨额资金打到了雷曼兄弟的账上，其结果可想而知。

显然，如果美国政府在这个问题的“处理进程”中哪怕有一丝的透明、或者有一点点“监管者”的道德，那家德国银行至于落入这种陷阱吗？至于让那数十亿美元如同“肉包子打狗”一般“有去无回”吗？

而我们之所以重提“格鲁吉亚回合”的关键时刻所出现的“欧美公开分裂”，之所以重提上述“第二个细节”，在于强调：“欧美国家利益”之间、“欧美资本利益” 之间的矛盾重重，如果仅从金融博弈的层面去观察问题，那么，通过这个细节，外加美国政府选择雷曼兄弟公司进行“定向倒闭（该公司的主要客户是‘非美客户’、特别是欧洲方向的）”，我们也就不难明白：欧洲资本利益、特别是欧洲国家利益，“更多地（请注意我们的用词）”是“华尔街庞式骗局”的一个“牺牲者”、而不是“食利者”。

●为了维护这个“庞式金融游戏”，美国不得不向中国兜售“中美（G2）模式”

事实上，在“美国次贷危机”之后，也就是“华尔街金融永动机”显然已经被证明为“不可能永动”、从而也是个“庞式骗局”之后，为了维护这个“庞式金融游戏”，美国不得不向中国兜售“中美（G2）模式”。

无可争辩的是，在此之前，这个世界上不是没有“G2”，且“G2”的形式还多种多样，比如，冷战时期，在政治与军事层面，就有个“两极（两个超级大国）”外加“北约与华约”的“G2模式”，除此之外，在经济、特别是金融层面，不仅曾经有、且现在还仍然维持着的“欧美（G2）”模式。

显然， *在美国急于与中国玩“中美国（G2）”的背后，是“美国次贷危机”爆发，“美国利益”通过“定向倒闭雷曼兄弟”、将“美国金融危机”弄成一场“欧美金融危机”、并导致全球经济一次探底，从而“活生生地”让“事实中的G2（欧美）”与“极力兜售中的G2（中美）”、以及其它经济体（比如俄罗斯），分别在 “金融”与“制造”层面、共同为之埋单。*

也正因如此，来自“中欧、甚至俄罗斯”的“强烈反弹”是必然的，而在这种反弹下，“华尔街金融永动机”这局看似高级得多（有诺贝尔经济学奖作“背书”、有“诸多诺贝尔经济学奖获得者”亲自参与、还有“美国这个国家”作为运作平台）”的“金融骗局”，也开始真正面临着“资金链断裂”的危险。

●“华尔街金融永动机”看似“高级”，但仍摆脱不了当年“庞氏”发明这种骗局时就“内嵌”的主要特征

显然，尽管“华尔街金融永动机”看似“高级”，但它仍摆脱不了当年“庞氏”发明这种骗局时就“内嵌”的主要特征，既： *“骗局”要想“持续产生足够”的“利润”、以吸引“后续资金”，就必须借助于“拆东墙补西墙”的手段。*

●“华尔街金融永动机”所面临的“资金链断裂”问题，与“麦道夫对冲基金”既有共同点也有不同点

在这里，由于“华尔街金融永动机”这局看似高级得多的“庞式骗局”借助了“美国国家”这个运行平台，再加上前面已经说了，“华尔街金融永动机”这边“需要投入”的“核心生产资料”包括有美国国债、两房次级债等政府与公司“有价债券”，外加“利率”与“汇率”、股指、大宗商品价格等诸多“金融材料”，而那边指望可以产出的、除了“更多的美元（华尔街的花红）”之外，还有维护“美国”这个“运行平台”稳定运行所必需“生产与生活资料”、特别是“美国军事力量”的 “庞大军费开支”，不仅如此，还必须“提留”出“足够的利润”、或者“利润前景”、以继续吸引、或骗取“后续资金”的持续流入，以供其不停地“拆东墙补西墙”。

因此，在“本质”上讲，“华尔街金融永动机”所面临的“资金链断裂”问题，与“麦道夫对冲基金”所遭遇的“资金链断裂”的问题，是既有共同点也有不同点。

●“麦道夫”的问题，就是个“钱”的问题！是个“钱”就能解决的问题！

首先，两者之间的“不同点”在于：

在 “麦道夫对冲基金”所遭遇的“资金链断裂”问题上，其实也就是个“美元多少”的问题，简而言之，如果麦道夫当时还能及时骗到一笔“70亿美元”的“现金流”，那么，“麦道夫”断不可能就此垮台；也就是说， *“麦道夫”的问题，就是个“钱”的问题！是个“钱”就能解决的问题！而在很大程度上，“钱”能解决的问题就都算不上什么问题！*

这一点，对“华尔街金融永动机”而言，尤其如此！

●“华尔街金融永动机”所面临的“资金链断裂”问题，绝不仅仅是个“钱”的问题

因为在“华尔街金融永动机”所面临的“资金链断裂”问题，除了也有个“美元多少”的问题外，更主要的，是个维持“华尔街金融永动机”稳定运行所需的“诸要素能否维持”的问题。

换句话说，“华尔街金融永动机”所面临的“资金链断裂”问题，绝不仅仅是个“美元多少”的问题。

在这个问题上，最贴切的说法就是：“钱”能解决的问题都不是问题！但“华尔街金融永动机”却的确遇到了问题！

否则，有“无限美元”可以调用的美国联储，早就用“美元”将次贷危机抹平了！何以至今天这种地步？

●两者之间的“共同点”在于：都是个信心问题

其次，两者之间的“共同点”在于：“麦道夫”的问题，虽说就是个“钱”的问题，但导致“麦道夫”不仅无法继续吸引足够现金流以供其“拆东墙补西墙”、且还遭遇“大量渎回”的，就是个“信心问题”。

显然，美国管理层通过对雷曼公司的“定向倒闭”、从而将欧盟也一把拖进“欧美金融危机”之后，“麦道夫对冲基金”的“欧洲客户”或基于对未来经济信心不足、或基于自己也需要“拆东墙补西墙”，从而“突然集中要求渎回”，又恰巧摧毁了“麦道夫对冲基金”、从而“鬼使神差”摧毁了“美国华尔街另一尊神像”。

可以肯定的是，“华尔街金融永动机”将来能否继续吸引“足够的资金流”、以维持其稳定运行，首先就在于一个“信心问题”。

*就中国而言，“华尔街金融永动机”想从中国这里拿到的“资金流”主要有两个* ：

第一个，是“实实在在的生活与生产资料”。

由于中国是东亚经济、甚至南方实体经济的代表，因此，作为“北方虚似经济”的代表，美国经济能否“相对低成本”地得到生活与生产资料，“中国商品”的输出方向，是关键性的。

第二个，如果“美国经济”能拿到“第一个”，特别是从中国手中拿到“第一个”，那么，这也就意味着会转化成中国手中的“美国国债、或其它美元资产的增加额”。

而在主权国家中，由于中国手中握有最大规模（1.3万亿美元）的美国国债，因此，中国的态度至关重要。

●中国已经开始冲着“华尔街金融永动机”的“命门”指指点点了

在这种事实下，这种“增加额”既可能被华尔街用作维持其“庞式骗局”的“现金流”，如果中国政府表示“对美元资产有信心”的话；但也可能被视为一种“大规模的渎回”、至少是“准备大规模渎回”的信号， *如果中国政府“每天都没完没了的担心”的话；特别是，一旦中国正式表示“对美元资产彻底没有信心、并“有事无事”地不停嘀咕“除非美国对中国以‘可信任的方案’切实保证‘没有问题’，否则中国随时准备调整手中‘在美资产’的规模与品种”的话！*

如果在这个层面去观察中国国家领导人在会见美国副总统拜登时、“不厌其烦”地轮番关切“中国在美资产安全问题”，也就不难明白： *中国已经开始冲着“华尔街金融永动机”的“命门”指指点点了* 。

而从美国副总统拜登也不得不一次又一次、在不同场合“反复解释”“美国保证中国在美资产安全”、根本就“没功夫”关切南海问题、甚至忘记了“要中国解释航空母舰用途”的“尴尬”来看，那种被别人“点中命门”的感觉的确难受！

显然， *中国手中的美国国债及其它美元有价证券、都是“华尔街金融永动机”的核心生产要素，中国所期望的“保值”、甚至“升值”，“本质”上，对美国而言，就等同于“麦道夫”的“每个月有1%”的“回报承诺”，*

如果中国时刻都在担心“手中的美元资产不仅不能升值”、甚至还要“亏本”，从而“终于有一天不再愿意”继续“维持原有规模的投入”、从而正式带领东亚经济、甚至南方经济“或主动、或被动地缩减”对美国的“实物产品的出口”，或大幅提高“美国从中国、东亚经济、甚至南方经济获取实物产品”的“成本”，而一旦 “华尔街金融永动机”无法“有效弥补”这一“断裂的资金链”，那么，“华尔街金融永动机”的“稳定运行”就会立刻“出问题”。

●就欧盟而言，“华尔街金融永动机”想从欧盟这里拿到的“资金流”主要有两个

*就欧盟而言，“华尔街金融永动机”想从欧盟这里拿到的“资金流”主要有两个* ：

第一个，是“欧洲国家利益”基于“南北撕裂”的框架，与美国一道、对中国进行遏制，这表现在经济上，就是与“欧美”共同对华构建贸易壁垒，从而令“中国商品”在“流向”上没有更多的选择！

第二个，是“欧洲资本利益”基于“西方资本必须主导世界”的“欧美共同利益”，继续维护“美国资本”的“西方资本代言人”的地位，从而继续维护“现有国际金融游戏规则”，也就是“欧美资本利益”共同维护“华尔街金融永动机”的稳定运行。

然而，“美国利益”想从欧盟这里拿到这两个层面的“资金流”又谈何容易？

前面已经说了，“欧美国家利益”之间、“欧美资本利益”之间的矛盾重重，欧洲资本利益、特别是欧洲国家利益，“更多地（请注意我们的用词）”是“华尔街庞式骗局”的一个“牺牲者”、而不是“食利者”。

●只要中国与欧盟能团结一致，就可以立马掀翻华尔街这条“四处漏水的破船”！

因此，在这个问题，我们认为，如果欧盟利益不想继续被牺牲，那么，欧盟的选择或许将集中表现在“欧洲资本利益”最终是否站在“欧洲国家利益”的层面上，是否在“信用评级”的问题上，或与中国公司合作，从承认中国大公国际等评级结果开始，慢慢建立一套“ *非美国际评级体系* ”，或者干脆“另起炉灶”、建立欧洲自己的评级体系！

显然，一旦如此，将是对“华尔街金融永动机”的毁灭性打击！因为，这将意味着“非美势力”将慢慢退出“华尔街金融游戏”，而一个“参与者持续减少”、且“游戏中沉淀的死筹过多”的“金融游戏平台”，其下场注定与“麦多夫对冲基金”一样！甚至更加惨淡！

通过上面的讨论，其实我们已经不难看出，即便仅从金融层面去观察问题，只要中国与欧盟能团结一致，就可以立马掀翻华尔街这条“四处漏水的破船”！

事实上，我们已经注意到，最近一段时间来，欧盟内部一边放出“是时候建立欧洲自己的评级体系”的风声，一边又开始客观评价中国大公评级公司的“相关评级报告”。

在东方评论员看来，这是一个值得注意的苗头！

●对中国而言，“努力促成中欧团结一致”只能是个“手段”、而不能当成目标

然而，我们也必须清醒，如果仅在“中欧美”的层面上考虑问题，那么，对中国而言，“努力促成中欧团结一致”只能是个“手段”、而不能当成目标，“真正的目标”仍然是“用这个手段去 *促进“欧美”之间的“越走越远”，从而“尽可能地”促成“华尔街金融永动机”尽早面临一个“欧洲方向资金链断裂”的问题* ，

而对“美国利益”而言，尤其可怕的是，或者还等不到真正“出问题”之前，基于“上述可能性”而提前产生、积聚的“强大市场预期”，就足以令“华尔街庞式骗局”提前面对“有别于令麦多夫对冲基金倒台”的“资金链断裂问题”。

我们再次强调，对承担了“美国利益太多融资任务”的“华尔街金融永动机”而言，所谓的“资金链断裂问题”，绝不是个单纯的“美元多少”的问题，即：它不是个“钱”能解决的问题。

●华尔街的另一尊已经倒下的神--格林斯潘老先生，不久前又重出江胡、继续“行骗”了

东方评论员注意到，曾被美国国务聊希拉里在庙堂上公开斥责为“骗子”的华尔街的另一尊已经倒下的神--格林斯潘老先生，不久前又重出江胡、继续“行骗”了，他说：美国有能力偿债，因为美国可以印美元！

然而，基于上面的讨论，我们也就不难明白，一旦“华尔街金融永动机”的、源于中国、或者欧盟之中任何一条“资金链断裂（再次强调：这不仅仅是个“美元多少” 的问题）”，而剩下的一家只需取“旁观态度”、且不说“落井下石”的话， *华尔街基于“美元本位制”而攫取的“无限印钞能力”* 将立刻被废，因为，“市场预期”将强烈地预期到：美国国内基于“华尔街金融永动机”的“永动原理（说白了，就是 *建立在‘风险对冲’基础上的‘套汇套利’* ）”而堆积的“数百万亿美元” 的“金融衍生品”将“灰飞烟灭”！美国民众“数十万亿美元”的私人财富也将在一场更大规模的“麦多夫对冲基金”的垮台中、瞬间“堙灭”！在此基础上，更加强烈的市场预期自然就是： *美利坚合众国将在美国社会的暴乱中被彻底撕裂！*

●这，恰恰是我们非常警惕一种可能性的原因

值得强调的是，在美国次贷危机、特别是欧美金融危机全面爆发后近三年的时间里，“美国利益决策层”在消除上述“市场预期”的层面上，除了拿一本“修订版会计准则”掩盖黑洞、延缓第二轮金融危机的爆发时间，通过手中的战略资源，从“中欧”那里或购买、或换取“资金流”、以维持“华尔街金融永动机”的“勉强稳定运行”之外，“毫无办法”可言。

因此，在东方评论员看来， *除非美国能将目前由欧盟、特别是由中国提供的“资金流”牢牢地抓在自己手里、而不是拿手中“日益贫乏的战略资源”去“换取”、或“购买”，才可能从根本上解决问题。*

而这，恰恰是我们非常警惕一种可能性的原因，即：“美国资本”极可能用“天量硬通货币”水淹“南方经济”，通过在“南方经济体”内、甚至全球制造金融危机的方式，掀起一场史前例的“大兼并、大收购”，从而 *“先”彻底掌控“南方经济”的经济命脉，“再”彻底收编“欧洲资本”，最后，则是在国家利益层面，彻底肢解中国、欧盟、俄罗斯。*

另外，有关如何水淹“南方经济”、从而“先”控制“中国之外的南方经济的经济、特别是金融命脉”，再利用这些“被控制的南方经济”去围剿“中国制造”，从而再控制中国经济、特别是金融命脉的“可能方案”，大家可以参阅之前的讨论纪要！

●所谓的“中美共管西太平洋”的“真正内涵”

通过上面的讨论，我们其实想强调的就是： *对“美国利益”而言，如果它仍然不实质性调整其“旨在支配全球的即定全球战略”，那么，除非它能拉着欧盟、顺利完成“水淹南方经济、直到彻底控制中国的经济、特别是金融命脉”的一整套计划，否则，除了大规模的战争，它已无路可走！*

而基于核大国之间的恐怖核平衡，发动“大规模战争”自然不是在求生，而是在找死！

因此，剩下来的其实就是一条可行之路，那就是实质性调整其“旨在支配全球的即定全球战略”，从而像十九世纪未、二十世纪初的英国（英镑）向美国（美元）慢慢让渡势力范围，并借助美国的力量、隔着大西洋、一边压制“其现实威胁（当时的法国）”，一边“尽可能长地”享受英国霸权的最后时光。

显然，在今天而言， *这也就是所谓的“中美共管西太平洋”的“真正内涵”* 。

然而，目前的情况是，在“哥伦比亚与阿根廷两国总统呼吁：联手应对金融震荡”的背后，在这两位总统强调“拉美国家目前面临的不仅仅是国际金融市场的动荡，而且是世界经济和金融领域的“飓风”，拉美国家绝不能等闲视之”的背后，是“美国利益决策者”仍然在将美国自己提出的“中美共管西太平洋”视为一种手段而非目的，也就是说， *“美国利益”仍然不打算“实质性调整”其“旨在支配全球的即定全球战略”，仍然在幻想着如何“策略地实现”水淹“南方经济”的方案、如何彻底控制中国的经济、特别是金融命脉，并彻底收编欧洲资本、最后“一劳永逸地”肢解“中欧俄”、最终实现华尔街金融永动机的“永动原理”。*

事实上，从标准普尔调降美国主权信用等级，从而引导美国股市、国际原油、及其它国际大宗商品的一轮暴跌之后，美国已经做好了“QE3（甚至QEN）的前期准备工作，也就是说， *如果没有意外，暴跌之后美国股市、国际原油、及其它国际大宗商品，将随着QE3（甚至QEN）的推出，启动一轮暴涨进程，从而一方面推高南方经济的通货膨胀率，打乱这些国家的经济、特别是金融布署；另一方面、则是进一步迫使包括中国在内的南方经济体被迫加息，直到“高企的利率”全面抑制南方经济的经济活力，从而为美元（甚至可能包括欧元）突然启动加息周期，用全球性紧缩将“活力”已经受到极大抑制的南方经济进一步“灭活”，为美元（甚至欧元）最后收购南方经济中这些“被灭活”的“制造业实体”、特别是“金融实体”，从而自我掌控“华尔街金融永动机”所需的“资金流”---“生产与生活资料”。*

●最近一段时来所发生的许多事情有个清晰的主线

如果我们从这个层面去观察问题，那么，最近一段时来所发生的许多事情，也就都有个清晰的主线，那就是：

第一，在中国已经准备面对“欧亚海上运输线之乱”、甚至“中东最暴力破局”的局面，从而开始筹划“中国经济最低内循环”之后，“美国利益”企图一方面通过 “利比亚让步”的“利诱”、另一方面通过警告“意大利将倒下”的“威逼”，去换取欧盟的“叙利亚配合”，从而摆出一副“下决心准备有效击穿”叙利亚这个 “止损点”的姿态；

第二，经过我们的观察，以美国目前的绝对实力与相对实力，以“中俄”的战略准备与能力，特别是欧盟伺机彻底解决科索沃问题的心机，“第一”对美国而言，极可能只是个佯动，否则，曾经将欧盟送进利比亚之乱长达数个月却不得要领的美国利益，自己就可能因叙利亚问题、而在因叙利亚这个止损点被击穿而引发的“巴以冲突”、或者另一次中东战争上“重蹈欧盟复辙”！并被“中欧俄”所“围观”、甚至“群殴”！

第三，一如我们之前多次强调，“美国利益”其实有两条逃生之路，一条是以利比亚为支点，对欧盟（欧元）进行跨海（地中海）一击；再就是，将“埃及之乱”导向巴基斯坦之乱、特别是印度之乱，从而以“第三种方式南亚破局”。

●有意思的是，美国副总统访华期间，中东、南亚、东亚等战略方向同时异动、且动得厉害！

有意思的是，就在这个时间点上，“原本”就是、直到现在仍然是“一群乌合之众”的、但显然“开始得到”“中俄”支持、且美国也不敢公开阻止的、亲欧洲的利比亚反对派武装、竟然一口气打到了卡扎菲的老巢--的黎波里。

同样是这个时间点，美国副总统正在访华，不仅如此，中东、南亚、东亚等战略方向同时异动、且动得厉害！

第一，以色列两辆公共巴士在以埃及边境受袭，而以色列安全官员说：“袭击的枪弹似乎是从埃及方向射过来的”。

另据消息称，以色列军队已经报复、并声称打死了袭击者，包括几名埃及士兵；

第二，巴勒斯坦继续寻求成为联合国会员3国，巴勒斯坦民族权力机构主席阿巴斯表示：“已有122个国家支持巴勒斯坦国加入联合国”。

在这个问题上，在之前的点评中，我们曾经明确指出：没有欧盟的支持，就目前而言，“中俄”是很难令巴勒斯坦是如此坚持“寻求成为联合国成员国”的；

第三，我们注意到，在此之前，也就是周三晚间，埃及与美国军方的消息称，埃及与美国取消了今年的联合军事演习，这项军事演习的名称为“明星-2011”。

显然，如果在”第二、及第三”的“联动”层面去观察问题，特别是，如果考虑到埃及通往加沙的“第二条通道”同时受到“欧美双方”的共同控制，不难看出，在这种综合背景下，以色列两辆公共巴士在“以埃边境”受袭，而以色列安全官员又称：“袭击的枪弹似乎是从埃及方向射过来的”，而基于我们之前的观点，就这个突然而来的“袭击事件”而言，无疑既显得“极其微妙”、又显得“极合逻辑”！

●这种说法似乎在降低“欧盟”的作用

第四，美国防部长帕内塔罕见地公开表示：“世界稳定需要靠中印等新兴力量”，并进一步解释说：“我们有日渐崛起的力量和国家，比如中国、印度和巴西，更不用说俄罗斯了。我们必须继续依靠他们为全球稳定发挥作用。我们面临资源有限的问题，现在正在紧缩预算。”

显然，这种说法似乎在可以降低“欧盟”的作用。

毫无疑问，“第四”是“第三”的逻辑使然！

●美国利益公开将“埃及之乱”导向“巴基斯坦、特别是印度之乱”的开始

第五，18日，巴基斯坦警方表示，截至当天5清晨，巴南部港口城市卡拉奇在过去24小时内发生的暴力事件已导致38人死亡。其中，一名巴人民党领导人17日晚在卡拉奇被刺杀。

第六，18日，针对美国声明称“印度应该允许安纳•哈扎尔等人进行示威,不应对示威设置任何障碍”。印度国会要求印度政府对这次为何一个“孤独”的社会活动家能引来如此大规模的支持进行调查。

　 　据报道，印度国大党发言人拉西特•阿尔维说,“自印度独立以来,美国从未支持过印度境内的任何运动,这是第一次。美国人说印度应该允许安纳•哈扎尔等人进行示威,不应对示威设置任何障碍。美国为什么会这样发表声明?我们需要考虑在这个试图动摇政府统治、破坏国家的活动幕后到底有着什么样的后台。我们需要严肃对待美国的声明。”

在我们看来， *“第五”、特别是“第六”，显然是美国利益公开将“埃及之乱”导向“巴基斯坦、特别是印度之乱”的开始。*

我们再次强调，要特别警惕“第三种方式南亚破局”。

第七：最新消息是，继美国稍早公开要求“叙利亚总统必须下台”之后，似乎在“第三”的“威胁下、“第四”的“逼迫”下，“第五”与“第六”的“引诱”下，英国、法国、德国也开始公开要求“叙利亚总统必须下台”；

第八，东方评论员注意到，正是在上述背景下，１８日，阿富汗东部一美军基地当天遭到炸弹爆炸袭击，直到目前，没有任何消息说明死伤情况。

*在我们看来，如果南亚方向承受的压力进一步加大，美军直升机成批往下掉的画面就一定会出面。我们认为，“成批”的画面一旦出现，将是“世界维护和平的力量”对“美帝国主义”的最后一次警告！*

而就历史经验而言，阿富汗可是个先后埋葬了“数个帝国（大英帝国、前苏联）”的“大国坟场”，特别是，不可一世的“前苏联红军”就是因“直升机成批往下掉”而掉下去的。

如果“有人”偏偏“想赌”自己“或是个例外”，那么，那就干脆一把抛出最后的筹码好了。

而10年的阿富汗战争已经、且还将继续证明，“美帝国”一点儿也不例外，因此，美国的国运也必将随着“直升机成批往下掉”而直线坠落！

第九：就在美副总统拜登“携带金融导弹（配合南亚破局）”访华期间，中国副总理李克强正在香港，也在布置“金融反导系统”。 *17日，中国公开表示：支持香港成为人民币离岸中心，并发行200亿元人民币债券，并一带公布了一连串“严重支持”香港金融稳定、特别是金融发展的“重大决定”。*

显然，中国决策层对“美国南亚政策”很可能率先金融攻击中国香港、甚至中国台湾保持着高度警惕！

●根本就不相信、或者不敢相信“美帝国”是个“例外”的大有“人”在！

第十：18日，横跨中日俄三国的日本海陆海联运航线通航仪式在日本新潟港举行；

在我们看来，这个仪式放在18日举行、就“日期”而言或是个巧合，但“这个仪式”本身却绝非巧合，这说明，根本就不相信（对中俄而言）、或者不敢相信（对日本而言）“美帝国”是个“例外”的，是大有“人”在！

第十一，正是在上述综合背景下，东方评论员“并不意外地”注意到，18日，继美国率先要求“叙利亚总必须下台”、并宣布制裁叙利亚的石油、金融等核心行业之后，英国、法国、德国政府也开始“附议”“叙利亚总必须下台”的“美国提议”，但在更加重要的“全面制裁问题”上，还是有所保留。

不仅如此，在印度“反政府示威”的问题上，也就是“南亚破局”的问题上，欧盟总体上仍然保持着低调。

●这到底是美国“已经拉”欧盟“下了水”呢？还是欧盟正琢磨着“如何一脚”将美国给彻底踢下水、且不再有机会爬起来呢？

这样， 如果从上述综合情况来看，在叙利亚这个“水深难测”的“止损点”上，欧盟公开加入“叙利亚总必须下台”这一步，这到底是美国“已经拉”欧盟“下了水” 呢？还是欧盟正琢磨着“如何一脚”将美国给彻底踢下水、且不再有机会爬起来呢？在东方评论员看来，就“结果”而言，恐怕还得走一步看一步！但 *欧盟琢磨“如何一脚”将美国给彻底踢下水的可能性要大得多！*

●显然，美国人的确“吃不准”欧盟对QE3的真实意图！

第十二，最新消息是，北京时间8月18日晚间消息，两名美联储理事称，美联储在未来两年时间里将基准利率维持在接近于零的承诺可能会带来有关该行旨在提振股市的误解，也就是发出一个“利多股市”的信号，这是他们反对这一措辞的原因所在.

而结合德国眼下拼命反对发行欧元债券的做法（注： *反对不是目的，只是手段，德国想的是借此整合欧盟的统一财权、从而令欧元取得与美元分庭抗礼的“财政保证”* ），再在“第十一”的层面去观察这一重大消息，不难明白：显然，美国人的确“吃不准”欧盟对“美国QE3”的真实态度！

●除非美国在最短的时间内，以“不可逆转的实际行动”承认“中国的南海核心利益”

如果在这个层面去观察越南与菲律宾的“示弱”，去观察美国对朝鲜的“示好”、去观察“横跨中日俄三国的日本海陆海联运航线通航仪式在日本新潟港举行”，也就不难看出，“吃不准”欧盟“最终态度”的美国决策者，也在给欧盟“喂药”，既然欧盟仍然没有“南亚配合”、从而“合欧美资本”之力、或从“印度之乱”入手、通过经济、特别是金融攻击南亚，从而掀起一轮对“南方经济”进行史无前例的“大兼并”的意思，那么，“美国利益”就可能选择另一条逃生之路，那就是尽可能寻求中国的“旁观”，从而以“利比亚”为支点，对欧盟（欧元）进行跨海（地中海）一击。

但从利比亚反对派迅速攻到“的黎波里”的情况来看，从美国要求乌克兰立刻释放那位美女前总理之后，俄罗斯已经正式要求“卡扎菲必须下台”的情况来看，“中俄”已经加大对“欧盟利比亚政策” 的支持力度，也就是说，美国在这个时候想寻求中国“旁观”，除非美国在最短的时间内，以“不可逆转的实际行动”承认“具锦州效应”的“中国的南海核心利益”，从而“兑现”“中美共管西太平洋”的提议，否则 ，根本就不可能！

而由于形势已经可能激变，因此，在“承认”与“兑现”之前，那种“美国准备放宽对华高技术出口”的“老话”，听听还是可以的，因为中国也希望利用这一点去“挤”“欧盟的东北亚政策”，但中国肯定不会“往心里去”！

至于那份性质原本就为“左手制造问题、右手解决问题”的所谓“台湾军售案”，那位“暗独”的台湾领导人马英九不是配合演双簧演得非常投入吗？那就请美国人与他去玩好了！在这个问题上，我们已经说过，由于形势已变，台湾问题已经太小，更何况一个“美国特意制造出来的对台军售问题”？

●美国决策层会在“两条生路”的问题上加快抉择

*就目前而言，美国的利比亚政策已经基本失败* ，这样，由于“利比亚筹码”已经对欧盟暂时失去了效力，因此，它不仅在击穿叙利亚这个止损点的问题上会更加谨慎，以免在中东落入与“中欧俄”、甚至阿拉伯联盟等“全面为敌”的处境，但由于时间不等人，美国决策层会在“两条生路”的问题上加快抉择，因此， *站在中国的角度看问题，即要高度警惕“第三种方式南亚破局”、也要警惕“西方资本”水淹南方经济、从而掀起一轮、最终旨在控制中国经济、特别是金融命脉的、史无前例的、对“南方经济”进行的“大兼并”。*

对此， *作为金融层面的应对措施之一，中国要更加频繁地、冲着“华尔街金融永动机”的“命门”进行“指指点点”。而作为政治与军事层面的准备，中国要与俄罗斯、土耳其、叙利亚、伊朗、埃及等中东地方王密切沟通，为“破”美国中东安全框架之 “局”、特别是旨在掀翻“西方资本主导世界”之基础的“最暴力中东破局”做最后的准备。*

●“美以”以实际行动测试欧盟在叙利亚政策上的真实取向

如果在这个层面去观察问题，那么，在欧美一致要求“叙利亚总统必须下台”，而“巴以冲突”却突然再起的背景下，以色列因报复打死埃及士兵一事，应该是“美以”以实际行动测试“国际社会（包括欧盟）”在“永久开通第二条、甚至强行第三条通道”问题上的“团结度”，也是测试欧盟在叙利亚政策上的真实取向。

●如果......这又何尝不是“有人”在测试“美以”阻止“第二条、甚至第三条通道”的决心？

而如果以色列两辆公共巴士在“以埃边境”受袭一事不那么简单的话，那么，这又何尝不是“有人”在测试“美以”阻止“第二条、甚至第三条通道”的决心？

而从欧盟对以色列两辆公共巴士在“以埃边境”受袭，以色列之后又枪杀埃及两名士兵的“低调反应”、而巴勒斯坦仍然坚持准备单方面建国的综合情况来看，我们再次强调：在叙利亚这个“水深难测”的“止损点”上，欧盟公开加入“叙利亚总必须下台”这一步，这倒底是美国“已经拉”欧盟“下了水”呢？还是欧盟正琢磨着“如何一脚”将美国给彻底踢下水、且不再有机会爬起来呢？在东方评论员看来，就“结果”而言，恐怕还得走一步看一步！但明知欧元是美元现实敌人的欧盟，在这种有利情况下，认真琢磨“如何一脚”将美国给彻底踢下水的可能性要大得多！

总之，由于局势已经发展到极其复杂的层面，全球热点问题明显开始联动，再往前走任何一步，都有可能触发不可意料的结果，特别是金融层面的。

因此，我们将与大家一起密切关注形势的后续发展！
