# -*- org -*-

# Time-stamp: <2011-08-08 16:40:27 Monday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+STYLE: <link rel="stylesheet" type="text/css" href="css/org.css">


** 2011年8月5日

*** 阿根廷总统呼吁拉美国家：警惕发达国家转嫁危机

【布宜诺斯艾利斯消息】据媒体报道，针对全球金融市场当天出现的剧烈动荡，阿根廷总统克里斯蒂娜4日呼吁拉美国家做好充分准备，防止发达国家将金融危机的严重后果转嫁给包括拉美地区在内的新兴市场国家。

克里斯蒂娜当天在出席阿根廷冶金业大会时发表讲话说，全球股市当天的大幅下跌给南美国家敲响了警钟，警惕发达国家将金融危机的后果转嫁给其他国家。南美国家必须加强整个地区抵御危机的能力，同时加快地区一体化进程，共同应对新一轮潜在危机的挑战。

克里斯蒂娜说，在2008年爆发国际金融危机后，阿根廷政府采取了一系列果断措施，有效地应对了金融危机的挑战，使阿根廷成为最早实现强劲复苏的国家之一。

她强调，面对新一轮的金融动荡，阿根廷政府将继续目前的经济政策，加强进口替代战略，加大对民族工业的保护和扶持力度，以确保就业市场稳定。此外，阿根廷政府还将鼓励企业加大在科技创新和产业技术升级方面的投入，通过提高产品附加值实现国民经济的可持续增长。

克里斯蒂娜说，对于国际金融市场的短期动荡需要进行冷静分析，目前整个世界经济的发展形势对阿根廷来说还是有利的，阿根廷政府将通过巩固和加强目前的经济发展模式，化解全球金融动荡冲击波。

*** 韩国将举行应对紧急状态的乙支训练44万人参加

【首尔消息】据韩联社报道，韩国行政安全部5日表示，将从本月16日至19日进行应对国家紧急状态的“乙支训练”。

据悉，今年韩国的乙支训练将有各市、郡、区行政机构和重点管理企业等3800多个机构的44万余名人员参加。

训练的主要内容包括，盘点局部挑衅应对守则、民官军联合进行居民疏散避难训练、针对DDoS攻击等网络恐怖活动进行应对训练。

报道介绍说，乙支训练始于1968年7月，起因是同年1月发生的“青瓦台袭击事件”。


【时事点评】在东方评论员看来，作为“华盛顿共识”的主要受害者之一，曾经是“南美金融危机”风暴中心的阿根廷，其总统的这番“危世警言”值得高度重视！

请大家注意这两段文字，原文分别是：
第一，克里斯蒂娜当天在出席阿根廷冶金业大会时发表讲话说，全球股市当天的大幅下跌给南美国家敲响了警钟，警惕发达国家将金融危机的后果转嫁给其他国家。南美国家必须加强整个地区抵御危机的能力，同时加快地区一体化进程，共同应对新一轮潜在危机的挑战。

第二，她强调，面对新一轮的金融动荡，阿根廷政府将继续目前的经济政策，加强进口替代战略，加大对民族工业的保护和扶持力度，以确保就业市场稳定。此外，阿根廷政府还将鼓励企业加大在科技创新和产业技术升级方面的投入，通过提高产品附加值实现国民经济的可持续增长。

克里斯蒂娜说，对于国际金融市场的短期动荡需要进行冷静分析，目前整个世界经济的发展形势对阿根廷来说还是有利的，阿根廷政府将通过巩固和加强目前的经济发展模式，化解全球金融动荡冲击波。

●克里斯蒂娜女士“极其敏锐”地点出了“此次剧烈振荡”之“可能的后续发展”及“某些显见的对策”，


显然，在东方评论员看来，或是基于以往的经验与教训，针对8月4日至5日全球资本与货币市场的“剧烈振荡”，阿根廷总统克里斯蒂娜女士“极其敏锐”地点出了“此次剧烈振荡”之“可能的后续发展”及“某些显见的对策”，那就是：南美国家必须加强整个地区抵御危机的能力，同时加快地区一体化进程，防止发达国家将金融危机的严重后果转嫁给包括拉美地区在内的新兴市场国家。



●2001至2002年的阿根廷


众所周知，在2001年底，1982年拉美国家债务危机的悲剧在拉美第三大经济实体的阿根廷又一次重演，并开始向其它拉美国家扩散。


我们知道，阿根廷经历过曲折的全球化历程，这表现在它“既”体验过开放初期遭受的强烈冲击，“也”享受过因外资大量流入带来的经济繁荣，但最终仍然爆发震惊世界的金融危机。

针对<<2001年至2002年间的阿根廷金融危机>>，其实在之前的讨论中已经详细讨论过，在这里不再重复，但为了更好地展开今天的内容，我们想重复强调这样几点：


第一点，它是在<<1997年东亚金融危机>>、<<1998年的俄罗斯金融危机>>、<<1999年初的巴西金融危机>>等一系列危机之后，在阿根廷暴发、并向其它拉美国家扩散的。


2001年7月，由于阿根廷经济持续衰退，税收下降，政府财政赤字居高不下，面临丧失对外支付能力的危险，酝酿已久的债务危机终于一触即发，短短一个星期内证券市场连续大幅下挫，梅尔瓦指数与公债价格屡创新低，国家风险指数一度上升到1600点以上，而国内商业银行为寻求自保，纷纷抬高贷款利率，其甚至达到250%～350%。


●阿根廷2001年底暴发金融危机的原因



第二点，在我们看.来，阿根廷金融危机的暴发，“即”在于上述一连串金融危机使阿根廷的外部经济环境发生了非常不利的变化的因素，比如：令阿根廷吸引外资的成本越来越高，“更”在于此前的“<<大规模私有化>>”所造成的严重恶果。


事实上，依据新自由主义的模式，阿根廷等南美许多国家在那之前就开始实行经济改革，普遍进行私有化。

当时，要求、并指导阿根廷政府大规模私有化的“指导思想”无外乎就是：国有企业效率低下，长期亏损；而外来的“处方”又是如此地“似曾相识”：只有将其私有化，才能减少政府干预和发挥市场机制的作用，才能调动私人资本的积极性。


而在这股私有化浪潮中，在短短的时间内（也就几年），阿根廷政府就把几代人挣下的国有财产卖得干干净净，绝大部分涉及国计民生的国有企业纷纷转让给私人经营。其程度，堪与墨西哥相提并论。

值得强调的是，阿根廷政府在危机爆发之前，虽然通过私有化获得了大量收入、但这笔钱最终却被消费一空。据美洲开发银行的数据，在1990－1995年的私有化高潮期，共有123家国有企业被私有化，政府获得了185亿美元。

而这笔巨大的收入可以使阿根廷政府继续大手大脚地花钱，可以继续给政府部门的官员支付高薪和优厚的社会保障福利，然而，其“主要作用”也仅此而已！




●“私有资本的积极性”都用在什么地方了？



毫无疑问，大规模的私有化令阿根廷国有资产的严重流失，使“国家可支配的资产”相比“私人支配的资产”显得“极其不足道”，这样，稍有风吹草动，一个以“私有资产”为主体的经济体、其首先做的“经济、特别是金融反应”、整体上必然就是“纯市场反应”，自然就是以“<<出逃境外>>”、“<<挤兑银行>>”为主，外加“<<收缩投资>>”与“<<解雇就业人员>>”而求“自保”。

显然，对比那张“处方”，我们也就不难看出，在“阿根廷私有化”之后，在阿根廷“不仅减少、甚至没有进行政府干预”、而且全凭“市场机制”的“发挥作用”之后，“私有资本的积极性”都用在什么地方了？




●由于没有必要的资源支撑，这些“非常规手段”原本就是“无本之木、无源之水”！


因此，在金融危机袭来之时，在经济、特别是金融常规手段上，阿根廷政府基本是“束手无策”，只得采取一些“非常规手段”，而由于手中又没有必要的经济、特别是金融层面的“战略资源”作支撑，这些“非常规手段”原本就是无本之木、无源之水。因此，它们一经推出，要么是毫无作用，要么是适得其反，令金融危机雪上加霜！



●爆发骚乱


真实的情况就是：当时，处于金融风暴中心阿根廷宣布暂停偿还外债，冻结储户银行帐户，美元存款比索化、甚至一度宣布停止偿付1000多亿美元外债等措施,而随之而来的是阿根廷社会动荡、频繁更换总统（在极短的一个月不到时间内，竟然一口气换了5位总统）、货币贬值，物价飞涨，国民经济秩序极其混乱。

在这个问题上，最具代表性的一件事，就是2001年12月18日，首都布宜诺斯艾利斯等地爆发前所未有的大规模骚乱，抗议政府的金融管制措施。这一骚乱持续了2天。在与警察的冲突中，近30人死亡。


期间，至于那种以“敲打锅碗瓢盆”为特征的“"锅碗瓢盆式示威、游行和抗议”则更是司空见惯，总之“连换5位总统”也没有令阿根廷社会稳定下来。




●在阿根廷玩“大换总统游戏”的背后



第三点，在阿根廷金融危机中，在阿根廷大玩“换总统游戏”的背后，除了国家层面的确“束手无策”之外，更重要的是，<<这种“连换5位”的本身，是一个与“华盛顿共识”讨价还价的过程>>>。


事实就是，金融危机之中，面对阿根廷的苦苦哀求，此前用一部“华盛顿共识”去指导阿根廷等拉美国家进行私有化的国际货币基金组织和视拉美为自己后院的美国、竞然是“无动于衷”，在所谓的“前提条件”满足之前，将金融危机的主因“咬死”在“阿根廷政府腐败、社会低效”之上，反正是死也不肯拿出一美分来解救。直到阿根廷“被迫服用美国通过”国际货币基金组织（IMF）开出的、围绕“将私有化进行到底”之“药理”的、一剂接一剂的“补药”为止。




●阿根廷金融危机实质上就是一场“债务危机”




第四点，就对本国、邻国的破坏程度与对世界金融冲击的范围而言，阿根廷金融危机对该国造成社会贫困和经济破坏之大，引发社会抗议和政局动荡之强烈，不仅超过阿根廷历史上任何一次危机，也令当年在亚洲金融危机中受到重创的“东南亚国家”相形见绌，因为，与阿根廷金融危机同步发生的，还有<<财政危机>>、<<企业危机>>、<<政治危机>>、<<社会危机>>、<<体制危机>>。


因此，首席评论员就明确指出两点：

其一，阿根廷金融危机实质上就是一场“<<债务危机>>”。




●这种“危世警言”由阿根廷政府发出是“再合适不过”的了



在美国两党于最后时刻、“毫不令人意外地”调高了美债上限、再次确认美国将基于“种种企图”、必推“QE3(或者变相QE3)”、从而“进一步证实”美国债务问题在“美国国家与资本利益之间不可调和矛盾”之下“根本无解”而“只能缓和”、并“进一步预示”全球经济必将“二次探底”、甚至“可能”史无前例地经济大衰退之后，从“历史的层面”去看，类似这种“防止发达国家将金融危机的严重后果转嫁给包括拉美地区在内的新兴市场国家”的“危世警言”，由阿根廷政府发出是“再合适不过”的了。


其二，通过阿根廷金融危机（债务危机）同步发生的那一连串“XX危机”，我们不难想像，不论是欧洲、还是美国，对其两家中的“任何一家”而言，其债务危机一旦全面爆发，在“美国国家与资本利益之间矛盾不可调和”、“欧美国家利益之间矛盾不可调和”而“欧美资本利益之间矛盾很难调和”的情况下，也将同步发生一连串的“XX危机”，并向对方、以至全世界扩散。



对上述“这些矛盾”，我们再次强调其属性，即：

其一，美国国家与资本利益之间的矛盾具有“不可调和性”，因此，两者之间只能缓和、至多是有效缓和；

由于令“美国国家利益”受益极大的“美国诸多霸权”原本就是运行在“美元本位制”的基础上的，而“美国资本利益”也是借助“美国国家利益（力量）”一步步实现并维持“美元本位制”的，因此，在“美国次贷危机”爆发之前，都可以“简单地”这样认为：<<美国国家利益与美国资本利益曾经基于“共同的利益（维护包括美元本位制在内的美国诸多霸权）”、在追逐“共同目标（美国利益支配全球）”的过程中“处于有效缓和状态”>>。


而以“次贷危机全面爆发、美元本位制受到俄罗斯的率先攻击、美国不得不策动格鲁吉亚战争进行反击但却惨败”为标志，在美国绝对实力与相对实力均已实质性下降、从而“美国资本利益”开始有理由怀疑“美国国家利益（力量）”已经不足以“助”其实现<<“美国利益（资本）支配全球”这一“共同目标”>>，而“美国国家利益（力量）”也因之前的“追逐不利”、并在维护“美国资本利益”的层面上“过度透支国力”、从而要求“美国资本利益”暂时让利的“同床异梦”下，上述“有效调和状态”明显受损，就最近而言，这集中表现在“美国国家利益”开始修理“美国资本（西方资本）”的喉舌的问题上。


但从美国两党在“调高”美债上限问题上的“极近逼真的”争斗、及“最终如期”调高美国国债上限、从而为“美国资本”推出“QE3（或变相QE3）”打开空间的“整个过程”来看，或出于一种无奈（在欧美资本仍然未‘实质性选择’流向之前，美国国家利益与美国资本利益之间就有妥协的必要）、或出于“某一不可告人的企图”，“具有不可调和矛盾”的美国国家与资本利益之间，仍在“试图回到有效缓和状态”。




●所谓的“某一不可告人的企图”，我们早已经“点”破




至于所谓的“某一不可告人的企图”，其实在之前的点评中（最早一次，是在舆论争论美国是否会救“两房”时），我们早已经“点”破，“定性”而言，它其实就是：

<<尽力激化“南北撕裂”，从而一面尽可能缓和“三边撕裂”，一边尽可能利用“美元本位制”的金融霸权、在世界范围内、寻找时机、甚至“制造”时机、针对“南方经济体”、并“威、逼、利、诱”欧盟（欧元）与日本（日本），用“天量的硬通货流动性”，共同掀起一场史无前例的、由“北方”对“南方”的大兼并、大收购，直至“北方”彻底掌控“南方经济”的经济、特别是金融命脉，从而彻底地将“南方经济”“永固”在“北方经济”的最下游，从而彻底走出“欧美日债务危机（注，日本债务危机一旦爆发，对日本经济的摧毁程度、绝对较欧美更加猛烈）”。>>


值得强调的是，如果我们抽去“三边撕裂”与“南北撕裂”两个框架之“中”的、或、两个框架之“间”的“错综复杂枝节”，就可以清楚地看到，由于“南方经济”的代表是中国经济，因此，在“北方经济”彻底掌控“南方经济”的经济、特别是金融命脉，从而彻底地将“南方经济”“永固”在“北方经济”最下游的层面上，其实现的标志，将是“北方”对中国经济、特别是金融命脉的彻底掌控。

显然，这是“西方资本利益”说服“西方国家利益”的“说词”之一，

如果进一步去观察，由于“北方经济”的代表是美国经济，因此，这其实又是从“美国国家利益”手中刚刚“拿到QE3空间”的“美国资本利益”、用以“说服”“欧洲资本利益）”与美国资本利益“一道去努力”的“说词”之一；


如果考虑到“西方资本”目前仍由“美国资本”代言，则，这其实也是刚刚与美国资本利益做出妥协，从而令“美国资本（西方资本）”可以继续“量化宽松”的“美国国家利益”、试图“先”通过“美国资本”去“说服”欧洲资本、再通过“西方资本（欧美资本）”去说服“欧洲国家利益”的“说词”之一；




●这个“不可告人的企图”也可细化为“理论”与“操作”层面



事实上，这些“说服”也好，“妥协”也罢，其实都是为了着眼于上述“某一不可告人的企图”。

如果在“定量”的层面去观察，那么，这个“不可告人的企图”也可细化为“理论”与“操作”层面。


所谓“理论”层面，阿根廷总统已经说得非常清楚了，即：将金融危机的严重后果转嫁给包括拉美地区在内的新兴市场国家。

至于转嫁的方式，不论是“2001年阿根廷金融危机”，还是在那之前的“血洗韩国、印尼、马来西亚等的97亚洲金融风暴、令俄罗斯经济几近崩溃的98年俄罗斯金融危机、99年巴西金融危机、甚至80年代的墨西哥债务危机、令日本“失去十年”的“广场协议”等，都是可以选择的“成功案例”！




●“破局”的具体路线图，我们可以在“阿根廷金融危机”的“前前后后”中去找寻



所谓“操作”层面，在东方评论员看来，这恐怕就是我们一再强调的通过“第三种方式的南亚破局”、<<伺机将中国推入南亚冲突，再对中国进行经济、特别是金融攻击>>。

至于“破局”的具体路线图，我们可以3在“阿根廷金融危机”的“前前后后”中去找寻。


显然，在“阿根廷金融危机”之前，“先”让阿根廷服下“大规模私有化”的“苦药”，国家经济跨国公司化或外国化，90％以上的经济活动被外国公司控制，国家经济安全，特别是金融安全受到威胁，经济主权受损，不得不受制于国际货币基金组织和西方发达国家及跨国公司；

而97亚洲金融风暴、98年俄罗斯金融危机、99年巴西金融危机等又全面恶化了阿根廷的“外部安全环境”，在阿根廷金融危机暴发之后，在阿根廷的“西方资本”又兴风作浪，或带头出逃，或率先挤兑，终令阿根廷政府的“非常手段”要么“无疾而终”，要么“适得其反”，直到阿根廷社会动荡不已，骚乱四起，最终不得不为了换取“外援”而被迫继续“服药”。



而从最近的一段来看，在“西方势力”的努力中，不仅大有将中国“努力”成“阿根廷第二”的架式、且其具体路线图业已浮现出来：


首先，围绕“723动车特大交通事故”，不是有那么一种声音在或“逼”、或“劝”中国对自己的、诸如铁道这种战略行业进行大规模私有化吗？


其次，如果再将“埃及之乱”导向“欧亚海上运输线之乱”、并最终“量身订造”为专门针对中国的“中国海上运输线”之乱，且在“埃及之乱”的“后续发展”中、将非洲这一中国能源与矿产的“供应点”、商品的庞大市场、要么“苏丹化”、要么“索马里化”，就可以全面恶化中国的外在安全环境，再结合“西方资本”手中的大宗商品定价权，就可全面推高中国的输入性通货膨胀，从而倒逼中国率先进入不可逆转的加息周期，并“努力”令人民币利率快速升到不能再高的高度。



●用“一个极其困难的巴基斯坦”去最大限度地消耗中国的战略资源



再次，一旦将“埃及之乱”导向巴基斯坦之乱、特别是印度之乱，从而令“第三种方式南亚破局”成功，那么，即便中国顶住“大规模私有化”的压力，从而继续掌控用以支撑“未来可能施展非常手段”的经济战略资源、特别是金融资源，也可用“将中国推入南亚冲突”的方式，通过印度去最大限度地消耗中国，从而令“这些支撑”的“支撑效用”大打折扣。


在这个层面上，站在“西方资本”的角度，如果能利用“印度之乱”将中国拖入南亚军事冲突，这种消耗无疑是最大的，效果也是最好的！


如果不能，那么，如果能利用“巴基斯坦之乱”、并启用“拉登遗物”这笔遗产、“制造”巴基斯坦支持本拉登的“事实”，并据此联手欧盟、日本等“北方经济”、并加上印度等“南方经济”、全面制裁巴基斯坦，就可用“一个极其困难的巴基斯坦”去最大限度地消耗中国的战略资源，显然，由于“巴基斯坦通道”对中国极其重要，中国对巴基斯坦必然会尽力相“救”，而尽力相“救”也就意味着“极大地消耗”，毕竟巴基斯坦有1亿人口、且国内政治极其复杂！


此外，还有一个已经受到制裁的伊朗。


如果还不能，那么，站在“西方资本”的角度，假如“西方资本”能在“向南方国家转嫁危机”的过程中，通过一场“史无前例的大兼并”、率先掌控印度、巴西等5南方经济的命脉，那么，就可以将“印度、巴西等已经掌握在手的南方经济”、或作为“低成本生产基地”，或通过立法、行政等手段、实质性限制“中国制造”的对这些市场的进入，从而“不计成本地”用来打击“中国制造”，显然，这也是一种消耗方式。


而一旦中国政府手中“用于支撑”战略资源被“西方”如此这般地大量消耗，那么，即便中国为应付经济波动而施展“非常手段”，也可能像阿根廷的“非常手段”那样、注定成为“无本之木、无源之水”！


最后，就是“西方资本”适时启动“加息周期”，在中国制造的生产成本、资金成本、运输成本最高的时候，“进一步抽取”中国的流动性，并通过在中国境内制造“社会环境”、或者“自然环境”混乱，从内、外两个方向逼中国像阿根廷政府那样妥协：为了换取所谓外援、而不得不服下“彻底私有化”的“烂药”！直到将电信、铁路、能源、矿产、特别是金融等战略行业“私有化”、“西方控股化”为止。



●为什么我们如此警惕“南亚破局”？



通过上面的讨论，大家也就不难明白，为什么我们如此警惕“南亚破局”？显然，所谓“南亚破局”，在我们的讨论中，在“中段反导”之前，总是被分成“明修栈道式（政治与军事层面破局）、暗渡陈仓式（经济特别是金融层面）”。



而在“中段反导”彻底打破“美国军事技术绝对优势”的神话、并致印度“惊吓过度”，从而“废掉”了其所谓的“核威慑能力”之后，<<中国就已经“实质性”打开了中国全球战略的“中东战略空间”，为中国现在的强行介入“中东和平事务”奠定了基础>>。


至于中国军机经伊朗、飞到土耳其进行军事演习，不过是“中段反导”的一个“具体成果”、中国“强行介入中东和平事务”的一个标志性事件而已。



不论是“废掉”印度所谓的“核威慑能力”、还是强行介入中东和平事务，<<本质上就是将“大国间战略交易主要平台”从南亚方向推到中东方向，>>到此，我们对“南亚破局”的担心，也就更多地转至所谓“第三种方式南亚破局”。这一点，在进入“第四波排列与组合”阶段、特别是“美国利益决策层”基于“美国资本利益层面”策动“埃及之乱”、企图全面恶化中国外在安全环境之后，更是如此！



●不论是哪一种逃生方案，要想成功，“美国利益”都必须寻求“中欧”中任何一方的“实质性配合（欧美联手）”才行




而在之前的点评中，在美国债务危机“急待深化”的大背景下，针对“美国利益”的逃生方案，我们给出了两种可能方案：

第一种方案，就是“第三种方式南亚破局”；


第二种方案，就是以“利比亚”为支点，针对科索沃问题，对欧盟（欧元）进行跨海一击。


然而，基于我们之前的大量讨论，大家也已知道，不论是哪一种逃生方案，要想成功，“美国利益”都必须寻求“中欧”中任何一方的“实质性配合（欧美联手）”才行：“第三种方式南亚破局”要想成功，得到欧盟（欧元）的实质性配合是前提，不然，不仅很难离间“中欧关系”，且一旦中国在南亚方向强硬反击，美国（美元）就很难摆脱“为人（欧盟、欧元）做嫁衣”的下场！最为不确定的是，一旦中国在中东方向强硬反击，促成“<<中东最暴力破局（中东核竞赛）>>”，则西方资本主导世界的根基都将动摇。



类似，以“利比亚”为支点，针对科索沃问题，对欧盟（欧元）进行跨海一击，这要想成功，却需要中国的“实质性配合（至少是旁观）”才行，否则，不但很难离间中欧关系、也很难通过“科索沃攻击”迫使欧盟（欧元）低头，更为重要的是，一旦发动“科索沃攻击”、但欧盟（欧元）长时间不低头，“美国资本”所代言的“西方资本”就很难阻止“人民币国际化”这只“陀螺”顺利起旋、并快速进至“高速旋转”的“超稳定状态”，甚至后来居上，从而美国（美元）也难以摆脱“一场辛苦为谁忙”的下场。




●美国急于解开上述“两种方案”的“共同死结”




而从目前美国的种种动作来看，美国急于解开上述“两种方案”的“共同死结”，即：不论是中国、还是欧盟，由于都看明白了“前因后果”，也就始终不肯为“第二种方案”、或者“第一种方案”给出“实质性配合”。


如果在这个层面去观察问题，我们也就不难明白，为什么尽管叙利亚局势如此紧张，但欧盟就是不肯在美国望眼欲穿的“全面制裁叙利亚“问题上“更进一步”？为什么中国外长在访欧期间俨然一位“财经阁员”，频频地谈论金融问题，一面提醒美国注意保障中国在美资产的安全问题，一面还不忘记“支持欧元”！


在这种情况下，美国决策层的策略显然有所改变，即：既然你们两位“老神在在”，那就换个方向，从“重启美俄关系”的层面着手。


由于“中俄欧美”在中东、南亚等几乎所有全球战略方向，在伊朗、科索沃、利比亚、叙利亚、巴基斯坦、印度、巴以和平、朝鲜等几乎所有热点问题上，都有大量的利益、矛盾重叠，并形成今天这种“多个热点的多极平衡”状态。


显然，“中欧”分别在“第二与第一方案”上的“老神在在”，就是这种“多极平衡”的一部分。





●美国决策者近日的“外交指南”



因此，如何能在“重启美俄关系”做点文章，在多个热点上，或者在某个热点上，比如叙利亚、更或者在巴基斯坦、印度等关键热点上“打破这一多极平衡”，也就成了美国决策者近日的“外交指南”。

在东方评论员看来，只有参考这样一份“外交指南”，我们才能看清楚美国在“俄罗斯入世”、“逮捕乌克兰美女前总理”等一系列重要问题上对俄罗斯“突然叩头”的动机，也才能看明白欧盟也赶紧“支持俄罗斯入世”、且不反对“逮捕乌克兰美女前总理”的“快速反应”。


显然，欧盟即不想俄罗斯的反应有利于美国利益，也不想其反应有利于中国利益。




●大家都是老中医，别给我来这偏方！




不仅如此，还能看明白俄罗斯早一天扬言“要提前归还中国的贷款、并对中国断气、强化对欧输气”，但过了一天，又表示“俄罗斯准备在对华输出天燃气的价格上主动降价100美元、不再坚持与输欧价格一致、以继续谈判”。


显然，作为一个当今的世界大国、曾经的超级大国，俄罗斯对美国的策略也看得一清二楚，在应对上也进退有据：对“欧美”的政治动机，其应对是“政治问题经济化”，即用“俄中”之间的“经济问题”去平衡；而应对中国的经济要求，其应对则是“经济问题政治化”，即用“俄美、俄欧”之间的“政治问题”去对冲！


在攸关自己全球利益的关键点上，比如叙利亚，俄罗斯则是坚决不让，因此，在谴责叙利亚的决议方案上，俄罗斯与中国一道，声称将“否决”，但是，在拿到了“俄罗斯入世”的承诺、与“欧美”联名签发的“逮捕乌克兰美女前总理”的“逮捕证”之后，那纸没有约束力的、谴责叙利亚的“主席声明”，就算是“扯平”了。



从俄罗斯的回应来看，可以肯定，俄罗斯面对美国的这一轮、有着“鲜明实用色彩”的“重启俄美关系”，其态度也分明是：

第一，大家都是老中医，别给我来这偏方！

第二，在美国“实质性启用”俄罗斯通道、从而将美国中亚战略、南亚战略、甚至全球战略的咽喉交由俄罗斯掌握之前，什么“入世”、什么“逮捕乌克兰美女前总理”，都只是“只能欣赏的态度”而不是“可以安全享用的成果”！

●“有人”在借机“替”俄罗斯“催促”美国了

因此，在东方评论员看来，绝非巧合的是，就是在这个时候，巴基斯坦境内再次传来“北约运输线频频被炸”的消息，显然，“有人”在借机“替”俄罗斯“催促”美国了：那条“俄罗斯通道”，你到底是决心“实质性启用”还是“不”启用？如果“实质性启用”，那么，这一连串袭击，在“美巴关系”已急转急下的背景下，这无疑是对巴基斯坦施加自“本拉登被打死以来”“最大压力”的“最好借口”，如果不打算启用，那就“别胡说八道”！

如此一来，“第三方案南亚破局”恐怕就不是美国决策层的“有决心立刻执行”的方案，如果是这样，那么，欧盟就要多想一想了：首先是想一想在叙利亚问题上，能做什么与不能做什么？其次，是想一想在巴以和平问题上、自己又能做什么与不能做什么？

最新消息是，在中国针对以色列指出“定居点问题”是巴以和平最大障碍、并称“对任何有利于巴以和平的方案都持开放性态度（注，我们认为，这暗含了巴勒斯坦单方面建国）”之后，尽管以色列突然宣布“准备回到1967年边境的基础上进行和谈”，但巴勒斯坦仍然放话“准备即9月在联合国寻求单方面建国”。

显然，根据我们的观察，美国这一轮旨在通过“重启美俄关系”、从另外一个方向打破“多个热点的多极平衡”的努力，在“有人”在“巴基斯坦通道”上“测试（注、恐怕也是报复）”了一把之后，由于北约（美国）果真“没胡说八道！”，因此，在大多数战略方向上，“方方面面”大体上也就“该干什么还是干什么”！

而对于中国而言，由于“南亚破局”始终是美国考虑的方案之一，因此，在东方评论员看来，就如我们之前所强调的那样，为了防止欧美联手，要以“一切可以考虑的手段”、鼓励欧盟向“欧盟彻底整合的目标”进行“冲刺”。

而在这些“可以考虑的手段”中，就包括让驻阿美军的直升机成批的往下掉，也包括朝鲜对韩国岸上目标今天打一枪、明天打一炮，从而将美国部署在东亚、中亚的战略资源也“死死地拖住”，甚至还包括以各种方式、支持南美国家或用政治、经济手段，或用军事手段进一步清除南美的亲美势力，从而将“热点”插进美国的后院、并“点火’、让其“冒烟”，以最大限度地“鼓励”欧盟（欧元）下决心快速解决“科索沃独立后续发展”、并下决心向“欧盟彻底整合的目标”进行“冲刺”。

但是，由于大国间的角力再次白热化，因此，东亚方向又有些闹腾！

对“越南邀印海军入驻芽庄港”，但却“与美国签了一份无关美军入住的军事协议”、我们的观点是，越南这一次的确有点儿“怕打”，否则，干脆直接拉美军入驻得了，一边拉没有能力抗衡中国的印军入驻越南，一边与美首签什么“无关驻军”的军事协议，显然是“心有不甘”的“内心写照”！也算是一种讨价还价！问题是，“首批”中国航母即将入役、且眼光盯在中东、科索沃、南亚的中国会理睬这些小动作吗？

●对可能的“日本版天安号事件”要高度警惕

结合“日本日本海上保安总部5日下午逮捕两名中国船长并扣押渔船”，“韩国将举行应对紧急状态的乙支训练44万人参加”等动静，以目前的形势来看，我们以前的一句话仍然适用，即：一旦中国在战略上安排好（在中东与南亚、或者科索沃方向），那么，在东亚方向，如果越南敢在南海方向浮出来（将美国军事力量正式引入越南）、就当着美国人的面、给“摁”下去；如果日本敢在东海方向飞出来（军事挑衅）、就当着美国人的面、给“打”下来，如果韩国还继续不清白，就让朝鲜对着韩国的岸上目标，今天放两枪，明天打两炮！直到打得韩国经济崩溃为止！

最后，从日本不顾地震灾难、特别是核灾难的后果远未清除，就四处挑衅（除了扣押中国渔船外，日本前外相还要访日俄争议岛屿）的情况来看，日本国内部分“李明博式亲美势力”仍然有“制造事端”的苗头，因此，我们再次建议有关部门，由于国际局势近几个月可能急变，特别是“印度之乱”、或者欧美债务危机引发全球经济危机、或者区域性（比如东亚、南美、非洲）经济危机、特别是金融危机的可能性持续增高，对可能的“日本版天安号事件”要高度警惕。

对此，除了要与日本国内的“健康力量”保持良好沟通之外，最好准备一份“公开、虽不带操作细节、但有操作结果”的“预案”，通过日本国内的“健康力量”让日本国内部分“李明博式亲美势力”明白、并加以约束，即：一旦有此类事件发生，除了“关系紧张”必将沉重打击日本经济之外，如果日本进一步做出军事层面的战略误判，在“中欧俄美”角力的关键时刻进行军事挑衅，那么，不论是什么挑衅行为，一旦失控，中国将毫不犹豫地、“成建制地”摧毁日本军事目标，至于“美日军事同盟”是否有效？那是事后美国需要考虑的事情！至于日本是否反击？那是日本在考虑清楚自己的生存问题之后，才可以做的反应！如果考虑清楚之后“不敢反应”，那么，如何对其国民进行交待，那是挑衅者事先就需要想好的事情。就像东海上空那架坠毁的F15j一样！
