# -*- org -*-

# Time-stamp: <2011-08-04 18:03:21 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent


* 入联公投局势追踪
  
** 【金鸿评论】入联公投局势追踪(连续一 周共六篇)

    2月27日,美国会众院外委会通过了“支持台湾民主选举”决议案。

    俄罗斯驻联合国大使维塔利·丘尔金27日在俄新社组织的莫斯科-纽约视频连线记者会上表示，如果伊朗在近期内不改变在浓缩铀问题上的立场，不停止其
重水项目，则俄罗斯将支持联合国针对伊朗的新的决议案。

    【金鸿评论】俄罗斯的做法有点胳膊肘儿往外拐——自己人算计自己人的味道。不过，俄罗斯“算计”伊朗好象来的不是时候，现在可正是美国向中国找事的
时候。难道美国与俄罗斯之间私下里达成了某种协议，以至于俄罗斯背叛了上合？还是先看一下局势的后续发展吧：

    上海合作组织秘书长博拉特·努尔加利耶夫29日在此间说，上合组织的“和平使命”反恐演习今后将定期举行。

    联合国安理会2月29日继续就含有制裁内容的伊朗核问题决议草案文本进讨论。美国、英国驻联合国代表28日分别表示，安理会可能将于3月1日就决议草
案进行投票表决。尽管面临联合国压力，伊朗总统内贾德依然态度强硬，幷在28日再次语出惊人，称伊朗为“世界头号强国”。

    【金鸿评论】上合秘书长与内贾德显然是在一唱一合。说伊朗是世界头号强国有点过了，不过，说上合在这个世界上无人敢惹倒不算自大。局势的发展显
然说明，俄罗斯没有做任何出格的事情，警告伊朗这档子事好象另有原因。

    俄罗斯的真实目的究竟是什么呢？是人情。俄罗斯有意卖个人情给中国。

    丘尔金警告伊朗的时候，正是美国拿着入联公投疯狂挑衅中国的时候。入联公投很显然是美国压中国在中东让步的一张牌，而胡主席在去年的APEC峰会时
当时布什的面接了招、把它定性为台独，目的就是要彻底废掉这张美国人手里唯一可以压着中国的牌——只要这一次中国挺了过去，以后就再了不是美国压中国
的牌了，所以，不得已时中国宁可提前武力解决台湾问题也绝不妥协。但是，如果中国冒然在台海动了手，极有可能落得个局势获利、全局被动的结果，而美
国一再的逼中国在台海出手也是为了以丢掉台湾为代价换取整体翻盘的机会。

    中国人也没那么容易被人算计。如果真的被逼着在台海出了手，那么，中国将在伊朗原子弹的爆炸声中解放台湾；朝鲜半岛上也肯定不会消停，至于要不
要把大把的美国国债卖了换成黄金，就看美国人的表现了——如果真没办法，只能让美国提前崩溃，尽管那样我们也会受伤害。

    写到这里，大家应该看出来了，丘尔金的表态来的恰如其时——现在如果美国人不希望伊核问题失控，那就去求中国人好了，现在我（俄罗斯）不会在这个
问题打劫你（美国）了。如此一来，中国的角色立码吃重了——如果美国不希望伊核问题失控，那就把入联公投压下去！同时，这也是在警告欧盟，不要站错了
队！如果再对美国抱幻想，极有可能失去在伊核问题上的话语权，接下来将会被踢出中东。

其实，俄罗斯也知道，如果中国的主要精力被牵制在了台海，那么在中东方向上俄罗斯只能独自面对来自美国的强大压力，这极有可能让大好的斗争形势急转
直下。所以，从这里也可以看出，绝对不存在俄罗斯趁着中国解放台湾的机会打劫中国一把的可能——这无疑于对自己进行釜底抽薪。另外，欧盟的态度也的确
令人恶心。一个默克尔私会老和尚还不够，萨科奇居然想打对台军售的主意，真是有水平！只不过，在砸到了自己的脚指头后不要怪自己搬了一块搬不动的石
头就好。

    中俄的强硬招开了美国强烈的反弹——距离3月22日还有近三周的时间，它还有足够的时间跳得更高一点，不过，结果只会是摔得更惨。

    以色列国防部副部长马坦·维勒奈2月29日接受以军方电台采访时，发表惊人言论，称巴勒斯坦人将给自身带来一场更大的“大屠杀”。

英国《星期日泰晤士报》在头版头条位置披露：以色列科学家奥登里奇正在全力破译犹太人与阿拉伯人之间的基因差异，目的是制造出只攻击阿拉伯人的‘基
因炸弹’！”

    【金鸿评论】以色列可真能耐。不过，以色列好象有点托大了——英国人在报道中还透露，奥登里奇领军的以色列生物学研究所的真正上司，是以色列总理
办公室和国防部，而其海外战略伙伴，则是专事生化基因武器研究的美国陆军医学研究与开发司令部——恰恰就在25日，美国的防长盖茨还在回答“美国是否在
利用印尼提供的禽流感病毒样本研发生物武器”的问题时说：“这是我所听过最可笑的事情。”

    可笑的到底是攻击美国的“传言”还是美国的那帮统治者们？

    还好，无论是生化武器、气象武器，还是激光武器、太空武器，都不是美国人一家的专利。在这个世界上还有别的国家能把美国炸回到石器时代，所以，
美国人的讹诈才没有那么可怕。再说了，大家都不是被吓大的，从最新传来的消息看，好象没人当这当回事：

    埃及外交部发言人胡萨姆·扎基2日表示，埃及决定开放与加沙地带交界的拉法边境口岸，允许近日来在以色列军事行动中受伤的巴勒斯坦人进入埃及境内
接受治疗。

    【金鸿评论】埃及能冲到第一线，绝对耐人寻味。欧盟该做检讨了！

    本次巴以冲突实际上是06年黎以战争的翻版（见《昨日重见》一文）。上次黎以战争结束前发生了这样几件关键的事情：埃及总统穆巴拉克公开表态，美
国等西方国家在中东正逐渐失去信誉——做为中东最亲美的阿拉伯国家发出了强烈的反思对美政策的信号；之后，中俄果断的在阿富汗方向亮牌——英国在巴基斯
坦提供的准确情报支持下破获了一起恐怖袭击案（对老穆的帮忙，美英不说一个谢字却从此时起天天问老穆要拉登），伊朗也号称与本国安全卫队与阿富汗毒
贩干过一仗。之后，怕阿富汗局势失控的美国马上命令以色列停止了对黎巴嫩真主党的攻击。那一次，本想捞好处的欧盟不但被美国挤压的很惨，还让阿拉伯
世界大失所望。

这一轮激烈的巴以冲突，“似乎”也到了该结束的时候了。

    5日更新：今天看到了巴以冲突的最新发展，消息如下：

    以色列方面2日继续对哈马斯组织控制的加沙地带发动猛烈攻势，巴勒斯坦自治政府主席阿巴斯已中止所有和以色列的接触，以抗议以军发动“闪电战”。

    以色列军队3日撤离加沙地带，控制该地区的巴勒斯坦激进组织哈马斯对此宣布“胜利”，并誓言将继续向以色列发射火箭弹。加沙地带经过连日来的冲突
，已导致100多名巴勒斯坦人死亡，美国因此呼吁双方停火，恢复和平会谈。

    【金鸿评论】出现这样的情况，我只能再次说，这是昨日重现，这一轮的巴以冲突完全是06年7、8月份黎以战争的翻版。如果硬要找区别，那就是以色列
更滑头了，美国更无奈了。

    在这一轮的冲突中，阿巴斯非常搞笑，中止了所有和以色列的接触，阿巴斯的这个表现和06年黎以冲突后期以色列轰炸了加纳村后黎巴嫩政府拒绝在以色
列停火前会见美国国务卿赖斯时的表现一模一样。当时的黎巴嫩政府无疑是亲美的，他们却不敢、也不能见自己的美国主子，倒不是他们不想，他们是怕被愤
怒的、绝望的黎巴嫩人民赶下台——当时的黎巴嫩驻联合国大使马穆德曾表示，他与黎巴嫩总统一样，尊敬真主党领袖纳斯鲁拉，并说如果黎巴嫩今天举行自由
选举，真主党会取得很好的成绩。今天的阿巴斯也是一样，再不装装样子也就没法混下去了。

    在美国人眼里，只有两个真正的“兄弟”，一个是英国，一个是以色列。可恰恰就是这两个“小兄弟”，对自己的中东政策都已不再配合了。去年春年，英国
人跟伊朗玩了一把“周瑜打黄盖”的水兵被抓游戏，向全世界表明，自己不参与对伊朗的战争。今天，以色列又玩了一回“昨日重现”，向全世界表明，别指望我
为了你（美国）连命都豁出去了，就算半年前你给了我300亿美元的军事援助也不行！这下子美国人可亏大发了，那次美国人给的援助可不少，为了笼络人心
，还不光给了以色列。美国人送装备的意思就是希望以色列对叙利亚的，现在倒好，全赔进去了。

     到现在为止，不光伊朗，就连叙利亚也安全了。看来，中俄的军事保护还是相当有效的。至于哈马斯就更不用说了，其光彩程度绝对不比前年的真主党
差。哈马斯宣布胜利完全在情理之中，他有本钱。

    现在大家应该能够看出来了，在中东美国是的的确确说了不算了——连自己的奴才你都玩不转，你还狂什么？

    倒是欧盟最近在某些问题的表现上非常恶心人，手里明明没什么本钱，偏要装的跟大爷似的——你就等着吃亏吧！现在，胡主席已经开始批台独了，就在同
一天，伊拉克也出事了:拉克军方一架米-17运输直升机在伊北部坠毁，机上8人全部丧生。真是巧的很呀!当然,这也是给欧盟的最后机会。如果不想被踢出中
东，沦为二流，就少耍小聪明——如果入联公投停不下来，中东的原子弹肯定先响，伊拉克肯定先开锅,到时候看谁最先扛不住！

    7日再次更新:
    【金鸿评论】在中国的强大压力下，在俄罗斯的通力配合下，美国终于顶不住了，露出了让步的意思，不过，他又非常的不甘心。于是，耍了一个小动作
：
    陈水扁5日表示，若国民党愿意“修法”降低“公投”门槛，他愿意协调“公投”和选举脱钩处理。
    【金鸿评论】现在说入联公投要被美国人压下来了还太早。小扁的这个动作完全是在试探——试探中国的战争意志。如果中国的态度马上软化了，那他们会
认为中国不敢打，是纸老虎，公投马上会反弹；如果中国继续强硬，他们会向台湾同胞煽风，“看，大陆只要地盘，根本不管我们老百姓的死活。”这个招还真
的不太好接——小扁，你个畜生！够刁！不过，你真以为玩不了你吗？
    伊朗总统内贾德3月6日说，从现在开始绝不会再与大国就伊朗核问题进行谈判，这一问题只能在国际原子能机构范围内解决。
    【金鸿评论】上面的评论中说中俄通过各种方式警告欧盟，配合中俄的中东战略，压制美国用入联公投挑衅中国的动作，以免大好形势出现意外。可欧盟
以为自己是“奇货可居”、“待价而沽”，结果迟迟不动。因为至少从表面上看，欧美还是一家——同属北约，所以，要想让欧盟做什么事，“请”不如“逼”。伊朗的
这个动作就是个意思。
     过去，在伊核问题向来是欧盟做中间人。现在伊朗表态了，“我们只和国际原子能机构谈”，无非是说“以后没你欧盟什么事了”。当然，这个警告的程度
还没到顶点——希望欧盟别逼着伊朗宣布“自己已经拥有了核武器”，那时可没有卖后悔药的。接下来我们要看的，就是欧盟会做什么动作来逼美国压入联公投以
保护在自己在伊核问题上的发言权了。

    今天还看到了另外一则消息:
    欧洲联盟６日发表声明说，台湾当局推动的“入联公投”将会加剧台海紧张局势，损害包括台湾人民在内的所有各方的利益。欧盟发表的声明重申，欧盟奉
行一个中国政策，维护海峡两岸的和平与稳定对于欧盟来说具有“重要的利益”。

    【金鸿评论】我现在还不确定内贾德的表态和这条消息倒底哪个更早,因为都是写的6日,所以我也不好说一定是老内警告在先,欧盟服软在后,不过,欧盟的
这个态度好象还是不太够,至少我感觉欧盟还是不够诚肯——当然了，承认有“重要的利益”就好。接下来,看美国的反应吧.如果入联公投还不停,欧盟的兄弟们还
得出力呀,否则,哼哼!

    8日更新:今天又看了一条消息:

    德国《金融时报》3月6日文章，原题：中美军力竞赛中国正在逐渐成为世界军力大国，美国为了应对中国的挑战而不断扩充自己的军力，并批评中国军费
不透明，但却是美国自己一手造成了这样的局面。

   【金鸿评论】有德国人这个态度在,欧盟的表现基本可以了,如果再结合以色列的态度的话，入联公投离结束不远了。下面看一条以前漏评的消息：

    以色列外交部4日发表声明称，以外长利夫尼3日表示，如果有必要，以色列将考虑重新占领加沙地带。
    【金鸿评论】奥尔默特真爷们，敢跟他的后台老板唱对台戏！所谓的“攻占加沙”完全是在说给他的美国老板听的。“攻占加沙”不是对哈马斯的军事进攻信
号，而是对美国的政治进攻信号。
    如果以色列真要打下加沙，还用等到今天？再说了，就军事实力而言，不用说对付拿着土枪土炮土炸弹的哈马斯，也不用说真主党，就算是连叙利亚绑在
一起，也不够以色列军队塞牙缝的。可问题是，打下加沙有用吗？灭了哈马斯有用吗？
他（以色列）可一直在瞪着眼睛看着站在哈马斯真主党叙利亚后面的人呢。
    这次以色列喊攻占加沙，完全是在将布什的军！如果把加沙打了下来，阿巴斯还敢和以色列“和谈”吗？巴勒斯坦人还不疯了？阿盟还是急了？阿拉伯人自
会清理门户，就算不让他消失，也会让他退休。如此一来，美国人可就麻烦大了--原来巴以和谈的双方都听自己的，阿巴斯一倒，哈马斯补位，巴以和谈就从
“美国自己把持、欧盟搀合、俄罗斯做冷板凳、没中国什么事”变成了“美国VS中俄、欧盟旁边干急眼”了。接下来美国在中东还混不混？刚刚失去了伊核的主导
权，再失去巴以和谈的主导权--布什先生真是好运！
    接下来布什会做什么？换人？拉宾被暗杀了，沙龙残废了，他们都是在不听话的时候倒下的。现在的奥尔默特也在做着与他们相同的事情--这位老兄也是
官司连连，还好，生命没有受到威胁。可明天会发生什么，谁敢说？
    现在，还有一个问题，就是为什么以色列会如此下狠手的逼他的大老板美国呢？他是怕伊核问题失控，怕伊朗拥有了原子弹。因为一旦伊朗也成了核国家
，以色列在中东的军事优势就荡然无存了，其国家安全马上就能了大问题，国小人微的以色列就得面临生存危机。所以，以色列极有可能是在逼美国在台海有
所收敛、把入联公投压下去。否则，那边一公投，这边就核爆，自己也就被架到火炉上了，以后的日子还过不过？
     9日更新

     【金鸿评论】先说一下昨天提到的“德国批评美国一手造成了中国成为全球军事大国”一文的意义。这里面有这样一个逻辑：德国人认为中国的军力增强
是被美国（用军力竞赛）逼的，德国人认为中国的做法没有错；同样的道理，德国人也认为中国对台湾动武是被美国（用入联公投）逼的，德国人认为中国的
做法也没有错。再加上欧盟的态度——维护海峡两岸的和平与稳定对于欧盟来说具有“重要的利益”，可以得出结论，如果台海开战，为了自己“重要的利益”，欧
盟绝对会站在中国这边、反对美国。所以说欧盟的表现基本可以了。
    下面看一下局势的发展：
    美国《华盛顿邮报》7日报道说，陈水扁执意推动“入联公投”，美国已经改寄希望于台湾人民，盼望选民在投票时有明智的抉择。美国国务院熟悉台海事
务的官员则表示，美国反对“入联公投”的立场没有改变。
    无党团结联盟籍“立委”高金素梅8日说，“公投”造成蓝绿阵营互斗，无盟党立场很清楚，不论是民进党提出的以“台湾”名义加入联合国“公投”案，还是国
民党提出的以“中华民国”名义重返联合国“公投”案，都呼吁民众拒领。至于“总统”票，高金素梅说，“我会把这张票投给马英九”。
    【金鸿评论】入联公投结束的钟声终于被美国人撞响了，台湾各届也开始“拒领公投票”;如果不出现大的意外,入联公投已进入扫尾阶段。接下来我们就可
以看到“台湾人民”是如何反入联公投的,小扁又是如何“被民意所迫”灰溜溜的停止入联公投的了——估计入联公投会在一周内彻底停下来。
    看来布什还是想表演一番，让我们胡主席看看他是如何玩弄台湾的“民意”的，又是如何巧妙的把下一个台独头子马英九送上宝座的。我们绝对承认，美国
人对台湾控制能力之强是令人惊叹的，但是，美国人的高超手腕对北京而言，绝对是“屠龙之技”——好看的很，却没有用处。你（美国）能左右的了台湾的政局
，你能左右的了东亚的局势吗？你能左右的了中东中亚的局势吗？你能左右的了南亚非洲南美的局势吗？你能左右的了俄欧关系吗？既然在这些大局势上无从
着力，那么，控制台湾控制的再好能有什么用？一枚弃之可惜、留之基本无用的残子而已。
    经过这一轮次（从去年澳大利亚APEC胡布会开始到现在）的斗争之后，美国人手里的台独牌已经被胡主席彻底废掉了。从今往后，“两岸三通”逐渐步入正
轨（先谈判后实施）——如果美国人希望朝核能出现一点实质性的突破的话，拿“三通”做交换是唯一的途径。“三通”应该会在3-5年内成为现实，中国统一也将
在15-20年内实现。不确定的是和统还是武统。一般说来，和统是当时付出代价小、尾巴太多，不利索；武统是当时会有阵痛，不过不会留下后遗症，属于一
劳永逸。从效果上说，武统好——打下来的江山最实在。当然，如果能沉的住气，多忍几天（拖得时间长一点、准备工作更充分一点）的话，武统的阵痛也会小
一点。当然了，这些都是后话，一年内台独还会反弹（无论是小扁还是小马在台上都一样），不过已无耐大局，他们再跳也不会象这回跳得这么高了——如果现
在硬要在这个世界上找两个美国“叫他往东他不敢往西、叫他打狗他不敢抓撵鸡”的人的话，那第一个一定是陈水扁，第二个就是马英九——民族的悲哀！

    还有一点就是在这一轮的入联公投中，许多朋友都很关注可能出现在台海战场上的1：3的问题。其实，那个 “美日台VS中国”的3：1并不存在——如果日本
胆敢加入战场，那我们就不收台湾了，先把日本打沉了再说！否则，怎么对得起当年的大东亚共荣圈？日本深知其中的利害，早就躲出去了，至于美国，台独
分子就更指望不上了，台湾只不过是美国的一颗残子而已，美国岂会为了一颗残子去拼老命？他要的只是中国的某些让步而已，如果实在得不到，入联公投自
会停下来。倒是另一个并不引人注意的3：1被北京基本搞成功了——“中俄欧VS美国”。当然，欧盟绝对是心不甘、情不愿的，可惜，他没有反抗的本钱，干也得
干，不干也得干！
    本来，欧盟是个不错的合作伙伴，可想不到的是默克尔、萨科奇太不争气，居然对美国心存幻想，从去年11月开始和美国做起了露水夫妻，到现在三个多
月了。不过，这三个月欧盟还真不捞到多少好处，脸却没少丢。不过，经此以役，想必欧盟也该长长记性了——与中俄联手抗美才是正道。

    10日更新:

    昨天的评论中出现了一点疏忽，有一条重要的消息考虑的少了，就是胡主席的对台讲话。这次入联公投就要收场了，从本质上说，是华盛顿通过操纵台湾
的民意在台湾自下而上反公投的结果；但是，从表面上看，台湾民意反公投发生在胡主席的讲话之后（“对于那些曾经台独抱有幻想、主张过台独甚至从事过
台独活动的人，也要努力争取团结，只要他们回到促进两岸关系和平发展的正确道路上来，我们都将热情欢迎，以诚相待。”），是胡主席对台湾民意“招安”
的结果。虽然北京现在还没有能力左右台湾的局势，但这次胡主席通过讲话给华盛顿搅局搅得确实漂亮。还有一则消息，比较有意思：
    现在有消息说，日本东京都知事石原慎太郎打算向中国的投资人求助，以化解自己设立的“新银行东京”所面临的破产危机。
    其实，日本比中国有钱，一家公司再缺钱也不至于到了非求中国不可的地步，再说了，象石原那种为了反华连命都可以不要的日本右翼怎么会仅仅为了救
一家公司而给中国下拜呢？其实，小日本想要传递的真实信息是：既然一家日本公司（其老板是绝对反华派）面临生存危机时，其老板为了让公司活下去都愿
意求中国帮忙，那么当整个日本国家（其老板骨子里同样反华）面临生存危机时，其老板为了让国家活下去选择倒向中国将是非常自然的事情。
    当然了，华盛顿还没有傻到放日本逃跑的那一步——这意味着美国全球战略的崩溃（对美国而言，十个台湾都比不了一个日本重要）。这个结果是华盛顿绝
对不敢面对的。所以，入联公投马上就要被压下去了。不过，我倒真的希望公投在3月22日以前不要停止——这样我们将有幸看到了一场“自发的”波澜壮阔的全
世界反台独大行动。不用中国提要求，会有大批的的国家跳出来反入联公投：
    首先是最害怕天下大乱的阿盟，害怕活不下去的以色列，也有怕被踢出中东的欧盟，这几位绝对是打头阵的；其次就是日本和韩国，这些国家反独都是被
逼的——城门失火，殃及池鱼。这些与美国有着重要关系的国家个个怕天下大乱之后自己会遭殃，所以“维护海峡两岸的和平与稳定”对他们个个都具有“重要的
利益”。
当然，也有大批支持北京的国家也会自发的加入进来：俄罗斯和其他上合成员国，第三世界的亲华国家（中亚亲华国家、非洲的兄弟国家、拉美左翼国家、东
盟等）。最后就是一部分相对超然一点的国家，为了卖个面子给几个老大，也会一起跟着喊两嗓子。
    不过，这一大气磅礴的场面大家应该无缘面对了。看一则8日的消息：
    朝鲜外务省发言人8日发表谈话，谴责台湾当局试图进行“入联公投”，并表示坚决反对台湾以任何形式加入联合国。朝鲜中央通讯社援引这位发言人的话
报道说，台湾当局将举行的“入联公投”是恶化台湾海峡和东北亚地区局势的严重行为。朝鲜政府一贯支持中国党和政府建立在一个中国、“一国两制”基础上的
统一政策，今后也将继续支持这一政策。
    上面分析反入联公投的国家时，没有提到朝鲜，因为朝鲜跟中国是一体的（巴基斯坦也是）。中国的朝核牌本身就是冲着美国的台独牌来的，朝鲜这次出
来反公投、支持一国两制本身就是在提前向美国开价——想要朝核出现一点实质性的、可以给美国脸上增点光的突破的话，就用“三通”来做交换吧——不先“三通”
怎么实现一国两制？
    上月底，黑妹赖斯亲自飞了一趟东亚（为核何而），甚至连“绑架问题不会影响将朝鲜从援恐名单中删除”的话都放出来了（当然美国也有威胁日本的意思
在里面），还没有换来六方会谈的复会。朝鲜在等什么呢？大米和重油吗？当然不是，是入联公投熄火。很快，我们就可以看到中国和美国一起玩一把“口头
对口头、行动对行动”的游戏——只要“台海三通”有突破，朝鲜弃核肯定有实质性的进展。如果谁想耍滑头，大家手里都有一把乱牌，愿意较较劲就请便好了。
    入联公投的局势跟踪到此为止了。我也连续的盯了一周的局势了，累，休息几天。回头见！

 ******************************************

    今年将是中央全面整顿吏治的一年，所以我说“全面发力了”。可能许多朋友都不相信。其实，十七大以前我写文章分析房价必降也没几个人相信，现在再
说房价会降有没有人怀疑呢？其实，我得结论的出发点是政治——中国是一个大国，人口大国，中国的人口比美国、日本、欧盟、俄罗斯加起来都要多，管理这
样一个国家是非常不容易的。既要保持稳定，又要解决问题，胡温真的很难，很难。好在经过五年的艰苦努力，他们成功的控制了局面，无论是国内，还是国
际。但是，他们依然需要并且绝对需要所有有正义感的中国人的支持。

    其实，中国的经济运行远不象媒体上宣传的那么好。甚至可以说是非常的糟糕。在这里，我只列举一组宏观数据，大家就可以看出来：

    都说中国改革开放的成绩举世无双，可懂经济的朋友都知道，只要一国经济强势增长，其货币汇率必然坚挺、升值。这一点，无论是从理论角度，还是实
践检验，都证明是正确的可看看我们的人民币呢？人民币的汇率从1978年（1：2.8）开始，到2005年(1:8.3)总体上是一路跌，当然，从1994年的1：8.7到
2004年的1:8.3的确是有所升值，但这是在1994年从1：5.7暴跌到1：8.7之后的小幅反弹，可就是这4.6%的小幅反弹还花了11年的时间——与其说是这11年人民
币在升值不如说11年前跌的太狠。如果说中国经济发展的奇迹真的让世界敬仰的话，为什么我们的汇率那么不给面子呢？

    同样的问题，为什么最近两年人民币能升值？因为胡主席从2003年开始制定的创新型国家战略经过三年的打基础之后开始发威了，中国企业的整体竞争力
开始增加了，所以，这两年人民币敢升值了。

绝对支持胡温！

    声明:经考虑，我决定退出奋进社。原因如下：做为一个社团，奋进社自成立以来从未以社团名义做过一件事。名为社团，实则各自为战，如一盘散沙。
成员之间的沟通协调远远不够，平时极少在一起交流，特别近两个月，从未集体交流过一次。当然，这也是没办法的事情，大家都是业余写作，还要工作和学
习，可支配时间太少。

    另：经过八个月的努力，对国际局势的把握已有一定的根基，故从现在起，我工作之余的主要精力、充电的方向将转向“金融-银行-股市”和“产经-财税-
企管”两条线(同属经济范畴,一虚一实)。以后，关于国际时局的评论将会继续写，不过数量会有所减少，因为个人精力有限，望朋友们见谅。
    同时，欢迎朋友们在我的博客里跟贴讨论问题，欢迎朋友给我提供更多的资讯，这对我写评论也大有帮助。从你们这里，我也可以学到很多东西。我将尽
可能的及时的以跟贴的方式答复朋友们提出的问题，也希望能提供答案的朋友们跟贴回答其他朋友的问题，大家一起讨论。这样也能让我的博客显得有生气一
点——我不喜欢死气沉沉的感觉。
    希望朋友们多参与，少潜水。谢谢！
