# -*- org -*-

# Time-stamp: <2011-08-04 18:06:25 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent


* 【金鸿评论】冷眼旁观马英九

  
    金鸿:看一下我们官方的态度,与国台办的声明并不矛盾。中央的定性是公投通过是变相台独。如果通不过则另当别论。不过，不得不说的是，我们赢得很
惨，那些杂种的擦边球打得很厉害，非常的恶心人。不过，他们的招数也不过如此了。不是吗？有本事动真格的呀？昨天美日的态度还不够明显吗？美国摆出
一副无心插手的架式——小鹰号只带一艘驱逐舰，日本更是自己卸链子——海上自卫队参谋长关键时刻给撤了。当然，在我们窝火的同时，敌人的色厉内荏和外强
中干也表现的淋漓尽致，所以，无论如何都不能说我们输了。只是我们还不够强大，还没有取得压倒性优势。最后说一句，爱国是好事，但不要冲动，大局为
重。
 
    新华网台北３月２２日电　陈水扁当局不顾海
内外强烈反对而执意推动的所谓“入联公投”于２２
日举行，因投票人数未达总投票权人数的一半，投
票率仅３５．８％，公投未获通过。公投结果说明
，“台独”不得人心。同时举办的由国民党所提出的
“返联公投”投票率仅３５．７％，同样因投票人数
不足而未获通过。                            

****************************                

    中台办、国台办就陈水扁当局公告举办“入联公投”发表受权声明。声明全文如下：

    ２月１日，陈水扁当局不顾两岸同胞的强烈反对和国际社会的谴责，公然决定于３月２２日举办所谓以台湾名义加入联合国的公投。 
    陈水扁当局执意举办“入联公投”，是谋求改变大陆和台湾同属一个中国的现状、走向“台湾法理独立”的重要步骤，是变相的“台独公投”。这一图谋一旦得
逞，势必严重冲击两岸关系，严重损害两岸同胞的根本利益，严重危害台海地区乃至亚太地区的和平。

    大陆和台湾同属一个中国。任何涉及中国主权和领土完整的问题，必须由包括台湾同胞在内的全中国１３亿人民共同决定。我们十分关注“入联公投”事态
的发展。陈水扁当局一意孤行，铤而走险，必将付出沉重代价。

    两岸同胞是骨肉兄弟，根本利益是一致的。两岸之间的矛盾和分歧完全可以在两岸关系和平发展过程中通过平等协商加以解决。我们真诚希望广大台湾同
胞认清陈水扁当局举办“入联公投”的险恶用心和必将给台湾同胞带来的严重后果。只有坚决遏制“台独”冒险行径，才能维护两岸关系和平发展的前景，才能维
护台湾同胞的福祉，才能维护台海地区和亚太地区的和平。

*********************************************************

    马英九当选了。马英九道底是何许人物呢？我们通过大选前十余天台湾发生的一些新闻来看一下吧：、
 
1、    原本立场深绿的“全民计程车队”大转向，将于十日上午集结二千多辆计程车，在二重疏洪道现场宣誓支持马英九，并由台“立法院长”王金平代表一一
授旗。“全民计程车队”2004年台湾“大选”前，曾发动会员力挺陈水扁连任。
 【简评】深绿的选民没变,他们支持的人就是台独分子,马英九穿的是蓝皮,可戴的是绿帽。
 
2、　　中新网3月8日电据台湾《联合报》报道，台湾地区领导人选举第二场政见发表会昨晚举行，国民党候选人马英九场边频咳嗽，民进党候选人谢长廷认
为马不是故意的；政见结束时，两人握手，谢伸右手握，左手掌举向马，马忙说不会拍背，谢称是要跟马“击掌”。
 
 【简评】宁做真小人，不做伪君子。可马先生为了引导选民的想象力，非要拿“背”做文章。真不会拍背吗？鬼才相信。相比之下，谢长廷倒显得象个实在人
。

3、    台“立法院交通委员会”今天邀请台当局“交通部”针对“远航财务危机”提出项目报告。会上，国民党“立委”江连福爆料，根据台湾“华航”内部的相关评
估报告，陈水扁有可能在“520”之前利用松山机场离台。他要求台当局“交通部”要“守好机场”。对此，台当局“交通部”及“民航局”相关负责人都表示不知情，
并强调相关的评估都是公开信息。

 【简评】现在丑化陈水扁是为什么？为整个民进党抹黑而已。暗助马英九上台的把戏！

4、    中新网3月12日电据台湾《中国时报》报道，台湾“大选”进入决战期，国亲展现大团结气势，国民党候选人马英九和亲民党主席宋楚瑜、国民党主席吴
伯雄十一日晚间在花莲首次同台造势，现场涌入二万五千多人，首次为马站台的宋楚瑜，带领台下群众高呼“冻蒜”(当选)口号，呼吁支持者票投马英九。

 【简评】这个不蓝不绿的宋楚瑜也被马英九收编了，小马岂有不赢的道理？当年国民党大败不就是败在这个宋先生带队出走上吗？

5、    中新网3月12日电据台湾媒体报道，陈水扁昨天评估“大选”选情时表示，马英九不是稳赢，谢长廷也不是稳输，最后一周常有机会逆转胜。陈水扁强调
，他曾说三月二十二日前要退居幕后，不是因为“立委”选差，也不是谢叫他退，而是本来就应以候选人当主角。对于近来参加“公投苦行”等活动，他称作是“
做暗的”、“顾内场”，默默帮忙奔走。

 【简评】看看小扁多不容易，还“做暗的”，生怕别人不知道？生怕别人不会联想？为了搞一张逃生机票还真不容易，掩护小马上台是他的美国主子赋于他的
历史使命。

6、　　据台湾“中广新闻”报道，国民党台北市党部准备周六(15日)，在凯达格兰大道举办“扫贪腐、迎接新台湾”集会活动，邀请上万妇女一同走上凯道扫贪
腐。

 【简评】做秀！有时间去给我家扫扫院子我还领你个人情呢，扫腐？扫个鬼！

7、　　中新网3月14日电前民进党籍“立法委员”陈道明涉嫌在2004年“立委”选举期间，以每票新台币五百元不等的金额向选民买票。台湾“最高法院”13日驳回
上诉，维持台“高等法院”更一审判决，判处陈道明一年八个月有期徒刑，并科罚金新台币五十万元，褫夺公权四年。全案定谳。

 【简评】现在给买票的判刑在攻击谁还不是明摆着的吗？

8、　　中新网3月14日电据台湾TVBS报道，受谢长廷竞选总部冲突事件影响，国民党原“立法院”党团书记长费鸿泰，继前晚请辞书记长一职后，今天上午又召
开记者会宣布退出国民党，以示负责。费鸿泰宣布，从现在开始自动退出国民党，不希望因为个人关系，影响到马英九的选举及国民党的形象。他哽咽地说，
如果马英九因为这一事件导致落选，无法打垮贪腐政权，“我不排除结束生命。”

    国民党“大选”候选人马英九今天上午九时在总部召开记者会，对党籍“立委”前往谢长廷竞选总部抽查引发冲突的行为，再度进行公开道歉。

    中新网3月20日电 3月12日谢长廷总部蓝绿阵营冲突事件的主角之一、国民党“立委”陈杰，在事件发生一周后，昨天(20日)首度现身说明事件始末。他说
，当天电梯停在维新馆(谢长廷竞选总部)三楼突然停住，并听到谢总部人员打电话动员时，才知道“中计了”，但因电梯电源被切掉而无法脱身。

【简评】从这一连串的爆料来看，这次冲突不是蓝营的错，既然如此，马英九为何一再的道歉？谦谦君子而已。

9、　　中新网3月17日电台当局“教育部”主任秘书庄国荣16日以不堪入耳的脏话攻击马英九已过世的父亲马鹤凌，引发台下群众骚动，庄国荣后向杜正胜口头
请辞但并不道歉。庄国荣失言风波绿营忧冲击选情："一人抵四傻"

 　　中新网3月18日电因爆发“粗口风波”而黯然下台的台前“教育部”主秘庄国荣，虽已发表声明向马英九家人致歉，但负面效应仍持续发酵。

 【简评】这是帮民进党的忙吗？纯粹是帮倒忙！又不是三岁孩子，能是无心之言？背后支持马英九的势力可以手眼通天，蓝绿通吃。

10、　　中新网3月17日电台联党中执委罗志明今天在国民党主席吴伯雄陪同下，宣示挺国民党二00八“大选”正副参选人马英九及萧万长，说明他的“三个理由
、三个期待”，同时宣示不会加入国民党，以免被某政党抹黑。

 【简评】这个罗志明好样的，牵过驴还不够，再送一程，好样的！

11、　　中新网3月20日电据台湾TVBS 报道，陈水扁19日表示“卸任不会把‘政权’交给有绿卡的人”，对此，马英九回应并重申绿卡早已失效，也强调520一到
，陈水扁依法必须走人。
 
 【简评】一副新领导人的口气！
 
12、　　中新网3月20日电据台湾中时电子报报道，国、亲两党合并的进程有具体进展。国民党主席吴伯雄昨天(19日)和亲民党主席宋楚瑜通电话。宋楚瑜同
意“大选”后国亲合并，但强调他个人不要任何位子。吴伯雄则说，国民党还是会用最“尊崇”的方式迎接宋楚瑜；至于要给宋楚瑜什么名衔，他将向国民党荣誉
主席连战请示后决定。
 
 【简评】宋楚瑜也不简单，怕国亲合作之后脸白心黑的人清洗掉，先给自己留后路了，不过，有用吗？
 
12、　　中新网3月21日电民进党籍台南市议员王定宇服务处，昨天上午接获恐吓电话，对方扬言要赏给谢长廷一颗子弹，警方立刻组成专案小组，昨晚逮获
一名蔡姓男子，依法送办。
 
【简评】生怕别人忘记了民进党几年前那点丑事，再专心提醒一下！ 

13、　　中新网3月21日电台湾中华视听传播基金会董事长许安进20日号召逾百位地下电台业者挺马英九，坚决反对选举前的任何“奥步”(烂招)。谈到艺人江
霞最近的言行，许安进笑着说，大家都有表态的自由，但请不要攻击别人。

【简评】实在没什么好说的了，用“一朝被蛇咬、十年怕井绳”做解释好象说不过去了。
 
14、    台海网3月22日讯 17时59分，在台北的马萧竞选总部自行宣布马萧当选。
 
