# -*- org -*-

# Time-stamp: <2011-09-14 20:43:56 Wednesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent



*** 井底望天

*** 占豪

*** 会同天下

*** 【金鸿95】被冤枉的毛主席

按照西方经济学精英的说法，毛主席不懂经济。

如果按照政治经济学的概念，经济是指社会生产关系的总和。毛主席带领着中华民族在一穷二白的基础上建立起了完全独立自主的经济体系，这个体系是除了美国苏联没有第三家的，这还不懂经济？英国法国日本没有一家能做到的，那他们的领导人懂什么？

其实，吃饭穿衣是最基本的经济。说到这里，有人就会说“毛主席时代挨饿”云云。其实，真要为中国人解决吃饭穿衣问题、让中国人过上好日子、为中华民族的长远发展打上好基础的，恰恰是毛主席。

拿吃饭来说吧，离不开袁隆平的水稻。而袁隆平是从1964年开始研究杂交水稻的。1973年实现三系配套，1974年育成第一个杂交水稻强优组合南优2号，1975年研制成功杂交水稻制种技术。 1975年冬，国务院作出了迅速扩大试种和大量推广杂交水稻的决定，国家投入了大量人力、物力、财力，一年三代地进行繁殖制种，以最快的速度推广。1976年定点示范208万亩，在全国范围开始应用于生产。1976年是毛主席他老人家离我们而去的那一年，所以，让中国人吃上高产稻与他无关了。跟着毛主席挨饿也就成了毛主席永远也摘不掉的帽子了。我不知道，说这话的人良知哪里去了——吃着人家的还骂人家，这样的人还算人吗？

毛主席是我们共和国的缔造者，连他都敢冤枉，那些人还有什么事不敢做？

再举个例子：2007年英国金融时报报道有科学家把1978年以前中国经济的发展速度统计了一下，发现66年至76年的文革，工业生产仍继续在以平均每年超过10%的速度增长（1966年国民生产总值年均递增10.7%，只有67、68年稍有减少，分别递增9.8%和9.9%，到了69年年均递增16.9%，70年比增19.4%）。金融时报还评价上个世纪全球最大规模，最成功的工业化是在中国，而同期世界的增长速度是3％。中国人的统计造假，西方人的统计总不能不信吧？既无内债，又无外债，还没有通货膨胀，这样的发展水平，居然是不懂经济的人干的！

还有一点大家需要知道：70年代中国是世界第三科技强国。这句话没有丝毫的夸张。今天的歼10、神舟、094全是1980年以前的东西，不相信的可以去查阅相关资料。有谁敢想象，在1976年以前，中国技术人员的比例和绝对数量都是世界第一的？其实，这个道理是明摆着的，那些年创造了多少“第一，那不全是人干出来的吗？没有足够数量的技术人员，怎么可能出那么多的成绩？今天的中国是什么？世界工厂，专门干组装的。没有技术含量的活全让我们干了。为什么？因为我们没有技术。我们发展的真好！幸运的是，胡总温总看透了问题，现在不是提出转型不做世界工厂了吗？按照西方经济精英的分工理论，这可是绝对错误的！

到底谁懂经济？又是谁不懂经济？

我以前写过几篇批判西方经济学的文章，同样被西方经济精英斥为“不懂经济”。其实，到底谁不懂经济？我把底捅出来可能会让所有人晕倒：那些经济精英，没有一个知道“经济”是何物的。

至今为止，在西方经济学中，经济一词还没有一个明确的定义。所以，他们对经济学的定义也处于混乱状态。下面19个句子都可以看作是经济的“定义”：

1．经济是指财富； 

2．经济是人类和社会选择使用自然界和前辈所提供的稀缺资源； 

3．经济是指利用稀缺的资源以生产有价值的商品并将它们分配给不同的个人； 

4．经济是指人类生活事务； 

5．经济是指把稀缺资源配置到各种不同的和相互竞争的需要上，并使它们得到最大满足； 

6．经济是指将稀缺的资源有效的配置给相互竞争的用途； 

7．经济是指个人、企业、政府以及其他组织在社会内进行选择，以及这些选择决定社会性稀缺性资源的使用； 

8．经济指社会管理自己的稀缺资源； 

9．经济是指我们社会中的个人、厂商、政府和其他组织进行选择，这些选择决定社会资源被利用； 

10．经济是指在经济活动中确定劳动、资本和土地的价格，以及运用这些价格配置资源； 

11．经济是指金融市场行为，金融市场将资本配置到其他经济部门； 

12．经济是指收入分配，以及不损害经济运行的前提下对人给予帮助； 

13．经济是指政府支出、税收、预算、赤字对经济增长的影响； 

14．经济是指经济周期中失业与生产的波动，并改善经济增长的政策； 

15．经济是指各国贸易模式贸易壁垒的影响；

16．经济是指发展中国家的发展，资源有效利用的方式； 

17．经济是指一定社会生产、交换分配和消费等经济活动，经济关系和经济规律； 

18．经济是指有限资源在不同用途上的运用； 

19．经济是指资源配置的全过程及决定影响资源配置的全部因素。

我想，看到这里大家可能都晕了。那些所谓的精英，懂“经济”的天才们，居然自己都说不清什么是经济！这可真是天大的笑话。这可是一门研究了200多年的高尚科学！真不知道他们在研究的什么！

其实，这也不是笑话，西方经济学就是这样的，在关键的必须搞清楚的地方，混沌的很，在大家都明白的地方，他们的分析却能让人大开眼界，大呼“非已之所及也”。这样的理论有什么用？

不要说我给他们扣帽子，在经济理论中最关键的几个问题：为什么会暴发经济危机、出现通货膨胀的原因、经济发展理论、汇率如何决定、金融危机为什么会暴发，这些关键性的问题上，没有一个能得出明确答案来的，都有上百种理论在那里摆着。对于那些无关紧要的东西，倒是搞出大堆的理论！这又有什么用呢？科学是解决现实问题的，可这门所谓的科学，一个关键问题解决不了。反而弄出上百种假说，搞得人头晕脑胀。学它有什么用？当然，有人总结过两个定律：经济学家第一定律：对任何一位经济学家而言，一定存在着一位实力旗鼓相当的同时观点又针锋相对的经济学家。经济学家第二定律：他们都是错的。 如果你真正学过西方经济学，你会发现，这两个定律是千真万确的。

还有一个讽刺西方经济学家的笑话是这样说的：一个人问：“经济学家干了什么？”回答是：“短期看他们干了很多，长期干他们什么也没干。” 这个笑话形容的恰如其分。

其实，“经济”是个很简单的东西，说穿了就是 *经世济民* ，就是 *民生* 。解决人民生活需求的。为什么西方经济学不给它下一个明确的定义呢？西方经济学的全名叫 *西方资产阶级经济学* ，它是为资产阶级服务的，不是为普罗大众服务的，如果把这个底兜出来了，不就穿帮了吗？

过多的我就不多写了，在文章的最后，我只想问那些西方经济精英们一句：“既然别人都不懂经济，那你们懂不懂？如果懂，请你们告诉我什么是经济好不好？骗子吗？”



附：自即日起，我再发文章将不再发往各大论坛。

*** 史评:谁是中国的千古一帝?

写在前面：发了上一篇时评,我提出一个观点:我相信我们胡总是千年一遇的人物。有许多人不以为然，甚至说我歌功颂德。说实在的，一开始出来写时评，就是有感于胡总温总的奋发有为而人不知，国家民族命脉所系，我希望能通过文章来尽自己的一点绵薄之力。不然，每天花这么多时间写东西又没有回报，我吃饱了撑的？今天就比较一下中国有作为的帝王，大家一起看看，我的评价有没有道理。
 
在金鸿个人眼里，中国历史上最有作为的领袖人物有三个：李世民，毛主席，胡总。其实，在个人的论坛里，也转贴过两个写李世民和毛主席的贴子，今天呢，以对比的方式，看看金鸿的判断是否正确。

先谈一下李世民。

世人对李世民抨击最厉害的地方有两点：玄武门之变和李世民收了李元吉的妃子。

玄武门之变无疑是一场惨烈无比的宫廷喋血。但是，如果我们换一个角度来看这个问题呢：如果李世民没有发动玄武门之变，那么天下会是谁的？十有八九会是李元吉的，当然，李元吉会先伙同李建成干掉李世民，自己再干掉李建成。李元吉的野心，在史书中是早有记载的。如果李元吉统治了中国会怎么样？如果李建成没有被李元吉杀死自己统治了中国又会怎样？他们两个谁有能力搞一个贞观之治出来？就这二位的水平，恐怕连汉朝的文帝景帝都比不了。还有一点，我们不能不承认，几千年的封建史中，为了争夺皇位而发生的宫廷杀戮多如牛毛，几乎是历朝历代都有，可以说，这是我们的民族性决定的，都是中国人，为什么要苛求于他一人呢？

再就是纳妃之事。其实，李世民不但纳了李元吉的妃子，还收了隋炀帝的萧皇后。在此，金鸿想提醒大家一点：李世民身上一半的血统是蒙古贵族的，在当时的蒙古，可汗中有“妻群母”的传统。这样的环境中，出现这样的事情，不是很正常吗？任何人都不可能脱离具体的社会环境而存在。其实，李世民执政其间，曾大规模的放出过宫女，他的后宫的女人与历朝的皇帝相比，是少而又少的；而大规模放出宫女的行为，在中国的封建史中，是不多见的。

也有人说，打天下的是李渊。其实，李渊造反，最早的谋划者是李世民，李渊自己在造反开始时也对李世民说过：“今日破家亡躯亦由汝，化家为国亦由汝矣！”

至于李世民的水平如何，我们看隋未起义的四巨头（李密、世民、王世充、窦建德）中一开始被人认为夺取天下最有希望的李密的评价吧：李密投降李渊后，见到李渊，“自恃智略功名”，脸上“犹有傲色”，可他一见李世民后，“不觉惊服”，私谓殷开山曰：“真英主也！不如是，何以定祸乱乎！”至于王世充和窦建德，是李世民一战而全擒的，他们没有不服气的理由。窦建德在被李世民抓了后更是说了句俏皮话：“今不自来，恐烦远取。”

李世民偃武修文的政策，有了天下太平，也有了四海归化。这一点比起把老子留下的家底全打空了的汉武帝刘彻，强了千倍。（当然，刘彻时也有外患怙恶不悛的原因，不得已而为之,但就治理天下的水平而言,刘仁兄是没办法与李世民相比的,看看他那些无用的丞相吧）

其实，看一个人如何，不必看他本人如何，看他做器重的人、与他关系最密切的人就足够了。只要这些人素质过硬，人品高尚，这个人绝对是素质过硬、人品高尚。李世民打天下时，最倚重的文臣是房玄龄、杜如晦，定天下后，最倚重的是魏征，而这三位是历史上少有的贤臣。其实的文臣如：虞世南、褚亮、姚思廉、李玄道、蔡允恭、薛元敬、颜相时、苏勖、于志宇、苏世长、薛收、李守素、陆德明、孔颖达、盖文达、许敬宗，还有闫立本、褚亮等人，至于武将，如李靖、尉迟敬德、秦琼、程知节、李世赜等等，人才济济。历代少有。

在中国历史上，吏治最清明的时代只有两个：一个是贞观之治，另一个就是49-76毛主席时代。这两个时代，几乎没有贪污犯。

另外，李世民是中国历史上最开明的帝王：中国封建史上唯一一个不“抑商”的皇帝就是李世民，正因为如此，才有了唐王朝的繁荣昌盛。当然，李世民的开明，还表现在他对“异已”的宽容。 资治通鉴中有这么一段记载：有刘恭者,颈有“胜”文,自云“当胜天下”,坐是系狱。上曰:“若天将兴之,非朕所能除;若无天命,‘胜’文何为!”乃释之。   如果这件事发生在康熙时代，恐怕这个姓刘的要被诛九族了。

既然这里比较到了康熙，就顺便谈一下吧：许多人认为康熙乾隆不得了，金鸿不以为然。先说一下十全老人乾隆，他的作为就象他的诗，一辈子作了数万首，可惜无一传世，治国也是如此，好象大有作为，其实，了了。康熙似有作为：平三藩、收台湾、剿葛尔丹、抗沙皇。其实，中国真正落后于世界，就是从他开始的。比较一下与康熙同时代的两个帝王吧：沙皇彼德大帝、英国伊丽莎白女王。英国从伊丽莎白开始了工业革命，走上了日不落的征服世界之路；彼德励志改革，走上了沙俄领土扩张之路。相比之下，康熙又如何呢？

如果有朋友对李世民感兴趣，可以看一下金鸿转贴的《中国历史上唯一没有贪污的半个王朝 》http://blog.sina.com.cn/s/blog_3fe443f701000bvk.html
   

下面再简单谈一下对毛主席的一点看法：毛主席是人类历史上前无古人的政治家，如果硬要找一个来比较的话，华盛顿或可一拼。但是，华盛顿有两个大错：一是把国家的货币发行权交给了私人银行，今天的美国，已不是华盛顿、杰弗逊、 富兰克林所努力构建的那个自由民主的国家了，一切都变味了，其错误就在于此。二、华盛顿对印弟安土著的杀戮可谓灭绝人性，这一点，决定了他从“道德”的角度无法让世人满意。

毛主席人品如何？看看周总理和朱总司令就知道了。这二位是毛主席的左膀右臂，至死不渝的支持者，而毛主席也从未抛弃过他们。“道不同，不相为谋”。如果不是同道之人，会如此吗？

至于十年文革，时间会还世人以真相的。

利已主义、享乐主义、无ZF主义已将今天的国人腐蚀的差不多了。中华民族是一个没有国教的国家。没有国教，可以摆脱迷信，但是，有两个致命的缺点：一是普通人没有是一个无形中支撑他的精神支柱，从而无法坚守道德底线；二是放纵了许多人的无法无天，他们已为“老老大、自己老二”，当然，死之前呢，又怕自己会下十八层地狱。这些，恰恰是没有崇拜的致命弱点----欧美国家有国教，是有道理的。

这里有一篇写主席的文章《一次又一次地震撼了整个世界的伟人 》，有兴趣的朋友可以看一下：http://blog.sina.com.cn/s/blog_3fe443f701000cb1.html
 

最后说一下我们胡总:的确,胡总执政只是五年,可他身上表现出了许多只有在李世民和毛主席身上才有的特质，所以，金鸿以自己的眼光坚定的相信，我们胡总，也是能震悍千年历史的人物！

最后，引一条新闻：   

*中国为确保守住十一五期间18亿亩耕地的红线，暂停了1600万亩的退耕还林计划。日前，国务院发布关于完善退耕还林政策的通知。通知提出，为确保“十一五”期间耕地不少于18亿亩，原定“十一五”期间退耕还林2000万亩的规模，除2006年已安排400万亩外，其余暂不安排。*

看来,我一周前的<调查>并非杞人忧天,中央今天的行动证明了一切.也感谢在各论坛和我博客里积极跟贴提供支持的网友们!现重发一次调查的原文如下:

=我发现了一个现象,现在国内许多农村的农田都改成经济林了.我询问过许多朋友,这种事全国许多地方都有.甚至有的地方因为种树多绿化率大幅提高被环保部门表彰.站在地方ZF的角度看,这是好事,有利于农民创收提高收入.但是,如果全国大范围的这么做,中国的粮食产量将出现下降,如果再遇上天灾,那么,也许中国会出现粮食危机.一旦出现粮荒,则人心动荡,如此时再起谣言,必有大麻烦.民以食为天呀.挣钱是好事,但吃饭最要命.所以,上面有关部门最好查一下这事,让经济林控制在一定范围内.再结合以前出现的拿粮食做乙醇的事，这是有人在拿粮食做文章呀！希望大家跟贴也说说自己当地农村有没有上面提到的事，看看这事的范围到底有多大．希望这是我的杯弓蛇影，庸人自扰．=

 
最后希望那些天天在网上没事找事乱攻击的人网友一句:有时间干点人事吧,不要再做那些让人笑的蠢事了.


*** 【奋进社/金鸿95】中国的全球战略

写中国的全球战略，不得不从美国写起。因为美国是中国最大的敌人，而中国也是对美国霸权威胁最大的国家。

*中国的全球战略目标，自然是打倒美国的霸权。* 问题是，我们该怎样做，才能达到这个目标呢？要打倒美国的霸权，首先必须明白，美国霸权的命门在哪里。

*美国霸权的命门，就是美国的金融霸权，* 美国的超强军力是为美国的金融霸权服务的。美国的金融霸权，第一表现就是美元是世界通用货币，第二表现就是美国掌握着全世界大宗商品的定价权。

美元之所以牢固的占据着世界通用货币的位置，是因为美元跟石油捆绑在一起。说到美元与石油的捆绑，不得不提巴以和谈。美国是通过控制巴以和谈来保证美元与石油捆绑在一起的：

美国通过以色列时刻威胁着中东产油国家的安全，而美国对以色列的支持是全天候的。因为没有一支全面抗衡美国人的力量在中东，所以，受着威胁的阿拉伯国家不得不也倒向美国，以求在美国的庇护下获得国家安全上的保证。当然，美国人是收保护费的。美国人要的保护费就是阿拉伯国家的石油用美元结算，然后阿拉伯国家必须把通过出口石油挣得的美元重新投资（和花费）到美国。这样一看，阿拉伯国家完全是美国的“奶牛”。同时，美国利用伊斯兰逊尼派与叶什派的矛盾，通过拉拢阿拉伯国家来围剿叶什派国家，实现自己独霸中东的梦想。

美国就是这样把美元和石油死死的捆在一起的。石油作为最重要的战略资源是任何一个国家都须臾不可离的。借着石油这种战略资源，美元成了全球通行的货币，世界各国也主要以美元为储备外汇进行国际结算。美国因此而获得的好处是无法估量的：首先就是美国人通过过多发行美元造成美元贬值（全球性的通货膨胀）以引发世界财富的重新分配----直接表现就是各国储备的美元价值“缩水”了，这也相当于美国向全世界人民征了税。另一个重要好处就是美国通过操纵石油价值来达到掏空某些国家经济、保卫自己世界第一强权位置的作用。在这一点上最经典的案例有两个：一个是1973年放手让美元疯长400%，狠剪了一把发展中国家的羊毛，二个是压低油价、残酷打击苏联经济最后导致苏联解体。

所以，美国要想继续始终保持自己的世界第一强权的位置，必须牢牢的控制住中东，把石油和美元死死的锁在一起。而想到打倒美国霸权的唯一办法，也是把石油和美元分割开。 *要想让石油输出国家改变用石油结算的现状，就必须为他们提供安全保护。* 现在的中东在美国人的保护之下，这些国家不用美元结算行吗？现在伊朗的石油已经改用欧元了，就是因为中俄为伊朗的国家安全提供了保护；而当年小布什之所以下决心推翻萨达姆政权，也是因为萨达姆想把出口的石油改为欧元结算而又没有国家能保护的了他。

现在，不光伊朗，叙利亚也处在了中俄的保护之下了：2007年12月26日，中国中东问题特使孙必干与叙利亚外长穆阿利姆会晤时，孙必干宣称，中方支持叙利亚收回戈兰高地的正当要求，希望早日重开叙以和谈。这就是中国最明显的态度。支持叙利亚收回戈兰高地就意味着中国愿意卷入叙以纠纷、得罪以色列和美国，保护叙利亚的国家安全。只要中俄在中东的军事影响力越来越大，愿意接受中俄保护的国家将不仅仅是逊尼派国家，阿拉伯国家也会产生这样的“想法”。

当然，有“想法”是一码事，付诸行动是另一码事。如何能让阿拉伯世界把“想法”变成行动呢？办法只有一个，就是让他们看到跟着中国（也包括俄罗斯）能得到好处。如果叙利亚能在中俄的支持下，顺利的重开叙以和谈并得到相应的好处（类似的，中俄正在做准备工作的还有黎以和谈），因为在巴以和谈上迟迟看不到欧盟为他们争得正当权益，产生另攀高枝的冲动将是不可避免的。

其实，一开始，中国俄罗斯是寄希望于在巴以和谈中从美国手中分权的，只不过，美国选择了宁可对欧盟让步，决不对中俄松口的做法。等得不耐烦的中俄只好自己准备谈判桌了。也好，中俄比美国要大方，一开就是两桌：叙以、黎以和谈。谁敢说只有欧洲人关心中东和平？——美国在中东花大力气搞的是“中东民主”，欧盟向中东国家推销的才是“中东和平”。接下来，不管是通过新开的两桌谈判替叙利亚、黎巴嫩捞得好处，还是迫于中俄在场外的压力而威逼以色列对巴勒斯坦让步，都会被阿拉伯国家及时的捕捉到，并增加向中俄靠拢的决心。

只要中东产油国家一个个的站到了中俄这边，中俄就可以有步骤、有次序的让这些国家与美国慢慢的脱钩。当然，中东国家石油不用美元结算了，会先改成欧元，这也是欧盟求之不得的，也是欧盟一直在努力做到的一点。这样还可以激化美欧之间的矛盾。面对着直打自己七寸的欧盟，美国人一定会全力反击。另外，因为中国持有巨额的外汇储备，可以时不时的拿着这笔巨资是多一点美元还是多一点欧元做文章，在美欧中间灵活的跳一下摇摆舞——只要中国动作一大，同样拿着大把美元储备的日韩印等国家肯定跟着做动作。这样可以从经济金融层面给中国也不时的捞一点油水出来。而俄罗斯也可以趁乱做一下出口石油用卢布结算的工作，跟着拆一下美元的墙角。

只要这样努力下去，把美元与石油彻底拆分了家，美国人耀武扬威的日子的就结束了。当然，打倒美国霸权是一个系统的工程，不是仅平几条妙计就可以做到的。

我们必须在以下六个方面做好扎实的工作：

1、科技上赶超。只要美国是世界上科学技术最先进的国家，它就永远是世界的领袖国家。要想把它赶下领袖的座位，科学技术方面必须赶超它。以我们中国人的创新能力，只要坚持独立研发，二十年内全面赶超是可以实现的。

2、政治上顶住。在国际斗争中，必须坚决顶住美国的压力，保护所有朋友的利益，寻找一切机会打击美国，包括愿意充当其走狗的国家。在联合国，无论是中国俄罗斯，还是法国，该动否决票时坚持不要客气。

3、军事上压住。狗急了跳墙。把美国逼急了，它肯定会找机会发动战争以扭转局面。所以，要坚决打击美国的一切军事冒险意图。只要美国敢动手，必须坚决回击。只有充分的准备战争，才能防止战争的发生。

4、经济上拆散。充分联合一切可以联合的力量，拆散美国的经济势力范围。APEC必须拆掉，把日本、韩国和东盟拉离美国的势力范围。在美国的后院也要狠挖墙角。在非洲，更要想办法把美国人顶出去，因为非洲有资源和廉价的劳动力。不要以为美国的那些大企业有多么多么强的竞争力，只要把美国的经济势力范围掏空了，美国的那些巨无霸级的企业会统统破产。一句话，把美国商人赶回美国本土去！只要美国的企业不行了，美国的军事、科技、金融就基本歇菜了。

5、金融上掏空。用石油欧元在中东排挤石油美元，人民币、卢布、日元居中策应。

6、实力上消耗。利用伊拉克和阿富汗两个战场全力消耗美国的有生力量。美国一时半会下不了撤出阿富汗的决心，因为美国一撤，上合就在伊朗、巴基斯坦、阿富汗连为一片，直逼中东。美国在中东的压力将会更大。只要美国从阿富汗一撤，土库曼斯坦将全面投入上合，阿塞拜疆也会“学习土库曼好榜样”，吉尔吉斯斯坦呢？乌克兰呢？所以，在阿富汗美国必须死扛。伊拉克的情况也差不多。只要美国一撤，伊拉克的石油一桶也没有美国人的份。签了的合同又如何？照样废掉！有本事再打回来！伊朗也会更加的无法无天，叙利亚也会学着伊朗的模样装大爷。阿拉伯国家还在乎以色列？个个都会往中俄的怀里钻。

只要这些方面都做到了，打倒美国霸权不在话下。接下来的欧盟就要容易对付的多——一个政治上不统一、军事上不够强大的组织是成不了世界霸主的。既使中国不收拾它，俄熊也会啃了它。欧盟到头来只会落个给别人做嫁衣裳的下场。当然既(即)使知道这个下场，它仍然会在中东狂拆美元墙角，因为如果不这样做，它亏的更多。



既然写中国的全球战略，就不能不回顾一下中国过去的全球战略是如何执行的：

我们的人民共合国刚刚建立，美国就侵略朝鲜、直逼中国。毛主席带领着中国人民抗美援朝、保国卫国。一战下来，打出了中华民族的尊严，打出了中华民族的生存空间。

1959年，中苏分裂。中苏分裂的真实原因是：艾森豪威尔上台后，变美国的战略从“遏制”为“大规模报复”，一切跟核战争挂钩，放弃过去认为在有限战争中不应使用核武器的想法，决定只要军方认为军事上需要就可以使用核武器，面对美国以核优势为后盾的“大规模报复”战略和“战争边缘”政策，苏联决定“缓和冷战”。 1956年2月的苏共二十大就提出了“和平共处”、“和平过渡”总路线。这实际是要求已经当政的共产党不要得罪美国，没当政的共产党（包括当时没统一的越南）别再走暴力革命的道路。潜台词：既然“一颗小小的火星就可以引起核大战”，那象抗美援朝那样的麻烦今后不能沾，免得惹火烧身，为了你的国家统一把我苏联拖进核战争。 

这样一来，中国收复台湾、维护领土完整和统一的民族利益就跟苏联的冷战需要矛盾了：要统一台湾就必须反掉美国的干涉。经过麦卡锡主义肆虐、顽固坚持冷战理论、敌视中国的美国坚决拒绝跟中国做任何妥协，甚至根本不承认中国政府，只承认在台湾的蒋介石当局代表全中国。最典型的事例就是1954年日内瓦会议上杜勒斯拒绝与周总理握手——敌视到这个份上，怎么“缓和”？即使中国放弃统一台湾美国都不会答应，更不用说中国坚持收复台湾了。毛泽东面临的问题是：是为苏联的冷战需要而牺牲中国的民族利益，放弃收复台湾的努力，还是为中国的民族利抵制苏联的冷战需要？毛泽东“咬定青山不放松”——咬定中国的民族利益绝不松口。这才是中苏决裂的根本原因。

在一般人看来，当时的中国实在是毫无希望了：外有强敌，内乏粮草，压力空前巨大，处境极端艰难，“黑云压城城欲摧”。中国既没有力量对抗苏联，更没有力量对抗美国，又没有办法劝说美苏改弦易辙改变对中国的敌对态度。

在这个中华民族面临空前危机的时刻，毛主席使出了他最得意的国际斗争谋略：中苏论战+抗美援越。具体的做法是：支持越共中央武装统一越南；《毛泽东选集》第四卷出版，指出 “帝国主义和一切反动派都是纸老虎”，要和美国打“人民战争”、“持久战”；批判苏联对美投降、背叛马克思主义。

毛主席这一下子同时戳到了美苏两家的痛处：美国苏联都是在自己阵营里当老大的主，最怕的是镇不住台。美国惟恐被看成“纸老虎”而众叛亲离，决心不让南越垮掉，马上跳进了越南战争的泥潭，从此越陷越深。这下苏联也坐不住了：袖手旁观、任凭美国肆意欺负“社会主义大家庭”的成员北越，那“龙头老大”的面子何在？威信何在？还保得住“社会主义阵营领袖”的地位？于是不得不援助越南对抗美国。而且为了证明自己才是正牌的社会主义阵营的盟主，不但援越，而且专给中国当时给不了的先进武器。——抗美援朝时中国的先进武器都得自己花钱向苏联买，买回来自己学着使用，然后再自己费尽心血送上前线去拼命。现在倒好，毛泽东一个“中苏论战”就让苏联一个子不要还卯着劲地白给，给的还净是当时中国给不了的好玩艺，还不劳中国人冒险，由老毛子亲自出马送货上门把着手教越南人使用，或者直接派人操作——这等于无偿帮着中国实现“让美国吃个史无前例的大败仗，使美国自己得出结论：跟中国敌对没有好处，不得不有求于中国”的战略总目标。这下中国可省大发了：有人心甘情愿倒贴着白帮忙还不用领情——我不谢你，你也不觉得是在帮我，连“聒噪”两字都省了，代价不过是“中苏论战”的一通笔墨官司——世界上还有比毛泽东的这招阳谋更巧妙更合算的买卖吗？苏联这一上劲，美国更不敢无限制扩大战争了：要扩大，是扩大到中国还是扩大到苏联？结果：战争一直老老实实局限在越南，使越南战争变成了一场符合毛泽东理想的时间、理想的地点、理想的方式的理想的人民战争，没有扩大到中国。再加上中国是在指责苏联背叛马克思主义，对美国搞投降，这种指责本身就使苏联清楚中国没打算和美国联手对付自己。如果放着越南不管却跟美国伙在一起收拾中国，就没法证明自己是“正统马列主义者”和“国际共产主义运动的领袖”，所以既下不了决心也没有借口立即进攻中国。毛泽东巧妙地利用了美苏矛盾，限制了战争扩大，争取了时间，使中国得以加速备战、加快“两弹一星”、开展三线建设，使自己的安全有了切实的保障。

美国几十万大军陷在东南亚的沼泽里无法自拔，苏联则趁机大举扩张，在全球到处挖美国墙脚。美国此时突然如梦方醒：上了毛泽东的大当了。原来美国真正的要害利益不是在东南亚的烂泥潭里，而是在中东和欧洲；真正威胁美国利益的不是“好战”的中国，而是美国以为“可以有共同利益”的苏联。美国敢情被毛泽东诱进了越南战争的沼泽地白挨揍，如同老牛掉进井里——有力没处使，进不得退不得，眼睁睁看着苏联坐大而无可奈何。如果还不顾一切继续在越南硬抗到底，就等于自我了断，把世界霸权拱手让给苏联。不管是谁当美国总统，借他八个胆他也不敢走到这一步。 

1969年尼克松上台后宣布美国从越南撤军，使战争“越南化”，通过谈判取得“体面的撤退”—— 不管你南越是死是活，反正我美国得走人了。我走后你南越有本事就靠自己活下去，没本事就听天由命。我真正关心的是别一垮一大片，弄得我管也不是不管也不是。只要美国脱身后只垮掉一个南越，那就谢天谢地，就算“体面的撤退”了。

1972年尼克松访华，向毛主席登门求和。既然有求于毛主席，那就不得不满足毛主席开出的价码。最终结果：美国解除对华封锁和外交孤立政策，承认一个中国、台湾属于中国，支持恢复中国的联合国席位和常任理事国地位、联华制苏。从此，世界政治力量的格局开始从“美苏两极世界”演变为“美、中、苏”三极的“新三国演义”。（毛主席时代的中国战略部分系摘抄黎阳先生的《如何看毛泽东时代》一文，在此提出感谢。）



可惜的是，这时的毛主席，年世已高，没过几天就离我们而去了。毛主席刚刚过世不久，奇怪的一幕马上出现了：中国开始韬光养晦了！刚刚打完八年抗战时，中国遍地废墟，毛主席没有韬光养晦；刚刚建国时，中国一穷二白、内外交困，毛主席也没有韬光养晦。为什么在毛主席刚走、中国外交形势一片大好的时候却要韬光养晦？

韬光养晦的结果是什么？有两个标志性的事件可以说明一切：国内方面，运10下马；外交方面，美国国会通过了《与台湾关系法》。从运10下马开始，中国开始了“以市场换技术”的道路。自主研发哪比的了引进技术快！结果呢？还是拿大飞机来做例子吧，如果不是胡主席执政，今天支线飞机能不能下线还是个未知数，更不要提大飞机了。国有企业先是搞合资、合作，最后干脆大甩卖。还是毛主席留下的底子厚，二十多年都没卖光。仅此一点，说毛主席不懂经济的人就得统统闭嘴！至于那部严重侵犯中国主权、干涉中国内政的《与台湾关系法》，就更不用提了，如果毛主席他老人家在世，就算美国国会的议员们拿枪顶在卡特（当时的美国总统）的脑袋上，他也得把国会刚刚通过的那部《与》法给否决了！——一面有求于中国要急着跟中国建交，一面还敢对中国内政指指点点？也是美国人时来运转，中国开始韬光养晦了！我们一路的韬光，一路的养晦，直到有一天，我们的大使馆都被人炸了，这时，国人猛然发现，再养下去中国就完蛋了！



天佑中国，胡主席上台了。05年3月14日，《反分裂国家法》通过。那时，胡主席刚刚带领中国人民走出了非典的阴影，稳住了阵角。《反分裂国家法》是一部《与台湾关系法》迎头撞车的法律。美国人通过《与》法来干涉中国内政、给台独势力打气、并随时准备在美国人需要的时候挑动台独搞独立以打断中国的经济建设进程。《反》法则迎头撞来——除非美国人真的敢于为了台湾跟中国打一仗，否则就不要再给台独分子发错误信号了。所以，我们有幸看到了一幕非常有趣的场面：美国众议院以424比4通过决议案，敦促布什对反分裂法提出严重关切——如此压倒性多数通过决议案愣是连个“反对”都不说，不是“纸老虎”是什么？从此，再也听不到美国人开口闭口的把《与》法挂在嘴上了。

从这时起，胡主席带领着中国人重新开始了征服世界的道路（对此，我们不必隐晦，任何一个国家都希望征服世界，我们为什么就不可以呢？）。为什么如此看重《反》法呢？道理很简单：如果我们的内政都能随随便便被人指点，我们又凭什么让我们的朋友依靠我们、敌人惧怕我们？我们连保护好自己的能力都没有！所以，当《反》法强硬通过的时候，就是我们胡主席向全世界宣布“当年打得美国佬满地找牙的中国人又回来了”的日子。

从此以后，中国的全球布局有条不紊的展开了：

1、东亚方向：用《反》法捆死了美国的台湾政策；把朝鲜纳入自己的保护范围，支持朝鲜经济发展和东北亚经济一体化、离间韩美关系；推动“东亚核竞赛”，直至06年用朝鲜核暴全面离间日美关系；加快推动东南亚经济一体化，把东盟做成中国的“后院”。

2、北亚方向：完善上合功能，全面深化中俄联盟，中国支持俄罗斯政治上、军事上对美强硬、经济上俄罗斯允许中国布局中亚，努力实现为上合成员国及其前苏联国家的全面经济捆绑。

3、西亚方向：与巴基斯坦全面捆绑并以此为跳板跳入中东；对印度既拉且打，军事上威慑、经济上拉拢，分裂所谓的“美印日澳同盟”；大手笔投资伊朗与伊朗捆绑、跳入直到控制伊核会谈进程，至到今天准备以伊核问题为桥头堡全面插手中东和平进程。

4、非洲方向：全面深化与非洲国家的联盟关系，经济上进一步融合，政治上加大对非洲盟友国家的支持。

5、欧洲方向：经济、科技层面加深合作，政治上加强协同，努力建立抗美统一战线。

5、美洲方向：毫不客气的与俄罗斯欧一起插手美国后院，当然，中国欧洲以经济布局为主、俄罗斯以军事政治为主（包括卖军火）。

透过这些，我们可以依稀看到了毛主席的影子——胡JINTAO同志接过了毛主席的枪。



  
*** 【奋进社/金鸿95】西方经济学的陷阱

——一篇推翻凯恩斯主义的经济论文

与只凭想象说话的微观经济学相比，西方经济学中的宏观经济学理论还是有一定科学性的。为什么那些经济学精英们不再坚持用分析微观经济的思路来分析宏观经济呢？道理很简单：如果经济学精英们希望他们的理论能上得“庙堂”，就不得不在许多地方“从实际出发”，而不是一分析问题就 “假如假如”的云山雾罩一翻。但是，宏观经济学同样存在着许多陷井，是我们不得不防的。现在把它们揪出来，以示世人：



+ 一、过时的萨伊法则：



200年前，萨伊提出了被西方经济学界奉为经典的"=萨伊法则="，即供给会创造出自己的需求，换句话说就是“生产会自行创造销售”。

这一观点正确吗？恐怕大家会说，不一定。因为在今天的市场竞争中，有太多的企业由于销路不畅、库存积压而导致资金链断裂、企业不得不破产，所以，现实并不支持“生产会自行创造销售”的观点。

不过，如果我们换一个角度看，萨伊法则又有它非常科学的一面。这个观点是1803年提出来的，当时的欧美国家都处于卖方市场。在卖方市场条件下，萨伊法则是基本正确的，至少没有明显不符合经济社会现状的地方。欧美国家进入买方市场是150年以后的事了（中国经济进入买方市场是1995年以后的事情）。我们可以拿中国经济作例子简单看一下卖方市场的一个事实：年纪大一点的人应该都还记得当年的“布票”、“肉票”吧？这些“票”就是卖方市场现实下厂家生产产品供不应求的一个真实写照，在这样的现实之下，“生产”当然“会自行创造销售”，就怕你生产不出来！

萨伊和李嘉图以萨伊以萨伊法则为基础得出一个重要推论：所有商品都生产过剩的经济危机是不可能的。应该说，这个推论没错：在卖方市场条件下，怎么可能出现全面的生产过剩呢？如果出现了，那就是买方市场了。从这里就可以看出萨伊法则的局限性。很显然，这是一个过时的理论。而 *现代的西方的宏观经济学就是建立在萨伊法则基础上的* 。

一栋建立在沙子上的大楼谁敢住？

19世纪初，美国福特汽车公司通过推行流水线和科学管理大规模降低生产成本，确立了在汽车市场上的霸主地位。成功后的大老板福特曾经傲慢的说过一句话：“我不管顾客需要什么颜色的汽车，我的汽车只有黑色的。”这句话把生产厂商在卖方市场上的强势地位清晰的描绘了出来，当然，这也是一句实话，如果不是因为福特汽车都是“黑色的”，它也成不了霸主——大规模标准化生产以降低成本从而确立自己在汽车市场上的成本领先优势正是福特汽车的成功之道。但是，随着汽车市场从卖方逐渐进入买方市场，仅仅一个“黑色的”汽车外壳已满足不了顾客追求个性的要求，福特公司却没有及时跟上顾客需求的变化。这时，小斯隆当上了美国通用汽车公司的总经理。他采取了事业部制来对通用汽车公司进行管理，注重满足顾客的个性化需求。于是，通用汽车公司迅速超过了福特汽车公司成了汽车市场上的新领袖。成也“黑色”的福特在市场竞争中落得了个败也“黑色”的结果（当然，福特制、科学管理理论和小斯隆的事业部制都是划时代的企业管理理论）。从这个例子可以看出，生产厂商在卖方市场和买方市场上的表现完全不同。

宏观经济学也支持这样的观点：宏观分析的投资需求是一定时期的单个厂商或企业的投资汇集而成。单个的厂商（或企业）的投资心态都发生了变化，宏观分析的投资需求能不也跟着发生变化？既然现实都变了，理论为何不“与时俱进”？我们都知道“刻舟求剑”的故事。在那个故事中，那个找剑的傻子只不过是坑了自己而已。现在，打着“科学”、“经典”旗号的经济学精英们又是在坑谁呢？他们可是在对我们的宏观经济政策指指点点！

鉴于凯恩斯的宏观经济模型同样以萨伊法则（S=I）为基础进行推导，所以对萨伊法则的错误推导不得不再做一点更深入的剖析：

萨伊法则的等价命题是：任何数量的储蓄都会全于变为投资（S=I），其实，这一点是否成立，有两个关键的因素必须考虑到：一、萨伊认为货币只有“价值尺度”和“交易媒介”两种职能，这与事实远不相符。现实经济生活中，货币至少还有一个“价值贮藏”的功能，这就意味着，在社会上会有一部分钱存在“既不消费也不储蓄（投资）”的状态。二是在部分准备金制度下，银行系统有创造货币的功能（存款乘数）。由于这两个因素的存在，决定着萨伊法则是错误的（即S≠I）。

需要指出的是：萨伊的理论尽管与今天的经济社会状况不相符，在他本人生活的那个时代，萨伊的理论还是有其合理性的。比如，货币的“中性”观点（货币供应量的多少及其增减变化，对于实物领域即商品总量及其构成以及各商品的交换比率等三个方面没有任何影响，货币及其数量只决定商品价格的名称及其绝对水平），在当时社会也是合理的。因为那个时代处于金本位时代，几乎没有通货膨胀。进入廉价货币（纸币）时代则不然，刻意的增发纸币必然引发通货膨胀，货币当然也就不再呈现“中性”。从这个意义上说，萨伊比起一代宗师凯恩斯来，还多了一点学者的良知。





+ 二、凯恩斯骗局：



凯恩斯号称西方经济学史上的革命性人物，其形象一直光辉无比。今天的经济学精英们，多数为凯恩斯的徒子徒孙。可是，他的理论是一套彻头彻尾的骗局。下面一一列举：



1、掩盖真相的“工资刚性”

“凯恩斯革命”推翻了萨伊法则关于宏观均衡的国民收入和就业量必然是充分就业的教义，作出了“工资刚性”的假设。即货币工资在一定时期内固定不变，这不同于萨伊法则关于劳动市场是完全竞争这一前提。在完全竞争条件下，只要存在失业，工人之间的竞争将迫使货币工资下降。而凯恩斯认为，在现实生活中，工人坚持不肯降低的是货币工资，有些失业工人，在货币工资不变物价上升、从而实际工资降低的情况下也是愿意就业的。很显然，凯恩斯的假设是有悖于常理的。难到工人们都是自欺欺人的傻子：五毛钱两个的鸡蛋不买，专买二毛五一个的？

当然了，象凯恩斯这种天才，既然做出了这种假设，肯定有他的目的。从他的“工资刚性”假设本身自然看不出他的目的，他的目的体现在他由此而推导出的经济政策主张里。他的政策主张是：降低货币工资，现实上或政治上难度很大，而通过增加货币供应以提高物价，从而降低实际工资，既简便易行，又可得到减少失业的效果。从这里，我们应该看到：降低货币工资在实际生活中是很正常的，失业工人之间的竞争必然导致工资下降。前几年不是传出过有大学毕业生为了进去好一点的公司就业而不要工资的吗？凯恩斯却说“难度很大”，很显然，他在说谎。他说谎的目的是什么？就是“增加货币供应”！

在金本位下，增加货币供应是很难行的通的，因为只有“上帝”才能制造黄金；那么，怎样才能增加货币供应呢？自然是用廉价货币（即纸币）。但是，在“凯恩斯革命”之时，英国正从金汇兑本位向不兑现纸币本位过渡的时期。由此可以清楚的看出凯恩斯“闹革命”的目的了：为廉价货币政策张目！

不过，在廉价货币通流的情况下，过度的增发货币必然导致通货膨胀而造成社会财富的重新分配。如果发行货币的银行归国家所有，那么，普通老百姓可能不吃亏，因为国家可以通过自己手中掌握的过多发行的货币来对老百姓进行补贴，在这种情况下，甚至可以促进社会收入分配的公平化。但是，如果银行掌握在私人手里，那时，增发货币就意味着变相掠夺普通老百姓的财富。说到这里，大家应该明白了，“凯恩斯革命”是在从理论上对私人银行家的掠夺行为合法性进行辩护。

事实上，凯恩斯年青时就已经认识到了通货膨胀的巨大的危害：没有金本位的情况下，将没有任何办法来保护人民的储蓄不被通货膨胀所吞噬。凯恩斯本应该是金本位的坚定拥护者，为何后来将黄金贬低为“野蛮的遗迹”、鼓吹廉价货币理论？因为他也是“理性人”，也要实现个人收益的最大化。当然，凯恩斯“理性”的结果，就是红的发紫，紫的发黑。



2、欺骗世人的消费函数

凯恩斯的消费函数C=a+bY是其宏观经济模型中的一个非常重要的函数。但是，这个消函数并非统计归纳的结果，也不是根本先验的假定进行推演的结果，只是以偶然观察为依据；而另一消费函数C=bY是对经济事实统计归纳的结果。美国经济运行的事实数据证明，凯恩斯的消费函数C=a+bY在短时期内（比如十年）是与事实吻合的，但是，如果把考察的周期加长（比如七十年）来观察，则凯恩斯的消费函数并不正确，正确的函数形式为C=bY。

为什么会出现这样的情况？

其实，短周期的消费函数之所以是C=a+bY而长周期的消费函数C=bY的原因很简单：每个周期之间通过以严重的经济危机出现的年份为断点（关于经济危机成因的讨论在后面部分），而每次严重的经济危机都造成了强烈的社会财富再分配效应（我个人认为用这个名称比较合理、姑且这么形容）——经济危机本身是大资本家、大银行家来打劫中小资本家、银行家、其他中产阶级和普通劳动者财富而制造出来的经济崩溃状态。正是因为社会财富在经历过了严重的经济危机上进行了重新分配，才造成了消费函数的突变。如果没有恶性的经济危机的存在，那么，无论是短周期，还是长周期，其消费函数都是一样的，即C=bY。我们国家不存在因恶意的通货紧缩而出现的经济危机，所以，我们做宏观经济分析时，应该用C=bY这个函数而不是凯恩斯的那一个；当然了，计划经济时期（1950-1978年）的消费函数可能与1978年以后的不一样，这是很正常的事情，因为经济体制不一样。

当然，在凯恩斯的推理中也有破绽：

按照凯恩斯的分析，人们的消费支出与其收入之间具有一种稳定的函数关系：收入增加消费支出也会增加，但消费的增量小于收入的增量。凯恩斯的消费函数就是以此为基础导出的。但是，如果仔细看一下上面凯恩斯的观点，大家会发现，凯恩斯的消费函数应该用二次函数才是科学的（一阶导数为正，二阶数为负），而凯恩斯故意用了一次函数来描述消费函数，这一点显然与“经济学精英们”一贯以“科学严谨而不怕麻烦”的风格制做经济模型的做法不相符。这是为什么？道理很简单，二次函数与现实经济运行根本无法吻合，所以他不得不用一次函数来代替（把二次函数Y= -ax2+bx+c中的-ax2项去掉，并对bx+c两项进行重新修饰）。

现在我们就不得不多长个心眼了，即然年轻时的凯恩斯就发现了通货膨胀的危害、最后却替那些制造通货膨胀的人辩解，为什么他就没有发现这个消费函数存在的问题呢？就算他没有发现，他的那些徒子徒孙们难道就没有一个人去怀疑过吗？对于这个问题，有必要深思一下。凯恩斯关于“消费的增量小于收入的增量”的观点包含着一个道理，就是消费不足导致的有效需求不足是必然的，而有效需求不足的必然性意味着失业存在的必然性。而且，随着经济的发展，消费的“萎缩”会越来越严重——失业也会必然增加，严重到一定程度就是经济危机。——真相出来了，凯恩斯用自己的理论（包括消费函数公式）为世人洗脑：经济危机是必然的，不是人为的！——这样体贴资本家们心思的“精英”怎么会不红？怎么可能不是一代宗师、革命性的人物？只要资本主义制度存在，资本家们肯定会把凯恩斯的理论奉为《圣经》。

按照凯恩斯的说法，消费函数C=a+bY中的a为自主的消费，即收入为零时也会有消费。乍一看，这是正确的，对个人而言，即使失业也要消费，再一想，对一个社会而言，如果所有人都不工作，同样也需要消费，所以a是存在的。但是，事实果真如此吗？如果一个社会中的所有人都不劳动（收入为零），他们需要的消费品是谁提供的？难道是从天上掉下来的？对一个经济体而言，只要有消费存在，必要意味着有等量的收入（劳动）存在。消费和收入是一枚硬币的两个方面，不可分割。所以，现实中，不可能有那个可恶的a！（同样的道理，凯恩斯的税收线性函数、进口线性函数也都是错误的，两个函数都没有那个固定不变的常数项。）

可笑的是，某些西方经济学精英们为了把凯恩斯“偶然观察”出的函数与事实吻合起来，煞费苦心的搞了一大推的“收入假说”（包括绝对收入假说、相对收入假说、恒常收入假说等）。现在，这些“假说”应该改成“假话”了。

当然了，不能不说的是，凯恩斯确实是个“精英”，谎言编造的如此高妙，利用对人类直觉的欺骗来蒙蔽世人，的确不简单。可惜，再狡猾的狐狸也逃不过猎人的眼睛。



3、胡编乱造的货币需求模型

按照凯恩斯的观点，人们对货币的需求有三种动机：交易、预防和投机。投机动机的意思是，人们之所以愿意持有不能生息的货币，是因为持有货币可以用来买卖投机性的债券（即政府永久公债）。

如果不考虑购买公债的利息收益，站在公众整体的角度看，购买公债进行投机是一种零和博弈，有赚钱的就有赔钱的，今天所有人都赚钱了明天就会有大批人赔钱。但是，如果考虑利息收益，对公众整体而言，购买公债是一种投资行为。这和买股票是一样的，从个人角度看是投机行为，从公众角度看是投资行为；而且股票的涨跌规律和公债是完全一样的，都是“市场价值与利率成反比例变化”。

当然了，按照经济学精英们的观点，公债利息不能计入GDP，只能算是“转移支付”，因为取得利息收入的人没有提供相应的物品和劳务。但是，这只能是精英们的一厢情愿罢了。公债、股票和储蓄对公众而言，都是投资­——储蓄也是投资，只不过是通过银行间接进行的。如果硬要说这三种投资有什么区别的话，那就是他们的风险和回报率不一样。需要强调的是，储蓄行为是投资行为不代表公众储蓄额等于社会投资额。

公众购买公债是为了获利，但是，公债是永不偿还本金的（凯恩斯即以此为前提进行的分析）。所以，我们看到的事实是，公众中始终有一部分人持有债券（准备高价抛售债券以获利），还有一部分公众持有“投机”货币（准备低价购买债券以便在高价时出售获利）。这一点和股市上股民的整体情况是一样的，也是有人持股有人持币；和厂商的流动资本也是一样的，一部分已变成了消耗品、工人工资等，一部分做准备金；和公众出于交易动机持有货币也是一样的，一部分已购买了消费品，一部分做准备金。所以，凯恩斯所谓的“投机动机的货币需求”应该分成两部分：一部分是投资，归入储蓄(S)；一部分是准备金，归入交易动机的货币需求。

现在，我们可以清楚的发现，货币的总需求就是货币的交易需求。如果用“货币的供求与利率的决定示意图”表示，在任一时点上都是一条垂直于横轴的直线。而货币当局决定的货币供给在任一时点上，也是一条垂直于横轴的直线。现在，是不是有的朋友感觉到迷茫了？——在货币需求量与发行量不同时，两条直线是不相交的；因为他们是平行线，无论利率如何变化，都不会相交。这该如何解释？其实，这才显示出现实经济世界的本质：如果货币发行量大于需求量，就意味着出现了通货膨胀；如果货币发行量小于需求量，则意味着出现了通货紧缩；只有货币发行量等于需求量，才意味着经济运行中既没有通货膨胀也没有通货紧缩。因为货币发行是货币当局决定的，所以，不论是出现通货膨胀还是通货紧缩，都是“人祸”，而不是因为那只“看不见的手”。

现在，大家应该明白了，凯恩斯为什么要弄出一个“投机动机的货币需求”了。如果不把货币需求直线搞成曲线，如何与货币供给线相交？如何隐藏通货膨胀的实质？其实，把“交易动机的货币需求”与“投机动机的货币需求”相叠加以得出“货币总需求”是没有道理的，这就象一个人告诉你：“我今年30岁，上过4年大学，所以我今年34岁。”你一定会回应他三个字：“神经病！”

明白了上面的事实，也就更容易理解为什么会冒出个 “流动性陷阱”来了。现实中哪有什么流动性陷阱，只有“凯恩斯陷阱”！

凯恩斯对“流动性陷阱”是这样表述的：在现行利率很高（比如10%）时，人们预期日后的利率只跌不涨，则投机性货币需求为零；而在另一极端即利率最低（比如2%）时，人们预期利率只涨不跌，此时人们必将卖出债券以持有货币，由此，货币当局在公开市场活动中收购债券所增加的货币供应量，必将全部被公众作为价值贮藏手段保存在身边，这就是流动性陷阱。下面看一下凯恩斯表述中的破绽：

第一，流动性陷阱与现实不相符：当利率最低时，人们如果真的都认为债券价格以后只跌不涨而卖出债券（在理性人的假设下）时，就会出现集体抛售的局面，这时，债券价格必然会在极短的时间内暴跌，这种情况可以叫恐慌性抛售。这时，抛售者面临的选择只有两个：一是深度被套，如果是这样，就意味着无法象凯恩斯那样上嘴唇一碰下嘴唇就把债券换成货币；二是割肉抛售，如果是这样，能换回多少货币？又会损失多少货币？凯恩斯也没说。当然了，有人可能会说，货币当局会大量吃进债券以维持债券价格稳定。现实会如此吗？如果货币当局是私人的银行家，他们会“学习雷锋好榜样”吗？如果货币当局是为社会公众服务的，由于并不是每个人都在买公债，如果货币当局这时大量吃进公债就是在帮助一部分人止损，那没买公债的人不就亏了吗？货币当局做这样的买卖合理吗？

第二，就算是货币当局通过某种只有“上帝才有的能力”在公债价格非常平稳的情况下把公债买了过来，社会上存在的公债总量也是有限的。在这样的情况下货币需求曲线怎么又会变成了与横轴平行的直线？它应该是一个点才对！在这个点上，公众手里只有货币，没有公债。也就是说，在此时，货币当局继续增发货币，根本就没有公债可以从公众手里收购。现在，大家应该明白了凯恩斯不去确定公债总额的原因了：如果确定了公债总额，他又如何任意解读“无论货币当局如何收购公债以增加货币，都会被公众当作价值贮藏手段保存在身边”，并造成一种货币需求可以无限增加的假象？他又如何解释货币当局严重过多发行货币造成货币供给量线与货币需求线无法相交的情况？现在好了，因为“流动性陷阱”，货币需求线可以平行与横轴并无限延长，就算货币当局造成10000%的通货膨胀，都可以蒙混过关了！

——好不精明的凯恩斯！敢玩弄世人的凯恩斯！一代宗师就是这个德行？难怪后世的经济学精英也是这个德行！因为有一个好榜样！

在此也顺便说明一下为什么07年中国的通货膨胀如此严重：有太多的“热钱”通过地下钱庄或者其他非法渠道进入了中国，并兑换成了人民币，所以，中国经济体中的货币就比实际的货币需求量增大了，即货币过量发行了，所以通货膨胀出现了，这也是06、07年中国外汇储备不合比例的高速增长的原因。出现这样的通货膨胀也不是我们的政府愿意看到的，因为“热钱”不是走的合法渠道，所以不在我们的央行控制之下，这也是06、07年中央狠查地下钱庄的原因。只有非法流入“热钱”的渠道堵死了，才不会出现我们的央行被动过量发行货币的现象——只要有美元进入了我们的储备体系，我们就得发行等价值的人民币进行兑换。

第三，既然买公债可以算投机动机，那买股票同样得算投机动机。现实经济生活中，在利率非常低的时候，公众往往更多的把钱投到股市上去，造成股市的暴涨。这时，“流动性陷阱”如何解释？

由于凯恩斯的货币需求模型是编造的太不合情理，所以，在以此为基础进行分析时，闹出了大笑话。在《宏观经济学》教材（注：本案例是从复旦大学出版社出版的《西方经济学》第三版一书中照搬的，该书作者为宋承先、许强。）第191页中有一个关于“货币的供求是怎样从失衡趋向平衡”的例子，内容摘要如下：

前提：利率为6%，此时人们自愿持有的货币为1050亿元（交易动机1000亿元投机动机50亿元），利率为4%时投机动机100亿元，利率为3%时投机动机150亿元。

现在，假设当前利率为6%，而货币供应为1100亿元，下面看一下凯恩斯大佬是如何把“失衡”搞“平衡”的：在此时（人们手中有100亿投机货币）人们会将多余的货币购买债券，由此引起债券价格提高、利率下跌，直到利率跌到4%为止（此时货币总求增为1100亿元，恰好等于既定的货币供给）。同样的推理，假设当前利率为3%，其他条件不变，在此时，公众愿意持有的投机货币是150亿元（大于手中的货币100亿元），人们将卖出债券持有货币而引发债券价格下跌、利率上升，直到利率升到4%为止（此时货币总求增为1100亿元，恰好等于既定的货币供给）.

现在，可以看到那个大笑话了：在利率为6%时公众明明是在花钱，花钱花得利率都跌到4%了，而利率降到4%时公众手里还有100亿元的投机货币。公众花的是谁的钱？怎么花不花的就不见少呢？在利率为3%时（公众此时手中有100亿投机货币）公众明明在卖出债券持有货币，为什么利率升到4%时公众手中还是只有100亿的投机货币？卖债券得到的货币哪儿去了？

至于凯恩斯分析的三种均衡利息率的变动情况（供币供应量的变动、收入水平的变动、投机性货币需求的变动）问题就更多了，多得我实在懒得去批判它。如果朋友们有兴趣，可以自己去批判它一下。

由于凯恩斯的货币供求与利率均衡理论是错误的，在此基础上推导的IS-LM模型自然是错误的。



4、、倒因为果的AD曲线

凯恩斯在推导总量需求曲线AD时，是以货币供给量不变为前提，假设“物价水平变化”，来观察国民收入是如何变化的。很显然，这是一种倒因为果的分析方法。在经济社会中，国民经济的运行是通过商品交换进行的。商品交换则是以货币为媒介，货币的正常流动代表商品交换的正常进行。所以，货币在经济体中的流动是因，全体劳动者创造的国民收入PY（即国民财富）是果。用公式表示就是MV=PY。在正常运行着的经济体中，货币供应量（M）没有变化，货币的流通速度（V）是没有道理发生突变的。这就象是一条在正常的流动着小河，在水量（可比作货币供应量）没有增加的情况下，河水流速（可比作货币流速）怎么会出现加快的情况呢？如此一来，国民收入又怎么会发生突变？物价水平又如何会发生突变？凯恩斯的这个假设是没有任何道理的！

现实情况是：国民收入不变，货币供给量增加则物价水平提高，货币供给量减少则物价水平降低。货币供给量与物价水平是水与船的关系，水涨（货币供给量增加）则船高（物价水平提高）。反过来则不成立——如果说水没涨船却高了，这可是天下最大的怪事了！船是怎么高上去的？这可不是市场那只“看不见的手”能办得。到的，只有依靠“上帝之手”了。

当然了，如果硬要说一下AD曲线的道理，那就是：（对任一条AD曲线而言，）在使用同一货币的不同经济体中，在相同的货币供应量条件下，在不同的物价水平时，对应的国民收入也不同。重新强调一遍，它只能指的是不同的经济体。

至于总量供给曲线AS，就更是胡说八道了。在这里凯恩斯故意把由于增发货币而引发的通货膨胀和成本上涨混为一谈。增发货币而引发的通货膨胀对经济而言是恶性的，因为这样会掠夺公众的财富（如果央行是全民所有的则可通过补贴弱势群体促进社会分配公平化）；成本上涨则是良性的。

下面解释一下为什么说生产成本上涨是良性的：

在一个国家，不同企业之间的劳动生产率（生产力水平）都是不一样的。一般说来，生产率最高的企业的工人工资是最高的，而同行的生产率较低的企业的工资也不会比生产率最高的企业低太多，因为如果差别太大则优秀员工会大量流失造成企业破产。如此一来，生产率较低的企业的生产成本就会比较高。随着一个国家整体生产力水平的提升，所有企业的工人工资都会跟着提高，生产成本也会跟着提高（生产率先提高的企业先涨以吸引人才，生产率落后的企业不得不跟着涨工资）。对于生产型的企业如此，对于提供服务的企业更是如此。比如饭店，社会生产率是否提高对工饭店服务员的工作效率几乎没有什么影响（如端盘子的服务员），可他们的工资依然会跟着整体社会的整体工资水平不断提高，就是这个道理。

这种生产成本上涨是良性的。如果生产率提高了而所有工人的收入没有提高，因生产率提高而多生产出来的商品由谁去消费？生产是需要消费来拉动的。生产持续扩张而消费能力不足会影响经济增长。如果一个国家的劳动生产率不断提高而生产成本始终都没有上涨，倒是说明这个国家有问题了。当然，有人可能会说，成本上升出口会受阻。这倒是正确的——也正是因为这个原因，随着一个国家生产率的提高，出口产品的技术含量才会越来越高。

而凯恩斯又意识的把成本上涨与通货膨胀混为一谈，给狼披上了羊皮，居心何在？通货膨胀是指货币过量发行，而成本上涨是因为工人收入提高。二者绝对不是一回事。

因为AS、AD曲线都是错误的，所以，凯恩斯的宏观经济模型是毫无价值的。至于那些精英们用AS-AD曲线分析出来了的形形色色的通货膨胀理论，全部都是骗人的鬼把戏。

从逻辑性方面来看，凯恩斯的《通论》（即凯恩斯的革命理论）完全可以说是胡编乱造。一套理论编得如此糟糕还能成为正统的理论，确实是大本事。时势造英雄，一点都不假。在此，我也正告中国经济教育界的爱国学者们，到了编一本逻辑上讲得通的经济学教材的时候了。



三、西方经济学的狭隘性



受制于西方经济学分析问题的出发点，即“如何实现个体最优化”，精英们在分析宏观问题时，总是容易犯下“差之毫厘，缪以千里”的错误。下面通过一个被凯恩斯写进了现代西方宏观经济学教科书的案例来看一下西方经济学的狭隘性，这个案例就是“节俭的佯缪”。

勤俭持家，节约储蓄，在任何社会都是个人的美德，但是，按照西方经济精英的说法，对一个社会而言，这种观点往往不成立。他们的理由是：假如一个社会还存在着发展生产的潜在能力，在这场合，假如每家每户都节制消费，产品会因缺乏需求而表现为生产过剩，由此导致社会生产进一步减少和个人收入下降、收入减少，生活水平下降，而且，这一动态过程是累积性的恶性循环，最后会引发经济危机。这个经济分析号称是经过“上世纪30年代的经济危机检验的”。事实果真如此吗？

拿中国经济做例子吧。从1952年到1978年26年间，中国的国民经济平均增长速度是6.5%（当时的世界经济平均增长速度只有3%），这一速度是任何一个国家都无法项背的。这26年的时间，中国在一个连造罐头的马口铁都得靠进口的落后的农业国基础上建立起了一个拥有完整工业体系的强大国家。中国的工业体系之完善，除美俄两国之外，再无第三国可比。不得不强调的是，那时中国绝大多数年份处于被封锁状态，没有外来投资，全靠中国人民苦干实干。当然，我们的收获都是货真价真的：没有通货膨胀，没有内债，没有外债，不卖资源，不恶化环境。但是，在那近三十年的时间内，中国人民吃不好、穿不好，举国上下无比节俭，也正是因为如此，直到1978年，中国的轻工业企业并不发达。如果按照“节俭的佯缪”的观点，近三十年的“恶性循环”下来，中国经济应该空前危机才是，可为什么那时的中国经济没有表现出一丝一毫的“恶化”迹象？是精英们错了还是中国错了？

其实，这个道理很简单，只不过，那些眼里只有“个体最优”的精英们永远都不会懂。还是让我这个只学了十八天宏观经济学的门外汉给他们上上课吧。

的确，生产是靠消费需求来拉动的。如果消费需求萎缩则生产规模也发展不起来。不过，消费需求并不只包括个人消费需求，还包括社会需求（或者称集体需求），比如兴修水兴、改造农田、修桥筑路等等（这都是毛主席给我们打下的好基础呀），社会需求的旺盛同样会拉动生产的高速发展。这才是我们的共和国建国28年来重工业发展迅速、国民经济高速发展的原因。也不怪那些精英们不懂这个道理，他们眼里哪有国家利益、民族大义？只有“私人利益的最大化”。在他们眼里，失业率能降到4%就是奇迹了，他们哪能理解当时的中国零失业是如何实现的！正在因为他们太“理性”，才会有“公地悲剧”：一群牧民在一块公共草场放牧。一个牧民想多养一只羊增加个人收益，虽然他明知草场上羊的数量已经太多了，再增加羊的数目，将使草场的质量下降。牧民将如何取舍？如果每人都从自己私利出发，肯定会选择多养羊获取收益，因为草场退化的代价由大家负担。每一位牧民都如此思考时，“公地悲剧”就上演了－－草场持续退化，直至无法养羊，最终导致所有牧民破产。——这个道理还不简单吗？有便宜不赚王八蛋。在精英们眼里，这居然是合理的！



综合起来，我们可以得出结论， *西方经济学中的微观经济学完全是一套建立在虚幻假设基础上的、没有实用价值的理论，是一套为掩盖资产阶级剥削行为的实质的理论。宏观经济学则是一套淡化资产阶级剥削行为、并帮助大资产阶级掠夺广大百姓利益的理论。* 那些西方经济精英都是在替资本家做辩护，没有一个是为老百姓说话的。所以，当他们从嘴里再吐出不象人话的惊人之论的时候，一律板砖伺候！

*** 简介

：毛主席领导中国，也不过27年；而主流们统治中国,已经30年了.结果主流们成天埋怨毛主席一直影响着中国，人民也总是想念毛主席。一个污染、负担如山、血汗工厂、崇洋媚外的中国，人民怎么可能不想念毛主席?到今年，中国改革开放已经30年了。在这30年里，据说“政策完全正确”，而且也取得了“举世瞩目的伟大成就”。当然可能吾运气不好，成天看到的是污染、负担如山、血汗工厂、崇洋媚外什么的，就是吃点肉也担心有毒或者造假，总之就是感觉不到主流们鼓吹的好处。主流们为了一个奥运会花费了几千个亿，却不肯拿出一点来解决物价、房价问题。请问如何让人民喜欢?当然，吾这样的草民，主流们是不会关心的。主流们关心的是什么呢？主流们成天觉得现在思想不够解放。为什么不够解放？据说是“左的思想”阻碍着。主流们成天攻击左的思想给他们带来极大的困扰，要扫清左的影响.其实这说起来让人觉得主流们非常非常的无能。为什么呢？主流们在台上搞了30年，要权力有权力，要资金有资金，要宣传有宣传。不到20年，在中国已经存在了几亿年的清水，几乎绝迹。这只是他们伟大力量的表现之一而已。凭着这种人的黑心，什么事情做不成？一点左的思想，那还不是太容易对付？可是为什么就对付不了呢?什么是左的思想？其实说白了，就是毛泽东思想。这毛泽东思想在中国，也就几十年吧。如果从1949年开始算，在中国占据思想上的统治地位也就27个年头而已。按照主流们的说法，在这27年里，中国人吃尽了苦头，投奔主流们的怀抱应该是象洪水一样不可阻挡。结果呢？去毛化搞了30年，毛泽东思想的大潮是一浪接一浪，一到什么节日，网上纪念毛主席丰功伟绩的文章排山倒海。这让主流精英们头痛不已，据说他们很不明白得到“改革开放好处”的人民为什么会这样。也就是说，他们不明白，明明30大于27，可是为什么27就是远远大于30呢？而且更加可怕的是，按照这个形势发展下去，这个27恐怕会大于100也是毫无疑问的了。 为什么越来越多的人怀念毛主席呢？是现实逼迫的。同样的，主流其实对自己的罪行清清楚楚，但是骨子里喜欢当洋奴，而且还要通过剥削人民来发财，所以就要愚弄人民。怎么愚弄呢？一方面是把毛主席时代说成一片漆黑，什么没有人性啦、迫害啦、经济要崩溃啦等等，另一方面说自己“政策完全正确”、“取得了举世瞩目的伟大成就”、“生活得到显著改善”——且不说这明显把人民当作猪只要吃好了就睡，就是这吃的肉是什么东西也没有人能够说清楚吧。但是污染、血汗工厂、矿难、贪污腐败、生活负担、卖国求荣、殖民地经济到处都是，人民也看得清清楚楚，这可怎么办？主流们就拿洋老爷，也就是所谓“世界主流文明”来压人民。看看？洋老爷都说话了，尔等贱民还不老实？只是洋老爷也不是吃素的，人家帮洋奴做事了自然要一点回报。而且这胃口越来越大，中国的行业都控制了还不满足呢。这中国人民的苦难，可是没有边了。这样的结果，就是更多的人想起毛主席来。没有办法，毛主席就是穷人的神.其实主流们要人民忘记毛主席，非常容易。把中国的污染治理好，让中国人民没有负担，在国际上谁也不怕，这时去污蔑毛主席，保证人人相信。但是主流们心里也清清楚楚，要想做到这几点，自己相信的“世界主流文明”是绝对不可能的，只有靠着毛泽东思想。最可怕的就是，毛泽东思想不仅不能让他们安心当洋奴，还要禁止他们掠夺人民的财富。既然糊弄不了人民，那就暴力好了。说到这里，就不好深入下去了.主流们铁了心要让27永远大下去，只是苦了中国人民和中华民族。这一笔账，历史一定要清算的。在这里，我要说说的是，争论最多的是左与右的问题。很可能，这是这个论坛与生俱来的特点，争论还一直比较激烈。
　　左与右的争论焦点集中表现在哪里呢？我看主要还是对毛泽东的态度问题。据观察，怀念毛泽东的人，在这里发表了不少文章，摆事实讲道理，讲得很清楚；对毛泽东持反对态度的人，没见发出什么贴子，不知道是什么原因？可是，他们总在贴子后面骂人家是左棍呀，左棍呀什么的，更好笑的是，有人说，怀念毛泽东的人，就是当年的即得利益者，现在混不下去了，所以才戚戚哀哀，或者说怀念毛泽东的人，就是好吃懒做的人.我要回答的正是这个问题，说怀念毛泽东的人，是既得利益者，这我完全承认，因为没有毛泽东，就没有新中国，没有毛泽东，就没有今天的安定日子，所以，既得利益者不仅仅是怀念毛泽东的人，而且是所有的人（包括反对毛泽东的人）是整个中华民族。如果有人认为，毛泽东因为土地改革分了他们的田地、房子，那么，可以理解了，可是，毛泽东没有剥夺你的生存权力。毛泽东只是让社会人人平等：均田地，等贵贱，实行按劳取酬的原则，建设一个新型的国家。有些人如果不承认这一点，他们对毛泽东刻骨仇恨，他的内心世界就昭然若揭了。再一个，说怀念毛泽东的人好吃懒做，这就贻笑大方了，告诉那些人吧，我们这些怀念毛泽东的人，没有一个是好吃懒做的，而且是干了一番事业的人，生活不比那些人差到哪里去。我所了解的怀念毛泽东的人之中，包括本人，也是干了事业的人，做了贡献的人。用好吃懒做的话来贬低对毛泽东有深厚感情的人们，这一点就是唯心主义者的一向判断事物现象的水平，可怜！我所接触的怀念毛泽东的人，他们写纪念文章，可以说，大多数是干部，知识分子，教师，也有拥有千万亿万财产的民营企业家，还有高干。持反对态度的人不知道吧？难道我们怀念毛泽东是因为没有饭吃才写文章的？可以这么说，真正的没饭吃的人根本没有时间来写这些文章的，写这样的文章正是在替那些下岗工人，生活贫困者说公道话，打抱不平。这就是那些以小人之心度我等之腹的人想不到的，也不得其解的，这也是那些僵化的不能再僵化的人判断问题的固有方式！用这种观点思考问题，可笑不可笑自己的去看吧，不必多说.为什么要怀念毛泽东？我想是有很多原因的，一些原因也是不言自明的。可以这么说，我们现在的经济发展了，人民生活水平提高了，怀念毛泽东的人对此根本没有持怀疑态度，只是认为，这个社会，还要回到路不拾遗，夜不闭户的那种状态上去，不是吗？这些年来党和政府的努力难道不是为了这些吗？可是事实怎么样呢？是不理想的，而且很不理想的。为什么？谁都知道，在官场，腐败现象滋生，到了令人发指的地步，庞家珏、段义和之流，做坏事，丑事，达到登峰造极的地步，贪官们说的做的言行不一，难道我们不应该呼唤毛泽东那个时代的干部的好品质好作风吗？贪污腐化给社会带来的负面影响是无法估量的，包括那些反对人们怀念毛泽东的人，也是这个社会的受害者,难道不是吗？如果不是,那么你不是贪官，就与贪官同流合污！社会不安定的因素还有一条，就是黑社会活动猖獗，你有多少安全感？人们怀念毛泽东，就是要增加安全感，争取路不拾遗，夜不闭户的那样一种社会风尚，你们反对这样的理想和愿望，除非你们是黑社会人物。人们为什么怀念毛泽东，就是毛泽东时代消灭了的性病、卖淫嫖娼、吸毒贩毒现象，怀念毛泽东的人不会去吸毒，不会去干伤天害理的事，起码人们是正派，是在呼唤公平，公道，正义，这些人看不到吗？这种正气难道不应该提倡吗？现在，这个社会出现的不正常现象极需人们继续解放思想，开动机器，发动群众，群策群力，解决问题，可是，现在就是出现了那些说别人是左棍，左混的人，他们才是真正的极左，真正的思想僵化，反对别人用脑袋思考问题的新的思想僵化群体！他们与当年四人帮搞的极左如出一辙，他们动辄对人打棍子扣帽子，反对人们反思问题，无疑是饮鸩止渴，自欺欺人！

　　人们怀念毛泽东，总体来说是一种忧患意识，希望国家长治久安，国家兴旺，社会安定，一天比一天好，错在哪里？为什么要受到责难，甚至攻击谩骂？是何居心？的确，毛泽东时代我们还很贫穷，但是，那个时代的优点正是要在新时代给予发扬光大的，这有什么不对吗？新时代创造了更多的财富，而新时代无可避免地出现了一些让人感到困惑的问题，难道人们呼唤现在的党中央认真解决这一问题，提高执政能力，错了吗？毛泽东曾经告诫我们防止和平演变，这是事实证明了的，历朝历代，开国皇帝不是制定了不少规章制度，不是从反腐败开始的吗？最后怎么样？不是以腐败透顶而灭亡的吗？难道提醒这些事，拿毛泽东时代伟大成就说话就有错？本来，左也好，右也好，都生活在中华大家庭，都是一家人，但是就是一些人目光短浅，才不喜欢让别人说这些忠言逆耳的话。事实上，封建社会的更迭，中华民族不就是一损俱损的，陷入灾难吗？过去许多富翁不是没有产生，可是现在他们在哪里呢？一个政权垮台了，更多的人得从头开始，如果一个国家乱成一团糟，有多少人的财富可以幸免？那些感到现在很有钱的人未免想的太天真了吧，不是想着逃到国外吗，那就是甘当二等公民了。我要告诉人们，一些写纪念毛泽东文章的人，这些人是值得尊敬的人，是最纯朴的人，并不是像那些人所说的，写这样文章的人混不下去了，除非你们心中有鬼！毛泽东已经离开我们三十一年了，而去世了三十多年的毛泽东，人们总是对他的怀念不断。在怀念毛泽东的声音一波高过一波之后，人们也在不断地思考着这是为什么。如果细心浏览各类文章和民间百姓评论，就会发现，人们怀念毛泽东，是因为毛泽东对中国人民的无私情怀，无私的奉献，而这种情怀和奉献，无人可以代替.一、人们怀念毛泽东是因为他说得到，做得到，全心全意为了人民立功劳。人们对照毛泽东的一生，就不难发现，他是说得到，做得到的一个人物。在一九四九年以前，他领导人民的目标就是要打倒帝国主义，官僚资本主义，封建主义，并称为“三座大山”，对强于自己多少倍的敌人，毛泽东提倡持久战，并发扬愚公移山的精神，下定决心，不怕牺牲，排除万难，去争取胜利。毛泽东说到做到，他自己付出的艰辛努力还不算，他的家人也为此付出了流血牺牲。所以，一个人干什么事，不三心二意，不说一套做一套，从各方面找不到他言行不一的表现，人们对这样的领袖怎么能不敬佩呢？他给人民带来路不拾遗，夜不闭户的生活环境，与现实的反弹对照，人们怎么能忘记呢?二、人们怀念毛泽东是因为他立场坚定旗帜鲜明，是就是，非就非，不做老好人。我们从毛泽东的一生中可以看出，毛泽东从来就是疾恶如仇的一个人，对待敌人，他从来不让步，对待错误思想，他从来不放松，他的原则立场从来没有动摇过。对待敌人，他说过，一切反动派都是纸老虎，要横扫一切害人虫，全无敌。而对待自己犯错误的同志，毫不客气，进行严肃的批评与帮助，延安整风运动，不是证明了这样的整风给中共的革命胜利奠定了基础吗？往前推推看，古田会议精神，不是毛泽东纠正了军队错误思想，从胜利走向胜利的开始吗？而毛泽东的一生，从来在大是大非面前，是不做好人，不和稀泥的，就是对他的恩师们，也不是给个高官厚禄，打着他的旗号乱发言的。所以，在毛泽东身上，看不到软弱无能这几个字。看不到他是在和谁搞平衡，搞中庸.三、人们怀念毛泽东是因为他善于调查研究，在调查研究中发现问题解决问题。在反映毛泽东的许多纪录片中，都记录了毛泽东这样和历史，他始终如一地深入社会进行调查研究，中华大地上，踏遍了他的足迹，甚至到了八十岁，还计划骑马到黄河上游走一走，他的许多决策并不是在北京开会做的，而是在调查研究的半路上做出来的，在纪录片上，人们看到，工厂、农村、学校、军队、田间，到处都有毛泽东的身影，甚至列车成了他的办公室，在列车上不知道接见了多少中外来宾。毛泽东接触群众，绝对不是做秀，不是跟百姓握一下手，留个镜头，也不是逢年过节端个碗吃个饭，就算深入群众，毛泽东也流过了不少眼泪，可是，眼泪流下之后，发出一定要把淮河治好，一定要消灭血吸虫的动员令。从毛泽东深入群众的镜头中，怎么都看不出他是在做秀.四、人们怀念是因为毛泽东总在为中国人争气，他从不丢中国人的面子。新中国成立以后，是一穷二白的，而毛泽东善于将中国人民建设自己美好家园的智慧、积极性和创造性调动起来，并把防御大国的威胁力量架设起来。当年，帝国主义威胁中国的就是有战略武器，而明明看着中国不具备发展那样武器的条件，不知道为什么，毛泽东领导中国人民鬼使神差地搞出来了两弹一星，有了这些东西，大长了中国人民的志气，大灭了那些妄我之心不死的敌对势力的威风，由此，也成了中国人民在世界上取得应有地位的参照物，中国如果落后，这将会是置疑的理由。因为毛泽东的那股中华民族英雄气的影响，中国人民，所以现在容忍不得谁有半点奴颜媚骨.五、人们怀念毛泽东是因为他热爱百姓，百姓热爱毛泽东。毛泽东和人民心连心，这没有半点娇柔造作，尽管当年没有电视，但毛泽东走到哪里，哪里的百姓就会认出他来，为了安全起见，后来的毛泽东视察，无奈地戴上口罩，但是，千山万水，连着天安门，毛主席是咱社里的人，以及毛主席与各族人民心连心是发自内心的歌唱。虽然毛泽东当年的‘四大’有点冒失，但现在看来，是一种胸怀，是一种伟大的谋略，是一种风度，更是史无前例。没有人敢试试这个创举的。于是人们可以说，一个真正得到人民拥护的领袖，做出什么样的荒唐之举，看起来荒唐，但都是一种伟岸和无可比拟.六、人们怀念毛泽东是因为他的家风，为后人开创了先例。有人曾经把毛泽东比作暴君，恶毒咒骂过他，可是，如果是暴君，如果毛泽东满脑子封建意识，那么他的家风为什么不按照封建王朝的那一套来呢？除了他的地位和工作需要以外，毛泽东的一家人，没有搞过什么特殊。毛泽东的儿子上前线牺牲了，有人说这说那，那么以后还有出现各种情况的可能，我们等着那些将小人之心度君子之腹的人的表现。毛泽东，生前坦坦荡荡，身后，任人评说，没有任何遮遮掩掩，无论是他个人还是他的家人，没有任何事不敢让人评说，这就是中国人民的福气，也是人们不断怀念毛泽东的理由.怀念毛泽东的理由太多了，许是因为当年人们的口味被毛泽东调高了吧？这社会真的找不到对手？当社会上习惯了一种健康向上的风气，习惯了一种伟人的作风，那么人们就是认定了，在中国，壮哉，毛泽东，伟哉，毛泽东！毛泽东逝三十一年，但毛泽东的风骨没有随风而去，没有飘浮不定，总是深深地扎根于人民心中，恐怕是人们随时都可能产生对毛泽东伟大品质怀念的起因。当下，不仅在网上，而且在生活中许多人谈起毛泽东都是那么一份景仰、那么一份留恋.的确，毛泽东是伟大的，毛泽东的伟人魅力也是无穷的，是永远值得人们怀念的。但若细细体味一下，也许就会明白，这种怀念毛泽东其实也有对建国初期二十世纪五六十年代那个时代的怀念。而且，还要明白，在改革开放之初甚至十年前，人们都没有如此的怀念情节，为什么在时间越久远、国家越繁荣之际的今天，出现了如此的返潮现象呢?其实问题不那么简单，这里有其深刻的内涵，这就是两个紧密相贯的问题，一是官员队伍问题，二是贫富分化问题.有那么一些人，当谈到了毛泽东时代的时候，总是这不是，那不足，但不知道干部队伍建设是很成功的。那时候的官员是人民的勤务员，并不像电影小说那样的瞎说八道，他们真的能与群众打成一片，与群众同吃同住是太平常的事了，凡观眼下这些官老爷，下一次乡就是“调研”、就成了报纸头版的大新闻，就成了对群众的莫大恩赐；更主要的是现在的一些官员贪污腐化成群，骄奢淫逸成风，大肆行贿，买官卖官，不顾民生，专捞政绩，现在人民群众要想办件事，不请客、不送礼那是什么都办不成的；还有就是，现在的法纪松驰，远没有毛泽东时代的纪律严明。现在干部队伍中这种情况在毛泽东时代简直是不可想像的.而另一方面，正是“吏治”不严，导致一些地方的官员，独断专行，官商官匪交结，侵吞国家和人民财产暴富，致贫富分化急剧加深。他们还经常养什么二奶三奶，不嫖就赌，腐化堕落，谁管老百姓的死活，这与1949年前蒋匪帮政权有什么区别？毛泽东时代虽“穷”，但贫富差距很小，工农兵唱主角，是主人，那时候一些普通“干部”的收入甚至还低于一般群众。而当今中国，有多少工人农民能走进人民大会堂。有的人是食不裹腹，有的人则是极力奢侈。这在毛泽东时代同样是不可想像的。人，作为一种有思维的社会性物种，渴望公平、公正是一种天性，生活环境的优化并不能消掩人们对公平正义的追求。理解了两个“不可想像”，就不难理解为什么今天怀念毛主席的人们越来越多了.倒过来看，毛泽东热的出现，实是一种警示，警示今天的官员腐败问题和贫富分化问题已到了非常危险的地步！“反腐败事关党和国家生死存亡”，切盼高层能铁腕治官、严厉打击，在腐败如此严峻的形势下，狠狠打击才是第一位的。打出声威，遏住不断蔓延的势头，给民心一个有效的抚慰！人们怀念毛泽东，是因为他时刻想着处在最底层的劳动大众，在他领导下的中国，工人、农民扬眉吐气，劳动大众真正享受到了做“主人”的味道。

人们怀念毛泽东，是因为他严格要求“人民的公仆”，一篇《为人民服务》曾经激荡过多少干部和群众的心。他不时告诫国家工作人员不要做官当老爷，不时清理干部队伍之中的腐败分子，要求各级党政部门、企事业单位的领导同志保持“两个务必”，从而使各级政府真正成为人民的政府，使广大干部真正成为人民的勤务员。

人们怀念毛泽东，是因为他公而忘私的品格与精神，他没有给儿女留下显赫的位置，也没有给儿女留下多少物质财富。相反，他还为革命、为国家献出了自己几位亲人的生命。在他死后，国外既无分文存款，也没有置下半点产业。他的儿女过着普通的平民生活，既没有出国，也没有做什么高官。

当然，毛泽东毕竟不是完人，他也犯过很多错误，特别是在中国经济的发展上，他的某些“左”的作法实际上是阻碍了中国的发展。但这并不能掩藏他作为伟人的光辉，不能抹掉人民对他真诚的怀念。

人民对真正关心过他们的人，总是不会忘记的。 坦率的讲，我是80年出生的，保守的讲我是6岁时开始懂事，也就是86年我开始渐渐的明白这个世界。我所看到的世界是怎样的世界呢？在我很小的时候很少听说这个世界有妓女，可是随着年龄的增长，渐渐开始听说在这个社会上出现了一些新鲜事物——姘头，在我整个成长的每一天里，我都生活在恐慌之中，每一天都能从同学们那里听说在我们这个社会里新出现最新的“有意思的新闻”，而社会上每一条这样的新闻都足以使成年人感到脸红心跳，更何况我们这些小孩子们呢？



　　后来我听到的社会上这样的新闻越来越多，简直日新月异，花样翻新。我有时候也在困惑，我们这个社会到底怎么了？我后来才知道，我们这个社会在86年——96年恰恰是娼妓现象经历了从无到有，从地下到公开的过程。而这个过程恰恰发生在我国改革开放程度越来越深化的时期。而这种现象在毛泽东时代恰恰是没有的。坦率的讲，我没有出生在毛泽东年代，我也没有经历过那个年代，那个年代到底是什么样我也不是十分清楚，但是，在今天我们仍然能够从历史的纪录片中和书藉中窥见那个时代。我们可以在纪录片中看到人们喜气洋洋的从事着集体劳动，劳动是那么苦，然而每个人的脸上都挂满了笑容。而这种现象在我们现在还能看到吗？



　　从我小时候听说某同学为了当班长，在放学后给老师送一篮鸡蛋到高中时某同学为了到年级的重点班读书给校领导送去几万元钱，我能够感受到在我渐渐长大成人的过程中，我们这个社会的腐败程度在逾演逾烈．然而，据我所知：这种现象在毛泽东时代是很少有的。这种现象也是在改革开放逐步深化的时候愈演愈烈的。难道社会上发生的这些变化，只有经历过毛泽东时代的人才能感觉到吗？



　　还记得，在很小的时候，每当过节的时候，亲戚们聚在一起吃饭，（那个时候，大家的公资都差不多，）大人们在桌上吃饭，我们小孩子们在桌下玩耍，很开心，那段和谐的，其乐融融的时光真的很令我难忘。随着我的长大，亲戚们之间的吃穿渐渐的就有好有坏了，三姨家装修得金壁辉煌，他们可以每餐到饭馆去吃，而我们家依旧贫穷。这几年之间，亲属之间的贫富之差就有这么明显，我这个出生在80年代的，没有经历过毛泽东时代的年轻人，难道就感受不到在改革开放的这些年来，人们之间的贫富差距在拉大吗？然而，据我所知，这种现象在毛泽东时代是很少有的。毛泽东把一家6位亲人献身给了中国革命，他老人家在生前却没有给自己的子女们谋个像样的高官当当，就连自己的爱子岸英也牺牲在朝鲜的战场上。哪一个现在的领导能做到呢？毛泽东拥有百万元（有些人说已经过亿元）的稿费，他老人家在生前没有因为自己家里的生活开支过一分钱。尽管有人在报刊上写文章提出非议，但这些钱一直是国家的财富，他的子女们竟然没有继承也没有开销。毛泽东挣着全国的头号工资也不过几百元，也就和现在的一个扫街道的清洁工的收入数差不了多少。就说他富也比全国人民富不了多少。如今呢，有的人钱多的没法花，有的人穷的没钱花。毛泽东的时代，用现在的说法是，法制很不健全。但是人们道不拾遗，夜不闭户，生活相安无事。很少有人犯案，即使偶尔有些地方出现一半个杀人案，也是惊天动地。如今，杀人放火成了家常便饭。老百姓们最爱说的一句说是，毛泽东爱穷人。爱穷人的人民领袖，穷人能不爱他吗？现在的大小官员却喜欢傍富人……

在生活枝节上让百姓们赞不绝口的事儿说不完。越说越能显示出毛泽东的伟大。

在老百姓的心目中，毛泽东之所以伟大，就是他事事为老百姓着想，尽量缩小贫富差别。尽管那时人们的生活并不富裕，甚至很清贫。但是，人们的心里却是踏实的。毛泽东逝世多年了，老百姓们谈及起来，却在不时地念及他带给人民的好处。人们深切怀念毛泽东，甚至在偏远农村的一些农民们，怀着质朴的感情，把他当神敬。 毛泽东去世30年来，资产阶级右翼分子、party内原有的反对派以及国际上的和平演变分子联成一气，向毛泽东和毛泽东思想发动了大规模的、旷日持久的审视，连毛泽东同志身上哪怕是一个微微的缺点都被揭了出来。能享受到这种如此大规模、如此精细精洗的，对于我party来说，绝对是第一人！更奇怪的是，对于其他领导人（不管是健在的，还是己故的），一律不准谈及。有些人主意想尽，甚至加上了造谣诬篾一手，也不起作用，毛泽东是越洗越亮，毛泽东在广大人民群众中的形像越来越高大，这成了现代修正主义分子最大的心病！

为什么毛泽东对中国人民有那么大的影响力？为什么人民群众是那样地诚挚地爱戴着毛泽东？有些右派网友弄不明白，在这里，我给右派网友露个底：

第一，千方百计、无时无刻、无私无畏、完全彻底地为人民谋利益，这是毛泽东得到全中国、全世界劳苦人民衷心爱戴的最根本原因；

毛泽东全心全意想着人民群众，一心一意地维护着人民的利益，这是13亿中国人有口皆碑的事实。

毛泽东一生一世站在人民群众一边。1954年淮河发大水，毛主席一边流着眼泪，一边疾书“一定要把淮河治好”八个大字，并亲自组织了治理淮河的伟大战斗，使近一亿江淮群众走上了幸福的康庄大道！

1`957年毛主席的一个警卫战土回家探亲，归来时带了几个用野菜做的窝窝头，加之路长，天暖，带到北京时已很难进嘴。毛泽东见到这几个窝窝头后热泪纵横，泣不成声。在全体机关干部、警卫人员的会议上，毛泽东义愤填鹰地说：觯放几年了，人民群众还过这样苦难的生活，我们对不起群众。我们要大干快干！于是1958年出现了大跃进！尊敬的右派网友：即使大跃进出现了这样那样的毛病，人民群众会因此而恨毛泽东吗？

第二，举世无双的智慧和能力，超乎常人的人格魅力，是毛泽东得到各阶层人士、甚至是他的敌人不得不叹服的重要原因；

毛泽东是古今中外举世无双的人民领袖，即使是无产阶级，在当今的今天，也没有一人能与他相比！

毛泽东是古今中外第一个不爱财的领导者。毛泽东有数千万元稿费，可是他交给party组织管。大儿子毛岸英结婚，他只办了一桌酒席，请了亲家母张文秋，以及刘少奇夫妇，周恩来夫妇，朱老总夫妇等；李敏李纳出嫁，毛泽东也是各办一桌酒，陪嫁的只是三四百本书而己。古今中外，有哪个统治者、领导者不为个人的私利苦心经营，惟独只有毛泽东除外！

毛泽东的领导艺术堪称古今中外举世一绝的最高艺术品。红军长征中的皿渡赤之战，让蒋介石浑头转向；红军长征蒋介石调动一二百万大军围追只有数万之众的红军，并以失败而告终。小日本侵华，蒋介石想借日本人消灭GCD，毛泽东只将GCD的“反蒋抗日”政策中的“反”字改为“联”字，竟奇迹般的发生了西安事变，发生了张学良、杨虎成、傅作义、冯玉祥、张治中等国民party高层人物的积极抗战，并最终形成了由GCD领导的抗日民族统一战线，在打败了小日本的同时为中华人民共和国的诞生提供了100万人民武装、200万民兵武装、八大块革命根据地的坚实基础、是毛泽东指挥100万人民解放军只用四年时间就消灭了由美帝国主义武装到牙齿的800万国民觉反动军队，建立了中华人民共和国。建国后，毛泽东又指挥中国人民，取得了抗美援朝、抗法援越、抗美援越、对印自卫作战的伟大胜利，并迅速还清了苏联的债务，并取得了两弹一星的胜利！这一件件伟大的历史功勋，哪一件不让有良心的中国人崇敬乃至崇拜？谈起功劳，个个向自已脸上贴金，可是哪一项重大决策不是毛泽东提出并拍板？成绩个个有份，出了问题，个个把头缩起来了，光打毛泽东的板子，思闻、疯和尚之所以不得人心，右派为什么不得人心，原因就在于此！

第三，由一些心怀叵恻的阴谋家的胡作非为造成的社会矛盾的加剧，剥削行为的加剧，两极分化的加剧，生存压力的加剧，使广大中、下层人民大众更加怀念毛泽东；

事实表明，大凡人民群众真正生活在和谐的幸福生活中的时候，人们倒真能慢慢地忘却幸福之源。但一旦社会矛盾、生存压力加剧的时候，人们自然而然地就会想念毛津东对人们的思情。社会矛盾越多，思念的人越多，人们对毛泽东的感情就越深！


富翁、老板、有权有钱有势者搂着小姐漫漫起舞的时候，这些人会怀念毛泽东吗？———他们根本不会！

拿着外国人的俸禄，或拿着富翁老板们的钱财为他们摇旗呐喊的那些士大夫们，他们会怀念毛泽东吗？——不会，他们根本不会！

但是：

广大失业工人、下岗工人，当他们生活痛苦无着时，他们会恨谁、怀念谁？

广大农民，特别是农民工，当他们以每天工作十多个小时、负出沉重的工作、每月工资不过千元、有时还拿不到手的肘时候，——他们会恨谁、怀念谁？

当广大农民、普通工人、社会人员有病无钱看，有学无钱上，或被拦

在医院外、学校外的时候，——他们会恨谁、怀念谁？

近千万应往届大学毕业生找不到工作，报不了父母恩，还不了求学欠下的债、四处碰壁的时候，——他们会恨谁、怀念谁？我这人平常喜欢在网上转悠，由于网络论坛是目前管制最宽松的舆论平台，也由于网络论坛最大限度体现了言论的平等性和自由性，我对观察论坛中的言论走向尤其感兴趣。

　　在百度毛泽东吧看到一位网友比较毛泽东吧和邓小平吧帖子数量的文章，感觉很有意思。我来这里时间不长，也只是很偶然才知道百度居然也有论坛之类的设置。但几天匆匆浏览下来，也大体能够感受到在这里毛泽东被关注的程度之高。其中提及毛泽东经常是各大时事BBS的头号热门话题，其间当然是各色杂陈，争论之激烈、涉及范围之广阔颇令人有叹为观止之感。但无论反对或赞成，一个事实已经不容否认：在今天讨论国事，毛泽东经常是一个无法绕过的巨大问题。对百度贴吧的观察再次印证了我的看法，同时由于百度的特殊性质，这里表现出的各种现象更有代表性，也更耐人寻味。

　　简单的统计表明，毛泽东吧的帖子数量大约是邓小平吧的十到十五倍，无论主帖或跟帖，比例大体如此。远期的差距还有可能进一步拉大，因为毛泽东吧的帖子增长速度远远超过邓小平吧。我也对天下论坛毛泽东与邓小平献花的数量以及言论作过关注。

　　如何解释这种现象？有人将其归因于所谓个人崇拜，但熟悉个人崇拜发生机制的人肯定不会很认真看待这种看似合理的解释。对待逝去的人，个人崇拜是没有意义的，个人崇拜背后是明确的政治需要，更需要现实权力的积极推动。如果有人要推动个人崇拜，那么，最优选择是崇拜目前当权的主流派，次优选择是崇拜一个对当前政治秩序有利的历史人物。显然，毛泽东不符合这两个基本条件：既不是当权者，推崇毛泽东也不符合当前秩序下很多当权派的利益。所以，我可以肯定地指出：数据的差异更多说明的是民意的去向。

　　为什么关注毛泽东吧的人要远远超过关注邓小平吧的人数，这本身就是一个耐人寻味的问题。一个是共和国和共和国的执政党——共产党的创始人，一个现在却被小心翼翼隐藏起来，不敢容许社会深入讨论的人，但也是今天社会下层民众和正义力量寻求民族前途和社会公正的政治符号；另一个是所谓改革开放的设计师，一个至今仍然被官方在邓小平理论的旗号下大肆宣传，却在民间日益引起质疑、逐步走向毁誉参半的人。如果说有人在推动个人崇拜的话，目前崇拜的对象也只能是后者，全力开动的宣传机器、歌功颂德的研讨会、子女们所谓回忆录的大量出版都证明确实有人很希望人们来崇拜邓小平。但很不幸，人民显然没有兴趣去崇拜这个被希望崇拜的人，反而是那个被拼命隐藏的人一次又一次成为人民在追问自身命运过程中最终可以诉求的精神导师，成为人民向二茬罪的制造者挑战的最有力的政治符号和政治资源。这还不能说明问题吗？

　　百度贴吧与很多网络论坛大有不同，由于百度作为中文最大搜索引擎的突出公共性质，我们有理由相信这里聚集了更加大量、更加广泛因而在社会学采样方面更具代表性的人群，这个人群包罗万象，一般论坛上常见的单一观念持有者扎堆、从而使论坛成为一言堂的现象不太可能在这里出现。扎堆现象到处存在，由于参与者的类型相对单一，凯迪变成了右派和反民族主义者的大本营，铁血变成了左派的扬声器，强国论坛则呈现出左派和民族主义者的压倒性优势。以这种论坛作为观察网络民意的样本多少有些不准确，不符合社会学取样寻求广泛性和一般性的原则。但在百度，由于参与者的广泛和形形色色，其间的观念和价值倾向就完全可以被相信代表着更广泛的社会呼声，有关的统计数据就像百度搜索引擎的使用量的统计数据一样有说服力，因而在社会学的意义上更有研究价值。统计数据告诉我们，在百度，对毛泽东的关注度决定性超越了对邓小平的关注度，参与其间的相当广泛的人群对毛泽东充满兴趣，他们在怀念和关注毛泽东。由于正在发生的关于毛泽东的讨论总是与今天的社会问题紧密相关，我们也有理由相信对毛泽东的关注不仅仅是对一位历史伟人的关注，而是人们在试图藉由毛泽东的管道来解答一系列的现实问题。

　　关注现实是当今网络世界中毛泽东热的基本特征，这就将第二次的毛泽东热与上世纪九十年代初第一次明显具有怀旧色彩的毛泽东热区隔开来，构成一个在关于中国当代社会的考察中非常值得注意的现象。

　　我个人认为：这不仅表明人们对毛泽东作为中华民族独一无二的历史伟人的兴趣，更说明当前社会正在发生的一切与毛泽东一生为之奋斗的事业正在再一次发生关键性的交合。

　　人们是在面对一个怎样的中国当代社会呢？虽然官方一直在掩饰，但任何一个理性的观察者都不得不承认，这个我们不得不在其中生活的社会正在复活一些曾经被毛泽东时代的社会价值抛弃的东西——那些注定只能被称作人类社会最恶劣产物的东西：巨大的社会贫富差距、严重的官僚体系腐败、权钱交易、疯狂的社会公共财产侵夺、日益堕落的社会价值体系、下层民众利益的无可保障、黄赌毒的泛滥成灾、三农问题、严重的城市失业问题、人民相对的和绝对的贫困化、教育对贫民子弟的拒绝、全面消失的社会福利和难产的社会保障体系。这些在毛泽东时代曾付出巨大历史代价加以消除的垃圾竟又一次堂而皇之地成为我们这个社会最具指标性的特征。毛泽东和他那一代仁人志士终其一生、为之殚精竭虑、悬首浴血而后初步建立的社会公平体系竟然被当作破烂丢掉。在所谓“效率”的冠冕堂皇的理由下，我们重新走向了资本主义，走向了所有资本主义形态中最糟糕的那一个——权贵资本主义，至此，权力与金钱的无耻而疯狂的勾结成为一切社会问题的事实制造者。

　　目睹这一切，人们怎能不思念毛泽东，怎能不思念毛泽东曾经带给中国人的那个虽然暂时还未摆脱贫穷，但却有着足够的社会公义和健康心灵，生机勃勃而前途无量的社会。今天的我们比毛泽东时代的我们富有一些，但我们中的大多数人却为此付出了不能承受的代价：工人和农民永远丧失了国家主人公的荣耀，重新沦为资本家和大官们颐指气使的奴隶；我们“提前透支二百年的资源消耗换来的只是眼前的繁荣假象”；我们的社会在价值体系方面已经彻底沦丧，金钱和权力崇拜横溢神州，我们这个曾经骄傲的民族终于再次在世界民族之林中无颜抬头，面对来自西方的真诚的亦或不真诚的道义谴责，却只能小声地、怨妇般地、了无意义地为自己辩解；我们丢失了一个独立自主的工业体系，不能生产早在几十年前的毛泽东时代就能够生产的很多东西，而这一切居然仅仅因为我们“伟大的”新自由主义经济学家们灌输给我们的 “造飞机不如买飞机，买飞机不如租飞机”的西方经济学的混账逻辑；面对西方，我们不再有自豪感，虽然除了槬璺之流最无耻者之外没有人愿意公开承认，但在内心认为“西方的月亮比中国的圆”的还是大有人在，他们本能地接受了中国人相对西方人在人种方面的恶劣性；我们不再能拒绝跨国公司的无理要求，内外企统一税收已经是对外国公司的优惠，不多征他们税就已经很好了，而他们却要求维持那个歧视民族企业的对跨国公司实行税收优惠的税收制度，并演出了一出55大跨国公司联合逼宫的闹剧，而我们的政府居然无法拒绝这种蛮不讲理、贪得无厌的要求。在付出如此多的代价之后，我们彻底失去了毛泽东所创立的那个堂堂皇皇的伟大中国，只得到了“用八亿件衬衫换回一架空中客车”这样一个在全球化资本体系中尴尬的下游苦力角色。

　　在毛泽东被遗忘的岁月，我们曾经欢呼乌托邦的破灭，我们以为自己打破了一个在虚幻中徘徊的宿命，我们在一个梦里沉睡了很久。现在我们试图从梦里醒来，睁开惺忪的双眼，却蓦然发现，我们付出如许代价，却只换回了一个不再有雄心壮志、不再有深远战略的不断沉沦的前途未卜的中国，这就是我们想要的吗？

　　我一直在想：如果给毛泽东足够的时间，我们是不是可以生活得更幸福，我们是不是可以拥有一个远比现在所拥有的更完美的社会？我不想再在财富增殖方面与一帮反毛者纠缠，历史不能假设，所以从历史学角度也很难设想毛泽东的领导是否会带给今天的我们更多的钱财。我更愿意诉求于信仰——基于坚实的现实基础之上的信仰，从这个信仰出发，我还是相信：如果我们能够沿毛泽东指引的道路继续走下去，甚或作为后人，我们能够拥有超越毛泽东、站到毛泽东肩头的智慧，那么，我们至少可以拥有一个健全得多的社会，我们也可以比毛泽东去世的时候更加富有，生活更富足，但不需要付出那么多难以接受的代价。这是一个信仰问题，但毛泽东时代打下的坚实工业基础、公平的社会体系和人们曾经拥有的贫困却不缺乏幸福感的生活使我确信我的信仰的正确。当然，如果你是西方经济学的信徒，信奉新自由主义的胡说，相信张维迎、厉以宁之流学术骗子和人民财产的隐形杀手的谎言，你就不会有此信仰。

　　为什么人们关注毛泽东，因为人类历史上在解决社会公平、维护下层人民利益方面还没有人比毛泽东做得更好，因为只有毛泽东才能最好的回答我们正在面临的问题，因为只有毛泽东才真的关心人民，相信人民，关心和相信首先由劳苦大众构成的、而不是用脑满肠肥的资本家和贪得无厌的官僚充填的偷换概念的所谓人民。

　　我敢和所有人打一个赌，未来的时间里，伴随前期积累的社会问题的恶果逐步显现，人们还会更加怀念毛泽东，对毛泽东道路的诉求只会更加强烈，而不会有丝毫减弱。虽然我对胡温新政充满期待，但这些问题的解决绝非一日之功，而且由于已经形成的剥夺人民利益的共同体势力庞大，事实上掌握了大多数的社会资源，新政仍然有夭折的可能。保险起见，我宁愿做悲观的设想。我相信，仅仅作局部的改良，指望给中国带来一个相对温和和公正的资本主义是不现实的，因为资本主义注定有一个残酷的早期资本积累阶段，这个阶段通常会持续一、二百年，难道要让我们的人民再忍受一、二百年的苦难？谁来说服他们？谁能说服他们？

　　令人欣慰的是，今天的领导人似乎正在对这种思路说不，从胡温执政以来对三农问题、城市贫困问题的一系列重大举措来看，我们有理由认为：胡温新政是在向毛泽东的道路重新回归，他们不必重复毛泽东的具体办法，但毛泽东以人民为价值依归的事业轨迹却是不容背离的，否则，我们很可能在不久的将来面临一场新的革命，一场巨大的社会崩溃的灾难。

对于毛泽东同志个人及他领导的那个时代的评价，人们主要经历了盲目崇拜——否定——理性反思——逐步认可四个阶段。而推动理性反思和逐步认可的动力，主要是因为现实社会空前激烈的社会矛盾，我们下面主要针对很多人对毛泽东同志及他领导的那个时代的批判，以及与现实的对比来展开。

有的人说毛泽东同志领导时代饿死几千万，犹其是针对经济建设方面，认为毫无成就。我对比了一下自解放以来中国历年的人口统计数量（联合国教科文卫组织统计），特别是在三年严重自然灾害（1960——1962年）人口数量，总量减少也不过几百万，而且还包括自然死亡或自然灾害导致人口出生率下降的因素，所以饿死几千万这纯粹是胡说，而且我也有从这个时代过来的老人为证，这种不顾历史的可耻的诬蔑行径，是注定要被人识破的。此外，也有人攻击他当政期间一事无成，只顾拼政治，抓阶级斗争，而经济建设毫无成就，认为现在的成就全是改革开放的成就。这同样是一种幼稚的观点，众所周知：解放前中国几乎没有任何重工业，而且很多设备都运到台湾，正是在这种一穷二白的程度上，我们的国民经济迅速得到发展，而且取得的成绩是举世公认的。如果没有毛泽东时代打下重工业的基础，哪有我们今天改革开放的建设成就？这种割裂历史的观点看问题，反映其幼稚和无知的历史观。

有的人批判毛泽东同志迫害死了几百万人。任何一场革命，对于自己的阶级敌人，都会采用暴力的方式，不这样，能巩固革命的胜利成果吗？而且如果不打倒这些地主恶霸，反革命分子和土匪，我们的人民能得到属于他们自己的土地吗？他们就是分得了土地，这些地主恶霸、土匪还有反革命分子能让他们安安静静地生活吗？如果没有分得土地，我们的人民能有今天的生活？说这些话的人无非是要为死去的僵尸鸣冤，无非还在怀念他们以往的寄良他人的生活，无非还想企图夺回早已属于人民的财产……而且如果不将这些打倒，那么中国将会有更多的人死在那些过寄生生活的人手中。看看解放前国贫极弱的中国，没有尊严，只是任人宰割的羔羊，如果没有毛泽东同志领导的中国革命，中国有属于自己的未来吗？况且当时镇压的土匪、地主、反革命分子还有干部（包括含冤的），何以会达到几百万人？真搞不懂说这些话的人，清不清楚几百万这个概念？

当然，我们也毫不避讳毛泽东同志所犯的错误，这也是大多数网友共同表达的一个意思。对于“大跃进”、“文化大革命”，作为领导人的毛泽东同志犯有不可推卸的领导责任，但如果将所有的错误一股脑全推给他，难道你们不觉得有失公理吗？更有甚者，有的人还将当前的社会不公现象推给一个业已作古的老人，有的人将对现实的极为不满的情绪发泄到对老人有失公允的评价，甚至对老人进行极度污蔑，这种病态的人格的人在网上通常指鹿为马，颠倒是非，有的人竟可笑到将毫无关系的外蒙古独立以及中日钓鱼岛争端扣在毛泽东头上……当然，所有这些病态的人毕竟是少数，多数人已经学会理性地分析看待事物，既看到好的一面，也看到其错误的地方。而且毛泽东同志获得了他的对手（西方专家）的认可，可以想象，能够获得自己对手认可的人，这应该是一个多么高尚无私的人呀！我想作为任何一个没有偏见的人，也会公正地看待毛泽东同志对中国的贡献的。

对于今天为什么有越来越多的人怀念毛泽东同志及他领导的那个时代？我个人认为主要源于人们对当前贪污腐败现象严重，官员道德品质低下，两极分化极其严重密不可分，人们更多的怀念那个时代公平的社会氛围，以身作则的公仆形象和为人民服务的政府机构，当然更多也是表达对现实的不满。而且正是这种怀念，再加上对过去的反思，促进人们理性地对过去的认识，还原了历史的真相，并以那个时代为镜子，来拷量现实的干部和经济建设，同时也推动了人们认知水平和社会的进步。 经常在农村听到人们这样讲，还是毛主席好，就算挨饿心里也舒坦！可能是真正了解挨饿滋味的人不多了，人们才这样说，但是人们从心里还是久久地怀念毛泽东的那一个时代。在城里，我很少能与市民交往，但是有一次我乘车去济南，在长途汽车上与一位胖胖的女人坐在一起，那女人应该是个贵妇，珠光宝气，而且香水味可以熏死一头牛，我只好用报纸遮住捏着鼻子的手。汽车发动了，汽车电视开始放映一个叫做《赤裸特工》的片子。那贵妇人忽然对片子大发感慨了，如果毛主席就不会有这种事了，现在可是什么社会！我并不认为她对片子的评价有多么的“独到”，但是她对毛主席的念念不忘却让我深有感触。我作为一名大学生，在校园里也经常可以看到同学们对毛主席的敬仰，每次谈起社会，都会有人大谈毛主席怎么怎么样，虽然并不见得他们对毛泽东本人和他的时代了解有多少。“毛主席 ”我们依然习惯这样的称呼，这就足以说明，他在我们心中有着什么样的影响！

我对于毛泽东同志也没有太多的研究，只看过他的几本传记和五卷本的《毛泽东选集》以及背诵过几篇他的诗词，此外就是一些无法考证的传说了。因此，对于毛泽东，我似乎无权发言，而且我没有直接感受过他的时代，似乎也无权指指点点，在这里我也不想做那些理性的分析，把他老人家当作一门学问来研究，我只凭感情，说说我的看法以及我周围的平凡的人们对他的评价，是否遗笑大方我到不在乎，“毛主席”这三个字好像不仅仅代表着他个人，好像包含着更深的东西。

一、 个人的魅力

对于毛泽东，我想任何一个人都是很难超越的，众所周知，毛泽东不仅是一位革命家、政治家、军事家、理论家，他还是一位学问家、诗人、书法家等等。伟人是不可多得的，秦皇汉武、唐宗宋主，加上成吉思汗，再加上康熙，恐怕中国五千年的历史，也就出了这么几个顶天立地的人。而在其中真正得到民心的，恐怕也只有毛泽东，李世民也享有盛誉，但是毕竟他离老百姓要远的多，最近流行的“康熙大帝”不过也是虚夸出来的幌子，在人们心中他只不过是个皇帝。而毛泽东却是一个领袖，不仅是一个社会领域的领袖，而且还是一个精神领域的领袖，或许直到现在，人们头脑中最根深蒂固的还是他的思想。

在毛泽东身上，人们的感触其实不是一个“神”，因为没有任何一个人看到过神，感触过神，受到过神的恩惠，而毛泽东却实实在在地在人民身边，为人民服务，与人民同甘共苦，直到现在，我们的老师一提到毛主席，依然很感动地说，那时候，毛主席也吃黑窝窝头，真的！还记得一位农民开玩笑地说，小时候我们最大的愿望就是过上毛主席的生活——夜里可以吃长果（花生）。可见，毛泽东在人们心中留下的最大的印象恰恰是一个人，一个与人们一起吃苦的人，而不是一个神。恰恰是现在的一些干部，好像神一样，吃着山珍海味，住着琼楼玉宇，而且高高在上，见上一面，比登天还难。谁是神？人们的心要比学者的论文更有权威！

正是这样，毛泽东才活在人们心中，让老百姓久久无法忘却，因为他圆过人们心中的梦！

二、他的思想与实践同步

毛泽东的思想从来都是都是与实践相结合的，无论是在抗日年代、解放时代，建国时代，建设时代，毛泽东似乎就没有说过空话，他的语言、他的思想永远都是与实践紧紧相结合的。不拿群众一针一线就是不拿群众一针一线，为人民服务就是为人民服务，无论是抗战、土改、建国……都做得实实在在，为什么现在的人都怀念那时候的诚信，讲诚信，首先应该是政府的诚信，无论是制度、法律、政策、既然说到就应该做到，如果只是给老百姓开空头支票，给老百姓一个美丽的梦，老百姓还会信任吗？还会诚信吗？现在的老百姓早就被骗怕了，早已没有了相应号召的激情，就算是确确实实的对他们有好处，他们一般也是冷眼看待。别说是农民了，就算是大学生，也被骗怕了，所以什么也不放在心上，禁止校外租房，给贫困大学生每日4元的生活费，可见的有一个大学生响应?再想一想当年为什么要“砸？

说到做到，就算是无意之间出了大错，也比那些不切实际的空谈要好。老百姓眼里不揉沙子，贯彻执行只是下级政府的报告，只是报纸上的空谈。百年以后，再回首的时候，或许在人们心中还是一个毛泽东！

三、一个大国的形象，更有民族性

在目前的人们谈起来，好像大国的形象还是在毛泽东的抗美援朝和周恩来在联合国的沙进杀出，每当中国又在国际上出了什么事，人们还是不无感慨地回想当时的中国！

是的，现在的综合国力上去了，国家有地位了，但是却越来越软弱了。“肉食者鄙”！或许美好的生活和财富容易成为累赘。对美国人们或许还可以谅解，但是对日本我们没有理由不如韩国。中国的人们没有韩国的人们团结，其实，是中国的政府不如韩国的政府强硬。我的一个同学在去年下半年去西安，看到了学生游行，却被警察们拦住了。还记得以前的九·一八，许多的同学自发集合纪念，学校却不允许，今年也就没有了生息，不知鲁迅先生是否又写了“友邦惊诧”？

还有台湾，国内的事，就被这样牵制着，没有了结的的日期。毛泽东真的不应该把这个任务留给后人啊！在他时代，中国人民才真正地显示了自己的力量，才是一头雄狮，而现在不过是一头披着狮皮的羊！哪里有大国的形象，哪里有民族性？

四、毛泽东时代的社会

毛泽东时代的社会只有贫穷，其实没有更多的社会弊病。只有毛泽东让人们变得朴实，真诚，在那个社会里，没有偷窃，没有坑蒙拐骗，没有嫖娼、卖淫和吸毒，没有贪污腐败成风，没有流氓横行，没有文化的堕落……而这一切，却又死灰复燃，你幸福吗？虽然口袋里有几个叮当响的钱。浮躁、自杀、空虚、堕落并不是脱离社会而存在的！在毛泽东的时代，至少可以安安静静地死！

我不能否认现在社会的富足，也不能否认现在社会所取得的成就，不过在人们怀念毛泽东的现象里，我们可以不费力地想到这些，相信，给人们财富的人，人们不会忘记，而给人们精神的人，人们更会把他记在心里。我们不可能平白无故地造神，也不会盲目地造神了，但是如果再有一个人物像毛主席一样，能改变现在的社会精神状态，我们宁愿再一次造神！
毛泽东时代就算有千种不足，但是其干部队伍建设还是很成功的。那时候的官员真能与群众打成一片，与群众同吃同住是太平常的事了，而现在干部下一次乡就是“调研”、就成了头版关条了不得的大新闻、就是对群众的莫大恩赐；更主要的是现在的一些官员贪污腐化成群，骄奢淫逸成风，不顾民生，专捞政绩；还有就是，现在的法纪松驰，远没有毛泽东时代的纪律严明。现在干部队伍中这种情况在毛泽东时代都是不可想像的。 斯大林悼列宁有一句这样的话“共产党人具有特种气质，是特殊材料制成的”。这句话有道理。我把这句话用在毛泽东身上最恰当了，因为毛泽东就是真正的共产党人，但又回过头来想，这句话也经不起推敲，他也是血肉之躯啊，根本不是什么特殊材料制成的。一个血肉之躯的人肯定会有过失的，所以有文革的错误，那又为什么时隔30年人们总惦记他呢？

　　是奇人有怪相吗？或许是，因为他有颗特别的痣，可是我们社会很多人有这样的痣，怎么也说不通啊！

　　是不是他举止不同呢？也不是，50年代，炮打金门，蒋介石一身戎装，也毛泽东却赤裸着坐在海边，他喜欢赤裸，连江青都有意见，这是大家都知道的，就连吃辣椒，红烧肉也是跟平民没有两样。我想这也不是惦记他的原因。

　　是不是他书读多呢？的确他书读的不少，读透24史，这在中国的文人里是无法比拟的，他走到哪里书读到哪里，我想这也不是理由，至少说陈独秀王明书也读的不少，再说他也没有上过显赫的名校，也没有留洋，就是一个师范生。有人说他是天才。林彪喜欢捧，毛泽东不是否定了他提的天才论吗？

　　是军事才能高吗？也许是，在战争年代，他以小米加步枪战胜了美帝，国民党的飞机加大炮，从百十人马开始，发展出几百万人的解放军，最终夺取政权。这一点不管是上层，中层，下层，中国人外国人都不能否认。这是人们想他的理由吗？我认为不是，至少说不全是。蒋介石军事才能就不高吗？如果按照有人那样把蒋介石的军事才能说的一文不值，那么用什么说明毛泽东的军事才能呢？所以这是不符合事实的。为什么没有人惦记蒋介石呢？

　　说了这么多，我想来想去都不是根本原因，根本原因就是“为人民服务”这五个字，不管是战争年代，还是和平年代,他虽然有高超军事才能，再怎样博览群书再怎样智慧都好，毛泽东战胜困难最根本原因就是懂得依靠人民，所以蒋介石不在话下，王明不在话下，既然是依靠人民取得胜利，就要感恩，毛泽东就是懂得感恩，感恩也是中国人民最朴素的感情.

　　毛泽东就是懂得感恩,所以“为人民服务”就是他的座右铭。正因为他胸中装着全体人民，所以才有艰苦的生活作风，严于律己，高瞻远瞩，三年自然灾害，他带头省吃减用，与民同甘共苦，对待子女更是严格，当朝鲜战争传来毛岸英不幸的噩耗，他就说了一句“谁叫他是毛泽东的儿子”。这就是一个特殊材料制成的人，把全体人民看成自己的亲人，他也是一个血肉之躯的人，把自己的亲人看成是人民中的一员。爱有多深就有多深。胸怀就是这么的宽。所以人民怎么不惦记呢？

　　人们不能忘记他，也是跟腐败分子有关，大家想想，我们有句俗语，不怕不识货，只怕货比货。同样人也是比出来的，一比就知道高尚与藐小，同样共产党人，有的人在人民的眼前喜欢耍威，“老子是公安局长，我怕谁啊”，“怎么没有人接待啊，我有事我先走了”，“你是群众你算老几啊”，“我后面有人擎着，我怕你啊”，这样的话充斥在社会的角落里，人民会怎样想啊。有了权就有钱，互相追逐，儿子先考虑，百姓放一边。如果是这样背离人民，我想我们是不是已经丢了“感恩”了，如果是这样人民会更想念伟人毛泽东。

　　伟人毛泽东固然要想，我想惦记他更关键就是要学好毛泽东思想，他的思想精髓就是为人民服务，时时坚持为人民服务，为人民服务跟我们现在中央领导集体的提出的执政为民理念是一致的。我想我们不但要学，更关键的是以自己的实际行动践行共产党人的义务和责任，这样才不会让我们白白惦记他一番。

　　
　　而另一方面，正是“吏治”不严，导致一些地方的官员，独断专行，官商官匪交结，侵吞国家和人民财产暴富，致贫富分化急剧加深。毛时代虽“穷”，但贫富间距很小，一些“干部”的收入甚至还低于一般群众。而当今中国，有的人是食不裹腹，有的人则是极力奢侈。这在毛泽东时代也是不可想像。
　　
　　人，作为一种有思维的社会性物种，渴望公平、公正是一种天性，生活环境的优化并不能消掩人们对公平正义的追求。理解了两个“不可想像”，就不难理解为什么今天会出现“恋毛”热了！
　　
　　而反过来看，“恋毛”热的出现，实是一种警示，警示今天的官员腐败问题和贫富分化问题已到了很危险的地步！“反腐败事关党和国家生死存亡”，切盼高层能铁腕治官、严厉打击，在腐败如斯严峻的形势下，打击才是第一位的。打出声威，遏住不断蔓延的势头，给民心一个有效的抚慰！

同时，毛泽东时代是中国近现代史上中国人民最扬眉吐气的时代，是中国人民最为自豪的时代，那时，我们建国后第二年就与世界头号强国美国为首的22国联合国军出国作战，弱小的中国竟然打赢了！接着，就是炮击金门，西藏平叛，对印自卫反击战，对苏自卫反击战，对越南海作战，爆炸了原子弹，氢弹 发射了卫星 建立了完整的军事 经济工业基础等等，而自毛之后，能令中国人扬眉吐气的事又有多少呢？军事上 政治上 外交上又有多少令中国人民不快的事发生呢？怎么能让中国人民不怀念毛主席！！！！

*** 现将中国普通百姓对毛泽东的评价整理如下：



　　毛泽东把一个支离破碎的、半封建、半殖民地的旧中国改革为一个新兴的、基本统一的、人民当家做主的人民共和国。

　　所以，从政治上讲：毛泽东是中国历史上一位伟大的改革家。

　　毛泽东指挥一支长征后不到三万人的军队，转战南北，通过“辽沈”、“平津”、“淮海”三大战，彻底打败了蒋介石领导的八百万军队。现在仍然是美军西点军校教科书的《论持久战》和《抗日游击战争的战略问题》就是毛泽东军事理论的代表著作。

　　所以，从军事上讲：毛泽东是中国历史上一位伟大的军事家。

　　毛泽东一生坚持自己的理念：“为人民服务”。至古帝王为自己，顶多为了江山社稷。毛泽东却始终高举“为人民”的大旗，这是任何一个帝王所望尘莫及的。

　　所以，从民心上讲：毛泽东是中国绝大多数低层民众的“大救星”。

　　毛泽东一生廉洁。两袖清风，廉洁勤政。作为最高领导人能够艰苦朴素过一生，最奢侈的食物也就是一碗“红烧肉”。痛恨贪官污吏，亲自批出尚方宝剑，痛斩高级贪官张子善和刘青山。而且要求自己的子女和后代廉洁奉公。

　　所以，从廉洁上讲：毛泽东是中国最廉洁的领袖人物。

　　毛泽东一身正气。敢于对苏、美两霸说“不”！敢于捍卫民族利益和国家利益。敢于勒紧裤带，顶住苏美“外科手术”式打击的威胁，搞出了“两弹一星”，让后人在毛泽东撑起的“核保护伞”下过太平日子。

　　所以，从胆略上讲：毛泽东是中国最有骨气的领导人。



　　毛泽东重视人民的疾苦。明确指示医院：“不能为金钱服务、不能为特权服务。必须救死扶伤，实行革命的人道主义”。在缺衣少药的年代，坚持“送医送药下乡”；穷则思变的在农村创立了“赤脚医生”；咬牙坚持国家补贴搞公费医疗和合作医疗，解决广大群众治病难的疾苦；真抓实干的在全国彻底消灭了性病、消灭了麻风病、消灭了血吸虫病。

　　所以，从医学上讲：毛泽东真是华佗在世。

　　毛泽东重视教育。明确指示学校：“教育必须为工农兵服务，必须与生产劳动相结合，必须培养德智体全面发展的学生”。在国民经济十分困难的情况下，坚持“义务教学”。在毛泽东时代，小学学费为1.5元/学期(还包括课本费)。大学全免学费，而且师范、石油、铁路、航空、邮电等大学还给大学生发工资。这样的免费教育体系在今天已经成为千古绝唱。

　　所以，从教育上讲：毛泽东是比孔夫子更伟大的教育家。

毛泽东重视国民经济发展和改善人民生活。为了维护国家的主权和尊严，毛泽东时代的中国既有“帝国主义封锁”，也有“修正主义”压迫。在这种特殊环境下，毛泽东坚持发展经济，亲自写下了指导国民经济发展的《论十大关系》，把一穷二白的旧中国，一举改造成为一个“既无内债、又无外债”逐步走向繁荣的新中国。毛泽东甚至对农民的种地也亲自提出了著名的“土、肥、水、种、密、保、管、工”八字方针。即使在文革动乱期间，毛泽东都一再向全国发出“抓革命、促生产、促工作、促战备”的最高指示重视发展经济。

　　所以，从经济上讲：毛泽东是务实的经济学家。

　　毛泽东历来重视民主和支持民主。早年参加了著名的“五四运动”等民主运动，在党内坚持“民主集中制”的原则。坚持“从群众中来，到群众中去；要相信群众、要依靠群众”的民主作风。在文学艺术领域坚持“百花齐放、百家争鸣”。在社会上坚持“让人说话，天不会垮；不让人说话，天总有迟早要垮”。坚持 “大鸣、大放、大辩论、大字报”的民主作风。

　　所以，从民主上讲：毛泽东是中国历史上最重视民主运动的领导人。

　　毛泽东重视外交战线和改革开放。对待苏联的无理要求，毛泽东敢于说不。毛泽东在关键时刻，利用著名的“乒乓外交”，打开了中美合作的大门。创立了“第三世界”的理论，成为第三世界崇拜的领袖，很多第三世界领导人来华访问因为毛泽东晚年健康原因没有获得毛泽东接见，走的时候还哭鼻子。第三世界国家用轿子把中国抬进了联合国，驱逐了台湾代表，恢复了中国安理会成员的资格，种下了一棵为子孙后代遮风档雨的外交大树。

　　所以，从外交上讲：毛泽东是高明的外交家。
        毛泽东高度重视国家的统一和主权的完整。毛泽东坚持在少数民族地区开展“民族自治”，同时有果敢的维护国家统一。面对西藏叛乱果断命令解放军进藏平叛；面对印度对中国的领土入侵，果断的开展了中印边境反击战；即使面对陈兵百万，拥有数万辆坦克，数千架飞机的苏联强大军事压力面前，就是一个小小的珍宝盗也不轻易放弃。毛泽东说：“宁肯再次上山打游击，也不放弃一寸土地”。他既明确发出了“我们一定要解放台湾！”的时代最强音，也在晚年向蒋介石伸出了和平统一的橄榄枝。

　　所以，从民族利益上讲：毛泽东不愧为民族之魂。

　　毛泽东博学多才。既是伟大的诗人（代表作有气势磅礴和文才飞扬的《沁圆春。雪》和《毛泽东诗词集》）；又是一位伟大的思想家（代表作有《毛泽东选集》五卷和红宝书《毛主席语录》）；还是一为伟大的军事战略家（代表作有《论持久战》和《抗日游击战争的战略问题》等军事著作）；更是一位伟大的哲学家（代表作有《矛盾论》和《实践论》等哲学著作）。

　　所以，从才华上讲：毛泽东集“文学家、思想家、军事家、哲学家”为一身的多才领袖。

　　毛泽东说过：“金无足赤，人无完人”。毛泽东是一位伟人，但也是一位凡人。他也犯有缺点和错误。但是，毛泽东晚年所犯的错误是当时历史环境和客观条件所造成的。如果没有“帝国主义封锁”，如果没有“修正主义压迫”，如果没有中国存在“资本主义复辟”的危险，如果不担心“工农群众再吃二道苦”，如果没有“林彪集团和四人帮集团”的干扰和破坏，毛泽东晚年就可能少犯错误甚至不犯错误。

　　当年，文革中毛泽东连发几道“要文斗、不要武斗”和 “抓革命、促生产、促工作、促战备”的最高指示，有几个人听了？如同现在中央三令五声要重视煤炭安全生产，但下面的官员和矿主同样“阳奉阴违”明拖暗抗一样。所以，今天的人们要站在历史的角度，用辨证的观点，客观地和全面的看待毛泽东晚年的错误和评价毛泽东。几十年过去了，人民群众更进一步认识了毛泽东的伟大，更加怀念一代伟人。

　　所以，从历史上讲：毛泽东是功绩远大于错误。

　　毛泽东南征北战创建了人民当家做主的中华人民共和国；毛泽东把毕生精力奉贤给了自己的祖国和他所热爱的人民；毛泽东一心想着“为人民服务”；毛泽东两袖清风一身正气。毛泽东远比彼得大帝和华盛顿更伟大。

　　毛泽东是中华民族引以自豪的英雄！

　　毛泽东是光照千秋万代的民族之魂！
