# -*- org -*-

# Time-stamp: <2011-09-15 13:57:44 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent



*** 井底望天

**** 也谈毛泽东时代经济（一）
(2009-01-08 13:55:31)

【俺的废话】最近看到了一种左的思潮，由于三十年改革中出现的贫富不均问题，有人开始从新谈到毛泽东时代经济，企图剥夺毛大爷的做人的权利，要把好不容易走下了神坛的老人家，在端上去，颇有推翻中共中央十三届三中全会精神，否定30年改革开放的成绩，要走回教条主义僵化思想的老路。因此随手写了这个系列，算是对新中国前30年的一个回顾。

因为和几位兄弟在这方面有些意见上的争论，所以顺便把想法写出来，希望可以和大家交流一下。

先得把几个概念定义一下，毛泽东时代，从时间上应该是中华人民共和国建国的1949年到老人家去世的1976年。当然也可以把继续高举“两个凡是”旗帜的后毛时代加进去，直到1978年底的十一届三中全会，放弃“以阶级斗争为纲”，否定“无产阶级专政下继续革命”这个政治方针。

另外一个概念就是俺只讨论毛泽东时代的经济政策，而不对老爷子的个人和其他人的互动，作出评价。只是就事论事。

首先看一下从建国开始，到社会主义过渡总路线这段时间，中国的经济政策是什么。http://www.ccthere.com/article/1975410

这个政策是由中国共产党和其他民主党派和人士，1949年9月21-30日，在北京召开的政协会议通过的临时宪法--共同纲领规定的。

共同纲领的第四章，从26条到40条，共14条是有关新中国的经济政策。http://www.ccthere.com/article/1975410

    第二十六条　中华人民共和国经济建设的根本方针，是以公私兼顾、劳资两利、城乡互助、内外交流的政策，达到发展生产、繁荣经济的目的。国家应在经营范围、原料供给、销售市场、劳动条件、技术设备、财政政策、金融政策等方面，调剂国营经济、合作社经济、农民和手工业者的个体经济、私人资本主义经济和国家资本主义经济，使各种社会经济成分在国营经济领导之下，分工合作，各得其所，以促进整个社会经济的发展。

　　第二十七条　土地改革为发展生产力和国家工业化的必要条件。凡已实行土地改革的地区，必须保护农民已得土地的所有权。凡尚未实行土地改革的地区，必须发动农民群众，建立农民团体，经过清除土匪恶霸、减租减息和分配土地等项步骤，实现耕者有其田。

　　第二十八条　国营经济为社会主义性质的经济。凡属有关国家经济命脉和足以操纵国民生计的事业，均应由国家统一经营。凡属国有的资源和企业，均为全体人民的公共财产，为人民共和国发展生产、繁荣经济的主要物质基础和整个社会经济的领导力量。http://www.ccthere.com/article/1975410

　　第二十九条　合作社经济为半社会主义性质的经济，为整个人民经济的一个重要组成部分。人民政府应扶助其发展，并给以优待。

　　第三十条　凡有利于国计民生的私营经济事业，人民政府应鼓励其经营的积极性，并扶助其发展。

　　第三十一条　国家资本与私人资本合作的经济为国家资本主义性质的经济。在必要和可能和条件下，应鼓励私人资本向国家资本主义方向发展，例如为国家企业加工，或与国家全营，或用租借形式经营国家的企业，开发国家的富源等。

　　第三十二条　在国家经营的企业中，目前时期应实行工人参加生产管理的制度，即建立在厂长领导之下的工厂管理委员会。私人经营的企业，为实现劳资两利的原则，应由工会代表工人职员与资方订立集体全同。公私企业目前一般应实行八小时至十小时的工作制，特殊情况得斟酌办理。人民政府应按照各地各业情况规定最低工资。逐步实行劳动保险制度。保护青工女工的特殊利益。实行工矿检查制度，以改进工矿的安全和卫生设备。http://www.ccthere.com/article/1975410

　　第三十三条　中央人民政府应争取早日制定恢复和发展全国公私经济各主要部门的总计划，规定中央和地方在经济建设上分工合作的范围，统一调剂中央各经济部门和地方各经济部门的相互关系。
　　中央各经济部门和地方各经济部门在中央人民政府统一领导之下各自发挥其创造性和积极性。

　　第三十四条　关于农林渔牧业：在一切已彻底实现土地改革的地区，人民政府应组织农民及一切可以从事农业的劳动力以发展农业生产及其副业为中心任务，并应引导农民逐步在按照自愿和互利的原则，组织各种形式的劳动互助和生产合作。在新解放区，土地改革工作的每步骤均应与恢复和发展农业生产相结合。人民政府应根据国家计划和人民生活的需要，争取于短时期内恢复并超过战前粮食、工业原料和外销物资的生产水平，应注意兴修水利，防洪抗旱，恢复和发展畜力，增加肥料，改良农具和种子，防止病虫害，救济灾荒，并有计划地移民开垦。
　　保护森林，并有计划的发展林业。http://www.ccthere.com/article/1975410
　　保护沿海渔场，发展水产业。
　　保护和发展畜牧业，防止兽疫。

　　第三十五条　关于工业：应以有计划有步骤地恢复和发展重工业为重点，例如矿业、钢铁业、动力工业、机器制造业、电器工业和主要化学工业等，以创立国家工业化的基础。同时，应恢复和增加纺织业及其他有利于国计民生的轻工业的生产，以供应人民日常消费的需要。第三十六条　关于交通：必须迅速恢复并逐步增建铁路和公路，疏浚河流，推广水运，改善发展邮政和电信事业，有计划有步骤地建造各种交通工具和创办民用航空。

　　第三十七条　关于商业：保护一切合法的公私贸易。实行对外贸易的管制，并采用保护贸易政策。在国家统一的经济计划内实行国内贸易的自由，但对于扰乱市场的投机商业必须严格取缔。国营贸易机关应负调剂供求、稳定物价和扶助人民合作事业的责任。人民政府应采取必要的办法，鼓励人民储蓄，便利侨汇，引导社会游资及无益于国计民生的商业资本投入工业及其他生产事业。http://www.ccthere.com/article/1975410

　　第三十八条　关于合作社：鼓励和扶助广大劳动人民根据自愿原则，发展合作事业。在城镇中和乡村中组织供销合作社、消费合作社、信用合作社、生产合作社和运输合作社，在工厂、机关和学校中应尽先组织消费合作社。

　　第三十九条　关于金融：金融事业应受国家严格管理。货币发行权属于国家。禁止外币在国内流通。外汇、外币和金银的买卖，应由国家银行经理。依法营业的私人金融事业，应受国家的监督和指导。凡进行金融投机、破环国家金融事业者，应受严厉制裁。

　　第四十条　关于财政：建立国家预算决算制度，划分中央和地方财政范围，厉行精简节约，逐步平衡财政收支，积累国家生产资金。
　　国家的税收政策，应以保障革命战争的供给、照顾生产的恢复和发展及国家建设的需要为原则，简化税制，实行合理负担。http://www.ccthere.com/article/1975410

估计这个纲领写得非常清楚，不需要我一一向大家解释。

国有经济哪里来？靠的是没收官僚资本。当时的三大经济纲领，这是头一条。第二条是没收地主阶级的土地，分给农民。第三条是保护民族工商业。http://www.ccthere.com/article/1975410

官僚资本，其实就是把老蒋底下的大名单列出来，主要是国民政府的国家企业，如控制全国资源和重工业的“国民政府资源委员会”，垄断纺织业的“中国纺织建设公司”，军工系统和后勤系统，CC系国民党党营企业，金融界的中央银行，中国银行，交通银行，农民银行，信托局，邮局，金库，交通部和招商局下属的全部运输，铁路和车辆，船厂，还包括复兴、富华、中国茶叶、中国石油、中国盐业、中国植物油、孚中、中国进出口、金山贸易、利泰、扬子建业、长江中美实业等１０多家垄断性的贸易公司。

第二条是土改，先是把土地分给了农民，然后是互助组和初级社。到1952年冬，开始冒进。后面会说明为啥。http://www.ccthere.com/article/1975410

第三条大家明白，就是扶持民族工商业。

在经济上，以陈云领导的财经委员会在上海，天津，广州等大城市整顿金融，杜绝了银元投机和流通对市场的冲击。通过大量运输物资投放市场，稳住了物价，并和囤积商人斗法，并通过控制银行，收紧银根，弄断了这些投机商的资金链，导致大量破产。最后把国民党时期的惊天通胀控制到了10%一下。http://www.ccthere.com/article/1975410

这段时期，军队在干嘛呢？干了三件事，一是剿匪和镇反，尤其是湘西和广西的国民党残余力量，二是和平解放的西藏，三是和美国带队的联合国军在朝鲜干了一仗。

和朝鲜战争相比，这之后的藏南，珍宝岛都是小儿科。如果说中国要搞备战经济，这个时候估计是最应该。可是不是，这个时候的经济中心，就是恢复生产，建设国家，提高人民生活水平。http://www.ccthere.com/article/1975410

而且还做到了。1952年，相比于1949年，工人工资涨了70%，农民收入增加了30%。

**** 也谈毛泽东时代经济（二）
(2009-01-09 04:49:49)

当然在抗美援朝期间，国内有些敌对势力也是蠢蠢欲动，所以有的镇反。任何政治运动，自然难以避免扩大化和有人公报私仇，打击对手，这也是后来开始出现的问题。

经济建设中，大权在手的官僚们自然会出现贪污腐化问题，就有了反贪污，反浪费，反官僚主义的三反，杀了刘青山和张子善，同时开始了五反来对付私营资本家，反行贿，反逃税，反偷工减料，反骗国家财产，反窃国家情报。

不是说当时没有经济问题，可是对付的手法不是法律的，而是政治运动方式。记得当年大家唱的儿歌--一二三四五，上山打老虎。这个老虎，就是贪污犯。

毛大爷对打虎有专门指示，哪里有老虎？吊睛大虫就在景阳岗上。景阳岗在哪里？“无论党政军民哪一系统，哪一机关，只要是大批地管钱管物的，就一定有大批的贪污犯。”http://www.ccthere.com/article/1975880

如何打？过来人知道，就是计划经济的工业生产，先是编制一个计划，定出一个灭虎的头数，然后算一下比例，然后单子交下去，发动群众自己打，打完报个数上来。

广东的陶铸还介绍了打虎经验，列出8大虎窝：1.经手建筑和营造的；2.负责采购的；3.公私合营里的老板兼职员；4.机关干部家里开商店的；5.解放前后掌握接收物资的；6.知道经济情报的；7.掌握仓库调拨物资的；8.掌管小家务生产的。http://www.ccthere.com/article/1975880

然后就是大胆怀疑，勇敢假设，不需要小心求证。收集的材料，小会挤，大会压，个人吓。用死去吓他，看他招不招。

按照后来的数字，抓了18万，非正常死亡（自杀，逼供而死，监狱和劳改时整死）和残废就是13万多。http://www.ccthere.com/article/1975880

后来安子文和廖鲁言，于1952年10月，写报告给中央要求结束三反五反，毛大爷说了，结束吧，斗争要继续哦，警惕反攻倒算。然后最高人民法院院长沈钧儒写信给中央，进行糾冤和错案。

资本家们有没有问题呢？有。偷税漏税是大家喜欢干的，偷工减料也有人干，而且在送往朝鲜前线的军需和补给里也有。可是群众政治运动，那就是一大堆无辜人士都给清理掉了。http://www.ccthere.com/article/1975880

这时候就有了一个重大的转变。本来按照共同纲领，新中国应该花10-15年时间，搞好新民主主义社会和经济，在之后，视情况而定，再考虑资本主义工商业的国有化和个体农业集体化。

这里俺们就如果一下，那就是说，本来当时那种经济结构，其实非常类似于现在，可以搞个10年，15年，年均10%，中国在1965年的情况，估计和后来看到的文革大不一样吧。http://www.ccthere.com/article/1975880

1952年9月，毛大爷在中共中央书记处会议上讲到，我们不要10年或者更长时间以后，在过渡，而是现在就要开始用10年到15年完成过渡。1953年6 月，政治局制定了总路线和总任务，要在“一个相当长的时期内”，逐步实现社会主义建设与改造并举的路线。1954年9月，第一届人大开会，通过了宪法，算是开始了新中国的第一个政策转变。而在俺看来，是冒进主义的抬头。
**** 也谈毛泽东时代经济（三）
(2009-01-10 06:18:49)

为什么这个是一个重要的转折呢？

因为俺们学过一些马克思主义皮毛的人都知道，马克思的社会发展三段论，是从封建社会，资本主义社会，到社会主义社会的由低向高的发展。社会主义只能建立在成熟的资本主义上面。

按照这样一个理论，那么中国革命已经“冒了进”。说是革命应该是主要依赖于工人阶级，可是新中国建立那一阵子工业占国民经济比重也就是10%-20%上下，中国还是一个传统的农业大国。靠那丁点工人阶级要取得革命胜利，开玩笑吧。

于是马克思主义还是得和中国的具体情况相结合，就结合出了“一个以工人阶级为主，工农联盟为基础”的力量。虽然共产党革命看起来和历代的农民革命差距并不大，至少在革命后的社会发展目标上，是大大不同了。http://www.ccthere.com/article/1977051

但是俺们也学到了另外的一些说法，一个就是生产力和生产关系，一个就是上层建筑和经济基础。就是这些关系必须匹配，那么对新建国的共产党人和他们的民主同盟者们而言，这里就有了一个落后的生产力和经济基础，与所谓“先进”的生产关系和上层建筑的冲突问题。

最后大家看完书本，拍完脑门，顺便对着意见的反方再拍桌子，就得出了最后那个妥协方案，即共同纲领。http://www.ccthere.com/article/1977051

这个共识在于：

1.生产力是落后的，经济基础是落后的。http://www.ccthere.com/article/1977051

2.要好好发展生产力，在可以和俺们先进的社会主义生产关系相匹配。

3.如何发展生产力？就是公说公有理，婆说婆有理。你说用了更好的生产关系，就可以释放出人民的巨大生产热情，他说还是要利用民族资本家好好发展工业。http://www.ccthere.com/article/1977051

4.自然最后的结果就是各种经济体制都允许存在。

那么既然工业中，现在是公有和私有一起来，而刚建国要恢复经济，又要在朝鲜打仗，再激进的人，也不能一下树敌太多。毛老爷发话说，“不要四面出击，树敌太多，造成全国紧张”。http://www.ccthere.com/article/1977051

那时候的经济情况是什么样的呢？1949年私营工业，全国有12万3千户，职工164万人，占总工人数的54.6%。

这些私企的生产总值是68亿元，占全国工农业总产值的63.2%。http://www.ccthere.com/article/1977051

在主要民生产品中，私企在棉纱占46%，棉布40%，面粉80%，卷烟80%，火柴80%。

在1950年，私人企业发展到了402万户，雇佣了662万人，在批发上是占了76%，零售上占了83.5%。http://www.ccthere.com/article/1977051

那么你是应该继续维持私企的重要地位，让资本主义继续发展成熟，再进入社会主义，还是应该对国有企业进行扶持，来逐渐取代私企的地位？

从“共同纲领”来看，应该是扶持国有企业，用一个相对长的时间来完成。今天看起来，10-15年时间并不长，但是对毛大爷等革命家，从1927年搞武装革命，20来年就革命成功，真叫做一万年太久，只争朝夕。因此很容易认为比较保守的不同意见，是落后思想，当然比较容易上纲上线了。http://www.ccthere.com/article/1977051

临时约法上，说的是要“公私兼顾”，情况是私强公弱，就是大家平分天下，也要扶持公有企业。所以1950年初，周恩来老爷子的政务院颁布的“全国税收实施要则”，采取的就是对私营企业的税收比较重。在私营商业的批发和零售环节，实行了多税种，多次征收，手续复杂，而且还是你商品在任何一个环节转一次，俺就征你一道营业税，附加税和印花税。

而对国有经济，就比较爽了。国有商业部分之间的商品流转，就和私企不一样，那叫做内部调拨，不予征税。对供销合作社在税收上是全免。http://www.ccthere.com/article/1977051

但是情况又有了一些变化，1951年12月，开始“三反”，1952年1月，开始“五反”，到6月结束，对私营企业的经营造成了更大冲击。天天查帐开大会，谁还有时间做生意？大批的私营企业停止运转，甚至倒闭，带来市场萧条。

另一个因素是因为共产党的统一，导致了市场的流通环节改善，商品中间流转次数减少了，这就导致营业税中批发那一块减少，或者难征,导致了税收下降。http://www.ccthere.com/article/1977051

为了大规模即将展开的经济建设，又要不断增加税收。由于国民党的前车之鉴，共产党里的经济主管们，尤其是财经块的陈云和薄一波对赤字非常恐惧。虽然解放时也发行了建设公债，但在1952年时，财政出现赤字，必须对税收进行改革。

这就导致了毛老爷和周老爷的一次政策冲突，即1952年的税制改革。 
**** 也谈毛泽东时代经济（四）
(2009-01-11 03:50:15)

要理解1952年的税制改革，其实并不是太难。税务局就是国家抢钱的工具，钱不够了，当然要想办法刮多点上来，至于从谁那里刮，当然就是看那个地主家里还有余粮。政治上的冠冕堂皇的忽悠，那是朝廷里的老爷子们去折腾的，对收税人来说，无关痛痒。

按照当时管理这一块的薄一波的说法，当时的思路是两个：一个是保住税收总量，一个是简化税制。简化税制是因为你的苛捐杂税定得太复杂，人家没有积极性来交税，你没有有效办法监管，最后还不是一样收不上了。http://www.ccthere.com/thread/1975410

薄老爷当初也知道公私税收不同的原因，设想是区别对待，国营不收，私营照收，结果在征求意见的时候，商业部和供销总社摇脑袋。为什么？因为私营企业在运动中打击太大，资本家们有“不跟你玩了”的抵触情绪，税源减少太大。因此还是要奉行“猪要养肥了才杀”的税务原则，让他们休养生息一下。

这样导致的情况，就是你必须到其他地方开源。薄老爷转眼一看，那些国营企业个个是肥头大耳，一身肥膘，就决定从国营企业那里，斩几件回来。http://www.ccthere.com/thread/1975410

1952年9月开了全国财经会议，12月16日-20日，开全国工商联大会讨论，12月26日周老爷在政务院164次会议拍板通过。12月31日向中央和毛老爷汇报，然后第二天正式实行。

可以看到这个税制改革的一大问题，就是冒进，是薄老爷和周老爷的冒进。从出台，到正式公布，没有做踏踏实实的工作，而且宣传上，欠缺思考，在人民日报社论里用了“公私一律平等纳税”口号。http://www.ccthere.com/thread/1975410

这个税制改革，私营企业的负担没有变化，新征税的冤大头落实在了各地方的国营企业，自然就引发了地方势力的强烈反弹。

其实当时的中国，为了恢复经济发展，再加上初生政权，地方上百废待兴，给予了地方非常大的自由。在加上本身中央的各种机构还在磨合，到底该采取怎样的政府结构，都还没有定论，地方已经开始有坐大的倾向。从政治上，五大诸侯进北京，已经是为了之后的取消行政大区做准备。在财政上，周老爷想把中央财权集中，碰到的就是地方财政的痛处，自然会引发强烈反弹。http://www.ccthere.com/thread/1975410

了解中国政治史的人，肯定不会忘记“一抓就死，一死就放，一放就乱，一乱就抓”这个著名的怪圈，而中国的很多政策，都是围绕着中央和地方的利益博弈，有时候中央集中多一点，有时候地方放权多一点，不过是个度的思考。

用今天的话来讲，就是地方的利益集团，以国营企业和地方政府为主的团体，被周老爷的税制改革，动了他们的奶酪。是不是还有个人的私利在里面？当然不排除，只不过，三反里，超过12万党员被清除出党，这种私利不应该是主要因素。地方政府想抓住自己的财权，加上各国营企业的领导和职工，想保住自己的利益，是主要原因。http://www.ccthere.com/thread/1975410

结果就是在这个改革公布的前后，出现了市场不稳的价格波动。面粉涨了6.3%，大米涨了8.8%，北京和其他大城市里出现的社会不稳现象。

对这一现象反对周老爷税改的人说，是因为税改造成了物价上涨，社会不稳。支持周老爷的人说，是宣传没有做好，导致大家思想有点混乱，并辩解说税制公布之前就出现了物价上涨局面。http://www.ccthere.com/thread/1975410

俺的说法，就是两次物价的上涨，都不排除地方政府和国营企业的鼓噪，以此向政务院逼宫。结果就是各路地方诸侯纷纷抗议，到毛大爷那里告御状，以山东局的向明为例，控诉新税法执行后的物价波动，抢购商品，私商观望，思想混乱。并在信中说：“我们真不懂，新税制为什么要在全民所有制企业和私营企业之间画等号？如果这样，社会主义的国营企业怎么能得到鼓励而发展？资本家的企业从新税制里得到了鼓励更加得意忘形，这样社会主义还要不要实现？所以，我们认为围绕新税制的实行，是一场尖锐的路线斗争。” 
**** 也谈毛泽东时代经济（五）
(2009-01-20 06:12:24)

周老爷的新税收是1953年1月1号实行，结果向明的告状信在9号就递交上了中央。两天后的11号，天子脚下的北京城，由北京市委写信给中央，反映的北京的商店里出现抢购风潮，物价猛涨，政府门口大量上访人员聚集，街道了流言传得很快。之后，各大区，省市的财经委员会也反映了同样的社会问题。

这一下毛大爷屁股坐不住了。国民党就是给物价飞涨，民心不稳，丢掉了江山。大概大家也记得那一次的物价上涨，在世界任何一个国家，造成的后果都是社会的不稳定。这一次事件，可以说是周老爷的政务院做事过于冒进，没有做好充分的准备，结果就挨了地方政府和国有企业的一大闷棍，算是对治理国家，缺乏经验的政务院官僚老爷们的上了一堂课。

对这个冒进，薄老爷的解释是，当时匆忙出台，是想趁着年关到了，从元旦到春节这个商业活动的旺季，好好收它一笔税上来。不过薄大爷的想法未免天真，因为人家要被你斩件的国有企业，也是要想办法推翻你这个新税制，哪怕是推不翻，也要搞到你推迟实行，不要在人家最长膘的时候，来榨油水出去。而且各地方政府的招数也是一剑封喉，打的是社会安定的金牌，搬出来的是皇上钦定的圣旨，不经过层层上诉，而是一下就上了最高法院毛大爷那里去了。

为啥说这个新税制违反的圣旨？因为俺前面提到的在1952年9月的总方针变化，开始从共同纲领的10-15年新民主主义建设，变成了10-15年的向社会主义过渡。在这个背景下，薄老爷的“公私一律平等纳税”显然是与这个方向不符。

结果就是反对新税制的各方，就以这个路线斗争的借口来发难，说明你政务院的政策是在压制国有经济，鼓励私营经济，而资本家要求休养生息的号召，只不过是一个借口，让你们这帮政务院老爷，向他们投降。

这一来，毛大爷就在15号写了封信，不光是给了周老爷和薄老爷，还发给了和这次事情关联不大的陈云大爷和邓小平大爷。信中提到：

“新税制事，中央既未讨论，对各中央局、分局、省市委亦未下达通知，匆率发表，毫无准备。此事似已在全国引起波动，不但上海、北京两处而已，究应如何处理，请你们研究告我。此事我看报始知，我看了亦不大懂，无怪向明等人不大懂。究竟新税制与旧税制比较利害如何？何以因税制而引起物价如此波动？请令主管机关条举告我。”

这封信的信息比较有意思。一个就是这次改革，中央没有讨论过，完全是政务院自己做了主。事前通报了中央，不过是12月31号，就是实施的前一天。不光是中央没有搞清楚，而且下层的党的单位，中央局，分局，省委和市委，都没有通报。所以这个税制改革，并没有动员党的组织和力量进行，绕过了党这一环，直接从政务那里做了。所以毛大爷看了人民日报，才知道新东西出台了。

第二就是这个改革，引起了全党的鼓噪，不仅上海和北京这些大都市。看来周老爷对下面的地方势力的反应，估计不足。

第三点，毛大爷说了，俺也不懂经济，你这个税制看了一下，没有明白。究竟和过去的比较，有什么利弊，为啥物价这么波动。得给俺上上课。

估计看到这里，就会有些兄弟，对第三点表示不赞成，认为说毛大爷不懂经济是一个错误的看法。马上就会有人反驳道，那么刘少奇大爷和邓大爷就是经济专家了吗？其实，平心静气的看一下历史事实，而不是拍脑袋得结论，毛大爷和刘大爷都不太懂经济。那时候真正懂经济的大概是陈云老爷子。邓老爷本来不大懂，但是学得快（就像当年拜师刘伯承大帅学军事一样），而且邓老爷比较尊重在第一线工作的专家意见，从来不搞不懂装懂。周老爷也不是太懂经济，只不过态度比较谦虚，虚心听取他人意见。

听起来比较荒唐，而那确实是当时的现状。

批评毛大爷不懂经济，却好指手划脚，经常掺乎进非常具体的经济活动，并不影响对老爷子实现中国独立，民族团结，国家统一，抵御外强的丰功伟绩的肯定，也不排除那个时代为中国的现代化提供了很多基础。


**** 也谈毛泽东时代经济（六）
(2009-01-24 07:45:44)


这个主要发生在毛大爷和周大爷之间的政策争论，即使在今天看来，也是具有非常重大的现实意义。那么这场争论的双方，到底孰对孰错？

俺的看法是，双方都对，但是双方都错。

毛大爷的正确之处在于看到了在当时的经济情况下，是私强公弱，所谓对公私企业一视同仁，实际上起了具体的削弱公有企业的作用，与将来的大方针政策不符。

毛大爷的错误之处在于脑袋里已经定了要社会主义改造的调子，本来说的是10-15年之间改造完成，但是打定的主意，还是恃机而动，能快则快。虽然后来在党内不同意见的制约下，妥协的结果是1953年6月，中央定调为“一个相当长的时间”，可是后来实践的结果，这个相当长的时间，就是3年，就通过公私合营，把私有资本主义经济，过渡到了国家资本主义经济，然后就是社会主义经济。

不是说当时不知道资本主义成分对国计民生有正面的作用，也有反面的影响，即当时吵得头破血流的限制和反限制之争。而是这种彻底地将私有经济中的自私逐利行为，加以限制，企图用政治运动，无私精神，和群众运动的替代方法，来带动经济的发展，几乎就是这之后，经济发展走入困境的主要原因。而且在这种认知下的经济决策，就不可避免的带上了不尊重科学，不尊重实践，相信精神原子弹的万能，和极端冒进思潮泛滥的行为。

毛老爷的认知，还是在于他自己的乐观和对经济活动的不熟悉。其实以他对中国历史的娴熟，不会不知道历代王朝在建国之初的黄老之术，都是轻赋薄敛，修养生息。从汉朝的文景之治，唐朝的贞观之治，清朝的康乾之治，走的都是先修养，再强权之路。而新中国1949年建国后，马上就是朝鲜战争，正是应该修养之际，如果可以在轻工业和商业上，让勤奋逐利的资本家们继续发展还很落后的各行各业，而由国家通过几个大型国有企业，进行控制；在农村继续让富农自己的单干，和中农下中农抱团互助和合作，来提高农业生产，并有国家来协调大型水利工程；在重工业发展上，则依赖于苏联的156个项目，由国有企业为主体，建立起一个完整的重工业基础，那么在20-30年间成为世界经济大国，到不是一个不可实现的梦想。

现在有种错误的观点，想把前30年的经济发展失误，简单的归结到“备战经济”，并认为那时的国际环境恶劣，是造成这种基本认知，和采取的对策的主要原因，从而为30年整个国家犯下的错误辩护。这种观点根本没有考虑历史史实。一个例子就是1952年9月毛大爷在中央书记处的谈话中，谈到10-15年安心搞社会主义改造时，表示“争取十五年不打仗是可以的”。

那么周老爷的正确和错误又在哪里呢？周大爷的正确之处，在于显然看到了私有经济对国家发展的贡献，而且理解在那个阶段，必须给予企业修养生息的机会，让他们能够更强大的发展起来。

周大爷的错误之处，是在于不明白国有企业在经济中和私有企业扮演的角色不同，一位网友评论说，如果在税收上，公私企业同等对待，没有垄断的话，国企一定不是对手。这话是正确的，但是国有企业的存在，不一定要扮演以盈利为目的的经济人角色，而更多的时候，是扮演以非盈利，稳定社会的社会人角色。

中国从春秋时代齐国的管仲开始，就有由国有企业，进行均输和平准的社会功能。就是说当影响国计民生的战略物资—比如说粮食和盐巴等等，出现价格波动时，粮贵伤民，导致社会次序大乱，国有企业就必须以低价卖粮，来稳定社会次序；粮贱伤农，导致粮食生产萎缩时，国有企业就必须以高价买粮，来保持粮食产量。这种平准行为，本质不是为了赚钱，甚至更多时候是赔本，你让它和私有企业竞争，不就成了粮价高的时候，不卖而囤积，粮价低的时候，不买而抄底。那国家还不乱了套？

因此周老爷要对公有企业和私有企业一视同仁，显然是混淆，或者不懂这个企业角色的区别。这也是一个更深刻的经济问题，即政府和市场的关系。搞不清楚这个问题，在陈云大佬手下，为平定各大城市里，被国民党搞出了超级通货膨胀，而立下汗马功劳的国有企业，在周老爷手下，闹了点情绪，就把各大城市的物价闹上去了，搞得紫禁城里一片恐慌。

对国有企业，必须厚待，这是一个铁律。当然如果你让这些国企老爷们坐大，形成了势力庞大的利益集团，搞得政府的号令都不尿你了，又是另一个极端。把国家的公器用来谋取私利，似乎不光是盐铁论时代可以听到的抱怨，而且也是现在中国官办经济的一些现实。

可是另外的一个极端，就是判处国有企业的功能死刑，拒绝承认国有企业在国家经济的平准效用，盲目迷信自由市场的非现实假设，要求中国把银行（甚至中央银行）等等国家重要工具私有化，比如现在几个大银行向外资银行送几十亿一封的圣诞大礼，在重要民生和经济市场上，任由国际势力操纵，都是在实际上打击中国经济的稳定发展。

也许比较一下美国银行的不作为，和中国银行的有所作为，对这个问题就会有比较深刻的理解。

*** 占豪
**** 就张献忠、鲁迅、毛泽东等与网友交流贴
来信：

占豪：

　　见信好！曾经写过信给你，有收到回应，很开心。小遗憾忘记了署名。由于电脑游戏玩的多，脑子动的少，缺少文化，决定起个“种草”为名。此名可否取，请指教下，呵呵！

　　今天看到３月１６日博文，有人就历史人物看法对占兄提出强烈交流，看了觉得很有趣，心情也有点冲动，也想发表点言论。我个人感觉自己头脑还是简单的，看到了表面现象，也许就以为这玩意，或者说这事就真是这样了。举个例子来说，如读书，理论上多读书总是好的，但有的书是毒草，有的书可能是智果，占兄的书读的多，可能经验丰富，能识真去伪。不过对于普通人来说，印刷成册即为书，好像就很容易对成册的东西，表现出“天然”的尊重，容易信书呀！如去年不小心看了些不健康的东西，看到某些网友对历史人物张献忠贬低多多，认为 “张献忠屠川”，简直是变态杀人狂，我看了也以为此人太不讲究人权，太把人当草了！后来听说有“蜀碧”这样的类似野史的东西也有记录其恶行，连鲁迅小时候看了也是愤怒冲上头。当然了，根据其种种恶性，有好事者根据这些“资料”帮忙统计张献忠屠杀有可能上６０００万到６亿人，而四川当时人口可能只有６００多万；另一点，张献忠死于清朝军队后，四川大概持续了１４年的民众反抗，最后据说四川只剩６０万人——假如张是恶魔，清军入川何必引发民众反抗，长达１４年？如果张已经把川人屠了１０遍，四川应该早成了无人区，清军主力随便拉伸，何必拉锯震荡１４年之久？清军屠杀是有传统的，例如“嘉定三屠”，应该是清军屠的结果栽赃给张献忠，死人不反驳了嘛！就这么个简单的事实，到现在好像还有好多口水——某些读书人的品德，或者说历史局限导致了伪书，结果到现在还产生恶劣的影响，误导，愚弄普通人，连鲁迅小时候也曾经被忽悠，太可恶了。占兄，作为游戏玩家，作为不爱动脑的普通人，我对这种伪书伪观点表示强烈的愤怒！因为，很重要，它验证了我的愚蠢。类似还有大家常说“以德报怨”，好像这样是老祖宗传下来的，做的话就高尚起来，就是好孩子！而实际上呢，此话被阉割了—— 出自《论语·宪问》：“或曰：‘以德报怨何如？’子曰：‘何以报德？以直报怨，以德报德。’”孔子的观点和雷锋叔叔多么相似，对同志要春天般的温暖，对敌人大概是要秋风扫落叶！孔老哥并没有叫大家当傻子啊，怎么传到现在变味了呢？肯定有某些东西或人有意的阉割了老孔的话。老孔比窦娥冤啊！——唉，也怪自个：怎么不读孔书，就随便跟着别人骂老孔呢？

　　占兄，我感觉的确被愚弄，但周围还有更愚的呢！您说说，我们该怎么办呀？

　　顺便批评下朱熹，就算是老乡也还是要跟大伙一起拍砖——打着维孔的招牌，卖的好像不是论语。我没读过，按道理是没发言权的，只能以无知的感觉认为，宋朝的封建理学建了座丰碑，把儒道做成了形式，根本失去了内在的精华，最后只留下浓味的裹脚布——当然，精华是什么，我不知道。

　　回到谈历史，说实在，我原本对毛泽东同志不感兴趣，不过很多人谈，我也跟着谈谈个人看法。现在我持的意见是跟风邓大人的意见：功大于过。人非圣贤，孰能无过？如果不把他当圣人，就不会有那么多神奇的要求了吧！我不喊毛主席了，我出生也没见过他老人家，我喊个毛爷爷或者毛泽东同志，不算喊错吧。我想说的是太多人的习惯是：对领导要求高，一切高明指望领导(原因分析应该还是民智有限），当然，对应的话，一旦出错，也请找领导。我不知道是不是全国皆然，但我觉得很多人都是这样习惯的想法啊！文*革当然是场灾难，毛泽东无法免责，当时其他大人物呢？听听邓公的观点吧：“我们这些老一辈的革命家，包括我，也是有 责任的！”——这种观点，我认为比较诚实和务实。

　　习惯有可能是一种无意识的传统文化，或者叫文明呢！以前是唱毛主席唱成了救世主，现在不唱了，我认为不是人的素质提高很多（某些地方应该有提高些），仅仅因为不流行毛主席而已。现在歌风颂德的东西，还是很流行啊！这是传统，说大点是封建传承，简单的把账算到毛泽东身上，是很不对的。拍马屁传统，何止于封建社会，周幽王烽火戏诸侯为拍褒姒一笑，易牙烹子献糜，传承至今，绵延不绝，赞美诗和欢乐颂蔚然成文化遗产，不管物质的和意识的，肯定要保护下去。文*革有“浮夸风”，现在有虚假统计，没少吧（毛时代结束后也没见少）；历史朝代呢，欺下瞒上，酒上谈政，明朝海瑞出了名，仅仅因为清廉而已，结果人送外号“海笔架”“海刚峰”——这样的人在历史上，却不多吧（历史上看来注水也该是潜规则）——小结论：现在的虚啊，拍啊，其实还是要归功于历史传承，不能把这个帐算到人或者党身上。嗯，只要国人敢于正视和更加深入的研究统计后，适当的时候可以把拍和虚申报世界文化遗产。

　　翻看中国历史，不用太认真看，就能发现我们的历史从不缺战争，只缺和平。据说近几千年的历史上，一年无战事的年份，低于３００年，可能低于１００年，我没算过。而新中国成立，我们度过了多少和平年份呢？比起历史上多少朝代都可能多吧！根据历史上看，每次换新皇帝，小的可能叫宫廷流血，大一点可能就是战争——粗糙推算，每届君王运气稳定的话，当政２０－３０年，如果运气再好一点，有可能一辈子只打一次到二次战争。能持续３０年不战争，生在此时可谓盛世！中共的发展建国史也伴随战争史，基本一直处于作战状态——这可能是个悖论：表象上看，共党就是战争狂，让战争狂当家能好吗？而实际上，战争的最高宗旨是止战，或者说共产党的宗旨指导着战争的发展趋势和目的。现在有些言论，国民党以前可能更好呢，而实际上呢，根本无法中国止战。理想的种子，必须适当的土壤才能生根发芽。国民党明显不适合国情。从现在台湾的民主路来说，国外都说台湾最民主，人权也很OK——我看新闻看他们选举，什么国会扔鞋子，粗口乱骂，竞选殴打甚至枪击，我只有对这种民主竖起中指。从文*革的出发点上看——占兄提到了一些，我也仅仅模糊看了一点点，大概是人民政府人民监督——文*革的出发点，这个种子，个人认为还不适合当时中国国情，民智远达不到。发动文*革的初衷，主要应该是出于公，而不是私。从这点上看，以杀人犯的个人理想套用文*革理想，这样说法太水了。

　　邓公接手中国后，要的还是“中国决不能乱”，也压制了８*９学chao（邓公也是军事家加政治家，怎么随便喊他和平革命家呢？我个人认为他不喜欢这样被人乱戴帽子呀）。内不乱，外不战。说到底，要的还是珍惜和平年代，中国太需要和平了！和平时期，也许躺在和平的红利而不知，一旦失去，那是比失去爱情还大的后悔莫及。和平并不是友情赠送和谈判而来，和平之果需要力量才能摘到。反观毛时代，打完内战接外战，东北打完打西南。表象又是很不安分的战争份子，国内吃不饱还去国外作战。然而，打完援朝战争，东北无战事；教训印度后，中印至今无战事。用２场战争换取几十年的和平，这种和平是最大的胜利果实。尤其是中印战争，引发我对毛泽东的高度尊敬和爱戴，发自内心的：毛泽东的国家操盘太厉害了！印度入侵中国，毛泽东以古巴导弹危机为时机，在印度认为中国无力反击的情况下突然反击，短短１个月内反攻进到印度内离新德里３００公里的恒河边，全歼对方王牌旅，沉重打击了印度的嚣张野心！随后马上主动撤退，毫不恋战贪功，完成战略目的，全身而退！印度伤亡近９０００，我军伤亡２０００多，最高阵亡一名营长，而换取到至今的和平！用战争换取和平，在外人看起来几乎不可能的情况下完美反击，而且完美收尾，打赢了战斗，打赢了道义，让美苏这样的国际大国看得目瞪口呆。毛主席的大国操盘，超牛啊！老外就怕毛泽东思想武装的中国吧！毛主席的操盘艺术，常人难及。邓公三起三落，充分感受其操盘水平，收获宝贵人生经验，必定有益增进其智慧和等级。

　　要提醒某些人的是，历史的演变并不是新中国招牌一挂，我们就能把破的旧的，还有传统的东西都抛去了。过去无法抛弃，现在难道超越了？事物的演变，总是个渐进的过程，过程肯定曲折。拿廉政来说吧，多少爱国爱家人士希望，永远不要有贪腐——再简单点，最好一夜之间把那些贪腐的东西全部消失。愿望不错，谁做？怎么做？如果有人这样认为可以“秒”廉，那和“跃进”的想法区别有多少呢？口口声声指责，全然忘了历史发展是有规律的。

　　特欣赏占豪的历史观和唯物观，看问题就是比一般人看的远的多。我搞不懂唯物观，读了任继愈的对话集，个人非常推崇这本书和观点，历史专家，个人认为他看问题就是很扎实的历史观。用历史观看问题，看更长远，更容易透过结果看到本质和原因。他研究的方向是宗教和哲学，而实际上，中国的宗教和哲学，还有生活是穿插黏合在一起的。信仰即宗教——占兄，我能这样粗浅的小结吗？祖先的的历史流传在我们的血液里，中华民族信仰的华夏祖先，让各个不同的族能彼此交融。亡国必亡其史——我个人认为按事实来说咱灭过国，被蒙古人灭了，当时蒙古人是异族；但也可以说没灭，中原数千年的农耕文明虽然被游牧文明短暂冲击，却并没有失去失去文明，失去信仰，可谓“未亡史”。孱弱的宋朝，对应的文化也是衰落。例如，诗经还有“关关雎鸠”，思想行为还自由奔放；“孔雀东南飞”看起来还是可以谈，不过决策权以父母为主，思想活泼度受到约束；到了宋朝，“非礼勿言勿看”，看起来是不用谈了，思想禁锢。先秦文化，百家争鸣，百花齐放，思想空前解放；秦统一疆土，而未统一思想；汉继承秦疆土，继续统一思想“独尊儒术”，有人说其实是假儒，以儒术的包装，卖的其实是道药，区别好像是儒家讲的是教化，要民智，而道讲的好像是愚民？从股势上分析，战国时期，思想百家达到大牛市，汉后开始达到高点，缓慢下行至隋，唐又迎来大反弹，至宋后开始破位，大破。。。。

　　我很喜欢占豪的开启民智，以及立场和理性感恩之心。《我在白宫当记者》特喜欢书里的一句话：记者是有国界的，新闻也是有国界的。而新闻的最高口号是：我们要以最客观的角度来报道！悖论否？立场不同，看事情就不同，符合咱的利益就是OK的，如果加入道德的元素当然更完美。您的立场，我就感觉到浩然之气。你今天的交流信好长，我想是受到对手的刺激才激发你，写这么多吧！事物按两面来看，有一些对手和讨厌的家伙在，可能让你更全力以赴的激发力量去战斗吧！

　　废话说了很多，想听听你对中国教育的看法。我认为问题很多。前段时间看了某老外一句话：“其实，很多人不适合进大学。”我觉得这是句大实话。教育到底是为了什么？开启民智。小时候会问：“为什么要读书呢？”回答基本都是官方：为了报效祖国，为了工作，为了父母的愿望，等等。古人１０年寒窗，而现代人呢？读完大学还是无知者，大有人在。这是问题关键：有很多人真的不适合读那么久。大学已经普及，根本不值钱，已经耽误大家到２３岁，继续下去，读个博士者仅仅是为了找个更好的饭碗。一切只为就业，这样的教育目标，我认为很低，只为就业的话应该多办职业技校之类。我们的制度，不少地方肯定有不合理。教育产业化，让教育也功利——本该育人为本，结果按照饲料养猪的方法来培育，我觉得误了太多人。大学弄多，水平却只有技校水平，规模不够就降级，这种压力下制造出大量的假冒伪劣不合格产品，所以市场最后买单的结果，廉价大学生。好的制度，可以让坏人变好，坏的制度，可以让好人变坏。原先酒店最高５星级，要求很高，在中国，可能适当操盘，４星的或３星东西很轻松和谐到５星，于是乎大家都５星，一片欢乐。这个时候，真５星可不想与假货为伍：我要挂６星！和谐这个东西，处理人际或者群体社会关系还是不错的，用在评审这样的东西上，不一定得体。而要让教育这只公鸡下蛋，唉，我梦见这种事是天方夜谭，结果醒来发现在中国好像可以成为事实。

　　写作不行，写的慢，爱睡觉了。顺便为日本核电祈个福，不一定发自肺腑，不过不祝福还不行：刚买了核电股，结果遇到它们玩核事故！占兄，您说说，我该祝福不？

　　这次我要写上小网名。

　　祝占豪身体健康，心情好。

　　　　　　　　　　　　　　　　　　　　　　福建　　种草

交流：

    历史，分现实的历史和书写的历史。现实的历史已经过去，而留下来的记载必然要受到视角选择、记述篇幅、政治压力、利益取向、价值取向以及史官的认识深度等因素影响。所以，我们从文字上看的历史不可能是真正的历史，那么如何相对更为客观地看待只能是查阅更多的相关资料，然后再结合当时的历史环境以及各种关系去推理、剖析。这就要求我们必须以历史唯物观去看待历史，而不是胡说八道、以讹传讹。更何况，历史记载往被政治所阉，这是客观事实。但，一般情况下，同族的改朝换代相对来说还算客观，而如果涉及异族入侵，则异族所写的历史可能根本与真实的历史相反。特别是清朝，很多历史都是颠倒黑白，这是清朝为了自己统治而做。举个小例子，中国的武圣在清朝前一直是岳飞，但由于岳飞是抗金而名（金为满祖），被民间所尊崇为武圣。清朝为了消除岳飞即消除抗金对大清统治的不利影响，于是就连续封关公N多头衔，甚至已经把头衔置于“关圣大帝”之后再连续淡化岳飞，所以现在我们看到N多关帝庙，却很少看到岳飞庙。

    至于所谓的张献忠的清史料大可不必在意，那不过是一种对抗清将领的一种污蔑。一个起义者，入川作战怎么可能不死人？但一个起义者靠的就是穷苦百姓才能打天下，如果起义者成了屠杀穷苦百姓者他怎么可能存活？这是用脚趾头就能想明白的道理。而清朝入关后嘉定三屠、扬州十日那是实实在在的，是那些民间人士冒死在那个时代记录下来的。所以，对于现在网上很多乱搞历史，甚至一些人竟然在百家讲坛上恶搞历史真是恶心死人。比如说某人讲两宋，竟然将宋辽开战说成宋朝皇帝在出征前就定好战争的一切，然后战场上必须按照皇帝布置的一切做。这可能吗？兵在外君命有所不受这是中国兵法几千年传下来的，到宋朝将领都变成傻子了？既然如此为什么宋朝还能支撑那么久？荒谬得可笑且不可理喻。但有一点可以确认，即作战前皇帝很可能与大臣商议出一个整体战略以及大致战略方向，然后会有一个执行，如果执行中遇到与战略方向上存在问题的将领们不敢做主。历史就是历史，需要用脑子和用心去读，要考量当时的那个年代背景。

    孔子虽然不是思想境界最高，但显然孔子的很多思想确实对中国文化起到了极其重要的作用，而且孔子的思想自汉以来已经被N次修改，特别是那个朱熹，自己本就没那么高结果把中国的很多好的东西搞得乱七八糟，中国的很多文化遗毒其实就是那个时候留下的。比如汉唐，其实中国并不是那么封建和死板，朱熹之后文化上越来越死板。儒家本身其实还是有很多好的东西的，儒家的最大的精神支柱就是基于现世、现实的济世思想，而这个思想本身就是从《易经》衍生而来。为什么后来整个儒家形成儒教统治中国两千年，归根结底就是他除了封建统治外还有立世、济世之思想的存在。同时，孔子追求建立一种理想的人类关系规则，这种规则被后人利用搞成了君君臣臣、父父子子等等，但孔子并非完全如此，他的思想归根结底是立足于当下的现实去建立一种人和的世界秩序，至于这个世界秩序的形式是现实、当下的而没有绝对的所谓封建。

    其实，那个年代并不是某一个人的责任，而是一个时代的责任。毛看到了前苏联精英统治的权本位、斯大林主义等，已经完全脱离了列宁路线。而中国的发展，未来几乎必然是要走前苏联的老路即斯大林化、权贵权力化，考虑到中国封建社会进行了两千多年，文化系统深入骨髓，这种命运几乎是必然。黄炎培曾经因此问题问过毛，毛的回答是“人民直接监督”。毛为此的思考，可谓绞尽脑汁，最后认为这个根就在文化。于是，这个被称作“文化*革*命”的运动开始了。毛要打倒孔老二、干倒孔家店，实际上就是要剪断根植于中国人骨髓的这种封建文化。毛要中国人都站起来（毛在建国时天安门城楼上喊的那句“中国人民从此站起来了”的意义极其深刻，虽然喊出来了但实际思想上上还并未真正站起来）。那个十年，实际上就是一个人民直接监督的巨大实验，是一次文化上要革除封建毒瘤的试验，试验的结果当然是失败的（这种试验几乎是必然失败的，毛以一己之力试图对抗根植于十亿人骨髓中的封建文化思维，那必然是要失败的，甚至连毛自己都受着封建影响，他又怎么可能实现？所以，这个失败几乎是必然，但如果不考虑其后果，这个尝试仍然很牛，前无古人，估计也后无来者。个人对毛没有崇拜情结，但他确是最清醒着、最深刻者、最大胆最有魄力者、是一个横刀立马站立的人，值得英雄式的尊重），教训当然是惨重的，但这仍然是一次试验，这次试验到底是好是坏很难绝对评判。因为，中国的确没有如前苏联那样崩溃（毛早已对苏联断言：如此必然是卫星上天，红旗落地。），但看看现代的发展你会发现它正在向一个权力和资本结合的方向发展，当前社会的权本位、金钱至上，难道还不能让我们反思？所以，个人认为那个十年是一个混乱且教训深刻的十年，我们应该从中吸取教训同时也要有所反思，不应该让那种极端发生，也不应该走向另一个极端。

    中国封建社会运行了两千多年，突然进入一个新社会不可能瞬间脱掉历史的影响，表新出一些东西时必然，这种必然其实就是时代特征。事实上，真正不断提出改革、要求改革正是GCD，这其实就是为什么历史选择了GCD的根本原因，适应力足够强。但，如果未来无法适应社会发展，那也会像历史上任何一件物事一样消失，这都是再正常不过的事情，这个世界没有千秋万代，只有“成住坏空”的循环。

    无论腐败也好、虚假也好、愚民也好、娱民也好，基本上都是世界通病，并非中国独有。比如美国，腐败是制度上的，议员接献金以维持自己的议员地位，然后议员就代表这些利益提出一些法律法规的制定，这种制度性的、法律性的其实是更可怕，只不过这个矛盾因为美国在世界国家生物链上的最上游矛盾没有爆发而已。如今，当世界性金融危机，美国的债务危机无法摆脱的情况下，美国不也时不时发生大的示威吗？再比如说虚假统计，美国同样也是存在，也是规则上的，比如说巨大的债务漏洞就是通过新会计准则而掩饰的。相比美国，说心里话我们的手段不够高明，国家还不够强大。那么，怎么破除这些世界性的通病？即每个人必须提高个人的智慧层次、知识水平，这样不存在指挥层次、知识水平的鸿沟，也就很难有权力和物质的鸿沟，那么社会必然会走向更为和谐的状态。这种博弈，必然是每个人自我意识的觉醒，必然是立足于独立思考与自力更生。这个力量如果在一个人身上，那么它就能给这个人带来巨大力量，如果世界上每个人都有这种力量，则世界将进入一种更为公平、合理、幸福的社会模式。作为我个人，我一直希望中国能够来一次伟大的文化复兴。海瑞其实就是因为清廉，其实这个人根本没干出什么实事，也没什么政绩，但就因为清廉却能名垂青史，可见中国历史上官场一贯黑暗，这也是为什么我们每个人一定要齐心合力，避免中国重蹈历朝历代覆辙的根本原因。

    中国的事情太复杂，比如二十多年前那件事，说白了就是别有用心的人要搞乱中国，看看东欧剧变，1991年前苏联解体后前苏联范围内的境遇，你只能说中国幸运了。这个世界，除了中国人自己没人愿意中国强大，现在连英国人和法国人还记得曾经八国联军入侵过中国，特别是英国曾经和中国打过鸦片战争，都担心中国强大了报复。东边小日本更不用提，中国强大收拾它的可能性最大。北边毛子又何尝不是？北边还有一百五十多万平方公里的土地被毛子占据。中国强大不一定非要对别人如何，但只有中国强大才能避免被分割的命运，因为外面都害怕中国强大，所以有机会都不会放过削弱中国的机会。这也应该成为每个中国人自强的最大理由，因为你不强随时可能面临着外敌入侵，中国最近两百年还经历的不够？如果不理解就去看中国近代史，去网上看看那些日本侵华时的照片，看看那经大屠杀的照片、纪实片等，你就会深深的理解这些。有人说占豪很爱国云云，其实完全不必这么大帽子，就从私人来说我不想再让近代史重复，我希望中华崛起，希望中国人都能够站起来而建立属于自己的幸福。这样，你好我好大家好，何乐而不为？

    个人认为，人不可被唯物观所限，我也不是一个唯物主义者，也不是一个唯心主义者，但我知道历史应该要有历史唯物观，这是看待历史最基本的底线。而且信仰和宗教也不是一码事，宗教是宗教，信阳是信仰，你信仰的不一定是宗教，宗教的也不一定绝对有信仰，挂羊头卖狗肉的宗教多了去了，没有信仰的所谓信徒也是成把抓。

    中国教育问题很多，多得让人感到漫无头绪。但我个人认为，中国教育最大的问题是缺少一个符合历史发展底蕴文化，这种新的文化不出现，教育总还是混乱的，而这种混乱在一轮轮改革中演绎着。试想，如果一个社会没有一个高层次的价值观，大家要不是拜权，意图望子成龙的方式去培养，要不拜金······总之，每个人的思想层次不够高，这教育的层次能高吗？当我们指责体制时，我们发现我们并未把自己当成体制的一员，也没有去试图用自己的力量来中和这种力量，一面积极压着给孩子培优、补课，一面又大骂教育制度TMD太差了，都应试教育。那为什么不从自己改变？和孩子一起成长？莫将自己的意志强加给孩子？让孩子能够在一个相对宽松的环境中成长？这是我们每个人的问题。而再看体制，首先教育投入就不够，国家嘴上说重视教育，可教育投入为什么不增加？喊了很多年结果每年投入都不够。这些责任，是应该相关人等承担的。而教育体系、制度，从某种意义上所教育变成了政绩工程，变成了某些人的政治资本，这显然是政府的问题。所以，这是一个相辅相成的，是大家一起的共业。所以，关于教育，我们每个人都有责任。个人意见是：从自己做起，让教育改革从每个人起步，教育体制必然会在这种“细胞改革”的推动中而改革，这就是历史的车轮，无人可当。

    另外再强调，“开民智”非占豪的，占豪只能开自己的智，无法开任何人的智，每个人也只能开自己的智，与他人无干。这就像抛砖引玉，抛出去的砖能否引玉不在砖而在玉，无玉就是抛出一个帝国大厦来也还是无玉，有玉早晚能够璞玉成器。

    不过，酒店好像原来是五星，后来世界上都在给自己加星，阿联酋的帆船酒店是七星。呵呵，所以这也还是那回事，当今世界流行升级，呵呵。

    占豪的博客只要能够坚持一天就会坚持一天“独立思考”、“自力更生”。能不能理解那不在占豪而在自己，与任何其它都没有干系。所以，一切都是缘分，缘聚缘散犹如花开花落，人生要有立锥之地不可能任由挥洒，但思想可以任由挥洒，而思想的瓶颈完全取决于自己。
**** 正确看待毛爷爷——转载占豪
2010-03-22 15:45
另：一些战友因为笔者午评中说了“回到老毛时代生活一个月你就要死要活的回来”就借机反毛大爷。毛大爷是伟大的，伟大的足以说是千年出一个的政治家，否则为什么至今在西方毛的威望还如旗帜般飘扬着？毛大爷的伟大在于他用他的智慧借力打力的不但成全了全中国也成全了他自己。这就是政治高手。在毛大爷那，小的能变成大的，大的能变成小的，其能量非一般人可比。否则，一个几乎啥都没有的中国却能在毛的带领下快速站稳脚跟？敢跟美国干、敢跟苏联干、这不是一般人能干出来的。毛时代的落后是历史原因，那是中国积弊了千年、羸弱了一百多年，清末被八国联军搜刮、民国被日本搜刮、即使快解放了还被国民党捞走了稠的导致的。我们今天的强盛势头，如果不是当时老毛在工业上打下根基，不是在人口上扎下根基，中国岂能有现在之成果？中国岂可在连续出现路线歪斜的情况下依然能够平稳走到今天？这些都是毛大爷打下的基础，这是不能忘本的。

    毛大爷的思想看看毛泽东选集就能知道，在中国革命史上的确无人能出其右。邓小平那是什么人物？文革后期能够力挽狂澜者，可在毛的时代只有被摆弄的份。这不是邓公不伟大，邓公的伟大在后面路上已经证明了，这只能证明毛太牛。当然，毛大爷思想上也是有局限性的，那就是对资本主义根本规律的认识不够，但也别说那个时候，当今又有几个人能够认识得够？邓公当时也只是知道之前的路走歪了但也不知道歪在哪？所以也只能是“摸着石头过河”。但那已经是当时最先进的思想。这就是现实，每个时代的人必须干每个时代的事。时间不可能倒流，人也必须向前看。文革后期给中国带来了巨大的破坏性，但那是毛大爷的思路是避免中国苏联的老路，是希望进行中国式的民主，让人民直接监督政府；可最终这种失败也是必然的失败是因为压根当时中国就不具备这样的环境且不可能让每个人都监督政府，这里必须有一个机制过度。当时无疑在走民主化道路上进入了极端。但看看现在，我们这三十年是不是又走向了另一个极端呢？监督机制在哪里？所以我们现在也应该反思文革其本身的价值所在，即要走中国式的民主之路，这种路不能是文革式的，但绝不能是现在这种积弊下去的路。文革之路必将失败，当下之路如果不进行改革也是死路。

    
**** 
*** 会同天下
*** 【金鸿评论】闲话国内政治
 (2010-10-03 21:10:59)
 【金鸿评论】中国的内政，我一般是不做讨论的。原因很简单，中国是一党专政，对国内政治消息层面上管制很严，很难得到全面而又准确的第一手信息。没有全面而又准确的信息，就无法对国内政局做出正确的判断，不全面的信息，往往会得出错误的结论。

我一向认为，一个卖国的、软弱的或者说是无能的政府，是不可能真正做到对外强硬的，也不可能得到其他国家的尊重。这一点所有人都应该会承认。所以，我一直在分析国际局势，从国际局势的走势中，去反推国内局势的一些基本面上的情况。

前几天写完了《04年以来的大国斗争回顾》一文，感觉到自己可以基本看清全球局势的发展，以此反推也能对中国的内政有大体有所了解了，今天就做一回分析。当然，分析中提到的东西，都可以公开途径搜集到：

 

 

【金鸿评论】先从整体上说一下03年以来国内正面的一些情况：

中国国内近七年来的变化极大：取消农业税、农村合作医疗和养老金让农民得到了实惠，工人退休金也提高了，九年义务教育全免了，整个社保体系在不断完善；产业结构调整稳步推进，反贪力度是公认的，扫黄打黑的成果大家也看的到。至于阴暗面，那肯定是有的，而且是很大的，这个所有中国人都明白。

为了发动群众监督，北京力推网络舆论的监督作用，这一点从四五年前就开始做了。我记得是17大还是之前的一次重要会议上，温总理见记者，先问有没有网络媒体的记者到场，要先接受他们的采访，后来胡哥登陆强国论坛，再开到微博，到今天的中南海直通车。这些是干什么的？有没有人想过？记得网络呼声第一次战胜负面事件是正龙拍虎，不知道大家还记不记得，当时网上骂了多久才骂赢的？再看现在，一般的负面事件只要在网上曝了光、有了影响，大都马上就查，当然也不排除曝光者遭报复的情况。斗争中总有反复，通向光明的道路也不是一帆风顺的，这个大家都能理解。

有些爱国的人，从来不宣扬这些正面的事情，总是盯着那些反面的东西不放，要说爱国，总要先树立荣誉感吧？一个不能让人感到自豪的国家会有多少人去爱？光宣传负面的东西，如何树立人们的荣誉感？

家里有个孩子，期末考试考了99分，回到家家长一通骂，为什么少考一分？为什么不仔细点？为什么难题都会做容易的题却做错了？你是猪吗？这时的孩子，会是什么心情？什么想法？另一个孩子，考了65分，家长说，不错，上回不及格，这回65了，有进步，好好学，下回考70分，怎么样？这个孩子又会是什么想法？

教育人，正面引导的作用要远远强于批评。这是基本的育人原则，应该都能明白吧？

那些有一定水平的、整天骂这个黑那个乱的人们，你们有没有想过，你们天天宣传这些负面的东西，让那些有爱国心却水平低一点的人们如何看待我们的政府呢？他们是该支持还是该反对？

 

 

【金鸿评论】今天的中国很乱很麻烦，所有人都知道。毛主席时代多好，当官的清正廉洁，老百姓真诚负责，既无黄赌毒，也无骗奸团（黑社会）。今天呢，没有的全有了。胡温接手时的局面有多难谁想过？这一点从国际局势最能看出来——国家强大的时候别人都怕你巴结你，国家弱时混乱时别人就都欺负你瞧不起你。

毛主席逝世后，邓小平访美。当时美国人为了巴结中国，安排一帮小孩欢迎、唱歌，唱的什么歌呢？我爱北京天安门，我爱毛主席。想想吧，视红色政权如洪水猛兽的美国人都要热爱毛主席了。

99年，我们的大使馆被炸，两国论盛行，03年中国爆发非典，许多人说是CIA干的。这时的中国面临着什么局面？国家要被分裂，人家把火烧进了我们的里屋（非典）。这时的中国有多少贪官，有多少卖国贼？老百姓心里也都很清楚，虽然不知道是谁，但都知道一定有，而且不少。

这时的胡温面临的局面，其实和刚刚走完长征的毛主席是一样的：

当时，毛主席面对的第一大敌人是日本，日本要是占领了中国，他们自然也就被消灭了；第二大敌人是蒋介石，千万百计要灭共安内；第三大敌人是各路军阀，唯恐被红军抢了地盘；第四就是各种地痞流氓黑帮，共产党推行那一套和他们格格不入。毛主席手里只有几万疲惫之师，却要面对十倍百倍于已的形形色色的敌人，他是怎么做的呢？抗日民族统一战线。不管是谁，只要抗日，就是朋友，就是兄弟，包括老蒋，包括杜月笙，甚至有悔过表现的汉奸都可以给机会。这么一来，红军的敌人大为减少，与蒋介石的矛盾也成了内部矛盾，成了可控的小摩擦。结果是什么呢？八年游击赶走日本后，红军发展到两三百万，势力空前壮大。

03年胡温一上台时，有政令不出中南海之说，这句话的意思只要不傻的人都明白。其实想想也是，我们身边的干部有几个清廉为民的？很自然，真正能贯彻胡温意图的人是非常少的。既然下面的人大部分都不是自己人，又得让人听自己的话，应该怎么办？不要说换人，换人不是那么容易的事，既然能爬到相当的位置，下面肯定一群人支持，闹不好下面的人换不了，上面的人倒坐不稳了。这个时候，只能在一些次要问题上做妥协，这是没有办法的事。

其实，政治就是有原则的妥协；作无原则妥协的，都是自私自利的政客；不懂得妥协的，都是政治上的失败者。古今中外，概莫如此。至于有人认为的胡温不一心的说法，太外行。看看中国的历史，哪个有作为的皇帝会用一个不跟自己一条心的宰相？一把手是路线的制定者，二把手是路线的执行者。一把手制定的路线二把手都不执行，还指望谁去执行？没有自己路线或者路线不能被执行的一把手，绝不是有作为的一把手。胡哥是什么人物，大家都应该有数。

当时的中国，面对的第一大敌人是美国，他们千万百计要中国放开资本管制，开放金融业，好接管中国经济，把中国变成殖民地，如果真那样了，次贷危机肯定不会出现，吸中国的血就提前把那个窟窿给补上了，当年的东南亚金融危机不就成功的为美国经济补过一次窟窿吗？不然克林顿凭什么那么狂？当时美国经济都出现拐点了。第二大敌人是国内的卖国势力，第三大敌人是各路贪官，第四就是各种民族资本势力（毕竟不是一条路线）。这时的胡温应该怎么办呢？自然只能团结一切可以团结的力量来对付美国。其他的，不论以前是贪过的、卖过的、黑过的，只要愿意改，一律给生路。只要打倒了美国，就什么都好说了。不然，光打内部敌人，被外敌钻了空子，国家都成殖民地了，那时还有什么国家利益民族利益可言？胜利也是失败。

毛主席带领着那么弱小的红军取得了天下，首先就是靠的统战工作，打日本是，打蒋介石是，建国后对付美苏也是，三个世界嘛。那些整天盯着阴暗面不放的爱国者们，大都在喊毛主席万岁，打着毛主席的旗号反对这、反对那。从不宣传中国取得的成绩、专曝阴暗面、专门强调内部斗争，这方面乌有之乡网站极具代表性，一帮自命不凡却又内战内行外战外行的家伙。请问你们，毛主席以前做过的事，你们为什么不做？毛主席最拿手的绝活，你们为什么不学？你们是不是在打着红旗反红旗？

 

 

【金鸿评论】到今年秋天，胡温应该真正掌握主导权了。这一点从政治和经济两个层面都有所表现。政治层面的宣示应该在今年的国庆节，三个动作：公祭先烈（铁血），嫦娥奔月（腾飞），巡航钓鱼岛（收土）。这样的威严与自信，令人振奋！

同时，两个经济层面的也有两个大动作：

一个是战略性新兴产业规划出台，这是他们第一次采用正面手法调整经济结构。以前的两轮调整方式，一是借用外力（人民币升值）淘汰血汗工厂，一是趁火打劫（全球金融危机）逼欧美交出技术，只有这一次是正面调整。要知道，这种经济结构层面的大幅度调整，绝对会严重损害利益集团的利益。以前不做是因为受牵制，今天能做说明什么？

二是9月底出台的打压房价的政策。以前打了多少次房价都没有成功，到底是为什么？利益集团在阻挠和对抗是绝对不能忽视的因素（当然这个利益集团和上面所说的不一定是一个，我只能概括一说，对于党内的派别，我基本不了解，但我相信毛主席的那句话，党外无党，帝王思想，党内无派，千奇百怪）。以前要牵就方方面面，打压房价的政策自然只能是打屁股，这一次完全不同了，是打脑袋。房价上涨的原动力是什么？住房按揭制度。如果不允许贷款买房，肯定不会有高房价，房价一高就买不起了，自然不会有地产泡沫。正是按揭制度对买房人未来收入的强大透支能力，才推动着房价节节攀升。在这其中，首套房的低首付（二成）是最根本的。以前出台过的所有调控政策当中，从来没有提高首套房首付比例的，这次有了，这是打脑袋的做法。打屁股是打不死人的，打脑袋却完全可以。这么一打脑袋的直接结果，就是把一部分想买房子自己住的人（刚性需求）赶出了买房队伍。不要以为二成到三成只增一成，对买房人来说，这相当于多付了50%的现金，是非常要命的。同时出台的打压屯地的政策和进一步扫清外围（打击炒房）的动作，都可以显示出重重的杀机。敢于一剑穿心打压房价，足以说明胡温有能力在稳定局势的前提下正面打击利益集团。

 

 

【金鸿评论】下面，再分析一下过去几年中国面临过多么险恶的国际环境。

美国一直想逼中国放开资本管制，胡温死死抗住坚决不放。不得已，美国只好通过地下钱庄走私美元进来，这就导致了中国的外汇储备暴增。07年上半年，这方面的报道奇多。习副调到上海任书记后，马上查出了大批的地下钱庄（之后很快去北京了，呵呵）。记得07年夏天的时候，有新闻直接说，3000亿美元热钱进了珠三角楼市，股市也一样，07年超级大牛市。而此前从04到07年，人民币总升值21%。这时如果不小心，中国会如何？

广场协议以后，日元升值一倍，出口制造业大受打击，日本政府为了改变局面开始降低利率拉动内需，造成了流动性泛滥，这时美国又封住日元对外投资的道路，之后无处可走的天量日元一头扎入了股市楼市，之后股市楼市就得了疯牛病，最后被美国用期指刺穿泡沫，日本人十年的辛苦钱全送人了。

中国这时也面临着同样的可能性，胡温又是怎么对付的呢？07年10月出手打楼市，二套房首付提至四成，楼市立即冰封。进楼市的热钱全部被套，之后的11月，又开始砸股市。

我没有内部消息，所以太准确的情况也就不得而知了，只是从表面推测。关于股市，08年时有一篇文章传的很广，名叫《神秘机构在高吸低抛做空中国A股》，从中可以看出一点门道：

 

T2****神秘空军1号席位，900亿资金高空砸盘，1023次现身龙虎榜，倾仓抛出50亿中国石油。

很多人把中石油看做是A股下跌的罪魁祸首。其实，中石油只不过是一个工具。如果看上交所的TopView数据，相信大家会比较清楚。在几个主要指标股上，有一个账号在做空中国股市，A2****！就是这个席位把中国股市牢牢地压制在死亡线上，所耗费的成本实在不是我等可以想象，大家可以看看中国石油、中国神华、建设银行等最大盘股的近期成交记录，这家A2****刻意不惜代价地每天十几亿甚至几十亿地抛。其背后的目的是什么，很令人费解。  

A2****席位的交易风格与众不同，当11月5日中石油以比H股价格高一倍的48元高价登陆A股市场时，该席位并未逢高套现，仅在第二天股价跌至40元一线时抛出14.79亿元，之后便一度销身匿迹。当上证综指11月28日开始进入反弹后，A2****席位却又再度发力，分十天集中抛售中国石油，并且是股价越低，抛出数量越多。  

从11月28日到12月12日，A2****席位共卖出近32亿元的中石油，最高成交价32.96元，成交均价31.37元  

在大规模抛售中国石油的同时，A2****席位还以每日数亿元的规模抛售中国神华、中国建行等大盘蓝筹股，其间该席位的卖出金额始终高居榜首，卖出数量常常是排名第二席位的7-8倍。A2****太神秘了，没人知道它是什么机构。因为在信息披露中，该席位被上交所标注为“其他席位”。但有一点可以肯定，它很强，手法凶悍。  

根据有关规定，网下申购的公开发行股票，至少要等到该股上市3个月以后才能出售，这意味着T2****席位抛出的32亿元中国石油，将全部来自网上申购，所动用的资金是个天文数字。”据临汾久信投资总经理张红记测算，如果T2****席位卖出的31.57亿元中国石油，平均价格在31元，其持股数至少在1亿股以上。

以中石油发行价16.7元，网上中签率1.94292037%计算，中得1亿股至少需要859亿元申购资金。这一资金规模已经超过号称国字头机构云集的打新股基地——中信建投北京三里河营业部，此前外界曾猜测聚集在该营业部的打新资金总量也不过500亿元。

859亿只是T2****席位掌握资金的一部分，如果考虑到该席位在其他个股上的进出，其资金量至少应该在900亿元以上。   

统计显示，股市大跌期间，T2****席位在抛售权重股上可谓不遗余力。以中国石油为例，除11月6日一天抛出14.7亿元外，该席位在11月28日至12月10日期间几乎每天都有上亿元规模的出售行为，此期间合计售出31.57亿元，从而使该席位在中国石油上的总抛售额达到46.36亿元。  

中国神华是T2****的另一大抛售对象。同样，这家席位也并未在中国神华上市后的上涨途中或10月15日创出94.88元历史新高附近套现，而是将筹码留到11月14日的底部区域——67元一线用于“砸盘”：11月14日，中国神华经过1个月的下跌后终于初露反弹曙光，当天在65.7元开盘后一路上涨，最终以9.94%报收。恰恰就在这一天，T2****开始了它的“砸盘”行动，当天卖出3.1亿元。此后11个交易日内，该席位合计卖出29亿元，成功将中国神华反弹势头压制，最终令其跌破支撑位，创出60.50元新低。11月14日到12月13日，T2****卖出中国神华共达32亿多元。（完）

 

 

【金鸿评论】两个席位号我马赛克处理了一下，大家只要能看出是什么事来就可以了。这两个席位是谁的呢？有人查过，只查到了四个字“机构专用”，别的就查不出来了。于是就有人猜是财政部和汇金公司的。到底是不是呢？从道理上讲应该是，当时在进行货币战争嘛。如果站在全球局势看，那几年应该是这个样子：

06年年初，中国介入伊核六方会谈后马上激化伊核问题死死缠住美国，伊朗则在中俄欧三国的保护开始加大对伊拉克反美武装的支持来消耗美国的实力（同时还有阿富汗）。这时的美国，对于不能接管中国经济也应该是心里有数了。所以，美国也想尽快解决两伊问题来减少烧钱。06年7月，美国想用武力解决掉伊朗和哈马斯，结果被朝鲜导弹试射（中国）和随后的黎以冲突（中俄）挡了回去。到了10月份，美国感觉到问题主要出在中国身上，就想通过切断巴基斯坦通道来解决问题，结果中国安排朝鲜引爆了原子弹，这是胡哥对小布什进行战略警告，宁可打核战也不会退出中东，结果小布什被震住，巴铁通道保住了。

进入07年，美国经济失血严重，次货危机开始一步步显山露水。之前从06年开始，大量热钱进入中国推高股市和楼市，所以07年是中国房价涨的最疯的一年，也让中国的股市也是历史上的超级大牛市。当楼市和股市推高到相当程度时，北京先发制人冻住楼市，接着出手砸盘打压股市，在巨额套现的同时，也截住了美国希望获利回流自救的资金。因为中国的资本项目是管制的，所以当北京砸盘的时候他们只能通过地下钱庄往里走私钱币托市，这样进钱的速度很慢，数量上也不足以顶住北京的抛盘。结果股市里的热钱也被套住。

07年7月，次贷危机引发全球股市暴跌，这时，美国国会通过了伊拉克撤军的时间表，准备好了退路，万一经济上撑不住了就撤出伊拉克少烧钱。到了08年2月，科索沃独立，欧元准备趁美国经济衰弱的机会抢班夺权。6月份，俄罗斯国际商品原料交易所成立，普京也开始与华尔街争夺石油定价权。7月份，地中海联盟成立，欧元挺进中东。俄欧联手挑战美元霸权。

之后，美国连续做了几件事，一是美国从7月份开始反手做空石油从经济上打压俄罗斯；二是在8月8日又挑动格鲁吉亚闹事，结果格鲁吉亚被肢解；三是8月下旬与伊拉克达成撤军协议，正式开始撤军，显然美国这时已经烧不起钱了；四是在9月份让雷曼兄弟倒闭，把欧洲也拖入了金融危机。很快，美俄欧三家全部陷入了泥潭。这时，中国的出口也严重受阻，不得已启动了四万亿投资计划。

俄罗斯动手打格鲁吉亚的时候大量抛售了美国两房债券，当时想和中国一起抛，中国出于制衡的考虑就没有接受。结果俄罗斯抛完了两房债券之后，美国宣布接管两房，保证了两房债券的安全，之后就把油价打到了30美元，俄罗斯经济也高亮红灯，中国则趁机完成了战略石油储备，在这里中国应该省了不少的钱，毕竟油价比起147美元时连零头都不到了。07年年底北京从股市上应该套现巨大，那么这些的钱会用到哪里去呢？如果是我，我肯定拿钱去国外找合适的矿产资源企业抄底。上面的所有内容都只是我个人的分析，是真是假无从验证，只是从逻辑上做出的判断。

当然，那时被套的小散是极多的，这也是没有办法的事，个人那点损失和中国经济的崩溃相比，实在不可同日而语，只要国家不倒，个人还有机会赚回来。如果中国股市当时再涨一段时间后被被获利巨大的热钱砸崩了盘，接着楼市崩楼，人民币暴贬，中国也就陷入了经济危机，跟着就是大量企业破产，获利巨大的热钱再杀回来低价收购中国企业，中国经济可就真的被人接管了，那时所有中国人的存款都会被打劫。

当然，有人可能说，北京的做法不是在操纵股市吗？是的。股市开门就是为了让人操纵的。在过去的两百多年里，欧美的顶级资本家们，哪个不是靠操纵股市赚钱的？当然，各国在操纵股市的同时，也都在打击操纵行为。这又是为什么呢？为了给散户们一个交待，抓几条小鱼给亏了钱的散户们出出气，不然以后哪个小散还到股市里扔钱呢？打击操纵是为了以后的操纵。其实，操纵股市也好，开动印钞机抢钱也好，都只是经济行为，没有好坏之分。真正的区别在于，当事人是把搞到的钱塞进了自己的腰包，还是回馈给了人民。

当然，北京操纵股市的出发点，是稳定经济，如何用股市来配合经济稳定呢？大家可以想，不过这里面的道理是非常复杂的，但是如果想明白了其中的道理，做个亿万富翁很容易。

如果不信我可以算一笔帐：一般说来，股市十年内大约上下波动五六个周期，只要踩准了点，在大底时抄入，大顶时出逃，只要选股的水平不太差，那么一波上涨之中赚4倍是很轻松的事情，股选的好的可以赚到十几倍。按5个周期每次赚4倍算，4*4*4*4*4=1024倍。投上10万，十年可以赚到一个多亿，不用做庄，只要跟庄就可以了。
*** 【金鸿95】被冤枉的毛主席

按照西方经济学精英的说法，毛主席不懂经济。

如果按照政治经济学的概念，经济是指社会生产关系的总和。毛主席带领着中华民族在一穷二白的基础上建立起了完全独立自主的经济体系，这个体系是除了美国苏联没有第三家的，这还不懂经济？英国法国日本没有一家能做到的，那他们的领导人懂什么？

其实，吃饭穿衣是最基本的经济。说到这里，有人就会说“毛主席时代挨饿”云云。其实，真要为中国人解决吃饭穿衣问题、让中国人过上好日子、为中华民族的长远发展打上好基础的，恰恰是毛主席。

拿吃饭来说吧，离不开袁隆平的水稻。而袁隆平是从1964年开始研究杂交水稻的。1973年实现三系配套，1974年育成第一个杂交水稻强优组合南优2号，1975年研制成功杂交水稻制种技术。 1975年冬，国务院作出了迅速扩大试种和大量推广杂交水稻的决定，国家投入了大量人力、物力、财力，一年三代地进行繁殖制种，以最快的速度推广。1976年定点示范208万亩，在全国范围开始应用于生产。1976年是毛主席他老人家离我们而去的那一年，所以，让中国人吃上高产稻与他无关了。跟着毛主席挨饿也就成了毛主席永远也摘不掉的帽子了。我不知道，说这话的人良知哪里去了——吃着人家的还骂人家，这样的人还算人吗？

毛主席是我们共和国的缔造者，连他都敢冤枉，那些人还有什么事不敢做？

再举个例子：2007年英国金融时报报道有科学家把1978年以前中国经济的发展速度统计了一下，发现66年至76年的文革，工业生产仍继续在以平均每年超过10%的速度增长（1966年国民生产总值年均递增10.7%，只有67、68年稍有减少，分别递增9.8%和9.9%，到了69年年均递增16.9%，70年比增19.4%）。金融时报还评价上个世纪全球最大规模，最成功的工业化是在中国，而同期世界的增长速度是3％。中国人的统计造假，西方人的统计总不能不信吧？既无内债，又无外债，还没有通货膨胀，这样的发展水平，居然是不懂经济的人干的！

还有一点大家需要知道：70年代中国是世界第三科技强国。这句话没有丝毫的夸张。今天的歼10、神舟、094全是1980年以前的东西，不相信的可以去查阅相关资料。有谁敢想象，在1976年以前，中国技术人员的比例和绝对数量都是世界第一的？其实，这个道理是明摆着的，那些年创造了多少“第一，那不全是人干出来的吗？没有足够数量的技术人员，怎么可能出那么多的成绩？今天的中国是什么？世界工厂，专门干组装的。没有技术含量的活全让我们干了。为什么？因为我们没有技术。我们发展的真好！幸运的是，胡总温总看透了问题，现在不是提出转型不做世界工厂了吗？按照西方经济精英的分工理论，这可是绝对错误的！

到底谁懂经济？又是谁不懂经济？

我以前写过几篇批判西方经济学的文章，同样被西方经济精英斥为“不懂经济”。其实，到底谁不懂经济？我把底捅出来可能会让所有人晕倒：那些经济精英，没有一个知道“经济”是何物的。

至今为止，在西方经济学中，经济一词还没有一个明确的定义。所以，他们对经济学的定义也处于混乱状态。下面19个句子都可以看作是经济的“定义”：

1．经济是指财富； 

2．经济是人类和社会选择使用自然界和前辈所提供的稀缺资源； 

3．经济是指利用稀缺的资源以生产有价值的商品并将它们分配给不同的个人； 

4．经济是指人类生活事务； 

5．经济是指把稀缺资源配置到各种不同的和相互竞争的需要上，并使它们得到最大满足； 

6．经济是指将稀缺的资源有效的配置给相互竞争的用途； 

7．经济是指个人、企业、政府以及其他组织在社会内进行选择，以及这些选择决定社会性稀缺性资源的使用； 

8．经济指社会管理自己的稀缺资源； 

9．经济是指我们社会中的个人、厂商、政府和其他组织进行选择，这些选择决定社会资源被利用； 

10．经济是指在经济活动中确定劳动、资本和土地的价格，以及运用这些价格配置资源； 

11．经济是指金融市场行为，金融市场将资本配置到其他经济部门； 

12．经济是指收入分配，以及不损害经济运行的前提下对人给予帮助； 

13．经济是指政府支出、税收、预算、赤字对经济增长的影响； 

14．经济是指经济周期中失业与生产的波动，并改善经济增长的政策； 

15．经济是指各国贸易模式贸易壁垒的影响；

16．经济是指发展中国家的发展，资源有效利用的方式； 

17．经济是指一定社会生产、交换分配和消费等经济活动，经济关系和经济规律； 

18．经济是指有限资源在不同用途上的运用； 

19．经济是指资源配置的全过程及决定影响资源配置的全部因素。

我想，看到这里大家可能都晕了。那些所谓的精英，懂“经济”的天才们，居然自己都说不清什么是经济！这可真是天大的笑话。这可是一门研究了200多年的高尚科学！真不知道他们在研究的什么！

其实，这也不是笑话，西方经济学就是这样的，在关键的必须搞清楚的地方，混沌的很，在大家都明白的地方，他们的分析却能让人大开眼界，大呼“非已之所及也”。这样的理论有什么用？

不要说我给他们扣帽子，在经济理论中最关键的几个问题：为什么会暴发经济危机、出现通货膨胀的原因、经济发展理论、汇率如何决定、金融危机为什么会暴发，这些关键性的问题上，没有一个能得出明确答案来的，都有上百种理论在那里摆着。对于那些无关紧要的东西，倒是搞出大堆的理论！这又有什么用呢？科学是解决现实问题的，可这门所谓的科学，一个关键问题解决不了。反而弄出上百种假说，搞得人头晕脑胀。学它有什么用？当然，有人总结过两个定律：经济学家第一定律：对任何一位经济学家而言，一定存在着一位实力旗鼓相当的同时观点又针锋相对的经济学家。经济学家第二定律：他们都是错的。 如果你真正学过西方经济学，你会发现，这两个定律是千真万确的。

还有一个讽刺西方经济学家的笑话是这样说的：一个人问：“经济学家干了什么？”回答是：“短期看他们干了很多，长期干他们什么也没干。” 这个笑话形容的恰如其分。

其实，“经济”是个很简单的东西，说穿了就是 *经世济民* ，就是 *民生* 。解决人民生活需求的。为什么西方经济学不给它下一个明确的定义呢？西方经济学的全名叫 *西方资产阶级经济学* ，它是为资产阶级服务的，不是为普罗大众服务的，如果把这个底兜出来了，不就穿帮了吗？

过多的我就不多写了，在文章的最后，我只想问那些西方经济精英们一句：“既然别人都不懂经济，那你们懂不懂？如果懂，请你们告诉我什么是经济好不好？骗子吗？”



附：自即日起，我再发文章将不再发往各大论坛。

*** 还毛主席一个公道 《1949年，“时间开始了”》

金鸿：这是两篇让人流泪的文章。看完了如果哪位朋友回贴，请给自己取个名字，不要匿名。时间终于又开始了。我也到了退出各大论坛的时候了。从今往后，发文只发个人网上阵地（包括博客）。

    
《1949年，“时间开始了”》

1840年开始，那个马可波罗笔下辉煌的帝国，膝盖残废了，常常跪在西方强权面前哆嗦。1949年10月1日，一个伟大的身躯站在天安门城楼，庄严的向世界宣告，这个跪了109年的帝国，从此重新站立起来了，并将有尊严的永远站立下去。

“时间开始了”！才子胡风不知如何能写出如此不朽的诗句，羡煞共和国的不知多少同样豪情满怀的知识分子。那天登上了天安门观礼台的李慎之先生，50年之后，还因为这神来之笔是由胡风，而不是自己写出，沧桑之心，再添几分愁绪。
那天，半个中国还在蒋介石的盘踞之下。毛泽东和他的战友们，穷寇续追，在中南，西南，两地，续用了两个月的时间，把蒋介石最后两支精锐主力，白崇禧部和胡宗南部基本肃清，彻底击碎蒋介石试图依靠四川与共产党继续对峙的美梦。随后西藏也获得和平解放。
时间在毛泽东洪亮的湖南口音中、在5万万人民的欢呼声中、在人民解放军消灭蒋介石残匪的炮火声中，开始了。那些不相信时间从此开始的懦夫们、短视者、嫉妒狂、旧王朝的卫道士们试图挑战时间。他们在上海搞金融破坏，狙击人民币，企图用经济金融的办法阻挡共产党接管政权，以为共产党真的是他们嘲笑的“军事上 100分，政治上80分，经济上0分”。然而他们一切试图阻挡时间前进的努力，在几个月的时间里，就土崩瓦解了。瓦解他们的方法是他们奉为至宝的纯经济的。因此，即便当时为上海工商界要人，后来官拜邓小平的国家副主席的荣毅仁大老板，事后也不得不臣服于新开始的“时间”，跟上时代的脚步。
在内部的敌人和看客们怀疑“时间开始了”的时候，那些习惯了中国人跪着听其呵斥的鸦片贩子、战争狂徒、浑水摸鱼者，更在新中国的大门口，以联合国和保卫自由的名义，发起了一场威胁我主权与安全的朝鲜战争。相应的“抗美援朝”，可以说是毛泽东一个人的战争，但其所带来的好处却是万代千秋的。那些假人道主义者、伪善家，以为不出兵、保全了几十万战士的生命，就是人道、就是上善、中国必然也得安全，而毛泽东牺牲了几十万生命，是首恶、是个人野心。这些成天哼哼唧唧的苍蝇们，只知道自己的营营，是“时间”最美丽的赞美诗，全然不知道人类的生存的法则。抗美援朝的“二次战役”之后，时为中央办公厅主任，后来做了邓小平的国家主席的杨尚昆在日记中写道：“主席决定志愿军入朝之举，实是万分英明、有远见的决定，事至今日则已如黑白之分明。如果当时要让我来决定，我则会偏于‘苟安’！诚如主席所说，不仅要近视、短视，而且必须远视、长视。决不可以眼前的，忽视了前途、远景！‘高瞻远瞩’盖即指此也。”（中央文献出版社《毛泽东传》）。两朝元老、时代的亲历者、参与者、缔造者之一，尚且有如此言论，营营者们，复有何言？
那些在蒋介石的中国享尽了荣华富贵的体面人物们，以为复辟的机会来临，以为失去的江山可在麦克阿瑟的烟斗喷出的烟云中还回来，不失时机地展开了对共产党人的暗杀和对新中国的破坏。毛泽东在人民的要求下（“天不怕，地不怕，就怕共产党讲宽大”），向这些暗藏的气焰嚣张的敌人发起了镇反运动。那些营营者，对数万共产党人鲜活的生命，没有丝毫的同情，却对被镇压的杀人者的死耿耿于怀，暴露出他们彻头彻尾的假仁假义和对民族崛起的仇恨。他们把仇恨泼向死后的毛泽东。那个写了毛泽东xx故事的张某人，不就是一个军阀的后代么！以她为代表的一群恨毛泽东是理所当然的，那些享受着毛泽东的福荫的人们，怎么也营营着呢？ 
延安窑洞里曾传出毛泽东和黄炎培先生关于“周期率（律）”的对话。伟人曾以坚定无可置疑的口气告诉这位民主人士，共产党找到了走出周期率的道路，那就是人民民主（专政）。于是，当党内一些意志薄弱者，不顾毛泽东西柏坡时的警告，学起刘宗勉，搞起腐败的时候，毛泽东果断了打响了挑战周期律的第一枪。虽然劳苦功高的刘青山、张子善，人头落了地，但共产党的队伍，从此保持了相当长时间的纯洁，共和国的五星红旗飘扬的更高。以纯洁党内为目标的党内“三反”（反贪污，反浪费，反官僚主义）尚未结束，毛泽东就在党外发起了一个旨在纯洁社会经济生活的“五反”（反对行贿、反对偷税漏税、反对盗窃国家财产、反对偷工减料、反对盗窃国家经济情报）。毛泽东，以睿智的眼光，看待自己的党和她领导下的中国，总是那么准确的抓住要害，及时出击。“三反五反”，居然也被后来许多的人们指责，但那终归也不过是苍蝇们的营营而已。
“反右”是苍蝇们营营了半个世纪的共和国的一件大事。感谢苍蝇们的营营，今天的人们，在这营营中，越来越多越来越深刻的理解了那场运动。那些被毛泽东信任和重用过的党内党外的人士们，下到普通者，上到一人之下万人之上的国家领导人，曾辜负了毛泽东和他领导的共和国的希望。他们制造了事端，哭喊着要复辟失去的天堂，当毛泽东迫于党内压力，给他们包藏着可怜的虚伪和自尊的精神果壳，轻轻一击的时候，他们就土崩瓦解，作鸟兽散，躲到暗角里哭嚎，一直哭到今天，老子死了儿子接着哭。更有甚者，居然不承认自己曾经要求共产党下台，要求各党轮流执政，不承认自己曾鼓动学生上街，要求共产党从工厂、学校、医院滚走。这些人就像强奸了少女的小流氓，提起裤子就不认账，还把自己打扮成英雄救美的正人君子和自由英雄。而那些该为扩大化负实际责任的领导者们，先在不负责任的加害中（必须承认这样的加害也是存在的）巩固了自己的权力，又在后来更加不负责任的“历史评价”中，把一切责任推给了毛泽东，骗取了善良的人们的信任，攫取了更高的权力。如果说，明知道那些被他们迫害的人士，的确并非冰清玉洁，却别有用心将他们奉为神圣，是为了政治的需要，尚可理解，那么，推卸自己的责任，把 “屎盆子”全部扣到毛泽东的脸上，则是彻头彻尾的自私自利，该千刀万剐。好在历史无穷的嘲笑了这些没有一点智慧的纯粹的投机政客。
对“大跃进”的恶毒攻击，是营营者们又一个偏爱。历史的看，“大跃进”是前7-8年社会高速发展的惯性之使然，绝不是毛泽东一个人的头脑发热。它的客观物质基础是，1949年立国、三年抗美援朝取得胜利、“三大改造”意外以极短的时间和极优秀的效果完成、战后国家经济迅速全面恢复，并高速增长以及生产力在短时间里的全面提升，对生产关系提出了一个现实的要求，即改变农业的个体分散经营的状况，改变工业生产结构和形式，向更高级的生产关系转变。其主观的基础是，共产党7-8年的所为，所取得的历史性的进步，鼓舞了全国人民和全党的信心，党内虽然有陈云这样的冷静者，但大气候已经决定了这样的一次“大跃进”的尝试不可避免。真实的“大跃进”其实是一个在农业领域粮食高指标和工业领域钢产量高指标（制定中就被毛泽东怀疑和压缩过）为基本标志的局部经济领域的大跃进，并非一次社会所有层面的大跃进，且利弊兼有、其不良后果很快就被发现并纠正。但是在后来别有用心的历史解说中，“大跃进”成了毛泽东个人头脑发热导致的一场全国性、全民性的大灾难，并直接与后来的三年自然灾害相连接，把共产党人主观上所作的自我批评“三分天灾，七分人祸”，当作了客观事实，并一直这样误导无知却处于好奇渴望了解那段历史的人们。如果我们在“大跃进”中，违反的只是经济规律，那么我们别有用心歪曲那段历史，则是违背了人类的理性、人类的基本良知。
提到“文革”，一些人就像是祖坟山被毛泽东挖了一般，怒不可遏，对毛泽东极尽诅咒之能事。他们把苍蝇的营营、泼妇的骂街、卑贱者的无耻诅咒和愚蠢者的自以为是，结合起来并发挥到极致。但是，历史并没有停止在这些人的狂吠之中。1966年毛泽东给江青写过一封信，是谈文革和林彪的，交由周恩来，先转林彪本人阅读(此一点说法不一)，再给江青。这封信，是毛泽东的“咒语”，也是先知带给人间的福音。今天我们重读那信的时候发现，1966年的毛泽东已经预言了今年中国发生的一切，并预告了未来中国将要发生的一切。那些还没有读过那信的人们，去读吧，也许就像读鲁迅的《阿Q正传》一样，需要读30遍，才解其中味。那个离经叛道的卜伽丘，打响了欧洲文艺复兴的第一枪，随后200年，这枪声响遍了整个欧洲，始有现代欧洲脱胎而出；在同一时期中国也有个离经叛道者，他头顶道冠，身披袈裟，足蹬儒靴，向与西方基督教一样吃人的礼教--新儒学（宋明理学）发起攻击，但却被朝廷判了死罪。他就是明代开明思想家李贽。李贽死了，中国的“文艺复兴”夭折了。然而，毛泽东只争朝夕，用10年时间，基本完成了欧洲200年文艺复兴才完成的全部事业。我们有何颜面去批评“文革”，批评毛泽东？我们真的懂了文革么？（如果这坛子给面子，读者将有机会看到我关于文革的系统的哲学反思，注意，是哲学反思）
说毛泽东闭关锁国，简直是个弥天大谎。如果说，当时烟雾遮住了人们眼睛，一时还看不到这个纵深的话，那么，今天因为时间洗刷了历史，擦亮了人们的眼睛，大家已经认清了事实。毛泽东从湖南一师开始，就是放眼世界的，他怎么可能自锁国门？延安时期，他突破重重艰难，与大洋彼岸的记者们结成好友，现实的目的是让他们在西方世界宣传共产党，长远的目标则是要与遥远世界建立互信，建立彼此的了解。《别了，司徒登雷》有多少遗憾留给历史？那时毛泽东希望美国有他同样的眼光，看到未来世界里另一支主宰力量，并与之结合，而不是对立，但是这个彼此的了解，非要经过一场死伤百万的大厮杀和几十年的封锁与反封锁，才姗姗来迟。换句话说，那扇沉重的国门，是由外面的敌人关上的。鉴于实际的需要和历史的必然，毛泽东不得不“打扫干净房子再请客”，在打扫房子（恢复和发展经济、加强和巩固国防建设、改造国家工业体系、建立新型的文化道德等等）的同时，一刻也不曾忘记请客，并将生命的最后几年，大部分时间用在请客上，并最终把美国集团怦然关上的中国国门从里向外推开了。我们可以设想，如果没有1972年前后的中美中日中法中澳等关系的实质性变化和更广泛的外交成就的取得，那么， 1979年中国的邓小平副总理决不可能找到去美国的路！为了给后来者铺平通往国际社会的道路。时间在1949年开始，但没有在1976年终结。1949年 -1976年是毛泽东亲自主宰的历史，1976年到今天则是毛泽东让别人从反面解释前28年历史的历史。从1949年，到今天，历史的实际主导者，无疑都是毛泽东。生前的毛泽东让灵魂坐在云端俯视人间，看妖魔鬼怪尽现本色，并不时发出预警，但俗众们无法理解毛泽东的灵魂。于是，那个“荒唐年代”“荒唐”的一切，从哲学家的伟大的头脑中走出，变成社会改造的具体行动时，几乎没有一个人理解哲学家的睿智。毛泽东满足卑贱者的表现欲和善良者的美好愿望，留下了反面教材。这样，就有了1976年后毛泽东靠灵魂而非靠肉体主宰的历史。实际上，从他1949年主导中国的那一刻开始，就有着两条路线进行着实质性的斗争。虽然毛泽东不得不直接告诉他的同志、他的人民，敌人就在党内，就是党内走资本主义道路的当权派，但善良的人们觉得毛泽东是在疑神疑鬼，是在捕风捉影。 
马克思认为，以往哲学都只在解释世界，而问题在于改造世界。毛泽东东先是合理解释了世界，然后按照解释得到的逻辑和结论，又改造了世界，最后提出了对未来世界的预告和警示。我们中的一些，目光短浅，把毛泽东上帝般的拯救和改造，视为独裁专制，把他改造了的世界叫做地狱、解释清楚了的世界叫做乌托邦。于是，一度被毛泽东收归到潘多拉盒子里的小鬼大鬼、魑魅魍魉、牛鬼蛇神就又被放到了人间，兴风作浪，比以往更惨烈的祸害世界。今天的学者专家，告诉我们，这就是市场经济，市场经济代表了人类的最后归宿，是此岸也是彼岸，是人性最美好的展示，是人性本真的要求，是人性本身。
马克思的警告式预言避免了现代资本主义的破产。但这并不是说马克思主义不是科学，唯能说明的是现代资本主义国家的优秀政治家和负责任的学者们，及时接受了马克思的警告，并在马克思的警告之下，改造了自己的社会，修正了自己的目标，并克制了一些贪婪，把普通民众的生存也当作社会和谐最根本的一环，才避免了社会发展的断裂。列宁在一个农奴制的苏俄建立了社会主义，后来经过斯大林的努力，发展起一个超级工业和军事大国。这是对马克思主义的发展。毛泽东在自己的国家，在推翻了半殖民半封建的统治后，在经过了“三大改造”后，开始过渡到社会主义。这也是发展，因为，无论是列宁还是毛泽东，他们的目标和道路的指向和马克思主义是一致的，只是在过程和程序上，因地制宜，进行了改造和压缩，该超越的过程刻不容缓去勇敢超越。这是实事求是的真正的马克思主义。毛泽东所试图超越的，就是那个赤裸裸的人吃人的残酷的血腥的原始资本主义，通过社会主义的道路，去迎头赶上现代资本主义，并最终超越现代资本主义。这里必须要对马克思之前的原始的资本主义和马克思之后，接受了马克思的警告进行改造和发展后的现代资本主义加以区分。可以说，毛泽东抓住了问题的实质，并取得了实际的举世瞩目的伟大成就。
然而，毛泽东的路没有被继承，那个被毛泽东刻意回避了的原始资本主义被自称是马克思主义者的人们，照搬到了毛泽东后的社会主义中国。一次空前的伟大的社会改造的成果，付诸水流。毛泽东不是失败于任何敌人，仅失败于生命的短暂。那些从不相信毛泽东的人，总以为自己正确，在毛泽东亲自主政的时候，他们没有机会展示自己的正确。1976年后，这个机会到来了。他们首先倡导的就是“补课”、“交学费”，人们其实和倡导者一样都知道这补课的含义，但人们真诚的虔敬的接受了倡导，把一个10亿人的国家交给某些人当作过河的石头。这样在“不争议”的一公斤的智慧下，就有了现在不得不争议的社会现实。18世纪伦敦上空飘荡的污染空气200年后飘到了北京上空。这是中国应该遭受的惩罚，还是我们不该交的学费？我深以为怀疑！巴尔扎克，雨果，狄根斯笔下的200年前的一个方面的欧洲，飞落在今天的中国大地，这是猥琐与倒退，还是崇高与进步？历史不会停留在今天，北京上空的黑雾终会消失，飞来的200年前的一个方面的欧洲也会再飞走，但它将会是以无数生灵遭本可避免的摧残甚至死灭为代价的。如果毛泽东的路不中断被继续到今天呢？1970年代我们几乎能造出绝大部分世界最先进的东西，今天我们买来了世界上一切最先进的东西。制造和卖，真的没有区别吗？
马克思在他的《德意志意识形态》里说：工人创造的财富越多，他的生产的能量和范围越是增加，他就变得越穷。工人创造的商品越多，他自己也就变成一种更加廉价的商品。伴随着物质世界的增值的是与之成正比的人的世界的贬值。劳动不仅生产商品，他还把自己和工人作为商品来生产-与它生产商品成比例。马克思继续说：不错，劳动给富人生产出美丽的东西—但对工人来说，他生产出贫困。它给富人造出宫殿，却给自己造出茅屋陋舍。它给富人生产出美，却给工人自己产生出残废和畸形。机器在取代劳动，但机器迫使一些工人回到一种原始而残酷的劳动中，同时又把另一些工人变成了机器。劳动生产智慧，却在工人身上产生出愚昧和痴呆。
这是原始资本主义的真实写照。现在，善良的人们，当你读了这段文字，你还会否定，马克思是最伟大的人道主义者吗？你还会怀疑毛泽东是最伟大的马克思主义者吗？你还怀疑毛泽东在文革中的梦话一样的警告还是捕风捉影吗？毫无疑问，毛泽东不但是马克思主义的理论家，难能可贵的，更是一个真正意义上的马克思主义的实践家。共产党内，除了毛泽东谁还有资格号称自己是马克思主义理论家，实践家，谁还敢不知羞耻说自己发展了马克思主义？当然，如果歪曲也是一种发展的话，那么有人发展了很多。
80年代的某个日子，在天安门广场耸立了20多年的马恩列斯的画像被请走了，取而代之的是孙中山的画像。毛泽东的画像虽然还挂在天安门城楼，但在毛泽东曾经的敌人那里，它成为没有任何意义的纯粹的装饰物，不再具有生命、意志、自由、民主的含义，不再具有国家合法性、共产党合法的含义。他们或许在为那尊画像烦恼、尴尬。
对于中断历史的痛惜，让人们变得智慧了。苦难的中国，对于她的英雄的时代超越性和历史使命感的完全理解，命定要在一个中断历史的无穷大代价的基础上完成。谁让我们是一个只有孔家的虚伪礼仪没有真正哲学的民族！既然我们没有哲学家洞察历史和未来的智慧，那就让现实的惨烈来当我们的老师吧。但是，我们没有理由气馁，因为我们已经有了毛泽东，有过毛泽东的时代，尤其有过毛泽东的文革后，学会了一点哲学的思考，开始懂得一点历史的纵深。
其实，毛泽东去世后，远不到28年，人们就终于理解了毛泽东先知先觉的警告，终于认情了敌人。他们是腐败分子、腐败分子的保护人、腐败的赞美人与辩护人、腐败制度的催生者、他们也是一些不负责任的文化人、文艺工作者、经济学家、学者、教授，等等，等等。那是一个长长的名单。生前的毛泽东苦口婆心却没有多少人理解他的良苦用心，今天，毛泽东不再说一句话，他曾经热爱，现在依然热爱，并将永远热爱的人们，就在许多事情上，完全的理解了他。当某些自以为正确的人，以为自己开创了一个新时代的时候，却浑然不知这个所谓新时代是毛泽东用来教育他的人民的。历史必然要回归毛泽东的人间正道。不管这个回归要多长时间，要付出多大代价，它必然发生。社会主义的事业，不是一个终结的过去存在，从更广大的历史视角中看，它恰是一个越来越近的未来存在。这便是历史的逻辑，我们无力抗拒。“人民，只有人民，才是创造世界历史的动力”。辩证法大师毛泽东，发挥了马克思的阶级斗争学说，从这个斗争中的一面，阐述清楚了这个斗争的全部。这就是对马克思的超越。
毛泽东以前的历史书，由帝王将相、才子佳人的名字组成，即便出现了小老百姓，那也是盗匪、刁民、流氓、恶棍、刺客，他们中没有一个是有帝王将相、王公贵族、才子佳人那般高尚和高贵的。但1949-1976的历史里，出现那么多小老百姓的名字。他们是张思德、雷锋、王杰、戴碧蓉、董存瑞、黄继光、王国藩、王进喜、陈永贵、郭凤莲、邱少云、蔡永祥，等等，等等。他们来自江河，来自草原，来自战场，来自农村，来自工厂，来自火热的社会主义建设的各条战线，他们是道德星空里闪烁的星，令我们敬畏，但他们却就在我们身边，在我们之间行走，他们是我们的学生、老师、同事、战友、兄妹、父母，他们真实、亲切、高尚、脱离了低级趣味。他们是时代的代表，也是我们自己的化身。我们多少人实际上和他们达到了一样的境界，一样的道德。只是真实历史不必要记下我们每一个名字，就让他们作为代表载入史册，就已经足够证明“高贵者最愚蠢，卑微者最高贵”，证明“人民，只有人民，才是创造世界历史的动力”。
社会主义与其说是作为一种政治制度被引入，不如说是作为一种人类崇高的新型道德价值体系被接纳和被实践。在毛泽东的中国，这个道德价值体系不是照搬马克思主义教科书上的，是结合中国的历史和现状，对比了中国和世界文化的优劣之后，旨在为一个庞大民族找到其在世界舞台上应有的位置，而做出调整后的道德价值体系。孙中山慨叹中国是一盘散沙，但他基于少数人，排斥工农大众的精英革命，最终遭到失败，没有完成对这盘散沙的最终改造。传统文化“仁义礼智信”倡导的是自下而上的“忠诚”，它的发动者名为孔孟实是皇上，它的落脚点和最终的收益者，也是皇上。正如同黑格尔所言，古代中国只有一个人是自由的，这个人就是皇上。“仁义礼智信”的全部目的，就是要保持皇上的自由。“温良恭俭让”所强调的是封建时代被统治者的个人的修养，也非国家民族精神。因之，社会因为纵向的盲目忠诚和横向的谦让，虽然具有一定稳定性和亲和性，但从来没有成为一个现代意义上的政治实体，尤其是没有成为一个团结的、统一的、具有内在凝聚力的政治实体。它表面上，具有一个所谓文明古国的一切外在特征，它的民众恭恭敬敬、和和气气，社会仿佛吉祥如意、生产蒸蒸日上、商业发达、文化繁荣，但是，它实质上是一盘散沙。这被1840年以来英国人的枪炮和以后一再屈辱的历史所一再验证。1840年发生的一切，只不过是戳破那层纸，让皇帝的新衣，为普通民众所知道而已。当毛??有很快得到改??、手工业改造、人民公社化、还有伟大的抗美援朝战争之后，这个社会主义道德体系才最终构建起来，并为大多数一般民众接受和遵循，一盘散沙才渐渐成为过去的历史。在1949年开始的时间里，过去历史上皇上一个人的自由，终被全民自由所代替。它的标志是，对外拥有实质意义上的完全独立和自由的主权，在内部则建立起主人翁的个体民众的社会自觉，一般民众有了国家为我，我为国家这种现代国家的公民意识。具体的表现形式则是，男女平等，官民平等，财富在全社会进行基本平等的生产和分配，话语权基本掌握在社会普通民众之手，那些捏着笔杆子的，或主动或被迫成为普通大众的代言人，城乡差别，工农差别，脑力劳动和体力劳动的差别，即所谓三大差别在大范围高程度缩小。更重要的是个体成员和国家结成了互信：一荣俱荣，一损俱损，爱国家即爱自己，珍爱自己的荣誉、节操、坚信爱劳动爱人民是崇高的修养，即是爱国家，会得到国家的表扬鼓舞。对“好人好事”即时表扬，并授予各种相应的荣誉称号，如光荣军属、先进生产者、先进个人集体、三好学生、五好家庭、学雷锋标兵等等，都是这个互信结成的标志。随着这个互相的结成，一盘散沙最终铸造成为国家意志体：一个由自由意志统一起来的现代意义上的国家，一个世界政治事务中最大的政治实体，最终登上了历史舞台。那时，我们自己形容为扬眉吐气。
历史上的英雄有天生的，有时势造出来的，有自我成长而来的。秦皇汉武是天生，唐宗宋祖是时势造成，毛泽东则是自我成长的。革命有两种，为了自己的革命和为了自由的革命。陈胜吴广，完不成军令，就揭竿而起，是为了自己的革命。他们看到和觊觎的是秦二世屁股底下的龙椅和身上的黄袍。他们在鱼肚里放进去的是卑微的道德和我们民族的奴性。斯巴达克斯则不同，角斗场上的胜利可以让他在罗马君主与贵族的歇斯底里的变态的快乐中获得自由，但他拒绝了这施舍，因为还有无数人要为那些王公贵族的变态的快乐失去生命，他要为这些人的自由，高昂起头颅，握紧手中的剑。斯巴达克斯死了，被君主绞死了，但他让最高贵者懂得了什么是真正的高贵：自由和为自由献身的意志。罗马帝国动摇了，但西方的自由却在罗马帝国最后的轰然倒塌中在现实社会萌芽了，不再只是希腊哲学家的理想。这是斯巴达克斯的贡献。毛泽东和斯巴达克斯一样，所从事的是为了自由的革命。他本可以继承一份不错的家业，做个小地主，三妻四妾，享受今天的精英们高扬的所谓“人性”；也可以当个小乡绅，长袍马褂，走东串西，为邻里乡亲的芝麻小事，操操心，迎来几分尊敬和心安理得；或者当个教书匠，摇头晃脑，之乎者也，传播所谓的仁义道德。但他没有，他选择了为自由的革命，选择了斯巴达克斯的路。普罗米修斯以自己的死，为人类向神要来自由，毛泽东则是代表被压迫的人向压迫者要来自由。
1949年前的毛泽东，容易被认作一代草莽枭雄，因为1949年以前的全部革命都可能被误解为是陈胜吴广为了秦二世的龙椅和黄袍的革命。而1949- 1976的历史，最终证明了毛泽东不是草莽枭雄、不是为了自己、不是时势造出来的。1949年以前的毛泽东只是伟人祠里一个普通的伟人，伟人星空里一颗普通的星，而1949年后，我们不得不为毛泽东单建一座伟人祠，历史伟人的星空里，毛泽东成为了最耀眼的一颗，那些渺小的嫉妒者，试图遮挡住他的光辉，但总是被他发出的光照见得更加渺小。
基督被犹大出卖，不得不死。他选择了死，并扛着那个钉死自己的十字架去刑场。毛泽东不得不也扛这样的一副十字架去死。这个十字架就是“文革”。与基督不同的是，毛泽东自己精心的、自觉自愿的打造了这个十字架，并把自己钉了上去。基督的神性就这样被毛泽东超越了。毛泽东“钉死”了自己，而人民获得了自由。被他拯救的人们，虔诚的将他解救下十字架，就这样他复活了，并将不再死去，并将庇佑每一个弱小者的心灵和魂魄。当他们孤独的时候，想到这个名字，就不再孤独；当他们害怕的时候，想到这个名字，就会有力量；当他们失去生的勇气的时候，想到这个名字，就会看到曙光和希望，就会懂得珍爱生命。
联合国曾下半旗为一个白人种族曾视为狗的民族的领袖致哀。请问，毛泽东之前的中国人有谁可以获得这个荣耀？毛泽东之后的中国人有几个还可以获得这种荣耀？ 1976年，毛泽东逝世的消息，传到加拿大，那个视毛泽东为政治宿敌的张国焘无限感慨的说：我们的时代过去了。这个“我们”，是大写的我们，它代表的是理想、正义、自由、奋斗、历史使命和民族的责任。但是，“我们”的时代决没有过去。
1949-1976的历史现在越来越清晰了：那是一个建设的、而非破坏的年代；一个理想的、而非庸俗的年代；一个高扬道德的、而非宣扬物欲的年代；一个人民民主自由、扬眉吐气的、而非少数人独裁专制的、人民为奴隶的时代；一个自力更生、敢想敢干的、而非洋奴哲学的、需要阿Q的年代；一个进取的创造了无数奇迹的、而非平庸的无所作为的年代。一句话，一个柏拉图理想中的哲学王的国家成为了现实的年代。今天，经济崩溃被大家认识到是个弥天大谎、闭关锁国是无耻的栽赃、迫害知识分子是知识分子小流氓式的自我辩解、文革为浩劫则是哲学无能者的信口雌黄。我们要感谢那个时代的主人们，但我们也不能忘掉为那个时代付出了青春爱情幸福乃至生命的普通大众，他们中确有一些无谓的生命牺牲。但这就是历史，我们要学会悼念亡者和和自我忏悔，但不能忘却。
高贵者最愚蠢，卑贱者最聪明。1949年开始的时间如是说。  

 

附：毛泽东给江青的一封信（1966年） 

　　六月二十九日的信收到。你还是照魏、陈二同志②的意见在那里住一会儿为好。我本月有两次外宾接见，见后行止再告诉你。自从六月十五日离开武林以后，在西方的一个山洞③里住了十几天，消息不大灵通。二十八日来到白云黄鹤的地方，已有十天了。每天看材料，都是很有兴味的。天下大乱，达到天下大治。过七、八年又来一次。牛鬼蛇神自己跳出来。他们为自己的阶级本性所决定，非跳出来不可。 

　　我的朋友④的讲话，中央催着要发，我准备同意发下去，他是专讲政变问题的。这个问题，象他这样讲法过去还没有过。他的一些提法，我总觉得不安。我历来不相信，我那几本小书，有那样大的神通。现在经他一吹，全党全国都吹起来了，真是王婆卖瓜，自卖自夸，我是被他们逼上梁山的，看来不同意他们不行了。在重大问题上，违心地同意别人，在我一生还是第一次。叫做不以人的意志为转移吧。 

　　晋朝人阮籍反对刘邦，他从洛阳走到成皋，叹到：世无英雄，遂使竖子成名。鲁迅也曾对于他的杂文说过同样的话，我跟鲁迅的心是相通的。我喜欢他那样坦率。他说，解剖自己，往往严于解剖别人。在跌了几跤之后，我亦往往如此。可是同志们往往不信，我是自信而又有些不自信。 

　　我少年时曾经说过：自信人生二百年，会当水击三千里。可见神气十足了。但又不很自信，总觉得山中无老虎，猴子称大王，我就变成这样的大王了。但也不是折中主义，在我身上有些虎气，是为主，也有些猴气，是为次。 

　　我曾举了后汉人李固写给黄琼信中的几句话：嶢嶢者易折，皎皎者易污。阳春白雪，和者盖寡。盛名之下，其实难负。这后两句，正是指我。我曾在政治局常委会上读过这几句。人贵有自知之明。 

　　今年四月杭州会议，我表示了对于朋友那样提法的不同意见。可是有什么用呢？他到北京五月会议上还是那样讲，报刊上更加讲的很凶，简直吹的神乎其神。这样，我就只好上梁山了。我猜他们的本意，为了打鬼，借助钟馗。我就在二十世纪六十年代当了共产党的钟馗了。 

　　事物总是要走向反面的，吹得越高，跌得越重，我是准备跌得粉碎的。那也没什么要紧，物质不灭，不过粉碎罢了。全世界一百多个党，大多数的党不信马、列主义了，马克思、列宁也被人们打的粉碎了，何况我们呢？我劝你也要注意这个问题，不要被胜利冲昏了头脑，经常想一想自己的弱点、缺点和错误。这个问题我同你讲过不知多少次，你还记得吧，四月在上海还讲过。以上写的，颇有点近乎黑话，有些反党分子，不正是这样说的吗？但他们是要整个打倒我们的党和我本人，我则只说对于我所起的作用，觉得一些提法不妥当，这是我跟黑帮们的区别。此事现在不能公开，整个左派和广大群众都是这样说的，公开就泼了他们的冷水，帮助了右派，而现在的任务是要在全党全国基本上（不可能全部）打倒右派，而且在七、八年以后还要有一次横扫牛鬼蛇神的运动，今后还要多次扫除，所以我的这些近乎黑话的话，现在不能公开，什么时候公开也说不定，因为左派和广大群众是不欢迎我这样说的。也许在我死后的一个什么时机，右派当权之时，由他们来公开吧。他们会利用我的这种讲法去企图永远高举黑旗的，但是这样一做，他们就倒霉了。中国自从一九一一年皇帝被打倒以后，反动派当权总是不能长久的。最长的不过二十年（蒋介石），人民一造反，他也倒了。蒋介石利用了孙中山对他的信任，又开了一个黄埔学校，收罗了一大批反动派，由此起家。他一反共，几乎整个地主资产阶级都拥护他，那时共产党又没有经验，所以他高兴地暂时地得势了。但这二十年中，他从来没有统一过，国共两党的战争，国民党和各派军阀之间的战争，中日战争，最后是四年大内战，他就滚到一群海岛上去了。中国如发生反共的右派政变，我断定他们也是不得安宁的，很可能是短命的，因为代表百分之九十以上人民利益的一切革命者是不会容忍的。那时右派可能利用我的话得势于一时，左派则一定会利用我的另一些话组织起来，将右派打倒。这次文化大革命，就是一次认真的演习。有些地区（例如北京市），根深蒂固，一朝覆灭。有些机关（例如北大、清华），盘根错节，倾刻瓦解。凡是右派越嚣张的地方，他们失败就越惨，左派就越起劲。这是一次全国性的演习，左派、右派和动摇不定的中间派，都会得到各自的教训。结论：前途是光明的，道路是曲折的，还是这两句老话。 

久不通讯，一写就很长，下次再谈吧。 

毛泽东 

一九六六年七月八日 
注： 
①毛泽东在武汉致江青的信，写成后在武汉给周恩来、王任重看过。原件为毛泽东销毁，以上为毛泽东校阅过的抄件。 
②魏：魏文伯，前中共上海市委书记、华东局书记。陈：陈丕显，前中共上海市委第一书记、华东局书记、兼上海警备区第一政委。 
③指韶山滴水洞。 
④朋友指林彪。讲话，指林彪于一九六六年五月十八日在中共中央政治局扩大会议上的讲话，其中提出“防止反革命政变”。 
*** 史评:谁是中国的千古一帝?

写在前面：发了上一篇时评,我提出一个观点:我相信我们胡总是千年一遇的人物。有许多人不以为然，甚至说我歌功颂德。说实在的，一开始出来写时评，就是有感于胡总温总的奋发有为而人不知，国家民族命脉所系，我希望能通过文章来尽自己的一点绵薄之力。不然，每天花这么多时间写东西又没有回报，我吃饱了撑的？今天就比较一下中国有作为的帝王，大家一起看看，我的评价有没有道理。
 
在金鸿个人眼里，中国历史上最有作为的领袖人物有三个：李世民，毛主席，胡总。其实，在个人的论坛里，也转贴过两个写李世民和毛主席的贴子，今天呢，以对比的方式，看看金鸿的判断是否正确。

先谈一下李世民。

世人对李世民抨击最厉害的地方有两点：玄武门之变和李世民收了李元吉的妃子。

玄武门之变无疑是一场惨烈无比的宫廷喋血。但是，如果我们换一个角度来看这个问题呢：如果李世民没有发动玄武门之变，那么天下会是谁的？十有八九会是李元吉的，当然，李元吉会先伙同李建成干掉李世民，自己再干掉李建成。李元吉的野心，在史书中是早有记载的。如果李元吉统治了中国会怎么样？如果李建成没有被李元吉杀死自己统治了中国又会怎样？他们两个谁有能力搞一个贞观之治出来？就这二位的水平，恐怕连汉朝的文帝景帝都比不了。还有一点，我们不能不承认，几千年的封建史中，为了争夺皇位而发生的宫廷杀戮多如牛毛，几乎是历朝历代都有，可以说，这是我们的民族性决定的，都是中国人，为什么要苛求于他一人呢？

再就是纳妃之事。其实，李世民不但纳了李元吉的妃子，还收了隋炀帝的萧皇后。在此，金鸿想提醒大家一点：李世民身上一半的血统是蒙古贵族的，在当时的蒙古，可汗中有“妻群母”的传统。这样的环境中，出现这样的事情，不是很正常吗？任何人都不可能脱离具体的社会环境而存在。其实，李世民执政其间，曾大规模的放出过宫女，他的后宫的女人与历朝的皇帝相比，是少而又少的；而大规模放出宫女的行为，在中国的封建史中，是不多见的。

也有人说，打天下的是李渊。其实，李渊造反，最早的谋划者是李世民，李渊自己在造反开始时也对李世民说过：“今日破家亡躯亦由汝，化家为国亦由汝矣！”

至于李世民的水平如何，我们看隋未起义的四巨头（李密、世民、王世充、窦建德）中一开始被人认为夺取天下最有希望的李密的评价吧：李密投降李渊后，见到李渊，“自恃智略功名”，脸上“犹有傲色”，可他一见李世民后，“不觉惊服”，私谓殷开山曰：“真英主也！不如是，何以定祸乱乎！”至于王世充和窦建德，是李世民一战而全擒的，他们没有不服气的理由。窦建德在被李世民抓了后更是说了句俏皮话：“今不自来，恐烦远取。”

李世民偃武修文的政策，有了天下太平，也有了四海归化。这一点比起把老子留下的家底全打空了的汉武帝刘彻，强了千倍。（当然，刘彻时也有外患怙恶不悛的原因，不得已而为之,但就治理天下的水平而言,刘仁兄是没办法与李世民相比的,看看他那些无用的丞相吧）

其实，看一个人如何，不必看他本人如何，看他做器重的人、与他关系最密切的人就足够了。只要这些人素质过硬，人品高尚，这个人绝对是素质过硬、人品高尚。李世民打天下时，最倚重的文臣是房玄龄、杜如晦，定天下后，最倚重的是魏征，而这三位是历史上少有的贤臣。其实的文臣如：虞世南、褚亮、姚思廉、李玄道、蔡允恭、薛元敬、颜相时、苏勖、于志宇、苏世长、薛收、李守素、陆德明、孔颖达、盖文达、许敬宗，还有闫立本、褚亮等人，至于武将，如李靖、尉迟敬德、秦琼、程知节、李世赜等等，人才济济。历代少有。

在中国历史上，吏治最清明的时代只有两个：一个是贞观之治，另一个就是49-76毛主席时代。这两个时代，几乎没有贪污犯。

另外，李世民是中国历史上最开明的帝王：中国封建史上唯一一个不“抑商”的皇帝就是李世民，正因为如此，才有了唐王朝的繁荣昌盛。当然，李世民的开明，还表现在他对“异已”的宽容。 资治通鉴中有这么一段记载：有刘恭者,颈有“胜”文,自云“当胜天下”,坐是系狱。上曰:“若天将兴之,非朕所能除;若无天命,‘胜’文何为!”乃释之。如果这件事发生在康熙时代，恐怕这个姓刘的要被诛九族了。

既然这里比较到了康熙，就顺便谈一下吧：许多人认为康熙乾隆不得了，金鸿不以为然。先说一下十全老人乾隆，他的作为就象他的诗，一辈子作了数万首，可惜无一传世，治国也是如此，好象大有作为，其实，了了。康熙似有作为：平三藩、收台湾、剿葛尔丹、抗沙皇。其实，中国真正落后于世界，就是从他开始的。比较一下与康熙同时代的两个帝王吧：沙皇彼德大帝、英国伊丽莎白女王。英国从伊丽莎白开始了工业革命，走上了日不落的征服世界之路；彼德励志改革，走上了沙俄领土扩张之路。相比之下，康熙又如何呢？

如果有朋友对李世民感兴趣，可以看一下金鸿转贴的《中国历史上唯一没有贪污的半个王朝 》http://blog.sina.com.cn/s/blog_3fe443f701000bvk.html


下面再简单谈一下对毛主席的一点看法：毛主席是人类历史上前无古人的政治家，如果硬要找一个来比较的话，华盛顿或可一拼。但是，华盛顿有两个大错：一是把国家的货币发行权交给了私人银行，今天的美国，已不是华盛顿、杰弗逊、 富兰克林所努力构建的那个自由民主的国家了，一切都变味了，其错误就在于此。二、华盛顿对印弟安土著的杀戮可谓灭绝人性，这一点，决定了他从“道德”的角度无法让世人满意。

毛主席人品如何？看看周总理和朱总司令就知道了。这二位是毛主席的左膀右臂，至死不渝的支持者，而毛主席也从未抛弃过他们。“道不同，不相为谋”。如果不是同道之人，会如此吗？

至于十年文革，时间会还世人以真相的。

利已主义、享乐主义、无ZF主义已将今天的国人腐蚀的差不多了。中华民族是一个没有国教的国家。没有国教，可以摆脱迷信，但是，有两个致命的缺点：一是普通人没有是一个无形中支撑他的精神支柱，从而无法坚守道德底线；二是放纵了许多人的无法无天，他们已为“老老大、自己老二”，当然，死之前呢，又怕自己会下十八层地狱。这些，恰恰是没有崇拜的致命弱点----欧美国家有国教，是有道理的。

这里有一篇写主席的文章《一次又一次地震撼了整个世界的伟人 》，有兴趣的朋友可以看一下：http://blog.sina.com.cn/s/blog_3fe443f701000cb1.html
 

最后说一下我们胡总:的确,胡总执政只是五年,可他身上表现出了许多只有在李世民和毛主席身上才有的特质，所以，金鸿以自己的眼光坚定的相信，我们胡总，也是能震悍千年历史的人物！

最后，引一条新闻：

*中国为确保守住十一五期间18亿亩耕地的红线，暂停了1600万亩的退耕还林计划。日前，国务院发布关于完善退耕还林政策的通知。通知提出，为确保“十一五”期间耕地不少于18亿亩，原定“十一五”期间退耕还林2000万亩的规模，除2006年已安排400万亩外，其余暂不安排。*

看来,我一周前的<调查>并非杞人忧天,中央今天的行动证明了一切.也感谢在各论坛和我博客里积极跟贴提供支持的网友们!现重发一次调查的原文如下:

=我发现了一个现象,现在国内许多农村的农田都改成经济林了.我询问过许多朋友,这种事全国许多地方都有.甚至有的地方因为种树多绿化率大幅提高被环保部门表彰.站在地方ZF的角度看,这是好事,有利于农民创收提高收入.但是,如果全国大范围的这么做,中国的粮食产量将出现下降,如果再遇上天灾,那么,也许中国会出现粮食危机.一旦出现粮荒,则人心动荡,如此时再起谣言,必有大麻烦.民以食为天呀.挣钱是好事,但吃饭最要命.所以,上面有关部门最好查一下这事,让经济林控制在一定范围内.再结合以前出现的拿粮食做乙醇的事，这是有人在拿粮食做文章呀！希望大家跟贴也说说自己当地农村有没有上面提到的事，看看这事的范围到底有多大．希望这是我的杯弓蛇影，庸人自扰．=

 
最后希望那些天天在网上没事找事乱攻击的人网友一句:有时间干点人事吧,不要再做那些让人笑的蠢事了.


*** 【奋进社/金鸿95】中国的全球战略

写中国的全球战略，不得不从美国写起。因为美国是中国最大的敌人，而中国也是对美国霸权威胁最大的国家。

*中国的全球战略目标，自然是打倒美国的霸权。* 问题是，我们该怎样做，才能达到这个目标呢？要打倒美国的霸权，首先必须明白，美国霸权的命门在哪里。

*美国霸权的命门，就是美国的金融霸权，* 美国的超强军力是为美国的金融霸权服务的。美国的金融霸权，第一表现就是美元是世界通用货币，第二表现就是美国掌握着全世界大宗商品的定价权。

美元之所以牢固的占据着世界通用货币的位置，是因为美元跟石油捆绑在一起。说到美元与石油的捆绑，不得不提巴以和谈。美国是通过控制巴以和谈来保证美元与石油捆绑在一起的：

美国通过以色列时刻威胁着中东产油国家的安全，而美国对以色列的支持是全天候的。因为没有一支全面抗衡美国人的力量在中东，所以，受着威胁的阿拉伯国家不得不也倒向美国，以求在美国的庇护下获得国家安全上的保证。当然，美国人是收保护费的。美国人要的保护费就是阿拉伯国家的石油用美元结算，然后阿拉伯国家必须把通过出口石油挣得的美元重新投资（和花费）到美国。这样一看，阿拉伯国家完全是美国的“奶牛”。同时，美国利用伊斯兰逊尼派与叶什派的矛盾，通过拉拢阿拉伯国家来围剿叶什派国家，实现自己独霸中东的梦想。

美国就是这样把美元和石油死死的捆在一起的。石油作为最重要的战略资源是任何一个国家都须臾不可离的。借着石油这种战略资源，美元成了全球通行的货币，世界各国也主要以美元为储备外汇进行国际结算。美国因此而获得的好处是无法估量的：首先就是美国人通过过多发行美元造成美元贬值（全球性的通货膨胀）以引发世界财富的重新分配----直接表现就是各国储备的美元价值“缩水”了，这也相当于美国向全世界人民征了税。另一个重要好处就是美国通过操纵石油价值来达到掏空某些国家经济、保卫自己世界第一强权位置的作用。在这一点上最经典的案例有两个：一个是1973年放手让美元疯长400%，狠剪了一把发展中国家的羊毛，二个是压低油价、残酷打击苏联经济最后导致苏联解体。

所以，美国要想继续始终保持自己的世界第一强权的位置，必须牢牢的控制住中东，把石油和美元死死的锁在一起。而想到打倒美国霸权的唯一办法，也是把石油和美元分割开。 *要想让石油输出国家改变用石油结算的现状，就必须为他们提供安全保护。* 现在的中东在美国人的保护之下，这些国家不用美元结算行吗？现在伊朗的石油已经改用欧元了，就是因为中俄为伊朗的国家安全提供了保护；而当年小布什之所以下决心推翻萨达姆政权，也是因为萨达姆想把出口的石油改为欧元结算而又没有国家能保护的了他。

现在，不光伊朗，叙利亚也处在了中俄的保护之下了：2007年12月26日，中国中东问题特使孙必干与叙利亚外长穆阿利姆会晤时，孙必干宣称，中方支持叙利亚收回戈兰高地的正当要求，希望早日重开叙以和谈。这就是中国最明显的态度。支持叙利亚收回戈兰高地就意味着中国愿意卷入叙以纠纷、得罪以色列和美国，保护叙利亚的国家安全。只要中俄在中东的军事影响力越来越大，愿意接受中俄保护的国家将不仅仅是逊尼派国家，阿拉伯国家也会产生这样的“想法”。

当然，有“想法”是一码事，付诸行动是另一码事。如何能让阿拉伯世界把“想法”变成行动呢？办法只有一个，就是让他们看到跟着中国（也包括俄罗斯）能得到好处。如果叙利亚能在中俄的支持下，顺利的重开叙以和谈并得到相应的好处（类似的，中俄正在做准备工作的还有黎以和谈），因为在巴以和谈上迟迟看不到欧盟为他们争得正当权益，产生另攀高枝的冲动将是不可避免的。

其实，一开始，中国俄罗斯是寄希望于在巴以和谈中从美国手中分权的，只不过，美国选择了宁可对欧盟让步，决不对中俄松口的做法。等得不耐烦的中俄只好自己准备谈判桌了。也好，中俄比美国要大方，一开就是两桌：叙以、黎以和谈。谁敢说只有欧洲人关心中东和平？——美国在中东花大力气搞的是“中东民主”，欧盟向中东国家推销的才是“中东和平”。接下来，不管是通过新开的两桌谈判替叙利亚、黎巴嫩捞得好处，还是迫于中俄在场外的压力而威逼以色列对巴勒斯坦让步，都会被阿拉伯国家及时的捕捉到，并增加向中俄靠拢的决心。

只要中东产油国家一个个的站到了中俄这边，中俄就可以有步骤、有次序的让这些国家与美国慢慢的脱钩。当然，中东国家石油不用美元结算了，会先改成欧元，这也是欧盟求之不得的，也是欧盟一直在努力做到的一点。这样还可以激化美欧之间的矛盾。面对着直打自己七寸的欧盟，美国人一定会全力反击。另外，因为中国持有巨额的外汇储备，可以时不时的拿着这笔巨资是多一点美元还是多一点欧元做文章，在美欧中间灵活的跳一下摇摆舞——只要中国动作一大，同样拿着大把美元储备的日韩印等国家肯定跟着做动作。这样可以从经济金融层面给中国也不时的捞一点油水出来。而俄罗斯也可以趁乱做一下出口石油用卢布结算的工作，跟着拆一下美元的墙角。

只要这样努力下去，把美元与石油彻底拆分了家，美国人耀武扬威的日子的就结束了。当然，打倒美国霸权是一个系统的工程，不是仅平几条妙计就可以做到的。

我们必须在以下六个方面做好扎实的工作：

1、科技上赶超。只要美国是世界上科学技术最先进的国家，它就永远是世界的领袖国家。要想把它赶下领袖的座位，科学技术方面必须赶超它。以我们中国人的创新能力，只要坚持独立研发，二十年内全面赶超是可以实现的。

2、政治上顶住。在国际斗争中，必须坚决顶住美国的压力，保护所有朋友的利益，寻找一切机会打击美国，包括愿意充当其走狗的国家。在联合国，无论是中国俄罗斯，还是法国，该动否决票时坚持不要客气。

3、军事上压住。狗急了跳墙。把美国逼急了，它肯定会找机会发动战争以扭转局面。所以，要坚决打击美国的一切军事冒险意图。只要美国敢动手，必须坚决回击。只有充分的准备战争，才能防止战争的发生。

4、经济上拆散。充分联合一切可以联合的力量，拆散美国的经济势力范围。APEC必须拆掉，把日本、韩国和东盟拉离美国的势力范围。在美国的后院也要狠挖墙角。在非洲，更要想办法把美国人顶出去，因为非洲有资源和廉价的劳动力。不要以为美国的那些大企业有多么多么强的竞争力，只要把美国的经济势力范围掏空了，美国的那些巨无霸级的企业会统统破产。一句话，把美国商人赶回美国本土去！只要美国的企业不行了，美国的军事、科技、金融就基本歇菜了。

5、金融上掏空。用石油欧元在中东排挤石油美元，人民币、卢布、日元居中策应。

6、实力上消耗。利用伊拉克和阿富汗两个战场全力消耗美国的有生力量。美国一时半会下不了撤出阿富汗的决心，因为美国一撤，上合就在伊朗、巴基斯坦、阿富汗连为一片，直逼中东。美国在中东的压力将会更大。只要美国从阿富汗一撤，土库曼斯坦将全面投入上合，阿塞拜疆也会“学习土库曼好榜样”，吉尔吉斯斯坦呢？乌克兰呢？所以，在阿富汗美国必须死扛。伊拉克的情况也差不多。只要美国一撤，伊拉克的石油一桶也没有美国人的份。签了的合同又如何？照样废掉！有本事再打回来！伊朗也会更加的无法无天，叙利亚也会学着伊朗的模样装大爷。阿拉伯国家还在乎以色列？个个都会往中俄的怀里钻。

只要这些方面都做到了，打倒美国霸权不在话下。接下来的欧盟就要容易对付的多——一个政治上不统一、军事上不够强大的组织是成不了世界霸主的。既使中国不收拾它，俄熊也会啃了它。欧盟到头来只会落个给别人做嫁衣裳的下场。当然既(即)使知道这个下场，它仍然会在中东狂拆美元墙角，因为如果不这样做，它亏的更多。



既然写中国的全球战略，就不能不回顾一下中国过去的全球战略是如何执行的：

我们的人民共合国刚刚建立，美国就侵略朝鲜、直逼中国。毛主席带领着中国人民抗美援朝、保国卫国。一战下来，打出了中华民族的尊严，打出了中华民族的生存空间。

1959年，中苏分裂。中苏分裂的真实原因是：艾森豪威尔上台后，变美国的战略从“遏制”为“大规模报复”，一切跟核战争挂钩，放弃过去认为在有限战争中不应使用核武器的想法，决定只要军方认为军事上需要就可以使用核武器，面对美国以核优势为后盾的“大规模报复”战略和“战争边缘”政策，苏联决定“缓和冷战”。 1956年2月的苏共二十大就提出了“和平共处”、“和平过渡”总路线。这实际是要求已经当政的共产党不要得罪美国，没当政的共产党（包括当时没统一的越南）别再走暴力革命的道路。潜台词：既然“一颗小小的火星就可以引起核大战”，那象抗美援朝那样的麻烦今后不能沾，免得惹火烧身，为了你的国家统一把我苏联拖进核战争。 

这样一来，中国收复台湾、维护领土完整和统一的民族利益就跟苏联的冷战需要矛盾了：要统一台湾就必须反掉美国的干涉。经过麦卡锡主义肆虐、顽固坚持冷战理论、敌视中国的美国坚决拒绝跟中国做任何妥协，甚至根本不承认中国政府，只承认在台湾的蒋介石当局代表全中国。最典型的事例就是1954年日内瓦会议上杜勒斯拒绝与周总理握手——敌视到这个份上，怎么“缓和”？即使中国放弃统一台湾美国都不会答应，更不用说中国坚持收复台湾了。毛泽东面临的问题是：是为苏联的冷战需要而牺牲中国的民族利益，放弃收复台湾的努力，还是为中国的民族利抵制苏联的冷战需要？毛泽东“咬定青山不放松”——咬定中国的民族利益绝不松口。这才是中苏决裂的根本原因。

在一般人看来，当时的中国实在是毫无希望了：外有强敌，内乏粮草，压力空前巨大，处境极端艰难，“黑云压城城欲摧”。中国既没有力量对抗苏联，更没有力量对抗美国，又没有办法劝说美苏改弦易辙改变对中国的敌对态度。

在这个中华民族面临空前危机的时刻，毛主席使出了他最得意的国际斗争谋略：中苏论战+抗美援越。具体的做法是：支持越共中央武装统一越南；《毛泽东选集》第四卷出版，指出 “帝国主义和一切反动派都是纸老虎”，要和美国打“人民战争”、“持久战”；批判苏联对美投降、背叛马克思主义。

毛主席这一下子同时戳到了美苏两家的痛处：美国苏联都是在自己阵营里当老大的主，最怕的是镇不住台。美国惟恐被看成“纸老虎”而众叛亲离，决心不让南越垮掉，马上跳进了越南战争的泥潭，从此越陷越深。这下苏联也坐不住了：袖手旁观、任凭美国肆意欺负“社会主义大家庭”的成员北越，那“龙头老大”的面子何在？威信何在？还保得住“社会主义阵营领袖”的地位？于是不得不援助越南对抗美国。而且为了证明自己才是正牌的社会主义阵营的盟主，不但援越，而且专给中国当时给不了的先进武器。——抗美援朝时中国的先进武器都得自己花钱向苏联买，买回来自己学着使用，然后再自己费尽心血送上前线去拼命。现在倒好，毛泽东一个“中苏论战”就让苏联一个子不要还卯着劲地白给，给的还净是当时中国给不了的好玩艺，还不劳中国人冒险，由老毛子亲自出马送货上门把着手教越南人使用，或者直接派人操作——这等于无偿帮着中国实现“让美国吃个史无前例的大败仗，使美国自己得出结论：跟中国敌对没有好处，不得不有求于中国”的战略总目标。这下中国可省大发了：有人心甘情愿倒贴着白帮忙还不用领情——我不谢你，你也不觉得是在帮我，连“聒噪”两字都省了，代价不过是“中苏论战”的一通笔墨官司——世界上还有比毛泽东的这招阳谋更巧妙更合算的买卖吗？苏联这一上劲，美国更不敢无限制扩大战争了：要扩大，是扩大到中国还是扩大到苏联？结果：战争一直老老实实局限在越南，使越南战争变成了一场符合毛泽东理想的时间、理想的地点、理想的方式的理想的人民战争，没有扩大到中国。再加上中国是在指责苏联背叛马克思主义，对美国搞投降，这种指责本身就使苏联清楚中国没打算和美国联手对付自己。如果放着越南不管却跟美国伙在一起收拾中国，就没法证明自己是“正统马列主义者”和“国际共产主义运动的领袖”，所以既下不了决心也没有借口立即进攻中国。毛泽东巧妙地利用了美苏矛盾，限制了战争扩大，争取了时间，使中国得以加速备战、加快“两弹一星”、开展三线建设，使自己的安全有了切实的保障。

美国几十万大军陷在东南亚的沼泽里无法自拔，苏联则趁机大举扩张，在全球到处挖美国墙脚。美国此时突然如梦方醒：上了毛泽东的大当了。原来美国真正的要害利益不是在东南亚的烂泥潭里，而是在中东和欧洲；真正威胁美国利益的不是“好战”的中国，而是美国以为“可以有共同利益”的苏联。美国敢情被毛泽东诱进了越南战争的沼泽地白挨揍，如同老牛掉进井里——有力没处使，进不得退不得，眼睁睁看着苏联坐大而无可奈何。如果还不顾一切继续在越南硬抗到底，就等于自我了断，把世界霸权拱手让给苏联。不管是谁当美国总统，借他八个胆他也不敢走到这一步。 

1969年尼克松上台后宣布美国从越南撤军，使战争“越南化”，通过谈判取得“体面的撤退”—— 不管你南越是死是活，反正我美国得走人了。我走后你南越有本事就靠自己活下去，没本事就听天由命。我真正关心的是别一垮一大片，弄得我管也不是不管也不是。只要美国脱身后只垮掉一个南越，那就谢天谢地，就算“体面的撤退”了。

1972年尼克松访华，向毛主席登门求和。既然有求于毛主席，那就不得不满足毛主席开出的价码。最终结果：美国解除对华封锁和外交孤立政策，承认一个中国、台湾属于中国，支持恢复中国的联合国席位和常任理事国地位、联华制苏。从此，世界政治力量的格局开始从“美苏两极世界”演变为“美、中、苏”三极的“新三国演义”。（毛主席时代的中国战略部分系摘抄黎阳先生的《如何看毛泽东时代》一文，在此提出感谢。）



可惜的是，这时的毛主席，年世已高，没过几天就离我们而去了。毛主席刚刚过世不久，奇怪的一幕马上出现了：中国开始韬光养晦了！刚刚打完八年抗战时，中国遍地废墟，毛主席没有韬光养晦；刚刚建国时，中国一穷二白、内外交困，毛主席也没有韬光养晦。为什么在毛主席刚走、中国外交形势一片大好的时候却要韬光养晦？

韬光养晦的结果是什么？有两个标志性的事件可以说明一切：国内方面，运10下马；外交方面，美国国会通过了《与台湾关系法》。从运10下马开始，中国开始了“以市场换技术”的道路。自主研发哪比的了引进技术快！结果呢？还是拿大飞机来做例子吧，如果不是胡主席执政，今天支线飞机能不能下线还是个未知数，更不要提大飞机了。国有企业先是搞合资、合作，最后干脆大甩卖。还是毛主席留下的底子厚，二十多年都没卖光。仅此一点，说毛主席不懂经济的人就得统统闭嘴！至于那部严重侵犯中国主权、干涉中国内政的《与台湾关系法》，就更不用提了，如果毛主席他老人家在世，就算美国国会的议员们拿枪顶在卡特（当时的美国总统）的脑袋上，他也得把国会刚刚通过的那部《与》法给否决了！——一面有求于中国要急着跟中国建交，一面还敢对中国内政指指点点？也是美国人时来运转，中国开始韬光养晦了！我们一路的韬光，一路的养晦，直到有一天，我们的大使馆都被人炸了，这时，国人猛然发现，再养下去中国就完蛋了！



天佑中国，胡主席上台了。05年3月14日，《反分裂国家法》通过。那时，胡主席刚刚带领中国人民走出了非典的阴影，稳住了阵角。《反分裂国家法》是一部《与台湾关系法》迎头撞车的法律。美国人通过《与》法来干涉中国内政、给台独势力打气、并随时准备在美国人需要的时候挑动台独搞独立以打断中国的经济建设进程。《反》法则迎头撞来——除非美国人真的敢于为了台湾跟中国打一仗，否则就不要再给台独分子发错误信号了。所以，我们有幸看到了一幕非常有趣的场面：美国众议院以424比4通过决议案，敦促布什对反分裂法提出严重关切——如此压倒性多数通过决议案愣是连个“反对”都不说，不是“纸老虎”是什么？从此，再也听不到美国人开口闭口的把《与》法挂在嘴上了。

从这时起，胡主席带领着中国人重新开始了征服世界的道路（对此，我们不必隐晦，任何一个国家都希望征服世界，我们为什么就不可以呢？）。为什么如此看重《反》法呢？道理很简单：如果我们的内政都能随随便便被人指点，我们又凭什么让我们的朋友依靠我们、敌人惧怕我们？我们连保护好自己的能力都没有！所以，当《反》法强硬通过的时候，就是我们胡主席向全世界宣布“当年打得美国佬满地找牙的中国人又回来了”的日子。

从此以后，中国的全球布局有条不紊的展开了：

1、东亚方向：用《反》法捆死了美国的台湾政策；把朝鲜纳入自己的保护范围，支持朝鲜经济发展和东北亚经济一体化、离间韩美关系；推动“东亚核竞赛”，直至06年用朝鲜核暴全面离间日美关系；加快推动东南亚经济一体化，把东盟做成中国的“后院”。

2、北亚方向：完善上合功能，全面深化中俄联盟，中国支持俄罗斯政治上、军事上对美强硬、经济上俄罗斯允许中国布局中亚，努力实现为上合成员国及其前苏联国家的全面经济捆绑。

3、西亚方向：与巴基斯坦全面捆绑并以此为跳板跳入中东；对印度既拉且打，军事上威慑、经济上拉拢，分裂所谓的“美印日澳同盟”；大手笔投资伊朗与伊朗捆绑、跳入直到控制伊核会谈进程，至到今天准备以伊核问题为桥头堡全面插手中东和平进程。

4、非洲方向：全面深化与非洲国家的联盟关系，经济上进一步融合，政治上加大对非洲盟友国家的支持。

5、欧洲方向：经济、科技层面加深合作，政治上加强协同，努力建立抗美统一战线。

5、美洲方向：毫不客气的与俄罗斯欧一起插手美国后院，当然，中国欧洲以经济布局为主、俄罗斯以军事政治为主（包括卖军火）。

透过这些，我们可以依稀看到了毛主席的影子——胡JINTAO同志接过了毛主席的枪。



  
*** 【奋进社/金鸿95】西方经济学的陷阱

——一篇推翻凯恩斯主义的经济论文

与只凭想象说话的微观经济学相比，西方经济学中的宏观经济学理论还是有一定科学性的。为什么那些经济学精英们不再坚持用分析微观经济的思路来分析宏观经济呢？道理很简单：如果经济学精英们希望他们的理论能上得“庙堂”，就不得不在许多地方“从实际出发”，而不是一分析问题就 “假如假如”的云山雾罩一翻。但是，宏观经济学同样存在着许多陷井，是我们不得不防的。现在把它们揪出来，以示世人：



+ 一、过时的萨伊法则：



200年前，萨伊提出了被西方经济学界奉为经典的"=萨伊法则="，即供给会创造出自己的需求，换句话说就是“生产会自行创造销售”。

这一观点正确吗？恐怕大家会说，不一定。因为在今天的市场竞争中，有太多的企业由于销路不畅、库存积压而导致资金链断裂、企业不得不破产，所以，现实并不支持“生产会自行创造销售”的观点。

不过，如果我们换一个角度看，萨伊法则又有它非常科学的一面。这个观点是1803年提出来的，当时的欧美国家都处于卖方市场。在卖方市场条件下，萨伊法则是基本正确的，至少没有明显不符合经济社会现状的地方。欧美国家进入买方市场是150年以后的事了（中国经济进入买方市场是1995年以后的事情）。我们可以拿中国经济作例子简单看一下卖方市场的一个事实：年纪大一点的人应该都还记得当年的“布票”、“肉票”吧？这些“票”就是卖方市场现实下厂家生产产品供不应求的一个真实写照，在这样的现实之下，“生产”当然“会自行创造销售”，就怕你生产不出来！

萨伊和李嘉图以萨伊以萨伊法则为基础得出一个重要推论：所有商品都生产过剩的经济危机是不可能的。应该说，这个推论没错：在卖方市场条件下，怎么可能出现全面的生产过剩呢？如果出现了，那就是买方市场了。从这里就可以看出萨伊法则的局限性。很显然，这是一个过时的理论。而 *现代的西方的宏观经济学就是建立在萨伊法则基础上的* 。

一栋建立在沙子上的大楼谁敢住？

19世纪初，美国福特汽车公司通过推行流水线和科学管理大规模降低生产成本，确立了在汽车市场上的霸主地位。成功后的大老板福特曾经傲慢的说过一句话：“我不管顾客需要什么颜色的汽车，我的汽车只有黑色的。”这句话把生产厂商在卖方市场上的强势地位清晰的描绘了出来，当然，这也是一句实话，如果不是因为福特汽车都是“黑色的”，它也成不了霸主——大规模标准化生产以降低成本从而确立自己在汽车市场上的成本领先优势正是福特汽车的成功之道。但是，随着汽车市场从卖方逐渐进入买方市场，仅仅一个“黑色的”汽车外壳已满足不了顾客追求个性的要求，福特公司却没有及时跟上顾客需求的变化。这时，小斯隆当上了美国通用汽车公司的总经理。他采取了事业部制来对通用汽车公司进行管理，注重满足顾客的个性化需求。于是，通用汽车公司迅速超过了福特汽车公司成了汽车市场上的新领袖。成也“黑色”的福特在市场竞争中落得了个败也“黑色”的结果（当然，福特制、科学管理理论和小斯隆的事业部制都是划时代的企业管理理论）。从这个例子可以看出，生产厂商在卖方市场和买方市场上的表现完全不同。

宏观经济学也支持这样的观点：宏观分析的投资需求是一定时期的单个厂商或企业的投资汇集而成。单个的厂商（或企业）的投资心态都发生了变化，宏观分析的投资需求能不也跟着发生变化？既然现实都变了，理论为何不“与时俱进”？我们都知道“刻舟求剑”的故事。在那个故事中，那个找剑的傻子只不过是坑了自己而已。现在，打着“科学”、“经典”旗号的经济学精英们又是在坑谁呢？他们可是在对我们的宏观经济政策指指点点！

鉴于凯恩斯的宏观经济模型同样以萨伊法则（S=I）为基础进行推导，所以对萨伊法则的错误推导不得不再做一点更深入的剖析：

萨伊法则的等价命题是：任何数量的储蓄都会全于变为投资（S=I），其实，这一点是否成立，有两个关键的因素必须考虑到：一、萨伊认为货币只有“价值尺度”和“交易媒介”两种职能，这与事实远不相符。现实经济生活中，货币至少还有一个“价值贮藏”的功能，这就意味着，在社会上会有一部分钱存在“既不消费也不储蓄（投资）”的状态。二是在部分准备金制度下，银行系统有创造货币的功能（存款乘数）。由于这两个因素的存在，决定着萨伊法则是错误的（即S≠I）。

需要指出的是：萨伊的理论尽管与今天的经济社会状况不相符，在他本人生活的那个时代，萨伊的理论还是有其合理性的。比如，货币的“中性”观点（货币供应量的多少及其增减变化，对于实物领域即商品总量及其构成以及各商品的交换比率等三个方面没有任何影响，货币及其数量只决定商品价格的名称及其绝对水平），在当时社会也是合理的。因为那个时代处于金本位时代，几乎没有通货膨胀。进入廉价货币（纸币）时代则不然，刻意的增发纸币必然引发通货膨胀，货币当然也就不再呈现“中性”。从这个意义上说，萨伊比起一代宗师凯恩斯来，还多了一点学者的良知。





+ 二、凯恩斯骗局：



凯恩斯号称西方经济学史上的革命性人物，其形象一直光辉无比。今天的经济学精英们，多数为凯恩斯的徒子徒孙。可是，他的理论是一套彻头彻尾的骗局。下面一一列举：



1、掩盖真相的“工资刚性”

“凯恩斯革命”推翻了萨伊法则关于宏观均衡的国民收入和就业量必然是充分就业的教义，作出了“工资刚性”的假设。即货币工资在一定时期内固定不变，这不同于萨伊法则关于劳动市场是完全竞争这一前提。在完全竞争条件下，只要存在失业，工人之间的竞争将迫使货币工资下降。而凯恩斯认为，在现实生活中，工人坚持不肯降低的是货币工资，有些失业工人，在货币工资不变物价上升、从而实际工资降低的情况下也是愿意就业的。很显然，凯恩斯的假设是有悖于常理的。难到工人们都是自欺欺人的傻子：五毛钱两个的鸡蛋不买，专买二毛五一个的？

当然了，象凯恩斯这种天才，既然做出了这种假设，肯定有他的目的。从他的“工资刚性”假设本身自然看不出他的目的，他的目的体现在他由此而推导出的经济政策主张里。他的政策主张是：降低货币工资，现实上或政治上难度很大，而通过增加货币供应以提高物价，从而降低实际工资，既简便易行，又可得到减少失业的效果。从这里，我们应该看到：降低货币工资在实际生活中是很正常的，失业工人之间的竞争必然导致工资下降。前几年不是传出过有大学毕业生为了进去好一点的公司就业而不要工资的吗？凯恩斯却说“难度很大”，很显然，他在说谎。他说谎的目的是什么？就是“增加货币供应”！

在金本位下，增加货币供应是很难行的通的，因为只有“上帝”才能制造黄金；那么，怎样才能增加货币供应呢？自然是用廉价货币（即纸币）。但是，在“凯恩斯革命”之时，英国正从金汇兑本位向不兑现纸币本位过渡的时期。由此可以清楚的看出凯恩斯“闹革命”的目的了：为廉价货币政策张目！

不过，在廉价货币通流的情况下，过度的增发货币必然导致通货膨胀而造成社会财富的重新分配。如果发行货币的银行归国家所有，那么，普通老百姓可能不吃亏，因为国家可以通过自己手中掌握的过多发行的货币来对老百姓进行补贴，在这种情况下，甚至可以促进社会收入分配的公平化。但是，如果银行掌握在私人手里，那时，增发货币就意味着变相掠夺普通老百姓的财富。说到这里，大家应该明白了，“凯恩斯革命”是在从理论上对私人银行家的掠夺行为合法性进行辩护。

事实上，凯恩斯年青时就已经认识到了通货膨胀的巨大的危害：没有金本位的情况下，将没有任何办法来保护人民的储蓄不被通货膨胀所吞噬。凯恩斯本应该是金本位的坚定拥护者，为何后来将黄金贬低为“野蛮的遗迹”、鼓吹廉价货币理论？因为他也是“理性人”，也要实现个人收益的最大化。当然，凯恩斯“理性”的结果，就是红的发紫，紫的发黑。



2、欺骗世人的消费函数

凯恩斯的消费函数C=a+bY是其宏观经济模型中的一个非常重要的函数。但是，这个消函数并非统计归纳的结果，也不是根本先验的假定进行推演的结果，只是以偶然观察为依据；而另一消费函数C=bY是对经济事实统计归纳的结果。美国经济运行的事实数据证明，凯恩斯的消费函数C=a+bY在短时期内（比如十年）是与事实吻合的，但是，如果把考察的周期加长（比如七十年）来观察，则凯恩斯的消费函数并不正确，正确的函数形式为C=bY。

为什么会出现这样的情况？

其实，短周期的消费函数之所以是C=a+bY而长周期的消费函数C=bY的原因很简单：每个周期之间通过以严重的经济危机出现的年份为断点（关于经济危机成因的讨论在后面部分），而每次严重的经济危机都造成了强烈的社会财富再分配效应（我个人认为用这个名称比较合理、姑且这么形容）——经济危机本身是大资本家、大银行家来打劫中小资本家、银行家、其他中产阶级和普通劳动者财富而制造出来的经济崩溃状态。正是因为社会财富在经历过了严重的经济危机上进行了重新分配，才造成了消费函数的突变。如果没有恶性的经济危机的存在，那么，无论是短周期，还是长周期，其消费函数都是一样的，即C=bY。我们国家不存在因恶意的通货紧缩而出现的经济危机，所以，我们做宏观经济分析时，应该用C=bY这个函数而不是凯恩斯的那一个；当然了，计划经济时期（1950-1978年）的消费函数可能与1978年以后的不一样，这是很正常的事情，因为经济体制不一样。

当然，在凯恩斯的推理中也有破绽：

按照凯恩斯的分析，人们的消费支出与其收入之间具有一种稳定的函数关系：收入增加消费支出也会增加，但消费的增量小于收入的增量。凯恩斯的消费函数就是以此为基础导出的。但是，如果仔细看一下上面凯恩斯的观点，大家会发现，凯恩斯的消费函数应该用二次函数才是科学的（一阶导数为正，二阶数为负），而凯恩斯故意用了一次函数来描述消费函数，这一点显然与“经济学精英们”一贯以“科学严谨而不怕麻烦”的风格制做经济模型的做法不相符。这是为什么？道理很简单，二次函数与现实经济运行根本无法吻合，所以他不得不用一次函数来代替（把二次函数Y= -ax2+bx+c中的-ax2项去掉，并对bx+c两项进行重新修饰）。

现在我们就不得不多长个心眼了，即然年轻时的凯恩斯就发现了通货膨胀的危害、最后却替那些制造通货膨胀的人辩解，为什么他就没有发现这个消费函数存在的问题呢？就算他没有发现，他的那些徒子徒孙们难道就没有一个人去怀疑过吗？对于这个问题，有必要深思一下。凯恩斯关于“消费的增量小于收入的增量”的观点包含着一个道理，就是消费不足导致的有效需求不足是必然的，而有效需求不足的必然性意味着失业存在的必然性。而且，随着经济的发展，消费的“萎缩”会越来越严重——失业也会必然增加，严重到一定程度就是经济危机。——真相出来了，凯恩斯用自己的理论（包括消费函数公式）为世人洗脑：经济危机是必然的，不是人为的！——这样体贴资本家们心思的“精英”怎么会不红？怎么可能不是一代宗师、革命性的人物？只要资本主义制度存在，资本家们肯定会把凯恩斯的理论奉为《圣经》。

按照凯恩斯的说法，消费函数C=a+bY中的a为自主的消费，即收入为零时也会有消费。乍一看，这是正确的，对个人而言，即使失业也要消费，再一想，对一个社会而言，如果所有人都不工作，同样也需要消费，所以a是存在的。但是，事实果真如此吗？如果一个社会中的所有人都不劳动（收入为零），他们需要的消费品是谁提供的？难道是从天上掉下来的？对一个经济体而言，只要有消费存在，必要意味着有等量的收入（劳动）存在。消费和收入是一枚硬币的两个方面，不可分割。所以，现实中，不可能有那个可恶的a！（同样的道理，凯恩斯的税收线性函数、进口线性函数也都是错误的，两个函数都没有那个固定不变的常数项。）

可笑的是，某些西方经济学精英们为了把凯恩斯“偶然观察”出的函数与事实吻合起来，煞费苦心的搞了一大推的“收入假说”（包括绝对收入假说、相对收入假说、恒常收入假说等）。现在，这些“假说”应该改成“假话”了。

当然了，不能不说的是，凯恩斯确实是个“精英”，谎言编造的如此高妙，利用对人类直觉的欺骗来蒙蔽世人，的确不简单。可惜，再狡猾的狐狸也逃不过猎人的眼睛。



3、胡编乱造的货币需求模型

按照凯恩斯的观点，人们对货币的需求有三种动机：交易、预防和投机。投机动机的意思是，人们之所以愿意持有不能生息的货币，是因为持有货币可以用来买卖投机性的债券（即政府永久公债）。

如果不考虑购买公债的利息收益，站在公众整体的角度看，购买公债进行投机是一种零和博弈，有赚钱的就有赔钱的，今天所有人都赚钱了明天就会有大批人赔钱。但是，如果考虑利息收益，对公众整体而言，购买公债是一种投资行为。这和买股票是一样的，从个人角度看是投机行为，从公众角度看是投资行为；而且股票的涨跌规律和公债是完全一样的，都是“市场价值与利率成反比例变化”。

当然了，按照经济学精英们的观点，公债利息不能计入GDP，只能算是“转移支付”，因为取得利息收入的人没有提供相应的物品和劳务。但是，这只能是精英们的一厢情愿罢了。公债、股票和储蓄对公众而言，都是投资­——储蓄也是投资，只不过是通过银行间接进行的。如果硬要说这三种投资有什么区别的话，那就是他们的风险和回报率不一样。需要强调的是，储蓄行为是投资行为不代表公众储蓄额等于社会投资额。

公众购买公债是为了获利，但是，公债是永不偿还本金的（凯恩斯即以此为前提进行的分析）。所以，我们看到的事实是，公众中始终有一部分人持有债券（准备高价抛售债券以获利），还有一部分公众持有“投机”货币（准备低价购买债券以便在高价时出售获利）。这一点和股市上股民的整体情况是一样的，也是有人持股有人持币；和厂商的流动资本也是一样的，一部分已变成了消耗品、工人工资等，一部分做准备金；和公众出于交易动机持有货币也是一样的，一部分已购买了消费品，一部分做准备金。所以，凯恩斯所谓的“投机动机的货币需求”应该分成两部分：一部分是投资，归入储蓄(S)；一部分是准备金，归入交易动机的货币需求。

现在，我们可以清楚的发现，货币的总需求就是货币的交易需求。如果用“货币的供求与利率的决定示意图”表示，在任一时点上都是一条垂直于横轴的直线。而货币当局决定的货币供给在任一时点上，也是一条垂直于横轴的直线。现在，是不是有的朋友感觉到迷茫了？——在货币需求量与发行量不同时，两条直线是不相交的；因为他们是平行线，无论利率如何变化，都不会相交。这该如何解释？其实，这才显示出现实经济世界的本质：如果货币发行量大于需求量，就意味着出现了通货膨胀；如果货币发行量小于需求量，则意味着出现了通货紧缩；只有货币发行量等于需求量，才意味着经济运行中既没有通货膨胀也没有通货紧缩。因为货币发行是货币当局决定的，所以，不论是出现通货膨胀还是通货紧缩，都是“人祸”，而不是因为那只“看不见的手”。

现在，大家应该明白了，凯恩斯为什么要弄出一个“投机动机的货币需求”了。如果不把货币需求直线搞成曲线，如何与货币供给线相交？如何隐藏通货膨胀的实质？其实，把“交易动机的货币需求”与“投机动机的货币需求”相叠加以得出“货币总需求”是没有道理的，这就象一个人告诉你：“我今年30岁，上过4年大学，所以我今年34岁。”你一定会回应他三个字：“神经病！”

明白了上面的事实，也就更容易理解为什么会冒出个 “流动性陷阱”来了。现实中哪有什么流动性陷阱，只有“凯恩斯陷阱”！

凯恩斯对“流动性陷阱”是这样表述的：在现行利率很高（比如10%）时，人们预期日后的利率只跌不涨，则投机性货币需求为零；而在另一极端即利率最低（比如2%）时，人们预期利率只涨不跌，此时人们必将卖出债券以持有货币，由此，货币当局在公开市场活动中收购债券所增加的货币供应量，必将全部被公众作为价值贮藏手段保存在身边，这就是流动性陷阱。下面看一下凯恩斯表述中的破绽：

第一，流动性陷阱与现实不相符：当利率最低时，人们如果真的都认为债券价格以后只跌不涨而卖出债券（在理性人的假设下）时，就会出现集体抛售的局面，这时，债券价格必然会在极短的时间内暴跌，这种情况可以叫恐慌性抛售。这时，抛售者面临的选择只有两个：一是深度被套，如果是这样，就意味着无法象凯恩斯那样上嘴唇一碰下嘴唇就把债券换成货币；二是割肉抛售，如果是这样，能换回多少货币？又会损失多少货币？凯恩斯也没说。当然了，有人可能会说，货币当局会大量吃进债券以维持债券价格稳定。现实会如此吗？如果货币当局是私人的银行家，他们会“学习雷锋好榜样”吗？如果货币当局是为社会公众服务的，由于并不是每个人都在买公债，如果货币当局这时大量吃进公债就是在帮助一部分人止损，那没买公债的人不就亏了吗？货币当局做这样的买卖合理吗？

第二，就算是货币当局通过某种只有“上帝才有的能力”在公债价格非常平稳的情况下把公债买了过来，社会上存在的公债总量也是有限的。在这样的情况下货币需求曲线怎么又会变成了与横轴平行的直线？它应该是一个点才对！在这个点上，公众手里只有货币，没有公债。也就是说，在此时，货币当局继续增发货币，根本就没有公债可以从公众手里收购。现在，大家应该明白了凯恩斯不去确定公债总额的原因了：如果确定了公债总额，他又如何任意解读“无论货币当局如何收购公债以增加货币，都会被公众当作价值贮藏手段保存在身边”，并造成一种货币需求可以无限增加的假象？他又如何解释货币当局严重过多发行货币造成货币供给量线与货币需求线无法相交的情况？现在好了，因为“流动性陷阱”，货币需求线可以平行与横轴并无限延长，就算货币当局造成10000%的通货膨胀，都可以蒙混过关了！

——好不精明的凯恩斯！敢玩弄世人的凯恩斯！一代宗师就是这个德行？难怪后世的经济学精英也是这个德行！因为有一个好榜样！

在此也顺便说明一下为什么07年中国的通货膨胀如此严重：有太多的“热钱”通过地下钱庄或者其他非法渠道进入了中国，并兑换成了人民币，所以，中国经济体中的货币就比实际的货币需求量增大了，即货币过量发行了，所以通货膨胀出现了，这也是06、07年中国外汇储备不合比例的高速增长的原因。出现这样的通货膨胀也不是我们的政府愿意看到的，因为“热钱”不是走的合法渠道，所以不在我们的央行控制之下，这也是06、07年中央狠查地下钱庄的原因。只有非法流入“热钱”的渠道堵死了，才不会出现我们的央行被动过量发行货币的现象——只要有美元进入了我们的储备体系，我们就得发行等价值的人民币进行兑换。

第三，既然买公债可以算投机动机，那买股票同样得算投机动机。现实经济生活中，在利率非常低的时候，公众往往更多的把钱投到股市上去，造成股市的暴涨。这时，“流动性陷阱”如何解释？

由于凯恩斯的货币需求模型是编造的太不合情理，所以，在以此为基础进行分析时，闹出了大笑话。在《宏观经济学》教材（注：本案例是从复旦大学出版社出版的《西方经济学》第三版一书中照搬的，该书作者为宋承先、许强。）第191页中有一个关于“货币的供求是怎样从失衡趋向平衡”的例子，内容摘要如下：

前提：利率为6%，此时人们自愿持有的货币为1050亿元（交易动机1000亿元投机动机50亿元），利率为4%时投机动机100亿元，利率为3%时投机动机150亿元。

现在，假设当前利率为6%，而货币供应为1100亿元，下面看一下凯恩斯大佬是如何把“失衡”搞“平衡”的：在此时（人们手中有100亿投机货币）人们会将多余的货币购买债券，由此引起债券价格提高、利率下跌，直到利率跌到4%为止（此时货币总求增为1100亿元，恰好等于既定的货币供给）。同样的推理，假设当前利率为3%，其他条件不变，在此时，公众愿意持有的投机货币是150亿元（大于手中的货币100亿元），人们将卖出债券持有货币而引发债券价格下跌、利率上升，直到利率升到4%为止（此时货币总求增为1100亿元，恰好等于既定的货币供给）.

现在，可以看到那个大笑话了：在利率为6%时公众明明是在花钱，花钱花得利率都跌到4%了，而利率降到4%时公众手里还有100亿元的投机货币。公众花的是谁的钱？怎么花不花的就不见少呢？在利率为3%时（公众此时手中有100亿投机货币）公众明明在卖出债券持有货币，为什么利率升到4%时公众手中还是只有100亿的投机货币？卖债券得到的货币哪儿去了？

至于凯恩斯分析的三种均衡利息率的变动情况（供币供应量的变动、收入水平的变动、投机性货币需求的变动）问题就更多了，多得我实在懒得去批判它。如果朋友们有兴趣，可以自己去批判它一下。

由于凯恩斯的货币供求与利率均衡理论是错误的，在此基础上推导的IS-LM模型自然是错误的。



4、、倒因为果的AD曲线

凯恩斯在推导总量需求曲线AD时，是以货币供给量不变为前提，假设“物价水平变化”，来观察国民收入是如何变化的。很显然，这是一种倒因为果的分析方法。在经济社会中，国民经济的运行是通过商品交换进行的。商品交换则是以货币为媒介，货币的正常流动代表商品交换的正常进行。所以，货币在经济体中的流动是因，全体劳动者创造的国民收入PY（即国民财富）是果。用公式表示就是MV=PY。在正常运行着的经济体中，货币供应量（M）没有变化，货币的流通速度（V）是没有道理发生突变的。这就象是一条在正常的流动着小河，在水量（可比作货币供应量）没有增加的情况下，河水流速（可比作货币流速）怎么会出现加快的情况呢？如此一来，国民收入又怎么会发生突变？物价水平又如何会发生突变？凯恩斯的这个假设是没有任何道理的！

现实情况是：国民收入不变，货币供给量增加则物价水平提高，货币供给量减少则物价水平降低。货币供给量与物价水平是水与船的关系，水涨（货币供给量增加）则船高（物价水平提高）。反过来则不成立——如果说水没涨船却高了，这可是天下最大的怪事了！船是怎么高上去的？这可不是市场那只“看不见的手”能办得。到的，只有依靠“上帝之手”了。

当然了，如果硬要说一下AD曲线的道理，那就是：（对任一条AD曲线而言，）在使用同一货币的不同经济体中，在相同的货币供应量条件下，在不同的物价水平时，对应的国民收入也不同。重新强调一遍，它只能指的是不同的经济体。

至于总量供给曲线AS，就更是胡说八道了。在这里凯恩斯故意把由于增发货币而引发的通货膨胀和成本上涨混为一谈。增发货币而引发的通货膨胀对经济而言是恶性的，因为这样会掠夺公众的财富（如果央行是全民所有的则可通过补贴弱势群体促进社会分配公平化）；成本上涨则是良性的。

下面解释一下为什么说生产成本上涨是良性的：

在一个国家，不同企业之间的劳动生产率（生产力水平）都是不一样的。一般说来，生产率最高的企业的工人工资是最高的，而同行的生产率较低的企业的工资也不会比生产率最高的企业低太多，因为如果差别太大则优秀员工会大量流失造成企业破产。如此一来，生产率较低的企业的生产成本就会比较高。随着一个国家整体生产力水平的提升，所有企业的工人工资都会跟着提高，生产成本也会跟着提高（生产率先提高的企业先涨以吸引人才，生产率落后的企业不得不跟着涨工资）。对于生产型的企业如此，对于提供服务的企业更是如此。比如饭店，社会生产率是否提高对工饭店服务员的工作效率几乎没有什么影响（如端盘子的服务员），可他们的工资依然会跟着整体社会的整体工资水平不断提高，就是这个道理。

这种生产成本上涨是良性的。如果生产率提高了而所有工人的收入没有提高，因生产率提高而多生产出来的商品由谁去消费？生产是需要消费来拉动的。生产持续扩张而消费能力不足会影响经济增长。如果一个国家的劳动生产率不断提高而生产成本始终都没有上涨，倒是说明这个国家有问题了。当然，有人可能会说，成本上升出口会受阻。这倒是正确的——也正是因为这个原因，随着一个国家生产率的提高，出口产品的技术含量才会越来越高。

而凯恩斯又意识的把成本上涨与通货膨胀混为一谈，给狼披上了羊皮，居心何在？通货膨胀是指货币过量发行，而成本上涨是因为工人收入提高。二者绝对不是一回事。

因为AS、AD曲线都是错误的，所以，凯恩斯的宏观经济模型是毫无价值的。至于那些精英们用AS-AD曲线分析出来了的形形色色的通货膨胀理论，全部都是骗人的鬼把戏。

从逻辑性方面来看，凯恩斯的《通论》（即凯恩斯的革命理论）完全可以说是胡编乱造。一套理论编得如此糟糕还能成为正统的理论，确实是大本事。时势造英雄，一点都不假。在此，我也正告中国经济教育界的爱国学者们，到了编一本逻辑上讲得通的经济学教材的时候了。



三、西方经济学的狭隘性



受制于西方经济学分析问题的出发点，即“如何实现个体最优化”，精英们在分析宏观问题时，总是容易犯下“差之毫厘，缪以千里”的错误。下面通过一个被凯恩斯写进了现代西方宏观经济学教科书的案例来看一下西方经济学的狭隘性，这个案例就是“节俭的佯缪”。

勤俭持家，节约储蓄，在任何社会都是个人的美德，但是，按照西方经济精英的说法，对一个社会而言，这种观点往往不成立。他们的理由是：假如一个社会还存在着发展生产的潜在能力，在这场合，假如每家每户都节制消费，产品会因缺乏需求而表现为生产过剩，由此导致社会生产进一步减少和个人收入下降、收入减少，生活水平下降，而且，这一动态过程是累积性的恶性循环，最后会引发经济危机。这个经济分析号称是经过“上世纪30年代的经济危机检验的”。事实果真如此吗？

拿中国经济做例子吧。从1952年到1978年26年间，中国的国民经济平均增长速度是6.5%（当时的世界经济平均增长速度只有3%），这一速度是任何一个国家都无法项背的。这26年的时间，中国在一个连造罐头的马口铁都得靠进口的落后的农业国基础上建立起了一个拥有完整工业体系的强大国家。中国的工业体系之完善，除美俄两国之外，再无第三国可比。不得不强调的是，那时中国绝大多数年份处于被封锁状态，没有外来投资，全靠中国人民苦干实干。当然，我们的收获都是货真价真的：没有通货膨胀，没有内债，没有外债，不卖资源，不恶化环境。但是，在那近三十年的时间内，中国人民吃不好、穿不好，举国上下无比节俭，也正是因为如此，直到1978年，中国的轻工业企业并不发达。如果按照“节俭的佯缪”的观点，近三十年的“恶性循环”下来，中国经济应该空前危机才是，可为什么那时的中国经济没有表现出一丝一毫的“恶化”迹象？是精英们错了还是中国错了？

其实，这个道理很简单，只不过，那些眼里只有“个体最优”的精英们永远都不会懂。还是让我这个只学了十八天宏观经济学的门外汉给他们上上课吧。

的确，生产是靠消费需求来拉动的。如果消费需求萎缩则生产规模也发展不起来。不过，消费需求并不只包括个人消费需求，还包括社会需求（或者称集体需求），比如兴修水兴、改造农田、修桥筑路等等（这都是毛主席给我们打下的好基础呀），社会需求的旺盛同样会拉动生产的高速发展。这才是我们的共和国建国28年来重工业发展迅速、国民经济高速发展的原因。也不怪那些精英们不懂这个道理，他们眼里哪有国家利益、民族大义？只有“私人利益的最大化”。在他们眼里，失业率能降到4%就是奇迹了，他们哪能理解当时的中国零失业是如何实现的！正在因为他们太“理性”，才会有“公地悲剧”：一群牧民在一块公共草场放牧。一个牧民想多养一只羊增加个人收益，虽然他明知草场上羊的数量已经太多了，再增加羊的数目，将使草场的质量下降。牧民将如何取舍？如果每人都从自己私利出发，肯定会选择多养羊获取收益，因为草场退化的代价由大家负担。每一位牧民都如此思考时，“公地悲剧”就上演了－－草场持续退化，直至无法养羊，最终导致所有牧民破产。——这个道理还不简单吗？有便宜不赚王八蛋。在精英们眼里，这居然是合理的！



综合起来，我们可以得出结论， *西方经济学中的微观经济学完全是一套建立在虚幻假设基础上的、没有实用价值的理论，是一套为掩盖资产阶级剥削行为的实质的理论。宏观经济学则是一套淡化资产阶级剥削行为、并帮助大资产阶级掠夺广大百姓利益的理论。* 那些西方经济精英都是在替资本家做辩护，没有一个是为老百姓说话的。所以，当他们从嘴里再吐出不象人话的惊人之论的时候，一律板砖伺候！

*** 简介

：毛主席领导中国，也不过27年；而主流们统治中国,已经30年了.结果主流们成天埋怨毛主席一直影响着中国，人民也总是想念毛主席。一个污染、负担如山、血汗工厂、崇洋媚外的中国，人民怎么可能不想念毛主席?到今年，中国改革开放已经30年了。在这30年里，据说“政策完全正确”，而且也取得了“举世瞩目的伟大成就”。当然可能吾运气不好，成天看到的是污染、负担如山、血汗工厂、崇洋媚外什么的，就是吃点肉也担心有毒或者造假，总之就是感觉不到主流们鼓吹的好处。主流们为了一个奥运会花费了几千个亿，却不肯拿出一点来解决物价、房价问题。请问如何让人民喜欢?当然，吾这样的草民，主流们是不会关心的。主流们关心的是什么呢？主流们成天觉得现在思想不够解放。为什么不够解放？据说是“左的思想”阻碍着。主流们成天攻击左的思想给他们带来极大的困扰，要扫清左的影响.其实这说起来让人觉得主流们非常非常的无能。为什么呢？主流们在台上搞了30年，要权力有权力，要资金有资金，要宣传有宣传。不到20年，在中国已经存在了几亿年的清水，几乎绝迹。这只是他们伟大力量的表现之一而已。凭着这种人的黑心，什么事情做不成？一点左的思想，那还不是太容易对付？可是为什么就对付不了呢?什么是左的思想？其实说白了，就是毛泽东思想。这毛泽东思想在中国，也就几十年吧。如果从1949年开始算，在中国占据思想上的统治地位也就27个年头而已。按照主流们的说法，在这27年里，中国人吃尽了苦头，投奔主流们的怀抱应该是象洪水一样不可阻挡。结果呢？去毛化搞了30年，毛泽东思想的大潮是一浪接一浪，一到什么节日，网上纪念毛主席丰功伟绩的文章排山倒海。这让主流精英们头痛不已，据说他们很不明白得到“改革开放好处”的人民为什么会这样。也就是说，他们不明白，明明30大于27，可是为什么27就是远远大于30呢？而且更加可怕的是，按照这个形势发展下去，这个27恐怕会大于100也是毫无疑问的了。 为什么越来越多的人怀念毛主席呢？是现实逼迫的。同样的，主流其实对自己的罪行清清楚楚，但是骨子里喜欢当洋奴，而且还要通过剥削人民来发财，所以就要愚弄人民。怎么愚弄呢？一方面是把毛主席时代说成一片漆黑，什么没有人性啦、迫害啦、经济要崩溃啦等等，另一方面说自己“政策完全正确”、“取得了举世瞩目的伟大成就”、“生活得到显著改善”——且不说这明显把人民当作猪只要吃好了就睡，就是这吃的肉是什么东西也没有人能够说清楚吧。但是污染、血汗工厂、矿难、贪污腐败、生活负担、卖国求荣、殖民地经济到处都是，人民也看得清清楚楚，这可怎么办？主流们就拿洋老爷，也就是所谓“世界主流文明”来压人民。看看？洋老爷都说话了，尔等贱民还不老实？只是洋老爷也不是吃素的，人家帮洋奴做事了自然要一点回报。而且这胃口越来越大，中国的行业都控制了还不满足呢。这中国人民的苦难，可是没有边了。这样的结果，就是更多的人想起毛主席来。没有办法，毛主席就是穷人的神.其实主流们要人民忘记毛主席，非常容易。把中国的污染治理好，让中国人民没有负担，在国际上谁也不怕，这时去污蔑毛主席，保证人人相信。但是主流们心里也清清楚楚，要想做到这几点，自己相信的“世界主流文明”是绝对不可能的，只有靠着毛泽东思想。最可怕的就是，毛泽东思想不仅不能让他们安心当洋奴，还要禁止他们掠夺人民的财富。既然糊弄不了人民，那就暴力好了。说到这里，就不好深入下去了.主流们铁了心要让27永远大下去，只是苦了中国人民和中华民族。这一笔账，历史一定要清算的。在这里，我要说说的是，争论最多的是左与右的问题。很可能，这是这个论坛与生俱来的特点，争论还一直比较激烈。
　　左与右的争论焦点集中表现在哪里呢？我看主要还是对毛泽东的态度问题。据观察，怀念毛泽东的人，在这里发表了不少文章，摆事实讲道理，讲得很清楚；对毛泽东持反对态度的人，没见发出什么贴子，不知道是什么原因？可是，他们总在贴子后面骂人家是左棍呀，左棍呀什么的，更好笑的是，有人说，怀念毛泽东的人，就是当年的即得利益者，现在混不下去了，所以才戚戚哀哀，或者说怀念毛泽东的人，就是好吃懒做的人.我要回答的正是这个问题，说怀念毛泽东的人，是既得利益者，这我完全承认，因为没有毛泽东，就没有新中国，没有毛泽东，就没有今天的安定日子，所以，既得利益者不仅仅是怀念毛泽东的人，而且是所有的人（包括反对毛泽东的人）是整个中华民族。如果有人认为，毛泽东因为土地改革分了他们的田地、房子，那么，可以理解了，可是，毛泽东没有剥夺你的生存权力。毛泽东只是让社会人人平等：均田地，等贵贱，实行按劳取酬的原则，建设一个新型的国家。有些人如果不承认这一点，他们对毛泽东刻骨仇恨，他的内心世界就昭然若揭了。再一个，说怀念毛泽东的人好吃懒做，这就贻笑大方了，告诉那些人吧，我们这些怀念毛泽东的人，没有一个是好吃懒做的，而且是干了一番事业的人，生活不比那些人差到哪里去。我所了解的怀念毛泽东的人之中，包括本人，也是干了事业的人，做了贡献的人。用好吃懒做的话来贬低对毛泽东有深厚感情的人们，这一点就是唯心主义者的一向判断事物现象的水平，可怜！我所接触的怀念毛泽东的人，他们写纪念文章，可以说，大多数是干部，知识分子，教师，也有拥有千万亿万财产的民营企业家，还有高干。持反对态度的人不知道吧？难道我们怀念毛泽东是因为没有饭吃才写文章的？可以这么说，真正的没饭吃的人根本没有时间来写这些文章的，写这样的文章正是在替那些下岗工人，生活贫困者说公道话，打抱不平。这就是那些以小人之心度我等之腹的人想不到的，也不得其解的，这也是那些僵化的不能再僵化的人判断问题的固有方式！用这种观点思考问题，可笑不可笑自己的去看吧，不必多说.为什么要怀念毛泽东？我想是有很多原因的，一些原因也是不言自明的。可以这么说，我们现在的经济发展了，人民生活水平提高了，怀念毛泽东的人对此根本没有持怀疑态度，只是认为，这个社会，还要回到路不拾遗，夜不闭户的那种状态上去，不是吗？这些年来党和政府的努力难道不是为了这些吗？可是事实怎么样呢？是不理想的，而且很不理想的。为什么？谁都知道，在官场，腐败现象滋生，到了令人发指的地步，庞家珏、段义和之流，做坏事，丑事，达到登峰造极的地步，贪官们说的做的言行不一，难道我们不应该呼唤毛泽东那个时代的干部的好品质好作风吗？贪污腐化给社会带来的负面影响是无法估量的，包括那些反对人们怀念毛泽东的人，也是这个社会的受害者,难道不是吗？如果不是,那么你不是贪官，就与贪官同流合污！社会不安定的因素还有一条，就是黑社会活动猖獗，你有多少安全感？人们怀念毛泽东，就是要增加安全感，争取路不拾遗，夜不闭户的那样一种社会风尚，你们反对这样的理想和愿望，除非你们是黑社会人物。人们为什么怀念毛泽东，就是毛泽东时代消灭了的性病、卖淫嫖娼、吸毒贩毒现象，怀念毛泽东的人不会去吸毒，不会去干伤天害理的事，起码人们是正派，是在呼唤公平，公道，正义，这些人看不到吗？这种正气难道不应该提倡吗？现在，这个社会出现的不正常现象极需人们继续解放思想，开动机器，发动群众，群策群力，解决问题，可是，现在就是出现了那些说别人是左棍，左混的人，他们才是真正的极左，真正的思想僵化，反对别人用脑袋思考问题的新的思想僵化群体！他们与当年四人帮搞的极左如出一辙，他们动辄对人打棍子扣帽子，反对人们反思问题，无疑是饮鸩止渴，自欺欺人！

　　人们怀念毛泽东，总体来说是一种忧患意识，希望国家长治久安，国家兴旺，社会安定，一天比一天好，错在哪里？为什么要受到责难，甚至攻击谩骂？是何居心？的确，毛泽东时代我们还很贫穷，但是，那个时代的优点正是要在新时代给予发扬光大的，这有什么不对吗？新时代创造了更多的财富，而新时代无可避免地出现了一些让人感到困惑的问题，难道人们呼唤现在的党中央认真解决这一问题，提高执政能力，错了吗？毛泽东曾经告诫我们防止和平演变，这是事实证明了的，历朝历代，开国皇帝不是制定了不少规章制度，不是从反腐败开始的吗？最后怎么样？不是以腐败透顶而灭亡的吗？难道提醒这些事，拿毛泽东时代伟大成就说话就有错？本来，左也好，右也好，都生活在中华大家庭，都是一家人，但是就是一些人目光短浅，才不喜欢让别人说这些忠言逆耳的话。事实上，封建社会的更迭，中华民族不就是一损俱损的，陷入灾难吗？过去许多富翁不是没有产生，可是现在他们在哪里呢？一个政权垮台了，更多的人得从头开始，如果一个国家乱成一团糟，有多少人的财富可以幸免？那些感到现在很有钱的人未免想的太天真了吧，不是想着逃到国外吗，那就是甘当二等公民了。我要告诉人们，一些写纪念毛泽东文章的人，这些人是值得尊敬的人，是最纯朴的人，并不是像那些人所说的，写这样文章的人混不下去了，除非你们心中有鬼！毛泽东已经离开我们三十一年了，而去世了三十多年的毛泽东，人们总是对他的怀念不断。在怀念毛泽东的声音一波高过一波之后，人们也在不断地思考着这是为什么。如果细心浏览各类文章和民间百姓评论，就会发现，人们怀念毛泽东，是因为毛泽东对中国人民的无私情怀，无私的奉献，而这种情怀和奉献，无人可以代替.一、人们怀念毛泽东是因为他说得到，做得到，全心全意为了人民立功劳。人们对照毛泽东的一生，就不难发现，他是说得到，做得到的一个人物。在一九四九年以前，他领导人民的目标就是要打倒帝国主义，官僚资本主义，封建主义，并称为“三座大山”，对强于自己多少倍的敌人，毛泽东提倡持久战，并发扬愚公移山的精神，下定决心，不怕牺牲，排除万难，去争取胜利。毛泽东说到做到，他自己付出的艰辛努力还不算，他的家人也为此付出了流血牺牲。所以，一个人干什么事，不三心二意，不说一套做一套，从各方面找不到他言行不一的表现，人们对这样的领袖怎么能不敬佩呢？他给人民带来路不拾遗，夜不闭户的生活环境，与现实的反弹对照，人们怎么能忘记呢?二、人们怀念毛泽东是因为他立场坚定旗帜鲜明，是就是，非就非，不做老好人。我们从毛泽东的一生中可以看出，毛泽东从来就是疾恶如仇的一个人，对待敌人，他从来不让步，对待错误思想，他从来不放松，他的原则立场从来没有动摇过。对待敌人，他说过，一切反动派都是纸老虎，要横扫一切害人虫，全无敌。而对待自己犯错误的同志，毫不客气，进行严肃的批评与帮助，延安整风运动，不是证明了这样的整风给中共的革命胜利奠定了基础吗？往前推推看，古田会议精神，不是毛泽东纠正了军队错误思想，从胜利走向胜利的开始吗？而毛泽东的一生，从来在大是大非面前，是不做好人，不和稀泥的，就是对他的恩师们，也不是给个高官厚禄，打着他的旗号乱发言的。所以，在毛泽东身上，看不到软弱无能这几个字。看不到他是在和谁搞平衡，搞中庸.三、人们怀念毛泽东是因为他善于调查研究，在调查研究中发现问题解决问题。在反映毛泽东的许多纪录片中，都记录了毛泽东这样和历史，他始终如一地深入社会进行调查研究，中华大地上，踏遍了他的足迹，甚至到了八十岁，还计划骑马到黄河上游走一走，他的许多决策并不是在北京开会做的，而是在调查研究的半路上做出来的，在纪录片上，人们看到，工厂、农村、学校、军队、田间，到处都有毛泽东的身影，甚至列车成了他的办公室，在列车上不知道接见了多少中外来宾。毛泽东接触群众，绝对不是做秀，不是跟百姓握一下手，留个镜头，也不是逢年过节端个碗吃个饭，就算深入群众，毛泽东也流过了不少眼泪，可是，眼泪流下之后，发出一定要把淮河治好，一定要消灭血吸虫的动员令。从毛泽东深入群众的镜头中，怎么都看不出他是在做秀.四、人们怀念是因为毛泽东总在为中国人争气，他从不丢中国人的面子。新中国成立以后，是一穷二白的，而毛泽东善于将中国人民建设自己美好家园的智慧、积极性和创造性调动起来，并把防御大国的威胁力量架设起来。当年，帝国主义威胁中国的就是有战略武器，而明明看着中国不具备发展那样武器的条件，不知道为什么，毛泽东领导中国人民鬼使神差地搞出来了两弹一星，有了这些东西，大长了中国人民的志气，大灭了那些妄我之心不死的敌对势力的威风，由此，也成了中国人民在世界上取得应有地位的参照物，中国如果落后，这将会是置疑的理由。因为毛泽东的那股中华民族英雄气的影响，中国人民，所以现在容忍不得谁有半点奴颜媚骨.五、人们怀念毛泽东是因为他热爱百姓，百姓热爱毛泽东。毛泽东和人民心连心，这没有半点娇柔造作，尽管当年没有电视，但毛泽东走到哪里，哪里的百姓就会认出他来，为了安全起见，后来的毛泽东视察，无奈地戴上口罩，但是，千山万水，连着天安门，毛主席是咱社里的人，以及毛主席与各族人民心连心是发自内心的歌唱。虽然毛泽东当年的‘四大’有点冒失，但现在看来，是一种胸怀，是一种伟大的谋略，是一种风度，更是史无前例。没有人敢试试这个创举的。于是人们可以说，一个真正得到人民拥护的领袖，做出什么样的荒唐之举，看起来荒唐，但都是一种伟岸和无可比拟.六、人们怀念毛泽东是因为他的家风，为后人开创了先例。有人曾经把毛泽东比作暴君，恶毒咒骂过他，可是，如果是暴君，如果毛泽东满脑子封建意识，那么他的家风为什么不按照封建王朝的那一套来呢？除了他的地位和工作需要以外，毛泽东的一家人，没有搞过什么特殊。毛泽东的儿子上前线牺牲了，有人说这说那，那么以后还有出现各种情况的可能，我们等着那些将小人之心度君子之腹的人的表现。毛泽东，生前坦坦荡荡，身后，任人评说，没有任何遮遮掩掩，无论是他个人还是他的家人，没有任何事不敢让人评说，这就是中国人民的福气，也是人们不断怀念毛泽东的理由.怀念毛泽东的理由太多了，许是因为当年人们的口味被毛泽东调高了吧？这社会真的找不到对手？当社会上习惯了一种健康向上的风气，习惯了一种伟人的作风，那么人们就是认定了，在中国，壮哉，毛泽东，伟哉，毛泽东！毛泽东逝三十一年，但毛泽东的风骨没有随风而去，没有飘浮不定，总是深深地扎根于人民心中，恐怕是人们随时都可能产生对毛泽东伟大品质怀念的起因。当下，不仅在网上，而且在生活中许多人谈起毛泽东都是那么一份景仰、那么一份留恋.的确，毛泽东是伟大的，毛泽东的伟人魅力也是无穷的，是永远值得人们怀念的。但若细细体味一下，也许就会明白，这种怀念毛泽东其实也有对建国初期二十世纪五六十年代那个时代的怀念。而且，还要明白，在改革开放之初甚至十年前，人们都没有如此的怀念情节，为什么在时间越久远、国家越繁荣之际的今天，出现了如此的返潮现象呢?其实问题不那么简单，这里有其深刻的内涵，这就是两个紧密相贯的问题，一是官员队伍问题，二是贫富分化问题.有那么一些人，当谈到了毛泽东时代的时候，总是这不是，那不足，但不知道干部队伍建设是很成功的。那时候的官员是人民的勤务员，并不像电影小说那样的瞎说八道，他们真的能与群众打成一片，与群众同吃同住是太平常的事了，凡观眼下这些官老爷，下一次乡就是“调研”、就成了报纸头版的大新闻，就成了对群众的莫大恩赐；更主要的是现在的一些官员贪污腐化成群，骄奢淫逸成风，大肆行贿，买官卖官，不顾民生，专捞政绩，现在人民群众要想办件事，不请客、不送礼那是什么都办不成的；还有就是，现在的法纪松驰，远没有毛泽东时代的纪律严明。现在干部队伍中这种情况在毛泽东时代简直是不可想像的.而另一方面，正是“吏治”不严，导致一些地方的官员，独断专行，官商官匪交结，侵吞国家和人民财产暴富，致贫富分化急剧加深。他们还经常养什么二奶三奶，不嫖就赌，腐化堕落，谁管老百姓的死活，这与1949年前蒋匪帮政权有什么区别？毛泽东时代虽“穷”，但贫富差距很小，工农兵唱主角，是主人，那时候一些普通“干部”的收入甚至还低于一般群众。而当今中国，有多少工人农民能走进人民大会堂。有的人是食不裹腹，有的人则是极力奢侈。这在毛泽东时代同样是不可想像的。人，作为一种有思维的社会性物种，渴望公平、公正是一种天性，生活环境的优化并不能消掩人们对公平正义的追求。理解了两个“不可想像”，就不难理解为什么今天怀念毛主席的人们越来越多了.倒过来看，毛泽东热的出现，实是一种警示，警示今天的官员腐败问题和贫富分化问题已到了非常危险的地步！“反腐败事关党和国家生死存亡”，切盼高层能铁腕治官、严厉打击，在腐败如此严峻的形势下，狠狠打击才是第一位的。打出声威，遏住不断蔓延的势头，给民心一个有效的抚慰！人们怀念毛泽东，是因为他时刻想着处在最底层的劳动大众，在他领导下的中国，工人、农民扬眉吐气，劳动大众真正享受到了做“主人”的味道。

人们怀念毛泽东，是因为他严格要求“人民的公仆”，一篇《为人民服务》曾经激荡过多少干部和群众的心。他不时告诫国家工作人员不要做官当老爷，不时清理干部队伍之中的腐败分子，要求各级党政部门、企事业单位的领导同志保持“两个务必”，从而使各级政府真正成为人民的政府，使广大干部真正成为人民的勤务员。

人们怀念毛泽东，是因为他公而忘私的品格与精神，他没有给儿女留下显赫的位置，也没有给儿女留下多少物质财富。相反，他还为革命、为国家献出了自己几位亲人的生命。在他死后，国外既无分文存款，也没有置下半点产业。他的儿女过着普通的平民生活，既没有出国，也没有做什么高官。

当然，毛泽东毕竟不是完人，他也犯过很多错误，特别是在中国经济的发展上，他的某些“左”的作法实际上是阻碍了中国的发展。但这并不能掩藏他作为伟人的光辉，不能抹掉人民对他真诚的怀念。

人民对真正关心过他们的人，总是不会忘记的。 坦率的讲，我是80年出生的，保守的讲我是6岁时开始懂事，也就是86年我开始渐渐的明白这个世界。我所看到的世界是怎样的世界呢？在我很小的时候很少听说这个世界有妓女，可是随着年龄的增长，渐渐开始听说在这个社会上出现了一些新鲜事物——姘头，在我整个成长的每一天里，我都生活在恐慌之中，每一天都能从同学们那里听说在我们这个社会里新出现最新的“有意思的新闻”，而社会上每一条这样的新闻都足以使成年人感到脸红心跳，更何况我们这些小孩子们呢？



　　后来我听到的社会上这样的新闻越来越多，简直日新月异，花样翻新。我有时候也在困惑，我们这个社会到底怎么了？我后来才知道，我们这个社会在86年——96年恰恰是娼妓现象经历了从无到有，从地下到公开的过程。而这个过程恰恰发生在我国改革开放程度越来越深化的时期。而这种现象在毛泽东时代恰恰是没有的。坦率的讲，我没有出生在毛泽东年代，我也没有经历过那个年代，那个年代到底是什么样我也不是十分清楚，但是，在今天我们仍然能够从历史的纪录片中和书藉中窥见那个时代。我们可以在纪录片中看到人们喜气洋洋的从事着集体劳动，劳动是那么苦，然而每个人的脸上都挂满了笑容。而这种现象在我们现在还能看到吗？



　　从我小时候听说某同学为了当班长，在放学后给老师送一篮鸡蛋到高中时某同学为了到年级的重点班读书给校领导送去几万元钱，我能够感受到在我渐渐长大成人的过程中，我们这个社会的腐败程度在逾演逾烈．然而，据我所知：这种现象在毛泽东时代是很少有的。这种现象也是在改革开放逐步深化的时候愈演愈烈的。难道社会上发生的这些变化，只有经历过毛泽东时代的人才能感觉到吗？



　　还记得，在很小的时候，每当过节的时候，亲戚们聚在一起吃饭，（那个时候，大家的公资都差不多，）大人们在桌上吃饭，我们小孩子们在桌下玩耍，很开心，那段和谐的，其乐融融的时光真的很令我难忘。随着我的长大，亲戚们之间的吃穿渐渐的就有好有坏了，三姨家装修得金壁辉煌，他们可以每餐到饭馆去吃，而我们家依旧贫穷。这几年之间，亲属之间的贫富之差就有这么明显，我这个出生在80年代的，没有经历过毛泽东时代的年轻人，难道就感受不到在改革开放的这些年来，人们之间的贫富差距在拉大吗？然而，据我所知，这种现象在毛泽东时代是很少有的。毛泽东把一家6位亲人献身给了中国革命，他老人家在生前却没有给自己的子女们谋个像样的高官当当，就连自己的爱子岸英也牺牲在朝鲜的战场上。哪一个现在的领导能做到呢？毛泽东拥有百万元（有些人说已经过亿元）的稿费，他老人家在生前没有因为自己家里的生活开支过一分钱。尽管有人在报刊上写文章提出非议，但这些钱一直是国家的财富，他的子女们竟然没有继承也没有开销。毛泽东挣着全国的头号工资也不过几百元，也就和现在的一个扫街道的清洁工的收入数差不了多少。就说他富也比全国人民富不了多少。如今呢，有的人钱多的没法花，有的人穷的没钱花。毛泽东的时代，用现在的说法是，法制很不健全。但是人们道不拾遗，夜不闭户，生活相安无事。很少有人犯案，即使偶尔有些地方出现一半个杀人案，也是惊天动地。如今，杀人放火成了家常便饭。老百姓们最爱说的一句说是，毛泽东爱穷人。爱穷人的人民领袖，穷人能不爱他吗？现在的大小官员却喜欢傍富人……

在生活枝节上让百姓们赞不绝口的事儿说不完。越说越能显示出毛泽东的伟大。

在老百姓的心目中，毛泽东之所以伟大，就是他事事为老百姓着想，尽量缩小贫富差别。尽管那时人们的生活并不富裕，甚至很清贫。但是，人们的心里却是踏实的。毛泽东逝世多年了，老百姓们谈及起来，却在不时地念及他带给人民的好处。人们深切怀念毛泽东，甚至在偏远农村的一些农民们，怀着质朴的感情，把他当神敬。 毛泽东去世30年来，资产阶级右翼分子、party内原有的反对派以及国际上的和平演变分子联成一气，向毛泽东和毛泽东思想发动了大规模的、旷日持久的审视，连毛泽东同志身上哪怕是一个微微的缺点都被揭了出来。能享受到这种如此大规模、如此精细精洗的，对于我party来说，绝对是第一人！更奇怪的是，对于其他领导人（不管是健在的，还是己故的），一律不准谈及。有些人主意想尽，甚至加上了造谣诬篾一手，也不起作用，毛泽东是越洗越亮，毛泽东在广大人民群众中的形像越来越高大，这成了现代修正主义分子最大的心病！

为什么毛泽东对中国人民有那么大的影响力？为什么人民群众是那样地诚挚地爱戴着毛泽东？有些右派网友弄不明白，在这里，我给右派网友露个底：

第一，千方百计、无时无刻、无私无畏、完全彻底地为人民谋利益，这是毛泽东得到全中国、全世界劳苦人民衷心爱戴的最根本原因；

毛泽东全心全意想着人民群众，一心一意地维护着人民的利益，这是13亿中国人有口皆碑的事实。

毛泽东一生一世站在人民群众一边。1954年淮河发大水，毛主席一边流着眼泪，一边疾书“一定要把淮河治好”八个大字，并亲自组织了治理淮河的伟大战斗，使近一亿江淮群众走上了幸福的康庄大道！

1`957年毛主席的一个警卫战土回家探亲，归来时带了几个用野菜做的窝窝头，加之路长，天暖，带到北京时已很难进嘴。毛泽东见到这几个窝窝头后热泪纵横，泣不成声。在全体机关干部、警卫人员的会议上，毛泽东义愤填鹰地说：觯放几年了，人民群众还过这样苦难的生活，我们对不起群众。我们要大干快干！于是1958年出现了大跃进！尊敬的右派网友：即使大跃进出现了这样那样的毛病，人民群众会因此而恨毛泽东吗？

第二，举世无双的智慧和能力，超乎常人的人格魅力，是毛泽东得到各阶层人士、甚至是他的敌人不得不叹服的重要原因；

毛泽东是古今中外举世无双的人民领袖，即使是无产阶级，在当今的今天，也没有一人能与他相比！

毛泽东是古今中外第一个不爱财的领导者。毛泽东有数千万元稿费，可是他交给party组织管。大儿子毛岸英结婚，他只办了一桌酒席，请了亲家母张文秋，以及刘少奇夫妇，周恩来夫妇，朱老总夫妇等；李敏李纳出嫁，毛泽东也是各办一桌酒，陪嫁的只是三四百本书而己。古今中外，有哪个统治者、领导者不为个人的私利苦心经营，惟独只有毛泽东除外！

毛泽东的领导艺术堪称古今中外举世一绝的最高艺术品。红军长征中的皿渡赤之战，让蒋介石浑头转向；红军长征蒋介石调动一二百万大军围追只有数万之众的红军，并以失败而告终。小日本侵华，蒋介石想借日本人消灭GCD，毛泽东只将GCD的“反蒋抗日”政策中的“反”字改为“联”字，竟奇迹般的发生了西安事变，发生了张学良、杨虎成、傅作义、冯玉祥、张治中等国民party高层人物的积极抗战，并最终形成了由GCD领导的抗日民族统一战线，在打败了小日本的同时为中华人民共和国的诞生提供了100万人民武装、200万民兵武装、八大块革命根据地的坚实基础、是毛泽东指挥100万人民解放军只用四年时间就消灭了由美帝国主义武装到牙齿的800万国民觉反动军队，建立了中华人民共和国。建国后，毛泽东又指挥中国人民，取得了抗美援朝、抗法援越、抗美援越、对印自卫作战的伟大胜利，并迅速还清了苏联的债务，并取得了两弹一星的胜利！这一件件伟大的历史功勋，哪一件不让有良心的中国人崇敬乃至崇拜？谈起功劳，个个向自已脸上贴金，可是哪一项重大决策不是毛泽东提出并拍板？成绩个个有份，出了问题，个个把头缩起来了，光打毛泽东的板子，思闻、疯和尚之所以不得人心，右派为什么不得人心，原因就在于此！

第三，由一些心怀叵恻的阴谋家的胡作非为造成的社会矛盾的加剧，剥削行为的加剧，两极分化的加剧，生存压力的加剧，使广大中、下层人民大众更加怀念毛泽东；

事实表明，大凡人民群众真正生活在和谐的幸福生活中的时候，人们倒真能慢慢地忘却幸福之源。但一旦社会矛盾、生存压力加剧的时候，人们自然而然地就会想念毛津东对人们的思情。社会矛盾越多，思念的人越多，人们对毛泽东的感情就越深！


富翁、老板、有权有钱有势者搂着小姐漫漫起舞的时候，这些人会怀念毛泽东吗？———他们根本不会！

拿着外国人的俸禄，或拿着富翁老板们的钱财为他们摇旗呐喊的那些士大夫们，他们会怀念毛泽东吗？——不会，他们根本不会！

但是：

广大失业工人、下岗工人，当他们生活痛苦无着时，他们会恨谁、怀念谁？

广大农民，特别是农民工，当他们以每天工作十多个小时、负出沉重的工作、每月工资不过千元、有时还拿不到手的肘时候，——他们会恨谁、怀念谁？

当广大农民、普通工人、社会人员有病无钱看，有学无钱上，或被拦

在医院外、学校外的时候，——他们会恨谁、怀念谁？

近千万应往届大学毕业生找不到工作，报不了父母恩，还不了求学欠下的债、四处碰壁的时候，——他们会恨谁、怀念谁？我这人平常喜欢在网上转悠，由于网络论坛是目前管制最宽松的舆论平台，也由于网络论坛最大限度体现了言论的平等性和自由性，我对观察论坛中的言论走向尤其感兴趣。

　　在百度毛泽东吧看到一位网友比较毛泽东吧和邓小平吧帖子数量的文章，感觉很有意思。我来这里时间不长，也只是很偶然才知道百度居然也有论坛之类的设置。但几天匆匆浏览下来，也大体能够感受到在这里毛泽东被关注的程度之高。其中提及毛泽东经常是各大时事BBS的头号热门话题，其间当然是各色杂陈，争论之激烈、涉及范围之广阔颇令人有叹为观止之感。但无论反对或赞成，一个事实已经不容否认：在今天讨论国事，毛泽东经常是一个无法绕过的巨大问题。对百度贴吧的观察再次印证了我的看法，同时由于百度的特殊性质，这里表现出的各种现象更有代表性，也更耐人寻味。

　　简单的统计表明，毛泽东吧的帖子数量大约是邓小平吧的十到十五倍，无论主帖或跟帖，比例大体如此。远期的差距还有可能进一步拉大，因为毛泽东吧的帖子增长速度远远超过邓小平吧。我也对天下论坛毛泽东与邓小平献花的数量以及言论作过关注。

　　如何解释这种现象？有人将其归因于所谓个人崇拜，但熟悉个人崇拜发生机制的人肯定不会很认真看待这种看似合理的解释。对待逝去的人，个人崇拜是没有意义的，个人崇拜背后是明确的政治需要，更需要现实权力的积极推动。如果有人要推动个人崇拜，那么，最优选择是崇拜目前当权的主流派，次优选择是崇拜一个对当前政治秩序有利的历史人物。显然，毛泽东不符合这两个基本条件：既不是当权者，推崇毛泽东也不符合当前秩序下很多当权派的利益。所以，我可以肯定地指出：数据的差异更多说明的是民意的去向。

　　为什么关注毛泽东吧的人要远远超过关注邓小平吧的人数，这本身就是一个耐人寻味的问题。一个是共和国和共和国的执政党——共产党的创始人，一个现在却被小心翼翼隐藏起来，不敢容许社会深入讨论的人，但也是今天社会下层民众和正义力量寻求民族前途和社会公正的政治符号；另一个是所谓改革开放的设计师，一个至今仍然被官方在邓小平理论的旗号下大肆宣传，却在民间日益引起质疑、逐步走向毁誉参半的人。如果说有人在推动个人崇拜的话，目前崇拜的对象也只能是后者，全力开动的宣传机器、歌功颂德的研讨会、子女们所谓回忆录的大量出版都证明确实有人很希望人们来崇拜邓小平。但很不幸，人民显然没有兴趣去崇拜这个被希望崇拜的人，反而是那个被拼命隐藏的人一次又一次成为人民在追问自身命运过程中最终可以诉求的精神导师，成为人民向二茬罪的制造者挑战的最有力的政治符号和政治资源。这还不能说明问题吗？

　　百度贴吧与很多网络论坛大有不同，由于百度作为中文最大搜索引擎的突出公共性质，我们有理由相信这里聚集了更加大量、更加广泛因而在社会学采样方面更具代表性的人群，这个人群包罗万象，一般论坛上常见的单一观念持有者扎堆、从而使论坛成为一言堂的现象不太可能在这里出现。扎堆现象到处存在，由于参与者的类型相对单一，凯迪变成了右派和反民族主义者的大本营，铁血变成了左派的扬声器，强国论坛则呈现出左派和民族主义者的压倒性优势。以这种论坛作为观察网络民意的样本多少有些不准确，不符合社会学取样寻求广泛性和一般性的原则。但在百度，由于参与者的广泛和形形色色，其间的观念和价值倾向就完全可以被相信代表着更广泛的社会呼声，有关的统计数据就像百度搜索引擎的使用量的统计数据一样有说服力，因而在社会学的意义上更有研究价值。统计数据告诉我们，在百度，对毛泽东的关注度决定性超越了对邓小平的关注度，参与其间的相当广泛的人群对毛泽东充满兴趣，他们在怀念和关注毛泽东。由于正在发生的关于毛泽东的讨论总是与今天的社会问题紧密相关，我们也有理由相信对毛泽东的关注不仅仅是对一位历史伟人的关注，而是人们在试图藉由毛泽东的管道来解答一系列的现实问题。

　　关注现实是当今网络世界中毛泽东热的基本特征，这就将第二次的毛泽东热与上世纪九十年代初第一次明显具有怀旧色彩的毛泽东热区隔开来，构成一个在关于中国当代社会的考察中非常值得注意的现象。

　　我个人认为：这不仅表明人们对毛泽东作为中华民族独一无二的历史伟人的兴趣，更说明当前社会正在发生的一切与毛泽东一生为之奋斗的事业正在再一次发生关键性的交合。

　　人们是在面对一个怎样的中国当代社会呢？虽然官方一直在掩饰，但任何一个理性的观察者都不得不承认，这个我们不得不在其中生活的社会正在复活一些曾经被毛泽东时代的社会价值抛弃的东西——那些注定只能被称作人类社会最恶劣产物的东西：巨大的社会贫富差距、严重的官僚体系腐败、权钱交易、疯狂的社会公共财产侵夺、日益堕落的社会价值体系、下层民众利益的无可保障、黄赌毒的泛滥成灾、三农问题、严重的城市失业问题、人民相对的和绝对的贫困化、教育对贫民子弟的拒绝、全面消失的社会福利和难产的社会保障体系。这些在毛泽东时代曾付出巨大历史代价加以消除的垃圾竟又一次堂而皇之地成为我们这个社会最具指标性的特征。毛泽东和他那一代仁人志士终其一生、为之殚精竭虑、悬首浴血而后初步建立的社会公平体系竟然被当作破烂丢掉。在所谓“效率”的冠冕堂皇的理由下，我们重新走向了资本主义，走向了所有资本主义形态中最糟糕的那一个——权贵资本主义，至此，权力与金钱的无耻而疯狂的勾结成为一切社会问题的事实制造者。

　　目睹这一切，人们怎能不思念毛泽东，怎能不思念毛泽东曾经带给中国人的那个虽然暂时还未摆脱贫穷，但却有着足够的社会公义和健康心灵，生机勃勃而前途无量的社会。今天的我们比毛泽东时代的我们富有一些，但我们中的大多数人却为此付出了不能承受的代价：工人和农民永远丧失了国家主人公的荣耀，重新沦为资本家和大官们颐指气使的奴隶；我们“提前透支二百年的资源消耗换来的只是眼前的繁荣假象”；我们的社会在价值体系方面已经彻底沦丧，金钱和权力崇拜横溢神州，我们这个曾经骄傲的民族终于再次在世界民族之林中无颜抬头，面对来自西方的真诚的亦或不真诚的道义谴责，却只能小声地、怨妇般地、了无意义地为自己辩解；我们丢失了一个独立自主的工业体系，不能生产早在几十年前的毛泽东时代就能够生产的很多东西，而这一切居然仅仅因为我们“伟大的”新自由主义经济学家们灌输给我们的 “造飞机不如买飞机，买飞机不如租飞机”的西方经济学的混账逻辑；面对西方，我们不再有自豪感，虽然除了槬璺之流最无耻者之外没有人愿意公开承认，但在内心认为“西方的月亮比中国的圆”的还是大有人在，他们本能地接受了中国人相对西方人在人种方面的恶劣性；我们不再能拒绝跨国公司的无理要求，内外企统一税收已经是对外国公司的优惠，不多征他们税就已经很好了，而他们却要求维持那个歧视民族企业的对跨国公司实行税收优惠的税收制度，并演出了一出55大跨国公司联合逼宫的闹剧，而我们的政府居然无法拒绝这种蛮不讲理、贪得无厌的要求。在付出如此多的代价之后，我们彻底失去了毛泽东所创立的那个堂堂皇皇的伟大中国，只得到了“用八亿件衬衫换回一架空中客车”这样一个在全球化资本体系中尴尬的下游苦力角色。

　　在毛泽东被遗忘的岁月，我们曾经欢呼乌托邦的破灭，我们以为自己打破了一个在虚幻中徘徊的宿命，我们在一个梦里沉睡了很久。现在我们试图从梦里醒来，睁开惺忪的双眼，却蓦然发现，我们付出如许代价，却只换回了一个不再有雄心壮志、不再有深远战略的不断沉沦的前途未卜的中国，这就是我们想要的吗？

　　我一直在想：如果给毛泽东足够的时间，我们是不是可以生活得更幸福，我们是不是可以拥有一个远比现在所拥有的更完美的社会？我不想再在财富增殖方面与一帮反毛者纠缠，历史不能假设，所以从历史学角度也很难设想毛泽东的领导是否会带给今天的我们更多的钱财。我更愿意诉求于信仰——基于坚实的现实基础之上的信仰，从这个信仰出发，我还是相信：如果我们能够沿毛泽东指引的道路继续走下去，甚或作为后人，我们能够拥有超越毛泽东、站到毛泽东肩头的智慧，那么，我们至少可以拥有一个健全得多的社会，我们也可以比毛泽东去世的时候更加富有，生活更富足，但不需要付出那么多难以接受的代价。这是一个信仰问题，但毛泽东时代打下的坚实工业基础、公平的社会体系和人们曾经拥有的贫困却不缺乏幸福感的生活使我确信我的信仰的正确。当然，如果你是西方经济学的信徒，信奉新自由主义的胡说，相信张维迎、厉以宁之流学术骗子和人民财产的隐形杀手的谎言，你就不会有此信仰。

　　为什么人们关注毛泽东，因为人类历史上在解决社会公平、维护下层人民利益方面还没有人比毛泽东做得更好，因为只有毛泽东才能最好的回答我们正在面临的问题，因为只有毛泽东才真的关心人民，相信人民，关心和相信首先由劳苦大众构成的、而不是用脑满肠肥的资本家和贪得无厌的官僚充填的偷换概念的所谓人民。

　　我敢和所有人打一个赌，未来的时间里，伴随前期积累的社会问题的恶果逐步显现，人们还会更加怀念毛泽东，对毛泽东道路的诉求只会更加强烈，而不会有丝毫减弱。虽然我对胡温新政充满期待，但这些问题的解决绝非一日之功，而且由于已经形成的剥夺人民利益的共同体势力庞大，事实上掌握了大多数的社会资源，新政仍然有夭折的可能。保险起见，我宁愿做悲观的设想。我相信，仅仅作局部的改良，指望给中国带来一个相对温和和公正的资本主义是不现实的，因为资本主义注定有一个残酷的早期资本积累阶段，这个阶段通常会持续一、二百年，难道要让我们的人民再忍受一、二百年的苦难？谁来说服他们？谁能说服他们？

　　令人欣慰的是，今天的领导人似乎正在对这种思路说不，从胡温执政以来对三农问题、城市贫困问题的一系列重大举措来看，我们有理由认为：胡温新政是在向毛泽东的道路重新回归，他们不必重复毛泽东的具体办法，但毛泽东以人民为价值依归的事业轨迹却是不容背离的，否则，我们很可能在不久的将来面临一场新的革命，一场巨大的社会崩溃的灾难。

对于毛泽东同志个人及他领导的那个时代的评价，人们主要经历了盲目崇拜——否定——理性反思——逐步认可四个阶段。而推动理性反思和逐步认可的动力，主要是因为现实社会空前激烈的社会矛盾，我们下面主要针对很多人对毛泽东同志及他领导的那个时代的批判，以及与现实的对比来展开。

有的人说毛泽东同志领导时代饿死几千万，犹其是针对经济建设方面，认为毫无成就。我对比了一下自解放以来中国历年的人口统计数量（联合国教科文卫组织统计），特别是在三年严重自然灾害（1960——1962年）人口数量，总量减少也不过几百万，而且还包括自然死亡或自然灾害导致人口出生率下降的因素，所以饿死几千万这纯粹是胡说，而且我也有从这个时代过来的老人为证，这种不顾历史的可耻的诬蔑行径，是注定要被人识破的。此外，也有人攻击他当政期间一事无成，只顾拼政治，抓阶级斗争，而经济建设毫无成就，认为现在的成就全是改革开放的成就。这同样是一种幼稚的观点，众所周知：解放前中国几乎没有任何重工业，而且很多设备都运到台湾，正是在这种一穷二白的程度上，我们的国民经济迅速得到发展，而且取得的成绩是举世公认的。如果没有毛泽东时代打下重工业的基础，哪有我们今天改革开放的建设成就？这种割裂历史的观点看问题，反映其幼稚和无知的历史观。

有的人批判毛泽东同志迫害死了几百万人。任何一场革命，对于自己的阶级敌人，都会采用暴力的方式，不这样，能巩固革命的胜利成果吗？而且如果不打倒这些地主恶霸，反革命分子和土匪，我们的人民能得到属于他们自己的土地吗？他们就是分得了土地，这些地主恶霸、土匪还有反革命分子能让他们安安静静地生活吗？如果没有分得土地，我们的人民能有今天的生活？说这些话的人无非是要为死去的僵尸鸣冤，无非还在怀念他们以往的寄良他人的生活，无非还想企图夺回早已属于人民的财产……而且如果不将这些打倒，那么中国将会有更多的人死在那些过寄生生活的人手中。看看解放前国贫极弱的中国，没有尊严，只是任人宰割的羔羊，如果没有毛泽东同志领导的中国革命，中国有属于自己的未来吗？况且当时镇压的土匪、地主、反革命分子还有干部（包括含冤的），何以会达到几百万人？真搞不懂说这些话的人，清不清楚几百万这个概念？

当然，我们也毫不避讳毛泽东同志所犯的错误，这也是大多数网友共同表达的一个意思。对于“大跃进”、“文化大革命”，作为领导人的毛泽东同志犯有不可推卸的领导责任，但如果将所有的错误一股脑全推给他，难道你们不觉得有失公理吗？更有甚者，有的人还将当前的社会不公现象推给一个业已作古的老人，有的人将对现实的极为不满的情绪发泄到对老人有失公允的评价，甚至对老人进行极度污蔑，这种病态的人格的人在网上通常指鹿为马，颠倒是非，有的人竟可笑到将毫无关系的外蒙古独立以及中日钓鱼岛争端扣在毛泽东头上……当然，所有这些病态的人毕竟是少数，多数人已经学会理性地分析看待事物，既看到好的一面，也看到其错误的地方。而且毛泽东同志获得了他的对手（西方专家）的认可，可以想象，能够获得自己对手认可的人，这应该是一个多么高尚无私的人呀！我想作为任何一个没有偏见的人，也会公正地看待毛泽东同志对中国的贡献的。

对于今天为什么有越来越多的人怀念毛泽东同志及他领导的那个时代？我个人认为主要源于人们对当前贪污腐败现象严重，官员道德品质低下，两极分化极其严重密不可分，人们更多的怀念那个时代公平的社会氛围，以身作则的公仆形象和为人民服务的政府机构，当然更多也是表达对现实的不满。而且正是这种怀念，再加上对过去的反思，促进人们理性地对过去的认识，还原了历史的真相，并以那个时代为镜子，来拷量现实的干部和经济建设，同时也推动了人们认知水平和社会的进步。 经常在农村听到人们这样讲，还是毛主席好，就算挨饿心里也舒坦！可能是真正了解挨饿滋味的人不多了，人们才这样说，但是人们从心里还是久久地怀念毛泽东的那一个时代。在城里，我很少能与市民交往，但是有一次我乘车去济南，在长途汽车上与一位胖胖的女人坐在一起，那女人应该是个贵妇，珠光宝气，而且香水味可以熏死一头牛，我只好用报纸遮住捏着鼻子的手。汽车发动了，汽车电视开始放映一个叫做《赤裸特工》的片子。那贵妇人忽然对片子大发感慨了，如果毛主席就不会有这种事了，现在可是什么社会！我并不认为她对片子的评价有多么的“独到”，但是她对毛主席的念念不忘却让我深有感触。我作为一名大学生，在校园里也经常可以看到同学们对毛主席的敬仰，每次谈起社会，都会有人大谈毛主席怎么怎么样，虽然并不见得他们对毛泽东本人和他的时代了解有多少。“毛主席 ”我们依然习惯这样的称呼，这就足以说明，他在我们心中有着什么样的影响！

我对于毛泽东同志也没有太多的研究，只看过他的几本传记和五卷本的《毛泽东选集》以及背诵过几篇他的诗词，此外就是一些无法考证的传说了。因此，对于毛泽东，我似乎无权发言，而且我没有直接感受过他的时代，似乎也无权指指点点，在这里我也不想做那些理性的分析，把他老人家当作一门学问来研究，我只凭感情，说说我的看法以及我周围的平凡的人们对他的评价，是否遗笑大方我到不在乎，“毛主席”这三个字好像不仅仅代表着他个人，好像包含着更深的东西。

一、 个人的魅力

对于毛泽东，我想任何一个人都是很难超越的，众所周知，毛泽东不仅是一位革命家、政治家、军事家、理论家，他还是一位学问家、诗人、书法家等等。伟人是不可多得的，秦皇汉武、唐宗宋主，加上成吉思汗，再加上康熙，恐怕中国五千年的历史，也就出了这么几个顶天立地的人。而在其中真正得到民心的，恐怕也只有毛泽东，李世民也享有盛誉，但是毕竟他离老百姓要远的多，最近流行的“康熙大帝”不过也是虚夸出来的幌子，在人们心中他只不过是个皇帝。而毛泽东却是一个领袖，不仅是一个社会领域的领袖，而且还是一个精神领域的领袖，或许直到现在，人们头脑中最根深蒂固的还是他的思想。

在毛泽东身上，人们的感触其实不是一个“神”，因为没有任何一个人看到过神，感触过神，受到过神的恩惠，而毛泽东却实实在在地在人民身边，为人民服务，与人民同甘共苦，直到现在，我们的老师一提到毛主席，依然很感动地说，那时候，毛主席也吃黑窝窝头，真的！还记得一位农民开玩笑地说，小时候我们最大的愿望就是过上毛主席的生活——夜里可以吃长果（花生）。可见，毛泽东在人们心中留下的最大的印象恰恰是一个人，一个与人们一起吃苦的人，而不是一个神。恰恰是现在的一些干部，好像神一样，吃着山珍海味，住着琼楼玉宇，而且高高在上，见上一面，比登天还难。谁是神？人们的心要比学者的论文更有权威！

正是这样，毛泽东才活在人们心中，让老百姓久久无法忘却，因为他圆过人们心中的梦！

二、他的思想与实践同步

毛泽东的思想从来都是都是与实践相结合的，无论是在抗日年代、解放时代，建国时代，建设时代，毛泽东似乎就没有说过空话，他的语言、他的思想永远都是与实践紧紧相结合的。不拿群众一针一线就是不拿群众一针一线，为人民服务就是为人民服务，无论是抗战、土改、建国……都做得实实在在，为什么现在的人都怀念那时候的诚信，讲诚信，首先应该是政府的诚信，无论是制度、法律、政策、既然说到就应该做到，如果只是给老百姓开空头支票，给老百姓一个美丽的梦，老百姓还会信任吗？还会诚信吗？现在的老百姓早就被骗怕了，早已没有了相应号召的激情，就算是确确实实的对他们有好处，他们一般也是冷眼看待。别说是农民了，就算是大学生，也被骗怕了，所以什么也不放在心上，禁止校外租房，给贫困大学生每日4元的生活费，可见的有一个大学生响应?再想一想当年为什么要“砸？

说到做到，就算是无意之间出了大错，也比那些不切实际的空谈要好。老百姓眼里不揉沙子，贯彻执行只是下级政府的报告，只是报纸上的空谈。百年以后，再回首的时候，或许在人们心中还是一个毛泽东！

三、一个大国的形象，更有民族性

在目前的人们谈起来，好像大国的形象还是在毛泽东的抗美援朝和周恩来在联合国的沙进杀出，每当中国又在国际上出了什么事，人们还是不无感慨地回想当时的中国！

是的，现在的综合国力上去了，国家有地位了，但是却越来越软弱了。“肉食者鄙”！或许美好的生活和财富容易成为累赘。对美国人们或许还可以谅解，但是对日本我们没有理由不如韩国。中国的人们没有韩国的人们团结，其实，是中国的政府不如韩国的政府强硬。我的一个同学在去年下半年去西安，看到了学生游行，却被警察们拦住了。还记得以前的九·一八，许多的同学自发集合纪念，学校却不允许，今年也就没有了生息，不知鲁迅先生是否又写了“友邦惊诧”？

还有台湾，国内的事，就被这样牵制着，没有了结的的日期。毛泽东真的不应该把这个任务留给后人啊！在他时代，中国人民才真正地显示了自己的力量，才是一头雄狮，而现在不过是一头披着狮皮的羊！哪里有大国的形象，哪里有民族性？

四、毛泽东时代的社会

毛泽东时代的社会只有贫穷，其实没有更多的社会弊病。只有毛泽东让人们变得朴实，真诚，在那个社会里，没有偷窃，没有坑蒙拐骗，没有嫖娼、卖淫和吸毒，没有贪污腐败成风，没有流氓横行，没有文化的堕落……而这一切，却又死灰复燃，你幸福吗？虽然口袋里有几个叮当响的钱。浮躁、自杀、空虚、堕落并不是脱离社会而存在的！在毛泽东的时代，至少可以安安静静地死！

我不能否认现在社会的富足，也不能否认现在社会所取得的成就，不过在人们怀念毛泽东的现象里，我们可以不费力地想到这些，相信，给人们财富的人，人们不会忘记，而给人们精神的人，人们更会把他记在心里。我们不可能平白无故地造神，也不会盲目地造神了，但是如果再有一个人物像毛主席一样，能改变现在的社会精神状态，我们宁愿再一次造神！
毛泽东时代就算有千种不足，但是其干部队伍建设还是很成功的。那时候的官员真能与群众打成一片，与群众同吃同住是太平常的事了，而现在干部下一次乡就是“调研”、就成了头版关条了不得的大新闻、就是对群众的莫大恩赐；更主要的是现在的一些官员贪污腐化成群，骄奢淫逸成风，不顾民生，专捞政绩；还有就是，现在的法纪松驰，远没有毛泽东时代的纪律严明。现在干部队伍中这种情况在毛泽东时代都是不可想像的。 斯大林悼列宁有一句这样的话“共产党人具有特种气质，是特殊材料制成的”。这句话有道理。我把这句话用在毛泽东身上最恰当了，因为毛泽东就是真正的共产党人，但又回过头来想，这句话也经不起推敲，他也是血肉之躯啊，根本不是什么特殊材料制成的。一个血肉之躯的人肯定会有过失的，所以有文革的错误，那又为什么时隔30年人们总惦记他呢？

　　是奇人有怪相吗？或许是，因为他有颗特别的痣，可是我们社会很多人有这样的痣，怎么也说不通啊！

　　是不是他举止不同呢？也不是，50年代，炮打金门，蒋介石一身戎装，也毛泽东却赤裸着坐在海边，他喜欢赤裸，连江青都有意见，这是大家都知道的，就连吃辣椒，红烧肉也是跟平民没有两样。我想这也不是惦记他的原因。

　　是不是他书读多呢？的确他书读的不少，读透24史，这在中国的文人里是无法比拟的，他走到哪里书读到哪里，我想这也不是理由，至少说陈独秀王明书也读的不少，再说他也没有上过显赫的名校，也没有留洋，就是一个师范生。有人说他是天才。林彪喜欢捧，毛泽东不是否定了他提的天才论吗？

　　是军事才能高吗？也许是，在战争年代，他以小米加步枪战胜了美帝，国民党的飞机加大炮，从百十人马开始，发展出几百万人的解放军，最终夺取政权。这一点不管是上层，中层，下层，中国人外国人都不能否认。这是人们想他的理由吗？我认为不是，至少说不全是。蒋介石军事才能就不高吗？如果按照有人那样把蒋介石的军事才能说的一文不值，那么用什么说明毛泽东的军事才能呢？所以这是不符合事实的。为什么没有人惦记蒋介石呢？

　　说了这么多，我想来想去都不是根本原因，根本原因就是“为人民服务”这五个字，不管是战争年代，还是和平年代,他虽然有高超军事才能，再怎样博览群书再怎样智慧都好，毛泽东战胜困难最根本原因就是懂得依靠人民，所以蒋介石不在话下，王明不在话下，既然是依靠人民取得胜利，就要感恩，毛泽东就是懂得感恩，感恩也是中国人民最朴素的感情.

　　毛泽东就是懂得感恩,所以“为人民服务”就是他的座右铭。正因为他胸中装着全体人民，所以才有艰苦的生活作风，严于律己，高瞻远瞩，三年自然灾害，他带头省吃减用，与民同甘共苦，对待子女更是严格，当朝鲜战争传来毛岸英不幸的噩耗，他就说了一句“谁叫他是毛泽东的儿子”。这就是一个特殊材料制成的人，把全体人民看成自己的亲人，他也是一个血肉之躯的人，把自己的亲人看成是人民中的一员。爱有多深就有多深。胸怀就是这么的宽。所以人民怎么不惦记呢？

　　人们不能忘记他，也是跟腐败分子有关，大家想想，我们有句俗语，不怕不识货，只怕货比货。同样人也是比出来的，一比就知道高尚与藐小，同样共产党人，有的人在人民的眼前喜欢耍威，“老子是公安局长，我怕谁啊”，“怎么没有人接待啊，我有事我先走了”，“你是群众你算老几啊”，“我后面有人擎着，我怕你啊”，这样的话充斥在社会的角落里，人民会怎样想啊。有了权就有钱，互相追逐，儿子先考虑，百姓放一边。如果是这样背离人民，我想我们是不是已经丢了“感恩”了，如果是这样人民会更想念伟人毛泽东。

　　伟人毛泽东固然要想，我想惦记他更关键就是要学好毛泽东思想，他的思想精髓就是为人民服务，时时坚持为人民服务，为人民服务跟我们现在中央领导集体的提出的执政为民理念是一致的。我想我们不但要学，更关键的是以自己的实际行动践行共产党人的义务和责任，这样才不会让我们白白惦记他一番。

　　
　　而另一方面，正是“吏治”不严，导致一些地方的官员，独断专行，官商官匪交结，侵吞国家和人民财产暴富，致贫富分化急剧加深。毛时代虽“穷”，但贫富间距很小，一些“干部”的收入甚至还低于一般群众。而当今中国，有的人是食不裹腹，有的人则是极力奢侈。这在毛泽东时代也是不可想像。
　　
　　人，作为一种有思维的社会性物种，渴望公平、公正是一种天性，生活环境的优化并不能消掩人们对公平正义的追求。理解了两个“不可想像”，就不难理解为什么今天会出现“恋毛”热了！
　　
　　而反过来看，“恋毛”热的出现，实是一种警示，警示今天的官员腐败问题和贫富分化问题已到了很危险的地步！“反腐败事关党和国家生死存亡”，切盼高层能铁腕治官、严厉打击，在腐败如斯严峻的形势下，打击才是第一位的。打出声威，遏住不断蔓延的势头，给民心一个有效的抚慰！

同时，毛泽东时代是中国近现代史上中国人民最扬眉吐气的时代，是中国人民最为自豪的时代，那时，我们建国后第二年就与世界头号强国美国为首的22国联合国军出国作战，弱小的中国竟然打赢了！接着，就是炮击金门，西藏平叛，对印自卫反击战，对苏自卫反击战，对越南海作战，爆炸了原子弹，氢弹 发射了卫星 建立了完整的军事 经济工业基础等等，而自毛之后，能令中国人扬眉吐气的事又有多少呢？军事上 政治上 外交上又有多少令中国人民不快的事发生呢？怎么能让中国人民不怀念毛主席！！！！

*** 现将中国普通百姓对毛泽东的评价整理如下：



　　毛泽东把一个支离破碎的、半封建、半殖民地的旧中国改革为一个新兴的、基本统一的、人民当家做主的人民共和国。

　　所以，从政治上讲：毛泽东是中国历史上一位伟大的改革家。

　　毛泽东指挥一支长征后不到三万人的军队，转战南北，通过“辽沈”、“平津”、“淮海”三大战，彻底打败了蒋介石领导的八百万军队。现在仍然是美军西点军校教科书的《论持久战》和《抗日游击战争的战略问题》就是毛泽东军事理论的代表著作。

　　所以，从军事上讲：毛泽东是中国历史上一位伟大的军事家。

　　毛泽东一生坚持自己的理念：“为人民服务”。至古帝王为自己，顶多为了江山社稷。毛泽东却始终高举“为人民”的大旗，这是任何一个帝王所望尘莫及的。

　　所以，从民心上讲：毛泽东是中国绝大多数低层民众的“大救星”。

　　毛泽东一生廉洁。两袖清风，廉洁勤政。作为最高领导人能够艰苦朴素过一生，最奢侈的食物也就是一碗“红烧肉”。痛恨贪官污吏，亲自批出尚方宝剑，痛斩高级贪官张子善和刘青山。而且要求自己的子女和后代廉洁奉公。

　　所以，从廉洁上讲：毛泽东是中国最廉洁的领袖人物。

　　毛泽东一身正气。敢于对苏、美两霸说“不”！敢于捍卫民族利益和国家利益。敢于勒紧裤带，顶住苏美“外科手术”式打击的威胁，搞出了“两弹一星”，让后人在毛泽东撑起的“核保护伞”下过太平日子。

　　所以，从胆略上讲：毛泽东是中国最有骨气的领导人。



　　毛泽东重视人民的疾苦。明确指示医院：“不能为金钱服务、不能为特权服务。必须救死扶伤，实行革命的人道主义”。在缺衣少药的年代，坚持“送医送药下乡”；穷则思变的在农村创立了“赤脚医生”；咬牙坚持国家补贴搞公费医疗和合作医疗，解决广大群众治病难的疾苦；真抓实干的在全国彻底消灭了性病、消灭了麻风病、消灭了血吸虫病。

　　所以，从医学上讲：毛泽东真是华佗在世。

　　毛泽东重视教育。明确指示学校：“教育必须为工农兵服务，必须与生产劳动相结合，必须培养德智体全面发展的学生”。在国民经济十分困难的情况下，坚持“义务教学”。在毛泽东时代，小学学费为1.5元/学期(还包括课本费)。大学全免学费，而且师范、石油、铁路、航空、邮电等大学还给大学生发工资。这样的免费教育体系在今天已经成为千古绝唱。

　　所以，从教育上讲：毛泽东是比孔夫子更伟大的教育家。

毛泽东重视国民经济发展和改善人民生活。为了维护国家的主权和尊严，毛泽东时代的中国既有“帝国主义封锁”，也有“修正主义”压迫。在这种特殊环境下，毛泽东坚持发展经济，亲自写下了指导国民经济发展的《论十大关系》，把一穷二白的旧中国，一举改造成为一个“既无内债、又无外债”逐步走向繁荣的新中国。毛泽东甚至对农民的种地也亲自提出了著名的“土、肥、水、种、密、保、管、工”八字方针。即使在文革动乱期间，毛泽东都一再向全国发出“抓革命、促生产、促工作、促战备”的最高指示重视发展经济。

　　所以，从经济上讲：毛泽东是务实的经济学家。

　　毛泽东历来重视民主和支持民主。早年参加了著名的“五四运动”等民主运动，在党内坚持“民主集中制”的原则。坚持“从群众中来，到群众中去；要相信群众、要依靠群众”的民主作风。在文学艺术领域坚持“百花齐放、百家争鸣”。在社会上坚持“让人说话，天不会垮；不让人说话，天总有迟早要垮”。坚持 “大鸣、大放、大辩论、大字报”的民主作风。

　　所以，从民主上讲：毛泽东是中国历史上最重视民主运动的领导人。

　　毛泽东重视外交战线和改革开放。对待苏联的无理要求，毛泽东敢于说不。毛泽东在关键时刻，利用著名的“乒乓外交”，打开了中美合作的大门。创立了“第三世界”的理论，成为第三世界崇拜的领袖，很多第三世界领导人来华访问因为毛泽东晚年健康原因没有获得毛泽东接见，走的时候还哭鼻子。第三世界国家用轿子把中国抬进了联合国，驱逐了台湾代表，恢复了中国安理会成员的资格，种下了一棵为子孙后代遮风档雨的外交大树。

　　所以，从外交上讲：毛泽东是高明的外交家。
毛泽东高度重视国家的统一和主权的完整。毛泽东坚持在少数民族地区开展“民族自治”，同时有果敢的维护国家统一。面对西藏叛乱果断命令解放军进藏平叛；面对印度对中国的领土入侵，果断的开展了中印边境反击战；即使面对陈兵百万，拥有数万辆坦克，数千架飞机的苏联强大军事压力面前，就是一个小小的珍宝盗也不轻易放弃。毛泽东说：“宁肯再次上山打游击，也不放弃一寸土地”。他既明确发出了“我们一定要解放台湾！”的时代最强音，也在晚年向蒋介石伸出了和平统一的橄榄枝。

　　所以，从民族利益上讲：毛泽东不愧为民族之魂。

　　毛泽东博学多才。既是伟大的诗人（代表作有气势磅礴和文才飞扬的《沁圆春。雪》和《毛泽东诗词集》）；又是一位伟大的思想家（代表作有《毛泽东选集》五卷和红宝书《毛主席语录》）；还是一为伟大的军事战略家（代表作有《论持久战》和《抗日游击战争的战略问题》等军事著作）；更是一位伟大的哲学家（代表作有《矛盾论》和《实践论》等哲学著作）。

　　所以，从才华上讲：毛泽东集“文学家、思想家、军事家、哲学家”为一身的多才领袖。

　　毛泽东说过：“金无足赤，人无完人”。毛泽东是一位伟人，但也是一位凡人。他也犯有缺点和错误。但是，毛泽东晚年所犯的错误是当时历史环境和客观条件所造成的。如果没有“帝国主义封锁”，如果没有“修正主义压迫”，如果没有中国存在“资本主义复辟”的危险，如果不担心“工农群众再吃二道苦”，如果没有“林彪集团和四人帮集团”的干扰和破坏，毛泽东晚年就可能少犯错误甚至不犯错误。

　　当年，文革中毛泽东连发几道“要文斗、不要武斗”和 “抓革命、促生产、促工作、促战备”的最高指示，有几个人听了？如同现在中央三令五声要重视煤炭安全生产，但下面的官员和矿主同样“阳奉阴违”明拖暗抗一样。所以，今天的人们要站在历史的角度，用辨证的观点，客观地和全面的看待毛泽东晚年的错误和评价毛泽东。几十年过去了，人民群众更进一步认识了毛泽东的伟大，更加怀念一代伟人。

　　所以，从历史上讲：毛泽东是功绩远大于错误。

　　毛泽东南征北战创建了人民当家做主的中华人民共和国；毛泽东把毕生精力奉贤给了自己的祖国和他所热爱的人民；毛泽东一心想着“为人民服务”；毛泽东两袖清风一身正气。毛泽东远比彼得大帝和华盛顿更伟大。

　　毛泽东是中华民族引以自豪的英雄！

　　毛泽东是光照千秋万代的民族之魂！
