# -*- org -*-

# Time-stamp: <2011-09-14 20:39:37 Wednesday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent

#+TITLE: 如何看毛泽东时代

#+AUTHOR:黎 阳

** 准战争年代

所谓“毛泽东时代”，是指从新中国成立的1949年到毛泽东逝世的1976年这27年。

这27年是个“准战争年代”——从头至尾不是打仗就是准备打仗。主要包括：

（一）不流血的大战

1、冷战（1945～1990）——贯穿整个毛泽东时代（1949～1976）。

2、反封锁、禁运、颠覆、包围的“超限战”——贯穿整个毛泽东时代（1949～1976）。

*** 流血的小战（局部战争）

1、反台湾国民党军队对大陆沿海的封锁破坏（1949～），其高峰时段为1949～1955，比较著名的有：

——舟山群岛之战（1949.8～1950.5）：打掉台湾国民党军队封锁长江口、上海、江浙沿海的基地

——万山群岛之战（1950.5～1950.8）：打掉台湾国民党军队封锁珠江口、广州、广东沿海的基地

——上海保卫战（1950）：制止台湾国民党空军轰炸上?

——海南岛之战（1950）：制止海南岛变成第二个台湾，奠定中国收复南海诸岛基础。

——东山岛之战（1953）：反击台湾国民党军队进攻东山岛

——东海海战（1954）：争夺东海制海权

——一江山岛之战（1955）：占领一江山岛和大陈岛，打掉台湾国民党军队在浙江沿海的最后一个基地——大陆沿海地区制空权争夺战（1949～）

——炮击金门（1958）

——挫败台湾国民党军队大规模反攻大陆的图谋（1962）

——反台湾国民党军队特工登陆骚扰（1962～1963）

——“八·六”海战与崇武以东海战（1965）

2、抗美援朝（1950～1953）

3、国内剿匪（1949～1962）

4、西藏平叛（1959）

5、中印边界保卫战（1959，1962）

6、中缅边界勘界作战（1960）

7、援越抗美（1960～1975）

8、中苏边界冲突（1969）

9、西沙之战（1974）

10、对美国和台湾国民党空军的反侦察、反袭扰作战（1949～1972）

整个毛泽东时代就是在这样“流血的大战不打、不流血的大战不断、流血的小战（局部战争）接二连三、一切按最坏的情况做准备”的准战争气氛、准战争环境中过来的。评论毛泽东时代，就不能脱离“准战争年代”这个历史实际。
   

** 用民族利益衡量一切

评价历史，看的是结果。评价历史人物，看的是对民族利益的贡献。只有坚持“民族利益超越意识形态、超越个人恩怨，超越个人好恶，超越个人私利”的原则，才能做到如实公正客观，达到全民族的最大共识。否则一切评论只不过是少数人谋求私利的鼓噪喧嚣和广告表演而已。

评价毛泽东时代，关键是看毛泽东时代开始时中国是什么状况，毛泽东逝世时中国又是什么状况。评价毛泽东，关键是看毛泽东时代开始时中华民族最根本的根本利益是什么，毛泽东逝世时这些根本利益实现得如何。

毛泽东时代发生了那么多流血的和不流血的战争，发生过那么多那么天翻地覆的变革，所有这一切是对是错，是功是过，同样只能用中华民族最根本的民族利益为标准来衡量才能弄清。


** 冷战时期中华民族最根本的民族利益

整个毛泽东时代都处在“冷战”期间。要评论毛泽东时代决不能脱离“冷战”这个大前提，一切都必须从“冷战”这个基本现实出发。

“冷战”导致世界分为“两大阵营”。现实迫使世界各主要国家必须作出自己的判断和选择，二者必择其一。《大国的兴衰》作者保罗•肯尼迪说：“一个国家不站在美国领导的阵营内，便站在苏联领导的阵营内，不存在中间道路。在斯大林和齐•麦卡锡时代，那种走中间道路的想法是很不明智的。”

中国尤其如此。中国的地理位置及其1945年的虚弱状况使中国对冷战既无法逃避又无法免受其害。

冷战甚至还没有正式开始，中国就已经成了冷战的牺牲品。1945年雅尔塔会议上，中国的主权被美国作为交易的筹码让给了苏联。而苏联坚持要得到这些权益（确保外蒙古从中国分裂出去、占有旅大基地和中长铁路）归根到底是出于冷战的需要。1945年冷战开始时的中国，是百年积弱又饱受八年战火蹂躏的中国，是满目疮痍、遍体鳞伤、国弱民贫的中国，是对美苏两强中的任何一个均毫无抵抗能力、“人为刀俎，我为鱼肉”、任其宰割的中国。作为弱者，夹在美苏冷战夹缝中的中国无论怎样都要倒霉：你向美国“一边倒”，苏联要收拾你。你向苏联“一边倒”，美国要收拾你。你谁也不向，两家一块收拾你：一家扯住你的一部分使劲往自己那边拽，直到把你扯成两半，一家分一半，分裂中国——我得不到的，你也休想得到，至少得不到个全的（设想一下两只狼撕抢一只羊的情景）。显然，这对中华民族的根本利益是最大的威胁。冷战期间中华民族最根本最头号的民族利益就是避免这种命运。这就必须彻底改变中国民族利益遭受美苏冷战主宰的命运，不当美苏冷战的牺牲品。

但只要冷战还没有结束，只要中国还不够强大，中国就无法抵御美苏的主宰，就无法避免成为冷战牺牲品的命运。这就发生了一个“先有鸡还是先有蛋”的难题：中国不强大，就不能摆脱当冷战牺牲品的命运；不摆脱当冷战牺牲品的命运，中国就不能强大。

由此可见，衡量冷战期间一切中国领导人历史功过的唯一标准，就是看其是否解开了这个死结，是否粉碎了美苏为自己的冷战需要而牺牲中国民族利益的一切举措，是否让中国从美苏两大阵营的左右夹击中突出了重围。一句话，是否使中国摆脱了冷战。做到了这条的就是捍卫了中华民族最根本民族利益的英雄，就应该肯定。否则就是中华民族的罪人，就应该否定。其他一切都是废话。

** 毛泽东时代的序幕

——中国避免了第二个、第三个“外蒙古”


蒋介石选择了向美国“一边倒”。在他看来只要傍上美国，一切问题都迎刃而解：美国强，美国富，美国反共。世界上没人敢惹美国。傍上美国金票大大的，实惠多多的，有美国撑腰苏联就不敢乱说乱动，自己就可以放手消灭共产党，就不用担心东北、西北出问题。

实际呢？

据《蒋经国自述》，斯大林当面明确告诉蒋经国苏联为什么一定要把外蒙古从中国分裂出去：“倘使有一个军事力量，从外蒙古向苏联进攻，西伯利亚铁路一被切断，俄国就完了。”“日本和中国都没有力量占领外蒙古来打俄国；但是，不能说就没有第三个力量出来这样做。”

蒋经国问这“第三个力量”是不是美国，斯大林回答说：“当然！”

斯大林更特别警告蒋经国：“不能让美国有一个兵到中国来。只要美国有一个兵到中国来，东北问题就很难解决了。”

斯大林的这番话充分说明苏联的战略图谋和夹在美苏两大国之间的中国在冷战中的处境。

中国与苏联有世界上最漫长的边境线。苏联面对中国的部分正是苏联最地广人稀、力量最薄弱、最无险可守的“柔软的腹部”。如果有“军事强国”从这个方向进攻苏联，就可能把苏联横着切开，“大卸八块”。斯大林对蒋经国说的“西伯利亚铁路一被切断，俄国就完了”并非杞人忧天。“军事强国”即便不进攻，只要沿着中苏边界驻军与苏联对峙，就足以产生足够的威慑，让苏联日夜精神紧张，防不胜防，不知道要部署多少兵力才敢放心。苏联向来把来自这个战略方向的军事威胁视为心腹之患，从不敢掉以轻心。1941年夏秋苏联在苏德战场那么吃紧，明斯克战役损兵41万，斯摩棱斯克战役损兵76万，基辅战役损兵70万，维亚兹马战役损兵66万，一线部队几乎打光了，预备队供不上了，莫斯科都快门户洞开了，苏联仍然不敢动用西伯利亚的驻军。直到获得佐尔格的确切情报、得知日本将“南进”而不“北进”、不会威胁西伯利亚时，斯大林才敢把西伯利亚驻军西调，在“最后一分钟”赶到前线守住了莫斯科。要知道，苏联早在1939年的哈勒欣河战役中就已经把日本最精锐的关东军打了个落花流水，已经知道日军的综合战斗力比苏军差得不是一星半点，对苏联的威胁跟德军没法比。即便如此，苏联对这个战略方向仍不敢掉以轻心，仍千方百计保持重兵。可见确保中苏边界的安全在苏联的战略思想中占有何等重要的地位。既然苏联视这个方向为战略要害，视这个方向上的军事威胁为心腹之患，那么苏联为对付这种威胁自然会不惜一切，决不会有任何顾忌，受任何束缚。

蒋介石显然没听出斯大林的弦外之音：如果中国向美国“一边倒”，苏联就要把中国的东北、西北变成第二个、第三个“外蒙古”——“不能让美国有一个兵到中国来。只要美国有一个兵到中国来，东北问题就很难解决了。”

其实仔细推敲一下斯大林的话的内在逻辑就不难看出苏联的战略意图：“西伯利亚铁路一被切断，俄国就完了”——如果要靠“缓冲国”这种办法来确保西伯利亚铁路不被切断，光一个外蒙古够用吗？从中国的东北、西北不照样可以“切断西伯利亚铁路”吗？既然确保西伯利亚铁路不被切断对苏联那么重要，那对苏联而言合乎逻辑的结论就是把中国的东北和西北变成第二个、第三个“外蒙古”——对此苏联毫无顾忌：战略利益的考量永远超越意识形态，超越个人恩怨，超越个人好恶，超越个人利益。

苏联的这种战略意图自沙俄时代就已经形成了。1902年10月，沙皇尼古拉二世在他主持召开的御前会议上说：满洲将来必须并入俄国，至少要成为完全依附俄国的属国。这就是史称"=黄俄罗斯计划="的核心内容。由此又产生了“中国边界不过在长城”之类论调。虽然日俄战争妨碍了沙俄实现这个战略，但从沙俄到苏联都一直没有放弃把中国的东北、正北和西北这“三北”都变成“缓冲国”的战略设想——所以有了外蒙古独立，所以有了苏联在抗日战争期间对“满洲国”的承认，以换取日本对外蒙古的承认（第二次世界大战中的反法西斯大国里只有苏联承认了“满洲国”）。新疆也曾差一点“独立”出去。也就是说，正当中国为民族生存跟日本浴血奋战的时候，苏联几乎实现了把中国的“三北”全部从中国分裂出去的战略意图。所有这一切都出于苏联极端重视确保西伯利亚安全、防范来自中国方面的任何可能的军事威胁这一战略总目标的需要。雅尔塔协议使苏联有权在中国的旅大驻军，控制了连通中苏边界和旅顺的铁路。凭这两条，加上苏联二战后巨大的国际政治威望，苏联有能力在东北培植亲苏分裂势力，制造第二个“外蒙古独立”。1945年苏联在新疆的影响势力同样不可小视，要制造第三个“外蒙古独立”也并非不可能。

如果苏联真这么干，以中国1945年的国力无论如何也阻止不了。那么向美国“一边倒”能阻止得了吗？

白日做梦。当日本制造“满洲国”的时候，美国向日本宣战了吗？美国能在雅尔塔会议上把中国的外蒙古当筹码送给苏联，同意苏军占领旅大，本身就说明美国对中国的主权和领土完整不当回事，更不用说为此牺牲自己的士兵跟苏联开战了。

不管中国如何向美国“一边倒”，美国的战略重点始终是欧洲，中国总是排在后面。二次大战中只要欧洲战场一吃紧，美国总是把给中国的物资扣下转运欧洲方向。解放战争三大战役时正赶上“柏林危机”，美国全力以赴保欧洲方向，对蒋介石的支持力度与此根本没法比。

不管中国如何向美国“一边倒”，美国顶多保你的政权而不保你的主权，更不会为了保你的主权而牺牲自己。——美国从来只在中国内战的问题上跟蒋介石站在一起。但碰上中国主权问题时，比如外蒙古，“满洲国”、麦克马洪线，钓鱼岛，西沙南沙等等，美国何曾为蒋介石“两肋插刀”过？

“冷战”其实就是美苏两家又要打仗又怕死，自己不上阵，雇别人去卖命。也就是说，让别人为自己的利益送死，而非相反。指望美国保卫你的主权，就等于要求美国为别人的主权而牺牲自己——这是美国打“冷战”的本意吗？这不是本末倒置吗？

更广义一点讲，国家关系再好不过如此。即便结盟，那也只管政权不管主权。除非蓄意挑起战争，否则决不会因为“友好国家”的主权如边界领土纠纷之类而卷入战争。

比如，不管是美国还是苏联，不管跟印度关系有多好，肯为克什米尔这样的主权和领土争端为印度向巴基斯坦宣战吗？中国能为克什米尔归属问题为巴基斯坦向印度宣战吗？

苏联把中国向美国“一边倒”视为“致命的威胁”，对此将毫不犹豫地利用自己的地理优势、政治影响和压倒的军事实力建立第二个、第三个“外蒙古”以应对，决不在乎因此而肢解中国。美国把中国向苏联“一边倒”视为“严重的威胁”但不是“致命的威胁”，对此宁愿封锁围堵禁运而不愿直接对华用兵。历史已经证明，美国对中国的分裂并不在意，只要自己能分得一杯羹。也就是说，处在1945年美苏冷战夹缝中的中国向苏联“一边倒”固然没好果子吃，向美国“一边倒”则只能落得个国家被肢解的下场。这就是当年的现实。

而蒋介石的账却不这样算。他觉得自己跟苏联做成的那笔交易已经解决了一切：“在苏联尊重东北的主权、领土完整，不干涉新疆的内部事务，不援助中共等三个条件下，允许外蒙古独立”。——用外蒙古换得东北和新疆，再加上苏联保证不援助中共——这就去掉了“蒋委员长”最大的心病：美国已经宣布不跟中国共产党合作，只跟他合作。现在连苏联这个世界头号共产党也同意跟他合作而不支持中共，那中国境内就没有任何力量能妨碍他消灭中共了。他的政权就坐稳了。牺牲主权保政权，这笔买卖划得来——只是为了显得不那么丢人，在宋子文、王世杰1945年8月14日签署的《中苏友好同盟条约》中走了个“公民投票”的过场：“鉴于外蒙古人民一再表示其独立愿望，中国政府同意，将在日本战败后举行公民投票以确定外蒙的独立。”

1945年10月20日，外蒙古当局一手操办了“公民投票”。国民党政府派内政部常务次长雷法章前往“观察”（不折不扣“叫人卖了，还帮着数票子”）。

“公民投票”结果：外蒙古独立。

*1946年1月5日，中国的国民党政府正式承认外蒙古的独立。*

显然，蒋介石做这笔交易时最优先的考量不是民族利益，而是意识形态——反共，是个人私利，是个人好恶，是个人恩怨，是有形的、眼前的好处——不折不扣“浙江奸商”兼股票交易所“上海小开”的投机本色：聪明不英明，精明不高明，见小利忘大义，顾眼前不顾长远，只知算小账，不知算大账。

蒋介石只顾打自己的如意算盘，却把历史的教训、苏联的战略意图和斯大林的弦外之音等等一股脑扔到了九霄云外。人家早有言在先：“只要美国有一个兵到中国来，东北问题就很难解决了。”——你既然坚持向美国“一边倒”，还能指望苏联信守承诺？何况条约规定的是苏联“不援助中共”，并没有规定苏联有义务帮蒋介石“取缔中共”、“禁止中共进入东北”，更没有规定苏联不得另起炉灶、就地取材培植当地亲苏势力。蒋介石在国内一贯翻云覆雨，纵横捭阖，把别人都玩弄于股掌之上，而跟超级大国打起交道来却如此无能。说他“外战外行、内战内行”真是一点不假。看来他的聪明劲只用在“保政权”上，不用在“保主权”上。

今天的中国人很难想象1945年冷战刚开始时中国的处境是何等险恶危急：蒋介石向美国“一边倒”，立刻将古老孱弱的中国置于美苏两大超级大国冷战的“交叉火力”之下：美国将不费吹灰之力在中国取得最能威慑苏联要害的战略要地，苏联将不惜一切凶狠反击，利用苏联二次世界大战后如日中天的威望，利用苏联在东北驻军的优势，培植、支持亲苏势力，把中国东北变成第二个“外蒙古”；在新疆如法炮制，制造出第三个“外蒙古”；美苏为避免直接军事冲突，将再来一次“雅尔塔协议”，划分出各自在中国的“势力范围”，让中国变成第二个朝鲜、第二个德国。中国的“三北”（东北、正北、西北）俱失，民族利益将遭到毁灭性伤害，从此被分割肢解，绑在美苏冷战的战车上永世不得翻身……更有甚者，千里长堤一旦决了口，崩溃就难避免了；外来势力操纵下的国土分裂一旦开了头，尔后的进展就殊难预料了。在那种情况下，谁敢担保中国不会被分裂分裂再分裂，变成又一个奥匈帝国，又一个阿拉伯世界，又一个南斯拉夫，又一次“春秋战国”，又一次“五胡十六国”？谁敢说届时中国老百姓的日子会比今日贝鲁特、伊拉克、阿富汗的老百姓的日子更好过？

中国之所以避免了这种不堪设想的命运，原因只有一个：毛泽东。是毛泽东领导的中国共产党在1945年的历史关键时刻眼明手快地抓住了稍纵即逝的历史机遇，扭转了历史进程。

不仅蒋介石和美国的如意算盘里没有中国共产党人的位置，苏联也一样。遵义会议确立了毛泽东在中国共产党的领导地位，结束了王明等“百分之百”听从苏联指挥的“百分之百的布尔什维克”的瞎指挥。此后苏联与中共的关系便冷淡而微妙。1944年6月，斯大林在与美国驻苏大使哈里曼的谈话中公开说中共不是真正的共产党，而是“人造黄油”式的共产党（意即“代用品”、“冒牌货”）。抗日战争时苏联给中国的一切援助都只给蒋介石，不给中共。苏联在与蒋介石签订的《中苏友好同盟条约》中明确承诺不支援中共，同意将中国东北交国民党人接收。这一切事先跟中共连个招呼都不打，倒是打电报要毛泽东去重庆谈判，甚至还提出要中共学法国共产党，交出武装去做官。

如果当时中共一切乖乖听苏联的，那中国的命运可想而知：毛泽东被缠在重庆没完没了地扯皮，整个中共的中心都放在等待与国民党讨价还价的结果上而无所作为。蒋介石在美国支持下从容不迫调兵遣将对付中共。苏联趁美蒋与中共斗得不可开交之际从容不迫在东北扶植“百分之百”听命于苏联的亲苏势力。（前苏联将军、1945～1946年奉天[沈阳]警备司令А•И•科夫通－斯坦克维奇将军在回忆录中说：“1946年3月9日，我们接到撤出奉天的命令，要把所有权力在3月11日前移交给中国人。这个命令使我们有些感到意外。要知道，在3月5日，抵达奉天的Р•Я•马利诺夫斯基元帅在与我的谈话中，叫我好好安排一下，因为我将在奉天长期驻守。而3月9日，我们就突然接到紧急撤离奉天的命令，警备司令部全体人员撤往哈尔滨。”——注意这句话：“我将在奉天长期驻守”——可见苏军原来的确打算要在东北长期待下去。）如果当真如此，那等美蒋把中共收拾得差不多了，苏联在东北制造第二个“外蒙古”的条件也成熟得差不多了：苏联并没有违约支援中共，只是趁美蒋忙着对付中共的时候做了一点“群众工作”而已——第二次世界大战后东欧国家的政权不都有类似的经历吗？

然而美蒋苏三家的如意算盘全被毛泽东打了个稀烂。毛泽东来了个“针锋相对”：“打的只管打，谈的只管谈”，“人民的武装，一枝枪、一粒子弹，都要保存，不能交出去”。不管苏联态度如何，毛泽东自有主张：争分夺秒，见缝插针，大举进军东北，战略上抢到了先机—— *1945年8月8日苏联对日宣战，8月11日朱德即下令进军东北；8月28日毛泽东赴重庆谈判，8月30日第一支中共武装即抵达东北，抓住了苏联最高层对中共如此迅速进入东北毫无思想准备、来不及下达明确指示而导致苏军中下层官兵自行其是的机会，于8月31日占领山海关，9月5日进驻沈阳—* —这一下就使美蒋苏三方把中共排除在东北之外“就地解决”的战略计划完全破产，各方马上全乱了套，各种猜忌、矛盾立刻激化，形势顿时改观：蒋介石认定苏联违约支持中共抢占东北，于是不顾一切请美军直接出动。美军也什么都顾不得了，于中共军队进驻沈阳后不到两周的1945年9月13日在青岛登陆，紧接着于9月30日在天津登陆，10月1日在秦皇岛登陆。美军同时大规模为国民党军队运送军队，亲自出马打通、抢修通往东北的交通线。美国大兵步步紧逼，美苏间“苏军不入关，美国不登陆”的默契随之破灭。苏联立刻直接感受到了蒋介石向美国“一边倒”带来的威胁，迫不及待急于反击。但“远水不解近渴”，于是苏联不得不放弃原先“利用中共拖住美蒋、在东北‘就地取材’培植亲苏势力、把东北变成第二个外蒙古”的念头，对“不请自来”的中共从排斥转为默认——苏联最高层对中共的态度在美军登陆前后大不相同，根本原因就在于此。

毛泽东一箭双雕：明抗美蒋，暗拒苏联——利用美苏矛盾，逼苏联不得不改弦更张，这就不动声色堵死了苏联在东北培植“第二个外蒙古”力量的机会。毛泽东就这样未雨绸缪，连打带消，不知不觉间便一举消除了严重威胁中华民族民族利益的这一大隐患。

苏联对中共之所以不得不改弦更张，是因为美军突然登陆。美军之所以突然登陆，是因为蒋介石为争夺东北迫不及待。蒋介石之所以迫不及待，是因为毛泽东的军队抢先进了东北。毛泽东的军队之所以能抢先进入东北，是因为毛泽东的军队与东北近在咫尺，而蒋介石的部队全远在西南。毛泽东的军队之所以与东北近在咫尺，是因为毛泽东领导中共坚持敌后抗战，在华北、山东、内蒙建立了敌后抗日根据地。中共能建立并坚持敌后抗日根据地，是因为中共的作战目标是长期抗战，是消耗敌人，打的是人民战争，没有外援也能坚持下去。蒋介石的军队之所以全远在西南，一是蒋介石的部队在敌后呆不下去，二是因为蒋介石的作战目标是打通对外交通线第一。打通对外交通线，是为了取得美援——说到底作战目标是捞钱第一。结果：进入东北时中共军队近水楼台，蒋介石军队望尘莫及，不得不求美国直接插手，引起美苏间的一连串连锁反应，让毛泽东抓住了历史的机遇。

毛泽东之所以能抓住这历史机遇，除了眼疾手快、当机立断之外更多的是靠了无数先前做的扎扎实实的基础性工作：建党、建军、人民战争、持久战、独立自主、自力更生、敌后抗日根据地……一切默默耕耘在此时此地都得到了回报。许多看起来似乎杂乱无章互不相干的东西，实际却是环环相扣、因果关系严密的统一体。——毛泽东能抓住这历史机遇看似偶然，实际包含着必然。没有基础，抓不住机遇。要抓机遇，先打好基础。

今天为台湾而焦虑的中国人能想象到1945年的中国差一点就丢掉东北和新疆吗？能想象得出失去了外蒙古之外还要失去东北、新疆、国土被美苏两强分别驻军占领、甚至走向四分五裂的中国会是个什么样吗？对没有发生的事虽然难有切肤之痛，但只要知道这种情况差一点就发生这个事实本身就够令人震惊的了。而这一切之所以没有发生，全亏了毛泽东在刻不容缓的千钧一发之际当机立断巧妙利用了美蒋苏的矛盾扭转了乾坤，又历经三年的血战才使中国避免了这一命运。国民党总是一口咬定自己失败是因为毛泽东的中共得到了苏联的支持，这纯粹是失败者为掩饰自己的无能而编造出来的拙劣借口。苏联瞒着毛泽东跟蒋介石做了交易，一点风声都不漏，明摆着要给毛泽东一个措手不及。而后又是逼毛泽东赴重庆谈判又是让毛泽东交出武装，说苏联支持蒋介石还差不多。对苏联来说这场战争最理想的结果不是中共统一中国，而是国共划江而治，再来一次“南北朝”——这样既能防止美军出现在中苏边境又能防止将来中国强大起来威胁苏联。如果中共真是靠苏联支持才能打赢，那苏联只要在中共打到长江边时切断对中共的供应就行了。实际呢？苏联只能“劝说”，听不听全在中共。这足以证明苏联控制不了中共，毛泽东保持了完全的独立自主。把解放战争说成“国共内战”不正确。这实际是一场毛泽东领导的中国人抗击美苏两强肢解中国的民族解放战争，是毛泽东领导中国人抵抗把中国当冷战牺牲品的第一仗。

这场战争的胜利者并不仅仅是毛泽东和中国共产党，而是中华民族，是中华民族的根本民族利益。毛泽东时代先声夺人，还没开始就已经先消除了一场不亚于“九·一八事变”的民族危机，为捍卫中华民族的根本利益作出了无可估量的贡献。

** 特殊条件下的特殊斗争方式

——“一边倒”

在毛泽东时代开始的1949年，中国是什么状况？

——百年积弱的农业古国，军阀混战、八年抗战蹂躏之余又经历了一场明为国共内战、实为抗击美苏冷战肢解中国的民族解放战争，实实在在已经国穷民贫、遍体鳞伤、满目疮痍。

——西北、西南、东南战事正酣。国内尚有大量土匪、残敌在大肆破坏捣乱。

——农业产值占国民经济的80%。农业靠天吃饭，靠人力畜力，靠铁锨木犁，靠一家一户的小农经济，生产力低下而不稳定，天公稍不作美就闹灾，全国年年都有地区不是旱就是涝。

——工业残破不全，不成体系，重工业不值一提。全国大部分地区在工业、交通、通讯等方面实际处于原始状态。一切关键都得靠进口：设备靠进口，原材料靠进口，石油靠进口，武器靠进口，汽车飞机靠进口，橡胶靠进口，医药靠进口……连造罐头的马口铁都得靠进口。

——仅有的黄金外汇全被蒋介石运走了。能创汇的只有为数不多的农副产品、土特产、原料矿产。有限的欧美海外市场大都掌握在当时亲蒋亲台的人的手里。“来料加工”、“劳务输出”等创汇方式更无从谈起。文盲占总人口77%、被赫鲁晓夫形容为“一堆肉”的中国，要资本没资本，要技术没技术，要外汇没外汇，要海外市场没海外市场，有的只是国民党留下的天文数字般的通货膨胀——老百姓上街买菜得用麻袋装钞票。

——西方国家和蒋介石对中国大陆的封锁禁运已经开始。《美国1949年出口管制法》规定：“那些有助于增强共产党国家的经济和军事潜力而有损于美国国家安全的出口都予以拒绝”。1949年11月22日，“对共产党国家出口管制统筹委员会”（“巴黎统筹委员会”）成立。新中国刚一成立便遭到美国的“对华贸易管制”，禁止向中国输送包括军火、钢铁、车船在内的战略物资。

1949年的中国，地面是共产党的，天空和海洋是国民党的。国民党空军随时随地肆意轰炸大陆城市，北京上海也不例外——1949年5月4日国民党空军轰炸了北京。上海自1949年5月27日解放到1950年2月，先后遭到国民党空军26次空袭。刚进北京时毛泽东为什么不住中南海而住香山？——防空。开国大典为什么定在下午三时而不是后来惯例的上午十时？——防空。

1949年6月23日，国民党海军永字号炮舰在天津口外炮击英属埃及货轮，由此开始实施持续长达六年的对大陆港口的全面封锁。从1949年到1955年，先后有十六个国家的二百多艘商船遭到国民党海军海盗式的拦截。（谁“闭关锁国”？谁“封闭半封闭”？谁“拒绝对外开放”？）

1949年的中国尽管已经极度虚弱，但仍然不得不在美苏冷战的夹缝中立即作出明确选择：向美国“一边倒”，向苏联“一边倒”，还是不偏不向？

1949年的中国尚未解决前面所述的“先有鸡还是先有蛋”的难题——中国不强大，就不能摆脱当冷战牺牲品的命运；不摆脱当冷战牺牲品的命运，中国就不能强大。因此，1949年夹在冷战夹缝中的中国无论怎样都免不了要付代价：向美国“一边倒”，苏联要收拾你。向苏联“一边倒”，美国要收拾你。谁也不向，两家一块收拾你。

毛泽东的选择是：向苏联“一边倒”。理由很简单：这是当时条件下唯一行得通的最符合中华民族最大民族利益的选择。

向美国“一边倒”绝对行不通：这是当第二个蒋介石，而且结果绝不会比蒋介石更好：苏联为了确保中国方向的战略安全是不惜一切的，包括意识形态关系。斯大林已经怀疑中国是又一个“南斯拉夫”——也就是说，只要中国向美国“一边倒”，苏联马上就会撕破脸皮，象对待南斯拉夫那样公开把中共当敌人对待。而美国即便有援助，也决不会比援蒋更积极——想想美国对共产党的态度和蒋介石在美国庞大的“院外援华集团”游说力量就够了。实际当时美国与其说试探着和中共拉关系，不如说是故作姿态企图加深苏联的猜疑：美国国务院一面指示美国驻华大使司徒雷登试探跟中共当局接触，一面不批准他前往北京，什么实际行动都不干，最后一走了之。就这么个姿态就让某些人喋喋不休说美国并非想跟中共对立，全是毛泽东的“一边倒”断送了机会，害了中国等等等等。这些人不希望中共长脑子长记性长心眼，毛泽东却对美国人的本性一清二楚：几年前刚刚跟蒋介石合作上演过一边“调解”一边运兵杀共产党的双簧，直到当时也一刻没有停止过援蒋反共的实际行动。现在故作姿态，无非是缓兵计加离间计，另外也是摸底：看中共是否有“共产党员时刻听从美国召唤”的味道，被人家杀着头还愿意赔笑脸、三鞠躬、“一边倒”。如果中共想当宋江，急着受招安忙着跟美国眉来眼去，结果必定是苏联翻脸，美国先坐山观虎斗，然后出来收拾残局，跟苏联再做一次交易，合伙肢解中国——如前所述，1949年的中国是那样虚弱，那样内外交困，抵挡得了两个超级大国的两面夹攻吗？即便抵挡得了，代价呢？

“不偏不倚”同样行不通。夹在两强当中的弱者“两面不得罪”的结果只能是“两面不讨好”，照样要受到美苏两家的夹击。

而在1949年的具体情况下向苏联“一边倒”则不同。对苏联而言，中国向美国“一边倒”是“致命的威胁”；对美国而言，中国向苏联“一边倒”是“严重的威胁”而不是“致命的威胁”。威胁的程度不同，反击的力度也不同。苏联的冷战需要是中苏边境方向不受美军威胁。中国的民族利益是把两个超级大国最终都赶出去。在“把美军赶走”这一点上，苏联的冷战需要跟中国的民族利益不矛盾。只要新中国没有向苏联出让主权，只要没有新的苏军进入中国，那来自苏联方向对中国民族利益的威胁就不比以前更大。1949年的冷战形势是美国包围苏联，苏联处于守势，对中国向自己“一边倒”喜出望外，不愿也来不及做危及这个大局的伤害中国的事。这就使中国解除了最大的后顾之忧，要面对的只是来自美国的经济封锁。这对中国民族利益的损害比被两个超级大国肢解那样的命运无疑小得多。“两害相衡取其轻”，对中华民族最根本的民族利益而言，毛泽东的“一边倒”是唯一正确的选择。

苏联对中国的态度、对中共的态度从来都是国家利益第一，从来不受意识形态的束缚。毛泽东对苏联的态度实际也一样：讲意识形态，但更讲民族利益，否则不会坚持独立自主。尽管苏联在毛泽东打天下的过程中捣了不少乱，尽管苏联与中国有那么多的历史恩怨，但毛泽东坚持了一个原则：民族利益超越意识形态，超越个人好恶，超越个人利益，超越个人恩怨，决不感情用事。

毛泽东的“一边倒”并不是无原则地一切都赖在苏联身上，使中国离不开苏联，而是坚持独立自主靠自己。不象蒋介石，向美国“一边倒”就让美军在中国如入无人之境，让美国军舰长驱直入中国长江内河。面对美蒋的海空封锁，毛泽东几乎从零开始，现建空军，现建海军，现学现用，现用现打， *非不得已不求于人* ——唯一的一次例外是上海保卫战：1950年2月，蒋军飞机炸毁上海发电厂，上海市电力供应下降97%，整个城市陷于瘫痪。在这种情况下毛泽东才同意请苏联暂时出兵相助，但为期仅仅几个月——1950年2月6日蒋军大轰炸。3月20日苏联巴基斯基空军中将率防空集团驱逐机团到达上海担任守卫。6月19日中国空军第四混成旅到达上海。8月1日华东军区空军正式成立。9月3日，陆军出身的华东军区空军司令聂凤智向陈毅报告，他用仅仅一个月的时间便学会了全部空战指挥课程，开始接手苏军指挥防务，苏军开始撤退回国。10月17日，中国空军接收了苏军飞机装备。10月19日，空4旅正式担负起了上海的防空作战任务——全过程一共7个月。

用一个月的时间学会空战指挥并投入实战——这就是毛泽东领导的军队在1950年的速度。中国的海防空防就是这样从无到有争分夺秒建立起来的。美蒋对中国大陆的封锁就是被这样的军队一步一步打破的。

——1949年8月至1950年5月：舟山群岛战役。解放军陆军用原始的木帆船跨海作战，端掉了台湾国民党军队封锁上海、长江口、浙江及东海的基地。

——1950年5月至8月：万山群岛战役。解放军海军第一次参战。端掉了台湾国民党军队封锁广州、珠江口、广东沿海的基地。

——1950年4月至5月：海南岛战役。韩先楚指挥解放军陆军利用原始的木帆船跨海作战，一举占领中国第二大岛海南岛，使中国避免了第二个台湾，获得了收复南海诸岛的基地。

1950年至1953年，中国被迫将主要兵力用于抗美援朝。战争一结束，中国立即挥兵东南，重新开始因抗美援朝而推迟的打破美蒋封锁的战争。

——1954年：解放军与台湾国民党军队争夺东海制空权、制海权，击沉“太平号”。1955年1月18日：攻占一江山岛。2月：收复大陈岛，打掉了台湾国民党军队在浙江沿海的最后一个基地。至此，台湾国民党军队对中国大陆的海空封锁基本被粉碎。

与此同时，面对金门的福建省的战备从基础开始有条不紊全面展开——鹰厦铁路1953年开始勘探设计，1954年全线施工，1957年底竣工，1958年1月通车，1958年夏解放军大举入闽，7月与台湾国民党军队激烈空战争夺制空权，8月23日大规模炮击金门。

美蒋对中国大陆的海空军事封锁就是这样被毛泽东指挥的军队靠自己的力量一步一个脚印地逐步粉碎的。封锁中国的包围圈就是这样被毛泽东领导中国人靠自己的力量、不仰仗别人、经过数年的血腥战斗一寸一寸地扫除的。（这些历史事实足以证明一切污蔑毛泽东“闭关锁国”、“封闭半封闭”、“拒绝对外开放”的人全是恬不知耻的大骗子。）

毛泽东领导中国边打仗边建设。1951年，抗美援朝战争还如火如荼就已经开始裁军。1952年中国财政预算中军费比例从1951年的50%下降到33%——近代中国历史上第一次出现了国家经济建设开支超过军费开支的局面。（国民党的“黄金十年”中军费开支一直占国家预算的80%，但基本用于“剿共”而不是建立独立自主的国防工业。对外则“绝对不抵抗”。）

1953年中国开始第一个五年计划，1957年顺利完成。两年之后，1959年中苏关系破裂，“一边倒”从此结束——中国向苏联“一边倒”共10年（1949～1959）。在这10年中，中国真正用于和平建设时间只有一个五年计划加两年（1953～1959）。也就是说，毛泽东仅仅用了10年的时间、一个五年计划加两年的建设，便使中国彻底摆脱了1945年冷战刚开始时面对超级大国的摆布肢解毫无反抗能力的悲惨处境，改变了中国1949年不得不夹在两大超级大国当中“两害相衡取其轻”的无奈地位，硬是在一个农业古国中从无到有建立起了足以抗衡美苏两个超级大国两面夹击的起码实力，使中国从此能够不再受制于任何一个超级大国，开始走上摆脱冷战主宰的坦途。（这样的成果，这样的效率，靠“市场经济”加“民营企业家”能做到否？）

毛泽东的“一边倒”是特殊历史条件下的特殊斗争方式。其结果不是削弱了中国的独立性，而是加强了中国的独立性；不是危害了中国的民族利益，而是维护了中国的民族利益。

** 历史性分水岭——抗美援朝

中国人里关于抗美援朝争论最多的大致有三：1、该不该。2、赢没赢。3、值不值。

对这些争论只有用中华民族的根本利益为标准，才能得出明确的结论。

*冷战时期中华民族的根本利益是什么？——摆脱美苏冷战的夹击。*

抗美援朝的结果是什么？“赶走一个，送走一个”：美军被从鸭绿江边赶到了三八线。苏军于1955年5月撤出了旅大。——赶走了美军，苏军也就没有了继续留驻中国的理由：中国证明了自己有能力保卫自己。中国被雅尔塔协议剥夺掉的这项主权从此被中国又拿了回来。这是对中国抗美援朝的回报，是中国抗美援朝的一个间接的胜利果实，也是一个根本的标志：把中国东北变成第二个“外蒙古”的隐患从此彻底消除。这样的结果对中华民族的根本利益——摆脱美苏冷战的夹击——是更有利，还是更不利？

有人说因为中国抗美援朝，所以美军才干预台湾。中国是帮了朝鲜，丢了台湾。

这样说的人是瞪着眼说瞎话。朝鲜内战于1950年6月25日爆发。美国于两天之后的1950年6月27日派第七舰队进入台湾海峡，公开干预中国内部事务。中国于4个月后的1950年10月19日派遣志愿军入朝参战。美国干预台湾在前，中国出兵抗美援朝在后。这一切不是什么机密。这样说的人与其说是无知，不如说是无赖。

有人说中国抗美援朝是多余，因为美军没有越过鸭绿江进攻中国的计划。

不知道这样说的人跟美国国家安全委员会主席或美军参谋长联席会议主席是什么样的铁哥们，对人家的心思如此有把握。对这样的说法，最好的答复是萨苏先生在《尊严，不是无代价的——评抗美援朝》中的一段话：

“在日本，阅读了大量关于甲午战争的史料——出乎意料的是，战争爆发之前，日军不但没有打到山海关的思想准备，甚至没有打过鸭绿江的作战计划！对中国这样一个大国，虽然知道它的软弱，几百年前丰臣秀吉在大明的炮声中忧病而死留下的恐惧，依然使日本迈不开侵略的步伐。”

“是谁让日本军队杀进了中国？”

“日本人的记载有些荒唐——因为在平壤缴获了叶志超丢弃的大量装备，日军士气大振。清军陆军的行营炮和连发枪比日军的装备还要先进，却一触即溃，令日军对中国有了‘新的认识’。然而，他们还是遵令在鸭绿江停了下来，并没有敢轻易渡江。”

“这时，对岸却来了一支清军骑兵——这就是所谓的‘八旗铁骑’了。日军只有三十人的先锋部队隔江开枪射击，并且就地准备掘壕防守。不料清军几百人的马队立即蜂拥而逃，丢盔弃甲！于是日军小队长就自作主张渡江追击……后续的日军随即跟上。”

“违抗命令如何？胜利者是不受责备的。确切地说，这些违抗命令的日本兵只是发现了一个事实。”

“从那一刻，中国的尊严，在日本人的心中已经荡然无存了。”

“朝鲜战争之前，这种事几乎每年都在发生的。而朝鲜战争之后，再没有一个国家认真地准备‘征服中国’。即便对于中国的那个政府不满，想要推翻它，也要想出种种制衡的办法来，从政治上，经济上，从各个方面想办法。”

“要是能用战争解决问题，不是比这些复杂而麻烦的方法简单得多？”

“正因为无法征服，我们才有了和这些曾被称作‘列强’的国家坐在一张桌子旁平等说话的机会。”

“而我们这些普通中国人因为这种尊严得到的，就是几十年来不再有战争来破坏我们的家园。”

1950年统帅“联合国军”的麦克阿瑟就是个坚信“胜利者不受责难”、谁也不尿的主：不准越过三·八线？老子偏过。不准使用美军占领中朝边境地区？老子偏用。不准把朝鲜战争跟蒋介石扯上？老子偏访问台湾。怕引起中国干涉？有什么了不起？中国人不过一群厨子裁缝，只会洗衣做饭，哪敢打仗？如果他们敢跟美国军队较量，那将是一场“史无前例的大屠杀”——对这样的将领而言，“没有越过鸭绿江进攻中国的计划”有什么关系？随时制定就是了。如果中国还像“李中堂”时代那样当缩头乌龟、一哄而散，谁能担保当年甲午战争的历史不会重演？

如果麦克阿瑟把“鸭绿江不是不可逾越的边界”的威胁付诸实施，当真过江入侵中国，根据《中苏友好互助同盟条约》，苏军有权出兵。最坏的结果：又一次“日俄战争”——外国军队在中国的土地上大打出手。不论谁胜谁负，战争的破坏都落在中国人头上。

即便美军不过鸭绿江，只是与中国军队沿江对峙，那又如何？中国必须随时随地防备美军打过来，必须在中朝边境处处设防，当时中国最大的重工业基地——东北的工厂必须内迁，整个中国的经济建设都要被打乱。更关键的是：苏联便有理由长期保持在旅大的驻军。这就使中国被牢牢绑死在美苏冷战的棋盘上愈陷愈深，离摆脱冷战这个根本目标越来越远。

*抗美援朝最大最深远的影响：1840年以来西方列强第一次得出结论：“不要进攻中国大陆”、“不要在陆地上跟中国较量”。*

列强如果1840年就有这个结论，就不会有鸦片战争了。如果甲午战争前就有这个结论，就不会有马关条约了。如果1900年就有这个结论，就不会有八国联军了。如果七·七事变前就有这个结论，就不会有八年抗战，尤其不会有“南京大屠杀”了。可见这个结论何等宝贝。

然而，从1840年鸦片战争开始，列强得出的却是另一个结论：“中国不堪一击，不打白不打”。

俾斯麦说：“当代的重大政治问题不是用说空话和多数派决议所能决定的，而必须用铁和血来解决。”

“中国不堪一击、不打白不打”这个结论是列强“用铁和血”得出来的，不是“用说空话和多数派决议”决定出来的。

于是有了一系列的侵略战争，有了中国一系列的失败屈辱，有了满清七十多年内签订的一千多个丧权辱国的不平等条约——差不多平均每年14个，每月摊上一个还多。

百年来不知多少中国人试图靠“说空话和多数派决议”而不靠“铁和血”来改变这个结论。无论是举人进士出身、八股文倍儿溜的曾国藩、李鸿章，还是留过洋的“蒋委员长”，身边都不乏能言善辩之士，“说空话”、打笔墨官司个个不外行。结果呢？“妙笔生花”和“三寸不烂之舌”改变了列强的“中国不堪一击、不打白不打”的结论了吗？仅以1931年到1937年这6年为例：

——1931年9月18日，日军发动“九·一八事变”，占领了东北。国民党政府“绝对不抵抗”，请西方列强“调停”：“先以公理对强权，以和平对野蛮，忍怒含愤，暂持逆来顺受态度，以待国际公理之判断。”

列强调停建议：中日两国都从中国东北撤出武装力量，中国东北由西方列强各国共管。《国联》通过了“多数派决议”，“不承认”日本占领东北。结果：日本退出《国联》，日本在东北建立“满洲国”。“多数派决议”一文不值。

——1932年1月28日，日军发动“1·28事变”，进攻上海。5月5日国民党政府签《上海停战协定》，划上海为非武装区，中国不得在上海至苏州、昆山一带地区驻军。

——1933年5月31日国民党政府签《塘沽协定》，承认了日本对东北、热河的占领，划绥东、察北、冀东为日军自由出入地区。“长城线以南由中国方面警察机关担任之上述警察机关，不可利用刺激日军感情的武力团体”。

——1935年7月国民党政府签《何梅协定》，中国河北省主权大部丧失。

——1935年6月27日国民党政府签《秦土协定》，中国丧失了在察哈尔省的大部分主权。

……

指望“说空话和多数派决议”的结果，是用“漂亮的书法”在一个又一个丧权辱国的协定上签字画押。——“铁和血”得出来的结论，只有“铁和血”才能改变。

中国人不是没有试过用“铁和血”来改变——八年抗战中国人付出的“铁和血”还少吗？但是那些“铁和血”硬不过列强的“铁和血”：当美军介入朝鲜、干预台湾、兵临鸭绿江时，满脑子仍然是列强1840年以来“铁和血”的老结论：“中国不堪一击，不打白不打”。

抗美援朝的“铁和血”彻底改变了1840年以来列强的“铁和血”的结论——从此不再是“中国不堪一击、不打白不打”，而是“不要进攻中国大陆”、“不要在陆地上跟中国较量”——中国人百年奋斗、八年抗战、牺牲几千万人、不知付出多少“铁和血”都没能做到的，毛泽东领导的抗美援朝用“铁和血”一举做到了——就凭这一条，能说中国抗美援朝失败了吗？

还不止于此呢。

既然推翻列强“中国不堪一击、不打白不打”的结论“不是用说空话和多数派决议所能决定的，而必须用铁和血来解决”——这就意味着非打一仗不可。如果在中国领土上打这一仗，即便中国赢了，那中国本土也要饱受战争破坏。而抗美援朝却使中国既用“铁和血”推翻了旧结论，又使中国本土免遭战争破坏——就凭这一条，能说中国抗美援朝亏了吗？

中国大陆在抗美援朝之前战乱不断，从来没消停过。但自抗美援朝之后，中国大陆就再也没遭受过任何大规模战争。对于中国，1949年是分水岭：1949年之前的中国是战乱的中国，1949年以后的中国是和平的中国。毛泽东时代的中国既是“准战争时代”的中国，又是免遭战祸的中国。扭转乾坤之举是抗美援朝。 *抗美援朝是当代世界认识中国的历史性分水岭。*

俞可平说“1949年后”的中国没有了“以人为本”、否定了“人道主义”、“人们的正常情理和心态受到严重的扭曲”——言外之意：1949年以前的中国是“以人为本”的中国，充满“人道主义”的中国，人们的“正常情理和心态不受到严重的扭曲”的中国——比起充满战争的“1949年前”，没有战争的“1949年后”居然是没有“以人为本”，可见俞可平不承认让中国人民免遭战争苦难是最大的“以人为本”，最大的“人道主义”，最大限度地保护了人民的“正常情理和心态”。——也就是说，俞可平口中“以人为本”的那个“人”指的不是普通老百姓，而是像他那样的“精英”。充满杀戮、死亡和破坏的战争不算破坏“以人为本”，“精英”感受不自在才算，可见“精英”的幸福感比让中国老百姓免遭战争苦难更重要——这条日本鬼子就能满足：当中国普通老百姓惨遭屠杀抢掠时，给日本鬼子当走狗的汉奸们不是过的很滋润吗？虽然在“太君”面前是条狗，但在“不是人”的老百姓面前却是“高等华人”，能充分享受“以人为本”、免受战争苦难的“人道主义”。可见俞可平的“以人为本”中的那个“人”只包括战争中能免受死亡苦难威胁的“高等精英”而不包括普通老百姓。用老百姓的俗话说，这小子就俩字——欠揍：如果这厮领教过日本鬼子的皮鞭耳光拳打脚踢的滋味，领教过南京大屠杀的滋味，领教过战火纷飞朝不保夕忍饥挨饿的滋味，那他就知道让中国老百姓免受战乱之苦算不算真正的“以人为本”了，就知道他一脸不屑的“1949年后”对中国人民意味着什么了。

有人说中国抗美援朝是上了苏联的当，为苏联当替死鬼，连武器都得自己掏钱，可见中国当了冤大头。

如前所述，中国抗美援朝是因为它符合中国的民族利益。既然符合中国的民族利益，那中国就是在为自己而战而不是在为别人而战，就不存在上当受骗当替死鬼的问题。当时中国和苏联的利益在抗美援朝这一点上一致，苏联提供的武器不少是要钱的，但白给的也不是没有。比如1951年志愿军攻占汉城后苏联就一次无偿赠送了米格～15歼击机372架。不过如果苏联一切都白给，那反而未必是好事：国与国的关系如同人与人的关系，宁可欠债，不可欠情。欠债算得清，欠情算不清。一旦有变，欠债可还，欠情难缠。比如两人恋爱，一方为另一方牺牲了一切：前途、机会、专业、工作、财产、亲情……却被对方占足了便宜后一脚踢开，那将会如何？搞不好能出人命。中苏分裂后苏联人对中国虽然恼火，却并不恨之入骨，因为当初中国并没有亏待苏联，只欠债，不欠情。赫鲁晓夫撕合同撤专家把事都干绝了又有点懊悔，很有点恋恋不舍当初能从中国得到的好处。结果：对美国联手干掉中国核力量的建议犹豫了一阵子。就这么一犹豫的功夫，中国的原子弹爆炸成功了。相反的例子是越南：跟中国打交道时一切白捞，占尽了便宜，很有点沾沾自喜洋洋得意：看我多能耐。越南不理会“宁可欠债、不可欠情”那一套，当为傍苏联过河拆桥跟中国翻了脸时，中国人从上到下立刻个个恨得咬牙切齿，同仇敌忾根本不用动员，说打就打毫不留情。两相比较，到底谁更吃亏？

最精于算计的当属“蒋委员长”：抗日战争时吃定了美国的底牌是不能让中国垮掉，只要国民党没有投降日本，不管打不打、打得有多烂美国照样得给钱给援助。这竹杠不敲白不敲。于是一天到晚向美国叫苦要援助。但东西一到手就全留着对付共产党，不对日本动真格的。不管美国如何催促，“委员长”总是“以不变应万变”——要东西来劲，打仗不来劲：给我援助可以，要我跟日军拼命不干。小算盘是反正美国早晚能打败日本，自己可以稳搭“顺风船”，犯不着拼命，不如趁机发一笔，留着将来消灭共产党用——不愧“浙江奸商”兼“上海小开”，算盘精，“拎得清”。（据罗斯福的儿子艾利沃特回忆，“罗斯福终于明白了：‘中国军队一心只放在监视共产军上，根本无心和日军作战。’”）1944年日军到处吃败仗，唯独打通中国大陆交通线之役大获全胜，打得“国军”一溃千里，望风而逃。美军驻华代表史迪威将军急了，要蒋介石赶紧调兵挽救战局。蒋介石说无兵可调。史迪威说你的胡宗南有四十万大军正闲着呢。蒋介石说那是对付共产党的，不能动。史迪威说既然你没兵那何不让我用美国武器装备共产党的八路军，由我带出去打日本。蒋介石勃然大怒，立即以“不撤换史迪威中美两国即无法合作”为最后通牒逼罗斯福调走了史迪威——表面上看“蒋委员长”大获全胜：赶走了对共产党有好感的史迪威将军，自己继续过“仗不打，美援白拿”的好日子，光占便宜不吃亏，让美国当冤大头。结果呢？美国立马放弃了陆地上靠中国军队打败日军的打算，转身求助于苏联。苏联正中下怀：求我可以，得有甜头——中国的主权。美国满口答应（这才是最狠的报复）。于是有了雅尔塔协议，有了苏联出兵东北。最后的结局：小算盘最精、最“拎得清”的“蒋委员长”被赶出了大陆，到台湾小岛上斤斤计较“拎得清”去了——只知算小帐，只知贪小便宜，见小利忘大义，总想白捞油水，有此下场奇怪吗？

*整天拿抗美援朝“亏不亏”、“合算不合算”说事的人其实是“醉翁之意不在酒”，找借口妖魔化毛泽东而已：现在中国“公款吃喝”每年有多少？贪官弄到国外的赃款每年有多少？“国有资产流失”每年有多少？中国的买办让外国老板从中国人身上榨取的血汗每年有多少？怎么从来也不见他们着急？怎么从来也不见他们象对抗美援朝那样斤斤计较、“拎得清”？*

有人专拿中国抗美援朝的伤亡说事。首先，战争的目标是胜利。看胜利与否不是看代价大小，而是看是否实现了战争的战略目标。实现了就是胜利，否则就是失败。——能说苏联卫国战争中的牺牲比德国大，所以苏联是战败国而德国是战胜国吗？能说中国抗日战争的牺牲比日本大，所以中国是战败国而日本是战胜国吗？其次，根据中国的统计，武器装备绝对劣势的志愿军抗美援朝的伤亡总数并不比“联合国军”的伤亡总数高。某些人论及中方的伤亡数字不用中国的统计而用美军的估计，这本身就是偏见的表现。而对比伤亡数字时，故意用美国一家的伤亡总数来对比志愿军的伤亡总数，这实际在耍流氓：跟志愿交手的有十六个国家（包括南朝鲜）的军队，这十六家的伤亡数字加在一起与中国一家的伤亡数字相比才能说明问题。中国出兵时北朝鲜的军队基本打光了，那些伤亡数字不能算在中国头上。隐瞒所有这些事实，用美军一家的伤亡数字和美军估计的中朝双方的伤亡数字做对比，这难道不是玩弄数字游戏搞诈骗？

有人说抗美援朝招致美国对中国长达二十多年的封锁禁运，给中国造成了巨大的困难和损失，可见抗美援朝没好处。

*前面已经说过，只要中国还没有摆脱冷战，那就不可避免要吃冷战的亏。美国干预台湾是因为冷战。封锁中国也是因为冷战。这就是冷战给中国带来的伤害，是中国向苏联“一边倒”的代价。问题的性质是这样的向苏联“一边倒”的代价与中国的东北、西北变成第二个、第三个“外蒙古”、整个国土被美苏肢解那样的向美国“一边倒”的代价孰轻孰重；是“两害相衡取其轻”的问题，而不是在“有害”与“无害”之间作选择的问题。*

美国的封锁禁运是一柄双刃剑，能伤人也能伤己。本来美国的算盘是封锁禁运能使毛泽东的政权即便不垮也发展不起来。但美国没想到毛泽东的中共是在被封锁被围剿的根据地这种环境中长大的，自力更生惯了，封锁禁运别人受不了，中国不但顶得住，而且摸索出经验来了，发展的路子步伐谁也干预不了。随着中国实力的不断增长，美国越来越坐不住了：

1962年古巴导弹危机，美国对古巴实行海上封锁，禁止向古巴运进“进攻性武器”（导弹、轰炸机）。当时美国海军对驶往古巴的中国轮船概不搜查——不是尊重，而是一种无言的轻蔑：谅你中国船上没有“进攻性武器”。但仅仅过了两年，中国原子弹试验成功（1964年）。又过了两年，中国导弹核武器试验成功（1966年）。再过了一年，中国氢弹试验成功（1967年）——1962年古巴导弹危机后仅仅5年，美国就再也没法对中国保持“谅你也没有进攻性武器”那种悠然的心情了。相反，美国不得不扒耳挠腮发愁：如果中国向“不友好国家、势力、地区”提供“进攻性武器”如导弹甚至核武器，那可怎么办？（实际上，利比亚总统卡扎菲确实曾提出愿意花大价钱向中国买原子弹，但周恩来总理彬彬有礼地拒绝了：原子弹是不供出售的。）要求中国同意不出口“进攻性武器”？处于敌对状态的中国会听你的？向中国施加压力？已经封锁禁运了二十年，能施的压力全施完了，再没什么可施的了。向中国开战？又不是没较量过。除非核大战，否则还能怎么样？设法让中国改变政策？美国与中国敌对二十年，对中国社会的影响几乎是零，吃里扒外替美国效劳的“基金会学者”一个都没有，能指望谁说得上话？被封锁被隔绝的中国成了“和尚打伞，无法无天”，不受任何条约规定的制约。不管是美国还是联合国，不管是国际组织还是“民权团体”，中国可以概不买账。谁也休想对中国内部事务指手画脚，说三道四。美国越来越痛感对中国的封锁禁运对美国利益的损害简直不亚于对中国利益的损害，越来越急着改变这种状况。尼克松说美国决不能让“几亿中国人生活在愤怒的孤立之中”，潜台词是：一个愤怒而孤立的中国更能给美国造成无法估量的损害，还不如赶紧解除封锁禁运，恢复美国对中国社会、对中国“精英”的影响力。所以到后来美国解除对中国封锁禁运的心情其实比中国人自己更迫切，而且更彻底：以后再也不这么干了。典型的例子是1989年，老布什坚决拒绝对中国重新施行严厉的封锁禁运。表面上说“不愿意孤立中国人民”，实际是历史的教训领教够了：对中国搞封锁禁运不但无效，而且到头来“搬起石头打自己的脚”。（如果封锁禁运管用，美国才不会在乎是否“孤立人民”呢。比如对萨达姆时代的伊拉克，那就封锁到底，毫不手软。）

抗美援朝导致的封锁禁运是坏事不假。但毛泽东领导下的中国把这种坏事变成了好事，反而使美国从此以后再也没胃口对中国用这招了。一劳永逸——1989年中国就沾了毛泽东的光——这难道不是坏事变成了好事吗？这难道不是有利于中国的民族利益吗？

** 咬定青山不放松——中苏分裂

中苏分裂表面上是因为意识形态，实际真正的原因是民族利益——民族利益超越意识形态、超越个人恩怨，超越个人好恶，超越个人私利。

五十年代初，中国的民族利益与苏联的冷战需要基本不冲突，加上有共同的意识形态，所以两国关系很热火。

艾森豪威尔上台后，变美国的战略从“遏制”为“大规模报复”，一切跟核战争挂钩：放弃过去认为在有限战争中不应使用核武器的想法，决定只要军方认为军事上需要就可以使用核武器，包括使用战略核武器和战术核武器，让“潜在的敌人由于确信美国将以它愿意的方式——首先是核手段——还击侵略而受到威慑，因而不敢轻举妄动”。

面对美国以核优势为后盾的“大规模报复”战略和“战争边缘”政策，苏联决定“缓和冷战”。1954年1月美国国务卿杜勒斯宣布“大规模报复战略”。两年之后，1956年2月的苏共二十大便提出了“和平共处”、“和平过渡”总路线。这实际是要求已经当政的共产党不要得罪美国，没当政的共产党别再走暴力革命的道路。潜台词：既然“一颗小小的火星就可以引起核大战”，那象抗美援朝那样的麻烦今后不能沾，免得惹火烧身，为了你的国家统一把我苏联拖进核战争。

这样一来，中国收复台湾、维护领土完整和统一的民族利益就跟苏联的冷战需要矛盾了：要统一台湾就必须反掉美国的干涉。经过麦卡锡主义肆虐、顽固坚持冷战理论、敌视中国的美国坚决拒绝跟中国做任何妥协，甚至根本不承认中国政府，只承认在台湾的蒋介石当局代表全中国。最典型的事例就是1954年日内瓦会议上杜勒斯拒绝与周总理握手——敌视到这个份上，怎么“缓和”？即使中国放弃统一台湾美国都不会答应，更不用说中国坚持收复台湾了。毛泽东面临的问题是：是为苏联的冷战需要而牺牲中国的民族利益，放弃收复台湾的努力，还是为中国的民族利抵制苏联的冷战需要？毛泽东“咬定青山不放松”——咬定中国的民族利益绝不松口。这才是中苏决裂的根本原因。

1958年苏联提出在中国建立长波电台、与中国建立联合舰队，被毛泽东一口回绝。毛泽东为什么发那么大脾气，反应那么激烈？因为这两个建议将严重危害中国的民族利益。

成立联合舰队、平分指挥权不仅意味着中国军权旁落，破坏毛泽东“坚持党对军队的绝对领导”这一根本原则，而且等于要封锁中国海岸线：当时中国海军力量很小。要成立联合舰队，中国的军舰都得填进去。苏联是“瘦死的骆驼比马大”，随便扫扫库底子就行了，自己另外仍然有完全属于自己的舰队。联合舰队表面是指挥权一家一半，实际上是让苏联拥有了对中国海军的否决权——只要不符合苏联的冷战需要，那联合舰队就甭想动。中国不管是收复台湾、护航护渔还是收复西沙南沙之类，都得事先经过苏联批准。这样一来，没有苏联的同意，中国的海军等于说没就没了——没了海军，中国的海岸线岂不等于被封锁了？理论上中国对联合舰队同样有否决权，实际那个否决权对中国没什么意思：当时中国没什么远洋权益，当务之急是沿海近海。中国近海的事跟苏联的冷战没多大关系，苏联却要管；远洋的事跟中国没多大关系，中国怎么否决？根据什么理由否决？实际的结果是苏联说了算，让中国当冤大头。而且即便中国行使了否决权苏联也不在乎：苏联除了联合舰队还有得是军舰可用，你联合舰队出不出动对苏联无关紧要。

建立长波电台的名堂就更大了。长波电台是为潜艇作战服务的。而在中国成立长波电台只能是为远洋作战服务——苏联本土的长波电台已经足够苏联潜艇近海作战用的。当时中国有多少远洋权益？这长波电台实际是为苏联海军远洋活动服务。而苏联海军到远洋活动只可能是跟美国较量，百分之百属于苏联冷战的需要，对中国的民族利益没什么好处。当时中苏是同盟国。理论上，一方遭到攻击时另一方有义务参战。但如果一方主动攻击别人呢？另一方就没有参战义务。在陆地上谁遭受攻击一目了然，在海上，尤其在远洋，军舰与军舰之间谁攻击了谁哪那么容易查清楚？这样一来，如果苏联与美国发生了海上冲突，不管是谁攻击谁，只要苏联宣称自己是遭到攻击的一方，那中国就得站在苏联一方参战，自己一点作不了主。当时美国坚持的是“大规模报复战略”，又把中国苏联看成铁板一块，有了抗美援朝结的“梁子”，恨中国胜过恨苏联。而当时中国的防卫力量又远不如苏联，万一美国跟苏联冲突，十之八九“老太太买柿子——专拣软的捏”，首先冲着中国来。如果苏联想暗中使坏借刀杀人，通过制造个海上冲突借美国的力量重创中国也不是不可想象的。所以表面上是个长波电台，实际是一张卖身契，要中国把和、战的选择权拱手交给苏联。

苏联关于联合舰队和长波电台的建议的真正效果是把中国牢牢绑在苏联的冷战战车上，休想摆脱苏联阵营。这跟中国的民族利益完全对立，毛泽东为此大动肝火一点没有错。

苏共二十大的路线、联合舰队和长波电台的建议标志着中苏关系已经走到了转折点：苏联的冷战需要跟中国的民族利益已经不能再兼容了。尽管如此，毛泽东还是竭力挽救两国关系，试图劝说苏联不要因美国的战略讹诈而改变总路线。赫鲁晓夫说美国现在碰不得，一碰就要打核大战，为小冲突把自己全赔上不值得。毛泽东说美国的“大规模报复”战略和“战争边缘”政策是吓唬人的，实用性很有限。它只立足于正面冲突、全面大打。但碰上小打小闹，特别是不牵涉到美国人的局部冲突就不知所措了——你能因为南越一支共产党的游击队伏击了亲美的政府军就往那里扔原子弹吗？不跟美国正面冲突不等于碰都不敢碰，顶多不正面突破就是了，侧面迂回仍然行得通。

毛泽东如此主张并非头脑发热。美国提出“大规模报复”战略后，毛泽东专门针对其搞了两次火力侦察：一江山岛之战和炮击金门。回顾一下这两次战役的大概经过，不难看出毛泽东胆识惊人，独具匠心。

——1954年12月1日，美台签订“共同防御条约”，规定美国帮助台湾当局协防台湾和澎湖列岛；美国有“依共同协议之决定在台湾、澎湖及其附近为其防卫所需要而部署美国陆海空军之权利。”48天后，1955年1月18日，解放军发起一江山岛战役，迅速攻占该岛。艾森豪威尔马上于1月24日向美国国会提出特别咨文宣称：“如果台湾和澎湖列岛落入不友好者的手里”，那就会“在西太平洋的岛屿锁链中造成一个缺口”，“中共对大陈群岛的炮击是共产党征服台湾的序幕，美国必须对此采取行动”。美国国会众参两院迅速于1月25日和1月28日分别通过“授权总统在台湾海峡使用武装部队的紧急决议”即《福摩萨决议案》。美军随即先后出动6个航空母舰群、400余架飞机全面封锁浙东海域，掌握了大陈岛——台湾——冲绳三角地带的制空权，控制了台湾对大陈岛屿的运输线。美国参谋长联席会议命令战略空军指挥部“以紧急情况为基础”，开始为大规模使用核武器攻击中国大陆选定目标。毛泽东针锋相对，于1月28日接见芬兰大使时说：“我们有两条：第一，我们不要战争；第二，如果有人来侵略我们，我们就予以坚决回击。”“美国的原子讹诈，吓不倒中国人民。”两天后（1月30日）解放军空军猛烈轰炸大陈岛。当天（1月30日），美国命令第7舰队准备帮助国民党部队从大陈撤退，并通过苏联向中国转达这一信息，希望在美军帮助国民党军撤退时，中国人民解放军不要采取行动。中国政府接到苏联转达的这一信息后指示解放军对从大陈撤退的美、蒋军不要攻击。2月5日，美国命令第7舰队和其他部队帮助国民党军队从大陈岛撤退。2月25日，解放军占领大陈列岛中最后一个岛屿。浙东沿海全部岛屿均被解放，大陈岛至金门数百公里海岸和近海海域全部被解放军控制，国民党军在大陆沿海所控制的岛屿仅剩下了金门和马祖。自1949年以来国民党对大陆的海空封锁基本被粉碎。（毛泽东冒着核威胁的风险发动一江山岛之战，就是为了打破对大陆的封锁。说毛泽东“闭关锁国”、“封闭半封闭”的人要脸不要？）

——1958年8月23日，毛泽东下令炮击金门。数日后宣布暂停炮击，允许国民党军舰向金门运送补给，条件是美国军舰不得护航，否则立即开炮。美国无视这一禁令，公然为国民党军舰护航。毛泽东立即下令开炮，命令只打国民党军舰，不打美国军舰。但如果美舰开火，则允许还击。炮声一响，美舰立即抛下被护航的国民党军舰而去，一炮未放。

这两次战役说明了什么？

1、美台的“共同防御条约”不适用于大陆沿海岛屿。美国只对台湾本岛感兴趣。

2、美国的原则是让蒋介石替美国卖命，不是让美国替蒋介石卖命，更谈不上“舍己救人”。

3、美国人的决心并没有表面上讲得那么吓人，并不是稍微一碰就当真要“大规模报复”打核大战。美国的战略实际是消极防守的战略，不是主动寻衅找岔子找机会跟中国打核战争的积极作战的攻势战略。美国虽然嘴上很硬，但并不打算主动发起对华战争。

4、美国的那个“大规模报复战略”太绝对，碰上小规模局部冲突这样的“擦边球”的复杂情况就不知所措：打又不是，不打又不是，左右为难。这样的战略完全对付不了毛泽东最拿手的游击战。

5、“正面攻不动，侧面迂回”。中国没有力量硬打台湾，但可以在其他地方挑战美国利益，让美国没好日子过，最后逼美国有求于中国。

6、美台的“共同防御条约”既不准大陆进攻台湾，也不准台湾“反攻大陆”。其客观效果是让台湾与大陆彻底隔离，最后势必导致台独。美国压蒋介石放弃金门，把所有兵力全收缩到台湾，让大陆台湾老死不相往来。这证明美国在图谋制造“台湾独立”。而蒋介石坚持保留金门这最后的“反攻大陆”的基地，证明美蒋之间的战略目标并不一致。

7、蒋介石坚持“反攻大陆”就意味着坚持承认台湾属于中国，就意味着反台独。如果大陆收复金门，蒋介石就更难以在美国人面前坚持“反攻大陆”的主张。当短期内没有力量收复台湾时，可以利用蒋介石“反攻大陆”的主张来遏制台独，办法就是炮击金门，保持适当的紧张局势，给蒋介石以“中国内战尚未结束，不能示弱”的借口顶住美国人要他从金门撤退的压力。金门炮战最后演变成“双日不打单日打”，实际是毛泽东、蒋介石在制止台独这个民族大义面前共同放弃了党派私利，联手上演的一出对付美国人制造台独阴谋的悲喜剧，从不同的立场、用不同的方式遵循了“民族利益高于意识形态、高于个人恩怨、高于个人好恶、高于个人私利”的共同原则。

8、美国虽然口口声声“美国利益”，但对“美国利益”的要害所在并不清楚。美军登陆黎巴嫩后，中国大陆向金门一开炮，美国就赶紧把航空母舰从中东调往台湾海峡。等弄清楚大陆并不准备攻占金门，又赶紧把航空母舰开回去。哪里吃紧往哪里跑，证明美国的战略虽然是“守势战略”，但对哪里是要害、哪里是重点心中无数，所以全球到处伸手。这样的对手容易被调动。

毛泽东通过这两次战略侦察基本摸清了美国的老底和真实意图，心中有了底，跟赫鲁晓夫争论起来底气十足。但赫鲁晓夫根本听不进去。他只知道按自己的冷战需要来衡量一切：我这里正跟美国人讲缓和，你那里炮击金制造紧张空气；我正要访问美国谈和平，你那里跟印度发生了边界冲突。全世界都把中苏看成是一气的，你这一打等于让我在美国人面前显成了个一边谈和平一边动手打仗的骗子，美国人对我的缓和呼吁不买账全是你给闹的。你再坚持就要搅黄我的和平共处的总路线。所以你中国无论如何不能打，台湾丢了就丢了，印度要边界领土你让给他就是。总之我的冷战需要高于你的民族利益。

要坚持中国的民族利益，就不能不对苏联的冷战需要说“不”。既说了“不”，那就意味着从“一边倒”走向“谁也不向”。当毛泽东坚决拒绝为苏联的冷战需要牺牲中国的民族利益时，赫鲁晓夫明白了：中国不再“一边倒”了。一直以为中国除了把自己绑在苏联冷战战车上别无出路的赫鲁晓夫之惊讶恼怒可想而知，立刻开始惩戒中国，再也顾不上意识形态、国家关系了。这就是中苏关系破裂的真正原因。

如前所述，处于美苏冷战夹缝的大格局下，中国“向这边‘一边倒’，那边要收拾你；向那边‘一边倒’，这边要收拾你；谁也不向，则两边一起收拾你——除非中国自己足够强”。1949年的中国极端虚弱，根本经受不起“谁也不向、两家一起收拾你”的局面。然而过了十年，仅仅十年，毛泽东已经带领中国建立起了足以抵御两大超级大国两面夹攻的必要实力，可以向“谁也不向”、“挣脱冷战夹击”的总目标进军了。

** 最伟大的阳谋——中苏论战+援越抗美

1959年中苏分裂。中国结束了向苏联“一边倒”，从此对美苏“谁也不向”。如前所述，只要中国不够强大，中国在冷战中就始终处于夹在美苏两个超级大国的夹缝中受欺负的地位：“向美国‘一边倒’，苏联要收拾你。向苏联‘一边倒’，美国要收拾你。谁也不向，两家一起收拾你”。中国在中苏分裂之后遭到美苏两面夹攻一点也不奇怪：“谁也不向，两家一起收拾你”。

在一般人看来，当时的中国实在是毫无希望：外有强敌，内乏粮草，压力空前巨大，处境极端艰难，“黑云压城城欲摧”。中国既没有力量对抗苏联，更没有力量对抗美国，又没有办法劝说美苏改弦易辙改变对中国的敌对态度。（别忘了俾斯麦的名言：“当代的重大政治问题不是用说空话和多数派决议所能决定的，而必须用铁和血来解决。”）在如此绝望的情况下，中国除了屈服投降还有别的出路吗？

历史结果是：13年后的1972年，美国总统尼克松访华。美国对中国的战略从敌对走向缓和，从联苏反华走向联华制苏。中国的“谁也不向，两家一起收拾你”的处境被彻底扭转，从被前后夹击走向左右逢源。对中国的封锁禁运包围孤立从此土崩瓦解。世界政治格局从两极走向“三国演义”，整个冷战局势彻底改观了。

如此天翻地覆的变化是怎么来的？是天上突然自己掉了个大馅饼，让中国白拣了个大便宜吗？是美国突然良心发现，洗心革面痛改前非，从此跟中国讲友好亲善了吗？是中国运气太好，啥也没干世道就突然之间变好了吗？

如果当真如此，那这个世界就是个童话世界。然而童话不是现实。现实中的这一切变化都不是偶然的，更不是白来的，而是一场惊心动魄空前绝后大较量的结果。

尼克松为什么访华？因为美国改变了对华战略。美国为什么改变对华战略？因为第一，美国终于认识到真正威胁美国利益的不是中国；第二，美国有求于毛泽东——帮助美国“体面地撤出越南”。美国为什么会改变对中国的认识，为什么会有求于毛泽东？因为美国陷入了越南战争的泥潭。美国为什么会陷入越南战争的泥潭？因为当时美国认为越南事关美国的核心利益。为什么当时美国认为越南事关美国的核心利益？第一，中苏论战。第二，援越抗美——中苏论战使美国认为毛泽东领导的中国是美国的最大威胁，援越抗美使美国认为越南是中国破坏美国利益的突破口。结论：美国必须在越南跟毛泽东较量。在越南取胜就等于打败了毛泽东，就保住了美国的核心利益。

今天的美国政要精英们一说到越南战争，几乎全部心照不宣地避免提及毛泽东。而整天绞尽脑汁标新立异的中国历史学者“精英”们虽然连“一个章子怡顶一万个孔夫子”这样的匪夷所思的命题都能挖空心思想得出来，但在美国陷入越南战争的泥潭和毛泽东的关系这个问题上却对美国人非常“体贴入微”、“为尊者讳”，绝不在这个方向上做任何研究和发掘。中外“学者”们在此空前一致，千方百计抹杀美国在越南战争的失败与毛泽东的关系——否认了美国在越南战争的失败是毛泽东的杰作，自然也就否认了美国改变对华战略、尼克松访华是毛泽东的胜利这一历史事实。这样一来就可以让普通人以为整个中美关系的历史性变化、中国战略环境根本性改善等等全是美国单方面的恩赐，与毛泽东没什么关系。历史就这样伪造出来了。

判断历史，真正有价值的是当时的事实，而不是“事后诸葛亮”们的信口开河。判断美国当年卷入越南战争的真正目的，看看当年美国政要的们为美国卷入越南战争辩护时的各种讲话、宣言、文件、决定等等白纸黑字的事实就够了。好在这些资料基本都已解密，花不了太大功夫就能查出来。

且看如下事实：

——1959年，中苏分裂。越共中央委员会决定武装统一越南。

——1960年，“中苏论战”爆发。

——1960年，中国出版发行《毛泽东选集》第四卷，外电纷纷报道评论。10月17日，《美国新闻与世界报道》发表题为《毛想使美国成为一只“纸老虎”》的文章，称：“毛泽东夺取世界的计划在要赤色中国人民学习的一本新书中作了概括的说明。”

——1960年11月19日，毛泽东公开接见并宴请古巴游击战英雄格瓦拉。顿时，“激进的赤色中国试图用游击战征服世界”的“中国威胁论”风靡一时。

——1960年12月，越南南方民族解放阵线成立。中国政府立即予以承认。

——1961年，肯尼迪就任美国总统，将“大规模报复战略”改为“灵活反应战略”，要求部下研究毛泽东著作，尤其是游击战的理论。肯尼迪亲自阅读毛泽东有关游击战争的著作，以求能找出破解以弱胜强人民战争的策略和方法。他常对他的妻子杰奎琳说，毛泽东把军人与人民的关系比作鱼儿与水的关系，多么巧妙。杰奎琳听后哈哈大笑。（1965年1月，毛泽东会见《西行漫记》作者斯诺时说：“美国总统肯尼迪为了对付亚非拉的新兴力量，提出了特种战争和局部战争。有消息说，他也看我写的军事文章，这可能是真的。”同年7月26日，程思远陪同归国的李宗仁见毛泽东时，也告诉毛泽东，肯尼迪生前在他的办公桌上摆着一部《毛泽东选集》，看来是要人们研究中国。）

——肯尼迪任命号称“冷战斗士”的腊斯克为国务卿。腊斯克经常把毛泽东、胡志明比作希特勒，把越南比作1947年的希腊，把和平抗议者比作对纳粹德国的绥靖分子。

——1961年1月28日，肯尼迪刚就职一个星期就向其高级顾问们表示他对越南问题有了危机感和紧迫感。不久，美国国务院通知驻西贡使馆：白宫已把在南越的“反叛乱”确定为美国对外政策最优先的事务之一。4月29日，肯尼迪批准在南越建立一个作战发展与试验中心，用以发展反越共的新技术。5月，美国派遣特种部队和军事顾问到南越，同时向南越提供财政支持帮助西贡政权推行“战略村”计划。“特种战争”爆发。

——1961年9月9日，肯尼迪在对NBC电视台晚间新闻节目主持人切特•亨特利和戴维•布林克利说：“中国的领土是如此之大，就像一个巨大的庞然之物一样，屹立在边境之外，如果南越倒向他们，那将比较会为他们在马来亚开展游击战争提供有利的地理条件，而且，也会给人们造成深刻的印象，即东南亚的发展趋势将掌握在中国和共产党人的手中。”

——美国驻苏大使汤普森给美国国务院的备忘录声称：“中国人正在提倡以更好战更咄咄逼人的政策反对西方，特别是美国。”“我们肯定不应站到中国人一边，同苏联人相比，他们倡导一种至少在短期内对我们更危险的政策”。

——1961年11月下旬，一个由中央情报局、国务院情报处、陆海空参谋长、所有美国情报委员会成员组成的国家情报特别评估委员会，对中国的外交意图做了仔细的剖析，认为：“一旦形势适宜，北京就会以常规政治战争形式，支持当地的游击战争和恐怖行动，或充当后盾和幕后操纵者。”

——1961年11月3日，美国国务院智囊班子——政策规划委员会主任罗斯托（Rostow, Walt W.）和泰勒给肯尼迪的报告中认为：“南越的失陷将导致共产主义的极度扩张，使东南亚和马来群岛的其他国家处于共产主义的控制之下，其战略影响特别是在亚洲的影响将是非常严重的；如果美国军事力量没有实质性的介入，阻止南越失陷的可能性是微乎其微的。”

——1962年1月2日，罗斯托宣布，中苏分裂显然是“史无前例的事件”，美国应该支持共产阵营中铁托那样的右倾分子，而不支持中国那样的“左倾分子”。

——1962年2月，“美国驻越南军事援助司令部”在西贡成立，直接统一指挥南越吴庭艳军队和美国“特种部队”作战。

——1962年3月26日，美国哥伦比亚大学共产主义问题研究所所长布热金斯基在《新共和》周刊上发表文章《和平交战的政策——我们如何能从共产主义的不团结中得到好处》，建议美国政府：因为“中国共产党人对美国的极端敌视”，所以应该“把友好和敌视区别对待的政策应用于中国”，“至少在现阶段继续排斥中国”。

——美国中央情报局1963年1月14日的备忘录中指出，“因为北京的尚武和强烈反西方的路线，一个单独在中国领导下的亚洲共产集团对美国的远东安全利益有严重影响。”

——1963年10月5日，前美国驻苏联大使凯南在《星期六晚邮报》发表文章《我们能同莫斯科交易吗？》称：“中国人的立场是不顾死活的，不负责任的，对谁都是危险的（包括中国自己在内）。苏联的立场却表明它开始认识到共产党和非共产党国家在具体的有限的一些方面可以有共同利益。”

——1963年12月13日，美国远东事务助理国务卿希尔斯曼在旧金山联邦俱乐部发表演说《美国对共产党中国的政策》，宣布：“中国是一个‘敌视西方、威胁邻国的激烈的敌对力量’，美国在远东面临的‘最大麻烦’的问题就是中国”；“苏联在核时代的现实面前似乎认识到某些利益——特别是生死存亡的利益——是全人类一致的。但是，北平（即北京）却仍然坚持正统形式的共产主义，这种共产主义强调暴力革命，即使将使世界文明遭到毁灭的危险也在所不惜。它不承认什么超越意识形态的界线的共同利益。”“美国对华政策的首要目标是要中国不对‘自由世界和邻国进行颠覆或发动侵略’，这需要在中国周围建立一个包围圈来‘遏制’中国”。

——1964年3月2日，美国参谋长联席会的备忘录宣称：“就美国的安全利益而言，阻止南越的丧失是头等重要的大事。”

——1964年3月26日，美国国防部长麦克纳马拉声称：“中国共产党人的利益是十分明显的。每当苏联发出警训式的调子时，他们就会公开谴责莫斯科，指责他们已背叛了革命的事业。他们将美国视为一只纸老虎，并坚持认为，在自由世界的核防务和常规防务面前，通过缓慢而卓有成效的运动，越南就可以进行其‘解放和统一’的革命斗争。因此，北京似乎认为，他们已经发现了一个绝好的时机，运用越南作为试验品来展现自己的新战略。北京认为，越南的胜利将为中国的论点提供有力的佐证，为其在世界范围内进行意识形态斗争服务。”

——1964年8月，美国中央情报局的国家评估委员的报告结论如下：“南越和老挝落入共产党人之手中，将会极为严重地削弱美国在远东的地位。造成这一结果的特殊原因是，长期以来，美国已经引人注目地公开承担了义务，要阻止共产党人强占这两个国家。失败于此，将对美国的威望带来无法估量的损害，并且，在遏制共产主义在其它地区的扩散方面，美国意志的可信度和能力也将受到严重的贬低。我们的敌人将会为此受到鼓励，而在其它国家中，以更大的规模向共产党人靠拢的倾向，将会出现快速增长的势头。”

“除了北越会因为实现了国内目标而感受到直接的欢欣鼓舞外，中国的共产党人也会受惠无穷。这不仅使他们早已引人注目的自信心得到了进一步的助长，而且，也使他们作为共产主义世界领袖的威望得到了提高。北京的理论认为，未发达国家革命的条件已经成熟，美国是一只虚张声势的纸老虎，地区性的暴动和起义不会导致国际间的大战，可以毫无风险地走向最终的胜利。他们早已将南越视为这些理论的试验场，并大造舆论。相比于苏联比较谨慎的姿态而言，南越和老挝的最后结果，将更为显著地支持了北京咄咄逼人的进攻性战略立场。就某种程度而言，这种结果对世界各地不发达国家出现更为积极的革命运动，将无疑会起到推波助澜的作用。”

——1964年12月，约翰逊指定的政策研究小组特别报告称：“如果我们不采取足以在军事上击败北越甚至共产党中国的军事行动，则我们不能保证非共产党的南越能继续存在下去。”

——1965年2月，美国国务卿迪安•腊斯克致总统的备忘录说：“共产党中国声明，南越的冲突是他们认为正在向全球蔓延的‘解放战争’”。“我坚信，如果允许共产党北越统治东南亚，必将给美国和自由世界带来灾难性后果。”“我还认为，应采取一切可能的手段回击河内和越共的侵略”，甚至不惜“冒大规模扩大战争的风险”。“以谈判为掩护把东南亚拱手让给共产党北越是完全不能接受的。”“我不认为我们可以从那里退出，因为我们有条约，因为我们已经发表了许多言论。我认为抽身而退会使我们在全世界大失脸面，一想到世人的舆论我就不寒而栗。”

——1965年2月，美国开始大规模地轰炸越南北方。3月8日，美国海军陆战队在越南南方岘港登陆。美军在越人数短短数月之后已达22万。（1966年达38万。1967年达42万。1968年达52万。）“特种战争”变为“局部战争”。

——1965年5月13日，约翰逊说：“共产党中国希望战争继续下去，不管盟友支付什么代价”。约翰逊讲话后美国国防部长麦克纳马拉在美国众议院军事委员会报告说，“南越是东南亚反共斗争的基石，是中共理论的决定性考验的对象。”

——1965年8月，约翰逊在同高级幕僚们讨论是否增派10万美国战斗部队、从而接过地面战争的主要责任时说，若不如此，世界各国会说美国是纸老虎，其威望将受到无可挽救的打击，“最严重的打击是地球上最强大的国家无法打败一小批游击队”。威廉•邦迪在1967年5月说，越南战争在“亚洲人”的眼里是一块试金石，美国的失败或软弱将使他们丧魂落魄。

——美国前驻南越大使亨利•洛奇在一篇题为《我们在越南能够获胜》的文章中指出：“在越南的斗争，是战后反共斗争的一个重要环节。如果北越胜利，中国的做法就会被证明是正确的，苏联也会被迫采取更好战的立场，盟国将不再相信美国的保证，国内也将要退出世界而实行固守‘美国堡垒’的战略。美国只要坚持下去，是能够胜利的。”

——美国参议员盖耳•麦吉在国会辩论越南问题时发言说，“南越如丢失，柬、泰、马、印（尼）、菲也将丢失；美国“已投下过多的资金，不能前功尽弃”。“现在指挥中心正在转移到北京，它的手法是‘最讨厌、最肮脏、最难得出定局的游击战’，因此，“必须在东亚划一条坚定的界线并坚守之”。

——《纽约时报》军事编辑汉斯•鲍德温说：“哪怕是中共以最大的力量打击我们，我们也能在南越和老挝打赢一场朝鲜式的战争”。

——1965年11月7日，美国国防部长麦克纳马拉在给美国总统的备忘录说：“中国是威胁到我国在世界上的重要地位和影响力的一个主要国家，其组织整个亚洲反对我们的可能性虽然较小，但威胁性极大”“……长期以来，有三条防线在竭力遏制中国（另外有苏联在北方和西北方‘遏制’中国）：一、日本～朝鲜防线；二、印度～巴基斯坦防线；三、东南亚防线。”“对遏制中国之事，美国仍需继续给予关注，投入金钱，有时还需牺牲美国人的生命。”

——麦克纳马拉在回忆录《回顾——越战的悲剧与教训》中承认：

“艾森豪威尔政府全盘继承了杜鲁门政府的观点，即共产主义在印度支那的胜利将威胁到美国的安全。”“一九五四年四月，艾森豪威尔总统发表了他著名的预见，如果印度支那落入共产党人手中，其它东南亚国家也会‘紧随其后’，就像‘多米诺骨牌’一样。”

“我们——当然包括我——只能相当肤浅地理解中国的动机，错误地认为，那些好斗的言词中包含着建立地区性霸权的意图。同样，对于胡志明领导的运动，我们也完全忽视其民族主义的色彩，而将其首先视为一名共产主义者，其次才把他当作一位越南的民族主义者。”

“中国和北越的激烈言词使我们认为：他们将追求一个地区性的霸权。”

“共产党中国声明，南越的冲突是他们认为正在向全球蔓延的‘解放战争’”。

“撤离也意味着，美国在整个世界中的威望一落千丈，而共产党人对其它东南亚国家的压力，则大大加强了。最后，撤离还将意味着，全世界与西方为敌的势力将备受鼓舞，他们也会效仿越南的做法，尝试进行暴动的滋味。”

“没有人愿意讨论退出越南。我们认为那将使我们遏制共产主义在东南亚蔓延的堤坝出现巨大的裂口，这是我们不能接受的。”

“我全文引述这些段落是因为现在回头来看，它们集中体现了当时我们头脑中一种完全不正确的想法：‘中国威胁’我国的安全。”

“迪安•腊斯克、沃尔特•罗斯托和世界上许多地缘政治学家至今仍回答说值得。他们断言：如果没有美国对越南的干涉，共产党霸权——苏联和中国——将会在东南亚进一步扩张，包括控制印尼、泰国，甚至可能还有印度。”

——1965年4月18日前美国国务院顾问汉斯•摩根索在《纽约时报》发表文章《在越南我们是在欺骗自己》说，美国试图在外围对中国实行军事遏制、结果必然导致中美战争，那时美国的核力量和海空优势都不会起决定作用，势必要派几百万地面部队到亚洲去。这将是美国最大的悲剧。美国必须适应中国在亚洲的政治和文化优势；在越南达成一个保全面子的协议；同苏联暗中合作来扶植一个“铁托式”的北越或全越政府。

——1967年总统顾问阿贝•福塔斯声称，从南越撤军“这是给中国共产党人在世界上扩大影响的一剂补药，是我们在亚洲多米诺骨牌前的全面撤退。”

——美国著名的专栏作家华尔特•李普曼著文说：“根据所谓多米诺骨牌的理论，如果美国在同中国共产主义对抗的时候显示出自己是一只纸老虎，而不采取军事行动，美国就会丧失亚洲各国人民对它的尊敬和支持。自从2月以来的3个月中，我们越来越大力地运用这个理论。结果是什么呢？同预期恰恰相反：今天美国不仅是孤立的，而且遭到亚洲每个主要国家越来越大的反对。”“亚洲人民中间的所有这种日益增长的反美情绪的根源是什么呢？这个根源就是：他们认为我们在越南进行的战争是一个富有的、强大的、白种人的西方国家对一个软弱而贫穷的亚洲国家进行的战争，是西方白种人对亚洲非白种人进行的战争。”“我们可以随意大谈我们如何为越南人的自由而战斗。但是，对亚洲各国人民来说，这显然主要是一场美国人对一个亚洲国家人民进行的战争。”

……

所有这些事实确凿无疑地证明美国当初卷入越南战争确实就是冲着毛泽东来的，就是要和毛泽东“单挑”。也就是说，美国之所以陷入越南战争的泥潭，完完全全是因为毛泽东——“中苏论战”使美国认定中国是比苏联更危险的敌人，“援越抗美”使美国认定中国的的确确正在通过“人民战争”挖美国的墙角。二者合起来就使美国精英认定：美国的最高国家利益在越南的丛林中。结果：美国倾举国之力“奋不顾身”地冲进了越南战争的泥潭。

美国几十万大军陷在东南亚的沼泽水网山川丛林中尽情地、无止无休地耀武扬威却又无法自拔。苏联则趁机大举扩张。60年代末，苏联军事力量已经与美国不相上下，在全球到处挖美国墙脚。1967年，苏军进驻中东。1968年，苏联入侵捷克。勃列日涅夫提出了咄咄逼人的“有限主权论”、“国际专政论”、“社会主义大家庭论”和“国际主义义务论”。美国精英们此时此刻突然如梦方醒，恍然大悟：坏了，上当了，上了毛泽东的大当了。原来美国真正的要害利益不是在东南亚的烂泥潭里，而是在中东和欧洲；真正威胁美国利益的不是“好战”的中国，而是美国以为“可以有共同利益”的苏联。美国敢情被毛泽东诱进了越南战争的沼泽地白挨揍，如同老牛掉进井里——有力没处使，进不得退不得，眼睁睁看着苏联坐大而无可奈何。如果还不顾一切继续在越南硬抗到底，就等于自我了断，把世界霸权拱手让给苏联。不管是谁当美国总统，借他八个胆他也不敢走到这一步。

1969年尼克松上台后宣布美国从越南撤军，使战争“越南化”，通过谈判取得“体面的撤退”——不再说“打赢”而说“体面的撤退”，这实际已经是认栽了：如果能打赢还用得着谈判吗？还有什么样的撤退能比凯旋而归更“体面”呢？所谓“体面的撤退”真正含义是：不管你南越是死是活，反正我美国得走人了。我走后你南越有本事就靠自己活下去，没本事就听天由命。我真正关心的是别一垮一大片，弄得我管也不是不管也不是。只要美国脱身后只垮掉一个南越，那就谢天谢地，就算“体面的撤退”了。而要实现这“体面的撤退”，就只得求毛泽东：得绕人处且绕人，千万别我前脚走你后脚乘胜追击，来个横扫东南亚。“解铃还需系铃人”，我美国当初因为你毛泽东才掉进了越南战争的泥潭，现在只好求你毛泽东高抬贵手，让我“体面”地从这泥潭里爬出来，好全力以赴去跟苏联争个高低。

美国既然有求于毛泽东，那就不得不满足毛泽东开出的价码。最终结果：

一、美国得出结论：不要在军事上大规模卷入亚洲大陆。

二、美国重新检讨对华政策。放弃敌视中国的立场。放弃“以冷战为纲”的对华政策和理论思维方式。总统亲自出马改善对华关系。承认中国大陆的政权（从想方设法推翻的准战争状态到不承认，从不承认到最终承认）。原则上停止了直接颠覆、骚扰中国的行为，停止了对流亡的西藏叛乱分子的援助。

三、美国承认“一个中国”。承认台湾属于中国。同意废除与台湾签订的《美台共同防御条约》（1980年1月1日正式废除），停止了海军在台湾海峡的巡逻，美军撤离台湾。

四、美国解除了对中国长达二十多年的全面经济封锁禁运和外交孤立政策。

五、美国承认中国的政治大国地位。支持恢复中国的联合国席位和常任理事国地位。

六、美国采取联合华制苏的战略——这意味着美国不仅实际承认了中国大陆的政权，承认了中国的大国地位，而且更进一步，承认中国已从“前苏联阵营的一员”上升为世界力量中的“一极”，即世界政治力量的格局开始从“美苏两极世界”演变为“美、中、苏”三极的“新三国演义”（如果仅仅把中国看成世界上一个普通的大国，何须如此大费周折？）

所有这一切都在毛泽东和尼克松、周恩来与基辛格的会谈、《上海公报》和而后的中美关系发展过程中得到了体现和证实。这一切都是战胜国才能得到的东西——这才是毛泽东进行中苏论战和援越抗美要达到的真正的战略目标，才是毛泽东自建国以来一直孜孜以求的东西：使中国从美苏两大阵营的两面夹击中突出重围，彻底摆脱美苏冷战的支配，变“谁也不向、两家一块收拾你”为“谁也不向、两家一块巴结你”，使中国的战略处境从“前后夹攻”转为“左右逢源”。也就是说，根本改善中国的战略处境，捍卫中国最根本的民族利益。

今天要问越南战争的失败者是谁，几乎众口一词会说是美国——美国自己都不否认美国输掉了越南战争。但如果要问越南战争的胜利者是谁，那答案就各式各样了。有说是北越的，有说是苏联的，就是少有说是中国的——如今中国的官方“精英”对“越南战争胜利者”这顶桂冠似乎毫无兴趣，那当然怪不得别人要贪天之功为己有。然而历史自有其逻辑。美国卷入越南战争是冲着毛泽东去的，毛泽东又从头奉陪到尾。美国失败了，越南战争的真正胜利者舍毛泽东其谁耶？

这个胜利是毛泽东误打误撞凭侥幸得来的吗？如果真是这样，那美国这个世界头号超级大国也太徒有其名了，居然稀里糊涂就破了自己号称“建国二百年从无败仗”的历史记录，轻而易举就把有史以来头一个“战胜美国”的胜利桂冠拱手送给了毛泽东。世界上哪有这种美事？！这一切都是毛泽东精心策划巧妙运筹的结果，是毛泽东跟美国斗智斗勇斗力、反复较量的结果。

如前所述，冷战期间中国最根本的民族利益是摆脱冷战，打破美苏对中国的围攻。要打破美苏对中国的围攻，关键在于美国——中苏是为了美国而闹翻的：对美国对中国民族利益的侵犯，毛泽东主张坚持斗争，苏联主张中国做牺牲以适应苏联的冷战需要——中苏分裂使毛泽东可以不必再顾忌苏联，完全按照自己的判断对付美国：要打破美国对中国的围攻，就必须使美国放弃对中国的敌视。要使美国放弃对中国的敌视，就必须记住俾斯麦的名言：“当代的重大政治问题不是用说空话和多数派决议所能决定的，而必须用铁和血来解决。”也就是说，必须让美国吃个史无前例的大败仗，使美国自己得出结论：跟中国敌对没有好处，不得不有求于中国。

然而要让世界头号超级大国、号称“建国二百年从未打过败仗”的美国吃个史无前例的大败仗谈何容易？当年的德国办不到。身为超级大国的苏联办不到。处于美苏两强的前后夹攻、处于三年经济困难中的中国哪有这个力量办到？怪不得国内外当时几乎所有的“精英”都认为毛泽东是“发疯”。（中国今天的“精英”们不还在如此喋喋不休地鹦鹉学舌吗？）所有这些“精英”都是“智叟”级人物，有知识，懂逻辑，会算计，但算来算去怎么算也算不出毛泽东有任何胜利的希望——当然这也不算多丢脸：从井冈山到长征、抗日战争、解放战争、抗美援朝……所有给毛泽东“算命”的“精英”“智叟”们哪次没得出过同样结论？所以他们这一次算不出毛泽东能以弱胜强、扭转乾坤也不算太低能。

他们算不到的是：以弱胜强恰恰是游击战出身的毛泽东的拿手好戏——我弱，那就不跟你正面较量，而是设法把你引到你的强项发挥不出来的地方，使你整体虽强，但局部为弱；我整体虽弱，但局部为强。只要在局部造成如此强弱逆转之势，那胜败就由不得你了。如此持之以恒打持久战，随着时间的推移，局面就必将改观——“战略上藐视敌人，战术上重视敌人”，看透强弱的辩证关系，调动敌人为我所乘——这正是毛泽东过人之处。

毛泽东经过五十年代与美国的三次大较量（抗美援朝、解放一江山岛、炮击金门），对美国已经摸了底：美国虽强，但不是没有致命弱点：

第一，骄傲狂妄，自我迷信——世界上头号超级大国，“上帝的宠儿”，经济力量第一，军事力量第一，科学技术第一，文化优势、心理优势，世界上没有美国办不到的事。难怪肯尼迪就职演说会如此牛气冲天：“我们将付出任何代价，忍受任何重负，应付任何艰辛，支持任何朋友，反对任何敌人”——“任何”、“任何”、“任何”，没有“任何”限定词。

古人云：“骄兵必败”。美国国力再强也不是无限的。认识不到这一点而盲目妄自尊大，这正是当时美国的致命伤，为日后的失败奠定了基础。

第二，意识形态挂帅，“以冷战为纲”——美国当年把全世界简单分成非黑即白的两大类，不反共就是共产党，不承认民族主义，不承认民族独立，一切都是“共产主义全球扩张的阴谋”。中国内战是“共产主义扩张”，朝鲜战争是“共产主义扩张”，古巴革命是“共产主义扩张”，越南战争也是“共产主义扩张主义”。麦克纳马拉说：“我们对敌友分析上的失误，反映出我们完全忽视了该地区的历史、文化、人民的政治信仰及其领导人的个性特征与习惯。”“对于胡志明领导的运动，我们也完全忽视其民族主义的色彩，而将其首先视为一名共产主义者，其次才把他当作一位越南的民族主义者。”美国这样简单粗暴地对待第三世界的民族独立、民族解放运动，结果只能走到与人民战争为敌的地步。

意识形态挂帅的另一个后果是麦卡锡主义阴魂不散：当年为“谁丢掉了中国”不知整了多少人。从此谁不主张强硬、建议妥协谁就有“同情共产主义”的嫌疑。麦克纳马拉在国会流露出对扩大轰炸效果的怀疑，马上就挨了当头一棒：“部长先生，我对您的话感到异常失望。我认为它会令共产主义者们感到欣慰。这是对共产主义退让的言论，这是一种失败的言论。”结果：美国政府官员明知越南战争打错了、打不赢也没人敢反对，唯恐被戴上“谁丢掉了越南”的大帽子。

第三，唯武器论——只要武器先进、训练有素就能解决一切问题，看不到也不肯相信人民战争中人心的向背才是最关键的，持久战才是最无法招架的。因为自持武器天下第一，所以敢毫不犹豫大包大揽往越南战争泥潭里跳。

第四，包袱沉重，输不起——“历史上从未打过败仗”这一历史记录谁也不敢破。“白种人优越、不能输给东南亚‘蚂蚁之国’的乡巴佬”的自负谁也不肯破。既然是“自由世界领袖”，那就必须有威信：有“威”别人才怕，有“信”别人才跟。打了败仗就没了“威”，半途溜号就没了“信”。约翰逊说：“如果我撒手不管这场战争，听任共产党人接管南越，那么我就会被看成是一个懦夫，我的国家就会被看成是一个绥靖者，我们和我们的国家都将发现，我们在整个世界上将不可能再为任何人做成任何事情。”1965年3月下旬，麦克瑙在为麦克纳马拉起草的一份备忘录中直言不讳地分析说，美国在越南的目的70%是为了避免丢脸的失败，20%是使南越及其邻近地区“不落于中国人之手”，10%是让南越人民享有“较好、较自由的生活方式”。麦克纳马拉说：“我不认为我们可以从那里退出，因为我们有条约，因为我们已经发表了许多言论。我认为抽身而退会使我们在全世界大失脸面，一想到世人的舆论我就不寒而栗。”——如同黑社会老大，无“威”无“信”今后在道上可还怎么混？所以“面子”比天大，一旦卷入就无论如何不能容许失败，代价再大也得硬着头皮顶住撑下去。

第五，战略重点意识薄弱——在美国眼里，全世界到处都是“美国利益”。结果：美国在全世界到处设防，哪里有动静就手忙脚乱调兵去救火。面面俱到必然顾此失彼——到处都是重点结果就是没了重点。毛泽东通过1958年炮击金门已经发现了这点：美军登陆黎巴嫩，中国大陆向金门一开炮，美国就赶紧把航空母舰从中东调往台湾海峡。等弄清楚大陆并不准备攻占金门，又赶紧把航空母舰开回去。哪里吃紧往哪里跑，证明美国对哪里是要害、哪里是重点心中并无成算。这样的对手容易被调动——否则美国怎么会把越南的沼泽地当成美国的核心利益？

毛泽东不但善于知彼，更善于知己：对付美国，最有效的办法是人民战争，最有利的地方是越南的丛林——作为游击战的大行家，毛泽东非常清楚什么样的地方最不利于现代化武器威力的发挥（苏联就不管这一套，跑到中东的沙漠去跟美国和以色列比试现代化武器，结果人所共知）。胡志明领导的越南统一战争是民族解放战争，地地道道的人民战争。只要得到中国的大力援助就能够战胜最强大的敌人。中国援越抗美，选择在越南跟美国较量是“天时、地利、人和”样样俱全，决不会失败。不怕美国不来，只怕美国不肯上钩。

结果是美国非常合作地上了钩，乖乖地跳进了越南战争的泥潭。1965年中国国庆时一位西方记者如此评价当时的中国：“政府廉洁有效。外交咄咄逼人。正带着满意的心情地看着美国在越南战争的泥潭中越陷越深”。

美国为什么会心甘情愿地跳进了越南战争的泥潭？阳谋。毛泽东的阳谋——“中苏论战”+“援越抗美”。

“中苏论战”是虚招，“援越抗美”是实招。毛泽东一虚一实双管齐下，虚虚实实，真真假假，虚实结合，出神入化，在全世界眼皮底下上演了一出空前精彩的谋略大战，将美苏两个超级大国都玩弄于股掌之上，把美国这个头号超级大国的“战略思维”打翻在地，使其自己闯进越南战争的泥潭里动弹不得，最后不得不向毛泽东认栽求和。

网络小说《新警察故事》里有几段关于“阳谋”极为精彩的描述，不引用在此实在可惜了：

——“所谓阴谋就是设陷阱，就是无中生有。其中高下就看你设置的陷阱高不高明了。不过再高明的陷阱都是阴谋中的致命伤。只要让人看穿，这个阴谋就一文不值。所以说是阴谋就有破绽。而阳谋就不同了，阳谋是把一切都放在你面前的计谋。它没有隐私，没有秘密。它几乎一切都是透明的，所以它没有破绽。实施者只要把握住方向就行了。可以说它是借势而动，推动一切必然的发展而达到自己的目的。就像洪水决堤，谁都知道会死人，可是挡在它前面的还是非死不可，走都走不了。举个简单的例子，毛主席当年和蒋介石争江山，明知道毛泽东打土豪、分田地是争取民心的阳谋，可蒋介石却干看着没有办法。因为他当时照做的话只有死得更快。结果一败涂地，直接逃到台湾去了。”

——“真正最无懈可击的计谋总的一句话概括就是——你明明第一次中了计，如果再来一次的话你还是不得不往里钻的计谋。”

——“阳谋最可怕之处并不是它本身有多么复杂的策划，而是它不可猜测的方向。甚至由于它把握了世事的脉搏，所以它的去势是不可逆转的。这就是我前面说的明知道是计，即使再来一次的话，你还是不得不往里钻。”

——“阳谋就是随势而动。没势他都会去造势，来达到他的目的。”“阳谋才是真正无懈可击的计谋”。

——“阳谋，策划的滴水不漏。你根本摸不清他的底细，可以说不到事情的结局，你不知道他的目标在哪里。唉，有时候我真希望这中间有什么遮遮掩掩、改头换面的勾当，一个人活到我这个岁数最不怕的就是别人跟我耍阴谋。因为只要有和客观存在相违背的行为，就会有漏洞，可惜，所有的一切都是在阳光下进行的，光明正大。”“这就是阳谋的可怕之处了。不管是不是陷阱，你都得往里头钻。因为你不知道他的目的。正因为不知道，才会越害怕。”

对照这些来回顾回顾毛泽东当年的种种举措，就不难理解毛泽东的“阳谋”的高明和厉害。

在外行人看来，毛泽东搞中苏论战纯粹是浪费口舌，徒劳无益：能说服谁呢？说服美国还是说服苏联？凭你一面之词能让人家改变对华政策吗？（又是俾斯麦的名言：“当代的重大政治问题不是用说空话和多数派决议所能决定的，而必须用铁和血来解决。”）即便能说服若干在野的共产党人，那对改善中国的战略处境又能有多大作用？毛泽东早在《反对党八股》里就批评过“无的放矢，不看对象”的宣传，提出“共产党员如果真想做宣传，就要看对象，就要想一想自己的文章、演说、谈话、写字是给什么人看、给什么人听的，否则就等于下决心不要人看，不要人听。”既然中苏论战的长篇大论既不准备说服美国又不准备说服苏联，那又是写给谁看的呢？所以也难怪中国“精英”们现在还一口咬定毛泽东的中苏论战是“头脑发热”、“左倾冒险”、“思想僵化”、“晚年错误”等等等等。

实际呢？

五、六十年代世界上搞游击战的人多的是，美国并没有那么在意。古巴的卡斯特罗在美国的鼻子底下靠游击战打得了天下，成立了共产党政权，美国虽然也对古巴又是封锁禁运又是雇佣军入侵，但力度和决心比打越南战争差远了。为什么美国单单对越南的游击战那么耿耿于怀呢？中苏论战。不是中苏论战，美国不至于把这个问题提到战略利益的高度来对待。

对美国而言，中国1960年出版的《毛泽东选集》第四卷中最刺激的是什么？“帝国主义和一切反动派都是纸老虎”，“人民战争”、“持久战”。为什么？因为这两条直接刺疼了美国最敏感的神经：一旦被当成了“纸老虎”，谁也不买账，这个霸主还当得下去吗？美军只学过如何打现代化战争，对苏联那样的堂堂之阵胸有成竹：“大规模报复战略”。但美军还真没学过如何对付人民战争，从军事理论起就是一片空白，把人民战争视为“最讨厌、最肮脏、最难得出定局的游击战”。（美国驻越军队总司令威斯特摩兰后来回忆说，他在越南的游击战面前实在是束手无策。每天晚上，他不得不看两本书，一本是《圣经》，一本就是美国军方编印的毛泽东的英文小册子《论游击战》。）中国又出“毛选”又援越，顿时使美国感到从理论到实践都被打中了要害：“大规模报复战略”对付不了“人民战争”，普通正规军不知道如何对付“游击战”。这一下子就使美国感到自己原以为固若金汤的“遏制共产主义”的大系统原来居然漏洞百出，对苏联信心十足的东西在毛泽东面前竟然一点底也没有。“理论上讲”，毛泽东可以通过“人民战争”一块一块蚕食美国的地盘而美国却无能为力。这还不是对美国核心利益的最大威胁？这还了得？结果：肯尼迪带头学“毛选”，苦心研究如何对付“人民战争”；立即调整战略，把“大规模报复战略”改为“灵活反应战略”，特地增加“特种战争”这一项以专门对付“游击战”；公开接受毛泽东的挑战，把位于中国“前沿”、深受中国游击战影响的南越作为“特种战争”的试验场；针对毛泽东“军民关系是鱼水关系”的论述，在南越实施“战略村”计划以切断军民的“鱼水关系”；充分发挥美国的技术优势，在南越采用“直升飞机战术”以对付丛林游击战……所有这一切都发生在中国出版《毛泽东选集》第四卷和宣布承认越南南方民族解放阵线之后短短几个月的1961年，可见毛泽东这两招当真戳到了美国的痛处，确实把美国弄毛了——毛泽东的一本书、一个宣言就闹得美国鸡飞狗跳，又是调整战略、又是增添“特种战争”、又是把整个南越变成“特种战争试验场”、又是“战略村计划”、又是“直升飞机战术”……这么多、这么大的动静，换了别人能有此“殊荣”否？

（俗话说，“说话有劲不在上粪多少，文章有劲不在牛皮多少”。如今中国的那个嘲讽毛泽东“只游过江、没留过洋”的“作家将军”、“具有革新精神的解放军高级将领”、充满“先进的思想理念和前瞻性”、具有“地缘战略的眼光和独特的战争视角”的“新锐军事理论家”搞出的“现代化军事战略”及种种“特色理论”可曾让美国正眼看一下？可曾让美国也如此大动干戈？）

现在可以看出毛泽东的“阳谋”的厉害了：我一点也没有撒谎，一切都放在明处：“帝国主义和一切反动派都是纸老虎”。“人民战争威力无穷”。“支持民族解放运动，援越抗美”。这一切都光明正大，一点阴谋也没有，的的确确实心实意地支持越南统一，确实没打算在越南取得任何见不得人的好处。如果你美国不管，那越南的民族解放战争就必然取胜，自然就证明“帝国主义和一切反动派都是纸老虎”、“人民战争威力无穷”。那中国就赢得了中苏论战，顺便打掉了世界对美国的迷信和美国的霸主地位。如果你美国管，那正中下怀：正怕你不肯往越南战争的泥潭里跳呢。——如果没有中苏论战，没有毛泽东的这一整套人民战争的理论，没有中国公开的援越抗美，美国未必把越南战争看成涉及美国核心利益的头等大事，未必会不顾一切竭尽全力卷入越南战争。有了“中苏论战”加“援越抗美”，一切都改观了——所以说“中苏论战”加“援越抗美”是一个虚实结合的阳谋。这就是所谓“阳谋是把一切都放在你面前的计谋。它没有隐私，没有秘密。它几乎一切都是透明的，所以它没有破绽。实施者只要把握住方向就行了。可以说它是借势而动，推动一切必然的发展而达到自己的目的。”“阳谋才是真正无懈可击的计谋”。“不管是不是陷阱，你都得往里头钻。”“你明明第一次中了计，如果再来一次的话你还是不得不往里钻”。

如果美国没有前边所述的那些致命弱点，毛泽东的阳谋未必奏效。（但那样的美国还会那样轻率地干预中国台湾、使自己处于与中国的敌对状态吗？）然而历史就是历史。面对毛泽东的阳谋，美国的一切致命弱点的致命效果充分发挥得淋漓尽致：

1、“骄傲狂妄，自我迷信”——美国天下第一，所向无敌，岂能怕你搞什么阳谋？“我们将付出任何代价，忍受任何重负，应付任何艰辛，支持任何朋友，反对任何敌人”——你毛泽东敢在越南跟我公开叫板，我立马公开就地接招，索性就把越南当成“特种战争”的试验场，跟你当众较量——痛痛快快一下就跳进了越南战争的泥潭。

2、“意识形态挂帅，‘以冷战为纲’”——“南越是东南亚反共斗争的基石，是中共理论的决定性考验的对象。”“越南的胜利将为中国的论点提供有力的佐证，为其在世界范围内进行意识形态斗争服务”。“在越南的斗争，是战后反共斗争的一个重要环节。如果北越胜利，中国的做法就会被证明是正确的，苏联也会被迫采取更好战的立场，盟国将不再相信美国的保证，国内也将要退出世界而实行固守‘美国堡垒’的战略。”

3、“唯武器论”——你靠百姓，我靠“精英”，用“直升飞机战术”对付你的游击战，用“特种部队”对付你的游击队，我武器精良，训练有素，不可能赢不了你的土枪土炮乡巴佬……于是眼都不眨就跳进了泥潭。

4、“包袱沉重，输不起”——“撤离也意味着，美国在整个世界中的威望一落千丈，而共产党人对其它东南亚国家的压力，则大大加强了。最后，撤离还将意味着，全世界与西方为敌的势力将备受鼓舞，他们也会效仿越南的做法，尝试进行暴动的滋味。”“没有人愿意讨论退出越南。我们认为那将使我们遏制共产主义在东南亚蔓延的堤坝出现巨大的裂口，这是我们不能接受的。”“南越如丢失，柬、泰、马、印（尼）、菲也将丢失；美国已投下过多的资金，不能前功尽弃”

5、“战略重点意识薄弱”——“就美国的安全利益而言，阻止南越的丧失是头等重要的大事。”“共产主义在印度支那的胜利将威胁到美国的安全。”“如果印度支那落入共产党人手中，其它东南亚国家也会‘紧随其后’，就像‘多米诺骨牌’一样。”“一个单独在中国领导下的亚洲共产集团对美国的远东安全利益有严重影响。”

……

所有这一切综合作用的结果就是美国非常自觉地配合了毛泽东的阳谋，积极主动闯入了越南战争的泥潭，从此在里边越陷越深。

特别值得一提的是当年的美国“精英”为顺利实现毛泽东的阳谋、使美国在越南失败而做出的“特殊贡献”。

肯尼迪、约翰逊政府荟萃了一大批名牌大学毕业、学术学历资格优异的“学者型官员”、“出类拔萃之辈”（The Best and The Brightest），甚至被称为“哈佛俱乐部”。这些人用中国今天的时髦话来说就是“精英”。而这些当年的美国战争“精英”跟今天的中国改革“精英”还真颇为相似，值得不惜篇幅对照描述一番。

1、都是凭“聪明绝顶”当“精英”。

中国的“精英”张维迎号称“神童”，美国的“精英”麦克纳马拉也号称“神童”。夸耀中国“精英”“绝顶聪明”的故事满天飞，如津津有味地描述张维迎“获得伦敦经济学院Lionel Robbins纪念奖学金”（还特别注明：面向全英大学的最高奖学金，每次仅授一名）、“获得华东地区哲学社会科学优秀图书特等奖（又特别注明：仅一名）”；夸耀美国“精英”“绝顶聪明”的故事也满天飞。如《出类拔萃之辈》里津津有味地描述某“精英”中学时代的得意之笔：被老师课堂点名朗读自己的作文，于是毫不迟疑拿起本子就念，结构严谨，文笔流畅。老师正津津有味，突然发现其他同学挤眉弄眼，表情古怪，赶忙追问。同学答曰：他作文本上什么也没写，是对着一张白纸现编呢——出口成章，何等聪明。总之都靠“绝顶聪明”捞世界：“你们个人聪明的脑袋与无数颗同样聪明、充满好奇的脑袋相连接，形成了一个智慧之网。”

2、都是只管理论不管实践，只管“逻辑推理”、“想当然”而不管实际后果。

中国“精英”：“我是一个由逻辑驱动的人，好证理论道”。“如果没有了逻辑，这还是社会吗？”“学术观点通行的表述方式是‘如果…，那么…’，讲的是事物的因果关系。比如说，‘如果我们不削减政府的权力，腐败现象就不可避免。’”

美国“精英”：整个越南战争都是这种“逻辑驱动”、“证理论道”、“如果……那么”之类“事物的因果关系”等“想当然”的“逻辑推断”“推导”出来的——

“如果印度支那落入共产党人手中，其它东南亚国家也会‘紧随其后’，就像‘多米诺骨牌’一样。”“如果美国不坚决有力地在东南亚同共产主义战斗，并且取得成功，菲律宾、冲绳和台湾等海岛基地就没有安全可言，太平洋就将成为‘红色海洋’，美国就不得不退守西海岸。”“如果我们不采取足以在军事上击败北越甚至共产党中国的军事行动，则我们不能保证非共产党的南越能继续存在下去。”“如果允许共产党北越统治东南亚，必将给美国和自由世界带来灾难性后果。”“如果美国在同中国共产主义对抗的时候显示出自己是一只纸老虎，而不采取军事行动，美国就会丧失亚洲各国人民对它的尊敬和支持”……（如果、如果、如果）

战略上如此，战术上亦如此：“美国的司令官们也像许多人那样，喜欢沉溺于一厢情愿的思维之中。”“根据合理的推测……我们似乎没有理由不获胜”。“美军政治和军事领导人都想当然地认为，美军和南越军队能够迫使越共和北越正规军在战场上进行常规战争。这样，美军的机动性和强大的火力，加上空中轰炸切断来自北越的供应和增援，定会迫使他们寻求和解。如果越共和北越军队像某些人认为的那样不打常规战争，而是采用游击战术，我们认为美军和南越军队在安民计划的强有力支持下，能够进行有效的反游击作战。”“事实证明这些假定都是错的。”“我们骄傲自大，因为我们是美国人，我们是陆军士兵或海军陆战队，我们能赢。但事实证明那是错误观念”……（“一厢情愿的思维”、“合理的推测”、“想当然”）

具体的过程更充满了这种“逻辑推理”“想当然”——既然毛泽东说游击战的成败关键是“军民鱼水关系”，那“合乎逻辑”的推论就是“反叛乱”的关键是将游击队从普通村民中分开，断掉这“鱼水关系”。要把“鱼”与“水”分开，“合乎逻辑”的办法就是建立“战略村”，把全体南越农民都迁入“战略村”，这不就断了“鱼水关系”了？一连串“合乎逻辑”的结果：对全体南越农民搞“强迫搬迁”：毁了你的家园，抄了你的家产，销了你的“农村户口”，统统“进城”，搬到“战略村”去。这是“改革代价”——不，“建设自由民主新越南”的“代价”。胆敢反抗格杀勿论：“合乎逻辑”的罪名是“反对改革”——不，反对“自由民主新世界”。——这一系列“合乎逻辑”的结果是“适得其反”，“火上浇油”，“搬起石头打自己的脚”，激起了越南人民更激烈的反抗，“特种战争”彻底破产。

3、都是顽固不化，死硬到底

中国“精英”：改革出问题是因为改革措施不彻底，必须深化改革。美国“精英”：战争没取胜是因为战争升级不到位，必须加速升级。

中国“精英”：“那些批评骂我的人，他的道德连我一个脚后跟都没有！”美国“精英”：“谁说撤军只配坐着撒尿！”（即娘们）

中国“精英”：“倒退没有出路”。美国“精英”：“我不认为我们可以从那里退出，因为我们有条约，因为我们已经发表了许多言论。我认为抽身而退会使我们在全世界大失脸面，一想到世人的舆论我就不寒而栗。”“美国已投下过多的资金，不能前功尽弃”

中国“精英”：“不争论”。美国“精英”：“没分歧”。（记得1965年面对国内一片抗议，约翰逊告诉记者：美国社会对美国卷入越南战争没有分歧，只对具体做法有不同见解。《人民日报》就此发表了方成的一幅漫画，还配了一首打油诗，开头几句是：“下有天，上有地，月亮落东日出西。示威抗议遍全国，美国国内没分歧。任何国家任何人，谁都不准有怀疑！君不见腊斯克发脾气，向舆论表示感激。白宫官员忙着向指责道谢，高兴得有点歇斯底里……”）

4、最后都顶风臭十里

讽刺美国“精英”的书《出类拔萃之辈》（The Best and The Brightest，直译为“最优秀和最聪明的人”，用中国现在的时髦话说就是“精英”）在美国大受欢迎，几十年畅销不衰。麦克纳马拉在回忆录一开头也承认：“这些人——‘最优秀和最聪明的人’（后来我们发现这种称谓具有讽刺和贬低之意）”。可见“精英”、“学者型官员”、“聪明绝顶”、“哈佛俱乐部”这些东西在美国早臭了。“精英”这个词在中国现在同样臭不可闻，也算“国际接轨”——见识了中国“精英”的德行，就不难明白为什么《出类拔萃之辈》在美国如此受欢迎了。看来“‘精英’不是好东西”还真是个规律，不分国家文化背景，“放之四海而皆准”，“英雄所见略同”——不，人民所见略同。

有人说毛泽东一边“中苏论战”一边“援越抗美”是同时向“两强开战”，是“冒险”、“孤注一掷”、“冒核战争风险”，实际呢？

恰恰相反。正是“中苏论战”+“援越抗美”才使中国不但有惊无险，而且稳操胜券。

毛泽东通过五十年代跟美国的屡次较量已经发现，美国对中苏的战略不管是“遏制”也好，“大规模报复”也好，“灵活反应”也好，连同整个“冷战”在内，基本思路就是个“守势战略”：既要打仗又怕死，能不直接上阵就决不上阵。只要自身不受到攻击就不主动进攻。“中苏论战”开始时，美国认为这是两个共产党巨人在争论用哪种方法搞共产主义，对中苏的分裂高兴还来不及，生怕一不小心做出使这两家和好的举动。当时赫鲁晓夫虽然跟中国闹翻了，但还不敢公开走得太远。美国唯恐如果直接攻击中国会反而逼得中苏和好，再加上抗美援朝的教训记忆犹新，美国不想冒这个险，只敢在南越舞刀弄枪搞“特种战争”。而中苏论战的核心是中国指责苏联背叛马克思主义，对美国搞投降。这种指责本身就使苏联清楚中国没打算和美国联手对付自己。如果放着越南不管却跟美国伙在一起收拾中国，就没法证明自己是“正统马列主义者”和“国际共产主义运动的领袖”，所以既下不了决心也没有借口立即进攻中国。

“中苏论战”+“援越抗美”其实是一箭双雕，一下子同时戳到了美苏两家的痛处：美国苏联都是在自己阵营里当老大的主，最怕的是镇不住台。美国惟恐被看成“纸老虎”而众叛亲离，决心不让南越垮掉，马上跳进了越南战争的泥潭，从此越陷越深。“特种战争”一输美国登时急眼了，不顾一切扩大战争轰炸北越。这下苏联也坐不住了：袖手旁观、任凭美国肆意欺负“社会主义大家庭”的成员北越，那“龙头老大”的面子何在？威信何在？那还不众叛亲离？还保得住“社会主义阵营领袖”的地位？于是不得不援助越南对抗美国。而且为了证明自己才是正牌的社会主义阵营的盟主，不但援越，而且专给中国当时给不了的先进武器如导弹、飞机等等。——抗美援朝时中国的先进武器都得自己花钱向苏联买，买回来自己学着使用，然后再自己费尽心血送上前线去拼命。现在倒好，毛泽东一个“中苏论战”就让苏联一个子不要还卯着劲地白给，给的还净是当时中国给不了的好玩艺，还不劳中国人冒险，由老毛子亲自出马送货上门把着手教越南人使用，或者直接派人操作——这等于无偿帮着中国实现“让美国吃个史无前例的大败仗，使美国自己得出结论：跟中国敌对没有好处，不得不有求于中国”的战略总目标。这下中国可省大发了：有人心甘情愿倒贴着白帮忙还不用领情——我不谢你，你也不觉得是在帮我，连“聒噪”两字都省了，代价不过是“中苏论战”的一通笔墨官司——世界上还有比毛泽东的这招阳谋更巧妙更合算的买卖吗？苏联这一上劲，美国更不敢无限制扩大战争了：要扩大，是扩大到中国还是扩大到苏联？结果：战争一直老老实实局限在越南，使越南战争变成了一场符合毛泽东理想的时间、理想的地点、理想的方式的理想的人民战争，没有扩大到中国。毛泽东巧妙地利用了美苏矛盾，限制了战争扩大，争取了时间，使中国得以加速备战、加快“两弹一星”、开展三线建设，使自己的安全有了切实的保障。

毛泽东的阳谋——“中苏论战”+“援越抗美”对美国来说如同斗牛士的红幡，就那么三晃两晃便引得美国如同红了眼的蛮牛，一头撞进了毛泽东为它选好的战场；对苏联来说则如同赶牛鞭子，就那么轻轻一扬便鞭策得苏联格外卖力，为毛泽东实现根本的战略目标——使中国摆脱美苏冷战支配——而使劲拉犁。

中国抗美援朝是被动出战，一切不由己，时间、地点、作战方式全是被动的。援越抗美则是中国主动出击，一切自己作主，完全按中国的胃口选择时间、地点、作战方式。抗美援朝时中国被逼上了第一线，直接承担了巨大的人员伤亡。援越抗美时中国除了高炮部队、工程部队外基本处于二线，伤亡比抗美援朝小得多，而战果却大得多：在越南给美国办了个“思想改造学习班”，专门改造美国社会的“冷战思维”、狂妄自大和反华意识：只要你坚持“以冷战为纲”，坚持目空一切不认输、死要面子活受罪，坚持敌视中国，坚持“中国威胁论“，那你就必然心甘情愿乖乖呆在越南尽情用脑袋撞墙，直到你“思想改造”成功、放弃那些立场为止。而苏联也非常配合，及时抓住这个机会全球到处挖美国墙脚，用实实在在的行动从反面教训美国：到底谁才是美国利益的真正威胁。美国硬着头皮死死撑了几年，最后实实在在撑不住了，终于大彻大悟，彻底认栽，决心改弦更张，从越南战争脱身。

1969年中苏边境冲突后苏联领导人试图联和美国一同袭击中国。这反而帮了中国一个大忙：打掉了美国对根本改变对华战略的最后一点顾虑，促使美国下定决心，改变对华战略。美国尼克松政府此时已经明白对美国根本利益的真正挑战来自苏联，已经决心从越南战争脱身，已经明白美国在越南真正的对手是中国——没有中国在政治、军事、经济、交通、后勤、人员等方面的全力支持和“不准美军越过北纬十七度线”的警告，贫穷落后的北越根本撑不下去，十个武元甲也抵挡不了美国的五十多万如狼似虎的现代化军队的进攻和空中的狂轰滥炸。美国要从越南“体面地撤退”，就不能不求助于毛泽东，就不得不改善对华关系，就不能不走联华制苏的路子。但美国又担心中苏会重归于好，让美国竹篮打水一场空。中苏在珍宝岛武装冲突，苏联试探与美国联合袭击中国，这等于向美国证实：中苏同盟关系不会再恢复，中国不会再向苏联“一边倒”。美中苏的关系不再是两极而是三极。三角政治的规律立刻开始发挥作用：美中苏三家中，中国最弱。正因为如此，美苏两家最关心的都不是中国目前会威胁自己，而是不要把中国推向对方，或被对方一口吃掉，尤其不能陷入跟中国的长期冲突消耗自己的实力，让对方坐收渔翁之利的情况。所以苏联一定要拉上美国一起对中国下手而不肯自己单干。美国则立即打消了最后一丝顾虑，马上通知苏联：美国认为中国的安全涉及美国的国家利益，警告苏联不要对中国下手，并开始认真设法改善对华关系——这意味着毛泽东的阳谋成功了：中国被美苏两强任意支配的战略处境已经改变，三角政治的规律已经起作用，毛泽东追求的“打破美苏两面夹攻”的战略目标已经成功在望。

尼克松访华意味着毛泽东的阳谋大获全胜：美国彻底改变对华政策，从敌视走向缓和。这也意味着整个美国社会对华认识都被毛泽东彻底改造了：在毛泽东的“越南战争思想改造学习班”学习及格，准予毕业。郑必坚跑到美国苦苦哀求美国人“换一种思维、换一种胸襟、换一个角度”，“研究一下中国共产党与已经解体的苏联的共产党之间的区别”。其实哪用得着他脱裤子放屁？毛泽东几十年前早就做到了——尼克松访华本身就证明美国对中国和苏联的“根本区别”一清二楚，否则何必那么积极跑到没有外交关系、相互敌对几十年的中国来？正因为毛泽东把整个美国社会的对华认识都彻底改造了，所以尼克松访华消息一宣布，美国社会一片叫好：“美国国会参众两院专门通过一项联合决议，要求规定1972年2月21日为支持尼克松访华的纪念日。美国新闻处的电报称，尼克松访华受到‘美国人民压倒多数的支持。两党所有的政治领袖实际上都和尼克松总统一样，具有同中国重新建立联系的愿望。’”——如果美国社会对华的主流意识没扭转过来，像郑必坚那样只知道围着少数几个美国“精英”打转，即使能改变个把官员的对华态度又有什么用？当年美国驻延安观察组的人如谢伟思等向美国国务院如实反映了中共实情，结果还不是都被清洗了？同样让美国人认识到中国和苏联的区别，毛泽东用的是“越南战争思想改造学习班”。结果：美国总统亲自访华——到一个没有外交关系、敌对隔绝了二十二年的国家来谈和平，并同意了中国政府的要求：有史以来破天荒头一次，在中国领空上美国总统不乘坐美国总统专机而乘坐中国飞机。不仅如此，尼克松访华是单方面访问，没有回访——也就是说，不对等。（按中国的老习惯，对此是什么个说法？——“来朝求和”。）而郑必坚呢？七老八十了还梳妆打扮送上门去发公嗲、卖老骚、吊洋膀子、撒媚娇：“面对这样的中国共产党，美国有什么可以担心的呢？”结果呢？“热脸贴上个冷屁股”——人家答曰：“中国有人认为，强调经济增长和增强民族主义可维持共产党的一党统治。这是危险的，也是错误的。”——相比之下，谁伟大？谁令人作呕？

毛泽东的阳谋——“中苏论战”+“援越抗美”是有史以来最精彩绝伦的谋略杰作。美国号称战无不胜，打遍天下无敌手，偏偏两次在亚洲跟毛泽东交手，两次都栽了大跟头，而且一次比一次惨：朝鲜战争开了个先例：“第一次没有取得胜利”。但美国好歹保住了南朝鲜半壁江山，还可以勉强用“没有失败”来自慰。而越南战争则连这样聊以自慰的借口都没捞到，完完全全彻彻底底地失败了。朝鲜战争还可以推说中国有苏联为后盾，越南战争则连这样的借口也找不到，完全是毛泽东的杰作。越南战争使美国有史以来第一次尝到了战败的滋味：经济衰退、沮丧迷茫、信心危机、国内矛盾激化、社会动荡不安……一切战败国的特征几乎都占全了。美国建国两百年，什么时候吃过这么大的亏？尤其令美国精英们憋气的是：明明知道这一切都是毛泽东干的，偏偏还没法报复。鲁迅说：“譬如一个人，自己打自己的嘴巴，心平气和，被别人打了，就非常气愤。”——如果承认美国这场史无前例的惨败是因为上了毛泽东的大当，那就属于“被别人打了，就非常气忿”，必定群情激愤，坚决要求追究责任。那样一来谁也承担不起这战败侮国之责。况且毛泽东的阳谋的特点就是毫无隐瞒，一切都放在明处，是你自己心甘情愿往陷阱里跳，能怪得了谁？所以美国只好说是“历届政府的错误”导致美国陷入了越南战争的泥潭，你错我错大家都错，一推六二五，“老虎吃天——没处下嘴”，最后不了了之——这就是“自己打自己的嘴巴，心平气和”——美国连败于毛泽东都不敢承认，那还有什么理由报复中国？如果中国跟美国打堂堂之阵，打不过不说，牺牲无算不说，即便打赢了，也得防备美国会卷土重来变本加厉地报复——第一次世界大战的战败国德国不就是个例子？二次大战后德国被分割占领，目的不就是防备复仇主义东山再起？这条中国能学吗？而毛泽东的阳谋却让美国吃了亏还有苦说不出，根本不存在报复的问题。整惨了你，还用不着担心你报复，不但一点后遗症没有，还让你从此不得不心甘情愿地跟我套近乎——世界上还有比这干得更漂亮的活吗？

还不止于此呢。毛泽东的阳谋让美国史无前例地吃了个大败仗。这意味着什么？意味着中国打赢了一场“隐形世界大战”，而且自己还几乎没怎么流血。美国压倒一切、举世无双的优势居然毫无用武之地，战死五万，伤残无数，耗费无数，费尽九牛二虎之力却一败涂地，而且输得莫名其妙：打赢了每一仗，却输掉了整个战争。而中国付出的代价呢？援越200个亿，算上战略佯动——援助阿尔巴尼亚200个亿，总共耗费400个亿。援越部队有伤亡，但比抗美援朝伤亡小得多。就中国的国力而言，这一切代价的确不小。但用400个亿加这些伤亡打败了世界头号超级大国、彻底改善中国的战略地位，打破了美苏的围堵，使中国从此成为世界大国，成为“三角政治”的“世界一极”，扫清了阻挠中国大崛起的最后的外在障碍。这样一算账，中国赢了还是亏了？跟这个大帐相比，后来越南跟中国闹翻对中国虽然不是好事，但二者哪个更值？（为什么有人一提援越抗美就只看得见中越闹翻这个战争后果而看不见中美接近、中国变成“世界一极”这个战争后果呢？）苏联第二次世界大战牺牲两千万、物质财产损失不计其数才当上“世界一极”。德国打了两次世界大战，牺牲无算、费尽九牛二虎之力仍然没当成“世界一极”。日本更是“偷鸡不着赊了米”，没捞着“世界一极”还吃了两颗原子弹。中国以弱胜强赢了一场“隐形世界大战”，成了“世界一极”，伤亡代价不但少于上述任何一个国家，而且还既无外债又无内债，以至于中国老百姓都不知道自己是生活在“隐形世界大战”中——这水平世界上还有第二家吗？尽管德国日本经济实力比中国强得多，但仍算不上“世界一极”，因为它们属于美国阵营。而中国当时虽然实力弱得多，却硬成了“世界一极”，凭的就是政治上跟美苏谁也不尿，自成一家。想想1945年的中国是什么个地位，想想1949年的中国是个什么地位，再看看尼克松访华后中国又是个什么地位，谁能否认毛泽东彻底改善了中国战略地位？看看建国后毛泽东经手的几场对外战争：抗美援朝、中印边界自卫反击战、援越抗美、中苏边界冲突、西沙海战——每打一仗，中国的国际地位就稳步上升一级，一次都不例外。中国就这么从“任人宰割”一步一步上升为“世界一极”。而其他一些国家呢？两伊打了那么多年，中东打了那么多年，不知付出多少代价，打出了什么名堂没有？“不怕不识货，就怕货比货”。这一比就能看出毛泽东的阳谋有多了不起，毛泽东有多了不起。

毛泽东的阳谋的胜利不仅仅是有形的，并不仅仅是根本改善了中国战略地位，更深远的意义是让西方精英对中华文明从此刮目相看，由轻蔑转为敬畏；使中国人对中华文明的信心倍增，极大地提高了中华文明的“软实力”和凝聚力。

这种改变在尼克松访华中体现得淋漓尽致：“尼克松来华途中路过关岛时，透过媒体表示，他期望同毛泽东主席和周恩来总理的谈话从哲学的角度来进行，而不是只集中讨论眼前的问题。”“我之所以这样说，是因为读了主席的诗词和讲话。我知道主席是一位思想深刻的哲学家。”——尼克松不是学哲学的。身为美国总统，越南战争就够他焦头烂额的了，加上欧洲、中东……全世界不知有多少麻烦让他手忙脚乱，每日每时不知道有多少事等着他急办。在这种情况下，他却要花整整一周，不远万里跑到没有外交关系、互相隔绝、相互敌对了二十多年的中国来，特意提到毛泽东的诗词，而且还专门想跟毛泽东谈哲学——怎么那么闲情逸致？难道尼克松真那么悠闲？开玩笑。谁不知道美国人最讲究实际，哪肯为不着边际的事浪费这么多时间？何况还是美国总统？

真正的含义是：第一，美国明白在越南战争的真正对手是中国——如果对手是北越，美国与北越正在巴黎会谈。如果对手是苏联，那尼克松直接访问苏联就是了。无论是两种情况的哪一种，尼克松都没必要绕个大圈子跑到没有外交关系的中国来。第二，尼克松和基辛格真正明白了毛泽东的阳谋的厉害：美国跟中国主要不是在较量实力，而是在较量谋略。而与谋略关系最密切的不是兵力兵器导弹飞机，而是哲学、文化、文明体系等精神因素。

基辛格也许是当时美国为数不多的能不从字面上理解毛泽东的人。

比如，1970年毛泽东发表了《5·20》声明，谴责美国入侵柬埔寨。“读过毛泽东的声明后，尼克松愁眉不展，满腹心事，以为刚见缝隙的中美关系的大门，又将重重封闭，自己为此所作的努力，将要付之流水。他心烦意乱，立即让基辛格研究毛泽东的声明，基辛格很快便送来自己的见解和分析：‘实质上，……那是一篇非常空洞的声明。……它没有提出什么威胁，没有承担什么义务，对你没有进行人身攻击，在有争议的双边问题上避免表态。从策略上看，毛的声明是要达到这么几个目的：利用你在柬埔寨的行动大肆宣传。以毛的个人威信加强中国人对西哈努克的支持。’”

同样的东西在肯尼迪政府的“出类拔萃之辈”们眼里是“中国共产党人对美国的极端敌视”、“中国人正在提倡以更好战更咄咄逼人的政策反对西方，特别是美国”、“中国和北越的激烈言词使我们认为：他们将追求一个地区性的霸权”，而基辛格却能看出这许多别人看不出的东西，坚持改善中美关系的既定方针，可见他确实领悟了毛泽东的阳谋。明白这一点，也就比较容易理解毛泽东会见尼克松时的这一段谈话了：

毛泽东用手指着基辛格说道，“‘只争朝夕’。我觉得，总的说来，我这种人说话像放空炮。比如这样的话：‘全世界团结起来，打倒帝国主义、修正主义和各国反动派，建立社会主义。’”

“像我这种人”，尼克松说，“还有匪帮，都在打倒之列吗？”

毛泽东微笑着说：“你，作为个人，也许不在被打倒之列。”接着，他指向基辛格说：“他这个人也不属于被打倒之列。如果你们都被打倒了，我们就没有朋友了。”

表面上看，这是在开玩笑。而我理解的更深一层的含义是：双方都清楚，阳谋是虚实结合。虚的部分可以是“放空炮”，也可以是当真的。你不跟中国作对，那虚的就始终是虚的，就成了“放空炮”。但你如果跟中国作对，那虚的随时可以变成实的，叫你吃不了兜着走，如援越抗美。毛泽东实际当面告诉尼克松、基辛格：既然你们改变对华关系了，那我那虚的部分就是“放空炮”了。——这正是尼克松、基辛格最想知道的底，也正是他们对毛泽东最感到神秘的地方：如此虚虚实实、真真假假、变化莫测、出神入化的谋略到底是从哪里来的？西方的哲学体系里找不到答案，古老的东方哲学体系如孔孟之道里似乎也没见识过。在这样的谋略面前，美国最自傲的、对付苏联行之有效的种种战略理论体系似乎简直不堪一击，轻而易举便被毛泽东玩得团团乱转找不到北，输都不知道怎么输的——像美军在南越，打赢了每一仗，却输掉了战争。这些在美国历史上从来找不到先例，在欧洲战场从来没见识过，在军事科学理论上无论如何也解释不通的东西，碰到毛泽东却成了活生生的现实。这才是令美国人最迷茫的地方。要论物质实力，美国对中国实在没什么可担心的，也并不太放在心上，以至于跟毛泽东周恩来谈不谈都无所谓。正因如此，尼克松才对跟毛泽东谈哲学有那么大兴趣——这样的谋略课世界上没第二家，没第二次机会，也永远不会有不走样的教科书和学习辅导材料——无论从回忆录上看还是从纪录片上看，尼克松、基辛格在毛泽东面前简直带了点学生般的表情。难怪基辛格会感慨：“我从来没有遇见过一个人像他具有如此高度集中的不加掩饰的意志力。”“他身上发出一种几乎可以感觉到的压倒一切的魄力。毛泽东的确能让人体会到力量、权力和意志的共鸣。”——如果仅仅为了取悦于人以利谈判，有必要事后这样说吗？

这说明了什么？说明美国最高级谋略家对毛泽东的谋略五体投地，钦佩之至。这背后的含义呢？现代史上第一次，代表西方文明的最高级精英在代表东方文明的最高级精英面前服软认输：我服了你。对你的谋略我甘拜下风。对能产生这种谋略的古老的中华文明我不由自主肃然起敬。美国军人说：“美国不怕中国军队现代化，就怕中国军队毛泽东化”——过去一般人总是从战略战术、战斗意志等纯军事方面来理解。实际这句话的含义已经超越了纯军事范围：越南战争之后，毛泽东的阳谋才是令美国军队最敬畏的，这是任何最现代化的电子计算机也算不出来的，永远不知道如何应付的。毛泽东的阳谋使中国人终于能够扬眉吐气地宣告：中华文明不仅不比西方文明差，而且有自己独到的优势，能令最傲慢的“西方文明优越论者”俯首称臣。不信？看看毛泽东的阳谋。看看越南战争。

重复一遍一开始的话：“衡量冷战期间一切中国领导人历史功过的唯一标准，就是看其是否解开了这个死结，是否粉碎了美苏为自己的冷战需要而牺牲中国民族利益的一切举措，是否让中国从美苏两大阵营的左右夹击中突出了重围。一句话，是否使中国摆脱了冷战。做到了这条的就是捍卫了中华民族最根本民族利益的英雄”。尼克松访华标志着毛泽东终于实现了1949年以来孜孜以求的“使中国摆脱美苏冷战的两面夹击”的战略目标。就凭这一条，就可以说毛泽东是中华民族有史以来最了不起的民族英雄。——不要以为民族英雄是只会吃苦牺牲、视死如归的“拼命三郎”。不要以为中国只有失败的民族英雄。中国不仅不乏成功的民族英雄，而且有“善战者，无赫赫之功”、“苟能制侵陵，岂在多杀伤”的智勇双全的高级成功的民族英雄。毛泽东的阳谋不动声色便将实力远远超过中国的超级大国玩弄于股掌之上、让中国人不知不觉间便打赢了一场“隐形世界大战”、让中国以最小的代价在战略上彻底翻身、一举去除对中华民族根本利益最大的威胁、使中华文明在“全球化”的世界大放异彩，空前地提高了中华民族的凝聚力、自信心和自尊心。毛泽东不仅是中华民族的民族英雄，而且是古往今来独一无二的最伟大的民族英雄。


** 高手过招

只有理解了毛泽东的阳谋，才能够理解并欣赏尼克松访华时中美两国顶级谋略高手直接交锋过招的精彩之处。

片段一：“维护中国的独立及其生存能力”

1972年1月3日，美国总统国家安全事务副助理亚历山大•黑格准将率先遣组来到北京，为尼克松的中国之行作技术安排。黑格此行带来了尼克松和基辛格的重要口信：由于苏联企图继续包围中国，美国对中国的生存能力表示怀疑，准备力图抵消苏联对中国的威胁，以维护中国的独立及其生存能力。希望通过这次访问，加强尼克松总统的世界领袖的形象。

毛泽东得知黑格口信后说：“包围中国！要他们来救我，那怎么了得！顶回去！无非尼克松不来。不来就不来嘛！22年不来了，再等22年。尼克松不来，土克松、砖克松也会来。”

毛泽东批准的中方答复说：“我们认为，任何国家决不能靠外力维护其独立和生存，否则只能成为别人的保护国或殖民地。……事实已经证明并将继续证明，一切妄图孤立、包围、遏制、颠覆中国的阴谋都只能以可耻的失败告终。”“美方口信表示，期望通过访问，加强尼克松总统作为世界领袖的形象。对此我们难以理解。一个人的形象取决于他自己的行动，而不是任何其他国家。我们从不认为有什么自封的世界领袖。”

当中方把答复稿念给黑格后，黑格脸上一阵红，一阵白，说：“我是个军人，可能我没有正确地转达尼克松总统的意思。”

评论：这一段实在精彩。表面看，美国人真是一片“好心”：“对中国的生存能力表示怀疑，准备力图抵消苏联对中国的威胁，以维护中国的独立及其生存能力”。代价呢？条件不高，一个子不要，只希望来点“面子工程”：“通过这次访问，加强尼克松总统的世界领袖的形象”。——给尼克松一点“世界领袖形象”就能解除中国的后顾之忧，不用再为“生存能力”、为苏联的大兵压境犯愁。这买卖太合算了。换上认实惠、“拎得清”、“逮住耗子就是好猫”的主早喜出望外一口答应了。然而实际呢？这等于承认美国是“世界领袖”，宣布中国是美国的“保护国”，等于中国“改换门庭”，从苏联阵营跳槽到美国阵营了——从向苏联“一边倒”改为向美国“一边倒”。这样一来，“向美国一边倒，苏联要收拾你”的规律立刻就会起作用：苏联将马上感到最敏感的“柔软腹部”遭到了来自中美的直接军事威胁，必定采取激烈的反措施。那时中国能指望美国什么？起码眼前亏吃定了。更进一步说，中国建国以来费了那么大心血，为的是什么？是从美苏冷战夹攻中突围出来，两方谁也不依附，自成一家。只要中方在这个问题上一松口，立刻前功尽弃，平等关系变成了不平等的保护国关系，三角政治的格局就算吹了，利用美苏矛盾确保中国安全的整个战略目标就算吹了，胜利者一下子变成了失败者——一言之差，天壤之别。美方实际想摸一下毛泽东的底：你争的究竟是“世界一极”还是眼前利益？同意跟我和解是因为要自成一家还是因为惧怕苏联？如果是因为受不了苏联的威胁而不顾一切，那给你点甜头就行了，在台湾问题和其他问题就可以强硬一些了。而这么重大的话题尼克松不出面，基辛格不出面，却让一介武夫黑格出面，显然为了留有余地便于下台阶，一旦被拒绝可以往底下推：“我是个军人，可能我没有正确地转达尼克松总统的意思。”如果是尼克松基辛格出面，那被中国一口拒绝就太难堪，搞不好会危及整个访华计划。可见这是美方一个精心准备的圈套。结果被毛泽东一眼识破，马上做出最强硬反应：宁可你尼克松访华取消，我也绝不答应。——什么叫高手，这就是高手：要害问题心中有数，明察秋毫，绝不含糊，寸步不让，根本不为眼前小便宜所动。美方的圈套水平高，毛泽东的眼力决心更高。尼克松人没到就先亲自领教了毛泽东的厉害，不但再也不提这个话题，而且小心翼翼多了。这次过招的结果：尼克松摸到了毛泽东的底，也向毛泽东漏了自己的底：出了这个插曲之后尼克松仍坚持按计划访华，可见决心之大，可见美国有求于中国之迫切。这等于反过来告诉中国：不用担心美国死不让步。这就为后来的联合公报奠定了基础。

片段二：起草《联合公报》

基辛格：按国际惯例，强调含糊其辞的共同点，用陈词滥调掩盖着分歧。毛泽东：各说各的，明确写出双方的分歧，同时写出双方的共同点。

基辛格：“在美国总统历史性的访问结束之时，列举双方这么多的不同观点，这岂不等于告诉全世界，中美双方在吵架么？！这无论在国际上，还是在国内都是难以接受的。”

周恩来：“你们的初稿是伪装观点一致，我们认为公报必须摆明双方根本性的分歧。众所周知，中美在意识形态、社会制度和国际重大问题上存在严重分歧，20多年的隔阂不可能消失于一旦，如果在此情况下双方签署那种既不说真话、也不打算遵守的陈词滥调式的文件，那是不可取的。”

基辛格：“我们不回避双方的分歧，签公报又有什么意义？”周恩来：“用漂亮的外交辞令掩盖分歧的典型公报，往往是‘放空炮’，是祸根。公开地摆明分歧，就是解决问题的开始，也是通向未来的第一步。”

结果：

基辛格：“也许用这种别出心裁的方式，可以解决我们的难题，这就是中方草案的奇妙之处。”洛德：“周恩来太厉害了！让我们否定了自己的方案，接受了他们的方案，而且高高兴兴，心悦诚服……”

评论：如果按照美方的方案搞出个“强调含糊其辞的共同点、用陈词滥调掩盖分歧”的符合“国际惯例”的公报来，那对于中国来说尼克松算是白来了：就算中国浑身是嘴，也没法让全世界相信中美之间是平等关系、中国与美国没有结盟、美国不是中国的保护国、中国没有与美国搞秘密交易、没有出卖别人的利益。美国可以对中美关系做随心所欲的解释放风，在中苏之间来回拨弄。毛泽东的使中国独立于美苏两强之外的战略总目标仍然实现不了。而按中国的办法搞联合公报，则用最明确无误的方式宣告中美之间关系改善但不是同盟关系。防止了美国利用措辞模糊的公报在中苏之间搬嘴弄舌，防止了苏联误判中美结成军事同盟而铤而走险，防止了第三世界国家误解中国。总之不给任何人留下任何猜测怀疑挑拨离间的机会，不让毛泽东利用美苏矛盾确保中国安全的“三角政治”战略目标受到任何可能的干扰。这才是最高明的做法。

片段三：正面交锋（毛泽东会见尼克松）

毛泽东：“我认为，一般地说来，像我这样的人放了许多空炮，比如，全世界人民团结起来打倒帝国主义、修正主义和一切反动派，建立社会主义。”毛泽东还说：“你（指尼克松，作者注）可能就个人来说，不在打倒之列。可能他（指基辛格，作者注）也不在内。都打倒了，我们就没有朋友了嘛。”

基辛格的理解：毛泽东说自己“放空炮”，实际上是在暗示，不要认真看待中国到处墙上写着的喊了几十年的口号，“中国领导人在和我们打交道时已经超越了意识形态。他们实际上是同我们订了一个无形的互不侵犯条约，从而解除了一个方面的敌情。”

评论：前面已经说过，阳谋是虚实结合，可以是“放空炮”，也可以是当真干。既然美国的对华战略从敌视变为和解，那原来实的就成了虚的，变成了“放空炮”。让毛泽东转实为虚的代价：美国人认同“订了一个无形的互不侵犯条约，从而解除了一个方面的敌情。”——阳谋厉害不厉害？

尼克松：“……究竟怎样好，是要日本处于中立和不能自卫的状态，还是在一个时期内让日本同美国具有某些关系，这都是属于哲学范围的问题。……总理指出，他感到美国在伸手，苏联在伸手，那么问题是，人民共和国面临的危险，是来自美国的侵略，还是来自苏联的侵略？这是一个困难的问题，但是我们要讨论这个问题。”

毛泽东：“来自美国方面的侵略，或者来自中国方面的侵略，这个问题比较小，也可以说不是大问题，因为现在不存在我们两个国家互相打仗的问题。你们想撤一部分兵回国，我们的兵也不出国。”“我们也不威胁日本和南朝鲜”。毛泽东坚持美国只有同台湾断绝所谓“外交关系”，中美才可能建立国家间的外交关系。在涉及中国主权的原则问题上，毛泽东寸步不让，毫不妥协。

基辛格的理解：毛泽东虽然没有公开承诺，但却有着明显的暗示，而正是这个暗示，“消除了美国两届政府的噩梦，害怕中国会武装干涉印度支那。”他说，对毛泽东这句话的前半段，“通过排除法，显然说明苏联是毛泽东在安全方面主要担心的对象。”在保证中国不会到国外进行军事干涉以及谈到日本和南朝鲜时，毛泽东是在告诉我们，北京不会对美国的主要利益提出挑战。

评论：尼克松费了那么大劲访华、改变对华战略，为的就是毛泽东的这句话：“现在不存在我们两个国家互相打仗的问题。你们想撤一部分兵回国，我们的兵也不出国。”——你美国可以“体面地撤出”越南了。中国不会出兵横扫东南亚。不会站在苏联一边跟你美国交战。也不会对美国的主要利益提出挑战。——美国耗费几千亿、几十万大军、无数人力物力在越南拼死拼活了好几年都得不到的东西，毛泽东一句话就解决了。代价：中国成为“世界一极”。台湾问题。撤消封锁禁运。联合制苏……

毛泽东得到了中国需要的一切。作出的让步是什么呢？严格讲，零——没有牺牲中国的主权。没有在台湾问题上做任何妥协。没有出卖越南或其他任何国家的利益。答应美国人的都是中国本来也要干的，比如不向苏联“一边倒”、反对苏联的霸权主义、“不称霸”、不出兵侵略别人、不干涉其他国家内政、不输出革命（但并不是说不保留支援民族解放运动的权利）。美国从毛泽东那里得到的实际只是一种保证——阳谋中化实着为虚着的保证。

谁说毛泽东不懂经济？世界上还有谁能做出这种比毛泽东的阳谋更厉害更精明的买卖？

回顾这最精彩的一幕，回顾这一幕的前前后后和来龙去脉，令人不禁感慨：毛泽东不是神，只是比神还神。



** 阳谋的副产品——猴与猪

毛泽东的阳谋产生了两个副产品：一猴一猪。

美国在越南战争吃了大亏之后得了“越南战争恐惧症”，听到“人民战争”、“游击战”这几个字就心惊肉跳，避之不及。1975年北越大举进攻，南越土崩瓦解，拼命向美国呼救求援。美国答曰：越南战争对美国来说已经结束了。美国再也不会管越南的事了。越南遂统一。1979年伊朗爆发伊斯兰革命。伊朗国王巴列维向美国求救。美国吭都不吭一声，听任美国的这个“铁杆盟国”轰然垮台。美国驻伊朗的外交官被绑了票，美国束手无策，一筹莫展。这一时期美国在全球处于守势。苏联却从越南战争尝到了甜头壮了胆，全球到处插手：中东、阿富汗、安格拉、埃塞俄比亚、索马里、也门、格林纳达、葡萄牙、支持印度肢解巴基斯坦、支持越南占领柬埔寨、挑衅泰国、苏联海军进驻越南金兰湾……（说来也好笑，中苏闹翻本来是因为苏联要和，中国要斗，现在却来了个大颠倒：苏联跟美国斗上了瘾，逼美国与中国加速缓和）苏联的咄咄逼人把美国逼急了，顾不上再拖延观望，终于兑现了向毛泽东的承诺，对台湾撤军、废约、断交，与中国正式建交——正式形成了中美苏三角关系，宣告毛泽东的阳谋终于大功告成。（如果当时毛泽东健在，“与台湾关系法”能出笼吗？毛泽东的阳谋把两个超级大国耍得像猴，“与台湾关系法”则把某些中国人耍得像猴：你抗议美国向台湾卖武器，人家说这是国会通过的法律，行政部门管不了，你找国会去。你当真去找国会，人家说这是民意，我没办法。你游说民意，人家马上大做文章，又是“干涉内政”又是“政治献金”……团团转了半天只能干瞪眼，比被耍的猴还狼狈。中美关系如同一桌盛宴，毛泽东又备料又下橱忙活了半天，正要端上桌不幸去世了。有幸坐享其成的只需把这桌现成的饭菜往嘴里一送就成——就连这点能耐都蹩脚，又是掉筷子又是流哈拉子的，愣是把毛泽东辛辛苦苦做成的极品佳肴弄变了味——没办法，伟人就是伟人，小人就是小人。）

苏联垮台关键原因之一是陷入阿富汗战争泥潭。陷入阿富汗战争泥潭是因为错误地总结了越南战争，以为自己才是越南战争的胜利者：什么毛泽东的阳谋、人民战争、游击战，全是瞎吹。起决定作用的是我的先进武器和“社会主义”旗号。只要在“社会主义”旗号下出兵，不论到哪里都无往而不胜。前苏联领导人在毛泽东的阳谋面前脑筋如猪——一点不开窍。结果：大举入侵阿富汗，闯进了另一个人民战争的泥潭。（越南领导人脑子同样进了水，自以为越南战争胜利是自己的本事，在毛泽东的阳谋面前同样如猪，所以大举入侵柬埔寨、跟中国闹翻。）

列宁说：“战败的军队善于学习。”美国输了越南战争，却知道了毛泽东的阳谋的厉害，知道了向毛泽东学阳谋。难怪美国的谋略水平从此大有长进，一反越南战争以前呆板僵硬的守势防御那种消极战略，开始以积极主动的姿态搞战略了。美国也学着像毛泽东的阳谋那样搞虚实结合，放弃了过去非黑即白的以“反共”为唯一标准的敌我划分法，代之以虚虚实实的“人权”“民主”战略：你听我的，我对你“人权”、“民主”的要求就是虚的，睁一只眼闭一只眼，一切好说好商量；你不听我的，我对你“人权”、“民主”的要求就是实的，横挑鼻子竖挑眼，鸡蛋里边挑骨头，发动“颜色革命”。俄国熊不知死活地闯进阿富汗，美国大概连做梦都能笑出声来：老天有眼，可轮到你来尝尝人民战争的滋味了。于是照葫芦画瓢模仿毛泽东的援越抗美，来了个援阿抗苏，把当年自己在越南吃足了的苦头照样送给了苏联。虽然这其实只是毛泽东的阳谋的“盗版”，苏联也照样吃不消，在阿富汗抗了十年之后终于也像当年的美国一样撑不下去，不顾一切夺路而逃。然而为时已晚，经济实力不如美国的苏联已经承受不起，从此一蹶不振了。

美国很善于举一反三：既然越南战争中本国决策层的“精英”能给国家带来这么大的祸害，那为什么不把这变成一种克敌制胜的武器，想方设法让敌对国家的决策层也来上一堆这样的“精英”？于是：“基金会学者”、“休克疗法”、“颜色革命”……结果：最现代化的导弹核武器、成千上万亿美元、“遏制战略”、“大规模报复战略”、“灵活反应战略”、“军备竞赛”等等倾举国之力费尽九牛二虎之力得不到的东西，花几个小钱雇几个“精英”鼓噪一通“民主”“自由”就办到了：苏联解体。冷战告终。中国从此彻底摆脱了冷战的威胁。

美国学毛泽东的阳谋开了窍，搞垮了苏联，赢得了冷战，乍一看似乎是“青出于蓝”，实际却是“画虎不成反类犬”——阳谋变成了阴谋。如前所述：“所谓阴谋就是设陷阱，就是无中生有。其中高下就看你设置的陷阱高不高明了。不过再高明的陷阱都是阴谋中的致命伤。只要让人看穿，这个阴谋就一文不值。所以说是阴谋就有破绽。而阳谋就不同了，阳谋是把一切都放在你面前的计谋。它没有隐私，没有秘密。它几乎一切都是透明的，所以它没有破绽。实施者只要把握住方向就行了。可以说它是借势而动，推动一切必然的发展而达到自己的目的。”美国搞垮苏联用的净是阴着、损着：收买、误导、欺骗……这一切越不过这一条：“再高明的陷阱都是阴谋中的致命伤。只要让人看穿，这个阴谋就一文不值”。幸亏当时苏联有一帮“基金会学者”与美国里应外合，愣是没让猪脑子的苏联领导人看穿，使美国计谋得逞。但是阴谋毕竟是阴谋。俄国人并非都是猪脑子。虽然当时上了当，事后仍然明白过来是被耍了。俄国人尽管嘴上不讲，但心里有数，这股子仇恨就别提了。美国对此当然心知肚明，一清二楚。冷战都结束了，苏联都解体了，俄罗斯已经算“民主国家”了，美国为什么仍然不依不饶接二连三下狠手，又是“颜色革命”又是“车臣独立”地不放过俄罗斯？就是怕俄国人有机会东山再起来报这一箭之仇。万一有那么一天，谁知道俄国熊的报复会有多狠？——这就是阳谋和阴谋的根本区别：搞阳谋成功了没有后遗症，不存在对方报复的问题。搞阴谋即便成功了也得时时提心吊胆，堤防对方报仇雪恨。（中国的改革“精英”虽然“骗出一个制度来”，但从此不得不时时担心受害者的报复。所以他们也同样必须“一不做，二不休，不把中国彻底搞垮就不能安心，就如同美国不把俄罗斯彻底搞垮就不能安心一样。）美国学阳谋学来学去只学了个皮毛，所以说美国在毛泽东的阳谋面前如猴——会模仿，但掌握不了精髓。

冷战怎么结束的？苏联崩溃了。苏联怎么崩溃的？中了美国的计谋。美国哪来的计谋？模仿毛泽东的阳谋。如果没有毛泽东的阳谋呢？继续如同越南战争之前那样，靠“遏制”、“大规模报复战略”之类蛮牛功夫硬顶。结论：结束冷战，毛泽东的阳谋功不可没。中国彻底摆脱冷战，多亏了毛泽东的阳谋。

** 今天来自昨天

1、不温故则不知新

毛泽东已经逝世了。冷战已经结束了。一切似乎都那么遥远了。现在还提毛泽东时代干吗？

因为今天来自昨天。中国今天的一切都从毛泽东时代奠定的基础上发展而来。不正确认识毛泽东时代，就不能正确认识今天的一切，就一切皆错，就要出大乱子。

比如：

——改革开放谁的功劳最大？毛泽东。道理很简单：改革开放的前提是和平。如果处于“战争状态”或“准战争状态”，就不是开放不开放的问题，而是“开门揖盗”或“开城投降”的问题——列宁格勒被德军团团围困时能“开放”吗？你一“开放”，德军马上冲进来按希特勒的命令把这座城市从地球上“抹掉”。只要战争没结束，你“开放”个试试？同样，当美国根本不承认中国政府、公开宣布要颠覆这个国家时，你能“开放”吗？就算你“开放”，人家还“封锁禁运”呢。——记得1962年《人民日报》登了条新闻：美国禁止加拿大从中国进口的酱油对虾过境。《人民日报》为此还配了首打油诗：“酱油对虾过境，美国政府不准。奇闻轰动加拿大，讽刺外加责问。若问对虾罪状，实在清楚得很：头脑一热便赤化，可见思想不稳。至于酱油其人，更是红得发紫。出场便能闹革命，由此可定罪名。铁幕高悬白宫，将军草木皆兵。如此封锁禁运，世界史上笑柄。”——封锁禁运得如此严厉，还想“开放”？如果不是毛泽东带领中国人民自力更生艰苦奋斗二十多载，使美国认识到对中国封锁禁运只能事与愿违，如果不是毛泽东用阳谋、出奇计逼美国有求于毛泽东而不得不解除禁运，如果不是毛泽东使中国彻底摆脱了冷战、赢得了和平的大环境，困在美苏两霸的夹缝中动弹不得的中国怎么“开放”？“开放”个屁！

历史的回声中，只有克劳塞维茨的声音最清晰：“你想和平吗？那么你就准备战争吧！”毛泽东的“准战争时代”换来了今天的和平环境。这个和平环境批准了今天的“改革开放”。可见中国今天的一切积极成就实际都不过是毛泽东挣来的“和平红利”，是毛泽东的阳谋的“胜利果实”。不承认这个，就叫“贪天之功为己有”。就叫“杀良冒功”。

——“制止台独”，得谢谢毛泽东用阳谋破使美国改变了对华政策。如果没有毛泽东迫使美国承认“一个中国”，同意废除“共同防御条约、从台湾撤军、与台湾断交，那么今天的台湾会是个什么状况？陈水扁会如何？还会不会有中国的“反分裂法”？

——“招商引资”，得谢谢毛泽东前后花十三年之久彻底清剿了国内千年未绝的匪患：如果中国还是遍地土匪横行，谁肯来投资？

——“出口创汇”、“国际接轨”、“全球化”，得谢谢毛泽东的普及教育：中国如果还像1949年以前那样77%的人是文盲，你能按国际标准迅速地、大规模地、保质保量地生产出口产品吗？

——中国与非洲的经济关系突飞猛进，得谢谢毛泽东的非洲政策：没有毛泽东时代打下的基础，今天中国人能说“五星红旗就是我的保镖”吗？——毛泽东在中华民族的根本利益上从来高瞻远瞩，没有走过废棋，更没有走过臭棋。

……

2、驳谬论种种

——“毛泽东时代生活苦。如今生活好。”

毛泽东时代是“准战争年代”。如今是和平年代。用和平年代的生活水平嘲笑战争年代本身就是一种卑鄙。没有毛泽东的战争胜利，哪有今天的一切？何况今天中国许多“弱势群体”的生活水平未必比毛泽东时代的普通老百姓强到哪里去。

——“毛泽东时代什么东西都买不到。如今什么东西都买得到”。“毛泽东时代买什么都凭票。如今什么都不凭票了。”

第一，战争年代凭票供应再正常不过。

第二，正因为有毛泽东时代的“凭票供应”，才会有今天的“不凭票供应”。这是毛泽东时代“凭票供应”换来的“胜利果实”。

举例：中国目前每年粮食总产量约4.69亿吨，总消费4.9亿吨，缺口2100万吨靠进口。如果中国仍处于被封锁禁运的状态，那这2100万吨就进口不成。那现在也照样得“凭票供应”。今天的“不凭票”是因为能进口。能进口是因为毛泽东的阳谋胜利迫使美国解除了对中国的封锁禁运。毛泽东的阳谋能取胜是因为毛泽东时代的中国人民跟随毛泽东，自力更生，艰苦奋斗，默默承受了“凭票供应”之类的苦难。毛泽东时代的“凭票供应”换来的是真正的独立自主：谁也休想用封锁禁运来左右中国的内外政策。中国人根本用不着看外国人的脸色行事。中国想发展什么武器，想搞什么工程，想上什么项目，想惩罚哪些内奸，不管哪个国家都无可奈何，最后的结论是封锁禁运得不偿失。结论：不能再对中国搞全面的封锁禁运。——毛泽东时代的“凭票供应”换来了今天的“不凭票供应”，不折不扣的“前人吃苦，后人享福”。毛泽东时代的中国人民都是英雄。今天的人有什么资格用“凭票供应”之类来嘲笑他们当年的奉献呢？

毛泽东时代根本不指望任何大规模外援。那时虽凭票供应，但供需平衡是真的，不含任何水分。现在呢？靠外债，靠内债，靠投资，靠卖资源，靠卖环境，靠卖苦力，靠卖血汗……用这一切跟毛泽东时代的“既无外债，又无内债”、计划平衡相比，谁有资格嘲笑谁？

第三，今天的“不凭票供应”未必靠得住。比如石油，一旦发生战乱，一旦被封锁，一旦国外供货短缺，马上就会供不应求，马上就会“凭票供应”。那时还有资格以汽车之类奢侈品为例来炫耀现在的生活比毛泽东时代强吗？

（这种假设可不是杞人忧天。如果中国内部矛盾危机激化而又无法解决，那保不定就有人需要用战争来转移视线了。台湾的陈水扁似乎也巴不得打起来，以便解脱困境。“你有情我有意”，说不定就撞到一起了——如果能一举收复台湾，一切内部矛盾都能得到缓解：没说的，统一了国家的就是民族英雄。民心民望一下就上去了。其他一切也都好办了。但如果不能迅速解决问题，那就得点有长期战争的思想准备了。——总不能为一时的挫折就放弃国家统一大计吧？那时还能嘲笑“毛泽东时代一切凭票”吗？）

用“毛泽东时代生活苦。如今生活好”、“毛泽东时代什么东西都买不到。如今什么东西都买得到”之类指责毛泽东，这叫“打井的有罪，吃水的有功”——“打井的有罪”：光付出没水吃。“吃水的有功”：不付出就有水吃——这是什么逻辑？又好比修青藏铁路，前人逢山开路，遇水搭桥，一切都就绪了，偏偏只剩下最后几公里铺轨的时候去世了。最后的铺轨、剪彩、通车等荣誉全由别人完成。你能说这条铁路跟前人没关系，全是最后剪彩的人的功劳吗？

——“毛泽东时代把富人都打倒了，结果就变成穷人国了”。“清算富人的结果是大家一块儿受穷，社会上再也没有富人了”。

这是无耻的诈骗。

“富裕”之“富”与“富人”之“富”根本不是一回事。一个社会可能人人都“富裕”，但不可能人人都是“富人”。

“富裕”含有“收入能够满足合理的生活需要”的意思。度量的标准是自己的收入与自己的需要相比满足程度如何，与奢侈和攀比无关，是一种客观而理性的度量。一个人是否算“富裕”与其他人是否算“富裕”无关，因此能够做到整个社会人人都“富裕”，即“小康社会”或“富裕社会”。

“富人”不仅含有“收入远远超过合理的生活需要”的意思，而且含有“收入远远超过其他人”的意思，度量的标准是奢侈和攀比：不穷奢极欲不能算“富人”。收入不让别人望尘莫及不能算“富人”。因此“富人”的标准是个无底洞，永无止境。凭这一条就可以知道，一个社会能当上“富人”的永远只能是极少数。说“穷人都能变成富人”是弥天大谎。

靠工资吃饭能做到“富裕”，但做不成“富人”（那些能自己给自己开工资的特殊“老总”不算）——要让打工族凭工资收入变成“富人”、达到奢侈和别人望尘莫及的水平，这工资该给多少？怎么核算？如果对人人都这么发工资，恐怕早破产了。——可见“富人”决不能单靠工资吃饭。单靠工资吃饭的决当不了“富人”。

“富人”基本都是“老板”，至少能自己给自己开工资。“富人”都是自己给人开工资（包括给自己开工资），而不是由人给自己开工资。所以“富人”手下无“富人”：让你们都达到“奢侈”，钱给光了恐怕都不够。那我呢？也就是说，“富人”的手下只能是“打工族”，每个富人必然对应着一群“富不了的人”——也就是说，一个人当了“富人”，至少有一群人就决当不了“富人”。凭这一点就可以说，要走“富人”之“富”的“先富带后富”没门。

亚当·斯密说：“哪里有巨大的财富，哪里就有巨大的不平等。有一个巨富的人，同时至少有500个穷人，少数人的富有，必定是以多数人的贫困为前提。”——对亚当·斯密在《道德情操论》里的这一论断，“主流经济学家”们决不肯引用，更不会放进“大国崛起”。他们大肆吹捧亚当·斯密的《国富论》，赞扬那只“看不见的手”，因为他们是专门用这“看不见的手”“捞世界”的“三只手”。——所谓“学术道德”、“学者的良知”不过如此。

公有制都是靠工资吃饭。既然靠工资吃饭可以实现“富裕”，那就是说，靠公有制为主、私有制为辅便能够做到人人“富裕”。这就是说，“富裕”之“富”与公有制不矛盾。也就是说，以公有制为主、“节制资本”可以做到整个社会人人“富裕”。这种“富裕”之“富”是没有穷人、没有“富人”、大家都“富裕”的“富裕社会”（或曰“小康”）。

既然靠工资吃饭当不成“富人”，那么要走“富人”之“富”就只能靠私有制，而且是大规模、无限制的私有制——规模小了不行，受到制约了不行，个体户、小业主、小老板那样小打小闹的顶多达到“富裕”，当不成“富人”。只有达到“富得流油”、“富可傲人”、“穷奢极欲”的水平才有资格当“富人”。“富人”之“富”只能允许少数人当“富人”——“富人”与“穷人”是对立统一：没“穷人”何谓“富人”？有“富人”就必有“穷人”。每造就一个“富人”就必然剥夺一群穷人“富裕”的机会。假如现在农民收入一万元就算富裕，那么每多一个亿万富翁就意味着剥夺了一万个农民富裕的机会。也就是说，“富人”之“富”必然导致社会两极分化。一旦走上“富人”之“富”的路子，阶级分化、社会分化、矛盾激化等等客观规律就必然发挥作用。这一切是不以人们的主观意志为转移的，也是任何花言巧语都掩饰不了的。

“富裕”之“富”与“富人”之“富”，一个容得公有制，一个容不得公有制，截然相反，水火不容：有“富裕”之“富”就没有“富人”之“富”，有“富人”之“富”就没有“富裕”之“富”。中国一旦走上“富人”之“富”就休想做到“全民富裕”。想靠“富人”之“富”实现“全民富裕”是“缘木求鱼”。把“致富”之“富”解释成“富人”之“富”是弥天大谎，是极其阴险卑鄙的理论诈骗。

茅于轼主张“为富人说话，为穷人办事”、“富人得到保护，穷人才可能变富。如果打倒了富人，这个国家就没有富人了，就变成穷人国了！”、“张维迎是非常同情穷人的”——真正同情穷人是使天下无穷人，即：认同既无“穷人”又无“富人”的“共同富裕”之“富”。只要认同“富人”之“富”，那就是认同制造穷人。茅于轼故意把人们引导到该如何对待“富人”与该如何对待“穷人”这一话题上。只要争论起该如何对待“富人”和“穷人”，那就已经中招了：因为这个话题的逻辑前提是认可“致富”之“富”乃“富人”之“富”。就这一下便足以使人不知不觉把既无“穷人”又无“富人”的“共同富裕”排除在外，忘掉这条规律：有“富人”就不能有“共同富裕”，有“共同富裕”就不能有“富人”。

那么西方国家为什么能既有“富人”又能大体上实现“富裕社会”呢？

因为一直有像中国这样的傻B在“舍己为人”地给“补贴”——乖乖迎合人家制定的“游戏规则”去“全球化”、“国际接轨”：中国每创造100元财富，人家就拿去99元，（足够人家补贴出个“富裕社会”了）。中国剩下的这一元，九毛九归“富人”，留给“打工族”一分钱养家糊口。口口声声“按经济规律办事”的中国“主流经济学家”们既不碰那99元，也不碰那九毛九，而是专打这最后的一分钱的打主意，整天琢磨如何再扣掉几厘以“降低成本”、“提高利润”，告诉“打工族”：只有把你们的“一分钱掰两半”，“贡献”给“富人”一半，你们将来才能当上“富人”，这叫“先富带后富”。

为什么人家能从中国拿走那99元？因为这是人家的“规矩”——比方说，你造裤子质量再好也只能卖10元。同样的东西人家贴上自己的商标牌号就能卖200元。人家什么也不花费，就凭这牌号赚死你。因为这是人家说了算的“全球化”，只认人家的牌子。挣钱得按人家的规矩办，花钱也得按人家的规矩办，甚至不花钱也得按人家的规矩办：辛辛苦苦挣了点钱，然后呢？还得听人家的：买美国国债？存美国银行？买美国股票？人民币升值？房地产投机？一大堆规矩，一大堆陷阱，叫你没钱头疼，攒了点钱照样头疼。虽然外汇储备世界第一，却左右为难，花也不是不花也不是，动不动就赔上千亿——挣钱、花钱、存钱、玩钱的规矩全是人家定的，主动权全在人家手里，不管你怎么跳都跳不出人家的手掌心。人家管着规矩，有票子占你的便宜，没票子还占你的便宜。你欠他的时候你吃亏，他欠你的时候还是你吃亏。他可以打白条、印票子、金融风暴、贬值赖账随心所欲，哪种情况都吃不着亏，而你哪种情况都占不着便宜——明白西方国家是怎么实现又有“富人”又有“富裕社会”的了吧？中国有人给这种“全球化”的“补贴”吗？就凭那可怜的半文钱，能实现“富裕社会”吗？

让一个社会“人人富裕”行得通也做得到。让一个社会人人“富人”则行不通也做不到：逻辑混乱不说，社会承受不起。地球承受不起。西方国家有“全球化”的“补贴”，才能既有“富人”又有“富裕社会”。中国在“全球化”中只有“补贴”别人的份，没人来“补贴”中国，所以中国没办法实现既有“富人”之“富”又有“富裕社会”。有“富人”之“富”就没有“共同富裕”之“富”。有“共同富裕”之“富”就没有“富人”之“富”。只有把“致富”之“富”解释成“富裕”之“富”才能坚持公有制为主，才能实现整个社会和谐富裕，才能避免走向社会分化、矛盾对抗。把“致富”之“富”解释成“富人”之“富”则必然摧毁公有制，必然实现无制约的私有制，必然造就大批穷人，必然造就贫富对立，必然导致社会贫富两极分化，必然分裂社会，必然引发越来越激烈的阶级斗争，最后必然形成对抗性矛盾。

只要不是贪官，从理论上讲不管官多大也只能靠工资吃饭。一个社会如果推崇“富人”之“富”，那只靠“死工资”吃饭的就会被视为“次等”，当官的也不例外。作为离不开“威信”二字的官员，手里有权而又低人一头，这能让人心理平衡吗？在这种大环境下能保持心理平衡、无动于衷的能有多少？而“富人”既成了社会的主流，你能指望他们当真尊重只靠工资吃饭的人吗？不管是部长省长还是司令政委，在“富人”眼里都不过是挣工资的“打工族”、自己做不了自己的主的一类。“富人”尽管为了需要可以花高价向官员行贿购买权力，但心里明白：这跟花钱买娼妓没什么两样。也就是说，在一个推崇“富人”之“富”的社会里，单纯靠工资吃饭的官员是被瞧不起的：社会主流——“富人”从心里瞧不起他们，只是利用他们。他们要保持心理平衡就只有三种选择：1、坚持操守，无动于衷。2、也当“富人”——既当官又当“富人”。既然只靠工资吃饭就当不成“富人”，那就只有利用权力贪赃枉法。3、我当不成“富人”也不会给你好气受，有机会就利用手里的权力给你点颜色，叫你不敢小瞧我。——不管怎么“制约权力”，你也没办法制约这“心病”。——“心病还须心药医”。这种“心病”在“共同富裕”的社会中就不存在：大家志同道合，地位相当，平等相处，没什么想不开的。所以推崇“富人”之“富”的社会想让权力机构清廉有效、平等尊重“富人”与其他人几乎是不可能的，杜绝贪污受贿和滥用职权也几乎是不可能的。

把“致富”之“富”解释成“富人”之“富”说穿了是为了自己当“富人”，为自己一家子巧取豪夺找根据。一个说：“以私有化为纲”。一个说：“资本家代表‘先进生产力’”。一个说，要学会“科学”地压榨，不要“杀鸡取卵”、“竭泽而渔”、一锤子买卖，而要“细水长流”、“可持续剥削”、世世代代不断线。“三结合”到一起，就凑成了一个完整的“体系”——绝对排斥毛泽东思想的“私有化特色理论体系”。

整个毛泽东时代都处于“准战争年代”，在没有取得“隐形世界大战”的胜利、冲破冷战的包围、为中国创造出和平环境之前，无法把“富裕”提上日程，所以老百姓的日子相对而言确实较苦。但那是战争年代的那种每个人都不可避免的必须的苦，是战争的代价，也是战争胜利的需要——如果战争年代的中国出现了“富人”，那才岂有此理呢——但毛泽东时代坚持走的路是“共同富裕”——“富裕”之“富”。只要在冷战结束和平来临后按照这条路继续走下去就必然是人人“富裕”——没有“富人”，但也没有穷人，更不是“穷人国”。——茅于轼说“打倒了富人就只剩下穷人”，这是玩弄文字概念游戏故意骗人。只有“富人”之“富”才会有穷富对立，非此即彼，非“富”即“穷”。“共同富裕”之“富”就不存在“不富即穷”。

——“你们想倒退回到毛泽东时代”

毛泽东时代分两部分：已经经历了的和尚未来得及经历的。前一部分是“准战争年代”，后一部分是“共同富裕年代”。前一部分是后一部分的必要准备。所谓“倒退回到毛泽东时代”只能是指已经发生了的那部分，即“准战争年代”。平白无故让和平年代的人过战争年代的生活，当然谁也不会愿意。但人们的主观愿望是一回事，事物的客观发展规律则是另一回事。如果将来某一天中国被迫处于战争状态，那就不是愿意不愿意的问题，而是愿意也是那样，不愿意也是那样。在那种情况下，是愿意象毛泽东时代那样人人平等、齐心协力、为一个共同的目标而努力奋斗，还是愿意象国民党时代那样“前方吃紧、后方紧吃”、贪污横行、物价飞涨、多数人饥寒交迫、流血拼命而少数人作威作福大发战争财、国难财、人命财？让你吃苦流血拼命以便让别人躲在一边享福敛财，你愿意不愿意？那时还会说“你们想倒退回到毛泽东时代”之类的讽刺话吗？

既然口口声声“你们想倒退回到毛泽东时代”，那就是说不愿意回到“毛泽东时代”已经发生过的那部分了。也就是说，不愿意中国处于战争年代或准战争年代了。但坚持“富人”之“富”已经使中国社会贫富剧烈分化，社会矛盾持续激化，正走向全面对抗。各种利益集团无视国家利益，肆无忌惮内外勾结祸国殃民。“政令不出中南海”，各路诸侯自行其是，对中央阳奉阴违。“人权高于主权”意识大行其道。民族凝聚力遭到越来越严重的破坏。如果一意孤行，沿这条路一直走到黑，那社会撕裂、国家分裂、爆发内战是免不了的。那时就只能靠毛泽东的一套来收拾残局了。这不反而实现了“回到毛泽东时代”了？主观上拼命想避免的东西客观效果上却是在为其变成现实而创造条件——这就叫“适得其反”，这就是历史的辩证法。

只有按毛泽东的主张，坚持公有制为主、私有制为辅，认同“富裕”之“富”而不认同“富人”之“富”，那才能避免中国社会的崩溃，自然也就不存在“倒退回到毛泽东时代”的问题。——不是“倒退回到毛泽东时代”，而是“前进走向毛泽东时代”——走向当年的“毛泽东时代”尚未来得及实现的那部分：“共同富裕”。



** 驳对毛泽东的三大诽谤

1、反右

反右是个什么性质的问题？

时代背景：1957年。“准战争年代”。美国的封锁禁运包围之中。四年前的1953年，朝鲜战争刚刚结束。三年前的1954年，美蒋签订了“共同防御协定”，宣布不承认中国政府的存在。杜勒斯拒绝在日内瓦会议上与周恩来握手。美军长期进驻台湾。两年前的1955年，中国解放一江山岛后，美国通过“授权总统在台湾海峡使用武装部队的紧急决议”即《福摩萨决议案》。美国参谋长联席会议命令战略空军指挥部“以紧急情况为基础”，开始为大规模使用核武器攻击中国大陆选定目标，对中国搞核讹诈。一年前的1956年，苏共二十大否定斯大林。中苏分歧开始。匈牙利事件爆发。国内剿匪尚未完成。——总之是不折不扣的“战争大环境”。

右派的核心主张：

——“党派轮流执政”。

——“各党派通过竞选轮流执政，共产党下台不等于蒋介石回来。”

——“党天下是一切宗派主义的根源。”“最近大家对小和尚提了不少意见，但对老和尚没有人提意见”。

——“一个上帝，九百万清教徒（那时党员数），统治着五亿农奴”。“非造反不行”。

——“到现在再来提人民内部矛盾问题，足证共产党统治中国这几年到处都是错误。”

——“大家要联合起来。匈牙利人民的血没有白流！我们今天争到这一点小小的民主，是和他们分不开的！”

——“中国应分成两半，以长江为界。长江以南归蒋介石领导，以北归共产党领导。让任何一国援助共产党，让美国援助蒋介石，双方竞争。”

……

结论：“准战争年代”。美国的核讹诈阴云未散，一年前“匈牙利事件”血迹未干。公然闹着让共产党下台——大敌当前窝里反，这叫什么？这叫政变。这就是问题的性质：战争期间的政变。

且看这一段文摘：“对于中国新政权到底‘能撑多久’，1949年秋美国国务院情报分析司曾经做过一次估计，得出的结论是，中共政权在未来五年内没有被推翻的可能，但是，内部困难和外部压力会使中共政权大大削弱，从而为其在将来的某个时候垮台准备条件。”

按美国国务院1949年的估计，美国的封锁禁运将为中共政权在五年之后“将来的某个时候垮台准备条件。”1949年的“五年之后”是1954年——离1957年只差三年，正属于美国人估计的“五年之后的某个时候”这一期间。也就是说，右派的政变正发生在美国人预期的时间内。美国人的结论：美国当初的预计准确。美国对中国的封锁禁运有效。共产党政权即将垮台。结果：坚定了美国通过封锁搞垮中国的决心和信心，加紧封锁。后果：增加中国饥荒年代的困难。

有人说：不对，右派在是帮共产党整风。是你共产党让党外人士帮助共产党整风提意见的。

这就如同展销会闹成了哄抢案：警察立案不立案？拘捕不拘捕？让你来参加展销，没让你来聚众抢劫。你能说因为一开始是你让我来的，所以你无权拘捕我？你能说抢着东西的是少数，所以其他参与起哄推挤的人就不能算涉案？

战争时期闹政变，该如何处置？

当初国民党是如何对付共产党的？“宁可错杀一千，不可漏网一人”、“杀绝共产党”——那时共产党还不肯抓枪杆子，还避免闹暴力。4·12发生地上海并没有什么工农“过激行动”。共产党正跟国民党并肩战斗闹北伐，没有提出要国民党下台。一句话，国民党是因与共产党政见不合，立刻动了刀子。

如果共产党也按国民党1927年对付自己的手段来对付1957年的右派政变，那会如何？——既然是“准战争年代”，那完全有理由以“紧急状态”为根据“军法从事”。——毛泽东这样做了吗？

有人连篇累牍说共产党如何如何残暴，右派家属如何如何受牵连，如何如何受到非人待遇，等等。

——先看看杨开慧亲属的这段回忆：

“在毛泽东被宣布是公众敌人时，他的妻子留在家中，拒绝逃跑，因为她认为自己并没有涉入政治，不应为丈夫的行为负责。她的审判只是形式，甚至连死刑都不是由法官宣判，而是由省主席何键直接下令。刽子手并没有让她迅速死亡，她身负枪伤，倒在地上挣扎。后来处理遗体的人发现，她手指甲里全是泥土。”

评论：右派家属遭到过这种待遇吗？

——再看看斯诺的《西行漫记》里这段对徐海东的采访：

我想大概也是由于这个缘故，我听到徐海东回答我的“你家里的人现在哪里？”时，不禁突然感到很大的兴趣，连忙坐直了身子。他若无其事的回答，显然没有准备，使我不能不怀疑这是实话。

“我家的人全都给杀了，只留下一个哥哥，他现在四方面军。”

“你是说在打仗的时候打死的？”

“哦，不是！我的哥哥只有三个是红军。其余的都是汤恩伯和夏斗寅将军枪决的。国民党军官一共杀死了徐家六十六个人。”

“六十六个人！”我几乎不相信自己的耳朵。

“是的，被杀的有我二十七个近亲，三十九个远亲——黄陂县的人都姓徐。老老少少，男男女女，甚至婴孩都给杀了。姓徐的都给杀光了，除了我的妻子和三个在红军的哥哥，还有我自己。后来两个哥哥又在作战时牺牲了。”

“你的妻子呢？”

“我不知道她的下落。一九三一年白军占领黄陂县时她被俘。后来我听说她被卖给汉口附近的一个商人做小老婆。这是我逃出来的哥哥告诉我的，还有其他人被杀的事。在第五次围剿中，徐家有十三个人逃出黄陂，到了礼山县。但是在那里都被逮捕了。男的被砍了头，女人小孩被枪决。”

徐海东看到我脸上吃惊的脸色，就惨然一笑。“这没有什么特别的地方，”他说。“许多红军指挥员家里都发生了这样的事，只是我家损失最大而已。蒋介石下了命令，我的家乡被占领时，姓徐的一个也不能留下。”

……

我们必须记住，现在大家都已知道，在第五次反共围剿中，国民党将领在许多地方下令要杀光全部老百姓。这被认为是军事上的必需，因为蒋总司令在一次演讲中谈到，凡是苏维埃政权久已确立的地方，“是分不清赤匪和老百姓的”。这种杀光的办法在鄂豫皖共和国执行得特别凶残，主要是因为有些负责剿共的国民党将领是本地人，是被共产党没收了土地的地主的儿子，因此报仇心切。在第五次围剿结束时，苏区人口减少了六十万人。

……

“到一九三三年十二月，”徐海东说，“整个鄂豫皖有一半已成一片荒地。在这一度富饶的地方，留下房子极少，牛都被赶走，土地荒芜，白军占领的村子无不尸积成山。湖北有四个县，安徽有五个县，河南有三个县都几乎完全破坏。东西四百里，南北三百里之内，全部人口不是被杀光就是给迁空了。”

……

评论：“不比不知道。一比吓一跳”。在如此事实面前，咒骂毛泽东对右派“残暴”、“株连家属”的哭天抹泪是不是有点太软弱无力、太虚伪了？

“伤痕文学”总是一把鼻涕一把泪诉说右派们是多么的善良，多么的无辜，多么的“无害而可怜”。然而文学中的优美进了现实就未必了。说“无害而可怜”，一旦大权在握立刻凶相毕露，“铁面”、“铁腕”砸“三铁”：“减员增效”、“下岗分流”、“买断工龄”、“国有企业重组”、“出卖国企”、“医疗产业化”、“教育产业化”、“住房商品化”、“MBO”、“扩大内需”、“公务员加薪加薪再加薪”……“改革代价论”、“靓女先嫁论”、“冰棍论”、“烂苹果论”、“吐唾沫论”、“社会财富向精英倾斜论”、“取消社会福利”、“为了达到改革的目标，必须牺牲一代人，这一代人就是3000万老工人。8亿多农民和下岗工人是中国巨大的财富，没有他们的辛苦哪有少数人的享乐，他们的存在和维持现在的状态是很有必要的”、“最低工资标准对工人没有好处”、“中国的贫富差距还不够大”、“腐败有利论”等等“理论”全是在这一时期出笼的。国有资产大量流失、贪污成风、造假成风、贫富剧烈分化、社会矛盾剧烈激化、社会风气急剧恶化等等令中国老百姓深恶痛绝的现象全是在这一阶段形成气候的。号称“清廉”，实际呢？手下金融大将个个巨贪，老子当头号大官儿子当头号买办——一个当婊子一个立牌坊，分工合作，名利双收，虚伪透顶。对内一副凶神恶煞“经济沙皇”的“铁”样，对外呢？不但“铁”不起来，而且软烂如泥，奴颜婢膝送上门去求人“消气”——身为一个主权国家首脑（既不是傀儡政府又不是战败国！）却主动跑到别的国家当众宣布供人家“消气”，这简直史无前例，闻所未闻。如果不是无耻到家，怎么可能干出如此丧权辱国的勾当、如此心安理得而且还如此兴高采烈？这创造了一项“世界记录”：以堪称登峰造极的厚颜无耻而载入史册。下岗工人的评价：毛主席当年太心慈手软，所以才会让当年的右派现在有机会回来搞阶级报复。——整个一个现代版的“农夫与蛇”。

当共产党在爬冰卧雪浴血奋战时，“精英”们舒舒服服地远远躲在安全地方袖手旁观，顶多不疼不痒地吆喝两声。等共产党打下天下，他们马上跑来伸手要这个天下：我是“精英”，“社会必须由精英治理”（茅于轼），所以你流血牺牲打下的政权应该归我。给就是“民主”，不给就是“独裁”（——又是那套“用虚的捞实的”把戏，用一句虚的“民主”白捞一个实实在在的政权。）毛泽东没答应，于是就“罪恶滔天”，就一切都被丑化，就把一切问题都往毛泽东身上推——无非要“证明”一切问题都是因为没有遵循“社会必须由精英治理”的恶果。今天的“精英”喋喋不休拿反右说事，污蔑毛泽东，不过是“继承先辈遗志”，继续玩弄“以虚捞实”的把戏，将诈骗进行到底。

那么“反右扩大化”、“按指标抓右派”也是对的了？当然不对。不但不对，而且是阴谋，大阴谋。反右是阳谋，“反右扩大化”、“按指标抓右派”是阴谋，是阳谋中的阴谋，披着阳谋外衣的阴谋。毛泽东只决策了反右，而具体安排、制定标准、规定执行细则的是“八大”后刚刚上任、急需“政绩”的书记处总书记。搞“反右扩大化”、“按指标抓右派”对他有好处：第一，创造了“政绩”——抓了右派多少多少万，成绩大大的。第二，先制造冤案，再甄别平反，最后来个“一风吹”，受害者便以为让自己受冤屈的是毛泽东的反右，而不是“按指标抓右派”的人——人家后来给自己平凡昭雪了嘛，可见是好人。所以对他感激涕零，而对毛泽东永远耿耿于怀。一手捉鬼一手放鬼，就唱了出这么一抓一放的“捉放曹”就离间了知识分子和毛泽东，自己乘机邀买人心——难怪掌握了“话语权”的“精英”总是把他的屎盆子往毛泽东头上扣。第三，暗暗夺权——“反右扩大化”、“按指标抓右派”制造大批冤案的后果是从此人人自危，党内普遍的教训是“宁犯政治错误，不犯组织错误”：不管正确与否，千万不可得罪党组织内的“一把手”。（今天仍然如此，这也是“反右扩大化”的功德。）刘少奇的“自觉做党的驯服工具”遂大行其道，成了党员的金科玉律——当“工具”不够，当“驯服工具”还不够，还得加上个“自觉”，当个“自觉”的“驯服工具”才合乎要求——这样一来，一切都由直接掌管党务的说了算，退居二线的毛泽东立刻说话不算数了，不管发现什么问题、有什么指示，不经过主管党务的副主席和书记处书记就一概行不通。党政实权便名正言顺地落到了掌管党务的副主席刘少奇和主持中央日常工作的总书记邓小平手里。这就解释了为什么一年之后毛泽东发现刘少奇搞“共产风”、“浮夸风”、“跑步进入共产主义”等歪风时不管怎么打招呼怎么批评都不管用，连开了八届六中全会纠偏、形成了正式文件仍然贯彻不下去：谁也不敢得罪主管党务的刘少奇——“宁犯政治错误，不犯组织错误”，明知“浮夸风”、“共产风”不对，但只要刘少奇坚持，就谁也不敢违抗。这才是“反右扩大化”、“按指标抓右派”的真正后果，所以说这是阴谋，是“借力打力”，借反右暗算毛泽东，架空毛泽东，自己乘机夺权。“第二司令部”就这样悄悄形成了。

2、“饿死三千万”

“饿死三千万”是个非同小可的罪行。既然涉及犯罪，那按“精英”们声嘶力竭鼓吹的“法治”，应该先“无罪推定”，再出示证据：犯罪事实、犯罪动机、主谋、帮凶、策划、实施、是否包庇凶手……一切都必须以板上钉钉的确凿事实说话，而不能以含含糊糊的蛛丝马迹、凭空的想象和推断充数。——“精英”们既然那么关怀黑社会头子的人权和证据的确凿性，那涉及毛泽东的人权和证据的确凿性时至少也应该“一碗水端平”。

“饿死三千万”这个数字从何而来？出处何在？证据何在？我查了半天，查不清。显然是人云亦云。能够确定的事实是：“三年自然经济困难时期”的确饿死了人。饿死人最多的地方一是河南，二是四川。当时河南省委书记是吴芝圃，四川省委书记是李井泉。饿死人的原因并非无粮，而是夺粮——这两个省负责人先虚报产量显示“政绩”。为了保护“政绩”，把民间的口粮调走充数，导致老百姓挨饿，并对上封锁消息隐瞒实情，对实际情况置之不理无动于衷，最终造成大批人饿死。——问题不是一个而是两个：“缺粮导致挨饿”与“夺粮导致饿死”。

“缺粮导致挨饿”不一定就“饿死人”，不能确定就是蓄意的罪行。而“夺粮导致饿死”则已经饿死了人，是不折不扣的蓄意罪行。——那么有什么证据证明毛泽东参与了“夺粮导致饿死”的罪行？中央文件？书面指令？口头命令？暗中鼓励？事后包庇？恰恰相反，“上穷碧落下黄泉，两处茫茫皆不见”。见到的倒是如下事实：“1958年在成都会议上，吴芝圃向毛主席汇报河南能搞几百亿斤粮食，河南粮食很快就过关了，主席根本不信，给他顶了回去。毛主席说：‘试试看，这种人表面上‘左’，实际上是形‘左’实右，缺乏经验，不深入群众’”。这二人都因“夺粮导致饿死”而受到毛泽东发动的“文化大革命”的严厉指责和追究，“文化大革命”后（毛泽东去世后）又都被“平反”，而且评价极高：吴芝圃“为中国人民的解放事业和共产主义事业鞠躬尽瘁，无私地贡献了自己的一生”、“对于强加给吴芝圃同志的一切诬蔑不实之词应予全部推倒，彻底为吴芝圃同志平反昭雪，恢复名誉”。李井泉则在“十大”当选中央委员、任全国人大常委会副委员长，中顾委常委。——毛泽东的“文化大革命”追究了“夺粮导致饿死”这一罪行的罪犯，有人却包庇了罪犯。谁包庇的？显然不是毛泽东。能把“夺粮导致饿死”的罪行栽到毛泽东身上吗？

“缺粮导致挨饿”是谁之过？“反反冒进”、“浮夸风”、“高指标”、“一平二调”、“共产风”、“人有多大胆，地有多大产”、“亩产万斤粮”、“吃饭不要钱”、“跑步进入共产主义”……

那么谁该对这一切负责呢？

网友“数学”的文章“关于‘亩产万斤’评价一下思闻和天父的材料”和黄岭峻先生的文章“毛泽东、刘少奇大跃进前后言论对比录”列举了一系列事实资料，很能说明问题，故不惜篇幅全文附后。（附录一、附录二、）

更能说明问题的是毛泽东于1958年11月“郑州会议”上的讲话《关于社会主义商品生产问题》，足以说明一切。故也附录于后（附录三）。

根据这些资料，充满“亩产万斤粮”、“人有多大胆、地有多大产”之类“浮夸风”的宣传集中发生在1958年6月至1958年9月这三个月。没有任何证据能证明这一切是毛泽东的布置或授意。（拼命鼓吹“人有多大胆、地有多大产”的就是如今大骂毛泽东、鼓吹“自由化”的胡绩伟——从“极左”跳到“极右”，这就叫无耻文人。）事实是：毛泽东一而再、再而三地批评反对“共产风”、“浮夸风”等错误倾向和“跑步进入共产主义”的狂热，无效。开了郑州会议专门纠偏，无效。最后于1958年11月28日至12月10日召开中共八届六中全会，正式纠正亩产万斤的错误和“共产风”的错误。也就是说，从出现问题到开中央全会正式下文件纠正问题一共六个月。而那些弄虚作假的数字都是来自下级的汇报和“专家”的“论证”。如果说毛泽东有错误，那就是在一开始某些场合对来自下层的若干汇报和“专家”的“学术见解”将信将疑，没有立即全力以赴纠正“浮夸风”。——换句话说，毛泽东的责任是最多三个月的“纠正不力”。（厉以宁在“强国论坛”里承认“改革”“工作中的经验不足”、“在改革中我们忽视了一些问题”、“我们当初的认识有局限性”——对毛泽东近三个月的“纠正不力”，“精英”们大肆喧闹了近三十年还没完没了；而对“精英”、“专家”、“学者”们近三十年的“问题”、“经验不足”、“局限性”却不准有人们有哪怕一分钟的质疑，否则就是“否定改革”。这一对比就能明白什么叫“虚伪”，什么叫“无耻”，什么叫“颠倒黑白”了。）

十七大辅导材料“中央领导机构的历史演变”里有如下一段：

http://news.xinhuanet.com/politics/2007-10/31/content_6977120.htm

“1956年9月，中国共产党第八次全国代表大会在北京举行。这是中国共产党在全国执政以后召开的第一次全国代表大会，是显示了党的团结和党的事业兴旺发达的一次代表大会。八大对中央领导机构做了较大调整。”

“（一）中央委员会除设主席外，第一次设了副主席，并规定，中央委员会的主席和副主席同时是中央政治局的主席和副主席。”

“（二）将中央政治局和中央书记处分开。八大修改的新党章规定：‘中央书记处在中央政治局和它的常务委员会领导之下，处理中央日常工作’。中央书记处第一把手不再称‘主席’，而改称为总书记。这样，就将中央政治局与书记处分开了，将决策机关与领导日常工作的机关分开了。邓小平任书记处总书记。”

“中央书记处有很大的权力，如中共中央副主席周恩来任总理的国务院要接受中央书记处的领导。书记处的权力高于政治局委员、甚至副主席。”

“邓小平曾向毛泽东提出，书记处还是作为政治局办事机构，负责对军队和国务院的文件呈送。毛泽东不同意，他强调书记处是党中央的办事机构，什么事都要管，发文用中央的名义。1958年，毛泽东起草的一个党内指示说得更明确：‘大政方针在政治局，具体部署在书记处。’凡是党政军各方面送中央常委的报告、文件都要先送书记处。一般问题，书记处讨论决定，即可下达、执行。重大问题，书记处先拿意见再报中央常委讨论、决定。那时，中央政治局委员因要主持地方大政工作，并不都在北京，非重要会议一般也不来京，所以，政治局不能经常召开全体会议。而书记处要处理大量日常工作，经常每周开会三四次，常常得到毛泽东的直接领导。书记处的同志最早听到毛泽东的声音，知道中央核心的决策，甚至比政治局的一些同志消息更灵通。”

综合这一切可以明白如下事实：

1、1956苏共二十大的反“个人迷信”在同年召开的中共八大也有所反映，开始分“一线”“二线”。中央书记处算一线。毛泽东开始退居“二线”。“中央日常工作都由书记处负责”“周恩来任总理的国务院要接受中央书记处的领导。书记处的权力高于政治局委员、甚至副主席。”——也就是说，中共中央一切具体工作的部署安排实施，包括反右、“大跃进”、“一平二调”、“对苏联提前还债”等等均由中央书记处书记负责经办。

2、邓小平自1956年到1966年任中央书记处书记。也就是说，在这十年期间中国除军事以外的一切活动均由他负责，包括经济活动。

3、1958年“浮夸风”最烈的6月至9月，毛泽东正忙于部署8·23炮击金门，要忙于对付美国，要忙于对付赫鲁晓夫的“共同舰队”和“长波电台”，以及接踵而来的中苏分裂，再加上思索打破美苏两霸冷战的包围等战略大计……这么多、这么大、这么紧急的事要办，未能及时全力以赴纠正“浮夸风”、“共产风”事出有因。

4、1956年起担任中央书记处书记的邓小平和1959年起担任国家主席的刘少奇都属于刚升到“一线”的“新官”。最需要拿出“政绩”证明自己的是他们，不是毛泽东。需要通过1957年的“按指标抓右派”和1958年～1959年的“浮夸风”、“跑步进入共产主义”来显示“政绩”的是他们，不是毛泽东。——50年代初到1956年八大前一直由毛泽东亲自主持工作，不分“一线”“二线”。那几年中国建设发展平稳迅速，成就举世公认。毛泽东并不需要搞什么异想天开、轰动一时的“政绩”来证明自己。1956年八大分了“一线”“二线”之后就不同了：“新官上任三把火”。新接手“一线”的邓小平、刘少奇从1957年起是一年一把“火”：1957：“按指标抓右派”。1958：“浮夸风”、“跑步进入共产主义”。1959：“反右倾”。此外还有“提前还债”——“小平最大的一个政绩，就是提前还债。80年代小平会见苏联代表团，还自夸说当他主持总书记工作期间，提前还清了苏联的外债。”“在大跃进期间，本来比较穷的四川省上缴粮在全国排列前茅，为小平主持总书记期间提前还债立下汗马功劳”——这就解释了为什么自1956年分了“一线”“二线”、毛泽东不再亲自主持“一线”工作后立刻出了那么多邪门的事——“按指标抓右派”、“浮夸风”、“跑步进入共产主义”……——新上任的“一线”领导们的“政绩工程”。

有人说：毛泽东是最高领导。即便书记处是“一线”，具体部属了一切，那也是毛泽东的责任。

毛泽东并没有回避责任，在1962年的七千人大会上做了自我批评，把责任兜到了自己头上。但毛泽东的责任是一时的“纠正不力”而不是“罪责”。

拿破仑说：

“一位统帅因为执行了远离战区、未明战事近况、或根本不知战况的君主或首相所下的命令，以致在战斗中铸成错误时，他是不能推脱责任的。因此，任何一位统帅在执行命令时，如果知道计划不妥或有失败危险，就应向上陈述理由，请求修订计划，并不惜在最后以辞职力争，甚至宁可不干，也不要使自己成为毁灭自己部队的工具。”

“任何一位统帅，明明知道将要遭到失败而仍然按照上级命令进行作战，那就是犯罪。他在此时应该拒绝遵从命令。只有在上级发令人于发令当时亲身处于战场的情况下，军令才要求绝对服从。因为在这种情况下，发令人可以即时聆听反对意见，并且可向执行命令的将领作出必要的解释。”

“当一位统帅接到来自君主的绝对命令，并预料将让敌人获胜而使自己失败时，他对此一命令是否应该服从呢？答案应是一个‘不’字。如果统帅明白此一奇特命令的理由，当然是应该遵照执行的，否则，就应拒绝。”

由此可见即便“浮夸风”是毛泽东亲自部署的，那中央书记处也必须负责。因为书记处书记没有“拒绝遵从明知将要遭到失败的命令”，反而部署实施了错误的东西。不追究书记处书记的责任而责怪毛泽东是站不住脚的。

比如你打“的”，告诉司机向左拐。司机却向左冲上了逆行线。你赶紧告诉司机快回右，司机却向右撞上了马路牙子、冲上了人行道、撞死了行人。警察来抓司机，司机却说不是他的责任，因为是你让他这么干的，该抓你去坐牢——这种逻辑站得住脚吗？到底谁有罪？“一线”手把方向盘的司机，还是坐在后排“二线”指方向的人？对于处于“二线”后排指路的人来说，如果有责任，那就是：为什么用了这么个混账司机？

茅于轼说：“1959～1961年饥荒的原因之一就是不肯利用世界市场。”“请问粮食缺了还不肯进口反倒是负责任吗？”“如果全世界对中国禁运粮食，一定是我们自己做了犯天下大忌的事。”

茅于轼在瞪着眼说瞎话。事实是当时中国政府一直在积极想方设法进口粮食救灾，不仅从加拿大和澳大利亚进口，而且积极谈判从美国进口。1961年1月周恩来总理在中共中央书记处会议上谈到粮食问题时说明：“至于进口，目前正在谈判，可能与美国签合同”。但美国政府坚持封锁禁运，不但不准美国商人向中国出口粮食，甚至于1961年2月3日下令美国公司不得给向中国运粮的船只加油。——表面上看，美国政府并没有一口回绝，而是“表示愿意考虑”向中国出口粮食，但有个前提：必须官方对官方，由中国政府向美国政府提出申请，而不准中国公司与美国公司直接谈判。这实际就是拒绝：美国根本拒绝承认中国政府，怎么个“官方对官方”？这是逼中国政府先投降，承认台湾“独立”，然后再说——这一拖天知道要拖多久。到头来即便最后能从美国进口粮食，那也缓不济急，早错过时机、失去救灾的价值了。茅于轼颠倒黑白倒打一耙，把一切责任都推给毛泽东，说“不肯利用世界市场”、“粮食缺了还不肯进口”、“如果全世界对中国禁运粮食，一定是我们自己做了犯天下大忌的事。”——世界上还有比这更无耻的吗？

说到救灾，不妨看一看斯诺在《西行漫记》的若干描述：

“1929年的大旱”

“西北大灾荒曾经持续约有三年，遍及四大省份，我在一九二九年六月访问蒙古边缘上的绥远省的几个旱灾区。在那些年月里究竟有多少人饿死，我不知道确切的数字，大概也永远不会有人知道了；这件事现在已经被人忘怀。一般都同意三百万这个保守的半官方数字，但是我并不怀疑其他高达六百万的估计数字。”

“我当时二十三岁。我想我是到东方来寻找‘东方的魅力’的。我以为自己是个冒险家，那次绥远之行就是那样开始的。但是在这里，我有生以来第一次蓦然看到了人们因为没有吃的而活活饿死。我在绥远度过的那一段噩梦般的时间里，看到了成千上万的男女老幼在我眼前活活饿死。”

……

“我并不想要危言耸听。这些现象都是我亲眼看到而且永远不会忘记的。在灾荒中，千百万的人就这样死了，今天还有成千上万的人在中国这样死去。我在沙拉子街上看到过新尸，在农村里，我看到过万人冢里一层层埋着几十个这种灾荒和时疫的受害者。但是这毕竟还不是最叫人吃惊的。叫人吃惊的事情是，在许多这种城市里，仍有许多有钱人，囤积大米小麦的商人、地主老财，他们有武装警卫保护着他们在大发其财。叫人吃惊的事情是，在城市里，做官的和歌妓舞女跳舞打麻将，那里有的是粮食谷物，而且好几个月一直都有；在北京天津等地，有千千万万吨的麦子小米，那是赈灾委员会收集的（大部分来自国外的捐献），可是却不能运去救济灾民。为什么？因为在西北，有些军阀要扣留他们的全部铁路车皮，一节也不准东驶，而在东部，其他国民党将领也不肯让车皮西去～哪怕去救济灾民～因为怕被对方扣留。”

……

“在灾情最甚的时候，赈灾委员会决定（用美国经费）修一条大渠灌溉一些缺水的土地。官员们欣然合作～立刻开始以几分钱一亩的低价收购了灌溉区的所有土地。一群贪心的兀鹰飞降这个黑暗的国家，以欠租或几个铜板大批收购饥饿农民手中的土地，然后等待有雨情后出租给佃户。”

“灾情最严重的时候，在这个黑暗的国家里出现一群贪婪者。他们以免收拖欠的租金或只付几个铜板的方式、从饥饿的农民手里收购了成千上万亩土地，等到旱情解除时再租给佃户。”

“1939年的水灾”

“居住在中国中部变化莫测的河流流域的中国人，大约有九十万人死于水灾惨祸。一千二百万户家庭被毁灭，五千五百万人受灾。就在这个打击以前，干旱使一些省份赤地千里，饥荒使曾经是富裕之乡的西北大伤元气，蝗灾接踵而至，十四次内战使国家的经济结构遭受破坏，盗窃、抢劫、匪患横行，为扑灭共产党人革命进行的斗争已经历时两年，军阀统治下一片恐怖，那种麻木不仁、暴虐和后果严重的无能，是本世纪任何其他地方所不及的。”

……

“从前，如果庄稼遭灾，还有储存的粮食可以支持到来年播种的时候。当雨水充足时，河渠饱满，健壮的水牛在地里推动着古老的水车，滋润着可爱的田地。农民挑着水桶在自己的那片地里忙来忙去、喊着那奇妙的、勤劳的劳动号子。生活似乎是亲切的。但是，这些年以来，在大地上出现了掠夺成性的野兽。官吏们把骇人听闻的敲诈勒索合法化、称之为‘捐税’。兵士们也抢劫分赃。盗贼横行，粮仓空空如也。除了地主和放高利贷的人以外，谁也没有什么银子，而地主和放高利贷的人的银子也是深藏不露的。”

……

“个旧矿共有近50000名矿工，其中60%以上是奴隶。40%的矿工干活三、四年以后便中砷毒而死。干上几个月，他们的皮肤差不多变成青色，因为砷毒迅速的进入了体内。他们的平均工资每年约20美元。每名童工死亡，如果有抚恤金给予他的父母，数目也只有二、三美元。”

……

“我向自己问道，‘他们为什么不反抗？’‘他们为什么不组成一直浩浩荡荡的大军、向那些只知道向他们征收苛捐杂税而不让他们吃饱、只知道夺取他们的土地而不会修复灌溉水渠的恶棍们发起进攻呢？他们为什么不冲进大城市去抢那些买了他们妻儿、那些当正直的人忍饥挨饿而他们却继续狼吞虎咽地饱餐三十六道菜的筵席的人呢？’我对他们的消极态度迷惑不解。有一个时期，我以为没有什么事情可以促使一个中国人起来斗争。”

“我错了。中国农民并不消极，他不是一个懦夫。如果有方法、有组织、有领导、有可行的计划、有希望——而且有武器，他们是会起来战斗的。”

……

上述腐败阴暗的情况在毛泽东时代的救灾过程中发生过吗？而有些情景——如“官员们欣然合作～立刻以几分钱一亩的低价收购了灌溉区的所有土地。一群贪心的兀鹰飞降这个黑暗的国家，以欠租或几个铜板大批收购饥饿农民手中的土地，然后等待有雨情后出租给佃户”、“40%的矿工干活三、四年以后便中砷毒而死”、“他们为什么不反抗？”“他们为什么不组成一直浩浩荡荡的大军、向那些只知道向他们征收苛捐杂税而不让他们吃饱、只知道夺取他们的土地而不会修复灌溉水渠的恶棍们发起进攻呢？他们为什么不冲进大城市去抢那些买了他们妻儿、那些当正直的人忍饥挨饿而他们却继续狼吞虎咽地饱餐三十六道菜的筵席的人呢？”——对今天的人来说是不是更有点“似曾相识”的味道呢？

网文“万流归海见桑田～从华夏五千年农耕文明的大视野仰望毛泽东”让我知道了一个事实：高粱为什么会逐渐消失。高粱不高产，缺营养，不好吃。但中国北方过去种得多，现在却越种越少。为什么？因为高粱极耐水涝、极耐盐碱。过去中国北方大地表面是平原，实际净是坑坑洼洼，动不动不是旱就是涝。洼地易积水。积水就易泛盐碱。这一切使其他作物都不好种，只好种高粱。为什么现在高粱种得少了呢？因为中国自1958年起开始了大规模的兴修水利、改造洼地、改造盐碱地、平整土地等“农田基本建设工程”，改造了自然，可以种高产作物，不必再种高粱了。结果：“三年自然灾害”之后再无大灾——碰上同样的气候不理想，过去为灾，后来就不为灾了，因为中国农业的抗灾害能力今非昔比了。——这一切靠个体户、小农经济做得到吗？没门——动不动就涉及几个县几条河的工程，没有成千上万的人谁干得了？靠机械化？当时哪来的钱？现在即使有钱，一算“经济效益”也受不了。那么是谁的功劳？第一，人民公社。只有人民公社才有这个组织能力。第二，人的精神：就凭人的肩挑手拉、一锹一筐、一步一个脚印，靠一个工分几角钱几分钱的报酬硬是改造了华夏大地。如果一切靠等靠钱靠设备，到现在也未必干得成。这才是真正的救灾，最彻底的救灾，一劳永逸的救灾，毛泽东式的救灾。

有人争辩说“浮夸风”直到1959年仍未制止，所以才有彭德怀的“万言书”。罢免彭德怀说明毛泽东拒绝正确意见，结果造成了饥荒。

这种说法似是而非。

1958年中共八届六中全会已经正式下文纠偏了。1959年的庐山会议本来的议题就是继续纠偏。彭德怀的“万言书”上说的东西并不是新出现的问题。问题不在“万言书”本身，而在“万言书”之外。——既然的问题已经被认识到，毛泽东已经接二连三又开会又讲话又发表文件大力纠正问题，那还提问题就不是为了问题本身，而是为了追究责任——如同一个人走错了路，已经发现了，已经回头了，你却一再逼问：你为什么走错了路？这就跟走错路本身无关了。彭德怀不是“就事论事”，而是“就事算旧账”——说过去在延安你操了我四十天娘，现在让我操你二十天娘行不行？这就超出了万言书自身的内容，不但涉及了历史上的是非，而且涉及了人事纠纷，要追究责任。——仅仅一年前彭德怀刚刚以“反教条主义”为名逼刘帅检讨退位，现在会不会又要逼谁退呢？没资料，不知道。但庐山会议上未必没有人这么认为，尤其是以“大跃进”为“政绩”的。——当年在当年庐山会议上与彭德怀激烈争论的人都有谁、都说了哪些等等现在还没有看到什么可靠的资料，不能妄议。但从另一个角度看，毛泽东罢免彭德怀并非没有道理：中苏已经分裂，毛泽东必须对党内军内可能的亲苏势力保持高度警惕。彭德怀在苏联影响很大。赫鲁晓夫公开说过彭德怀是他的好朋友。彭德怀刚刚率领军事代表团访苏归来，马上就上庐山递“万言书”，而且扯到了人事纠纷，再加上跟一批高级将领伙在一起。这一切引起毛泽东的警惕并不奇怪。如果毛泽东因为这些而决心罢免彭德怀，那不能说没有道理。

“精英”们用“万言书”大做文章攻击毛泽东，完全是出于自己利益的需要：为了证明茅于轼的论断——“社会必须由精英治理”，就必须证明“没有精英治理”必遭大难，就必须制造个“饿死三千万”的吓人罪名强加给毛泽东，就必须利用彭德怀的万言书来证明一切都是毛泽东之过。这是在“杀鸡吓猴”，借妖魔化毛泽东警告中国今后的一切领导人：谁敢得罪“精英”谁就没有好下场，不世之功会变成滔天大罪，苍蝇会变成大象，白的会变成黑的。而如果赞同“社会必须由精英治理”，则即便有“饿死三千万”的大罪也会被“精英”们“隐恶扬善”、“为尊者讳”、“文过饰非”、“化腐朽为神奇”地嫁祸于人。所以才会出现毛泽东三个月的“纠正不力”被揪斗了几十年，而毛泽东几十年的不朽功勋被一笔抹杀等冤案。——这一切都是“精英”们实现“社会必须由精英治理”这一政治目标的需要。

那么彭德怀是否冤枉呢？

在今天的“事后诸葛亮”们看来，是有些冤枉。但当“事后诸葛亮”容易，当“事先诸葛亮”难。在没有条件从容查清一切时，为了确保国家安全大局，有时采取断然措施防患于未然是不可避免的。这在任何国家都有可能发生。这如同战场上的误伤：如果能够慢条斯理地弄清一切，自然不会误伤。但既然没有条件去慢慢查清楚，那就只能根据当时条件下所能得到的最好资料当机立断，宁可承受误伤的损失也不能因怕误伤而给敌人可乘之机——美军装备那么现代化，也照样不能避免误伤。

好人受冤枉是最不幸的事。但社会自有其规律，战争自有其法则，很多情况下避免不了不幸。有些平时看来理所当然的事，特殊情况下就容不得。比如婴儿啼哭是理所当然的，谁也无权制止。但抗日战争反扫荡时多次发生过母亲为了避免婴儿啼哭暴露目标被日本鬼子发觉，不得不把要啼哭的婴儿捂死了——平时最正常的“啼哭权”在特定条件下就容不得。这对于婴儿来说的确是天大的冤枉，天大的委屈。但当时当地的情况就是：是一个婴儿的委屈重要，还是一群人的生命重要？

又比如现在人们关于以往革命战争时期的“肃反”几乎是众口一词一边倒地全盘否定，简直骂得一塌糊涂。这就有片面性，缺乏具体分析。首先得看具体的历史环境。比如土地革命时期，一方面1927年大革命失败，蒋介石的口号是“宁可错杀一千，不可漏网一人”，整个社会一片恐怖，背叛、出卖行为不少，稍有不慎被叛徒内奸特务钻了空子就会一死一大片。而当时的条件下又不可能从容周密地到全国调查每一个可疑对象。那就免不了经常面对这种选择：是个人的清白重要，还是更多的人的性命重要？这是严酷的环境强加的选择。另一方面，共产党1927年才开始搞武装斗争，一切都刚开始学习。谁能要求一个人一跟头就从外行变成内行，从门外汉立马变成肃反专家，不放过一个坏人，不冤枉一个好人？（“主流经济学家”改革了近三十年还没学会改革呢，还承认“认识有局限”呢。）再加上国民党大屠杀激起的普遍仇恨和急于报仇的情绪，这就导致一些冤案难免。但很多当时条件下受过冤枉的人都理解：这是客观环境所迫。如果换了自己也会同样处理。所以这些人虽然受了委屈，但多数并不因此而投敌，以至于国民党都奇怪：这些人国民党要杀，共产党也要杀，为什么还要跟着共产党？

再比如说对当过俘虏的自己人。过去靠“小米加步枪”对付现代化，打仗全凭一股气。一旦士气受损，那就没办法打仗了。而在当时情况下怎么可能有条件有时间慢慢调查，弄清楚那些当过俘虏的人是否是人家故意派回来败坏士气的？这同样面临着一个“是个人的清白重要，还更多人的生命重要、部队的士气重要、战斗的胜利重要”的抉择问题。过去对当过俘虏的自己人那么严厉，同样是环境所迫。等环境不那么严酷了，要求也就不那么严厉了——对中越边境自卫反击战时当过俘虏的中国军人的处理就与以往不同。这同样是环境的产物。在今天的和平时期看来蛮不讲理的东西，在战争时期是不可避免的，有些在极端严酷的战争条件下有时简直是必需的。

所有这些无非是关于如何看待彭德怀的遭遇问题。但这并不是说就应该制造冤案，就应该“残酷斗争、无情打击”。这正是毛泽东历来是最反对的。毛泽东关于这方面的规定是一整套一整套的：人民内部矛盾、党政关系、军民关系、上下级关系、同志之间的关系……连对待敌人和叛徒都有明确规定：缴枪不杀、优待俘虏、不虐待俘虏、对叛徒，如其悔改，还可接待，但不准重新入党、不给出路的政策，不是无产阶级的政策……毛泽东一贯主张通过批评与自我批评团结一切可以团结的同志，包括反对自己反对错了并愿意改正错误的同志。朱德、陈毅、周恩来等都曾经反对过毛泽东，但最后都团结到了毛泽东周围。毛泽东处理干部历来是“批评教育从严，组织处理从宽”，被喻为“热加工，冷处理”。要说与人为善，做得最好的是毛泽东。而其他人就不然了。不信看看现在最时髦最红火的“理论书”，可有如此详尽完整的主张？可能用来指导处理各种关系？

《亮剑》主人公李云龙的原型——王近山，号称“王疯子”。没有命令的情况下主动伏击日寇“皇军战地观摩团”就是他的杰作。战功累累却不幸“英雄难过美人关”，闹着离婚娶小姨子，被一状告到刘少奇处。结果：开除党籍，一撸到底，下放农场劳动。——喜新厌旧闹婚变是不对，不听党组织劝阻是有错，但错不至此。就凭这就把个有功之臣整成那样，如此冷酷无情，为什么？“自觉做党的驯服工具”——你不是功臣，是工具。所以毫不留情。——如果是毛泽东经手，会如此心狠手辣吗？

至于那个“人民的儿子”，只要看下述时间和随之而来的事实就行；1956年升迁中央书记处总书记——“反右扩大化”、“按指标抓右派”、“浮夸风”、“反瞒产”、“调粮导致饿死”、“提前还债”。1975年第一次复出——下令武力围剿云南沙甸回民。1978年第二次复出——1979年打越南。1989年第三次复出——大兵进京。——四次掌大权，四次立刻杀人。几何上两点确定一线，三点确定一面，四点确定一体。而这里的历史上的四个点能确定出个什么样的立体形象？俗话说“可一可再不可三”。一次两次是偶然，再三再四就是规律。什么规律？凶神。心狠手辣的凶神、死神。只要一掌权，必定要死人。最多死了多少？“饿死三千万”。什么“人民的儿子”？“龟儿子”！阎王鬼子！这样的凶神恶煞跟大仁大义的毛泽东能相比吗？把“饿死三千万”的罪名强加给毛泽东，这难道不是中国有史以来最大的冤案吗？天日昭昭！天日昭昭！

3、“文化大革命”

首先必须承认，“文化大革命”失败了：“彻底否定”了，“肃清‘三种人’”了，文革时期的一切推倒重来了——这难道还不算失败吗？

为什么失败？

因为这是一场超越了时代的革命。

——就普通老百姓而言，当时并没有感到有多迫切的革命的要求。上头号召了，报纸上宣传了，就跟着干了。

——更关键的是谁都不知道如何弄清“谁是我们的敌人、谁是我们的朋友”这个“革命的首要问题”：谁是“走资派”？谁是“反动学术权威”？没法判断：按今天的标准看，那时的官员个个都是清官，没一个够资格算坏蛋。所有的官员都一样地说拥护毛泽东。要从这里边挑出坏人来，靠X光都分不清。这就好像两军交战，一样的外观，一样的服装，一样的语言，一样的口号，一样的目标——到底谁是敌人？谁是自己人？当兵的说不清，当官的也说不清，结果净是自相残杀，净是好人打好人，打来打去打得好人都学坏了。大家都受不了了，都觉得是毫无意义的瞎折腾，于是集体抵制了。遭到群众普遍抵制的革命当然进行不下去，失败也就不可避免了。

在当时看来，否定“文化大革命”是很得人心的：不折腾了，安安静静过日子了，不是挺好吗？

但是随着时间的推移，形势的发展，人们忽然发现，“文化大革命”的原则不再是那么荒唐无稽、那么不可理喻了。相反，当初死活弄不清的东西现在竟然渐渐清晰开朗起来了。

比如，文化大革命的“四大”——大鸣、大放、打字报、大辩论，过去觉得是无法无天，现在呢？只问一句：会不会上网？天天上网不上网？

——如果不会上网不上网，那什么都不必谈了：落后于时代、属于上个世纪的老古董，。厉以宁说“要顶住互联网”，这相当于工业革命初期手工业作坊的工人闹着砸机器，属于对抗科技文明。如此被现代科技淘汰的活化石、兵马俑、木乃伊一般的“学者”，如何“代表先进生产力”？

——如果会上网、天天上网呢？那就恭喜了：您口头上也许在否定“文化大革命”，但行动上却在天天积极参加着当代的“文化大革命”呢。

“文化大革命”是“充分发动群众，自下而上地、全面揭露社会的阴暗面”。——当时没有互联网，只能采取“大鸣、大放、大字报、大辩论”的形式。

而如今的互联网呢？干的恰恰是同样的事。任何人，只要有机会上网，就可以畅所欲言，发表意见，揭露阴暗面，不折不扣实现了“充分发动群众，自下而上地、全面揭发社会的阴暗面”。这跟“文化大革命”的宗旨有区别吗？本质上毫无区别。要说区别就是现在的“网上文革”比“文化大革命”的“四大”方便得多，有效得多，转播迅速得多，广泛得多。也就是说，唯一的区别是用现代技术——网络取代了文革的“四大”。所以说网络就是现代化的“四大”，上网就是参加现代化的“文化大革命”。

又比如，如果现在要弄清楚谁是“走资派”，谁是“反动学术权威”，立刻千夫所指，毫不犹豫。

现在中国的老百姓最恨谁？贪官污吏，以及专门与贪官污吏狼狈为奸的“无良学者”——窃取了“硬权力”和窃取了“软权力”干坏事的。

“文化大革命”要打倒谁？“党内走资本主义道路的当权派”和“反动学术权威”——窃取了“硬权力”和窃取了“软权力”干坏事的。

当年“文化大革命”要打击的，正是最令今天中国老百姓咬牙切齿恨之入骨的。他们的本质和危害，毛泽东早在四十年前就已经看透了。从这个角度讲，“文化大革命”的原则错了吗？

毛泽东“文化大革命”的理论太超前了，远远领先于时代，远远超越了当时人们的领受能力。俗话说，领先时代一代会被当成天才，领先时代三代则会被当成疯子。毛泽东的“文化大革命”正是这样。当时并不具备革命的条件，几乎没有人能理解“文化大革命”，当然更不知道该如何干，干起来岂有不乱之理？超越时代、得不到老百姓的拥护的“文化大革命”在当时只能失败。

别看我现在是铁杆“毛派”，但当年我对“文化大革命”可是一点也不理解，没少发牢骚，没少讲怪话，没少欢呼“彻底否定文化大革命”。但是严酷的现实改变了我的看法。只要不肯自欺欺人，只要还讲点良心，只要还讲究点实事求是，就不能不正视中国社会的现实，就不能不承认（哪怕是痛苦地承认）当年的毛泽东是对的，文化大革命的总目标没有错，发动群众自下而上揭露阴暗面、打击“走资派”和“反动学术权威”的大宗旨没有错。执行中的问题不能影响“战略目标正确”这个本质。当年的毛泽东远远超越了时代。但毛泽东没有时间等待人们慢慢觉悟过来，只好在其有生之年通过“文化大革命”把自己的理论信念刻在历史上，让后人慢慢领悟觉醒。为此宁可自己一时不为人理解，甚至被人误解、谩骂也在所不惜，也就是牺牲自己，教育人民。从这个角度看，当年欢呼“彻底否定文化大革命”的我颇有点类似耶稣被钉死在十字架上时在一边欢呼的愚民，其实并不知道自己在做什么。

当年的耶稣被钉死了，其信仰却复活了，曾经欢呼处死他的人的后代不少人后来却皈依了基督教，也算是一种历史的讽刺。更讽刺的是，同样的情况正在中国重演。毛泽东的“文化大革命”也如同耶稣，被钉死在“十字架”上之后又复活了。随着时间的推移，技术的进步，尤其是互联网的普及，“文化大革命”的正面意义越来越明显。当时因技术条件限制而做不到的，现在不在话下了。当时人们不理解的，现在都不难理解了。越来越多的中国人开始认识到“文化大革命”的积极意义了。“文化大革命”这个字眼虽然现在被妖魔化了，让不少人一听就要跳，但其实质内容已经进入了人们的日常生活，在中国人的政治生活中发挥越来越大的作用。

九十年代中国的强迫征地、强迫拆迁、下岗、买断工龄、贪污腐化、国有资产流失、贫富极端分化等等比现在严重得多，嚣张得多，引起的社会关注却比如今少得多，遭到的抵制更没有今天这么大。为什么？当时互联网在中国不普及，没有“网上文革”，把握着“话语权”的“主流精英”严密封锁了消息，颠倒了黑白，一切矛盾都被掩盖了，任凭他们“杀人如草不闻声”。而今天不同了。有了“网上文革”。“主流精英”的话语垄断和信息垄断被打破了。他们想为所欲为不那么容易了。他们不能像以前那样呼风唤雨，招摇撞骗了。没有互联网，他们说什么是什么，神气活现，傲慢嚣张。现在呢？“主流经济学家”、“主流精英”这些词汇不是已经臭不可闻了吗？“重庆钉子户”僵持了几年，网上一登，半个月解决问题。这一切都是谁的功劳？互联网——“网上文化大革命”。没有互联网，指望平面媒体发善心，能有这样的局面吗？对比九十年代和今天的现实，现在人们还离得开这种“网上文化大革命”吗？

“饿死三千万”是“共产风”、“浮夸风”、“穷过渡”、“跑步进入共产主义”之类“政绩工程”的结果，天大的罪名却被巧妙地强加给了曾一再制止那些歪风的毛泽东，以至于人们普遍一提到“大跃进”就联想到“共产风”、“浮夸风”、“穷过渡”、“跑步进入共产主义”；一提到“共产风”、“浮夸风”、“穷过渡”、“跑步进入共产主义”就联想到“饿死三千万”，一提到“饿死三千万”就联想到是毛泽东的责任，而对“共产风”、“浮夸风”、“穷过渡”、“跑步进入共产主义”等“政绩工程”真正的始作俑者——刘少奇的责任一无所知。毛泽东这才发现自己一直相信倚重的助手原来竟是如此阴险狠辣，才发现原来真正的敌人在党内、在身边——难怪毛泽东从此以后把注意力从党外转向了党内。

但此时刘少奇已经非同小可：党务专家——“论共产党员的修养”是党员必读；刘的一举一动代表党——全党都必须服从：“宁犯政治错误，不犯组织错误”、“自觉地做党的驯服工具”。“饿死三千万”的罪责已经被巧妙地安到了毛泽东头上，而刘少奇却成功地把自己塑造成一个替毛泽东收拾了拦摊子、把中国从“三年自然灾害”中解救出来的“务实专家”。毛泽东的一切指示主张刘少奇均可以置之不理。如果按程序召开党代会在党内较量，刘少奇几乎稳操胜券。刘少奇自己也清楚，难怪他1966年7月19日公开宣布，要保护“拥护党中央、反对毛主席”的人。

此时毛泽东的大战略——使中国冲破美苏冷战的包围、通过中苏论战+援越抗美打战略翻身仗的阳谋才刚刚有点眉目。这时刘少奇却准备参加苏共二十三大，与苏联和好共同援越。这等于要永远把中国绑在苏联的战车上，永远对苏“一边倒”。这势必彻底破坏毛泽东的战略大计，断绝了中国称为“世界一极”、崛起成为世界大国的可能。这使毛泽东忍无可忍，决心与刘少奇斗到底。

如果按正常党内民主程序，刘少奇几乎赢定了。所以毛泽东采用了非常手段——文化大革命。

文化大革命失败了，但毛泽东的阳谋——打破美苏两霸冷战夹击中国、使中国成为世界一极的战略目标实现了。毛泽东的代价：牺牲自己的一世英名，长期被人误解，直到现在。

文化大革命在今天还有意义吗？

记得小时候有一首儿歌：“理发师，技术高，不用剪子不用刀，一根一根往下薅，薅成一个大秃瓢。”【薅，hāo,拔除，编者注。】

如今已经“政令不出中南海”——当然，只是于国于民有利的政令。凡对利益集团有利而对老百姓不利的政令，如“教育产业化”、“医疗产业化”、“涨价”等，那绝对一帆风顺，执行得飞快，决无出不了中南海的问题——如果“各路诸侯”公然造反倒好办，武力讨伐就是了。难就难在是“和平对抗”——只跟你软磨。你拨一拨，我动一动，动也只动在表面。比如矿难，出来了就抓，不出来不管，只跟你瞎糊弄。反正你没办法自己来抓。贪污腐化案也是如此：如今的贪污腐化、两极分化、矛盾激化已经遍地开花。靠专案一个一个地处理，那就等于“不用剪子不用刀，一根一根往下薅”——薅掉一根，长出一把；薅完一个，冒出一堆。看你能不能亲自来“一根一根往下薅”。这一切实际是中央政府对地方失控：你的一切政令都行不通。结果：各地缓慢地走向分离分裂，社会走向对抗崩溃。

如果中央政府决心决不允许“群雄并起、天下大乱”的局面发生，就只能面临一种选择：如何根本扭转。结论只有一个：要么文化大革命——在中央政府的强力干涉下把地方各级机构推倒重来，来个自下而上的彻底解决；要么等死。也就是“要么在沉默中爆发，要么在沉默中灭亡”。就像当年的毛泽东：在“重上井冈山”与“文化大革命”之间做一选择。

（当然，按照“精英”的药方，还可以“民主制约”，“增量民主”解决一切。但那样只能瓦解得更快：在一个满地骗子的社会搞“自由竞选”，不分崩离析才怪。）

** 一场空前的民族危机

冷战结束了。苏联解体了。美国在伊拉克、阿富汗忙得不可开交。目前似乎不存在来自外部的、迫在眉睫的、足以威胁到中国生存的大患。那么中国是否可以高枕无忧了呢？不能。

“祸兮福所依，福兮祸所至”。外部威胁减退是好事，但也有另一面。根据中国的历史教训，外患减退之日，便是需要警惕内乱分裂之时。大敌当前能促进中国人团结一致共同对外。外来的压力反而加强了中国人的凝聚力。一旦来自外部的压力消退，那这种凝聚力的助力也随之而去。中国能否继续存在而不分裂瓦解，全靠中国自身的凝聚力。物质上的凝聚取决于经济利益的一致。精神上的凝聚力取决于民族认同。

目前中国的凝聚力，无论是物质方面还是精神方面，都正在受到空前的挑战与破坏。

1、物质方面：

中国现在当“买办”最吃香——既然以追逐“富人”之“富”来“致富”，出现这种情况一点也不奇怪。

网络文章“918事变的教训”里关于“买办”有几段话非常精辟：

“1931年8月22日蒋介石在南昌说：‘中国亡于帝国主义，我们仍能当亡国奴，尚可苟延残喘，若亡于共产党，则纵肯为奴隶亦不可得’。”

“9·18的夜里，东北军参谋长荣臻打电话给北大营下令说：‘不准抵抗，不准动，把枪放到库房里，挺着死，大家成仁，为国牺牲。’”

“蒋介石说的‘我们’是谁呢？荣臻说的‘国’是谁的国呢？”

“显然不是农民，从清末以来，每一次割地赔款的负担最终都落到农民身上，早就知道‘最恨条约’的道理。不是工人，因为工人一向在列强和买办的血汗工厂里被敲骨吸髓。也不是知识分子，9·18之后不知有多少青年学生在请愿时被打得头破血流。也不是军人，保家为国是军人的本分，绝大多数军官和士兵都是坚决要求抗日的。甚至有不少地主，因为在日本占领下的台湾大部分土地被日本人霸占了，在东三省，日本也计划霸占1/3的耕地分给日本的‘开拓民’。”

“总是有人要求别人牺牲，牺牲工人，牺牲农民，牺牲知识分子，牺牲军队，牺牲一代人，牺牲国土，牺牲盟国……试问一个国家里把工人、农民、知识分子和军队都牺牲了还剩下谁？谁的利益如此崇高？竟需要整个民族为之牺牲？”

“这个凶狠的怪物就是买办。蒋介石发表的讲话正是官僚买办集团利益宣言。蒋介石的不抵抗主义正是买办利益的要求。”

……

“买办们为了自己的利益，卖了农民卖工人，丢了东北丢华北，至于从日本手中收复朝鲜和台湾更是早就丢到爪哇国去了。总之只要买办们能苟且偷安，继续捞钱，一切都可以出卖。唐朝时武则天有个男宠叫张易之，有人在他家门上贴了个纸条上写：‘看你横行到几时’，张易之竟狂妄的回贴：‘为欢一日已以足’。后来张易之果然被愤怒的御林军斩杀了。然而买办的本事比张易之要大得多。他们一面把中国当成淘金场，一面把自己的根扎在大洋彼岸，一有风吹草动，只要拿上一本护照，再记住瑞士银行的密码，就可以一走了之。在美国居住多年的宋美龄，她豪华别墅的每一块砖都浸透了南京30万中国人的血，她余生中的每一天都在向人们证明这样一个道理――买办没有祖国。”

“因为买办没有祖国，所以买办不需要国防。蒋介石时代对海军的投资还比不上满清。30年代蒋军的炮兵实力甚至比不上北洋军，北洋军参照德国、日本军制，1个正规师里还有1个炮兵团，而1937年的国民党军最好的嫡系师里也只有1个炮兵营。买办经济只偏重于列强需要的纺织、原材料加工等轻工业，而所有和国防有关的航空、化学、钢铁等重工业买办都不能使买办获利。宋子闻有句名言：‘外国进口的盘尼西林（青霉素）用都用不完，中国何必要自己生产？’。”

“买办也需要军队，但这是内战型的军队，专门用于镇压人民的军队。无论从装备、编制、教育、训练都是如此。由于缺乏火炮等重武器，蒋的200万军队按当时国际通行的标准，只是一支治安军，远远不能算国防军。1935年庐山军官训练团学的是《剿匪手本》，德国顾问教的是堡垒战术。这一套对付江西红军是有效的，但搬到淞沪战场上就成了日军飞机、大炮的活靶子。对红军的围剿动辄出动30万、50万、100万兵力，3000万军费。围剿抗日的19路军和抗日同盟军都出动了15万以上的兵力。而每次用于抗日的中央军不过几个师而已，19路军作战的经费竟是靠各界捐助的。”

“所有这些倒行逆施都说明，买办的利益依附于列强的利益，与中华民族的根本利益是背道而驰的。买办经济不能成为中华民族复兴的脊梁。一旦买办的意志上升为国家意志，则必有投降政治、消极军事、破产外交和殖民文化。国家民族的前途命运就会坠入黑暗的深渊。”

……

说明一句：这里说的“买办”，指的是“官僚买办”——不错，买办的性质就是为外国谋利益，不是为中国谋利益。但外资外商的正当雇员通过正常商业活动在中国为外国谋利益是一回事，中国的官员与外资外商内外勾结里应外合损害中国利益为外国谋利益是另一回事。一个合法，一个非法；一个两相情愿，一个动用权力强迫中国做牺牲。普通买办不一定是中国的敌人；官僚买办必定是中国的敌人。

是不是官僚买办不能看表面形式，而要看整个买办过程中有没有权力参与加利益转移。只要有，那就构成了官僚买办。不管是“家族分工”——“老子当官、儿子买办”、是“互助组、合作社”——“你给我办事，我安排你家属出国、就业”，是“友情协作”——“互相帮忙”还是“一次性交易”，只要涉及钱权交易，那就是官僚买办。

现在中国“老子当官、儿子买办”的情况还少吗？外资外商通过这种“曲线买办”左右中国决策强迫中国牺牲中国利益的事还少吗？中国社会以当买办为荣难道不是事实吗？面对如此强势，如此吃香的官僚买办集团，中国的民族利益何在？中国的物质凝聚力何在？

2、精神方面：

中国的“主流精英”正有组织、有计划、有步骤、有纲领地全面围剿中国人的民族认同，以彻底摧毁中国人的民族凝聚力。这表现在以下几个方面：

（1）、全面妖魔化中国的一切民族英雄，全面美化中国的一切民族败类。

使中国避免了1945年被美苏两霸瓜分肢解的命运、最终将中国从“人为刀俎、我为鱼肉”的处境变为“世界一极”的毛泽东是中华民族有史以来最伟大的民族英雄，却遭到中国“主流精英”有史以来最卑劣最无耻的诬陷诽谤妖魔化。

“主流精英”无孔不入地把1949年以来的历史描绘得如同一个荒诞神话：毛泽东夺得政权后就没干好事：“杀人放火”、“镇反”、“反右”、“闭关锁国”、“一边倒”、“替苏联跟美国打仗”、“大跃进”、“饿死三千万”、“文化大革命”、“勒紧裤带输出革命”、“不顾人民死活造原子弹”……总之是个到处搞破坏的头脑发昏的疯子，直闹得天怒人怨、“国民经济处于崩溃的边缘”。等毛泽东去世，地下拱出个土地怪，口中一通念念有词，大叫一声：“改革开放！”顿时中国春暖花开好事全来，要风得风要雨得雨，满地馅饼，“国际接轨”、“全球化”、“世界工厂”、“外汇储备世界第一”，从此人人向善、个个虔诚、处处一片歌舞升平，中国一跟头就成了“世界大国”、“责任大国”……（“主流精英”们如同一群耗子，把一个完整严密、充满因果关系的历史啃成一地碎片，每只耗子各叼一片到处卖弄：我这一片就是历史！——按照他们的碎片去了解历史，只能看到一个被耗子啃得歪七扭八变了形的丑八怪。）

不仅毛泽东，中国史上一切民族英雄也无不遭到丑化淡化、“重新评价”：狼牙山五壮士、黄继光、邱少云、岳飞、文天祥……而一切民族败类无不遭到翻案美化、“重新评价”：汪精卫、袁世凯、李鸿章、吴三桂、洪承畴、秦桧……完全再现了鲁迅当年的辛辣嘲讽——“玉中求瑕，屎里觅道”。

更严重的是最近的《色·戒》风波：一个坚贞不屈、视死如归的抗日女英雄，一个“满门忠烈”、可歌可泣的民族英雄故事，被个汉奸婆娘张爱玲歪曲成了个为性爱背叛抗日的叛徒娼妇，被个性变态导演李安拍成了个汉奸色情教学片——核心意思：“人权高于主权”——性爱是“人权”问题，“抗日”是主权问题。影片“激情”了半天，要说的就一条：为了性爱背叛抗日可以理解，应该歌颂，值得效仿。这还不是“人权高于主权”？——这一切本不足为怪：林子大了什么鸟都有。中国历来盛产汉奸文人，有这俩不多，没这俩不少。怪就怪在这部“说英雄是娼妇，举娼妇为英雄”的汉奸色情教学片居然得到了中国官方的认可，居然在“南京大屠杀”七十周年的前夕公开发行，居然受到“主流媒体”狂热叫好，为居然“并未引起民族主义情绪强烈反弹”而欢欣鼓舞，北大学子看到《色戒》中喊出“中国不能亡”口号时居然哄堂大笑，官方居然对中国老百姓洪水般的指责抗议置之不理，居然禁止争论朝着“要不要国家民族认同”的方向蔓延，“有关方面”居然要求媒体在讨论中不能出现“汉奸”二字；居然立刻示威性地在“国家大剧院”安排公演汉奸婆娘张爱玲的另一作品《红玫瑰白玫瑰》……如果“有关部门”不是吃了台湾人的贿，那这一切就是正式的“官方表态”：《色·戒》与“十七大”要建立的“核心价值观”不但不矛盾，而且完全一致——否则何必如此力挺？这问题的性质就大不一样了。援引此例，类似的汉奸片都可以理直气壮纷纷出笼。肯定了《色·戒》，就认同了“人权高于主权”。那下一步呢？“绝对不抵抗”？

《色·戒》的客观社会效果是什么？且看如下评论：

——“爱情的珍贵表达其‘贞操’和‘性’，却要献给国家、民族的‘抗战’事业，个体与国家利益的要求就必定要牺牲一个女子的感情和身体吗？王佳芝只是不能控制自己的感情而已，一个肌肤相亲那么久的男子，要她完全的冷血，这本身也是抹杀了人性的要求。不管对于国家这个男人扮演了什么角色，对于王佳芝来说，他仅是个疼爱怜惜过她的人，那一丝不知是否出于真心的温情，让她忍不住想要抓住，因为这正是她最渴望而又最缺乏的东西。那些口口声声国家民族的人，可曾对她有过一丝的关心么？”

——“那些批评《色·戒》的，诚如君言，是一群可怜的失去了灵魂为虎作伥的鬼而已，不值一哂。”

——“作为一个女人的王佳芝，她的身与魂，其个体在中国道德谱系中可见丝毫的存在空间？与易先生比，王的父亲和爱人甚至连一点、一丝虚假的关心与怜悯都没有。对于易的‘真假’，判别权利在王佳芝。而她最终是用生命的代价作出了抉择的。但看中国，不光彼时，亦在今日，又有几多须眉男人智慧达知‘自由’真谛，并了悟、珍惜‘选择’权利，敢用生命证实之的？”（——注：珍惜“选择”背叛、出卖的“权利”？）

——“真正的人民，关心的是自己的生活，人性不是一堆大道理的空泛堆砌。”

——“凡是参加者（签名抗议公开信）都是无可救药的极‘左’分子！”

……

没有对民族英雄的认同就没有对民族的认同。没有对民族的认同就没有民族凝聚力。借口“人性”而否认民族英雄，这还不是公然破坏民族凝聚力？《色·戒》受到那么多“精英”的吹捧，肯定为“人性”而背叛国家的行为的观点如此泛滥，这样的情况在以色列、俄罗斯、美国等国家可能吗？“胜利者不受责难，民族英雄不受诬蔑”，世界上还有哪个国家哪个民族会如此丑化自己的民族英雄？还有哪个国家哪个民族会有“爱国贼”、“愤青”这样如此有“独创性”的“发明”？中国史书历来如何评价“诬陷民族英雄、迫害爱国志士”？“奸佞当道，残害忠良”。——中国历史上每逢“朝中有奸臣”，往往后果是什么？国破家亡。——这是不是民族危机？

（2）、用“文明认同”取代“民族认同”

凡真正爱国的，无不坚持一条：一切最后都要落实到有利于让中国好起来。

凡真正卖国的，无不坚持一条：一切最后都要落实到有利于让外国搞垮中国，还说这是在为中国好。

坚持“民族认同”的前提下批判地吸收外国文明的优秀部分是爱国。只要“认同外国先进文明”不要“民族认同”是卖国，甚至是种族灭绝：汪精卫也可以说他当汉奸是“认同外国先进文明”。欧洲人灭绝印第安人、希特勒灭绝犹太人也可以说是在“认同外国先进文明”——为“先进文明”扫除障碍，消灭“落后劣等种族”。马克思主义属于“西方先进文明”，王明只“认同西方先进文明”而不要“民族认同”，所以一切听苏联的，当“百分之百”的“布尔什维克”。毛泽东则坚持在“民族认同”的前提下“认同先进西方文明”。他说：“中国共产党人必须将爱国主义和国际主义结合起来。我们是国际主义者，我们又是爱国主义者，我们的口号是为保卫祖国反对侵略者而战。”“爱国主义就是国际主义在民族解放战争中的实施。”

把“认同外国先进文明”置于“民族认同”之上是为分裂国家制造理论根据。“台独”就是这个“理由”：留在中国妨碍了我的“人权”、“民主”、“自由”。“藏独”、“疆独”也都是这个“理由”。你把“认同西方先进文明”置于“民族认同”之上，那自然就承认了“人权高于主权”。中国任何一个省、任何一个地区、任何一部分的任何人都可以以此为借口闹独立：既然“认同西方先进文明”高于“民族认同”，那我只要随便编个“理由”，声称脱离中国有利于我的“认同世界先进文明”，那就万事大吉。

“坚持在‘民族认同’的前提下批判地吸收外国文明的优秀部分”如同人吃饭：吃进自己肚子，消化吸收变成自己的一部分。

“只要‘认同外国先进文明’不要‘民族认同’”如同把自己让别人吃，或把器官移植给别人：自己的命不要了，“认同”到别人肚子里了，由此也算“变成了‘先进文明’的一部分”。

“主流精英”们大肆宣扬“自由”、“民主”、“人权”是“人类共同的价值观”、“具有压倒一切的重要性”、“必须从‘革命高于一切’的传统束缚中解放出来”，这实际也是在为搞垮中国制造理论根据。

第一，“自由”、“民主”、“人权”等等都是虚玩艺，没有什么靠得住的客观标准。“自由”不“自由”、“民主”不“民主”、“人权”不“人权”全凭“精英”嘴上说了算，谁有“话语权”谁说了算，谁财大气粗谁说了算。俄罗斯为了当上“民主国家”，又是裁军又是“休克疗法”，价值成千上万亿的导弹、战略轰炸机、核潜艇说炸就炸，说拆就拆，说毁就毁。国外基地不要了，军队削减了，战略要地放弃了。忙活了半天，不知费了多少劲，美国仍然拒绝承认它是“民主国家”，又是北约东扩又是支持车臣叛乱……俄罗斯那么多倾家荡产的损失仍然换不来一个虚无缥缈的“民主”，最后终于死了心，再也不迷恋那个“民主”虚名，重新往回拣那些白白放弃了的实实在在的东西：重新武装、恢复战略轰炸机的巡逻……早知今日，何必当初？就为了那么个虚张声势的“民主”“自由”，白白丢掉了多少国家利益！这买卖亏得太大了。

这种“用虚的换实的”把戏实在是无本万利的好买卖。美国用它把俄罗斯耍得一愣一愣的。中国的“精英”们也不甘落后，同样狮子大开口：把政权交给我就叫“民主”，不让我当政就是“独裁”。——别看中国的“主流精英”们言必称“民主”，其实什么是“民主”他们自己也说不清做不到。譬如北大，不是号称“民主自由大本营”吗？实际呢？“那些批评骂我的人，他的道德连我一个脚后跟都没有！”——用自己都实现不了的东西当国策，开什么玩笑？！但是人家就愣有本事把这种谎话说得一本正经。这就是“用虚的换实的”把戏的奥妙：你置之不理就是不“民主”，你信以为真就非解体不可。几句空话就能毁灭一个国家——以前没人相信，现在有俄罗斯前车之鉴，中国人能不相信吗？

第二、“主流精英”们所谓的“自由”、“民主”、“人权”都是假的。

他们的“人权”的实际含义是“精英”们要有“欺人权”。

他们的“民主”的实际含义是“精英”们要“主民”。

他们的“自由”的实际含义是“我自由奴役你”。

——且看这条报道：“工人为争取权益拒绝超时加班被指煽动罢工遭解雇”。

中国法律禁止罢工（这也是“改革开放”的“成果”）。所以才会有“煽动罢工”这种罪名。无权罢工，就是说，干也得干，不干也得干。（现在全国的“打工族”，不管是白领还是民工，动不动超时加班的有多少？无加班费或加班费微不足道的有多少？敢拒绝这种超时加班的有多少？）——什么人属于“不干也得干”？奴隶。奴隶有“人权”吗？按“精英”们说法，现在是“中国人权状况最好的时候”。“人权状况最好的时候”的工人没有罢工权，究竟是工人的人权不算数呢，还是工人不算人？为什么“精英”这么多年闹“修改宪法”从来不关心什么“罢工权”，只关心“物权”？“精英”就是如此“保护人权”？“精英”稍不如意就大哭大闹，“伤痕文学”满天飞。而现在工伤事故矿难伤亡人数比“伤痕文学”里的“精英”多了多少倍？“精英”们吭过一声吗？创作过“伤残文学”、“伤心文学”、“伤亡文学”吗？这一切难道不证明“精英”的“人权”只包括他们自己，实际是他们的“欺人权”吗？

——茅于轼说：“社会必须由精英治理”“社会进步是靠精英的。社会没有了精英，必然退步。”张维迎说：“那些批评骂我的人，他的道德连我一个脚后跟都没有！”

这足以说明“精英”们的“民主”是什么玩艺了：他们说了算叫“民主”，他们说了不算叫“独裁”。“民主是个好东西”，“大民主”是个坏东西。——只有“精英”参加才叫“民主”，老百姓参加就叫“民粹”，叫“大民主”，叫“无政府主义”。预先规定“社会必须由精英治理”，一切都必须由“精英”说了算，那还“民主”个什么？那不就是任凭“精英”们“主民”吗？

——“精英”一方面口口声声“言论自由”，一方面近三十年“不争论”。（还要“不争论”到何时？难道要以世纪为度量？）

有“话语权”的，“言论自由”得随心所欲。没有“话语权”的，近三十年不得出声。如此“言论自由”，中国“特色”，世界一绝。

把持“话语权”，坚决“不争论”——只许“精英”放火，不许百姓点灯。结果：社会成了骗子社会，中国成了骗子国——不是说中国人人都是骗子，而是说中国人人都不知道谁不是骗子，甚至不知道谁大概不是骗子：现在不管是谁说话，不管其身份如何，不管是什么话题，不管是“虎照”还是“嫦娥照”，老百姓敢随便相信吗？碰上任何事物任何人都得象破案：搜集证据，研究分析，如履薄冰，小心翼翼——都被骗怕了。骗子太多了。上当太多了。为什么？把持了“话语权”的“精英”在“言论自由”的借口下滥用言论自由，把“言论自由”变成了诈骗犯罪工具而不受任何惩罚。经济诈骗多少还有法可管（虽然经济诈骗犯落网的概率并不高，惩罚也不严厉）。思想诈骗、政治诈骗、学术诈骗则根本不受任何惩罚，一切都有“言论自由”罩着。结果：吹牛不上税。撒谎不犯罪。诈骗最实惠——“骗出一个体制来”。

“精英”整天说“阶级斗争无孔不入”的日子多么恐怖，而如今“说谎诈骗无孔不入”的日子就不恐怖吗？亲戚朋友、父母子女、夫妻兄弟……所有这些关系有多少没有被“诈骗”弄变了味？谁知道这些过去普遍认为最可靠的关系现在会不会被用来诈骗？过去的“阶级斗争无孔不入”至少还有光明正大的理由，还可以说是为国为公。而现在无孔不入的诈骗呢？

“骗子社会”的结果是谁说话也没人信。“谁说话也没人信”意味着谁说话都白说。“说话白说”等效于“不说”。“不说”等效于取消发言权。——发言权都被取消了，还有什么“言论自由”？滥用“言论自由”的结果等效于剥夺了所有人的“言论自由”——这就如同在大城市取消交通警察、红绿灯，说是为了车辆的“行驶自由”，结果是交通阻塞，谁也动弹不得，取消所有人的自由。“绝对自由”的结果是“绝对不自由”——这就是“精英”滥用“言论自由”的结果。大家都失去了“言论自由”，有“话语权”的“精英”就有了绝对自由：你爱信不信。反正你整天只能听到我的大喇叭在哇啦哇啦。时间长了你信也得信，不信也得信，最后只能听我的。

列宁说：“吹牛撒谎是道义上的灭亡，它势必引向政治上的灭亡。”“在政治上采取诚实的态度是有力的表现，如果在政治上采取欺骗的态度则是软弱的表现。”

德国诗人海涅说：“生命不可能从谎言中开出灿烂的鲜花。”

中国的“精英”们离得开吹牛撒谎吗？

鲁迅说：“中国把日本全部排斥都行，可是只有那认真却断乎排斥不得。无论有什么事，那一点是非学习不可的。”——“认真”这一条，可以算做“外国先进文明”了吧？别的且不论，撒谎成性而口口声声“认同外国先进文明”的“主流精英”们“认同”这一条吗？

第三，把“认同外国先进文明”置于“民族认同”之上必将导致国家解体。

只“认同先进文明”认不出一个国家来。欧美可以说是同一个文明体系，但仍然必须有各自的民族认同才能确保英国是英国，法国是法国，美国是美国。“认同外国先进文明”可以跟中国毫无关系。任何国家任何人都可以“认同外国先进文明”，何以见得就一定认同个中国出来？如果“认同外国先进文明”高于“民族认同”，那任何地方任何人都可以借口“认同外国先进文明”“认同”到其他国家去，或自立山头闹独立闹分裂。要确保中国是中国，就必须确保民族认同第一。而中国靠什么确保民族认同？过去靠中华文明、靠孔孟之道。但自鸦片战争以后，旧的中华文明已经敌不过西方文明的挑战，已经不能指导中国人自立，已经不能再保护中国人的自尊自信。环顾中华大地，对旧中华文明“取其精华、去其糟粕”批判地继承、对外国先进文明兼收并蓄、拥有强大完整的哲学体系、理论联系实际、经得起实践检验、为绝大多数中国老百姓所信服、能指导中国人认识世界改造世界、在西方文明面前能够顶天立地的只有毛泽东思想。去掉了毛泽东思想，今天能指导、能激励、能凝聚中国人的还有什么？“蒋介石日记”？“曾文正公家书”？“黑猫白猫”？临时抱佛脚现编现造？

中国现在贫富之差惊人，富人之富难以想象。任何有常识的人都知道，即使在资本主义国家，靠正当商业运作也绝对不可能在如此短的时间内积累如此巨额的财富。如此非正常的暴富只能是犯罪。——有些人如同抗日战争胜利后国民党的“接收大员”一样“劫收”“国有资产”暴发——如此巨额的犯罪在任何正常的法制国家都属于非正常现象，都不能容忍。而在中国不但容忍，不但积极保护：“赦免原罪”、“宽容不规范”，而且还想方设法让老百姓对这种犯罪习惯、同情、羡慕、尊敬、自觉服从，把罪变成了“功”。毛泽东挽救了中国，保卫了中国，强大了中国。从中华民族的角度看，这是丰功伟绩。但毛泽东的功全被说成了“罪”——把罪说成“功”，把功说成“罪”，黑的成了白的，白的成了黑的——以如此是非颠倒为基础的“新理论”能有什么生命力？何况如此“理论”充满了粗制滥造、信口开河，没有深邃的哲学内涵，没有严谨的理论体系，自相矛盾，谬误百出。这样的理论体系是不折不扣的骗子理论体系。不管堆了多少华词丽藻、马屁牛皮，仍然是“沐猴而冠”——“穿上龙袍也不是太子”。想靠这样的冒牌货凝聚中国人，只能是水中捞月，缘木求鱼。

不管是“增量民主”还是“休克民主”，反正中国“精英”的最终目的是“自由选举”。“自由选举”拼的是“话语权”——谁有“话语权”谁赢。谁的“话语权”大谁赢。从这个角度讲，“话语权”就是政权。“精英”们别的本事没有，卖嘴的功夫天下第一，最不怕的就是拼“话语权”。可见“自由选举”是“精英夺权”的代名词。“精英”们总是“言必称民主”——“‘精英’民主”。讲“精英民主”必讲“自由选举”，而“自由选举”就是“选自己”——不，是“拔”自己，或曰“扣着屁眼上楼——自抬自”。“精英”们对“精英民主”这么着迷，因为这也是用虚的捞实的那一套，“空手套白狼”，单凭三寸不烂之舌通吃天下。（这如同生活中的“恋爱专业户”，开口闭口就是“表现你的诚意”（民主精神）。怎么个“表现”法呢？房子、车子、票子、金子、存款、时装、高级化妆品、国际旅游、七大姑八大姨的礼物……一切的一切，舌头一卷：“诚意”，就通通笑纳了。不把对方老底挖光决不罢休。如果傻乎乎用自己的一切实实在在的财产换这个虚无缥缈的“诚意”，把老本赔光人家又飞了，永远不算“有诚意”。“主流精英”的“精英民主”也是这样：一句可以随心所欲解释的“民主”就把整个政权接管了，全部国有资产都盘过来了，这买卖多合算？这也算模仿了阳谋中“虚的换实的”——只不过阳谋是为国家争利益，光明磊落。而这“精英民主”则是为自己谋私利，见不得人。）

“自由选举”有个前提：必须得到相对集中。如果每个人都投票选自己，那选跟不选没什么两样。“精英”们已经把中国变成了个骗子国，老百姓谁都信不过。也就是说，谁也没凝聚。没凝聚就没集中。没集中则必分散，分散的极端就是分裂，国家解体。——不管“精英”说得如何天花乱坠，中国的历史经验有一条：只要中央集权削弱，必定天下大乱。一旦“认同外国先进文明”超越民族认同，这种情况势不可免。——台湾闹“自由选举”都快闹成两半了。为什么？只有“认同外国先进文明”而没有“民族认同”：是“认同中国”，还是“认同台湾”？这么块豆腐干大的地方都能闹成这样，何况中国大陆这么大地方？已经“政令不出中南海”了还要闹“削权”，不是想搞分裂又是什么？

如果靠损害中国的民族利益吃饭的人势力越来越强大、能凝聚中国人的毛泽东思想被否定被丑化被淡化、“认同外国先进文明”超越民族认同、“人权高于主权”之类观念越来越盛行，那维持中国人的凝聚力何在？中国如何避免分裂？这难道还不是空前的民族危机？

（3）、瓦解中国是“精英”们私利的需要。

不要以为只有外敌入侵、国难当头时才会有人当汉奸。不要以为只有外敌才想搞垮中国。不要以为所有中国人都自然而然地希望中国强盛。不要以为是中国人就自然而然地不希望中国瓦解。世界上的事是复杂的。人们脑子也不能那么简单。

观察分析一下：现在那些对毛泽东恨之入骨、无孔不入百般辱骂的人，都是些什么样的人？

——有多少是打过仗的？有多少是打过胜仗的？有多少是以弱胜强打过胜仗的？有多少是一贯以弱胜强、从无到有、从小到大打胜仗的？

——有多少是搞出了实实在在的显著成果如“两弹一星”、“杂交水稻”、“人工合成胰岛素”之类的？

——有多少是造福一方百姓、得到老百姓长期的交口称赞的？

——有多少是拿出了经得起实践检验、放之四海而皆准、能够指导人们取得实践的成功的理论的？

几乎一个没有。

最恨毛泽东的人都是些什么样的人呢？

——几乎全是“精神贵族”，自以为高人一等、以“精英”自居的。

——几乎全是没有经过长期实践锻炼检验的。

——几乎全是学文的，包括学理工学不出来、一事无成、不得不改行学文混饭的，如茅于轼、刘吉之类。

——几乎全是“狗掀帘子——全仗着嘴功”，只懂得卖嘴规律，不懂得客观规律的。

——几乎全是只有个人的成功、没有集体的成功、个人的成功只取决于主观的夸张、不取决于客观的实践的。

——几乎全是靠个人单打独斗加后台混饭吃，不需要集体协作和团队精神的。

——几乎全是只知道替自己打算，不知道也不会替别人打算、不懂调度协调、不懂“全国一盘棋”的道理的。

——几乎全是只会解释世界，不会改造客观世界的。

——几乎全是“拉屎不揩腚”、从不为自己的言论主张的后果负责的。

——几乎全是撒谎赖账不眨眼，根本不知“诚信”“道德”为何物的。（“打左灯向右拐”、“能做不能说”）

——几乎全是将个人利益、个人恩怨、个人好恶、意识形态置于民族利益之上的。

——几乎全是“认同西方文明”超越民族认同的。——不认同毛泽东，所以不认同新中国，所以“人权高于主权”。

……

这些人有两大共同特点：第一，精神贵族，以“精英”自居，总想高人一等，骑在普通老百姓头上作威作福。第二，没有真才实学，全靠三寸不烂之舌招摇撞骗、滥竽充数、不劳而获。

这就决定了这种人的个人利益与中国的民族利益水火不相容。

中华民族要真正富强，第一意味着不受别人欺负。要不受外人欺负就不能容许国内存在人欺负人。这就使“精英”们不能高人一等，不能骑在别人头上作威作福。第二意味着要按客观规律办事，容不得弄虚作假——弄虚作假能使个人发财，但不能使国家强盛。这就使“精英”们无法滥竽充数，无法不劳而获。

换句话说，中华民族真正富强了，“精英”们就不好混了，当不成“精英”骗不了人，更当不了“富人”发不了财了。只有把中国搞垮，让中国分崩离析，“精英”们才能如鱼得水，既能骑在老百姓头上作威作福当“精英”又能不劳而获靠耍嘴皮子发财。

毛泽东使中华民族富强起来。中国人凡是希望中国富强的，凡是靠实实在在变革客观世界创造财富的都认同毛泽东，因为自己的亲身实践告诉他们毛泽东的那一套正确。而靠中华民族衰败才能混日子的“精英”则恨毛泽东，因为毛泽东使中华民族富强妨碍了他们巧取豪夺。

有人很不理解：“精英”们难道不是中国人吗？搞垮中国对他们有什么好处呢？“覆巢之下无完卵”。中国垮了，中国人受外国人欺负，“精英”们难道能例外吗？

这叫“以君子之心，度小人之腹”。

且看这一段报道：“2006年11月16日，厉以宁到南京财经大学，向南京学子传授‘管理经’”。

厉以宁讲了个故事：“有两个人到郊外去旅游，忽然听到老虎叫，于是两个人都慌了，其中一个人赶紧蹲在地上，从背包里把运动鞋取出来——这样跑得快啊。第二个人奇怪地问，老虎跑得比人快，你换运动鞋有什么用？此人回答道，我当然知道老虎跑得比人快，但只要我跑得比你快就行了。第二个人不慌不忙，脱掉鞋子爬上了树。老虎到了，树上的人它吃不着。老虎不会爬树，继续往前追把换运动鞋的人吃掉了。”厉以宁说，这个笑话说明了一个道理，在国际竞争中，大风大浪是难以避免的，光会躲避是没有用的，关键是要有绝招、有过硬的本领。

这正是“主流精英”们的心态：老虎吃人不要紧，吃不到自己就行了。中国垮了、中国人受外国人欺负不要紧，自己不受欺负就行了。自己受欺负不要紧，有其他人可欺负就行了。——“精英”们人人有“运动鞋”，个个善“爬树”，无论是上蹿下跳还是拔脚飞逃都非常人可比，根本不在乎“老虎伤人”。中国垮了，“精英”们可以当工头，当奴隶总管，当刽子手，当收尸队，当翻译官，当“皇协军”，当汪精卫，当“二狗子”……如果中国分裂了呢？那更好，能立刻创造出一大堆“总统”“元首”“国家领导人”的位子来。“精英”们“过把瘾”的机会岂不比现在大多了？——现在中国一个县委书记、一个大学校长就敢搞“阅兵”，可见觊觎“国家元首”之位的大大小小的野心家有多少，“独立王国”到了何等程度。——总之出路大大的，金票大大的。这比中国富强了没人可欺负、没法滥竽充数招摇撞骗舒服得多——这种账，只知道靠国家富强生存的人算得出来吗？——苏联不就是这样垮的吗？虽然是超级大国，虽然国家强盛，但这一切对“精英”们个人有多大好处？不把苏联闹垮，他们能当上亿万富翁吗？——明白了这点，就能明白一个无情的事实：“精英”们的私利不是国家富强民族兴旺，而是国家瓦解民族灾难——前苏联就是个例子：“精英”们为了自己的私利，连超级大国都不惜干翻，何况中国？只有这样才能明白为什么“精英”那么仇恨使中华民族站起来的毛泽东了，为什么那么起劲地、不遗余力地摧毁中华民族的凝聚力了，为什么那么积极鼓吹“认同外国先进文明”高于“民族认同”了。

为私利而决心要把中国搞垮的“主流精英”当了道，中国能不遭遇空前的民族危机吗？

** 毛泽东的旗帜永远飘扬

如今认同毛泽东意味着什么？

——意味着民族利益高于个人利益，高于个人恩怨，高于个人好恶，高于个人私利。

——意味着为人民服务，为绝大多数人着想。

——意味着认同中华民族，认同中华文明，认同“批判地继承传统文化，吸收外来先进文化”。

——意味着“世界上怕就怕‘认真’二字，共产党就最讲认真”。

——意味着谦虚谨慎、戒骄戒躁、理论联系实际、密切联系群众、批评与自我批评、实事求是、不尚空谈。

——意味着“我们中华民族有同自己的敌人血战到底的气概，有在自力更生的基础上光复旧物的决心，有自立于世界民族之林的能力。”“这个军队具有一往无前的精神，它要压倒一切敌人，而决不被敌人所屈服。不论在任何艰难困苦的场合，只要还有一个人，这个人就要继续战斗下去。”“战略上藐视敌人，战术上重视敌人”。“战略上以一当十，战术上以十当一”。

——意味着独立自主、自力更生、自尊自重、靠自己的双手改造世界。

——意味着“人民，只有人民，才是创造世界历史的动力。”

……

总之意味着一切积极向上的东西。

认同毛泽东的人决不会认同撒谎诈骗、贪污腐化、卖国求荣、欺压百姓。

看一个人的人品良知，看看他对待毛泽东的态度就知道了。

“精英”、贪官们对老百姓的嚣张程度与民间的毛泽东热恰成反比。

1993年毛泽东诞辰一百周年时，天安门广场只有一朵孤零零的小白花。那时是“毛泽东热”低潮的时候，也正是砸“三铁”、“减员增效”、“下岗分流”、“买断工龄”、“国有企业重组”、“出卖国企”、“医疗产业化”、“教育产业化”、“住房商品化”、“MBO”、“扩大内需”、“公务员加薪加薪再加薪”、“改革代价论”、“靓女先嫁论”、“冰棍论”、“烂苹果论”、“吐唾沫论”、“社会财富向精英倾斜论”、“取消社会福利”、“为了达到改革的目标，必须牺牲一代人，这一代人就是3000万老工人。8亿多农民和下岗工人是中国巨大的财富，没有他们的辛苦哪有少数人的享乐，他们的存在和维持现在的状态是很有必要的”、“最低工资标准对工人没有好处”、“中国的贫富差距还不够大”、“腐败有利论”等等谬论最猖獗的时候。

民间的“毛泽东热”一加温，“精英”们的嚣张气焰就有所收敛。民间的“毛泽东热”越热，“精英”们就越泄气：“非毛化”变成了“去毛化”，不敢再与毛泽东公然叫板，只能搞些偷偷摸摸的小把戏，想方设法让老百姓忘了毛泽东。“改革代价论”也不那么嚣张了，从“杀鸡取卵”、“竭泽而渔”“和谐”为“可持续剥削”。现在则更进一步，把毛泽东供进了“十三陵”：逢年过节请出来上上香，隆重拜祭一番以示“基业来路正当”。——当然碰上具体事情还是要把毛泽东扔到一边，只按自己的主意办。——这比以前那些杀气腾腾的反毛叫嚣算是进步多了。

为什么？

“毛泽东热”存在本身就代表了一种民心，一种情绪，就令“精英”想到最不愿想到的话：“哪里有压迫，哪里就有反抗”。“造反有理”。“毛泽东热”如同一个巨大的幽灵，在“精英”的乐土上徘徊不去，使他们不得不担心肆无忌惮穷凶极恶的结果将会如何。

毛泽东的旗帜是今天唯一能够凝聚中国人的旗帜。

当“精英”们肆无忌惮用“认同外国先进文明”摧毁中国人的民族认同之时，能够凝聚中国人、振奋中国人、激励中国人、保护中国人的民族自尊、自信和自爱的，只有毛泽东思想。其他一切都不能给中国人带来信心和自豪，更不能对中国人有指导作用。

如果中国人要能够粉碎“精英”们分化瓦解中国的阴谋，战胜新的民族危机，就只有依靠毛泽东思想。——战胜新的民族危机的最好办法就是大力宣传毛泽东思想，尤其让青年一代真正了解毛泽东。在“精英”们把持“话语权”的情况下，必要时就只能不怕麻烦、不怕劳苦，一个人一个人地做工作，用“小米加步枪”对付“飞机加大炮”。

如果中国被“精英”们搞垮、分裂，也只有依靠毛泽东思想才能重新统一中国。

中国人终将在毛泽东思想的旗帜下重新团结起来。

** 附录：

*** 关于“亩产万斤”评价一下思闻和天父的材料

数　学

2007年12月10日

 

 

天父上了一个帖子，名字叫《【毛泽东】在亩产万斤时在干啥？》。当然，天父的观点倾向于亩产万斤，共产风等错误，主要是刘少奇的错误。而思闻来了一个反击，他也上了一个帖子《【毛泽东】在亩产万斤那年干了啥？》当然，思闻是认为毛泽东应当为亩产万斤，共产风的错误负主要责任。

我看了天父的帖子，也看了思闻的帖子。本帖子站在中间立场，分析一下两个人的帖子的内容。而且，尽量假定两个人的帖子是对的，符合历史事实的。

首先，人民日报报道亩产万斤失实的过程的日期序列是：

1958年6月8日，《人民日报》报道河南省遂平县卫星农业社5亩小麦平均亩产达到2105斤。1958年6月12日，又报道该社放出的第二颗“卫星”，2.9亩小麦试验田，亩产达3530斤。1958年6月16日，新华社报道，湖北省谷城县星光社王明进试验田的小麦亩产4353斤。1958年6月23日，《人民日报》报道湖北省谷城县先锋农业社小麦试验田亩产4689斤。1958年7月12日，《人民日报》报道河南省西平县城关镇和平农业社2亩小麦创亩产7320斤的记录。1958年7月18日，《人民日报》报告福建省闽侯县连坂农业社2.6亩早稻试验田亩产5806斤。1958年7月25日，新华社报道，江西省波阳县桂湖农业社干部试验田早稻亩产9195斤。1958年8月13日，新华社报道，湖北省麻城县溪建园一社出现“天下第一田”，早稻亩产36900斤。1958年9月5日，《人民日报》报道广东省连县1.73亩中稻亩产60437斤?

截止1958年9月25日资料，小麦亩产最高数是青海柴达木盆地赛什克农场第一生产队的8586斤，稻谷亩产最高数为广西环江县红旗人民公社130435斤。

那么，这个错误是谁有责任呢？如果以我这么个中间人的态度，我就会认为毛泽东和刘少奇都有责任。因为这两个人都说过一些过头话，比如思闻摘的：

“1958年9月5日，毛泽东说：“钢铁明年可能超过2千万吨。总而言之，明年是基本上赶上英国。除了造船，汽车，电力这几项外，明年都要超过英国。15年计划，2年基本完成。”（《在第15次最高国务会议上的讲话》，《建国以来毛泽东文稿》第7册，第381页）”

而天父摘的：

“1958年9月10日至11日，刘少奇到他的“共产主义试点公社”河北徐水县视察，当他听到有人说，给山药灌狗肉汤，亩产可以收120万斤时，即说道：“那么作真有效果吗？哈哈！你们可以养狗啊！狗很容易繁殖吗！”（1958年9月18日《人民日报》）

既然摘的是人民日报，看来也不会假，说明刘少奇当时也相信亩产可收120万斤。

因此我认为，给刘少奇或者毛泽东作无错辩护，都是不通的。毛泽东也是人不是神，无可能不犯错误，尤其是在社会主义刚刚建立才两年，不可能对社会主义社会有充分的了解，也要通过实践来认识社会主义社会。当然，刘少奇也一样。

但是，我认为毛泽东之所以成功，并不在于他从来不犯错误，而在于他一旦发现错误，就要纠正。

那么，从上面的日期知道亩产万斤的谎言大约从六月开始，持续到了9月25日。那么什么时候纠正的呢？什么时候开始不提亩产万斤了呢？是谁率先发表了言论纠正这个错误的呢？这才是历史的一个重要课题。

我认为，到了一九五八年十一月二十八日至十二月十日中国共产党八届六中全上，正式纠正了亩产万斤的错误，共产风的错误。请注意这个会议开了有十二天，如果是一个专制的会议，怎能开如此长的时间？我当然能够想到有许多的争论。这个全会通过了一个《关于人民公社若干问题的决议》，这个决议可以说是专门针对共产风的，摘引其中的两段：

“应当着重指出：在今后一个必要的历史时期内，人民公社的商品生产，以及国家和公社、公社和公社之间的商品交换，必须有一个很大的发展。这种商品生产和商品交换不同于资本主义的商品生产和商品交换，因为它们是在社会主义公有制的基础上有计划地进行的，而不是在资本主义私有制的基础上无政府状态地进行的。继续发展商品生产和继续保持按劳分配的原则，对于发展社会主义经济是两个重大的原则问题，必须在全党统一认识。有些人在企图过早地‘进入共产主义’的同时，企图过早地取消商品生产和商品交换，过早地否定商品、价值、货币、价格的积极作用，这种想法是对于发展社会主义建设不利的，因而是不正确的。”

这就是在否定“共产风”，但是这里面批评的“有些人”究竟是谁？我从理工科思维的角度讲，那是一个“我不知道”。是毛泽东吗？如果这样，能不能认为八届六中全会对毛泽东的一些想法进行了严厉批评呢？

这个决议还决定要对人民公社进行整社，整社的办法呢？这个决议中写道：

“在进行整社的时候，首先要求领导干部认真地进行自我批评，虚心地听取群众的意见，在这个基础上，放手发动群众大鸣大放大辩论，贴大字报，表扬好人好事，批判坏思想坏作风，总结经验，明确方向，开展一个深入的社会主义、共产主义思想教育运动。”

但是还是来谈个人责任吧。我注意到了天父的帖子中有毛泽东在1958年纠正共产风的一系列动作和讲话。在这一点上，我觉得思闻也应当寻找一些有关刘少奇在1958年纠正共产风的一系列讲话，最早的时间是什么？如果刘少奇纠偏的讲话要早于毛泽东的纠偏讲话，倒也可以认为是刘少奇率先发现了共产风的毛病。甚至也可以同时找一下彭德怀最早纠偏的讲话。因为上面已经提到了八届六中全会，还在1958年就纠正了共产风，那么彭德怀为什么在1959年的夏天还那么大的火气？而在历史的宣传上怎么就讲成了是彭德怀在1959年才开始的纠偏呢？

这些我都感兴趣，但是事先不预设立场，再看二位提出新的证据吧。

再说一遍，就是我认为拥刘方缺少刘少奇在1958年末纠偏的讲话。只是知道约在1959年还是六零年以后，有过一个“三分天灾，七分人祸”的说法，但是这个说法并不是理论上的说法，刘少奇有没有辅以一系列理论上的研究和纠偏？比如说，从马克思主义理论出发共产风为什么不对的研究？这一点还需要思闻提供进一步的材料。

*** 毛、刘大跃进前后言论对比录

资料来源主要为网上《毛泽东力纠五风》一书，该书引用的是当年的报纸和文件等第一手资料，以及吴冷西等人的回忆。部分资料来源为薄一波的书。资料来自不同的段落，以A、B、C、D等分开。

——黄岭峻

一、跃进前及跃进初（1958年8月以前）

甲、刘少奇的有关言行及相应报道

A

1958年6月14日，刘少奇在同全国妇联党组织负责人的谈话中说：“中宣部印了一本有关空想社会主义的资料，其中有一段是康有为《大同书》写的。康有为27岁（一说25岁）写《大同书》，要破除九界，即国家界限、男女界限、家庭、私有财产……。毛泽东讲话时，也提到康有为的《大同书》（按：毛泽东在《论人民民主专政》一书中说：‘康有为写了《大同书》，他没有也不可能找到一条达到大同的道路。’《毛泽东选集》第四卷，第1471页－－笔者注）空想社会主义者的想法，在那时没有实现的条件，现在马克思主义者抓住了阶级斗争，已经消灭阶级或正在消灭阶级的过程中，这样，把空想社会主义者不能实现的空想实现了。”刘少奇在谈话中把托儿所、公共食堂等这样一些生活服务组织视为“大家趋向共产主义”。他提倡家务劳动社会化、解放妇女劳动力、办食堂、托儿所、洗衣房等服务性事业。他说：“可以搞很多事业，象空想社会主义者所说，小孩子多大年龄就到什么地方去，到处有花园，老人有养老院，还有戏院、小学、图书馆、电影院……搞得好可以达到这种境地。我们到共产主义不要多远，十五年可以赶上美国，再有四十年、五十年中国可以进入共产主义。’”

B

1958年6月30日，刘少奇在同《北京日报》编辑谈话时说：“共产主义社会的基层组织，现在开始实验”（按：当时搞农业合作社小社并为大社，有的包括工、农、商、学、兵内容，但还没有“人民公社”的名称，刘少奇称之为“共产主义社会的基层组织”－－笔者注）。“恐怕不能像现在这样，种地的净种地，做工的净做工，现在就要搞工农商学兵。”他还作了解释，“不能搞单打一，现在农业合作社已经开始办工厂、商店、银行、服务事业、洗衣房、食堂、学校，都归它。以后就在工厂、农村、学校发枪操练，工农商学兵都有了。他提出：‘我看，三、四十年之后，可以到共产主义社会，你们看，要不要这么长？”

C

1958年7月5日，刘少奇在北京石景山发电厂同工人谈话时说：“工厂要办食堂、托儿所、洗衣店，办学校、办农场，发点枪给大家操练。总之，工农商学兵全都自己干。”又说：“这样下去，我们的国家，我们的民族大有希望，不要几年就好了。现在苦干几年很有必要，不然过不了关，苦干几年就不那么落后了。现在赶上英国不是十几年，二年三年就行了。明年后年要超过英国，这不是假的。十五年超过美国的问题，其实也用不了十五年，七、八年就行了。大家干劲这么大嘛！不计上下班，干完就算数，有这么股劲，我看七、八年就行。”又说：“一是党的领导，一是大家努力，好好干，大有希望。中国进入共产主义不要好久，你们大家都可以看到共产主义。”

D

1958年7月19日，刘少奇在天津讲话中提出：“在并社时，‘一乡一社’、‘政社合一’。”他说：“一个乡一个社，将来是否叫社，农庄也包括不了，因为有工业、有学校、有商业、又有民兵，生孩子也有人管，实际上是共产主义的基层结构，这是组织起来的公社，有工业、有农业、有学校，生老病死都在这里，这是共产主义公社。”（许全兴：《毛泽东晚年的理论与实践》，中国大百科出版社，1993年版，119、120、175、176页）

E

1958年7月14日到18日，刘少奇到山东省寿张县视察，报道说：“少奇同志还非常关心共产主义生活方式萌芽的出现。他说，现在有的地方组织了公共食堂、托儿所、缝纫组等等，使家务劳动社会化。”（1958年8月4日《光明日报》）

F

1958年8月6日，刘少奇派中共中央农村工作部副部长陈正人，带着康有为的《大同书》，到河北省徐水县搞共产主义公社试点，陈正人传达了刘少奇同志关于搞试点的指示，还把康有为的《大同书》送给一些人。（赵云山、赵本荣《徐水共产主义试点始末》《党史通讯》1987年第六期）徐水县委第一书记张国忠立即宣布“跑步进入共产主义”，成立公社，树木归集体，房屋也由公社统一分配，社员实行工资制，社员和干部大搞实验田，计划一亩山药产120万斤，一棵白菜500斤，小麦亩产12万斤，皮棉亩产5000千斤。这些将要发射的卫星庄稼，是在迈向共产主义的人民公社殿堂上空飘扬的鲜明耀眼的红旗，也只有人民公社才能竖起这样的红旗。试想想，一个二分地沼气山药堆就得花去成百个人工，成本更是不可计算，这除了几万人的人民公社，那一个普通农业社能够办得到！（康濯：《徐水人民公社颂》1958年9月1日《人民日报》）

G

1958年7月14日到18日，刘少奇到山东寿张县视察，报道说：少奇同志在参观了台前社亩产将达3万至5万斤的玉米，3万至5万斤的谷子，30万斤地瓜和宏伟社亩产15000斤籽棉的丰产后，赞扬他们说：“你们压倒了科学家，他们没敢想的，你们做到了，这是个革命。”这一讲话一传出，全国各地的实验田丰产田纷纷把原来亩产千几斤、几千斤的牌子换为几千斤、上万斤甚至十几万斤的牌子。假报导的丰产数也由亩产几千斤一跃报道亩产数几万斤，都顺着刘主席的爱好大胆地吹起来了。

H

1958年8月，刘少奇派人到山东寿张县进一步了解那里的高额丰产情况，写回的调查报告说：“今年寿张县的粮食单位产量，县委的口号是‘确保双千斤，力争三千斤’，但实际在搞亩产万斤粮的高额丰产运动，一亩地要产5万斤、10万斤，以至几十万斤红薯，一亩地要产一、两万斤玉米、谷子，这样高产的指标，当地干部和群众，讲起来象很平常，一点也不神秘。一般的社也是8千斤、7千斤，提5千斤指标的已经很少，至于亩产一、两千斤的根本没有人提了。”（刘西瑞：《人有多大胆，地有多大产》1958年8月27日《人民日报》）

乙、毛泽东同期的言论和中央的决议

A

吴冷西回忆说：1958年3月，在成都会议期间，毛主席找我谈话，毛主席说：“河南提出苦战一年，实现四、五、八水利化，除四害和消灭文盲。辽宁要实现三自给（即粮、菜、肉自给）。我怀疑是错误的。河南提出今年办四件大事，有些可能做到，有些可能做不到。就算都做到，也不要登报。人民日报硬是要卡住。否则这个省登，那个省登，大家抢先，搞得天下大乱。一年完成不登报，两年完成恐怕也不要登报。各省提口号恐怕时间长一点比较好。我就有点机会主义，要留有余地。”毛主席说：“现在报纸报道要调整一下，不要尽唱高调，要压缩空气，这不是泼冷水，而是不要鼓吹不切实际的高指标，要大家按实际条件办事。提口号，定指标要留有余地”（吴冷西：《忆毛主席——我亲身经历的若干重大历史事件片段》新华出版社，1995年版63、64页）

B

1958年4月中旬，在武昌会议期间，毛主席专门找我就人民日报的宣传问题做了五点指示（吴冷西：《忆毛主席》）：

1

近来报纸的宣传反映实际不够，但也有不实之处。如指标、计划讲得过头了。现在要调整一下，要压缩空气。鼓干劲的话要讲，但不要华而不实。

2

报纸在宣传的时候要慎重，比如说绿化，不能说种一些树就是绿化，要成活，成片，成林，象在飞机上看到湘南、粤北那样郁郁葱葱才算绿化。又如水利化，有的说一年实现的，有的说三年实现的，其实都不能叫“化”，只是改变一些面貌。又如说“四无”，应当相信可以实现，但也不是一两年或三五年可以实现的。一个“化”，一个“无”不要随便宣传已经实现了。即使订规划、提口号，也要留有余地，在时间和空间上说得活一点。否则，说一年或两年完成，那不是以后没事干了吗？要留给后代子孙一些事做。现在说苦战三年基本改变面貌，其实只是初步改变面貌，能否做到还得看一年。

3

报纸的宣传要搞深入、踏实、细致。我们讲多快好省的方针，报纸上不能只讲多快，不讲好省。我们是讲好大喜功的，大而无功，其实不是好大而是好小，不实就是无功。报纸对一些问题，要由小见大，要把许多杂乱无章的事情加以概括，从理论上把事情说清楚。报纸的评论，应带理论色彩，这就是深入事情的本质，抓住了规律。这样把纲提起来，才能使干部和群众方向明确。意识形态上和上层建筑的重要性就在这里。

4

现在全国出现高潮，出现许多新鲜事物，但也鱼龙混杂，泥沙俱下。记者、编辑要提高政治思想水平，能对眼前彩色缤纷的现象做出政治判断，有远见卓识，这不容易，但应努力做到。

5

报纸的问题带有普遍性，不仅人民日报存在，省报也存在，今年夏天要召开全国报纸的总编辑会议，讨论新闻宣传如何改进。此事要告诉陆定一同志，并报中央书记处。（此事我都照毛主席的意见办了。后来陆定一同志说，夏天太忙秋后再说）（吴冷西：《忆毛主席》70、72页）

D

毛泽东说：我们争取在十五年或者更长些时间，在钢铁和其它重工业产品上赶上或超过英国（中国确实在钢铁产量上，用十五年的时间，在七十年代初超过了英国。见薄一波的书）（刘少奇说：现在赶上英国不是十几年，两年三年就行。明年后年超过英国，这不是假的。刘少奇讲：我国十五年超过美国的问题，其实也用不了十五年，七、八年就行了。大家干劲这么大嘛！）

E

毛泽东说：我们的方向，应该逐步地有次序地把工业、农业、商业、学校、民兵，组成一个大公社，从而构成我国社会的基本单位。（刘少奇说：共产主义的基层组织，现在开始实验。恐怕不能像现在这样，种地净种地，做工的净做工，现在就要搞工农兵学商。）F毛泽东说：公共食堂、托儿所等社会性的服务组织，过去已经有了。（即在旧社会的中国、世界资本主义国家早已经有了，不是什么新鲜事……。）（刘少奇说：公共食堂、托儿所、缝纫组，是共产主义生活方式的萌芽。）

二、在大跃进中、后期（1958年9月以后）的言论比较

甲、刘少奇的言行和当时的报道

A

中共徐水县委作了一个《关于最近几年全面跃进规划草案》，送刘少奇看，少奇同志不仅在视察前看过，而且还记得非常清楚，于是少奇同志于1958年9月10日至11日到徐水视察，作了许多深刻而全面的指示：第一，少奇同志感到徐水的“工业发展布局”的“规划仍有些毛病”，于是引用孟子的话“且一人之身而百工之所为备”，精辟地说明了生产计划安排的复杂性和重要性。在肯定了这里公社社员要求实物加货币的工资制以后，也同样用孟子上述的话，指示县委，必须慎重考虑实物加工资的比例，以便满足社员们，复杂的生活需要。第二，少奇同志指示徐水县委按照《礼记》上面的话，修订规划，设法使非生产人员和非生产时间尽量减少。报道说：少奇同志还指示县委对全县工、农、后勤和文教各方面的人，力算一笔细账，又引证《礼记》上面的话“生之者众，食之者寡，为之者疾，用之者野，则财恒足矣！”让县委根据上述细账，设法使非生产人员和非生产时间尽量减少。第三，少奇同志指示县委要发展高中，以作为发展大学的后备；并且建议省委解书记帮助徐水大学解决三两个教员。少奇同志在知道徐水大学和县科学研究所共有一部分仪器设备以后，指示说：好呀！你们慢慢地就会办成正式大学，同大城市的差不多，或许比那还好呢！第四，由于徐水的公社已经在很大程度上实行了全民所有制，少奇同志又告诉大家，全民所有制还并不是共产主义性质的，希望大家努力，争取早日进入“共产主义时代”。少奇同志对徐水人民急迫渴望早日向共产主义过渡的热情和干劲，都给予了最大的鼓舞和赞扬。第五，少奇同志还对徐水全县人民的生产和生活作了许多美妙而宽广的安排。（康濯：《少奇同志在徐水》1958年9月18日《人民日报》）由于少奇同志做了许许多多的重要指示，到了9月13日，中共中央政治局委员国务院副总理兼财政部长李先念等人到徐水视察时，徐水县已经实现了“一县一社，县、社合一”。一县一社，即一县一个公社，全县统收统支，统一核算，共负盈亏，原来各社队的收入统一交县，支出统一由县核拨，供给标准，工资水平全县基本上一致。徐水人民公社已经消灭了生产资料私有制的某些残余，徐水全县没有一个小商贩，他们全部实行了供给制。（李先念《人民公社所见》1958年10月17日《人民日报》）青年一代不懂什么叫“共产风”，不知道什么叫“穷队和富队拉平”，“搞平均主义”，“刮共产风”等等，看了刘少奇在河北徐水县搞的“共产主义公社试点”的经验情况，看了李先念的简要介绍，就略知一二了。

B

1958年9月16日到18日，刘少奇到河南视察，9月24日人民日报以《少奇同志在河南视察时具体阐述过渡到共产主义的几个条件》为题目报道了这一重大新闻。这是当时办人民公社亟待解决的问题，因为刘副主席在9月3日的人民日报社论中，已经强调，有条件的可以立即过渡到全民所有制，条件还不成熟的最慢不能超过三、四年或五、六年。那么，要创造那些条件才能过渡到共产主义呢？人民日报将刘少奇在河南视察时的指示，提纲式的归纳为以下几条：

——每个人都应当参加体力劳动；

——对小孩子必须强调社会教育；

——要由低级到高级实行供给制；

——工厂办半工半读到大学；

——工厂也可以实行半供给半工资；

接着人民日报详细的报道了少奇同志具体阐述过渡到共产主义的条件：

第一，使社会上所有有劳动能力的人都进行劳动，特别是体力劳动。每个人都应当担负起力所能及的劳动，体力劳动是搞吃穿的，每个人都吃穿，有人不能负担，别人就要加重负担。少奇同志特别强调说，毛主席说过，马克思、恩格斯都说过。这是过渡到共产主义的一个必要条件。

第二，搞好食堂、幼儿园、缝纫厂，把妇女从家务劳动解放出来，参加生产。（按：在这之前，刘少奇把办食堂、幼儿园、托儿所、缝纫组放在第一条，说它是“共产主义萌芽，现在放在第二条，把它当作过渡到共产主义的条件之一了。——笔者注）

第三，要搞技术革命，我在河北看到两个小高炉炼铁厂，一个厂要五百人砸矿石，另一个厂一部矿石粉碎机解决了问题，搞技术革命就能节约大量劳动力。

第四，改进社会的劳动组织，也能节省很多劳动力。（按：这条很要紧，现在报纸上只登一句话作提纲，到19日，少奇同志视察江苏时就具体阐述了。－－笔者注）

第五，要提高技术水平和文化水平。

报道说，少奇同志十分称赞河南的人民公社实行供给制。当吴芝圃谈到许多公社都实行供给制时，少奇同志说：这要由低级到高级，一半供给，一半工资的做法是很好的。报道又说：少奇同志说，学校办工厂，工厂办学校，也是过渡到共产主义的一个条件。少奇同志指示，要采取新的办法办工厂、办教育。他说，你们建立新工厂，不要照搬老工厂那一套，目前，公社实行劳动工资加奖励，除了吃粮食等以外每月发几块钱，社员就高兴得不得了了。公社可以这样做，那么按这个办法，工厂为什么不可以呢？工人也是农民，农民也是工人，为什么不可以这样呢？新工厂也可以办学校，招一批初中生，就在这里上课，一个工厂就是一个高中。一天读几小时书，做几小时工，工厂即是学校，学校即是工厂。半工半读可以搞到高中，也可以搞到大学。要建立制度，每天六小时劳动，二小时上课，要比较稳妥，搞它八年到十年，一直到大学毕业，这样学生也多了，工人也多了，将来出来，即是大学生，也是技术工人。这也是过渡到共产主义的一个条件。《人民日报》报道还说，刘少奇在河南视察时，还“听取了新乡七里营人民公社、修武人民公社和遂平人民公社党委的汇报，并作了重要指示。”具体作了哪些指示报道没有具体讲。但从毛泽东1958年10月派吴冷西和田家英率领调查组到新乡七里营人民公社和修武人民公社的调查报告看，可以认证刘少奇指示的后果：实行一县一个公社，全县统一核算，统一收支，共负盈亏，贫队和富队一齐拉平；实行全民所有制，搞供给制，实行十六包；实行消灭家庭，搞男女老少分别编班，分开做事，分开居住等等。

C

1958年9月10日至11日，刘少奇到他的“共产主义试点公社”河北徐水县视察，当他听到有人说，给山药灌狗肉汤，亩产可以收120万斤时，即说道：“那么作真有效果吗？哈哈！你们可以养狗啊！狗很容易繁殖吗！”（1958年9月18日《人民日报》）

D

1958年9月19日到28日，刘少奇到江苏视察，在常熟县和平人民公社，他参观中稻丰产实验田，他问党委书记：亩产可以打多少？回答说：可以打1万斤。少奇同志说：“1万斤，还能再多吗？你们这里条件好，再搞一搞深翻，还能多打些。”（1958年9月30日《人民日报》）1958年9月19日到28日，刘少奇到江苏视察，又大谈“如何建设美好的共产主义生活及培养人民共产主义精神”问题“如何建设美好的共产主义生活呢”？

刘少奇指示“应该做好五件事”：第一，要使社会上所有的人都参加力所能及的劳动；第二，彻底把妇女从繁琐的家务劳动中解放出来；第三，大规模地进行技术改革，改革各种劳动工具，提高劳动效率；第四，改善社会的劳动组织，例如，规模较小的农业合作社转变成规模较大的人民公社实行“组织军事化、行动战斗化、生活集体化”，农村劳动组织大进一步的改进，这种改进，大大有利于农村劳动力的调配，大大有利于农村生产的发展。又例如，实行郑州提出的“男女换班，老少换班”，即使女人能做的事不再由男人去做，使老人能做的事不再由青年和壮年去做，以使男女老少能够各自担任自己力能胜任的工作。第五，发展多面手，一人多艺，提高劳动者的文化技术水平。做好这五件事，不仅可以解决劳动力紧张的困难，而且将会使整个社会的劳动制度，劳动组织发生根本的变化。

乙、毛泽东同志同期的言论和中央的决议

A

毛泽东说：中国是个大国，但是个大穷国。今年大跃进，但即使根据现在报的数字，全国农民年平均收入也只有70元上下。全国工人每月平均工资也只有60元左右，现在有些县委（按：指山东寿张县。刘少奇7月14日到那里视察，作了重要指示后，他们提出“苦战三年过渡到共产主义”的口号，详见吴冷西《忆毛主席》137页）不知天高地厚，说什么苦战三年就可以过渡到共产主义。这不是发昏说胡话？说是“穷过渡”，马、恩、列、斯哪里说过共产主义社会还是很穷的呢？他们都说过渡到共产主义社会必要条件是产品极为丰富，否则怎么能实行按需分配呢？有些同志（指刘少奇，下同）要“穷过渡”，这样的共产主义有什么优越性和吸引力呢？毛泽东又说：现在人民公社搞的供给制，不是按需分配，而是平均主义。中国农民很早就有平均主义思想，东汉末年张鲁搞的“太平道”也叫“五斗米道”，农民交五斗米入道，就可以天天吃饱饭。这恐怕是中国最早的农民空想社会主义。我们现在有些同志急于向共产主义过渡，这非常危险。北戴河会议规定了过渡到共产主义的五个条件，哪一条也不能少，缺一条也不能向共产主义过渡。谈到这里，毛主席很动感情地说：反正我不准备急急忙忙的过渡。我今年65岁，即使将来快要死的时候，也不急急忙忙过渡。毛泽东强调：“过渡要有物质条件，精神条件，还要有国际条件。不具备条件宣布过渡也没有用。要划清两条线：一条是集体所有制，和全民所有制的区别，一条是社会主义和共产主义的区别。不要轻易宣布向全民所有制过渡，更不要轻易宣布向共产主义过渡。”毛泽东还说：“我们的大跃进，和人民公社化，不仅把杜勒斯吓了一跳，也把赫鲁晓夫吓了一跳。不过看来赫鲁晓夫还比较谨慎，他现在只讲12年内准备向共产主义过渡的条件，并没有说到那时就要过渡。我们有些同志（指刘少奇）头脑发热，想抢在赫鲁晓夫前头过渡，这很不好。苏联同志建设社会主义已搞了41年，我们才搞了9年就想当先锋，还不是头脑发昏？人有老中青，水有溪河湖海，事物都有一定的量度，有相对的规定性，从量变到质变要有一个过程，不能随意想过渡就过渡。”（吴冷西：《忆毛主席》——我亲身经历的若干重大历史事件片段，新华出版社1995年版111－112页。以下应用简称《忆毛主席》）

B

毛泽东1958年10月对田家英、吴冷西说：毛泽东说，我们共产党人的最终目标是建立共产主义社会，这是没有问题的。现在的问题在于：什么是共产主义社会？现在并不是人人认识一致，甚至在高级干部中也各说各的，其中有不少胡说。因此公社化过程中的具体做法，真是八仙过海，各显神通。你们这次下去调查要带两本书，一本是中国人民大学编辑的《马恩列斯论共产主义社会》，一本是斯大林写的《苏联社会主义经济问题》，出发前要把这两本小册子通读一遍，至少把人民大学编的那一本看一遍，要你的助手也这么办。毛泽东郑重地说，他的意思不是要我们搞本本主义，按图索骡，对号入座，也不是要我们照本本宣传，而是想使我们对马恩列斯关于共产主义说过什么有个大致的了解，下去调查中面对眼花缭乱的实际情况，能够保持冷静的头脑。不能道听途说，人云亦云。要深入实际调查研究，实事求是，心中有数，头脑清醒，做冷静的促进派。毛主席还交代，下去调查时不要各级领导作陪，要找生产队长就找生产队长，不要公社书记，大队长参加；要找群众谈话时就不要干部参加；要找县委书记也只请他本人来谈，因为人多了谈话就有顾虑（同级干部如此，上级干部更加如此），找群众谈话时要有各个阶层的人物，尤其要注意中农的态度。还可以找下放干部谈话，他们可能顾虑较少。总之，要了解各种人的想法。助手中可以选一两个女同志，那样，同农村妇女谈话比较方便。他吩咐我们下去不要张扬。我带的一组用新华社记者的名义，田家英那一组用中央办公厅工作人员的名义。（吴冷西：《忆毛主席》）

C

毛泽东听取了田家英和吴冷西调查刘少奇去过的七里营等地回来后的实情报告后，发表评论说：〈一〉一县一社太大了。平均分配会损害富队富社的积极性，还是要搞“按劳分配”毛主席谈到一县一社时提出，一县一社太大了。县委管不了那么多具体事，而且全县各地生产水平很不平衡，平均分配损害富队富社的积极性。我们现在还是搞社会主义还是按劳分配。凡是有利于发展生产的就干，一切不利于发展生产的就不干。供给制只能搞公共食堂，而且要加强管理，粗细粮搭配，干稀搭配，农忙农闲不同，要学会勤俭过日子，不能放开肚皮大吃大喝，那样肯定维持不下去。其它只搞些公共福利事业，不要采取“包”的办法，量力而为。延安时期搞供给制，是属于战时共产主义的办法，是不得已而为之，不能作为分配方式的榜样，所以全国解放后，就改行工资制了。

〈二〉两种所有制的接近是一个很长的历史过程，千万不能把两者混同起来。谈到修武县的全民所有制，毛主席说，修武不同于鞍钢，产品不能调拨，只能进行商品交换，不能称谓全民所有制，只能叫集体所有制。千万不能把两者混同一起，修武县委书记提出的问题，表明他实际上是不赞成搞全民所有制的，县里的产品不能全部调给国家，不可能也不必要，他作为一县之长，不能不慎重考虑，尤其是国家对县，在平常年景也不能完全保证按照县里的需要调拨给生产资料和生活资料，遇到灾年更加不能保证，这也是明摆着的。他提出的问题使我们想到：如果生产力没有高度发展，像北戴河会议关于人民公社决议中指出的，产品极端丰富，工业和农业都高度现代化，那么，生产关系上从集体所有制过渡到全民所有制，分配方式从按劳分配过渡到按需分配，是根本不可能的。这两种所有制的接近，是一个很长的历史过程。

〈三〉把夫妻分开搞集体住宿，不是给国民党对我们的诬蔑帮了忙吗？当我们汇报到有些公社搞集体住宿时，毛主席很生气地说，那种搞法不是给国民党对我们的诬蔑帮了忙吗？凡是这样胡搞的地方，我都支持群众起来造反。这些干部头脑发昏了，怎么共产党不要家庭了呢？要禁止拆散家庭，还是一家人大、中、小结合的好。（按：所谓搞“集体住宿”即刘少奇的“男女换班”“老少换班”的做法，把男女老少分别编班集体住宿，“搞军事化生活”，“以便男女老少各自能够担任自己力能胜任的工作”，就是共产主义“家庭革命”的办法，这就是刘少奇鼓吹的主意——笔者注）

〈四〉几千万人上山，农业可能丰产不丰收，食堂又放开肚皮吃，怎么得了？谈到群众大炼钢铁的干劲很大，地里庄稼没人收时，毛主席说：1070万吨钢的指标，可能闹得天下大乱。从北戴河会议到年底只有四个月，几千万人上山，农业可能丰产不丰收，食堂又放开肚皮吃，怎么得了？这次郑州会议要叫大家冷静下来。（吴冷西：《忆毛主席》95——103页）吴冷西回忆说：1958年11月6日，毛泽东特意找我专门指示：“人民日报和新华社天天作报道，发表议论，尤其要注意头脑冷静，要当促进派”。还说，他对报纸宣传有一点意见，过几天空一点了再谈。（吴冷西：《忆毛主席》104页）

D

1958年11月22日，毛泽东就人民日报和新华社的宣传报导，找吴冷西长谈，吴冷西回忆道，毛主席说：“做新闻宣传工作的记者和编辑，看问题要全面，要看正面，又要看到侧面，要看到主要方面，又要看到次要方面，要看到成绩，又要看到缺点。这叫做辩证法，两点论。现在有一种不好的风气，就是不让讲缺点，不让讲坏话，不让讲怪话。任何事情都有两面性，好的事情不是一切都好，也有坏的一面；反之坏的事情不是一切都坏，也有好的一面，只不过主次不同罢了。听到人家说好，你就得问一问是否一点坏处也没有？听到人家说坏，你就得问一问是否一点好处也没有？大跃进是好事，但浮夸风就不好。”毛主席强调，做新闻工作无论记者或编辑都要头脑冷静，要实事求是。下去采访，不要人家说什么你就报道什么。要自己动脑筋想想是否真实，是否有理。毛主席说到，据一些省委反映，人民日报在大跃进中搞各省进度表（如水利工程完成土石方进度表），放“卫星”（粮食和钢铁的高产“卫星”）等报道方法，对各地压力很大。结果“你追我赶”，大搞浮夸，这要引以为戒。毛主席讲了上面这些话后，又归纳为三个意见。他说：

第一，要实事求是，报道时要弄清事实真相，不是新闻必须真实吗？一定要查清虚与实，是虚夸、作假，还是真实、确实。新闻报道不是做诗写小说，不能凭想象虚构，不能搞浪漫主义。

第二，现在要下明矾，把混乱的思想加以澄清。听说人民日报有一篇社论讲人民公社从集体所有制过渡到全民所有制时把时间缩短了，说三、四年，四、五年就行了，不要北戴河决议上写的“或者更长一些时间”那半句话了。那半句话是我加上的。当时的想法是谨慎一点好。现在看来还是太急了。你们删去那半句话就更急了，不知是听了那一位政治局委员的意见。（按：毛泽东的意见非但不听，就连写上中央《决议》的话也敢删掉，可见这位政治局委员非同一般，实权在毛之上——笔者注）

第三，要考虑国际影响，今年我们宣传上吹得太厉害，不但在国内搞得大家头脑发昏，而且国际影响也不利。毛主席说：“我在成都会议上就曾说过，不要务虚名而得实祸，现在就有这个危险。杜勒斯天天骂我们，说明他恐慌，害怕我们很快强大起来。美国人会想到是不是对中国发动预防性战争。这对我们不利。何必那样引人枪打出头鸟呢？何况我们的成就中还有虚夸成分呢！即使真的有那么多的成绩，也不要大吹大擂，还是谦虚一点好………。”毛主席说：“新华社和人民日报，记者和编辑头脑都要清醒，多开动自己的脑筋，独立思考，不要人云亦云，随声附和。要调查，追根到底。要比较，同周围比较，同前后左右比较，同古今中外比较。唐朝有位太守，他审理案件，先不问原告和被告，而要先了解原告和被告周围的人和环境，调查好了才去审问原告和被告，这叫做勾推法，也就是比较法。记者和编辑要学会这种调查研究的工作方法，其实这也是思想方法，是实事求是的方法。记者，特别是记者头子——这时毛主席指我说，——像你这样的人，头脑要清醒，要实事求是。”（吴冷西：《忆毛主席》108－113页）

E

毛泽东召开一系列重要会议采取一系列措施力纠“五风”

第一节

郑州会议1958年8月下旬，中央政治局北戴河会议以后，从9月开始，毛泽东相继视察了河北、河南等省的一些农村，发觉在人民公社运动中，由于受刘少奇的《高举人民公社的红旗前进》的社论和他在河北、河南等地鼓吹“穷过渡”等讲话的影响，出现了一大堆混乱思想。有许多人急于宣布向共产主义过渡，急于实行全民所有制，主张消灭商品经济等等。针对这种情况，他于11月2日至10日在郑州主持召开了中央和地方部分领导人参加的会议，即第一次郑州会议。着重研究解决人民公社化运动中发生的种种问题。会议期间，毛泽东多次讲话，带头提出了一些纠正“五风”的意见：

一、强调划清社会主义与共产主义；集体所有制与全民所有制的界限，肯定现阶段我国是社会主义社会；肯定人民公社基本上是集体所有制。针对当时普遍存在混淆两个社会发展阶段，混淆两种所有制的思想情况，毛泽东为会议安排的第一个议题，就是对社会主义与共产主义要不要划一条线，什么叫建成社会主义。他在讲话中指出，现在我们还是社会主义。大线是社会主义与共产主义，小线是集体所有制和全民所有制，这两条线一定要划清，不能混淆。他也肯定人民公社的性质，目前基本上是社会主义的集体所有制。毛泽东反复强调要划清两个社会阶段和两种所有制的原则界限。对于澄清混乱思想，遏制严重泛滥的“共产风”是有积极作用的。（毛泽东以上讲话内容，见他4日和10日讲话稿）

二、指出取消商品经济是违背客观经济规律的。强调社会主义商品经济要大发展。毛泽东在会上多次批评刘少奇和陈伯达等人主张取消商品经济的错误观点。他说：现在我们有些人大有消灭商品生产之势，有不少人向往共产主义，一提商品生产就发愁，觉得这是资本主义的东西，没有区别社会主义与资本主义商品的差别，没有懂得利用其作用的重要性。这是不承认客观法则的表现。毛泽东在讲话中强调：现在还是要利用商品生产，商品交换，价值法则来作为一种有用的工具。我们国家是个商品生产不发达的国家，现在又很快的进入了社会主义，社会的商品生产，商品交换还要发展，这是肯定的，有积极作用的。10日，毛泽东在会上讲述斯大林的《苏联社会主义经济问题》一书时说：有些同志读马列主义书时是马克思主义，一碰到实际问题就要打折扣，避开使用还有积极意义的资本主义范畴——商品生产、商品流通、价值法则等来为社会主义服务。第三十六条（指会议起草的《十五年社会主义建设纲要四十条》1958－1972的36条——引者注）的写法就是证明，尽量用不明显的词句来蒙混过关。他说：有一些可怜的马克思主义者，要剥夺农村的中小生产者，我国也有这种人。有些同志急于要宣布全民所有，废除商品，实行调拨，那就是剥夺。商品生产不能与资本主义混为一谈，要看它同什么经济联系，商品与资本主义联系就出资本主义；和社会主义联系，就不是资本主义，就出社会主义。（毛泽东11月9、10日在郑州会议上讲话文稿）

三、实事求是，不许说谎虚报；坚持走群众路线，不许强迫命令。毛泽东提出，要把改进干部工作作风，注意工作方法当成重点。他强调：提倡实事求是，不要说谎，人民是骗不了的。他修改会议决议草案时，专门加了一节《工作方法》：在人民公社中，由于群众生活的集体化程度更多了，干部工作作风的好坏，对群众生活影响更大了，必须特别注意坚持走群众路线的工作方法，不允许用简单化的行政命令手段处理有关群众切身利益的问题。对工作中的成绩和缺点要采取老实态度，反对虚报成绩，隐瞒缺点。第一次郑州会议起草了《关于人民公社若干问题的决议》（草案）。

四、建议读两本书，用马克思列宁主义理论澄清混乱思想，统一思想认识。会议期间，毛泽东给中央、省、市、自治区、地、县四级党委委员写了一封信，建议读两本书，一本是斯大林的《苏联社会主义经济问题》，另一本是《马克思、恩格斯、列宁、斯大林论共产主义社会》。他在信中写道：要联系中国社会主义经济革命和经济建设去读这两本书，使自己获得一个清醒的头脑，以利指导我们伟大的经济工作。现在有很多人，有一大堆混乱思想，读这两本书就有可能给予澄清。（毛泽东：《关于读书的建议》1958年11月9日）毛泽东在这次会议中，反复倡导读马列的书，力求用马列主义的基本原理，武装党员干部的头脑，以统一思想和行动，这是一种高屋建瓴的领导艺术。第一次郑州会议起草了两个文件，一是《十五年社会主义建设纲要四十条》（1958－1972年），二是《郑州会议纪要》，后改为《郑州会议关于人民公社若干问题的决议》，根据毛泽东的意见，这两个文件都没有下达，而后提交武昌会议和八届六中全会修改、审议。11月12日，毛泽东致信邓小平说：“郑州会议就是一个为武昌会议准备文件的会议。”由于当时中央领导层许多人对于当时的经济发展形势仍存在不切实际的估计，继续坚持工农业生产的一些高指标，对大跃进和人民公社化运动中存在的问题严重性还缺乏足够的认识，尽管毛泽东在会上提出了一些很好的思想主张，但第一次郑州会议仅仅为纠“五风”错误开了一次头。第一次郑州会议结束后，11月13日，毛泽东致信刘少奇、邓小平，要求中央政治局、书记处同志，再加若干同志，在几天内开三至四次会：①

讨论第一次郑州会议起草的两个文件。当作问题提出，征求意见。②

讨论斯大林的《苏联社会主义经济问题》中“意见书”部分的第一、二、三章，各省也要照办。毛泽东说：这样做，是为了对武昌会议先做准备。所谓当作问题提出，即对每一个问题，都提出正反两面。例如，对一条线划清界限问题，提出划线好，还是不划线好？对商品问题，提出现阶段要商品好，还是不要商品好？其它问题以此类推。尽管毛泽东辛辛苦苦力纠“五风”，对刘少奇和邓小平等人进行耐心的沟通，然而他们在意么？没有。郑州会议结束后不久，他们照样利用人民日报鼓吹浮夸风。

11月21日，人民日报以显著标题报道：广东又一个实现粮食平均亩产1000斤以上的省份。平均亩产粮食1600斤，30多万亩晚稻特大丰收，比去年亩产增加2.2倍。“共产风”、“高指标风”，他们照旧鼓吹，有增无减。

第二节

武昌会议为继续纠正“五风”，1958年11月21日至27日，毛泽东在武昌主持召开中央政治局扩大会议，讨论人民公社问题和1959年国民经济计划安排问题。毛泽东在会上多次讲话，关于纠正“五风”的意见，有以下要点：

一、批评抢先过渡到共产主义的空想，再次肯定我国现阶段的任务是建设社会主义。毛泽东说：现在有的人吹得太大了（按：指刘少奇），我看不合事实，没有反映客观实际。社会主义建设我们没有经验，苏联建设社会主义已搞了41年，我们才搞了9年。现在一吹，吹得那么厉害，想当先锋，这不是头脑发昏？人有老中青，水有溪河湖海，事情都有一定的度量，有相对的规律性，从量变到质变要有一个过程，不能随意说过渡就过渡。从社会主义过渡到共产主义，不但要具备有物质条件和精神条件，而且还要有国际条件，这是不以人们意志为转移的。

二、指出人民公社有两种可能性，要么亡，要么不亡。毛泽东在21日的讲话中指出：人民公社还是要议一下，总得有那么个决议，或者搞个指示。杜勒斯、蒋介石他们都说，我们不搞人民公社还不会亡，一搞这个东西，就一定会亡。你不要说他没有道理，总有两个可能性，要么亡，要么不亡。他说这一句，在我脑子里头，一直在考虑这个问题。人民公社究竟怎么办才好？经过这次讨论，如果是多数人，比如十个人里头有六、七个人，都说那个办法比较好，那个办法就比较可靠了。显然，毛泽东是要集思广益要大家出主意想办法，认真研究如何办好人民公社。

三、强调要“压缩空气”，把根据不足的高指标压下来。11月21日，毛泽东就压缩工、农业生产的高指标问题说：“我们再一次唱个低调，把脑筋压缩一下，把空气变成低调空气。先搞少一点，如果行，有余力，情况顺利，再加一点。这有点泼冷水的味道，右倾机会主义了。”他说：“不要务虚名，而得实祸。现在要减轻点任务，水利建设，去冬今春全国搞五百亿土石方，而今冬明春要搞一千九百亿土石方，多了三倍。还有各种各样的任务，钢、铁、铜、铝、煤炭、运输、加工工业、化学工业，需要多少人力财力，这样一来，我看起来，中国非死一半人不可，不死一半，也要死三分之一，或者十分之一，死五千万人。死五千万人，你的职不撤，至少我的职要撤，头也成问题。要不要搞那么多，你多了也可以，以不死人为原则。你们一定要搞，我也没有办法，但死了人不能杀我的头。明年3000万吨钢（按北戴河会议决定1959年钢产量为2700－3000万吨——笔者注），究竟要不要定这么多？搞不搞得出？要多少人上阵，会不会死人？这次会议要唱个低调，把空气压缩一下。胡琴的弦不能拉得太紧，有断弦的危险。”11月23日，毛泽东在会上第二次讲话强调说：“我们的脑筋正在这里压缩空气。物质不灭，空气还是那么多。但是，压缩成液态或者固态，使它凝一点。关于生产指标问题，他说：以钢为纲，带动一切，究竟什么指标为好？北戴河会议后两个半月的经验，对我是一个很好的经验，就想到恐怕明年2700到3000万吨难于办到，我们是不是可以用另一种办法，把指标减低？”他还说：“你说服我是可以的，你打我通是可以的，但是，你得打我才能通，你得说我才能服。你们现在说的那些根据我还不能服，我不仅要做机会主义，我已经是机会主义，我就是站在机会主义的立场上，为此而奋斗，不牵累别人，将来算起账来的时候，不打你们，打我。因为我在这里反冒进，以前别人反我的冒进，现在我反人家的冒进。”（按：毛泽东这里讲的“你”、“人家”、“别人”指的是刘少奇）由于当时许多领导干部头脑发热，武昌会议压缩工、农业生产主要指标仍然偏高。但毛泽东在会议上讲的这些话，确实反映了他当时要求压缩不切实际的高指标的心情。

四、批评弄虚作假的浮夸风，要求经济事业越搞越合乎实际。毛泽东在会上专门讲了反对作假的问题，他强调提出：我看我们的经济事业是要越搞越细密，越搞越合乎实际。他要求人们讲老实话，说现在有一种空气，只许讲成绩多，脸上有光，得到奖励。要讲实话，比如讲牛的尾巴生在屁股后面，这是老实话，动物的尾巴总是要生在后面的。（毛泽东1958年11月23日在武昌会议上的讲话）

五、强调破除迷信不要把科学破除了。毛泽东在23日的讲话中提出：破除迷信，现在有些人把科学破除了。比如，第一条科学人是要吃饭的。这不但是科学，这是自然规律，客观法则，存在于人的思想意识之外的，没有一处地方证明人可以不吃饭。他强调指出，凡迷信一定要破除，凡真理，凡科学一定要保护。六、指出有一部分“资产阶级法权”的残余，现在还有用，不能破除，我们要保护它，使它为社会主义服务。毛泽东说：资产阶级法权，目前只能破除一部分。三风五气、老爷架子、工资过高过大的悬殊、猫鼠关系，这些东西要破除，彻底破除，反得越干净越有利，另一部分，工资等级、上下级关系、国家还带有一点强制性，则不能马上破除。社会主义时期，有一部分资产阶级法权，现在有用，因为它有用我们要保护它，使它为社会主义服务。（毛泽东：在武昌会议上的讲话1958年11月23日）。

第三节

中共八届六中全会1958年11月28日至12月1日，中共八届六中全会，在武昌举行。根据毛泽东的意见，全会审议通过《关于人民公社若干问题的决议》，一方面，对人民公社给予充分肯定；另一方面，从理论上和政策上阐述了一系列重大问题。比较集中地体现了前一时期党中央和毛泽东纠正“五风”错误的认识成果。

一、批评企图超越社会主义阶段的空想，重申社会主义和共产主义，集体所有制和全民所有制的区别。强调大力发展生产力。《决议》指出：无论由社会主义的集体所有制向社会主义的全民所有制过渡，还是由社会主义向共产主义的过渡，都必须以一定程度的生产力发展为基础。我们既然热心于共产主义事业，就必须首先热心于发展我们的生产力。首先用大力实现我们的社会主义工业化计划，而不应当无根据地宣布农村人民公社立即实行全民所有制，甚至立即进入共产主义等等。接着《决议》还分析了那样做的危害性。《决议》中的这些精彩文字都是毛泽东修改时加进去的，是专门对刘少奇和邓小平等人在《高举人民公社的红旗前进》的社论以及刘少奇在山东、河北、河南、江苏等地视察中所鼓吹的错误做法而进行的批评。为使读者研究，现将毛泽东在《决议》中加进去的文字转录如下：“必须指出，集体所有制对于今天的农村人民公社的生产发展，仍然有它积极的作用。集体所有制向全民所有制过渡的迟早，取决于生产发展的水平和人民的觉悟水平，这是客观存在的形势，而不能听凭人们的主观愿望，想迟就迟，想早就早。因此这个过渡只有经过一个相当长的时间，才能在全国范围内分期分批地实现。如果看不到这些，把成立公社和实现全民所有制混为一谈，过于性急，企图在农村中过早地否定集体所有制，急忙地改变为全民所有制，那也是不适当的，因而是不可能成功的……”。每个马克思主义者，必须清醒地认识到，由社会主义过渡到共产主义是一个相当长和相当复杂的发展过程，而在这整个过程中，社会的性质仍然是社会主义的。社会主义社会和共产主义社会是经济上发展程度不同的两个阶段。社会主义的原则是“各尽所能，按劳分配”。共产主义的原则是“各尽所能，按需分配”。共产主义的分配制度更合理，但是，这只有产品极大丰富了以后才可能实现。没有这个条件而否定按劳分配的原则，就会妨害人们劳动的积极性，就不利于生产的发展，不利于社会产品的增加，也就不利于促进共产主义的实现。因此，在人民公社社员收入中，按劳分配的工资部分，在长时期内，必须占有重要地位，为了促进社员劳动的积极性，也为了使社员在生活中的复杂的需要比较容易满足，公社必须努力使社员所得工资逐步增加，并且在若干年内，必须比供给部分增加更快。即使已经由集体所有制过渡到全民所有制以后，由于社会产品还没有丰富到足以实现共产主义，人民公社在一个必要的历史时期内，仍然将保留按劳分配的制度。企图过早的否定按劳分配的原则而代之以按需分配的原则，也就是说，企图在条件不成熟的时候勉强进入共产主义，无疑是一个不可能成功的空想。无论由社会主义集体所有制向社会主义的全民所有制过渡，还是由社会主义向共产主义过渡，都必须以一定生产力的发展为基础。生产关系一定要适合生产力性质，只有生产力发展到某种状况才会引起生产关系的某种改变，这是马克思主义的一条基本原理。同志们要记着，我国现在的生产力发展水平还是很低，苦战三年，加上再努力若干年，全国的经济面貌可以有一个很大的改变，但是那时离开全国高度工业化，全国农业机械化，电气化的目标，还将有一段不少的距离：就是离开社会产品大大丰富、劳动时间大大缩短、劳动强度大大减轻，还有一段很长的距离。而没有这些，当然就谈不到人类社会的更高发展阶段——共产主义。因此，我们既然热心于共产主义事业，就必须首先热心于发展我们的生产力。首先用大力实现我们的工业化计划，而不应当无根据地宣布农村人民公社“立即实行全民所有制”，甚至“立即进入共产主义”等等。那样做，不仅是一种轻率的表现，而且将大大降低共产主义在人们心目中的标准。使共产主义伟大的理想受到歪曲和庸俗化，助长了资产阶级的平均主义倾向，不利于社会主义建设的发展。（《关于人民公社若干问题的决议》1958年12月10日中共八届六中全会通过。1958年12月人民日报有关刘少奇的“穷过渡”、“跑步进入共产主义”的论调，请参阅本论著前面的有关文章）

二、批评企图否定商品生产和按劳分配的错误观点，强调继续发展商品生产和继续保持按劳分配的必要和重要性。《决议》提出：继续发展商品生产和继续保持按劳分配的原则，对发展社会主义经济是两个重大原则问题，必须统一认识。有些人在企图过早的“进入共产主义”的同时，企图过早的取消商品生产和商品交换，过早的否定商品、价值、货币、价格的积极作用。这种想法是对于发展社会主义建设不利的，因而是不正确的。这是我们以决议的形式，对商品生产和按劳分配这两个发展社会主义经济的重大原则的明确肯定。

三、批评浮夸风。要求发扬党的实事求是的作风，把经济工作越做越细。《决议》指出：目前社会主义建设中值得注意的一种倾向是浮夸。这是同我们党的实事求是的作风不相容的，是对我们的社会主义建设事业的发展不利的。我们的经济工作必须越做越细致，我们的各级领导工作人员必须善于区别事物的真相和假象。区别有根据的要求和没有把握的要求，对情况的判断必须力求接近客观实际。尽管毛泽东一再强调“压缩空气”，降低生产指标，但会议通过的《关于一九五九年国民经济计划的决议》规定的粮、棉、钢、煤等四大指标仍然偏高。如钢的产量由2700——3000万吨降为1800万吨左右，仍没有足够的能量抵抗刘的热情并降到应该的合乎实际的数字。全会期间，毛泽东于12月1日，撰写了《关于帝国主义和一切反动派是不是真老虎的问题》一文。在写到事物的两种可能性时指出：虚假的可能性同现实的可能性又是两件东西，又是统一性的两个对立面。冲天干劲是热，科学分析是冷。在我国，在目前，有些人太热了一点，他们不想使自己的头脑有一段冷的时间，不愿做分析，只要热，是不利于做领导工作的……。12月9日，毛泽东在六中全会上讲了12个问题对继续纠正“五风”提出了以下意见：——对“苦战三年，基本上改变农村面貌”的口号有怀疑。毛泽东指出：“本来是苦战三年改变农村面貌，但是后头不知道那一天就推广到全国去了。我的意见就是说，我对这个口号有怀疑，苦战三年基本上改变农村面貌，我曾经是有怀疑的，在4月武昌10个省委书记开会的时候，我提出过这个问题。我说，可以不可以改为苦战三年，初步改变农村面貌。把这个基本改变全国面貌的口号时间拖长一点，无疑是当机会主义，这样的机会主义我很愿当，当了有味道。”——指出围绕人民公社问题，有一大堆思想搞不清楚。这个决议的主要锋芒是向着急这方面的。毛泽东在讲到党内外争论时说：“最近围绕人民公社这个问题，有各种议论。我看，大概可能有几十万干部对这个问题，有一大堆思想搞不清楚。一人一说，十人十说，大体上有几说，一说就是性急了一点，纷纷宣布自己是全民所有制，纷纷宣布两年或三年或四年进入共产主义。缺点是太急了一点。我们这一回作这个《决议》主要锋芒是向着急这方面的，就是说，不要太急，太急了没有好处。”——要求做到计划要留有余地，让群众的实践超过计划。毛泽东认为，马克思主义对立统一学说，在我们国家1958年有一个很大的发展。他说：“现在要搞一个空气压缩机，把空气压缩一下，我们脑子里的空气还是那么多，但是，压缩一下，要留有余地，提出的计划要低一点，让群众的实践超过我们的计划。我看这也是一个辩证法的问题。”——强调要估计人民公社和人民政权存在着巩固和垮台的两种可能性。毛泽东指出：“巩固和垮台这两种可能性都存在。他说，我倒是借这个机会讲一下这些倒霉的事情，无非是人民公社垮台，共产党垮台、崩溃、分裂，剩下一些游击队。他强调：不过，我们有一条马克思主义基本规律管着，就是说，我们这些倒霉，尽管怎么样，总是暂时的，就整个说，是局部的。帝国主义、世界上的资产阶级，一定要灭亡，是永久的，以后就没有了。而社会主义事业，有损失，有失败，因为我们搞的不好。那种挫折、那种分裂、那种失败，甚至灭亡，都是暂时的，不久就要恢复。”毛泽东的这番话是就人民公社问题说起的一方面，他希望人民公社巩固，力求它巩固；另一方面他又担心人民公社垮掉，或者要作垮掉的思想准备。他进而引发出对共产党和社会主义发展的两种可能性的论述，反映了彻底的辩证唯物主义者的深邃认识和郑重态度。毛泽东这番话是在三十多年前说的，然而，对于我们今天正确看待国际共产主义运动中的挫折、失败，仍然具有震耳发聩的指导作用。

第四节

第二次郑州会议党的八届六中全会以后，1959年2月下旬，毛泽东赴河北、山东、河南三省调查研究，发现八届六中全会《决议》做出的关于纠正“共产风”的决定精神并未贯彻，“一平、二调、三收款”的现象仍然相当严重。于是，毛泽东于2月27日至3月5日，在郑州召开中央政治局扩大会议，即第二次郑州会议，专门研究纠正“共产风”的问题。在会议中，毛泽东对“共产风”进行了更严厉的批评。他说：“从去年9月人民公社成立后，刮起了一股共产风，主要有三条：一是穷富拉平，二是积累太多，三是猪、鸡、鸭、（有的部分，有的全部）无偿归公社，还有部分桌椅、板凳、刀锅、碗筷等无偿归公社食堂，还有大部分自留地归公社……。这样一来，共产风刮遍全国。他批评说：无偿占有别人劳动成果，这是不允许的。我们对民族资产阶级的生产资料都还采用赎买政策，怎么可以无偿剥夺农民的劳动成果呢？这样做，实际是抢产，没给钱，不是抢是什么？这样下去，一定垮台！”他又说：“我代表一千万队长干部，五亿农民说话，坚持右倾机会主义（按：当时如果谁反对刘少奇推行的‘共产风’就被他们批判为右倾，所以毛泽东这样说——笔者注），贯彻到底，你们不跟我贯彻，我一个人贯彻，直到开除党籍，要到马克思那里告状！”为了引起大家重视，在3月5日的发言中，毛泽东严厉的批评说：“共产主义没有饭吃，天天搞共产，实际上是抢产，向富队共产。旧社会谓之贼，红帮谓之抢，青帮叫偷，抢和偷的科学名词叫无偿占有别人劳动成果。他把‘共产风’上纲为‘左’的修正主义，冒险主义。他批评说：误认社会主义为共产主义，误认集体所有制为全民所有制，误认按劳分配为按需分配，想快反而慢。武昌会议时，价值法则、等价交换已弄清，但根本不执行，等于放屁。”毛泽东讲的这些话，显然是对刘少奇和邓小平等人拒不执行武昌会议精神和八届六中全会精神的批评。毛泽东在会上多次讲话，他强调要整顿公社内部的所有制，进一步解决“共产风”问题。

一、指出人民公社的集体所有制，需要一个发展过程，目前必须以生产队所有制为基础。毛泽东说：现在，许多人还不认识公社所有制有一个发展过程，在公社内部，由队的小集体所有制到社的大集体所有制，需要一个过程。他强调，目前人民公社以生产队所有制为基础，有极大的重要性。这就有力的批评和纠正刘少奇所鼓吹和推行的，一律实行公社所有制和全民所有制的错误做法。

二、坚持按劳分配原则，纠正平均主义和过分集中两种错误倾向。毛泽东在分析一平、二调、三收款的现象后，指出：“上述两种倾向，都包含有否认价值法则，否认等价交换的思想在内，过头热是不对的。”为纠正这两种倾向，他提出了整顿和建设人民公社的方针：“统一领导，队为基础；分级管理，权力下放；三级指标，各计盈亏；分配计划，由社决定；适当积累，合理调剂；物资劳动，等价交换；按劳分配，承认差别。”（按：刘少奇搞的则是：全社统收统支，统一核算，共负盈亏，各大队、各小队的收入统一交公社，支出由公社统一核发，供给标准、工资水平公社基本一致——笔者注）

三、指出“共产风”的实质就是无偿占有别人劳动成果。毛泽东指出：“公社化后刮起了‘共产风’，即是说，在某种范围内，实际上造成了一部分人无偿占有别人劳动成果的情况，是我们所不许可的。他严厉的批评这种行为是强盗行为，是旧社会上海青帮、红帮流氓集团的偷、抢行为。在共产党内绝对不允许这样做。我们对民族资产阶级还采用赎买政策，我们怎么可以无偿占有人民的劳动成果呢？他在一个文件批语中指出：这是‘左’倾冒险主义思想行为。”（毛泽东1959年2月28日对山西省委《关于整顿和巩固人民公社的决议》的批语）

Ｆ

为反“五风”，毛泽东向省、地、县、社、队致公开信（《党内通信》1959年4月29日）省级、地级、县级、社级、队级、小队级的同志们：我想和同志们商量几个问题，都是关于农业的。

第一个问题，包产问题。南方正在插秧，北方也在春耕。包产一定要落实。根本不要管上级规定的那一套指标。不管这些，只管现实可能性。例如，去年亩产只有三百斤的，今年能增产一百斤、二百斤，也就很好了。吹上八百斤、一千斤、一千二百斤，甚至更多，吹牛而已，实际办不到，有何益处呢？又例如，去年亩产五百斤的，今年增加二百斤、三百斤，也就算成绩很大了，再增上去，就一般说，是不可能的。

第二个问题，密植问题。不可太稀，不可太密，许多年轻干部和某些上级机关缺少经验，一个劲儿要密植，有些人竟说愈密愈好。不对，老年人怀疑，中年人也有怀疑的。这三种人开一个会，得出一个适当的密度，那就好了。既然要包产，密植问题就得由生产队、生产小队商量决定。上面死硬的密植命令，不但无用，而且害人不浅。因此，根本不要下这种死硬的命令，省委可以规定一个密植幅度，不当作命令下达，只供下面参考。此外，上面要精心研究，到底密植程度以何为好，积累经验，根据因气候不同，因地点不同，因土、肥、水、种等条件不同，因各种作物的情况不同，因田间管理水平高低不同，做出一个比较科学的密植程度的规定，几年之内达到一个实际可行的标准那就好了。

第三个问题，节约粮食问题。要十分抓紧，按人定量。忙时多吃，闲时少吃，闲时半干半稀，杂以番薯、青菜、瓜豆、芋头之类，此事一定要十分抓紧。每年一定把收割、保管、吃用三件事（收、管、吃）抓得很紧很紧，而且要抓得及时，机不可失，时不再来。一定要有储备粮，年年储一点，逐年增多，经过十年八年奋斗，粮食问题可能解决。在十年内，一切大话、高调切不可讲，讲就是十分危险的。须知我国是一个有六亿五千万人口的大国，吃饭是一件大事。

第四个问题，播种面积要多少的问题。少种高产多收的计划，是一个远景计划，是可能的。但在十年内不能全部实行，也不能大部实行。十年内，只能看情况逐步实行。三年以内，大部不可行。三年以内，要力争多种，目前几年的方针是：广种薄收与少种多收的高额丰产田同时进行。

第五个问题，机械化问题。农业的根本出路在于机械化。要有十年时间，四年以内小解决，七年以内中解决，十年以内大解决。今年、明年、后年，这三年内，主要依靠改良农具，半机械化农具，每省每地每县都要设一个农具研究所，集中一批科学技术人员和农村有经验的铁匠木匠，收集全省、全地、全县各种比较进步的农具，加以比较，加以实验，加以改进，试制新式农具。试制成功，在田里实验，确实有效，然后才能成批制造，加以推广。提机械化，用机械制造化学肥料这件事，必须包括在内，逐年增加化学肥料是一件十分重要的事。

第六个问题，讲真话问题。包产能包多少，就讲能包多少。不讲经过努力实在做不到而又勉强讲做得到的假话。各项增产措施，实行八字宪法，每项都不可讲假话。老实人，敢讲真话的人，归根到底，于人民事业有利，于自己也不吃亏。爱讲假话的人，一害人民，二害自己，总是吃亏的。应当说，有许多假话是上面压出来的。上面，一吹，二压，三许愿，使下面很难办。因此，干劲一定要有，假话一定不可讲。

以上六件事，请同志们研究，可以提出不同意见，以求得真理为目的。我们办农业、工业的经验还很不足。一年一年积累经验，再过十年，客观必然性可能逐步被我们认识，在某种程度上，我们就有自由了。什么叫自由？自由就是必然的认识。同目前流行的一些高调比较起来，我在这里唱的是低调，目的在真正调动积极性，达到增产目的。如果事实不是我讲的那样低，而达到了较高的目的，我变为保守主义者，那就谢天地，不胜光荣之至。

三、遇到困难后（1960年以后）的言论比较

刘少奇说：三分天灾，七分人祸。

毛泽东同志同期的言论“我是中央主席，都有我的份。”（薄一波）“1958、1959年，主要责任在我身上。”“我是主席，不能驳，我看不对。”（薄一波）“凡是中央犯的错误，直接的归我负责，间接的我也有份，因为我是中央主席。”

四、在七千人大会上

国家主席，党的副主席，在大跃进期间的一线领导人刘少奇讲了：三分天灾，七分人祸。

1月30日毛泽东在会上就党的民主集中制问题作了重要讲话，并作了自我批评，对几年来工作中发生的缺点、错误承担了责任。

2月6日下午全体会议上，邓小平讲了党的工作问题，代表中央书记处，对几年来工作中的缺点错误作了自我批评，承担了责任。

周恩来讲了国內经济问题，从国务院工作的角度作了自我批评，对几年来的问题承担了责任。



*** 关于社会主义商品生产问题


毛泽东

(一九五八年十一月九日、十日)

 

一

许多人避而不谈商品和商业问题，好像不如此就不是共产主义似的。人民公社必须生产适宜于交换的社会主义商品，以便逐步提高每个人的工资。在生活资料方面，必须发展社会主义的商业；并且利用价值法则的形式，在过渡时期内作为经济核算的工具，以利逐步过渡到共产主义。现在我们的经济学家不喜欢经济学，苏联也是这样，认为谁说到价值法则谁就不名誉似的，表现在雅罗申柯写的一封信上。这些人不赞成商品生产，以为苏联已经是共产主义了，实际上还差得很远。我们搞社会主义只有几年，则差得更远。

列宁曾经大力提倡发展商业，因为苏联那时城乡商品流通有断流的危险。我们在一九五○年也曾有过这种危险。现在运输情况不好，出现半断流的状态。我看要向两方面发展:一是扩大调拨，一是扩大商品生产。不如此，就不能发工资，不能提高生活。

提倡实事求是，不要谎报，不要把别人的猪报成自己的，不要把三百斤麦子报成四百斤。今年的九千亿斤粮食，最多是七千四百亿斤，把七千四百亿斤当数，其余一千六百亿斤当作谎报，比较妥当。人民是骗不了的。过去的战报，谎报战绩只能欺骗人民，欺骗不了敌人，敌人看了好笑。有真必有假，真真假假搞不清。偃师县原想瞒产，以多报少，也有的以少报多。《人民日报》最好要冷静一点。要把解决工作方法问题，当成重点，党的领导，群众路线，实事求是。

斯大林的《苏联社会主义经济问题》一书，要再看一遍。省委常委、地委常委以上干部要研究一下，都要研究这本书的第一章、第二章、第三章。过去看，不感兴趣，现在不同了。这三章中有许多值得注意的东西，也有一些写得不妥当，再有一些他自己也没有搞清楚。

第二章、第三章，讲商品和价值法则，你们有什么看法?我相当赞成其中的许多观点，把这些问题讲清楚很有必要。斯大林认为在苏联生产资料不是商品。在我们国家就不同，生产资料又是商品又不是商品，有一部分生产资料是商品，我们把农业机械卖给合作社。

进入共产主义要有步骤。我们向两方面扩大:一方面发展自给性的生产，一方面发展商品生产。现在要利用商品生产、商品交换和价值法则，作为有用的工具，为社会主义服务。在这方面，斯大林讲了许多理由。商品生产有没有消极方面呢?有就限制它嘛!

我国是商品生产很不发达的国家，比印度、巴西还落后。印度的铁路、纺织比中国发达。去年我们生产粮食三千七百亿斤，其中三百亿斤作为公粮，五百亿斤作为商品卖给国家，两项合起来商品粮还不到粮食总产量的四分之一。粮食以外的经济作物也很不发达，例如茶、丝、麻、烟都没有恢复到历史上的最高产量。需要有一个发展商品生产的阶段，否则公社发不出工资。例如河北省分三种县，一种只够吃饭，一种需要救济，一种除吃饭外还能发点工资。发工资又分几种情况，有的只能发几角钱。因此，每个公社在生产粮食以外还要发展能卖钱的东西，发展社会主义的商品生产和商品交换。必须肯定社会主义的商品生产和商品交换还有积极作用。调拨的产品只是一部分，多数产品是通过买卖进行商品交换。

现在有一种偏向，好像共产主义越快越好。实现共产主义是要有步骤的。山东范县提出两年实现共产主义，要派人去调查一下。现在有些人总是想在三五年内搞成共产主义。

二

大跃进把有些人搞得糊里糊涂，到处都是诗。有人说“诗无达诂”，这是不对的。诗有达诂，达即是通达，诂即是确凿。

睡不着觉，想说一点。试图搬斯大林，继续对一些同志作说服工作。我自以为是正确的，如果对立面的同志正确，那我服从。

现在仍然是农民问题。有些同志忽然把农民看得很高，以为农民是第一，工人是第二了，农民甚至比工人阶级还高，是老大哥了。农村在有些方面走在前面，这是现象，不是本质。有人以为中国的无产阶级在农村，好像农民是无产者，工人是小资产阶级。这样看，是不是马克思主义的?有的同志读马克思主义教科书时是马克思主义者，一碰到实际问题就要打折扣。这一股风，有几十万甚至几百万人。至于群众，也有些昏昏沉沉。于是谨慎小心，避开使用还有积极意义的资本主义范畴——商品生产、商品流通、价值法则等来为社会主义服务。第三十六条[2]的写法就是证据，尽量用不明显的词句，来蒙混过关，以便显得农民进入共产主义了。这是对马克思主义不彻底、不严肃的态度。这是关系到几亿农民的事。斯大林说不能剥夺农民。我国人民公社，不但种子，还有肥料、产品，所有权在农民。国家不给它东西，不进行等价交换，它的产品也不会给你。是轻率地还是谨慎地对待这个问题好呢?修武县县委书记，不敢宣布公社是全民所有制。他第一条是怕有灾荒，农业减产了，发不了工资，而国家又不能包下来，不能给补贴；第二条是怕丰产了，国家把粮食调走。这个同志是想事情的，不冒失。我们没有宣布土地国有，而是宣布土地、种子、牲畜、大小农具社有。这一段时期内，只有经过商品生产、商品交换，才能引导农民发展生产，进入全民所有制。

现在，我们有些人大有要消灭商品生产之势。他们向往共产主义，一提商品生产就发愁，觉得这是资本主义的东西，没有分清社会主义商品生产和资本主义商品生产的区别，不懂得在社会主义条件下利用商品生产的作用的重要性。这是不承认客观法则的表现，是不认识五亿农民的问题。在社会主义时期，应当利用商品生产来团结几亿农民。我以为有了人民公社以后，商品生产、商品交换更要发展，要有计划地大大发展社会主义的商品生产，例如畜产品、大豆、黄麻、肠衣、果木、皮毛。现在有人倾向不要商业了，至少有几十万人不要商业了。这个观点是错误的，这是违背客观法则的。把陕西的核桃拿来吃了，一个钱不给，陕西的农民肯干吗?把七里营[3]的棉花无代价地调出来，会马上打破脑袋。这是不认识五亿农民，不懂得无产阶级对农民应该采取什么态度。恩格斯曾经说过，“一旦社会占有了生产资料，商品生产就将被消除，而产品对生产者的统治也将随之消除”。[4]产品在旧社会对人是有控制作用的。斯大林对恩格斯的这个公式所作的分析是对的，斯大林说:“恩格斯在他的公式中所指的，不是把一部分生产资料收归国有，而是把一切生产资料收归国有，即不仅把工业中的生产资料，而且也把农业中的生产资料都转归全民所有。”“恩格斯认为，在这样的国家中，在把一切生产资料公有化的同时，还应该消除商品生产。”[5]现在我们的全民所有是一小部分，只占有生产资料和社会产品的一小部分。只有把一切生产资料都占有了，才能废除商业。我们的经济学家似乎没有懂得这一点。

斯大林说，有一种“可怜的马克思主义者”认为，应当剥夺农村的中小生产者。[6]我国也有这种人。有些同志急于要宣布人民公社是全民所有，废除商业，实行产品调拨，这就是剥夺农民，只会使台湾高兴。我们在一九五四年犯过点错误，征购粮食太多了，全体农民反对我们，人人说粮食，户户谈统购，这也是“可怜的马克思主义者”因为不知道农民手里到底有多少粮。这还是征购，只是过头了一点，农民就反对。曾经有过这种经验，犯过这种错误，后来我们就减下来了，决定只征购八百三十亿斤。现在农民的劳动，同土地和其他生产资料(种子、工具、水利工程、林木、肥料等)一样是他们自己所有的，因此有产品所有权。不知道什么道理，我们的哲学家、经济学家显然把这些问题忘记了。忘记了这一点，我们就有脱离农民的危险。

商品生产不能与资本主义混为一谈。为什么怕商品生产?无非是怕资本主义。现在是国家同人民公社做生意，早已排除资本主义，怕商品生产做什么?不要怕，我看要大大发展商品生产。我国还有没有资本家剥削工人?没有了，为什么还怕呢?不能孤立地看商品生产，斯大林的话完全正确，他说:“决不能把商品生产看作是某种不依赖周围经济条件而独立自在的东西。”[7]商品生产，要看它是同什么经济制度相联系，同资本主义制度相联系就是资本主义的商品生产，同社会主义制度相联系就是社会主义的商品生产。商品生产从古就有，商朝的“商”字，就是表示当时已经有了商品生产的意思。把纣王、秦始皇、曹操[8]看作坏人是完全错误的。纣王是个很有本事能文能武的人。纣王伐徐州之夷，打了胜仗，只是损失太大，俘虏太多，消化不了，以致亡了国。说什么“血流漂杵”[9]，纣王残暴极了，这是《书经》中夸张的说法。所以孟子说:“尽信《书》，则不如无《书》。”[10]在奴隶时代商品生产并没有引导到资本主义。斯大林说，商品生产“替封建制度服务过，可是，虽然它为资本主义生产准备了若干条件，却没有引导到资本主义”。[11]斯大林的这一说法不很准确，应该说:封建社会这个母胎中已经孕育了资本主义的生产方式。

一九四九年七届二中全会[12]上，我的报告中就说到限制资本主义经济成分的问题，对资本主义经济成分不是漫无限制地任其泛滥。从一九五○年开始，我们让资本主义经济成分发展了六年之久，但同时已经实行加工订货、统购包销、公私合营，对资本主义经济成分进行社会主义改造。到一九五六年，他们实际上空手过来了，斯大林所说的“一些决定性的经济条件”[13]，我们已经完全有了。斯大林说:“试问，为什么商品生产就不能在一定时期内同样地为我国社会主义社会服务而并不引导到资本主义呢?”[14]这句话很重要。已经把鬼吃了，还怕鬼?不要怕，不会引导到资本主义，因为已经没有了资本主义的经济基础。商品生产可以乖乖地为社会主义服务，把五亿农民引导到全民所有制。商品生产是不是有利的工具?应当肯定说:是。为了五亿农民，应当充分利用这个工具发展社会主义生产。要把这个问题提到干部中进行讨论。

劳动、土地及其他生产资料统统是农民的，是人民公社集体所有的，因此产品也是公社所有。他们只愿意用他们生产的产品交换他们需要的商品，用商品交换以外的办法拿走公社的产品，他们都不接受。我们不要以为中国农民特别进步。修武县县委书记的想法是完全正确的。商品流通的必要性是共产主义者要考虑的。必须在产品充分发展之后，才可能使商品流通趋于消失。同志们，我们建国才九年就急着不要商品，这是不现实的。只有当国家有权支配一切产品的时候，才可能使商品经济成为不必要而消失。只要存在两种所有制，商品生产和商品交换就是极其必要、极其有用的。河南提出四年过渡到共产主义，马克思主义“太多”了，不要急于在四年搞成。不要以为四年之后河南的农民就会同郑州的工人一样，这是不可能的。我们搞革命战争用了二十二年，曾经耐心地等得民主革命的胜利。搞社会主义没有耐心怎么行?没有耐心是不行的。

根据中央档案馆保存的讲话记录稿刊印。

 

注释

[1]一九五八年十一月二日至十日，毛泽东召集部分中央领导人和部分地方负责人在郑州举行工作会议。他在会上多次讲话，批评了急于想使人民公社由集体所有制过渡到全民所有制、由社会主义过渡到共产主义，以及企图废除商品生产等错误主张。本篇节选了毛泽东讲话中关于社会主义商品生产问题的内容。其一选自十一月九日的讲话；其二选自十一月十日下午的讲话。

[2]指《十五年社会主义建设纲要四十条（1958－1972）》第一次修正稿修改时重新改写的第三十六条，内容是：“人民公社应当根据必要的社会分工发展生产，既要增加自给性的产品，又必须增加用以交换的产品。产品的交换，除了在公社相互之间可以继续采取合同制度以外，在国家和公社之间，应当逐步地从合同制度过渡到调拨制度。”这个纲要后来没有形成正式文件。

[3]指河南新乡七里营人民公社。

[4]见恩格斯《反杜林论》（《马克思恩格斯选集》第3卷，人民出版社1995年版，第633页）。

[5]见斯大林《苏联社会主义经济问题》（《斯大林选集》下卷，人民出版社1979年版，第546页）。

[6]见斯大林《苏联社会主义经济问题》。原文是：“也不能把另一种可怜的马克思主义者的意见当作答案，他们认为，也许应该夺取政权，并且剥夺农村的中小生产者，把他们的生产资料公有化。”（《斯大林选集》下卷，人民出版社1979年版，第547页）

[7]见斯大林《苏联社会主义经济问题》（《斯大林选集》下卷，人民出版社1979年版，第549页）。

[8]纣王，又称帝辛，商朝最后的国君。秦始皇，即嬴政（公元前259-前210），秦王朝的建立者。曹操（155-220），字孟德，沛国谯（今安徽亳县）人，三国时期政治家、军事家。

[9]见《书经•周书•武成》。

[10]见《孟子•尽心下》。

[11]见斯大林《苏联社会主义经济问题》（《斯大林选集》下卷，人民出版社1979年版，第549页）。

[12]七届二中全会，见本卷第98页注[8]。

[13]指生产资料公有制的建立、雇佣劳动制度的消灭和剥削制度的消灭。见斯大林《苏联社会主义经济问题》（《斯大林选集》下卷，人民出版社1979年版，第549页）。

[14]见斯大林《苏联社会主义经济问题》（《斯大林选集》下卷，人民出版社1979年版，第549页）。
