# -*- org -*-

# Time-stamp: <2011-09-15 19:48:40 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent


* 罗斯柴尔德家族:“大道无形”世界首富

只要我能控制一个国家的货币发行，我不在乎谁制订法律。[fn:hobizhanzheng1-01]

梅耶·罗斯柴尔德本章导读当国际媒体成天炒作身家500亿美元的比尔·盖茨蝉联世界首富宝座的时候，如果你信以为真，你就上当了。因为在人们耳熟能详的所谓富豪排行榜上，你根本找不到“大道无形”的超级富豪们的身影，因为他们早已严密地控制了西方主要的媒体。
所谓“大隐隐于朝”。如今，罗斯柴尔德家族仍在经营着银行业务，但是如果我们随机在北京或上海的街头问100个中国人，其中可能有99个知道美国花旗银行，而不见得有1个知道罗斯柴尔德银行。
究竟谁是罗斯柴尔德？如果一个从事金融行业的人，从来没有听说过“罗斯柴尔德”这个名字，就如同一个军人不知道拿破仑，研究物理学的人不知道爱因斯坦一样不可思议。奇怪却并不意外的是，这个名字对绝大多数中国人来说是非常陌生的，但它对中国人民乃至世界人民的过去、现在和未来的影响力是如此巨大，而其知名度是如此之低，其隐身能力让人叹为观止。
罗斯柴尔德家族究竟拥有多少财富？这是一个世界之迷。保守的估计是50万亿美元！[2]罗斯柴尔德家族到底是怎样赚到如此惊人的财富的？这就是本章要告诉你的故事。
严密的家族控制，完全不透明的黑箱操作，像钟表一般精确的协调，永远早于市场的信息获取，彻头彻尾的冷酷理智，永无止境的金权欲望，以及基于这一切的对金钱和财富的深刻洞察和天才的预见力，使得罗斯柴尔德家族在世界两百多年金融、政治和战争的残酷旋涡中所向披靡，建立了一个迄今为止人类历史上最为庞大的金融帝国。

** 拿破仑的滑铁卢与罗斯柴尔德的凯旋门

内森是老罗斯柴尔德的第三个儿子，也是五兄弟中最具胆识的一个。1798年，他被父亲从法兰克福派到英国开拓罗斯柴尔德家族的银行业务。内森是一个城府极深、行事果决的银行家，从没有人真正了解他的内心世界。凭着惊人的金融天赋和神鬼莫测的手段，到1815年，他已成为伦敦首屈一指的银行寡头。
内森的大哥阿姆斯洛在法兰克福打理罗斯柴尔德家族银行的大本营（M.A.Rothschild and Sons），他的二哥所罗门在奥地利的维也纳建立了家族的另一分支银行（S.M. Rothschild and Sons），他的四弟卡尔在意大利的那不勒斯建立了另一个银行，他的五弟詹姆斯在法国巴黎也有一个银行（Messieus de Rothschild Freres）。罗斯柴尔德家族创建的银行体系是世界上第一个国际银行集团。此时五兄弟正密切地注视着1815年的欧洲战况。
这是一场关系着欧洲大陆命运和前途的重要战争。如果拿破仑取得了最终胜利，法国将不容置疑地成为欧洲大陆的主人。如果威灵顿勋爵打垮了法军，那英国将主导欧洲的大国均势。
早在战前，罗斯柴尔德家族就非常具有远见地建立了自己的战略情报收集和快递系统。他们构建起数量庞大的秘密代理人网络，这些类似战略情报间谍的人被称为“孩子们”。这些人被派驻欧洲所有的首都、各大城市、重要的交易中心和商业中心，各种商业、政治和其他情报在伦敦、巴黎、法兰克福、维也纳和那不勒斯之间往来穿梭。这个情报系统的效率、速度和准确度都达到令人叹为观止的程度，远远超过了任何官方信息网络的速度，其他商业竞争对手更是难以望其项背。这一切使得罗斯柴尔德银行在几乎所有的国际竞争中处于明显的优势。[3]
“罗斯柴尔德银行的马车奔驰在（欧洲各地的）公路上，罗斯柴尔德银行的船穿梭于海峡之间，罗斯柴尔德银行的间谍们遍布（欧洲的）城市街道，他们揣着大量现金、债券、信件和消息，他们最新的独家消息在股票市场和商品市场中被迅速地传播着，但所有的消息都没有滑铁卢战役的结果更为宝贵。”[4]
1815年6月18日，在比利时布鲁塞尔近郊展开的滑铁卢战役，不仅是拿破仑和威灵顿两支大军之间的生死决斗，也是成千上万投资者的巨大赌博，赢家将获得空前的财富，输家将损失惨重。伦敦股票交易市场的空气紧张到了极点，所有的人都在焦急地等待着滑铁卢战役的最终结果。如果英国败了，英国公债（Consols）的价格将跌进深渊；如果英国胜了，英国公债将冲上云霄。
正当两支狭路相逢的大军进行着殊死战斗时，罗斯柴尔德的间谍们也在紧张地从两军内部收集着尽可能准确的各种战况进展的情报。更多的间谍们随时负责把最新战况转送到离战场最近的罗斯柴尔德情报中转站。到傍晚时分，拿破仑的败局已定，一个名叫罗斯伍兹的罗斯柴尔德快信传递员亲眼目睹了战况，他立刻骑快马奔向布鲁塞尔，然后转往奥斯坦德港。当罗斯伍兹跳上了一艘具有特别通行证的罗斯柴尔德快船时，已经是深夜时分。这时英吉利海峡风急浪高，在付了2 000法郎的费用之后，他终于找到了一个水手连夜帮他渡过了海峡[5]。当他于6月19日清晨到达英国福克斯顿的岸边时，内森·罗斯柴尔德亲自等候在那里。内森快速打开信封，浏览了战报标题，然后策马直奔伦敦的股票交易所。
当内森快步进入股票交易所时，正在等待战报的焦急而激动的人群立刻安静下来，所有人的目光都注视着内森那张毫无表情、高深莫测的脸。这时，内森放慢了脚步，走到自己的被称为“罗斯柴尔德支柱”的宝座上。此时他脸上的肌肉仿佛石雕一般没有丝毫情绪浮动。这时的交易大厅已经完全没有了往日的喧嚣，每一个人都把自己的富贵荣辱寄托在内森的眼神上。稍事片刻，内森冲着环伺在身边的罗斯柴尔德家族的交易员们递了一个深邃的眼色，大家立即一声不响地冲向交易台，开始抛售英国公债。大厅里立时一阵骚动，有些人开始交头接耳，更多的人仍然不知所措地站在原地。这时，相当于数十万美元的英国公债被猛然抛向市场，公债价格开始下滑，然后更大的抛单像海潮一般一波比一波猛烈，公债的价格开始崩溃。
这时的内森依然毫无表情地靠在他的宝座上。交易大厅里终于有人发出惊叫：“罗斯柴尔德知道了！”“罗斯柴尔德知道了！”“威灵顿战败了！”所有的人立刻像触电一般回过味来，抛售终于变成了恐慌。人在猛然失去理智的时候，跟随别人的行为成了一种自我强制性行为。每个人都想立刻抛掉手中已经毫无价值的英国公债，尽可能地留住一些所剩无几的财富。经过几个小时的狂抛，英国公债已成为一堆垃圾，票面价值仅剩下5%。[6]此时的内森像一开始一样，仍然是漠然地看着这一切。他的眼睛以一种不是经过长期训练绝不可能读懂的眼神轻微地闪动了一下，但这次的信号却完全不同。他身边的众多交易员立即扑向各自的交易台，开始买进市场上能见到的每一张英国公债。
6月21日晚11点，威灵顿勋爵的信使亨利·珀西终于到达了伦敦，消息是拿破仑大军在8个小时的苦战后被彻底打败了，损失了1/3的士兵，法国完了！
这个消息比内森的情报晚了整整一天！而内森在这一天之内，狂赚了20倍的金钱，超过拿破仑和威灵顿在几十年战争中所得到的财富的总和！[7]滑铁卢一战使内森一举成为英国政府最大的债权人，从而主导了英国日后的公债发行，英格兰银行被内森所控制。英国的公债就是未来政府税收的凭证，英国人民向政府缴纳各种税赋的义务，变成了罗斯柴尔德银行向全民变相征税。英国政府的财政支出是靠发行公债来筹集的，换句话说，英国政府因为没有货币发行权而必须向私人银行借钱花，而且要支付8%左右的利息，所有本息都是以金币结算。当内森手里攥着具有压倒性优势数量的英国公债的时候，他实际上操控着公债的价格，左右着整个英国的货币供应量，英国的经济命脉被紧紧地捏在了罗斯柴尔德家族的手中。
志得意满的内森毫不掩饰他征服了大英帝国的骄傲：我不在乎什么样的英格兰傀儡被放在王位上来统治这个庞大的日不落帝国。谁控制着大英帝国的货币供应，谁就控制了大英帝国，而这个人就是我！[8]

罗斯柴尔德起家的时代背景(1)

少数能理解这个系统（支票货币和信用货币）的人，要么是对这个系统所产生的利润非常感兴趣，要么就是非常依赖这个系统的施舍（政治家），这个阶层的人是不会反对我们的。另一方面，绝大多数的人民在智力上不足以理解基于这个系统所衍生出的资本所带来的巨大优势，他们将承受压迫而且毫无怨言，甚至一点都不会怀疑这个系统损害了他们的利益。[9]
罗斯柴尔德兄弟，1863年
老罗斯柴尔德生长在工业革命在欧洲迅猛发展、金融业空前繁荣的时代，全新的金融实践和思想从荷兰和英国向全欧洲辐射开来。随着1694年英格兰银行（Bank of England）的成立，一个远较过去复杂得多的金钱的概念和实践被一大批富于冒险精神的银行家创造出来。
在17世纪的100年中，金钱的概念和形式都发生了深刻变化，从1694年到1776年亚当·斯密的《国富论》问世时，人类历史上银行发行的纸币量第一次超过了流通中的金属货币总量[10]。工业革命所产生的对铁路、矿山、造船、机械、纺织、军工、能源等新兴行业空前巨大的融资需求，与传统金匠银行的古老低效和极为有限的融资能力之间产生了日益强烈的矛盾。以罗斯柴尔德家族为代表的新兴银行家，抓住了这一历史性的重要机遇，以对自己最为有利的方式，全面主导了现代金融业的历史走向，而所有其他人的命运则不得不或毫无知觉地被这种制度所决定。
1625年以来的两次内战和政局动荡使英国国库空虚，1689年威廉一世入主英国（由于娶了英王詹姆士二世的女儿玛丽才得到的王位）时他面对的是一个烂摊子，再加上他与法王路易十四正在进行的战争，使得威廉一世四处求钱，几近饥不择食的程度。这时，以威廉·帕特森（William Paterson）为首的银行家向国王提出一个从荷兰学来的新概念：建立一个私有的中央银行—英格兰银行，来为国王庞大的开支进行融资。
这家私有银行向政府提供120万英镑的现金作为政府的“永久债务”（Perpetual Loan），年息8%，每年的管理费为4 000英镑，这样每年政府只要花10万英镑就可以立刻筹到120万英镑的现金，而且可以永远不用还本钱！当然政府还要提供更多的“好处”，那就是允许英格兰银行独家发行国家认可的银行券（Bank Note）[11]。
长久以来人们就知道金匠银行家（Goldsmith Banker）最有利可图的就是发行银行券，这些银行券其实就是储户存放在金匠那里保管的金币的收据。由于携带大量金币非常不便，大家就开始用金币的收据进行交易，然后再从金匠那里兑换相应的金币。时间长了，人们觉得没必要总是到金匠那里存取金币，后来这些收据逐渐成了货币。聪明的金匠银行家们渐渐发现每天只有很少的人来取金币，他们就开始悄悄地增发一些收据来放贷给需要钱的人并收取利息，当借债的人连本带息地还清借据上的欠款，金匠银行家们就收回借据再悄悄地销毁，好像一切都没发生过，但利息却稳稳地装进了自己的钱袋。一个金匠银行的收据流通范围越广，接受程度越高，利润就越大。而英格兰银行发行的银行券的流通范围和接受程度，是其他银行远远无法比拟的，这些得到国家认可的银行券就是国家货币。
英格兰银行的现金股本向社会招募，认购2 000英镑以上的人，有资格成为英格兰银行的董事（Governor）。一共有1 330人成为英格兰银行的股东，14人成为银行董事，包括威廉·帕特森[12]。
1694年，英王威廉一世颁发了英格兰银行的皇家特许执照（Royal Charter），第一个现代银行就这样诞生了。
英格兰银行的核心理念就是把国王和王室成员的私人债务转化为国家的永久债务，用全民税收做抵押，由英格兰银行来发行基于债务的国家货币。这样一来，国王有钱打仗或享受了，政府有钱做自己爱做的事了，银行家放出了他们日思夜想的巨额贷款并得到了可观的利息收入，似乎是一个皆大欢喜的局面，只有人民的税收成了被抵押品。由于有了这样强大的新的金融工具，英国政府的赤字直线上升，从1670年到1685年，英国政府的财政收入是2 480万英镑。从1685年到1700年，政府收入增加了一倍多，达到了5 570万英镑，但英国政府从英格兰银行的借贷从1685年到1700年暴涨了17倍多，从80万英镑涨到了1 380万英镑。[13]
更妙的是，这个设计把国家货币的发行和永久国债死锁在一起。要新增货币就必须增加国债，而还清国债就等于摧毁了国家货币，市场上将没有货币流通，所以政府也就永远不可能还清债务。由于偿还利息和经济发展的需要，必然导致对货币更大的需求，这些钱还得向银行借债，所以国债只会永远不断地增加，而这些债务的利息收入全部落入银行家的钱袋，利息支出则由人民的税收来负担！
果然，从此以后，英国政府就再也没有还清债务，到2005年年底，英国政府的欠债从1694年的120万英镑增加到了5 259亿英镑，占英国GDP的42.8%。[14]如此看来，为了这样大的一笔巨款，如果有谁胆敢挡了私有化的国家银行之路，砍掉个把国王的头，或刺杀若干个总统的风险，实在是值得冒一下。

老罗斯柴尔德的第一桶金(1)

1744年2月23日，梅耶·A·鲍尔出生在法兰克福的犹太人聚居区，他的父亲摩西是一个流动的金匠和放贷人，常年在东欧一带谋生。当梅耶出生以后，摩西决定在法兰克福定居下来。梅耶从小就展现出惊人的智商，父亲对他倾注了大量心血，悉心调教，系统地教授他关于金钱和借贷的商业知识。几年以后，摩西去世了，年仅13岁的梅耶在亲戚的鼓励下，来到汉诺威的欧本海默家族银行当银行学徒[15]。
梅耶以其过人的悟性和勤奋迅速掌握了银行运作的各类专门技能，在整整七年的岁月里，他像海绵吸水一般吸收并消化着从英国传来的种种金融业的奇思妙想。由于工作出色，梅耶被提拔为初级合伙人。在银行工作的日子里，他结识了一些很有背景的客户，其中包括对他日后发展起了重大作用的冯·伊斯托弗将军。正是在这里，梅耶意识到把钱贷给政府和国王要比贷给个人的利润和保险系数高得多，不仅贷款数额大得多，更有政府税收做抵押。这种来自英国的全新的金融理念使梅耶的头脑焕然一新。
几年以后，年轻的梅耶回到了法兰克福，继续他父亲的放贷生意。他还将自己的姓氏改为罗斯柴尔德（Rothschild，Rot是德文的红色，Schild是德文中盾的意思）。当梅耶得知冯·伊斯托弗将军也回到法兰克福并在威廉王子的宫廷中做事时，立刻想到要好好利用一下这层关系。当冯·伊斯托弗将军再次见到梅耶时，也非常高兴。将军本人是一名钱币收藏家，而梅耶对钱币的研究更是几代祖传的，谈起古代的各种钱币是如数家珍，直听得将军眉飞色舞。更让将军欣喜的是，梅耶愿意以很低的折扣卖几枚罕见的金币给将军，很快冯·伊斯托弗将军就把梅耶当做知己。工于心计的梅耶很快和宫廷的重要人物熟稔起来。终于有一天，经冯·伊斯托弗将军引见，威廉王子召见了梅耶，原来王子本人也是金币收藏家，梅耶用同样的手段很快就让王子对他青睐有加。
在几次以低价卖给王子稀世罕见的金币之后，王子也觉得不太好意思，就问梅耶有什么需要帮忙的，梅耶不失时机地提出想要成为宫廷正式代理人，他终于如愿以偿了。1769年9月21日，梅耶在自己的招牌上镶上王室盾徽，旁边用金字写上：“M·A·罗斯柴尔德，威廉王子殿下指定代理人”[16]。一时间，梅耶的信誉大涨，生意越来越红火。
威廉王子本人在历史上是一个嗜财如命的人，在18世纪的欧洲以“租借军队”给别的国家来“维护和平”而出名。他和欧洲各个王室都关系密切，尤其喜欢和英国王室做生意—英国由于有很多海外利益，经常需要用兵，而自己的军队数量不敷使用，英国出的钱较多，也很少拖欠，所以和威廉王子一拍即合。后来在美国独立战争时，华盛顿对付的德国士兵比英国的还要多。威廉王子由此积攒下了欧洲历史上王室最大的一笔遗产，大约相当于2亿美元。难怪人们称他是“欧洲最冷血的贷款鲨鱼”。[17]
投身于威廉王子的帐下后，梅耶尽心竭力地把每件差事都办得尽善尽美，因此深得王子信任。不久法国资产阶级大革命（1789～1799）爆发，革命的浪潮从法国逐渐向周边的君主制国家蔓延。威廉王子开始焦虑不安起来，他越来越担心革命会在德国产生共鸣，暴徒们会洗劫他的财富。与王子的想法相反，梅耶却对法国革命非常高兴，因为恐慌导致他的金币生意量大涨。当革命的矛头指向神圣罗马帝国的时候，德国与英国的贸易中断了，进口货的价格飞涨，从英国贩运商品到德国贩卖使梅耶狠赚了一笔。
梅耶一直是犹太社区非常活跃的领袖人物。“每个星期六的晚上，当犹太教堂的礼拜结束之后，梅耶总是会邀请一些最具智慧的犹太学者到他的家里，他们聚拢在一起，一边慢慢地喝着葡萄酒，一边详细地讨论做一些事的顺序直到深夜。”[18]
梅耶有句名言：“在一起祈祷的家庭将凝聚在一起。”后来的人们始终闹不明白，是什么样的力量让罗斯柴尔德家族的人这样执著于征服与权力。
到1800年时，罗斯柴尔德家族已成为法兰克福最富有的犹太家族之一。梅耶还在这一年获得了神圣罗马帝国皇帝授予的“帝国皇家代理”的称号。这个称号使他能通行帝国的各个地区，免除了加在其他犹太人身上的各种赋税，他的公司人员还可以配备武器。
1803年，梅耶和威廉王子的关系日益密切，使梅耶的势力大大地跃上一个台阶。事情是这样的，威廉王子的一位表兄是丹麦国王，他向威廉王子提出想借一笔款子，威廉王子怕露富就不愿答应。当梅耶得知此事以后，认为是个很好的机会，就向王子提出一个解决方案，由王子出钱，梅耶出面协商，以罗斯柴尔德的的名义给丹麦国王贷款，利息梅耶可以提成。王子仔细想了想，觉得是个不错的办法，既能放贷收钱又不会露富。对于梅耶来说，放贷给国王是他梦寐以求的事，不仅能得到稳定的回报，更是提高声誉的绝好机会。结果贷款获得了极大的成功。紧接着，又有六笔丹麦王室的贷款通过梅耶成交。罗斯柴尔德声名鹊起，尤其是他与皇室的密切联系在欧洲开始为人所知。
拿破仑当政以后，曾经试图将威廉王子拉到自己一边，威廉王子首鼠两端，不愿在形势明朗之前选边站队，最后拿破仑宣布“要把赫思－凯瑟（威廉王子家族）从欧洲的统治者名单中清除出去”，随即法军大兵压境，威廉王子仓皇流亡到丹麦，出逃之前，将一笔价值300万美元的现金交给梅耶保管[19]。就是这300万美元的现金为梅耶带来了前所未有的权力和财富，成为梅耶铸造其金融帝国的第一桶金。
梅耶有比建立一个英格兰银行要大得多的雄心！当他得到了威廉王子这笔巨款的时候，他就开始点兵遣将了。他的五个儿子像五支利箭射向欧洲的五个心脏地区。老大阿姆斯洛镇守法兰克福总部，老二所罗门到维也纳开辟新战场，老三内森被派往英国主持大局，老四卡尔奔赴意大利的那不勒斯建立根据地，并作为兄弟之间的信使往来穿梭，老五詹姆斯执掌巴黎业务。
一个人类历史上前所未有的金融帝国揭开了帷幕。

内森主宰伦敦金融城

他们（罗斯柴尔德家族）是世界金钱市场的主宰，当然也就是几乎所有一切其他事物的主宰。他们实际上拥有以整个南意大利地区的财政收入做抵押的资产，（欧洲）所有国家的国王和部长都在聆听他们的教诲。[20]
本杰明·迪斯雷利，英国首相，1844年
伦敦金融城是大伦敦地区中心的一块占地仅2.6平方公里的地区，18世纪以来一直是英国乃至世界的金融中心，它拥有独立的司法系统，与梵蒂冈很类似，颇像一个国中之国。这个弹丸之地云集着包括英格兰银行总部在内的世界主要的金融机构，创造了当今英国GDP的1/6。谁主宰着伦敦金融城，谁就主宰着英国。
内森初到英国正值法英对峙，互相封锁。英国货在欧洲价格卖得很高，内森开始与在法国的弟弟詹姆斯联手把货物从英国偷运到法国转手，从中赚了很多钱。后来内森结识了英国财政部的官员约翰·哈里斯，打听到英军在西班牙的困境。当时威灵顿公爵所统帅的英军已经做好了进攻法军的准备，唯一的难题就是缺少军饷。威灵顿公爵尽管有英国政府的担保，但他磨破了嘴皮子也难以说服西班牙和葡萄牙的银行家接受他拿出的银行券，威灵顿公爵的大军迫切需要黄金[21]。
内森灵机一动，决心要在此事上大捞一笔。他四处打听黄金的货源，正好东印度公司有一批黄金刚从印度运来，准备出售，而英国政府也想购买，只是觉得价格太高，想等黄金价格降下来再购进。内森摸准了情况，立即将他带到英国打天下的威廉王子的300万美元现金和自己走私英国货物赚来的大笔资金全部押上，抢先与东印度公司成交，购买了80万英镑的黄金[22]，然后立刻抬高黄金价格。英国政府眼见黄金价格降不下来，前方军情又十万火急，只有从内森手中以高价购进。这一笔交易让内森赚得盆满钵满。
但内森继续施展连环计，他又提出要护送这批黄金到威灵顿公爵的军中。当时法国对英国进行严密的陆上封锁，此行风险极大，英国政府愿意付很高的价钱来运送这批黄金。拿到这个差事之后，内森让他年仅19岁的弟弟詹姆斯通知法国政府，内森想运送黄金到法国，英国政府可能会对此非常愤怒，因为黄金流到法国会大大削弱英国的财政能力。法国方面一听有这样的大好事，岂有不大力支持的道理，立即下令法国警察沿途保护，一路放行。个别瞧出名堂的法国官员也被重金贿赂，装聋作哑。
于是内森等人押送的黄金，得到了英法两国政府的支持，浩浩荡荡、大摇大摆地进入巴黎的银行，内森一面参加法国政府的欢迎宴会，一面悄悄派人把黄金兑换成威灵顿公爵能够接受的金币，再神不知鬼不觉地通过罗斯柴尔德的运输网络运到了西班牙的英军手中。其手法之高妙直追现代好莱坞的电影情节。
一位普鲁士驻英国的外交官这样说道：“罗斯柴尔德对这里（伦敦）的金融事务的影响力大得惊人。他们完全左右着伦敦金融城的外汇交易价格。作为银行家，他们的权力令人瞠目。当内森发怒时，英格兰银行都在颤抖。”
有一次，内森拿着他哥哥阿姆斯洛从法兰克福罗斯柴尔德银行开的支票到英格兰银行要求兑换现金，银行以只兑换本银行支票为由加以拒绝。内森勃然大怒，第二天一早，他领着自己的九名银行职员，带着大批英格兰银行的支票要求兑现黄金，只一天就使英格兰银行的黄金储备明显下降。第二天，内森带来更多的支票，一名银行的高级主管颤声问内森还要兑换几天，内森冷冷地回答：“英格兰银行拒绝接受我的支票，我干吗要它的？”英格兰银行立即召开紧急会议，然后银行的高级主管非常客气地告诉内森，英格兰银行今后将荣幸地兑换所有罗斯柴尔德银行的支票。
内森在滑铁卢战役中一举夺得伦敦金融城的主导权，从而掌握了英国的经济命脉。从此，包括货币发行和黄金价格等至关重要的决定权，一直把持在罗斯柴尔德家族的手中。

詹姆斯征服法兰西

当一个政府依赖银行家的金钱时，掌握着局势的便是银行家，而不是政府的领导人，因为给钱的手始终高于拿钱的手。金钱没有祖国，金融家不知道何为爱国和高尚，他们的唯一目的就是获利。[23]
拿破仑，1815年
老罗斯柴尔德的第五个儿子詹姆斯在拿破仑执政时期，主要来往于伦敦和巴黎之间，建立家族运输网络来走私英国货。在帮助威灵顿运送黄金和英国国债收购战之后，詹姆斯在法国名声大噪。他建立了罗斯柴尔德巴黎银行，并暗地里资助西班牙革命。
1817年，滑铁卢战败之后，法国丧失了拿破仑战争中得来的大片领土，政治上限于被围堵的境地，国民经济也日益凋敝。路易十八的政府四处贷款，希望在财政上逐渐站稳脚跟。一家法国银行和英国的巴林银行得到了数目庞大的政府融资项目，而声名显赫的罗斯柴尔德银行却名落孙山，詹姆斯为此愤愤不平。
到了1818年，由于前一年发行的政府债券在巴黎和其他欧洲城市都行情见涨，法国政府尝到了甜头，想再向这两家银行融资。罗斯柴尔德兄弟费尽心机也得不到半点利益。原来，法国贵族们自恃出身显赫，血统高贵，觉得罗斯柴尔德家族不过是一群乡巴佬暴发户，不愿意和他们做生意。尽管詹姆斯在巴黎财大气粗，豪宅华服，但社会地位并不高，法国贵族的高傲令詹姆斯恼羞成怒。
詹姆斯立即和其他几个兄弟开始策划制服法国贵族们的计划。而法国的贵族们高傲却不聪明，更低估了罗斯柴尔德家族在金融方面出类拔萃的战略战术，其运筹帷幄决胜千里的能力，并不低于拿破仑在军事上的造诣。
1818年11月5日，一向稳健升值的法国公债突然开始颇不寻常地跌价。很快，政府的其他债券也开始受到影响，价格出现了不同程度的下滑。市场上的投资者开始议论纷纷。随着时间的推移，情况非但没有好转，反而越来越糟[24]。交易所里的议论逐渐演变成流言四起，有人说拿破仑可能再次上台，也有人说政府财政税收不足以偿还利息，还有人担心爆发新的战争。
路易十八的宫廷内部气氛也相当紧张，债券如果继续大幅下滑，政府以后的开支将无从筹集。高傲的贵族们的脸上也堆满了愁容，每个人都在担心这个国家的未来。只有两个人在一边冷眼旁观，他们就是詹姆斯和他的哥哥卡尔。
由于有英国的前车之鉴，慢慢地有人开始怀疑罗斯柴尔德家族在操纵公债市场。实际情况正是如此。从1818年的10月开始，罗斯柴尔德家族开始以其雄厚的财力做后盾，在欧洲各大城市悄悄吃进法国债券，法国债券渐渐升值。然后，从11月5日开始，他们突然在欧洲各地同时放量抛售法国债券，造成了市场的极大恐慌。
眼看着自己的债券价格像自由落体一般滑向深渊，路易十八觉得自己的王冠也随之而去了。此时，宫廷里罗斯柴尔德家族的代理人向国王进言，为什么不让富甲天下的罗斯柴尔德银行试试挽救局面呢？心神不定的路易十八再也顾不上皇家的身份地位了，马上召见詹姆斯兄弟。爱丽舍宫的氛围为之一变，被冷落许久的詹姆斯兄弟处处被笑脸和尊敬包围着。
果然，詹姆斯兄弟一出手就制止了债券的崩溃，他们成了法国上下瞩目的中心，在法国军事战败之后，是他们从经济危机中拯救了法国！赞美和鲜花令詹姆斯兄弟陶醉不已，连他们的衣服款式也成了流行的时装样式。他们的银行成了人们竞相求贷的地方。
由此，罗斯柴尔德家族完全控制了法国金融。
“詹姆斯·罗斯柴尔德的财富达到了6亿法郎。在法国只有一个人的财富比他多，那就是法国国王，他的财富是8亿法郎。法国其他所有银行家的财富加在一起仍然比詹姆斯少1.5亿法郎。这样的财富自然赋予了他不可名状的权力，甚至到了随时可以让政府内阁垮台的程度。比如，众所周知的梯也尔政府就是被他推翻的。”[25]

所罗门问鼎奥地利(1)

在他们（罗斯柴尔德家族）的眼里没有战争与和平，没有口号和宣言，也没有牺牲或荣誉，他们忽略了这些迷惑世人眼睛的东西。他们的眼中只有垫脚石。威廉王子是一个，下一个就是梅特涅。[26]
弗雷德里克·默顿
所罗门是罗斯柴尔德家的老二，常年穿梭于欧洲各大城市之间，担任家族各个银行之间的协调人角色。他在几个兄弟中具有过人的外交才能，说话措辞考究，巧于恭维。一位和所罗门打过交道的银行家曾评论道：“没有人离开他时不是神清气爽的。”正是因为这个原因，弟兄们公推他到维也纳开拓欧洲心脏地区的银行业务。
维也纳是当时欧洲的政治中心，几乎所有的欧洲王室都和奥地利的哈布斯堡王朝有着千丝万缕的血缘关系。哈布斯堡王朝作为神圣罗马帝国（1806年解体）的王室，统治着包括现在的奥地利、德国、意大利北部、瑞士、比利时、荷兰、卢森堡、捷克、斯洛文尼亚以及法国东部地区长达400余年，是欧洲最古老、最正宗的王室血脉。
拿破仑战争虽然打垮了神圣罗马帝国，但它的继承者奥地利仍然以中欧的龙头自居，傲视其他的王室。加之其正统的天主教教义，与英法等新教盛行的国家相比要僵化不少，和这样的高贵家族打交道，要比与威廉王子交往高贵得多。虽然罗斯柴尔德家族过去曾经几次想和哈布斯堡建立商业关系，结果始终被王室挡在圈子之外，不得其门而入。
当拿破仑战争结束后，所罗门再次叩响维也纳的大门时，情势已经全然不同了。罗斯柴尔德家族在欧洲已成为名噪一时的望族，挟征服英法之锐气，底气足了不少。尽管这样，所罗门也不敢造次去直接和哈布斯堡的人谈生意，而是找到了一块“垫脚石”，他就是名震19世纪欧洲政坛的奥地利外长梅特涅（Klemens von Metternich）。
拿破仑战败之后的欧洲，由梅特涅牵头建立的维也纳体系维系了19世纪欧洲最长的和平时期。梅特涅在奥地利日渐衰落而强敌环伺的不利态势下，把制衡的精髓发挥到了极致。他利用哈布斯堡在欧洲残存的皇家正统号召力，拉住邻国普鲁士和俄国组成神圣同盟，既遏制了法国的东山再起，又牵制了俄国扩张的躁动，还形成了联合压制境内民族主义和自由主义浪潮的机制，确保了奥地利境内多民族分裂势力不致失控。
1818年的亚琛会议是讨论拿破仑战败后欧洲未来的一次重要会议，来自英、俄、奥、普、法等国代表决定了法国的战争赔款和同盟国撤军等问题。所罗门和他的弟弟卡尔都参加了这次会议。正是在这次会议上，经梅特涅的左右手金斯（Gentz）引荐，所罗门结识了梅特涅，并很快地与梅特涅成为无话不谈的密友。一方面所罗门巧妙而得当的赞美让梅特涅极为受用，另一方面，梅特涅也很想借重罗斯柴尔德家族的雄厚财势，两人一拍即合，所罗门和金斯更是铁得不分彼此。
在梅特涅和金斯的极力推荐下，加之罗斯柴尔德与威廉王子和丹麦王室密切的商业关系，哈布斯堡高大的围墙终于被所罗门越过了。王室开始固定和频繁地向所罗门的银行贷款和融资，所罗门很快就成了“圈里人”。1822年，哈布斯堡王室授予罗斯柴尔德四兄弟（内森除外）男爵封号。
在所罗门的大力资助之下，梅特涅开始扩张奥地利的影响力，四处派出军队去麻烦地区“保卫和平”，使原本国力日衰的奥地利陷入了更深的债务泥潭，从而更加依赖所罗门的银箱。1814～1848年的欧洲被称为“梅特涅时代”，而实际上控制着梅特涅的是背后的罗斯柴尔德银行。
1822年，梅特涅、金斯和所罗门、詹姆斯、卡尔三兄弟参加了重要的维罗纳会议（Verona Congress）。会后，罗斯柴尔德银行得到了利益丰厚的资助第一条中欧铁路的项目。奥地利人越来越感受到罗斯柴尔德的影响力，人们开始笑言“奥地利有一个斐迪南皇帝和一个所罗门国王”。1843年，所罗门收购了V抰kovice联合矿业公司和奥地利－匈牙利冶炼公司，这两家公司都名列当时世界十家最大的重工业公司。
到1848年，所罗门已成为奥地利金融和经济的主宰者。

罗斯柴尔德盾徽下的德国和意大利

自从拿破仑从德国撤军之后，德国由过去300多个松散的封建小国合并成30多个较大的国家，并成立了德意志联邦。留守法兰克福的罗斯柴尔德家老大阿姆斯洛被任命为德意志的首届财政部长，1822年被奥地利皇帝加封为男爵。法兰克福的罗斯柴尔德银行成为德国金融的中心。由于阿姆斯洛膝下无子，引为终生憾事，所以对后起之秀倾心扶持。其中一位深得阿姆斯洛喜爱的年轻人就是后来闻名世界现代史的德国铁血宰相俾斯麦。
阿姆斯洛与俾斯麦情同父子，阿姆斯洛去世后，俾斯麦与罗斯柴尔德家族仍然保持着密切联系。俾斯麦背后的银行家布雷克劳德（Samuel Bleichroder）也是罗斯柴尔德家族的代理人[27]。
老四卡尔是罗斯柴尔德五兄弟中最平庸的一个，担任家族的主要信使，往来欧洲各地传递信息和协助其他兄弟。帮助五弟在法国1818年国债战役中取得辉煌胜利之后，卡尔被执掌家门的三哥内森派往意大利的那不勒斯建立银行。他在意大利却展露了超出其他兄弟预期的能力。卡尔不仅资助了梅特涅派往意大利镇压革命的军队，而且以出色的政治手腕迫使意大利当地政府承担了占领军的费用。他还帮朋友麦迪奇策划并夺回了那不勒斯财政大臣的要职。卡尔逐渐地成为意大利宫廷的财政支柱，影响力遍及意大利半岛。他还与梵蒂冈教廷建立了商业往来，当教皇格里高利十六世见到他时，破例伸出手让卡尔亲吻，而不是像惯常那样伸出脚来。

罗斯柴尔德金融帝国(1)

只要你们兄弟凝聚在一起，世界上没有任何一家银行能够与你们竞争、伤害你们，或是从你们身上渔利。你们合在一起将拥有比世界上任何一家银行都要大的威力。[28]
戴维森给内森的信，1814年6月24日
老罗斯柴尔德在1812年去世之前，立下了森严的遗嘱：
（1）所有的家族银行中的要职必须由家族内部人员担任，绝不用外人。只有男性家族人员能够参与家族商业活动。
（2）家族通婚只能在表亲之间进行，防止财富稀释和外流。（这一规定在前期被严格执行，后来放宽到可以与其他犹太银行家族通婚。）
（3）绝对不准对外公布财产情况。
（4）在财产继承上，绝对不准律师介入。
（5）每家的长子作为各家首领，只有家族一致同意，才能另选次子接班。
任何违反遗嘱的人，将失去一切财产继承权[29]。
中国有句俗话，兄弟同心，其利断金。罗斯柴尔德家族通过家族内部通婚严格防止财富稀释和外流。在100多年里，家族内部通婚18次，其中16次是在第一表亲（堂兄妹）之间。
据估计，1850年左右，罗斯柴尔德家族总共积累了相当于60亿美元的财富，如果以6%的回报率计算，在150多年后的今天，他们家族的资产至少超过了50万亿美元。
严密的家族控制，完全不透明的黑箱操作，像钟表一般精确的协调，永远早于市场的信息获取，彻头彻尾的冷酷理智，永无止境的金权欲望，以及基于这一切的对金钱和财富的深刻洞察和天才的预见力，使得罗斯柴尔德家族在两百多年金融、政治和战争的残酷旋涡中所向披靡，建立了一个迄今为止人类历史上最为庞大的金融帝国。
到20世纪初，罗斯柴尔德家族所控制的财富估计达到了当时世界总财富的一半。[30]
罗斯柴尔德家族银行遍及欧洲主要城市，他们拥有自己的情报收集和快速传递系统，甚至欧洲国家的王室和贵族在需要迅速和秘密地传递各种信息时，都是通过他们的系统进行。他们还首创了国际金融清算系统，利用其对世界黄金市场的控制，他们在家族银行体系中首先建立起不用实物黄金运输的账目清算系统。
在这个世界上，只怕没有其他人比罗斯柴尔德家族更能深刻理解黄金的真正意义。当2004年罗斯柴尔德家族宣布退出伦敦黄金定价系统时，他们正在悄悄地远离未来世界空前的金融风暴的中心，撇清他们与黄金价格之间的关系。负债累累的美元经济和危机四伏的世界法定货币体系，以及世界外汇储备体系很有可能将面临一场清算，只拥有微不足道的黄金储备的亚洲国家积累多年的财富，将被“重新分配”给未来的赢家。对冲基金将再次发动攻击，只不过这一次的对象将不再是英镑和亚洲货币，而是世界经济的支柱—美元。
对于银行家而言，战争是天大的喜讯。因为和平时期缓慢折旧的各种昂贵设施和物品，会在战争中顷刻之间灰飞烟灭，交战各方会不惜一切代价去取得胜利，到战争结束时，政府无论输赢都将深深地陷入银行的债务陷阱之中。在英格兰银行成立到拿破仑战争结束的121年时间里（1694～1815），英国有56年处于战争之中，剩下的一半时间在准备下一场战争。
策动和资助战争符合银行家的根本利益，罗斯柴尔德家族也不例外，从法国大革命到第二次世界大战的几乎所有近代战争的背后，几乎都闪动着他们的影子。罗斯柴尔德家族是当今主要西方发达国家最大的债权人。老罗斯柴尔德的夫人（Gutle Schnaper）在去世之前说道：“如果我的儿子们不希望发生战争，那就不会有人热爱战争了。”
到19世纪中叶，英、法、德、奥、意等欧洲主要工业国的货币发行大权均落入了罗斯柴尔德家族的控制之中，“神圣的君权被神圣的金权所取代”。此时，大西洋彼岸美丽繁荣富庶的美利坚大陆早已落入了他们的视野。
注 释
[1] G. Edward Griffin, The Creature from Jekyll Island (American Media, Westlake Village, CA 2002), p218.
[2] Note: Morton (1962) noted that the Rothschild wealth was estimated at over $6 billion US in 1850. Not a significant amount in today誷 dollars; however, consider the potential future value compounded over 156 (2006) years!
Taking $6 billion (and assuming no erosion of the wealth base) and compounding that figure at various returns on investment (a conservative range of 4% to 8%) would suggest the following net worth of the Rothschild family enterprise:
$2.7 trillion US (@ 4%)
$12.1 trillion US (@ 5%)
$53.2 trillion US (@ 6%)
$230.2 trillion US (@ 7%)
$982.3 trillion US (@ 8%)
[3] Des Griffin, Descent into Slavery (Emissary Publications 1980), Chapter 5.
[4] Des Griffin, Descent into Slavery (Emissary Publications 1980), p94.
[5] Eustace Mullins, The Secrets of the Federal Reserve-The London Connection (Bankers Research Institute, 1985), Chapter 5.
[6] Des Griffin, Descent into Slavery (Emissary Publications 1980), Chapter 5.
[7] Ignatius Balla, The Romance of the Rothschilds, (Everleigh Nash, London, 1913).
Note: the New York Times, April 1, 1915 reported that in 1914, Baron Nathan Mayer de Rothschild went to court to suppress Ignatius Balla誷 book on the grounds that the Waterloo story about his grandfather was untrue and libelous. The court ruled that the story was true, dismissed Rothschild誷 suit, and ordered him to pay all costs.
[8] Eustace Mullins, The Secrets of the Federal Reserve-The London Connection (Bankers Research Institute, 1985), Chapter 5.
[9] The Rothschild Brothers of London in a letter sent in 1863 to New York Bankers in support of the then proposed National Banking Act.
[10] Glyn Davis, History of Money From Ancient Times to The Present Day (University of Wales Press 2002), p257, p258.
[11] Eustace Mullins, The Secrets of the Federal Reserve-The London Connection (Bankers Research Institute, 1985), Chapter 5.
[12] Ibid.
[13] Glyn Davis, History of Money From Ancient Times to The Present Day (University of Wales Press 2002), p239.
[14] UK National Statistics (http://www.statistics.gov.uk/ CCI/nugget.asp?ID=277).
[15] Des Griffin, Descent into Slavery (Emissary Publications 1980), Chapter 5.
[16] Ibid.
[17] Frederic Morton, The Rothschilds (Fawcett Books, 1961), p40.
[18] Ibid., p31.
[19] Des Griffin, Descent into Slavery (Emissary Publications, 1980), Chapter 5.
[20] Benjamin Disraeli, Coningsby (New York: Alfred A. Knopf, originally published in England in 1844), p225 .
[21] G. Edward Griffin, The Creature from Jekyll Island (American Media, Westlake Village, CA 2002), p224.
[22] Frederic Morton, The Rothschilds (Fawcett Books, 1961), p45.
[23] R. McNair Wilson, Monarchy or Money Power (London: Eyre and Spottiswoode, Ltd., 1933), p68.
[24] Des Griffin, Descent into Slavery (Emissary Publications, 1980), Chapter 5.
[25] David Druck, Baron Edmond de Rothschild (Privately printed), N.Y. 1850.
[26] Frederic Morton, The Rothschilds (Fawcett Books, 1961).
[27] Des Griffin, Descent into Slavery (Emissary Publications 1980), Chapter 5.
[28] Lord Rothschild, The Shadow of a Great Man. London: 1982, p.6.
[29] Des Griffin, Descent into Slavery (Emissary Publications,1980), Chapter 5.
[30] Ted Flynn, Hope of the Wicked (MaxKol Communication, Inc, 2000), p38
