# -*- org -*-

# Time-stamp: <2011-09-15 19:48:40 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent


林肯，美国第16届总统

本章导读
如果说中国的历史是围绕着政治权力斗争而展开，不理解帝王心术就无法洞察中国历史的精髓，那么西方近代史则是沿着金钱角逐而进化的，不明了金钱的机谋就不能把握西方历史的脉络。
美国的成长历程充斥着国际势力的干预和阴谋，其中尤以国际金融势力对美国的渗透和颠覆最令人惊心动魄，而却最不为人所知。
民主制度的设计和建立几乎是全神贯注地防范封建专制势力的威胁，并在这方面取得了可观的成效，但是，民主制度本身对金钱权力这一新生的、致命的病毒，却没有可靠的免疫力。
新生的民主制度对于“国际银行家通过控制货币发行权来控制整个国家”这一战略主攻方向的判断和防御出现了重大漏洞。“金钱超级特殊利益集团”与美国民选政府在南北战争前后的一百多年的时间里，双方在美国私有中央银行系统的建立这一金融制高点上进行了反复的殊死搏斗，前后共有七位美国总统因此被行刺，多位国会议员丧命。美国历史学家指出，美国总统的伤亡率比美军二战期间，诺曼底登陆的一线部队的平均伤亡率还要高！
随着中国金融的全面开放，国际银行家将大举深入中国的金融腹地，昨天发生在美国的故事，今天会在中国重演吗？

刺杀林肯总统

1865年4月14日星期五晚上，在艰难困苦和重重危机中度过了四年残酷内战的林肯总统，终于在五天前迎来了南军将领罗伯特·李将军向北方格兰特将军投降的胜利消息，总统高度紧张的神经一下子松弛下来，兴致颇高地来到华盛顿的福特剧院看表演。10点15分，凶手潜入没有守卫的总统包厢，在距离林肯不到两英尺的后方，用一把大口径手枪向总统的头部开枪，林肯中弹后倒向前方。第二天凌晨，林肯总统去世。
凶手是一个名叫布斯（John Wilkes Booth）的颇有名气的演员。他在刺杀林肯之后仓皇出逃，据说4月26日凶手在逃亡途中被击毙。在凶手的马车里，发现了很多用密码写成的信件和一些犹大·本杰明的私人物品，这个犹大是当时南方政府的战争部长和后来的国务卿，也是南方金融方面的实权人物，因为他和欧洲的大银行家们过从甚密。他后来逃到了英国。刺杀林肯事件被广泛认为是一个大规模的阴谋。参与阴谋的可能有林肯的内阁成员、纽约和费城的银行家、南方的政府高官、纽约的报纸出版商和北方的激进分子。
当时流传甚广的一个说法是，布斯并没有被杀死，而是被放走了，后来埋葬的尸体是他同谋的。当时手握重权的战争部长埃德温·斯坦顿（Edwin Stanton）掩盖了事实真相。乍听之下，这又是一个荒谬的阴谋论说法。但是，当战争部长的大量秘密文件到20世纪30年代中期被解密之后，历史学家吃惊地发现，真相竟和民间传说高度吻合。
第一个深入研究这些惊人史料的是历史学家奥托·爱森斯默（Otto Eisenschiml），他发表的《为什么林肯被刺杀？》震动了当时的史学界。后来，西奥多·罗斯科（Theodore Roscoe）出版了影响更广泛的研究结果，他指出：
19世纪大量有关刺杀林肯事件的历史研究，对福特剧院的悲剧描述更像是在展示一部大型歌剧……只有少数人将其作为一个谋杀事件来看待：林肯死于一个鲁莽的罪犯手中……罪犯得到了经典的法律惩罚；阴谋论被扼杀了；美德最终取得了胜利，林肯也“属于过去”了。
但是，刺杀事件的解释既不能使人满意也难以令人信服。事实表明，林肯之死的相关罪犯一直逍遥法外。[2]
凶手的孙女伊左拉（Izola Forrester）在她的回忆录《这个疯狂的行动》（This One Mad Act）中提到，她发现“金色圆圈骑士”（Knights of the Golden Circle）的秘密记录被政府小心地收藏在一个文件库里，并被战争部长埃德温·斯坦顿列为机密材料。林肯遇刺后，任何人都不允许接触这些文件。由于伊左拉与布斯的血缘关系，以及她作为专业作家的身份，她最终成为第一个获准查阅这些材料的学者。她在书中说道：
这些神秘的旧文件包，被隐藏在存放“阴谋审判”的遗迹和展览的房间角落的一个保险箱里。如果不是五年前，我偶然跪在（那个房间的）地上翻阅资料时看到了保险箱的一侧，我可能永远都不会发现它们（秘密文件）。
这里（的文件）与我祖父有关。我知道他曾是一个秘密组织的成员，这个组织就是由比克利（Bickley）建立的“金色圆圈骑士”。我有一张他（祖父）的照片，是和他们一起照的，他们全都穿着全套的制服，这张照片是从我祖母的《圣经》中发现的……我还记得祖母曾说过她的丈夫（布斯）是“别人的工具”。[3]
“金色圆圈骑士”和纽约的金融势力到底是什么样的关系？林肯政府内部有多少人卷入了刺杀林肯的阴谋？对林肯遇刺的研究怎么会长期系统性地偏离正确方向？林肯的遇刺和一百年后的肯尼迪遇刺颇为相似，同样都是大规模的组织协调，全方位的证据封杀，系统性的调查误导，真相始终隐藏在一片浓厚的历史迷雾之中。
要理解刺杀林肯的真正动机和图谋，我们必须以更大的历史纵深来审视美国立国以来，民选政府和金钱权力在控制货币发行权这一国家战略制高点上的反复与殊死较量。

货币发行权与美国独立战争(1)

有关美国独立战争的起源分析的历史课本，比较多地采取了全面地和抽象地论述大的原则和意义的方式。在这里我们将从另一个视角，去阐述这场革命的金融背景及其所起到的核心作用。
最早到美洲大陆谋生的人大多是非常穷困的贫民，他们除了随身的简单行李，几乎没有什么财产和金钱。当时的北美还没有发现大型的金矿和银矿，所以在市场上流通的货币极为短缺。加之与母国英国的严重贸易逆差使得大量金银货币流向英国，更加剧了流通货币的稀缺[4]。
北美的新移民通过辛勤的劳动所创造出来的大量产品和服务，由于流通货币短缺而无法进行充分和有效的交换，从而严重地制约了经济的进一步发展。为了应对这个难题，人们不得不使用各种替代货币进行商品交易。诸如动物的皮毛、贝壳、烟草、大米、小麦、玉米等接受程度较高的物品被各地用来当钱使。仅在北卡罗来纳州，1715年时就有多达17种不同的物品被当做法定货币（Legal Tender），政府和民间可用这些物品进行税务缴纳、公私债务偿还和商品服务买卖。当时所有这一切替代货币都以英镑、先令作为会计结算标准。在实际运作中，这些物品由于成色、规格、接受度和可保存性都相差很大，难以进行标准计量，所以虽然在一定程度上缓解了没有货币的燃眉之急，但仍然构成了商品经济发展的重要瓶颈。[5]
长期的金属货币奇缺和替代实物货币应用的不便，促使当地政府跳出传统思维，开始了一种崭新的尝试，那就是由政府印刷和发行纸币（Colonial Script）来作为统一和标准的法币。这种纸币和欧洲流行的银行券最大的区别就是，它没有任何金银实物做抵押，是一种完全的政府信用货币。社会上的所有人都需要向政府交税，而只要政府接受这种纸币作为缴税的凭证，它便具备了在市场上流通的基本要素。
新的货币果然大大地促进了社会经济的迅速发展，商品贸易日趋繁荣。
与此同时，英国的亚当·斯密也注意到了北美殖民地政府这一新的货币尝试，他相当清楚这种纸币所带来的对商业的巨大刺激作用，特别是对于缺少金属货币的北美地区，“基于信用的买和卖，使得商家可以每月或每年定期结算相互之间的信用余额，这将减少（交易的）不便。一个管理良好的纸币系统，不仅不会产生任何不便，甚至可以在某些情况下拥有更多的优势”。[6]
但是，一种没有抵押的货币是银行家的天敌，因为没有政府债务做抵押，政府就不需要向银行借当时最为稀缺的金属货币，银行家手上最大的砝码一下子就失去了威力。
当本杰明·富兰克林在1763年访问英国时，英格兰银行的主管问他新大陆的殖民地如此兴旺发达的原因，富兰克林回答：“这很简单。在殖民地，我们发行自己的货币，名叫‘殖民券’。我们按照商业和工业的需要来发行等比例的货币，这样，产品就很容易地从生产者那里传递到消费者手中。用这种方式创造我们自己的纸货币，并保证它的购买力，我们（的政府）不需要向任何人支付利息。”[7]
这种新的纸货币必然会导致美洲殖民地脱离英格兰银行的控制。
愤怒的英国银行家们立刻行动起来，在他们控制之下的英国议会于1764年通过《货币法案》（Currency Act），严厉禁止美洲殖民地各州印发自己的纸币，并强迫当地政府必须使用黄金和白银来支付全部向英国政府缴纳的税收。
富兰克林痛苦地描述这个法案给殖民地各州带来的严重经济后果，“只一年的时间，（殖民地的）情况就完全逆转了，繁荣时代结束了，经济严重衰退到大街小巷都站满了失业的人群。[8]
“如果英格兰不剥夺殖民地的发币权，殖民地人民是乐意支付茶叶和其他商品作为额外的少量税赋的。这个法案造成了失业和不满。殖民地不能发行自己的货币，从而将无法永久地摆脱国王乔治三世和国际银行家的控制，这是美国独立战争爆发最主要的原因。”[9]
美国的开国奠基者们对于英格兰银行对英国政治的控制和对人民的不公有着相当清醒的认识。年仅33岁就完成了万古流芳的美国《独立宣言》的作者，也是美国第三届总统的托马斯·杰斐逊有一句警世名言：如果美国人民最终让私有银行控制了国家的货币发行，那么这些银行将先是通过通货膨胀，然后是通货紧缩，来剥夺人民的财产，直到有一天早晨当他们的孩子们一觉醒过来时，他们已经失去了自己的家园和父辈曾经开拓过的土地。[10]两百多年后再来聆听1791年杰斐逊的这一段话时，我们不禁惊叹他的预见惊人的准确。今天，美国私有银行果然发行了国家货币流通量的97%，美国人民也果然欠着银行44万亿美元的天文数字般的债务，他们也许真的有一天一觉醒来就会失去家园和财产，就像1929年发生过的一样。
当美利坚的伟大先驱们用他们智慧和深邃的目光审视着历史和未来时，他们在美国《宪法》第一章第八节开宗明义地写下：“国会拥有货币的制造和价值设定的权利。”[11]

国际银行家的第一次战役：美国第一银

行（1791～1811）我坚信银行机构对我们自由的威胁比敌人的军队更严重。他们已经创造出了一个金钱贵族阶级，并且藐视政府。（货币的）发行权应该从银行手中夺回来，它应该属于它正当的主人—人民。[12]美国第三届总统托马斯·杰斐逊，1802年亚历山大·汉密尔顿是一个与罗斯柴尔德家族有着密切联系的重量级人物。他出生在英属西印度群岛，在隐瞒了他的年龄、真名和出生地的情况下来到美国并与纽约望族的女儿成亲。大英博物馆收藏的付款收据显示，汉密尔顿接受过罗斯柴尔德家族的资助。[13]1789年，汉密尔顿被华盛顿总统任命为美国第一任财政部长，他始终是美国中央银行制度的主要推动者。1790年，面对独立战争之后严重的经济困境和债务危机，他强烈建议国会成立类似于英格兰银行的私有的中央银行，以彻底履行发行货币的职责。他的主要思路是：中央银行由私人拥有，总部设在费城，各地设立分支银行，政府的货币和税收必须放在这个银行系统中，该银行负责发行国家货币来满足经济发展的需要，向美国政府贷款并收取利息。该银行总股本为1 000万美元，私人拥有80%的股份，美国政府拥有剩余的20%。25人所组成的董事会中的20人由股东推举，5人由政府任命。
汉密尔顿代表着精英阶级的利益，他曾经指出：“所有的社会都分成极少数和大多数人群。前者出身良好而富有，后者则是普罗大众。大众是动荡和变化的，他们很少能做出正确的判断和决定。”
而杰斐逊则代表着人民大众的利益，对于汉密尔顿的观点，他的回应是：“我们认为下述真理是不言而喻的：人人生而平等，造物主赋予他们若干不可剥夺的权利，其中包括生存权、自由权和追求幸福的权利。”
在私有中央银行制度的问题上，双方也是针锋相对。
汉密尔顿认为，“如果不把社会上有钱的个人的利益和财富信用集中起来，这个社会不可能成功。”[14]“国家的债务，如果不是过多，应该是我们国家的福祉。”[15]杰斐逊反驳道，“一个私有的中央银行发行人民的公共货币，这对人民自由的威胁比敌人的军队更严重。”[16]“我们不能容忍统治者将永久债务强加在人民的身上。”[17]1791年12月，当汉密尔顿的方案被提交国会讨论时，立即引起了空前激烈的争论。最终，参议院以微弱多数通过了这项提案，而在众议院也以39对20票过关。此时，被严重的债务危机压得喘不过气的总统华盛顿陷入了深深的犹豫，他征询了当时的国务卿杰斐逊和麦迪逊的意见，他们明确表示这个提案明显与宪法冲突。宪法授权国会发行货币，但绝没有授权国会转让发币权给任何私人银行。华盛顿显然被深深地触动了，他甚至已决心要否决该法案。
得知这个消息后，汉密尔顿立刻跑来游说华盛顿，财政部长汉密尔顿的账本似乎更有说服力，那就是如果不成立中央银行以得到外国资金入股，政府将很快垮台。最终，迫在眉睫的危机压倒了对未来长远的顾虑，华盛顿总统于1791年2月25日签署了美国第一个中央银行的授权，有效期20年。[18]国际银行家终于取得了第一个重大胜利。到1811年，外国资本占到了1 000万股本中的700万，英格兰银行和内森·罗斯柴尔德成为美国中央银行—美国第一银行（The first Bank of the United States）的主要股东。[19]汉密尔顿最终成为巨富。第一银行后来与亚伦·波成立的纽约曼哈顿公司成为了华尔街的第一家银行，它在1955年与洛克菲勒的大通银行合并成为大通曼哈顿银行（Chase Manhattan Bank）。
对金钱极度渴望的政府，与热烈期盼政府债务的私有中央银行一拍即合，从中央银行成立的1791年到1796年短短的五年时间里，美国政府的债务就增加了820万美元。
杰斐逊在1798年懊恼地说：“我真希望我们能增加哪怕一条宪法修正案，取消联邦政府借钱的权力。”[20]当杰斐逊当选美国第三届总统（1801～1809）之后，他不遗余力地试图废除美国第一银行，到1811年银行有效期满的时候，双方的角力达到了白热化程度，众议院以65对64仅一票否决了银行授权延期的提案，而参议院是17对17票打平。这次由副总统乔治·克林顿打破僵局投下关键的否决票，美国第一银行于1811年3月3日关门大吉。[21]这时坐镇伦敦的内森·罗斯柴尔德闻讯大发雷霆，他威胁道：“要么给（美国第一）银行授权延期，要么美国将会面对一场最具灾难性的战争。”结果美国政府不为所动，内森立刻回应：“给这些放肆无理的美国人一次教训，把他们打回到殖民地时代。”
结果几个月之后，爆发了英美之间的1812年战争。战争持续了三年，罗斯柴尔德的目的非常明确，要打到美国政府债台高筑，最后不得不屈膝投降，让他们掌握的中央银行继续运作为止。结果，美国政府的债务从4 500万美元增加到12 700万美元，美国政府最终在1815年屈服了，麦迪逊总统在1815年12月5日提出成立第二家中央银行，结果是1816年诞生了美国第二银行（The Bank of the United States）。

国际银行家卷土重来：美国第二银行(1

国际银行家卷土重来：美国第二银行（1816～1832）
银行机构所拥有的对人民意识的支配必须被打破，否则这种支配将打破我们（的国家）。[22]
杰斐逊1815年写给门罗（美国第5届总统）的信
美国第二银行得到了20年的营业授权，这次总股本提高到3 500万美元，仍然是80%由私人占有，剩下的20%属于政府[23]。和第一银行一样，罗斯柴尔德牢牢地把握了第二银行的权力。
1828年，安德鲁·杰克逊参加了总统竞选，在一次面对银行家发表演讲时，他假以颜色地说道：
“你们是一群毒蛇。我打算把你们连根拔掉，以上帝的名义，我一定会将你们连根拔掉。如果人民知道我们的货币和银行系统是何等的不公正，在明天天亮之前就会发生革命。”
当安德鲁·杰克逊在1828年当选总统后，他决心废除第二银行。他指出：“如果宪法授权国会发行货币，那是让国会自己行使这个权力，而不是让国会授权给任何个人或公司。”在11 000人的联邦政府工作人员中，他解雇了2 000多名与银行相关的人员。
1832年是杰克逊总统竞选连任的年头，如果他连任，第二银行的有效期将于1836年（他的下一届任期内）结束。大家都知道总统对第二银行的观感，为了避免夜长梦多，银行想在大选年趁乱提前再延续20年的经营特许权。与此同时，银行家以300万美元的重金不惜血本地资助杰克逊的竞争对手亨利·克雷（Henry Clay），而杰克逊的竞选口号是“要杰克逊，不要银行”。最后杰克逊以压倒性优势获胜。
银行经营权延期的提案在参议院以28对20票获得通过，在众议院以167对85票也成功过关[24]，第二银行主席比德尔自恃有欧洲强大的罗斯柴尔德金融帝国做后援，没有将总统放在眼里。当人们议论杰克逊可能会否决提案时，比德尔毫不退让地表示：“如果杰克逊否决提案，我将否决他。”
杰克逊总统当然毫无疑问地否决了第二银行延期的提案，他还下令财政部长将所有政府储蓄从第二银行账户上立即取走，转存进各州银行。1835年1月8日，杰克逊总统还清了最后一笔国债，这是历史上美国政府唯一的一次将国债降到了0，并且产生了3 500万美元的盈余。历史学家评论这一伟大成就为“这是总统最为灿烂的荣誉，也是他为这个国家做出的最重要的贡献”。《波士顿邮报》把这一成就和耶稣将放贷者（Money Changers）赶出神庙相提并论。

“银行想要杀了我，但我将杀死银行”

1835年1月30日，美国第7届总统安德鲁·杰克逊来到国会山参加一位国会议员的葬礼。一位来自英国的失业油漆匠理查德·劳伦斯悄悄地跟随着杰克逊总统，在他的口袋里有两把装着上好子弹的手枪。
当总统进入葬礼仪式的房间时，劳伦斯距离总统距离较远，他耐心地等待着更好的时机。仪式结束后，劳伦斯守候在两根柱子之间，那里是总统的必经之地。就在总统经过的一刹那，劳伦斯冲了出来，在距离总统不到两米的地方开了枪，但是手枪炸了膛，子弹没有射出。这时，周围所有人都惊呆了。此时，戎马一生的67岁的杰克逊总统并没有惊慌失措，面对穷凶极恶的杀手，他本能地举起手杖自卫。这时，凶手已掏出第二把手枪开了火，结果仍然是个臭弹。福大命大的杰克逊险些成为美国历史上第一位被刺杀的总统，而两把手枪都发臭弹的概率据说仅为1/125 000。
这位32岁的刺杀者号称自己是英国国王的合法继承人，美国总统杀死了他的父亲，还拒绝让他得到一大笔钱。后来，法庭经过仅仅五分钟的审理就断定此人有精神病，没有追究其法律责任。
从此以后，精神病就成为各种谋杀凶手最合适的借口了。
1835年1月8日，杰克逊总统还清了最后一笔国债，1月30日就发生了刺杀事件。关于凶手理查德·劳伦斯，格里芬在他的书中写道：“那个刺客要么是真的疯了，要么是假装疯了来逃避严厉的惩罚。后来，他向别人夸口说他和欧洲有权势的人有联系，他得到许诺，如果被抓住将会得到保护。”[25]
1845年6月8日，杰克逊总统去世。他的墓志铭上只有一句话：“我杀死了银行。”
美国中央银行的再度被废，招致英国方面的严厉报复，英国立刻停止了对美国的各种贷款，尤其厉害的撒手锏是收紧美国的黄金货币供应量。当时的英国金融体系在罗斯柴尔德的运作下，拥有最大规模的黄金货币流通量，通过贷款和美国中央银行的运作，完全控制了美国的货币供应。
当美国第二银行的延期申请遭到总统否决之后，第二银行主席比德尔对总统的“否决”启动了。第二银行宣布立即召回所有贷款，停止一切新贷款的发行。罗斯柴尔德家族所把持的欧洲主要银行也同时收紧了美国银根，美国陷入了严重的“人为”货币流通量剧减的境地，最终引发了“1837年恐慌”，经济陷入严重衰退长达五年之久，其破坏力之大前所未见，直追1929年美国大萧条时期。
“1837年恐慌”以及后来的“1857年恐慌”、“1907年恐慌”，再次印证了罗斯柴尔德的一句名言：“只要我能控制一个国家的货币发行，我不在乎谁制订法律。”
1850年7月4日，泰勒总统参加了在华盛顿纪念碑前举行的国庆活动。当天的天气非常炎热，泰勒喝了些冰镇牛奶，又吃了几颗樱桃，结果有些闹肚子，到7月9日，这位健康魁梧的总统又神秘地死去了。
如此区区小病害得两位军人出身的总统死得不明不白，当然会引起人们的关注。史学界为此争论达百年之久。1991年，在征得泰勒总统后人的同意后，他的遗体被挖掘出来，总统的指甲和头发经过化验，结果果然发现了砒霜，但当局很快下了少量的砒霜不足以致命的结论，然后匆匆结案。没有人知道为什么总统的体内会有这些砒霜。

国际银行家再度出手：“1857年恐慌”

由于1836年美国第二银行的关闭而导致国际银行家突然出手，猛抽美国流通的金属货币，造成了美国持续五年的严重经济危机。虽然在1841年，国际银行家的代理人曾两次试图恢复私有中央银行体系，但都没有成功，双方陷入僵局，美国的货币紧缩状态直到1848年才开始得到缓解。
情况开始好转的原因当然不是由于国际银行家大发慈悲，而是由于1848年，美国加州发现了巨大的金矿—旧金山。
从1848年开始，持续九年美国的黄金供应量空前增长，仅加州就生产出价值5亿美元的金币。1851年澳大利亚也发现了大量金矿，世界范围内的黄金供应量由1851年的1.44亿先令猛增到1861年的3.76亿先令。而美国国内的金属货币流量从1840年的8 300万美元猛增到1860年的2.53亿美元[28]。
美国和澳大利亚的黄金大发现打破了欧洲金融家对黄金供应量的绝对控制。被紧紧扼住货币供应量的美国政府长长地舒了一口气。大量优质货币的供应大大增强了市场信心，银行重新开始大规模扩张信贷，美国许多重要的工业、矿山、交通、机械等国家财富最重要的基础都是在这一段黄金般的岁月里确立的。
眼看金融遏制难以奏效，国际银行家早已有了新的对策。那就是，金融上控制，政治上分化。
早在危机结束之前，他们已经开始着手低廉地吸纳美国的优质资产，到1853年美国经济蒸蒸日上时，外国资本，尤其是英国资本已经拥有了美国联邦国债的46%，各州债券的58%，美国铁路债券的26%[29]，从而再度给美国经济套上了笼头，中央银行制度一旦就位，美国经济就和欧洲其他国家一样被银行家们所控制了。
国际银行家再度施展他们的绝技，先使劲发放信贷，把泡沫吹起来，让人民和其他行业拼命创造财富，然后突然猛踩信贷刹车，使得大量企业和人民破产，银行家们就又有了一个好收成。果然，当看到收获的季节到了，国际银行家和他们在美国的代理人携手再度收紧信贷，造成了“1857年恐慌”，出乎他们意料之外，此时的美国国力已非20年前可比，“1857年恐慌”并没有重创美国经济，仅一年就恢复了元气。
当看到美国的实力越来越强大、金融越来越难以操控时，挑动内战、分裂美国就成了国际银行家的当务之急。

美国内战的起因：欧洲的国际金融势力

毫无疑问，把美国分裂成南北两个实力较弱的联邦，是内战爆发前早就由欧洲的金融强权定好了的。
俾斯麦
美国的成长历程充满了国际势力的干预和阴谋，其中尤以国际金融势力对美国的渗透和颠覆最令人惊心动魄，却最不为人所知。
美国历史上发生在其本土的最大规模的战争当属南北战争。这场历时四年的血腥战争，南北双方参战人数多达300万人，占其总人口的10%，其中60万人战死，无数人员受伤，大量财产毁于战火，战争给人民带来的创伤到140多年后的今天仍然没有完全平复。
今天，关于南北战争起源的争论大多围绕着战争的道义问题，即废除奴隶制的正当性，恰如希特尼所说：“如果没有奴隶制，就不会有战争。如果没有对奴隶制的道德谴责，就不会有战争。”[30]
其实，在19世纪中叶的美国，关于奴隶制的争论是经济利益第一，道德问题第二。当时的南方经济支柱就是棉花种植产业和奴隶制，如果废除奴隶制，农场主就不得不按白人劳动力的市场价格支付工资给原来的奴隶，那么整个产业就会陷入亏损，社会经济结构势必崩溃。
如果说战争是政治斗争的延续，那么政治利益冲突的背后正是经济利益的较量。这种经济利益的较量表面上体现为南北方的经济利益差异，但其实质是国际金融势力为分裂新生的美利坚合众国而玩弄“分而制之”（Divide And Conquer）的策略。
与罗斯柴尔德家族有着极深渊源的德国首相俾斯麦说得透彻：“毫无疑问，把美国分成南北两个实力较弱的联邦，是内战爆发前早就由欧洲的金融强权定好了的。”
其实“伦敦、巴黎和法兰克福轴心”的银行家们正是美国南北战争的幕后黑手。
为了挑起美国内战，国际银行家们进行了长期缜密而周详的策划。在美国独立战争之后，英国的纺织工业和美国南方的奴隶主阶层逐渐建立起密切的商业联系，欧洲的金融家们瞧准了这一机会，乘势秘密发展起一个将来可以挑起南北冲突的人脉网络。在当时的南方，到处都是英国金融家的各类代理人，他们和当地的政治势力共同策划脱离联邦的阴谋并炮制各种新闻和舆论。他们巧妙地利用南北双方在奴隶制问题上的经济利益冲突，不断地强化、突出和引爆这一原本并非热门的话题，并最终成功地把奴隶制问题催化成南北双方水火不容的尖锐矛盾。
国际银行家们做好了充分准备，就等战争开打，然后大发战争横财。他们在策动战争的过程中，惯用打法是两面下注，无论谁胜谁负，巨额的战争开支所导致的政府巨额债务都是银行家们最丰盛的美餐。
1859年秋，法国著名银行家所罗门·罗斯柴尔德（詹姆斯·罗斯柴尔德之子）以旅游者的身份从巴黎来到美国，他是所有计划的总协调人。他在美国南北奔走，广泛接触当地政界、金融界要人，不断地把收集到的情报反馈给坐镇英国伦敦的堂兄纳萨尼尔·罗斯柴尔德。所罗门在与当地人士的会谈中，公开表示将在金融方面大力支持南方，并表示将尽全力帮助独立的南方取得欧洲大国的承认。[31]
国际银行家在北方的代理人，是号称纽约“第五大道之王”（The King of Fifth Avenue）的犹太银行家奥古斯特·贝尔蒙特（August Belmont）。他是法兰克福罗斯柴尔德家族银行的代理人，也是该家族的姻亲。1829年，年仅15岁的奥古斯特就开始了银行家生涯，他起初为法兰克福的罗斯柴尔德银行工作，很快便显露了出类拔萃的金融天赋。1832年，他被提拔到那不勒斯的一家银行工作以便历练他国际金融业务的经验。他精通德、英、法、意大利语。他在1837年被派往纽约，由于大手笔吃进政府债券，很快便成为纽约金融界的领袖级人物，并被总统任命为金融顾问。奥古斯特代表英国和法兰克福的罗斯柴尔德银行表态，愿意从金融上支持北方的林肯。
为了增大对北方的军事压力，1861年年底英国增兵8 000人到加拿大，随时准备策应南军的进攻，从北部边界威胁林肯政府。1862年，英国、法国和西班牙联军在墨西哥港口登陆，在美国南方边境地区完成集结，必要时将进入美国南方直接与北方开战。1863年10月3日，法军将领耶列又增兵三万，并占领了墨西哥城。
在战争爆发初期，南方的军事进攻节节胜利，英法等欧洲列强又强敌环伺，林肯陷入了极大的困境。银行家们算准了此时的林肯政府国库空虚，不进行巨额融资战争将难以为继。自1812与英国的战争结束以来，美国的国库收入连年赤字，到林肯主政之前，美国政府预算的赤字都是以债券形式卖给银行，再由银行转卖到英国的罗斯柴尔德银行和巴林银行，美国政府需要支付高额利息，多年积累下来的债务已使政府举步维艰。
银行家们向林肯总统提出了一揽子融资计划并开出了条件，当听到银行家们开出的利息要求高达24%～36%的时候，惊得目瞪口呆的林肯总统立即指着门让银行家们离开。这是一个彻底陷美国政府于破产境地的狠招，林肯深知美国人民将永远无法偿还这笔天文数字的债务。

林肯的货币新政

没有钱就无法进行战争，而向国际银行家借钱无疑是把绞索往自己脖子上套。林肯苦思冥想解决方案。这时，他在芝加哥的老友迪克·泰勒给林肯出了一个主意—政府自己发行货币！
“让国会通过一个法案，授权财政部印发具有完全法律效力的货币，支付士兵工资，然后去赢得你的战争。”林肯问美国人民是否会接受这种新货币，迪克说：“所有的人在这个问题上将别无选择，只要你使这种新货币具有完全的法律效力，政府赋予它们完全的支持，它们将会和真正的钱一样通用，因为宪法授予国会发行和设定货币价值的权力。”
林肯听了这个建议后，大喜过望，立即让迪克筹划此事。这个石破天惊的办法打破了政府必须向私人银行借钱并付高额利息的惯例。这种新货币使用绿色的图案以区别于其他的银行货币（Bank Note），史称“绿币”（Greenback）。这种新货币的独到之处在于它完全没有金银等货币金属做抵押，并在20年里提供5%的利息。
在内战期间，由于这种货币的发行，政府克服了在战争初期严重缺乏货币的状况，极大和高效地调动了美国北方的各种资源，为最终战胜南方奠定了坚实的经济基础。同时，由于这种低成本的货币依法成为北方银行的储备货币，北方的银行信贷得以大幅扩张，军事工业、铁路建设、农业生产和商业贸易都得到了前所未有的金融支持。
1848年以来的黄金大发现，使美国的金融逐渐摆脱了完全被欧洲银行家控制的极端不利的局面，也正是由于有大量的优质货币作为信心基础，林肯的新币才能够广为人民接受，为赢得南北战争的胜利奠定了可靠的金融基础。更加令人吃惊的是，林肯发行的新币并没有造成类似独立战争时期的严重通货膨胀，从1861年内战爆发到1865年战争结束，整个北方的物价指数仅仅温和地从100增长到216。考虑到战争的规模和破坏程度的严重，以及与世界上其他同等规模的战争相比，这不能不说是一种金融奇迹。相反，南方也采用了纸币流通方式，但效果真是天壤之别，南方物价指数在同期从100飙升到2 776。[32]
在整个南北战争期间，林肯政府一共发行了4.5亿美元的新货币。这种新的货币机制运行得如此之好，以至于林肯总统非常认真地考虑要把这种无债货币（Debt Free Money）的发行长期化和法制化。而这一点深深地刺痛了国际金融寡头的根本利益。如果所有政府都不用向银行借钱而“悍然”自己发行货币，银行家对货币发行的垄断将不复存在，银行岂不是要喝西北风了吗？
难怪在听到这个消息后，代表英国银行家的《伦敦时报》立即发表声明：
如果源于美国的这种令人厌恶的新的财政政策（林肯绿币）得以永久化，那么政府就可以没有成本地发行自己的货币。它将能够偿还所有的债务并且不再欠债，它将获得所有必要的货币来发展商业，它将变成世界上前所未有的繁荣国家，世界上的优秀人才和所有的财富将涌向北美。这个国家必须被摧毁，否则它将摧毁世界上每一个君主制国家。
英国政府和纽约银行协会（New York Associations of Banks）愤怒地表示要实施报复。1861年12月28日，他们宣布停止向林肯政府支付金属货币。纽约的一些银行还阻止了黄金储蓄者提取黄金，并宣布撤销用黄金购买政府债券的承诺。美国各地银行纷纷响应，他们跑到华盛顿向林肯总统提出变通方案，建议仍然采取过去的做法，把高利息的债券卖给欧洲银行家们；把美国政府的黄金存到私人银行作为信贷发放的储备，银行家好大发其财；美国政府向工业部门和人民征税去支持战争。
林肯总统理所当然地坚决拒绝了银行家们这个完全不合常理的要求。他的政策深得民心，美国人民踊跃购买了全部债券，并根据法律把它们当做现金使用。
银行家们见一计不成，又生一计。他们发现国会发行林肯新币的法案中并没有提到国债利息的支付是否使用黄金，于是和国会议员达成了一项妥协，即允许用林肯新币购买国债，但利息部分要用金币支付。这是一个完整计划的第一步，先把美国国内的林肯新币和黄金的价值挂钩，而作为当时拥有世界储备货币的英镑系统的欧洲银行家们，拥有远远多于美国的黄金货币。美国银行家和国会的妥协，使国际金融势力利用对美国黄金进出口总量的控制，间接达到了操纵美国货币价值的效果。

林肯的俄国同盟者

在欧洲的国王们于1861年美国内战爆发前后向美洲大量派兵准备分裂美国的最危险的时刻，林肯立刻想到了欧洲君主们的宿敌—俄国。林肯派出特使向沙皇亚历山大二世求救。当沙皇收到林肯的信，他并没有立刻打开，只是在手上掂了掂，然后说道：“在我打开这封信或知道它的内容之前，我将事先同意它所提出的任何要求。”[33]
沙皇准备军事介入美国内战有几方面的原因。一是唇亡齿寒的担忧，在亚历山大二世时期，横扫欧洲的国际金融势力已经叩响了克里姆林宫的大门。银行家们强烈要求比照欧洲“先进”金融国家的经验，成立私有的中央银行，沙皇早已瞧破了其中的秘密，坚决拒绝了这个要求。当看到岌岌可危的另一个反对国际金融势力的林肯总统陷入危险境地时，亚历山大二世如不出手相助，只怕下一个就轮到他了。另一个原因是在美国南北战争爆发之前的1861年3月3日，亚历山大二世宣布了解放农奴的法律，在废除奴隶制方面，双方有些同仇敌忾，惺惺相惜。还有一个原因就是俄国刚在1856年结束的克里米亚战争中败于英法之手，亚历山大二世雪耻之心未泯。
未经宣战，俄国的舰队在里维斯基（Liviski）将军的率领下，在1863年9月24日开进了纽约港。波波夫将军所统领的俄国太平洋舰队在10月12日到达旧金山。对于俄国的行为，基丁·威尔士评论道：“他们是在南方正处于高潮而北方处于低潮时来到的，他们的出现造成了英国和法国的犹豫不决，最终给林肯扭转局面赢得了时间。”
内战结束以后，为了支付俄国舰队总计720万美元的费用，美国政府颇费了一番周折。因为宪法没有授权总统支付外国政府的战争费用，当时的总统约翰逊与俄国达成了以购买俄国阿拉斯加的土地来支付战争费用的协议。这件事在历史上称为“西华德的蠢事”（Seward誷 Folly），西华德是当时的美国国务卿，人们强烈批评他不应该花720万美元去买当时看起来不值一文的荒地。
由于同样的原因，亚历山大二世在1867年被行刺，但没有成功。1881年3月1日，亚历山大二世终于还是死于刺客之手。

谁是刺杀林肯的真凶？

德国的铁血首相俾斯麦曾一针见血地指出：
他（林肯）从国会那里得到授权，通过向人民出售国债来进行借债，这样政府和国家就从外国金融家的圈套中跳了出来。当他们（国际金融家）明白过来美国将逃出他们的掌握时，林肯的死期就不远了。
林肯在解放了黑奴、统一了南方以后，立即宣布南方在战争中所负的债务全部一笔勾销。在战争中一直为南方提供巨额金融支持的国际银行家们损失惨重。为了报复林肯，更是为了颠覆林肯的货币新政，他们纠集了对林肯总统不满的各种势力，严密策划了刺杀行动。最后发现，指派几个行刺的狂热分子实在不是一件困难的事。
林肯遇刺后，在国际金融势力的操纵下，国会宣布废除林肯的新币政策，冻结林肯新币的发行上限为不超过4亿美元。
1972年，有人问美国财政部，林肯发行的4.5亿美元的新币到底节省了多少利息。经过认真计算，几个星期之后财政部的回答是：因为林肯发行美国政府自己的货币，一共为美国政府节省了40亿美元的利息。[34]
美国的南北战争，从根本上看，是国际金融势力及其代理人与美国政府激烈争夺美国国家货币发行权和货币政策的利益之争。在南北战争前后的一百多年时间里，双方在美国中央银行系统的建立这个金融制高点上进行反复的殊死搏斗，前后共有七位美国总统因此被刺杀，多位国会议员丧命。直至1913年，美国联邦储备银行系统的成立，最终标志着国际银行家取得了决定性胜利。
诚如俾斯麦所言：
林肯的死是基督徒世界的重大损失。美国可能没人能够沿着他伟大的足迹前行，而银行家们将会重新掌握那些富有的人。我担心外国银行家以他们高超和残酷的手腕会最终得到美国的富饶，然后用它来系统地腐蚀现代文明。

致命的妥协：1863年《国家银行法》(1)

我在催生《国家银行法》上所起到的作用是我一生中最严重的财政错误。它（《国家银行法》）所产生的（货币供应）垄断将影响这个国家的每一个方面。它应该被废除，但是在此之前，国家将会分裂成两边，人民在一边，而银行家在另一边，这种情况在这个国家的历史上还从未出现过。
所罗门·切斯，美国财政部长（1861～1864）
南北战争爆发以后，林肯拒绝了罗斯柴尔德及其美国代理人利息高达24%～36%的金融绞索，转而授权财政部发行自己的“美国政府券”（United States Notes），又称绿币。1862年2月通过的《法币法案》（Legal Tender Act）授权财政部发行1.5亿绿币，随后又于1862年7月和1863年3月，再度授权财政部发行1.5亿绿币。在内战期间，绿币总共发行了4.5亿。
林肯绿币的发行就像捅了国际银行业的马蜂窝，银行家们对此深恶痛绝，相反，普通人民和其他工业部门则对绿币持非常欢迎的态度，林肯绿币在美国货币系统中一直流通到1994年。
1863年，当战争到了最紧要的关头，林肯需要更多的绿币去赢得战争，他为了获得第三次绿币发行的授权，不得不向国会的银行家势力低头，做出了一个重要的妥协，签署了1863年《国家银行法》。该法案授权政府批准国家银行（National Bank）发行统一标准的银行券（除了发行银行的名称不同），这些银行实际上将发行美国的国家货币。至关重要的一点就是，这些银行以美国政府债券（Government Bond）作为发行银行券的储备金，实际上将美国的货币发行和政府债务死锁在一起，政府将永远不可能还清债务。
美国著名经济学家约翰·肯尼斯·加尔布雷斯（John Kenneth Galbraith）就曾一针见血地指出：“在内战结束以后的许多年里，联邦政府财政每年都获得了大量盈余。但是，它却无法还清它的债务，清偿发售出的政府债券，因为这样做意味着没有债券去做国家货币的抵押。还清债务就等于摧毁了货币流通。”
国际银行家把英格兰银行模式复制到美国的阴谋终于得逞了。从此偿还美国政府永久的和永远增加的债务利息，就像一根绞索牢牢地套在美国人民的脖子上，越挣扎越紧。到2006年，美国联邦政府共欠下8.6万亿美元的天文数字的债务，平均每一个四口之家，要摊上11.2万美元的国债，而且国债总额正以每秒两万美元的速度增长！美国联邦政府对国债利息的支出仅次于健康医疗和国防。
从1864年开始，银行家们可以世世代代享用国债利息这一美餐。仅仅是由于政府直接发行货币还是政府发行债券而银行发行货币这一点看似不起眼的差别，就造成了人类历史上最大的不公平。人民被迫向银行家间接缴税，为了原本是他们血汗劳动所创造的财富和货币！
到目前为止，中国是世界上仅存的为数不多的由政府直接发行货币的国家。政府和人民为此而节省下来的巨额利息开支是中国能够高速长期发展不可缺少的重要因素。如果有人提出要学习外国的“先进经验”，人民银行必须用政府的国债作为抵押来发行人民币，中国人民就需要当心了。
林肯并非不知道这个永久的威胁，只是迫于眼前的危机不得不做出权宜之计。
林肯本来打算在1865年获得连任之后废除该法案，结果他在大选获胜之后仅41天就被刺杀。银行家们在国会的势力乘胜追击，必除掉林肯的绿币而后快。1866年4月12日，国会通过了《紧缩法案》（Contraction Act），试图召回所有流通中的绿币，兑换成金币，然后把绿币踢出货币流通领域，恢复国际银行家占绝对优势的金本位体系。
在一个刚刚经过空前战争浩劫百废待兴的国家，没有比实施紧缩货币更为荒谬的政策了。货币流通量从1866年的18亿美元（每人50.46美元），降到1867年的13亿美元（每人44.00美元），1876年的6亿美元（每人14.6美元），最后降到1886年的4亿美元（每人6.67美元），在美国战争创伤亟待医治，经济急需恢复和发展，同时人口大量增加的时期，却人为造成货币供应严重短缺。大多数人民总是觉得繁荣和衰退是经济发展的规律，但事实上操纵在国际银行家手中的货币供应时紧时松才是问题的根源。
1872年冬，国际银行家们派出欧内斯特·塞德（Ernest Seyd）带着大笔金钱从英国来到美国，通过贿赂促成了1873年《硬币法案》（Coinage Act），史称“1873年恶法”（Crime of 1873），欧内斯特本人起草了法案全文，该法案把银币从货币流通中踢了出去，金币成为了货币中唯一的主宰。这一法案无疑对本已严重短缺的货币流通造成了雪上加霜的效应。事后，欧内斯特本人扬扬自得地说：“我1872年冬去了一趟美国，确保了废除银币的硬币法案的通过。我所代表的是英格兰银行董事们的利益。到1873年，金币成为了唯一的金属货币。”
事实上，废除银币在国际货币流通领域的作用，是为了确保国际银行家们对世界货币供应量的绝对控制力。相对于越来越多的银矿发掘，金矿的勘探和产量要稀有得多，在完全掌握了世界金矿开采之后，国际银行家当然不希望难以控制的银币流通量来影响他们主宰世界金融的霸权地位。所以从1871年开始，白银在德国、英国、荷兰、奥地利、斯堪的纳维亚国家被普遍废除，导致各个国家的货币流通量大幅紧缩，从而引发了欧洲长达20年的严重经济大衰退（Long Depression，1873～1896）。
在美国，《紧缩法案》和《硬币法案》直接触发了1873～1879年的经济大衰退。在三年时间里，美国的失业率高达30%，美国人民强烈要求回到林肯绿币和银币共同构成货币的时代。美国民众自发成立了白银委员会（US Silver Commission）、绿币党（Greenback Party）等组织，推动全国恢复银币和金币双轨制，重新发行受到人民欢迎的林肯绿币。
美国白银委员会的报告指出：“黑暗的中世纪时代正是由于货币短缺和价格下降所造成。没有货币，文明就不可能发生，货币供应减少，文明必将消亡。在罗马的基督徒时代，帝国共有相当于18亿美元的金属货币流通，到了15世纪末，（欧洲的）金属货币流通量只剩下了2亿美元。历史表明，没有任何灾难性的变化能够与从罗马帝国坠入黑暗的中世纪相比。”
与之形成鲜明对比的是美国银行家协会（The American Bankers Association）的态度。该协会在发给所有会员的信中指出：
我们建议你们竭尽全力去支持著名的日报和周刊，特别是农业和宗教方面的媒体，坚决反对政府发行绿币，你们要停止资助那些不愿表示反对政府发行绿币的候选人。废除银行发行国家货币或恢复政府发行绿币都将使（国家）能够向人民提供货币，这将严重损害我们作为银行家和放贷者的利润。立刻去约见你们地区的国会议员，要求他们保护我们的利益，这样我们就能够控制立法。[35]
1881年，在一片经济萧条之中上台的美国第20届总统詹姆斯·加菲尔德已经明确地把握了问题的要害，他说道：
在任何一个国家里，谁控制着货币供应，谁就是所有工业和商业的绝对主人。当你明白整个（货币）系统非常容易地由极少数人用这样或那样的方法来控制时，你就不用别人告诉你通货膨胀和紧缩的根源了。
这番话落地才几个星期，加菲尔德总统就被另一个“精神病患者”查尔斯·吉托于1881年7月2日行刺。总统被击中了两枪，最后在9月19日去世。
国际银行家们在整个19世纪中，成功地在欧洲“以神圣的金权取代了神圣的王权”，在美国，“神圣的金权也逐步瓦解了神圣的民权”。国际银行家在与美国民选政府经历了长达百年的激烈较量之后，已经完全占了上风。美国历史学家指出，美国总统的伤亡率比美军诺曼底登陆的第一线部队的平均伤亡率还要高。
当银行家们踌躇满志地手握1863年《国家银行法》时，他们距离最终的目标—在美国完全复制一个英格兰银行的计划只剩一步之遥。一个完全控制美国货币发行的私有的中央银行，一个银行家的银行已经出现在美利坚的地平线上。
注 释
[1] Abraham Lincoln, letter to William Elkins, Nov 21, 1864 (just after the passage of the debt causing National Bank Act [June 3, 1864], right before assassination).
[2] G. Edward Griffin, The Creature from Jekyll Island (American Media, Westlake Village, CA 2002) p393.
[3] Izola Forrester, This One Mad Act (Boston: Hale, Cushman & Flint, 1937), p359.
[4] Glyn Davis, History of Money From Ancient Times to The Present Day (University of Wales Press, 2002), p458.
[5] Ibid., p459.
[6] Adam Smith, Wealth of Nations, 1776, book IV Chapter one.
[7] Congressman Charles G. Binderup, How Benjamin Franklin Made New England Prosperous, 1941. .
Note: Radio address given by Congressman Charles G. Binderup of Nebraska, and was reprinted in Unrobing the Ghosts of Wall Street.
[8] Ibid……
[9] Ibid.
[10] In 1787, when the Continental Congress met to adopt the replacement to the Articles of Confederation, which would become the Constitution, Jefferson誷 address regarding a central banking system.
[11] US Constitution Article I Section 8.
[12] Letter to the Secretary of the Treasury Albert Gallatin (1802).
[13] Allan Hamilton, The Intimate Life of Alexander Hamilton (Charles Scribner誷 Sons 1910).
[14] Quoted by Arthur Schlesinger, Jr., The Age of Jackson (New York: Mentor Books, 1945), p6-7.
[15] Written on April 30, 1781, to his mentor, Robert Morris. Quoted by John H. Makin, The Global Debt Crisis: America誷 Growing Involvement (New York: Basic Books, 1984), p246.
[16] The Writings of Thomas Jefferson (New York: G.P.Putnam & Sons, 1899), Vol. X, p31.
[17] The Basic Writings of Thomas Jefferson (Willey Book Company, 1944), p749.
[18] Glyn Davies, History of Money From Ancient Times to The Present Day (University of Wales Press, 2002), p474.
[19] Ibid., p475.
[20] Thomas Jefferson, Letter to John Taylor of Caroline, 26 November 1798; reproduced in The Writings of Thomas Jefferson v. 10, editted by Lipscomb and Bergh.
[21] Glyn Davies, History of Money From Ancient Times to The Present Day (University of Wales Press 2002), p475-476.
[22] Thomas Jefferson, Letter to James Monroe, January 1, 1815.
[23] Glyn Davies, History of Money From Ancient Times to The Present Day (University of Wales Press 2002), p476.
[24] Ibid., p479.
[25] G. Edward Griffin, The Creature from Jekyll Island (American Media, Westlake Village, CA 2002).
[26] Inaugural Address of President William Henry Harrison March 4, 1841.
[27] Michael F. Holt; The Rise and Fall of the American Whig Party: Jacksonian Politics and the Onset of the Civil War (1999). p272.
[28] Glyn Davies, History of Money From Ancient Times to The Present Day (University of Wales Press 2002), p484.
[29] Ibid., p486.
[30] Sydney E. Ahlstrom, A Religious History of the American People (Yale University Press, 1972), on p. 649.
[31] Jewish History in Civil War, Jewish-American History Documentation Foundation, Inc. 2006.
[32] Glyn Davies, History of Money From Ancient Times to The Present Day (University of Wales Press 2002), p489.
[33] Des Griffin, Descent into Slavery (Emissary Publications, 1980).
[34] Abraham Lincoln and John F. Kennedy by Melvin Sickler.
[35] From a circular issued by authority of the Associated Bankers of New York, Philadelphia, and Boston signed by one James Buel, secretary, sent out from 247 Broadway, New York in 1877, to the bankers in all of the States.
