# -*- org -*-

# Time-stamp: <2011-09-15 19:48:40 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent


美联储：私有的中央银行

一个伟大的工业国家被信用系统牢牢地控制着，这个信用系统高度地集中。这个国家的发展和我们所有的（经济）活动完全掌握在少数人手中。我们已经陷于最糟糕的统治之下，一种世界上最完全、最彻底的控制。政府不再有自由的意见，不再拥有司法定罪权，不再是那个多数选民选择的政府，而是在极少数拥有支配权的人的意见和强迫之下（运作）的政府。
这个国家的很多工商业人士都畏惧着某种东西。他们知道这种看不见的权力是如此的有组织、如此的悄然无形、如此的无孔不入、如此的互锁在一起、如此的彻底和全面，以至于他们不敢公开谴责这种权力。[1]
伍德罗·威尔逊，美国第28届总统
本章导读
不算夸张地说，直到今天，中国可能也没有几个经济学家知道美联储其实是私有的中央银行。所谓“联邦储备银行”，其实既不是“联邦”，更没有“储备”，也算不上“银行”。
多数中国人可能会想当然地认为是美国政府发行着美元，实际情况是，美国政府根本没有货币发行权！1963年肯尼迪总统遇刺后，美国政府最终丧失了仅剩的“白银美元”的发行权。美国政府要想得到美元，就必须将美国人民的未来税收（国债）抵押给私有的美联储，由美联储来发行“美联储券”，这就是“美元”。
美联储的性质和来历在美国的学术界和新闻媒体中，是一个大家心照不宣的“禁区”。媒体每天可以长篇累牍地辩论“同性恋婚姻”这类无关痛痒的问题，而对到底谁控制着货币发行这样一个关系到每一个人、每一天、每一分钱收入、每一项贷款利息支付的“利益攸关”的问题，几乎只字不提。
读到这里，如果你有吃惊的感觉，说明这一问题是重要的，而你居然不知道。这一章将讲述被美国主流媒体刻意“过滤掉”的美联储成立的秘密，当我们拿着放大镜，用慢镜头回放这一影响世界历史进程的重大事件的最后关头时，事件发展将精确到以小时为单位。
1913年12月23日，美国民选政府终于被金钱权力所颠覆。

神秘的哲基尔岛：美联储的策源地(1)

1910年11月22日夜，纽约城外一节完全密封的火车车厢里，所有的车窗全部被窗帘严密地遮挡住，列车缓缓向南驶去。车厢里坐着的全是美国最重要的银行家，没有任何人知道他们此行的目的地。列车的终点是数百英里之外的佐治亚州的哲基尔岛。
佐治亚州的哲基尔岛是一群美国超级富豪拥有的冬季度假胜地。以J.P.摩根为首的大腕们成立了一个哲基尔岛打猎俱乐部，地球上1/6的财富聚集在这个俱乐部会员的手中，会员身份只能继承，不可转让。此时，该俱乐部得到通知，有人要使用俱乐部场所大约两个星期，所有会员不能在这段时间内使用会所。会所的所有服务人员全部从大陆调来，对所有到达会所的客人一律只称呼名字，而绝对不能使用姓氏。会所周围50英里的范围内被确保不会出现任何记者。
当一切准备就绪，客人们出现在会所中。参加这个绝密会议的有：尼尔森·奥尔德里奇（Nelson Aldrich），参议员，国家货币委员会主席，尼尔森·洛克菲勒的外祖父派亚特·安德鲁（A. Piatt Andrew），美国财政部助理部长弗兰克·范德利普（Frank Vanderlip），纽约国家城市银行总裁亨利·戴维森（Henry P. Davison），J.P.摩根公司高级合伙人查尔斯·诺顿（Charles D. Norton），纽约第一国家银行总裁本杰明·斯特朗（Benjamin Strong），J.P.摩根的左膀右臂保罗·沃伯格（Paul Warburg），德国犹太移民，1901年到美国，库恩雷波公司（Kuhn Loeb and Company）的高级合伙人，英国和法国的罗斯柴尔德家族的代理人，美联储的总设计师，第一任美联储董事这些重要人物来到这个偏僻的小岛，对来此打猎毫无兴趣，他们的主要任务是起草一份重要的文件：《联邦储备法案》（Federal Reserve Act）。
保罗·沃伯格是银行运作方面的高手，精通几乎所有的银行运作细节。当其他人提出各类问题时，保罗不仅耐心解答，更是滔滔不绝地讲解每一个细节概念的历史渊源。所有的人无不为他在银行方面的渊博知识所折服。保罗自然成为文件的主要起草者和解释者。
尼尔森·奥尔德里奇是所有人中唯一的外行，他负责使文件内容符合政治正确的要求，能够在国会被接受。其他人则代表不同的银行集团的利益，他们围绕着保罗提出的方案细节进行了长达九天的激烈争论，最后终于达成了共识。
由于1907年银行危机以来，银行家在美国人民心目中的形象太差，以至于国会议员中没有人胆敢公开支持由银行家参与制订的法案，所以这些人不远千里从纽约躲到这个僻静的小岛来起草这个文件。另外，中央银行这个名称过于树大招风，自杰斐逊总统以来，中央银行的名称始终与英国的国际银行家阴谋联系过密，所以保罗建议用联邦储备系统（Federal Reserve System）的名称来遮人耳目。但是，它具有一切中央银行的职能，和英格兰银行一样，美联储被设计成私人拥有股份，并将从中获得巨大的利益。与第一银行和第二银行不同的是，美联储的股份构成中，原来20%的政府股份被拿掉了，它将成为一个“纯粹”的私有中央银行。
为了使联邦储备系统更有欺骗性，在谁控制美联储的问题上，保罗巧妙地提出：“国会控制美联储，政府在董事会中拥有代表，但是董事会的多数成员由银行协会直接或间接控制。”
后来，保罗把最后的版本改为“董事会成员由美国总统任命”，但是董事会的真正功能由联邦咨询委员会（Federal Advisory Council）所控制，联邦咨询委员会与董事会定期开会“讨论”工作。联邦咨询委员会成员将由12家联邦储备银行的董事决定，这一点被有意地向公众隐瞒了。
另一个保罗要应付的难题是，如何隐藏纽约的银行家将主导美联储这个事实。19世纪以来，美国中西部广大中小商人、农场主饱受银行危机的浩劫，对东部银行家深恶痛绝，这些地区的议员不可能支持纽约银行家占主导的中央银行。保罗为此设计了一套由12家美联储地区银行构成整个系统的天才解决方案。在银行圈子之外，很少有人明白，在美国货币和信贷发放高度集中于纽约地区这一基本前提下，提议建立各地区联储银行，只不过是给人造成中央银行的业务并没有集中在纽约的假象罢了。
还有一个体现保罗深谋远虑之处的就是将美联储总部设在政治首都华盛顿，而有意远离它真正接受指令的金融之都纽约，以进一步分散公众对纽约银行家的顾虑。
保罗的第四个困扰是如何产生12家美联储地区银行的管理人员，尼尔森·奥尔德里奇的国会经验终于派上了用场。他指出中西部的议员普遍对纽约银行家有敌意，为了避免失控现象，所有地区银行的董事应该由总统任命，而不要由国会插手。但是这造成了一个法律漏洞，《宪法》第一章第八节明确规定由国会负责发行管理货币，将国会排除在外，意味着美联储从一开始就违背了《宪法》。后来这一点果然成为了很多议员攻击美联储的靶子。
在经过这一番颇具匠心的安排以后，该法案俨然以模拟美国宪法分权与制衡的面目出现。总统任命，国会审核，独立人士任董事，银行家做顾问，真是滴水不漏的设计！

华尔街七巨头：美联储的幕后推动者(1)

华尔街的七个人现在控制了美国大部分基础工业和资源。其中J.P.摩根、詹姆斯·希尔、乔治·贝克（纽约第一国家银行的总裁），属于所谓摩根集团；其余四人，约翰·洛克菲勒、威廉·洛克菲勒、詹姆斯·斯蒂尔曼（国家城市银行总裁）、雅各布·希夫（库恩雷波公司），属于标准石油城市银行集团。他们所构成的资本的核心枢纽控制着美国。[2]
约翰·穆迪，穆迪投资评估体系创始人，1911年
华尔街的七位大腕是建立美联储的真正幕后推动者。他们之间及其与欧洲罗斯柴尔德家族的秘密协调，最终建立了英格兰银行在美国的翻版。
摩根家族的兴起
摩根银行的前身是不太为人所知的英国乔治·皮博迪公司（George Peabody and Company）。乔治·皮博迪原是美国巴尔的摩的一个干货商，在发了一些小财之后，于1835年来到英国伦敦闯世界。他瞧准了金融行业是个发财的行业，就开始在伦敦和一些商人一起做起承兑银行（Merchant Bank）的生意，这是当时一种非常时髦的“高级金融”（High Finance）业务，客户主要包括政府、大公司和大富豪们。他们提供国际贸易贷款，发行股票和债券，经营大宗商品，这就是现代投资银行的前身。
乔治·皮博迪通过巴尔的摩的布朗兄弟公司在英国分号的引荐，很快打入了英国的金融圈子。不久，乔治·皮博迪非常吃惊地收到内森·罗斯柴尔德男爵的邀请前去做客。诚惶诚恐的乔治·皮博迪觉得能被名震世界银行界的内森请去做客，就好像天主教徒被教皇接见一般荣幸。
内森开门见山地提出希望乔治·皮博迪帮他一个忙，做罗斯柴尔德家族的秘密公关代理人。罗斯柴尔德家族由于在欧洲巧取豪夺，虽然家财万贯，可也被很多人痛恨和鄙视。伦敦的贵族阶级就不屑于与内森为伍，屡次拒绝内森的邀请，虽然罗斯柴尔德在英国势力很大，但始终有些被贵族孤立的感觉。内森看中乔治·皮博迪的另一个原因是他为人谦和，人缘颇佳，又是美国人，日后还可以派上大用场。
乔治·皮博迪对内森的提议自然是满口应承，所有公关开销全由内森买单，乔治·皮博迪的公司很快就成为伦敦著名的社交中心。特别是每年7月4日在乔治·皮博迪家举办的美国独立节宴会，更是伦敦贵族圈子里的一件盛事[2]。客人们可能没有想到，富丽堂皇和气派奢华的招待开销，岂是一个几年前还名不见经传的普通商人所能负担得起的。
直到1854年，乔治·皮博迪还只是一个百万英镑级别的银行家，在短短的六年之内，他却发了一笔近2 000万英镑的横财，一举成为美国重量级的银行家。原来在罗斯柴尔德家族策动的美国1857年经济危机中，乔治·皮博迪由于大量投资于美国铁路债券和政府债券，当英国的银行家突然狂抛和美国沾边儿的一切债券时，乔治·皮博迪也被深度套牢。奇怪的是，英格兰银行在他濒临破产边缘的时候，仿佛天使从天而降，紧急提供了80万英镑的信用额度，不仅把他从死神身边夺了回来，更鬼使神差般地使一贯极端谨慎和早已失魂落魄的乔治·皮博迪赌上全部身家，大笔吃进被惊恐万状的美国债券投资者当做垃圾抛售的各类债券。1857年的危机全然不同于1837年的十年萧条，仅一年时间，美国的经济就完全走出衰退的阴影，结果，乔治·皮博迪手中的美国债券使他很快成为超级富豪，这与1815年内森的英国国债战役惊人的相似。在没有内线准确信息的情况下，刚从破产噩梦中惊醒过来的乔治·皮博迪，是断然不敢大量吃进美国债券的。
乔治·皮博迪一生没有子嗣，庞大的产业无人继承，他为此煞费苦心，终于决定邀请年轻的朱尼厄斯·摩根（Junius Morgan）入伙。在乔治·皮博迪退休以后，朱尼厄斯·摩根接掌了全部生意，并将公司改名为朱尼厄斯·摩根公司（Junius S. Morgan and Company），仍然设在伦敦。后来，朱尼厄斯的儿子J.P. 摩根接掌了公司，后来他将美国的分支改名为J.P.摩根公司。1869年，J.P.摩根和佐格索（Drexel）在伦敦与罗斯柴尔德家族会面，摩根家族完全继承了乔治·皮博迪与罗斯柴尔德家族的关系，并将这种合作发展到一个新的高度。1880年，J. P. 摩根开始大量资助重组铁路公司的商业活动。
1891年2月5日，罗斯柴尔德家族和英国的其他一些银行家成立了秘密组织“圆桌会议集团”，美国也建立了相应的组织，牵头的就是摩根家族。第一次世界大战以后，美国的“圆桌会议集团”更名为“外交协会”（Council on Foreign Relation），英国的改为“皇家国际事务协会”（Royal Institute of International Affairs）。美英两国政府的许多重要官员就是从这两个协会中被挑选出来的。
1899年，J.P.摩根和佐格索到英国伦敦参加国际银行家大会。当他们回来时，J.P.摩根已经被指派为罗斯柴尔德家族在美国利益的首席代理人。伦敦会议的结果就是，纽约的J.P.摩根公司，费城的佐格索公司，伦敦的格伦费尔（Grenfell）公司，巴黎的摩根·哈杰斯·希公司（Morgan Harjes Cie），德国和美国的沃伯格公司（M. M. Warburg Company），与罗斯柴尔德家族完全联系在一起了。[3]
1901年，J.P.摩根以5亿美元的天价收购了卡内基的钢铁公司，并组建了世界上第一家市值超过10亿美元的巨无霸—美国钢铁公司（United States Steel Corporation）。J.P.摩根在当时被认为是世界上最富有的人，可是，据国家临时经济委员会（Temporary National Economic Committee）的报告，他仅拥有自己公司 9%的股份。看来，声明赫赫的摩根还只是一个前台人物。
洛克菲勒：石油大王
老约翰·洛克菲勒在美国历史上是一个颇有争议的人物，被人们冠以“最冷酷无情的人”。他的名字自然和大名鼎鼎的标准石油公司密不可分。
洛克菲勒的石油生涯开始于美国内战时期（1861～1865），直到1870年他成立美国标准石油公司时，生意做得仍然属于一般水准。自从得到克里夫兰国家城市银行的一批种子贷款后，他好像一下子找到了感觉，尤其是在恶意竞争方面展现出超乎常人的想象力。在他非常看好的石油精炼行业中，他很早就悟出石油精炼虽然短期利润极高，但由于缺乏控制的激烈竞争，终将陷入自杀般的恶性竞争。办法只有一个，毫不留情地消灭竞争对手，为此目的可以不惜一切手段。
具体方法是，首先由受其控制但不为人所知的中间公司提出用现金低价收购竞争对手，如果遭到拒绝，竞争对手将面临惨烈的价格战，直到对方屈服或破产。如果还不奏效，洛克菲勒最后将使出撒手锏：暴力破坏。殴打竞争对手的工人，放火焚烧对手厂房等，几个回合下来，幸存者寥寥无几。如此霸道的垄断行为，虽然引起了同行的公愤，但也招来了纽约银行家的浓厚兴趣。酷爱垄断的银行家非常欣赏洛克菲勒实现垄断的高度执行力。
罗斯柴尔德家族一直煞费苦心想控制日益强大的美国，但屡屡失手。控制一个欧洲的国王比控制一个民选政府要简单得多。美国内战以后，罗斯柴尔德家族开始部署控制美国的计划。在金融业，有摩根银行和库恩雷波公司，在工业界，他们还一直没有物色到合适的代理人选，洛克菲勒的所作所为，让罗斯柴尔德家族眼前一亮。如果在金融方面给予大量输血，洛克菲勒的实力会远远超出小小的克里夫兰地区。
罗斯柴尔德家族派出他们在美国最重要的金融战略家库恩雷波公司的雅各布·希夫（Jacob Schiff）。1875年，希夫亲赴克里夫兰去指点洛克菲勒下一步的扩张计划。希夫带来了洛克菲勒想都不敢想的空前支持，由于罗斯柴尔德此时通过摩根银行和库恩雷波公司已经控制了美国95%的铁路运力，希夫拟定了一个由影子公司（South Improvement Company）出面，给洛克菲勒的标准石油公司提供非常低廉的运费折扣，在这个运费折扣压力之下，没有几家炼油公司还能够继续生存。洛克菲勒很快就完全垄断了美国石油行业，成了名副其实的“石油大王”。
雅各布·希夫：罗斯柴尔德的金融战略家
罗斯柴尔德家族和希夫家族之间的密切关系可以上溯到1785年，当老罗斯柴尔德举家搬到法兰克福的一幢五层楼房时，与希夫家族合住了多年。同为德国犹太银行家，两家有长达百年的情谊。
1865年，年仅18岁的雅各布·希夫在英国罗斯柴尔德银行见习了一段时间以后，来到美国。在林肯总统被刺杀之后，雅各布协调在美国的欧洲银行家代理人之间的利益，共同推动建立美国的私有中央银行制度。他的另外一个目的就是发现、培养欧洲银行的代理人，并将他们输送到政府、法院、银行、工业、新闻等各种重要的位置上，以待时机。
1875年1月1日，雅各布加盟库恩雷波公司，并从此成为公司的核心。在强大的罗斯柴尔德家族支持之下，库恩雷波公司最终成为美国19世纪末和20世纪初最著名的投资银行之一。
詹姆斯·希尔：铁路大王
铁路的建设是严重依赖金融支持的重要基础建设，美国庞大的铁路工业的发展，在很大程度上是仰赖英国和其他欧洲国家的资本市场的金钱才得以实现的。控制美国铁路债券在欧洲的发行，就成为掌握美国铁路工业命脉的直接手段。
1873年，由于国际银行家们对美国突然实施金融紧缩，狂抛美国债券，美国铁路债券也未能幸免。到危机结束的1879年时，罗斯柴尔德家族已成为美国铁路最大的债权人，只要他们高兴，可以随时掐断任何美国铁路公司的金融命脉。在这样的时代背景之下，靠汽船运输和煤矿起家的詹姆斯·希尔必须投靠在金融家的旗下，才可能在铁路行业惨烈的竞争中生存和壮大，摩根正是他背后的金融靠山。在摩根的大力扶持下，利用1873年危机后大量铁路公司倒闭的机会，詹姆斯·希尔实现了迅速兼并和扩张的计划。
到1893年，詹姆斯·希尔拥有横贯美国大陆的铁路的梦想终于实现了。在争夺中西部铁路（Chicago，Burlington and Quincy Railroad）控制权时，詹姆斯·希尔遇到了强大的对手，由洛克菲勒财团支持的太平洋联合铁路（Union Pacific Railroad）向他发动了突然袭击。太平洋联合铁路的总裁哈里曼开始秘密收购詹姆斯·希尔控制的北方太平洋铁路公司（Northern Pacific）的股票，当詹姆斯·希尔惊觉即将失去控制权时，哈里曼还差4万股就大功告成了。詹姆斯·希尔立即向正在欧洲度假的后台老板摩根紧急求救，摩根马上指令手下反击洛克菲勒的挑战。一时间华尔街烽烟四起，对北方太平洋铁路公司股票的争夺达到了白热化的程度，每股价格一度达到1 000美元的天价。
两虎相争必有一伤，最后国际银行家们不得不出面调停，达成的最终结果是成立一家新的控股公司—北方证券公司（Northern Securities Company），两强共同控制美国北方的铁路运输。在公司成立当天，麦金利总统被刺杀，副总统老罗斯福继任。在老罗斯福的强力反对下，北方证券公司被美国1890年通过的《谢尔曼反垄断法》强制解体。受挫之后，詹姆斯·希尔的发展方向掉头向南，收购了从科罗拉多直抵得克萨斯的铁路。到1916年去世时，詹姆斯·希尔积累了5 300万美元的财产。
沃伯格兄弟
1902年，保罗和费里克斯兄弟从德国法兰克福移民到美国。出身于银行世家的两兄弟对银行业务十分精通，尤其是保罗，堪称当时的金融顶尖高手。罗斯柴尔德非常看重保罗的天分，特意从欧洲战略联盟的沃伯格家族银行（M. M. Warburg and Co.）将两兄弟抽调到急需人才的美国战线上。
此时，罗斯柴尔德家族在美国推行私有中央银行的计划已近百年，始终起起伏伏没有最终得手。这一次，保罗将承担主攻任务。在抵达美国不久，保罗加盟先头部队雅各布·希夫的库恩雷波公司，并娶了希夫妻妹的女儿，费里克斯则娶了希夫的女儿。
老罗斯福和威尔逊总统两朝的金融顾问加里森（Colonel Ely Garrison）指出：“在奥尔德里奇计划在全国招致愤恨和反对的情况下，是保罗·沃伯格先生把《美联储法案》重新组合起来的。这两份计划背后的天才智慧都来源于伦敦的阿尔弗雷德·罗斯柴尔德。”[4]

策立美联储的前哨战：1907年银行危机

1903年，保罗将一份如何将欧洲中央银行的“先进经验”介绍到美国的行动纲领交给雅各布·希夫，这份文件随后又被转交给纽约国家城市银行（后来的花旗银行）总裁詹姆斯·斯蒂尔曼和纽约的银行家圈子，大家都觉得保罗的思想真如醍醐灌顶，使大家茅塞顿开。
问题是美国历史上反对私有中央银行的政治力量和民间力量相当强大，纽约银行家在美国工业界和中小业主的圈子里口碑极差。国会的议员们对银行家提出的任何有关私有中央银行的提案都像躲避瘟疫一般避之唯恐不及。在这样的政治气氛中想通过有利于银行家的中央银行法案比登天还难。
为了扭转这种不利的态势，一场巨大的金融危机开始被构想出来。
首先是新闻舆论导向开始大量出现宣传新金融理念的文章。1907年1月6日发表了保罗的文章，题目是“我们银行系统的缺点和需要”，从此保罗成为美国倡导中央银行制度的首席吹鼓手。此后不久，雅各布·希夫在纽约商会宣称：“除非我们拥有一个足以控制信用资源的中央银行，否则我们将经历一场前所未有而且影响深远的金融危机。”[5]
苍蝇不叮没缝的鸡蛋，与1837年、1857年、1873年、1884年和1893年一样，银行家们早已瞧出经济过热发展中出现的严重泡沫现象，这也是他们不断放松银根所导致的必然结果。整个过程形象地说就像银行家在鱼塘里养鱼，当银行家向鱼塘里放水时就是在放松银根，向经济体大量注入货币，在得到大量的金钱之后，各行各业的人就开始在金钱的诱惑之下日夜苦干，努力创造财富，这个过程就像水塘里的鱼儿使劲吸收各种养分，越长越肥。当银行家看到收获的时机成熟时，就会突然收紧银根，从鱼塘中开始抽水，这时鱼塘里的多数鱼儿就只有绝望地等着被捕获的命运。
但是，什么时候开始抽水捞鱼却只有几个最大的银行寡头知道，当一个国家建立了私有的中央银行制度以后，银行寡头对放水抽水的控制就更加得心应手，收获也就越加精确。经济发展与衰退，财富积累与蒸发都成为银行家“科学饲养”的必然结果。
摩根和他背后的国际银行家们精确地计算着这次金融风暴的预估成果。首先是震撼美国社会，让“事实”说明一个没有中央银行的社会是多么脆弱。其次是挤垮和兼并中小竞争对手，尤其是令银行家颇为侧目的信托投资公司。还有就是得到让他们垂涎已久的重要企业。
时髦的信托投资公司在当时享有许多银行不能经营的业务，政府监管方面又非常宽松，这一切导致了信托投资公司过度吸纳社会资金并投资于高风险的行业和股市。到1907年10月危机爆发时，纽约一半左右的银行贷款都被高利息回报的信托投资公司作为抵押投在高风险的股市和债券上，整个金融市场陷入极度投机状态。
摩根在此之前的几个月里一直在欧洲的伦敦与巴黎之间“度假”，经过国际金融家们精心策划，摩根回到美国。不久，纽约突然开始广泛传言美国第三大信托公司尼克伯克（Knickerbocker Trust）即将破产，流言像病毒一般迅速传染了整个纽约，惊恐万状的存款市民在各个信托公司门口彻夜排队等候取出他们的存款。银行则要求信托公司立即还贷，受到两面催款的信托公司只好向股票市场借钱（Margin Loan），借款利息一下冲到150%的天价。到10月24日，股市交易几乎陷于停盘状态。
摩根此时以救世主的面目出现了。当纽约证交所主席来到摩根的办公室求救时，他声音颤抖地表示如果不能在下午三点之前筹集到2 500万美元，至少50家交易商将会破产，他除了关闭股票市场将别无选择。下午两点，摩根紧急召开银行家会议，在16分钟里，银行家们筹足了钱。摩根立即派人到证交所宣布借款利息将以10%敞开供应，交易所里立即一片欢呼。仅过了一天，紧急救助的资金告罄，利息再度疯长。8家银行和信托公司已经倒闭。摩根赶到纽约清算银行，要求发放票据作为临时货币以应付严重的现金短缺。
11月2日星期六，摩根开始了他蓄谋已久的计划，“拯救”仍在风雨飘摇之中的摩尔斯莱（Moore and Schley）公司。该公司已陷入2 500万美元的债务，濒临倒闭。但是它却是田纳西矿业和制铁公司（Tennessee Coal and Iron Company）的主要债权人，如果摩尔斯莱被迫破产清偿，纽约股市将完全崩溃，后果不堪设想。摩根将纽约金融圈子里的大腕悉数请到他的图书馆，商业银行家被安排在东书房，信托公司老总被安排在西书房，惶惶不可终日的金融家们焦急地等待着摩根给他们安排的命运。
摩根深知田纳西矿业和制铁公司拥有的田纳西州、亚拉巴马州和佐治亚州的铁矿和煤矿资源，将大大加强摩根自己创办的钢铁巨无霸—美国钢铁公司的垄断地位。在反垄断法的制约之下，摩根始终对这块大肥肉无法下嘴，而这次危机给他创造了一个难得的兼并机会。摩根的条件是，为了拯救摩尔斯莱公司和整个信托行业，信托公司必须集资2 500万美元来维持信托公司不致崩溃，美国钢铁公司要从摩尔斯莱手中买下田纳西矿业和制铁公司的债权。焦虑烦躁的心情，濒临破产的压力，整夜未眠极度疲倦的信托公司的老总们终于向摩根缴械投降。
在拿到田纳西矿业和制铁公司这块肥肉之后，喜不自胜的摩根还有最后一关要过，那就是对反垄断一点不含糊的老罗斯福总统。11月3日星期天晚上，摩根派人星夜赶往华盛顿，务必在下个星期一上午股票市场开盘之前，拿到总统的批准。银行危机使大批企业倒闭，失去一生积蓄的成千上万愤怒的人民形成了巨大的政权危机，老罗斯福不得不借重摩根的力量来稳定大局，他在最后时刻被迫签下城下之盟。此时距星期一股市开盘仅剩5分钟！
纽约股市闻讯大涨。
摩根以4 500万美元的超低价吃下田纳西矿业和制铁公司，而该公司的潜在价值按照约翰·穆迪的评估，至少在10亿美元左右。[6]
每一次金融危机都是蓄谋已久的精确定向爆破，熠熠夺目的崭新金融大厦总是建筑在成千上万破产者的废墟之上。

从金本位到法定货币：银行家世界观的

大转变
19世纪末以来，国际银行家对金钱的认识再一次实现重大飞跃。
原有的英格兰银行模式，即以国债作为抵押来发行货币，通过两者的死锁，实现政府举债，银行发行货币，确保债务规模越来越大，从而保证了银行家不断增长的巨额收益。在金本位体系之下，银行家坚决反对通货膨胀，因为任何货币贬值都直接伤害了银行家的利息实际收入。这种思路还是比较原始的放贷吃利息的办法，主要的缺点就是财富积累得太慢，即使是用上部分储备金制度（Fractional Reserve），仍然不足以满足银行家们日渐膨胀的胃口。特别是黄金和白银增加缓慢，这就等于给银行放贷总量设了一个上限。
19、20世纪之交的欧洲，银行家们已经摸索出一套更为高效也更为复杂的法定货币体制。法定货币（Fiat Money）彻底摆脱了黄金和白银对贷款总量的刚性制约，对货币的控制更加有弹性，也更加隐秘。当银行家逐渐明白通过无限制地增加货币供应来获得的收益，远比通货膨胀带来的贷款利息损失要大得多时，他们随即成为法定货币最热烈的拥护者。通过急剧增发货币，银行家们等于掠夺了整个国家储蓄者的巨额财富，而比起原来银行强制拍卖别人财产的方式，通货膨胀要“文明”得多，所遇到人民的抵抗也要小得多，甚至难以被人察觉。
在银行家的资助之下，通货膨胀的经济学探讨逐渐被引导到纯数学游戏的轨道上，由于增发纸币所导致的通胀（Currency Inflation）的概念，在现代已经完全被价格上涨的通胀（Price Inflation）理论所淹没。
这时，银行家们赖以发财致富的手段中除了原有的部分储备金制度、货币与国债死锁之外，又增加了一个更为强大的工具：通货膨胀。从此，银行家实现了从黄金的卫道士到黄金的死敌这一戏剧性的转变。
凯恩斯就通货膨胀的评价可谓一针见血：“用这个办法，政府可以秘密地和难以察觉地没收人民的财富，一百万人中也很难有一个人能够发现这种偷窃行为。”
准确地说，在美国使用这个办法的是私有的美联储而不是政府。

1912年大选烽烟(1)

星期二，普林斯顿的校长将会当选你们（新泽西州）的州长。他不会完成他的任期。在1912年11月，他将当选美国总统。1917年3月，他将连任总统。他将是美国历史上最伟大的总统之一。
拉比·怀斯在新泽西的演讲，1910年
这个后来成为威尔逊总统亲密智囊的怀斯能在两年前准确预测总统大选的结果，甚至准确预测六年之后的总统大选结果，并不是因为他的手中真有神奇的水晶球，而是因为所有的结果都是事先由银行家们精确谋划出来的。
不出国际银行家们所料，1907年的银行危机的确极大地震撼了美国社会。人们对信托投资公司的愤怒，对银行倒闭的恐慌，与对华尔街金融寡头势力的畏惧掺和在一起，一股反对一切金融垄断的强大民意潮流席卷全国。
普林斯顿大学校长伍德罗·威尔逊就是一位著名的反对金融垄断的活跃分子。纽约国家城市银行的总裁范德利普曾这样说道：“我写信邀请普林斯顿的伍德罗·威尔逊参加一个晚宴并发表演讲。为了让他知道这是一次重要的机会，我提到了参议员奥尔德里奇也要到场并发表演讲。我的朋友威尔逊博士的回答让我大吃一惊，他拒绝和奥尔德里奇参议员同台发表演说。”[7]
参议员奥尔德里奇当时权倾朝野，他在40年的国会生涯中，有36年为参议员，又是权力极大的参议院金融委员会的主席，身为小约翰·洛克菲勒的岳父，他与华尔街银行界过从甚密。1908年，奥尔德里奇提议在紧急情况下，银行可以发行货币，并以联邦政府、州政府和地方政府的债券和铁路债券做抵押。天下竟有如此好事，风险由政府和人民扛着，好处全是银行家得，让人不得不佩服华尔街的手段。该法案被称为《紧急货币法案》（Emergency Currency Act），这个法案成为五年以后《美联储法案》的立法基础。奥尔德里奇被社会认为是华尔街的代言人。
伍德罗·威尔逊1879年毕业于普林斯顿大学，后进入弗吉尼亚大学深造法律，于1886年在约翰·霍普金斯大学获得博士学位，1902年就任普林斯顿大学校长。学究气十足的伍德罗·威尔逊一贯高调反对金融垄断，自然不肯与金融寡头的代言人亲近。学术上的精深造诣和理想主义的情怀并不能弥补他金融行业知识的极度缺乏，他对华尔街银行家们的赚钱技巧更是一窍不通。
银行家们正是看中了威尔逊的单纯而容易被利用的特点，又是社会公认的反金融垄断的著名活动家，形象清新可人，真是一块难得的璞玉。银行家们准备在他身上投下重金，悉心“雕琢”，以备大用。
正好，纽约国家城市银行的董事克里夫兰·道奇（Cleveland Dodge）是威尔逊在普林斯顿的大学同学，1902年威尔逊能够顺利当上普林斯顿的校长，就是财大气粗的道奇鼎力相助的结果。有了这一层不浅的关系，道奇在银行家们的策划下，开始在华尔街放风说威尔逊是一块当总统的料。
一个上任才几年的校长突然被人捧为是当总统的料，心中一阵窃喜也是人之常情。当然，被捧红总是要付出代价的，威尔逊开始背地里和华尔街黏糊起来。果然，威尔逊很快在华尔街大佬们的扶持下，于1910年当选新泽西州的州长。
在公开的场合下，威尔逊仍然义正词严地抨击华尔街金融垄断，私下里也明白他的地位和政治前途完全要依赖银行家的势力。银行家们对威尔逊的抨击出奇地容忍和克制，双方保持了一种微妙而不可言传的默契。
正当威尔逊声誉日隆的时候，银行家紧锣密鼓地为他筹措竞选总统的经费。道奇在纽约百老汇大道42号设立了为威尔逊筹款的办公室，并建立了银行账户，道奇捐上第一张1 000美元的支票。很快，道奇通过直邮的方式，迅速在银行家的圈子里征集到了大笔经费，其中2/3的经费来源于七个华尔街银行家。[8]
威尔逊在获得总统竞选提名后，难耐激动的心情，他在给道奇的信中说，“我的喜悦无法言表”。自此，威尔逊已经完全扑进了银行家的怀抱。作为民主党候选人的威尔逊肩负着民主党的莫大希望，失去总统宝座多年的民主党对权力的饥渴和威尔逊一样强烈。
威尔逊挑战的是时任总统塔夫特，与当时在全国范围内还名不见经传的威尔逊相比，塔夫特拥有很大的优势。正当踌躇满志准备着连任总统的塔夫特表示不准备对奥尔德里奇法案开绿灯时，一件前所未见的怪事发生了，塔夫特的前任总统老罗斯福突然横刀杀出，居然又要参加总统竞选，这对于老罗斯福自己挑选的接班人和同是共和党的塔夫特而言，真是天大的噩耗。当年老罗斯福因迫使北方证券解体而名声大噪，享有反垄断决不手软的胜誉，他的突然出现将会严重侵蚀塔夫特的选票。
事实上，三个竞选人背后全都是银行家在支持，只不过银行家在三个人中间暗地偏向最具可控制性的威尔逊罢了。在华尔街的安排下，老罗斯福果然“不小心”重创塔夫特，使得威尔逊顺利当选。这一幕和1992年老布什被佩里抢走大量选票而意外地败于新手克林顿有异曲同工之妙。

B计划

银行巨头们在哲基尔岛的策划十分机密，出于严谨的职业本能，他们准备了两份计划。第一份就是由奥尔德里奇参议员主持的计划，负责佯攻，以便吸引反对派的火力，共和党是奥尔德里奇计划的支持者。另一份被称为的方案才是真正的主攻方向，这就是后来的《美联储法案》，民主党是主要推动力量。
其实这两份计划并无本质区别，只是措辞有所不同而已。
总统大选也是围绕这个核心目标而展开的。奥尔德里奇参议员和华尔街的关系是尽人皆知的事，在当时全国普遍强烈地反华尔街的氛围中，他所提出的金融改革法案必然失败。而远离权力中心已有多年的民主党，一直扮演着强烈批评金融垄断的角色，再加上形象清新的威尔逊，这一切使得民主党所支持的《美联储法案》有着更大的机会被接受。1907年的危机设计巧妙地达成了金融体制必须改革的两党共识，为了“顺应”民意，此时银行家们牺牲共和党而成全民主党，就成为逻辑上的必然。
为了进一步迷惑公众，银行家们使出了让实际上是支持同一内容不同版本的两派互相攻击的高招。奥尔德里奇参议员率先发难，他词严色厉地指责民主党的提案对银行怀有敌意，而且不利于政府。他宣称一切背离金本位的法定货币政策都是对银行家的严重挑战。《国家》（Nation）杂志在1913年10月23日指出：“奥尔德里奇先生所反对的没有黄金支撑的政府法定货币，恰恰是他自己在1908年所提出的法案（《紧急货币法案》）所要做的事。他还应该知道，政府事实上与货币发行毫无关系，是联邦储备委员会全权控制着货币发行。”
民主党对奥尔德里奇提案的指责同样令人大开眼界，他们声称奥尔德里奇维护的是华尔街银行家的利益和金融垄断地位，而民主党所提出的美联储提案旨在打破这种垄断，建立起一套地区分立、总统任命、国会审核、银行家提供专家意见的相互制约、分权分立的完美的中央银行系统。不谙金融事务的威尔逊诚心实意地相信这个方案打破了华尔街银行家们对金融的垄断。
正是由于奥尔德里奇和范德利普以及华尔街不遗余力地反对和指责，反而使得民主党的《美联储法案》赢得了民众的好感，银行家们把“明修栈道，暗度陈仓”的计谋发挥到了令人拍案叫绝的程度。

《美联储法案》过关，银行家美梦成真

威尔逊当选总统的同时，B计划正式启动。
1913年6月26日，即威尔逊入主白宫仅三个月，由弗吉尼亚的众议员银行家格拉斯（Carter Glass）在众议院正式抛出了B计划：格拉斯提案（The Glass Bill），他刻意避免了中央银行等过于刺激的用词，代之以美联储。9月18日，该提案在多数众议员不知就里的情况下以287对85票获得通过。
该提案被转送到参议院后变成格拉斯信肺奶岚福℅lass Owen Bill），参议员欧文（Robert L. Owen）也是一位银行家。参议院的提案于12月19日获得通过。此时，两份提案中尚有40多处分歧有待解决，按照两院的惯例，圣诞节前的一周之内不会通过重要法案，按照当时两院提案的差距推算，在正常情况下，只能等到第二年再讨论，所以许多重要的反对该法案的议员纷纷离开华盛顿回家过节去了。
此时，在国会山设有一个临时办公室，在“战地”直接指挥的保罗·沃伯格瞧准了这一千载难逢的时机，发动了一场闪电战。在他的办公室里，每隔一个小时就有一批议员赶到，商讨下一步的计划。12月20日星期六的晚上，参众两院召开联席会议继续商讨重要分歧。此时，国会弥漫着一种不惜一切代价也要在圣诞节前通过《美联储法案》的气氛，白宫甚至在12月17日宣布，已经开始考虑第一届美联储董事成员名单。但是直到20日深夜，重要的分歧一个也未能解决。看起来，要在12月22日星期一通过《美联储法案》已经不太可能了。
在银行家们的催逼之下，联席会议决定21日星期天全天继续开会，不解决问题决不休会。
到20日深夜，参众两院在若干重要问题上仍然没有达成一致。这些分歧包括：美联储地区银行的数量；如何确保储备金；黄金储备的比例；国内国际贸易中的货币结算问题；储备金更改提案；美联储发行的货币能否成为商业银行的储备金；政府债券作为联储货币发行抵押品的比例；通货膨胀问题等。[9]
在经过21日紧张的一天之后，22日星期一《纽约时报》头版登出“货币提案今天可能成为法律”的重要新闻，这篇文章热情洋溢地称赞国会的效率，“以这种几乎是前所未有的速度，联席会议修正了两院提案的差异，在今天早晨全部完工”。这篇文章提到的时间段大约是星期一的凌晨1点30分到4点。一个即将影响每一个美国人的每一天生活的重要法案就是在这样一种仓促和压力之下进行的，绝大多数议员根本没有来得及仔细阅读修改之处，更别说提出修正案了。
22日凌晨4点30分，最后文件被送交打印。
7点整，最后校稿。
下午2点，打印好的文件放在了议员的办公桌上，并通知下午4点开会。
下午4点，会议开始。
6点整，最后联席会议报告提交，此时大多数议员已经去吃晚饭了，会场上的议员寥寥无几。
晚7点30分，格拉斯开始20分钟演讲，然后进入辩论阶段。
晚11点开始表决，最后以298对60票获得众议院通过。
23日，圣诞节前两天，参议院表决以43对25票（27人缺席）通过了《美联储法案》。威尔逊总统为报华尔街的知遇之恩，在参议院通过《美联储法案》仅一小时，就正式签署了该法案。
华尔街和伦敦金融城顿时一片欢腾。
林德伯格（Lindbergh）议员在这一天对众议院发表演讲：
这个法案（《美联储法案》）授权了地球上最大的信用。当总统签署这个法案后，金钱权力这个看不见的政府将被合法化。人民在短期内不会知道这一点，但几年以后他们会看到这一切的。到时候，人民需要再次宣告《独立宣言》才能将自己从金钱权力之下解放出来。这个金钱权力将能够最终控制国会。如果我们的参议员和众议员不欺骗国会，华尔街是无法欺骗我们的。如果我们拥有一个人民的国会，人民将会有稳定（的生活）。国会最大的犯罪就是它的货币系统法案（《美联储法案》）。这个银行法案是我们这个时代最严重的立法犯罪。两党的头头和秘密会议再一次剥夺了人民从自己的政府得到益处的机会。[10]
银行家们对这个法案却好评如潮，美利坚国家银行（American National Bank）的总裁奥利弗（Oliver Sands）热情洋溢地说：这个货币法案的通过将对整个国家带来有益的影响，它的运作将有利于商业活动。在我看来，这是一个普遍繁荣时代的开始。
美联储的始作俑者奥尔德里奇参议员在1914年7月《独立》杂志对他的采访中透露：在这个法案（《美联储法案》）之前，纽约的银行家只能控制纽约地区的资金。现在，他们可以主宰整个国家的银行储备金。
经过与美国政府一百多年的激烈较量，国际银行家终于达到了他们的目的，彻底控制了美国的国家货币发行权，英格兰银行的模式终于在美国被复制成功了。

谁拥有美联储？

许多年以来，究竟谁拥有美联储一直是一个讳莫如深的话题，美联储自己总是含糊其辞。和英格兰银行一样，美联储对股东情况严守秘密。众议员赖特·帕特曼（Wright Patman）担任众议院银行和货币委员会主席长达40年，在其中20年里，他不断地提案要求废除美联储，他也一直在试图发现究竟谁拥有美联储。
这个秘密终于被发现了。《美联储的秘密》（Secrets of Federal Reserve）一书的作者尤斯塔斯（Eustace Mullins）经过近半个世纪的研究，终于得到了12个美联储银行最初的企业营业执照（Organization Certificates），上面清楚地记录了每个联储银行的股份构成。
美联储纽约银行是美联储系统的实际控制者，它在1914年5月19日向货币审计署（Comptroller of the Currency）报备的文件上记录着股份发行总数为203 053股，其中：
?洛克菲勒和库恩雷波公司所控制的纽约国家城市银行，拥有最多的股份，持有3万股。
?J.P.摩根的第一国家银行拥有1.5万股。
当这两家公司在1955年合并成花旗银行后，它拥有美联储纽约银行近1/4的股份，它实际上决定着美联储主席的候选人，美国总统的任命只是一枚橡皮图章而已，而国会听证会更像一场走过场的表演。
?保罗·沃伯格的纽约国家商业银行拥有2.1万股。
?田罗斯柴尔德家族担任董事的汉诺威银行（Hanover Bank）拥有1.02万股。
?大通银行（Chase National Bank）拥有6 000股。
?汉华银行（Chemical Bank）拥有6 000股。
这六家银行共持有40%的美联储纽约银行股份，到1983年，他们总共拥有53%的股份。经过调整后，他们的持股比例是：花旗银行15%，大通曼哈顿14%，摩根信托9%，汉诺威制造7%，汉华银行8%。[11]
美联储纽约银行的注册资本金为1.43亿美元，上述这些银行究竟是否支付了这笔钱仍然是个谜。有些历史学家认为他们只付了一半现金，另一些历史学家则认为他们根本没出任何现金，而仅仅是用支票支付，而他们自己所拥有的美联储的账户上只有几个数字的变动而已，美联储的运作其实就是“以纸张做抵押发行纸张”。难怪有的历史学家讥讽联邦储备银行系统既不是“联邦”，又没有“储备”，也不是银行。
1978年6月15日，美国参议院政府事务委员会（Government Affairs）发布了美国主要公司的利益互锁问题的报告，该报告显示，上述银行在美国130家最主要公司里拥有470个董事席位，平均每个主要公司里有3.6个董事席位属于银行家们。
其中，花旗银行控制了97个董事席位；J.P.摩根公司控制了99个；汉华银行控制了96个；大通曼哈顿控制了89个；汉诺威制造控制了89个。
1914年9月3日，《纽约时报》在美联储出售股份的时候，公布了主要银行的股份构成：
?纽约国家城市银行发行了25万股票，詹姆斯·斯蒂尔曼拥有47 498股；J.P. 摩根公司14 500股；威廉·洛克菲勒1万股；约翰·洛克菲勒1 750股。
?纽约国家商业银行发行了25万股票，乔治·贝克拥有1万股；J.P. 摩根公司7 800股；玛丽·哈里曼5 650股；保罗·沃伯格3 000股；雅各布·希夫1 000股，小J.P. 摩根1 000股。
?大通银行，乔治·贝克拥有13 408股。
?汉诺威银行，詹姆斯·斯蒂尔曼拥有4 000股；威廉·洛克菲勒1 540股。
从1914年美联储建立以来，无可辩驳的事实显示了银行家们操纵着美国金融命脉、工商业命脉和政治命脉，过去如此，现在仍然如此。而这些华尔街的银行家都与伦敦城的罗斯柴尔德家族保持着密切联系。
银行家信托公司（Bankers Trust）的总裁本杰明·斯特朗被选为第一任美联储纽约银行董事会主席。“在斯特朗的控制下，联储系统与英格兰银行和法兰西银行形成了互锁（Interlocking）关系。本杰明·斯特朗作为纽约美联储银行董事于1928年突然死亡，当时国会正在调查美联储董事和欧洲中央银行巨头们的秘密会议，而这些秘密会议导致了1929年经济大衰退。”[12]

美联储第一届董事会

威尔逊后来自己承认，他只被允许指定一名美联储董事，其余都是由纽约的银行家挑选。在保罗·沃伯格被提名和任命为董事的过程中，参议院要求他于1914年6月到国会回答质询，主要是了解他在《美联储法案》拟定过程中的角色，结果被他断然拒绝。保罗在写给国会的信中宣称，如果他被要求回答任何问题，都会影响他在美联储董事会的作用，因此他宁愿拒绝接受美联储董事的提名。《纽约时报》立即跳出来为保罗鸣冤，在其1914年7月10日的报道中谴责参议院不该无中生有地质询保罗。
保罗自然是美联储系统的核心人物，除了他只怕当时没有第二个人知道美联储到底该如何运转。在他强硬的态度面前，国会只有低头，提出可以事前提供所有问题的清单，如果保罗觉得某些问题“会影响他的作用”，他可以不予回答。保罗最后勉强答应了，但要求非正式见面。
委员会问：我知道你是一个共和党人，但是当罗斯福先生参选时，你却成了威尔逊先生的同情者并且支持他（民主党）？
保罗答：是的。
委员会问：但是你的哥哥（费里克斯·沃伯格）却支持塔夫特（共和党）？
保罗答：是的。[13]
有意思的是，库恩雷波公司的三个合伙人却支持了三个不同的总统候选人，其中奥图（Otto Kahn）支持老罗斯福，保罗的解释是他们三人彼此不干涉对方的政治理念，因为“金融与政治无关”。保罗顺利通过国会听证，成为美联储第一届董事，后成为董事会副主席。
除了保罗以外，另外任命的四名董事会成员是：
?阿道夫·米勒（Adolph Miller），经济学家，出身于洛克菲勒资助的芝加哥大学和摩根资助的哈佛大学。
?查尔斯·哈姆林（Charles Hamlin），曾任助理财政部长。
?弗雷德里克·戴拉诺（Frederick Delano），罗斯福的亲戚，铁路银行家。
?哈丁（W. P. G Harding），亚特兰大第一国家银行总裁。
威尔逊总统自己提名的托马斯·琼斯被记者发现正在被美国司法部调查和起诉，后来琼斯自己提出退出董事会提名。
美联储另外两名成员是财政部长和货币审计员。

不为人知的联邦咨询委员会

联邦咨询委员会（Federal Advisory Council）是保罗·沃伯格精心设计的一个秘密的遥控装置，以此操控美联储董事会。在美联储90多年的运作中，联邦咨询委员会非常出色地实现了保罗当年的构想，几乎没有人注意过这个机构和它的运作，也没有大量文献可供研究。
1913年，格拉斯议员在众议院大力推销联邦咨询委员会的概念，他说：“这里面不可能有什么邪恶的东西。每年（联储董事会）与银行家的咨询委员会谈四次，每个成员代表自己所在的联储地区。还有什么比这种安排更能保护公众的利益吗？”格拉斯议员自己就是银行家，他没有解释或提供任何证据来表明银行家在美国的历史上何曾保护过公众的利益。
联邦咨询委员会由12家联储地区银行各推选一名代表组成，每年在华盛顿与美联储董事会的成员会谈四次，银行家们向美联储的董事们提出各种货币政策的“建议”，每名银行家都代表本地区的经济利益，每人都有相同的投票权，在理论上简直无懈可击，但在银行业激烈残酷的现实中却全然是另一套规则。
难以设想一个辛辛那提的小银行家和保罗·沃伯格、摩根这样的国际金融巨头坐在一个会议桌前，向这些巨头提出“货币政策的建议”，这两个巨头中的任何一个随便从口袋里摸出一张支票画上两笔，就足以使这个小银行家倾家荡产。事实上，12个联储地区中的每一个中小银行的生存，都完全取决于华尔街的五大银行巨头的恩赐，五巨头有意地把和欧洲银行的大笔交易化整为零，交给自己在各地的“卫星银行”去办理，“卫星银行”为得到这些高回报的生意自然更加俯首帖耳，而五巨头也拥有这些小银行的股份。当这些“代表各自地区利益”的小银行们和五巨头坐在一处探讨美国货币政策的时候，探讨的结果也就可想而知。
尽管联邦咨询委员会的“建议”对美联储的董事决策没有强制约束力，但是华尔街五巨头每年四次不辞劳苦地跑到华盛顿，不会是仅仅为了和联储的几位董事喝喝咖啡。要知道，像摩根这样身兼63个公司的董事职务的超级大忙人，如果他们的“建议”得不到任何考虑，而他们仍然乐此不疲地来回奔波，那实在是奇怪之极了。

真相何在(1)

绝大多数美国人并不真正理解国际放贷者的运作方式。美联储的账目从来就没有被审计过。它完全在国会控制的范围之外运作，它操纵着美国的信用（供应）。
参议员巴里·戈德华特
为了制造高价格，美联储只需要降低利率，来扩张信用和造就一个繁荣的股市。当工商业已经习惯了这样的利率环境之后，美联储又将通过任意提高利息来中止这种繁荣。
它（美联储和拥有美联储的银行家们）可以通过轻微调息使市场的价格钟摆般温柔地起伏，也可以猛烈调息来使市场价格剧烈波动，无论哪种情况，它将拥有金融状况的内部信息，事先得知即将到来的变化。
这是一种任何政府从未给予的，少数特权阶层所拥有的最怪异和最危险的（市场信息）先知权。
这个系统是私有的，它运作的全部目的就是利用别人的金钱来获得最大限度的利润。
他们事先知道什么时候制造恐慌来创造对他们最有利的情况。他们同样知道什么时候停止恐慌。当他们控制了金融的时候，通货膨胀和通货紧缩在实现他们的目的方面同样有效率。
众议员查尔斯·林德伯格
每一元流通中的美联储券（Federal Reserve Note，美元）都代表欠着美联储一美元的债务。
货币报告，众院银行与货币委员会
美联储地区银行不是政府机构，而是独立的，私人拥有的和地方控制的公司。
刘易斯，1982年
美联储是世界上最为腐败的机构之一。所有能听见我讲话（国会演讲）的人，没有一个人不知道我们的国家实际上是被国际银行家统治着。
有些人以为美联储银行是美国政府的机构。它们（美联储银行）不是政府机构。它们是私有的信贷垄断者，美联储为了自己和外国骗子的利益盘剥着美国人民。
众议员麦克法登
当你和我写支票的时候，我们的账户上必须要有足够的钱来支撑支票的金额。但是，当美联储写支票时，账户上是没有任何钱做支撑的。当美联储写支票时，它是在创造货币。
波士顿美联储银行
从1913年到1949年，美联储的资产由1.43亿美元暴涨到450亿美元，这些钱直接进了美联储银行股东们的腰包。
埃斯塔克·穆林斯
如此众多的总统对金钱权力的威胁反复发出过警告，如此大量的国会记录和法律案例明白无误地说明了美联储的私有性质，可是有多少美国人、中国人和其他国家的人知道这一点呢？这才是问题的可怕之处！我们以为“自由公正”的西方权威新闻媒体会报道一切真相，原来真相是大量的事实被它们有意地“过滤”掉了。那么美国的教科书呢？事实是，各种以国际银行家们的名字命名的基金会，在为美国的下一代挑选着“内容健康”的教科书。
在威尔逊总统去世之前，他承认自己在美联储的问题上是被“欺骗”了，他内疚地表示：“我在无意之中摧毁了我的国家。”
当1914年10月25日美联储正式开始运作时，第一次世界大战爆发了，又一个完美的时间“巧合”，美联储的股东们注定要大发一笔横财了！
注 释
[1] Quoted in "National Economy and the Banking System," Senate Documents Co. 3, No. 23, Seventy-sixth Congress, First session, 1939.
[2] John Moody, The Seven Men, McClure's Magazine, August, 1911, p. 418.
[3] William Guy Carr, Pawns In The Game (Legion for the Survival of Freedom, 1978).
[4] Eustace Mullins, The Secrets of the Federal Reserve (John McLaughlin 1993) Chapter 3.
[5] Paul M Warburg, Defects and needs of our banking system, 1907.
[6] Ron Chernow, The House of Morgan (Groove Press, 1990), p128.
[7] Antony C. Sutton, The Federal Reserve Conspiracy (Tab Books, 1995) p78.
[8] Ibid., p83.
[9] Eustace Mullins, Secrets of Federal Reserve (John McLaughlin, 1993) Chapter 3.
[10] Congressman Charles Lindberg Sr. Speech on floor of the Congress, December 23, 1913.
[11] Eustace Mullins, The Secrets of the Federal Reserve (John McLaughlin 1993) p178.
[12] Ferdinand Lundberg, America誷 60 families (Halcyon House, 1939).
[13] Eustace Mullins, The Secrets of the Federal Reserve (John McLaughlin 1993) Chapter 3.
