# -*- org -*-

# Time-stamp: <2011-09-15 19:49:12 Thursday by ldw>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil H:2

#+STARTUP: indent



* 前 言(1)

起航的中国经济航母，会一帆风顺么？

—写在中国加入WTO五周年、金融全面对外资开放之际

赵煜

2006年，美国财长保尔森在访华前夕接受美国全国广播公司有线电视频道CNBC访问时指出，作为经济大国，“他们已是全球经济的领导者，世界其他国家不会再给他们很多时间”。毫无疑问，这个“他们”，就是中国。

显然，今天的中国，正以惊人的速度，将自己变成全球经济举足轻重的一部分。一系列的经济数据和迹象都表明，庞大的中国经济航母，已经起程。

如果说，三年前政治局请几位学者进京讲授大国崛起的历史，还只是在为中国可以预见的发展做准备，那么从“崛起”到“发展”提法上的变化，就足以看出中国自信心的调整，看出中国经济发展的速度之快，甚至超过了中央电视台那部叫做《大国崛起》的纪录片的拍摄速度。

全世界都把目光对准中国：“21世纪将是中国人的世纪”、“2040年左右，中国的经济实力将赶超美国”，类似的说法不绝于耳，似乎中国成为世界第一经济强国已成定局。

然而，起航的中国经济航母，会一帆风顺么？在未来至关重要的50年内，中国经济能够保持现有的“航速”，勇往直前么？可能影响航向、航线、航程的不可测因素又有哪些呢？

按常规分析，中国这艘巨型航母未来数十年最为险峻的航程是能否平安通过“台湾海峡”，以及在东亚相关海域能否获得制海权。但是，笔者认为，中国能否在21世纪中叶成为世界经济真正强国的最主要隐患，更有可能来自于一个看不见硝烟的战场，即潜在的“金融大战”的威胁。这种威胁的危险度，随着中国加入WTO五年届满、金融业将对外资全面开放而日益加剧。

即将对外资全面开放的中国金融业，有足够的抗打击能力包括实战经验，来防范金融衍生工具等一系列金融手段的“远程精确打击”么？

以海战作比：十年前，中国潜艇逼退美“尼米兹号”航母，2006年10月底，中国“宋级”潜艇再次贴近至美军“小鹰号”战斗群五英里。中国在军力暂时无法与美军抗衡的现实情况下，制订出凭借潜艇战术特性遏制美军航母群的相应战略。同样，在中国迅速发展的今天，我们根本无法保证，某些认为中国强大有损于自身利益的国家不会在经济领域，以金融战争的“核潜艇”，攻击中国这艘已经起航的经济航母，令中国经济发展改变航向和航程。中国在21世纪中叶成为世界强国目前只是常规性的预测，并没有包括对重大突发性事件所可能造成的破坏与阻挠的评估，比如金融战。

金融对外资开放，做个不恰当的比喻，其风险甚至可能大于让美国的所有航母编队开到中国临近海域。因为军事攻击最多摧毁建筑设施、消灭人体，以中国的疆域之广，常规战争几乎不可能造成中国经济命脉的彻底损伤。而金融战争的隐蔽性和无战例借鉴、无实战演练的残酷性，对中国的国家防务是一个巨大挑战。一旦整个国家的经济秩序遭到金融战打击，会迅即造成国内局势动荡，由“外患”引发“内乱”。

历史和现实同样严峻：苏联的解体、卢布的贬值；亚洲金融风暴、“四小龙”们偃旗息鼓；日本经济仿佛被灌了迷魂药似的一蹶不振。我们是否仔细想过：这一切难道只是偶然或者巧合？如果不是，谁是幕后发力的真正推手？谁又可能成为下一个被暗算的目标？最近几个月来，前苏联的特工和能源大亨、欧洲的银行家接二连三被暗杀，这和前苏联的垮台有没有联系呢？决定苏联解体的最主要因素是政治改革还是金融打击？

这不能不令人为中国金融体系的防御能力担忧，进而为中国的经济发展前途担忧。即便暂且搁置人民币汇率和1万亿外汇储备不谈，那么国家层面的、国与国之间游离于正常金融秩序视线之外的政治热钱的博弈，中国到底处于怎样的态势，这不能不成为关注的重中之重。中华文明的善良隐忍，中国反复表达的“和平发展”的理念，能够抵御一贯具有颠覆性和攻击性的“新罗马帝国”的金融入侵么？在现实层面，中国目前是否具有这样的专业人才储备，足以在理论和实践上有效防范潜在的金融攻击呢？如果遭遇隐形的金融“核讹诈”甚至“核攻击”，分布在世界金融领域的中国“海龟”中，会出现钱学森和邓稼先这样的国家栋梁么？

保尔森将到中国进行一项“战略性经济对话”，伯南克也将随行。美国财长和美联储主席同时抵达北京，这种出乎寻常的举动背后的含义又是什么呢？除了人民币汇率，国与国之间还有怎样不为外界所知的“较量”呢？保尔森在接受CNBC访问时强调，为期两天的对话将集中于讨论中国经济迅速崛起所带来的长期挑战。

那么，这种所谓“长期挑战”，是否包括可能的“金融大战”呢？

本书的目的，就在于将世界18世纪以来的重大金融事件背后的黑手曝光出来，回放、观察、体会、对比、总结这些人的战略目的和惯用手法，从而预测他们未来对中国打击的主攻方向，以及探讨中国的反制之道。

战争已经开始，虽然看不见硝烟！
